### ISSUE TITLE
[Bug] 应用发布即初始化部署问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10005]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
应用发布机初始化部署失败，不知道哪里设置有问题

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/44529247/225934347-0711b087-8227-4e40-966e-ec85c4826ec1.png)
![image](https://user-images.githubusercontent.com/44529247/225935361-8f2adee8-5709-42a9-ba54-00dcc1f97613.png)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/44529247/225937178-1b20bd13-d576-4895-8466-65834a90ca80.png">

2.
3.

**Comment by wojiushixiaobai** [comment]
已修复，等待下个版本更新。
当前版本不支持自签证书

**Comment by LeeEirc** [comment]
v3.1.0 已经支持自签证书。有问题再反馈。

**Comment by ryswork1993** [comment]
> v3.1.0 已经支持自签证书。有问题再反馈。
我是3.1.0使用自签证书，出现这个问题是bug吗，还是需要怎么解决
![image](https://user-images.githubusercontent.com/44529247/227463944-cdec3883-a4fd-4ca6-9f70-5ed80fc38666.png)
![image](https://user-images.githubusercontent.com/44529247/227464015-2eeb29c8-9868-4832-8eae-21735182d1a4.png)
![image](https://user-images.githubusercontent.com/44529247/227464050-09f35c75-04f2-40f9-b115-bf5f02623fb8.png)

**Comment by LeeEirc** [comment]
已经选择忽略证书了吗
![image](https://user-images.githubusercontent.com/32626707/227465445-33c00347-78ed-415d-a1e7-a063c82d8564.png)

**Comment by ryswork1993** [comment]
> 已经选择忽略证书了吗 ![image](https://user-images.githubusercontent.com/32626707/227465445-33c00347-78ed-415d-a1e7-a063c82d8564.png)
默认已经勾选忽略证书
<img width="869" alt="image" src="https://user-images.githubusercontent.com/44529247/227467095-ca8b7bec-cb5b-4475-8743-d6d1256fd242.png">

**Comment by ryswork1993** [comment]
> > 已经选择忽略证书了吗 ![image](https://user-images.githubusercontent.com/32626707/227465445-33c00347-78ed-415d-a1e7-a063c82d8564.png)
> > 默认已经勾选忽略证书
> 
> <img alt="image" width="869" src="https://user-images.githubusercontent.com/44529247/227467095-ca8b7bec-cb5b-4475-8743-d6d1256fd242.png">
请问这个问题应该怎么解决啊

**Comment by LeeEirc** [comment]
可能是其他问题，登录发布机，查看目录看下融日志 C:\Users\Administrator\AppData\Local\Programs\Tinker\data\logs

**Comment by ryswork1993** [comment]
> 可能是其他问题，登录发布机，去 tinker 目录，看下日志 C:\Users\Administrator\AppData\Local\Programs\Tinker\data\logs
<img width="365" alt="image" src="https://user-images.githubusercontent.com/44529247/227525243-f1e5b272-97f8-4e3b-bfce-e3c9cbc3ea76.png">
这个目录下没有日志文件

**Comment by LeeEirc** [comment]
命令行手动启动 tinkerd 服务 
```
cd C:\Users\Administrator\AppData\Local\Programs\Tinker
./tinkerd 
```

**Comment by ryswork1993** [comment]
> 



> 命令行手动启动 tinkerd 服务
> 
> ```
> cd C:\Users\Administrator\AppData\Local\Programs\Tinker
> ./tinkerd 
> ```
好像是有报错
<img width="816" alt="image" src="https://user-images.githubusercontent.com/44529247/227822424-e9f2909a-10eb-4060-b21a-014f0aa4d246.png">

**Comment by LeeEirc** [comment]
名称重复注册失败。终端管理页面删掉原来关联的 tinker 终端。如果删除不了，就先删发布机，再删除终端。

**Comment by ryswork1993** [comment]
> 名称重复注册失败。终端管理页面删掉原来关联的 tinker 终端。如果删除不了，就先删发布机，再删除终端。

发布成功了，但是远程web失败
<img width="314" alt="image" src="https://user-images.githubusercontent.com/44529247/227827086-a3787b3a-f4b6-4efd-9517-2c999af43400.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/44529247/227827232-8bbeccb9-37f1-4f9d-aee0-e72e88883a5f.png">

**Comment by ryswork1993** [comment]
> > 名称重复注册失败。终端管理页面删掉原来关联的 tinker 终端。如果删除不了，就先删发布机，再删除终端。
> 
> 发布成功了，但是远程web失败 <img alt="image" width="314" src="https://user-images.githubusercontent.com/44529247/227827086-a3787b3a-f4b6-4efd-9517-2c999af43400.png"> <img alt="image" width="508" src="https://user-images.githubusercontent.com/44529247/227827232-8bbeccb9-37f1-4f9d-aee0-e72e88883a5f.png">

<img width="274" alt="image" src="https://user-images.githubusercontent.com/44529247/227828771-0bba080f-6ec4-440d-8931-bab7b5ca3e7a.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/44529247/227828830-302118e6-d77e-4f9d-a977-52fc29140a6f.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/44529247/227828868-079561c7-e108-47bb-b19b-56692244cfcd.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/44529247/227828899-1a34e16e-d982-41cd-b4e2-8bcb5caf4112.png">

**Comment by ryswork1993** [comment]
> 名称重复注册失败。终端管理页面删掉原来关联的 tinker 终端。如果删除不了，就先删发布机，再删除终端。

<img width="354" alt="image" src="https://user-images.githubusercontent.com/44529247/227829741-51de2bdf-bf4c-4157-86a9-c69b952352b4.png">
<img width="261" alt="image" src="https://user-images.githubusercontent.com/44529247/227829798-dbc09350-5c83-4592-a0e5-b7feec9346a8.png">
![image](https://user-images.githubusercontent.com/44529247/227829834-3ecf51e7-816a-42c1-91c3-c48c5ce317d6.png)

**Comment by maowen295340923** [comment]
这应该是一个bug，我是为了给其他人重新演示一下部署应用发布服务器，于是我删除了旧的应用发布服务器，新的和旧的名称一致，就一直无法部署完成，每一次都卡在wait tinker api health这一步，修改了一个名字后顺利安装。我使用的版本就是3.1.0

**Comment by Userljp** [comment]
命令行手动启动，报这个错是什么问题呢
![Uploading 微信图片_20241114172832.png…]()

**Comment by Userljp** [comment]
命令行手动启动，报这个错是什么问题呢
![8c010d5c140fe3766c8def6cb6df157](https://github.com/user-attachments/assets/231d3fca-e849-4166-a466-4bff71110397)
