### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by a295053193** [jumpserver/jumpserver#10002]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1

**浏览器版本**
chrome Version 108.0.5359.94 (Official Build) (arm64)

**Bug 描述**
在web ui上使用vnc连接macOS机器，画面卡顿严重，画质较差

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/30852312/225867056-48b562a7-f7ea-405a-ae4e-0dff29edb283.png)

2.
3.

**Comment by wojiushixiaobai** [comment]
解决方法1：请将 macOS 分辨率降低，以及将颜色降低为 16 或者 24 位。
解决方法2：请求助 VNC 相关社区，咨询 macOS VNC 的最优设置。

另外：此问题使用原生 VNC 客户端也存在。
