### ISSUE TITLE
Error on in loading docker image

### ISSUE THREAD

**Issue by AhmedBadawi95** [jumpserver/jumpserver#10008]
>>> Loading Docker Image
[jumpserver/redis:6.2]
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

i need ugent help please

**Comment by wojiushixiaobai** [comment]
There may be a problem with your network.

Try the following:
- https://hub.docker.com/r/jumpserver/redis/tags
```sh
docker pull jumpserver/redis:6.2
```

or
- https://github.com/jumpserver/jumpserver/pkgs/container/redis
```sh
docker pull ghcr.io/jumpserver/redis:6.2
docker tag ghcr.io/jumpserver/redis:6.2 jumpserver/redis:6.2
docker rm ghcr.io/jumpserver/redis:6.2
```
