### ISSUE TITLE
发布机初始化部署出现错误, 该如何处理?

### ISSUE THREAD

**Issue by wxf26054** [jumpserver/jumpserver#10006]
![image](https://user-images.githubusercontent.com/22016320/226088398-fd9e78fc-c5c2-40d8-8309-6a1d4fe86c50.png)

**Comment by wojiushixiaobai** [comment]
core api 填写错误，请将 127.0.0.1:8080 更换为 jumpserver 的访问地址

**Comment by wxf26054** [comment]
多谢, 解决了
