### ISSUE TITLE
[Feature] 建议在控制台增加快捷命令功能

### ISSUE THREAD

**Issue by Subp66** [jumpserver/jumpserver#10010]
在控制台增加快捷命令功能，每个登录的用户可以添加快捷命令到自己账户下，其它用户无法使用。
管理员可以添加所有人能看到的命令集。添加的快捷命令结尾如果有换行，执行时自动回车,
如果没有换行，点击后显示在界面上，等待用户按下回车
快捷命令可以用于发送到所有ssh终端, 也可以只发送到当前终端

相对于后台里面工作台的快捷命令，这里更常用，也更方便用户
因为执行完快捷命令，还能继续后续工作，比如用快捷命令执行了环境变量，在未退出前都要用
JumpServer都v3了，建议能考虑加上此功能，感谢!!

![1679193272064](https://user-images.githubusercontent.com/39667572/226150749-0dba3861-13aa-4858-b998-d31419c865e6.jpg)

**Comment by BaiJiangJie** [comment]
很好的一个提议，**快捷命令** 的执行，在设计上我们可能会考虑放到底部。（_发送文本到所有ssh终端..._ 这一块）

到时候会把下面的输入框丰富起来。

当前的一个设想是：

用户在工作台->命令管理中，管理自己的快捷命令。

在 Luna 页面的底部会加在出用户所有的命令列表，用户可以选择命令多所有会话（当前会话）执行快捷命令。

也可以手动输入命令，执行和保存到命令管理中。

**Comment by BaiJiangJie** [comment]
这个功能处理工作量比较大，涉及到的模块也比较多，上线日期会再延迟一下。

**Comment by fikimbing** [comment]
> 起来

这个功能设想挺好的，有预估的上线版本吗？现在都已经3.6版本了

**Comment by BaiJiangJie** [comment]
v3.7、v3.8 支持一下。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。

在 Luna 页面的最下方，升级体验一下。

**Comment by Subp66** [comment]
一段时间的使用，我说一下目前的体验：
1. 保存的命令无法修改，这里建议保存的命令可以在个人工作台有一个界面可以修改或新增等操作
2. 关闭所有控制台后，下面命令行还在
3. 从控制台复制一条命令，写入下面命令行，加＆＆ 再写下一条，写第３条时输入＆＆，包括后面输入的都变成全角了，切换中文，再切换回英文，还是全角输入，占位很宽
4. 保存的命令，选择时不太合适。保存太多时，不知道每个保存的是什么命令，只有保存的名字，可能导致误操作！如果保持这个模式，建议鼠标悬停显示命令内容。
5. 如果支持工作台修改、新增命令，建议控制台命令行那里有刷新功能，可以加载最新修改或新增的命令。
