### ISSUE TITLE
[Feature] 取消网关作为资产自动添加网域功能

### ISSUE THREAD

**Issue by XzBuleSky** [jumpserver/jumpserver#10017]
**请描述您的需求或者改进建议.**

    在我添加网域网关后,   网关作为一台主机被录入到资产中, 代表可以进行登录的操作且网域默认为自己.

    我在网关服务器的防火墙限制了只有Jumpserver的公网IP能访问主机/网关的SSH端口, 在登录网关后发现网关根本无法正常登录.

    我在防火墙中添加了网关自己的公网IP访问自己SSH端口后才可正常登录. 
   
    要么网关不要作为资产, 要么网关作为资产不要添加网域.

**Comment by BaiJiangJie** [comment]
[已修改](https://github.com/jumpserver/jumpserver/pull/10183/files)

v3.2 上线。
