### ISSUE TITLE
[Question] Jumpserver底层数据库支持

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#10019]
Jumpserver 2.28.x现在支持底层数据库使用mysql 8.x版本吗？

**Comment by wml3** [comment]
软件部署的时候，支持使用MySQL8.x版本。
问题二提到的端口是magnus组件使用的端口，该服务端口是给堡垒机纳管的数据库使用，不分类型，在2.27版本是随机分配，建议升级到最新版本，新版本又改回了原有的模式
