### ISSUE TITLE
批量导入资产信息，提示导入成功，但是在资产清单里没有显示

### ISSUE THREAD

**Issue by wb1021** [jumpserver/jumpserver#1001]
[简述你的问题]
批量导入资产信息，提示导入成功，但是在资产清单里没有显示
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Jumpserver版本 0.3.2
##### 问题复现步骤
1. [步骤1]
批量导入资产是，页面提示导入成功，但是在资产里实际没有添加
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
老版本小问题不再修复
