### ISSUE TITLE
[Question] jumpserver管理数据库的问题

### ISSUE THREAD

**Issue by JSXGQ** [jumpserver/jumpserver#10018]
**请描述您的问题.**
jumpserver的数据库的连接配置是动态的么? mysql的连接的过期时间默认300s,可以调大么

**Comment by JSXGQ** [comment]
![0a96d362c9a7c74da067df39ca6d4bd](https://user-images.githubusercontent.com/33593423/226284329-b1678746-0435-4c14-86fe-0fd98ccc9590.png)

**Comment by llussy** [comment]
可以调大，`vim /opt/jumpserver/config/config.txt`  最后增加一行  
CONNECTION_TOKEN_EXPIRATION=300          # client token 连接过期时间 (koko magnus 等组件) v2.23 添加
[官方文档](https://docs.jumpserver.org/zh/master/admin-guide/env/#core)
