### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by a295053193** [jumpserver/jumpserver#10014]
**请描述您的需求或者改进建议.**
增加vnc支持选择本地vnc client
<img width="580" alt="image" src="https://user-images.githubusercontent.com/30852312/226229749-789f941b-b01f-4760-9579-7e79e03ba55f.png">

**Comment by BaiJiangJie** [comment]
如果要支持 VNC Client 的话，需要实现一个 VNC Server。

暂时没有还 VNC Client 的支持计划。
