### ISSUE TITLE
[Feature] 传输文件保留

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#10011]
**请描述您的需求或者改进建议.**
用户通过堡垒机传输的文件，后续是否会考虑文件保留功能，方便对用户传输的文件进行事后追溯。
建议：可以新增是否保留选项，保留文件可定期清理功能

**Comment by BaiJiangJie** [comment]
计划在 v3.3 版本中支持。

**Comment by BaiJiangJie** [comment]
新版本已支持。
