### ISSUE TITLE
发布应用或者连通性测试时总是有这种提示, 是什么原因?

### ISSUE THREAD

**Issue by wxf26054** [jumpserver/jumpserver#10029]
`
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.awx_display.CallbackModule object at
0x7fab3eb91520>): 'utf-8' codec can't encode character '\udcbe' in position
150: surrogates not allowed
`
![image](https://user-images.githubusercontent.com/22016320/226625244-2e23d72d-e641-4c47-9e73-fe0345336a5f.png)

**Comment by LeeEirc** [comment]
对发布机 windows 更新补丁。
