### ISSUE TITLE
[Question] websocket无法连接

### ISSUE THREAD

**Issue by PikuZheng** [jumpserver/jumpserver#10022]
**请描述您的问题.**
严格按照[”源码部署“文档操作](https://docs.jumpserver.org/zh/v3/installation/source_install/requirements/)。websocket无法连接（登陆和资产管理均报错）
![image](https://user-images.githubusercontent.com/12579522/226516028-eb51c5c4-3852-4235-a737-802df8a9caa9.png)
![image](https://user-images.githubusercontent.com/12579522/226516068-be8cbe7a-cb6a-4366-98a6-46b4a2688671.png)

组件显示正常
![image](https://user-images.githubusercontent.com/12579522/226517808-d3562183-2808-4c76-848e-e2b95e06185e.png)

？nginx配置问题？
~？`netstat -alnp` 未发现8070端口监听，core问题？~

**Comment by wojiushixiaobai** [comment]
v3 版本已经不使用 8070 端口，请将 8070 相关的解析到 8080 即可

**Comment by PikuZheng** [comment]
> 请将 8070 相关的解析到 8080 即可

除了[示例文档的nginx配置](https://docs.jumpserver.org/zh/v3/installation/source_install/merge_jumpserver/)，需要额外配置吗？

**Comment by PikuZheng** [comment]
> 此文档里面应该没有 8070 的相关信息才对

没理解您为啥非常在意8070。现在的问题是按文档配置后，报websocket无法连接错误。显然文档中少了一些东西。

**Comment by PikuZheng** [comment]
那么端口号的问题排除了

**Comment by wojiushixiaobai** [comment]
nginx 缺失 ws 相关配置
```
          location /ws/ {
            # 注意将模板中的组件名称替换为服务实际 ip 地址， 如都在本机部署
            # proxy_pass       http://127.0.0.1:8080;
            proxy_pass http://core:8080;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
```
