### ISSUE TITLE
[Bug] ssh服务端禁止使用密码登录，测试资产连接性以及批量命令功能失败

### ISSUE THREAD

**Issue by aaronchou0** [jumpserver/jumpserver#10021]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.9

**浏览器版本**
chrome 
edge

**Bug 描述**
ssh服务端禁止使用密码登录，测试资产连接性以及批量命令功能失败无法连接。但是可以正常登录资产以及其他登录操作。将允许密码登录后以上功能正常。
基本确定是 测试资产连接性以及批量命令功能 使用的是ssh密码进行登录的，而其他功能可使用ssh 私钥登录。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by aaronchou0** [comment]
补充：root用户没有以上问题，只有普通用户有以上问题。当然也可能是我配置的root用户没有配置密码，只配置了ssh 私钥，而普通用户是使用系统托管的，自动生成的密码以及密钥。当同时有密码以及密钥时，使用测试资产连接性以及批量命令会走密码通道而导致失败。

**Comment by BaiJiangJie** [comment]
1. ssh服务端禁止使用密码登录。
2. 测试资产连接性、批量命令功能。

上面2中功能之间没有关联，不会互相影响的。

1. 通过 ssh 登录 JumpServer 时不允许使用密码。
2. 测试可连接性，走的是 Ansible 的逻辑，有密码会使用密码，没有密码会使用密钥。

在这2两个功能之间，root 用户和普通用户是同样的处理逻辑，没有对root进行过特殊处理。

再检查一下 root 账号的配置信息。

另外建议升级到 v3 版本中看看上述情况是否还存在。

当前 Issue 就先关掉了，如果后续依旧存在问题，可以再次打开，然后给出一些复现的步骤。
