### ISSUE TITLE
自定义Applet包上传创建远程应用时总是提示缺少manifest.yml文件. 但是压缩包里有这个文件

### ISSUE THREAD

**Issue by wxf26054** [jumpserver/jumpserver#10025]
自定义Applet包上传创建远程应用时总是提示缺少manifest.yml文件. 但是压缩包里有这个文件
![b36af0d3590015de9a0be4cc5834465](https://user-images.githubusercontent.com/22016320/226528788-0346e015-c9ad-4f20-9524-50f49eb4b5b4.png)
![f8c51f7fb6b53a20f56d9306b200233](https://user-images.githubusercontent.com/22016320/226528798-e158734a-fe03-4b12-9d64-090cae1d8635.png)

**Comment by aaronchou0** [comment]
我的也是这样 还以为要企业版才能支持

**Comment by LeeEirc** [comment]
要压缩整个文件夹，此外内部的文件夹名称也保持一致。

**Comment by wxf26054** [comment]
了解

**Comment by LeeEirc** [comment]
有问题再反馈，先关闭了

**Comment by aaronchou0** [comment]
![image](https://user-images.githubusercontent.com/15139155/227112566-e19def6d-97f2-4084-85f4-1b98dbb7a8e4.png)
压缩文件夹后上传报错，接口返回400错误。会是什么问题

**Comment by xiaoLu3** [comment]
├── app.py
├── build.yml
├── common.py
├── icon.png
├── main.py
├── manifest.yml
├── platform.yml
├── README.md
├── patch.yml
└── setup.yml
想创建应用这几个文件的自己写么》

**Comment by woyeshixiaobai** [comment]
> ![image](https://user-images.githubusercontent.com/15139155/227112566-e19def6d-97f2-4084-85f4-1b98dbb7a8e4.png) 压缩文件夹后上传报错，接口返回400错误。会是什么问题



> ![image](https://user-images.githubusercontent.com/15139155/227112566-e19def6d-97f2-4084-85f4-1b98dbb7a8e4.png) 压缩文件夹后上传报错，接口返回400错误。会是什么问题

你的解决了吗
