### ISSUE TITLE
在系统用户列表删除用户时，删除用户操作未同步到各个服务器

### ISSUE THREAD

**Issue by Debris2017** [jumpserver/jumpserver#1003]
[简述你的问题]
在系统用户列表删除用户时，并未同步删除操作，在服务器上进行用户删除
##### 使用版本

 0.5.0
##### 问题复现步骤
1. 在系统用户列表里新增用户，在服务器上查看是否新增用户；
2. 在系统用户列表里删除用户，在服务器上查看用户是否删除；

##### 具体表现[截图可能会更好些,最好能截全]
新增操作会同步到服务器上，删除操作呢不会同步

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不会删除服务器上系统用户，删除是危险操作，请自己想办法解决
