### ISSUE TITLE
v2.28.1 版本koko sftp连接报错400 

### ISSUE THREAD

**Issue by easonboy** [jumpserver/jumpserver#10030]
1, jumpserver打开文件管理功能一直报400，重启koko服务恢复

![image](https://user-images.githubusercontent.com/25821436/226786909-a5be7aa8-5a54-495f-b46f-14ad407d5c96.png)

2，koko pod 2个节点

3，部署方式使用使用helm

4,  yaml文件

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: jms-k8s
  creationTimestamp: "2022-12-06T09:04:34Z"
  generation: 5
  labels:
    app.jumpserver.org/name: jms-koko
    app.kubernetes.io/instance: jms-k8s
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jumpserver
    app.kubernetes.io/version: v2.28.1
    helm.sh/chart: jumpserver-2.28.1
  name: jms-k8s-jumpserver-jms-koko
  resourceVersion: "428834333"
  uid: dee50170-4ed7-4800-abc8-3a3dde7c53a8
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.jumpserver.org/name: jms-koko
      app.kubernetes.io/instance: jms-k8s
      app.kubernetes.io/name: jumpserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-12-20T11:48:44+08:00"
        redeploy-timestamp: "1671944242635"
      creationTimestamp: null
      labels:
        app.jumpserver.org/name: jms-koko
        app.kubernetes.io/instance: jms-k8s
        app.kubernetes.io/name: jumpserver
    spec:
      containers:
      - env:
        - name: CORE_HOST
          value: http://jms-k8s-jumpserver-jms-core:8080
        - name: BOOTSTRAP_TOKEN
          value: 
        - name: LOG_LEVEL
          value: ERROR
        - name: SSHD_PORT
          value: "2222"
        - name: HTTPD_PORT
          value: "5000"
        - name: REUSE_CONNECTION
          value: "false"
        - name: SHARE_ROOM_TYPE
          value: redis
        - name: REDIS_HOST
          value: 
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: 
        image: docker.io/jumpserver/koko:v2.28.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /koko/health/
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: jms-koko
        ports:
        - containerPort: 5000
          name: web
          protocol: TCP
        - containerPort: 2222
          name: ssh
          protocol: TCP

**Comment by BaiJiangJie** [comment]
看下 koko 服务的日志信息。

**Comment by easonboy** [comment]
重启之后后面还是一直出现（属于间隔性出现的），资产可以正常连接
现在就是一个pod提供服务，也会有这个问题

日志：

010338558d0c18f9_L0RlZmF1bHQ&reqid=187061bc88834e"
2023-03-22 05:38:16 [ERRO] Ws[2340f81d-3db7-48b8-947e-133045cafee1] read data err: websocket: close 1001 (going away)
[GIN] 2023/03/22 - 05:38:16 | 200 |      11h1m12s |      10.1.1.117 | GET      "/koko/ws/elfinder/?type=elfinder&target_id=_"
[GIN] 2023/03/22 - 05:38:42 | 200 |  125.952946ms |      10.1.1.226 | GET      "/koko/elfinder/sftp/"
2023-03-22 05:38:47 [ERRO] Ws[92c4fca3-8013-4c4f-9173-7fc7f2f7ddd6] read data err: websocket: close 1001 (going away)
[GIN] 2023/03/22 - 05:38:47 | 200 |  5.091383862s |      10.1.1.180 | GET      "/koko/ws/elfinder/?type=elfinder&target_id=_"
[GIN] 2023/03/22 - 09:54:06 | 200 |   104.62621ms |       10.1.1.55 | GET      "/koko/terminal/?target_id=ea1af0a6-7ece-487a-acb5-9c32fb457e86&type=ssh&system_user_id=1cfc1203-4bdf-47aa-a63c-35a3f23e4a1b&disableautohash=&_=1679450046446"

**Comment by findlayfeng** [comment]
@easonboy 请问一下你的文件解决了吗？我现在用的是 v4.10.12 版本，似乎问题还存在，我也是集群部署的，上次出现这个问题大约在半年前，一直到现在然后二次出现。。。。。
看半天日志，判断不了诱因
