### ISSUE TITLE
终断在线会话无效

### ISSUE THREAD

**Issue by zhaofei91** [jumpserver/jumpserver#1004]
[简述你的问题]

##### 使用版本
[0.5.0]

##### 问题复现步骤
1. 会话管理-在线会话-终断会话
2. 终断无效，在在线会话里依然存在。
3. 查询数据库 is_finished=0

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/13270279/35848443-2476f544-0b59-11e8-89fb-3b9da32875df.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
下发任务后，coco会在同步心跳时取到任务，不是实时的
