### ISSUE TITLE
[Bug] 更新资产对应的系统平台信息不全

### ISSUE THREAD

**Issue by KaguraRui** [jumpserver/jumpserver#10040]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
如题，更新资产时，系统平台信息不全，只有linux和gateway两个选项（实际有很多系统平台）

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/127723557/226888033-5d4e8b6a-bb3a-4db2-a964-4d6570a9634b.png)

**Comment by BaiJiangJie** [comment]
现在系统平台分为：主机、网络设备、数据库、Web和云服务，五个种类。

每一种类下有分别对应着不同的类型，

比如：主机下分为Linux、Unix、Windows和其他，四种类型。

在更新资产平台时，只允许更新与资产当前平台同类型的系统平台。

比如：资产目前系统平台为 Linux（类型也是 Linux），只允许更新为类型是 Linux 的其他系统平台（比如：自定义 Linux 平台），不能更新为 Windows、Unix 或 其他类型。
