### ISSUE TITLE
[Bug] redis指向外部后重启后统计接口报错

### ISSUE THREAD

**Issue by chestarss** [jumpserver/jumpserver#10047]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
jumpserver-installer-v2.28.6

**浏览器版本**

**Bug 描述**
修改了config.txt将redis指向了外部的redis实例
然后执行jmsctl restart

报错接口
/api/v1/index/?total_count=1

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/11288347/227101040-8c58f3b0-b01f-4ffa-b252-5df784511862.png)
![image](https://user-images.githubusercontent.com/11288347/227101073-e7fca256-9173-4812-8114-cf6bdc0443ca.png)
最终检查是 redis 里少了一个hash
cache.orgs.caches.OrgResourceStatisticsCache.org_00000000-0000-0000-0000-000000000002
请问这个是什么时候创建的，重启不会在新集群创建吗

**Comment by ibuler** [comment]
如果没有的话，会重新计算的，如果没有计算出来，有可能是  celery 存在问题了
