### ISSUE TITLE
[Bug] 系统工具模块Telnet 测试资产连接失败

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#10048]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.7

**浏览器版本**
Chrome 69.0.3497.100（正式版本）

**Bug 描述**
堡垒机服务器直接Telnet 资产成功，使用“系统设置”--“系统工具” Telnet 资产报错。

**Bug 重现步骤(有截图更好)**
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/77430030/227101379-16d3d03c-8173-4f02-8230-8a48493f83c7.png">

**Comment by ibuler** [comment]
系统工具中执行是在容器里，你执行的是在宿主机，所以你应该去容器里执行一下，应该是 docker 网络问题

**Comment by xulinde** [comment]
已复现，下个版本修复～

**Comment by datutu58888** [comment]
> 系统工具中执行是在容器里，你执行的是在宿主机，所以你应该去容器里执行一下，应该是 docker 网络问题

我发现容器的ip 地址是内网的，服务器是公网的，有自动NAT转换吗? 我这telnet 连接也提示

Connecting to 接入设备(admin)@10.10.47.26 14.9
Connecting to 接入设备(admin)@10.10.47.26 error: telnet: handshake failed: read tcp 192.168.250.8:46686->10.10.47.26:23: use of closed network connection
Receive Connection closed
Connection websocket closed

我跟他一样测试工具提示断开连接   

 我的网络结构   192.168.250.8  -->  192.168.12.5  --> 公网ip  然后转向10.10.47.26   网络是通的，因为是内网部署的

**Comment by datutu58888** [comment]
公网ip哪里是做过nat的.且其他资产ssh都没问题

**Comment by datutu58888** [comment]
> 系统工具中执行是在容器里，你执行的是在宿主机，所以你应该去容器里执行一下，应该是 docker 网络问题

我在系统工具里测试，提示跟他一样...

web cli 下面这样提示
Connecting to 接入设备(admin)@10.10.47.26 14.9
Connecting to 接入设备(admin)@10.10.47.26 error: telnet: handshake failed: read tcp 192.168.250.8:46686->10.10.47.26:23: use of closed network connection
Receive Connection closed
Connection websocket closed

容器下其实可以连接，难道是他无法识别用户名密码输入导致超时了?


![QQ图片20230723163405](https://github.com/jumpserver/jumpserver/assets/138114577/5bca9d15-4f11-4aaf-9a89-b53b2154b60b)

**Comment by BaiJiangJie** [comment]
测试的时候要保证 jms_core 容器可以连的通测试的 IP
