### ISSUE TITLE
[Feature] 自定义终端显示的列

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10056]
**请描述您的需求或者改进建议.**
有时候没在电脑旁边的时候，会临时用手机登陆资产处理一些问题，但是手机屏幕较小无法完整显示信息，希望可以自定义要显示的列
![5fbe7aca2465b13c38ac1f3e41b0702](https://user-images.githubusercontent.com/44529247/227230850-e54481a6-98a4-4a20-9b03-22172db39f39.jpg)

**Comment by BaiJiangJie** [comment]
是的，现在不允许配置显示字段。

将来我们考虑增加一个模块“用户个人设置”，
包括：终端资产字段列显示、默认连接资产分辨率等等与个人相关的一些配置。

**Comment by ibuler** [comment]
横屏的话，体验应该会好些

**Comment by ryswork1993** [comment]
> 

横屏也无法正常显示资产名称
![bba6fced4e27cbfa0ce6596e2fe7b17](https://user-images.githubusercontent.com/44529247/227848093-94993f79-f5a4-46f8-9e61-e731eaf8d089.jpg)

**Comment by BaiJiangJie** [comment]
计划在 v3.3 或 v3.4 版本中支持配置显示字段。

**Comment by BaiJiangJie** [comment]
新版本已支持，要在配置文件中指定。
