### ISSUE TITLE
[Bug] 添加Web资产表单问题

### ISSUE THREAD

**Issue by phantomlsh** [jumpserver/jumpserver#10058]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.0 企业版

**浏览器版本**
Google Chrome Version 110.0.5481.181 (Official Build) (64-bit)

**Bug 描述**
- 在添加web资产时，协议总是显示http（端口443时应当改为https）
- 选择器中的placeholder拼写错误login_botton

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/30175757/227354530-1e28fc16-6f36-40a1-84e6-b64b5b8ca530.png)

**Comment by BaiJiangJie** [comment]
嗯，确实有问题；

1. http 修改为 http(s)
2. longin 修改为 login

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/10062

**Comment by BaiJiangJie** [comment]
v3.2 优化。
