### ISSUE TITLE
[Bug] 正在使用中，弹出登录提醒

### ISSUE THREAD

**Issue by harbour015** [jumpserver/jumpserver#10068]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1.0

**浏览器版本**
edge

**Bug 描述**
正在使用，直接弹出了登录提醒

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/48000268/227701135-2da41093-723e-4201-989c-40ce8fa0923a.png)

**Comment by huailei000** [comment]
连接什么类型的资产、用的什么连接方式报的错

**Comment by BaiJiangJie** [comment]
看一下浏览器控制台（检查），网络 tab 下对应的 API 请求体数据和响应数据。@harbour015

**Comment by Subp66** [comment]
这个问题我也遇到过几次，已经开的控制台都不让操作了，只能刷新网页才行。3.0之前版本从未出现过。

**Comment by harbour015** [comment]
> 看一下浏览器控制台（检查），网络 tab 下对应的 API 请求体数据和响应数据。@harbour015
> 
> 偶尔出现，还是频繁出现？

偶尔出现

**Comment by BaiJiangJie** [comment]
@Subp66 @harbour015 嗯，这是 v3 中增加的处理逻辑。

我们没有复现出来，想想办法看能不能稳定复现一下。

**Comment by BaiJiangJie** [comment]
1. 检查浏览器的 API 调用
2. 检查 Core 服务日志：`/data/jumpserver/core/logs/jumpserver.log` 日志文件，应该是调用 API （`/api/v1/authentication/connection-token/`）时有报错信息。

**Comment by BaiJiangJie** [comment]
已修复。建议升级到最新版本使用。
