### ISSUE TITLE
[Question] v3.1，添加数据库资产，测试数据库连接时报错如下，看如何解决谢谢

### ISSUE THREAD

**Issue by fanmaoyang** [jumpserver/jumpserver#10067]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/46638118/227496397-fa7cf069-24dc-494c-b105-7abbc6cdce0e.png)

**Comment by BaiJiangJie** [comment]
python 环境的问题，你是什么部署模式？

**Comment by fanmaoyang** [comment]
> python 环境的问题，你是什么部署模式？

源码单机部署的

**Comment by fanmaoyang** [comment]
> python 环境的问题，你是什么部署模式？

源码编译部署的，目前服务器是可以正常连接访问的，这个是数据库连接测试时报的错

**Comment by fanmaoyang** [comment]
> python 环境的问题，你是什么部署模式？

ln -s /usr/bin/python3 /usr/local/bin/python
谢谢，问题已得到解决
