### ISSUE TITLE
[Bug] 服务器切换资产目录，数量显示问题

### ISSUE THREAD

**Issue by hujx111** [jumpserver/jumpserver#10064]
**JumpServer 版本( v3.1.0 )**

**Bug 描述**
bug-1 服务器更新切换到别的资产目录，更新成功。但是资产目录数量没有变化
bug-2 使用作业管理配置ansible-playbook，遇到有网域的节点会无法执行，报错：the list of known hosts.\r\nPermission denied；目标用户已有sudo 免密

**Bug 重现步骤(有截图更好)**
<img width="679" alt="image" src="https://user-images.githubusercontent.com/43087874/227474213-fdf1c007-2666-4038-844f-0acfd4ca13c1.png">

bug2
<img width="899" alt="image" src="https://user-images.githubusercontent.com/43087874/227475326-e3a7930c-660d-4b60-910f-aa52bfb464d8.png">

**Comment by ibuler** [comment]
bug-1：这个数量是异步计算的，等会儿就对了
bug-2:  测试一下网关的可连接性

**Comment by BaiJiangJie** [comment]
（ansible执行的修改密码任务，报错但是密码已经修改成功）
这种情况在开发、测试阶段，都没有遇到过。

你可以提供一个复现环境吗？

**Comment by BaiJiangJie** [comment]
建议升级到最新版本使用。
