### ISSUE TITLE
[Bug] jumpserver3.0.3 Web终端连接重置

### ISSUE THREAD

**Issue by yc-xiao** [jumpserver/jumpserver#10060]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
谷歌版本 78.0 64 位

**Bug 描述**
1. IP+端口访问正常.
2. 域名访问会出现连接重置.  在Web终端页面抓包时, 发现所有的请求都是指向域名. 而当点击资产连接时,请求指向了IP.

**Bug 重现步骤(有截图更好)**
1. ![](https://share-1308465481.cos.ap-guangzhou.myqcloud.com/test/example/2.png)
2. 点击连接时,请求的URL不是指向域名而是指向IP.

**Comment by BaiJiangJie** [comment]
查看**系统设置**-**终端设置**-**服务端点**/**端点规则**，是不是有对应的端点配置。

**Comment by yc-xiao** [comment]
改了端口也不行, 发起的请求是https, 最终发送的请求是https://ip:8000.

**Comment by BaiJiangJie** [comment]
应该不需要修改端口。

截图看一下这两个 Tab 页的数据。

<img width="2557" alt="image" src="https://user-images.githubusercontent.com/32935519/228744541-7fe42095-0cf7-4ded-b2f8-e64c277fe57a.png">

**Comment by yc-xiao** [comment]
不用，谢谢．
