### ISSUE TITLE
web终端同时打开多台主机容易卡死

### ISSUE THREAD

**Issue by zhaofei91** [jumpserver/jumpserver#1006]
[简述你的问题]
web终端同时打开多台主机容易卡死。
重复多次很容易重现。目前测试使用阶段，这是最简单的场景，复杂场景还没测试。
望回复，谢谢！

##### 使用版本
[0.5.0]

##### 问题复现步骤
1. 同时打开3台主机
2. 只输入回车，然后exit退出。当2台退出后，最后一台终端会卡死。
3. 在卡死状态下终端里输入命令，coco日志里会有命令执行日志输出。

##### 具体表现[截图可能会更好些,最好能截全]
2018-02-07 11:43:01 [session INFO] Session 97a34a05-59e7-423b-aafd-d4e5c93d1798 object has been GC
<coco.recorder.ServerReplayRecorder object at 0x7f78306e16a0> has been gc
2018-02-07 11:43:05 [recorder DEBUG] <Session command recorder 1> queue size: 0
127.0.0.1 - - [07/Feb/2018 11:43:05] "GET /socket.io/?EIO=3&transport=polling&t=M5kMpMh&sid=f5768b68746f404096422462d505e740 HTTP/1.1" 400 -
2018-02-07 11:43:45 [models DEBUG] 
############################## Command ##############################
Input: pwd
Output: /home/admin
##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
0.5有小版本，能否告知，查看方法，Luna 页面左下角，如仅有0.5，那说明是alpha版本，请尝试使用beta版本，同时升级coco

**Comment by zhaofei91** [comment]
版本号   Version 0.5.0-2 GPLv2

**Comment by liuzheng** [comment]
尝试升级Luna和coco
