### ISSUE TITLE
[Question] 开启MFA后，为什么使用密钥登录终端还要输入OTP Code

### ISSUE THREAD

**Issue by Rehtt** [jumpserver/jumpserver#10061]
**请描述您的问题.**
只想登录web使用MFA，而用密钥ssh登录就不用。

而且本地生成的带密码的key在登录的时候不会提示输入密码，直接跳到了要输入OTP

**Comment by BaiJiangJie** [comment]
MFA 是二次认证。

用户登录 JumpServer 时，密码是第一层，第二层是 MFA。

通过 Terminal 登录时，也是一样的。

使用密钥 SSH 登录，只是第一层认证通过了，所以会显示 MFA 等待输入。

如果用户开启了 MFA，那无论是 Web 还是终端都需要认证。

从安全角度来讲，没问题的。
