### ISSUE TITLE
[Bug] 安全隐患 - 用户连接RemoteApp时可能非法获取到上一个用户的RemoteApp权限

### ISSUE THREAD

**Issue by updogliu** [jumpserver/jumpserver#10069]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0 (具售后支持反馈说v2和v3的各个版本均有这个问题)

**浏览器版本**
Chrome

**Bug 描述**
假设用户A有权使用RemoteApp 1；用户B有权使用RemoteApp 2，但是无权使用RemoteApp 1。

用户A刚刚关闭一个RemoteApp 1后，如果用户B马上连接一个RemoteApp 2，这时有一定概率会重用Windows前置机上刚才用户A使用的RDP session。一旦发生，则用户B通过切换窗口或者打开历史页面获得用户A使用RemoteApp 1的浏览器session，进而以用户A的app user操作RemoteApp 1。

**Bug 重现步骤(有截图更好)**
1. 添加一台RemoteApp windows前置机。初始前置机上会自动生成100个windows RDP用户。
2. 删除99个RDP用户，只剩下一个，以方便复现上述Bug。
3. 按照 Bug 描述中，用户A打开一个RemoteApp 1，登录后关闭。然后用户B马上打开另一个RemoteApp 2。
4. 这时用户B已经拿到了用户A的RDP session，可以查看浏览器历史，或者拖动浏览器窗口来看到已登录的RemoteApp 1。
(截图在后面的评论中)

**Comment by updogliu** [comment]
**Bug 分析**
导致该问题的直接原因是Jumpserver用户关闭RemoteApp后，所使用的RDP session在Windows server端并不会马上删掉，而是会有几十秒到1分钟的残留。下一个用户打开一个RemoteApp的时候，Jumpserver会随机给他分配一个windows RDP user。如果随机到的user正好刚才的人一样，那就会重用这个还没有删掉的RDP session。

**可能的几种解决方案：**
1. 给RemoteApp分配windows RDP user的时候，先向Windows server检查一下该user是否还有未删除的session，如果有的话就不要使用该RDP user。
2. (不是很理想，但相对简单) 每一个RDP user在使用结束后，3分钟之内不能再被使用。
3. 支持给JumpServer用户分配固定的windows RDP user，这样给每个Jumpserver用户一个专属的windows RDP user就可以避免被别人拿到RDP session。

**Sidenote**
务请重视这个Bug，因为RemoteApp资产管理的往往是各系统 admin 级别的应用权限，一旦被非法获取，影响很严重。而且，现在这种开一大堆RDP user来减少随机分配到同一个RDP user的设计显的很不专业，不是一个严肃的 PAM (Privileged access management) 系统该有的设计。修复过程中有能帮的上忙的我们愿意积极配合。

**Comment by LeeEirc** [comment]
我理解 Windows 的 RemoteApp，就算是同一个用户打开，也是不同的程序界面。基于目前 v3 的实现，每次打开的都是新的 Chrome 实例，应该无法查看到上一个会话才对。
创建多个 RDP user 是为了隔离 RemoteApp 应用。

**Comment by updogliu** [comment]
复现截图如下

JumpServer用户zihan有只有keycloak的权限
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/1288299/227830167-377b0150-280b-4f6e-a3be-6c77f093bbea.png">

用户kun有访问keycloak和gitlab的权限
<img width="1762" alt="2" src="https://user-images.githubusercontent.com/1288299/227830186-269d7501-7d60-413a-be5d-c736850c086b.png">

kun打开gitlab remoteApp，登录gitlab，然后关闭gitlab remoteApp
<img width="1763" alt="3" src="https://user-images.githubusercontent.com/1288299/227830193-8ef17a6a-5f7f-4b0a-9da7-7b77279d2028.png">

30秒内，zihan打开keycloak remoteApp，拖动浏览器窗口，就可以看到gitlab和keycloak两个都登录了。有时gitlab窗口在前面，不需要拖动窗口就直接看到gitlab。
<img width="1916" alt="4" src="https://user-images.githubusercontent.com/1288299/227830200-f1893be4-9d9a-4d21-a3ff-a28dd352c0a4.png">

**Comment by updogliu** [comment]
以上复现时，windows前置机只保留了除admin以外的一个RDP user，以方便复现。
<img width="1052" alt="windows" src="https://user-images.githubusercontent.com/1288299/227833208-e0d143d5-aeba-4e97-9317-064a243775f5.png">

另外Windows有时会有这个错误窗口报出来，拖动开前面的窗口就可以看到。
<img width="633" alt="Screenshot 2023-03-27 at 11 22 57" src="https://user-images.githubusercontent.com/1288299/227833178-9e994663-89a7-49b1-8b17-0aaaa65c11cd.png">

**Comment by LeeEirc** [comment]
> 以上复现时，windows前置机只保留了除admin以外的一个RDP user，以方便复现。 <img alt="windows" width="1052" src="https://user-images.githubusercontent.com/1288299/227833208-e0d143d5-aeba-4e97-9317-064a243775f5.png">
> 
> 另外Windows有时会有这个错误窗口报出来，拖动开前面的窗口就可以看到。 <img alt="Screenshot 2023-03-27 at 11 22 57" width="633" src="https://user-images.githubusercontent.com/1288299/227833178-9e994663-89a7-49b1-8b17-0aaaa65c11cd.png">

嗯，待研究修复这个问题

**Comment by LeeEirc** [comment]
@updogliu  可否进群联系下，帮忙协助远程测试。

**Comment by LeeEirc** [comment]
已解决，待版本更新。
