### ISSUE TITLE
[Bug] 作业管理：选择资产目录节点的时候，无法显示该资产目录下的服务器

### ISSUE THREAD

**Issue by hujx111** [jumpserver/jumpserver#10065]
**JumpServer 版本( v3.1.0 )**
**Bug 描述**
作业管理：选择资产目录节点的时候，无法显示该资产目录下的服务器，只显示所有的服务器

**Bug 重现步骤(有截图更好)**
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/43087874/227478278-ee54aec5-601a-4fae-9c77-1e3156a58d92.png">

**Comment by Aaron3S** [comment]
已解决。 pr:  https://github.com/jumpserver/jumpserver/pull/10075
