### ISSUE TITLE
[Bug] web_cli 登录无反应

### ISSUE THREAD

**Issue by OnionTop** [jumpserver/jumpserver#10066]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1.0

**浏览器版本**
chrome 111.0.5563.111

**Bug 描述**
jumpserver部署在内网机器上，通过nat8080端口映射至公网ip，通过公网ip访问内网的jumpserver。问题在余我通过web终端登录机器时，页面无任何反应，通过等待之后，可以出现一个Login reminder的提示，但是提示内容是空的。

**Bug 重现步骤(有截图更好)**
1.web页面显示如下
![1](https://user-images.githubusercontent.com/83639885/227495872-56353db4-fefe-4755-a8ff-3ac4f9966ea5.jpg)
2、浏览器控制台显示如下报错信息
![kongzhitai](https://user-images.githubusercontent.com/83639885/227496059-b18fb1a7-2b42-46f3-ba89-8d4385cfd786.jpg)

3.浏览器调试模式显示如下信息
![tiaoshi](https://user-images.githubusercontent.com/83639885/227496136-26107a02-cfd4-40b8-b753-26b57686ee40.jpg)

**Comment by BaiJiangJie** [comment]
看看报错的 connection-token/ API 的返回值。

**Comment by OnionTop** [comment]
> 看看报错的 connection-token/ API 的返回值。
> 
> <img width="1390" alt="image" src="https://user-images.githubusercontent.com/32935519/227501601-c97b34c3-3646-4d22-b8b5-e691deb613a8.png">
> 

这个API没有返回任何，好像是不通？

**Comment by OnionTop** [comment]
> 看看报错的 connection-token/ API 的返回值。
> 
> <img width="1390" alt="image" src="https://user-images.githubusercontent.com/32935519/227501601-c97b34c3-3646-4d22-b8b5-e691deb613a8.png">
> 

第一张图显示connection reset了，不知道是不是有别的端口也要nat出来？还是说有别的服务没起来？用jmsctl.sh tail命令也没看到啥错误信息，MySQL和Redis用的都是内置的

**Comment by OnionTop** [comment]
![Dingtalk_20230328103142](https://user-images.githubusercontent.com/83639885/228112086-38783f9e-e3ac-41bc-a127-0bdd966ae6b2.jpg)

**Comment by BaiJiangJie** [comment]
https://help.aliyun.com/noticelist/articleid/1060784724.html?spm=0.2020520154.sas.34.1f88CZChCZCh6i

阿里云-云防火墙
