### ISSUE TITLE
[Feature] 企业微信免密处理工单

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#10076]
**请描述您的需求或者改进建议.**
目前 JumpServer 对接好企业微信，可以在企业微信工作台免密登录 JumpServer 应用，也可接收工单消息
但在企业微信处理工单时，需要登录认证，对企业微信用户体验不友好，能否在处理工单时也能免登录处理？

比如这个链接附带一个 24小时有效的 token
![image](https://user-images.githubusercontent.com/89765365/227880082-7c15ff48-1231-4cff-b73e-379644208637.png)

**Comment by BaiJiangJie** [comment]
不支持免密审批，但是用户只需要登录一次，就可以审批多个工单，并不是每一个工单都需要重新登录。
