### ISSUE TITLE
[Vote] 【投票】支持 v3 版本的 All-In-One 镜像（点赞/回复 超过 100 条将会继续维护）

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#10073]
**投票 【v3 版本对于 All-In-One 镜像的支持】**

对于 JumpServer v2 版本我们是有 All-In-One 镜像的，由于有一些维护成本，所以在 v3 中目前还没有支持。

但是从 Issues 可以看到有一些用户提到了这个问题，所以我们在这里统计一下大家对于 All-In-One 镜像的需求热度，

如果当前 Issue 的 **点赞/回复** 累计超过100 条，那么我们就考虑重启对于 v3 版本的 All-In-One 项目。

_备注：欢迎大家根据自己的实际需求进行投票！！！_

**Comment by dhfsqxz** [comment]
个人认为 All-In-One 镜像没有意义

**Comment by ok-dok** [comment]
我可能需要all-in-one，但是是不是all-in-one对我来说不是很重要，我其实是需要一个docker-compose启动所有依赖组件就可以了，我用Dockefile那个仓库里的allinone改成v3.1.1也能用呀， 没发现什么问题

**Comment by fency12** [comment]
支持，对于小公司没有使用压力，一键快速部署简单便捷。

**Comment by h0we** [comment]
支持，有时候all-in-one很好用，对于个人用户很友好。

**Comment by asd2bsa** [comment]
絕對支持,

**Comment by MilkWangStudio** [comment]
支持，小公司用起来太舒服了

**Comment by luomoxu** [comment]
v2的all-in-one好像也好久没更新了

**Comment by wang-xiaowu** [comment]
+1

**Comment by BaiJiangJie** [comment]
v3 会支持。

**Comment by opslx** [comment]
还是all_in_one好用，k8s直接用省劲

**Comment by maninhill** [comment]
All in one 上架 1Panel 应用商店，以后可以只通过 1Panel 发布 all_in_one 版。

**Comment by wang-xiaowu** [comment]
> All in one 上架 1Panel 应用商店，以后可以只通过 1Panel 发布 all_in_one 版。

为了安装一个运维面板需要再去安装另外一个运维面板吗😢

**Comment by Lensual** [comment]
仔细看了下`jumpserver/Dockerfile`仓库主要是docker compose，对于简化部署来说，docker compose与all in one同样满足一键部署，个人认为没有必要维护all in one。

感觉这个投票有点歧义，到底是不维护`jumpserver/Dockerfile`呢还是不维护`jumpserver/Dockerfile/allinone`呢

**Comment by BaiJiangJie** [comment]
最新版本已支持。https://github.com/jumpserver/Dockerfile
