### ISSUE TITLE
[Bug] 3.0.4 资产列表添加资产报错，密码太长or特殊字符原因？

### ISSUE THREAD

**Issue by Si-ren** [jumpserver/jumpserver#10070]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.4

**浏览器版本**
edge

**Bug 描述**
资产列表添加资产（linux服务器）
密码32位，并且带特殊字符'$?*;=~+，出现报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/47218028/227836640-28b7f9e2-6c62-463c-b108-c74c1e31f2f6.png)

**Comment by BaiJiangJie** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/32935519/228719660-96a1a410-1e1f-44f5-aa97-5597d77ffd9b.png">

**Comment by BaiJiangJie** [comment]
主要原因是密码不能包含 ‘ 特殊字符。

**Comment by SnowsonZ** [comment]
麻烦问下，这个问题解决了吗?在哪个版本解决的？

**Comment by SnowsonZ** [comment]
> 麻烦问下，这个问题解决了吗?在哪个版本解决的？

@BaiJiangJie

**Comment by SnowsonZ** [comment]
版本
![img_v2_18f8ec1c-654a-45e5-8e4a-51f779c6872g](https://github.com/jumpserver/jumpserver/assets/12555482/c02d0956-5fb1-427d-8bdc-f918a49b75ac)

添加 linux主机资产，ssh密码中包含'等特殊字符，保存报错，不能包含'字符。
