### ISSUE TITLE
0.5.0 关于报表显示问题

### ISSUE THREAD

**Issue by qiushaohu** [jumpserver/jumpserver#1008]
[简述你的问题]
在报表或统计过程中，显示名称会不会比显示用户名更直观？
![image](https://user-images.githubusercontent.com/34025457/35909298-16c44fac-0c2e-11e8-9b8c-a2a805d3bb0c.png)

##### 使用版本
 0.5.0

##### 问题出处
1. 仪表盘
![image](https://user-images.githubusercontent.com/34025457/35909343-45bc63b2-0c2e-11e8-8bf5-3297fa1dd3b7.png)

2. 会话信息
![image](https://user-images.githubusercontent.com/34025457/35909370-5a1108d6-0c2e-11e8-969c-878ee2f044cd.png)

##### 建议
因为用户名一般都是 电话号码， 邮箱，或者工号之类的 数字，字母全拼，用来展示不能直观的获取有效信息， 故此建议将这类展示 改为 用 名称 字段。

[注:] 完成后请关闭 issue

**Comment by topicgit** [comment]
还有月数据总览并没有数据展示

**Comment by deeper-yang** [comment]
我这月数据总览也是没有数据展示，并且库里面就没有log相关的表  
版本0.5.0.2
![](https://i.imgur.com/CJcy0J5.png)

**Comment by ibuler** [comment]
当时设想的，名称可能会相同，比如说公司 两个都叫 张三，而用户名是唯一标识符

**Comment by ibuler** [comment]
@deeper-yang 数据是从 terminal_session表中取的

**Comment by qiushaohu** [comment]
@ibuler  是的，确实用户名才是唯一标识，thanks!
