### ISSUE TITLE
[Bug] VNC Connection with MacOS Issue

### ISSUE THREAD

**Issue by lucianoecodes** [jumpserver/jumpserver#10081]
**JumpServer version (versions before v2.28 are no longer supported)**
Version v2.28.10 GPLv3.

**Browser version**
Version 111.0.5563.65 (Official Build) (64-bit)

**Bug Description**
1. I'm trying to use Asset connection with this configurations:
   - IP:  10.X.X.28
   - Protocol: vnc/5900
   - Platform: MacOS
2. To connect to MacOS:
   - OS: macOS Ventura - Version 13.2.1
   - Sharing > Screen Sharing > Enable
3. But when I try to connect using Jump Console, I recieved the same message:
   - "No System User"

**Bug reproduction steps (better with screenshots)** ( follow zipped )
1. At Asset detail, follow the informations: ( 01_Asset_detail.png )
   - IP:  10.X.X.28
   - Protocol: vnc/5900
   - Platform: MacOS
2. At System User Associated, follow the screenshots:
   - ( 02_1_System_user.png )
   - ( 02_2_System_user_Details.png )

3. About Console Error, follow the screenshot:
   - ( 03_Console_Error.png )

4. I really need help to understand:
   - Is there some configuration I misunderstood or put something wrong in Asset configuration?
   - Is a bug from VNC connection?
   - Do you have some guide to configure built-in MacOS Screen Sharing, without using RealVNC, to work as well, like the RealVNC ?

Thanks and best regards!
Luciano.

**Comment by LeeEirc** [comment]
Please check if the system user's protocol is VNC.  
When connecting to assets in JumpServer, you need to select a system user, the protocol of the system user should be supported by the asset.

**Comment by lucianoecodes** [comment]
Hi LeeEirc!

1. About system user's protocol, I checked, the protocol is VNC. ( 02_2_System_user_Details.png )
2. About select a system user, I did the association follow this steps: ( 02_1_System_user.png )
=> Page: Asset detail  >  Tab: System user > Div: Associate system users
=> I select the same user configured with VNC protocol and click in "Add";
=> This user shows on left list .

- Do you think this is correct steps to associate the user to asset?
- Is there other page to do this association?

I'm attaching again the screenshots.

Thanks,
Luciano.
[issue_jump.zip](https://github.com/jumpserver/jumpserver/files/11090476/issue_jump.zip)

**Comment by LeeEirc** [comment]
No, you need to do the following three steps to associate the user to connect the asset

1. Page: Assets --> Create an asset using the VNC protocol.
2. Page: System Users --> Create a system user with vnc protocol
3. Page: Permissons --> Asset Permissions --> Create a permission
   1) Select user or user‘s group
   2) Select the asset or nodes
   3) Select the system user

After the above three steps, the user can connect to the asset through the system user' authentication (username/password)

**Comment by lucianoecodes** [comment]
Hi LeeEirc !

This last one step, about permission, I didn't do before.
Now the access working as well.
I create system user, associate to asset, and it works too.

I will continue my tests.

Thanks for your time !
Take care and have a nice week !

King regards,
Luciano.

**Comment by BaiJiangJie** [comment]
That's great news, Luciano.

If you encounter any problems in the future, please feel free to contact us and we will help as soon as possible.
