### ISSUE TITLE
[Bug] admin账号丢失管理员权限

### ISSUE THREAD

**Issue by dhfsqxz** [jumpserver/jumpserver#10085]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1.1

**浏览器版本**
edge 111

**Bug 描述**
当前使用的为admin账号，admin账号系统角色为系统管理员
添加、修改用户，添加、修改平台显示无权限

例:
保存新的平台列表时显示 
CSRF Failed: CSRF token missing or incorrect.
![image](https://user-images.githubusercontent.com/74221255/228119240-3bbd869a-9b3d-4304-aae0-4b65a336176e.png)
f12查看网络显示
![image](https://user-images.githubusercontent.com/74221255/228119429-093a83c9-1aa8-4d5a-9e1f-eddb7d60f1e7.png)
创建资产时显示
![image](https://user-images.githubusercontent.com/74221255/228119647-f49e4ea9-28bd-483d-93e0-e14783177765.png)

当前堡垒机升级方式为 3.0.1->3.0.2->3.0.3->3.1.0->3.1.1

**Comment by dhfsqxz** [comment]
补充：
此问题出现在admin记住用户，且关闭浏览器等待较长时间后再进入
admin用户未退出，但丢失部分管理权限
退出账号且重新登录后权限正常

**Comment by dhfsqxz** [comment]
所以csrf token有效期是不是应该和用户登录的有效期一致？
一开始我还以为跨版本升级导致的数据出问题了

**Comment by ibuler** [comment]
正常情况应该是这样的

**Comment by huai168an** [comment]
我用的2.12.2版本，也出现了CSRF Failed: CSRF token missing or incorrect.，admin权限无法添加资产了，csrf token过期的话，怎么解决呢？

**Comment by ibuler** [comment]
> 我用的2.12.2版本，也出现了CSRF Failed: CSRF token missing or incorrect.，admin权限无法添加资产了，csrf token过期的话，怎么解决呢？

刷新页面或者重新登录
