### ISSUE TITLE
[Question] 账号管理 账号推送 定时执行无法选择

### ISSUE THREAD

**Issue by aaronchou0** [jumpserver/jumpserver#10083]
**请描述您的问题.**
版本 3.1.0
在账号管理 账号推送 创建界面无法选择定时执行开关。
![image](https://user-images.githubusercontent.com/15139155/228112214-22e9488c-ef9a-468b-8c10-73533616a2e0.png)

**Comment by aaronchou0** [comment]
![image](https://user-images.githubusercontent.com/15139155/228112587-199aebe3-4850-4a9c-b59a-3e1c532d7a34.png)
鼠标移上去是这样的，无法点击，截图没截出来

**Comment by ibuler** [comment]
暂时不支持
