### ISSUE TITLE
[Question] 初始化部署remote app的时候遇到问题

### ISSUE THREAD

**Issue by fishball0206** [jumpserver/jumpserver#10092]
如题 会卡在安装tinker installer那边
![image](https://user-images.githubusercontent.com/104894061/228305034-daa01997-f0ce-4f75-b039-03711a5a5e02.png)

**Comment by ibuler** [comment]
Core api 配置的不对

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/228406406-865f7123-3d44-4da7-9c69-a573e4aaad5e.png)


这个地址，需要能在 windows 浏览器中访问

**Comment by jym503558564** [comment]
修改正确后，再进行测试，如有发现问题，可再次打开该Issues
