### ISSUE TITLE
[Feature] 资产树筛选某节点后编辑资产，返回能否回到之前操作的节点中

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#10095]
**请描述您的需求或者改进建议.**

现状：
1、进入资产列表模块，左侧为资产树，右侧资产列表默认展示所有资产；资产树下有“应用发布节点”，该节点下有2台资产
2、点击“应用发布节点”，右侧资产列表刷新只留下节点下的2台资产
3、点击某一台资产的更新，再点击返回，右侧资产列表展示所有资产

建议：
第3步更新返回时希望能回到之前操作的节点（应用发布节点），右侧只保留2台资产

**Comment by BaiJiangJie** [comment]
有一定的实现难度，先记录下来了。

后续上线之后，会继续在当前 Issue 进行回复。

**Comment by BaiJiangJie** [comment]
暂时搞不定，未来计划。
