### ISSUE TITLE
在v2.27.0, koko 无法通过ssh的心跳包来保持长链接

### ISSUE THREAD

**Issue by zhongliangshan** [jumpserver/jumpserver#10090]
jumpserver 版本： v2.27.0

这里显示，配置了最大超时时间为1分钟(为了加快测试复现的步骤)
![image](https://user-images.githubusercontent.com/10019422/228230133-506715a8-3e4f-4ca9-a5b5-8d8cbbde5757.png)

这里也设置了每10s发送一次心跳包, 可以看到每10秒都有发送和接收到回包
![image](https://user-images.githubusercontent.com/10019422/228227675-9b86f297-51de-4855-bb11-13e87a396037.png)
但是依旧在1分钟后 断开连接
![image](https://user-images.githubusercontent.com/10019422/228227915-ec4e4457-4b87-4cf8-9c92-49162ec5c2d0.png)

**Comment by ibuler** [comment]
手动输入内容才会计时，心跳包不会

**Comment by zhongliangshan** [comment]
那这样对某些需要通过心跳包来保活的场景会不会不太友好，请问你们这边有没有规划支持这个场景了？

**Comment by zhongliangshan** [comment]
> 手动输入内容才会计时，心跳包不会
那这样对某些需要通过心跳包来保活的场景会不会不太友好，请问你们这边有没有规划支持这个场景了？

**Comment by LeeEirc** [comment]
主要是基于安全的考虑，如果长时间不操作就必须退出。

**Comment by zhongliangshan** [comment]
> 主要是基于安全的考虑，如果长时间不操作就必须退出。
