### ISSUE TITLE
 MFA auth  报错No PTY requested.

### ISSUE THREAD

**Issue by weitianyuan** [jumpserver/jumpserver#10093]
**请描述您的问题.**
通过vscode 远程登录，从跳板机登录资产 ，输入完 MFA auth 报这个错误怎么解决的呀
No PTY requested.
[01:30:11.568] "install" terminal command done
[01:30:11.568] Install terminal quit with output: No PTY requested.

**Comment by LeeEirc** [comment]
使用的jms版本？Koko 是否开启了以下参数

```
ENABLE_LOCAL_PORT_FORWARD: true
ENABLE_VSCODE_SUPPORT: true
```

查看下 Koko 的日志

```
docker logs -f jms_koko --tail=100
```
如果关闭 MFA 可以登录吗？

**Comment by jym503558564** [comment]
参数设置：
ENABLE_LOCAL_PORT_FORWARD: true
ENABLE_VSCODE_SUPPORT: true

设置参数好之后，进行测试。如有问题，可再次提Issues。
