### ISSUE TITLE
[Question]  jumpserver 连接MySQL5.6应用，获取用户权限的时候报错

### ISSUE THREAD

**Issue by JSXGQ** [jumpserver/jumpserver#10103]
jumpserver 连接mysql5.6的应用（mysql的某个普通账户）用navicat连接的时候报错

**Comment by JSXGQ** [comment]
jumpserver的版本是2.25.4

**Comment by JSXGQ** [comment]
我这边尝试了几次 发现是在连接5.6的用户权限报出的问题，想知道是什么原因导致的？

**Comment by BaiJiangJie** [comment]
你用的是社区版还是企业版？

**Comment by JSXGQ** [comment]
社区版

**Comment by BaiJiangJie** [comment]
“用navicat连接的时候报错” 是什么意思？因为社区版本不支持使用 Navicat 连接。

**Comment by JSXGQ** [comment]
我知道问题在哪了 谢谢
