### ISSUE TITLE
[Bug] 3084x1080 宽屏显示器用rdp方式连接资产的审计录像文件出现花屏

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#10108]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

3084x1080 宽屏显示器使用rdp方式连接资产后，他的审计录像文件出现花屏，纯web方式访问录像文件是正常的
1920x1080显示屏访问录像文件是正常的
<img width="550" alt="aa563dc09bc5dc38c7617febcadb930" src="https://user-images.githubusercontent.com/122069934/228750277-a4c324d4-e499-4d1e-91e7-0bd10547cb56.png">

**Comment by BaiJiangJie** [comment]
我用 2840 x 2160 的显示器测试录像效果是正常的。

在 3084 x 1080 的显示器中，你的每一次会话连接后的录像都是这样的吗？

**Comment by BaiJiangJie** [comment]
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/32935519/228755007-701d041e-927e-435b-946d-db67a95096ea.png">

**Comment by zhenzhendong** [comment]
访问时间超过5分钟就会出现

**Comment by BaiJiangJie** [comment]
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/32935519/228758631-48067a50-effa-4ca4-9fae-c390d509b15b.png">

**Comment by BaiJiangJie** [comment]
你的环境是必现吗？还是偶现？

**Comment by BaiJiangJie** [comment]
已线下沟通，Ubuntu系统，RDP 连接。（暂时解决不了）
