### ISSUE TITLE
get auth info http failed

### ISSUE THREAD

**Issue by uguraaygun** [jumpserver/jumpserver#10101]
Hello guys i love the project.

I have a question about web access. I implemented everything on this link https://kb.fit2cloud.com/?p=c207be97-6439-4d19-b228-4f1ac7da831e

But i am gettin an error like below. Any suggestion would help
![error](https://user-images.githubusercontent.com/129187301/228461817-0f0e5a58-9079-4372-b562-a0f18931fb95.PNG)

**Comment by LeeEirc** [comment]
Login to the Applet-Host Windows server, and check the log file in the folder below.

```
C:\Users\Administrator\AppData\Local\Programs\Tinker\data\logs
```

And make your `Windows Time` in sync with Windows NTP server.

**Comment by BaiJiangJie** [comment]
Great! That's really awesome. If you have any other issues, feel free to reach out to us and we'll do our best to assist you. Finally, I wish you all the best and hope you enjoy using our service. @uguraaygun
