### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by hom7** [jumpserver/jumpserver#10113]
**请描述您的问题.**

跳板机添加资产，提示错误

![image](https://user-images.githubusercontent.com/15682396/229403623-19ca2e54-4b8b-4e68-b0ec-84a03245dfb6.png)

**Comment by BaiJiangJie** [comment]
测试可连接性报错了，检查一下下面几项：

1. 网关资产的网络和堡垒机是否通？（在部署机器上 ping 一下 资产 IP）
2. 网关资产添加的账号、密码是否正确？

**Comment by hom7** [comment]
1、宿主肯定是通的，内部jumpserver docker并没有试过

**Comment by BaiJiangJie** [comment]
jms_core 和 jms_celery 容器里试一下。

**Comment by jym503558564** [comment]
该问题还存在吗？由于长时间未反馈，我们将关闭该Issues，如有其他问题可再次提Issues
