### ISSUE TITLE
[Question] 下载文件夹时提示【压缩包文件超过最大允许文件大小范围】

### ISSUE THREAD

**Issue by asdfec** [jumpserver/jumpserver#10111]
系统 ubuntu20.04
连接方式 web sftp
文件夹大小约1.2G，下载时提示【压缩包文件超过最大允许文件大小范围】。
请问如何调整允许的大小？

**Comment by ibuler** [comment]
web sftp 是通过 nginx 下载的，其中会用到内存，所以限制了大小，这样大的最好使用 sftp 而不是 web sftp

**Comment by asdfec** [comment]
cat /proc/meminfo
MemTotal:       791077900 kB
MemFree:        788383468 kB
MemAvailable:   785796360 kB
Buffers:          201640 kB
Cached:           691964 kB

我觉得内存应该够用啊，有没有办法打开限制呢？

**Comment by LeeEirc** [comment]
参考 [文档参数](https://docs.jumpserver.org/zh/v3/guide/env/#2-koko)
```
ZIP_MAX_SIZE=1024M               # web sftp 文件下载，zip 支持压缩的最大额度 (单位=M)
ZIP_TMP_PATH=/tmp                # web sftp 文件下载，zip压缩文件存放的临时目录
```

**Comment by pika-FENG** [comment]
> 文档参数

请问这些组件的参数配置文件在哪呢，/opt/jumpserver/config/koko，这下面没有看到配置文件，有一个config.yml也是空的
