### ISSUE TITLE
终端设置修改密码认证，重启后无效

### ISSUE THREAD

**Issue by ericyee** [jumpserver/jumpserver#1011]
[简述你的问题]
终端设置修改密码认证，重启后无效
##### 使用版本
[ 0.5.0]

##### 问题复现步骤
1. 在终端设置修改取消密码认证，重启coco
2. 在终端设置修改打钩密码认证，重启coco，发现密码认证为生效，ssh登录是秘钥方式

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3068272/35957546-0b54e538-0cd7-11e8-9960-03d4d44d6086.png)

##### 其他
无

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed
