### ISSUE TITLE
[Feature] 授权资产树

### ISSUE THREAD

**Issue by wcb0414** [jumpserver/jumpserver#10126]
**请描述您的需求或者改进建议.**
资产管理中的资产列表资产树与权限管理中的资产授权资产树是否两者可以独立。
![image](https://user-images.githubusercontent.com/81307592/229659744-e1acb977-70e3-480c-8e4f-e72f62e57bce.png)

在授权资产树中创建的新项时，只有选择”节点“时才能显示在当前的节点下，如果这个节点为空时，创建的新项变成在Default 下面了，对管理有些不方便。
![image](https://user-images.githubusercontent.com/81307592/229659640-5d5a7a1e-bf60-4a0e-8904-be9151f2cccc.png)

如果同一个资产需要创建多个授权时，如果填写这个”节点“就变得没有意义了。

**Comment by BaiJiangJie** [comment]
这是对资产授权的策略机制问题。

创建授权规则中的节点，指的是授权给用户节点下的所有资产（包含子节点）。
另一个方面理解，支持选择节点，是为了批量授权资产的。

在授权规则的资产树中，点击节点或者资产，会看到关联节点或资产的授权规则。

**Comment by jym503558564** [comment]
如有其他问题，可再次提Issues
