### ISSUE TITLE
[Question] 录像是否可过滤命令

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10128]
**请描述您的问题.**
用户执行tail日志文件，量太大，是否可以过滤例如 tail、top等持续命令

**Comment by BaiJiangJie** [comment]
录像不会过滤命令，录像中要记录完整命令。

文本类的录像，应该也不会很大吧。

**Comment by wangheng0206** [comment]
> 

有一些大数据的日志，一些用户tail之后没停，很快就把磁盘搞满了

**Comment by BaiJiangJie** [comment]
单个录像文件下来得有多大？

建议配置一个 oss 存储。
