### ISSUE TITLE
luna没有下拉菜单 显示不全

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1012]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2]

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/9443696/35967067-b02f9bac-0cfa-11e8-89d0-8e2346e83593.png)
主机显示不全  没有下拉框

**Comment by qianghong000** [comment]
![jms2](https://user-images.githubusercontent.com/9443696/35972031-2584c188-0d0b-11e8-93ed-28edc937e1ff.png)
这个图标不能反映数值吗？

**Comment by liuzheng** [comment]
@qianghong000 一个issue针对一个问题，该issue的bug已经fix，数值问题请另开issue去trace

**Comment by qianghong000** [comment]
luna的bug已经处理了吗？我git pull没有更改代码，最新的代码怎么获取啊

**Comment by liuzheng** [comment]
@qianghong000 过年，还没push，没完全测完几个issue
