### ISSUE TITLE
[Feature] V3普通用户登录成功建议默认进入工作台界面

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#10123]
**请描述您的需求或者改进建议.**
目前 V3 普通用户登录成功默认进入个人信息页面
觉得默认进入工作台界面，用户体验会更好些
记得 V2 就是设计的默认进入工作台界面

**Comment by BaiJiangJie** [comment]
我刚才测试了一下，普通用户登录成功，默认是工作台页面。

新用户首次登录，会进入到个人信息页面。（因为首次登录用户需要配置一些个人信息）

@hzhfit2cloud
