### ISSUE TITLE
jumpserve从2.x的最高版本升级到3.x的最新版本 现在有些命令过滤的规则去不了  麻烦问下可以直接从库里删除吗 

### ISSUE THREAD

**Issue by BruceChinese** [jumpserver/jumpserver#10137]
jumpserve从2.x的最高版本升级到3.x的最新版本 现在有些命令过滤的规则想去掉 现在发现是找不到这些记录  麻烦问下可以直接从库里删除吗 

如果可以的话 从哪个表里可以删除

**Comment by BaiJiangJie** [comment]
在页面上就可以删除。

v3 版本对命令过滤规则做了一些处理，如果页面上看不到，那就是没有同步上来。

**Comment by BruceChinese** [comment]
页面上看不到 但是在执行某些命令的时候会关联到命令过滤规则导致不能继续执行

**Comment by BaiJiangJie** [comment]
那查看一下下面这两张表的数据：

- `acls_commandfilteracl`
- `acls_commandgroup`
