### ISSUE TITLE
[Feature] http://127.0.0.1/ui/#/tickets/tickets/fb18b2b5-dd77-4a56-85cb-684a73c7c9be?type=command_confirm

### ISSUE THREAD

**Issue by Garrybac** [jumpserver/jumpserver#10132]
Dear Guys

I see in approval mode it use IP 127.0.0.1 how could I change it to Jumpserver IP instead?

Thanks

**Comment by JumpServer-Zac** [comment]
Hi there, I am the JumpServer support team Zac,
You can add my WhatsApp +86 15717111453 if you need help to use JumpServer
