### ISSUE TITLE
是否已支持移动版？

### ISSUE THREAD

**Issue by FayJiang** [jumpserver/jumpserver#1013]
官网上显示有“移动版支持”，
请问是否已支持移动版？
能否提供相关介绍、文档、下载链接的位置?
谢谢

**Comment by ibuler** [comment]
1. 后台支持移动访问，bootstrap自适应
2. web terminal 移动设备直接访问
3. ssh工具直接访问coco，不用记录众多账号密码

希望对你有帮助

**Comment by yssnet** [comment]
![image](https://user-images.githubusercontent.com/8636036/54585017-e66aa300-4a53-11e9-8b95-d4d9f504550a.png)

web terminal 访问不太友好，有做移动端的计划吗？ @ibuler
