### ISSUE TITLE
[Bug] 数据库提示的错误为 1045 - backend auth error invalid ok packet

### ISSUE THREAD

**Issue by kenleemyth** [jumpserver/jumpserver#10134]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0

**浏览器版本**
chrome

**Bug 描述**
通过第三方数据库链接Mysql8.0会出现提示的错误为 1045 - backend auth error invalid ok packet

**Bug 重现步骤(有截图更好)**
1.通过网域链接
2.ssh正常使用mysql
3.第三方工具不正常

**Comment by BaiJiangJie** [comment]
第三方工具用的是什么工具？尽量放一些截图，复现步骤描述尽量详细一些，不然很难理解的你的问题是什么！

**Comment by kenleemyth** [comment]
DataGrip Navicat Premium 15 DBeaver 都测试过 就是正常的链接数据库就不可以 
数据库是阿里云的serveless mysql8

**Comment by kenleemyth** [comment]
昨日已经尝试升级到3.1.1目前情况还是一致

**Comment by kenleemyth** [comment]
后面又升级了一次成功了
