### ISSUE TITLE
[Question] v3.10 推送用户Permission denied:

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#10139]
**请描述您的问题.**
jumpserver v3.10 k8s 部署 
资产是aws平台ec2
配置了特权用户可以连接可以刷硬件，但是推送用户失败
用户名为ec2-user ，认证方式为秘钥
错误日志：
 {"changed": false, "cmd": "/sbin/useradd -p VALUE_SPECIFIED_IN_NO_LOG_PARAMETER -m admin", "msg": "[Errno 13] Permission denied: b'/sbin/useradd'", "rc": 13, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
手动登录成功，执行/sbin/useradd -p VALUE_SPECIFIED_IN_NO_LOG_PARAMETER -m admin  命令失败，
sudo 执行命令成功
我认为可能是用户名为非root导致的，请问特权用户是否必须为root才可以使用

**Comment by whiskyy** [comment]
v2.x 是没问题的

**Comment by BaiJiangJie** [comment]
`我认为可能是用户名为非root导致的，请问特权用户是否必须为root才可以使用`

理论上，用户只要有权限就可以执行，不一定是 root。

如果修改认证方式为 `密码` 可以吗？

**Comment by whiskyy** [comment]
现在aws 新的linux镜像 默认关闭密码登录了，不过就算是密码也不可以
我使用ec2-user手工登录机器 add user 也没有权限

**Comment by whiskyy** [comment]
需要sudo 才能执行

**Comment by whiskyy** [comment]
换句话说 这个特权用户是有权限的，不过需要sudo + 命令

**Comment by justin096** [comment]
这里没有将配置中特权用户的信息加到运行的playbook里面，我临时在celery容器的apps/accounts/automations/change_secret/host/*/main.yml里面加了become: yes，在容器重建之前都没有什么总是。

**Comment by whiskyy** [comment]
@justin096 你这个回答专业啊，我也试试

**Comment by BaiJiangJie** [comment]
这个问题考虑一下怎么集成到账号里，在执行任务的时候，配置是否使用 sudo，或者 sudo 时是否需要输入密码。

**Comment by BaiJiangJie** [comment]
最新版本配置用户切换自就可以了。
