### ISSUE TITLE
[Bug] ssh

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10145]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.1

**浏览器版本**
版本 111.0.1661.62 (正式版本) (64 位)

**Bug 描述**
我的理解里，使用“模板添加”添加的账号是不需要再次输入用户名和密码的

**Bug 重现步骤(有截图更好)**
1.添加网络设备
2.账号列表选择“模板添加”
3.提示异常
![image](https://user-images.githubusercontent.com/63082453/230266112-2f6d1f19-f405-4f72-8b7d-386596c02914.png)
4.手动更新一下账号信息，然后自己手动敲一遍密码，就可以正常提交

**Comment by BaiJiangJie** [comment]
看一下浏览器控制台的 console 有没有报错？

**Comment by BaiJiangJie** [comment]
新版本已优化。
