### ISSUE TITLE
默认密码

### ISSUE THREAD

**Issue by chao901103** [jumpserver/jumpserver#1014]
[简述你的问题]
有一年的时间了安装的时候找到一次默认密码，也登录成功，但是这次安装使用之前的默认密码登录不上去。
看了wiki说是在jumpserver.log日志中，我的日志是什么都没有记录。
默认密码有没有保留在哪里，可以直接修改的？
默认密码是什么？ 还是随机的？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
使用git 拉取的
git clone https://github.com/ibuler/jumpserver.git

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16370986/36063572-9dc18a1e-0eb9-11e8-8d75-cc3f758e8d03.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已废弃，查看 新仓库  https://github.com/jumpserver/jumpserver
