### ISSUE TITLE
[Feature] ssh登录期望有语法高亮

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10143]
**请描述您的需求或者改进建议.**
登录Linux服务器或者交换机等网络设备时，期望有语法高亮

**Comment by BaiJiangJie** [comment]
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/32935519/230535829-0399705d-246d-4d4f-9247-ff5860f6040e.png">
一些目录的颜色是高亮的。语法上产品暂时不考虑支持。
