### ISSUE TITLE
[Bug] 3.0版本无法关闭web sftp

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#10140]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.1

**浏览器版本**
Microsoft Edge 版本 111.0.1661.62

**Bug 描述**
我想关闭某个主机的WEB SFTP链接方式，只保留WEB CLI，但无法关闭。

**Bug 重现步骤(有截图更好)**
1. 在平台列表中克隆了一个Linux类型，然后在他的设置里点开齿轮，关闭“启用 SFTP”
2. 新建一个资产，系统平台选择刚才创建的那个（点开齿轮依旧可以看到启用 SFTP处于关闭状态）
3. 给一个普通用户授权这个资产，但是在WEB终端连接这个资产的时候，依然可以选择 WEB SFTP
4. 甚至在第一步关闭功能前，先修改"SFTP home"再关闭功能，这个所设置的"SFTP home"路径依然有效。

![Snipaste_2023-04-05_17-05-14](https://user-images.githubusercontent.com/1674158/230036922-bf2353d5-01cc-46e1-ad34-e3a4de157d26.png)
![image](https://user-images.githubusercontent.com/1674158/230037143-12bab0f0-1db5-4382-a663-311a467acec9.png)

**Comment by BaiJiangJie** [comment]
嗯，目前是有这个问题，在 v3.2 中会优化。

**Comment by BaiJiangJie** [comment]
已修改 https://github.com/jumpserver/jumpserver/commit/e12b8329923aea18f6bd64e3744adf64a2013032
