### ISSUE TITLE
[Question]  v2.28.11 文件管理功能提示 connection lost

### ISSUE THREAD

**Issue by zzoujinn** [jumpserver/jumpserver#10146]
**请描述您的问题.**
添加资产后，添加了 root 用户和 jumpserver 用户，root用户可以正常的获取到 sftp 路径内容，jumpserver提示 connection lost，修改jumpserver 用户的 sftp 根路径为家目录/home/jumpserver后依旧如此

**Comment by zzoujinn** [comment]
![image](https://user-images.githubusercontent.com/28640714/230266828-db8b7dc3-1445-4d7d-8b44-69882c8001b1.png)

**Comment by LeeEirc** [comment]
去看下 koko 的日志，是不是账号密码错误，连不上。 
```
docker logs -f jms_koko -tail=100
```

**Comment by zzoujinn** [comment]
![image](https://user-images.githubusercontent.com/28640714/230281539-ad530437-6ac3-486f-ae1f-9992aecf1fa0.png)
koko报错这个

**Comment by zzoujinn** [comment]
用户名密码正确，ssh连接是正常的

**Comment by LeeEirc** [comment]
可以用这个账号，试下原生 sftp 工具连接有没有报错。

**Comment by jym503558564** [comment]
请升级至v2.28最新版本进行测试，如有问题可再次打开该Issues，并附上截图或日志
