### ISSUE TITLE
[Feature] 在luna初次点击资产弹窗选择很不人性化

### ISSUE THREAD

**Issue by Subp66** [jumpserver/jumpserver#10149]
**请描述您的需求或者改进建议.**
所有用户大部分场景肯定都是进CLI命令行，可能偶尔会有SFTP需求
而新版本JumpServer为了这小部分需求，强制所有资产初次点击时，弹窗并点击连接才能继续
如果不想下次提示，还要多点一次下次自动登录，而以后要使用SFTP，还要在资产右键点连接弹窗选择
比如我有1000个资产，初次升级后，如果都要进一遍CLI，我要点3000次鼠标(点资产，点勾选，点连接)
而且没有任何地方可以设置默认选项，这很反人类

这里我给出的建议是加强luna界面鼠标右键能力，在右键加入连接SFTP即可，默认左键只是进CLI
另外还有个建议，是否可以在luna界面多选资产，批量打开CLI
比如通过按CTRL多选资产，或者鼠标拖选，选中后，右键菜单连接CLI

**Comment by ibuler** [comment]
统一了连接方式，现在各组件都是使用 connect token 连接的，所以无法右击连接了，必须事先生成一个 token

**Comment by ibuler** [comment]
这个可能也不行，有可能选的有 windows 有 linux ，可能账号也不统一
---
另外还有个建议，是否可以在luna界面多选资产，批量打开CLI
比如通过按CTRL多选资产，或者鼠标拖选，选中后，右键菜单连接CLI

**Comment by yiqikeji17** [comment]
建议是加强luna界面鼠标右键能力，在右键加入连接SFTP即可，默认左键只是进CLI。

**Comment by Subp66** [comment]
我不是很理解为什么不太行？如果说弹窗是为了生成一个token，当用户点了左键，系统完全可以模拟弹出过程，完成生成token的过程，然后进到控制台。用户右键菜单选择进入SFTP，然后系统也可以同上，完成生成token过程并进入到sftp

因为你们没有面对大量的主机，你不知道每点一个主机弹一次窗口的痛苦，如果上一次选择进了sftp，弹窗还要选择一下，大大增加了时间成本，如果要进sftp，多点了一次右键，还是要弹窗，再选择sftp，再点连接，相比2.0繁琐了多少倍

**Comment by BaiJiangJie** [comment]
你站在多种资产类型的角度考虑一下，左键点击资产你说 Linux 的默认打开 Web CLI 方式。

那 Windows、数据库类型（MySQL、Redis、Oracle）、Web 类型（Chrome、DBeaver）呢？

不要只站在 ssh 和 sftp 的角度考虑。

**Comment by Subp66** [comment]
你说的也有道理。是不是可以这样呢？因为资产在添加时，已选择了类型，那在打开终端页面时，系统自动根据不同资产，展示不同菜单，linux类的沿用v2的管理方式，其它类型使用v3的管理方式？

**Comment by BaiJiangJie** [comment]
最主要的原因是 Luna 页面对所有资产类型的连接底层都做了统一，修改起来相当于两套逻辑，维护成本很高。

暂时不考虑优化了。

**Comment by jjk334** [comment]
建议有个地方可以设置默认的资产类型型连接的默认方式 这样首次批量打开就不需要选择了。  然后右键在单独去选择。 这样比较人性化。
