### ISSUE TITLE
[Question]3.0.4离线升级3.1.0升级失败

### ISSUE THREAD

**Issue by joedong1988** [jumpserver/jumpserver#10148]
**请描述您的问题.**
目前使用的是社区版3.0.4，使用3.1.1离线包jmsctl.sh upgrade升级后，虽然提示升级成功，但是登录Jumpserver查看版本时还是3.0.4。

**Comment by BaiJiangJie** [comment]
升级完以后重启一下服务，然后强制刷新一下页面呢？

**Comment by jym503558564** [comment]
升级成功了吗？如有问题可再次打开该Issues。
