### ISSUE TITLE
建立了web 的asset 不能login

### ISSUE THREAD

**Issue by asd2bsa** [jumpserver/jumpserver#10147]
問題1: 在asset 建立了一個web 的asset. 加入了user. 要login 時發現下面是灰時沒. 沒有得login. 
![image](https://user-images.githubusercontent.com/130030200/230295238-a9ab5c2f-423e-4a8c-84ff-eaf88d2bbac5.png)

問題2: 是否一定要加入user? 可以彈出接入頁面時才輸入用戶和密碼資料嗎?

**Comment by BaiJiangJie** [comment]
远程应用发布机部署了吗？
