### ISSUE TITLE
[Question] 命令和录像备份问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10156]
**请描述您的问题.**
1、jumpserver的命令记录是在数据库里吗或者是在哪个目录里
2、一台3.1.0的录像文件传输到另一台3.1.0的jumpserver上，另一台上能看这些录像吗

**Comment by BaiJiangJie** [comment]
`1、jumpserver的命令记录是在数据库里吗或者是在哪个目录里`

在 terminal_command 表里。

`2、一台3.1.0的录像文件传输到另一台3.1.0的jumpserver上，另一台上能看这些录像吗`

要看请求到了哪一台服务器上，建议使用 NFS 共享目录，或者使用 oss 对象存储。

**Comment by ryswork1993** [comment]
比如我有一台jumpserver突然坏了，我把这台上备份的录像文件放到我新部署的同版本jumpserver上，能看回放吗



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月07日 16:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Question] 命令和录像备份问题 (Issue #10156) |

1、jumpserver的命令记录是在数据库里吗或者是在哪个目录里

在 terminal_command 表里。

2、一台3.1.0的录像文件传输到另一台3.1.0的jumpserver上，另一台上能看这些录像吗

要看请求到了哪一台服务器上，建议使用 NFS 共享目录，或者使用 oss 对象存储。

**Comment by BaiJiangJie** [comment]
可以的。

**Comment by ryswork1993** [comment]
我把一台的录像文件传到一样配置的另一台中，web界面看不到新录像，刷新页面，退出账户重新登录都试了，不过没重启jms试试



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月07日 17:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Question] 命令和录像备份问题 (Issue #10156) |

可以的。

**Comment by ryswork1993** [comment]
> 可以的。

我把一台的录像文件传到一样配置的另一台中，web界面看不到新录像，刷新页面，退出账户重新登录都试了，重启jms也试过了

**Comment by LeeEirc** [comment]
另一台 jms 的数据库需要有相应的 session 数据，
