### ISSUE TITLE
[Feature] 作业中心的几点优化建议。

### ISSUE THREAD

**Issue by luan-xj** [jumpserver/jumpserver#10154]
**请描述您的需求或者改进建议.**
1.堡垒机工作台--作业中心--模板管理--创建命令过程中，参数的最大长度为1024，如果想讲脚本放在模板里面，长度就非常有限。
  作业管理里面也是这种问题，希望优化。
2.模板管理里面如果是放的脚本的话，那作业中心里，可以想调用playbook那样调用shell、python等脚本。
3.在作业管理调用模板的时候，可以添加模板参数。像shell脚本、python脚本，playbook脚本都是可以传参的。这样更方便针对不同的资产运行。
4.在调用playbook模板时，现在只能选取资产，建议可以选取节点。因为ansible的管理概念中就有分组（资产节点）的概念。

**Comment by BaiJiangJie** [comment]
第1、4个问题，可考虑优化。

第2、3个问题有没有具体的优化方案？用图片表达一下可能更清晰。

**Comment by luan-xj** [comment]
第2条：就是脚本放在模板中，作业中心只是调用模板中的脚本。
第3条如图，就是选择完脚本，可以加参数，同理，shell脚本，python脚本都添加这个参数的可选选项，几个参数，就可以手动添加几个.
![图片](https://user-images.githubusercontent.com/20200881/230861330-45bf3084-7214-42d1-a03c-81e04a34ed26.png)

**Comment by kdyq007** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/8168931/231375855-2966cbd7-e666-4c9d-bfab-cc3cd45b5585.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/8168931/231375921-4573dbcd-8169-4167-8d3a-655fd170ac74.png">

**Comment by macaty** [comment]
5、希望计划任务可以编排，就是可以设定多个任务先后顺序、并行顺序、前置关系等编排执行

**Comment by BaiJiangJie** [comment]
> 5、希望计划任务可以编排，就是可以设定多个任务先后顺序、并行顺序、前置关系等编排执行

暂时先不考虑了。

**Comment by BaiJiangJie** [comment]
未来可能会考虑。

**Comment by BaiJiangJie** [comment]
短期内不支持。
