### ISSUE TITLE
[Question] Ansible-playbook

### ISSUE THREAD

**Issue by ehsanhajian** [jumpserver/jumpserver#10157]
Hi. I need to run my ansible playbook from my laptop on the servers that are managed by jumpserver. due to security policy, I have no direct ssh access to them only jumpserver has. Do you have any solution or best practice for it?  Should I run through a runner instance? Can jumpserver handle it? I see jumpserver has some built-in playbooks like ping each host. Can I run my playbook through jumpserver? Thank you in advance

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/231354921-0bf90429-19c5-4e29-b6e9-1049bd133e04.png)

Try this.

**Comment by ehsanhajian** [comment]
thanks for your response. how about ansible host file? if I upload my playbook to jumpserver, jumpserver will use assets name as ansible host file? thanks for your explanation.

**Comment by ehsanhajian** [comment]
could you please upload some sample ansible roles and playbooks to know how to make it compatible with jumpserver? I've imported my ansible roles in jumpserver but when I run it I got this error.

```
Start adhoc execution error: 'set' object is not subscriptable
Task ops.tasks.run_ops_job_execution[24e9e242-412f-457e-8450-dfc0d077429d] succeeded in 0.07275671511888504s: None
``` 
no idea how to resolve the errors. Thanks

**Comment by BaiJiangJie** [comment]
```
Start adhoc execution error: 'set' object is not subscriptable
Task ops.tasks.run_ops_job_execution[24e9e242-412f-457e-8450-dfc0d077429d] succeeded in 0.07275671511888504s: None
```
This problem has been fixed in the new version, please update to the latest version.（v3.2.2）
