### ISSUE TITLE
[Bug] 群晖docker 部署后，数据库迁移报错

### ISSUE THREAD

**Issue by netusb** [jumpserver/jumpserver#10155]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
Version v2.8.4 GPLv2.

**浏览器版本**
edge

**Bug 描述**
https://docs.jumpserver.org/zh/master/install/upgrade/mariadb-mysql/
中  备份数据库--docker 部署--命令
mysqldump -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME > /opt/jumpserver.sql

**Bug 重现步骤(有截图更好)**
1.报错信息
```
[root@7445bec27084 opt]# mysqldump -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME > /opt/jumpserver.sql
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
```
![20230407111055](https://user-images.githubusercontent.com/51571969/230533549-5869a3ff-e707-439d-85ed-39eeb85e99af.png)

**Comment by BaiJiangJie** [comment]
看日志是 $DB_USER 对数据库的操作权限不够。

**Comment by wojiushixiaobai** [comment]
这个报错应该不影响，或者请授权 `gant all <user> ...`

**Comment by jym503558564** [comment]
v2.8.4已不再支持，请升级至v2.28最新版本进行体验测试
