### ISSUE TITLE
[Question] ssh idle timeout

### ISSUE THREAD

**Issue by ehsanhajian** [jumpserver/jumpserver#10150]
**请描述您的问题.**
Hi team. I recently installed jumpserver. the issue that I have is about ssh timeout. when I ssh to a server if I don't type any command in 5sec my connection will be dropped. this is happening when I use jumpserver to connect to the server. the other SSH clients have no issues. Do you also have English version of jumpserver documentation?

<img width="306" alt="Screenshot 1402-01-17 at 15 03 40" src="https://user-images.githubusercontent.com/18378194/230359166-8949f77c-77bb-4f2d-ba00-f8c54e853131.png">

**Comment by ehsanhajian** [comment]
It seems the issue is related to my proxy server when I pass port 443 to port 80. is there any recommended reverse proxy config for the jump server?

**Comment by LeeEirc** [comment]
Your proxy server should support websocket.
If you use nginx, you need to add the following configuration to the nginx configuration file.

```
location / {
    proxy_pass http://jumpserver;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header X-Forwarded-For $remote_addr;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
}

```
This is the full example configuration [http_server.conf](https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf)
