### ISSUE TITLE
[Question] Keyboard Settings does not work

### ISSUE THREAD

**Issue by uguraaygun** [jumpserver/jumpserver#10158]
Hello guys;

When we connect via rdp or ssh;

Our keyboards settings does not apply. For example our windows machines use turkish keyboard. But when i connect them it uses english keyboard instead. And i could not find any options about it. 

Is there any option ?

**Comment by LeeEirc** [comment]
There are no options available for keyboard settings.

We utilize xterm.js to display the web terminal for our SSH connection, but unfortunately, do not find any options for configuring the QWERTY keyboard.

To address the issue with RDP connections, we would like to add an additional option setting as described in the relevant [issue](https://github.com/jumpserver/jumpserver/issues/9752) in upcoming release.

**Comment by uguraaygun** [comment]
Thank you mate. This is great project. I am looking for next update.

**Comment by BaiJiangJie** [comment]
Thanks. After the function is launched, it will reply in the current Issue.

**Comment by BaiJiangJie** [comment]
The v3.4 version has been released to include the keyboard layout select, it is recommended to upgrade and use it as soon as possible. @uguraaygun

**Comment by uguraaygun** [comment]
Thank you for implementation. I tried but i  could not find it.

Upgraded to v3.3.0

![image](https://github.com/jumpserver/jumpserver/assets/129187301/4605a91b-b91c-4bfc-ad7b-e61fc1e43733)

**Comment by uguraaygun** [comment]
Also tried when connected to a windows machine via rdp do i need to edit a setting ?

**Comment by BaiJiangJie** [comment]
The keyboard layout selection function is placed in the enterprise version by default, and we will open it in the community version in the v3.3.1 version.

https://github.com/jumpserver/luna/pull/831

**Comment by BaiJiangJie** [comment]
v3.3.1 has been released, you can try it out.

**Comment by uguraaygun** [comment]
Thank you very much mate. It works. 

Thank you and to the team
