### ISSUE TITLE
支持用用户a登录堡垒机，在堡垒机用其他用户登录服务器吗

### ISSUE THREAD

**Issue by chinesejie** [jumpserver/jumpserver#1016]
举个例子，我用zhangsan登录堡垒机，然后在堡垒机我想用work帐号登录服务器b，支持吗？

**Comment by chinesejie** [comment]
没表述清楚，就是我用zhangsan登录堡垒机，既想用zhangsan登录client机器，又想用work登录client机器

**Comment by liuzheng** [comment]
你授权Client机器给work不就行了？

**Comment by chinesejie** [comment]
支持 多账号授权吗？ 既有zhangsan，又有work？

**Comment by liuzheng** [comment]
@chinesejie 当然
