### ISSUE TITLE
[Bug] 单机部署后，使用web终端连接k8s报错，Server error occur, contact administrator

### ISSUE THREAD

**Issue by w7team** [jumpserver/jumpserver#10163]
/api/v1/perms/users/self/nodes/children-with-k8s/tree/?token=a8d2a3ec-5a15-4206-b656-80912851e0b6

Server error occur, contact administrator
![image](https://user-images.githubusercontent.com/74588507/230767640-cd1d64e9-e93f-48bd-a64f-b3fcc06aeb5d.png)

检查日志没有任何问题
![image](https://user-images.githubusercontent.com/74588507/230767678-dfc03b56-3f12-4bb7-9ad9-b9166d61d465.png)

各个容器也都正常启动
![image](https://user-images.githubusercontent.com/74588507/230767694-402e6d75-6766-4b57-aaed-1918c41a0d4a.png)

操作界面一直在转圈
![image](https://user-images.githubusercontent.com/74588507/230767711-007904ae-de63-4aa6-996c-5fa4b2c55ee1.png)

**Comment by w7team** [comment]
初步确定了原因，只有在k8s的token填错时才会出现这个

**Comment by BaiJiangJie** [comment]
连接的时候后端会获取 k8s 的 namespaces，获取的时候没有 try，所以后端直接 500 了。

会在 v3.1.3 和 v3.2 版本中进行修复。
