### ISSUE TITLE
[Bug] CONNECTION_TOKEN_EXPIRATION参数不生效

### ISSUE THREAD

**Issue by markvivv** [jumpserver/jumpserver#10165]
**v3.1.1**
从v2版本，使用jumpserver-offline-installer-v3.1.1-amd64-264升级而来

**Safari**

**/opt/jumpserver/config/config.txt配置CONNECTION_TOKEN_EXPIRATION=28800不生效，Mysql数据库链接仍然90分钟左右失效**

**Bug 重现步骤(有截图更好)**
1. 在/opt/jumpserver/config/config.txt配置CONNECTION_TOKEN_EXPIRATION=28800
2. 执行./jmsctl.sh stop停止服务
3. 执行./jmsctl.sh start启动服务
4. 访问jumpserver web终端页面，申请数据库客户端账号密码
5. 将数据库账号密码配置到dbeaver上
6. 使用约1个半小时之后提示错误： 1045 - can not get backend info, POST http://core:8080/api/v1/authentication/super-connection-token/secret/ failed, get code: 400, {"id":"Token is expired"}

**Comment by BaiJiangJie** [comment]
嗯，已知问题，下个版本会优化。

**Comment by jibill** [comment]
v3.1.0，遇到同样的问题。

**Comment by BaiJiangJie** [comment]
@markvivv  @jibill 

改动比较大，小版本不更新了。

计划在 v3.3 版本中支持。

**Comment by markvivv** [comment]
@BaiJiangJie 已知晓，感谢回复。
