### ISSUE TITLE
[Question] rename or delete nodes

### ISSUE THREAD

**Issue by ehsanhajian** [jumpserver/jumpserver#10170]
**请描述您的问题.**
Hi. on asset management when I want to add a new `node` I can add it without any problem but when I want to delete or rename it I'm getting an access denied error.  Didn't find anything on logs.

<img width="847" alt="Screenshot 1402-01-21 at 12 04 55" src="https://user-images.githubusercontent.com/18378194/230858013-b6309fcc-bed1-4fa0-85a4-dd1e378c225d.png">

**Comment by BaiJiangJie** [comment]
Take a look at the API requests and responses in your browser console.

**Comment by JumpServer-Zac** [comment]
Hi there, I am the JumpServer support team Zac,
You can add my WhatsApp +86 15717111453 if you need help to use JumpServer
