### ISSUE TITLE
[Bug] 资产连接连接全屏显示，按esc无法退出全屏

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#10179]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.1

**浏览器版本**
版本 111.0.5563.148

**Bug 描述**
资产连接连接全屏显示，按esc无法退出全屏；

**Bug 重现步骤(有截图更好)**
1.无法退出全屏
![微信截图_20230411161723](https://user-images.githubusercontent.com/43403764/231100054-f92696dc-134c-437c-af29-532ae9471ff7.png)

**Comment by BaiJiangJie** [comment]
长按 ESC 键盘 2-3s。

短按不能退出全屏，是为了避免 vi 进入编辑模式后按 esc 可以进入命令模式。
