### ISSUE TITLE
[Bug] 新建系统平台ssh复用失效

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#10178]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.11 

**浏览器版本**
版本 111.0.5563.148（正式版本） （64 位）

**Bug 描述**
1、登录资产的账号是OTP认证（密码是动态的）每次登录手动输入密码，基于Linux平台新建一个Linux-GBK平台，登录后使用复制窗口会报错，error：认证失败(用户名或码错误)，使用默认的Linux平台是可以直接ssh复用的；
2、基于Linux平台新建一个Linux-GBK平台,登录资产的账号是静态的，登录后复制窗口不会走ssh复用，会重新连接，使用默认的Linux平台是可以直接复用的；

**Bug 重现步骤(有截图更好)**
![微信图片_20230411153234](https://user-images.githubusercontent.com/43403764/231088697-df27b47f-cd5d-4254-ac26-4202222429fb.png)

**Comment by BaiJiangJie** [comment]
上面两个问题，根本上都是一个问题。

目前 v2.28 的版本进行 `复用链接` 限制了只有内置 Linux 平台生效。

计划在 v2.28.13 上支持一下自定义平台的复用。

**Comment by jym503558564** [comment]
建议升级至v2.28最新版或v3最新版本，进行测试
