### ISSUE TITLE
centos6 TypeError: 'OSError' object is not subscriptable

### ISSUE THREAD

**Issue by Aneuuu** [jumpserver/jumpserver#1017]
[简述你的问题]

##### 使用版本
版本 0.5.0

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/16789723/36131946-84196a12-10af-11e8-9f06-237c22313e62.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不清楚，可以尝试一下 docker版本 

> $ docker run -p 8080:80 -p 2222:2222 jumpserver/jumpserver:0.5.0-beta2
