### ISSUE TITLE
授权用户登陆出现问题

### ISSUE THREAD

**Issue by jiaminxu** [jumpserver/jumpserver#1018]
[简述你的问题]

##### 使用版本
[ 0.5.0]

##### 问题复现步骤
1. [创建资产名为34  创建资产见message1]
2. [提交之后，看到可连接不可用，日志见message2，message3]
3.[但是之后  连接状态就变成了可连接，message4是我机子的信息。但是连接上去会提示问题message5]
我机子是centos6.4  wiki v0.3.2-客户端-RedHat里的条件我也都是满足的。
4.[连上34之后发现/home 目录下的dev 用户组很怪异。不知道是不是推送的时候出现了问题。如图message6，修改成dev 之后登陆没问题。]
请问这个是不是我哪里操作有误造成的

感谢开源    新年快乐！
##### 具体表现[截图可能会更好些,最好能截全]
![message1](https://user-images.githubusercontent.com/20829899/36272745-5f47548c-12bd-11e8-8726-55cbfcf2fdc9.jpg)
![message2](https://user-images.githubusercontent.com/20829899/36272825-938677aa-12bd-11e8-8951-9b058999dcff.jpg)
![message3](https://user-images.githubusercontent.com/20829899/36272938-e901bf78-12bd-11e8-8166-cfbc24e7d62e.jpg)
![message4](https://user-images.githubusercontent.com/20829899/36273087-5bd4911a-12be-11e8-8c8a-09f8db2237b4.jpg)
![message5](https://user-images.githubusercontent.com/20829899/36273094-6152d75a-12be-11e8-9b83-a31d7eb80d6d.jpg)
![message6](https://user-images.githubusercontent.com/20829899/36273585-e83be346-12bf-11e8-9de3-9c476b791210.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新年快乐

**Comment by wojiushixiaobai** [comment]
退出34的终端状态，然后重新连接看看。
如果还不行，请检查日志进行插排。
也可以尝试在Web界面把资产删除后重新添加试试。
