### ISSUE TITLE
[Bug] 快捷命令执行报错

### ISSUE THREAD

**Issue by Anorpi** [jumpserver/jumpserver#10185]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer  v3.1.2

**浏览器版本**
Chrome 版本 111.0.5563.147（正式版本） （64 位）

**Bug 描述**
我是通过 jmsctl.sh  upgrade 命令将 v2.28 升级到  v3.1.2的。但使用 快捷命令功能时，总是遇到
“Start adhoc execution error: 'set' object is not subscriptable” 报错。

**Bug 重现步骤(有截图更好)**
1.进入 “快捷命令”
2.左侧选择一个主机
3.右侧输入 w 命令，点击执行

![w](https://user-images.githubusercontent.com/7035867/231387784-67549683-c492-46d8-91bd-8418fe86486b.png)

**Comment by Anorpi** [comment]
> 看下后端 celery_ansible.log 的日志报错信息

![ww](https://user-images.githubusercontent.com/7035867/231403684-be6864de-5db7-414b-b679-3490eba1eef3.png)

**Comment by BaiJiangJie** [comment]
没有打堆栈信息还看不出来，怎么复现一下呢？

**Comment by BaiJiangJie** [comment]
```
# 进入 celery 容器
docker exec -it jms_celery bash

# 编辑文件，修改代码
vi apps/ops/tasks.py

# 修改 50 行

（修改前）logger.error("Start adhoc execution error: {}".format(e))


（修改后）logger.error("Start adhoc execution error: {}".format(e), exc_info=True)

# 退出容器
exit 

# 重启 celery 容器
docker restart jms_celery 


# 执行任务，再查看 celery_ansible.log 日志
```

**Comment by Anorpi** [comment]
> 按照下面的方法修改一下代码，来看看日志输出信息：
> 
> ```
> # 进入 celery 容器
> docker exec -it jms_celery bash
> 
> # 编辑文件，修改代码
> vi apps/ops/tasks.py
> 
> # 修改第 50 行代码
> 
> （修改前）logger.error("Start adhoc execution error: {}".format(e))
> 
> 
> （修改后）logger.error("Start adhoc execution error: {}".format(e), exc_info=True)
> 
> # 退出容器
> exit 
> 
> # 重启 celery 容器
> docker restart jms_celery 
> 
> 
> # 执行任务，再查看 celery_ansible.log 日志
> ```

按照这个编写了 apps/ops/tasks.py 但好像日志格式还是没什么变化。
刚测试的时候发现，是有些机器会报这个错 有些则不会，具体看下面的截图。
最后选了另外一台主机进行执行，没有报错。


![jmp1](![jmp1](https://user-images.githubusercontent.com/7035867/231411299-b4c7a724-5f45-4058-8b8d-6b9654a19190.png))
![jmp5](![jmp5](https://user-images.githubusercontent.com/7035867/231411004-aeea69f6-c9a5-4fb2-ba7b-5bf8a488f8fc.png))

**Comment by BaiJiangJie** [comment]
那再修改一下第 76 行，修改前的代码一样。

**Comment by BaiJiangJie** [comment]
```
# 进入celery容器再修改一下文件 apps.ops.ansible.inventory.py
vi apps/ops/ansible/inventory.py

# 第 174 行上面添加一行

print('LOG FOR ACCOUNT: accounts: {}, type: {}'.format(accounts, type(accounts)))

# 退出容器，重启，执行任务，查看日志
```

<img width="780" alt="image" src="https://user-images.githubusercontent.com/32935519/231418633-80356c36-7d3e-494e-962f-95df55213940.png">

**Comment by Anorpi** [comment]
大概定位到了。我快捷命令 执行用户手动输入的 root ，但当前用户没有这个资源的root账号权限 导致报错。感觉可以做个提示。

![Snipaste_2023-04-12_17-46-15](https://user-images.githubusercontent.com/7035867/231421091-738ece87-47fc-45b8-bdf5-2d8f708cc2aa.png)

**Comment by BaiJiangJie** [comment]
问题原因找到了，会在 v3.1.3 和 v3.2 版本中进行修复。

- [v3.1 PR](https://github.com/jumpserver/jumpserver/pull/10190/files)

- [dev PR](https://github.com/jumpserver/jumpserver/pull/10189)
