### ISSUE TITLE
[Question]连续刷新jumpserver页面jms_core重启

### ISSUE THREAD

**Issue by xiaozhuang314** [jumpserver/jumpserver#10182]
登录jumpserver（v3.1.2）后连续刷新几次页面报错502（有时候点击切换页面也报错502），抓取日志如下 
-----
<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>      

### **报错日志1** 
# ./jmsctl.sh tail jms_core
2023-04-12 10:36:44 Wed Apr 12 10:36:44 2023
2023-04-12 10:36:44 JumpServer version v3.1.2, more see https://www.jumpserver.org

- Start Flower as Task Monitor

- Start Gunicorn WSGI HTTP Server
- Start heartbeat thread => ([Core]-eu-pki-jumpserver)
2023-04-12 10:36:45 Check service status: flower -> running at 16
2023-04-12 10:36:46 Check service status: gunicorn -> running at 172023-04-12 10:37:17 Check service status: flower -> stopped at 16
2023-04-12 10:37:17 Service start failed, exit: flower
flower is stopped.
Stop service: gunicorn Error
2023-04-12 10:37:22 Check database connection: 0
System check identified no issues (0 silenced).
2023-04-12 10:37:23 Database connect success
2023-04-12 10:37:23 Collect static files
2023-04-12 10:37:23 Collect static files done
2023-04-12 10:37:23 Check database structure change ...
2023-04-12 10:37:23 Migrate model change to database ...

**### #报错日志2**
lion_1    | 2023-04-12 10:46:17 main main.go [ERROR] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF
lion_1    | 2023-04-12 10:46:17 main main.go [ERROR] Ws heart beat closed, try reconnect after 10s
lion_1    | [GIN] 2023/04/12 - 10:46:19 | 200 |      55.024��s |       127.0.0.1 | GET      "/lion/health/"
koko_1    | [GIN] 2023/04/12 - 10:45:37 | 200 |      51.584��s |       127.0.0.1 | GET      "/koko/health/"
koko_1    | [GIN] 2023/04/12 - 10:45:47 | 200 |      48.672��s |       127.0.0.1 | GET      "/koko/health/"
koko_1    | [GIN] 2023/04/12 - 10:45:57 | 200 |      62.909��s |       127.0.0.1 | GET      "/koko/health/"
koko_1    | [GIN] 2023/04/12 - 10:46:07 | 200 |      45.114��s |       127.0.0.1 | GET      "/koko/health/"
koko_1    | [GIN] 2023/04/12 - 10:46:17 | 200 |      41.289��s |       127.0.0.1 | GET      "/koko/health/"
koko_1    | 2023-04-12 10:46:17 [ERRO] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF
koko_1    | [GIN] 2023/04/12 - 10:46:27 | 200 |      49.831��s |       127.0.0.1 | GET      "/koko/health/"
core_1    | 2023-04-12 10:46:26 Check service status: flower -> running at 16
celery_1  | 2023-04-12 10:46:26 Check service status: beat -> running at 18
core_1    | 2023-04-12 10:46:27 Check service status: gunicorn -> running at 17
celery_1  | 2023-04-12 10:46:27 Check service status: celery_ansible -> running at 19
lion_1    | [GIN] 2023/04/12 - 10:46:29 | 200 |      52.931��s |       127.0.0.1 | GET      "/lion/health/"
koko_1    | [GIN] 2023/04/12 - 10:46:37 | 200 |      53.379��s |       127.0.0.1 | GET      "/koko/health/"
lion_1    | [GIN] 2023/04/12 - 10:46:39 | 200 |      81.929��s |       127.0.0.1 | GET      "/lion/health/"
koko_1    | [GIN] 2023/04/12 - 10:46:47 | 200 |      53.791��s |       127.0.0.1 | GET      "/koko/health/"
lion_1    | [GIN] 2023/04/12 - 10:46:50 | 200 |       49.92��s |       127.0.0.1 | GET      "/lion/health/"
koko_1    | [GIN] 2023/04/12 - 10:46:57 | 200 |      43.665��s |       127.0.0.1 | GET      "/koko/health/"
core_1    | 2023-04-12 10:46:58 Check service status: flower -> stopped at 16
core_1    | 2023-04-12 10:46:58 Service start failed, exit: flower
core_1    | flower is stopped.
koko_1    | 2023-04-12 10:46:58 [ERRO] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF
magnus_1  | 2023-04-12 10:46:58 [ERRO] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF
lion_1    | 2023-04-12 10:46:58 main main.go [ERROR] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF
lion_1    | 2023-04-12 10:46:58 main main.go [ERROR] Ws heart beat closed, try reconnect after 10s
core_1    | Stop service: gunicorn Error
celery_1  | 2023-04-12 10:46:59 Check service status: celery_default -> running at 16
lion_1    | [GIN] 2023/04/12 - 10:47:00 | 200 |      55.253��s |       127.0.0.1 | GET      "/lion/health/"
celery_1  | 2023-04-12 10:47:00 Check service status: beat -> running at 18
celery_1  | 2023-04-12 10:47:01 Check service status: celery_ansible -> running at 19
core_1    | 2023-04-12 10:47:03 Check database connection: 0
core_1    | System check identified no issues (0 silenced).
core_1    | 2023-04-12 10:47:04 Database connect success
core_1    | 2023-04-12 10:47:04 Collect static files
core_1    | 2023-04-12 10:47:04 Collect static files done
core_1    | 2023-04-12 10:47:04 Check database structure change ...
core_1    | 2023-04-12 10:47:04 Migrate model change to database ...

**Comment by wojiushixiaobai** [comment]
flower 异常，尝试清理 jms_core 容器里面 /opt/jumpserver/data/flower 文件，然后重启看看问题是否解决。

**Comment by ShiLongTowngrass** [comment]
@wojiushixiaobai Thank you! that's a good a answer.

**Comment by ShiLongTowngrass** [comment]
@wojiushixiaobai Thank you! that's a good answer.
