### ISSUE TITLE
[Bug] sftp概率连接不上问题

### ISSUE THREAD

**Issue by dhfsqxz** [jumpserver/jumpserver#10199]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1.1

**浏览器版本**
chrome 112

**Bug 描述**
通过网域网关连接服务器，如果直接使用web sftp，概率性无法连接，等待超时
但是通过web cli先连接ssh，同一服务器的sftp在一段时间内就正常连接了

**Comment by BaiJiangJie** [comment]
可以稳定复现吗？

**Comment by dhfsqxz** [comment]
基本可以稳定复现，配置好后如果长时间(我本人测试的是几天)未连过，那么直接用sftp就会出现

**Comment by BaiJiangJie** [comment]
账号是手动登录还是自动登录？

**Comment by dhfsqxz** [comment]
手动登录自动登录都会出现，应该与jumpserver账号无关
且一旦出现只要不连接ssh就一直出现，我本地已经有出现问题的实例
如有需求可加我微信提供测试环境：dhfsqx
