### ISSUE TITLE
[Feature] 资产列表显示列不一致

### ISSUE THREAD

**Issue by tonycody** [jumpserver/jumpserver#10191]
# 管理后台的资产列表
![image](https://user-images.githubusercontent.com/6773121/231663326-e67fd7bc-e215-4eb4-880d-99be85bc4b8e.png)
建议标签这个列默认呈现，有利于同类机器标识是开发还是测试还是生产。这样主机名可以一致。

# 工作台我的资产
![image](https://user-images.githubusercontent.com/6773121/231663452-e6b8134d-7cd3-4e87-b869-e59bcc0428d5.png)

示例中，如果 Skywalking 有2台，一台是测试一台是生产，除非通过名字区分，因为标签在这里面没有。实际上标签指定了是测试还是生产。

建议至少到标签级别，在管理后台和工作台资产列表中保持一致。

**Comment by BaiJiangJie** [comment]
好的，v3.2 会优化一下。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/10338

v3.3 已支持
