### ISSUE TITLE
jumpserver logout can't login again

### ISSUE THREAD

**Issue by DarcyNing** [jumpserver/jumpserver#102]
![image](https://cloud.githubusercontent.com/assets/6072115/13386109/a018b70e-dee3-11e5-8e04-4dbf385b92b3.png)

**Comment by ibuler** [comment]
May be the user of you login isn't exist in database.
Please visit web console see it.

**Comment by DarcyNing** [comment]
I hava login using default user amazon ec2-user, it was in /etc/password

**Comment by DarcyNing** [comment]
My commandtext user is not exists. not jumpserver user not exists

**Comment by ibuler** [comment]
I get it. Because the file /etc/profile.d/zzjumpserver.sh . After installed, the script will be copy to /etc/profile.d/.

**Comment by DarcyNing** [comment]
ok, and after installation, My /etc/nsswitch.conf will be changed ?
![image](https://cloud.githubusercontent.com/assets/6072115/13386948/e75c3f9c-deec-11e5-843e-f86d78a0297d.png)

**Comment by DarcyNing** [comment]
it's  db is in front of file ?

**Comment by ibuler** [comment]
No, please run
#   mv /etc/profile.d/zzjumpserver /tmp  
then login again

**Comment by DarcyNing** [comment]
ok, thank you very much.

**Comment by DarcyNing** [comment]
Will the command mv /etc/profile.d/zzjumpserver /tmp   influence any function of jumpserver ?
