### ISSUE TITLE
[Question] 连接website资产报错，提示“Core API 发生错误”

### ISSUE THREAD

**Issue by palkiller** [jumpserver/jumpserver#10202]
**请描述您的问题.**
Jumpserver版本：**3.1.2开源版**
故障情况：
应用发布机已部署完成，当前状态正常
![image](https://user-images.githubusercontent.com/74942632/231916988-1111aae6-70ff-4e9c-9198-a28bc33eb8e4.png)
连接website资产时报错，提示“Core API 发生错误”
![image](https://user-images.githubusercontent.com/74942632/231916439-efbc5dc1-23c7-456a-b172-afdaeaecdc88.png)

**Comment by BaiJiangJie** [comment]
看一下日志  `/data/jumpserver/core/logs/jumpserver.log`

**Comment by palkiller** [comment]
日志报这个：
2023-04-14 11:21:51 [applet ERROR] Applet host remain accounts: AppPublishingSvr: 0

**Comment by palkiller** [comment]
> 检查一下发布机的账号列表有多少账号？
> 
> <img alt="image" width="1544" src="https://user-images.githubusercontent.com/32935519/231972617-3f6ad73b-0a0c-45c2-b726-cee33d1f49a7.png">

刚才那个问题知道原因了，这批账号我以为没用，直接删掉了，现在重新部署了发布机，远程应用还是连不上  -_-|||
![image](https://user-images.githubusercontent.com/74942632/232027966-60a7a367-86b6-457e-a9e8-de6330b5429b.png)
![image](https://user-images.githubusercontent.com/74942632/232028084-b73ac2af-6990-4e14-8392-81a245b51bb1.png)
![image](https://user-images.githubusercontent.com/74942632/232028129-e0ca8b63-c7d0-4146-986d-148fd6fe9eea.png)
![image](https://user-images.githubusercontent.com/74942632/232028181-c5851371-328f-4ba5-aaa9-d830ea99fe42.png)
账号列表除了特权账户外，有100个jms开头的帐号

**Comment by palkiller** [comment]
已经找到原因，自动推送的用户没有添加任何组，所以没办法远程调用，远程的权限添加everyone之后就可以了
官方的文档过于简单了，这些坑都没提到，郁闷，关贴...
