### ISSUE TITLE
低优先级系统用户和高优先级系统用户同时存在时，无法选择前者登录

### ISSUE THREAD

**Issue by zhus2015** [jumpserver/jumpserver#1020]
[简述你的问题]
我授权时给一个用户授权可以使用两个系统用户登录一台机器，但是只能看到 优先级高的系统用户，低优先级的系统用户无法看到，那这样授权两个系统用户岂不是没有意义了？

##### 使用版本
[0.5.0]

##### 问题复现步骤
1. 创建两个系统用户，一个优先级为10，一个优先级为9
2. 授权进行登录
3. 登录查看有权限的主机

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
优先级的意义就在于让用户不再二次选择，如果想看到就让两个系统用户优先级一致

**Comment by zhus2015** [comment]
如果想要用高优先级用户切换到低优先级用户，还可以切换吗？

**Comment by ibuler** [comment]
不可以，有着需求，你就直接让两个优先级保持一致

**Comment by BackFire** [comment]
建议支持 “系统用户名@资产名”的形式登陆资产，这样子可以支持低优先级系统用户登陆
