### ISSUE TITLE
[Question] 快捷命令问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10216]
**请描述您的问题.**
3.1.2
/usr/bin/ls -t /opt/jumpserver/db_backup/ | /usr/bin/tail -n +3 | /usr/bin/xargs /usr/bin/rm -rf这条命令在命令行可以执行，用jumpserver的快捷命令执行后没有效果

**Comment by wojiushixiaobai** [comment]
SHELL 环境不一样，请自行检查
