### ISSUE TITLE
[Bug] 大数量文件上传bug

### ISSUE THREAD

**Issue by honker-j** [jumpserver/jumpserver#10214]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.0

**浏览器版本**
chrome 110.0.5481.178

**Bug 描述**
在上传文件夹时，文件夹内文件数量超过150， 就会一直卡住 ， 无法上传成功

**Bug 重现步骤(有截图更好)**
1.
![20230415102541](https://user-images.githubusercontent.com/130810734/232178757-dfe2995a-bd29-4bd3-b733-eb776dbcc66f.png)

2.
3.

**Comment by LeeEirc** [comment]
由于文件太多，会超过 url 的最大长度的限制，造成请求失败。对于大数量的文件，建议先压缩再上传。
