### ISSUE TITLE
[Question] nginx二级反向代理失败

### ISSUE THREAD

**Issue by abcd0403** [jumpserver/jumpserver#10215]
jumpserver通过在debian linux上一键安装部署

以下是nginx的配置
    location /jms {
        proxy_pass http://10.1.1.1;
        rewrite "/jms/(.*)$" /$1 break;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect ~^/(.*) https://$http_host/jms/$1;
        sub_filter_types *;
        sub_filter_once off;
        sub_filter '/static/' '/jms\/static/';
        sub_filter '/ui/' '/jms/';
        sub_filter '/api/' '/jms/api/';
        sub_filter '/core/' '/jms/core/';
        sub_filter '/ws/notifications/' '/jms/ws/notifications/';
        sub_filter '/luna/' '/jms/luna/';
        sub_filter '/koko/' '/jms/koko/';
        sub_filter '/lion' '/jms/lion';
        sub_filter '/media/' '/jms/media/';
        sub_filter '/omnidb/' '/jms/omnidb/';
    }

当访问域名 https://exp.org/jms 时
浏览器会自动改为 https://exp.org/ui/#/jms 后反馈404
请帮帮我！不胜感激！

**Comment by abcd0403** [comment]
补充，实际上我用的是https，但在问题描述中例子是http

**Comment by BaiJiangJie** [comment]
你是不是应该访问 `http://exp.org/jms` 而不是 `http://exp.org/jmp`;

<img width="453" alt="image" src="https://user-images.githubusercontent.com/32935519/232419805-55fb7e83-1406-47fc-97ed-133a4e8e3ce7.png">

**Comment by BaiJiangJie** [comment]
这里需要修改成 /jms/ui/ 吗？

<img width="564" alt="image" src="https://user-images.githubusercontent.com/32935519/232656140-4c2871e4-7ef1-4fed-904d-c5ad8742ca81.png">

**Comment by abcd0403** [comment]
> 这里需要修改成 /jms/ui/ 吗？
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/32935519/232656140-4c2871e4-7ef1-4fed-904d-c5ad8742ca81.png">

您好，我是按照官方文档中这个页面进行设置的：https://github.com/jumpserver/docs/pull/213/files

按照您回复的我试了一下，注释掉了该行，可问题不变：
在我访问https://www.exp.org/jms时
浏览器会自动跳转为https://www.exp.org/ui/#/jms并反馈404

**Comment by BaiJiangJie** [comment]
好吧，具体方式就是配置的那样，至于为什么不成功就不清楚了。

**Comment by abcd0403** [comment]
> 好吧，具体方式就是你配置的那样，至于为什么不成功就不清楚了。

我看那篇github二级目录反带已经是去年6月提交的了。应该是老版本。我用的这个比他的那个要新，会不会因为版本问题？

**Comment by BaiJiangJie** [comment]
nginx 这一块v3、v2的变化不大，应该不是。

**Comment by rainbird** [comment]
> jumpserver通过在debian linux上一键安装部署
> 
> 以下是nginx的配置 location /jms { proxy_pass http://10.1.1.1; rewrite "/jms/(._)$" /$1 break; proxy_http_version 1.1; proxy_buffering off; proxy_request_buffering off; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_redirect ~^/(._) https://$http_host/jms/$1; sub_filter_types *; sub_filter_once off; sub_filter '/static/' '/jms/static/'; sub_filter '/ui/' '/jms/'; sub_filter '/api/' '/jms/api/'; sub_filter '/core/' '/jms/core/'; sub_filter '/ws/notifications/' '/jms/ws/notifications/'; sub_filter '/luna/' '/jms/luna/'; sub_filter '/koko/' '/jms/koko/'; sub_filter '/lion' '/jms/lion'; sub_filter '/media/' '/jms/media/'; sub_filter '/omnidb/' '/jms/omnidb/'; }
> 
> 当访问域名 https://exp.org/jms 时 浏览器会自动改为 https://exp.org/ui/#/jms 后反馈404 请帮帮我！不胜感激！

咋样？搞定没？

**Comment by abcd0403** [comment]
> > jumpserver通过在debian linux上一键安装部署
> > 以下是nginx的配置 location /jms { proxy_pass http://10.1.1.1; rewrite "/jms/(._)$" /$1 break; proxy_http_version 1.1; proxy_buffering off; proxy_request_buffering off; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header X-Real-IP $remote_addr; proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_redirect ~^/(._) https://$http_host/jms/$1; sub_filter_types *; sub_filter_once off; sub_filter '/static/' '/jms/static/'; sub_filter '/ui/' '/jms/'; sub_filter '/api/' '/jms/api/'; sub_filter '/core/' '/jms/core/'; sub_filter '/ws/notifications/' '/jms/ws/notifications/'; sub_filter '/luna/' '/jms/luna/'; sub_filter '/koko/' '/jms/koko/'; sub_filter '/lion' '/jms/lion'; sub_filter '/media/' '/jms/media/'; sub_filter '/omnidb/' '/jms/omnidb/'; }
> > 当访问域名 https://exp.org/jms 时 浏览器会自动改为 https://exp.org/ui/#/jms 后反馈404 请帮帮我！不胜感激！
> 
> 咋样？搞定没？

一直没搞成

**Comment by BaiJiangJie** [comment]
看了一下，目前 JumpServer 不支持二级反向代理，需要做适配。

**Comment by mylovesaber** [comment]
可能不是nginx的配置文件，问题可能出在前端 lina 的代码上，参考https://github.com/jumpserver/jumpserver/issues/10309#issuecomment-1804984126

**Comment by jiang2050** [comment]
sub_filter '"/koko"' '"/jump/koko"';  ##添加这个可以解决 web终端无法打开的问题
