### ISSUE TITLE
jms_core 一直unhealthy,无法启动

### ISSUE THREAD

**Issue by jack891011** [jumpserver/jumpserver#10217]
**请描述您的问题.**
启动jumpserver时，jms_core这个容器 一直unhealthy,无法启动, 查了下日志，貌似也没有啥报错，求大佬帮忙
![image](https://user-images.githubusercontent.com/26128800/232305370-5aaae90f-9015-4004-b152-14480d2146ac.png)
![image](https://user-images.githubusercontent.com/26128800/232305394-2445bddb-402b-4c14-99f2-1bf88371623a.png)

**Comment by wojiushixiaobai** [comment]
超时？
```sh
docker exec -it jms_core bash
curl http://localhost:8080/api/health/
```
看看能不能正确获取

**Comment by jack891011** [comment]
> 超时？
> 
> ```shell
> docker exec -it jms_core bash
> curl http://localhost:8080/api/health/
> ```
> 
> 看看能不能正确获取

奇怪了，我放那不管他，过了四五个小时以后， jmsctl restart 居然就可以正常启动了。，正常启动以后执行curl http://localhost:8080/api/health/ 是可以正常获取返回的

**Comment by wojiushixiaobai** [comment]
处于 unhealthy 时，容器会自启直到容器 healthy

**Comment by jack891011** [comment]
> 处于 unhealthy 时，容器会自启直到容器 healthy

好的好的。感谢

**Comment by guoqc3** [comment]
curl -fsL http://localhost:8080/api/health/ 返回是正常的，但是还是一直是unhealthy 是什么情况？
![image](https://github.com/jumpserver/jumpserver/assets/57341168/afbed7a1-44ea-48ef-8ded-1608733fed3f)

**Comment by tsukiazuma** [comment]
how about return Fail to connect:
`curl: (28) Failed to connect to localhost port 8080: Connection timed out`
