### ISSUE TITLE
[Question] 推送用户报权限不够

### ISSUE THREAD

**Issue by jonys1994** [jumpserver/jumpserver#10219]
**请描述您的问题.**
执行账号推送（非特权账号）时有如下报错：
fatal: [app-90-87(reader)]: FAILED! => {"changed": false, "cmd": "/sbin/useradd -p VALUE_SPECIFIED_IN_NO_LOG_PARAMETER-m reader", "msg": "[Errno 13] 权限不够", "rc": 13, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

而推送特权账号则无此问题
直接通过ansible对目标主机执行“/sbin/useradd -p VALUE_SPECIFIED_IN_NO_LOG_PARAMETER-m reader“是没有报错的

jumpserver版本：v3.0.1

**Comment by wojiushixiaobai** [comment]
等待修复

**Comment by BaiJiangJie** [comment]
最新版本已修复。
