### ISSUE TITLE
[Feature] 多云资产同步支持根据主机名匹配策略同步到指定资产节点

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#10225]
我司目前阿里云资产分为JAVA 、PHP 两类主机，目前是通过主机名来区分的，大致格式是这样的 “JAVA_xxxx”。
由于目前资产的弹性伸缩比较频繁，希望针对资产节点去做授权，也就是JAVA 类主机自动授权给内部JAVA 组。
因此期望在资产同步的时候，根据主机名进行模糊匹配，命中匹配规则（正则表达式匹配）就同步到指定的资产节点下。

**Comment by BaiJiangJie** [comment]
有在考虑这一块的设计，先记录到内部了。
