### ISSUE TITLE
使用v3.1.2版本无法正常连接阿里云Mongo实例V3.4版本

### ISSUE THREAD

**Issue by lifubinmx** [jumpserver/jumpserver#10227]
**请描述您的问题.**
使用jmsV3.1.2版本创建阿里云Mongo实例v3.4版本后，无法正常连接，测试连接界面报版本兼容性问题，想了解一下V3.1.2版本jms还是否支持对MongoV3.4版本的管理，能否在jms上面创建资产时可以选择客户端的版本，兼容较低版本（如V3.4）的Mongo数据库。

**Comment by iyunwei8971** [comment]
进入koko容器内使用mongosh命令连接时，报的信息一样：
MongoServerSelectionError: Server at dds-j6cec73047-pub.mongodb.rds.aliyuncs.com:3717 reports maximum wire version 5, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)

**Comment by BaiJiangJie** [comment]
我们每次发布都是使用官方最新版本的 (MongoDB Client)[https://www.mongodb.com/docs/v5.0/release-notes/5.0/]

支持的数据库版本也是根据 client 来的，对于在创建的时候选择客户端版本，目前没有支持计划。

**Comment by lifubinmx** [comment]
了解，感谢！
