### ISSUE TITLE
[Question] 2.9.2版本的一些问题

### ISSUE THREAD

**Issue by wangchaoHeart** [jumpserver/jumpserver#10238]
1.     2.9.2版本中的guacamole组件是完全开源的吗(直接引用的官方版本)？还是在Apache Guacamole基础上做了一些开发？
2.     如果是开源的，我是不是可以按照Apache Guacamole官网的方式部署guacamole组件

**Comment by BaiJiangJie** [comment]
1. ` 2.9.2版本中的guacamole组件是完全开源的吗(直接引用的官方版本)？还是在Apache Guacamole基础上做了一些开发？`

做了一些开发。
