### ISSUE TITLE
api的方式打开远程终端窗口 

### ISSUE THREAD

**Issue by mifashion** [jumpserver/jumpserver#10237]
我使用/api/v1/authentication/connection-token/获取到token后接下来不知道该怎么去连接终端，因为我想把终端页集成到我们自己的项目当中

**Comment by wojiushixiaobai** [comment]
你可以参考 luna 项目，看 iframeURL 和 token 部分的调用和拼接即可。

**Comment by mifashion** [comment]
但是每次调用/lion/connect?token=接口时都要校验登录，这个要怎么弄啊，前端代码看不懂

**Comment by BaiJiangJie** [comment]
校验登录的话，可以通过单点登录解决。
