### ISSUE TITLE
[Question] docker-compose 部署的jms_core一分钟重启一次

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#10231]
**请描述您的问题.**
我使用的是docker-compose部署的负载均衡的jumpserver，版本是Version v2.28.8
当我尝试用./jmsctl.sh restart或者./jmsctl.sh uninstall && ./jmsctl.sh install 之后每间隔一分钟重启现象依旧。请问要如何解决该问题。
以下是错误截图：
1、docker 容器状态
![image](https://user-images.githubusercontent.com/13248366/232676514-2c5d049b-bd14-4dbd-b3af-6346c8d3f290.png)
2、jms_core 容器报错日志
![image](https://user-images.githubusercontent.com/13248366/232676654-c3633363-819f-4e8c-a0e3-33fd0a4bf70e.png)
3、当jms_core容器重启后访问页面报错信息
![image](https://user-images.githubusercontent.com/13248366/232676907-be42a4f4-5239-4986-b4d3-7a23c28a21a8.png)

**Comment by wojiushixiaobai** [comment]
flower 异常的话，删掉持久化文件 
```sh
docker exec -it jms_core bash
rm -f data/flower
exit
```
```sh
docker restart jms_core
```
