### ISSUE TITLE
当前版本的jumpserver是否有提供api和各api接口的使用方法

### ISSUE THREAD

**Issue by mrBob90** [jumpserver/jumpserver#1024]
[简述你的问题]
请问当前版本的jumpserver是否有提供api和各api接口的使用方法
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
 0.3.2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
当前操作添加主机，修改权限等操作只能在jumpsever平台进行，不便于自动化操作。

##### 其他

[注:] 完成后请关闭 issue

**Comment by mrBob90** [comment]
https://pypi.python.org/pypi/jumpserver-python-sdk/0.0.8#downloads

**Comment by mrBob90** [comment]
https://pypi.python.org/pypi/jumpserver-python-sdk/0.0.8#downloads    
这个链接的sdk是你们官方提供的吗

**Comment by ibuler** [comment]
本来打算做了，可是时间实在有限，不过会一步一步来的，是官方的sdk

**Comment by ibuler** [comment]
其实 访问 /docs/会列出api文档的 

![image](https://user-images.githubusercontent.com/17382885/36957804-019e2b7c-2072-11e8-9ec5-ebcac9108d3c.png)

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/36957808-0965eef8-2072-11e8-90c7-852ac14f06e5.png)

**Comment by KeithTt** [comment]
> 其实 访问 /docs/会列出api文档的
> 
> ![image](https://user-images.githubusercontent.com/17382885/36957804-019e2b7c-2072-11e8-9ec5-ebcac9108d3c.png)

正在找接口文档，这个 swagger 好棒

**Comment by hedaweiii** [comment]
命名太抽象了，没有注解，只能靠猜😂
