### ISSUE TITLE
[Feature] 资产搜索的建议

### ISSUE THREAD

**Issue by tonycody** [jumpserver/jumpserver#10251]
涉及的功能位置：
- 资产管理UI
- Web 终端资产列表UI

![image](https://user-images.githubusercontent.com/6773121/232935955-fbf9129f-ba6a-4b68-98a8-876a73db3f84.png)

如上图示例中的 Web 终端内的资产列表。
问题1：限制大小写搜索，没找到位置可以修改不限制大小写。这边限制大小写有什么意义？只能影响搜索时的复杂度。要频繁切或试可能是因为大小写拼错了导致搜索不到。
问题2：这个搜索框默认展开不折叠不香吗？折叠是为了什么？一大片区域是空的，折叠就影响搜索时的体验。要反复展开和自动折叠。

以上2个问题点在Web终端、控制台资产管理中都是一样的问题。

**Comment by ibuler** [comment]
1. 大小写是数据决定的，修改一下校对集
2. 只从美观上入手了，一直显示着没做好设计，尤其管理控制台

**Comment by tonycody** [comment]
> 1. 大小写是数据决定的，修改一下校对集
> 2. 只从美观上入手了，一直显示着没做好设计，尤其管理控制台

大小写的问题需要解决啊，不能因为写入的数据包含了大写，搜索的时候必须要大写吧。企业微信还支持拼音首字母呢。人家写入的是中文。是不是这道理呢。
主要是搜索区分了大小写，不利于搜索包含了大小写混合的资产名称。要反复大小写混合试错，尤其是比如资产命名为：ApachePulsar 这种。

**Comment by ibuler** [comment]
look look 这个 https://github.com/jumpserver/jumpserver/issues/6918
