### ISSUE TITLE
jumpserver版本的v3.1.2，创建使用mongodb数据库资产，连接测试mongodb3.2版本报错

### ISSUE THREAD

**Issue by li-lin99** [jumpserver/jumpserver#10259]
问题:
jumpserver的v3.1.2，创建使用mongodb数据库资产，连接测试mongodb3.2版本报错。
报错：
fatal: [mongodb-test]: FAILED! => {"changed": false, "msg": "Unable to determine if auth is enabled: Traceback (most recent call last):\n  File \"/tmp/ansible_mongodb_ping_payload_78mj1ffp/ansible_mongodb_ping_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_common.py\", line 279, in is_auth_enabled\n    myclient['admin'].command('listDatabases', 1.0)\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/database.py\", line 594, in command\n    with self.__client._socket_for_reads(\n  File \"/usr/local/lib/python3.9/contextlib.py\", line 119, in __enter__\n    return next(self.gen)\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py\", line 1177, in _socket_for_reads\n    server = self._select_server(read_preference, session)\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py\", line 1137, in _select_server\n    server = topology.select_server(server_selector)\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/topology.py\", line 242, in select_server\n    servers = self.select_servers(\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/topology.py\", line 200, in select_servers\n    server_descriptions = self._select_servers_loop(\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/topology.py\", line 228, in _select_servers_loop\n    self._description.check_compatible()\n  File \"/usr/local/lib/python3.9/site-packages/pymongo/topology_description.py\", line 130, in check_compatible\n    raise ConfigurationError(self._incompatible_err)\npymongo.errors.ConfigurationError: Server at 10.1.6.7:27017 reports wire version 4, but this version of PyMongo requires at least 6 (MongoDB 3.6).\n"}
报错截图：
![微信图片_20230419134834](https://user-images.githubusercontent.com/64114440/232978520-2f432bb7-e5f7-4ff6-9fe2-7910a9fcc28c.png)

**Comment by BaiJiangJie** [comment]
>= MongoDB 3.6 的版本


<img width="1239" alt="image" src="https://user-images.githubusercontent.com/32935519/234216952-0db9cb94-1589-437f-b413-f4d2b158fb10.png">

**Comment by BaiJiangJie** [comment]
在 Web 终端页面可以连接成功吗？

**Comment by li-lin99** [comment]
不行，上图就是在web终端页面测试的

**Comment by BaiJiangJie** [comment]
我们尝试使用一下 MongoDB 3.2 版本看看能不能复现。

**Comment by BaiJiangJie** [comment]
Web CLI 使用的是  `mongosh`，目前官方给出 `mongosh` 不支持 4.2 以下的版本；

https://www.mongodb.com/docs/mongodb-shell/install/

**Comment by li-lin99** [comment]
好的，感谢

**Comment by bryanzl** [comment]
如何让jumpserver可以连接mongo3.6以下的版本呢
