### ISSUE TITLE
jumpserver命令行窗口用top等命令时 文本对不齐

### ISSUE THREAD

**Issue by wwwyang** [jumpserver/jumpserver#1026]
[jumpserver命令行窗口用top等命令时 文本对不齐]

##### 使用版本
[0.3.2]

##### 问题复现步骤
1. 见截图

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/33954514/36722413-69fba85e-1be8-11e8-814f-b96037f0ed51.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
0.3.2不再维护
