### ISSUE TITLE
[Question] doris生成的代理账号连接查询sql报错

### ISSUE THREAD

**Issue by FLVE** [jumpserver/jumpserver#10263]
通过doris生成的代理账号，可以连接，但查询语句时，返回MySQL server has gone away。
![image](https://user-images.githubusercontent.com/46079296/233061167-6e6f6fd1-9ca3-404b-b6a6-0c3c3d6420a9.png)

通过JumpServerde Web CLI的方式是可以正常连接查询的。
![image](https://user-images.githubusercontent.com/46079296/233061040-0db966a0-3399-46e9-95a6-1563c37dc0c8.png)

**Comment by BaiJiangJie** [comment]
`通过doris生成的代理账号，可以连接，但查询语句时，返回MySQL server has gone away。`

没看懂，这是通过 JumpServer 的什么方式连接的？

**Comment by FLVE** [comment]
> 
![](https://user-images.githubusercontent.com/46079296/233061167-6e6f6fd1-9ca3-404b-b6a6-0c3c3d6420a9.png)
通过使用JumpServer 的DB Client生成的连接账号，在cvm上可以使用该账号信息连接到doris，但是在进行查询语句时，就会报这个错误

使用JumpServer 的Web CLI方式连接访问doris，是没有问题的。

**Comment by BaiJiangJie** [comment]
那使用 DB Client 链接 doris 并且查询会报错吗？

**Comment by FLVE** [comment]
> 那使用 DB Client 连接 doris 并且查询会报错吗？
这样连接都存在问题

**Comment by BaiJiangJie** [comment]
使用 DB Client 直连 doris 生成一些连接账号，然后在使用 DB Client 通过 JumpServer 连接 doris （使用生成的连接账号）并且查询会有问题吗？


主要确认以下几种情况的连接（包括查询）是否有问题：

只连：不通过 JumpServer 进行连接；

1. DB Client 直连 doris，使用 JumpServer 生成的账号；
2. DB Client + JumpServer 使用普通账号（不是通过 JumpServer 生成的账号，是通过直连方式生产的账号）连接 doris；

**Comment by FLVE** [comment]
> 使用 DB Client 直连 doris 生成一些连接账号，然后在使用 DB Client 通过 JumpServer 连接 doris （使用生成的连接账号）并且查询会有问题吗？
> 
> 主要确认以下几种情况的连接（包括查询）是否有问题：
> 
> 只连：不通过 JumpServer 进行连接；
> 
> 1. DB Client 直连 doris，使用 JumpServer 生成的账号；
> 2. DB Client + JumpServer 使用普通账号（不是通过 JumpServer 生成的账号，是通过直连方式生产的账号）连接 doris；


1、doris直连，连接查询没有问题
![企业微信截图_16825602882043](https://user-images.githubusercontent.com/46079296/234740194-b2864352-8444-49d1-a316-656614567bb9.png)

2、使用JumpServer的Web CLI方式，连接查询没有问题
![企业微信截图_16825603648099](https://user-images.githubusercontent.com/46079296/234740364-8dcdab9e-5310-4792-aa27-504856463754.png)

3、使用JumpServer 的 DB Client生成代理账号方式：服务器上连接没有问题，查询报错；本地无法连接
![企业微信截图_16825604523737](https://user-images.githubusercontent.com/46079296/234740543-86637025-516e-4cfb-a4e5-969305d6f459.png)

**Comment by BaiJiangJie** [comment]
DB Client 主要还是支持 MySQL 协议，Doris 的话其实有些操作上和 MySQL 的底层协议还是不一样的，所以有一些命令在执行的时候就会有问题。

目前 JumpServer 也没有计划单独支持 Doris 数据库；

**Comment by FLVE** [comment]
> DB Client 主要还是支持 MySQL 协议，Doris 的话其实有些操作上和 MySQL 的底层协议还是不一样的，所以有一些命令在执行的时候可能会有问题。
> 
> 不过，目前 JumpServer 也没有单独完美支持 Doris 数据库的计划；

好的，多谢解答。感谢 😊
