### ISSUE TITLE
添加windows主机测试连接性显示22端口

### ISSUE THREAD

**Issue by Lihy6472** [jumpserver/jumpserver#10261]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.1.1

**浏览器版本**

chrom 112.0.5615.49

**Bug 描述**

* 添加windows主机后更新硬件信息显示失败，端口为22。目标主机防火墙未开启，未安装安全软件。

**Bug 重现步骤(有截图更好)**

* 以下为操作的录屏：

https://image.jishuliu.cn/%E8%A7%86%E9%A2%91/Desktop%202023.04.19%20-%2014.22.45.02.mp4

* 可以连接，但是不能复制上传文件

![image](https://user-images.githubusercontent.com/116717391/232988924-1ccb1074-ab8d-4cf2-9c13-afbcf07904f2.png)
![image](https://user-images.githubusercontent.com/116717391/232989016-10a9d07c-9105-4643-ba64-abf1f7b34349.png)

**Comment by wojiushixiaobai** [comment]
测试可连接性需要客户端部署 openssh-server 服务才行

**Comment by BaiJiangJie** [comment]
windows 的一些自动化任务是需要安装 openssh-server 的。

如果你只使用 rdp 连接 windows，包括复制文字、上传下载文件都不需要 openssh-server.

**Comment by Lihy6472** [comment]
> windows 的一些自动化任务是需要安装 openssh-server 的。
> 
> 如果你只使用 rdp 连接 windows，包括复制文字、上传下载文件都不需要 openssh-server.

好的，了解了，
