### ISSUE TITLE
修改jumpserver的config.txt不生效

### ISSUE THREAD

**Issue by mifashion** [jumpserver/jumpserver#10264]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.2

**浏览器版本**
112.0.5615.86

**Bug 描述**
修改config.txt配置开启SSO认证，请求接口返回SSO 认证关闭了

**Bug 重现步骤(有截图更好)**
1.按照文档执行 vi /opt/jumpserver/config/config.txt，
2.然后在末尾追加了一行AUTH_SSO=True的配置，
3.docker重启jumpserver所有的容器后，
4.通过Private Token的方式去创建免密登录链接，请求后接口返回“SSO 认证关闭了”
![image](https://user-images.githubusercontent.com/33660730/233242364-c9cbc2d0-1835-4c6f-98df-ad02b7bcc6d6.png)
![image](https://user-images.githubusercontent.com/33660730/233242197-bc7fed63-dda1-4e4b-aa80-293c46e1b4c6.png)

**Comment by mifashion** [comment]
刷新下了文档，一看这功能要收费了
![E88GZPUWFVDHABP)KB6_FYJ](https://user-images.githubusercontent.com/33660730/233289236-3eb49eb7-d61c-43ce-bd24-cf17bab6f312.png)

**Comment by yuanhaoliang** [comment]
在后台开启CAS认证是好使的。用Private Token也没问题。
