### ISSUE TITLE
作业中心：test:	ping => to use the 'ssh' connection type with passwords, you must install the sshpass program

### ISSUE THREAD

**Issue by cjw0202** [jumpserver/jumpserver#1027]
[简述你的问题]

 test: | ping => to use the 'ssh' connection type with passwords, you must install the sshpass program
-- | --
安装完sshpass还是一直报这个 求解答

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
建议重启下服务试试。还不行的话可以直接重启一下服务器。

**Comment by cjw0202** [comment]
试过了 还是不行哎  我直接运行ansible是可以的，在jumpserver中就不行

**Comment by wojiushixiaobai** [comment]
@cjw0202 只有一台被控服务器这样还是所有服务器都这样

**Comment by cjw0202** [comment]
@wojiushixiaobai 我试了两台主机都是这样，这个应该跟被控段没关系，应该是server端的问题

**Comment by cjw0202** [comment]
@wojiushixiaobai  而且我另外一个server直接用的docker 也是这样  不知道咋回事

**Comment by wojiushixiaobai** [comment]
@cjw0202  233333，老哥你直接到jumpserver容器（或者jumpserver服务器）里面，然后用ssh连被控端试试。

**Comment by cjw0202** [comment]
@wojiushixiaobai 这样和直接用ansible一样 都可以连

**Comment by wojiushixiaobai** [comment]
@cjw0202 重装试试老哥。。我没遇到过这问题，不能给你更多帮助了。

**Comment by cjw0202** [comment]
@wojiushixiaobai  关键我直接用他官方的docker 镜像也是这样，是不是要配置什么啊，但是在github中的安装文档也没有啊。很纳闷，还是很感谢。

**Comment by wojiushixiaobai** [comment]
@cjw0202 https://github.com/jumpserver/jumpserver/wiki/v0.5.0-基于-CentOS7  参照这个来一遍试试？

**Comment by cjw0202** [comment]
@wojiushixiaobai 就是按照这个安装的

**Comment by ibuler** [comment]
是不是和python版本有关系？

**Comment by cjw0202** [comment]
@ibuler 不应该吧  按照文档用的是python3.6.1的虚拟环境

**Comment by cjw0202** [comment]
好像找到问题了，之前我是用supervisor管理进程的
[program:jumpserver]
environment=PATH="/py3/jumpserver/bin"
directory=/py3/jumpserver-dev/
command=/py3/jumpserver/bin/python3 run_server.py all
#command=python -V
pidfile=/py3/jumpserver.pid
autostart=true
autorestart=true
startsecs=3
配置基本类似上面这样

然后手动前台启动各个服务，现在是可以使用的

但是这样不是事呀，这几个进程怎么管理呢？求赐教

**Comment by Aruiwen** [comment]
environment=PATH="/py3/jumpserver/bin:$(ENV_PATH)"

改成这样测试下

**Comment by jianjian01** [comment]
这个问题解决了吗？不使用 docker 应该怎么部署？
