### ISSUE TITLE
求教:docker 部署如何使用 web terminal? 

### ISSUE THREAD

**Issue by xumin-sh** [jumpserver/jumpserver#1028]
[简述你的问题]
想快速的看看jumpserver,用docker部署的,然而,登陆进去发现没有web terminal链接,运行以下命令后,还需要什么配置么?在https://github.com/jumpserver/Dockerfile  此页面没看到有别的什么说明呀...

docker run -p 8080:80 -p 2222:2222 jumpserver/jumpserver:0.5.0-beta2

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0-bata2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![20180228153711](https://user-images.githubusercontent.com/32701132/36775503-46867376-1c9d-11e8-972f-b74b74d3651d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
右上角-用户界面 里面访问web terminal

![image](https://user-images.githubusercontent.com/17382885/36828796-ef2b934e-1d56-11e8-9ecf-1967dac210c3.png)

**Comment by xumin-sh** [comment]
找到了，非常感谢，没想到它藏的那么深，看来还是点的不够多，我先折腾折腾，再次感谢～

**Comment by ibuler** [comment]
已经做了更改，放到更容易找到的地
