### ISSUE TITLE
[Question] 无法限制上传与下载的文件大小

### ISSUE THREAD

**Issue by Egbert-518** [jumpserver/jumpserver#10282]
**请描述您的问题.**
您好，我想限制用户上传和下载的文件大小，我查找到了/opt/jumpserver/config/config.txt中的CLIENT_MAX_BODY_SIZE，并将它改为100m(也试过100M)，但是通过页面的“文件管理”依然可以上传大文件，请问我的操作有哪里有问题？或是如何可以限制文件大小吗？谢谢！

**Comment by ibuler** [comment]
文件管理中，我们做了分片处理，现在不会影响 linux 上传，影响是 windows

**Comment by Egbert-518** [comment]
> 文件管理中，我们做了分片处理，现在不会影响 linux 上传，影响是 windows

好的，感谢！
