### ISSUE TITLE
0.5.0版本的资产组和集群功能取消了嘛？

### ISSUE THREAD

**Issue by yyhutao** [jumpserver/jumpserver#1029]
[简述你的问题]
0.5.0版本的资产组和集群功能取消了嘛？
0.5.0 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，使用了更加灵活的 资产树

**Comment by yyhutao** [comment]
资产树是什么
