### ISSUE TITLE
[Bug] 命令过滤审批功能

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10302]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.0

**浏览器版本**

**Bug 描述**
当用户执行一个需要审批的命令时，管理员打开邮件点击提示的查看详情和直接审批无法打开jumpserver详情页面和审批页面
![image](https://user-images.githubusercontent.com/44529247/233590469-dc02e9dc-52d6-4e55-afe5-ec6364325a24.png)

![image](https://user-images.githubusercontent.com/44529247/233590065-d89f3fc9-9163-4a4d-bceb-bc251b5d7071.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
社区版本？还是企业版本？

**Comment by ryswork1993** [comment]
社区版，社区版不支持吗



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月21日 17:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Bug] 命令过滤审批功能 (Issue #10302) |

社区版本？还是企业版本？

**Comment by BaiJiangJie** [comment]
对的，社区版暂时不支持审批。

**Comment by jym503558564** [comment]
已修复
