### ISSUE TITLE
[Bug] 指定资产授权，显示未分组

### ISSUE THREAD

**Issue by zhongjun96** [jumpserver/jumpserver#10304]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

V3.1.2

**浏览器版本**

Google Chrome 112.0.5615.137（正式版本） (x86_64)

**Bug 描述**

例如有节点`/DEV`，下面有 `A,B,C` 三个资产。在资产授权里只授权 `A` 资产。

现在在终端页面，`A` 会归类到`未分组`节点。

期望值：`A` 归类到 `/DEV` 节点

**Bug 重现步骤(有截图更好)**
1. ![](https://files.catbox.moe/24p07x.png)
2. ![](https://files.catbox.moe/lnu8df.png)
3. ![](https://files.catbox.moe/53dlpw.png)

**Comment by BaiJiangJie** [comment]
在系统设置 - 其他设置中，关闭设置项 `显示未分组节点`。

**Comment by zhongjun96** [comment]
> 在系统设置 - 其他设置中，关闭设置项 `显示未分组节点`。

可以了😌
