### ISSUE TITLE
[Question] 二级域名配置

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#10309]
kubernetes部署jumpserver服务时，域名不使用demo.jumpserver.com而是想使用tools.xxx.com/jumpserver的方式

想了解是否可以通过更改web服务的配置文件来实现，还是只能用web前面再套一层nginx的方式呢?

**Comment by wojiushixiaobai** [comment]
需要自测，目前我们尚未对此进行适配。

**Comment by songchaoqiang** [comment]
这个文档可以作为参考吗?
https://docs.jumpserver.org/zh/v3/installation/proxy/#2-nginx

**Comment by BaiJiangJie** [comment]
可以参考这个

https://github.com/jumpserver/docs/pull/213/files

但是没有进行适配测试；


也可以和 https://github.com/jumpserver/jumpserver/issues/10215 用户进行沟通一下。

**Comment by carlsue** [comment]
研究了下，gzip会引起问题。我通过set header access encoding解除了第一层gzip，可以解决ui  404 问题，但koko那又不行了

**Comment by mylovesaber** [comment]
> 可以参考这个
> 
> https://github.com/jumpserver/docs/pull/213/files
> 
> 但是没有进行适配测试；
> 
> 也可以和 #10215 用户进行沟通一下，也有同样的问题。

症状表现是做好代理后 `location /jms {...}` ，即 jms 作为二级目录，我打开链接地址：
http://10.0.0.2/jms
按照正常情况应该变成这个链接：
http://10.0.0.2/jms/ui/#/
但实际是：
http://10.0.0.2/ui/#/jms
我做了不少尝试，链接总是被改成ui在面前的情况，说明问题应该不是出在nginx的配置上

我找了下，问题来源应该是前端把链接路径做了强转导致的，nginx在前端之前，因此理论上无论nginx如何配置，转发到前端的时候就被这html里面把链接路径改写了，要改的应该就是这个地方：
https://github.com/jumpserver/lina/blob/master/public/index.html
```html
      window.onload = function() {
        if (location.pathname === '/') {
           location.pathname = '/ui/'
        }
        const pathname = window.location.pathname
        if (pathname.startsWith('/core')) {
            return
        }
        if(pathname.indexOf('/ui') === -1) {
          window.location.href = window.location.origin + '/ui/#' + pathname
        }
      }
```
我觉得以上代码段可能解释了为何jms总是被挤到ui的后面。你们有时间去改一下么？

**Comment by carlsue** [comment]
> > 可以参考这个
> > https://github.com/jumpserver/docs/pull/213/files
> > 但是没有进行适配测试；
> > 也可以和 #10215 用户进行沟通一下，也有同样的问题。
> 
> 症状表现是做好代理后 `location /jms {...}` ，即 jms 作为二级目录，我打开链接地址： http://10.0.0.2/jms 按照正常情况应该变成这个链接： http://10.0.0.2/jms/ui/#/ 但实际是： http://10.0.0.2/ui/#/jms 我做了不少尝试，链接总是被改成ui在面前的情况，说明问题应该不是出在nginx的配置上
> 
> 我找了下，问题来源应该是前端把链接路径做了强转导致的，nginx在前端之前，因此理论上无论nginx如何配置，转发到前端的时候就被这html里面把链接路径改写了，要改的应该就是这个地方： https://github.com/jumpserver/lina/blob/master/public/index.html
> 
> ```
>       window.onload = function() {
>         if (location.pathname === '/') {
>            location.pathname = '/ui/'
>         }
>         const pathname = window.location.pathname
>         if (pathname.startsWith('/core')) {
>             return
>         }
>         if(pathname.indexOf('/ui') === -1) {
>           window.location.href = window.location.origin + '/ui/#' + pathname
>         }
>       }
> ```
> 
> 我觉得以上代码段可能解释了为何jms总是被挤到ui的后面。你们有时间去改一下么？

你这个ui不是问题，只要反代nginx加上 proxy_set_header Accept-Encoding '';就能解决。麻烦的是koko组件，怎么调都不对。
feat: 添加 二级目录代理 jms 文档 #213
