### ISSUE TITLE
[Question] V2.28.8升级到V3.2.0问题

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#10316]
你好，我从V2.28.8升级到V3.2.0，显示升级成功。
但是发现几个问题：
1. 版本号还是V2.28.8
2. 没有账号管理菜单
3. 资产显示都不正常

![image](https://user-images.githubusercontent.com/40048968/233828821-2dc9eccb-b771-4d5d-a0ea-57e4a7dcfe7e.png)

参照的如下文档：
https://docs.jumpserver.org/zh/v3/installation/setup_linux_standalone/online_upgrade/

具体升级过程如下：
[root@pro-login102 14:42:03 opt]#cd /opt
[root@pro-login102 14:42:05 opt]#wget https://resource.fit2cloud.com/jumpserver/installer/releases/download/v3.2.0/jumpserver-installer-v3.2.0.tar.gz
--2023-04-23 14:43:14-- https://resource.fit2cloud.com/jumpserver/installer/releases/download/v3.2.0/jumpserver-installer-v3.2.0.tar.gz
Resolving [resource.fit2cloud.com](http://resource.fit2cloud.com/) ([resource.fit2cloud.com](http://resource.fit2cloud.com/))... 140.249.61.246
Connecting to [resource.fit2cloud.com](http://resource.fit2cloud.com/) ([resource.fit2cloud.com](http://resource.fit2cloud.com/))|140.249.61.246|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47758 (47K) [application/gzip]
Saving to: ‘jumpserver-installer-v3.2.0.tar.gz’

100%[================================================================================================================================================================================================>] 47,758 --.-K/s in 0.04s

2023-04-23 14:43:14 (1.08 MB/s) - ‘jumpserver-installer-v3.2.0.tar.gz’ saved [47758/47758]

[root@pro-login102 14:43:36 opt]#cd jumpserver-installer-v3.2.0
[root@pro-login102 14:43:41 jumpserver-installer-v3.2.0]#ls -al
total 104
drwxr-xr-x 8 root root 4096 Apr 20 18:49 .
drwxr-xr-x. 11 root root 4096 Apr 23 14:43 ..
-rw-rw-r-- 1 root root 2124 Apr 20 18:48 cn-quick_start.sh
drwxrwxr-x 2 root root 4096 Apr 20 18:48 compose
-rw-rw-r-- 1 root root 4220 Apr 20 18:48 config-example.txt
drwxrwxr-x 8 root root 4096 Apr 20 18:48 config_init
drwxrwxr-x 4 root root 4096 Apr 20 18:48 .github
-rw-rw-r-- 1 root root 173 Apr 20 18:48 .gitignore
-rwxrwxr-x 1 root root 7048 Apr 20 18:48 jmsctl.sh
-rw-rw-r-- 1 root root 35148 Apr 20 18:48 LICENSE
drwxrwxr-x 4 root root 4096 Apr 20 18:48 locale
-rw-rw-r-- 1 root root 1995 Apr 20 18:48 quick_start.sh
-rw-rw-r-- 1 root root 1874 Apr 20 18:48 [README.md](http://readme.md/)
drwxrwxr-x 2 root root 4096 Apr 20 18:48 scripts
-rw-rw-r-- 1 root root 24 Apr 20 18:49 static.env
drwxrwxr-x 2 root root 4096 Apr 20 18:48 utils

[root@pro-login102 14:45:16 jumpserver-installer-v3.2.0]#./jmsctl.sh upgrade
Are you sure you want to update the current version to v3.2.0 ? (y/n) (default y): y

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt [ √ ]
/opt/jumpserver/config/core/config.yml [ √ ]
/opt/jumpserver/config/koko/config.yml [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf [ √ ]
/opt/jumpserver/config/mysql/my.cnf [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf [ √ ]
/opt/jumpserver/config/redis/redis.conf [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt [ √ ]
/opt/jumpserver/config/nginx/cert/server.key [ √ ]
complete

2. Loading Docker Image
[jumpserver/redis:6.2]
6.2: Pulling from jumpserver/redis
Digest: sha256:a6349e1a6a8b317dbd9e196eb3f4c44b304f7fb899e7d2af7b0211112bccd952
Status: Image is up to date for jumpserver/redis:6.2
[docker.io/jumpserver/redis:6.2](http://docker.io/jumpserver/redis:6.2)

[jumpserver/mariadb:10.6]
10.6: Pulling from jumpserver/mariadb
Digest: sha256:455383acf7d0b64ca7ae2d6b620311e41e6d76059fc7e24c2557174cc2959e5f
Status: Image is up to date for jumpserver/mariadb:10.6
[docker.io/jumpserver/mariadb:10.6](http://docker.io/jumpserver/mariadb:10.6)

[jumpserver/core:v3.2.0]
v3.2.0: Pulling from jumpserver/core
26c5c85e47da: Pull complete
9e79879be9c7: Pull complete
bdf2b0f347d4: Pull complete
d65cf2430a1a: Pull complete
a8f1be862cc9: Pull complete
bf1437bfec66: Pull complete
edfca2132a0f: Pull complete
e12e0a1990c3: Pull complete
8a83359fd240: Pull complete
75dc46184a60: Pull complete
ebb5b5d615d7: Pull complete
fe0f7922db3c: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:30fd65bc4bd299c823b02ce35552f983eedb7b6ac32624f6db0659a10164f703
Status: Downloaded newer image for jumpserver/core:v3.2.0
[docker.io/jumpserver/core:v3.2.0](http://docker.io/jumpserver/core:v3.2.0)

[jumpserver/koko:v3.2.0]
v3.2.0: Pulling from jumpserver/koko
26c5c85e47da: Already exists
aba13b81e867: Pull complete
0ad9190e943a: Pull complete
c50861b01129: Pull complete
05c59db2e141: Pull complete
f327755e4bff: Pull complete
8bc9b30c2b34: Pull complete
Digest: sha256:07f6b3e06fbe0edc62f0d93135bc4cb1244355cb26100ea3f7c6b7357022e0bb
Status: Downloaded newer image for jumpserver/koko:v3.2.0
[docker.io/jumpserver/koko:v3.2.0](http://docker.io/jumpserver/koko:v3.2.0)

[jumpserver/lion:v3.2.0]
v3.2.0: Pulling from jumpserver/lion
72a69066d2fe: Already exists
01971ece8edb: Already exists
00efad7f1f86: Already exists
ac262804a75a: Already exists
0688de3fd063: Already exists
2e94ff443643: Already exists
d4b1196ea6e9: Already exists
189920b619e2: Already exists
fb989d125624: Already exists
343d7d255839: Pull complete
4ff13065f157: Pull complete
7ca6cb9324aa: Pull complete
af2a6baf57c5: Pull complete
a28e2c32133e: Pull complete
Digest: sha256:3af3b8d0dfe20b36fc3c5bc00b87b4997461b540082111a5cde966bf0615e217
Status: Downloaded newer image for jumpserver/lion:v3.2.0
[docker.io/jumpserver/lion:v3.2.0](http://docker.io/jumpserver/lion:v3.2.0)

[jumpserver/magnus:v3.2.0]

v3.2.0: Pulling from jumpserver/magnus
26c5c85e47da: Already exists
57cd55bee15c: Pull complete
dd763f468b7c: Pull complete
31c9810389ef: Pull complete
91f2fda8751a: Pull complete
c763f1392e2b: Pull complete
6310690877a0: Pull complete
Digest: sha256:b68370ef8524d139ac5d06d26d7d2f3e932a378e14a5d2b9fbab9baaff4daa34
Status: Downloaded newer image for jumpserver/magnus:v3.2.0
[docker.io/jumpserver/magnus:v3.2.0](http://docker.io/jumpserver/magnus:v3.2.0)

[jumpserver/web:v3.2.0]
v3.2.0: Pulling from jumpserver/web
f1f26f570256: Pull complete
fd03b214f774: Pull complete
ef2fc869b944: Pull complete
ac713a9ef2cc: Pull complete
fd071922d543: Pull complete
2a9f38700bb5: Pull complete
0d31ee5ec6ac: Pull complete
20f41fd7e922: Pull complete
31e6210ed891: Pull complete
834543bf301d: Pull complete
7da8f50c0643: Pull complete
5ee7fa2babed: Pull complete
2403454065d6: Pull complete
4f4fb700ef54: Pull complete
4d4bf2a765cc: Pull complete
fe0ade360716: Pull complete
848509c01d92: Pull complete
d282adbb35d2: Pull complete
1048428bc3a0: Pull complete
1b4b5e693550: Pull complete
Digest: sha256:0eab7dea75825841ac037be40686a1c9d2d8697fa6c7480c8ce6a78a6bff5976
Status: Downloaded newer image for jumpserver/web:v3.2.0
[docker.io/jumpserver/web:v3.2.0](http://docker.io/jumpserver/web:v3.2.0)

complete

3. Backup database
Backing up...
[SUCCESS] Backup succeeded! The backup file has been saved to: /opt/jumpserver/db_backup/jumpserver-v2.28.8-2023-04-23_14:49:50.sql

4. Backup Configuration File
Back up to /opt/jumpserver/db_backup/config-v2.28.8-2023-04-23_14:50:11.conf

5. Apply database changes
Changing database schema may take a while, please wait patiently
[+] Running 2/2
⠿ Container jms_redis Healthy 0.8s
⠿ Container jms_core Started 1.2s
2023-04-23 14:50:19 Collect static files
2023-04-23 14:50:19 Collect static files done
2023-04-23 14:50:19 Check database structure change ...
2023-04-23 14:50:19 Migrate model change to database ...
Operations to perform:
Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
Applying tickets.0019_delete_applyapplicationticket... OK
Applying tickets.0020_auto_20220817_1346...
Start migrate system user to account
- migrate 'ApplyAssetTicket'
- migrate 'ApplyCommandTicket'
- migrate 'ApplyLoginAssetTicket'
OK
Applying tickets.0021_auto_20220921_1814... OK
Applying tickets.0022_alter_applyassetticket_apply_actions... OK
Applying tickets.0023_alter_applyassetticket_apply_actions... OK
Applying tickets.0024_auto_20221121_1800... OK
Applying acls.0004_auto_20220831_1658... OK
Applying acls.0005_auto_20221201_1846... OK
Applying acls.0006_commandfilteracl_commandgroup... OK
Applying acls.0007_auto_20221202_1048... OK
Applying acls.0008_commandgroup_comment... OK
Applying tickets.0025_auto_20221206_1820... OK
Applying assets.0093_auto_20220403_1627... OK
Applying assets.0094_auto_20220402_1736... OK
Applying assets.0095_auto_20220407_1726... OK
Applying assets.0096_auto_20220426_1550... OK
Applying assets.0097_auto_20220426_1558... - Update platform: Windows2016
- Update platform: Other
OK
Applying assets.0098_auto_20220430_2126...

- Set node asset: Node object (0a2fced3-0e67-4ca6-a33f-21ffde18e6fa)
OK
Applying assets.0099_auto_20220711_1409...
Start migrate asset protocols
- Create asset protocols: 0-18 using: 0.00s
OK
Applying accounts.0001_initial... OK
Applying assets.0100_auto_20220711_1413...
Start migrate asset accounts
- Create asset accounts: 0-39 using: 0.06s
- accounts: 57
- histories: 57

Start migrate app accounts

OK

Applying assets.0101_auto_20220811_1511... OK

Applying assets.0102_auto_20220816_1022...

Start migrate command filters to assets

OK

Applying assets.0103_auto_20220902_1021...>>> migrate gateway to asset

>>> migrate gateway to account

OK

Applying assets.0104_auto_20220817_1544... OK

Applying assets.0105_auto_20221220_1956... OK

Applying assets.0106_auto_20221228_1838... OK

Applying assets.0107_automation... OK

Applying assets.0108_alter_platform_charset... OK

Applying accounts.0002_auto_20220616_0021... OK

Applying accounts.0003_automation... OK

Applying accounts.0004_auto_20230106_1507... OK

Applying accounts.0005_alter_changesecretrecord_options... OK

Applying accounts.0006_gatheredaccount... OK

Applying accounts.0007_alter_account_options... OK

Applying accounts.0008_alter_gatheredaccount_options... OK

Applying accounts.0009_account_usernames_to_ids... OK

Applying accounts.0010_gatheraccountsautomation_is_sync_account... OK

Applying acls.0009_auto_20221220_1956... OK

Applying acls.0010_alter_commandfilteracl_command_groups... OK

Applying perms.0029_auto_20220728_1728... OK

Applying perms.0030_auto_20220816_1132... OK

Applying perms.0031_auto_20220816_1600... OK

Applying ops.0022_auto_20220817_1346... OK

Applying applications.0025_auto_20220817_1346... OK

Applying applications.0026_auto_20220817_1716... OK

Applying applications.0027_auto_20221220_1956... OK

Applying assets.0109_alter_asset_options... OK

Applying assets.0110_auto_20230315_1741... OK

Applying assets.0111_auto_20230321_1633... OK

Applying assets.0112_auto_20230404_1631... OK

Applying assets.0113_auto_20230411_1917...

Migrate platform su method: Cisco

Migrate platform su method: H3C

Migrate platform su method: Huawei

OK
Applying assets.0114_baseautomation_params... OK
Applying assets.0115_auto_20230417_1425... OK
Applying assets.0116_auto_20230418_1726... OK
Applying ops.0023_auto_20220912_0021... OK
Applying audits.0016_auto_20221111_1919... OK
Applying audits.0017_auto_20221220_1757... OK
Applying audits.0018_operatelog_resource_id... OK
Applying audits.0019_alter_operatelog_options... OK
Applying audits.0020_auto_20230117_1004... OK
Applying audits.0021_auto_20230207_0857... OK
Applying tickets.0026_auto_20221220_1956... OK
Applying tickets.0027_alter_applycommandticket_apply_run_account... OK
Applying tickets.0028_remove_app_tickets... OK
Applying authentication.0012_auto_20220816_1629... OK
Applying authentication.0013_connectiontoken_protocol... OK
Applying authentication.0014_auto_20221122_2152... OK
Applying authentication.0015_auto_20221205_1136... OK
Applying authentication.0016_auto_20221220_1956... OK
Applying authentication.0017_auto_20230105_1743... OK
Applying authentication.0018_alter_connectiontoken_input_secret... OK
Applying users.0041_auto_20221220_1956... OK
Applying notifications.0003_auto_20221220_1956... OK
Applying notifications.0004_auto_20230201_1614... OK
Applying ops.0024_alter_celerytask_date_last_publish... OK
Applying ops.0025_auto_20230413_1531... OK
Applying orgs.0014_organization_builtin... OK
Applying orgs.0015_auto_20221220_1956... OK
Applying perms.0032_auto_20221111_1919... OK
Applying perms.0033_auto_20221220_1956... OK
Applying rbac.0010_auto_20221220_1956... OK
Applying rbac.0011_remove_redundant_permission... OK
Applying terminal.0054_auto_20221027_1125... OK
Applying terminal.0055_auto_20221228_1804... OK
Applying terminal.0056_auto_20221228_1808... OK
Applying terminal.0057_auto_20230109_1447... OK
Applying terminal.0058_auto_20230110_1445... OK
Applying terminal.0059_session_account_id... OK
Applying terminal.0060_sessionsharing_action_permission... OK
Applying tickets.0029_auto_20230110_1445... OK
Applying users.0042_auto_20230203_1201... OK

After migration, update builtin role permissions
- Update builtin roles

6. Cleanup Image
Do you need to clean up the old version image? (y/n) (default y): y

Untagged: jumpserver/web:v2.28.8
Untagged: jumpserver/web@sha256:c8532ab737babdd9a622e0044df9cf34167ed80d72cf0e57991a150cd3101a6c
Deleted: sha256:11f31ede5d3fa5935182707bc7b0c818a6fc23e6113680d6805bfa3c5c5238bb
Deleted: sha256:ab3383070ac58450951510f423a597095a2fc856a777192994f61609c7ce1801
Deleted: sha256:5e6f5c7208b13ffefd65a3c5f9d3e3a887d6849ed180583475d3f4fd3dba8fae
Deleted: sha256:7baba0c89991630cea576d28d25824c576828955d0b63e2c02a4cc012f6a473d
Deleted: sha256:ac6f8a3fe35c3c3f68d39ad773e55f9e16f22814cdc125ebd05078eef5aee09f
Deleted: sha256:a605e8f6ab36220f7bda1b84f0c58fb933138288379e748fe278bfa5bdbf65fd
Deleted: sha256:e32df7db82275a14619552fc76fd2eba17634122448f761600bd80b36eafa4b5
Deleted: sha256:b3ccda4c0994a86958aeb5bf14a01f26066866c361dc99645f3b8e4f52cfcc64
Deleted: sha256:13f8b09fa1be04bd13d4690745b43fd7667e77001466ba9cff336ef62a5b75d0
Deleted: sha256:709dd1a6395b197cc8c5f3f1fe2614d77200c028732991e841bb8f9578d0c510
Deleted: sha256:4cf1662319acdc5b0f3bf43fc47672ab5f8f82c3c69c71fa93aa192d81e32731
Deleted: sha256:68b342c6dd49886a4ee9ef83de0b84c14cb58bf899419a37a21eb36be8681bf1
Untagged: jumpserver/core:v2.28.8
Untagged: jumpserver/core@sha256:6bdddc4df061027aedc54374694ddf8e4657f6fb18fe1f8b8d0757f8b84f8860
Deleted: sha256:f76a932d5f6076481236f0f67d7bf074580a5a28f9356ba4d98534c09d4ffe68
Deleted: sha256:91de447e04f0ad4a9aa748d3f11bf6d304071fb6355c10297d63c25533f553b4
Deleted: sha256:0ba4844acbe36d84e128a36013b25b90d9c94a93d85e177239fcbdf28815fd93
Deleted: sha256:584eb335b6b4c55c05a23dc0b7045f757a5fe8a8001125ea2f842dccb7b8e676
Deleted: sha256:def541a28b743c6c6500c7a9f1850eca0c0c648a421d12ef85ed1ef599c8c937
Deleted: sha256:505813ec08c4aae3f69152eab3465ba9f3c9afcbb9d593befbe781077aede8e5
Deleted: sha256:72be29a72c3bd558e9edf79897ca0e0cfd88487e15e396ccdc7cfffb546edcfc
Deleted: sha256:27b79cb16b9e7e283a7afc152f9d797d337e575be55b0c0c8209700f6e3572a0
Deleted: sha256:fb237cf0bb7c7f3aca3a805480e0debad378424c0cac240d7e366bd10401af8f
Deleted: sha256:24ddeb7ddf5e71568cad91f8cb96873bd1eafb98165d71bfdbec8050dd43ebfa
Deleted: sha256:4523329f47540baf9ee4982dfba970219abf272c66de4e088d3b5b634e9246d8
Deleted: sha256:5d36c702cbf88643faa56f2cafeed42c28816f5f450f05c8921cf6171659f1cf
Deleted: sha256:8706a70a66e22f89929936d88ae15ce0c078b8b586a72e782618e98b02956f8f
Untagged: jumpserver/koko:v2.28.8
Untagged: jumpserver/koko@sha256:6e575937c4aa244b59267f1c5d05c6b1716ecc0d8b8a1a313b2fc02457846b0b
Deleted: sha256:d7f378b7b4b2cd93d9d65de77d8a3bac4511f736c270ae8e67b201f7aae185b1
Deleted: sha256:9352c306f29323e66c5c393ea9997738b4cbbcbbb72db0d18438301782a5e3a3
Deleted: sha256:0df466c49bf9df9570746398ff40d9d2f1b6480b507b114e8e2686720a9fb6de
Deleted: sha256:5de17d6ccf4f57b2d4faf99835cee73a0350123010e42d38231ac6947567fd23
Deleted: sha256:e9badb8f6a21797a79616db871472db0aa1a1d54bc92b540b75397f2ec8f4553
Deleted: sha256:bf2301191ccf0e5d900eb1c3e75c8eb55b6446a432d587db892e9f9ac4d5f51d
Deleted: sha256:38fd7adfe198a1bdd159dbd58d764a1b0086c4e46cf3a02c753ac0b35effd1da
Deleted: sha256:07cf5a233d8ef29e87a252b76c3097cd160a90e2dfe8da0f53abe60798c83f1f
Untagged: jumpserver/lion:v2.28.8
Untagged: jumpserver/lion@sha256:364f2f10f2adeb7c92efe6a53707765e3fa83d8691a1129f044465f1fde91348
Deleted: sha256:e0c02802f9df613def33805976deca6ddaa5dc293e07bdfc1fce58cc7d49798a
Deleted: sha256:08ca858682f26aa70e3099508589404c088873b38c311e2e8ec5456e2626dfbb
Deleted: sha256:734f2b74c8ca9a75b10afa35e2bc7b2d4c274920d414d144df3dd5627cf76187
Deleted: sha256:362e4892dc9d7dbb5aeabc82b17a5724d912ffac675dbf17c39d5322539e4da3
Deleted: sha256:e304c0548c45b4bd7a7bb24867f07b88c1f93d72c47eb9277a531e9fbbd1fac4
Deleted: sha256:06ba1f44f1e8ddd51eaa3cfff7a6a37859ac482bc3dda94dcde7b0e8da59483f
Untagged: jumpserver/magnus:v2.28.8
Untagged: jumpserver/magnus@sha256:946e79512c066ae399e645a7fbb01b8fe5b510fb1a89035e96dd36fdacd678b8
Deleted: sha256:dd7712d227f571ff0684bc74f05b3adf3704a71b47f22c0e2479c0736ee28422
Deleted: sha256:02d8a06a8d50b24e2a716ed4f93c8499f4fda937b130625b6f0dc82875b83a01
Deleted: sha256:0488f128d7405dcc7efcab3ceb3fc0cf840eb7847ba189bdb28ca1170711a551
Deleted: sha256:6bf3e7ec3414eb0b85af7236cb24967c23b6c713a16236a0d2b931f0c70891e8
Deleted: sha256:344405862361adebcdbb48efee4545c6d87e528334e4ce22ac28fc1fdd080257
Deleted: sha256:1c549d283f9f4240a97f538c6a5107dac7c95d89e0923de7ae8b19e14c3969f4
Deleted: sha256:6bb9ede5a07fb827461be80ce22248c37a0d75ea0162bfdca7c77bd07da61c4d
Deleted: sha256:650abce4b096b06ac8bec2046d821d66d801af34f1f1d4c5e272ad030c7873db

7. Upgrade Docker
Docker version 20.10.22, build 3a2c30b --> Docker version 23.0.4
Do you need upgrade Docker binaries? (y/n) (default n): yy^H^Hyy^H^H^[[3~^H^H    （这里误输入，最后回车了）

Docker Compose version v2.14.2 --> Docker Compose version v2.17.2
Do you need upgrade Docker Compose? (y/n) (default n):

8. Upgrade successfully. You can now restart the program
cd /opt/jumpserver-installer-v3.2.0
./jmsctl.sh start

[root@pro-login102 14:53:25 jumpserver-installer-v3.2.0]#./jmsctl.sh start

[+] Running 7/7

⠿ Container jms_redis Healthy 0.8s

⠿ Container jms_core Healthy 26.7s

⠿ Container jms_lion Started 28.2s

⠿ Container jms_magnus Started 28.9s

⠿ Container jms_web Started 29.4s

⠿ Container jms_celery Started 28.1s

⠿ Container jms_koko Started

**Comment by brucegogo** [comment]
我又重新执行了upgrade命令一次，结果还是成功，但是问题还是一样的，没有变化：

[root@pro-login102 16:09:55 jumpserver-installer-v3.2.0]#./jmsctl.sh stop
[+] Running 1/1
 ⠿ Container jms_core  Stopped                                                                                                                                                                                                       0.9s
[+] Running 1/1
 ⠿ Container jms_koko  Stopped                                                                                                                                                                                                      10.2s
[+] Running 1/1
 ⠿ Container jms_lion  Stopped                                                                                                                                                                                                      10.2s
[+] Running 1/1
 ⠿ Container jms_magnus  Stopped                                                                                                                                                                                                    10.3s
[+] Running 1/1
 ⠿ Container jms_web  Stopped                                                                                                                                                                                                        1.0s
[+] Running 1/1
 ⠿ Container jms_celery  Stopped                                                                                                                                                                                                     0.3s
[+] Running 1/1
 ⠿ Container jms_core  Removed 0.2ss
[+] Running 1/0
 ⠿ Container jms_koko  Removed 0.0s
[+] Running 1/0
 ⠿ Container jms_lion  Removed 0.0s
[+] Running 1/0
 ⠿ Container jms_magnus  Removed 0.0s
[+] Running 1/0
 ⠿ Container jms_web  Removed 0.0s
[+] Running 1/1
 ⠿ Container jms_celery  Removed 0.7ss

[root@pro-login102 16:11:13 jumpserver-installer-v3.2.0]#./jmsctl.sh upgrade
Are you sure you want to update the current version to v3.2.0 ? (y/n)  (default y): y

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/core/config.yml   [ √ ]
/opt/jumpserver/config/koko/config.yml   [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]
complete

2. Loading Docker Image
[jumpserver/redis:6.2]
6.2: Pulling from jumpserver/redis
Digest: sha256:a6349e1a6a8b317dbd9e196eb3f4c44b304f7fb899e7d2af7b0211112bccd952
Status: Image is up to date for jumpserver/redis:6.2
docker.io/jumpserver/redis:6.2

[jumpserver/mariadb:10.6]
10.6: Pulling from jumpserver/mariadb
Digest: sha256:455383acf7d0b64ca7ae2d6b620311e41e6d76059fc7e24c2557174cc2959e5f
Status: Image is up to date for jumpserver/mariadb:10.6
docker.io/jumpserver/mariadb:10.6

[jumpserver/core:v3.2.0]
v3.2.0: Pulling from jumpserver/core
Digest: sha256:30fd65bc4bd299c823b02ce35552f983eedb7b6ac32624f6db0659a10164f703
Status: Image is up to date for jumpserver/core:v3.2.0
docker.io/jumpserver/core:v3.2.0

[jumpserver/koko:v3.2.0]
v3.2.0: Pulling from jumpserver/koko
Digest: sha256:07f6b3e06fbe0edc62f0d93135bc4cb1244355cb26100ea3f7c6b7357022e0bb
Status: Image is up to date for jumpserver/koko:v3.2.0
docker.io/jumpserver/koko:v3.2.0

[jumpserver/lion:v3.2.0]
v3.2.0: Pulling from jumpserver/lion
Digest: sha256:3af3b8d0dfe20b36fc3c5bc00b87b4997461b540082111a5cde966bf0615e217
Status: Image is up to date for jumpserver/lion:v3.2.0
docker.io/jumpserver/lion:v3.2.0

[jumpserver/magnus:v3.2.0]
v3.2.0: Pulling from jumpserver/magnus
Digest: sha256:b68370ef8524d139ac5d06d26d7d2f3e932a378e14a5d2b9fbab9baaff4daa34
Status: Image is up to date for jumpserver/magnus:v3.2.0
docker.io/jumpserver/magnus:v3.2.0

[jumpserver/web:v3.2.0]
v3.2.0: Pulling from jumpserver/web
Digest: sha256:0eab7dea75825841ac037be40686a1c9d2d8697fa6c7480c8ce6a78a6bff5976
Status: Image is up to date for jumpserver/web:v3.2.0
docker.io/jumpserver/web:v3.2.0

complete

3. Backup database
Backing up...
[SUCCESS] Backup succeeded! The backup file has been saved to: /opt/jumpserver/db_backup/jumpserver-v3.2.0-2023-04-23_16:11:47.sql

4. Backup Configuration File
Back up to /opt/jumpserver/db_backup/config-v3.2.0-2023-04-23_16:11:56.conf

5. Apply database changes
Changing database schema may take a while, please wait patiently
[+] Running 2/2
 ⠿ Container jms_redis  Healthy                                                                                                                                                                                                      2.6s
 ⠿ Container jms_core   Started                                                                                                                                                                                                      3.0s
2023-04-23 16:12:06 Collect static files
2023-04-23 16:12:07 Collect static files done
2023-04-23 16:12:07 Check database structure change ...
2023-04-23 16:12:07 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
  Your models in app(s): 'assets' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

After migration, update builtin role permissions
  - Update builtin roles

6. Cleanup Image


7. Upgrade Docker
Docker version 20.10.22, build 3a2c30b --> Docker version 23.0.4
Do you need upgrade Docker binaries? (y/n)  (default n): y

[+] Running 2/2
 ⠿ Container jms_redis  Removed                                                                                                                                                                                                      0.2s
 ⠿ Network jms_net      Removed                                                                                                                                                                                                      0.1s

d2ee36bf614d2104e72d612e5df39983
Starting to download Docker engine ...

Docker Compose version v2.14.2 --> Docker Compose version v2.17.2
Do you need upgrade Docker Compose? (y/n)  (default n): y

e6739efadaf75e91b59f0888859697e9
Starting to download Docker Compose binary ...
complete

8. Upgrade successfully. You can now restart the program
cd /opt/jumpserver-installer-v3.2.0
./jmsctl.sh start


[root@pro-login102 16:14:59 jumpserver-installer-v3.2.0]#./jmsctl.sh start
[+] Running 8/8
 ✔ Network jms_net       Created                                                                                                                                                                                                     0.1s 
 ✔ Container jms_redis   Healthy                                                                                                                                                                                                    11.9s 
 ✔ Container jms_core    Healthy                                                                                                                                                                                                    37.9s 
 ✔ Container jms_koko    Started                                                                                                                                                                                                    39.7s 
 ✔ Container jms_magnus  Started                                                                                                                                                                                                    39.8s 
 ✔ Container jms_web     Started                                                                                                                                                                                                    40.1s 
 ✔ Container jms_lion    Started                                                                                                                                                                                                    40.1s 
 ✔ Container jms_celery  Started

**Comment by wojiushixiaobai** [comment]
清理浏览器缓存，有缓存导致的。

**Comment by brucegogo** [comment]
哇，确实如此！
非常感谢！

**Comment by brucegogo** [comment]
哇，确实如此！
非常感谢！
