### ISSUE TITLE
[Bug] 全新安装2.28.12远程桌面字体平滑不生效

### ISSUE THREAD

**Issue by actck** [jumpserver/jumpserver#10312]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
2.28.12

**浏览器版本**
chrome

**Bug 描述**
全新centos7.9，全新默认安装2.28.12，远程桌面字体平滑不生效，配置文件中看到默认有配置：JUMPSERVER_ENABLE_FONT_SMOOTHING=True，将“True”改为“true”之后，重启服务，平滑生效，不确定是否大小写问题

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.3 版本中会优化，后端默认生效值是 true，后端没有做处理，所以 True 不生效。

https://github.com/jumpserver/installer/pull/312
