### ISSUE TITLE
[Bug] 远程应用发布部署出现异常导致中断

### ISSUE THREAD

**Issue by Jackie-Pan** [jumpserver/jumpserver#10317]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.1

**浏览器版本**
Microsoft Edge
版本 112.0.1722.48 (正式版本) (64 位)

**Bug 描述**
远程应用发布部署异常中断
![image](https://user-images.githubusercontent.com/52104725/233829015-bbe0cf63-83e1-4bcf-9182-e87e1628a10c.png)

针对报错的信息中URL http://localhost:6068/api/health/  ，测试端口未使用，链接无效
又去除了端口测试了一下http://localhost/api/health/，有返回值，{"status":true,"db_status":true,"db_time":0.0026602745056152344,"redis_status":true,"redis_time":0.0017790794372558594,"time":1682238973}

我不确定是否是因为这个导致异常不能继续部署的。

**Comment by wojiushixiaobai** [comment]
等待后续优化，你可以手动到 windows 服务器上把 tinkerd  启动
```powershell
tinkerd service start
```

**Comment by Jackie-Pan** [comment]
![image](https://user-images.githubusercontent.com/52104725/233903408-4acbc80b-f6eb-4f27-bd19-d4a23c5cff90.png)
服务无法启动，查看Windows日志
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2023-04-24T04:42:23.146417700Z" /> 
  <EventRecordID>811</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="684" ThreadID="5140" /> 
  <Channel>System</Channel> 
  <Computer>WIN-U0O2GKHEUM5</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="param1">JumpServer Tinker Service</Data> 
  <Data Name="param2">13</Data> 
  <Binary>4A0075006D0070005300650072007600650072002000540069006E006B00650072000000</Binary> 
  </EventData>
  </Event>

> 等待后续优化，你可以手动到 Windows 服务器上把 tinkerd 启动
> 
> ```powershell
> tinkerd service start
> ```

**Comment by BaiJiangJie** [comment]
1. 检查一下发布机的 `Core 服务地址` 有没有正确填写？
 
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/32935519/233964984-c074b52a-db70-4308-b42b-3ba467b999f7.png">

2. 打开「终端注册」功能。

![image](https://user-images.githubusercontent.com/32935519/233965325-fd869486-dd39-4ae6-a663-9bd1bcf00c84.png)

3. 查看 Tinker 日志并手动执行测试

#远程应用发布机进入 CMD 控制台

```
cd C:\Users\Administrator\AppData\Local\Programs\Tinker
./tinkerd
```

4. 在执行 Wait Tinker api health 阶段时确认远程应用发布机 Tinker 服务正常，且端口正常监听
![image](https://user-images.githubusercontent.com/32935519/233965711-db5fc8d9-21ec-4a1f-b1fe-681be82f8973.png)

**Comment by Jackie-Pan** [comment]
不知道怎么回事，Tinker Service自己运行起来了，然后部署也就可以正常完成了
