### ISSUE TITLE
管理员不能重置本身的MFA

### ISSUE THREAD

**Issue by BruceChinese** [jumpserver/jumpserver#10315]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.2.1
**浏览器版本**
版本 112.0.5615.121

**Bug 描述**

管理员不能重置本身的MFA,如果要是MFA忘记了,可以通过https://docs.jumpserver.org/zh/v3/guide/system/authentication/mfa/#3-mfa来重置MFA进来,然后从管理员的个人信息里设置多因子验证点击设置, 点击启用MFA, 点击重置按钮,会出现让输入MFA码的窗口,这样反复的就是一个死循环, 麻烦以目前的版本,可以从哪里重置MFA的码 
![image](https://user-images.githubusercontent.com/12492229/233828521-909fbe11-dbdd-4cd8-8d4d-8c8ae60561cd.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wojiushixiaobai** [comment]
你可以使用其他管理员或者控制台给自己重置密码，管理员可以给其他人重置 MFA，但是不可以给自己重置。
