### ISSUE TITLE
[Bug] 配置邮箱使用tls 显示unsupported protocol (_ssl.c:1129)

### ISSUE THREAD

**Issue by shuinoo** [jumpserver/jumpserver#10314]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1

**浏览器版本**
chrome  111.0.5563.111

**Bug 描述**
配置邮箱使用tls 显示unsupported protocol (_ssl.c:1129)

**Bug 重现步骤(有截图更好)**
1. 使用官方文档快速安装jumpserver 
2. 进入配置邮箱使用tls 协议，测试邮箱提示[email ERROR] [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)
![image](https://user-images.githubusercontent.com/38451598/233824523-80a547c6-243f-480b-a11c-040c7725d28f.png)

4.
![image](https://user-images.githubusercontent.com/38451598/233824539-6aee3dde-2fd8-4f03-b0aa-fb3b848e3b8d.png)

5. 错误截图如下：
![image](https://user-images.githubusercontent.com/38451598/233824564-063d576e-c2fb-4d5f-8526-a3aec6f0a542.png)

**Comment by wojiushixiaobai** [comment]
确定你的邮箱支持该协议

**Comment by shuinoo** [comment]
确定我的邮箱支持tls
![image](https://user-images.githubusercontent.com/38451598/233888408-ab3d2167-b544-45eb-9c95-e6cc949687ee.png)

**Comment by shuinoo** [comment]
使用163的授权码登录，
![image](https://user-images.githubusercontent.com/38451598/233893124-1a2c1b34-cf55-48c7-93cd-81989f224d0c.png)
提示
![image](https://user-images.githubusercontent.com/38451598/233893237-a13fd5f8-1c3e-4147-882e-87aa275d5e94.png)
在安卓手机
![1682306743690](https://user-images.githubusercontent.com/38451598/233893467-02e677f7-3007-41d4-b44a-d05240da9c9f.jpg)

**Comment by wojiushixiaobai** [comment]
163.com 的测试是账号密码不对，请重新检查。

**Comment by shuinoo** [comment]
麻烦说明第一个问题需要提供的截图，以及处理的方法

**Comment by BaiJiangJie** [comment]
`进入配置邮箱使用tls 协议，测试邮箱提示[email ERROR] [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1129)`

切换成 SSL 试一下呢？@shuinoo
