### ISSUE TITLE
[Bug] 2222存在加密套件漏洞

### ISSUE THREAD

**Issue by MrCat1016** [jumpserver/jumpserver#10310]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v.2.28.6

**浏览器版本**
Chrome Version 112.0.5615.138

**Bug 描述**
Nexpose扫描发现漏洞如下：
![image](https://user-images.githubusercontent.com/131500720/233753263-188f272b-58f6-4e71-9040-f20e969c9f9f.png)

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/131500720/233753269-d2ee6630-3f17-449c-9873-25233898ddd6.png)

**Comment by BaiJiangJie** [comment]
@wojiushixiaobai 看一下；

**Comment by MrCat1016** [comment]
感谢各位大佬~
