### ISSUE TITLE
回放vi编辑状态显示问题

### ISSUE THREAD

**Issue by tsdcz** [jumpserver/jumpserver#1031]
[简述你的问题]

回放中，当vi编辑内容时，显示不正常

##### 使用版本
0.5.0-2

##### 问题复现步骤
使用vi编辑一个文件，然后通过回放看

##### 具体表现[截图可能会更好些,最好能截全]
下图是正常的状态
![image](https://user-images.githubusercontent.com/36932386/36814991-453e28ca-1d14-11e8-83bf-f75bfbc90e97.png)

============我是分割线=============
下图是回放显示的状态
![image](https://user-images.githubusercontent.com/36932386/36815001-4d9ef062-1d14-11e8-8daf-6805a637118f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
最大化播放试试

**Comment by wojiushixiaobai** [comment]
@ibuler 老哥，窗口最大化正常，默认窗口有个别中文乱码，而且汉字的间距也有点问题。

**Comment by ibuler** [comment]
距离问题应该和系统有关，其他的一些中文没有问题
