### ISSUE TITLE
[Question] 为什么根据教程一步一步在线安装，会出现断网的现象

### ISSUE THREAD

**Issue by jxyk2007** [jumpserver/jumpserver#10319]
**请描述您的问题.**
为什么根据教程一步一步在线安装，会出现断网的现象。
一键自动部署的，出现断网，在同一局域网内，服务器也可以ping通网关，其他ip就不行，都不能ping通，uninstall卸载掉 又会恢复网络

**Comment by wojiushixiaobai** [comment]
docker 网段和本地网段冲突，你检查下。
jumpserver 默认使用了 192.168.251.1/24 这个网段，你可以在配置文件里面自行修改。

- /opt/jumpserver/config/config.txt

**Comment by Howard9414** [comment]
> docker 网段和本地网段冲突，你检查下。 jumpserver 默认使用了 192.168.251.1/24 这个网段，你可以在配置文件里面自行修改。
> 
> * /opt/jumpserver/config/config.txt
想问下要怎么修改安装位置嘛？本地没法用root安装
