### ISSUE TITLE
[Bug] 使用终端进行sftp登录时，ls -l命令显示用户id而不显示用户名

### ISSUE THREAD

**Issue by qinsiqs** [jumpserver/jumpserver#10311]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
利用koko模块的功能
![57a19f0b754db89e32affbad752b26b](https://user-images.githubusercontent.com/48946147/233782109-892d461d-fc68-42a0-bec7-80939486a9d4.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
提供一下不通过 koko 连接时展示的信息；

**Comment by qinsiqs** [comment]
![image](https://user-images.githubusercontent.com/48946147/236676176-035b10a7-6693-449a-93f4-49db32aa11f9.png)
不用koko的sftp登录时，ls -l命令可以展示文件用户名，而不是用户id

**Comment by BaiJiangJie** [comment]
目前我们 SFTP 获取不到文件的用户名，@LeeEirc 再确认一下，现在是否可以获取到？

**Comment by LeeEirc** [comment]
参考 https://github.com/pkg/sftp/issues/530，暂无 metadata 相关信息。
