### ISSUE TITLE
[Bug] 无法修改任何平台配置

### ISSUE THREAD

**Issue by 7980963** [jumpserver/jumpserver#10326]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
产品:	JumpServer 社区版 GPLv3
版本:	v3.2.1

**Bug 描述**
无法修改任何平台配置

**Bug 重现步骤(有截图更好)**
控制台-资产列表-某LINUX资产-更新-SSH协议设置-修改SFTP home，提示
继承自平台配置，如需更改，请更改平台中的配置 
[查看](https://xxx.xxx/ui/#/console/assets/platforms/1)
https://xxx.xxx/ui/#/console/assets/platforms/1
跳转-SSH协议设置-修改SFTP home，提示
继承自平台配置，如需更改，请更改平台中的配置 
[查看](https://xxx.xxx/ui/#/console/assets/platforms/undefined)
https://xxx.xxx/ui/#/console/assets/platforms/undefined
然后。。。。
系统平台对象不存在

**Comment by BaiJiangJie** [comment]
问题回复：

1. 内置类型的平台不允许修改；

2. 如果要修改，需要手动创建一个平台，和资产进行关联；

3. 平台中的协议设置显示`查看`的提示语有问题；（v3.3 会优化）
