### ISSUE TITLE
[Bug] web终端 手动输入密码连接后，下次连接会保存

### ISSUE THREAD

**Issue by MinLi2** [jumpserver/jumpserver#10325]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.0

**浏览器版本**
Microsoft Edge 112.0.1722.58
**Bug 描述**
 web终端 手动输入密码连接后，下次连接会保存

**Bug 重现步骤(有截图更好)**
视频演示如下
https://www.bilibili.com/video/BV1rP411U7yy/

**Comment by BaiJiangJie** [comment]
`https://www.bilibili.com/video/BV1rP411U7yy/`

<img width="994" alt="image" src="https://user-images.githubusercontent.com/32935519/233958506-9e373dd7-466e-4212-964d-92a16f4a10b0.png">

**Comment by BaiJiangJie** [comment]
`web终端 手动输入密码连接后，下次连接会保存`

浏览器的设置吧

**Comment by linfnaa** [comment]
我得也有这个问题，第二次打开密码就在哪里了，浏览器没有设置自动保存密码

**Comment by saszhuqing** [comment]
和浏览器无关，未允许浏览器保存密码，但手动输入后，确实就自动保存在输入框那里了，第二次无需输入即可直接连接。
版本：v3.2.1

**Comment by jym503558564** [comment]
可升级至新版本进行测试，新版本测试，无该问题。
