### ISSUE TITLE
[Bug] Unable to resolve IDP settings. Please contact your administrator to check system settings,or login using other methods.

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#10324]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
升级版本后不能使用SAML认证，之前该功能是免费版的，不知道什么时候变成企业版了。不知道是不是这个原因

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by OldTT** [comment]
请问你关闭的这个问题是怎么处理的？我现在使用Authentik 的 saml2.0的方式连接jumpserver也出现了这个错误，版本是v2.28.8。我使用自建证书，然后导出jumpserver的Meta文件，然后导入到Authentik自动生成配置，随后将Authentik 的MetadataURL写入到jumpserver的IDP metadata URL。然后创建一个应用程序进行测试，就报你现在这个错误了，想请教一下你是如何解决的
