### ISSUE TITLE
[Bug] 在资产列表 选择部分资产选择 更多操作->批量删除后，大概率会把节点下所有资产删除

### ISSUE THREAD

**Issue by helfee** [jumpserver/jumpserver#10323]
JumpServer 社区版 GPLv3
版本:	v3.2.1

**浏览器版本**
Microsoft Edge
版本 112.0.1722.48 (正式版本) (64 位)

**Bug 描述**
在资产列表 选择部分资产选择 更多操作->批量删除后，大概率会把节点下所有资产删除
出现好几次

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
没有复现出来，最好可以提供一个复现环境？@helfee

**Comment by helfee** [comment]
已经找到原因，禁用浏览器插件 uBlock Origin 之后就正常

**Comment by BaiJiangJie** [comment]
好的。
