### ISSUE TITLE
[Question] Audit > Session audit > Commands  风险等级问题 (risk level)

### ISSUE THREAD

**Issue by shlee4** [jumpserver/jumpserver#10320]
**请描述您的问题.**
你好。我有个问题。

Risk level（Ordinary, Dangerous)的分类标准是什么？

**Comment by wojiushixiaobai** [comment]
拦截的命令属于 `Dangerous`
非拦截的命令属于 `Ordinary`

**Comment by shlee4** [comment]
Hello.
Thanks, but I don't think that I understand your answer.
I understand that '非拦截的命令属于" (Ordinary) means ls, cd, tail -f,  pwd, vi, mv, cp command ... etc ,
and then "拦截的命令属于" (dangerous) means ......?

**Comment by BaiJiangJie** [comment]
No no.

Command filtering can be configured in rights management. There are action options in the command filtering rules. If your command is rejected, it will be marked as `Dangerous` when recording the command.

权限管理中可以配置命令过滤规则，命令过滤规则中有动作选项，如果你的命令属于拒绝，那么在记录命令的时候会标记为危险（Dangerous）。

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/32935519/234202047-7592e327-e8bb-46f1-883c-6680eb54103a.png">

**Comment by shlee4** [comment]
Hello.
I understand how the Command Filtering works.

Thank you.
