### ISSUE TITLE
[Question] 集群模式部署下审核人地址为127.0.0.1，无法跳转

### ISSUE THREAD

**Issue by 1104008306** [jumpserver/jumpserver#10329]
**请描述您的问题.**
集群部署时，审核人的地址为私有地址
http://127.0.0.1/ui/#/tickets/tickets/1127f768-5a5b-4393-a95b-917a957cea02?type=command_confirm
![image](https://user-images.githubusercontent.com/23133728/233944797-07967857-43f7-41c2-9581-aeb4dd1cd78b.png)
修改配置文件config.txt
![image](https://user-images.githubusercontent.com/23133728/233946066-bf601b13-5872-440e-8b22-89ab7d19574e.png)
lion和koko组件容器报错，提示
![image](https://user-images.githubusercontent.com/23133728/233945773-3626ee8f-1333-465c-9695-ba9d144e29e6.png)
发现所有集群jms_core 端口并未对外发布，该如何操作呢？求告知
![image](https://user-images.githubusercontent.com/23133728/233946442-ecc1faa7-bdfd-4761-bff1-670685eb71e2.png)

**Comment by BaiJiangJie** [comment]
`系统设置` - `基本设置` 修改 `当前站点URL`；

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/32935519/233958150-3f6502bc-f743-4849-ab64-a63a382e8df0.png">

**Comment by 1104008306** [comment]
好的，感谢。
