### ISSUE TITLE
推送账号时提示没有需要执行的任务[Bug] 

### ISSUE THREAD

**Issue by jonys1994** [jumpserver/jumpserver#10322]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.1

**浏览器版本**
edge 107.0.1418.42

**Bug 描述**
推送账号时提示没有需要执行的任务

**Bug 重现步骤(有截图更好)**
1. 新建资产，关联账号模板
2. 进入资产-账号列表-选择账号（进入）
3. 推送账号，返回提示
4. 
![image](https://user-images.githubusercontent.com/17492409/233885900-5b2d553f-ed0e-46db-a8a4-199ea363d47c.png)

**Comment by jonys1994** [comment]
另外，有时在执行账号推送任务时（多台服务器）也会出现此提示

**Comment by jonys1994** [comment]
升级至3.1.2版本依然如此，是我使用姿势的问题嘛？

**Comment by BaiJiangJie** [comment]
确认一下，资产下有几个账号？
如果只有一个，会出现日志中的提示。

因为在 <= v3.2  的版本中都不支持自己推送自己；

比如账号下只有 root 用户，不会生成推送任务；

**Comment by jonys1994** [comment]
> 确认一下，资产下有几个账号？ 如果只有一个，会出现日志中的提示。
> 
> 因为在 <= v3.2 的版本中都不支持自己推送自己；
> 
> 比如账号下只有 root 用户，不会生成推送任务；

抱歉，我说错了，之前版本升级到了3.2.1，不是3.1.2，3.2.1版本按我前面描述的操作去推送特权用户时会提示“没有需要执行的任务”，把“特权用户”关掉推送就可以
资产下共三个账号，一个root用户，一个admin用户和一个readonly用户

**Comment by BaiJiangJie** [comment]
v3.2 版本我测试没问题啊

**Comment by BaiJiangJie** [comment]
在后端处理逻辑中，会选择使用哪个账号进行推送，优先级会按照，特权用户 > 最近更新的账号 > 其他账号，进行优选选择；

在你的问题中，如果要推送admin，那可以手动更新一下root账号（比如修改一下名称），这样最后更新时间 root > admin，再推送 admin 时，会使用 root 机械能推送；

**Comment by BaiJiangJie** [comment]
其实出现这个问题的原因是在 <= v3.2 版本中不支持账号自己推送自己；

在 v3.3 版本中计划优化一下处理逻辑，支持账号自推送；

**Comment by jonys1994** [comment]
> 其实出现这个问题的原因是在 <= v3.2 版本中不支持账号自己推送自己；
> 
> 在 v3.3 版本中计划优化一下处理逻辑，支持账号自推送；

好的，谢谢您耐心解答！

**Comment by BaiJiangJie** [comment]
已经提交在了 dev 分支，后续关注 v3.3 版本的正式发布就可以了。

https://github.com/jumpserver/jumpserver/pull/10349/files#diff-4e1966cd2b08ee15593ee8b98bfe98fa1fea35315700000ec8db482ca0ab57aeR75

**Comment by jonys1994** [comment]
> 已经提交在了 dev 分支，后续关注 v3.3 版本的正式发布就可以了。
> 
> https://github.com/jumpserver/jumpserver/pull/10349/files#diff-4e1966cd2b08ee15593ee8b98bfe98fa1fea35315700000ec8db482ca0ab57aeR75

好的谢谢！

**Comment by jonys1994** [comment]
再请教下，这个问题和【账号管理-账号推送】中，新建推送任务，推送【特权用户】时提示“没有需要执行的任务”，是一个问题吧？
