### ISSUE TITLE
[Question] 审计查看在线会话抛出异常

### ISSUE THREAD

**Issue by 1104008306** [jumpserver/jumpserver#10330]
**请描述您的问题.**
2台jumpserver节点，集群模式部署，查看在线会话会提示异常。
![image](https://user-images.githubusercontent.com/23133728/234152505-982ca8e7-f48b-4e40-b820-c0ce3819fb22.png)

通过登录到某一台，才能够进行正常查看在线会话。

**Comment by 1104008306** [comment]
单独访问某一台节点IP，而非HAproxy地址才能够在线审计

**Comment by wojiushixiaobai** [comment]
redis 共享 session 信息才行。
```
SHARE_ROOM_TYPE=redis
```

**Comment by 1104008306** [comment]
是我配置文件写错，感谢。
祝贵团队越做越好！
