### ISSUE TITLE
[Bug] mysql连接，使用客户端的方式，dbeaver报Unknown system variable 'transaction_isolation'，无法连接

### ISSUE THREAD

**Issue by mmy83** [jumpserver/jumpserver#10332]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.2.0

**浏览器版本**
chrome 112.0.5615.49

**Bug 描述**
使用dbeaver 版本: 23.0.3.202304240630 连接mysql 5.6.51，选择客户端方式连接，报Unknown system variable 'transaction_isolation'错误，经过测试，不通过jumpserver连接是没有任何问题的，而且使用客户端里面的命令行也是没问题的，且dbeaver里面选择的是mysql5。

**Bug 重现步骤(有截图更好)**
1、首先确认不经过jumpserver没有任何问题，可以连接，不管是命令行还是dbeaver客户端。
2、dbserver里面选择mysql5（选mysql也不行），填写jumpserver提供的连接信息，报Unknown system variable 'transaction_isolation'
3、查看dbserver中mysql5 的mysql-connector-java.jar版本为5.1.44，经测试报报Unknown system variable 'transaction_isolation'，但不经过jumpserver可以正常
4、换mysql-connector-java.jar为5.1.10，经测试正常，且不经过jumpserver也正常

**Comment by BaiJiangJie** [comment]
好的，我们尝试复现一下。

**Comment by BaiJiangJie** [comment]
确实是这样的，v5.1.10 可以，v5.1.44 不行（JumpServer 不支持）；

**Comment by mmy83** [comment]
会修复吗？

**Comment by BaiJiangJie** [comment]
不考虑修复了，你切换一下 jdbc 的版本吧。

**Comment by mmy83** [comment]
不修复了？新版本dbeaver下的都是5.1.44吧，大家都换呀！而且有些工具是不能换的吧，不过没测过都哪些不能用。

**Comment by mmy83** [comment]
有些工具是不能切换的吧

**Comment by BaiJiangJie** [comment]
常用的功能一般都支持

**Comment by mmy83** [comment]
没有别的解决方案吗？我们这边数据库有5.6,5.7,8.0，来回切换太麻烦了
