### ISSUE TITLE
[Bug] 上传文件到堡垒机虚拟盘符Guacamole后，系统导数据直接使用Guacamole里的数据文件，导致IIS报错，服务器自动重启

### ISSUE THREAD

**Issue by ZionLoh90** [jumpserver/jumpserver#10331]
**JumpServer 版本( v3.1.0 )**

**浏览器版本：112.0.5615.87**

**上传文件到堡垒机虚拟盘符Guacamole后，ERP系统使用Guacamole里的数据文件读取数据，导致IIS报错，服务器自动重启【数据手动拷贝到物理盘，同样数据导入操作无异常】**

**Bug 重现步骤**
1.上传数据到虚拟盘符Guacamole
![捕获](https://user-images.githubusercontent.com/63135200/234153329-50cad814-f607-486a-9ddd-18580cd5d98f.PNG)
2.系统从Guacamole盘符导入数据
![ImportData](https://user-images.githubusercontent.com/63135200/234153903-d64aeb2e-3433-44a1-929a-9b8f802488bb.png)
3.系统日志报错，服务器自动重启
![AutoReboot](https://user-images.githubusercontent.com/63135200/234154076-90b2dbb2-ce9b-4c34-a159-0ab4891ed8ec.png)
![err](https://user-images.githubusercontent.com/63135200/234154495-a627ac2c-3365-44b0-9320-92b57cc5d517.png)

**Comment by ZionLoh90** [comment]
在上图2中，点击+选择了虚拟盘符Guacamole中的文件，服务器立刻重启、、、这个问题找了一个星期！！！

**Comment by wojiushixiaobai** [comment]
虚拟盘只作为数据中转的存储路径，此目录非持久化目录。你应当将数据库拷贝到其他持久化目录后正常导入使用。
