### ISSUE TITLE
[Question] jumpserver v2.22.1无法手动推送系统用户到资产

### ISSUE THREAD

**Issue by liuwork479** [jumpserver/jumpserver#10343]
**请描述您的问题.**
jumpserver v2.22.1 关闭系统用户自动推送后，无法手动推送系统用户到相应资产，推送按钮变灰，无法点击

![image](https://user-images.githubusercontent.com/52516621/234481085-64bc62fa-91aa-4003-ba82-28be546344af.png)
![image](https://user-images.githubusercontent.com/52516621/234481192-c16392e7-0b16-468f-a78b-59d2b37a4916.png)
![image](https://user-images.githubusercontent.com/52516621/234481315-caabc03e-cab0-4d10-9f24-6569305a590f.png)

**Comment by BaiJiangJie** [comment]
需要开启`自动提送`按钮。

**Comment by liuwork479** [comment]
> 需要开启`自动提送`按钮。



> 需要开启`自动提送`按钮。

不支持手动推送资产吗？自动推送按钮开启后好像隔一段时间就会推送一次

**Comment by BaiJiangJie** [comment]
自动推送的按钮开启，只会再资产和系统用户进行关联时推送一次（创建授权规则时）。

**Comment by liuwork479** [comment]
好的 了解
