### ISSUE TITLE
[Feature] 会话分享被踢后拒绝再次连接

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#10344]
**请描述您的需求或者改进建议.**
v3.2.1
当前版本将会话分享给其他用户后，用户加入。
当本次问题处理完成后，会话持有者将用户踢出。
被分享用户可以再次通过地址和验证码再次加入。

建议：
1、验证码针对用户一次有效，使用过后无法再次使用。
2、或者踢后被分享者无法再次加入。
3、被分享者打开地址输入验证，会话持有者需要同意方可连接。（增加一次复核）

**Comment by BaiJiangJie** [comment]
计划采用这个机制：`验证码针对用户一次有效，使用过后无法再次使用`；

考虑在 v3.4 中优化；
