### ISSUE TITLE
[Bug] 升级到 V3.2.1 之后 rz 以及 sz 不能使用了

### ISSUE THREAD

**Issue by yunyouu** [jumpserver/jumpserver#10340]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.2.1

**浏览器版本**
112.0

**Bug 描述**
升级到 V3.2.1 之后 rz、sz 无法使用了，在之前版本还能使用但是不确定是哪个版本，服务器是同一台。

**Bug 重现步骤(有截图更好)**
koko 有部分日志，不确定有没有相关，也截图了。
<img width="437" alt="image" src="https://user-images.githubusercontent.com/32095100/234201255-46f032ed-4059-4205-9810-8f797932933e.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/32095100/234201321-14230aa5-38a6-4718-a541-f2b9d42ce712.png">

**Comment by sgyy** [comment]
我这升级到 V3.2.1 之后 rz、sz 也无法使用

**Comment by yxmingh** [comment]
遇到了同样的问题，已经通过数据库备份回退3.1.2

**Comment by LeeEirc** [comment]
已经复现此问题，待 v3.2 小版本中修复。

**Comment by LeeEirc** [comment]
v3.2.2 已发布。
