### ISSUE TITLE
[Question] 客户端redis-cli连接jumpserver纳管的redis报错create session failed, auth failed, EOF

### ISSUE THREAD

**Issue by yiyuqiuchi** [jumpserver/jumpserver#10346]
jumpserver版本：v3.2.1 社区版
redis-cli：6.2
操作系统：macOS 13.3.1   CPU: Apple M1 Max

使用redis-cli连接时报错I/O error，
magnus.log：2023-04-26 16:15:13 [ERRO] create session failed, auth failed, EOF,from: xx.xx.xx.xx:61211 db_type: redis

**Comment by BaiJiangJie** [comment]
Redis 数据库版本是多少？

**Comment by yiyuqiuchi** [comment]
> Redis 数据库版本是多少？

5.2.0

**Comment by BaiJiangJie** [comment]
下面的信息提供一下：

1. 提供一下 redis 资产的账号创建页面的信息
2. 用的什么客户端工具连接的？
3. redis 是否是用了 用户名 认证？（因为 redis6+ 可以使用用户名认证）

其他你认为比较特殊的信息也可以提供一下，尽量详细一些，不然不好定位是什么原因。

**Comment by yiyuqiuchi** [comment]
> 下面的信息提供一下：
> 
> 1. 提供一下 redis 资产的账号创建页面的信息
> 2. 用的什么客户端工具连接的？
> 3. redis 是否是用了 用户名 认证？（因为 redis6+ 可以使用用户名认证）
> 
> 其他你认为比较特殊的信息也可以提供一下，尽量详细一些，不然不好定位是什么原因。

1、
<img width="659" alt="image" src="https://user-images.githubusercontent.com/5187334/235068971-399f7d77-0843-4a96-a249-a6eab5245f3e.png">
2、redis-cli，版本6.2
3、redis版本为5.2，不是redis6+

**Comment by BaiJiangJie** [comment]
redis 5 版本不支持使用用户名认证，但是我们表单限制`用户名`字段又是必填项，所以给了一个特殊的用户名配置；

你将 `jumpserver` 用户名修改为 `null`，在进行数据库连接时会忽略用户名，直接用密码进行验证；

**Comment by yiyuqiuchi** [comment]
> redis 5 版本不支持使用用户名认证，但是我们表单限制`用户名`字段又是必填项，所以给了一个特殊的用户名配置；
> 
> 你将 `jumpserver` 用户名修改为 `null`，在进行数据库连接时 Magnus 会忽略用户名，直接用密码进行验证；
> 
> 这样应该就可以正常通过 DB Client 连接了；

已解决，建议后续能优化，官方文档并没有相关备注和说明。

**Comment by BaiJiangJie** [comment]
<img width="1485" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/0d6aa33c-90f6-4cb2-9460-e78ab63c06a1">
