### ISSUE TITLE
Python依赖安装不成功

### ISSUE THREAD

**Issue by helllkz** [jumpserver/jumpserver#1034]
[简述你的问题]

##### 使用版本
0.5.0

##### 问题复现步骤
安装文档说明，在Centos7下面进行0.5.0版本的安装，安装到Python的时候出错，yum都已安装成功

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/14025168/36885643-33e6b122-1e23-11e8-9be9-22e809866bc4.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请详细说明一下，截图可能会更好些,最好能截全

**Comment by ibuler** [comment]
mysql-devel 或者 mariadb-devel需要安装

**Comment by helllkz** [comment]
@ibuler 
安装了的哦
[error.txt](https://github.com/jumpserver/jumpserver/files/1774417/error.txt)

**Comment by wojiushixiaobai** [comment]
应该是某个devel包没装，建议试试yum update

**Comment by helllkz** [comment]
yum update也执行了，还是报错。就是mysqlclient失败了，我系统里面现在没装mysql，装的10.2的mariadb，应该没区别吧

**Comment by wojiushixiaobai** [comment]
@helllkz 理论上来说只要装了对应的python数据库驱动就行。你可以继续往下走试试看；实在不行就重新搭个服务器吧

**Comment by helllkz** [comment]
把mariadb卸载了，重装了mysql，然后再yum按照的mysql-devel就可以了，之前是装mariadb-devel，估计是这个原因

**Comment by gengkeye** [comment]
我也遇到了这个问题，安装mariadb后，无法安装mysqlclient，报错是：gcc找不到-lmariadb。
然后我卸载了mariadb，安装mysql，再安装mysql-devel，报错， 说mysql-devel和mysql-server冲突，
接着我手动下载了mysql-devel的rpm包，可以安装了，但是继续装mysqlclient时仍然装不了，报错是gcc找不到-lmysqlclient
