### ISSUE TITLE
[Feature] 命令过滤 用户、资产 动态联动

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#10345]
**请描述您的需求或者改进建议.**
v3.2.1
当前无法随便输入一个关键字自动联动出已有用户、资产 可以提供选择，当前全部手动输入，可能会出错。（这个联动其他页面都有的啊，怎么命令过滤不支持。）

还有资产缺少资产组的选项。

另外以下截图中几个位置，一行只能写一个吗？还是可以通过分号、逗号等填写多个信息。
![image](https://user-images.githubusercontent.com/58923704/234506333-57a85e7d-3061-4bda-9449-ab399337547b.png)

**Comment by BaiJiangJie** [comment]
资源选择问题会在 v3.3 版本中优化；

**Comment by BaiJiangJie** [comment]
新版本已支持。
