### ISSUE TITLE
[Question] 黑屏 - Web acces via remote host is black page

### ISSUE THREAD

**Issue by GGOOHAPPY** [jumpserver/jumpserver#10348]
I have deployed the remote host and completed all the initial setup , 
![image](https://user-images.githubusercontent.com/56582124/234529149-1ea140b8-4e79-427f-8c16-c4d6326ce28f.png)
However , when I use access web application , if will show logging in with a self created acct.
![image](https://user-images.githubusercontent.com/56582124/234530363-1cbef715-24dc-4aad-be2a-725c3e78df16.png)
but after a while , it is still a blank page and nothing show up . 
i tested the acct i could login to the remote host . 
is there somehting else i could trouble shoot the problem ?

**Comment by wojiushixiaobai** [comment]
What kind of blank page can you capture below?

**Comment by GGOOHAPPY** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/56582124/234808493-fd6190ea-cadd-40bb-bf1d-af30e2c81539.png">
the web terminal is blank after waiting user profile service

**Comment by BaiJiangJie** [comment]
Look at the log information of the `Lion` component.

`/data/jumpserver/lion/data/logs/lion.log`

**Comment by JumpServer-Zac** [comment]
Hi there, I am the JumpServer support team Zac,
You can add my WhatsApp +86 15717111453 if you need help to use JumpServer
