### ISSUE TITLE
[Bug] 局域网同步点击提交没有反应

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#10353]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1

**浏览器版本**
谷歌浏览器最新版

**Bug 描述**
局域网同步点击提交没有反应

**Bug 重现步骤(有截图更好)**
1.资产同步方式选择局域网同步
![image](https://user-images.githubusercontent.com/35896106/234733704-69be4c7d-13d6-48ac-9a3a-729a64619b75.png)

2.填写信息点击提交没有反应（稳定复现）
![image](https://user-images.githubusercontent.com/35896106/234733750-c61768eb-4ee1-4ed1-8bea-fb328ea46718.png)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/3093

https://github.com/jumpserver/lina/pull/3094

已修复，小版本会发布。

**Comment by jym503558564** [comment]
已修复
