### ISSUE TITLE
[Bug] 控制台里读取地址错误，无法连接服务器

### ISSUE THREAD

**Issue by nmxiaowei** [jumpserver/jumpserver#10359]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.0

**浏览器版本**
谷歌版本 109.0.5414.87（正式版本） (x86_64)

**Bug 描述**
![image](https://user-images.githubusercontent.com/35983068/234808108-b4f09f2b-d1b3-4e86-8f97-9670b4cd389a.png)
控制台这里读取的是127.0.0.1 应该读取的是域名才对

**Bug 重现步骤(有截图更好)**
1.进入控制台连接服务器

**Comment by BaiJiangJie** [comment]
配置当前站点；

https://github.com/jumpserver/jumpserver/issues/10329#issuecomment-1519728812

**Comment by BaiJiangJie** [comment]
同时看一下 `系统设置-终端设置-服务端点` 配置。


<img width="2552" alt="image" src="https://user-images.githubusercontent.com/32935519/235045563-03ac8dc0-4d0d-42cb-9c2b-b62e4944cd52.png">
