### ISSUE TITLE
[Bug] v3版本 config.txt 中部分参数的值为 True，导致配置无法生效

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#10351]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1
CentOS 7.9 2009

**浏览器版本**
Chrome 版本 112.0.5615.138（正式版本） （64 位）

**Bug 描述**
v3版本 config.txt 中部分参数的值为 True，导致配置无法生效，具体参数为 JUMPSERVER_ENABLE_FONT_SMOOTHING=True
通过Web终端连接到 Windows 远程桌面或远程应用时，字体边缘锯齿严重。
参考 v2 版本，修改为 JUMPSERVER_ENABLE_FONT_SMOOTHING=true 并重启后，字体平滑生效，

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.3 版本会解决。

https://github.com/jumpserver/jumpserver/issues/10312

**Comment by BaiJiangJie** [comment]
v3.3.0 版本已修复。
