### ISSUE TITLE
[Bug] 按照接口文档写的api报错

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#10355]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.2.1
**浏览器版本**
chrome mac 最新版

**Bug 描述**
![image](https://user-images.githubusercontent.com/28191563/234788504-652eabee-cada-4e01-9e85-6421dad178f0.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/32935519/235088022-2115afc9-5ef2-4433-a847-c953d223a8c0.png">

我用 postman 试了下没问题，你用 postman 试试呢？

**Comment by whiskyy** [comment]
postman确实没问题

**Comment by whiskyy** [comment]
找到问题了，使用requst库的时候要用json，指定其他的会报错

![image](https://user-images.githubusercontent.com/28191563/236782760-9b4f19a1-560a-4446-91ed-80dd764ad0e7.png)
