### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by alexjs001** [jumpserver/jumpserver#10350]
**请描述您的需求或者改进建议.**

3.0以后版本的社区版本， 系统设置--->>>认证设置里面没有第三方集成（钉钉、微信、飞书），这个后期会开放使用吗

**Comment by luweijun1992** [comment]
> **请描述您的需求或者改进建议.**
> 
> 3.0以后版本的社区版本， 系统设置--->>>认证设置里面没有第三方集成（钉钉、微信、飞书），这个后期会开放使用吗

 更新说明说了，这个功能要商业版支持。同时将远程应用下放到开源版。
https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9
【系统管理】社区版 JumpServer v3.0 版本认证只支持 LDAP、CAS。 如果之前配置的是其它认证方式，在升级后依然可用，但不再能修改。

**Comment by alexjs001** [comment]
之前2.x版本有配置钉钉登录的，也是可以正常登录的；现在升级到3.2.1版本，钉钉登录提示“你无权限查看该页面”

**Comment by alexjs001** [comment]
是钉钉后台权限问题，功能正常的

**Comment by BaiJiangJie** [comment]
好的。
