### ISSUE TITLE
[Bug] 目标资产删除已推送的模版账号，重新授权不会重新推送

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#10358]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1

**浏览器版本**
版本 112.0.5615.138（正式版本） （64 位）

**Bug 描述**
1、资产授权的时候选择模版账号（会自动创建资产下不存在的账号并推送）；
2、推送完成之后，在目标主机删除推送的模版账号；
3、资产授权重新授权该模版账号，不再重新推送；

**Bug 重现步骤(有截图更好)**
1.推送wa完成，并且删除模版用户
![1](https://user-images.githubusercontent.com/43403764/234796672-09e48a7e-3e46-49e3-886d-ee5984416594.png)

2.重新授权，再次登录
![登录报错](https://user-images.githubusercontent.com/43403764/234796800-1d089c9c-38f2-412e-8de3-540e95462b9b.png)

此外：通过模版账号授权后，首次登录偶尔会出现报错，第二次登录就正常了

**Comment by BaiJiangJie** [comment]
目标主机上已经删除 template 肯定连接不了啊！

按照下面的步骤重新操作一下：

1. 在资产详情页找到账号 template，删除并重新做资产授权；
2. 在资产详情页找到账号 template，进行手动推送；


`此外：通过模版账号授权后，首次登录偶尔会出现报错，第二次登录就正常了`

第一次登录时，推送任务会不会还没有完成？

**Comment by LinuxLeader** [comment]
明白，我以为会重新推送一次。
