### ISSUE TITLE
windows远程的问题

### ISSUE THREAD

**Issue by litian6363** [jumpserver/jumpserver#1036]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
1. 更新jumpserver后发现多了rdp协议的支持，赶紧把coco和luna也更新了，然后测试一下
2. docker也下载好
3. 测试没显示
![image](https://user-images.githubusercontent.com/32709005/36888972-d13e0a2e-1e32-11e8-9d13-afa931d9c756.png)

##### 具体表现[截图可能会更好些,最好能截全]
docker的输出
![image](https://user-images.githubusercontent.com/32709005/36889022-0e7625fc-1e33-11e8-9f79-dce750ceabff.png)
![image](https://user-images.githubusercontent.com/32709005/36889065-3a4e596a-1e33-11e8-96f1-6b28ca07a9b2.png)
不知道哪里出错了。。。

##### 其他
如果有个window的使用指南就好了。。。
非常感谢，元宵快乐！！

[注:] 完成后请关闭 issue

**Comment by jiaxiangkong** [comment]
已经更新 https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%BA%94%E7%94%A8%E5%9B%BE%E8%A7%A3
