### ISSUE TITLE
[Bug] 在线会话数和在线会话列表依然存在（当用户断开会话后）

### ISSUE THREAD

**Issue by liuhryme** [jumpserver/jumpserver#10363]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
chrome 

**Bug 描述**
升级至3.2.1之后，控制台>仪表盘>实时数据>在线会话数 数据有异常；

**Bug 重现步骤(有截图更好)**
1.用户浏览器终端已经退出，但是控制台>仪表盘>实时数据>在线会话数 中显示用户还展示在 在线会话中。
![image](https://user-images.githubusercontent.com/12726017/235038603-8246b164-1fcf-4963-8bf1-a7ade2165595.png)

**Comment by BaiJiangJie** [comment]
意思是用户通过 Web Terminal 登录了资产，此时`仪表盘-在线会话数` 和 `会话记录-在线会话` 列表数据是正常的，当用户断开会话后，这边的数据没有更新对吗？

**Comment by liuhryme** [comment]
是的 是这个意思 仪表盘-在线会话数 和 会话记录-在线会话  还显示在线 .
![image](https://user-images.githubusercontent.com/12726017/235047191-b355aa2f-b566-41f8-a1b5-71e31e1147a4.png)
这是从“监控”里面看到的。

**Comment by BaiJiangJie** [comment]
开始时用户连接成功了吗？

**Comment by BaiJiangJie** [comment]
我刚才测试没有复现，你现在再连一个会话看看这个会话断开后会不会正常移动到`历史会话`列表中。

**Comment by liuhryme** [comment]
我打开的是这个会话  四天前都已经断开了。 现在还显示在在线会话里。
![image](https://user-images.githubusercontent.com/12726017/235136158-23b087b3-6561-46bf-b49a-042ec4931ae7.png)

**Comment by liuhryme** [comment]
![image](https://user-images.githubusercontent.com/12726017/236085067-c4498323-72ac-4747-b116-9c17d371216f.png)
 这个应该yi mu一目了然吧。

**Comment by pika-FENG** [comment]
我这边也复现了，这个会话其实是没有连接上，但是从在线会话里一直显示，而且下发“中断"也不会断。
<img width="1670" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/61920af9-d1a4-4538-9b9d-58b989130cf2">
<img width="721" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/b4a49604-5684-49a1-811c-51129a1920a1">

**Comment by pika-FENG** [comment]
<img width="1677" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/17a19166-4cd3-4540-b708-b08c2bce2c77">
还有这个审计台，仪表盘，历史会话显示”-1“

**Comment by yiqikeji17** [comment]
我这边也是同样的问题，目前使用版本v3.3.0还是存在这个bug
![image](https://github.com/jumpserver/jumpserver/assets/76174277/13476d28-374d-430e-adc7-338bc21fcba3)

**Comment by BaiJiangJie** [comment]
最新版本已修复。
