### ISSUE TITLE
[Feature] 批量更新资产时能否不限定必须设置节点

### ISSUE THREAD

**Issue by helfee** [jumpserver/jumpserver#10365]
**请描述您的需求或者改进建议.**
![微信截图_20230428143155](https://user-images.githubusercontent.com/4361294/235071915-c52e0dae-8197-478f-83d5-7646378fdcb5.png)
例如想修改linux资产的ftp路径，批量更新资产的系统平台还做不到，只能一个一个节点修改

**Comment by BaiJiangJie** [comment]
`选择属性` 这一行，`节点`取消勾选；

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/32935519/235089611-4f463f39-3963-4cc9-ade0-01bf5ef8d64f.png">
