### ISSUE TITLE
[Bug] 2.14.2升级到3.2.1 表结构变更失败

### ISSUE THREAD

**Issue by tzm1921995** [jumpserver/jumpserver#10370]
直接升级提示以下报错：
2023-04-29 09:59:32 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying tickets.0011_remove_approvalrule_assignees_display... OK
  Applying terminal.0041_auto_20211105_1605... OK
  Applying terminal.0042_auto_20211229_1619... OK
  Applying tickets.0012_ticketsession... OK
  Applying tickets.0013_ticket_serial_num...
	Fill ticket serial number ... 
 OK
  Applying tickets.0014_auto_20220217_2135... OK
  Applying tickets.0015_superticket... OK
  Applying terminal.0043_auto_20220217_2135...2023-04-29 09:59:35 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 230, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
[ERROR] 表结构变更失败!

尝试过以下方式：
1、新安装3.2.1版本环境，将2.14.2版本数据库备份还原到新数据库中
     失败，很多表字段不能为空，无法导入
2、在方法1失败后尝试使用navicat将数据同步到新库中，字段不能为空时修改字段属性，数据同步完成
    失败，数据库覆盖后jumpserver无法启动
3、在方法1基础上只同步users-user表部分数据，想将数据迁移到新环境
    失败，3.2.1环境中users-user表有数据情况下系统无法显示导入的用户，新建用户可以显示

请问有没有其它数据升级方案

**Comment by wojiushixiaobai** [comment]
不能覆盖数据，只能新建空库然后导入数据进行升级。
注意数据库字符集和排序规则需要与旧版本一致。

**Comment by jym503558564** [comment]
升级请参考官方文档，如有问题可将报错贴出来，再次打开该Issues

**Comment by ztskycn** [comment]
> 直接升级提示以下报错： 2023-04-29 09:59:32 Migrate model change to database ... Operations to perform: Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users Running migrations: Applying tickets.0011_remove_approvalrule_assignees_display... OK Applying terminal.0041_auto_20211105_1605... OK Applying terminal.0042_auto_20211229_1619... OK Applying tickets.0012_ticketsession... OK Applying tickets.0013_ticket_serial_num... Fill ticket serial number ... OK Applying tickets.0014_auto_20220217_2135... OK Applying tickets.0015_superticket... OK Applying terminal.0043_auto_20220217_2135...2023-04-29 09:59:35 Perform migrate failed, exit Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute return self.cursor.execute(query, args) File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query _mysql.connection.query(self, query) MySQLdb._exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/opt/jumpserver/./jms", line 88, in perform_db_migrate management.call_command('migrate') File "/usr/local/lib/python3.9/site-packages/django/core/management/**init**.py", line 181, in call_command return command.execute(*args, **defaults) File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute output = self.handle(*args, **options) File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped res = handle_func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle post_migrate_state = executor.migrate( File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial) File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial) File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 230, in apply_migration migration_recorded = True File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 118, in **exit** self.execute(sql) File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute cursor.execute(sql, params) File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in **exit** raise dj_exc_value.with_traceback(traceback) from exc_value File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute return self.cursor.execute(query, args) File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute res = self._query(query) File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query db.query(q) File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query _mysql.connection.query(self, query) django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint') [ERROR] 表结构变更失败!
> 
> 尝试过以下方式： 1、新安装3.2.1版本环境，将2.14.2版本数据库备份还原到新数据库中 失败，很多表字段不能为空，无法导入 2、在方法1失败后尝试使用navicat将数据同步到新库中，字段不能为空时修改字段属性，数据同步完成 失败，数据库覆盖后jumpserver无法启动 3、在方法1基础上只同步users-user表部分数据，想将数据迁移到新环境 失败，3.2.1环境中users-user表有数据情况下系统无法显示导入的用户，新建用户可以显示
> 
> 请问有没有其它数据升级方案

你好，你后来怎么解决的，我是按照他们升级方案来的。也是有问题Mysql表迁移一直过不去。。。
