### ISSUE TITLE
[Bug] 修改数据库客户端连接过期时间不生效

### ISSUE THREAD

**Issue by CoderConan** [jumpserver/jumpserver#10373]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

JumpServer：v3.2.1
操作系统：CentOS 7.9 2009

**浏览器版本**

与浏览器版本无关

**Bug 描述**

编辑配置文件 /opt/jumpserver/config/config.txt
追加配置项：CONNECTION_TOKEN_EXPIRATION=21600
使用客户端模式连接MySQL数据库，连接信息显示过期时间为21599s，但实际上连接信息仍然是300s过期

**Bug 重现步骤(有截图更好)**
1. ![image](https://user-images.githubusercontent.com/88372830/235934408-9c3288f0-73b5-492c-b052-2afd19b1129e.png)
2. ![image](https://user-images.githubusercontent.com/88372830/235934775-f5a0af05-5929-422e-b2f1-b9f5c84cdfe1.png)

**Comment by BaiJiangJie** [comment]
目前版本在连接过一次后就会失效；

v3.3 版本会考虑支持多次使用（在有效期内）。

**Comment by CoderConan** [comment]
好的，希望v3.3版本能增加在有效期内支持多次连接的功能！ @BaiJiangJie

**Comment by jibill** [comment]
@BaiJiangJie Hi. 请问下v3.3.1版本中修复这个问题了吗？
