### ISSUE TITLE
[Feature] Web 终端页面快捷命令执行

### ISSUE THREAD

**Issue by baixing99** [jumpserver/jumpserver#10377]
**请描述您的需求或者改进建议.**
是否能提供像xshell一样的快捷按钮功能 点击按钮可以吧一些常用命令输入到服务器中
![按钮](https://user-images.githubusercontent.com/73473087/236123306-4322ed78-1a09-48db-bb73-fdcdefe59c66.png)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10010

同这个需求一样，会考虑。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10010

同这个需求一样，会考虑。

**Comment by baixing99** [comment]
收到&nbsp; 十分感谢。

**Comment by BaiJiangJie** [comment]
好的，不客气，具体上线版本暂时还确定。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
