### ISSUE TITLE
[Question] web管理华为防火墙不会自动填充密码

### ISSUE THREAD

**Issue by iderfu** [jumpserver/jumpserver#10378]
**请描述您的问题.**
版本：V3.2.1 docker部署
配置好应用发布机后，通过web去管理华为防火墙或者是Vcenter的时候，只能自动填充用户名，密码不会自动填充。

![2d56bf2af4ee8b201cf913716341fa4](https://user-images.githubusercontent.com/132550149/236137470-5b24732c-5866-468d-9783-51c30892d9a8.png)

![8a0644ddbd42b09fc695b73203b991c](https://user-images.githubusercontent.com/132550149/236137487-92db4ebb-6a81-4529-8678-6d99195a6ff1.png)

**Comment by fitchibing** [comment]
https://bbs.fit2cloud.com/t/topic/413

**Comment by 233rp** [comment]
华为防火墙的密码输入框代码是隐藏的，往里面输入了字符以后，会跳转到隐藏的标签，可以通过自定义脚本来解决。
自定义脚本需要写4个节点。

**Comment by 233rp** [comment]
[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "",
    "command": "type"
  },
  {
    "step": 2,
    "value": "",
    "target": "",
    "command": "click"
  },
  {
    "step": 3,
    "value": "{SECRET}",
    "target": "",
    "command": "type"
  },
  {
    "step": 4,
    "value": "",
    "target": "",
    "command": "click"
  }
]
可以尝试使用上面的自定义脚本，第二个节点为点击密码框，触发隐藏的标签，第三个节点为在隐藏的标签输入密码

**Comment by 233rp** [comment]
或者收集密码框的XPath值之前在密码框随意输入几个字符，然后直接将收集的XPath放入密码选择器中，在登陆资产后需要点击密码框，让隐藏的标签显现，密码就会自动填入

**Comment by iderfu** [comment]
> 或者收集密码框的XPath值之前在密码框随意输入几个字符，然后直接将收集的XPath放入密码选择器中，在登陆资产后需要点击密码框，让隐藏的标签显现，密码就会自动填入


这个是这个意思吗，这个xpath以前没用过，不知道怎么用

我按照那个自定义脚本写上去好像也不行，用你说的自定义脚本，连用户名都识别不出来了

![image](https://user-images.githubusercontent.com/132550149/236610739-77b78c80-a1ed-4d9a-9bc2-01a3bb33d685.png)
![image](https://user-images.githubusercontent.com/132550149/236610744-9892047d-a8b5-4c00-9970-61483b5b9539.png)

**Comment by 233rp** [comment]
> > 或者收集密码框的XPath值之前在密码框随意输入几个字符，然后直接将收集的XPath放入密码选择器中，在登陆资产后需要点击密码框，让隐藏的标签显现，密码就会自动填入
> 
> 这个是这个意思吗，这个xpath以前没用过，不知道怎么用
> 
> 我按照那个自定义脚本写上去好像也不行，用你说的自定义脚本，连用户名都识别不出来了
> 
> ![image](https://user-images.githubusercontent.com/132550149/236610739-77b78c80-a1ed-4d9a-9bc2-01a3bb33d685.png) ![image](https://user-images.githubusercontent.com/132550149/236610744-9892047d-a8b5-4c00-9970-61483b5b9539.png)

选择 full XPath  然后注意前两个字母是大写   XPath=

**Comment by 233rp** [comment]
> > 或者收集密码框的XPath值之前在密码框随意输入几个字符，然后直接将收集的XPath放入密码选择器中，在登陆资产后需要点击密码框，让隐藏的标签显现，密码就会自动填入
> 
> 这个是这个意思吗，这个xpath以前没用过，不知道怎么用
> 
> 我按照那个自定义脚本写上去好像也不行，用你说的自定义脚本，连用户名都识别不出来了
> 
> ![image](https://user-images.githubusercontent.com/132550149/236610739-77b78c80-a1ed-4d9a-9bc2-01a3bb33d685.png) ![image](https://user-images.githubusercontent.com/132550149/236610744-9892047d-a8b5-4c00-9970-61483b5b9539.png)

复制的时候选择full XPath  注意 XPath的前两个字母大写

**Comment by iderfu** [comment]
> > > 或者收集密码框的XPath值之前在密码框随意输入几个字符，然后直接将收集的XPath放入密码选择器中，在登陆资产后需要点击密码框，让隐藏的标签显现，密码就会自动填入
> > 
> > 
> > 这个是这个意思吗，这个xpath以前没用过，不知道怎么用
> > 我按照那个自定义脚本写上去好像也不行，用你说的自定义脚本，连用户名都识别不出来了
> > ![image](https://user-images.githubusercontent.com/132550149/236610739-77b78c80-a1ed-4d9a-9bc2-01a3bb33d685.png) ![image](https://user-images.githubusercontent.com/132550149/236610744-9892047d-a8b5-4c00-9970-61483b5b9539.png)
> 
> 复制的时候选择full XPath 注意 XPath的前两个字母大写


/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[6]/div[1]/input


复制的时候选择full XPath 粘贴的时候是显示这个字符的，感觉还是不行呢

**Comment by 233rp** [comment]
[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "id=username",
    "command": "type"
  },
  {
    "step": 2,
    "value": "",
    "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[5]/div[1]/input",
    "command": "click"
  },
  {
    "step": 3,
    "value": "{SECRET}",
    "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[4]/div[1]/input",
    "command": "type"
  },
  {
    "step": 4,
    "value": "",
    "target": "XPath=/html/body/div[1]/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[1]/table/tbody/tr/td",
    "command": "click"
  }
]

**Comment by iderfu** [comment]
[](url)> 

![image](https://github.com/jumpserver/jumpserver/assets/132550149/92ef1efc-e2dd-43d5-9f71-56017d71673f)
![image](https://github.com/jumpserver/jumpserver/assets/132550149/9768eb17-660d-4c82-a67d-1b31e6930a28)
[这样好像也不行哦，代码这块能力不行，不会写，不知道是不是没写对，附件是华为给的参考脚本，您再帮忙看看，谢谢]([url]([url]([url]([代填测试脚本-new.txt](https://github.com/jumpserver/jumpserver/files/11540703/-new.txt)))))

**Comment by iderfu** [comment]
[
[代填测试脚本-new.txt](https://github.com/jumpserver/jumpserver/files/11540710/-new.txt)
](url)

**Comment by 233rp** [comment]
直接把我的那个复制进去脚本就行了，不用改

**Comment by LeeEirc** [comment]
Chrome 浏览器可以安装 Selenium IDE 插件，通过这个插件，导出脚本，协助编写脚本里的 target 的值

**Comment by qianshijinshen** [comment]
> Chrome 浏览器可以安装 Selenium IDE 插件，通过这个插件，导出脚本，协助编写脚本里的 target 的值

这个工具怎么配合jms使用呢，我通过工具代填没问题，但是将工具生成的步骤填到jms脚本里就不行

**Comment by LeeEirc** [comment]
导出工具生成的脚本文件，大部分是 .side 后缀的文件名。打开文件，可以使用这个 target 的值

![image](https://github.com/jumpserver/jumpserver/assets/32626707/62cee9ca-d1f3-416d-a209-b1e71d059591)

**Comment by 233rp** [comment]
> > [ { "step": 1, "value": "{USERNAME}", "target": "id=username", "command": "type" }, { "step": 2, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[5]/div[1]/input", "command": "click" }, { "step": 3, "value": "{SECRET}", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[4]/div[1]/input", "command": "type" }, { "step": 4, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[1]/table/tbody/tr/td", "command": "click" } ]
> 
> 没用呢，按你这个脚本，连用户名都识别不了了呢，上面的华为界面的截图就是用你上面的脚本填进去的

2332836501

**Comment by BaiJiangJie** [comment]
最新版本已解决。
