### ISSUE TITLE
普通用户首次登陆所填的ssh公钥 填啥

### ISSUE THREAD

**Issue by cjw0202** [jumpserver/jumpserver#1038]
[简述你的问题]
普通用户首次登陆所填的ssh公钥 填啥
##### 使用版本
0.5.0

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/17582805/36964356-575c48d6-2091-11e8-80ee-a3b81c9971ff.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ifreesec** [comment]
就是这个**用户自己**电脑上的公钥，用于终端登录跳板机的

**Comment by ibuler** [comment]
用户自己生成秘钥对，公钥贴上来，和github机制一样
