### ISSUE TITLE
[Bug] 从V2升级到V3后，账号无法测试通过

### ISSUE THREAD

**Issue by jason-bateman** [jumpserver/jumpserver#10398]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
V2升级到V3后，系统账号会复制分配给每一个资产，资产总原来V2的密码账号连接测试提示“Unable to connect to asset: encountered RSA key, expected OPENSSH key”

**Bug 重现步骤(有截图更好)**
1.账号管理-账号列表
2.选择一个托管密码方式账号点击测试
3.提示FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/local/bin/python3.9"},"changed": false, "msg": "Unable to connect to asset: encountered RSA key, expected OPENSSH key"}

**Comment by BaiJiangJie** [comment]
查看一下迁移后的账号密码是不是正确

**Comment by jason-bateman** [comment]
账号密码是正确的，使用ssh直接用在页面上输入mfa码获取的密码也可以登录机器

**Comment by BaiJiangJie** [comment]
日志看获取的是私钥，你是用的是密码还是密钥？

**Comment by jason-bateman** [comment]
![WX20230508-192547](https://user-images.githubusercontent.com/17306875/236812174-2ad2dd17-6673-4c13-b69a-671479192bd3.png)

**Comment by BaiJiangJie** [comment]
手动更新一下密码的账号呢？

**Comment by jason-bateman** [comment]
手动更新也不可以

**Comment by BaiJiangJie** [comment]
其他资产的账号呢？（密码认证方式）

或者在这个资产下创建一个其他的账号试一下？

定位一下只是当前账号的问题，还是通用问题？

**Comment by jason-bateman** [comment]
我今天又重新弄个新的环境，添加账号以及测试连接性都是可以的  应该是升级的一个bug
