### ISSUE TITLE
[Question] 特权帐号切换的普通帐号问题

### ISSUE THREAD

**Issue by c342ng** [jumpserver/jumpserver#10395]
Jumpserver：3.2.1
1:特权帐号切换的普通帐号 新建时无“切换自”选项，在更新时可以选择“切换自”，如果不填写密码在登陆时会要求填密码，任意密码均可登陆，这块功能是否有问题。
2:特权帐号切换的普通帐号是否支持sftp。 在特权帐号切换的普通帐号连接时报“ connection lost“错误，如果支持，需要如何配置。

**Comment by BaiJiangJie** [comment]
第一个问题：

> “切换自”选项受平台的控制 `启用账号切换`；
> 
> 不填写密码，默认为手动登录；
> 
> 任意密码均可登录，那就有问题了，看看是不是目标主机的设置？

第二个问题：

> sftp 不支持切换自用户登录；
