### ISSUE TITLE
[Question] 关于/prometheus/metrics/的api

### ISSUE THREAD

**Issue by Egbert-518** [jumpserver/jumpserver#10397]
您好，我的jumpserver版本是3.2.1，按照官方文档进行在线的默认配置部署，在使用/api/docs在线调用/prometheus/metrics/的api时结果如下
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Server error</title>
</head>
<body>
<h1>Server error occur, contact administrator</h1>
</body>
</html>
```
想知道是什么原因，是否需要额外安装prometheus才可正常使用？另外想咨询一下该接口是用于监视jumpserver本身还是监视其下资产状态的？

**Comment by BaiJiangJie** [comment]
`/prometheus/metrics/`

现在有点问题，v3.2.2 版本会修复。

接口是用于监视 JumpServer 组件的一些参数，cpu、负载、存储等等的一些数据。

**Comment by Egbert-518** [comment]
> `/prometheus/metrics/`
> 
> 现在有点问题，v3.2.2 版本修复。
> 
> 接口是用于监视 JumpServer 组件的一些参数，比如：cpu、负载、存储等等的一些数据。

好的，谢谢您
