### ISSUE TITLE
[Feature] web页面登录问题

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10392]
**请描述您的需求或者改进建议.**
如何使用远程应用的话，可以调用谷歌浏览器进行免密登录。但是浏览器记住的密码可以通过F12控制台进行查看，这个请问贵公司可有好的解决办法呀。it人员基本上都懂这个，密码一下子就泄露了

**Comment by LeeEirc** [comment]
代码里，禁用了 chrome 浏览器的相关插件功能，应该不会记录密码了。
