### ISSUE TITLE
window同时连接问题

### ISSUE THREAD

**Issue by litian6363** [jumpserver/jumpserver#1039]
[简述你的问题]
不能同时连接2台window
##### 使用版本
0.5.0

##### 问题复现步骤
1. 点第一台机，登录成功
2. 点第二台机，第一台机的guacamole就登出了

##### 其他
如果用第二个浏览器操作就可以同时登录2台window

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
same with #1041
