### ISSUE TITLE
[Bug] web终端访问website黑屏，rdp3389正常-源代码部署

### ISSUE THREAD

**Issue by 0lizi** [jumpserver/jumpserver#10393]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1

**浏览器版本**
Chrome 108.0.5359.125（正式版本） （64 位）

**Bug 描述**
RDP3389端口正常，http类型无法访问，跳转几次后黑屏前端不报错。
可能出错点：
 ERRINFO_RPC_INITIATED_DISCONNECT_BY_USER (0x0000000B):The disconnection was initiated by an administrative tool on the server running in the user's session.
日志如下
guacd[4118610]: INFO:   Guacamole proxy daemon (guacd) version 1.4.0 started
guacd[4118610]: DEBUG:  Successfully bound AF_INET socket to host 127.0.0.1, port 4822
guacd[4118610]: INFO:   Listening on host 127.0.0.1, port 4822
guacd[4118610]: INFO:   Creating new client for protocol "rdp"
guacd[4118610]: INFO:   Connection ID is "$8757b15d-d7a7-4633-a011-aedb764aef2a"
guacd[4118638]: DEBUG:  Processing instruction: size
guacd[4118638]: DEBUG:  Processing instruction: audio
guacd[4118638]: DEBUG:  Processing instruction: video
guacd[4118638]: DEBUG:  Processing instruction: image
guacd[4118638]: DEBUG:  Processing instruction: timezone
guacd[4118638]: DEBUG:  Parameter "console" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "console-audio" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "disable-auth" omitted. Using default value of 0.
guacd[4118638]: INFO:   Security mode: Negotiate (ANY)
guacd[4118638]: DEBUG:  User resolution is 1536x871 at 96 DPI
guacd[4118638]: DEBUG:  Parameter "dpi" omitted. Using default value of 96.
guacd[4118638]: DEBUG:  Using resolution of 1536x871 at 96 DPI
guacd[4118638]: DEBUG:  Parameter "force-lossless" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "read-only" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "client-name" omitted. Using default value of "Guacamole RDP".
guacd[4118638]: DEBUG:  Parameter "enable-wallpaper" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-theming" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-font-smoothing" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-full-window-drag" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-desktop-composition" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-menu-animations" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "disable-bitmap-caching" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "disable-offscreen-caching" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "disable-audio" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-printing" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "printer-name" omitted. Using default value of "Guacamole Printer".
guacd[4118638]: DEBUG:  Parameter "timezone" omitted. Using default value of "Asia/Shanghai".
guacd[4118638]: DEBUG:  Parameter "enable-sftp" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "sftp-hostname" omitted. Using default value of "192.168.100.10".
guacd[4118638]: DEBUG:  Parameter "sftp-port" omitted. Using default value of "22".
guacd[4118638]: DEBUG:  Parameter "sftp-username" omitted. Using default value of "jms_o3uKsSuS".
guacd[4118638]: DEBUG:  Parameter "sftp-password" omitted. Using default value of "".
guacd[4118638]: DEBUG:  Parameter "sftp-passphrase" omitted. Using default value of "".
guacd[4118638]: DEBUG:  Parameter "sftp-root-directory" omitted. Using default value of "/".
guacd[4118638]: DEBUG:  Parameter "sftp-server-alive-interval" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "sftp-disable-download" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "sftp-disable-upload" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "recording-exclude-output" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "recording-exclude-mouse" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "recording-exclude-touch" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "recording-include-keys" omitted. Using default value of 0.
guacd[4118638]: INFO:   Resize method: display-update
guacd[4118638]: DEBUG:  Parameter "enable-touch" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "enable-audio-input" omitted. Using default value of 0.
guacd[4118638]: DEBUG:  Parameter "gateway-port" omitted. Using default value of 443.
guacd[4118638]: INFO:   No clipboard line-ending normalization specified. Defaulting to preserving the format of all line endings.
guacd[4118638]: DEBUG:  Parameter "wol-send-packet" omitted. Using default value of 0.
guacd[4118638]: INFO:   User "@e9122778-c356-4e8d-b5c2-05b6f446d8e8" joined connection "$8757b15d-d7a7-4633-a011-aedb764aef2a" (1 users now present)
guacd[4118638]: DEBUG:  Client is using protocol version "VERSION_1_3_0"
guacd[4118638]: DEBUG:  guac_rdp_fs_alloc: Creating directory "/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d" if necessary.
guacd[4118638]: INFO:   Recording of session will be saved to "/opt/lion-v3.2.1-linux-amd64/data/replays/2023-05-06/e042be19-edf8-4f0b-8303-459ff14fa47e".
guacd[4118638]: INFO:   Loading keymap "base"
guacd[4118638]: INFO:   Loading keymap "en-us-qwerty"
guacd[4118638]: DEBUG:  freerdp_connect:freerdp_set_last_error_ex resetting error state
guacd[4118638]: DEBUG:  Support for CLIPRDR (clipboard redirection) registered. Awaiting channel connection.
guacd[4118638]: DEBUG:  Support for static channel "rdpdr" loaded.
guacd[4118638]: DEBUG:  Support for static channel "rdpsnd" loaded.
guacd[4118638]: DEBUG:  Support for RAIL (RemoteApp) registered. Awaiting channel connection.
guacd[4118638]: DEBUG:  Local framebuffer format  PIXEL_FORMAT_BGRX32
guacd[4118638]: DEBUG:  Remote framebuffer format PIXEL_FORMAT_BGR24
guacd[4118638]: DEBUG:  guac_rdp_fs_open: path="/", access=0x80000000, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Normalized path "/" to "\".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Translated path "\" to "/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: native open: real_path="/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/", flags=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Opened "\" as file_id=0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: path="/Download", access=0x80000000, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Normalized path "/Download" to "\Download".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Translated path "\Download" to "/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/Download".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: native open: real_path="/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/Download", flags=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Opened "\Download" as file_id=1
guacd[4118638]: DEBUG:  guac_rdp_fs_close: Closed "\Download" (file_id=1)
guacd[4118638]: DEBUG:  guac_rdp_fs_close: Closed "\" (file_id=0)
guacd[4118638]: DEBUG:  primitives autodetect, using optimized
guacd[4118638]: DEBUG:  freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
guacd[4118638]: DEBUG:  freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
guacd[4118638]: DEBUG:  CLIPRDR (clipboard redirection) channel connected.
guacd[4118638]: DEBUG:  SVC "rdpdr" connected.
guacd[4118638]: DEBUG:  SVC "rdpsnd" connected.
guacd[4118638]: DEBUG:  RAIL (RemoteApp) channel connected.
guacd[4118638]: DEBUG:  Loading Dynamic Virtual Channel disp
guacd[4118638]: INFO:   Connected to RDPDR 1.12 as client 0x0003
guacd[4118638]: DEBUG:  Ignoring server capability set type=0x0001, length=44
guacd[4118638]: DEBUG:  Ignoring server capability set type=0x0002, length=8
guacd[4118638]: DEBUG:  Ignoring server capability set type=0x0003, length=8
guacd[4118638]: DEBUG:  Ignoring server capability set type=0x0004, length=8
guacd[4118638]: DEBUG:  Ignoring server capability set type=0x0005, length=8
guacd[4118638]: DEBUG:  Sending capabilities...
guacd[4118638]: DEBUG:  Capabilities sent.
guacd[4118638]: DEBUG:  Client ID confirmed
guacd[4118638]: INFO:   RDPDR user logged on
guacd[4118638]: DEBUG:  Registered device 0 (JumpServer)
guacd[4118638]: DEBUG:  All supported devices sent.
guacd[4118638]: DEBUG:  Device 0 (JumpServer) connected successfully
guacd[4118638]: DEBUG:  Display update channel will be used for display size changes.
guacd[4118638]: DEBUG:  guac_rdp_fs_open: path="", access=0x80, file_attributes=0x0, create_disposition=0x1, create_options=0x1
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Normalized path "\" to "\".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Translated path "\" to "/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: native open: real_path="/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/", flags=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Opened "\" as file_id=1
guacd[4118638]: DEBUG:  guac_rdpdr_fs_process_create: [file_id=1] desired_access=0x80, file_attributes=0x0, create_disposition=0x1, create_options=0x1, path=""
guacd[4118638]: DEBUG:  guac_rdp_fs_open: path="\Download", access=0x80000000, file_attributes=0x0, create_disposition=0x3, create_options=0x1
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Normalized path "\Download" to "\Download".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Translated path "\Download" to "/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/Download".
guacd[4118638]: DEBUG:  guac_rdp_fs_open: native open: real_path="/opt/lion-v3.2.1-linux-amd64/data/drive/a3dd543e-118f-4eb7-8e7c-c09af3993c1d/Download", flags=0x0
guacd[4118638]: DEBUG:  guac_rdp_fs_open: Opened "\Download" as file_id=0
guacd[4118638]: DEBUG:  guac_rdp_fs_close: Closed "\Download" (file_id=0)
guacd[4118638]: DEBUG:  guac_rdpdr_fs_process_query_basic_info: [file_id=1]
guacd[4118638]: DEBUG:  guac_rdpdr_fs_process_close: [file_id=1]
guacd[4118638]: DEBUG:  guac_rdp_fs_close: Closed "\" (file_id=1)
guacd[4118638]: DEBUG:  ERRINFO_RPC_INITIATED_DISCONNECT_BY_USER (0x0000000B):The disconnection was initiated by an administrative tool on the server running in the user's session.
guacd[4118638]: DEBUG:  rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_RPC_INITIATED_DISCONNECT_BY_USER [0x0001000B]
guacd[4118638]: INFO:   RDP server closed/refused connection: Manually disconnected.
guacd[4118638]: DEBUG:  Disconnect reason code: 0xB.
guacd[4118638]: DEBUG:  CLIPRDR (clipboard redirection) channel disconnected.
guacd[4118638]: DEBUG:  Display update channel disconnected.
guacd[4118638]: DEBUG:  Unloading device 0 (JumpServer)
guacd[4118638]: DEBUG:  SVC "rdpdr" disconnected.
guacd[4118638]: DEBUG:  SVC "rdpsnd" disconnected.
guacd[4118638]: INFO:   Internal RDP client disconnected
guacd[4118610]: INFO:   Connection "$8757b15d-d7a7-4633-a011-aedb764aef2a" removed.

**Bug 重现步骤(有截图更好)**
1.  guard日志
![image](https://user-images.githubusercontent.com/32761468/236603161-cfc27d96-4a71-4e19-aee5-c69189e5f8ab.png)

2.lion日志
![image](https://user-images.githubusercontent.com/32761468/236603214-0c211345-af87-4fd9-99e4-b8aca6c2f820.png)

**Comment by wojiushixiaobai** [comment]
确定 guacd 监听在 ipv4 上面，看错误的提示是无法连接上 guacd 的服务 127.0.0.1:4822

**Comment by LeeEirc** [comment]
发布机上 Windows 是否安装自己的 chrome，造成 chrome 驱动冲突，造成启动失败了？

**Comment by 0lizi** [comment]
我更换了一个全新的server2012 r2，更换了应用发布成功后，再连接web应用，提示
![image](https://user-images.githubusercontent.com/32761468/237059944-01a759b4-05c5-44d3-8899-ba0134a2a95a.png)
但是我通过cmd查看是有的
![image](https://user-images.githubusercontent.com/32761468/237060091-c30c5290-768f-4dc9-a5f2-8169219c645a.png)

**Comment by LeeEirc** [comment]
查看下 C:\Program Files\Python310 是否有 pythonw.exe 执行文件？

**Comment by 0lizi** [comment]
应该是操作系统的问题，我把python装到了 C:\Program Files\Python310下，跟最开始的黑屏一样，重新安装了server2019，正常使用了。谢谢~
