### ISSUE TITLE
[Bug] 使用客户端方式连接mysql，报 1045 - backend auth error auth failed

### ISSUE THREAD

**Issue by try3** [jumpserver/jumpserver#10406]
**JumpServer 版本**
v3.2.1

**浏览器版本**

**Bug 描述**
jump最新版本v3.2.1，使用客户端方式连接mysql（非root账号），报 1045 - backend auth error auth failed

**Bug 重现步骤(有截图更好)**
1.
2.
3.

![QQ截图20230509092737](https://user-images.githubusercontent.com/17698581/236971328-30348021-b204-4fbc-b2c1-23ef7b863f6b.jpg)

**Comment by BaiJiangJie** [comment]
MySQL 是什么版本？

**Comment by BaiJiangJie** [comment]
好的，数据库应该是必填的；

后面版本限制一下。

**Comment by zhenghongyang666** [comment]
我也遇到了 请问最后怎么解决的
