### ISSUE TITLE
[Bug] v2.28.10升级到v2.28.13之后lrzsz命令在web terminal无法使用

### ISSUE THREAD

**Issue by abelyang** [jumpserver/jumpserver#10405]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
谷歌 113.0.5672.64（正式版本） （64 位）

**Bug 描述**
[Bug] v2.28.10升级到v2.28.13之后lrzsz命令在web terminal无法使用

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/8252560/236839671-08b5100a-2199-4265-b61f-0db9451ded6e.png)

2.
![image](https://user-images.githubusercontent.com/8252560/236848728-15d41531-24fe-4f83-8b74-94bcad26456b.png)

3.

**Comment by BaiJiangJie** [comment]
嗯，rz、sz 的问题会在 v2.28.14 中修复。（今天下午会发布 05.09）

**Comment by BaiJiangJie** [comment]
已发布（https://github.com/jumpserver/jumpserver/releases/tag/v2.28.14）

**Comment by abelyang** [comment]
已更新
