### ISSUE TITLE
[Bug] 资产标签显示异常

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#10418]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.1

**浏览器版本**
谷歌最新版

**Bug 描述**
添加了三个标签：生产、开发、测试环境，如图，在资产里选了生产，但是在资产列表里，它只显示了key：环境，没有显示value：生产环境，更新资产里面是可以看到的

**Bug 重现步骤(有截图更好)**
![e2f2b36ec95d87bcba9548c3c6a22d5](https://github.com/jumpserver/jumpserver/assets/35896106/d405ff5d-31fc-4a60-bf85-9f3675308a6f)

![f341577ec148df128d39de143e4c747](https://github.com/jumpserver/jumpserver/assets/35896106/84b3cab6-9de8-4031-ae4d-0425215a3992)
![a2f7e8c5e2e407d75fc8d3d571ee5ac](https://github.com/jumpserver/jumpserver/assets/35896106/072643c7-771f-4f6e-9d4b-6a6607a5c340)

**Comment by BaiJiangJie** [comment]
v3.3.0 版本已优化。
