### ISSUE TITLE
[Bug] playbook change Secret没有Set sudo setting

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#10411]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.1

**浏览器版本**

**Bug 描述**
playbook change Secret没有Set sudo setting 这一步

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/28191563/ab33531e-bcdb-4d67-9951-b105c93630ed)

**Comment by BaiJiangJie** [comment]
什么意思？图中不是有吗？

**Comment by whiskyy** [comment]
图中是我自己加的

**Comment by davie89** [comment]
Ubuntu 20.02 就切换不了账号 估计就是sudo设置问题

**Comment by BaiJiangJie** [comment]
最新版本已更新。
