### ISSUE TITLE
[Bug] 重命名了一下节点，后面的资产数量就变成了0，要再刷新一下网页才能重新显示

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#10428]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.2

**浏览器版本**
谷歌浏览器最新版

**Bug 描述**
重命名了一下节点，后面的资产数量就变成了0，要再刷新一下网页才能重新显示

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/35896106/9cdc4235-7433-408e-af64-4ffcb187e7fe)
2.
![image](https://github.com/jumpserver/jumpserver/assets/35896106/1084916a-e212-4213-8f9b-834fc481769d)

**Comment by BaiJiangJie** [comment]
嗯，有这个问题，考虑处理一下。
