### ISSUE TITLE
帐号管理-帐号列表-导入帐号报错

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#10422]
###  社区版本：v3.2.1，按照帐号模版导入后报错，已核实资产ID正确

 **资产导入报错：**

![QQ图片20230510153916](https://github.com/jumpserver/jumpserver/assets/133093482/8ba2e842-88db-4b04-89dc-039fd872039f)

**帐号导入模版：**

![QQ图片20230510153922](https://github.com/jumpserver/jumpserver/assets/133093482/43a260c5-d5c9-4a18-bbc2-6c3b9bdd82c3)

**资产ID：**

![QQ图片20230510153925](https://github.com/jumpserver/jumpserver/assets/133093482/e581e562-619f-4faf-8e5d-b46f5d23694d)

**Comment by BaiJiangJie** [comment]
看下 core 服务的日志，jumpserver.log 文件。

**Comment by jym503558564** [comment]
该问题还存在吗？由于长时间未反馈，我们将关闭该Issues，如有其他问题可再次提Issues
