### ISSUE TITLE
如何关闭录像功能

### ISSUE THREAD

**Issue by hzxgo** [jumpserver/jumpserver#10424]
**请描述您的问题.**
机器负载高，如何关闭录像功能？
以及还有哪些负载高的功能可以关闭吗？

**Comment by BaiJiangJie** [comment]
`机器负载高，如何关闭录像功能？`

终端管理每一个终端中设置 `录像存储` 为 null，就行。

其他情况应该不会导致负载高。

**Comment by hzxgo** [comment]
@BaiJiangJie 你说的不存储录像是等价于不录像？
我理解的不存储录像是会有录像只是不存储罢了，所以我理解的不存储录像只是节省磁盘空间而已，还是会有录像功能。

**Comment by shangxinliu** [comment]
新版本没有这个入口了，怎么办？

**Comment by w940853815** [comment]
放到了系统设置 - 组件设置 - 组件列表 编辑组件即可关闭对应组件的录像功能 @shangxinliu
