### ISSUE TITLE
0.5终端使用sz下载完毕后终端卡死

### ISSUE THREAD

**Issue by myhoop** [jumpserver/jumpserver#1042]
[简述你的问题]
0.5终端使用sz下载完毕后终端卡死
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
1. [步骤1]
sz test.tar.gz

2. [步骤2]
下载完成后，等待3秒左右，终端卡死。
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已经解决，准备更新
