### ISSUE TITLE
如何隐藏跳板机某些列

### ISSUE THREAD

**Issue by hzxgo** [jumpserver/jumpserver#10426]
**请描述您的问题.**
在终端通过ssh登录跳板机，输入p后显示了有权限的资产，目前显示的列名有：
「ID，名称，地址，协议，平台，组织，备注」

请问如何隐藏其中的「协议，平台，组织」列？

**Comment by ryswork1993** [comment]
我跟你的需求是一样的，他们已经有了实现这个需求的安排

**Comment by hzxgo** [comment]
@ryswork1993 了解感谢。那就静候更新了。
