### ISSUE TITLE
[Question] 如何通过API对堡垒机内所有或特定主机批量执行命令

### ISSUE THREAD

**Issue by Ch4mpa9ne** [jumpserver/jumpserver#10430]
**请描述您的问题.**
如何通过APi对堡垒机内所有或特定主机执行命令？就好像luna界面中发送文本到所有终端那样，但是要能通过API执行，查看返回结果。

**Comment by BaiJiangJie** [comment]
你看一下使用一下控制台的作业中心-快捷命令，然后打开浏览器的控制台看看 API 的调用，研究一下。

应该可以满足你的需求。

**Comment by Ch4mpa9ne** [comment]
<img width="233" alt="image" src="https://github.com/jumpserver/jumpserver/assets/22672207/8bb44fef-7308-49c0-b60c-66ab8cb00682">

你是指这里的控制台吗？似乎没有快捷命令。找了找别的地方似乎也没有，但找到了api文档，但只有接口名，没有接口功能介绍文档。

**Comment by BaiJiangJie** [comment]
在 工作台 中，上面描述有误；

**Comment by BaiJiangJie** [comment]
<img width="1791" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d4edcb8d-eaae-4935-b023-c97805e0f29b">
