### ISSUE TITLE
[Bug] 远程应用连接后没有弹出应用程式还直接断连

### ISSUE THREAD

**Issue by PoundofAntonio** [jumpserver/jumpserver#10439]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.2

**JumpServer 主机 OS**
Ubuntu 20.04.1 LTS

**远程应用发布机 OS**
Microsoft Windows Server 2016 Standard

**浏览器版本**
Google Chrome Version 112.0.5615.140

**Bug 描述**
远程应用连接后有显示使用了`jms_`帐号登入RDP, 还有读取使用者设定档
然后就黑屏一分钟就断线

**远程应用发布机状态**
都是成功的
![image](https://github.com/jumpserver/jumpserver/assets/132991093/79226f87-bba7-4743-a125-d31db6d0c731)
![image](https://github.com/jumpserver/jumpserver/assets/132991093/663b9ee2-a4a7-4149-9fea-05b2a77b3eba)

**Bug 重现步骤(有截图更好)**
1. 远程应用连接
![image](https://github.com/jumpserver/jumpserver/assets/132991093/40fff459-2046-4756-80ab-538f02792011)
2. 读取使用者设定档
![image](https://github.com/jumpserver/jumpserver/assets/132991093/640bafff-2a36-4875-aa7c-1a49eec5a304)
3. 黑屏一分钟就断线
![image](https://github.com/jumpserver/jumpserver/assets/132991093/3cbcd21d-d389-4314-aeb8-540677fe69df)

**JumpServer 主机 log**
kern.log: guacd segfault
![image](https://github.com/jumpserver/jumpserver/assets/132991093/21c09c37-117e-48c8-96a9-4d3a57f23b3e)

**Lion 组件 logs from docker container**
- guacd.log: 没有log
- lion.log:
![image](https://github.com/jumpserver/jumpserver/assets/132991093/e74314b4-6bd4-44b3-a80a-d898d553e7ab)

**远程应用发布机 Windows Event log - Application**
Source: JumpServer Tinker
`unexpected control request #{4 0 0 {4 5 0 0 0 0 0} 123456}`
![image](https://github.com/jumpserver/jumpserver/assets/132991093/266a7de0-d2b2-4b32-bca7-def84fa242f3)

**Comment by LeeEirc** [comment]
Windows 上有没有安装其他的 Chrome，另外同步下 Window 发布机 上的 NTP 时间

**Comment by PoundofAntonio** [comment]
已解决, 用server 2019/2022 就行了
