### ISSUE TITLE
[Bug] Redis资产无法显示账号

### ISSUE THREAD

**Issue by gaoyufu** [jumpserver/jumpserver#10437]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.2.2

**浏览器版本**
Chrome 版本 113.0.5672.93（正式版本） （64 位）

**Bug 描述**
redis资产无法显示账号

**Bug 重现步骤(有截图更好)**
1.
![1](https://github.com/jumpserver/jumpserver/assets/66066827/1fc06aac-fb0d-400c-ac01-01a352d22e0f)
2.
![2](https://github.com/jumpserver/jumpserver/assets/66066827/87f28ca0-42b0-4d9c-a373-1dedd1fe8e03)
3.
![3](https://github.com/jumpserver/jumpserver/assets/66066827/ac55902b-e76c-46d0-967f-984cfe54bde3)
4.
![4](https://github.com/jumpserver/jumpserver/assets/66066827/29cb0077-07d1-4f60-8c47-9a3c7c3d10d7)

**Comment by BaiJiangJie** [comment]
做授权了吗？

**Comment by gaoyufu** [comment]
![Snipaste_2023-05-12_18-30-02](https://github.com/jumpserver/jumpserver/assets/66066827/f95c2294-9177-4a93-80b7-c3ee288e228b)
我是管理员权限，还有administer用户也试了，一样的情况

**Comment by BaiJiangJie** [comment]
<img width="2049" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a690c5d2-1bdb-456d-b81c-91d33428a564">

要看资产授权规则中的配置；

**Comment by gaoyufu** [comment]
已解决
