### ISSUE TITLE
[Feature] 可以加一个备案信息展示功能吗

### ISSUE THREAD

**Issue by cangkuai** [jumpserver/jumpserver#10435]
**请描述您的需求或者改进建议.**
现在我们公司准备把jumperver扔到公网但是目前不知道如何在jumpserver的最底部显示备案信息

**Comment by cangkuai** [comment]
?

**Comment by BaiJiangJie** [comment]
目前不支持。

**Comment by ibuler** [comment]
> **请描述您的需求或者改进建议.**
> 现在我们公司准备把jumperver扔到公网但是目前不知道如何在jumpserver的最底部显示备案信息

首先不应该公网
