### ISSUE TITLE
在系统用户为root时，使用jump用户进行资产的文件管理时无法进行权限控制！

### ISSUE THREAD

**Issue by 3721518** [jumpserver/jumpserver#10431]
**请描述您的问题.**
在jumper控制台下，操作资产管理-系统用户-设置特权用户名为root，且SFTP根路径是根的情况下，jumper用户在进行资产的文件管理时无法进行权限的控制。比如：禁止它删除文件和文件夹，可正常删除，目的是不让他删除。
请问这是默认权限行为吗，因为我没找到怎么去控制这个权限的按钮！

**Comment by BaiJiangJie** [comment]
删除操作目前控制不了

**Comment by 3721518** [comment]
> 文件删除操作目前控制不了

那此功能是否在你们迭代开发的排期内呢，我觉得对实例上的文件进行读写控制需求还是很高的。

**Comment by BaiJiangJie** [comment]
目前计划 v3.4、v3.5 版本左右支持控制；

**Comment by 3721518** [comment]
好的
