### ISSUE TITLE
[Question] dial tcp: lookup core on 127.0.0.11:53: server misbehaving

### ISSUE THREAD

**Issue by beebol** [jumpserver/jumpserver#10448]
koko日志如下：
2023-05-12 18:29:52 [ERRO] Update terminal config failed: Get "http://core:8080/api/v1/terminal/terminals/config/": dial tcp: lookup core on 127.0.0.11:53: server misbehaving
2023-05-12 18:29:53 [ERRO] Post "http://core:8080/api/v1/terminal/terminals/status/": dial tcp: lookup core on 127.0.0.11:53: server misbehaving

jumpserver无法打开，重新安装也是一样。

**Comment by beebol** [comment]
版本为：jumpserver-installer-v2.28.8
docker安装

**Comment by BaiJiangJie** [comment]
进入到安装包目录，使用 

./jmsctl.sh down

./jmsctl.sh start

重启一下呢？

重启之前先重启一下 docker 服务。

**Comment by beebol** [comment]
> 

一样的，我把整个数据都清了，重新安装一次也不行。

**Comment by BaiJiangJie** [comment]
@wojiushixiaobai 小白来帮忙看看是什么问题？

**Comment by BaiJiangJie** [comment]
看看 core 服务的启动日志

**Comment by beebol** [comment]
> 看看 core 服务的启动日志

[W 230512 18:53:12 inspector:42] Inspect method active failed
[W 230512 18:53:12 inspector:42] Inspect method stats failed
[W 230512 18:53:12 inspector:42] Inspect method reserved failed
[W 230512 18:53:12 inspector:42] Inspect method registered failed
[W 230512 18:53:12 inspector:42] Inspect method conf failed
[W 230512 18:53:12 inspector:42] Inspect method scheduled failed
[W 230512 18:53:12 inspector:42] Inspect method active_queues failed
[W 230512 18:53:12 inspector:42] Inspect method revoked failed

**Comment by beebol** [comment]
[core_logs.tar.gz](https://github.com/jumpserver/jumpserver/files/11462965/core_logs.tar.gz)
core日志

**Comment by beebol** [comment]
127.0.0.11   53是会自动启的吗？宿主机本成有dnsmasq，我将它停了后，重新安装，并不会有53的监听。

**Comment by wojiushixiaobai** [comment]
别去动你的 iptables 或者 firewalld，把 docker 重启问题即可解决。

**Comment by beebol** [comment]
> 别去动你的 iptables 或者 firewalld，把 docker 重启问题即可解决。

没有动呢，只是机器关机后，再开机，jmsct.sh  start再启来后就行不了。

**Comment by beebol** [comment]
> 别去动你的 iptables 或者 firewalld，把 docker 重启问题即可解决。

[root@crossevery jumpserver-installer-v2.28.8]# ./jmsctl.sh down
[+] Running 7/6
 ⠿ Container jms_koko    Removed                                                                                                                                                                              10.2s
 ⠿ Container jms_magnus  Removed                                                                                                                                                                              11.2s
 ⠿ Container jms_lion    Removed                                                                                                                                                                              10.2s
 ⠿ Container jms_celery  Removed                                                                                                                                                                               0.4s
 ⠿ Container jms_web     Removed                                                                                                                                                                               0.3s
 ⠿ Container jms_core    Removed                                                                                                                                                                               0.2s
 ⠿ Network jms_net       Removed                                                                                                                                                                               0.0s
[root@crossevery jumpserver-installer-v2.28.8]# systemctl restart docker
[root@crossevery jumpserver-installer-v2.28.8]# ./jmsctl.sh start
[+] Running 7/7
 ⠿ Network jms_net       Created                                                                                                                                                                               0.0s
 ⠿ Container jms_core    Healthy                                                                                                                                                                              11.9s
 ⠿ Container jms_magnus  Started                                                                                                                                                                              13.1s
 ⠿ Container jms_celery  Started                                                                                                                                                                              12.4s
 ⠿ Container jms_koko    Started                                                                                                                                                                              12.3s
 ⠿ Container jms_web     Started                                                                                                                                                                              12.4s
 ⠿ Container jms_lion    Started

**Comment by beebol** [comment]
web界面打不开，但我刚才试了下api是可以正常调用。

**Comment by BaiJiangJie** [comment]
core_logs.tar.gz 中 jumpserver.log 日志文件是怎么是空的呢？

**Comment by beebol** [comment]
<img width="1496" alt="image" src="https://github.com/jumpserver/jumpserver/assets/4249023/cbb4e676-f123-44d4-954d-e1316e141240">

**Comment by beebol** [comment]
是网络问题，打扰了。
