### ISSUE TITLE
[Bug] ftp文件管理页面刷新会将软链文件夹识别为文件

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#10440]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.2.2
**浏览器版本**

**Bug 描述**

ftp文件管理页面刷新会将软链文件夹识别为文件

**Bug 重现步骤(有截图更好)**
1.在/root/test/下创建opt软链
![image](https://github.com/jumpserver/jumpserver/assets/66759501/17fd2108-144f-4e99-aa6b-81f4494e0256)

2.在ftp web页面上初次打开显示正常，且能正常访问
![image](https://github.com/jumpserver/jumpserver/assets/66759501/724c796d-3aca-4d2b-8fd2-0682de8c75be)

3.页面刷新之后软链的文件夹识别成了文件
![image](https://github.com/jumpserver/jumpserver/assets/66759501/1a82c26f-0f60-49b5-bcf4-5ceb8a5d6806)
![image](https://github.com/jumpserver/jumpserver/assets/66759501/ecb0b31c-7e92-48bf-b398-1ed6eeda89ae)

**Comment by BaiJiangJie** [comment]
好的，可能有问题，我们复现一下，应该还是比较好复现的。

**Comment by jstbw** [comment]
在3.4.3上测这个问题还存在

**Comment by BaiJiangJie** [comment]
嗯，复现了确实有这个问题，目前还没解决。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/koko/commit/1a37cd546fab13ce5a99601e515a463ff4dc4508

v3.5 解决。
