### ISSUE TITLE
无法创建节点

### ISSUE THREAD

**Issue by zhaofei91** [jumpserver/jumpserver#1045]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2.]
浏览器chrome 版本 64.0.3282.186

##### 问题复现步骤
1. 资产管理-资产列表
2. 无法新增新节点

##### 具体表现[截图可能会更好些,最好能截全]
v0.5.0 应用图解中 资产管理-资产列表 可以新建节点
安装后发现无法新建节点，点击新建节点无任何响应，也没有打印日志。
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
截图看看，不太明白

**Comment by zhaofei91** [comment]
![default](https://user-images.githubusercontent.com/13270279/37072815-4c1bbede-21fe-11e8-9149-29db80b918e9.png)
chrome 浏览器右键不显示节点管理

**Comment by ibuler** [comment]
授权管理不支持添添加节点

**Comment by BosonMao** [comment]
![图片](https://user-images.githubusercontent.com/22047703/76209511-fff49400-623c-11ea-9480-5910f5d31935.png)
无反应

**Comment by BosonMao** [comment]
@ibuler
