### ISSUE TITLE
[Bug] 在堡垒机上设置好rdp分辨率后，使用客户端工具访问远程桌面分辨率设定不生效

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#10456]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.2

**浏览器版本**
chrome 113.0.5672.92

**Bug 描述**
在堡垒机上设置好rdp分辨率后，使用客户端工具访问远程桌面分辨率设定不生效

**Bug 重现步骤(有截图更好)**
1. 工作台 > 设置 > 图形化 > 设置分辨率为1024 * 768
2. 使用客户端的方式去访问远程桌面发现分辨率设定不生效

**Comment by BaiJiangJie** [comment]
v3.3.0 版本已修复。

**Comment by huskiesir** [comment]
> v3.3.0 版本已修复。

收到
