### ISSUE TITLE
helm部署jumpserver，各个pvc大小该如何确定

### ISSUE THREAD

**Issue by qybf** [jumpserver/jumpserver#10458]
**请描述您的问题.**
我在本地测试环境用helm部署好了jumpserver-v3.2.2，即将投入生产，但是现在有一个问题，就是如何确定六个pvc的大小，这六个pvc里面存的都是什么数据，希望各位大佬给个建议。
这是六个pod:
![图片](https://github.com/jumpserver/jumpserver/assets/47775316/d0d7d5d5-e606-4f4c-80ba-d728c68b4a21)

这是六个pvc:
![图片](https://github.com/jumpserver/jumpserver/assets/47775316/e1193e20-2768-4c4b-a2d1-28b7b0cf79d9)

**Comment by wojiushixiaobai** [comment]
data 相关的基本都是录像
log 相关的是日志

其中如果未配置录像上传到其他云存储，那么 core-data 需要合理分配，最终所有录像都会上传到 core-data 目录。
