### ISSUE TITLE
[Bug] 远程应用DBevaer黑屏

### ISSUE THREAD

**Issue by zs19940216** [jumpserver/jumpserver#10452]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.2.2

**Bug 描述**
在使用远程应用DBevaer时黑屏，显示使用jumpserver登录了windows后，就没有反应，一直都是黑屏查看到lion的日志，存在报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/45357822/b6a6f05c-27a4-467e-ad91-d56a93a4d648)
![image](https://github.com/jumpserver/jumpserver/assets/45357822/4d812eb6-b435-4070-92e5-ac1a9a3086da)
![image](https://github.com/jumpserver/jumpserver/assets/45357822/7992d957-c4a4-4406-b96d-db0eab619dbd)

**Comment by BaiJiangJie** [comment]
Web 资产使用 Chrome 远程应用可以连接成功吗？

**Comment by zs19940216** [comment]
> Web 资产使用 Chrome 远程应用可以连接成功吗？

可以，chrome的没问题

**Comment by zs19940216** [comment]
> 以前就不可以，还是说以前没问题，最近才出现的黑屏？

最早部署的时候没问题，后来一直没用，V3.2.1的时候不行，我进行的升级

**Comment by zs19940216** [comment]
> 在系统设置-远程应用中，重新部署一下 DBevaer 应用试试

试过了，把DBevaer删了，重新部署也不行。我准备新建一台windows server主机试试了

**Comment by zs19940216** [comment]
> 好的，等你消息。

重新部署就没问题了，后来试了一下，重新初始化部署也好了就，谢谢了
