### ISSUE TITLE
jumpserver的koko怎么修改支持的算法协议

### ISSUE THREAD

**Issue by Lihy6472** [jumpserver/jumpserver#10460]
* 最近公司漏洞扫描扫到jumpserver-koko的2222端口有两个漏洞需要处理，但是我手动修改koko容器内的/etc/ssh/ssh_config配置文件在最后一行添加了"KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521"内容退出容器后重启了jms_koko容器，但是在别的服务器测试刚才添加的配置并不生效。

![image](https://github.com/jumpserver/jumpserver/assets/116717391/d4ab7f9a-331a-410c-9e75-c27b70328305)
![image](https://github.com/jumpserver/jumpserver/assets/116717391/abea875e-f643-454e-9fc1-8f37f76aef43)

* 版本是最新的3.2.2，并且在/etc/ssh/ssh_config.d/新建了一个conf文件写进去也不行。

**Comment by LeeEirc** [comment]
可以列一下哪些 KexAlgorithms 属于安全漏洞吗？这里需要修改下 koko 代码解决。参考 [koko 代码](https://github.com/jumpserver/koko/blob/dev/pkg/sshd/server.go#LL74C55-L74C55)

**Comment by Lihy6472** [comment]
* 目前漏扫报告列出了两个：
```
diffie-hellman-group14-sha1
```

**Comment by LeeEirc** [comment]
参考 https://github.com/jumpserver/koko/pull/1097

**Comment by Lihy6472** [comment]
在server.go 内并没有找到漏扫扫到的两个算法，

![image](https://github.com/jumpserver/jumpserver/assets/116717391/07eff898-30d9-49cb-8ac4-82fa8376a3e0)

![image](https://github.com/jumpserver/jumpserver/assets/116717391/7db6775a-557d-443b-85db-2cf25da37c62)

**Comment by LeeEirc** [comment]
已经移除了，可以自己使用 dev 代码构建替换试试

**Comment by LeeEirc** [comment]
可等待下个版本发布，dev 已经移除
```
diffie-hellman-group14-sha1
diffie-hellman-group14-sha256
```

**Comment by Lihy6472** [comment]
* make docker报错提示这个

![image](https://github.com/jumpserver/jumpserver/assets/116717391/0e838949-7fed-4e71-b677-4cbec7994f70)

* 新版本需要什么时间发布呢？
