### ISSUE TITLE
[Feature] 命令过滤器 资产名称或 IP 设置能否支持正则表达式或资产节点的筛选

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#10467]
**请描述您的需求或者改进建议.**
命令过滤器 资产名称或 IP 设置能否支持正则表达式或资产节点的筛选，都用逗号拼接不太直观且不便于维护
且数据库资产和Linux资产可能是相同的 IP，能让用户选择资产树节点也是不错的选择
![image](https://github.com/jumpserver/jumpserver/assets/89765365/f1830372-a44f-49b1-9088-38c7ba32737e)

**Comment by BaiJiangJie** [comment]
嗯，目前使用起来不是很优雅，计划会在 v3.4 版本中进行优化；

下面图片是大概的实现效果：

![image](https://github.com/jumpserver/jumpserver/assets/32935519/cce42065-ea9f-4f7a-a848-a65c094dc809)

![image](https://github.com/jumpserver/jumpserver/assets/32935519/74456b1f-0963-4e92-b5ca-67de8e7b3027)

**Comment by hzhfit2cloud** [comment]
太强啦👍🏻

**Comment by BaiJiangJie** [comment]
等到时候发布了 v3.4 可以尽快体验一下
