### ISSUE TITLE
[Bug] 资产添加了备注信息，在资产列表的搜索框搜索备注信息无法查到资产，但是在普通用户工作台资产页面可以搜索到

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [jumpserver/jumpserver#10478]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.1

**Bug 描述**
资产添加了备注信息，在资产列表的搜索框搜索备注信息无法查到资产，但是在普通用户工作台资产页面可以搜索到。

**Bug 重现步骤(有截图更好)**
1.给资产添加备注信息；
2.在资产列表右上角搜索框搜索备注信息无法查到对应资产；
3.切换到普通用户工作台，在“我的资产”页面搜索框搜索备注信息可以查到对应资产。

**Comment by BaiJiangJie** [comment]
新版本已支持。
