### ISSUE TITLE
[Question] mysql cli无法输入中文问题

### ISSUE THREAD

**Issue by jiangqinghuang** [jumpserver/jumpserver#10473]
**请描述您的问题.**
通过mysql 命令行去管理MySQL时，在SQL中无法入中文。
jumpServer版本：v3.2.2
![图片](https://github.com/jumpserver/jumpserver/assets/32115295/bde8ec73-a61c-47f8-be86-7b29c5a7bee5)

**Comment by BaiJiangJie** [comment]
这应该是和你 Linux 主机的 bash 环境有关系
