### ISSUE TITLE
这到底是什么问题，日志没有任何体现，你们能不能解决！！！

### ISSUE THREAD

**Issue by 3721518** [jumpserver/jumpserver#10474]
**请描述您的问题.**
jumper版本：2.28.8
部署方式：jmsctl install
截图如下：
![image](https://github.com/jumpserver/jumpserver/assets/68690637/5d9383aa-7937-4ddf-a8eb-62e9f246b71e)

**Comment by ibuler** [comment]
首先学会尊重

**Comment by 3721518** [comment]
> 首先学会尊重

尊重是相互的，你只是揣测了我的语义，说明我发的内容让你心里不舒服了，深表歉意，对不起。
但，我提的问题你连解决都不解决就给关掉了，是不是玩不起。

**Comment by 3721518** [comment]
我想说的是，这问题有一年多了吧，优化在哪里还是你们根本就不想优化，别人提的这个相关issue也不回答。我不知道你们是装清高还是自傲还是自负，希望你们坻坜前行！

**Comment by 3721518** [comment]
> 首先学会尊重

删除你的回答吧，累了。

**Comment by ibuler** [comment]
> > 首先学会尊重
> 
> 删除你的回答吧，累了。

以后不再处理你的任何问题，没有欠你
