### ISSUE TITLE
[Question] About feature remote and record

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#10482]
I have some question such as:
- What is the maximum number of sessions that can remote to the server at the same time?
- Does the number of remote sessions vary between remote types (rdp, ssh, web)?
- What is the maximum time the recording feature can record?
- Records stored locally are automatically deleted or not? If yes, how long will the record be deleted?
- On the interface, you can only review the record up to 3 months ago, so is there a way to review the previous video like 6 months ago?
- A 7-minute long record has a capacity of 51MB, a 48-minute record is only 92MB. So what factors does the record size mainly depend on?

Thank you

**Comment by BaiJiangJie** [comment]
![1101684753276_ pic](https://github.com/jumpserver/jumpserver/assets/32935519/c8583589-ce43-4d00-84cb-8c7a2b0270b7)

**Comment by tsukiazuma** [comment]
Thank you for your answer.
I have a question about remote feature. I can deploy remote web with Applets - https://kb.fit2cloud.com/?p=c207be97-6439-4d19-b228-4f1ac7da831e. However, in document tutorial there is mention of being able to remote apps - https://kb.fit2cloud.com/?p=114, but I don't find it in Jumpserver Communication.
![image](https://github.com/jumpserver/jumpserver/assets/75791054/a19a8aa1-b66f-4ed6-9ad1-73f2a8277a66)

Is it only available on Jumpserver Enterprise?

**Comment by BaiJiangJie** [comment]
I can see from your screenshot that you are using the v2 version, and the link describes the functions of the JumpServer v3 version.
`https://kb.fit2cloud.com/?p=c207be97-6439-4d19-b228-4f1ac7da831e`
`https://kb.fit2cloud.com/?p=114`


For remote applications, the v2 version has some flaws in its design. 

If you want to use remote applications, it is strongly recommended that you upgrade to the v3 version, because the v3 version has greatly improved the remote application functions.

**Comment by tsukiazuma** [comment]
Yeah, I am using Jumpserver Communication v3.1.0.
Above link document which I read to deploy remote applications.
And I want to ask is there a way to remote the application such as TightVNC, TeamView,... like document remote to Chrome.
Or it only deploy in Jumpserver Enterprise.

**Comment by BaiJiangJie** [comment]
Well, currently neither the Enterprise nor the Community editions support applications such as TightVNC and TeamView.

**Comment by tsukiazuma** [comment]
Oh that's unfortunate.

Thank you

**Comment by BaiJiangJie** [comment]
Oh You're welcome.
There will be an application market in the future. If you need it urgently, you can consider purchasing the enterprise version. There will be a remote application team to help you develop as soon as possible.

https://jumpserver.org/index-en.html
