### ISSUE TITLE
Ubuntu 20.02 就切换不了账号 估计就是sudo设置问题

### ISSUE THREAD

**Issue by davie89** [jumpserver/jumpserver#10481]
Ubuntu 20.02 就切换不了账号 估计就是sudo设置问题

**浏览器版本**
Ubuntu 20.02 就切换不了账号 估计就是sudo设置问题

**Bug 描述**
Ubuntu 20.02 就切换不了账号 估计就是sudo设置问题

**Bug 重现步骤(有截图更好)**
1.
Ubuntu 20.02  就不能切换
<img width="376" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10398440/372fce25-8997-46c6-910b-8d65ea304b5c">

2.
centos7。就可以切换
<img width="287" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10398440/ec170c6b-667b-4340-aa3d-e87324eed515">

目前version：jumpserver-installer-v3.2.2

**Comment by davie89** [comment]
version jumpserver-installer-v3.2.2

**Comment by davie89** [comment]
感觉应该是sudo 设置问题

**Comment by LeeEirc** [comment]
可以手动操作下 `su -` 命令切换 root 用户，截图看看，可能 KoKo 代填操作失败了。

**Comment by davie89** [comment]
> 可以手动操作下 `su -` 命令切换 root 用户，截图看看，可能 KoKo 代填操作失败了。

正常j加sudo 可以登录 <img width="279" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10398440/e819671b-1f23-42aa-9a46-d090b3b27f2b">

su - root 就是认证失败了，ubantu就是这样的

<img width="271" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10398440/005c3586-8da6-4b6d-8fe8-d3f76aeb6aae">

**Comment by davie89** [comment]
> 可以手动操作下 `su -` 命令切换 root 用户，截图看看，可能 KoKo 代填操作失败了。

能解决这个bug吗

**Comment by LeeEirc** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32626707/9dbb99a4-9fe4-43ff-9069-ba22a6de98f5)
![image](https://github.com/jumpserver/jumpserver/assets/32626707/85875cfa-2ac6-45d7-b004-f4a9531ea4c1)
正常可以用 su 吧。

**Comment by davie89** [comment]
> ![image](https://user-images.githubusercontent.com/32626707/239795412-9dbb99a4-9fe4-43ff-9069-ba22a6de98f5.png) ![image](https://user-images.githubusercontent.com/32626707/239795578-85875cfa-2ac6-45d7-b004-f4a9531ea4c1.png) 正常可以用 su 吧。

可以正常su

**Comment by LeeEirc** [comment]
> > ![image](https://user-images.githubusercontent.com/32626707/239795412-9dbb99a4-9fe4-43ff-9069-ba22a6de98f5.png) ![image](https://user-images.githubusercontent.com/32626707/239795578-85875cfa-2ac6-45d7-b004-f4a9531ea4c1.png) 正常可以用 su 吧。
> 
> 可以正常su

如果调整之后，切换 root 正常了吗？

**Comment by davie89** [comment]
> 

我测试下

**Comment by davie89** [comment]
还是普通账号可以登录，切换到root 不行，还是代填的问题，是否能把需要sudo 才能登录的系统类型单独拆分出来

**Comment by davie89** [comment]
<img width="537" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10398440/97d54630-5562-4341-8332-b3b76f212063">
我自己改了下模版好像也不行

**Comment by LeeEirc** [comment]
目前 `sudo su`  和 `su` 都是用的 `su - root` 切换。这个可以优化下，等下个版本吧。
