### ISSUE TITLE
[Bug] web页面账号推送 用户名过多会超出框限制

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#10485]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.2.2

**浏览器版本**
Edge 113.0

**Bug 描述**
web页面账号推送 用户名过多会超出框限制

**Bug 重现步骤(有截图更好)**
1.点击账号推送
2.用户名中输入很多用户，长度超过输入框
3.bug 复现
<img width="1553" alt="企业微信截图_60f4a2a8-7129-415a-93dd-89be493b35b5" src="https://github.com/jumpserver/jumpserver/assets/81400245/8fccda36-06f1-4245-b854-21663d268ffc">

**Comment by BaiJiangJie** [comment]
计划在 v3.4 版本中优化一下。

**Comment by BaiJiangJie** [comment]
新版本已解决。
