### ISSUE TITLE
jumpserver 0.5.0 创建Windows资产报错

### ISSUE THREAD

**Issue by 0whale0** [jumpserver/jumpserver#1049]
[jumpserver 0.5.0 创建Windows资产报错]

##### 使用版本
[0.5.0]

##### 问题复现步骤
创建Windows资产后点击 测试可连接性 后报错

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/37136826/37079505-d0d4c80e-221d-11e8-8ba6-4aa0f49b92ee.png)
![default](https://user-images.githubusercontent.com/37136826/37079730-922fcdfa-221e-11e8-8289-3dc3da1da2c3.png)

![default](https://user-images.githubusercontent.com/37136826/37079791-d1e0122a-221e-11e8-81e3-25081bf12c5d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
无法测试windows的连接性

**Comment by 0whale0** [comment]
账户也没推送过去，无法通过web连接
