### ISSUE TITLE
[Bug] xshell登录后不能完整显示主机名称和IP

### ISSUE THREAD

**Issue by 20has** [jumpserver/jumpserver#10491]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.2.2

**浏览器版本**

**Bug 描述**
v3版本堡垒机通过xshell连接2222端口后 登录界面 首行列字段是：  ID | 名称     | 地址     | 协议     | 平台     | 组织     | 备注
v2版本堡垒机通过xshell连接2222端口后 登录界面 首行列字段是：  ID | 主机名                                   | IP              | 备注

**Bug 重现步骤(有截图更好)**
我的环境是 1080P屏幕   xshell5  字体14号  显示有问题 
字体调整到12号 就可以显示完整了

**建议**
最好是可以自定义需要显示的列字段，因为协议 平台 组织字段对我没有意义，我最需要的是主机名称和IP。

**截图**
v3+字体14号 不正常的界面
![v3 +字体14号](https://github.com/jumpserver/jumpserver/assets/8327740/a4b5d080-ab1f-49df-b544-919931e01b32)

v2版本正常的界面
![v2](https://github.com/jumpserver/jumpserver/assets/8327740/20848f30-50e1-449a-ac4e-4f419cbb5942)

v3+字体10号字体 正常的界面
![v3+字体10号](https://github.com/jumpserver/jumpserver/assets/8327740/1bc7c4e0-1562-43be-ba0d-5439faa92ec3)

**Comment by BaiJiangJie** [comment]
计划在 v3.4 版本中优化一下。

**Comment by ivancxj** [comment]
最好可以自定义需要显示的列字段，默认的字段 【协议/平台/组织】 对我来说没用，我需要 【名称/ip/硬件信息】

**Comment by 20has** [comment]
我再记录下：
**操作记录**：

```
#下载包
cd /opt
wget https://resource.fit2cloud.com/jumpserver/installer/releases/download/v3.4.0/jumpserver-installer-v3.4.0.tar.gz
tar -xf jumpserver-installer-v3.4.0.tar.gz
cd jumpserver-installer-v3.4.0

#升级
./jmsctl.sh upgrade

# 启动 JumpServer 服务
./jmsctl.sh start
```

**调整下参数**
```

#修改配置文件参数
cat <<\EOF>>/opt/jumpserver/config/config.txt
#2023年4月13日17:48:07  navicat直连数据库 修改 协议访问的时候 过期时间为 1年  默认是200s
CONNECTION_TOKEN_EXPIRATION=31536000
#2023年06月21日11:41:29 xshell界面 只显示字段   ID | 名称 | 地址 | 备注
HIDDEN_FIELDS=protocols,platform,organization
EOF

#重启堡垒机容器 生效
jmsctl restart
```

**效果图**
![Snipaste_2023-06-21_11-50-10](https://github.com/jumpserver/jumpserver/assets/8327740/6d7c070c-d281-464b-bbf6-40b81fe53ef9)
