### ISSUE TITLE
[Bug] JS V3.2.2开源版本配置资产时，添加SSH密钥的账号,点击提交时会报错

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#10504]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.2.2

**浏览器版本**

**Bug 描述**
用户在子产品配置了ssh密钥后，在资产上添加ssh密钥类型的账号，并且填写了ssh密钥密码，点击提交会报错Server Error，无法正常添加ssh密钥的用户。
![fa1c4d77d674bf2e0f0d5779510e273](https://github.com/jumpserver/jumpserver/assets/47737772/fe51dcb1-4f7a-4bfd-ae65-35490a66c8e0)
查看后台日志，发现报错：
![0e5133ff29f1fd5ada495d9747755d8](https://github.com/jumpserver/jumpserver/assets/47737772/9d83dfa4-7a79-4a6b-937c-4272825b1188)

**Comment by BaiJiangJie** [comment]
v3.3.0 修复了。

**Comment by blooze123** [comment]
好的，感谢！！
