### ISSUE TITLE
[Question] jumpserver能否支持以awscli的形式获取AWS EKS登录token

### ISSUE THREAD

**Issue by SC-zj** [jumpserver/jumpserver#10505]
通过手动调用awscli获取的EKS登录token有效期只有8h，使用起来很麻烦，能不能通过配置awscli动态获取EKS登录token

**Comment by BaiJiangJie** [comment]
可以详细描述一下使用场景，或者站在用户使用的角度描述一下，理想中 JumpServer 产品应该如何呈现这个功能。

_因为目前对于 awscli 获取 EKS token 的方式和真实的使用场景都不是很熟悉。_

**Comment by SC-zj** [comment]
目前我自己的运维电脑是通过aws的命令行工具awscli命令` aws eks update-kubeconfig --name your-cluster-name`这个命令得到.kube/config的更新。我看过.kube/config文件，里面是eks的certificate信息和aws iam arn信息（应该是每次登录通过命令行工具awscli请求一个最新的token）。可以看下面的截图，实际就是一个具体命令`aws --region us-west-1 eks get-token --cluster-name xxxxx`
<img width="650" alt="image" src="https://github.com/jumpserver/jumpserver/assets/70679694/4943b300-72a7-4a6a-89e2-24a72acac673">

**Comment by BaiJiangJie** [comment]
也就是每次登录 aws k8s 前，使用 `aws eks update-kubeconfig --name your-cluster-name` 命令更新一下最新的 token，然后再使用这个 token 进行登录？

现在不方便的地方是，你需要每次手动生成这个 token，然后手动更新到账号密码中才能登录。

这样理解对吗？

**Comment by SC-zj** [comment]
是的，如果用jumpserver来登录aws k8s的话我需要每次动生成这个 token，然后手动更新到账号密码中才能登录。
我自己电脑里面装了awscli工具不需要我手动登录，k8s工具kubectl会自动去调用awscli生成最新的token（因为kubectl的配置文件中配置的就是调用awscli命令）。

**Comment by SC-zj** [comment]
所以jumpserver能不能增加对AWS相关SDK的支持（Linux命令行工具有awscli，也有python等各语言版本的sdk。python的库叫Boto）。

**Comment by BaiJiangJie** [comment]
有一个问题是什么场景下会需要使用动态 token 去登录，目前遇到的用户大多数还是静态 token。

**Comment by SC-zj** [comment]
我问过aws的人，他们的静态 token有效期最长12h。要是有效期能有个几个月我也不问你们了。

**Comment by BaiJiangJie** [comment]
那在调用命令生成新 token 的时候得保证当前 token 还在有效期内，如果登录时做这个动作，那就不能保证旧 token 还有效（因为用户登录 k8s 的时间是不确定的）

**Comment by BaiJiangJie** [comment]
aws 最大有效期是 12h，应该是出于安全角度考虑。
所以在 JumpServer 中资产账号可以修改为手动登录，每次登录前手动生成一下token，登录是填入，就不用每次更新账号的密码了。

**Comment by SC-zj** [comment]
1.生成新 token，旧token并不会失效。我们Jenkins做cicd就是用了相关工具在每一个job里面动态获取k8s的凭证的，没有影响
2.aws可以给服务器赋予角色，只要服务器有权限就可以调用aws的sdk获取相应的凭证那就不需要输入aksk。那jumpserver能否做到网关上安装了kubectl和aws相关sdk，然后通过这个网关去连到k8s呢？

**Comment by BaiJiangJie** [comment]
哦，大概明白了，AWS 给服务器赋予角色，对`对象存储服务`来讲可以使用免密登录，对于 `EKS` 来说应该是可以免密获取 认证 Token。

对于 JumpServer 来讲，这样的方式涉及到安全问题，暂时不考虑支持。

**Comment by mjwtc0722** [comment]
> 

自己写个定时任务，通过API去更新jumpserver上的token

**Comment by SC-zj** [comment]
好吧
