### ISSUE TITLE
[Bug] 资产树节点不显示资产授权规则

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#10509]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.0

**浏览器版本**
Chrome 版本 113.0.5672.93（正式版本） （64 位）

**Bug 描述**
资产授权页面，点击资产树节点时不显示授权规则，需要点击某一资产，才显示授权规则。

**Bug 重现步骤(有截图更好)**
1.点击资产树节点
![image](https://github.com/jumpserver/jumpserver/assets/32380085/b38fc13a-fbe2-409b-84e6-040497e581f3)

2.点击资产
![image](https://github.com/jumpserver/jumpserver/assets/32380085/a96171ba-3a8f-410a-815c-4c6d7c659d06)

**Comment by BaiJiangJie** [comment]
资产授权的显示逻辑

1. 点击节点，右侧会显示直接授权该节点和所有父级节点的授权规则；（不会显示节点下资产关联的授权规则）
2. 点击资产，右侧会显示直接授权该资产和所有父级节点的授权规则；
