### ISSUE TITLE
[Question] v3.3.0 帐号推送如何指定home目录

### ISSUE THREAD

**Issue by c342ng** [jumpserver/jumpserver#10508]
版本：v3.3.0
 帐号推送时，如何指定home目录
<img width="1018" alt="image" src="https://github.com/jumpserver/jumpserver/assets/5120942/2718afb5-ce8c-4455-9bb2-a2bd19c5bb5d">

**Comment by BaiJiangJie** [comment]
目前版本不支持指定推送的 home 目录，默认为 /home/{username} 目录；

**Comment by jym503558564** [comment]
升级至最新版本，可支持了
