### ISSUE TITLE
[Feature] Azure Active Directory登陆集成

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#10514]
**请描述您的需求或者改进建议.**
当前有集成[Azure Active Directory](https://azure.microsoft.com/en-us/products/active-directory/) 登陆吗？

**Comment by louishot** [comment]
https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/auth-saml
这个saml兼容吗

**Comment by BaiJiangJie** [comment]
AD username/password 方式开源版支持；

AD auth-saml 方式企业版支持；
