### ISSUE TITLE
web端连接资产mysql fail.error: Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.

### ISSUE THREAD

**Issue by niuqiqi** [jumpserver/jumpserver#10537]
[**
保存：(error: Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON.)
是否需要配置SSL证书，如何配置？
.**]

**Comment by BaiJiangJie** [comment]
MySQL 暂时不支持，将来会考虑支持。

**Comment by BaiJiangJie** [comment]
最新版本已支持。
