### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by lijialin-code** [jumpserver/jumpserver#10532]
**请描述您的问题.**
jumpserver版本：Version v2.25.0 GPLv3
执行批量命令报错
Unable to execute ssh command line on a controller due to: [Errno 2] No such file or directory: b'ssh'

**Comment by wojiushixiaobai** [comment]
没安装 openssh-client ？

**Comment by jym503558564** [comment]
该问题还存在吗？由于长时间未收到反馈，我们将关闭该Issues，如还有问题可在提Issues。
