### ISSUE TITLE
关于使用脚本进行密码代填的问题

### ISSUE THREAD

**Issue by freedomxlp** [jumpserver/jumpserver#10533]
关于登录时需要跳转页面的website账号代填请问是否有脚本模板
流程是 填写账号，点击按钮，填写密码，点击按钮    完成登录
![账号](https://github.com/jumpserver/jumpserver/assets/63400238/7e5addba-b5e1-4f1d-b630-27a61522dd0f)
![密码](https://github.com/jumpserver/jumpserver/assets/63400238/88607b5b-f1ed-45f8-86ea-c2c5dcd4bd67)

**Comment by ibuler** [comment]
这个属于高级代填了，需要使用脚本来完成，脚本是 selenium 语法

**Comment by freedomxlp** [comment]
> 这个属于高级代填了，需要使用脚本来完成，脚本是 selenium 语法

那脚本中如何引用在jumpserver里登记的用户名和密码

**Comment by ibuler** [comment]
> > 这个属于高级代填了，需要使用脚本来完成，脚本是 selenium 语法
> 
> 那脚本中如何引用在jumpserver里登记的用户名和密码

我们正在整理到 知识库 中，稍后回复

**Comment by ibuler** [comment]
```
[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "name=accessKey",
    "command": "type"
  },
  {
    "step": 2,
    "value": "{SECRET}",
    "target": "name=secretKey",
    "command": "type"
  },
  {
    "step": 3,
    "value": "",
    "target": "id=do-login",
    "command": "click"
  }
]

```
