### ISSUE TITLE
[Bug] 使用JumpServer进行remoteAPP发布chrome应用，连接后闪退。

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#10549]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.3.0

**浏览器版本**
chrome

**Bug 描述**
用户使用window2016作为remoteAPP发布机,发布机部署和chrome发布都正常。配置remoteAPP资产和资产授权也正常，并且该网站也能正常通过chrome进入。但是通过终端登录后，会出现连接上window后，立刻闪退。

**Bug 重现步骤(有截图更好)**
1.window发布机配置截图：
![c81103c9adba93f5331c0f4c2374f8d1_](https://github.com/jumpserver/jumpserver/assets/47737772/3df56ce0-30ce-44e5-a9c2-e396593a430f)
![90cc0d0e862170085de539862d7f9dd6_](https://github.com/jumpserver/jumpserver/assets/47737772/d76f5bcb-9143-4119-bac2-c7adc4070011)

2.remoteAPP资产和资产授权截图：
![e745d12f015ac0460be4e1dc0df981aa_](https://github.com/jumpserver/jumpserver/assets/47737772/e75beb0f-45fc-4ed0-9f75-62da01440e7c)
![e481c305668ff89d05c9b8587d56b2a8_](https://github.com/jumpserver/jumpserver/assets/47737772/883b4e52-dc4a-408b-b85e-30ed85931073)
![fff2b93c30c7c8008c0662cf92d96a54_](https://github.com/jumpserver/jumpserver/assets/47737772/b0685553-1dcd-4d34-895a-048fca9c4f59)
![8229087cf91f483da7b2fa8bcfb0ed0f_](https://github.com/jumpserver/jumpserver/assets/47737772/73bd5a45-7ea2-4a42-bad1-d676a699ee31)
3.用终端登录后，会先显示连接成功，在任务管理器也能显示已经连接上的用户，然后一两秒后就黑屏了，截图：
![e536c8bf210b5392175880f79b267abc_](https://github.com/jumpserver/jumpserver/assets/47737772/6a12d0c2-6d28-4b64-9bbe-dc852029507a)
![589aceb9c73f749a7b9f4ce0dfccccfa_](https://github.com/jumpserver/jumpserver/assets/47737772/79c51ff8-8b60-4e0c-8243-b5150ab45271)

**Comment by BaiJiangJie** [comment]
每次都会闪退吗？

或者把任务管理器中 js_luochengbin 的进程注销掉再登录呢？

**Comment by blooze123** [comment]
每次都闪退。注销进程再登录也一样。好像是v3.3的bug&nbsp;


明天，你好
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月26日(星期五) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Bug] 使用JumpServer进行remoteAPP发布chrome应用，连接后闪退。 (Issue #10549)





 
每次都会闪退吗？
 
或者把任务管理器中 js_luochengbin 的进程注销掉再登录呢？

**Comment by wojiushixiaobai** [comment]
- Link: #10555

**Comment by BaiJiangJie** [comment]
等 v3.3.1 发布之后，重新初始化部署一下发布机器就可以了。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v3.3.1

<img width="2558" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f10b4760-8b3f-4dec-84e1-0a0def470ac2">

**Comment by wellsyu** [comment]
同样的情况，升级后还是一样的

**Comment by jumping008** [comment]
请问这个问题由什么结论了么，我这边也遇到相同的情况，之前是好的，今天突然不行了

**Comment by BaiJiangJie** [comment]
看看发布机的环境变量

![image](https://github.com/jumpserver/jumpserver/assets/32935519/3c64a71f-2c06-4438-b27a-9ee8c128ed6f)


手动打开 PATH 下的 Chrome 看看是不是能正常启动？

**Comment by BaiJiangJie** [comment]
新版本已解决。
