### ISSUE TITLE
[Question] 华为防火墙无法使用远程应用发布代填

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10553]
**请描述您的问题.**
华为防火墙无法使用远程应用发布代填，错误截图如下：
![e09263c9d4715c1b81711578b61df06](https://github.com/jumpserver/jumpserver/assets/63082453/eb1ca854-7e36-4b02-b31d-f1067e737549)
是否有相关的解决办法？好像是因为：华为防火墙web页面把元素进行了隐藏，所以堡垒机就没办法实现代填。web页面密码填充代码如下：
![e8ed3e4f79a1c67aa5bcea355be96d5](https://github.com/jumpserver/jumpserver/assets/63082453/deee9ea6-159c-43bf-8ee6-32ea9f931480)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10378

这个 issue 里正在讨论，目前还没解决，正在寻找解决方案。

**Comment by qianyu-0712** [comment]
[ { "step": 1, "value": "{USERNAME}", "target": "id=username", "command": "type" }, { "step": 2, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[5]/div[1]/input", "command": "click" }, { "step": 3, "value": "{SECRET}", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[4]/div[1]/input", "command": "type" }, { "step": 4, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[1]/table/tbody/tr/td", "command": "click" } ]
用这个脚本解决的

**Comment by iderfu** [comment]
> [ { "step": 1, "value": "{USERNAME}", "target": "id=username", "command": "type" }, { "step": 2, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[5]/div[1]/input", "command": "click" }, { "step": 3, "value": "{SECRET}", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[4]/div[1]/input", "command": "type" }, { "step": 4, "value": "", "target": "XPath=/html/body/div[1]/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[1]/table/tbody/tr/td", "command": "click" } ] 用这个脚本解决的


请教一下，我的这边看到的XPath分别对应的是

2
/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[4]/div[1]/input
3
/html/body/div[1]/div[4]/div/div/div[1]/div/form/div[6]/div[1]/input
4
/html/body/div[1]/div[4]/div/div/div[2]/div/div/table/tbody/tr/td[1]/table

按代码模板填进去之后，还是不行的

华为设备是USG6315E-ac
系统版本信息是USG6300E V600R007C20SPC500

看到你的XPath值跟我的不一致，想看看是不是系统版本不一致，所以值不一样

**Comment by qianyu-0712** [comment]
不要坐任何改动，你试试，直接复制粘贴我的。

**Comment by iderfu** [comment]
> 不要坐任何改动，你试试，直接复制粘贴我的。

![image](https://github.com/jumpserver/jumpserver/assets/132550149/55ef18aa-2f31-4f0c-990e-3218e6cadd5a)

用你的复制进去就直接只能代填用户名，密码代填失败了，也不能直接登录

**Comment by chenyc2021** [comment]
> > 不要坐任何改动，你试试，直接复制粘贴我的。
> 
> ![image](https://user-images.githubusercontent.com/132550149/241614129-55ef18aa-2f31-4f0c-990e-3218e6cadd5a.png)
> 
> 用你的复制进去就直接只能代填用户名，密码代填失败了，也不能直接登录

我这边用@qianyu-0712的脚本完全没问题，应该是可以的
