### ISSUE TITLE
推送资产报错Permission denied ().", "unreachable": true

### ISSUE THREAD

**Issue by 15377643091** [jumpserver/jumpserver#10566]
这个是突然产生的，之前推送和链接都是正常的，今天突然出现多台资产推送权限拒绝
[\r\nqingteng@10.10.188.70: Permission denied ().", "unreachable": true](fatal: [node8]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '10.10.188.70' (ECDSA) to the list of known hosts.\r\nqingteng@10.10.188.70: Permission denied ().", "unreachable": true})
防火墙和selinux都关闭了，也对比了正常推送的资产，都是一样的配置

**Comment by BaiJiangJie** [comment]
机器上有做过什么变更吗？

**Comment by BaiJiangJie** [comment]
升级到最新版本解决。
