### ISSUE TITLE
[Bug] 修改k8s资产端口号，提交后会变成80

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#10562]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
110.0.5481.177

**Bug 描述**
修改k8s资产端口，提交后端口号会变成80

**Bug 重现步骤(有截图更好)**
1.修改k8s资产端口并提交，提示更新成功
![image](https://github.com/jumpserver/jumpserver/assets/89773363/038360c3-9af2-4d57-a48d-07250e1d922b)

2.点击资产名称，协议组端口号显示80
![image](https://github.com/jumpserver/jumpserver/assets/89773363/1640d89e-6681-4732-95bf-914922b729f8)

3.点击资产更新按钮，端口号显示80
![image](https://github.com/jumpserver/jumpserver/assets/89773363/b702c986-5adb-4194-8cfc-2ae3d7a6c61b)

**Comment by BaiJiangJie** [comment]
前端有 Bug，v3.3.1 上会修复。

https://github.com/jumpserver/lina/pull/3156

**Comment by BaiJiangJie** [comment]
最新版本已修复。
