### ISSUE TITLE
应用发布机chrome部署异常；希望增加edge选项(winserver 2022)[Bug] 

### ISSUE THREAD

**Issue by win9zhanhuaxi0ng** [jumpserver/jumpserver#10569]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.0社区版本

**浏览器版本**
edge最新

**Bug 描述**
应用发布机为winserver 2022，内置chromium内核的edge，配置了RemoteApp后创建Web资产，按照教程部署后无法打开
经排查，是应用发布机无chrome导致，手动安装chrome才可以正常打开Web资产。

建议：
winserver 2022 自带edge，可以在应用发布机里面内置edge吗？或者说部署的时候把chrome完整的部署上去

**Comment by BaiJiangJie** [comment]
远程应用要支持 edge 的话，需要单独开发。

或者你也可以研究一下贡献一个 Edge 远程应用。

Chrome 是内置的远程应用，初始化部署发布机时会默认安装上。

**Comment by jym503558564** [comment]
可以查看我们应用市场已支持的应用：https://apps.fit2cloud.com/jumpserver
如还未支持的应用，欢迎贡献。
