### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10573]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**浏览器版本**
远程应用服务器自带chrome

**Bug 描述**
在交换机上使用acl限制IP登录， 放行了堡垒机IP，放行了远程应用发布机IP，但是无法进行正常访问。而直接在远程应用发布机上访问则是正常的。通过堡垒机的web跳转就是异常，是否中间发生了源地址转换？

**Bug 重现步骤(有截图更好)**
1.配置远程应用发布
2.在H3C S5024配置基础acl（序号为2001-2999）不是高级acl
3.在远程应用发布机测试，正常访问
4.在堡垒机web终端测试不能访问
注：锐捷也有类似的情况，不过锐捷关闭了禁止内部ip登录就恢复了正常。

**Comment by wojiushixiaobai** [comment]
通过容器 NAT 出去的，你可以尝试抓包看看。
或者在 koko 容器里面手动 telnet 测试下
```
docker exec -it jms_koko bash
telnet 
```

**Comment by datutu58888** [comment]
> 通过容器 NAT 出去的，你可以尝试抓包看看。 或者在 koko 容器里面手动 telnet 测试下
> 
> ```
> docker exec -it jms_koko bash
> telnet 
> ```
老板我这里提示
web cli 提示界面
Connecting to 接入设备(admin)@10.10.47.26 14.9
Connecting to 接入设备(admin)@10.10.47.26 error: telnet: handshake failed: read tcp 192.168.250.8:46686->10.10.47.26:23: use of closed network connection
Receive Connection closed
Connection websocket closed


koko测试界面
![image](https://github.com/jumpserver/jumpserver/assets/138114577/88e132fb-345e-431e-9b53-5fd8e9d23483)

难道我telnet 正则表达式没写的缘故?  如果要写，写什么?

**Comment by BaiJiangJie** [comment]
使用最新版本再试试，如果还有问题 Reopen。

**Comment by datutu58888** [comment]
最新版本如何升级哟？



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 16, 2023 15:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jumpserver/jumpserver] [Bug]  (Issue #10573)




 
使用最新版本再试试，如果还有问题 Reopen。
