### ISSUE TITLE
[Bug] 剪切板中文乱码

### ISSUE THREAD

**Issue by yiqikeji17** [jumpserver/jumpserver#10575]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer v3.3.0

**浏览器版本**
chrome

**Bug 描述**
web VNC远程桌面使用剪切板中文乱码，能否通过转码解决一下该问题。
如python使用该函数转码，text.encode('gbk').decode('latin-1')

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ahaitodo** [comment]
对，这个问题也困扰我好久了，不然要通过第三方传中文比较麻烦。

**Comment by BaiJiangJie** [comment]
嗯，后面复现一下定位一下问题，看看怎么处理。
@jym503558564 @LeeEirc

**Comment by jym503558564** [comment]
已复现，待修复。

**Comment by LeeEirc** [comment]
原生 guacamole 也有类似的问题，暂时不好处理。
可参考下这个文章[Guacamole VNC剪切板乱码](https://blog.csdn.net/qq_36577699/article/details/124544661)
