### ISSUE TITLE
[Question] About remote web on Jumpserver

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#10572]
When I remote web on Jumpserver, if I click on Minimize by mistake and the window is hidden
How can I do to show it back.

Thank you

**Comment by BaiJiangJie** [comment]
I tested using Option + Shift to switch back (I use a MacBook Pro).

In the v3.4 version, we will hide the address bar and the minimize button, etc., on the one hand for safety, and on the other hand to avoid troubles caused by other operations of the user.

**Comment by BaiJiangJie** [comment]
You can try it.
