### ISSUE TITLE
web连接Windows报错

### ISSUE THREAD

**Issue by 0whale0** [jumpserver/jumpserver#1057]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
web连接Windows时报错报错

##### 具体表现[截图可能会更好些,最好能截全]
03:04:39.051 [http-apr-8080-exec-3] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:{code:200,result:{"id":"ee294baa-35a0-4933-8921-8f7e7039da15","username":"admin","name":"Administrator","email":"admin@mycomany.com","is_active":true,"is_superuser":true,"role":"管理员","groups":["Default"],"wechat":"","phone":null,"comment":"","date_expired":"2088-02-18 04:39:49"}}
03:04:39.079 [http-apr-8080-exec-3] INFO  o.a.g.a.j.p.JumpserverPermissionService - validatePermission:{code:200,result:{"msg":true}}
03:04:39.105 [http-apr-8080-exec-3] INFO  o.a.g.a.j.p.JumpserverPermissionService - getAsset:{code:200,result:{"id":"aec1a3c8-8391-4f8e-a648-653f53c0d117","ip":"172.31.101.111","hostname":"win-test1","port":3389,"is_active":true,"public_ip":null,"number":null,"vendor":null,"model":null,"sn":null,"cpu_model":null,"cpu_count":null,"cpu_cores":null,"memory":null,"disk_total":null,"disk_info":null,"platform":"Windows","os":null,"os_version":null,"os_arch":null,"hostname_raw":null,"created_by":null,"date_created":"2018-03-08 02:43:45 +0000","comment":"","admin_user":"7f21b3d0-30aa-4d2c-9997-394e3cea2ef6","nodes":["aac9562d-3823-4e7e-ac91-4c1192d9724d"],"labels":[],"hardware_info":"","is_connective":true}}
03:04:39.115 [http-apr-8080-exec-3] INFO  o.a.g.a.j.p.JumpserverPermissionService - getSystemUser:{code:200,result:{"id":"8c2d150e-cafe-41e7-9f62-4100bf5a950a","name":"lzh2","username":"lzh","password":"abc@123","private_key":null}}
03:04:39.116 [http-apr-8080-exec-3] INFO  o.a.g.r.auth.AuthenticationService - User "Administrator" successfully authenticated from [172.31.101.2, 172.17.0.1].
03:04:40.248 [http-apr-8080-exec-2] INFO  o.a.g.tunnel.TunnelRequestService - Connection "win-test1" does not exist for user "Administrator".
03:04:40.248 [http-apr-8080-exec-2] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: Requested connection is not authorized.
03:04:40.383 [http-apr-8080-exec-7] INFO  o.a.g.tunnel.TunnelRequestService - Connection "win-test1" does not exist for user "Administrator".
03:04:40.383 [http-apr-8080-exec-7] WARN  o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request rejected: Requested connection is not authorized.

![default](https://user-images.githubusercontent.com/37136826/37130958-05dafbba-22c1-11e8-98d0-2e23f8e63975.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
请参阅faq  docs.jumpserver.org/zh/docs/faq.html#faq
