### ISSUE TITLE
[Bug] 命令过滤功能在数据库的远程应用连接方式中无法拒绝执行

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10586]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.3.0

**Bug 描述**
命令过滤功能在数据库的远程应用连接方式中无法拒绝执行

**Bug 重现步骤(有截图更好)**
1. 命令过滤配置
![image](https://github.com/jumpserver/jumpserver/assets/54871762/a3bd11da-5275-47a9-b1db-f3750665c1ec)

2. 客户端连接正常拒绝
![image](https://github.com/jumpserver/jumpserver/assets/54871762/a4cb545d-86ed-4405-8d88-fdaa3087b56c)

3. web gui 正常拒绝
![image](https://github.com/jumpserver/jumpserver/assets/54871762/937b58e2-a99c-4cf9-ac1c-28d404eb27ed)

4. 远程应用dbeaver可以通过
![image](https://github.com/jumpserver/jumpserver/assets/54871762/c96d6112-916d-42f2-bc60-551e73ce6cfb)

**Comment by BaiJiangJie** [comment]
对的，远程应用方式都不支持命令记录、命令过滤；
