### ISSUE TITLE
[Feature] 对于ssh和rdp连接协议加一个提示有哪些人正在使用该账号，在建立连接后使用web gui模式时也显示当前正在使用的人

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10587]
对于ssh和rdp连接协议加一个提示有哪些人正在使用该账号，在建立连接后使用web gui模式时也显示当前正在使用的人
1. ssh：防止因为不知道其他人也在使用该资源导致的操作冲突
2. rdp：防止在不知情的情况下将正在使用的人给顶掉

**Comment by BaiJiangJie** [comment]
<img width="912" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/604a9cea-fc31-43d1-a767-241143dcc9a9">

**Comment by BaiJiangJie** [comment]
类似于这样的提示吗？

大多数情况下，每个人连接资产的账号会不一样吧？（除了管理员之间）

**Comment by BaiJiangJie** [comment]
好的，目前分析下来这个功能还是比较合理的，不过会根据用户需求量来进行排期。

正好借此机会，希望你能在社区群里或者 Issue 里问问我们的广大用户，大家是否也有遇到类似的问题，
如果用户量比较多的话，我们就提高优先级，优先处理。

**Comment by pika-FENG** [comment]
同求~我们所有资产都是以应用简称创建的账号，没有根据使用人创建账号，所以都是共用情况

**Comment by BaiJiangJie** [comment]
Web Terminal 连接资产的弹窗页面显示账号的使用情况，连接进去之后就不显示了。

**Comment by BaiJiangJie** [comment]
> 

用户、资产、账号的规模是不是比较少？

**Comment by BaiJiangJie** [comment]
> 同求~我们所有资产都是以应用简称创建的账号，没有根据使用人创建账号，所以都是共用情况

用户、资产、账号的规模是不是比较少？

**Comment by pika-FENG** [comment]
> > 同求~我们所有资产都是以应用简称创建的账号，没有根据使用人创建账号，所以都是共用情况
> 
> 用户、资产、账号的规模是不是比较少？

用户50+，资产400+，账号900+

**Comment by BaiJiangJie** [comment]
规模其实还可以啊，不算很少。

**Comment by saszhuqing** [comment]
> 是类似这样的提示 主要是用于只能用一个账号的场合，win10通常只能一个用户登录。然后使用vpn连接客户现场，vpn只有一个，也就只能用一个账号。

win10 可以用这个软件开启多用户登录功能，很稳定。https://github.com/stascorp/rdpwrap

**Comment by BaiJiangJie** [comment]
后面版本找个合适的机会，支持一下。

**Comment by ibuler** [comment]
已提交到 dev

![image](https://github.com/jumpserver/jumpserver/assets/17382885/bb0fb8ac-378c-4205-9667-ebf6ae30809b)
