### ISSUE TITLE
[Bug] 通过远程应用连接数据库没有走网关

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10588]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.3.0

**Bug 描述**
通过远程应用dbeaver连接数据库没有走网关，导致远程应用无法连接云环境内部数据库，建议远程应用dbeaver直接使用代理配置连接数据库

**Comment by MAOUXSAKI** [comment]
如果这样修改需要注意代理oracle时，不支持thin驱动的问题

**Comment by BaiJiangJie** [comment]
好的，目前还不支持远程应用方式通过网关连接数据库资产，后面版本考虑支持一下。

**Comment by MAOUXSAKI** [comment]
我看3.4的更新中已经说支持了，怎么启动呢，我直接用dbeaver连接还是连不了 @BaiJiangJie

**Comment by LeeEirc** [comment]
重新初始化发布机，更新 Tinker 服务 和 dbeaver 版本。

**Comment by LeeEirc** [comment]
v3.4.0 已发布，dbeaver 已经支持网关，有问题新开 issue。
