### ISSUE TITLE
[Question] 源码部署架构，修改密码登录页面报错

### ISSUE THREAD

**Issue by linmumu0205** [jumpserver/jumpserver#10590]
在pycharm安装部署好jumpserve api服务器后，安装调试好lina组件后，进入jumpserver登录界面修改密码后再访问，网页刷新不出来。打开dev-tools看到  error |  _callee$ |  TypeError: Cannot read properties of undefined  (reading 'filter')错误，这个是什么问题呢？

**Comment by BaiJiangJie** [comment]
截图看一下呢？应该是有一些值没有返回回去。

**Comment by BaiJiangJie** [comment]
看看是前端哪一行报出来错。

**Comment by BaiJiangJie** [comment]
看一下 profile 的 API 返回数据

**Comment by linmumu0205** [comment]
![BA42ED2E-B02F-40EE-B6D6-36B7B7CC4E53](https://github.com/jumpserver/jumpserver/assets/92515192/569a8a64-80a6-47b1-894a-ff448d87a488)
api返回信息如下 这个set prpfile哪个目录下呢 我这种情况改怎么解决呢

**Comment by BaiJiangJie** [comment]
<img width="1431" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/dfb9b396-2f11-4f6b-bda0-094b77e86a74">

**Comment by BaiJiangJie** [comment]
这要看看是什么原因没有返回才知道如何解决，正常应该不会有这样的情况。

**Comment by BaiJiangJie** [comment]
上面的描述中，还是没有看到 API 返回的信息啊？
