### ISSUE TITLE
[Feature] shell终端登录界面显示的列字段需要自定义功能

### ISSUE THREAD

**Issue by ivancxj** [jumpserver/jumpserver#10606]
**请描述您的需求或者改进建议.**
目前终端登录默认的列字段是：
ID 名称 地址 协议 平台 组织 备注
![image](https://github.com/jumpserver/jumpserver/assets/2024637/dedc7d6b-277a-4440-8a8a-9e75f7c9f3bc)

实际上，部分列字段对我来说是没用的（并且我想要硬件信息列字段），所以希望官方支持下自定义列字段！

**Comment by BaiJiangJie** [comment]
v3.4 版本会支持对 “资产名称、资产地址、协议、平台、组织、备注” 字段的显示控制（在配置文件中，全局所有用户生效）；

如果要做用户个人自定义配置，需要新增用户个人设置的模块，目前计划 v3.5+ 支持。

**Comment by LeeEirc** [comment]
@BaiJiangJie   “资产名称、资产地址、备注” 这些是必须显示的字段

**Comment by BaiJiangJie** [comment]
@BaiJiangJie

**Comment by ivancxj** [comment]
> v3.4 版本会支持对 “资产名称、资产地址、协议、平台、组织、备注” 字段的显示控制（在配置文件中，全局所有用户生效）；
> 
> 如果要做用户个人自定义配置，需要新增用户个人设置的模块，目前计划 v3.5+ 支持。

非常期待！那v3.4 版本是啥时候发布

**Comment by BaiJiangJie** [comment]
v3.4 计划 06.15 发布。

**Comment by LeeEirc** [comment]
config.txt 中添加以下配置
```
HIDDEN_FIELDS=protocols,platform,organization
```

**Comment by LeeEirc** [comment]
已经发布 v3.4.0。

**Comment by luweijun1992** [comment]
> config.txt 中添加以下配置
> 
> ```
> HIDDEN_FIELDS=protocols,platform,organization
> ```

在管理页面上进行配置不是更好，使用配置文件的话很多从老版本升级上来的配置文件中应该不存在这些新版本增加的参数吧。
