### ISSUE TITLE
[Feature] web CLI方式访问资产控制复制粘贴的权限

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#10607]
**请描述您的需求或者改进建议.**
资产授权时能否控制通过 web CLI方式访问linux资产的复制粘贴的权限
![image](https://github.com/jumpserver/jumpserver/assets/122069934/e99d6c1f-4754-4903-b86b-89c8d71bf125)

**Comment by BaiJiangJie** [comment]
Web CLI 复制粘贴目前控制不了。
