### ISSUE TITLE
[Question] 源码调试celery 断点不生效

### ISSUE THREAD

**Issue by catdiscus** [jumpserver/jumpserver#10605]
**请描述您的问题.**
使用 pycharm 调试 celery,调试配置为
<img width="718" alt="image" src="https://github.com/jumpserver/jumpserver/assets/103556820/90192a2d-b65a-4a8e-8efb-e1097428a1fa">
断点不生效,请问如何正确配置?

**Comment by BaiJiangJie** [comment]
使用 celery 命令启动，我用的是 IntelliJ IDEA，你用 PyCharm 参考一下，主要是启动参数。

`-A ops worker -P threads -l INFO -c 10 -Q celery,ansible -n celery@%h --without-mingle`

<img width="1036" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fb047f3e-e701-4df1-8829-80c3ef0076f5">

**Comment by catdiscus** [comment]
断点仍是不生效,请问这个本身可以调试吗?

**Comment by catdiscus** [comment]
<img width="650" alt="image" src="https://github.com/jumpserver/jumpserver/assets/103556820/06b00479-f6a5-40c6-bc64-853d91aca7d1">
配置改改成这样了,打的断点无效

**Comment by catdiscus** [comment]
换 idea 后断点正常,应该是 pycharm 的问题
