### ISSUE TITLE
[Feature] 远程应用website密码代填脚本添加等待时间

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#10613]
**请描述您的需求或者改进建议.**
当前通过远程应用发布部分应用的时候发现，密码代填太快，登录按钮会因为自检导致灰色无法选中，需要添加den等待时间，如time.sleep()；
![7d80ca5dce164ca1b0e27b625511e41](https://github.com/jumpserver/jumpserver/assets/66759501/bf733229-ec4e-4d9c-9ca0-6a8f828b77bd)

**Comment by BaiJiangJie** [comment]
后面 Web 资产脚本加一个 sleep 指令，允许用户自定义。

**Comment by BaiJiangJie** [comment]
v3.4 支持。

**Comment by jstbw** [comment]
麻烦告诉一下这个等待时间在哪里加，直播视频一带而过，没看到添加的地方
