### ISSUE TITLE
[Question] 从2.2.3迁移到3.3.1以后，所有用户的MFA无法使用，必须重新绑定

### ISSUE THREAD

**Issue by r023875206** [jumpserver/jumpserver#10610]
**请描述您的问题.**
从2.2.3迁移到3.3.1以后，所有用户的MFA无法使用，必须重新绑定，是否可以还原原来的MFA

**Comment by BaiJiangJie** [comment]
不应该啊，升级上来后，配置文件中的 SECRET_KEY 迁移到新环境了吗？

**Comment by jym503558564** [comment]
该问题还存在吗？由于长时间未反馈，我们将关闭该Issues，如有其他问题可再次提Issues。
