### ISSUE TITLE
[Bug] Safari浏览器资产列表空白bug

### ISSUE THREAD

**Issue by Halo1236** [jumpserver/jumpserver#10617]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**浏览器版本**
Safari浏览器
版本16.3 (18614.4.6.1.6)

**Bug 描述**
资产列表空白，不显示列表
<img width="976" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17096387/1947ae5c-3bc0-4d9c-90b8-5d99c23228e8">

**Comment by BaiJiangJie** [comment]
问题找到了，是 Safari 不支持复杂正则匹配规则导致页面失败的问题。

v3.4 版本解决。
