### ISSUE TITLE
[Bug] 通过账号模板给资产添加切换账号，会导致切换至为空

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10619]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.3.1

**Bug 描述**
通过账号模板给资产添加切换账号，会导致切换自为空

**Bug 重现步骤(有截图更好)**
1. 创建 普通账号模板 centos
![image](https://github.com/jumpserver/jumpserver/assets/54871762/042f653f-a5ea-43ab-a78e-3153142ee6f8)
2. 创建root账号模板 切换自选择第一步创建的centos
![image](https://github.com/jumpserver/jumpserver/assets/54871762/f81d71f5-2388-42f0-badf-d73d921dfa27)
3. 创建资产，通过账号模板绑定步骤1和步骤2创建的centos账号和root账号
![image](https://github.com/jumpserver/jumpserver/assets/54871762/4bc761c2-21a0-4bb6-b3a5-8897768ffd3f)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/54d690f9-ae5c-4131-b78f-3b6bcea1cd29)
4. 查看创建好资产的账号列表，点击root账号的更新，发现切换自为空
![image](https://github.com/jumpserver/jumpserver/assets/54871762/d52a61b0-035c-44c7-8e93-935aab2bcccc)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/ae76395c-4ac8-4f1a-bcd3-46b36dfd7814)

**Comment by BaiJiangJie** [comment]
好的，我们验证一下。

**Comment by BaiJiangJie** [comment]
新版本已优化。
