### ISSUE TITLE
[Question] 本地调试如何启动 ws 服务

### ISSUE THREAD

**Issue by catdiscus** [jumpserver/jumpserver#10615]
**请描述您的问题.**
调试批量命令过程发现会创建调用ws/ops/tasks/log/，未发现如何启动 ws 服务

**Comment by BaiJiangJie** [comment]
启动服务时，默认会启动 ws 服务的。

**Comment by catdiscus** [comment]
启动命令
<img width="624" alt="image" src="https://github.com/jumpserver/jumpserver/assets/103556820/0f93b699-7a54-45d5-bb2e-30649436787e">
nginx 配置
<img width="530" alt="image" src="https://github.com/jumpserver/jumpserver/assets/103556820/ef93e939-64a9-416e-a389-95511ca3976e">
ws 请求报错
<img width="710" alt="image" src="https://github.com/jumpserver/jumpserver/assets/103556820/b0a13f4a-52e1-4bbc-bd2e-a2335be8eae7">

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/jumpserver/blob/dev/apps/common/management/commands/services/services/gunicorn.py#L14

看 cmd 的定义

**Comment by catdiscus** [comment]
抱歉我对这个不太清楚，目前是在本地调试，用的 manage这个文件启动的 jumpserver，启动命令是python manage.py runserver 127.0.0.1:8060，web 服务正常，ws 异常，所以想问下怎么启动开发环境能正常的调试 ws？

**Comment by wojiushixiaobai** [comment]
把 python manage.py runserver 换成
gunicorn jumpserver.asgi:application -b, 0.0.0.0:8080 -k uvicorn.workers.UvicornWorker
