### ISSUE TITLE
[Feature] 建议增加“创建Web资产时可以选择特定应用发布机”功能

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#10612]
**请描述您的需求或者改进建议.**
目前 RemoteApp 的主机池由 JumpServer 进行统一维护，新建 Web 资产时无法选择由哪一台应用发布机进行承载，而是随机确定的，无法满足一些隔离网络的特殊需求，建议后续新增此功能。
举例说明：JumpServer 作为统一入口，分别连接到不同网络（不互通）的两台应用发布机 Server1 和 Server2，分别承载两个不同的 Web 资产 OA1 和 OA2，这样使用起来更加灵活方便。

**Comment by BaiJiangJie** [comment]
类似`终端端点`的特殊匹配逻辑，计划使用`标签`来解决。
