### ISSUE TITLE
[Feature] 会话分享增加“站内信”需求

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#10623]
**请描述您的需求或者改进建议.**
目前我们这堡垒机是纯内网部署，没有内网IM工具的话，此时会话分享就比较鸡肋，没有很好的办法能快速获得那个分享链接。
是否可以在分享界面增加一个“推送站内信”的按钮呢？
<img width="452" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/49c11d28-c96b-49a4-a9f3-6e21b780180d">

**Comment by BaiJiangJie** [comment]
很好的一个提议。

如果指定了 分享用户 在创建分享链接成功后，会自动发送站内信通知。

如果不指定则不发送。

这样就不用考虑再增加一个按钮了。

计划 v3.5 版本支持。
