### ISSUE TITLE
jumpserver使用后root密码会变吗

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1062]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2.]

##### 问题复现步骤
jumpserver会自己定期修改root密码吗？root密码好像都变了

**Comment by ibuler** [comment]
不会

**Comment by qianghong000** [comment]
但是所有机器root密码又不对了

**Comment by ibuler** [comment]
你查看一下带吗，root被过滤了

**Comment by qianghong000** [comment]
在哪里看？怎么修复呢

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/master/apps/assets/tasks.py#L318

**Comment by qianghong000** [comment]
311 ####  Push system user tasks ####
312 
313 def get_push_system_user_tasks(system_user):
314     # Set root as system user is dangerous
315     if system_user.username == "root":
316         return []
代码跟你给的链接里是一样的

**Comment by ibuler** [comment]
那就不会推送啊

**Comment by qianghong000** [comment]
chage -l root
命令显示最近确实没有修改过root密码。我再找找其他原因吧

**Comment by qianghong000** [comment]
其他同事反馈 没有加入堡垒机的服务器 就没出现这种问题。会不会加入到堡垒机以后 对root登录有了限制

**Comment by qianghong000** [comment]
可能是我们密码记错了 看看以后还会不会复现吧
