### ISSUE TITLE
[Bug] Error response from daemon: No such container: jms_core

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#10628]
When I install Jumpserver v3.3.1 with
```
./jmsctl.sh install
```
In step 6. Init JumpServer Database, it take error:
```
Error response from daemon: No such container: jms_core
[ERROR] Failed to change the table structure!
```
How to do fix it

**Comment by wojiushixiaobai** [comment]
Complete logs are required.

**Comment by JumpServer-Zac** [comment]
Hi I am the JumpServer support team Zac,
You can add my WhatsApp +86 15717111453 if you need help to use JumpServer
