### ISSUE TITLE
[Feature] 审计日志筛选功能优化建议

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10627]
**请描述您的需求或者改进建议.**
当前日志筛选功能选择使用用户或者资产作为条件时，如果假如用户名是Tom, 姓名为张三，那么在记录中用户一列会显示为 张三(Tom).
我在添加筛选条件时选择用户作为筛选条件时不论是张三还是Tom都无法筛选出需要的记录必须是"张三(Tom)"这个字符串才能正确出现结果，web资源也有一样的问题，web资源显示为 百度(www.baidu.com).
要么加入下拉框，要么支持单独使用用户名或者姓名进行搜索。

**Comment by BaiJiangJie** [comment]
如果下拉框里选择了资产或者用户，代表着精确匹配，就需要输入完整的名称，如：张三(Tom)

如果想要模糊匹配，就直接输入到输入框中，如：js_yy

<img width="1880" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fc5f3607-1131-4052-83f3-0b45d84f18c7">
