### ISSUE TITLE
[Question] 获取数据库连接信息超时问题咨询

### ISSUE THREAD

**Issue by asdfgasysfy** [jumpserver/jumpserver#10625]
**请描述您的问题.**
设置12小时的超时时间. 但是实际上1 2 小时就失效了.  是我使用有问题. 还是配置有问题.  
![image](https://github.com/jumpserver/jumpserver/assets/132526870/02d47e14-1c96-4736-a0ec-00e325dccacf)

**Comment by asdfgasysfy** [comment]
翻直播看到问题了

**Comment by BaiJiangJie** [comment]
新版本需要开启配置来进行复用，看直播解决了吗？

**Comment by asdfgasysfy** [comment]
已经解决

**Comment by mmy83** [comment]
是否能说说咋解决的或者提供一下视频地址，我也遇到了这个问题

**Comment by mmy83** [comment]
@BaiJiangJie 你好，我也遇到这个问题，能帮我解决一下吗？
