### ISSUE TITLE
[Bug] 通过账号模板给资产添加账号后，账号模板和资产的绑定不符合预期

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10620]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.3.1

**Bug 描述**
通过账号模板给资产添加账号后，账号模板和资产的绑定不符合预期
1. 在创建资产时用账号模板给资产添加账号在创建完成后，账号模板的账号列表中没有关联创建的账号
2. 在已经创建好的资产中用多个账号模板给资产添加多个账号会导致新创建的多个账号会随机全部绑定在一个用于创建账号的账号模板下面

**Bug 重现步骤 新资产**
1. 创建资产时用账号模板添加账号
![image](https://github.com/jumpserver/jumpserver/assets/54871762/a73e9c69-ad21-4058-8864-f691ea569f8c)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/73683f6b-afeb-40ec-8994-fa7bf0803916)
2. 查看使用的账号模板的账号列表为空
![image](https://github.com/jumpserver/jumpserver/assets/54871762/6dff2251-aecf-4e06-bfa2-313a71bc644b)

**Bug 重现步骤 已创建的资产**
1. 使用已创建好的资产使用账号模板添加账号
![image](https://github.com/jumpserver/jumpserver/assets/54871762/8989edc1-b541-4a7f-a09d-41d6f2fcf068)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/08671e5b-9138-448c-ba51-bb1069d5e58c)
2. 分别去这两个账号模板的账号列表查看，发现账号都关联到此例中的New-Demo-centos下面
![image](https://github.com/jumpserver/jumpserver/assets/54871762/e5f75cf9-999b-4eed-9c99-2e898142c284)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/afc17be0-9c88-47e6-9c5e-02fe503c82f6)
3. 把账号删除用同样的账号模板再添加一次，这次账号全部都关联到了Test-Centos下面
![image](https://github.com/jumpserver/jumpserver/assets/54871762/e521719d-9972-4bb0-8808-837e4d93a670)
![image](https://github.com/jumpserver/jumpserver/assets/54871762/32c1cec3-1b6a-4d19-85a7-bd3c3d2bcf74)

**Comment by BaiJiangJie** [comment]
我们来验证一下 @feng626

**Comment by jym503558564** [comment]
3.8.1无法复现。
问题1:测试结果如下
![image](https://github.com/jumpserver/jumpserver/assets/40739051/80dfe2b0-d1e1-4f5e-8e62-fe5fb784cd4f)
<img width="1391" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/bf2581f3-8c3c-4fb0-8d4d-3577aff10fe1">

问题2: 测试结果如下
![image](https://github.com/jumpserver/jumpserver/assets/40739051/63f363f3-7862-4839-a341-a97e5796ffd4)
![image](https://github.com/jumpserver/jumpserver/assets/40739051/dbfe4706-c012-4055-a150-b3c18a7f7a71)
![image](https://github.com/jumpserver/jumpserver/assets/40739051/a06d1034-069c-46dd-996b-729bafd04a67)

**Comment by BaiJiangJie** [comment]
最新版本已修复了，升级解决。
