### ISSUE TITLE
[Question] redis 无密码。堡垒机发布以后无法用客户端连接

### ISSUE THREAD

**Issue by ighack** [jumpserver/jumpserver#10634]
redis 6.2.3  无密码
jumpserver v3.3.1-amd64-322

在jumpserver发布了一个redis 现在只能用web cli来连接
密码处直接回车
![image](https://github.com/jumpserver/jumpserver/assets/6670377/e72a516e-e061-45e9-b212-38e1943d82e7)

但是RDM无论怎么输入用户名密码或只有密码都不行
![image](https://github.com/jumpserver/jumpserver/assets/6670377/e23ea2ef-5c46-49d0-b623-f1b3cc8c394f)

redis-cli也不行
![image](https://github.com/jumpserver/jumpserver/assets/6670377/c6d2a8da-cc4f-424f-a860-666ec3a108cc)

**Comment by BaiJiangJie** [comment]
点击账号查看下密码，是不是使用 RDM 时密码不对？

**Comment by ighack** [comment]
> 点击账号查看下密码，是不是使用 RDM 时密码不对？

我的redis 本身是没有密码的。
用堡垒机去连的话 我RDM里的密码是直接复制的。是包含@前后所有字符的

**Comment by BaiJiangJie** [comment]
那是 RDM 的问题吧？
