### ISSUE TITLE
[Question] 歷史會話回放一片黑

### ISSUE THREAD

**Issue by RainFall2416** [jumpserver/jumpserver#10632]
請問我審計台的歷史會話回放無法正常顯示，都是一片黑，下載可正常撥放，
而且有部分記錄無法回放及下載，有什麼解決方案嗎，
版本是v3.2.2，
謝謝！

**Comment by BaiJiangJie** [comment]
`有部分記錄無法回放及下載`

这个可能是录像本身没有记录，比如，资产连接不成功（但是会话会记录）

`回放無法正常顯示，都是一片黑`

看看前端页面有报错吗？

**Comment by RainFall2416** [comment]
沒有報錯，進度條可以正常跑，錄像長度、用戶與資產都正常顯示，
但是回放沒有畫面，一片黑。

**Comment by RainFall2416** [comment]
![jms截圖](https://github.com/jumpserver/jumpserver/assets/128705852/4c75bed0-cc2b-4093-9a87-2d30ba501071)
整段就像這樣，沒有畫面，條正常跑，但是就跑8分54秒的黑畫面，
錄像可下載可以播放。

**Comment by LeeEirc** [comment]
什么类型的资产？通过什么方式连接的，web 还是 客户端？

**Comment by RainFall2416** [comment]
windows，有RDP也有VNC，都是從web。

**Comment by LeeEirc** [comment]
如果你录像下载可以播放，那么我怀疑是 web 播放器存在问题。可以使用 chrome 浏览器试一下吗？另外可以打开浏览器的开发者工具，看看是否有报错信息？

**Comment by RainFall2416** [comment]
![螢幕擷取畫面 2023-06-16 102932](https://github.com/jumpserver/jumpserver/assets/128705852/aef3b12b-46cd-475f-8d26-ac4a2e7b7003)
chrome開發者工具顯示大量這個訊息

**Comment by BaiJiangJie** [comment]
加入一下社区交流群，远程看一下吧？

**Comment by RainFall2416** [comment]
解決了，nginx config裡的CSP設定拿掉就好了。
![image](https://github.com/jumpserver/jumpserver/assets/128705852/8f16c084-eae2-4e55-8969-02c2d8ac983b)
