### ISSUE TITLE
[Question] 是否支持mongodb 集群模式和redis集群模式

### ISSUE THREAD

**Issue by ighack** [jumpserver/jumpserver#10635]
我们的mongodb，redis都 是分片集群

mongodb是否支持用客户端连接
如navicat 等工具

**Comment by BaiJiangJie** [comment]
`mongodb是否支持用客户端连接`
可以使用远程应用 Navicat 连接 MongoDB（企业版支持）


MongoDB，Redis集群问题，作为资产纳管的话，只要提供一个统一的访问地址就能连接。
