### ISSUE TITLE
[Question] 如何关闭任务中心里自带的任务

### ISSUE THREAD

**Issue by catdiscus** [jumpserver/jumpserver#10648]
**请描述您的问题.**
"校验资产授权规则已过期" 
![image](https://github.com/jumpserver/jumpserver/assets/103556820/84174992-ff42-4452-a1a5-0ea0aa586beb)
目前希望关闭这个任务,是否删除 ops_celerytask 表内name 为perms.tasks.check_asset_permission_expired的这条记录即可,还是说需要同时改其他的东西?

**Comment by BaiJiangJie** [comment]
目前不支持关闭。
但是可以通过修改配置文件校验周期来侧面关闭。

PERM_EXPIRED_CHECK_PERIODIC 默认是 3600 （1h）

可以修改的时间长一些，比如

PERM_EXPIRED_CHECK_PERIODIC=31536000

`3600 * 24 * 365 = 31536000`（相当于 1 年执行一次）
