### ISSUE TITLE
审计角色可以按资产授权，仅允许审计部分资产。

### ISSUE THREAD

**Issue by zhanggefei** [jumpserver/jumpserver#10645]
审计角色可以按资产授权，仅允许审计部分资产。

**Comment by BaiJiangJie** [comment]
审计还是按照组织来进行划分，目前默认角色中有`组织审计员`角色。
如果对`审计部分资产`功能有强烈需求的话，还是建议使用不同的组织进行纳管。

如果审计资产也通过授权的方式进行控制的话，无论是管理员操作起来还是后端逻辑实现起来，相对都会比较繁琐，易用性会降低。

当然了，组织管理是企业版的功能。
