### ISSUE TITLE
资产连接windows测试连接报错，实际可以连接[Question] 

### ISSUE THREAD

**Issue by wttt-py** [jumpserver/jumpserver#10642]
**请描述您的问题
![image](https://github.com/jumpserver/jumpserver/assets/83765757/bfcfd669-d860-49ce-bb1f-34674b972a62)
![image](https://github.com/jumpserver/jumpserver/assets/83765757/d5d2843b-cb99-474c-907f-b0da3a058014)
jumpserver为3.3.1版本单机容器部署
![image](https://github.com/jumpserver/jumpserver/assets/83765757/0b4bb388-f62c-4f42-bbc8-8f7cd0d3f24c)

.**

**Comment by BaiJiangJie** [comment]
测试走的是 ssh 协议，连接使用的是 rdp 协议。

可以试试通过 ssh 协议是否可以连接成功。
