### ISSUE TITLE
[Bug] 资产列表页为空

### ISSUE THREAD

**Issue by xuanouba** [jumpserver/jumpserver#10643]
**JumpServer 版本 **
3.3.1

**浏览器版本**
chrome 113.0.5672.127

**Bug 描述**
资产列表页为空
控制台报错  chunk-2d209162.075be28f.js:1 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'hidden')
    at chunk-2d209162.075be28f.js:1:4256

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/19262324/f514abdd-c81c-4146-80b2-d4de3867d70b)
![image](https://github.com/jumpserver/jumpserver/assets/19262324/390a7a84-8f29-4c93-8367-d8b7cdcf7b84)

**Comment by xuanouba** [comment]
不是必现，刷新下就好了，但是偶尔会发生这种情况

**Comment by BaiJiangJie** [comment]
好的，v3.4 版本对这一块有优化。

可以留意一下，什么情况下会出现。
