### ISSUE TITLE
[Feature] MongoDB 数据库支持多种连接方式

### ISSUE THREAD

**Issue by SnowStorms** [jumpserver/jumpserver#10651]
**请描述您的需求或者改进建议.**
现在mongodb使用的越来越多，我们公司所有的db都是使用这个，

非常希望能像mysql一样，支持mongodb的多种连接方式！！！

**Comment by BaiJiangJie** [comment]
目前支持 Web CLI 和 远程应用 Navicat 连接（企业版）。

Web GUI 方式暂时不考虑支持，因为 MongoDB 和 MySQL 这种关系型数据库还不太一样，GUI 方式呈现起来难度会比较大。

**Comment by BaiJiangJie** [comment]
不过，将来 Web GUI 和 本地客户端连接方式都会考虑的。
