### ISSUE TITLE
web终端里面使用Linux终端的时候输入内容稍频繁或者内容过多就会卡死

### ISSUE THREAD

**Issue by Driver-C** [jumpserver/jumpserver#1065]
[简述你的问题]

##### 使用版本
0.5.0

##### 问题复现步骤
1. 进入web终端
2. 一直按住任意键或者频繁操作一下

##### 具体表现[截图可能会更好些,最好能截全]

一旦卡死会话小窗就会变成白色，只能关闭了重新开启。

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
你是什么网络，内网还是公网，你这个大概率就是公网防火墙或者运营商把数据包掐断了

**Comment by Driver-C** [comment]
jumpserver是搭在阿里云ECS上的，用内网访问其他服务器的，内网应该是没有这方面的限制吧。

**Comment by Driver-C** [comment]
@liuzheng

**Comment by liuzheng** [comment]
@Driver-C 你流量走公网了，websocket可能被运营商掐了
你阿里云ECS的公网带宽足够么？

**Comment by Driver-C** [comment]
@liuzheng 确实和走公网有关系，谢谢。

**Comment by ibuler** [comment]
fixed
