### ISSUE TITLE
No migrations to apply.

### ISSUE THREAD

**Issue by alvist0101** [jumpserver/jumpserver#1066]
5.0 这个是什么错误
No migrations to apply. 
求解
![image](https://user-images.githubusercontent.com/31679747/37327393-0fe1ae06-26d1-11e8-9e51-bce91019c98e.png)

![wx20180313-151350](https://user-images.githubusercontent.com/31679747/37327421-2d3a9d96-26d1-11e8-9aa3-c436392adf09.png)

**Comment by ibuler** [comment]
这不是报错，可以忽略
