### ISSUE TITLE
[Question] 使用jumpserver通过ssl连接数据库应用

### ISSUE THREAD

**Issue by La-lakers** [jumpserver/jumpserver#10660]
**请描述您的问题.**
jumpserver v2.28.14，社区版本，通过jumpserver连接数据库报错，Error 9002: SSL connection is required. Please specify SSL options and retry.
mysql开启强制ssl，如何可以使用Jump server通过ssl连接数据库。

**Comment by BaiJiangJie** [comment]
目前不支持 SSL 连接 MySQL。

**Comment by jym503558564** [comment]
v3.7.0已支持mysql
