### ISSUE TITLE
[Question] v2.0.2启用rsyslog无论怎么试都不行，是不是该版本还未支持rsyslog

### ISSUE THREAD

**Issue by blaze622** [jumpserver/jumpserver#10665]
**请描述您的问题.**
如题，经过多次尝试，始终无法通过rsyslog收集日志

**Comment by blaze622** [comment]
配置参考官网配置
# 加入 syslog 相关设置
SYSLOG_ENABLE=true
SYSLOG_ADDR=192.168.106.168:514
已经使用命令测试通过可生成日志
logger -n 192.168.106.168 -P 514 -p local2.info "message:rsyslog loggging From JumpServer"

**Comment by maninhill** [comment]
建议你们升级到 v2.28，这么老的版本没有支持了。

**Comment by blaze622** [comment]
好的，谢谢，我们这个是当时用一键脚本安装的，是否可以平滑升级到最新版本呢？ 有什么需要注意的吗？

**Comment by maninhill** [comment]
认真阅读文档，按文档操作。

**Comment by jym503558564** [comment]
升级请参照官方文档，且需阅读升级须知。
