### ISSUE TITLE
[Bug] web链接信锐交换机闪退

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10673]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**浏览器版本**
版本 114.0.1823.37 (正式版本) (64 位)

**Bug 描述**
使用堡垒机web访问信锐交换机闪退

**Bug 重现步骤(有截图更好)**
1.现有一台信锐交换机，型号RS6300-24X-LI-12X；软件版本SW3.4 BUILD20230422
2.现有一台堡垒机v3.3.1
3.信锐交换机web页面如下：
![image](https://github.com/jumpserver/jumpserver/assets/63082453/1f77849a-9829-4eae-875f-b54044d1fd0a)
![image](https://github.com/jumpserver/jumpserver/assets/63082453/ef1b72cd-91d7-40ec-be88-d514e345ee56)
![image](https://github.com/jumpserver/jumpserver/assets/63082453/ae5b5a45-756f-4c1a-a8a7-35c2f0ce8ec3)
4.堡垒机配置如下
![image](https://github.com/jumpserver/jumpserver/assets/63082453/71c03fd4-79dd-4381-87bd-b1666f0aeba8)

**Comment by BaiJiangJie** [comment]
Web 资产的地址写的对吗？

可以在发布机上先手动打开 Chrome 试一下是否可以打开。

**Comment by qianyu-0712** [comment]
发布机上是可以正常打开的，jumpserver里看到了输入用户名和密码的界面，点击了确认之后就黑了，还显示正在注销用户

**Comment by BaiJiangJie** [comment]
按照 https://github.com/jumpserver/jumpserver/issues/10692 里的方法试一下。

修改 环境变量 path 就行。

如果可以的话，那就是需要重新初始化部署一下发布机（v3.3.1 上做了修复）

**Comment by qianyu-0712** [comment]
我的发布机是在3.3.1全新部署的。环境变量跟https://github.com/jumpserver/jumpserver/issues/10692 是一致的。有且只有锐信交换机有这样的问题。其他厂家的都没有

**Comment by qianyu-0712** [comment]
如果只做用户名和密码的填充就没有问题。做了登录按钮的点击，就会闪退

**Comment by BaiJiangJie** [comment]
加入一下交流群，远程看看效果
