### ISSUE TITLE
[Bug] 资产太多展开之后会显示双滚动条。

### ISSUE THREAD

**Issue by yunyouu** [jumpserver/jumpserver#10670]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**浏览器版本**
Chrome 114.0.5735.106

**Bug 描述**
进入终端之后展开资产，资产很多的时候会显示两个滚动条，显示器分辨率低的时候滚动条就占了很宽的位置。

**Bug 重现步骤(有截图更好)**
mac 上的效果倒还好
<img width="157" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/3a477769-d5cc-4e43-ab28-ba320a5a7c14">

**Comment by BaiJiangJie** [comment]
是的，目前支持`资产树`和`类型树`两种显示视图。
外侧的滚动条是视图范围，内侧的滚动条控制展开的其中一种视图内的显示（如：资产树）

**Comment by BaiJiangJie** [comment]
想办法看看能不能合并成一个滚动条

**Comment by yunyouu** [comment]
v3.4.1 已解决
