### ISSUE TITLE
[Feature] 考虑接入 trzsz ( trz / tsz ) ？可以浏览器中上传和下载文件（ 支持目录 ）。

### ISSUE THREAD

**Issue by lonnywong** [jumpserver/jumpserver#10679]
在服务器上要安装 [trzsz ( trz / tsz )](https://github.com/trzsz/trzsz)，现在（ 2023-06 ) [Go 版](https://github.com/trzsz/trzsz-go) 会新一些。

在 Web 终端要接入 [JS 版 trzsz](https://github.com/trzsz/trzsz.js)，开源地址：https://github.com/trzsz/trzsz.js

浏览器录屏演示：
![browser example](https://trzsz.github.io/images/browser.gif)

**Comment by BaiJiangJie** [comment]
提议很好，我们研究一下看看能不能集成进来。

**Comment by fengmikaelson** [comment]
同问，现在的rz sz 还有web端的sftp经常变成0kb。好头疼。

**Comment by BaiJiangJie** [comment]
暂不考虑。将来考虑的话会 reopen。
