### ISSUE TITLE
[Bug] v3.3.1版本连接 web 应用无法打开 chrome

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [jumpserver/jumpserver#10692]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v3.3.1

**浏览器版本**
chrome

**Bug 描述**
v3.3.1版本连接 web 应用无法打开 chrome

**Bug 重现步骤(有截图更好)**
1. 应用发布机初始化部署成功
2.部署 chrome 应用成功
3.添加 web 资产，连接的时候没有打开 chrome 浏览器就直接注销了
用发布机创建的账号登录进去可以正常打开浏览器，访问网站。

**Comment by mjwtc0722** [comment]
同样的问题

**Comment by wellsyu** [comment]
重新下载chrome 对应版本的driver，覆盖。修改path变量中的chrome

**Comment by songchaoqiang** [comment]
@wellsyu 可以说下具体操作方式么, 感谢🙏

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10673

https://github.com/jumpserver/jumpserver/issues/10684

好像都是类似的情况

**Comment by BaiJiangJie** [comment]
资产地址写 http:// 或者 https:// 协议了吗？

**Comment by songchaoqiang** [comment]
写了

**Comment by BaiJiangJie** [comment]
发布机系统是什么版本？

**Comment by songchaoqiang** [comment]
可以，我在交流群里

**Comment by zhanwonichengshizhu** [comment]
> 重新下载chrome 对应版本的driver，覆盖。修改path变量中的chrome

是的，用这种方法解决了
