### ISSUE TITLE
[Question] 管理员如何手动删除用户上传的文件？

### ISSUE THREAD

**Issue by Satan023** [jumpserver/jumpserver#10701]
**请描述您的问题.**
1.想知道admin如何手动删除用户上传的文件？因为有些用户上传的东西太多了，明明已经拷贝到服务器了他也不删除，跳板机容量有点捉鸡。所以我想手动删除。
2.JUMPSERVER_CLEAR_DRIVE_SESSION=false 该参数是否还生效？在现在的官方文档的参数里面也就找不到这条了。

**Comment by BaiJiangJie** [comment]
看看是哪个目录下存储占用比较大？

<= 2.10.0 配置生效，设置 `JUMPSERVER_CLEAR_DRIVE_SESSION=true`，每一个会话断开后会清理上传的文件。

>= 2.13.0，设置 `JUMPSERVER_CLEAN_DRIVE_SCHEDULE_TIME=1` 定时清理挂载盘文件的时间间隔 (单位：小时)，如果设置值 0，则不清理。（ v2.13新增 ）

**Comment by Satan023** [comment]
> 看看是哪个目录下存储占用比较大？
> 
> `<= 2.10.0 配置生效，设置 JUMPSERVER_CLEAR_DRIVE_SESSION=true，每一个会话断开后会清理上传的文件。 `
> 
> `>= 2.13.0，设置 JUMPSERVER_CLEAN_DRIVE_SCHEDULE_TIME=1 定时清理挂载盘文件的时间间隔 (单位：小时)，如果设置值 0，则不清理。（ v2.13新增 ）`

是这里 /data/jumpserver/lion/data/drive/

v3.3.1版本这两条命令依旧生效吗？

thx

**Comment by BaiJiangJie** [comment]
只有这个配置生效 JUMPSERVER_CLEAN_DRIVE_SCHEDULE_TIME=1

**Comment by Satan023** [comment]
> JUMPSERVER_CLEAN_DRIVE_SCHEDULE_TIME=

好的，感谢
另外我手动清理/data/jumpserver/lion/data/drive/下面的文件也是可以的吧？

**Comment by BaiJiangJie** [comment]
嗯，可以。
