### ISSUE TITLE
5.0版本中 设置管理用户无法使用加密的key

### ISSUE THREAD

**Issue by alcat01** [jumpserver/jumpserver#1071]
[简述你的问题]
使用docker 方式部署5.0版本，在 设置管理用户时无法使用加密的key
##### 使用版本
 jumpserver 0.5.0 

##### 问题复现步骤
1. [步骤1]
设置管理用户时使用ssh私钥上传id_rsa 文件提示ssh秘钥不合法，
服务器管理禁用密码登录，ssh key 使用加密方式，导致上传时ssh秘钥不合法。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
该版本是支持的，近期更新过吗

**Comment by alcat01** [comment]
docker 镜像使用 registry.jumpserver.org/public/jumpserver:1.0.0  使用加密的key 依旧存在ssh秘钥不合法提示，秘钥格式：
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
![Uploading 图片.png…]()

**Comment by ibuler** [comment]
正确输入密钥的密码，必须能解密

**Comment by alcat01** [comment]
必须的！密码或者秘钥密码，太棒了
