### ISSUE TITLE
1.0.0上传文件

### ISSUE THREAD

**Issue by UmfintechWtc** [jumpserver/jumpserver#1073]
####使用版本
[1.0.0]

##### 问题描述
请问1.0.0的版本怎么上传下载文件，我通过rz不成功,输入后会卡死；xftp之类的还没有试过

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/31309558/37452329-3aeb3c4e-286f-11e8-91e5-ac8425f8a767.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
web shell不支持，因为web 没法收到 zmodem的数据，使用客户端，不过我们马上就做上传下载文件的功能
