### ISSUE TITLE
jms_celery 总是掉线

### ISSUE THREAD

**Issue by yxiaoy6** [jumpserver/jumpserver#10730]
![image](https://github.com/jumpserver/jumpserver/assets/43592152/031cd123-cb0c-429a-9ced-ade7f7c1ee37)

在运行批量推送，批量命令等情况时，jms celery总是不可用，有什么解决办法吗

**Comment by wojiushixiaobai** [comment]
收到反馈，我们看看能否优化。

**Comment by BaiJiangJie** [comment]
最新版本已优化。
