### ISSUE TITLE
Docker compose从v3.2.2升级到v3.4.0时，core无法启动

### ISSUE THREAD

**Issue by jumping008** [jumpserver/jumpserver#10737]
当通过docker compose进行升级时，core无法启动
具体截图如下

![d26fc7a8f7ad9972303ac4a3410ae0c](https://github.com/jumpserver/jumpserver/assets/58167667/afb0b2a2-f058-4f43-bb6e-98c31b7adc65)

**Comment by BaiJiangJie** [comment]
稍等片刻

**Comment by ibuler** [comment]
可以升级了

**Comment by BaiJiangJie** [comment]
已经正式发布了，你升级失败是因为当时还没有发布完成。
