### ISSUE TITLE
web terminal登陆成功后退出，远程服务器ssh进程未关闭

### ISSUE THREAD

**Issue by UmfintechWtc** [jumpserver/jumpserver#1074]
##### 使用版本
[1.0.0]

##### 问题描述
在web terminal开启了三个会话，在会话中通过exit退出或者在管理员端杀死会话连接时，发现远程服务器上的ssh对应进程并没有关闭，请问一下这个该怎么解决；

##### 具体表现[截图可能会更好些,最好能截全]

![1521103775 1](https://user-images.githubusercontent.com/31309558/37452896-e96fa16e-2870-11e8-820f-661fefe597ae.png)
![1521103805 1](https://user-images.githubusercontent.com/31309558/37452897-e9a464e4-2870-11e8-9eb4-f6b1c39e4a52.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by w55554** [comment]
我也遇到这个问题了，目前没有解决吧。

**Comment by ibuler** [comment]
这个tty不是连接后留下的，而是ansible执行任务后留下的，如 测试连接，如推送系统用户等等，
你可以尝试找个没有 notty进程的资产，测试一下可连接性，这时你会发现这个资产上有了 notty，不过过一段时间就没了

**Comment by w55554** [comment]
但是我服务器上这些进程，存在20多天了，也没有退出，除非手动 杀死！是不是我设置不正确导致的呢？ @ibuler

**Comment by ibuler** [comment]
这个你可以帮助研究一下吗，查看一下 ansible的文档，我解决一下别的问题，然后我们一起来解决一下

**Comment by ibuler** [comment]
请再观察一下 ssh 进程不会变为 僵尸进程

**Comment by Nidhoggur1993** [comment]
@ibuler @w55554 我刚刚也试了一下，从coco上exit的时候远程服务器的sshd不释放，进程不是 僵尸进程，就是正常的sleep状态，/var/log/secure里没有 `session closed` ，但是把coco关掉就马上会释放这个挂起的sshd进程。
但是分别重启了一下jumpserver和coco之后问题不复现

**Comment by UmfintechWtc** [comment]
这个连接会持续2、3天，最终都会关闭（我试过好几遍），不知道是我环境的原因还是什么，我看到有人说20多天还未关闭！
我是运维工程师，技术有点次，恐怕帮不上什么！
谢谢您了！





在 2018-03-16 11:43:15，"老广" <notifications@github.com> 写道：


这个你可以帮助研究一下吗，查看一下 ansible的文档，我解决一下别的问题，然后我们一起来解决一下

**Comment by UmfintechWtc** [comment]
没有变成僵尸进程，我观察的现象是：
web terminal关闭会话后，远程服务器在一定时间内会保持notty连接，但是经过2、3天，notty进程会自动关闭！





在 2018-03-16 11:47:44，"老广" <notifications@github.com> 写道：


请再观察一下 ssh 进程不会变为 僵尸进程

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
