### ISSUE TITLE
[Question] core模块启动异常咨询

### ISSUE THREAD

**Issue by asdfgasysfy** [jumpserver/jumpserver#10759]
**请描述您的问题.**
flower.log日志
![image](https://github.com/jumpserver/jumpserver/assets/132526870/2a0fb35d-5de8-44d5-84ec-4474ccb11d25)
ddocker  core日志
![image](https://github.com/jumpserver/jumpserver/assets/132526870/07387352-e1c1-43f3-bdcd-609574be769c)

**Comment by BaiJiangJie** [comment]
删掉 /data/jumpserver/core/data/flower.db 文件，重启一下服务试试？
