### ISSUE TITLE
[Bug] v3.4.0复测模板账户绑定切换至后，资产账户切换至没有同步

### ISSUE THREAD

**Issue by b-ing** [jumpserver/jumpserver#10764]
**JumpServer 版本( v3.4.1 之前的版本不再支持 )**

**浏览器版本**
Microsoft Edge 版本 114.0.1823.43 (正式版本) (64 位)

**Bug 描述**
v3.4中说修复了模板账户设置切换自某账号，资产中的主机应自动绑定到切换自，实测还是为空，以下为截图：

**Bug 重现步骤(有截图更好)**

1.已设置切换至
![image](https://github.com/jumpserver/jumpserver/assets/33180711/161b5be9-d271-4c6d-a69d-885beb32b3e5)

2.关联的资产
![image](https://github.com/jumpserver/jumpserver/assets/33180711/e00a073f-4a47-42eb-a4b2-841916fd7747)

3.资产中切换自为空截图：
![image](https://github.com/jumpserver/jumpserver/assets/33180711/887265d3-a77a-46df-9e9f-f0bd647ab5d5)

**Comment by BaiJiangJie** [comment]
v3.6 最新版本已解决。
