### ISSUE TITLE
[Bug] v3.4.0在平台列表选定切换账户方式时，资产切换时并未区分sudu 和su

### ISSUE THREAD

**Issue by b-ing** [jumpserver/jumpserver#10765]
**JumpServer 版本3.4.0**

**浏览器版本**

**Bug 描述**
在平台列表选定切换账户方式时，资产切换时并未区分sudu 和su
区别：
sudo 需要配置，并且需要输入跳转账户的密码
su -   不需要配置，输入 root的密码后自动切换
![image](https://github.com/jumpserver/jumpserver/assets/33180711/f6afe9bb-32db-48da-a8a3-abf852f6bdd4)

**Bug 重现步骤(有截图更好)**
1.报错为sudo错误！！
![image](https://github.com/jumpserver/jumpserver/assets/33180711/b70644eb-5ef5-4b4b-a03a-a54a717b5204)

2.平台设置为su
![image](https://github.com/jumpserver/jumpserver/assets/33180711/d3281907-3fd5-454e-b0b4-421672378c50)

3.资产关联的平台列表
![image](https://github.com/jumpserver/jumpserver/assets/33180711/3d30e53b-a359-4af9-9198-eb95d3dff1f0)

**Comment by BaiJiangJie** [comment]
@xulinde 创建两个不同用户名、密码均不相同的账号，分别设置为账号和切换自账号。看看能否复现。

**Comment by b-ing** [comment]
目前更新到3.7.2发现更新账号模版，账号模版中的配置未同步到账号列表中
[账号模版](https://seafile.b-ing.vip:11113/d/6032c09a77b14ceb8b76/files/?p=/111.png)
[账号列表](https://seafile.b-ing.vip:11113/d/6032c09a77b14ceb8b76/files/?p=/222.png)

**Comment by b-ing** [comment]
> @xulinde 创建两个不同用户名、密码均不相同的账号，分别设置为账号和切换自账号。看看能否复现。

测试3.7.2 su -切换可以了，但是账号模版同步有点问题，请查看上面的截图

**Comment by BaiJiangJie** [comment]
v3.8 版本修复了一下。v3.7 当时修改的有点问题。

升级到最新版本解决。

创建、更新日期，不会使用模版的，账号创建出来有自己的时间。
