### ISSUE TITLE
[Question]还是升级v3.4.0 pull镜像失败的问题 

### ISSUE THREAD

**Issue by sevenclockseven** [jumpserver/jumpserver#10763]
**请描述您的问题.**
之前pull jumpserver的镜像都是正常的，这次升级v3.4.0一直失败，我又测试了阿里云跟华为云ECS还有本地服务器直接pull镜像都是一样报这个错，有没有网络配置能参考一下。
华为云ecs
![image](https://github.com/jumpserver/jumpserver/assets/49014592/fb63827e-3564-458d-ab6d-43e934341ce3)
本地的
![image](https://github.com/jumpserver/jumpserver/assets/49014592/fca2170c-4339-40a8-a406-9a0d21f101a3)
阿里云的
![image](https://github.com/jumpserver/jumpserver/assets/49014592/2c5d6d57-ac94-4f01-b0b1-63359864724b)

**Comment by markvivv** [comment]
国内 docker 镜像的问题，目前使用上海交大的镜像网站成功。修改 /etc/docker/daemon.json 配置文件

`{
  "registry-mirrors": ["https://docker.mirrors.sjtug.sjtu.edu.cn"]
}`

**Comment by sevenclockseven** [comment]
> 国内 docker 镜像的问题，目前使用上海交大的镜像网站成功。修改 /etc/docker/daemon.json 配置文件
> 
> `{ "registry-mirrors": ["https://docker.mirrors.sjtug.sjtu.edu.cn"] }`

这个镜像站好使
