### ISSUE TITLE
命令行登录是否计划支持ssh key forward方式避免用户上传私钥到平台

### ISSUE THREAD

**Issue by chestarss** [jumpserver/jumpserver#1076]
如题，某些情况私钥集中保存不利于安全控制。
如果可以支持key fowrard则用户只需要本地自己保存私钥，通过ssh-add key的方式添加本地代理，然后登陆服务器

**Comment by ibuler** [comment]
用户登录 jumpserver的秘钥，还是 jumpserver登陆服务器的秘钥？

或者说 用户的秘钥，还是 系统用户或管理用户的秘钥?

**Comment by liuzheng** [comment]
@chestarss 我理解你的意思，ssh forward将key一层层透传过去。抱歉，这个不考虑，因为这个违背了jumpserver的设计初衷，jumpserver就是将key和密码统一管理，便于在人员变动时快速无感的进行key和密码的更新和权限收回，如果依然使用传统的方案，那么一旦涉及到人员变动就需要广播更新所有的key了，我们就是解决这个问题的。至于安全性问题，有jumpserver进行保证，并且我们提供自动更新的功能，可以做到无感，原则上，定期更新密钥更为安全。比如你每小时更新一次，黑客拿到这个密钥也就差不多立即失效了，况且黑客能进入主机内网，并且掌握jumpserver或者数据库权限，就证明这个已经被攻破了。

传统的攻击思路就是攻击页面注入，拿到注入点，select出key，现在我们使用的框架django做到了这个，作为开发，我们可以不需要考虑这种case。其余攻击方案我大多都清楚，暂时黑客要拿下，除非是用户自己设置了弱密码，软件本身已经达到了基本的安全规范
