### ISSUE TITLE
[Question] 站内信问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10767]
**请描述您的问题.**
普通用户执行被禁止的命令，这个会在管理员的站内信显示这个提示吗，我的没显示

**Comment by BaiJiangJie** [comment]
在系统设置里可以设置。

<img width="2559" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2aabb4e9-924d-4648-9a74-803d73dffb18">

**Comment by ryswork1993** [comment]
我想问的是普通用户执行被禁止的命令，管理员的站内信里会不会提示
| |
任永帅
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年6月25日 14:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Question] 站内信问题 (Issue #10767) |

在系统设置里可以设置。

**Comment by BaiJiangJie** [comment]
系统设置里`消息接收人`配置了管理员就会收到，不配置就收不到。
