### ISSUE TITLE
[Question] Jumpserver error when change host of mysql account

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#10768]
I have followed the documentation and used the command create user 'jumpserver'@'%' identified by 'KXOeyNgDeTdpeu9q'; to create the account, the created account will have a host of "%" allowing any server to access the database.
I want to limit server access by changing host with RENAME USER 'jumpserver'@'%' TO 'jumpserver'@'${IP}';
try accessing with mysql -h ${IP Jumpserver} -u jumpserver -p then can access and everything is fine. But when accessing Jumpserver, I receive a "Server Error" response, change the host "%" to be able to access it again.
How to change host but Jumpserver still has no error.

**Comment by BaiJiangJie** [comment]
After modifying the database information 'jumpserver'@'%' to 'jumpserver'@'${IP}', restart the jumpserver service, and check the log of the jms_core container when starting, `docker logs -f jms_core --tail 10` to see what is reported mistake?
