### ISSUE TITLE
v3.4.0 在线安装报错

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#10772]
>>> 安装配置 Docker
1. 安装 Docker
开始下载 Docker 程序 ...
[ERROR] 下载 docker 失败, 请检查网络是否正常
./jmsctl.sh:行81: docker-compose: 未找到命令

<img width="360" alt="image" src="https://github.com/jumpserver/jumpserver/assets/133093482/12f09517-6b5f-4aa1-897b-c1629dcb7eb1">

**Comment by BaiJiangJie** [comment]
网络正常吗？

**Comment by vipquan** [comment]
> 网络正常吗？

正常啊，需要提前部署Docker环境吗？

**Comment by BaiJiangJie** [comment]
提前部署也可以，没有 Docker 的话，安装 JumpServer 时会自动下载。

看日志是自动下载有问题，你还是先手动装一下吧。

**Comment by jym503558564** [comment]
安装解决了吗？如有问题可再次打开Issues
