### ISSUE TITLE
[Bug]  角色权限控制不准确

### ISSUE THREAD

**Issue by limin-fit2** [jumpserver/jumpserver#10773]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
    V3.4.0

**浏览器版本**
    版本 114.0.5735.133（正式版本） (arm64)

**Bug 描述**
    角色权限树控制失效

**Bug 重现步骤(有截图更好)**
1. 单独创建一个新的角色，权限只给审计台--》 文件管理权限，用户实际登录后，审计台日志出现作业日志菜单，并且会提醒“您没有执行该操作的权限”
![image](https://github.com/jumpserver/jumpserver/assets/61964761/464cb499-dab8-4475-9c45-0d8c34f975e8)

3.
4.

**Comment by limin-fit2** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/61964761/5f09eccc-537c-48d4-8416-823f62d16ed9)

**Comment by BaiJiangJie** [comment]
应该是 Bug，v3.4.2 版本会修复。

**Comment by BaiJiangJie** [comment]
已修复。
