### ISSUE TITLE
求0.3.2升级到1.0正式版的文档

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#1077]
首先非常感谢这个项目，使用 0.3.2 版本已经一段时间，终于等到正式版了。
求 0.3.2 升级到 1.0 正式版的文档，谢谢！

##### 使用版本
0.3.2

[注:] 完成后请关闭 issue

**Comment by alvin6666** [comment]
请问有文档吗

**Comment by EverCurse** [comment]
+1
