### ISSUE TITLE
[Question] 请问V3.4.0 账号自动推送社区版不支持了吗？

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10785]
**请描述您的问题.**
1.社区版无法设置自动推送账号。
![image](https://github.com/jumpserver/jumpserver/assets/106153788/a7f72bff-a0c4-4c72-9e26-79834be3d61b)

**Comment by jym503558564** [comment]
<img width="1439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/11f84b15-1ae5-4c8a-ae8c-359362d95c02">
支持的
