### ISSUE TITLE
[Question] 开启MFA，终端ssh连接失败

### ISSUE THREAD

**Issue by weqopy** [jumpserver/jumpserver#10782]
**请描述您的问题.**
版本 2.27.0

Web登录账号查看资产：
<img width="1094" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10494196/c5602d48-44b0-4447-be15-88ea8091b732">

```
Web 地址：***.81
账号：username
资产：****.115
资产系统用户：***-dev-ubuntu
```

下载 pem 密钥文件，ssh/config配置：
```
Host *
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa


Include ~/.orbstack/ssh/config

Host js
    HostName ***.81
    User username@***-dev-ubuntu@****.115
    Port 2222
    PreferredAuthentications publickey
    IdentityFile ~/.ssh/*****-jumpserver.pem

```

ssh 连接报错`Permission denied (keyboard-interactive).`
<img width="758" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10494196/b3ec6882-5d45-4415-9ea4-bb871a209e1c">

是否是config配置错误？

**Comment by BaiJiangJie** [comment]
先不用 config 配置文件，就手动 ssh 使用密码/密钥 登录，可以连接成功吗？

**Comment by weqopy** [comment]
@BaiJiangJie 手动登录成功了，资产那里的用户名有问题，应该直接用ubuntu
<img width="203" alt="image" src="https://github.com/jumpserver/jumpserver/assets/10494196/8e9f62c0-2e99-4474-8393-5276aa788f3e">
