### ISSUE TITLE
[Bug] Web GUI 连接 Mac VNC 失败

### ISSUE THREAD

**Issue by DNSTESTWEB** [jumpserver/jumpserver#10794]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

2.28.6 GPLv3.
**浏览器版本**
 chrome 114.0.5735.133

**Bug 描述**
无法链接macos系统vnc 
**Bug 重现步骤(有截图更好)**
1.，mac设置屏幕共享
资产列表添加macmini的vnc资产

2.系统创建macmini的本地账户密码
3.权限授权的添加之前创建macmini用户，web端链接报错如下，其他客户端链接测正常
![image](https://github.com/jumpserver/jumpserver/assets/36812022/2b3cc423-edb2-4247-9171-f68112cd5531)

**Comment by BaiJiangJie** [comment]
Web 连接失败的问题，看看 Lion 组件的日志有没有报错信息？

**Comment by ibuler** [comment]
看看 vnc server 的加密，改成自动或者不加密
