### ISSUE TITLE
[Bug] 监控问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10791]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.0

**浏览器版本**

**Bug 描述**
远程web资产，管理员无法点击监控会话
![image](https://github.com/jumpserver/jumpserver/assets/44529247/4d93c089-38c2-476e-962e-8aa1e6878a25)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by saszhuqing** [comment]
我从v3.3.1升级到 v3.4.0后也遇到同样的问题了

**Comment by BaiJiangJie** [comment]
v3.4.1 版本已修复。

@ryswork1993 @saszhuqing
