### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sushang123** [jumpserver/jumpserver#10795]
**Bug 描述**
节点这里，新增资产以后，资产列表有数据，但是这个总数的地方显示0

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/1906271/ed1c040a-6af6-4772-8da3-afe2a79e1610)

**Comment by BaiJiangJie** [comment]
右击节点-校对资产数量试试

<img width="533" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/02951bd7-f69f-48e7-99b0-0b47d929d606">

**Comment by sushang123** [comment]
OK
