### ISSUE TITLE
[Bug]  mac下使用iterm2登录，资产列表里的列显示不全。

### ISSUE THREAD

**Issue by tankxxl** [jumpserver/jumpserver#10793]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
社区版  v3.3.1

**浏览器版本**

**Bug 描述**
mac下使用iterm2登录，资产列表里的列显示不全。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/1826540/b376e35c-c3a6-4a99-96f7-657d4d524f94)

2.
3.

**Comment by LeeEirc** [comment]
https://github.com/jumpserver/jumpserver/issues/10606
