### ISSUE TITLE
1.0发邮件发不出是怎么回事呢？测试是ok的

### ISSUE THREAD

**Issue by dreamer-chen** [jumpserver/jumpserver#1079]
如题，给用户发邮件显示发成功了，but，没有

**Comment by flapjackegg** [comment]
我也是，测试的时候接收到了，但是新建用户的时候发送邮件就收不到了

**Comment by flapjackegg** [comment]
问题解决了，是因为jumpserver 启动的时候，我用的命令是 python run_server.py gunicorn ，必须得用 all

**Comment by Spinestars** [comment]
...有一行小字,是这么说的:
提交smtp设置后,请手动重启服务

**Comment by chenhaohao3025** [comment]
1.0如何重启程序？有大神知道吗

**Comment by ibuler** [comment]
下载这个脚本重启吧 

https://github.com/jumpserver/jumpserver/blob/dev/jms
