### ISSUE TITLE
[Feature] 录像存储能否指定时间上传到外部存储？

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#10807]
我设置了OSS的外部存储，但因为服务器带宽有限，总是用着用着就发现卡死了，发现是堡垒机把录像文件传到OSS的时候占用了外网带宽。
能否设置一个时间，一次性同步当天所有录像，在上传之前可以存在本地，避免在工作时间挤占外网带宽影响工作。
谢谢。

**Comment by BaiJiangJie** [comment]
目前不支持指定上传时间，都是实时上传的（会话结束时）；

因为会话和录像实际上还是比较重要的数据，尽量要在完成后完成上传；

**Comment by rex5652** [comment]
个人觉得可以增加一个设置，让用户选择是实时上传还是定时上传

**Comment by BaiJiangJie** [comment]
建议在带宽上做个升级，目前很少用户遇到带宽不够的情况。

为了审计的实时性，在产品上暂时先不考虑增加延时上传功能。

还有一个原因是，上传的动作都是由组件操作的，我们的组件目前也都是无状态的，所以说控制起来也不是很合适。
