### ISSUE TITLE
[Question] telnet 协议的资产批量tab操作

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#10803]
**请描述您的问题.**
ssh,powershell,python等可以批量操作设备，但是telnet协议连接的设备不能批量，有没有相关方法，或者后期会增加么

**Comment by BaiJiangJie** [comment]
嗯，暂时不支持。

将来考虑，对 telnet 协议的资产 和 数据库资产进行批量命令操作，不过目前还没排期。

**Comment by BaiJiangJie** [comment]
最新版本已支持。v3.7
