### ISSUE TITLE
[Bug] web终端UTF-8字符可能出现乱码

### ISSUE THREAD

**Issue by coder014** [jumpserver/jumpserver#10809]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
目前版本均有该bug

**浏览器版本**
~&nbsp;&nbsp;&nbsp;&nbsp;~

**Bug 描述**
web终端（目前发现`koko`组件存在该问题）如果远程输出了 UTF-8 字符，就有概率出现乱码（U+FFFD，�）。

**Bug 重现步骤(有截图更好)**
1. 

```bash
#!/bin/bash
echo -en '\0125\0124\0106\055\070\040\0350\0276\0223\0345\0207'
sleep 1s
echo -en '\0272\0346\0265\0213\0350\0257\0225\012'
```
2. 

![image](https://github.com/jumpserver/jumpserver/assets/68953464/48d0b89f-938e-4f45-aefd-705572d23a75)

**Comment by BaiJiangJie** [comment]
有一个版本修复过，v3.4 版本也存在吗？

**Comment by coder014** [comment]
是的，以上步骤依然能在 v3.4 得到复现，目前看来更像是前端问题。

**Comment by coder014** [comment]
https://github.com/jumpserver/koko/blob/v3.4/ui/src/components/Terminal.vue#L286
```javascript
      this.term.write(decodeToStr(data));
```


`koko`组件中该行，`decodeToStr()`是否应当考虑后端下发的可能是不完整的字节序列，否则就可能因为遇到不完整的UTF-8字节而生成`U+FFFD`。或者说当前将 data 从`Uint8Array`转为`String`是出于何种考虑？因为目前 xterm.js 的 write 方法支持直接传入`Uint8Array`，其内部合理处理了相关问题。

**Comment by BaiJiangJie** [comment]
<img width="273" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/4329520b-d7ea-4b80-829d-26ecedcfe475">

这个文件内容我直接粘在我本地 MacBook Pro 上，使用 iTerm2 执行也显示乱码啊

**Comment by coder014** [comment]
抱歉可能我没有说清楚，这段 shell 需要用`bash`运行，`sh` (POSIX bash) 里的 echo 和 sleep 功能上并不完整。

**Comment by coder014** [comment]
`sleep` 命令也是用的 GNU Coreutils，Mac 中的`sleep`与 Linux 实现并不一致。我的本意就是用`sleep`构造一段延时，让终端的数据流得以在此处能稳定地被截断。

这样也许能在 Mac 下用`bash`正常运行
```bash
#!/bin/bash
echo -en '\0125\0124\0106\055\070\040\0350\0276\0223\0345\0207'
sleep 1 # use `sleep 1s` on Linux
echo -en '\0272\0346\0265\0213\0350\0257\0225\012'
```

**Comment by LeeEirc** [comment]
> https://github.com/jumpserver/koko/blob/v3.4/ui/src/components/Terminal.vue#L286
> 
> ```js
>       this.term.write(decodeToStr(data));
> ```
> 
> `koko`组件中该行，`decodeToStr()`是否应当考虑后端下发的可能是不完整的字节序列，否则就可能因为遇到不完整的UTF-8字节而生成`U+FFFD`。或者说当前将 data 从`Uint8Array`转为`String`是出于何种考虑？因为目前 xterm.js 的 write 方法支持直接传入`Uint8Array`，其内部合理处理了相关问题。

根据测试，Koko 去掉这个前端字符转换确实可以正常显示测试的字符，已经提交到 dev 中，待下个大版本更新。

**Comment by LeeEirc** [comment]
@BaiJiangJie 测试下 dev
