### ISSUE TITLE
[Bug] v3.3.0 版本对 windows 2012 上传文件失败

### ISSUE THREAD

**Issue by sushang123** [jumpserver/jumpserver#10818]
**JumpServer 版本 3.3.0

**Bug 描述**
windows2012文件上传,无法上传，很容易显示超时
特别小的文件，就是一个普通文本，都会显示超时

**Bug 重现步骤(有截图更好)**

![image](https://github.com/jumpserver/jumpserver/assets/1906271/9e1c9787-2970-43f7-b816-799369847992)
![image](https://github.com/jumpserver/jumpserver/assets/1906271/31530017-7c05-4f53-9e02-e72d659a4e53)

![image](https://github.com/jumpserver/jumpserver/assets/1906271/5ec70c9e-3713-4d06-af55-0444e9a443a4)

**Comment by BaiJiangJie** [comment]
v3.4.1 修复了文件上传相关的问题，建议升级到最新版本试一下。

**Comment by sushang123** [comment]
> 

升级到3.4.1以后  在上传文件的地方，服务器名称都找不到了
![image](https://github.com/jumpserver/jumpserver/assets/1906271/29903d47-e544-46e8-892f-be52e5c20f16)
![image](https://github.com/jumpserver/jumpserver/assets/1906271/1d21a582-9a02-496b-9fd5-dd8e432e4629)

**Comment by BaiJiangJie** [comment]
资产是不是没有配置 ssh 协议？

**Comment by sushang123** [comment]
> 资产是不是没有配置 ssh 协议？

Windows 2012也需要配置ssh么？有参考文档吗？

**Comment by BaiJiangJie** [comment]
如果要使用文件管理的话，需要配置。

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/guide/asset_requirements/windows_ssh/?h=openssh

文档看看这个

**Comment by sushang123** [comment]
OK 谢谢
