### ISSUE TITLE
能以Daemon方式启动吗

### ISSUE THREAD

**Issue by helllkz** [jumpserver/jumpserver#1081]
[简述你的问题]
太多日志信息了，能通过daemon方式启动吗
把配置文件的debug修改为false后，css和js文件就不能被访问了
##### 使用版本
V1.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by flapjackegg** [comment]
python run_server.py all  &
这样就是后台启动，或者用 nohub

**Comment by ibuler** [comment]
更新了一个脚本，暂时没有merge，请测试一下

https://github.com/jumpserver/jumpserver/blob/dev/jms

1. 下载或复制内容到项目中 jms文件
2. chmod +x jms
3. 先关闭原来的程序
4. 使用
    ` ` `
     ./jms start all
     ./jms start all -d
    ` ` `
