### ISSUE TITLE
[Question] v2的用户数据直接导入到v3的数据库中，SSH登录失败

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10820]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/106153788/9ea70aac-9e41-4e33-ab54-e3d2936c3e49)
![image](https://github.com/jumpserver/jumpserver/assets/106153788/f4abd744-bb1f-487f-8359-af3dc9abf24d)
加密方式不一样了吗

**Comment by BaiJiangJie** [comment]
config.txt 文件复制过来了吗？

**Comment by wangheng0206** [comment]
> 

秘钥配置都是一样的。
