### ISSUE TITLE
Guacamole无法跳转

### ISSUE THREAD

**Issue by Nidhoggur1993** [jumpserver/jumpserver#1082]
[简述你的问题]
guacamole安装成功，但是web terminal里的windows机器无法跳转，直接输入http://ip/guacamole 提示“连接已关闭”

##### 使用版本
v 1.0.0

##### 问题复现步骤
1. docker安装guacamole，docker start jms_guacamole启动，docker ps能看到进程
`CONTAINER ID        IMAGE                                            COMMAND             CREATED             STATUS              PORTS                    NAMES`
`c06aba5eda47        registry.jumpserver.org/public/guacamole:1.0.0   "/init"             About an hour ago   Up 20 minutes       0.0.0.0:8081->8080/tcp   jms_guacamole`
2. web界面接受guacamole注册
3. web界面进入web terminal，选择windows服务器，点击后没有反应

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/12947582/37509435-4eb24952-2932-11e8-9454-fd7ff5e209c4.png)

![image](https://user-images.githubusercontent.com/12947582/37509417-437d5342-2932-11e8-8dfa-a0db87f3e45d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
@Nidhoggur1993 请查阅faq  docs.jumpserver.org/zh/docs/faq.html#faq

**Comment by Nidhoggur1993** [comment]
@liuzheng 可能是我表述有些问题？
目前是luna可以列出windows和linux，点击linux server可以正常跳转，但是点击windows server没有反应
windows server已经设定了rdp的系统用户，测试连通性应该也是成功的

> 127.0.0.1 [21/Mar/2018:16:27:21 +0800] "GET /assets/system-user/de0cd8dc-d5d5-40b7-8341-b0185b2298c3/ HTTP/1.0" 200 23726
> 127.0.0.1 [21/Mar/2018:16:27:26 +0800] "GET /api/assets/v1/system-user/de0cd8dc-d5d5-40b7-8341-b0185b2298c3/push/ HTTP/1.0" 200 22
> Received task: assets.tasks.push_system_user_to_assets_manual[9cd240ff-d623-47ef-804a-48d5e686ac9f]  
> 2018-03-21 16:27:26 [tasks INFO] push system user `windows-admin` passed, may be not auto push or ssh protocol is not ssh
> push system user `windows-admin` passed, may be not auto push or ssh protocol is not ssh
> Task assets.tasks.push_system_user_to_assets_manual[9cd240ff-d623-47ef-804a-48d5e686ac9f] succeeded in 0.0029194699600338936s: None
> 127.0.0.1 [21/Mar/2018:16:27:26 +0800] "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2
> 127.0.0.1 [21/Mar/2018:16:27:31 +0800] "GET /api/assets/v1/system-user/de0cd8dc-d5d5-40b7-8341-b0185b2298c3/connective/ HTTP/1.0" 200 22
