### ISSUE TITLE
[Question] 發佈外網後，通過外網地址連接不到資產。通過沒網地址可以。

### ISSUE THREAD

**Issue by linfnaa** [jumpserver/jumpserver#10822]
**请描述您的问题.**
版本 3.3.1
錯誤截圖
![mmexport1687760337057](https://github.com/jumpserver/jumpserver/assets/131939078/d99bf168-8a76-4265-b806-b4ce53a9880c)

**Comment by BaiJiangJie** [comment]
从截图看不出是什么问题！

确保 Core 服务和 Lion 服务网络之间互通，Lion 服务和连接的目标资产网络互通。

**Comment by ibuler** [comment]
v2版本外网地址只是一个标识，连接的时候不会使用

**Comment by linfnaa** [comment]
>  我用内网的地址

> 从截图看不出是什么问题！
> 
> 确保 Core 服务和 Lion 服务网络之间互通，Lion 服务和连接的目标资产网络互通。

用内网地址打开web的时候连接超快，在公网地址连web的也挺快，就是在web终端页面连接资产是连不上，一直转圈显示连接中。
内网可以说明core和lion和目标资产网络都是互通的呀。
公网进来咋就不行嘞。头大了
![mmexport1687843049397](https://github.com/jumpserver/jumpserver/assets/131939078/caa9c5eb-e1fc-42e3-b94a-f050ffde5b17)

**Comment by linfnaa** [comment]
> > 我用内网的地址
> 
> > 从截图看不出是什么问题！
> > 确保 Core 服务和 Lion 服务网络之间互通，Lion 服务和连接的目标资产网络互通。
> 
> 用内网地址打开web的时候连接超快，在公网地址连web的也挺快，就是在web终端页面连接资产是连不上，一直转圈显示连接中，提示websocket连接失败，请检查网络 内网可以说明core和lion和目标资产网络都是互通的呀。 公网进来咋就不行嘞。头大了 ![mmexport1687843049397](https://user-images.githubusercontent.com/131939078/249043622-caa9c5eb-e1fc-42e3-b94a-f050ffde5b17.png)
> 
> /

![Uploading mmexport1687843871980.png…]()

**Comment by linfnaa** [comment]
> > 我用内网的地址
> 
> > 从截图看不出是什么问题！
> > 确保 Core 服务和 Lion 服务网络之间互通，Lion 服务和连接的目标资产网络互通。
> 
> 用内网地址打开web的时候连接超快，在公网地址连web的也挺快，就是在web终端页面连接资产是连不上，一直转圈显示连接中，提示websocket连接失败，请检查网络 内网可以说明core和lion和目标资产网络都是互通的呀。 公网进来咋就不行嘞。头大了 ![mmexport1687843049397](https://user-images.githubusercontent.com/131939078/249043622-caa9c5eb-e1fc-42e3-b94a-f050ffde5b17.png)
> 
> /

![Uploading mmexport1687843871980.png…]()

**Comment by BaiJiangJie** [comment]
配服务端点了吗？（系统设置-终端管理-服务端点）

如果用公网地址的话，各组件的端口也需要全部映射出来。
