### ISSUE TITLE
[Question] 资产登录功能，是企业版还是社区版功能？

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10821]
**请描述您的问题.**
<img width="386" alt="559b9c223c3ec1b540eda575b1e5b6a" src="https://github.com/jumpserver/jumpserver/assets/44529247/2c2d9762-03a7-4628-a161-09a6e86c7463">
<img width="162" alt="3f0e3f7d32d451ae6b7248532b7dd0b" src="https://github.com/jumpserver/jumpserver/assets/44529247/857195ef-3353-4ce1-b862-ed198c5d775e">

这个功能是属于社区版功能吗，为啥我的3.4.1没有这个

**Comment by BaiJiangJie** [comment]
`资产登录`企业版功能，Release Note 未做标识，我记录一下。
