### ISSUE TITLE
[Feature] 应用商城增加 “DameWare Mini Remote Control”

### ISSUE THREAD

**Issue by renziyou** [jumpserver/jumpserver#10824]
**请描述您的需求或者改进建议.**
老哥们应用商城能添加一款这个远程工具么 “DameWare Mini Remote Control”

这上内网远程PC的工具非常好用，类似VNC形势，企业用这款的比较多，希望JMS应用商场里能录入

**Comment by BaiJiangJie** [comment]
好的，我们先研究一下。 @wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
@renziyou 测试了下，DameWare Mini Remote Control 自带的协议因为许可的原因无法验证，RDP 和 VNC 连接验证无效，无法继续。
