### ISSUE TITLE
[Question] 终端管理中的 Tinker 是什么？做什么用的？

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#10834]
**请描述您的问题.**
在Jumpserver V3.3.0版本中出現以下兩個終端Thinker，是做什麼用的？剛部署好時沒有這兩個終端
![image](https://github.com/jumpserver/jumpserver/assets/35226938/ddb75d40-a4de-4e2e-8dad-0d479eaa7ffb)

**Comment by BaiJiangJie** [comment]
这个 Tinker 终端是在远程应用发布机上的服务。
