### ISSUE TITLE
能否提供一份windows环境本地项目部署指导

### ISSUE THREAD

**Issue by Lilinfei1024** [jumpserver/jumpserver#1083]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
是需要在Windows服务器上面部署Jumpserver吗？
