### ISSUE TITLE
[Question] 外部系统接入terminal的webshell接口功能

### ISSUE THREAD

**Issue by whiteskylife** [jumpserver/jumpserver#10848]
jumpserver的这个terminal接口功能（webShell），https://jumpserver.fit2cloud.com/koko/terminal/?target_id=xxx&type=ssh&system_user_id=xxx， 可以接入外部系统吗？ 比如想在A系统中，调用这个terminal接口，来实现和jumpserver管理的机器进行webSSH连接。文档中好像没有相关的接口说明
![e89b2c8fb932cae5bae267d7b7aa759](https://github.com/jumpserver/jumpserver/assets/22437514/d21614ec-1425-4078-a762-7962c1a0d802)
![f9d116f5df157188a1298d5f6afc095](https://github.com/jumpserver/jumpserver/assets/22437514/e9753463-fe15-4eb5-b007-564b32b14748)

**Comment by BaiJiangJie** [comment]
目前没有对接文档；

简单描述一下：

1. JumpServer 和 外部系统配置单点登录
2. 外部系统回调中直接调用 "https://jumpserver.com/koko/terminal/?target_id=&type=&system_user_id=" 就可以了。
3. 跳转到 Web Terminal 页面后会默认点击 target_id 指定的资产 id，并且弹窗选择系统用户进行登录。
