### ISSUE TITLE
[Question] 如何修改web界面登录超时时间？

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#10849]
需求：修改web界面登录超时时间为一小时。

**Comment by BaiJiangJie** [comment]
连接 Web 资产后的空闲超时时间，还是什么？

**Comment by vipquan** [comment]
> 连接 Web 资产后的空闲超时时间，还是什么？

只是登录web界面后的空闲时间

**Comment by BaiJiangJie** [comment]
可以在系统设置中设置最大空闲时间，对所有会话生效，包括 Web 资产。

<img width="1405" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2ac88fc5-7bed-4242-8c94-dc99bc642b08">
