### ISSUE TITLE
[Bug] 3.4.1版本website闪退 

### ISSUE THREAD

**Issue by lyace2010** [jumpserver/jumpserver#10846]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.1

**浏览器版本**

**Bug 描述**
WebSite闪退  在Windows尝试启动chrome  报错 0xc0000142
https://demo.jumpserver.org   Demo里的2个WebSite远程Chrome也是不定时闪退
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wojiushixiaobai** [comment]
demo 的应用异常是由于被用户恶意破坏导致，审计日志如下：
https://demo.jumpserver.org/luna/replay/a954174e-cc0f-4d91-89a2-8cd6f6adb392
https://demo.jumpserver.org/luna/replay/0322143d-947e-4db8-a5e0-b2d1581b439e

该用户故意将存储空间填满导致应用无法正常访问，与你的问题并无关联。

**Comment by lyace2010** [comment]
我最后使用3.2.2版本的chrome-win.zip和chromedriver_win32.zip这2个包内的文件 替换发布机内的文件后可以使用
