### ISSUE TITLE
[Bug] 当有ssh密钥记录时,帐号列表页面加载缓慢

### ISSUE THREAD

**Issue by stanhui** [jumpserver/jumpserver#10845]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.0

**浏览器版本**
chrome  110.0.5481.177
Safari     版本15.2 (17612.3.6.1.6)

**Bug 描述**
帐号列表页面
api/v1/accounts/accounts/?asset=&node=&order=-date_updated&offset=0&limit=15&display=1&draw=1
加载缓慢

**Bug 重现步骤(有截图更好)**
1.帐号列表里有多条密文类型是ssh密钥记录时(例如10条)，就会出现
2. 
![9E90B243-9733-4280-9309-AAE6478A74F4](https://github.com/jumpserver/jumpserver/assets/8624140/f653e009-7802-4898-ae70-efe0ebcddad7)

3.

**Comment by BaiJiangJie** [comment]
API 的请求时长应该和密文类型没有关系，估计还是网络有延迟。

**Comment by stanhui** [comment]
> API 的请求时长应该和密文类型没有关系，估计还是网络有延迟。

主要是我能稳定复现，随着ssh密钥记录的增多，加载时间也有增长。删除后就恢复，同时相同条数的密码类型就没有问题。

**Comment by BaiJiangJie** [comment]
好的，那明天（2023.07.06）有时间吗？我们远程看一下。

我本地没有复现。

**Comment by BaiJiangJie** [comment]
如果还有问题在重新打开 issue。
