### ISSUE TITLE
[Bug] 禁用用户后，免密用户依然可以sftp连接到jumpserver

### ISSUE THREAD

**Issue by 580825** [jumpserver/jumpserver#10843]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.14

**浏览器版本**
Chrome 114.0.5735.198（正式版本） (x86_64)

**Bug 描述**
禁用jumpserver用户后，免密用户依然可以使用 sftp 命令连接到jumpserver

**Bug 重现步骤(有截图更好)**
1. 创建普通用户，在jumpserver配置好密码登录
2. 禁用或让该用户到期，使用 sftp 依然可以连上jumpserver，并看到相关服务器

**Comment by BaiJiangJie** [comment]
描述一下详细的复现步骤

**Comment by 580825** [comment]
今天过来发现复现不了了，猜测可能是某个机制通信卡住了，没能及时关闭相关权限
