### ISSUE TITLE
[Bug] 命令过滤

### ISSUE THREAD

**Issue by YuJunping** [jumpserver/jumpserver#10840]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.3.1

**浏览器版本**

**Bug 描述**
命令过滤，会把与命令相同的文件当成命令。如禁用init  ， 实际会把vim init.py 这种也给禁用

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
看一下你配置的命令组信息，应该特殊处理，init 必须是一个单独的语句。

**Comment by wml3** [comment]
尝试用正则表达式的方式，精准匹配命令，如：^init$

**Comment by BaiJiangJie** [comment]
是的，用正则表达式更好一些。
