### ISSUE TITLE
[Question] 远程应用发布报错

### ISSUE THREAD

**Issue by fanmaoyang** [jumpserver/jumpserver#10841]
**请描述您的问题.**
创建应用发布机后，进行连接性测试报下面的错误，看如何解决
![微信截图_20230628124421](https://github.com/jumpserver/jumpserver/assets/46638118/63d432d2-5185-4c1a-9427-c7d810c08d94)

**Comment by wojiushixiaobai** [comment]
把堡垒机重启，你的发布机被你重装过系统或者重置过 SSH，导致信任校验不通过。

**Comment by fanmaoyang** [comment]
我操作了重启堡垒机，然后把发布机的IP修改了下，重新添加。在操作部署的时候又报这个错，帮看要怎么解决
![2](https://github.com/jumpserver/jumpserver/assets/46638118/18314b6c-4b74-4228-9296-838c4bb27171)

**Comment by wojiushixiaobai** [comment]
将发布机的账号改为使用 administrator 账号

**Comment by fanmaoyang** [comment]
我这边重新安装了一台虚拟机server2019,安装成功后设置了允许远程，关闭了server2019的防火墙，操作发布，也是报的相同的错误。我这边堡垒机是通过源码方式安装的v3.4.1版本的
![34](https://github.com/jumpserver/jumpserver/assets/46638118/38032c98-44a7-4b52-a9d5-15f7303f1f89)

**Comment by fanmaoyang** [comment]
堡垒机是从v2升级到v3的版本的，折腾不成功。从新安装堡垒机后，再操作远程应用部署，部署成功了。
