### ISSUE TITLE
[Question] v3.4.1 安装报错

### ISSUE THREAD

**Issue by PoundofAntonio** [jumpserver/jumpserver#10854]
我自己echo debug一下跑到哪个function。
安装到 `6. Init JumpServer Database`,
发现卡住在这句 `docker exec -i jms_core bash -c './jms upgrade_db'`
最后就timeout掉了, 又进了`down_db_ops_env`就有`[ERROR] Failed to change the table structure!`
就没法安装下去。

![image](https://github.com/jumpserver/jumpserver/assets/132991093/2255fd80-f248-4e65-be97-84bdc16d6d6f)

**Comment by BaiJiangJie** [comment]
看日志是 Redis 和 MySQL 服务没有正常提供服务。

为什么会有 upgrade_db 的操作呢？

使用 ./jmsctl install 安装一下。

**Comment by PoundofAntonio** [comment]
我直接跑`curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash`
也是卡住在`6. Init JumpServer Database`不动

![image](https://github.com/jumpserver/jumpserver/assets/132991093/b109e2a1-b407-4638-92a4-51e84e394201)
然后`TimeoutError`就出`[ERROR] Failed to change the table structure!`安装失败了
![image](https://github.com/jumpserver/jumpserver/assets/132991093/8a2c0ad0-940a-41d6-8554-2703a85444b6)

我排查了一下加了两句echo, 那确实跑了upgrade_db, 不知道干嘛就等着timeout又安装失败了
![image](https://github.com/jumpserver/jumpserver/assets/132991093/f5d6c3b4-1ce6-472c-b8aa-0275e6e9c736)

**Comment by wojiushixiaobai** [comment]
无法连接 redis，自行检查网络问题

**Comment by PoundofAntonio** [comment]
Reinstall iptables + try install the new version 3.4.2 seems works

**Comment by ibuler** [comment]
> Reinstall iptables + try install the new version 3.4.2 seems works

got
