### ISSUE TITLE
[Question] 关于v2升级v3 之后无法使用企业微信

### ISSUE THREAD

**Issue by Songxwn** [jumpserver/jumpserver#10855]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/21145071/c772790d-17dd-4509-9db2-5003a6728832)

![49b7bd2a3f840e45e46ab76320cc582](https://github.com/jumpserver/jumpserver/assets/21145071/b3a58b7b-25ff-489d-ba9a-05c5fd9e990a)

请问这又是偷偷改了吗？

**Comment by BaiJiangJie** [comment]
对的，v3 版本的用户认证只支持，LDAP、CAS 了。

其他的认证方式（包括企业微信、钉钉）等，在企业版本中支持。

**Comment by ibuler** [comment]
v2 升级上来的不可以配置，但可以使用
