### ISSUE TITLE
[Bug] 使用 helm 部署从0开始部署，前端报错导致大部分功能无法使用

### ISSUE THREAD

**Issue by Fushengliangnian** [jumpserver/jumpserver#10871]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.1 / 3.4.0 / 3.3.1

**浏览器版本**
Chrome 版本 114.0.5735.106（正式版本） (x86_64)

**Bug 描述**
使用 helm 部署从0开始部署。
最一开始使用的是3.4.1的版本。部署完之后所有涉及到列表的接口前端都会报错 `TypeError: Cannot read properties of undefined`
导致部分页面为空
后面切换到 3.4.0 依然存在。
再然后删除所有表后重新部署 3.3.1 也任然出现。

**Bug 重现步骤(有截图更好)**
<img width="981" alt="image" src="https://github.com/jumpserver/jumpserver/assets/39857406/42a3ea77-fea7-4be0-a6f8-c6131c2dbbdc">

![image](https://github.com/jumpserver/jumpserver/assets/39857406/a7f0dd32-14d4-4247-ab4f-4bdd662c6964)

<img width="1433" alt="image" src="https://github.com/jumpserver/jumpserver/assets/39857406/0079d5af-d73a-43e5-848f-7ed7b4d11864">

<img width="1421" alt="image" src="https://github.com/jumpserver/jumpserver/assets/39857406/78b1828f-bd41-4044-abb8-7d553b445e22">

**Comment by Fushengliangnian** [comment]
后端 api 的数据有正常返回。但是好像是 先发了 [POST/PUT/GET] 等请求后再发的 [Options]
![image](https://github.com/jumpserver/jumpserver/assets/39857406/99b2734d-3811-4596-8bc7-1e6f84d1e781)
![image](https://github.com/jumpserver/jumpserver/assets/39857406/3a47c63e-9e6f-4f3f-ac75-a31e3b8a0a29)

**Comment by wojiushixiaobai** [comment]
检查你的防火墙

**Comment by Fushengliangnian** [comment]
> 检查你的防火墙

不好意思，可以详细一点嘛？客户端的防火墙，还是服务器的？😂

**Comment by wojiushixiaobai** [comment]
都不是，应用防火墙，咨询贵司安全部门的相关同事。
如果防火墙无任何配置，请检查你的 SLB

**Comment by Fushengliangnian** [comment]
slb 做过检查，一开始以为是跨域的问题导致触发了 option 的请求，对 ng 进行调整之后任然出现。

而且option 的请求也不是所有接口都出现。
我现在正在研究，为何会在正常请求之后再次出发 option 请求。

**Comment by BaiJiangJie** [comment]
option 请求是 JumpServer 在渲染表单和列表的时候发送的，属于正常的浏览器请求。

对于页面上渲染报错的问题应该是你环境的问题。

这个我们确定不出来是什么导致的。

按照 @wojiushixiaobai 的提示，应该是网络层面的原因。

**Comment by Fushengliangnian** [comment]
🙏🏻🙏🏻🙏🏻 感谢回复！ 最近暂时没有时间继续排查。后面有时间了，会先研究一下网络的问题，准备把service 改成 nodeport 再试下，有结果再回复。

然后 option 我比较好奇以及困惑的是，在没有触发跨域的情况下，为什么还会触发，重点是option的请求是在正常请求之后触发的。

**Comment by BaiJiangJie** [comment]
好的，有问题随时交流。

一般渲染一个表单，顺序是先发送 OPTION 请求，再发送 GET 请求；

但是触发的时候几乎是同时的，所以浏览器可能会先记录为 GET，再记录 OPTION；

其实先后顺序是没有关系的。

**Comment by Fushengliangnian** [comment]
如果是同时触发，只是返回顺序不同，我是可以理解的。
我的问题描述之外的 第一个评论里有贴F12关于时间的截图，并圈出了 两个请求的时间顺序，结果看起来是先发正常请求，并且等待完成后，再发的option 请求。

**Comment by Fushengliangnian** [comment]
而且根据 F12 console 里的报错信息，感觉是把 option 请求的返回结果当成了正常的请求去处理，导致 undefind 的报错。 很神奇

**Comment by Fushengliangnian** [comment]
哈喽，我想我大概找到原因了，上午改成 nodeport 后可以正常访问。

通过F12观察，和我之前猜想的结果差不多，仍然重复触发了 optings 请求。而我的slb针对于options请求做了空处理，导致出现问题。

我觉得这应该算是一个bug，具体是 axios 的问题，还是后端返回的问题就不清楚了。
而且还有一个问题，同域下为什么会触发option请求呢？

后面我暂时会把 option 的限制去掉。如果你们有了更新的结果，麻烦通知我一下。学习一下🙏🏻🙏🏻🙏🏻

**Comment by BaiJiangJie** [comment]
好的，我们使用 OPTION 请求来获取 API 所需要的数据字段、类型以及默认值，以此来自动生成页面表单。

所以必须开放 OPTION 请求才能正常使用。

@Fushengliangnian
