### ISSUE TITLE
[Question] windows授权不同的协议

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#10872]
**请描述您的问题.**
3.4.1
我的windows资产绑定了rdp和ssh协议，我想根据协议授权给不同的人，应该怎么做
比如我把rdp协议授权给张三，他只能rdp方式登陆，把ssh授权给李四，他只能用ssh方式登陆
现在是只能创建两边windows资产分别绑定ssh和rdp，再分开授权给不同的人吗

**Comment by ibuler** [comment]
细化的控制，还没有做，未来考虑增加这个功能

**Comment by BaiJiangJie** [comment]
已记录。
