### ISSUE TITLE
Maridb镜像无法启动

### ISSUE THREAD

**Issue by minesunny** [jumpserver/jumpserver#10878]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.1

**浏览器版本**
谷歌浏览器Version 114.0.5735.198 (Official Build) (arm64)

**Bug 描述**
Maridb镜像无法启动

**Bug 重现步骤(有截图更好)**
1.curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
2.
<img width="1954" alt="image" src="https://github.com/jumpserver/jumpserver/assets/98507458/17c7e06e-9bb0-483b-ac24-ec612f49dacb">

3.
<img width="1956" alt="image" src="https://github.com/jumpserver/jumpserver/assets/98507458/3bcf8abc-5a0d-4ca2-9e3c-d55e7fe148e3">

**Comment by wojiushixiaobai** [comment]
奇怪，为啥提示权限不足？你挂载了 NFS？还是对持久化目录进行了权限定制？

**Comment by minesunny** [comment]
> 奇怪，为啥提示权限不足？你挂载了 NFS？还是对持久化目录进行了权限定制？

没有挂载，就是用的腾讯云服务器，所有目录的权限，磁盘都是默认的资源配置

**Comment by wojiushixiaobai** [comment]
你把 /data/jumpserver 备份后重命名或者移除，然后重新执行 
```sh
jmsctl init_db
```
看看问题是否解决

**Comment by minesunny** [comment]
> 你把 /data/jumpserver 备份后重命名或者移除，然后重新执行
> 
> ```shell
> jmsctl init_db
> ```
> 
> 看看问题是否解决，出现此问题的原因是 maridb 的 socket 文件无法被 mariadb 读取
> 
> * [Bind on unix socket: Permission denied MariaDB/mariadb-docker#363](https://github.com/MariaDB/mariadb-docker/issues/363)

不行的。

**Comment by wojiushixiaobai** [comment]
我通过腾讯云新建了一个 Ubuntu 虚拟机，并未复现你的问题，我可能需要查看你的环境才能定位问题。

**Comment by minesunny** [comment]
> 我通过腾讯云新建了一个 Ubuntu 虚拟机，并未复现你的问题，我可能需要查看你的环境才能定位问题。

我将ssh登录证书发给你邮箱

**Comment by wojiushixiaobai** [comment]
我的邮箱是 296015668@qq.com
如果你方便的话，我们可以用微信沟通下，微信号也是 296015668

**Comment by minesunny** [comment]
Ubuntu使用了kali镜像源，导致Ubuntu变成kali了，已重新更改Ubuntu，已安装成功
![image](https://github.com/jumpserver/jumpserver/assets/98507458/1300d3e0-9d38-4f89-96c8-074285d5cfb4)
<img width="1956" alt="image" src="https://github.com/jumpserver/jumpserver/assets/98507458/e0c45df4-90c1-4599-a165-eb607d6c3a1d">
