### ISSUE TITLE
[Bug] 应用发布闪退

### ISSUE THREAD

**Issue by Lekou520** [jumpserver/jumpserver#10881]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.1/3.4.2

**浏览器版本**
Chrome 114.0.5735.134

**Bug 描述**
使用Windows 2016/2019测试均出现此问题，链接进入系统后，黑屏随即跳转到windows用户注销界面，随后关闭连接状态。
手工测试应用发布机内自动安装的chrome浏览器报错0x000142。

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![image](https://github.com/jumpserver/jumpserver/assets/76936213/9dd43b62-72af-4ed7-a557-d411007d62fa)

**Comment by wojiushixiaobai** [comment]
已知问题，等待我们优化

**Comment by Lekou520** [comment]
是否有缓解方案
