### ISSUE TITLE
[Bug] Chrome 远程应用连接资产时隐藏地址栏后找不到下载

### ISSUE THREAD

**Issue by wdwnet** [jumpserver/jumpserver#10886]
JumpServer 版本v3.4.1

有些Chrome 远程应用的应用内有下载文件功能，但Chrome隐藏地址栏后也没有菜单，下载文件后无法打开下载文件夹，导致功能无法正常使用

**Comment by BaiJiangJie** [comment]
文件可以正常下载吗？

下载完成后，下方应该会显示文件列表吧。

<img width="1880" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1c204fff-f6a2-45e5-a03a-688f2a6c0a66">

**Comment by BaiJiangJie** [comment]
<img width="2040" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/bbcd6ff8-c693-4f72-8daa-db618c1a9c2c">

**Comment by BaiJiangJie** [comment]
<img width="1497" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/0ead056c-62cf-42fb-af59-6cef6489c8c4">

**Comment by BaiJiangJie** [comment]
下载之后下方从文件夹中打开，这样就会打开文件管理器，然后查看所有下载到本地的文件了。

**Comment by wdwnet** [comment]
> 下载之后下方从文件夹中打开，这样就会打开文件管理器，然后查看所有下载到本地的文件了。

之前chrome地址栏没有被隐藏的时候是可以正常下载文件的，现在地址栏隐藏后下载功能无法正常使用了

**Comment by BaiJiangJie** [comment]
我上面测试的结果是可以正常使用的。

v3.5 版本对 Chrome 浏览器有一些优化，到时候再试一下。
