### ISSUE TITLE
[Bug] 使用批量导入账号功能无法导入带有部分生僻字的账号

### ISSUE THREAD

**Issue by Xyuncheng** [jumpserver/jumpserver#10887]
**JumpServer 版本**
v3.4.1

**Bug描述**
在批量导入账号的时候，下载了csv的模板去导入账号，在名称那里输入带“昇”字时会报错，xlsx则无此现象。

**Bug 重现步骤(有截图更好)**
1.账号管理>账号列表>导入
2.点击导入，下载CSV的模板之后，打开对应的csv文件，在名称那一列输入名称为”某某昇“
![image](https://github.com/jumpserver/jumpserver/assets/137035261/b9c1b91f-8107-4404-b6d2-2fa00143e574)
3.上传对应的csv文件，报错如下：
![image](https://github.com/jumpserver/jumpserver/assets/137035261/06f2fad4-d990-4753-ab87-7debba07a4e7)

**Comment by BaiJiangJie** [comment]
<img width="1497" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/67db5e66-91e4-45a8-97c6-01dbb63865ad">

**Comment by BaiJiangJie** [comment]
我下载的也是 csv 文件可以啊。

**Comment by BaiJiangJie** [comment]
[account_2023-07-05_17-49-37.csv](https://github.com/jumpserver/jumpserver/files/11956463/account_2023-07-05_17-49-37.csv)

试一下这个文件

**Comment by Xyuncheng** [comment]
使用您提供的文件是可以正常导入，但是我重新下载模板之后还是不行，下面的文件是我测试用的文件：

[account_2023-07-05_17-51-57.csv](https://github.com/jumpserver/jumpserver/files/11956702/account_2023-07-05_17-51-57.csv)

将您的文件内容复制到我下载的模板中也没能正常导入，以下是相关截图：
![image](https://github.com/jumpserver/jumpserver/assets/137035261/367732d9-d48a-4319-9e6d-25964f0b9201)
![image](https://github.com/jumpserver/jumpserver/assets/137035261/64242e6b-6f5b-42b1-926d-5dde19d9adbc)

**Comment by BaiJiangJie** [comment]
看一下你的 excel 软件使用的是什么编码？

**Comment by Xyuncheng** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/137035261/b55f2505-7a55-4cfd-b7f0-57c541b3a2b3)

**Comment by BaiJiangJie** [comment]
改成 utf8 格式的可以吗？
