### ISSUE TITLE
v1.0.0 在线会话里已经关闭的web终端信息依然存在

### ISSUE THREAD

**Issue by Spinestars** [jumpserver/jumpserver#1088]
[简述你的问题]
1.打开web终端,并关闭
2.在线会话列表依然存在已经关闭的会话信息

##### 使用版本
[v1.0.0]

##### 问题复现步骤
1.打开web终端,并关闭
2.在线会话列表依然存在已经关闭的会话信息

##### 其他

[注:] 完成后请关闭 issue

**Comment by huangzx** [comment]
我也碰到这个问题。是不是必须在终端中执行 exit，会话才真正退出？

PS：有图为证
测试环境，只有一个人用，所有的终端都关了，但是在线会话数量：
![image](https://user-images.githubusercontent.com/3265516/37564111-ba7dfe66-2ac1-11e8-8cbe-11d3f854afa1.png)

**Comment by ibuler** [comment]
可以联系我远程观察一下

**Comment by huangzx** [comment]
重现很简单。
打开终端，退出时不执行 exit 命令，而是直接关闭网页或luna的标签页。然后服务器执行 who 命令会看到该用户。

**Comment by ibuler** [comment]
关闭网页或标签页时，session不会立刻结束的，而是有一个超时时间，因为有时网络情况没那么好，断线重连的，默认应该是 1分钟

**Comment by huangzx** [comment]
那，如果终端卡死的情况呢

**Comment by ibuler** [comment]
终端卡死，请附上日志，应该是哪里有异常了，我看看怎么解决

**Comment by huangzx** [comment]
好，多谢！
