### ISSUE TITLE
[Bug] 使用下载的用户导入模版，导入失败

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#10894]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.2

**浏览器版本**
Chrome 114.0.5735.133

**Bug 描述**
使用下载的用户模版，修改信息后导入，提示手机号格式错误
![image](https://github.com/jumpserver/jumpserver/assets/104493699/5122d8e2-479c-4054-9107-b052b844ef15)
将表格中的手机号修改，只填写手机号导入成功
<img width="915" alt="image" src="https://github.com/jumpserver/jumpserver/assets/104493699/3cc2b0c0-3f54-44e6-b66c-55c3b52e3299">
![image](https://github.com/jumpserver/jumpserver/assets/104493699/e7250781-ca06-42e0-bd8c-8423af80cd72)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
嗯，最新版本确实有问题。没有对 dict 类型的手机号字段进行处理。

v3.4.3 和 v3.5 版本会修复。
