### ISSUE TITLE
[Feature] 建议在工作台当中增加快速访问资产的入口，方便连接。

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#10890]
**请描述您的需求或者改进建议.**
工作台中增加快速访问入口，原型图如下入所示：
<img width="1475" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/4bfd3187-4ce0-4454-ba02-8fead3df73cd">

**Comment by BaiJiangJie** [comment]
嗯，可以考虑和我的资产列表页面的跳转逻辑一样，点击`连接` 跳转到 Luna 页面，选择账号进行登录。

这样会比直接使用当前会话的账号要灵活一些。

**Comment by BaiJiangJie** [comment]
计划 v3.6 版本支持。

**Comment by huskiesir** [comment]
> 计划 v3.6 版本支持。

嗯，做的时候，感觉还可以考虑能够批量打开资产连接的情况

**Comment by BaiJiangJie** [comment]
嗯，v3.6 版本再考虑批量打开的功能，但是有难度。

浏览器本身不支持同时打开多个窗口，所以还得多考虑考虑方案。

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持。
