### ISSUE TITLE
[Question] 有没有直连资产时直接按资产名指定链接

### ISSUE THREAD

**Issue by mz5c** [jumpserver/jumpserver#10898]
**请描述您的问题.**
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
上面Assetip要求资产的ip是唯一的，但现实情况存在ip相同，登录端口不同，资产名唯一的情况，这个时候按资产名直连岂不是更好

**Comment by BaiJiangJie** [comment]
资产名称可能会包含特殊字符，不是很通用。

v2 版本支持同时指定 systemUserID 和 AssetID

如：`ssh jumpserverUsername@systemUserID@AssetID@jumpserverHostIP -p2222`

v3 版本只支持使用 AssetIP

如果有重复的 IP，会列出来，再选择连接哪一台。

**Comment by mz5c** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/6127329/c4def8c9-c15b-4905-8e43-139e67f1ed5e)
VScode连接资产时如果资产ip不是唯一的，如上图报错，这个情况有没有解决方案

另外如果出现重复的ip，能不能以非交互方式根据额外参数直接选择某个资产登录，比如
`ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222 -t 1`
上面命令，我是希望它执行后进入资产选择页按`-t 1`中的1选择资产ID为1的资产直接登录
这个方案当前有没有类似的实现

**Comment by BaiJiangJie** [comment]
对的，目前 vscode 连接如果资产 IP 有重复会执行报错。

-t 的话，用户也不知道第几个是想要登录的那台资产。

所以，v3 版本，后续会考虑`资产信息`支持 `资产IP` 和 `资产ID` 两种方式。

`ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`
`ssh jumpserverUsername@systemUsername@AssetID@jumpserverHostIP -p2222`

**Comment by BaiJiangJie** [comment]
你用的是v2还是v3？

**Comment by mz5c** [comment]
用的v3

**Comment by mz5c** [comment]
v3版本计划什么时候考虑资产信息支持 资产IP 和 资产ID 两种方式。

**Comment by BaiJiangJie** [comment]
好的，目前计划 v3.6 版本支持。

**Comment by mz5c** [comment]
> 
这个按资产id直连的功能在v3.6实现了吗

**Comment by BaiJiangJie** [comment]
实现了。

**Comment by BaiJiangJie** [comment]
<img width="1390" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/9f7e2e98-cef9-466c-9f12-3b6b94624c39">

**Comment by Dbgsaoge** [comment]
您好现在用两台主机同样是设置下用vscode ssh链接，一台主机可以成功登入，另一台也会报错资产不唯一的情况，请问有办法解决吗
