### ISSUE TITLE
[Feature] 希望增加登录审批功能，类似谷歌登录审批

### ISSUE THREAD

**Issue by MrYangyt** [jumpserver/jumpserver#10907]
希望增加登录审批功能，类似谷歌登录审批，登录的时候点击确认才能登录机器。可以结合企业微信或者钉钉等webhook进行审批登录操作

**Comment by BaiJiangJie** [comment]
目前企业版本支持。

**Comment by BaiJiangJie** [comment]
<img width="2213" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/70aebf72-debf-4d94-aead-bae9438d83d7">
<img width="2523" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/0916ebbb-92fa-4b20-a822-c32b9bc153bb">

**Comment by MrYangyt** [comment]
好的👌
