### ISSUE TITLE
[Feature] 添加网络设备，涉及2次密码验证的，如enable密码，登录账号那边如何配置？

### ISSUE THREAD

**Issue by haining-zhn** [jumpserver/jumpserver#10906]
**请描述您的需求或者改进建议.**
在添加思科交换机时，登录设备需要enable密码登录，这个在堡垒机侧该如何配置，谢谢。

**Comment by BaiJiangJie** [comment]
这个需求目前支持，需要使用账号切换的功能。

首先，在资产平台中，查看账号切换方式，设置为 enable。

其次，在资产的账号列表中，创建两个账号，一个是 enable账号（用户名随便写，建议设置为 null）；一个是登录账号（如：web）。
更新 enable 账号时，切换自 设置为 web。

资产授权时授权 enable 账号。

这样配置完成后，在登录资产时会先使用 web 账号登录资产，然后再使用 enable 账号输入密码进行切换。

**Comment by BaiJiangJie** [comment]
<img width="2550" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/21655c3a-4105-43e7-9d96-f05f25245aa7">
<img width="2018" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/871292cd-0266-4dc2-bb80-3dcc9b03ddb0">

**Comment by haining-zhn** [comment]
直接登录时使用enable登录的，我理解是继承了开始创建的用户名密码，登录后顺次使用enable，解决了，谢谢！
![2](https://github.com/jumpserver/jumpserver/assets/70742886/d1f85423-9739-41e7-ba1d-5c990f8df15a)
