### ISSUE TITLE
可以直接在0.3.2的基础上升级为0.5.0吗？

### ISSUE THREAD

**Issue by Ishelp** [jumpserver/jumpserver#1091]
[简述你的问题]

##### 使用版本
[使用的Jumpserver版本 0.3.2]

##### 其他
您好，打扰了，请问可以直接在0.3.2的基础上升级为5.0的吗？还有wiki上的0.5.0和版本的v1.0.0是一样的吗？

**Comment by ibuler** [comment]
不可以
