### ISSUE TITLE
[Feature] 资产移动不实时刷新，需要手动更新

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#10918]
**请描述您的需求或者改进建议.**
这个不知道是不是跟上面提的资产数量更新原理一样，因为业务需求，或涉及资产移动，无法及时更新。
移动资产时不显示移动信息 (例如将勾选资产移动至xxx节点)，容易忘，且移动时无法看到被移动节点和移动节点信息(例如当前节点移动到当前节点，无法看到进度和结果)

**Comment by BaiJiangJie** [comment]
是的，移动完成后需要手动刷新。

**Comment by jstbw** [comment]
这个可以优化吗，缩短刷新时间间隔，现在的太长了
