### ISSUE TITLE
[Feature] 资产树、类型树里资产数量更新滞后严重

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#10916]
**请描述您的需求或者改进建议.**
已经发现过很多次，手动“校验资产数量”太鸡肋，不知道为什么到了v3会反向升级，虽然之前说之所以异步同步是为了降低消耗，但这理由太牵强，绝大部分用户资产数量没那么多，没必要用异步方式，可以改成v2的么，或者加个配置项？
![image](https://github.com/jumpserver/jumpserver/assets/66759501/4564bad9-9991-441a-801a-7a4da29298ac)

**Comment by BaiJiangJie** [comment]
暂时不考虑修改。

**Comment by jym503558564** [comment]
咱不支持，就先关闭了。
