### ISSUE TITLE
[Feature] 资产树支持自定义展开层级

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#10919]
**请描述您的需求或者改进建议.**
目前默认不展开资产树节点，如果有多级的时候很不方便，应添加设置默认展开层级

**Comment by BaiJiangJie** [comment]
左侧树一般都是使用异步加载的，指定层级后端不太好处理。

暂时不考虑了。

**Comment by Fallen-Breath** [comment]
同样有这个需求，每次进入 web 终端时都需要手动展开资产树，挺麻烦的。

后端不好做的话可以考虑前端自动拉取展开？除此之外目前 web 终端页面也能关闭异步加载资产树，这个时候好像是走 `api/v1/perms/users/self/nodes/all-with-assets/tree/` 一次拉足数据的，应该足够让前端自动展开资产树显示了

**Comment by jym503558564** [comment]
暂时不考虑，我们将关闭Issues，如后续版本有支持该计划，我们将在公布在release-notes。
