### ISSUE TITLE
[Bug] 粘贴多行命令执行，命令记录记录异常，多条命令记录到到一条

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10928]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
core:V3.4.1
koko:V3.4.1
**浏览器版本**

**Bug 描述**
粘贴多行命令执行，命令记录记录异常，多条命令记录到到一条

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/106153788/f9a4cce2-4ed0-4dcd-a687-4177c6faa652)

![image](https://github.com/jumpserver/jumpserver/assets/106153788/a512f1c8-d899-43cf-bbd1-7352612e80b8)

**Comment by BaiJiangJie** [comment]
目前只能作为一条命令记录。
