### ISSUE TITLE
[Bug] 机器一直在线，但每隔时间在站内信通知提示“终端已离线”

### ISSUE THREAD

**Issue by ivancxj** [jumpserver/jumpserver#10934]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.0

**浏览器版本**
chrome

**Bug 描述**
有一台机器一直在线的（改过名称），但每隔时间在站内信通知提示“终端已离线”，不知道问题在哪？

**Bug 重现步骤(有截图更好)**
![WechatIMG636](https://github.com/jumpserver/jumpserver/assets/2024637/105dd461-3af7-494c-a15b-b01b149d1657)

![截屏2023-07-10 10 29 51](https://github.com/jumpserver/jumpserver/assets/2024637/b8ef3c24-ba8f-40b9-9c0e-eb90bfd873d8)

![截屏2023-07-10 10 29 41](https://github.com/jumpserver/jumpserver/assets/2024637/e7ff3da7-d4ee-453c-92df-9ab0251f346a)

**Comment by wml3** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/49503874/d6e193bc-e7c0-4890-8afe-bfbd587ed544)
v2.28.16版本，有相同现象

**Comment by BaiJiangJie** [comment]
看看终端管理、终端列表中的组件还在线吗？

**Comment by ivancxj** [comment]
> 看看终端管理、终端列表中的组件还在线吗？

终端jump-new_10-111-12.204不在了。但对应的机器ip 10.111.12.204实际还是在的，并且名称已不是这个

**Comment by ivancxj** [comment]
> 离线的删掉就可以了。

资产列表已没有jump-new_10-111-12-204这台机器，但还是会离线告警。

**Comment by ivancxj** [comment]
> 



> 离线的删掉就可以了。

嗯，删掉了

**Comment by wml3** [comment]
检查了一下，多个节点，采用不同redis的时候，也会出现该情况

**Comment by liukunpeng-me** [comment]
系统设置 - 组件设置 页面下的 组件管理 里面删除发布机组件即可
