### ISSUE TITLE
[Question] " Connect Websocket failed " notification

### ISSUE THREAD

**Issue by ahmadinejad** [jumpserver/jumpserver#10932]
when I install jumpserver in source code deployment code mode and after finish installation , when I want to login it , show the "
Connect Websocket failed" notification to me.
what's that reason and how to solve it?

**Comment by BaiJiangJie** [comment]
Use `./jms start` to start the service.

**Comment by ahmadinejad** [comment]
I started it and when login it , notify me that's message.

**Comment by BaiJiangJie** [comment]
<img width="1291" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/559b4360-c20f-4889-a1a9-1f3f50c3ad77">

You need to modify the configuration file of the lina component

**Comment by ahmadinejad** [comment]
thnx for your reply. so I must be copy .env.development.example to .env.development and then repackage lina?

**Comment by BaiJiangJie** [comment]
Yeah

**Comment by ahmadinejad** [comment]
thnx. I do it and reply to you that's result.

**Comment by BaiJiangJie** [comment]
Then your problem of websocket connection failure is solved?

**Comment by ahmadinejad** [comment]
no, I don't it now.  I will do it and then reply to you.

**Comment by ahmadinejad** [comment]
Hi. I do that but it is not correct.
![Screenshot 2023-07-23 091731](https://github.com/jumpserver/jumpserver/assets/53111373/eab3d4ba-27a3-4d15-b45d-43a6701a3936)

**Comment by BaiJiangJie** [comment]
Then don't know why.
