### ISSUE TITLE
jumpserver-v1.0.0 luna 使用cat,tail和less查看日志文件问题

### ISSUE THREAD

**Issue by devon6686** [jumpserver/jumpserver#1093]
[简述你的问题]

##### 使用版本
Jumpserver版本 1.0.0

##### 问题复现步骤
1. 使用luna，在web终端连接上一个主机时，打开主机上一个日志文件，使用cat, tail，less命令时就会卡住，无显示，只能关闭连接；而使用vi命令是可以打开的。

##### 具体表现[截图可能会更好些,最好能截全]
![q-jump1](https://user-images.githubusercontent.com/15604228/37629222-8f89903c-2c18-11e8-8ab9-10023742c393.PNG)
![q-jump2](https://user-images.githubusercontent.com/15604228/37629231-93e6933c-2c18-11e8-9493-bc8cf227e1a3.PNG)
![q-jump3](https://user-images.githubusercontent.com/15604228/37629233-9569d656-2c18-11e8-9436-b5ac98ece9db.PNG)

nginx error日志如下：

2018/03/20 08:23:45 [error] 11613#0: *19217 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.50.34, server: , request: "POST /socket.io/?EIO=3&transport=polling&t=M90o_V_&sid=4cdc127a550742af902f65b38c0f4780 HTTP/1.0", upstream: "http://[::1]:5000/socket.io/?EIO=3&transport=polling&t=M90o_V_&sid=4cdc127a550742af902f65b38c0f4780", host: "xxx.xxxx.com", referrer: "https://xxx.xxxx.com:4443/luna/"
2018/03/20 08:23:45 [error] 11612#0: *19224 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.50.34, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=M90o_aK&sid=4cdc127a550742af902f65b38c0f4780 HTTP/1.0", upstream: "http://[::1]:5000/socket.io/?EIO=3&transport=polling&t=M90o_aK&sid=4cdc127a550742af902f65b38c0f4780", host: "xxx.xxxx.com", referrer: "https://xxx.xxxx.com:4443/luna/"

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed
