### ISSUE TITLE
[Feature] 能否支持远程桌面时多显示器显示

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#10930]
能否支持远程桌面时多显示器显示，也就是使用rdp连接时勾选，"将我的所有监视器用于远程会话"
![企业微信截图_1688726611179](https://github.com/jumpserver/jumpserver/assets/54871762/cc275d02-7cfc-4e7d-95dc-fa6cc4a0f5c2)

**Comment by wojiushixiaobai** [comment]
不支持

**Comment by MAOUXSAKI** [comment]
能否加一个高级选项支持多屏

**Comment by BaiJiangJie** [comment]
先调研一下看看能不能支持。

**Comment by BaiJiangJie** [comment]
Web 方式访问不支持。因为是浏览器里的一个窗口。

本地客户端的方式支持多屏显示。（企业版）

**Comment by MAOUXSAKI** [comment]
我现在用的是企业版，但是怎么切换开启双屏呢

**Comment by MAOUXSAKI** [comment]
我这边咨询知道了可以通过该远程文件可以支持多屏，但确实是不方便。能否在高级选项中加个开关支持多屏显示的开启与关闭
![image](https://github.com/jumpserver/jumpserver/assets/54871762/91451a6f-1581-4a6b-b37d-35e066720e07)

**Comment by BaiJiangJie** [comment]
计划 v3.6 版本再高级选项中支持。

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持。配置使用多屏显示。
