### ISSUE TITLE
[Question] /users/users/{id}/pubkey/reset/ 通过该接口上传用户ssh公钥，上传后在数据库中users_user表用户对应pubkey字段数据为null

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#10935]
**请描述您的问题.**
调用后该接口正常返回200，没有对应报错。数据发生改变，对应用户公钥字段变为null。 PATCH 和 PUT 方式都尝试了，情况一样。

**Comment by Sanbobo1** [comment]
应该怎样正确调用呢

**Comment by Sanbobo1** [comment]
使用/api/v1/users/users/ 接口 ，在用户创建时 数据的pubkey就加上公钥字段上传，查看数据库，pubey字段有编码过的公钥数据，但用户使用对应私钥登录时，仍然失败。

**Comment by BaiJiangJie** [comment]
public_key 只能用户自己修改。

<img width="1631" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/4146f020-a511-4b91-83b4-b841badd4bbd">

**Comment by Sanbobo1** [comment]
好的 已解决 感谢回答
