### ISSUE TITLE
[Bug]  mac 客户端无法打开，因为“无法验证开发者”

### ISSUE THREAD

**Issue by JulianZhang** [jumpserver/jumpserver#10946]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.4.1

**浏览器版本**
client 看不出版本，md5sum信息如下

3387817e7a048a2c766e27f9576df124   JumpServer-Client-Installer-arm64.dmg

**Bug 描述**
app 无法打开，提示无法验证开发者
是没有做开发者签名吗？

**Bug 重现步骤(有截图更好)**
1、完成安装client安装
2、点击app，或者启用客户端ssh
<img width="272" alt="截屏2023-07-12 09 55 02" src="https://github.com/jumpserver/jumpserver/assets/1280015/9eb6b885-3748-4cd8-b5b9-4eb412d8a78f">

**Comment by BaiJiangJie** [comment]
目前没有认证，在系统设置-安全里应该可以允许打开。

**Comment by JulianZhang** [comment]
> 目前没有认证，在系统设置-安全里应该可以允许打开。

目前还没有计划增加签名吗？

**Comment by BaiJiangJie** [comment]
暂时没有，将来考虑企业版本增加 Client 签名。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
