### ISSUE TITLE
[Question] 编译安装后lion组件配置文件问题

### ISSUE THREAD

**Issue by daddy2000** [jumpserver/jumpserver#10947]
目前整套是通过编译安装部署的，由于需求需要不能使用docker。现在遇到问题为，已知lion组件可以修改xrdp的显示效果，但在lion的配置文件内添加文档对docker安装的对应配置，并不能增加远程背景、字体光滑等效果。
在lion的配置文件config.yml中添加的参数为：
JUMPSERVER_DPI: 240
JUMPSERVER_ENABLE_FONT_SMOOTHING: true
JUMPSERVER_ENABLE_THEMING: true
JUMPSERVER_ENABLE_WALLPAPER: true

以上均无效果。
想询问下，是否是添加位置错误或参数错误，如何可以解决编译安装情况下需要增加xrdp的一些显示效果的配置？
谢谢。

**Comment by wojiushixiaobai** [comment]
写入环境变量里面
```sh
export JUMPSERVER_DPI=240
```
...
然后重启 lion

**Comment by daddy2000** [comment]
感谢，DPI的配置已经生效了。
但是后几个布尔值的参数，在环境变量中尝试使用字符串并没有生效。

**Comment by wojiushixiaobai** [comment]
```sh
export JUMPSERVER_ENABLE_FONT_SMOOTHING=true
```

**Comment by daddy2000** [comment]
![企业微信截图_16891307103337](https://github.com/jumpserver/jumpserver/assets/19424761/6840b3cc-a5f0-4052-af2b-0f92d16f5a09)
![企业微信截图_168913073629](https://github.com/jumpserver/jumpserver/assets/19424761/a60d6ceb-0ff6-4846-a0fa-fce4ab2a0e52)
是的，确实如此配置。并且source profile后重启了lion。但依然得到的是图2的情况，没有加载背景和主题，字体也没有平滑。

**Comment by wojiushixiaobai** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
使用了那个版本的 Lion ，可以看看 guacd 是否有相关数据。调整 guacamole server 的日志级别排查下
![image](https://github.com/jumpserver/jumpserver/assets/32626707/70ec77a9-c22a-4fa2-918e-dc77dcab73b4)
如果没有设置值，这里会显示 “Parameter "enable-wallpaper" omitted. Using default value of 0.”

**Comment by daddy2000** [comment]
![企业微信截图_16891484862975](https://github.com/jumpserver/jumpserver/assets/19424761/2f5b3614-6978-4769-a7f9-3c2f5db0a862)
从guacd的日志来看，貌似dpi也没有生效。。。已确认在系统环境变量下可以查看到对应参数的值的情况下重启的lion后得到的日志。
lion版本v3.3.1-linux-amd64

**Comment by LeeEirc** [comment]
通过什么方式启动的 lion ？如果使用的 service 方式启动，需要指定环境变量。

```
....
[Service]
# Get network environmental variables
EnvironmentFile=/etc/lion-environment

# Env Vars
Environment=JUMPSERVER_ENABLE_FONT_SMOOTHING=true
.....
```

**Comment by daddy2000** [comment]
感谢帮助，service启动方式建立环境变量参数文件，在service文件中添加EnvironmentFile，已经全部生效。
