### ISSUE TITLE
[建议]创建资产的ip和公网ip信息

### ISSUE THREAD

**Issue by Spinestars** [jumpserver/jumpserver#1094]
[简述你的问题]

##### 使用版本
1.0.0.0

##### 问题复现步骤
1.能否将ip栏和公网ip栏的描述文字改成内网ip和外网ip,同时实现下面功能:
即:
测试链接的时候,自动连接内网ip,如果内网ip不通,则通过外网ip连接.

缘由:
实际生产环境中,特别是云环境中,涉及到多个aws账户和大区,所以机器很多都不在同一个内网环境内
按照当前的设定方式,
一个是连接ip(此时我只能设置外网),
一个是公网ip(....这里我再写个外网IP,没有意义)
从而没有填写内网ip的地方

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果连接多云环境 如果可以使用gateway呢，

比如每个云环境暴露一台机器，它又公网IP，连接时以它为网关跳过去

ProxyCommand机制

**Comment by Spinestars** [comment]
是一种方式 @ibuler 
3Q
