### ISSUE TITLE
会话审计中记录密码问题

### ISSUE THREAD

**Issue by jianfzhu** [jumpserver/jumpserver#10952]
使用jumpserver vnc 登录到机器，输入锁屏密码或打开网页输入密码会记录到会话审计-> 命令记录中。如下：

$ elasi Backspace Backspace Backspace Backspace Backspaceelastic Tab ShiftS Backspace ShiftElk Enter

好像是按下shift 键后就开始记录输入数据， 哪里可以配置不记录密码？

**Comment by BaiJiangJie** [comment]
这个其实是记录了键盘操作，记录过程中其实是不知道是不是密码或者敏感信息的。

**Comment by jianfzhu** [comment]
测试下来，按了Shift 键后才激活记录，是不是Shift 键是个快捷键啊？可以更改吗？

**Comment by BaiJiangJie** [comment]
不是特殊设置的快捷键，可能 Shift 触发了键盘的记录。

**Comment by jianfzhu** [comment]
命令行终端输入密码虽然也按了SHIFT 键，但是没有记录。 这个只存在vnc 环境中。

**Comment by BaiJiangJie** [comment]
vnc 或者 rdp 方式连接资产都会出现，属于图形化方式连接的键盘记录功能。

如果觉得危险系数比较高的话，就考虑做一个全局配置，资产连接是否允许记录用户键盘操作。

**Comment by BaiJiangJie** [comment]
目前的方案是：管理员设置 Lion 组件的命令存储为 null，这样就不会记录用户的键盘操作了。
