### ISSUE TITLE
添加新服务器授权服务器时系统用户无法推送

### ISSUE THREAD

**Issue by penglongsd** [jumpserver/jumpserver#1095]
[简述你的问题]
centos 6.8
jumpserver 5.0使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. 添加服务器资产和添加管理用户测试连接OK
2. 把资产添加到已有的项目组中（其他资产已授权都可以连接通）重新手动再次提交授权，和删除项目组，再次重新授权对项目组（包含这台设备）都无法重新推送过去系统管理用户。
##### 具体表现[截图可能会更好些,最好能截全]
 UNREACHABLE! => {"changed": false, "msg": "Authentication failure.", "unreachable": true}
![image](https://user-images.githubusercontent.com/37572795/37641771-f15c7e22-2c55-11e8-8162-f22102eeee74.png)

请问，这个是哪方面的问题

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
那重新手动推送试试呢？

**Comment by penglongsd** [comment]
点击手动推送时也没有效果，比较麻，现在我的处理方式是手动在服务器上建立同步用户和密码，这样就可以连接了。

**Comment by ibuler** [comment]
那有可能是管理账号密码有问题

**Comment by wojiushixiaobai** [comment]
0.5版本我记得以前做个这个测试，但是没有发现问题，现在在新版本1.0.0上面重新测试了一遍，也没有重现这个问题。。建议检查下资产环境。。

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
