### ISSUE TITLE
[Feature] 优化sz/rz命令上传下载

### ISSUE THREAD

**Issue by zeng202211** [jumpserver/jumpserver#10950]
**需求**
相比2.x版本, 升级后, sz/rz命令的上传下载慢了很多, 建议优化sz/rz命令上传下载功能
**jumpserver社区版**
v3.4.3
**浏览器**
Microsoft Edge
版本 114.0.1823.79 (正式版本) (64 位)

**Comment by BaiJiangJie** [comment]
v2和v3版本对于 rz/sz 应该变化不大，新版本为了保证文件里的字符显示正常，对流做了一层处理。

如果慢的话，最有可能这里会有影响。


比如 50M 的文件，前后时间对比是多少？
