### ISSUE TITLE
[Bug] 在控制台--->仪表盘--->用户/资产活跃情况的数据展示有问题

### ISSUE THREAD

**Issue by laodengto** [jumpserver/jumpserver#10957]
**JumpServer 版本( v3.4.1 )**

**浏览器版本**
Chrome 和 Edge 浏览器
**Bug 描述**
在控制台--->仪表盘--->用户/资产活跃情况的数据展示有问题

**Bug 重现步骤(有截图更好)**

![image](https://github.com/jumpserver/jumpserver/assets/49049414/0f9f67f6-46dd-42de-9015-f7b939a12cd6)

**Comment by BaiJiangJie** [comment]
看看 API 返回的数据是什么？本地来复现一下。

**Comment by yiqikeji17** [comment]
> **JumpServer版本( v3.4.1 )**
> 
> **浏览器版本** Chrome和Edge浏览器 **错误描述** 在控制台--->仪表盘--->用户/资产情况活跃的数据显示有问题
> 
> **Bug修复步骤(有截图更好)**
> 
> ![图像](https://user-images.githubusercontent.com/49049414/253143912-0f9f67f6-46dd-42de-9015-f7b939a12cd6.png)

我也遇到了，自从3.0开始就这样了

**Comment by yanxu4780** [comment]
同遇到

**Comment by BaiJiangJie** [comment]
现在确实有问题，同在这个 issue 中记录修复日期。
