### ISSUE TITLE
[Bug] Remote Webapp 代填密码后的一瞬间违规获取密码的风险

### ISSUE THREAD

**Issue by updogliu** [jumpserver/jumpserver#10954]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.0

**浏览器版本**
Google Chrome v114.0.5735.198 

**Bug 描述**
密码代填，遇到有“显示密码”按钮的，是可以在代填密码后的一瞬间点该按钮，看到密码的。
除此之外，可能还有用快捷键inspect网页dom来拿到代填的密码的风险。

是否能在代填完成前禁用键盘鼠标？

**Comment by rex5652** [comment]
+1

**Comment by BaiJiangJie** [comment]
`除此之外，可能还有用快捷键inspect网页dom来拿到代填的密码的风险。`

这个问题在新版的 Chrome 应用里已经解决了，禁用了 Chrome 的 inspect 操作。

`密码代填，遇到有“显示密码”按钮的，是可以在代填密码后的一瞬间点该按钮，看到密码的。`
这个问题不太好控制，代替是 Chrome 应用里的操作，控制鼠标键盘是 Lion 组件的操作，代填是否完成，Lion 其实是不知道的。

**Comment by updogliu** [comment]
有没有可能打开应用的时候默认是禁止键鼠的 (不启动Lion组件)，然后等代填脚本执行完毕后再启动Lion组件，启用键鼠？

还是说 “代填脚本执行完毕” 这个事件本身就无法获知？

**Comment by BaiJiangJie** [comment]
目前代填的过程中发现不能 Block 掉，v3.6 版本中再想一下有没有其他办法。

比如：先代填，完成后再显示 Chrome 页面。

**Comment by updogliu** [comment]
请问这个有进展吗？密码框带显示密码按钮还是挺常见的，比如 [Twilio](https://www.twilio.com/login).

是否可以先提供一个简单的方案，比如可以允许设置remote-app启动后若干秒内不许操作。我看v3.6.0里支持“在线会话支持管理员执行会话暂停”。这个就相当于remote-app启动后有一个自动暂定若干秒。

**Comment by ibuler** [comment]
解决了，填写密码时会 loading，你可以升级测试一下，看看是否满足你的要求

**Comment by updogliu** [comment]
> 解决了，填写密码时会 loading，你可以升级测试一下，看看是否满足你的要求

是 v3.6 中加入的feature吗？

**Comment by BaiJiangJie** [comment]
v3.6 已经解决了。

**Comment by updogliu** [comment]
已经升级到v3.6.6，但是依然可以在自动代填的时候 (虽然只有不到1秒的时间窗口) 点击眼睛按钮来显示密码。

比如 gitlab 的登录页面:  https://gitlab.com/users/sign_in

@ibuler @BaiJiangJie
