### ISSUE TITLE
[Bug] 远程应用里的Chrome无法再次打开新窗口

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#10956]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**浏览器版本**
Microsoft Edge 版本 114.0.1823.79

**Bug 描述**
全新安装的v3.4.3版本之后，打开远程应用的Chrome，此时web应用所设置的网站是可以正常打开的。但如果这个网站里点击某个连接会弹出新窗口，则新窗口无法显示在web终端里面，只是一闪而过。。。
v3.4.2 没有这个问题

**Bug 重现步骤(有截图更好)**
1. 打开一个WEB远程应用，启动Chrome
2. 随便点击这个远程里的某个连接，这个连接需要会打开新的Chrome窗口
3. 新窗口无法显示，可能会一闪而过

我从3.3一路升级到3.4.3后没有遇到这个问题，但昨天全新安装了3.4.3之后，出现了这个问题。

**Comment by BaiJiangJie** [comment]
Q: 但如果这个网站里点击某个连接会弹出新窗口，则新窗口无法显示在web终端里面，只是一闪而过。。。

A: 这是新 Chrome 远程应用的优化，阻止了打开新窗口。

**Comment by rex5652** [comment]
有办法调整吗？或者有没有办法将弹出的窗口显示在Chrome上。。
因为网站不是我们的，只是借用堡垒机去免密登陆。如果从网站正常的弹窗都不允许的话，那没法用了啊 😂

Bryan ***@***.***>于2023年7月13日 周四13:54写道：

**Comment by BaiJiangJie** [comment]
这里设计到一个问题，假如管理员配置的资产地址是（https://cn.aliyun.com/），用户登录上去之后应该限制只能在阿里云网站里进行操作，如果用户点击一个按钮跳转到了比如腾讯云里，我觉得这应该是不合适的。

**Comment by rex5652** [comment]
@BaiJiangJie 其实严格来说，不是打开新的网站，而是点击这个网站上的一个连接会打开本站的新窗口。

就有点像在Jumpserver的仪表盘上，我点右上角的Web终端按钮，会打开Web终端这样一个新窗口。
在我的业务中，其实是一个后台授权PDF文档用的页面，点击一个链接，弹出需要授权的人员，或者弹出需要授权的文档。
但现在这个情况下根本无法弹出新窗口来让我选择。

我确实可以理解您说的那种场景，可能会绕过可访问的页面。不知道有没有更好的办法？比如限制只能打开同域名的？或者做个设置让管理员决定是否可以弹出新窗口之类的。

**Comment by BaiJiangJie** [comment]
如果配置可以打开的域地址，管理员管理起来就比较复杂了。

还是要想怎么样能够禁用掉地址栏。（目前看着是没有办法）

**Comment by rex5652** [comment]
@BaiJiangJie 现在已经不显示地址栏了呀。只是不允许弹窗而已。还有在网页加载的过程中，标题栏里会显示完整的URL。。
![image](https://github.com/jumpserver/jumpserver/assets/1674158/81133ee3-e662-4b88-98c5-eac99e34a70c)

**Comment by BaiJiangJie** [comment]
如果弹窗放开，新的弹窗里还是会显示地址栏的。

**Comment by rex5652** [comment]
@BaiJiangJie 哦哦哦原来如此，那就看看能不能让新窗口的地址栏去掉吧

**Comment by BaiJiangJie** [comment]
调研的结果是 Chrome 地址栏控制不了，所以这个问题近期可能无解了。

**Comment by TinyWuP** [comment]
> 如果配置可以打开的域地址，管理员管理起来就比较复杂了。
> 
> 还是要想怎么样能够禁用掉地址栏。（目前看着是没有办法）

我们也碰到这个问题，很多业务站点需要新创建tab来交互，现在tab限制后，业务就无法处理。

**Comment by rex5652** [comment]
> 调研的结果是 Chrome 地址栏控制不了，所以这个问题近期可能无解了。

@BaiJiangJie 只能先装一个3.3的，部署好发布机，再升级到最新了。。

**Comment by BaiJiangJie** [comment]
这样其实也不行，因为只要新创建 tab 地址栏就会暴露出来，用户可以随便输入访问了。

new tab 和 new window 默认都会把 地址栏 显示出来。

**Comment by BaiJiangJie** [comment]
或者将来考虑支持两种模式的 Chrome 远程应用

1. 一种是原生 Chrome，地址栏、Inpsect 等等都不做限制。
2. 一种是安全模式的 Chrome，禁止 New Tab、New Window、Inspect，不显示地址栏。

管理员控制用什么方式打开。

这样感觉怎么样？

**Comment by rex5652** [comment]
> 或者将来考虑支持两种模式的 Chrome 远程应用
> 
> 1. 一种是原生 Chrome，地址栏、Inpsect 等等都不做限制。
> 2. 一种是安全模式的 Chrome，禁止 New Tab、New Window、Inspect，不显示地址栏。
> 
> 管理员控制用什么方式打开。
> 
> 还有一种方法，地址栏放出来不做控制了，在访问的时候进行判断拦截，允许管理员配置白名单。

@BaiJiangJie 我觉得这样可行，管理能控制用哪种也好点。如果以后有更多模式可以让管理员控制。
另外初始化部署的时候建议不要安装所有应用，可以点开初始化部署的时候，让管理员选择需要安装的应用

**Comment by rex5652** [comment]
@BaiJiangJie 两种 Chrome 远程应用也行，个人觉得设置白名单允许访问的URL个人觉得应该好一点。要交给社区投票？
或者设置白名单的也能做成一种应用吗？3个Chrome远程应用让管理员选择安装，给不同的远程应用使用。

**Comment by BaiJiangJie** [comment]
考虑了一下，两种应用、白名单方案，管理起来都会比较复杂。

简单一些，无论是 New Tab 还是 New Window，都限制只能打开同域的地址。

**Comment by rex5652** [comment]
> 考虑了一下，两种应用、白名单方案，管理起来都会比较复杂。
> 
> 简单一些，无论是 New Tab 还是 New Window，都限制只能打开同域的地址。

也可以，至少能用。希望尽快更新发布 😁

**Comment by BaiJiangJie** [comment]
嗯，v3.5 版本中会发布。
