### ISSUE TITLE
[Question] 录像存储OBS测试成功但并未上传到OBS，还需要什么配置么

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10958]
**请描述您的问题.**
录像存储OBS测试成功但并未上传到OBS，还需要什么配置么
![image](https://github.com/jumpserver/jumpserver/assets/106153788/142ad609-9825-47d3-bf5f-47ae27554cbf)
![image](https://github.com/jumpserver/jumpserver/assets/106153788/3f3dbab4-4f2b-4d76-98e0-094553ba0617)
![image](https://github.com/jumpserver/jumpserver/assets/106153788/2a5b413b-15af-4166-a7a2-dbf9ec0760a5)

**Comment by rex5652** [comment]
要去终端管理上更新一下配置

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/guide/system/terminal/#3

看文档。@wangheng0206
