### ISSUE TITLE
[Question] 部署远程应用发布机时卡死

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#10953]
部署远程应用发布机，每次到Download Chrome zip package (Chrome)的时候跑一段就卡死了，然后只能重新删掉发布机，再次添加，重新部署。或者等非常久，让堡垒机检测到部署失败再重新部署。。。
有没有办法从这一步重试呢？
谢谢

**Comment by rex5652** [comment]
其实应该说，部署过程中任一步骤都有可能卡死。。然后只能重头再来。。

**Comment by BaiJiangJie** [comment]
将来可以考虑分开为两个步骤，一个是只初始化发布机，一个是安装内置的远程应用（Chrome 和 DBeaver）。

**Comment by wojiushixiaobai** [comment]
发布机 SSH 改成 WinRM，WinRM 不会卡死
![91fc3da1a580604380f7be454052a8b](https://github.com/jumpserver/jumpserver/assets/24326988/bb7fce36-3529-4769-b665-19af8b366740)

**Comment by wojiushixiaobai** [comment]
@rex5652 问题是你的步骤都没有到发布的应用那个地方，你的问题跟这个无关

**Comment by QYG2297248353** [comment]
@wojiushixiaobai 
![image](https://github.com/jumpserver/jumpserver/assets/56836951/76a1a376-6c39-421a-898d-7079459873c1)
部署一上午了就是卡在这一步

**Comment by wojiushixiaobai** [comment]
@QYG2297248353 说明通过什么方式部署的，这里卡住表示下载 chrome 安装包很慢卡住了

**Comment by wojiushixiaobai** [comment]
@QYG2297248353 资源默认重定向到了 https://gitea.com/jumpserver/web-static/src/tag/v1.1.3 此仓库，可以找网络好的环境手动下载到容器里面
```sh
docker exec -it 1panel_jumpserver bash   # 或者通过 1panel 的控制台直接进入容器
```
```sh
cd /opt/download/

# 比如下载 chrome
mkdir applets
cd applets
wget https://gitea.com/jumpserver/web-static/src/tag/v1.1.3/download/applets/chrome-win.zip

# 其他的应用一样，注意路径
```

**Comment by QYG2297248353** [comment]
发布后又有新问题
![image](https://github.com/jumpserver/jumpserver/assets/56836951/a247b036-d61f-4980-8064-59d2089c0032)

部署应用卡住了，也没办法取消，再次执行部署
![image](https://github.com/jumpserver/jumpserver/assets/56836951/05ddd765-ff51-45cc-a948-992186367302)

提示是成功了，页面还是失败

![image](https://github.com/jumpserver/jumpserver/assets/56836951/02646e3b-a155-4b0c-9234-0fdd8e71d28a)

@wojiushixiaobai

**Comment by QYG2297248353** [comment]
升级了应用 
现在用的最新版
![image](https://github.com/jumpserver/jumpserver/assets/56836951/a5a5af13-10e9-4aaf-ba9b-2d4e892dcb67)
部署是在升级前部署的，我看卡了好久
