### ISSUE TITLE
[Feature] 关于web终端增加批量登录功能的需求建议

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#10955]
需求描述，经常有批量登录一些设备同时操作的需求，（作业中心那种有时不太爱用，输出内容过多时需要翻页查看回显，没有xshell那种瓷砖排序后回显的直观），是否可以考虑在web终端中设备前面增加复选框，勾选后可以一次性批量登录，或者在个人收藏夹中支持创建自定义文件夹并实现文件夹内的设备批量登录。
<img width="292" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/402db22d-faff-48b3-a50e-9ba06b3ce92c">
<img width="1897" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/043764c9-2871-4359-a9f9-39f81b1b6f7d">

**Comment by BaiJiangJie** [comment]
以前设想过再 Web 终端页面支持批量连接资产的功能，但是现在连接资产无论有几个账号都会弹出账号选择框，也只有这个弹窗关闭后才能连接其他资产，左侧资产树的复选框倒是好加，但是批量连接的时候还是免不了要一个一个选账号，也比较繁琐（还得是顺序选择）

所以现在的想法是，在工作台，我的资产列表页面增加【一键连接】的按钮，会同时打开多个浏览器 Tab，如果浏览器不是全屏，会打开多个小窗口（就像现在 Web 终端页面右击打开新窗口的效果）

<img width="2559" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/c0e022ad-f13d-4a32-b723-8def4c6816ed">

<img width="1989" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/89801076-98ed-46f3-8aa3-8e6d2fe29c6c">

**Comment by pika-FENG** [comment]
> 以前设想过在 Web 终端页面支持批量连接资产的功能，但是现在连接资产无论有几个账号都会弹出账号选择框，也只有这个弹窗关闭后才能连接其他资产，左侧资产树的复选框倒是好加，但是批量连接的时候还是免不了要一个一个选账号，也比较繁琐（还得是顺序选择）
> 
> 所以现在的想法是，在工作台，我的资产列表页面增加【一键连接】的按钮，会同时打开多个浏览器 Tab，如果浏览器不是全屏，会打开多个小窗口（就像现在 Web 终端页面 资产树右击打开新窗口的效果）
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/32935519/253182329-c0e022ad-f13d-4a32-b723-8def4c6816ed.png">

如果能保存上一次选中的批量设备列表以及对应的登录账号就完美解决了，无非是第一次麻烦一点，后期其实大多数情况下都是用这个记录去登录了。

**Comment by BaiJiangJie** [comment]
嗯，这个勾选上就不会弹窗了。

<img width="847" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/8ba6560d-a69a-4195-8a46-a471588e8981">

**Comment by BaiJiangJie** [comment]
下个版本可能会考虑先在【我的资产】列表页面增加一个批量连接的功能。

Web 终端页面操作，处理起来相对比较繁琐。

**Comment by pika-FENG** [comment]
赞

**Comment by BaiJiangJie** [comment]
先不 Close，有计划的功能一般等开发完准备上线时再关闭。

**Comment by BaiJiangJie** [comment]
计划 v3.6 版本支持。

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持批量连接资产。
