### ISSUE TITLE
[Bug] 快捷命令操作网络设备提示运行失败

### ISSUE THREAD

**Issue by archonzc** [jumpserver/jumpserver#10962]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
jumserver 3.4.3 社区版

**浏览器版本**
edge 11.4.0.1823.79

**Bug 描述**
快捷命令模块中，尝试发送命令给ssh方式连接的网络设备，提示失败。

**Bug 重现步骤(有截图更好)**
1.勾选网络设备，选择运行账号，输入命令，点击运行
2.提示运行失败 UNREACHABLE

**Comment by BaiJiangJie** [comment]
数据库、网络设备类型的资产，目前还不支持批量命令，将来会支持。（计划 v3.6、v3.7+ 版本）

**Comment by BaiJiangJie** [comment]
作业中心，对于数据库的批量命令已支持（v3.6）

网络设备计划（v3.7）

**Comment by BaiJiangJie** [comment]
最新版本均已支持。
