### ISSUE TITLE
docker启动，测试连接性，一直报sshpass没有安装

### ISSUE THREAD

**Issue by GounGG** [jumpserver/jumpserver#1096]
![image](https://user-images.githubusercontent.com/17611638/37644851-ffcf0970-2c5f-11e8-93a3-36fa6e1e243a.png)
我使用的是ssh password登陆方式？请问这个该怎么解决

**Comment by atonganan** [comment]
我也是这样的额，到底怎么回事

**Comment by ibuler** [comment]
解决了，是supervisord.conf中的PATH配置的有问题，
https://github.com/jumpserver/Dockerfile/blob/mysql/alpine/supervisord.conf#L11  需要带上原来的PATH

直接更新即可，很少变动，速度比较快

**Comment by ibuler** [comment]
没问题后请关闭issue

**Comment by GounGG** [comment]
好的，问题已解决！

**Comment by GounGG** [comment]
close
