### ISSUE TITLE
[Bug] V3.4.2 多条命令执行时，命令耗时较长时会被截断执行，风险极大希望尽快修复

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10976]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

V3.4.2
**浏览器版本**

**Bug 描述**
多条命令执行时，每条命令耗时较长时会被截断
会导致重大生产风险，例如删除OBS数据时，命令被截取，删除了上级目录文件。

**Bug 重现步骤(有截图更好)**
1.贴入多行命令，模拟每行执行两秒重，会出现命令被截取执行的情况
![image](https://github.com/jumpserver/jumpserver/assets/106153788/618e3ddc-bae9-45a7-af3f-f4bba3acf962)
2.命令被截断并被执行
![image](https://github.com/jumpserver/jumpserver/assets/106153788/158c5c8f-9652-4d88-ba2a-2c3a92f08c29)

**Comment by LeeEirc** [comment]
可以贴一下你的多条命令吗？可能是字符长度的限制，如果少两条命令，可以正常执行吗？

**Comment by wangheng0206** [comment]
> 可以贴一下你的多条命令吗？可能是字符长度的限制，如果少两条命令，可以正常执行吗？

少于两条不会，就是多条会出这种问题

**Comment by wangheng0206** [comment]
> 可以贴一下你的多条命令吗？可能是字符长度的限制，如果少两条命令，可以正常执行吗？

有命令长度限制吗

**Comment by LeeEirc** [comment]
尝试复制了一个超级长的命令，本地未能复现你所说的截断问题。

**Comment by wangheng0206** [comment]
> 尝试复制了一个超级长的命令，本地未能复现你所说的截断问题。
你可以先创建这个文件夹然后执行以下命令
mkdir /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521


ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2
ls -l  /var/log/messages.messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521messages-20230521 && sleep 2

**Comment by wangheng0206** [comment]
> 尝试复制了一个超级长的命令，本地未能复现你所说的截断问题。
被截取了，找不到创建的文件夹了
![image](https://github.com/jumpserver/jumpserver/assets/106153788/f61e1255-90dd-4d57-a36b-87bfa2748663)

**Comment by LeeEirc** [comment]
按照你的方式，模拟了下复制多行的情况，貌似也没有截断。

![image](https://github.com/jumpserver/jumpserver/assets/32626707/982941ed-96c7-4c2d-8964-6c87bd241140)
