### ISSUE TITLE
docker启动，测试连接性，一直报sshpass没有安装 

### ISSUE THREAD

**Issue by atonganan** [jumpserver/jumpserver#1097]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.0.0-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
![image](https://user-images.githubusercontent.com/13044518/37646761-80a3f718-2c65-11e8-8761-2eb68e0de3ff.png)

![image](https://user-images.githubusercontent.com/13044518/37646798-96725102-2c65-11e8-8f94-47bc18179c48.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
same with #1096
