### ISSUE TITLE
[Bug] 访问群晖异常

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#10977]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**浏览器版本**
Microsoft Edge
版本 114.0.1823.82 (正式版本) (64 位)

**Bug 描述**
通过jumpserver进行访问群晖，自动填充密码是提示用户名密码错误，手敲却正确。群晖版本是DSM 7.1-42661 Update 1，输入用户名和密码的页面是分布在两个页面的。

自动填充密码是提示用户名密码错误，手敲却正确。

想要获取支持，如何查看填充的密码是否正确。此外是使用脚本进行登录的。

[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "name=username",
    "command": "type"
  },
  {
    "step": 2,
    "value": "",
    "target": "XPath=/html/body/div[3]/div/span/div/div[2]/div[2]/div/div[3]/div[2]/div/div[2]/div[3]/div[1]",
    "command": "click"
  },
  {
    "step": 3,
    "value": "{PASSWORD}",
    "target": "XPath=/html/body/div[3]/div/span/div/div[2]/div[2]/div/div[3]/div[2]/div/div[2]/div[1]/div[2]/form/div[1]/div/div[1]/input",
    "command": "type"
  },
  {
    "step": 4,
    "value": "",
    "target": "XPath=/html/body/div[3]/div/span/div/div[2]/div[2]/div/div[3]/div[2]/div/div[2]/div[1]/div[4]/div[1]",
    "command": "click"
  }
]

**Bug 重现步骤(有截图更好)**
1.配置群晖作为资产
2.配置登录脚本
3.堡垒机访问时提示用户名或者密码错误，手敲密码就正确

想要知道如何能查询到堡垒机填充的密码是多少

**Comment by LeeEirc** [comment]
密码是使用的替换词是 `{SECRET}` ，而不是 `{PASSWORD}`

**Comment by qianyu-0712** [comment]
奥奥，不好意思啊，我弄错了

**Comment by shine85** [comment]
> 奥奥，不好意思啊，我弄错了

您好，我也遇到这个不自动填入密码，不能登录，请问可以把脚本分享下吗？谢谢
