### ISSUE TITLE
[Bug] V3.4.2账号列表查询选定节点后再查询出现多条记录

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#10975]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.4.2

**浏览器版本**

**Bug 描述**
V3.4.2账号列表查询选定节点后再查询出现多条记录

**Bug 重现步骤(有截图更好)**
1.直接查询仅一条记录
![image](https://github.com/jumpserver/jumpserver/assets/106153788/1ebdb459-9f6a-4382-9c83-b433614bcb1f)

2.选定节点后出现多条记录
![image](https://github.com/jumpserver/jumpserver/assets/106153788/e3389974-3223-4bef-bc56-56a43fe9f91c)
3.数据库仅一条记录
![image](https://github.com/jumpserver/jumpserver/assets/106153788/4a796d92-4702-4884-b4dc-f4b34c347bc3)

**Comment by BaiJiangJie** [comment]
应该是只有一条记录，本地 v3.4.3 版本没有复现，升级一下试试呢？

**Comment by BaiJiangJie** [comment]
最新版本已修复。
