### ISSUE TITLE
[Question] 两地三中心架构升级版本mysql数据如何同步？

### ISSUE THREAD

**Issue by catdiscus** [jumpserver/jumpserver#10984]
**请描述您的问题.**
jumpserver集群目前有三台机器abc
A区域：a，b
B区域：c，作为冷备，数据库、redis等一切中间件都是独立的一套，平时通过阿里云的数据同步服务来同步mysql数据
现在遇到一个问题
版本升级时，先在ab上执行upgrade，然后在c上执行upgrade，升级几次后两个区域的数据库出现表结构不一致的问题
请问在两地三中心的模式下，数据库推荐的同步方式是怎样的？

**Comment by wojiushixiaobai** [comment]
升级前关闭所有 JumpServer 节点，手动备份数据库相关信息。
指定任意一个节点执行升级操作，升级操作后执行同步数据库。
其他 JumpServer 正常升级即可。

注意事项：
1. 升级过程不允许有 JumpServer 节点在运行
2. 不允许多个 JumpServer 节点同时升级
