### ISSUE TITLE
[Bug] v3.4.3 版本名称为中文，ansible命令报错，中文乱码，快捷命令报错

### ISSUE THREAD

**Issue by qw4285632q** [jumpserver/jumpserver#10986]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
Microsoft Edge  114.0.1823.82

**Bug 描述**
ansible命令报错，中文乱码，快捷命令报错 

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/27714601/e3201425-1669-42bd-a21b-e73fff88cff7)
![image](https://github.com/jumpserver/jumpserver/assets/27714601/10296894-4875-470b-81f1-88af001e83fd)

**Comment by qw4285632q** [comment]
补充说明：资产列表命名：
![image](https://github.com/jumpserver/jumpserver/assets/27714601/427014b8-6ba2-4672-9ae3-b1f0f8daba55)
快捷命令截图：
![image](https://github.com/jumpserver/jumpserver/assets/27714601/3edd57f5-bcf5-4908-b652-faa13c5ecb2c)
我将中文全部删除后执行成功了

**Comment by BaiJiangJie** [comment]
删除资产名称里的中文吗？

**Comment by qw4285632q** [comment]
对 删除资产名称中的中文，快捷命令执行正常

**Comment by BaiJiangJie** [comment]
在 v3.5 和 v3.4.3 版本中会修复。
