### ISSUE TITLE
我在jumpserver上拖拽一个zip文件的时候，结果上传的是一个打不开的图片，麻烦看看是不是已知问题

### ISSUE THREAD

**Issue by Eric-yhg** [jumpserver/jumpserver#10987]
[[我在jumpserver上拖拽一个zip文件的时候，结果上传的是一个打不开的图片，麻烦看看是不是已知问题]([url](<img](url) width="518" alt="企业微信截图_35aa701d-e135-4884-8b89-09d8692471be" src="https://github.com/jumpserver/jumpserver/assets/20981836/b812c31b-c7b2-4ef8-950c-505b0b9205f8">))

**Comment by BaiJiangJie** [comment]
在哪个页面上传的？详细描述一下。

**Comment by Eric-yhg** [comment]
服务器的文件上传 /tmp发自我的荣耀手机-------- 原始邮件 --------发件人： Bryan ***@***.***>日期： 2023年7月18日周二 17:25收件人： jumpserver/jumpserver ***@***.***>抄送： Eric-yhg ***@***.***>, Author ***@***.***>主    题： Re: [jumpserver/jumpserver] 我在jumpserver上拖拽一个zip文件的时候，结果上传的是一个打不开的图片，麻烦看看是不是已知问题 (Issue #10987)
在哪个页面上传的？详细描述一下。

**Comment by BaiJiangJie** [comment]
不是图片，上传上来就是一个 zip 文件，没问题。

<img width="1815" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/63e293a1-cd2f-44ad-80be-dbc07b4540cc">
