### ISSUE TITLE
[Feature] Web终端文件管理上传文件提示功能

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#10983]
目前通过web终端对linux主机进行文件管理，上传文件时，不会提醒文件已存在，会直接覆盖。是否考虑增加”覆盖“、”跳过“、”重命名“等安全提示，如XFTP这种
<img width="440" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/af847fb1-eae8-4795-838e-4e980e995fd6">

**Comment by BaiJiangJie** [comment]
v3.6 版本考虑优化一下。

**Comment by BaiJiangJie** [comment]
v3.6 已上线。
