### ISSUE TITLE
[Feature] 建议版本升级后API向下兼容

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#10993]
**请描述您的需求或者改进建议.**
我这边是企业用户，基于JumpServer堡垒机API做了大量的自动化功能开发。发现下面这些问题：
1。 JS不同的版本，API变动很大，无法向下兼容；
2。新版本说明里面，没有列出api的变动，我需要花费大量时间去测试发现和验证；
这些痛点导致现在不敢升级了，因为谁也不知道升级完后，哪块业务会出现预料之外的故障！

**Comment by maninhill** [comment]
你可否参与到社区中，帮助做测试和验证，一起来改进兼容性？

**Comment by ibuler** [comment]
目前没有这方面精力整理，欢迎参与进来，整理一遍，写到 readme 中

**Comment by khy2021** [comment]
> 你可否参与到社区中，帮助做测试和验证，一起来改进兼容性？
如果不是太麻烦的话，那可以啊。不过这个事后整理是一方面，更关键的是产品那边后续设计的时候，可能就需要考虑api变动对用户的影响。

**Comment by khy2021** [comment]
> 目前没有这方面精力整理，欢迎参与进来，整理一遍，写到 readme 中

可以试试哈[嘿哈]

**Comment by ibuler** [comment]
> > 你可否参与到社区中，帮助做测试和验证，一起来改进兼容性？
> > 如果不是太麻烦的话，那可以啊。不过这个事后整理是一方面，更关键的是产品那边后续设计的时候，可能就需要考虑api变动对用户的影响。

维护成本不大会考虑的，如果兼容成本比较大，就不会兼容了。
