### ISSUE TITLE
[Bug] 思科设备账号切换功能连接超时（enable密码）

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#10992]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**浏览器版本**
Chrome 114.0.5735.199
Xshell 7

**Bug 描述**
v3.2.0新增功能：账号切换支持网络设备(交换机)，如：Cisco、华为交换机、H3C
当前使用该功能异常。同一个资产，不同账号（1、ssh账号；2、enable密码；），一个正常，一个超时。

**Bug 重现步骤(有截图更好)**
1. 配置：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/33e6b820-6979-44c7-9be7-25b51283fad3)
![image](https://github.com/jumpserver/jumpserver/assets/58923704/1754df65-cf65-48ab-910c-cee01b580efa)
![image](https://github.com/jumpserver/jumpserver/assets/58923704/073f0ce0-ae68-46c5-8d88-b49f88af00fb)
![image](https://github.com/jumpserver/jumpserver/assets/58923704/eab98ea1-a087-4579-8cd7-d4aad041ea94)

2. 连接测试：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/6167d5d2-545c-4130-84e5-93c7eda2af70)

3. koko日志
![image](https://github.com/jumpserver/jumpserver/assets/58923704/c056a377-bc74-4e22-a146-eabec0dded5d)

**Comment by qianyu-0712** [comment]
哥们，你的网络设备是怎么做到语法高亮的

**Comment by luweijun1992** [comment]
> 哥们，你的网络设备是怎么做到语法高亮的

Xshell 软件有高亮功能，根据需要设置即可。

**Comment by qianyu-0712** [comment]
哦哦，我以为是堡垒机里的页面来着

**Comment by BaiJiangJie** [comment]
用 2 登录没问题， 用 1 登录 你的网络设备支持吗？

**Comment by BaiJiangJie** [comment]
开 DEBUG 日志看看连接的过程中是否使用了切换用户？

**Comment by luweijun1992** [comment]
> master 直连没问题吗？

是的，连接测试截图第二次连接就是使用master账号，成功连上了。

**Comment by luweijun1992** [comment]
> 开 DEBUG 日志看看连接的过程中是否使用了切换用户？

DEBUG信息如下：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/32e5285b-83e6-4999-a227-56966684784c)

**Comment by LeeEirc** [comment]
思科配置存在问题？enable 的密码错误？或当前用户没有权限执行 enable？手动 ssh 到资产 执行 enable 可以切换登录吗？

**Comment by luweijun1992** [comment]
> 思科配置存在问题？enable 的密码错误？或当前用户没有权限执行 enable？手动 ssh 到资产 执行 enable 可以切换登录吗？

手动登录是没有问题的。且从debug信息看到enable密码是没错的。

**Comment by LeeEirc** [comment]
进 Koko 容器执行 ssh 命令连接思科设备，手动测试下，看到报错 `Access denied`，手动检查下是不是有其他限制。
```
docker exec -it jms_koko bash
ssh master@172.16.144.125

```

**Comment by luweijun1992** [comment]
> 

进入Koko容器直接ssh失败了：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/6beb0bda-f7e0-4e72-aa77-0e51a11848ab)
但是这边又能正常连接上：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/140c8120-0ed4-4c7c-9819-677a283ff89e)

**Comment by LeeEirc** [comment]
通过 Koko 的方式连接也行，通过 master 登陆的资产，手动 enable ，可以成功吗？

**Comment by luweijun1992** [comment]
> 通过 Koko 的方式连接也行，通过 master 登陆的资产，手动 enable ，可以成功吗？

可以的，没问题。
![image](https://github.com/jumpserver/jumpserver/assets/58923704/4b1036a2-e996-450e-b687-6ee0b1aa9b19)
enable密码就是用的Koko DEBUG中如下截图密码：
![image](https://github.com/jumpserver/jumpserver/assets/58923704/22d2e0e0-11bd-4c26-848e-31125b577ae0)

**Comment by LeeEirc** [comment]
加入交流群，贴下github issue，远程帮你看下，看下是不是执行代填的部分存在问题。

**Comment by BaiJiangJie** [comment]
已远程解决，v3.5 发布。
