### ISSUE TITLE
资产列表做三级分组后，在web终端不做分组

### ISSUE THREAD

**Issue by zhaofei91** [jumpserver/jumpserver#1099]
[简述你的问题]

##### 使用版本
[1.0.0-2]

##### 问题复现步骤
1. 资产列表做三级分组后，在web终端不做分组。

##### 具体表现[截图可能会更好些,最好能截全]
![qq 20180321111141](https://user-images.githubusercontent.com/13270279/37693154-c8b3c4be-2cf8-11e8-906e-65d580e121e5.png)
![default](https://user-images.githubusercontent.com/13270279/37693149-bd249754-2cf8-11e8-9f97-f21d6e6aff4d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
前端能力有限，左侧树好做，但是树和终端中间的分隔可以手动拖动，这个实现起来略有难度，不过已经在做了

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
