### ISSUE TITLE
[v3.0 beta] webterminal vim后命令double

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#110]
bug现象：vim一下不管成功与否，每敲一个字符，客户端显示2个
![image](https://cloud.githubusercontent.com/assets/17382885/13452662/fb34a4c0-e084-11e5-8b46-c182cf7b56b9.png)
![image](https://cloud.githubusercontent.com/assets/17382885/13452665/01343a0c-e085-11e5-9703-8e9bcde24d5d.png)

**Comment by liuzheng712** [comment]
fixed closed
