### ISSUE TITLE
[Bug] 会话实际已经退出，但在会话记录中依然显示且无法中断。

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#11006]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**Bug 描述**
会话在卡住之后，无法中断，实际上是这些会话早就中断了
![image](https://github.com/jumpserver/jumpserver/assets/1674158/6c399a4c-7b32-498b-b6b3-bea6978b4479)

这是点监控后的情况
![image](https://github.com/jumpserver/jumpserver/assets/1674158/59b75568-4b7d-4774-a3fa-4955252ce81b)

**Bug 重现步骤(有截图更好)**
不确定怎么触发。。

**Comment by luweijun1992** [comment]
一样会遇到，但是好像过段时间就消失了。
且当前去中断的话并不会马上中断，只是提示任务下发了。

**Comment by rex5652** [comment]
最终我通过重启了服务器后好像才消失的

**Comment by BaiJiangJie** [comment]
是的，会有定时任务清除一些不能正常断开的会话。

**Comment by LeeEirc** [comment]
https://github.com/jumpserver/jumpserver/issues/11176
