### ISSUE TITLE
[Question] ansible批量命令權限設置

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#11007]
版本：jumpserver 3.3.0
如何實現只對某個用戶或者用戶組設置ansible 批量命令權限？

**Comment by BaiJiangJie** [comment]
需要去掉角色里的权限位。

<img width="990" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/ca316e68-564b-4d8b-9c51-54c5a8333516">
