### ISSUE TITLE
[Question] 远程发布机问题

### ISSUE THREAD

**Issue by vyunwei** [jumpserver/jumpserver#11013]
**请描述您的问题.**
版本 3.4.3

问题1：创建远程发布机时，账号模版没有删除入口，在控制台---账号管理-账号模版 找不到远程发布主机的账号模版，怎么删除呢？
问题2：远程发布机的初始化部署任务一直卡着不动，请问什么原因呢？
![微信截图_20230719123815](https://github.com/jumpserver/jumpserver/assets/18206104/151fdd73-07a5-438e-ac67-d3c36dff3751)
![微信截图_20230719124231](https://github.com/jumpserver/jumpserver/assets/18206104/0455fee8-3a7c-465f-bedc-913eea7a712d)
![微信图片_20230719123839](https://github.com/jumpserver/jumpserver/assets/18206104/2d563fa4-8911-4bfb-be75-9d3d1c783636)

**Comment by BaiJiangJie** [comment]
问题1：创建远程发布机时，账号模版没有删除入口，在控制台---账号管理-账号模版 找不到远程发布主机的账号模版，怎么删除呢？

应用发布机页面不能删除账号模版，这两个账号模版是系统组织下的资源，也就是系统默认的只能查看。

**Comment by BaiJiangJie** [comment]
问题2：远程发布机的初始化部署任务一直卡着不动，请问什么原因呢？

看看 core 执行部署的 celery ansible 日志。

**Comment by vyunwei** [comment]
> 问题1：创建远程发布机时，账号模版没有删除入口，在控制台---账号管理-账号模版 找不到远程发布主机的账号模版，怎么删除呢？
> 
> 应用发布机页面不能删除账号模版，这两个模版是怎么创建的？

添加发布主机的时候 “添加模版--添加” 这样添加上的模版，但是并没有在 “控制台---账号管理-账号模版 ” 里面找到已经添加上的发布主机的账号模版

**Comment by vyunwei** [comment]
> > 问题1：创建远程发布机时，账号模版没有删除入口，在控制台---账号管理-账号模版 找不到远程发布主机的账号模版，怎么删除呢？
> > 应用发布机页面不能删除账号模版，这两个模版是怎么创建的？
> 
> 添加发布主机的时候 “添加模版--添加” 这样添加上的模版，但是并没有在 “控制台---账号管理-账号模版 ” 里面找到已经添加上的发布主机的账号模版

![image](https://github.com/jumpserver/jumpserver/assets/18206104/e3a3ec0b-a2ea-44b5-9cb3-c4a8fd6e5f3d)
点进去其中任意一个模版就会提示“账号模版: undefined” “没有找到对应资源或者已经被删除”
![image](https://github.com/jumpserver/jumpserver/assets/18206104/cc783543-8858-467f-8741-24962dd423f0)
点击右上角删除就会报错“AccountTemplate对象不存在”
![image](https://github.com/jumpserver/jumpserver/assets/18206104/56bb55e2-f0c8-49c7-b85a-063117bcb8e5)
