### ISSUE TITLE
[Bug] jumpserver3.4.3管理k8s集群无法加载资源树

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11039]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
edge 版本 114.0.1823.82 (正式版本) (64 位)

**Bug 描述**
目前多轮测试下，我新版本使用clusterrole cluster-admin才能看到资源树层级 使用我自定义的role命名空间的都无法看到层级显示  也无法连接集群 提示无效token ，但是新旧版的区别是旧版虽然看不到层级但是可以右击链接集群命令行操作 但是新版连接k8s集群也连接不上 无效token
我这边测试发现只有使用clusterrole的token才能正常加载集群信息 pod信息 使用自定义的role都无法加载信息 但是我手动kubectl 加上我的token是可以获取的 

**Bug 重现步骤(有截图更好)**
1.在指定命名空间如p-oms创建sa
[saas@p-10 ~]$ kubectl get  sa oms -n p-oms -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-07-19T15:19:12Z"
  name: oms
  namespace: p-oms
  resourceVersion: "34167052"
  uid: 07f9bc2b-c92a-4d9f-a1a8-07a3f9f5deb7
secrets:
- name: oms-token-77f26
2.创建role 
[saas@p-10 ~]$ kubectl get  role jumpserver-role -n p-oms -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"jumpserver-role","namespace":"p-oms"},"rules":[{"apiGroups":[""],"resources":["pods","pods/exec","pods/log"],"verbs":["get","watch","list","exec","create"]}]}
  creationTimestamp: "2023-07-19T15:20:50Z"
  name: jumpserver-role
  namespace: p-oms
  resourceVersion: "34777383"
  uid: c9fd479b-0e66-42e0-9a8b-e8ddfd1cf17c
rules:
- apiGroups:
  - '*'
  - apps
  resources:
  - pods
  - nodes
  - namespaces
  - namespaces/status
  - pods/exec
  - pods/log
  verbs:
  - get
  - watch
  - list
  - exec
  - create

3.rolebinding 绑定sa和role
kubectl create rolebinding jumpserver-rb --role=jumpserver-role --serviceaccount=p-oms:default --namespace=p-oms
4.然后获取sa的token 复制到jumpserver k8s集群的账号的令牌中

**Comment by wangmingwang123** [comment]
@wojiushixiaobai @BaiJiangJie 麻烦帮忙看下这个bug呢 下一期能修复嘛

**Comment by BaiJiangJie** [comment]
自定义的 Role，有 NameSpace、Pod、Container 这些权限吗？

旧版本没有校验这三个权限，直接连接的，新版本增加了权限校验，所以连不上了。

**Comment by wangmingwang123** [comment]
我自定义角色写了这些权限你看看少那些嘛 还是不行

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/768df030-898b-45b4-a2fd-7d3364fef5e1)

**Comment by BaiJiangJie** [comment]
使用这个 Token 通过 kubctl 命令查看一下 namespace、pods 等等的资源看看有权限吗？

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/848166b2-a604-4e8d-a0b7-4d8589315313)
权限有的 都可以看到所有pod

**Comment by BaiJiangJie** [comment]
还有 namespaces 呢？这个比较重要

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/caf80574-dc6c-4c32-9408-e38fe67edfb3)
这个也是可以看到所有命名空间的

**Comment by BaiJiangJie** [comment]
新版本集群不能连接的问题会在 v3.6 版本中解决。

Luna 页面左侧树没有显示的问题，应该还是 role 权限不对。

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/5a968a1e-a124-4e57-818e-509f2d133577)
看日志确实是Forbidden但是我该给的权限都给了呀 
![image](https://github.com/jumpserver/jumpserver/assets/73093158/ef4b5698-892e-4a53-b932-a1d08fb9c08a)
![image](https://github.com/jumpserver/jumpserver/assets/73093158/650d4b56-9a3f-4381-8ebd-e0da29785c20)

**Comment by wangmingwang123** [comment]
https://github.com/jumpserver/jumpserver/issues/8701
我看到一个issue跟我这个一样的 授权无法精确到namespace像我这样role绑定ns不生效 只有clusterrole生效

**Comment by BaiJiangJie** [comment]
好的，https://github.com/jumpserver/jumpserver/issues/8701 当时 GitHub Actions 自动关闭了。

应该是 sdk 调用 API 权限时的要求。

下个版本调研一下。

**Comment by BaiJiangJie** [comment]
v3.6 已解决。

**Comment by wangmingwang123** [comment]
> 好的，#8701 当时 GitHub Actions 自动关闭了。
> 
> 应该是 sdk 调用 API 权限时的要求。
> 
> 下个版本调研一下。（v3.7）

这个问题3.6已经解决了嘛

**Comment by wangmingwang123** [comment]
> v3.6 已解决。
 3.6.2版本
![image](https://github.com/jumpserver/jumpserver/assets/73093158/cc55b556-dee5-4cf8-9181-e58bd3abcee1)
![image](https://github.com/jumpserver/jumpserver/assets/73093158/661bf2ab-818b-43cf-93fd-7aa19be8d565)
我针对单个命名空间p-oms创建的role 可是还是可以看到其他命名空间的pod
