### ISSUE TITLE
[Bug] upgrade to v3.5.0 error

### ISSUE THREAD

**Issue by yangbo254** [jumpserver/jumpserver#11038]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**

**Bug 描述**
从3.4.3升级至3.5.0时，升级过程有报错，相关两个docker image无法pull
[jumpserver/chen:v3.5.0]
Error response from daemon: Head "https://swr.cn-north-1.myhuaweicloud.com/v2/jumpserver/chen/manifests/v3.5.0": denied: You may not login yet
Error response from daemon: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/chen:v3.5.0
Error response from daemon: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/chen:v3.5.0

[jumpserver/kael:v3.5.0]
Error response from daemon: Head "https://swr.cn-north-1.myhuaweicloud.com/v2/jumpserver/kael/manifests/v3.5.0": denied: You may not login yet
Error response from daemon: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/kael:v3.5.0
Error response from daemon: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/kael:v3.5.0

**Bug 重现步骤(有截图更好)**
1.curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
2.
3.

**Comment by yangbo254** [comment]
> 等明天，华为云的缓存还没刷新

好像这个denied: You may not login yet错误，是镜像忘记公开导致的。。。
https://support.huaweicloud.com/codeci_faq/codeci_faq_0024.html

话说其实海外部分，直接用ghcr.io是不是更方便？华为云的pull速度，在海外aws或gcp上拉，速度还是慢。

**Comment by wojiushixiaobai** [comment]
镜像同步需要时间，国外默认使用 docker.io，只有国内才会用 huaweicloud.com 加速。
国内已经无法直连 docker.io

**Comment by yangbo254** [comment]
已解决，已能够正常pull到资源。
