### ISSUE TITLE
web终端接受注册后，会自动发送一封邮件到xxx@local.domain

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#1103]
[简述你的问题]

问题出现在0.5和1.0.0版本

##### 问题复现步骤
1. 先配置好jumpserver邮箱相关设置
2. 在会话管理 - 终端管理 里注册应用（目前就coco和guacamole，），登录邮箱看发件记录就可以看到发件记录了

##### 具体表现
![1112](https://user-images.githubusercontent.com/24326988/37744881-9627aa6a-2dac-11e8-9557-0d48f64ecb2d.png)
![11133](https://user-images.githubusercontent.com/24326988/37744883-996f3dd2-2dac-11e8-8363-e3071b9f2307.png)

##### 其他
建议直接屏蔽掉，或者local.domain改成管理员设置的邮箱都行

**Comment by ibuler** [comment]
fixed
