### ISSUE TITLE
使用web界面访问的网络设备如何添加

### ISSUE THREAD

**Issue by cellomi** [jumpserver/jumpserver#11044]
你好，我安装了这个堡垒机，因为我有防火墙和路由器，除了使用SSH登陆外，还需要使用web界面，但是文档里没有使用web登陆的教程，麻烦提供一下方法，谢谢！
![image](https://github.com/jumpserver/jumpserver/assets/140156954/70a911e1-3061-44bf-9ab9-406ec3dd6ff3)

**Comment by rex5652** [comment]
添加一个远程应用，部署发布机，然后添加资产
https://kb.fit2cloud.com/?p=c207be97-6439-4d19-b228-4f1ac7da831e

**Comment by BaiJiangJie** [comment]
> 添加一个远程应用，部署发布机，然后添加资产 https://kb.fit2cloud.com/?p=c207be97-6439-4d19-b228-4f1ac7da831e

按着文档成功了吗？ @cellomi
