### ISSUE TITLE
[Bug] 3.5.0 jms_web访问chen bug

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#11040]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
jms_web 的配置文件中chen的配置文件没有及时更新 还是使用的omnidb，导致页面404

**Bug 重现步骤(有截图更好)**
1.docker exec -it jms_web bash
2.cat /etc/nginx/conf.d/default.conf 
<img width="523" alt="企业微信截图_d8c54ca5-d5a0-40a7-a355-1545ded6109f" src="https://github.com/jumpserver/jumpserver/assets/81400245/f19dad22-a34a-4a06-8c66-1326b7dc5d55">
3.将omnidb改成chen 问题修复
<img width="536" alt="image" src="https://github.com/jumpserver/jumpserver/assets/81400245/207125b8-83cc-464a-9721-d041d0f8af64">

**Comment by ibuler** [comment]
已经更新了，分支忘记合并了
