### ISSUE TITLE
[Bug] v3.5.0 自动代填功能无法自动填写用户名

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#11046]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**
Chrome 版本 114.0.5735.199（正式版本） （64 位）

**Bug 描述**
Web 资产的自动代填功能无法自动填写用户名，只能填写密码和点击登录按钮，导致报错，无法正常登录，手动填写用户名后可以正常登录。
检查了 2个 Web 资产的页面元素，确认用户名选择器填写正确。
升级此版本前使用的 v3.4.3 版本自动代填功能是正常的。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by saszhuqing** [comment]
基本可以确认是同名账号部分出问题了，又测试了一下windows资产，使用同名账号无法正常登录，提示 Abort，see logs 。在资产授权里改成手动账号，用同样的账号就能正常登录。

**Comment by BaiJiangJie** [comment]
嗯，v3.5.1 版本修复了。更新一下最新版本。

**Comment by saszhuqing** [comment]
升级到 v3.5.1 版本，测试了 Windows 和 Web 资产，同名账号代填功能正常，可以正常登录了。
