### ISSUE TITLE
普通用户的sudo命令当有多个时无法推送成功

### ISSUE THREAD

**Issue by mgdsxhy** [jumpserver/jumpserver#1104]
[简述你的问题]
系统用户里的普通用户，需要给他增加多个sudo命令，但只能推送成功一个

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
v1.0

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/6211830/37746846-21860eda-2db7-11e8-8a02-ae4c84730ab9.png)

2. [步骤2]
![image](https://user-images.githubusercontent.com/6211830/37746857-331a08a4-2db7-11e8-8a02-14da9efc574c.png)
只成功推送了一个，如果后期再加sudo命令则无法推送

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
我这边没有复现。请重新授权试试

**Comment by ibuler** [comment]
之前版本有个bug，更改系统用户配置后，关联节点丢失，现在master分支修复了

或者 你可以选择手动推送
