### ISSUE TITLE
[Question] 使用同名账号无法登录Windows资产

### ISSUE THREAD

**Issue by WeiYingZhe** [jumpserver/jumpserver#11041]
v3.5.0更新后使用同名账号无法登录Windows资产，手动填写就没有问题。
之前的用户名是不带有域名的，点连接后转一两圈就黑屏了；现在我改成带域名后就一直转圈圈，时间长了就出现连接异常 Aborted. See logs.
![image](https://github.com/jumpserver/jumpserver/assets/98902853/41e59f1e-0018-4663-ba29-ee3b0fc195f6)

**Comment by saszhuqing** [comment]
> RDP和Web访问第一次分辨率不正常，要重新连接一次才会正常的分辨率 @wojiushixiaobai @BaiJiangJie

我这边多次断开重连依然不正常，清理浏览器缓存或者使用无痕模式都没用。

**Comment by BaiJiangJie** [comment]
v3.5.1 修复了同名账号无法登录Windows资产的问题。

分辨率问题（目前是居中显示，没有展开），计划在 v3.5.2 中修复。

@WeiYingZhe @saszhuqing

**Comment by jym503558564** [comment]
请更新至最新版本进行测试，如有问题可再次提Issues。
