### ISSUE TITLE
[Bug] 审计台的仪表盘里面的会话趋势和用户登录趋势两个是不显示

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11058]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0
**浏览器版本**
版本 115.0.1901.183 (正式版本) (64 位)
**Bug 描述**
从[v2.28.16]升级到V3.50 使用倒是没有问题 但是界面有些数据是不显示的！比如审计台的仪表盘里面的会话趋势和用户登录趋势两个是不显示的！控制台里面的用户/资产活跃情况也无法正常显示！
**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/70053869/c01762dc-8ee8-45f3-a405-3ad80917827f)
![image](https://github.com/jumpserver/jumpserver/assets/70053869/7d32acdb-c8dd-45c4-8328-a195b531f3c6)

**Comment by BaiJiangJie** [comment]
我看页面看的是近30天的数据，

今天、近7天的数据可以正常显示吗？

**Comment by JeongHyeokLee** [comment]
都是一样的都不显示

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/c95a1664-553a-4a38-86b5-af17375ea94a)
![image](https://github.com/jumpserver/jumpserver/assets/70053869/73e8e2b1-6c26-4fdb-a908-707ba72a9d8f)

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/dc888a9c-d207-4207-a703-8d75cb0cc82c)
控制台里面的仪表盘上面的用户/资产活跃情况也不显示

**Comment by BaiJiangJie** [comment]
<img width="2553" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/3d518744-fac0-43f3-bcab-14f7d19d45b6">
<img width="2360" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/e0686c81-0091-4bed-bdf5-02abffb60656">

**Comment by BaiJiangJie** [comment]
我本地看没什么问题。

你看一下浏览器的 API 请求返回结果。

**Comment by BaiJiangJie** [comment]
<img width="1747" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f24d3c5f-e157-424b-ab21-42fbe29b7a4a">
<img width="1547" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/99029613-816c-4d29-a9b8-8ffd88ffa988">

看看 Response。

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/94cab9bc-1a30-4378-8662-d51f45d3fd9e)
是不是我数据库升级的时候有问题！

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/3f676317-b0a2-4c23-9c8e-3b8f70087f2d)
我再可视化撸一遍数据库看看！应该是这个问题导致的吧。

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/8d13f2a9-18a3-4570-b082-1231a0b790b3)
这个sql查询的是那几个表能告诉我么？

**Comment by JeongHyeokLee** [comment]
我新部署了一组分布式的 还是这样字。。。。。怪了。。。。。。。。。。

**Comment by BaiJiangJie** [comment]
后端数据没有获取到。

**Comment by BaiJiangJie** [comment]
可以先看一下 terminal_session 表的数据。
