### ISSUE TITLE
[Question] jumpserver基于SAML2接入idp后，如果处理终端登录的问题

### ISSUE THREAD

**Issue by adoo123** [jumpserver/jumpserver#11051]
版本：2.28.8
在接入SAML单点登录后，终端无任何变化，即使我把数据源改成了SAML2，也还是跟之前一样，需要账号密码验证
请问这个能和web端一样，使用idp验证吗

**Comment by O-Jiangweidong** [comment]
SAML2协议依赖浏览器之间的重定向进行认证，目前还不支持终端直连的方式

可以使用临时密码登录终端，临时密码需要修改jumpserver的配置文件config.txt(AUTH_TEMP_TOKEN=true)重启生效，临时密码功能在用户个人界面使用

**Comment by adoo123** [comment]
好的
