### ISSUE TITLE
[Question] jumpserver基于SAML2对接自建SSO后，出现重复验证的情况

### ISSUE THREAD

**Issue by adoo123** [jumpserver/jumpserver#11050]
版本：2.28.8
基于SAML2对接自建SSO完成后，频繁在验证页和idp登录页之间跳转，有时跳一次就进入主页了，有时要跳5次
![image](https://github.com/jumpserver/jumpserver/assets/32384019/2fcec9e2-6b5f-4f67-b3b6-42a721e5b815)
![image](https://github.com/jumpserver/jumpserver/assets/32384019/1850e3d7-8491-4b7c-8c1b-8cf5e69bed34)
发现重新跳转的时候/api/v1/users/profile/接口是401
![image](https://github.com/jumpserver/jumpserver/assets/32384019/efc98b67-f79c-4683-9e7e-d28d46cbb132)

**Comment by O-Jiangweidong** [comment]
麻烦在出现多次重定向跳转认证的时候，看一下jumpserver.log的日志，给个截图

**Comment by adoo123** [comment]
我们是docker部署的，并且没有挂载文件出来，请问日志的位置是在哪里
![image](https://github.com/jumpserver/jumpserver/assets/32384019/8d8488a3-90fb-4aa7-988c-7468aa54fbb5)

**Comment by O-Jiangweidong** [comment]
如果近期升级了3.5版本的话，日志目录在这个层级下
<img width="1107" alt="image" src="https://github.com/jumpserver/jumpserver/assets/80373698/7876bf13-2648-4644-a566-46afc324f760">

**Comment by O-Jiangweidong** [comment]
配置文件中的日志级别LOG_LEVEL最好修改为DEBUG，可以看到更详细的日志信息
