### ISSUE TITLE
[Feature] 希望docker配置文件能增加个绑定启动IP的项目之前2.2X版本是支持的。希望恢复这个功能！

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11059]
希望docker配置文件能增加个绑定启动IP的项目之前2.2X版本是支持的。希望恢复这个功能！

**Comment by BaiJiangJie** [comment]
绑定启动 IP 是什么意思？

**Comment by JeongHyeokLee** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/70053869/0899fe9f-653a-474a-a830-1cd777334992)
之前的启动docker的时候可以指定绑定到哪个IP上面 比如我有两个IP一个是8.8.8.8这种公网的 一个是192.168.0.1一个是内网  当我绑定192.168.0.1的时候  就只有内网的IP可以访问 公网的IP就无法访问！

**Comment by wojiushixiaobai** [comment]
你可以自己改 compose/docker-compose-app.yml 文件，如果这里要加判断还会涉及到 ipv6 的判断，有点难搞

**Comment by JeongHyeokLee** [comment]
OK已经测试 谢谢！
