### ISSUE TITLE
[Bug] v3.5.0 数据库WebGUI连接错误

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#11056]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/14314203/752b49e5-b7c8-4d77-862b-d8497f26ecfe)

**Comment by wushengmin** [comment]
重新拉一下jumpserver/web:v3.5.0就可以了

**Comment by mjwtc0722** [comment]
> 

没用，一样的报错

**Comment by BaiJiangJie** [comment]
右击浏览器-检查，看一下报什么错？

**Comment by mjwtc0722** [comment]
> 右击浏览器-检查，看一下报什么错？

![image](https://github.com/jumpserver/jumpserver/assets/14314203/965927f2-498b-461e-8183-7bba4d8583a5)
We're sorry but doesn't work properly without JavaScript enabled. Please enable it to continue.

**Comment by BaiJiangJie** [comment]
详细描述一下。

连接的什么数据库类型？
API 请求报错，请求提、响应体是什么？

**Comment by dhfsqxz** [comment]
我这里也出现了
尝试了3.4.3升级3.5.0
也试过升级3.5.1
不过我这里提示不是404而是502
![image](https://github.com/jumpserver/jumpserver/assets/74221255/f29b552b-9128-4c5c-bd51-730e5bf15c85)
![image](https://github.com/jumpserver/jumpserver/assets/74221255/c94478a7-4dbc-4b5b-9015-76ee96765cc3)
