### ISSUE TITLE
[Feature] web页面下载配置文件

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#11053]
**请描述您的需求或者改进建议.**
在使用web设备的时候，有时候有保存配置并导出的需求。使用咱们的堡垒机好像有相关的禁止。导出来配置之后无法通过浏览器下载。

烦请考虑一下我的建议

**Comment by BaiJiangJie** [comment]
使用最新的 v3.5 版本试一下可以吗？对于 Chrome 远程应用有一些优化，升级后需要重新部署一下发布机 和 Chrome 远程应用。

**Comment by qianyu-0712** [comment]
已经测试了，使用vsphere去down导出的列表还是没有弹出下载框。此外测试如果新开一个页面，能够正常弹出了

**Comment by BaiJiangJie** [comment]
对，需要新开一个窗口，限制了默认打开的窗口不能弹出新窗口。

**Comment by BaiJiangJie** [comment]
每个页面的下载链接都不一样，可以远程看一下你的场景吗？

**Comment by qianyu-0712** [comment]
可以的，我在JumpServer华东地区交流群1里，前羽。目前的场景是vcenter的导出虚拟机清单。烦请链路

**Comment by BaiJiangJie** [comment]
https://jumpserver.org/

加入官网最下面的技术交流群，下周咱们约个时间。

**Comment by BaiJiangJie** [comment]
v3.6 版本已解决。

对应资产 Web 平台中关闭安全模式。就可以弹窗了。
