### ISSUE TITLE
系统用户名过长ssh登录卡死

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#1106]
[简述你的问题]

##### 使用版本
Jumpserver1.0.0

##### 问题复现步骤
系统用户设置过长就会卡在如下的图，一直卡住不动。

![11323](https://user-images.githubusercontent.com/24326988/37755896-3d80f5b6-2de2-11e8-854b-9f66a90cb3ce.png)
 

群里的朋友发现的
已经验证
![123](https://user-images.githubusercontent.com/24326988/37755951-73ac3e5c-2de2-11e8-9586-bcbeec4749aa.png)

测试的过程中发现，每次修改增加几个字符并重新登录并不会卡死，但是新建系统用户，一次性这么长的就会卡死。
![111111](https://user-images.githubusercontent.com/24326988/37756065-055c826c-2de3-11e8-831a-ca917e430eb9.png)

。。。

**Comment by ibuler** [comment]
。。。这个bug暂时不处理
