### ISSUE TITLE
windows历史会话无法查看！？

### ISSUE THREAD

**Issue by Cuigeek** [jumpserver/jumpserver#1107]
Windows的历史会话没法查看吗？无法看到录像的话Windows堡垒机功能就弱化了

##### 使用版本
Jumpserver 1.0版本

##### 问题复现步骤
1. Windows系统的历史会话无法查看
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20765447/37761180-e8383d78-2df3-11e8-993e-85d270b10042.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
下个小版本release出来
