### ISSUE TITLE
[Bug] 上传文件winserver会蓝屏

### ISSUE THREAD

**Issue by qq1012482327** [jumpserver/jumpserver#11081]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**浏览器版本**
Microsoft Edge
版本 115.0.1901.183

**Bug 描述**
充当发布机的winserver2016蓝屏过四五次，每次蓝屏都是因为在web端上传文件，查看winserver2016日志没有发现异常

**Bug 重现步骤(有截图更好)**
1.
![c11755571c0a777ab50e57f9d5d29cf](https://github.com/jumpserver/jumpserver/assets/63997866/7b9848aa-a211-4acd-b379-75f7821d52c0)

![46fb589687ad37abd34afc148cf982b](https://github.com/jumpserver/jumpserver/assets/63997866/ed024207-c484-4202-abc8-319b654ee695)

2.
3.

**Comment by qq1012482327** [comment]
![c11755571c0a777ab50e57f9d5d29cf](https://github.com/jumpserver/jumpserver/assets/63997866/a127b1cd-e56c-40a6-8032-9fa4689321c3)

**Comment by ibuler** [comment]
等待更多 case 反馈
