### ISSUE TITLE
[Feature] 右键里的文件管理，能给加上不

### ISSUE THREAD

**Issue by harbour015** [jumpserver/jumpserver#11097]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/48000268/2338c498-2d58-4579-89c4-efb806531231)

之前的版本一直在用的文件管理功能，用习惯了。这个能给加到3.x的版本不
![image](https://github.com/jumpserver/jumpserver/assets/48000268/9b165bcc-513d-4e56-bef9-8465f17fe08d)

**Comment by BaiJiangJie** [comment]
现在所有的连接方式都统一了，使用习惯比较好理解，尤其是新接触的用户。

对于老用户来说可能会觉得没有之前方便了，这个我确实也遇到过。

其中还有一个最主要的核心问题，

有些用户想手动登录文件管理，v2 的版本是不支持，没有手动输入账号密码的页面；

v3 版本统一之后，可以使用手动登录的用户登录，因为登录页面的账号选择都统一了。

所以暂时先不考虑放回到右击快捷键里了。

**Comment by BaiJiangJie** [comment]
<img width="2559" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f01686a2-72fb-4338-b9c9-4fae34c445ec">

可以直接进入到完全的文件管理页面进行操作。
