### ISSUE TITLE
luna的终端资产排序不对

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#1110]
[简述你的问题]
请看图，coco 配置资产为以 hostname 排序，但luna终端中排序不对

##### 使用版本
1.0

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/3265516/37809516-5c96f5d6-2e82-11e8-968e-a4c153a16ff7.png)

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
