### ISSUE TITLE
[Bug] 主机资产可连接性显示错误

### ISSUE THREAD

**Issue by jerry202307** [jumpserver/jumpserver#11105]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.5.0

**浏览器版本**
谷歌浏览器、Edge

**Bug 描述**
主机资产可以通过jumpserver的web端登陆，但是可连接状态显示错误状态（我的主机是通过网域网关才能进行连接，就是我的业务服务器的SSH端口只对网域网关这台服务器开放，所以我想要连接服务器的时候，需要在配置里面添加网域网关，但是这样导致主机资产里面的可连接状态为错误状态）

**Bug 重现步骤(有截图更好)**
1.添加一个网域，然后在这个网域里面添加一个主机当做登陆服务器的跳板机（因为业务服务器的SSH端口只对这台跳板机开放）
2.主机资产里面的可连接状态就会显示错误
3.通过主机资产里面的测试连接功能测试连接，也会显示无法连接到目标服务器
![image](https://github.com/jumpserver/jumpserver/assets/140630834/e8b15fbc-8de9-4267-ac20-496ce3c984d7)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/06745ef0-3245-4379-8b89-95e62f6858e4)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/8471af4b-4257-4a9f-ad54-e9ee7deb323e)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/14abfe0c-16b1-433a-82db-fa93ca307702)

**Comment by BaiJiangJie** [comment]
配置文件开一下 DEBUG_ANSIBLE=1 再次执行看看详细日志
