### ISSUE TITLE
[Bug] ChatGPT资产无法正常使用

### ISSUE THREAD

**Issue by jerry202307** [jumpserver/jumpserver#11103]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.5.0

**浏览器版本**
谷歌浏览器、edge

**Bug 描述**
使用添加好的GPT资产的时候，GPT返回ChatGPTResponse parse json error错误，尝试过更换ChatGPT的key，依旧如此

**Bug 重现步骤(有截图更好)**
1.添加ChatGPT资产
2.资产授权给指定用户
3.登陆有ChatGPT使用权限的用户开始对话
4.返回错误
5.报错截图、资产截图、apikey使用截图
![image](https://github.com/jumpserver/jumpserver/assets/140630834/a81dddb4-c4bb-4b1e-b887-1459b2d7d659)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/c9b7d9df-3929-4c13-b4f2-e65bb320d4e6)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/f0a846a3-ae58-4bda-a7dd-05eb50bc7cf9)
![image](https://github.com/jumpserver/jumpserver/assets/140630834/2a11e52f-11c0-4897-8030-d4e28a54ddec)

**Comment by BaiJiangJie** [comment]
以前有其他用户遇到过，应该是你的账号额度过期了。
