### ISSUE TITLE
[Bug] v3.5.0 RDP分辨率异常

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#11104]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**
版本 115.0.5790.102（正式版本） （64 位）

**Bug 描述**
Web 终端 - 设置 - 图形化 - RDP 分辨率，为默认值 Auto
通过 RDP 连接到 Windows 资产，或连接到 Web 资产时，分辨率异常，无法根据当前窗口大小自动调整为合适的分辨率。尝试断开资产重新连接、清除浏览器缓存、使用无痕窗口重新登录再连接资产等方式，均无法解决。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by liubo637** [comment]
同样的问题，尝试重新打开使用齿轮工具中的“自动适应”后，再重新连接rdp可以恢复分辨率，缩小放大浏览器亦可恢复自动分辨率。

**Comment by saszhuqing** [comment]
> 同样的问题，尝试重新打开使用齿轮工具中的“自动适应”后，再重新连接rdp可以恢复分辨率，缩小放大浏览器亦可恢复自动分辨率。

我这边通过缩小放大浏览器可以恢复自动分辨率，调整齿轮工具中的没有效果，但断开资产重新连接后，又无法自动分辨率了。

**Comment by BaiJiangJie** [comment]
v3.5.2 中会优化。

**Comment by saszhuqing** [comment]
升级到 v3.5.2 后确认已修复此 bug
