### ISSUE TITLE
容器添加hostname

### ISSUE THREAD

**Issue by renziyou** [jumpserver/jumpserver#11112]
**请描述您的需求或者改进建议.**
背景：因确保安全，域控中限制了域用户只能登陆指定PC。因此域用户中需要添加lion ID 才能解决堡垒机用户正常连接。但容器ID是会变的。因此希望后续版本上能配上容器hostname

需要：容器配上hostname信息

**Comment by BaiJiangJie** [comment]
v3.6 和 v3.5.2 支持一下。

**Comment by BaiJiangJie** [comment]
Hostname 默认是容器的名称，比如 jms_lion

<img width="672" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2f7ef847-8978-41a3-9ba3-daa1e2582592">

**Comment by BaiJiangJie** [comment]
需要支持配置域吗？

比如 fit2cloud

默认登录到容器里就是 root@jms_core.fit2cloud

现在是：root@jms_core

**Comment by renziyou** [comment]
目前Hostname 默认是 容器ID 只要有重启或升级ID就会变。所以绑定工作站没有用。因此希望在docker-compose-app.yml  加 上hostname
![image](https://github.com/jumpserver/jumpserver/assets/8150303/c1fc69c0-67c6-4a2e-bc8d-b986544c6bf0)

**Comment by renziyou** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/8150303/7fc13561-845e-4e0d-9b39-9a6a3d49abf0)
原来这块需要填容器ID 但ID会变，所以希望增加hostname

**Comment by BaiJiangJie** [comment]
嗯 已经加上了，https://github.com/jumpserver/installer/pull/334/files

hostname 的值还有其他特殊要求吗？

**Comment by renziyou** [comment]
谢大佬，暂时没

**Comment by BaiJiangJie** [comment]
好的。

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持。
