### ISSUE TITLE
主机组Comment内容配置问题

### ISSUE THREAD

**Issue by yuanguoping** [jumpserver/jumpserver#1111]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.0.0]

##### 问题复现步骤
请问“输入 G/g 显示您有权限的主机组” 显示的Comment内容在哪里配置？
![qq 20180323155342](https://user-images.githubusercontent.com/34155972/37817993-993336b8-2eb3-11e8-93a2-f4d5f1544cc0.png)

**Comment by ibuler** [comment]
遗留的问题，节点现在没有备注这个字段

**Comment by yuanguoping** [comment]
好的，感谢！
