### ISSUE TITLE
[Question] v2.19 升级到v3.5   接口问题

### ISSUE THREAD

**Issue by dwdaiwei** [jumpserver/jumpserver#11115]
v2.19 升级到v3.5 web终端连接资产时
接口 http://公网ip/api/v1/authentication/connection-token/  一直是pending状态 
在部署的服务机器上 curl http://公网ip/api/v1/authentication/能通     curl http://公网ip/api/v1/authentication/connection-token/ 不通

**Comment by dwdaiwei** [comment]
已经解决

**Comment by serven007** [comment]
我也遇到同样问题，请问如何解决的，谢谢
