### ISSUE TITLE
[v3.5.1] 对于已经授权的资产没有标记，容易再次选中

### ISSUE THREAD

**Issue by simplove** [jumpserver/jumpserver#11124]
**请描述您的需求或者改进建议.**
![](https://img.233444.xyz/imgs/2023/07/98a04156a5ac4d2f.png)
![](https://img.233444.xyz/imgs/2023/07/51192082006b8dd1.png)
老版本中是有标记的，升级到V3以后这个功能就没了

**Comment by BaiJiangJie** [comment]
好的，v3.6 版本中优化一下。

**Comment by BaiJiangJie** [comment]
已优化。
