### ISSUE TITLE
[Feature] 资产授权页面分类的建议

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#11127]
**请描述您的需求或者改进建议.**
资产授权页面，有个难点就是给授权命名，当资产较多时，命名要想半天，而且授权较多时，难以直观看出授权作用。
建议资产授权页面分几个子页面，比如，按用户授权、按用户组授权、按组织结构授权、按功能组授权、按标签授权
就可以省去授权的命名，比较直观一些

**Comment by BaiJiangJie** [comment]
v2 版本应用和资产是分开的，v3 的一大亮点就是合并了资产和应用的授权。

对于命名的问题，其实和写程序时命名变量一样，是一个技术活。

用户可以定义一套自己的命名规则，同类型的授权加一些前缀来解决这个问题。

产品设计上就暂时不考虑了。
