### ISSUE TITLE
更新jumpserver时报错

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1113]
[简述你的问题]
从0.5版本更新到1.0版本，最后  sh make_migrations.sh 执行这步报错

##### 使用版本
[Version 1.0.0-2 GPLv2]

##### 问题复现步骤
$ cd /opt/jumpserver  && source /opt/py3/bin/activate
$ git pull && pip install -r requirements/requirements.txt
$  cd utils && sh make_migrations.sh
-----------------------------------------------------------------------------
2018-03-23 16:20:50 [signals_handler DEBUG] Receive django ready signal
2018-03-23 16:20:50 [signals_handler DEBUG]   - fresh all settings
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0008_auto_20180307_1601, 0006_auto_20180210_1226 in django_celery_beat).
To fix them run 'python manage.py makemigrations --merge'
2018-03-23 16:20:52 [signals_handler DEBUG] Receive django ready signal
2018-03-23 16:20:52 [signals_handler DEBUG]   - fresh all settings
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0006_auto_20180210_1226, 0008_auto_20180307_1601 in django_celery_beat).
To fix them run 'python manage.py makemigrations --merge'

**Comment by ibuler** [comment]
```
$ ls /opt/py3/lib/python3.6/site-packages/django_celery_beat
$ rm -rf /opt/py3/lib/python3.6/site-packages/django_celery_beat
$ pip uninstall django_celery_beat
$ pip install django_celery_beat
```

**Comment by qianghong000** [comment]
解决了，very感谢！

**Comment by qianghong000** [comment]
请问现在jumpserver是不是应该拉取master分支了

**Comment by qianghong000** [comment]
我的服务器是linux系统  windows支持组建 guacamole 组件是不是可以不装，是做什么用的

**Comment by qianghong000** [comment]
两个分支下面内容一样，测试环境按照你给的方法好像没警告。我在另一台测试环境中用同样的方式，那条警告信息还存在：
WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
