### ISSUE TITLE
[Feature] 账号改密模块优化其显示

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11132]
**请描述您的需求或者改进建议.**
版本：3.5.0
路径“账号管理-账号改密-执行列表”  这里，显示非常不友好。如果有执行很多改密任务，这里会有对应的多条执行记录；然而每条执行记录没有一个可识别的ID，很难快速找到刚刚执行的任务。
希望这里能把改密任务的名称显示出来，以提高各个任务的识别度。

**Comment by BaiJiangJie** [comment]
好的，确实有问题，信息显示的太少了。

v3.6 优化一下。

**Comment by BaiJiangJie** [comment]
v3.6 版本已优化。
