### ISSUE TITLE
[Feature] 命令审计中支持展示账号信息。

### ISSUE THREAD

**Issue by garyhuseh** [jumpserver/jumpserver#11139]
**请描述您的需求或者改进建议.**
版本：3.x
问题：在命令审计中没有账号信息列表，但是在筛选的时候有账号的选项

**Comment by BaiJiangJie** [comment]
嗯，下个版本列表中显示一下。

v3.6 和 v3.5.3 支持。

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持。
