### ISSUE TITLE
guacamole 组件是什么

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1114]
[简述你的问题]

##### 使用版本
[Jumpserver1.0]

##### 问题复现步骤
我的服务器是linux系统 windows支持组建 guacamole 组件是不是可以不装，是做什么用的

**Comment by wojiushixiaobai** [comment]
如果不需要使用jumpserver管理windows服务器，可以略过。nginx配置文件里面请注释相关代码

**Comment by qianghong000** [comment]
好的，谢谢
