### ISSUE TITLE
[Bug] jms_web容器无法启动

### ISSUE THREAD

**Issue by Anorpi** [jumpserver/jumpserver#11160]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**
版本 115.0.5790.110（正式版本） （64 位）

**Bug 描述**
使用命令 ./jmsctl.sh upgrade v3.5.2 从 v3.3.0 升级后，jms_web容器 无法正常启动，报错：
`nginx: [emerg] host not found in upstream "chen" in /etc/nginx/conf.d/default.conf:87`

**Bug 重现步骤(有截图更好)**
1. ./jmsctl.sh upgrade v3.5.2 从 v3.3.0 升级
2. ./jmsctl.sh start
3. 访问 web页面显示无法连接
4. ./jmsctl.sh status 查看状态 jms_web 一直重启中。查看报错为：
    `nginx: [emerg] host not found in upstream "chen" in /etc/nginx/conf.d/default.conf:87`

**Comment by wojiushixiaobai** [comment]
参考文档正确升级问题自然解决。

**Comment by Anorpi** [comment]
为了方便管理 `CONFIG_DIR` 我们是自定义了。
不能在当前安装路径下 执行 ./jmsctl.sh upgrade 来升级吗。

比如项目是部署在 /data/app/jumpserver 下的，使用cd /data/app/jumpserver  &&  ./jmsctl.sh upgrade 后，再使用  ./jmsctl.sh version 查看版本，会显示最新版本。

但脚本自动下载的 jumpserver-installer-v3.5.2 目录下的一些文件不会被拷贝到 /data/app/jumpserver 下。
比如：compose 目录。

里面的 docker-compose-app.yml 会在启动的时候拉起来关联的组件，但 v3.5.2 新增的 **chen**、**kael**，因为在 v3.3.0 的docker-compose-app.yml 文件中不存在，导致没有拉取和启动这两个组件。

**Comment by wojiushixiaobai** [comment]
😂 如果非得说一下，你的行为可以用一句话来形容：**拿明朝的剑斩清朝的官**

我们不知道未来会发生什么，所以正常情况下软件的支持都是 `向下兼容`，而不会`向上兼容`。

至于你修不修改代码代码这与本问题无关，你可以在遵守项目 LICENSE 的情况下进行任意修改。
