### ISSUE TITLE
[Feature] Web应用服务器建议

### ISSUE THREAD

**Issue by WeiYingZhe** [jumpserver/jumpserver#11162]
1、应用服务器对于某些web的标签页或链接不友好。例如，我这边的堡垒机管理着一台华为的ASG5550，点击他的标签页进行跳转的时候会整个chrome窗口只显示标签页内的内容，原本web的header之类的都不见了。希望能优化一下。下图是点击系统管理之后的效果。
![1690940136476](https://github.com/jumpserver/jumpserver/assets/98902853/75cf5019-9535-4cac-833c-8eff21318d5d)
![1690940197832](https://github.com/jumpserver/jumpserver/assets/98902853/6145335b-fb52-4936-8299-70cb4792d4e2)

2、云平台的“VNC登录”无法使用，VNC登录都是以新的窗口弹出VNC界面，版本更新后对新窗口有限制。希望能优化一下。

3、某堡垒机的禁止手动点击“打开新的标签页”这种模式会不会对以上两种情况有所优化。
![1690940612574](https://github.com/jumpserver/jumpserver/assets/98902853/a96b2fbd-8dab-46d7-8ec8-c91ebef843e1)

以上是一些小问题及建议，望能优化，谢谢！

**Comment by BaiJiangJie** [comment]
好的，v3.6 版本优化一下。

Web 平台，支持配置是否启用安全模式。

**Comment by WeiYingZhe** [comment]
> 好的，v3.6版本优化一下。
> 
> Web平台，支持配置是否启用安全模式。
> 
> 如果不开启安全限制模式，那使用浏览器就不行了。

感谢

**Comment by BaiJiangJie** [comment]
v3.6 版本已支持。

**Comment by WeiYingZhe** [comment]
> v3.6 版本已支持。

  我好像没看到在哪里可以设置
