### ISSUE TITLE
[Bug] 终端健康警告

### ISSUE THREAD

**Issue by gyf19** [jumpserver/jumpserver#11167]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**
chrome 114

**Bug 描述**
系统自动离线了

**Bug 重现步骤(有截图更好)**
<img width="817" alt="image" src="https://github.com/jumpserver/jumpserver/assets/233857/af693948-2e9c-478b-b1a3-c6712e16f79d">

**Comment by BaiJiangJie** [comment]
看看系统设置-终端管理里面，是不是有离线的终端。
