### ISSUE TITLE
[Bug] sftp 上传文件后，查看文件为0，有时还会出现上传过程中卡顿是什么原因？[Question] 

### ISSUE THREAD

**Issue by yzqcymx** [jumpserver/jumpserver#11165]
**请描述您的问题.**
sftp 上传文件后，查看文件为0，有时还会出现上传过程中卡顿是什么原因？

**Comment by yzqcymx** [comment]
sftp 上传文件后，查看文件为0，有时还会出现上传过程中卡顿是什么原因？

**Comment by BaiJiangJie** [comment]
什么版本？

**Comment by wufeiqun** [comment]
我也遇到了相同的问题, 使用的版本为3.5.0, 现象是使用mobaxterm上传文件会卡住, 进度条显示为0, 但是使用mac通过命令行没问题
<img width="1442" alt="image" src="https://github.com/jumpserver/jumpserver/assets/7486508/8696977a-1a66-4d49-a715-2421028858b3">

**Comment by jym503558564** [comment]
3.8.1版本测试，无法复现。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/86a9b107-51f5-4737-9297-f632e5871a4e)

**Comment by jym503558564** [comment]
有些工具需要开启token复用，可开启token复用进行测试。如果还有问题，可再次打开issues
