### ISSUE TITLE
远程应用 发布机账号问题

### ISSUE THREAD

**Issue by LoveThemeFromTIGA** [jumpserver/jumpserver#11163]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.5.1

**浏览器版本**

**Bug 描述**
3.5.0升级到3.5.1之后，；连接第1个远程应用正常（Chrome或DBeaver其中一个），连接第2个远程应用会出现“Core API 出现错误”
![image](https://github.com/jumpserver/jumpserver/assets/17798748/14fb1e5f-9c53-4b0e-a602-19186b7cc86a)

**Bug 重现步骤(有截图更好)**
1. 远程应用机信息
![image](https://github.com/jumpserver/jumpserver/assets/17798748/e404d74b-ca66-4b1a-9e64-de59e7c16700)

2. 连接第1个远程应用DBeaver（正常）
![image](https://github.com/jumpserver/jumpserver/assets/17798748/fdd4c729-d6e8-4806-820e-ef8c2e2f5e64)

3. 连接第2个远程应用DBeaver （报错）
![image](https://github.com/jumpserver/jumpserver/assets/17798748/14fb1e5f-9c53-4b0e-a602-19186b7cc86a)

>在3.5.0表现是第2个远程应用正常连接，但同时会将第1个远程应用踢下线，在第1个远程应用窗口会提示类似于“已断开连接，因为已与远程计算机建立了另一个连接”“的提示

4. 错误日志
`jumpserver.log`中的错误日志
```text
2023-08-02 09:43:47 [applet ERROR] Applet host remain public accounts: 172.16.4.31: 0
```
>没有其他日志了，特意重定向清理了日志，出现错误时只会产生这一行日志

**Comment by LeeEirc** [comment]
检查下发布机里的账号，应该会从发布机里的账号选择一个可用的

**Comment by LoveThemeFromTIGA** [comment]
> 检查下发布机里的账号，应该会从发布机里的账号选择一个可用的

我是将Jms_*用户都删除了，期望只使用js_${username} 的用户去登录windows；

**Comment by LoveThemeFromTIGA** [comment]
> 这是两种类型的账号， `js_ `是优先使用的同名用户，`jms_ `是共用的账号池。如果你删掉 `jms_` 的账号，那么同一用户同一时间只能连接一个远程应用。

在3.5.0表现是第2个远程应用正常连接，但同时会将第1个远程应用踢下线，在第1个远程应用窗口会提示类似于“已断开连接，因为已与远程计算机建立了另一个连接”的提示

**Comment by LeeEirc** [comment]
那之前的表现是不正常的。因为已经在使用的账号，未退出之前，理论上不应该被再次调度使用。
