### ISSUE TITLE
[Question] No logs in Celery

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [jumpserver/jumpserver#11179]
We deployed JumpServer using our own local Kubernetes cluster with a clean install. We have our own IIS proxy with Nginx as our ingress controller, and the web service is being exposed as an ingress entry which we can log into and we do have remote access to our servers but we cannot see the Ansible logs in Celery, so there is nothing in the task output:
![image](https://github.com/jumpserver/jumpserver/assets/112843587/def634ab-c689-45a1-a0b0-2b00d58d9811)
However, I noticed that in /opt/jumpserver/data/logs/celery_ansible.log, the Ansible output is visible with color.

**Comment by BaiJiangJie** [comment]
Yes, so is the problem solved now?

**Comment by wizpresso-steve-cy-fan** [comment]
@BaiJiangJie No it wasn't. I see that the WebSocket connection was stalled with just one message, I'm consulting the Nginx logs now. Could be because of proxy buffering

**Comment by BaiJiangJie** [comment]
Ok, looking forward to your good news.
