### ISSUE TITLE
[Bug] 会话实际上已经关闭，但在线会话一直显示该会话在线

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#11176]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5

之前版本也发现过，重启celery没效果，需要重启堡垒机
<img width="812" alt="361c24382dff46228cd67ff3a34c0da4_" src="https://github.com/jumpserver/jumpserver/assets/66759501/e2e60cd3-c73b-4f40-a8dc-14eb377f7ae0">

**Comment by BaiJiangJie** [comment]
<img width="1738" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/921b80a3-7670-46fb-9e0a-dc66f9e40235">

看看任务列表中这个任务执行正常吗？

**Comment by BaiJiangJie** [comment]
v3.6 版本已解决。是因为 KoKo 组件的会话阻塞问题导致的。
