### ISSUE TITLE
[Feature] 数据库历史账号管理

### ISSUE THREAD

**Issue by sunny5156** [jumpserver/jumpserver#11178]
**请描述您的需求或者改进建议.**
增加数据库账号列表功能，可对历史token账号 进行 删除/续期功能
![image](https://github.com/jumpserver/jumpserver/assets/2882717/a4dba24c-0440-4909-b4e5-9ae36220e502)

**Comment by BaiJiangJie** [comment]
一个 Token 理论上只能使用一次。

但是后端可以配置是否启用 Token 复用。

# 启用复用
CONNECTION_TOKEN_REUSABLE=True

# 单位 s
CONNECTION_TOKEN_REUSABLE_EXPIRATION=3600
