### ISSUE TITLE
[Bug] VNC窗口无法全屏，显示小窗口居中

### ISSUE THREAD

**Issue by yanxu4780** [jumpserver/jumpserver#11189]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**
Edge 115.0.1901.188 / Chrome  115.0.5790.110

**Bug 描述**
更新 v3.5.2版本在Web界面VNC窗口无法全屏，显示**小窗口居中**

**Bug 重现步骤(有截图更好)**
1.正常在我的资产中连接VNC资产
2.在Web终端界面中，点击视图——全屏显示
3.无法全屏，显示小窗口居中
4.退出全屏后，再点击视图——全屏显示，然后才正常全屏
5.Windows相关资产未出现这个bug

**Comment by BaiJiangJie** [comment]
v3.5.1 有这个问题，v3.5.2 应该修复了。

录屏或者截图看一下效果。

**Comment by yanxu4780** [comment]
> v3.5.1 有这个问题，v3.5.2 应该修复了。
> 
> 录屏或者截图看一下效果。
![QQ截图20230804081316](https://github.com/jumpserver/jumpserver/assets/5827407/0f6d4c55-6ba7-4c3b-84b6-b7fa85bb382d)
![QQ截图20230804081333](https://github.com/jumpserver/jumpserver/assets/5827407/a82ce9fe-8dd4-4612-8005-b45646e6a48e)

是v3.5.2版本，全屏就是显示小窗口。Linux的RealVNC服务。

**Comment by BaiJiangJie** [comment]
<img width="2560" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/17d49a79-8fcc-42b4-b446-c7f60be16005">

<img width="2046" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/9e3537cb-0b67-4c6f-afa9-2b4daa11cbe9">


windows vnc 和 linux vnc 都会出现不全屏的问题。

我测试，windows 是左右没有铺满，linux 是上线没有铺满。

后续 Debug 一下看看是什么问题，进行优化。

**Comment by yanxu4780** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/32935519/258283297-17d49a79-8fcc-42b4-b446-c7f60be16005.png"> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/32935519/258283616-9e3537cb-0b67-4c6f-afa9-2b4daa11cbe9.png">
> windows vnc 和 linux vnc 都会出现不全屏的问题。
> 
> 我测试，windows 是左右没有铺满，linux 是上线没有铺满。
> 
> 后续 Debug 一下看看是什么问题，进行优化。

我用Win11系统就会有问题，Win10电脑就没事。然后Win11 21H2也没事，Win11 22H2 和测试版23H2都会复现这个VNC窗口无法自动全屏的bug。EDGE Chrome和360浏览器都一样。只要在Win11 22H2以上系统就会出现这个问题。Win11 22H2以下Windows版本就是正常的。

**Comment by yanxu4780** [comment]
问题很奇怪，测试最后发现是显示器问题，我这个外接显示器打开vnc就小窗口，换一个显示器就正常了。换其他笔记本用同一个显示器也是小窗口。现在判断是显示器和系统哪里不兼容导致的。

**Comment by BaiJiangJie** [comment]
好的，产品层面应该是没问题的。
