### ISSUE TITLE
试用了3.5.1版本，怎么找不到角色列表了

### ISSUE THREAD

**Issue by forwardwayl** [jumpserver/jumpserver#11183]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/24289167/9ccd51a5-1746-42e3-b869-01096f941447)

之前使用的是2.19版本，用户管理下有个 角色列表 的。请问3.5.1版本中，在什么地方

**Comment by BaiJiangJie** [comment]
是的，社区版 v3.0 版本之后不支持自定义角色了，只能使用系统默认的内置角色。
