### ISSUE TITLE
jumpserver 无法发送用户创建时的邮件

### ISSUE THREAD

**Issue by weixp** [jumpserver/jumpserver#1118]
[简述你的问题]
我已经按照要求填写了邮件服务器的配置，并且测试邮件也发送成功，但是正式创建用户发送邮件时还是会报错，报错为Sending mail error: please run connect() first
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.0.0-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
需要彻底重启 Jumpserver

```
$ ./jms stop 
$ ./jms start
```
