### ISSUE TITLE
[Question] About RDS license of feature Remote Website

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11184]
Hello

After long time no use feature Remote Website, I tried it again. But session remote auto sign out, when I check Remote host have notice: No RDS license is available

I tried remove 'GracePeriod' key, but it doesn't work

How can I do to reset RDS license or fix it.

Thank you.

**Comment by BaiJiangJie** [comment]
This is normal and you need to configure the RDS license on windows.

**Comment by tsukiazuma** [comment]
I don't think problem is in configuration the RDS license on windows.
I can remote RDP to server. But can't remote Web through this server.

**Comment by BaiJiangJie** [comment]
Yes, Windows RDS is used to limit this operation, the default should be 30 minutes to automatically log out.

**Comment by BaiJiangJie** [comment]
Sometimes it could be minutes or hours, depending on the Windows version and licensing policy.

**Comment by tsukiazuma** [comment]
Oh sorry, looks like you misunderstood.

Before, I can remote rdp and web to server.
And have a long time, I don't use remote web to server.
Now, I try to use remote web feature again. But it don't work. When I try it, it only connect and sign out within seconds.

**Comment by BaiJiangJie** [comment]
Oh, then check the log of the backend Lion service for any errors?

**Comment by tsukiazuma** [comment]
Yeah have error like:
2023-08-03 18:04:23 tunnel conn.go [ERROR] Session[359128f4-6dc9-480f-bc19-2d286dad194b] receive web client disconnect opcode
2023-08-03 18:04:23 tunnel conn.go [ERROR] Session[359128f4-6dc9-480f-bc19-2d286dad194b] web client read err: websocket: close 1005 (no status)
2023-08-03 18:04:23 tunnel conn.go [ERROR] Session[359128f4-6dc9-480f-bc19-2d286dad194b] guacamole server read err: read tcp 127.0.0.1:58264->127.0.0.1:4822: use of closed network connection

**Comment by tsukiazuma** [comment]
I add more information, have error in \AppData\Local\Programs\Tinker\data\logs:
2023-08-03 17:09:56 [ERRO] Create account js_[Tinker]-RemoteW password err: netUserAdd failed: NERR_BadUsername status=2202 
2023-08-03 17:09:57 [INFO] sync host accounts end

**Comment by tsukiazuma** [comment]
Oh, my problem same https://github.com/jumpserver/jumpserver/issues/10684

**Comment by BaiJiangJie** [comment]
What version are you using?

**Comment by tsukiazuma** [comment]
Product:	JumpServer Community Edition GPLv3
Version:	v3.3.0

**Comment by BaiJiangJie** [comment]
Upgrade to the latest version v3.5.0, redeploy the publishing machine, and reinstall the application.

Versions v3.4 and v3.5 are optimized for remote application installation for Chrome browser.

**Comment by tsukiazuma** [comment]
Yeah, I will try it.
But I think the problem also is RDS license

**Comment by BaiJiangJie** [comment]
There should be no problem at the product level. If the new version still doesn’t work, then look at the RDS problem.

**Comment by tsukiazuma** [comment]
I tried update version Jumpserver, remove RDS on windows server and redeploy the publishing machine.
But process skip:
```
TASK [Set RDS LicenseServer (regedit)] *****************************************
skipping: [RemoteW]

TASK [Set RDS LicensingMode (regedit)] *****************************************
skipping: [RemoteW]

TASK [Set RDS fSingleSessionPerUser (regedit)] *********************************
skipping: [RemoteW]
```
And result don't have change :(

**Comment by BaiJiangJie** [comment]
Is RDS_Licensing of the publishing machine enabled?

**Comment by tsukiazuma** [comment]
No. It is disable

**Comment by BaiJiangJie** [comment]
If it is disabled, then the task display skip is correct.

**Comment by tsukiazuma** [comment]
Oh, how can I do to fix this problem

**Comment by BaiJiangJie** [comment]
@LeeEirc Eric for helping.

**Comment by LeeEirc** [comment]
Could you share a few screenshots ? 
Which version of Windows are you currently using?
Can you outline the steps to reproduce the issue?

**Comment by tsukiazuma** [comment]
Sure.
1. Windows version is 2019
2. Some image about prolem like: https://github.com/jumpserver/jumpserver/issues/10684.

**Comment by LeeEirc** [comment]
Could you check your windows server on `Advanced system settings` about `Environment Variables --- System variables --- Path`? 
It should be like the screenshots below :

![image](https://github.com/jumpserver/jumpserver/assets/32626707/575d3160-363e-430d-b17a-6cf6ffcef279)

**Comment by tsukiazuma** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/75791054/a6ca332b-b9e7-44ec-b653-2f53aa202462)

**Comment by LeeEirc** [comment]
The path value 'C:\Program Files\Chrome\chrome-win32' should be removed. 
Path values on version v3.5.0 or above should be like the screenshot I posted above.
Could you use the latest JumpServer version v3.5.3, and click `Initial deploy ` deploy  button to redeploy again.  
It may be mismatch the version between chrome and chromedriver.

**Comment by LeeEirc** [comment]
any update? @tsukiazuma

**Comment by LeeEirc** [comment]
if you have any other problems, you could create a new issue.
