### ISSUE TITLE
[Bug] 用户批量更新功能异常

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#11187]
**JumpServer 版本( v2.28 之前的版本不再支持 )**		
3.5.1		
		
**浏览器版本**		
firefox 115.0.2		
		
**Bug 描述**		
用户列表-批量导入（更新）		
		
**Bug 重现步骤(有截图更好)**		
1.模板下载，根据导出的清单，填写了ID、名称等，主要是将部分目标用户的”激活“修改为NO		
2.个别字段以为没什么关系，就留空过了,如”用户组	系统角色	组织角色“
3.执行后，目标用户直接就不见了，按用户名、邮箱等都搜索不出来了，重新导入表格更新”用户组之类的“都提示用户对象不存在了”。		
4.实际只是考虑到有些用户长期不用，通过这个功能做个批量禁用而已，但是这些用户现在都无法维护了，新增回来也会提示已存在用户了。譬如”具有 邮箱 的 用户 已存在。“		
5.同时建议提供配置，针对不活跃用户提供自动禁用计划。		
		
![image](https://github.com/jumpserver/jumpserver/assets/38068938/1a8f8112-ca22-4cd4-a30b-68c04ad1e093)

**Comment by BaiJiangJie** [comment]
好的。

5.同时建议提供配置，针对不活跃用户提供自动禁用计划。

采纳建议，计划在 v3.6 版本中支持。

**Comment by BaiJiangJie** [comment]
问题 1-4，我本地先看一下能否复现。

**Comment by BaiJiangJie** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32935519/6d8c18bc-7e6f-4065-a3db-e3cd8ac5f3e0)

<img width="2353" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/0b91071e-b6ff-464b-9615-3ecb86f4ada3">

测试了一下，没问题啊。

你下载更新模版，然后修改后，上传文件。

**Comment by BaiJiangJie** [comment]
针对不活跃用户提供自动禁用计划

在 v3.6 版本已支持。

**Comment by sanpichen** [comment]
> 针对不活跃用户提供自动禁用计划
> 
> 在 v3.6 版本已支持。

是怎样的机制呢，我升级后似乎没看到效果。
版本：docker 升级部署  到 v3.6.2
不活跃用户自动禁用 (天) 30
很多用户加入系统后很久压根都没用过，都没被自动禁用啊

![1693359822055](https://github.com/jumpserver/jumpserver/assets/38068938/ec8f1759-2a4e-4a4c-8090-3cdebe5f4cf8)
