### ISSUE TITLE
[Question] 自定义app，上传报错400

### ISSUE THREAD

**Issue by woyeshixiaobai** [jumpserver/jumpserver#11185]
**请描述您的问题.**
官方应用商店下载plsql，之后自定义platform.yml文件，重新打包上传报bad request
 Failed to load resource: the server responded with a status of 400 ()
detailcode"
"方法“GET” 不被允许。
method not_allowed

以下是platform.yml文件内容,wang'ge'wei望各位大神指正！
[platform.txt](https://github.com/jumpserver/jumpserver/files/12246293/platform.txt)

**Comment by BaiJiangJie** [comment]
看看 API 请求返回报的错误信息是什么？

**Comment by woyeshixiaobai** [comment]
怎么看api报错

**Comment by BaiJiangJie** [comment]
浏览器，右击-检查，看控制台

**Comment by woyeshixiaobai** [comment]
![图片1](https://github.com/jumpserver/jumpserver/assets/41566419/4e51ec77-ebf8-4ded-b46e-2c9f56979313)

**Comment by woyeshixiaobai** [comment]
![图片1](https://github.com/jumpserver/jumpserver/assets/41566419/12f9be5f-4022-41a0-8e7d-b2e11efe82eb)

**Comment by woyeshixiaobai** [comment]
![微信截图_20230803171625](https://github.com/jumpserver/jumpserver/assets/41566419/4ec63e8d-2303-4afa-adee-7f01b04e03ab)

**Comment by BaiJiangJie** [comment]
<img width="1012" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/0d348931-6d66-4b96-b8cc-b631914ce3f2">

**Comment by woyeshixiaobai** [comment]
明天可以远程看
![6](https://github.com/jumpserver/jumpserver/assets/41566419/c6ad32bc-81ce-4849-907c-384462b5a54e)

**Comment by woyeshixiaobai** [comment]
今天有上传了几次，发现控制台无报错，网络处显示都是200，但是传不上去
![8](https://github.com/jumpserver/jumpserver/assets/41566419/e2c75ad9-ad07-4218-b464-c30f2fea4790)

**Comment by BaiJiangJie** [comment]
如果报错的话，肯定有错误信息。

先打开检查再上传文件。

第一个看看上传的页面报什么错，再看看控制台中 400 的 API 报什么错，最后再看 jumpserver.log 的日志。

**Comment by woyeshixiaobai** [comment]
![6](https://github.com/jumpserver/jumpserver/assets/41566419/e96273d1-80f7-4377-9ee8-a2f26fc98a40)
![7](https://github.com/jumpserver/jumpserver/assets/41566419/b55f5bfc-bd03-4a6e-bc77-c1e25e33a053)
![9](https://github.com/jumpserver/jumpserver/assets/41566419/b243b0b0-88f7-48c8-81c8-c4fa551b3219)

**Comment by BaiJiangJie** [comment]
upload 的那个 API 点进去看 Response 的返回。

**Comment by woyeshixiaobai** [comment]
这应该是platform.yml文件缺少字段或者哪个字段不对吧

**Comment by woyeshixiaobai** [comment]
docker logs jms_core|grep error 这样看没有报错，还是说报错不是这样看的

**Comment by woyeshixiaobai** [comment]
![35](https://github.com/jumpserver/jumpserver/assets/41566419/c675da27-e7f8-4fcc-8a5f-dff4b6f7da8c)

**Comment by woyeshixiaobai** [comment]
![08071](https://github.com/jumpserver/jumpserver/assets/41566419/0e2adb24-e5be-4aa6-b5bc-2068435287a3)
![070702](https://github.com/jumpserver/jumpserver/assets/41566419/dfe8960a-e1a1-4f1a-a174-6601c422641b)

**Comment by BaiJiangJie** [comment]
在另一个 issue 里交流吧。
