### ISSUE TITLE
[Bug] ChatGPT对话内容不连贯

### ISSUE THREAD

**Issue by yanxu4780** [jumpserver/jumpserver#11192]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**
Edge 115.0.1901.188 / Chrome 115.0.5790.110

**Bug 描述**
ChatGPT对话无法连贯的进行内容对话

**Bug 重现步骤(有截图更好)**
上下文不连贯
![20230803170044](https://github.com/jumpserver/jumpserver/assets/5827407/b9a16dfb-7c6b-4e99-b3d3-31ac899409d2)

**Comment by BaiJiangJie** [comment]
<img width="666" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/ba7b48bf-244a-4924-840d-190348899608">

ChatGPT 的 API 调用结果就是这样的，每次的回答可能都不太一样。

**Comment by yanxu4780** [comment]
> 小问题，ChatGPT 的 API 标准调用，每次的回答都不太一样。
> 
> 对于连贯不连贯，也正是 ChatGPT 需要优化的地方。
![QQ截图20230804083003](https://github.com/jumpserver/jumpserver/assets/5827407/b420a4c2-4397-4974-9db5-336ba94af433)

![QQ截图20230804082951](https://github.com/jumpserver/jumpserver/assets/5827407/d6ee6999-4c36-488e-8ebd-19b7b07947f9)

用OPENAI自己的Web页面，还是用第三方应用调用API来回答，都不会上下文不连贯。应该不是ChatGPT的问题。

**Comment by yanxu4780** [comment]
![QQ截图20230804084844](https://github.com/jumpserver/jumpserver/assets/5827407/dc145800-79aa-4301-9f20-aca184fb5c85)
![QQ截图20230804084831](https://github.com/jumpserver/jumpserver/assets/5827407/611120b5-f948-4690-9fc1-d15faa119cad)

似乎是默认的模型调用有问题，调用到了GPT3模型上去了，而不是GPT3.5-turbo

**Comment by BaiJiangJie** [comment]
默认调用的就是 GPT3.5-turbo


欢迎提优化：https://github.com/jumpserver/kael
