### ISSUE TITLE
LDAP 匹配到了用户但无法展示在user列表

### ISSUE THREAD

**Issue by luweiv9988** [jumpserver/jumpserver#1119]
[简述你的问题]

##### 使用版本
[Jumpserver版本 1.0.0-2 ]

##### 问题复现步骤
1. [步骤1]
![selection_011](https://user-images.githubusercontent.com/10349332/37884367-3a0d8630-30e2-11e8-9d61-9d0a5662731d.png)

2. [步骤2]
![selection_012](https://user-images.githubusercontent.com/10349332/37884426-7c7294ac-30e2-11e8-8694-e6f1a04d3a62.png)

是有那里配置错了吗？　用户过滤器也有改过其他的，也是现在的状态，无法获取列表
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
匹配到代表配置可用，但不会自动导入进去，用户登录时自动导入

**Comment by ibuler** [comment]
也想做一个自动导入的功能，排期靠后些，欢迎PR
