### ISSUE TITLE
[Question] koko 频繁打印 `send TERMINAL_BINARY message err: websocket: close sent`

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#11196]
**请描述您的问题.**
版本：v2.20.1
当一个连接被关掉时，koko.log 频繁打印如下错误日志，同时会话审计里仍展示为在线会话
[ERRO] Ws[624181d4-bfb9-4713-a835-2bedeb4ec245] send TERMINAL_BINARY message err: websocket: close sent

暂时没有办法升级版本，请问下当前版本这个现象是什么原因导致的呢？

**Comment by lf-zhang** [comment]
额外补充下：查看日志发现使用了 unshare 开启命令行 /bin/unshare --fork --pid --mount-proc /opt/koko/mysql

**Comment by LeeEirc** [comment]
> **请描述您的问题.** 版本：v2.20.1 当一个连接被关掉时，koko.log 频繁打印如下错误日志，同时会话审计里仍展示为在线会话 [ERRO] Ws[624181d4-bfb9-4713-a835-2bedeb4ec245] send TERMINAL_BINARY message err: websocket: close sent
> 
> 暂时没有办法升级版本，请问下当前版本这个现象是什么原因导致的呢？

这种大部分都是因为网络问题，造成的连接异常。v3 已经优化此问题





> 额外补充下：查看日志发现使用了 unshare 开启命令行 /bin/unshare --fork --pid --mount-proc /opt/koko/mysql

这个是连接 MySQL 数据库使用的命令，属于正常日志
