### ISSUE TITLE
[Question] 创建应用无法上传包

### ISSUE THREAD

**Issue by woyeshixiaobai** [jumpserver/jumpserver#11198]
**请描述您的问题.**
控制台无报错，网络处显示都是200，但是传不上去

**Comment by BaiJiangJie** [comment]
看浏览器 API 报错，看 Core 服务的日志。

**Comment by woyeshixiaobai** [comment]
![08071](https://github.com/jumpserver/jumpserver/assets/41566419/879eecc4-2e69-437f-b818-2374b613afb4)
![070702](https://github.com/jumpserver/jumpserver/assets/41566419/bab0fd59-6b3c-457d-b7cc-d3bfa7038344)
这就是全部报错了，到底什么原因，今天能不能解决呢

**Comment by BaiJiangJie** [comment]
下载的哪个应用？

**Comment by woyeshixiaobai** [comment]
下的plsql，添加了自定义platform.yml文件，重新压缩后无法上传，浏览器api报错看上图回复，core服务没有报错

**Comment by woyeshixiaobai** [comment]
manifest.yml 文件是plsql包里自带的
![微信截图_20230808091653](https://github.com/jumpserver/jumpserver/assets/41566419/8576585d-5da9-4f3b-a6fe-d1aacc9bae92)

**Comment by BaiJiangJie** [comment]
直接上传下载的 plsql 呢？先别改 platform.yml

**Comment by woyeshixiaobai** [comment]
直接上传可以，添加plartform.yml就有问题

**Comment by BaiJiangJie** [comment]
<img width="312" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/805803a5-5a22-4b35-b363-2dc2064715df">

应该是你的重新压缩的有问题吧？怎么还嵌套着一层呢？

**Comment by BaiJiangJie** [comment]
你对比一下下载的 zip 包 和 你重新压缩后的 zip 包，目录结构是不是多了一层 plsql。
