### ISSUE TITLE
[Feature] v3.5.1版本 无法修改SFTP路径

### ISSUE THREAD

**Issue by alexjs001** [jumpserver/jumpserver#11197]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/76512139/a4fbfe7d-f7b1-4207-b5b7-d44a8552ebfe)
v3.5.1版本 无法修改SFTP路径

**Comment by pika-FENG** [comment]
新建平台试一下，默认的应该不能改

**Comment by BaiJiangJie** [comment]
对，内置平台不能修改，如果要修改要创建新的平台。
