### ISSUE TITLE
v3.5.2的连接令牌和api key

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11203]
**请描述您的问题.**
请问各位大佬v3的连接令牌是啥有啥用 如何使用 是调用api自动生成的吗没看到可以创建的地方 和apikey通过api操作资产的时候提供的ak有啥区别呢

**Comment by wangmingwang123** [comment]
2 创建令牌[⚓︎](https://docs.jumpserver.org/zh/v3/guide/user/personal_information/connect_token/#2)
创建连接令牌的方式如下：
连接 SSH 协议资产：通过 Web 终端连接 Linux 资产，即可创建令牌信息。
连接 RDP 协议资产：通过 Web 终端连接 RDP 资产，选择连接方式为“RDP 客户端”，即可创建令牌信息。
连接数据库应用：通过 Web 终端连接数据库应用，选择连接方式为“DB Client”，即可创建令牌信息；
通过调用 API 方式创建。
这是文档里看到的 可是我操作通过web终端链接资产之后并没有在个人信息里连接令牌看到生成的连接令牌

**Comment by BaiJiangJie** [comment]
v3 的连接令牌，是连接资产的唯一凭证。v3 版本底层的重构，连接所有类型的资产都使用 token 的方式，都是自动生成的。
