### ISSUE TITLE
[Bug] 终端健康状况检查警告的邮件一直在发送

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#11204]
**JumpServer 版本 v3.4.3 **

**浏览器版本**
chrome  版本 115.0.5790.170（正式版本） （64 位）

**Bug 描述**
离线的终端已经删除，而且告警也关闭了， 终端健康状况检查警告的邮件还一直在发送，如何彻底关闭告警功能。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/24754263/90e79e48-6370-4c6c-8391-e1c572a23a84)
![image](https://github.com/jumpserver/jumpserver/assets/24754263/d65fb2d4-7a35-4cc2-9572-03529a60f457)
![image](https://github.com/jumpserver/jumpserver/assets/24754263/bd9e00b0-bd80-4950-b4ab-75c64f7c12e5)

**Comment by jiangxianliang007** [comment]
而且，告警邮件貌似是通知到 这个邮箱了，都是退信
![image](https://github.com/jumpserver/jumpserver/assets/24754263/577f475a-623d-4e10-b904-3607406d8100)

**Comment by BaiJiangJie** [comment]
正常系统设置里关闭就可以了，有可能是遗留的任务。

再观察一两天看一下。
