### ISSUE TITLE
[Question] v3.4.3 配置 ed25519 算法失败

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#11207]
**请描述您的问题.**
在个人信息，设置SSH 公钥，还不支持ed25519 算法吗？
设置 ed25519 无法登录，用rsa 可以登录。
![image](https://github.com/jumpserver/jumpserver/assets/24754263/b5b4924d-5c02-4740-9755-98b991189b1f)

**Comment by jiangxianliang007** [comment]
看文档说已经支持 ed25519？

**Comment by BaiJiangJie** [comment]
资产账号支持了。

个人信息配置后，登录有报错吗？

**Comment by jiangxianliang007** [comment]
配置的时候没报错，就是登录的时候私钥不能匹配， X  All configured authentication methods failed。

**Comment by BaiJiangJie** [comment]
好的，刚看了一下目前不支持，在 v3.6 中支持。

**Comment by jiangxianliang007** [comment]
v3.6 预计发布时间是？

**Comment by BaiJiangJie** [comment]
08.17

**Comment by BaiJiangJie** [comment]
v3.6 版本已解决。
