### ISSUE TITLE
[Question] 在节点下新增资产后，ssh登录节点的数量统计不变化

### ISSUE THREAD

**Issue by allegrox** [jumpserver/jumpserver#11208]
在节点下新增一个服务器，此节点已经对用户授权，这时在用户的web界面可以看到节点树里面的节点名称后面有资产数量的变化。但是登录ssh后用g命令显示树形，节点名称后数量不变，但是用g后面加节点号命令，可以显示出节点下新增的服务器。请问，如何能同步数据，让ssh登录也能正确显示节点下的资产数量？

**Comment by BaiJiangJie** [comment]
ssh 终端每次登录成功后只刷新一次。

如果有变化，先 s 刷新一下，再 g 显示节点，数量就变过来了。

**Comment by allegrox** [comment]
> ssh 终端每次登录成功后只刷新一次。
> 
> 如果有变化，先 s 刷新一下，再 g 显示节点，数量就变过来了。

s是切换语言，你是说r命令吧，试过，好像不灵光
引申一个问题，如果ssh终端已经登录，管理端收回了一个资产的权限，这时候已登录的终端受影响吗？

**Comment by BaiJiangJie** [comment]
已登录的资产不受影响。

如果没有登录资产，管理员收回权限，再选择连接资产会提示没有权限。
