### ISSUE TITLE
[Bug] 升级v3后，没有saml2关闭入口，导致无法登录 

### ISSUE THREAD

**Issue by silencelog** [jumpserver/jumpserver#11209]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
升级v3之后，原先使用阿里云idaas认证，但是一年到期后saml2因为升级后没有了页面，每次打开页面还是默认走saml2认证，会报错误。导致无法通过账号密码登录。/opt/jumpserver/config/config.txt里面也没有，看了数据库也没有，请问怎么关闭saml2

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.v2.28配置saml2
2.更新v3版本，关闭saml2服务端
3.jumpserver页面打开，就会报错

**Comment by BaiJiangJie** [comment]
``` sh
# 进入 jms_core 容器
docker exec -it jms_core bash

cd apps/

python manage.py shell
```
``` python

from settings.models import *

s = Setting.objects.get(name='AUTH_SAML2')

s.value = False

s.save()
```

退出容器，重启服务。

**Comment by silencelog** [comment]
第二天，又自动开启了saml2。。。
