### ISSUE TITLE
资产IP字段问题

### ISSUE THREAD

**Issue by Nidhoggur1993** [jumpserver/jumpserver#1120]
[简述你的问题]
部分导入的资产，IP字段最前面会有空格，导致无法连接

##### 使用版本
1.0.0

##### 问题复现步骤
1. 批量导入
2. 查看某些资产（连通性测试不通过的），IP字段会有空格
3. 手动删除空格后即可恢复正常

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/12947582/37885453-e122fc70-30e7-11e8-8612-e8c1fed76be0.png)
![2](https://user-images.githubusercontent.com/12947582/37886812-45e85ab2-30f0-11e8-8cb3-027ab4be76d7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Nidhoggur1993** [comment]
Update：
刚查了下数据库，可能是tab缩进的
![image](https://user-images.githubusercontent.com/12947582/37888609-ef2ef572-30fa-11e8-9c59-82f943f5e5ae.png)

**Comment by ibuler** [comment]
fixed
