### ISSUE TITLE
luna不显示主机

### ISSUE THREAD

**Issue by hacker0001** [jumpserver/jumpserver#1121]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本  Version 1.0.0-2 GPLv2]

##### 问题复现步骤
1. [步骤1]
用管理员账号登录jumpserver
2. [步骤2]
打开会话管理-》web终端，跳转至luna后不显示主机

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ssh登录显示吗？如果都不显示就是没有授权

**Comment by hacker0001** [comment]
大神您好：ssh也不显示


hacker.wcq@qq.com
 
发件人： 老广
发送时间： 2018-03-27 11:31
收件人： jumpserver/jumpserver
抄送： hacker0001; Author
主题： Re: [jumpserver/jumpserver] luna不显示主机 (#1121)
ssh登录显示吗？如果都不显示就是没有授权

**Comment by hacker0001** [comment]
请问怎么添加授权

**Comment by ibuler** [comment]
去看文档

**Comment by hacker0001** [comment]
好的，谢谢




hacker.wcq@qq.com
 
发件人： 老广
发送时间： 2018-03-27 11:38
收件人： jumpserver/jumpserver
抄送： hacker0001; Author
主题： Re: [jumpserver/jumpserver] luna不显示主机 (#1121)
去看文档

**Comment by liaoqiArno** [comment]
我也碰到这个问题，但是我的xshell里是显示这台机器的ssh可以登陆的。。
