### ISSUE TITLE
[Question] 前端隐藏api key和连接令牌按钮

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11214]
**请描述您的问题.**
你好，我们部署了jumoserver3.5.2，然后我们希望隐藏下图的按钮
![image](https://github.com/jumpserver/jumpserver/assets/73093158/f669cd33-0549-46e7-8aed-9622b15953f6)
我的操作是如下图：
![image](https://github.com/jumpserver/jumpserver/assets/73093158/4de87343-17a8-4822-a17f-e47e00792b74)
然后复制到了docker里面，没有预期的效果，我应该怎么操作呢，或者是否有现成的功能可以实现这个

**Comment by BaiJiangJie** [comment]
没问题，是修改这里。

**Comment by wangmingwang123** [comment]
可是我们修改后再把文件拷贝到jms_web的/opt/lina覆盖掉 前端还是显示api key和连接令牌按钮

**Comment by BaiJiangJie** [comment]
得重新编译

**Comment by BaiJiangJie** [comment]
如果产品层面不想给用户显示，修改角色权限位就可以。

**Comment by wangmingwang123** [comment]
> 得重新编译

我们是拉取了lina的源码 修改后 yarn build:prod生产了lina文件夹然后拷贝覆盖奥web容器内的 这样也不行嘛

**Comment by wangmingwang123** [comment]
> 如果产品层面不想给用户显示，修改角色权限位就可以。

可是我们是社区版 3.0社区版不支持角色权限位

**Comment by BaiJiangJie** [comment]
好吧，可以考虑买个企业版。
