### ISSUE TITLE
[Feature] 组件按需开启/关闭

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#11218]
**请描述您的需求或者改进建议.**
当前JMS发展很好，且功能很强大，对应组件也是越来越多。
对于一些用户，我可能就只需要Luna（Web Terminal）和Koko（port/2222）
其他的一些比如Magnus（数据库）、Kael（ChatGPT）、Chen（数据库可视化）等组件。
众多组件种有部分是我用不到的，能否通过config.txt配置文件对指定组件的关闭不启用。

**Comment by BaiJiangJie** [comment]
好的，计划 v3.7 版本支持一下。

**Comment by luweijun1992** [comment]
> 好的，计划 v3.7 版本支持一下。

给力，到时候最好说明下各个组件作用及相关关系。
好让大家选择是否需要启动。
比如一些群体只是管理网络设备，确实只需要Web Terminal和Koko就够了，其他组件用不到。

**Comment by BaiJiangJie** [comment]
组件说明在这儿：https://github.com/jumpserver

**Comment by luweijun1992** [comment]
> 好的，计划 v3.7 版本支持一下。

请问刚发布的v3.7支持了吗？好像更新说明没有看到

**Comment by BaiJiangJie** [comment]
发布了，已支持。没有在 Release Note 中添加。

**Comment by luweijun1992** [comment]
> 发布了，v3.7 已支持。没有在 Release Note 中添加。

那如何将对应组件关闭，还麻烦给个资料。
