### ISSUE TITLE
[Bug] 账号推送卡住的问题（300台主机）

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#11225]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**

**Bug 描述**
V3 推送用户，一次性推送多台机器会卡住，我尝试推送了300台Linux server 一开始显示分4批来推送 第一批推送到最后就不Finnish了，就是卡住，没有task OK的结果  第二批也不开始，看起来用户虽然推送到服务器上了但是密码没有保存到jumpserver内，堡垒机配置上无法登陆，我紧急回退到V2版本了 

**Bug 重现步骤(有截图更好)**
1. 创建用户推送流程
2. 选择一个分组（大概200-300台 Linux server）
3. 随机密码 推送

**Comment by BaiJiangJie** [comment]
第一批推送，最后大概卡住有多久了？

提供一下任务执行日志截图。

密码是最后完成后才会保存下来的。（比如第一批完成后会保存一下）

比如只选 50 台，或者 100 台，能正常推送吗？

**Comment by wushengmin** [comment]
因为已经回滚所以目前没有截图，大概卡了半个多小时了。没有尝试分批推送

**Comment by BaiJiangJie** [comment]
好的，这个需要在测试环境复现一下。

**Comment by BaiJiangJie** [comment]
最新版本已优化。
