### ISSUE TITLE
下载大文件异常

### ISSUE THREAD

**Issue by penglongsd** [jumpserver/jumpserver#1122]
[简述你的问题]

jumpserver5.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
sz catalina.tar.gz   文件 624K	catalina.tar.gz
2. [步骤2]

![image](https://user-images.githubusercontent.com/37572795/37957725-42d84976-31e1-11e8-8b64-ccdcbd6e6706.png)

满屏乱码，下载超慢
![image](https://user-images.githubusercontent.com/37572795/37957778-647e9f62-31e1-11e8-8e87-ddc1f91fea4a.png)

请问这个是什么问题题导致的

[注:] 完成后请关闭 issue

**Comment by penglongsd** [comment]
文件下载一会后自动断开，单是文件只下载了一小部分

**Comment by penglongsd** [comment]
目前有什么方法避免这个问题吗？

**Comment by penglongsd** [comment]
可否给些建议

**Comment by liuzheng** [comment]
jumpserver现在不支持该方案，请勿使用该方案

**Comment by ibuler** [comment]
及时直接连服务器sz也有可能出现这个问题

**Comment by penglongsd** [comment]
那通过堡垒机，下载文件有什么其他的方法吗？

**Comment by Spinestars** [comment]
建议采用ftp方式...或者如果使用云,可采用对象存储方式

**Comment by liuzheng** [comment]
ftp我是不会用的，有漏洞，可内网入侵。
使用云的话对使用者要求有点多了，后期会开放上传下载的页面，同时也会有审计相关的功能。
单纯上传下载是没难度的，主要是审计这块要做好

**Comment by penglongsd** [comment]
等待各位大咖，上线上传下载功能，审计是否先可以只记录操作过程，
