### ISSUE TITLE
[Bug] 使用SecureCRT连接堡垒机，提示 Key exchange failed.

### ISSUE THREAD

**Issue by lhs286266503** [jumpserver/jumpserver#11230]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.5.2

**浏览器版本**
SecureCRT window platform

**Bug 描述**
使用SecureCRT window平台版本链接堡垒机，提示
Key exchange failed.
No compatible key exchange method. The server supports these methods: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521

而使用同一个工具连接2.28.6版本堡垒机又正常；

其他情况：iterm2使用ssh登录正常，CRT Mac版本正常，Xshell window版本正常，windterm正常，winSCP不正常；

CRT支持的key change如图
<img width="628" alt="image" src="https://github.com/jumpserver/jumpserver/assets/3786970/33db5418-6fa4-4fdc-b263-f2f74b915f27">

使用nmap得到3.5.2版本的如下
![企业微信截图_2f08444a-1955-4f5b-bcc9-02798881d44b](https://github.com/jumpserver/jumpserver/assets/3786970/552c4e59-85ef-4c33-88fe-c3a7549bdd59)

使用nmap得到2.28.6版本的如下
![企业微信截图_6c802c39-c207-4cf7-824a-21cd56762eb9](https://github.com/jumpserver/jumpserver/assets/3786970/1d8dd46d-f800-440d-87c3-04446d2b7667)

总结：新版没有包含diffie-hellman-group系列的 kex_algorithms

**Comment by LeeEirc** [comment]
有用户提示说 `diffie-hellman-group` 不是安全的算法， Koko 移除了这些不安全的算法。
参考 https://github.com/jumpserver/jumpserver/issues/10460 
另外，SecureCRT 版本应该也支持其他常见的算法吧。

**Comment by lhs286266503** [comment]
原来如此。感谢回复~，只能换其他工具连接了
