### ISSUE TITLE
终端管理的应用用户显示在用户组里面

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#1123]
[简述你的问题]
![qq20180327-172014](https://user-images.githubusercontent.com/24326988/37958458-2c707800-31e3-11e8-91d5-bea682071935.png)

更新里面没有
![qq20180327-172114](https://user-images.githubusercontent.com/24326988/37958505-49268782-31e3-11e8-824c-418b89707a00.png)

##### 使用版本
[Jumpserver1.0.0]

**Comment by ibuler** [comment]
fixed
