### ISSUE TITLE
[Feature] 希望系统工具那里可以支持批量Ping和telnet

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11238]
**请描述您的需求或者改进建议.**
当前3.5版本，“系统工具”那里的ping或telnet只支持单个IP。
当有大量资产想去测试其网络连通性时，这个功能就显得有点鸡肋了。希望能实现批量的功能。

**Comment by BaiJiangJie** [comment]
v3.7 版本支持一下。

**Comment by BaiJiangJie** [comment]
新版本已支持。
