### ISSUE TITLE
[Question] Celery启动成功，但是一直显示离线，请问怎么配置

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#11235]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/106153788/2fd3186a-da43-49c3-952a-62437dab2ed0)

![image](https://github.com/jumpserver/jumpserver/assets/106153788/69ce6740-ee4f-4d77-9d11-6acbb4524633)

**Comment by BaiJiangJie** [comment]
用离线包部署。
