### ISSUE TITLE
[Bug] DB web GUI有些表无法查询，执行错误: Zero date value prohibited

### ISSUE THREAD

**Issue by jibill** [jumpserver/jumpserver#11234]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**
firefox 116.0.1 (64 位)
chrome 115.0.5790.102（正式版本） (arm64)

**Bug 描述**
使用web GUI连接Mysql 5.7数据库，如图为TS库
4张表，只有1张表的某些数据无法查询，并返回`执行错误: Zero date value prohibited`
<img width="1189" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/c727ef27-c396-4bea-901d-afeae5fa9571">
<img width="725" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/196ce439-87b9-46c1-89a3-da18575002bf">

这是同一张表的不同数据，web GUI 正常查询
<img width="1293" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/10ab6602-1b56-4813-97d8-c147d382c135">
这是同一张表的另一个查询，web GUI 无法查询
![image](https://github.com/jumpserver/jumpserver/assets/42427328/22cc91cd-a3cf-4808-a3a9-f779f9f0362e)
这是使用web CLI，都正常查询
![image](https://github.com/jumpserver/jumpserver/assets/42427328/9c871aa4-9962-475a-aa1f-fc8f65125dca)

数据类型为 `datetime`

**Bug 重现步骤(有截图更好)**

**Comment by BaiJiangJie** [comment]
应该是表数据的日期字段值有问题。

**Comment by BaiJiangJie** [comment]
v3.5.4 版本处理一下。

**Comment by jibill** [comment]
好的。多谢

**Comment by BaiJiangJie** [comment]
最新版本已解决。
