### ISSUE TITLE
[Bug] 3.5.2 chatgpt连接后立即断开连接

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11246]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.5.2
**浏览器版本**
edge

**Bug 描述**
![image](https://github.com/jumpserver/jumpserver/assets/73093158/d939ef60-5e34-45ca-bfcb-7e22a9dbd4ac)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
看 kael.log 日志。

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/633e3853-8f2b-437f-a98f-32eb3819ded6)
日志是这个 啥问题

**Comment by BaiJiangJie** [comment]
账号的账单正常吗？
