### ISSUE TITLE
[Bug] 低级管理员提权成为高级管理员

### ISSUE THREAD

**Issue by Xyuncheng** [jumpserver/jumpserver#11248]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**浏览器版本**
chrome

**Bug 描述**
用户 A 在组织 A 中只是一个低权限的管理员（具有邀请用户、查看用户组的权限），用户 A 通过邀请用户这个功能邀请自己加入某组织，这个时候他可以把自己邀请成高权限的管理员。

**Bug 重现步骤(有截图更好)**
1.新建具有邀请用户权限的管理员——测试管理员。
![1691659161172](https://github.com/jumpserver/jumpserver/assets/137035261/04de7f18-57f0-4f27-a47d-58684828a056)

2.用户 A 为测试管理员，在界面上将自己邀请进当前组织。
![1691659553194](https://github.com/jumpserver/jumpserver/assets/137035261/fdf9f42b-bae4-4045-822c-5e153334fd0b)
![1691659574995](https://github.com/jumpserver/jumpserver/assets/137035261/a1f2be8c-7d2a-4bcb-b949-8e770a67b2db)

3.邀请完成之后，用户 A 已经具有组织管理员权限。
![1691659851678](https://github.com/jumpserver/jumpserver/assets/137035261/7a636158-b6cc-4412-b2b4-b87fe026f692)

**Comment by BaiJiangJie** [comment]
明显还有更新用户的权限。

**Comment by BaiJiangJie** [comment]
新版本已优化，不允许自己更新自己的角色。
