### ISSUE TITLE
[Question] 源码部署v3.5.2 在线会话监视、历史会话回放 报404

### ISSUE THREAD

**Issue by cruize3** [jumpserver/jumpserver#11259]
查看Nginx日志，发现在找/opt/luna-3.5.2/luna-v3.5.2/下的monitor和replay目录，实际并没有这两个目录。手动创建并给足权限也没有用。

![截图_选择区域_20230812122628](https://github.com/jumpserver/jumpserver/assets/53335613/509c9b7d-76e5-4e61-af1a-04ca8bdd9e13)

**Comment by wojiushixiaobai** [comment]
nginx 配置有误，自行更改。
```
  # Core data 静态资源
  location /media/replay/ {
    add_header Content-Encoding gzip;
    root /opt/jumpserver-v3.5.3/data/;
  }

```

**Comment by cruize3** [comment]
/media/replay/的配置是这样的
![image](https://github.com/jumpserver/jumpserver/assets/53335613/c4826589-3c79-4286-8f1e-4423808aa45f)
/opt/jumpserver-3.5.2/data/media/下也确实有replay目录
![截图_选择区域_20230814094710](https://github.com/jumpserver/jumpserver/assets/53335613/c4d032bb-41af-4cec-9b7d-ad3283323635)
但是Nginx日志中看是在找/opt/luna-3.5.2/luna/下的replay和monitor
![image](https://github.com/jumpserver/jumpserver/assets/53335613/388df751-1348-4d8e-ae76-fad308ca9d4d)
