### ISSUE TITLE
远程能否提示当前服务器正在被远程,请稍后尝试

### ISSUE THREAD

**Issue by woyeshixiaobai** [jumpserver/jumpserver#11255]
目前用户较多，经常存在远程被顶的情况，能否在远程时提示当前服务器正在被远程并显示远程用户的登录名

**Comment by BaiJiangJie** [comment]
后期版本会考虑再 Web Luna 页面的连接弹窗中，加入某个账号的当前使用人数，作为提示。

计划 v3.7 版本支持。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10587

**Comment by woyeshixiaobai** [comment]
预计什么时候发布v3.7版本

**Comment by BaiJiangJie** [comment]
预计9月份。

**Comment by ibuler** [comment]
已提交到 dev

![image](https://github.com/jumpserver/jumpserver/assets/17382885/c93ca12b-e297-4437-b42a-12f16937bc4f)
