### ISSUE TITLE
[Bug] 镜像存在较多的安全漏洞

### ISSUE THREAD

**Issue by lanss315425** [jumpserver/jumpserver#11253]
**JumpServer 版本 v2.28 **

详情请见一下文档
[jumpserver-koko-v2.28.8-cve.txt](https://github.com/jumpserver/jumpserver/files/12319305/jumpserver-koko-v2.28.8-cve.txt)
[ jumpserver-web-v2.28.8-cve.txt](https://github.com/jumpserver/jumpserver/files/12319306/jumpserver-web-v2.28.8-cve.txt)
[jumpserver-core-v2.28.8-cve.txt](https://github.com/jumpserver/jumpserver/files/12319307/jumpserver-core-v2.28.8-cve.txt)
[jumpserver-redis-6.2-cve.txt](https://github.com/jumpserver/jumpserver/files/12319300/jumpserver-redis-6.2-cve.txt)
[jumpserver-lion-v2.28.8-cve.txt](https://github.com/jumpserver/jumpserver/files/12319302/jumpserver-lion-v2.28.8-cve.txt)
[jumpserver-mariadb-10.6-cve.txt](https://github.com/jumpserver/jumpserver/files/12319303/jumpserver-mariadb-10.6-cve.txt)
[jumpserver-magnus-v2.28.8-cve.txt](https://github.com/jumpserver/jumpserver/files/12319304/jumpserver-magnus-v2.28.8-cve.txt)

**Comment by wojiushixiaobai** [comment]
v2 的最新版本是 [2.28.17](https://github.com/jumpserver/jumpserver/releases/tag/v2.28.17)
镜像都是使用上游的公共镜像，如果你担心安全问题可以通过源码自行部署或者参考 `Dockerfile` 手动构建符合安全要求的镜像。

**Comment by BaiJiangJie** [comment]
基本都是 Linux 上最基本工具的漏洞，比如 curl、vim、xxd 等等。

忽略。

**Comment by lanss315425** [comment]
好的
