### ISSUE TITLE
[Question] User ACL doesn't seem to work properly

### ISSUE THREAD

**Issue by shlee4** [jumpserver/jumpserver#11251]
"Users > User detail > User acl lists" 
User ACL doesn't seem to work properly.

Symtoms )
set IP group to 172.100.100.100/32 ( and acl.Action to "Allow" and Other to "Active" )
but User can log in with the other address 172.100.100.101,  172.100.100.102,  172.100.100.103 ... and so on

Version v2.27.0

**Comment by BaiJiangJie** [comment]
This is normal.

If you don't want users to log in through the 172.100.100.100/32 IP network segment, Action should be set to Deny.

**Comment by shlee4** [comment]
Hello.
Thans your anser
but
if I want to log in from only 172.100.100.100.
what can I set User ACL to?

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by BaiJiangJie** [comment]
<img width="1845" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f264ae8c-1be1-4eb9-b0c7-8d7147de267c">


![2251691744291_ pic](https://github.com/jumpserver/jumpserver/assets/32935519/a1d0f59e-9297-4f7e-b7e7-1b5b52e27c31)

**Comment by BaiJiangJie** [comment]
First step, create a deny all ACL (priority 50) (action deny)

The second step is to create an ACL (priority < 50) that allows the specified network segment to access (action allow)

**Comment by shlee4** [comment]
Thanks your answer.
I'll try it.

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by BaiJiangJie** [comment]
네 천만에요

**Comment by shlee4** [comment]
Hello ~

I tried it as your guide

***@***.***

and Allow IP

***@***.***

I want it logged in with only 172.18.125.58
but it was also logged in with 172.18.125.132

***@***.***



cf)
My Jumpserver version is Version v2.27.0
Your guide version seems to be different from my version.

**Comment by shlee4** [comment]
Hello.
I tried it as your guide.

![image](https://github.com/jumpserver/jumpserver/assets/124868879/959623ee-9653-4f40-95b9-407316b688b7)

![image](https://github.com/jumpserver/jumpserver/assets/124868879/5fca8fb3-ab82-442f-b77f-d274c36915cd)

I set ACL to log in with only 172.18.125.58.
but it was also logged in with other ip address (172.18.125.132) as below

![image](https://github.com/jumpserver/jumpserver/assets/124868879/0e4401d9-368d-4275-bc25-313510c72eab)

cf)
My Jumpserver version is Version v2.27.0
Your guide version seems to be different from my version.

**Comment by shlee4** [comment]
Thank you for your kindly reply !!
