### ISSUE TITLE
[Question] 资产连接windows测试连接报错，实际可以连接

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11269]
**请描述您的问题.**
我们windows资产测试连接不通过 但是登录可以
![image](https://github.com/jumpserver/jumpserver/assets/73093158/5432b1cf-5d39-402c-bfa4-b2904c2f6e0b)
![image](https://github.com/jumpserver/jumpserver/assets/73093158/d8349877-19c5-4fa9-ba47-7e6a0ea7010b)
看到之前的issue说是测试连接是22端口 登录是3389我配置了22可还是不行

**Comment by BaiJiangJie** [comment]
应该是 windows openssh 配置的有问题

**Comment by wangmingwang123** [comment]
> 应该是 windows openssh 配置的有问题

意识是说windows还需要手动安装oepnssh嘛 我看3.0是通过winrm测试连接的吧

**Comment by BaiJiangJie** [comment]
winrm 的话需要在平台中修改探活方式。

**Comment by wangmingwang123** [comment]
> winrm 的话需要在平台中修改探活方式。

那openssh是需要win资产上手动配置ssh吗 没有像linux的直接测试的吗

**Comment by BaiJiangJie** [comment]
openssh 的需要配置，winrm 的不需要。
