### ISSUE TITLE
[Question] MFA开启后，web端登录失败，ssh端可以正常登录

### ISSUE THREAD

**Issue by yangyang122** [jumpserver/jumpserver#11263]
**请描述您的问题.**
版本： jumper v2.17.0
ssh登录，正常，可以输入动态验证口令，正常登录登出
web端 密码+动态口令，登录失败
![图片](https://github.com/jumpserver/jumpserver/assets/12775735/b947598f-e50d-4ce6-890c-725e50ce95e8)
web账号登录提示
![图片](https://github.com/jumpserver/jumpserver/assets/12775735/78bc9524-a3c4-41b2-a776-0e0150862112)
能否从后台服务器端，把全局的MFA功能关闭掉呢

起初按照大佬指示，服务器时间同步过

**Comment by yangyang122** [comment]
ssh端，输入动态验证码口令，可以显示服务器列表，正常登录，目前web端admin无法登录。无法管理

**Comment by yangyang122** [comment]
第一步 输入账号+密码，这个“动态验证码”不输入. 感觉这个动态验证码框有些多余，不知道怎么去掉
![图片](https://github.com/jumpserver/jumpserver/assets/12775735/2871c4e4-7c77-4ea2-b7d7-cd5e0efe14b8)
点击登录，输入MFA验证码，可以正常登录
![图片](https://github.com/jumpserver/jumpserver/assets/12775735/0fe185b4-a2da-420a-bae6-2a659ca6cd9a)

**Comment by yangyang122** [comment]
按照配置重新配置开关，解决了

**Comment by eicesoft** [comment]
> 按照配置重新配置开关，解决了

怎么修改配置啊. 我也被锁定了.
