### ISSUE TITLE
web中命令记录文件太大打开卡死

### ISSUE THREAD

**Issue by penglongsd** [jumpserver/jumpserver#1127]
[简述你的问题]
jumpserver  0.5.0

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/37572795/38007962-ba91588e-327e-11e8-9756-5094343fce39.png)
进入到命令记录中，只能看到当前显示出这些，这个页面已经卡死

![image](https://user-images.githubusercontent.com/37572795/38007991-e18dca6c-327e-11e8-93cf-09f35a181550.png)
服务器中记录的日志已经有1G了，是不是当前页面显示全部导致卡死，有分页功能吗？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
和这个日志没关系，和数据库里存储的有关系，这个bug比较严重，请方便时候 qq我，teamview查看一下

**Comment by penglongsd** [comment]
你好 我还没有加你的QQ，方便的话加我或告诉我下您的QQ，我的是280246775，我的邮箱是；280246775@qq.com，谢谢

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/38012236-31f504fc-3293-11e8-8e7a-b68e63866a8c.png)

**Comment by penglongsd** [comment]
这个是我那出问题了那？

**Comment by penglongsd** [comment]
![image](https://user-images.githubusercontent.com/37572795/38012764-4d3f6e80-3295-11e8-93fe-40686578bb72.png)
这个是我的“历史会话” 选项中的日志，已经达到191行了，也没有出现分页的选项。
在 会话管理中的-几个选项都出现了没有分页的情况。

**Comment by penglongsd** [comment]
问题已解决；
有余没有启动分页功能  /opt/jumpserver/jms start
