### ISSUE TITLE
[Question] 请问如何在 playbook 中使用资产特定的变量

### ISSUE THREAD

**Issue by linshaoyong** [jumpserver/jumpserver#11283]
我之前只用 ansible，在 inventory 里每个 host 有自己的一些变量，比如 kafka 集群里的 host 有各自 broker_id。
最近尝试使用 JumpServer v3.5.3，打算把 playbook 迁移到 JumpServer 里，不懂 inventory 里的变量怎么处理。
尝试在资产的标签里设置，发现 playbook 不能获取资产的标签。
如果在 playbook 里创建 vars 太不通用，playbook 对应的资产上下线比较频繁，每次执行 playbook 都要 人工编辑 host_vars 麻烦且容易出错。

**Comment by BaiJiangJie** [comment]
目前不支持在资产级别定义变量，只能在原生的 playbook 中写 vars。

**Comment by seaurching** [comment]
> 目前不支持在资产级别定义变量，只能在原生的 playbook 中写 vars。

通过vars 目录下创建 all.yaml定义变量也不行吗？
