### ISSUE TITLE
[Feature] 资产添加账号密码是明文传输

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#11288]
**请描述您的需求或者改进建议.**
v3.5目前为资产创建账号的时候发现密码还是明文传输，如果有人抓包就非常不安全，这块能加密吗
![image](https://github.com/jumpserver/jumpserver/assets/66759501/5174ebf9-7a00-4978-9c99-2b6284b5a266)

**Comment by BaiJiangJie** [comment]
好的，下个版本会处理一下。

v3.6 和 v3.5.5。
