### ISSUE TITLE
[Question] 远程应用部署不生效

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [jumpserver/jumpserver#11289]
**请描述您的问题.**
应用上传后，点击部署，任务框显示都执行成功，但是在应用列表里查看还是未部署状态，而且发布机上也没有对应的applet文件，请问是什么原因啊？

**Comment by wojiushixiaobai** [comment]
能截图看看吗？以及是什么应用？

**Comment by zhanwonichengshizhu** [comment]
Firefox应用
<img width="950" alt="image" src="https://github.com/jumpserver/jumpserver/assets/102785193/b14b265c-3a38-4b60-98f0-f3ea843743f6">
<img width="1128" alt="image" src="https://github.com/jumpserver/jumpserver/assets/102785193/ec568a66-2e21-4b2d-a604-fe5f46d21f95">
<img width="818" alt="image" src="https://github.com/jumpserver/jumpserver/assets/102785193/adf92008-96ee-46bf-949c-7321741c56e8">

**Comment by Halo1236** [comment]
@zhanwonichengshizhu 请下载最[新版firefox应用](https://apps.fit2cloud.com/jumpserver/firefox)，问题已经解决
