### ISSUE TITLE
[Question] 录入了windows server 2022的资产在物理机和远程桌面之间不能完成文本的复制粘贴。

### ISSUE THREAD

**Issue by EnergeticWong** [jumpserver/jumpserver#11284]
录入了windows server 2022的资产在物理机和远程桌面之间不能完成文本的复制粘贴。
授权时给予了复制粘贴权限。

**Comment by EnergeticWong** [comment]
请问是我的操作问题吗？

**Comment by BaiJiangJie** [comment]
<img width="2047" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/93727d4f-b865-46f5-b452-62b8c0a561b5">

打开剪切板试一下。正常应该是可以复制粘贴的。

**Comment by jstbw** [comment]
他们企业版支持原生rdp，可以直接复制粘贴

**Comment by EnergeticWong** [comment]
是我操作的问题，没看到右边的设置按钮。
