### ISSUE TITLE
Jumpserver版本 0.3.2上传文件500error

### ISSUE THREAD

**Issue by Ishelp** [jumpserver/jumpserver#1128]
[简述你的问题]

##### 使用版本
Jumpserver版本 0.3.2 

##### 问题复现步骤
1. 点击上传文件会提示下图的错误
2. 文件内容是几百k的zip文件

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/29914031/38011144-cc308172-328e-11e8-87c9-33b1505ed535.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
0.3.2的版本暂不提供支持了
