### ISSUE TITLE
[bug] ` 是被禁止的

### ISSUE THREAD

**Issue by bluemiaomiao** [jumpserver/jumpserver#11296]
**JumpServer 版本( v2.28 之前的版本不再支持 )** v2.28.7

**浏览器版本** Chrome 最新版

**Bug 描述**

```shell
uname -r
` 是被禁止的。
```

**Bug 重现步骤(有截图更好)**
1. 执行一个命令，通过上箭头执行历史命令 uname -r，其他命令也是
2. 按下 Enter 键执行
3. 返回错误

**Comment by BaiJiangJie** [comment]
看看命令过滤器是怎么配置的。
