### ISSUE TITLE
[Feature] Web资产使用代理访问

### ISSUE THREAD

**Issue by WeiYingZhe** [jumpserver/jumpserver#11290]
应用服务器所在段无法访问某些Web资源，需要用其他的段进行访问，能否可以设置代理进行访问吗

**Comment by BaiJiangJie** [comment]
v3.6 版本计划在应用发布机上增加网域的功能，这样发布机就可以放大其他网段了（Web 资源所在的网段）。
应该是可以解决问题的。

但是因为发布机在系统组织里，发布机的网域需要在系统组织中进行创建，但是社区版没有组织功能，所以会放到企业版中。

**Comment by WeiYingZhe** [comment]
好的，感谢

**Comment by ryswork1993** [comment]
> 

目前jumpserver堡垒机的网段要和应用发布机的网段一致才行吗

**Comment by WeiYingZhe** [comment]
> v3.6版本计划在应用发布机上增加网域的功能，这样发布机就可以放到其他网段了（Web资源所在的网段），这样应该是可以解决问题的。
> 
> 但是因为发布机在系统组织里，发布机的网域需要在系统组织中进行创建，但是社区版没有组织功能，所以会放到企业版中。

可以跟chatgpt那要使用http代理吗

**Comment by BaiJiangJie** [comment]
发布机和其他普通资产走的网域网关一样。

Web 资产本身暂时不考虑使用 http 代理。

**Comment by BaiJiangJie** [comment]
> > 
> 
> 目前jumpserver堡垒机的网段要和应用发布机的网段一致才行吗

目前是的。

**Comment by ryswork1993** [comment]
> > > 
> > 
> > 
> > 目前jumpserver堡垒机的网段要和应用发布机的网段一致才行吗
> 
> 目前是的。

我本来想在另一个机房再部署一个发布机和server不同网段，两个发布机做主备，愿望落空了

**Comment by BaiJiangJie** [comment]
v3.6 版本支持了发布机通过网域进行连接。
