### ISSUE TITLE
[Feature] 希望通过客户端直连MySQL数据库时支持通过 jumpserver平台用户密码认证

### ISSUE THREAD

**Issue by GuryYu** [jumpserver/jumpserver#11294]
**请描述您的需求或者改进建议.**
主要对用户的访问做日志审计和权限控制，不需要每次动态账户密码。当前的方式对连接较多的数据库资产操作比较繁琐

使用方式类似 SSH ⼯具直连资产，通过用户名标识访问的账户、访问账户、资产ID

用户名：```jumpserverUsername@systemUsername@AssetID```
密码：```jumpserverUserPassword```

**Comment by BaiJiangJie** [comment]
目前直连式通过 Token 的方式连接的，默认 Token 是一次性的，所以每次连接需要创建新的 Token。

你可以设置 Token 允许复用，这样每次连接时直接使用就行了。

**Comment by GuryYu** [comment]
Token 允许复用能部分缓解这个问题，但是每个数据库首次连接仍然需要手动获取一次token
另外允许复用token也会降低原本临时访问token的安全性。

希望在系统中能够设置数据库是否允许使用平台账户认证连接，开启情况下用户只需知道资源名称，+自己的账户密码就可以连接了
