### ISSUE TITLE
1.0邮件无法发送，使用1.0的大神们，求指教啊

### ISSUE THREAD

**Issue by fortyhub** [jumpserver/jumpserver#1129]
[简述你的问题]
在web页面的系统设置里面配置好了邮件，点测试连接成功。新建用户时,显示添加成功，logs里面也有：[signals_handler INFO]    - Sending welcome mail ...   但是，没有收到邮件。点击重置密码，提示重置成功，log里面可以看到有邮件内容的日志，但是也收不到邮件。
##### 使用版本
Jumpserver版本 1.0
##### 具体表现[截图可能会更好些,最好能截全]
<img width="634" alt="default" src="https://user-images.githubusercontent.com/20607447/38015938-06abd728-32a0-11e8-92a8-8459a28e4824.png">

**Comment by fortyhub** [comment]
下面有个类似的问题，说是启动加  all  参数就可以，但是我本来就是加all启动的......

**Comment by penglongsd** [comment]
看看你启动  python run_server.py all    python run_server.py    jms start all  ，都启动了吗？ 我之前也出现过同样的问题，重启几次之后就好了，没找到具体原因

**Comment by fortyhub** [comment]
重启了无数遍了，就只能在日志里看到邮件内容，并没有发送到邮箱。

**Comment by zhaixg** [comment]
我在日志中看到如下报错内容：

2018-05-03 20:06:46 [tasks ERROR] Sending mail error: please run connect() first
2018-05-03 20:08:48 [utils DEBUG]
    您好 xxx:
    </br>
    请点击下面链接重置密码， 如果不是您申请的，请关注账号安全
    </br>
    <a href="http://localhost/users/password/reset?token=...">请点击这里设置密码 </a>
    </br>
    这个链接有效期1小时, 超过时间您可以<a href="http://localhost/users/password/forgot?email=xxx@xxx.com">重新申请</a>

    </br>
    ---

    </br>
    <a href="http://localhost/users/login">直接登录</a>

    </br>

2018-05-03 20:08:48 [tasks ERROR] Sending mail error: please run connect() first

**Comment by MaloneQQ** [comment]
jumpserver发送邮件任务默认会加入Celery任务队列中，通常Celery队列任务过多导致发送邮件任务无法执行：
方法一：清除celery队列任务
$ source /opt/py3/bin/activate
$ cd /opt/jumpserver/apps
$ python manage.py shell
$ from celery.task.control import discard_all
$ discard_all()
$ exit()
$ cd /opt/jumpserver
$ ./jms restart celery

方法二：取消邮件的异步发送功能
vim /opt/jumpserver/apps/users/utils.py
修改以下三个方法中的发送邮件方法
send_user_created_mail(user)
send_reset_password_mail(user)
send_reset_ssh_key_mail(user)
去掉.delay
# send_mail_async.delay(subject, message, recipient_list, html_message=message)
send_mail_async(subject, message, recipient_list, html_message=message)

我的问题通过以上方法解决，希望可以解决你遇到的问题。
