### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HongLiQin** [jumpserver/jumpserver#11304]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.5.2

**浏览器版本**

firefox 116.0.2 (64 位)
**Bug 描述**
api doc  创建hosts描写错误，导致 500

**Bug 重现步骤(有截图更好)**
1.目前自带的文档如下图：
![图片](https://github.com/jumpserver/jumpserver/assets/98111146/f3533e2a-d5f2-45de-b3e9-847a9ce9d664)

2.查询现有节点的信息
![图片](https://github.com/jumpserver/jumpserver/assets/98111146/c37ecf28-fa0c-4824-8c8b-71961cb133b4)

3.结论
实际上一个字典，而文档写的还是string，有问题

**Comment by ibuler** [comment]
创建时写 id 就可以，返回时数据更加丰富

**Comment by HongLiQin** [comment]
UUID的生成函数是什么呢
