### ISSUE TITLE
[Bug] MySQL实例通过网域测试连接失败

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#11303]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.3

**浏览器版本**
Chrome 版本 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
MySQL实例配置网域，测试连接失败，实际通过web终端可连接

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/16077203/a406551e-c857-49fc-86fe-dfe677d264aa)
![image](https://github.com/jumpserver/jumpserver/assets/16077203/2df8a175-b7fb-4fcb-9092-8ef58eb874cf)

**Comment by slooring** [comment]
同样的问题，网关可以连接。

![image](https://github.com/jumpserver/jumpserver/assets/7947986/889fd56c-fd8e-4db4-8eb9-b11fce0f2134)

![image](https://github.com/jumpserver/jumpserver/assets/7947986/8817762a-4168-4385-99a3-2782f7369215)

**Comment by slooring** [comment]
补充截图

![image](https://github.com/jumpserver/jumpserver/assets/7947986/23e60ab8-813b-41b5-b84c-a18af5a91481)

**Comment by slooring** [comment]
网关配置ssh密钥连接，在网关页面无法连接，在web终端可以连接

版本: v3.6.2

![image](https://github.com/jumpserver/jumpserver/assets/7947986/7116b66f-d17a-4b9e-824d-1ef91bc6a61d)

**Comment by BaiJiangJie** [comment]
新版本已支持。
