### ISSUE TITLE
启动jumpserver 1.0时，int()报base 10错误

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1130]
[简述你的问题]
安装之后每次启动都报这个错误，coco启动直接报500错误
##### 使用版本
1.0.0
##### 问题复现步骤
按照详细部署的步骤做的，不过python使用的是ius源上的python36u-3.6.4-1.ius.centos7.x86_64，没用虚拟环境

##### 具体表现[截图可能会更好些,最好能截全]
jumpserver：python3  run_server.py  all
![image](https://user-images.githubusercontent.com/26393744/38016719-76856e5e-32a2-11e8-91ba-391a6f78859f.png)
coco：python3  run_server.py
![image](https://user-images.githubusercontent.com/26393744/38016934-34faff5c-32a3-11e8-82bb-9ee6f3ba99d3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
redis的端口

**Comment by yaoluoye** [comment]
端口配置没问题，原始文件复制过来之后没有改
![image](https://user-images.githubusercontent.com/26393744/38069786-c7c3c16e-334a-11e8-8834-ce16e2489a36.png)

**Comment by yaoluoye** [comment]
折腾了几天，终于搞清楚了，redis密码中不能有逗号
