### ISSUE TITLE
[Bug] 远程应用-初始化部署失败-找不到pip_packages.zip

### ISSUE THREAD

**Issue by casualfish** [jumpserver/jumpserver#11308]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3 docker版本， repo：jumpserver/jms_all:latest

**浏览器版本**
chrome 版本 116.0.5845.97（正式版本） （64 位）

**Bug 描述**
远程应用，初始化部署失败，提示找不到对应的pip_package.zip，docker容器内也没有该文件

**Bug 重现步骤(有截图更好)**
1. 完成远程应用发布机创建
2. 步骤执行的报错信息如下（xxx.com为堡垒机域名，确定可以访问）：
PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [windows发布机]

TASK [Install RDS-RD-Server (RDS)] *********************************************
ok: [windows发布机]

TASK [Stop Tinker before install (jumpserver)] *********************************
ok: [windows发布机]

TASK [Stop Tinkerd before install (jumpserver)] ********************************
ok: [windows发布机]

TASK [Download JumpServer Tinker installer (jumpserver)] ***********************
ok: [windows发布机]

TASK [Install JumpServer Tinker (jumpserver)] **********************************
changed: [windows发布机]

TASK [Set Tinkerd on the global system path (jumpserver)] **********************
ok: [windows发布机]

TASK [Download python-3.10.8] **************************************************
ok: [windows发布机]

TASK [Install the python-3.10.8] ***********************************************
changed: [windows发布机]

TASK [Check pip command exists] ************************************************
ok: [windows发布机]

TASK [Reboot if installing requires it] ****************************************
skipping: [windows发布机]

TASK [Set RDS LicenseServer (regedit)] *****************************************
skipping: [windows发布机]

TASK [Set RDS LicensingMode (regedit)] *****************************************
skipping: [windows发布机]

TASK [Set RDS fSingleSessionPerUser (regedit)] *********************************
skipping: [windows发布机]

TASK [Set RDS MaxDisconnectionTime (regedit)] **********************************
ok: [windows发布机]

TASK [Set RDS RemoteAppLogoffTimeLimit (regedit)] ******************************
ok: [windows发布机]

TASK [Download pip packages] ***************************************************
fatal: [windows发布机]: FAILED! => {"changed": false, "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip_packages.zip", "elapsed": 0.031249, "msg": "Error downloading 'https://xxx.com/download/applets/pip_packages.zip' to 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip_packages.zip': The remote server returned an error: (404) Not Found.", "status_code": 404, "url": "https://xxx.com/download/applets/pip_packages.zip"}

PLAY RECAP *********************************************************************
windows发布机                 : ok=12   changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
Task terminal.tasks.run_applet_host_deployment[a06d46f3-291c-48b2-96e0-3c10705e2059] succeeded in 66.83736037719063s: None

**Comment by casualfish** [comment]
从/opt/jumpserver/apps/terminal/automations/deploy_applet_host/playbook.yml 来看，下载了pip_packages.zip，这个压缩包能否提供一下下载方式，或者提供对应的requirements.txt。

`    - name: Download pip packages
      ansible.windows.win_get_url:
        url: "{{ APPLET_DOWNLOAD_HOST }}/download/applets/pip_packages.zip"
        dest: "{{ ansible_env.TEMP }}\\pip_packages.zip"
        validate_certs: "{{ not IGNORE_VERIFY_CERTS }}"
`

**Comment by wojiushixiaobai** [comment]
下个版本修复

**Comment by QYG2297248353** [comment]
@wojiushixiaobai 
![image](https://github.com/jumpserver/jumpserver/assets/56836951/cd04c84e-548e-4a5a-b745-3617403a7ce9)
相同的问题，如何解决

**Comment by QYG2297248353** [comment]
1Panel 3.10.8 All In One

![image](https://github.com/jumpserver/jumpserver/assets/56836951/348d47fd-d02c-443e-bcb9-e0cd1ed26178)
