### ISSUE TITLE
jumpserver ssh登录其他主机时不需要显示密码登录方式

### ISSUE THREAD

**Issue by kissingtiger** [jumpserver/jumpserver#11314]
版本：v3.5.3
问题：如何去掉密码登录的方式
<img width="1034" alt="image" src="https://github.com/jumpserver/jumpserver/assets/18210209/83ed2904-6aec-4b4f-b0c7-c4fb8c588d49">

**Comment by BaiJiangJie** [comment]
目前没有办法控制。

**Comment by kissingtiger** [comment]
我是从v2.21升级到3.5.3，才出现password认证方式，原v2.21版本是没有使用password认证方式的
