### ISSUE TITLE
[Bug] Chen组件在执行ALTER TABLE 的DDL命令时，会报错（oracle）

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#11315]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.5.3

**浏览器版本**

**Bug 描述**
情况1：使用oracle进行Web GUI可视化命令时，当使用ALTER TABLE 语句添加一个字段时，会报错：“执行错误: ORA-01735: 无效的 ALTER TABLE 选型”的错误。sql完整命令见下面bug截图1。（mysql能正常执行该命令）
情况2：以情况1为基础，如果数据集包含GBK数据集时，执行相同的sql语句，会报错：“执行错误: ORA-00911: 无效字符”的错误。sql完整命令见下面bug截图2。
情况3：Chen组件新建查询后，如果隔几分钟不去操作这个页面，就无法再执行sql命令了，点击执行按钮，没任何反应。

**Bug截图**
1.
![1692251087932](https://github.com/jumpserver/jumpserver/assets/47737772/45eab39e-7f74-467a-8fcb-b37039d66da4)

2.
![c6081d3bf0b92a1d02dc9b44717e51a](https://github.com/jumpserver/jumpserver/assets/47737772/9f8cf705-5cbf-4a8e-956c-e68301aaa16b)

3.

**Comment by jym503558564** [comment]
在用户的环境可复现，已提到tapd上，附上环境信息了。
