### ISSUE TITLE
[Question] 是否支持批量文件推送

### ISSUE THREAD

**Issue by Masterlovsky** [jumpserver/jumpserver#11327]
有一个需求是需要堡垒机像下面的终端主机发送软件的安装包，然后使用远程脚本运行的方式完成一键部署。
但是没有找到可以批量发送文件的地方，现在是只能连到某一个sftp然后发送文件过去吧

**Comment by Masterlovsky** [comment]
> 我觉得这个提议不错，不过目前还不支持，将来会考虑。

感谢反馈，目前自己用python的paramiko库做了简单的脚本实现，期待官方支持！

**Comment by jym503558564** [comment]
v3.10.0已支持，请升级进行测试。如有其他问题，可再次打开Issues.
