### ISSUE TITLE
[Question] v3.5.3 更新到 v3.6.0 后, web登陆页打不开如何排查问题?

### ISSUE THREAD

**Issue by zeng202211** [jumpserver/jumpserver#11330]
**请描述您的问题.**
升级后登陆页打不开, 

**报错信息**
请求 URL:
https://jumpserver.xxx.org:65443/api/v1/settings/public/open/
请求方法:
GET
状态代码:
400
远程地址:
127.0.0.1:8889
引用者策略:
strict-origin-when-cross-origin

**Comment by zeng202211** [comment]
配置 DOMAINS= 参数影响导致

**Comment by kingsmile16** [comment]
升到最新3.6.0同样的问题，登陆页报400

**Comment by kingsmile16** [comment]
> 配置 DOMAINS= 参数影响导致

@zeng202211 老哥，请问哪里的domain配置

**Comment by BaiJiangJie** [comment]
配置文件里。
