### ISSUE TITLE
[Bug]  升级3.6 页面出错

### ISSUE THREAD

**Issue by biliivan** [jumpserver/jumpserver#11332]
**JumpServer 版本( v3.6 )**

**浏览器版本**

**Bug 描述**
升级3.6版本后，页面无法开启，提示:

禁止访问 (403)
CSRF验证失败. 请求被中断.

更多可用信息请设置选项DEBUG＝True。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by biliivan** [comment]
[root@localhost jumpserver-installer-v3.6.0]# ./jmsctl.sh status
NAME                IMAGE                      COMMAND                  SERVICE             CREATED             STATUS                   PORTS
jms_celery          jumpserver/core:v3.6.0     "./entrypoint.sh sta…"   celery              20 minutes ago      Up 4 minutes (healthy)   8080/tcp
jms_chen            jumpserver/chen:v3.6.0     "./entrypoint.sh"        chen                20 minutes ago      Up 4 minutes (healthy)   8082/tcp
jms_core            jumpserver/core:v3.6.0     "./entrypoint.sh sta…"   core                20 minutes ago      Up 4 minutes (healthy)   8080/tcp
jms_kael            jumpserver/kael:v3.6.0     "./entrypoint.sh"        kael                20 minutes ago      Up 4 minutes (healthy)   8083/tcp
jms_koko            jumpserver/koko:v3.6.0     "./entrypoint.sh"        koko                20 minutes ago      Up 4 minutes (healthy)   0.0.0.0:2222->2222/tcp, :::2222->2222/tcp, 5000/tcp
jms_lion            jumpserver/lion:v3.6.0     "./entrypoint.sh"        lion                20 minutes ago      Up 4 minutes (healthy)   4822/tcp, 8081/tcp
jms_magnus          jumpserver/magnus:v3.6.0   "./entrypoint.sh"        magnus              20 minutes ago      Up 4 minutes (healthy)   0.0.0.0:33061-33062->33061-33062/tcp, :::33061-33062->33061-33062/tcp, 0.0.0.0:63790->63790/tcp, :::63790->63790/tcp
jms_mysql           jumpserver/mariadb:10.6    "docker-entrypoint.s…"   mysql               5 days ago          Up 4 minutes (healthy)   3306/tcp
jms_redis           jumpserver/redis:6.2       "docker-entrypoint.s…"   redis               5 days ago          Up 4 minutes (healthy)   6379/tcp
jms_web             jumpserver/web:v3.6.0      "/docker-entrypoint.…"   web                 20 minutes ago      Up 4 minutes (healthy)   80/tcp, 0.0.0.0:9901->9901/tcp, :::9901->9901/tcp
![360截图20230818113102677](https://github.com/jumpserver/jumpserver/assets/103026005/02adca2b-7e33-4ad5-b420-2e74b90115ec)

**Comment by ryswork1993** [comment]
> 
我也是打不开web
都是急性子，出版本就升级，哈哈

**Comment by ibuler** [comment]
有个升级说明：https://github.com/jumpserver/jumpserver/releases

**Comment by kingsmile16** [comment]
缺少domain配置，添加跨域请求：
![image](https://github.com/jumpserver/jumpserver/assets/29245763/5f40f68c-1137-4f31-badc-fc4dc5561cb1)

**Comment by biliivan** [comment]
> 缺少domain配置，添加跨域请求： ![image](https://user-images.githubusercontent.com/29245763/261517186-5f40f68c-1137-4f31-badc-fc4dc5561cb1.png)

 按要求增加过了，问题还是一样

**Comment by ibuler** [comment]
> > 
> 
> 我也是打不开web 都是急性子，出版本就升级，哈哈

抱歉哈

**Comment by ibuler** [comment]
> 

贴出你的配置

**Comment by biliivan** [comment]
> > 
> 
> 贴出你的配置

# Core Session 定义,
# SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期,
# SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
#
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=True

# 可信任 DOMAINS 定义,
# 定义可信任的访问 IP, 请根据实际情况修改, 如果是公网 IP 请改成对应的公网 IP,
# DOMAINS="demo.jumpserver.org"
# DOMAINS="172.17.200.191"
# DOMAINS="demo.jumpserver.org,172.17.200.191"
DOMAINS="192.168.1.224"

# Lion 开启字体平滑, 优化体验
#

**Comment by ibuler** [comment]
DOMAINS="demo.jumpserver.org,172.17.200.191"

这个要写你浏览器中的，并且只能写一行，后面的会覆盖前面的

**Comment by biliivan** [comment]
#




> DOMAINS="demo.jumpserver.org,172.17.200.191"
> 
> 这个要写你浏览器中的，并且只能写一行，后面的会覆盖前面的

没呢，这几行都是#注释掉了，刚回贴时给处理掉了，你确定是这个里设置的原因是吗，我再找找原因

**Comment by ryswork1993** [comment]
> > DOMAINS="demo.jumpserver.org,172.17.200.191"
> > 这个要写你浏览器中的，并且只能写一行，后面的会覆盖前面的
> 
> 没呢，这几行都是#注释掉了，刚回贴时给处理掉了，你确定是这个里设置的原因是吗，我再找找原因

是这个原因，我已经解决了  DOMAINS="demo.jumpserver.org,172.17.200.191"  这个里边换成你自己的域名或者ip，如果有端口号要加上

**Comment by zeng202211** [comment]
登陆页倒是能打开, MFA认证跳转的页面就不行. 
不能配置 *

**Comment by zeng202211** [comment]
带上端口号才行 ... ...

**Comment by biliivan** [comment]
谢谢大家，已经查到原因了，原来配置文件底下系统安装默认给多加了一行domain 但没给配置端口号

**Comment by vc8426** [comment]
方便把修改的地方展示一下吗,按上面的更改了域名和ip还是无法访问

**Comment by kingsmile16** [comment]
如果出现重复配置，取最后一行
![1692347582928](https://github.com/jumpserver/jumpserver/assets/29245763/60a128ff-8485-41f5-a421-47e872fd28e8)
xxxx --->端口号，格式如下：
`DOMAINS="jps.domain.com,jps.domain.com:xxxx"`

**Comment by kingsmile16** [comment]
> DOMAINS="192.168.0.5,192.168.0.5:80" 我就是这么配置的,但是就是不行,加不加端口都打不开

确保jms各组件服务是否正常running  `jmsctl.sh status`
如果OK，F12打开调试模式看看，哪里出问题了

**Comment by saszhuqing** [comment]
> DOMAINS="192.168.0.5,192.168.0.5:80" 我就是这么配置的,但是就是不行,加不加端口都打不开
看官方文档示例，端口号是必须的
你写这个试试看 DOMAINS="192.168.0.5:80"
![image](https://github.com/jumpserver/jumpserver/assets/32380085/20cb329e-13c9-48af-b141-fccbbdfa788a)

**Comment by BaiJiangJie** [comment]
v3.6.1 解决了，不再强制要求配置 DOMAINS 字段。

大家升级到最新版本试试。
