### ISSUE TITLE
CSRF验证失败. 请求被中断.[Question] 

### ISSUE THREAD

**Issue by lujay** [jumpserver/jumpserver#11339]
**请描述您的问题.**
版本  3.6.0
全新安装
配置domains如下

![image](https://github.com/jumpserver/jumpserver/assets/6263244/bcaa2343-40b8-4d20-8ddc-51dfe3b7e4b0)
访问如下
![image](https://github.com/jumpserver/jumpserver/assets/6263244/0f1af5ec-0616-4196-a39e-8f1f432c60a1)
![W0}%HBD( KMCXO Q8K~ZEU](https://github.com/jumpserver/jumpserver/assets/6263244/780a7d62-3f92-4e21-b375-54c51651954c)
没配置domains，登录页打不开400， 配置domains后， 能打开登录页，输入用户名密码之后  报错 403

**Comment by ibuler** [comment]
DOMAINS 上需要有访问的端口

**Comment by zeng202211** [comment]
DOMAINS="mlbhg.asuscomm.cn:4480"

**Comment by lujay** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/6263244/6b6c4dec-7163-4991-b76a-bf6d5c5ce8b6)
已解决，感谢各位
