### ISSUE TITLE
[Feature] 历史版本清理

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#11334]
**请描述您的需求或者改进建议.**
通过 docker image ls 会发现很多历史版本，因为升级过很多次
jumpserver能不能安装安装时提供清理历史版本的功能，或者在命jsmctl 加入清理历史版本功能

**Comment by wojiushixiaobai** [comment]
升级时默认会清理旧版本镜像，你也可以手动清理

**Comment by saszhuqing** [comment]
在 jmsctl.sh /upgrade 的第 6 步
![image](https://github.com/jumpserver/jumpserver/assets/32380085/99324199-ca4d-46b0-ac22-9d03b65e487e)

**Comment by wellsyu** [comment]
> 升级时默认会清理旧版本镜像，你也可以手动清理
实际上，我在我系统里，发现了所有以前升级过的镜像，占用了很多磁盘空间

**Comment by wellsyu** [comment]
> 在 jmsctl.sh /upgrade 的第 6 步 ![image](https://user-images.githubusercontent.com/32380085/261616816-99324199-ca4d-46b0-ac22-9d03b65e487e.png)

![微信截图_20230819095749](https://github.com/jumpserver/jumpserver/assets/19767613/083dc350-1efb-436f-9a7b-2b978ae86eff)

**Comment by wojiushixiaobai** [comment]
自行处理，我们只会清理上个版本你使用的镜像，更久远的你得手动清理。

脚本没法判断你哪些镜像被你使用。
