### ISSUE TITLE
1.0不能立即推送系统用户

### ISSUE THREAD

**Issue by mrzhxl** [jumpserver/jumpserver#1133]
[v1.0在系统用户已经设置立即推送,但是点击立即推送也不能推送]

##### 使用版本
[v1.0]

##### 问题复现步骤
1. [授权管理给资产授权]
2. [ssh登陆跳板机可以看到资产,选择登陆后提示Authenticate with server failed, contact administrator,资产主机中没有推送系统用户,点击立即推送,显示成功,但是还是没有执行任务]

##### 具体表现
![image](https://user-images.githubusercontent.com/15653783/38076227-930d17d2-3367-11e8-8694-41ecac64aab2.png)
![image](https://user-images.githubusercontent.com/15653783/38076290-c5b0ee02-3367-11e8-8f70-de43fae283dc.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liwei5** [comment]
我也遇到这个问题，不知道怎么解决

**Comment by mrzhxl** [comment]
@liwei5 我的是docker环境,把redis别外置就可以,但是跑个4-5天还是会有问题,好像是任务不往redis里存了
