### ISSUE TITLE
[Question] 连接上一个不存在的资产会话中断会话

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11335]
**请描述您的问题.**
3.6.0
我们下架了一台交换机，但是jumpserver资产列表没删除，不小心连接上了这个不存在的资产，会话无法中断，点中断选项也不行
![image](https://github.com/jumpserver/jumpserver/assets/44529247/e6d0ed19-eacf-4508-810a-3f85cb13e648)

**Comment by LeeEirc** [comment]
复现了，已修复，待 v3.6 小版本更新。

**Comment by BaiJiangJie** [comment]
v3.6.1 已解决。
