### ISSUE TITLE
[Question] M1 mac jumpserver_client增加crt客户端

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11342]
**请描述您的问题.**
client2.0没有发现可以配置新增远程终端的按钮，如何调用CRT呢？
<img width="860" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/8715a1f9-c64d-4df7-9b2c-a3996f7d66da">

**Comment by BaiJiangJie** [comment]
MacOS 目前还不支持。

**Comment by Halo1236** [comment]
@pika-FENG 后续迭代支持
