### ISSUE TITLE
[Question] 无法使用pycharm远程调试python代码

### ISSUE THREAD

**Issue by tokendot** [jumpserver/jumpserver#11351]
ssh可以正常连接，无问题。
但选择远程解释器时，无法显示python版本，显示为'unknown python'。
强行进行debug，pycharm报错，内容为：While creating remote tunnel for SshjSshConnection(xx@xx@xx@xx)@xxx: localhost:xxxx == localhost:xxxxx: Global request [global req for tcpip-forward] failed。
请问应当如何解决？

**Comment by BaiJiangJie** [comment]
应该是还不支持  tcpip-forward 方式。

**Comment by tokendot** [comment]
> 应该是还不支持 tcpip-forward 方式。

那请问应当如何解决？是需要联系管理员调整一些设置吗

**Comment by BaiJiangJie** [comment]
应该不是设置的问题，可能是代码层面的不支持。

我们复现一下看看其中的问题吧。使用 vscode 直连应该是支持的。

**Comment by tokendot** [comment]
> 应该不是设置的问题，可能是代码层面的不支持。
> 
> 我们复现一下看看其中的问题吧。使用 vscode 直连应该是支持的。

需要提供具体环境吗，如果需要的话可能要等到周一才可以提供

**Comment by BaiJiangJie** [comment]
暂时不需要。

**Comment by BaiJiangJie** [comment]
应该是不支持 PyCharm 远程调试。

**Comment by cupen** [comment]
支持 ssh tunnel 就可以了。
