### ISSUE TITLE
[Question] v3.5.2 源码部署 打开Web终端一直转圈

### ISSUE THREAD

**Issue by cruize3** [jumpserver/jumpserver#11355]
情况如图：
![830c2db73eda51acc0661745fc5231b](https://github.com/jumpserver/jumpserver/assets/53335613/782b32a3-a9b5-4634-b6f5-8472ad99400a)
浏览器控制台：
![image](https://github.com/jumpserver/jumpserver/assets/53335613/63674e2b-f44b-438b-b2fe-aedb2d2f21d7)

**Comment by cruize3** [comment]
有编译需求，这个问题没法排查吗

**Comment by ibuler** [comment]
参考 Dockerfile 构建

**Comment by cruize3** [comment]
我根据在线手册布的，这个有错误吗
[在线的源码部署手册](https://docs.jumpserver.org/zh/v3/installation/source_install/requirements/#1)

**Comment by BaiJiangJie** [comment]
源码编译问题，问题比较复杂，不好排查是什么导致的。

还是建议直接用离线包部署使用。如果要自己编译，参考 Dockerfile 的构建步骤。
