### ISSUE TITLE
[Bug] 新版本改密功能缺陷

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11354]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6

**浏览器版本**

**Bug 描述**
Linux机器。ops是特权账号，测试登录OK；root禁止直连，设置了“切换自ops”，测试登录OK；
创建改密任务修改root密码，os改密成功，但是改密任务在校验密码时候报错，然后堡垒机里面密码也没有更新。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
看一下校验密码的报错日志。

**Comment by khy2021** [comment]
>>> 开始执行任务

PLAY [all] *********************************************************************

TASK [Test privileged opadm account] *******************************************
ok: [10.21.120.124(root)]

TASK [Check if root user exists] ***********************************************
ok: [10.21.120.124(root)]

TASK [Add root user] ***********************************************************
skipping: [10.21.120.124(root)]

TASK [Add root group] **********************************************************
skipping: [10.21.120.124(root)]

TASK [Add root user to group] **************************************************
skipping: [10.21.120.124(root)]

TASK [Change root password] ****************************************************
changed: [10.21.120.124(root)]

TASK [remove jumpserver ssh key] ***********************************************
skipping: [10.21.120.124(root)]

TASK [Change root SSH key] *****************************************************
skipping: [10.21.120.124(root)]

TASK [Set root sudo setting] ***************************************************
skipping: [10.21.120.124(root)]

TASK [Refresh connection] ******************************************************
[WARNING]: Failed to reset connection:Control socket
connect(/root/.ansible/cp/7f55244eb3): No such file or directory

TASK [Verify root password (paramiko)] *****************************************
core/2.14/reference_appendices/interpreter_discovery.html for more information.
fatal: [10.21.120.124(root) -> localhost(127.0.0.1)]: FAILED! => {"changed": false, "msg": "Unable to connect to asset: Authentication failed."}

PLAY RECAP *********************************************************************
10.21.120.124(root)        : ok=3    changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0
Task accounts.tasks.automation.execute_account_automation_task[7c55e181-beb5-4e90-aee4-85ca0d1744c7] succeeded in 12.643637176603079s: None

**Comment by BaiJiangJie** [comment]
修改为使用 Ansible Ping 的账号验证方式呢？

**Comment by khy2021** [comment]
> 修改为使用 Ansible Ping 的账号验证方式呢？

在哪里改呢？

**Comment by khy2021** [comment]
> 修改为使用 Ansible Ping 的账号验证方式呢？

我修改了平台上的“账号验证方式”为 Ansible Ping后，账号登录测试都通不过，报错
PLAY [all] *********************************************************************

TASK [Verify account connectivity] *********************************************
fatal: [IP(root)]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Warning: Permanently added 'IP' (ECDSA) to the list of known hosts.\r\nPermission denied, please try again.", "unreachable": true}

PLAY RECAP *********************************************************************
IP(root)        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
Task accounts.tasks.verify_account.verify_accounts_connectivity_task[100a547f-dfe0-4359-a0b2-4d1ee4d865c3] succeeded in 3.8399828523397446s: None

**Comment by BaiJiangJie** [comment]
看着像是服务器配置的问题。多测试几台，看看其他的是不是正常。

**Comment by khy2021** [comment]
> root禁止直连，设置了“切换自ops”，测试登录OK

这不会是服务器的问题。这台机器试过了，root可以登录成功，但是在“账号”--“测试”那里都会报错。
问题应该很明显，就是验证该账号的有效性时，没有走sudo方式，而是直接登录的。改密后进行验证也是同理。

>>> 开始执行任务

PLAY [all] *********************************************************************

TASK [Verify account connectivity] *********************************************
fatal: [IP(root)]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Warning: Permanently added 'IP' (ECDSA) to the list of known hosts.\r\nPermission denied, please try again.", "unreachable": true}

PLAY RECAP *********************************************************************
IP(root)        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
Task accounts.tasks.verify_account.verify_accounts_connectivity_task[fee489f9-6f26-46c7-97c9-3f9ed936c248] succeeded in 3.3108932450413704s: None

**Comment by BaiJiangJie** [comment]
你是 root 设置了 切换自 ops，跟 sudo 有什么关系？

这样，你配置 root 切换自 ops1（自己在服务器上创建出来），然后直接测试 root 账号可连接性，看结果。

**Comment by khy2021** [comment]
> 你是 root 设置了 切换自 ops，跟 sudo 有什么关系？



> 你是 root 设置了 切换自 ops，跟 sudo 有什么关系？
> 
> v3.6 测试账号可连接性做了 切换用户 测试。
> 
> 这样，你配置 root 切换自 ops1（自己在服务器上创建出来），然后直接测试 root 账号可连接性，看结果。

我描述的不贴切吧，我意思就是它没有从ops切换过去登录。
ops1和ops有什么区别吗？ops就是我们服务器里面有免密sudo的系统账号。

**Comment by BaiJiangJie** [comment]
嗯，问题找到了。

目前测试账号可连接性不支持切换自的测试，所以会测试失败。

改密的时候最后会测试可连接性，失败了就不会保存了。

也就是目前版本还不支持对于切换自账号的改密。

除非解除 root 禁止直连。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11566

**Comment by BaiJiangJie** [comment]
关注新版本发布。（v3.8）已修复。

**Comment by Coldfengzi** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/23092924/d6c45cf9-4da8-4651-b80b-357ceff7b14b)
V3.8 版本root切换自账号登录还是失败。
