### ISSUE TITLE
[Feature] 增加passkey或者webauthn认证方式

### ISSUE THREAD

**Issue by imleafz** [jumpserver/jumpserver#11365]
希望在开启MFA的基础上增加浏览器passkey、webauthn等认证方式。目前github支持passkey、security key，gitlab支持webauthn。

**Comment by ibuler** [comment]
国内好像不太流行这些

**Comment by imleafz** [comment]
确实国内项目集成这个的不多，所以？

**Comment by iseki0** [comment]
确实，没有这个功能非常蛋疼

**Comment by iseki0** [comment]
主要是这个功能也可以和本地操作系统上的认证机制结合使用，不一定要使用 Yubikey 这样的硬件，Windows Hello 也是可行的。所以非常有用的一个东西

**Comment by imleafz** [comment]
> 主要是这个功能也可以和本地操作系统上的认证机制结合使用，不一定要使用 Yubikey 这样的硬件，Windows Hello 也是可行的。所以非常有用的一个东西

是的，我所指的就是Windows Hello和iCloud Keychain，现在我登录支持的网站（GitHub/Gitlab/Cloudflare/Google），只需要指纹就可以认证了，非常方便安全。

**Comment by BaiJiangJie** [comment]
嗯，可以考虑支持。

**Comment by jym503558564** [comment]
v3.7.0版本已实现Passkey认证服务。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/db2dea9c-24d3-4f71-ae31-e71d2d5a4e6b)
