### ISSUE TITLE
[Question] 网络设备的sftp连接

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11368]
**请描述您的问题.**
3.6.1
web终端连接交换机设备的时候没有sftp选项了，是取消了吗，linux的sftp选项是存在的。
交换机
![image](https://github.com/jumpserver/jumpserver/assets/44529247/92f34dec-b1f9-41ca-976c-27399f152103)
服务器
![image](https://github.com/jumpserver/jumpserver/assets/44529247/267d1ed0-814e-4eeb-bcec-a07c4651f890)

**Comment by ryswork1993** [comment]
知道原因了，ssh和sftp分开了，linux默认存在sftp协议，网络设备的sftp协议取消了，希望可以把网络设备的sftp也加回来
![image](https://github.com/jumpserver/jumpserver/assets/44529247/fc65ac35-0fcd-4733-9fa3-0ebe923c1d6c)

![image](https://github.com/jumpserver/jumpserver/assets/44529247/20f5f634-ceb1-4084-b4d0-6d855d3386b6)

**Comment by jym503558564** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40739051/7ea03fd7-650c-4756-997d-06d614473508)
已实现
