### ISSUE TITLE
[Bug] mysql 客户端方式 kill 存在问题

### ISSUE THREAD

**Issue by asdfgasysfy** [jumpserver/jumpserver#11366]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
edge 最新版本

**Bug 描述**
数据库连接方式为客户端方式
通过这种方式连接后. kill id命令将报错报错内容如下
![image](https://github.com/jumpserver/jumpserver/assets/132526870/6657d154-bb20-4208-91a0-f12f47ec3086)

**Bug 重现步骤(有截图更好)**
1.在堡垒机配置一台数据库资产 mysql5.7
2.配置数据用户. 开启process select super权限. 并在堡垒机配置相应用户
3.通过客户端的方式. 获取连接信息. 使用navicat登录
4. 在navicat执行执行 kill ID  会报错.  
5. 但是使用web方式连接就可以正常kill
![image](https://github.com/jumpserver/jumpserver/assets/132526870/13e9fdf1-1b5a-4834-9d86-592ae2042cf6)

**Comment by asdfgasysfy** [comment]
虽然两次kill ID不一样 . 但是问题确实存在

**Comment by ibuler** [comment]
kill 命令应该发生在客户端， web方式是  web -> 客户端 -> 服务器端，客户端执行应该没有问题，代理方式是  客户端 -> 代理端 代理客户端 -> 服务器端，所有可能错乱

**Comment by jym503558564** [comment]
问题已复现，已提交开发修复。

**Comment by BaiJiangJie** [comment]
算 Bug，后续版本会修复。

**Comment by Aaron3S** [comment]
您好 jumpserver 版本是什么，没看到你的的版本信息。

**Comment by BaiJiangJie** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32935519/b6472b0c-9f5c-4ce0-aa57-323c167d2835)

kill 后面的值是怎么获取的？
@asdfgasysfy

**Comment by BaiJiangJie** [comment]
后续有反馈再 Reopen。
