### ISSUE TITLE
[Question] jumpserver调用本地jumpserver client问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11367]
**请描述您的问题.**
3.6.1
1、我用web终端通过ssh客户端方式连接资产的时候，连接的资产ip和端口号是应用发布机的ssh端口而不是资产的ip和端口号这是正常的吗

![image](https://github.com/jumpserver/jumpserver/assets/44529247/d134c76a-d3d0-4b2a-8d38-2445f09f792e)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/05fbb077-21b9-4b2f-99cf-07692f741fc0)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/63b1e765-e985-4fbc-b47f-cd6242917c23)

**Comment by ibuler** [comment]
客户端连接的是 koko 组件，并非资产，koko 连接的才是真正资产

**Comment by ryswork1993** [comment]
> 客户端连接的是 koko 组件，并非资产，koko 连接的才是真正资产

他默认调用的ip是jumpserver的，但是端口号是应用发布机的端口号，我堡垒机的管理端口是9001，所以导致jumperver client连接堡垒机失败
![image](https://github.com/jumpserver/jumpserver/assets/44529247/8e89bc6d-c3e7-45cd-a236-5f5bc6991207)

**Comment by ibuler** [comment]
这个你你需要去  系统设置 -> 组件管理（终端管理） ->  服务端点 (Endpoint) 告诉 core，你监听的端口

**Comment by ibuler** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/17382885/e588cc67-6008-48bc-89a8-da731b878354)

**Comment by ryswork1993** [comment]
> 



> ![image](https://user-images.githubusercontent.com/17382885/261898669-e588cc67-6008-48bc-89a8-da731b878354.png)

感谢，已经解决了。rdp调用客户端功能是企业版功能吗，社区版好像没有调用客户端这个选项

**Comment by ibuler** [comment]
是的
