### ISSUE TITLE
[Bug] 优化文件管理上传文件时，如果存在同名文件则使用新名称进行保存

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#11369]
使用场景，比如当有jar包需要修改后重新打包上传覆盖。
之前是可以直接覆盖的，现在默认是重命名。但是文件很多找起来也麻烦，就怕一不小心就误删。
能不能同文件名覆盖上传时，就像删除一样弹出一个确认框呢？确认是否覆盖，否的话再重命名。

**Comment by dhfsqxz** [comment]
+1
现在感觉好麻烦
一开始还以为文件权限出问题了

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10983

当时有用户提覆盖的问题，所以考虑了重命名。


那后面版本考虑提示一下执行动作吧。（覆盖、重命名）

**Comment by dhfsqxz** [comment]
> #10983
> 
> 当时有用户提覆盖的问题，所以考虑了重命名。
> 
> 那后面版本考虑提示一下执行动作吧。（覆盖、重命名）

建议改为后台配置，管理员统一配置默认为覆盖或者重命名
如果不配置则每次弹出提示

**Comment by dhfsqxz** [comment]
用了好久了
我们好多同事都不习惯
这东西太痛苦了

**Comment by flacce** [comment]
> 用了好久了 我们好多同事都不习惯 这东西太痛苦了

回退吧3.5.4吧，这是一种很新的同名文件处理方式，看PR提交是没有要处理的意思。

**Comment by BaiJiangJie** [comment]
v3.7 版本会优化。

允许用户在个人设置中，进行配置。

1. 直接替换
2. 重命名

上传的过程中，提示弹窗不好处理。会根据用户的个人设置进行处理。

**Comment by flacce** [comment]
收到，感谢！

**Comment by dhfsqxz** [comment]
感谢

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
