### ISSUE TITLE
[Bug] v3.6.1 csrf 问题

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11363]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.5.4升级到3.6.1

**浏览器版本**
版本 115.0.1901.203 (正式版本) (64 位)

**Bug 描述**
1.新开期页面无法登录
2.升级前的web页面刷新可以但是无法使用web链接服务器

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/70053869/1ae12cab-1208-4f63-84ed-96adb475ea32)
![image](https://github.com/jumpserver/jumpserver/assets/70053869/c7ec8910-3440-4677-b07b-dc0738b7d58f)

**Comment by ibuler** [comment]
由于新版本升级了新版本 Django，为了安全，要求必须填写可信任的域名，所以 JumpServer v3.6 可选择一种下面方式解决：
1. 如果只有一层 Nginx 应该不会出现问题，如果多层 Nginx，需要每层上添加配置：proxy_set_header Host $http_host;
2. 配置文件中添加 DOMAINS="浏览器中你的域名或IP:端口,其它域名IP:端口"

**Comment by JeongHyeokLee** [comment]
按照您说的配置方式 并没有解决问题还是一样的 只能回滚到3.5.4

**Comment by ibuler** [comment]
ok，你可以测试环境试试

**Comment by dowliu** [comment]
v3.5.4升级v3.6.1出现同样的问题，添加DOMAINS配置能够解决。
但是昨天在另外两套同样的版本的测试环境升级未出现该问题，其中一套是直接通过公网IP暴露的，另外一套是通过腾讯云CLB暴露的。

**Comment by Finnimbrun** [comment]
> 由于 v3.6 升级了最新版本的 Django(4.1)，新 Django 为了安全，要求必须填写可信任的域名，所以 JMS v3.6.1 可选择一种下面方式解决 440、403 的问题 (v3.6.0 只能选第 2 中) ：
> 
> 1. 如果没有额外配置过 nginx 或者其它 LB 应该不会有问题，如果配置过，需要每层代理上添加配置：proxy_set_header Host $http_host;
> 2. 配置文件(/opt/jumpserver/config/config.txt)中添加配置:  DOMAINS="浏览器中你的域名或IP:端口,其它域名IP:端口"
> 
> 重启

似乎只有添加的第一个域名或IP才能生效,后面添加的其他域名IP依旧报错. 当换到第一个位置的时候就生效了.

**Comment by JeongHyeokLee** [comment]
只要升级就不行哎 也不知道您说修复是怎么修复的

**Comment by newIDforLOL** [comment]
原本参照[升级须知](https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/)，添加了DOMAINS=MYIP，但依然不成功，调了半天只知道是CSRF的问题

看了ibuler的回答才知道还需要写端口....  

建议修改一下升级须知里的示例，增加端口信息。
