### ISSUE TITLE
首页用户/资产活跃情况，接口返回为空值，/api/v1/index/?dates_metrics=1&days=7

### ISSUE THREAD

**Issue by todevops** [jumpserver/jumpserver#11376]
![image](https://github.com/jumpserver/jumpserver/assets/57765353/a962811a-e054-4579-9574-39408a5d2e95)
![image](https://github.com/jumpserver/jumpserver/assets/57765353/04a221b7-99fd-4aea-aad7-6f2975a1176b)
首页接口返回为空，v3.5.3 出现，升级 v3.6.0 也一样
查询日志发现 flower有一些warn日志
![image](https://github.com/jumpserver/jumpserver/assets/57765353/d4446a64-2413-4765-b850-ca79fecb609c)

**Comment by BaiJiangJie** [comment]
有连接过会话吗？

**Comment by todevops** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/57765353/d68e756d-5d0e-4f6f-9be5-c7ee52380475)

**Comment by BaiJiangJie** [comment]
在交流群里吗？远程看一下。
