### ISSUE TITLE
[Feature] "默认数据库"字段建议允许为空

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11378]
**请描述您的需求或者改进建议.**
当前版本3.6，数据库资产的“默认数据库”字段不允许为空，必须指定某个数据库；但是实际场景中，用户是希望能登录后展示所有的数据库，这里字段应该为空。
希望该字段可以允许为空，让用户自主选择被授权的数据库。

**Comment by BaiJiangJie** [comment]
后面版本考虑一下。

**Comment by BaiJiangJie** [comment]
其实即便是填写了数据库，连上去之后也是能操作其他数据库的（关键取决于 mysql 的权限机制）。

**Comment by 0x5c0f** [comment]
> 其实即便是填写了数据库，连上去之后也是能操作其他数据库的（关键取决于 mysql 的权限机制）。

其实按照现有的规则，一个资产只能对应一个数据库实例，但实际上一个mysql可能包含多个数据库，关于说的连接上去也能操作其他数据库，这个就涉及到mysql的授权问题了，大多数时候，每个库都会有独立的授权，所以`连上去之后也是能操作其他数据库`如果mysql本身未授权，也是不存在的，因此如果强制默认数据库必填可能不是很好的选择，因为这样一个数据库实例如果有多个库就需要创建多个资产，当然可以将默认库设置为 information_schema

**Comment by BaiJiangJie** [comment]
v3.8 版本会取消 默认数据库的必填项。（仅针对 MySQL）
