### ISSUE TITLE
[Bug] jumpserver redis Browser connection, Chinese garbled code

### ISSUE THREAD

**Issue by buxiuzhang** [jumpserver/jumpserver#11374]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
V3.4.3

**Bug 描述**
When using JumpServer client to access Redis Cli, read Chinese garbled code, such as "get Key xxx",

Suggestion! When connecting redis cli, adding the - raw parameter can effectively avoid the problem of Chinese garbled characters.

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/43929602/94dc1187-288e-4732-a4fd-2a38d1e076ac)
2.
![image](https://github.com/jumpserver/jumpserver/assets/43929602/6e7a6f5a-b04e-4a3a-8eff-88b3418eb213)
3.

**Comment by BaiJiangJie** [comment]
好的，小版本优化一下。

**Comment by liubo637** [comment]
v3.6.1版，版本号写错了

**Comment by BaiJiangJie** [comment]
新版本已优化。
