### ISSUE TITLE
[Bug] ssh终端连接模式下看不到授权的数据库，网页登录正常

### ISSUE THREAD

**Issue by liubo637** [jumpserver/jumpserver#11375]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
Microsoft Edge 115.0.1901.203 

**Bug 描述**
ssh终端连接模式下看不到授权的数据库，网页登录正常

**Bug 重现步骤(有截图更好)**
1.
![891d3e5a9485b467211e8fd730223b1](https://github.com/jumpserver/jumpserver/assets/1932666/8f3cc3bb-4b5d-4eeb-91c6-8805772058c6)

2.
![267fd96d1ec4c0c96de1166066a1af9](https://github.com/jumpserver/jumpserver/assets/1932666/079b0aaf-872b-4499-a657-7a4ecb3b8480)

3.

**Comment by BaiJiangJie** [comment]
<img width="1014" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f7af3548-6171-4baf-8de6-f13408780a3b">

新版本 KoKo 不支持对于这几种数据库的连接了。

**Comment by liubo637** [comment]
就是说以后不再支持能过ssh访问堡垒机的数据库资源了吗？

**Comment by BaiJiangJie** [comment]
主要考虑的原因有几点：

1. koko 连接数据库需要 unshare 模式；
2. 使用 client 端镜像比较大
3. Chen 组件已经支持连接数据库，将来会把 console 方式放在 Chen 组件中。

**Comment by liubo637** [comment]
好的，多谢解答！

**Comment by ibuler** [comment]
koko 连接数据库需要 unshare 模式；这个也需要 容器以 特权模式运行，所以才决定逐步挪到 chen 中，以一种比较好的方式来实现
