### ISSUE TITLE
功能需求：希望能开发管理员手机APP

### ISSUE THREAD

**Issue by renziyou** [jumpserver/jumpserver#11377]
**请描述您的需求或者改进建议.**
背景：因班次不同或出门在外身边没电脑。有用户打电话要求处理账号问题（如，锁定、过期、协助修改密码、MFA等问题）用手机web操作就不是太方便了，希望能开发款手机APP直接 通过手机APP操作。这功能很实用的希望能采纳哈

**Comment by BaiJiangJie** [comment]
主要考虑几点：

1. 大多数企业的堡垒机都是在内网部署的，通过 APP 操作的场景有，但是很少；
2. 手机 Web 操作可以满足基本的运维需求；
3. APP 端的实现、维护成本比较大。

所以暂时先不考虑了。

**Comment by BaiJiangJie** [comment]
如果您愿意开发、贡献 APP 端的话，JumpServer 研发团队很愿意为您提供支持。 @renziyou

**Comment by ryswork1993** [comment]
> 如果您愿意开发、贡献 APP 端的话，JumpServer 研发团队很愿意为您提供支持。 @renziyou

他这几个需求可以在登录界面设置一个帮助选项，把他想要的解锁，过期申请放里边，通过点击解锁，过期申请等自动发送邮件给管理员，管理员点击链接实现操作，是不是也行

**Comment by ibuler** [comment]
@ryswork1993 好像在理

**Comment by BaiJiangJie** [comment]
目前不考虑支持手机 APP。
