### ISSUE TITLE
[Question] 为啥3.5.3版本token过期之前的页面直接刷新会自动刷新 

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11371]
**请描述您的问题.**
3.5.3
3.5.3版本token过期 之前的页面直接刷新自动刷新 必须手动访问/路径然后重新登录才可以  为何tokken过期不会返回登录页面？

**Comment by BaiJiangJie** [comment]
详细描述一下，配上截图。
