### ISSUE TITLE
[Question] 升级版本后web无法登录

### ISSUE THREAD

**Issue by aaronchou0** [jumpserver/jumpserver#11389]
从3.5.0升级到3.6.1，在线升级方式
升级后登录web控制台报错
![image](https://github.com/jumpserver/jumpserver/assets/15139155/1c477574-1d00-42bf-b80d-e32478b96056)
命令行可以登录堡垒机并连接其他资产。

暂没查询到其他相关日志

**Comment by BaiJiangJie** [comment]
外部有 Nginx 吗？

**Comment by aaronchou0** [comment]
> 外部有 Nginx 吗？
> 
> 参考一下这个 issue（[https://github.com/jumpserver/jumpserver/issues/11363）](https://github.com/jumpserver/jumpserver/issues/11363%EF%BC%89)

感谢，搞定了，我看更新日志里面写
fix: 修复安装、升级 v3.6.0 版本后访问页面 400、403 的问题（正常情况下，不再强制要求配置 DOMAINS 参数）
就没管这个，看来还是没修复？

**Comment by dowliu** [comment]
> > 外部有 Nginx 吗？
> > 参考一下这个 issue（[https://github.com/jumpserver/jumpserver/issues/11363）](https://github.com/jumpserver/jumpserver/issues/11363%EF%BC%89)
> 
> 感谢，搞定了，我看更新日志里面写 fix: 修复安装、升级 v3.6.0 版本后访问页面 400、403 的问题（正常情况下，不再强制要求配置 DOMAINS 参数） 就没管这个，看来还是没修复？

目测是没修复，我在三个不同的环境下从3.5.4升级3.6.1，有两套正常，有一套出现了403的错误，通过增加DOMAINS解决的。所以，怀疑这个问题尚未彻底修复。

**Comment by ibuler** [comment]
这个是新 Django 带来的问题，为了安全，还是麻烦点，最好都设置 DOMAINS 吧
