### ISSUE TITLE
[Feature] 批量登录勾选框优化

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11384]
请问出于何种原因要点击一下“批量登录”的复选框再选择设备呢，为何不能直接在设备前面显示复选框？是否可以优化。

**Comment by BaiJiangJie** [comment]
因为考虑到使用过程中单个连接的使用率更高。

**Comment by pika-FENG** [comment]
个人感觉保留复选框的情况下也不影响连接单台设备

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bryan ***@***.***&gt;
发送时间: 2023年8月25日 09:58
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: Feng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [Feature] 批量登录勾选框优化 (Issue #11384)

**Comment by BaiJiangJie** [comment]
直接放出来，审美不过关。

**Comment by pika-FENG** [comment]
确实，理解



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bryan ***@***.***&gt;
发送时间: 2023年8月25日 10:22
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: Feng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [Feature] 批量登录勾选框优化 (Issue #11384)
