### ISSUE TITLE
[Bug] 对名称中含 `[`、`]` 的主机进行“测试资产可连接性”测试时，会 Runner failed

### ISSUE THREAD

**Issue by Fallen-Breath** [jumpserver/jumpserver#11388]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

JumpServer 社区版 GPLv3 v3.6.1

**浏览器版本**

Chrome 116.0.5845.97

**Bug 描述**

对名称中含 "["、"]" 的主机进行“测试资产可连接性”测试时，会出现形如 `Runner failed: cannot unpack non-iterable NoneType object <assets.automations.ping.manager.PingManager object at 0x7f47a04cb890>` 的错误。详见下面的复现步骤

怀疑由如下代码引起：

在下述代码中，有对 `host['name']` 中 `[`、`]` 进行替换的操作

https://github.com/jumpserver/jumpserver/blob/1044ff004bd1c47d3e70f59f05a390ae9382cd16/apps/ops/ansible/inventory.py#L281-L285

在下述代码中，使用了 `host['name']` 作为 `self.host_asset_and_account_mapper` 的 key，但使用了 `host` 进行查询。这里的 `host` 参数怀疑是替换了 `_` 主机名的版本，从而导致 `self.host_asset_and_account_mapper.get(host) ` 返回 `None`，导致 `cannot unpack non-iterable NoneType object` 错误

https://github.com/jumpserver/jumpserver/blob/1044ff004bd1c47d3e70f59f05a390ae9382cd16/apps/assets/automations/ping/manager.py#L17-L29

**Bug 重现步骤(有截图更好)**
1. 创建一个主机名中含有 `[` 或 `]` 的 Linux 主机
  
  ![image](https://github.com/jumpserver/jumpserver/assets/28978806/b5be9bea-291d-4129-b6c8-453fa6c31b9a)

2. 在资产列表页面，选择这台机子，点击测试
  
  ![image](https://github.com/jumpserver/jumpserver/assets/28978806/21038f24-0595-4312-af46-ecbc0ce0cbed)

3. 在执行界面，出现所述错误

  ![image](https://github.com/jumpserver/jumpserver/assets/28978806/7f3529d3-28f8-43ec-9e4b-2f45e93b4b24)

**Comment by ibuler** [comment]
收到，下个小版本修复

**Comment by ibuler** [comment]
[v3.6.2](https://github.com/jumpserver/jumpserver/releases/tag/untagged-df96dd7e388a024b68c1) released fix this issue thanks
