### ISSUE TITLE
[Feature] 保留批量登录会话记录

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11383]
V3.6.1批量登录和调起本地客户端工具真给力，实际运维中对当前勾选的N个设备，下次同样会再次勾选批量登录，是否可以考虑在工作台最近会话中 保留上一次勾选的批量设备，方便直接登录。

**Comment by ibuler** [comment]
收到，下个大版本，提交上去了

**Comment by ibuler** [comment]
https://github.com/jumpserver/luna/pull/936
