### ISSUE TITLE
[Bug] chen 组件纳管SQL Server 数据库， 时间字段显示异常

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#11385]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**浏览器版本**

**Bug 描述**
纳管 SQL Server 数据库。 时间字段在数据库客户端有做格式化显示，但在 JumpServer 这里直接显示的是时间戳。 如下图

<img width="771" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/ebf65495-42fc-4256-80e1-dc88fb3fcdc6">
<img width="772" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/ee7116ae-0ea9-40c8-9955-bac44ebcf726">

**Comment by xulinde** [comment]
目前还不支持，已提需求了，看研发排期吧

**Comment by BaiJiangJie** [comment]
计划在 v3.7 版本中优化。

**Comment by BaiJiangJie** [comment]
v3.6.4 中会修复。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
