### ISSUE TITLE
[Bug] Windows 推送账号失败，web 正常登录进入系统

### ISSUE THREAD

**Issue by yunyouu** [jumpserver/jumpserver#11380]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.6.0
**浏览器版本**
Chrome 116

**Bug 描述**
新增了一个 Windows RDP 资产，使用内网地址进行连接。web 界面 RDP 登陆正常，资产推送日志有以下错误。
<img width="915" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/73619961-dcda-49c3-975e-c27c75544344">
执行列表显示推送成功。
<img width="1169" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/981bac4d-22a3-4c26-a3f1-9d74855abe4d">
系统内部没有新增用户成功。
<img width="775" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/1eb9305c-26ee-445f-b9a2-9648b45ce213">

**Bug 重现步骤(有截图更好)**
添加一个 Windows Server，正常新建一个账号推送。
<img width="1176" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/3f174070-ba6d-4220-84c8-38d99948a47b">

**Comment by BaiJiangJie** [comment]
windows 上安装 openssh 了吗？

**Comment by yunyouu** [comment]
> windows 上安装 openssh 了吗？

没有，刚找到文档关于这块的描述。有问题再重新打开。谢谢回复
