### ISSUE TITLE
[Bug] chen 组件纳管SQL Server 数据库，分页查看失败

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#11386]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**Bug 描述**
chen 组件访问 SQL Server数据库，分页查询报错。（MySQL 正常）
![1692696865443](https://github.com/jumpserver/jumpserver/assets/30264974/f1301e14-4a9b-4317-8140-884c023a0972)

**Comment by xulinde** [comment]
后续版本修复

**Comment by BaiJiangJie** [comment]
计划 v3.6.3 中修复一下。
