### ISSUE TITLE
[Feature] 命令过滤在审核 SQL 语句的页面，增加“影响行数”字段

### ISSUE THREAD

**Issue by jializhu** [jumpserver/jumpserver#11387]
JumpServer 版本：v3.6.1
需求描述：命令过滤目前在数据库的 sql 语句审核上面的功能希望优化，优化方式是在审核的工单里增加"影响行数” 。

可行性：命令过滤在配置 update 或者 delete 的 sql 的时候，当审核未通过的时候，堡垒机通过在sql 外面包一个 begin transaction  及 rollback transaction 拿到影响的行数，审核人可以看到影响的行数知晓影响范围，从而给审核人带来便利。
因为当update有多重嵌套的时候，审核人为了看到影响行数需要手动将 update 改成 select 比较麻烦，特别是 sql 特别复杂的时候。

（希望能考虑下这个需求，如果短期和长期都不会考虑的话也请给个答复，非常感谢！）
<img width="885" alt="image" src="https://github.com/jumpserver/jumpserver/assets/23527101/5d80762f-e90c-4b83-9deb-c8955b9338fc">

**Comment by BaiJiangJie** [comment]
好的，考虑一下。v3.7 调研一下。

**Comment by jym503558564** [comment]
已实现
