### ISSUE TITLE
[Bug] MFA在OTP 扫描后的名称过长的情况下不显示MFA绑定二维码

### ISSUE THREAD

**Issue by guclan** [jumpserver/jumpserver#11391]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
Chrome 116.0.5845.97

**Bug 描述**
系统设置->安全设置->MFA->OTP 扫描后的名称
输入内容过长时（测试7个汉字即可触发该问题），在用户初始化扫描MFA绑定二维码时无法显示该二维码。

**Bug 重现步骤(有截图更好)**
1.系统设置->安全设置->MFA->OTP 扫描后的名称
2. 输入：XXXX堡垒机（XXXX为任意汉字）
3. 登录未进行MFA绑定的用户，在登录后页面进行绑定

**Comment by BaiJiangJie** [comment]
截图看一下效果，我测试了没问题。

**Comment by BaiJiangJie** [comment]
<img width="612" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/b02f30c7-0ffa-4375-8651-ea280699caca">

**Comment by BaiJiangJie** [comment]
<img width="638" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/e5c830a1-9fcd-44ef-903c-e4c7c59ac702">

**Comment by guclan** [comment]
我这边尝试复现了一下，上面我的描述有一些问题。应该是9个汉字时会报错。如下是报错时console日志及页面展示。
![image](https://github.com/jumpserver/jumpserver/assets/25996724/99ef5dd9-7c1e-4f7c-b235-0fc55b92ed44)

**Comment by guclan** [comment]
目前我这边排查的问题是中文会转码urlencode，而英文不会进行转码，编码后的长度传入qrcode会长度过长导致二维码生成失败。

**Comment by BaiJiangJie** [comment]
<img width="555" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/caa673c7-d0bf-4f7c-a37d-fd0d427ff6a6">

也没问题啊，你输入的是什么名称，发我一下。

**Comment by guclan** [comment]
正在搞测试的堡垒机
![image](https://github.com/jumpserver/jumpserver/assets/25996724/4a667868-d434-4cc1-8469-b37f5da21263)

输入上面的字符就会报错，具体报错为代码生成qrcode的otp链接
otpauth://totp/%E6%AD%A3%E5%9C%A8%E6%90%9E%E6%B5%8B%E8%AF%95%E7%9A%84%E5%A0%A1%E5%9E%92%E6%9C%BA:XXXX?secret=XXXXXXXXXXXXXXXX&issuer=%E6%AD%A3%E5%9C%A8%E6%90%9E%E6%B5%8B%E8%AF%95%E7%9A%84%E5%A0%A1%E5%9E%92%E6%9C%BA

X为脱敏位置，都为字母或数字且位数与原文一致，经过解码为原文。
![image](https://github.com/jumpserver/jumpserver/assets/25996724/251e9b91-bdc6-457a-b58f-7f32497007bc)

**Comment by guclan** [comment]
该问题可能为qrcode组件问题，参考https://github.com/davidshimjs/qrcodejs/issues/237

**Comment by BaiJiangJie** [comment]
嗯，是库的问题，小问题，你先换个名称吧。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/11425/files

小版本修复。

更新了一下库，可以了。
