### ISSUE TITLE
[Question] 通过客户端进行连接，是否支持堡垒机作为跳板，直接连接到某台机器。

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11392]
**请描述您的问题.**
你好，例如使用mobaxterm软件进行连接，为了便利性。会配置堡垒机作为jumphost
![image](https://github.com/jumpserver/jumpserver/assets/138869963/5aa00549-38c3-49c6-89c1-dfa2d4cacbbd)
![image](https://github.com/jumpserver/jumpserver/assets/138869963/45f0eadb-fb2d-4b29-91b0-e008927f1875)
然后配置目的机器的host信息，这样通过堡垒机作为跳板，就可以直连到目的机器。
但使用jumpserver堡垒机会有如下报错。
![image](https://github.com/jumpserver/jumpserver/assets/138869963/7a0a8dbb-d86a-43fc-8744-9aa1daaa66b5)
切换secureCRT，会有如下报错。
![image](https://github.com/jumpserver/jumpserver/assets/138869963/28d1fc99-744a-4931-990c-601d387b4805)
请问这个问题如何能否解决呢？感谢

**Comment by BaiJiangJie** [comment]
目前应该是不支持。

**Comment by LeeEirc** [comment]
暂不支持 ssh proxyJump 的方式连接资产。

你可以通过特定的用户名格式，直接连接授权的 ssh 协议资产
 v2 版本参考以下格式

```
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
解释：
- jumpserverUsername：登录 JumpServer 的用户
- systemUsername：连接资产指定的系统用户
- AssetIP：指定要连接的资产
- jumpserverHostIP：JumpServer 服务 IP
- 2222：KOKO 端口
```

 v3 版本参考以下格式

```
ssh jumpserverUsername@accountUsername@Asset@jumpserverHostIP -p2222
解释：
- jumpserverUsername：登录 JumpServer 的用户
- accountUsername：连接资产指定的账户用户名
- Asset：指定要连接的资产 ip 或者 资产 id
- jumpserverHostIP：JumpServer 服务 IP
- 2222：KOKO 端口
```

**Comment by coolmian** [comment]
> 暂不支持 ssh proxyJump 的方式连接资产。
> 
> 你可以通过特定的用户名格式，直接连接授权的 ssh 协议资产 v2 版本参考以下格式
> 
> ```
> ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
> 解释：
> - jumpserverUsername：登录 JumpServer 的用户
> - systemUsername：连接资产指定的系统用户
> - AssetIP：指定要连接的资产
> - jumpserverHostIP：JumpServer 服务 IP
> - 2222：KOKO 端口
> ```
> 
> v3 版本参考以下格式
> 
> ```
> ssh jumpserverUsername@accountUsername@Asset@jumpserverHostIP -p2222
> 解释：
> - jumpserverUsername：登录 JumpServer 的用户
> - accountUsername：连接资产指定的账户用户名
> - Asset：指定要连接的资产 ip 或者 资产 id
> - jumpserverHostIP：JumpServer 服务 IP
> - 2222：KOKO 端口
> ```

这样还是连不上，提示
```
[17:43:59.389] > No PTY requested.
[17:43:59.418] > 过程试图写入的管道不存在。
[17:44:00.697] "install" terminal command done
[17:44:00.698] Install terminal quit with output: 过程试图写入的管道不存在。
[17:44:00.698] Received install output: 过程试图写入的管道不存在。
[17:44:00.699] Failed to parse remote port from server output
[17:44:00.700] Resolver error: Error: 
```

**Comment by lousuan** [comment]
> > 暂不支持 ssh proxyJump 的方式连接资产。
> > 你可以通过特定的用户名格式，直接连接授权的 ssh 协议资产 v2 版本参考以下格式
> > ```
> > ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
> > 解释：
> > - jumpserverUsername：登录 JumpServer 的用户
> > - systemUsername：连接资产指定的系统用户
> > - AssetIP：指定要连接的资产
> > - jumpserverHostIP：JumpServer 服务 IP
> > - 2222：KOKO 端口
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > v3 版本参考以下格式
> > ```
> > ssh jumpserverUsername@accountUsername@Asset@jumpserverHostIP -p2222
> > 解释：
> > - jumpserverUsername：登录 JumpServer 的用户
> > - accountUsername：连接资产指定的账户用户名
> > - Asset：指定要连接的资产 ip 或者 资产 id
> > - jumpserverHostIP：JumpServer 服务 IP
> > - 2222：KOKO 端口
> > ```
> 
> 这样还是连不上，提示
> 
> ```
> [17:43:59.389] > No PTY requested.
> [17:43:59.418] > 过程试图写入的管道不存在。
> [17:44:00.697] "install" terminal command done
> [17:44:00.698] Install terminal quit with output: 过程试图写入的管道不存在。
> [17:44:00.698] Received install output: 过程试图写入的管道不存在。
> [17:44:00.699] Failed to parse remote port from server output
> [17:44:00.700] Resolver error: Error: 
> ```
> 
> 直接命令行使用ssh jumpserverUsername@accountUsername@Asset@jumpserverHostIP -p2222 是可以连接的，但是从Vscode里面连不上

这个真的可以吗？我这边命令行都登不上。。。

**Comment by sincebyte** [comment]
> 暂不支持 ssh proxyJump 的方式连接资产。
> 
> 你可以通过特定的用户名格式，直接连接授权的 ssh 协议资产 v2 版本参考以下格式
> 
> ```
> ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
> 解释：
> - jumpserverUsername：登录 JumpServer 的用户
> - systemUsername：连接资产指定的系统用户
> - AssetIP：指定要连接的资产
> - jumpserverHostIP：JumpServer 服务 IP
> - 2222：KOKO 端口
> ```
> 
> v3 版本参考以下格式
> 
> ```
> ssh jumpserverUsername@accountUsername@Asset@jumpserverHostIP -p2222
> 解释：
> - jumpserverUsername：登录 JumpServer 的用户
> - accountUsername：连接资产指定的账户用户名
> - Asset：指定要连接的资产 ip 或者 资产 id
> - jumpserverHostIP：JumpServer 服务 IP
> - 2222：KOKO 端口
> ```
这个是生效的，但是配置到ssh_config中就提示：Connection closed by UNKNOWN port 65535
Host asset
    HostName asset
    User root
    ProxyCommand ssh -q -W %h:%p jump-server
HOST jump-server
    ControlMaster auto
    ControlPath ~/.ssh/ssh-%r@%h:%p
    ControlPersist 10m
    ServerAliveInterval 60
    hostname jumpserver
    Port 2222
    User username
    ForwardAgent yes
    ForwardX11 yes
    IdentityFile ~/.ssh/id_rsa
