### ISSUE TITLE
[Bug] jumpserverclient v2.0.0 (Apple Silicon) 无法打开

### ISSUE THREAD

**Issue by Uniquefatty** [jumpserver/jumpserver#11398]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
safari 版本16.5.2 (18615.2.9.11.10)

**Bug 描述**
jumpserverclient v2.0.0 (Apple Silicon) 无法打开，提示已损坏
机器是MacBook Air M2芯片
**Bug 重现步骤(有截图更好)**
1.在web终端页面通过菜单“帮助-下载” 打开客户端下载页面
2.下载安装客户端
3.点击客户端图标或通过连接资产时选择客户端方式调起APP均提示已损坏
<img width="1050" alt="截屏2023-08-23 16 30 36" src="https://github.com/jumpserver/jumpserver/assets/80079306/fddfb216-3abd-4976-bd62-ffdffcab8655">

<img width="1147" alt="截屏2023-08-23 16 30 46" src="https://github.com/jumpserver/jumpserver/assets/80079306/14724441-2975-45b0-a342-33fae59d6984">

**Comment by Uniquefatty** [comment]
安全性菜单中，也没有找到系统阻止应用打开的内容，没有看到“任要打开”的可操作按钮

**Comment by pika-FENG** [comment]
xattr -r -d com.apple.quarantine /Applications/JumpServerClient.app即可解决

**Comment by Uniquefatty** [comment]
resolved
