### ISSUE TITLE
[Feature]  关于客户端的连接

### ISSUE THREAD

**Issue by 0x5c0f** [jumpserver/jumpserver#11390]
**请描述您的需求或者改进建议.** 

本来想扯些话的，但还是直接说了，我是linux桌面用户，我的系统是`fedora 38`   

第一个问题:   `jumpserver-client-linux-amd64.run` 客户端工具，这个工具默认是安装到用户主目录的，这个本来没什么问题，但是直接装到主目录，还没有隐藏，这个对于经常使用终端的人来说看起来非常别扭，我之前尝试把这个路径手动改了，但改了后浏览器调用似乎就找不到了。所以这个安装位置能不能隐藏下，或者放到`/opt` 等其他地方去。

第二个问题：关于客户端的`windows`远程功能，客户端下载那个位置提供了 `windows` 和  `mac` 的`rdp`工具，那应该意味着`win`和`mac`是支持拉起本地的`rdp`工具的，然而 在`linux`是并没有的，希望在 `linux` 下也能够支持， 或者支持唤起自定义`rdp`连接的命令 ， 以`fedora` 为例， `rdesktop` 就是一个很好用的`rdp`工具, 安装也简单`sudo dnf install rdesktop`

**Comment by Halo1236** [comment]
linux 使用 deb 格式安装包，安装路径 /opt/jumpserver-client，rdesktop暂时不支持rdp文件，暂时无法支持，推荐使用remmina
