### ISSUE TITLE
[Bug] 默认的admin管理员必须重命名才能删除.

### ISSUE THREAD

**Issue by Finnimbrun** [jumpserver/jumpserver#11393]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**浏览器版本**
最新chrome浏览器

**Bug 描述**
 默认的admin管理员必须重命名才能删除.

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
admin 用户不能被删除。

**Comment by Finnimbrun** [comment]
原本是不能删除或者禁用的, 在我新建了具有管理员权限的用户后, 我又重名了默认的admin用户, 然后把修改用户名后的admin,给删除了.

**Comment by BaiJiangJie** [comment]
只有 username 为 admin 的不允许删除。

如果故意修改用户名后删除，不做限制。
