### ISSUE TITLE
[Bug]  数据库名称带空格时，DBeaver连接错误

### ISSUE THREAD

**Issue by zhongjun96** [jumpserver/jumpserver#11395]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**浏览器版本**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Bug 描述**
数据库名称带有空格，使用数据库客户端连接报错。

**Bug 重现步骤(有截图更好)**
1. 
![image](https://github.com/jumpserver/jumpserver/assets/18225577/8cf46ae1-b434-43e8-9a2d-89e786c3ac28)

2. 
![image](https://github.com/jumpserver/jumpserver/assets/18225577/b746439e-6fc9-40aa-94ba-c04689e5d76d)

3.
<img width="579" alt="image" src="https://github.com/jumpserver/jumpserver/assets/18225577/c8939349-0025-483b-9c83-7c2a138d8466">

**Comment by BaiJiangJie** [comment]
不带空格没问题？

**Comment by zhongjun96** [comment]
> 不带空格可以连接吗？

测试不带空格可以连接。

**Comment by BaiJiangJie** [comment]
测试了一下带空格也没问题。

把你的名称发一下，看看是不是其他字符导致的。

**Comment by zhongjun96** [comment]
> 测试了一下带空格也没问题。
> 
> 把你的名称发一下，看看是不是其他字符导致的。

试了一下 
`DB - 生控中心`  报错
`DB-生控中心`  正常

**Comment by BaiJiangJie** [comment]
嗯，确实有问题。

**Comment by xulinde** [comment]
已复现，v3.9修复～

**Comment by jym503558564** [comment]
v3.9.1已修复，请升级测试
<img width="1102" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/3c0836cc-495d-4ad0-bfd5-a0cfe73bb9b4">
