### ISSUE TITLE
[Bug] 作业管理资产数量显示问题

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#11397]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.6.2
**浏览器版本**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54

**Bug 描述**
当有资产删除后，如果工作台----->作业中心------>作业管理中有该资产。那么资产总数并不会减少

**Bug 重现步骤(有截图更好)**
1.新建资产，新建作业命令，添加资产到该作业中
2.删除资产
3.作业管理概况总数不变
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/1f5cb08e-f598-40d6-ab2a-881c6f1bbbdb)

**Comment by flacce** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/44e2cbe6-4c7d-46d9-85c9-5e39ccc77952)

**Comment by BaiJiangJie** [comment]
刚测试了一下，没问题。刷新一下页面，同时看一下更新页面里的资产。

**Comment by flacce** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/8bbe8173-24b7-4d25-984d-43a6057925e9)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/413678c7-e557-443b-9f83-d567c86dbfc5)
刷新，更换浏览器都是一样的，资产数量是对的上的。
要不然就是我这边的bug吧

**Comment by BaiJiangJie** [comment]
嗯，应该是没问题的。
