### ISSUE TITLE
[Feature] 针对审计员单独做操作审计

### ISSUE THREAD

**Issue by xinlongnb** [jumpserver/jumpserver#11403]
JumpServer建议针对审计人员的操作做一个留痕处理，很多安全部门的检测需要针对，审计人员在什么时间段看了哪些录像有一定的需求，就是审计人员在看录像的时候，需要有一个留痕，让管理人员知道，有谁在什么时间段看了录像，就像做出来的资产活动记录一样
<img width="777" alt="image" src="https://github.com/jumpserver/jumpserver/assets/101784208/157495a1-d0ed-44e8-9847-88cf902fa890">

**Comment by BaiJiangJie** [comment]
目前是会记录所有用户的操作行为，审计员也算用户的一种。没有单独对哪一种用户做特殊记录。

**Comment by ibuler** [comment]
下个版本新增查看录像记录

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/pull/11452

**Comment by ibuler** [comment]
先关闭 issue 了，等待 release
