### ISSUE TITLE
[Bug] 数据库远程应用连接的问题

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11400]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
Google

**Bug 描述**
堡垒机打开后没有进入指定的database，能看到所有的database。

**Bug 重现步骤(有截图更好)**
1. 配置数据库资产，指定database
2. 使用远程应用方式连接数据库资产
3. 堡垒机打开后没有进入指定的database，能看到所有的database

**Comment by BaiJiangJie** [comment]
创建数据库时填写的 Database 是默认连接的数据库，登录上去之后是否能查看其他数据库在于 MySQL 的权限管理机制是否对连接的账号有控制。

**Comment by khy2021** [comment]
> 创建数据库时填写的 Database 是默认连接的数据库，登录上去之后是否能查看其他数据库在于 MySQL 的权限管理机制是否对连接的账号有控制。

跟理解中的不一样。既然指定了database，那么是不是就应该进入到该database，而不显示其它database呢？

**Comment by BaiJiangJie** [comment]
现在很多数据库产品都是这样的方式。
