### ISSUE TITLE
恶性BUG-LDAP认证问题

### ISSUE THREAD

**Issue by xent9312** [jumpserver/jumpserver#1140]
[简述你的问题]
如果一个LDAP用户，首次登录的时候没填写完第一步的信息，别的没有登录过的用户再登陆就会报异常。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.0.0-2

##### 问题复现步骤
1. 链接LDAP
2. 使用LDAP用户1登陆系统，进入首次登录页面。用户1不填写任何信息，关闭网页。
3、使用LDAP用户2登陆系统，出现异常。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是不是这个用户没有设置email

**Comment by BaiJiangJie** [comment]
jumpserverr用户的email字段是必须填写的属性，且唯一。
