### ISSUE TITLE
[Question] 如何调整终端内缓存行数（上滑显示的内容数量）

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#11409]
**请描述您的问题.**
版本：v2.20.1
当前查看文件或执行 sql 时可能有内容较长的场景，上滑无法查看完整内容，目前来看好像只能看到 800 行左右，如何调整呢，尝试过调整 JUMPSERVER_DISABLE_OFFSCREEN_CACHING 参数为 false 没有效果

**Comment by LeeEirc** [comment]
不支持设置，v2.23.0之后已调整成 5000 行，基本满足上下滚动的要求了。

**Comment by lf-zhang** [comment]
> 不支持设置，v2.23.0之后已调整成 5000 行，基本满足上下滚动的要求了。

好吧，请问 2.23.0 之前是多少行呢？

**Comment by LeeEirc** [comment]
之前版本使用是 xterm.js 的默认值 1000 行
