### ISSUE TITLE
[Bug] 无法开启 “与用户登录时相同”

### ISSUE THREAD

**Issue by Genie0s** [jumpserver/jumpserver#11418]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.62

**浏览器版本**
Chrome 116.0.5845.97

**Bug 描述**
虚拟账号中 同名账户无法开启 “与用户登录时相同”

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/68246463/b62939fb-f535-48d7-9840-e9048bc322b9)
显示禁用 无法点击开启
2.
3.

**Comment by BaiJiangJie** [comment]
需要开启 LDAP 认证。

**Comment by Genie0s** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/68246463/45cf8a37-b568-42fd-ba7b-32e42b9a61da)
是已开启LDAP的 微信反馈后修改配置文件 CACHE_LOGIN_PASSWORD_ENABLED=true 后可以正常启用

**Comment by ibuler** [comment]
@Genie0s 能正常使用了吗？使用体验怎么样？

**Comment by Genie0s** [comment]
可以正常使用了 功能没有问题
