### ISSUE TITLE
[Bug] linux平台账号切换登录问题

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11414]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.6.1
**浏览器版本**

**Bug 描述**
当平台的“账号切换方式”设置为“sudo  su -”的时候，设置了“切换自”属性的账号，将无法登录，报错
Connecting to root(root)@<IP> error: i/o timeout

**Bug 重现步骤(有截图更好)**
1. 克隆Linux平台，创建新的平台A
2. 修改平台A的“账号切换方式”属性，设置为“sudo  su -”
3. 更新资产1的平台为平台A
4. 登录资产1的root账号，报错i/o timeout
5.  修改平台A的“账号切换方式”属性，设置为“su -”
6. 登录资产1的root账号成功。

**Comment by wojiushixiaobai** [comment]
sudo su 是提权自己，
su - 是切换用户。

请确定你的特权账号配置正确

**Comment by khy2021** [comment]
> sudo su 是提权自己， su - 是切换用户。
> 
> 请确定你的特权账号配置正确

你说的配置，是指的哪里的配置呢？是服务器上对应的账号的配置呢，还是堡垒机上资产的“特权账号”属性呢？

**Comment by BaiJiangJie** [comment]
sudo su - 

如果执行 sudo 的时候也需要输入密码，su - 的时候也需要输入密码，这样会需要输入两遍密码，不支持这种方式。

su - 只输入 root 的密码，是支持的。
