### ISSUE TITLE
[Bug] 3.6.2版本连接集群无法单个命名空间role限制

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11417]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.2
**浏览器版本**
edge
**Bug 描述**
我针对单个命名空间p-oms创建的role  绑定到命名空间p-oms创建的sa 可是还是可以看到其他命名空间的pod 会加载所有ns的pod列表
![image](https://github.com/jumpserver/jumpserver/assets/73093158/28b2933e-45fa-4ab3-99e4-eb1e4382c972)
![image](https://github.com/jumpserver/jumpserver/assets/73093158/1cf250af-77b2-4a6f-8292-16279b5b224e)

**Comment by wangmingwang123** [comment]
#11039

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/46317158-313a-4d36-88be-baee34639911)
上面的忽略 是我角色绑定问题  现在改好之后权限是符合预期的 但是还有个问题是左侧的pod列表无法加载出来 但是右击连接进集群可以查看到p-oms下的pod其他的命名空间无权限查看  权限是符合预期的只是pod列表左侧无法加载

**Comment by wangmingwang123** [comment]
@BaiJiangJie @BaiJiangJie

**Comment by wangmingwang123** [comment]
请问这个是会在下一个小版本中修复嘛

**Comment by LeeEirc** [comment]
左侧树是通过类似获取所有 namespace  的方式得到数据，如果没有权限的话，可能无法获知有哪些 namespace，也就无法展示。

**Comment by wangmingwang123** [comment]
> 
那这个通过role授予单个命名空间的功权限的功能等于没有实现呀   还是要clusterrole才能显示左侧树

**Comment by wangmingwang123** [comment]
只能说是命令行操作集群权限是生效的  通过左侧树对集群操作还是不行的

**Comment by wangmingwang123** [comment]
左侧树能否通过指定命名空间去获取相关数据呢 
![Uploading image.png…]()

**Comment by wangmingwang123** [comment]
![Uploading image.png…]()

**Comment by wangmingwang123** [comment]
![31D5F84B-7A6B-4071-9771-FA4440D0ACD1](https://github.com/jumpserver/jumpserver/assets/73093158/7570a90a-4f25-4ed0-bffe-4bbe6bccf1c5)

**Comment by LeeEirc** [comment]
目前只有对 k8s 集群资产的管理，尚未限制到具体的 namespace。另外有集群模式，也无法做严格限制。

**Comment by wangmingwang123** [comment]
好的  那我自己通过k8s的rbac实现吧

**Comment by LeeEirc** [comment]
OK
