### ISSUE TITLE
[Bug] 更新资产对应的平台配置，资产列表里的平台配置无变化

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11413]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.2

**浏览器版本**

**Bug 描述**
1、更新平台的配置信息不会自动同步给资产
2、批量更新网络设备的平台后，资产平台mei没有变成更新后的平台

**Bug 重现步骤(有截图更好)**
1. 更新资产对应的平台配置
![image](https://github.com/jumpserver/jumpserver/assets/44529247/977cc149-f02b-4c15-a4fa-4441226541b5)

2.资产列表里的资产的平台配置没变化
![image](https://github.com/jumpserver/jumpserver/assets/44529247/6369502f-3a40-4fd1-b162-0656e9fdb60e)

3.批量更新网络设备的平台交换机变为Huawei，资产平台没变化，收到的一个邮件提示
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d676d776-2a4c-482d-86e5-c652f22fb454)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/e81d4a30-bd78-47a5-a7ef-47127d8e488e)

**Comment by ibuler** [comment]
平台添加的是对资产协议的约束，平台更改新增或减去协议，不会对资产造成影响。对协议的配置才会

**Comment by BaiJiangJie** [comment]
v3.8 会支持同步到资产的协议（只会更新新增加的协议）不会对资产上已存在的协议做移除操作，即使是新的平台中不包含的协议。

请关注后续版本的发布。
