### ISSUE TITLE
[Bug] v3.6.1 SFTP目录设置失效

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11411]
V3.6.1

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
<img width="696" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/4b97b727-91f2-42dd-aa6f-e39ce91a3aae">

2.设置/tmp /home/${ACCOUNT}都不生效

**Comment by LeeEirc** [comment]
已修复，待v3..6.3 小版本更新。

**Comment by ibuler** [comment]
等待修复，的确存在这个 bug
