### ISSUE TITLE
[Question] 连接服务器手动输入密码没有反应

### ISSUE THREAD

**Issue by TIGER-bit** [jumpserver/jumpserver#11419]
**请描述您的问题.**
版本：v3.6.1 
问题：Web 终端连接服务器使用手动输入，一直处于连接中...但是使用托管账号可以正常登录。
![image](https://github.com/jumpserver/jumpserver/assets/67221083/a84788b4-de74-43ba-a2a3-480f9feec5eb)
![image](https://github.com/jumpserver/jumpserver/assets/67221083/52d3be93-bff1-4e67-b703-3aa426bb2e57)

**Comment by wojiushixiaobai** [comment]
检测下账号密码有没有问题，将对应的日志一起发出来看看

**Comment by TIGER-bit** [comment]
账号密码是没有问题的，测试过，正常账号密码错误会弹出相应对话框，但是这个是一直在加载，像是密码一直没有传过去。
当前问题已解决。解决过程：
1、连续降低两个小版本，问题依然存在。
2、重建 jumpserver database问题解决。
3、将版本升至3.6.1，问题依然存在。
4、最后使用版本3.5.4，和重建后的database。
应该是版本间数据库差异，导致数据读写问题。
