### ISSUE TITLE
[Bug] 资产登录跳转时组织不匹配问题

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11427]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.6.1

**浏览器版本**
谷歌105

**Bug 描述**
用户工作台页面，当前是在组织A下；
点击“我的资产”--“登录”，弹出luna页面后，luna页的组织显示是组织B，而不是组织A；
组织B下找不到组织A的该资产，导致无法登录该资产。

另外，建议工作台那里直接允许用户选择用web方式还是客户端方式登录资产，而不是一定要先登录luna页面。
对用户来说，操作越简便，体验就越好。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
@xulinde

**Comment by ibuler** [comment]
原来 Luna 中是全部组织，后来Luna 支持了多组织，跳转没有同步导致的

**Comment by khy2021** [comment]
> 原来 Luna 中是全部组织，后来Luna 支持了多组织，跳转没有同步导致的

大佬，请问可以优化吗？

**Comment by BaiJiangJie** [comment]
我测试跳转到 Luna 页面后，可以正常切换组织啊。

我的资产页面选择资产的登录方式，目前先不考虑做。

登录逻辑想要统一在 Luna 页面，作为 Web 登录资产的唯一访问入口。
