### ISSUE TITLE
[Bug] 在windows中，连接RDP客户端时，使用中文标题无法正确显示

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#11424]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**浏览器版本**
谷歌浏览器

**Bug 描述**
使用JumpServer进行连接windows资产时，使用RDP客户端方式连接（windows电脑，非mac电脑），连接后，会发现RDP客户端标题上，中文显示成了URL编码格式，没有正确显示中文内容。如下图：

![image](https://github.com/jumpserver/jumpserver/assets/47737772/49f11448-3955-497b-9f63-7c5ce08efa15)

**Comment by BaiJiangJie** [comment]
中文是资产的名称吗？还是什么名称？

**Comment by blooze123** [comment]
是的，就是对应左侧资产树的资产名称

**Comment by jym503558564** [comment]
确实存在该问题，mac也是会存在这个问题

**Comment by Halo1236** [comment]
@blooze123 麻烦更新一下客户端 https://github.com/jumpserver/clients/releases/download/v2.0.0/JumpServer-Client-Installer-v2.0.0-x86_64.msi，最新的已经修复
