### ISSUE TITLE
[Feature] sftp禁止删除指定目录

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11428]
**请描述您的需求或者改进建议.**
我linux资产禁止执行rm，所有服务器的文件删除都通过sftp，但有些文件/文件夹不允许被删除，有些可以被删除，是否可以支持指定文件/文件夹禁止删除，删除的目录或者文件都自动保存一份

**Comment by BaiJiangJie** [comment]
删除操作：暂时不考虑对指定文件/文件夹控制。

对于删除的文件/文件夹，可以考虑备份一下，用来审计。
