### ISSUE TITLE
[Bug] oracle连接chen组件查询到数据，但是页面上无法正常显示数据内容

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#11420]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.5.3

**浏览器版本**

**Bug 描述**
如下图，通过oracle连接web gui后，执行查询命令后，查询结果是有两条数据的，但是没有显示具体的数据内容，而是一片空白
![image](https://github.com/jumpserver/jumpserver/assets/47737772/859bf86f-f2bd-4324-a3eb-7f6fbdd03507)

**Comment by BaiJiangJie** [comment]
怎么复现一下呢？

**Comment by jym503558564** [comment]
在我们当前环境无法复现，测试版本：v3.6.4，oracle12c。需提供一下oracle版本？
