### ISSUE TITLE
[Bug] 在使用web GUI执行create/grant SQL时，语句中包含 `（反引号）会报语法错误，而使用 ' （单引号）则正常。

### ISSUE THREAD

**Issue by jibill** [jumpserver/jumpserver#11429]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
chrome or firefox

**Bug 描述**
v3.6.1，在使用web GUI执行这create/grant SQL的时候，上面的语句中包含 `（反引号）会报语法错误
而改成下面的语句，使用 ' （单引号）则正常。
<img width="1125" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/47b292cc-082b-4333-8564-33169263b26f">

在CLI中是正常使用反引号的，但是在GUI中就无法使用。
<img width="920" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/32b3ed52-5384-4eb7-a2ed-a487f7718614">

**Bug 重现步骤(有截图更好)**
1. 执行这2条SQL
```sql
-- 报错：Error while parsing: syntax error. pos 41, line 1, column 30, token VARIANT 
create user `admin`@`10.10.%` identified by 'admin@Ab123';
grant create, drop, REFERENCES, select, insert, update, delete on `DB`.* to `admin`@`10.10.%`;
flush privileges;

-- 正常
create user 'admin'@'10.10.%' identified by 'admin@Ab123';
grant create, drop, REFERENCES, select, insert, update, delete on `DB`.* to 'admin'@'10.10.%';
flush privileges;
```

**Comment by jibill** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/42427328/a219ccc8-8709-4abc-a7a0-1bb967ed6397)
<img width="711" alt="image" src="https://github.com/jumpserver/jumpserver/assets/42427328/e20cc300-714c-4b16-a0c7-92cc8175416c">

大佬们，下个版本能不能先把web CLI还给我们，把web GUI优化完了再移除啊

**Comment by ibuler** [comment]
@jibill 好吧，下个版本还原回来

**Comment by LeeEirc** [comment]
v3.7.0 已经恢复 web cli 连接。
