### ISSUE TITLE
[Bug] sftp删除的目录和目录里的文件不能下载

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11422]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.2

**浏览器版本**

**Bug 描述**
sftp删除的目录和目录里的文件不能在审计-sftp传输里下载，目录里文件加起来不超过100M
![image](https://github.com/jumpserver/jumpserver/assets/44529247/9af02dc6-2be3-4014-a2ea-1fb580b1a046)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by LeeEirc** [comment]
删除的文件不支持下载，目前仅上传下载的文件审计日志支持下载审计 。
