### ISSUE TITLE
[Feature] 云同步-同步策略-策略规则和策略动作选项优化建议

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#11423]
**请描述您的需求或者改进建议.**

描述：云同步-同步策略-策略规则和策略动作中的选项，选中之后只能更换，不能取消。
场景：一般在设置完策略之后会检查，不小心点击选项后无法取消，后面的字段又会显示“ 这个字段是必填项” ，会影响用户的判断；
![image](https://github.com/jumpserver/jumpserver/assets/43403764/a78d0e8a-c84e-48ee-9e94-aecdfac2e46e)
![image](https://github.com/jumpserver/jumpserver/assets/43403764/023f1144-0c8a-4707-b9ed-aaeb008d38d5)

建议：可以考虑加一个取消的按钮，如下：
![image](https://github.com/jumpserver/jumpserver/assets/43403764/cd246614-af7a-443a-827b-cf434d99218d)

**Comment by BaiJiangJie** [comment]
没理解什么意思。

**Comment by BaiJiangJie** [comment]
描述：云同步-同步策略-策略规则和策略动作中的选项，选中之后只能更换，不能取消。

这个“取消”指的是什么？

**Comment by BaiJiangJie** [comment]
那个本身就是一个普通的文本输入框，不用取消操作，全选删除就可以了。

**Comment by LinuxLeader** [comment]
好的，明白了
