### ISSUE TITLE
部署系统Windows问题

### ISSUE THREAD

**Issue by virtual163** [jumpserver/jumpserver#1142]
[简述你的问题]
登录windows系统没有问题，可是在在线会话和历史会话里发现不了windows的系统登录信息，也就是无法对windows系统做会话记录和录像
##### 使用版本
[请提供你使用的Jumpserver版本 v1.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
暂时还不支持windows下的会话记录和硬件信息刷新，请等待功能更新。

**Comment by cxzcyy** [comment]
期待功能更新吧

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
