### ISSUE TITLE
[Feature] 分享资产时临时账号

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#11433]
**请描述您的需求或者改进建议.**
有没有可能，在分享资产时，创建有时效的临时账号。
最近公司这边出现过这样的需求，就是有外部人员远程调试内部系统，所以只能手动给他创建一个账号，用完再删除，手动操作比较麻烦，下次调试的时候又要进行相同的操作

**Comment by ibuler** [comment]
不安全，不考虑，为了这点方便，不值得
