### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11434]
**请描述您的需求或者改进建议.**
请更新https://docs.jumpserver.org/zh/master/install/setup_by_lb/
如上的分布式部署的教程
因为按照上面的部署方式那个
![image](https://github.com/jumpserver/jumpserver/assets/70053869/9a9f5aa5-09c2-459f-afa7-ca9f55193c81)
这里怎么配置都不行我是完全按照这个流程部署的 3.5.4之前升级都没有问题 一到3.6.0+版本就不行

**Comment by ibuler** [comment]
报错有没有提示

**Comment by wojiushixiaobai** [comment]
listen jms-web 这个地方的 haproxy 完整截图
另外把 haproxy 的 web 监控页面截图发过来
