### ISSUE TITLE
[Bug] Web终端数据库查询精度丢失

### ISSUE THREAD

**Issue by vastsa** [jumpserver/jumpserver#11436]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
版本:	v3.6.2

**浏览器版本**
Google Chrome
版本 116.0.5845.96（正式版本） (arm64)

**Bug 描述**
通过web终端管理mysql数据库时，雪花ID出现精度丢失

**Bug 重现步骤(有截图更好)**
1.直接通过web终端查询
<img width="420" alt="image" src="https://github.com/jumpserver/jumpserver/assets/48862574/4000a672-85fa-4dc7-adcc-341593179764">
2.通过本地Navicat查询
<img width="429" alt="image" src="https://github.com/jumpserver/jumpserver/assets/48862574/5a473084-fd5c-41ef-a451-fbb11cf0a8ec">
3.通过看ws记录发现，传输过来的时候就已经丢失了
<img width="684" alt="image" src="https://github.com/jumpserver/jumpserver/assets/48862574/875a84ed-1af0-4ae3-be7f-f27654a2244d">

**Comment by ibuler** [comment]
@Aaron3S
