### ISSUE TITLE
jumpserver 上传文件限制500MB

### ISSUE THREAD

**Issue by qw4285632q** [jumpserver/jumpserver#11438]
jumpserver3.5 版本  centos7.9服务器安装rz工具进行文件上传显示如下报错 
![image](https://github.com/jumpserver/jumpserver/assets/27714601/bf47ef73-6a46-4db7-aef1-cd56b6c121c8)
。单独用xshell登录服务器 使用rz工具不报错，请问这个参数是在哪里设置的

**Comment by jym503558564** [comment]
rz 和 sz 传输不适合传输大文件，就做了限制。我们研发人员，经过斟酌考虑，一般小文件500M也就够用了。所以就做了这方面的限制。

**Comment by qw4285632q** [comment]
这边有办法开放这个限制吗

**Comment by LeeEirc** [comment]
web 端暂不开放限制，大文件传输还是通过 ssh 或者 sftp 的方式。
