### ISSUE TITLE
[Question] SFTP连接，指定初始目录后，无法回到根目录

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11430]
![image](https://github.com/jumpserver/jumpserver/assets/138869963/79ce2200-cfbe-4caa-a46e-6064a3194109)
在资产平台配置指定初始目录后，通过sftp连接后，无法返回到根目录。
请问这里能否设置，因为用户有常用的home目录，但有时候也需要到根目录的其他目录下进行sftp操作

**Comment by wojiushixiaobai** [comment]
你可以改成 /

**Comment by ibuler** [comment]
根目录就是这么设计的，就是防止切换到别的目录
