### ISSUE TITLE
[Bug] 首次安装失败

### ISSUE THREAD

**Issue by qingyuan0o0** [jumpserver/jumpserver#11437]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
第一次使用v3.4.3的配置文件部署docker失败，mysql的容器启动失败
第二次使用v3.6.2的在线安装一键执行，部署失败

**浏览器版本**
没有使用浏览器访问

**Bug 描述**
在容器下载完成后
>>> Install and Configure JumpServer
1. Configure Private Key
SECRETE_KEY:     YmI2NjRkNTYtMWU2MC00MDFlLTY0NTEtMDVlNGJlMjAyMWVm
BOOTSTRAP_TOKEN: YmI2NjRkNTYtMWU2MC00MDFl
complete

2. Configure Persistent Directory
Do you need custom persistent store, will use the default directory /data/jumpserver? (y/n)  (default n): complete

3. Configure MySQL
Do you want to use external MySQL? (y/n)  (default n): complete

4. Configure Redis
Do you want to use external Redis? (y/n)  (default n): complete

5. Configure External Access
Do you need to customize the JumpServer external port? (y/n)  (default n): complete

6. Init JumpServer Database
Pulling core (jumpserver/core:v3.6.2)...
v3.6.2: Pulling from jumpserver/core
14726c8f7834: Already exists
7d676dc8a994: Pull complete
e9e2f08137fc: Pull complete
6cc9fece80c8: Pull complete
264b6a89a95d: Pull complete
0ac8fb0982a5: Pull complete
c5de88bb6b25: Pull complete
4f4fb700ef54: Pull complete
40ef94697eb5: Pull complete
Digest: sha256:91c737669c9149aa4e2fa3913d4afa4e23496dcbae5ea15cbcf4b24a1707b4b4
Status: Downloaded newer image for jumpserver/core:v3.6.2
Creating jms_redis ... done
Creating jms_mysql ... done

ERROR: for core  Container "081f5f16b7dc" is unhealthy.
ERROR: Encountered errors while bringing up the project.
看报错依旧是jms_mysql没有办法继续
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/18437931/71d20ff2-419f-4dc6-8354-291b8a2e4d48)
这个是3.4.3，使用https://github.com/jumpserver/Dockerfile里面的快速部署，执行到docker exec -i jms_core bash -c './jms upgrade_db'报错
2.使用官方网站的curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
执行后运行到就卡住不动了
![image](https://github.com/jumpserver/jumpserver/assets/18437931/c778ef21-3e26-46bc-92fd-b5e475049c89)

**Comment by wojiushixiaobai** [comment]
卸载后重新安装，出现此问题的大概率原因是由于你的 mysql 持久化数据库认证密码不正确

你可以根据 mysql 日志进行定位，或者使用外置数据库解决。
