### ISSUE TITLE
提供消息确认功能

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#11444]
**请描述您的需求或者改进建议.**
是不是可以给管理员一个消息制定的权限。
可以定义弹出一条消息，让每一位之后 成功登录系统的人 每次/一次 （可定义，就跟好多网站都老是做cookie弹窗提醒一样），点击确认后才才开始使用系统。

最好还能支持实时消息发送，譬如管理员定制一条实时消息“系统将在*分钟后重启应用，请大家..."
所有在线用户在弹窗都能收到该消息。

这样我可以 提醒用户多长时间要更新密码、多少天至少登录一次系统否则用户被停用等等。

**Comment by ryswork1993** [comment]
不是有公告功能吗   系统设置-功能设置

**Comment by ibuler** [comment]
已有公告，暂时不考虑

**Comment by BaiJiangJie** [comment]
<img width="2486" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/751104ea-688e-481b-94dd-9279f15fb76b">
<img width="1236" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a62eced4-822a-44a0-83c5-2f988182df81">
