### ISSUE TITLE
[Question] v2升级v3出现core api500问题

### ISSUE THREAD

**Issue by l1422586361** [jumpserver/jumpserver#11446]
**请描述您的问题.**

- 版本升级情况为，v2.22 -> v3.6.2，使用的docker-compose部署方式
- 升级步骤为
> - docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose-init-db.yml up -d
> - docker exec -i jms_core bash -c './jms upgrade_db' [已有旧数据的情况下升级]
> - docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml up -d
- 具体问题：在使用web窗口进行服务器连接时，弹出报错窗口
![image](https://github.com/jumpserver/jumpserver/assets/32669129/f7ddf262-75e7-4d0d-8da5-b6905db75dfc)

- 后续测试：在使用空白目录进行纯净安装的情况下，可以正常连接到资产
- 寻求帮助：
> - 如何正常从v2.22升级到v3.6.2，我需要对我的升级步骤做什么改进？
> - 是否有比较全面的将2.22的旧数据导出导入到v3.6.2的空白环境里的解决方案，我查看了v2.22的导出文件与v3.6.2的导入模板，发现有很大的差别，在实际导入过程中，没有一项成功的记录

希望能得到解答，感谢！

**Comment by maninhill** [comment]
建议先升级到 v2.28，然后再升级到 v3。

**Comment by l1422586361** [comment]
不好意思，后面测试发现ssh使用密码连接服务器可以正常连了，但ssh使用公钥连接服务器提示认证失败，想问下这个是什么问题？

**Comment by BaiJiangJie** [comment]
看看报错提示什么？

**Comment by LeeEirc** [comment]
ssh 登陆需要使用对应的私钥。有问题再打开。
