### ISSUE TITLE
[Bug] API创建Host的时候报错

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#11448]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.2

**浏览器版本**
chrome 116.0.5845.96

**Bug 描述**
使用API创建host
```shell
curl \
 -H 'accept: application/json' \
 -H 'Authorization: Token aaaaaaaaaaa' \
 -H 'Content-Type: application/json' -X POST http://localhost:82/api/v1/assets/hosts/ \
 -d '{"name":"abcd","address":"10.11.12.13","platform":{"id":1,"name":"Linux"},"protocols":[{"name":"ssh","port":22}],"is_active":true,"nodes":["36d13c16-db2a-4814-8d15-2480d9a97c87"],"accounts":[{"id":"27a68746-b2ee-48ce-8d5c-72096b0c2d57","name":"root","username":"root","version":0,"secret_type":"ssh_key","privileged":false,"is_active":true,"push_now":false,"template":true}]}'
```

服务器返回：
```json
{"error": "Server internal error"}
```

创建Host的时候，使用了账号模板
![image](https://github.com/jumpserver/jumpserver/assets/2853517/8268ff39-7b93-44b2-9547-a605c46128da)

jumpserver日志：

```text
2023-08-29 12:39:22 [log ERROR] Internal Server Error: /api/v1/assets/hosts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 159, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.11/site-packages/drf_writable_nested/mixins.py", line 233, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 297, in create
    self.accounts_create(self._accounts, instance)
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 289, in accounts_create
    s = AssetAccountSerializer(data=accounts_data, many=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/common/serializers/mixin.py", line 95, in many_init
    return super(BulkSerializerMixin, cls).many_init(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 47, in __init__
    self.set_initial_value()
  File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 61, in set_initial_value
    self.from_template_if_need(data)
  File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 95, in from_template_if_need
    field.name for field in template._meta.fields
                            ^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute '_meta'
```

以前v2是使用/api/v1/assets/assets/ 的API，
现在v3使用是/api/v1/assets/hosts/ 的API。
在刚升级到v3时，这个curl执行是没问题的，不知道升级到哪个版本后，就不能创建Host了。

**Bug 重现步骤(有截图更好)**
1. 使用API创建HOST

**Comment by wojiushixiaobai** [comment]
在开发者工具栏里面看提交的表单，自己对比下是否缺少某些参数

**Comment by nangongchengfeng** [comment]
楼主根据 你参数，我进行调试，好像缺少参数。目前也在研究最新版 API 添加 主机 的接口 和 Python 代码
![image](https://github.com/jumpserver/jumpserver/assets/46562911/9196d8c0-74ff-4128-b40e-974df8892d80)

**Comment by nangongchengfeng** [comment]
> 在开发者工具栏里面看提交的表单，自己对比下是否缺少某些参数

您好，能否提供一个demo 测试一下。我这边测试是 500 的错误
```python
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "address": "string",
  "comment": "string",
  "domain": "string",
  "platform": "string",
  "nodes": [],
  "labels": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "value": "string"
    }
  ],
  "protocols": [],
  "nodes_display": [
    "string"
  ],
  "accounts": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "username": "string",
      "secret": "string",
      "passphrase": "string",
      "created_by": "string",
      "comment": "string",
      "su_from": "string",
      "asset": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "version": 0,
      "source_id": "string",
      "template": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "params": {},
      "privileged": false,
      "is_active": true,
      "push_now": false,
      "date_created": "2023-08-29T11:43:57.479Z",
      "date_updated": "2023-08-29T11:43:57.479Z"
    }
  ],
  "auto_config": "string",
  "created_by": "string",
  "gathered_info": {},
  "org_id": "00000000-0000-0000-0000-000000000004",
  "org_name": "string",
  "spec_info": "string",
  "is_active": true,
  "date_verified": "2023-08-29T11:43:57.479Z",
  "date_created": "2023-08-29T11:43:57.480Z"
}
```
![image](https://github.com/jumpserver/jumpserver/assets/46562911/c7e77f60-e9cb-4b8d-bfc8-7665ffdb5a23)

**Comment by nangongchengfeng** [comment]
> **JumpServer 版本( v2.28 之前的版本不再支持 )** v3.6.2
> 
> **浏览器版本** chrome 116.0.5845.96
> 
> **Bug 描述** 使用API创建host
> 
> ```shell
> curl \
>  -H 'accept: application/json' \
>  -H 'Authorization: Token aaaaaaaaaaa' \
>  -H 'Content-Type: application/json' -X POST http://localhost:82/api/v1/assets/hosts/ \
>  -d '{"name":"abcd","address":"10.11.12.13","platform":{"id":1,"name":"Linux"},"protocols":[{"name":"ssh","port":22}],"is_active":true,"nodes":["36d13c16-db2a-4814-8d15-2480d9a97c87"],"accounts":[{"id":"27a68746-b2ee-48ce-8d5c-72096b0c2d57","name":"root","username":"root","version":0,"secret_type":"ssh_key","privileged":false,"is_active":true,"push_now":false,"template":true}]}'
> ```
> 
> 服务器返回：
> 
> ```json
> {"error": "Server internal error"}
> ```
> 
> 创建Host的时候，使用了账号模板 ![image](https://user-images.githubusercontent.com/2853517/263903538-8268ff39-7b93-44b2-9547-a605c46128da.png)
> 
> jumpserver日志：
> 
> ```
> 2023-08-29 12:39:22 [log ERROR] Internal Server Error: /api/v1/assets/hosts/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
>     raise exc_info[1]
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
>     response = await get_response(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
>     raise exc_info[1]
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
>     response = await wrapped_callback(
>                ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
>     ret: _R = await loop.run_in_executor(
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
>     return func(*args, **kwds)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
>     return view_func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
>     return self.dispatch(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 159, in create
>     return super().create(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
>     return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
>     self.perform_create(serializer)
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
>     serializer.save()
>   File "/usr/local/lib/python3.11/site-packages/drf_writable_nested/mixins.py", line 233, in save
>     return super(BaseNestedModelSerializer, self).save(**kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
>     self.instance = self.create(validated_data)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
>     return func(*args, **kwds)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 297, in create
>     self.accounts_create(self._accounts, instance)
>   File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 289, in accounts_create
>     s = AssetAccountSerializer(data=accounts_data, many=True)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 122, in __new__
>     return cls.many_init(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/jumpserver/apps/common/serializers/mixin.py", line 95, in many_init
>     return super(BulkSerializerMixin, cls).many_init(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 149, in many_init
>     child_serializer = cls(*args, **kwargs)
>                        ^^^^^^^^^^^^^^^^^^^^
>   File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 47, in __init__
>     self.set_initial_value()
>   File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 61, in set_initial_value
>     self.from_template_if_need(data)
>   File "/opt/jumpserver/apps/accounts/serializers/account/account.py", line 95, in from_template_if_need
>     field.name for field in template._meta.fields
>                             ^^^^^^^^^^^^^^
> AttributeError: 'bool' object has no attribute '_meta'
> ```
> 
> 以前v2是使用/api/v1/assets/assets/ 的API， 现在v3使用是/api/v1/assets/hosts/ 的API。 在刚升级到v3时，这个curl执行是没问题的，不知道升级到哪个版本后，就不能创建Host了。
> 
> **Bug 重现步骤(有截图更好)**
> 
> 1. 使用API创建HOST

```bash
{
	"name": "k8s-master01",
	"address": "192.168.102.30",
	"platform": "1",
	"protocols": [{
      
        "name": "ssh",
        "port": 22
      },
      {
        "name": "sftp",
        "port": 22
      }],
	  "nodes_display": [
    "/Default/app"
  ],
   "nodes": [
      {
        "id": "61838d4f-72b2-4132-858b-94ce33fb643a",
        "name": "app"
      }
    ],
	"is_active": true,
	"nodes": ["2624f4b8-cf58-47a1-aafa-5a35d9fb3095"],
	"accounts": [{
		"name": "root(免密码用户)",
		"username": "root",
		"template": "60b11033-a6e1-467d-8388-68a0e64134ff",
		"is_active": true
	}]
}
```
按照 这个数据 来，目前已经测试成功。这里特别注意一下："platform" 这个参数，后面是 string 类型的数字 “1”
![image](https://github.com/jumpserver/jumpserver/assets/46562911/d0764ee2-ca9f-49cd-9b7c-ce0fdcfda967)

![image](https://github.com/jumpserver/jumpserver/assets/46562911/e5028777-7bb7-4a3f-bd0c-f63e923aad44)

**Comment by nangongchengfeng** [comment]
@yuanhaoliang  关闭吧

**Comment by yuanhaoliang** [comment]
试出来了，有两个问题
- platform: "1"
- accounts里的template的id字段，应该为template

**Comment by zhuw0312** [comment]
{
  "nodes": [
    "期望为一个包含物件的列表，得到的类型是“str”。"
  ]
}

请求参数
{
  "name": "10.114.24.78",
  "address": "10.114.24.78",
  "platform": "1",
  "nodes": "1f7b62c2-1011-4f7c-b6f9-bbf53378d8e8",
  "protocols": [{"name": "ssh", "port": 62222}],
  "accounts": [
      {"name":"root(Gl1qX01)",
       "username": "root",
       "template":"863f8a1e-28f6-47fd-a5d8-def39f5599d7",
       "privileged": true,
       "is_active": true}],
  "is_active": true
}
能帮忙看下么？
