### ISSUE TITLE
[Question] What happens to remote Web function when RDS stops working

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11445]
Hi,

When deploy "Remote hosts" to can use remote Web, I see RDS installed with `TASK [Install RDS-RD-Server (RDS)]`.
![image](https://github.com/jumpserver/jumpserver/assets/75791054/73b1fd40-0e28-43e9-aa8e-227edaa66501)

Then remote this server, I get a notification that `Remote Desktop licensing mode is not configured` and `Remote Desktop Services will stop working in xxx days`
![image](https://github.com/jumpserver/jumpserver/assets/75791054/e9c87599-8c80-4dda-bc3e-5e84bf58428e)

What happens when it stops working?
Can I remote to server and use remote web funtion?
If no, how do i renew it?

Thank you

**Comment by LeeEirc** [comment]
The remote Web connection based on the Microsoft RemoteApp on Windows Server, as we called it "Remote host".

If you want to use the full feature of the RemoteApp, you need to purchase the  [RDS license](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license) from Microsoft.
If you do not have the license, you may encounter the limitation.

**Comment by tsukiazuma** [comment]
Thanks for taking care of my problem.

But RDS will automatically install when I deploy Applets -> Remote hosts.
![image](https://github.com/jumpserver/jumpserver/assets/75791054/93822446-0097-4ca6-a623-015db463ef5b)

And according to your feedback, I can't use remote Web when it stop? If yes, there is a way to renew it or have to do the deployment on another server, this is too inconvenient.

**Comment by LeeEirc** [comment]
Yes, you could not use the remote Web as the RDS license expired. It is better to purchase the RDS license. 
You could reset the remote host RDS license manually, but it is not recommended.

**Comment by tsukiazuma** [comment]
Oh, thank you so much

**Comment by LeeEirc** [comment]
Welcome
