### ISSUE TITLE
[Bug] 用户拒绝命令的邮件主题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11449]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.2

**浏览器版本**

**Bug 描述**

拒绝命令的邮件主题
![image](https://github.com/jumpserver/jumpserver/assets/44529247/91644047-b5d5-4c82-a2ea-128329e071b7)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ibuler** [comment]
收到

**Comment by ibuler** [comment]
是不是设置了主题前缀 ？再系统设置中设置的

**Comment by ryswork1993** [comment]
这是安装之后的默认信息，我没设置过，我感觉现在的禁止命令告警和改密邮件公用的一个主题

**Comment by feng626** [comment]
去系统设置 消息设置里的邮件设置 看看 前缀是什么

**Comment by ryswork1993** [comment]
> 去系统设置 消息设置里的邮件设置 看看 前缀是什么

![image](https://github.com/jumpserver/jumpserver/assets/44529247/1c79c662-4afd-4e59-bca6-a596e211cf17)

**Comment by feng626** [comment]
改一下前缀吧
