### ISSUE TITLE
在建资产时，IP项只能用IP地址方式，不支持域名添加

### ISSUE THREAD

**Issue by cxzcyy** [jumpserver/jumpserver#1144]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
jumpserver1.0

##### 问题复现步骤
在建资产时，IP项只能用IP地址方式，不支持域名添加，这样的话，不太灵活，因为在实际生产用，IP有时会变化

##### 其他

[注:] 完成后请关闭 issue

**Comment by clangcn** [comment]
顶一下，刚想提交这个问题，发现有了，希望作者能加入域名

**Comment by ibuler** [comment]
资产管理这里不仅仅是设置连接服务器，更重要的是，我们想真正作为资产的管理者，ip是一个资产不可缺少的一部分，一个点也不能少

**Comment by boy6585948** [comment]
IP和域名两个都支持不是更好么，而且很多情况下本身简化管理，更换IP的时候就会自动更新对应的域名解析。
