### ISSUE TITLE
[Bug] 对接CAS后，登录的时候一直在认证页面循环

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#11451]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.2

**浏览器版本**
chrome 115.0.5790.114

**Bug 描述**
对接CAS后，登录的时候一直在认证页面循环，使用v3.3版本正常
![image](https://github.com/jumpserver/jumpserver/assets/104493699/c36eab34-437f-4609-9278-f4d4715ecef3)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by hhdnxx** [comment]
自V2.2.6至V3.5.4所有版本对接CAS均正常，目前发现V3.6.0，V3.6.1，V3.6.2对接后均出现楼主提报的BUG

**Comment by ibuler** [comment]
cas 问题找到了，依赖的一个库改了属性，https://github.com/django-cas-ng/django-cas-ng/issues/284，所以 v3.6 中需要 系统设置中 - 修改 cas   uid -> cas:user

**Comment by ibuler** [comment]
@hhdnxx

**Comment by ibuler** [comment]
@shimengqiao

**Comment by hhdnxx** [comment]
收到，谢谢

**Comment by shimengqiao** [comment]
谢谢，验证可以

**Comment by shimengqiao** [comment]
关闭

**Comment by cheetah747** [comment]
我再补充一点，可以留意一下自己服务器上的时间是否准确。
我的情况是系统时间不准，而我浑然不知，导致CAS登录无限循环。后来的人可以参考一下。
