### ISSUE TITLE
jms-celery无法正常启动

### ISSUE THREAD

**Issue by yilingyi** [jumpserver/jumpserver#11457]
**我在k8s上部署jumpserver 3.6.1时遇到celery一直在重启，且提示启动失败**
![image](https://github.com/jumpserver/jumpserver/assets/36027338/b90a5579-67a9-47eb-9d0c-d9f5235f2da4)

**Comment by BaiJiangJie** [comment]
看一下健康检测的逻辑。

**Comment by wojiushixiaobai** [comment]
https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/templates/celery/deployment-celery.yaml#L99

试试将 `livenessProbe` 和 `readinessProbe` 的 `initialDelaySeconds` 时间改长，如果依旧不行，那可能是组件真的有问题。另外组件不能使用 `readonly` 方式运行，文件会写入 `/tmp`

**Comment by yilingyi** [comment]
> https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/templates/celery/deployment-celery.yaml#L99
> 
> 试试将 `livenessProbe` 和 `readinessProbe` 的 `initialDelaySeconds` 时间改长，如果依旧不行，那可能是组件真的有问题。另外组件不能使用 `readonly` 方式运行，文件会写入 `/tmp`

谢谢，已经解决了
