### ISSUE TITLE
[Question] 远程应用Web代填脚本如何设置延时时间

### ISSUE THREAD

**Issue by dfdf10086** [jumpserver/jumpserver#11454]
**请描述您的问题.**
有些网站在页面未加载完成时运行脚本会导致无法找到该元素，如何延时执行脚本

**Comment by LeeEirc** [comment]
可以通过编写脚本的方式增加 sleep 指令，例如延迟 5s 格式如下:

```
  {
    "step": 3,
    "value": "",
    "target": "5", 
    "command": "sleep"
  }
```
脚本介绍参考 [JumpServer远程应用Web代填方式介绍](https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f)
