### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nooneaaaa** [jumpserver/jumpserver#11458]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
Google chrome
版本 116.0.5845.111（正式版本） （64 位）

**Bug 描述**
**Bug 重现步骤(有截图更好)**
1.启动一开始是好的，几分钟后，就开始报 redis.exceptions.ConnectionError: Too many connections
就算啥都没操作也会这样。

![image](https://github.com/jumpserver/jumpserver/assets/13516536/3b26e350-7138-4e3e-9320-66b64af0f098)

**Comment by ibuler** [comment]
redis 连接数太少了

**Comment by nooneaaaa** [comment]
首次试用，没有仔细阅读文档，自省中。
redis版本升到6+就好了。
