### ISSUE TITLE
[Feature] 关于资产登录方式的选定

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11450]
**请描述您的需求或者改进建议.**
版本V3.6.1
用户在访问他的资产的时候，默认是用“Web CLI”；
如果用户想要像在本地打开plsql登录数据库一样，去登录数据库资产，那么他还需要去修改luna页面的“设置”--“图形化”--“客户端”，然后右键点击资产，再点击“远程应用”，最后选中想要的登录工具如“navicat”。
对用户来说，这种操作是很繁琐的，而且大部分用户最开始都不知道需要这么操作，然后就会提出质疑或投诉。
希望能在管理员设置页面那里，提供一个全局设定默认值的地方，允许管理员根据用户使用场景进行指定，这样能很好地提升用户体验。

**Comment by ibuler** [comment]
收到，想想办法

**Comment by BaiJiangJie** [comment]
正常情况，图形化里面，全局修指定一下 web 或者 客户端 就行吧？ @khy2021 

如果要用远程应用，应该都会使用统一的 web 或者 客户端。

难道还有 A 资产使用 Web 远程应用，B 资产使用 客户端远程应用的场景？

**Comment by khy2021** [comment]
> 正常情况，图形化里面，全局修指定一下 web 或者 客户端 就行吧？ @khy2021
> 
> 如果要用远程应用，应该都会使用统一的 web 或者 客户端。
> 
> 难道还有 A 资产使用 Web 远程应用，B 资产使用 客户端远程应用的场景？

不是这个意思，我是指的，能否让管理员来设定，让用户访问数据库资产的时候，默认就使用“远程应用”--“Navicat16”，“远程应用连接方式”这里 默认使用“客户端”呢？因为涉及到一些软件的license以及其它因素。

**Comment by ibuler** [comment]
那个是由 Remote app 决定的，它是客户端就是客户端，是 web 就是 web，比如 VMware 的 vsphere

**Comment by ibuler** [comment]
v3.7 高级选项新增了连接方式

![image](https://github.com/jumpserver/jumpserver/assets/17382885/3d85e8a6-2eac-4f41-9d20-4deb378efa0b)
