### ISSUE TITLE
[Bug] Cerely 任务卡住占用内存

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#11453]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

 V3.4.2
**浏览器版本**

**Bug 描述**
  执行账号可用性探测任务，ansible任务卡住不回收，导致内存增加，kill掉后内存恢复

**Bug 重现步骤(有截图更好)**
1.

![image](https://github.com/jumpserver/jumpserver/assets/106153788/d97de604-cf57-462b-b518-529d0efa1180)

2.
![image](https://github.com/jumpserver/jumpserver/assets/106153788/45c1b887-4b1c-47a3-adc2-03d7448340e6)
3.

**Comment by BaiJiangJie** [comment]
建议升级到最新版本使用，中间版本有优化过任务执行的逻辑。
