### ISSUE TITLE
[Feature] 支持 elasticsearch 8

### ISSUE THREAD

**Issue by jializhu** [jumpserver/jumpserver#11466]
目前 elasticsearch 最高版本是 v8.9，自 2022 年 2 月推出 8 以后，陆续企业做了升级。
现状 ：jumpserver v3.6.1 能支持到 Elasticsearch 7，
问题：请问近 jumpserver 近 2 个版本会考虑支持 elasticsearch 8 吗？还是说会等到 elasticsearch 9 未来出来后才会支持 8 呢？如果大概有个支持的时间就更好了。感谢！

**Comment by BaiJiangJie** [comment]
可以考虑，暂时计划在 v3.9（11 月）的版本支持。

**Comment by ibuler** [comment]
等待新版本支持，issue 积攒太多，暂时关闭，如果到时没有支持，请再打开

**Comment by jializhu** [comment]
收到，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月4日(周一) 下午2:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Feature] 支持 elasticsearch 8 (Issue #11466)




 
Closed #11466 as completed.

**Comment by jializhu** [comment]
收到，非常感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月31日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Feature] 支持 elasticsearch 8 (Issue #11466)




 
可以考虑，暂时计划在 v3.9（11 月）的版本支持。

**Comment by HanadaLee** [comment]
3.9.1版本发布了，测试发现没有上线这个需求

> 可以考虑，暂时计划在 v3.9（11 月）的版本支持 es8。

**Comment by Songxwn** [comment]
3.10还没支持
