### ISSUE TITLE
[Feature] 作业管理任务无法停止

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#11460]
**请描述您的需求或者改进建议.**
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/946eb554-a241-47e2-8547-38a0a0e16b0c)
作业管理的任务执行后没有终止按钮，如果cv错了，或者异常会导致任务一致运行下去，无法停止，重启堡垒机也不行。
这样是不安全，存在风险的，能否加个终止按钮呢？

**Comment by BaiJiangJie** [comment]
使用的是 celery 的异步任务，可能存在多节点执行的情况，没有办法直接终断。

执行的时候可以设置预计的超时时间来控制。

**Comment by Ricardo-X-Chen** [comment]
> 使用的是 celery 的异步任务，可能存在多节点执行的情况，没有办法直接终断。
> 
> 执行的时候可以设置预计的超时时间来控制。也是 Celery 官方比较推荐的方法。

这个超时时间是在哪里设置的 我在flower下设置task的timeout，显示required to enable API without authentication
