### ISSUE TITLE
[Question] MySQL连接参数在哪里加？

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#11471]
**请描述您的问题.**
通过网域连接MySQL Web CLI加载很慢，直连不会，加载表信息数据这么慢嘛？
提示说可以通过添加参数跳过这个加载`-A` 这个参数在哪里加，没找到入口
```
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
```
![image](https://github.com/jumpserver/jumpserver/assets/16077203/0f6f6572-3c46-4fd9-add2-8175205d8d7d)

**Comment by BaiJiangJie** [comment]
< v3.6 版本里可以在连接时的高级选项中设置，>= v3.6 版本中不支持通过 Web CLI 方式连接数据库了。

**Comment by BaiJiangJie** [comment]
设置 `禁用自动补全` 为 `是`。

-A 的参数就这个意义。

<img width="699" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a79010e9-e087-4789-be1d-0329e918cabd">
