### ISSUE TITLE
[Bug] 远程应用调用core失败

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#11479]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.1

**浏览器版本**
Chrome 版本 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
jumpserver是k8s集群部署，打开website通过远程应用打开，报错：Core API调用失败
lion中有找到调用500的错误日志，是从哪里调用的？远程发布机嘛？远程应用win无法直接调用k8s core服务svc地址，这个地址可否单独配置？
在远程发布机配置的是域名
![image](https://github.com/jumpserver/jumpserver/assets/16077203/be03be98-afad-433d-ac0f-ee87e67e0736)

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/16077203/db6dca46-a69b-4dfd-8f50-c579af44774c)
![image](https://github.com/jumpserver/jumpserver/assets/16077203/29ad2447-712c-476d-977d-8389bf414767)

**Comment by BaiJiangJie** [comment]
可以单独配置，就是你截图中的地方。

返回状态码 500 说明可以连接，但是有报错。

这时候需要查看 core 服务的日志。jumpserver.log 或者 gunicorn.log

**Comment by kzcPo** [comment]
> 可以单独配置，就是你截图中的地方。
> 
> 返回状态码 500 说明可以连接，但是有报错。
> 
> 这时候需要查看 core 服务的日志。jumpserver.log 或者 gunicorn.log

已解决，是redis keys的问题

**Comment by kzcPo** [comment]
通过远程应用打开website，一直在loading，这一块怎么排查？
![image](https://github.com/jumpserver/jumpserver/assets/16077203/03564c8e-b8b5-4e79-a37c-69383f7a70dc)

**Comment by LeeEirc** [comment]
应该是你 chrome 代替步骤执行失败了。可以检查下你 web 资产使用的代替类型是否正确填写。

**Comment by ibuler** [comment]
@LeeEirc 超时 30 s，超过 30s 成功与否，都会放开

**Comment by kzcPo** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16077203/545fdbc6-9333-405c-a2e1-6fc79e145a82)
将自动代填改成禁用，还是一样

**Comment by BaiJiangJie** [comment]
v3.7 优化一下代填的处理逻辑。

报错提示出来。@LeeEirc

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11522

**Comment by LeeEirc** [comment]
v3.7.0 已做部分优化
