### ISSUE TITLE
[Bug] 升级到3.6.2后删除用户报错

### ISSUE THREAD

**Issue by todest** [jumpserver/jumpserver#11475]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.2

**Bug 描述**
升级到3.6.2后删除用户报错，是否jms_oidc_rp_oidcuser表不再使用了？
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`jumpserver`.`jms_oidc_rp_oidcuser`, CONSTRAINT `jms_oidc_rp_oidcuser_user_id_92db75c5_fk_users_user_id` FOREIGN KEY (`user_id`) REFERENCES `users_user` (`id`))')

**Comment by BaiJiangJie** [comment]
对，这个表不再使用了，由于一些历史原因这张表暂时还不能删除。

手动清空一下这样表就能正常删除用户了。

**Comment by todest** [comment]
> 对，这个表不再使用了，由于一些历史原因这张表暂时还不能删除。
> 
> 手动清空一下这样表应该就能正常删除用户了。

好的，谢谢
