### ISSUE TITLE
[Question] 您好，想问一下，JumpServer开启CAS登录模式后，如何获取到具体用户的信息。

### ISSUE THREAD

**Issue by LPL-hacker** [jumpserver/jumpserver#11473]
**请描述您的问题.**
认证走的CAS Server，那么JumpServer是如何知道现在是哪个用户登录的呢？

**Comment by BaiJiangJie** [comment]
根据用户名判断的。

**Comment by ibuler** [comment]
cas server 会返回其中的信息  cas:user   

<img width="1158" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17382885/00d36907-5369-4bef-b277-a7adddcfebc3">
