### ISSUE TITLE
[Question] 无法添加redis客户端连接

### ISSUE THREAD

**Issue by evirts** [jumpserver/jumpserver#11470]
**请描述您的问题.**
jumpserver版本3.3.1

资产详细配置如下：
![image](https://github.com/jumpserver/jumpserver/assets/10336478/09eb7849-5043-4001-b632-6aa12b49e5a3)

账号配置，redis没有账号只配置了密码
![image](https://github.com/jumpserver/jumpserver/assets/10336478/d6ae343c-b924-4e78-abe0-205181ad820e)

资产授权信息
![image](https://github.com/jumpserver/jumpserver/assets/10336478/e9d91871-9b97-43c9-9288-4ad6b6ae67f0)

登录redis报错
![a8f6d8a5173ae5f6ac97b64813ac745](https://github.com/jumpserver/jumpserver/assets/10336478/b1e4a0bd-7fe0-444d-8592-33e835e82b77)
在jumpserver上可以telnet通redis，在core容器内也能telnet通

**Comment by BaiJiangJie** [comment]
系统平台改一下，不用 Redis6+，使用 Redis。

**Comment by evirts** [comment]
> 系统平台改一下，不用 Redis6+，使用 Redis。

是的，改成redis就正常了
