### ISSUE TITLE
[Question] 关于使用ReplicaSet的mongoDB数据库问题

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11477]
**请描述您的问题.**
当前版本3.6.1，有的MongoDB数据库，启用了ReplicaSet和SSL，配置完成后无法登录成功。
请问要如何配置数据库，使之能成功登录呢？

**Comment by BaiJiangJie** [comment]
是通过什么方式连接的？

数据库配置 和 错误日志，详细情况描述一下。
