### ISSUE TITLE
使用rz上传文件185m卡死jumpserver客户端[Bug] 

### ISSUE THREAD

**Issue by wpwwwwang** [jumpserver/jumpserver#11485]
**JumpServer 版本( v3..6.1之前的版本不再支持 )**

**浏览器版本**
116.0.5845.112（正式版本） 

**Bug 描述**
上传185m文件会卡死客户端，ctrl+c 也无法中断，尝试了多次都是乱码

**Bug 重现步骤(有截图更好)**
1.
![aeb5cf985de6208383798b0f0cc39a9](https://github.com/jumpserver/jumpserver/assets/94963350/b387752a-8251-4640-855a-04fbdb18c4d5)

2.
![image](https://github.com/jumpserver/jumpserver/assets/94963350/abacc71f-bf1f-49ea-8b30-4278644ef5dd)

3.

**Comment by ibuler** [comment]
rz 上传大文件有时就是有问题，不太好处理

**Comment by wpwwwwang** [comment]
Web Terminal 使用rz上传文件应该是500m限制，500m内应该正常上传，没有达到预期，还请官方优化优化，带来更好的体验
