### ISSUE TITLE
[Bug] 源码安装文档，安装依赖方式的问题

### ISSUE THREAD

**Issue by GHpassleo1021** [jumpserver/jumpserver#11480]
**JumpServer 版本( v3.6.2 )
**Bug 描述**
从GitHub上下载jumpserver-v3.6.2.tar.gz，发现解压后的目录文件夹requirements下没有requirements.txt这个文件。
而jumpserver官网提到源码部署的时候，core部署当中是需要执行命令pip3 install -r requirements.txt的。
请问这个问题什么时候可以修复？

**Comment by BaiJiangJie** [comment]
修改了安装包的依赖方式，文档暂时没有更新。后面更新一下。

最新版本使用 poetry install 来安装。

**Comment by GHpassleo1021** [comment]
什么时候文档更新？急急急！

**Comment by ibuler** [comment]
> 什么时候文档更新？急急急！

查看 dockerfile 文件

**Comment by ibuler** [comment]
已通知文档组，等待更新

**Comment by GHpassleo1021** [comment]
还有请教个问题：3.6.2源码安装的koko不能再使用koko -d后台运行，也不支持koko -s stop停止了；那么有其他方式让koko可以后台运行吗？我想要使用systemctl来管理koko的启动和停止。

**Comment by LeeEirc** [comment]
> 还有请教个问题：3.6.2源码安装的koko不能再使用koko -d后台运行，也不支持koko -s stop停止了；那么有其他方式让koko可以后台运行吗？我想要使用systemctl来管理koko的启动和停止。

自行添加 service 服务，文件可参考 [koko.service](https://github.com/jumpserver/koko/blob/dev/cmd/koko/koko.service)

**Comment by GHpassleo1021** [comment]
老哥，我提个问题哈，你们文档组的人是不是和运维或者开发不是同一个部门或者同一个人来的？官网文档有那么明显的错误都看不到的吗？
![微信截图_20230907154340](https://github.com/jumpserver/jumpserver/assets/143698761/33942ee2-0aad-40cd-94ee-ea82a29d7492)
![微信截图_20230907154440](https://github.com/jumpserver/jumpserver/assets/143698761/c4cd1a42-a79a-40c0-b2db-683b0f424a2d)
你们这个文档这么不严谨都不查下的吗？

**Comment by gcl1fit2cloud** [comment]
感谢反馈，后续我们调整更新。

**Comment by GHpassleo1021** [comment]
请教下，源码部署3.6.3的时候。core部署这里报错：
![图片](https://github.com/jumpserver/jumpserver/assets/143698761/807f6c98-cecc-4da8-9c5b-b868cae408e6)
是什么原因？怎么解决呢？

**Comment by wojiushixiaobai** [comment]
poetry 相关命令参考其官方文档。poetry 自带虚拟环境管理，你应该正确使用 poetry 配置虚拟环境

**Comment by GHpassleo1021** [comment]
再请教下，源码部署3.6.3的时候，magnus+wisp能够使用systemctl去管理其服务的启动吗？如果可以，怎么使用systemctl进行管理，有参考链接吗？
