### ISSUE TITLE
[Question] v3.6.2 sftp本地客户端无法使用或者能否关闭显示客户端连接sftp

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11489]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/73093158/4833199e-91fc-4fa0-95c4-a7c51606c14a)
1.这个能不能像ssh本地拉起客户端那样关闭不显示这个只让通过jms去连接sftp
2.我使用这个本地客户端连接也无法跳转到本地客户端 配置好了 但是选择客户端的时候没反应

![Uploading 30DF274C-A141-40a2-BCAD-8371D4BF18D2.png…]()

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/8d3f5505-ef0b-4a54-90d0-92987ac188a0)

**Comment by wangmingwang123** [comment]
第2点我重新安装客户端可以拉起本地客户端了  但是为了安全我想要开发连接资产不走本地客户端 不显示sftp 客户端的连接方式

**Comment by ibuler** [comment]
目前社区版，不支持对连接方式限制，企业版支持
