### ISSUE TITLE
[Bug] 使用Web GUI方式连接数据库连接成功后，无法进行查询

### ISSUE THREAD

**Issue by wdwnet** [jumpserver/jumpserver#11486]
**JumpServer 版本：3.6.1**

**浏览器版本：Edge116**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.连接MySQL数据库时，无法使用查询，打开界面时一直转圈
![微信截图_20230901095056](https://github.com/jumpserver/jumpserver/assets/73337439/7854b3ac-4c7b-447d-bf88-c202f8b45c22)

**Comment by BaiJiangJie** [comment]
偶尔出现还是必现？

**Comment by wdwnet** [comment]
> 偶尔出现还是必现？

必现

**Comment by wdwnet** [comment]
> 偶尔出现还是必现？
![1694068414068](https://github.com/jumpserver/jumpserver/assets/73337439/d836b9e1-78e2-41f0-a905-3bb40c82e299)
这个是日志，不知道和这个有没有关系

**Comment by BaiJiangJie** [comment]
应该查看 Chen 组件的日志。

**Comment by BaiJiangJie** [comment]
描述一下如何复现。

使用什么版本的 MySQL？

**Comment by wdwnet** [comment]
> 应该查看 Chen 组件的日志。
>
> 描述一下如何复现。
> 
> 使用什么版本的 MySQL？

![微信截图_20230911130906](https://github.com/jumpserver/jumpserver/assets/73337439/f630b355-8340-4cb6-b738-b090701a4879)
MySQL5.7，复现方法：双击资产进行连接就是这种状态，没有其他步骤

**Comment by xulinde** [comment]
未复现该问题。JumpServer版本：v3.6.4；Mysql版本：5.7.36

**Comment by wdwnet** [comment]
> > 应该查看 Chen 组件的日志。
> > 描述一下如何复现。
> > 使用什么版本的 MySQL？
> 
> ![微信截图_20230911130906](https://user-images.githubusercontent.com/73337439/266913761-f630b355-8340-4cb6-b738-b090701a4879.png) MySQL5.7，复现方法：双击资产进行连接就是这种状态，没有其他步骤

看下这是什么问题

**Comment by wdwnet** [comment]
> 未复现该问题。JumpServer版本：v3.6.4；Mysql版本：5.7.36

上面的错误是怎么回事

**Comment by BaiJiangJie** [comment]
@Aaron3S 看看为什么报错？

**Comment by Aaron3S** [comment]
资产页面有正确填写默认的数据库吗？ 我看报错是在执行 select database() 这个 sql 来获取当前数据库的语句返回了null 导致的

**Comment by wdwnet** [comment]
> 资产页面有正确填写默认的数据库吗？ 我看报错是在执行 select database() 这个 sql 来获取当前数据库的语句返回了null 导致的

确实是这个原因，这个资产是之前版本添加的，默认数据库这个字段应该是后加的吧，我这个资产的默认数据库是空着的
