### ISSUE TITLE
[Question] Connect Error - Upstream error

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11499]
Hi,

I can use Remote Desktop Connection to access the server.
But with Jumpserver, I get error `Connect Error - Upstream error` when doing remote RDP to server.
![image](https://github.com/jumpserver/jumpserver/assets/75791054/9dfaa67c-61b7-4f33-87bd-ce806a210b3e)

How to fix it

Thank you

**Comment by BaiJiangJie** [comment]
Take a look at the log of the lion component.

**Comment by tsukiazuma** [comment]
I don't see anything unusual

![image](https://github.com/jumpserver/jumpserver/assets/75791054/4b8a1d94-3774-4e95-aa72-976aef3900ec)

**Comment by BaiJiangJie** [comment]
使用的什么版本？

**Comment by tsukiazuma** [comment]
I use version 3.3.1

**Comment by BaiJiangJie** [comment]
这个日志好像不是。
查看连接 Windows 资产时那段时间的 Lion 组件日志。

**Comment by tsukiazuma** [comment]
In /opt/jumpserver/lion/data/logs/lion.log, only similar log
I tried to check the log of the day but didn't see any abnormal log

**Comment by LeeEirc** [comment]
Which version of Windows are you using, and how does it differ from other ?

You can change `LOG_LEVEL` to `DEBUG`  in `/opt/jumpserver/config/config.txt` and restart server, then check log file in `lion/data/logs/guacd.log`

 ```
 #/opt/jumpserver/config/config.txt

 LOG_LEVEL=DEBUG

 ```

**Comment by tsukiazuma** [comment]
Oh, I tried uninstall Remote Desktop Service on server and reinstall.
Then, I can remote.

Thanks for the support
