### ISSUE TITLE
[Bug] 无法添加网域网关

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#11497]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.3

**浏览器版本**

**Bug 描述**
/api/v1/assets/gateways/
请求方法:
POST
状态代码:
404 Not Found

{"detail":"系统平台对象不存在","code":"object_does_not_exist"}

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
<img width="749" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/62ceecba-e302-4399-b5af-024804d2ca02">

**Comment by BaiJiangJie** [comment]
POST 提交的参数写上 platform 字段为 Gateway

**Comment by mrbaiwei** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16459219/a9d5febe-cf3f-46cc-84b5-ad7691866321)
![image](https://github.com/jumpserver/jumpserver/assets/16459219/c8e24fc5-db17-4074-8a33-270637cc8055)
查看参数是正确的

**Comment by BaiJiangJie** [comment]
页面操作报错的？

**Comment by mrbaiwei** [comment]
是的，页面上操作的

**Comment by BaiJiangJie** [comment]
在交流群里吗？远程看一下

**Comment by mrbaiwei** [comment]
> 在交流群里吗？远程看一下
已查到原因了，是Gateway的internal必须为1，早期版本时因为要调整协议改过
