### ISSUE TITLE
[Question] 远程应用发布机初次部署报错无法下载python

### ISSUE THREAD

**Issue by 2292527883** [jumpserver/jumpserver#11498]
**请描述您的问题.**
# 远程应用发布机初次部署报错无法下载python

环境：winsever2022 
hyper虚拟机安装的ubuntu sever 22
ubuntu安装完成后直接安装1paner
在1paner应用商店安装jumpsever，设定访问端口为192.168.0.6:400
winsever2022 物理机地址为192.168.0.3

远程应用发布机初次部署报错无法下载python
从网上查到可能是网络问题，但是搜不到解决方案
在对应的winsever文件目录下放置安装包也无效

## 求助如何操作能够使用web资产访问内网管理页面？

错误代码如下：

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [chrome]

TASK [Install RDS-RD-Server (RDS)] *********************************************
ok: [chrome]

TASK [Stop Tinker before install (jumpserver)] *********************************
ok: [chrome]

TASK [Stop Tinkerd before install (jumpserver)] ********************************
ok: [chrome]

TASK [Download JumpServer Tinker installer (jumpserver)] ***********************
ok: [chrome]

TASK [Install JumpServer Tinker (jumpserver)] **********************************
changed: [chrome]

TASK [Set Tinkerd on the global system path (jumpserver)] **********************
ok: [chrome]

TASK [Download python-3.10.8] **************************************************
fatal: [chrome]: FAILED! => {"changed": false, "dest": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\python-3.10.8-amd64.exe", "elapsed": 0.0549973, "msg": "Error downloading 'http://192.168.0.6:400/download/applets/python-3.10.8-amd64.exe' to 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\python-3.10.8-amd64.exe': The remote server returned an error: (404) Not Found.", "status_code": 404, "url": "http://192.168.0.6:400/download/applets/python-3.10.8-amd64.exe"}

PLAY RECAP *********************************************************************
chrome                     : ok=7    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Task terminal.tasks.run_applet_host_deployment[03c3db5f-987e-4187-be59-ca9d0ff105fc] succeeded in 34.217749752000145s: None

**Comment by BaiJiangJie** [comment]
现在 allinone 的镜像还没有适配最新版本，目前建议使用离线包部署。

**Comment by 2292527883** [comment]
离线部署后一切正常，折腾了我三天😂，总之非常感谢。但是web终端的自动填充还是有问题，我再自己折腾折腾吧，总之谢谢
