### ISSUE TITLE
首页：登录记录点头像报404

### ISSUE THREAD

**Issue by jiaxiangkong** [jumpserver/jumpserver#115]
如图：
![e h il_p kq 8 1 u r 9](https://cloud.githubusercontent.com/assets/16377458/13545072/9f251e92-e2bb-11e5-9395-0ed9807bb215.png)

![1zpl_ 5z 39 9f 5ivf tq](https://cloud.githubusercontent.com/assets/16377458/13545074/ac873304-e2bb-11e5-8009-11f9bf5b86f0.jpg)

**Comment by ibuler** [comment]
已修复 close
