### ISSUE TITLE
[Question] 【有偿问题咨询】V3.6.2 JumpServer的web登陆日志无法记录客户端真实IP （用frp转发）

### ISSUE THREAD

**Issue by FIERCELION** [jumpserver/jumpserver#11502]
**我期望解决的问题：**
使用frp转发JumpServer的https流量时，使JumpServer的【网页面板登陆日志】及【其他可能涉及到的日志】记录访客真实的IP，而不是内网ip。

**我期望获得的帮助：**
方式一：
希望懂得如何操作的朋友能提供一个确实可行的教程，它可以是一个链接，可以是一个操作说明。

**方式二：
对于可以远程连接我的ssh直接解决问题的朋友，我愿意付费。(请联系tg@GlobalMarkMonitor)**

**版本**
JumpServer: V3.6.2
Frp: V0.51.3

**我自己的研究：**

我阅读过以下教程

[使用frp内网穿透时获取用户的真实ip](https://www.psay.cn/toss/183.html)

[Nginx如果透过代理获取真实IP地址](https://bloodzer0.github.io/ossa/log_analysis/nginx_realip/)

https://docs.jumpserver.org/zh/v3/installation/proxy/#1-nginx-ssl （阅读部分：如果需要自定义 Nginx 配置文件, 可以参考此处）

为了便于研究，所有的尝试都是在http下进行，即没有SSL。

我尝试过上述教程，frpc.ini在type=tcp的时候可以正常转发流量出来，如果设置type=http时，会提示“This site can’t be example.com refused to connect.”

如果保持type=tcp直接在frpc.ini下增加“proxy_protocol_version = v2”也会有相同的提示。

不知道是NGINX中间件配置出了问题，还是frpc.ini的配置有问题

**Comment by xzqiaochu** [comment]
修改 USB_LB = 0
我通过这种方法解决了，版本 v3.10.10
