### ISSUE TITLE
[Bug] Web 资产选择关联账号后，登录资产时没有同名账号选项

### ISSUE THREAD

**Issue by limin-fit2** [jumpserver/jumpserver#11507]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 
      Version v3.6.3

**浏览器版本**

 版本 116.0.5845.110（正式版本） (arm64)

**Bug 描述**
  
Web 资产选择关联账号后，登录资产时候无法再选择同名账号登录
授权规则都关联了所有账号、同名账号、手动账号、匿名账号

适用场景：
       各个业务系统集成之后，web应用也会使用AD账号进行登录，同时还存在本地最高管理员权限账号

**Bug 重现步骤(有截图更好)**
1. 创建web资产，资产中未关联账号信息，资产登录时候可以选择同名账号登录；
![image](https://github.com/jumpserver/jumpserver/assets/61964761/bbcb2435-7804-401e-ae1e-9abf74bacde0)

2. web资产关联账号信息后，资产登录无法再选择同名账号
![image](https://github.com/jumpserver/jumpserver/assets/61964761/2a8d168a-e61a-4007-8454-6c6afb493ba9)

**Comment by Laplacence** [comment]
你在权限管理-资产授权那块有做配置吗？

**Comment by limin-fit2** [comment]
资产授权的账号都勾选上了
![image](https://github.com/jumpserver/jumpserver/assets/61964761/c85c1027-a6ca-40a6-b6d3-0f8e919d521a)

**Comment by Laplacence** [comment]
分组管理可以使用吗？

**Comment by limin-fit2** [comment]
如果web资产关联账号后，资产授权选择同名账号也无法实现，资产登录时候还是托管账号
![image](https://github.com/jumpserver/jumpserver/assets/61964761/5d0ee8d5-2922-4bf0-af08-7c028ba848d3)
![image](https://github.com/jumpserver/jumpserver/assets/61964761/52fcc1b2-0e40-4d32-bb27-dc895e65de4a)
![image](https://github.com/jumpserver/jumpserver/assets/61964761/d26bd960-89b8-4351-949f-a356fb64f9f3)

**Comment by Laplacence** [comment]
这么离谱…因为我这边有个环境也是类似的场景需要同名+指定账号，windows做了AD域配置，现在还在v2.25.1。
等开发者回复这个issues吧。

**Comment by xulinde** [comment]
资产上有添加过该同名账号，就不会再显示同名账号选项了

**Comment by BaiJiangJie** [comment]
v3.7 版本优化一下。

**Comment by BaiJiangJie** [comment]
v3.7 版本优化方案：

下拉账号列表会显示账号的 Name 和 Username 字段（如果 Name 和 Username 值不相同的时候），如果相同就只显示 Name。

如果同名的账号已经被纳管，那么 `同名账号` 选项依然不显示。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
