### ISSUE TITLE
导入没有网域的资产报错，Cannot assign "''": "Asset.domain" must be a "Domain" instance

### ISSUE THREAD

**Issue by lishuaisky** [jumpserver/jumpserver#1150]
[简述你的问题]

##### 使用版本
[1.0.0-2]

##### 问题复现步骤
1. 修改csv资产文件，没有网域
![image](https://user-images.githubusercontent.com/13938126/38187056-90b8d222-3688-11e8-928f-e9ff36a7c285.png)

2. 进入资产列表，导入资产，报错

![image](https://user-images.githubusercontent.com/13938126/38187132-e4f22dd4-3688-11e8-8636-cc2a30424da7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed

**Comment by ibuler** [comment]
有问题请重新打开issue
