### ISSUE TITLE
[Bug] Chen 查询 bigint 类型的数据精度丢失

### ISSUE THREAD

**Issue by allegrox** [jumpserver/jumpserver#11500]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.2

**浏览器版本**
Google Chrome 116.0.5845.110

**Bug 描述**
使用WebGUI方式连接（MySQL）数据库时，当表字段是bigint类型时，查询结果可能会丢失精度。

**Bug 重现步骤(有截图更好)**
1.分别使用WebCli和WebGUI方式连接同一数据库
2.使用同一语句查询数据：select * from im_message t where t.id IN(452714,452715);
3.返回结果中to_uid字段的值不同，其中WebCli的结果是正确的，详见截图
![截屏2023-09-05 下午12 05 52](https://github.com/jumpserver/jumpserver/assets/13879102/b93d0871-1cd5-4a9d-ab2f-5a6f42043536)
![截屏2023-09-05 下午12 08 03](https://github.com/jumpserver/jumpserver/assets/13879102/5f59e1e2-f1a4-4e7e-97fc-3f0b8fd478bb)

应该是js在处理bigint类型的数据时，丢失了精度。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11436

**Comment by ibuler** [comment]
已修复
