### ISSUE TITLE
[Bug] 无法拉起客户端访问方式

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#11506]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
docker 3.6.2

**浏览器版本**
firefox117.0

****操作系统******
WIN11专业
![`PXW4ME0 8C()SQ{Q_4$8KR](https://github.com/jumpserver/jumpserver/assets/38068938/c112db43-eb53-4f9a-85fe-57abd7c9beea)

**Bug 描述**
无法提起客户端

**Bug 重现步骤(有截图更好)**
1.下载安装最新的客户端
![61ZR_SR5BSV P3C3H9B$ 6K](https://github.com/jumpserver/jumpserver/assets/38068938/2cf8d188-cd3d-4780-8de9-24bf68e599fd)

2.资产右键连接，选择客户端-ssh客户端
![BJMG Q9H_YXB{F03}YXWY7](https://github.com/jumpserver/jumpserver/assets/38068938/262b4815-11a1-4cca-98b6-b1ff9844c73e)

3.报错失败“该文件没有与之关联的应用来执行该操作”
![1693965686204](https://github.com/jumpserver/jumpserver/assets/38068938/5eceab5f-13f1-4344-a413-f949143e60e6)

**Comment by BaiJiangJie** [comment]
@Halo1236

**Comment by Halo1236** [comment]
@sanpichen 
![image](https://github.com/jumpserver/jumpserver/assets/17096387/9cf5dc4c-a4cf-46b0-a0e0-442a874fb4c6)

我这边测试正常拉起，尝试重新下载安装一下
https://github.com/jumpserver/clients/releases/download/v2.0.1/JumpServer-Client-Installer-v2.0.1-x86_64.exe

并且检查一下注册表是否有下列配置
[HKEY_CLASSES_ROOT\jms\shell]
[HKEY_CLASSES_ROOT\jms\shell\open]
[HKEY_CLASSES_ROOT\jms\shell\open\command]
