### ISSUE TITLE
[Question] 点击文件管理功能连接跳转后提示连接被关闭？

### ISSUE THREAD

**Issue by dadiaomengmeizi** [jumpserver/jumpserver#11504]
**请描述您的问题.**
文件管理功能无法正常使用，大家有遇到过吗，连接跳转后提示连接被关闭？
![image](https://github.com/jumpserver/jumpserver/assets/144116443/83335738-b834-4a54-9e11-de861b6fe8c8)

**Comment by BaiJiangJie** [comment]
测试了下没问题。

看下 KoKo 组件的日志有报错吗？

**Comment by dadiaomengmeizi** [comment]
> 测试了下没问题。
> 
> 看下 KoKo 组件的日志有报错吗？

ngnix转发问题导致得，我们有SLB--物理机ng--容器ng   去掉物理机ng就行了
