### ISSUE TITLE
[Feature] RDP登录后显示用户标识

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#11503]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/16459219/1128955a-0459-4658-9bdb-baf143fa975c)
比如显示 XXX-JumpRDP

**Comment by BaiJiangJie** [comment]
这是什么地方的现实？

**Comment by BaiJiangJie** [comment]
<img width="263" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/befc4479-dd2b-4ccc-99bc-7ab67073a4b7">

**Comment by mrbaiwei** [comment]
是任务管理器中的终端的登录标识，不好意思截图没截完整

**Comment by BaiJiangJie** [comment]
还是没找到，完整截一下图。

**Comment by mrbaiwei** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16459219/e73de0ef-c8c7-4136-9728-33a04fd869b4)
这里

**Comment by BaiJiangJie** [comment]
嗯，找到了，用的 Guacamole server 实现的所以要看看 Gaucamole 是否支持修改。

**Comment by BaiJiangJie** [comment]
v3.7 版本会修改为 JumpServer-Lion。

**Comment by mrbaiwei** [comment]
建议是加上跳板机用户名，不过好像名字太长了显示不全，可能要控制下字符长度

**Comment by BaiJiangJie** [comment]
可以考虑。

**Comment by LeeEirc** [comment]
这个标识有 16个字符限制，暂定为 `JumpServer-Lion` ，不显示用户名了。
