### ISSUE TITLE
[Bug] 远程应用Radmin打开后，不会自动代填

### ISSUE THREAD

**Issue by yucai100** [jumpserver/jumpserver#11501]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.1

**浏览器版本**
Firefox 117

**Bug 描述**
在远程应用的[应用市场](https://apps.fit2cloud.com/jumpserver/radmin)下载了Radmin，在发布机上部署、创建资产、权限，然后web终端上进行连接，会弹出对话框，但是不会账号密码代填，大概十几秒后自动注销（3.4和3.5.4上测试会自动注销，3.6.1就停留在对话框的界面上）。
我之后在发布机上改写了app.py和main.py，不进行传参，直接将账号、密码、终端IP和端口都写进去，在发布机上执行正常，但是运行远程应用，依然不会代填。然后我又改写app.py，让程序打开Radmin Viewer窗口，点击连接图标，弹出“联机至”对话框，在发布机上执行正常，在远程应用上只会出现Radmin Viewer窗口，后续不执行任何操作。后来，我安装了pyautogui的库，用pyautogui.write 填上用户名和密码，在远程应用能够正常执行。

**Bug 重现步骤(有截图更好)**
1. 安装应用市场里的radmin，打开远程应用
![图片](https://github.com/jumpserver/jumpserver/assets/26432807/d6624d73-7866-444b-aadb-c1b9319cb4b4)

2. 我改写app.py和main.py，让其弹出“联机至”对话框，不会弹出
![屏幕截图 2023-09-05 143523](https://github.com/jumpserver/jumpserver/assets/26432807/a257b5eb-81dc-4e8a-9d0e-f996f4565d99)

3. 在发布机内能够正常弹出
![图片](https://github.com/jumpserver/jumpserver/assets/26432807/1cde0593-20d9-472e-9c0f-556c369e9337)

4. 我用pyautogui的库，就能自动代填
![屏幕截图 2023-09-05 144802](https://github.com/jumpserver/jumpserver/assets/26432807/68751b60-3949-47c9-99c3-42144c5ee20b)

**Comment by Halo1236** [comment]
@yucai100 请问你的windows server 版本是什么

**Comment by yucai100** [comment]
> @yucai100 请问你的windows server 版本是什么

windows server 2022

**Comment by BaiJiangJie** [comment]
https://github.com/pywinauto/pywinauto/issues/1234

pywinauto 和 win 2022 有兼容性问题。
