### ISSUE TITLE
[Question] redis纳管登录报错

### ISSUE THREAD

**Issue by skipper-sj** [jumpserver/jumpserver#11517]
**请描述您的问题.**
配置了redis数据库，使用web终端登录时提示报错如下：
Connecting to Database **-redis(redis.**.net)  0.0
Connecting to Database **-redis(redis.**.net) error: Redis login prompt characters did not match: redis-cli: /lib/x86_64-linux-gnu/libm.so.6:version `GLIBC_2.29' not found (required byredis-cli)
Receive Connection closed
Connection websocket closed

以上部分敏感信息打码了，其他的都是终端显示内容，帮忙排查下问题，谢谢

**Comment by skipper-sj** [comment]
另外，我这边配置的是阿里云的[云数据库Redis版]，版本是Redis 5.0社区版

**Comment by wojiushixiaobai** [comment]
JumpServer 版本号是多少？
如果不是最新的话更新一下问题即可解决

**Comment by skipper-sj** [comment]
我这边用的版本是jumpserver-installer-v3.6.0，是直接在虚拟机上使用jmsctl.sh start运行的

**Comment by skipper-sj** [comment]
输入命令行，显示：
redis-cli: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by redis-cli)

**Comment by wojiushixiaobai** [comment]
该问题已经在最新版本修复，请更新

**Comment by skipper-sj** [comment]
升级到最新版，已验证可以访问redis
