### ISSUE TITLE
[Bug] cisso交换机命令过滤不生效

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#11518]
**JumpServer 版本3.6.3
配置了命令过滤，执行后发现交换机实际已经执行了，没有过滤成功

![7fcbcf55e498acf4f019d2d702bb03b](https://github.com/jumpserver/jumpserver/assets/122069934/bee84ae1-fe75-4ca6-9549-87a2ad072075)
![2ab94023b336e33ea559a4138073294](https://github.com/jumpserver/jumpserver/assets/122069934/40ed9863-ff7b-4af0-84a4-c012f6b4d0ab)

**Comment by BaiJiangJie** [comment]
@jym503558564

**Comment by jym503558564** [comment]
命令规则设置，贴出来一下看看

**Comment by zhenzhendong** [comment]
命令规则如下：
![image](https://github.com/jumpserver/jumpserver/assets/122069934/df8fdddb-09fe-49c9-ad36-99d89fafb0ed)
<img width="629" alt="91049ba6de6c21e3b8b421fb9c05022" src="https://github.com/jumpserver/jumpserver/assets/122069934/d8b1be44-0c20-46ca-9eef-c6996f6884a7">


访问协议是telnet方式

**Comment by jym503558564** [comment]
telnet协议复现shutdown命令拦截失败，已提到tapd

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
