### ISSUE TITLE
[Bug] 资产的导入导出图标显示有误，建议修改

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#11521]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.6.3

**浏览器版本**
与浏览器版本无关

**Bug 描述**
资产的导入导出图标显示有误，建议修改

**Bug 重现步骤(有截图更好)**
1.在资产列表中查看导入、导出的图标，图标显示与文字描述相反。

![image](https://github.com/jumpserver/jumpserver/assets/92150453/1ac752fb-26ab-4c1b-b8d6-051b418dc186)

**Comment by BaiJiangJie** [comment]
没问题，向上是导入。向下类似于下载，是导出。

**Comment by BaiJiangJie** [comment]
<img width="2551" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/22efaa50-6b87-40be-b0a9-47136a8c6c91">
