### ISSUE TITLE
[Question] 升级3.6.3后，ssh终端无法连接mysql

### ISSUE THREAD

**Issue by swordcooler** [jumpserver/jumpserver#11524]
Host]>
  ID | 名称              | 地址                                                   | 协议                     | 平台                    | 组织                     | 备注
-----+-------------------+--------------------------------------------------------+--------------------------+-------------------------+--------------------------+--------------------------
  1  | adb               | xxxx           | mysql                    | MySQL                   | Default                  |
  2  | mysql.admin       | xxx           | mysql                    | MySQL                   | Default                  |
  3  | mysql.busi.master | xxxxx            | mysql                    | MySQL                   | Default                  
页码：1，每页行数：70，总页数：1，总数量：9
提示：输入资产ID直接登录，二级搜索使用 // + 字段，如：//192 上一页：b 下一页：n
搜索：
[Host]> 1
无协议
[Host]> 2
无协议
[Host]> 3
无协议

如上，升级前ssh可以连接。升级后只有web终端可以正常连接。

**Comment by BaiJiangJie** [comment]
v3.6 版本移除了 DB CLI 的连接方式。终端获取资产的时候数据库资产没有过滤掉。

v3.7 版本计划回归 CLI 方式的数据库连接。

**Comment by swordcooler** [comment]
好的。感谢解答
