### ISSUE TITLE
[Bug] chrome应用在打开部分web应用进行脚本代填时，存在异常，在元素可定位操作的情况下报错元素不可交互

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#11520]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.6.3

**浏览器版本**
发布机chrome应用版本：0.8；firefox应用版本：0.1.2

**Bug 描述**
twitter登录网页的脚本代填，在使用chrome浏览器进行代填时，输入用户名的元素定位失败，报错:element not interactable；使用firefox浏览器进行代填时，能正常代填

**Bug 重现步骤(有截图更好)**
1.编写好twitter登录的代填脚本；
2.分别通过firefox和chrome浏览器进行twitter web应用的访问；
3.对比查看chrome无法正常访问，代填时报错

firefox代填结果
![image](https://github.com/jumpserver/jumpserver/assets/92150453/fa5dcdbc-94a2-4236-bb74-c60158e659b1)
chrome代填结果：
![d226cda22341796efa88cdf8c8d99a1](https://github.com/jumpserver/jumpserver/assets/92150453/b5c48f4c-2bdc-42dd-a487-4dd417a3085e)
![0ad2e4b4fcd3c6da8e6dad55d00937a](https://github.com/jumpserver/jumpserver/assets/92150453/8473dc28-307b-4010-a519-8b8597b968a1)
![046ca293c15c11a70a3975021904d14](https://github.com/jumpserver/jumpserver/assets/92150453/c9c4a307-7336-4ab1-bba0-af6013310181)
代填脚本：
[代填脚本.txt](https://github.com/jumpserver/jumpserver/files/12555225/default.txt)

**Comment by BaiJiangJie** [comment]
有没有可能是 twitter 在 Chrome 上做了限制？

**Comment by sageonedream** [comment]
在本地通过RobotFramework，采用chrome驱动。可以正常往下跑

**Comment by BaiJiangJie** [comment]
换个其他网站试试。

**Comment by BaiJiangJie** [comment]
但是我看你的代填脚本，Xpath 写的好像不对。

**Comment by BaiJiangJie** [comment]
<img width="1464" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/25ef13fb-2f6e-4c9e-8b66-f5a40c036e07">

这样来复制。

**Comment by xulinde** [comment]
chrome 最小化造成元素定位不到，已经在 v3.7 移除了

**Comment by BaiJiangJie** [comment]
新版本已优化，升级解决。
