### ISSUE TITLE
[Question] 没有做任何修改 ChatGPTResponse parse json error 重启无法解决

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#11525]
**请描述您的问题.**
<img width="368" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/34bcb7c6-d34c-4eb2-9903-78c599badf53">

版本v3.5.3

**Comment by feng626** [comment]
key 过期或错误 会出现这种问题，建议升级3.6.3 会返回你完整的错误信息
