### ISSUE TITLE
[Bug] openapi接口数据无法完整查询

### ISSUE THREAD

**Issue by chianoceanwhale** [jumpserver/jumpserver#11523]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
/ops/ansible/job-execution/{id}/log/接口数据无法完整获取，代码写死了获取大小，如果为了防止查询数据太大，应该给前端输入分页参数

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/38933373/e5b905dd-c20f-443e-b091-ddb89a8702da)

**Comment by BaiJiangJie** [comment]
/core/ops/celery/task/3ce22826-5f81-4039-8ccd-822858fe1aab/log/?type=celery

调用这个 API

**Comment by chianoceanwhale** [comment]
是的 手动调试的

**Comment by chianoceanwhale** [comment]
这个1024*10的大小应该给openapi接口输入

**Comment by chianoceanwhale** [comment]
> /core/ops/celery/task/3ce22826-5f81-4039-8ccd-822858fe1aab/log/?type=celery
> 
> 你手动调用的吗？调用这个 API。

不是 我调用的是/ops/ansible/job-execution/{id}/log/接口

**Comment by chianoceanwhale** [comment]
> celery

这个接口没有开放出来吧  我在API Docs上没有找到
![image](https://github.com/jumpserver/jumpserver/assets/38933373/14ce269e-8471-4693-8949-9c4caacb23d0)

另外这个接口控制台看是websocket协议传输回来的数据吧
