### ISSUE TITLE
[Bug] 角色详情对应授权用户未显示

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11536]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.3

**浏览器版本**
Chrome

**Bug 描述**
角色详情对应授权用户未显示

**Bug 重现步骤(有截图更好)**
1.进入角色列表
2.点击角色名称，进入授权用户
3.看不到用户名称
<img width="1305" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/20af3209-4a27-4197-aff9-ed47242c7b62">

**Comment by BaiJiangJie** [comment]
有 Bug，v3.7 版本修复。

https://github.com/jumpserver/lina/pull/3384

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
