### ISSUE TITLE
[Bug] 工单回复异常

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11537]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.3

**浏览器版本**
chrome

**Bug 描述**
工单回复异常

**Bug 重现步骤(有截图更好)**
1.管理员审批工单时，选择回复，报服务器错误
<img width="1243" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/76d59462-c4d5-4cca-997a-099ad32c69a8">

**Comment by BaiJiangJie** [comment]
@xulinde 是否能复现？

**Comment by xulinde** [comment]
已知bug：https://www.tapd.cn/45454465/bugtrace/bugs/view?bug_id=1145454465001029748

**Comment by BaiJiangJie** [comment]
新版本已修复。
