### ISSUE TITLE
[Bug] 设置-系统任务，搜索无返回结果

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11538]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.3

**浏览器版本**
chrome

**Bug 描述**
设置-系统任务，搜索无返回结果

**Bug 重现步骤(有截图更好)**
1.进入设置-系统任务
2.在输入框输入任务名称，精准搜索和模糊匹配都显示暂无结果
<img width="1430" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/54fca34d-bfda-49c5-8db1-5b9c9ca9ae77">
<img width="1427" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/703b2976-2201-42d3-87a5-86bb364a6344">
<img width="1422" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/f6db0f3c-7809-488c-96bb-70b82b2223f6">

**Comment by BaiJiangJie** [comment]
有 Bug，v3.7 版本支持通过 Name 搜索。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
