### ISSUE TITLE
[Question] 【问题咨询】RDP资产连接方式里没有RDP客户端和RDP文件

### ISSUE THREAD

**Issue by FIERCELION** [jumpserver/jumpserver#11540]
使用的是Jumpserver社区版3.6.3的版本，RDP只有通过WEB UI的连接方式，想知道怎么配置rdp客户端和rdp文件？有相关的文档吗？谢谢

![20230912 jumpserver issue](https://github.com/jumpserver/jumpserver/assets/41266070/4a7ad573-3d5b-417f-b740-4903d0732aef)

**Comment by BaiJiangJie** [comment]
RDP 客户端和 RDP文件的连接方式是企业版功能。
