### ISSUE TITLE
> 针对不活跃用户提供自动禁用计划

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#11549]
> 针对不活跃用户提供自动禁用计划
> 
> 在 v3.6 版本已支持。

是怎样的机制呢，我升级后似乎没看到效果。
版本：docker 升级部署  到 v3.6.2
不活跃用户自动禁用 (天) 30
很多用户加入系统后很久压根都没用过，都没被自动禁用啊

![1693359822055](https://github.com/jumpserver/jumpserver/assets/38068938/ec8f1759-2a4e-4a4c-8090-3cdebe5f4cf8)

_Originally posted by @sanpichen in https://github.com/jumpserver/jumpserver/issues/11187#issuecomment-1698367430_

**Comment by BaiJiangJie** [comment]
<img width="1504" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/571add71-bd42-4f4e-a3fd-93783b20d46f">

看用户的最后一次登录日期。

**Comment by BaiJiangJie** [comment]
<img width="951" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fcc5c304-aaff-449d-923c-b72189d3f124">

**Comment by sanpichen** [comment]
是的呀，我看了最后一次登录时间是超过30天了，但是用户状态还是正常的。
![1694741008670](https://github.com/jumpserver/jumpserver/assets/38068938/7a695312-1b42-4bea-9fb3-29f1b7caa5c0)
![1694741052571](https://github.com/jumpserver/jumpserver/assets/38068938/4791da74-726e-43c8-86b6-13b7b9ef3283)

**Comment by BaiJiangJie** [comment]
判断逻辑有一些问题，v3.7 版本优化一下。

目前是根据登录日志里已有的数据来进行判断的。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。

**Comment by sanpichen** [comment]
关于：perf: 优化禁用长时间未登录用户的处理逻辑
没有看到效果

已经升级到 Version v3.7.1
譬如如下用户，应该已经过期了，还是有效未锁定 状态
到底禁用逻辑是怎样的？（以下信息直接通过用户列表导出获得，实测用户确实可以正常登录使用）
ID *名称 *用户名 *邮箱 微信 手机 MFA 级别 来源 企业微信 钉钉 飞书 创建者 最后更新者 备注 Is superuser 组织管理员 用户组 系统角色 组织角色 密码策略 服务账号 是否有效 已过期 激活 是否绑定了虚拟 MFA 可以使用公钥认证 MFA 已启用 需要更新密码 强制 MFA 首次登录 登录被锁定 失效日期 加入日期 上次登录 更新日期 最后更新密码日期 
98d53731-cec8-4f10-8308-81fxxxxx455 郑xx zhxxhz ***@***.*** {"code": "+86", "phone": 136xxxxxx7} 2 local - - - Administrator - No No ["系统管理员(d888d904-ea4c-40db-9ff0-4bcc38216eda)", "网络管理员(e64d9eae-d102-42bc-99a1-d908aa0321f2)"] ["支持室管理员(f0619b28-886f-4fc4-aa7b-b87686900027)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2091/03/21 14:54:28 +0800 2022/09/01 08:54:34 +0800 2023/03/01 17:08:31 +0800 2023/03/14 10:17:01 +0800 2023/03/01 16:45:21 +0800 
b6a38dba-83e9-4b6c-98fa-a16xxxxx51e 孔xx koxxao ***@***.*** {"code": "+86", "phone": 135xxxxxx4} 2 local - - - Administrator - No No ["系统管理员(d888d904-ea4c-40db-9ff0-4bcc38216eda)"] ["支持室管理员(f0619b28-886f-4fc4-aa7b-b87686900027)", "系统审计员(00000000-0000-0000-0000-000000000002)", "用户(00000000-0000-0000-0000-000000000003)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2092/04/21 14:23:28 +0800 2022/07/30 08:47:51 +0800 2023/04/07 13:24:25 +0800 2023/03/14 10:17:01 +0800 2023/01/29 09:32:57 +0800 
b6a72891-f028-4881-89f8-a4cxxxxx2ec 崔xx cuxxng ***@***.*** {"code": "+86", "phone": 137xxxxxx7} 2 local - - - Administrator - No No ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] ["用户(00000000-0000-0000-0000-000000000003)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2092/05/01 15:11:12 +0800 2022/07/15 10:07:18 +0800 2023/04/25 10:42:36 +0800 2023/03/14 10:17:01 +0800 2023/02/21 09:23:10 +0800 
04bddea5-0e40-4d81-8d4c-b0dxxxxx39a 彭xx pexxingshan ***@***.*** {"code": "+86", "phone": 137xxxxxx3} 2 local - - - Administrator 彭xxx No No ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] ["用户(00000000-0000-0000-0000-000000000003)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2092/05/01 15:11:12 +0800 2022/09/23 11:04:38 +0800 2023/07/14 18:08:14 +0800 2023/06/21 17:16:53 +0800 2023/06/21 17:16:52 +0800 
e66b5d8b-0b2c-4bf8-a9bd-c03xxxxx08b 吴xx wuxx ***@***.*** {"code": "+86", "phone": 134xxxxxx9} 2 local - - - Administrator 吴xxx - No No ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] ["用户(00000000-0000-0000-0000-000000000003)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2092/05/01 15:11:12 +0800 2022/10/27 16:30:06 +0800 2023/07/24 09:34:24 +0800 2023/07/24 09:34:03 +0800 2023/07/24 09:34:03 +0800 
a03d6dd5-f706-4ccc-be8b-e64xxxxx5e8 田xx tixxm ***@***.*** {"code": "+86", "phone": 139xxxxxx3} 2 local - - - Administrator 田xxx - No No ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] ["用户(00000000-0000-0000-0000-000000000003)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2092/05/01 15:11:12 +0800 2022/07/25 14:05:28 +0800 2023/08/03 09:56:25 +0800 2023/08/03 09:48:00 +0800 2023/08/03 09:40:38 +0800 
23789b18-238f-4b32-92d7-8daxxxxx273 潘xx paxx ***@***.*** {"code": "+86", "phone": 135xxxxxx2} 2 local - - - Administrator 潘xxx - No No ["系统部服务台(0bc7d9ed-1874-480e-acbb-40e5be2208b8)"] ["一线支持工程师(73086d96-dcf4-42be-956c-5b7169e3442e)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2091/03/21 14:54:28 +0800 2022/09/01 09:09:53 +0800 2023/08/09 17:10:44 +0800 2023/07/19 16:33:18 +0800 2023/07/19 16:33:18 +0800 
767553be-806c-4392-9fe1-d07xxxxx082 陈xx chxxl ***@***.*** {"code": "+86", "phone": 136xxxxxx1} 2 local - - - Administrator 陈xxx - No No ["系统部服务台(0bc7d9ed-1874-480e-acbb-40e5be2208b8)"] ["一线支持工程师(73086d96-dcf4-42be-956c-5b7169e3442e)"] ["OrgUser(00000000-0000-0000-0000-000000000007)"] email No Yes No Yes Yes Yes Yes No Yes No No 2091/03/21 14:54:28 +0800 2022/09/01 09:07:02 +0800 2023/08/16 08:59:37 +0800 2023/08/01 08:45:07 +0800 2023/07/31 16:55:03 +0800 









***@***.***
 
发件人： Bryan
发送时间： 2023-09-22 10:55
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] > 针对不活跃用户提供自动禁用计划 (Issue #11549)
v3.7 已发布，更新版本解决。
