### ISSUE TITLE
[Question] 【问题咨询】通过root特权账号连接SFTP，文件无法上传到系统目录

### ISSUE THREAD

**Issue by FIERCELION** [jumpserver/jumpserver#11542]
通过root特权账号连接SFTP，文件无法传到以下的系统目录，改怎么解除这样的限制？（同样的服务器、用户和密码在next-terminal上是可以直接上传文件到系统目录的）
/boot
/proc
/root
/sys

![20230912 jumpserver issue-files](https://github.com/jumpserver/jumpserver/assets/41266070/19411504-25b2-4341-b240-3cad2d894797)

**Comment by BaiJiangJie** [comment]
资产对应的系统平台修改 SFTP 协议中的目录位置。

**Comment by BaiJiangJie** [comment]
<img width="1504" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/12370a22-ed7a-412e-8678-de2160ff23f2">

**Comment by FIERCELION** [comment]
> <img alt="image" width="1504" src="https://user-images.githubusercontent.com/32935519/267250055-12370a22-ed7a-412e-8678-de2160ff23f2.png">

如果把SFTP root改为“/root”，那么用户是可以在/root文件夹下直接上传文件的。然而，用户无法看到/root的上级目录。
如果把SFTP root改为“/”，那么用户可以看到服务器根目录下的所有的文件，也包含上面说的那些系统目录。然而在此种情形下，系统目录均是“只读”权限，无法通过jumpserver上传文件到root。

现在我想的是要么有一种办法可以让SFTP root配置多个目录，要么可以考虑这或许是一个bug？

**Comment by BaiJiangJie** [comment]
暂无计划支持配置多个目录。

配置 SFTP root 为 "/" 后，应该可以操作 / 目录下的所有目录和文件。

如果不能操作，应该是账号的权限问题。

比如：
/boot
/proc
/root
/sys

可以提供一下账号登录到主机上后的目录权限吗？

**Comment by BaiJiangJie** [comment]
@LeeEirc 看一下文件管理中的 🔒 目录，什么情况下会出现？

**Comment by BaiJiangJie** [comment]
@jym503558564 是否可以复现？

**Comment by FIERCELION** [comment]
> 暂无计划支持配置多个目录。
> 
> 配置 SFTP root 为 "/" 后，应该可以操作 / 目录下的所有目录和文件。
> 
> 如果不能操作，应该是账号的权限问题。
> 
> 比如： /boot /proc /root /sys
> 
> 可以提供一下账号登录到主机上后的目录权限吗？@FIERCELION

@BaiJiangJie 

这是next-terminal登录后显示的目录权限
![20230912 next-terminal-Snipaste_2023-09-12_19-56-56](https://github.com/jumpserver/jumpserver/assets/41266070/16661a01-1f66-44a3-a0c8-485330e05fca)

这是jumpserver登录后显示的目录权限
![20230912 jumpserverfolderproperties_Snipaste_2023-09-12_19-58-11](https://github.com/jumpserver/jumpserver/assets/41266070/63564a90-fa6c-44a2-bc7c-3cdcaf3aa9c5)

两个登的都是同一台服务器。另外我也用其他服务器测试过，感觉和特定的文件夹（或名称）有关。那些比较重要的系统文件夹在jumpserver里都是上锁的状态。

**Comment by BaiJiangJie** [comment]
看着没问题啊，目录权限读写中只包含读权限。

**Comment by FIERCELION** [comment]
> 看着没问题啊，目录权限读写中只包含读权限。

@BaiJiangJie 
别的目录没有尝试过，但是/root目录比较特殊。

虽然我明白dr-xr-x--- 表示其拥有者有读取和执行的权限但没有写权限，群组成员也有读取和执行的权限但没有写权限，而其他用户没有任何权限。

然而，/root这个目录实际上是可写的，这个不但可以在next-terminal上实现，而且在咱们的jumpserver中，只要我把sftp的一级目录改为“/root"，那个这个目录也是可写的。

我期望的是 /root 这个目录可以被写入。

**Comment by FIERCELION** [comment]
再次补充一下，这是一个十分令人困惑的问题。当我在ssh中执行”sudo chmod u+w /root“之后，/root目录便可写了。但是我不确定这样做是必须的，因为那里有一个参照物——next-terminal可以在root目录为dr-xr-x--- 的前提下写入文件。我很想知道为什么会出现这样的情况……

**Comment by FIERCELION** [comment]
@BaiJiangJie 
现在一个合理的解释是：
**Jumpserver会根据Linux系统文件夹的权限首先检查一遍权限，权限不符合的就直接给目录上锁了**。如果Jumpserver中sftp根目录设为/root那么Jumpserver就不会判断文件夹的权限，从而让/root又变得可写。

事实上即使目录的权限是 dr-xr-x---，但如果当前的用户是 root（超级用户），那么它几乎可以无视文件系统的权限进行任何操作。超级用户有特权可以读、写和执行大多数文件和目录，即使权限设置实际上并不允许这样做。

要修复这一问题，就是**让JumpServer不要去主动锁定那些看似不可写的目录，尤其在特权账户启用的情形下。**因为像/root这样的文件夹遇到root这样的超级用户，/root目录实际可写是在预料范围内的。

**Comment by jym503558564** [comment]
配置SFTP目录为“/”，超级账号root对于该目录下，如：
/boot
/proc
/root
/sys
root无法对这些目录进行文件操作，问题复现，已提交给研发。

**Comment by BaiJiangJie** [comment]
没问题，如果获取回来的目前权限中没有 w 权限，有 r 权限，就不允许上传操作，但是支持下载操作。

**Comment by FIERCELION** [comment]
> 没问题，如果获取回来的目前权限中没有 w 权限，有 r 权限，就不允许上传操作，但是支持下载操作。

正如我上面提到的，root应该对/root目录有默认的写入权限，root用户想要在root目录下创建或删除文件或子目录，它只需要执行（x）权限，而不需要写入（w）权限。

**Comment by BaiJiangJie** [comment]
后面版本优化，对于 root 用户做个特殊处理，我们不控制他的目录权限。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
