### ISSUE TITLE
[Bug] V3.0.4 ansible已禁用

### ISSUE THREAD

**Issue by hejunv** [jumpserver/jumpserver#11545]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.0.4 ansible已禁用

**浏览器版本**
chrome 92.0.4515.107

**Bug 描述**
使用作业中心，快捷命令时出现ansible已禁用。
对于Linux设备正常，对于华为交换机就ansible已禁用。都是在jumpserver上用ssh能正常登录的。

**Bug 重现步骤(有截图更好)**
1.作业中心快捷命令
2.选择资产华为交换机，用户名选择ssh01（这是该交换机上正常能登的账号），策略跳过，语言shell，超时60
3.输入框输入dir（显示文件）
结果是：
等待
跳过以下主机：
1:华为交换机 Ansible 已禁用
[WARNING]:provide forhosts list is empty，only...

**Comment by BaiJiangJie** [comment]
默认的 华为交换机 平台 Ansible 功能是没有开启的。

需要新建一个开启 Ansible 功能的 华为网络设备 平台。

要求：交换机上需要有 bash 环境 和 Python 解释器。

<img width="2544" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/4ef66883-d703-4ecc-831f-a4329dad6b7a">
