### ISSUE TITLE
[Question] 资产私钥查询

### ISSUE THREAD

**Issue by skipper-sj** [jumpserver/jumpserver#11541]
我新增了资产列表，使用了私钥，我想重新查找获取该部分私钥，哪里可以查找，有没有完整的文档可以查看

**Comment by BaiJiangJie** [comment]
账号管理，找对对应的账号条目，点击“查看”。

**Comment by BaiJiangJie** [comment]
<img width="2531" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/32d9d156-6233-46da-bf44-4e2fb86d9345">

**Comment by skipper-sj** [comment]
感谢，已解决
