### ISSUE TITLE
[Question] 作业中心的快捷命令是否可以自定义执行目录

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11558]
**请描述您的问题.**
我的ubuntu系统不知道什么情况/root目录无法创建文件导致，执行快捷命令的时候失败，是否可以自定义目录执行操作，这个root是可以登录资产的
![image](https://github.com/jumpserver/jumpserver/assets/44529247/e6fcfc6f-e0c4-4caf-8488-376d7d31521c)

**Comment by BaiJiangJie** [comment]
那你执行：cd /tmp && date 呢？

**Comment by ryswork1993** [comment]
你说的这个我试了一下不行
因为jumpserver用的是ansible实现的批量操作设备，所以需要在/root目录下面生成.ansible文件，现在因/root目录无法生成文件，所以执行失败

**Comment by BaiJiangJie** [comment]
sftp 协议中你配置的 SFTP ROOT 是什么？

**Comment by BaiJiangJie** [comment]
那没有办法，必须得保证 root 用户在 /root 目录下有创建文件的权限。

**Comment by ibuler** [comment]
这个是临时文件目录的问题，默认就是在家目录下，和当前目录没有关系

**Comment by BaiJiangJie** [comment]
v3.8 版本会支持指定目录运行。

请关注后续的版本发布。
