### ISSUE TITLE
[Feature] 用户登录堡垒机时通知管理员

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11551]
**请描述您的需求或者改进建议.**
1、我们有一台网管平台需要让其他公司的人随时登录操作，我想实现他登录jumpserver的时候发个通知到指定邮箱
2、公告功能能不能针对不同用户显示不同内容或者只针对指定用户显示公告，不指定的用户不显示

**Comment by BaiJiangJie** [comment]
1. 现在对用户登录有控制，是企业版功能，将来要做也会考虑放到企业版中。
2. 暂时不考虑支持。

**Comment by BaiJiangJie** [comment]
<img width="2232" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1c3873ec-9fab-47d4-a4d1-73d776cc1e57">

**Comment by BaiJiangJie** [comment]
新版本已上线。（企业版）
