### ISSUE TITLE
[Bug] 使用xftp编辑文件时，不修改文件，而是生成一个新的带duplicate标识的文件

### ISSUE THREAD

**Issue by PlaneV** [jumpserver/jumpserver#11556]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**
Microsoft Edge
版本 116.0.1938.69 (正式版本) (64 位)

**Bug 描述**
使用xftp编辑文件时，不修改文件，而是生成一个新的带duplicate标识的文件，以前是直接修改文件，现在的方式对于编辑配置文件非常不方便，请考虑修复这个问题。

**Bug 重现步骤(有截图更好)**
1.在xftp连接堡垒机2222端口，编辑文件就会出现
2.
3.

**Comment by BaiJiangJie** [comment]
v3.7 版本会优化，可以支持用户个人配置是重命名还是直接替换。

**Comment by BaiJiangJie** [comment]
v3.7 已发布，更新版本解决。
