### ISSUE TITLE
[Question] 脚本不能叫升级到3.6.4

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#11557]
**请描述您的问题.**
原版本3.6.3，想升级到3.6.4
curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
反向升级到了3.5.5
我反复测试了几遍，不知道什么原因。

**Comment by BaiJiangJie** [comment]
现在可以了，cdn 没有同步过来。
