### ISSUE TITLE
[Question] SFTP 上传文件，遇到同名文件会自动重命名为  xxx_duplicate_xxxxxxxx

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11569]
**请描述您的问题.**
请问如何设置上传已存在的同名文件时，执行覆盖操作，而不是自动创建副本文件

**Comment by Sanbobo1** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/138869963/0db2aef2-e117-4bc8-b977-1be4ad3e62a0)

**Comment by BaiJiangJie** [comment]
v3.7 版本优化，支持用户个人配置重命名还是替换。

**Comment by Sanbobo1** [comment]
请问下v3.7版本预计什么时候会上线

**Comment by BaiJiangJie** [comment]
预计 09.21 号。
