### ISSUE TITLE
[Bug] web拉去客户端无法连接服务器

### ISSUE THREAD

**Issue by spiritcharm** [jumpserver/jumpserver#11565]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.5.0

**Bug 描述**
将jumpserver的ssh端口从2222改为其他端口，通过web拉起客户端
客户端还是会去访问2222端口，导致链接服务器不成功

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
系统设置-终端管理-终端端点 里也需要同步设置。

**Comment by BaiJiangJie** [comment]
<img width="2438" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/8630273c-84ec-49aa-bf16-1877a0d56962">
