### ISSUE TITLE
[Bug] 最新社区版：v3.6.4 切换用户登录失败。

### ISSUE THREAD

**Issue by Coldfengzi** [jumpserver/jumpserver#11566]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.4

**浏览器版本**
102.0.5005.167

**Bug 描述**
#9850 升级之后切换用户登录失败。

**Bug 重现步骤(有截图更好)**
1. 资产添加了两个账号：
admin 普通用户，密码登录。测试连接成功。
root 用户，设置切换自 admin 用户，密码框输入的是admin密码非root密码。
2. admin账号jumpserver上登录没问题，使用admin账号登录后su root使用admin密码没问题
3. jumpserver使用root账号登录出错
![截图1](https://user-images.githubusercontent.com/32095100/222402806-4c46071e-e523-4f28-8c0e-da9931b98214.png)
![微信截图_20230914175429](https://github.com/jumpserver/jumpserver/assets/23092924/1272729d-926d-4f89-90ad-6a3ccc641fc8)

**Comment by BaiJiangJie** [comment]
admin 的密码在 admin 账号里设置。

root 密码在 root 账号里设置。

root 账号设置 切换自 admin 账号。

这时候测试 root 账号可连接性，是什么结果？

**Comment by Coldfengzi** [comment]
> admin 的密码在 admin 账号里设置。
> 
> root 密码在 root 账号里设置。
> 
> root 账号设置 切换自 admin 账号。
> 
> 这时候测试 root 账号可连接性，是什么结果？

是失败的。

**Comment by Coldfengzi** [comment]
![微信截图_20230915091033](https://github.com/jumpserver/jumpserver/assets/23092924/cca20e8b-090f-4c71-9aa7-ced59a3fdd22)
可连接性失败截图

**Comment by BaiJiangJie** [comment]
@feng626 冯，看一下。

**Comment by BaiJiangJie** [comment]
修复进度统一记录在 https://github.com/jumpserver/jumpserver/issues/11354 中。
