### ISSUE TITLE
V3 版本如何关闭 openid 认证[Question] 

### ISSUE THREAD

**Issue by ainuoyan** [jumpserver/jumpserver#11563]
V2 版本使用的时候开启了 openid 认证，升级到 V3 之后由于更换了 OA 系统，不需要使用 openid 认证了，请问如何关闭 openid 认证

**Comment by BaiJiangJie** [comment]
需要手动修改 settings_setting 表。

name 为 AUTH_OPENID 的行，value 设置为 false。

然后重启服务。

**Comment by ainuoyan** [comment]
> 需要手动修改 settings_setting 表。
> 
> name 为 AUTH_OPENID 的行，value 设置为 false。
> 
> 然后重启服务。

已成功，非常感谢
