### ISSUE TITLE
[Bug] AUTH_LDAP_ALWAYS_UPDATE_USER=True

### ISSUE THREAD

**Issue by hwmail** [jumpserver/jumpserver#11562]
**JumpServer version (versions before v2.28 are no longer supported)**
V3.2

**Browser version**
all

**Bug description**

Jumpserver configures domain authentication.
Then use a lowercase domain account to log in using the domain password. Jumpserver will create an uppercase user.

For example, a1234 jumpserver will automatically create an A1234 account

**Bug reproduction steps (preferably with screenshots)**
1. Configure AD domain authentication on Jumpserver.
2.Jumpserver creates an a1234 account and joins the user group without setting a password.
3. The user uses a1234 and uses the domain password 12345678 to log in
4.Jumpserver will automatically create an A1234 account. This user is not in any group.  this account is not my wanna account

**Comment by hwmail** [comment]
why jumpserver account distinguishing capitals from lower case letters ?  can jumpsever  set  capital or lower case the same account  dont  distinguishing

**Comment by BaiJiangJie** [comment]
Take a look at the user attribute mapping fields you configured and view the corresponding attribute values in AD Server.

**Comment by hwmail** [comment]
Yes,i found  the user attribute  samaccount value is  capital letter A1234  ,  so this is why jumpserver will create another account A1234,but i had manually create account a1234 and the problem is  our AD account attribute some are lowcase some are capital letter.  We only want  jumpserver use AD indentify password not need automatic create account ,account we will manually create.

**Comment by BaiJiangJie** [comment]
The current logic is as follows: all mapped attribute values will be synchronized after each authentication is completed.

I have a question. Will there be any problems if you log in using A1234?

Why does it have to be case sensitive?

**Comment by hwmail** [comment]
Thand you very much i got the root case, cause  our AD  account attritubes are too messy ,some uppercase and some lowercase.

So  the question is  users familiar with use lowercase account to login. andy AD  account dont have case sensitive but jumpserver.
