### ISSUE TITLE
[Bug]  批量命令选择节点，第一次选择没有选中节点下的资产

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#11564]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.4

**浏览器版本**
chrome 116.0.5845.187

**Bug 描述**
工作台-作业中心-快捷命令   选择节点时如果节点未展开，第一次选择节点 节点下的资产不会被选中，需要再次点击
展开节点的话选择就没问题

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/63093589/635feaf3-8b5d-4e3b-9cfc-65dd9892f3ef)

**Comment by BaiJiangJie** [comment]
测试时可以的。

直接选中内网机器，看下执行任务日志。

**Comment by wangzhishang02** [comment]
如果未展开节点，第一次勾选节点时，实际是未选中节点下的资产的

https://github.com/jumpserver/jumpserver/assets/63093589/09f93d1f-3497-43ff-b1fa-5a8260bf9b12

**Comment by BaiJiangJie** [comment]
截图就行，视频看不了。

**Comment by wangzhishang02** [comment]
如果未展开节点，第一次勾选节点时，实际是未选中节点下的资产的

![复现视频](https://github.com/jumpserver/jumpserver/assets/63093589/c81fe7a5-f37a-458c-aec3-a6718e3ce7c0)

**Comment by BaiJiangJie** [comment]
这种情况重新再勾选一下。

**Comment by wangzhishang02** [comment]
体验可能没那么好，看能否优化下
