### ISSUE TITLE
[Bug] 命令过滤的bug

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11573]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.3

**浏览器版本**

**Bug 描述**
命令过滤那里，设置了passwd命令需要审核。

**Bug 重现步骤(有截图更好)**
1. 登录堡垒机，输入passwd，执行，提示要复核。
2. 输入sudo  passwd（该用户没有免密sudo权限），然后ctrl+c结束（没有执行）；
3. 输入passwd，执行成功，没有要求复核

**Comment by BaiJiangJie** [comment]
有复现环境吗？测试环境没有复现啊。

<img width="382" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/7a3a26dc-c937-40bb-82ba-e3ce13bf1d4b">

**Comment by khy2021** [comment]
> 有复现环境吗？测试环境没有复现啊。
> 
> <img alt="image" width="382" src="https://user-images.githubusercontent.com/32935519/268198291-7a3a26dc-c937-40bb-82ba-e3ce13bf1d4b.png">

sudo passwd这里不要执行，直接ctrl+c试试看。
我的环境没有限制sudo passwd这样的命令。
我的规则是  ^\s*passwd\s*.*

**Comment by BaiJiangJie** [comment]
截图看看你的命令规则和执行效果。
