### ISSUE TITLE
推送用户时没有执行set password这一步

### ISSUE THREAD

**Issue by yxiaoy6** [jumpserver/jumpserver#11575]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
Version v2.20.2 GPLv2.

**Bug 描述**
推送用户时没有执行set password这一步

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/43592152/c756ed52-6619-4d10-acae-c21c77e96fee)

2.
3.

**Comment by BaiJiangJie** [comment]
应该是你的系统用户没有设置密码。

https://github.com/jumpserver/jumpserver/blob/v2.22.2/apps/assets/tasks/push_system_user.py#L101

**Comment by yxiaoy6** [comment]
> 应该是你的系统用户没有设置密码。
> 
> https://github.com/jumpserver/jumpserver/blob/v2.22.2/apps/assets/tasks/push_system_user.py#L101

使用的是托管密码的模式

**Comment by yxiaoy6** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/43592152/20e38f4f-5c42-40da-aa29-8d462ee0dcfc)

**Comment by BaiJiangJie** [comment]
查看密码，密码得有值。

**Comment by yxiaoy6** [comment]
> 查看下密码，密码得有值。

![image](https://github.com/jumpserver/jumpserver/assets/43592152/e7408b80-7ef3-4cde-8c9d-46c5b32a8491)
系统用户创建时是托管密码，自动生成，那就是这个自动生成没有生效吗？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/blob/v2.22.2/apps/assets/serializers/system_user.py#L198

逻辑和操作看着都没有问题。

页面上查看一下账号的密码。

**Comment by yxiaoy6** [comment]
> https://github.com/jumpserver/jumpserver/blob/v2.22.2/apps/assets/serializers/system_user.py#L198
> 
> 逻辑和操作看着都没有问题。
> 
> 页面上查看一下账号的密码。

哪里查看？我这个版本可能还不支持

**Comment by BaiJiangJie** [comment]
那可能还不支持。

可以通过下面命令查看一下：

```python
# 登录到部署服务器
# 进入 core 容器
docker exec -it jms_core bash
cd apps
python manage.py shell
# 导入系统用户模块
from assets.models import *
# 根据系统用户id获取系统用户实例
s = SystemUser.objects.get(id="")
# 查看密码
s.password
# 查看 key
s.private_key
```

**Comment by yxiaoy6** [comment]
> 那可能还不支持。
> 
> 可以通过下面命令查看一下：
> 
> ```python
> # 登录到部署服务器
> # 进入 core 容器
> docker exec -it jms_core bash
> cd apps
> python manage.py shell
> # 导入系统用户模块
> from assets.models import *
> # 根据系统用户id获取系统用户实例
> s = SystemUser.objects.get(id="")
> # 查看密码
> s.password
> # 查看 key
> s.private_key
> ```

我新建新的系统用户测试，但新建的推送键不可操作

**Comment by yxiaoy6** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/43592152/2513ee1d-8c76-4932-97a1-d70001333f23)

**Comment by BaiJiangJie** [comment]
必须开启自动推送选项。

**Comment by BaiJiangJie** [comment]
建议升级到最新版本使用。
