### ISSUE TITLE
[Feature] 新建资产时不要跳到新的标签页上

### ISSUE THREAD

**Issue by Rainshaw** [jumpserver/jumpserver#11579]
**请描述您的需求或者改进建议.**
v3.6.3 版本，新建资产/网域 等都会新建一个标签页，操作有些割裂，如果可以一站式完成这些任务体验会更好一些

**Comment by BaiJiangJie** [comment]
当前页面打开创建有一个问题：

创建资产时，点击左侧资产树的某个节点，资产创建完成后，会自动返回资产列表页面，这时所选的节点会丢失。

当时是为了解决这个问题。

**Comment by Rainshaw** [comment]
我提两个解决方案哈，具体是否采用你们来决定：
1. 通过localStorage或sessionStorage来存储上一次的节点选择结果，每次打开资产列表时自动定位，不仅可以解决这个场景，同时用户在查看资产树时的体验也会更好一些。
2. 通过在新建资产页面的url里拼接之前选择的节点信息，当创建完资产后，跳转资产列表时读取这个节点信息并定位。

**Comment by BaiJiangJie** [comment]
这两种方案都考虑过，记住点击的哪个节点不是问题。
比较难处理的是自动展开节点，因为左侧资产树是异步加载的。

**Comment by Rainshaw** [comment]
那感觉可以把新建资产页面做成和资产列表一样的组件，保留资产树不动。

**Comment by BaiJiangJie** [comment]
嗯，这样改动比较大，和其他页面的操作体验会不一致。

后面版本想从架构上改一下，创建、更新资源的设计。

比如：都从右侧滑动向左展开创建、更新表单。

**Comment by ibuler** [comment]
已有计划，未来再说
