### ISSUE TITLE
[Question] 清理资产的时候无法删除 报500错误 发现是2.2.8升级到3.5.3的时候进行了回滚 然后发生如下问题

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#11589]
**请描述您的问题.**
背景：之前原地从2.2.8版本升级到3.5.3版本。出现问题，直接进行mysql数据回滚。回滚之后可正常使用。
目前jumpserver的版本还是2.2.8版本，其他功能均能正常使用。
但是无法正常删除资产，mysql报
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`jumpserver`.`accounts_account`, CONSTRAINT `accounts_account_asset_id_d77d9aa0_fk_assets_asset_id` FOREIGN KEY (`asset_id`) REFERENCES `assets_asset` (`id`))')
错误。
发现：
![image](https://github.com/jumpserver/jumpserver/assets/85990572/519ffd1b-2f6a-4f96-86b7-4e34897623bb)
mysql数据表存在181张表。比原本3.5.3版本的143张表还要多出了30多张表
所以怀疑当时原地升级已经修改了数据库。
并且发现不应该存在于2.2.8版本的表
![image](https://github.com/jumpserver/jumpserver/assets/85990572/076a5139-0562-4353-9688-2644db955690)
但是删除资产这一点可以通过按顺序删除：
1. accounts_account
2. assets_asset_nodes
3. assets_authbook
4. assets_host
5. assets_protocol
6. ops_adhoc_hosts
7. perms_assetpermission_assets
8. assets_asset
表来进行删除操作。目前已通过脚本实现该删除
删除100多个资产后。发现目前的资产总数未发生变化。但是删除的资产已经看不到，但是变成了”隐形资产“
<img width="567" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/a5cfdc33-928b-41f0-8cf6-a917d3903d32">
<img width="1079" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/5c20e068-fcf8-4439-b20a-2bc8556fb00d">
请问如果要真实的删除该部分资产，我该如何操作

**Comment by BaiJiangJie** [comment]
回滚的时候一定要使用升级前备份的原始数据库启动，不要使用升级后的数据库，因为版本不同，数据表结构不同。

页面上显示删除了，实际上的资产应该也确实删除了。
可以通过查看 assets_asset 表来确认一下。

**Comment by BaiJiangJie** [comment]
所有问题，使用升级前的数据库启动 v2.2.8 版本就可以解决。

**Comment by xiaoxiongxyy** [comment]
> 回滚的时候一定要使用升级前备份的原始数据库启动，不要使用升级后的数据库，因为版本不同，数据表结构不同。
> 
> 页面上显示删除了，实际上的资产应该也确实删除了。 可以通过查看 assets_asset 表来确认一下。

MySQL [jumpserver]> select count(*) from assets_asset;
+----------+
| count(*) |
+----------+
|      828 |
+----------+
1 row in set (0.00 sec)

之前就已经查过 是看到assets_asset的资产被删除了之后 再去看页面 页面的资产还是之前的台数 并没有减少
我使用的数据库就是回滚之后的数据库。这边看问题可能是回滚之后 覆盖了v3版本数据库的表 但是升级的时候所创建的表 并没有进行删除 而是与v2版本的表同时存在 所以造成同时存在v2和v3版本的表
我目前有方法解决这个问题吗

**Comment by xiaoxiongxyy** [comment]
> 所有问题，使用升级前的数据库启动 v2.2.8 版本就可以解决。

目前使用的正是升级前的数据库启动 只是无法解决表共同存在问题

**Comment by BaiJiangJie** [comment]
回滚版本的时候数据库表结构不会被回滚，你要使用升级前备份的数据库。

**Comment by xiaoxiongxyy** [comment]
> 回滚版本的时候数据库表结构不会被回滚，你要使用升级前备份的数据库。
请问仪表盘中显示的数据是从哪获取的 Redis吗

**Comment by BaiJiangJie** [comment]
原数据是从 MySQL 中获取的，在 Redis 中做了一层缓存。

**Comment by BaiJiangJie** [comment]
升级到最新版本解决。
