### ISSUE TITLE
[Bug] v3.6.4修改平台列表中的支持的协议组时，对应资产协议组不会变化

### ISSUE THREAD

**Issue by b-ing** [jumpserver/jumpserver#11582]
**Bug 描述**
修改平台列表中的支持的协议组时，对应资产协议组不会变化

**Bug 重现步骤(有截图更好)**
1. 资产关联的平台为 python3_linux
![image](https://github.com/jumpserver/jumpserver/assets/33180711/039ebb0b-efcb-43d8-b602-4cfebd7ad701)

2. python3_linux平台中的ssh协议组
![image](https://github.com/jumpserver/jumpserver/assets/33180711/97201dea-8473-4939-9543-5cbd244b519c)

不会自动同步到资产

**Comment by ibuler** [comment]
不会自动同步的，平台中的协议只是默认值，新增协议后，资产也可以添加新的协议
