### ISSUE TITLE
[Bug] ubuntu 系统使用rz命令上传较大文件时直接打开了文件，导致文件上传失败

### ISSUE THREAD

**Issue by liubo637** [jumpserver/jumpserver#11595]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.4

**浏览器版本**
Microsoft Edge
版本 117.0.2045.31 (正式版本) (64 位)

**Bug 描述**
Web CLI终端，用rz命令上传较大文件时直接打开了文件，导致文件上传失败

**Bug 重现步骤(有截图更好)**
1.
2.
3.

![image](https://github.com/jumpserver/jumpserver/assets/1932666/0bc771f1-08a0-4f98-b2dd-192a4af102ee)

**Comment by BaiJiangJie** [comment]
@jym503558564 复现一下大文件的 rz 上传会不会出现。

**Comment by liubo637** [comment]
不要使用压缩包

**Comment by jym503558564** [comment]
经测试，80M以上的文件容易复现该问题。小文件50M上下的基本正常。已反馈研发，待处理。

**Comment by 1inuxboy** [comment]
在实际使用中使用web终端上传确实会出现类似的情况，使用连接工具如xshell进行连接的时候偶现该问题，个人的临时解决方案是：1. 使用rz -E命令 2. 多次执行rz命令可以实现上传 3. 使用xftp相关工具上传

**Comment by jym503558564** [comment]
可参照：
![image](https://github.com/jumpserver/jumpserver/assets/40739051/18e3e461-94d7-405b-8dba-68d807c33af6)

**Comment by jym503558564** [comment]
大文件推荐用sftp
