### ISSUE TITLE
[Question] Website资产 连接按钮点击没反应

### ISSUE THREAD

**Issue by forwardwayl** [jumpserver/jumpserver#11597]
**请描述您的问题.**

Website资产，连接按钮 是灰的，点击没反应

堡垒机版本：3.6.2

**Comment by BaiJiangJie** [comment]
需要部署发布机。

**Comment by forwardwayl** [comment]
部署发布机后可以正常使用了。

部署过程中需要注意开启终端注册、如果api调用有类似IP限制的话需要事先加白；此外，redis命令重命名可能导致连接Website资产异常（redis.exceptions.ResponseError: unknown command 'KEYS', with args beginning with: ':1:applet_host_accounts****'）。
