### ISSUE TITLE
[Bug] 远程应用标签  <发布机:发布机名称> 不生效

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#11598]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.3

**浏览器版本**
版本 116.0.5845.188（正式版本） （64 位）

**Bug 描述**
远程应用标签  <发布机:发布机名称> 不生效， <AppletHost:发布机名称>是可以的

**Bug 重现步骤(有截图更好)**
1.切换远程应用的标签，打开不同的 web 界面
2.访问 https://ip.sb/ 查看来源IP
![image](https://github.com/jumpserver/jumpserver/assets/43403764/a34f6654-124d-4e14-8fcc-1f4204ec962a)

**Comment by BaiJiangJie** [comment]
一个资产关联的标签只能是下面的其中一个：

1. 标签的 name 是：发布机，值是发布机的名称
2. 标签的 name 是：AppletHost，值是发布机的名称

**Comment by LinuxLeader** [comment]
我知道的，如果标签用 “ 发布机:发布机名称”  web界面查看来源IP两次访问的IP是同一个，如果标签换成 “AppletHost:发布机名称” ，两次访问的是不同的IP

**Comment by BaiJiangJie** [comment]
看下发布机日志，是否调用到了呢？

**Comment by LinuxLeader** [comment]
好的
