### ISSUE TITLE
[Bug] 点击忘记密码无法发送重置邮件

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11594]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.3

**浏览器版本**

**Bug 描述**
在登录界面输入账号，点击忘记密码，无法收到重置密码邮件
![image](https://github.com/jumpserver/jumpserver/assets/44529247/906aefc7-34a5-44e6-bc14-c06bc238e202)
管理员点击重置用户密码可以发送重置邮件
![image](https://github.com/jumpserver/jumpserver/assets/44529247/1979c92d-efd3-4af5-8d38-76bdefedd231)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
<img width="809" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/30523ec0-d19a-4955-a49f-84bce93069ce">

忘记密码的邮件在这个页面发送。

**Comment by ryswork1993** [comment]
> <img alt="image" width="809" src="https://user-images.githubusercontent.com/32935519/268606603-30523ec0-d19a-4955-a49f-84bce93069ce.png">
> 忘记密码的邮件在这个页面发送。

我在登陆界面点击忘记密码之后，然后就自动刷新又回到登陆界面，看不到你说的这个界面

**Comment by BaiJiangJie** [comment]
<img width="2208" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f425d1d6-68be-4d42-bf23-7c14d5e963ca">

看下这儿的配置是什么？

**Comment by ryswork1993** [comment]
> <img alt="image" width="1602" src="https://user-images.githubusercontent.com/32935519/268829902-fc5aee3a-0ca4-4e94-8c80-5fab9082f94b.png">
> 看下这儿的配置是什么？

![image](https://github.com/jumpserver/jumpserver/assets/44529247/dbf759a5-1b52-47b1-859b-8d249e95a223)

**Comment by ryswork1993** [comment]
> > <img alt="image" width="1602" src="https://user-images.githubusercontent.com/32935519/268829902-fc5aee3a-0ca4-4e94-8c80-5fab9082f94b.png">
> > 看下这儿的配置是什么？
> 
> ![image](https://user-images.githubusercontent.com/44529247/268844605-dbf759a5-1b52-47b1-859b-8d249e95a223.png)

这个应该怎么排查和解决呢

**Comment by BaiJiangJie** [comment]
清空 忘记密码的 URL 就可以正常跳转了。
