### ISSUE TITLE
[Bug] MFA 绑定失败，显示 MFA code invalid, or ntp sync server time 的问题

### ISSUE THREAD

**Issue by spidemen** [jumpserver/jumpserver#11590]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
Version 117.0.5938.88 (Official Build) (arm64)

**Bug 描述**
<img width="1122" alt="image" src="https://github.com/jumpserver/jumpserver/assets/33735949/9fe2b3f0-7b39-4a69-b8ef-6bc2f3103eda">

**Bug 重现步骤(有截图更好)**
1.  输入正确用户名密码
2.  输入密码
3.   下载google auth
4.    二次验证设备绑定
5.    用手机扫描二维码
6.    输入code  出现图片上错误。 mac 当地时钟没问题的 手机上时钟也没问题 都是iphone

**Comment by BaiJiangJie** [comment]
要看部署服务器上的时间 和 手机时间是否一致。
