### ISSUE TITLE
[Bug] Windows web访问里面的键盘记录不完整

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#11593]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

命令审计里面针对Windows web访问里面的键盘操作无法记录，必须操作enter后命令才会被记录，实际的操作时间也是以enter的操作时间记录的
![image](https://github.com/jumpserver/jumpserver/assets/122069934/7b3193fa-bbf1-4f4d-abf1-d9aac974866c)

**Comment by BaiJiangJie** [comment]
目前逻辑是这样的。

**Comment by zhenzhendong** [comment]
后面可以规划所有命令都记录么？windows命令操作不会输入enter

**Comment by BaiJiangJie** [comment]
目前找不到比较好的方案，所以使用的 Enter 作为结束的标志。

**Comment by BaiJiangJie** [comment]
目前没有优化计划。

**Comment by BaiJiangJie** [comment]
有一个方案可以试一下，最后一次键盘输入计时开始，比如10s内没有输入，就作为一次输入记录下来。

**Comment by LeeEirc** [comment]
v3.8.0 已添加检测机制，超时未操作，会自动记录键盘数据。
