### ISSUE TITLE
[Bug] 堡垒机web界面使用域名登录报配置文件存在问题，无法完成登录，请联系管理员解决，或查看最新更新说明

### ISSUE THREAD

**Issue by syushin55** [jumpserver/jumpserver#11599]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.2

**浏览器版本**

**Bug 描述**
jumpserver配置文件配置 HTTP_PORT=8000，宿主机的nginx和jumpserver部署在同一台机器，nginx配置反向代理
```nginx
server {
    listen 80;
    server_name example.com;  # 自行修改成你的域名
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name          example.com;
    ssl_certificate      cert/example.com.pem;
    ssl_certificate_key  cert/example.com.key; 
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_protocols TLSv1.1 TLSv1.2;
    add_header Strict-Transport-Security "max-age=63072000" always;

    client_max_body_size 4096m;
    location / {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

**Bug 重现步骤(有截图更好)**
1. 访问域名时显示配置文件有问题，请联系管理员，这个错误不知道怎么排查。

**Comment by xzlive** [comment]
同样的报错,等待大牛指导排查.

**Comment by syushin55** [comment]
解决了，config-example.txt 里面的 DOMAINS 字段必须配置自己的域名或者地址，否则无法登录。
![image](https://github.com/jumpserver/jumpserver/assets/43629361/5a3c219d-b343-47e0-9288-de60ecb3f2d9)

**Comment by Lihy6472** [comment]
我配置文件没有这个选项，

**Comment by syushin55** [comment]
@Lihy6472 你手动添加一下，然后 ./jmsctl.sh restart，看下行不行。不然就 ./jmsctl.sh uninstall 再 jmsctl.sh install，会重新生成配置文件。

**Comment by Lihy6472** [comment]
手动添加了一下可以了，但是配置文件我需要覆盖掉吗？我看好像升级的时候没覆盖，

**Comment by syushin55** [comment]
@Lihy6472 不用覆盖，/opt/jumpserver/config/config.txt 这个就是使用的配置，这个配置文件没问题就行。你也可以把配置同步到 config-example.txt

**Comment by Lihy6472** [comment]
升级到3.6.4的时候好像好多配置文件里面的东西都没覆盖掉旧版本的，少了60多行

![image](https://github.com/jumpserver/jumpserver/assets/116717391/04676f8b-30d0-4238-a643-1dd546d9cb5f)

**Comment by BaiJiangJie** [comment]
config-example.txt 是不会覆盖 config.txt 的。

多出来的60多行，是新版本新增的配置，有默认值的。不影响。

**Comment by Lihy6472** [comment]
奥奥，好的，谢谢。
