### ISSUE TITLE
[Feature] 资产列表搜索框可以使用退格键重新搜索

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11601]
资产列表搜索框输入关键字后按回车开始搜索，想要继续搜索其它资产时需要使用鼠标点击“x”去掉关键字，需求增加使用退格键清空关键字，这样可以快速多次搜索设备
<img width="1119" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/a18e0f84-3544-4ffd-9d40-568f2036c4c6">

**Comment by huailei000** [comment]
下个版本会优化下。
