### ISSUE TITLE
按照官方教程在线安装，配置config.txt 443端口，https不生效[Bug] 

### ISSUE THREAD

**Issue by ueware** [jumpserver/jumpserver#11600]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.2 
**浏览器版本**
116.0.5845.110

**Bug 描述**
1.使用在线安装脚本快速安装Jumpserver；
2.安装完成后，编辑config.txt文件，配置域名、ssl证书、访问端口为80和443，启动jumpserver
3.80端口访问成功，443不能访问；
4.dockerps检查访问情况，没有443相应的映射端口
![image](https://github.com/jumpserver/jumpserver/assets/12973416/57012987-fa90-462a-a040-3568793c0c94)
附件是config.txt配置文件
**Bug 重现步骤(有截图更好)**
1.
2.
3.
[config.txt](https://github.com/jumpserver/jumpserver/files/12654724/config.txt)

**Comment by wojiushixiaobai** [comment]
把你配置文件里面的 
```
# 参考 https://docs.jumpserver.org/zh/v3/installation/proxy/ 配置
#
 HTTPS_PORT=443
 SERVER_NAME=bastion.ueware.com
 SSL_CERTIFICATE=/opt/jumpserver/config/nginx/cert/jump.pem
 SSL_CERTIFICATE_KEY=/opt/jumpserver/config/nginx/cert/jump.key
#
```
修改为如下，把你多余的空格删掉。`a` 和 `空格a` 不是一个东西
```
# 参考 https://docs.jumpserver.org/zh/v3/installation/proxy/ 配置
#
HTTPS_PORT=443
SERVER_NAME=bastion.ueware.com
SSL_CERTIFICATE=/opt/jumpserver/config/nginx/cert/jump.pem
SSL_CERTIFICATE_KEY=/opt/jumpserver/config/nginx/cert/jump.key
#
```
