### ISSUE TITLE
[Feature] 建议添加OSS的资产类型

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#11612]
目标：使用jumpserver的文件管理功能，向OSS上传下载文件

希望添加OSS类型的资产，填写阿里云OSS的endpoint和AKSK，使用文件管理来打开OSS类型资产，上传下载，可以有操作审计，上传和下载权限控制，路径访问控制。

现在想实现这个效果，我的做法是：做一个docker，docker里挂载OSS路径，然后用户SFTP绑定路径。当需要多个不同的路径权限时，只能创建多个docker当linux资产来解决，较为麻烦。

**Comment by ibuler** [comment]
暂无计划
