### ISSUE TITLE
升级3.6.4版本后api接口无法调用

### ISSUE THREAD

**Issue by Marcyle** [jumpserver/jumpserver#11613]
**JumpServer 版本**
v3.6.4

**Bug 描述**
v3.4.2升级到v3.6.4版本后api接口无法调用，返回
Failed to fetch.
Possible Reasons:
- CORS
- Network Failure
- URL scheme must be "http" or "https" for CORS request.

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/38044893/b0341ff1-4d21-46dd-a17f-7c66fc9482ef)

**Comment by BaiJiangJie** [comment]
这个问题的原因应该是你访问的地址是 https，但是调用 API 的时候用的是 http（应该也要使用 https）。

没有调用 https 的原因是，你中间的某个 nginx 可能没有把 https scheme 代理过来，导致获取的是 http。

**Comment by BaiJiangJie** [comment]
`proxy_set_header X-Forwarded-Proto $scheme;`

每一层 Nginx 中都加上这个配置。
