### ISSUE TITLE
JumpServer v3.6.4 mysql GUI BUG[Bug] 

### ISSUE THREAD

**Issue by baij1314** [jumpserver/jumpserver#11627]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer v3.6.X
JumpServer v3.6.4

**浏览器版本**
Microsoft Edge
版本 117.0.2045.31 (正式版本) (64 位)

**Bug 描述**
连接mysql数据ID不一致 
回放录像是一致的web GUI 的主机不一致，后面3位为400

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/35292770/f4b87423-9c8e-42d5-81bf-c8176946e3ba)

2.
![image](https://github.com/jumpserver/jumpserver/assets/35292770/3f56d860-c791-46a3-a5ce-975827ed6cfe)

3.

**Comment by BaiJiangJie** [comment]
v3.6.4 版本应该修复了。

<img width="1387" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/50c4c16d-dd06-446b-953f-f70933a33a6c">

**Comment by baij1314** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/35292770/31ef148d-c8de-4e74-a83c-58437071ccf1)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/20ef24ee-b2d9-45fe-bc86-34cd62006373)

![image](https://github.com/jumpserver/jumpserver/assets/35292770/55f3efee-1cdc-44eb-a2fe-85ce3558b739)
升级到 v3.6.4
问题没有解决

**Comment by jym503558564** [comment]
v3.7.0测试，数据显示正常
![image](https://github.com/jumpserver/jumpserver/assets/40739051/48856e3c-7289-4d78-8d6e-ff66a7b425f2)

**Comment by baij1314** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/35292770/d1c8d018-3f03-4a34-ab01-3bdd79ca1d02)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/375c3afe-be1a-422b-9ca3-9e3230d173c5)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/973769e1-bcd0-4641-9954-888e5707f55b)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/843fa449-e836-4ca6-9dbc-8eb3baa6eb2c)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/5d394d62-219d-4d8e-82a7-9363d0f50b02)
![image](https://github.com/jumpserver/jumpserver/assets/35292770/f104fe88-f442-4975-8b72-d4c52360b482)

v3.7.0测试，Web CLI 正常，Web GUI 数据显示异常

**Comment by BaiJiangJie** [comment]
看看这张表的 tmp_temple  DDL。

**Comment by baij1314** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/35292770/61c97d88-3e9f-4bab-a0ba-2618b5620374)

**Comment by BaiJiangJie** [comment]
找着问题了，v3.7.1 修复一下。

**Comment by baij1314** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/35292770/74985661-bab2-4a8d-9309-92edd9f5ace4)
升级 v3.7.1  已解决问题了
