### ISSUE TITLE
v2.28.8升级到v3.6.4资产连接失败

### ISSUE THREAD

**Issue by DaddyXz** [jumpserver/jumpserver#11628]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.8升级到v3.6.4

**浏览器版本**
Google Chrome 114.0.5735.110

**Bug 描述**
v2.28.8升级到v3.6.4资产连接失败，升级前，资产关联了一个用户，且用户配置的为密钥登录，升级之后发现资产变为密码登录，且认证失败

**Bug 重现步骤(有截图更好)**
1.升级前的账号
![image](https://github.com/jumpserver/jumpserver/assets/99782519/8be5d2f0-e9ee-42b7-9c2e-57e33bb980ec)

2.升级后的
![image](https://github.com/jumpserver/jumpserver/assets/99782519/1fe7a5d4-154f-4771-afa0-1ab666fd8b73)

3.连接机器
![image](https://github.com/jumpserver/jumpserver/assets/99782519/ad55d175-1fdd-47e1-8706-877f367b2176)

**Comment by jym503558564** [comment]
升级后这个资产里面有多少个账号

**Comment by jym503558564** [comment]
V2和V3版本有重大改变，升级前请参考：https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/ 
https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9

**Comment by jym503558564** [comment]
该系统用户在v2版本是不是设置了密码和密钥

**Comment by jym503558564** [comment]
已修复发版，请升级至v3.7.1进行测试。
