### ISSUE TITLE
[Bug] 批量命令偶发性无法获取执行结果

### ISSUE THREAD

**Issue by catdiscus** [jumpserver/jumpserver#11632]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3.1

**Bug 描述**
执行批量命令过程中, 偶发性出现执行结果未返回, 看日志已经执行成功并打印出了执行结果

**Comment by jym503558564** [comment]
截图附带日志结果，页面等日志有无报错信息

**Comment by BaiJiangJie** [comment]
详细描述后，reopen。
