### ISSUE TITLE
[Question] JumpServer社区版v3.6.3，推送账号异常

### ISSUE THREAD

**Issue by JackZhouZhouZhou** [jumpserver/jumpserver#11630]
**JumpServer社区版v3.6.3，推送账号异常**
推送普通账号，提示：“FAILED! => {"changed": false, "msg": "Unable to connect to asset: encountered RSA key, expected OPENSSH key"}”
原来我们使用的是JumpServerV1.4.9-2，人工迁移到JumpServer社区版v3.6.3。一部分普通账号推送到服务器无法使用无法登录，几乎无法登录的是centos6服务器，而且还提示输入密码，但centos7版本的可以正常登录而且可以正常切换成root权限。
求大神解决！
![微信截图_20230920150531](https://github.com/jumpserver/jumpserver/assets/114642129/1b3bc05b-d772-410b-b016-e8920df4033e)
![微信截图_20230920145944](https://github.com/jumpserver/jumpserver/assets/114642129/26dc9753-018c-43ab-bdaa-8b5b92dbb357)
![image](https://github.com/jumpserver/jumpserver/assets/114642129/ba7359c9-ff34-45f7-97bf-9fcd6edf52f1)

另外一个问题，为什么重启./jmsctl.sh restart，总是提示“ERROR: No such service: lb”这个？
![image](https://github.com/jumpserver/jumpserver/assets/114642129/64193c5c-6198-46b2-b794-d54e607a16c4)

**Comment by wojiushixiaobai** [comment]
我不太清楚你的迁移过程，还请详细描述下。
新版本已经没有使用 lb 这个组件，可能要看下你的环境才知道啥原因导致的。

你可以在微信群或者 QQ 群联系下管理员远程看看什么问题。

**Comment by JackZhouZhouZhou** [comment]
实际上没有所谓的迁移，就是按照https://docs.jumpserver.org/zh/v3/ 这个文档部署的离线安装
然后用表格模板导入资产。128台只有16台无法登录，16台服务器有一个共同点都是centos6版本的

**Comment by JackZhouZhouZhou** [comment]
已加QQ群

**Comment by wojiushixiaobai** [comment]
`jms_lb` 问题通过下面 pr 修复
- fix: jumpserver/installer#351
