### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by yileinayn** [jumpserver/jumpserver#11639]
需求：
Windows的机器 首次登录提示需要修改密码，然后给用户一个修改密码的页面（堡垒机能够连接这个页面）
![41ba65440eebe0ce28ab3cfc52edecf](https://github.com/jumpserver/jumpserver/assets/77610565/d5eecca0-7d2f-46cf-bd39-71c1508b2356)
![75d5bef43a99f94c60195f1ff47aaa2](https://github.com/jumpserver/jumpserver/assets/77610565/1b9dd70a-2bb7-42ec-b646-9e97ae26ed96)
![9f65141fdd47f6595f00a54de5c9055](https://github.com/jumpserver/jumpserver/assets/77610565/0d036f9c-b30c-418b-a47d-df9ee1477a95)

**Comment by ibuler** [comment]
无计划
