### ISSUE TITLE
[Bug] 从3.1.1升级到3.6.4后admin等账户无法登录

### ISSUE THREAD

**Issue by kean0048** [jumpserver/jumpserver#11647]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**
Chrome Version 115.0.5790.170 (Official Build) (64-bit)

**Bug 描述**
因3.1.1版本有漏洞，公司要求升级，于是升级到3.6.4版本，使用curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash，这个命令升级的，但是升级完成后登录提示“配置文件存在问题，无法完成登录，请联系系统管理员解决问题，或查看更新说明”，我查看了更新说明，并没有特别需要设置的地方

**Bug 重现步骤(有截图更好)**
1. 使用 curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash升级
2. admin账户登录
3.无法登录

**Comment by kean0048** [comment]
![MicrosoftTeams-image (25)](https://github.com/jumpserver/jumpserver/assets/20370671/017cbc68-d998-411f-b35d-60eb99f725f1)

**Comment by LiaoSirui** [comment]
经测试 VERSION=v3.5.6 可以正常工作

可以尝试使用 http，http 不受影响

**Comment by kean0048** [comment]
# JumpServer configuration file example.
#
# 如果不了解用途可以跳过修改此配置文件, 系统会自动填入
# 完整参数文档 https://docs.jumpserver.org/zh/v3/guide/env/

################################## 镜像配置 ###################################
#
# 国内连接 docker.io 会超时或下载速度较慢, 开启此选项使用华为云镜像加速
# 取代旧版本 DOCKER_IMAGE_PREFIX
#
DOCKER_IMAGE_MIRROR=1

################################## 安装配置 ###################################
#
# JumpServer 数据库持久化目录, 默认情况下录像、任务日志都在此目录
# 请根据实际情况修改, 升级时备份的数据库文件(.sql)和配置文件也会保存到该目录
#
VOLUME_DIR=/data/jumpserver

# 加密密钥, 迁移请保证 SECRET_KEY 与旧环境一致, 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 SECRET_KEY
#
SECRET_KEY=YmFkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxYzY3

# 组件向 core 注册使用的 token, 迁移请保持 BOOTSTRAP_TOKEN 与旧环境一致,
# 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 BOOTSTRAP_TOKEN
#
BOOTSTRAP_TOKEN=YmFkdddddddddddddddddddddddMWIy

# 日志等级 INFO, WARN, ERROR
#
LOG_LEVEL=ERROR

# JumpServer 容器使用的网段, 请勿与现有的网络冲突, 根据实际情况自行修改
#
DOCKER_SUBNET=192.168.250.0/24

# ipv6 nat, 正常情况下无需开启
# 如果宿主不支持 ipv6 开启此选项将会导致无法获取真实的客户端 ip 地址
#
USE_IPV6=0
DOCKER_SUBNET_IPV6=fc00:1010:1111:200::/64

################################# MySQL 配置 ##################################
# 外置 MySQL 需要输入正确的 MySQL 信息, 内置 MySQL 系统会自动处理
#
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=YmFxxxxxxxxxxxxxxMWIyLW
DB_NAME=jumpserver

# 如果外置 MySQL 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/mysql_ssl/
#
# DB_USE_SSL=True

################################# Redis 配置 ##################################
# 外置 Redis 需要请输入正确的 Redis 信息, 内置 Redis 系统会自动处理
#
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=YmFxxxxxxxxxxxxMWIyLW

# 如果使用外置 Redis Sentinel, 请手动填写下面内容
#
# REDIS_SENTINEL_HOSTS=mymaster/192.168.100.1:26379,192.168.100.1:26380,192.168.100.1:26381
# REDIS_SENTINEL_PASSWORD=your_sentinel_password
# REDIS_PASSWORD=your_redis_password
# REDIS_SENTINEL_SOCKET_TIMEOUT=5

# 如果外置 Redis 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/redis_ssl/
#
# REDIS_USE_SSL=True

################################## 访问配置 ###################################
# 对外提供服务端口, 如果与现有服务冲突请自行修改
#
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_MYSQL_PORT=33061
MAGNUS_MARIADB_PORT=33062
MAGNUS_REDIS_PORT=63790
MAGNUS_POSTGRESQL_PORT=54320
MAGNUS_ORACLE_PORTS=30000-30030

################################# HTTPS 配置 #################################
# 参考 https://docs.jumpserver.org/zh/v3/installation/proxy/ 配置
#
HTTPS_PORT=443
# SERVER_NAME=your_domain_name
# SSL_CERTIFICATE=your_cert
# SSL_CERTIFICATE_KEY=your_cert_key
#

# Nginx 文件上传下载大小限制
#
CLIENT_MAX_BODY_SIZE=4096m

################################## 组件配置 ###################################
# 组件注册使用, 默认情况下向 core 容器注册, 集群环境需要修改为集群 vip 地址
#
CORE_HOST=http://core:8080
PERIOD_TASK_ENABLED=True

# Core Session 定义,
# SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期,
# SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
#
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=True

# Lion 开启字体平滑, 优化体验
#
JUMPSERVER_ENABLE_FONT_SMOOTHING=True

################################# XPack 配置 #################################
# XPack 包, 开源版本设置无效
#
RDP_PORT=3389

################################## 其他配置 ##################################
# 终端使用宿主 HOSTNAME 标识, 首次安装自动生成
#
SERVER_HOSTNAME=localhost.localdomain

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#
CURRENT_VERSION=v3.6.4

DOMAINS="10.184.74.1"

**Comment by kean0048** [comment]
2023-09-21 14:30:33 [db_port ERROR] (1054, "Unknown column 'assets_asset.gathered_info' in 'field list'")

**Comment by kean0048** [comment]
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Consume msg error: Connection closed by server.
2023-09-21 14:30:03 [connection ERROR] Retry #0 settings subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 settings subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.orgs_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.node_asset_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.orgs_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.node_asset_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.orgs_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 settings subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.node_asset_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.applet_host_change subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.applet_host_change subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.applet_host_change subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 settings subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.node_asset_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.orgs_mapping subscribe channel error: Error 111 connecting to redis:6379. Connection refused.
2023-09-21 14:30:03 [connection ERROR] Retry #0 fm.applet_host_change subscribe channel error: Error 111 connecting to redis:6379. Connection refused.

**Comment by pollyduan** [comment]
居然和我一样从3.1.1升级到3.6.4,也居然和我遇到了同一个问题。

小助手提示我： https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/
即在 /opt/jumpserver/config/coffig.txt中添加：

DOMAINS="demo.jumpserver.org"

### 请改为你自己的域名

好了，我接下来遇到了一个新的问题，web终端无法访问，报错： Connection websocket error

我还没解决，祝你好运

**Comment by jym503558564** [comment]
v3.6 版本为了安全，要求强制填写 DOMAINS 可信任域名才能正常访问服务，否则会提示错误码 400/403 导致无法无法访问页面
升级请参考官方文档，升级前请查看升级须知：v3.6.0https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/

**Comment by pollyduan** [comment]
websocket的问题解了，顺便来解释一下。

我的jumpserver 外面还有一个nginx，在外部的nginx挂在了ssl证书。之前因为安全问题添加了下面的请求头：

Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self'

我改成下面就好了，就是增加了一个wss:

Content-Security-Policy: default-src https: wss: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self'

奇怪的是，为什么3.1.1没问题呢？看起来是还是跟版本更新有关系。如果没用Content-Security-Policy 或许你遇不到。

**Comment by kean0048** [comment]
> 居然和我一样从3.1.1升级到3.6.4,也居然和我遇到了同一个问题。
> 
> 小助手提示我： https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/ 即在 /opt/jumpserver/config/coffig.txt中添加：
> 
> DOMAINS="demo.jumpserver.org"
> 
> ### 请改为你自己的域名
> 好了，我接下来遇到了一个新的问题，web终端无法访问，报错： Connection websocket error
> 
> 我还没解决，祝你好运

谢谢您的回复，但是您应该能看到在config.txt的结尾我是增加了增加的DOMIAINS配置的，但是为什么还有这也的错误提示？
Thanks.

**Comment by kean0048** [comment]
> jym503558564

Hi [jym503558564](https://github.com/jym503558564),
您好，感谢回复。
如我刚才答复的，我已经注意到这个问题，并在我的config.txt的结尾增加了这个配置，您可以仔细看下我贴的配置的最后，在版本号的下一行，我已经添加了DOMIAINS这个参数为内网IP地址了，但是为什么还有有错误？
谢谢！

**Comment by kean0048** [comment]
> 经测试 VERSION=v3.5.6 可以正常工作
> 
> 可以尝试使用 http，http 不受影响
> 
> 使用 v3.6.4 的有问题，配置文件如下：
> 
> ```
> server {
>     listen 80;
>     listen 443 ssl;
> 
>     server_tokens off;
>     client_max_body_size 0;
> 
>     # if ($scheme = http) {
>     #     return 301 https://$host:443$request_uri;
>     # }
> 
>     ssl_certificate /etc/nginx/conf.d/cert/tls.crt;
>     ssl_certificate_key /etc/nginx/conf.d/cert/tls.key;
> 
>     location /player/ {
>         try_files $uri / /index.html;
>         alias /opt/player/;
>     }
> 
>     location /ui/ {
>         try_files $uri / /index.html;
>         alias /opt/lina/;
>     }
> 
>     location /luna/ {
>         try_files $uri / /index.html;
>         alias /opt/luna/;
>     }
> 
>     location /download/ {
>         alias /opt/download/;
>     }
> 
>     location /static/ {
>         root /opt/jumpserver/data/;
>     }
> 
>     location /koko/ {
>         proxy_pass http://koko:5000;
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_request_buffering off;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
> 
>     location /lion/ {
>         proxy_pass http://lion:8081;
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_request_buffering off;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
> 
>     # location /chen/ {
>     #     proxy_pass http://chen:8082;
>     #     proxy_buffering off;
>     #     proxy_http_version 1.1;
>     #     proxy_set_header Upgrade $http_upgrade;
>     #     proxy_set_header Connection "upgrade";
>     #     proxy_set_header X-Real-IP $remote_addr;
>     #     proxy_set_header Host $host;
>     #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     #     proxy_ignore_client_abort on;
>     #     proxy_connect_timeout 600;
>     #     proxy_send_timeout 600;
>     #     proxy_read_timeout 600;
>     #     send_timeout 6000;
>     # }
> 
>     # location /kael/ {
>     #     proxy_pass http://kael:8083;
>     #     proxy_buffering off;
>     #     proxy_http_version 1.1;
>     #     proxy_set_header Upgrade $http_upgrade;
>     #     proxy_set_header Connection "upgrade";
>     #     proxy_set_header X-Real-IP $remote_addr;
>     #     proxy_set_header Host $host;
>     #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     #     proxy_ignore_client_abort on;
>     #     proxy_connect_timeout 600;
>     #     proxy_send_timeout 600;
>     #     proxy_read_timeout 600;
>     #     send_timeout 6000;
>     # }
> 
>     location /ws/ {
>         proxy_pass http://core:8080;
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> 
>     location ~ ^/(core|api|media)/ {
>         proxy_pass http://core:8080;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $http_host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> 
>     location / {
>         rewrite ^/(.*)$ /ui/$1 last;
>     }
> }
> ```

Hi LiaoSirui,

谢谢您的答复。
您说的版本好像也满足要求，以下是我们的安全团队的提示“
官方已发布新版本修复了该漏洞，请受影响的用户升级到安全版本：
JumpServer >= v3.5.5
JumpServer >= v3.6.4”
所以您建议的3.5.6是可以升级的，那么我想详细了解下这个过程，因为我现在已经升级到3.6.4了，**该如何做才能升级到您建议的3.5.6这个版本？**
然后就是您给的这个配置是3.6.4的吗？我需要做什么，按照您给你文件去配置吗？但是我不知道这个配置在那个文件在那个目录下呢？希望您给予更多的信息支援。
谢谢！

**Comment by kean0048** [comment]
> websocket的问题解了，顺便来解释一下。
> 
> 我的jumpserver 外面还有一个nginx，在外部的nginx挂在了ssl证书。之前因为安全问题添加了下面的请求头：
> 
> Content-Security-Policy: default-src https: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self'
> 
> 我改成下面就好了，就是增加了一个wss:
> 
> Content-Security-Policy: default-src https: wss: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self'
> 
> 奇怪的是，为什么3.1.1没问题呢？看起来是还是跟版本更新有关系。如果没用Content-Security-Policy 或许你遇不到。

Hi [pollyduan](https://github.com/pollyduan)，

您好，感谢回复！
是的3.1.1运行状态良好，没有什么错误信息，近期公司安全部门提示有漏洞，所以我按照要求的版本和我们的官方提示升级，升级后就不能用了，我只增加了DOMAINS的配置，其他的都没有动过，保持原有配置的，但是您可以看到我贴的图片，所有用户都无法登录了。如果您需要更多的log请告诉我。

谢谢！

**Comment by ibuler** [comment]
DOMAINS=上面提示的那个 IP

**Comment by wojiushixiaobai** [comment]
试试下面的命令：
```sh
# cd 到 installer 安装目录，如 cd /opt/jumpserver-installer-v3.6.4
./jmsctl.sh down
systemctl stop docker docker.socket

ps aux | grep containerd # 如果不为空则需要 kill 掉 containerd 的进程，或者重启一次服务器

systemctl restart docker
./jmsctl.sh start
```

检查问题是否解决，需要这样做的原因可能是由于 `iptables` 那边出了问题，`client ip` 传递的信息不正确，需要重启一下 `docker`

**Comment by kean0048** [comment]
Hi @wojiushixiaobai ,

谢谢您的答复，但是我试了一下，在登录界面好像没有错误提示里，但是我输入用户名和密码后的页面一直加载不出来。
我的微信：15012890305
谢谢

**Comment by kean0048** [comment]
Hi all,
我昨天看到有最新的3.7.0版本发布了，我就升级了，现在好像是只有admin无法登录，其他的可以登录了，这又是什么情况，用admin输入密码后进入状态一直在空白页

谢谢！

**Comment by BaiJiangJie** [comment]
好的， @feng626 帮忙看一下是什么问题。

DOMAINS 配置的时候，如果端口是 80 和  443 默认要省略。 @kean0048

**Comment by feng626** [comment]
尝试无痕登录 看看后台日志具体报什么错误

**Comment by jym503558564** [comment]
该问题是否还存在，可联系我们社区管理员帮忙远程定位下问题。有其他问题，可再次提issues。

**Comment by vinaquino** [comment]
草你妈了个逼，V2，V3安装后都一样, admin无法登陆，* The username or password you entered is incorrect, please enter it again. You can also try 3 times (The account will be temporarily locked for 30 minutes), 好东西被这帮狗团队给糟蹋了，草你妈了个B的jumpserve团队，狗东西，干你妈的技术。

**Comment by vinaquino** [comment]
草你妈了个逼，V2，V3安装后都一样, admin无法登陆，* The username or password you entered is incorrect, please enter it again. You can also try 3 times (The account will be temporarily locked for 30 minutes), 好东西被这帮狗团队给糟蹋了，草你妈了个B的jumpserve团队，狗东西，干你妈的技术。

**Comment by LiaoSirui** [comment]
> 草你妈了个逼，V2，V3安装后都一样, admin无法登陆，* The username or password you entered is incorrect, please enter it again. You can also try 3 times (The account will be temporarily locked for 30 minutes), 好东西被这帮狗团队给糟蹋了，草你妈了个B的jumpserve团队，狗东西，干你妈的技术。

文明文明...

**Comment by LiaoSirui** [comment]
> > 经测试 VERSION=v3.5.6 可以正常工作
> > 可以尝试使用 http，http 不受影响
> > 使用 v3.6.4 的有问题，配置文件如下：
> > ```
> > server {
> >     listen 80;
> >     listen 443 ssl;
> > 
> >     server_tokens off;
> >     client_max_body_size 0;
> > 
> >     # if ($scheme = http) {
> >     #     return 301 https://$host:443$request_uri;
> >     # }
> > 
> >     ssl_certificate /etc/nginx/conf.d/cert/tls.crt;
> >     ssl_certificate_key /etc/nginx/conf.d/cert/tls.key;
> > 
> >     location /player/ {
> >         try_files $uri / /index.html;
> >         alias /opt/player/;
> >     }
> > 
> >     location /ui/ {
> >         try_files $uri / /index.html;
> >         alias /opt/lina/;
> >     }
> > 
> >     location /luna/ {
> >         try_files $uri / /index.html;
> >         alias /opt/luna/;
> >     }
> > 
> >     location /download/ {
> >         alias /opt/download/;
> >     }
> > 
> >     location /static/ {
> >         root /opt/jumpserver/data/;
> >     }
> > 
> >     location /koko/ {
> >         proxy_pass http://koko:5000;
> >         proxy_buffering off;
> >         proxy_http_version 1.1;
> >         proxy_request_buffering off;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection "upgrade";
> >         proxy_set_header X-Real-IP $remote_addr;
> >         proxy_set_header Host $host;
> >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >         proxy_ignore_client_abort on;
> >         proxy_connect_timeout 600;
> >         proxy_send_timeout 600;
> >         proxy_read_timeout 600;
> >         send_timeout 6000;
> >     }
> > 
> >     location /lion/ {
> >         proxy_pass http://lion:8081;
> >         proxy_buffering off;
> >         proxy_http_version 1.1;
> >         proxy_request_buffering off;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection "upgrade";
> >         proxy_set_header Connection $http_connection;
> >         proxy_set_header X-Real-IP $remote_addr;
> >         proxy_set_header Host $host;
> >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >         proxy_ignore_client_abort on;
> >         proxy_connect_timeout 600;
> >         proxy_send_timeout 600;
> >         proxy_read_timeout 600;
> >         send_timeout 6000;
> >     }
> > 
> >     # location /chen/ {
> >     #     proxy_pass http://chen:8082;
> >     #     proxy_buffering off;
> >     #     proxy_http_version 1.1;
> >     #     proxy_set_header Upgrade $http_upgrade;
> >     #     proxy_set_header Connection "upgrade";
> >     #     proxy_set_header X-Real-IP $remote_addr;
> >     #     proxy_set_header Host $host;
> >     #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     #     proxy_ignore_client_abort on;
> >     #     proxy_connect_timeout 600;
> >     #     proxy_send_timeout 600;
> >     #     proxy_read_timeout 600;
> >     #     send_timeout 6000;
> >     # }
> > 
> >     # location /kael/ {
> >     #     proxy_pass http://kael:8083;
> >     #     proxy_buffering off;
> >     #     proxy_http_version 1.1;
> >     #     proxy_set_header Upgrade $http_upgrade;
> >     #     proxy_set_header Connection "upgrade";
> >     #     proxy_set_header X-Real-IP $remote_addr;
> >     #     proxy_set_header Host $host;
> >     #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     #     proxy_ignore_client_abort on;
> >     #     proxy_connect_timeout 600;
> >     #     proxy_send_timeout 600;
> >     #     proxy_read_timeout 600;
> >     #     send_timeout 6000;
> >     # }
> > 
> >     location /ws/ {
> >         proxy_pass http://core:8080;
> >         proxy_buffering off;
> >         proxy_http_version 1.1;
> >         proxy_set_header Upgrade $http_upgrade;
> >         proxy_set_header Connection "upgrade";
> >         proxy_set_header X-Real-IP $remote_addr;
> >         proxy_set_header Host $host;
> >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     }
> > 
> >     location ~ ^/(core|api|media)/ {
> >         proxy_pass http://core:8080;
> >         proxy_set_header X-Real-IP $remote_addr;
> >         proxy_set_header Host $http_host;
> >         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> >     }
> > 
> >     location / {
> >         rewrite ^/(.*)$ /ui/$1 last;
> >     }
> > }
> > ```
> 
> Hi LiaoSirui,
> 
> 谢谢您的答复。 您说的版本好像也满足要求，以下是我们的安全团队的提示“ 官方已发布新版本修复了该漏洞，请受影响的用户升级到安全版本： JumpServer >= v3.5.5 JumpServer >= v3.6.4” 所以您建议的3.5.6是可以升级的，那么我想详细了解下这个过程，因为我现在已经升级到3.6.4了，**该如何做才能升级到您建议的3.5.6这个版本？** 然后就是您给的这个配置是3.6.4的吗？我需要做什么，按照您给你文件去配置吗？但是我不知道这个配置在那个文件在那个目录下呢？希望您给予更多的信息支援。 谢谢！

我有点忘记了，是不是因为服务端没有拿到客户端真实 IP 呀， 有时间我协助你们 debug 下。需不需要开 proxy protocol.
