### ISSUE TITLE
[提问] 升级到3.7之后ping不通docker

### ISSUE THREAD

**Issue by Mayter** [jumpserver/jumpserver#11658]
**请描述您的问题.**
在线安装的,进入docker web里面可以访问80端口，但是在宿主机访问不了80 ，但是端口都没有问题，curl http://127.0.0.1也报错

![2](https://github.com/jumpserver/jumpserver/assets/6148807/091b88d8-fc83-46b3-aa88-bf0ce2b716eb)
![1](https://github.com/jumpserver/jumpserver/assets/6148807/9e03451c-35ec-4f1e-8e80-095be71d38d7)
![3](https://github.com/jumpserver/jumpserver/assets/6148807/c198b210-6df9-48ec-beac-fa637f98db59)

**Comment by wojiushixiaobai** [comment]
重启 docker 试试，不要修改 iptables 或者 firewalld

**Comment by Mayter** [comment]
我默认是centos7 系统，3.10.0.327内核，升级为3.10.0-1160解决
