### ISSUE TITLE
邮件设置输入完smtp 密码后前端显示无该字段

### ISSUE THREAD

**Issue by TelDragon** [jumpserver/jumpserver#1165]
[简述你的问题]
配置完smtp 服务后。smtp 密码也写了，点击了提交。程序提示重启程序。程序正常重启后。刷新页面 点击“测试邮件” 提示错误 
（“error“：”{EMAIL_HOST_PASSWORD：该字段不能为空}）
不好意思不怎么会贴图片。

但是用户注册没有问题正常收到邮件并注册。
就是不能点击测试邮件。给人的感觉就是 密码没有输入。但是实际上密码已经生效，
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![SMTP提交](https://github.com/TelDragon/Dragon/blob/master/image/QQ%E5%9B%BE%E7%89%8720180403212213.png?raw=true)

![SMTP错误](https://github.com/TelDragon/Dragon/blob/master/image/QQ%E5%9B%BE%E7%89%8720180403205554.png?raw=true)
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
先测试再保存，然后重启jumpserver服务。
系统设置修改需要重启的问题之后会解决掉

**Comment by jacky0922** [comment]
果然，需要重启，并且start all之后等完全重启好之后是可以的

**Comment by krisbai** [comment]
![qq20180517-115824](https://user-images.githubusercontent.com/10414888/40156042-a75157d4-59c9-11e8-8714-e95aed922e1c.png)
有人遇到过这种情况吗？邮件配置好之后测试报超时。。。

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
