### ISSUE TITLE
[Question] 自定义sftp目录是否支持变量

### ISSUE THREAD

**Issue by magicJie** [jumpserver/jumpserver#11652]
**请描述您的问题.**
如图，设置sftp为动态目录无法识别，是不支持变量，还是使用的方式不对？
![image](https://github.com/jumpserver/jumpserver/assets/6937525/4aea6644-de8d-4965-968b-e056d0520c9a)

**Comment by BaiJiangJie** [comment]
<img width="1253" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/126ef04b-c3f0-47ce-a228-b5c17a1fe39e">

新版本支持变量。
