### ISSUE TITLE
将旧版本数据库users_user表导入到新的数据库，控制台用户列表不显示

### ISSUE THREAD

**Issue by TIGERRAN** [jumpserver/jumpserver#11661]
将老的版本2.2.3 数据库的users_user表dump出来， 导入到版本3.6.4的数据库，发现控制台上用户列表不显示导入的用户信息
同时也将users_user_groups、users_usergroup 关联的表也导入了，用户组可以看到信息。请问怎么解决呢
mysql> show create database jumpserver;
+------------+-----------------------------------------------------------------------------------------------------------+
| Database   | Create Database                                                                                           |
+------------+-----------------------------------------------------------------------------------------------------------+
| jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */ |

**Comment by jym503558564** [comment]
先升级到V2.28版本，再进行测试看看。

**Comment by TIGERRAN** [comment]
> 先升级到V2.28版本，再进行测试看看。

![image](https://github.com/jumpserver/jumpserver/assets/41050950/b6720297-6a1e-4152-938e-e2a324ad6b60)
升级了V2.28版本后导入数据还是看不到？

**Comment by ibuler** [comment]
不支持导入
