### ISSUE TITLE
[Bug] 升级到 v3.7.0 版本后，无法通过 Web 终端连接到 Web 资产

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#11662]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v3.7.0

**浏览器版本**
版本 116.0.5845.188（正式版本）

**Bug 描述**
v3.6.4 升级到 v3.7.0 版本后，无法通过 Web 终端连接到 Web 资产
连接 Web 资产时，会跳出要求下载客户端的界面，点击取消后就没有任何反应了
![aba5a6fa2921e01cb5894b09cd4d8cf](https://github.com/jumpserver/jumpserver/assets/32380085/e5cef8d5-8516-4261-9c6b-42ff633d97e8)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by jym503558564** [comment]
把 JumpServer 客户端升级到最新版本进行测试下呢？

**Comment by saszhuqing** [comment]
> 把 JumpServer 客户端升级到最新版本进行测试下呢？

连接Web资产是不需要客户端的

**Comment by ryswork1993** [comment]
> > 把 JumpServer 客户端升级到最新版本进行测试下呢？
> 
> 连接Web资产是不需要客户端的

你用docker  ps -a看下组件版本

**Comment by saszhuqing** [comment]
> > > 把 JumpServer 客户端升级到最新版本进行测试下呢？
> > 
> > 
> > 连接Web资产是不需要客户端的
> 
> 你用docker ps -a看下组件版本

现在已经通过快照恢复到 v3.6.4 版本了，晚点克隆一台出来测试看看

**Comment by jym503558564** [comment]
已修复，待发版。https://github.com/jumpserver/luna/pull/965/files

**Comment by ccx0lw** [comment]
可以自己先修复
/opt/luna/main.04221242cad8df71c5ba.js
中找到  &&"web"!==a.appletConnectMethod?
把 web 改成 client 即可

![image](https://github.com/jumpserver/jumpserver/assets/20969915/d9aceb7c-248e-479e-85b1-d42617d28473)


然后 需要清空下浏览器缓存。

**Comment by jym503558564** [comment]
v3.7.1已修复，请更新至最新版本进行测试。
