### ISSUE TITLE
[Feature] web终端默认主题增加到用户个人设置

### ISSUE THREAD

**Issue by zeng202211** [jumpserver/jumpserver#11671]
环境: 浏览器自动重置, web终端的默认主题不好看, 浏览器关闭后重新访问, 主题需要重新设置一次.
需求: 希望可以将web终端默认主题增加到用户个人设置进行修改配置.
谢谢.

**Comment by pika-FENG** [comment]
貌似每次升级后 web终端主题也会失效

**Comment by BaiJiangJie** [comment]
你指的是什么默认主题？

**Comment by pika-FENG** [comment]
锋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月25日(星期一) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Feature] web终端默认主题增加到用户个人设置 (Issue #11671)





 
你指的是什么默认主题？

**Comment by pika-FENG** [comment]
<img width="393" alt="图片" src="https://github.com/jumpserver/jumpserver/assets/91412927/34acd557-e06f-4803-acd6-7b3e1cb5271b">

**Comment by BaiJiangJie** [comment]
好的，计划 v3.8 版本支持一下。
支持持久化保存到个人设置。

**Comment by LeeEirc** [comment]
v3.8.0 已更新。
