### ISSUE TITLE
[Feature] web终端增加设备语言编码调整功能

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11676]
Linux设备系统编码和某些程序编码，日志编码并未保持一致，此时需要每次修改设备平台的语言编码才可以正常显示，是否可以增加自助切换的按钮

**Comment by ibuler** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/17382885/d4763c72-06f8-407b-9667-29db69b93d39)
