### ISSUE TITLE
登录日志展示丢失

### ISSUE THREAD

**Issue by navyaijm2017** [jumpserver/jumpserver#1167]
[简述你的问题]

##### 使用版本
1.0.0

##### 问题复现步骤
1. 用户A通过web登录jumpser，命令记录都已经记录到A用户的操作命令了，仪表盘的“登录记录”也记录了A的登录记录，但是在用户管理-->登录日志里面不显示A用户的登录记录

##### 具体表现[截图可能会更好些,最好能截全]
![11](https://user-images.githubusercontent.com/29217326/38284244-d69ff8be-37ec-11e8-9870-452fac01f46e.png)
![22](https://user-images.githubusercontent.com/29217326/38284248-dc05998a-37ec-11e8-9b1d-73d2e7b63060.png)
![33](https://user-images.githubusercontent.com/29217326/38284255-df8254b8-37ec-11e8-87b0-249b32fa20d1.png)

[注:] 完成后请关闭 issue

**Comment by liyanxia** [comment]
users_loginlog 表的字符集需要改成utf8 包括 列的字符集

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
