### ISSUE TITLE
Linux平台为GBK字符集的情况下，luna web控制台rz和sz无法正常上传和下载[Bug] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#11675]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
≤v3.6.4
注：更高版本未试过

**浏览器版本**
国际版Firefox 117.0.1 (64 位)

**Bug 描述**
Linux平台选择GBK字符集的情况下，luna web控制台rz和sz无法正常上传和下载。并且执行命令的时候当前会话会卡主无法退出。
目前Linux发行版为CentOS5、6、7的64位都有这个问题。另外，Linux资产操作系统本身字符集无论是否与堡垒机匹配，问题都存在。

**Bug 重现步骤(有截图更好)**
1.克隆现有Linux平台为Linux-GBK，并选择字符集为“GBK”：
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/21083ada-cf6d-41ac-a501-843a1497a0b2)
2.在堡垒机中创建资产，并选择Linux-GBK。
3.通过堡垒机web控制台访问此资产，执行rz或sz命令会出现异常。如图：
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/2901cb41-6aba-408e-bda4-4c3bc05a47d1)
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/42043d08-9429-46ee-a018-f2b9854b3ba0)

**Comment by LeeEirc** [comment]
有可能，如果使用了gbk，koko对数据进行 UTF8 到 GBK 的编码转换，可能就会丢失 rz 的协议数据，暂时不好处理。

**Comment by BaiJiangJie** [comment]
上传下载编码不一致的情况，暂时搞不定。
