### ISSUE TITLE
[Bug] 远程应用连接失败

### ISSUE THREAD

**Issue by lxsexl** [jumpserver/jumpserver#11677]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
社区版v3.5.6

**浏览器版本**
Chrome v117.0.5938.92

**Bug 描述**
web资产，使用jump client调用mstsc连接发布机失败，而且只能用jumpserver client调用，不能使用WEBGUI，卸载客户端就提示你下载。jumpserver是一键安装，宿主机是debian11，发布机也是全新安装的Server2019，部署成功，负载正常，应用发布正常，账号测试正常。jumpserver client使用的是jumpserver自带的版本，3.5.6自带的是1.1.8。在客户端调用mstsc连接时，我追踪了连接的IP，居然是堡垒机的IP，而不是发布机的IP。我先后安装3.7.0和3.6.5版本都试过，都是一样的毛病。

**Bug 重现步骤(有截图更好)**

![A](https://github.com/jumpserver/jumpserver/assets/113326833/e5adf109-a32d-4571-9497-efc195d3089f)
![B](https://github.com/jumpserver/jumpserver/assets/113326833/f26b10b2-78f8-4151-9bd5-dcf51b332913)
![C](https://github.com/jumpserver/jumpserver/assets/113326833/68b64156-ff68-4d58-941f-c8f6a2be8a19)
![D](https://github.com/jumpserver/jumpserver/assets/113326833/4553311a-620e-4338-a103-c21ede6f1f75)
![E](https://github.com/jumpserver/jumpserver/assets/113326833/898ae474-8d43-4b59-b4c8-423ad1a23394)
![F](https://github.com/jumpserver/jumpserver/assets/113326833/e7ce0e50-4d8b-4635-87ec-57fe5bbdc802)

**Comment by SpeedCloudNoc** [comment]
对的 刚刚我也复现了该问题，机器是centos7 一键部署，设置的web资产连接时候根本就没有WEBGUI的连接，只有调用client
然后client有连接失败，因为前几天我们测试的时候是可以正常的。今天重新部署就有问题了，期待回复

**Comment by ibuler** [comment]
收到，今天修复

**Comment by jym503558564** [comment]
已修复，待发版。

**Comment by lxsexl** [comment]
期待新版本测试

**Comment by SpeedCloudNoc** [comment]
> 已修复，待发版。

大概多久会发修复版本，马上国庆，公司一直催 或者有临时解决方案吗？

**Comment by maninhill** [comment]
3.7.1已经发布了，请自行下载升级。

**Comment by jym503558564** [comment]
已发版，可升级进行测试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SpeedCloudNoc ***@***.***&gt;
发送时间: 2023年9月26日 16:35
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [Bug] 远程应用连接失败 (Issue #11677)





  
已修复，待发版。
  
大概多久会发修复版本，马上国庆，公司一直催 或者有临时解决方案吗？

**Comment by lxsexl** [comment]
已测试，现在直接调用WEB GUI了，可以正常连接。

**Comment by jym503558564** [comment]
感谢支持和使用JumpServer

**Comment by joy88888888** [comment]
升级后好了，还以为咋的了呢

**Comment by lxsexl** [comment]
magnus日志显示：
[ERRO] Post "http://core:8080/api/v1/terminal/terminal-registrations/": dial tcp 192.168.250.7:8080: connect: connection refused
这是什么情况？192.168.250.7是core的IP。
