### ISSUE TITLE
[Question] 请问3.7版本远程应用是必须要要客户端才能使用吗？

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#11672]
**请描述您的问题.**
请问3.7版本远程应用是必须要客户端才能使用吗？
还有用户名现在是不能为中文吗？中文用户名否则登录会提示Internal Server Error
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/ce703dc8-3f92-4bc1-9b0a-7c93cb8f42c7)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/8653c500-6fa2-4f6a-a28f-3756cf6c2238)

**Comment by jym503558564** [comment]
客户端问题，已修复。

**Comment by flacce** [comment]
> 客户端问题，已修复。

v3.7.1修复的吧，中文字符往后用户名就不能使用了吗？

**Comment by jym503558564** [comment]
用户名中文登录失败，也已修复。请升级至3.7.1版本进行测试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: flacce ***@***.***&gt;
发送时间: 2023年9月26日 15:00
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [Question] 请问3.7版本远程应用是必须要要客户端才能使用吗？ (Issue #11672)





  
客户端问题，已修复。
  
v3.7.1修复的吧，中文字符往后用户名就不能使用了吗？

**Comment by flacce** [comment]
> 用户名中文登录失败，也已修复。请升级至3.7.1版本进行测试。 发自我的iPhone
> [… ](#)
> ------------------ 原始邮件 ------------------ 发件人: flacce ***@***.***&gt; 发送时间: 2023年9月26日 15:00 收件人: jumpserver/jumpserver ***@***.***&gt; 抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [jumpserver/jumpserver] [Question] 请问3.7版本远程应用是必须要要客户端才能使用吗？ (Issue #11672) 客户端问题，已修复。 v3.7.1修复的吧，中文字符往后用户名就不能使用了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，这两个问题都是昨天在v3.7.1版本中测试的，中文用户名测试如图。
![bandicam 2023-09-27 09-56-57-443](https://github.com/jumpserver/jumpserver/assets/64127000/0fefe95e-785b-451b-bdc1-c2ab14a1a45a)
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.41
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/63c398f0-279c-4be7-ae5e-b2d8b982b4b2)

**Comment by flacce** [comment]
实测直到昨天晚上v3.7.2版本发布，中文用户名登录报错问题才修复。真不知道您用的是不是发布的v3.7.1复现的
