### ISSUE TITLE
[Bug] 邮件后缀不生效的问题

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#11689]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v 3.6.4

**浏览器版本**
Chrome 116.0.5845.188

**Bug 描述**
【系统设置】-【消息通知】-【邮箱后缀】配置不生效

**Bug 重现步骤(有截图更好)**
![GIF 2023-9-25 16-55-01](https://github.com/jumpserver/jumpserver/assets/40846859/594725ee-9a72-4de5-bd23-932811f4760c)

**Comment by BaiJiangJie** [comment]
@jym503558564 可以复现吗？

**Comment by jym503558564** [comment]
已复现，待开发修复。

**Comment by BaiJiangJie** [comment]
v3.7.2 中会修复。

**Comment by BaiJiangJie** [comment]
新版本已修复。
