### ISSUE TITLE
[Bug] 3.7.0 快捷命令通过raw批量操作网络设备报错

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11681]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.0

**浏览器版本**

**Bug 描述**
![image](https://github.com/jumpserver/jumpserver/assets/44529247/4b0d9e29-a595-4cec-98f9-912a382a4abc)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ryswork1993** [comment]
> 你的网络设备应该比较旧，有些 ssh 算法已经被废弃了，手动在 core 和 celery 里修改下 `/root/.ssh/config`文件，添加下不安全算法，如果可以解决，后续会优化下这里
> 
> ```
> Host *
>   KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
>   Ciphers +aes128-cbc
>   HostKeyAlgorithms +ssh-rsa
>   PubkeyAcceptedAlgorithms +ssh-rsa
> ```
将您给出的内容复制到jms_core和jms_celery容器的/root/.ssh/config里后执行交换机还是有报错
![image](https://github.com/jumpserver/jumpserver/assets/44529247/5e485e5a-bab0-4278-b8b8-a0dff771a02e)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/b78bc625-e83d-4353-bde6-143cf34d3b71)

**Comment by ryswork1993** [comment]
按照您给的配置粘贴之后提示这个






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年9月27日 16:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Bug] 3.7.0 快捷命令通过raw批量操作网络设备报错 (Issue #11681) |

抱歉给贴错配置了，主要是给 KexAlgorithms 增加两个算法，应该是类似如下配置：

Host *
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
	Ciphers +aes128-cbc
	KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
	HostKeyAlgorithms +ssh-rsa

**Comment by ryswork1993** [comment]
> 按照您给的配置粘贴之后提示这个
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年9月27日 16:36 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [jumpserver/jumpserver] [Bug] 3.7.0 快捷命令通过raw批量操作网络设备报错 (Issue #11681) | 抱歉给贴错配置了，主要是给 KexAlgorithms 增加两个算法，应该是类似如下配置： Host * StrictHostKeyChecking no UserKnownHostsFile /dev/null Ciphers +aes128-cbc KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 HostKeyAlgorithms +ssh-rsa — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

加上您给的配置之后，华三设备通过raw执行成功，华为的各系列设备都提示
![image](https://github.com/jumpserver/jumpserver/assets/44529247/1e41d069-f065-430c-a6c2-33a4de3bb45a)

**Comment by LeeEirc** [comment]
已经线下联系处理
