### ISSUE TITLE
历史会话 回放功能默认不可用！

### ISSUE THREAD

**Issue by TelDragon** [jumpserver/jumpserver#1169]
[简述你的问题]
默认安装完jump系统后 链接测试 sshlinux 主机。 点击回放提示下载失败。然后查看了下 回放的路径
“http://192.168.1.199/luna/replay/f7832f44-c1be-4826-b8ac-870e6778f07f”
登录服务器查看
/opt/luna/ 下是没有replay 目录的。

然后手动创建 replay 目录 解决。

考虑 是否跟 luna 目录权限有关 然后查看了下 有权限。

是否是 luna git 库中将 replay 目录忽略掉了？

第二个问题。 .
自行解决回放后 再web 登录linux 主机 创建 文本 写入中文字符。

回放时 写入回放 不会显示中文 而是其他乱码格式。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
第二个问题的截图
![中文回放](https://github.com/TelDragon/Dragon/blob/master/image/QQ%E5%9B%BE%E7%89%8720180404120245.png?raw=true)
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
第一个问题，复现时暂时没有发现，请说明下环境（包括路径及权限）
第二个问题看图
![qq20180404-141441](https://user-images.githubusercontent.com/24326988/38291821-ff91d39c-3813-11e8-9161-ab75dc01c5fe.jpg)
无法复现。建议更换浏览器再尝试

**Comment by Jonnter** [comment]
回放问题怎么解决的呢？luna目录下是没有replay目录的，连接走的socker.io的

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
