### ISSUE TITLE
[Bug] 资产添加账号错误

### ISSUE THREAD

**Issue by jerry-zww** [jumpserver/jumpserver#11691]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.6.4

**浏览器版本**

Chrome 114.0.

**Bug 描述**

为Linux资产添加账号，提示：密码不能包含 `{{` 字符

**Bug 重现步骤(有截图更好)**
1. 添加Linux资产
2. 打开资产列表
3. 打开资产详情中的账号列表
4. 添加账号
5. 输入账号信息，密码类型为密码，密码中包括特殊字符 - 对Linux是允许和接受的
6. 点击提交，即看到错误提示信息

**Comment by SnowsonZ** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/12555482/af57c14d-8ff9-4924-90b7-2bdd41f231de)
同样的问题。在ssh 登录 Linux时报错。密码中包含单引号等特殊字符。

**Comment by BaiJiangJie** [comment]
是的，不能包含这些特殊字符。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11722

关注这个 issues。
