### ISSUE TITLE
[Bug] v3.1.2 版本升级数据库表结构变更报错

### ISSUE THREAD

**Issue by 1-step** [jumpserver/jumpserver#11690]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
Jumpserver V3.1.2

**Bug 描述**
Jumpserver 从 V3.1.2 升级到 V3.2.0 报错（installer 部署，使用外部数据库）

> [root@gzwxhcn jumpserver-installer-v3.1.2]# ./jmsctl.sh upgrade

执行之后，报错以下信息

> django.db.utils.OperationalError:` (1050, "Table 'assets custom' already exists")
[ERROR] Failed to change the table structure!

报错并不总是提示 “assets custom” 已存在，有时候是其他表

**Bug 重现步骤(有截图更好)**
1. installer 升级操作： ./jmsctl.sh upgrade
2. 升级过程到 Running migrations 时，提示数据库迁移失败
![2d2e3b6e26867c08d01c3a194aad313](https://github.com/jumpserver/jumpserver/assets/25605874/1673d3a9-902b-42e2-99c6-b5aae3e9a0ba)
3. 报错内容如下
![2f7e58c506f85ec138be9591695d8c3](https://github.com/jumpserver/jumpserver/assets/25605874/da84d185-0e48-406d-a724-85387cb64a29)
> django.db.utils.OperationalError:` (1050, "Table 'assets custom' already exists")

**已经试过的解决方法**
1. 查到有可能是数据库的问题，试过 drop 原库，升级到新版本（这一步没有报错），导入原库备份之后，./jmsctl start 启动 Jumpserver，容器启动失败，查看容器日志，内容和上面报错一致
2. 怀疑是表结构有改动，只 dump 数据忽略表结构之后，drop 原库，升级到新版本（升级没有问题），导入原数据时看到有字段错误返回，容器启动成功，但是前端页面拉不到资产信息

**Comment by BaiJiangJie** [comment]
整体来看，是数据库表的问题。原来的数据库有自己做过什么变更吗？

**Comment by BaiJiangJie** [comment]
看报错是数据库重复升级了，中间升级过程中不要中断，还原数据库重试一下。

还原回去先看一下是否存在 assets_custom 表。

**Comment by 1-step** [comment]
> 看报错是数据库重复升级了，中间升级过程中不要中断，还原数据库重试一下。
> 
> 还原回去先看一下是否存在 assets_custom 表。

上面提到的解决方案里就是用的数据库还原，在我后续尝试升级的过程中也多次备份还原过原库

**Comment by BaiJiangJie** [comment]
回滚到 v3.1.2 版本，看一下数据库表。

**Comment by 1-step** [comment]
> 回滚到 v3.1.2 版本，看一下数据库表。

现在已经回滚了，表是存在的，且每次升级报错提示的表都不一样。

**Comment by 1-step** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/25605874/7a74a3c3-c03b-4e21-be96-bdff32f641bb)

**Comment by 1-step** [comment]
> 那说明 v3.1.2 的表结构已经有问题了。 assets_custom 表是在 v3.2 版本新增加的。

查了一下这个表是空的

**Comment by BaiJiangJie** [comment]
查看一下 django_migrations 表结构的数据。

**Comment by 1-step** [comment]
> django_migrations

![image](https://github.com/jumpserver/jumpserver/assets/25605874/ad97d61c-af6f-4c97-8e9e-c058f4ef4e8e)

**Comment by 1-step** [comment]
> 那说明 v3.1.2 的表结构已经有问题了。 assets_custom 表是在 v3.2 版本新增加的。

我需要删除这个表之后再更新吗

**Comment by BaiJiangJie** [comment]
可以删除一下试试。

**Comment by BaiJiangJie** [comment]
因为判断不出来都执行了那些迁移文件，生成了那些数据表，所以不能确定一定会成功。

如果还是不行，得再回滚之前正常的数据库版本。

**Comment by 1-step** [comment]
> 因为判断不出来都执行了那些迁移文件，生成了那些数据表，所以不能确定一定会成功。
> 
> 如果还是不行，得再回滚之前正常的数据库版本。

我先尝试一下吧，感谢大佬

**Comment by 1-step** [comment]
我尝试了删除这个表之后升级，但是出现了读不到资产的问题

**Comment by weijingqi** [comment]
问题解决了吗
