### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by wptad** [jumpserver/jumpserver#117]
I am going to add Docker feature for JumpServer. With Docker, it should be very easy to deploy/upgrade Jumpserver and eliminate various dependance problems.

**Comment by xrain0610** [comment]
I like it, wait you~ , I think should use the alpine base images, I love docker~

**Comment by xrain0610** [comment]
by the way , if use the docker, I think you should support the sqlite db

**Comment by ibuler** [comment]
This is some one jumpserver user built docker image.
https://github.com/xrain0610/docker-jumpserver 

some one else can try it, and report it.  And we need @wptad a perfect image for jumpserver stable version.

Thanks xrain0610.
@xrain0610

**Comment by wptad** [comment]
Cool. 

Sorry, very busy recently. I will check and work on it this weekend.  

Thanks 

----------
Tad

**Comment by Kinganmi** [comment]
Pls, go on
