### ISSUE TITLE
[Bug] 数据库连接密码包含特殊字符，v3.7.0远程连接数据库失败

### ISSUE THREAD

**Issue by foreverrice** [jumpserver/jumpserver#11708]
![image](https://github.com/jumpserver/jumpserver/assets/33533816/badc49cd-66ce-45e9-ad17-14360b25d71d)
通过其他工具可以连接，连接阿里云数据库密码包含“#”，怀疑被转义或解析失败

**Comment by BaiJiangJie** [comment]
不带 `#` 号可以吗？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11722

关注这个。

**Comment by foreverrice** [comment]
> #11722
> 
> 关注这个。



> #11722
> 
> 关注这个。

👌
