### ISSUE TITLE
Jumpserver 1.0 网域网关显示错误

### ISSUE THREAD

**Issue by w55554** [jumpserver/jumpserver#1170]
##### 使用版本
Version 1.0.0-2 GPLv2

##### 问题复现步骤
1.  新版本在网域创建网关的时候， 协议和用户名显示颠倒，协议显示root，用户名显示ssh。

##### 图片展示

![图片展示](http://ow7h4ercl.bkt.clouddn.com/0180404135708.png)

**Comment by wojiushixiaobai** [comment]
无法复现，建议重新打开页面试试
![qq20180404-141441](https://user-images.githubusercontent.com/24326988/38291495-9611bc4e-3812-11e8-94f7-853a181d3658.jpg)

**Comment by w55554** [comment]
@wojiushixiaobai 感谢回复，另外提个小建议
Web 终端显示列表，能否做成树装列表，类似资产树。

例如我的情况，我这边的主节点，例如 中国 ，运维管理 这些节点下（不包含子节点）没有机器，就不用Web 终端显示.
![Web](http://ow7h4ercl.bkt.clouddn.com/JumpServer_QA-1.png)

**Comment by ibuler** [comment]
树形结构在做了，前端很麻烦
