### ISSUE TITLE
[Feature] 调起Xshell后可以直接点击xftp文件传输

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11714]
V3.7.0
通过客户端方式调起linux设备Xshell链接
<img width="785" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/b25fec75-6ae0-480c-9398-1c76513aabff">
此时大部分运维习惯是直接点击客户端上的文件传输按钮，但这种方式目前需要重新认证
<img width="903" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/fbf89e64-76b4-4f23-b515-330618c5889d">

**Comment by BaiJiangJie** [comment]
试一下，连接的时候，使用“向导”里面的 Token 信息能不能打开 文件传输的功能。

**Comment by pika-FENG** [comment]
向导里的token每次都变，和调用客户端的不一样

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bryan ***@***.***&gt;
发送时间: 2023年9月27日 15:14
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: Feng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [Feature] 调起Xshell后可以直接点击xftp文件传输 (Issue #11714)

**Comment by BaiJiangJie** [comment]
自动拉起的 token 只能使用一次，向导里的可以设置允许复用。

**Comment by pika-FENG** [comment]
> 自动拉起的 token 只能使用一次，向导里的可以设置允许复用。

3.7.1试了下向导里的也不能多次使用呀

**Comment by BaiJiangJie** [comment]
配置文件开启多次复用。
<img width="2516" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fd800575-af05-48c3-a176-9305179d8eb3">
https://docs.jumpserver.org/zh/v3/guide/env/#1-core
