### ISSUE TITLE
[Feature] jumpserver快捷键添加

### ISSUE THREAD

**Issue by yiqikeji17** [jumpserver/jumpserver#11724]
**请描述您的需求或者改进建议.**
1. 希望能增加VNC远程页面中，右边快捷键可自定义添加。

**Comment by BaiJiangJie** [comment]
能详细描述一下功能设想吗？比如一些实际的使用场景。

**Comment by yiqikeji17** [comment]
在Windows业务机上，经常会用到alt+tab切换窗口，希望能增加这个功能，谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Feature] jumpserver快捷键添加 (Issue #11724)





 
能详细描述一下功能设想吗？比如一些实际的使用场景。

**Comment by BaiJiangJie** [comment]
可以考虑加一个快捷键，但是不知道效果是什么样的。

录个使用的小视频看一下。

**Comment by yiqikeji17** [comment]
就是跟在自己本地电脑上按alt+tab切换窗口一样的，您自己在电脑上按下alt+tab键就知道了。其实只要能在远程机能接收到alt+tab键指令就行，请试试下，谢谢。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月28日(星期四) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Feature] jumpserver快捷键添加 (Issue #11724)





 
可以考虑加一个快捷键，但是不知道效果是什么样的。
 
录个使用的小视频看一下。
 
&mdash;

**Comment by BaiJiangJie** [comment]
好的，等上线了你可以体验一下。

**Comment by yiqikeji17** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月28日(星期四) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Feature] jumpserver快捷键添加 (Issue #11724)





 
好的，等上线了你可以体验一下。

**Comment by LeeEirc** [comment]
v3.8.0 已添加

**Comment by yiqikeji17** [comment]
收到，我测试看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 上午10:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Feature] jumpserver快捷键添加 (Issue #11724)





 
v3.8.0 已添加
