### ISSUE TITLE
[Bug]  账号模板应用后，名称不是模板里配置的名称

### ISSUE THREAD

**Issue by lls205** [jumpserver/jumpserver#11723]
**JumpServer 版本
v3.7.1

**浏览器版本**
Chrome 已是最新版本
版本 117.0.5938.92（正式版本） （64 位）

**Bug 描述**
账号模板应用后，名称不是模板里配置的名称，是跟用户名一样的名称；正常我希望显示为模板里配置的名称

**Bug 重现步骤(有截图更好)**
1. 创建账号模板
2. 账号列表，模板添加
3. 查看账号列表，名称和用户名都显示的是root

**Comment by lls205** [comment]
都显示为用户名，多个项目的多套密码，我都难以区分这个资源当前对应的哪个模板的root

**Comment by BaiJiangJie** [comment]
资产详情中账号列表，添加模版是会同步模版的名称的。

账号列表中添加模版，都会使用 username，有问题。 @feng626

**Comment by lelovelo** [comment]
借楼请问下，账号模版进行更新密码或密钥后，使用模版的账号 是不会同步更新的，这个是我设置的问题还是本身就是这么设定的

**Comment by BaiJiangJie** [comment]
如果使用账号模版生成的账号，没有单独更改过密码。

在账号模版详情中更新是可以同步修改的。

在更新账号模版页面更新密码不会同步修改。

**Comment by BaiJiangJie** [comment]
v3.8 已发布。
