### ISSUE TITLE
[Bug] v3.1.2 版本升级数据库表结构变更报错

### ISSUE THREAD

**Issue by 1-step** [jumpserver/jumpserver#11725]
链接之前的问题
https://github.com/jumpserver/jumpserver/issues/11690#issue-1911027043
**Bug 描述**
删除问题表之后，升级 v3.2.0 成功，但是无法读取资产内容导致资产无法登陆

**Comment by BaiJiangJie** [comment]
那就不好处理了，数据库表结构有点乱。

**Comment by BaiJiangJie** [comment]
资产不多的话，新部署一台重新录入一下资产用户吧

**Comment by 1-step** [comment]
解决了，还原了一次数据库到之前的版本，然后重新删除了冲突的表，就好了

**Comment by BaiJiangJie** [comment]
Nice.
