### ISSUE TITLE
[Feature] 资产批量更新平台字段，根据平台约束协议自动生效

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11726]
**请描述您的需求或者改进建议.**
需求场景：有一批 windows 新安装了 openssh 需要批量添加 ssh 协议

期望解决方案：
1、新建平台 windows_ssh ，将 ssh 协议设置为 主要的、默认的、必要的、开放的
2、批量勾选资产，批量更新，将平台更换为 windows_ssh

目前：需要每一台资产进入提交后，资产才会新增 ssh 协议
期望：自动给匹配了 windows_ssh 平台的资产新增 ssh 协议

**Comment by BaiJiangJie** [comment]
嗯，可以考虑。

主要有两种情况：
1. 单独更新平台的时候，所有关联的资产是否同步更新。
2. 更新资产的平台时，资产对应的字段是否更新为平台的值。（包括单独、批量更新）

目前设想的实现方案：
1. 在平台详情的协议 Card 中，增加一个按钮，【应用到资产】（会将当前平台的协议同步更新到所有的资产，只增加不删除）
2. 资产、平台之间的关系有变化的时候，同步更新（也是只增加不删除）。

注：目前资产、平台变化，只考虑`协议`字段的变化，其他字段暂时不考虑同步。

**Comment by hzhfit2cloud** [comment]
👍🏻👍🏻👍🏻
