### ISSUE TITLE
[Feature] 密码不支持特殊字符"

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#11722]
**请描述您的需求或者改进建议.**
当前JumpServer添加密码的时候不支持特殊字符，如"     ，看看能不能处理一下，如后台自动识别加\

**Comment by BaiJiangJie** [comment]
有点难度，后面版本计划支持一下。

**Comment by jym503558564** [comment]
3.9.1已支持“和‘ 这样的特殊字符

**Comment by SnowsonZ** [comment]
> 3.9.1已支持“和‘ 这样的特殊字符

麻烦问下，目前还有哪些特殊字符是不支持的。有没有对应的文档？

**Comment by SnowsonZ** [comment]
> > 3.9.1已支持“和‘ 这样的特殊字符
> 
> 麻烦问下，目前还有哪些特殊字符是不支持的。有没有对应的文档？

@jym503558564  @BaiJiangJie

**Comment by BaiJiangJie** [comment]
目前只有 `{{` `}}` `{%` `%}` 不支持，其他都支持。

**Comment by SnowsonZ** [comment]
> 目前只有 `{{` `}}` `{%` `%}` 不支持，其他都支持。

好的。2.x的版本都是那些特殊字符不支持？能不能麻烦也给个列表。翻文档没看到。
