### ISSUE TITLE
[Question] vscode通过jumpserver直连服务器

### ISSUE THREAD

**Issue by kailiangshang4paradigm** [jumpserver/jumpserver#11727]
**请描述您的问题.**
注意到发布信息里面的vscode直连仅支持系统的默认用户，如果是root权限新开通的用户，且在/etc/group中已经有的用户不支持直连么。
如果是这样的话，就导致每次用vscode打开，首先要切换到用户下，然后再输入密码，但是由于刚开始登陆时的用户权限时平级的，这就导致在打开文件夹时总是不能默认打开，然后被拒绝。只能在终端重新切换到用户的目录下再操作。

**Comment by BaiJiangJie** [comment]
可以的啊，你试一下。

**Comment by kailiangshang4paradigm** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/146298235/93808481-3211-4551-b54e-90e8b8c69686)

**Comment by kailiangshang4paradigm** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/146298235/a97de0a7-c8e4-442e-8ec1-ca30ca55d7fa)
这里显示没有该用户，问了一下其他人，说是如果要这样做，就需要新的端口。
