### ISSUE TITLE
[Feature] Chen 组件请求外网 css 文件

### ISSUE THREAD

**Issue by JonnnLOL** [jumpserver/jumpserver#11729]
**请描述您的需求或者改进建议.**
内网 JumpServer，使用 Chen 组件连接 MariaDB 时，发现向外网请求了这个 css 文件，导致界面响应速度会很慢。
![image](https://github.com/jumpserver/jumpserver/assets/95204418/b88cb519-71fa-4e0a-892d-51d1f62e4e31)

**Comment by BaiJiangJie** [comment]
v3.7.1 优化了，升级试试。

**Comment by JonnnLOL** [comment]
确实是 v3.7.1 版本
![image](https://github.com/jumpserver/jumpserver/assets/95204418/d33a6cac-ad0f-4f32-a2ec-18758a2695db)

**Comment by jym503558564** [comment]
@Aaron3S 存在该问题，chen组件代理连接数据库，请求外网css。

**Comment by BaiJiangJie** [comment]
新版本已解决。
