### ISSUE TITLE
[Bug] 3.7.1版本，mysql连接测试全是失败

### ISSUE THREAD

**Issue by pingliu** [jumpserver/jumpserver#11739]
**JumpServer 版本**
3.7.1

**浏览器版本**
chrome 

**Bug 描述**
mysql连接测试全是失败，但是通过web终端是可以登录的。

<img width="1274" alt="271242031-c4f7a780-1e51-41f8-a3c1-34748910d9b5" src="https://github.com/jumpserver/jumpserver/assets/6415493/d49ebc26-5d1f-42fe-a4a1-85591c2ceae8">
<img width="1795" alt="271242070-8ca20287-7e59-4af8-a180-65f5518cb4db" src="https://github.com/jumpserver/jumpserver/assets/6415493/f30a31f0-6eb0-42f8-9292-35af7c8704ee">
<img width="783" alt="271242087-1940cd56-044b-442b-acb6-3cb73bab08db" src="https://github.com/jumpserver/jumpserver/assets/6415493/498e7e63-3b94-4613-baa1-035645ee5adc">

**Comment by BaiJiangJie** [comment]
@jym503558564 测试环境是否能复现？

**Comment by jym503558564** [comment]
v3.7.1测试数据库可连接性成功，无法复现。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/47514c74-fdf1-4320-b9bd-0fb629476ed6)

**Comment by pingliu** [comment]
我用3.6.4的话，没有这个问题，但是因为漏洞要升级到3.7.1

**Comment by BaiJiangJie** [comment]
复现的时候用的也是 v3.7.1 的版本。

**Comment by pingliu** [comment]
我刚刚按照文档：https://docs.jumpserver.org/zh/v3/installation/setup_kubernetes/helm_online_install/#22-jumpserver-valuesyaml，重新部署了jumpserver，发现还是同样的问题

**Comment by BaiJiangJie** [comment]
有没有可能是数据库类型的问题。

**Comment by pingliu** [comment]
不是数据库类型的问题，我刚刚安装了两个版本，一个是3.6.4，一个是3.7.1，前者没有这个问题，后者有这个问题，主要是测试链接会报错，但是不影响使用，

**Comment by BaiJiangJie** [comment]
@feng626 约一下时间远程调试一下。

**Comment by feng626** [comment]
看看mysql是否开启了ssl认证

**Comment by pingliu** [comment]
没有开通

**Comment by feng626** [comment]
3.7 加了mysql的ssl测试可连接性，在jumpserver的系统上 mysql没有开启ssl？

**Comment by pingliu** [comment]
没有开启ssl认证，而且我前面说了，3.6.4和3.7.1表现不一致

**Comment by BaiJiangJie** [comment]
那就奇怪了，v3.7.2 呢？

**Comment by XingTom** [comment]
遇到同样问题，请问怎么解决的呢

**Comment by pingliu** [comment]
没解决，一直使用3.5.5版本，不敢升级

**Comment by jym503558564** [comment]
阿里云rds for mysql ?
