### ISSUE TITLE
[Bug] Inconsistencies in September 27 security advisories

### ISSUE THREAD

**Issue by cfi-gb** [jumpserver/jumpserver#11735]
Hello,

i would like to report a few inconsistencies in the security advisories published last week which are:

https://github.com/jumpserver/jumpserver/security/advisories/GHSA-7prv-g565-82qp

The following `Patched versions` at the top:

```
Affected versions v2.24 - v3.6.4
Patched versions >= v2.28.19, >= v3.6.5
```

doesn't match the `safe versions` mentioned later:

```
Upgrade to safe versions:

v2 version: >= v2.28.20
v3 version: >= v3.7.1
```

https://github.com/jumpserver/jumpserver/security/advisories/GHSA-ghg2-2whp-6m33

The `Affected versions` mentions that only 3.x is affected and that `3.6.5` is the fixed version:

```
Affected versions v3.0.0 - v3.6.4
Patched versions >= v3.6.5
```

but at the same time later it is mentioned that `2.28.20` also contains a fixed version (but 2.x seems to be not affected) and also mentions that `3.7.1` includes the fix (vs. `3.6.5` mentioned previously):

```
Update to safe versions:
v2 version: >= v2.28.20
v3 version: >= v3.7.1
```

https://github.com/jumpserver/jumpserver/security/advisories/GHSA-jv3c-27cv-w8jv

This says that version smaller then `3.6.4` are affected while at the same time mentions that version `3.6.5` contains the fix:

```
Affected versions < 3.6.4
Patched versions 3.6.5 3.5.6
```

```
Safe versions: v3.6.5，v3.5.6
```

**Comment by BaiJiangJie** [comment]
Yes, the above is each bug and the corresponding affected version and fixed version.

If you want to fix the vulnerability, it is better to upgrade to the latest version of v2 (v2.28.20) or v3 (v3.7.1).

**Comment by cfi-gb** [comment]
Thanks a lot for your response. Currently my point is that the advisories are not fully clear on the affected and/or fixed versions as shown previously. For example:

```
Affected versions < 3.6.4
Patched versions 3.6.5 3.5.6
```

I guess the `Affected versions` should be `Affected versions <= 3.5.5, 3.6.x <= 3.6.4` or similar instead.

**Comment by BaiJiangJie** [comment]
Yes, your description is more accurate.
Mainly focus on fixed versions.

**Comment by BaiJiangJie** [comment]
There is indeed a problem, and the above three bug fix versions have been updated.

**Comment by cfi-gb** [comment]
LGTM now, thanks a lot for taking care :+1:
