### ISSUE TITLE
[Question] Can send/forward logs of Jumpserver to SIEM ?

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11736]
Hello,

Now, I need know way to can send/forward logs of Jumpserver such as: user login, logout, create assets, create users, users remote to server,... to SIEM system - Wazuh.

Please, help me.

**Comment by ibuler** [comment]
I am not familiar with SIEM，but jumpserver support forward log to rsyslog，may be help to you

**Comment by tsukiazuma** [comment]
> I am not familiar with SIEM，but jumpserver support forward log to rsyslog，may be help to you

Oh, can you give me some documents about the requirement or configuration to forward log, rsyslog,...

Thank you

**Comment by BaiJiangJie** [comment]
<img width="2558" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/c194aca3-a8f9-4091-960b-fc22a6764aec">

https://docs.jumpserver.org/zh/v3/guide/env/#1-core

https://github.com/jumpserver/jumpserver/blob/dev/apps/jumpserver/settings/logging.py#L141

You can take a look at the documentation and code above.

**Comment by tsukiazuma** [comment]
Oh thank you, I will check and try forward log to SIEM, then I response then

**Comment by BaiJiangJie** [comment]
Okay！

**Comment by tsukiazuma** [comment]
Hello,

I want config logs to qradar such as: user login, user remote to server, type remote.
Now I can see logs about login of user at `/opt/jumpserver/core/logs/jumpserver.log`. How about logs of remote to server and type remote?

Thank
