### ISSUE TITLE
[Bug] 点击资产树连接，选择协议时界面空白

### ISSUE THREAD

**Issue by dsf1995cn** [jumpserver/jumpserver#11733]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.3

**浏览器版本**
Edge 117.0.2045.43

**Bug 描述**
点击资产树连接，选择协议时界面空白。

[附图](https://img1.imgtp.com/2023/09/28/7ueDI4yi.png)

**Bug 重现步骤(有截图更好)**
1.选择某协议，在终端连接一次。
2.资产管理删除上述协议。
3.到终端重新连接资产即可触发。

**Comment by BaiJiangJie** [comment]
升级最新版本试一下，修复过一次。

**Comment by dsf1995cn** [comment]
已修复。
升级到v3.7.1，此问题已不存在。
当前版本逻辑为：点击连接前做了判断，如上次连接使用协议已被删除，则聚焦到当前资产存在的第一个协议。
