### ISSUE TITLE
[Bug] WEB GUI 方式连接数据库时高危命令复核异常

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#11746]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**

**Bug 描述**
WEB GUI 连接数据库，命令复核完成后抛异常，且不能执行成功。v3.6 则正常。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/40846859/d6893d73-74a4-4b05-b788-b0e04622ca45)

**Comment by BaiJiangJie** [comment]
@xulinde 测试环境能否复现？

**Comment by xulinde** [comment]
感谢反馈，已复现该问题，后续版本修复～

**Comment by jym503558564** [comment]
v3.8.0已修复，请升级后进行测试。
