### ISSUE TITLE
[Feature] Jumpserverclient安装到programfiles目录

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11745]
目前是安装到C:\用户目录下，是否可以指定安装位置到program目录呢，这样公共机上的多个用户都可以使用

**Comment by BaiJiangJie** [comment]
@Halo1236 是否能优化一下？

安装的时候用户可以安装到当前用户和系统目录中，拉起的时候两个目录都获取一下。

**Comment by Halo1236** [comment]
v3.8支持
