### ISSUE TITLE
[Bug] 文档中缺少wget

### ISSUE THREAD

**Issue by xaswq** [jumpserver/jumpserver#11749]
![image](https://github.com/jumpserver/jumpserver/assets/85377380/87921a20-9a13-435c-9299-d96bda36b814)

快速入门里面 

https://docs.jumpserver.org/zh/v3/quick_start/

其他地区
https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash

改成 

wget https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash

可能更合适？

**Comment by BaiJiangJie** [comment]
好的，感谢指出问题。

**Comment by BaiJiangJie** [comment]
已添加。
