### ISSUE TITLE
[Bug] 资产列表的选项卡切换需要1-4秒左右才能切换成功

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11752]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
版本 117.0.5938.150（正式版本） （64 位）

**Bug 描述**
资产列表的选项卡切换需要1-4秒左右才能切换成功，这里估计有性能问题。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/f6d9fe9f-efce-4f90-a662-0667053454f7)

**Comment by BaiJiangJie** [comment]
看看浏览器控制台，定位一下是哪个 API 比较慢？

**Comment by nondevops** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/12181410/e90214c2-21fe-4612-8cfe-fad5f374ce7d)
从控制台看，响应倒是很快，但是切换到另外一个标签页的确要等很久，你可以在你们的demo环境或者开发环境重现下这个现象。

**Comment by BaiJiangJie** [comment]
你可以在 demo 试一下，正常的。

**Comment by BaiJiangJie** [comment]
![Oct-09-2023 15-01-13](https://github.com/jumpserver/jumpserver/assets/32935519/d7365ba3-2466-437f-8311-678623abe7be)

**Comment by BaiJiangJie** [comment]
![Oct-09-2023 15-03-51](https://github.com/jumpserver/jumpserver/assets/32935519/26f46166-8867-4dc4-8361-2c9a7bf73ab7)
