### ISSUE TITLE
[Bug] 创建资产-云平台无法返回

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11753]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
版本 117.0.5938.150（正式版本） （64 位）

**Bug 描述**
创建资产-云平台无法返回，看样子无法返回是一个通病，建议通盘遍历一次。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/167d9738-d464-45fc-9422-dbcab504a133)

**Comment by BaiJiangJie** [comment]
因为创建资产是新打开的浏览器 Tab 页面，所以不能返回。

其他资源创建的时候可以返回。
