### ISSUE TITLE
[Bug] 资产推送失败

### ISSUE THREAD

**Issue by GabeCloy** [jumpserver/jumpserver#11756]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
Google Chrome 版本 117.0.5938.132 (正式版本) (arm64)

**Bug 描述**
使用管理员给普通用户“账号推送”到时候，提示“[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'”

**Bug 重现步骤(有截图更好)**
1.超级管理员帐号登录，帐号管理 -> 账号推送 -> 选择帐号点击"更多">执行

<img width="904" alt="image" src="https://github.com/jumpserver/jumpserver/assets/19618375/c4636d3a-3d5e-4817-bb5e-cf1ca702591c">

**Comment by BaiJiangJie** [comment]
账号关联的资产 IP 是多少？

**Comment by GabeCloy** [comment]
你好，已经找到问题了，资产名称不能携带“/”这个符号，否则会导致全部资产无法推送

**Comment by BaiJiangJie** [comment]
好的，在创建资产的时候先做个限制。

**Comment by demirozmustafa** [comment]
any feedback problem not resolved
