### ISSUE TITLE
咨询一个系统用户登录超时退出的问题

### ISSUE THREAD

**Issue by uepuer** [jumpserver/jumpserver#11750]
在以前的旧版本里面，可以配置系统用户登录之后空闲时间30分钟之后，系统用户自动退出。我们在昨天测试环境上面安装到v3.7.1 之后，找不到这一项配置，只有管理会话超时，请问在哪个页面配置？

**Comment by BaiJiangJie** [comment]
<img width="1512" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/01e1efe9-4e4c-49e9-8688-dc060f24d108">

**Comment by BaiJiangJie** [comment]
在会话安全里。

**Comment by uepuer** [comment]
请问这一项不是web 连接客户端的空闲时间吗？同时如果是这一项配置管理系统用户登录超时自动退出的吗？那么这一个地方就有bug ，并没有生效。劳烦你们测试 一下。感谢！
