### ISSUE TITLE
[Bug] GPT页面无法返回

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11751]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
版本 117.0.5938.150（正式版本） （64 位）

**Bug 描述**
GPT页面无法返回

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/430e1715-77bc-4d3d-9fd0-21cbceb282d0)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11753

情况一样。
