### ISSUE TITLE
[Bug] 升级到V2.28.20后，sz无法下载png jpg等图片文件

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#11757]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v2.28 

**浏览器版本**
Chrome以及Firefox

**Bug 描述**
从v2.12升级到v2.28.20版本后，使用WebCli登录，用sz下载png jpg等图片文件下载不了，下载完直接卡住。

**Bug 重现步骤(有截图更好)**

![搜狗截图20231008154004](https://github.com/jumpserver/jumpserver/assets/11976391/9a660be2-c379-49f5-93c9-c66c9c8deb87)

**Comment by BaiJiangJie** [comment]
下载其他格式的文件有问题吗？

**Comment by ztskycn** [comment]
> 下载其他格式的文件有问题吗？

不好意思，忘记说了。其它格式目前没有发现问题，只有图片有问题。目前测试png和jpg都有问题，原来2.12版本是正常的。

**Comment by BaiJiangJie** [comment]
好的。

看看能否复现？@xulinde

**Comment by ztskycn** [comment]
> 好的。
> 
> 看看能否复现？@xulinde

每次都有复现

**Comment by BaiJiangJie** [comment]
看看 koko 组件日志里有报错吗？

**Comment by xulinde** [comment]
感谢反馈，已复现该问题，后续版本修复～

**Comment by ztskycn** [comment]
![搜狗截图20231008162945](https://github.com/jumpserver/jumpserver/assets/11976391/e3baea8d-0b71-4e16-8094-fc87c1fc1b1d)

2023/10/08 16:29:07 Screen不支持解析l
2023/10/08 16:29:07 Screen 未解析 ESC `'>'` 3eParameters字符
2023/10/08 16:29:07 Screen不支持解析l
2023/10/08 16:29:07 Screen不支持解析h
2023/10/08 16:29:07 Screen不支持解析l

另外，我上面还有WS连接的报错。
Ws[124ce309-3e63-4132-98be-39eb3321816c] send TERMINAL_BINARY message err: write tcp 192.168.250.6:5000->192.168.250.5:50388: write: connection reset by peer

**Comment by BaiJiangJie** [comment]
最新版本没问题，建议升级到 v3 最新版本解决。

v2.28 后期看情况修复。
