### ISSUE TITLE
[Question] 当前这个IP归属地就属于重庆，为什么还是要报异地登录呢。

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11755]
**请描述您的问题.**
当前这个IP归属地就属于重庆，为什么还是要报异地登录呢。
<img width="203" alt="企业微信截图_16967357626807" src="https://github.com/jumpserver/jumpserver/assets/12181410/3bd1f3eb-7fd7-4a21-9ae8-92a109a0cc91">
![image](https://github.com/jumpserver/jumpserver/assets/12181410/ea8ca04b-b03a-4d68-bdce-6d225d73530d)

我每天都在重庆的，不知道这个异地登录的逻辑是怎么判断出来的

**Comment by BaiJiangJie** [comment]
看一下你的账号在登录日志中，最后两次成功的记录中城市是否一样？

**Comment by nondevops** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/12181410/626f0fa2-6e15-4155-91f1-d05c3df1114f)

**Comment by BaiJiangJie** [comment]
这就是问题所在，一个是重庆市，一个是重庆。识别的 IP 地址城市不完全一样。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/11769/files

v3.8 版本优化。
