### ISSUE TITLE
[Feature] 优化远程应用代填过程

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11762]
**请描述您的需求或者改进建议.**
版本3.7.0企业版
远程应用--客户端方式，使用图形工具访问数据库，代填过程很慢。下面是我整理的大概所需的时间；
工具                  数据库类型        所需时间
navicat16           MongoDB       29秒
mongocompass  MongoDB        11秒
navicat16           Mysql              31秒
dbeaver          Mysql              21秒

其它不测了，代填过程太慢了，用户无法接收。希望尽快优化，谢谢！

**Comment by BaiJiangJie** [comment]
Debug 一下慢在什么地方。

有几个过程：连接、拉起、代填。
