### ISSUE TITLE
[Question] 管理华三服务器的WEB界面无法代填

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11764]
**请描述您的问题.**
通过jumpserver管理华三服务器的web界面无法代填

用户名输入框
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d3b13c86-6e96-444d-bf3b-76cf98c99d5e)
密码输入框
![image](https://github.com/jumpserver/jumpserver/assets/44529247/8c336a4e-c848-4320-96b9-ecafa00a319a)
登录框，复制的完整的xpath
/html/body/div/div[1]/div[2]/form/div[2]/button

资产代填参数
![image](https://github.com/jumpserver/jumpserver/assets/44529247/8ee2359c-617c-4a2d-9e14-b1e563d2466f)

**Comment by BaiJiangJie** [comment]
用的什么版本，tinker 服务报什么错？

**Comment by ryswork1993** [comment]
> 用的什么版本，tinker 服务报什么错？

版本：3.7.1，其他服务器的web管理都正常，只有华三的代填失败，账号密码没有输入，是空的
![image](https://github.com/jumpserver/jumpserver/assets/44529247/205f92be-8d9c-4fca-9af4-c8ba2f7adc60)

**Comment by BaiJiangJie** [comment]
登录发布机看看 tinker 的日志。

**Comment by ryswork1993** [comment]
|
|


|
|


|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月9日 14:58 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Question] 管理华三服务器的WEB界面无法代填 (Issue #11764) |

登录发布机看看 tinker 的日志。

**Comment by BaiJiangJie** [comment]
代填页面上没有报错吗？

**Comment by BaiJiangJie** [comment]
你回复的信息里没有日志和截图信息。

**Comment by ryswork1993** [comment]
> 你回复的信息里没有日志和截图信息。
tinker日志
![image](https://github.com/jumpserver/jumpserver/assets/44529247/1c136adf-be7c-4ac0-abdf-1cbf880b4543)
连接之后账号密码的框里没有任何内容，过几秒之后会出现这个
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d391acd7-df46-4e6e-8c62-dbc6262e704c)
关掉上面那个提示之后又出现下面这个
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d0da3d9e-14f0-4a2d-8352-d9b711fe28b7)

**Comment by LeeEirc** [comment]
这里需要注意看下登陆页面是否是 iframe 嵌入的，另外是否页面渲染太慢，需要设置等待时间？

**Comment by ryswork1993** [comment]
我晚点先设置一下代填等待时间测试一下，另外怎么查看是否是iframe

**Comment by ryswork1993** [comment]
> 这里需要注意看下登陆页面是否是 iframe 嵌入的，另外是否页面渲染太慢，需要设置等待时间？

怎么设置等待时间，另外怎么查看是否是iframe

**Comment by LeeEirc** [comment]
已处理，多层 iframe 需要通过脚本的命令 select_frame 处理。
