### ISSUE TITLE
[Question] LDAP测试链接和测试登录都成功，但是每次用户导入都提示“同步正在运行中，请稍等”

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#11768]
**请描述您的问题.**
LDAP测试链接和测试登录都成功，但是每次用户导入都提示“同步正在运行中，请稍等”

![img_v2_48d38d0e-8869-4355-912c-8378f426e4bg](https://github.com/jumpserver/jumpserver/assets/85990572/a899b4b7-ed17-4a99-8950-f97ee4f79fee)

版本v3.6.4

**Comment by BaiJiangJie** [comment]
表示后端有任务正在执行。

**Comment by xiaoxiongxyy** [comment]
昨天开始就在执行 今天看还是这样 请问如何看这个后端任务的进度或进程呢

**Comment by BaiJiangJie** [comment]
清除一下 redis 再执行任务。

**Comment by BaiJiangJie** [comment]
v3.8 版本优化一下，任务状态的设置，现在逻辑上有点问题。
