### ISSUE TITLE
[Bug] 用户信息手机号设置+7，保存后查看用户信息自动加了+86

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#11773]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.1

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
用户信息手机号设置+7，保存后查看自动加了+86

**Bug 重现步骤(有截图更好)**
1.编辑用户手机号，把默认+86区号改成+7，点击保存
![1696839777732](https://github.com/jumpserver/jumpserver/assets/35896106/9d3d6083-9ac9-463b-83b9-9bfd8f7f0530)
2.查看用户详情发现默认加了+86
![1696839815839](https://github.com/jumpserver/jumpserver/assets/35896106/ef19c95e-374a-4e77-96dc-cd5f053e098e)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/11802/files

已修复，v3.8 版本上线。
