### ISSUE TITLE
[Question] installer方式v2.7.1升级v3.7.1

### ISSUE THREAD

**Issue by dsxkza** [jumpserver/jumpserver#11779]
**请描述您的问题.**
请问一下，我需要从v2.7.1版本升级到v3.7.1版本，在这中间我需要经历哪几个版本呢

**Comment by wojiushixiaobai** [comment]
备份数据库，参考 v3.7.1 环境要求，然后直接升级即可。

升级有问题再提交具体的问题及相关错误日志
