### ISSUE TITLE
[Question] Debian 12 认证失败

### ISSUE THREAD

**Issue by BOBOKaa** [jumpserver/jumpserver#11777]
jumpserver跳到debian 12的目标机器上提示
error: 认证失败（用户名或密码错误）

需要把ssh的密码登录改成enable才能登录
PasswordAuthentication yes
请教下如何再不用更改ssh的密码登录情况下能够成功跳转

**Comment by BOBOKaa** [comment]
<img width="917" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30493490/1cc5506c-6473-4b52-bafa-c84325d853a4">

**Comment by BaiJiangJie** [comment]
不然你就使用 密钥的方式登录。

**Comment by BOBOKaa** [comment]
> 不然你就使用密钥的方式登录。

目前就是密钥登录的，登录会报认证失败，用户名密码错误

**Comment by BaiJiangJie** [comment]
密钥登录 debian 12 失败的时候，看看 koko.log 日志。
