### ISSUE TITLE
[Bug] Centos 7单机部署组件无法启动

### ISSUE THREAD

**Issue by DaddyXz** [jumpserver/jumpserver#11770]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**
不涉及

**Bug 描述**
使用centos7单机部署，jumpserver 组件仅有core容器启动成功，其他组件无法启动

**Bug 重现步骤(有截图更好)**
1. 使用3.10.514版本内核，启动jumpserver，core启动成功，其他组件提示unhealthy，无法启动
2. 升级内核到3.10.1160. 启动jumpserver成功
3. docker版本20.10.17，查询docker文档，对内核要求为3.10版本，说明docker是支持3.10.514版本内核的

**Comment by BaiJiangJie** [comment]
那就使用最新的内核版本吧。

**Comment by BaiJiangJie** [comment]
只要 docker 兼容，JumpServer 应该都是兼容的。
