### ISSUE TITLE
[Question] 2.23.4版本升级2.24.0版本报错Failed to change the table structure!

### ISSUE THREAD

**Issue by linchenWSX** [jumpserver/jumpserver#11778]
**请描述您的问题.**
django.db.utils.OperationalError: (1005, 'Can\'t create table `jumpserver`.`tickets_applyloginticket` (errno: 150 "Foreign key constraint is incorrectly formed")')
[ERROR] Failed to change the table structure!
![image](https://github.com/jumpserver/jumpserver/assets/147408169/34d4980d-a22c-4480-abe4-f57789e3a463)

**Comment by linchenWSX** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/147408169/335824d8-2d78-44c3-bae2-b06c4b0417d8)
补充一下，我的是单节点，使用jmsctl.sh upgrade进行升级，数据库使用的是外部MariaDB-10.3.34

**Comment by BaiJiangJie** [comment]
升级前，数据库重新恢复过吗？是不是字符编码不对？

**Comment by linchenWSX** [comment]
> 升级前，数据库重新恢复过吗？是不是字符编码不对？

嗯，数据库多次重新创建，但依旧不行，使用这条命令创建的数据库
create database jumpserver default charset 'utf8';

**Comment by BaiJiangJie** [comment]
看看你备份的 sql 文件里 charset 是不是 utf8?

比如：我的是 utf8mb3。

**Comment by linchenWSX** [comment]
> 看看你备份的 sql 文件里 charset 是不是 utf8?
> 
> 比如：我的是 utf8mb3。

![image](https://github.com/jumpserver/jumpserver/assets/147408169/3614c926-f25d-4d47-aba0-a4b894261210)
我的是utf8mb4

**Comment by BaiJiangJie** [comment]
create database jumpserver default charset 'utf8mb4' collate utf8mb4_bin;

这样创建数据库。

**Comment by linchenWSX** [comment]
> create database jumpserver default charset 'utf8mb4' collate utf8mb4_bin;
> 
> 这样创建数据库。

解决了，十分感谢
