### ISSUE TITLE
控制台执行命令卡住了[Bug] 

### ISSUE THREAD

**Issue by dotanero9** [jumpserver/jumpserver#11781]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.1

**浏览器版本**
Chrome 已是最新版本
版本 117.0.5938.150（正式版本）

**Bug 描述**
任何同一时间针对2台不同的Linux服务器执行命令，其中A会卡住，B不会，且A和B直接在堡垒机后台服务器上直接连接A和B是都可以连接并执行命令的。
应该和后台服务器负载情况及组件状态应该都无关。

**Bug 重现步骤(有截图更好)**
A服务器：
![image](https://github.com/jumpserver/jumpserver/assets/88821514/62b61f2b-e170-4200-982f-98c3f2833334)
![image](https://github.com/jumpserver/jumpserver/assets/88821514/0fd3124e-bf76-4118-8c6a-97e01b838bb7)

B服务器：
![image](https://github.com/jumpserver/jumpserver/assets/88821514/12cc0712-2814-461e-a18f-24f89fe715ef)
![image](https://github.com/jumpserver/jumpserver/assets/88821514/1a0ae90a-806c-47af-8e5a-6545f12c6e66)

**Comment by BaiJiangJie** [comment]
你是怎么测试的？多人同时操作？

**Comment by BaiJiangJie** [comment]
测试了一下没有复习啊

**Comment by dotanero9** [comment]
只有这2台服务器，一旦输入ip add就卡住不动了，其它无问题，输其它命令又不会有问题
![微信截图_20231010141601](https://github.com/jumpserver/jumpserver/assets/88821514/ac95692c-eeb5-4947-a819-5305cc5a9c26)
![微信截图_20231010141624](https://github.com/jumpserver/jumpserver/assets/88821514/cba32f7b-bfe0-47b6-a230-2757c8c60eef)

**Comment by BaiJiangJie** [comment]
那应该不是产品的问题。看看 koko 服务日志有报错吗？

**Comment by dotanero9** [comment]
koko服务日志在哪里看？
另外我从1panel重新安装了jumpserver3.4.3去连接输入ip add卡主的那台服务器，依然是卡住的状态。但是输入其它命令则不会卡住

**Comment by BaiJiangJie** [comment]
安装最新版本的 JumpServer，可能之前有 bug。

或者重新使用离线包的方式部署一下。
