### ISSUE TITLE
[Question] 堡垒机升级3.7后，原有的api使用报错 {"detail":"用户未激活或者已删除。","code":"authentication_failed"}

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11783]
**请描述您的问题.**
执行如下命令获取token 发现token与原来没有变化，但是调用api报错 {"detail":"用户未激活或者已删除。","code":"authentication_failed"}
docker exec -it jms_core /bin/bash
cd /opt/jumpserver/apps
python manage.py shell
from users.models import User
u = User.objects.get(username='admin')
u.create_private_token()
麻烦帮忙看下

**Comment by BaiJiangJie** [comment]
我试了一下没问题啊。

**Comment by Sanbobo1** [comment]
找到原因了 admin账户被删除了 感谢回答

**Comment by BaiJiangJie** [comment]
应该是被禁用了。周期检测不活跃用户的时候，没有考虑到使用 token 的情况，v3.8 会优化一下。
