### ISSUE TITLE
[Feature] 审计台文件传输的这个留存文件可以加个审计吗

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#11791]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/66759501/682e7c6f-cc4c-4379-88db-b4f47eda5f94)
当前这个文件传输源文件记录任何人都可以直接下载，不太安全，看能不能加入工单系统，用户去下载源文件的时候加个审计

**Comment by BaiJiangJie** [comment]
不是所有人都能下载，只有审计员可以下载。

**Comment by jstbw** [comment]
知道可以设置角色，但是现在需要审计员，或者有查看权限的，下载文件也需要审批
