### ISSUE TITLE
[Question]  使用 jumpserver 是否意味着 ssh tun, scp, ansible 等工具都无法使用了？

### ISSUE THREAD

**Issue by cupen** [jumpserver/jumpserver#11798]
ssh 到堡垒机后，貌似是进入了一个特制的 shell ，与目标机器的通信都是基于这个 shell, 无法与现存的 ssh 协议兼容。这意味着现存的所有基于 ssh 协议的工具全都失效。 ssh tun,  scp,  ansible 之类都用不了，爽了运维但苦了开发啊。

![image](https://github.com/jumpserver/jumpserver/assets/1221615/f7eab025-ebd4-460f-9062-2e34caa4b2d4)

**Comment by BaiJiangJie** [comment]
这是一个命令行的入口方式，你可以使用 Web CLI 访问，或者拉起本地工具连接资产。

**Comment by cupen** [comment]
> 这是一个命令行的入口方式，你可以使用 Web CLI 访问，或者拉起本地工具连接资产。

是的，我问的就是命令行入口…… 似乎一切基于命令行的工具全都失效了。不知道您说的 “本地工具“具体是指哪些？

**Comment by stuacct073** [comment]
同样的问题。ssh 到堡垒机后，是否可以在堡垒机上配置端口转发，从而实现scp，rsync等命令呢？

**Comment by cupen** [comment]
这算哪门子兼容 ssh?   ssh tunnel,  scp 全都用不了了……
