### ISSUE TITLE
[Bug] 命令过滤识别错误

### ISSUE THREAD

**Issue by reviewcoder** [jumpserver/jumpserver#11793]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.4.2

**浏览器版本**
Google Chrome Version 117.0.5938.150

**Bug 描述**
命令过滤把mv命令识别为rm命令，导致无法执行

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/107672906/5edd20b7-4cb0-4083-a951-3dc882063964)

2.
3.

**Comment by BaiJiangJie** [comment]
目前的机制确实会有误判的问题。

建议使用正则表达式的方式配置过滤规则。rm 后加上空格。
