### ISSUE TITLE
[Feature] web资产代填脚本的中的账户信息明文问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#11799]
**请描述您的需求或者改进建议.**
现在的3.7.0版本，web资产代填脚本中的账户信息是明文，能不能做成zabbix那种方式，先设置一个变量和值的对应关系，值是隐藏状态，然后脚本中使用变量
1、设置变量和值的对应关系，可以选择值隐藏
![image](https://github.com/jumpserver/jumpserver/assets/44529247/859db637-6714-4767-a873-3fc65fa75056)
2、添加资产的时候，使用变量
![image](https://github.com/jumpserver/jumpserver/assets/44529247/f2bcd11e-a433-423b-85a2-6af5a9e4611a)

**Comment by BaiJiangJie** [comment]
详细说一下什么地方明文了。我们都是通过程序拉起代填的啊。

**Comment by ryswork1993** [comment]
> 详细说一下什么地方明文了。我们都是通过程序拉起代填的啊。

通过脚本代填的时候，脚本里边的value值不需要写吗
![image](https://github.com/jumpserver/jumpserver/assets/44529247/37feae13-b55e-4e94-b43b-0b7b144562b0)

**Comment by BaiJiangJie** [comment]
可以使用变量啊。

{USERNAME}
{SECRET}

**Comment by ryswork1993** [comment]
> 可以使用变量啊。
> 
> {USERNAME} {SECRET}

哦  那就没问题了， 完美

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f
