### ISSUE TITLE
[Bug] 堡垒机用户授权系统角色（权限为所有的权限），部分模块提示无权限操作

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#11795]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.7.1

**浏览器版本**
Chrome

**Bug 描述**
堡垒机用户授权系统角色（权限为所有的权限），该用户点击系统设置的模块，部分模块提示无权限操作

**Bug 重现步骤(有截图更好)**
1. 新建系统角色，勾上所有的权限，包括系统设置的所有权限。
![image](https://github.com/jumpserver/jumpserver/assets/30264974/5b8c32f6-a0b2-45c5-b0e9-41dfe50c5c49)

3. 新建一个堡垒机用户，配置系统角色为刚新建的角色。
![image](https://github.com/jumpserver/jumpserver/assets/30264974/058ab077-b261-4c39-af30-1266ad7c4ca0)

3、登录堡垒机用户，点击 系统设置-界面设置，提示无权限。
<img width="1129" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/4b26f039-20c7-4c5e-8ac7-e781b95f0e58">

**Comment by xulinde** [comment]
已知bug，v3.8修复～
https://www.tapd.cn/45454465/bugtrace/bugs/view?bug_id=1145454465001025442

**Comment by BaiJiangJie** [comment]
@xulinde 还有这个。https://github.com/jumpserver/jumpserver/issues/10773
