### ISSUE TITLE
[Bug] 控制台仪表盘-账号/资产活跃情况报表，概率性显示异常

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#11809]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.7.1

**浏览器版本**
chrome 104.0.5112.81

**Bug 描述**
控制台仪表盘-账号/资产活跃情况报表，概率性显示异常(放大缩小后可恢复正常显示)

**Bug 重现步骤(有截图更好)**
![0b9a695015ba2ff693752846f235384](https://github.com/jumpserver/jumpserver/assets/92150453/429a46e6-ca93-45f6-9855-d0165a5a817f)

**Comment by BaiJiangJie** [comment]
找环境复现一下，这个问题已经修复很多次了。
@jym503558564 

如果还是有问题，就想办法重构一下。
@huailei000

**Comment by jym503558564** [comment]
已反馈开发，待修复

**Comment by jym503558564** [comment]
已记录，待后面版本优化。
