### ISSUE TITLE
[Bug] 发邮件时出错，SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by sgyy** [jumpserver/jumpserver#11806]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
Edge 117

**Bug 描述**
发送邮件时报错，错误信息如下
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)

**Bug 重现步骤(有截图更好)**
1. 邮件设置里将邮件服务器配置为腾讯云的邮件服务。
SMTP主机：smtp.qcloudmail.com
SMTP端口：465
开启使用SSL
2. 设置好其它内容，点击“测试连接”

![image](https://github.com/jumpserver/jumpserver/assets/4221388/f3e922fe-ee05-4d55-8830-8641692a722c)

**Comment by BaiJiangJie** [comment]
使用 TLS 试试？

**Comment by sgyy** [comment]
> 使用 TLS 试试？

只支持SSL。测试使用TLS会卡住。[腾讯云文档](https://cloud.tencent.com/document/product/1288/65750)

**Comment by sgyy** [comment]
腾讯给出的[Python调用示例](https://cloud.tencent.com/document/product/1288/97581)也会出现同样的错误，解决办法是将
```python
            client = smtplib.SMTP_SSL(host, port)
``` 
改为
 ```python
            context = ssl.create_default_context()
            context.set_ciphers('DEFAULT')
            client = smtplib.SMTP_SSL(host, port, context=context)
```

**Comment by BaiJiangJie** [comment]
要不然你提个 PR，我们 review 一下。

**Comment by BaiJiangJie** [comment]
看看 django 自带的 send_mail 是不是支持。

**Comment by BaiJiangJie** [comment]
<img width="631" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/3c2fd338-7766-486c-b767-76b5a46e78a1">

<img width="861" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/81abc787-6c6c-4b8d-aa20-c17ba4b84929">

django 给出的 SMTP_SSL 中 没有添加 context 参数。

**Comment by BaiJiangJie** [comment]
默认会使用这种方式，你试一下。

<img width="797" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/7eaeae57-22ed-4335-aad0-3f4c7cfdef35">

**Comment by BaiJiangJie** [comment]
certfile 和 keyfile 默认 None。

**Comment by BaiJiangJie** [comment]
我们平时用的就是腾讯的邮件服务器，没问题啊。

**Comment by sgyy** [comment]
试了下，用腾讯QQ邮箱确实没问题
