### ISSUE TITLE
[Question] 堡垒机留存的上传和下载文件保留多久？

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11801]
**请描述您的问题.**
工作环境中会有很多上传下载的场景，3.7版本保留了相关文件，这个多久自动清理一次呢？在哪里配置

**Comment by BaiJiangJie** [comment]
不允许删除。

**Comment by pika-FENG** [comment]
> 因为有可能存放在服务器本地，也有可能存放在管理员配置的 对象存储中（录像存储）。

那现在是超过1G的不留存，其他都留存了一份，这样的话/data/jumpserver目录会越来越大呀
