### ISSUE TITLE
[Feature] 资产授权，新添资产新添前置校验

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11805]
**请描述您的需求或者改进建议.**
希望在授权规则详情，新添资产时能把已经选择的资产置灰不能选择（v2做了前置校验会置灰，v3未做），否则当授权规则资产多的时候容易出现如下情况，且难以排查
<img width="939" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/ef9ed3c9-32c6-4abe-b44d-b10bc9a0a9be">

**Comment by BaiJiangJie** [comment]
最新版本已经修复了。
