### ISSUE TITLE
[Bug] 拖动会话窗口，会提示令牌过期会话会断开

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#11819]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

版本：V3.7.1

**浏览器版本**

**Bug 描述**
连接资产后，拖动会话窗口的顺序，会提示令牌过期
![image](https://github.com/jumpserver/jumpserver/assets/104493699/d9d0c5fb-2e98-42a9-8d63-4e6e93644bbe)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.7、v3.8 上都修复一下。
@huailei000

**Comment by huailei000** [comment]
> v3.7、v3.8上都修复一下。 @huailei000

好的。
