### ISSUE TITLE
[Question] kubernetes 不展开pod信息

### ISSUE THREAD

**Issue by pingliu** [jumpserver/jumpserver#11816]
**请描述您的问题.**
jumpserver: 3.7.1

web终端登录kubernetes 资产时，默认会展开所有namespace信息，有什么方法配置不展开吗
<img width="368" alt="截屏2023-10-12 16 20 01" src="https://github.com/jumpserver/jumpserver/assets/6415493/9777b94d-86ca-4284-b43b-43cb4140c9f8">

**Comment by BaiJiangJie** [comment]
默认是展开的，不支持关闭。
