### ISSUE TITLE
[Question] 作业中心执行历史该如何删除

### ISSUE THREAD

**Issue by AbleHou** [jumpserver/jumpserver#11811]
作业中心执行历史积攒过多如何删除，另外作业管理经常加载失败不显示作业，需要多刷新几次页面才能恢复

**Comment by BaiJiangJie** [comment]
<img width="2557" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/6c271ca1-4543-4faf-9e04-391f0862eed4">

功能实现已完成，后续请关注 v3.9 版本的发布。
