### ISSUE TITLE
[Bug] 关闭密钥认证-下次登录须修改密码按钮丢失

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#11814]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v 2.28.17

**浏览器版本**
chrome 116.0.5845.187

**Bug 描述**
关闭密钥认证后，更新用户页面“下次登录须修改密码”按钮丢失

**Bug 重现步骤(有截图更好)**
![10021697080992_ pic](https://github.com/jumpserver/jumpserver/assets/97491875/6903f240-a569-42e8-ae81-e6c7736bf027)
![10041697081006_ pic](https://github.com/jumpserver/jumpserver/assets/97491875/f554f114-8445-47ba-a545-9f4926d716a3)

**Comment by BaiJiangJie** [comment]
v2.28.20 和 v3.7.2 最新版本已修复。
