### ISSUE TITLE
[Bug] 连接令牌过期按钮无法点击

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#11829]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
chrome 版本 117.0.5938.92（正式版本） (x86_64)

**Bug 描述**
连接令牌过期按钮无法点击

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/39d23bd9-d02c-4f0b-a188-f3ad3812462c)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/3432

v3.8 修复。
