### ISSUE TITLE
web控制台资产管理列表排序会被自动打乱

### ISSUE THREAD

**Issue by OscaoChaser** [jumpserver/jumpserver#1182]
再web上资产管理列表进行设置资产时，如果资产目录设置过多，会出现一级二级目录以及排序发生混乱的情况（也就是刚排好的序，刚设置好的一级二级目录，一会就会莫名其妙的被打乱）

##### 使用版本
Jumpserver 1.0.0

##### 问题复现步骤
1. 设置资产列表（资产管理-资产列表）
2. 关闭页面后重登
3.资产列表被打乱

##### 具体表现
第一步，设置资产列表
![image](https://user-images.githubusercontent.com/31474555/38538357-facc345e-3cc5-11e8-8ed8-3aed988383df.png)
以上是排序好的资产列表，一级目录为ROOT，二级目录为生产主机，测试主机，发布主机，日志主机，监控主机，三级目录略。。。
第二步，关闭页面后重登
第三步，发现资产列表被打乱
![image](https://user-images.githubusercontent.com/31474555/38538471-96238588-3cc6-11e8-88d2-fc5bc668fd47.png)
可以看到完全被打乱了，资产一塌糊涂

##### 其他
请尽快解决，这个是要上生产的，这个样子肯定没办法上了

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
