### ISSUE TITLE
[Question] 关于ChatGPT管理的模型选择

### ISSUE THREAD

**Issue by Ink-Osier** [jumpserver/jumpserver#11821]
想咨询一下大佬们在系统里管理ChatGPT的时候应该怎么进行模型选择呀，只能用默认的3.5模型嘛，我看代码里好像支持多模型，但是似乎没在页面上找到选择的地方~

**Comment by BaiJiangJie** [comment]
目前不支持其他模型，只支持 3.5 模型。

**Comment by Ink-Osier** [comment]
好的，谢谢大佬
