### ISSUE TITLE
[Bug] 快捷命令保存报错

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#11828]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
chrome 版本 117.0.5938.92（正式版本） (x86_64)

**Bug 描述**
快捷命令保存，未输入命令就保存，提示请求错误。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/5bf324b2-a3a6-480d-b232-cf338ed7067a)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
如果没有内容，保存按钮 disable。
