### ISSUE TITLE
[Bug] windows机器改密问题

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#11822]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.0

**浏览器版本**

**Bug 描述**
windows机器通过ansible ssh方式改密成功，但是资产账号那里的“更新日期”字段没有更新。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
资产账号的更新日期，只的是在产品里对账号的更新操作，不是修改远程主机上账号的时间。

**Comment by khy2021** [comment]
> 更新日期

改密成功了的话，堡垒机里面的账号的密码不是也要更新吗？更新堡垒机账号的密码，这个“更新日期”字段不是也会更新吗？
