### ISSUE TITLE
[Question] 社区版v3.7.2，配置windows资产无法连接

### ISSUE THREAD

**Issue by jeffsunpan** [jumpserver/jumpserver#11823]
**请描述您的问题.**
社区版v3.7.2，配置windows资产无法连接，请帮忙看看

![image](https://github.com/jumpserver/jumpserver/assets/19886270/d1857756-3697-4c38-bbfe-e3c8d153bbe6)
![image](https://github.com/jumpserver/jumpserver/assets/19886270/49665043-9a45-4502-ada3-4f3f3c64fa26)

**Comment by BaiJiangJie** [comment]
查看你的windows资产的平台探活协议。
如果是 ansible 需要在资产上配置 ssh 协议。
