### ISSUE TITLE
[Feature] 命令记录方式及机制咨询

### ISSUE THREAD

**Issue by ttkanni** [jumpserver/jumpserver#11836]
版本：
3.6.4

现象：
项目成员在Jumpserver生成了客户端链接，然后通过Navicat终端连接了MySQL，执行了诸多条性能特别差的SELECT查询，数据库此时跑批负载高，直接撑爆数据库负载，资源争用最终MySQL hang死。由于SELECT查询都半天不出结果，该成员直接从任务管理器kill了Navicat进程。

现象：
事后从堡垒机会话进行命令审计，未发现该成员执行SELECT的命令记录！

疑问：
1，为什么用户通过堡垒机连接数据库，执行了SELECT命令而堡垒机却没有命令执行的记录？不符合实际情况啊。
2，Jumpserver是不是只有在命令执行成功并返回了结果才会记录命令？

**Comment by ibuler** [comment]
后续更新一下逻辑，断开连接时会 flush 记录到库中

**Comment by BaiJiangJie** [comment]
v3.9 已实现，请关注后续版本的发布。

**Comment by ttkanni** [comment]
> v3.9 已实现，请关注后续版本的发布。

收到，后续新版本发布后更新。
