### ISSUE TITLE
[Feature] V3能否支持V2版本的动态用户

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#11831]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/89765365/544751fc-1c2a-4b62-a4f9-9e0f1b15dc9a)

**Comment by BaiJiangJie** [comment]
一直在考虑如何做，还没有比较理想的方案。

还在规划中。
