### ISSUE TITLE
[Bug] es 配置点击清空的问题

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#11830]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
chrome 版本 117.0.5938.92（正式版本） (x86_64)

**Bug 描述**
点击截图红框内容，填写的内容会被清空

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/cd3a2d6d-1e91-488e-8b89-6bbad2e894e5)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
@huailei000 v3.8 版本中修复一下。点击后编辑。

**Comment by BaiJiangJie** [comment]
v3.8 已优化，升级到最新版本。
