### ISSUE TITLE
[Feature] 无公网ip服务器连接问题

### ISSUE THREAD

**Issue by isyee2738** [jumpserver/jumpserver#11832]
jumpserver现在有没有连接没有公网IP（能对外上网）服务器的连接方式？ 比如说在该服务器中安装一个agent，然后与jumpserver服务器通信，通过改agent与该台服务器以及其内网其它机器连接

**Comment by BaiJiangJie** [comment]
可以啊，给资产配置网域网关就可以。

**Comment by isyee2738** [comment]
对外没有固定的公网IP也可以配置网关吗？ 我没有在网关上面看到

**Comment by isyee2738** [comment]
还有某些服务器能对外上网，但是不能配置公网ip端口转发到内部服务器，这种情况呢

**Comment by isyee2738** [comment]
@BaiJiangJie
