### ISSUE TITLE
[Bug] 3.7.1版本kubernetes 资产执行命令Permission denied

### ISSUE THREAD

**Issue by pingliu** [jumpserver/jumpserver#11840]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.1

**浏览器版本**
chrome

**Bug 描述**
版本从3.5.5升级到3.7.1后，登录k8s资产后，执行常用的命令显示permission denied

**Bug 重现步骤(有截图更好)**
<img width="479" alt="截屏2023-10-13 17 01 39" src="https://github.com/jumpserver/jumpserver/assets/6415493/402f7315-9541-4fd4-b8d4-30bfbd55b302">
<img width="413" alt="截屏2023-10-13 17 06 41" src="https://github.com/jumpserver/jumpserver/assets/6415493/7b064ec8-ba4d-463e-af3d-cbe8d444a2fe">

**Comment by LeeEirc** [comment]
基于安全的考虑，目前限制大部分命令的可执行权限。你可以使用 `vim` 创建文件。你可以罗列下 `k8s` 集群操作需要的常用命令，后续会酌情考虑放开。

**Comment by pingliu** [comment]
这个限制是从哪个版本开始的，另外我觉得这个可执行的命令，可以做成可配置的，比如常用的cat,touch,grep,sed,awk命令

**Comment by pingliu** [comment]
主要是我们生产使用3.5.5，很多命令都可以执行，升级后表现不一致了，使用者有意见，又回退了

**Comment by LeeEirc** [comment]
从 v3.7 开始。你可以临时手动进容器修改下执行权限  chmod 755 `which touch`

**Comment by pingliu** [comment]
不对啊，我刚刚测试了3.6.6，也有这个问题啊

**Comment by LeeEirc** [comment]
> 不对啊，我刚刚测试了3.6.6，也有这个问题啊

最近一个月发的修复版本也都改了。

**Comment by BaiJiangJie** [comment]
升级到最新版本解决。
