### ISSUE TITLE
[Bug] jumpserver v2.28.1 无法同步ldap用户

### ISSUE THREAD

**Issue by liwenson** [jumpserver/jumpserver#11847]
**Bug 描述**
jumpserver v2.28.1 开启ldap认证，同步配置设置为 周期执行 1小时，无法达到效果，配置为定时执行也无法同步用户。
将文档中的参数添加了，也没有同步，没有看到相关的日志输出

![image](https://github.com/jumpserver/jumpserver/assets/19527818/50b2dd49-842f-4d42-87fc-8690a65b6b70)

**Bug 重现步骤(有截图更好)**

![image](https://github.com/jumpserver/jumpserver/assets/19527818/9c5bcd8d-7aab-4082-9436-24af14b444d6)

**Comment by BaiJiangJie** [comment]
如果定期执行和周期执行同时设置了，会优先使用定期执行，也就是每天 1:00 执行。

**Comment by BaiJiangJie** [comment]
<img width="936" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/143c2234-29e8-414e-81c4-64c5240deb45">

这个参数开启。

**Comment by liwenson** [comment]
配置了定时执行也无法同步用户，已经观察了一周，重新部署了一套v2.28.1 也无法同步用户

**Comment by liwenson** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/19527818/ac40d366-b027-4db6-b21b-7bb83b874a4d)
![image](https://github.com/jumpserver/jumpserver/assets/19527818/e2021131-a27f-49b0-8afe-dcefb7371d3d)

没有效果，日志也看不出有没有执行
