### ISSUE TITLE
批量导入资产，打开自送推送，会出现不完全推送的情况(部分可以，部分不可以)

### ISSUE THREAD

**Issue by linux2ubuntu** [jumpserver/jumpserver#1184]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
