### ISSUE TITLE
[Bug] 切换成英语，部分内容显示仍然是中文

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#11849]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.7.2

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
切换成英语，部分内容显示仍然是中文

**Bug 重现步骤(有截图更好)**
1.平台设置页
![1697426207518](https://github.com/jumpserver/jumpserver/assets/35896106/37240e8a-c02d-4fdc-b7b6-2cd5148f1fbc)
![1697426215370](https://github.com/jumpserver/jumpserver/assets/35896106/7485b2be-c800-4e71-be6f-18f7ddf1c8ea)

2.改密任务执行Change secret pararms页
![1697426250626](https://github.com/jumpserver/jumpserver/assets/35896106/7f66ede4-6bca-4155-a88f-b3f03f2e704f)
![1697426234776](https://github.com/jumpserver/jumpserver/assets/35896106/8ad317ba-e444-475b-afe7-c39736ddbcda)

**Comment by jym503558564** [comment]
已记录，待修复
