### ISSUE TITLE
[Feature] JumpServerClient希望支持英文显示模式

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#11850]
**请描述您的需求或者改进建议.**
目前JumpServerClient只有中文显示，希望增加英语显示，对国外用户使用会更加友好
![image](https://github.com/jumpserver/jumpserver/assets/35896106/abe7acdc-0bd3-41a4-945b-52e9073cb084)

**Comment by BaiJiangJie** [comment]
@Halo1236 考虑一下。

**Comment by BaiJiangJie** [comment]
v2.1.0 的 Client 客户端已支持。
