### ISSUE TITLE
[Bug] All-In-One 的 Dockerfile 问题

### ISSUE THREAD

**Issue by geekidentity** [jumpserver/jumpserver#11861]
VERSION=v3.8.0-rc4  3.7.2，的Dockerfile 版本 magnus 模块一直unhealth，
https://github.com/jumpserver/Dockerfile/pull/195
我看这里有个提交，不知道是不是这个问题。

**Comment by BaiJiangJie** [comment]
VERSION=v3.8.0-rc4 这个是怎么来的？

**Comment by geekidentity** [comment]
https://hub.docker.com/r/jumpserver/magnus/tags 

这里的版本

https://github.com/jumpserver/Dockerfile/blob/master/docker-compose.yml

使用上面docker-compose方式启动

**Comment by BaiJiangJie** [comment]
是的，下个版本修复。
https://github.com/jumpserver/Dockerfile/pull/195
https://github.com/jumpserver/magnus/pull/228
https://github.com/jumpserver/installer/pull/359
