### ISSUE TITLE
[Bug] 非活跃用户未自动停用

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#11862]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.7.1

**浏览器版本**
不涉及

**Bug 描述**
不活跃用户自动禁用还是不起效，
见：https://github.com/jumpserver/jumpserver/issues/11549

**Bug 重现步骤(有截图更好)**
1.我在10月8日导出用户信息，发现其状态都是正常的
2.实际测试相关用户，也是可正常登录使用的。例子清单如下：
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

ID | *名称 | *用户名 | *邮箱 | 微信 | 手机 | MFA 级别 | 来源 | 企业微信 | 钉钉 | 飞书 | 创建者 | 最后更新者 | 备注 | Is superuser | 组织管理员 | 用户组 | 系统角色 | 组织角色 | 密码策略 | 服务账号 | 是否有效 | 已过期 | 激活 | 是否绑定了虚拟 MFA | 可以使用公钥认证 | MFA 已启用 | 需要更新密码 | 强制 MFA | 首次登录 | 登录被锁定 | 失效日期 | 加入日期 | 上次登录 | 更新日期 | 最后更新密码日期
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
98d53731-cec8-4f10-8308-81f68acae455 | 郑XX洲 | zhXXghz | zXXXz@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator |   | - | No | No | ["系统管理员(d888d904-ea4c-40db-9ff0-4bcc38216eda)", "网络管理员(e64d9eae-d102-42bc-99a1-d908aa0321f2)"] | ["支持室管理员(f0619b28-886f-4fc4-aa7b-b87686900027)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2091/03/21 14:54:28 +0800 | 2022/09/01 08:54:34 +0800 | 2023/03/01 17:08:31 +0800 | 2023/03/14 10:17:01 +0800 | 2023/03/01 16:45:21 +0800
b6a38dba-83e9-4b6c-98fa-a16f658e051e | 孔XX | koXXtao | kXXXo@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator |   | - | No | No | ["系统管理员(d888d904-ea4c-40db-9ff0-4bcc38216eda)"] | ["支持室管理员(f0619b28-886f-4fc4-aa7b-b87686900027)", "系统审计员(00000000-0000-0000-0000-000000000002)", "用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2092/04/21 14:23:28 +0800 | 2022/07/30 08:47:51 +0800 | 2023/04/07 13:24:25 +0800 | 2023/03/14 10:17:01 +0800 | 2023/01/29 09:32:57 +0800
b6a72891-f028-4881-89f8-a4c79e45b2ec | 崔XX | cuXXing | cXXXg@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator |   | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2092/05/01 15:11:12 +0800 | 2022/07/15 10:07:18 +0800 | 2023/04/25 10:42:36 +0800 | 2023/03/14 10:17:01 +0800 | 2023/02/21 09:23:10 +0800
04bddea5-0e40-4d81-8d4c-b0d791e1039a | 彭XX山 | peXXdiXngXhan | pengdXXhan@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | 彭* |   | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2092/05/01 15:11:12 +0800 | 2022/09/23 11:04:38 +0800 | 2023/07/14 18:08:14 +0800 | 2023/06/21 17:16:53 +0800 | 2023/06/21 17:16:52 +0800
e66b5d8b-0b2c-4bf8-a9bd-c03e2bb7a08b | 吴XX强 | wuXX | wuXX@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | 吴* | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2092/05/01 15:11:12 +0800 | 2022/10/27 16:30:06 +0800 | 2023/07/24 09:34:24 +0800 | 2023/07/24 09:34:03 +0800 | 2023/07/24 09:34:03 +0800
a03d6dd5-f706-4ccc-be8b-e6402bfaa5e8 | 田XX梅 | tiXXym | tiXXym@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | 田* | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2092/05/01 15:11:12 +0800 | 2022/07/25 14:05:28 +0800 | 2023/08/03 09:56:25 +0800 | 2023/08/03 09:48:00 +0800 | 2023/08/03 09:40:38 +0800
23789b18-238f-4b32-92d7-8da6b96c3273 | 潘XX海 | paXXh | paXXh@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | 潘* | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["一线支持工程师(73086d96-dcf4-42be-956c-5b7169e3442e)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2091/03/21 14:54:28 +0800 | 2022/09/01 09:09:53 +0800 | 2023/08/09 17:10:44 +0800 | 2023/07/19 16:33:18 +0800 | 2023/07/19 16:33:18 +0800
767553be-806c-4392-9fe1-d07ab78c0082 | 陈XX浪 | chXXxl | chXXxl@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | 陈* | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["一线支持工程师(73086d96-dcf4-42be-956c-5b7169e3442e)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2091/03/21 14:54:28 +0800 | 2022/09/01 09:07:02 +0800 | 2023/08/16 08:59:37 +0800 | 2023/08/01 08:45:07 +0800 | 2023/07/31 16:55:03 +0800
462a30c2-6ae4-4458-9304-328c2dd0d086 | AdXXnistraXXr | adXXn | admin@mycomany.com |   | {"code": "+86", "phone": 136XXXXX27} | 1 | local | - | - | - | Administrator | Ad*istrator |   | Yes | Yes | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["支持室管理员(f0619b28-886f-4fc4-aa7b-b87686900027)", "系统管理员(00000000-0000-0000-0000-000000000001)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2091/03/21 11:01:21 +0800 | 2021/04/07 11:01:21 +0800 | 2023/08/24 14:35:52 +0800 | 2023/08/16 15:41:23 +0800 | 2023/08/16 15:41:22 +0800
68557eb1-38b9-490d-bca2-248924925e4f | 魏XX礼 | weXXl | weXXl@roXXXXom |   | {"code": "+86", "phone": 136XXXXX27} | 2 | local | - | - | - | Administrator | Sy*m | - | No | No | ["开发部(485e1867-9884-4870-aef2-d1c37c3ddaf1)"] | ["用户(00000000-0000-0000-0000-000000000003)"] | ["OrgUser(00000000-0000-0000-0000-000000000007)"] | email | No | Yes | No | Yes | Yes | Yes | Yes | No | Yes | No | No | 2091/08/23 11:58:43 +0800 | 2022/05/11 10:16:26 +0800 | 2023/08/25 10:41:27 +0800 | 2023/08/10 09:28:12 +0800 | 2023/08/10 09:28:12 +0800

</body>

</html>

**Comment by BaiJiangJie** [comment]
v3.7 优化了一下，看看系统任务中的最后一次执行时间。

**Comment by sanpichen** [comment]
有两个相关任务，都没有自动执行的样子。我刚触发了一个，不能确认有什么效果。我直接查看用户是正常状态的。

![1697511942908](https://github.com/jumpserver/jumpserver/assets/38068938/5341b967-920a-41ec-995f-9fe9435c13c7)
其他还有好多任务似乎都没怎么执行了。
![1697512062883](https://github.com/jumpserver/jumpserver/assets/38068938/754665ce-5e5f-4a5d-9dab-42b4de310362)

**Comment by BaiJiangJie** [comment]
<img width="1728" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/7a5b9589-8f23-488c-8965-f8cc911411fe">

**Comment by BaiJiangJie** [comment]
这个任务的执行历史。

**Comment by sanpichen** [comment]
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/32935519/275700020-7a5b9589-8f23-488c-8965-f8cc911411fe.png">

![1697512304625](https://github.com/jumpserver/jumpserver/assets/38068938/cb3d90a2-c682-4141-9662-42576a4dbcd9)

**Comment by BaiJiangJie** [comment]
看着是 Celery 任务没有执行。

**Comment by BaiJiangJie** [comment]
点一下再次执行

**Comment by BaiJiangJie** [comment]
<img width="651" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/51692ae7-6e0d-48f3-a871-eac43018eb15">

顺便看看任务监控的中的任务 Worker 是不是正常。

**Comment by sanpichen** [comment]
***@***.***
 
发件人： Bryan
发送时间： 2023-10-17 11:33
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] [Bug] 非活跃用户未自动停用 (Issue #11862)
顺便看看任务监控的中的任务 Worker 是不是正常。

**Comment by sanpichen** [comment]
这个 任务有3条记录，是都点击再次执行还是只点最新的即可？



***@***.***
 
发件人： Bryan
发送时间： 2023-10-17 11:27
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] [Bug] 非活跃用户未自动停用 (Issue #11862)
点一下再次执行

**Comment by sanpichen** [comment]
触发执行后是有效果的，
确实停用过了过期账号，
现在是要看怎么定位和处理未自动执行的问题了



***@***.***
 
发件人： Bryan
发送时间： 2023-10-17 11:27
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] [Bug] 非活跃用户未自动停用 (Issue #11862)
点一下再次执行

**Comment by BaiJiangJie** [comment]
说明检测用户过期的处理逻辑是没有问题的。

定时任务没有执行的问题，可能的原因有几个，

1. 任务多被阻塞了。
2. Celery 组件挂了。

看看能否稳定复现，如果能稳定复现，那么在 reopen 另一个 issue。

**Comment by BaiJiangJie** [comment]
任何一个定时任务都行，不一定是定期检测用户过期的任务。
