### ISSUE TITLE
[Feature] 批量改密时，没有特权账号，需免密su到特权账号

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#11866]
**请描述您的需求或者改进建议.**
现在V3的版本，批量改密的时候，有些机器时没有特权账号的，他们需要提权的时候就执行的sudo的命令，但是这个是不需要输入密码的。但是现在的版本不支持，请问下官方团队，这个有没有解决方案或者有没有计划安排。

**Comment by BaiJiangJie** [comment]
最新版本现在应该是支持的。

**Comment by wxcen** [comment]
好的，谢谢，尝试了下确实可以支持。
