### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by faith2god** [jumpserver/jumpserver#11867]
**请描述您的问题.**
2.23.4 jumpserver无法通过网关连接到腾讯云mongo集群（在作为网关的机器上是可以连接到腾讯云mongo集群）。同时，可以成功通过网关连上腾讯云云主机自建的单机mongo。

报错如下
```
开始连接数据库 mongodb://172.26.81.47:27017/mo 59.7
开始连接数据库 mongodb://172.26.81.47:27017/mo error: 网络不通（连接超时）
Receive Connection closed
Connection websocket closed
```

**Comment by BaiJiangJie** [comment]
最新版本有优化，升级到最新版本试一下。

**Comment by faith2god** [comment]
升级到了最新版本      产品:JumpServer 社区版 GPLv3，版本:	v3.7.2
无法通过网关连接到腾讯云mongo集群（在作为网关的机器上是可以连接到腾讯云mongo集群）。同时，可以成功通过网关连上腾讯云云主机自建的单机mongo。
报错信息如下
```
Connecting to Database web-sv-pro-mongo(172.26.81.47)  2.8
Connecting to Database web-sv-pro-mongo(172.26.81.47) error: Authentication failed
Receive Connection closed
Connection websocket closed
```

**Comment by faith2god** [comment]
> 最新版本有优化，升级到最新版本试一下。

这是要重新提个issuse，还是要等回复啊？
