### ISSUE TITLE
[Bug] v3.7.1版本/assets/hosts/接口批量导入机器异常

### ISSUE THREAD

**Issue by no-catcake** [jumpserver/jumpserver#11879]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**Bug 描述**
通过/assets/hosts/批量导入机器出现异常
请求body为
`{
    "asset": [
        {
            "name": "CP1",
            "platform": {
                "id": 1,
                "name": "Linux"
            },
            "protocols": [
                {
                    "name": "ssh",
                    "port": 22
                }
            ],
            "address": "127.0.0.1",
            "accounts": [
                {
                    "name": "root",
                    "username": "root",
                    "secret_type": "password",
                    "secret": "abcd1234"
                }
            ]
        }
    ]
}`
报错内容为
`{
    "platform": "平台不存在"
}`
若改为单台导入则无问题

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
`[ { "name": "CP1", "platform": { "id": 1, "name": "Linux" }, "protocols": [ { "name": "ssh", "port": 22 } ], "address": "127.0.0.1", "accounts": [ { "name": "root", "username": "root", "secret_type": "password", "secret": "abcd1234" } ] } ]`

Body 应该是这样吧，不带 asset 的 key。

**Comment by no-catcake** [comment]
> `[ { "name": "CP1", "platform": { "id": 1, "name": "Linux" }, "protocols": [ { "name": "ssh", "port": 22 } ], "address": "127.0.0.1", "accounts": [ { "name": "root", "username": "root", "secret_type": "password", "secret": "abcd1234" } ] } ]`
> 
> Body 应该是这样吧，不带 asset 的 key。

3.7.1版本这样去请求会报错：
`{
    "asset": "该字段是必填项。"
}`

**Comment by BaiJiangJie** [comment]
原因是批量创建主机的时候，不允许直接创建 accounts；

`[{ "name": "CP123", "platform": 1, "protocols": [ { "name": "ssh", "port": 22 } ], "address": "127.0.0.1" }]`

这样可以。

需要创建 accounts 的话，单独调用 accounts 相关的 API。

**Comment by no-catcake** [comment]
> 原因是批量创建主机的时候，不允许直接创建 accounts；
> 
> `[{ "name": "CP123", "platform": 1, "protocols": [ { "name": "ssh", "port": 22 } ], "address": "127.0.0.1" }]`
> 
> 这样可以。
> 
> 需要创建 accounts 的话，单独调用 accounts 相关的 API。

用3.3.1版本的时候还是可以的，这是新的限制吗
