### ISSUE TITLE
请问什么时候docker hub仓库提供jumpserver/jms_all的V2.28.20的镜像版本

### ISSUE THREAD

**Issue by xionghaihua** [jumpserver/jumpserver#11873]
**请描述您的问题.**
我这边采用allinone的方式,目前部署的版本为jms_all:v2.24.2版本，由于最近暴露jumpserver的安全漏洞，需要升级版本，升级到v3版本，我这边很多特权用户丢失，因此需要升级到v2.28.20版本，但是目前jms_all没有最新镜像，请问v2版本的最新的镜像什么时候出来

**Comment by BaiJiangJie** [comment]
v2.28 不考虑支持 jms_all 了，直接升级到 v3 版本吧。
