### ISSUE TITLE
[Question] Not use remote Web after reset RDS license key

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11871]
Hi,

I deployed some Web remote with applet. But after 120 days, I reset RDS license key to continue remote.
But only RDS can work on this server, Web remote not working with error like:
![image](https://github.com/jumpserver/jumpserver/assets/75791054/7148da66-eb95-452e-9731-a75ca9c223a8)

How can I do to fix it ?

Thank you

**Comment by BaiJiangJie** [comment]
Do you mean that you can connect normally using native RDS, but cannot connect using JumpServer's Web Remote?

Can you provide the corresponding video?

**Comment by tsukiazuma** [comment]
Yes, I can remote to server with RDP, but can't remote web through that server.
This happens only after resetting the RDS license key.

Now, I can't provide video for some specific reasons.

Thank you

**Comment by BaiJiangJie** [comment]
Check security group and network settings: Make sure the RDS instance's security group settings allow connections from remote applications. If you reset the RDS key, you may need to update the corresponding security group rules. Make sure that the subnet where the RDS instance is located is configured correctly and that the network connection is smooth.

**Comment by BaiJiangJie** [comment]
Review the logs and error information of the RDS instance to determine if there are specific error messages or issues. These logs often contain useful information about connection failures.

**Comment by BaiJiangJie** [comment]
If these information are normal, then I don’t know what the cause is.

Have you tried restarting the RDS instance?

**Comment by tsukiazuma** [comment]
Oh, thank for your advice.

But network setting is not problem, I can telnet and ping to this server though tool on Jumpserver. I can remote RDP to this server.
Currently, the remote web feature cannot be used

**Comment by LeeEirc** [comment]
You can inspect the guacd logs. The log file is likely located at `/data/jumpserver/lion/data/logs/guacd.log`

**Comment by tsukiazuma** [comment]
Oh, I checked guacd logs, but haven't information about remote web. It ony show some error logs from other activity

**Comment by LeeEirc** [comment]
Has it installed another version of Chrome? There may be a version conflict. Try disabling autofill for the web asset. Does it work normally after that?

**Comment by tsukiazuma** [comment]
I only reset RDS license key and do not make any other changes or settings. I tried with not autofill.

Here is record about process remote web:
https://github.com/jumpserver/jumpserver/assets/75791054/1147559c-ae12-46c5-8bad-e9011e7b142c

**Comment by LeeEirc** [comment]
Please verify the applications installed on your Windows Server. If you have an additional version of the Chrome browser installed, it should be removed.

**Comment by tsukiazuma** [comment]
I sure that no have update about chrome on this server.

**Comment by LeeEirc** [comment]
Could you join the Discord channel at https://discord.gg/Qsrzj9xJ? We can address the issue there.
