### ISSUE TITLE
[Bug] 密码中包含特殊字符导致无法通过数据库透明代理连接 Oracle

### ISSUE THREAD

**Issue by Xyuncheng** [jumpserver/jumpserver#11876]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
chrome

**Bug 描述**
Oracle 12c 的数据库透明代理连接失败，报错一直为 ORA-01017: invalid username/password; logon denied
![image](https://github.com/jumpserver/jumpserver/assets/137035261/719de0e1-61a7-434e-9c33-0ea4830aa494)
后面发现是密码中含有特殊字符导致问题出现（使用的密码为：85D%N$%wtbWRt#79）

**Bug 重现步骤(有截图更好)**
1.打开 Web 终端
2.选择 Oracle 数据库
3.选择客户端的 DB 连接向导
4.本地 navicat 输入对应的信息
5.测试连接

**Comment by BaiJiangJie** [comment]
限制一下保存的密码包含的字符。
