### ISSUE TITLE
[Bug] 请问下一件安装后无法打开ui界面是什么情况

### ISSUE THREAD

**Issue by MrYangyt** [jumpserver/jumpserver#11874]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.2

**浏览器版本**
edge最新版本

**Bug 描述**
一键安装好后，可以登陆，但是打不开ui界面

**Bug 重现步骤(有截图更好)**
1.一键安装v3.7.2
2.配置自己的外网ip
3.登陆
<img width="1480" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/2a933ae5-7b16-4cc7-a408-bece4185f654">

**Comment by MrYangyt** [comment]
是的，用的这种一键部署的方式

**Comment by MrYangyt** [comment]
因为我服务器在国外，使用的是这条命令 curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash

**Comment by MrYangyt** [comment]
是哪个容器？我看了web这个容器是没有任何报错的

**Comment by BaiJiangJie** [comment]
core 容器的日志。

**Comment by BaiJiangJie** [comment]
正常，一个是 core 服务，一个是 celery 服务。

**Comment by BaiJiangJie** [comment]
刚试了下是可以正常访问的，你是改什么配置了吗？

**Comment by MrYangyt** [comment]
那我看core 容器没有错误的日志
<img width="844" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/e4310bfb-a574-42be-82f0-c67de51f5761">

**Comment by BaiJiangJie** [comment]
jumpserver.log 文件。

**Comment by MrYangyt** [comment]
没有，我直接一键安装好，然后什么也没有改动，然后去访问jump地址，可以访问到首页，也能登陆，但是登陆后就进不去工作台界面了

**Comment by MrYangyt** [comment]
<img width="985" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/21324be8-7d9c-48d2-a82b-132f67fe761a">
jumpserver.log 文件的错误

**Comment by BaiJiangJie** [comment]
看下终端管理，有名称重复了。

**Comment by MrYangyt** [comment]
哪个是终端管理，一键安装的怎么还会有key重复问题呢

**Comment by BaiJiangJie** [comment]
系统设置-组件设置-组件管理。

**Comment by MrYangyt** [comment]
我现在进不去页面，只能登陆，登陆点击后，一直卡在最上面那个报错上，登陆后所有页面资源都加载不出来

**Comment by BaiJiangJie** [comment]
远程你看一下吧。

**Comment by MrYangyt** [comment]
好的，用那种远程方式呢

**Comment by BaiJiangJie** [comment]
腾讯会议吧？

**Comment by MrYangyt** [comment]
好的，稍等，我安装一下

**Comment by BaiJiangJie** [comment]
白江杰 邀请您参加腾讯会议
会议主题：白江杰的快速会议
会议时间：2023/10/17 18:42-19:42 (GMT+08:00) 中国标准时间 - 北京

点击链接直接加入会议：
https://meeting.tencent.com/dm/Cl9yjdjpbAW5

#腾讯会议：579-237-695

复制该信息，打开手机腾讯会议即可参与

**Comment by BaiJiangJie** [comment]
代理设置问题，已解决。
