### ISSUE TITLE
[Feature] 重置密码功能是否可以通过OTP

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#11872]
目前是通过邮件形式推送密码重置，但很多情况下堡垒机都是隔离内网部署，不允许开通互联网访问，是否可以考虑增加OTP重置，若考虑安全问题，那是否可以考虑通过历史密码+OTP的形式重置。

**Comment by BaiJiangJie** [comment]
暂时先不考虑了。
