### ISSUE TITLE
[Bug] 基础设置页面无法回退

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11881]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
版本 118.0.5993.70（正式版本） （64 位）

**Bug 描述**
基础设置页面无法回退

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/cd8e2f3f-6065-45b9-9de9-7efd2bfab216)

**Comment by BaiJiangJie** [comment]
从别的页面点进来是可以回退的。
直接进入系统设置，因为没有上游页面所以回退按钮是 disable 的。

<img width="578" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1844743a-069b-41d0-b4bd-0018585bdd4b">
