### ISSUE TITLE
[Question] 添加配置CACHE_LOGIN_PASSWORD_ENABLED=true也无法修改虚拟账号

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#11886]
**请描述您的问题.**
<img width="899" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/c1e0f9e7-ee27-4a99-974d-5377a034e12c">

添加了配置选项 也不能点击启用 使用的是LDAP用户认证

**Comment by BaiJiangJie** [comment]
重启服务了吗？

**Comment by xiaoxiongxyy** [comment]
> 重启服务了吗？

修改了/opt/jumpserver/config/config.txt 在最后一行加上了CACHE_LOGIN_PASSWORD_ENABLED=true 然后进服务目录 ./jmsctl.sh restart。还是不行呢

**Comment by xiaoxiongxyy** [comment]
好了 应该是有缓存
