### ISSUE TITLE
[Question] 使用mobaxterm软件进行sftp连接，访问软链文件时，报错SFTP error #4: please select one of the assets

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11883]
**请描述您的问题.**
如图，请问应该怎么解决。该软链是存在并可以正常访问的，但是sftp连接访问报错
![image](https://github.com/jumpserver/jumpserver/assets/138869963/2ff33613-58e0-4d2a-8780-ae0f24cc7dc3)

**Comment by BaiJiangJie** [comment]
现在用的什么版本。

**Comment by Sanbobo1** [comment]
v3.7.1

**Comment by BaiJiangJie** [comment]
web 页面的文件管理功能能正常使用吗？

**Comment by Sanbobo1** [comment]
web页面是SFTP是正常使用的

**Comment by Sanbobo1** [comment]
mobaxterm软件连接非jumpserver堡垒机 使用SFTP访问软链目录也是正常的

**Comment by BaiJiangJie** [comment]
其他的软件呢？

**Comment by Sanbobo1** [comment]
xshell软件 连接jumpserver堡垒机 使用SFTP访问软链目录是正常的。

**Comment by BaiJiangJie** [comment]
只是软链接文件不能访问，其他都正常，是吗？

**Comment by Sanbobo1** [comment]
对的

**Comment by BaiJiangJie** [comment]
好的，后期研究一下，看看是什么原因。

**Comment by Sanbobo1** [comment]
好的 感谢支持

**Comment by Sanbobo1** [comment]
还有一个表现就是软链接如果是软链到当前目录的其他子目录，是可以打开。如果是到非当前目录的其他目录下，无法打开
![image](https://github.com/jumpserver/jumpserver/assets/138869963/7b77b16e-e4fc-47d5-8395-85957a15e271)
![image](https://github.com/jumpserver/jumpserver/assets/138869963/7e0d0135-db31-4640-9eab-258e0a966331)

**Comment by jym503558564** [comment]
已复现，已反馈开发，待修复。

**Comment by BaiJiangJie** [comment]
后面研究一下试试，软链接文件怎么处理一下比较好。

**Comment by BaiJiangJie** [comment]
v3.10 已解决。
