### ISSUE TITLE
[Bug] 更新资产无法选择linux平台

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#11880]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**
版本 118.0.5993.70（正式版本） （64 位）

**Bug 描述**
更新资产无法选择linux平台

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/1e46b497-36ea-4380-aef3-53b4641b0862)
![image](https://github.com/jumpserver/jumpserver/assets/12181410/2b187e4d-d062-4bec-b1c7-4617f90af3fc)

**Comment by BaiJiangJie** [comment]
是的，更新资产时，平台只能选择与当前平台类型相同的平台进行更新。
