### ISSUE TITLE
[Bug] web方式访问windows2000报错

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#11896]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.7.1

**Bug 描述**
web方式访问windows2000报错，无法访问，lion报错如下图，是什么原因？
![Uploading 98c9b814ae3266c6ec0593b15c95858.png…]()

**Comment by jstbw** [comment]
<img width="744" alt="98c9b814ae3266c6ec0593b15c95858" src="https://github.com/jumpserver/jumpserver/assets/66759501/20a47ff0-5a2a-4267-b1ee-9e3dd78014ab">

**Comment by BaiJiangJie** [comment]
在 Lion 组件里，ping 一下资产 IP 是不是通。

**Comment by BaiJiangJie** [comment]
应该是不支持 2000 系统。
