### ISSUE TITLE
采用ladp，用户登陆，保存公钥后，注销再登陆 报错duplicate entry 'username这里是自己的用户名' for key 'username'

### ISSUE THREAD

**Issue by lkad** [jumpserver/jumpserver#1189]
[简述你的问题]
采用ladp，用户登陆，保存公钥后，注销再登陆 报错duplicate entry 'username这里是自己的用户名' for key 'username'
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
registry.jumpserver.org/public/jumpserver:1.0.0 
##### 问题复现步骤
1. [步骤1]
系统里面配置ldap验证，再ldap里面新建普通用户。
2. [步骤2]
采用这个普通用户登陆，再jumpserver里面会提示输入邮箱和公钥，保存后，注销登陆后再次登陆就会出现。
看了一下错误报告，应该是验证用户通过后会再次插入用户，但是用户已存在，产生唯一约束报错。
##### 具体表现[截图可能会更好些,最好能截全]
![avatar](http://dh.itdhz.com/pic01.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
应该是ldap设置的有问题
```
{"username": "cn", "name": "sn", "email": "mail"}
```

映射到username的是ldap的cn字段，必须是唯一的

**Comment by lkad** [comment]
映射是按照上面来的。username是唯一的。我重新描述下，第一次登陆的时候会要求保存e-mail和公钥，保存OK后，操作其他的都是正常，退出登陆后，就会出错。个人比较怀疑，在验证账户密码通过后，是不是验证操作出问题了，然后当新用户处理直接保存出错。

**Comment by lkad** [comment]
已找到原因,cn在添加的时候前面多了一个空格，程序在做用户验证的时候出错，导致会再次存入数据库，由唯一约束报错。

**Comment by peileijp** [comment]
我也同样碰到这个问题了，麻烦问下你修改什么配置把它弄好的。

**Comment by brucegogo** [comment]
我也碰到同样问题了。
原因如@lkad所说，是因为在使用phpldapadmin添加账户的时候，CN默认前面有一个空格。
把空格去掉，重新登录就好了。

**Comment by ivonlee** [comment]
@brucegogo 你可以看下数据库中的表users_user中的username字段，从ldap中同步过来的用户名字前面有个空格，你去掉数据库里面空格后就可以登陆了，或者改下jumpserver的ldap模块用户入库逻辑，把username字段前后空格去掉。
