### ISSUE TITLE
[Question] 社区版本: v3.7.2，无法通过网关连接到腾讯云mongo集群

### ISSUE THREAD

**Issue by faith2god** [jumpserver/jumpserver#11905]
**请描述您的问题.**
升级到了最新版本 产品:JumpServer 社区版 GPLv3，版本: v3.7.2
无法通过网关连接到腾讯云mongo集群（在作为网关的机器上是可以连接到腾讯云mongo集群）。同时，可以成功通过网关连上腾讯云云主机自建的单机mongo。
两个mongo实例，使用的用户名和密码是一样的。配置的信息除了IP其他都一致。

腾讯云mongo集群连接报错信息如下

Connecting to Database web-sv-pro-mongo(172.26.81.47)  2.8
Connecting to Database web-sv-pro-mongo(172.26.81.47) error: Authentication failed
Receive Connection closed
Connection websocket closed

**Comment by O-Jiangweidong** [comment]
目前我们还不支持连接腾讯云的MongoDB集群模式的
