### ISSUE TITLE
[Question] 3.6.4版本无法连接阿里云MongoDB4 .2版本实例

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#11903]
**请描述您的问题.**
jms版本:3.6.4
mongodb v4.2
测试连接成功的  终端连接报错 无法连接
Connecting to Database gm1-mongodb(dds-bp19b79b3cca9c842.mongodb.rds.aliyuncs.com) error: Authentication failed
Receive Connection closed
Connection websocket closed

**Comment by BaiJiangJie** [comment]
其他版本的 MongoDB 可以连接吗？

**Comment by wangmingwang123** [comment]
其他版本指的是3.2嘛我们目前在使用的只有3.2和4.2

**Comment by BaiJiangJie** [comment]
3.2 的可以连接成功吗？

**Comment by wangmingwang123** [comment]
刚测试了下 4.0可以

**Comment by O-Jiangweidong** [comment]
你们的MongoDB4.2版本的是什么配置呢，我刚才测试了阿里云的MongoDB4.2版本3节点，无只读节点的机器，使用Primary节点登录成功

**Comment by O-Jiangweidong** [comment]
你们的MongoDB4.2版本的是什么配置呢，我刚才测试了阿里云的MongoDB4.2版本3节点，无只读节点的机器，使用Primary节点登录成功
<img width="1042" alt="image" src="https://github.com/jumpserver/jumpserver/assets/80373698/08ba826e-d5e9-44e9-bab4-56f07332a956">

**Comment by wangmingwang123** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/73093158/564f91a1-0ed6-46a6-8d66-01da53271a09)
我也是三节点呢

**Comment by BaiJiangJie** [comment]
你的 MongoDB 4.2 是哪个云服务商的？
@wangmingwang123

**Comment by BaiJiangJie** [comment]
升级到最新版本使用，如还有问题 Reopen issue。
