### ISSUE TITLE
[Feature] 增加服务器指纹验证功能

### ISSUE THREAD

**Issue by Fallen-Breath** [jumpserver/jumpserver#11901]
## 描述

以 ssh 类型的连接为例，目前 jms 使用 ssh 协议链接一台资产时，并没有验证资产的 ssh 指纹（fingerprint）是否可信

这导致即使资产的 ssh 指纹发生了变化（如系统重装），仍无需在 jms 上进行任何配置就能照常连接这台资产。这可能导致一些潜在的安全问题，无法防御如目标资产 ssh server 遭篡改、ssh 连接遭受中间人攻击等危险情况

## 例子

一个简单的复现用例：

1. 创建一个新的 linux 资产 A，指向某台服务器 svr，配置好账号信息
2. 使用 ssh 连接资产 A
3. 重新安装 svr 的系统，但保持账号密码不变。这将改变服务器的 ssh 指纹，可在重装前后用 `ssh-keyscan` 等方式验证
4. 使用 ssh 链接资产 A

可以发现，在 4. 的第二次 ssh 可以畅通无阻地直接连到 svr，没有任何阻止 / 警告，就像服务器没有被重装一样

复现于 JumpServer 社区版 GPLv3 `v3.7.2`

## 期望功能

1. 为一台资产配置 ssh 连接方式时，需显式配置好其 ssh 指纹。方式可选：
    - 首次 ssh 连接这台主机时，需要管理员确认目标主机返回的指纹是否符合预期
    - 管理员在资产配置界面，预先输入服务器的 ssh 指纹。格式可参考 `~/.ssh/known_hosts`
2. 每次进行 ssh 连接时，如果发现服务器的 ssh 指纹发生变化，则阻止该连接。需要管理员确认这一新指纹可信，才可允许连接
    - 也即 ssh 连接时，目标服务器的 ssh 指纹必须是已知可信的，才允许 ssh 连接。否则，管理员
3. 对资产 ssh 指纹的查看、修改等配置操作

上述功能可以在管理后台 / 配置文件里开关。为了兼容性考虑，可考虑默认关闭

## 对比

以 linux 系统常见的 openssh client 作为参考进行对比，版本为  `OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022`

openssh 的客户端在首次连接、再次连接发现指纹不匹配时，均有对目标主机 ssh 指纹的检查验证，即

```bash
$ # 首次连接时
$ ssh 1.2.3.4
The authenticity of host '1.2.3.4 (1.2.3.4)' can't be established.
ED25519 key fingerprint is SHA256:strGfidAtysZhIaGsoMd3DRuNUAB3TF9EDotlxju3ko.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '1.2.3.4' (ED25519) to the list of known hosts.
```

```bash
$ # 二次链接时，发现指纹不匹配
$ ssh 1.2.3.4
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:NKgn1bBdDUmU3Ppog6HotMms8oeQUx+s9VYtxKoi9QI.
Please contact your system administrator.
Add correct host key in /home/example/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /home/example/.ssh/known_hosts:13
Host key for 1.2.3.4 has changed and you have requested strict checking.
Host key verification failed.
```

## 其他

其他连接资产的协议可能也存在类似指纹的概念，如 rdp 中主机发过来的证书的指纹。对这些“指纹”信息的验证，希望也能一并支持

**Comment by BaiJiangJie** [comment]
感谢你的提问，经过内部慎重讨论，连接过程中暂时不考虑增加对ssh指纹的校验。

**Comment by Fallen-Breath** [comment]
是否能给出一些不考虑支持的理由？该 feature request 与 ssh 的安全性密切相关。若不考虑支持，使用 jumpserver 进行 ssh 连接时将存在不可忽视的安全风险

**Comment by Fallen-Breath** [comment]
一个基于 `v3.8.1` 版本 koko 的简单 ssh 指纹验证概念验证：https://github.com/Fallen-Breath/koko/commit/a2c54c67bf15a66c25ce4bf58cc75928a639f3b6

虽然并不完善，只能拿来个人用用，但确实已起到了指纹验证的作用，确保了 ssh 连接的安全性
