### ISSUE TITLE
[Bug] 作业任务无法正常定时运行

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#11906]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.7.2
**浏览器版本**
Microsoft Edge
版本 118.0.2088.57 (正式版本) (64 位)
**Bug 描述**
作业任务无法正常定时运行

**Bug 重现步骤(有截图更好)**
设置定时任务时间保持，不定时运行
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/31712250-6287-4c4f-8d5e-a039818241e7)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/649c184e-7f2a-4657-bd70-35c19c9b9053)

**Comment by BaiJiangJie** [comment]
修改一下定期执行的时间。每分钟跑一次有点频繁。

改成每 10 min 跑一次试试。

**Comment by flacce** [comment]
> 修改一下定期执行的时间。每分钟跑一次有点频繁。
> 
> 改成每 10 min 跑一次试试。

应该不是执行频率的问题，之前是设置每天定时跑一次，但是没有执行。设置一分钟一次是测试能不能跑起来一次定时任务，结果就是还是跑不起来。十分钟一次也测试了，不行的。
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/ed87c966-6f98-42d2-b75c-8a72cd471469)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/03e6c419-4256-4b52-8247-b82ab535dad2)

**Comment by BaiJiangJie** [comment]
celery 容器正常吗？

**Comment by flacce** [comment]
> celery 容器正常吗？

![图片](https://github.com/jumpserver/jumpserver/assets/64127000/05ae0100-f000-4912-8c31-d2298349bcfb)
正常的

**Comment by flacce** [comment]
更新v3.8.0后，能正常跑了

**Comment by flacce** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/d4719b9b-a9f0-4b50-ad73-06203577e1f3)

**Comment by BaiJiangJie** [comment]
好的，也遇到过几次定时任务不执行的情况，但是没有稳定复现。

后期会多关注一下。
