### ISSUE TITLE
[Bug]3.7.2版本不支持连接mysql 5.1.37-community

### ISSUE THREAD

**Issue by 2023fan** [jumpserver/jumpserver#11919]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.2-企业版

**浏览器版本**
chrome、火狐都试过了

**Bug 描述**
mysql 版本为：5.1.37-community或者 5.1.37-community-log
通过web-cli连接，可以正常连接
通过navicat连接，报错是：1045 - backend auth error auth failed
![image](https://github.com/jumpserver/jumpserver/assets/145900305/6b8ff1a5-f5f2-41a1-83ef-7bd2cf09fd57)
通过web-GUI方式连接，报错是：client plugin auth is required
<img width="464" alt="77fc6068a6ab53bc75079f2cb529424" src="https://github.com/jumpserver/jumpserver/assets/145900305/5be3026b-0df9-4094-acc1-a4212d55b5ac">
连接测试，报错是：unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1115, \"Unknown character set: 'utf8mb4'\")"
![image](https://github.com/jumpserver/jumpserver/assets/145900305/ac6e7d72-4403-4540-95c5-20059f402d0b)

**Bug 重现步骤(有截图更好)**
1.在一台linux机器，安装mysql版本为：5.1.37-community或者 5.1.37-community-log

**Comment by BaiJiangJie** [comment]
可能是不支持这两个版本。

**Comment by faith2god** [comment]
社区版v3.8.0 连接腾讯云数据库 mysql5.7，连接测试报同样的错，web-cli可正常连接。

**Comment by BaiJiangJie** [comment]
@2023fan 5.1 版本的 MySQL 不支持，最低版本支持到 5.7。

**Comment by BaiJiangJie** [comment]
@faith2god 看一下 Magnus 的日志有没有报错。
