### ISSUE TITLE
[Bug] v2.28.20 升级到v3.7.2 报[ERROR] Failed to change the table structure!

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#11910]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.20

**浏览器版本**
chrome

**Bug 描述**
v2.28.20版本原来是从v2.12升级过来的。这次升级到v3版本的时候报错。

**Bug 重现步骤(有截图更好)**
1、在线升级，使用./jmsctl.sh upgrade
2、升级表结构的时候报错，但是没有具体的mysql相关错误

![搜狗截图20231019143007](https://github.com/jumpserver/jumpserver/assets/11976391/26cae351-46ad-43c9-981b-ac5a921cb6f4)

**Comment by BaiJiangJie** [comment]
像是表结构迁移问题，v2 到 v3 升级按照这种方式操作。

https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9

**Comment by ztskycn** [comment]
> 像是表结构迁移问题，v2 到 v3 升级按照这种方式操作。
> 
> https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9

就是按照这个方式升级的
