### ISSUE TITLE
[Question] 使用excel模板导入（创建）用户后无法使用模板中的密码登录

### ISSUE THREAD

**Issue by skinnyshy** [jumpserver/jumpserver#11922]
**请描述您的问题.**
- 产品版本：v3.7.2
- 问题描述：使用excel模板导入（创建）用户后无法使用模板中的密码登录

密码策略配置：
![image](https://github.com/jumpserver/jumpserver/assets/12553514/812bd0aa-1129-4663-8708-8da318224fd5)
密码：
![image](https://github.com/jumpserver/jumpserver/assets/12553514/23db1938-2a9e-4e0f-8a8d-9d270751d013)
导入：
![image](https://github.com/jumpserver/jumpserver/assets/12553514/0f04a037-791a-4b00-8826-8eb388e5478e)
登录测试
<img width="610" alt="image" src="https://github.com/jumpserver/jumpserver/assets/12553514/cbf9d508-9bb5-4628-8506-8e103f13a004">

**Comment by BaiJiangJie** [comment]
不要使用回显的密码登录。（这个密码是加密显示的。）

使用 Excel 中的密码登录。（Admin@123456789）

**Comment by skinnyshy** [comment]
> 不要使用回显的密码登录。（这个密码是加密显示的。）
> 
> 使用 Excel 中的密码登录。（Admin@123456789）

你好， 使用的就是加密之前的密码登录的
