### ISSUE TITLE
[Bug] 账号/资产活跃情况 显示异常

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11934]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V.3.8.0
**浏览器版本**
Microsoft Edge
版本 118.0.2088.61 (正式版本) (64 位)
**Bug 描述**
账号/资产活跃情况 显示异常
**Bug 重现步骤(有截图更好)**
1.![image](https://github.com/jumpserver/jumpserver/assets/70053869/406eb38b-91fe-45a5-9603-34e139e19d5d)

**Comment by jym503558564** [comment]
感谢反馈，待修复。

**Comment by JeongHyeokLee** [comment]
版本3.9.0版本 活跃账号正常了 但是活跃资产依然有问题
![image](https://github.com/jumpserver/jumpserver/assets/70053869/0a094ff5-bc3c-4b75-a86a-ccc58406bff5)

**Comment by BaiJiangJie** [comment]
拖拉一下浏览器窗口大小应该就可以了。
