### ISSUE TITLE
[Bug] 升级到 3.8.0 无法连接，koko 有错误信息

### ISSUE THREAD

**Issue by yunyouu** [jumpserver/jumpserver#11930]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.8.0
**浏览器版本**

chrome 最新版本
**Bug 描述**
连接到节点返回 502 错误，koko 一直在重启，错误信息如下
<img width="1185" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32095100/cb945459-2492-409c-9641-e400faf34f3a">

**Comment by ibuler** [comment]
access key 失效了，删掉重启

**Comment by yunyouu** [comment]
感谢🙏
