### ISSUE TITLE
[Bug] 设置 TLS 自签名证书后无法在 Web 控制台中进行身份验证并收到 CSRF 错误

### ISSUE THREAD

**Issue by dfluenza** [jumpserver/jumpserver#11933]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.8.0

**Bug 描述**

我已经创建了自签名证书和密钥，但尝试在 Web 应用程序中进行身份验证时出现 CSRF 错误。

我按照说明使用 TLS 证书设置 HTTPS 连接，但始终收到身份验证错误。
这是我的配置文件：

1. /opt/jumpserver/config/config.txt
2. /opt/jumpserver/config/nginx/lb_http_server.conf 

<img width="809" alt="Снимок экрана 2023-10-20 в 15 54 40" src="https://github.com/jumpserver/jumpserver/assets/32838937/d22ce147-a350-4073-83a3-b2ed681f8b9d">
<img width="835" alt="Снимок экрана 2023-10-20 в 15 56 06" src="https://github.com/jumpserver/jumpserver/assets/32838937/e82779b7-f860-48b7-88b1-338a74f4c947">

**Comment by dfluenza** [comment]
这看起来很奇怪，但是当我为 Web 控制台分配外部 IP 地址并修改配置文件时，错误消失了。我不确定这是否是预期行为，但我仍在努力在内网中设置 HTTPS 连接。

**Comment by BaiJiangJie** [comment]
分配外部 IP 地址后，正常了吗？

**Comment by dfluenza** [comment]
是的，分配外部IP后就可以了，但是如果我只需要在内网中使用怎么办？

**Comment by BaiJiangJie** [comment]
@wojiushixiaobai 帮忙看看有没有思路？

**Comment by BaiJiangJie** [comment]
升级到最新版本使用，如还有问题 Reopen issue。
