### ISSUE TITLE
[Bug]  DOMAINS 解析错误

### ISSUE THREAD

**Issue by johnny-jiang** [jumpserver/jumpserver#11935]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.8.0

**浏览器版本**
Chrome 已是最新版本
版本 118.0.5993.96（正式版本） (arm64)

**Bug 描述**
配置文件的DOMAINS的端口包含`:80`的时候，会被替换，比如:  `172.25.8.123:8081`会被替换成 `172.25.8.12381`

**Bug 重现步骤(有截图更好)**
1. 查询jms_core的日志，提示 
```
ALLOWED_HOSTS: 
  - 172.25.8.12381
  .....
```
2. 对应代码: https://github.com/jumpserver/jumpserver/blob/v3.8.0/apps/jumpserver/settings/base.py#L82
```
ALLOWED_DOMAINS = [host.replace(':80', '').replace(':443', '') for host in ALLOWED_DOMAINS]
```

**Comment by BaiJiangJie** [comment]
有 Bug，小版本修复一下。

临时处理，你配置的时候不用写 80 和 443。

**Comment by xzplays** [comment]
k8s，通过helm商店部署后提示
配置文件有问题，无法登录，请联系管理员或查看最新文档
如果你是管理员，可以更新配置文件解决，设置配置项
DOMAINS=xxxx:30478

**Comment by wojiushixiaobai** [comment]
@xzplays 按照要求配置 DOMAINS

**Comment by xzplays** [comment]
@wojiushixiaobai 看到了。那行配置被注释了，当成注解了。

**Comment by sckghost** [comment]
我也是相同的问题，直接配置config.txt中的domain不生效
![image](https://github.com/jumpserver/jumpserver/assets/7287929/b7bbc893-351b-4476-9f27-939cd3874c7e)

**Comment by zydudu** [comment]
> 我也是相同的问题，直接配置config.txt中的domain不生效，现在是直接登录不了了 ![image](https://user-images.githubusercontent.com/7287929/277227804-b7bbc893-351b-4476-9f27-939cd3874c7e.png)

你的端口号中含有80或者443吗？把你的端口号暂时换成不带80或者443的，要不就降低版本，实在不行就等bug修复发版。。

**Comment by BaiJiangJie** [comment]
v3.8.1 会修复。
