### ISSUE TITLE
[Bug] jumpserver-client-darwin.dmg(Apple Silicon)-M2 芯片-无法打开

### ISSUE THREAD

**Issue by ITZhai** [jumpserver/jumpserver#11938]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

JumpServer的版本：v3.7.1

下载的客户款工具：
下载最新的安装包：jumpserver-client-darwin.dmg(Apple Silicon)

**Bug 描述**
下载安装后，无法打开。
提示：
无法打开“JumpServerClient”，因为Apple无法检查其是否包含恶意软件。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/49891327/97befec0-6ebc-41e8-a1d2-08842ac289ef)

**Comment by BaiJiangJie** [comment]
因为目前 Client 没有 License，在 安全 里面打开信任就可以了。
