### ISSUE TITLE
[Bug] 使用ssh链接jumpserver后 搜索资产 第一次会全部显示， 之后再按一次回车 就显示不全了。只剩下部分了。

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#11942]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.0
**浏览器版本**
Microsoft Edge
版本 118.0.2088.61 (正式版本) (64 位)
**Bug 描述**
使用ssh链接jumpserver后 搜索资产 第一次会全部显示，  之后再按一次回车 就显示不全了。只剩下部分了。
**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/70053869/3b7f1bb5-1e0e-42db-983a-5248a9f2548e)

**Comment by BaiJiangJie** [comment]
在回车相当于下一页。

这是分页显示的。

你看总数量 17 个。第一页 15 个，第二页 2 个。
