### ISSUE TITLE
[Bug] helm部署的v3.8.0存在远端IP获取不正确，显示的始终是ingress的私网段IP，旧版本没问题。

### ISSUE THREAD

**Issue by spbdev** [jumpserver/jumpserver#11947]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
浏览器无关，firefox/chrome都试过

**Bug 描述**
k8s下helm部署的jumpserver，之前的版本都是正常的，上周五从3.7.2升级到3.8.0后，获取的远端IP成了Ingress(traefik)的pod IP了，而不是浏览器所在的客户端外网IP。之前的3.7.x版本都没有问题。

通过k8s部署一个测试用的tomcat，放一个jsp页面观察，header中的x-real-ip、x-forwarded-for都是正确的远端公网IP，只有getRemoteAddr()取到的才是traefik的私网IP(10.42.0.x)，说明k8s本身是没有问题的。

**Bug 重现步骤(有截图更好)**
1.k8s部署jumpserver
2.观察审计-会话审计-会话记录中的远端IP
3.

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/jumpserver/issues/11935

**Comment by spbdev** [comment]
> * [[Bug]  DOMAINS 解析错误 #11935](https://github.com/jumpserver/jumpserver/issues/11935)

感觉不是域名解析错误。说的是客户端（浏览器）IP显示不正确，跟域名没关系的。本质就是获取IP的代码有问题，大体看了下，疑似11870这次代码提交导致的（不很确定）：https://github.com/jumpserver/jumpserver/commit/b5ef239c6ce99a9ee61cdebd0077875592dc9536

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/installer/blob/dev/config-example.txt#L151
- https://github.com/jumpserver/docker-web/blob/master/init.sh#L15
```
# 使用内置 SLB, 如果 Web 页面获取到的客户端 IP 地址不正确, 请将 USE_LB 设置为 0
# USE_LB 设置为 1 时, 使用配置 proxy_set_header X-Forwarded-For $remote_addr
# USE_LB 设置为 0 时, 使用配置 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
USE_LB=1
```

**Comment by spbdev** [comment]
添加USE_LB确实可以。但是旧版本却没这个问题。搞不懂是bug还是啥问题。

**Comment by spbdev** [comment]
添加USE_LB=0后，审计台会话记录的IP是显示正常了，但是“在线用户”的IP显示的还是私网IP。

**Comment by BaiJiangJie** [comment]
需要修改一下 登录日志和在线会话的 IP 获取方式。

v3.8.1 版本修复。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/11963/files

**Comment by spbdev** [comment]
> 需要修改一下 登录日志和在线会话的 IP 获取方式。
> 
> v3.8.1 版本修复。

v3.8.1修复了？我更新后还是没效果啊，不论web的env是否添加USE_LB: 0都一样。用的是helm方式，因为没发布3.8.1的chart，用的3.8.0的chart但是values.yaml里面的镜像版本用的3.8.1。

**Comment by carlsue** [comment]
一样的升级到3.8.1没有效果。直连是可以获取到真实ip的。但是前面加个nginx就不行了。用的是官方的nginx反代配置

**Comment by carlsue** [comment]
修改自己的nginx解决了，要进入nginx 的http_server.conf 配置把：    proxy_set_header X-Forwarded-For $remote_addr;改为    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

**Comment by wojiushixiaobai** [comment]
@carlsue - https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/values.yaml#L838
```json
  env: []
    # nginx client_max_body_size, default 4G
    CLIENT_MAX_BODY_SIZE: 4096m
    ## See: https://github.com/jumpserver/docker-web/blob/master/init.sh#L37
    # USE_LB: 1, then nginx use 'proxy_set_header X-Forwarded-For $remote_addr'
    # USE_LB: 0, then nginx use 'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for'
    USE_LB: 0
```

**Comment by spbdev** [comment]
@wojiushixiaobai 已经修改了USE_LB: 0了，会话记录里面IP显示正常，但在线用户的IP显示还是局域网的
![1](https://github.com/jumpserver/jumpserver/assets/5189960/f0872f16-e5f3-4a50-b9e2-8b15a9123630)

**Comment by wojiushixiaobai** [comment]
@spbdev 确定版本是最新

**Comment by spbdev** [comment]
> @spbdev 确定版本是最新

helm chart v3.8.1，镜像版本v3.8.1，WEB界面“关于”和“WEB终端"也都显示的是v3.8.1

**Comment by carlsue** [comment]
> @carlsue - https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/values.yaml#L838
> 
> ```
>   env:
>     # nginx client_max_body_size, default 4G
>     CLIENT_MAX_BODY_SIZE: 4096m
>     ## See: https://github.com/jumpserver/docker-web/blob/master/init.sh#L37
>     # USE_LB: 1, then nginx use 'proxy_set_header X-Forwarded-For $remote_addr'
>     # USE_LB: 0, then nginx use 'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for'
>     USE_LB: 0
> ```

嗯，我是docker-compose部署，这个useLb不知道加哪里，手动进入web容器，改成你说明的就ok了

**Comment by wojiushixiaobai** [comment]
@spbdev 你看看 Nginx 那边获取到的日志是否正常，如果你前面有 SLB，你还得确定下传递过来的真实 IP 变量名是啥
日志在 jms_web 这个 pod 里面 /var/log/nginx ，这是一个 Nginx 镜像

**Comment by spbdev** [comment]
> @spbdev 你看看 Nginx 那边获取到的日志是否正常，如果你前面有 SLB，你还得确定下传递过来的真实 IP 变量名是啥 日志在 jms_web 这个 pod 里面 /var/log/nginx ，这是一个 Nginx 镜像

nginx日志里面记录的就是局域网IP。传递过来的真实IP变量名x-real-ip、x-forwarded-for(http的header)，都是正确的远端公网IP。另外，注意下我反馈的问题哦：审计台会话记录的IP显示是正常的（是外网IP），但是“在线用户”的IP显示的是私网IP。

**Comment by wojiushixiaobai** [comment]
@spbdev 
根据 https://github.com/jumpserver/jumpserver/blob/v3.8.1/apps/common/utils/common.py#L157 定义
修改下 web pod 的配置文件试试
```sh
# 主要是下面两行，你根据实际情况修改试试。
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**Comment by carlsue** [comment]
> > @spbdev 你看看 Nginx 那边获取到的日志是否正常，如果你前面有 SLB，你还得确定下传递过来的真实 IP 变量名是啥 日志在 jms_web 这个 pod 里面 /var/log/nginx ，这是一个 Nginx 镜像
> 
> nginx日志里面记录的就是局域网IP。传递过来的真实IP变量名x-real-ip、x-forwarded-for(http的header)，都是正确的远端公网IP。另外，注意下我反馈的问题哦：审计台会话记录的IP显示是正常的（是外网IP），但是“在线用户”的IP显示的是私网IP。

我遇到过，你改成这样应该就ok了
![image](https://github.com/jumpserver/jumpserver/assets/17507066/156f94c4-05ca-46ca-9cc3-2b5ab1c575eb)

**Comment by spbdev** [comment]
> @spbdev 根据 https://github.com/jumpserver/jumpserver/blob/v3.8.1/apps/common/utils/common.py#L157 定义 修改下 web pod 的配置文件试试
> 
> ```shell
> # 主要是下面两行，你根据实际情况修改试试。
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> ```
> 
> 代码方面我们已经在排查了，需要时间。如果代码有问题的话将在之后的版本修复

我进入容器看了nginx的配置文件/etc/nginx/conf.d/jms.conf，已经有以下配置了（helm方式安装时values.yaml配置了USE_LB: 0）
`proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

**Comment by spbdev** [comment]
> > > @spbdev 你看看 Nginx 那边获取到的日志是否正常，如果你前面有 SLB，你还得确定下传递过来的真实 IP 变量名是啥 日志在 jms_web 这个 pod 里面 /var/log/nginx ，这是一个 Nginx 镜像
> > 
> > 
> > nginx日志里面记录的就是局域网IP。传递过来的真实IP变量名x-real-ip、x-forwarded-for(http的header)，都是正确的远端公网IP。另外，注意下我反馈的问题哦：审计台会话记录的IP显示是正常的（是外网IP），但是“在线用户”的IP显示的是私网IP。
> 
> 我遇到过，你改成这样应该就ok了 ![image](https://user-images.githubusercontent.com/17507066/282632050-156f94c4-05ca-46ca-9cc3-2b5ab1c575eb.png)

已经有你说的配置了，我是helm方式安装的。
`proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

**Comment by BaiJiangJie** [comment]
主要是这行：proxy_set_header X-Real-IP $remote_addr;

**Comment by BaiJiangJie** [comment]
根据 jumpserver 的代码，配置 X-Real-IP 后，X-Forwarded-For 不管填什么都是无效的。
k8s 默认情况下不能使用 proxy_set_header X-Real-IP $remote_addr，需要使用 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
除非是 slb ，用户对外的出口就是公网出口

**Comment by wojiushixiaobai** [comment]
- link: https://github.com/jumpserver/jumpserver/issues/12246#issuecomment-1837971985

![image](https://github.com/jumpserver/jumpserver/assets/24326988/404b062d-c20f-404b-8664-b01180fc48e8)

**Comment by BaiJiangJie** [comment]
按照上面的方式重新配置一下，如果还有问题 Reopen issue。
