### ISSUE TITLE
[Feature] 期望主界面增加语言切换功能

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#11949]
**请描述您的需求或者改进建议.**
期望主界面（lina）增加语言切换功能。

场景：
目前 JumpServer 语言切换功能设置在登录界面和 web 终端界面，对接第三方认证后JumpServer 登录界面不再出现，导致语言切换必须先进入到 web 终端修改后再回到主界面刷新，比较繁琐

**Comment by BaiJiangJie** [comment]
嗯，以前版本有，后来挪到了登录页面。

计划 v3.9 版本考虑加回来。

**Comment by BaiJiangJie** [comment]
<img width="2557" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/8ebfbc66-fa95-4eb5-b664-e4971ee165c9">

功能实现已完成，后续请关注 v3.9 版本发布。
