### ISSUE TITLE
[Bug] OAuth2 单点集成在获取 Token 的时候，表单请求格式的变化

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#11941]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3最新版

**浏览器版本**
所有版本

**Bug 描述**
在 OAuth2 请求中有一个步骤是获取 Token，但是对方在接受不 Post 请求的时候要求的 Content-Type 是x-www-form-urlencoded。但是在现在的版本中默认的是 Json 的格式，导致在获取 Token 的时候有问题。附 azure AD 的链接。
https://learn.microsoft.com/zh-cn/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow

希望官方在界面上可以加一个配置项。

**Bug 重现步骤(有截图更好)**
后面手动改代码实现了。
<img width="1330" alt="企业微信截图_2f97ad7a-8bd6-48fd-82bb-7f65b82a02f6" src="https://github.com/jumpserver/jumpserver/assets/40848979/6391d103-77f1-43bb-b22c-1306c7746924">

**Comment by O-Jiangweidong** [comment]
https://github.com/jumpserver/jumpserver/pull/11945

**Comment by jym503558564** [comment]
已修复
