### ISSUE TITLE
[Feature]  账号模板可以给个标签字段

### ISSUE THREAD

**Issue by lls205** [jumpserver/jumpserver#11943]
**请描述您的需求或者改进建议.**

账号模板的条数比较多，不太好区分

建议： 
1. 详情页加个标签字段，按标签筛选
2. 选择资源后选择模板，按标签筛选后显示再选择

**Comment by BaiJiangJie** [comment]
嗯，可以考虑。

**Comment by BaiJiangJie** [comment]
预计 v3.10 支持。

**Comment by jym503558564** [comment]
v3.10.0已优化全局标签功能，请升级进行测试。如有其他问题，可再次打开Issues.
