### ISSUE TITLE
[Bug] Web GUI访问数据库做查询时超时时间超过10s抛异常

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#11959]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.6.4

**浏览器版本**
-

**Bug 描述**
TiDB（在JumpServer里配置成MySQL），假设SQL就是要查10秒以上，如果查询需要的时间超过10秒，就会出现如图的错误信息
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/40846859/0c04eb84-8838-4362-91c8-d06fe657eef1)

2.
3.

**Comment by BaiJiangJie** [comment]
可能是后端固定了 10s 的超时时间。

大概多少数据量呢？

**Comment by jym503558564** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40739051/622b0dca-d66f-4444-ab87-b9a3c32b2a25)
经测试，查询30万左右的数据，无报错。Mysql版本为5.7.36。JumpServer版本为3.8.0。

**Comment by xusongtao** [comment]
![1698568704750](https://github.com/jumpserver/jumpserver/assets/40846859/badcfdbf-02ed-4396-bcc2-3c9dc52f8d68)

执行时间超过 10s 即复现。
如图所示，查询一张千万数据量的大表，通过 order by 增加执行时间。
在limit=50时，执行时间 9050ms，正常返回结果；
在limit=100时，执行时间 9259ms，正常返回结果；
在limit=300时，执行时间 8544ms，正常返回结果；
在limit=3000时，执行时间 16075ms，抛异常；

**Comment by jym503558564** [comment]
https://github.com/jumpserver/jumpserver/issues/11958 问题重复，关闭一个
