### ISSUE TITLE
[Bug] Web GUI 连接 MySQL 查询大表时抛异常 

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#11958]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v 3.6.4

**浏览器版本**
v 117.0

**Bug 描述**
Web GUI 连接 MySQL 查询数据量为几十万的单表时正常返回。查询大表时抛 Communications link failure The last packet successfully received from the server was 33,990 milliseconds ago. The last packet sent successfully to the server was 33,990 milliseconds ago.

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/40846859/e4d22cc4-92ac-4b1f-9be9-08412387106c)

2.

3.

**Comment by BaiJiangJie** [comment]
和这个应该是同样的问题。https://github.com/jumpserver/jumpserver/issues/11959

**Comment by BaiJiangJie** [comment]
多少数据啊？

**Comment by jym503558564** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40739051/e6903d0d-e064-42a5-91cc-73bb1bc3dcd2)
经测试，查询30万左右的数据，无报错。Mysql版本为5.7.36

**Comment by xusongtao** [comment]
感谢回复。数千万数据量大表会这样，数十万的小表可以正常返回

**Comment by BaiJiangJie** [comment]
千万级别的数据必现吗？

**Comment by xusongtao** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40846859/dc048258-eca9-4256-8d0d-fb6d6a2744d5)
必现。执行时间超过 10s 即复现。
如图所示，查询一张千万数据量的大表，通过 order by 增加执行时间。
在limit=50时，执行时间 9050ms，正常返回结果；
在limit=100时，执行时间 9259ms，正常返回结果；
在limit=300时，执行时间 8544ms，正常返回结果；
在limit=3000时，执行时间 16075ms，抛异常；

**Comment by jym503558564** [comment]
远程看了环境，确实他们的环境可百分百复现。已反馈开发，待修复。

**Comment by BaiJiangJie** [comment]
发一下 Chen 组件的日志。
@xusongtao

**Comment by BaiJiangJie** [comment]
升级到最新版本使用，如还有问题 Reopen issue。
