### ISSUE TITLE
[Bug] 3.4升级3.8后无法访问

### ISSUE THREAD

**Issue by madman163** [jumpserver/jumpserver#11969]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.8

**浏览器版本**

chrome版本 117.0.5938.150（正式版本） （64 位）
**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.3.4升级3.8后,jws_web容器 0.0.0.0:8080->8080/tcp,容器内能访问容器外不能访问
2.DOMAINS 填了域名 127.0.0.1  机器内网IP 外网IP都不能访问
3.监听显示为tcp6       0      0 :::8080                 :::*                    LISTEN      31561/docker-proxy  
4. 其他的堡垒机例如spug 也是tcp6监听正常访问
5. net.ipv4.ip_forward=1  没错
所以实在是不知道错在哪了 nc 端口正常 curl 返回Connection reset by peer
[root@dl-devops ~]# nc -zv 127.0.0.1 8080
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:8080.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
[root@dl-devops ~]# curl 127.0.0.1:8080
curl: (56) Recv failure: Connection reset by peer

**Comment by madman163** [comment]
Creating network "jms_net" with driver "bridge"

升级3.8.1照旧,bridge网络里外网正常访问的容器换成jms_net网络就不能访问,切回bridge网络又正常,最后解决方案 所有jumpserver相关容器加入bridge网络,可以访问了

不懂什么鬼问题  启动也不报错

**Comment by wojiushixiaobai** [comment]
大概率是在 `jumpserver` 启动后修改了 `iptables` 或者 `firewalld` 导致 `docker` 相关 `iptables` 规则丢失
解决方法是关闭 `jumpserver` 组件后，完整的重启一次 `docker` 即可

或者重启服务器一次也可以。

每次修改 iptables 和 firewalld 都需要重启 docker
