### ISSUE TITLE
跳Windows连接错误

### ISSUE THREAD

**Issue by zhangxiongfu** [jumpserver/jumpserver#1196]
[简述你的问题]

##### 使用版本
Jumpserver版本1.0.0

##### 问题复现步骤

![g x3802n1w_1 fqeos v x](https://user-images.githubusercontent.com/37925854/38660967-cb564294-3e61-11e8-9672-4b824fa461b6.png)

[注:] 完成后请关闭 issue

**Comment by zhangxiongfu** [comment]
是我windows上电脑配置的问题还是server端中要配置？求指导

**Comment by wojiushixiaobai** [comment]
# 正常运行后到Jumpserver 会话管理-终端管理 里面接受gua注册
   $ docker restart jms_guacamole  # 如果接受注册后显示不在线，重启gua就好了
如果任然没有解决，参考faq第4条重新注册
http://docs.jumpserver.org/zh/docs/faq.html

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
