### ISSUE TITLE
[Feature] 工单申请快速查找资产

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#11966]
**请描述您的需求或者改进建议.**
目前工单申请的时候，显示的是一个下拉列表而且列表只是展示10条数据，然后通过模糊搜索去查找。但是在实际应用中有很多人是不知道资产的IP或者命名规则的。
那么针对于这个情况，是不是可以在工单的某一个地方可以加一个设置，是使用下拉列表框还是资产树的形式。这样子如果客户是怕资产泄漏的话，就可以选择下拉列表的方式，如果是有些客户希望能快速查找的话，就可以通过资产树的形式去选择。资产树就根据他选择的组织来展示组织的下的资产树。
希望采纳建议～

**Comment by BaiJiangJie** [comment]
暂时不考虑。

如果申请人，可以通过资产树来选择资产的话，那是会有信息泄漏的问题。

**Comment by wxcen** [comment]
所以是说建议加一个配置， 你默认是下拉列表，如果需要资产树的话，就配置成资产树不？那配置资产树的话，是不是可以加一行风险提示。
或者实在不行的话，有没有好的考虑让不知道资产IP和命名的情况下，也能快速找到需要申请的资产。减少客户的沟通成本。

**Comment by BaiJiangJie** [comment]
不知道资产 IP 和 名称又要搜索资产，那其他字段也不合适啊。

如果用户不知道资产 IP，那么全部给他他知道要申请哪台吗？
