### ISSUE TITLE
[Question] v3.7.2 sftp 下载文件的请求等待是什么机制？

### ISSUE THREAD

**Issue by zlcxk** [jumpserver/jumpserver#11972]
![image](https://github.com/jumpserver/jumpserver/assets/41320143/cd604e7a-da2c-4fc1-8e2b-5423711daae2)
在v3.7.2版本通过sftp连接服务器后下载大文件存在如图示的请求等待，类似预加载，5g文件等待1分钟，12g文件等待3分钟。
升级之前的版本是2.24.2，不存在此现象。

**Comment by LeeEirc** [comment]
不影响，下载完成之后会有回调结束这个弹框。
