### ISSUE TITLE
[Question] Can disable limit the number of user login failures?

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11979]
Hi,

I configure auth with LDAP, so account will be blocked after 5 times login fail.
But Jumpserver also has account blocking function, it takes more time to check and unblock accounts on LDAP or Jumpserver.

I only can bypass with increase limit the number of user login failures from 7 to 99999.
How can I do to disable limit the number of user login failures?

Thank

**Comment by BaiJiangJie** [comment]
Turning this option off is currently not supported.
