### ISSUE TITLE
[Question] 从v3.4.3升级到v3.7.2版本一直卡住

### ISSUE THREAD

**Issue by liunancun** [jumpserver/jumpserver#11974]
![image](https://github.com/jumpserver/jumpserver/assets/12378933/af9dd59b-315c-4fed-bad0-2881898a8d53)

我的是Docker环境下进行版本升级，一直卡在[DEBU] syncing proxy contexts, version是什么问题？

docker-compose.xml文件
jumpserver:
  image: jumpserver/jms_all:v3.4.3
  container_name: jumpserver
  privileged: true
  environment:
    - SECRET_KEY=xxx
    - BOOTSTRAP_TOKEN=xxx
    - LOG_LEVEL=ERROR
    - DB_HOST=10.40.2.xx
    - DB_PORT=3306
    - DB_USER=jumpserver
    - DB_PASSWORD=xxx
    - DB_NAME=jumpserver
    - REDIS_HOST=10.40.2.xx
    - REDIS_PORT=6379
    - REDIS_PASSWORD=xxx
  volumes:
    - /home/data/jumpserver/core:/opt/jumpserver/data
    - /home/data/jumpserver/koko:/opt/koko/data
    - /home/data/jumpserver/lion:/opt/lion/data
  ports:
    - 80:80
    - 2222:2222

升级命令：
docker run --name jms_all --rm -v /home/data/jumpserver/core:/opt/jumpserver/data -v /home/data/jumpserver/koko:/opt/koko/data -v /home/data/jumpserver/lion:/opt/lion/data -e SECRET_KEY=xxx -e BOOTSTRAP_TOKEN=xxx -e LOG_LEVEL=ERROR -e DB_HOST=10.40.2.xx -e DB_PORT=3306 -e DB_USER=jumpserver -e DB_PASSWORD=xxx -e DB_NAME=jumpserver -e REDIS_HOST=10.40.2.xx -e REDIS_PORT=6379 -e REDIS_PASSWORD=xxx jumpserver/jms_all:v3.7.2 upgrade

**Comment by wojiushixiaobai** [comment]
直接访问你的 web 页面不就知道了吗，升级完成后会自动启动

**Comment by liunancun** [comment]
docker run --name jms_all --rm -v /home/data/jumpserver/core:/opt/jumpserver/data -v /home/data/jumpserver/koko:/opt/koko/data -v /home/data/jumpserver/lion:/opt/lion/data -e SECRET_KEY=xxx -e BOOTSTRAP_TOKEN=xxx -e LOG_LEVEL=ERROR -e DB_HOST=10.40.2.xx -e DB_PORT=3306 -e DB_USER=jumpserver -e DB_PASSWORD=xxx -e DB_NAME=jumpserver -e REDIS_HOST=10.40.2.xx -e REDIS_PORT=6379 -e REDIS_PASSWORD=xxx jumpserver/jms_all:v3.7.2 upgrade
我执行的这个升级命令不会自动启动吧，要用docker-compose命令才能启动，我是按照[hub.docker.com](https://hub.docker.com/r/jumpserver/jms_all)上的升级步骤操作的

**Comment by wojiushixiaobai** [comment]
去掉 upgrade 命令，直接启动就像

**Comment by liunancun** [comment]
优秀，这种升级方式比之前的好很多 @wojiushixiaobai 
建议改下[hub.docker.com](https://hub.docker.com/r/jumpserver/jms_all)上面的升级步骤
