### ISSUE TITLE
希望可以修改上传目录，或者不限制上传的具体目录

### ISSUE THREAD

**Issue by lkkljjknkui** [jumpserver/jumpserver#11988]
tmp在系统盘中，系统盘太小，无法传输大文件，希望可以支持切换目录上传文件

**Comment by jym503558564** [comment]
自定义平台，添加sftp协议，可以修改上传目录。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/494217a6-8711-4338-851a-af9e28b07e85)

**Comment by lkkljjknkui** [comment]
可以截一下这个页面在哪里吗，没找到耶

檐下风铃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 上午9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] 希望可以修改上传目录，或者不限制上传的具体目录 (Issue #11988)





 
自定义平台，添加sftp协议，可以修改上传目录。

**Comment by BaiJiangJie** [comment]
见上图。
