### ISSUE TITLE
虚拟账号怎么用，我想在连接Win的时候再输入密码怎么设置[Question] 

### ISSUE THREAD

**Issue by liunancun** [jumpserver/jumpserver#11989]
![image](https://github.com/jumpserver/jumpserver/assets/12378933/6ecadd06-778c-4130-b1e2-016385509e92)

这个虚拟账号怎么用的

![image](https://github.com/jumpserver/jumpserver/assets/12378933/9a2f4514-2662-4593-a98d-7488b0f2621c)
我创建了一个密码为空的账号，想登录的时候再输入密码，但输入密码之后登录报错

![image](https://github.com/jumpserver/jumpserver/assets/12378933/f8db3de7-7666-435e-99ee-de78b61b706f)

![image](https://github.com/jumpserver/jumpserver/assets/12378933/943758d0-6d70-4494-a06a-56cff33ac223)

**Comment by BaiJiangJie** [comment]
虚拟账号是在授权的时候使用的。

输入密码后登录报错，应该是你输入的密码不正确。
