### ISSUE TITLE
超级管理员在作业中心的快捷命令中执行命令，不会被记录到命令记录当中

### ISSUE THREAD

**Issue by lkkljjknkui** [jumpserver/jumpserver#11987]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/115009241/a21f7f55-8402-4759-998a-0e807d75ecc4)
![image](https://github.com/jumpserver/jumpserver/assets/115009241/eb32ab58-d518-4028-820f-0a61f3e7a8a3)

2.
3.

**Comment by BaiJiangJie** [comment]
在两个地方会有记录：

1. 在 “工作台-作业中心-执行历史” 中
2. 在“审计台-日志审计-作业日志”中

在会话审计的命令记录里没有，这里只记录连接成功的会话中执行的命令。
