### ISSUE TITLE
[Feature] 关于rdp资产的快捷键操作

### ISSUE THREAD

**Issue by dongxiaoqing** [jumpserver/jumpserver#11984]
通过webgui连接rdp资产操作时的快捷键操作真的是痛苦的体验。
举例：想要在在资产中切换输入法，alt-tab切换窗口，会发送到local桌面
真的是非常痛苦的体验。
不知道是我操作的问题还是产品本身没有考虑到。

建议：希望可以设定为在全屏模式下，所有键盘操作都发送到rdp资产主机。

谢谢

**Comment by BaiJiangJie** [comment]
我测试是可以的。

![Oct-27-2023 14-42-40](https://github.com/jumpserver/jumpserver/assets/32935519/98662f48-e3b5-47e0-a6b4-29dc8b51f6a3)

**Comment by BaiJiangJie** [comment]
![Oct-27-2023 14-44-38](https://github.com/jumpserver/jumpserver/assets/32935519/0b636299-77f8-444b-be21-69c3aece76f7)
