### ISSUE TITLE
[Question] Permissions for system operators but no auditing

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#11995]
Hello,

I want have role can manager Jumpserver such as: add/edit/delete user, asset, group, node,... on Jumpserver, but can't access to audit.
Now, I only see 3 role in Jumpserver: SystemAdmin, SystemAuditor and User. No have role can satisfy the above condition.

How can I do to modify or add new role as requested above?
Thank

**Comment by BaiJiangJie** [comment]
Thank you for your question.

Viewing and customizing roles is an Enterprise Edition feature. The community version does not support viewing and modification, and only built-in roles can be used.

If there is a custom role you would like to use, please contact us for business purchase or trial the enterprise version.

`support@fit2cloud.com`
