### ISSUE TITLE
源码安装的jumpserver3.8.0版本组件健康经常离线

### ISSUE THREAD

**Issue by liangmartin** [jumpserver/jumpserver#11990]
![image](https://github.com/jumpserver/jumpserver/assets/66021709/4b63e24b-63e3-4e6c-9399-3a66c4256c27)
我在使用源码安装3.8.1版本健康经常离线，然后邮件一直在提醒离线，我看log并没有执行” - "GET /api/health/ HTTP/1.1" 200“ 这一条；而我在docker启动的jumpserver却一直有这一条

**Comment by JeongHyeokLee** [comment]
我记得2.20版本源码的时候就这样 之后我就升级成Docker了

**Comment by liangmartin** [comment]
> 我记得2.20版本源码的时候就这样 之后我就升级成Docker了

确实，我使用docker就不会有这种问题。

**Comment by BaiJiangJie** [comment]
嗯，长期使用，建议使用离线包部署。

**Comment by liangmartin** [comment]
> 嗯，长期使用，建议使用离线包部署。

老哥指的是用还是用docker的包吗，我使用jumpserver官网的源码安装的
