### ISSUE TITLE
[Question] jumpserver3.8.1安装后https登陆不了

### ISSUE THREAD

**Issue by SoHuDrgon** [jumpserver/jumpserver#11997]
域名访问输入密码后提示
<img width="1209" alt="截屏2023-10-31 11 23 23" src="https://github.com/jumpserver/jumpserver/assets/11847516/697bdedc-93d6-4089-ab3d-5a6baa4dfa30">

情况如下：
容器化安装了jumpserver
通过haproxy将jumpserver的web端80访问映射成域名了
配置了DOMAINS
DOMAINS="jumpserver.xxxxx.com:4443,192.168.11.230:80"

jms_lion日志报错：
2023-10-31 11:21:12 main main.go [ERROR] 校验 access key failed: connect failed:Get "http://core:8080/api/v1/users/profile/": dial tcp 192.168.250.7:8080: connect: connection refused
看情况是本地网络访问不了docker的网络
请问你们是怎么解决的？

**Comment by wojiushixiaobai** [comment]
尝试重启 docker
```
./jmsctl.sh down
systemctl stop docker docker.socket
systemctl restart docker
```

如果依旧无效，检查下列表单：
- [ ] 不使用 haproxy 是否正常

如果存在上述问题，请将 haroxy 的配置截图上传

**Comment by SoHuDrgon** [comment]
不使用haproxy是正常的，我的haproxy配置上面有连接数和带宽限制，我改大一些就好了，谢谢你！
