### ISSUE TITLE
[Bug] 账号自动禁用不生效

### ISSUE THREAD

**Issue by DaddyXz** [jumpserver/jumpserver#11999]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**

**Bug 描述**
配置账号不活跃30天自动禁用，但是未生效

**Bug 重现步骤(有截图更好)**
1. 
![image](https://github.com/jumpserver/jumpserver/assets/99782519/511fd2f2-63cd-4b57-bc0e-944f151a9c0f)

2.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/a4e16f66-1413-4ee9-bc05-6ccb4bf3675d)

3.超过30天未登录，账号未禁用，且可以正常登录

**Comment by BaiJiangJie** [comment]
最新版本修复了，请升级到最新版本解决。
