### ISSUE TITLE
建议使用pyte进行命令数据的解析.

### ISSUE THREAD

**Issue by wcc526** [jumpserver/jumpserver#120]
pyte
https://github.com/selectel/pyte

这两个项目都是使用该库进行终端数据解析的。
http://github.com/ajenti/ajenti
https://github.com/jonathanslenders/pymux

def deal_command(self, str_r):
def remove_control_char:
def deal_backspace:
def remove_obstruct_char:
这几个函数

**Comment by ibuler** [comment]
感谢反馈，我们学习一下

**Comment by yumaojun03** [comment]
pyte 不错。解析的比较全面，优雅。

**Comment by wcc526** [comment]
https://github.com/wcc526/bastion-ssh

可以参考我这个项目代码 @ibuler  @yumaojun03 

我重构了 jumpserver/connect.py 这部分代码。我现在审计内容现在暂时是输出在~/bashion_ssh.log.

建议不要放在connect.py的代码放在同一个文件下，代码量比较大，不方便代码阅读。

**Comment by kelianchun** [comment]
@wcc526 我看了下你的代码，我发现你是把所有的屏幕输出写入日志，而我们所做的是将用户的命令解析出来，最后获取的是用户的命令

**Comment by wcc526** [comment]
@kelianchun 我代码又改了下，增加了用户的命令的解析的代码，暂时是输出到文件。

见
https://github.com/wcc526/bastion-ssh/blob/master/bastion_ssh/plugins/audit/main.py

测试的话以master分支为主，下载代码本地安装

现在这部分命令解析部分是和jumpserver差不多了。原先 jumpserver 的dealcommand的解析逻辑有点复杂，不好理解。

**Comment by kelianchun** [comment]
@wcc526 感谢，现在已经使用pyte
