### ISSUE TITLE
[Bug] 源码安装启动组件离线似乎与运行时是否挂后台有关

### ISSUE THREAD

**Issue by liangmartin** [jumpserver/jumpserver#12008]
JumpServer 版本 v3.8.0

**浏览器版本**

**Bug 描述**
源码安装启动 在jms 中management.call_command(action, *services, *start_args)
![image](https://github.com/jumpserver/jumpserver/assets/66021709/9b10c894-1fb9-4a33-8a89-5042304e0630)
management.call_command(action, *services, *start_args)

**Bug 重现步骤(有截图更好)**
1.当使用./jms start all 不挂后台的时候组件是不会离线的
![image](https://github.com/jumpserver/jumpserver/assets/66021709/8ea22ffd-a5dc-439a-abcf-6ffe882fcc01)
2.当使用./jms start all -d 挂后台的时候 组件就离线了
![image](https://github.com/jumpserver/jumpserver/assets/66021709/8968806a-78af-44b0-a569-acacc9a6df76)

**Comment by BaiJiangJie** [comment]
core 和 celery 组件是，随着 core 服务的 gunicorn 进程和 celery 进程启动的。类似于两个虚拟组件，主要用来监控 core 服务所在主机的一些负载参数。因为 core 服务和其他组件（如：koko）可能不在同一台服务器上运行。
