### ISSUE TITLE
[Question] 创建Web资产自动代填如何实现HTTP Basic认证

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#12006]
由于目标系统的原因，无法支持http://username:password@domain/这种认证的方式
允许的方式只有在HTTP header中添加"Authorization: Basic xxxxx"
这种方式要如何实现

**Comment by BaiJiangJie** [comment]
"Authorization: Basic xxxxx" 

这种方式应该指的是通过 API 方式访问的认证吧？

**Comment by BaiJiangJie** [comment]
Web 资产访问的时候，都是通过页面上的用户名、密码窗口进行代填的，所以我觉得应该实现不了 Basic 方式的认证。

**Comment by mjwtc0722** [comment]
> Web 资产访问的时候，都是通过页面上的用户名、密码窗口进行代填的，所以我觉得应该实现不了 Basic 方式的认证。

后续会支持这个功能吗？

**Comment by BaiJiangJie** [comment]
你用本地浏览器登录，是怎么实现 Basic 方式认证的？

**Comment by mjwtc0722** [comment]
> 你用本地浏览器登录，是怎么实现 Basic 方式认证的？

使用nginx来做的
auth_basic "Authenticate";
auth_basic_user_file /etc/nginx/encrypt_pass;

**Comment by ibuler** [comment]
不打算支持，请尝试添加一个新的页面，输入后，自动跳转
