### ISSUE TITLE
堡垒机跳转界面，上下键查询历史命令

### ISSUE THREAD

**Issue by chenrongfang** [jumpserver/jumpserver#1200]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1]
<h3>Jumpserver版本 1.0</h3>
##### 问题复现步骤
1. <h3>上下键找历史记录的功能在哪设置啊</h3>

##### 具体表现[截图可能会更好些,最好能截全]
https://user-images.githubusercontent.com/36058840/38719353-22dc3f7e-3f24-11e8-908f-7e3df5e90f48.png
##### 其他
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时不支持呢，等待优化

**Comment by jym503558564** [comment]
已支持，如有其它问题可重新打开issues
