### ISSUE TITLE
[Feature]  请问下对k8s的管理操作有什么支持计划？ 

### ISSUE THREAD

**Issue by tanguofu** [jumpserver/jumpserver#12000]
**请描述您的需求或者改进建议.**
期望能通过k8s， 在对应的集群下的树，可以进行基本的k8s操作，比如
1. 节点的查看
2. pod对应yaml的查看
3. 其他k8s 基本的configmap secret 等的资源的yaml 查看 和编辑

**Comment by BaiJiangJie** [comment]
可以右击集群，连进去后进行操作。

<img width="1695" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d54f4467-2f94-47a2-8cd9-514a845135cc">

**Comment by tanguofu** [comment]
嗯嗯 通过kubectl 是可以的， 那么这里有其他通过ui 获取对应yaml的 计划么
