### ISSUE TITLE
SSH 协议连接 Linux 资产增加复制粘贴的权限控制

### ISSUE THREAD

**Issue by jializhu** [jumpserver/jumpserver#12015]
需求描述：目前复制粘贴的权限控制只能限制 RDP 和 VNC 协议，希望能限制 SSH 协议。
理由：对大部分用户来说，用 SSH 协议来连接 Linux 机器和网络设备等资产是堡垒机最重要的功能。而堡垒机这边的权限控制是区别于xshell 和 putty 等工具的最终要的功能之一，所以这个需求是有价值；

还请再评估看看。感谢~

**Comment by ibuler** [comment]
不了解友商怎么实现的，xshell, putty 是文本的客户端，结果输出出来了，无法控制客户端自己的行为

**Comment by jializhu** [comment]
收到，谢谢
