### ISSUE TITLE
[Feature] web终端的标签页没办法快速切换，希望可以增加个快捷键

### ISSUE THREAD

**Issue by FLSZ** [jumpserver/jumpserver#12017]
比如说我在web终端，打开了5个linux的连接，我没办法直接用快捷键，快速切换不同的标签页，而是必须使用鼠标点击。

像xshell  就可以使用 alt  +1  ，alt  +2  ，alt +3  这种方式切换，希望可以增加，让使用体验有所提升
![1698905227506](https://github.com/jumpserver/jumpserver/assets/98043316/99529238-d7dd-4395-8ea8-98ae29d02313)

**Comment by BaiJiangJie** [comment]
可以考虑支持。

**Comment by BaiJiangJie** [comment]
预计 v3.10 支持。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
