### ISSUE TITLE
[Question] 主机指纹重复的问题

### ISSUE THREAD

**Issue by fladdy** [jumpserver/jumpserver#12016]
使用同一个自定义镜像创建的云主机，ssh主机指纹都是一样的，但IP不一样，添加资产后测试连接性报错
fatal: [XXX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nxxx@x.x.x.x: Permission denied (publickey,password).", "unreachable": true}
这种问题如果是在操作系统下删除~/.ssh/known_hosts里对应条目就可以解决，但jumpserver里如何处理呢？

**Comment by BaiJiangJie** [comment]
正常不用处理，保证 IP 和账号的 用户名和SSH 密钥信息正确就可以。

**Comment by fladdy** [comment]
我只是举个例子，jumpserver肯定不会在操作系统生成 know_hosts 文件，它的ssh客户端功能是由 koko 实现？
但现在就是不正常了，ssh认证信息确认是没问题的，koko是否和openssh一样会保存主机指纹？

**Comment by fladdy** [comment]
不好意思，应该是我这边的问题，重启资产后能正常连接了，原因不明。

**Comment by BaiJiangJie** [comment]
嗯，应该不是，测试可连接性，没有使用 KoKo 组件。
