### ISSUE TITLE
[Bug] 使用Web GUI方式连接 Windows 资产，当输入重复的汉字时有丢失的问题

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#12018]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**

**Bug 描述**

https://github.com/jumpserver/jumpserver/assets/104493699/b39f4706-15f9-491c-8925-17ef1a8c7c9c

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
使用本地的 微软远程应用功能连接一下试试。

**Comment by shimengqiao** [comment]
使用mstsc客户端没有这个问题

**Comment by BaiJiangJie** [comment]
应该是原生 Guacamole 就有问题，我们暂时处理不了。
