### ISSUE TITLE
[Bug] 会话记录和命令记录为空

### ISSUE THREAD

**Issue by JunXiaoRuo** [jumpserver/jumpserver#12014]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
Chrome
版本 118.0.5993.118（正式版本） （64 位）

**Bug 描述**
ubuntu20.04使用一键安装命令安装，后面通过堡垒机登录交换，在审计首页可以看见命令条数，但是会话记录和命令记录为空

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/47996900/964b6be2-c6c8-49ef-b3e2-32c88865678f)
![image](https://github.com/jumpserver/jumpserver/assets/47996900/89b0fb04-f9fc-4cfe-817c-0411eed7b9f0)
![image](https://github.com/jumpserver/jumpserver/assets/47996900/4a20b06d-8552-4762-ab57-aeaf5fca3331)

**Comment by BaiJiangJie** [comment]
调整一下这个时间，比如：11.05 号。

**Comment by JunXiaoRuo** [comment]
已经好了，谢谢
