### ISSUE TITLE
用户web界面没有已授权资产信息

### ISSUE THREAD

**Issue by faidev** [jumpserver/jumpserver#1201]
[简述你的问题]

##### 使用版本
Version 1.2.0-2  git commit id: 3ccb6637d7909551570535bbeb2e7ab8a2af75af

##### 问题复现步骤
1. 新建普通用户，授权已添加资产。
2. 在web界面查看没有已授权资产，web终端管理可以看见。

##### 具体表现[截图可能会更好些,最好能截全]
<img width="1315" alt="2018-04-15 11 18 35" src="https://user-images.githubusercontent.com/20348767/38780077-e2c143d0-4103-11e8-995a-2e121c4c39c5.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues
