### ISSUE TITLE
[Bug] 通过tmux命令，就进入 Tmux 窗口输入命令，命令审计命令缺失

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12029]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
版本 118.0.5993.118（正式版本） （64 位）

**Bug 描述**
通过tmux命令，就进入 Tmux 窗口输入命令，命令审计命令缺失

**Bug 重现步骤(有截图更好)**
1. 安装，yum install tmux -y 

2. tmux，进入窗口
![a7e19469f317a813f596359e4180264](https://github.com/jumpserver/jumpserver/assets/43403764/9549b924-b055-40cb-b51c-9eb3d6c57fcb)

3. 查看命令审计
![image](https://github.com/jumpserver/jumpserver/assets/43403764/e11d1b0b-3e1f-4b9f-89fe-8424f3fef908)

**Comment by BaiJiangJie** [comment]
是的，目前记录不了 tmux 后输入的命令。
