### ISSUE TITLE
[Question] /etc/environment 修改环境变量，其他用户如果是复用SSH连接的Session无法读取到最新的环境变量。

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#12022]
**请描述您的问题.**
如图新增一个环境变量
![image](https://github.com/jumpserver/jumpserver/assets/138869963/f98f7f96-9baf-4b1f-8eaa-66bdeb268d72)
其他用户如果未关闭所有连接，而是复用SSH连接的session，将无法读取到
![image](https://github.com/jumpserver/jumpserver/assets/138869963/4096e927-4334-47f7-8533-a346e0e0e488)
相反如果未显示复用连接，则可以正常读取新环境变量
![image](https://github.com/jumpserver/jumpserver/assets/138869963/4d7340b2-0e24-4d14-a0a1-eaafd33638ac)
是设计如此，还是可以优化下。如果修改了环境变量，其他用户无需关闭所有session 就可以查看到

**Comment by BaiJiangJie** [comment]
正常现象。

因为复用的连接不会重新加载环境变量。

未复用的连接会重新加载。

**Comment by Sanbobo1** [comment]
能否设置默认不复用呢？不然这边改环境变量的时候，用户都需要关闭连接，再重新连接才能加载

**Comment by Sanbobo1** [comment]
或者后续版本是否考虑下这个需求
