### ISSUE TITLE
[Bug] 在Application中，无法使用grep命令

### ISSUE THREAD

**Issue by jesse-zhangh** [jumpserver/jumpserver#12020]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.20

**浏览器版本**
chrome Version 118.0.5993.118

**Bug 描述**
访问Application中应用，无法使用grep命令

**Bug 重现步骤(有截图更好)**
1.访问某个资源并登录
2.使用grep，提示被禁用
![image](https://github.com/jumpserver/jumpserver/assets/87465352/747d057c-c7b2-4bbb-8cad-b024917b9d03)

**Comment by BaiJiangJie** [comment]
是的，目前是禁用的。

如果想使用，可以到 koko 容器里修改一下命令的权限。

# k8s 集群连接需要的命令
chmod 755 `which grep`
