### ISSUE TITLE
jumpserver可以只推送一台服务器的系统用户吗

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1202]
[简述你的问题]

##### 使用版本
[Version 1.0.0-2 GPLv2.]

##### 问题复现步骤
请问添加完资产以后，可以手动只推送指定服务器的系统用户吗？现在添加一台服务器就得推送一遍所有服务器的系统用户，耗大量CPU资源和负载

**Comment by wojiushixiaobai** [comment]
请更新到1.2.0，新版本已经支持对单用户和单资产授权

**Comment by qianghong000** [comment]
jumpserver可以只推送一台服务器的系统用户吗 。升级到新版本是可以对单用户和资产授权了。但还是无法对单台服务器推送系统用户

**Comment by BaiJiangJie** [comment]
新版本已支持，请使用最新版本，如果有问题请重新打开Issues
