### ISSUE TITLE
[Question] docker部署的jumpserver断电后重启访问 API 报错 

### ISSUE THREAD

**Issue by Lelylsj** [jumpserver/jumpserver#12026]
**请描述您的问题.** docker部署的jumpserver断电后重启报错   023-11-02 14:39:04 main main.go [ERROR] 校验 access key failed: connect failed:Get "http://core:8080/api/v1/users/profile/": dial tcp 192.168.250.3:8080: connect: connection refused

**Comment by BaiJiangJie** [comment]
docker 和 JumpServer 服务全部重启一下呢？

**Comment by BaiJiangJie** [comment]
如果还有问题，请 Reopen。
