### ISSUE TITLE
[Bug]配置mongo连接不上，mongo版本4.4

### ISSUE THREAD

**Issue by MrYangyt** [jumpserver/jumpserver#12028]
**JumpServer 版本3.72**

**浏览器版本**

**Bug 描述**
配置mongo无法连接成功，报错如下，mongo版本4.4，

**Bug 重现步骤(有截图更好)**
<img width="1536" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/9cee4c6b-838a-4dd5-a2a9-30957300639c">
<img width="900" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/fbd1cff2-a899-4619-820c-96b3c9b0c875">
<img width="1119" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/8f6210ad-0770-4341-97c3-6cba6fb34106">

**Comment by BaiJiangJie** [comment]
最新的 v3.10 版本连接正常吗？

**Comment by BaiJiangJie** [comment]
升级到最新版本使用。

**Comment by MrYangyt** [comment]
测试最新版本还是报错，报错如下
<img width="1000" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32567408/b08f079c-f803-44df-8e4b-3c1be174590c">
和3.7.2一样的报错
