### ISSUE TITLE
[Bug] 关于v3.8.0连接windows server 2008 花屏 的问题。

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#12035]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
mirosoft edge及其他chrome内核的浏览器。

**Bug 描述**
连接windows server 2008资源的时候，只要打开应用程序画面就直接变黑。

**Bug 重现步骤(有截图更好)**
尝试打开画图工具或者其他应用程序。

![image](https://github.com/jumpserver/jumpserver/assets/51370399/61635ce6-878a-49a0-92e4-504c4d97886b)

经测试，v2版本不存在该问题。

**Comment by jym503558564** [comment]
关闭浏览器硬件加速后，再测试一下

**Comment by vzrs** [comment]
感谢，正常了。不过希望之后还是修复一下吧。

**Comment by BaiJiangJie** [comment]
如果关闭浏览器硬件加速。

参考：https://www.sysgeek.cn/chrome-hardware-acceleration/
