### ISSUE TITLE
[Bug] chen组建问题

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#12039]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.1

**浏览器版本**
Edge 119

**Bug 描述**
chen组建好像有些小bug不清楚到底是哪个组建的bug，使用的mysql数据库，在添加资产里 默认数据库选项为非* 也能正常的添加资产，但是使用chen在连接数据库后查询页面就会一直转圈，同事chen的日志里会有报错“java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "currentContext" is null” 加上默认数据库后报错消失

**Bug 重现步骤(有截图更好)**
1.添加数据库资产（mysql）不填写默认数据库
2.打开mysql的web GUI 默认查询页面不断转圈，日志报错
<img width="1220" alt="image" src="https://github.com/jumpserver/jumpserver/assets/81400245/4c9a25c0-157c-4774-8bf0-fad5b830ca51">

3.添加默认数据库，访问正常

**Comment by BaiJiangJie** [comment]
预计 v3.8.2 和 v3.9 上都会修复。请关注新版本发布。

**Comment by jym503558564** [comment]
已修复，请升级进行测试。3.8.2 和 v3.9.1
