### ISSUE TITLE
[Question] V3.7.1版本 频繁连接Jumpserver执行操作时断开连接，已复现三次 并抓包

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#12031]
**请描述您的问题.**
一位同学使用finalshell连接jumpserver服务器，总是频繁断开连接
![img_v2_c229a24c-3d67-4b2d-87b9-3604e1c4af9g](https://github.com/jumpserver/jumpserver/assets/85990572/b3353ecd-fab8-4371-8770-c92957131a48)
![img_v2_e0e85aa2-b676-439e-9770-392ec4ccddeg](https://github.com/jumpserver/jumpserver/assets/85990572/a6fa6db8-55f3-45f9-a6be-ba7a0d78543b)
而且不是空闲超时那种和某台服务器断开连接(可继续选择机器) 是和ssh的jumpserver服务断开连接(无法选择机器)
抓包后发现：12：07-12:08
<img width="955" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/24411e6d-8544-49ad-92b1-f099a18cb307">
是jumpserver主动对所连接服务器发起断开请求？？？
这是为什么 谢谢回答

**Comment by BaiJiangJie** [comment]
这要看看 KoKo 组件的日志了。

**Comment by charnet1019** [comment]
同样的版本也遇到相同的问题
[koko.log](https://github.com/jumpserver/jumpserver/files/13290893/koko.log)

**Comment by xiaoxiongxyy** [comment]
> 这要看看 KoKo 组件的日志了。

2023-11-03 12:07:48 [ERRO] Session[65e358e7-eed6-4d04-8132-e916df7b2d64] user read err: io: read/write on closed pipe
抓包时间点的准确日志就是这一条 这个代表了什么会发起断开呀？为什么会出现这个错误？

**Comment by xiaoxiongxyy** [comment]
> 这要看看 KoKo 组件的日志了。

又有一位同学反映使用finalshell后 上传文件报错 但是在web端 可以正常上传成功 查看koko日志发现
![image](https://github.com/jumpserver/jumpserver/assets/85990572/903c6fa8-a11c-44dd-8be9-c0073c636a75)
好像还是类似的错误
是不是v3.7.1版本对finalshell的适配性不行呀？就这个终端工具出现问题 麻烦排查一下。。。

**Comment by BaiJiangJie** [comment]
是通过什么方式连接的？

Web 页面拉起客户端工具，还是直接 SSH 登录的？

**Comment by xiaoxiongxyy** [comment]
> 是通过什么方式连接的？
> 
> Web 页面拉起客户端工具，还是直接 SSH 登录的？

通过finalshell直接ssh上去的

**Comment by BaiJiangJie** [comment]
只有 finalshell 有问题吗？其他工具会不会出现同样的问题？

**Comment by xiaoxiongxyy** [comment]
> 只有 finalshell 有问题吗？其他工具会不会出现同样的问题？

没有 只有这个fianlshell终端反映问题

**Comment by khy2021** [comment]
Finalshell客户端带有监控功能，会在登录的主机上高频次执行shell命令，可能导致连接问题。

**Comment by LeeEirc** [comment]
如果 finalshell 连接 koko 频繁建立 ssh 连接就会出现此类日志，属于正常现象。
