### ISSUE TITLE
[Feature] 云同步支持更新策略中的动作

### ISSUE THREAD

**Issue by limin-fit2** [jumpserver/jumpserver#12037]
**请描述您的需求或者改进建议.**
在设置云同步策略分组时候，把A开头的名称划分到开发组，B开头的名称划分到测试组，服务器内部网络资产调整，需要将开发组和测试组分组合并，但是更改策略分配无法生效（显示资产已存在），需要删除机器才会重新匹配新的策略，所以是否可以增加 “策略中的动作也会更新(节点、网域、平台、账号模板)” 
![image](https://github.com/jumpserver/jumpserver/assets/61964761/17e5120f-ee8d-4d8e-9f80-0c35b5c884b7)
![image](https://github.com/jumpserver/jumpserver/assets/61964761/6a87156b-4e76-4f95-993b-03bf18b7be99)

**Comment by BaiJiangJie** [comment]
可以考虑，预计 v3.10 版本。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
