### ISSUE TITLE
通过RDP重复连接3次以上Windows后报连接异常错误[Bug] 

### ISSUE THREAD

**Issue by liunancun** [jumpserver/jumpserver#12034]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
Google Chrome 119.0.6045.105

**Bug 描述**
通过RDP重复连接3次以上Windows后报连接异常错误
无法连接到远程桌面服务器（网络不可达 | 安全策略错误）
过很长一段时间，几天之后又可以连接，然后再重复连接、断开3次以上，第4次又会报这个错误

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12378933/bb54d066-414c-458e-85ee-9c128da0bcd2)

**Comment by liunancun** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/12378933/c9bbafc4-543f-4ae3-a7d9-9c57c1eeafe3)

这是连接失败时控制台打印的日志

**Comment by wojiushixiaobai** [comment]
应该是你的安全策略或者 WAF 拦截了请求，检查下。
从你的描述来看，问题应该不是 JumpServer 本身的问题
