### ISSUE TITLE
[Bug] 会话记录不存在

### ISSUE THREAD

**Issue by DaddyXz** [jumpserver/jumpserver#12030]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**
117.0.5938.89

**Bug 描述**
回放会话记录，提示不存在

**Bug 重现步骤(有截图更好)**

两个问题，第一个就是存在部分无法选中回放，第二个就是可以回放的提示录像不存在

1.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/58316586-c19e-47ee-b81d-7669054ce243)

2.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/c964f04a-bdb7-4912-be33-635170a03036)

3.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/f549e9c1-039f-4d82-81e4-5745774de810)

**Comment by BaiJiangJie** [comment]
可能是录像没有上传成功。

看看 KoKo 的日志。

**Comment by BaiJiangJie** [comment]
过滤一下 replay 关键词。

**Comment by BaiJiangJie** [comment]
那原因可能就不好定位了。建议升级到最新版本使用。

新版本中如果有失败的录像文件，可以直接从列表中看到失败的原因。（做了一个小优化）
