### ISSUE TITLE
[Feature] 完成操作记录的信息

### ISSUE THREAD

**Issue by taoge1111** [jumpserver/jumpserver#12048]
将操作记录的日志改成文字显示，现在这样可读性太差
然后操作记录查看授权规则，不显示对那些资产那些用户做了怎么样的授权规则
![Snipaste_2023-11-07_11-27-07](https://github.com/jumpserver/jumpserver/assets/119826490/124284e1-8053-43eb-ad71-60c043292340)

希望能像之前v2版本这样显示直观一点
![Snipaste_2023-11-07_11-24-04](https://github.com/jumpserver/jumpserver/assets/119826490/228726fe-9d6b-4658-858e-31cce3fa6c9f)

**Comment by BaiJiangJie** [comment]
我测试的情况是，创建的时候，一些用户、用户组、资产、节点，信息的增加没有记录在操作日志中；动作，显示63，应该显示所有权限的名称。

更新授权规则，删除一些用户的时候，显示的不太好，比如有 A、B 两个用户，删除A，操作日志显示，变更前 A，变更后 B。（应该是变更前 A、B，变更后 B）。

还有一些情况，在进行优化的时候，多考虑一下。

**Comment by BaiJiangJie** [comment]
v3.10 已优化。
