### ISSUE TITLE
[Question] JumpServer V2升级到V3以后，账号的问题

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#12045]
**请描述您的问题.**
原来v2版本分配了很多的策略规则，目前升级到v3.8.1。有些机器是密码是对的，有些机器密码不对。而且没有什么规律，同一个节点里面的机器，同一组密码。也有这个问题。

目前打算采用账号模板的方式将所有机器都添加到新的账号模板里面的账号。但是这样因为我们账号和资产的数量比较多，工作量比较多。
请问有没有什么其它好的方案可以解决这个问题？

另外问一下，
1、咱们目前v2升级到V3的过程中，一般怎么解决账号这块的问题。
2、是否可以通过你Ansible测试一下所有资产哪些已经连不上了，哪里登录失败。

谢谢。
![搜狗截图20231107110020](https://github.com/jumpserver/jumpserver/assets/11976391/caf49364-f72f-41d3-972b-777e0a0e3c6f)

**Comment by BaiJiangJie** [comment]
可以啊，建议直接在账号列表页面导入所有账号信息。

**Comment by BaiJiangJie** [comment]
应该是你通过什么方式添加的，账号列表的账号，是按资产区分的，相当于每个资产下，分别都有2个账号，administrator和root。
