### ISSUE TITLE
[Bug] v3.8.1，操作记录显示不全

### ISSUE THREAD

**Issue by taoge1111** [jumpserver/jumpserver#12046]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
edge 119.0.2151.44

**Bug 描述**
更新授权规则，改了授权用户跟资产节点，实际上未记录变更内容

**Bug 重现步骤(有截图更好)**
1.正常创建授权规则
2.更改授权规则，改动用户和资产，操作记录里都没显示
![Snipaste_2023-11-07_11-01-45](https://github.com/jumpserver/jumpserver/assets/119826490/5ed1f4cb-31ae-4c3b-8522-2a87007bd4d7)

**Comment by BaiJiangJie** [comment]
授权规则改动，显示你是移除了资产，实际上你的操作是什么？

**Comment by BaiJiangJie** [comment]
统一记录到 https://github.com/jumpserver/jumpserver/issues/12048 中。

**Comment by taoge1111** [comment]
> 授权规则改动，显示你是移除了资产，实际上你的操作是什么？



> 授权规则改动，显示你是移除了资产，实际上你的操作是什么？

但是实际上我的用户也做了删除。添加操作，然后没显示
