### ISSUE TITLE
[Feature] 企业微信免登录完成审批

### ISSUE THREAD

**Issue by Xyuncheng** [jumpserver/jumpserver#12044]
**请描述您的需求或者改进建议.**
如果 JumpServer 和企业微信已经打通认证，作为企业微信的应用免密登录了，管理层在收到工单申请的时候，对应的审批操作能否也密码登录？

**Comment by O-Jiangweidong** [comment]
可以考虑优化下的

**Comment by BaiJiangJie** [comment]
已完成，请关注 v3.10.4 版本的发布。
