### ISSUE TITLE
[Question] v2.28升级v3.8.1，nginx ssl代理的配置问题。

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#12040]
上面有LB，443和80都是配置上LB上面的（证书都有）。
后端转到主Nginx的80端口，再转到JumpServer的80端口。
因为我只需要用JumpServer的80端口，所以修改lb_http_server.conf文件，将443的配置全部清掉。
访问是可以直接访问的，但总是跳转到https://ui/#这个页面。我看了之前有人也遇到过转ui这个问题，但是issue没有进一步解答。

我目前这个LB架构，如果直接原始的lb_http_server.conf文件，配置443及域名证书。一直跳无限301没办法访问。

**Comment by wojiushixiaobai** [comment]
将你配置文件中关于 https 部分的内容全部注释掉。
```sh
## /opt/jumpserver/config/config.txt

# HTTPS_PORT=443               # 对外 https 端口, 默认 443
# SERVER_NAME=www.domain.com   # 你的 https 域名
# SSL_CERTIFICATE=xxx.pem      # /opt/jumpserver/config/nginx/cert 目录下你的证书文件
# SSL_CERTIFICATE_KEY=xxx.key  # /opt/jumpserver/config/nginx/cert 目录下你的 key 文件
```
