### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dugangandy** [jumpserver/jumpserver#12049]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.2

**浏览器版本**
chrome  119.0.6045.105

**Bug 描述**
使用Web终端连接Linux资产，使用【客户端-> SSH客户端】方式连接报错。

老版本v3.5.4能正常使用。

**Bug 重现步骤(有截图更好)**
1. 使用Web终端连接Linux资产，使用【客户端-> SSH客户端】方式连接报错。
![ef94834fc2121608a709075b94010bd](https://github.com/jumpserver/jumpserver/assets/13115769/cb7033b2-375c-490c-b7e6-4b4eda320e0d)

2.mac平台报错如下：
![image](https://github.com/jumpserver/jumpserver/assets/13115769/196b3bde-7b7f-490a-b1d8-a446030fb3b6)

3.windows系统报错如下：
![4c2ae7c6941e12e7c88c292837f105d](https://github.com/jumpserver/jumpserver/assets/13115769/3d5b3814-cfb7-4f62-8ebb-a01c432c8447)

**Comment by dugangandy** [comment]
重新安装 v2.0.0版本的 jumpserver客户端，能正常使用。

**Comment by BaiJiangJie** [comment]
嗯，新版本要适配最新的客户端。

**Comment by dugangandy** [comment]
> 嗯，新版本要适配最新的客户端。

使用了老版本的jumpserver客户端v2.0.0解决的。 

v3.7.2 配套的jumpserver客户端v2.0.1 会有这个问题。
