### ISSUE TITLE
华为云虚拟机获取CPU核心数不准确

### ISSUE THREAD

**Issue by linux0x5c** [jumpserver/jumpserver#1205]
[简述你的问题]

##### 使用版本
1.2.0

##### 问题复现步骤
1. 更新硬件信息
2. CPU核心数1核的显示正常2核以及2核以上的都比实际系统显示核心数少一半
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
经测试，包括vmware、Xenserver都有这个现象。。

**Comment by ibuler** [comment]
欢迎PR，逻辑部分在这里 https://github.com/jumpserver/jumpserver/blob/master/apps/assets/tasks.py#L29
