### ISSUE TITLE
[Feature] Web GUI 能否配置高级选项，禁用自动补全

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12053]
**请描述您的需求或者改进建议.**
需求场景：数据库表上万张，用 Web GUI 连接时需要加载几分钟才能连接上

原因我猜测是 Web GUI 会先扫描库下的所有表，用于 SQL 自动补全

能否像 Web CLI 一样，在 Web GUI 也添加高级选项，可禁用自动补全
![image](https://github.com/jumpserver/jumpserver/assets/89765365/f24d4652-80f8-41f2-8163-c6ceebadacf8)

**Comment by BaiJiangJie** [comment]
嗯，可以考虑。v3.10

**Comment by hzhfit2cloud** [comment]
👍🏻
