### ISSUE TITLE
[Bug] 首页高危命令占比不显示问题

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#12051]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.1

**浏览器版本**
Chrome

**Bug 描述**
开通了高危命令，实际也触发了高危命令，但是在首页显示不出来高危命令占比。

**Bug 重现步骤(有截图更好)**
首页界面
<img width="629" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40848979/53b7a761-498b-476a-9c24-365fa8356013">
通过DE大屏展示的命令
![image](https://github.com/jumpserver/jumpserver/assets/40848979/1687bf51-36d3-49a7-985c-3d4ffb1b1daa)

**Comment by BaiJiangJie** [comment]
配置 es 存储了吗？

**Comment by BaiJiangJie** [comment]
<img width="1382" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/45a5d085-a841-4ac8-a77b-4a78c9df665c">

**Comment by BaiJiangJie** [comment]
查看下面 API 返回的 total_count_commands_danger 数量。

<img width="1632" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a5916f02-5c67-451a-b2cc-ba94a3ca6224">

查看当前组织的命令列表记录中高危命令的数量。

查看数据库中高危命令的数量。

**Comment by jym503558564** [comment]
@wxcen 该问题是否还存在？

**Comment by BaiJiangJie** [comment]
升级到最新版本，如果问题依旧，Reopen issue。
