### ISSUE TITLE
[Bug] 阿里云RDS for MySQL 资产测试可连接性错误

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#12056]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
Chrome

**Bug 描述**
阿里云RDS for MySQL 资产测试可连接性错误，WEB cli 和 WEB GUI 都能正常连接。
RDS for MySQL 5.7，基础版，高权限账户。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/40846859/ac146f50-f78e-4f7a-935e-24447821db17)

2.
3.

**Comment by ttkanni** [comment]
@BaiJiangJie 我在3.7.2这个版本也遇到了这个问题，升级3.8.2问题依旧，在【控制台】资产测试可连接性会提示这个错误，在【工作台】连接资产却可以连接。在之前的版本没有这个问题。

阿里云的RDS for MySQL和自建MySQL有一个区别，连接地址是一个域名，而不是IP。

**Comment by jym503558564** [comment]
已复现，待修复

**Comment by jym503558564** [comment]
已修复，待3.9.0发布，在进行升级测试。

**Comment by windli2018** [comment]
没改完全。

**Comment by jym503558564** [comment]
v3.9.2已修复，并发布。请更新进行验证测试～

**Comment by windli2018** [comment]
> v3.9.2已修复，并发布。请更新进行验证测试～

已修复 。👍
