### ISSUE TITLE
[Feature] 系统设置中支持设置资产默认自动登录

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [jumpserver/jumpserver#12052]
**请描述您的需求或者改进建议.**

在系统设置里增加是否开启资产自动登录的配置。
这种配置可以针对只有一个资产账号、一种连接方式的资产生效。
![image](https://github.com/jumpserver/jumpserver/assets/81545871/bed86a2a-173f-44e8-a3e3-a5452cef4652)

**Comment by BaiJiangJie** [comment]
暂时不考虑。

是的，自动登录的选项，只会锁定到当前的登录信息。
