### ISSUE TITLE
[Bug] 选择资产导出不符合预期（已解决）（附带问题：批量选中资产的数量来回切换节点后不准确）

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12060]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1、v3.6.6

**浏览器版本**
Chrome 119

**Bug 描述**
资产列表导出选中资产，实际导出列表中包含了其他未选中资产

**Bug 重现步骤(有截图更好)**
1.资产列表选择某个节点，勾选部分资产
![image](https://github.com/jumpserver/jumpserver/assets/95400700/e3ebe959-ee4b-41ef-9d29-1449b0445c0b)

2.导出选择“仅导出选择项”
![image](https://github.com/jumpserver/jumpserver/assets/95400700/f7eef962-b896-4d14-a9a5-4bee7ae515d0)

3.查看导出结果，比选择资产多出很多
<img width="872" alt="image" src="https://github.com/jumpserver/jumpserver/assets/95400700/2ba3b8b5-70e5-45f5-8803-ed9fbbd1130d">

**Comment by BaiJiangJie** [comment]
看一下批量处理的选中项有多少个？

<img width="1258" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/8b03373e-2a66-44fd-882f-f67fbbc7558a">

是支持多个节点下的资产批量选中，导出的。

**Comment by BaiJiangJie** [comment]
@huailei000 

批量选中的选中项数量，来回切换节点是，计算的不准确，处理一下。（容易复现）

**Comment by gerry-fit** [comment]
好的，谢谢
