### ISSUE TITLE
[Bug] Luna 页面经常弹出 “登录已过期，请重新登录” 的提示

### ISSUE THREAD

**Issue by snoopystarch** [jumpserver/jumpserver#12061]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.1

**浏览器版本**
chrome 版本 119.0.6045.106

**Bug 描述**
web终端内连接资产，经常出现登录已过期，请重新登录
![541bbd6364745912270ade325ab46efe](https://github.com/jumpserver/jumpserver/assets/63605243/04ab3693-980b-4e65-88eb-3c15ac660dae)

**Bug 重现步骤(有截图更好)**
1.打开web终端
2.选择任意资产，window/linux
3.连接几分钟后就会弹出”登陆已过期，请重新登录“

**Comment by BaiJiangJie** [comment]
看一下配置文件 config.txt 中 SESSION_COOKIE_AGE 的值，是不是太小了。

**Comment by BaiJiangJie** [comment]
弹窗的原因是你的浏览器用户会话过期了，需要重新登录一下就好了。

**Comment by snoopystarch** [comment]
> 弹窗的原因是您的浏览器用户已经过期，需要重新登录一下就好了。
经常刚登陆上没多久，打开一个web终端就会弹这个，点确定之后过一段时间又会弹


> 看一下配置文件config.txt中SESSION_COOKIE_AGE的值，是不是太小了。

默认配置，这条是注释掉的

**Comment by snoopystarch** [comment]
> 看一下配置文件config.txt中SESSION_COOKIE_AGE的值，是不是太小了。

SESSION_EXPIRE_AT_BROWSER_CLOSE=True

**Comment by BaiJiangJie** [comment]
那没问题，重新登录一下，还会经常弹出吗？

**Comment by snoopystarch** [comment]
> 那没问题，重新登录一下，还会经常弹出吗？

好像是每次浏览器不关闭，但是关掉jumpserver的页面，过一会再打开jumpserver时候就会出现这个问题，所有用户都是这个毛病

**Comment by BaiJiangJie** [comment]
尝试将 SESSION_EXPIRE_AT_BROWSER_CLOSE=True 修改为 False，看看是不是还会出现。

**Comment by snoopystarch** [comment]
> 尝试将 SESSION_EXPIRE_AT_BROWSER_CLOSE=True 修改为 False，看看是不是还会出现。

好的我尝试一下

**Comment by BaiJiangJie** [comment]
开了 SESSION_EXPIRE_AT_BROWSER_CLOSE 参数后。
关闭页面后的时间 > 2min，再打开会提示需要重新登录。
