### ISSUE TITLE
[Feature] Web终端和文件管理 资产排序可否调整成一样的。

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#12067]
Web终端和文件管理 资产排序可否调整成一样的。
![image](https://github.com/jumpserver/jumpserver/assets/70053869/af4f1d53-f10d-4100-b303-660b6f6454f1)
![image](https://github.com/jumpserver/jumpserver/assets/70053869/abcb0b41-df44-4f1c-9ef4-e2969eb54a3e)

**Comment by BaiJiangJie** [comment]
两棵树看似一样，其实不一样。

Luna 页面的最深一层到资产。

文件管理的最深一层到账号。

暂时不考虑优化了。
