### ISSUE TITLE
[Question] 【提问】可以在资产树下创建其他”根节点“吗？

### ISSUE THREAD

**Issue by FIERCELION** [jumpserver/jumpserver#12064]
我注意到在 【控制台】→【资产管理】→【资产列表】→【资产树】 下无法创建根节点，目前创建的所有节点都在“Default”下，怎么创建与"Default“**同级的**根节点？

![Snipaste_2023-11-08_15-20-11](https://github.com/jumpserver/jumpserver/assets/41266070/3549febd-a08b-4f28-92dc-8938bc228e9e)

**Comment by BaiJiangJie** [comment]
不能创建根节点，只能创建 Default 的子节点。
