### ISSUE TITLE
请问一下 现在的版本（1.2）支持ansible和文件的上传下载了吗

### ISSUE THREAD

**Issue by cjw0202** [jumpserver/jumpserver#1206]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已支持 sftp上传，ansible的批量上传还不支持
