### ISSUE TITLE
[Feature] Chen组件能否支持 数据库执行结果复制粘贴的权限控制

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12071]
**请描述您的需求或者改进建议.**
目前情况：数据库 Web GUI 方式连接，查询结果可以进行导出的权限控制，但并不能做复制粘贴的权限控制

需求背景：
对于做了禁止导出的数据库，如果查询结果能复制出来，那和能导出的效果并无太大差异

功能背景：
Chen 组件刚出来的时候，SQL查询结果是不可以进行复制粘贴的，后来用户提需求才改成的可以进行复制粘贴

需求建议：
能否对Chen组件的复制粘贴，在资产授权处进行复制粘贴的权限控制；
或者开放系统配置让用户自行选择能否复制粘贴数据库执行结果

**Comment by BaiJiangJie** [comment]
授权里可以控制复制、粘贴的权限啊。

**Comment by hzhfit2cloud** [comment]
授权规则页面提示复制粘贴仅对 RDP、VNC 生效
<img width="697" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/a7dce714-7177-4a58-81be-c1abfcbb477c">

**Comment by jym503558564** [comment]
待修复

**Comment by jym503558564** [comment]
已修复，待3.9.0发布，再测试。

**Comment by hzhfit2cloud** [comment]
虽弹提示但并未控制成功，还是复制粘贴出来了
![image](https://github.com/jumpserver/jumpserver/assets/89765365/519933c3-04ad-49af-8f6c-d10b89ed8b52)

**Comment by BaiJiangJie** [comment]
v3.9 已发布。

**Comment by hzhfit2cloud** [comment]
已更新到 v3.9 功能，但功能并未实现，如我上一条评论所示
