### ISSUE TITLE
[Bug] 2.28.21 获取登录 IP 错误

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12073]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
版本：v2.28.21

**浏览器版本**
Chrome

**Bug 描述**
升级 v2.28.21 后，登录日志中 web 登录获取的 IP 不是用户 IP，如截图所示，升级前正常，升级后 web 登录 IP 为 LB 的 IP，但是 terminal 登录的是正确的，升级之前的也是正确的。
<img width="1221" alt="image" src="https://github.com/jumpserver/jumpserver/assets/95400700/bb9a77e8-a35b-450e-860c-97b083cc373f">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
LB 是不是没有把地址代理过去？

**Comment by gerry-fit** [comment]
已经代理了，terminal 登录 IP 是正确的，升级之前也是正确的，升级前后 LB 配置未变更

**Comment by gerry-fit** [comment]
看了源码，2.28.21 有调整获取 IP 这一段代码，麻烦核实下

**Comment by BaiJiangJie** [comment]
<img width="967" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1b5e7df2-3fde-4190-beb1-052fb24dd10a">

主要改了这块逻辑。增加了对于 KoKo 端登录获取不到真实 IP 的问题。

**Comment by BaiJiangJie** [comment]
确认一下 这一行是否加上了。

https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf#L39C4-L39C51

**Comment by gerry-fit** [comment]
好的，我确认下

**Comment by gerry-fit** [comment]
配置文件中配置了 USE_LB=0，应该是不会使用到 这个 conf 文件

**Comment by BaiJiangJie** [comment]
嗯，那在华为云的 LB 服务中也需要加上这个配置。

**Comment by gerry-fit** [comment]
华为云 LB 没改配置，升级之前都是可以获取到的， 2222 端口登录也是正确的 IP，您看下最开始的截图，这里就很矛盾了

**Comment by BaiJiangJie** [comment]
v2.28.21 版本优化了获取 IP 的逻辑，更加严谨了一些。

之前发现了漏洞，不优化的话，容易被爆破。

**Comment by gerry-fit** [comment]
所以现在跟 koko 2222 端口获取 IP 逻辑还没有同步是吗

**Comment by gerry-fit** [comment]
可以确认的是华为云 ELB 配置中已经开启了获取客户端 IP

**Comment by BaiJiangJie** [comment]
KoKo 端是主动获取的 IP 地址，在 Core 认证的时候直接取的 KoKo 获取到的客户端地址。

跟访问 Core 获取的逻辑是一样的。

**Comment by BaiJiangJie** [comment]
开启了之后，要转发出去。

> 可以确认的是华为云 ELB 配置中已经开启了获取客户端 IP

**Comment by BaiJiangJie** [comment]
2222 端口走 LB 了吗？

**Comment by gerry-fit** [comment]
这个有点问题吧，华为云开启后就可以了，官方说明：https://www.huaweicloud.com/special/info-elb-ip.html，高级转发策略中也只能将 header 作为条件

**Comment by gerry-fit** [comment]
2222 端口也是走了 LB 的

**Comment by BaiJiangJie** [comment]
<img width="1667" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/ac8e37ab-a25e-4a75-90e4-4883673cce73">

应该就是这个吧。

**Comment by gerry-fit** [comment]
那不就回到 JumpServer 本身了吗.....

**Comment by BaiJiangJie** [comment]
那你最终是改的什么配置，可以的？

**Comment by gerry-fit** [comment]
现在没地方改配置啊，检查了华为云 LB 跟JumpServer jms_web 的 Nginx 配置都是有转发真实 IP，我能想到的就是升级改了相关代码带来的问题

**Comment by BaiJiangJie** [comment]
> 没地方改配置啊，检查了华为云 LB 跟JumpServer jms_web 的 Nginx 配置都是有转发真实 IP，我能想到的就是升级改了相关代码带来的问题

你不是说可以了吗？

**Comment by gerry-fit** [comment]
全程没有说可以哦，只是你提出建议，我去验证测试，然后在讨论这个问题

**Comment by BaiJiangJie** [comment]
<img width="1048" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fcf4011d-a6a5-4dc1-bb6d-b0e4a1a0b535">

**Comment by gerry-fit** [comment]
是我没表达清楚，我这个是回复的你上一个说开启获取客户端 IP 后还要转发 
![image](https://github.com/jumpserver/jumpserver/assets/95400700/d5e122ab-30de-4653-a959-07504f30ae52)

**Comment by BaiJiangJie** [comment]
那就不清楚了。你试试不用华为云的 LB 可以吗？

**Comment by gerry-fit** [comment]
我要表达的意思是，华为云 ELB 只需要开启“获取客户端 IP”，没有其他转发设置了，这个是已经开启了的

**Comment by BaiJiangJie** [comment]
有环境吗？

**Comment by gerry-fit** [comment]
周一麻烦你看下吧，周五就不加班了，早点下班，辛苦了！

**Comment by BaiJiangJie** [comment]
好的。

**Comment by gerry-fit** [comment]
配置文件修改 USE_LB 的值重启可以

**Comment by waterdrops** [comment]
> 配置文件修改 USE_LB 的值重启可以
我们JumpServer 数据走向： 阿里云LB --> ECS --> JumpServer

看代码取的是$remote_addr的值，如果nginx 不配置set_real_ip_from x.x.x.x/x，JumpServer一直取的是LB的IP

Nginx添加以下内容
```
    set_real_ip_from 100.64.0.0/10;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
```

@gerry-fit 请问只需要修改USE_LB=0，./jmsctl.sh restart 就可以了吗？
