### ISSUE TITLE
[Question] 双因子MFA登陆绑定手机界面提示下载对应软件的二维码能否更换

### ISSUE THREAD

**Issue by sookey** [jumpserver/jumpserver#12077]
现在默认用户手机扫描二维码下载的是google authenticator，但这个应用IOS版本已经在中国区下架，能否修改默认二维码，最终达到提示用户下载其他替代软件的效果？

**Comment by BaiJiangJie** [comment]
最新版本的 MFA 认证应用二维码已更新，请升级解决。
