### ISSUE TITLE
[Feature] 工单管理-数据库命令批量复核执行

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12072]
**请描述您的需求或者改进建议.**
目前数据库命令复核策略是：一条SQL走一个复核工单，审批同意后进入下一条SQL复核，拒绝则不进行后续SQL的审批

需求背景：
希望把JS作为数据库访问的唯一入口，以便于进行数据库审计
当有跑批场景时，通常是会批量修改几百甚至更多 SQL 语句的，如果每一条SQL都需要审批一次，那工单审批的工作量是巨大的

需求建议：
方案一：能否在 Web GUI 执行批量SQL的时候，作为一个整体进行命令复核？
方案二：能否在工单管理模块添加 【数据库批量执行申请】，选择对应的数据库，填写批量SQL语句，由 DBA 审批通过后批量下发数据库执行命令

**Comment by BaiJiangJie** [comment]
SQL 语句是否需要审批是通过命令规则来控制的。

只有当执行的 SQL 语句命中了复核的命令规则，才会发起工单进行审批。

批量审批也是一样的逻辑，如果批量命令中的任意一条命令被拒绝了，整条命令就都会被拒绝执行。

**Comment by hzhfit2cloud** [comment]
主要针对这种场景：
比如我有 100条Update语句需要执行，审批者能够一眼看出来无危险操作，希望可以直接一键审批通过，但按照目前的逻辑得审批100次 才可以

**Comment by BaiJiangJie** [comment]
嗯，这种批量审核的方式对于 Web GUI（Chen）来说是合适的。

v3.10 考虑支持一下。

**Comment by hzhfit2cloud** [comment]
👍🏻
