### ISSUE TITLE
LDAP用户导入点击书刷新无效 

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12088]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
版本 119.0.6045.124（正式版本） （64 位）

**Bug 描述**
第一次设置好LDAP，点击用户同步，一直显示等待用户同步，然后点击刷新业务反应，关闭用户导入窗口，才能看到导入的用户。

**Bug 重现步骤(有截图更好)**
1.第一次配置好LDAP，点击用户导入
![微信截图_20231113105616](https://github.com/jumpserver/jumpserver/assets/43403764/20574d6e-1025-4842-a867-b89883bc4bc4)

2.这个界面一直显示等待用户用户，点击刷新也没有反应
![1699845050134](https://github.com/jumpserver/jumpserver/assets/43403764/81c78e6a-1f20-41e6-8cc2-e420e1658dd9)

3.关闭这个窗口，重新打开一次，才能显示同步的用户
![1699845134947](https://github.com/jumpserver/jumpserver/assets/43403764/12060f81-87c2-4415-8ebf-62fdd720f657)
![3a1a9df195a159f415b79439ecf41d7](https://github.com/jumpserver/jumpserver/assets/43403764/c27bf296-97f4-49e1-ae2c-9b6b57af1b8b)

**Comment by jym503558564** [comment]
已知问题，待复现。

**Comment by jym503558564** [comment]
v3.10.0已修复
