### ISSUE TITLE
[Bug] 资产详情页面快速更新激活状态后端口被重置为22

### ISSUE THREAD

**Issue by HanadaLee** [jumpserver/jumpserver#12085]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.7.0

**浏览器版本**

Chrome 版本 119.0.6045.124（正式版本） （64 位）

**Bug 描述**

资产详情页面快速更新激活状态后端口被重置为22

**Bug 重现步骤(有截图更好)**
1. 首先将SSH端口设置为一个除了22以外的特殊端口
![image](https://github.com/jumpserver/jumpserver/assets/33758411/26577d7b-07aa-490d-96bd-a07b328fb126)

2. 进入资产详情页面，右上角有快速更新
![image](https://github.com/jumpserver/jumpserver/assets/33758411/48bbd5dd-5102-4276-b5fb-b3c9be0f815a)

4. 点击激活按钮，禁用资产
![image](https://github.com/jumpserver/jumpserver/assets/33758411/eb1ef63c-0d0e-4877-8577-6eda5cd2ffdd)

5、刷新页面，端口变回22
![image](https://github.com/jumpserver/jumpserver/assets/33758411/b07de5d2-d033-4f1a-85ac-da9e481007bf)

**Comment by BaiJiangJie** [comment]
感谢提问，这个问题最新版本已解决。（不过也可以等等再升级，预计下周会发布 v3.8.2 版本，修复了一些 v3.8 版本带来的一些问题）

请关注后续版本发布。
