### ISSUE TITLE
[Bug] RDP资产连接显示异常问题

### ISSUE THREAD

**Issue by lzy192251** [jumpserver/jumpserver#12086]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
  Version v3.8.1

**浏览器版本**
   Google Chrome 版本 119.0.6045.105（正式版本） （64 位）

**Bug 描述**
 通过JumpServer 连接windos2008 R2版本资产时候，显示界面第一次连接正常显示，过了1-2s后，出现部分黑块，但可以进行操作，只不过无法确定点击位置的问题，只得重新连接，连接后问题依旧。
使用老版本和新版本JumpServer 同样存在该问题。windows2016版本不受影响。
也尝试切换Edge浏览器，问题依旧。
尝试在设置切换分辨率，1080P问题依旧，自动则会减少异常显示的次数。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/9943697/f6e2e3b5-d24d-41c7-8293-f4f3918e3c0b)

**Comment by BaiJiangJie** [comment]
尝试关闭浏览器硬件加速。
https://github.com/jumpserver/jumpserver/issues/12035

**Comment by lzy192251** [comment]
已经收到您的邮件，我会尽快处理。

**Comment by BaiJiangJie** [comment]
@lzy192251 知道如何复现吗？

**Comment by lzy192251** [comment]
> @lzy192251知道如何复现吗？

目前暂时使用了关闭浏览器硬件加速解决问题，复现的话应该直接去连接2008类型就好了。我们的资产不变的情况下，我安装了新版本的Jumpserver问题依旧。但是没有尝试使用新新安装的2008资产，也并没有再外部网络重试验证。

**Comment by BaiJiangJie** [comment]
我们内部有一台 windows 2008 RD 的机器，Chrome 也是最新版本，一直没有复现。

**Comment by BaiJiangJie** [comment]
<img width="960" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/f4b9afbc-32e3-49c3-a2a5-61ec44a0050a">
<img width="1207" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/e20d5c7b-44a9-4ce2-99bd-4b79eebe20e9">
<img width="495" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a4b34095-3dc0-4433-a698-fae927471a7c">


还是没有复现。

**Comment by lzy192251** [comment]
稍等下，我在另一环境试试。

**Comment by BaiJiangJie** [comment]
好的。

**Comment by BaiJiangJie** [comment]
我们想定位一下问题，看看能否从产品层面解决。（因为目前浏览器默认都是打开的浏览器硬件加速，最近挺多用户遇到的）

**Comment by lzy192251** [comment]
我在我们另一环境下面，尝试连接2008也没有出现这个问题（开启加速），但在我们最早使用的版本也就是出现问题的版本上还是复现了。

**Comment by lzy192251** [comment]
是不是需要长时间使用后系统层面才会出现这个问题，因为这个之前这个系统我们已经使用了2-3年了。一致没出现这个问题，也就是11月4日前后才出现的问题。

**Comment by BaiJiangJie** [comment]
> 是不是需要长时间使用后系统层面才会出现这个问题，因为这个之前这个系统我们已经使用了2-3年了。一致没出现这个问题，也就是11月4日前后才出现的问题。

2-3年使用过程中，一直使用的是什么版本？11月4日的时候，有升级过吗？（JumpServer 的版本）或者 Windows 系统有变更过吗？

还是说正常使用着都没有做过升级就出现了呢？

**Comment by R0llingRed** [comment]
同样出现了这个问题，我的jumpserver版本是最新的，操作系统是Windows Server 2008和2003，都出现了这种情况。甚至今天查看4个月前的录像时也出现了黑块，我记得当时肯定是没有黑块的😨。

**Comment by djy1121** [comment]
同样出现这个问题，之前使用v3.7.1版本是正常，上周升级到v3.8.1后出现。目前发现在windows server 2008和2003上都有类似情况，而且是在安装有数据库或者数据库连接工具或软件的设备上出现，如果没有开启数据库连接工具或软件时能正常显示，启动后就会出现大面积黑块

**Comment by BaiJiangJie** [comment]
> @BaiJiangJie 我们一直用的是这个版本Version v2.16.3-101 GPLv2. 出问题之前服务器、jumpserver都没有任何升级操作。无任何操作就突然出现的，后面我们直接使用windows rdp连接是正常的，可以排除网络的问题。后面单独安装了Version v3.8.1问题也还是又出现，这就很难确认问题了。


这个情况下，浏览器做升级了吗？

**Comment by BaiJiangJie** [comment]
现在怀疑是 Chrome 升级导致的。

**Comment by lzy192251** [comment]
> > @BaiJiangJie 我们一直用的是这个版本Version v2.16.3-101 GPLv2. 出问题之前服务器、jumpserver都没有任何升级操作。无任何操作就突然出现的，后面我们直接使用windows rdp连接是正常的，可以排除网络的问题。后面单独安装了Version v3.8.1问题也还是又出现，这就很难确认问题了。
> 
> 这个情况下，浏览器做升级了吗？



> 现在怀疑是 Chrome 升级导致的。


Chrome确实是有升级的，这个问题再edge也出现了。回去我换一个旧版本的chrome 试试在回复。

**Comment by lzy192251** [comment]
@BaiJiangJie 
我使用Chrome版本 89.0.4389.114（正式版本） （64 位）测试是正常的，没有出现花屏。默认Chrome配置，未进行任何设置参数的修改。

**Comment by lzy192251** [comment]
经过测试，在正式推送版本Chromium 119.0.6045.105 for Windows (x64)复现这个问题。

**Comment by lzy192251** [comment]
@BaiJiangJie 
经过测试，在Chromium 119.0.6045.105 for Windows (x64)版本复现问题，在Chromium 118.0.5993.118 for Windows (x64)为最后正常的版本。具体请查看chrome更新日志。

附下载地址：
Chromium 118.0.5993.118 for Windows (x64)：
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1192607%2Fchrome-win.zip?generation=1693948542833695&alt=media

Chromium 119.0.6045.105 for Windows (x64)：
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1204234%2Fchrome-win.zip?generation=1696284118231383&alt=media

**Comment by lzy192251** [comment]
@BaiJiangJie 
经过测试，119.0.6030.1版本向119.0.6031.0升级后，出现了问题，只能帮忙验证到这里了，希望可以帮助解决问题。

119.0.6030.1
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1200941%2Fchrome-win.zip?generation=1695652010339515&alt=media


119.0.6031.0
https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F1201324%2Fchrome-win.zip?generation=1695699022206867&alt=media
