### ISSUE TITLE
[Bug] 添加网域网关的资产进下账号推送时，账号校验失败

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#12080]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.1

**浏览器版本**
Chrome 104.0.5112.81

**Bug 描述**
问题一：账号推送时，在资产所选系统平台账号校验方式为ansible ping的情况下，仍使用python paramiko模块进下账号校验；
问题二：在资产已配置网域网关，且需要通过网域网关进下通信时，进下账号推送，账号实际已推送成功，但账号校验报错连接超时(当不走网域网关后，账号推送测试OK)

**Bug 重现步骤(有截图更好)**
见问题描述
![25ba2105d78b891b5375fd3cdae1474](https://github.com/jumpserver/jumpserver/assets/92150453/77482434-12bf-4137-923f-12500ee05344)
![cb8c24432b6db4cee2bfea00172086f](https://github.com/jumpserver/jumpserver/assets/92150453/4f35202b-ee72-48f1-b2ed-33945e3481f4)
![13859f5a1fd61c273234872634adf1c](https://github.com/jumpserver/jumpserver/assets/92150453/61f5044e-4250-4d4a-b6e2-4fda96e9f2db)
![019c67803919aa9fb48b5c72d902b1f](https://github.com/jumpserver/jumpserver/assets/92150453/8543df35-e49b-40f3-8dbf-35ab89cfd2a3)

**Comment by BaiJiangJie** [comment]
第一个问题：账号改密和账号推送中的“账号可连接性校验”步骤使用的方式是内部指定的（Paramiko），不是平台的校验方式。

**Comment by BaiJiangJie** [comment]
第二个问题，手动测试一下账号的可连接性。（ping 和 paramiko 方式都试一下）

**Comment by sageonedream** [comment]
> 第二个问题，手动测试一下账号的可连接性。（ping 和 paramiko 方式都试一下）

单独ping是不行的，需要走网域网关才能连接上。目前的情况就是在账号推送时，最后的账号校验环节，已配置的网域网关没有识别

**Comment by BaiJiangJie** [comment]
v3.9 优化过一次，升级到最新版本看看会不会还有问题。

**Comment by sageonedream** [comment]
问题二：升级至3.9.3版本，在资产需配置网域网关的情况下才能与JS建立通信，进行账号推送时，仍报错连接超时
![e701d683a13b8845ec14f1a7bc1bcf72_](https://github.com/jumpserver/jumpserver/assets/92150453/5244f0d9-d6cd-4f0a-87eb-6e1f5f761d08)
![b6d9a562dd3ce79820d946a7e21879d1_](https://github.com/jumpserver/jumpserver/assets/92150453/ca5a0829-fe23-45d1-9b9a-f09a814f37a8)
