### ISSUE TITLE
[Bug] 关于WEB终端， Session不会失效问题

### ISSUE THREAD

**Issue by xinlongnb** [jumpserver/jumpserver#12089]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer V3.8.1

**浏览器版本**
![image](https://github.com/jumpserver/jumpserver/assets/101784208/6fcd43aa-7d9b-4666-baf5-2db5d4123aaf)

**Bug 描述**

JumpServer使用管理员界面登录，然后触发连接超时提醒，但是之前的WEB终端，里面的 Session不会失效
 

在WEB终端里面，全部都可以随便连接

**Bug 重现步骤(有截图更好)**
1.

![image](https://github.com/jumpserver/jumpserver/assets/101784208/895ee5b4-d4e1-421e-8ad7-2837bf06966e)

2.

![image](https://github.com/jumpserver/jumpserver/assets/101784208/22c2271d-2949-4fc5-b105-cdc98945d1ab)

3.
控制台界面，的会话会提升断开，但是不去刷新，luan界面里面的无影响，可以正常使用，不会提示断开，这个进程可以一直使用，只要不刷dashboard页面，他的权限就一直登录一直使用。

**Comment by BaiJiangJie** [comment]
<= v3.7 以前的版本是用户 Session 会话过期，已经建立的 Luna 页面的会话不会失效，也没有提示，可以正常使用；但是不能新连接会话。

3.8 版本以后做了优化，用户 Session 会话过期，已建立的 Luna 页面的会话会提示已过期，需要重新登录，如果用户选择取消，可以正常操作，但是 2min 就会提醒一下。（主要为了解决正在操作的会话比较重要，给用户一个缓冲的时间）。但是不能新连接会话。

你的情况应该是第二种吧。

**Comment by xinlongnb** [comment]
是的第二种，但是目前发现，我的前段dashboard页面提示从新登录，但是我点击去取消，Luna页面页面权限全部存在，我不管新建立会话，还是从新连接全部都是没有问题的，只要我第一个dashboard不动，Luna就会一直存在，目前这个场景主要应用的是用户电脑休眠了两天，我从新打开浏览器进行刷新luna页面，照常能出现连接，而且可以连接成功。感觉具有一定风险。

**Comment by BaiJiangJie** [comment]
应该是不会的。
@xinlongnb

**Comment by BaiJiangJie** [comment]
没有复现，可以提供一些复现视频吗？

**Comment by xinlongnb** [comment]
好的，我今天录一下视频

**Comment by xinlongnb** [comment]
我从新测试了一下，发现这个问题应该是我浏览器Cookie引起的，从新测试已经浮现不了了。应该是我的问题，我把问题关闭一下
