### ISSUE TITLE
ssh进入jumpserver后如果连接到其他服务器有问题，无法优雅的退出，只能关闭终端重连

### ISSUE THREAD

**Issue by stephen8339** [jumpserver/jumpserver#1208]
[简述你的问题]
ssh进入jumpserver后如果连接到其他服务器有问题，无法优雅的退出，只能关闭终端重连

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.2.0-2

##### 问题复现步骤
1. [步骤1]ssh进入jumpserver
2. [步骤2]连接一台无法连通的服务器

##### 其他
希望有连接超时选择重试或者退出的选项，谢谢！

**Comment by gengkeye** [comment]
SAME

**Comment by ibuler** [comment]
收到

**Comment by ibuler** [comment]
fixed

**Comment by stephen8339** [comment]
好快，请问还在dev分支吗？还是已经合到正式版了？只要更新代码就可以了吗？

**Comment by ibuler** [comment]
master分支
