### ISSUE TITLE
网域网关的密码里面包含特殊字符"&",会导致资产连接报错。

### ISSUE THREAD

**Issue by claybbs** [jumpserver/jumpserver#1209]
[简述你的问题]
网域网关的密码里面包含特殊字符"&",比如:abc123&fZ,新增的资产使用该网关会报错如下：
 {'ping': {'unreachable': True, 'msg': 'Failed to connect to the host via ssh: /bin/bash: fZ: 未找到命令\nssh_exchange_identification: Connection closed by remote host\r\n', 'changed': False}}
##### 使用版本
1.2.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个bug无法解决，因为ansible使用时没有处理特殊字符
