### ISSUE TITLE
[Feature] 从资产列表进入资产详情 退出后保持之前的筛选条件

### ISSUE THREAD

**Issue by internelp** [jumpserver/jumpserver#12099]
**现状**
版本：v3.8.1
资产列表进入资产详情，返回后筛选条件被清空。

<img width="471" alt="iShot_2023-11-14_13 48 58" src="https://github.com/jumpserver/jumpserver/assets/3395436/133374eb-4ddf-4ec5-9181-16d3fb37b609">

<img width="531" alt="iShot_2023-11-14_13 49 29" src="https://github.com/jumpserver/jumpserver/assets/3395436/cdadead8-843e-42c8-8e41-1f92c682cab9">

<img width="485" alt="iShot_2023-11-14_13 50 07" src="https://github.com/jumpserver/jumpserver/assets/3395436/ca92bfd4-869e-4113-8865-b4cb76e92d01">

**建议**
从资产详情返回后保持之前的筛选条件。

**Comment by BaiJiangJie** [comment]
暂时不支持，因为涉及到节点层级的展开问题（异步方式），记住之后还要默认再展开，所以设计起来比较复杂。
