### ISSUE TITLE
[Bug] 资产树目录显示的数量为0

### ISSUE THREAD

**Issue by airsmon** [jumpserver/jumpserver#12097]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
edge最新版本

**Bug 描述**
资产树显示为0，实际有2个资产
![image](https://github.com/jumpserver/jumpserver/assets/55136870/5426b74e-a455-43d4-9119-54c272343d24)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
右击-重新校对一下资产数量。
