### ISSUE TITLE
[Question] 远程桌面里面右键后黑屏

### ISSUE THREAD

**Issue by Belkuy** [jumpserver/jumpserver#12090]
**请描述您的问题.**
jumpserver 版本：2.28.16
chrome 版本：119.0.6045.106
问题：
最近在远程 windows server 2008 r2的系统时，在远程主机的应用上右键，立马黑屏，只能重连恢复。
![image](https://github.com/jumpserver/jumpserver/assets/84887701/b7ac9730-5226-4a8b-8a3a-1787a7f4407e)

**Comment by BaiJiangJie** [comment]
关闭浏览器加速可解决。

https://github.com/jumpserver/jumpserver/issues/12035
