### ISSUE TITLE
多网域不能添加相同IP资产

### ISSUE THREAD

**Issue by sy1995** [jumpserver/jumpserver#1210]
[简述你的问题]

##### 使用版本
jumpserver 1.1

##### 问题复现步骤
1. 在网域1中添加了如172.0.0.2
2. 网域2中也要添加相同ip172.0.0.2就会报错，提示重名。

这是两个网域，完全隔离，内部用的私网地址应该是可以重复的。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ip和端口现在有唯一键限制

**Comment by opstrip** [comment]
我也遇到这问题了。临时解决办法是该数据库把这个唯一约束删掉改成主机名+ip+端口了。不知道会不会有其他的问题。应该是网域+ip+端口可能更科学点。

**Comment by jokimina** [comment]
![image](https://user-images.githubusercontent.com/11460661/40988792-8f7ab1a0-691e-11e8-96da-7f24608515f4.png)

apps/assets/models/asset.py

如果想先解除限制的话 修改如上文件 然后  ./utils/make_migrations.sh    @sy1995

**Comment by liqilong2017** [comment]
现在还是这样吗？？？IP 还是不能一样对么？IP一样，端口不一样也不行吗？？？提示验证失败！！！

**Comment by ibuler** [comment]
新版本已去掉唯一键约束
