### ISSUE TITLE
[Feature] 希望离线更新脚本中自动备份数据步骤可选

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12108]
**请描述您的需求或者改进建议.**
希望在执行 ./jmsctl.sh upgrade 进行离线更新时，数据库备份步骤改为可选，默认进行备份的情况下，如果数据量较大在以下几种场景将耗费太多时间：
1、提前备份了数据的情况下；
2、主备或分布式架构升级时每个节点都会备份数据，是重复工作，没有必要；

<img width="906" alt="image" src="https://github.com/jumpserver/jumpserver/assets/95400700/b30a5a35-b773-45f9-ab5f-950f7b2adab3">

**Comment by BaiJiangJie** [comment]
好的，可以考虑一下。之前主要考虑容错问题。强制需要执行备份。

**Comment by wojiushixiaobai** [comment]
export SKIP_BACKUP_DB=1
或者写入配置文件
