### ISSUE TITLE
[Bug]  命令过滤规则资产属性筛选标签显示问题

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12103]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
 Chrome 119

**Bug 描述**
命令过滤、资产登录创建规则时，资产标签属性只显示名称，而平台允许存在同名标签，从而产生歧义
![image](https://github.com/jumpserver/jumpserver/assets/95400700/5a697d2f-39aa-45d6-b48f-b012cdb6bc11)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.9 版本已修复。请关注后续版本发布。

**Comment by jym503558564** [comment]
已修复，3.9.1已发布，请升级进行测试。
