### ISSUE TITLE
[Feature] Web GUI  的方式连接数据库导出结果不会审计

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12116]
需求描述：
Web GUI  的方式连接MySQL导出查询结果，命令记录里面只会记录select语句，无法区分是导出还是查询操作，文件传输也不会记录导出的文件。

实现：
可以区分是导出还是查询，实现审计效果。

**Comment by BaiJiangJie** [comment]
导出的时候，select 语句前加一个【Export】select * from table ............；
文件传输记录一下日志。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
