### ISSUE TITLE
[Bug] 账号推送失败，变成手动账号，需要输入密码

### ISSUE THREAD

**Issue by DaddyXz** [jumpserver/jumpserver#12113]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.4

**浏览器版本**

**Bug 描述**
账号推送失败

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/b4af4a4f-a408-4a77-8bad-d4c889042b69)

2.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/735f0afc-0469-4574-8ea5-716a6cb90bba)

3.
![image](https://github.com/jumpserver/jumpserver/assets/99782519/c2a1d441-5082-43cf-950c-28e925d29972)
4. 
![image](https://github.com/jumpserver/jumpserver/assets/99782519/796f83de-0c7c-438b-b46d-b622287509f4)

**Comment by BaiJiangJie** [comment]
查看一下账号密码信息，看看是否有密码？

**Comment by BaiJiangJie** [comment]
看一下推送任务的执行日志。

如果找不到，就手动推送一下，看看日志。

**Comment by BaiJiangJie** [comment]
升级到最新版本试一下。最新版本有对这块做一些优化。
