### ISSUE TITLE
[Bug] Win11，最新版JumpServerClient端安装后，保存配置时报错

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12112]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.0

**浏览器版本**
版本 119.0.6045.124（正式版本） （64 位）

**Bug 描述**
Win11，安装最新版JumpServerClient（exe文件格式）端，在保存配置路径的时候报错

**Bug 重现步骤(有截图更好)**
1.安装后，保存配置的时候报错如下：
![image](https://github.com/jumpserver/jumpserver/assets/43403764/5d30ea08-6260-4c1b-a584-6539cca97b6e)

![6a5a136b6daa68eef0cfece3a822535](https://github.com/jumpserver/jumpserver/assets/43403764/1009a20d-1029-46b7-ba86-9e21f90207f0)

**Comment by BaiJiangJie** [comment]
能稳定复现吗？

**Comment by Halo1236** [comment]
https://github.com/jumpserver/clients/releases/download/v2.0.2/JumpServer-Client-Installer-v2.0.2-x86_64.exe

c盘权限问题，麻烦重新下载安装一下这个包，再试试 @LinuxLeader
