### ISSUE TITLE
[Bug] 3.8版本 配置多层反向代理 rz传输大文件失败

### ISSUE THREAD

**Issue by qiulinjie0327** [jumpserver/jumpserver#12118]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.8.1 3.8.0

**浏览器版本**
edge

**Bug 描述**
配置了多层反向代理后，文件上传乱码，和超时断开
小文件几十M正常，大于100M稳定复现。

**Bug 重现步骤(有截图更好)**
1.使用web端，rz上传文件乱码。
![image](https://github.com/jumpserver/jumpserver/assets/52249559/52375c6a-a254-43e8-af47-c63023dbaed4)

2.使用客户端，rz上传文件乱码
<img width="1064" alt="5a98c67e3372924d32fb3f79e3b8ad7" src="https://github.com/jumpserver/jumpserver/assets/52249559/5473a9e8-a2d9-477e-a877-1da5a42ece8e">

3.使用rz -e 传输报错websocket closd
![48b986007b1bf65fbe2272ab1dea665](https://github.com/jumpserver/jumpserver/assets/52249559/7cf41d7c-0a28-4732-b335-57f23480fc5a)

**Comment by BaiJiangJie** [comment]
“配置了多层反向代理后”

原生的单机部署会有问题吗？
@qiulinjie0327

**Comment by qiulinjie0327** [comment]
原生单机部署上传是没有问题的 但是上传的时候卡顿下应该是浏览器资源占用过多导致的
![image](https://github.com/jumpserver/jumpserver/assets/52249559/a45cd2f5-97eb-431c-80d7-11d1a2c2c429)

**Comment by BaiJiangJie** [comment]
多层 Nginx 和 大文件传输，建议使用 SFTP，不建议使用 rz、sz。
