### ISSUE TITLE
[Bug] WEB CLI 和 WEB GUI 连数据库，字段类型为地理坐标location时显示乱码

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#12114]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
Chrome

**Bug 描述**
WEB CLI 和 WEB GUI 连数据库，字段类型为地理坐标location时显示乱码

**Bug 重现步骤(有截图更好)**
1.在MySQL上创建一张表，并插入测试数据
-- 创建地理坐标表
CREATE TABLE coordinates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    location POINT,
    address VARCHAR(255)
);
-- 插入地理坐标数据
INSERT INTO coordinates (location, address)
VALUES (POINT(30.2888, -97.7054), 'Austin, TX'),
       (POINT(37.7749, -122.4194), 'San Francisco, CA'),
       (POINT(40.7128, -74.0060), 'New York, NY');
![image](https://github.com/jumpserver/jumpserver/assets/40846859/8742aaa5-ccb4-4428-be95-34ad4a204045)
Navicat直连数据库显示如图
2.在JumpServer上使用WEB CLI 和 WEB GUI 连数据库
3.
![image](https://github.com/jumpserver/jumpserver/assets/40846859/a2ad816a-832c-4d2f-8888-a20838249847)
![image](https://github.com/jumpserver/jumpserver/assets/40846859/6552c68a-3ebd-47dd-8682-0ca173d2a8c1)

**Comment by jym503558564** [comment]
已复现，待修复

**Comment by jym503558564** [comment]
已修改成合原生的cli一致
![image](https://github.com/jumpserver/jumpserver/assets/40739051/650ccd10-f6ed-419a-bc1b-30a78bb3eda0)

**Comment by jym503558564** [comment]
研发这边已优化成和原生显示一致。
