### ISSUE TITLE
[Feature] 3.6.4版本的web终端资源搜索框太小

### ISSUE THREAD

**Issue by wangmingwang123** [jumpserver/jumpserver#12127]
**请描述您的需求或者改进建议.**
目前使用的3.6.4版本  web终端搜索资源的时候每次都需要点击放大镜搜索框才能出来  比较麻烦 而且搜索框比较小  不如2.0的好用 直观 请问这个可以优化嘛?
![image](https://github.com/jumpserver/jumpserver/assets/73093158/728d7eb9-1907-44d3-bc76-a9eae63c74c0)
![image](https://github.com/jumpserver/jumpserver/assets/73093158/6f7e0d48-c37f-4e09-a690-f7a59bfa69dc)

**Comment by BaiJiangJie** [comment]
精心设计过的，暂时不考虑优化了。
