### ISSUE TITLE
上传文件

### ISSUE THREAD

**Issue by caochuansong** [jumpserver/jumpserver#1212]
请问 我要在本地通过跳板机往目标服务器上传文件  我应该怎么操作呢？

**Comment by caochuansong** [comment]
shell界面为什么没有看到u选项

**Comment by chenrizhi** [comment]
使用sftp工具（如Xftp）登录coco端口2222，就能看到资产列表了。

**Comment by brucegogo** [comment]
看到资产列表后，无法上传到资产
![default](https://user-images.githubusercontent.com/40048968/44098326-79c7bdfa-a012-11e8-8002-6a3193eedd8c.png)

我选择资产，系统用户，无法打开。
不像 SSH登录，选择资产后提示登录密码。
