### ISSUE TITLE
[Question] 在web终端连接website资产时出现“Core API 发生错误”

### ISSUE THREAD

**Issue by dadonehouse019** [jumpserver/jumpserver#12132]
jumpserver版本：3.7.1
发布机版本：windows server 2016（已初始化）
问题：
检查/data/jumpserver/core/data/logs/jumpserver.log日志时出现以下错误
[log ERROR] Internal Server Error: /api/v1/authentication/super-connection-token/applet-option/
Traceback (most recent call last):

**Comment by dadonehouse019** [comment]
docker logs -f jms_lion --tail 20

**Comment by dadonehouse019** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/116007084/0e4ff5c2-6281-40b7-9b58-c442b20d82e6)

**Comment by qiulinjie0327** [comment]
要么就是没部署应用发布机，如果部署了
检查下系统-远程应用-应用详情里账号列表有没有生成。
![image](https://github.com/jumpserver/jumpserver/assets/52249559/39b7c14b-bbab-4eb8-9c4c-d3f5047d511a)

**Comment by BaiJiangJie** [comment]
看看组件注册成功了吗？
