### ISSUE TITLE
如何 v2.23.4  升级到 v3.8.2 

### ISSUE THREAD

**Issue by leipore** [jumpserver/jumpserver#12140]
环境kubernetes helm

数据库需要如何变动 ，什么升级路径？

**Comment by jarod** [comment]
建议jumpserver团队重视大版本升级问题，向gitlab这样的软件学习，让升级平顺过度，把版本升级迁移作为软件的一部分，否则只是提示一句建议搭建一个新的3.0环境体验只会造成用户停留在老版本

**Comment by shiqianwei0508** [comment]
如果没有完整的升级方案，我是不会升级的。慢慢累积下来的资产，我不想重新添加一遍

**Comment by leipore** [comment]
> 如果没有完整的升级方案，我是不会升级的。慢慢累积下来的资产，我不想重新添加一遍

关键问题是有安全漏洞

**Comment by BaiJiangJie** [comment]
研发团队考虑的情况是这样的：
1. v2 所有版本 和 v3 所有版本，同等大版本的情况下，所有版本都能平滑升级
2. v1、v2、v3 大版本之间，我们会尽量做到兼容，如果因为架构的变动，导致无法兼容，我们会放弃对应模块的兼容。

无论是研发新版本之前，之中还是之后，平滑升级一直是我们首要考虑的问题。

如果默认升级流程，无法做到兼容，会提供对应的迁移脚本，辅助我们的用户进行升级。

如果迁移脚本都解决不了，那就需要用户手动进行干预，同时项目团队会出对应的迁移指南，如果自己搞不定，交流群里的社区助手也会帮助大家。

**Comment by leipore** [comment]
> 研发团队考虑的情况是这样的：
> 
> 1. v2 所有版本 和 v3 所有版本，同等大版本的情况下，所有版本都能平滑升级
> 2. v1、v2、v3 大版本之间，我们会尽量做到兼容，如果因为架构的变动，导致无法兼容，我们会放弃对应模块的兼容。
> 
> 无论是研发新版本之前，之中还是之后，平滑升级一直是我们首要考虑的问题。
> 
> 如果默认升级流程，无法做到兼容，会提供对应的迁移脚本，辅助我们的用户进行升级。
> 
> 如果迁移脚本都解决不了，那就需要用户手动进行干预，同时项目团队会出对应的迁移指南，如果自己搞不定，交流群里的社区助手也会帮助大家。
> 
> 如果以上流程都解决不了，那就需要重新添加数据。

给些建议和文档呗？

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9

**Comment by leipore** [comment]
> https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9

这个里面没有提到数据库表结构的问题？

**Comment by BaiJiangJie** [comment]
表结构正常是不会出现问题的。

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/installation/migration/#24

按着文档来，基本没问题。
