### ISSUE TITLE
luna 连接centos失败

### ISSUE THREAD

**Issue by Suchel** [jumpserver/jumpserver#1215]
[简述你的问题]
luna 连接centos失败。coco 无法使用ssh admin@ip 2222登录，报权限拒绝。

##### 使用版本
Version 1.2.0-2 GPLv2.
centos 6.5
非docker部署

##### 问题复现步骤
1. 添加1台windows和1台centos作为测试
2. 使用luna连接windows正常，连接centos失败，界面无反应，打开浏览器控制台，报错：
502 bad getway

##### 具体表现[截图可能会更好些,最好能截全]
![qq 20180419143840](https://user-images.githubusercontent.com/23067401/38975156-633a32c8-43df-11e8-8867-4d90663974f6.png)

![qq 20180419143847](https://user-images.githubusercontent.com/23067401/38975185-8075b36c-43df-11e8-9e5c-ed5c7c0a9436.png)

![bcht 59 svbkchn 0mkw4](https://user-images.githubusercontent.com/23067401/38975345-19655258-43e0-11e8-9ae0-4c96f727630f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
coco/logs/coco.log看下报错，然后根据[faq](http://docs.jumpserver.org/zh/docs/faq.html)解决。如果我没有看错，应该是coco掉了。

**Comment by Suchel** [comment]
我当时查看了日志，具体什么忘记了。然后查看了cooc的状态，也是运行中的。
这个问题会偶尔出现，解决方法目前发现的只有通过重启jms和coco。
至于访问2222端口，从始至终还是没有成功过

**Comment by gengkeye** [comment]
>至于访问2222端口，从始至终还是没有成功过

你没有加-p选项，我试了一下加-p是可以的，不加就不行

**Comment by liuzheng** [comment]
@Suchel 请到jumpserver终端后台查看是否接受coco的注册，或者更新coco的注册信息：删除终端控制台里的coco注册信息，删除coco目录下 keys/.access_key 文件，重新运行coco，接受coco的注册

**Comment by wojiushixiaobai** [comment]
@Suchel 群 I 里面发下言，我可以协助你解决。或者自己参考faq解决下

**Comment by Suchel** [comment]
自己已经解决，谢谢各位大佬的帮助。thanks very much!
