### ISSUE TITLE
wait for jms_mysql 172.19.0.2 ready

### ISSUE THREAD

**Issue by mzsj2214474136** [jumpserver/jumpserver#12160]
**请描述您的问题.**
打扰了，我正在学习这个，docker 安装出现问题，我应该怎么解决
这是我的
 version: '3'
services:
  jumpserver:
    container_name: jumpserver
    image: jumpserver/jms_all:v3.9.1
    ports:
      - 10099:80
    volumes:
      - /usr/local/docker/JumpServer/data:/opt/jumpserver/data
      - /usr/local/docker/JumpServer/logs:/opt/jumpserver/logs
    environment:
      - SECRET_KEY=YoLTgaAeOaXPFRljOAPOr9Xh5H6RXhMakWMXjPAB9Jx8YRsbGx
      - BOOTSTRAP_TOKEN=YfwYqckamzswdMrL
      - DB_ENGINE=mysql
      - DB_HOST=172.19.0.2
      - DB_PORT=10096
      - DB_NAME=jumpserver
      - DB_USER=jumpserver
      - DB_PASSWORD=jumpserver
      - REDIS_HOST=172.22.0.3
      - REDIS_PORT=10098
      - REDIS_PASSWORD=12345678910
    privileged: true
容器日志：
wait for jms_mysql 172.19.0.2 ready
我尝试了
mysql8数据库
为utf8 | utf8_general_ci
mysql5.7
都报这个问题，是我哪里写错了吗？

**Comment by feng-bao** [comment]
我也碰到这个问题，怎么解决的
