### ISSUE TITLE
[Bug] 3.8升级3.9.1 web组件健康状态不正常

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12168]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
2.9.1

**浏览器版本**

**Bug 描述**
我两台jumpserver从3.8升级3.9.1 web组件健康状态都不正常
![image](https://github.com/jumpserver/jumpserver/assets/44529247/86909bfc-5f39-421b-bda6-bbd3ef9e16a9)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/2539ac8f-08bc-4eee-aaf2-a7ff0080fcd9)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by jym503558564** [comment]
无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/50d68f25-cc65-4296-9801-8caca89c7881)

**Comment by isyee2738** [comment]
我这边是从3.8.2升级3.9.1，jmsctl.sh 拉取的景像是jumpserver/core:v3.9.1，我看到最新的景像变成jumpserver/core-ce:v3.9.1，请问我要怎么做？

**Comment by isyee2738** [comment]
执行的命令是3.8.2的jmsctl upgrade v3.9.1

**Comment by jym503558564** [comment]
暂时无法复现，方便远程查看的话。可联系我们团队成员，帮忙远程看看。@wojiushixiaobai

**Comment by ryswork1993** [comment]
先这样吧，虽然显示unhealthy，但是不影响使用，我有空升级2.9.2尝试一下

**Comment by jym503558564** [comment]
或者重启下服务看看，会不会正常。

**Comment by ryswork1993** [comment]
> 或者重启下服务看看，会不会正常。

重启过多次了没有解决，我两台独立的服务器升级后都是这个问题

**Comment by jym503558564** [comment]
好的，我们这边也再复现下。看能不能定位到问题。

**Comment by ttkanni** [comment]
> 好的，我们这边也再复现下。看能不能定位到问题。

从3.8.1升级到3.9.3，遇到同样的问题，jms_web显示unhealthy，但jumpserver使用暂无异常。

经过检查，发现启动jumpserver服务后，在/opt/jumpserver/nginx/data/logs的erro.log内会连续提示：
2023/11/30 09:11:00 [error] 75#75: *407 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/v1/users/profile/ HTTP/1.1", upstream: "http://192.168.250.2:8080/api/v1/users/profile/", host: "jumpserver.XXXXXXXX.com", referrer: "https://jumpserver..XXXXXXXX.com/luna/?_=1701088724387"

docker inspect jms_web后发现：
 "Health": {
                "Status": "unhealthy",
                "FailingStreak": 109,
                "Log": [
                    {
                        "Start": "2023-11-30T09:38:38.020629619+08:00",
                        "End": "2023-11-30T09:38:43.056658193+08:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (5s)"
                    },
                    {
                        "Start": "2023-11-30T09:38:53.060696834+08:00",
                        "End": "2023-11-30T09:38:58.096279438+08:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (5s)"
                    },

从历史日志内去查看3.8.1的erro.log，无此类错误提示。

有点疑问的是，erro.log打印的错误和jms_web health check url不一样 ???

**Comment by ttkanni** [comment]
> 容器无法访问 `jumpserver.XXXXXXXX.com` ？

jumpserver.XXXXXXXX.com是jumpserver堡垒机的公网域名，域名的解析指向的是Jumpserver所在的ECS EIP，这个域名很早就配置上了，之前的各个版本都没有这个报错问题。

比较奇怪的是，为什么从jms_web访问要去走公网域名？按理说应该内部服务之间互访就行咯。如果走公网域名，那岂不是自己走公网绕一圈访问自己？
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/installer/blob/dev/compose/docker-compose-web.yml#L28
```sh
在容器执行这条命令看看结果
```

**Comment by ttkanni** [comment]
> * https://github.com/jumpserver/installer/blob/dev/compose/docker-compose-web.yml#L28
> 
> ```shell
> # 在容器执行这条命令看看结果
> curl -k -fsL http://localhost:$HTTP_PORT/api/health/
> ```

root@jms_web:/opt# curl -k -fsL -v http://localhost:$HTTP_PORT/api/health/ 
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /api/health/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Server: nginx
< Date: Wed, 06 Dec 2023 09:49:57 GMT
< Content-Type: text/html
< Content-Length: 164
< Connection: keep-alive
< Location: https://jumpserver.xxxxx.com/api/health/
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Clear auth, redirects to port from 80 to 443Issue another request to this URL: 'https://jumpserver.xxxxx.com/api/health/'
*   Trying 39.111.232.244:443...
……
……

一直到timeout。

**Comment by wojiushixiaobai** [comment]
你可以手动修改 `health` 命令，改成你认为合适的即可。

**Comment by ttkanni** [comment]
> 你可以手动修改 `health check` 命令，改成你认为合适的即可。

建议考虑优化下这块的逻辑，health check的话主要还是检查容器服务是否正常，如果周转到域名这块的check，域名涉及WAF、安全组以及各种访问限制，不确定因素多，很容易达不到health check的预期结果。

**Comment by wojiushixiaobai** [comment]
有好处有坏处，临时先自己改下吧。
在单机或者网络不复杂的环境中能判断真实的连接情况，可以修改成监听内部端口，我们考虑下吧
