### ISSUE TITLE
[Bug] 升级3.9报错：core容器没有3.9.0与3.9.1

### ISSUE THREAD

**Issue by isyee2738** [jumpserver/jumpserver#12177]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.2 升级到v3.9.2

**Bug 描述**
jumpserver升级报错：
[+] Running 0/1
 ⠿ core Error                                                                                                                                                                                                   33.2s
Error response from daemon: manifest for jumpserver/core:v3.9.1 not found: manifest unknown: manifest unknown

hub.docker.com上面最新版本是3.8.2
![image](https://github.com/jumpserver/jumpserver/assets/54405304/0c48b222-369d-48b0-83f9-7900d7bc66c0)

**Comment by isyee2738** [comment]
我这边是从3.8.2升级3.9.1，jmsctl.sh 拉取的景像是jumpserver/core:v3.9.1，我看到最新的景像变成jumpserver/core-ce:v3.9.1，请问我要怎么做？
执行的命令是3.8.2的jmsctl upgrade v3.9.1

**Comment by wojiushixiaobai** [comment]
请勿篡改安装脚本，请按照官方文档的说明进行升级，每次升级必须下载对应版本的 installer 安装包，然后使用安装包进行升级。
