### ISSUE TITLE
[Bug] 在群晖中用docker启动的3.9.1和3.9.0统一报错

### ISSUE THREAD

**Issue by chensj923** [jumpserver/jumpserver#12172]
**JumpServer 版本( v3.9.1/v3.9.0)**

![image](https://github.com/jumpserver/jumpserver/assets/34698775/7224883a-50eb-4224-b05f-6528c7452626)

**Bug 描述**
jms_all镜像启动，外部mysql和外部redis。

**Bug 重现步骤(有截图更好)**
1.删除mysql原有数据库，然后重建，CREATE DATABASE jumpserver DEFAULT CHARSET utf8 COLLATE utf8_bin;。
2.配置容器运行参数，数据库用root用户登录
3.启动后日志报错

**Comment by jym503558564** [comment]
建议使用Linux部署

**Comment by wojiushixiaobai** [comment]
看了下问题，应该是由 `buildx` 构建引起的，我修复下。
请明天再试试更新镜像。

**Comment by wojiushixiaobai** [comment]
更新完毕，再试试
