### ISSUE TITLE
[Bug] windows server 2016 通过堡垒机复制文件，服务器会异常重启

### ISSUE THREAD

**Issue by GuoYingLong** [jumpserver/jumpserver#12173]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

![image](https://github.com/jumpserver/jumpserver/assets/40883280/d6784b09-3739-4ebe-b71c-9c1c8e3110e0)

**浏览器版本**
chrome 最新版本

**Bug 描述**
通过堡垒机复制文件，服务器会异常重启，服务器操作系统：windows server 2016

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/40883280/3cf4975e-0c6d-4d9b-982b-86a1978290b7)
![image](https://github.com/jumpserver/jumpserver/assets/40883280/8b21f38c-afcd-4b34-b7d8-0341ccce91b8)
![image](https://github.com/jumpserver/jumpserver/assets/40883280/421cef16-6ab6-4ba4-abf4-23a6c10a989a)

**Comment by jym503558564** [comment]
其他版本windows正常？只有windows server 2016 有这个问题？

**Comment by jym503558564** [comment]
无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/c2aa0420-2d20-4001-a578-59b9ceb8d7a0)

**Comment by GuoYingLong** [comment]
其他版本正常，好像只有一台机器，复制粘贴会重启，重装了windows server 2019，目前无法使用剪切板
