### ISSUE TITLE
[Question] 远程应用连接数据库错误

### ISSUE THREAD

**Issue by Happyhappyhappy23** [jumpserver/jumpserver#12176]
已经在数据库服务器上安装了2.7版本的pymysql，为什么测试连接还会报这个错呢？

>>> 任务准备阶段
>>> 开始执行任务

PLAY [all] *********************************************************************

TASK [Test MySQL connection] ***************************************************
fatal: [testdb2]: FAILED! => {"changed": false, "msg": "A MySQL module is required: for Python 2.7 either PyMySQL, or MySQL-python, or for Python 3.X mysqlclient or PyMySQL. Consider setting ansible_python_interpreter to use the intended Python version."}

**Comment by jym503558564** [comment]
什么版本

**Comment by jym503558564** [comment]
v3.9最新版本验证，无该问题。可升级进行测试

**Comment by Happyhappyhappy23** [comment]
> 什么版本

v3.8.1

**Comment by jym503558564** [comment]
是从3.7版本升级上来的吗？我们在3.7.2修复过： jms_web 容器缺少依赖导致的远程应用发布机拉起应用失败的问题。
如果是从旧版本升级上来，可能升级前就存在该问题。建议发布机重新部署看看。（重新部署前，先把发布机上原有的tinker配置文件等删除）

**Comment by Happyhappyhappy23** [comment]
> 是从3.7版本升级上来的吗？我们在3.7.2修复过： jms_web 容器缺少依赖导致的远程应用发布机拉起应用失败的问题。 如果是从旧版本升级上来，可能升级前就存在该问题。建议发布机重新部署看看。（重新部署前，先把发布机上原有的tinker配置文件等删除）

现在是3.9.2，没有这个问题了，非常感谢。
还有一个问题想问下，用docker compose部署的，mariadb=10.6，从docker进入mysql，用mysql -u root -p的方式能正常登录，但是从页面测试资产连接报错如下：
TASK [Test MySQL connection] ***************************************************
fatal: [testsql]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2003, \"Can't connect to MySQL server on '192.168.72.56' ([Errno 113] No route to host)\")"}

**Comment by BaiJiangJie** [comment]
应该是你的 MySQL 用户的权限没有开放外部访问。
