### ISSUE TITLE
[Bug] CONNECTION_TOKEN_EXPIRATION 設置無效, 數據庫連線有效時間只有 5 分鐘

### ISSUE THREAD

**Issue by benq-richard-cw-ting** [jumpserver/jumpserver#12175]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
- 3.8.1
- 3.9.1

**浏览器版本**
- Firefox 119.0.1

**Bug 描述**

`CONNECTION_TOKEN_EXPIRATION` 設置無效, 數據庫連線有效時間只有 5 分鐘
> Note: `3.6.4` 正常

**Bug 重现步骤(有截图更好)**
1. 在 `/opt/jumpserver/config/config.txt` 加入 `CONNECTION_TOKEN_EXPIRATION=3600`
2. 重啟 JumpServer 
3. 在 Web Terminal 中, 開啟一個 MySQL 資產連線 (Connect Method = DB Guide)
    - 畫面中 Databaseconnect info 的 Expire time 正確顯示 1 小時後的時間
4. 使用數據庫管理工具 adminer 及步驟 3 的資訊, 連線至數據庫
5. 使用數據庫管理工具 adminer IDLE 10 分鐘, 再進行 TABLE 查詢, 出現以下的錯誤

    ```bash
    2023-11-21 08:10:04 [ERRO] Get Connect token auth failed: POST http://core:8080/api/v1/authentication/super-connection-token/secret/ failed, get code: 403, {"detail":"连接令牌过期: 2023-11-21 08:02:49.062802+08:00","code":"permission_denied"}
    ```

**Comment by BaiJiangJie** [comment]
# Token 是否需要复用，因为机制问题必须设置为 true
CONNECTION_TOKEN_REUSABLE=true
# 表示复用 Token 的过期时间
CONNECTION_TOKEN_REUSABLE_EXPIRATION=3600

如果使用客户端方式连接的话，需要配置这两个参数。（建议升级到最新版本使用）

**Comment by benq-richard-cw-ting** [comment]
#### 新增下列參數到 `config.txt`

```bash
CONNECTION_TOKEN_REUSABLE=true
CONNECTION_TOKEN_REUSABLE_EXPIRATION=3600
```

#### 驗証版本

- 3.9.1 (數據庫連線有效時間成功延長至 1 小時)
- 3.10.0 (數據庫連線有效時間成功延長至 1 小時)

感謝幫忙!
