### ISSUE TITLE
应用发布机部署失败

### ISSUE THREAD

**Issue by xinxinzhao1212** [jumpserver/jumpserver#12187]
jumpserver 版本----- 3.9.1 
应用发布机负载状态---离线
应用发布机测试结果---- 成功，win 10 系统
![image](https://github.com/jumpserver/jumpserver/assets/32668515/f21c50d1-0d90-4ea2-b13a-f55357345c78)

账号列表：
![image](https://github.com/jumpserver/jumpserver/assets/32668515/f80049dd-d973-42e4-8158-ce8951317048)
远程应用：
![image](https://github.com/jumpserver/jumpserver/assets/32668515/afdc59ef-15fd-466f-9667-022e50b222c9)

发布机部署----失败
![image](https://github.com/jumpserver/jumpserver/assets/32668515/9324f6a9-1400-4dca-acdc-e3aa717d15f8)

**Comment by xinxinzhao1212** [comment]
any update?

**Comment by LeeEirc** [comment]
RemoteApp 只有 Windows server 版本才支持，建议使用 Windows 2016 或者 window 2019 当作发布机。

**Comment by xinxinzhao1212** [comment]
window 2023 版本目前可以支持吗？

**Comment by LeeEirc** [comment]
Windows 2022 经测试存在部分问题，2023 未做测试验证。
