### ISSUE TITLE
[Bug] 发送命令给所有ssh 终端还是使用不了

### ISSUE THREAD

**Issue by taoge1111** [jumpserver/jumpserver#12183]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

发送命令给所有ssh 终端还是使用不了

**Bug 

> 

> 重现步骤(有截图更好)**
![Snipaste_2023-11-22_14-33-26](https://github.com/jumpserver/jumpserver/assets/119826490/9e8b47e7-6091-4025-bde1-4025a60a9ae7)

**Comment by jym503558564** [comment]
1.现在可在这个命令行输入命令，保存为快捷命令。保存按钮在页面右下角
2.左下角有个切换图标，可切换到快捷命令，用户可选择要执行的快捷命令，且可选择是只在当前窗口执行还是所有窗口执行。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12221

v3.10 会优化。
