### ISSUE TITLE
[Bug] redis本地客户端连接，在调起客户端后未能自动连接

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#12181]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8.1

**浏览器版本**
null

**Bug 描述**
在本地安装Redis Desktop Manager客户端并配置正确的情况下，进行redis本地客户端连接，发现客户端正常被调用的情况下，未能进行redis的数据库连接操作

**Bug 重现步骤(有截图更好)**
见问题描述
![6fc1905baffb9dee42111a99d49b183](https://github.com/jumpserver/jumpserver/assets/92150453/95ae2ebc-c1df-443f-98d7-a7ab1073021e)

**Comment by BaiJiangJie** [comment]
目前不支持客户端拉起 RDM，因为 RDM 不支持命令方式的参数传递连接。

**Comment by Halo1236** [comment]
@sageonedream 试试这个版本 https://github.com/jumpserver/clients/releases/download/v2.1.0/JumpServer-Client-Installer-win-v2.1.0-x64.exe

**Comment by sageonedream** [comment]
> @sageonedream 试试这个版本 https://github.com/jumpserver/clients/releases/download/v2.1.0/JumpServer-Client-Installer-win-v2.1.0-x64.exe

好的
