### ISSUE TITLE
刷新大量日志 

### ISSUE THREAD

**Issue by SwitfSystem** [jumpserver/jumpserver#12190]
43.198.250.174 - - [22/Nov/2023:20:20:59 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/2.0" 401 70 "https://gxxx.mxxxxxxxxs.org/luna/?_=1700634797680" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [22/Nov/2023:20:20:59 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1" 401 70 "https://xxx.mxxxxxxxxs.org/luna/?_=1700634797680" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" "43.198.250.174"

本地使用 发现nginx出现大量以上日志

**Comment by jym503558564** [comment]
已知问题，待修复。

**Comment by jym503558564** [comment]
3.9.3已修复

**Comment by nanoguo** [comment]
社区版 4.1.0 也出现了这个问题，每分钟两三条
