### ISSUE TITLE
[Bug] 通过快捷命令批量执行，华为交换机出现报错 Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by gdongquan** [jumpserver/jumpserver#12191]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.1

**浏览器版本**
Google CHrome 118.0.5993.118

**Bug 描述**
通过快捷命令批量执行，华为交换机出现报错：Failed to connect to the host via ssh: Warning: Permanently added '10.10.2.15' (ECDSA) to the list of known hosts

**Bug 重现步骤(有截图更好)**
1. 作业中心 -> 快捷命令，勾选2台华为交换机
2. 选择对应的账号后，执行测试命令“display version”
3. 等到2台均超时后，提示报错。

**Comment by ryswork1993** [comment]
我的也是这样

**Comment by jym503558564** [comment]
感谢反馈，待修复。

**Comment by jym503558564** [comment]
和该Issues问题重复，暂时先关闭。https://github.com/jumpserver/jumpserver/issues/12362
