### ISSUE TITLE
[Bug] v3.8.2升级V3.9.2资产无法连接 v3.8.2升级V3.9.2资产加载很慢

### ISSUE THREAD

**Issue by xuhb-PRC** [jumpserver/jumpserver#12198]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

**Bug 描述**

v3.8.2升级V3.9.2资产无法连接
v3.8.2升级V3.9.2资产加载很慢

**Bug 重现步骤(有截图更好)**
1.![image](https://github.com/jumpserver/jumpserver/assets/151893643/a217a00e-9684-4e48-8a9e-170fb55607ce)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/31f14ef4-3cf9-4d58-bfe2-9dd481f9eadb)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/100a7b44-d5e8-4d3d-a91e-b24ad9a7270f)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/fc025ac5-484b-4f32-83ac-2373932768c1)

/koko/connect/?disableautohash=&token=30c90b18-2ad3-4007-a677-aac881f73c57&_=1700794697192
企业微信截图_17007948595463
企业微信截图_17007951498800

**Comment by ibuler** [comment]
没有道理啊，建议再观察观察，多提供一些信息，比如  哪个 api 比较慢， 浏览器 F12 - 网络 - 查看 api

**Comment by xuhb-PRC** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/151893643/af9c7ce2-ce15-48a0-a23a-624a13aa62ae)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/87ee641d-bc29-4283-938d-ad67692814eb)

**Comment by xuhb-PRC** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/151893643/af9c7ce2-ce15-48a0-a23a-624a13aa62ae)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/87ee641d-bc29-4283-938d-ad67692814eb)

**Comment by xuhb-PRC** [comment]
/koko/connect/?disableautohash=&token=30c90b18-2ad3-4007-a677-aac881f73c57&_=1700794697192
![企业微信截图_17007948595463](https://github.com/jumpserver/jumpserver/assets/151893643/ce88982c-88db-4292-80dc-c50eda18b4a9)
![企业微信截图_17007951498800](https://github.com/jumpserver/jumpserver/assets/151893643/303ced9d-9e2d-4c24-a760-404c890b50c7)

**Comment by xuhb-PRC** [comment]
> 没有道理啊，建议再观察观察，多提供一些信息，比如 哪个 api 比较慢， 浏览器 F12 - 网络 - 查看 api

麻烦老师看看

**Comment by LeeEirc** [comment]
看下 koko 的日志，`docker logs -f --tail=100 jms_koko` 是不是没成功启动。

**Comment by xuhb-PRC** [comment]
> 看下koko的日志，`docker logs -f --tail=100 jms_koko`并不是没成功启动。

![image](https://github.com/jumpserver/jumpserver/assets/151893643/40bf38f9-fe39-4859-a0e2-4579e0d60bf7)
![image](https://github.com/jumpserver/jumpserver/assets/151893643/cb0005fb-caee-4464-98a6-29d9883cae16)

**Comment by LeeEirc** [comment]
连接 koko 终端报错，可能是你负载的问题？是不是 nginx 的相关配置不正确？找找 nginx 的日志查看下链路。

**Comment by BaiJiangJie** [comment]
确认一下是不是你 Default 节点下的资产比较多？

@xuhb-PRC

**Comment by jym503558564** [comment]
v3.10.2-lts优化了大数据资产用户等性能问题。请升级至最新版本，进行测试。
