### ISSUE TITLE
升级到V3之后ldap用户与现有数据库用户在权限分配是否通用。

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#12192]
**请描述您的问题.**
目前用的数据库用户有很多权限分配的规则，打算将用户都统一和ldap用户导入之前用户登录用户名和原来数据库里面存有的用户名大多数一致。因为不太想动原来v2的权限分配规则，现在升级到V3之后如果用ldap用户这些相同用户名对应的权限分配规则。能和之前的数据库用户名对应起来关系吗？
 我们权限分配太多很复杂，如果动起来的话  容易动错。或者有什么其它方案能解决这个问题的。

**Comment by jym503558564** [comment]
v3 版本与 v2 版本存在一定的差异，如需 v2 版本升级至 v3 版本 [请先阅读此文档](https://kb.fit2cloud.com/?p=06638d69-f109-4333-b5bf-65b17b297ed9)

**Comment by ztskycn** [comment]
我这个问题有解吗，还是只能一个一个规则替换？

**Comment by jym503558564** [comment]
1.如果LDAP 上的用户和JUmpServer数据库用户同名，同步过来后，会将改用户名的来源变更为AD/LDAP。
2.原授权的规则，该同名用户也会存在。
3.用户所在的LDAP的组织单元，会自动创建AD 组,并加入该AD用户组，用户原有的JS 用户组不见了。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/b4002cff-193e-47b8-b60b-2ea9e9e608ae)
<img width="1450" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/ee7f5d3d-f396-4f1e-bb2b-364bdae2f249">
![image](https://github.com/jumpserver/jumpserver/assets/40739051/cbbaf4d9-f617-44b4-8f4c-33d2460f4567)
![image](https://github.com/jumpserver/jumpserver/assets/40739051/86b5d104-3a3a-4545-af00-b121e2ca4f48)

**Comment by ztskycn** [comment]
> 1.如果LDAP 上的用户和JumpServer数据库用户同名，同步过来后，会将改用户名的来源变更为AD/LDAP。 2.原授权的规则，该同名用户也会存在。 3.用户所在的LDAP的组织单元，会自动创建AD 组,并加入该AD用户组，用户原有的JS 用户组不见了。 4.关于授权，如果有授权用户组的情况，可以更改该用户组的名称和LDAP用户组一致，则也可实现你的需求 ![image](https://user-images.githubusercontent.com/40739051/285129118-b4002cff-193e-47b8-b60b-2ea9e9e608ae.png) <img alt="image" width="1450" src="https://user-images.githubusercontent.com/40739051/285129399-ee7f5d3d-f396-4f1e-bb2b-364bdae2f249.png"> ![image](https://user-images.githubusercontent.com/40739051/285129705-cbbaf4d9-f617-44b4-8f4c-33d2460f4567.png) ![image](https://user-images.githubusercontent.com/40739051/285129874-86b5d104-3a3a-4545-af00-b121e2ca4f48.png)

感谢用心回复。。。
我测试了一下跟您的说的情况基本一致，就是有个问题。我这边导入了相同的ldap账号之后，原来ldap账号的密码可以登录，同时原来数据库里面的密码也可以登录。

**Comment by jym503558564** [comment]
你可以开启：仅从用户来源登录
<img width="1433" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/6134679d-21b0-4515-8c7a-677e7006331d">

**Comment by ztskycn** [comment]
> 你可以开启：仅从用户来源登录 <img alt="image" width="1433" src="https://user-images.githubusercontent.com/40739051/285330092-6134679d-21b0-4515-8c7a-677e7006331d.png">

测试是可行的，谢谢

**Comment by ztskycn** [comment]
> 1.如果LDAP 上的用户和JumpServer数据库用户同名，同步过来后，会将该用户名的来源变更为AD/LDAP。
> 2.原授权的规则，该同名用户也会存在。
> 3.用户所在的LDAP的组织单元，会自动创建AD 组,并加入该AD用户组，用户原有的JS 用户组不见了。
> 4.关于授权，如果有授权用户组的情况，可以更改该用户组的名称和LDAP用户组一致，则也可实现你的需求

您这边提到的前面3条没有太大问题，关于第4条。我这边测试下来，在原来保存下来的用户组和关联用户策略。如果将LDAP里面的新组改为原来用户组的名字则需要将原来的用户组先删除或者改名。而删除或者改名之后，相关的策略就会删掉用户组或者将用户组的名字改名。没有办法新的LDAP组继承之前的关系，您要不帮忙验证下，看是否存在这个问题？

**Comment by BaiJiangJie** [comment]
不能删除原来的用户组，改名是可以的。

**Comment by ztskycn** [comment]
> 不能删除原来的用户组，改名是可以的。

想了一个目前我们遇到的这种场景应该是很普遍的啊，原来走的数据库这套认证体系。配置有一堆资产分配权限（基于用户组的）；如果将数据库改为LDAP认证。基于原来数据库里面用户组的资产分配规则都会有这个问题。没有办法直接钭分配规则里面的组和LDAP的组关联起来。。。
官方一般是怎么解决这种问题的呢？之前的资产分配权限规则，可能是几年积累下来的，不可能一个一个改的啊，改的话肯定会其它问题的。

目前我能想到的办法，就是将LDAP用户加到原来的数据库体系里面的用户组。但是不确定，会不会有其它问题。

**Comment by BaiJiangJie** [comment]
LDAP 用户的 username 和本地数据库用户的 username 一样的话，直接登录是没问题的。

资产授权规则都不需要修改。关于用户组的问题，也不需要处理。

**Comment by BaiJiangJie** [comment]
资产授权规则关联了用户，这一方面不用修改。

资产授权规则关联了用户组，这个情况如果原用户没有修改的话，也是不用动的。以前的用户还在对应的用户组中，新增加的用户放到以前的用户组就可以了。

**Comment by ztskycn** [comment]
> 资产授权规则关联了用户，这一方面不用修改。
> 
> 资产授权规则关联了用户组，这个情况如果原用户没有修改的话，也是不用动的。以前的用户还在对应的用户组中，新增加的用户放到以前的用户组就可以了。

新增的用户放到以前的用户组，这里的用户组不是原来数据库的用户组吗。这样会不会存在数据库和LDAP账号共存，这样不会有问题吗。

如果是这样的话，我就原来的用户组不做处理了。LDAP这里就不用用户组的概念了，还是统一使用原来的用户组。
我在导入LDAP用户之前原来数据库里面的用户需要先删除，这样删除以后对应原来用户组里面的用户也就没有了。当LDAP里面的同名用户名导入进来之后，会自动添加到原来的用户组里面吗？（我们原来测试是需要手动添加的） 麻烦帮忙也确认一下。
谢谢。

**Comment by BaiJiangJie** [comment]
不是，理解有误。

**Comment by BaiJiangJie** [comment]
会议已沟通，先验证一下。

核心：已存在（已授权）的用户和用户组都不要删除。

**Comment by ztskycn** [comment]
谢谢，已沟通。空了，我来测试下。

**Comment by ztskycn** [comment]
> 会议已沟通，先验证一下。
> 
> 核心：已存在（已授权）的用户和用户组都不要删除。

我将线上数据又导了一份下午测试了下，直接导入ldap用户的话（和数据库账号名同名）原来的数据库账号会自动被覆盖，反正我在用户列表里面是找不到原来的账号了，只有ldap的用户。而且原用户组里面也没有这个用户了。
同时，用这个用户登录的时候直接报错。以下：
![image](https://github.com/jumpserver/jumpserver/assets/11976391/fd7db8b9-b890-4c86-9b76-535c35057f39)
除了这个报错，也没有其它日志。

其它数据库用户登录正常。

**Comment by BaiJiangJie** [comment]
准备好导入 LDAP 用户之前的环境，到时候我们从旧的使用场景，迁移到新的使用场景这个过程，我们一起走一遍。看看会不会出现问题。

**Comment by ztskycn** [comment]
> 准备好导入 LDAP 用户之前的环境，到时候我们从旧的使用场景，迁移到新的使用场景这个过程，我们一起走一遍。看看会不会出现问题。

我这边准备好了，您方便了 告诉我。或者加我QQ

**Comment by BaiJiangJie** [comment]
好的，现在来看一下。

**Comment by BaiJiangJie** [comment]
白江杰 邀请您参加腾讯会议
会议主题：白江杰的快速会议
会议时间：2023/12/01 16:12-17:12 (GMT+08:00) 中国标准时间 - 北京

点击链接直接加入会议：
https://meeting.tencent.com/dm/5qHzkrHieMJe

#腾讯会议：176-887-439

复制该信息，打开手机腾讯会议即可参与

**Comment by BaiJiangJie** [comment]
经过调试，登录报错是因为 DN 用户没有填写密码导致的。

LDAP 同步用户时，会从当前不存在的用户组中移除。
