### ISSUE TITLE
使用网域网关管理服务器错误：kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by wenbc** [jumpserver/jumpserver#12195]
版本：3.9.1 
通过网域网关管理服务器，在资产列表 页面 中 点击网关管理的服务器 的 测试 出现错误：
Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host\r\nConnection closed by UNKNOWN port 65535

![image](https://github.com/jumpserver/jumpserver/assets/8147297/8563cc1e-e39b-49c3-aa5c-653df808848e)

配置的网域网关状态正常：
![image](https://github.com/jumpserver/jumpserver/assets/8147297/837654a8-c824-4c6b-8537-de8e79e2009a)

![image](https://github.com/jumpserver/jumpserver/assets/8147297/8ce24345-b3e9-4a22-82e6-4883cd1dc7e0)

我分别使用测试：
koko ssh 到网关服务器能正常登录（密码登录）
网关服务器上ssh登录到管理终端服务器也是能正常登录。（密码登录）

不知道是我配置的问题还是这个版本的bug？

**Comment by ibuler** [comment]
找个普通的 ssh server 试试，估计是 sshd 没有开启转发

**Comment by wenbc** [comment]
> 找个普通的 ssh 服务器尝试，估计是 sshd 没有开启转发



> 找个普通的 ssh server 试试，估计是 sshd 没有开启转发

应该网关服务器sshd没有开启转发的问题，因为我老版本v2.28.1 的jumpserver使用的就是这个网关，功能是正常的。难道jumpserver 3.X版本不支持这个网域连接了？

**Comment by wenbc** [comment]
> > 找个普通的 ssh 服务器尝试，估计是 sshd 没有开启转发
> 
> > 找个普通的 ssh server 试试，估计是 sshd 没有开启转发
> 
> 应该不是网关服务器sshd没有开启转发的问题，因为我老版本v2.28.1 的jumpserver使用的就是这个网关，功能是正常的。难道jumpserver 3.X版本不支持这个网域连接了？

而且也尝试了从koko 容器内发起ssh，能ssh到网关服务器，然后网关服务器也能ssh到需要管理的服务器。

**Comment by wenbc** [comment]
问题解决，直接赋权限是可以登录，但是好像是不能进行 账号推送。我看了2.X版本功能也是一样。
