### ISSUE TITLE
[Bug] 堡垒机在大资产的情况下，存在慢 SQL 查询

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#12208]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.8

**浏览器版本**
谷歌浏览器

**Bug 描述**
客户资产数 6w ， 堡垒机出现卡顿。其中执行最慢的SQL 是获取 default 组织下的资产数，执行时间超过 2s 。

详情见附件，这是 DBA 抓出来的慢 SQL。 
[慢日志统计.csv](https://github.com/jumpserver/jumpserver/files/13473147/default.csv)

以下是建议的SQL优化：
优化前：
SELECT COUNT(*) FROM (SELECT DISTINCT `assets_asset`.`created_by` AS `col1`, `assets_asset`.`updated_by` AS `col2`, `assets_asset`.`date_created` AS `col3`, `assets_asset`.`date_updated` AS `col4`, `assets_asset`.`comment` AS `col5`, `assets_asset`.`id` AS `col6`, `assets_asset`.`org_id` AS `col7`, `assets_asset`.`connectivity` AS `col8`, `assets_asset`.`date_verified` AS `col9`, `assets_asset`.`name` AS `col10`, `assets_asset`.`address` AS `col11`, `assets_asset`.`platform_id` AS `col12`, `assets_asset`.`domain_id` AS `col13`, `assets_asset`.`is_active` AS `col14`, `assets_asset`.`gathered_info` AS `col15`, `assets_asset`.`custom_info` AS `col16` FROM `assets_asset` INNER JOIN `assets_asset_nodes` ON (`assets_asset`.`id` = `assets_asset_nodes`.`asset_id`) INNER JOIN `assets_node` ON (`assets_asset_nodes`.`node_id` = `assets_node`.`id`) WHERE (`assets_asset`.`org_id` = '00000000-0000-0000-0000-000000000002' AND (`assets_node`.`key` LIKE BINARY '1:%' OR `assets_node`.`key` = '1'))) subquery
优化后：
SELECT COUNT(*)
FROM assets_asset
WHERE org_id = '00000000-0000-0000-0000-000000000002'
AND EXISTS (
    SELECT 1 FROM assets_asset_nodes 
    INNER JOIN assets_node ON assets_asset_nodes.node_id = assets_node.id
    WHERE assets_asset_nodes.asset_id = assets_asset.id
    AND (`assets_node`.`key` LIKE BINARY '1:%' OR `assets_node`.`key` = '1')
);
![image](https://github.com/jumpserver/jumpserver/assets/30264974/ccee6da6-d5f1-4671-b977-d92ce280347e)

**Comment by ibuler** [comment]
已优化完成
