### ISSUE TITLE
[Feature] Can you change notice for expire license RDP ?

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#12205]
Hi,

In case, user remote to server which expire license RDP, user only receive notice: "The remote desktop server does not appear to exist, or cannot be reached over the network.". It makes it difficult for administrators to find the cause and fix it.

![image](https://github.com/jumpserver/jumpserver/assets/75791054/35e5e232-a7f9-4ea5-b1bb-82303f277a15)

So, Can you change notice for expire license RDP such as: License RDP of server is expired ?

Thank you.

**Comment by BaiJiangJie** [comment]
We need to confirm whether we can capture the corresponding error information. The previous survey results were not available.

**Comment by LeeEirc** [comment]
We were unable to retrieve any further error messages from the Windows RDP server after its license expired.
