### ISSUE TITLE
[Question] 本机的命令行无法通过ssh访问

### ISSUE THREAD

**Issue by egoisz** [jumpserver/jumpserver#12200]
**请描述您的问题.**
本机的命令行无法通过ssh直接访问jumpserver，但是本机可以页面正常登录jumpserver，且其他主机可以ssh访问jumpserver，本机ip也不在黑名单中。
通过ssh直接访问jumpserver 返回报错是 Access denied

**Comment by jym503558564** [comment]
哪个版本，我们在3.8.2和3.9版本修复过类似的问题

**Comment by egoisz** [comment]
> 哪个版本，我们在3.8.2和3.9版本修复过类似的问题

v2.20.3，这个版本，jms_koko服务有以下报错，
2023-11-27 07:58:24 [ERRO] Post "http://core:8080/api/v1/terminal/terminals/status/": dial tcp: lookup core on 127.0.0.11:53: server misbehaving
重启了jms_core组件，解决了
