### ISSUE TITLE
[Bug] V3.7.1升级3.8.0之后web控制台登录页面不能正常显示

### ISSUE THREAD

**Issue by 9792799** [jumpserver/jumpserver#12206]
**Bug 描述**

V3.7.1升级3.8.0之后web控制台登录页面不能正常显示

**Bug现象(有截图更好)**
1.升级之后主服务都显示正常,但是web端口都不通。
<img width="1368" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/530a32f5-1532-43a6-a507-620e53ec0d61">
<img width="950" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/cd0e702e-ecd1-4c32-8066-2a58638c9e27">
<img width="1348" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/b0f6d54b-c37e-4121-affb-0b402f4b650d">

<img width="753" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/726116f1-1eb2-4cb7-9628-fc5e157fa0cd">

2.检查主服务配置文件ok。
<img width="1417" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/74a786cc-0b54-4870-abb2-f48cc79eafa2">

**Comment by ibuler** [comment]
重启一下 Docker 试试

**Comment by 9792799** [comment]
> 重启一下 Docker 试试

jmsctl restart 问题依旧。

**Comment by ibuler** [comment]
去部署机上，telnet localhost 80 试试

**Comment by 9792799** [comment]
> 去部署机上，telnet localhost 80 试试

<img width="743" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/9e6d58f4-d476-4ec4-91c3-54d5071411ab">

**Comment by BaiJiangJie** [comment]
测试用 localhost 不用 IP。

**Comment by 9792799** [comment]
> 测试用 localhost 不用 IP。

<img width="656" alt="image" src="https://github.com/jumpserver/jumpserver/assets/151818472/c1b6e1e9-fa67-460c-8ce6-e5c8034d560d">

**Comment by BaiJiangJie** [comment]
localhost 可以，从网络层面检查一下你的 IP。

**Comment by 9792799** [comment]
> 不是服务本身的问题，localhost 可以，从网络层面检查一下你的 IP。
测试网络可达网络本身就没问题，3.7.1的基础上升级的3.8.2怎么可能升级之后网络就不可达。其实原因在于我使用的是默认的nginx ssl服务，并没有使用Nginx代理，也就是说你们并没有做过默认配置的3.8.2升级测试。建议你们做好测试和kb。
