### ISSUE TITLE
[Bug] 应用发布机部署成功后，生成的账号未能自动添加至Remote Desktop Users组(非必现)

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#12214]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.9.1

**浏览器版本**
104.0.5112.81

**Bug 描述**
基于windows server2016机器做应用发布机部署，部署成功并生成账号激活成功后，才看发布机中的js_xx、jms_xxx账号均未归属至Remote Desktop Users组中，导致无法连接上发布机，需手动添加至Remote Desktop Users组中才行。
(备注：winrm、ssh方式均尝试过。客户之前找的一台windows server2016机器是可以正常添加账号至Remote Desktop Users组)

**Bug 重现步骤(有截图更好)**
见问题描述
![282e1789759434329abf4fdf959d837](https://github.com/jumpserver/jumpserver/assets/92150453/4796a085-06b5-41d4-8a59-af8ecc9b017d)
![32f496e1b9f26e4adaca7585951f381](https://github.com/jumpserver/jumpserver/assets/92150453/ec3f1e5a-473d-481d-8386-8308a3bcb755)

**Comment by jym503558564** [comment]
rsop.msc 
查看用户都这是了哪些策略，我们对应配置下，再复现看看。暂时我们全新的windows server 2016无法复现问题。需要用户提供更多的信息。

**Comment by BaiJiangJie** [comment]
确认一下如何复现，Reopen issue！
