### ISSUE TITLE
[Bug] OIDC 无法配置

### ISSUE THREAD

**Issue by HsunGong** [jumpserver/jumpserver#12219]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.9.2

**浏览器版本**

Chrome

**Bug 描述**

1. 使用config.txt配置，无法读取到相应的config，参考 https://docs.jumpserver.org/zh/master/admin-guide/authentication/openid/#3
2. OIDC的配置界面无法找到，参考 https://blog.csdn.net/JiangLaoBi/article/details/130127204

**Bug 重现步骤(有截图更好)**

1. 使用docker搭建，其他事情都没做  `https://github.com/jumpserver/Dockerfile`

<img width="403" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32933986/4d731eb3-59d6-469f-a5bc-08ca01f1ff18">

**Comment by ibuler** [comment]
企业版功能

**Comment by liuyongqing1** [comment]
那如何我们已经在2.28上已经配置成功了。我目前看升级到3.10.1还可以使用，但是如果需要修改相关地址。还能用吗？

**Comment by liuyongqing1** [comment]
@ibuler
