### ISSUE TITLE
[Bug] v3.8.2升级V3.9.2资产无法连接    后再升级V3.9.3 windows资产无法连接提示 socketerr

### ISSUE THREAD

**Issue by xuhb-PRC** [jumpserver/jumpserver#12224]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
之前v3.8.2升级V3.9.2资产无法连接   
今天再升级V3.9.3 windows资产无法连接提示 socketerror，linux 资源可以正常访问（之前连接类似秒连，现在延迟很大，特别是 经过 网域网关的，要等很久）

**Bug 重现步骤(有截图更好)**
1.
![企业微信截图_17012388806456](https://github.com/jumpserver/jumpserver/assets/151893643/2d13aa75-668e-4336-ac0f-5bfe4071f0d1)

2.
![企业微信截图_17012389837580](https://github.com/jumpserver/jumpserver/assets/151893643/e38bca8f-a287-4566-bda0-284a0f73b539)

**Comment by BaiJiangJie** [comment]
连接时，看一下 Lion 组件的日志。

**Comment by xuhb-PRC** [comment]
> 连接时，看一下 Lion 组件的日志。

![image](https://github.com/jumpserver/jumpserver/assets/151893643/efa93330-69a6-4703-8a78-1b92e469a1da)

**Comment by BaiJiangJie** [comment]
看一下 guacd.log 的文件内容，开一下 DEBUG 模式。

**Comment by BaiJiangJie** [comment]
建议升级到最新版本使用。
