### ISSUE TITLE
[Bug] 禁用root直接ssh登录，sudo免密账号修改root账号密码导致root密码在JMS平台丢失

### ISSUE THREAD

**Issue by chengfeiyue** [jumpserver/jumpserver#12223]
版本：v3.8.2
第一步、创建一个sudo 用户，sudo_user  :useradd -u 7002 sudo_user 
第二步、#编辑/etc/sudoers配置文件： sudo_user ALL=(ALL)      NOPASSWD: ALL
<img width="415" alt="image" src="https://github.com/jumpserver/jumpserver/assets/49852751/4537fb99-dda4-4fc8-99f0-9e1c757a07e5">
第三步、禁用root直接登录:sudo vi /etc/ssh/sshd_config 、PermitRootLogin no、重启sshd 服务使配置生效
第四步、在jms 账号列表分别添加账号 root和sudo_user (选择特权账号)
第五步、创建账号改密。
第六步、查看执行结果、 从日志中看到root账号的密码被修改了，但是在验证root 账号密码时候，因为root不允许直接登录所以，ansible日志报错。这个时候去查看 root账号的密码没有发生变化。但是操作系统内的root 密码已经改掉了。密码丢失
<img width="910" alt="image" src="https://github.com/jumpserver/jumpserver/assets/49852751/100a4593-7c08-4948-8bff-ca7588b4d903">

**Comment by BaiJiangJie** [comment]
我记得修复过一次，禁用root用户登录的情况。

@jym503558564 

v3.9 上验证一下，或者联系飞跃看一下环境。

**Comment by chengfeiyue** [comment]
OK，空了再V3.9验证一下，验证完再这里反馈

**Comment by jym503558564** [comment]
v3.9.3版本测试了。实际上我们在v3.8.1也修复过了。

**Comment by chengfeiyue** [comment]
经过沟通总结为下面两点：
1、使用问题：root账号我未选择切换自“sudo_user”，有选择切换自“sudo_user” 改密正常
2、偶然出现截图中的结果：未选择切换自“sudo_user”，出现截图中的现象。在V3.8.2，V3.9.2，V3.9.3均有该现象出现。正常不应该出现。

**Comment by BaiJiangJie** [comment]
那最终的结果问题还存在吗？

**Comment by chengfeiyue** [comment]
存在，偶现

**Comment by BaiJiangJie** [comment]
那应该还有问题，找到稳定复现方式后，联系育敏再看一下。

**Comment by chengfeiyue** [comment]
昨天和育敏一起看过了。同一个环境V3.9.3。相同的操作，执行账号改密出现不同的结果。
<img width="1439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/49852751/f11beb73-5ace-4104-b70f-6320c8b1c0ff">
