### ISSUE TITLE
求优化：关于发送文本到所有SSH终端的问题 

### ISSUE THREAD

**Issue by jiangshenyang** [jumpserver/jumpserver#12221]
1、现在使用发送文本到所有SSH终端，不生效，只会给当前终端发送命令文本，其他终端没有收到文本命令
【带水印，还是不贴图了】
2、日常执行命令，并不是所有的都可以添加快捷命令的方式发送，一个“ls”也要建快捷命令才能给所有终端同时发送命令吗？
【带水印，还是不贴图了】
3、建议参考下SecureCRT，默认就是给所有的会话发送文本命令，快捷命令只是作为一个补充，而不是强制的选项
![image](https://github.com/jumpserver/jumpserver/assets/29298552/9082e06e-bc1b-42f6-9c1c-9838e0c67c18)

**Comment by ryswork1993** [comment]
+1

**Comment by BaiJiangJie** [comment]
嗯，v3.10 优化一下，快捷命令和手动输入，均支持：仅发送当前会话 和 发送到所有活跃会话。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
