### ISSUE TITLE
升级jumpserver，coco报错

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1222]
[简述你的问题]

##### 使用版本
[Version 1.2.0-2 GPLv2]

##### 问题复现步骤
升级jumpserver
git pull && pip install -r requirements/requirements.txt
报错：
jumpserver-python-sdk 0.0.34 has requirement paramiko==2.4.0s, but you'll have paramiko 2.4.0 which is incompatible.
jumpserver-python-sdk 0.0.34 has requirement pyte==0.5.2, but you'll have pyte 0.7.0 which is incompatible.
jumpserver-python-sdk 0.0.34 has requirement pytz==2017.2, but you'll have pytz 2017.3 which is incompatible.
jms-storage 0.0.13 has requirement boto3==1.6.5, but you'll have boto3 1.6.4 which is incompatible.
jms-storage 0.0.13 has requirement botocore==1.9.5, but you'll have botocore 1.9.4 which is incompatible.
jms-storage 0.0.13 has requirement certifi==2018.1.18, but you'll have certifi 2017.11.5 which is incompatible.
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

[注:] 完成后请关闭 issue

**Comment by qianghong000** [comment]
升级coco
cd requirements &&pip install -r requirements.txt
报错：
  Could not find a version that satisfies the requirement jumpserver-python-sdk==0.0.41 (from -r requirements.txt (line 23)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31, 0.0.32, 0.0.33, 0.0.34, 0.0.35, 0.0.36, 0.0.37, 0.0.38, 0.0.39, 0.0.40)
No matching distribution found for jumpserver-python-sdk==0.0.41 (from -r requirements.txt (line 23))
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by qianghong000** [comment]
pip install --upgrade pip
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already up-to-date: pip in /opt/py3/lib/python3.6/site-packages (10.0.0)
jumpserver-python-sdk 0.0.34 has requirement paramiko==2.4.0s, but you'll have paramiko 2.4.0 which is incompatible.
jumpserver-python-sdk 0.0.34 has requirement pyte==0.5.2, but you'll have pyte 0.7.0 which is incompatible.
jumpserver-python-sdk 0.0.34 has requirement pytz==2017.2, but you'll have pytz 2017.3 which is incompatible.
jms-storage 0.0.13 has requirement boto3==1.6.5, but you'll have boto3 1.6.4 which is incompatible.
jms-storage 0.0.13 has requirement botocore==1.9.5, but you'll have botocore 1.9.4 which is incompatible.
jms-storage 0.0.13 has requirement certifi==2018.1.18, but you'll have certifi 2017.11.5 which is incompatible.
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by ibuler** [comment]
https://pypi.org/project/jumpserver-python-sdk/

请不要使用阿里云的镜像

**Comment by qianghong000** [comment]
请问怎么切换

**Comment by gengkeye** [comment]
>请问怎么切换

参考链接：https://www.jianshu.com/p/3621780417be

**Comment by qianghong000** [comment]
我使用pip -i 指定国内源都不行

**Comment by ibuler** [comment]
不要指定源，因为国内源是镜像，同步可能会晚几天  -i https://pypi.org/simple

**Comment by qianghong000** [comment]
![jms](https://user-images.githubusercontent.com/9443696/39037956-ad6615c6-44b4-11e8-8bfd-d4024bd5ed48.png)

**Comment by qianghong000** [comment]
最后这段红色字体 有影响吗

**Comment by wojiushixiaobai** [comment]
@qianghong000 无影响，报错会提示error，红色的这个问题群主老哥最近会处理掉。

**Comment by qianghong000** [comment]
好的 谢谢
