### ISSUE TITLE
[Question]  请问v3.8.2 版本的k8s集群连接是否支持网域功能

### ISSUE THREAD

**Issue by shalou93** [jumpserver/jumpserver#12231]
**请描述您的问题.**
看了下资产支持，k8s等云服务好像是没有找到网域的选项

**Comment by BaiJiangJie** [comment]
<img width="1335" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/168a95a7-76bb-498e-bd5d-6faf82d09191">

应该可以，最新版本是肯定支持。
