### ISSUE TITLE
[Feature] web终端的web资产问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12230]
**请描述您的需求或者改进建议.**
1、当web终端同时打开多个web资产，全屏显示的时候将所有的web资产都在全屏显示，而不是只能全屏一个web资产
2、web终端右键资产新窗口打开，分辨率很不好
![image](https://github.com/jumpserver/jumpserver/assets/44529247/6dac43b1-9aac-4f41-b6e7-5c3a5a4b9601)

**Comment by BaiJiangJie** [comment]
1. 全屏显示是这样的，直接全屏当前页面。单独会话全屏的话就是右击新窗口打开。
2. 改一下分辨率。

**Comment by ryswork1993** [comment]
> > 1. 全屏显示是这样的，直接全屏当前页面。单独会话全屏的话就是右击新窗口打开。
> >    不能一次将多个窗口全屏吗，想多个资产全屏的话，只能把每个想全屏的右键资产吗
> >    ![image](https://private-user-images.githubusercontent.com/44529247/286915186-c5efa68e-8049-4da8-aae9-699d75f1d8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDQ2NDcsIm5iZiI6MTcwMTM0NDM0NywicGF0aCI6Ii80NDUyOTI0Ny8yODY5MTUxODYtYzVlZmE2OGUtODA0OS00ZGE4LWFhZTktNjk5ZDc1ZjFkOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDc5ZDU3OGM2NTFhYjA3MGVlMWEyNWMzZDljOGE4Yzc2MTc2ZWJiMzIxMmE1MGMwZjIzYjk0MWJmMmEzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KMFEMLCgyQj5uoZMBxOC3In7jL3qYCVRQkCaxighBPQ)
> 
> > 2. 改一下分辨率。
> >    改应用发布机的分辨率还是jumpserver的内置分辨率，下面是jumpserver分辨率设置和右键web资产开启新窗口后的登陆后界面，看不到全部内容
> >    ![image](https://private-user-images.githubusercontent.com/44529247/286916145-d2e85908-71a2-43fd-a46d-c12a47acd022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDQ2NDcsIm5iZiI6MTcwMTM0NDM0NywicGF0aCI6Ii80NDUyOTI0Ny8yODY5MTYxNDUtZDJlODU5MDgtNzFhMi00M2ZkLWE0NmQtYzEyYTQ3YWNkMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhODBkZjYzM2Q1ZGU3N2M1YWY0ODRhYTQ5M2U5YTg3ZDNhODNhN2Q0ZDRiNjRkODRjODEyNjEwNGQ1YTgzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7G_j8vwOKhHF7aRJqJ_r5LFvtTUcEBGmv0MLczAM2ZA)
> >    ![image](https://private-user-images.githubusercontent.com/44529247/286916169-f0b31bd5-6e24-4daf-a634-c21a5ab3870e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDQ2NDcsIm5iZiI6MTcwMTM0NDM0NywicGF0aCI6Ii80NDUyOTI0Ny8yODY5MTYxNjktZjBiMzFiZDUtNmUyNC00ZGFmLWE2MzQtYzIxYTVhYjM4NzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExMzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYzc1N2VmNWEwNGViZDg5YzNkNmE1ZTM3NzlmMmI0ZjczYjJjOWRlN2E4YmViYTE1YTFhNjFmNWZhNTc4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YbANkcaU38GANdofgQK_8MGSQzr72Sb3SDHmUkVtew4)

右键web资产打开新界面，显示不全的原因找到了，如果在资产登陆成功之前不要立马点击浏览器的最大化，要不然会显示不全
在下面这个小窗口资产登陆之后，再点击标红的位置，资产内容就能显示全部了
![image](https://github.com/jumpserver/jumpserver/assets/44529247/95a5cfd7-a393-49d1-b85e-f632a0826a10)
