### ISSUE TITLE
[Feature] 授权管理

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12237]
**请描述您的需求或者改进建议.**
在授权管理里未勾选的功能，能不能让用户也看不到啊
![image](https://github.com/jumpserver/jumpserver/assets/44529247/08775f3b-24bf-4577-af68-c15b21142d18)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/fc3b55be-2c9e-45b2-8b06-7bc24d6f51ad)

**Comment by BaiJiangJie** [comment]
文件管理功能是否有权限，是否可以查看，可以通过 RBAC 角色进行控制。

<img width="689" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/fb02f31c-e1dd-42ea-9e80-37a7f6a2f7d7">

企业版功能支持。
