### ISSUE TITLE
[Bug] 账号模板密码修改后，密码正确，无法登录资产

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12238]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
2.9.3

**浏览器版本**

**Bug 描述**
账号模板密码正确的，却登录资产失败，不通过堡垒机，登录是正常的，我检查好几遍账号模板密码和我不通过堡垒机登录密码一样的

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by jym503558564** [comment]
账号模版详情页-账号列表：点击同步，可将最新密码同步到关联资产的模版账号密码
<img width="1419" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/a68a587b-fb75-4706-a851-444dee84e49e">

**Comment by ryswork1993** [comment]
某个资产密码修改后，我修改完模板密码，还需要手动将账号列表的账号删除掉，然后重新授权才可以
1、修改模板密码，这个时候资产是无法用这个新密码，重新授权也不行
![image](https://github.com/jumpserver/jumpserver/assets/44529247/fa0044da-50e8-40a2-81da-cbafd72dd7a2)
2、需要将账号列表里的账号删除掉，因为模板里的密码修改后不会自动同步到这里
![image](https://github.com/jumpserver/jumpserver/assets/44529247/2c454a96-455d-4a36-b3f6-a876b0bd9f2b)
3、前两不不成功的话，就重新授权

这样才能变更资产密码成功，有点不合理吧，能不能修改模板密码之后自动同步到账号列表里的密码

**Comment by BaiJiangJie** [comment]
<img width="2552" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/52a22dd9-a831-4639-979f-84e50ced93c5">

修改完账号模版密码后，详情中同步一下。
