### ISSUE TITLE
[Feature] 管理员分级需求

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12233]
**请描述您的需求或者改进建议.**
正常情况下1级管理员可以管理所有资产，不同小组为2级管理员，不同小组之间要管理的资产不同，需要给不同的小组管理员授权改小组的资产，然后由小组管理员进行资产权限的管理

**Comment by ryswork1993** [comment]
> **请描述您的需求或者改进建议.** 正常情况下1级管理员可以管理所有资产，不同小组为2级管理员，不同小组之间要管理的资产不同，需要给不同的小组管理员授权改小组的资产，然后由小组管理员进行资产权限和授权的分配
管理

**Comment by BaiJiangJie** [comment]
企业版，有组织功能。

每个组织下的资源是隔离的，组织管理员只能管理当前组织下的资源。

应该可以满足你的需求。
