### ISSUE TITLE
[Bug] 连接Windows 2003/xp、win7资产的时候会偶尔黑屏

### ISSUE THREAD

**Issue by yanxu4780** [jumpserver/jumpserver#12235]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**
EDGE：119.0.2151.97

**Bug 描述**
连接Windows 2003/xp、win7资产的时候会偶尔黑屏，只要打开资源管理器就可能会直接黑屏，但是用右键刷新或移动窗口之后，会显示一部分画面。重新连接资产后正常。显卡驱动是默认的。

**Bug 重现步骤(有截图更好)**
1.正常连接资产
2.打开我的电脑
3.资产黑屏
4.重新连接资产就正常，再打开我的电脑依旧黑屏。其他资产遇到过相同情况，不是单一资产的问题。
4.连接Windows 2003/xp、win7资产都会有一样的问题。而win10/2022系统暂未发现。印象中，3.8以前版本未遇到这个问题，但不一定对。
![1701393305400](https://github.com/jumpserver/jumpserver/assets/5827407/fb34de5f-936f-4a6c-8e5e-2e59ccfc2397)

**Comment by yanxu4780** [comment]
![1701393760142](https://github.com/jumpserver/jumpserver/assets/5827407/79ba999d-9332-4d03-8a31-1921ce6b7977)

**Comment by yanxu4780** [comment]
我在Firefox浏览器中未发现这个问题，只有在EDGE和Chrome浏览器最新版本中有这个问题。EDGE和Chrome老版本暂未测试。Firefox最新版是没问题的，不会黑屏。

**Comment by yanxu4780** [comment]
测试了一下117版本的Chrome内核，未出现这个问题。可能只有118和119版本开始，就出现了这个问题。Firefox 120版本也是正常的，未出现这个黑屏问题。

**Comment by ibuler** [comment]
感谢反馈，117 版本的 chrome 默认开启了硬件加速吗 ？

**Comment by yanxu4780** [comment]
> 感谢反馈，117 版本的 chrome 默认开启了硬件加速吗 ？

开了的，119版本在Windows还有mac上都会出现这个黑屏的问题，应该不是显卡或者系统的问题。

**Comment by yanxu4780** [comment]
119版本关闭硬件加速之后就正常了，问题应该出在硬件加速那里

**Comment by BaiJiangJie** [comment]
嗯，所以现在想了解在 117 版本里 Chrome 是否开启了硬件加速，你能帮忙确认一下吗？

**Comment by yanxu4780** [comment]
> 嗯，所以现在想了解在 117 版本里 Chrome 是否开启了硬件加速，如果 117 默认也开启了，为什么 117 的时候没有出现黑屏呢，是比较奇怪的一点。

确实开启了，不知道为什么，比较奇怪

**Comment by BaiJiangJie** [comment]
估计是 Chrome 118+ 做了一些底层优化，目前没有别的解决方案，只能先关闭硬件加速解决。

**Comment by yanxu4780** [comment]
下载121测试版试了下，开启硬件加速之后不会黑屏。稳定版估计要等更新了。
