### ISSUE TITLE
内网部署，如何管理阿里云上的windows资产

### ISSUE THREAD

**Issue by x84044907** [jumpserver/jumpserver#1223]
[简述你的问题]
目前在企业内网部署，连接内网windows服务器没问题，但是无法连接上阿里云的windows资产。（通过服务器公网IP）
目前混合云架构用的比较多，jumpserver一般部署在企业私有云内，有没有方法能同时管理内网与外网的windows服务器？
##### 使用版本
jumpserver 1.0.0

##### 问题复现步骤
1.在内网部署jumpserver，连接内网windows服务器，没问题
2. 添加阿里云资产，填入相应公网IP，连接不上

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
跨网络时请使用网域功能，可以在网域中设置一个或多个网关，这样登录域下资产时会通过网关跳转。
之前：
    Jumpserver --网络可达--> 资产
现在：
    Jumpserver --网络可达--> 网关 --网络可--> 资产

ssh的网关是一个普通的 ssh server，开启了跳转功能即可
rdp的网关是windows上的一个服务，叫rdp gateway，请了解

**Comment by x84044907** [comment]
多谢指导，我先去测试一下，希望成功

**Comment by dantin-s** [comment]
@ibuler 请教下 ssh 网关如何设置，有相关的指导资料吗，感谢！
