### ISSUE TITLE
[Question] 从V2.12.1升级到v3.9.3jms_web容器启动报错

### ISSUE THREAD

**Issue by hu16725434** [jumpserver/jumpserver#12232]
从V2.12.1升级到v3.9.3其他组件容器都正常启动，只有jms_web启动失败，启动容器日志如下：

Starting periodic command scheduler: cron.
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] unknown directive "sticky" in /etc/nginx/conf.d/https_server.conf:3
![微信图片_20231130212718](https://github.com/jumpserver/jumpserver/assets/117888727/910c08ef-484e-4dee-9e08-c42b26e044aa)

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/installer/blob/dev/scripts/7_upgrade.sh#L68

升级脚本应该正确处理了才对，你是自己改了东西？手动把 `/opt/jumpserver/config/nginx/lb_http_server.conf` 关于 `sticky` 的内容注释掉

**Comment by hu16725434** [comment]
升级的脚本我没改过呢，不过V2.x的版本不是我安装，我对了下配置文件
https://docs.jumpserver.org/zh/v3/installation/proxy/#1-nginx-ssl 跟这个文档的是一样的
注释了之后jms_web容器变为unhealthy了

**Comment by hu16725434** [comment]
upstream http_server {
  sticky name=jms_route;
  server nginx:80;
  # server HOST2:80;  # 多节点
}
改为

upstream http_server {
  #sticky name=jms_route;
  server web:80;
  # server HOST2:80;  # 多节点
}
就正常了！谢谢
