### ISSUE TITLE
[Bug] jumpserver 在创建同名账号登录资产的时候，如何将ssh-key放到对应的home下面？这样能够自动登录而不用输入密码

### ISSUE THREAD

**Issue by HsunGong** [jumpserver/jumpserver#12248]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.9.2

**Bug 描述**

jumpserver 在创建同名账号登录资产的时候，如何将ssh-key放到对应的home下面？这样能够自动登录而不用输入密码。

每次登录资产，无法正确读取上传到jumpserver的pub-key，使得必须输入密码才能登陆。
同时web端没有使用pub-key登录的选项，只有输入密码的选项

**Bug 重现步骤(有截图更好)**

资产已经配置sssd+ldap登录
jumpserver使用ldap登录和同步账户，账户已经配置pub-key

1. 直接用 ssh user@jumpserver 可以无密码登录
2. 登录后选择资产必须输入ldap密码，无法继续使用pub-key
3. 使用 ssh user@user@jumpserver@asset 一样需要使用密码

<img width="575" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32933986/8943a7d7-356f-4789-a185-f10d800e8f0a">

**Comment by BaiJiangJie** [comment]
登录资产的同名账号密码，和 LDAP 用户的密码一样吗？

**Comment by BaiJiangJie** [comment]
<img width="1729" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1f0d8874-b30b-445e-92f3-5845a49d6225">

有两种方式可以免使用同名账号免密登录。

1. 在资产中创建对应的账号，配置密钥认证并推送到资产。
2. 开启上图中的配置，并修改配置文件重启服务。（仅支持使用密码方式登录）
