### ISSUE TITLE
[Bug] 登录日志中IP地址显示问题

### ISSUE THREAD

**Issue by pengcheng820** [jumpserver/jumpserver#12246]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

之前安装的版本为3.7.1，于11月28日升级到3.9.2

升级后发现登录日志中，登录IP显示问题

红色为3.7.1版本的登录日志    蓝色为3.9.2版本的登录日志

3.7.1版本中，内网访问都能显示具体的内网IP，升级到3.9.2后，内网访问显示的IP都是Nginx代理服务器IP

JumpServer 部署在 10.0.1.x     

内网IP段：192.168.1.0/24    172.31.255.0/24   10.0.0.0/24   10.0.1.0/24

Nginx代理服务器IP：10.0.1.111

![image](https://github.com/jumpserver/jumpserver/assets/12994898/9a08a914-36d4-4522-88e3-103efc57a41a)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
代理 Nginx 要添加配置信息：

https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf#L39

**Comment by pengcheng820** [comment]
Nginx 反向代理 proxy_set_header X-Forwarded-For $remote_addr; 改成了  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
获取到的IP还是Nginx反向代理的IP地址

![image](https://github.com/jumpserver/jumpserver/assets/12994898/ad9e961f-b88e-4a88-9dc2-2f38ff7de9d6)

![image](https://github.com/jumpserver/jumpserver/assets/12994898/0aaa0c21-aea9-4b6e-a2ae-fc7ecf79a596)

**Comment by BaiJiangJie** [comment]
这行：proxy_set_header X-Forwarded-For $remote_addr;

**Comment by pengcheng820** [comment]
之前方向代理按照文档就有  proxy_set_header X-Forwarded-For $remote_addr;
现在$remote_addr 和 $proxy_add_x_forwarded_for 都加上了
IP显示还是代理IP

![image](https://github.com/jumpserver/jumpserver/assets/12994898/939d0f4d-360c-421b-b1c7-3040816f4a23)


![image](https://github.com/jumpserver/jumpserver/assets/12994898/cb443414-2fa0-4021-8eb3-d7cad51ce033)

**Comment by BaiJiangJie** [comment]
第二行去掉。

**Comment by pengcheng820** [comment]
3.7.1版本还好好的，升级后发现IP显示不对了

**Comment by pengcheng820** [comment]
一直都是Docker
从2.8   3.7.1   3.9.2

**Comment by BioEvo** [comment]
> * https://github.com/jumpserver/jumpserver/pull/11973/files
>   这个 pr 修改了获取 IP 的规则。
> 
> ```python
> def get_request_ip(request):
>     x_real_ip = request.META.get('HTTP_X_REAL_IP', '')
>     if x_real_ip:
>         return x_real_ip
> 
>     x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', '').split(',')
>     if x_forwarded_for and x_forwarded_for[0]:
>         login_ip = x_forwarded_for[0]
>         return login_ip
> 
>     login_ip = request.META.get('REMOTE_ADDR', '')
>     return login_ip
> ```
> 
> 按照你的说法，可能是 `X-Forwarded-For` 被覆盖了，你看下 `Nginx` 的日志，确定真实 IP 是哪个变量。 如果 `Nginx` 日志里面也无真实 IP，你可能要检测下 `iptables` 的规则是不是过滤掉了。

感谢给出代码，配置完X-Real-IP问题解决了XD

**Comment by wojiushixiaobai** [comment]
@stardemo 既然已经拿到 真实IP 的变量，你直接根据你的实际情况修改 nginx 的配置文件即可。

**Comment by stardemo** [comment]
审计登陆日志获取的IP改Nginx配置可以么？不是程序获取的？

**Comment by stardemo** [comment]
> @stardemo 既然已经拿到 真实IP 的变量，你直接根据你的实际情况修改 nginx 的配置文件即可。

审计登陆日志获取的IP改Nginx配置可以么？不是程序获取的？

**Comment by wojiushixiaobai** [comment]
```python
def get_request_ip(request):
    x_real_ip = request.META.get('HTTP_X_REAL_IP', '')
    if x_real_ip:
        return x_real_ip

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', '').split(',')
    if x_forwarded_for and x_forwarded_for[0]:
        login_ip = x_forwarded_for[0]
        return login_ip

    login_ip = request.META.get('REMOTE_ADDR', '')
    return login_ip
```
这个代码是 `Core` 组件的获取代码日志，获取到的信息是由 `Nginx` 传递过来的，获取不正确表示你的 `Nginx` 配置不当。
以你的实际环境为例，你的 nginx 配置文件里面缺失：
```sh
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
需要使用 ` X-Forwarded-For $proxy_add_x_forwarded_for;` 表示你的上层还有 `Nginx` 或者其他 `SLB`

针对此问题，配置文件有明确说明 - https://github.com/jumpserver/installer/blob/dev/config-example.txt#L152
```sh
# /opt/jumpserver/config/config.txt
#
################################## 其他配置 ##################################
# 终端使用宿主 HOSTNAME 标识, 首次安装自动生成
#
.
SERVER_HOSTNAME=${HOSTNAME}

# 使用内置 SLB, 如果 Web 页面获取到的客户端 IP 地址不正确, 请将 USE_LB 设置为 0
# USE_LB 设置为 1 时, 使用配置 proxy_set_header X-Forwarded-For $remote_addr
# USE_LB 设置为 0 时, 使用配置 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
USE_LB=1

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#
CURRENT_VERSION=
```

**Comment by stardemo** [comment]
我研究下 问题是用1Panel应用商店安装的  jumpserver/jms_all:v3.9.3 整合镜像 注入 USE_LB参数 0或者1都是无效的

**Comment by stardemo** [comment]
镜像里Nginx注入了错误的HTTP_X_REAL_IP header 改了一下代码屏蔽了  可以用起了
