### ISSUE TITLE
[Bug] MFA安装应用引导-iPhone手机下载应用失败

### ISSUE THREAD

**Issue by 2023fan** [jumpserver/jumpserver#12258]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.91

**浏览器版本**
谷歌-版本 119.0.6045.200（正式版本） （64 位）

**Bug 描述**
MFA安装应用引导-iPhone手机下载应用失败，提示：App不可用
![Uploading f0e7386c9a373d1f93bf81bb5a8ba28.jpg…]()

**Bug 重现步骤(有截图更好)**
1.启用MAF
2.iPhone手机扫码就好了

**Comment by 2023fan** [comment]
![f0e7386c9a373d1f93bf81bb5a8ba28](https://github.com/jumpserver/jumpserver/assets/145900305/075d2bfe-b00e-4b50-a2d8-1dc37090bd83)

**Comment by BaiJiangJie** [comment]
升级到最新版本使用。
