### ISSUE TITLE
[Bug] SFTP  web文件终端目录下刷新多出文件

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12256]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v3.9.3

**浏览器版本**
Chrome 最新版

**Bug 描述**
当 SFTP 协议根路径设置为 /  根目录时，web终端 SFTP 连接资产，选中某个目录显示文件正常，刷新一下会多出四个文件

**Bug 重现步骤(有截图更好)**
1.复制 Linux 平台，sftp 协议修改 根路径为 /
![image](https://github.com/jumpserver/jumpserver/assets/95400700/f190b25a-2def-41fb-b85d-233f4c8f2679)

2.创建基于新建平台的资产，web SFTP 连接资产，首次选中某个目录：
![image](https://github.com/jumpserver/jumpserver/assets/95400700/0459539c-f128-4e84-8e59-265f085d7bcf)

3.在右边文件列表右击刷新后
![image](https://github.com/jumpserver/jumpserver/assets/95400700/3e11fb60-2da0-48a8-b4a7-8fcce9002ed7)

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
