### ISSUE TITLE
[Bug] mysql连接，使用客户端的方式，dbeaver报Unknown system variable 'query_cache_size'，无法连接

### ISSUE THREAD

**Issue by SC-zj** [jumpserver/jumpserver#12259]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**
Chrome 119.0.6045.200

**Bug 描述**
mysql8.0.28连接，使用客户端的方式，dbeaver报Unknown system variable 'query_cache_size'，无法连接。
直接使用dbeaver客户端可以正常连接

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/70679694/20dfa0dd-b58a-446b-8504-fe8d77e544da)

2.
3.

**Comment by BaiJiangJie** [comment]
其他版本的 MySQL 数据库会报错吗？

**Comment by SC-zj** [comment]
Mysql5.xxx版本没问题，就是连mysql8有这个问题。dbeaver也换过没效果

**Comment by sevenclockseven** [comment]
dbeaver连接8.0以上MySQL时，连接类型换成mariadb就能正常连接了

**Comment by SC-zj** [comment]
1.把连接类型换成mariadb确实可以连上了。
2.![image](https://github.com/jumpserver/jumpserver/assets/70679694/f9774a80-47c1-4493-9992-1ee0d7219415)
![image](https://github.com/jumpserver/jumpserver/assets/70679694/2b7398ad-576b-464e-9fb9-36c5bd2247cc)
我发现问题所在了，jumpserver 组件设置里面的端点端口号和我配置文件里面的端点端口号不一致，导致我用mariadb的33061用mysql协议去连接了，导致出现了Unknown system variable 'query_cache_size'错误，我将这个错误修正后就可以用mysql协议连上mysql8.0了。
