### ISSUE TITLE
[Question] 历史会话不能回放和下载

### ISSUE THREAD

**Issue by wenbc** [jumpserver/jumpserver#12252]
历史会话不能回放和下载，页面显示禁用状态，是因为录屏的文件容量太大了吗？

当前使用的版本是：V3.9.2

![image](https://github.com/jumpserver/jumpserver/assets/8147297/48936e28-b600-4ee8-ba6c-d5fb8594ee6c)

**Comment by BaiJiangJie** [comment]
有一个错误信息列，放出来看一下是什么原因。

**Comment by wenbc** [comment]
> 有一个错误信息列，放出来看一下是什么原因。

错误信息列里面空空如也。

![image](https://github.com/jumpserver/jumpserver/assets/8147297/30346c99-bbf3-4481-ae5c-62c0dfa42a22)

**Comment by BaiJiangJie** [comment]
是什么会话？windows 还是 linux？

**Comment by wenbc** [comment]
linux，但是协议是 Sftp，这种是不能回放？

**Comment by BaiJiangJie** [comment]
嗯，SFTP 会话，目前没有录像。在 FTP 日志里会记录对于文件的操作。

后面版本在错误信息中会给出提示。

**Comment by jym503558564** [comment]
v3.10.0已优化，sftp会话提示不支持录像信息，请升级进行测试。如有其他问题，可再次打开Issues.
