### ISSUE TITLE
[Bug] redis 客户端连接问题   (error) invalid secret 

### ISSUE THREAD

**Issue by 0x5c0f** [jumpserver/jumpserver#12267]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

当前 `jms`版本 `v3.9.3`   

容器下载的是云加速镜像(DOCKER_IMAGE_MIRROR=1)

**浏览器版本**
google-chrome 116.0.5845.190 

**Bug 描述**
`redis` 连接，无论是数据库客户端连接，还是`DB`连接向导连接都存在错误 `(error) invalid secret `

`redis` 资产版本是 `6.2.7` , 未设置用户名 

`redis-cli` 本地版本是 `6.7.12` 

正常配置`redis`资产, 平台设置的是 `redis 6+`，用户配置时，我设置用户名是 `null` , 然后通过`Web`终端连接正常。
通过`DB`连接向导，根据展示的数据库连接信息配置。  

1. 使用客户端工具 `Another Redis Desktop Manager` 连接，报错 `Client On Error: ReplyError: invalid secret Config right?`   
2. 使用唤醒工具`JumpServerClient`中数据库连接工具推荐的`Redis Desktop Manager(FuckDoctors/rdm-builder) - resp.exe` 连接报错   
```
External: Can't load list of available formatters from extension server: Protocol "" is unknown, 
Formatters: Cannot import module: formatters (bad magic number in 'formatters': b'\xa7\r\r\n')
Connection: xxxx> connected
Connection: xxxx > [runCommand] AUTH *******
Connection: redis-server doesn't support AUTH command or ismisconfigured. Trying to proceed without password. (Error: invalid secret)
Connection: xxxx > [runCommand] PING
Connection: Connection error on AUTH: need auth
```  
3. ***使用`连接命令行` 中推荐命令 `redis-cli`，如果 使用`-a` 参数指定用户名密码，则正常登陆。但是，如果未使用`-a`指定用户名密码，只是连接到`redis`，然后使用 `AUTH 用户名  密码`,则同样出现错误 `(error) invalid secret`***  

**Bug 重现步骤(有截图更好)**
1. 正常配置redis资产，由于我的redis资产未设置用户名，所以jms配置时，连接账户的用户名设置为`null``
2. 正常资产授权
3. `Web终端连接` - 选择`redis` 资产，选择 `DB连接向导` ，按照提示信息配置测试

**Comment by BaiJiangJie** [comment]
将 Redis 的资产平台从 Redis6+ 修改为 Redis 试一下。

**Comment by BaiJiangJie** [comment]
通过 redis-cli 连接时，注意 -a 之后的参数是：username@password

<img width="1159" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/05fcf02d-66e9-4d8e-850d-33b348d43699">

**Comment by 0x5c0f** [comment]
> 将 Redis 的资产平台从 Redis6+ 修改为 Redis 试一下。

已测试此项，仍然存在  

![20231207155709](https://github.com/jumpserver/jumpserver/assets/26927906/cd904c3e-0082-461f-a4e5-1acf23471f2f)
![20231207155934](https://github.com/jumpserver/jumpserver/assets/26927906/c75ba8c5-e829-4692-93d1-3a2abebb30bc)

**Comment by BaiJiangJie** [comment]
测试一下这种方式。

> 通过 redis-cli 连接时，注意 -a 之后的参数是：username@password
> 
> <img alt="image" width="1159" src="https://private-user-images.githubusercontent.com/32935519/288675490-05fcf02d-66e9-4d8e-850d-33b348d43699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDcxODIsIm5iZiI6MTcwMTk0Njg4MiwicGF0aCI6Ii8zMjkzNTUxOS8yODg2NzU0OTAtMDVmY2YwMmQtNjZlOS00ZDhlLTg1MGQtMzNiMzQ4ZDQzNjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDExMDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGNlYzA1MDI2Nzk3MzI2YzgxM2E0OTkyNjg4ZTFmNzFmMDUyMThhZTgwMmZlNjM4ZDU4ZjRjZDM5ZWE1NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0AStk-iSNlHM_ozWz5Bn5jhdVlLl8LZ2RcQbBCyWLDw">

**Comment by 0x5c0f** [comment]
@BaiJiangJie  刚刚查询到后端日志也是认证失败，但我确定我是直接复制的所有信息 

![20231208165408](https://github.com/jumpserver/jumpserver/assets/26927906/9733da75-2bbf-4185-a471-81349244b394)

**Comment by BaiJiangJie** [comment]
约个时间我们远程看一下吧？

**Comment by 0x5c0f** [comment]
> 约个时间我们远程看一下吧？

可以在VI群 @0x5c0f ,我在群里面

**Comment by BaiJiangJie** [comment]
好的，看到了。

**Comment by BaiJiangJie** [comment]
问题已解决，所有连接方式的 密码字段，都填写：username@password。

**Comment by ChenWenBrian** [comment]
> 问题已解决，所有连接方式的 密码字段，都填写：username@password。

同样的问题，another redis desktop manager里，分开填写用户名和密码就会报错。可选的操作有两种：
1. 空掉`用户名`，然后`密码`处填`username@password`的组合。
2. `用户名`处填`username@password`的组合也是可以的，`密码`留空或者乱填都可以。

很奇怪的使用体验😂

**Comment by 449134904** [comment]
> > 问题已解决，所有连接方式的 密码字段，都填写：username@password。
> 
> 同样的问题，another redis desktop manager里，分开填写用户名和密码就会报错。可选的操作有两种：
> 
> 1. 空掉`用户名`，然后`密码`处填`username@password`的组合。
> 2. `用户名`处填`username@password`的组合也是可以的，`密码`留空或者乱填都可以。
> 
> 很奇怪的使用体验😂

这个办法可以
