### ISSUE TITLE
[Bug] v3.9.3版本设置了密码复杂策略后，JumpServer用户下次登录修改密码，没有设置特殊字符仍然可以重置密码成功

### ISSUE THREAD

**Issue by yileinayn** [jumpserver/jumpserver#12260]
**JumpServer 版本**
  v3.9.3

**浏览器版本 **
 Chrome 119.0.6045.200（正式版本）(64 位）

**Bug 描述**
设置了密码复杂策略后，JumpServer用户下次登录修改密码，没有设置特殊字符仍然可以重置密码成功

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/77610565/d359bdd4-5155-4530-bc2b-8f3616d73ffe)

![b2e94fe34de2ac8935abee2e5fdbe5f](https://github.com/jumpserver/jumpserver/assets/77610565/2554858a-0a54-45d9-b573-cc9fc069ca8d)

![1fa491715f21d659fe6c5a8d5ad3e63](https://github.com/jumpserver/jumpserver/assets/77610565/a7312aef-9589-44b8-aa7f-3f9b1cbd5f67)

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
