### ISSUE TITLE
[Question] 页面web 的键值对填写问题

### ISSUE THREAD

**Issue by xinxinzhao1212** [jumpserver/jumpserver#12264]
**请描述您的问题.**
页面链接如下：https://rancher2.hitroncloud.cn/dashboard/auth/login
想添加jumpserver 的自动登录，但是这个页面的password 是在input 的外层，这种应该怎么填写password ？ username 和button 如下图是否为正确？

username
![image](https://github.com/jumpserver/jumpserver/assets/32668515/da222874-222b-4256-b447-69d9efe29218)

password：
![image](https://github.com/jumpserver/jumpserver/assets/32668515/62c832ee-c2b4-44e2-a804-224ceebb3c88)

submit
![image](https://github.com/jumpserver/jumpserver/assets/32668515/03150c85-f8f6-4ebe-9341-f3815ee11d26)

**Comment by BaiJiangJie** [comment]
建议使用 XPath 定位，更准确一些。
