### ISSUE TITLE
[Bug]  使用web 登录网页，有时候不能通过配置自动登录页面，有时候可以

### ISSUE THREAD

**Issue by xinxinzhao1212** [jumpserver/jumpserver#12263]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.1

**浏览器版本**
![image](https://github.com/jumpserver/jumpserver/assets/32668515/29a56c97-4d76-45be-be34-ebda119dbcae)

**Bug 描述**
在使用web 访问远端页面时候，有时候能自动填写用户名密码并且登录，有时候没有填写用户名密码，不能自动登录

**Bug 重现步骤(有截图更好)**
1。需要打开的页面
https://978793689832.signin.amazonaws.cn/console

在jumpserver 上的配置

![image](https://github.com/jumpserver/jumpserver/assets/32668515/648a741b-cb3a-47ab-8140-95af73cb0ec6)

登录结果：
可以登录：
![image](https://github.com/jumpserver/jumpserver/assets/32668515/58c5c04e-1f3c-4130-b02e-6bb82e1e792f)

不可以登录：
![image](https://github.com/jumpserver/jumpserver/assets/32668515/b4ff89ea-864d-4afb-acc1-4dabc95463ca)

**Comment by BaiJiangJie** [comment]
配置一样，第一次打开可以登录，第二次打开不能登录？还是什么情况下可以稳定复现？

**Comment by BaiJiangJie** [comment]
如果还有问题，Reopen!
