### ISSUE TITLE
[Bug] web GUI 方式连接MySQL，控制台输出的结果看不全，不能点击、全选

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12279]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**
chrome 版本 119.0.6045.199（正式版本） (x86_64)

**Bug 描述**
web GUI 方式连接MySQL，控制台输出的结果看不全，不能点击、全选。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/0e380748-c5a0-4010-92b6-df2555a8dc3e)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
验证了，可以复制出来。也可以拖拽列。
