### ISSUE TITLE
升级到1.2.0后 之前的授权规则还存在吗

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1227]
[简述你的问题]

##### 使用版本
[Version 1.2.0-2 GPLv2]

##### 问题复现步骤
发现升级到1.2.0版本后  授权规则又清空了 。只能重新添加吗

**Comment by onekeyshell** [comment]
记得执行 utils下的2018_04_11_migrate_permissions.sh 脚本，迁移原来的授权数据

**Comment by clangcn** [comment]
记得执行 utils下的2018_04_11_migrate_permissions.sh 脚本，迁移原来的授权数据

**Comment by qianghong000** [comment]
多谢
