### ISSUE TITLE
[Bug] WEB终端总是弹出“登录已过期，请重新登录”

### ISSUE THREAD

**Issue by novice-gamer** [jumpserver/jumpserver#12271]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.9.0

**浏览器版本**
Google 119.0.6045.159

**Bug 描述**
在web终端操作命令行时，总是弹出“登录已过期，请重新登录”的弹窗，有时候正在输入命令就开始弹，我看之前有提到过这个问题，但是我设置SESSION_EXPIRE_AT_BROWSER_CLOSE=False后依然还是会弹。点击登录后会打开新的浏览器窗口，但是并不是真的重新登录的界面。

**Bug 重现步骤(有截图更好)**
1.打开web终端
2.正常输入命令或者等待一会
3.

**Comment by BaiJiangJie** [comment]
确认一下是不是你的用户会话真的过期了。
