### ISSUE TITLE
[Feature] 资产列表希望能够根据创建日期排序

### ISSUE THREAD

**Issue by Jonnn-y** [jumpserver/jumpserver#12277]
**请描述您的需求或者改进建议.**
v3.9.3 版本资产列表，不能通过创建日期排序
![image](https://github.com/jumpserver/jumpserver/assets/95204418/cec50934-2769-4693-9067-37726c1ab69a)

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
