### ISSUE TITLE
[Question] Is there any english documentation available?

### ISSUE THREAD

**Issue by NathanArkov** [jumpserver/jumpserver#12272]
Hello, I would like to try Jumpserver on my system but the lack of english documentation is making it almost impossible. I do not speak mandarin and it seems like all of your documentation website and github is written in mandarin. 

Is there a translation somewhere ? Do Jumpserver even works outside of China ?

Regards

**Comment by BaiJiangJie** [comment]
Hello, thank you for your question.

Currently, the language can be selected in the JumpServer product, supporting Chinese, English, and Japanese. As shown below.
<img width="1439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/238743f8-6208-42bc-a703-8791ba303e81">


However, JumpServer's documentation (`https://docs.jumpserver.org/zh/v3/`) is currently only in Chinese. You can translate the entire page through the Google browser plug-in (for example: JumpServer's documentation). Alternatively, you can contact our marketing department to provide you with technical support. (`https://jumpserver.org/index-en.html`)
<img width="1151" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2d20efb9-22f0-4066-80fd-d0e916504c48">

However, what is worth looking forward to is: in 2024, the JumpServer team plans to support full English version of the usage documentation.

Currently, users in many countries are already using JumpServer. I hope it can help you.
