### ISSUE TITLE
自动任务不会执行

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#12278]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.9.3

**浏览器版本**
不涉及

**Bug 描述**
查看任务没有自动执行，重启过celery也无效

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![WXWorkLocal_17019956455448](https://github.com/jumpserver/jumpserver/assets/38068938/8f6920b3-7503-4abe-a8b4-24a6f3bb80d4)
![WXWorkLocal_17019956169719](https://github.com/jumpserver/jumpserver/assets/38068938/5a7473ce-a8d6-4b16-963e-30852958c5b8)

**Comment by BaiJiangJie** [comment]
<img width="1049" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/775a0d45-2879-4922-8c81-5280c62b57b5">

看下任务监控里面的 worker 正常吗？

**Comment by zhonglinwei** [comment]
我12月7日从3.4.0升级到3.9.3版本后，作业管理里定时执行的命令作业也无法执行
![微信截图_20231211102855](https://github.com/jumpserver/jumpserver/assets/51225774/8a55e249-7db4-4893-8f4a-1910fca73b98)

**Comment by sanpichen** [comment]
![canvas2](https://github.com/jumpserver/jumpserver/assets/38068938/b03d2e8b-c906-4348-9f7b-a5d18e0967a5)
![微信图片_20231212083910](https://github.com/jumpserver/jumpserver/assets/38068938/d0eee17e-db1d-4951-ad90-891506291394)


> <img alt="image" width="1049" src="https://private-user-images.githubusercontent.com/32935519/288979082-775a0d45-2879-4922-8c81-5280c62b57b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDIzNTIsIm5iZiI6MTcwMjM0MjA1MiwicGF0aCI6Ii8zMjkzNTUxOS8yODg5NzkwODItNzc1YTBkNDUtMjg3OS00OTIyLThjODEtNTI4MGM2MmI1N2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAwNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzOTRhZTc0MmYwZTExMTdhZTY1ZTY3ZjNkZWE5NmIzYTA2YmZlYjE0OTA3MzY4YTgzMTQ0ZGY4MWYwMGIxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CIBnvjVBkh17NDr-w-HaBqN4pWjiCkSh6aCVsaZUx-w">
> 
> 看下任务监控里面的 worker 正常吗？

**Comment by BaiJiangJie** [comment]
日志显示最后执行是 12.09 号。约个时间远程看一下吧。

**Comment by sanpichen** [comment]
公司不允许安装、使用 远程协助工具
有什么好的办法吗

**Comment by BaiJiangJie** [comment]
以前遇到这个问题是因为 Celery 阻塞了。重启一下 `jms_celery` 容器就可以了。

或者，你清空一下 redis，然后重启所有服务，再看看情况。（**注：清空 Redis 会让当前登录的用户失效，确认时间后再操作**）

**Comment by sanpichen** [comment]
> 以前遇到这个问题是因为 Celery 阻塞了。重启一下 `jms_celery` 容器就可以了。
> 
> 或者，你清空一下 redis，然后重启所有服务，再看看情况。（**注：清空 Redis 会失效当前登录的用户，确认时间后再操作**）

我清空过redis，重启服务了。
现在看到的状态是我做每日定时重启jms_celery任务后今天看到的结果，有些任务不知怎么就不执行了。
![微信图片_2023121 9090737](https://github.com/jumpserver/jumpserver/assets/38068938/c5f34284-6eb5-4e51-abca-0d71e7b14fa9)

**Comment by BaiJiangJie** [comment]
确实有点奇怪。我们的环境一直没有复现。

@jym503558564 再观察观察我们的环境，能否复现？

**Comment by sanpichen** [comment]
升级到最新的3.10.1还是不行，基本都没有执行到。
![1705048643153](https://github.com/jumpserver/jumpserver/assets/38068938/2cc7a8f8-fff4-4e7c-ba01-04f024d591cc)

**Comment by sanpichen** [comment]
docker部署
###########
CONTAINER ID   IMAGE                        COMMAND                  CREATED       STATUS                 PORTS                                                                                                                                                                                        NAMES
079481b213d5   jumpserver/core-ce:v3.10.1   "./entrypoint.sh sta…"   10 days ago   Up 10 days (healthy)   8080/tcp                                                                                                                                                                                     jms_core
9c6efffb5f9d   jumpserver/core-ce:v3.10.1   "./entrypoint.sh sta…"   10 days ago   Up 9 days (healthy)    8080/tcp                                                                                                                                                                                     jms_celery
53fa08f463af   jumpserver/lion:v3.10.1      "./entrypoint.sh"        10 days ago   Up 10 days (healthy)   4822/tcp, 8081/tcp                                                                                                                                                                           jms_lion
e1f20a2f36ad   jumpserver/web:v3.10.1       "/docker-entrypoint.…"   10 days ago   Up 10 days (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp                                                                                                 jms_web
b6c063a7f48d   jumpserver/chen:v3.10.1      "./entrypoint.sh"        10 days ago   Up 10 days (healthy)   8082/tcp                                                                                                                                                                                     jms_chen
221f2e045e96   jumpserver/koko:v3.10.1      "./entrypoint.sh"        10 days ago   Up 10 days (healthy)   0.0.0.0:2222->2222/tcp, :::2222->2222/tcp, 5000/tcp                                                                                                                                          jms_koko
105c72b120c6   jumpserver/kael:v3.10.1      "./entrypoint.sh"        10 days ago   Up 10 days (healthy)   8083/tcp                                                                                                                                                                                     jms_kael
2687c6ea4a0e   jumpserver/magnus:v3.10.1    "./entrypoint.sh"        10 days ago   Up 10 days (healthy)   0.0.0.0:14330->14330/tcp, :::14330->14330/tcp, 0.0.0.0:63790->63790/tcp, :::63790->63790/tcp, 0.0.0.0:33060->33061/tcp, :::33060->33061/tcp, 0.0.0.0:33061->33062/tcp, :::33061->33062/tcp   jms_magnus
6c2347ba1087   jumpserver/mariadb:10.6      "docker-entrypoint.s…"   10 days ago   Up 10 days (healthy)   3306/tcp                                                                                                                                                                                     jms_mysql
643efa7ad6fe   jumpserver/redis:6.2         "docker-entrypoint.s…"   10 days ago   Up 10 days (healthy)   6379/tcp                                                                                                                                                                                     jms_redis
###########
CentOS Linux release 7.9.2009 (Core)
Docker version 23.0.1, build a5ee5b1
ProLiant DL380e Gen8   24G 



***@***.***
 
发件人： Bryan
发送时间： 2024-01-12 16:42
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
什么部署方式，机器配置怎么样？

**Comment by BaiJiangJie** [comment]
不能远程就没有好的办法了，主要我们的测试环境中没有复现。

**Comment by feng626** [comment]
进 celery 容器里  apps 目录下 celery -A ops  purge 这个命令会清空celery中的任务 之后再重启容器 
也可以校准一下主机的时间 尝试一下

**Comment by sanpichen** [comment]
***@***.***_celery:/opt/jumpserver#  celery -A ops purge 
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
The module ops was not found.
***@***.***_celery:/opt/jumpserver# 



***@***.***
 
发件人： feng626
发送时间： 2024-01-12 17:07
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
进 celery 容器里 apps 目录下 celery -A ops purge 这个命令会清空celery中的任务 之后再重启容器
也可以校准一下主机的时间 尝试一下

**Comment by w940853815** [comment]
进入core容器，到/opt/jumpserver/apps目录下  执行 python3 manage.py dbshell 然后执行select * from information_schema.innodb_trx\G;看下输出 @sanpichen

**Comment by sanpichen** [comment]
空：

MariaDB [jumpserver]> select * from information_schema.innodb_trx\G
Empty set (0.001 sec)



***@***.***
 
发件人： w940853815
发送时间： 2024-01-16 16:13
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
进入core容器，到/opt/jumpserver/apps目录下 执行 python3 manage.py dbshell 然后执行select * from information_schema.innodb_trx\G;看下输出 @sanpichen

**Comment by w940853815** [comment]
@sanpichen 现在自动任务还是有的不会执行？

**Comment by sanpichen** [comment]
再看一下，早上我清理redis重启了
现在大多看来是有正常执行的，明天再看看



***@***.***
 
发件人： w940853815
发送时间： 2024-01-16 16:33
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
@sanpichen 现在自动任务还是有的不会执行？

**Comment by sanpichen** [comment]
看来还是不行
我刚查的执行情况，很多都没触发到。
16日执行了清理重启，17日似乎是ok的，18日就没执行到了。



***@***.***
 
发件人： w940853815
发送时间： 2024-01-16 16:33
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
@sanpichen 现在自动任务还是有的不会执行？

**Comment by w940853815** [comment]
@sanpichen sql执行还是为空吗？

**Comment by sanpichen** [comment]
是的，空的。



***@***.***
 
发件人： w940853815
发送时间： 2024-01-19 10:25
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
@sanpichen sql执行还是为空吗？

**Comment by w940853815** [comment]
@sanpichen 日志可以打给包发出来吗？发下data目录下的celery和logs两个文件夹日志

**Comment by sanpichen** [comment]
文件太多太大了，  不是应该不需要那么多。




***@***.***
 
发件人： w940853815
发送时间： 2024-01-19 11:15
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
@sanpichen 日志可以打给包发出来吗？发下data目录下的celery和logs两个文件夹日志

**Comment by w940853815** [comment]
@sanpichen 那先发下data/logs目录下的jumpserver.log和celery_default.log两个文件吧

**Comment by sanpichen** [comment]
我提取了 -mtime -2 的日志出来，你看是否足够了。



***@***.***
 
发件人： w940853815
发送时间： 2024-01-19 11:15
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
@sanpichen 日志可以打给包发出来吗？发下data目录下的celery和logs两个文件夹日志

**Comment by w940853815** [comment]
@sanpichen 先发一下吧 发我邮箱w940853815#gmail.com

**Comment by BaiJiangJie** [comment]
后面版本研究一下，不太好修复。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12703

@sanpichen 

有新方案了，使用这个 issue 中评论的方式验证一下。

**Comment by sanpichen** [comment]
按这个方法，3月12日至今，大多数自动任务显示执行成功的。有没该执行而未执行的就不清楚了。





***@***.***
 
发件人： Bryan
发送时间： 2024-03-13 17:44
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] 自动任务不会执行 (Issue #12278)
#12703 (comment)
@sanpichen
有新方案了，使用这个 issue 中评论的方式验证一下。

**Comment by BaiJiangJie** [comment]
好的，主要看历史执行记录，如果执行时间都是预设时间那应该没问题。
