### ISSUE TITLE
[Bug] 自定义远程应用无法更新版本

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12270]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v3.9.3

**浏览器版本**
Chrome 

**Bug 描述**
在应用市场下载安装的远程应用（有自定义协议的比如 Radmin），当创建对应资产使用一段时间后，想更新该远程应用时，直接上传会报应用已存在，删除应用会报有资产关联。而对于没有自定义协议的应用则可以正常删除应用并重新上传部署

**Bug 重现步骤(有截图更好)**
1. 下载安装 Radmin
2.创建 Radmin 资产
3.上传 / 删除 Radmin 远程应用

**Comment by BaiJiangJie** [comment]
嗯，目前更新远程应用确实有问题。

v3.10 中优化一下。

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
