### ISSUE TITLE
[Bug] 使用https访问linux和windows资产，输入命令没有回车，命令没有记录

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12274]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**
chrome 版本 119.0.6045.199（正式版本） (x86_64)

**Bug 描述**
Lion 组件问题
1.使用https访问环境, web GUI 的方式访问linux和windows资产，进入资产后输入命令没有回车，命令没有记录；
2.断开会话或会话超时，命令没有记录：windows 定时 30s 会结算一次命令记录，如果 30s 内输入命令，但是没有回车，然后直接断开会话，没有命令记录；linux输入命令没有回车，然后直接断开会话，没有命令记录。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
linux、windows 输入命令，没有回车就是没有执行，没有执行就=不会记录。
这是正常的情况。没有执行，当然不会记录了。
