### ISSUE TITLE
[Bug] 文件管理功能中，如果修改默认上传路径为 / 目录的话，在每个目录刷新都会生成bin\lib\lib64\sbin四个文件

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#12282]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.9.2/3.5.5

**浏览器版本**
版本 119.0.2151.93 (正式版本) (64 位)

**Bug 描述**
文件管理功能中，如果修改默认上传路径为 / 目录的话，在每个目录刷新都会生成bin\lib\lib64\sbin四个文件，机器版本centos 7.6/7.9

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/136306850/1b9e7e78-5d4d-46c6-8298-b1ce9f1f1468)
<img width="632" alt="674b40b58bd0a68f14f20332c20f77f" src="https://github.com/jumpserver/jumpserver/assets/136306850/bc17b209-30c9-4f1d-913b-af8483f23765">
<img width="610" alt="f1d25928b09a63b0daf4f5cf7313a0b" src="https://github.com/jumpserver/jumpserver/assets/136306850/59f23e57-fa9c-4528-a3b2-19129131da68">
2.
![image](https://github.com/jumpserver/jumpserver/assets/136306850/0cc76a38-4fae-41bd-a9d6-3662ae7cbd40)

3.

**Comment by BaiJiangJie** [comment]
嗯，目前是存在这个问题，v3.10 会修复。

**Comment by jym503558564** [comment]
已复现，待修复。

**Comment by 1223ruiyin** [comment]
好的

**Comment by jym503558564** [comment]
v3.10.0已优化，请升级进行测试。如有其他问题，可再次打开Issues.
