### ISSUE TITLE
为什么3.8 版本后 oidc 功能没有了[Question] 

### ISSUE THREAD

**Issue by G-Akiraka** [jumpserver/jumpserver#12295]
**请描述您的问题.**
之前3.8以下版本还可以使用 oidc登录，还可以跳板机使用oidc登录，到后面web还能登录，但是跳板机无法登录，直到最后都无法登录。

**Comment by BaiJiangJie** [comment]
目前 OIDC 认证方式是企业版功能。

**Comment by G-Akiraka** [comment]
好吧，那只能降会旧版本使用了
