### ISSUE TITLE
请求添加推送单台机器系统用户的功能

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1229]
[简述你的问题]

##### 使用版本
[Version 1.2.0-2 GPLv2]

##### 问题复现步骤
因添加新机器 偶尔会出现不自动推送系统用户，只能手动推送。但是每次都是讲所有服务器都推送一次，系统负载瞬间跑满。希望可以添加单台服务器系统推送功能

**Comment by gengkeye** [comment]
+1

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
