### ISSUE TITLE
[Bug] ssh连接，高级选项，字符集gbk不生效

### ISSUE THREAD

**Issue by Halo1236** [jumpserver/jumpserver#12296]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

<img width="616" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17096387/f879a78e-ddd3-4176-89c6-71ab067b4e9b">

修改字符集不生效，修改系统平台之后ok

**Comment by BaiJiangJie** [comment]
Fix it！

**Comment by BaiJiangJie** [comment]
最新版本已修复。
