### ISSUE TITLE
开源不是打电话骚扰别人的理由

### ISSUE THREAD

**Issue by interfacekun** [jumpserver/jumpserver#12299]
首先，我对这个项目不是很了解，也没有使用，我对这个项目的好坏没有任何评论。只是对打电话给我，骚扰我这个人感到愤怒。只是贵项目中的某未大能者的骚扰电话和发短信的行为干扰到了我的正常生活。我在这里非常不礼貌的对他说，我去年买了个表！
![WechatIMG135793](https://github.com/jumpserver/jumpserver/assets/18142336/ff2b9904-ce32-4e59-beef-b9fb88b07a04)
![Uploading WechatIMG186560.jpeg…]()

**Comment by maninhill** [comment]
很抱歉给你造成困扰，我们查下并改正。

**Comment by interfacekun** [comment]
谢谢

**Comment by ibuler** [comment]
非常抱歉，我们会严肃处理的

**Comment by ibuler** [comment]
因为图片涉及到手机号，暂时删除了图片

**Comment by ibuler** [comment]
我的邮箱是  ibuler#fit2cloud.com  ，你可以发邮件给我

**Comment by interfacekun** [comment]
已用gmail发送，望核查，谢谢
