### ISSUE TITLE
升级到3.9之后 本地客户端无法使用了[Bug] 

### ISSUE THREAD

**Issue by shanjunmei** [jumpserver/jumpserver#12290]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
无论是putty 还是winscp 都说 unknow option "-"

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
截图看一下。

**Comment by shanjunmei** [comment]
> 截图看一下。

![image](https://github.com/jumpserver/jumpserver/assets/9591051/f0dd2f38-e502-4579-b8eb-8c5dddf0d006)

**Comment by BaiJiangJie** [comment]
客户端用的什么版本？

**Comment by BaiJiangJie** [comment]
把之前安装的客户端 卸载干净。

**Comment by shanjunmei** [comment]
> 把之前安装的客户端卸载干净，再试一下。

多谢，确实可以了，但是我那个早已经升级了2.0.2 的要怎么处理呢，似乎已经找不到旧版本的程序卸载了

**Comment by BaiJiangJie** [comment]
找着对应的安装目录，删除文件应该就行了。
