### ISSUE TITLE
[Question] 自定义ansible-playbook目录；

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#12307]
**请描述您的问题.**
在剧本目录下配置了 ansible.cfg文件，自定义了执行目录。如下图结构显示的，在执行批量任务的时候提示找不到角色。难道是不支持吗？

![image](https://github.com/jumpserver/jumpserver/assets/7349963/a7cc7bb7-88ff-4957-b233-fa2c96f2c410)

**Comment by BaiJiangJie** [comment]
目前却是不支持 ansible.cfg 和 hosts 文件的自定义。

roles 目录需要直接放到 ansible-playbook 节点下，在 main.yml 中引用。

**Comment by BaiJiangJie** [comment]
后面版本会考虑优化一下这块的自定义，但是目前还没有排期。

**Comment by BaiJiangJie** [comment]
不考虑支持 ansible.cfg 的配置。

**Comment by seaurching** [comment]
> 不考虑支持用户自定义 ansible.cfg 配置文件。 会存在 ansible 执行的安全问题。

动态hosts是不是可以支持？
