### ISSUE TITLE
[Bug] 快捷命令60s超时不生效，一直不超时

### ISSUE THREAD

**Issue by hifer** [jumpserver/jumpserver#12304]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.7.2

**浏览器版本**
chrome 120.0.6099.71

**Bug 描述**
快捷命令60s超时不生效，一直不超时

**Bug 重现步骤(有截图更好)**
1. 执行需要交互的命令，例如sudo apt-get install supervisor
2.超时时间60s,一直等待，无法取消
3.如图所示
![image](https://github.com/jumpserver/jumpserver/assets/16734310/cce7b656-8c6c-4c09-8f0d-12a9a883e593)

**Comment by BaiJiangJie** [comment]
@jym503558564 测试一下最新版本有没有问题？

**Comment by fatpa** [comment]
在执行历史里可以查看到输出内容？

**Comment by hifer** [comment]
> 在执行历史里可以查看到输出内容？

![image](https://github.com/jumpserver/jumpserver/assets/16734310/c1baec7d-5e2b-4182-9229-ddfd1f2d1ec2)

**Comment by hifer** [comment]
> 在执行历史里可以查看到输出内容？

可以的
![image](https://github.com/jumpserver/jumpserver/assets/16734310/97d44dfa-f449-4fb4-be95-9de70a54e3b8)
![image](https://github.com/jumpserver/jumpserver/assets/16734310/67d1dd86-5f95-45e3-9bae-f95bff4b50b5)

**Comment by BaiJiangJie** [comment]
apt-get -y 一下应该就可以了。

这个命令有交互式的逻辑，超时可能检测不到。
