### ISSUE TITLE
[Bug] 3.1.x升级到3.9.3后管理员账号被禁用

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#12301]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.9.9

**浏览器版本**
Chrome 120.0.6099.71

**Bug 描述**
3.1.x升级到3.9.3后管理员账号被禁用，系统里只有一个管理员一个普通用户的账号，现在我已经失去jumpserver的控制权

**Comment by ibuler** [comment]
管理员账号是不是长时间没有登录了

**Comment by wojiushixiaobai** [comment]
参考官方帮助文档
![image](https://github.com/jumpserver/jumpserver/assets/24326988/6012f313-f06b-44b3-a682-b4940f613c37)
```sh
docker exec -it jms_core /bin/bash
cd /opt/jumpserver/apps
python manage.py createsuperuser --username=user --email=user@domain.com
```

**Comment by sicode** [comment]
> 管理员账号是不是长时间没有登录了

对的，管理员很少登录除非增加资产或者开新账号

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/12346/files

v3.10 会默认排除了 admin 用户。
