### ISSUE TITLE
登录主机提示：没有系统用户

### ISSUE THREAD

**Issue by czsmall** [jumpserver/jumpserver#12308]
![image](https://github.com/jumpserver/jumpserver/assets/110958481/e58e4e54-139b-4382-89a4-69b191cff58d)
反复检查了是授权了用户。
试了多个字长都试一样的提示。不知道怎么办了，不知道是什么原因

**Comment by BaiJiangJie** [comment]
资产授权中，授权系统用户应该就可以了。如果还是提示没有，Reopen issue。
