### ISSUE TITLE
[Question] assets_historicalauthbook 表占用大量磁盘空间

### ISSUE THREAD

**Issue by lhmlihaomin** [jumpserver/jumpserver#12303]
如图，table assets_historicalauthbook占用了11G磁盘空间，
请问此表格的用途是什么？
是否可以自动或手动清理其中的数据？

![688f81bc-011d-46c2-98a9-04db5b85ebf4](https://github.com/jumpserver/jumpserver/assets/6542305/068adc5a-3052-4893-9735-c7fe6f27d445)

**Comment by BaiJiangJie** [comment]
目前这张表中有多少条数据？

**Comment by lhmlihaomin** [comment]
> 目前这张表中有多少条数据？

目前有约300万数据。

我看了下这张表的created_by字段，基本全部是我们用于云函数的用户。
我们部署了Lambda云函数用于监听K8S集群的节点变化，发生EC2实例创建/终止事件时自动调用Jumpserver的assets/assets/接口。
由于节点变化过于频繁，表里很多asset_id已经不存在了，还没排查出头绪来，我们自己再研究下，谢谢

**Comment by BaiJiangJie** [comment]
好的。可以先找着已经不存在的资产 ID 行数据进行删除。
