### ISSUE TITLE
[Feature] 远程应用发布机调度问题

### ISSUE THREAD

**Issue by Jonnn-y** [jumpserver/jumpserver#12318]
**请描述您的需求或者改进建议.**
当关闭自动创建账号后，该发布机将不会在调度池内。
![image](https://github.com/jumpserver/jumpserver/assets/95204418/0cb469db-1352-4614-b3aa-d480390f40d0)

个人认为发布机调度不应该和自动创建账号开关绑定在一起，有时只是不想这台发布机在调度池中，但是又希望能够自动创建账号。
**建议**当自动创建账号打开后，多出一个是否放入调度池中的开关。
![image](https://github.com/jumpserver/jumpserver/assets/95204418/366a0fb7-f41a-40a7-b608-5596d57c76c7)
当自动创建账号关闭后，该发布机还是默认不会放到调度池中。

**Comment by BaiJiangJie** [comment]
<img width="1547" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/12401491-2470-41e3-b8ec-ea0ebb995da9">

可以开启 自动创建账号，但是不激活，这样就不会放到调度池中并能够创建出来账号了。

**Comment by JonnnLOL** [comment]
但是不激活也无法使用该发布机了。
主要的使用方式是这样的：
通过标签指定调用固定的发布机，不希望其他远程应用调用到该发布机，但又希望能够自动创建账号。

**Comment by BaiJiangJie** [comment]
创建发布机的时候，你先打开自动创建账号，等账号创建完成后，再关闭。这样能解决吗？（这样的情况，对于用户不频繁增加的情况比较好）
