### ISSUE TITLE
docker写入太大了

### ISSUE THREAD

**Issue by haitun3721** [jumpserver/jumpserver#12314]
运行一段时间后，/var/lib/docker/overlay2  这个目录太大了

再就是不停的去访问dns53，没必要总去解析啥域名吧！

**Comment by BaiJiangJie** [comment]
我们看着正常啊，才几十K。你截图看一下日志。

**Comment by haitun3721** [comment]
[qq@baoleiji ~]$ sudo du -lh --max-depth=1 /var/lib/docker/overlay2
60K     /var/lib/docker/overlay2/2e42690c8548651767d2db5295130c86badedf3e8496e1fe6d4ba4dd5ba6f158-init
424K    /var/lib/docker/overlay2/l
408M    /var/lib/docker/overlay2/c719e12eb84b9bd92e74efc5654de62aabb2a373bf8aa7070bd54b34cc17a0f3
5.0M    /var/lib/docker/overlay2/f68ae107ccb32c046c66642e5b8488049b7678df042f2e600389cd6ea3635e5b
36K     /var/lib/docker/overlay2/cee99ea70d50ff492102005192fc4d5dbb5c70516df21de9183e67e49a07ee39
384K    /var/lib/docker/overlay2/ef5be20f5b17895e6f91c7b7057b27f85edc85ea1731ee639e02d0d0c32ce883
62M     /var/lib/docker/overlay2/f06cc6a52e1db879513166db8d2f1b36fb059c9275400d40f64a6c1fe5d76a76
80K     /var/lib/docker/overlay2/63d5ff7a344a617a7c066533e4b170ffaa0eaa60232cf74beaaf79ba8a72feb1
36K     /var/lib/docker/overlay2/4d92009e24337dcbdde1534eb70a7c3c36c1f805dce094f3ec004b3f10d3b8d1
3.8M    /var/lib/docker/overlay2/fa51e1b8562c2bf897a4fc94210cff17372293d4f959a8b2ea49f9ff536b749a
26M     /var/lib/docker/overlay2/2e0fac1a32dc0b5de57e7e9721d1fd5e183aa18a8333a48b0fa14d8452952da4
36K     /var/lib/docker/overlay2/059a3fd1ce0b67626c29a5c6c86cdac7a2a8612d8590e19edbe3e40abf60aa5c
36K     /var/lib/docker/overlay2/ab19fa5738415facf286c106ae912fa2b34f227694beeafa42e89ded9d25e5f8
266M    /var/lib/docker/overlay2/f26e6ca43bd7afa095fc3c804ba991b92abad330b70e2bc1678fa85ae1b71fbd
44K     /var/lib/docker/overlay2/73ffaccd136dc6b5b3a45777da48f6c30e2f009f568341da44e55fd899a0d6d9
32K     /var/lib/docker/overlay2/a39aa199adb83225d126719304122d52e3c366ae1f378bfbc5efc7b95ea85e7c
1.7G    /var/lib/docker/overlay2/e17f3e7ee0aa07e0a638480ee5c298f8097ce38b9c31276c53a54f9562777cfd
32K     /var/lib/docker/overlay2/e5168cf84c216ba945a4c1baf7f2b865ba55a01202cea37e6ca117e5b05ad17c
384K    /var/lib/docker/overlay2/3e032f6a4ae4d1002e3ddb2fb9c47fef977301cf84f3efd56f64c11ba7988d20
60K     /var/lib/docker/overlay2/e17f3e7ee0aa07e0a638480ee5c298f8097ce38b9c31276c53a54f9562777cfd-init
1.7G    /var/lib/docker/overlay2/a7cd28772be4180694184f9913c7c9a1ced34d7ececca0f5d39998187b4aaff9
27M     /var/lib/docker/overlay2/68346a32598972b9a5045fb1084ed763b6a440dd6545f64e4b45fcddeefa68f1
5.2M    /var/lib/docker/overlay2/a49f1f5408dfb8eb9bc09495a10a183284ee58c70c6daf5d71b13c0fb877e0a2
28K     /var/lib/docker/overlay2/a8f0d5ca7461d12645ebad7ac12e491e8433c0f8c937c347b5f7c04f44158002
60K     /var/lib/docker/overlay2/b7271fd059bea666794613e1855dceee599304aa3109207494aa0f170cdbf757-init
92M     /var/lib/docker/overlay2/9a46d8fca7f268d152b4e06752ae2385bd0b8d64cf94886b8d82626617eb8d19
32K     /var/lib/docker/overlay2/975baaea8f3f93a316454c32e77abb2cdf5c02d5ec870c5305909ca2350fc5b8
19M     /var/lib/docker/overlay2/188ed23009b8382557bc6127dbfbd7b616cfc2e43795db12efa1c8732dc1f253
17M     /var/lib/docker/overlay2/1d0a9d3a0d6664bde014df302bca276ecfa8a399dd2a26220b6091e6ab47e505
40K     /var/lib/docker/overlay2/73b4eeda4f4d784c3563969d942168d6e3fbbf176cbb2aa8688697f678362b8e
64M     /var/lib/docker/overlay2/f850ead80fcd3ae3fea765ba1183de3f14d2d7a43cf290db74f222180bea9390
82M     /var/lib/docker/overlay2/07d51de89778fbf333fea257a753b749af6ddf72c7505ba532954000a4abf7cb
28K     /var/lib/docker/overlay2/428fab89b34228fd739da1aed3210ba2c42147e59959775e1bf772769852eafd
20K     /var/lib/docker/overlay2/1f54a35fac9056c18e6fadf2f2b61009341e4906220a606c8751e85e8e7240e1
44K     /var/lib/docker/overlay2/36960698f0636130a532f2415978e72a2ea5607416a3cd75d9dedbe39673df75
32K     /var/lib/docker/overlay2/5bc922e994aa3e4e5554f65f8b8394b966b5a03473ddc79019213e8b605b81d1
22M     /var/lib/docker/overlay2/46d91f9ddac19d14aa41423632c4a7bed56d74a7517912759a4def6050317139
380K    /var/lib/docker/overlay2/1a12a4644a32ce1823c5d88dd4402dad3aa1064cac6057171834b973492c9a08
176M    /var/lib/docker/overlay2/6242c30aa5e4c53e48e5dd0c014f7fa6783ba7c7aa44b45ff12b2c0cd1796d03
92M     /var/lib/docker/overlay2/3ea04b40c74747614b451a4d0e74146a80ca6ec9da09967a2f003daa441976d0
500M    /var/lib/docker/overlay2/3cfe6c524dd69759f2f1f675a87a38a5750090961ea6b08b77c28e0762135708
32K     /var/lib/docker/overlay2/4e0ab0711b57d40c9939a10bcaa3ce5e8f10e670455252be174d7ca0ece34bf3
58M     /var/lib/docker/overlay2/ad3e3379a2ea003449b9d6e16e1966dbde1ca937aa53cf7fbeb4aeea6600e1c6
28K     /var/lib/docker/overlay2/e59d0c13dbe3027a753fd1ece22bb50fee673899b887a6a23346da61955b8441
4.2M    /var/lib/docker/overlay2/ce96176f056d60bdeb4ad0b0b684583137bf971a419a300085821b4d18372169
962M    /var/lib/docker/overlay2/dd56ffd291d884323c10fa122d66ee0f4d130bd1b6dd1133069da6ece358d9a6
141M    /var/lib/docker/overlay2/9df6a893e353e36c605ff33d8f626374507229fb00495f3fdbfee201e04a2f44
4.0M    /var/lib/docker/overlay2/0806bb1cd2170babbea438197fde45dcb1844e89e77b68f8da51228b3dd7e5a7
156M    /var/lib/docker/overlay2/b7271fd059bea666794613e1855dceee599304aa3109207494aa0f170cdbf757
316M    /var/lib/docker/overlay2/f4b3be307f271fbc89bd095ba9761eddee595c28d4fea49c30904c479c2f6c8f
132K    /var/lib/docker/overlay2/998097963e7d97e14d659e9bfe051f87d982fe6b29f020bf6b16b3a56c938736
32K     /var/lib/docker/overlay2/f7c223211e3080c6913d82bf1d5a64dd6a121d398faae078be78f6b95d00bee9
81M     /var/lib/docker/overlay2/cbad1ab31f3f3ba706524f531029beb4d9c010a880126b40f32cf666dcb8b1df
560M    /var/lib/docker/overlay2/1cc0822dba0564ce54b89aa2327008294eab9ace07f4fb55abfa9fd073010a56
28K     /var/lib/docker/overlay2/e289e6cc5ecdfe3722185d398fa22c2002d303bf4f990aba12a81ff67bb8151d
28K     /var/lib/docker/overlay2/a06c45cb0f211c2d16c790ca7e47a12886f282ae29dd453eb3c03d940b5ebcc0
60K     /var/lib/docker/overlay2/a7cd28772be4180694184f9913c7c9a1ced34d7ececca0f5d39998187b4aaff9-init
32K     /var/lib/docker/overlay2/6ff2095c7aea4e194bb976bcc4b68194b2cd3a24bac056d7bc6abc93490b8154
60K     /var/lib/docker/overlay2/116826289d5f288cd5fadf88ec3bbd52c8400d9b2cad284af3eb371327ddeb57-init
22M     /var/lib/docker/overlay2/cae73096885e055e889004bf0a4035d8e8b3c3e4a184baa94cc54f9c350ca1da
60K     /var/lib/docker/overlay2/c719e12eb84b9bd92e74efc5654de62aabb2a373bf8aa7070bd54b34cc17a0f3-init
164M    /var/lib/docker/overlay2/ce77852c249e26f045bc4bb2ec7559f9e8411b161e2767862625180b6e6f275c
36K     /var/lib/docker/overlay2/22e83387e31d977f1354e86498ef785f254e285f77563581ba2d6ddd2f900960
6.5M    /var/lib/docker/overlay2/91d2304e01dae4ba85494b6f31d00362f022cf35ad556e659de1e81a83340d3c
1.2G    /var/lib/docker/overlay2/8b1ba1e1bcc8acbf3dd92010aed9f176b3c1b8c28672581f16e90cdd8b44dd3c
24M     /var/lib/docker/overlay2/6ce6777dde57aa6c69e01d81a892a810914b8e8e4a6d9249a341b527e5ff7e37
78M     /var/lib/docker/overlay2/4c7e5bd2848bca856dd91db222b23fca044a115a5c0503950c82e697520d2d47
52K     /var/lib/docker/overlay2/5976393c7baa0890463187ede7473de80de113ff3b8fac5adc07de346b219a61
63M     /var/lib/docker/overlay2/1c5c6d4ea3b764b5d9b80d65a7bd8f6f7b4f218906c7aab1f9212448c3308a9c
60K     /var/lib/docker/overlay2/b2512d63ac2d587e64d679fd307e157726b4fe224945b5239bd4454be57cb48b-init
28K     /var/lib/docker/overlay2/8c5c271b1fdd2be614141836e80d6526c3fab282dd8d9e47054d8482c46120ee
308M    /var/lib/docker/overlay2/72bfeec7e51d1ff08fc44953c65b92f5daca235fd96becf52fc3d93fea6a08b5
12M     /var/lib/docker/overlay2/7e6d1479abcc2eb2f72573a5dbd0329ffec9f83107a3d7687afecee8945d2df5
282M    /var/lib/docker/overlay2/2e42690c8548651767d2db5295130c86badedf3e8496e1fe6d4ba4dd5ba6f158
1.8G    /var/lib/docker/overlay2/116826289d5f288cd5fadf88ec3bbd52c8400d9b2cad284af3eb371327ddeb57
15M     /var/lib/docker/overlay2/7dffe30183ed9504af7419a8bbfa0e91f5935f35a493ad74d741de269899e94b
27M     /var/lib/docker/overlay2/6c4bdc51e9f9bae703ad053eb250fe3ccc744ca8ee26d1a3be4b7e08c3f6c127
13M     /var/lib/docker/overlay2/02e959ba48230729db5cba0faca75adcaf15fae20e42d9240b2931301128fca3
28K     /var/lib/docker/overlay2/047dc29d7652d4429923ebb3fb2a1958419700ac5c364087e21d4091fbdfc7ca
26M     /var/lib/docker/overlay2/09535f97317771a76302c90e0811ceee8716e26af8724dcf50b59badb2f83a9f
20K     /var/lib/docker/overlay2/6ed7bfb7dac73987b6e80d8024cd265ded137606ec071220c33f6bef1fd88443
259M    /var/lib/docker/overlay2/c5bd70044f583898c19fd1763985aa5c3888055103e2c5fc0ce1abfe8186ebdf
32K     /var/lib/docker/overlay2/bd065a0e85b9b225946b2e27202ab5b04114295a99ffc6655d12e8bd4bf67eef
20K     /var/lib/docker/overlay2/547b6ac7eb8e2b51ff95204834df24a73666804db8116645811249320aa6ae72
6.5M    /var/lib/docker/overlay2/c24dadb65034f2d3f41cf0d4f9c1a6d00da5aa50877dc06ba3a3965d161d2030
92M     /var/lib/docker/overlay2/47df00e9702d45cce7f6565a4102a86b67f02970225c151bb221c2b21968a7aa
24K     /var/lib/docker/overlay2/5f7031094f810f5254af5267ad880f30c4bc8ee74c4d122b72d09385de3e04d0
32K     /var/lib/docker/overlay2/00a0608e7909ba59e4053e31ad77661a3b4b74674a1105bacf8e28d99a8a4e0b
60K     /var/lib/docker/overlay2/4a51733d95640e5499971f0d0f87c84cf887cd8d1a7b58183654db317a664b06-init
60K     /var/lib/docker/overlay2/f26e6ca43bd7afa095fc3c804ba991b92abad330b70e2bc1678fa85ae1b71fbd-init
34M     /var/lib/docker/overlay2/5101c240e68194705b8b5f30e685f23e0dec068b84c8bb8ae76bd04abf822b2d
52K     /var/lib/docker/overlay2/6c643914922798d5d84ff3af89eefdfa3e6609855d5c2bcfd5498eaf0f989e0c
36K     /var/lib/docker/overlay2/fbf45119243b1cd12fe6bf6a5bafd5f395a8004556f8510df8eece6703989b6c
28K     /var/lib/docker/overlay2/5e2e6c8b247f6107d9df350716fd5913774251b8aeb68c276a492ae9ca8e50b8
27M     /var/lib/docker/overlay2/29f146e245b9be8b86066657b7e7c4d5fee9c1c3b4ff44e90c9ec6b724327ef8
20K     /var/lib/docker/overlay2/7ed77462ba9b2698f30842ca553afffc0285bcb15f40a62b58ddff43b2dbb73c
60K     /var/lib/docker/overlay2/1cc0822dba0564ce54b89aa2327008294eab9ace07f4fb55abfa9fd073010a56-init
202M    /var/lib/docker/overlay2/5a1d295a7c642c7d3b5d8678bf161918fc040107196f8245f2c0c6ef551915c8
1.5G    /var/lib/docker/overlay2/b2512d63ac2d587e64d679fd307e157726b4fe224945b5239bd4454be57cb48b
27M     /var/lib/docker/overlay2/c722fa87b965bc3d49043f8156d6c027cc346f90b15d5734e44d5a2b6e38a36e
28M     /var/lib/docker/overlay2/c099c0292cca23377182fa7070efee3fce15e3cb87b5af82254deca154ab8e0d
20K     /var/lib/docker/overlay2/9a6fd27e717e9a8842870edc82b56d3f8f6829bc58ff700279ee64d35fe39ca6
28K     /var/lib/docker/overlay2/c351ea504ffd95ccbb45435b7b17fe7cc8a272071c81726427b3c7c2ea7f4ef3
119M    /var/lib/docker/overlay2/4a51733d95640e5499971f0d0f87c84cf887cd8d1a7b58183654db317a664b06
14G     /var/lib/docker/overlay2
[qq@baoleiji ~]$ sudo du -lh --max-depth=1 /var/lib/docker
46M     /var/lib/docker/containers
104K    /var/lib/docker/buildkit
4.0K    /var/lib/docker/tmp
108K    /var/lib/docker/network
11M     /var/lib/docker/image
572K    /var/lib/docker/containerd
4.0K    /var/lib/docker/runtimes
16K     /var/lib/docker/plugins
4.0K    /var/lib/docker/swarm
14G     /var/lib/docker/overlay2
44K     /var/lib/docker/volumes
14G     /var/lib/docker

**Comment by wojiushixiaobai** [comment]
Docker 所有镜像都存储在 /var/lib/docker/overlay2，可以通过 `docker inspect <container name or id>` 查询
具体的占用可以通过 `docker system df ` 进行查询，自行将不需要的镜像移除。

容器内部使用 `service name` 通信，因此不停的访问 `dns`  服务器是正常现象。如果你不希望使用容器化部署，可以自行根据实际需求自行部署。
