### ISSUE TITLE
[Question] jumpserver作业管理如何取消

### ISSUE THREAD

**Issue by chenconghe** [jumpserver/jumpserver#12311]
**请描述您的问题.**
如何取消Jumpserver作业管理的作业，有时候一个作业执行了很久都没有结果，我想取消他，页面上也没有按扭，如果直接重启jms_celery后会立即把所有作业都重启执行一次，这个不符合我的需求，有什么别的方法吗？

**Comment by BaiJiangJie** [comment]
目前不能取消，没有太好的办法。

**Comment by chenconghe** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/59158123/3c1b7b03-5471-428b-a6c5-56f96891512e)
好像重启一次他作业管理就重新执行一次，我今天又重启了一次celery，他立马又执行一次作业 管理，但是昨天并没有按计划任务执行，是哪里有问题吗？

**Comment by BaiJiangJie** [comment]
你定时间设置的多少？间隔不要太短。

**Comment by BaiJiangJie** [comment]
计划 v3.10.4 优化一下。

**Comment by BaiJiangJie** [comment]
升级到最新版本，作业中心执行应该不会卡住了。
