### ISSUE TITLE
Issue with the French keyboard layout

### ISSUE THREAD

**Issue by lberrezoug** [jumpserver/jumpserver#12315]
Hi,
wanted to bring to your attention the issue with the French keyboard layout. Unfortunately, I am unable to input special characters such as '#' or '@,' which is quite inconvenient when entering the password for connecting to a Windows session, for example. This problem seems to persist whether my JumpServer profile or the workstation is configured with the French (AZERTY) keyboard layout.

Thank you for your attention to this issue, and I hope it will be resolved soon.

JumServer v3.9.2 

_Originally posted by @lberrezoug in https://github.com/jumpserver/jumpserver/issues/9752#issuecomment-1851844332_

**Comment by BaiJiangJie** [comment]
OK, we'll reproduce it and fix it.

But before reproducing, please provide the steps and process for reproducing, preferably with a demonstration video.

**Comment by rmoula** [comment]
i'v managed to recreat the issue on my envirement 
i hope this video would help you guys break this down ASAP 
Thank you 

https://github.com/jumpserver/jumpserver/assets/153616467/0d624395-46e6-417b-b85a-afff71c2bf99

**Comment by lberrezoug** [comment]
thanks rmoula, and indeed, I’ve noticed the same thing. When you have the keyboard set to US layout, it lets you type in AZERTY, but special characters such as # and @, in short, those that require key combinations, don’t work.

**Comment by BaiJiangJie** [comment]
Windows PC default keyboard language is also set to French, and Windows server keyboards are also set to French by default, right?

Take a screenshot to show me your PC and server keyboard default settings.

@lberrezoug @rmoula

**Comment by rmoula** [comment]
I can confirm that the key board is Azerty on both virtual and phisical machine 
![physica_Machine](https://github.com/jumpserver/jumpserver/assets/153616467/f6e450ae-4096-4571-a8b6-2677eecfd779)
![VM](https://github.com/jumpserver/jumpserver/assets/153616467/0e7211ba-056a-4fa5-aeec-e994a429ec9e)

**Comment by BaiJiangJie** [comment]
The latest version（v3.10.1） has been fixed. It is recommended to upgrade to the latest version for use. If the problem still exists, please reopen the issue.
