### ISSUE TITLE
[Feature] 发布机、webterminal

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#12317]
**请描述您的需求或者改进建议.**
版本3.9.3
1、远程应用的发布机的账号管理不是特别方便，
      模版账号的建立智能在发布机添加的时候建立，
      建立后也不知道在哪里能删除，修改
2、webterminal 底部的发送到所有所有ssh终端功能好像失效了

**Comment by BaiJiangJie** [comment]
2、webterminal 底部的发送到所有所有ssh终端功能好像失效了

这个问题会在 v3.10 优化。

**Comment by BaiJiangJie** [comment]
1. 建立之后在发布机的详情中进行删除。
