### ISSUE TITLE
发邮件异常，jumpserver.log异常

### ISSUE THREAD

**Issue by blank614** [jumpserver/jumpserver#1232]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
version 1.2.0-2 
##### 问题复现步骤
问题1，安装完成后，页面展示什么都正常，但是发邮件异常，测试邮件链接也没有问题，提示如下：
    _```
这个链接有效期1小时, 超过时间您可以<a href="http://localhost/users/password/forgot?email=web-b9h5j@mail-tester.com">重新申请</a>

    </br>
    ---

    </br>
    <a href="http://localhost/users/login">直接登录</a>

    </br>
```_
    一个是地址不应该是localhost，另外一个是无法收到这个邮件
celery.log 日志如下：
```
TaskPool: Apply <function _fast_trace_task at 0x7f833241c2f0> (args:('terminal.tasks.clean_orphan_session', 'f4fd4e12-667b-48ea-b267-0774a8aee423', {'lang': 'py', 'task': 'terminal.tasks.clean_orphan_session', 'id': 'f4fd4e12-667b-48ea-b267-0774a8aee423', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f4fd4e12-667b-48ea-b267-0774a8aee423', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen4067@ip-172-31-0-252', 'reply_to': 'cf39598c-d398-3b4e-81df-1534e8156f08', 'correlation_id': 'f4fd4e12-667b-48ea-b267-0774a8aee423', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}}, b'\x80\x02)}q\x00}q\x01(X\t\x00\x00\x00callbacksq\x02NX\x08\x00\x00\x00errbacksq\x03NX\x05\x00\x00\x00chainq\x04NX\x05\x00\x00\x00chordq\x05Nu\x87q\x06.', 'application/x-python-serialize', 'binary') kwargs:{})
Task accepted: terminal.tasks.clean_orphan_session[f4fd4e12-667b-48ea-b267-0774a8aee423] pid:4094
Task assets.tasks.update_assets_hardware_info_period[ccfd17b1-8d7c-47f2-822a-bad6fa2e5e90] succeeded in 0.17674523300001965s: None
Task terminal.tasks.delete_terminal_status_period[53688784-e047-4b1c-bff7-7c901de3ff03] succeeded in 0.17463548700004594s: None
Task terminal.tasks.clean_orphan_session[f4fd4e12-667b-48ea-b267-0774a8aee423] succeeded in 0.1098132509999914s: None
Task assets.tasks.test_admin_user_connectability_period[13612e46-b48a-44b9-86dd-9704c305e4e7] succeeded in 16.352229058000034s: None
Received task: common.tasks.send_mail_async[1447e79b-57ba-450d-946c-bcbbad529808]  
TaskPool: Apply <function _fast_trace_task at 0x7f833241c2f0> (args:('common.tasks.send_mail_async', '1447e79b-57ba-450d-946c-bcbbad529808', {'lang': 'py', 'task': 'common.tasks.send_mail_async', 'id': '1447e79b-57ba-450d-946c-bcbbad529808', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '1447e79b-57ba-450d-946c-bcbbad529808', 'parent_id': None, 'argsrepr': '(\'重置密码\', \'\n    您好 XX:\n    </br>\n    请点击下面链接重置密码， 如果不是您申请的，请关注账号安全\n    </br>\n    <a href="http://localhost/users/password/reset?token=eyJhbGciOiJIUzI1NiIsImlhdCI6MTUyNDUzNDI2MCwiZXhwIjoxNTI0NTM3ODYwfQ.eyJyZXNldCI6ImExM2UzMWQ2LTJiNzAtNGE3ZC1iYTkwLTQ4YTg2OTBjMjE2YiIsImVtYWlsIjoid2ViLWI5aDVqQG1haWwtdGVzdGVyLmNvbSJ9.dpw2MZlG3isRT8_r9eHLsNx7Sz4QnchTAzTZWcFxCVI">请点击这里设置密码 </a>\n    </br>\n    这个链接有效期1小时, 超过时间您可以<a href="http://localhost/users/password/forgot?email=web-b9h5j@mail-tester.com">重新申请</a>\n\n    </br>\n    ---\n\n    </br>\n    <a href="http://localhost/users/login">直接登录</a>\n\n    </br>\n    \', [\'web-b9h5j@mail-tester.com\'])', 'kwargsrepr':... kwargs:{})
Task accepted: common.tasks.send_mail_async[1447e79b-57ba-450d-946c-bcbbad529808] pid:4094
Task common.tasks.send_mail_async[1447e79b-57ba-450d-946c-bcbbad529808] succeeded in 4.712159842000119s: None

```

问题2，jumpserver.log一直报如下错误：

> 2018-04-24 09:33:37 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z
> 2018-04-24 09:33:37 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z
> 2018-04-24 09:34:23 [base WARNING] Not Found: /UyUKc24B2QL-UhBvRFSMJg_G6ZdD-p_-RkF9Tkmvl8xtuBkFm4dYmEkyLGoVjhX8ZHeUOAk74wQdGSkH758i5MdixNLNJBJT7Ovad2uL52lBmLbRLR-FJuF9bpq1z47G7H53EE_MbRkaDXDhri8xsQIdeieZDq6kRPAE5bwuODmA
> 2018-04-24 09:34:23 [base WARNING] Not Found: /UyUKc24B2QL-UhBvRFSMJg_G6ZdD-p_-RkF9Tkmvl8xtuBkFm4dYmEkyLGoVjhX8ZHeUOAk74wQdGSkH758i5MdixNLNJBJT7Ovad2uL52lBmLbRLR-FJuF9bpq1z47G7H53EE_MbRkaDXDhri8xsQIdeieZDq6kRPAE5bwuODmA
> 2018-04-24 09:36:12 [base WARNING] Not Found: /jO6T2Xz8tWikSFS9c0vcuwVr_2Mt0meTwA5J7C-i7WMmOYdNfSxHokmm7eYtzvos9-BZN1WKdTiSbZgkZNbCx2TrzK8TLVFH1IQoMf7snfa-Sw9bfqxGH8OoQCJ6IOPINF3kjSTFZYiLODpqIyEuJs
> 2018-04-24 09:36:12 [base WARNING] Not Found: /jO6T2Xz8tWikSFS9c0vcuwVr_2Mt0meTwA5J7C-i7WMmOYdNfSxHokmm7eYtzvos9-BZN1WKdTiSbZgkZNbCx2TrzK8TLVFH1IQoMf7snfa-Sw9bfqxGH8OoQCJ6IOPINF3kjSTFZYiLODpqIyEuJs
> 2018-04-24 09:36:57 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z
> 2018-04-24 09:36:57 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z
> 2018-04-24 09:40:17 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z
> 2018-04-24 09:40:17 [base WARNING] Not Found: /SOZQYrAn1RZ1eERf_GQ-XgKXcZqSAx30BZ582QXNYqxNBzoQWqVlsihUVPjj5K0rgVKSUW1MtCpEZa43Kag6mX4uHuMJ98_nd5Gu9y_gn2c3h-hmDX-XAMU7H-YQNB5nsOX5EPMfwlPQ68gkkGMO3z



问题3
仪表盘/用户管理  /用户授权资产内，无法有显示已添加的资产，即无法授权用户资产


##### 具体表现[截图可能会更好些,最好能截全]


##### 其他


[注:] 完成后请关闭 issue
![1](https://user-images.githubusercontent.com/20389919/39161845-403213d0-47a5-11e8-82ed-63d9e93049a9.png)
![2](https://user-images.githubusercontent.com/20389919/39161851-44ce8216-47a5-11e8-8e4c-873aaca76357.png)

![3](https://user-images.githubusercontent.com/20389919/39161803-10cac84e-47a5-11e8-8b78-2d88cbf5db4b.png)

**Comment by wojiushixiaobai** [comment]
无法显示资产的问题，更新下代码。

邮件问题参考faq第9条
其他问题
(1). 邮箱设置 新建用户无法收到邮件需要重启一次jumpserver（系统设置修改需要重启的问题后面会修正）

(2). 收到的邮件链接地址是 localhost 可以到 系统设置-基本设置 里面修改url，保存后重启即可

**Comment by blank614** [comment]
第二个问题，解决了，但是第一个问题任然异常，具体错误我查了下，大致是说发邮件的程序没有把from谁加上，具体可以看下我上传的报错截图，谢谢~
![1](https://user-images.githubusercontent.com/20389919/39166570-ec6fac04-47bc-11e8-8078-c264118868d7.png)

**Comment by MaloneQQ** [comment]
1.修改测试邮件的发件人地址：
![image](https://user-images.githubusercontent.com/9944635/40472658-acd17b14-5f6c-11e8-9709-56b573dbab28.png)

2.修改常用通知邮件发信人地址：
![image](https://user-images.githubusercontent.com/9944635/40472699-cc757ed4-5f6c-11e8-8b69-44b754a5d405.png)

建议官方在SMTP配置中增加设置发信人地址功能
