### ISSUE TITLE
添加网域网关的资产进行账号推送时，账号校验失败

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#12322]
升级至3.9.3版本，在资产需配置网域网关的情况下才能与JS建立通信，进行账号推送时，仍报错连接超时(当配置好网络，不走网域网关后，账号推送测试OK)
![e701d683a13b8845ec14f1a7bc1bcf72_](https://github.com/jumpserver/jumpserver/assets/92150453/5244f0d9-d6cd-4f0a-87eb-6e1f5f761d08)
![b6d9a562dd3ce79820d946a7e21879d1_](https://github.com/jumpserver/jumpserver/assets/92150453/ca5a0829-fe23-45d1-9b9a-f09a814f37a8)

_Originally posted by @sageonedream in https://github.com/jumpserver/jumpserver/issues/12080#issuecomment-1853452513_

**Comment by BaiJiangJie** [comment]
先不要推送，配置好资产的网域网关，先测试一下特权账号的可连接性。看看结果会不会报错。

**Comment by BaiJiangJie** [comment]
如果还有问题，reopen！
