### ISSUE TITLE
[Question] 文件管理功能web端下载文件失败

### ISSUE THREAD

**Issue by carpediem-777** [jumpserver/jumpserver#12338]
**请描述您的问题.**
web端下载>100M的文件失败，sftp客户端正常。
<img width="1919" alt="image" src="https://github.com/jumpserver/jumpserver/assets/24445264/fbcfc57a-1242-41fd-a886-d18d7d357e41">

**Comment by carpediem-777** [comment]
sftp客户端也下载失败☹️

**Comment by LeeEirc** [comment]
使用的那个版本的 JumpServer，看下 koko 的日志，`docker logs -f --tail=100 jms_koko`  
另外可能是审计文件造成的超时，可以把 nginx 的超时时间设置的大一些。 
sftp 可以试试命令行，如果是 sftp 的客户端，设置下超时时间。

**Comment by carpediem-777** [comment]
版本是3.9.3；部署方式使用的HELM；我通过更改jumpserver-jms-web的config文件，临时加上超时时间后可以了，不过helm chart中配置相应的dev不起作用。

**Comment by LeeEirc** [comment]
这个大文件留存审计，造成的超时问题，将在 v3.10 中优化。另外后续可以通过配置 `FTP_FILE_MAX_STORE=0`不对文件进行留存。

**Comment by carpediem-777** [comment]
好的，感谢回复！

**Comment by BaiJiangJie** [comment]
请关注后续版本的发布。

**Comment by carpediem-777** [comment]
OK👌
