### ISSUE TITLE
[Feature] 标签资产希望允许设置“备注”列

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#12331]
**请描述您的需求或者改进建议.**
标签资产显示了“备注”字段，但是更新或者创建的时候，无法设定“备注”信息。
希望允许设置该信息，以方便资产管理。

**Comment by BaiJiangJie** [comment]
<img width="1154" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/cf3a2fa2-aff9-4675-8f68-6296cda10c81">

v3.10 版本会支持。对标签有比较大的优化。

**Comment by BaiJiangJie** [comment]
请关注最新版本的发布。（预计下周会发布）

**Comment by khy2021** [comment]
谢谢
