### ISSUE TITLE
时间太长的历史会话无法回放

### ISSUE THREAD

**Issue by stephen8339** [jumpserver/jumpserver#1233]
[简述你的问题]
超过1小时的历史会话无法回放
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.2.0-2 jumpserver git md5 e865484a56d6ae2a94a4d2f543f3d7934cfe9a7a

##### 问题复现步骤
1. [步骤1]长时间保持会话，做适当操作并退出
2. [步骤2]在网页上回放会话，显示无法下载

##### 其他
使用了两台allinone的jumpserver+LB做高可用

**Comment by wojiushixiaobai** [comment]
我这有超过4小时的记录，可以正常播放，检查下网络。

**Comment by stephen8339** [comment]
我看聊一下日志显示：
 Not Found: /api/terminal/v1/sessions/61f33065-f2df-4ddc-be97-d7aa08995217/replay/
请问这日志是存在哪里的，我检查一下

**Comment by ibuler** [comment]
可能没有上传录像成功
