### ISSUE TITLE
[Bug] 纳管 Linux 资产， 服务端sshd_config 配置Ciphers算法， 资产连接失败

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#12335]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V 3.9.0

**浏览器版本**
谷歌浏览器

**Bug 描述**
纳管 Linux 资产， 服务端sshd_config 配置Ciphers算法， 配置的规则为： Ciphers aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc ,资产连接失败

**Bug 重现步骤(有截图更好)**
1.  连接失败的情况：
服务器资产操作系统： Centos 7.6
1.1  修改服务器端的 /etc/ssh/sshd_config , 新增如下的规则：
<img width="668" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/56aab017-1a59-44fc-b2d2-472e25d1a46f">

重启 sshd 服务：systemctl restart sshd

1.2 可以看到此时资产支持的 ssh 加密算法，如下：
<img width="412" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/5b97a5c0-b186-4d33-9ba1-12c8e78685f1">

1.3 此时 JumpServer 连接失败，如下：
<img width="775" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/5cc8008c-30db-4ecc-9256-62a9ffd43b32">

2. 连接成功的情况：
2.1 不修改 sshd_config ，可以看到此时服务器资产支持的加密算法如下：
<img width="1388" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/5044b6e6-f4bc-4c93-990d-abc71e5f744a">

2.2 可以看到，和连接成功的场景对比，客户的 Linux 资产sshd_config 少了如下的算法就会导致连接失败：
chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,blowfish-cbc,cast128-cbc

猜测：堡垒机的逻辑 是不是 随机使用 这里的某个算法去连接资产，结果资产 sshd_config 里面没配置支持这种算法，导致连不上呢？
![image](https://github.com/jumpserver/jumpserver/assets/30264974/b5d3c39c-f202-4b1a-bd28-aef40684a0e1)

**Comment by BaiJiangJie** [comment]
好的，明天研究一下。

**Comment by BaiJiangJie** [comment]
@LeeEirc 帮看一下。

**Comment by LeeEirc** [comment]
golang ssh 库如果使用 `aes128-cbc` 和 openssh-server 会协商失败，建议修改下配置，增加一些 golang 底层库支持的加密算法

```
	"aes128-gcm@openssh.com", "aes256-gcm@openssh.com"
	"chacha20-poly1305@openssh.com",
	"aes128-ctr", "aes192-ctr", "aes256-ctr",
```
或者 sshd_config 配置按照如下方式修改：

![image](https://github.com/jumpserver/jumpserver/assets/32626707/48480630-7f72-41b7-9c38-455f49478011)
