### ISSUE TITLE
[Bug] 3.9.3升级后连接WEB资产报错 提示网络不可达或者安全策略错误 

### ISSUE THREAD

**Issue by joy88888888** [jumpserver/jumpserver#12339]
![1](https://github.com/jumpserver/jumpserver/assets/33371884/1db64079-24a5-4a65-85ae-8ce8b338e7fe)
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.发布机正常 测试也OK
2.网络也都是通的
3.

**Comment by BaiJiangJie** [comment]
看一下 Lion 组件的日志。

**Comment by joy88888888** [comment]
> 看一下 Lion 组件的日志。

怎么看

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/faq/faq/

**Comment by joy88888888** [comment]
> https://docs.jumpserver.org/zh/v3/faq/faq/

没找到啊  能不能是自带的RDS授权到期了 连接不上啊

**Comment by joy88888888** [comment]
![2](https://github.com/jumpserver/jumpserver/assets/33371884/b015bdc9-7994-4676-9b96-db6be6ab018d)

**Comment by BaiJiangJie** [comment]
也有可能，你换台机器试试。

**Comment by joy88888888** [comment]
> 也有可能，你换台机器试试。

那这种情况怎么解决  每次到期都需要重新换个发布机？

**Comment by BaiJiangJie** [comment]
那你试试使用原生的远程客户端能不能连接成功？

**Comment by joy88888888** [comment]
> 那你试试使用原生的远程客户端能不能连接成功？

远程桌面可以连接啊

**Comment by BaiJiangJie** [comment]
用 windows 自带的远程桌面软件，连接远程应用试试。

**Comment by BaiJiangJie** [comment]
之前好像有用户遇到过，建议购买一个正版的 RDS。

https://github.com/jumpserver/jumpserver/issues/11871

**Comment by joy88888888** [comment]
> 之前好像有用户遇到过，建议购买一个正版的 RDS。
> 
> #11871

我服务器上有RDS怎么来使用啊  我发现也不行啊  有配置说明参考吗

**Comment by BaiJiangJie** [comment]
这个应该看 windows 官方文档。

**Comment by zk1215056613** [comment]
我也遇到了类似的问题，我的管理员账号可以正常连接web资产，但是我新建的账号连接web资产时就会报错

**Comment by BaiJiangJie** [comment]
购买正版 RDS 解决。
