### ISSUE TITLE
[Bug] 远程应用的账号默认都被禁用了

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#12344]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
![图片](https://github.com/jumpserver/jumpserver/assets/19767613/910428e6-de13-4b1f-8b94-95ac7db60ffd)

如果，jumpserver 界面都被禁用，删除重新生成也是一样。
然后到远程应用所在的服务器，账号是存在，也没有被禁用。

至于怎么复现，怎么出现的，不是很清楚

**Comment by BaiJiangJie** [comment]
需要确认发布机的状态，发布机上的 Tinker 进程会更新发布机账号的激活状态。

是不是发布机部署成功？

**Comment by xzqiaochu** [comment]
请问 “发布机上的 Tinker 进程会更新发布机账号的激活状态” 是以怎样的计划运行的？在JumpServer添加新账号后，发布机会出现“js_用户名”这样的账号，但刚开始是禁用状态，一段时间后变成激活状态，但是在 活动记录 中并没有看到添加账号的任务
