### ISSUE TITLE
登录终端重复输入序号登录显示错乱以及无法登录，无法上下左右

### ISSUE THREAD

**Issue by freelinuxer-cn** [jumpserver/jumpserver#1234]
[简述你的问题]
coco ssh 到终端上 直接输入序号登录错乱，如果打p 的话 会复位 再按序号就能正常。退出资产后 
再打别的登录序号就会有问题了.

##### 使用版本
jumpserver Version 1.2.0-2 

##### 问题复现步骤
 
![1](https://user-images.githubusercontent.com/24829782/39164578-ade5b9f6-47b2-11e8-9f44-b1b157b2a49e.jpg)
![qq 20180424112730](https://user-images.githubusercontent.com/24829782/39164601-be98cd60-47b2-11e8-98ce-9a326507ffff.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这里可能是设计上的一个问题，序列号是动态生成的，不是某个资产固定的序列号，所以必须p以后才能使用序列号登录

**Comment by freelinuxer-cn** [comment]
登陆的时候 自动记住 p 结果序号, 每次p 才更新序号这样是不是好点呢.

**Comment by ibuler** [comment]
其实使用 ip后面几位登陆比较好一些

**Comment by ibuler** [comment]
与 #1200 重复
