### ISSUE TITLE
[Question] 版本V3.7.1 通过Jump远程RDP协议连接Windows机器 无法识别物理机的Usb key，但是通过ldrac连接可识别

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#12352]
版本V3.7.1 通过Jump远程RDP协议连接Windows机器 无法识别物理机的Usb key，但是通过ldrac连接可识别
<img width="179" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/afb656da-ac4e-4f4b-bfae-e0952cfa5823">

**Comment by BaiJiangJie** [comment]
目前确实不支持。
