### ISSUE TITLE
历史命令记录不完整

### ISSUE THREAD

**Issue by stephen8339** [jumpserver/jumpserver#1235]
[简述你的问题]
遇到较长的命令，在历史命令里显示不完整

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.2.0-2

##### 问题复现步骤
1. [步骤1]在服务器上使用较长的命令
2. [步骤2]查看历史命令，记录不完整但是返回记录的是正确的

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/20554349/39164728-a539d03e-47b3-11e8-8772-9f8f6faba2d4.png)
![2](https://user-images.githubusercontent.com/20554349/39164732-a835fea2-47b3-11e8-9a30-76cc00baf62a.png)

##### 其他
使用了两台allinone的jumpserver+LB做高可用

**Comment by stephen8339** [comment]
又试了一次，录像记录了，历史命令还是不正确，可能是我用了自动补全的关系？
![5](https://user-images.githubusercontent.com/20554349/39167959-73a06dc4-47c4-11e8-8b71-65d9a87c0dc6.png)
![6](https://user-images.githubusercontent.com/20554349/39167962-751729d6-47c4-11e8-8cab-5a0926c7bbff.png)

**Comment by stephen8339** [comment]
有人能关注一下这个问题吗？个人认为还挺严重的问题

**Comment by ibuler** [comment]
开始关注

**Comment by ibuler** [comment]
#1281

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues

**Comment by xionghui** [comment]
能贴一下怎么解决的么？哪里出的问题。我这边是偶现出现命令不完整的情况。
