### ISSUE TITLE
[Bug] 账号推送sudo问题

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#12351]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.3

**浏览器版本**
Edge 120.0.2210.77

**Bug 描述**
账号推送sudo的时候NOPASSWD没有跟着改变，还是whoami

**Bug 重现步骤(有截图更好)**
1.账号管理---账号推送
2.创建一个推送规则（Linux）
3.推送参数，sudo模块填写ALL
4.系统内visudo查看推送的规则为 sa ALL=(ALL) NOPASSWD: /bin/whoami

**Comment by BaiJiangJie** [comment]
如果账号已经存在了，就不会更新了。

只有通过推送任务新创建的账号才会修改。

**Comment by wushengmin** [comment]
好的 我这里再尝试一下
