### ISSUE TITLE
[Feature] 云同步任务设置定期执行，定期执行的cron和周期只填其一即可

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12356]
云同步任务设置定期执行，这里我已经设置了定期执行的cron，每天0点执行，为啥周期执行还要输入呢？
我理解的是，这里cron和周期执行只填其一就可以了吧

**Comment by BaiJiangJie** [comment]
<img width="1053" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/8cad2133-0dc1-4a5e-a5f4-e5a0b0c57e5e">

正常是只填写一个就行，同时也只会有一个生效。

历史原因，周期执行字段必须填写。
