### ISSUE TITLE
[Feature] 资产列表根据ID查询资产，优化错误提示

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12357]
![image](https://github.com/jumpserver/jumpserver/assets/15103510/9bd4f103-6ec2-47f6-8485-fbe0d6709646)
输入的不是uuid，查询报错提示“请求错误，请检查输入内容”，是不是可以优化下报错提示 “请输入正确的uuid”呢

**Comment by BaiJiangJie** [comment]
其实后端已经返回回来了，前端是统一处理的，可能不好获取。

<img width="1124" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/07e1e387-8eb1-4b37-be5b-52e385b7ae7a">

**Comment by BaiJiangJie** [comment]
目前搞不定。

**Comment by liufei20151013** [comment]
但是这个报错给用户看到不太友好吧
