### ISSUE TITLE
[Bug] 3.9.3社区版，批量执行华为交换机报错

### ISSUE THREAD

**Issue by Powerlgh** [jumpserver/jumpserver#12362]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

产品:	JumpServer 社区版 GPLv3
版本:	v3.9.3

**浏览器版本**
Microsoft Edge
版本 120.0.2210.77 (正式版本) (64 位)

**Bug 描述**
华为交换机配置好ssh v2版本，可以通过web界面进行管理。
但无法在“工作台”，“快捷命令”，选中多台交换机，运行。系统要么报错连接不上交换机，要么无法超时，一下处于等待状态，运行时间那，一直在增长，无法自动结束。

等待
huawei_181 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.100.181' (RSA) to the list of known hosts.\r\nShared connection to 192.168.100.181 closed.",
    "unreachable": true
}
huawei_182 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '192.168.100.182' (RSA) to the list of known hosts.\r\nShared connection to 192.168.100.182 closed.",
    "unreachable": true
}

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/110659497/cafd81ba-b46b-4d16-b0c8-a302cb50e9b9)
![image](https://github.com/jumpserver/jumpserver/assets/110659497/e7fab9cf-0548-4660-9943-0b805b924537)
![image](https://github.com/jumpserver/jumpserver/assets/110659497/0c8bd3a4-7193-469f-a58a-8748c404bd85)
![image](https://github.com/jumpserver/jumpserver/assets/110659497/ee1366e9-15f9-42ed-b876-120503f38eef)
![image](https://github.com/jumpserver/jumpserver/assets/110659497/c5215282-e52a-4e17-9a5e-51f1d3b97b2b)

**Comment by BaiJiangJie** [comment]
交换机上有 python 解释器吗？

**Comment by Powerlgh** [comment]
所有网络设备里，都没有python环境。
但ansible管理交换机，是通过raw模块来处理，我通过web界面是可以单独管理交换机。
意思堡垒机中的“批量管理”功能能使用，必须要求终端设备，要有python环境，不能用raw模块？

**Comment by BaiJiangJie** [comment]
都有 python 环境的话应该是可以的。

看一下，测试交换机的可连接性是成功的吗？

**Comment by BaiJiangJie** [comment]
进入 jms_celery 容器，使用 ssh 命令进行连接网络设备，看一下能不能成功？

**Comment by Powerlgh** [comment]
进到jms_celery容器，用ssh连接华为交换机是正常的。
贵司原厂有没有测试环境，可自行测下。
![image](https://github.com/jumpserver/jumpserver/assets/110659497/b31e0d1d-a853-41a6-b124-5415b7755d66)

**Comment by Powerlgh** [comment]
批量对交换机执行命令，依旧报错。
![image](https://github.com/jumpserver/jumpserver/assets/110659497/e1ce4336-a55c-4a0d-8f68-d13b5bf0cdf5)

**Comment by jym503558564** [comment]
这个是已知问题，待修复。

**Comment by BaiJiangJie** [comment]
v3.10.8 已修复。
请关注后续版本发布，及时升级。
