### ISSUE TITLE
查询终端状态mysql发生死锁

### ISSUE THREAD

**Issue by stephen8339** [jumpserver/jumpserver#1236]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.2.0-2，使用两台allinone的jumpserver做高可用
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![3](https://user-images.githubusercontent.com/20554349/39166445-4cdb1642-47bc-11e8-9654-46aa072efad6.png)

**Comment by wojiushixiaobai** [comment]
数据库有没有做主从

**Comment by stephen8339** [comment]
没有，aws的rds，没做主从

**Comment by wojiushixiaobai** [comment]
@stephen8339 数据库被多个应用使用，锁表不是很常见吗？

**Comment by stephen8339** [comment]
@wojiushixiaobai 锁表是挺正常的，但是死锁有时候会发生问题，如果这不会影响程序功能的话那当然就没问题

**Comment by ibuler** [comment]
新版本最近没有发现这个问题，暂时关闭
