### ISSUE TITLE
jumpserver报错

### ISSUE THREAD

**Issue by blank614** [jumpserver/jumpserver#1237]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
v1.2.0
##### 问题复现步骤
1. [步骤1]添加了一台资产之后，留意到jumpserver.log就一直报一个类似的错误：
![1](https://user-images.githubusercontent.com/20389919/39170608-c00badea-47ce-11e8-8a8f-a1fa475ee55c.png)

[注:] 完成后请关闭 issue

**Comment by blank614** [comment]
快醉了，发现是jumpserver里面的配置文件config.py里面的mysql之前配置相关的不在development函数里面，改了就没事了

**Comment by ibuler** [comment]
非正常请求，检查是不是有人扫描
