### ISSUE TITLE
[Feature] 支持像xshell这种，发送指令到所有会话的功能

### ISSUE THREAD

**Issue by wang-xiaowu** [jumpserver/jumpserver#12378]
**请描述您的需求或者改进建议.**

目前的这种单行文本发送到所有会话的方式在一些场景下功能过于单一
支持像xshell这种，发送指令到所有会话的功能会更友好

![image](https://github.com/jumpserver/jumpserver/assets/44340137/e4f75752-e6c3-4690-a743-17511a73c60c)

**Comment by BaiJiangJie** [comment]
支持单行命令发送，也支持复杂命令发送。

xshell 这种是批量发送快捷键？比如：Ctrl + C。是这个意思吗？

**Comment by wang-xiaowu** [comment]
> 支持单行命令发送，也支持复杂命令发送。
> 
> xshell 这种是批量发送快捷键？比如：Ctrl + C。是这个意思吗？

是的
我贴了张操作xshell发送全部指令到所有会话的动态图在下面
![gif](https://github.com/jumpserver/jumpserver/assets/44340137/87b5aade-7013-451e-a88e-522b3fd15c74)

**Comment by BaiJiangJie** [comment]
输入命令的话是可以的，只不过需要在 Luna 页面下方先输入，然后点击执行。

v3.10 支持发送到所有会话。

**Comment by BaiJiangJie** [comment]
<img width="1243" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/4d327faa-9a17-4431-b49b-46be80823694">

**Comment by wang-xiaowu** [comment]
好的，看来是已经有类似功能在开发了，那我等3.10发布出来再看下吧，谢谢

**Comment by BaiJiangJie** [comment]
嗯，之前版本也支持，v3.10 是做了优化。
