### ISSUE TITLE
[Feature] 考虑支持下Chatgpt4.0的选项

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#12370]
**请描述您的需求或者改进建议.**
<img width="1003" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/2644ba44-9902-41a9-b088-ae39511b9712">
目前看，这个平台创建界面还未支持到ChatGpt4.0。看了看kael的源码，这个添加上去应该就是一个Key、Value的选项，应该直接调用官方的接口，然后替换model参数就行了。认为支持的工作量不大，小部分代码就行。这个能优化一下吗请问
![img_v3_0269_2b808a08-4b1d-4b24-8955-c4924204c42g](https://github.com/jumpserver/jumpserver/assets/85990572/097d4b8e-1148-4657-a278-e6f5f7dc47a8)
非常感谢

**Comment by BaiJiangJie** [comment]
<img width="940" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d14db039-7061-494c-96e3-61531ee8394e">

企业版本支持 GPT-4。
