### ISSUE TITLE
单机离线安装3.9.3社区版本遇到的问题

### ISSUE THREAD

**Issue by OpenBitOps** [jumpserver/jumpserver#12374]
近日在部署（单机 离线安装）3.9.3 社区版本中，遇到的问题，如下：
1. 配置中用户自定义的数据库（MySQL），数据库部署的网段（如172.16.1.0/24），并且仅限该网段的地址登录。在安装的配置中定义docker的子网（DOCKER_SUBNET=192.168.250.0/24），那么安装过程中会出现 无法连接到数据的错误，数据库报错：app@192.168.250.2不能登录数据库。这样意味着用户定义的数据库账号必须不做限制（配置成%）。
2. 解决问题1后，又遇到该账号并无创建的权限（数据库app账号并无create权限），django无法migration。

问题1：自定义数据库是否能仅限内网登录，而不需要开放全部？
问题2：允许用户自定义数据库，是否该说明数据库账号所需的权限，提供初始化的SQL。还是说安装的时候可提供高权限的数据库账号，安装完成后可用app应用账号？

**Comment by wojiushixiaobai** [comment]
你可以通过 `WAF` 来控制，容器里面的网段是 `NAT` 出去的，最终到 `MySQL` 上应该是宿主机的 `IP`。
但是实际建立连接的地址是容器的 `IP` 地址，所以如果你需要在 `MySQL` 上做策略你需要为 容器的 网段 和宿主所在的 局域网网段 进行授权。

权限方面大致需要：`SELECT, INSERT, UPDATE, DELETE, ALTER, CREATE, DROP, INDEX, REFERENCES, EXECUTE`
```mysql
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, CREATE, DROP, INDEX, REFERENCES, EXECUTE
ON jumpserver.* to 'jumpserver'@'host';
```

如果权限不足，JumpServer 会提示相应的权限错误。自己加上即可
