### ISSUE TITLE
不同版本jumpserver下Linux特殊字符支持问题

### ISSUE THREAD

**Issue by SnowsonZ** [jumpserver/jumpserver#12380]
**请描述您的问题.**
目前正在用2.x的jumpserver，遇到linux特殊字符问题。计划升级到3.x版本。想了解下不同版本针对特殊字符的支持问题。翻了下文档没找到。麻烦给个列表说明下。

**Comment by BaiJiangJie** [comment]
对 Linux 的特殊字符支持是什么？

**Comment by SnowsonZ** [comment]
> 对 Linux 的特殊字符支持是什么意思？

哪些特殊字符可以配置在密码中，哪些配置到密码中回报错。

**Comment by BaiJiangJie** [comment]
你可以稍微等一等，即将发布的 v3.10 版本，密码中除了 `{{` 开头，`}}` 结尾的，其他字符都可以。

**Comment by SnowsonZ** [comment]
> 你可以稍微等一等，即将发布的 v3.10 版本，密码中除了 `{{` 开头，`}}` 结尾的，其他字符都可以。

嗯，这个我知道了。因为我们目前在用2.x版本，需要了解下2.x版本都哪些是不支持的。

**Comment by BaiJiangJie** [comment]
具体是 v2 的什么版本？我帮你看一下。

**Comment by SnowsonZ** [comment]
> 
![img_v2_18f8ec1c-654a-45e5-8e4a-51f779c6872g](https://github.com/jumpserver/jumpserver/assets/12555482/4ee81adf-5ec8-45bb-9c4d-ca561624610c)

**Comment by SnowsonZ** [comment]
> 具体是 v2 的什么版本？我帮你看一下。

![img_v2_18f8ec1c-654a-45e5-8e4a-51f779c6872g](https://github.com/jumpserver/jumpserver/assets/12555482/33dd90ff-be9a-4c04-ad68-29faa69a6aaa)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/blob/v2.28.6/apps/assets/serializers/utils.py#L7

`{{` `'` `""` 不支持。

实际上：`}}` `{%` `%}` 也不支持。

**Comment by SnowsonZ** [comment]
> https://github.com/jumpserver/jumpserver/blob/v2.28.6/apps/assets/serializers/utils.py#L7
> 
> v3.10 之前的版本，`{{` `}}` `'` `"` `{%` `%}` 这些字符都不支持。

感谢
