### ISSUE TITLE
ip 取值错误 

### ISSUE THREAD

**Issue by shanjunmei** [jumpserver/jumpserver#12381]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.9.2
**浏览器版本**
所有

**Bug 描述**
 将jumpserver 放在lb之后 ，就无法获得客户真实ip了，永远获得是lb本身的地址， X-Forwarded-For 的逻辑正常来说 就是服务端代理用来向上游服务传递客户真实ip的，而且它是逐级追加的，所以理论上它应该永远获取X-Forwarded-For 的第一跳作为客户端ip，为防止恶意客户端为止，可信服务端的第一跳应该用客户请求地址直接覆盖 X-Forwarded-For 的值 ，而不是获取 优先获取X-Real-IP，或者 X-Forwarded-For的最后一跳值
 参考资料
   https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-Forwarded-For
  https://zhuanlan.zhihu.com/p/345273687#:~:text=X-Forwarded-For%3A%20client%2C%20proxy1%2C%20proxy2%20X-Forwarded-For%20%E8%AF%B7%E6%B1%82%E5%A4%B4%E7%9A%84%E5%86%85%E5%AE%B9%E7%94%B1%E8%8B%B1%E6%96%87%E9%80%97%E5%8F%B7%E5%92%8C%E7%A9%BA%E6%A0%BC%E9%9A%94%E5%BC%80%EF%BC%8C%E6%AF%8F%E7%BB%8F%E8%BF%87%E4%B8%80%E7%BA%A7%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%8CX-Forwarded-For,%E5%90%8E%E9%9D%A2%E5%B0%B1%E4%BC%9A%E7%BB%A7%E7%BB%AD%E6%B7%BB%E5%8A%A0%E8%AF%A5%E4%BB%A3%E7%90%86%E8%AE%BE%E5%A4%87%E7%9A%84IP%E5%9C%B0%E5%9D%80%E3%80%82%20%E5%9B%A0%E6%AD%A4%EF%BC%8C%E4%B8%80%E8%88%AC%E6%9D%A5%E8%AF%B4%EF%BC%8C%E6%88%91%E4%BB%AC%E8%A6%81%E8%8E%B7%E5%BE%97%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%9C%B0%E5%9D%80%EF%BC%8C%E7%9B%B4%E6%8E%A5%E4%BB%8E%20X-Forwarded-For%20%E6%8B%BF%E5%88%B0%E7%AC%AC%E4%B8%80%E4%B8%AA%20IP%20%E5%9C%B0%E5%9D%80%E5%8D%B3%E5%8F%AF%E3%80%82
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12246#issuecomment-1857175109

看一下这个 issue 的回答。

中间经过的所有 Nginx 都配置上这个参数。X-Forwarded-For

**Comment by shanjunmei** [comment]
> [#12246 (comment)](https://github.com/jumpserver/jumpserver/issues/12246#issuecomment-1857175109)
> 
> 看一下这个 issue 的回答。
> 
> 中间经过的所有 Nginx 都配置上这个参数。X-Forwarded-For

我并没有中间的nginx ，lb后面直接到的jumpserver

**Comment by BaiJiangJie** [comment]
那有配置 X-Real-IP 吗？

**Comment by shanjunmei** [comment]
> 那有配置 X-Real-IP 吗？

没有，无法配置

**Comment by wojiushixiaobai** [comment]
lb 传递过来的真实 ip 参数是什么？
自己去 nginx 日志里面打印出来看看，然后正确配置即可

**Comment by shanjunmei** [comment]
> X-Real-IP

lb 设置了 X-Forwarded-For :ip ,我分别尝试了以下两个指令都失败了    # `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 如果上层还有其他 slb 需要使用 $proxy_add_x_forwarded_for 获取真实 ip
proxy_set_header X-Forwarded-For $http_x_forwarded_for; `

**Comment by BaiJiangJie** [comment]
那你 LB 真实传递 IP 地址的是哪个配置？

**Comment by shanjunmei** [comment]
> X-Forwarded-For

lb 传递的是 X-Forwarded-For

**Comment by BaiJiangJie** [comment]
方便远程帮你调试看一下吗？

**Comment by shanjunmei** [comment]
> 方便远程帮你调试看一下吗？

不好意思，不方便哦，另外问题解决了，其中一个修改use_lb=0 ,这点很奇怪，难道use_lb=0 才是使用lb的设置？0不是false吗，还有一个问题，X-Forwarded-For中可能包含端口的，我猜测jumpserver对这种情况处理有问题，我不确定对于X-Forwarded-For有多个值的情况，又是怎样处理的

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/apps/common/utils/common.py#L157-L164

如果带端口，应该会将 `IP:PORT` 作为 LoginIP 进行记录。

如果是多个地址，会获取第一个作为 LoginIP。

**Comment by BaiJiangJie** [comment]
USE_LB=0 表示用户使用自己的 SLB，
USE_LB=1 表示用户使用 JumpServer 的 LB

![image](https://github.com/jumpserver/jumpserver/assets/32935519/c0c7701b-0df7-43d0-9f5e-668e4373f6e9)

**Comment by shanjunmei** [comment]
> USE_LB=0 表示用户使用自己的 SLB， USE_LB=1 表示用户使用 JumpServer 的 LB
> 
> ![image](https://private-user-images.githubusercontent.com/32935519/292447743-c0c7701b-0df7-43d0-9f5e-668e4373f6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzYzMDIsIm5iZiI6MTcwMzIzNjAwMiwicGF0aCI6Ii8zMjkzNTUxOS8yOTI0NDc3NDMtYzBjNzcwMWItMGRmNy00M2QwLTlmNWUtNjY4ZTQzNzNmNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA5MDY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Y2Y5ZTg3NjUwZDQ2OWZkODlmMzYyOGExMGFmODM1NGEwNGQ4ODI1MDVkZGM1YTgyMWEwNmMwOWVkNWMyZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PC4H1RvcwagrPKw4_Djz6f2k_erEIBrH3q_1Ksn2Khg)

了解了，多谢
