### ISSUE TITLE
ops_celerytask表数据疯狂增长

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1238]
启动beat后，后台不停地向API接口ops:celery-task-log发送请求，表ops_celerytask中数据疯狂增长，
一度达到百万级别。。

**Comment by ibuler** [comment]
不会这么疯狂吧，暂时关掉定时任务把，
```
 export PERIOD_TASK=0
```
重启

**Comment by gengkeye** [comment]
@ibuler 感觉新版定时任务太多了，很吃CPU和内存

**Comment by ibuler** [comment]
已默认关闭了定时任务，等待任务系统修复
