### ISSUE TITLE
[Question] v3.9.3 启用 IPv6 支持后，NGINX 未监听 IPv4

### ISSUE THREAD

**Issue by FengLing02** [jumpserver/jumpserver#12391]
今天使用全新的服务器安装 v3.9.3，启用 IPv6 支持后，发现 NGINX 未监听 IPv4
进入 web docker 内查看 NGINX 配置文件，发现只有 IPv6 的监听项
![image](https://github.com/jumpserver/jumpserver/assets/152166457/29f06308-b75f-4ea8-88b7-eed9b970db20)

**Comment by wojiushixiaobai** [comment]
下个版本修复

**Comment by FengLing02** [comment]
> 下个版本修复
> 
> * fix: [jumpserver/docker-web@6f74473](https://github.com/jumpserver/docker-web/commit/6f74473e97150016355c3bec961ab8e045229628)

您好，已升级至V3.10.1，但问题似乎依旧存在

**Comment by wojiushixiaobai** [comment]
检测 `/opt/jumpserver/config/nginx/lb_http_server.conf`，将其内容比对
- https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf

将端口监听部分的内容还原或者修改成你需要的内容即可。
