### ISSUE TITLE
[批量导入资产] 如何再导入资产的时候批量导入资产对应的账号模板？

### ISSUE THREAD

**Issue by Jack-Ywn** [jumpserver/jumpserver#12390]
在导入的表格模板中并没有账号模板的子段

**Comment by jym503558564** [comment]
账号字段格式如下：
可以直接添加账号，也可以添加模版账号，其中模版账号source值为template。
[
    {
        "username": "test",
        "secret": "123123"
    },
    {
        "source": "template",
        "template": "UUID"
    }
]

**Comment by Jack-Ywn** [comment]
![微信截图_20231223051552](https://github.com/jumpserver/jumpserver/assets/72083949/6d5b8d8d-3c33-4e44-823f-1bbc616898c0)
我bing
![image](https://github.com/jumpserver/jumpserver/assets/72083949/81b73e2e-8efc-4ff3-8707-0537d2d7b53b)
我这样来导入失败了，上图是我的账号模板信息，能否用表格演示下具体导入的用户和用户模板对应的表头和字段信息，非常感谢

**Comment by BaiJiangJie** [comment]
在批量导入资产的 Excel 模版中，有个账号字段，账号字段按照上面的格式写，指的就是账号模版，不是单独导入账号模版。
@Jack-Ywn 

> 账号字段格式如下： 可以直接添加账号，也可以添加模版账号，其中模版账号source值为template。 `[ { "username": "test", "secret": "123123" }, { "source": "template", "template": "UUID" } ]`

**Comment by Jack-Ywn** [comment]
恩，已经正常导入
