### ISSUE TITLE
[Bug] 设置全局组织的名称与现有组织重名，导致无法创建资产、改密计划

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12398]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**
chrome 版本 119.0.6045.199（正式版本） (x86_64)

**Bug 描述**
环境上已经有一个名称为信息部的组织，然后把全局组织的名称也改成了信息部，然后重新登录，切到信息部，发现无法创建资产、改密计划，这里重新登录后选择的信息部实际上应该是全局组织了，希望限制下全局组织的名称不能与现有组织名称重复。

**Bug 重现步骤(有截图更好)**
<img width="1433" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/3af2e6f4-9e83-4401-9c9b-34bda2edb300">

1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.10 已优化。
