### ISSUE TITLE
资产树，创建节点无反应。

### ISSUE THREAD

**Issue by cncentoscn** [jumpserver/jumpserver#12404]
**请描述您的问题.**
![WechatIMG162](https://github.com/jumpserver/jumpserver/assets/39993331/1b1615b6-2048-479c-9742-7da019b7df3e)

![WechatIMG163](https://github.com/jumpserver/jumpserver/assets/39993331/ea11293c-980b-4e3d-b25c-fe8e9f8a702c)
看不到任何报错，也不显示。

**Comment by cncentoscn** [comment]
Google Chrome 120.0.6099.129

**Comment by jym503558564** [comment]
JumpServer什么版本？

**Comment by cncentoscn** [comment]
最新版本v3.10.0，没有报错。
