### ISSUE TITLE
[Question] 想问一下v3.10.0-lts中所说的 feat: 新增 Chat AI 小助手功能（ChatGPT） 这个是指什么？是有额外的AI功能吗

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#12405]
如上 
想问一下v3.10.0-lts中所说的 feat: 新增 Chat AI 小助手功能（ChatGPT） 这个是指什么？是有额外的AI功能吗
如何使用呢？

**Comment by jym503558564** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40739051/9df88da9-791d-4496-b075-2e4805333709)

**Comment by xiaoxiongxyy** [comment]
> ![image](https://private-user-images.githubusercontent.com/40739051/292398569-9df88da9-791d-4496-b075-2e4805333709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzEzNjYsIm5iZiI6MTcwMzIzMTA2NiwicGF0aCI6Ii80MDczOTA1MS8yOTIzOTg1NjktOWRmODhkYTktNzkxZC00NDk2LWIwNzUtMmU0ODA1MzMzNzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA3NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYjdiZGQ0YzM3OTQ4YzU4NzdiNzY3YTIyYWYzMzM5OTIzMDdiYjMyMWQ4YmM2ZDk2OWExN2I5MzVmZTM1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4qvCBio6mRcRpyc6zuq4YWPtIa_QgFKCV4wBiyJykY4)

这个基本地址是和Chatgpt资产里一样 填API的地址吗？我这边填一样的 感觉好像连接不上呢

**Comment by BaiJiangJie** [comment]
地址是一样的，正常资产如果能连接的话，Chat AI 应该也可以连接。

**Comment by xiaoxiongxyy** [comment]
> 地址是一样的，正常资产如果能连接的话，Chat AI 应该也可以连接。

噢噢噢 除开这个Chat AI。该版本还有加入其他AI方面的更新吗

**Comment by BaiJiangJie** [comment]
v3.10 只增加了，Chat AI，其他目前没有了。

**Comment by xiaoxiongxyy** [comment]
> v3.10 只增加了，Chat AI，其他目前没有了。

好的哈 谢谢～
