### ISSUE TITLE
[Bug] 活动记录 UNION 的类型 character varying 和 uuid 不匹配

### ISSUE THREAD

**Issue by zhoufaming** [jumpserver/jumpserver#12411]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
master分支代码

**浏览器版本**

**Bug 描述**
刷新活动记录页面时，接口异常报错UNION 的类型 character varying 和 uuid 不匹配
from django.db.models.functions import Cast

    @staticmethod
    def get_operate_log_qs(fields, limit, org_q, resource_id=None):
        q, user = Q(resource_id=resource_id), None
        if is_uuid(resource_id):
            user = User.objects.filter(id=resource_id).first()
        if user is not None:
            q |= Q(user=str(user))
        queryset = OperateLog.objects.filter(q, org_q).annotate(
            r_type=Value(ActivityChoices.operate_log, CharField()),
            #将F('id')修改成Cast(F('id'), CharField())接口不再报错
            r_detail_id=F('id'), r_detail=Value(None, CharField()),
            r_user=F('user'), r_action=F('action'),
        ).values(*fields)[:limit]
        return queryset

    @staticmethod
    def get_activity_log_qs(fields, limit, org_q, **filters):
        queryset = ActivityLog.objects.filter(org_q, **filters).annotate(
            r_type=F('type'), r_detail_id=F('detail_id'),
            r_detail=F('detail'), r_user=Value(None, CharField()),
            r_action=Value(None, CharField()),
        ).values(*fields)[:limit]
        return queryset
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
使用的什么类型的后端数据库，不是MySQL吗？

**Comment by zhoufaming** [comment]
@BaiJiangJie 使用的是postgresql数据库

**Comment by BaiJiangJie** [comment]
还有其他报错吗？

**Comment by zhoufaming** [comment]
@BaiJiangJie 没有了 目前只发现这一个报错

**Comment by BaiJiangJie** [comment]
之前也一直使用的pg吗？

**Comment by zhoufaming** [comment]
之前用的小于3.0版本 配置的pg 没有问题

**Comment by zhoufaming** [comment]
@BaiJiangJie

**Comment by BaiJiangJie** [comment]
好的，你测试一下没问题，直接向 dev 分支提交个 PR 就可以了。
@zhoufaming

**Comment by zhoufaming** [comment]
@BaiJiangJie 在postgresql数据库测试 目前接口数据正常返回了，对应detail_url数据也包含了对应的detail_id
![Dingtalk_20231228175234](https://github.com/jumpserver/jumpserver/assets/29621766/3aa9d024-f007-48ac-bab0-c585caa8c1cd)

![695E2B07-1DA9-4bcb-8C21-062C09FF6685](https://github.com/jumpserver/jumpserver/assets/29621766/256045fb-a5ed-47a6-87ba-f507ed784156)

@BaiJiangJie

**Comment by zhoufaming** [comment]
@BaiJiangJie  PR 已提交

**Comment by BaiJiangJie** [comment]
好的，感谢。

测试没问题的话，计划在 v3.10.2 中上线。
