### ISSUE TITLE
服务器中8081的端口被占用了，如何去更改jumpserver中的8081端口

### ISSUE THREAD

**Issue by zhangxiongfu** [jumpserver/jumpserver#1241]
服务器中8081的端口被占用了，如何去更改jumpserver中的8081端口

**Comment by gengkeye** [comment]
>docker run --name jms_guacamole -d \
>  -p 8081:8080 -v /opt/guacamole/key:/config/guacamole/key \
>  -e JUMPSERVER_KEY_DIR=/config/guacamole/key \
> -e JUMPSERVER_SERVER=http://<填写本机的IP地址>:8080 \
> registry.jumpserver.org/public/guacamole:1.0.0

你把上面的8081换成其它端口不就行了吗

**Comment by gengkeye** [comment]
默认配置是：
jumpserver 8080 
jms_guacamole 8081 
coco sshd 2222
coco httpd 5000
这些端口在配置文件中可以更改的
