### ISSUE TITLE
[Feature] 远程应用发布机创建的Administrator账号不能够被轻易删除或者删除提示

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#12415]
**请描述您的需求或者改进建议.**
<img width="915" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/6cee26d1-44e0-462e-a106-66d0cb71b99e">
原因：如果选择批量删除时不小心删除了Administrator账号，会影响发布机的正常使用，比如无法进行资产连通性检测。

**Comment by jym503558564** [comment]
v3.10.1已修复，请升级至v3.10.1进行测试。
