### ISSUE TITLE
[Bug] 用户下线后luna终端并不会下线用户登陆的ssh

### ISSUE THREAD

**Issue by emran519** [jumpserver/jumpserver#12412]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0

**浏览器版本**
chrome

**Bug 描述**
用户被下线后，如果此时用户已经登陆了ssh，则ssh不会断开链接，用户还能继续操作服务器；

**Bug 重现步骤(有截图更好)**
1.审计台中->在线用户->操作 下线该用户；
2.用户如果已经在luna面板中并且登陆了服务器，则不会强制下线，用户可以继续操作服务器

**Comment by BaiJiangJie** [comment]
是的，但是两分钟后会提醒用户会话已过期，需要重新登录才能操作。
