### ISSUE TITLE
[Bug] 3.10.0 工作台>我的资产，标签列为空

### ISSUE THREAD

**Issue by carllhw** [jumpserver/jumpserver#12416]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.0

**浏览器版本**

**Bug 描述**
工作台>我的资产，标签列为空

**Comment by BaiJiangJie** [comment]
确实有问题，v3.10.1 修复一下。

**Comment by jym503558564** [comment]
v3.10.1已修复，请升级至v3.10.1进行测试。

**Comment by carllhw** [comment]
已测试通过
