### ISSUE TITLE
web登录多个资产的选项卡拖拽后执行的操作不一致问题[Bug] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12429]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0
另，之前的多个版本也有这个问题。

**浏览器版本**
火狐国际版 v121.0

**Bug 描述**
web登录多个资产，会显示在不同的选项卡，拖拽选项卡位置后，右键选择任何操作，都会是针对拖拽前初始位置的选项卡的操作。而不是对实际右键选择的选项卡的操作。这样比较危险。

**Bug 重现步骤(有截图更好)**
1.web方式ssh依次登录test1和test2两个资产，此时选项卡顺序是test1|test2
2.拖拽test1和test2调换位置，此时选项卡的顺序是test2|test1
3.右键选择test1，然后选择任何操作，实际都是针对的test2，比如点击“关闭当前”，会关闭test2

**Comment by haitang5445** [comment]
哈哈，重新连接同样出现你这个问题

**Comment by akang1798** [comment]
> 哈哈，重新连接同样出现你这个问题

哈哈，是的，上面提到是任何操作，“关闭当前”只是举例。

**Comment by BaiJiangJie** [comment]
嗯，确实有问题，小版本修复一下。

**Comment by BaiJiangJie** [comment]
v3.10.1 已修复。
