### ISSUE TITLE
[Feature] V3资产支持自定义默认协议

### ISSUE THREAD

**Issue by linqianye** [jumpserver/jumpserver#12424]
V3的平台列表里设置资产平台支持的协议，目前是存在一个默认的协议类型，默认协议不能删除，只能修改端口号，建议把默认的协议设置为可修改协议类型和修改端口。
实际使用中同样是Linux平台，有的资产使用的是ssh/22，有的资产使用是telnet/23。默认为ssh/22时，只能新增一个telnet/23然后共存，用户使用时经常选错协议和端口号，导致频繁反馈连不上资产。

**Comment by BaiJiangJie** [comment]
<img width="2251" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/c1c279ea-e4a7-4106-a8ac-b24bc408fd11">

你可以新建一个资产平台（克隆一个 Linux 平台）

然后自定义协议，想保留什么都可以。

**Comment by linqianye** [comment]
这样能一定程度解决问题，但是随着组合情况越来越多，需要建立的平台数量也越来越多，最后会管理混乱。

**Comment by BaiJiangJie** [comment]
合理使用，会很优雅的。
另外授权中也支持授权协议，可以配合使用。
