### ISSUE TITLE
发送文本命令到ssh分屏终端，分屏的第一个资产会重复执行[Bug] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12438]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0
另，之前的多个版本也有这个问题。

**浏览器版本**
火狐国际版 v121.0

**Bug 描述**
发送文本命令到所有ssh分屏终端，第一个会重复执行

**Bug 重现步骤(有截图更好)**
1.打开资产test1，然后分屏连接资产test2
2.发送文本，如ls命令，到所有ssh终端
3.第一个终端会执行2次。
![ead511e7ac2cd755b16ab59f8efb9ee](https://github.com/jumpserver/jumpserver/assets/82021637/66867c05-0fbf-4dea-b248-b2e02f20ff80)

**Comment by BaiJiangJie** [comment]
最新版本已修复。（v3.10.1）
