### ISSUE TITLE
关于基于用户的授权规则问题或建议[Question] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12430]
**请描述您的问题.**
因为以每资产为出发点创建资产对应的规则，规则显得比较多。所以我现在的授权规则是，以堡垒机用户为出发点的，每个用户一个规则。基于这样的方式，目前没法实现这样的授权：
1、资产和用户情况：现有堡垒机用户u1、资产A和资产B，资产均为linux，且资产帐号不一样，分别对应资帐号a和资产帐号b。
2、权限情况：目前堡垒机用户u1有如上所示所有资产的访问权限（即拥有资产A的帐号a权限和资产B的帐号b权限。）
3、现象：在登录资产A时，除了资产A的帐号a，也有帐号b的选择。
4、问题：在一个授权规则的情况下，能不能实现让登陆资产A时只看到帐号a（或者直接由帐号a进入系统）？

2023.12.28补充：
一、问题背景————
目前部分也是根据资产创建不同授权规则，但问题逻辑变量会比较多，授权会相对比较乱。比如有一些授权规则包含了多个堡垒机用户，有一些授权规则中重复包含了一些其他规则中有的堡垒机用户或资产。这样排查起问题会相对比较麻烦，列举一个遇到的问题：
某个运维人员发现有一个资产无法登录了，比如找不到用户。因为授权规则比较多，有可能是规则r1的问题，也有可能是规则r2上的问题，所以比较难定位和处理。如果能够按自然人堡垒机用户来授权一个规则，那么这样就比较好处理。

二、问题建议————
Jumpserver的一个权限规则只有一个表单，在这个表单中，堡垒机用户、资产、资产帐号都是全局对应关系。这样如果添加了资产帐号，那么表单中所有资产的这个帐号必然都会授权。我建议：
拆分授权规则表单，或者在表单中加入多级选择向导。比如选择了资产或资产组后，基于被选择的这个资产或资产组，再下一步选择资产上的用户。

**Comment by BaiJiangJie** [comment]
我先简单理一下你的需求：

现在有一个用户 admin；一个资产 linux，有两个账号a和b；一个资产 windows，也有两个账号a和b；

为 admin 创建一个授权规则，授权了资产linux 和 windows，需求是：访问 linux 的时候只显示 a；访问 windows 的时候只显示 b；


思考了一下，目前的授权规则无法满足。

你只能从 用户和资产账号的命名上进行入手了。

比如：admin 用户的所有有权限的资产都使用同一个账号进行登录。不然就是按照 资产+账号 进行授权。（这样就不是一个用户一个授权规则了）

**Comment by akang1798** [comment]
我在原问题中补充了一下进一步的分析和建议，可见原文的“2023.12.28补充”。

**Comment by BaiJiangJie** [comment]
嗯，你的需求背景我了解了。还是上面回复的方案，建议从用户和资产账号的命名上考虑。

产品层面中暂时不考虑授权到 资产+具体账号，这样会导致权限管理很冗余。

根据现有的权限管理体系，再整合上资产账号的命名策略，一定有适合你的比较不错的方案。
