### ISSUE TITLE
[Bug] 交换机命令过滤功能

### ISSUE THREAD

**Issue by xiongxq123** [jumpserver/jumpserver#12435]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
edge  120.0.2210.91

**Bug 描述**
交换机命令过滤功能不生效

**Bug 重现步骤(有截图更好)**
1.查看端口状态
![屏幕截图 2023-12-27 090240](https://github.com/jumpserver/jumpserver/assets/154940176/383d57f2-ef39-4bc5-90ac-b48f04302459)

2.设置命令禁用并查看端口状态:,有拦截,但是设备已执行
![屏幕截图 2023-12-27 090414](https://github.com/jumpserver/jumpserver/assets/154940176/1d0525b3-6a70-42db-92fc-10aa4ed26373)

![屏幕截图 2023-12-27 090339](https://github.com/jumpserver/jumpserver/assets/154940176/7e6decff-26c4-4042-9e66-9799efcb1dea)

3.堡垒机命令过滤设置
![image](https://github.com/jumpserver/jumpserver/assets/154940176/44f84abd-7cfb-4b7b-973b-bc6a32836464)
![image](https://github.com/jumpserver/jumpserver/assets/154940176/ae74841e-da9f-4516-a78c-67647b704d39)

**Comment by BaiJiangJie** [comment]
使用的什么版本？

**Comment by xiongxq123** [comment]
3.10.0

**Comment by BaiJiangJie** [comment]
交换机的具体型号是什么？不同类型的服务器取消命令执行的指令不一样，初步定位可能是这个原因。

**Comment by BaiJiangJie** [comment]
上面这些型号，所有都没有拦截成功吗？

**Comment by xiongxq123** [comment]
是的,只提示,未成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Bug] 交换机命令过滤功能 (Issue #12435)





 
上面这些型号，所有都没有拦截成功吗？

**Comment by jym503558564** [comment]
cisco版本：WS-C2960-24TT-L (PowerPC405) ，经测试无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/e78ba6e0-28ac-48e8-87da-da8c57404d05)
