### ISSUE TITLE
[Bug] 3.10 用户角色修改后更新页面与用户列表页显示不一致

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12439]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 v3.10.0

**浏览器版本**
Chrome 最新版

**Bug 描述**
修改已存在用户的系统角色和组织角色，保存成功后，用户列表显示的角色是修改后的，再次点击更新进入到更新页面，系统角色和组织角色瞬间会变成修改之前的角色，使用无痕模式打开测试结果一致

**Bug 重现步骤(有截图更好)**
1.修改用户的系统角色和组织角色
2.查看用户列表用户的角色信息
![image](https://github.com/jumpserver/jumpserver/assets/95400700/3f312762-6183-4e27-a7e7-1ba4c6f05e56)

3.再次点更新，查看角色信息
![image](https://github.com/jumpserver/jumpserver/assets/95400700/61903e1a-5143-45cb-9bd6-6b3a21b61ee5)

**Comment by jym503558564** [comment]
v3.10.1已修复，请升级至v3.10.1进行测试。
