### ISSUE TITLE
[Bug] 更新到最新版docker后不能使用

### ISSUE THREAD

**Issue by cuichenggen** [jumpserver/jumpserver#12433]
**Bug 描述**
docker 拉取了最新版的 jumpserver/jms_all后启动，不能用了。
试过删/opt/chen/data/keys/.access_key，/opt/kael/data/keys/.access_key，/opt/magnus/data/keys/.access_key后重启，无效。

**Bug 重现步骤(有截图更好)**
{ComponentName:kael Name:[Kael]-882f8070ea21-JarTsME CoreHost:http://localhost:8080 BootstrapToken:K99uTIJCq&zfJZb19B*G BindHost:0.0.0.0 BindPort:9091 LogLevel:ERROR RootPath:/opt/kael ExecuteProgram:/opt/kael/kael DataFolderPath:/opt/kael/data LogFolderPath:/opt/kael/data/logs KeyFolderPath:/opt/kael/data/keys AccessKeyFilePath:/opt/kael/data/keys/.access_key}
2023-12-26 19:41:00 [ERRO] Post "http://localhost:8080/api/v1/terminal/terminal-registrations/": dial tcp 127.0.0.1:8080: connect: connection refused
2023/12/26 19:41:01 Load config from env
2023/12/26 19:41:01 &{Root:/opt/lion DrivePath:/opt/lion/data/drive RecordPath:/opt/lion/data/replays FTPFilePath:/opt/lion/data/ftp_files LogDirPath:/opt/lion/data/logs AccessKeyFilePath:/opt/lion/data/keys/.access_key CertsFolderPath:/opt/lion/data/certs Name:[Lion]-882f8070ea21-RvFJeAq CoreHost:http://localhost:8080 BootstrapToken:K99uTIJCq&zfJZb19B*G BindHost:0.0.0.0 HTTPPort:8081 LogLevel:ERROR GuaHost:127.0.0.1 GuaPort:4822 DisableAllCopyPaste:false DisableAllUpDownload:false EnableRemoteAppUpDownLoad:false EnableRemoteAPPCopyPaste:false CleanDriveScheduleTime:1 ShareRoomType: RedisHost:192.168.0.98 RedisPort:6379 RedisPassword: RedisDBIndex:0 RedisSentinelPassword: RedisSentinelHosts: RedisUseSSL:false EnableVideoWorker:false VideoWorkerHost: IgnoreVerifyCerts:false PandaHost:http://localhost:9001 EnablePanda:false}
2023-12-26 19:41:01 main main.go [ERROR] 校验 access key failed: connect failed:Get "http://localhost:8080/api/v1/users/profile/": dial tcp 127.0.0.1:8080: connect: connection refused
Load config from env
{ComponentName:chen Name:[Chen]-882f8070ea21-WZzvrVW CoreHost:http://localhost:8080 BootstrapToken:K99uTIJCq&zfJZb19B*G BindHost:0.0.0.0 BindPort:9092 LogLevel:ERROR RootPath:/opt/chen ExecuteProgram:java -Dfile.encoding=utf-8 --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAME -XX:+ExitOnOutOfMemoryError -jar /opt/chen/chen.jar --mock.enable=false DataFolderPath:/opt/chen/data LogFolderPath:/opt/chen/data/logs KeyFolderPath:/opt/chen/data/keys AccessKeyFilePath:/opt/chen/data/keys/.access_key}
Load config from env
{ComponentName:magnus Name:[Magnus]-882f8070ea21-paIKuBR CoreHost:http://localhost:8080 BootstrapToken:K99uTIJCq&zfJZb19B*G BindHost:0.0.0.0 BindPort:9090 LogLevel:ERROR RootPath:/opt/magnus ExecuteProgram:/opt/magnus/magnus DataFolderPath:/opt/magnus/data LogFolderPath:/opt/magnus/data/logs KeyFolderPath:/opt/magnus/data/keys AccessKeyFilePath:/opt/magnus/data/keys/.access_key}
2023-12-26 19:41:01 [ERRO] Post "http://localhost:8080/api/v1/terminal/terminal-registrations/": dial tcp 127.0.0.1:8080: connect: connection refused
2023-12-26 19:41:01 [ERRO] Post "http://localhost:8080/api/v1/terminal/terminal-registrations/": dial tcp 127.0.0.1:8080: connect: connection refused
2023-12-26 19:41:01
KoKo Version v3.10.0, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
2023/12/26 19:41:01 Load config from env
2023/12/26 19:41:01 &{Name:[KoKo]-882f8070ea21-BftWxoM CoreHost:http://localhost:8080 BootstrapToken:K99uTIJCq&zfJZb19B*G BindHost:0.0.0.0 SSHPort:2222 HTTPPort:5000 SSHTimeout:15 LogLevel:ERROR Comment:KOKO LanguageCode:zh UploadFailedReplay:true UploadFailedFTPFile:true AssetLoadPolicy: ZipMaxSize:1024M ZipTmpPath:/tmp ClientAliveInterval:30 RetryAliveCountMax:3 ShowHiddenFile:false ReuseConnection:true ShareRoomType:local RedisHost:192.168.0.98 RedisPort:6379 RedisPassword: RedisDBIndex:0 RedisClusters:[] RedisSentinelPassword: RedisSentinelHosts: RedisUseSSL:false EnableLocalPortForward:false EnableVscodeSupport:false HiddenFields:[] RootPath:/opt/koko DataFolderPath:/opt/koko/data LogDirPath:/opt/koko/data/logs KeyFolderPath:/opt/koko/data/keys AccessKeyFilePath:/opt/koko/data/keys/.access_key ReplayFolderPath:/opt/koko/data/replays FTPFileFolderPath:/opt/koko/data/ftp_files CertsFolderPath:/opt/koko/data/certs}
2023-12-26 19:41:01 [ERRO] Post "http://localhost:8080/api/v1/terminal/terminal-registrations/": dial tcp 127.0.0.1:8080: connect: connection refused

**Comment by wojiushixiaobai** [comment]
从你的日志上看，是 core 还未完成启动，等待即可。如果后续有 core 组件的错误日志，请一并发上来

**Comment by cuichenggen** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/67672096/3bacc587-6bbf-469f-b73e-ff5c695d1f5c)
没有看到其他错误

**Comment by cuichenggen** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/67672096/29532c95-43bf-4ae8-8c3c-217d53ef91c0)
后续错误

**Comment by wojiushixiaobai** [comment]
应该可以访问了你试试

**Comment by cuichenggen** [comment]
还是不行

**Comment by cuichenggen** [comment]
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
882f8070ea21   jumpserver   2.56%     1.673GiB / 7.548GiB   22.16%    118MB / 49.5MB   1.31GB / 2.01MB   220

还是不能正常访问

**Comment by cuichenggen** [comment]
不好意思起docker改了端口
