### ISSUE TITLE
[Question] vscode remote-ssh连接端口转发问题

### ISSUE THREAD

**Issue by qyang2001** [jumpserver/jumpserver#12448]
我在macos的terminal中能直接使用ssh连接服务器，但在vscode中使用remote-ssh连接会出错，详细信息如下：

2387fc195e85: running
Acquiring lock on /home/user/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/vscode-remote-lock.user.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Found existing installation at /home/user/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2...
Checking /home/user/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log and /home/user/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.pid for a running server
Looking for server with pid: 2894472
Running ssh connection command... /home/user/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/user/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log" < /dev/null
printenv:
    SHELL=/bin/bash
    LC_ADDRESS=zh_CN.UTF-8
    LC_NAME=zh_CN.UTF-8
    LC_MONETARY=zh_CN.UTF-8
    PWD=/home/user
    LOGNAME=user
    XDG_SESSION_TYPE=tty
    MOTD_SHOWN=pam
    HOME=/home/user
    LANG=en_US.UTF-8
    LC_PAPER=zh_CN.UTF-8
    VSCODE_AGENT_FOLDER=/home/user/.vscode-server
    SSH_CONNECTION=192.168.209.15 40020 192.168.197.164 22
    XDG_SESSION_CLASS=user
    LC_IDENTIFICATION=zh_CN.UTF-8
    USER=user
    SHLVL=0
    LC_TELEPHONE=zh_CN.UTF-8
    LC_MEASUREMENT=zh_CN.UTF-8
    XDG_SESSION_ID=1238
    XDG_RUNTIME_DIR=/run/user/1000
    SSH_CLIENT=192.168.209.15 40020 22
    LC_TIME=zh_CN.UTF-8
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    LC_NUMERIC=zh_CN.UTF-8
    _=/usr/bin/printenv
Removing old logfile at /home/user/.vscode-server/.0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.log
Spawned remote server: 2998709
Waiting for server log...
Waiting for server log...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
 
2387fc195e85: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==34435==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==88==
connectionToken==5262ca12-045f-4dc3-96df-0b260f0df471==
2387fc195e85: end
channel 3: open failed: administratively prohibited: port forwarding is disabled
channel 3: open failed: administratively prohibited: port forwarding is disabled
 
关键信息似乎是“channel 3: open failed: administratively prohibited: port forwarding is disabled”，我猜测这是服务器不允许端口转发。

我已经尝试过几种可能的解决方法。

包括在配置文件config.txt中添加：
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

以及修改/etc/ssh/sshd_config文件为：
AllowAgentForwarding yes
AllowTcpForwarding yes
GatewayPorts yes
PermitTunnel yes

我也排除了vscode或ssh版本问题。

更奇怪的是，以上的报错信息是当 "remote.SSH.useLocalServer"为 false 时出现的，当我将这个选项修改为true时，会出现另一种报错信息：

[19:48:11.336] > local-server-1> ssh child died, shutting down
[19:48:11.342] Local server exit: 0
[19:48:11.342] Received install output: local-server-1> Running ssh connection command: "-v -T -D 58796 -o ConnectTimeout=15 gpu.aiserver.cn"
local-server-1> Spawned ssh, pid=2568
OpenSSH_9.4p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:+/cCmGKuQ9zprxmHQhumvz43H2JGojraB5H1AYC2T+Y
Permission denied, please try again.
Authenticated to gpu.aiserver.cn ([219.150.35.116]:2222) using "password".
No support vscode like requested.
Transferred: sent 2656, received 1700 bytes, in 0.3 seconds
Bytes per second: sent 8044.6, received 5149.0
local-server-1> ssh child died, shutting down

[19:48:11.345] Resolver error: Error: Permission denied, please try again.
	at g.Create (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at /Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:639355
	at t.handleInstallOutput (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:639991)
	at e (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/yang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003

关键信息似乎是“local-server-1> ssh child died, shutting down”，我在其他issue中看到了类似的问题，但依旧无法解决。

我对于jumpserver并不太了解，但我已经在自己的能力范围内尝试了大部分可能的方案，这一问题困扰了我很久。可能我错误地理解了报错的原因，希望能得到一些指导和启发。

**Comment by LeeEirc** [comment]
可以先参考下我们的 [使用 VSCode 工具连接 JumpServer 资产](https://kb.fit2cloud.com/?p=48) 文档。
修改资产上的 /etc/ssh/sshd_config 配置
```
AllowTcpForwarding yes
```

另外提供下相关信息：
- 本地 Mac 版本，VSCode 版本及 OpenSSH 版本
- 资产使用的 OpenSSH 版本
- JumpServer 使用的版本
- KoKo报错日志，如果信息少，可以打开 DEBUG 日志

**Comment by qyang2001** [comment]
> vscode 方式连接，资产账号必须是托管才能登录。

如何验证自己的账号是否托管呢，以及如何托管账号呢？我在文档里没有找到相关的教程

**Comment by qyang2001** [comment]
> 可以先参考下我们的 [使用 VSCode 工具连接 JumpServer 资产](https://kb.fit2cloud.com/?p=48) 文档。 修改资产上的 /etc/ssh/sshd_config 配置
> 
> ```
> AllowTcpForwarding yes
> ```
> 
> 另外提供下相关信息：
> 
> * 本地 Mac 版本，VSCode 版本及 OpenSSH 版本
> * 资产使用的 OpenSSH 版本
> * JumpServer 使用的版本
> * KoKo报错日志，如果信息少，可以打开 DEBUG 日志

macOS Sonoma 14.2.1
VSCode 1.85.1 (Universal)
本地OpenSSH 9.4，资产OpenSSH 8.2
JumpServer v3.10.0
KoKo报错日志：2023-12-28 18:24:35 [ERRO] Ws client read err: websocket: close 1006 (abnormal closure): unexpected EOF

这些信息足够吗

**Comment by LeeEirc** [comment]
托管账号指的是 资产的账号密码是保存在 JumpServer 数据库的，通过资产授权，终端页面可以直接连接的。
KoKo 的报错信息太少。

**Comment by tangguangliang** [comment]
```
afcd07eb8de6: running
Acquiring lock on /home/ops/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/vscode-remote-lock.ops.8b3775030ed1a69b13e4f4c628c612102e30a681
Found existing installation at /home/ops/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681...
Checking /home/ops/.vscode-server/.8b3775030ed1a69b13e4f4c628c612102e30a681.log and /home/ops/.vscode-server/.8b3775030ed1a69b13e4f4c628c612102e30a681.pid for a running server
Looking for server with pid: 26061
Found running server...
 
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*

Checking server status on port 41629 with wget
afcd07eb8de6: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==41629==
osReleaseId==centos==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==52dd12c3-10c0-47ff-b70f-c1bcafc5f04c==
afcd07eb8de6: end
channel 3: open failed: administratively prohibited: port forwarding is disabled
channel 3: open failed: administratively prohibited: port forwarding is disabled
```
我在windows下面连接也是报了同样的报错, sshd配置也更新了
```
grep AllowTcpForwarding /etc/ssh/sshd_config
AllowTcpForwarding yes
```
.ssh/config中的配置如下：
```
Host dls
  HostName jms-hk.domain.cn
  User guangliang.tang@ops@xxx.xx.xx.xx
  Port 2222
  IdentityFile ~/.ssh/id_rsa
```
在config中配置后ssh dls是可以直接连接的，就vscoce remote ssh 打开的时候就无法连接

**Comment by TanShun** [comment]
我也遇到相似问题，由于对 JumpServer 工作机制不是很熟，这个问题也困扰了我很久，我说下我的排查过程，希望能有所帮助。
JumpServer 是通过一键安装脚本自动安装的，版本号为`v3.10.3`。测试资产是一个 Ubuntu 22.04 server 的服务器，有一个root账号和一个非root账号，root账号单独设置了密码，可以直接登录。资产的账号已经托管在了 JumpServer 上，在终端中使用 ssh username@root@<assets-ip>@<jump-server-ip> -p2222的连接方式，无论是 root 账号还是非 root 账号，都可以连接成功。
但使用 VSCode 的 Remote-SSH 插件连接，当使用 root 账号时，VSCode 插件报 `Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`错误；使用非 root 账号时，VSCode 插件可以成功在资产服务器上安装好 vscode-server，也就是说 VSCode 连接上了资产服务器，但是在安装成功后，会卡住，插件报 `channel 3: open failed: administratively prohibited: port forwarding is disabled`。
查看堡垒机 配置文件，在`/opt/jumpserver/config/config.txt` 的文件中没有发现 `ENABLE_LOCAL_PORT_FORWARD` 和 `ENABLE_VSCODE_SUPPORT` 配置项，我就将相关配置手动追加在了文件末尾，使用 `docker restart jms_koko` 命令重启了 KOKO 服务，发现问题依旧。在查看 KOKO 服务日志的时候，发现服务启动日志中 `EnableLocalPortForward:false EnableVscodeSupport:false`，说明我新添加的配置项未生效。**最后通过执行 `jmsctl restart`，将所有服务重启后，配置项才生效**。此时就可以通过 VSCode 插件使用非 root 账号连接上资产服务器了。
目前通过 VSCode 插件使用 root 账号，还是连接不上资产服务器，报`Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`错误。如果不使用堡垒机，使用 VSCode 插件直连是可以用 root 账号连接的。

**Comment by SpecterHi** [comment]
我的是通过1panel安装的jumpserver 4.6.0，然后这台机器本身还在内网，是通过frp把http和ssh的端口转发至公网。
同样遇到类似的vscode无法打开动态端口转发不能用的情况，一开始还怀疑是因为本来就是转发导致，之后冷静思考本来就是用ssh啊，问题肯定在别处。

排查思路：用各种方式，只要定位到是
`open failed: administratively prohibited: port forwarding is disabled`

就应该可以用类似方法排除。

首先修改.env，增加
`ENABLE_LOCAL_PORT_FORWARD="true"
ENABLE_VSCODE_SUPPORT="true"`
这个处理方式其实也可以在网上搜到，但是重建后问题依旧，用楼上的思路查看容器日志会发现同样的
`EnableLocalPortForward:false EnableVscodeSupport:false`
信息，说明的确没有生效。

最后的解决：
在上述基础上，修改
`docker-compose.yml`

在
`services:
    jumpserver:
        environment:
`
段中，已有的多个变量后添加
`ENABLE_LOCAL_PORT_FORWARD: ${ENABLE_LOCAL_PORT_FORWARD}
ENABLE_VSCODE_SUPPORT: ${ENABLE_VSCODE_SUPPORT}`

重建容器实例，搞定！

**Comment by ZYWNB666** [comment]
C:\Users\QQQQ>ssh -T 1755613@test@hgx-011@vssh.cloud.cn -p 2222
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

C:\Users\QQQQ>ssh -T 1755613@root@hgx-011@vssh.cloud.cn -p 2222
Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-94-generic x86_64)

为什么ssh -T就无法登录，而ssh就可以正常登录了呢
