### ISSUE TITLE
有没有什么方式使得centos字母变大

### ISSUE THREAD

**Issue by zhangxiongfu** [jumpserver/jumpserver#1244]
有没有什么方式使得数子变大，字母数字太小，看的眼睛 疼。

![1524628387 1](https://user-images.githubusercontent.com/37925854/39225516-6c4d5b8e-487f-11e8-894b-44be08eadb3e.jpg)

**Comment by ibuler** [comment]
目前只能手动修改代码来完成，参见 https://github.com/jumpserver/luna/issues/27
