### ISSUE TITLE
[Bug] 通过web连接SFTP页面，文件删除和创建的逻辑不一致，能否优化

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#12441]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
 V3.10.0

**浏览器版本**
chrome

**Bug 描述**
用户在平台列表那边，设置SFTP根目录为“/tmp/${USER}”,设置完毕后，用户在使用web页面进行SFTP文件传输时，如果在根目录右击删除所有文件夹内容时，会把默认创建出来的${USER}文件夹删除。但是在新建的时候，将文件拉入这个根目录时，却无法将默认的${USER}文件夹创建出来（通过右击新建文件夹的方式，却能创建出${USER}文件夹）。两边逻辑不一致。

**Bug优化建议**
希望删除和创建逻辑能保持一致，能够优化以下两个点其中之一以保持逻辑一致：
第一个：删除就不能把根路径的那个文件夹删掉
第二个：上传文件的时候，如果文件夹不存在，就自动创建，因为有可能人为在服务器把文件夹删掉，之后就会导致文件无法上传了。

**Comment by blooze123** [comment]
复现视频如下：
[iShot_2023-12-27_18.00.57.zip](https://github.com/jumpserver/jumpserver/files/13782740/iShot_2023-12-27_18.00.57.zip)

**Comment by BaiJiangJie** [comment]
嗯，看了一下视频。我觉得比较好的处理方案是，删除是不能删除 SFTP 中配置的根目录。

比如视频中配置的应该是 Z14015 目录。

Web SFTP 打开的时候，根目录不能删除。

**Comment by blooze123** [comment]
嗯嗯是的，会比较合理

**Comment by BaiJiangJie** [comment]
v3.10.1 会上线。

**Comment by blooze123** [comment]
大赞！！

**Comment by jym503558564** [comment]
v3.10.1已修复，请升级至v3.10.1进行测试。
