### ISSUE TITLE
外部链接，跳转漏洞

### ISSUE THREAD

**Issue by yuanzhimengbian** [jumpserver/jumpserver#12440]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0

**浏览器版本**
所有浏览器版本都会跳转

**Bug 描述**
jumpserver的逻辑漏洞，访问页面中的跳转链接的时候会打开新的chorme页面，在新的chorme的标签页可以输入网址，在知道IP的情况下，就可以直接访问内网的资源

**Bug 重现步骤(有截图更好)**
1.在页面中点击一个可以跳转的外部链接
<img width="1789" alt="iShot_2023-12-27_20 37 34" src="https://github.com/jumpserver/jumpserver/assets/93107257/d28a138d-9077-4b03-ab9d-3b7ed6d5efd6">

2.直接打开新的含有地址栏的chorme页面，可以直接访问内网资源
<img width="1780" alt="iShot_2023-12-27_20 38 47" src="https://github.com/jumpserver/jumpserver/assets/93107257/290f3139-56bd-43f6-be89-b407d9906bea">

**Comment by ibuler** [comment]
不要危言耸听，还以为有啥问题呢。

新建个 web 平台，http 协议 设置中，开启 安全模式，仅能访问当前站点。

**Comment by BaiJiangJie** [comment]
<img width="2064" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/af363262-6da5-4dcc-9fc1-41b2a766dccc">
