### ISSUE TITLE
[Bug] LDAP同步用户会覆盖手动添加的用户组

### ISSUE THREAD

**Issue by strongDong** [jumpserver/jumpserver#12449]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.0

**浏览器版本**
Google Chrome 120.0.6099.110

**Bug 描述**
LDAP用户自动或者手动通过完成后，添加用户组，下次自动同步或者手动同步后回覆盖修改的用户组信息。比如 张三 同步过来时默认用户组是“AD 技术部”，然后给张三 添加一个 运维 用户组，此时张三属于“AD 技术部”和“运维”两个用户组，待下次同步后又会变成“AD 技术部”，覆盖掉了“运维”用户组数据。

**Bug 重现步骤(有截图更好)**
1. 手动同步用户
2. 为用户添加新的用户组
3. 再次手动同步用户或等待自动同步
4. 此时用的用户组已不包含第二步添加的用户组了

**Comment by BaiJiangJie** [comment]
会移除，因为如果用户组是从 LDAP 同步过来的， 下次 LDAP 端中的一个用户组移除了用户，那么对应到 jumpserver 也应该移除。

**Comment by BaiJiangJie** [comment]
后面考虑支持一下，自己手动创建的用户组，同步时不移除。

**Comment by strongDong** [comment]
> 后面考虑支持一下，自己手动创建的用户组，同步时不移除。

之前使用的2.28.1版本是支持的，升级到V3发现这个问题导致用户没有了资产权限。
期待新版本能继续支持哈~~
感谢回复~

**Comment by jym503558564** [comment]
v3.10.2已修复，待发版。

**Comment by jym503558564** [comment]
v3.10.2-lts已修复ldap同步时，不再覆盖手动添加的用户组。请升级至最新版本，进行测试。
