### ISSUE TITLE
[Question] 用户自动推送到资产问题

### ISSUE THREAD

**Issue by strongDong** [jumpserver/jumpserver#12455]
使用版本：3.10.0

问题：
1. 您好，请问怎么自动把用户同名的账号推送到资产服务器上？资产授权的时候我选择同名账号但是不能登录，服务器上也没有和LADP同步过来的用户一样的账号。
2. 账号管理-》账号推送功能只能手动输入用户名推送，不能使用@USER变量推送js系统用户吗？
3. 虚拟账号中的同名账号提供的别名 @USER 是做什么用的？

新手用户，忘不吝指教~

**Comment by BaiJiangJie** [comment]
目前只能是在账号推送任务中手动输入要推送的账号。

虚拟账号中的同名账号（@user）是用来登录资产的，比如 a 用户登录使用 a 账号，b 用户登录使用 b 账号。

但是 a 和 b 账号，都必须先在资产主机上创建出来。

**Comment by strongDong** [comment]
感谢回复，已了解使用方法~
