### ISSUE TITLE
引入网域功能的rdp gateway怎么用

### ISSUE THREAD

**Issue by sy1995** [jumpserver/jumpserver#1245]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.1.0

##### 问题复现步骤
1. 更新日志说已经引入了rdp gateway的概念，但是没有看到任何相关文档，自己测了一下也没成功
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是否部署完成 rdp gateway服务？

**Comment by wojiushixiaobai** [comment]
@sy1995 搭建完成后，可以通过如图方式测试一下。我上次简单的测试了一下，应该是设置问题，不能连接，准备重新搭建环境测试一下。

![1](https://user-images.githubusercontent.com/24326988/39678824-98a06b04-51c6-11e8-9c4a-d3a1a808e4d0.jpg)

**Comment by sy1995** [comment]
@wojiushixiaobai 我们环境里的rdp gateway测通了的，微软有专业支持搞得，这个功能没问题，问题是在jumpserver上怎么搞不知道呀？
正常使用步骤是要导入证书，还要配hosts文件把rdp gateway的主机名配上解析

**Comment by ibuler** [comment]
guacamole 存在bug，无法使用网关，等待新的版本release

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
