### ISSUE TITLE
3.10版本 使用python同步主机信息，通过/api/v1/assets/hosts/提交提示：{"detail":"账号对象不存在","code":"object_does_not_exist"}[Bug] 

### ISSUE THREAD

**Issue by linkdao** [jumpserver/jumpserver#12453]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
使用python同步主机信息，通过/api/v1/assets/hosts/提交提示：{"detail":"账号对象不存在","code":"object_does_not_exist"}
1，我通过/api/v1/accounts/account-templates/可以获取我创建的账号模板，
![image](https://github.com/jumpserver/jumpserver/assets/72115270/582eb6e8-ffb2-45f3-889d-6915c154b6d4)
2，使用
    account=get_template_info()
    data={
  "name": "testssw1",
  "address": "10.31.240.230",
  "comment": "",
  "domain": "",
  "platform": {'id': 1, 'name': 'Linux'},
  "nodes": [
    "e0f9cddb-6d6e-49e8-80ab-97677aee335c"
  ],
  "labels": [
  ],
  "protocols": [
    {
      "name": "ssh",
      "port": 22
    }
  ],
  "accounts": account,
  "info": {
    "vendor": "string",
    "model": "string",
    "sn": "string",
    "cpu_model": [
      "string"
    ],
    "cpu_count": 0,
    "cpu_cores": 0,
    "cpu_vcpus": 0,
    "memory": "string",
    "disk_total": "string",
    "distribution": "string",
    "distribution_version": "string",
    "arch": "string"
  },
  "is_active": True
}
url = jms_url + "/api/v1/assets/hosts/"
print(url)
data = json.dumps(data)
print(data)
response = requests.post(url, auth=auth, headers=headers, data=data)
print(response.text)
提示 {"detail":"账号对象不存在","code":"object_does_not_exist"}
尝试多次都是如此
**Bug 重现步骤(有截图更好)**
1.查看日志发现，提示/api/v1/assets/hosts 404
![image](https://github.com/jumpserver/jumpserver/assets/72115270/56c5b3c7-d6fb-445c-a93b-e1de4c78067c)
2.swager api打不开
![image](https://github.com/jumpserver/jumpserver/assets/72115270/eaabf6f8-3c86-48e3-80ea-9444a609318a)

**Comment by linkdao** [comment]
def get_template_info():
    """
    获取账号模板信息
    :return:
    """
    url = jms_url + "/api/v1/accounts/account-templates/"
    print(url)
    response = requests.get(url, auth=auth, headers=headers)
    tpm_list = response.text
    # print(json.loads(tpm_list))
    return json.loads(tpm_list)

**Comment by BaiJiangJie** [comment]
Swagger API 打不开的问题，会在 v3.10.1 中修复。

账号对象不存在，说明 account 字段的信息有误。

<img width="844" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/75ca78c4-d82e-46e9-a4ab-d89ac9ead433">

**Comment by BaiJiangJie** [comment]
获取回 template 信息后，增加一个字段:

{
  'template': '输入获取回来的账号模版 id'
}

**Comment by linkdao** [comment]
> 获取回 template 信息后，增加一个字段:
> 
> ```
> {
>   'template': '输入获取回来的账号模版 id'
> }
> ```
> 
> 比如：
> 
> ```python
> data = {
>  "accounts": [{"template": "UUID-1"}, {"template": "UUID-2"}]
> }
> ```

谢了
