### ISSUE TITLE
[Question] Error "Connetc Error - Aborted. See logs"

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#12469]
Hi,

I have problem with remote RDP.
- Some users can remote RDP to this server and no errors occurred
- Some users can remote RDP to this server, but then 5-10 minutes will error: `Connetc Error - Aborted. See logs`.
![image](https://github.com/jumpserver/jumpserver/assets/75791054/bd7082ef-c713-47f0-9445-dc5f026cc106)

Some info:
- Jumpserver v3.8.1
- Server: Window Server 2012 R2
- Problem is not resource usage (RAM and CPU always within range 20% ~30%)

**Comment by BaiJiangJie** [comment]
Check `lion.log` and `guacd.log` to see if there are any abnormal logs?

**Comment by tsukiazuma** [comment]
Yeah, I checked logs but don't see any abnormal logs.

In `guacd.log` contains some info like:
```
guacd[2247314]: ERROR:  User is not responding.
guacd[2246539]: ERROR:  File open refused (-2): "\desktop.ini"
```
In `lion.log` also not any abnormal logs:
```
2024-01-02 15:58:25 tunnel conn.go [ERROR] Session[916236ca-1d34-48a9-bb71-4d4810ea66c2] web client read err: websocket: close 1005 (no status)
2024-01-02 15:58:25 tunnel conn.go [ERROR] Session[916236ca-1d34-48a9-bb71-4d4810ea66c2] guacamole server read err: read tcp 127.0.0.1:39422->127.0.0.1:4822: use of closed network connection
```

or logs check cookie:
`2024-01-02 15:21:01 middleware cookie.go [ERROR] Check user cookie failed: map[SESSION_COOKIE_NAME_PREFIX:jms_ X-JMS-ORG:00000000-0000-0000-0000-000000000002 _ce.s:v~d816c32cc246aa8cb3ee3b1c4c45b7131769c98c~lcw~1697447297251~vpv~0~v11.fhb~1697447252991~v11.lhb~1697447289207~v11.cs~430023~v11.s~70e806a0-6c03-11ee-bc6a-9f594a62adc8~v11.sla~1697447297279~gtrk.la~lnsoakwi~v11.send~1697447297250~lcw~1697447297283 _ga:GA1.1.658264230.1664186534 _ga_4E547DPCZ3:GS1.1.1700209900.9.0.1700209907.0.0.0 _ga_B8FC82R3D5:GS1.1.1700209899.8.0.1700209907.0.0.0 _ga_DRR9FLR74Q:GS1.1.1700209900.3.0.1700209907.53.0.0 _ga_QBK4G2Y9VD:GS1.1.1700209900.3.0.1700209907.0.0.0 _gcl_au:1.1.616103665.1697447251 jms_csrftoken:Hb0efY39R46sQoCwD5QDoLkLksWuOoXa jms_public_key:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDTG8vSStmdDFPZ0pBam1KL01aYm9UTnFCNAowZHNqaCtHU3dqUytOSWNTd25NckFpU213c2ZVY0Y1ZTRsdWxxTEl3RDk5K0JhV0FQQUJyVkJkV2RXQWZ4bllQCjdjYXY1clEvS2tHVUdsem9CWmpWMUIzbTc4UnIyQzU3dkxtLzlPVE1rZ3BLQklzS3ljQU5tQU9MeWFwN2o0OXoKQWl6Qi8rNFJDdUNaS0M3U2tRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ== jms_sessionid:akanqxb52rwwx0z4x6v713wlr90wi5hc] GET http://core:8080/api/v1/users/profile/ failed, get code: 401, {"detail":"Authentication credentials were not provided.","code":"not_authenticated"}`

**Comment by LeeEirc** [comment]
Are these users using VPN or HTTP proxy? Could you please check the network status of these users?
I suspect that their network is unable to maintain a WebSocket connection.

**Comment by tsukiazuma** [comment]
Yeah, all users using HTTP proxy, but only some users get the above error
And more information from user, above error doesn't happen continuously, some days it happens, some days it doesn't

**Comment by LeeEirc** [comment]
Would it be ok without HTTP proxy? I think it's the proxy issue.

**Comment by tsukiazuma** [comment]
All users using HTTP proxy, but some users get error.
So I think `their network is unable to maintain a WebSocket connection` can be right, because today user work well.
But I will still follow up to can detect more information.

Thank you
