### ISSUE TITLE
[Question] 我在升级3.10.0版本时遇到报错

### ISSUE THREAD

**Issue by harbour015** [jumpserver/jumpserver#12465]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/10bbe287-d5c8-4ff8-91a9-c18de8663bb1)

**Comment by harbour015** [comment]
我用的是外置的mysql  8.1.0版本

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/a9a4a07f-5d45-47d6-bb52-1f69cd88a7bb)

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/a0330b3f-b678-47d6-9286-6ad2c1daaab7)

**Comment by BaiJiangJie** [comment]
升级过程中不要手动中断，因为会有一些表结构迁移，如果中断二次执行会出现上面类似的问题。

现在恢复到升级前的数据库，重新升级一下。

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/b8eeb784-8ffe-40c9-a7b9-9744a7832fc7)
数据库恢复到升级之前的，再次执行升级。还是出现了类似的报错。

**Comment by BaiJiangJie** [comment]
这个应该是编码问题。新建的数据库和之前的数据库编码保持一致。

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/d6899253-1ae3-4049-aa17-98fab390b94f)
数据库的编码没有区别，我现在应该怎么办。

**Comment by BaiJiangJie** [comment]
之前也是 utf8mb3?

**Comment by BaiJiangJie** [comment]
最好看一下之前备份的 sql 文件，看一下 charset 值和 collect 值。创建新数据库的时候指定相同的值。

https://kb.fit2cloud.com/?p=9aaf5bc6-7071-4be0-96fd-98295feee3f2

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/99c1a270-43b3-432a-bdfa-cc56f04cb738)
![image](https://github.com/jumpserver/jumpserver/assets/48000268/606fedba-f096-469b-99dc-8f7e978f5943)
确实所有的都一样

**Comment by BaiJiangJie** [comment]
一般推荐使用 utf8mb4，不知道是不是 mb3 的影响。

**Comment by harbour015** [comment]
除了备份了一个数据库，现在其他的东西都没有了，还有办法还原之前添加的资产不？

**Comment by BaiJiangJie** [comment]
约个时间我们远程看一下吧？

charset 和 collate 要看库、表、字段的。都要看。

**Comment by BaiJiangJie** [comment]
或者这样，你都查一下 database、table、field 的 charset 和 collate 的值。

再发一下，你创建数据库的语句。我来对比看一下。

**Comment by harbour015** [comment]
因为我这里不至一个jumpserver，创建库的时候，是按照其他机器上创建的，表是自动创建的。
CREATE DATABASE `jumpserver`  DEFAULT CHARACTER SET utf8mb3  COLLATE=utf8mb3_bin ;
我只是创建了一个库

**Comment by harbour015** [comment]
我想退回老版本也启动不起来了

**Comment by BaiJiangJie** [comment]
对，创建库的语句没问题。

**Comment by BaiJiangJie** [comment]
备份的那个版本，应该能起得来才对啊，如果启动不起来，说明备份的有问题。

**Comment by harbour015** [comment]
我是在升级失败以后，做了一个全备。升级自动备份的文件，我在重新安装的时候，给自动删除了。

**Comment by harbour015** [comment]
我现在重新安装一下，能不能把原来的资产的导入进去？

**Comment by harbour015** [comment]
比如单独把某一张表导入？

**Comment by BaiJiangJie** [comment]
单独导进去，服务起不来也用不了啊。

**Comment by harbour015** [comment]
我的意思是，正常安装一个，等服务都启动起来以后，把资产那个表，单独导入一下。现在是启动不起来，添加的资产太多，一个一个添加不太好搞。或者能不能帮忙给远程一下。

**Comment by BaiJiangJie** [comment]
估计也不好搞，资产表关联了节点，节点表也要导入，就怕表之间互相有关联。不过你可以试一下。

**Comment by BaiJiangJie** [comment]
<img width="1169" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/24231bc8-cb9b-45c1-8f86-2be267540ea1">

查看一下这两个字段的详细信息。

**Comment by harbour015** [comment]
我找到23年11月的升级3.8.2版本时备份的数据库，还原了一下，然后升级了3.9.2，又升级了3.10。现在是3.10版本，用ssh user@hostname -p 2222登录，可以正常看到原来的资产。但是网页打不开。打开http://1.1.1.1:8080自动跳转到了https://ui/#/然后显示无法访问此网页。

**Comment by BaiJiangJie** [comment]
那应该是升级成功了。

Nginx 使用的是默认的，还是自己的？如果是自己的，需要和默认的配置保持一样。

**Comment by harbour015** [comment]
全部都是默认的

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/c5f8866c-d870-44da-a0ae-9303bd4b8af0)
./jmsctl.sh tail 也没看到什么报错，只是web页面不能访问。

**Comment by BaiJiangJie** [comment]
看看 nginx 的日志。

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/44df405f-7cc5-43b6-922e-d63ae85fd083)
不知道是不是这个导致的

web的这个服务，没有看到有报错的提示
![image](https://github.com/jumpserver/jumpserver/assets/48000268/8f5ff980-f283-4fad-862a-e3cd295e5677)

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/243f094c-9aa7-490e-9d0c-dbb9b2467285)
我把所有目录下的.access_key删除以后，提示终端注册关闭了，我可能确实在页面上关掉了，现在页面打不开，有没有办法打开这个按钮。或者说，这个问题是不是我关闭了终端注册导致的。

**Comment by harbour015** [comment]
我解决了，感谢

**Comment by harbour015** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48000268/69491375-9135-4adb-ae3c-c87f8fbc5d13)
经过多次测试，原来的版本是3.8.2，数据库是mysql 8.1.0 只要升级3.10.0，就会出现这个报错。重新安装3.8.2没有问题。
