### ISSUE TITLE
[Bug] 升级3.10.0后，config.txt中HTTPS_PORT=443被注释掉导致https访问失败，升级3.10.1 Bug依旧

### ISSUE THREAD

**Issue by reginofchaos** [jumpserver/jumpserver#12477]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.0
3.10.1

**浏览器版本**
Microsoft Edge
版本 120.0.2210.91 (正式版本) (64 位)

**Bug 描述**
3.9.2及之前版本一直配置了https并且使用正常。从3.9.2升级至3.10.0，https页面无法访问，./jmsctl.sh status显示jms_web只有80端口，检查config.txt发现HTTPS_PORT=443被注释掉。重新编辑config.txt，删除注释，https页面恢复访问。
从3.10.0升级3.10.1，问题重现，config.txt中HTTPS_PORT=443再次被注释掉。

**Bug 重现步骤(有截图更好)**
1.下载离线安装包jumpserver-offline-installer-v3.10.1-amd64.tar.gz
2.正常升级步骤
3.https页面无法访问，检查config.txt发现HTTPS_PORT=443被注释掉，但config.txt中的域名、证书等配置都保留完好。
![image](https://github.com/jumpserver/jumpserver/assets/730904/c64bdab8-961b-4db0-b8db-2657a88f90a3)

**Comment by BaiJiangJie** [comment]
之前的配置文件应该不会被覆盖才对啊。

**Comment by BaiJiangJie** [comment]
你的 config.txt 在什么目录下？

**Comment by reginofchaos** [comment]
/opt/jumpserver/config/config.txt

**Comment by BaiJiangJie** [comment]
v3.10.2 修复上线。

**Comment by jym503558564** [comment]
v3.10.2-lts已修复，并发布。请升级至最新版本，进行测试。

**Comment by reginofchaos** [comment]
已升级到3.10.2，配置文件正常，问题没有复现。
