### ISSUE TITLE
[Bug] sftp客户端模式使用winscp工具批量传输文件到本地报错

### ISSUE THREAD

**Issue by haipeng-fit2** [jumpserver/jumpserver#12478]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.10.1

**浏览器版本**
Chrome 120.0.6099.129（正式版本） (x86_64)
winscp版本6.1.2
**Bug 描述**
sftp客户端模式使用winscp工具，把linux资产中的文件批量传输到本地会报这个错误，单个文件传输是正常的，使用web端也是正常的，日志只有一条报错信息：2024-01-02 16:06:14 [ERRO] Remote sftp file /Default/172.16.19.141/bb.txt close err: file does not exist

**Bug 重现步骤(有截图更好)**
1、使用winscp通过2222端口登录Linux资产的tmp目录
2、批量拖拽文件到本地PC

![Uploading 151704182890_.pic.jpg…]()

**Comment by haipeng-fit2** [comment]
![151704182890_ pic](https://github.com/jumpserver/jumpserver/assets/81673899/cc88fb78-538a-407c-84f1-8a35b5779281)

**Comment by LeeEirc** [comment]
开启连接 token 复用，可解决此类问题。
