### ISSUE TITLE
[Question] 针对Oracle11g资产，在资产列表中运行测试连接选项,测试结果失败，系统页面显示资产状态为错误。

### ISSUE THREAD

**Issue by fit2cloud-jinyan** [jumpserver/jumpserver#12470]
1. 纳管Oracle 11g资产。
2. 在资产列表中运行测试连接功能。
3. 测试结果失败，提示python版本兼容问题， 资产连接性状态为错误,但是通过远程应用发布可正常连接该数据库
![1](https://github.com/jumpserver/jumpserver/assets/73215788/97969612-fa27-4e30-ad28-72c2f24b37c0)
。
4. Oracle19c未有此问题。
5. 测试环境 JS 3.9.1 （10.1.13.66） Oracle 11g(10.1.13.95)

**Comment by feng626** [comment]
版本太老了 不支持了
