### ISSUE TITLE
web终端页面被关掉，能否断开此次会话。

### ISSUE THREAD

**Issue by xiongligit** [jumpserver/jumpserver#1247]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.0.0
##### 问题复现步骤
1. [步骤1]
jumpserver 用web终端连接linux。当web终端页面被关掉时。此次会话不会断开。
2. [步骤2]
当20多分钟后通过管理端强制终端此次会话后，录像不能回放。
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
