### ISSUE TITLE
jump对接casdoor,使用外网地址后，无法认证通过

### ISSUE THREAD

**Issue by ywd1988** [jumpserver/jumpserver#12479]
RT：jump对接casdoor,使用外网地址后，无法认证通过，但是全部使用内网地址就没问题
![image](https://github.com/jumpserver/jumpserver/assets/92080991/ae32d6d7-271d-4b27-8f1a-a3edd35613a1)

**Comment by BaiJiangJie** [comment]
哪一步 504 了？在 CAS Server 端认证成功了吗？

**Comment by ywd1988** [comment]
> 哪一步504了？在CAS Server端认证成功了吗？

提示登录成功

**Comment by BaiJiangJie** [comment]
内网地址，是指什么？

**Comment by ywd1988** [comment]
> 内网地址，是指什么？

192.168 这类地址

**Comment by BaiJiangJie** [comment]
全部是用外网不行？

**Comment by ywd1988** [comment]
> 全部使用外网不行？也就是 https 协议。

是的

**Comment by BaiJiangJie** [comment]
正常应该是可以的，具体到每个用户的环境不一样，需要你自己研究一下。

**Comment by ywd1988** [comment]
> 正常应该是可以的，具体到每个用户的环境不一样，需要你自己研究一下。

试了几天了，各种改，还是不行

**Comment by BaiJiangJie** [comment]
在 core 容器里，curl 一下配置的 CAS 外网地址，试试能通吗？

**Comment by ywd1988** [comment]
> 在 core 容器里，curl 一下配置的 CAS 外网地址，试试能通吗？

感谢大佬，是我出口双线的问题
