### ISSUE TITLE
[Bug] 账号管理菜单打不开

### ISSUE THREAD

**Issue by wddphero** [jumpserver/jumpserver#12489]
**JumpServer 版本(v3.10.1 )**

**浏览器版本**
Google Chrome
版本 120.0.6099.109（正式版本） (arm64)

**Bug 描述**
账号管理菜单，账号推送，账号模板，账号列表   4个菜单打不开。 一直加载

**Bug 重现步骤(有截图更好)**
1.
<img width="689" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17229891/fd5e68a9-906b-4f30-b8d1-e181137d08bd">
<img width="965" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17229891/74439fa5-2253-4397-9a4e-7a127134424f">

2.
3.
![Uploading image.png…]()

**Comment by BaiJiangJie** [comment]
看看浏览器控制台有没有报错？

**Comment by jym503558564** [comment]
升级至最新版本，再验证下，是否还存在改问题
