### ISSUE TITLE
双机部署jumpserver，分别通过ldap user登陆这二台jumpserver，发现只有一台能正常登录，另外一台登录异常。

### ISSUE THREAD

**Issue by hnzhuzi** [jumpserver/jumpserver#12484]
开始只部署了一台jumpserver 01，配置好ldap认证后，可以正常通过ldap user登陆这一台jumpserver 01，但后面添加另外一台jumpserver 02后，同样通过ldap user用户访问jumpserver 02，发现登录异常：
![image](https://github.com/jumpserver/jumpserver/assets/49380375/a9143f76-4262-4787-8935-df5effcbf86e)
![image](https://github.com/jumpserver/jumpserver/assets/49380375/cdc87b30-78cb-4ba5-9a39-ce700acabeaf)

然后通过admin用户分别登录jumpserver01和jumpserver02，查看ldap后台系统配置，发现jumpserver 01测试连接正常：
![image](https://github.com/jumpserver/jumpserver/assets/49380375/2831d6f9-dcf9-4174-9a7a-2bf894bde2e3)
而jumpserver 02却测试连接异常：
![image](https://github.com/jumpserver/jumpserver/assets/49380375/01e69596-2eda-4517-a8a7-50532c8a7db3)

多次测试，发现只有一台jumpserver正常能通过ldap user登录，另个一台就是登录异常。按理说二台的nfs/mysql/redis都是配置一样的，ldap应该也保持同步，怎么总有一台登录异常？

**Comment by BaiJiangJie** [comment]
两台的数据库（MySQL）是独立的还是共用的？

**Comment by BaiJiangJie** [comment]
02 测试可连接性的时候，密码输入的不对吧。

**Comment by hnzhuzi** [comment]
二台的数据库都是一样的，密码输入肯定正确的，然后二台用admin都能正常登入，且ldap user登录异常的那台02，用admin登录后台配置ldap认证(只要重新输入ldap密码)然后提交，发现02就能正常通过ldap user登录，而01马上就不能通过ldap user异常。所以总有一台不能通过ldap user登录。

**Comment by hnzhuzi** [comment]
用admin分别登录二台，资产、账号、权限、用户都是一样的。

**Comment by BaiJiangJie** [comment]
01 和 02 服务的后端数据库是，独立的还是共用的？不是说配置是不是一样。

**Comment by hnzhuzi** [comment]
后端用的是同一个数据库，其它redis，nfs都是共用的。

**Comment by BaiJiangJie** [comment]
看一下两个节点的 LDAP 配置信息一致吗？

**Comment by hnzhuzi** [comment]
> 看一下两个节点的 LDAP 配置信息一致吗？
> 
> 如果还不行就进交流群，联系一下技术支持，远程看一下。

二个节点的ldap配置信息是一样的，我添加交流群，麻烦你们帮忙远程看一下。

**Comment by BaiJiangJie** [comment]
嗯，直接找技术支持就行。

**Comment by hnzhuzi** [comment]
> 嗯，直接找技术支持就行。

群里没有回复啊，等了半天了。二台jumpserver就只有一台能通过ldap访问，哪台后端配置提交一下ldap配置，哪台就能登录，随之另外一台不能正常登录。

**Comment by BaiJiangJie** [comment]
你在哪个群里呢？

**Comment by hnzhuzi** [comment]
> 你在哪个群里呢？
交流群32

**Comment by hnzhuzi** [comment]
> > 你在哪个群里呢？
> > 交流群32

还没联系我呀

**Comment by wml3** [comment]
查看两台的这个配置是否一致，保持一致

# 记录 SECRET_KEY 和 BOOTSTRAP_TOKEN
cat /opt/jumpserver/config/config.txt | egrep "SECRET_KEY|BOOTSTRAP_TOKEN"

**Comment by BaiJiangJie** [comment]
@hnzhuzi 记得记录一下解决方法。
