### ISSUE TITLE
升级到3.9.3后，文件传输异常

### ISSUE THREAD

**Issue by kenneth1302** [jumpserver/jumpserver#12485]
原来使用的是3.2.2版本，文件传输机制似乎和3.9.3不同。
下载大文件异常，查看审计台发现文件传输可能对文件大小有100M的默认限制。
请问在3.9.3版本应该如果调整这个默认配置？如何下载大文件？

**Comment by BaiJiangJie** [comment]
审计台的限制是保存审计日志的文件大小限制。

下载文件的大小默认是没有限制的。看看报什么错？是不是 Nginx 限制了？

**Comment by kenneth1302** [comment]
页面右上角有个进度条一直在加载。
![image](https://github.com/jumpserver/jumpserver/assets/23459991/4802e308-b7b8-4e27-b667-6f60d26bc7b6)

F12没有看到有用信息。
![image](https://github.com/jumpserver/jumpserver/assets/23459991/f8788d52-684e-408b-8623-adab5507d900)

 查看jumpserver的ftp_files目录，发现koko会存一个文件，然后消失了。
![image](https://github.com/jumpserver/jumpserver/assets/23459991/2a7ef907-e086-4e54-8a19-ddb8e45e0dd2)




/data/jumpserver/koko/data/ftp_files/2024-01-04

**Comment by BaiJiangJie** [comment]
最终这个文件下载下来了吗？

**Comment by kenneth1302** [comment]
> 最终这个文件下载下来了吗？

下载不了，ftp_file目录里的文件也消失了

**Comment by BaiJiangJie** [comment]
ftp_file 目录中的文件会自动清理的。能下载到你本地就行。

**Comment by BaiJiangJie** [comment]
最新版本下载策略在 v3.10 有优化，尤其是针对大文件。建议你升级到最新版本试一下问题还是否存在。
