### ISSUE TITLE
[Bug] 作业中心 powershell 不可用

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#12486]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.0

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
作业中心使用 powershell 提示 Module shell is not suitable for this asset

**Bug 重现步骤(有截图更好)**
1.配置Windows资产，添加winrm协议，资产测试连接性等都可以正常使用
2.作业中心选择资产，使用administrator用户，选择powershell执行命令，提示Module shell is not suitable for this asset
![image](https://github.com/jumpserver/jumpserver/assets/35896106/64203fbf-5a28-4135-adad-f4fe9d2b8fc2)

**Comment by BaiJiangJie** [comment]
作业中心执行命令，windows 必须得有 ssh 协议。
