### ISSUE TITLE
[Bug] v3.10.1 升级后登录界面的 “ 1 天内自动登录” 无法勾选

### ISSUE THREAD

**Issue by loginkeithhe** [jumpserver/jumpserver#12497]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.1

**浏览器版本**
Chrome 120.0.6099.130

**Bug 描述**
v3.10.1 升级后登录界面的 “ 1 天内自动登录” 无法勾选

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/61262621/6da18b77-f814-429b-b4f9-1f3c78649b70)

**Comment by loginkeithhe** [comment]
> 关了页面,清空浏览器缓存再看看

没有用。

**Comment by BaiJiangJie** [comment]
配置文件查看下面两个配置项：
- SESSION_COOKIE_AGE （大于 3600）
- SESSION_EXPIRE_AT_BROWSER_CLOSE_FORCE（值为 false）

上面两种情况同时满足才允许勾选。

**Comment by loginkeithhe** [comment]
> 配置文件查看下面两个配置项：
> 
> * SESSION_COOKIE_AGE （大于 3600）
> * SESSION_EXPIRE_AT_BROWSER_CLOSE_FORCE（值为 false）
> 
> 上面两种情况同时满足才允许勾选。

似乎还是不行，已重启过了，清理过了浏览器缓存。
![image](https://github.com/jumpserver/jumpserver/assets/61262621/46c4557a-6208-4a51-adf2-28cada691f18)

**Comment by BaiJiangJie** [comment]
使用的是什么安装方式？

**Comment by loginkeithhe** [comment]
> 上面描述的有误。
> 
> SESSION_COOKIE_AGE 值要大于 86400（60 * 60 * 24）
> 
> @loginkeithhe

Hi，已经可以勾选了。
