### ISSUE TITLE
jumpserver1.0版本新增资产，推送用户不成功

### ISSUE THREAD

**Issue by chenglu01** [jumpserver/jumpserver#1249]
[简述你的问题]
jumpserver 1.0版本新增资产之后，跳板机登录不了，手动推送系统用户之后，提示任务已下发，但是发现后端被控机器上一直没有推送过来用户，查看celery.log
里面有报错信息：fatal: [hostname-02]: UNREACHABLE! => {"changed": false, "msg": "Authentication failure.", "unreachable": true}
##### 使用版本
jumpserver 1.0版本

##### 问题复现步骤
1. jumpserver的web界面新增资产
2. 登录coco跳板，跳后端服务器失败（Authenticate with server failed, contact administrator）
3. web端系统用户选择 立刻推送系统
4. 等待半个小时之后再登录后端服务器，依然不行

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
推送失败了，可能是你的管理用户认证信息不对造成的，请检查该服务器的管理用户密码是否正确
