### ISSUE TITLE
[Bug] NGINX 监听存在故障

### ISSUE THREAD

**Issue by FengLing02** [jumpserver/jumpserver#12498]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.1

**浏览器版本**
Microsoft Edge 120.0.2210.91 (正式版本) (64 位)

**Bug 描述**
NGINX HTTP（80）未监听 IPv6， HTTPS（443）未监听 IPv4

**Bug 重现步骤(有截图更好)**
1. /opt/jumpserver/config/config.txt 中开启 IPv6 (USE_IPV6=1)
2. 进入jms_web docker 容器内，查看 NGINX 配置文件，截图如下
![image](https://github.com/jumpserver/jumpserver/assets/152166457/a932c1ab-8caa-4781-be41-218dc87c0828)

**Comment by wojiushixiaobai** [comment]
手动添加一行，然后重启即可
```nginx
listen 443 ssl https2;  # 手动加入
listen [::]:443 ssl https;
```

**Comment by FengLing02** [comment]
/opt/jumpserver/config/nginx/lb_http_server.conf 我尝试修改后发现它不能修改，无论修改什么都会导致无法启动 web 服务
![image](https://github.com/jumpserver/jumpserver/assets/152166457/0eb383a9-836d-485d-9b4f-5cd9bff7962f)

**Comment by wojiushixiaobai** [comment]
不能修改是啥意思？
文件只读？还是修改无效？

**Comment by alfredfenglq** [comment]
> 手动添加一行，然后重启即可
> 
> ```shell
> cat /opt/jumpserver/config/nginx/lb_http_server.conf
> ```
> 
> ```nginx
> listen 443 ssl http2;  # 手动加入
> listen [::]:443 ssl http2;
> ```
> 
> 或者手动将安装脚本目录下面的 `config_init/nginx/lb_http_server.conf` 文件覆盖 `/opt/jumpserver/config/nginx/lb_http_server.conf` 然后重启也可以。
> 
> 代码由 [jumpserver/docker-web@6f74473](https://github.com/jumpserver/docker-web/commit/6f74473e97150016355c3bec961ab8e045229628) 修复。

这个commit只修复了http端口，https端口还是不对
> ```shell
> if [ "${USE_IPV6}" == "1" ]; then
>     sed -i "s@listen 443@listen [::]:443@g" "${config_file}"
> fi
> ```

**Comment by wojiushixiaobai** [comment]
确实需要转义，当时测试的时候可能漏了。

`https` 的端口请参考 `function config_https`
```

function config_https() {
  config_file=/etc/nginx/conf.d/https_server.conf
  if [ -f "${config_file}" ]; then
    rm -f "${config_file}"
  fi
  cp -f /etc/nginx/sites-enabled/https_server.conf "${config_file}"

  config_nginx "${config_file}"

  if [ -z "${HTTPS_PORT}" ]; then
    HTTPS_PORT=443
  fi

  sed -i "s@server web:.*;@server localhost:51980;@g" "${config_file}"

  if [ "${USE_IPV6}" == "1" ]; then
    sed -i "s@listen 443@listen [::]:443@g" "${config_file}"
  fi

  if [ "${HTTPS_PORT}" != "443" ]; then
    sed -i "s@listen 443@listen ${HTTPS_PORT}@g" "${config_file}"
    sed -i "s@https://\$server_name\$request_uri;@https://\$server_name:${HTTPS_PORT}\$request_uri;@g" "${config_file}"
    if [ "${USE_IPV6}" == "1" ]; then
      sed -i "s@listen \[::\]:443@listen \[::\]:${HTTPS_PORT}@g" "${config_file}"
    fi
  fi

  if [ -n "${SSL_CERTIFICATE}" ] && [ -f "/etc/nginx/cert/${SSL_CERTIFICATE}" ]; then
    sed -i "s@ssl_certificate .*;@ssl_certificate cert/${SSL_CERTIFICATE};@g" "${config_file}"
  fi
  if [ -n "${SSL_CERTIFICATE_KEY}" ] && [ -f "/etc/nginx/cert/${SSL_CERTIFICATE_KEY}" ]; then
    sed -i "s@ssl_certificate_key .*;@ssl_certificate_key cert/${SSL_CERTIFICATE_KEY};@g" "${config_file}"
  fi
  if [ -n "${CLIENT_MAX_BODY_SIZE}" ]; then
    sed -i "s@client_max_body_size .*;@client_max_body_size ${CLIENT_MAX_BODY_SIZE};@g" "${config_file}"
  fi
}
```

**Comment by alfredfenglq** [comment]
> 确实需要转义，当时测试的时候可能漏了。
> 
> `https` 的端口请参考 `function config_https`
> 
> ```shell
> function config_https() {
>   config_file=/etc/nginx/conf.d/https_server.conf
>   if [ -f "${config_file}" ]; then
>     rm -f "${config_file}"
>   fi
>   cp -f /etc/nginx/sites-enabled/https_server.conf "${config_file}"
> 
>   config_nginx "${config_file}"
> 
>   if [ -z "${HTTPS_PORT}" ]; then
>     HTTPS_PORT=443
>   fi
> 
>   sed -i "s@server web:.*;@server localhost:51980;@g" "${config_file}"
> 
>   if [ "${USE_IPV6}" == "1" ]; then
>     sed -i "s@listen 443@listen [::]:443@g" "${config_file}"
>   fi
> 
>   if [ "${HTTPS_PORT}" != "443" ]; then
>     sed -i "s@listen 443@listen ${HTTPS_PORT}@g" "${config_file}"
>     sed -i "s@https://\$server_name\$request_uri;@https://\$server_name:${HTTPS_PORT}\$request_uri;@g" "${config_file}"
>     if [ "${USE_IPV6}" == "1" ]; then
>       sed -i "s@listen \[::\]:443@listen \[::\]:${HTTPS_PORT}@g" "${config_file}"
>     fi
>   fi
> 
>   if [ -n "${SSL_CERTIFICATE}" ] && [ -f "/etc/nginx/cert/${SSL_CERTIFICATE}" ]; then
>     sed -i "s@ssl_certificate .*;@ssl_certificate cert/${SSL_CERTIFICATE};@g" "${config_file}"
>   fi
>   if [ -n "${SSL_CERTIFICATE_KEY}" ] && [ -f "/etc/nginx/cert/${SSL_CERTIFICATE_KEY}" ]; then
>     sed -i "s@ssl_certificate_key .*;@ssl_certificate_key cert/${SSL_CERTIFICATE_KEY};@g" "${config_file}"
>   fi
>   if [ -n "${CLIENT_MAX_BODY_SIZE}" ]; then
>     sed -i "s@client_max_body_size .*;@client_max_body_size ${CLIENT_MAX_BODY_SIZE};@g" "${config_file}"
>   fi
> }
> ```

如果我没有理解错的话，这样在启用ipv6之后nginx只监听ipv6而不会监听ipv4了，它会把原始配置文件里面的listen 443直接替换为listen [::]:443而不是取消ipv6端口的注释

**Comment by wojiushixiaobai** [comment]
下面这行是吧，确实有问题
```sh
  if [ "${USE_IPV6}" == "1" ]; then
    sed -i "s@listen 443@listen [::]:443@g" "${config_file}"
  fi
```

**Comment by alfredfenglq** [comment]
> 下面这行是吧，确实有问题
> 
> ```shell
>   if [ "${USE_IPV6}" == "1" ]; then
>     sed -i "s@listen 443@listen [::]:443@g" "${config_file}"
>   fi
> ```

是的

**Comment by BaiJiangJie** [comment]
已合并，v3.10.4 会上线。

你可以根据这个 pr，修改后试一下。

https://github.com/jumpserver/docker-web/pull/159

**Comment by alfredfenglq** [comment]
> 已合并，v3.10.4 会上线。
> 
> 你可以根据这个 pr，修改后试一下。 @alfredfenglq
> 
> [jumpserver/docker-web#159](https://github.com/jumpserver/docker-web/pull/159)

确认已修复
