### ISSUE TITLE
[Bug] v1.5.7升级到 V3.10.0 之后 sz 不能使用了

### ISSUE THREAD

**Issue by huangjianye** [jumpserver/jumpserver#12493]
**Bug 描述**
v1.5.7升级到 V3.10 之后 sz 不能使用了， web终端出现同样的问题
奇怪的是 rz 命令能正常使用

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/49425015/6d130d2f-1324-44d5-ac78-1bcf4da98048)
2.
![image](https://github.com/jumpserver/jumpserver/assets/49425015/de30f53b-78e4-4e62-9b14-78751450e9cc)

3.大文件（50多M）
![image](https://github.com/jumpserver/jumpserver/assets/49425015/19fae294-87cb-4a57-9c72-f19d82409958)

4.传输结果
![image](https://github.com/jumpserver/jumpserver/assets/49425015/1a1e8d8d-121a-48e4-b19a-d32f2c31bab5)

5. sz 加上 -b -e 选项一直卡住，无法传输文件
![image](https://github.com/jumpserver/jumpserver/assets/49425015/d1edeb97-78b3-4c17-a3d0-7093e1d1da37)

**Comment by LeeEirc** [comment]
你使用哪一个 ssh 客户端？我测试使用 xshell 5 可以正常使用 sz 下载文件。

**Comment by huangjianye** [comment]
不能正常使用 sz 命令的shell版本是 Xshell_5.0.1339_Xftp_5.0.1235_PortableSoft ，这是个便携版（免安装，解压即可用的版本），在你的回复中意识到可能是ssh客户端版本的问题，于是下载安装了官网最新版本的 Xshell-7.0.0144p.exe，安装后并测试 sz、rz 命令使用一切正常，谢谢！

![image](https://github.com/jumpserver/jumpserver/assets/49425015/b79245be-25d2-4a9c-91e1-fb27ed8c78ad)


![image](https://github.com/jumpserver/jumpserver/assets/49425015/0ff2633b-fed3-409f-89b9-2d261198f72d)

**Comment by LeeEirc** [comment]
好的
