### ISSUE TITLE
升级3.10.0tls后发现Luna 无法显示完整的ip地址！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#12495]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
版本：3.10.0 3.10.1

**浏览器版本**
chrome最新版 120.0.6099.200
Firefox 版本121.0

**Bug 描述**
升级3.10.0tls版本后在chrome浏览上luna 连接windows资产 无法显示完整的ip地址
但在firefox浏览器可正常显示
更新到最新的3.10.1版本后故障依旧

**Bug 重现步骤(有截图更好)**
1.
![chrome无法显示完整ip](https://github.com/jumpserver/jumpserver/assets/36059301/823b20f5-4168-41f9-bf47-e3ed807805ab)

2.
![firefox显示完整ip](https://github.com/jumpserver/jumpserver/assets/36059301/329ebd56-c40d-4028-8b5f-85fcd443ba7b)

**Comment by BaiJiangJie** [comment]
是的，这里显示的是资产的名称，因为资产的名称可能会很长，所以考虑显示前面的字符，鼠标悬停上去显示完整名称。
