### ISSUE TITLE
[Question] 当我部署jumpserver3.10集群的时候总是会卡在初始化数据库

### ISSUE THREAD

**Issue by MetalCase** [jumpserver/jumpserver#12496]
**请描述您的问题.**
部署jumpserver3.10集群的时候总是会卡在初始化数据库
![image](https://github.com/jumpserver/jumpserver/assets/55723321/c72ca59a-8c2b-4a8b-aad4-bf76c60b10d7)

**Comment by wojiushixiaobai** [comment]
更新下内核，或者重启下服务器
