### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#125]
1.web终端某些机器卡死，登录jump服务websocket的cpu是100%，看其他人的反馈是编码引起的
2.根据上一个问题建议在添加主机资源的时候可以设置ssh编码
3.web的安全性，建议启用二次验证的模块，可参考https://duo.com/docs/duoweb

**Comment by ibuler** [comment]
1，2这两点我们也在研究，web端卡死等是编码问题，至于负载高不确认是不是编码导致
3 这个我们已经着手做了

**Comment by ibuler** [comment]
#527 参考一下实现
