### ISSUE TITLE
打开科学上网后登陆堡垒机提示错误

### ISSUE THREAD

**Issue by shibosen** [jumpserver/jumpserver#12503]
![image](https://github.com/jumpserver/jumpserver/assets/93109624/9e3ab1e5-3d1c-4f94-8eb4-2e08d92706eb)

**Comment by shibosen** [comment]
关闭科学上网后，访问正常，需要在哪里单独设置一下吗

**Comment by BaiJiangJie** [comment]
应该是你网络规则的设置问题。
