### ISSUE TITLE
[Bug] web gui执行oracle查询sql会出现"执行错误：IO错误：Socket read timed out

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12506]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1

**浏览器版本**
Google Chrome 120.0.6099.129

**Bug 描述**
web gui执行oracle查询sql会出现"执行错误：IO错误：Socket read timed out，表总记录数4000W

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/38065018/dcce062c-291d-4c1b-b760-ba3ef49bb6df)

**Comment by BaiJiangJie** [comment]
表中数据少一些的呢？会出现这个问题吗？或者加一些 limit 限制。

**Comment by jym503558564** [comment]
v3.10.2-lts优化了不限制超时设置。请升级至最新版本，进行测试。

**Comment by yuanxixue** [comment]
好的
