### ISSUE TITLE
仪表盘“帐号/资产活跃情况”趋势图显示不正常[Bug] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12504]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.1
另部分早期版本版本也有。

**浏览器版本**
火狐国际版 v121.0

**Bug 描述**
管理员初登Jumpserver，仪表盘“帐号/资产活跃情况”趋势图显示不正常。

**Bug 重现步骤(有截图更好)**
1.登录Jumpserver
2.查看“仪表板”
3.仪表盘“帐号/资产活跃情况”趋势图显示不正常：
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/50173a2f-ca61-4929-9b81-a358dbb91b1f)
4.连续点击“活跃帐号”2次后恢复正常：
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/180f1745-145d-490a-bd7e-74560c287125)
5.我有一个测试环境貌似没有这个问题，但在Jumpserver社区交流群中，有其他人也有这个问题：
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/d8f25640-5635-45b6-a664-66a5c31e7eb3)

**Comment by BaiJiangJie** [comment]
目前绘图好像确实有问题，我测试重新拖拽一下窗口，调整一下窗口大小就可以了。

不太好修复，但是问题确实存在。

**Comment by Halo1236** [comment]
<img width="781" alt="image" src="https://github.com/jumpserver/jumpserver/assets/17096387/47471db7-bd4c-4497-80f4-571d3d801ccc">

**Comment by BaiJiangJie** [comment]
最新版本已修复。
