### ISSUE TITLE
[Bug] v3.10.1 登陆记录为空，完全不记录登录日志

### ISSUE THREAD

**Issue by cecnet** [jumpserver/jumpserver#12500]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
全新安装的v3.10.1，登陆后，登陆记录里是空的，不记录登陆日志。

**Bug 重现步骤(有截图更好)**
1. 必现。
2.
3.

**Comment by BaiJiangJie** [comment]
v3.10 有问题。

登录日志实际上记录了，在列表获取信息的时候没有过滤出来，判断逻辑有点问题。

v3.10.2 处理一下。

**Comment by jym503558564** [comment]
v3.10.2-lts修复了用户登录成功，登录日志不显示的问题。请升级至最新版本，进行测试。
