### ISSUE TITLE
[Bug] Ansible could not initialize the preferred locale

### ISSUE THREAD

**Issue by chenxuan353** [jumpserver/jumpserver#12516]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

docker jms_all:v3.10.1

**浏览器版本**

chrome 115.0.5790.171

**Bug 描述**

ERROR: Ansible could not initialize the preferred locale: unsupported locale setting

进入容器内执行ansible --version后有相同报错，设置环境变量LANG=C.UTF-8后正常，但网页执行测试依旧报这个错误。

**Bug 重现步骤(有截图更好)**
1.docker安装jms_all
2.添加资产
3.测试资产

![image](https://github.com/jumpserver/jumpserver/assets/48858695/1f032c9b-6871-4e87-b458-6a7a4cef2a18)

**Comment by chenxuan353** [comment]
linux 配置了ssh和sftp，ssh和ftp能通过堡垒机连接。

**Comment by feng626** [comment]
ansible在运行时找不到对应的语言环境 ，尝试把环境变量是永久性修改 再重启容器

**Comment by chenxuan353** [comment]
尝试过进入容器设置以及运行参数设置，都没有效果。

**Comment by feng626** [comment]
改完后重启了么 服务要重启 celery

**Comment by chenxuan353** [comment]
容器重启过了，甚至系统也重启过。

**Comment by feng626** [comment]
重启后进到容器里 你设置的环境变量还在么
https://fabianlee.org/2023/08/21/ansible-resolving-could-not-initialize-the-preferred-locale-unsupported-locale-setting/ 看看这个

**Comment by chenxuan353** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48858695/e7938f58-c8d0-47ac-9269-ef56e9c395e1)
![image](https://github.com/jumpserver/jumpserver/assets/48858695/df05755c-86f4-44e1-9cd4-3e287f3e1d73)

**Comment by chenxuan353** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48858695/9ff17ba6-fa80-4ed1-aa2d-8dd7e3bfcadb)
![image](https://github.com/jumpserver/jumpserver/assets/48858695/11de80b0-a508-4ad1-b100-fb73a5beadfd)

**Comment by feng626** [comment]
LC_ALL=C.UTF-8 试试

**Comment by chenxuan353** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/48858695/5c75ed1f-6409-4920-bd78-7f9816af8c1c)

**Comment by feng626** [comment]
cd apps/common/management/commands/services/services  然后修改celery_base.py文件
<img width="861" alt="image" src="https://github.com/jumpserver/jumpserver/assets/57284900/16b4d5e7-6eb6-4a03-8386-aed7ce4fdd33">
添加这一行 再重启jms_celery 容器 改也是改jms_celery容器里的代码

**Comment by chenxuan353** [comment]
只添加下述部分依旧有问题
```
os.environ.setdefault('LANG', 'C.UTF-8')
```

只添加这个后解决
```
os.environ.setdefault('LC_ALL', 'C.UTF-8')
```

**Comment by feng626** [comment]
3.10.2修复

**Comment by BaiJiangJie** [comment]
升级到最新版本使用。
@chenxuan353
