### ISSUE TITLE
[Bug] 数据库审计时的一些问题

### ISSUE THREAD

**Issue by kk545141** [jumpserver/jumpserver#12513]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

V3.9.3

**浏览器版本**

chrome 版本 120.0.6099.200（正式版本） （64 位）

**Bug 描述**

1. 对数据库命令的审核，采用cli形式连接时，可以通过敲错字符再回撤的形式绕过审核。
2. 数据库远程应用web访问形式可以记录用户命令，但记录不全。尤其是当出现backspace命令时，后续记录不全。当通过远程应用的客户端形式访问时，无法记录命令。
3. mysql客户端连接方式下，使用call执行存储过程时报错，其他方式暂未发现问题。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/29938714/4f587d50-cb91-4242-a705-f05b6d85538a)

2.
3.

**Comment by BaiJiangJie** [comment]
第3个问题可以研究一下。

第1、2问题，目前确实存在，没有解决方案。

**Comment by Aaron3S** [comment]
好的 。我复现一下 mysql 存储过程的问题。
