### ISSUE TITLE
LDAP定时任务执行结果邮件告警[Feature] 

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#12518]
**请描述您的需求或者改进建议.**
执行LDAP定时任务的时候，结果想要邮件告警

**Comment by BaiJiangJie** [comment]
可以考虑。

**Comment by 1223ruiyin** [comment]
> 可以考虑。
> 
> 你具体描述一下详细需求。 比如：邮件内容想看到哪些信息？是基于什么场景下需要查看结果？

基于执行自动化任务的场景之下，执行结果通过邮件告知，比如LDAP定时同步用户，执行成功与否需要在执行结束后邮件或钉钉发出执行结果，任务什么时间执行的，执行花费了多久，执行结果是什么类似于这种信息内容较详细。

**Comment by BaiJiangJie** [comment]
好的。

**Comment by jym503558564** [comment]
v3.10.2-lts版本新增LDAP同步后发送信息通知接收人。请升级至最新版本，进行测试。
