### ISSUE TITLE
[Question] xshell连接MySQL时如何关闭自动补全功能

### ISSUE THREAD

**Issue by xmabul** [jumpserver/jumpserver#12515]
web终端是有“禁用自动补全”选项
![image](https://github.com/jumpserver/jumpserver/assets/25163530/1f565c38-525f-4565-88ac-0319bae95c6c)

但是，如果通过xshell连接到堡垒机，选择连接mysql就没有该选项
![image](https://github.com/jumpserver/jumpserver/assets/25163530/2ac381a4-5236-49d5-a1c0-7341c258ad12)

做为DBA，正常都是建议默认关闭auto-rehash，如果koko代码里没有指定默认--auto-rehash，那可以通过my.cnf指定--no-auto-rehash来禁用，建议你们去掉默认指定

**Comment by BaiJiangJie** [comment]
@LeeEirc 看看能不能加一个配置来控制 客户端方式连接。（或者默认关闭）

**Comment by BaiJiangJie** [comment]
Web CLI 端支持，本地客户端不打算支持了。

**Comment by xmabul** [comment]
> Web CLI 端支持，本地客户端不打算支持了。

@BaiJiangJie 本地客户端确实也没有界面可交互式配置，就是建议koko [CommandArgs](https://github.com/jumpserver/koko/blob/ad98cf72bd4a50bc9c1e60c9201b89dd5d79e1a9/pkg/srvconn/conn_mysql.go#L190C1-L190C1)这个方法不要写死默认一定要传authRehashFlag变量

建议改成如下：
```
func (opt *sqlOption) CommandArgs() []string {
	args := make([]string, 0, 6)
	// authRehashFlag := "--auto-rehash"
	if opt.disableMySQLAutoRehash {
		authRehashFlag = "--no-auto-rehash"
                args = append(args, authRehashFlag)   // 有传递参数disableMySQLAutoRehash或enableMySQLAutoRehash(目前你们没有这参数) 才去配置该值，否则走mysql客户端默认配置
	}
	//args = append(args, authRehashFlag)
	if charset := os.Getenv(kokoMySQLDefaultCharset); charset != "" {
		charset = strings.TrimSpace(charset)
		args = append(args, fmt.Sprintf("--default-character-set=%s", charset))
	}
	args = append(args, fmt.Sprintf("--user=%s", opt.Username))
	args = append(args, fmt.Sprintf("--host=%s", opt.Host))
	args = append(args, fmt.Sprintf("--port=%d", opt.Port))
	args = append(args, "--password")
	args = append(args, opt.DBName)
	return args
}
```
只要协议不传`--auto-rehash`，那么不管Web CLI还是本地客户端都能通过koko那台的mysql.cnf配置[mysql]块来指定是否自动补全，客户端展示字符集`default-character-set`也是同样解决方法。

**Comment by gnayfly** [comment]
> > Web CLI 端支持，本地客户端不打算支持了。
> 
> @BaiJiangJie 本地客户端确实也没有界面可交互式配置，就是建议koko [CommandArgs](https://github.com/jumpserver/koko/blob/ad98cf72bd4a50bc9c1e60c9201b89dd5d79e1a9/pkg/srvconn/conn_mysql.go#L190C1-L190C1)这个方法不要写死默认一定要传authRehashFlag变量
> 
> 建议改成如下：
> 
> ```
> func (opt *sqlOption) CommandArgs() []string {
> 	args := make([]string, 0, 6)
> 	// authRehashFlag := "--auto-rehash"
> 	if opt.disableMySQLAutoRehash {
> 		authRehashFlag = "--no-auto-rehash"
>                 args = append(args, authRehashFlag)   // 有传递参数disableMySQLAutoRehash或enableMySQLAutoRehash(目前你们没有这参数) 才去配置该值，否则走mysql客户端默认配置
> 	}
> 	//args = append(args, authRehashFlag)
> 	if charset := os.Getenv(kokoMySQLDefaultCharset); charset != "" {
> 		charset = strings.TrimSpace(charset)
> 		args = append(args, fmt.Sprintf("--default-character-set=%s", charset))
> 	}
> 	args = append(args, fmt.Sprintf("--user=%s", opt.Username))
> 	args = append(args, fmt.Sprintf("--host=%s", opt.Host))
> 	args = append(args, fmt.Sprintf("--port=%d", opt.Port))
> 	args = append(args, "--password")
> 	args = append(args, opt.DBName)
> 	return args
> }
> ```
> 
> 只要协议不传`--auto-rehash`，那么不管Web CLI还是本地客户端都能通过koko那台的mysql.cnf配置[mysql]块来指定是否自动补全，客户端展示字符集`default-character-set`也是同样解决方法。

谢谢你提供的思路，我按照你上面的代码，注释掉那2行(//)，会报找不到变量: authRehashFlag ，后来我是直接修改
authRehashFlag := "--auto-rehash"
变成
authRehashFlag := "--no-auto-rehash"
直接禁止
再按照文档:https://github.com/jumpserver/koko/tree/master，重新make一下，把build目录下的koko-linux-amd64，复制出来，再上传到docker koko容器，替换掉原来的koko，重启容器就可以了，非常感谢！

**Comment by xmabul** [comment]
> > > Web CLI 端支持，本地客户端不打算支持了。
> > 
> > 
> > @BaiJiangJie 本地客户端确实也没有界面可交互式配置，就是建议koko [CommandArgs](https://github.com/jumpserver/koko/blob/ad98cf72bd4a50bc9c1e60c9201b89dd5d79e1a9/pkg/srvconn/conn_mysql.go#L190C1-L190C1)这个方法不要写死默认一定要传authRehashFlag变量
> > 建议改成如下：
> > ```
> > func (opt *sqlOption) CommandArgs() []string {
> > 	args := make([]string, 0, 6)
> > 	// authRehashFlag := "--auto-rehash"
> > 	if opt.disableMySQLAutoRehash {
> > 		authRehashFlag = "--no-auto-rehash"
> >                 args = append(args, authRehashFlag)   // 有传递参数disableMySQLAutoRehash或enableMySQLAutoRehash(目前你们没有这参数) 才去配置该值，否则走mysql客户端默认配置
> > 	}
> > 	//args = append(args, authRehashFlag)
> > 	if charset := os.Getenv(kokoMySQLDefaultCharset); charset != "" {
> > 		charset = strings.TrimSpace(charset)
> > 		args = append(args, fmt.Sprintf("--default-character-set=%s", charset))
> > 	}
> > 	args = append(args, fmt.Sprintf("--user=%s", opt.Username))
> > 	args = append(args, fmt.Sprintf("--host=%s", opt.Host))
> > 	args = append(args, fmt.Sprintf("--port=%d", opt.Port))
> > 	args = append(args, "--password")
> > 	args = append(args, opt.DBName)
> > 	return args
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 只要协议不传`--auto-rehash`，那么不管Web CLI还是本地客户端都能通过koko那台的mysql.cnf配置[mysql]块来指定是否自动补全，客户端展示字符集`default-character-set`也是同样解决方法。
> 
> 谢谢你提供的思路，我按照你上面的代码，注释掉那2行(//)，会报找不到变量: authRehashFlag ，后来我是直接修改 authRehashFlag := "--auto-rehash" 变成 authRehashFlag := "--no-auto-rehash" 直接禁止 再按照文档:[https://github.com/jumpserver/koko/tree/master，重新make一下，把build目录下的koko-linux-amd64，复制出来，再上传到docker](https://github.com/jumpserver/koko/tree/master%EF%BC%8C%E9%87%8D%E6%96%B0make%E4%B8%80%E4%B8%8B%EF%BC%8C%E6%8A%8Abuild%E7%9B%AE%E5%BD%95%E4%B8%8B%E7%9A%84koko-linux-amd64%EF%BC%8C%E5%A4%8D%E5%88%B6%E5%87%BA%E6%9D%A5%EF%BC%8C%E5%86%8D%E4%B8%8A%E4%BC%A0%E5%88%B0docker) koko容器，替换掉原来的koko，重启容器就可以了，非常感谢！

可能没注意到我还有加了一行，不过你能实现效果也可以
