### ISSUE TITLE
[Feature] 希望可以为K8S添加搜索和查看日志

### ISSUE THREAD

**Issue by isdamir** [jumpserver/jumpserver#12511]
目前在终端里面，机器实例可以搜索，但是点击K8S的资产后就无搜索按钮了。一般实际情况下的K8S集群规模都比较大，无搜索很难定位到一个实例。希望可以增加搜索。我在使用的过程中发现，K8S的实例是实时加载的，这会带来搜索的实现困难，建议可以缓存实例数据，刷新按钮逻辑改为强制刷新缓存。
另外K8S的实例，很多情况下运维需要查看通多stdout输出的日志，希望在终端里面增加一个按钮查看日志，可以查看容器输出的日志内容。
这两个在实际使用中都比较影响运维工作，希望可以沟通一下。

**Comment by BaiJiangJie** [comment]
你指的是 Web 页面还是客户端方式？

**Comment by fikimbing** [comment]
目前web页面是需要这个功能的，因为使用web登录设备的时候， 有时候输入命令之后，会输出一堆有用没用的信息，这个时候需要搜索关键字搜索上下文。现在这个功能是没有的。就比较难用一些。希望能有这个功能
