### ISSUE TITLE
建议web控制台打开选择用户时勾选“下次自动登录”可以保存到服务端[Feature] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12521]
建议web控制台打开选择用户时勾选“下次自动登录”可以保存到服务端。
对于运维或开发人员，可能会经常清理和堡垒机相同主域名的另一个二级域名的Cookie。这样在清除Cookie后会导致堡垒机的Cookie也一并被清理。
如果相关设置能够保存到服务端数据库，则清理浏览器数据后不会丢失。

**Comment by BaiJiangJie** [comment]
清楚 Cookie 没关系的，”自动登录的信息“ 是保存在 Local Storage 中的， 不要清楚 Storage 就行，Cookie 不影响。

**Comment by akang1798** [comment]
我可能表达的不够严谨，实际是“清除Cookie和网站数据”这个快捷按钮。包括Cookie和网站的数据。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/aac55009-ecc5-413d-92b5-546a59434665)

**Comment by BaiJiangJie** [comment]
这样的话包含网站数据了，可能就会导致 Storage 中的数据被清除。

**Comment by akang1798** [comment]
嗯。除此之外，一旦不是这个浏览器，比如更换了电脑，则之前的设置都会丢失。所以建议能保存服务端数据库保存。

**Comment by BaiJiangJie** [comment]
嗯，其实需求还是比较合理的。但是有一些用户是不想存放在后端的。

将来可以考虑支持后端存储，短期内暂时不考虑了。

**Comment by akang1798** [comment]
如果有用户的确不想保存在后端数据库，或许可以有个选项，由用户自行选择。
