### ISSUE TITLE
[Feature] 日志审计功能优化建议

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#12529]
**请描述您的需求或者改进建议.**
背景：资产经常会发生名称、IP地址等信息的变动。
现状：版本V3.10.1，发现审计台上，“命令日志”、“文件传输”以及“操作日志”这3个模块，无法根据资产ID来筛选日志；
当资产的ip和名称有变化的时候，根据资产名称或者IP来过滤日志会存在问题，因为会无法筛选出资产更新前或者更新后的相关记录，给审计工作带来很大的麻烦。
希望能增加“根据资产ID筛选”的功能。

**Comment by BaiJiangJie** [comment]
目前 命令日志 和 文件传输 日志都和 会话记录有关联。

如果都在其他操作日志中包含 资产 ID，那会有很多冗余字段，不符合设计逻辑。

<img width="1806" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/99dad107-79bd-4f20-8df9-0a3d445083ce">

新版本支持在资产详情中查看命令记录。

暂时不考虑通过 资产ID 进行搜索。
