### ISSUE TITLE
[Feature] 远程应用发布机希望添加网域连接

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#12532]
远程应用发布机，可能存在跨网络访问的情况，希望添加网域设置。

**Comment by BaiJiangJie** [comment]
<img width="1607" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d8dd6a2d-0d48-45b0-ab9a-d4017b89fe85">

最新版本，支持网域功能。

**Comment by kzcPo** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16077203/ceae4cbd-0f67-4160-aba0-6e3ba73b3843)
当前版本v3.10.1，并未看到网域的功能，是还未发版吗？
