### ISSUE TITLE
远程应用随机账号，希望能指定账号

### ISSUE THREAD

**Issue by guohengh** [jumpserver/jumpserver#12531]
**请描述您的需求或者改进建议.**

远程应用登录的时候，用的是随机账号访问windows应用发布机，这一块用户有需求使用指定账户，这样会很方便保存用户信息，便于用户下次操作时，能够记住上次的操作。

**Comment by BaiJiangJie** [comment]
在远程应用发布机详情中，删除 jms_ 开头的账号即可。

**Comment by guohengh** [comment]
删除jms账号后，会因为没账号选择，报core api错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Bryan ***@***.***&gt;
发送时间: 2024年1月12日 16:36
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: guoheng ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] 远程应用随机账号，希望能指定账号 (Issue #12531)





 
在远程应用发布机详情中，删除 jms_ 开头的账号即可。
