### ISSUE TITLE
[Bug] 存储配置成功后，不生效

### ISSUE THREAD

**Issue by ideamean** [jumpserver/jumpserver#12535]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.1

**浏览器版本**
chrome 版本 120.0.6099.216（正式版本） (arm64)

**Bug 描述**
采用在线安装：https://docs.jumpserver.org/zh/v3/installation/setup_linux_standalone/online_install/#1
安装版本：jumpserver-installer-v3.10.1
问题：配置了命令存储es，但是不生效，还是走了默认的存储，测试成功，并且验证es索引已经自动创建。 对象存储配置了oss也是如此

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/824662/a3727143-67a5-4b46-bd01-1e99fdd177b0)

2.
![image](https://github.com/jumpserver/jumpserver/assets/824662/d2bbd987-12c7-4182-ae7d-aba14d7c9a4a)

3.

**Comment by BaiJiangJie** [comment]
终端设置中更新一下存储设置。

默认存储是在新创建终端的时候会使用。

<img width="1197" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/4a245a10-04a0-4d69-a111-999d488b908a">

**Comment by ideamean** [comment]
更新了， 记录里依然展示不出来，oss有了
![image](https://github.com/jumpserver/jumpserver/assets/824662/723e1dcb-acb4-4d03-879d-50268619da2d)
![image](https://github.com/jumpserver/jumpserver/assets/824662/cea32118-5c5b-465f-8597-ef436f790d47)
