### ISSUE TITLE
helm 安装部署dockerproxy.com/jumpserver/web:v3.10.1镜像版本 无法正常运行

### ISSUE THREAD

**Issue by yang0009** [jumpserver/jumpserver#12538]
helm 安装部署v3.10.0镜像版本
jms-k8s-jumpserver-jms-web pod 不断重启，容器stdout 内容日志显示
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
Starting periodic command scheduler: cron.
/docker-entrypoint.sh: Configuration complete; ready for start up
...
一直卡着然后不断重启

**Comment by wojiushixiaobai** [comment]
看看持久化里面的 nginx 日子 /var/log/nginx/

**Comment by yang0009** [comment]
> 看看持久化里面的 `nginx` 日志 `/var/log/nginx/`

![image](https://github.com/jumpserver/jumpserver/assets/47616231/48ce4a85-0e81-4e9e-a7fb-ac39d119e36e)

**Comment by BaiJiangJie** [comment]
探活的时候没连上，之前用的什么版本？

**Comment by hu16725434** [comment]
从3.9.3的数据库导出迁移到3.10.2，nginx持久化日志也报楼主你的这个错误，登录页面都打不开

**Comment by wojiushixiaobai** [comment]
k8s 的话删掉 web pod 重建即可，或者等待一会会自动就绪，如果无法就绪，自行解决 k8s pod 网络问题

**Comment by yang0009** [comment]
> k8s 的话删掉 web pod 重建即可，或者等待一会会自动就绪，如果无法就绪，自行解决 k8s pod 网络问题

Liveness probe failed: HTTP probe failed with statuscode: 502
Readiness probe failed: HTTP probe failed with statuscode: 502
重启之后也是一样的，502应该是本身服务的报错？

**Comment by wojiushixiaobai** [comment]
没法复现，你手动排查下看看。
502 应该是 web 无法连接到 core 的 pod
