### ISSUE TITLE
[Bug] CAS 认证，邮箱属性映射不生效。

### ISSUE THREAD

**Issue by leshalv** [jumpserver/jumpserver#12537]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.10.0

**浏览器版本**

谷歌 120.0.6099.199

**Bug 描述**

CAS 认证，配置邮箱属性映射不生效。

**Bug 重现步骤(有截图更好)**

jumpserver 配置

<img width="954" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30397655/d5720293-c5b5-4e4c-a190-67b07b53cad8">

cas server 返回

```xml
<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
    <cas:authenticationSuccess>
        <cas:user>topiam</cas:user>
        <cas:attributes>
            <cas:name>topiam</cas:name>
            <cas:email>support@topiam.cn</cas:email>
        </cas:attributes>
    </cas:authenticationSuccess>
</cas:serviceResponse>
```

**Comment by BaiJiangJie** [comment]
具体要看 API 返回来的属性 key 是什么。

不生效现在会报什么错？

**Comment by leshalv** [comment]
返回的属性是 <cas:email>support@topiam.cn</cas:email>，查看个人信息，该值没有展示。

**Comment by BaiJiangJie** [comment]
应该是服务器配置的问题。

**Comment by deng00** [comment]
最新版本  name或uid 字段 应该改为 cas:user ,  但是email 字段不知如何配置
