### ISSUE TITLE
[Feature] 使用客户端工具运维操作MySQL数据库，如MySQL开启SSL后，连接会报错

### ISSUE THREAD

**Issue by haipeng-fit2** [jumpserver/jumpserver#12540]
**请描述您的需求或者改进建议.**
MySQL5.7和8.0版本，开启了SSL后，使用客户端工具登录目标MySQL数据库，会提示1045-backend auth error auth failed。使用webGUI的方式登录正常。

**Comment by BaiJiangJie** [comment]
客户端方式不支持 SSL 连接。

**Comment by liushan9981** [comment]
请问版本v3.10.12支持mysql资产录入时通过ssl连接，用户使用客户端工具连接吗？
我现在这样用，还是报错：1045-backend auth error
