### ISSUE TITLE
已经结束的会话仍然出现在在线会话列表中

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1254]
Version: 1.2

**Comment by snowkity2005** [comment]
Version 1.3.0-2 版本也有这个问题。

**Comment by opstrip** [comment]
还有报“Error reading SSH protocol bannerfiledescriptor out of range in select()”错误导致连不上，不知道是不是跟这个有关。

**Comment by py0426** [comment]
还有一个问题，这些已结束的会话，手动中断也是失效的。
