### ISSUE TITLE
[Bug] 账号管理-账号列表 获取列表的速度非常非常的慢

### ISSUE THREAD

**Issue by luyouli** [jumpserver/jumpserver#12546]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
helm部署的3.10.1

**浏览器版本**
Chrome 版本 120.0.6099.217（正式版本）

**Bug 描述**
控制台-账号管理-账号列表 获取数据的速度非常的慢，要8-9秒才能把90条数据列出来

**Bug 重现步骤(有截图更好)**
1.选择 控制台
2.选择 账号管理
3.选择 账号列表
![BUG 1](https://github.com/jumpserver/jumpserver/assets/28440272/5de61f27-1f15-4d8e-b611-16a8fd729a15)

![BUG 2](https://github.com/jumpserver/jumpserver/assets/28440272/5476fcd4-355f-404f-974c-0466dd42d958)

**Comment by BaiJiangJie** [comment]
其他列表的速度怎么样？看看资产列表。

**Comment by luyouli** [comment]
其他列表都没问题，唯独账号列表非常非常的慢，而且在等待账号列表期间，CPU使用率200%以上
![BUG 3](https://github.com/jumpserver/jumpserver/assets/28440272/0d8f6507-5443-4d23-8820-0ce4d4330a92)

**Comment by BaiJiangJie** [comment]
配置文件开一下 DEBUG 看看日志是那条查询比较慢。
```
DEBUG=true
DEBUG_DEV=true
LOG_LEVEL=DEBUG
```

**Comment by luyouli** [comment]
DEBUG模式打开，在pod内jms restart重启，core-pod就会是0/1尚未就绪的状态

**Comment by BaiJiangJie** [comment]
修改配置启动时看一下截图日志。

**Comment by nickzhuyb** [comment]
我也遇到了，账号管理里的账号列表和账号模板 这两个页面各几十条数据，每次http请求都要5～10秒，其他用户、资产、权限页面打开都很快。请问这个问题要如何定位？

**Comment by BaiJiangJie** [comment]
还真是没有遇到过，升级到最新版本试一下。

对账号列表的获取有优化。
