### ISSUE TITLE
[Bug] [Question] jumpserver v2.28.20 web界面无法连接资产，提示connection websocket closed 

### ISSUE THREAD

**Issue by 1018565530** [jumpserver/jumpserver#12553]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
升级 v3 解决。

https://github.com/jumpserver/jumpserver/issues/12519

**Comment by 1018565530** [comment]
[迁移之后提示 jumpserver v2.28.20 web界面无法连接资产，提示connection websocket closed](https://github.com/jumpserver/jumpserver/issues/12553#top)
