### ISSUE TITLE
单机部署，清理环境时，提示需要需要卸载docker

### ISSUE THREAD

**Issue by gzwxh** [jumpserver/jumpserver#12558]
再使用单机部署时，如果异常之后，重新部署，清理环境会将已经部署的docker服务一起清理掉，是否可以提示一下，jumpserver已经停止完，但是还再使用docker运行的服务信息

**Comment by BaiJiangJie** [comment]
应该会提示是否删除 docker 吧？

**Comment by gzwxh** [comment]
是会提示，想想让他提示时，执行一个docker ps 
看一下是否还有再运行的docker服务

**Comment by wojiushixiaobai** [comment]
你可以先自己部署 docker，手动安装的 docker 脚本不会处理。
我们脚本自动安装的脚本会自动删除。
