### ISSUE TITLE
[Bug] Jumpserver从3.8.1升级到3.10.0后从一台服务器退出后到加载资产列表延迟

### ISSUE THREAD

**Issue by 26cm** [jumpserver/jumpserver#12550]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.8.1 -> 3.10.0 -> 3.10.1

**浏览器版本**

xshell
**Bug 描述**
使用docker部署的jms，外置mysql/redis,下载v3.10.0后执行./jmsctl.sh upgrade使服务从3.8.1升级到3.10.0
问题现象：
当我从某台服务器上执行ctrl+D退出后返回到资产列表时，响应有1-3s左右的延迟
发现koko会有如下日志：
2024-01-04 14:15:07 [ERRO] Session[2d8a8aba-b640-4149-bc91-9fed2ab3b295] srv read err: EOF
2024-01-04 14:15:07 [ERRO] Session[2d8a8aba-b640-4149-bc91-9fed2ab3b295] user read err: io: read/write on closed pipe

后续升级到了3.10.1仍然存在该现象
录了一个视频可以看一下现象：

https://github.com/jumpserver/jumpserver/assets/121849700/b9edfee1-5388-46e5-8db8-7380e5c74f87

**Bug 重现步骤(有截图更好)**

**Comment by BaiJiangJie** [comment]
这是正常的，以前从连接的资产中退出，会直接显示 终端的菜单页面，新版本会返回上次查询搜索的结果页面，所以会看到有一些延迟。

**Comment by jym503558564** [comment]
这是优化后的结果。当资产退出或者连接失败是，返回上次查询结果页面，方便用户继续连接其他资产。

**Comment by 26cm** [comment]
主要是我感觉这有个问题：我的理解，当我从某个资产退出时，服务端实际上是产生了一个sql查询来返回资产列表，如果mysql部署在远端而不是服务局域网，那么返回资产列表的速度会有点慢；现在我就部署在jms本机上面，这个查询理论上是非常快的，但是这个查询就要2-3秒，这个显然是不正常的。
