### ISSUE TITLE
删除资产时，如该资产对应的授权规则只有一个资产可以考虑关联删除资产授权

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#12560]
当用户删除资产时，资产对应的授权会保留下了；当有很多资产存在时会出来大量过期不存在的，可以考虑判断删除资产时如果资产授权规则中只有当前资产，可以将授权关联删除

**Comment by BaiJiangJie** [comment]
不太合理，暂不考虑。
