### ISSUE TITLE
重启的时候 Celery cpu 爆表 redis堵塞

### ISSUE THREAD

**Issue by alexshenyuefei** [jumpserver/jumpserver#1256]
<img width="468" alt="1111" src="https://user-images.githubusercontent.com/16495430/39349178-97c79b22-4a2c-11e8-8d66-970525181ef5.png">

[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 Version 1.0.0-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
<img width="524" alt="5246433515938" src="https://user-images.githubusercontent.com/16495430/39284086-3233c5c6-4944-11e8-83f1-8f5ae89b81cd.png">

##### 其他
临时把在线会话删了，能定时删除在线会话吗

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可以关闭定时任务，
```
export PERIOD_TASK=0 
```
然后重启jumpserver

**Comment by ibuler** [comment]
已默认关闭 celery定时任务

**Comment by liyanxia** [comment]
在哪里设置 export PERIOD_TASK=0
