### ISSUE TITLE
[Bug] ssh登录密码口令不能包含英文的单引号和双引号

### ISSUE THREAD

**Issue by lwyg65** [jumpserver/jumpserver#12576]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.8 

**浏览器版本**
chrome 120.0.6099.225

**Bug 描述**
web端 SSH登录服务器，规则要求“手动输入密码”，正常情况下，在web端输入密码之后，能建立ssh连接的。
但是，部分服务器密码是生成的随机密码，一定概率是会包含单引号（'）和双引号（")的，如果我要输入的密码包含了其中之一的话，就会出现登录不上的情况，在ssh软件界面输入是没有问题的。

**Bug 重现步骤(有截图更好)**
1.把某台能ssh登录的用户密码修改成包含单引号（'）或者双引号（")的，
2.远程登录改成密码需要手动输入
3.远程连接，输入密码

**Comment by BaiJiangJie** [comment]
v3 最新版本支持。

https://github.com/jumpserver/jumpserver/issues/12519

升级到最新版本使用。
