### ISSUE TITLE
[Feature] Add the default language in a config file or by a global setting

### ISSUE THREAD

**Issue by troublestarter** [jumpserver/jumpserver#12578]
**请描述您的需求或者改进建议.**
Is it possible to configure the default language (on the web page) with a default language parameter in global configuration ?

Default chinese version is not very suitable in our situation.

Thanks you.

**Comment by BaiJiangJie** [comment]
`LANGUAGE_CODE=en`

You can try to configure the above values in the configuration file `config.txt`.

**Comment by troublestarter** [comment]
> `LANGUAGE_CODE=en`
> 
> You can try to configure the above values in the configuration file `config.txt`.

Seems working.

To be perferct, this value should have changed too :

![image](https://github.com/jumpserver/jumpserver/assets/6012203/f007fa17-372a-47d7-b80b-6b8b7c4fbcab)

**Comment by BaiJiangJie** [comment]
Refreshing the browser should be enough. If the browser and system settings are consistent, there should be no problem.

**Comment by troublestarter** [comment]
Yes it is good.
Thanks you @BaiJiangJie
