### ISSUE TITLE
[Bug] 无法访问ui【已解决】

### ISSUE THREAD

**Issue by vvb7456** [jumpserver/jumpserver#12575]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
[v3.10.2-lts](https://github.com/jumpserver/jumpserver/releases/tag/v3.10.2)

**浏览器版本**
Microsoft Edge

**Bug 描述**
类似#11874，一键安装后可以登陆，但登陆后不加载ui，使用内网http或公网ssl故障一致。

**Bug 重现步骤(有截图更好)**
![QQ截图20240119013338](https://github.com/jumpserver/jumpserver/assets/24655851/ce5c322d-ff06-4cd8-b4ec-5422af6a6b0c)

**Comment by vvb7456** [comment]
# /opt/jumpserver/config/config.txt 
# JumpServer configuration file example.
#
# 如果不了解用途可以跳过修改此配置文件, 系统会自动填入
# 完整参数文档 https://docs.jumpserver.org/zh/v3/guide/env/

################################## 镜像配置 ###################################
#
# 国内连接 docker.io 会超时或下载速度较慢, 开启此选项使用华为云镜像加速
# 取代旧版本 DOCKER_IMAGE_PREFIX
#
DOCKER_IMAGE_MIRROR=1

# 镜像拉取规则 Always, IfNotPresent
# Always 表示每次都会拉取最新镜像, IfNotPresent 表示本地不存在镜像时才会拉取
#
# IMAGE_PULL_POLICY=Always

################################## 安装配置 ###################################
#
# JumpServer 数据库持久化目录, 默认情况下录像、任务日志都在此目录
# 请根据实际情况修改, 升级时备份的数据库文件(.sql)和配置文件也会保存到该目录
#
VOLUME_DIR=/data/jumpserver

# 加密密钥, 迁移请保证 SECRET_KEY 与旧环境一致, 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 SECRET_KEY
#
SECRET_KEY=******************************************************

# 组件向 core 注册使用的 token, 迁移请保持 BOOTSTRAP_TOKEN 与旧环境一致,
# 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 BOOTSTRAP_TOKEN
#
BOOTSTRAP_TOKEN=*************************************************

# 日志等级 INFO, WARN, ERROR
#
LOG_LEVEL=ERROR

# JumpServer 容器使用的网段, 请勿与现有的网络冲突, 根据实际情况自行修改
#
DOCKER_SUBNET=192.168.250.0/24

# ipv6 nat, 正常情况下无需开启
# 如果宿主不支持 ipv6 开启此选项将会导致无法获取真实的客户端 ip 地址
#
USE_IPV6=0
DOCKER_SUBNET_IPV6=fc00:1010:1111:200::/64

################################# MySQL 配置 ##################################
# 外置 MySQL 需要输入正确的 MySQL 信息, 内置 MySQL 系统会自动处理
#
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=********************************************
DB_NAME=jumpserver

# 如果外置 MySQL 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/mysql_ssl/
#
# DB_USE_SSL=true

################################# Redis 配置 ##################################
# 外置 Redis 需要请输入正确的 Redis 信息, 内置 Redis 系统会自动处理
#
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=***************************************************

# 如果使用外置 Redis Sentinel, 请手动填写下面内容
#
# REDIS_SENTINEL_HOSTS=mymaster/192.168.100.1:26379,192.168.100.1:26380,192.168.100.1:26381
# REDIS_SENTINEL_PASSWORD=your_sentinel_password
# REDIS_PASSWORD=your_redis_password
# REDIS_SENTINEL_SOCKET_TIMEOUT=5

# 如果外置 Redis 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/redis_ssl/
#
# REDIS_USE_SSL=true

################################## 访问配置 ###################################
# 对外提供服务端口, 如果与现有服务冲突请自行修改
#
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_MYSQL_PORT=33061
MAGNUS_MARIADB_PORT=33062
MAGNUS_REDIS_PORT=63790
MAGNUS_POSTGRESQL_PORT=54320
MAGNUS_SQLSERVER_PORT=14330
MAGNUS_ORACLE_PORTS=30000-30030

################################# HTTPS 配置 #################################
# 参考 https://docs.jumpserver.org/zh/v3/installation/proxy/ 配置
#
HTTPS_PORT=8443
SERVER_NAME=my.domains.com
SSL_CERTIFICATE=fullchain.pem
SSL_CERTIFICATE_KEY=privkey.key
#

# Nginx 文件上传下载大小限制
#
CLIENT_MAX_BODY_SIZE=4096m

################################## 组件配置 ###################################
# 组件注册使用, 默认情况下向 core 容器注册, 集群环境需要修改为集群 vip 地址
#
CORE_HOST=http://core:8080
PERIOD_TASK_ENABLED=true

# Core Session 定义,
# SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期,
# SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
#
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=true

# 可信任 DOMAINS 定义,
# 定义可信任的访问 IP, 请根据实际情况修改, 如果是公网 IP 请改成对应的公网 IP,
# DOMAINS="demo.jumpserver.org:443"
# DOMAINS="172.17.200.191:80"
# DOMAINS="demo.jumpserver.org:443,172.17.200.191:80"
DOMAINS="my.domains.com:8443"

# 配置不需要启动的组件, 默认所有组件都会开启, 如果不需要某个组件可以通过设置 {组件名称}_ENABLED 为 0 关闭
# CORE_ENABLED=0
# CELERY_ENABLED=0
# KOKO_ENABLED=0
# LION_ENABLED=0
# MAGNUS_ENABLED=0
# CHEN_ENABLED=0
# KAEL_ENABLED=0
# PANDA_ENABLED=0

# Lion 开启字体平滑, 优化体验
#
JUMPSERVER_ENABLE_FONT_SMOOTHING=true

################################# XPack 配置 #################################
# XPack 包, 开源版本设置无效
#
RDP_PORT=3389
XRDP_PORT=3390

################################## 其他配置 ##################################
# 终端使用宿主 HOSTNAME 标识, 首次安装自动生成
#
SERVER_HOSTNAME=JumpServer

# 使用内置 SLB, 如果 Web 页面获取到的客户端 IP 地址不正确, 请将 USE_LB 设置为 0
# USE_LB 设置为 1 时, 使用配置 proxy_set_header X-Forwarded-For $remote_addr
# USE_LB 设置为 0 时, 使用配置 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
USE_LB=1

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#
CURRENT_VERSION=v3.10.2

**Comment by vvb7456** [comment]
# /opt/jumpserver/config/config.txt 
```# JumpServer configuration file example.
#
# 如果不了解用途可以跳过修改此配置文件, 系统会自动填入
# 完整参数文档 https://docs.jumpserver.org/zh/v3/guide/env/

################################## 镜像配置 ###################################
#
# 国内连接 docker.io 会超时或下载速度较慢, 开启此选项使用华为云镜像加速
# 取代旧版本 DOCKER_IMAGE_PREFIX
#
DOCKER_IMAGE_MIRROR=1

# 镜像拉取规则 Always, IfNotPresent
# Always 表示每次都会拉取最新镜像, IfNotPresent 表示本地不存在镜像时才会拉取
#
# IMAGE_PULL_POLICY=Always

################################## 安装配置 ###################################
#
# JumpServer 数据库持久化目录, 默认情况下录像、任务日志都在此目录
# 请根据实际情况修改, 升级时备份的数据库文件(.sql)和配置文件也会保存到该目录
#
VOLUME_DIR=/data/jumpserver

# 加密密钥, 迁移请保证 SECRET_KEY 与旧环境一致, 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 SECRET_KEY
#
SECRET_KEY=******************************************************

# 组件向 core 注册使用的 token, 迁移请保持 BOOTSTRAP_TOKEN 与旧环境一致,
# 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 BOOTSTRAP_TOKEN
#
BOOTSTRAP_TOKEN=*************************************************

# 日志等级 INFO, WARN, ERROR
#
LOG_LEVEL=ERROR

# JumpServer 容器使用的网段, 请勿与现有的网络冲突, 根据实际情况自行修改
#
DOCKER_SUBNET=192.168.250.0/24

# ipv6 nat, 正常情况下无需开启
# 如果宿主不支持 ipv6 开启此选项将会导致无法获取真实的客户端 ip 地址
#
USE_IPV6=0
DOCKER_SUBNET_IPV6=fc00:1010:1111:200::/64

################################# MySQL 配置 ##################################
# 外置 MySQL 需要输入正确的 MySQL 信息, 内置 MySQL 系统会自动处理
#
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=********************************************
DB_NAME=jumpserver

# 如果外置 MySQL 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/mysql_ssl/
#
# DB_USE_SSL=true

################################# Redis 配置 ##################################
# 外置 Redis 需要请输入正确的 Redis 信息, 内置 Redis 系统会自动处理
#
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=***************************************************

# 如果使用外置 Redis Sentinel, 请手动填写下面内容
#
# REDIS_SENTINEL_HOSTS=mymaster/192.168.100.1:26379,192.168.100.1:26380,192.168.100.1:26381
# REDIS_SENTINEL_PASSWORD=your_sentinel_password
# REDIS_PASSWORD=your_redis_password
# REDIS_SENTINEL_SOCKET_TIMEOUT=5

# 如果外置 Redis 需要开启 TLS/SSL 连接, 参考 https://docs.jumpserver.org/zh/v3/installation/security_setup/redis_ssl/
#
# REDIS_USE_SSL=true

################################## 访问配置 ###################################
# 对外提供服务端口, 如果与现有服务冲突请自行修改
#
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_MYSQL_PORT=33061
MAGNUS_MARIADB_PORT=33062
MAGNUS_REDIS_PORT=63790
MAGNUS_POSTGRESQL_PORT=54320
MAGNUS_SQLSERVER_PORT=14330
MAGNUS_ORACLE_PORTS=30000-30030

################################# HTTPS 配置 #################################
# 参考 https://docs.jumpserver.org/zh/v3/installation/proxy/ 配置
#
HTTPS_PORT=8443
SERVER_NAME=my.domains.com
SSL_CERTIFICATE=fullchain.pem
SSL_CERTIFICATE_KEY=privkey.key
#

# Nginx 文件上传下载大小限制
#
CLIENT_MAX_BODY_SIZE=4096m

################################## 组件配置 ###################################
# 组件注册使用, 默认情况下向 core 容器注册, 集群环境需要修改为集群 vip 地址
#
CORE_HOST=http://core:8080
PERIOD_TASK_ENABLED=true

# Core Session 定义,
# SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期,
# SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
#
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=true

# 可信任 DOMAINS 定义,
# 定义可信任的访问 IP, 请根据实际情况修改, 如果是公网 IP 请改成对应的公网 IP,
# DOMAINS="demo.jumpserver.org:443"
# DOMAINS="172.17.200.191:80"
# DOMAINS="demo.jumpserver.org:443,172.17.200.191:80"
DOMAINS="my.domains.com:8443"

# 配置不需要启动的组件, 默认所有组件都会开启, 如果不需要某个组件可以通过设置 {组件名称}_ENABLED 为 0 关闭
# CORE_ENABLED=0
# CELERY_ENABLED=0
# KOKO_ENABLED=0
# LION_ENABLED=0
# MAGNUS_ENABLED=0
# CHEN_ENABLED=0
# KAEL_ENABLED=0
# PANDA_ENABLED=0

# Lion 开启字体平滑, 优化体验
#
JUMPSERVER_ENABLE_FONT_SMOOTHING=true

################################# XPack 配置 #################################
# XPack 包, 开源版本设置无效
#
RDP_PORT=3389
XRDP_PORT=3390

################################## 其他配置 ##################################
# 终端使用宿主 HOSTNAME 标识, 首次安装自动生成
#
SERVER_HOSTNAME=JumpServer

# 使用内置 SLB, 如果 Web 页面获取到的客户端 IP 地址不正确, 请将 USE_LB 设置为 0
# USE_LB 设置为 1 时, 使用配置 proxy_set_header X-Forwarded-For $remote_addr
# USE_LB 设置为 0 时, 使用配置 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
USE_LB=1

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#
CURRENT_VERSION=v3.10.2
```

**Comment by fstd2** [comment]
从v3.8.1升级，有同样问题

**Comment by cecnet** [comment]
3.10.1升级上来首次登陆也是加载不出来，刷新一下就进去了，后面都正常进入。

**Comment by jym503558564** [comment]
日志发出来看一下？

**Comment by vvb7456** [comment]
> 日志发出来看一下？

不知为何/data/jumpserver/core/data/logs/jumpserver.log文件是空的
倒是发现nginx有几个错误
```2024/01/19` 00:44:28 [error] 72#72: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /core/auth/login/?csrf_failure=1&admin=1 HTTP/1.1", upstream: "http://192.168.250.7:8080/core/auth/login/?csrf_failure=1&admin=1", host: "my.domain.com", referrer: "https://my.domain.com:8443/core/auth/login/"
2024/01/19 00:44:31 [error] 70#70: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/v1/settings/public/open/ HTTP/1.1", upstream: "http://192.168.250.7:8080/api/v1/settings/public/open/", host: "my.domain.com", referrer: "https://my.domain.com:8443/"
2024/01/19 00:44:31 [error] 72#72: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/v1/settings/public/open/ HTTP/1.1", upstream: "http://192.168.250.7:8080/api/v1/settings/public/open/", host: "my.domain.com", referrer: "https://my.domain.com:8443/ui/"
2024/01/19 00:44:32 [error] 72#72: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/health/ HTTP/1.1", upstream: "http://192.168.250.7:8080/api/health/", host: "localhost:51980" ```

**Comment by topsage** [comment]
我测试也有问题，能从3.10.2 回退吗？

**Comment by topsage** [comment]
我回退到3.10.1  清浏览器缓存后都正常了

**Comment by Qiming0912** [comment]
从3.10.1升级到3.10.2遇到一样的问题，可以登录，但是卡ui界面。问下怎样退回操作？

**Comment by topsage** [comment]
> 从3.10.1升级到3.10.2遇到一样的问题，可以登录，但是卡ui界面。问下怎样退回操作？

我直接用3.10.1 做upgrade，我虚拟机部署，打快照了。你可以试试，打个快照回退。。。

**Comment by fstd2** [comment]
- /data/jumpserver/core/data/logs/
```
[I 240119 02:17:00 command:168] Visit me at http://0.0.0.0:5555//core/flower/
[I 240119 02:17:00 command:176] Broker: redis://:**@redis:6379/3
[I 240119 02:17:00 command:177] Registered tasks: 
    ['accounts.tasks.automation.execute_account_automation_task',
     'accounts.tasks.automation.execute_automation_record_task',
     'accounts.tasks.backup_account.execute_account_backup_task',
     'accounts.tasks.gather_accounts.gather_asset_accounts_task',
     'accounts.tasks.push_account.push_accounts_to_assets_task',
     'accounts.tasks.remove_account.clean_historical_accounts',
     'accounts.tasks.remove_account.remove_accounts_task',
     'accounts.tasks.template.template_sync_related_accounts',
     'accounts.tasks.vault.sync_secret_to_vault',
     'accounts.tasks.verify_account.verify_accounts_connectivity_task',
     'assets.tasks.automation.execute_asset_automation_task',
     'assets.tasks.gather_facts.gather_assets_facts_task',
     'assets.tasks.nodes_amount.check_node_assets_amount_period_task',
     'assets.tasks.nodes_amount.check_node_assets_amount_task',
     'assets.tasks.ping.test_assets_connectivity_task',
     'assets.tasks.ping_gateway.test_gateways_connectivity_task',
     'audits.tasks.clean_audits_log_period',
     'audits.tasks.upload_ftp_file_to_external_storage',
     'authentication.tasks.clean_django_sessions',
     'celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'common.tasks.send_mail_async',
     'common.tasks.send_mail_attachment_async',
     'common.tasks.upload_backup_to_obj_storage',
     'common.utils.verify_code.send_async',
     'notifications.notifications.publish_task',
     'ops.tasks.check_server_performance_period',
     'ops.tasks.clean_celery_periodic_tasks',
     'ops.tasks.clean_job_execution_period',
     'ops.tasks.clean_up_unexpected_jobs',
     'ops.tasks.create_or_update_registered_periodic_tasks',
     'ops.tasks.run_ops_job',
     'ops.tasks.run_ops_job_execution',
     'orgs.tasks.refresh_org_cache_task',
     'perms.tasks.check_asset_permission_expired',
     'perms.tasks.check_asset_permission_will_expired',
     'settings.tasks.ldap.import_ldap_user',
     'settings.tasks.ldap.import_ldap_user_periodic',
     'terminal.tasks.applet_host_generate_accounts',
     'terminal.tasks.check_command_replay_storage_connectivity',
     'terminal.tasks.clean_orphan_session',
     'terminal.tasks.delete_terminal_status_period',
     'terminal.tasks.run_applet_host_deployment',
     'terminal.tasks.run_applet_host_deployment_install_applet',
     'terminal.tasks.upload_session_replay_to_external_storage',
     'users.signal_handlers.clean_expired_user_session_period',
     'users.tasks.check_password_expired',
     'users.tasks.check_password_expired_periodic',
     'users.tasks.check_unused_users',
     'users.tasks.check_user_expired',
     'users.tasks.check_user_expired_periodic']
[I 240119 02:17:00 mixins:228] Connected to redis://:**@redis:6379/3
[W 240119 02:17:01 inspector:44] Inspect method scheduled failed
[W 240119 02:17:01 inspector:44] Inspect method conf failed
[W 240119 02:17:01 inspector:44] Inspect method registered failed
[W 240119 02:17:01 inspector:44] Inspect method reserved failed
[W 240119 02:17:01 inspector:44] Inspect method stats failed
[W 240119 02:17:01 inspector:44] Inspect method revoked failed
[W 240119 02:17:01 inspector:44] Inspect method active_queues failed
[W 240119 02:17:01 inspector:44] Inspect method active failed
```
core里好像没有看到其它报错

**Comment by BaiJiangJie** [comment]
大家都是在线升级吗？

**Comment by fstd2** [comment]
> 大家都是在线升级吗？

我是在线升级

**Comment by vvb7456** [comment]
> 大家都是在线升级吗？

我是全新安装

**Comment by BaiJiangJie** [comment]
全新安装是使用的离线包吗？

**Comment by BaiJiangJie** [comment]
在线安装看看本地使用的镜像源是哪个？

**Comment by BaiJiangJie** [comment]
目前，docker pull jumpserver/web:v3.10.2 从 docker hub 官方源拉一下最新的镜像，重启应该可以。

**Comment by vvb7456** [comment]
> 全新安装是使用的离线包吗？

在线 ```curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash```

**Comment by BaiJiangJie** [comment]
CDN 的问题，现在应该可以了。
@vvb7456

**Comment by BaiJiangJie** [comment]
重新pull一下镜像。

**Comment by fstd2** [comment]
配置文件启用的DOCKER_IMAGE_MIRROR=1，应该是华为的镜像
从docker hub拉了最新的镜像，问题已解决
![image](https://github.com/jumpserver/jumpserver/assets/56252962/1a76308f-8067-4731-9abb-8b31622abf09)

**Comment by vvb7456** [comment]
> 目前，docker pull jumpserver/web:v3.10.2 从 docker hub 官方源拉一下最新的镜像，重启应该可以。


`docker pull jumpserver/web:v3.10.2 && jmsctl restart`

刷新浏览器后页面上方提示

```<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->```

清除浏览器缓存与cookie，重启后恢复正常

**Comment by BaiJiangJie** [comment]
嗯，现在华为云的镜像也同步了。

**Comment by jym503558564** [comment]
已解决，有该问题的用户，可更新web镜像，重启服务。
docker pull jumpserver/web:v3.10.2
jmsctl restart
