### ISSUE TITLE
录像存放在ali-oss上，无法回放

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1258]
已正确配置，录像也保存到了阿里OSS上，但是在历史会话中点击回放时，显示无法下载。
OSS上文件的读取权限设置的公共读，没有做限制。

**Comment by wojiushixiaobai** [comment]
尝试直接用url连接访问文件，看提示什么？
就是oss的url地址，不是从oss客户端里面访问，在浏览器直接访问文件的地址，看有没有报错

**Comment by gengkeye** [comment]
>尝试直接用url连接访问文件，看提示什么？
就是oss的url地址，不是从oss客户端里面访问，在浏览器直接访问文件的地址，看有没有报错

@wojiushixiaobai 直接访问是没有问题的，可以正常下载

**Comment by liuzheng** [comment]
其实不推荐直接挂使用oss的开放可读权限，容易被别人拿走，请按照我们的nginx配置进行操作。

**Comment by gengkeye** [comment]
原来是因为jms-stroage的版本太低，升级到0.0.13就OK了

**Comment by liuzheng** [comment]
@gengkeye 社区里有人图方便，直接改nginx配置的情况也是有的，只是我不建议这样做，这样做的好处就是快，坏处就是别人可能可以拿到日志，不过需要配合oss的设置
