### ISSUE TITLE
[Bug] Jumpserver无法连接11.5.8.0 这个版本的 DB2

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#12588]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.2

**浏览器版本**
版本 120.0.6099.216（正式版本） (arm64)

**Bug 描述**
连接DB2 提示连接被拒绝，但是使用DBeaver同样的连接参数可以正常连接。

**Bug 重现步骤(有截图更好)**
1.这是Jumpserver连接DB2的报错
<img width="984" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/e246ea07-1c97-4eac-b9d3-dcbaf7e2d615">

2.这是DBeaver成功连接到DB2的截图
<img width="914" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/a90a04dd-ea9e-45d9-b0f2-7f9720cb68a0">

3.

**Comment by BaiJiangJie** [comment]
其他版本的 DB2 可以吗？

**Comment by BaiJiangJie** [comment]
我们试试能不能复现这个版本的 DB2
