### ISSUE TITLE
Jump版本2.28.8，命令返回Command not allowed，是和默认库有关系吗？

### ISSUE THREAD

**Issue by zfq314** [jumpserver/jumpserver#12581]
在web页面上，点击web终端--我的应用--随意选择一个MySQL应用后--连接方式选择DB Client--确认后把数据库连接信息填入到Navicat客户端后，在navicat客户端上测试连接提示连接成功，随后执行一条alter语句后提示“Command not allowed”，系统用户是mysql的root用户；
我当前使用的jumpserver版本是2.28.8，我查了下issue好像是bug，请问这个问题在哪个版本里解决了呢，能否升级！！！

**Comment by maninhill** [comment]
v2 已经停止更新了，请升级到最新的 v3 版本。

**Comment by zfq314** [comment]
好的，多谢
