### ISSUE TITLE
[Bug] V3.7.1 web终端sz下载有时候无文件

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#12582]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.1

**浏览器版本**

版本 120.0.6099.71（正式版本） （64 位）

**Bug 描述**
通过sz命令下载文件后，进度为100%时，有时候出现下载为空且浏览器不会弹出下载记录

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/12181410/9d52fb90-9653-48ef-b164-e2e86d8f9510)
![image](https://github.com/jumpserver/jumpserver/assets/12181410/0c55c21c-f335-4a03-ad1f-c832adcb2d28)

**Comment by maninhill** [comment]
请升级到最新的 v3.10.2-lts 版本。

**Comment by BaiJiangJie** [comment]
最新版本对这块有优化。

> 请升级到最新的 v3.10.2-lts 版本。

@nondevops
