### ISSUE TITLE
关于用户审计角色[Feature] 

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12584]
有时候可能会为外包临时开通一个用户u2，为了全程跟踪u2的活动，我希望能够指派内部一个普通用户u1能够审计u2，包括查看实时的操作，并能够阻断暂停等。为u1配置“系统审计员”虽然可以解决上面问题，但范围太大，我不希望u1能够审计所有人员的操作。所以是否可以针对u2来创建审计角色？

**Comment by BaiJiangJie** [comment]
审计角色分为两种级别：系统级别、组织级别。不支持针对某个用户或者某个资源进行审计。

在企业版本中，你可以创建一个组织，将 u2 单独放到一个组织中，赋予 u1 为这个组织的审计角色，进行实现。
但是，角色范围最小也是组织级别的。
