### ISSUE TITLE
连接资产时账号选择手动收入，不输入账号密码而去连接，会一直显示连接中，而不会有错误提示[Feature] 

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#12586]
**请描述您的需求或者改进建议.**

![image](https://github.com/jumpserver/jumpserver/assets/136306850/87835cb4-9f05-4988-a0ba-7a569f8a450b)
<img width="748" alt="77e096ecfb8db389f7ce58f8205aefc" src="https://github.com/jumpserver/jumpserver/assets/136306850/5ccd53dc-f363-411b-bed3-71ca026e7dd6">

**Comment by BaiJiangJie** [comment]
使用的什么版本？

**Comment by jym503558564** [comment]
待优化
![image](https://github.com/jumpserver/jumpserver/assets/40739051/ec1d3d6e-a603-4589-87af-f9de8af5c0d1)

**Comment by 1223ruiyin** [comment]
好的

**Comment by 1223ruiyin** [comment]
> 待优化 ![image](https://private-user-images.githubusercontent.com/40739051/299576322-ec1d3d6e-a603-4589-87af-f9de8af5c0d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODY4NjgsIm5iZiI6MTcwNjU4NjU2OCwicGF0aCI6Ii80MDczOTA1MS8yOTk1NzYzMjItZWMxZDNkNmUtYTYwMy00NTg5LTg3YWYtZjlkZThhZjVjMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzNDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OGJlMzQ4MjJmODk3NjA0N2EwMmIzNTkzZGMzMzZhMDk0MjA0NDI2Njg1Y2VjZTM0YWUyZDllNzEzMjY4NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5V_xruib3nmjjRmHulBhz2_j3YLusXlOW2iVFl7nFoc)

你好，请问一下预计哪个版本可以修复呢

**Comment by BaiJiangJie** [comment]
目前还没有定位到问题，得找找原因。修复版本暂时还不确定。

**Comment by 1223ruiyin** [comment]
> 目前还没有定位到问题，得找找原因。修复版本暂时还不确定。

好的，多谢

**Comment by jym503558564** [comment]
v3.10.4已发布，请升级进行体验。
