### ISSUE TITLE
请问如何配置ES来保存命令记录

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1259]
有没有文档可参考，谢谢

**Comment by stephen8339** [comment]
+1

**Comment by ibuler** [comment]
访问终端配置页面 /settings/terminal/ 设置命令存储
{
    "default":{
        "TYPE":"server"
    },
    "ali-es":{
        "TYPE":"elasticsearch",
        "HOSTS":[
            "http://elastic:changeme@localhost:9200"
        ]
    }
}

然后终端选择使用新设置的es作为命令存储

**Comment by gengkeye** [comment]
@ibuler 感谢

**Comment by jijianming** [comment]
> 访问终端配置页面 /settings/terminal/ 设置命令存储
> 
> ```
> {
>     "default":{
>         "TYPE":"server"
>     },
>     "ali-es":{
>         "TYPE":"elasticsearch",
>         "HOSTS":[
>             "http://elastic:changeme@localhost:9200"
>         ]
>     }
> }
> ```
> 
> 然后终端选择使用新设置的es作为命令存储

如果es有密码呢？

**Comment by w2n1ck** [comment]
配置完，为啥没生效呀？

**Comment by alireza1371** [comment]
guys please someone answer this issue, its not working on both GUI and cli after configuring ES.
