### ISSUE TITLE
[Feature] 对象存储对接是否可以增加NFS协议实现挂载

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#12594]
**对象存储对接是否可以增加NFS协议实现挂载**
原型图如下：
<img width="876" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/e7cfa32f-bb77-47b9-a5c6-a61d24d1ca23">

**Comment by BaiJiangJie** [comment]
可以考虑一下，不知道会不会特别慢。

**Comment by huskiesir** [comment]
> 可以考虑一下，不知道会不会特别慢。

那就期待一下子

**Comment by BaiJiangJie** [comment]
嗯，将来可能会考虑，中短期目前还没有计划。
