### ISSUE TITLE
3.10.3 的core-ce 镜像没有同步吗？

### ISSUE THREAD

**Issue by topsage** [jumpserver/jumpserver#12608]
升级v3.10.3 找不到core-ce 镜像
![3cdf69cc83fc2855d6515d20d61f562](https://github.com/jumpserver/jumpserver/assets/51810073/d540f09e-5f01-47d7-ab52-3ddf83b108a2)

**Comment by jym503558564** [comment]
在线升级方式？

**Comment by jym503558564** [comment]
最新镜像已上传成功，请升级进行验证。
