### ISSUE TITLE
网络PA设备改密[Feature] 

### ISSUE THREAD

**Issue by guohengh** [jumpserver/jumpserver#12607]
**请描述您的需求或者改进建议.**
网络设备类型 palo alto FW 设备型号 PAVM100，IOS-11，PAVM50,IOS-8.1.PA因为有个commit命令提交后生效，改密计划所以失败，有客户希望能够支持。

**Comment by BaiJiangJie** [comment]
使用自定义改密命令应该可以支持吧

**Comment by guohengh** [comment]
主要特点是commit后需要一分钟配置才生效，不是立即生效。会导致改密不生效

**Comment by BaiJiangJie** [comment]
没理解是什么意思，如果要支持的话，需要产品做什么操作？

**Comment by guohengh** [comment]
就是不通过jms，用户&nbsp;发送&nbsp;那边的改密命令提交后，也需要一分钟后改密生效，所以这类设备就不好使用改密计划了。那暂时忽略吧，因为这种场景也比较少，也不是标准化的网络设备。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月29日(星期一) 下午2:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] 网络PA设备改密[Feature]  (Issue #12607)





 
没理解是什么意思，如果要支持的话，需要产品做什么操作？

**Comment by BaiJiangJie** [comment]
好的。
