### ISSUE TITLE
怎么清理录像

### ISSUE THREAD

**Issue by ansemz** [jumpserver/jumpserver#1260]
[简述你的问题]

##### 使用版本
Version 1.2.1-2

##### 问题复现步骤
1. 在会话管理-历史会话中没有找到删除录像的功能

##### 其他

[注:] 完成后请关闭 issue

**Comment by stephen8339** [comment]
JUMPSERVER_DIR下面根本没有media这文件夹。。。

**Comment by ansemz** [comment]
在JUMPSERVER_DIR/data/media下面的的确有录像文件。
但是历史会话列表应该是存在数据库里面的吧。如果我只是删除了录像文件，就不知道哪些历史会话有录像了

**Comment by ibuler** [comment]
删除后就无法播放了
