### ISSUE TITLE
[Question] 有人遇到升级到3.10.2后，使用xshell或crt工具连接jms的配置实例后，退出响应时间变长的问题吗

### ISSUE THREAD

**Issue by tangguangliang** [jumpserver/jumpserver#12619]
之前使用3.6.2的版本，连接实例退后基本不到1s就退出，现在升级到3.10.2后，退出实例有2s左右的延迟，有人遇到过吗

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12550

其实是优化后的结果。
