### ISSUE TITLE
新增定时任务中如何选择python版本为python3

### ISSUE THREAD

**Issue by evirts** [jumpserver/jumpserver#12613]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/10336478/42bbe096-d147-4b64-aab4-111268644742)
返回错误ERROR! failed at splitting arguments either an unbalanced jinja2 block or quotes: #!/usr/bin/env python
把该脚本放到服务器上执行没问题，通过定时任务执行就返回如上错误

**Comment by BaiJiangJie** [comment]
目前不支持指定，把脚本中的第一、二行去掉呢？

**Comment by evirts** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/10336478/ca0d096d-12e9-40ce-a187-3bb2be7e5fc9)
去掉了也是报同样的错误

![image](https://github.com/jumpserver/jumpserver/assets/10336478/802b0d93-c59f-4809-a564-15f4f923e4cf)
我把py代码保存到服务器上，然后通过shell去执行就没问题

**Comment by BaiJiangJie** [comment]
python /data/scripts/1.py 呢？

是不是 python3 和 python 调用的不是同一个。

**Comment by evirts** [comment]
刚改成python执行脚本也是正常的，手动在服务器上执行以及通过定时页面shell方式，都是正常

**Comment by BaiJiangJie** [comment]
配置文件开启一下 `DEBUG_ANSIBLE=true` 的配置，然后重启服务，再执行一下任务，看看详细日志。
