### ISSUE TITLE
[Bug] 特权用户测试可连接，但 Web 终端提示密码失败

### ISSUE THREAD

**Issue by tonycody** [jumpserver/jumpserver#12616]
![image](https://github.com/jumpserver/jumpserver/assets/6773121/fce501b6-e293-4b42-81a7-5eca92b5291f)
![image](https://github.com/jumpserver/jumpserver/assets/6773121/ad6eb482-e223-487f-9c7f-84fdda651004)

v2.28.7

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12519
