### ISSUE TITLE
[Question] Can't upload Files in Windows Machine

### ISSUE THREAD

**Issue by jennerfernandesfilho** [jumpserver/jumpserver#12610]
Hi,

I'm testing the JumpServer on my environment, and while testing those feature I find myself facing a problem to upload files in a Windows 10 machine (lab). I didn't found where i can upload files in a easy way.

![image](https://github.com/jumpserver/jumpserver/assets/157854557/ad743f4c-60d4-480c-b109-5c4c436be249)
![image](https://github.com/jumpserver/jumpserver/assets/157854557/697fa85e-d93e-4140-b945-25cc8b28b473)

I've tried change the "Upload Directory" to a Windows Directory (C: or something like that) but i'm not allowed to do that. Transfer files to linux was easy, but transfer files to Windows environment has been a bad experience.

Someone can help?

**Comment by BaiJiangJie** [comment]
Bulk uploading files also supports Windows, but requires Windows assets to configure the SSH protocol and install the openssh service on the Windows host.

**Comment by BaiJiangJie** [comment]
Have you configured it?

**Comment by jennerfernandesfilho** [comment]
For security compliance on my customer, I won't be able to open SSH access on Microsoft environment. Is the Bulky upload the only way to upload files on a Microsoft Windows Server? There some simple way to upload single files on a Windows Access? I tried through RDP Session, File Manager, drop and drag without success.

Can help?

**Comment by jennerfernandesfilho** [comment]
I'm tried to upload files through the RDP Session, but i'm not able to locate on my local machine.

![image](https://github.com/jumpserver/jumpserver/assets/157854557/21a13553-04ee-4ec0-a5af-2b8e5f1c0bbf)

**Comment by BaiJiangJie** [comment]
Okay, if there is no need for bulk upload, the files can be uploaded in a single RDP session as shown in your screenshot.
One thing you need to know is that when the upload is completed, it will not appear in your C drive, but will be stored in the shared drive. Like below.

<img width="1127" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/220d0b90-88ef-4cd2-b986-979d22ba7a15">

**Comment by jennerfernandesfilho** [comment]
Perfect, I found it.

![image](https://github.com/jumpserver/jumpserver/assets/157854557/a33bbf37-aa24-4b59-94f4-a5ee8d6e5416)

Thank you so much!!
