### ISSUE TITLE
[Feature] JumpServer账号推送的功能

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12611]
**请描述您的需求或者改进建议.**
JumpServer账号推送设置了用户属性，如：用户组、家目录等属性，后期后期更改用户属性再次推送的话，用户属性不会发生变化。后期只能通过手动的方式登录服务器进行修改。

**Comment by BaiJiangJie** [comment]
是的，目前策略是只有当用户不存在的时候会设置。
服务器上已存在的用户就不会更改了。
