### ISSUE TITLE
[Bug] 使用Web GUI方式连接数据库，选择其他分页或者导出全部的时候，提示“connection closed”

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#12623]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.2

**浏览器版本**
Chrome 121.0.6167.85

**Bug 描述**
使用Web GUI方式连接数据库，选择其他分页或者导出全部的时候，提示“connection closed”
![image](https://github.com/jumpserver/jumpserver/assets/104493699/7377f75a-d54a-4048-aa6b-00ca62ba9435)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
看一下 Chen 组件的日志，报什么错？

**Comment by shimengqiao** [comment]
执行docker logs -f jms_chen 然后点击导出全部，没有日志输出

**Comment by shimengqiao** [comment]
看 /data/jumpserver/chen/data/logs/chen.log 也没有报错日志

**Comment by BaiJiangJie** [comment]
好的，我们来本地复现一下。

**Comment by BaiJiangJie** [comment]
目前已经修复了，v3.10.4 版本会上线。

**Comment by jym503558564** [comment]
v3.10.4已发布，请升级进行体验。
