### ISSUE TITLE
[Bug] JumpServer v3.10.3 用户可访问登录资产树节点下其它未授权服务器

### ISSUE THREAD

**Issue by tomseanmy** [jumpserver/jumpserver#12627]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
Chrome 版本 121.0.6167.85

**Bug 描述**
JumpServer v3.10.3，突然发现开发人员可点击访问资产树节点下其它未授权的服务器！！！

![image](https://github.com/jumpserver/jumpserver/assets/42232933/7aa6041c-b2c3-4098-801c-4aacac33b4b6)

如图所示：当前的用户设置的是只能访问151这台服务器，但实际情况是他可以访问节点下的其它服务器。确认没有把124服务器授权给当前用户。但是在资产里的授权信息里，却有该开发人员的信息。

问题比较严重！！！

这是授权配置截图：
![image](https://github.com/jumpserver/jumpserver/assets/42232933/7318b216-eabb-41a9-bab6-afab3ad4effc)

![image](https://github.com/jumpserver/jumpserver/assets/42232933/dd87fb33-e647-46c8-a033-2e4d607bc048)

**Bug 重现步骤(有截图更好)**
1.配置资产组1，分配2台服务器
2.授权用户A对资产组1的2台服务器访问权限
3.确认用户A能正常对资产组1的2台服务器的正常访问
4.取消用户A对资产组1的其中一台服务器的访问权限
5.发现用户A依然能访问资产组1中的2台服务器

预期：在取消用户A对资产组1其中一台服务器的授权后，用户A只能访问未被取消授权的1台服务器

**Comment by feng626** [comment]
取消用户A对资产组1其中一台服务器的授权 是怎么取消的 将资产从组1里删除？

**Comment by tomseanmy** [comment]
> 取消用户A对资产组1其中一台服务器的授权 是怎么取消的 将资产从组1里删除？

修改资产授权规则里的资产列表，移除对应的资产。

**Comment by BaiJiangJie** [comment]
v3.10.3 有一些延时，v3.10.4 会有优化。

Luna 页面用户授权树应该只是会显示，真正连接的时候应该是禁止的。（确认一下，是否是这样的情况）

**Comment by tomseanmy** [comment]
> v3.10.3 有一些延时，v3.10.4 会有优化。（主要考虑大规模资产时频繁刷新的问题，下个版本会考虑小规模资产刷新速度，立即刷新）
> 
> Luna 页面用户授权树应该只是会显示，真正连接的时候应该是禁止的。（确认一下，是否是这样的情况）

并非如此，实际情况是被移除了资源的用户依然能够正常查看、访问和操作资源

**Comment by BaiJiangJie** [comment]
什么时候方便远程看一下吗？应该还是有授权。

**Comment by tomseanmy** [comment]
> 什么时候方便远程看一下吗？应该还是有授权。 @tomseanmy

感谢，已经找到原因了（如果节点属性设置了值，资产属性设置就不起作用了），社区论坛有人回复是因为资产和节点权限同时设置的问题。已验证去掉节点属性设置后资产属性中的值就生效了。

**Comment by alexg9781** [comment]
遇到了同样的问题
请问具体 节点属性 和 资产属性 的配置是什么地方，我是用的是v3 版本的
