### ISSUE TITLE
[Bug] JumpServer资产加入网域通过网关连接后，通过sftp上传下载文件速度明显变慢

### ISSUE THREAD

**Issue by PlaneV** [jumpserver/jumpserver#12620]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.3~v3.10

**浏览器版本**
Microsoft Edge v120

**Bug 描述**
问题是这样的，我们公司的服务器分别放在几个不同的局域网内，所以我们开了几个网域网关来连接不通局域网的服务器，各种功能都能正常使用，只有上传文件到服务器的速度特别慢，明显和带宽相差太远，最近发现只要资产不配置网关就没有问题，请问这个有什么方法优化吗？
这个问题其实从3.1开始就发现，之前一直找不到原因

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
多了一层网关，中间传输就会多一层转存，没有好的办法。

**Comment by PlaneV** [comment]
针对这个情况，目前想到两个可能有效的方法：
1. 在各个子网络分别安装独立的Jumpserver
2. 在各子网找一台服务器作为网关安装wireguard，配通网络转发就可以在Jumpserver上直接通过局域网IP访问相应的服务器

还没测试，还不知道优劣，各位大牛觉得可不可行？

**Comment by BaiJiangJie** [comment]
如果都部署两套了，可以考虑使用 JumpServer 的服务端点和端点规则功能来试试。

**Comment by PlaneV** [comment]
服务端点是个不错的解决方法，达到的效果应该和用wireguard+路由规则做出来的效果差不多，可能会在资源消耗上稍微吃亏一点，但是在有局域网段IP冲突的环境里，Jumpserver的配置时更简单方便的
