### ISSUE TITLE
[Question] 直连资产如何实现的

### ISSUE THREAD

**Issue by Casslie** [jumpserver/jumpserver#12624]
**v2.11.0 版本提供了 ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222 直连资产，想咨询下这种实现方式，ssh命令不支持，如何处理的ssh命令的参数；

**Comment by BaiJiangJie** [comment]
这样就是直连的方式，ssh 命令不支持是什么意思？

**Comment by Casslie** [comment]
> 这样就是直连的方式，ssh 命令不支持是什么意思？

直连设备是先登录堡垒机节点，在登录目标资产，这个过程需要完成两步认证么？所以我的疑问在于：
1. ssh本身不支持多个@吧，会把最后一个@之前的都识别为user，包含@或者#的是非法用户名，没有办法创建这样一个用户名，那如何完成的堡垒机节点的OS认证？
2. koko代码里，是获取到user根据@或#拆分的，这个user是怎么获取的，是OS用户？进入到koko的代码里时，用户是否已经登录到堡垒机节点了，koko只是连接目标资产的？

**Comment by BaiJiangJie** [comment]
`ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`

使用这种方式，KoKo 会做 JumpServer 的用户认证，成功后，会进行资产账号的认证（就和登录到 KoKo 再连接资产的逻辑一致了），只不过 KoKo 将这两步认证合并到了一起，用户感觉是登录了一次，就直接登录到资产里面了。

**Comment by Casslie** [comment]
`ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`
用户访问KoKo（jumpserverHostIP），这一步是怎么认证的，没有依赖OS的认证？

**Comment by BaiJiangJie** [comment]
走的是原生的 SSH 协议。
