### ISSUE TITLE
[Bug] 改密计划存在密码丢失风险

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12631]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.2

**浏览器版本**
chrome

**Bug 描述**
改密计划中，使用 WinRM 修改 Windows 密码时存在密码丢失的风险

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/89765365/dce4220a-0cfb-4f70-9d3d-3c81b2d1f8b6)

改密报错问题已解决，重点不在报错，而在改密策略的逻辑设计

当前改密策略分为三步：
1、验证当前密码是否正确
2、修改系统账号密码
3、验证修改的密码是否正确
4、只有以上三步都执行成功，才会把修改的密码改到JS数据库中
目前发现的问题场景是：
当第二步修改系统账号成功，第三步验证密码错误时，导致系统账号密码被修改了而JS数据库的密码不会变更，而导致资产密码丢失

期望：
若第二步成功、第三步失败，希望再执行一次改密操作，把系统账号的密码修改回去，保障密码不被丢失

**Comment by BaiJiangJie** [comment]
这样就进到了循环中，不能真正解决问题，而且会引来其他问题。
比如：第二步成功，第三步失败，这时候修改回之前的密码（这一步如何保证能成功？）

关键问题要看为什么第三步失败了。

**Comment by BaiJiangJie** [comment]
显示 ntlm 方式的校验失败了，看看其他成功的主机是什么配置。

<img width="787" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2665df30-9fae-4e98-9799-512ae5f041d3">

**Comment by hzhfit2cloud** [comment]
> 这样就进到了循环中，不能真正解决问题，而且会引来其他问题。 比如：第二步成功，第三步失败，这时候修改回之前的密码（这一步如何保证能成功？）
> 
> 关键问题要看为什么第三步失败了。

但是现在的设计是存在账号密码丢失的问题，如果随机密码改密，密码修改成功，但是整个任务失败的话，系统中还是存的是原来的密码，这样子就导致登录不上去，要如何规避这个问题呢？

**Comment by BaiJiangJie** [comment]
核心是需要研究为什么第三步会失败。

实际上改密的密码都在数据库里存着，只不过没有保存到账号里，是放在了改密计划执行中。

**Comment by BaiJiangJie** [comment]
有稳定复现环境吗？
@hzhfit2cloud
