### ISSUE TITLE
[Bug]【控制台-用户管理-角色列表-组织角色】在列表中取消全选失败

### ISSUE THREAD

**Issue by binbin0406** [jumpserver/jumpserver#12632]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.3

**浏览器版本**
Edge版本 121.0.2277.83 (正式版本) (64 位)

**Bug 描述**
【控制台-用户管理-角色列表-组织角色】在列表中先删除任意一条数据后，点击全选框选中所有数据，再点选全选框则无法取消全选操作
**Bug 重现步骤(有截图更好)**
1.在组织角色列表中删除任意一条数据
2.点击列表全选框，选中所有数据
3.再次点击列表全选框，无法取消全选
![1706786536579](https://github.com/jumpserver/jumpserver/assets/77324661/a380ed5d-f616-4a6c-9b00-3adb10ea0329)

**Comment by BaiJiangJie** [comment]
我测试可以啊。

看看浏览器控制台有报错吗？

**Comment by BaiJiangJie** [comment]
能稳定复现后再 reopen 当前 issue。
