### ISSUE TITLE
LDAP配置登录页面，测试登录没有使用页面修改的临时值进行登录测试

### ISSUE THREAD

**Issue by ladixiu** [jumpserver/jumpserver#12648]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
jumpserver-offline-installer-v3.10.1-amd64

**浏览器版本**
chrome 121.0.6167.85

**Bug 描述**
LDAP配置登录页面，测试登录没有使用页面修改的临时值进行登录测试

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/43605070/dcd75bc2-d1cc-444e-9ea0-d9d60043c320)

**Comment by BaiJiangJie** [comment]
测试登录不会使用临时的配置，测试连接会使用临时配置。

如果要测试登录，必须提交后再操作。（为了防止管理员测试登录成功后，忘记提交导致实际登录时失败的情况）
