### ISSUE TITLE
jumpserver启用cas认证后，有时登录上去会突然退出页面，需要重新登录[Bug] 

### ISSUE THREAD

**Issue by xingyunliuyue** [jumpserver/jumpserver#12640]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

3.10.3
**浏览器版本**

chrome
**Bug 描述**
正常使用堡垒机的时候会突然出现类似的情况，或者刚登陆到jumpserver，偶发性出现账号失效的告警，需要重新登陆
![image](https://github.com/jumpserver/jumpserver/assets/65636727/cdf2e0c1-34ef-4293-8f89-9794de06106f)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
v3.10.4 版本会优化这块逻辑。

应该是你后端配置过期时间选项太短了吧？

**Comment by xingyunliuyue** [comment]
web处配置了120分钟，后端你是指哪个过期时间？

**Comment by BaiJiangJie** [comment]
配置文件中的 SESSION_COOKIE_AGE 相关的参数。

等 v3.10.4 发布后看看还会不会出现。
