### ISSUE TITLE
[Feature] 批量更新资产的账号

### ISSUE THREAD

**Issue by s5unty** [jumpserver/jumpserver#12641]
**请描述您的需求或者改进建议.**

预定义了几个账号模板，要想让资产绑定上这些账号，只能单台依次的手动处理
希望账号批处理的功能，能支持这种场景。

![0204-0944-7510](https://github.com/jumpserver/jumpserver/assets/50655/40998e6c-3360-4252-baa2-8b7790b0f687)

**Comment by BaiJiangJie** [comment]
<img width="1367" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/70d084fd-4a83-4a2c-b62a-634aa7f40981">

在这儿，可以批量给资产添加账号模版。

**Comment by s5unty** [comment]
感谢快速回复，问题完美解决~
