### ISSUE TITLE
[Feature] 深信服防火墙误报

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#12649]
**请描述您的需求或者改进建议.**
在 web 上传文件处，经常被深信服拦截误报，导致文件上传失败。查看日志等都没有消息。
在深信服防火墙上看到的拦截信息如下，应该是按照关键字匹配拦截的，建议看看是不是可以做个base64加密，在cmd的字段处。
<img width="619" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40848979/815f4f9a-f68b-4a3e-94cd-974681c1920a">

**Comment by BaiJiangJie** [comment]
你设置一下规则，放过呢？

**Comment by wxcen** [comment]
设置规则是肯定可以的，提这个建议是觉得产品处可以做下完善，不要让有这种误报不。避免误报和排查，使用体验更好。毕竟深信服那边我们也不能改变什么。

**Comment by BaiJiangJie** [comment]
嗯，其实问题不大。两种方式一种 get 请求，一种 post 请求。

@LeeEirc 研究一下能不能改成 post 的方式。

**Comment by wxcen** [comment]
嗯嗯，可以看看怎么避免，不止一个地方遇到了。

**Comment by LeeEirc** [comment]
能否加微信群，联系一下我们，给帮忙测试验证下 `post` 方式能否解决误报的问题？
