### ISSUE TITLE
web终端不显示资产

### ISSUE THREAD

**Issue by alenas520** [jumpserver/jumpserver#1264]
[简述你的问题]
web终端不显示资产
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
ssh端可以显示服务器列表，连接服务器
web端不显示设备
报错信息：
[base WARNING] Not Found: /api/perms/v1/user/my/asset-groups-assets/
##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
能否提供您的nginx配置，应该是您的nginx配置出错了

**Comment by alenas520** [comment]
luna更新到1.0了，nginx配置跟官方文档一样，
以下是nginx报错：
2018/05/02 10:25:03 [error] 82426#82426: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.47.1, server: , request: "GET /api/perms/v1/user/my/asset-groups-assets/ HTTP/1.1", upstream: "http://[::1]:8080/api/perms/v1/user/my/asset-groups-assets/", host: "192.168.47.150", referrer: "http://192.168.47.150/luna/"
2018/05/02 10:25:03 [warn] 82426#82426: *34 upstream server temporarily disabled while connecting to upstream, client: 192.168.47.1, server: , request: "GET /api/perms/v1/user/my/asset-groups-assets/ HTTP/1.1", upstream: "http://[::1]:8080/api/perms/v1/user/my/asset-groups-assets/", host: "192.168.47.150", referrer: "http://192.168.47.150/luna/"

**Comment by liuzheng** [comment]
@alenas520 请贴一下你的nginx配置，以及Jumpserver的ip和端口
