### ISSUE TITLE
[Feature] 希望可以共享作业

### ISSUE THREAD

**Issue by myselfghost** [jumpserver/jumpserver#12659]
作业，团队协作的时候，很多时候是需要：
1、一人创建多人可执行；
2、一人创建多人可读，可更新，可执行；
3、一人创建多人可读（作业详情以及作业执行记录，日志等）；
希望增加这个特性。

**Comment by BaiJiangJie** [comment]
目前 v3 版本没有计划，将来 v4 会考虑。
