### ISSUE TITLE
[Bug] Google Chrome和Microsoft Edge假死

### ISSUE THREAD

**Issue by WeiYingZhe** [jumpserver/jumpserver#12658]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
Windows 11专业版
Google Chrome版本 121.0.6167.185（正式版本） （64 位）
Microsoft Edge版本 121.0.2277.128 (正式版本) (64 位)

**Bug 描述**
使用以上两种浏览器，唤醒睡眠状态下在Web终端页面下按下任意键盘键位会导致浏览器假死状态。

**Bug 重现步骤(有截图更好)**
为了更好的复现，以下操作均在远程设备（RDP）上操作
1.登录并打开“Web终端”页面，链接任意资产。
2.关闭远程会话（RDP）。
3.重新该设备的远程会话（RDP）。
4.在“Web终端”页面按下任意键盘键位，整个浏览器进入假死状态。

切到其他应用再切回浏览器就能暂时恢复，此后在“Web终端”按下任意键盘键位都会触发，甚至有时候会导致浏览器地址栏无法输入或百度搜索栏无法输入。

麻烦大佬们帮忙看看是什么问题，看看有没有解决方案！

**Comment by BaiJiangJie** [comment]
可以录制一个视频看一下吗？
@WeiYingZhe

**Comment by WeiYingZhe** [comment]
> 可以录制一个视频看一下吗？ @WeiYingZhe

可以，不过视频超过GitHub上传的大小，请问有其他的方式吗？

**Comment by BaiJiangJie** [comment]
做成 GIF 动图。

**Comment by WeiYingZhe** [comment]
![Uploading QQ图片20240219143957.gif…]()

**Comment by WeiYingZhe** [comment]
![QQ图片20240219143957](https://github.com/jumpserver/jumpserver/assets/98902853/2afe2785-bcf6-446c-ae35-513f69ab50d6)

**Comment by BaiJiangJie** [comment]
动图有点小，看不太清。

试试邮件可以发送吗？jiangjie.bai#fit2cloud.com

**Comment by BaiJiangJie** [comment]
邮件收到了，不通过 RDP 会话能复现吗？

**Comment by WeiYingZhe** [comment]
进入睡眠模式100%可触发，RDP可以快速令设备进入睡眠模式。

**Comment by BaiJiangJie** [comment]
本地电脑，直接进入睡眠模式呢？

**Comment by BaiJiangJie** [comment]
这种情况下，不连 JumpServer，使用浏览器按打开别的网站，是不是也会有卡死的情况？

**Comment by WeiYingZhe** [comment]
我试了一下华为防火墙较新软件版本的Web CLI也会出现这种情况。用Firefox不会有这种问题，难道是浏览器内核的问题吗

**Comment by BaiJiangJie** [comment]
有可能，应该不是产品的问题。

**Comment by WeiYingZhe** [comment]
好吧，感谢！
