### ISSUE TITLE
不懂就问，数据库用utf8编码而不是utf8mb4是有什么优点吗？

### ISSUE THREAD

**Issue by mattholy** [jumpserver/jumpserver#12654]

**Comment by BaiJiangJie** [comment]
UTF-8（Unicode Transformation Format - 8-bit）和 UTF-8mb4 是两种字符编码，它们之间有一些区别，主要涉及到它们对于字符集的支持范围。

UTF-8:

`UTF-8 是 Unicode 编码的一种变体，它使用1至4个字节表示一个字符。
最初设计用于兼容ASCII字符集，因此它对ASCII字符使用单个字节表示，而对其他字符使用多个字节。
UTF-8 支持的最大Unicode代码点是 U+10FFFF。`

UTF-8mb4:
`UTF-8mb4 也是一种 Unicode 编码，但相对于UTF-8，它支持更广泛的字符集。
UTF-8mb4 最初是为了支持 MySQL 数据库而引入的，用于存储四字节的Unicode字符，如 emoji 表情。
UTF-8mb4 使用1至4个字节表示一个字符，可以表示 UTF-8 所能表示的所有字符，同时还能支持一些额外的字符。`

主要的区别在于 UTF-8mb4 能够处理一些辅助平面字符（Supplementary Planes），如 emoji 表情，而 UTF-8 不支持。如果你的应用需要处理这些特殊字符，那么选择 UTF-8mb4 是更为合适的选择，特别是在数据库设计中，确保存储和处理这些字符时不会出现问题。

---

UTF-8 相对于 UTF-8mb4 有一些优势，主要是在存储空间和一些特定应用场景上：

1. 存储空间：

UTF-8 使用的存储空间相对较小，因为它只使用1至4个字节，而不考虑辅助平面字符。
在存储大量文本数据时，UTF-8 可能占用的存储空间较少，因为大部分文本字符都属于基本多文本平面（BMP），只需要1至3个字节表示。

2. 兼容性：

由于 UTF-8 是 Unicode 的标准编码之一，它在许多环境中得到广泛支持。
一些旧的系统或应用程序可能不支持或不完全支持 UTF-8mb4，而 UTF-8 可能更容易在这些情况下进行集成。

3. 一般应用场景：

对于大多数应用，特别是在处理文本数据的场景下，使用 UTF-8 是合适的，因为它涵盖了绝大部分的字符集，而且更为轻量。
然而，需要注意的是，如果你的应用需要处理一些特殊字符，例如 emoji 表情，或者需要支持一些辅助平面字符，那么选择 UTF-8mb4 是更为合适的，因为它可以覆盖 UTF-8 的字符集，并确保不会丢失或损坏这些特殊字符。在数据库设计中，尤其是对于支持多语言和特殊字符的应用，选择 UTF-8mb4 是更为推荐的做法。

---
简单理解，更节省空间。
