### ISSUE TITLE
[Bug] 资产树节点右键操作时，有的节点无法正常显示“节点重命名”选项卡

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#12655]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
版本 121.0.6167.139（正式版本） (arm64)

**Bug 描述**
资产树节点右键操作时，有的节点无法正常显示“节点重命名”选项卡

**Bug 重现步骤(有截图更好)**
1.
<img width="1451" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/adef0083-8687-42e3-9dcb-d0fe99b099ab">

2.
<img width="1475" alt="image" src="https://github.com/jumpserver/jumpserver/assets/45967454/0a81ceb0-cd84-48ff-8beb-e7ad963995aa">

**Comment by BaiJiangJie** [comment]
这应该是坐标太高了，好复现吗？

**Comment by BaiJiangJie** [comment]
能稳定复现吗？
@huskiesir

**Comment by huskiesir** [comment]
> 能稳定复现吗？ @huskiesir

可以稳定复现！

**Comment by BaiJiangJie** [comment]
怎么复现一下？

**Comment by BaiJiangJie** [comment]
@huskiesir 

你打开浏览器控制台了吗？
