### ISSUE TITLE
[Feature] 数据库连接支持一下Postgres

### ISSUE THREAD

**Issue by bollowang** [jumpserver/jumpserver#12653]
**请描述您的需求或者改进建议.**

目前的数据库只支持了Mysql和Mariadb，能不能支持一下Postgres连接

<img width="707" alt="image" src="https://github.com/jumpserver/jumpserver/assets/22709567/09e05ed1-bfd2-4831-a9d0-d93915e4a699">
<img width="1019" alt="image" src="https://github.com/jumpserver/jumpserver/assets/22709567/74b49251-33e2-48e0-aec3-3f952be94f8f">

**Comment by BaiJiangJie** [comment]
<img width="2100" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/3fafab50-183c-4514-942f-4459b493031b">

最新版本支持。

**Comment by BaiJiangJie** [comment]
PostgreSQL 是企业版功能。

![image](https://github.com/jumpserver/jumpserver/assets/32935519/0d7761d8-313d-44a8-b39a-92be8b763099)

**Comment by BaiJiangJie** [comment]
如果平时使用的 PostgreSQL 数量大的话，建议考虑一下企业版。
