### ISSUE TITLE
[Bug] centeros7.9连接VNC连接不上

### ISSUE THREAD

**Issue by phphappy** [jumpserver/jumpserver#12657]
**JumpServer 版本：3.10.3

**Bug 描述**
主机版本是centeros7.9,jumpserver版本：v3.10.3,使用guacamole1.5.1独立部署vnc可以连接上，使用jumpserver的vnc连接不上

是不是协议版本的问题？guacamole1.5.1 的日志里面显示的是protocol version "VERSION_1_5_0"
guacd[2899]: DEBUG: Client is using protocol version "VERSION_1_3_0"
guacd[2899]: INFO: Connect failed. Waiting 1000ms before retrying...
guacd[2899]: INFO: Connect failed. Waiting 1000ms before retrying...
guacd[2899]: INFO: Connect failed. Waiting 1000ms before retrying...
guacd[2899]: ERROR: Unable to connect to VNC server.
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
有可能，如果原生 Guacamole 可以连接，JumpServer 应该也能成功才对。

**Comment by LeeEirc** [comment]
centos 7.9 使用的那个 VNC Server？VNC Server 的配置是什么？

**Comment by LeeEirc** [comment]
参考 #12824
