### ISSUE TITLE
[Bug] 3.10.3 单机安装后连接不了外部mysql

### ISSUE THREAD

**Issue by linguohu** [jumpserver/jumpserver#12663]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.3

**浏览器版本**
谷歌121.0.6167.161

**Bug 描述**
新版本安装启动所有服务后，连接不了外部数据库。关闭服务后，可以连接

**Bug 重现步骤(有截图更好)**
1.启动所有服务，等1分钟，telnet 外部数据库 3306端口 不通
![image](https://github.com/jumpserver/jumpserver/assets/12726197/3611907a-ff7e-47d9-86af-9473ef908895)
同时jumpserver/core/data/logs/jumpserver.log日志报连不了数据库
![image](https://github.com/jumpserver/jumpserver/assets/12726197/c20e12a9-b7ea-4d02-9a4d-66e30e0da89d)

2.关闭所有服务器，等1分钟左右，telnet 外部数据库 3306端口 可以通
![image](https://github.com/jumpserver/jumpserver/assets/12726197/edf3cdc5-cbba-40ee-8c3d-9b5c3b356589)

3.

**Comment by BaiJiangJie** [comment]
这应该是网络问题吧，所有服务都不启动，能连接外部数据库吗？使用 mysql 命令。

**Comment by linguohu** [comment]
> 这应该是网络问题吧，所有服务都不启动，能连接外部数据库吗？使用 mysql 命令。

不启动服务可以的，安装时数据库都可以初始化写入表成功。一启动服务就连不了

**Comment by BaiJiangJie** [comment]
看看数据库端的日志报什么错？
