### ISSUE TITLE
[Feature] 远程发布机是否可以新增剪切板与上传下载的控制

### ISSUE THREAD

**Issue by asdfgasysfy** [jumpserver/jumpserver#12668]
**请描述您的需求或者改进建议.**
远程发布机为控制远程应用的主机. 但某些场景. 不希望用户能够进行复制出. 或者下载等功能.  能不能做成跟资产授权里面那种控制复制和下载的方式

**Comment by BaiJiangJie** [comment]
资产授权中的动作就是用来控制的。
