### ISSUE TITLE
[Question] External storage for session recording

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#12666]
Hi,

- In document, I see can set up external storage for session recording include SFTP. But on web GUI, I only see method to connect with cloud storage like: S3, Ceph, Swift, OSS, Azure, OBS, COS
![image](https://github.com/jumpserver/jumpserver/assets/75791054/cbf22018-2ded-42bc-8a5a-c33121a71152)

- I using JumpServer Community Edition

Method SFTP is only have on version license? How anyway for me to set up external storage on another server (not cloud)?

**Comment by BaiJiangJie** [comment]
Currently, SFTP storage only supports account backup and does not support session recording storage.

**Comment by BaiJiangJie** [comment]
Yes.
