### ISSUE TITLE
[Bug] MySQL Web Cli 中断 sql 执行未记录 SQL 命令

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12676]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
Chrome 最新版

**Bug 描述**
使用 web cli 连接 MySQL 资产，执行 sql 等待返回时中断 sql，审计台命令记录未记录该 SQL 

**Bug 重现步骤(有截图更好)**
1. 通过 Web Cli 连接 MySQL 资产
2.执行 select sleep(60);
![image](https://github.com/jumpserver/jumpserver/assets/95400700/ce4bdda4-5590-4d15-9dcb-307a95fb1f7c)

按几个回车，输入一些字符后 Ctrl+C 中断会话

3.审计台查看命令记录，执行的 SQL 未被记录到
![image](https://github.com/jumpserver/jumpserver/assets/95400700/841b2eee-7da1-483f-9954-609209ea2abc)

**Comment by BaiJiangJie** [comment]
select sleep(60);

是上下键输入的还是手动输入的？

**Comment by gerry-fit** [comment]
Ctrl V 粘贴上去的，试了下上下键输入的也会丢

**Comment by BaiJiangJie** [comment]
手动输入的呢？

**Comment by BaiJiangJie** [comment]
数据库连接的上下键盘、复制粘贴是解析不到。

**Comment by gerry-fit** [comment]
能优化吗，目前有用户执行了影响业务的 SQL 审计不到，影响比较大

**Comment by BaiJiangJie** [comment]
先确认什么场景下会出现，必现还是偶现。

**Comment by LeeEirc** [comment]
偶现情况，先关闭。后续有新的复现方式和进展，创建新的 issue。
