### ISSUE TITLE
[Question]  jumpserver/core/data/media/FTP_FILES

### ISSUE THREAD

**Issue by dwdaiwei** [jumpserver/jumpserver#12675]
**请描述您的问题.**

jumpserver/core/data/media/FTP_FILES这个目录下的文件是不是上传成功了就可以删除掉
<img width="696" alt="image" src="https://github.com/jumpserver/jumpserver/assets/56427437/4bea5d9c-5ec7-401e-bdc4-ad760241762d">

**Comment by BaiJiangJie** [comment]
是的，最新版本默认不会留存了。

升级解决一下，或者修改一下配置项：

FTP_FILE_MAX_STORE=0
