### ISSUE TITLE
[Bug] 测试邮件无法发送

### ISSUE THREAD

**Issue by shuinoo** [jumpserver/jumpserver#12686]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v2.7.0
**浏览器版本**
chrome 121.0.6167.140

**Bug 描述**

设置-邮件测试无法发送测试邮件
**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/38451598/ae7e7cba-0975-425c-ba9e-ad6ae8791845)

**Comment by BaiJiangJie** [comment]
升级到最新版本使用。
