### ISSUE TITLE
[Question] web 终端登录后30秒自动断开连接

### ISSUE THREAD

**Issue by XXMY** [jumpserver/jumpserver#12680]
**请描述您的问题.**
**版本:** 
`v3.10.3`

**环境:** 
```
k3s version v1.26.10+k3s2 (cb5cb555)
go version go1.20.10
```

**部署方式:**
```
helm repo add jumpserver https://jumpserver.github.io/helm-charts
helm repo update
helm install jumpserver jumpserver/jumpserver -f values.yaml \
    --create-namespace \
    --namespace default\
    --kubeconfig /etc/rancher/k3s/k3s.yaml
```

**问题:**
在web终端中成功连接上服务器后，不做任何操作的时候，通过web console可以看到 websocket 连接中有间断性的发送 PING 消息，shell 连接正常，但是在shell中执行任一操作后，websocket中的 PING 消息不再发送，30秒后，自动关闭shell连接，这个是什么原因导致的

<img width="1050" alt="image" src="https://github.com/jumpserver/jumpserver/assets/8390566/885446f5-22fd-4bac-bd21-cc1fb0c399ca">

**Comment by BaiJiangJie** [comment]
系统设置配置的会话空闲超时时间是多少？

**Comment by XXMY** [comment]
> 系统设置配置的会话空闲超时时间是多少？

默认配置，30分钟

**Comment by BaiJiangJie** [comment]
自动断开的时候，看一下 koko 的日志。

**Comment by XXMY** [comment]
> 自动断开的时候，看一下 koko 的日志。

问题定位到了，是代理服务器的超时时间配置引起了，谢谢你的帮助
