### ISSUE TITLE
[Bug] 新版本响应速度变慢

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#12696]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
无关

**Bug 描述**
在使用远程SSH连接到Jumpserver后，发现刷新列表速度变慢很多，之前基本上是秒出，现在需要等3s左右，如何排查？

**Bug 重现步骤(有截图更好)**
从视频中可以看到，第一个是老版本，exit退出以后立即就可以进行操作，第二个是3.10.3版本，exit退出以后需要等几秒才能操作。

https://github.com/jumpserver/jumpserver/assets/22488813/700a1451-9c42-42de-bf63-80aa1048ef56

**Comment by BaiJiangJie** [comment]
你看细节，之前版本 `exit` 退出后是 `>ID` 页面，新版本 `exit` 退出后是上次搜索的资产页面，是新版本优化的一个功能，导致的退出后会有`3s`的延迟。

后面版本考虑一下再优化一下。

**Comment by rty813** [comment]
@BaiJiangJie 我在旧版本里面，exit退出以后立即按一下回车，也会显示上次搜索的资产页面，但是这个速度就快得多，感觉不到延迟的。可以看视频：

https://github.com/jumpserver/jumpserver/assets/22488813/c6eed999-c0e3-42e8-b723-58ca8610d171

**Comment by BaiJiangJie** [comment]
v3.10.4 计划去掉 exit 资产时的延迟操作。

**Comment by jym503558564** [comment]
v3.10.4 已发布，去掉exit 资产时的延迟操作，请升级至最新版本进行体验，

**Comment by rty813** [comment]
3.10.4操作很流畅，没有问题。感谢
