### ISSUE TITLE
[Feature] 作业管理建议添加失败重启与邮件通知功能

### ISSUE THREAD

**Issue by alan-yeh** [jumpserver/jumpserver#12695]
现有的作业管理支持定时执行作业，但是有时作业会执行失败，建议：

- 新增失败重试机制：作业管理新增失败重试次数的设置，如果作业执行失败，则根据用户的配置启动新的重试作业。
- 新增失败邮件通知机制：因为作业是每天定时执行，那么就要求运维人员每天检查作业是否执行成功。建议新增邮件或相其它（如钉钉、微信之类）的通知机制，这样就可以不需要每天检查。

**Comment by BaiJiangJie** [comment]
目前 v3 版本暂时不考虑，下一个大版本可以考虑支持一下。
