### ISSUE TITLE
[Feature] 查看过的命令记录做标记

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12694]
**请描述您的需求或者改进建议.**
![image](https://github.com/jumpserver/jumpserver/assets/44529247/6b1a4580-1385-419e-808b-682d282d3eeb)

想查看某个命令的结果，现在根据命令过滤出了多个记录，我得一个一个数着点进去查看录像，能不能把点过的自动变个颜色，我就知道这个记录已经看过了，不用再点进去

**Comment by BaiJiangJie** [comment]
可以考虑支持一下。

**Comment by fikimbing** [comment]
> 可以考虑支持一下。
看 [ryswork1993] 截图里面的命令有一些不是正常的命令输入，如第3条命令可能键入了tab或者往上、往下、往左、往右的组合，导致并不是正在最后输入的命令，这个可以通过技术解决吗？

**Comment by BaiJiangJie** [comment]
最新版本已支持。
