### ISSUE TITLE
[Bug] 应用发布机无端离线

### ISSUE THREAD

**Issue by alan-yeh** [jumpserver/jumpserver#12698]
**JumpServer 版本( 3.10.3 )**

**Bug 描述**
应用发布机不知道因为什么原因，负载状态总是隔一段时间就变成了离线状态。测试这个服务器，返回应用状态良好，但是负载状态还是离线。

修复这个状态，只通进入详情，然后重新[初始化部署]一次才行。但是过一段时间（一天左右），又会变成离线状态。

**Bug 重现步骤(有截图更好)**
![Snipaste_2024-02-23_14-22-19](https://github.com/jumpserver/jumpserver/assets/15818715/fab6e1a8-384e-4bb2-82f7-910b25bb89de)

**Comment by BaiJiangJie** [comment]
看一下发布机器上的 tinker 后台进程的日志信息，有没有报错？
@alan-yeh

**Comment by alan-yeh** [comment]
之前看到是有问题的，后面我重新初始化部署之后，发现这两天又比较正常了。等我下次出现问题时再反馈，非常感谢
