### ISSUE TITLE
sftp 2222速度太慢

### ISSUE THREAD

**Issue by gaoshan800** [jumpserver/jumpserver#1270]
局域网环境，
客户端通过sftp 2222端口上传下载比 跳过堡垒机直接sftp 22 速度慢慢3倍左右。
客户端直接到堡垒机,堡垒机到资产使用sftp 22  速度都很快。
个人感觉是2222这边有限制，

##### 使用版本
Version 1.2.0-2 GPLv2

**Comment by kaede425** [comment]
我用rz上传的时候同样很慢

**Comment by huangjingui** [comment]
rz 太慢 现在有好的解决方案吗
