### ISSUE TITLE
[Bug] 定期作业不执行

### ISSUE THREAD

**Issue by alan-yeh** [jumpserver/jumpserver#12703]
**JumpServer 版本(v3.10.3 )**

**Bug 描述**

如下图所示，我这边设置了每晚 00:30 分执行指定脚本，好像从来没有触发过。我目前定期作为有 13 条，这十几条定期作业都是在 00:00 ~ 05:00 之间执行，但是没有一条能触发成功。

我排查了一段时间，发现有时候，好像定期作业又正常运行，比如当前是 13:35 分，我将定期作为设置为 40 13 * * * 的话，到了 13:40 时，我发现似乎又能正常执行。

如果这个不是一个 BUG 的话，麻烦指导一下此功能应该怎么使用，非常感谢

**Bug 重现步骤(有截图更好)**

<img width="1151" alt="Snipaste_2024-02-25_03-10-12" src="https://github.com/jumpserver/jumpserver/assets/15818715/35d2ada5-f9a2-4b58-8fe2-c943afb808b2">

**Comment by BaiJiangJie** [comment]
根据你的描述判断，使用的方式没有问题。

目前定时任务执行，好像是存在一些偶发不执行的现象，看到有其他用户也有遇到，但是目前还没有排查出原因。

**Comment by alan-yeh** [comment]
现在的解决方案是每晚 11 点 30 分重启一下 jumpserver，现在定时任务比较稳定了🤣

**Comment by BaiJiangJie** [comment]
```
# 进入 Celery 容器
docker exec -it jms_celery bash
 
# 编辑 connection.py 文件
vi /opt/py3/lib/python3.11/site-packages/redis/connection.py
 
# 修改文件内容 def reset() 方法下的代码；并保存退出文件；
修改 `self._lock = threading.Lock()` 为 `self._lock = threading.RLock()`
:wq
 
# 退出容器
exit
 
# 临时重启 Celery 容器
docker restart jms_celery
```

临时修改试试。

参考 PR：https://github.com/redis/redis-py/pull/3000/files

**Comment by alan-yeh** [comment]
根据上面的修改，现在定时任务可以正常执行了。测试一周，全部任务都正常
