### ISSUE TITLE
[Bug] 账号收集失败

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12717]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**

**Bug 描述**
对96个资产做账号收集，但是任务没有正常结束，直接卡住了，没有任何反馈信息，没有报错，收集成功的账号也没有保存。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/9b4ce7de-1bfc-4f37-b91d-a876c8446ec8)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
升级到 v3.10 试试。
