### ISSUE TITLE
[Bug] 禁用OpenID用户后，登录会一直反复刷新页面，没有出现禁用提示

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [jumpserver/jumpserver#12718]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.2

**浏览器版本**
Edge 122.0.2365.52

**Bug 描述**
1、认证设置中禁用登录跳转提示，并启用OIDC认证，配置使用Keycloak之后，在JS上禁用A用户。
2、打开JS页面会跳转至Keycloak登录，登录A用户后，会返回JS，但是页面空白并且会一直反复刷新。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/81545871/c026270a-75a3-4ff8-b4b0-568bb5a8579c)

2.
![image](https://github.com/jumpserver/jumpserver/assets/81545871/292a18a6-770a-4193-9c78-2a52a2c3e0e3)

3.
登录禁用的用户后，页面一直反复刷新：
![image](https://github.com/jumpserver/jumpserver/assets/81545871/c96535b7-5e63-49e0-9e7d-3b41083a438a)

**Comment by BaiJiangJie** [comment]
升级到最新版本解决。
