### ISSUE TITLE
[Bug] 账号改密失败

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12715]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.9.2

**浏览器版本**

**Bug 描述**
账号改密，设置改普通账号readonly，结果把 roo t账号的密码给改掉了，但是普通账号的密码没有改。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/15103510/82b705ef-886c-4bc8-9d57-6837edd49227)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
不会吧！升级到 v3.10 试试。
