### ISSUE TITLE
[Bug] Ceph存储不生效

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#12713]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
无关

**Bug 描述**
设置了对象存储ceph，测试也通过了，并且组件管理里面给所有的终端都设置了录像存储。但实际并未生效，录像依然存在本地。

**Bug 重现步骤(有截图更好)**
1.
![9a6d4ba4e0e37ad30893954f3777e1e](https://github.com/jumpserver/jumpserver/assets/22488813/64c832b4-161d-4da4-8871-33ec9554c0d5)
2.
![c69aced7b5aba955beb8fc8cbe5489c](https://github.com/jumpserver/jumpserver/assets/22488813/cbbe827b-fcb7-4691-8b91-7cb0f15630df)
3.
![f8e6514fac780769e166260769f4bb8](https://github.com/jumpserver/jumpserver/assets/22488813/f75b38e4-dcdc-4344-9680-8c3641ea0fe4)
4. 
![image](https://github.com/jumpserver/jumpserver/assets/22488813/f15b08be-d6ba-4eaa-8518-4f910e4eec67)

**Comment by rty813** [comment]
补充一下，我这个设置是早就设置了的，2024-02-26的录像是在设置成功后产生的。

**Comment by BaiJiangJie** [comment]
<img width="1437" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/01f5d143-9acf-4215-b009-2a95bf793d00">
https://docs.jumpserver.org/zh/v3/guide/env/#1-core

**Comment by rty813** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/22488813/f22348e7-5cc0-49d1-b206-da8eb22d0ef8)
刚测试的也没有上传，ceph上面没有录像
![image](https://github.com/jumpserver/jumpserver/assets/22488813/ab9a3eae-484c-4d1c-b7dc-65e3780dc38c)
---
所以是否需要在配置文件中设置呢？

**Comment by BaiJiangJie** [comment]
创建好对象存储，给对应的组件设置上录像存储，1分钟后连接资产，会话结束后，组件会直接上传到 Ceph 存储。

组件设置的是 Koko，会话连接的是什么类型的？windows？linux？

不同会话使用的组件不同。看看是不是这个问题。

**Comment by rty813** [comment]
@BaiJiangJie 确实是按照你说的方式配置的，会话连接是Linux，但是确实没有上传至Ceph。
补充两点：
1. 对象存储我实际上使用的是Seaweedfs的s3端点，这个之前测试也没啥问题，从前面发的截图可以看到之前我有成功上传过，但是后来不知道怎么就不行了，我倾向于不是它的问题。
2. 部署方式采用的是两台服务器的部署方式，他们共用同一个mysql，但是是不同的redis。core目录也是通过NFS共享的。这个是否有影响？

**Comment by rty813** [comment]
@BaiJiangJie 我是按照这种方式配置的。会话连接是linux。我查看了jms_koko的日志，发现报错：
```
2024-02-28 14:31:32 [ERRO] S3 upload file /opt/koko/data/replays/2024-02-28/94a526f7-2972-4b41-944e-e6c32f8a3de0.cast.gz failed: AuthorizationQueryParametersError: Error parsing the X-Amz-Credential parameter; the Credential is mal-formed; expecting "<YOUR-AKID>/YYYYMMDD/REGION/SERVICE/aws4_request".
	status code: 400, request id: 1709101892790722685, host id: 
```
这个是自签发证书导致的问题吗？

**Comment by rty813** [comment]
而且我有一个老版本的v2.5.3的jumpserver，用的也是同一个ceph，就是正常的，能成功上传，配置一样：
![image](https://github.com/jumpserver/jumpserver/assets/22488813/58cc4163-8548-4df5-b316-9dd7b124a45b)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/b38817e9-b9f9-48fb-bf35-e66415c9cf73)

**Comment by BaiJiangJie** [comment]
远程看一下吗？

**Comment by BaiJiangJie** [comment]
Koko Ceph 的上传逻辑很长时间没有修改过了。

**Comment by rty813** [comment]
> 远程看一下吗？或者你也可以使用 python 的 jms_storage 库在命令行测试上传一个文件试试。

@BaiJiangJie 能具体说一下这个如何通过命令行测试吗？或者远程的话，链接地址： https://jump.orca-tech.cn:8085/koko/share/76e0f920-fa4a-4a13-bd0a-b2381b3f0a24/
验证码: 3leo
有效期一个小时

**Comment by BaiJiangJie** [comment]
koko 共享的话，需要给我一个临时用户。

**Comment by BaiJiangJie** [comment]
或者使用 toDesk 软件。
或者你研究一下代码直接调试也可以。https://github.com/jumpserver/jms-storage-sdk/blob/master/jms_storage/ceph.py#L36

**Comment by BaiJiangJie** [comment]
现在想确定，是Ceph的问题，还是代码的问题。（koko go 不行，测试一下 python 是否成功）

**Comment by rty813** [comment]
> koko 共享的话，需要给我一个 JumpServer 的临时用户。 操作命令有点复杂，不是很好描述。

能不能用我前面发的那个共享链接？可以直接登录到部署jumpserver的主机上，然后你可以通过docker命令进入

**Comment by rty813** [comment]
@BaiJiangJie 我刚看了一下jms-storage-sdk代码，他的CEPHStorage类中is_secure写死的是False，但是我这个链接是HTTPS的，所以直接用这个类是不行的。但是我通过boto手动链接了一下是能连接上去的：
![image](https://github.com/jumpserver/jumpserver/assets/22488813/259375b2-5a2e-4ebd-9ef3-44b655224884)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/c6b25081-9d87-43df-af49-67ce7cf80d83)

**Comment by rty813** [comment]
@BaiJiangJie 我用jms_storage的S3Storage成功上传了一个文件：
![image](https://github.com/jumpserver/jumpserver/assets/22488813/82e11f3c-2cd4-41c6-acba-edae3154864d)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/ebd7b37c-e95d-483f-b992-7105673e1888)

**Comment by BaiJiangJie** [comment]
那就说明 Ceph 服务和 Python 没问题，用 Go 的代码再测试一下。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/koko/blob/dev/pkg/proxy/recorderstorage/s3.go

**Comment by rty813** [comment]
@BaiJiangJie 上传成功
![image](https://github.com/jumpserver/jumpserver/assets/22488813/a1537bb8-fce7-4952-b694-edae91db7b52)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/2406e03d-252e-4c4e-9383-c43439976929)
代码如下：
```go
package main

import (
        "os"
        "fmt"

        "github.com/aws/aws-sdk-go/aws"
        "github.com/aws/aws-sdk-go/aws/credentials"
        "github.com/aws/aws-sdk-go/aws/session"
        "github.com/aws/aws-sdk-go/service/s3/s3manager"
)


type S3ReplayStorage struct {
        Bucket    string
        Region    string
        AccessKey string
        SecretKey string
        Endpoint  string
}

func (s S3ReplayStorage) Upload(gZipFilePath, target string) (err error) {

        file, err := os.Open(gZipFilePath)
        if err != nil {
                fmt.Printf("Open %s file failed: %s", gZipFilePath, err)
                return err
        }
        defer file.Close()
        s3Config := &aws.Config{
                Credentials:      credentials.NewStaticCredentials(s.AccessKey, s.SecretKey, ""),
                Endpoint:         aws.String(s.Endpoint),
                Region:           aws.String(s.Region),
                S3ForcePathStyle: aws.Bool(true),
        }

        sess, err := session.NewSession(s3Config)
        if err != nil {
                fmt.Printf("S3 new session failed: %s", err)
                return err
        }

        uploader := s3manager.NewUploader(sess, func(u *s3manager.Uploader) {
                u.PartSize = 64 * 1024 * 1024 // 64MB per part
        })
        _, err = uploader.Upload(&s3manager.UploadInput{
                Bucket: aws.String(s.Bucket),
                Key:    aws.String(target),
                Body:   file,
        })
        if err != nil {
                fmt.Printf("S3 upload file %s failed: %s", gZipFilePath, err)
                return err
        }

        return
}

//func (s S3ReplayStorage) TypeName() string {
//      return "s3"
//}

func main() {
        storage := S3ReplayStorage{
                Bucket:    "jumpserver",
                Region:    "china",
                AccessKey: "xxxxxxxxxxxx",
                SecretKey: "xxxxxxxxxxx",
                Endpoint:  "https://xxxxxxxxxxxx:9000",
        }
        // 指定本地文件路径和目标S3路径
        localFilePath := "/home/orca/list2.txt"
        targetS3Path := "jumpserver/test"

        // 调用Upload方法上传文件
        err := storage.Upload(localFilePath, targetS3Path)
        if err != nil {
                fmt.Printf("Failed to upload file: %s", err)
        }

        fmt.Println("File uploaded successfully.")
}
```

**Comment by BaiJiangJie** [comment]
那上传逻辑就没问题。

**Comment by BaiJiangJie** [comment]
```
docker exec -it jms_core bash

cd apps/

python manage.py shell

from terminal.models import *

t = Terminal.objects.get(type='koko')

print(t.config)

```

看一下 Koko 获取存储信息的 AK/SK 对吗？

**Comment by rty813** [comment]
报错：
```
In [1]: 
   ...: from terminal.models import *
   ...: 
   ...: t = Terminal.objects.get(type='koko')
   ...: 
   ...: print(t.config)
   ...: 
---------------------------------------------------------------------------
MultipleObjectsReturned                   Traceback (most recent call last)
Cell In[1], line 3
      1 from terminal.models import *
----> 3 t = Terminal.objects.get(type='koko')
      5 print(t.config)

File /opt/py3/lib/python3.11/site-packages/django/db/models/manager.py:85, in BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method(self, *args, **kwargs)
     84 def manager_method(self, *args, **kwargs):
---> 85     return getattr(self.get_queryset(), name)(*args, **kwargs)

File /opt/py3/lib/python3.11/site-packages/django/db/models/query.py:653, in QuerySet.get(self, *args, **kwargs)
    649 if not num:
    650     raise self.model.DoesNotExist(
    651         "%s matching query does not exist." % self.model._meta.object_name
    652     )
--> 653 raise self.model.MultipleObjectsReturned(
    654     "get() returned more than one %s -- it returned %s!"
    655     % (
    656         self.model._meta.object_name,
    657         num if not limit or num < limit else "more than %s" % (limit - 1),
    658     )
    659 )

MultipleObjectsReturned: get() returned more than one Terminal -- it returned 3!
```

**Comment by BaiJiangJie** [comment]
`t = Terminal.objects.get(name='你设置了存储的 koko 组件的名称')`

改一下这一步。

**Comment by rty813** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/22488813/62964892-f20b-4044-9541-b4e02bad3355)
从图上看感觉配置没有问题

**Comment by BaiJiangJie** [comment]
AK/SK 信息都对吗？

**Comment by BaiJiangJie** [comment]
> 那就说明 Ceph 服务和 Python 没问题，用 Go 的代码再测试一下。

对了，执行这个的时候，在 jms_koko 容器里运行。

**Comment by rty813** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/22488813/8e18d428-0c87-4ca8-9a4c-61e42a64c8a6)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/6a0eaf69-453a-4d46-b917-17b998eef268)

@BaiJiangJie  在jms_koko中成功执行，也成功上传了，我确认AK/SK是对的，因为我在网页上如果填入一个错误的SK，点击测试的时候会报错。

**Comment by BaiJiangJie** [comment]
你在 jms_koko 容器中执行脚本的时候，aws-sdk-go 依赖是这个版本吗？

`github.com/aws/aws-sdk-go v1.44.306`

**Comment by rty813** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/22488813/f6dee601-d459-4589-af3d-e1bd74f420fd)
这是我在容器外执行的截图。然后我通过`go build .`命令编译后，拷贝到jms_koko内执行也没有报错

**Comment by rty813** [comment]
@BaiJiangJie 
链接地址： https://jump.orca-tech.cn:8085/koko/share/4b0c158a-dcce-4834-875e-83be20ddf19e/
验证码: eRCe

有效期一个小时

**Comment by BaiJiangJie** [comment]
JumpServer 共享首先需要是 JumpServer 的用户。只有链接不行。

**Comment by rty813** [comment]
@BaiJiangJie 
豆腐邀请您进行远程控制
ToDesk设备代码:203 899 708
临时密码:g7n3pv1y
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=trCuhdDExeZaTmTWxCOUn

**Comment by BaiJiangJie** [comment]
问题已知晓，ENDPOINT 中 region 获取有问题，v3.10.5 版本修复上线。

**Comment by rty813** [comment]
更新v3.10.5版本后正常
