### ISSUE TITLE
[Question] 新节点 http请求耗时太长 有20多秒

### ISSUE THREAD

**Issue by rainsunset** [jumpserver/jumpserver#12726]
**请描述您的问题.**
问题详情及日志已提交到社区 
地址： https://bbs.fit2cloud.com/t/topic/3510

**Comment by BaiJiangJie** [comment]
docker ps 查看所有容器状态都正常吗？

**Comment by BaiJiangJie** [comment]
`websockets.exceptions.ConnectionClosedError: no close frame received or sent`

gunicorn 日志为什么会一直显示这个报错呢？

**Comment by BaiJiangJie** [comment]
curl 一下 `/api/health/` API，看看 mysql 和 redis 的建立连接速度。

**Comment by rainsunset** [comment]
cbh-node3 的 api/health 报文如下 
![image](https://github.com/jumpserver/jumpserver/assets/26954709/09446636-fc73-43ed-881b-f88abe163e92)

容器状态正常  系统资源占用正常
![image](https://github.com/jumpserver/jumpserver/assets/26954709/d649b8dd-09f7-42ce-a59b-1f1d3c95afa2)


@BaiJiangJie

**Comment by BaiJiangJie** [comment]
那说明状态都没问题，这个 health API 响应快吗？

**Comment by BaiJiangJie** [comment]
那就是有问题，你从网络方面找找原因。正常应该和 node2 一样，ms 级返回。

不然你就换一台其他云的服务器，验证一下。
