### ISSUE TITLE
[Feature] 日志审计中的操作日志支持中文显示

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12725]
**请描述您的需求或者改进建议.**
日志审计中的操作日志后续是否会支持中文显示。
![image](https://github.com/jumpserver/jumpserver/assets/43403764/7528f343-7f7e-4969-9cd1-310b0a993745)

**Comment by BaiJiangJie** [comment]
可以的。

**Comment by jym503558564** [comment]
3.10.8已修复，支持操作日志中文显示。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/b950c7aa-4955-46c3-8dc6-72a1a9facb14)
