### ISSUE TITLE
[Bug] 资产添加授权后，过了半分钟左右才能在web端看到资产

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12721]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.3

**浏览器版本**

**Bug 描述**
资产添加授权后，过了半分钟左右才能在web端看到资产。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
多少资产？
