### ISSUE TITLE
账号改密-密码生成规则可以指定大小写特殊字符数量

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12733]
**请描述您的需求或者改进建议.**
由于资产有密码复杂度要求，资产改密密码生成策略为随机生成，不能满足需求，导致改密任务失败，希望可以指定密码生成规则大小写字母和特殊字符不少于2个字符
![WechatIMG646](https://github.com/jumpserver/jumpserver/assets/38065018/43867436-e7d4-4d08-b945-9732af5f8ebd)

**Comment by BaiJiangJie** [comment]
大、小写字母和特殊字符，分别不小于2个？还是总共？

**Comment by yuanxixue** [comment]
分别不少于两个

**Comment by BaiJiangJie** [comment]
暂时不考虑。
