### ISSUE TITLE
[Bug] mysql Web GUI横向滑块无法拖动

### ISSUE THREAD

**Issue by b-ing** [jumpserver/jumpserver#12730]
**JumpServer版本**
v3.10.0

**浏览器版本**
Chrome
版本 122.0.6261.94（正式版本） （64 位）

**Bug 描述**
使用mysql Web GUI连接 数据库当sql太长时，底部滑块无法选择和拖动。
https://github.com/jumpserver/jumpserver/assets/33180711/32a5b25f-03c6-4acf-b646-664c74355cf0

**Comment by jym503558564** [comment]
待修复。

**Comment by jym503558564** [comment]
可使用触摸板左右滑动，现鼠标拖动暂时还未支持。待优化
