### ISSUE TITLE
[Bug] 登陆页面的【1 天内自动登录】选项无法勾选。

### ISSUE THREAD

**Issue by KeitaroDPVF** [jumpserver/jumpserver#12742]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.4 LTS

**浏览器版本**
Firefox 123.0 64 位
Chrome 122.0.6261.95  64 位
Edge 122.0.2365.59 64 位

**Bug 描述**
登陆界面的【1 天内自动登录】选项无法勾选。

**Bug 重现步骤(有截图更好)**
打开登陆界面即可再现。

![00111](https://github.com/jumpserver/jumpserver/assets/127463192/48dfb7d4-53c9-4752-b6a6-7b28cfc8496e)

**Comment by topsage** [comment]
![802bb2d204fdd74efc170d1b25a3d67](https://github.com/jumpserver/jumpserver/assets/51810073/f3ad944d-ec88-4590-8074-97c70f35e093)

代码中，选项 disabled要去掉

**Comment by feng626** [comment]
配置文件 SESSION_EXPIRE_AT_BROWSER_CLOSE 改为False

**Comment by BaiJiangJie** [comment]
配置文件的看一下这两个参数：

SESSION_EXPIRE_AT_BROWSER_CLOSE=False

SESSION_COOKIE_AGE>86400

同时满足。

**Comment by KeitaroDPVF** [comment]
可用，已起效。

> 配置文件的看一下这两个参数：
> 
> SESSION_EXPIRE_AT_BROWSER_CLOSE=False
> 
> SESSION_COOKIE_AGE>86400
> 
> 同时满足。
