### ISSUE TITLE
[Feature] 建议针对Windows的资产，在浏览器中打开时可以设置默认隐藏左侧和顶部的菜单栏以扩大操作面积，或支持一键网页内最大化

### ISSUE THREAD

**Issue by wqinf** [jumpserver/jumpserver#12741]
目前针对针对Windows的资产，在浏览器中打开时，默认左侧和顶部都会占据一定的空间，如下图：
![image](https://github.com/jumpserver/jumpserver/assets/48460483/fc7e4768-db9a-4562-8ac4-159f87b1ad05)
这样的话页面可操作空间就少了很多，在部分软件的弹窗下面的操作按钮有可能还显示不全，建议可以设置默认隐藏左侧（目前只能部分折叠）和顶部的菜单栏以扩大操作面积，或支持一键网页内最大化（非F11的效果，因为任务栏遮住了就没办法看微信或其他软件的消息了）。

请考虑优化，谢谢。

**Comment by BaiJiangJie** [comment]
<img width="439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/66980b38-1b74-4f1e-9169-dda808df947a">

右击-新窗口打开。

**Comment by wqinf** [comment]
> 右击-新窗口打开。
> 
> <img alt="image" width="731" src="https://private-user-images.githubusercontent.com/32935519/309210921-40f6ca86-e09b-4b38-80bd-c9b304ed83ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODU0MTIsIm5iZiI6MTcwOTI4NTExMiwicGF0aCI6Ii8zMjkzNTUxOS8zMDkyMTA5MjEtNDBmNmNhODYtZTA5Yi00YjM4LTgwYmQtYzliMzA0ZWQ4M2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MjUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZTZjZDI1ZjAwY2E4NTdmYTQ0ODAwZTg3NThiMGEyMDhkNDkzMTdkMzVmZGEyZmMxOGQ1NTFmNTNiN2U1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_1igzZEncVYhkGRx9qvuNwyj7ZLsouu-JJypbz_nKw">

哇塞，这个效果基本可以了，不过要多操作一步，有什么办法可以一步就直接打开这种效果吗？谢谢

**Comment by BaiJiangJie** [comment]
目前不支持设置默认方式，将来可以考虑。

<img width="1478" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/023321e2-caeb-4fe8-b51a-16e38a545256">

**Comment by wqinf** [comment]
> 目前不支持设置默认方式，将来可以考虑。
> 
> <img alt="image" width="1478" src="https://private-user-images.githubusercontent.com/32935519/309213300-023321e2-caeb-4fe8-b51a-16e38a545256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODU5ODMsIm5iZiI6MTcwOTI4NTY4MywicGF0aCI6Ii8zMjkzNTUxOS8zMDkyMTMzMDAtMDIzMzIxZTItY2FlYi00ZmU4LWI1MWEtMTZlMzhhNTQ1MjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA5MzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMWY0YmYyZTViODM4NmI4ODE0MDRlM2ZkNmY0YjRhNDE3NzNhOWVmY2M1YzllYzYzOGQzMjhmYmEzNTAxOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.foT4Rv9wVDMHn233YJxGeqPfxCR1iMBSwm9iu66SSZ4">

期待早日上线，谢谢。

**Comment by jym503558564** [comment]
3.10.8已支持，资产连接默认打开方式：当前窗口和新窗口，两种模式。请升级进行体验。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/11d80625-a107-4ed2-bc65-8bff585ce8c5)

**Comment by wqinf** [comment]
> 3.10.8已支持，资产连接默认打开方式：当前窗口和新窗口，两种模式。请升级进行体验。 ![image](https://private-user-images.githubusercontent.com/40739051/323812959-11d80625-a107-4ed2-bc65-8bff585ce8c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDM0NTksIm5iZiI6MTcxMzUwMzE1OSwicGF0aCI6Ii80MDczOTA1MS8zMjM4MTI5NTktMTFkODA2MjUtYTEwNy00ZWQyLWJjNjUtOGJmZjU4NWNlOGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA1MDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ODBkMDA3NDAzZGFjMGYyNDI0NDViYWE1NGE5ZmM5NjFhYTBiMmMyNDI0YzljZDIzMWQ1ODA1MGI3NmM0ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.55HR7SfQC_jbTwkL_LBtwxe1dKifWsc1I5ERs_CXmno)

已升级至v3.10.8，不过并没有看到这个设置的入口，请问是因为是社区版的缘故吗？
