### ISSUE TITLE
[Bug] 账号收集无法通过任务ID过滤任务

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12750]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
版本 122.0.6261.69（正式版本） (x86_64)

**Bug 描述**
账号收集无法通过任务ID过滤任务。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/24abe020-32b6-4862-b483-b2eea72528dc)

**Bug 重现步骤(有截图更好)**
从执行次数这里进入，查看任务。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/56a62a2e-7c90-4465-84dc-228d826dc0db)

1.
2.
3.

**Comment by BaiJiangJie** [comment]
是的，目前有 bug，v3.10.5 会修复。

**Comment by BaiJiangJie** [comment]
v3.10.5 还有问题，v3.10.6 继续优化。

**Comment by jym503558564** [comment]
3.10.8已修复，收集账号任务，支持ID过滤搜素。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/4a2f935d-a4d3-4c2d-86aa-38c044277073)
