### ISSUE TITLE
[Bug] ldap拉取用户失败

### ISSUE THREAD

**Issue by ChenXiangxxxxx** [jumpserver/jumpserver#12751]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
google最新版

**Bug 描述**
页面设置LDAP认证，填入ldap地址，DN，用户OU，过滤器，用户属性映射等信息后，点击测试连接，偶尔会成功，但是大部分时候会报错：
错误 (不合法的用户OU或用户过滤器): 不合法的用户OU或用户过滤器: ou=xxx研发组,ou=xx研发部,ou=xx研发部,ou=产品开发与工程平台（产品研发体系）,ou=xxx,ou=xxx,dc=xxx,dc=com

可以确认的是，我的ldap信息填的是正确的。因为别的系统也在用，并且jumpserver偶尔能拉取到用户。

**Bug 重现步骤(有截图更好)**
1.admin用户登录
2.点击系统设置-认证设置
3.填写ldap相关信息，点击测试连接，会报错，报错信息如上。

**Comment by BaiJiangJie** [comment]
看着应该还是 ou 的问题，配置的是一个 ou 还是多个 ou？（多个 ou 的话中间要用 `|`分割，每一个 ou 都应该是完整的）

**Comment by ChenXiangxxxxx** [comment]
> 看着应该还是 ou 的问题，配置的是一个 ou 还是多个 ou？（多个 ou 的话中间要用 `|`分割，每一个 ou 都应该是完整的）

配置的两个OU，用的 | 分割的

**Comment by w940853815** [comment]
OU名称配置问题，已解决
