### ISSUE TITLE
[Bug] 权限管理-资产登录；设置规则禁止某用户使用root账号登录资产；用户手动登录数据root账号密码依然可以登录

### ISSUE THREAD

**Issue by 2023fan** [jumpserver/jumpserver#12755]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.3

**浏览器版本**
谷歌最新版

**Bug 描述**
权限管理-资产登录；设置规则禁止某用户使用root账号登录资产；用户手动登录数据root账号密码依然可以登录

**Bug 重现步骤(有截图更好)**
1.权限管理-资产登录-设置规则
![image](https://github.com/jumpserver/jumpserver/assets/145900305/b7d2728e-06c7-4ddb-a74f-5f29b7f82377)
![image](https://github.com/jumpserver/jumpserver/assets/145900305/e56205a1-2215-41c7-b724-eaeb63218b13)

2.登录资产，选择手动输入账号密码
![image](https://github.com/jumpserver/jumpserver/assets/145900305/5c9e60fc-bb39-4227-9928-d0e22332a764)

**Comment by jym503558564** [comment]
3.10.8已修复，请升级进行体验。
