### ISSUE TITLE
[Bug] 会话安全-连接最大空闲时间设置对Web SFTP连接无效

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [jumpserver/jumpserver#12759]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.7.2

**浏览器版本**
Edge 122.0.2365.66

**Bug 描述**
在系统设置-安全设置-会话安全中设置了连接最大空闲时间30分钟以及会话连接最大时间24小时后，
使用Web SFTP连接，空闲超过24小时也不会断开。

**Bug 重现步骤(有截图更好)**
1.
![Snipaste_2024-03-06_09-32-26](https://github.com/jumpserver/jumpserver/assets/81545871/74e29f65-58ff-46e6-bdad-907e089dcc11)

2.
![Snipaste_2024-03-06_09-32-44](https://github.com/jumpserver/jumpserver/assets/81545871/83f4b1af-1493-4719-975b-7b80b621530e)

**Comment by BaiJiangJie** [comment]
SFTP 会话不受这两个参数影响，因为文件的上传下载相对是比较慢的。

**Comment by fit2cloud-mahaoyu** [comment]
那SFTP 会话目前是没有超时时间的吗？

**Comment by BaiJiangJie** [comment]
没有。
