### ISSUE TITLE
[Question]  关于使用容器进行部署，然后测试winrdp资产时，报错

### ISSUE THREAD

**Issue by CMJNB** [jumpserver/jumpserver#12758]
**请描述您的问题.**
版本：1Panel商店的3.10.3
报错截图：
![QQ截图20240305234230](https://github.com/jumpserver/jumpserver/assets/53365071/33bf828e-0a75-44d7-870a-3af53ff306e5)

**Comment by BaiJiangJie** [comment]
```
docker exec -it jms_celery bash

cd apps/

python manage.py shell

import pyfreerdp
```

执行一下看看能否导入？

**Comment by CMJNB** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/53365071/1ee55aeb-4866-4c06-a4f0-614c45f40b80)
请问是这样么

**Comment by BaiJiangJie** [comment]
看着没问题，1Panel 使用的 All-in-one 版本，如果要长期使用还是建议使用离线包安装。

**Comment by BaiJiangJie** [comment]
进入到 All-in-one 容器中，执行一下命令看一下在什么路径下：
```
which python

which ansible

which ansible-runner
```

**Comment by CMJNB** [comment]
> @CMJNB
> 
> 进入到 All-in-one 容器中，执行一下命令看一下在什么路径下：
> 
> ```
> which python
> 
> which ansible
> 
> which ansible-runner
> ```

![image](https://github.com/jumpserver/jumpserver/assets/53365071/7a9779d8-685a-4fc6-9e37-a22705471ea8)

**Comment by feng626** [comment]
jumpserver/apps/assets/automations/ping/custom/rdp/main.yml  修改一下mian.yml 脚本 
  vars:
    ansible_shell_type: sh
    ansible_connection: local
    ansible_python_interpreter: /opt/py3/bin/python

**Comment by feng626** [comment]
/opt/py3/bin/python 这个路径下 import pyfreerdp 有么

**Comment by CMJNB** [comment]
> jumpserver/apps/assets/automations/ping/custom/rdp/main.yml 修改一下mian.yml 脚本 vars: ansible_shell_type: sh ansible_connection: local ansible_python_interpreter: /opt/py3/bin/python

![image](https://github.com/jumpserver/jumpserver/assets/53365071/0de57232-337a-49f5-b63a-e86cd00b8ecd)

**Comment by CMJNB** [comment]
> /opt/py3/bin/python 这个路径下 import pyfreerdp 有么

![image](https://github.com/jumpserver/jumpserver/assets/53365071/1afad110-cc99-4eb9-8de5-df28110b5e5a)
这样么

**Comment by feng626** [comment]
改完文件 可执行成功么

**Comment by CMJNB** [comment]
> 改完文件 可执行成功么

可以执行成功

**Comment by feng626** [comment]
accounts/automations/verify_account/custom/rdp  这里的main文件也要改一下 
 先这么写着吧 等.6的时候我加到代码里

**Comment by QYG2297248353** [comment]
3.10.6也是出现此问题
![image](https://github.com/jumpserver/jumpserver/assets/56836951/4f7c81f9-a12a-43a5-9124-77530110392e)

**Comment by QYG2297248353** [comment]
但是获取硬件信息也报错，不知道是不是类似问题

**Comment by QYG2297248353** [comment]
@feng626 [v3.10.7-lts](https://github.com/jumpserver/jumpserver/releases/tag/v3.10.7) 修复了吗

**Comment by BaiJiangJie** [comment]
没有，v3.10.8-lts 上修复。

@QYG2297248353

**Comment by m7mdcc** [comment]
The issue still on the latest version , if you change system to Windows2016 its work , but the issue now with the remote app , when you create remote app host , there is no choice to set system Windows2016 , winrm work . but the system say 

'Core API failed: connect API core err: No host account available' 


when you change it to rdp its say 
`fatal: [Win-Server-2019]: FAILED! => {"msg": "the connection plugin 'rdp' was not found"}`
