### ISSUE TITLE
[Question] 在权限管理-用户登录设置了指定时间禁止登录，到指定时间后，已有的Web SSH会话依旧可以操作

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [jumpserver/jumpserver#12760]
**请描述您的问题.**
在权限管理-用户登录设置了指定时间禁止登录，到达指定时间后，已有的Web SSH会话依旧可以操作，执行命令，如果不关闭会话或者不刷新页面的话，就可以一直操作。
是否有配置可以到限制时间后强制登出呢？
如果目前没有，后续是否有优化的计划？

**Comment by BaiJiangJie** [comment]
权限管理中的设置（资产授权、用户登录、资产登录等）对于已建立的 Web SSH 的会话是不限制的，只在连接资产时进行校验。

你可以配合`连接资产的最大时间`配置项来使用。（系统设置-安全设置-会话设置）

针对这块逻辑，目前短期内还没有优化计划。
