### ISSUE TITLE
[Question] 关于MongoDB数据库测试验证错误的问题

### ISSUE THREAD

**Issue by CMJNB** [jumpserver/jumpserver#12767]
**请描述您的问题.**
![image](https://github.com/jumpserver/jumpserver/assets/53365071/8777cf09-5a2a-4c35-b908-aaa02029d8bb)
测试的账号密码应该是没问题的，复制粘贴的
![image](https://github.com/jumpserver/jumpserver/assets/53365071/df418f84-87ae-4377-8ef7-2ce30aed5c82)
但是客户端测试是没问题的。

**Comment by CMJNB** [comment]
补充。在工作台-控制台能连接上。

**Comment by BaiJiangJie** [comment]
也就是真正连接使用的时候没问题，就是测试数据库可连接性的时候报错？

**Comment by CMJNB** [comment]
> 也就是真正连接使用的时候没问题，就是测试数据库可连接性的时候报错？

就目前情况看，是的。

**Comment by CMJNB** [comment]
还有就是，为什么mysql可以不选择数据库进行链接，MongoDB一定要选择数据库？

**Comment by O-Jiangweidong** [comment]
@CMJNB 这套MongoDB环境是怎么搭建出来的，什么版本，我们试着复现一下

**Comment by CMJNB** [comment]
> @CMJNB 这套MongoDB环境是怎么搭建出来的，什么版本，我们试着复现一下

你好。这个也是1panel商店安装的，版本是7.0.6

**Comment by O-Jiangweidong** [comment]
我试一下哈

**Comment by O-Jiangweidong** [comment]
@CMJNB 我在1panel上部署了一个mongodb7.0.6的，测试了一下，测试可连接是没有问题的，我使用的mongodb库是admin，你检查一下你再JumpServer中配置的这个库是否存在于mongodb中，因为自动化任务底层使用的是ansible模块，这里要求db是必填的，如果填写不对，测试链接是无法通过的

**Comment by O-Jiangweidong** [comment]
<img width="1439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/80373698/3cd0250e-2db8-4055-93a9-772e4e3ab1d8">

**Comment by CMJNB** [comment]
> @CMJNB 我在1panel上部署了一个mongodb7.0.6的，测试了一下，测试可连接是没有问题的，我使用的mongodb库是admin，你检查一下你再JumpServer中配置的这个库是否存在于mongodb中，因为自动化任务底层使用的是ansible模块，这里要求db是必填的，如果填写不对，测试链接是无法通过的

我确定是填写了正确的库，因为不填写是无法保存的，而且在控制台却可以正常进行连接数据库。
![image](https://github.com/jumpserver/jumpserver/assets/53365071/2cc80908-6156-4da3-bf8c-845a5f505f38)
![image](https://github.com/jumpserver/jumpserver/assets/53365071/6ff2de76-2050-4909-9ea5-c016e17c6118)
![image](https://github.com/jumpserver/jumpserver/assets/53365071/41ee419f-065a-47c2-a65e-6582740a6125)
我还需要提供什么日志文件么

**Comment by O-Jiangweidong** [comment]
执行命令查看一下这个用户下拥有的数据库(show dbs)，

能连接上是因为mongosh工具可以直接连接到指定的库(即使没有)，但是ansible模块不支持这么操作

你需要在main库中也能查到此用户

<img width="469" alt="image" src="https://github.com/jumpserver/jumpserver/assets/80373698/68461752-9d2d-4a03-bb36-4681b6fa2c19">

<img width="558" alt="image" src="https://github.com/jumpserver/jumpserver/assets/80373698/14b639ce-6ca6-43b6-a90f-892b702c73dc">

**Comment by CMJNB** [comment]
> db.runCommand({ usersInfo: "" })
你好，
之前是我直接用管理员去连接库，所以能进shell
现在我创了新的库叫maindb，并在库里创建了用户mainuser，这是链接成功的截图
![image](https://github.com/jumpserver/jumpserver/assets/53365071/280da150-cced-4e9d-bead-72f3e0d272f5)
测试也可以了
![image](https://github.com/jumpserver/jumpserver/assets/53365071/7f8bcf34-eb27-4b65-ae14-7fedb49f098a)
但是shell反而进不去了
![image](https://github.com/jumpserver/jumpserver/assets/53365071/7c6b744c-467a-4054-aaca-8af894ce133a)

**Comment by O-Jiangweidong** [comment]
因为koko组件(命令行方式连接)目前只能接受 authSource 为 admin 的连接，
原因：mongodb-urioption-urioption.authSource 只支持admin连接，后续调研这个库支持修改后，我们会放开这个参数

**Comment by O-Jiangweidong** [comment]
https://github.com/jumpserver/koko/pull/1310

**Comment by jym503558564** [comment]
3.10.8已修复，请升级进行体验。
