### ISSUE TITLE
[Bug] 循环登录问题

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#12771]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.5 

**浏览器版本**
edge  

**Bug 描述**
（原版本3.10.3）升级到3.10.5后，很多用户都出现了登录时，输入完用户名、密码后又跳转到登录界面的问题，希望排查下

**Comment by wellsyu** [comment]
使用无痕模式或者完全清理浏览器数据可以解决，但是，很多人不愿意清楚浏览器数据，有没有其他方法

**Comment by BaiJiangJie** [comment]
其他用户没有反馈这个问题。能复现吗？

**Comment by James-ci-git** [comment]
umpServer 版本 3.10.5 lts
管理员登录登录时存在这个问题，非管理员登录没有这个问题，浏览器使用无痕模式登录还算比较稳定一点。使用Chrome浏览器比使用火狐浏览器几率要大。

**Comment by wellsyu** [comment]
> umpServer 版本 3.10.5 lts 管理员登录登录时存在这个问题，非管理员登录没有这个问题，浏览器使用无痕模式登录还算比较稳定一点。使用Chrome浏览器比使用火狐浏览器几率要大。

我这边是管理员和非管理员都存在这个问题

**Comment by BaiJiangJie** [comment]
用 edge 能复现，用 chrome 能吗？

**Comment by BaiJiangJie** [comment]
打开控制台，看看 API 条用顺序，是哪个 API 请求退出的？

**Comment by wellsyu** [comment]
升级后，同时还出现另外两个问题
1、登录界面不能勾选 1天内自动登录
2、web控制台 收藏夹的内容全部失去

**Comment by BaiJiangJie** [comment]
第1个问题，是因为配置的原因。

**Comment by BaiJiangJie** [comment]
循环跳转和收藏夹的问题，远程看一下？
@wellsyu

**Comment by SC-zj** [comment]
3.10.1升级到3.10.5也出现了这个问题，回滚后恢复。

**Comment by wellsyu** [comment]
> 循环跳转和收藏夹的问题，远程看一下？ @wellsyu

都已经通过清理浏览器处理掉了，循环登录不能再复现。收藏夹的内容一直没恢复，这个问题不大重新收藏

**Comment by BaiJiangJie** [comment]
好的。
