### ISSUE TITLE
[Bug] 重新初始化部署远程应用发布机和远程应用后，Chrome无法使用

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#12780]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.4

## 使用的版本类型 (必填)
- [√ ] 社区版

## 版本安装方式 (必填)
- [√ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
因远程应用发布机显示离线，于是删除后重新初始化部署远程应用发布机和远程应用，部署成功后发现远程应用Chrome无法使用，报如下错误
![image](https://github.com/jumpserver/jumpserver/assets/32380085/8319af8e-d481-4d32-a7d5-7ce261a0c830)

## 系统环境
检查远程应用发布机，发现重新初始化部署的过程中安装了这两个软件
![image](https://github.com/jumpserver/jumpserver/assets/32380085/92577d02-f309-4ced-9bd7-4a9f739768f3)

环境变量中的 Path 也指向了新安装的 Python3.11 的目录
![image](https://github.com/jumpserver/jumpserver/assets/32380085/c9e6caf5-0ac4-4cd5-9744-849f6f7c4f72)

结合报错信息，推测是因为 Python 版本更新导致无法找到 module，从而无法启动。
手动修改环境变量，指向 Python 3.10 的目录后，问题解决，Chrome 远程应用正常启动。
![image](https://github.com/jumpserver/jumpserver/assets/32380085/7c2edcb1-5482-483d-9f9c-a06b44261658)

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
从哪个版本升级上来的？
@saszhuqing

**Comment by saszhuqing** [comment]
> 从哪个版本升级上来的？ @saszhuqing

Jumpserver 是从 v3.10.3 版本升级上来的，远程应用发布机是v3.4.0版本之前部署的，因为当时还没有加入 隐藏地址栏 这个特性。
Python v3.10 版本和安装时间如下图所示
![image](https://github.com/jumpserver/jumpserver/assets/32380085/76e0fb7d-f1c0-46ba-bd1c-01e9e9ef7a1f)

**Comment by LeeEirc** [comment]
可能初始化部署升级到 python3.11的时候，未卸载旧版本的 python3.10造成依赖安装路径不对。待测试复现后，会优化此问题。

**Comment by jym503558564** [comment]
按照您这边的测试版本，我进行了以下测试，未复现该问题。
1.JS-v3.4.0版本，发布机部署成功，此时查看发布机上pyhton版本是3.10，且python环境变量路径正确。测试web资产连接成功。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/75cd71d4-3305-41a9-924e-4833fbc0738a)
<img width="1367" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/44e7f6e7-ebf0-4738-a101-61e40b6f42e4">

2.JS-v3.4.0版本升级至v3.10.4版本，发布机重新点击初始化部署成功后。此时查看发布机上pyhton版本是3.11，且python环境变量路径正确。测试web资产连接成功。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/368c08c7-f19a-4036-80b2-f93b613ffa0f)
<img width="1370" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/05409d09-d61f-491f-9eeb-3970b02bef37">

**Comment by saszhuqing** [comment]
能否确认下控制面板中是还有python3.10 ？我是连续升级的，不是从3.4直接升级到3.10的。

**Comment by LeeEirc** [comment]
可以说下具体的升级复现步骤吗？

**Comment by saszhuqing** [comment]
重新理了一下时间线，根据控制面板里 python 3.10 的安装时间 2023-5-18，以及官网的更新日志，推测是在 v3.3.0 的时候第一次部署了远程发布机和远程应用。后面是按照 3.3→3.4→3.5→……→3.9→3.10 的顺序连续升级上来的。
升级到 v3.10.4 后，因为网络架构原因，变更了 JS 的 IP 地址。变更后远程发布机显示离线，根据指南删除发布机后重新添加，并做了初始化部署，发布远程应用。发布后发现 Chrome 无法打开，检查控制面板发现同时存在 Python 3.10 和 3.11 两个版本，后调整环境变量 Path 中的 Python 路径指向 3.10 后可以正常打开。

**Comment by LeeEirc** [comment]
Windows 发布机是否有过其他的手动修改？只要是升级到 3.10 后才点击的初始化部署，低版本顺序连续升级 v3.10 和直接升级到 v3.10 并无本质区别。

**Comment by saszhuqing** [comment]
没有手动修改过，全新的 Win Server 2019 部署的。我觉得有可能是 v3.3 版本和后续版本的 Chrome 远程应用的不同导致的。从 v3.4 版本开始 Chrome 远程应用加入了隐藏地址栏功能，启用前提之一是重新部署发布机。我在升级到 v3.10.4 之前都没有重新部署过，所以这个功能也就一直没用过，打开 Web 资产时就是标准的、包含地址栏的浏览器窗口，但重新部署发布机并发布应用之后这个功能就生效了，说明是对 Chrome 远程应用进行了更新。
根据 @jym503558564 的测试结果，从 v3.4 升级到 v3.10 并没有复现这个问题，说明应该是 v3.3 和 v3.4 两个版本中所包含的 Chrome 远程应用存在差异。

**Comment by BaiJiangJie** [comment]
@saszhuqing  感谢详细反馈，目前尝试了多次复现场景也没有复现出来。
我们暂且记住这个问题，将来如果有其他用户遇到了，我们在研究复现场景。

当前先按照修改发布机上`Python`解释器路径来进行解决，如果后续研发团队发现产品的默认升级逻辑有问题会及时修复。
并在当前 issue 进行回复。

**Comment by foaisjf** [comment]
![Image](https://github.com/user-attachments/assets/80805766-f21f-4deb-b693-042e82ab669c)
发布机服务起不来 部署一直报错是什么问题
