### ISSUE TITLE
针对sftp的一些建议[Feature]

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#12782]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
1、授权sftp时添加“修改”这个复选框。
2、sftp的默认家目录路径能够直接在资产上更改。

## 功能描述
1、授权sftp时添加“修改”这个复选框。这样达到控制修改文件名称和内容的目的。
2、sftp的默认家目录路径能够直接在资产上更改，甚至在这台资产的账号上更改。这样就不需要在“平台列表”上添加指定路径的平台类型了。

## 功能要求
1、对于添加“修改”这个复选框，遇到的场景：给用户授权时，即便是只勾选了“下载”，其文件名称和内容还是可以修改的。这样存在安全隐患。
2、对于sftp默认家目录，遇到的场景：有一些需求，是仅授权sftp的指定目录可以访问，而且不同的需求，目录不同，并非固定。所以目前只能新建平台的方式创建，每个需求创建一个平台会比较麻烦。如果能在资产上直接修改最好，我可以将sftp当作应用来进行创建，每个需求创建一个资产即可。但目前资产上面是继承且灰色无法修改。

**Comment by BaiJiangJie** [comment]
问题1，只勾选了“上传”，修改文件名称和内容是合理的；只勾选了“下载”，应该不能修改只能下载。上传权限，其实属于读写权限（只不过读，读只能读文件目录名），下载相当于只读权限（文件名和文件内容）。
你 SFTP 连接的是 Linux 吗？

问题2，在平台中指定 SFTP 目录时可以使用下面的变量类型，可以达到每个账号使用不同的路径，整体还是相对统一的，这样也方便管理，针对资产或者账号进行单独修改的场景，一个是使用起来比较分散，另一个维护成本比较高，据用户反馈真正的使用场景也不是很多。所以暂时不考虑支持单独修改。

**Comment by akang1798** [comment]
问题1中提到的sftp是Linux的。我试过只勾选“下载”的确不能删除，但可以修改文件名。

**Comment by BaiJiangJie** [comment]
可以截图看一下吗？如何进行修改的？

**Comment by BaiJiangJie** [comment]
如果能稳定复现，重新 reopen。
