### ISSUE TITLE
[Feature] 管理员可以根据需要选择是否隐藏用户连接Chrome远程应用时显示地址栏

### ISSUE THREAD

**Issue by saszhuqing** [jumpserver/jumpserver#12783]
## 功能名称
管理员可以根据需要选择是否隐藏用户连接Chrome远程应用时所显示的地址栏信息

## 功能描述
从 JumpServer v3.4.0 版本开始，系统默认隐藏了用户连接Chrome远程应用时所显示的地址栏信息，防止用户通过单个会话跳转到其他页面进行操作。这个设计的初衷是好的，可以避免一些可能的未授权访问，但对于一些点击链接会自动拉起新标签页的系统，或者需要通过一个界面访问多个系统时（已在系统层面通过防火墙做了白名单），隐藏地址栏就很不方便。

如下图所示，左侧是连接到 Web 资产时自动拉起来的、没有地址栏和标签页的浏览器窗口（分析代码应该是通过加了 --app 参数实现的）；右侧是在点击左侧应用系统中的某些链接，操作系统自动拉起来的一个标准的、有地址栏和标签页的浏览器窗口。这样导致既没有起到“防止用户通过单个会话跳转到其他页面进行操作”的隔离作用，反而给正常操作带来了极大的不便。

![image](https://github.com/jumpserver/jumpserver/assets/32380085/7b0b0e21-84ef-477d-83ac-cd99254ad043)

## 功能要求
建议在 Web 资产中添加一个选项，管理员可以根据需要选择是否隐藏地址栏，即是否启用 Chrome 的 --app 参数

**Comment by BaiJiangJie** [comment]
<img width="1365" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/1aa726a3-9cf2-41cd-82c8-4cac0b79cab9">

连接 Chrome 远程应用时，是否允许显示地址栏或者打开新的标签页，管理员可以控制的。
如上图，创建一个新平台，在协议设置中关闭安全模式。

**Comment by saszhuqing** [comment]
已创建一个新的 Web 平台，并关闭安全模式，重启服务器后进行测试，地址栏仍为隐藏状态。

![image](https://github.com/jumpserver/jumpserver/assets/32380085/ee87f4a4-d2b3-48b9-87a9-2511039539cf)

![image](https://github.com/jumpserver/jumpserver/assets/32380085/10a0ec9b-e0df-4e8a-86dc-11ebbf3ab34f)

**Comment by BaiJiangJie** [comment]
嗯，地址栏还是会隐藏，但是可以新建的标签页，新建的标签页就有地址栏了吧。

**Comment by saszhuqing** [comment]
在原窗口上无法新建标签页，必须要右键点击菜单栏，然后选择“打开浏览器窗口”，才能打开一个新的浏览器窗口，这样就又回到我一开始说的问题了，首页面和其他页面分开了，操作很不方便。
![image](https://github.com/jumpserver/jumpserver/assets/32380085/15bc76b6-5c32-4259-80ab-c331825e3feb)

我看了下远程应用包里的代码，如果注释掉 app.py 的第 244 行，也就是不加 --app 参数，就是可以正常打开一个标准浏览器窗口的，但不能自动打开 Web 资产里设置的 URL 地址，即便在 app.py 里加上 --url 参数也没用，不知道是否有其他临时解决方案？
![image](https://github.com/jumpserver/jumpserver/assets/32380085/8fbeb131-72d3-473b-9f92-f30924b51c22)

**Comment by BaiJiangJie** [comment]
目前官方只提供安全模式浏览器应用。

如果你需要的话可以自己下载 Chrome 应用，然后修改 app.py 文件，重新压缩一下，上传使用。

**Comment by saszhuqing** [comment]
已更换为应用市场里的 0.7.3 版本，并把 app.py 里的 --app 参数更换为 --url ，但现在只能打开标准浏览器窗口，不能自动打开 Web 资产设定的 URL 地址，请问 app.py 还需要修改哪里吗？

**Comment by saszhuqing** [comment]
删除了L247-251，还是没用，请问哪里可以下载到 v3.3 版本对应的 Chrome 远程应用吗？这个版本的还没加入安全功能。

**Comment by saszhuqing** [comment]
仔细研究了一下 Chrome 的参数，终于发现之前为什么修改 --app 为 --url 没有成功的原因了，--app 后面需要加一个 =，而 --url 后面是一个空格，把 app.py 的 244 行修改一下，就能解决这个问题了。
![image](https://github.com/jumpserver/jumpserver/assets/32380085/dbf26fd5-c80b-42c8-97ff-02dceac0916b)

**Comment by rudstone** [comment]
Hi,

I confirm now it does'nt working... I have top bar again...
Any solution?
