### ISSUE TITLE
LDAP用户是否不支持vscode Remote-ssh直连托管机

### ISSUE THREAD

**Issue by CupofFish** [jumpserver/jumpserver#12794]
##LDAP用户是否不支持vscode Remote-ssh直连

## 当前使用的 JumpServer 版本 (必填)
3.7.1

## 使用的版本类型 (必填)
-  社区版

## 版本安装方式 (必填)
- 在线安装 (一键命令)

## 问题描述 (详细)
已参照教程：https://kb.fit2cloud.com/?p=48  修改配置，重启Jumpserver。JumpServer 用户来源为LDAP，目前无法在终端页面直接连接。在网页端能通过记住密码选择机器直接登陆，这一步是否未能做到托管账号，将资产密码保存在Jumpserver数据库中。终端使用命令ssh  ldapuser@ldapuser@tuoguanji@baoleiji 需要输入两次密码才能登录。
## 背景信息
- 操作系统：本地终端：windows、ubuntu

## 尝试过的解决方法
1、查看koko报错
docker logs -f jms_koko --tail 200 | grep ssh
2024-03-12 11:25:20 [ERRO] Get SSH Client failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

## 预期结果
能通过vscode 直接远程连接托管机

## 我们的期望
我该如何做到托管账号

**Comment by BaiJiangJie** [comment]
可以啊，托管资产账号密码后，打开 Web 终端页面。
选择 SSH 向导，在打开的连接信息向导页面使用第一种 ssh 命令连接方式，输入表格中对应的密码，就直接登录了。

<img width="715" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/5d9ca859-5822-4fe3-9e98-3efab71f0c13">

<img width="1036" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/3735c86a-b65d-4e54-bba8-c5460ca722c0">

**Comment by zdf0221** [comment]
多谢，这个操作可以成功连接，想再确认一下有没有其他方法可以固化这个连接？我测试了一下，该Token貌似仅供单次使用。

**Comment by BaiJiangJie** [comment]
是的，目前这个 Token 是一次性的，不允许永久 Token 创建，将来可能会考虑支持。

`想了解一下为什么使用帐户名密码进行二次跳转的方式不适用于LDAP用户，该ssh连接方式在终端中是可用的（需要输入两次LDAP密码）`
这个没有看懂是什么问题？

**Comment by zdf0221** [comment]
笔误，想了解一下为什么使用用户名密码进行二次跳转的方式不适用于vscode ssh插件，而该ssh连接方式在终端中是可用的（需要输入两次LDAP密码）

**Comment by BaiJiangJie** [comment]
因为 vscode ssh 插件的方式进行认证时，只有一次的交互式输入密码的逻辑，我们控制不了。
ssh 方式我们可以进行控制，交互次数。

@zdf0221

**Comment by BaiJiangJie** [comment]
好的，目前计划 v3.10.6-lts 上线。

@CupofFish

**Comment by zdf0221** [comment]
@BaiJiangJie 您好,我看了一下release log,这个功能是不是已经在3.10.8 LTS版本上线了? 我们可以尝试更新了吗? 谢谢

**Comment by BaiJiangJie** [comment]
最新版本已更新。可以试试。
@zdf0221

**Comment by CupofFish** [comment]
@BaiJiangJie 您好，我们升级到了v3.10.9，页面显示token的过期时间还是五分钟，我们在vscode里仍然五分钟就断连，token过期时间我们能设置嘛？
![image](https://github.com/jumpserver/jumpserver/assets/44918824/00e40746-7c86-4bf9-a423-0aefd32d6c25)
