### ISSUE TITLE
[Feature] ChatGPT审计台会话记录远端地址不显示实际IP

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#12793]
## 功能名称
chatgpt 类资产运维审计远端地址显示真实ip

## 功能描述
用户其他类型资产远端地址显示正常，ChatGPT类资产显示地址为容器内部网段的地址

## 功能要求
ChatGPT显示地址为真实地址

**Comment by BaiJiangJie** [comment]
好的，v3.10.6-lts 修复一下。

**Comment by jym503558564** [comment]
已复现，待修复。

**Comment by jym503558564** [comment]
3.10.8已修复，ChatGPT会话记录远端地址不对的问题，请升级进行体验。
