### ISSUE TITLE
[Question] 使用新建窗口方式打开，侧栏的设置消失

### ISSUE THREAD

**Issue by Belkuy** [jumpserver/jumpserver#12792]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.10.5]

## 使用的版本类型 (必填)
- [√] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [√] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在这里描述你遇到的问题]

## 背景信息
- 操作系统：Windows
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
使用新建窗口方式打开windows系统，侧栏没有了设置的按钮，无法复制粘贴和上传下载文件。我记得3.10.1的时候还有的。

**Comment by BaiJiangJie** [comment]
v3.10.4 显示有点问题没有图标，v3.10.5 应该有了。

分屏显示的状态下没有，单个会话是有的。

**Comment by BaiJiangJie** [comment]
<img width="1835" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/a5f51eca-be54-4e36-9c1c-ba2919404563">

**Comment by Belkuy** [comment]
我现在版本就是V3.10.5，windows 系 在“新窗口打开”中，设置这个按钮没有
![image](https://github.com/jumpserver/jumpserver/assets/84887701/793e73ce-23a9-45bf-866a-86cc1d4c94cc)

![image](https://github.com/jumpserver/jumpserver/assets/84887701/a029ca7c-629a-4ce1-a4c8-0cb8ae8c2cc7)


> v3.10.4 显示有点问题没有图标，v3.10.5 应该有了。
> 
> 分屏显示的状态下没有，单个会话是有的。

**Comment by BaiJiangJie** [comment]
好的，新窗口打开有问题，后面版本优化一下加上设置按钮。
