### ISSUE TITLE
[Question] jumpserver 安装在pull镜像时报错：missing signature key

### ISSUE THREAD

**Issue by asaotomo** [jumpserver/jumpserver#12798]
<img width="727" alt="image" src="https://github.com/jumpserver/jumpserver/assets/67818638/0091c3cc-f68d-4cb1-8d53-ba16d88217eb">
安装在pull镜像时报错：missing signature key，不知道为何，docker安装其他软件的镜像是没问题的。

**Comment by asaotomo** [comment]
> <img alt="image" width="727" src="https://private-user-images.githubusercontent.com/67818638/311968509-0091c3cc-f68d-4cb1-8d53-ba16d88217eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjYwODYsIm5iZiI6MTcxMDIyNTc4NiwicGF0aCI6Ii82NzgxODYzOC8zMTE5Njg1MDktMDA5MWMzY2MtZjY4ZC00Y2IxLThkNTMtYmExNmQ4ODIxN2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA2NDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZjY0MTA4MTgzNjI3NGRhNWEwZmJmNmQ1ZWIyNjY4ZmFiODU0MWIyNDY2ZjMwMDQ0ODNiYzQyNTYyYWEzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnLNIIvLVp0_19rJivjbg0Th3JVDvbtD9jmVNP3GQYA"> 
安装脚本在pull镜像时报错：missing signature key，不知道为何，docker安装其他软件的镜像是没问题的。

**Comment by wojiushixiaobai** [comment]
更新 docker 版本后重启 docker 或者 重启服务器 即可。

**Comment by abbott68** [comment]
系统内核低的原因

**Comment by zphj1987** [comment]
更新 docker 版本后可以了
