### ISSUE TITLE
[Feature] JumpServer的云同步能否增加资产自动添加后实现可选择自动打标签的能力？

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#12802]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[云同步 打标签]

## 功能描述
[云同步任务增加给添加上的资产自动打标签]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[中]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
截图 + 详细描述。
