### ISSUE TITLE
Lion 连接windows资产 转圈！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#12817]
## 当前使用的 JumpServer 版本 (必填)
3.10.5-tls

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## Bug 描述 (详细)
目前使用的是3.10.5-tls 最新版本，该版本使用的是Lion组件 在连接windows资产时 发现每次都显示连接中 转圈转三次 （有时次数更多）才能进去windows系统，给使用者造成了一定的困扰。
我环境中保留了早期的2.0版本，该版本连接windows使用的是Apache Guacamole组件 连接时不会出现连接中转圈的现象，瞬间就进入windows系统中。

谢谢！

**Comment by BaiJiangJie** [comment]
v3 版本使用的也是 Guacamole 组件，你看一下 Lion 的日志有没有异常信息?

**Comment by vicentwu** [comment]
![QQ图片20240314222545](https://github.com/jumpserver/jumpserver/assets/36059301/710a5b1d-fc73-46c3-94bc-5fe53966c7d9)
lion.log很多类似的记录，

**Comment by BaiJiangJie** [comment]
这个 ERROR 是正常，下个版本修改一下日志级别。

这个日志是用户正常断开会话的时候打印的。

转3圈其实是正常的，后端要处理很多数据。

**Comment by BaiJiangJie** [comment]
正常情况，v3 版本的交互会多一些，还增加了一些 loding 的状态，v2 版本是直接呈现画面的感觉上可能会快一些。

如果转圈之后，连不上了那是有问题。

**Comment by vicentwu** [comment]
这个连接转圈数还不定期的增加，给用户造成了一定的困扰，，是否会考虑采用V2版本的直接呈现画面，这样用户直观看到，不会因为一直转圈圈，而觉得服务器有问题或者这个堡垒机的问题。谢谢！
