### ISSUE TITLE
日志记录不全问题

### ISSUE THREAD

**Issue by yuanguoping** [jumpserver/jumpserver#1281]
[简述你的问题]

##### 使用版本
[jumpserver1.2.1  coco 1.2.0]

##### 问题复现步骤
通过coco登录mysql执行的sql有换行，命令记录中没有记录。
如：
CREATE TABLE
    test
    (
        id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        is_active TINYINT(1) NOT NULL,
        date_expired DATETIME NOT NULL,
        created_by VARCHAR(128) NOT NULL,
        date_created DATETIME NOT NULL,
        COMMENT longtext NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT name UNIQUE (name)
    )
;

在coco的日志中以及jumpserver命令记录也没都没有

[注:] 完成后请关闭 issue

**Comment by yuanguoping** [comment]
一条都没有，复制粘贴到终端执行的

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues

**Comment by xionghui** [comment]
![default](https://user-images.githubusercontent.com/2037425/45605282-7ceee500-ba6e-11e8-8d24-659d0461ba64.png)

**Comment by xionghui** [comment]
偶现出现，命令显示问题，如何破？

**Comment by xionghui** [comment]
![default](https://user-images.githubusercontent.com/2037425/45605295-9bed7700-ba6e-11e8-8647-e9d7ec4d40d7.png)

**Comment by xionghui** [comment]
会话管理-》命令记录下的命令有问题，input 会跑到output里
