### ISSUE TITLE
[Bug] 无法取消SSH为主协议，自定义通用模版，测试可连接性显示报错

### ISSUE THREAD

**Issue by asaotomo** [jumpserver/jumpserver#12810]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
v3.10.5

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
我们网络设备使用的是telnet，但是在添加网络设备资产选择huawei设备时，无法取消SSH主协议。自建通用模版可以设置主协议为telnet，但是测试连接报错，测试步骤还是使用ssh进行的连接测试，导致可连接性显示报错。

## 复现步骤
<img width="1521" alt="image" src="https://github.com/jumpserver/jumpserver/assets/67818638/a805081b-8e6b-4f6f-b4fe-5ded1fc4fc7e">

<img width="1310" alt="image" src="https://github.com/jumpserver/jumpserver/assets/67818638/c6c9613c-3e6b-40e5-9961-493889197067">

**Comment by BaiJiangJie** [comment]
你需要先创建一个新的 Huawei 平台，在平台中对协议的属性进行设置，资产中只能查看不能设置。
