### ISSUE TITLE
[Feature] 录像会话加密方式写入配置文件

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#12818]
## 功能名称
录像会话加密方式写入配置文件

## 功能描述
目前堡垒机录像会话的加密方式是同样的，当录像会话被拷贝或泄露时，可以通过任意开源客户端下载的播放器播放录像文件。
可以考虑将录像会话的加密密钥写入配置文件（类似数据库加密密钥），只有通过当前堡垒机客户端下载的播放器才可以解码录像会话文件。

**Comment by BaiJiangJie** [comment]
暂时不考虑对录像文件进行加密。

1. 加密操作比较耗时。
2. 有权限的管理员才能下载录像。
3. 可以直接在线播放，不用下载到本地。
