### ISSUE TITLE
[Bug] 关于会话分享的命令过滤

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#12811]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.4

## 使用的版本类型 (必填)
社区版

## 版本安装方式 (必填)
在线安装 (一键命令)

## Bug 描述 (详细)
用管理员登录一个资产，然后将这个资产进行会话分享给一个指定的用户，这个指定的用户打开链接登录资产的操作不受命令过滤控制

## 复现步骤
1. 用管理员登录linux设备
2. 将这个设备会话分享给一个指定的用户
3. 用这个指定的用户打开链接登录设备，操作的命令不受命令过滤控制

## 期望行为
我是希望会话分享给一个指定的用户，那就得按照这个指定用户的命令过滤规则来执行
因为正常本公司的人是拥有网络设备的所有执行权限，本公司的人分享会话给其他部门的用户或者其他公司的用户希望是只有查看权限的，

## 实际行为
我测试了一下，目前的逻辑是将会话分享给一个指定的用户，这个用户打开的资产权限是继承了分享人的用户的权限，比如我用管理员将会话分享给一个指定的用户，这个指定的用户就算绑定了命令过滤规则，他也可以执行命令过滤规则中拒绝的命令

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
命令过滤规则是根据这个会话的 Owner 来的，不会根据被分享者的权限来。
创建分享链接时支持两种方式：读写、只读权限。

不考虑根据被分享者进行权限判断（命令过滤）。
