### ISSUE TITLE
升级到3.10.5后vnc始终认证失败

### ISSUE THREAD

**Issue by jumping008** [jumpserver/jumpserver#12824]
jumpserver 通过docker-compose方式升级到v3.10.5后，所有资产vnc登录失败

![image](https://github.com/jumpserver/jumpserver/assets/58167667/392ca801-d555-438e-bf4e-c9cae5f64527)

显示信息如下：
![image](https://github.com/jumpserver/jumpserver/assets/58167667/cf51f186-3973-488f-972e-64cb2efec1c0)

查看服务器上VNC的log显示：
![image](https://github.com/jumpserver/jumpserver/assets/58167667/69f7a80d-34d8-4f5c-99dc-b4f34e6b30ae)

从正常的PC上vnc-view登录是成功的，log显示如下：
![image](https://github.com/jumpserver/jumpserver/assets/58167667/8f9dc6d2-d30e-4be8-add3-71079cc44451)

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [ ] 社区版 v3.10.5
-

## 版本安装方式 (必填)
通过docker-compose安装

**Comment by BaiJiangJie** [comment]
之前版本一直可以吗？ 查看一下账号的密码对吗？

**Comment by jumping008** [comment]
之前的是3.4.1一直是可以的，使用vnc-viewer用相同的密码是可以登录的
![image](https://github.com/jumpserver/jumpserver/assets/58167667/71f228ff-8dd2-4a14-948b-f2ce0fc51c8f)

**Comment by XMoon** [comment]
相同反馈 之前一直正常 升级后一直提示密码错误 相同密码使用novnc可以正常连接
```
Mar 17 23:26:44 lubuntu bash[1094]: 17/03/2024 23:26:44 rfbAuthProcessClientMessage: password check failed
Mar 17 23:26:44 lubuntu bash[1094]: 17/03/2024 23:26:44 rfbClientSendString("password check failed!")
```

**Comment by BaiJiangJie** [comment]
好的，那有可能是 Lion 有问题了，我们复现一下。
@jym503558564

**Comment by LeeEirc** [comment]
可以加下社群，远程看下环境

**Comment by jumping008** [comment]
再社群34里，有说话等待回复哈

**Comment by LeeEirc** [comment]
@XMoon 把 jumpserver/jms_lion:v3.10.2 镜像替换成 jumpserver/lion:v3.10.2 应该就可以了。

**Comment by LeeEirc** [comment]
使用社区 lion 镜像 `jumpserver/jms_lion:v3.10.2` 的可替换成 ` jumpserver/lion:v3.10.2` 解决连接 VNC 的问题。
