### ISSUE TITLE
mysql web cli连接支持caching_sha2_password算法

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12829]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
mysql web cli连接支持caching_sha2_password算法

## 功能描述
mysql8 之前的版本中加密规则是mysql_native_password,而在mysql8之后,加密规则是caching_sha2_password，现在使用web cli控制台连接mysql8之后版本会提示
ERROR 2061 (HY000): Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection.
使用mysql 命令行连接需添加参数--get-server-public-key则能成功登录，有什么解决方案吗
参考：https://cloud.tencent.com/developer/article/2027452

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
@jym503558564 看看能不能复现一下，@LeeEirc 评估一下如何处理。

**Comment by yuanxixue** [comment]
mysql 8.0.3的版本，但是加密算法是caching_sha2_password，caching_sha2_password，希望做一个适配的选项，可以根据选项来适配mysql_native_password改成caching_sha2_password两种加密方式
![Uploading image.png…]()

**Comment by yuanxixue** [comment]
![Uploading 1710752676670.jpg…]()

**Comment by yuanxixue** [comment]
![Uploading 1710752676670.jpg…]()

**Comment by jym503558564** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/40739051/9175213e-3357-404a-8883-c73105725022)
我这个MySQL-8版本使用也是caching_sha2_password加密，连接时未发现报错。不通过JS时，可正常连接吗？或者有没有其他设置？

**Comment by yuanxixue** [comment]
连接一直卡在这里，在堡垒机服务器上执行mysql命令连接，也是一样的效果，网络端口是通的
![Uploading 1710836591712.jpg…]()

**Comment by jym503558564** [comment]
图片重新上传一下，显示不出来。

**Comment by yuanxixue** [comment]
![1710836591712](https://github.com/jumpserver/jumpserver/assets/38065018/8f6915a0-2c2c-4bba-8787-3c31a01624d6)

**Comment by jym503558564** [comment]
1.测试了阿里云的MySQL8 ，查询其默认加密规则为：mysql_native_password。此时JS-koko代理连接成功。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/b15cf669-0314-45de-9367-3801fbf03198)
2.修改加密规则为caching_sha2_password，此时JS-koko代理连接成功。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/d43cd02e-4ad5-41dc-a28e-121d5e5c0491)
