### ISSUE TITLE
[Bug] 终端真实ip

### ISSUE THREAD

**Issue by wmbin** [jumpserver/jumpserver#12839]
## 当前使用的 JumpServer 版本 (必填)
v3.10.5

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## Bug 描述 (详细)
终端获得ip为容器的ip

终端 | 192.168.250.1 | 局域网 | Go-http-client/1.1 | 启用

USE_LB已经设置为0

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12381#issuecomment-1867424637

USE_LB=1 呢？

**Comment by wmbin** [comment]
> [#12381 (comment)](https://github.com/jumpserver/jumpserver/issues/12381#issuecomment-1867424637)
> 
> USE_LB=1 呢？

也一样，但是web端 USE_LB=0可以获取到真实ip
但是终端不行，不知道终端是怎么取值的

**Comment by BaiJiangJie** [comment]
1. 用户 Web 方式登录 JumpServer
2. 用户 SSh 方式登录 JumpServer
3. 用户 Web SSH 方式登录资产
4. 用户 SSH 方式登录资产

上面四种情况，是哪种情况下可以获取真实 IP，哪种情况下获取不到？

**Comment by wmbin** [comment]
> 1. 用户 Web 方式登录 JumpServer
> 2. 用户 SSh 方式登录 JumpServer
> 3. 用户 Web SSH 方式登录资产
> 4. 用户 SSH 方式登录资产
> 
> 上面四种情况，是哪种情况下可以获取真实 IP，哪种情况下获取不到？

问题解决了，群晖的iptables问题，添加以下策略就好了
`

iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER

`
