### ISSUE TITLE
[Feature] 历史会话导出结果中建议增加时长列

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#12837]
## 功能要求
当前历史会话页面展示结果中有时长列，但是导出结果中没有改列信息，希望可以再导出结果中增加一列时长列

<img width="604" alt="image" src="https://github.com/jumpserver/jumpserver/assets/97491875/115fa979-2de3-4c77-970b-7508afd88d58">

**Comment by BaiJiangJie** [comment]
v3.10.7 版本支持。

**Comment by jym503558564** [comment]
3.10.8已修复，请升级进行体验。
<img width="388" alt="image" src="https://github.com/jumpserver/jumpserver/assets/40739051/65749579-2eb7-4756-a92d-1bd9d3a6057a">
