### ISSUE TITLE
更新到v3.10.5後, 1天自動登錄不能勾上

### ISSUE THREAD

**Issue by leo880816** [jumpserver/jumpserver#12831]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.5

## 使用的版本类型 (必填)
- [√] 社区版

## 版本安装方式 (必填)
- [√] 在线安装 (一键命令)

## Bug 描述 (详细)
更新到v3.10.5後, 1天自動登錄的選項不能勾上.

## 系统环境
- 操作系统：[Windows 11, macOS Sonoma]
- 浏览器/应用版本：Google Chrome 122.0.6261.129
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
![image](https://github.com/jumpserver/jumpserver/assets/31840811/9fb09452-e12c-40f9-ae25-3b8ffd56ffd5)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12742#issuecomment-1975600320

按照这种方式操作一下。

**Comment by learn-py-c** [comment]
> 抱歉... 我看了Core下 /opt/jumpserver/apps/jumpserver/conf.py 兩個參數都改了, 還是不能勾選 ![image](https://private-user-images.githubusercontent.com/31840811/313625590-db14dcc4-7e03-4fb8-bdaf-8a3034da4d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYwOTQsIm5iZiI6MTcxMzUxNTc5NCwicGF0aCI6Ii8zMTg0MDgxMS8zMTM2MjU1OTAtZGIxNGRjYzQtN2UwMy00ZmI4LWJkYWYtOGEzMDM0ZGE0ZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YjBhZjE2YjYwNWM3YmUwMzJhMGUzM2RmMDMxZmU3MzlmYjE5MzcyODUyNGE3ZTQxYzk4YzcyNGNkYWFiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5YzlETVL1ADCPjtZLf3rsdASR0l2_86bGf5lOTyNSI)

**Comment by learn-py-c** [comment]
> 抱歉... 我看了Core下 /opt/jumpserver/apps/jumpserver/conf.py 兩個參數都改了, 還是不能勾選 ![image](https://private-user-images.githubusercontent.com/31840811/313625590-db14dcc4-7e03-4fb8-bdaf-8a3034da4d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYwOTQsIm5iZiI6MTcxMzUxNTc5NCwicGF0aCI6Ii8zMTg0MDgxMS8zMTM2MjU1OTAtZGIxNGRjYzQtN2UwMy00ZmI4LWJkYWYtOGEzMDM0ZGE0ZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YjBhZjE2YjYwNWM3YmUwMzJhMGUzM2RmMDMxZmU3MzlmYjE5MzcyODUyNGE3ZTQxYzk4YzcyNGNkYWFiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5YzlETVL1ADCPjtZLf3rsdASR0l2_86bGf5lOTyNSI)

修改的应该是宿主机/opt/jumpserver/config/config.txt 目录下的配置文件。虽然我改了，而且重启了所有容器也没用，不知道是不是使用脚本一键部署的问题，没法重新加载配置文件

**Comment by leo880816** [comment]
> > 抱歉... 我看了Core下 /opt/jumpserver/apps/jumpserver/conf.py 兩個參數都改了, 還是不能勾選 ![image](https://private-user-images.githubusercontent.com/31840811/313625590-db14dcc4-7e03-4fb8-bdaf-8a3034da4d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTYwOTQsIm5iZiI6MTcxMzUxNTc5NCwicGF0aCI6Ii8zMTg0MDgxMS8zMTM2MjU1OTAtZGIxNGRjYzQtN2UwMy00ZmI4LWJkYWYtOGEzMDM0ZGE0ZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YjBhZjE2YjYwNWM3YmUwMzJhMGUzM2RmMDMxZmU3MzlmYjE5MzcyODUyNGE3ZTQxYzk4YzcyNGNkYWFiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5YzlETVL1ADCPjtZLf3rsdASR0l2_86bGf5lOTyNSI)
> 
> 修改的应该是宿主机/opt/jumpserver/config/config.txt 目录下的配置文件。虽然我改了，而且重启了所有容器也没用，不知道是不是使用脚本一键部署的问题，没法重新加载配置文件
> 
> 需要使用jmsctl restart重启才有效果。测试已经解决

感謝回覆, 成功解決了
