### ISSUE TITLE
[Question] scp文件传输的命令格式

### ISSUE THREAD

**Issue by bikai-ayy** [jumpserver/jumpserver#12843]
## 注意
**scp命令格式** <br>
**v3.10.5* <br>
_如何在本地终端使用scp命令通过jumpserver向资产传输文件_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.5]

## 使用的版本类型 
- [ ✅] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 
- [ ] 在线安装 (一键命令)
- [✅ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[如何在本地终端使用scp命令通过jumpserver向资产传输文]

## 背景信息
- 操作系统：macos

**Comment by BaiJiangJie** [comment]
开启 ENABLE_LOCAL_PORT_FORWARD 和 ENABLE_VSCODE_SUPPORT 的配置，才可以使用 scp 命令上传了。（直连方式）（这种操作目前没有文件审计记录）

scp -P 2222 localFilePath admin@account@assetID@jumpserverHost:remotePATH

**Comment by bikai-ayy** [comment]
报错提示scp: dest open "/root/": Failure
![image](https://github.com/jumpserver/jumpserver/assets/120439116/8b1c9cdb-c2c5-4e8b-8dfd-ad0c39a8eb2e)

**Comment by BaiJiangJie** [comment]
openssh 版本 >= 8.7 的版本使 scp 默认会使用 sftp 的子系统，我们的 scp 不支持 sftp 方式。
所以，你使用 scp 时加上 -O 参数，强制使用 scp 协议进行传输。

scp -O -P 2222 .......

**Comment by bikai-ayy** [comment]
添加-O之后解决了，thanks
