### ISSUE TITLE
标识RDP 会话的咨询

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#12846]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.5
## 使用的版本类型 (必填)
-  社区版

## 版本安装方式 (必填)
-在线安装 (一键命令)

## 问题描述 (详细)
我的场景是：同时有多人登录同一个windows资产（跳板机，共用远程登录用户），由于工作需要，需要标识/定位/识别/找回 自己的会话，以便在出现异常时（如会话超时、网络异常、被抢占会话）找回自己的会话。是否有办法在系统的任务管理器的会话中予以标识支持。

## 背景信息
- 操作系统：Windows 2016等
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
在资源管理器的用户标签中，”客户端名“或”会话"显示jumpserver用户的信息
![图片](https://github.com/jumpserver/jumpserver/assets/38068938/8d7d5972-7253-47a9-8558-843c4717fd6f)

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by LeeEirc** [comment]
参考 #https://github.com/jumpserver/jumpserver/issues/11503
