### ISSUE TITLE
资产树节点主机数显示与列表显示不一致

### ISSUE THREAD

**Issue by huang830** [jumpserver/jumpserver#1284]
资产列表--资产树节点显示的跟列表明细显示的主机数不一致，经核实资产树节点数量是正确的，列表显示的明细有误（显示了其它节点的主机）。
##### 使用版本
Version 1.2.1-2 GPLv2

##### 问题复现步骤
1. 新建多级资产树节点，然后去数据库assets_node表里找相似key 如：节点1的key：0:1:0:1:3，节点2的key：0:1:3
2. 在节点1里面新建主机，此时节点1的标签数据显示为1，节点2标签数量显示为0，但是点开节点2发现里面有刚才节点1里面新建的主机

##### 问题分析
感觉是查询某节点列表的SQL语句写的有问题，匹配key的时候错了。

![d10c6f5a-feed-4510-b866-a0a5dad6c1e4](https://user-images.githubusercontent.com/38782102/39670894-d3a9fe4e-5140-11e8-8331-552c844192b8.png)
![qq 20180506152019](https://user-images.githubusercontent.com/38782102/39670901-06b6e612-5141-11e8-9b24-8e8e5de14d6a.png)

##### 其他

望早日修复，等着测试。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
