### ISSUE TITLE
[Question] 前端界面button disabled

### ISSUE THREAD

**Issue by bikai-ayy** [jumpserver/jumpserver#12852]
## 注意
**前端界面资产创建按钮无法点击** <br>
**v3.10.5** <br>
_admin用户资产创建按钮变成灰色，有些按钮也有类似问题_

## 当前使用的 JumpServer 版本
[v3.10.5]

## 使用的版本类型 
- 社区版

## 版本安装方式
- 离线安装 (下载离线包)

## 背景信息
- macOS
- Chrome 122.0.6261.129（正式版本） (arm64)

## 具体问题
![image](https://github.com/jumpserver/jumpserver/assets/120439116/ce0e5d23-6f6f-408a-91fe-7d714b421dd3)
资产创建按钮无法点击

**Comment by BaiJiangJie** [comment]
还没有遇到过这种情况，可以远程看一下吗？

**Comment by bikai-ayy** [comment]
先上传了一个录屏，请问下，怎么远程？
https://github.com/jumpserver/jumpserver/assets/120439116/6e19eaa2-3d47-4aed-8271-c38bd524b91f

**Comment by BaiJiangJie** [comment]
使用远程工具，到你电脑上看一下是什么问题？

**Comment by bikai-ayy** [comment]
https://quicksupport.me/s148292934 你看teamviewer可以吗

**Comment by BaiJiangJie** [comment]
我的 teamviewer 用不了，toDesk 可以吗？

**Comment by bikai-ayy** [comment]
ToDesk设备代码:288 803 975
临时密码:5xwx891a
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=RDtVkL8E1AG4iqa2Tuhxt
试试呢

**Comment by BaiJiangJie** [comment]
好的。

**Comment by BaiJiangJie** [comment]
连上了。

**Comment by BaiJiangJie** [comment]
白江杰 邀请您参加腾讯会议
会议主题：白江杰的快速会议
会议时间：2024/03/22 14:56-15:56 (GMT+08:00) 中国标准时间 - 北京

点击链接直接加入会议：
https://meeting.tencent.com/dm/q4UYtLQSnrO3

#腾讯会议：587-621-215

复制该信息，打开手机腾讯会议即可参与

**Comment by BaiJiangJie** [comment]
加一下会议，比较好沟通。
@bikai-ayy

**Comment by bikai-ayy** [comment]
好的

**Comment by bikai-ayy** [comment]
浏览器删除local storage和session storage解决
