### ISSUE TITLE
[Bug] v3.10.5 资产授权列表没有“有效性”列了

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12854]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
企业版 v3.10.5

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
v3.10.5 资产授权列表没有“有效性”列了。
<img width="1382" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/2c580b86-83ec-4b1f-a7a2-61dab3a1c744">
<img width="847" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/43c1c6f7-aed0-4132-bb61-62fd7a8972b6">

v3.9 
<img width="1020" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/3fe95d39-2ed7-4c7e-8736-406d9c7c72f3">

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
v3.10.7 加一下。

**Comment by jym503558564** [comment]
3.10.8已修复，请升级进行体验。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/b848fa9f-5118-4020-9924-1ea2787c4416)
