### ISSUE TITLE
[Question] 配置CAS后，当CAS server注销时，需要请求哪个接口进行jumpserver的注销

### ISSUE THREAD

**Issue by Iamdreaming** [jumpserver/jumpserver#12856]
## 当前使用的 JumpServer 版本 (必填)
[3.10.5]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [x] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
jumpserver的开发者，你们好，配置CAS后，当CAS server注销时，是否支持cas server进行注销jumpserver，如果支持需要请求哪个接口进行jumpserver的注销。

## 我们的期望
帮忙告知是否有相关cas注销接口，或者是否能够支持单点注销

**Comment by BaiJiangJie** [comment]
支持的，cas server 用户退出后，调用 http://localhost/core/auth/logout/ 路径就可以。

**Comment by Iamdreaming** [comment]
但这个需要在浏览器调用，没法通过服务器发送cas退出
`<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="529c1ded-63fc-47f4-ad03-62a6ff4e8f02" Version="2.0" IssueInstant="2024-03-25T09:03:55.074Z"><saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">admin</saml:NameID><samlp:SessionIndex>ST-43-bPiQjjeenOGBFg1AOigZeSJnTe7T1weCOmR</samlp:SessionIndex></samlp:LogoutRequest>`
以下是响应
Http Response HttpStatus 301 MOVED_PERMANENTLY

**Comment by BaiJiangJie** [comment]
嗯，没有别的 API 方式了。
