### ISSUE TITLE
[Bug] Windows 资产多人登录有些用户，常常提示“连接异常，aborted see logs”

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#12851]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.5
## 使用的版本类型 (必填)
 社区版

## 版本安装方式 (必填)
 在线安装 (一键命令)

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
客户端windows2003
资产系统平台：Windows
多人登录使用，个别人 突发提示“连接异常 aborted see logs” 被退出webgui，同期其它人员正常。

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：windows 2003
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]
![76ae00a303474de1afeb17de794fe35](https://github.com/jumpserver/jumpserver/assets/38068938/cf7765cb-a9a6-4637-b558-f050ef9be827)
![429b14394944ce195fd1a42b067df6e](https://github.com/jumpserver/jumpserver/assets/38068938/3fbf77d8-d139-4566-9df5-9f26c96edf3f)

**Comment by BaiJiangJie** [comment]
日志级别修改成 DEBUG，然后看一下 guacd.log 日志。

**Comment by sanpichen** [comment]
我已经打开debug模式，但是guacd.log日志里连时间都没有，我很难定位到具体的日志信息，有需要请你告知我定位方式，以便我摘出来提供给你们。。
如下是docker logs jms_lion日志：
2024-04-23 08:50:13 tunnel conn.go [INFO] Session[532c5a12-06ca-4112-a2c2-13d1a32f8b41] receive guacamole server disconnect: 5.error,18.Aborted. See logs.,3.520;
2024-04-23 08:50:13 tunnel conn.go [ERROR] Session[532c5a12-06ca-4112-a2c2-13d1a32f8b41] receive web client disconnect opcode
2024-04-23 08:50:13 tunnel conn.go [ERROR] Session[532c5a12-06ca-4112-a2c2-13d1a32f8b41] web client read err: websocket: close 1005 (no status)
2024-04-23 08:50:13 tunnel conn.go [INFO] Session[532c5a12-06ca-4112-a2c2-13d1a32f8b41] Connection exit websocket: close 1005 (no status)
2024-04-23 08:50:13 tunnel conn.go [ERROR] Session[532c5a12-06ca-4112-a2c2-13d1a32f8b41] send web client err: websocket: close sent
2024-04-23 08:50:13 session parser.go [INFO] Session 532c5a12-06ca-4112-a2c2-13d1a32f8b41: Parser close
2024-04-23 08:50:13 session parser.go [INFO] Session 532c5a12-06ca-4112-a2c2-13d1a32f8b41: Parser routine done
2024-04-23 08:50:13 session recorder.go [INFO] Session 532c5a12-06ca-4112-a2c2-13d1a32f8b41: Command recorder close

**Comment by sanpichen** [comment]
这些搜出来的ERR有无价值：
	行 193813: guacd[823]: DEBUG:	ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
	行 193815: guacd[823]: DEBUG:	rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_DECRYPT_FAILED [0x00011192]
	行 193817: guacd[823]: ERROR:	Connection closed.
	行 194435: guacd[228]: ERROR:	User is not responding.
	行 194459: guacd[1538]: DEBUG:	ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
	行 194461: guacd[1538]: DEBUG:	rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_DECRYPT_FAILED [0x00011192]
	行 194463: guacd[1538]: ERROR:	Connection closed.
	行 195091: guacd[2014]: DEBUG:	ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
	行 195093: guacd[2014]: DEBUG:	rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_DECRYPT_FAILED [0x00011192]
	行 195095: guacd[2014]: ERROR:	Connection closed.
	行 196123: guacd[3513]: ERROR:	User is not responding.

**Comment by LeeEirc** [comment]
替换资产的平台类型为 Windows-RDP 平台，连接 RDP 使用的安全层改成 RDP 再试一下。

**Comment by sanpichen** [comment]
不行，我找某次的日志如下：
lion.log 日志：
2024-04-25 14:48:54 tunnel server.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] Connect options resolution: "auto"
2024-04-25 14:48:54 tunnel server.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] use resolution (1919*992)
2024-04-25 14:48:54 tunnel server.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] connect success
2024-04-25 14:48:54 session parser.go [INFO] Session 37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf: Parser start
2024-04-25 14:48:54 session recorder.go [INFO] Session 37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf: Command recorder start
2024-04-25 15:29:41 tunnel conn.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] receive guacamole server disconnect: 5.error,18.Aborted. See logs.,3.520;
2024-04-25 15:29:41 tunnel conn.go [ERROR] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] receive web client disconnect opcode
2024-04-25 15:29:41 tunnel conn.go [ERROR] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] web client read err: websocket: close 1005 (no status)
2024-04-25 15:29:41 tunnel conn.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] Connection exit websocket: close 1005 (no status)
2024-04-25 15:29:41 tunnel conn.go [ERROR] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] send web client err: websocket: close sent
2024-04-25 15:29:41 session parser.go [INFO] Session 37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf: Parser close
2024-04-25 15:29:41 session parser.go [INFO] Session 37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf: Parser routine done
2024-04-25 15:29:41 session recorder.go [INFO] Session 37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf: Command recorder close
2024-04-25 15:29:42 session server.go [INFO] Upload record file: /opt/lion/data/replays/2024-04-25/37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf.replay.gz, type: server
2024-04-25 15:29:42 tunnel server.go [INFO] Session[37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf] disconnect

guacd.log日志：
guacd[54665]: DEBUG:    Processing instruction: size
guacd[54665]: DEBUG:    Processing instruction: audio
guacd[54665]: DEBUG:    Processing instruction: video
guacd[54665]: DEBUG:    Processing instruction: image
guacd[54665]: DEBUG:    Processing instruction: timezone
guacd[54665]: DEBUG:    Parameter "console" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "console-audio" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "disable-auth" omitted. Using default value of 0.
guacd[54665]: INFO:     Security mode: RDP
guacd[54665]: DEBUG:    User resolution is 1919x992 at 96 DPI
guacd[54665]: DEBUG:    Parameter "dpi" omitted. Using default value of 96.
guacd[54665]: DEBUG:    Using resolution of 1916x992 at 96 DPI
guacd[54665]: DEBUG:    Parameter "force-lossless" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "read-only" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-theming" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-full-window-drag" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-desktop-composition" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-menu-animations" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "disable-bitmap-caching" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "disable-offscreen-caching" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "disable-audio" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-printing" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "printer-name" omitted. Using default value of "Guacamole Printer".
guacd[54665]: DEBUG:    Parameter "timezone" omitted. Using default value of "Asia/Shanghai".
guacd[54665]: DEBUG:    Parameter "enable-sftp" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "sftp-hostname" omitted. Using default value of "10.194.131.35".
guacd[54665]: DEBUG:    Parameter "sftp-port" omitted. Using default value of "22".
guacd[54665]: DEBUG:    Parameter "sftp-username" omitted. Using default value of "administrator".
guacd[54665]: DEBUG:    Parameter "sftp-password" omitted. Using default value of "".
guacd[54665]: DEBUG:    Parameter "sftp-passphrase" omitted. Using default value of "".
guacd[54665]: DEBUG:    Parameter "sftp-root-directory" omitted. Using default value of "/".
guacd[54665]: DEBUG:    Parameter "sftp-server-alive-interval" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "sftp-disable-download" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "sftp-disable-upload" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "recording-exclude-output" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "recording-exclude-mouse" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "recording-exclude-touch" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "recording-include-keys" omitted. Using default value of 0.
guacd[54665]: INFO:     Resize method: display-update
guacd[54665]: DEBUG:    Parameter "enable-touch" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "enable-audio-input" omitted. Using default value of 0.
guacd[54665]: DEBUG:    Parameter "gateway-port" omitted. Using default value of 443.
guacd[54665]: INFO:     No clipboard line-ending normalization specified. Defaulting to preserving the format of all line endings.
guacd[54665]: DEBUG:    Parameter "wol-send-packet" omitted. Using default value of 0.
guacd[54665]: INFO:     User ***@***.***" joined connection "$b6e2f3ac-491a-47fd-bc8e-47c23ff940c6" (1 users now present)
guacd[54665]: DEBUG:    Client is using protocol version "VERSION_1_3_0"
guacd[54665]: DEBUG:    guac_rdp_fs_alloc: Creating directory "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826" if necessary.
guacd[54665]: INFO:     Recording of session will be saved to "/opt/lion/data/replays/2024-04-25/37b7d7f7-6da8-4c8d-88da-f3a1efb5dbcf".
guacd[54665]: INFO:     Loading keymap "base"
guacd[54665]: INFO:     Loading keymap "en-us-qwerty"
guacd[54665]: DEBUG:    Support for CLIPRDR (clipboard redirection) registered. Awaiting channel connection.
guacd[54665]: DEBUG:    Support for static channel "rdpdr" loaded.
guacd[54665]: DEBUG:    Support for static channel "rdpsnd" loaded.
guacd[54665]: DEBUG:    Local framebuffer format  PIXEL_FORMAT_BGRX32
guacd[54665]: DEBUG:    Remote framebuffer format PIXEL_FORMAT_BGR24
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="/", access=0x80000000, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "/" to "\".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\" as file_id=0
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\" (file_id=0)
guacd[54665]: DEBUG:    CLIPRDR (clipboard redirection) channel connected.
guacd[54665]: DEBUG:    SVC "rdpdr" connected.
guacd[54665]: DEBUG:    SVC "rdpsnd" connected.
guacd[54665]: DEBUG:    Loading Dynamic Virtual Channel disp
guacd[54665]: INFO:     Connected to RDPDR 1.10 as client 0x6c79
guacd[54665]: DEBUG:    Ignoring server capability set type=0x0001, length=44
guacd[54665]: DEBUG:    Ignoring server capability set type=0x0002, length=8
guacd[54665]: DEBUG:    Ignoring server capability set type=0x0003, length=8
guacd[54665]: DEBUG:    Ignoring server capability set type=0x0004, length=8
guacd[54665]: DEBUG:    Ignoring server capability set type=0x0005, length=8
guacd[54665]: DEBUG:    Sending capabilities...
guacd[54665]: DEBUG:    Capabilities sent.
guacd[54665]: DEBUG:    Client ID confirmed
guacd[54665]: INFO:     RDPDR user logged on
guacd[54665]: DEBUG:    Registered device 0 (JumpServer)
guacd[54665]: DEBUG:    All supported devices sent.
guacd[54665]: DEBUG:    Device 0 (JumpServer) connected successfully
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\", access=0x100001, file_attributes=0x0, create_disposition=0x1, create_options=0x21
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\" to "\".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\" as file_id=0
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_create: [file_id=0] desired_access=0x100001, file_attributes=0x0, create_disposition=0x1, create_options=0x21, path="\"
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\Download", access=0x80000000, file_attributes=0x0, create_disposition=0x3, create_options=0x1
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\Download" to "\Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\Download" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\Download" as file_id=1
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\Download" (file_id=1)
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_directory: [file_id=0] initial_query=1, dir_pattern="\*"
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\", access=0x1, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\" to "\".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\" as file_id=1
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_both_directory_info: [file_id=1 (entry_name=".")]
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\" (file_id=1)
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_directory: [file_id=0] initial_query=0, dir_pattern="\*"
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\", access=0x1, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\" to "\".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\" as file_id=1
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_both_directory_info: [file_id=1 (entry_name="..")]
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\" (file_id=1)
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_directory: [file_id=0] initial_query=0, dir_pattern="\*"
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\Download", access=0x1, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\Download" to "\Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\Download" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\Download" as file_id=1
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_both_directory_info: [file_id=1 (entry_name="Download")]
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\Download" (file_id=1)
guacd[54665]: DEBUG:    guac_rdp_fs_open: path="\Download", access=0x100001, file_attributes=0x0, create_disposition=0x1, create_options=0x21
guacd[54665]: DEBUG:    guac_rdp_fs_open: Normalized path "\Download" to "\Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: Translated path "\Download" to "/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download".
guacd[54665]: DEBUG:    guac_rdp_fs_open: native open: real_path="/opt/lion/data/drive/92fd3e19-0b47-4357-a4c8-bb7e97e45826/Download", flags=0x0
guacd[54665]: DEBUG:    guac_rdp_fs_open: Opened "\Download" as file_id=1
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_create: [file_id=1] desired_access=0x100001, file_attributes=0x0, create_disposition=0x1, create_options=0x21, path="\Download"
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_directory: [file_id=1] initial_query=1, dir_pattern="\Download\*"
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_close: [file_id=1]
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\Download" (file_id=1)
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_query_directory: [file_id=0] initial_query=0, dir_pattern="\*"
guacd[54665]: DEBUG:    guac_rdpdr_fs_process_close: [file_id=0]
guacd[54665]: DEBUG:    guac_rdp_fs_close: Closed "\" (file_id=0)
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[54665]: DEBUG:    ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
guacd[54665]: DEBUG:    rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_DECRYPT_FAILED [0x00011192]
guacd[54665]: DEBUG:    BIO_read returned a system error 104: Connection reset by peer
guacd[54665]: ERROR:    Connection closed.
guacd[54665]: DEBUG:    CLIPRDR (clipboard redirection) channel disconnected.
guacd[54665]: DEBUG:    Unloading device 0 (JumpServer)
guacd[54665]: DEBUG:    SVC "rdpdr" disconnected.
guacd[54665]: DEBUG:    SVC "rdpsnd" disconnected.
guacd[54665]: INFO:     User ***@***.***" disconnected (0 users remain)
guacd[54665]: INFO:     Last user of connection "$b6e2f3ac-491a-47fd-bc8e-47c23ff940c6" disconnected
guacd[54665]: DEBUG:    Requesting termination of client...
guacd[54665]: INFO:     Internal RDP client disconnected
guacd[54665]: DEBUG:    Client terminated successfully.


***@***.***
 
发件人： Eric_Lee
发送时间： 2024-04-23 14:29
收件人： jumpserver/jumpserver
抄送： sanpichen; Author
主题： Re: [jumpserver/jumpserver] 常常提示“连接异常，aborted see logs” (Issue #12851)
替换资产的平台类型为 Windows-RDP 平台，连接 RDP 使用的安全层改成 RDP 再试一下。

**Comment by sanpichen** [comment]
> 按照以下方式测试看看 1、进入 jms_lion 容器
> 
> ```
> docker exec -it jms_lion bash
> ```
> 
> 2、容器内执行以下两条命令
> 
> ```
> sed -i "s#MinProtocol = .*#MinProtocol = TLSv1#g" /etc/ssl/openssl.cnf
> sed -i "s#CipherString = .*#CipherString = DEFAULT@SECLEVEL=1#g" /etc/ssl/openssl.cnf
> ```
> 
> 3、退出容器，重启下 Lion 容器
> 
> ```
> docker restart jms_lion
> ```

试过了，没用
