### ISSUE TITLE
JumpServer Access to Web

### ISSUE THREAD

**Issue by Garrybac** [jumpserver/jumpserver#12857]
Hello,

On JumpServer I face issue that I have configured Jump to Access the Web But when I access it. The button "Connect" is disabled.
How could I configure it correctly?

Thanks

**Comment by Garrybac** [comment]
![jumpweb](https://github.com/jumpserver/jumpserver/assets/117132103/a9e2770b-51ee-4316-a00a-1c58a5647f79)

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/

You need to deploy a remote application publishing machine.
（But there is currently no English documentation.）

**Comment by BaiJiangJie** [comment]
<img width="2006" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/04fafcb1-f3f8-4276-ad4a-561bd55555ee">

**Comment by Garrybac** [comment]
Thank you it is working.
