### ISSUE TITLE
[Bug] 工单-待我审批列表默认搜索未生效

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12865]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.6

## 使用的版本类型 (必填)
- 企业版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
进入工单待我审批列表，默认的“待处理” 搜索条件未生效，显示的是全量数据，如图
![image](https://github.com/jumpserver/jumpserver/assets/95400700/0d632e9f-9dcf-4e5a-940d-b95504a393b7)

## 复现步骤
1. 打开工单

## 期望行为
进入待我审批列表，默认展示 “待处理” 的工单列表

## 实际行为
进入待我审批列表，默认展示的是所有工单

## 系统环境
- 操作系统：Windows 10, macOS Big Sur
- 浏览器/应用版本：Chrome 最新版
- 其他相关环境信息：无

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
嗯，目前有一些问题，v3.10.8 中会修复。
