### ISSUE TITLE
[Bug] 连接 Windows VNC资产 ，画面下半部分会变的模糊

### ISSUE THREAD

**Issue by liuyy0808** [jumpserver/jumpserver#12863]
## 当前使用的 JumpServer 版本 (必填)
[V3.10.6]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## Bug 描述 (详细)
[使用VNC协议，连接Windows 资产时，屏幕下半部分会变得模糊，上半部分正常，重装老版本发现，V3.6.6版本是清晰的，到V3.7就模糊了，3.7版本更新了大量关于lion组件的内容，怀疑和此次更新变更的内容有关]

## 复现步骤
1. [每次连接Windows VNC资产必复现]

## 期望行为
[期望和以前一样清晰不模糊]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：WIN10 专业版
- 浏览器/应用版本：谷歌 版本 122.0.6261.129
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by liuyy0808** [comment]
![画面截图](https://github.com/jumpserver/jumpserver/assets/164499075/c01f7444-9e06-4df3-a715-f6d02031c172)

**Comment by BaiJiangJie** [comment]
下半部分看着页不是很模糊啊

**Comment by liuyy0808** [comment]
截图过来有压缩了，实际肉眼看着，V3.66和V3.7对比很明显的

**Comment by LeeEirc** [comment]
v3.6 和 v3.7 Lion 的核心连接逻辑的代码没有改动，应该是一样的连接效果。

**Comment by liuyy0808** [comment]
但是我实测下来，确实有肉眼可见的模糊。对比的环境如下：
1、centos 7.9 离线安装V3.6.6 **清晰** 
2、centos 7.9 离线安装V2.28    **清晰**
3、centos 7.9 离线安装V3.7    **模糊**
4、centos 7.9 一键安装V3.10.6    **模糊**
 Windows VNC Server均为同一台资产，VNC版本6.9.1，操作系统WIN10
期间也换过别的VNC资产，也同样能复现问题

**Comment by liuyy0808** [comment]
![V3 10 6](https://github.com/jumpserver/jumpserver/assets/164499075/d39b76b5-353e-45a6-984e-04319aa21dce)
![V2 28 21](https://github.com/jumpserver/jumpserver/assets/164499075/4e2b5be1-be39-4c9c-8613-5cecb56983a0)

截图对比如上，可能截图再上传有压缩，没有本地看明显
左上角是清晰的，越往右下角越模糊，测试期间换过电脑和显示器，都是右下角模糊

**Comment by LeeEirc** [comment]
V3.7 或 V3.10.6 的宿主机上，通过 docker 启动新的 guacd 服务：
```
docker run --name jms_guacd01 -d -p 4822:4822 --restart=always jumpserver/guacd:1.5.2
```

在 config.txt 添加修改下 Lion 配置：

```
GUA_HOST = '宿主机IP'
GUA_PORT = 4822
```

如果当前镜像未能有改善的话，可以替换 其它的镜像测试下。JumpServer 的 guacd 镜像参考https://hub.docker.com/r/jumpserver/guacd/tags

```
jumpserver/guacd:1.5.4-bookworm
jumpserver/guacd:1.5.3-bookworm
jumpserver/guacd:1.5.3-bullseye
jumpserver/guacd:1.5.2-buster
```
 
也可以替换原生 guacamole/guacd 镜像测试，镜像名参考 https://hub.docker.com/r/guacamole/guacd/tags

**Comment by liuyy0808** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/164499075/6cc62769-db4a-442f-acae-5574b4296563)
镜像已经替换了jumpserver/guacd:1.5.4-bookworm，Lion 的配置也更改了，但是我技术有限，更改后无法连接资产了

**Comment by LeeEirc** [comment]
加下交流群，可以远程帮你看下，或者你替换别的镜像再试试，也有可能是镜像本身的问题。

**Comment by LeeEirc** [comment]
窗口大小与资产分辨率不一致，画面缩放造成的虚化问题，已优化。窗口缩放侧边栏设置里可手动调节。
