### ISSUE TITLE
[Bug] gunicorn 组件CPU持续飙高

### ISSUE THREAD

**Issue by kesterchen** [jumpserver/jumpserver#12864]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.8.0]

## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] All-in-One

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
日志 /api/v1/users/profile/  频繁请求用户接口，导致gunicorn 组建CPU飙升

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

![image](https://github.com/jumpserver/jumpserver/assets/17474484/b433a1e5-5a87-4457-8b62-c2e56eee82cf)

**Comment by kesterchen** [comment]
192.168.250.11:60264 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60278 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60118 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60126 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59066 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59688 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60128 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58744 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58912 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60292 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60288 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60298 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60310 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58654 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58750 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58756 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58792 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58826 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60334 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58982 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59058 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58804 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59030 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58880 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58766 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58670 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58674 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60286 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58822 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60320 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60316 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60304 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60342 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60348 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60376 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58778 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58928 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58800 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60432 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60324 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58966 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58998 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59042 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58704 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58844 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60352 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59062 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60364 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58818 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60410 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59692 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58728 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60368 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58694 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60440 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60444 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60468 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:58946 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:59054 - "GET /api/v1/users/profile/ HTTP/1.0" 200
192.168.250.11:60510 - "GET /api/v1/users/profile/ HTTP/1.0" 200

**Comment by BaiJiangJie** [comment]
升级到最新版本，已解决。

**Comment by kesterchen** [comment]
> 升级到最新版本，已解决。
1.   V3.10.3 是否可以解决此问题
2. docker all one  3.8 有升级到最新版本的文档吗？
