### ISSUE TITLE
[Feature] 建议改进 MFA 验证体验，快速进入主页

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [jumpserver/jumpserver#12860]
建议输入 MFA 验证码之后 **自动验证进入主页，不需要自己再手动点击验证**

> 现在的 MFA 管理器基本都支持一键点击复制验证码功能，所以在登录过程中希望支持一键粘贴后 **自动进入主页**，无需手动点击验证。

<img width="634" alt="image" src="https://github.com/jumpserver/jumpserver/assets/46734380/615c4e70-2a7e-4064-83a2-13d9b8bc27b6">

**Comment by BaiJiangJie** [comment]
暂时不考虑优化。
