### ISSUE TITLE
[Question] 如何通过 API 方式上传部署文件至资产服务器

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#12868]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.8.1

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)

引入 JumpServer 之后，资产服务器无法直连，传输部署文件的时候就没办法走 SCP 的方式。虽然提供了 SFTP ，但是我更希望的部署动作是，先调用 JumpServer API 将部署文件上传至指定服务器的指定位置，然后再调用 API 创建一个作业，最后执行刚才创建的作业。以上三步操作我会封装成一个部署脚本，但目前卡在第一步上面。我在 Swagger 里面没找到相关接口。

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
升级到最新版本，会有文件传输功能。
升级后尝试一下你的设想，如果还有问题再 reopen。

**Comment by cobolbaby** [comment]
我不想走工作台模式，我还是希望可以从我本地的脚本发起操作，过堡垒机只是为了安全，后期方便审计。

@BaiJiangJie

**Comment by ViCrack** [comment]
同问，api上传方式

**Comment by fishs-x** [comment]
同问，api上传方式

**Comment by LoveWaguan** [comment]
是哪个API接口呢，需要这个接口

**Comment by ipengyo** [comment]
同问，如何处理呢？ 这对自动化操作非常需要。

**Comment by ViCrack** [comment]
当时官方没有提供文件管理API

一年前我用的方式是

调用模拟登录的web接口来实现，可以在文件管理中上传和下载文件，然后配合shell移动文件，至少这种方式可以实现自动化了，总算可以绕过这jumpserver，不用每次我都得登录这东西

**Comment by LoveWaguan** [comment]
希望可以帮助你们，拿到登录后的鉴权信息，模拟程序API接口如下，创建任务发送文件
 /**
     * 创建任务
     */
    public static final String CREATE_JOBS = "/api/v1/ops/jobs/";

    /**
     * 文件上传
     */
    public static final String UPLOAD_FILE = "/api/v1/ops/jobs/upload/";

    /**
     * 上传任务详情
     */
    public static final String TASK_DETAIL = "/api/v1/ops/job-execution/task-detail/";

    /**
     * 远端服务器返回执行信息
     */
    public static final String TASK_EXECUTION_LOG = "/api/v1/ops/ansible/job-execution/{id}/log";
