### ISSUE TITLE
[Bug] LDAP 登录认证失败

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12871]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.5]

## 使用的版本类型 (必填)
- [ ] 社区版
- [ ] 企业版
- [ √  ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ √   ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
LDAP 认证配置成功后，使用相同的 LDAP 账号登录有时登录正常，有时登录失败

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
登录后，前端页面报错：
<img width="762" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89765365/6f717171-ca35-44b5-b34b-84abf3f72628">

后台 jumpserver.log 报错：
![image](https://github.com/jumpserver/jumpserver/assets/89765365/f53e2460-c599-4073-bd37-ce95d59f4729)

## 系统环境
- 操作系统：[例如：CentOs]
- 浏览器/应用版本：[ Chrome ]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
LDAP Server 的版本和类型是什么？

什么情况下会出现（稳定复现）？

**Comment by BaiJiangJie** [comment]
已解决。（配置错误问题）
