### ISSUE TITLE
资产更新提交后返回页面为当前节点

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12875]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[节点下更新资产信息，点击提交后，希望页面还在当前节点下，而不是返回根节点]

## 功能描述
[节点下更新资产信息，点击提交后，希望页面还在当前节点下，而不是返回根节点]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]
<img width="1418" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/38b494e3-b6d8-452b-a099-66a51fc9f7f6">
节点层级较多，每次更新完节点下的资产，点击提交后，页面会返回根节点，还需要再一层一层点回来，继续更新别的资产，希望提交完页面还停留在当前节点
## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
是的，目前存在这样的问题。
暂时先不处理了，后期可能会修改整体创建/更新的方式，比如从右侧弹出。
具体计划目前还没有，未来会考虑。
