### ISSUE TITLE
[Bug] v2.28 升级到 v3.10.5，资产授权没有重复用户名，但是升级后资产授权还是丢失了与账号的关联关系

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#12876]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v2.28 升级到 v3.10.5

## 使用的版本类型 (必填)
企业版

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
 v2.28 升级到 v3.10.5，资产授权没有重复用户名，但是升级后资产授权还是丢失了与账号的关联关系。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/65611e6f-902f-453c-9711-5e73290aae53)
<img width="1394" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/ec3fe7c3-24bd-4470-ab2c-39c55b4389a2">

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
如果 v2 中没有授权关系，也会在升级过程中丢失。

**Comment by liufei20151013** [comment]
我已经知道什么原因导致的了，通过修改迁移脚本已经解决了。https://wiki.fit2cloud.com/pages/viewpage.action?pageId=143197711

**Comment by limoou** [comment]
> 我已经知道什么原因导致的了，通过修改迁移脚本已经解决了。https://wiki.fit2cloud.com/pages/viewpage.action?pageId=143197711

你好这个迁移脚本可以发我一份吗？
