### ISSUE TITLE
[Question] docker安装时mysql容器启动失败

### ISSUE THREAD

**Issue by taomujian** [jumpserver/jumpserver#12879]
## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- 社区版

## 版本安装方式 (必填)
- [ ] All-in-One

## 问题描述 (详细)
docker安装时mysql容器启动失败，报错ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

## 背景信息
- centos

## 具体问题
docker安装时mysql容器启动失败，报错ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

## 解决方法

修改jumpserver-installer-v2.28.8/compose/docker-compose-mariadb.yml文件内容，在第11行restart: always下面添加一行，内容为privileged: true

## 我们的期望
希望尽快更新文件，让更多的人不背这个问题卡住，浪费时间

**Comment by BaiJiangJie** [comment]
长期使用建议通过 离线安装包 方式部署，尽量使用最新版本。
