### ISSUE TITLE
[Bug] web资源在配置选择器自动登录的情况下如果页面里面有拖拽的行为会导致页面卡死

### ISSUE THREAD

**Issue by wzqiang1332** [jumpserver/jumpserver#12872]
版本号：3.10.6
版本类型：社区版
安装方式：docker一键安装

## Bug 描述 (详细)
最近发现web资产页面里面有拖动行为的组件拖拽时会导致卡死，比如画布里面拖拽，比如左侧拖拽到右侧div等等。
大概尝试了3个系统，只要存在拖拽组件拖拽就卡死了。F12也打不开，看不了控制台。
后面升级版本（3.10.2->3.10.6）,重新初始化跳板机都没有解决。最后发现可能是web资产的自动登录导致的，web资产选择器：自动代填选的基本，用户名，密码，确认按钮选择器都是css选择器。
我去掉确认按钮选择器，取消自动登录页面内部组件拖拽就正常了，加上确认按钮选择器，又会卡死。

## 复现步骤
1.添加web资产，web资产选择器：自动代填选的基本，用户名，密码，确认按钮选择器都是css选择器。web资产页面里面有拖拽功能。
2. 进入有拖拽功能的页面，进行拖拽无反应，F12无法打开
3. 去除确认按钮选择器，再次进入有拖拽功能的页面，进行拖拽功能正常
4. 再次添加确认按钮选择器，进行拖拽无反应，F12无法打开

## 期望行为
自动代填并确认登录后拖拽行为正常

## 实际行为
自动代填并确认登录后拖拽卡死

## 系统环境
- 操作系统：Centos7
- 浏览器/应用版本：Chrome

**Comment by BaiJiangJie** [comment]
可以录个视频看一下吗？

拖拽是指什么操作？为什么要拖拽组件。
