### ISSUE TITLE
[Question]  golang获取sso 免密登录地址失败

### ISSUE THREAD

**Issue by sierfeinuoding** [jumpserver/jumpserver#12880]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
2.25.5

## 使用的版本类型 (必填)
- [ * ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ * ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
我使用下面代码获取登录地址的时候会出现这个报错：{"detail":"Missing filename. Request should include a Content-Disposition header with a filename parameter.","code":"parse_error"}，请问是哪里写的不正确吗？

func main() {
	auth := SigAuth{
		KeyID:    AccessKeyID,
		SecretID: AccessKeySecret,
	}
	GetUserLoginUrl(JmsServerURL, &auth)
}
const (
	JmsServerURL    = "https://aaa.com"
	AccessKeyID     = ""
	AccessKeySecret = ""
)

type SigAuth struct {
	KeyID    string
	SecretID string
}

func (auth *SigAuth) Sign(r *http.Request) error {
	headers := []string{"(request-target)", "date"}
	signer, err := httpsig.NewRequestSigner(auth.KeyID, auth.SecretID, "hmac-sha256")
	if err != nil {
		return err
	}
	return signer.SignRequest(r, headers, nil)
}

func GetUserLoginUrl(jmsurl string, auth *SigAuth) {
	Jmsurl := jmsurl + "/api/v1/authentication/sso/login-url/"
	gmtFmt := "Mon, 02 Jan 2006 15:04:05 GMT"
	client := &http.Client{}
	form := url.Values{}
	form.Add("username", "aaa")
	form.Add("next", "/luna/")

	// 编码表单数据为字符串
	data := form.Encode()
	req, err := http.NewRequest("POST", Jmsurl, strings.NewReader(data))
	req.Header.Add("Date", time.Now().Format(gmtFmt))
	req.Header.Add("Accept", "application/json")
	req.Header.Add("X-JMS-ORG", "00000000-0000-0000-0000-000000000002")
	if err != nil {
		fmt.Println(err)
	}
	if err := auth.Sign(req); err != nil {
		fmt.Println("auth: ", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("client: ", err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("body: ", err)
	}
	json.MarshalIndent(body, "", "    ")
	fmt.Println(string(body))
}

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
可以获取到登录url

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
API URL 和 Parameters 看着没问题，

API 使用 管理员的 AK/SK 调用，参数 username 和 next。

看看 core 的日志报什么错？

**Comment by xiaoxiongxyy** [comment]
我也遇到了这个问题 请问有解决办法吗 版本3.7.1

**Comment by xiaoxiongxyy** [comment]
core的报错日志：
mework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 159, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 155, in __init__
    self._extract_accounts()
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 162, in _extract_accounts
    accounts = self.initial_data.pop('accounts', None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 569, in pop
    self._assert_mutable()
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 527, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable

**Comment by xiaoxiongxyy** [comment]
辛苦帮忙看看下 这个问题没法解

**Comment by sierfeinuoding** [comment]
我这边也没刷错误日志，我用下面那段python代码跑是可以的。。。
def get_token(jms_url,auth):
    url = jms_url + '/api/v1/authentication/sso/login-url/'
    gmt_form = '%a, %d %b %Y %H:%M:%S GMT'
    headers = {
        'Accept': 'application/json',
        'X-JMS-ORG': '00000000-0000-0000-0000-000000000002',
        'Date': datetime.datetime.utcnow().strftime(gmt_form)
    }

    data = {
        "username": "bingshen.zhou",
        "next": "/luna/"
    }

    response = requests.post(url, auth=auth, headers=headers,data=data)
    print(json.loads(response.text))


if __name__ == '__main__':
    jms_url = 'https://xxx'
    KeyID = 'bbb'
    SecretID = 'aaa'
    auth = get_auth(KeyID, SecretID)
    # get_user_info(jms_url, auth)
    get_token(jms_url, auth)

**Comment by BaiJiangJie** [comment]
那不行就用 python 调用吧，产品服务应该没问题，大概率是代码调用的问题。

最好升级到 v3 最新版本使用。

**Comment by LeeEirc** [comment]
可能需要设置下请求的 Content-Type
```
// 设置请求头，例如 Content-Type 为 application/x-www-form-urlencoded
req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
```

**Comment by sierfeinuoding** [comment]
> 可能需要设置下请求的 Content-Type
> 
> ```
> // 设置请求头，例如 Content-Type 为 application/x-www-form-urlencoded
> req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
> ```

可以获取到了
