### ISSUE TITLE
[Bug] 3.10.5 设置sftp 连接故障

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#12885]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.5
## 使用的版本类型 (必填)
- [√ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
 sftp 选择web 方式能登录成功，但是我安装了客户端，选择客户端连接的时候依旧提示去下载客户端  
![image](https://github.com/jumpserver/jumpserver/assets/13248366/be928305-6095-4e04-b7f3-286f3cd966c0)
![image](https://github.com/jumpserver/jumpserver/assets/13248366/1fcc7eba-f8c4-4c5b-a4ef-955b87b626cb)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
是不是有旧的 客户端？卸载掉之前安装过的客户端。
