### ISSUE TITLE
[Feature] 网络设备PA改密

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#12881]
* 需求描述：网络设备类型 palo alto FW 设备型号 PAVM100，IOS-11，PAVM50,IOS-8.1.PA 因为有个commit命令提交后生效，改密计划所以失败，有客户希望能够支持。
* 需要根进： 早前客户提过，前期沟通需求优先级可能不会太高，现在客户追问，领导问进度，希望安排在排期内，提高优先级
* 主要问题：
主要特点是该类型的网络设备commit后需要一分钟配置才生效，不是立即生效。会导致改密不生效，自定义改密命令也是会不生效。

**Comment by BaiJiangJie** [comment]
网络设备的账号改密是支持自定义的呀，解决不了吗？
@guoheng888
