### ISSUE TITLE
[Bug]3.10.5 rdp 会话复用导致桌面花屏

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#12884]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.5
## 使用的版本类型 (必填)
- [√ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
 3.10.5 版本 如果一个账户通过rdp登录centos的主机，另外一个账户也用他的账户登录同样的那个主机，就会发生屏闪的情况，那个账户退出连接之后，原来的那个rdp登录就恢复正常了
![image](https://github.com/jumpserver/jumpserver/assets/13248366/d39208f4-f0bb-49d8-a0c8-1b2dca2842df)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
那是 centos 对于 rdp 多开的情况支持不够好吧？

不通过 jumpserver，使用其他 rdp 客户端工具多开试试呢？

**Comment by elite8** [comment]
我现在把jumpserver 版本 从3.10.5 升级到3.10.7 之后，问题依旧。现在测试下来如果是同一个浏览器复制窗口或者重新打开同一个资产，登录3个会话都不会闪屏。但是用另外一个浏览器使用其他人的账户登录堡垒机，然后用已登录同一个资产的那个账户登录同一个资产的时候就会花屏。
同一个浏览器会话复制不花屏
![image](https://github.com/jumpserver/jumpserver/assets/13248366/1cfb6167-0cb4-4753-9b0c-18dfd4fb5c69)

浏览器隐私模式另一个账户登录堡垒机，然后用复制会话的那个账户登录资产花屏
![image](https://github.com/jumpserver/jumpserver/assets/13248366/de54ed98-fef2-4ed5-85f7-82c6298427bb)

**Comment by BaiJiangJie** [comment]
修改一下 centos 上的 rdp 配置：
![image](https://github.com/jumpserver/jumpserver/assets/32935519/f194b94d-2c55-4e0b-9fc1-45b1a5c6f20d)

修改一下 

Policy=UBDC

**Comment by elite8** [comment]
看截图需要改红框的2处吗？如果设置为killdisconnected=true 会不会杀掉已经登录的rdp会话呢.

**Comment by LeeEirc** [comment]
试一下，killdisconnected 指的是用户连接断开之后，超过一段时间后会杀掉该会话进程。

**Comment by elite8** [comment]
那用户希望关闭rdp连接之后，任务继续在后台执行呢。下次登录系统打开的窗口和任务都还在，而不是自动杀掉他的会话

**Comment by BaiJiangJie** [comment]
先不要纠结是否后台执行，先试试配置能不能解决模糊的问题。

@elite8

**Comment by elite8** [comment]
我修改过这个参数了  Policy=UBDC  ，目前重启了xrdp 服务，但是发现新的问题了。当通过堡垒机正常登录资产之后产生一个会话，通过另外一个浏览器使用同样的账户登录那个资产的时候变成了黑屏没有任何提示了。

**Comment by BaiJiangJie** [comment]
通过别的连接工具也会有问题吗？

**Comment by LeeEirc** [comment]
> 我修改过这个参数了 Policy=UBDC ，目前重启了xrdp 服务，但是发现新的问题了。当通过堡垒机正常登录资产之后产生一个会话，通过另外一个浏览器使用同样的账户登录那个资产的时候变成了黑屏没有任何提示了。

 xrdp 版本是多少，升级到最新的版本呢？

**Comment by elite8** [comment]
版本是这个  xrdp-0.9.21-1.el8.x86_64

**Comment by LeeEirc** [comment]
加交流群，远程看下。

**Comment by elite8** [comment]
群里找谁帮忙看呢

**Comment by LeeEirc** [comment]
群里发下链接，会有人联系你的。
