### ISSUE TITLE
[Feature] 希望一个资产允许多个vnc协议

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#12882]
## 注意
3.10.3版本

## 功能名称
希望一个主机资产允许多个vnc协议

## 功能描述
允许一个主机配多个vnc协议（不同的vnc端口）

## 用户故事（可选）
目前一个主机资产只允许1条vnc协议，对应1个vnc端口；实际场景中，一个服务器上可以配置多个vnc'用户，对应会有多个vnc端口；这些vnc账号希望能统一托管到此主机资产上。

## 功能要求
1. 允许一个主机配多个vnc协议（不同的vnc端口）

## 优先级
中

**Comment by BaiJiangJie** [comment]
目前不支持，未来可能会考虑。需求先留下来。
