### ISSUE TITLE
[Bug]3.10.5 版本 组件正常，但是rdp显示没有可登录账户

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#12883]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.5
## 使用的版本类型 (必填)
- [ √] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
已经给资源授权rdp连接，但是会显示rdp连接没有可用账户，组件都是正常的
![image](https://github.com/jumpserver/jumpserver/assets/13248366/1ccc59df-b0e4-4774-b63a-5efe489d730e)
![image](https://github.com/jumpserver/jumpserver/assets/13248366/2676ac21-7cc0-4a70-89ba-afb7b5f133ce)
![5O I@{QEFN}XBJ6C 1HO %H](https://github.com/jumpserver/jumpserver/assets/13248366/e3847d9d-7834-41af-992e-e841d0b0538b)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
<img width="1116" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/e2a97807-52c7-44a8-83c4-7d007eed3a66">

正常会显示一个手动账号啊。（我的是 v3.10.7）
升级到最新版本试试。

**Comment by BaiJiangJie** [comment]
<img width="1546" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/14af07f8-a74e-4f72-b01a-695562d6774f">

**Comment by elite8** [comment]
目前问题已解决
