### ISSUE TITLE
账号推送秘钥算法支持指定openssh签名

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12895]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[账号推送秘钥算法支持指定openssh签名]

## 功能描述
[资产openssh 版本为8.8，openssh8.8及以上版本默认禁用SHA-1哈希算法的RSA签名了，但是堡垒机生成的秘钥格式为RSA格式签名，导致资产推送账号为秘钥格式时失败，需要修改sshd配置文件支持ssh-rsa算法才可以]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
<img width="704" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/5a411cb5-c8a7-4fc7-9663-0e624f7e96e7">

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by yuanxixue** [comment]
如何了这个问题？

**Comment by LeeEirc** [comment]
v3.10.8 中优化。
默认 jumpserver 的账号推送支持 openssh8.8，针对旧设备，需要创建新的平台类型支持，配置 
![image](https://github.com/jumpserver/jumpserver/assets/32626707/e8252efd-c513-44e1-94ed-0b7615b9a245)

**Comment by yuanxixue** [comment]
请问v3.10.8 是会支持推送openssh算法的秘钥吗

**Comment by BaiJiangJie** [comment]
v3.10.8 会支持。

需要测试包的话找一下区域负责人。

**Comment by yuanxixue** [comment]
好的，谢谢
