### ISSUE TITLE
安装或升级中出现 WARN compose/docker-compose-xxxx.yml: `version` is obsolete

### ISSUE THREAD

**Issue by haitang5445** [jumpserver/jumpserver#12905]
## 当前使用的 JumpServer 版本 (必填)
- [x]  v3.10.7

## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] 离线安装 (下载离线包)

## 问题描述 (详细)
![Uploading image.png…]()

## 背景信息
- 操作系统：Debian12 
- 浏览器/应用版本：docker-ce-26.0.0-1 
- 其他相关环境信息：Docker Compose version v2.25.0

## 具体问题
root@xxxx:/data/jumpserver-installer-v3.10.7# ./jmsctl.sh start
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-network.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-core.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-celery.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-koko.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-lion.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-magnus.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-web.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-mariadb.yml: `version` is obsolete
WARN[0000] /data/jumpserver-installer-v3.10.7/compose/docker-compose-redis.yml: `version` is obsolete
[+] Running 8/8
 ✔ Container jms_koko    Started                                                                                                    0.7s
 ✔ Container jms_magnus  Started                                                                                                    1.1s
 ✔ Container jms_lion    Started                                                                                                    0.7s
 ✔ Container jms_redis   Running                                                                                                    0.0s
 ✔ Container jms_web     Started                                                                                                    1.0s
 ✔ Container jms_celery  Started                                                                                                    0.9s
 ✔ Container jms_core    Started                                                                                                    0.9s
 ✔ Container jms_mysql   Running

## 尝试过的解决方法
1. 停止jms
2. 删除/opt/jumpserver/
3. 重新执行 ./jmsctl.sh install
4. 状态复现

## 预期结果
.

## 我们的期望
虽然不影响使用，但是不清楚这个算不算bug

**Comment by BaiJiangJie** [comment]
升级一下 docker-compose 版本试试？

**Comment by wojiushixiaobai** [comment]
只是警告，可以忽略。如果你不需要这个提示，可以将 compose/*.yml 里面的 
```yaml
version: '2.4'
```
给注释掉或者删除这行即可
```yaml
# version: '2.4'
```
之后重启即可解决。
