### ISSUE TITLE
windows RDP 资产无法使用键盘正常输入

### ISSUE THREAD

**Issue by ZhouJun1997** [jumpserver/jumpserver#12904]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.6]
[v3.10.7]

## 使用的版本类型 (必填)
- [*] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [*] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[JumpServer 一键安版本v3.10.6，RDP成功登录，鼠标操作无异常，键盘输入导致整个RDP卡住，鼠标点击RDP窗口以外的区域后可以释放卡顿情况，中英文输入法切换可能使键盘输入成功，但是依然是卡住。
JumpServer jmctl.sh check_update 升级v3.10.7，问题依旧存在]

## 复现步骤
1. [资产列表，添加windows资产，类型：Windows，平台：Windows]
2. [资产授权，协议：所有，权限：全部]
3. [切换工作台，Web终端选择对应RDP资产点击连接]
4. [RDP成功登录，鼠标操作无异常，键盘输入导致整个RDP卡住]

## 期望行为
[RDP资产连接后键盘无法正常输入，点击RDP窗口以外区域可以释放卡顿情况]

## 实际行为
[未知原因]

## 系统环境
- 操作系统：[Windows 10 22H2 专业版]
- 浏览器/应用版本：[Googl Chrome 123.0.6312.86(正式版本)（64位）]
- 其他相关环境信息：[Windows 10 22H2 为ESXI 6.7上面的虚拟机]

## 附加信息（可选）
[]

**Comment by BaiJiangJie** [comment]
1. 不通过 jumpserver 连接使用其他工具会卡住吗？
2. 安装一下原生的 guacamole 服务配置上尝试连接一下，看看是否有卡住的情况？

**Comment by ZhouJun1997** [comment]
1.不通过 jumpserver ，使用windows自带远程桌面连接没有问题；
2.刚接触jumpserver ，我可能需要一个guacamole的入门文档。

感谢您的及时回复。

**Comment by BaiJiangJie** [comment]
guacamole google 搜索就行，部署一个容器很容易入手的。

建议使用 guacmaole 测试一下，是因为 web 方式连接 windows jumsperver 底层使用了 guacamole 的服务。

https://guacamole.apache.org/doc/gug/guacamole-docker.html

**Comment by ZhouJun1997** [comment]
额，我的问题解决了。
问题的原因：我的向日葵远程控制(sunlogin remote control)处于打开状态。关闭向日葵一切都变好了。
