### ISSUE TITLE
智能问答 GPT模型GPT-4 32K的api key限制不能超过256字符

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12906]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[在这里输入功能的名称或标题]

## 功能描述
智能问答 GPT模型GPT-4 32K的api key限制不能超过256字符，但是GPT-4 32K的模型，不能创建低于256字符的api key，希望优化

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]
<img width="1356" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/857c4cce-9c20-4f30-842a-ddce8b698bc8">

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
v3.10.8 上解除一下限制。

**Comment by Songxwn** [comment]
请问目前 3.10.7 不支持GPT4  吗？

**Comment by jym503558564** [comment]
v3.10.8已修复，请升级进行测试。
