### ISSUE TITLE
[Question] Period clean is not working

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#12901]
Hello,

I tried set up save logs, session,... for 90 days but not working
Jumpserver version is Community Edition v3.8.1

![image](https://github.com/jumpserver/jumpserver/assets/75791054/59908b37-3803-42f5-b33f-1a8fdd5d751b)
![image](https://github.com/jumpserver/jumpserver/assets/75791054/dc20b07b-e5fa-45e6-b710-ed8cf52e718e)

**Comment by BaiJiangJie** [comment]
Our initial guess is that the scheduled cleanup task did not execute.

We recommend upgrading to version v3.10.7, which addresses the occasional issue of Celery scheduled tasks not running.

**Comment by tsukiazuma** [comment]
Is there any way to fix it except upgrading?

**Comment by BaiJiangJie** [comment]
Below is a temporary fix, and restarting the service will automatically clear the modified content.

```
# Enter the Celery container
docker exec -it jms_celery bash

# Edit the connection.py file
vi /opt/py3/lib/python3.11/site-packages/redis/connection.py

# Modify the code under the def reset() method; and save and exit the file;
Change `self._lock = threading.Lock()` to `self._lock = threading.RLock()`
:wq

# Exit the container
exit

# Temporarily restart the Celery container
docker restart jms_celery

```

**Comment by tsukiazuma** [comment]
> # Edit the connection.py file
> vi /opt/py3/lib/python3.11/site-packages/redis/connection.py

I can't find it, tried find "connection" with `find / -type d -name "connection"`
![image](https://github.com/jumpserver/jumpserver/assets/75791054/0d896b8a-ec09-428e-80d9-29df8e0e0a6a)

**Comment by tsukiazuma** [comment]
When check log scheduled task, it has not been working for a while now.
And I tried restart Celery container -> see task check_password_expired work again.
I will continue to monitor other tasks and respond. Hope it will work properly again

**Comment by w940853815** [comment]
find / -name "connection.py"?

> > # Edit the connection.py file
> > vi /opt/py3/lib/python3.11/site-packages/redis/connection.py
> 
> I can't find it, tried find "connection" with `find / -type d -name "connection"` ![image](https://private-user-images.githubusercontent.com/75791054/318611188-0d896b8a-ec09-428e-80d9-29df8e0e0a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjQxNDUsIm5iZiI6MTcxMjAyMzg0NSwicGF0aCI6Ii83NTc5MTA1NC8zMTg2MTExODgtMGQ4OTZiOGEtZWMwOS00MjhlLTgwZDktMjlkZjhlMGUwYTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAyMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZTFjN2VkYWU0YmFmOTVlZjgwMzlhOTUzOTUzMjVlZjdiZWI2YzhmYzJiNzliZTRkNDkxZmY5MGRlM2VhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OUnOwtIvv9LRQ8VfKkD0KaHELXEkM9Q3nfzmSDbllV0)

**Comment by BaiJiangJie** [comment]
Sure, it is advisable to upgrade to the latest version for long-term usage.
