### ISSUE TITLE
[Bug] web终端无法连接到MongoDB v7

### ISSUE THREAD

**Issue by dsf1995cn** [jumpserver/jumpserver#12909]
## 当前使用的 JumpServer 版本 (必填)
Version v3.10.7

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
MongoDB（v7.0.7）在web终端无法连接，测试资产可连接性成功。浏览器为Chrome，使用Navicat连接MongoDB成功，说明数据库服务没有问题。
图一：web终端无法连接到MongoDB，error: Authentication failed。
![图一](https://cdn.jsdelivr.net/gh/dsf1995cn/PicHub@main/imgs/Snipaste_2024-03-30_14-19-46.png)
图二：【资产管理】--【资产列表】--【测试资产可连接性】提示succeed。
![图二](https://cdn.jsdelivr.net/gh/dsf1995cn/PicHub@main/imgs/Snipaste_2024-03-30_14-27-24.png)

**Comment by BaiJiangJie** [comment]
authSource 是默认的 admin 吗？

**Comment by dsf1995cn** [comment]
> authSource 是默认的 admin 吗？

authSource不是admin，我试着切换到admin，发现连接成功。
![图一](https://cdn.jsdelivr.net/gh/dsf1995cn/PicHub@main/imgs/Snipaste_2024-04-01_15-16-14.png)
