### ISSUE TITLE
[Feature] 针对对象存储的存储设置带路径

### ISSUE THREAD

**Issue by viazry** [jumpserver/jumpserver#12911]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
对象存储设置前缀路径

## 功能描述
例如在设置阿里云oss对象存储桶时可以配置指定到jumpserver目录中，由于配置对象存储无法定期清理旧数据，可以使用对象存储功能设置指定目录下文件的生命周期作为定期清理手段

## 功能要求
- 要求1：在配置存储设置中对象存储配置增加一栏文件目录

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
v3 版本暂时不考虑，未来 v4 版本可能会考虑。
