### ISSUE TITLE
[Bug] 误报异地登陆

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#12912]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.5

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
不停的给我发邮件提示异地登陆，但是我一直在西安。

## 复现步骤
未知

## 期望行为
不要发送邮件

## 实际行为
一直在发邮件

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
![image](https://github.com/jumpserver/jumpserver/assets/22488813/63037455-f221-45ed-ace3-b67bb229b167)

**Comment by harboor** [comment]
我配置了限制指定区域的IP登陆，今天直接不能用了。
通过其他小伙伴获取不到终端真实IP的issue，我意识到可能是配置文件有问题。
我在修改jms_web的容器内的nginx配置后，现在恢复正常了，您可以也试试看。

```
root@jms_web:/opt# vim /etc/nginx/conf.d/http_server.conf


server {
    listen 38808;
    # listen [::]:80;
    # server_name demo.jumpserver.org;  # 取消注释并自行修改成你自己的域名

    client_max_body_size 4096m;

    location / {
        proxy_pass http://localhost:51980;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        #  加上两行
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 注释一行
        #proxy_set_header X-Forwarded-For $remote_addr;
        proxy_ignore_client_abort on;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 6000;
  }
}
```

然后用Nginx测试和重新加载配置
```
root@jms_web:/opt# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@jms_web:/opt# nginx -s reload
```

**Comment by BaiJiangJie** [comment]
是否异地就是根据最近两次登录城市是否一致判断的，看一下你登录日志中的最近两次登录城市一样吗？
@rty813

**Comment by rty813** [comment]
@BaiJiangJie 邮件时间是4/1 09:07，查看登录日志显示如下：
![image](https://github.com/jumpserver/jumpserver/assets/22488813/267ab71c-7046-461f-a75c-bd041589ebb3)

我通过百度IP查询，查到这个IP也属于西安：
![image](https://github.com/jumpserver/jumpserver/assets/22488813/da9c898f-853f-4bc6-bd15-ce066e68da47)

所以可能是jumpserver判断登陆城市为未知的情况下，会误报

**Comment by rty813** [comment]
除此之外，还有误判定登陆城市为延安的，但是通过百度IP查询，也是处于西安市。而且我确认我只在西安登陆过。
![image](https://github.com/jumpserver/jumpserver/assets/22488813/eb7b6c39-0c68-487b-81dc-c2f8de7c8dd9)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/88304f28-0561-4764-8c5a-0297a96aa119)

**Comment by BaiJiangJie** [comment]
不是误判，是使用的IP解析库不一样。

<img width="909" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/362d7848-06aa-4293-ba06-b426fd5f49c8">

那就是解析IP的问题，解析到的城市不一样，所以提示告警。

**Comment by BaiJiangJie** [comment]
IP 解析库目前更新不了。

如果想禁用异地登录提醒功能，下面系统设置中关闭。
<img width="1443" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/dadd682d-8463-432c-9313-5ef1637a5100">

**Comment by rty813** [comment]
建议后面可以考虑换个库优化一下，从我自身角度考虑，我没有去过其他城市，始终在西安，但是不停的收到邮件报警，进而导致我只能关闭这个功能，这个功能对我们来说就处于不可用的状态了。

**Comment by rty813** [comment]
除此之外，如果本次登录城市为“未知”，那么下次登录时理论上是否不应该再发送邮件提醒了呢
