### ISSUE TITLE
[Bug] Bug 标题  3.10.7版本 鼠标指针不变化形状

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#12915]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.7
## 使用的版本类型 (必填)
- [√ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
通过web页面登录 luna 的主机资源，当通过rdp方式成功登录centos系统之后，打开gvim编辑器，输入字符串之后， 在文本框中‘I’ 这样的提示符状态不会闪烁。之前的2.28.8版本打开gvim光标会闪烁的。并且之前的版本打开一些图形化的工具时候，本来可以将将鼠标放在状态栏之后，会将鼠标箭头图形变成 “I”型，新版本则还是鼠标的箭头样式。请问这个问题有解决方法嘛。
## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]
![image](https://github.com/jumpserver/jumpserver/assets/13248366/67e523a2-38f5-4f05-8e9e-1716724eee79)

![image](https://github.com/jumpserver/jumpserver/assets/13248366/cc05e707-9408-42fe-af2e-4514704d4b20)

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by elite8** [comment]
我这上不了这个网站，这个问题能在3.10.8 版本中 优化好嘛？
![image](https://github.com/jumpserver/jumpserver/assets/13248366/66da81a4-e4cf-434a-80a7-0b1261d7ef5e)

**Comment by BaiJiangJie** [comment]
不确定是什么问题，没有办法优化。

**Comment by BaiJiangJie** [comment]
你要试试原生的 guacamole 服务会不会有类似的问题。
