### ISSUE TITLE
[Question] 使用Bitwarden保存安全密钥时服务器报错

### ISSUE THREAD

**Issue by BilikoX** [jumpserver/jumpserver#12910]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [x] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
使用Bitwarden保存安全密钥时服务器报错

## 背景信息
- 操作系统：[Windows 11]
- 浏览器/应用版本：[Chrome 版本 123.0.6312.86（正式版本） （64 位）]
- 其他相关环境信息：[Bitwarden 版本2024.3.0，浏览器插件版本2024.2.1]

## 具体问题
passkey设置
![](https://github.com/jumpserver/jumpserver/assets/15882517/f07c1e17-d213-4c8d-bc76-2bdf8aff21a2)
操作步骤
![](https://github.com/jumpserver/jumpserver/assets/15882517/34cdad4a-28f4-479a-8cdc-d9f92236afc3)
![](https://github.com/jumpserver/jumpserver/assets/15882517/d7b628db-5511-455d-b228-53a59055b710)
Bitwarden上密钥已保存，但是jumpserver浏览器报错。
## 尝试过的解决方法
设置DEBUG=true,LOG_LEVEL=DEBUG,控制台日志无任何输出.
![](https://github.com/jumpserver/jumpserver/assets/15882517/6e98c989-7367-43d1-a8ff-62cfd037d328)

## 预期结果
[正常保存通行密钥]

## 我们的期望

不知道是否我操作有问题？望解答

**Comment by BaiJiangJie** [comment]
初步判断是 fido2 的库对 Bitwarden 注册密钥时传的参数不支持。

**Comment by 0pera** [comment]
> 初步判断是 fido2 的库对 Bitwarden 注册密钥时传的参数不支持。

这个后续有修复吗？或者有没有修复计划？我目前跑着V4.6.0，还是一样的问题。
