### ISSUE TITLE
使用guacamole盘下载目录出错

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#12914]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[V3.10.7]

## 使用的版本类型 (必填)
- [ ] 企业版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
[使用挂载盘下载目录，在 Windows 机器上直接复制一个多层级的目录，大小大约两个G，文件下载到一半的时候会报错 websocket错误，接着机器就会卡住，下载停止，浏览器下载栏会显示无法下载]

## 复现步骤
1. [粘贴下载的目录到 Download 下] 
<img width="431" alt="3a629729efca0fb0342d8a0f2225436" src="https://github.com/jumpserver/jumpserver/assets/136306850/9bb87443-4989-4778-b592-639b44636feb">

2. [下载过程]
<img width="670" alt="425d117164fd0d078588dfe344c22d8" src="https://github.com/jumpserver/jumpserver/assets/136306850/5308c46c-927f-4c04-a8c6-42b016830a21">

3. [结果]
<img width="643" alt="809e43e6348b8e97dd935a8a78d6670" src="https://github.com/jumpserver/jumpserver/assets/136306850/aa0f950b-1920-4278-be47-640f743bd104">

## 期望行为
[希望目录下载这个操作如果不能用的话，可以禁用掉，或者可以下载成功]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[Windows server 2019 standard]
- 浏览器/应用版本：[Microsoft Edge 版本 122.0.2365.92 (正式版本) (64 位)]

## 附加信息（可选）
[
![image](https://github.com/jumpserver/jumpserver/assets/136306850/d797866d-91bc-4349-a856-53ed30936732)
]

**Comment by BaiJiangJie** [comment]
不要直接拖到 download 文件夹，先拖到共享盘中，再使用文件管理下载。

**Comment by 1223ruiyin** [comment]
大佬，先把文件夹拖到共享盘，再拖 download 下载的话，下载会是下面的情况
![image](https://github.com/jumpserver/jumpserver/assets/136306850/269aaeb5-2e64-434e-a6ce-84d99da0d996)
我试了小一点的目录是可以直接下载下来的，大点的目录就不行，下载到一半就会断掉，文件大小没有超过限制4G大小，是不支持目录的直接下载吗

**Comment by BaiJiangJie** [comment]
直接下载会对网络要求比较高，容易出错。相当于一次性完成了两步。

不支持文件夹的下载，压缩一下。

**Comment by 1223ruiyin** [comment]
好的，明白了，感谢大佬解答
