### ISSUE TITLE
[Bug] v3.10.7新版本消息通知邮件配置异常错误

### ISSUE THREAD

**Issue by szalexs** [jumpserver/jumpserver#12917]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [ √] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [√ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[缘由：在上一个使用版本v3.10.1中，是不支持Exchange模式发信的，所以未能验证]
近日，针对JumpServer 3.10.1=upgrade=> 3.10.7，实际环境是使用的在线安装的docker环境。
因为消息通知模块有支持Exchange，所以我们打算验证并使用，在之前的模式中都是在本地网内匿名SMTP发信，觉得不是特别合规。
我们新增了邮件系统专用帐号，先变更了SMTP发信帐号并测试，可以正常收信（旧模式匿名，不写SMTP密码）。
然后我们调整到Exchange模式，并输入了账号的密码，直接出现报错（经过单独访问验证是正确的）‘’
最后，我们打算放弃，再改回之前SMTP的匿名发信模式，发现也已经无法使用，点击重置后再重新配置也是一样出现错误。
至此，邮件通知功能已经无法使用。

## 复现步骤
1. [调整了一下匿名发信的账号为真实帐号测试成功（之前帐号一直用的虚拟的，本地服务器允许本地可靠来源不验证）]
2. [配置Exchange发信帐号配置，测试失败报错，Invalid URL 'szmail.tsmtml.com': No scheme supplied. Perhaps you meant https://szmail.******.com?  附图]
3. [调整回原来的SMTP匿名本地发信，功能失效，使用之前的配置错误相同，No suitable authentication method found. 附图]

## 期望行为
[1、通过Exchange发信，收信者可确认发信来源是邮件系统组织的名称详情，增加可信度]
[2、通过Exchange发信失败时，回归到SMTP匿名 OR 不匿名，均无法发信，已经无法使用邮件通知]

## 实际行为
[实际上，貌似发生了认证方式的类型和代码识别出错，因为后来我们用其他系统平台的Exchange模式在使用中的账号测试均相同的错误]

## 系统环境
- 操作系统：[例如：Windows 10]
- 浏览器/应用版本：[Google Chrome/109.0.5414.168]
- 其他相关环境信息：[无]

## 附加信息（可选）
[变更Exchange前，先变更账号测试一次SMTP的匿名发信正常]
![image](https://github.com/jumpserver/jumpserver/assets/33921287/e60f35ca-f003-4894-af5b-5083d80c8b0b)

[变更Exchange模式，配置正式的账号，测试报错]
![image](https://github.com/jumpserver/jumpserver/assets/33921287/0350fb57-363b-4af8-affe-99f4da78bf54)

[回归SMTP发信模式，配置匿名 OR 非匿名账号，测试发生报错，至此，邮件通知已经无法使用]
![image](https://github.com/jumpserver/jumpserver/assets/33921287/0f208fbb-22bf-411c-ba3f-b21444fc1a0b)

**Comment by BaiJiangJie** [comment]
也就是说现在使用之前的 SMTP 配置也不能正常发送邮件了？

**Comment by szalexs** [comment]
> 也就是说现在使用之前的 SMTP 配置也不能正常发送邮件了？

对的，不管是匿名 OR 非匿名，，都是报错：No suitable authentication method found.

另外，我们本地还有1套jumpserver测试环境，一样是docker在线安装的v3.10.7最新版，使用相同的帐号和方式是正常发送的。（未改Exchange模式，排除邮件系统问题）

**Comment by szalexs** [comment]
出问题的是我们内部在线上使用的环境，，早知道在测试环境先测试的，因为是邮件功能，忘记了谨慎。

**Comment by BaiJiangJie** [comment]
方便远程看一下吗？
后台我去帮你查看一下所有的 EMAIL 配置，你核对一下。

**Comment by szalexs** [comment]
> 方便远程看一下吗？ 后台我去帮你查看一下所有的 EMAIL 配置，你核对一下。

可以的，请问怎么联系？我WeChat：TYBHKTKA

**Comment by BaiJiangJie** [comment]
好的，我加你。

**Comment by BaiJiangJie** [comment]
EMAIL 账号密码没有清空导致的。
