### ISSUE TITLE
[Bug] 使用本地客户端连接Redis，magnus组件有报错，修改key值保存后刷新再看实际没改成功。

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#12918]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [√ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[使用本地客户端连接Redis，magnus组件报错“ErrorDetail(string='不允许是用空字符串。'”，修改key值保存后刷新再看实际没改成功]
Redis版本是：5.0.5

## 复现步骤
1. [连接Redis的时候，选择DB连接向导]
2. [打开本地RESP客户端连接Redis，可以连接成功看到数据]
3. [修改key值后保存，刷新再看没有修改成功]
连接Redis后magnus报错截图：
![05cfcc3d1a441dd944f4d7b72e04921](https://github.com/jumpserver/jumpserver/assets/104493699/466b48ec-135a-42c7-8341-7396df526904)
Redis修改的内容：
![9e1dd2dc238fef00c75793374dfe9c3](https://github.com/jumpserver/jumpserver/assets/104493699/7f27780e-5d6b-42d9-a235-8ce5bc7e96a8)

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
Magnus 的报错是因为 命令上传失败了。

修改值提示成功了吗？

**Comment by shimengqiao** [comment]
没有提示成功，在客户端上修改后，没有任何提示。

**Comment by BaiJiangJie** [comment]
这个 value 看起来很大，修改其他的key对应的value可以成功吗？还是所有都不成功。

**Comment by shimengqiao** [comment]
是修改比较大的value会复现，大概哪个版本会修复？

**Comment by BaiJiangJie** [comment]
等复现后排期处理，这个问题不太好搞。

**Comment by jym503558564** [comment]
1.v3.10.8，更新redis value 长字符串失败的问题已修复，请升级进行体验。
2.重命名key失败的问题，各种客户端表现不一。目前有几个客户端进行验证是可以修改成功的。个别客户端会修改key失败。可使用比较常见的客户端进行测试。
