### ISSUE TITLE
[Bug] Bug 3.10.7登录页面 1天内自动登录无法勾选

### ISSUE THREAD

**Issue by OrangeCanyon** [jumpserver/jumpserver#12916]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.10.7]

## 使用的版本类型 (必填)
- 社区版

## 版本安装方式 (必填)
- 在线安装 (一键命令)

## Bug 描述 (详细)
[登录页面无法勾选1天内自动登录]

## 复现步骤
1. [完成3.10.7的升级操作]
2. [打开登录页面]
3. [勾选1天内自动登录]

## 期望行为
[能够正常勾选1天内自动登录]

## 实际行为
[勾选框灰色无法选中]

## 系统环境
- 操作系统：[Ubuntu22.04]
- 浏览器/应用版本：[Chrome版本 123.0.6312.86（正式版本） （64 位）]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[![image](https://github.com/jumpserver/jumpserver/assets/99263989/c5672f24-929c-4c31-bb40-11abae0ecfb5)]

**Comment by BaiJiangJie** [comment]
v3.10.8 会优化。
