### ISSUE TITLE
[Bug] 用户筛选功能异常

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12929]
## 注意
**JumpServer 版本 3.10.7-企业版

## 版本安装方式 (必填)
 离线安装 (下载离线包)

## Bug 描述 (详细)
用户筛选功能异常，筛选组织管理员会把组织用户也筛选出来。

## 复现步骤
1.筛选组织管理员
![image](https://github.com/jumpserver/jumpserver/assets/43403764/53e9fa9f-57d8-47aa-999c-fb93d692a25b)

2、确认该用户只有一个角色，为组织用户

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/12934/files

已修复，v3.10.8 发布。
