### ISSUE TITLE
[Bug] 使用标签筛选主机资源，当一个标签名有两个值时，筛选全部无法展示资源

### ISSUE THREAD

**Issue by notevery** [jumpserver/jumpserver#12926]
## 当前使用的 JumpServer 版本 (必填)
v3.10.7

## 使用的版本类型 (必填)
- 社区版

## 版本安装方式 (必填)
- 1Panel 安装

## Bug 描述 (详细)
我使用 `一个标签两个标签值（node:22  和 node:22022）` 来 分别标识ssh端口在22的主机和ssh端口在22022的主机；
标签筛选 `node:22` 或者 `node:22022` 单独一个标签筛选都能筛选出对应的主机
标签筛选 `node:所有`  不能筛选出主机

## 复现步骤
1. 添加两台主机，一个打标签 `node:22` ，另一个打标签 `node:22022`
2. 标签筛选 `node:22` 或者 `node:22022` 单独一个标签筛选都能筛选出对应的主机
3. 标签筛选 `node:所有`  不能筛选出主机

## 期望行为
标签筛选 `node:所有`  可以筛选出主机

## 实际行为
`所有` 这个标签值，不能筛选
![image](https://github.com/jumpserver/jumpserver/assets/12843847/874db47b-fa48-4d81-8b0b-f0c8fea277fb)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/e75ab595-7904-441f-9bf4-aadd1a1ce13f)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/a1e3f73e-1e0f-4bcf-892b-e67f8450637a)

## 系统环境
- 操作系统：Windows 11
- 浏览器/应用版本：Microsoft Edge 版本 123.0.2420.65 (正式版本) (64 位)
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
所有指的是 同时包含所有标签的资产，不是 OR 的关系。

**Comment by notevery** [comment]
> 所有指的是 同时包含所有标签的资产，不是 OR 的关系。

确实标签只有 and逻辑，但是 and 也有bug，同一台主机有两个标签 host:linux , mysql:3306 ，输入两个标签筛选不出来
![image](https://github.com/jumpserver/jumpserver/assets/12843847/4f60a1e1-3292-4337-82c3-2f40d62b8e14)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/cad74c5b-a26b-4b67-87af-32cc8e8e6f68)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/52932121-f9ab-46f8-8f0a-5e4dd0c154d2)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/9e04cd44-372a-4181-baed-0ad22c9b94d5)

我期望的标签逻辑：左侧的复选框是 and，右侧的复选框是 or ; 能不能请产品经理评估一下子。
![image](https://github.com/jumpserver/jumpserver/assets/12843847/2d8bd1c7-f58a-4e9f-942f-ab625708b1cc)

**Comment by notevery** [comment]
@BaiJiangJie 
`所有` 这个标签 的 and 逻辑也有 bug
![image](https://github.com/jumpserver/jumpserver/assets/12843847/8a37dc13-071e-4d19-8198-400a2083dabc)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/e6ce57c1-de96-4eb8-b616-1b7b3659bab8)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/20010bc7-1209-4b33-bf9b-906df2c19736)
