### ISSUE TITLE
ladp服务重启登录验证失败

### ISSUE THREAD

**Issue by navyaijm2017** [jumpserver/jumpserver#1292]
[简述你的问题]

##### 使用版本
1.0.0.2

##### 问题复现步骤
ladp重启，jump通过ldap验证就不成功了，但是新用户是可以的，新用户第一次用ldap账号登录jump，会自动创建用户，老用户验证失败，但是我通过界面上把老用户删掉，用ldap的账号密码重新登录，理论上这样就是新用户了吧，但是还是登录不了
##### 其他

[注:] 完成后请关闭 issue

**Comment by navyaijm2017** [comment]
已经找到问题，是redis里面存了ldap用户的信息，没有设置过期时间，当ldap人员信息有变化时，就无法登录了，把redis的信息清理掉就可以了，建议redis的信息设置过期时间

**Comment by navyaijm2017** [comment]
redis里面的db4， key如下：
":1:django_auth_ldap.user_dn.xxxx"

**Comment by ibuler** [comment]
已修复
