### ISSUE TITLE
[Question] 使用哪个Dockerfile构建JMS_ALL镜像？

### ISSUE THREAD

**Issue by artemus717** [jumpserver/jumpserver#12927]
## 当前使用的 JumpServer 版本 (必填)
v2.28.21

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] Kubernetes 安装

## 问题描述 (详细)
我想使用Dockerfile构建v2.28.21的all in one镜像。目前使用的是本工程内的[Dockerfile-ce](https://github.com/jumpserver/jumpserver/blob/v2.28.21/Dockerfile-ce)
构建出来的镜像缺少Lina组件。单独构建Lina组件后，又发现Lina容器无法访问Jumpserver容器内的静态文件。

请问应该使用哪个Dockerfile构建JMS_ALL镜像？

**Comment by BaiJiangJie** [comment]
使用这个 https://github.com/jumpserver/Dockerfile

**Comment by artemus717** [comment]
好的，谢谢，我试一下。我看这个2.x的最高只有2.5.3，不知道2.28.21能构建出来不。
