### ISSUE TITLE
[Question] JumpserverV3.7.1 利用模版创建的用户 推送不到资产上 提示skipping: no hosts matched

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#12932]
![image](https://github.com/jumpserver/jumpserver/assets/85990572/4ae9d546-7f63-4864-8822-41dc9b730994)
辛苦看一下 根据模版创建了一个用户 无法推送到资产上 一直提示skipping: no hosts matched

**Comment by BaiJiangJie** [comment]
版本有点旧，升级到最新版本试试。

**Comment by xiaoxiongxyy** [comment]
> 版本有点旧，升级到最新版本试试。

这是版本问题吗？之前推送也没有问题呀 就是从那天开始现在都推送不上去
推送必须使用root用户推送吗？

**Comment by BaiJiangJie** [comment]
不一定是 root，其他有权限的用户也行。

**Comment by BaiJiangJie** [comment]
推送的是什么类型的资产？

**Comment by xiaoxiongxyy** [comment]
推送的账号 往上推送一个test用户 但是账号列表里没有root用户 这能推送上去吗？

**Comment by xiaoxiongxyy** [comment]
是不是必须需要一个特权账号 才能往上进行推送呢？

**Comment by BaiJiangJie** [comment]
是的，必须有一个。

**Comment by xiaoxiongxyy** [comment]
> 是的，必须有一个。

特权用户可以自己推送自己吗
