### ISSUE TITLE
[Feature] 建议在资产列表上方添加一个上下页切换

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12931]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
在资产列表上方添加一个上下页切换

## 功能描述
在资产列表上方添加一个上下页切换，用户上下页切换不用每次都划到最底部。
![image](https://github.com/jumpserver/jumpserver/assets/43403764/4aae9d3a-8a95-46b8-8c3e-d47c2aa7b6a3)

## 用户故事（可选）
如果每页显示100条，每次切换上下页鼠标需要滑动到最下方，如果在上方添加一个上下页切换，无论是滑动到底部和上部都能实现上下页切换，查找资产会很方便。

## 功能要求
在资产列表上方新增一个上下页切换

**Comment by BaiJiangJie** [comment]
当前版本优化改动比较大，后面有重大 UI 重构的时候再考虑优化。
