### ISSUE TITLE
[Feature] 资产树可以设置自定义展示层级

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#12930]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
资产树可以设置自定义展示层级

## 功能描述
每次打开资产树只显示一级，下级节点每次都需要手动点开，可以自定义显示的层级
![image](https://github.com/jumpserver/jumpserver/assets/43403764/7581974b-4a40-4810-a987-de812ff9dd90)

## 用户故事（可选）
下级目录如果是一两级还行，层级多的话每次打开都需要点击一遍才能找到下级目录资产，用户操作不是很友好。

## 功能要求
显示的层级可以自定义或者默认展开多级

**Comment by BaiJiangJie** [comment]
考虑性能问题，暂时不支持。
