### ISSUE TITLE
[Question]命令过滤‘rm’在web终端生效，但是我用xshell登录进去 还是可以用rm命令

### ISSUE THREAD

**Issue by javaXiaoHan** [jumpserver/jumpserver#12943]
## 注意
**请描述您的问题.** <br>
命令过滤‘rm’在web终端生效，但是我用xshell登录进去 还是可以用rm命令
![image](https://github.com/jumpserver/jumpserver/assets/32090060/4c614ea4-c192-41d5-a9a6-9d0a6aa86052)
![image](https://github.com/jumpserver/jumpserver/assets/32090060/4fa17305-63fa-49ca-ad8d-4ae6fc22af0e)

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
v3.10.7

## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)

## 我们的期望
[描述你希望我们提供的帮助或支持]
怎么让指令过滤 在Xshell 客户端也生效

**Comment by BaiJiangJie** [comment]
xshell 端是手动输入的吗？还是粘贴、上下键输入的？

**Comment by javaXiaoHan** [comment]
> xshell 端是手动输入的吗？还是粘贴、上下键输入的？

用账密登录Xshell客户端，进入到目录，手动输入rm -rf xx.log 可以直接删除 没有过滤

**Comment by jym503558564** [comment]
无法复现

**Comment by javaXiaoHan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32090060/863faed2-ee2f-4b44-bfa1-ce014d00d463)

**Comment by javaXiaoHan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32090060/6e4b40ae-1a52-4349-8713-53e9b2228b69)
这是web终端的提示

**Comment by javaXiaoHan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32090060/aaca6c34-834f-4d4b-8bd3-8019b89f04ea)
![image](https://github.com/jumpserver/jumpserver/assets/32090060/d562decc-df49-48cc-a505-f857860a12b3)
同一个ip的服务器

**Comment by LeeEirc** [comment]
查看下是否是同一个资产？登陆资产是通过 koko 的 2222 端口吗？

**Comment by javaXiaoHan** [comment]
> 查看下是否是同一个资产？登陆资产是通过 koko 的 2222 端口吗？

是同一个资产。koko端口是什么意思。Xshell是通过22端口访问的

**Comment by javaXiaoHan** [comment]
> 查看下是否是同一个资产？登陆资产是通过 koko 的 2222 端口吗？

是直连Xshell 的

**Comment by BaiJiangJie** [comment]
xshell 使用 22 端口，那你是直接连到资产里面了？没有通过koko吗？

**Comment by javaXiaoHan** [comment]
> xshell 使用 22 端口，那你是直接连到资产里面了？没有通过koko吗？

xshell怎么通过koko链接资产

**Comment by BaiJiangJie** [comment]
ssh admin@JUMPSERVER-HOST -p 2222 

密码输入 admin 用户的密码，进去之后选择连接。

你上面的连接相当于都没通过 jumpserver 那肯定不行啊。

**Comment by javaXiaoHan** [comment]
> ssh admin@JUMPSERVER-HOST -p 2222
> 
> 密码输入 admin 用户的密码，进去之后选择连接。
> 
> 你上面的连接相当于都没通过 jumpserver 那肯定不行啊。
谢谢。我下载了jumpserver客户端 ，在这里面跳转xhshell！
