### ISSUE TITLE
[Question] 该如何贡献并支持多语言？（以中文繁体为例）（v3）

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#12947]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [ ] 社区版
- [x] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [x] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在这里描述你遇到的问题]
请问该如何支持繁体？是否将下述文件翻译好后提交 PR？
1、jumpserver/apps/locale/zh/LC_MESSAGES/django.po
2、jumpserver/apps/locale/zh/LC_MESSAGES/djangojs.po
3、luna/src/assets/i18n/zh.json
4、lina/src/i18n/langs/zh.json
5、koko/locale/zh_CN/LC_MESSAGES/koko.po
6、koko/ui/src/i18n/langs/zh.json
7、installer/locale/zh_CN/LC_MESSAGES/jumpserver-installer.po
8、lion/ui/src/i18n/lang/cn.js🌲
9、chen/frontend/src/i18n/lang/zh-CN.js🌲

**Comment by BaiJiangJie** [comment]
是的，对应着支持 1-7 翻译文件即可，注意文件的命名符合规范，完成后提交 pr 到各仓库的 dev 分支。

研发团队支持 8、9。

研发团队根据支持的语言增加页面操作的选项。

**Comment by BaiJiangJie** [comment]
- [ ] - 1、jumpserver/apps/locale/zh/LC_MESSAGES/django.po
- [ ] - 2、jumpserver/apps/locale/zh/LC_MESSAGES/djangojs.po
- [ ] - 3、luna/src/assets/i18n/zh.json
- [ ] - 4、lina/src/i18n/langs/zh.json
- [ ] - 5、koko/locale/zh_CN/LC_MESSAGES/koko.po
- [ ] - 6、koko/ui/src/i18n/langs/zh.json
- [ ] - 7、installer/locale/zh_CN/LC_MESSAGES/jumpserver-installer.po

- [ ] - 8、lion/ui/src/i18n/lang/cn.js🌲 @LeeEirc 
- [ ] - 9、chen/frontend/src/i18n/lang/zh-CN.js🌲 @Aaron3S

**Comment by elf168** [comment]
已經提交上去你們確認看看

**Comment by BaiJiangJie** [comment]
修改的不对，以 jumpserver/jumpserver 仓库为例，当前 zh 目录下的是中文简体，如果要增加中文繁体不应该直接修改 zh 目录下的 .po 文件，应该创建一个新的目录 zh_hant 然后在目录下面对应着翻译内容。

**Comment by BaiJiangJie** [comment]
> @hzhfit2cloud 中文繁体完成后，打勾并附上 pr 链接。
> 
> * [ ]  1、jumpserver/apps/locale/zh_Hant/LC_MESSAGES/django.po
> * [ ]  2、jumpserver/apps/locale/zh_Hant/LC_MESSAGES/djangojs.po
> * [ ]  3、luna/src/assets/i18n/zh_Hant.json
> * [ ]  4、lina/src/i18n/langs/zh_Hant.json
> * [ ]  6、koko/ui/src/i18n/langs/zh_Hant.json
> * [ ]  5、koko/locale/zh_Hant/LC_MESSAGES/koko.po
> * [ ]  7、installer/locale/zh_Hant/LC_MESSAGES/jumpserver-installer.po
> * [ ]  8、lion/ui/src/i18n/lang/zh_Hant.js🌲 @feng626
> * [ ]  9、chen/frontend/src/i18n/lang/zh-Hant.js🌲 @feng626

按着这个目录来就行。

**Comment by BaiJiangJie** [comment]
core 和 lina 项目中的选项加上。 @feng626

**Comment by hzhfit2cloud** [comment]
> > @hzhfit2cloud 中文繁体完成后，打勾并附上 pr 链接。
> > 
> > * [1 ]   1、jumpserver/apps/locale/zh_Hant/LC_MESSAGES/django.po
PR：https://github.com/jumpserver/jumpserver/pull/12959
> > * [1 ]   2、jumpserver/apps/locale/zh_Hant/LC_MESSAGES/djangojs.po
PR：https://github.com/jumpserver/jumpserver/pull/12959
> > * [1 ]   3、luna/src/assets/i18n/zh_Hant.json
PR：https://github.com/jumpserver/luna/pull/1077
> > * [1 ]   4、lina/src/i18n/langs/zh_Hant.json
PR：https://github.com/jumpserver/lina/pull/3827
> > * [1 ]   6、koko/ui/src/i18n/langs/zh_Hant.json
PR：https://github.com/jumpserver/koko/pull/1318
> > * [1 ]   5、koko/locale/zh_Hant/LC_MESSAGES/koko.po
PR：https://github.com/jumpserver/koko/pull/1318
> > * [1 ]   7、installer/locale/zh_Hant/LC_MESSAGES/jumpserver-installer.po
https://github.com/jumpserver/installer/pull/405

**Comment by BaiJiangJie** [comment]
已合并，v3.10.8 上线。
