### ISSUE TITLE
[Bug] 标签筛选主机，只能单个标签，两个及以上标签无法筛选

### ISSUE THREAD

**Issue by notevery** [jumpserver/jumpserver#12944]
## 当前使用的 JumpServer 版本 (必填)
v3.10.7

## 使用的版本类型 (必填)
-  社区版

## 版本安装方式 (必填)
- 1Panel 安装

## Bug 描述 (详细)
有一台主机上有两个标签, 但是使用两个标签无法筛选出这台主机。
![image](https://github.com/jumpserver/jumpserver/assets/12843847/0e63b0c4-ae9f-42d9-a976-022c5932cf3e)
![image](https://github.com/jumpserver/jumpserver/assets/12843847/1534f452-c492-426e-a9ef-97f9479b3dc7)

![image](https://github.com/jumpserver/jumpserver/assets/12843847/8efced22-00b7-465d-a64e-59e51277b474)

## 复现步骤
1.  将一台主机，打上两个标签 `node:22` 和 `node:22022`
2. 分别使用 node:22 ，node:22022 能筛选到正确主机
3. 同时使用 node:22  和 node:22022 两个标签就筛选不到了

## 期望行为
希望能两个以上标签筛选，定位到符合多个标签的主机

## 实际行为
根本不支持两个及以上标签，这基本上意味着标签系统不能用

## 系统环境
- 操作系统：Windows 11
- 浏览器/应用版本：edge

**Comment by BaiJiangJie** [comment]
是的，目前搜索确实有问题。

**Comment by BaiJiangJie** [comment]
v3.10.8 已修复。

修复后的逻辑是：标签同 key 之间的条件是“或”的关系，不同key之间是“且”的关系，多个 key 的条件就是组合的“或”“且”的关系。

上线后体验一下。
