### ISSUE TITLE
[Bug] 远程发布机删除后，还一直发布离线报警

### ISSUE THREAD

**Issue by leedavid** [jumpserver/jumpserver#12952]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[V3.10.7]

## 使用的版本类型 (必填)
 社区版

## 版本安装方式 (必填)
在线安装 (一键命令)

## Bug 描述 (详细)

，我把远程发布机 10.20.0.9，删除了，只保留了一台，10.20.8.44，但jumpersever 还一直报警 10.20.0.9 离线， 请问我如何手工删除。。

## 复现步骤
增加一台远程发布机 10.20.0.9
删除一台远程发布机 10.20.0.9

## 期望行为
不报警 10.20.0.9 

## 实际行为
每1小时就报警 10.20.0.9  离线 

## 系统环境
- 操作系统：[ubuntu 22.04lts]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
系统设置-组件管理-组件列表找到对应类型为 tinker 的终端，删掉就行了。

**Comment by leedavid** [comment]
非常感谢，已解决。
