### ISSUE TITLE
1.2.1-2版本使用后的两个感受

### ISSUE THREAD

**Issue by dongbozhou** [jumpserver/jumpserver#1295]
使用版本
1.2.1-2

第一个问题，登录到跳板机后，ID 、Hostname 、IP 、 LoginAs 、Comment 这几个字段隔的太近了，如果我Hostname长度相差比较大，就会显示的不整齐

第二个问题，我用的ssh工具是securecrt，以前还使用ossh等命令登录服务器的时候可以通过设置“登录动作”将要登录的服务信息保存在crt中，避免我每次去搜索主机名后来登录服务器，而且可以批量操作。但是现在的版本无法实现，保存到“登录动作”中的主机信息不会在登录跳板机后跳转到后端服务器

![image](https://user-images.githubusercontent.com/26269393/39660425-50713030-5071-11e8-950b-7372864fefb8.png)

**Comment by yaoluoye** [comment]
设定hostname长度上限
取出现有hostname长度，根据现有hostname 的最大长度来合理显示，可以制定几个显示策略
对超过长度上限的hostname可以截断显示

**Comment by dongbozhou** [comment]
hostname长度可以设定一个上限，ip距离hostname第一位的间距就可以固定了

**Comment by ibuler** [comment]
hostname整齐问题已经解决，expect现在也可用了
