### ISSUE TITLE
[Bug] 非管理员用户访问数据库失败提示1045 - backend auth error auth failed

### ISSUE THREAD

**Issue by laikinWong** [jumpserver/jumpserver#12962]
## 当前使用的 JumpServer 版本 (必填)
v3.10.5

## 使用的版本类型 (必填)
JumpServer 社区版

## Bug 描述 (详细)
-联通云mysql数据库版本5.7，该数据库下有管理员账号以及普通账号
-在堡垒机使用普通账号进行访问时，选择客户端-DB连接向导，使用向导信息在navicat进行登录时报错1045 - backend auth error auth failed，使用管理员账号却不会报错能够正常登录
-测试账号连接数据库时，两个账号都显示成功连接，但实际普通账号不能访问

## 复现步骤
1. 选择数据库资产
2. 选择客户端-DB连接向导方式登录
3.打开navicat工具，填写对应的信息

## 期望行为
数据库访问成功

## 实际行为
报错1045 - backend auth error auth failed
截图
![微信图片_20240409151935](https://github.com/jumpserver/jumpserver/assets/49440719/675b9240-883a-4b62-84f0-fb63724f7312)
![微信截图_20240409152756](https://github.com/jumpserver/jumpserver/assets/49440719/c4b222d0-29fc-4d6d-a959-baf415dedf9c)
![微信图片_20240409151945](https://github.com/jumpserver/jumpserver/assets/49440719/c1ec9881-7fd6-4f02-b9ad-31dabac19fe5)

**Comment by laikinWong** [comment]
![微信截图_20240409152756](https://github.com/jumpserver/jumpserver/assets/49440719/199bbab7-096b-4c9c-a066-9f07ae36ccd1)
![微信图片_20240409153016](https://github.com/jumpserver/jumpserver/assets/49440719/400a69b1-2808-47a8-9da6-297659a0e49d)
测试通过远程应用可以连接成功，没办法定位到问题

**Comment by BaiJiangJie** [comment]
你这样操作一下，将这个数据库资产的平台，修改成 MariaDB 试试是否可以认证成功？

**Comment by BaiJiangJie** [comment]
换一下其他云平台的数据库试试，应该是协议匹配问题。

**Comment by jym503558564** [comment]
无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/79148730-e059-47bd-9916-34cc6d8b977e)

**Comment by fengmikaelson** [comment]
遇到同样的问题了。。。
