### ISSUE TITLE
需求：普通用户登陆可对资产个人备注

### ISSUE THREAD

**Issue by WilliamGuozi** [jumpserver/jumpserver#1296]
### [需求]
普通用户添加一个字段叫个人备注什么的，能自由编辑，让普通用户自由定义该资产的功能角色。

### 使用版本
Version 1.2.0-2 GPLv2

[注:] 需求

**Comment by jingyugao** [comment]
I need a remark for target host. Because I have many hosts ,I can’t  distinct them just by host name.

**Comment by jym503558564** [comment]
目前普通用户无权限更改资产信息。某台资产授权了几个登录用户，如果每个用户都有权更改这个资产信息，也是不太合理的。如有其它问题，可重新打开issues
