### ISSUE TITLE
资产树中测试连接性和更新信息功能有问题

### ISSUE THREAD

**Issue by zabbixfan** [jumpserver/jumpserver#1297]
[简述你的问题]

##### 使用版本
1.3

##### 问题复现步骤
资产树有多级子节点，只有在资产所属的节点中更新节点硬件信息，测试节点连接性2个功能才可以用，在上面的父节点中都不能使用，下图中只有iwork节点可用，上面的节点都无法使用这个功能。原因应该和node.py中229行assets = node.assets.all()有关，只能找到当前节点关联的资产，用assets = node.get_all_assets()应该会更好。
![image](https://user-images.githubusercontent.com/13973917/39684814-273b8aea-51f1-11e8-9c48-9fa9d241585e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues

**Comment by chenylon** [comment]
不知道是不是我操作不对 我使用的最新版的jumpserver:1.4.6-2 发现问题依然存在 git pull也显示是最新的
于是我改动了一下jumpserver/apps/assets/api/node.py文件中的TestNodeConnectiveApi类
将：
assets = node.assets.all()
改为：
assets = node.get_all_assets()
重启jumpserver之后就可以使用了
