### ISSUE TITLE
[Feature] 远程应用强制指定发布机

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12979]
## 功能名称
远程应用强制指定发布机

## 功能描述
期望远程应用可以强制指定发布机打开

## 用户故事（可选）
企业内存在多个 web 网站，且访问时需要单独设置 DNS ，当前发布机标签的机制是优先访问，在此种情况下指定发布机故障时还能进入到浏览器页面，容易产生歧义

## 功能要求
- 期望远程应用可以强制指定发布机打开，当指定发布机故障时直接报错

**Comment by BaiJiangJie** [comment]
不考虑强制指定。

资产可连是首先要考虑的。
