### ISSUE TITLE
[Question] Where is the code that sets up networking

### ISSUE THREAD

**Issue by cookiemonsteruk** [jumpserver/jumpserver#12973]
Hello. Apologies I only know English and other languages but not any Chinese.
I used the latest script from github to install jumpserver using:
```
git clone --depth=1 https://github.com/jumpserver/Dockerfile.git
cd Dockerfile
cp config_example.conf .env
docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose-init-db.yml up -d
docker exec -i jms_core bash -c './jms upgrade_db'
docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml up -d
```
But I immediately lost ssh connection to the server. Upon inspection from the console, we could see the network has been reconfigured and the installation had stopped without completing.
We would like to start again but we have been unable to undo the networking changes.
The real problem we have is that there is a network bridge created and the IP address gets assigned to it as 192.168.5.1/24 on every reboot even if we change it to something different. Unfortunately that address is the one of the main router/firewall on the network and as soon as the jumperver boots and assigns to itself that address, it breaks the network for all other clients.
The question here is to please tell me where is the code that sets up the network for jumpserver bridge so that we can change the ip address for the bridge so that we can re-attempt the installation. Please.

**Comment by BaiJiangJie** [comment]
Well, we have received your inquiry.

First, you can try to view and modify the configuration DOCKER_SUBNET in the .env file. By default, it is set to DOCKER_SUBNET=192.168.250.0/24. We suspect that there might be a conflict between the Docker subnet and your actual IP address. After trying this, please provide the actual error message.

Finally, if you intend to use it in a production environment, we recommend deploying JumpServer using the offline package installation method.

**Comment by BaiJiangJie** [comment]
Try stopping the JumpServer service and then using the docker command to remove the network.

**Comment by wojiushixiaobai** [comment]
Please set the value of DOCKER_SUBNET to an unused network segment address, such as 192.168.250.0/24.
```sh
cd Dockerfile
cat .env | grep DOCKER_SUBNET

DOCKER_SUBNET=192.168.250.0/24
```

**Comment by cookiemonsteruk** [comment]
Yup, got that:
```
penguin@bastion-1:~/Dockerfile$ cat .env | grep DOCKER_SUBNET
DOCKER_SUBNET=192.168.7.0/24
```
What's next?

**Comment by wojiushixiaobai** [comment]
> Yup, got that:
> 
> ```
> penguin@bastion-1:~/Dockerfile$ cat .env | grep DOCKER_SUBNET
> DOCKER_SUBNET=192.168.7.0/24
> ```
> 
> What's next?

Restart your container service.

**Comment by wojiushixiaobai** [comment]
Please execute the following shell commands in order.

```sh
cd Dockerfile

# stop jumpserver
docker compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml down -v

# clean docker network
docker network prune -f

# restart docker
systemctl restart docker

# check network
ip addr

# check jumpserver network config
docker compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml config

# start jumpserver
docker compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml start
```

**Comment by cookiemonsteruk** [comment]
Beautiful. So far the bridge is gone:
```
penguin@bastion-1:~/Dockerfile$ sudo docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.y
ml -f docker-compose.yml down -v
[sudo] password for penguin:
WARNING: The DEBUG variable is not set. Defaulting to a blank string.
Stopping jms_mysql ... done
Stopping jms_redis ... done
Stopping jms_core  ... done
Removing jms_mysql ... done
Removing jms_redis ... done
Removing jms_core  ... done
Removing network jms_net
penguin@bastion-1:~/Dockerfile$ sudo docker network prune -f
penguin@bastion-1:~/Dockerfile$ sudo systemctl restart docker
penguin@bastion-1:~/Dockerfile$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 78:f2:9e:f9:b5:ed brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.157/24 metric 100 brd 192.168.5.255 scope global dynamic enp1s0
       valid_lft 7178sec preferred_lft 7178sec
    inet6 fe80::7af2:9eff:fef9:b5ed/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:e0:55:f6:c7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by wojiushixiaobai** [comment]
There seems to be no problem. You can try restarting. Good luck. 
:)

**Comment by cookiemonsteruk** [comment]
Networking problem that I needed to fix is now fixed. I'll try to start over again .
Many thanks @wojiushixiaobai . Superstar !!

**Comment by cookiemonsteruk** [comment]
closing
