### ISSUE TITLE
[Feature] 命令记录对接 ES 长度限制解除或放宽

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12978]
## 功能名称
命令记录对接 ES 长度限制解除或放宽

## 功能描述
希望命令记录对接 ES 后，其长度的限制可以解除或放宽

## 功能要求
- 当前命令记录默认截取 1024 字节长度，对于部分场景例如执行复杂 SQL 时可能超出限制，期望在对接 ES 后可以解除或放宽字符长度限制，能做参数控制最优

**Comment by BaiJiangJie** [comment]
对 es 存储没有限制。

**Comment by BaiJiangJie** [comment]
v3.10.8 放开。

**Comment by gerry-fit** [comment]
好的，谢谢
