### ISSUE TITLE
[Bug] CSRF Failed: CSRF token missing

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#12987]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
v3.10.7

## 使用的版本类型 (必填)
- [ ] 企业版 

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
管理员使用过程中会提示 “CSRF Failed: CSRF token missing.”，刷新页面后恢复正常，影响使用体验
![image](https://github.com/jumpserver/jumpserver/assets/95400700/2665584a-6e4e-4d15-b127-077d4fed5c4a)

## 期望行为
无报错

## 系统环境
- 操作系统：Windows 10
- 浏览器/应用版本：Chrome 新版

**Comment by BaiJiangJie** [comment]
能稳定复现吗？
