### ISSUE TITLE
申请工单-资产授权当主机和节点都为空的情况，不可提交

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12982]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[申请工单-申请资产授权]

## 功能描述
[在这里描述该功能的详细内容，包括其作用、目的和所需的功能]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [在申请工单时，如果将节点和资产都为空的情况下，消息通知中工单可以正常审批，工单列表-待我审批会提示“资产或者节点至少选择一项”，会有无效工单存在，能否在用户申请工单时，就直接提示“资产或者节点至少选择一项“，避免审批人经常收到无效工单审批通知。]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]
<img width="1363" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/7ff5732a-ce66-4ca0-9c09-b65b81647e68">
<img width="1109" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/e28cc6fd-37b9-413e-850f-c884e2967fda">

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
用户提交工单时，可能会不知道要申请的节点名称和资产名称，允许为空。
管理员审批时，允许就必须要指定资产或节点，所以是必填。
逻辑上是合理的。
