### ISSUE TITLE
工作台资产可连接性无法排序

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#12995]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[在这里输入功能的名称或标题]

## 功能描述
[在这里描述该功能的详细内容，包括其作用、目的和所需的功能]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [工作台资产可连接性无法排序，建议可以跟激活一样，做个筛选框]

## 示例或原型（可选）
<img width="1366" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/dc834b98-547f-44a7-8da6-5007fb0de4dc">
## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
已修复，v3.10.8 发布。
