### ISSUE TITLE
[Bug] web控制台自动登录无法点击

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#12991]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.17]

## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)

## Bug 描述 (详细)
[web端功能无法点击]

## 复现步骤
1. [登录页面]
2. [如图]

![image](https://github.com/jumpserver/jumpserver/assets/48144475/9a54fa42-91c4-4eb8-89af-57d5ad3ec7b5)

## 期望行为
[这是预期的？]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[Centos7]
- 浏览器/应用版本：[chrome]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by Evo555** [comment]
配置文件 /opt/jumpserver/config/config.txt 修改参数SESSION_EXPIRE_AT_BROWSER_CLOSE=False ，重启服务生效

**Comment by BaiJiangJie** [comment]
v3.10.8 会优化。

关注新版本发布。

是的，这种方式可以解决。
> 配置文件 /opt/jumpserver/config/config.txt 修改参数SESSION_EXPIRE_AT_BROWSER_CLOSE=False ，重启服务生效
> 
> 另外，你的版本填错了，还没有发布该版本

**Comment by cuijianzhe** [comment]
> v3.10.8 会优化。
> 
> 关注新版本发布。
> 
> 是的，这种方式可以解决。
> 
> > 配置文件 /opt/jumpserver/config/config.txt 修改参数SESSION_EXPIRE_AT_BROWSER_CLOSE=False ，重启服务生效
> > 另外，你的版本填错了，还没有发布该版本

感谢可以了，版本抱歉写错了
