### ISSUE TITLE
跳板机增加代理网关功能。

### ISSUE THREAD

**Issue by wcc526** [jumpserver/jumpserver#130]
部署堡垒机后：自动化服务器连接服务器前必须得经过堡垒机了，整个连接过程就变成了自动化服务器需先和堡垒机建立SSH会话，然后由堡垒机和目标服务器建立SSH会话，整个过程如图2。这个过程的变化会导致自动化服务器脚本登录失效，而且还带来了几个难题：
自动化服务器如何完成和堡垒机的身份认证，如果堡垒机登录有双因子认证怎么办？
堡垒机怎么选择目标服务器？因为堡垒机并不知道自动化脚本想推给哪台目标服务器，只有自动化服务器自己知道。

通过和工程师进行沟通，SSH网关模式可以让自动化运维执行起来

详见这篇文章。
http://mp.weixin.qq.com/s?__biz=MzA3MzYwNjQ3NA==&mid=403377581&idx=1&sn=43a1b282de496be4482eda2f04c5aa61&scene=1&srcid=0315x6io41hZ6LgJ4S1kvgLF#wechat_redirect

实现思路是采用
ssh-proxycommand

实现方式可以参考以下文章
http://beakdoosan.blogspot.tw/2010/11/ssh-proxycommand-nc.html
https://www.lainme.com/doku.php/blog/2011/01/%E9%80%8F%E8%BF%87%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5ssh
http://www.cyberciti.biz/faq/linux-unix-ssh-proxycommand-passing-through-one-host-gateway-server/
https://wiki.gentoo.org/wiki/SSH_jump_host
http://bitprophet.org/blog/2012/11/05/gateway-solutions/
http://backreference.org/2010/02/26/jump-in-with-ssh-and-netcat/

**Comment by wptad** [comment]
说的非常好。我研究下，感谢分享

-- 
Tad Wang

在 2016年3月17日 10:52:20, chi-chi weng (notifications@github.com) 写到:

部署堡垒机后：自动化服务器连接服务器前必须得经过堡垒机了，整个连接过程就变成了自动化服务器需先和堡垒机建立SSH会话，然后由堡垒机和目标服务器建立SSH会话，整个过程如图2。这个过程的变化会导致自动化服务器脚本登录失效，而且还带来了几个难题：
自动化服务器如何完成和堡垒机的身份认证，如果堡垒机登录有双因子认证怎么办？
堡垒机怎么选择目标服务器？因为堡垒机并不知道自动化脚本想推给哪台目标服务器，只有自动化服务器自己知道。

通过和工程师进行沟通，SSH网关模式可以让自动化运维执行起来

详见这篇文章。
http://mp.weixin.qq.com/s?__biz=MzA3MzYwNjQ3NA==&mid=403377581&idx=1&sn=43a1b282de496be4482eda2f04c5aa61&scene=1&srcid=0315x6io41hZ6LgJ4S1kvgLF#wechat_redirect

实现思路是采用
ssh-proxycommand

实现方式可以参考以下文章
http://beakdoosan.blogspot.tw/2010/11/ssh-proxycommand-nc.html
https://www.lainme.com/doku.php/blog/2011/01/%E9%80%8F%E8%BF%87%E4%BB%A3%E7%90%86%E8%BF%9E%E6%8E%A5ssh
http://www.cyberciti.biz/faq/linux-unix-ssh-proxycommand-passing-through-one-host-gateway-server/

**Comment by wcc526** [comment]
@wptad 直接采用 ProxyCommand 应该还不够，需要把 nc 命令封装到bash里

`ProxyCommand ssh jumpserver_user@jumpserver_server -p jumpserverport bastion-nc %h %p`

bastion-nc 的内容是

     #!/usr/bin/bash

    # something before nc
     echo "hello" >> /var/tmp/hellworld.txt
     
     /usr/bin/nc $@

有问题再私下交流，ＱＱ 949409306 ，我也在研究网关的功能。

**Comment by ibuler** [comment]
非常不错的需求，也是急切的需求

**Comment by LeoLiuYan** [comment]
这个issue解决了吗？

**Comment by ibuler** [comment]
尝试解决了，但是启用网关功能后无法获取输入输出

**Comment by ibuler** [comment]
对ssh协议不是很熟悉，新的版本实现了 ssh server, 用户直接登录的话 会调用 paramiko的`check_channel_shell_request `  `check_channel_pty_request `方法    https://github.com/jumpserver/coco/blob/master/coco/interface.py#L110

如果使用  ProxyCommand
#  .ssh/config
`ProxyCommand ssh jumpserver_user@jumpserver_server -p port  -W %h:%p`

会调用 `check_channel_shell_request(self, channel)`
https://github.com/paramiko/paramiko/blob/master/paramiko/server.py#L507

paramiko返回的 channel并不是一个可以直接写入的socket,而是一个隧道，虽然可以实现 proxy  gateway功能但是无法获取其中的命令。

@wcc526 望交流

**Comment by swift1911** [comment]
这个问题有进展了吗

**Comment by ihipop** [comment]
有进展吗？ 新版的SSH自带jumpserver选项

```
-J [user@]host[:port]
             Connect to the target host by first making a ssh connection to the jump host and then establishing a TCP forwarding to the ultimate destination from there.  Multiple jump hops may be specified
             separated by comma characters.  This is a shortcut to specify a ProxyJump configuration directive.

```

**Comment by vinsia** [comment]
这个搞定了吗

**Comment by awklinux** [comment]
这个问题还有继续跟进嘛

**Comment by awklinux** [comment]
很勿希望能搞定这个

**Comment by ibuler** [comment]
该功能无法记录内容，故暂时不考虑

**Comment by leopku** [comment]
2021年来挖个坟
