### ISSUE TITLE
[Question] ha或者nginx反向代理后端，出现登录失败或者websocket连接失败

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#13005]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)

## 问题描述 (详细)
[ha或者nginx反向代理后端，出现登录失败或者websocket连接失败]
配置信息：
```
        location / {
		proxy_pass http://jumpserver.4pd.io/;
                proxy_set_header Upgrade "websocket";
                proxy_http_version 1.1;
                proxy_connect_timeout 30s;
                proxy_send_timeout 120;
                proxy_read_timeout 120;
                proxy_buffer_size 32k;
                proxy_buffers 4 32k;
                proxy_busy_buffers_size 64k;
                proxy_redirect off;
                client_max_body_size    1000m;
                proxy_hide_header Vary;
                proxy_set_header Connection "upgrade";
                proxy_set_header Accept-Encoding '';
                proxy_set_header Host $host;
                proxy_set_header Referer $http_referer;
                proxy_set_header Cookie $http_cookie;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

upstream jumpserver.4pd.io {
    server 172.27.232.27:80 weight=3 max_fails=2 fail_timeout=30;
    server 172.27.232.19:80 weight=3 max_fails=2 fail_timeout=30;
}
upstream jumpserver.4pd.io {
    server 172.27.232.27:80 weight=3 max_fails=2 fail_timeout=30;
    server 172.27.232.19:80 weight=3 max_fails=2 fail_timeout=30;
}

```

https://github.com/jumpserver/jumpserver/assets/48144475/ec10c197-2c8a-4df9-b250-45bc2a27c095

https://github.com/jumpserver/jumpserver/assets/48144475/be0a2504-1bc6-45dd-aabc-befbee4a171c

## 背景信息
- 操作系统：[centos7]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[官网集群搭建文档搭建]

## 具体问题
[ha或者nginx代理后端jumpserver会出现登录反复登出，如果后端代理一台正常，当代理多台会出现问题]

## 尝试过的解决方法
[卸载重装会好使一段时间，开启LDAP认证后会复现问题，400报错等，关闭后也会出现登录立即登出，重启无用]

## 预期结果
[可以通过ha代理后端多台80端口]

## 我们的期望
[希望自谦有同样问题解决方案]

**Comment by wojiushixiaobai** [comment]
配置 一致性 hash 或者 会话保持。

如果不理解是什么意思，你可以将你的轮询算法改成 ip_hash。更多内容请参考你的 Nginx 官方文档负载均衡部分
