### ISSUE TITLE
[Bug] /core/download/页面无法下载文件，点击显示404

### ISSUE THREAD

**Issue by zydudu** [jumpserver/jumpserver#13013]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
Version v3.10.7

## 使用的版本类型 (必填)
- [* ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ *] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
 /core/download/页面无法下载文件，点击显示404

## 复现步骤
1. iPanel安装最新版本jumpserver
2.登录进入web终端页面
3. 点击帮助-》下载，打开下载页面
4. 点击任意链接，无法下载相关内容

## 期望行为
可以正常下载文件

## 实际行为
下载链接404

## 系统环境
- 操作系统：Windows 10
- 浏览器/应用版本：chrome
- 其他相关环境信息：无

## 附加信息（可选）
无

**Comment by wojiushixiaobai** [comment]
- 注意: all-in-one 部署方式不支持 Client 相关功能, 仅支持在 纯 B/S 架构 Web 端使用。

**Comment by zydudu** [comment]
已解决
