### ISSUE TITLE
[Bug] Jupserver集群，控制台设置elastic配置测试失败

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#13012]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [ x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[一共3台jumpserver节点，一天设置的elastic有效并且可以连接，其他两台不行。点进去还不能配置，更新不了灰色的]
![image](https://github.com/jumpserver/jumpserver/assets/48144475/0536a57e-8a69-418c-b88a-c91e5581336a)
![image](https://github.com/jumpserver/jumpserver/assets/48144475/90338140-844a-464f-ab41-f059e5c32648)
![image](https://github.com/jumpserver/jumpserver/assets/48144475/045f0d3c-17ff-49a4-971a-0c1b072430ec)

![image](https://github.com/jumpserver/jumpserver/assets/48144475/99a14918-11f2-4ff5-8622-fbb5343b9a13)

## 期望行为
[希望可以看下]

## 系统环境
- 操作系统：[centos7]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by Evo555** [comment]
其它节点有没有重启koko组件，或者查看一下组件情况
