### ISSUE TITLE
[Bug] 远程应用发布机已经删除，但是还是有健康检查提示已离线

### ISSUE THREAD

**Issue by zydudu** [jumpserver/jumpserver#13017]
## 当前使用的 JumpServer 版本 (必填)
v3.10.7

## 使用的版本类型 (必填)
- [ *] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [* ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
在系统设置远程应用发布机和资源列表里都删除了远程系统发布机，但是在站内信提示中还有远程发布机已离线的提示

## 复现步骤
1. 删除远程应用-》应用发布机下面的远程发布机
2. 删除控制台-〉资产列表中相同的资产
3.站内信依然定时提示已删除的发布机已离线

## 期望行为
已删除的发布机不再提示离线

## 系统环境
- 操作系统：Windows 10
- 浏览器/应用版本：chrome
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
无
<img width="919" alt="image" src="https://github.com/jumpserver/jumpserver/assets/4986296/801ab9e4-c19b-410c-95b6-9fd9e878f2d8">

**Comment by wojiushixiaobai** [comment]
`系统设置` - `组件设置` 页面下的 `组件管理` 里面删除发布机组件即可

**Comment by zydudu** [comment]
已解决
