### ISSUE TITLE
账号模板页面崩溃

### ISSUE THREAD

**Issue by entercoder1993** [jumpserver/jumpserver#13015]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.7

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [x] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
在弹出的对话框中选择对应的资产（部分资产不会崩溃），在进行选择的瞬间会出现页面崩溃

## 复现步骤
1. 创建好账号模板之后，在账号列表中点击模板添加，
2. 再点击资产，
3. 在弹出的对话框中选择对应的资产（部分资产不会崩溃），
4. 在进行选择的瞬间会出现页面崩溃，如图。
<img width="1450" alt="截屏2024-04-13 15 09 45" src="https://github.com/jumpserver/jumpserver/assets/16153495/3dc383a6-bf12-4f82-bfd3-5a9c03694e7b">

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
 web 页面崩溃，出现重新加载页面

## 系统环境
- 操作系统：macOS Sonoma 14.0
- 浏览器/应用版本：Arc 浏览器 1.38.0
- 其他相关环境信息：在 windows 环境中使用 chrome 浏览器不会崩溃，但在 macOS 环境中使用 chrome 和 edge 浏览器 仍出现 web页面崩溃，如下图
<img width="1450" alt="截屏2024-04-13 15 23 24" src="https://github.com/jumpserver/jumpserver/assets/16153495/c4484a1a-2c2f-4661-9947-ee98b0f602b3">

## 附加信息（可选）
<img width="1450" alt="截屏2024-04-13 15 23 24" src="https://github.com/jumpserver/jumpserver/assets/16153495/c4484a1a-2c2f-4661-9947-ee98b0f602b3">
<img width="1450" alt="截屏2024-04-13 15 09 45" src="https://github.com/jumpserver/jumpserver/assets/16153495/3dc383a6-bf12-4f82-bfd3-5a9c03694e7b">

**Comment by BaiJiangJie** [comment]
操作过程中打开浏览器控制台，看看哪些 API 会报错？
