### ISSUE TITLE
[Feature] 资产授权的复制粘贴权限目前除lion组件，其他组件能支持吗

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13028]
## 功能名称
除lion组件外的其他组件负载粘贴权限控制

## 功能描述
有用户反馈目前只有远程应用连接数据库时，复制粘贴收资产授权的限制，web cli不受资产授权的控制

## 用户故事（可选）
目前有用户反馈资产授权去除了粘贴权限，远程应用的数据库资产不能粘贴，但是web cli方式连接的数据库仍然可以粘贴进去，本地复现，发现只有lion组件能够资产授权管控复制粘贴权限，koko，chen组件复制粘贴均不受资产授权的限制。

## 功能要求
-  支持koko组件的复制粘贴权限管控
-  支持chen组件的复制粘贴权限管控

![微信图片_20240416100050](https://github.com/jumpserver/jumpserver/assets/136363116/df6cb479-11a3-4d9a-bafa-48e8c9a5143b)

![1](https://github.com/jumpserver/jumpserver/assets/136363116/87a6fb16-7eb1-42e2-a4a6-a335540d5c58)

**Comment by BaiJiangJie** [comment]
是的，目前只有 Lion 组件的可以控制，其他组件目前都控制不了。
