### ISSUE TITLE
【账号模版】资产授权选择账号模版自动推送用户时，实际创建的用户属性与账号模版定义的不一致

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#13025]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.7

## 使用的版本类型 (必填)
企业试用版

## 版本安装方式 (必填)
离线安装 (下载离线包)

## Bug 描述 (详细)
资产授权选择账号模版自动推送用户时，实际创建的用户属性与账号模版定义的不一致

## 复现步骤
1. 新建一个账号模版，设定属性为 NOPASSWD:ALL
![image](https://github.com/jumpserver/jumpserver/assets/43403764/b9a7047d-a9a1-43ea-a7d5-6f1ef29e8c87)

2.资产授权，账号来自模版；

3、查看推送结果：与设定属性不一致
![image](https://github.com/jumpserver/jumpserver/assets/43403764/6c5757ef-2a76-4b66-9877-e6657078d1a2)

## 期望行为
与设置的参数保持一下

## 系统环境
- 操作系统：Centos7
- 浏览器/应用版本：最新版
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

**Comment by BaiJiangJie** [comment]
如果账号在资产上已存在，则不会更新推送参数。
只有在资产上新创建账号时，才会设置推送参数。

**Comment by LinuxLeader** [comment]
推送的账号是资产上不存在的账号，设定属性为 NOPASSWD:ALL，推送之后变成 /bin/whoami

**Comment by jym503558564** [comment]
无法复现该问题。推送新用户，重新配置推送参数，再试下。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/7c37564b-d964-4171-9f47-cf8940c14b74)

**Comment by BaiJiangJie** [comment]
升级到最新版本使用。
