### ISSUE TITLE
无法使用web gui连接到mysql

### ISSUE THREAD

**Issue by GavinTan** [jumpserver/jumpserver#13039]
## 当前使用的 JumpServer 版本 (必填)
v3.10.7

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [x] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
无法使用web gui方式连接到数据库，点击连接后什么内容都没有。chen进程正常有8082端口，用的docker jms_all测试了几个版本只要升级3.10.4包括最新的3.10.7都是这个错误 ，3.10.4以下3.10.3，3.10.2这些都正常。

## 系统环境
docker

## 附加信息（可选）
![image](https://github.com/jumpserver/jumpserver/assets/10555093/7e5494f3-5a2b-4bd6-a1e4-09f5f672e996)
![image](https://github.com/jumpserver/jumpserver/assets/10555093/bcc8f317-d11a-4ab0-8562-50047490fef3)

**Comment by BaiJiangJie** [comment]
也就是 v3.10.4 之前可以连接，升级之后不能连接了？

提供一下 MySQL 数据库的版本。

**Comment by GavinTan** [comment]
好的，还发现一个问题All-in-one好像gpt也有问题 static/?token=7591f97a-ade7-4758-bd22-4583d361eff6   404

**Comment by BaiJiangJie** [comment]
截图看一下。

**Comment by GavinTan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/10555093/47a64895-40db-4f61-bab6-656edf196fd1)
![image](https://github.com/jumpserver/jumpserver/assets/10555093/7504261f-9db0-44b7-a866-9b0ea444dd0b)

**Comment by feng626** [comment]
打开控制台看看ws的连接

**Comment by GavinTan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/10555093/9d637ada-0eec-40a8-a782-f5796304341e)
没有ws连接出现404就没了

**Comment by wojiushixiaobai** [comment]
查 `kael` 组件是否在线，或者 `jms_all` 里面查 `kael` 组件的日志

**Comment by GavinTan** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/10555093/0036ffc5-9590-4d6f-bd33-6b8d6bd410e8)
![image](https://github.com/jumpserver/jumpserver/assets/10555093/f12f089b-9817-43fd-98b1-ea7085c91031)
我发现问题了在jumpserver/kael docker里有ui目录，All-in-one没有把ui目录拷贝过来正常了

**Comment by BaiJiangJie** [comment]
好的，下个 All-in-one 版本中修复一下。

**Comment by jym503558564** [comment]
v3.10.9 已修复，请升级进行体验
![image](https://github.com/jumpserver/jumpserver/assets/40739051/16e1a835-9d92-44a0-8c1f-29c372265d1a)
![image](https://github.com/jumpserver/jumpserver/assets/40739051/552271ff-a787-4478-8a6e-947d52603a72)
