### ISSUE TITLE
[Bug] API for labelled resource creation in v3.10.1 isn't working as expected

### ISSUE THREAD

**Issue by asians-singhayushh** [jumpserver/jumpserver#13030]
### Jumpserver Version
Product: 	JumpServer Community Edition GPLv3
Version: 	v3.10.1

### Description
For the API to create a labeled resource, the post request on `/labels/labeled-resources/` is returning unexpected errors:
- `propKeyres_typeerrorValue must be a string` if res_type is included in the request body, like in the screenshot below
- `internal server error` if we remove the optional res_type and only pass label uuid - resource id - resource name

![image](https://github.com/jumpserver/jumpserver/assets/161552037/6e41790e-f7ad-4232-a25f-bea2e90546fe)
> the screenshot above has dummy values

Help needed!
Please let us know if there's something wrong with our payload. I cross verified that the label uuid is valid and even tried changing the resource name to not have the IP.

**Comment by BaiJiangJie** [comment]
You should access this API to update resource and labels:

PUT /api/v1/labels/labels/{label-id}/resource-types/{resource-type-id}/resources/

Such as:
```
label_id=7a4ab994-09f7-4bfa-be1f-7cc91721140f
asset-type-id=8

PUT /api/v1/labels/labels/7a4ab994-09f7-4bfa-be1f-7cc91721140f/resource-types/8/resources/

Payload:
{
    "res_ids":  [
        "01a68cf3-d2ab-4789-c61c-9756314c4d73",
        "02876adb-d9d7-4bca-a84e-c046fe4952f5",
        "0684c3a0-58ac-38d4-c61c-9756314c4d73",
        "071ca098-4de7-41b8-c61c-9756314c4d73"
        ]
}

Get resource type and id:

GET /api/v1/labels/resource-types/

```
