### ISSUE TITLE
[Feature] 全局启用MFA，单独创建单个用户取消勾掉MFA选项

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#13032]
## 功能名称
1、系统设置中开启全局MFA认证
2、创建用户时还可以选择MFA级别，会让用户产生误解

## 功能要求
当用户开启全局MFA认证后，在创建用户时是否可以将MFA级别选择置灰，或默认隐藏避免用户理解歧义
<img width="1258" alt="image" src="https://github.com/jumpserver/jumpserver/assets/97491875/595a8b10-8058-4c70-a158-c964421fa557">

**Comment by BaiJiangJie** [comment]
后面版本考虑优化一下。

**Comment by BaiJiangJie** [comment]
v3.10.10 优化。
