### ISSUE TITLE
[Feature] 审计台-会话记录-在线会话中显示远程应用使用的发布机具体是哪一台

### ISSUE THREAD

**Issue by yuqun-nj** [jumpserver/jumpserver#13033]
## 功能名称
审计台-会话记录-在线会话中显示远程应用使用的发布机具体是哪一台,有助于定位哪一台发布机不稳定

**Comment by BaiJiangJie** [comment]
暂时不考虑支持，会话连接失败可通过对应的组件日志查看。（Lion、Razor）

未来考虑支持在页面上查看系统服务运行日志。
