### ISSUE TITLE
[Bug] 会话审计下面的任何一个子项整个页面都会卡住转圈。

### ISSUE THREAD

**Issue by dengpei89** [jumpserver/jumpserver#13041]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.10.7-lts]

## 使用的版本类型 (必填)
- [* ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [* ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
![image](https://github.com/jumpserver/jumpserver/assets/26969979/1ad76b72-c378-408c-b6ed-624feaaf6f7c)

![image](https://github.com/jumpserver/jumpserver/assets/26969979/a11feb07-d178-49f2-b1de-d529cf667790)

![image](https://github.com/jumpserver/jumpserver/assets/26969979/4573466b-c73d-4734-b4a4-9885e4cced3e)

![image](https://github.com/jumpserver/jumpserver/assets/26969979/dde9c5b3-c91e-499b-b174-8aed9a5420d7)

只要点击会话审计下的任何一个，整个页面就会卡住，再访问其他页面都会转圈，过一会（20s）又会自动恢复。
新部署，还未开始使用

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by dengpei89** [comment]
【补充】
![image](https://github.com/jumpserver/jumpserver/assets/26969979/73a6d63a-a9a7-4898-9503-60430319214e)
web容器的error.log有这一条错误

**Comment by BaiJiangJie** [comment]
看着像是网络配置的问题，JumpServer 上层还有其他 Nginx 吗？

**Comment by dengpei89** [comment]
没有，单机部署的，只有这个会话审计下面会卡，其他页面都正常。 起初怀疑是机器问题，换了台机器，重新部署问题依旧。
会不会是这块的逻辑有问题？

**Comment by BaiJiangJie** [comment]
应该不是，那看看这个目录下的 API 请求时间长吗？

**Comment by dengpei89** [comment]
3.10.6 7 8试了都不行，在那个目录下可以看请求时长呢。 有个问题比较奇怪，如果这个地方卡了，原来可访问打开得页面也不行，刷新也不行，必须得等待20s左右才会自动恢复。。

**Comment by dengpei89** [comment]
这个问题很好复现，用all in one拉起来就可以复现

**Comment by BaiJiangJie** [comment]
你是什么方式部署的？离线包？

**Comment by BaiJiangJie** [comment]
测试了 All-in-one 没有问题。应该还是你网络环境的问题。

如果可以，你去云上开一台机器，不要和现在的网络有任何关联，试试。

**Comment by dengpei89** [comment]
离线的，又单独搞了一台，只要访问/api/v1/terminal/sessions，页面就会卡住，请求就失败了，后台nginx日志好像也没反应
![image](https://github.com/jumpserver/jumpserver/assets/26969979/ac4ba6aa-dfd6-42ee-b90b-cc7b84d37e1c)
![image](https://github.com/jumpserver/jumpserver/assets/26969979/432ca571-5e15-4151-b92e-fba6f7830550)
![image](https://github.com/jumpserver/jumpserver/assets/26969979/19564ab5-b742-4128-9740-a7cca242eaaa)

**Comment by BaiJiangJie** [comment]
可以远程吗？

**Comment by dengpei89** [comment]
可以的，您看您什么时间方便？

**Comment by dengpei89** [comment]
抱歉，抱歉，确实是网络问题，有过滤，同一个网段试了没问题。 @BaiJiangJie

**Comment by dengpei89** [comment]
补充一下原因： 因为之前jumpsever版本的漏洞（下面的链接），加上公司防火墙的漏洞库没有更新，导致/api/v1/terminal/sessions/的请求直接被拦截了
https://github.com/jumpserver/jumpserver/security/advisories/GHSA-633x-3f4f-v9rw
