### ISSUE TITLE
[Question] /accounts/accounts/bulk POST接口，secret 字段值如何加密

### ISSUE THREAD

**Issue by bikai-ayy** [jumpserver/jumpserver#13057]
## 
**/accounts/accounts/bulk POST接口，secret 字段值如何加密.** <br>
**v3.10.7** <br>
_/accounts/accounts/bulk POST接口，secret 字段值如何加密。_

## 当前使用的 JumpServer 版本
v3.10.7

## 使用的版本类型 
- 社区版

## 版本安装方式 
- 在线安装 (一键命令)

## 问题描述 (详细)
![image](https://github.com/jumpserver/jumpserver/assets/120439116/c2bc57ea-6d89-45e5-96bd-fac551bc0d98)

## 背景信息
- 操作系统：[ubuntu]

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/blob/dev/src/utils/crypto.js#L36-L51

研究这个代码，跟前端提交的加密方式保持一致就行。

有一点需要注意的是，JumpServer 默认的加解密过程中，后端服务会对每一个请求生成一个 密钥对，前端使用 `jms_public_key` 进行加密。后端使用对应的 `jms_private_key` 解密。

也就是通过 API 请求时，需要使用浏览器中的 Cookie 进行认证。

**Comment by BaiJiangJie** [comment]
如果你使用的 https 就不用考虑加密了，因为 secret 等敏感信息的加密方式和 https 的标准加密是一致的。

**Comment by BaiJiangJie** [comment]
1. 构造 aesKey: 首先随机生成一个长度为 10 的随机字符串
```const aesKey = (Math.random() + 1).toString(36).substring(2)```

2. 生成 keyCipher: 使用 rsa 加密方式，使用 jms_public_key 加密 aeskey
```
let rsaPublicKeyText = getCookie('jms_public_key')
rsaPublicKeyText = rsaPublicKeyText.replaceAll('"', '')
const rsaPublicKey = atob(rsaPublicKeyText)
const keyCipher = rsaEncrypt(aesKey, rsaPublicKey)
```

3. 生成 secretCipher: 使用 aes 加密方式，使用 aesKey 加密 secret
``` const passwordCipher = aesEncrypt(password, aesKey)```

4. 构造加密后的 secret 值：`keyCipher:secretCipher`
```${keyCipher}:${passwordCipher}```
