### ISSUE TITLE
[Question] web终端web cli连接方式无法使用

### ISSUE THREAD

**Issue by eya46** [jumpserver/jumpserver#13053]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.7

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
只用过web cli，其他的没试过
连接地址有问题，指向的是127.0.0.1
全部的资产试了下都这样
![image](https://github.com/jumpserver/jumpserver/assets/61458340/c6d59383-bebe-4f93-85f1-43996ba71a8f)
![image](https://github.com/jumpserver/jumpserver/assets/61458340/81afe4f9-e152-4bb9-b99a-8ca55a3be7d0)
![image](https://github.com/jumpserver/jumpserver/assets/61458340/b282d36f-153e-418c-bf5b-332ce5d1d9c6)
导出的sql
![image](https://github.com/jumpserver/jumpserver/assets/61458340/33588c90-8dd3-4c9e-b93d-b6f577518a30)

## 背景信息
- 操作系统：Ubuntu 22.04
- 浏览器/应用版本：Chrome 123.0.6312.123

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]
- 修改`当前站点 URL`
- 修改config.txt中`CORE_HOST`

## 预期结果
[描述你期望的解决方案或结果]
正常使用

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by eya46** [comment]
ssh客户端也一样
![image](https://github.com/jumpserver/jumpserver/assets/61458340/157ba59b-5318-416f-a050-4fd0bf507b10)

**Comment by BaiJiangJie** [comment]
确认一下 `系统设置-组件设置-服务端点` 的列表，是否有 127.0.0.1 的端点。

<img width="2054" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/6c436a66-a4c6-4afe-9f31-8cacd5f2087f">

**Comment by eya46** [comment]
没找到
![image](https://github.com/jumpserver/jumpserver/assets/61458340/7e4c6187-6cc7-458c-af4a-3c6dcc844993)

**Comment by BaiJiangJie** [comment]
服务端点列表中只有 Default 吗？

**Comment by eya46** [comment]
对
![image](https://github.com/jumpserver/jumpserver/assets/61458340/017072f8-5338-4a33-a919-cc82c0e94660)


> 服务端点列表中只有 Default 吗？

**Comment by BaiJiangJie** [comment]
真实访问的 JumpServer 地址是 127.0.0.1 吗？

**Comment by eya46** [comment]
域名访问的，机器在外网

**Comment by BaiJiangJie** [comment]
可以远程吗？帮你看一下为什么会请求到 127.0.0.1 地址。

**Comment by eya46** [comment]
发邮件了

**Comment by BaiJiangJie** [comment]
发到哪个邮箱了？

**Comment by eya46** [comment]
[baijiangjie@gmail.com](mailto:baijiangjie@gmail.com)

**Comment by eya46** [comment]
发送过去了

> 没有收到。 [jiangjie.bai@fit2cloud.com](mailto:jiangjie.bai@fit2cloud.com) 发到我工作邮箱吧。

**Comment by eya46** [comment]
@BaiJiangJie 帮忙找到问题了：反向代理proxy_set_header Host 设置成了127.0.0.1
