### ISSUE TITLE
添加交换机造成交换机cpu每隔一小时飙高到60%-80%

### ISSUE THREAD

**Issue by yang-sheep** [jumpserver/jumpserver#1305]
[简述你的问题]
添加交换机资产，没有选择推送，但是每隔一小时都是对交换机的帐号做可连接性测试，造成个别交换机cpu飙高很多
##### 使用版本
[请提供你使用的Jumpserver版本1.3.0]

##### 问题复现步骤
1. [步骤1]
添加交换机帐号admin，自动推送和密钥都勾掉，添加交换机资产（ssh连接）
2. [步骤2]
测试登录没有问题，但是每隔一小时jumpserver就自动测试帐号的可连接性，造成我的一台交换机cpu飙高到60%-80%（平常大概在28%左右）
目前我只能此交换机的资产从jumpserver中去掉，别的交换每个一小时也有这个问题，但是cpu飙升的不高，大概高与平均值5%-7%

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/23044170/39793980-7ea684ee-537a-11e8-9316-d27a13e76c4b.png)

![default](https://user-images.githubusercontent.com/23044170/39793964-6ce34c56-537a-11e8-84c9-8cdfda84dd10.png)
zabbix监控图
![default](https://user-images.githubusercontent.com/23044170/39794066-0699c56e-537b-11e8-8f5c-c82ef859e808.png)

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
