### ISSUE TITLE
WEB终端里，连接资产全屏后，最右侧的快捷键齿轮会自动隐藏

### ISSUE THREAD

**Issue by liuyy0808** [jumpserver/jumpserver#13064]
## 功能名称
[WEB终端里，连接资产全屏后，最右侧的快捷键齿轮会自动隐藏]
![image](https://github.com/jumpserver/jumpserver/assets/164499075/08af09b5-ebc6-4114-a98b-2ec94f84aecd)
## 功能要求
希望和V2.*一样，在全屏的时候也能显示快捷齿轮，不隐藏，方便用户操作
或者隐藏、不隐藏作为设置项，给用户进行选择
- [以此类推，列出所有相关的功能要求]

## 优先级
高

**Comment by BaiJiangJie** [comment]
最新版本已优化，全屏也会显示。

**Comment by Lee-Z** [comment]
使用的是xrdp，全屏后还是不显示齿轮。版本：开源3.10.10

**Comment by zwl1998** [comment]
同样的问题，我的版本跟上面的人一样：社区版3.10.10，是否需要升级到4版本
