### ISSUE TITLE
资产添加完可以登录，但是连接状态是红色的，而且无法获取到硬件信息

### ISSUE THREAD

**Issue by yang-sheep** [jumpserver/jumpserver#1306]
[简述你的问题]
正常添加主机，自动推送，推送状态是失败，但是因为root的密码是对的，可以通过跳板机登录此服务器，访问正常，但是进入点击测试可连接性就会报错，而且硬件信息也不能自动获取到了
![default](https://user-images.githubusercontent.com/23044170/39794733-6fbf3c74-537e-11e8-8c57-938c692aa141.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.0 ]

##### 问题复现步骤
1. [步骤1]

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/23044170/39794682-2624ea1e-537e-11e8-824c-f81e1636205f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yang-sheep** [comment]
好的

**Comment by caicaicaiyuting** [comment]
- 我也遇到了。
- python版本：2.7.5
- 
![image](https://user-images.githubusercontent.com/39758945/137101010-5cf50ce2-958a-41a8-89fd-01cf602dfff9.png)
