### ISSUE TITLE
[Bug] feat: HUAWEI 交换机资产执行快捷命令还是报错

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13073]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.8

## 使用的版本类型 (必填)
- [* ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [* ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
在工作台-快捷命令界面勾选华为交换机执行失败
![image](https://github.com/jumpserver/jumpserver/assets/44529247/b275260a-b4f4-4ee6-b42e-f7f5d9cace02)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by w940853815** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/17764568/83c2a853-1aa8-4c7e-af5a-ad6168890883)
系统平台这里是Huawei吗？

**Comment by ryswork1993** [comment]
> ![image](https://private-user-images.githubusercontent.com/17764568/323890607-83c2a853-1aa8-4c7e-af5a-ad6168890883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTc0MTUsIm5iZiI6MTcxMzUxNzExNSwicGF0aCI6Ii8xNzc2NDU2OC8zMjM4OTA2MDctODNjMmE4NTMtMWFhOC00YzdlLWFmNWEtYWQ2MTY4ODkwODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4NTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNzg3NjkyZTRlMGE3Mzg3MDVlZTg1NjY5ZmVlY2QwY2U5ZTY3ZjQ5ZTBhMTkwNGM5ZTAxMDc3MjU5MWI5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EuHLoUBAfo28fiw1tGe4RJBXY20KuuBI1u94C6zMy3s) 系统平台这里是Huawei吗？

不是自带的huawei，是我自定义的平台，自带的huawei平台不能添加sftp和自定义端口号

**Comment by ryswork1993** [comment]
> ![image](https://private-user-images.githubusercontent.com/17764568/323890607-83c2a853-1aa8-4c7e-af5a-ad6168890883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTkwMDMsIm5iZiI6MTcxMzUxODcwMywicGF0aCI6Ii8xNzc2NDU2OC8zMjM4OTA2MDctODNjMmE4NTMtMWFhOC00YzdlLWFmNWEtYWQ2MTY4ODkwODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA5MjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYWI5N2I0Y2QzNWY4MTI0ZmRjZjdjMmM1YjIxOGRjNTY1NmIzNGVkODBiNGJlYWU2NTllMTQwMjdlNWU5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X2x1clQWLiNXMwbmlG2GqnypLKNH3ed_gv0c64NmLZw) 系统平台这里是Huawei吗？

执行成功了，多谢

**Comment by BaiJiangJie** [comment]
下个版本考虑支持 平台名称 中带 `huawei`, `华为` 关键字的平台，默认都按照 HUAWEI 模块执行快捷命令。

**Comment by w940853815** [comment]
> 下个版本考虑支持 平台名称 中带 `huawei`, `华为` 关键字的平台，默认都按照 HUAWEI 模块执行快捷命令。

@ryswork1993  https://github.com/jumpserver/jumpserver/pull/13084
