### ISSUE TITLE
[Bug] token认证的方式 api查询权限问题

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13075]
组织管理员，组织在 default 组织时，api 接口获取用户列表信息等正常，当处于自行创建的其他组织下时权限被拒绝，如运维部这个组织
![image](https://github.com/jumpserver/jumpserver/assets/136363116/4dec383f-5def-4106-a06c-a5c9cde1bb37)

**Comment by BaiJiangJie** [comment]
那就是没有这个组织的权限吧。

**Comment by BaiJiangJie** [comment]
在页面上直接访问一下（url 参数重直接写 oid 参数）：

http://host/api/v1/users/users?oid={ORG_ID}

**Comment by guoheng888** [comment]
> 在页面上直接访问一下（url参数重直接写oid参数）：
> 
> [http://host/api/v1/users/users?oid={ORG_ID}](http://host/api/v1/users/users?oid=%7BORG_ID%7D)

页面是可以的，用户写脚本发现curl命令获取不到。

**Comment by BaiJiangJie** [comment]
那 curl 的时候也写到 url 参数中，不要写到 Header 中试试。

**Comment by guoheng888** [comment]
> 组织管理员，组织在 default 组织时，api 接口获取用户列表信息等正常，当处于自行创建的其他组织下时权限被拒绝，如运维部这个组织 ![image](https://private-user-images.githubusercontent.com/136363116/323869085-4dec383f-5def-4106-a06c-a5c9cde1bb37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzUxNDIsIm5iZiI6MTcxMzgzNDg0MiwicGF0aCI6Ii8xMzYzNjMxMTYvMzIzODY5MDg1LTRkZWMzODNmLTVkZWYtNDEwNi1hMDZjLWE1YzljZGUxYmIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwMTE0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmFiZThhNjQyZmVhMzNlYzJiZGViZWEyNWI4MDRlNjQ5ZTM3YjI3MzgyYjJkOTcxZWIxYWVmMzQyNDUzYjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wFxEXIm7M7b7MxGKgdihAbi_oxDpDKvc5tHWOUxvyXs)

![image](https://github.com/jumpserver/jumpserver/assets/136363116/2b571e09-b869-4be7-8b9b-9f283791b2c6)
也是没权限

**Comment by guoheng888** [comment]
> 那curl的时候也写到url参数中，不要写到Header中试试。

也是没权限
![image](https://github.com/jumpserver/jumpserver/assets/136363116/2929ea5a-02dd-4208-9725-07c6af9868bb)

**Comment by BaiJiangJie** [comment]
Bearer 是怎么生成的？

**Comment by BaiJiangJie** [comment]
<img width="1751" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d7783fb8-04da-434d-8043-120fc002484e">

确认了，两种方式都可以。

**Comment by guoheng888** [comment]
> <img alt="image" width="1751" src="https://private-user-images.githubusercontent.com/32935519/324731057-d7783fb8-04da-434d-8043-120fc002484e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUwNDMsIm5iZiI6MTcxMzg2NDc0MywicGF0aCI6Ii8zMjkzNTUxOS8zMjQ3MzEwNTctZDc3ODNmYjgtMDRkYS00MzRkLTgwNDMtMTIwZmMwMDI0ODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MmVhMzg0NjhlNDEzYTk2Nzg0NDEyNTgzMWIxNjJiYTg0MzY4ODQ4MjQ4MTU4MGNhZGI1OGJiYTgwMzUwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaxfBFLnOICCEjLacBuriYXjlUc87yLf6Ja0Yq3ngQQ">
> 确认了，两种方式都可以。

Bearer 是通过临时token的方式，新建一个组织的时候api获取用户列表test成功过，在新组织下面漠视创建了资产和资产授权时就复现了没有执行权限的情况。我测下看看。感谢大佬。

**Comment by guoheng888** [comment]
> <img alt="image" width="1751" src="https://private-user-images.githubusercontent.com/32935519/324731057-d7783fb8-04da-434d-8043-120fc002484e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUwNDMsIm5iZiI6MTcxMzg2NDc0MywicGF0aCI6Ii8zMjkzNTUxOS8zMjQ3MzEwNTctZDc3ODNmYjgtMDRkYS00MzRkLTgwNDMtMTIwZmMwMDI0ODRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MmVhMzg0NjhlNDEzYTk2Nzg0NDEyNTgzMWIxNjJiYTg0MzY4ODQ4MjQ4MTU4MGNhZGI1OGJiYTgwMzUwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaxfBFLnOICCEjLacBuriYXjlUc87yLf6Ja0Yq3ngQQ">
> 确认了，两种方式都可以。

Bearer 是通过临时token的方式，新建一个组织的时候api获取用户列表test成功过，在新组织下面漠视创建了资产和资产授权时就复现了没有执行权限的情况。我再多测下看看。感谢大佬。
