### ISSUE TITLE
资产管理希望加入资产到期设置及提醒筛选功能，更好管理好资产情况并优化

### ISSUE THREAD

**Issue by xiemeng00** [jumpserver/jumpserver#13089]
## 注意
我觉得可以把资产管理升级一下，现在管理的服务很多了，大多服务器都是有寿命周期的，公司服务器开一年或者两年都会到期关闭停用的。需要加一个到期时间，可以通知和筛选查看哪些服务器最近到期需要关闭的。配置升级到期也可以筛选查看并提醒，真正的管理好资产情况咯。资产都在jumpserver里了，省得手动再在另一套资产管理系统里输入到期时间了
![QQ图片20240422115555](https://github.com/jumpserver/jumpserver/assets/167733485/3a0f62ef-8ccd-41ec-ba5e-118410883a8e)
_

## 功能名称
[在这里输入功能的名称或标题]

## 功能描述
[在这里描述该功能的详细内容，包括其作用、目的和所需的功能]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by xiemeng00** [comment]
资产到期和“一键清理过期资产”的功能也请加进去。同时还需要增加“资产费用”情况。晓得资产所产生的费用情况如何，以便更好的计算和统计成本

**Comment by xiemeng00** [comment]
资产到期和“一键清理过期资产”的功能也请加进去。同时还需要增加“资产费用”情况。晓得资产所产生的费用情况如何，以便更好的计算和统计成本

**Comment by BaiJiangJie** [comment]
暂时没有这个计划，因为费用等相关的功能更像是云管平台的功能。

堡垒机更加关心的是用户的认证、账号的管理以及资产的授权、连接、审计。
