### ISSUE TITLE
[Feature] 快捷命令输出的交换机数据简化

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13082]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
快捷命令输出的交换机数据简化

## 功能描述
将输出的"stdout": 字段中的内容全部不输出，只输出"stdout_lines": 字段中的内容
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d53f5e5e-475b-4663-83c1-b14845fdcf95)

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
日志格式目前不好统一处理，有些任务需要 stdout，有些需要 stdout_lines。

目前为了日志更详细，所以选择了都输出。
