### ISSUE TITLE
jumpserver 1.3.0.2,关于LDAP接入问题

### ISSUE THREAD

**Issue by xianxichao** [jumpserver/jumpserver#1308]
[简述你的问题]

##### 使用版本
1.3.0.2

##### 问题复现步骤
1. web上已经接入LDAP并提示成功，之前测试过用ldap的账户登录Web，会在jumpserver上建立一个新的用户
2. 我们之前的旧版本是0.3.2，这次是直接迁移机器重新搭建安装新版本的，我把旧的资产数据导进来已经发现不能用ldap登录，xshell登录时会提示不存在用户，web上也不能登陆

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13365621/39855242-be5435a8-545d-11e8-98b5-fc0598b0c979.png)

##### 其他

麻烦各位大神给我解决下~~ 最好有详细点的步骤，，我比较菜鸡~~感谢~~
[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
