### ISSUE TITLE
[Question] 1Panel 安装，部署发布机时提示 pip_packages.zip 资源不存在

### ISSUE THREAD

**Issue by HugoLew** [jumpserver/jumpserver#13085]
## 当前使用的 JumpServer 版本 (必填)
[v3.10.8]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [x] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
发布机部署失败：
TASK [Set RDS RemoteAppLogoffTimeLimit (regedit)] ******************************
ok: [192.168.2.36-win-server-2019]

TASK [Download pip packages] ***************************************************
fatal: [192.168.2.36-win-server-2019]: FAILED! => {"changed": false, "dest": "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip_packages.zip", "elapsed": 0.515625, "msg": "Error downloading 'http://192.168.2.6:8080/download/applets/pip_packages.zip' to 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip_packages.zip': The remote server returned an error: (404) Not Found.", "status_code": 404, "url": "http://192.168.2.6:8080/download/applets/pip_packages.zip"}

PLAY RECAP *********************************************************************
192.168.2.36-win-server-2019 : ok=12   changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0
Task terminal.tasks.run_applet_host_deployment[e01dee38-3e8b-423b-916e-47df57fa60f6] succeeded in 161.54561529700004s: None

**Comment by HugoLew** [comment]
是这个项目中缺少文件，请尽快加一下

<img width="1356" alt="image" src="https://github.com/jumpserver/jumpserver/assets/9965339/aaeb7d9d-1367-4dbd-b379-a950536fa533">

**Comment by QYG2297248353** [comment]
临时如何解决
