### ISSUE TITLE
[Bug] v3.10.8-lts集群部署时jms_receptor容器服务无法启动

### ISSUE THREAD

**Issue by duesouth2022** [jumpserver/jumpserver#13087]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.8-lts

## 使用的版本类型 (必填)
- [ *] 社区版

## 版本安装方式 (必填)
- [ *] 离线安装 (下载离线包)

## Bug 描述 (详细)
v3.10.8-lts集群部署时jms_receptor容器服务无法启动

## 复现步骤
1. [v3.10.8-lts集群部署时jms_receptor容器服务无法启动]

## 期望行为
[jms_receptor容器可以正常启动]

## 实际行为
[v3.10.8-lts集群部署时jms_receptor容器服务无法启动，请检查下NFS是否影响jms_receptor]

## 系统环境
- 操作系统：[AnoLi7.9]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by wojiushixiaobai** [comment]
等待修复

**Comment by jym503558564** [comment]
v3.10.9 优化了，默认不开启jms_receptor，请升级进行体验。如有需要，可在config.txt 配置参数RECEPTOR_ENABLED=1。
