### ISSUE TITLE
[Feature]chen组件导出数据功能

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13093]
- 早期版本导出数据 功能，升级之前可以选择不同格式csv 或xlsx
- 升级后合并了格式不能选，默认是csv
需求分析：
12位数字，但类型位字符型，csv 格式下来就自动变为科学计数法。客户使用上不方便，一般用的就是xlsx的格式，希望回退之前csv和xlsx可选的那种机制。

**Comment by BaiJiangJie** [comment]
之前的 OmniDB 组件的时候支持 csv 和 xlsx 两种格式。
Chen 组件只支持 csv 格式。
v4 后再考虑支持 xlsx 格式。
