### ISSUE TITLE
水印后期是否考虑增加时间戳或者可以自定义水印

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13098]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[水印后期是否考虑增加时间戳或者可以自定义水印]

## 功能描述
[在这里描述该功能的详细内容，包括其作用、目的和所需的功能]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[
<img width="549" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/6b0c739f-c30b-4c93-886c-7f1e29592419">
]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
暂时不考虑支持自定义。
