### ISSUE TITLE
创建网关时提示“系统对象不存在”

### ISSUE THREAD

**Issue by menglee37** [jumpserver/jumpserver#13090]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]  **3.10.7**  是根据官方文档从2.28版本升级到3.10.7.

## 使用的版本类型 (必填)
- [√] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [√ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
先在网域列表中添加网域，然后在新建的网域中添加网关机器，添加网关时候就会报错 “系统对象不存在”；
请求url 为  https://<domain>/api/v1/assets/platforms/1/
![image](https://github.com/jumpserver/jumpserver/assets/104623946/c8742abc-3af4-4e2f-8401-49b9fc432c2b)
![image](https://github.com/jumpserver/jumpserver/assets/104623946/093dd03c-a54d-45ea-936d-1805267d9c2d)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur] 
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
这块目前有 Bug，v3.10.9 修复一下。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/3868

**Comment by jym503558564** [comment]
v3.10.9已修复创建网关提示对象不存在的问题，请升级进行体验。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/8ad841ba-01ac-42af-afb8-f4804ebd0032)
