### ISSUE TITLE
推送系统用户时报错：Failed to open session: SSH session not active

### ISSUE THREAD

**Issue by lijunlinux** [jumpserver/jumpserver#131]
系统环境：CentOS 6.5 64位
相关软件：Python 2.7.5， pip (8.1.0)  ，ansible (1.9.4)，Django (1.6)
jumpserver.log报错日志：
![image](https://cloud.githubusercontent.com/assets/12249160/13837886/7cead8c4-ec4a-11e5-904d-50a4ecc8026d.png)

**Comment by ibuler** [comment]
手动以添加的管理员用户登录试试  ssh xxx@xxx

**Comment by yumaojun03** [comment]
处理中， 请关注。

**Comment by superkzh** [comment]
重启websocket
