### ISSUE TITLE
[Question] v3.10.8 用户登录后跳转回登录页（开启了二次认证） & 终端拉起失败问题

### ISSUE THREAD

**Issue by lyitt1987** [jumpserver/jumpserver#13101]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [*] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [*] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
我升级到V3.10.8后，谷歌浏览器登录和连接异常：
1 有的同事反馈谷歌浏览器输入动态口令后又返回到登录页面
2 能登录，但是使用web终端时无法调出终端(不管是什么终端均无法调出)
   360浏览器则没有这种现象

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[谷歌浏览器124.0.6367.61（正式版本） （64 位）]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
重启电脑，升级谷歌浏览器到最新版

## 预期结果
[希望能解答此问题]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by feng626** [comment]
给一下控制台报错 或 后台日志
