### ISSUE TITLE
[Feature] 资产节点编辑需要支持整个节点移动

### ISSUE THREAD

**Issue by xxl82** [jumpserver/jumpserver#13119]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[资产节点需要支持整个节点迁移]

## 功能描述
目前节点创建好，是不可以编辑节点的层级关系的，如果需要调整节点层级，需要新建节点，然后再将资产迁移到新节点，而不能方便的将整个节点调整到指定层级，比如原本是二级的节点A，现在需要调整为一级节点AA，需要先新建这个一级节点AA，将之前的A节点中资产迁移到AA节点中，再删除原来的二级节点A。在节点数量比较多的情况下，节点细分的时候，想调整节点层级将非常麻烦。

**Comment by BaiJiangJie** [comment]
v3.10.10
