### ISSUE TITLE
[Bug] 连接VNC资产时，第一次点击全屏按钮画面显示异常

### ISSUE THREAD

**Issue by liuyy0808** [jumpserver/jumpserver#13118]
## 当前使用的 JumpServer 版本 (必填)
V3.10.9

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## Bug 描述 (详细)
连接Windows VNC资产时，第一次点击全屏按钮，网页画面全屏，但是画面内容未能全屏，需要退出全屏后，再次点击全屏按钮才能正常显示，
异常画面见下图

![image](https://github.com/jumpserver/jumpserver/assets/164499075/dffc78da-156b-4ea6-9a3a-29b9e11593bb)

正常画面见下图
![image](https://github.com/jumpserver/jumpserver/assets/164499075/a80ff077-19cf-45d0-8862-f25eca7d7c00)

## 复现步骤
1. 点击连接任意 Windows VNC资产
2. 点击视图，全屏显示      显示异常，网页能全屏，但是画面还是原来的大小
3. 退出网页全屏
4. 再次点击视图，全屏显示，画面显示正常

## 期望行为
期望每次连接资产后，第一次点击全屏显示就可以正常显示，不用退出全屏第二次点击全屏显示

**Comment by LeeEirc** [comment]
线下联系处理，已经优化，待后续新版本发布。

**Comment by BaiJiangJie** [comment]
v3.10.10
