### ISSUE TITLE
[Bug] 命令过滤功能设置了高危命令拦截，在资产上执行时，针对同一条命令有时候放行有时候拦截

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#13117]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.6

## 使用的版本类型 (必填)
企业试用版

## 版本安装方式 (必填)
离线安装 (下载离线包)

## Bug 描述 (详细)
设置命令过滤规则后，针对同一条命令有时候放行有时候拦截

## 复现步骤
1. 设置命令组，正则表达式：kubectl .* 命令过滤规则拒绝执行，优先级50
2. 设置命令组，正则表达式：kubectl get|top|describe|logs .* 命令过滤额规则接受执行，优先级40
3. 实际执行时，有时成功执行，有时被拦截

## 期望行为
正常拦截高危命令

## 实际行为
同一条命令偶尔未进行拦截

## 系统环境
- 操作系统：MAC OS
- 浏览器/应用版本：124.0.6367.60（正式版本） (arm64)
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]
![image](https://github.com/jumpserver/jumpserver/assets/89773363/523298bb-b268-4263-b64b-d271f7f8be51)

**Comment by BaiJiangJie** [comment]
图片中有三条，第1、2、3分别是如何输入的？
复制、粘贴还是上下键？

**Comment by lyons-hz** [comment]
> 图片中有三条，第1、2、3分别是如何输入的？ 复制、粘贴还是上下键？

第一条是copy，第2、3条是上键

**Comment by BaiJiangJie** [comment]
每次 copy 都拦截不了吗？还是概率性的？

**Comment by BaiJiangJie** [comment]
命令解析这一块确实有点问题，不能非常精准的 100% 还原命令。还在持续改进中。

**Comment by lyons-hz** [comment]
感谢
