### ISSUE TITLE
[Bug] 当jumpServer修改2222端口后  luna下主机用SSH Client链接超时

### ISSUE THREAD

**Issue by increase0102** [jumpserver/jumpserver#13121]
SSH Client的客户端JumpServerClient.exe应该是写死2222端口当jumpServer修改2222为别的端口后SSH Client链接超时，无法是使用JumpServerClient.exe

**Comment by BaiJiangJie** [comment]
按照 Bug 模版提交！

**Comment by increase0102** [comment]
![微信图片_20240425151848](https://github.com/jumpserver/jumpserver/assets/34668500/ed87d0cd-f727-49aa-b785-5f10c40c0f7f)
![微信图片_20240425151855](https://github.com/jumpserver/jumpserver/assets/34668500/036cd7af-bcd9-40ef-b840-7d131e3ca937)
