### ISSUE TITLE
[Bug] v3.10.8的jmsctl.sh没有升级选项

### ISSUE THREAD

**Issue by xxl82** [jumpserver/jumpserver#13125]
## 当前使用的 JumpServer 版本 (必填)
[v3.10.8]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## Bug 描述 (详细)
看v3.10.9版本出来了，想着升级，结果到v3.10.8的目录中执行jsmctl.sh的时候发现没有check_update参数
![image](https://github.com/jumpserver/jumpserver/assets/31279129/99eab0d5-ec5c-417c-ab79-c0b592af7635)

**Comment by wojiushixiaobai** [comment]
参考官方文档进行升级，版本差异过大，暂时去掉了入口。
