### ISSUE TITLE
后台配置ldap服务，ou组内只有一个用户可用，其他用户报错

### ISSUE THREAD

**Issue by lls205** [jumpserver/jumpserver#13124]
## 当前使用的 JumpServer 版本 (必填)
3.9.3

## 使用的版本类型 (必填)
社区版 

## 版本安装方式 (必填)
离线安装 (下载离线包)

## Bug 描述 (详细)
接入ldap，ou配置的组，无法获取到组下的用户，测试LDAP 用户登录提示“认证失败 (用户名或密码不正确): failed to map the username to a DN.”，但ldap那边的组下有这个用户的

## 复现步骤
1. ldap添加组，组里添加已有的用户，当前只有test1用户可登录

## 期望行为
多个用户都可以测试登录通过，正常test2也可以登录

## 实际行为
测试LDAP 用户登录报错

## 系统环境
- 浏览器/应用版本：chrome

## 附加信息（可选）
![image](https://github.com/jumpserver/jumpserver/assets/16010476/b87cea31-6369-4239-814e-a00d61155eda)
![image](https://github.com/jumpserver/jumpserver/assets/16010476/92554261-a7e5-4ec2-a202-8fc5087755b1)
![image](https://github.com/jumpserver/jumpserver/assets/16010476/5777f3ad-ffdf-4550-b2cf-8ef83cf93f4f)

**Comment by BaiJiangJie** [comment]
测试登录时没有获取到这个用户。

**Comment by lls205** [comment]
我用ldap admin工具创建的，ldapsearch查到的信息这个组下面也是有这几个用户，为啥这里获取不到；测试添加了几个组，一直都是只能获取到test1这个用户。

**Comment by lls205** [comment]
jms我退出当前用户，使用test2也是提示登录不上，只有test1这个用户可以正常登录

**Comment by BaiJiangJie** [comment]
那应该是 OU 配置的不对，尝试 OU 直接配置到 dc 级别。

**Comment by lls205** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16010476/1b535c39-a8ba-47d4-9fc1-43d1fa036492)
![image](https://github.com/jumpserver/jumpserver/assets/16010476/e778bbad-a063-4c53-b937-c2ddd43ded3c)
现在是怎么样都只有test1用户有效，其他用户都不行，是不是有啥缓存之类的

**Comment by wojiushixiaobai** [comment]
过滤器错误，过滤器的语法自己参考下相关文档。

如果是要匹配特定 CN 属性的人，需要使用 memberOf，否则你应该指定 OU

**Comment by lls205** [comment]
我看了网上的过滤器，这样写提示错误
![image](https://github.com/jumpserver/jumpserver/assets/16010476/74d68ad9-4442-4ce7-9526-71f61438bd4b)
![image](https://github.com/jumpserver/jumpserver/assets/16010476/78b2aee1-c4fa-4b74-ab55-8acea3fe6c65)

**Comment by BaiJiangJie** [comment]
<img width="879" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/29b9217e-3033-4da6-8b66-2e0d4fd00240">

你的 OU 配置的不对。

**Comment by BaiJiangJie** [comment]
<img width="291" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/2dfb64ad-0458-47c0-b4fb-0467ae1c0ec9">

把 ou=new 也去掉，只保留后面的 dc,dc

**Comment by lls205** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/16010476/98b956f3-081f-44ac-bdb8-ccd29c802355)
ou去掉了，还是这个错误提示

**Comment by BaiJiangJie** [comment]
过滤器还原会最开始的状态。

**Comment by lls205** [comment]
用户 OU：ou=new,dc=xxx,dc=com
用户过滤器：(cn=%(user)s)
最开始的状态是这样，测试连接是正常的

我现在改成
用户 OU：ou=new,dc=xxx,dc=com
用户过滤器：(&(cn=%(user)s)(memberOf=CN=jms,OU=new,DC=xxx,DC=com))
也是不行的

**Comment by BaiJiangJie** [comment]
用户 OU：dc=xxx,dc=com
用户过滤器：(cn=%(user)s)

现在改成这样去测试。

**Comment by lls205** [comment]
我知道问题了，用memberOf过滤，ldap创建组的属性不能是posixGroup，需要是groupOfUniqueNames
