### ISSUE TITLE
[Feature] 发布机部署任务取消

### ISSUE THREAD

**Issue by QYG2297248353** [jumpserver/jumpserver#13120]
发布及部署时间长是一个问题，有的资源用Nginx代理有的应用 chrome之类的 下载超久，我也不理解。
部署了一个晚上 我看过了 服务器 powershell 网速仅有 12kb,真心不理解

今早安装应用，一上午都在安装，我想取消任务重新部署应用，但是找不到办法，服务器重启也无法终止此任务
![image](https://github.com/jumpserver/jumpserver/assets/56836951/317addf4-6a77-4835-ac39-f5e4366e9aee)
![image](https://github.com/jumpserver/jumpserver/assets/56836951/81684b5d-8deb-47b7-b79c-ac5caf2cf0db)

但是我重新部署该应用很快就提示完成了，实际能不能用没测试，但是页面显示还是失败

就问，如何结束掉这个无法完成的部署任务

**Comment by QYG2297248353** [comment]
#10953 
我有再这里询问相关后续问题，之前发布机部署就卡进度。但是似乎需要等待

**Comment by QYG2297248353** [comment]
部署应用不行
结束 powershell 和 重启 windows 发布机 不管用
这一招仅针对发布机部署
![image](https://github.com/jumpserver/jumpserver/assets/56836951/ea908b82-303b-4f9e-bd42-4b162713805f)

**Comment by wojiushixiaobai** [comment]
我的回答只针对无法结束的任务，按照我的说法一定可以结束，服务器都重启了不可能任务还在执行。

部署卡住的问题是网络导致的，安装的文件很大，你可以手动下载文件后拷贝到对应的目录。

**Comment by QYG2297248353** [comment]
额，部署应用确实结束不了，我只能删除发布机，文件大能不能让用户手动安装，发布机部署做检查，有的就不在重复部署

**Comment by QYG2297248353** [comment]
> 具体结束不了是指什么？截图看看？ 如果你是指你发的那张图，那个可以忽略。只是显示问题

显示问题，那就实属心里别扭。
gitea仓库我看了，下载是个大问题，根本克隆不下来
https://gitea.com/jumpserver/web-static.git

github仓库空空如也 只找到个 pip_packages.zip

**Comment by wojiushixiaobai** [comment]
@QYG2297248353 分支没有，看 tag 
- https://gitea.com/jumpserver/web-static/src/tag/v1.1.3
