### ISSUE TITLE
[Bug] window服务器无法远程(网络不可达|安全策略错误) 

### ISSUE THREAD

**Issue by wintsa123** [jumpserver/jumpserver#13135]
## 当前使用的 JumpServer 版本 (必填)
3.9.3

## 使用的版本类型 (必填)
- [ √] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [√ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
 window服务器无法远程(网络不可达|安全策略错误) 

我有两台相同配置的服务器，相同系统，winserver2012
但是链接A正常，链接B显示(网络不可达|安全策略错误) 。
A和B用window自带的远程控制都能链接，B的系统日记应用里面显示 
```js
从远程客户端应用程序收到一个  TLS 1.2 连接请求，但没有任何受客户端应用程序支持的密码套件是受服务器支持的。SSL 连接请
```

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12851#issuecomment-2078694898

试一下这种方式。

**Comment by wintsa123** [comment]
> [#12851 (comment)](https://github.com/jumpserver/jumpserver/issues/12851#issuecomment-2078694898)
> 
> 试一下这种方式。


尝试了，依旧不行，在服务器上看到日记
```bash
生成了一个严重警告并将其发送到远程终结点。这会导致连接终止。TLS 协议所定义的严重错误代码是 40。Windows SChannel 错误状态是 1205。
```
也许是我的winserver没打开安装远程相关的？

**Comment by BaiJiangJie** [comment]
也有可能，你试试。
一台可以一台不可以，大概率是机器配置问题。
自行研究一下。
