### ISSUE TITLE
[Bug] 快捷命令同时获取多个主机的信息时内容缺失

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13139]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>

## 当前使用的 JumpServer 版本 (必填)
3.10.9

## 使用的版本类型 (必填)
- [  ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [  ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
在快捷命令里同时勾选多个主机获取打量数据时，获取的结果中会有内容缺失，没有报错
我勾选5个华为交换机获取端口模块信息，输出的结果中只有2-3个主机的信息，其他信息没有了

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
提供一下截图。

**Comment by ryswork1993** [comment]
> 提供一下截图。
勾选了4太华为S系列交换机
![image](https://github.com/jumpserver/jumpserver/assets/44529247/592587f2-a3df-4fea-bbd8-63526ccd2319)

**Comment by BaiJiangJie** [comment]
没有显示 2-3 台，又报错吗？

单独勾选执行会有输出吗？

**Comment by ryswork1993** [comment]
我选2-3台输出数据少的话，输出内容是全的，也没报错选4台以上不知道是不是因为数据量多，输出没报错，但数据不全等我晚上后选5台，然后输出数据少点，看是否输出全-------- 原始邮件 --------发件人： Bryan ***@***.***>日期： 2024年4月28日周日 18:09收件人： jumpserver/jumpserver ***@***.***>抄送： ryswork1993 ***@***.***>, Author ***@***.***>主    题： Re: [jumpserver/jumpserver] [Bug] 快捷命令同时获取多个主机的信息时内容缺失 (Issue #13139)
没有显示 2-3 台，有报错吗？
单独勾选执行会有输出吗？

**Comment by ryswork1993** [comment]
> 没有显示 2-3 台，有报错吗？
> 
> 单独勾选执行会有输出吗？
勾选4台交换机，数据量不大，输出正常
![image](https://github.com/jumpserver/jumpserver/assets/44529247/3ae170cb-d028-43db-ad89-bea416b80e1e)
[shortcut_cmd_c1d97623-14f3-4980-b66f-5702a2c1c277.log](https://github.com/jumpserver/jumpserver/files/15142014/shortcut_cmd_c1d97623-14f3-4980-b66f-5702a2c1c277.log)

**Comment by ryswork1993** [comment]
> 没有显示 2-3 台，有报错吗？
> 
> 单独勾选执行会有输出吗？

我勾选了13台设备，每个设备输出10行内，输出全部正常，没有报错也没有缺少内容

**Comment by BaiJiangJie** [comment]
只有华为设备吗？还是大批量 Linux 主机也会有输出内容缺失的问题？

**Comment by ryswork1993** [comment]
> 只有华为设备吗？还是大批量 Linux 主机也会有输出内容缺失的问题？
linux我勾选了15台左右，每个主机输出20行左右，没有报错，没有缺失内容

**Comment by BaiJiangJie** [comment]
使用原生 Ansible 执行一下，看看效果。如果原生的没问题，我们再排查。
