### ISSUE TITLE
[Bug] 远程应用浏览器下载文件问题，求解决方案

### ISSUE THREAD

**Issue by abc5588** [jumpserver/jumpserver#13137]
jumpserver 3.10.9 社区版, 在线一键安装的. 并配置好了远程应用.

使用远程应用打开google浏览器，设置下载下载路径为【\\tsclient\JumpServer\Download】
从远程应用浏览器中打开下载文件：https://shujufw.lcev.cn/1.doc 进行下载

当设置的下载路径不要download时，下载1.doc文件是完全正常的。能正常下载。

当下载路径加了download 时，它的下载地址就变成了下面这样
https://我的jumpserver域名.com/lion/api/tunnels/%241664710f-839a-4d9e-bcf2-131b910784d5/streams/0/a7f7ba23-c90d-4262-a5cc-81504325f034.tmp

发现：如果下载路径不加download时，文件能正常下载, 是下载到了服务器，不是我要的。

下载路径加了download时，文件是直接下载到了我本地电脑的，完全符合我要的。但是下载时，文件变了。求解决方案。

**Comment by BaiJiangJie** [comment]
没太看懂是什么意思，有录像吗？

**Comment by ryswork1993** [comment]
> 没太看懂是什么意思，有录像吗？

怎么把远程应用浏览器下载目录自定义成\tsclient\JumpServer\Download这个目录，我也试试，我的远程应用浏览器没有设置选项

**Comment by abc5588** [comment]
视频录像 请见：https://wx.mail.qq.com/ftn/download?func=3&key=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&code=6a6d9445&k=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&fweb=1&cl=1

**Comment by abc5588** [comment]
> > 没太看懂是什么意思，有录像吗？
> 
> 怎么把远程应用浏览器下载目录自定义成\tsclient\JumpServer\Download这个目录，我也试试，我的远程应用浏览器没有设置选项

视频录像 请见：https://wx.mail.qq.com/ftn/download?func=3&key=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&code=6a6d9445&k=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&fweb=1&cl=1

**Comment by BaiJiangJie** [comment]
录像视频我看了，你通过原生的 guacamole 试一下是不是同样的情况。

**Comment by BaiJiangJie** [comment]
确认了一下，正常是不支持设置下载路径的。

你能设置是因为你在 web 远程应用中新窗口打开了新的 Tab，所以出现了浏览器的选项。

**Comment by abc5588** [comment]
> 确认网关，正常是不支持设置下载路径的。
> 您可以设置是因为您在网络远程应用中新闻窗口打开了新的选项卡，所以出现了浏览器的选项。

是的，新增加了窗口，给浏览器设置下载路径。 
那么这个问题【设置下载路径为\tsclient\JumpServer\Download】时。该如何解决让其下载文件非tmp缓存，而是正常文件呢？

**Comment by abc5588** [comment]
@BaiJiangJie 是的，手动设置了下载路径。那怎么让下载路径为【\\tsclient\JumpServer\Download】时，让下载的文件是正常文件，而不是tmp缓存呢？
