### ISSUE TITLE
资产中打开浏览器使用Ctrl快捷键进行复制粘贴异常

### ISSUE THREAD

**Issue by ljclour** [jumpserver/jumpserver#13138]
## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [√] 社区版

## 版本安装方式 (必填)
- [√] 离线安装 (下载离线包)

## Bug 描述 (详细)
在添加Windows远程资产中，打开浏览器，在浏览器中使用Ctrl相关的快捷键，并不能按常规的效果，需要加上Shift才能实现正常的效果。如
Ctrl +C：正常的时候是复制。不正常的时候是打开了浏览器的开发者工具。这时候按Ctrl + Shift + C则可以实现复制功能。
Ctrl +V：正常的时候是粘贴。不正常的时候是没有相应的。这时候按Ctrl + Shift + V则可以实现粘贴功能。
Ctrl +F：正常的时候是搜索。不正常的时候是没有相应的。这时候按Ctrl + Shift + F则可以实现搜索功能。

## 复现步骤
目前没有到可以复现具体步骤，不是所有添加了的资产都有这样的问题，有时候重新登录，这种情况会消失。
## 期望行为
添加Windows远程资产中，能够正确的使用Ctrl +C和Ctrl+V等一系列的Ctrl相关快捷键。

## 实际行为

Ctrl +C：正常的时候是复制。不正常的时候是打开了浏览器的开发者工具。这时候按Ctrl + Shift + C则可以实现复制功能。
Ctrl +V：正常的时候是粘贴。不正常的时候是没有相应的。这时候按Ctrl + Shift + V则可以实现粘贴功能。
Ctrl +F：正常的时候是搜索。不正常的时候是没有相应的。这时候按Ctrl + Shift + F则可以实现搜索功能。

## 系统环境
- 操作系统：[Windows 10]

**Comment by BaiJiangJie** [comment]
你指的是 Chrome 远程应用，还是使用 Chrome 连接 JumpServer 时创建 Web 资产？

**Comment by ljclour** [comment]
> 你指的是在 Chrome 远程应用资产中的操作，还是使用本地 Chrome 连接 JumpServer 时的操作？

是第一种情况。本地Chrome连接Win资产，在Win资产中打开Chrome浏览器，在里面操作就会偶尔出现这种快捷键异常的情况。
![资产操作](https://github.com/jumpserver/jumpserver/assets/45123712/d76c5d2f-c39b-4af0-90bd-9c4858760937)

**Comment by BaiJiangJie** [comment]
这种情况很正常，很容易和本地的一些应用冲突，打开右侧齿轮⚙️ 有快捷键列表。

**Comment by ljclour** [comment]
> 应该是和你本地的一些应用冲突了。我测试了一下 Ctrl + c/v 是没问题的。

暂时没办发找到具体有冲突的应用。就像我之前说的，同一个资产，可能用着用着就出现这种情况的，并不是一直都有。而且有些时候重新退出jumpserver，再登录又可以解决问题的 😢
