### ISSUE TITLE
[Bug] 卸载发布机里的远程应用，当该应用有关联资产时，卸载失败，但该应用的图标在发布机-应用列表及远程应用列表中消失，卸载逻辑需优化

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#13134]
##当前使用的 JumpServer 版本 (必填)
V3.10.9

## 使用的版本类型 (必填)
企业版

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
卸载发布机里的远程应用，当该应用有关联资产时，卸载失败，但该应用的图标在发布机-应用列表及远程应用列表中消失，卸载逻辑需优化

## 复现步骤
1. 选择一个已关联资产的远程应用，在应用发布机-远程应用列表中点击卸载；
2. 重复步骤1，再次卸载该应用；

## 期望行为
1. 卸载失败，并弹窗提示该应用有关联资产，无法卸载，且应用图标信息均保留，能继续正常使用；
2. 与步骤1的期望保持一致；

## 实际行为
1. 卸载失败，并弹窗提示；但原应用图标在发布机-应用列表和远程应用列表中均消失
2. 没有弹窗提示，能正常执行卸载操作，但实际应用未卸载。

## 系统环境
不涉及

## 附加信息（可选）
![image](https://github.com/jumpserver/jumpserver/assets/92150453/a76b7ba9-0244-45a4-b856-8275ec0b0de6)

**Comment by BaiJiangJie** [comment]
没有复现这个问题。
