### ISSUE TITLE
[Bug]windows分辨率不生效

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13133]
新版本自3.10.7版本后windows分辨率不生效，试了3.9.2的一些旧版本正常，其他版本未知。

**Comment by BaiJiangJie** [comment]
强制刷新一下前端。

**Comment by jym503558564** [comment]
v3.10.9测试正常，无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/f8587f43-b0ed-47a8-97e0-71f87f0b74d1)
![image](https://github.com/jumpserver/jumpserver/assets/40739051/8944bc3c-a199-4dca-a9eb-6748a0daa645)

**Comment by guoheng888** [comment]
> v3.10.9测试正常，无法复现 ![image](https://private-user-images.githubusercontent.com/40739051/326322159-f8587f43-b0ed-47a8-97e0-71f87f0b74d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM2NDgsIm5iZiI6MTcxNDM3MzM0OCwicGF0aCI6Ii80MDczOTA1MS8zMjYzMjIxNTktZjg1ODdmNDMtYjBlZC00N2E4LTk3ZTAtNzFmODdmMGI3NGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMWMzZWE2YzA0ZTJlOTA1YzhmNjliZDMwOTk2MjZlYmM5YTI4MWExNDVmNDkwYmJhM2E1ZjY0OGMxYTY2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6p88Tob-k-AASd2B1zidmcPUHpTTTLmfqfQzqueGVk) ![image](https://private-user-images.githubusercontent.com/40739051/326322196-8944bc3c-a199-4dca-a9eb-6748a0daa645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM2NDgsIm5iZiI6MTcxNDM3MzM0OCwicGF0aCI6Ii80MDczOTA1MS8zMjYzMjIxOTYtODk0NGJjM2MtYTE5OS00ZGNhLWE5ZWItNjc0OGEwZGFhNjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZmU4NmJlZjQwZDRiNTE0MmMxYTEwZmQ3ZWU0ZjYwZTUzYWE5OWJhMGI1NDVkMTMwZDhhYTg1ZjM0OGU3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J17WGkBtrd9z5xGQmSFImsUysV7wGoyA-opZdJ1JYvo)
除了显示的参数，不同分辨率效果看一下1920X1080和1024x768的实际显示效果，3.10.9和3.10.7的感觉不出来，3.10.8正常，测试了有明显区别。

**Comment by guoheng888** [comment]
> v3.10.9测试正常，无法复现 ![image](https://private-user-images.githubusercontent.com/40739051/326322159-f8587f43-b0ed-47a8-97e0-71f87f0b74d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM2NDgsIm5iZiI6MTcxNDM3MzM0OCwicGF0aCI6Ii80MDczOTA1MS8zMjYzMjIxNTktZjg1ODdmNDMtYjBlZC00N2E4LTk3ZTAtNzFmODdmMGI3NGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMWMzZWE2YzA0ZTJlOTA1YzhmNjliZDMwOTk2MjZlYmM5YTI4MWExNDVmNDkwYmJhM2E1ZjY0OGMxYTY2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X6p88Tob-k-AASd2B1zidmcPUHpTTTLmfqfQzqueGVk) ![image](https://private-user-images.githubusercontent.com/40739051/326322196-8944bc3c-a199-4dca-a9eb-6748a0daa645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM2NDgsIm5iZiI6MTcxNDM3MzM0OCwicGF0aCI6Ii80MDczOTA1MS8zMjYzMjIxOTYtODk0NGJjM2MtYTE5OS00ZGNhLWE5ZWItNjc0OGEwZGFhNjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZmU4NmJlZjQwZDRiNTE0MmMxYTEwZmQ3ZWU0ZjYwZTUzYWE5OWJhMGI1NDVkMTMwZDhhYTg1ZjM0OGU3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J17WGkBtrd9z5xGQmSFImsUysV7wGoyA-opZdJ1JYvo)

大佬除了显示的参数，不同分辨率效果看一下1920x1080和1024x768的实际显示效果，3.10.9和3.10.7的感觉不出来，3.10.8正常，测试了有明显区别

**Comment by BaiJiangJie** [comment]
升级到最新版本试试，之前版本有问题。
