### ISSUE TITLE
[Question] ssh websocket断开

### ISSUE THREAD

**Issue by wochicheng** [jumpserver/jumpserver#13141]
## 注意
**请描述您的问题.** <br>
我之前安装了jumpserver。我最近遇到的问题是ssh 超时。当我 ssh 到服务器时，经常会出现ssh断开。当我使用 Jumpserver 连接到服务器时会发生这种情况。其他 SSH 客户端没有问题。
## 当前使用的 JumpServer 版本 (必填)
v3.10.6

## 使用的版本类型 (必填)
- [* ] 社区版

## 版本安装方式 (必填)
- [* ] 在线安装 (一键命令)

## 问题描述 (详细)
最开始安装的几周没有出现ssh无故断开的现象
近两周现在经常出现ssh断开，有的时候连接不到1分钟就自动断开，有的时间过了很久才自动断开
如图所示，命令行连接和浏览器连接都出现了该问题
![image](https://github.com/jumpserver/jumpserver/assets/62383904/734c3cff-766d-44b1-8080-7081f9d08d2d)

## 背景信息
- 操作系统：Ubuntu 22.04.3 LTS
- 浏览器/应用版本：[chrome]
- 其他相关环境信息：[命令行工具]

## 具体问题
这是koko的包含“eof”的日志
![image](https://github.com/jumpserver/jumpserver/assets/62383904/0997a8e8-cea2-4189-9ef8-d4b8411de3c8)
![image](https://github.com/jumpserver/jumpserver/assets/62383904/f6a07950-7018-4fff-b6dd-1fae02b97c7e)

## 尝试过的解决方法
我查看过nginx配置，为默认的超时配置
![image](https://github.com/jumpserver/jumpserver/assets/62383904/260d99a8-af38-48b5-a982-11eea80a8889)
我加了超时次数到20，仍会出现该问题
<img width="612" alt="image" src="https://github.com/jumpserver/jumpserver/assets/62383904/353e8b11-d2fe-456b-8300-171ed56c0660">
我增加了jumpserver服务器的内存和核数，但是仍会出现该问题
<img width="1914" alt="image" src="https://github.com/jumpserver/jumpserver/assets/62383904/8b7fe1d2-9d5e-4fe6-8475-6d14c2696253">

## 预期结果
不再出现该问题

## 我们的期望
解决该问题

**Comment by BaiJiangJie** [comment]
网络环境怎么样？

默认的 nginx 之上还有其他 nginx 吗？

**Comment by wochicheng** [comment]
没有nginx，网络环境如下
员工----云枢vpn-----jumpserver-----服务器
     外网｜内网

**Comment by BaiJiangJie** [comment]
那应该是 vpn 的问题，这种情况大概率是网络环境不问题导致的。
