### ISSUE TITLE
web终端：localhost 拒绝了我们的连接请求。

### ISSUE THREAD

**Issue by FangTangJing** [jumpserver/jumpserver#13148]
## 注意
![image](https://github.com/jumpserver/jumpserver/assets/24773663/7a877b31-fc24-43d8-982a-bffcd1344c8f)

## 当前使用的 JumpServer 版本 (必填)
3.10.9

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
![image](https://github.com/jumpserver/jumpserver/assets/24773663/6922fe01-496e-4f6a-8ada-1bea87756f4c)

## 问题描述 (详细)
![image](https://github.com/jumpserver/jumpserver/assets/24773663/c666c8d6-b3b1-4aac-9d17-07a205c5d037)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13053#issuecomment-2071951498

看一下 服务端点列表、看一下 nginx 的配置。
