### ISSUE TITLE
[Bug] 资产的账号密码第一位为0，导出CSV格式时0不显示，Excel格式没问题。

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13140]
[JumpServer版本3.10.9]

## 使用的版本类型 (必填)
- [√] 企业版
- [√] 企业试用版
企业版和企业试用版都复现成功。

## 版本安装方式 (必填)
- [√] 离线安装 (下载离线包)

## Bug 描述 (详细)
账号导出功能异常，具体表现为，在配置了MFA认证和文件加密密码之后，导出CSV格式的账号表格。如果密码首位为0，则表中密码从第二位显示，不显示0，表格格式调整为文本等类型时也不显示0,。导出Excel格式时密码正常显示。

## 复现步骤
1. 堡垒机添加Linux资产和Windows资产，并且给相关资产添加以0为首字母的密码。
2. 堡垒机配置文件加密密码和双因素认证。
3. 在账号管理---账号列表导出CSV格式的账号表格，解压之后查看密码。

## 期望行为
[在导出CSV格式的账号列表时密码可以正确显示]

## 系统环境
- 操作系统：[例如：Windows 10]
- 浏览器/应用版本：[chrome和edge]
- 其他相关环境信息：[]

## 附加信息（可选）
[
1. 下图为在堡垒机上查看托管的资产账号密码截图：
![Linux资产账号密码](https://github.com/jumpserver/jumpserver/assets/156915989/babd56cc-2b71-4497-9920-f3e0c8ab2929)
![Windows资产账号密码](https://github.com/jumpserver/jumpserver/assets/156915989/9f64c2e0-1859-4de2-ae45-35e9fd676b9a)
2. 下图为导出CSV格式的表格查看账号密码的截图：
![CSV格式的账号表格截图](https://github.com/jumpserver/jumpserver/assets/156915989/a2d61fdd-b4e9-42a5-a435-dd5636589adf)
]

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/13143

v3.10.10 优化。
