### ISSUE TITLE
[Bug] Magnus 透明代理 SQL 命令行审计显示不正确

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [jumpserver/jumpserver#13142]
## 当前使用的 JumpServer 版本 (必填)
3.10.6

## 使用的版本类型 (必填)
-企业版

## 版本安装方式 (必填)
 离线安装 (下载离线包)

## Bug 描述 (详细)
通过透明代理的方式连接 PostgreSQL 数据库，命令行审计显示异常。

## 复现步骤
1、通过本地客户端连接 pgsql ， 执行一条 update 的sql ，有实际更新数据的。
<img width="803" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/16be4527-b1bd-45ae-b88b-1127f9ca27f6">

2、命令行审计，显示 0 rows affected
<img width="849" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30264974/c4102040-a332-4d9d-9e42-0424724140b8">

## 期望行为
正常应该显示为 1 updated Rows 。

**Comment by Aaron3S** [comment]
![image](https://github.com/user-attachments/assets/8aacff05-62e3-4d3f-b394-9bdd9b88d88f)
本地未复现这个情况

**Comment by BaiJiangJie** [comment]
未复现，请提供复现环境。
