### ISSUE TITLE
[Bug] 使用Ctrl+C可以绕过命令过滤的拦截

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#13149]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.6
## 使用的版本类型 (必填)
企业试用版

## 版本安装方式 (必填)
离线安装 (下载离线包)

## Bug 描述 (详细)
设置命令过滤规则后，先输入白名单命令，ctrl+C取消，再输入应该被拦截的命令，可以正常执行

## 复现步骤
1. 设置命令组，正则表达式：.* 命令过滤规则拒绝执行所有命令，优先级50
2. 设置命令组，正则表达式：^(mysql|git|ssh).+ 命令过滤额规则接受执行，优先级40
3. 连接资产后，输入ssh ，再输入ctrl+C取消，再输入其他任何命令，均可执行
<img width="1046" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89773363/f5149a8d-d0da-4767-a293-d1db38dad994">

## 期望行为
正常拦截黑名单命令

## 实际行为
命令过滤未进行拦截

## 系统环境
操作系统：MAC OS
浏览器/应用版本：124.0.6367.60（正式版本） (arm64)
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
是的，目前这块命令过滤的逻辑还在支持优化中。
