### ISSUE TITLE
[Bug] 工作台资产列表重复显示

### ISSUE THREAD

**Issue by Jackie-Pan** [jumpserver/jumpserver#13154]
##当前使用的 JumpServer 版本
[3.10.9]

##使用的版本类型
- [x] 社区版

##版本安装方式 
- [x] 在线安装 (一键命令)

##Bug 描述 (详细)
![image](https://github.com/jumpserver/jumpserver/assets/52104725/f16d83ce-855e-4f40-a49f-0f98d73638f8)
如图所示，工作台中的资产都是显示两条重复的，但是总数是对的
最近几个小版本更新后就出现这个问题，且一直未恢复

## 期望行为
[资产列表正常显示]

## 系统环境
- 操作系统：[ubuntu 20.04]
- 浏览器/应用版本：[Google chrome及Microsoft edge最新版本]

**Comment by BaiJiangJie** [comment]
强制刷新一下呢

**Comment by Jackie-Pan** [comment]
> 强制刷新一下呢

没用，就一直是这样。刷新，升级版本，重启都试过

**Comment by jym503558564** [comment]
可以远程看下问题吗？

**Comment by Jackie-Pan** [comment]
社区版，具体哪个版本开始出现的已经记不得了，应该是3.9或者3.10开始的。什么时间方便远程？

> 可以远程看下问题吗？

**Comment by Jackie-Pan** [comment]
意外发现这个现象只在部分账号上出现，在排查用户组、权限设置等设置的影响后，通过删除用户重新同步设置用户组后恢复正常。

**Comment by BaiJiangJie** [comment]
好的，目前还没有收到其他用户的类似问题反馈。
后面如果能稳定复现再进行处理。
