### ISSUE TITLE
[Question] web资产

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13157]
## 注意
**请描述您的问题.** <br>
怎么将应用发布机浏览器下载目录设置成\\tsclient\JumpServer\Download
怎么显示应用发布机的设置选项，我的不显示
![image](https://github.com/jumpserver/jumpserver/assets/44529247/c7834c7b-20fd-4514-878b-8449ff09c181)

## 当前使用的 JumpServer 版本 (必填)
3.10.9

## 使用的版本类型 (必填)
- [  ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [  ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在这里描述你遇到的问题]

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
不支持设置。
有些 Web 网页会在新窗口中打开，会出现浏览器的设置选项，产品本身是不支持的。
