### ISSUE TITLE
How could I set permission in Command ACL for allow specific command and deny all?

### ISSUE THREAD

**Issue by Garrybac** [jumpserver/jumpserver#13150]
Hello,

Is there a way to create permission for Command Acl to allow specific commands and deny all other commands?

Thanks,

**Comment by BaiJiangJie** [comment]
Deny all commands ACL priority 50
Whitelist command ACL priority 40

**Comment by BaiJiangJie** [comment]
<img width="1565" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/75efc379-b832-46b0-9fab-690e4ccb4215">

**Comment by BaiJiangJie** [comment]
`.*`  You can use regular expressions.

**Comment by Garrybac** [comment]
Hello,
Thank you. I have set for allowance to 40 priority and disallow all commands to 50 priority. However, I still can't run allowance command.
Thanks

**Comment by BaiJiangJie** [comment]
Take a look at your command filtering ACLs and command groups.

**Comment by Garrybac** [comment]
![Allow Command Filter](https://github.com/jumpserver/jumpserver/assets/117132103/c9eb8705-4328-4b80-a8fb-409c3db68b11)
![Command Group](https://github.com/jumpserver/jumpserver/assets/117132103/1cd33671-a8bf-4406-ac31-afffc486ae0a)
![Disallow Command](https://github.com/jumpserver/jumpserver/assets/117132103/a721c620-03ad-4438-940e-bfccc56b4c2c)

**Comment by Garrybac** [comment]
I have created command group for deny all command and other for allow command exit.
But I still can't use exit command.

**Comment by BaiJiangJie** [comment]
<img width="1147" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/b66b9edf-0be7-4481-9d68-ef25b09b5aa5">

**Comment by BaiJiangJie** [comment]
Make sure the command group type is regular expression.
At the same time, the command filtering ACL also selects the assets, users, and accounts to be operated.

It is best to provide an update page for command filtering ACLs and command groups, as complete as possible.

**Comment by Garrybac** [comment]
![Allow Command Group](https://github.com/jumpserver/jumpserver/assets/117132103/772abacb-5f7c-4c2f-b416-c55378579120)
![Allow Filter](https://github.com/jumpserver/jumpserver/assets/117132103/a998184c-0c01-4ede-b145-49a7acf52900)
![Disallow Command Group](https://github.com/jumpserver/jumpserver/assets/117132103/9216f00b-4f3f-4575-ac58-0533ea517449)
![Disallow Filter](https://github.com/jumpserver/jumpserver/assets/117132103/74b40e33-4583-48fb-8447-ce8d679ba2ce)

**Comment by Garrybac** [comment]
Hello,

Please help to correct me.

Thanks,

**Comment by Garrybac** [comment]
Hello,
I have fixed it by adding * in Command filter name.
Thank you for your support.
Thanks,

**Comment by BaiJiangJie** [comment]
Your version is relatively old, it is recommended to upgrade to the latest version.

**Comment by BaiJiangJie** [comment]
Okay, you're welcome.

**Comment by Garrybac** [comment]
> Your version is relatively old, it is recommended to upgrade to the latest version.

I have new version already. But I haven't import the assets then I tested on old one first.
Thank for your recommended.
Thanks
