### ISSUE TITLE
后端服务器只允许秘钥登录，添加服务器后，显示不可连

### ISSUE THREAD

**Issue by jaikewhh166** [jumpserver/jumpserver#1315]
[简述你的问题]
     后端服务器只允许秘钥登录，添加服务器后，显示不可连

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
jumpserver 1.3.0
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/39252581/39976468-834d3fb6-5766-11e8-85a0-02c6c5989fe2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
系统设置-终端设置，取消密码认证。保存后重启jumpserver

**Comment by jaikewhh166** [comment]
![image](https://user-images.githubusercontent.com/39252581/39984933-53e220ce-578f-11e8-9c7a-029bba8dac35.png)

ansible推送用户或获取服务器信息，也需要走秘钥，这个秘钥需要从哪里传到ansible去

**Comment by jaikewhh166** [comment]
ssh密钥不合法  私钥传不上去，这个私钥是通过secureCRT生成的，我登录系统用的就是这个私钥文件，不应该不合法啊

**Comment by gengkeye** [comment]
@jaikewhh166 @wojiushixiaobai 
我也遇到了这个问题，按照
```系统设置-终端设置，取消密码认证。保存后重启jumpserver```
操作之后，仍然无法连接。
