### ISSUE TITLE
远程应用使用DBeaver连接MySQL，打开黑屏

### ISSUE THREAD

**Issue by ztskycn** [jumpserver/jumpserver#13156]
## 注意
**请描述您的问题.** <br>
远程应用使用DBeaver连接MySQL，第一次可以连接（打开DBeaver界面），后面再次连就不行了，没有报错就是黑屏。升级到最新的0.2.3版本的DBeaver也是一样。查看lion日志报出来。

2024/04/30 11:20:29 5.audio,1.1,31.audio/L16; instruction with bad Content: 5.audio,1.1,31.audio/L16
[GIN] 2024/04/30 - 11:20:32 | 200 |      46.184µs |             ::1 | GET      "/lion/health/"
[GIN] 2024/04/30 - 11:20:42 | 200 |      58.342µs |             ::1 | GET      "/lion/health/"
[GIN] 2024/04/30 - 11:20:52 | 200 |      52.125µs |             ::1 | GET      "/lion/health/"
2024-04-30 11:20:53 tunnel conn.go [ERROR] Session[13494e07-d825-47f6-b3ab-7927b0340442] guacamole server read err: EOF
[GIN] 2024/04/30 - 11:20:54 | 200 | 25.133473349s |     1.1.1.1  | GET      "/lion/ws/connect/?SESSION_ID=13494e07-d825-47f6-b3ab-7927b0340442&GUAC_WIDTH=1229&GUAC_HEIGHT=643&GUAC_DPI=96&GUAC_KEYBOARD=en-us-qwerty&GUAC_IMAGE=image%2Fjpeg&GUAC_IMAGE=image%2Fpng&GUAC_IMAGE=image%2Fwebp&GUAC_AUDIO=audio%2FL8&GUAC_AUDIO=audio%2FL16"

**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
3.10.9 社区版，Docker在线升级安装。
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在这里描述你遇到的问题]

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
看一下远程应用发布机上的，tinker 日志。

**Comment by ztskycn** [comment]
C:\Users\Administrator\AppData\Local\Programs\Tinker\data\logs\remote:
2024-04-30 13:55:08 [INFO] Logoff session 6 by windows event

**Comment by ztskycn** [comment]
> 多看几行，看看有没有 ERROR 日志。

没有其它日志了，ERROR日志在哪个路径？我看logs目录下面只有remote文件。

**Comment by LeeEirc** [comment]
每一次打开远程应用的画面都是黑屏吗？可以观察下打开使用的 windows 账号名称是否一样？

**Comment by ztskycn** [comment]
> 每一次打开远程应用的画面都是黑屏吗？可以观察下打开使用的 windows 账号名称是否一样？

第一次可以打开，后面就打开就一直黑屏。使用的Windows账号名字都是一样的，jms_我的用户名。

**Comment by LeeEirc** [comment]
不应该每次都是调度到相同的 `jms_我的用户名`, 看看你发布机账号列表是否生成了足够多的公共账号。

**Comment by ztskycn** [comment]
> 不应该每次都是调度到相同的 `jms_我的用户名`, 看看你发布机账号列表是否生成了足够多的公共账号。

应该有所有的公共账号，jms_随机账号和jms_存在的用户名

**Comment by LeeEirc** [comment]
重新初始化发布机和应用，再测试下。
