### ISSUE TITLE
[Question] manage user access time

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#13158]
Hi,
Can I manage user access time?
Such as: only allowing access from 8:00 a.m. to 5:00 p.m. daily

**Comment by BaiJiangJie** [comment]
Yeah，sure.

You can set it in the permission management user login ACL.

**Comment by tsukiazuma** [comment]
> Yeah，sure.
> 
> You can set it in the permission management user login ACL.

It have only on Enterprise version?
I using Communication

**Comment by tsukiazuma** [comment]
I can see i. Thank you
