### ISSUE TITLE
[Feature] 支持 ssh tunnel 

### ISSUE THREAD

**Issue by Patrick0308** [jumpserver/jumpserver#13151]
## 功能名称
支持 ssh tunnel 

## 功能描述
跳版机支持建立 ssh tunnel

## 用户故事（可选）
我知道已经有几个 issue 已经提到了这个功能，这个功能因为不符合你们可审计原则被拒绝了。

但是在云原生本地开发环境中需要k8s 集群与本地环境机器的互通。

在我们的实际的本地开发场景中会使用 [telesperence](https://www.telepresence.io/) 连接测试 k8s 环境做本地联调，之前我们在本地与 boundary 管理的跳板机建立 ssh tunnel ，基于跳板机访问 k8s 集群。

当然如果有直接安全的能本地访问 k8s apiserver 方案也能解决我们的问题。

## 功能要求
- 能够跳板机之间建立 ssh tunnel

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

**Comment by LeeEirc** [comment]
使用类似以下正向代理的方式开启 ssh tunnel 吗？

```
ssh -NL 1080:192.168.122.1:8000 root@jms_koko 
```

**Comment by Patrick0308** [comment]
> koko 

是的

**Comment by Patrick0308** [comment]
> 使用类似以下正向代理的方式开启 ssh tunnel 吗？
> 
> 
> 
> ```
> 
> ssh -NL 1080:192.168.122.1:8000 root@jms_koko 
> 
> ```
> 
> 

是的

**Comment by LeeEirc** [comment]
不支持，koko 启动 sock5 动态代理，也不符合安全的要求。后续会研究下针对授权资产的 ssh tunnel 代理。

**Comment by Patrick0308** [comment]
@LeeEirc  ssh socket 代理不是通过 ssh tunnel 实现的吗？实现了 ssh tunnel 会不会就已经支持了 socket 代理？

**Comment by LeeEirc** [comment]
不会让 koko 的节点进行动态转发，转发的 ssh tunnel 需要针对特定的资产地址。

**Comment by jixuuse** [comment]
这种功能就是方便从受限环境盗窃源码、保密数据的吧
