### ISSUE TITLE
[Feature] 授权新增或修改交互体验优化

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#13165]
## 功能名称
授权新增或修改使用体验优化

## 功能描述
希望在权限管理列表，点击创建或更新时能够打开新的标签页进行操作。

## 用户故事（可选）
当前资产列表新增或更新时，会打开新的标签页，原标签页会保持节点展开状态，这对于持续添加或修改比较友好。然而在授权规则列表添加/更新授权时是在当前页面操作，操作完成后节点展开状态重置了，可能导致要重复去展开节点，对于节点层次较多的不太友好，希望能优化一下

## 功能要求
- 在权限管理列表，点击创建或更新时能够打开新的标签页进行操作。

## 示例或原型（可选）
参照资产添加/更新的交互（打开新标签页）

**Comment by BaiJiangJie** [comment]
v4 版本中会考虑优化的。v3 版本暂时不考虑了。

**Comment by gerry-fit** [comment]
好的
