### ISSUE TITLE
[Question] 如何调整终端健康状况磁盘使用率告警阈值

### ISSUE THREAD

**Issue by zeng202211** [jumpserver/jumpserver#13160]
**如何调整终端健康状况磁盘使用率告警阈值** <br>
**JumpServer 版本: v3.10.9** <br>
社区版
在线安装 (一键命令)

## 问题描述 (详细)
需要调整这个磁盘使用率的告警阈值, 不清楚如何调整
![image](https://github.com/jumpserver/jumpserver/assets/126559759/8e9d86c4-4242-4270-b0f8-793b23ee037c)

方便的话, 麻烦告知, 谢谢

**Comment by BaiJiangJie** [comment]
目前不支持调节。
