### ISSUE TITLE
[Feature] 多台发布机，如何确定每次连接远程应用使用的发布机？希望能看到远程应用每次连接使用的发布机记录。

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13168]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
多台发布机，如何确定每次连接远程应用使用的发布机？希望能看到远程应用每次连接使用的发布机记录。

## 功能描述
场景：
有多台发布机，需要达到负载均衡的效果，只能使用随机发布机，不能使用标签关联。
因为是使用的随机的发布机，如果连接远程应用出了问题，希望能够获知使用哪台发布机连接出的问题，不希望一台台发布机去排查，直接查看lion日志也不太好，如果有每次连接使用的发布机记录，就会很方便。

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
v4 中计划将使用的发布机信息放到会话的 comment 中。
