### ISSUE TITLE
[Question] 华为交换机作业中心执行命令报错

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#13163]
![image](https://github.com/jumpserver/jumpserver/assets/19767613/3b00afe9-83f7-41d4-825c-c4182016c26d)

#版本 v3.10.9
如图，作业中心-快捷命令，操作华为网络设备。
执行命令会报错，想了解下问题是出在docker里面，还是宿主机。
有什么可以解决的方法

**Comment by w940853815** [comment]
```
screen-length 0 temporary
display interface brief
```
试一下呢？

**Comment by ryswork1993** [comment]
> ![image](https://private-user-images.githubusercontent.com/19767613/328232511-3b00afe9-83f7-41d4-825c-c4182016c26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTMyOTgsIm5iZiI6MTcxNTA1Mjk5OCwicGF0aCI6Ii8xOTc2NzYxMy8zMjgyMzI1MTEtM2IwMGFmZTktODNmNy00MWQ0LTgyNWMtYzQxODIwMTZjMjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjdjODI3NWM2NzljNzM3NjcxYzhjOWFhNDAyNWY3ZmRhODM4M2QzNjE5NTU1ZDRkOGVhMTYyY2M1NThiNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D14c8Evm9RUWRRHcd-Ckg1de4BWzFODKCWFQTxt0mPM)
> 
> #版本 v3.10.9 如图，作业中心-快捷命令，操作华为网络设备。 执行命令会报错，想了解下问题是出在docker里面，还是宿主机。 有什么可以解决的方法

你的华为设备平台选择的是什么

**Comment by wellsyu** [comment]
> ```
> screen-length 0 temporary
> display interface brief
> ```
> 
> 试一下呢？@wellsyu

简写和全写是一样的结果

**Comment by w940853815** [comment]
> > ```
> > screen-length 0 temporary
> > display interface brief
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试一下呢？@wellsyu
> 
> 简写和全写是一样的结果

其他命令能执行不？还是只有这个命令报错了？

**Comment by wellsyu** [comment]
> ```
> screen-length 0 temporary
> display interface brief
> ```
> 
> 试一下呢？@wellsyu
screen-length 0 temporary 
这句加了能输出结果，是什么原因呐？

**Comment by w940853815** [comment]
> > ```
> > screen-length 0 temporary
> > display interface brief
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试一下呢？@wellsyu
> > screen-length 0 temporary
> > 这句加了能输出结果，是什么原因呐？

已知问题，命令输出带--more--的话就会报错，这个还在找解决办法，临时解决就可以设置命令全部输出，不显示--more--

**Comment by wellsyu** [comment]
> > > ```
> > > screen-length 0 temporary
> > > display interface brief
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 试一下呢？@wellsyu
> > > screen-length 0 temporary
> > > 这句加了能输出结果，是什么原因呐？
> 
> 已知问题，命令输出带--more--的话就会报错，这个还在找解决办法，临时解决就可以设置命令全部输出，不显示--more--

![image](https://github.com/jumpserver/jumpserver/assets/19767613/1c670942-faec-4548-b249-d0aee348c237)
输出的结果的格式，还是不宜读的

**Comment by wellsyu** [comment]
> > ![image](https://private-user-images.githubusercontent.com/19767613/328232511-3b00afe9-83f7-41d4-825c-c4182016c26d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTMyOTgsIm5iZiI6MTcxNTA1Mjk5OCwicGF0aCI6Ii8xOTc2NzYxMy8zMjgyMzI1MTEtM2IwMGFmZTktODNmNy00MWQ0LTgyNWMtYzQxODIwMTZjMjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAzMzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjdjODI3NWM2NzljNzM3NjcxYzhjOWFhNDAyNWY3ZmRhODM4M2QzNjE5NTU1ZDRkOGVhMTYyY2M1NThiNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D14c8Evm9RUWRRHcd-Ckg1de4BWzFODKCWFQTxt0mPM)
> > #版本 v3.10.9 如图，作业中心-快捷命令，操作华为网络设备。 执行命令会报错，想了解下问题是出在docker里面，还是宿主机。 有什么可以解决的方法
> 
> 你的华为设备平台选择的是什么

1楼已经解答了，谢谢

**Comment by w940853815** [comment]
> > > > ```
> > > > screen-length 0 temporary
> > > > display interface brief
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 试一下呢？@wellsyu
> > > > screen-length 0 temporary
> > > > 这句加了能输出结果，是什么原因呐？
> > 
> > 
> > 已知问题，命令输出带--more--的话就会报错，这个还在找解决办法，临时解决就可以设置命令全部输出，不显示--more--
> 
> ![image](https://private-user-images.githubusercontent.com/19767613/328404610-1c670942-faec-4548-b249-d0aee348c237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjI5ODEsIm5iZiI6MTcxNTA2MjY4MSwicGF0aCI6Ii8xOTc2NzYxMy8zMjg0MDQ2MTAtMWM2NzA5NDItZmFlYy00NTQ4LWIyNDktZDBhZWUzNDhjMjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA2MTgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWUwMTk2N2NhYTUxMzViYWZjODA3NGM2OTJhOWY0ZDAwYjlkZjcyN2QxNWY5MWRmOGVmYzZkZDE1ZTVmYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyVQHkrnS2D7uZiro-yWDrlYkdR_s_AAuV4onIYUEZw) 输出的结果的格式，还是不宜读的

输出里面的stdout_lines 应该易读吧
