### ISSUE TITLE
[Question] 资产探活

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13176]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.10.9

## 使用的版本类型 (必填)
- [  ] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [  ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/484ecbc9-5a16-4f9e-8bb7-be490cb4e2b0)
这里勾选之后，不是自动探活的吗，还需要在业务中心手动设置资产探活吗

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
是的，不是自动探活的，开启表示支持探活。
