### ISSUE TITLE
[Question] 请问在 iPhone, iPad (iOS) 上Safari浏览器中使用Web终端, 如何输入Ctrl+C, Home, Insert, 上下左右这些常用快捷键？

### ISSUE THREAD

**Issue by tracking** [jumpserver/jumpserver#13170]
## 问题
**请问在 iPhone, iPad (iOS) 上Safari浏览器中使用Web终端, 如何输入Ctrl+C, Home, Insert, 上下左右这些常用快捷键？** <br>

## 当前使用的 JumpServer 版本
v3.10.9

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [x] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
请问在 iPhone, iPad (iOS) 上Safari浏览器中使用Web终端, 如何输入Ctrl+C, Home, Insert, 上下左右这些常用快捷键(不外接键盘的情况下)？

目前用快捷命令解决了一部分问题, 但用起来很别扭. 比如Ctrl+C, 我是通过直接输入ASCII码的方式录入快捷命令, 发送的时候总是多给我加了一个`\r`, 很难受(见下图)
![image](https://github.com/jumpserver/jumpserver/assets/5705827/57afca99-4adf-4853-b90e-926502f57584)

找过社区和Issues, 好像没有人遇到和我一样的问题, 也可能是我没找对方法或者孤陋寡闻了.
请教一下是否有更好的方法.

**Comment by BaiJiangJie** [comment]
目前好像没有办法输入组合键和模拟特殊键盘操作场景。

![image](https://github.com/jumpserver/jumpserver/assets/32935519/47ac06a3-2d65-4027-b678-852187e6db6f)

v4+ 版本之后考虑在右侧弹窗中内置一些快捷键。

**Comment by BaiJiangJie** [comment]
![image](https://github.com/user-attachments/assets/05884f7e-87fa-4136-9b82-11af0d43f7be)

v4.2.0 版本已上线。
