### ISSUE TITLE
[用户列表可根据系统角色筛选]

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13178]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[在这里输入功能的名称或标题]

## 功能描述
[用户列表可根据系统角色筛选，这里有下拉框的，是否考虑做个筛选]

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]
<img width="1211" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/b0efca45-7d81-4a71-ad44-85f4bc0a5a6d">

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
<img width="1414" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/d0a38f9b-94b8-4b16-b28b-861e7768d37f">

搜索框进行搜索。
