### ISSUE TITLE
[Question] API创建账号，回显报错内容不符

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#13173]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.10.7]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[通过/api/v1/accounts/accounts/ 这个接口创建账号，回显报错，但是post数据根据api文档进行指定的，内容如下：
代码：
]
```
    def create_accounts_accounts(self):
        url = self.host + '/api/v1/accounts/accounts/'
        signature_headers = ['(request-target)', 'accept', 'date', 'host']
        headers = {
            'Accept': 'application/json',
            'Date': str(time.strftime("%a, %d %b %Y %H:%M:%S GMT", time.gmtime()))
        }
        auth = HTTPSignatureAuth(key_id=self.keyid, secret=self.secret,
                                 algorithm='hmac-sha256',
                                 headers=signature_headers)
        # data = {
        #     "username": "zhouxinyu",
        #     "secret_type": {"value": "ssh_key", "label": "SSH 密钥"},
        #     "asset": {
        #         "id": "f8968fe1-a6ce-4a94-aa03-3a3a03fdd510",
        #         "name": "prd-jumpserver-2",
        #         "address": "172.27.232.27"
        #     }
        # }
        data = {
            "username": "zhouxinyu",
            "secret_type": {
                "value": "passwd",
                "label": "密码"
            },
            "asset": {
                # "id": "f8968fe1-a6ce-4a94-aa03-3a3a03fdd510",
                "name": "prd-jumpserver-2",
                "address": "172.27.232.27"
            },
            "privileged": 'false',
            "is_active": 'true',
            "push_now": 'false'
        }
        req = requests.post(url,auth=auth,headers=headers,json=data)
        return json.loads(req.content)
```
报错内容：
```
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2651, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ["“{'name': 'prd-jumpserver-2', 'address': '172.27.232.27'}”不是一个有效的UUID"]

```
截图所示，双引号显示都不对，不知道后端这个是啥？
![image](https://github.com/jumpserver/jumpserver/assets/48144475/a5dc92b8-96b7-43b5-8a04-de1516a64eb2)

## 尝试过的解决方法
[按照api文档进行操作，并没有得到预期效果]

## 预期结果
[希望可以得到预期效果]

## 我们的期望
[可以指出错误之处，不胜感激]

**Comment by BaiJiangJie** [comment]
<img width="847" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/982b9a15-4710-4be8-826a-6a0663ebba75">

asset 参数的值，
要么是 
```
"asset": {
    "id": "ASSET ID"
}
```

要么是 

`"asset": "ASSET ID"`

不然会将后面的整体 value 作为 id 进行处理，就看到的是报错的信息。

**Comment by cuijianzhe** [comment]
> <img alt="image" width="847" src="https://private-user-images.githubusercontent.com/32935519/328786120-982b9a15-4710-4be8-826a-6a0663ebba75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTE4MDYsIm5iZiI6MTcxNTE1MTUwNiwicGF0aCI6Ii8zMjkzNTUxOS8zMjg3ODYxMjAtOTgyYjlhMTUtNDcxMC00YmU4LTgyNmEtNmEwNjYzZWJiYTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2NTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWZkODI5ZmMzODc4MGJhZjY0OTI3ZjdkN2Q2ZDQyM2NiOGM3ZWRmYzE3YTU2NWFmODEwMzQ0YTc2MDMwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jsy2vNojpWzn7uK3VtHjd3TZlPmwNziZ_v6LS9XS_4w">
> asset 参数的值， 要么是
> 
> ```
> "asset": {
>     "id": "ASSET ID"
> }
> ```
> 
> 要么是
> 
> `"asset": "ASSET ID"`
> 
> 不然会将后面的整体 value 作为 id 进行处理，就看到的是报错的信息。

API文档是整体的，而且name和address还是必填项，需要分开填写？
![image](https://github.com/jumpserver/jumpserver/assets/48144475/225e4cb2-2060-4de3-b831-c2de2030713b)

![image](https://github.com/jumpserver/jumpserver/assets/48144475/68ce5695-a259-4d0a-a360-288ec3239eb8)
