### ISSUE TITLE
Error RDP 

### ISSUE THREAD

**Issue by srkaviani** [jumpserver/jumpserver#13179]
I get this error after add windows-rdp asset on test and refresh.
Please help. 

![image](https://github.com/jumpserver/jumpserver/assets/90821955/39a01586-c277-44e3-b03f-e10540819f71)

**Comment by feng626** [comment]
Windows supports adding ssh protocol

**Comment by srkaviani** [comment]
How can i solve this problem? i need to add windows rdp assets.

**Comment by BaiJiangJie** [comment]
Take a look at your windows asset details.
