### ISSUE TITLE
[Question] 能否通过API读取作业的输出？

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#13171]
目前来看，作业的输出（stdout/stderr）是通过websocket传输到浏览器上查看的。我没有找到API接口能读取到作业输出，是否有接口？如果没有，将来有没有计划添加？

**Comment by BaiJiangJie** [comment]
`http://127.0.0.1/core/ops/celery/task/c13fb7a0-5f18-49e6-a719-96d4e80f094d/log/`

中间的 uuid 就是执行任务返回的 taskID

<img width="1147" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/bd8e6f35-ba5f-40d2-8e9d-bea1d6f28389">

**Comment by rty813** [comment]
@BaiJiangJie 这样得到的是一个终端页面，然后实际内容仍然是通过websocket传输的
![image](https://github.com/jumpserver/jumpserver/assets/22488813/76436028-41a3-4ea0-8e22-301c17347baf)
![image](https://github.com/jumpserver/jumpserver/assets/22488813/c626a2da-01aa-4197-9132-48e43ce5c97a)

**Comment by rty813** [comment]
我希望能得到文本格式的，或者说机器可读的，例如json格式这样的输出结果。
