### ISSUE TITLE
账号列表必现 504 

### ISSUE THREAD

**Issue by QooGeek** [jumpserver/jumpserver#13180]
版本v3.10.9、

然后什么也没操作、设备的资源一直占用很高，没排查思路了

<img width="1679" alt="image" src="https://github.com/jumpserver/jumpserver/assets/31933126/e3faaf24-8651-44f9-903d-b455c1b66bb8">

<img width="1678" alt="image" src="https://github.com/jumpserver/jumpserver/assets/31933126/c82329e6-181f-42e0-8038-7ebdeedeaf9f">

**Comment by BaiJiangJie** [comment]
看看是后端服务的哪个进程占用资源比较高

**Comment by QooGeek** [comment]
jumpserver/core-ce 点击账号列表的时候，这个服务占用资源很高

**Comment by BaiJiangJie** [comment]
可以验证一下是否是 密钥 8192 导致的吗？

> 我猜测可能是我的各个资产的 ssh 密钥是 8192 的，导致的 jumpserver/core-ce 这个服务占用资源很高，点击账号列表加载的时候超时了

**Comment by QooGeek** [comment]
我有两台 jumpserver、配置一模一样、唯一不一样的就是这个ssh 密钥，第一台默认的1024密钥没有这个问题。

比如说，我30多个主机，3个账号、用的密钥都是 8192 的。然后点击这个账号列表的时候。core 资源占用率一直很高。导致加载超时。

**Comment by BaiJiangJie** [comment]
好的，看看本地来复现一下。

@jym503558564

**Comment by BaiJiangJie** [comment]
@QooGeek 
30+ 主机 3 个账号，总共的账号列表有多少？90+？

**Comment by jym503558564** [comment]
待修复

**Comment by QooGeek** [comment]
@BaiJiangJie 是，你可以复现看看、主要涉及到账号密钥的地方，都加载很慢很慢，其中账号列表加载不出来的100%复现。

**Comment by QooGeek** [comment]
@jym503558564 辛苦了，谢谢

**Comment by BaiJiangJie** [comment]
v3.10.10-lts 版本中会解决。
