### ISSUE TITLE
新创建用户访问web终端无资产问题，资产授权在创建用户时已做授权，

### ISSUE THREAD

**Issue by shaohuayangfit2** [jumpserver/jumpserver#13184]
## 
JumpServer 版本( v3.10.7 )
新创建用户访问web终端无资产问题，资产授权在创建用户时已做授权，
1，登录堡垒机后资产列表无资产，刷新后资产列表才会展示比较慢。
2，web终端也是一样无资产信息，需要等资产列表刷新后才会展示。

## 使用的版本类型 
- [x] 企业版

## 版本安装方式 (必填)
- [x] 离线安装 (下载离线包)

## 期望行为
创建用户，第一次登录后，可以看到资产树，并进行连接；

## 系统环境
- 操作系统：[例如：Windows 10]

https://github.com/jumpserver/jumpserver/assets/47516608/bd7d531a-fbd4-4ff2-9e2b-2fc8991bf5e3

**Comment by BaiJiangJie** [comment]
v3.10.10 版本资产总数超过 5000 的 延迟 20s 刷新。
