### ISSUE TITLE
[Bug] 授权mhyuser，会同时把mhyuser(sshkey)也授权上

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13185]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>

## 当前使用的 JumpServer 版本 (必填)
v3.10.9

## 使用的版本类型 (必填)
企业版

## 版本安装方式 (必填)
离线安装 (下载离线包)

## Bug 描述 (详细)
授权mhyuser，会同时把mhyuser(sshkey)也授权上。希望可以根据名称授权。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/eb34678c-862a-4b47-8969-6106e40ebf16)
而且加了密码、密钥两个账号，web登录的时候会放到一块。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/743d224a-ebb2-4299-89fe-ac2087f9db8a)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
希望可以根据名称授权。

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
目前是这样的策略，只支持通过 username 授权。
