### ISSUE TITLE
雪崩  windows连接断开后会进行录像转码存储非常耗费cpu

### ISSUE THREAD

**Issue by niugengtian** [jumpserver/jumpserver#13189]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>

## 当前使用的 JumpServer 版本 (必填)
[Version v3.10.9]

## 使用的版本类型 (必填)

- [ x] 企业版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [x ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
![image](https://github.com/jumpserver/jumpserver/assets/33859108/0ff20e57-e972-4351-a53c-4946269cd308)
![image](https://github.com/jumpserver/jumpserver/assets/33859108/c3d94e82-3c0e-47c0-b566-5faf8fea708a)
经过关闭录像一段时间定位到
连接断开后 会进行转码 压缩 转移目录等 非常吃cpu
同时多个连接断开引发雪崩

## 复现步骤
1. 连接20个windows rdp 进行录像 时间维持在两小时一上
2. 同时关闭20个windows rdp 连接 
3.cpu炸了
## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by niugengtian** [comment]
建议把连接断开后的任务 转码 压缩 转移目录这些任务 放在另外一台机器上执行 不要影响连接

**Comment by LeeEirc** [comment]
可以在单独的服务上部署 video-worker，减少录像转码的影响

**Comment by LeeEirc** [comment]
用添加配置可以控制转码的数量 

```
VIDEO_WORKER_COUNT=2
```

**Comment by niugengtian** [comment]
我让服务团队试试

**Comment by niugengtian** [comment]
> ```
> VIDEO_WORKER_COUNT=2
> ```

这个地方 是限制转码队列数2  不会丢录像吧？ 另外 有没有地方限制这个录像文件的大小？ 比如切割成100M一个 太大的话你们的播放器不支持500M以上 用浏览器的player 不好拖动定位

**Comment by LeeEirc** [comment]
不会丢失，录像已经留存在服务器上了。转码已经是压缩之后的录像了。对于不同的操作会话情况，录像大小是不一样的。

**Comment by niugengtian** [comment]
> 不会丢失，录像已经留存在服务器上。转码之后已经是压缩的录像了。对于不同的操作会话情况，录像大小是不一样的。

我这个服务器主要用来连接windows 远程工作 所以在线时间比较长 每个小时应该有几百M的样子 不能切割吗 linux的话根本就不存在这个问题 一天的命令也没1m

**Comment by LeeEirc** [comment]
暂时无法切割。Windows 录像与 Linux 录像的格式有区别，Linux 是字符数据，本身占用比较小。Windows 是图形数据，包含各种操作的图片，相对大一些。

**Comment by niugengtian** [comment]
> 用添加配置可以控制转码的数量
> 
> ```
> VIDEO_WORKER_COUNT=2
> ```

jumpserver/config/config.txt 直接写入这里 然后重启？

**Comment by LeeEirc** [comment]
> > 用添加配置可以控制转码的数量
> > ```
> > VIDEO_WORKER_COUNT=2
> > ```
> 
> jumpserver/config/config.txt 直接写入这里 然后重启？

是的，重启服务。

**Comment by niugengtian** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/33859108/337af1d3-eb0b-4bb4-bd5c-df4b0740ad08)

此处默认是否 我用脚本生成的rdp文件会疯狂闪退 请帮帮我吧 我要把这个复用默认是 不要默认否

**Comment by niugengtian** [comment]
告诉我哪个表字段 默认值否 对应哪个 是 对应哪个 谢谢

**Comment by niugengtian** [comment]
我现在一百多号人  一百多个资产 两千多用户 要生成2000多的rdp文件 3.10.3没这个问题啊 3.10.9 多了这个is_reusable的默认值吧？

**Comment by LeeEirc** [comment]
代码怎么写的？是不是有报错了？生成的 rdp 文件对吗？

**Comment by niugengtian** [comment]
文件是对的 但是 只能用一次 不能复用

**Comment by niugengtian** [comment]
import json
import urllib.parse

import requests
from openpyxl import load_workbook

# JumpServer base url
JUMPSERVER_BASE_URL = 'http:/192.168.1.1'
# 组织 ID，默认组织
JUMPSERVER_ORG_ID = '00000000-0000-0000-0000-000000000002'
# 文件路径
XLSX_PATH = './堡垒机账号密码.xlsx'

# 读取的文件 Sheet
WORKSHEET = 'Sheet1'
# 文件路径
OUT_XLSX_PATH = './账号密码清单结果.xlsx'
# 读取的文件 Sheet
OUT_WORKSHEET = 'Sheet1'


def get_token_info(username, password):
    auth = {
        'username': username,
        'password': password
    }
    url = urllib.parse.urljoin(JUMPSERVER_BASE_URL,'/api/v1/authentication/auth/')
    response = requests.post(url, data=auth)
    response_data = response.json()
    if response.status_code != 201 and response.status_code != 200:
        raise Exception('Failed to authenticate to Jumpserver')
    return response_data



"""
curl --location 'https://jumps3.fit2cloud.com/api/v1/authentication/connection-token/' \
--header 'Authorization: Bearer XYQsOjxJ75uajfICYHyujutdOIrIQTclmQo7' \
--header 'X-Jms-Org: 00000000-0000-0000-0000-000000000002' \
--form 'account=administartor' \
--form 'asset=65f3f417-cecc-4519-b02f-3c6eb86f782a' \
--form 'connect_method="mstsc"' \
--form 'protocol="rdp"' \
--form 'is_active=true' \
--form 'is_reusable=true'
"""
def convert_body(account, asset_id):

    body = {
        "account": account,  # 名称
        "asset": asset_id,  # 资产ID
        "connect_method": "mstsc",
        "protocol": "rdp",
        "is_active": True,  # 激活
        "connect_options": {
            "charset": "default",
            "disableautohash": False,
            "resolution": "auto",
            "backspaceAsCtrlH": False,
            "appletConnectMethod": "web",
            "reusable":True
        }
    }
    return body


def get_connection_token(rid: int, token: str, body: dict):
    headers = {
        "Authorization": "Bearer " + token,
        "X-JMS-ORG": JUMPSERVER_ORG_ID,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
    }
    url = urllib.parse.urljoin(JUMPSERVER_BASE_URL, '/api/v1/authentication/connection-token/')
    res = requests.post(url, json=body, headers=headers)
    if res.status_code != 201 and res.status_code != 200:
        print("第 %d 行创建 CONNECT_TOKEN 失败：%s" % (rid, res.text))
    data = res.json()
    return data.get('id')

def get_perm_assets(rid: int, token, user_id):
    headers = {
        "Authorization": "Bearer " + token,
        "X-JMS-ORG": JUMPSERVER_ORG_ID,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
    }
    url = JUMPSERVER_BASE_URL + f'/api/v1/perms/users/self/assets/'
    res = requests.get(url, headers=headers)
    if res.status_code != 201 and res.status_code != 200:
        print("第 %d 行获取资产失败：%s" % (rid, res.text))
    data = res.json()
    return data


def get_account(rid: int, token, asset_id):
    headers = {
        "Authorization": "Bearer " + token,
        "X-JMS-ORG": JUMPSERVER_ORG_ID,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
    }
    url = JUMPSERVER_BASE_URL + f'/api/v1/perms/users/self/assets/{asset_id}/'
    res = requests.get(url, headers=headers)
    if res.status_code != 201 and res.status_code != 200:
        print("第 %d 行获取账号失败：%s" % (rid, res.text))
    data = res.json()
    return data.get("permed_accounts")

def run():
    # 加载 Excel 文件
    workbook = load_workbook(filename=XLSX_PATH)

    # 选择要读取的工作表
    worksheet = workbook[WORKSHEET]

    # 加载 Excel 文件
    workbook_out = load_workbook(filename=OUT_XLSX_PATH)

    # 选择要读取的工作表
    worksheet_out = workbook_out[OUT_WORKSHEET]

    # 遍历行并打印单元格的值
    rid = 0
    nrid = 2
    
    worksheet_out.cell(row=1, column=1, value="店铺")
    worksheet_out.cell(row=1, column=2, value="内网远程ip")
    worksheet_out.cell(row=1, column=3, value="资产id")
    worksheet_out.cell(row=1, column=4, value="使用人")
    worksheet_out.cell(row=1, column=5, value="使用人UUID")
    worksheet_out.cell(row=1, column=6, value="accountsUUID")
    worksheet_out.cell(row=1, column=7, value="accounts名称")
    worksheet_out.cell(row=1, column=8, value="user临时token")
    worksheet_out.cell(row=1, column=9, value="连接串")

    for row in worksheet.iter_rows():
        rid += 1
        if rid == 1:
            continue
        if row[0] is None:
            break
        try:
            token_info = get_token_info(row[1].value, row[2].value)
            token =  token_info.get("token")
            user_id = token_info.get("user").get("id")
            user_name = token_info.get("user").get("username")
            perm_assets = get_perm_assets(rid, token, user_id)
            if perm_assets == []:
                continue
            for perm_asset in perm_assets:
                asset_name = perm_asset.get("name")
                asset_ip = perm_asset.get("address")
                asset_id = perm_asset.get("id")
                accounts = get_account(rid, token, asset_id)
                if accounts == []:
                    continue
                for account in accounts:
                    worksheet_out.cell(row=nrid, column=1, value=asset_name)
                    worksheet_out.cell(row=nrid, column=2, value=asset_ip)
                    worksheet_out.cell(row=nrid, column=3, value=asset_id)
                    worksheet_out.cell(row=nrid, column=4, value=user_name)
                    worksheet_out.cell(row=nrid, column=5, value=user_id)
                    worksheet_out.cell(row=nrid, column=6, value=account.get("id"))
                    worksheet_out.cell(row=nrid, column=7, value=account.get("name"))
                    worksheet_out.cell(row=nrid, column=8, value=token)
                    body = convert_body(account.get("name"), asset_id)
                    connect_token = get_connection_token(rid, token, body)
                    worksheet_out.cell(row=nrid, column=9, value=connect_token)
                    nrid += 1
                

        except Exception as e:
            print('第 %d 行错误：%s' % (rid, e))
    workbook_out.save(OUT_XLSX_PATH)


if __name__ == '__main__':
    run()

**Comment by niugengtian** [comment]
import pandas as pd
import os


def generate_files(excel_path, internal_template_path, external_template_path, output_dir):
    # Load the account information from an Excel file
    account_info_df = pd.read_excel(excel_path, sheet_name='Sheet1')

    # Read the content of the template files
    with open(internal_template_path, 'r') as file:
        internal_template_content = file.read()
    with open(external_template_path, 'r') as file:
        external_template_content = file.read()

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Iterate through the DataFrame rows
    for index, row in account_info_df.iterrows():
        # Construct the filenames
        internal_filename = f"{row['使用人']}_{row['accounts名称']}_{row['内网远程ip']}_internal.rdp"
        external_filename = f"{row['使用人']}_{row['accounts名称']}_{row['内网远程ip']}_external.rdp"

        # Replace the username placeholders in the templates
        new_username_internal = f"username:s:{row['使用人']}|{row['连接串']}"
        new_username_external = f"username:s:{row['使用人']}|{row['连接串']}"

        internal_content_modified = internal_template_content.replace("username:s:niuhuanxi|chuanchuanchuan",
                                                                      new_username_internal)
        external_content_modified = external_template_content.replace("username:s:niuhuanxi|chuanchuanchuan",
                                                                      new_username_external)

        # Save the modified templates to new RDP files
        internal_file_path = os.path.join(output_dir, internal_filename)
        external_file_path = os.path.join(output_dir, external_filename)

        with open(internal_file_path, 'w') as file:
            file.write(internal_content_modified)
        with open(external_file_path, 'w') as file:
            file.write(external_content_modified)


# Example usage
generate_files('账号密码清单结果.xlsx', 'internal.rdp_template', 'external.rdp_template',
               'rdp_file')

**Comment by niugengtian** [comment]
full address:s:172.16.113.190:3389
username:s:niuhuanxi|chuanchuanchuan
use multimon:i:0
audiomode:i:0
disable wallpaper:i:0
disable full window drag:i:0
disable menu anims:i:0
disable themes:i:0
alternate shell:s:
shell working directory:s:
authentication level:i:2
connect to console:i:0
disable cursor setting:i:0
allow font smoothing:i:1
allow desktop composition:i:1
redirectprinters:i:0
prompt for credentials on client:i:0
autoreconnection enabled:i:1
bookmarktype:i:3
use redirection server name:i:0
screen mode id:i:2
session bpp:i:32
smart sizing:i:0

**Comment by niugengtian** [comment]
full address:s:183.234.126.34:8389
username:s:niuhuanxi|chuanchuanchuan
use multimon:i:0
audiomode:i:0
disable wallpaper:i:0
disable full window drag:i:0
disable menu anims:i:0
disable themes:i:0
alternate shell:s:
shell working directory:s:
authentication level:i:2
connect to console:i:0
disable cursor setting:i:0
allow font smoothing:i:1
allow desktop composition:i:1
redirectprinters:i:0
prompt for credentials on client:i:0
autoreconnection enabled:i:1
bookmarktype:i:3
use redirection server name:i:0
screen mode id:i:2
session bpp:i:32
smart sizing:i:0

**Comment by LeeEirc** [comment]
启用 rdp 文件的复用，config.txt 需要添加参数。

```
CONNECTION_TOKEN_REUSABLE=true
```

只有开启了配置，页面上也才会出现复用的高级选项。

**Comment by niugengtian** [comment]
谢谢 已经解决
