### ISSUE TITLE
安装文档步骤有误

### ISSUE THREAD

**Issue by wstart** [jumpserver/jumpserver#1318]
http://jumpserver.readthedocs.io/zh/docs/setup_by_centos7.html?highlight=log 

在 安装  下载 Jumpserver 与 Coco 中 
$ cd /opt/
$ git clone https://github.com/jumpserver/jumpserver.git && cd jumpserver && git checkout master && git pull
$ echo "source /opt/py3/bin/activate" > /opt/jumpserver/.env  # 进入 jumpserver 目录时将自动载入 python 虚拟环境
$ git clone https://github.com/jumpserver/coco.git && cd coco && git checkout master && git pull
$ echo "source /opt/py3/bin/activate" > /opt/coco/.env  # 进入 coco 目录时将自动载入 python 虚拟环境
##### 其他

安装完jumpserver后 需要退回到/opt目录下 
再执行 
git clone https://github.com/jumpserver/coco.git && cd coco && git checkout master && git pull

**Comment by wojiushixiaobai** [comment]
ok，修改下。

**Comment by guanbear** [comment]
@wojiushixiaobai 搭车报一个安装文档错误 http://docs.jumpserver.org/zh/docs/setup_by_ubuntu.html 安装依赖RPM包应该改成 DEB包

**Comment by wojiushixiaobai** [comment]
@guanbear 好的。
