### ISSUE TITLE
[Feature] 网域网关-匹配网关考虑自定义平台

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#13190]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
网域网关-匹配网关考虑自定义平台

## 功能描述
希望自定义的 Getway 平台能够被 “创建网域” 的网关下拉列表获取到

背景：
硬性规定：所有资产不允许 root 直连且禁用 su - 提权，只能通过 sudo su - 提权，因此需要自定义平台
当需要打通网域时，网关机需要自定义 Getway 平台，例如：Getway_sudo

目前：
创建网域时，选择网关只能匹配到 Getway 平台的资产

期望：
希望在 创建网域时，选择网关能匹配到 平台中包含“Getway” 平台名称的资产

**Comment by BaiJiangJie** [comment]
v3 版本暂时不考虑，v4 后可以考虑。

**Comment by BaiJiangJie** [comment]
v4+ 平台中考虑增加一种 Gateway 种类，支持自定义。
