### ISSUE TITLE
问题：无法获取真实的客户端 IP 地址

### ISSUE THREAD

**Issue by juncheng731** [jumpserver/jumpserver#13199]
## 注意
**请描述您的问题.** <br>
审计台无法获取真实的客户端登录账号的IP地址，显示的都是局域网IP：192.168.250.1，admin账号登录也是显示这个IP

## 当前使用的 JumpServer 版本 (必填)
[v3.10.9]

## 使用的版本类型 (必填)
社区版

## 版本安装方式 (必填)
离线安装 (下载离线包)

## 问题描述 (详细)
[在这里描述你遇到的问题]

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
审计台无法获取真实的客户端登录账号的IP地址，显示的都是局域网IP：192.168.250.1，
服务器系统是centos 8.2
config.txt配置文件设置的USE_IPV6=0，DOCKER_SUBNET=192.168.250.0/24

## 尝试过的解决方法
[尝试在Ubuntu 22.04系统和centos 8.2系统安装过JumpServer v3.10.9，都是无法获取真实的客户端 ip 地址 ]

## 预期结果
[希望给出解决办法，能获取真实的客户端IP地址]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
上层如果有 Nginx，和默认 Nginx 的配置保持一致。

其他情况，参考一下其他 issue。
https://github.com/jumpserver/jumpserver/issues/12839
https://github.com/jumpserver/jumpserver/issues/12073#issuecomment-1840277301

**Comment by juncheng731** [comment]
已解决，谢谢
