### ISSUE TITLE
[Bug] 批量删除操作404

### ISSUE THREAD

**Issue by zWeng33** [jumpserver/jumpserver#13202]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.10.7]

## 使用的版本类型 (必填)
- [ *] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ *] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[批量删除资源报404]

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]
![企业微信截图_20240513111537](https://github.com/jumpserver/jumpserver/assets/3939631/be835277-b0f8-4c3c-8343-bc15d8c13237)

**Comment by BaiJiangJie** [comment]
打开浏览器控制台，看一下 404 的请求是哪个 API？

**Comment by BaiJiangJie** [comment]
长时间未回复，关闭当前 issue。如果能稳定复现 reopen。

**Comment by zWeng33** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/3939631/5d47fa46-11a4-4d7c-91ce-f7d6d93128e0)

**Comment by BaiJiangJie** [comment]
最新版本没有复现，升级到最新版试试，如果还不行，远程看一下。

**Comment by vzrs** [comment]
我也出现了该问题，在4.0.2版本，但不是任何版本的问题或BUG。本人是进行了mysql到pgsql的数据库迁移，当删除账号的时候会同时生成一条insert语句将账号信息插入“accounts_historicalaccount”表中，由于pgsql序列的问题无法插入，因此也不会让你删除成功。我尝试了修改序列但都失败了，最终选择将“accounts_historicalaccount”表中记录全部删除。这个表只是历史记录，备份一下就删了吧，没啥问题。
