### ISSUE TITLE
无法再用户端查看应用机器

### ISSUE THREAD

**Issue by yuanpantest** [jumpserver/jumpserver#1320]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.0-2 ]

##### 问题复现步骤
1. [步骤1]
用户可以查看到资产信息，无法在终端查看到机器

2. [步骤2]
![image](https://user-images.githubusercontent.com/18694561/39984625-59703a9a-578e-11e8-9050-d336074a784f.png)

![image](https://user-images.githubusercontent.com/18694561/39984653-6f6ee7ce-578e-11e8-9944-2edbdb0e4237.png)

##### 其他
请查看

**Comment by wojiushixiaobai** [comment]
前台启动jumpserver，看报错信息。

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
