### ISSUE TITLE
[Question] 关于一台服务器多资产的连接问题

### ISSUE THREAD

**Issue by 0x5c0f** [jumpserver/jumpserver#13207]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
`3.10.9 `

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
具体的问题是这样的，我有**一台**服务器，而这个服务器对应了有3个资产，一个数据库资产、一个sftp资产(这个sftp分出来是因为哦sftp需要定制目录和指定用户)、一个服务器资产。 然后这个登陆，在网页端实际上是毫无问题的，问题是出现在终端登陆，我通过终端或者`xshell`这种`ssh`客户端登陆的时候，默认用户名应该指定 `<user>@<system_user>@<assest_ip>`，然后这个时候问题就来了，登陆后他会让你选择你要具体登陆的是哪个资产？关键是这个地方的判定，出现这么多的选择，似乎也只能是登陆服务器可以。其他的两个资产也登陆不了。其实这个问题我也还能接受，不能接受的是，这个判定会影响`vscode`的`Remote - SSH`远程连接，导致出现资产不唯一而登陆失败的情况。

![image](https://github.com/jumpserver/jumpserver/assets/26927906/71c8904d-827c-4969-9ab6-f0f46e995383)

## 背景信息
- 操作系统：[Fedora Linux 38 (Workstation Edition)]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[vscode: 1.89.1; OpenSSH_9.0p1, OpenSSL 3.0.9 30 May 2023]

## 具体问题
`vscode` 使用`Remote - SSH`登陆出现资产不唯一  

## 尝试过的解决方法
我尝试过指定远程连接目标为资产名，然后去连接，这个时候是直接失败，应该是不支持通过资产名字连接

## 预期结果
第三方客户端可以正确登陆到固定资产，而不用手动选择，这样应该也可以解决`vsocde`连接的问题。 如果是我配置的问题，我希望能为我提供一份此类问题的解决案例。

## 我们的期望

我在官方2群，可以直接联系我

**Comment by BaiJiangJie** [comment]
`<user>@<system_user>@<assest_ip>`

将 `asset_ip` 修改为 `asset_id`

**Comment by 0x5c0f** [comment]
🤏🤏🤏  厉害了  已解决问题
