### ISSUE TITLE
[Feature] 数据库阿里云hologres

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13208]
## 功能名称
- 客户在测试阿里数仓产品hologres的连接产品过程中，报错，
- 内核和协议应该也是postgressql数据库的，这类资产的纳管有有支持计划吗
-  用户反应为标准协议类型数据库，希望得到支持

![image](https://github.com/jumpserver/jumpserver/assets/136363116/8a136d06-c5bb-4478-b149-88e437d8c093)

**Comment by BaiJiangJie** [comment]
使用的什么版本？提 issue 的时候按照提示规范填写。

**Comment by BaiJiangJie** [comment]
使用默认的 pgsql 客户端命令行工具连接试试能不能成功，如果不成功，查看 core 的日志报什么错误？

**Comment by BaiJiangJie** [comment]
长时间未回复，关闭当前 issue。如果能稳定复现 reopen。
