### ISSUE TITLE
[Question] scp命令和ansible不能使用SSH向导提供的主机连接信息操作资产

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#13201]
## 当前使用的 JumpServer 版本 (必填)
v 3.10.7

## 使用的版本类型 (必填)
- [ ✅] 企业试用版

## 版本安装方式 (必填)
- [✅ ] 离线安装 (下载离线包)

## 问题描述 (详细)
scp 命令使用 JumpServer 的 SSH 向导 提供的 [主机连接信息] 向被纳管资产传输文件时不成功，报错信息如下：
[root@iZwz94i6ctasbp0eqtydleZ opt]# scp -P 2222 ./a.txt JMS-095b3734-93dd-43ad-b6b1-d644b3168430@14.103.36.21:/opt
The authenticity of host '[14.103.36.21]:2222 ([14.103.36.21]:2222)' can't be established.
RSA key fingerprint is SHA256:tVC/7IEsD64etP1WJCyhsKbsGo81ZZeXA6ql4PcrMxA.
RSA key fingerprint is MD5:be:50:e1:da:e5:32:90:eb:42:18:78:b9:69:5f:20:a1.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[14.103.36.21]:2222' (RSA) to the list of known hosts.
JMS-095b3734-93dd-43ad-b6b1-d6@14.103.36.21's password:
lost connection

## 背景信息
使用一台新部署的云服务器，操作系统为 CentOS 7.9，在该操作系统上使用scp命令向被 JumpServer 托管的资产上传输一个叫 a.txt 的文件，其中[JMS-095b3734-93dd-43ad-b6b1-d644b3168430]是 JumpServer SSH 连接向导提供的用户名，并且也正确输入了 SSH 连接向导提供的密码，直接提示 [lost connection] ，
命令如下：
scp -P 2222 ./a.txt JMS-095b3734-93dd-43ad-b6b1-d644b3168430@14.103.36.21:/opt

## 具体问题
使用一台新部署的云服务器，操作系统为 CentOS 7.9，在该操作系统上使用scp命令向被 JumpServer 托管的资产上传输一个叫 a.txt 的文件，其中[JMS-095b3734-93dd-43ad-b6b1-d644b3168430]是 JumpServer SSH 连接向导提供的用户名，并且也争取输入了 SSH 连接向导提供的秘密，直接提示 [lost connection]

## 尝试过的解决方法
1、绕过 JumpServer 直接 scp 可传输文件
2、ssh 命令可以使用 JumpServer SSH 向导的方式登录资产
3、scp 命令使用拼接登录的方式提示 [invalid user name]，拼接登录方式的的命令[scp -P 2222 ./a.txt admin#root#192.168.0.7@14.103.36.21:/opt]
4、在 ansible 中也无法使用 SSH 向导的连接方式，报错如下：
  [storage | FAILED! => {
      "msg": "failed to transfer file to /root/.ansible/tmp/ansible-local-157937Qny4R/tmpUoX7Yh /opt/.ansible/tmp/ansible-tmp-1715507610.41-15801-127048969015890/AnsiballZ_ping.py:\n\nlost connection\n"
  }]

## 预期结果
希望 scp 命令能使用 SSH 向导提供的连接信息进行文件传输

## 我们的期望
1、定位 scp 不能使用 SSH 向导提供的连接信息传输文件的原因。
2、定位 ansible 不能使用 SSH 向导提供的连接信息执行任务的原因。

## 附ansible的详细日志：
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2023, 11:36:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/inventory3.yml as it did not pass its verify_file() method
script declined parsing /root/inventory3.yml as it did not pass its verify_file() method
Parsed /root/inventory3.yml inventory source with yaml plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.
META: ran handlers
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: admin#root#192.168.0.7
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="admin#root#192.168.0.7"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/5477ed7a59 14.103.36.21 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /opt/.ansible/tmp `"&& mkdir "` echo /opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458 `" && echo ansible-tmp-1715517883.29-31069-171226357623458="` echo /opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458 `" ) && sleep 0'"'"''
<14.103.36.21> (0, 'ansible-tmp-1715517883.29-31069-171226357623458=/opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458\n', '')
<storage> Attempting python interpreter discovery
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: admin#root#192.168.0.7
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="admin#root#192.168.0.7"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/5477ed7a59 14.103.36.21 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<14.103.36.21> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.6\n/usr/bin/python2.7\n/usr/libexec/platform-python\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n', '')
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: admin#root#192.168.0.7
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="admin#root#192.168.0.7"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/5477ed7a59 14.103.36.21 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<14.103.36.21> (0, '{"osrelease_content": "NAME=\\"CentOS Linux\\"\\nVERSION=\\"7 (Core)\\"\\nID=\\"centos\\"\\nID_LIKE=\\"rhel fedora\\"\\nVERSION_ID=\\"7\\"\\nPRETTY_NAME=\\"CentOS Linux 7 (Core)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:centos:centos:7\\"\\nHOME_URL=\\"https://www.centos.org/\\"\\nBUG_REPORT_URL=\\"https://bugs.centos.org/\\"\\n\\nCENTOS_MANTISBT_PROJECT=\\"CentOS-7\\"\\nCENTOS_MANTISBT_PROJECT_VERSION=\\"7\\"\\nREDHAT_SUPPORT_PRODUCT=\\"centos\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"7\\"\\n\\n", "platform_dist_result": ["centos", "7.9.2009", "Core"]}\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<14.103.36.21> PUT /root/.ansible/tmp/ansible-local-30986DZZf80/tmpvAeZQ2 TO /opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458/AnsiballZ_ping.py
<14.103.36.21> SSH: EXEC sshpass -d10 scp -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="admin#root#192.168.0.7"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/5477ed7a59 /root/.ansible/tmp/ansible-local-30986DZZf80/tmpvAeZQ2 '[14.103.36.21]:/opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458/AnsiballZ_ping.py'
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: admin#root#192.168.0.7
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="admin#root#192.168.0.7"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/5477ed7a59 14.103.36.21 '/bin/sh -c '"'"'rm -f -r /opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458/ > /dev/null 2>&1 && sleep 0'"'"''
<14.103.36.21> (0, '', '')
storage | FAILED! => {
    "msg": "failed to transfer file to /root/.ansible/tmp/ansible-local-30986DZZf80/tmpvAeZQ2 /opt/.ansible/tmp/ansible-tmp-1715517883.29-31069-171226357623458/AnsiballZ_ping.py:\n\nlost connection\n"
}

**Comment by LeeEirc** [comment]
目前 scp 传输的文件不支持审计。如果需要使用 scp 传输文件，可开启 Koko 的以下配置

```
ENABLE_VSCODE_SUPPORT=true
ENABLE_LOCAL_PORT_FORWARD=true
```

如果传输出现问题，可以查看 Koko 的报错日志。

**Comment by xusongtao** [comment]
感谢回复，现在scp可以传输文件了。
但是ansible中还是无法使用SSH向导提供的主机连接信息操作资产，执行ansible任务时卡在这里，能帮忙评估一下吗？日志如下：
[root@iv-yd13r6aiv4k36d10mmi6 ~]# ansible all -m ping -i inventory4.yml -vvv
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2023, 11:36:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/inventory4.yml as it did not pass its verify_file() method
script declined parsing /root/inventory4.yml as it did not pass its verify_file() method
Parsed /root/inventory4.yml inventory source with yaml plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.
META: ran handlers
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 14.103.36.21 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /opt/.ansible/tmp `"&& mkdir "` echo /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841 `" && echo ansible-tmp-1715570085.79-11683-65370654693841="` echo /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841 `" ) && sleep 0'"'"''
<14.103.36.21> (0, 'ansible-tmp-1715570085.79-11683-65370654693841=/opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841\n', '')
<storage> Attempting python interpreter discovery
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 14.103.36.21 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<14.103.36.21> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.6\n/usr/bin/python2.7\n/usr/libexec/platform-python\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n', '')
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 14.103.36.21 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<14.103.36.21> (0, '{"osrelease_content": "NAME=\\"CentOS Linux\\"\\nVERSION=\\"7 (Core)\\"\\nID=\\"centos\\"\\nID_LIKE=\\"rhel fedora\\"\\nVERSION_ID=\\"7\\"\\nPRETTY_NAME=\\"CentOS Linux 7 (Core)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:centos:centos:7\\"\\nHOME_URL=\\"https://www.centos.org/\\"\\nBUG_REPORT_URL=\\"https://bugs.centos.org/\\"\\n\\nCENTOS_MANTISBT_PROJECT=\\"CentOS-7\\"\\nCENTOS_MANTISBT_PROJECT_VERSION=\\"7\\"\\nREDHAT_SUPPORT_PRODUCT=\\"centos\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"7\\"\\n\\n", "platform_dist_result": ["centos", "7.9.2009", "Core"]}\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<14.103.36.21> PUT /root/.ansible/tmp/ansible-local-11665xA7sIO/tmpaMXk_I TO /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841/AnsiballZ_ping.py
<14.103.36.21> SSH: EXEC sshpass -d10 scp -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 /root/.ansible/tmp/ansible-local-11665xA7sIO/tmpaMXk_I '[14.103.36.21]:/opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841/AnsiballZ_ping.py'
<14.103.36.21> (0, '', '')
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 14.103.36.21 '/bin/sh -c '"'"'chmod u+x /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841/ /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841/AnsiballZ_ping.py && sleep 0'"'"''
<14.103.36.21> (0, '', '')
<14.103.36.21> ESTABLISH SSH CONNECTION FOR USER: JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3
<14.103.36.21> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=8822 -o 'User="JMS-f4bc7488-1076-4b30-b4df-5e1ba23901f3"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/f3beb81124 -tt 14.103.36.21 '/bin/sh -c '"'"'/usr/bin/python /opt/.ansible/tmp/ansible-tmp-1715570085.79-11683-65370654693841/AnsiballZ_ping.py && sleep 0'"'"''
^[:q^H^H^C [ERROR]: User interrupted execution

**Comment by LeeEirc** [comment]
ansible 任务可能会多次建立 SSH 连接，而 SSH 向导提供的 [主机连接信息]  Token 默认仅一次连接有效，你可能需要开启 connection_token 的复用。

```
CONNECTION_TOKEN_REUSABLE=true
```

**Comment by xusongtao** [comment]
感谢回复。
ansible 任务会多次建立 SSH 连接。
按照要求添加并且开启的connection_token 连接复用，ansible执行时仍同样出现卡住的现象。
截图如下：
![image](https://github.com/jumpserver/jumpserver/assets/40846859/42ce2755-283e-44ce-b967-1c809e5e9df6)

![image](https://github.com/jumpserver/jumpserver/assets/40846859/7bba6b55-fc7f-43f3-9e78-bfa2703b0ba1)
![image](https://github.com/jumpserver/jumpserver/assets/40846859/dbd0b97a-0013-4086-a7d8-b35855a2e4ad)

![image](https://github.com/jumpserver/jumpserver/assets/40846859/4615262a-f509-4c6a-820d-8654ebad0552)

堡垒机的审计台可以看到如下审计记录
![image](https://github.com/jumpserver/jumpserver/assets/40846859/826a5531-fc28-4b8c-a1d6-9da604b3cce5)

**Comment by LeeEirc** [comment]
无法看出你这个卡住原因，看看执行其他 ansible 命令是否会卡住。也可以查看下 Koko 有没有报错日志。

**Comment by xusongtao** [comment]
感谢回复，执行其他ansible同样卡住

![image](https://github.com/jumpserver/jumpserver/assets/40846859/0f5e5f20-e244-4608-acbc-a3e7f961414a)

[root@iv-yd13r6aiv4k36d10mmi6 ~]# ansible test3 -m command -a 'date' -vvv
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 20 2023, 11:36:40) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.
META: ran handlers
<120.77.248.78> ESTABLISH SSH CONNECTION FOR USER: JMS-d29249f3-7816-425e-8293-863dd6a0dd2d
<120.77.248.78> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 120.77.248.78 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /opt/.ansible/tmp `"&& mkdir "` echo /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753 `" && echo ansible-tmp-1715595266.86-22010-132583601467753="` echo /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753 `" ) && sleep 0'"'"''
<120.77.248.78> (0, 'ansible-tmp-1715595266.86-22010-132583601467753=/opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753\n', '')
<120.77.248.78> Attempting python interpreter discovery
<120.77.248.78> ESTABLISH SSH CONNECTION FOR USER: JMS-d29249f3-7816-425e-8293-863dd6a0dd2d
<120.77.248.78> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 120.77.248.78 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<120.77.248.78> (0, 'PLATFORM\nLinux\nFOUND\n/usr/bin/python\n/usr/bin/python3.6\n/usr/bin/python2.7\n/usr/libexec/platform-python\n/usr/bin/python3\n/usr/bin/python\nENDFOUND\n', '')
<120.77.248.78> ESTABLISH SSH CONNECTION FOR USER: JMS-d29249f3-7816-425e-8293-863dd6a0dd2d
<120.77.248.78> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 120.77.248.78 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<120.77.248.78> (0, '{"osrelease_content": "NAME=\\"CentOS Linux\\"\\nVERSION=\\"7 (Core)\\"\\nID=\\"centos\\"\\nID_LIKE=\\"rhel fedora\\"\\nVERSION_ID=\\"7\\"\\nPRETTY_NAME=\\"CentOS Linux 7 (Core)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:centos:centos:7\\"\\nHOME_URL=\\"https://www.centos.org/\\"\\nBUG_REPORT_URL=\\"https://bugs.centos.org/\\"\\n\\nCENTOS_MANTISBT_PROJECT=\\"CentOS-7\\"\\nCENTOS_MANTISBT_PROJECT_VERSION=\\"7\\"\\nREDHAT_SUPPORT_PRODUCT=\\"centos\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"7\\"\\n\\n", "platform_dist_result": ["centos", "7.9.2009", "Core"]}\n', '')
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<120.77.248.78> PUT /root/.ansible/tmp/ansible-local-22002T7rBf0/tmpaZiRe2 TO /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753/AnsiballZ_command.py
<120.77.248.78> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 '[120.77.248.78]'
[WARNING]: sftp transfer mechanism failed on [120.77.248.78]. Use ANSIBLE_DEBUG=1 to see detailed information
<120.77.248.78> SSH: EXEC sshpass -d10 scp -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 /root/.ansible/tmp/ansible-local-22002T7rBf0/tmpaZiRe2 '[120.77.248.78]:/opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753/AnsiballZ_command.py'
<120.77.248.78> (0, '', '')
<120.77.248.78> ESTABLISH SSH CONNECTION FOR USER: JMS-d29249f3-7816-425e-8293-863dd6a0dd2d
<120.77.248.78> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 120.77.248.78 '/bin/sh -c '"'"'chmod u+x /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753/ /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753/AnsiballZ_command.py && sleep 0'"'"''
<120.77.248.78> (0, '', '')
<120.77.248.78> ESTABLISH SSH CONNECTION FOR USER: JMS-d29249f3-7816-425e-8293-863dd6a0dd2d
<120.77.248.78> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=2222 -o 'User="JMS-d29249f3-7816-425e-8293-863dd6a0dd2d"' -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/8ecac900c1 -tt 120.77.248.78 '/bin/sh -c '"'"'/usr/bin/python /opt/.ansible/tmp/ansible-tmp-1715595266.86-22010-132583601467753/AnsiballZ_command.py && sleep 0'"'"''
^C [ERROR]: User interrupted execution

Koko的log如下：
2024-05-13 18:13:48 [ERRO] SSH conn[11085a10423e29420e18375f156048658990632bc742a7b4beeb56ff5514cc1e] auth method none failed: ssh: no auth passed yet
2024-05-13 18:13:48 [ERRO] SSH conn[11085a10423e29420e18375f156048658990632bc742a7b4beeb56ff5514cc1e] auth method password success
2024-05-13 18:14:19 [ERRO] Session[31d4eb85-78fd-432a-b4d6-741f0d639d4f] user read err: io: read/write on closed pipe
2024-05-13 18:14:19 [ERRO] Session[31d4eb85-78fd-432a-b4d6-741f0d639d4f] srv read err: EOF
2024-05-13 18:14:36 [ERRO] Session[ef3bcd75-9029-4be4-aa86-f87e28b56711] user read err: io: read/write on closed pipe
2024-05-13 18:14:36 [ERRO] Session[ef3bcd75-9029-4be4-aa86-f87e28b56711] srv read err: EOF

**Comment by xusongtao** [comment]
已由工程师对接
