### ISSUE TITLE
[Feature] AWS大模型Claude 3 sonnet

### ISSUE THREAD

**Issue by SC-zj** [jumpserver/jumpserver#13213]
1.  能不能支持下AWS的大模型Claude 3。chatGPT国内访问不了，AWS的没这种限制方便很多。
<img width="1439" alt="image" src="https://github.com/jumpserver/jumpserver/assets/70679694/73bd6ff7-8710-4e81-8701-f0ba30ac7cd4">

**Comment by BaiJiangJie** [comment]
嗯，可以考虑在 v4+ 版本中支持。

**Comment by BaiJiangJie** [comment]
API 和 GPT 的标准不一样，暂时不考虑。
