### ISSUE TITLE
[Bug] 会话列表命令数量为 0

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#13214]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.7.10]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
[通过Python脚本连接堡垒机，并登录某台设备执行命令，在会话记录里可以回放显示执行命令过程，但是会话记录里面，命令数量显示为0，且在命令记录里查不到记录]

## 复现步骤
<img width="1334" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/47bdc6bd-0102-4b5a-92d5-d651f3e4e4fe">
## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

**Comment by BaiJiangJie** [comment]
应该是上传命令失败了，看一下 koko 日志有没有报错信息。

**Comment by BaiJiangJie** [comment]
命令数量为0，会话详情中的命令列表有记录吗？

**Comment by pika-FENG** [comment]
> 命令数量为0，会话详情中的命令列表有记录吗？

没有，查不到任何记录

**Comment by pika-FENG** [comment]
> 应该是上传命令失败了，看一下 koko 日志有没有报错信息。

<img width="1316" alt="image" src="https://github.com/jumpserver/jumpserver/assets/91412927/412133df-19cc-4bc0-bfeb-b5f4bbbe87fd">
每天早上六点执行的，koko日志如图

**Comment by BaiJiangJie** [comment]
搜索一下日志包含 command 关键字的日志。

**Comment by pika-FENG** [comment]
> 搜索一下日志包含 command 或者 upload 关键字的日志。

对应的时间段内没有这俩关键字的日志

**Comment by BaiJiangJie** [comment]
重新连接一个会话，输入10+ 命令，tail 日志。

**Comment by pika-FENG** [comment]
> 重新连接一个会话，输入10+ 命令，tail 日志。

![image](https://github.com/jumpserver/jumpserver/assets/91412927/df62dfe0-0060-4183-bc0b-2e7d6a6cd0a2)
是不是日志级别不够呢，还是没显示

**Comment by pika-FENG** [comment]
> 有可能，开下 DEBUG。

![image](https://github.com/jumpserver/jumpserver/assets/91412927/7bd57bda-e9a2-4fb1-a010-056ad91fcf37)

**Comment by BaiJiangJie** [comment]
还是没有命令上传的报错日志？

**Comment by BaiJiangJie** [comment]
`通过Python脚本连接堡垒机` 是什么意思？

**Comment by pika-FENG** [comment]
> `通过Python脚本连接堡垒机` 是什么意思？

就是通过paramiko 连接堡垒机2222，然后登录对应的资产，执行相关命令，因为是开源版，我们自己写的脚本去定时执行一些备份工作

**Comment by BaiJiangJie** [comment]
有脚本吗？我们自己测试一下。

**Comment by pika-FENG** [comment]
> 有脚本吗？我们自己测试一下。

发你邮箱了

**Comment by BaiJiangJie** [comment]
好的，收到了，我们来验证一下。

**Comment by LeeEirc** [comment]
@pika-FENG  已经针对脚本情况做了特殊处理，可以构建 dev 版本的 koko 验证下。

- https://github.com/jumpserver/koko/pull/1331
