### ISSUE TITLE
[Question] 命令过滤规则接受动作如果是只允许命令组的命令，拒绝其他命令，会不会好点？

### ISSUE THREAD

**Issue by icefire-ken** [jumpserver/jumpserver#13224]
## 当前使用的 JumpServer 版本 (必填)
v3.10.9

## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)

## 问题描述 (详细)
我是用jumpserver来SSH管理网络设备，目前测试只关联了交换机设备。
在命令过滤功能上碰到一个问题，就是命令过滤规则动作选择接受，我的理解它应该是只能接受关联的命令组内的命令，拒绝其他命令。
结果不是，命令组内的命令和命令组外的命令都能接受输入。不是很理解这个设计逻辑，能说明下吗？
当然我还是希望能改成**只能接受关联的命令组内的命令，拒绝其他命令**。

## 背景信息
- 操作系统：Windows11
- 浏览器/应用版本：Chrome

## 尝试过的解决方法
问过群里的小伙伴，给出了一个解决方案。
利用命令过滤规则的优先级，
先创建一个匹配所有命令的命令组，然后创建一个规则，关联此命令组，优先级100；
然后创建一个匹配允许输入的命令组，如show相关命令，再创建另一个规则，关联此命令组，优先级50；
两个规则都关联给同一个用户，可以实现这个需求。

## 预期结果
**只能接受关联的命令组内的命令，拒绝其他命令**

**Comment by BaiJiangJie** [comment]
是的，群里的小伙伴给出的建议是可采用的。

默认情况下所有命令都可以执行。
如果只允许执行 3 条命令，那么需要创建两条规则：
1. 优先级低，禁止所有命令执行。
2. 优先级高，允许指定的命令。

**Comment by icefire-ken** [comment]
您好！

明白您的意思。

但是我还是想建议修改一下这个逻辑，希望能采纳。

或者您可以说明一下现在这个设计逻辑是为了应对什么样的使用场景的。
















在 2024-05-16 10:42:46，"Bryan" ***@***.***> 写道：

是的，群里的小伙伴给出的建议是可采用的。

默认情况下所有命令都可以执行。
如果只允许执行 3 条命令，那么需要创建两条规则：

优先级低，禁止所有命令执行。
优先级高，允许指定的命令。
