### ISSUE TITLE
[Question] LDAP 配置

### ISSUE THREAD

**Issue by yuhongwei380** [jumpserver/jumpserver#13225]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[3.10.9]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
我搭建了一个ldap服务，但不是OPENLDAP；在群晖中的加入ldap我只需要配置以下内容；在jumpserver中的ldap中我填入相同的信息，进行测试的时候就一直报错。
举例：
baseDN 管理员帐号：test  密码 test
域名 test.com
我该如何正确配置？
![image](https://github.com/jumpserver/jumpserver/assets/44333391/5b4f72f0-aa04-4dfd-b56e-fed26d2b85d5)

## 背景信息
- 操作系统：centos7
- 浏览器/应用版本：chrome 
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]

## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by yuhongwei380** [comment]
我的这个ldap包装器不会产生ou；我该如何进行配置？ 以及我配置了BIND DN 是报错的；我BIND的账户和密码是test/test   dc=test.com ；

**Comment by BaiJiangJie** [comment]
提供一下测试可连接信息后的报错截图。

**Comment by yuhongwei380** [comment]
> 提供一下测试可连接性后的报错截图，以及配置页面的截图。

![image](https://github.com/jumpserver/jumpserver/assets/44333391/7377a14b-de13-496f-8e02-e1d08e248c89)

**Comment by BaiJiangJie** [comment]
那就是用户名密码不正确。

**Comment by yuhongwei380** [comment]
> 那就是用户名密码不正确。

但是我填入的信息都是正确的；同样的BIND用户名和密码，我在群晖上配置完全都加入ldap了；
![image](https://github.com/jumpserver/jumpserver/assets/44333391/1b546a09-e958-4898-951f-64046b0cc825)

**Comment by BaiJiangJie** [comment]
那你将 ldap:// 前缀去掉试一下呢？

**Comment by yuhongwei380** [comment]
> 那你将 ldap:// 前缀去掉试一下呢？

![image](https://github.com/jumpserver/jumpserver/assets/44333391/2a412350-7732-412d-9de1-af377e24adda)
去掉以后报错的；

**Comment by BaiJiangJie** [comment]
<img width="1188" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/84f18420-16f0-432b-b4ea-41c59d7c712f">

DN 配置的也不一样啊

**Comment by yuhongwei380** [comment]
群晖中DN就只有这个信息，DN的用户名和密码是单独项填入的； 可以看这个case 中第一张图。

**Comment by BaiJiangJie** [comment]
使用的什么 LDAP 服务？

**Comment by yuhongwei380** [comment]
> 使用的什么 LDAP 服务？

这个项目https://github.com/ahaenggli/AzureAD-LDAP-wrapper

**Comment by BaiJiangJie** [comment]
不知道是不是标准协议，我们的用户一般对接的是 OpenSSH 或者 Windows AD。

**Comment by BaiJiangJie** [comment]
JumpServer 对于 LDAP 的连接、认证。使用的是 ldap3 的库。
你可以在本地使用 python 库来测试一下。
https://github.com/cannatag/ldap3

**Comment by yuhongwei380** [comment]
> 不知道是不是标准协议，我们的用户一般对接的是 OpenSSH 或者 Windows AD。

我在对方那边也提了个case；[site](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/issues/82)
害，这不是windows server版本的AD是 要付费的嘛，而且我们主要是云上版本的AzureAD；但是对接OIDC这种你们都是企业版才有这个功能。

**Comment by yuhongwei380** [comment]
> JumpServer 对于 LDAP 的连接、认证。使用的是 ldap3 的库。 你可以在本地使用 python 库来测试一下。 https://github.com/cannatag/ldap3

嗯嗯好的

**Comment by wojiushixiaobai** [comment]
`cn=vexxx`
这里的 cn 属性你确定是正确的

**Comment by yuhongwei380** [comment]
> LDAP-wrapper

我用的一个ldap包装器（对接了azuread），群晖那边做绑定的话，BIND DN管理员账密填写很简单，所以我不知道在jumpserver这边我怎么指定我的BIND DN的账号密码；BIND DN本身不带有dc的信息；

**Comment by yuhongwei380** [comment]
> `cn=vexxx` 这里的 cn 属性你确定是正确的
我用的一个ldap包装器（对接了azuread），群晖那边做绑定的话，BIND DN管理员账密填写很简单，所以我不知道在jumpserver这边我怎么指定我的BIND DN的账号密码；BIND DN本身不带有dc的信息；比如我的BIND DN账号是vetest 密码也是vetest。我该如何在jumpserver中正确填写呢。我尝试去掉dc的描述，也是有问题的。

**Comment by yuhongwei380** [comment]
> `cn=vexxx` 这里的 cn 属性你确定是正确的

我用的一个ldap包装器（对接了azuread），群晖那边做绑定的话，BIND DN管理员账密填写很简单，所以我不知道在jumpserver这边我怎么指定我的BIND DN的账号密码；BIND DN本身不带有dc的信息；比如我的BIND DN账号是vetest 密码也是vetest。我该如何在jumpserver中正确填写呢。我尝试去掉dc的描述，也是有问题的。

**Comment by BaiJiangJie** [comment]
你先使用 ldap3 的包，使用程序去连接测试一下，如果能成功再将代码提供上来，我们和JumpServer的代码进行对比，看看是否有需要优化的地方。

**Comment by wojiushixiaobai** [comment]
你可以在你的 `DC` 服务器里面可以查到这些用户属性。

以 `Windows AD` 为例，`administrator` 账号的完整 `DN` 为 
`CN=Administrator,CN=Users,DC=DOMAIN,DC=LOCAL`
`sAMAccountName=Administrator,CN=Users,DC=DOMAIN,DC=LOCAL`
或者其他具有唯一性的其他属性。不一定就是 `CN`

**Comment by BaiJiangJie** [comment]
按照上面提供的方式先试一下，如果还有问题 reopen issue。

**Comment by yuhongwei380** [comment]
> 按照上面提供的方式先试一下，如果还有问题 reopen issue。

ldapsearch -x -H ldap://192.168.8.199:389 -D 'uid=admin' -w "Test123." -b "dc=test,dc=com"
用这个可以获取到ldap包装器的相关内容；
![image](https://github.com/jumpserver/jumpserver/assets/44333391/b667b45f-6989-4538-8e2a-25d94bcd45b1)
另外，获取到的内容里没有包含关于OU的部分；我也尝试利用uid的方式在jumpserver中进行配置，
![image](https://github.com/jumpserver/jumpserver/assets/44333391/13f2ef7f-6d6b-4ad1-9958-6cb9d15baac7)
报错还是跟之前一样的。

**Comment by yuhongwei380** [comment]
> 你先使用 ldap3 的包，使用程序去连接测试一下，如果能成功再将代码提供上来，我们和JumpServer的代码进行对比，看看是否有需要优化的地方。

```
from ldap3 import Server, Connection, ALL, NTLM, SUBTREE, ALL_ATTRIBUTES

# LDAP服务器配置
ldap_server = '192.168.8.199'
ldap_port = 389
ldap_base_dn = 'dc=test,dc=com'
ldap_bind_user = 'uid=admin'
ldap_bind_password = 'Vesoft123.'
ldap_domain = 'test.com'

# 测试用户
test_user = 'phoenix.yu@test.com'
test_password = 'Ytest.'

# 创建服务器对象
server = Server(ldap_server, port=ldap_port, get_info=ALL)

# 创建连接对象并进行绑定
conn = Connection(server, user=ldap_bind_user, password=ldap_bind_password, auto_bind=True)

# 检查绑定状态
if conn.bind():
    print("LDAP 绑定成功！")
else:
    print("LDAP 绑定失败！")

# 搜索测试用户
conn.search(search_base=ldap_base_dn,
            search_filter=f'(mail={test_user})',
            search_scope=SUBTREE,
            attributes=ALL_ATTRIBUTES)

# 打印搜索结果
if conn.entries:
    print("搜索成功，找到了以下条目：")
    for entry in conn.entries:
        print(entry)
else:
    print("搜索失败，没有找到相关条目。")

# 断开连接
conn.unbind()

```
这个代码我可以成功的连接到我的ldap包装器

**Comment by yuhongwei380** [comment]
@BaiJiangJie  你好，我没看到reopen的按钮

**Comment by wojiushixiaobai** [comment]
保存 ldap 后重新测试，如果你的版本不是最新版本注意先升级到最新版本再测试

**Comment by yuhongwei380** [comment]
> 保存 ldap 后重新测试，如果你的版本不是最新版本注意先升级到最新版本再测试
你好，我就是在一个新的环境里重新部署了新的jumpserver然后再测试的。
![image](https://github.com/jumpserver/jumpserver/assets/44333391/486f03f2-912d-4c73-9c7b-da8f98e9d993)
报错仍然是指向绑定DN有错误
![image](https://github.com/jumpserver/jumpserver/assets/44333391/494cfb3a-ae65-406b-a353-8176247e0399)

**Comment by wojiushixiaobai** [comment]
换个认证账号试试看，放到 `OU` 下面

**Comment by yuhongwei380** [comment]
> 换个认证账号试试看，测试的认证账号放到 `OU` 下面

刚刚我测试了下，绑定DN那边只设置uid=admin 就可以了，然后就匹配到了用户；也用我自己的个人账户测试登录jumpserver了；目前这一步应该是没啥问题了~还是感谢之前的指导意见
