### ISSUE TITLE
System 账号不支持Domain 账号

### ISSUE THREAD

**Issue by wang415** [jumpserver/jumpserver#1322]
[System 账号不支持Domain 账号]

##### 使用版本
[Jumpserver版本 1.3.0-2]

##### 问题复现步骤
1. 新建管理账号
创建账号-
账号名称-XX
账号名字- admin@domin.com or domin.com\admin

报错 不支持特殊字符

**Comment by wojiushixiaobai** [comment]
问题已经解决，更新下
