### ISSUE TITLE
docker部署jumpserver/jms_all:latest设置https失效

### ISSUE THREAD

**Issue by pumpkin-nbc** [jumpserver/jumpserver#13235]
## 当前使用的 JumpServer 版本 (必填)
jumpserver/jms_all:latest v3.10.9

## 使用的版本类型 (必填)
- [*] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [*] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
将容器中/etc/nginx/nginx.conf配置映射出后 配置了ssl配置
登陆时报错
![image](https://github.com/jumpserver/jumpserver/assets/58675642/4df40d96-b748-4e53-abb7-b0b95cdeda1e)

容器中不存在/opt/jumpserver/config/config.txt

## 期望行为
如何通过修改nginx配置 或者 在容器启动命令中增加 -e 从而支持https

**Comment by wojiushixiaobai** [comment]
`jms_all` 不支持容器里面配置 `ssl`，你可以修改 `/etc/nginx/nginx.conf`，或者单独新增反向代理

**Comment by pumpkin-nbc** [comment]
> `jms_all` 默认不支持通过参数配置 `ssl`，你可以修改 `/etc/nginx/nginx.conf`，或者单独新增反向代理

nginx.conf已经修改过了 但是登陆的时候报错 显示配置文件异常

**Comment by pumpkin-nbc** [comment]
> <img alt="image" width="998" src="https://private-user-images.githubusercontent.com/32935519/331155216-b181b2f5-b435-4f25-ad51-8108021d4b34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjI2MjMsIm5iZiI6MTcxNTg2MjMyMywicGF0aCI6Ii8zMjkzNTUxOS8zMzExNTUyMTYtYjE4MWIyZjUtYjQzNS00ZjI1LWFkNTEtODEwODAyMWQ0YjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEyMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YmYxZmNiYzkyMjkwYTViOTc4NWVlZGU5MmRmNWU1M2ZlZjk3N2RkMTlhN2JiYmIyZTE5ZjZmZDg3ZmY4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1mhiFPqted-tdglY8372bI8gd7EPeQZz3b58gh8yHh4"> https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/
> -e 增加 DOMAINS 参数。

配置中添加了 -e DOMAINS=xxx.xxxx.xxx之后 启动之后 还是报配置异常

**Comment by wojiushixiaobai** [comment]
完整启动日志发出来看看，确定启动的日志里面有你配置的域名

**Comment by pumpkin-nbc** [comment]
> 完整启动日志发出来看看，确定启动的日志里面有你配置的域名
命令是这个
docker run -d --name jumpserver --restart=always \
          -p 8820:443 \
          -e SECRET_KEY=xxxx \
          -e BOOTSTRAP_TOKEN=xxxx \
          -e DOMAINS=域名 \
          -e LOG_LEVEL=ERROR \
          -e DB_HOST=mariadb -e DB_PORT=3306 -e DB_USER=xxx -e DB_PASSWORD=xxx -e DB_NAME=jumpserver \
          -e REDIS_HOST=redis -e REDIS_PORT=6379 -e REDIS_PASSWORD=xxx \
          -v /jumpserver/data/core/data:/opt/jumpserver/data \
          -v /jumpserver/data/koko/data:/opt/koko/data \
          -v /jumpserver/data/lion/data:/opt/lion/data \
          -v /jumpserver/data/kael/data:/opt/kael/data \
          -v /jumpserver/data/chen/data:/opt/chen/data \
          -v /jumpserver/data/web/log:/var/log/nginx \
          -v /jumpserver/data/certs:/opt/certs \
          -v /jumpserver/data/nginx/nginx.conf:/etc/nginx/nginx.conf \
          jumpserver/jms_all:latest

**Comment by BaiJiangJie** [comment]
如果配置了不同的端口，DOMAINS 中要包含端口信息。

**Comment by pumpkin-nbc** [comment]
> 如果 -p 配置了不同的端口，DOMAINS 中要包含端口信息。

感谢 可以了 -e DOMAINS=xxx.xxxx.xxx:port 之后可以登陆
