### ISSUE TITLE
[Bug] 全局组织显示bug

### ISSUE THREAD

**Issue by Evo555** [jumpserver/jumpserver#13238]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.9

## 使用的版本类型 (必填)
- [√] 社区版
- [] 企业版
- [] 企业试用版

## 版本安装方式 (必填)
- [] 在线安装 (一键命令)
- [√] 离线安装 (下载离线包)
- [] All-in-One
- [] 1Panel 安装
- [] Kubernetes 安装
- [] 源码安装

## Bug 描述 (详细)
社区版无全局组织功能，如果先点击用户登录，右键去打开新标签页的资产列表，那么资产列表中会显示全局组织，企业版同理
<img width="1280" alt="屏幕截图 2024-05-16 174027" src="https://github.com/jumpserver/jumpserver/assets/166269017/ec0bcb08-b0db-4ceb-ac10-3d2f567b4fd0">
<img width="1279" alt="屏幕截图 2024-05-16 174352" src="https://github.com/jumpserver/jumpserver/assets/166269017/710aeca6-4fd8-4ce0-925b-aaf10a7e62d5">

## 复现步骤
1. 点击到用户登录下
2. 右键资产列表，点击新标签页打开

## 期望行为
显示默认组织

## 实际行为
显示全局组织

## 系统环境
- 操作系统：windows11
- 浏览器/应用版本：chrome:latest

**Comment by BaiJiangJie** [comment]
v3.10.10-lts 修复了。

刚发布，升级一下试试。

**Comment by Ewall555** [comment]
> v3.10.10-lts 修复了。
> 
> 刚发布，升级一下试试。

刚刚在3.10.10复现了，这个问题会造成社区版用户在全局组织下导致无法创建资产按钮被禁用
