### ISSUE TITLE
[Question] 远程应用浏览器下载路径设置问题

### ISSUE THREAD

**Issue by abc5588** [jumpserver/jumpserver#13239]
引用之前提交过的问题，一下没有解决。请高手帮助解决一下。
之前提交的问题地址：[https://github.com/jumpserver/jumpserver/issues/13137](url)

重复说一下：

jumpserver 3.10.9 社区版, 在线一键安装的. 并配置好了远程应用.

使用远程应用打开google浏览器，然后随便打开一个网页，这时google浏览器右上角有三个点，找到google浏览器设置按钮，设置下载下载路径为【\\tsclient\JumpServer\Download】
从远程应用浏览器中打开下载文件：https://shujufw.lcev.cn/1.doc 进行下载

当设置的下载路径不要download时，下载1.doc文件是完全正常的。能正常下载。

当下载路径加了download 时，它的下载地址就变成了下面这样
[https://我的jumpserver域名.com/lion/api/tunnels/%241664710f-839a-4d9e-bcf2-131b910784d5/streams/0/a7f7ba23-c90d-4262-a5cc-81504325f034.tmp](https://xn--jumpserver-tc6qx08aem7a923d.com/lion/api/tunnels/%241664710f-839a-4d9e-bcf2-131b910784d5/streams/0/a7f7ba23-c90d-4262-a5cc-81504325f034.tmp)

发现：如果下载路径不加download时，文件能正常下载, 是下载到了服务器，不是我要的。

下载路径加了download时，文件是直接下载到了我本地电脑的，完全符合我要的。但是下载时，文件变了。求解决方案。

问题录像视频：https://wx.mail.qq.com/ftn/download?func=3&key=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&code=6a6d9445&k=c99e5c649659c43bfbed18643b343435a315c86539343435134e4e100b56020354521b565d0c0c185203035214060000004c0f515b035704005303540f572d356104750c58406b07065302540d070404045503560d1a59450275b9c585c2b87b1e07558c51863e5f5e06e12bfa28&fweb=1&cl=1

求解决：怎么让下载路径为【\\tsclient\JumpServer\Download】时，让下载的文件是正常文件，而不是tmp缓存。

**Comment by BaiJiangJie** [comment]
是不支持的。

**Comment by BaiJiangJie** [comment]
只能使用默认路径。

**Comment by abc5588** [comment]
好吧。 付费也没办法解决吗
