### ISSUE TITLE
jms_celery unhealthy状态

### ISSUE THREAD

**Issue by XH996** [jumpserver/jumpserver#13230]
## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
v3.10.9
## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## 问题描述 (详细)
[在这里描述你遇到的问题]
![image](https://github.com/jumpserver/jumpserver/assets/127380435/1c4ddf28-af60-4881-925b-1f6cfd6a4a47)
![image](https://github.com/jumpserver/jumpserver/assets/127380435/df39b6c9-85cd-4132-b539-f6b4ce4a0ed7)
![image](https://github.com/jumpserver/jumpserver/assets/127380435/f429351c-583c-4afb-8001-af7d3217d4b1)

**Comment by BaiJiangJie** [comment]
Not permitted!
