### ISSUE TITLE
[Feature]  SSH协议 客户端方式支持 IDEA Remote development 

### ISSUE THREAD

**Issue by gcl1fit2cloud** [jumpserver/jumpserver#13231]
## 功能名称
当前支持使用 VSCode 软件进行 SSH 连接， 但是用 IDEA 的 Remote Development 不行， 希望能够支持

## 功能描述
功能类似 VSCode, IntelliJ IDEA 软件用的比较普遍，希望能够支持，具体方式可参考以下 blog ：https://blog.csdn.net/2301_78834737/article/details/132004664

**Comment by BaiJiangJie** [comment]
v4+ 版本后再考虑。

**Comment by BaiJiangJie** [comment]
v4.0 已支持。
