### ISSUE TITLE
堡垒机ssh方式登陆的端口由2222修改为其他端口之后，通过客户端的方式登陆资产失败。

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13246]
## 当前使用的 JumpServer 版本 (必填)
3.10.9

## 使用的版本类型 (必填)
- [ ] 社区版
- [ √] 企业版
- [ √] 企业试用版

## 版本安装方式 (必填)
- [√] 离线安装 (下载离线包)

## Bug 描述 (详细)
ssh方式登陆堡垒机的端口由2222修改为其他端口之后，通过客户端的方式登陆资产失败。
客户端报错为ssh: connect to host 192.168,1.122 port 2222: Connection timed out
## 复现步骤
1. 修改config.txt文件堡垒机对外提供服务的ssh端口。我修改了两次进行测试，分别是64222和6222。
2. 使用jmsctl start命令启动堡垒机。
3. 使用客户端方式登陆堡垒机纳管的资产。我测试的客户端工具由putty和mobaxterm。
4. mobaxterm会提示ssh: connect to host 192.168.0.119 port 2222: Connection timed out。putty提示超时。
5. 使用web可以正常登陆资产。

## 期望行为
修改对外提供服务的端口之后也能正常使用客户端登陆资产。

## 系统环境
- 操作系统：[客户机为win10和2019，堡垒机服务器为Centos7.6，资产为Ubuntu和Centos7]
- 浏览器/应用版本：[谷歌浏览器，EDGE]

## 附加信息（可选）
1. 修改配置文件的截图：
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/57e9c841-55f5-457f-b3dd-22a70ce8579a)
2. 客户端工具的报错截图
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/d5dc23c4-b4b9-4858-bbdd-61a3d1e879df)
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/beecb972-e81c-4f7e-b7af-0cb9251c0a40)

**Comment by BaiJiangJie** [comment]
docker ps 看一下 koko 容器的端口映射。

**Comment by BaiJiangJie** [comment]
你先不用修改端口，使用 -p2222 连接试试，这是默认的端口。

**Comment by helomng** [comment]
> 你先不用修改端口，使用 -p2222 连接试试，这是默认的端口。

确实是一个BUG，在自定义修改了默认的SSH配置后，调用本地客户端时，调用行为仍然指向了旧的SSH端口即2222，而没有指向新的端口，所以会超时，但是WEB就是正常的。可以参考客户端向导页面的配置，


如果手动修改对应的参数为新端口，则是可以正常登录， 说明容器端口映射是没问题的。这个BUG在3.10都是没有修复的，4.0版本没有测试。
![Snipaste_2024-10-28_13-46-27](https://github.com/user-attachments/assets/0cab8d6f-4c0b-404d-abe2-9d8e41e5a6ab)

**Comment by LiaoSirui** [comment]
reopen

**Comment by LiaoSirui** [comment]
配置一下服务端点试一下，我看了，数据库默认写入 2222，这个端口需要在两个地方配置
