### ISSUE TITLE
[Bug] chen组件数据库导出问题

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#13248]
## 当前使用的 JumpServer 版本 (必填)
v3.10.9

## 使用的版本类型 (必填)

- [ ] 企业版

## 版本安装方式 (必填)
- [x] 离线安装 (下载离线包)

## Bug 描述 (详细)
数据库表中导出的格式乱码，jumpserver web gui连接数据查询返回结果显示正常，导出中文乱码，这里测试使用的是mysql类型数据库

![image](https://github.com/jumpserver/jumpserver/assets/136363116/d47da9af-35c3-49ec-bad2-5d2722a8e450)
![ba711df44c35a50f75dedb3ba96f79f](https://github.com/jumpserver/jumpserver/assets/136363116/eac45c94-feee-40e7-bf8b-33e014bddf86)

还存在字段都是char类型，导出为科学计数法的情况

![bb7d601a-7e43-42de-bc7d-30af361ff350](https://github.com/jumpserver/jumpserver/assets/136363116/c0305ac4-b646-41f3-ade7-0d0d6473eccc)

## 复现步骤
1. 创建一个测试数据表
2. 插入几条中文数据
3. web gui连接查询数据，正常显示中文，导出excel则出现乱码

## 期望行为
数据库表导出格式正常，无乱码现象
## 系统环境
- 操作系统：centos7
- 浏览器/应用版本：Chrome

**Comment by jym503558564** [comment]
是使用office办公软件打开的吗？可尝试使用wps软件打开csv文件看看，是否还存在乱码。
