### ISSUE TITLE
jumpserver  Version 1.3.0-2 GPLv2.

### ISSUE THREAD

**Issue by shenhongbin7854** [jumpserver/jumpserver#1324]
页面上设置授权规则问题：
操作过程：
      1 添加一条授权规则，一个主机，添加两个用户。  coco登录正常显示。
      2 删除规则中的一个用户，coco还是现实两个用户，web显示一个用户。
    
![default](https://user-images.githubusercontent.com/29226778/40032938-c1ce6c84-5828-11e8-8c37-06893665824a.png)

![default](https://user-images.githubusercontent.com/29226778/40032956-da837a4e-5828-11e8-9dda-b8d882f257d5.png)

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
