### ISSUE TITLE
[Bug] 访问k8s资产，连接容器后，如果容器被回收或销毁，这时候刷新左边的资产树页面就提示“没有权限”。

### ISSUE THREAD

**Issue by shimengqiao** [jumpserver/jumpserver#13243]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.9

## 使用的版本类型 (必填)
* [ ]  社区版
* [ ] 企业版
* [x] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [x] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
访问k8s资产，连接容器后，如果容器被回收或销毁，这时候刷新左边的资产树页面就提示“没有权限”，需要重新进入这个k8s资产才能正常访问。

## 复现步骤
1. 进入一个容器
2. 对容器进行了回收或者销毁
3. 这个时候堡垒机页面就没有反应了
4. 刷新资源树，就报错了，然后页面就卡死了一直提示没有权限
![image](https://github.com/jumpserver/jumpserver/assets/104493699/f884c9a7-0fbd-47d7-9464-dbfd0043badb)
![image](https://github.com/jumpserver/jumpserver/assets/104493699/76c41690-d65c-45c3-9c48-09ed3448cd02)

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
每次连接都会使用一个 Token，而每个 Token 只能使用一次。

连接成功后你直接刷新左侧树试试，应该也会提示没有权限。

**Comment by BaiJiangJie** [comment]
连接成功后，过 5 min，再尝试刷新资产树。

默认 Token 过期时间 5min，如果 5 min 内一直刷新，会一直续期 5min，所以要保证 5 min内没有刷新资产树。
然后测试，过5min后再刷新，应该会提示 Token 过期的问题。
