### ISSUE TITLE
[Question] 社区版本支持调取windows自带rdp客户端远程吗？

### ISSUE THREAD

**Issue by Coflys** [jumpserver/jumpserver#13247]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ ] 离线安装 (下载离线包)
- [ ] All-in-One
- [x] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在这里描述你遇到的问题]
windows 远程只能使用web gui，没有看到桌面客户端

## 背景信息
- 操作系统：win10
- 浏览器/应用版本：edge最新
- 其他相关环境信息：

## 具体问题
[在这里详细描述你的问题，包括任何相关细节或错误信息]
![image](https://github.com/jumpserver/jumpserver/assets/4775343/b1b23857-ea4f-468e-a640-167b162d0261)

## 尝试过的解决方法
[如果你已经尝试过解决问题，请在这里列出你已经尝试过的解决方法]
网上搜索过了，没有发现有这个问题的说明。。。
## 预期结果
[描述你期望的解决方案或结果]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by Coflys** [comment]
已安装 jumpserver client，发现RDP还是没有桌面选项

**Comment by jym503558564** [comment]
社区版不支持。

**Comment by BaiJiangJie** [comment]
如果对客户端方式感兴趣，可以在 https://jumpserver.org/enterprise.html 申请企业试用版体验一下。
