### ISSUE TITLE
[Bug] jumpserver 集成freeipa  用户同步问题

### ISSUE THREAD

**Issue by liuhaixiao** [jumpserver/jumpserver#13253]
![image](https://github.com/jumpserver/jumpserver/assets/21102326/dcb94564-cd2e-431a-998e-f91e35131ad4)

1.jumpserver如上版本 集成freeipa  ldap后 ，如果在ldap上面删除用户 但是jumpserver 上面的用户还在，并不会删除 

在用户管理  用户列表依然可以看打此用户

**Comment by BaiJiangJie** [comment]
是的，不会删除。因为有些用户使用 LDAP 配置时会经常修改 OU，每次同步时没有获取到的用户，不一定是已删除的用户。
所以你可以配置属性映射时使用 is_active 字段，每次在 LDAP 端删除用户前，先将用户禁用，同步一次，这时候 JumpServer 端的用户会设置为禁用状态。`{is_active: “LDAP 端bool类型的字段就行”}`

**Comment by liuhaixiao** [comment]
Thank  you  very  much
