### ISSUE TITLE
RDP 协议下的 Ctrl+Alt+shift 粘贴板不可使用解决办法。

### ISSUE THREAD

**Issue by TelDragon** [jumpserver/jumpserver#1325]
[简述你的问题]
RDP 协议下的 Ctrl+Alt+shift 粘贴板不可

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.30

##### 问题复现步骤

可能缺少组件造成。
debian/ubuntu  平台
libfreerdp-dev

$ apt-get install libfreerdp-dev
Fedora / CentOS / RHEL 平台
freerdp-devel  freerdp-plugins

$ yum install freerdp-devel  freerdp-plugins

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
写下操作步骤，在jumpserver上面安装吗？还是guacamole上？

**Comment by kemenkai** [comment]
写下操作步骤，在jumpserver上面安装吗？还是guacamole上？

**Comment by NeilyoSH** [comment]
查了一下guacamole 安装部署文档，应该是在Docker-guacamole 里安装这些依赖的lib库
