### ISSUE TITLE
反向代理jumpserver 要求配置可信任域名或主机，否则无法正常使用

### ISSUE THREAD

**Issue by limoou** [jumpserver/jumpserver#13256]
版本V3.10.10

反向代理的nginx的配置文件：
server {
    listen 80;
    server_name jump_test.tkeasia.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name jump_test.tkeasia.com;  # 修改成你的域名或者注释掉

    ssl_certificate "/etc/nginx/ssl/tech.tkeasia.com.crt";
    ssl_certificate_key "/etc/nginx/ssl/tech.tkeasia.com.key";
    ssl_session_timeout  1d;
    ssl_session_cache shared:MoSSL:10m;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_protocols TLSv1.1 TLSv1.2;
    add_header Strict-Transport-Security "max-age=63072000" always;

    access_log   /var/log/nginx/jump_test.access.log  main;
    client_max_body_size 4096m;

    location / {
      proxy_pass      http://10.251.68.237:18080;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_ignore_client_abort on;
      proxy_connect_timeout 600;
      proxy_send_timeout 600;
      proxy_read_timeout 600;
      send_timeout 6000;
    }
}
## 使用的版本类型 (必填)
- [ ] 社区版

## 问题描述 (详细)
DOMAINS="jump_test.tkeasia.com:18080,jump_test.tkeasia.com:443,10.251.68.237:18080"
使用ip+端口的方式可以访问
域名+端口就不行
没有开启 ssl 
测试开启之后导入证书加域名都不可以访问。
我不知道该如何正确配置这个 DOMAINS

**Comment by limoou** [comment]
![QQ截图20240520160344](https://github.com/jumpserver/jumpserver/assets/34920129/2bc2db8d-a945-4c65-8d6f-cda142abdeeb)
![QQ截图20240520160511](https://github.com/jumpserver/jumpserver/assets/34920129/8946fcf3-944c-417d-bde7-85e648c644b2)

我已经修改了 结果如上。
我做的操作如下：
1. 修改 /opt/jumpserver/config/config.txt
DOMAINS="jump_test.tkeasia.com:18080,10.251.68.237:18080"

2. ./jmsctl.sh restart

这还是没有访问代理的情况，还需要配置什么吗？ 或是能不能关闭这个检测。

**Comment by limoou** [comment]
> 改成如下：
> 
> ```
> DOMAINS="10.251.68.237:18080,jump_test.tkeasia.com:18080"
> ```
> 
> 重启 `JumpServer` 即可

我已经修改了 还是不行。
我做的操作如下：

修改 /opt/jumpserver/config/config.txt
DOMAINS="jump_test.tkeasia.com:18080,10.251.68.237:18080"

./jmsctl.sh restart

这还是没有访问代理的情况，还需要配置什么吗？ 或是能不能关闭这个检测。

**Comment by Ewall555** [comment]
> > 改成如下：
> > ```
> > DOMAINS="10.251.68.237:18080,jump_test.tkeasia.com:18080"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 重启 `JumpServer` 即可
> 
> 我已经修改了 还是不行。 我做的操作如下：
> 
> 修改 /opt/jumpserver/config/config.txt DOMAINS="jump_test.tkeasia.com:18080,10.251.68.237:18080"
> 
> ./jmsctl.sh restart
> 
> 这还是没有访问代理的情况，还需要配置什么吗？ 或是能不能关闭这个检测。

清除浏览器缓存

**Comment by wojiushixiaobai** [comment]
重启 `JumpServer` 后，检查启动日志，确定你配置的域名正确显示
docker logs -f jms_core --tail 200

**Comment by limoou** [comment]
> 重启 `JumpServer` 后，检查启动日志，确定你配置的域名正确显示
> 
> ```shell
> docker logs -f jms_core --tail 200
> ```

![image](https://github.com/jumpserver/jumpserver/assets/34920129/7891a1b1-c88b-4ff8-a107-038ce6f64dc4)

**Comment by limoou** [comment]
> > > 改成如下：
> > > ```
> > > DOMAINS="10.251.68.237:18080,jump_test.tkeasia.com:18080"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 重启 `JumpServer` 即可
> > 
> > 
> > 我已经修改了 还是不行。 我做的操作如下：
> > 修改 /opt/jumpserver/config/config.txt DOMAINS="jump_test.tkeasia.com:18080,10.251.68.237:18080"
> > ./jmsctl.sh restart
> > 这还是没有访问代理的情况，还需要配置什么吗？ 或是能不能关闭这个检测。
> 
> 清除浏览器缓存

F12 禁用缓存的，确实是这样的。

**Comment by limoou** [comment]
我已经解决，我的解决方式是把 jump_test.tkeasia.com域名改为 jumpatest.tkeasia.com ，貌似不支持下划线。
我看不懂代码也不太知道，但我感觉应该是一个问题 你们可以看看。
![image](https://github.com/jumpserver/jumpserver/assets/34920129/7ed5b620-2aaf-492e-bc19-247001b5def8)
