### ISSUE TITLE
[Bug] 全局组织显示 BUG

### ISSUE THREAD

**Issue by Evo555** [jumpserver/jumpserver#13254]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.9
v3.10.10

## 使用的版本类型 (必填)
- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [x] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
#13238 社区用户在全局组织将导致无法创建资产，关闭旧标签页后清除浏览器缓存无法恢复，新版本稳定复现

**Comment by BaiJiangJie** [comment]
将 Local storage 清除一下。

**Comment by Evo555** [comment]
存在恢复方式
