### ISSUE TITLE
![image](https://github.com/jumpserver/jumpserver/assets/3939631/5d47fa46-11a4-4d7c-91ce-f7d6d93128e0)

### ISSUE THREAD

**Issue by zWeng33** [jumpserver/jumpserver#13260]
![image](https://github.com/jumpserver/jumpserver/assets/3939631/5d47fa46-11a4-4d7c-91ce-f7d6d93128e0)

_Originally posted by @zWeng33 in https://github.com/jumpserver/jumpserver/issues/13202#issuecomment-2114099218_

**Comment by BaiJiangJie** [comment]
Discussed in #13202
