### ISSUE TITLE
[Feature] 增加终端记录导出功能

### ISSUE THREAD

**Issue by blankleee** [jumpserver/jumpserver#13261]
## 功能名称
增加终端记录导出功能

## 功能描述
可以导出当前终端记录信息，导出为txt文件

## 用户故事（可选）
在做等保需求的时候，有一些检查脚本要执行。执行完要把记录保存，目前的做法是执行脚本，保存结果，下载结果。这样比较繁琐。
如果可以直接导出当前终端的记录。就执行脚本，导出记录就行了。

等保检测可能是一个例子，可能会有其他需求有类似的场景。

## 功能要求
在web终端页面有一个按钮可以导出当前终端的记录

**Comment by BaiJiangJie** [comment]
连接 Linux 资产时的命令记录吗？

**Comment by blankleee** [comment]
> 我理解时，想要导出 Web CLI 方式连接 Linux 资产会话时的执行的命令记录，对吗？

对的， 在web终端里面导出当前会话的执行记录。

**Comment by BaiJiangJie** [comment]
Web 终端里暂时没有计划支持用户直接导出。

但是，目前审计台中管理员可以导出命令记录。
