### ISSUE TITLE
coco 启动报WebSocket transport not available

### ISSUE THREAD

**Issue by jaikewhh166** [jumpserver/jumpserver#1326]
[简述你的问题]
coco 启动报WebSocket transport not available，Install eventlet or gevent and gevent-websocket for improved performance.   http的5000端口无法连接 
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
jumpserver 1.3.0
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/39252581/40035519-bc7b76f8-5834-11e8-9fa9-f1f81151b5c7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
这个端口是给luna使用的，不是给用户直接访问的
