### ISSUE TITLE
黑客“凭空”创建了一个账号

### ISSUE THREAD

**Issue by motuwe** [jumpserver/jumpserver#13267]
版本: v3.10.3

最近一直在处理服务器资源泄露的问题，追溯至了 jumpserver。黑客“凭空”创建了一个账户。
如图，是 System 创建，而且加入时间和最后更新密码时间竟然在同一秒。怎么做到的？

![image](https://github.com/jumpserver/jumpserver/assets/5621857/213beeb6-bd69-4b79-964e-b802db4486ff)

**Comment by BaiJiangJie** [comment]
可能情况是通过 django shell 中创建的用户。

最后更新密码日期，会在用户首次创建时更新，也就是首次创建的用户最后更新密码日期和加入日期是一致的。

**Comment by BaiJiangJie** [comment]
建议日常管理好服务器的密码/密钥信息。

**Comment by motuwe** [comment]
> 最后更新密码日期，会在用户首次创建时更新，也就是首次创建的用户最后更新密码日期和加入日期是一致的。

用户首次通过 Web 登录是需要修改密码的，不能做到同一秒吧？

**Comment by BaiJiangJie** [comment]
不用登录，用户创建成功后，就是最后更新密码日期就是有值的。

**Comment by motuwe** [comment]
> 可能情况是通过 django shell 中创建的用户

第一时间证实是通过 django shell 创建的用户，黑客并未清除 Docker Bash 里的 History。
谢谢解惑。


> 不用登录，用户创建成功后，就是最后更新密码日期就是有值的

但是 TA 登录了，所以奇怪点就在这里，而且是通过 Web 登录，这种情况下不改密码说不过去。难道说 System 创建的用户不用改密码？

![Snipaste_2024-05-21_15-42-08](https://github.com/jumpserver/jumpserver/assets/5621857/26f77ffa-0191-4bec-9289-e8b1ba58f5b1)

![Snipaste_2024-05-23_14-59-12](https://github.com/jumpserver/jumpserver/assets/5621857/5df9d8d8-b1d6-4191-bf64-866b039c306b)
