### ISSUE TITLE
[Question] 公网地址无法访问，内网地址可以访问

### ISSUE THREAD

**Issue by H4AER** [jumpserver/jumpserver#13270]
## 当前使用的 JumpServer 版本 (必填)
[jumpserver-offline-release-v3.10.10-amd64]

## 使用的版本类型 (必填)
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## 问题描述 (详细)
[在这里描述你遇到的问题]
部署成功后，使用公网ip访问堡垒机后无法连接到资产（弹出提示框显示{"isTrusted":true}），使用内网ip可以访问到资产

## 尝试过的解决方法
[开放堡垒机、资产主机所有端口]

## 预期结果
[期望使用公网ip访问堡垒机后可以连接到资产]

## 我们的期望
[描述你希望我们提供的帮助或支持]

**Comment by BaiJiangJie** [comment]
<img width="921" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/48d480c6-5912-4457-a94b-12959a77a32d">
https://docs.jumpserver.org/zh/v3/installation/upgrade_notice/
配置一下 DOMAINS 试试。

**Comment by H4AER** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/15047422/89b6d3ad-04f0-494b-9098-3636f741166d)
配置并重启过的

**Comment by H4AER** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/15047422/9a55bf32-3bbc-4459-ab75-d821766fb246)
![图片](https://github.com/jumpserver/jumpserver/assets/15047422/0845c7b4-4bf3-4703-a836-43e284b67cf7)
这是公网和内网访问的图片

**Comment by BaiJiangJie** [comment]
打开浏览器控制台，看一下 API 请求的 地址、方法、请求体、响应体。

**Comment by H4AER** [comment]
公网 ，没有响应
![图片](https://github.com/jumpserver/jumpserver/assets/15047422/8a7d0795-f2c5-458f-9888-0134d3f07af8)

**Comment by H4AER** [comment]
![图片](https://github.com/jumpserver/jumpserver/assets/15047422/d0459683-8380-48c8-85e1-06a499d05a2c)

**Comment by Evo555** [comment]
换个浏览器试试？
