### ISSUE TITLE
[Question] Jumpserver 升级问题

### ISSUE THREAD

**Issue by lxsexl** [jumpserver/jumpserver#13279]
## 当前使用的 JumpServer 版本 (必填)
[v3.10.7]

## 使用的版本类型 (必填)
- [*] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [*] 在线安装 (一键命令)
- [*] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
从v3.10.7准备升级到v3.10.8的过程中，在第5步，进行数据库变更时出现出错信息，跳过v3.10.8直接升级v3.10.10也出现相同的信息，并且我试了在线一键升级和一键离线升级都如此。

## 背景信息
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
ERROR: The Compose file './compose/docker-compose-network.yml' is invalid because:
networks.net contains an invalid type, it should be a string

ERROR: Invalid interpolation format for "core" option in service "services": "${REGISTRY:-docker.io}/jumpserver/core-ce:${VERSION}"

## 尝试过的解决方法
第一个错误看上去是无效类型，对比了v3.10.7的同文件，内容差不多。
第二个错误翻译了下说什么插值格式无效。
也找不到升级时的日志，解决不了这两个问题。

## 预期结果
这是BUG还是我原来版本有问题，造成此情况？能否不在重新安装的基础上，修复这两个问题，并能正常升级？

## 我们的期望
[描述你希望我们提供的帮助或支持]

![捕获](https://github.com/jumpserver/jumpserver/assets/113326833/b8228d3e-d737-4def-b445-37c1141cbc52)

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/jumpserver/issues/13164
升级你的 `docker-compose` 即可
