### ISSUE TITLE
录像存储增加自定义策略功能

### ISSUE THREAD

**Issue by VossenZhou** [jumpserver/jumpserver#13271]
录像可以自定义设定存储空间大小，满了会自动清理时间久的录像
因服务器长时间未登录，录像时间久远，防止自动清理录像，建议可以自定义设定保留服务器登录近三次的操作录像，不会被自动清理

**Comment by BaiJiangJie** [comment]
对于录像存储策略比较复杂的场景，建议使用云端的对象存储。

因为对于一台资产，可能会有不同的用户去登录。

**Comment by VossenZhou** [comment]
因公司政策相关要求，不能使用云端产品

> 对于录像存储策略比较复杂的场景，建议使用云端的对象存储。
> 
> 因为对于一台资产，可能会有不同的用户去登录。

因公司政策相关要求，不能使用云端产品

**Comment by VossenZhou** [comment]
因公司政策相关要求，不能使用云端产品

对于录像存储策略比较复杂的场景，建议使用云端的对象存储。

因为对于一台资产，可能会有不同的用户去登录。

因公司政策相关要求，不能使用云端产品

**Comment by BaiJiangJie** [comment]
本地存储方式暂时不考虑支持设置策略。
