### ISSUE TITLE
[Bug] WebSocket connection to 'ws://192.168.101.12/ws/ops/tasks/log/' failed:

### ISSUE THREAD

**Issue by HGHNice** [jumpserver/jumpserver#13276]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
v3.10.10
## 使用的版本类型 (必填)
- [x] 社区版

## 版本安装方式 (必填)
- [x] 在线安装 (一键命令)

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]

## 复现步骤
1. [描述如何复现 Bug 的第一步]
进行安装之后访问网页  批量命令这边 点击F12 会显示这个
![image](https://github.com/jumpserver/jumpserver/assets/84365959/c3b6f18a-cc6b-46bf-b94e-2d64f4cc9a03)
我的docker 容器里的nginx的配置为
![image](https://github.com/jumpserver/jumpserver/assets/84365959/005b5db5-d0c2-441a-b838-988f0f27171a)

## 期望
请问大家如何解决呢？
## 系统环境
- 操作系统：[例如：Windows 10]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

**Comment by HGHNice** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/84365959/fc5c5344-72b2-43c3-bdb7-1c1cea37da43)
这是我点击功能的地方

**Comment by HGHNice** [comment]
批量命令是可以执行的  但是无法在web页面看见日志

**Comment by BaiJiangJie** [comment]
<img width="899" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/43b80464-f1bd-4e0d-8c23-0d07d1149604">

去掉这一行试试。

**Comment by BaiJiangJie** [comment]
jms_web 容器里的 nginx 不用修改，使用默认的配置。

jumpserver 服务器之上还有其他 nginx 服务吗？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/docker-web/blob/master/includes/core.conf

**Comment by HGHNice** [comment]
不行的  会不会是我使用的不是https协议？

**Comment by BaiJiangJie** [comment]
页面上访问的地址是 192 开头的ip吗？

**Comment by HGHNice** [comment]
是的哦

**Comment by HGHNice** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/84365959/8af12f0d-4edd-49f1-bef5-fe09d247591b)

**Comment by BaiJiangJie** [comment]
jumpserver 服务器之上还有其他 nginx 服务吗？

**Comment by HGHNice** [comment]
没有的  直接访问的

**Comment by BaiJiangJie** [comment]
全部重启一下服务试试

**Comment by HGHNice** [comment]
试过了哦 重装也是

**Comment by BaiJiangJie** [comment]
有防火墙之类的吗？

**Comment by HGHNice** [comment]
没有哦

**Comment by HGHNice** [comment]
直接停止防火墙也不行

**Comment by HGHNice** [comment]
就是批量命令是可以执行的  说明其中一个websocket是可以执行的  但是我需要在webui看见日志  这个websocket是连接失败的  抓包显示504的

**Comment by HGHNice** [comment]
就是/ws/ops/tasks/log/这个路径的websocket是失败的

**Comment by BaiJiangJie** [comment]
<img width="1645" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/97d76de6-999e-48ee-b234-d59e87d80974">

https://demo.jumpserver.org/

试试 demo 环境。

**Comment by HGHNice** [comment]
demo环境没问题的 除了请求协议是https不同以外

**Comment by HGHNice** [comment]
所以我怀疑 是不是不支持普通http  只支持https

**Comment by BaiJiangJie** [comment]
http 也支持，应该是你网络环境的问题。

**Comment by HGHNice** [comment]
不是哦  我将你们前端的复制 enable的websocket的段  我改成wss协议 是不报错的  我电脑本身不开启代理等 也让别的同事进行测试

**Comment by HGHNice** [comment]
没有的

**Comment by BaiJiangJie** [comment]
你是在云上部署的还是本地服务器上部署的？

**Comment by wojiushixiaobai** [comment]
检查 `WAF`，一般此现象都是被拦截了

**Comment by HGHNice** [comment]
您好 我这边检查了 当前这个网段的waf  并没有拦截 还有没有其他原因呢

**Comment by BaiJiangJie** [comment]
从网络环境中找找原因。

**Comment by HGHNice** [comment]
我这边打开https之后 就可以了 想不通是什么问题

**Comment by HGHNice** [comment]
http的时候是不行的
