### ISSUE TITLE
建立的资产授权不显示

### ISSUE THREAD

**Issue by oldwangtou** [jumpserver/jumpserver#1327]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本1.0.0]

##### 问题复现步骤
1. 之前创建的资产授权不见了，数据库了信息存在
2. 点击资产授权，之前创建的授权规则名字 闪烁一下就消失，创建相同名字的时候会提示已存在。

##### 具体表现[截图可能会更好些,最好能截全]

![Uploading 111.png…]()

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues
