### ISSUE TITLE
[Question] issue#12794 追加问题，LDAP用户vscode Remote-ssh直连托管机token过期时间设置

### ISSUE THREAD

**Issue by CupofFish** [jumpserver/jumpserver#13278]
## 当前使用的 JumpServer 版本 (必填)
3.10.9

您好，我们升级到了v3.10.9，页面显示token的过期时间还是五分钟，我们在vscode里仍然五分钟就断连，token过期时间我们能设置嘛？
![image](https://github.com/jumpserver/jumpserver/assets/44918824/2d44e52d-f12c-42e7-bd40-668e23402da6)
了解到CONNECTION_TOKEN_EXPIRATION 和 CONNECTION_TOKEN_REUSABLE变量，但我们不能直接配置在/opt/jumpserver/config/config.txt中 。请教一下我们该怎么解决？

**Comment by BaiJiangJie** [comment]
配置文件中配置 CONNECTION_TOKEN_EXPIRATION 的只值，默认是 5 min

页面上不能配置，页面连接资产时，只能选择当前 Token 是否开启复用，而复用时间只能通过配置文件参数指定。

**Comment by CupofFish** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/44918824/4d8ca72b-7dc3-41d6-bf8f-c3cfc5e8c102)
@BaiJiangJie 您好，我在/opt/jumpserver/config/config.txt这个文件中配置的，容器起不来，请问我该在哪个文件中配置呢？

**Comment by BaiJiangJie** [comment]
就是在这个文件中配置，但是你配置的格式不对，不能使用python中相乘的格式，直接写一个固定的数字。

**Comment by CupofFish** [comment]
收到，已配置已解决，谢谢！！！

**Comment by zdf0221** [comment]
您好，我们配置成功之后上午测试了下，发现还是会有不规律的断开连接情况（大致5-15min不等），使用LDAP密码能重连。这个问题应该如何排查？谢谢
