### ISSUE TITLE
[Bug] Web CLI无法使用只读账号连接阿里云Redis

### ISSUE THREAD

**Issue by CoderConan** [jumpserver/jumpserver#13282]
## 当前使用的 JumpServer 版本
v3.10.8

## 使用的版本类型
社区版

## 版本安装方式
在线安装 (一键命令)

## Bug 描述 (详细)

Web CLI无法使用 只读账号 连接阿里云Redis：

## 复现步骤
1. 其他配置都不变，账号改为读写权限账号可以正常连接；
2. 其他配置不变，连接方式选择 [数据库客户端] 方式可以正常连接
![image](https://github.com/jumpserver/jumpserver/assets/88372830/cd536988-1c48-46b1-b56d-05885c21b846)
4. 非特殊字符问题，改为非特殊符号的用户名和密码依然无法连接，提示invalid password；
5. 使用 user@password 格式作为密码登录依然提示invalid password；
![image](https://github.com/jumpserver/jumpserver/assets/88372830/34957a40-d595-4430-bee5-00d33c96a602)
## 期望行为
能够正常连接Redis。

## 实际行为
提示invalid password，无法连接。

## 系统环境
- 操作系统：Windows 10
- 浏览器/应用版本：Chrome
- 阿里云Redis版本：Redis 5.0

## 附加信息

jms_koko日志：

2024-05-24 17:21:35 [ERRO] ERR invalid password.
2024-05-24 17:21:35 [ERRO] 开始连接数据库 xxx-redis-01(r-xxx.redis.rds.aliyuncs.com) error: ERR invalid password.
2024-05-24 17:21:35 [ERRO] Try password: hmo4V*********
2024-05-24 17:21:35 [ERRO] Ws[b2af9dd3-6282-49ed-bc9f-acb757xxx9bb] read message err: websocket: close 1005 (no status)

![image](https://github.com/jumpserver/jumpserver/assets/88372830/a15e8b3d-a5be-4a81-bdcf-421b134dc121)

**Comment by LeeEirc** [comment]
Redis 账号是否配置了username ？添加一个 null 账号测试一下？

**Comment by CoderConan** [comment]
> Redis 账号是否配置了username ？添加一个 null 账号测试一下？
配置了username，使用null账号测试还是报error: ERR invalid password.
![image](https://github.com/jumpserver/jumpserver/assets/88372830/10c62c11-1cba-45f3-a8f4-2c51868b4b1c)

**Comment by LeeEirc** [comment]
好的，属于阿里云 Redis 密码有特殊设置。
