### ISSUE TITLE
[Feature] web终端页面增加支持复制标签文字和搜索不区分大小写字母选项

### ISSUE THREAD

**Issue by sansam** [jumpserver/jumpserver#13287]
## 功能名称
web终端页面增加支持复制标签文字和搜索不区分大小写字母选项

## 功能描述
不少场景下，需要复制标签中的文字，文字内容包含了资产名称，IP地址等信息

## 用户故事（可选）
比如需要获取资产IP，到另外一个系统里面进行搜索，或者分享给其他人资产IP

## 功能要求
- 要求1：
web终端页面：
--在树形资产列表，右键点击资产名称，增加一个复制资产名称的选项。
--右键点击已打开的标签，增加一个复制资产名称的选项。
- 要求2：
web终端页面：
搜索不区分大小写字母（在后台设置页面增加该设置选项）

- [以此类推，列出所有相关的功能要求]

## 优先级
中

**Comment by BaiJiangJie** [comment]
第一个需求暂时不考虑，如果要复制资产的信息，在“工作台-我的资产”页面。

第2个需求，搜索是否支持大小写搜索是和mysql数据库设置相关的。
JumpServer 初始化的数据库默认是区分大小的，你可以自己创建一个数据库设置为不区分大小写。
