### ISSUE TITLE
[Feature] 安卓资产控制

### ISSUE THREAD

**Issue by dgbfm36** [jumpserver/jumpserver#13285]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 安卓资产
[在这里输入功能的名称或标题]

## 功能描述
[在这里描述该功能的详细内容，包括其作用、目的和所需的功能]
Android adb 网络控制
能不能增加上安卓终端远程，把scrcpy嵌入进，有许多安卓资产也需要管理

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]
输入ip和端口，要是有frpc中转更安全，用stcp协议，这个需要加上连接密码和本机端口
## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]
scrcpy
## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]
中
## 备注（可选）
[在这里添加任何其他相关信息或备注]
只是想要这个功能，想着安卓资源也不少，市场上没有统一管理安卓的资产审计软件，提下这方面要求

**Comment by ibuler** [comment]
有没有 demo 的项目？

**Comment by dgbfm36** [comment]
可以参考这个：https://github.com/Genymobile/scrcpy

**Comment by BaiJiangJie** [comment]
看起来有点复杂，暂时先不考虑支持。
