### ISSUE TITLE
[Question] 给core新增一个接口

### ISSUE THREAD

**Issue by fanlc** [jumpserver/jumpserver#13280]
## 当前使用的 JumpServer 版本 (必填)
[v3.10.9]

## 使用的版本类型 (必填)
- 社区版

## 版本安装方式 (必填)
- [ ] 源码安装

## 问题描述 (详细)
您好，我是直接修改的core源码
1，我想给core服务新增一个自己的接口
2，在这个文件新增 jumpserver-v3.10.9/apps/perms/urls/user_permission.py
3，自己的接口是/api/v1/perms/users/mytickets/createauth/
4，然后使用postman，curl，python脚本调用这个接口 http://my.aaa.ccc/api/v1/perms/users/mytickets/createauth/
5，get请求是没问题的，但是post请求就一直报错.
6，返回就是登陆界面的html文件，错误是
        配置文件有问题，无法登录，请联系管理员或查看最新文档<br/>
        如果你是管理员，可以更新配置文件解决，设置配置项 <br/>
        DOMAINS=10.8.100.102:8080
7，DOMAINS=10.8.100.102:8080 这个配置我在config.yml。里面已经加了。
8，我自己写的接口get，都没问题，post就会出现这个问题。
9，是因为你们核心代码里面有对于接口权限的 限制吗。

感谢大佬 抽出宝贵的时间 为我解答。

## 背景信息
- 操作系统：centos7

## 我们的期望
1，希望大佬能抽出时间为我解答这个问题
2，比如我想新增一个自己的接口，怎么配置下呢

**Comment by BaiJiangJie** [comment]
你先通过 Postman 访问一下其他 POST 接口，比如创建一个资产/用户，是不是可以成功？

**Comment by BaiJiangJie** [comment]
参考其他 API 开发，正常没有限制。

**Comment by fanlc** [comment]
好的 感谢，我再找找是啥问题。
