### ISSUE TITLE
苹果电脑本地拉起客户端闪退-芯片是mac1 pro

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13281]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[V3.10.7]

## 使用的版本类型 (必填)
- [ ] 社区版
- [√] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [√] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## Bug 描述 (详细)
[mac电脑拉起本地客户端闪退，电脑芯片是mac1 pro ，版本macos Sonoma14.5 和 macosSonoma14.4都出现闪退问题，客户端使用第一天还是macosSonoma14.4正常拉起，第二天就是闪退了，升级macos Sonoma14.5 有段时间是正常的，后面又闪退了，不使用堡垒机本地直连是可以的]

## 复现步骤
1. [mac1 pro拉起客户端，系统是macos Sonoma14.5 和 macosSonoma14.4，第一天正常，后面就闪退]

## 系统环境
- 操作系统：[系统是macos Sonoma14.5 和 macosSonoma14.4]
- 其他相关环境信息：[芯片是mac1 pro]

## 附加信息（可选）
[不使用堡垒机，本地直连是可以的]

**Comment by BaiJiangJie** [comment]
拉起的什么客户端？
