### ISSUE TITLE
[Bug] Luna页面命令行资产无法修改别名

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#13288]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.10

## 使用的版本类型 (必填)
- [ ] 企业版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
luna页面命令行资产无法修改别名，windows、远程应用这些可以修改

## 复现步骤
1、双击tab页标题，无光标显示，输入信息会在下面对话框内显示，测试发现是cli的都会这样
![image](https://github.com/jumpserver/jumpserver/assets/66759501/7339c62c-b6a5-4c52-911a-f75d917d3ee9)
2、双击tab页应用标题，有光标显示，输入别名信息会正常留存显示，测试发现windows类的都可以正常显示
![image](https://github.com/jumpserver/jumpserver/assets/66759501/cfb350b4-a628-4578-940a-62b689ace26a)

## 期望行为
可以正常备注所有资产的别名

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
是的，目前有点问题，v4 版本后考虑优化一下。

**Comment by jym503558564** [comment]
v4.1.0， Luna页面已优化可修改资产别名，请升级进行体验。
