### ISSUE TITLE
[Bug] 资产授权-资产树，无法根据资产名称搜索授权

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13295]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
v3.10.10

## 使用的版本类型 (必填)
企业版

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
资产授权-资产树，无法根据资产名称搜索授权。
v3.9.2 是支持的：
![image](https://github.com/jumpserver/jumpserver/assets/15103510/189a7bac-8cb2-4d6b-8662-3e6128a146ed)
v3.10.10 不支持：
![image](https://github.com/jumpserver/jumpserver/assets/15103510/2e576ddf-0a33-4fea-9db5-4b42336d8ad7)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/13299

v3.10.11
