### ISSUE TITLE
[Question] CPU 周期性升高

### ISSUE THREAD

**Issue by Zubenxing** [jumpserver/jumpserver#13296]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[v3.9.1]

## 使用的版本类型 (必填)
- [ √] 社区版
- [ ] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)
- [ √] 离线安装 (下载离线包)
- [ ] All-in-One
- [ ] 1Panel 安装
- [ ] Kubernetes 安装
- [ ] 源码安装

## 问题描述 (详细)
[在安装完awx两天后对服务器做磁盘扩容，中途停机3分钟左右，再次开机后3个小时左右CPU高居不下]

## 背景信息
- 操作系统：[例如：Windows 10]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 具体问题
[在安装完awx两天后对服务器做磁盘扩容，中途停机3分钟左右，再次开机后3个小时左右CPU高居不下]

## 尝试过的解决方法
[重启容器 重启服务器 修改容器配置]

## 预期结果
[帮忙找出CPU升高的原因已解决方案]

## 我们的期望
[帮忙查找问题]

**Comment by BaiJiangJie** [comment]
哪个进程 CPU 高？

**Comment by Zubenxing** [comment]
> 哪个进程 CPU 占用高？

从docker stats来看是 jms_core 这个pod的CPU占用高 在100%左右
从top来看 gunicorn

**Comment by BaiJiangJie** [comment]
看看曲线图，一直高还是有起伏的。

**Comment by Zubenxing** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/133339362/f4cd136a-c7e3-4071-8106-b1583faf305b)
跑满CPU后一直下不来

**Comment by BaiJiangJie** [comment]
这是 5.24 号的，今天的负载如何？
