### ISSUE TITLE
[Feature] Jumpserver提供使用SSl/TLS方式去访问PostgreSQL

### ISSUE THREAD

**Issue by Markfaye** [jumpserver/jumpserver#13298]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
使用SSl/TLS方式去访问PostgreSQL

## 功能描述
类比MYSQL的SSL/TLS功能
![image](https://github.com/jumpserver/jumpserver/assets/92771026/8787cd61-1b8a-4b91-a48e-b84aa1593751)

## 用户故事（可选）
用户的PostgreSQL服务器设置了TLS，通过Jumpserver去访问的时候报This RDS Proxy requires TLS connections的错误，所以Jumpserver需要提供配置SSL/TLS的入口。

## 功能要求
类比MYSQL的SSL/TLS功能

## 示例或原型（可选）
![image](https://github.com/jumpserver/jumpserver/assets/92771026/c14012ea-3c3f-41b0-8ab4-48d5641c81e8)

## 优先级
中

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
v4+ 后可以考虑。

**Comment by BaiJiangJie** [comment]
Chen、Magnus、KoKo

**Comment by BaiJiangJie** [comment]
v4.2.0 版本 KoKo、Chen、自动化任务已支持。
