### ISSUE TITLE
[Feature] 工单申请备注是否可以设置为必填

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#13294]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
工单申请备注是否可以设置为必填

## 功能描述
工单申请备注是否可以设置为必填，当前工单缺少必要的描述部分，唯一一个备注还是选填，不强制的话申请者都不填

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
工单申请备注是否可以设置为必填，当前工单缺少必要的描述部分，唯一一个备注还是选填，不强制的话申请者都不填
![image](https://github.com/jumpserver/jumpserver/assets/66759501/907c84b5-3549-4d24-a851-a0602be1ec56)

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
高（打算购买，准企业版用户）

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
暂时不考虑。
