### ISSUE TITLE
Windows机器通过web界面实现文件的上传下载？

### ISSUE THREAD

**Issue by Michael754267513** [jumpserver/jumpserver#1329]
登入web界面。打开windows机器。然后拖拽文件到web界面的Windows机器里面，在web界面提示：

File transfer is either not supported or not enabled. Please contact your system administrator, or check your system logs.

接下来我该如何操作，才能实现文件的拖拽功能

**Comment by lklkxcxc** [comment]
我的也是

**Comment by wojiushixiaobai** [comment]
不要拖文件夹。

**Comment by Michael754267513** [comment]
单文件，没有拖文件夹，比如一个txt的文件，这种的

**Comment by gian2008** [comment]
我的也是，无法从windows机器上把文件脱下来!求教

**Comment by gian2008** [comment]
从windows机器上把文件拖拽到本地主机，该怎么设置？
