### ISSUE TITLE
webterminal复制粘贴问题

### ISSUE THREAD

**Issue by liuzheng712** [jumpserver/jumpserver#133]
由于在Linux下ctrl+c是撤销，而在win下是复制，故拟采用alt+c的方式进行复制粘贴，类似Mac，其他快捷键拟采用类似的方案。

现研究该方案是否会带来潜在的安全问题和新问题的引入

**Comment by lhmlihaomin** [comment]
Alt快捷键很大可能会与窗口菜单栏快捷键冲突吧？Windows下的复制粘贴可以使用 shift+insert 和 ctrl+insert 来替代。Mac下的Alt对应按钮是option键，类似mac的话那应该是使用win+c来复制粘贴，会感觉很奇怪。

**Comment by liuzheng712** [comment]
@lhmlihaomin 暂时没有很理想的键位方案，都会引入问题
