### ISSUE TITLE
[Bug] 连接远程应用，页面报错 “Core API 错误”

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13301]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
3.9.2

## 使用的版本类型 (必填)
企业版

## 版本安装方式 (必填)
离线安装

## Bug 描述 (详细)
当前环境仅有一台发布机，发布机有点问题，无法连接远程应用，于是将发布机关闭激活。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/b23b708a-8d11-4414-ac98-6d8c23915767)
1.这是在 web 端点击 web 资产，弹出连接框。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/0d5a2263-ad85-4ba3-aca9-e16bb2a285e6)
无可用发布机的时候，我们正常应该是不能使用远程应用连接方式的（未部署发布机前，连接按钮是置灰的）。
2.点击连接按钮后，页面报错 “Core API 错误”，没有相关提示，日志文件也未看到相关报错，这里如果有个提示：“无可用发布机”会更好些。当然，更推荐上面的处理方式。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/60c2f9f1-7d23-4fee-b082-610621cd7f7c)

## 复现步骤
1. [描述如何复现 Bug 的第一步]
2. [描述如何复现 Bug 的第二步]
3. [以此类推，列出所有复现 Bug 所需的步骤]

## 期望行为
[描述 Bug 出现时期望的系统行为或结果]

## 实际行为
[描述实际上发生了什么，以及 Bug 出现的具体情况]

## 系统环境
- 操作系统：[例如：Windows 10, macOS Big Sur]
- 浏览器/应用版本：[如果适用，请提供相关版本信息]
- 其他相关环境信息：[如果有其他相关环境信息，请在此处提供]

## 附加信息（可选）
[在这里添加任何其他相关信息，如截图、错误信息等]

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/13308/files

Fix in v3.10.11
