### ISSUE TITLE
web平台列表开启安全模式之后还是有方式打开新页面，以及后台

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13307]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[V3.10.9]

## 使用的版本类型 (必填)
- [ ] 企业版

## 版本安装方式 (必填)
- [ ] 离线安装 (下载离线包)

## Bug 描述 (详细)
[web平台开启安全模式后，还是有方法打开后台，以及从后台下载文件]

## 复现步骤
1. [修改平台列表，打开安全模式]
2. 
![1716864671102](https://github.com/jumpserver/jumpserver/assets/136306850/6d3ccd48-fa6d-4afb-887e-848fcbc3d677)

3. [登录web资产，页面下载文件]
4. 
![1716864671116](https://github.com/jumpserver/jumpserver/assets/136306850/0b208a76-e653-4a52-9e40-2857cae24222)

5. [通过下载打开后台文件]
6. 
![1716864671132](https://github.com/jumpserver/jumpserver/assets/136306850/8f0c574e-b357-4614-bfb9-87429c1ec3c4)

## 期望行为
[希望安全模式能够禁止用户通过文件下载打开发布机后台，安全模式下只允许用户浏览和查看web页面]

## 实际行为
[开启安全模式，不能限制用户打开访问发布机后台]

**Comment by jym503558564** [comment]
同地址的是放开的。如果打开其他标签页等，均有提示安全模式，禁止xxx等。

**Comment by 1223ruiyin** [comment]
> 同地址的是放开的。如果打开其他标签页等，均有提示安全模式，禁止xxx等。

期望同地址也可以禁止用户直接访问到后台，因为这也是一个相对比较危险的行为
