### ISSUE TITLE
[Feature] 资产详情界面，希望可以查看该资产的所有关联的授权规则，在资产授权界面搜索太麻烦

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13302]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
资产详情界面查看关联所有的授权规则。

## 功能描述
在资产授权界面搜索资产的关联授权太麻烦，希望在资产详情界面可以增加一个授权规则 Tab， 点击可以查看该资产的所有关联的授权规则。
<img width="1426" alt="image" src="https://github.com/jumpserver/jumpserver/assets/15103510/c9a030bb-2f23-4b5c-a446-fdb5e75614c9">

## 用户故事（可选）
[如果适用，可以提供用户故事来更好地理解该功能的使用场景和用户期望]

## 功能要求
- [要求1：描述该功能的具体要求，如界面设计、交互逻辑等]
- [要求2：描述该功能的另一个具体要求]
- [以此类推，列出所有相关的功能要求]

## 示例或原型（可选）
[如果有的话，提供该功能的示例或原型图以更好地说明功能的实现方式]

## 优先级
[描述该功能的优先级，如高、中、低，或使用数字等其他标识]

## 备注（可选）
[在这里添加任何其他相关信息或备注]

**Comment by BaiJiangJie** [comment]
v4+ 后考虑。

**Comment by BaiJiangJie** [comment]
v3.10.11 支持授权页面左侧资产树搜索资产后就方便了。

**Comment by BaiJiangJie** [comment]
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/c27ed533-3e0c-4136-85b3-91005a41214b">

授权页面查看。
