### ISSUE TITLE
Windows录像键盘记录，会记录到密码

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13313]
## 注意
_针对过于简单的需求描述不予考虑。请确保提供足够的细节和信息以支持功能的开发和实现。_

## 功能名称
[录像回放时，键盘不记录密码输入等操作，或者记录形式是否可以是密文]

## 功能描述
[录像不记录页面输入密码或者密码记录加密，防止密码泄露]

## 功能要求
- [录像回放对于密码输入加密或者不显示]

## 优先级
[高]

**Comment by BaiJiangJie** [comment]
目前没有比较好的方案知道是输入的密码还是其他键盘操作，暂时不支持。
