### ISSUE TITLE
[Question] accounts_account表中的_secret字段是如何加密的

### ISSUE THREAD

**Issue by hanhan2022** [jumpserver/jumpserver#13314]
## 注意
**请描述您的问题.** <br>
accounts_account表中的_secret字段是如何加密的，我直接对数据库进行操作时，应当对明文密码进行怎样的加密操作

## 当前使用的 JumpServer 版本 (必填)
[3.8.2]

## 使用的版本类型 (必填)
- [ ] 社区版

## 版本安装方式 (必填)
- [ ] 在线安装 (一键命令)

## 背景信息
- 操作系统：Windows 10

**Comment by BaiJiangJie** [comment]
使用的算法不同，加密的方式不同，工具在项目中，研究一下代码。
