### ISSUE TITLE
邮件跳转修改ssh 密码

### ISSUE THREAD

**Issue by huyipow** [jumpserver/jumpserver#1332]
[简述你的问题]

##### 使用版本
[使用 jumpserver 1.3 二进制安装]

##### 问题复现步骤
1. [配置ldap连接，用户可以正常登陆]

![default](https://user-images.githubusercontent.com/10229351/40094108-a6de3b3c-58f7-11e8-8829-cd7f4e004f70.png)

2. [在用户管理界面，修改ssh 密钥，用户收到邮件点击连接跳转报错]
![_20180516100343](https://user-images.githubusercontent.com/10229351/40094117-b2a7b394-58f7-11e8-969c-31428e270a46.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
新版本已解决，请使用最新版本，如果有问题请重新打开Issues
