### ISSUE TITLE
[Feature] 命令存储支持ES8的版本

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13339]
### 产品版本

v3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

目前命令存储es只支持es7，但是目前审计要求使用es8，能否支持

### 解决方案

命令存储支持es8版本，满足审计要求

**Comment by BaiJiangJie** [comment]
v4+ 版本后考虑支持 es8
