### ISSUE TITLE
[Feature] Would lovely if there's any English version for the Docs

### ISSUE THREAD

**Issue by rizkyfaza20** [jumpserver/jumpserver#13338]
### Product Version

All

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

Is there any chance if the product can be converted to english, I love the feature of the apps itself, but it seems because I dont understand Chinese, it will be nice.

### Proposed Solution

Is there any chance if the product can be converted to english, I love the feature of the apps itself, but it seems because I dont understand Chinese, it will be nice.

**Comment by BaiJiangJie** [comment]
Don't worry, although there is currently no fully English documentation, we plan to launch it in the second half of this year. In the meantime, you can switch the language of the product to English and use Google Translate to translate the Chinese documentation online.
