### ISSUE TITLE
[Bug] web 资产，打开浏览器使用中文输入法，没有 文字提示

### ISSUE THREAD

**Issue by Lee-Z** [jumpserver/jumpserver#13348]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver 社区版3.10.10.
部署新增web资产，登陆web资产后，使用中文输入法，输入汉字的时候，没有下面的文字选择提示

### 🐛 缺陷描述

要求是需要和在本地输入文字一样，输入中文时，下面会有文字提示

### 复现步骤

jumpserver 社区版3.10.10.
web资产：
服务器windows server 2019
安装的360 浏览器应用

### 期望结果

需要和在本地输入文字一样，输入中文时，下面会有文字提示

**Comment by BaiJiangJie** [comment]
我在连接一些 Web 资产时都会有输入法提示。

你的环境中 360 浏览器修改为 Chrome 试试呢？或者尝试使用其他客户端连接试试。
