### ISSUE TITLE
[Question] Server Error - jms_core unhealthy -> jms_mysql unhealthy

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#13341]
### Product Version

3.8.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Jumpserver Community Edition v3.8.1

### 🤔 Question Description

Jumpserver was still running smoothly yesterday
But now, I get notice "Server Error". When check on server, I can see "jms_core unhealthy"
When restart -> jms_mysql unhealthy
How can I do to fix it?

**Comment by tsukiazuma** [comment]
Update information, reason is DB - jms_mysql: ERROR 1040 (HY000): Too many connections
I will bypass with
- increase glocal max connection in docker jms_mysql: SET GLOBAL max_connections=200;
- decrease wait_timeout: SET session wait_timeout=600;

But Jumpserver reponse is very slow, check process_list in jms_sql have many jms_core.jms_net:60604   | jumpserver | Sleep
![image](https://github.com/jumpserver/jumpserver/assets/75791054/68fb8fcb-7775-4752-9bb7-31b9be2b5040)

**Comment by tsukiazuma** [comment]
CPU jms_core is very high: over 350%
![image](https://github.com/jumpserver/jumpserver/assets/75791054/f57a0223-325f-42b6-b8d7-96a655475252)

**Comment by BaiJiangJie** [comment]
Upgrade to the latest version v3.10, which fixes the problem of database connection number not being released.
