### ISSUE TITLE
[Bug] 使用rdp协议，连接带有gui的linux操作系统出现问题

### ISSUE THREAD

**Issue by suijishengchengde** [jumpserver/jumpserver#13346]
### Product Version

v3.10.10

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

centOS7.9

### 🐛 Bug Description

测试JS功能，使用RDP进行远程linux gui 过程中出现bug，情况如下：

1.如果是通过堡垒机登入，两个不同堡垒机账户登入的同一台服务器同一个账户，画面也是同步的，任意一个人操作都会影响另一个堡垒机用户；
2.上述1问题同时出现连接窗口闪烁花屏等情况。

### Recurrence Steps

两个不同账号的js用户，使用同一个资源账号去访问带有gui的linux服务器，即可复现

**Comment by BaiJiangJie** [comment]
使用原生的 RDP 客户端工具不会出现吗？

**Comment by suijishengchengde** [comment]
直接通过windows的远程访问，是正常的。

**Comment by BaiJiangJie** [comment]
可以提供一下录像吗？
