### ISSUE TITLE
[Bug] 手机端使用远程应用浏览器不兼容

### ISSUE THREAD

**Issue by abc5588** [jumpserver/jumpserver#13356]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7.9

### 🐛 缺陷描述

配置好远程应用浏览器，使用手机端登录使用，当打开远程应用google浏览器时，手机端完全无法控制鼠标，无法操作。

![微信图片_20240603224342](https://github.com/jumpserver/jumpserver/assets/155609349/5c3f51bb-598d-4d16-9ace-1570887097d2)

### 复现步骤

手机端访问远程应用浏览器即可看到问题。

### 期望结果

修复兼容手机端。

**Comment by BaiJiangJie** [comment]
是的，原生的 guacamole 服务就不支持，可以通过鼠标箭头指向右侧和下方的滚动条进行拖动。
