### ISSUE TITLE
[Bug] v3.10.7部署备机，通过备份数据库文件方式导入数据，用户登录资产时需要手动输入密码。

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#13355]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.7部署备机，通过备份数据库文件方式导入数据，用户登录资产时需要手动输入密码。

### 🐛 缺陷描述

v3.10.7部署备机，通过备份数据库文件方式导入数据，用户登录资产时需要手动输入密码。

### 复现步骤

v3.10.7部署备机，通过备份数据库文件方式导入数据，用户登录资产时需要手动输入密码。
![1](https://github.com/jumpserver/jumpserver/assets/133093482/6ed88e37-d653-497a-8cdf-2f902466c003)
![2](https://github.com/jumpserver/jumpserver/assets/133093482/b8dcce5f-5165-48dd-b821-267a587e33a9)

### 期望结果

不需要手动输入密码，自动带入。

**Comment by vipquan** [comment]
![1](https://github.com/jumpserver/jumpserver/assets/133093482/74b59614-67d5-4c5e-a42f-d02c9998f57c)
![2](https://github.com/jumpserver/jumpserver/assets/133093482/c6668afd-b9f1-4490-a2a7-a8f384914fc2)

**Comment by BaiJiangJie** [comment]
检查配置文件中的 SECRET_KEY 值和之前环境中的是否一致。
