### ISSUE TITLE
[Bug] 导出 “历史会话” 和 “命令记录” 系统会自动退出

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#13350]
### 产品版本

3.10.10

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：X86（amd）
版本：3.10.10 

### 🐛 缺陷描述

1、导出 “历史会话” 系统会自动退出
2、导出  “命令记录” 系统会自动退出

### 复现步骤

1、导出 “历史会话” 系统会自动退出
（1）第一步
![image](https://github.com/jumpserver/jumpserver/assets/43403764/b7e6894a-8183-4e9a-b52b-05f70e3d4dff)
（2）第二步：导出后点击“历史命令”或者其他功能，系统已退出
![image](https://github.com/jumpserver/jumpserver/assets/43403764/a925f146-3048-4613-8e09-1b1bce0443ba)

2、导出  “命令记录” 系统会自动退出
（1）第一步
![微信图片_20240603115909](https://github.com/jumpserver/jumpserver/assets/43403764/e6067bbb-e09e-4ba9-a442-fd93b3bd1ab5)

（2）第二步：导出历史命令，然后切换会话记录，系统自动退出
![1717387264445](https://github.com/jumpserver/jumpserver/assets/43403764/672ef3ea-2563-4317-9254-040e4f569d90)

### 期望结果

导出后保持登录状态

**Comment by BaiJiangJie** [comment]
没有复现。
