### ISSUE TITLE
[Bug] 用户登录报错：登录超时，请重新登录 | Login timeout, please try again.

### ISSUE THREAD

**Issue by kk545141** [jumpserver/jumpserver#13352]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos 7.6
mysql 8.4
redis 7.2.4
jms 3.10.10

### 🐛 缺陷描述

v3.10系列版本中测试发现，用户登录页面可能存在超时而无法登录的现象，猜测该现象与浏览器session缓存有关。
当用户请求登录，正好处于session过期时，登录就会报超时。此时，只有将域名或IP地址后的“/core/auth/login/”后缀去掉，并回车刷新页面才会正常获取到新的session，而成功登录。

### 复现步骤

后台将session超时时间设短（如1分钟），在退出后的登录页面等待一分钟之后，再输入账户密码进行登录，就会出现登录超时报错现象。强制刷新页面后，可以正常登录。

### 期望结果

用户在点击登录按钮时，应同步刷新session，避免session过期导致的无法登录问题。

**Comment by BaiJiangJie** [comment]
### 报错提示
```Login timeout, please try again.```
```登录超时，请重新登录```

### 报错情况
配置文件的配置选项分别在两种情况下会出现:
1. SESSION_COOKIE_AGE <= 30s
2. SESSION_EXPIRE_AT_BROWSER_CLOSE = true

### 报错原因
报错的原因是当用户打开登录页面后，后端服务会调用 session.set_test_cookie 设置测试 Cookie，如果在当前用户的 session 过期后才提交登录信息，那么就会导致 session.test_cookie_worked 测试 Cookie 的逻辑失败，进而返回报错信息。

为了解决报错的问题
在之前的版本中登录页面增加有一个定时请求 `/api/health/` 的接口，意味着每 30s 会定时给 session 进行续期，但是只有当 SESSION_EXPIRE_AT_BROWSER_CLOSE=false 的时候生效。

### 解决方案
所以如果想要不报错，需要设置 SESSION_COOKIE_AGE>30s 并且 SESSION_EXPIRE_AT_BROWSER_CLOSE=false（默认）。

### 其他问题
如果系统要求，必须设置 SESSION_EXPIRE_AT_BROWSER_CLOSE=true，那么在 <= v3.10.10 的版本中出现报错后，用户使用快捷键 `Ctrl+R / ⌘+R` 刷新浏览器重新提交还会报同样的错误，这就要求用户必须将鼠标聚焦到浏览器 URL 地址栏并按下回车，刷新页面后再次提交表单才会登录成功。

针对这个问题我们将会在 v3.10.11 版本中进行修复。

**Comment by kk545141** [comment]
当前出现该问题，确实属于其中之一。感谢支持~
