### ISSUE TITLE
[ldap是否支持ldaps协议] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13365]
### 产品版本

v3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

我们会重新部署新域控，启用LDAPS办议，堡垒机对接ldap时，是否支持ldaps协议，如不支持，预计哪个版本支持？

### 解决方案

堡垒机对接ldap支持ldaps协议

**Comment by BaiJiangJie** [comment]
支持。配置 LDAP 地址时使用 ldaps://
