### ISSUE TITLE
[Question] 导入用户列表如何配置密码

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#13369]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [x] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.7

### 🤔 问题描述

遇到一个问题，当批量导入用户列表的时候，用户的初始密码是什么？

然后又遇到了第二个问题，想把所有导入的用户批量改一个初始密码，没有配置密码的参数

那么在导入的时候如何配置密码，导入的用户该怎么登录？

### 期望结果

批量修改用户密码

**Comment by BaiJiangJie** [comment]
下载用户导入模版后，修改 `密码策略` 字段的值为 `custom`，代表密码要手动输入（自定义）。
> 默认是用户创建成功后会给用户发送邮件，用户通过邮件链接设置自己的密码。

设置 `密码策略` 为 `custom` 后，设置 `密码` 字段，即用户的密码。

导入成功后，就可以正常使用设置的密码登录了。

**Comment by BaiJiangJie** [comment]
[user_2024-06-05_15-04-28.xlsx](https://github.com/user-attachments/files/15575820/user_2024-06-05_15-04-28.xlsx)
