### ISSUE TITLE
[Question] sz 命令下载卡住100%

### ISSUE THREAD

**Issue by msxiehui** [jumpserver/jumpserver#13366]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

阿里云ECS
CentOS 7.9 64位
配置：2核8G
下载过程中，内存和CPU没有太大波动

### 🤔 问题描述

使用sz 下载文件时，卡到100% 无法继续，web端、mac iterm2 ,均是如此。
卡一会后，显示 00  然后命令行恢复，但是文件没有下载。

<img width="528" alt="image" src="https://github.com/jumpserver/jumpserver/assets/5189018/eec93d64-7271-481b-875d-c0ac8f4807d3">

<img width="567" alt="image" src="https://github.com/jumpserver/jumpserver/assets/5189018/72b57304-79b0-4d81-b75f-72912f74e283">

### 服务器直连下载是正常的。

![image](https://github.com/jumpserver/jumpserver/assets/5189018/b626f123-7f18-4505-8b9e-a47cbcce3bc1)

![image](https://github.com/jumpserver/jumpserver/assets/5189018/2d478b1c-2a72-45a4-900c-64e74e264e8b)
![image](https://github.com/jumpserver/jumpserver/assets/5189018/5c990b7e-2cdc-4155-ad4d-580cfdce4b9a)

以前使用 2.X 版本的时候还是正常的。后来升级v3 之后就不好用了。
开始以为是vpn的问题，今天单独开了一台服务器，开通外网，依然不好使

### 期望结果

期望能够使用 rz sz 进行正常上传下载小文件，大文件使用 sftp。

**Comment by BaiJiangJie** [comment]
下载文件卡住的情况，文件多大？正常小文件应该是没问题的。

也是建议小文件（< 500M）使用 rz、sz，大文件使用 SFTP。

**Comment by msxiehui** [comment]
图片测试 4.2M ，文件是 724k,都是小文件。

我新起服务器，全新安装也不行。
 一台mac  一台 win10 做客户端测试都不行，
 浏览器用 edge和chrome也不行。
 已经进入自我怀疑状态。。。

**Comment by BaiJiangJie** [comment]
不用怀疑，现在 rz、sz 命令使用起来确实不是很稳定，有些用户可以下载 40M 左右的文件，有些 1k 的文件也会卡住，目前还没有找到原因。

找到问题和解决方案，后面版本会持续优化的。

**Comment by msxiehui** [comment]
好的，希望能尽快解决，小文件用 rz,sz 还是很方便的。
