### ISSUE TITLE
[Question] What do we need to do to enable RDP to a MS Windows desktop

### ISSUE THREAD

**Issue by cookiemonsteruk** [jumpserver/jumpserver#13368]
### Product Version

v3.10.7

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Hello. I am still testing and have been able to install jumpserver from the offline method I believe.
Jumpserver is running on an Ubuntu server 22.04.4 LTS on the same network segment.

### 🤔 Question Description

I can ssh to linux machines but when I try to connect to a Microsoft Windows 10 machine on the same LAN, I get the message:
"Connect Error
The remote desktop server does not appear to exist, or cannot be reached over the network."
The machine is switched on, remote connections have been enabled to it from the windows settings and I am connecting with a user account that is member of the administrator group. There are no domain controllers, is a standalone environment.
I don't read Chinese and that makes it possible I have missed some instructions.
Could I have assistance as to what I need to check please.

**Comment by BaiJiangJie** [comment]
You need to check the log of the Lion component, and the filename is `lion.log`.

Alternatively, you can try connecting using another native client to see if it can connect successfully?

**Comment by cookiemonsteruk** [comment]
thanks for this. I am struggling to find any logs. I must have missed a setting when installing it and I've been looking around in places to find where the setting might need to be set. I think I used the offline installer after a previous attempt failed to set the network correctly.
```
root@bastion-1:/home/penguin/Dockerfile# tree
.
├── allinone
│   ├── docker-compose.yml
│   ├── Dockerfile
│   ├── entrypoint.sh
│   ├── nginx.conf
│   ├── README.md
│   ├── readme.txt
│   └── supervisord.conf
├── chen
│   ├── Dockerfile
│   └── entrypoint.sh
├── config_example.conf
├── core
│   └── Dockerfile
├── docker-compose-build.yml
├── docker-compose-init-db.yml
├── docker-compose-mariadb.yml
├── docker-compose-network.yml
├── docker-compose-redis.yml
├── docker-compose.yml
├── kael
│   ├── Dockerfile
│   └── entrypoint.sh
├── koko
│   ├── Dockerfile
│   └── entrypoint.sh
├── LICENSE
├── lion
│   ├── Dockerfile
│   ├── entrypoint.sh
│   └── supervisord.conf
├── magnus
│   ├── Dockerfile
│   └── entrypoint.sh
├── README.md
└── web
    ├── Dockerfile
    ├── entrypoint.sh
    └── nginx.conf

8 directories, 31 files
```
Pointer where the setting for logging could be from my tree?
Meantime yes, great suggestion, to check other methods too. Thanks.

**Comment by BaiJiangJie** [comment]
Are you installing an All-in-One? 

'lion.log' was not found in the tree directory.

I recommend using offline packages for deployment.

[Download here.](https://community.fit2cloud.com/#/products/jumpserver/downloads)

**Comment by BaiJiangJie** [comment]
In this [issue](https://github.com/jumpserver/jumpserver/issues/12973), because you asked about the All-in-One version, the following solutions are all based on this version.

For short-term experience, we recommend using the All-in-One version because it can be installed and deployed faster. However, if you plan to use it for a long time, we strongly recommend using the offline installation package deployment method for installation and deployment. This is the link: 
https://community.fit2cloud.com/#/download/jumpserver/v3-10-10-lts

In addition, back to the current issue itself, if you don’t see the `lion.log` file in the current directory, search it globally in the root directory `/`.

**Comment by BaiJiangJie** [comment]
All-in-One should not have a separate lion.log file, so you should use the docker logs command to view the container's logs.

**Comment by cookiemonsteruk** [comment]
very helpful, thank you. Last question, how do I remove the current installation of all-in-one so I can then install the suggested offline?

**Comment by BaiJiangJie** [comment]
It's very simple, just follow the steps below to get it done.
1. Back up the current database
2. Back up the current configuration file (especially the SECRET_KEY configuration item)
3. Download the same version of JumpServer offline installation package as All-in-One
4. Put the configuration file in the latest offline installation package and start the service directly.

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/installation/setup_linux_standalone/offline_install/

You can refer to this offline installation document, but currently there is only a Chinese version. You can translate it using some translation software and read it. We will release an English version of the document later.

**Comment by cookiemonsteruk** [comment]
hi. I tried to download from that link https://community.fit2cloud.com/#/download/jumpserver/v3-10-10-lts but for 3.10.7 but it requires a telephone number and code. I entered my number in international format i.e. +countrycode number and I get a "malformed number" error. Is it only available in CN ?

**Comment by BaiJiangJie** [comment]
What country's area code are you in? Currently supported countries include the following:
<img width="199" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/da35231a-c693-4d45-94b4-c161959ffb34">

**Comment by cookiemonsteruk** [comment]
+44 Great Britain. Do I need to do something e specific?

**Comment by BaiJiangJie** [comment]
I have tested that my Britain mobile phone number can be submitted successfully.

How many digits are there in your cell phone number? Mine is ten.

**Comment by cookiemonsteruk** [comment]
yes my UK mobile number has 11 digits with the leading zero. Landlines also all begin with a zero. 
Normally when entering UK numbers, either mobile or landlines, preceded by the country code 44 we remove the leading zero, therefore the number becomes a +44-no zero-10 digits.
I'm going to try again when I get home. Thanks for sticking with me.

**Comment by BaiJiangJie** [comment]
You're welcome. I guess you can submit it after you drop the 0.

**Comment by cookiemonsteruk** [comment]
I don't know what could I be doing wrong. All cases give me "malformed number:
+4409999999999
+449999999999
+44 09999999999
+44 9999999999

4409999999999
449999999999
44 09999999999
44 9999999999
In every case I tick the accept terms and conditions. The response is always 手机号格式错误
Anything else I suggest I check? Do I need to have signed up to something else first? I have used two mobile (cell) numbers.

**Comment by BaiJiangJie** [comment]
Show me the screenshots.

**Comment by BaiJiangJie** [comment]
+449999999999 is invalid, you can try +4477777777.

**Comment by BaiJiangJie** [comment]
<img width="452" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/6aa43c32-c11c-4c8b-8683-a54dcf600c95">
It's okay for me to try this.

**Comment by cookiemonsteruk** [comment]
> +449999999999 is invalid, you can try +4477777777.

Of course. I was using all 9s to mask my actual numbers. I'll show the screenshots.

**Comment by BaiJiangJie** [comment]
Oh, no, I forgot, this community site only allows Chinese mobile number login.

**Comment by BaiJiangJie** [comment]
It is also possible to use an online script instead of an offline package.

`curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash`

The latest version of v3.10.10 is installed in this way.

**Comment by BaiJiangJie** [comment]
<img width="1365" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/3de95f50-9c2d-4146-88c6-c7f0852c41fe">

**Comment by cookiemonsteruk** [comment]
Ok thanks for all this help. I have found the logs in /data/jumpserver/ and will need to check there for this original problem.
One final question on this thread: am I right then in thinking that as per earlier the methods to install are:
- all-in-one is for short term or testing.
- for permanent use we should use quick start method curling the desired version from github as per your screenshot; and this method to download is an alternative to downloading an installer from fit2cloud but are the same thing.

**Comment by BaiJiangJie** [comment]
Yes, you understand the installation method correctly.

Back to the original question, if Windows 10 cannot connect, check the Lion log `lion.log`.

**Comment by cookiemonsteruk** [comment]
thanks. Closing.
