### ISSUE TITLE
Windows资产不输入密码只用账号去连接

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13374]
### 产品版本

V3.10.9

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

授权用户Windows机器并授权手动账号，期望可以不输入密码，连接到锁屏输入密码页面
![image](https://github.com/jumpserver/jumpserver/assets/136306850/3806b827-eaf8-4d3d-8502-63f6bc0ab2b4)
因为是个人前置机，出于管理要求使用习惯，这种类型的机器都是不托管密码的

### 解决方案

期望可以不输入密码，连接到锁屏输入密码页面
![a3d66827-d1b2-4787-bd22-e4d3cd9186d1](https://github.com/jumpserver/jumpserver/assets/136306850/d89d55a1-cd0f-4608-ac8e-b21d6dfb8fc1)

**Comment by BaiJiangJie** [comment]
授权手动登录的账号，需要在Luna页面连接资产时，在JumpServer的账号密码弹框中输入用户名和密码。
如果不在这一层强制要求的话，会绕过 ACL 规则。
所以目前版本是不能在 Windows 锁屏界面登录的。
