### ISSUE TITLE
[Bug] 资产列表内，展示字段配置了“硬件信息”，但是有的机器获取不到

### ISSUE THREAD

**Issue by cui369680775** [jumpserver/jumpserver#13377]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机部署

### 🐛 缺陷描述

1、自定义字段勾选了 “硬件信息”后，页面刷新，有的机器能够获取到硬件信息并展示，有的显示“-”，信息获取不到
      机器是相同配置，确认可链接，系统版本相同，可正常ssh，系统平台选项都是一个，确认开启了信息采集

### 复现步骤

自定义字段勾选了 “硬件信息”后，页面刷新，有的机器能够获取到硬件信息并展示，有的显示“-”，信息获取不到

**Comment by BaiJiangJie** [comment]
点击 `-` 看一下是不是已经获取回来来，只是没有展示出来。

**Comment by cui369680775** [comment]
> 点击 `-` 看一下是不是已经获取回来来，只是没有展示出来。

两种情况，一种是数据有，但是没有展示出来，一种是没有获取到数据

**Comment by BaiJiangJie** [comment]
没有展示出来的情况是已知问题，v4 版本修复。

没有获取到数据的情况，手动更新一下。

**Comment by cui369680775** [comment]
好的



***@***.***
 
发件人： Bryan
发送时间： 2024-06-06 17:09
收件人： jumpserver/jumpserver
抄送： cui369680775; Author
主题： Re: [jumpserver/jumpserver] [Bug] 资产列表内，展示字段配置了“硬件信息”，但是有的机器获取不到 (Issue #13377)
没有展示出来的情况是已知问题，v4 版本修复。
没有获取到数据的情况，手动更新一下。
