### ISSUE TITLE
在web端使用ssh 方式连接资产会不会考虑对复制粘贴进行权限设置？

### ISSUE THREAD

**Issue by Lee-Z** [jumpserver/jumpserver#13372]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

目前rdp和vnc是支持，对内容复制和粘贴进行限制。

### 解决方案

如果是由于ssh连接资产时能调用本地的ssh连接软件的话，造成不能对ssh方式进行复制、粘贴权限设置的话。
那能不能对ssh能否调用本地连接ssh工具进行权限限制。这样是不是就能设置ssh的连接方式只能在web端进行连接，这样是不是对浏览器进行复制、粘贴限制就行？
如果不是该原因请大概描述下原因及后续是否支持对ssh连接资产方式进行复制、粘贴权限限制。

**Comment by BaiJiangJie** [comment]
通过 ssh 协议连接资产的几种方式：Web CLI、本地客户端，都是支持控制是否启用的。

但是，使用 Web CLI 方式连接资产时的复制、粘贴权限是控制不了的。
KoKo 组件使用的 canvas 进行实现的，不支持控制。
