### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by leipore** [jumpserver/jumpserver#13379]
### Product Version

 Version v2.23.4 GPLv2. Copyright - FIT2CLOUD 飞致云 © 2014-2024

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

k8s

### 🐛 Bug Description

无法离线回放
![1717661610030](https://github.com/jumpserver/jumpserver/assets/17704595/fba9a28f-120a-4359-9bef-bf1eec78bb63)

### Recurrence Steps

未知情况

**Comment by BaiJiangJie** [comment]
升级到最新版本使用，之前版本可能会有录像上传不成功无法播放的问题。
