### ISSUE TITLE
[Bug]  资产列表内，点击资产树不同的节点，展示数据的页面内的“自定义列表字段”内，有时候有“硬件信息”，有时候没有

### ISSUE THREAD

**Issue by cui369680775** [jumpserver/jumpserver#13376]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机部署

### 🐛 缺陷描述

资产列表内，点击资产树不同的节点，展示数据的页面内的“自定义列表字段”内，有时候有“硬件信息”，有时候没有

### 复现步骤

资产列表内，点击资产树不同的节点，展示数据的页面内的“自定义列表字段”内，有时候有“硬件信息”，有时候没有

**Comment by BaiJiangJie** [comment]
`硬件信息` 的字段列，只有主机页面中会显示，其他页面，如：所有、数据库、网络设备等都没有这个信息。
