### ISSUE TITLE
[Bug] 通过 DB 向导使用客户端通过 Magnus 连接 Oracle 数据库查看 SQL 执行计划报错

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13375]
### 产品版本

3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

版本是V3.10.10

### 🐛 缺陷描述

通过db连接向导信息客户端连接，查看sql 执行计划报错
![企业微信截图_17175770136952](https://github.com/jumpserver/jumpserver/assets/136306850/c2fddeb3-bc8a-4d45-8b28-3cf06453651f)
通过DB向导的命令行是正常的，使用本地客户端直连也是正常的

### 复现步骤

DB向导生成连接信息，本地客户端通过向导连接，F5查看SQL执行计划

### 期望结果

期望可以正常查看

**Comment by BaiJiangJie** [comment]
Bug 的描述信息太少。

1. 什么类型的数据库？
2. 使用的什么客户端，版本是多少？
3. 使用的什么版本的数据库？
4. Magnus 组件的日志是什么？

**Comment by 1223ruiyin** [comment]
> Bug 的描述信息太少。
> 
> 1. 什么类型的数据库？
> 2. 使用的什么客户端，版本是多少？
> 3. 使用的什么版本的数据库？
> 4. Magnus 组件的日志是什么？

1. 数据库类型及版本oracle 11.2.04
2. 客户端 PL/SQL Developer  Version 11.0.4.1788  (64 bit)
3.  Magnus日志如下
<img width="542" alt="0fa9fe443146a9c72b7bd29d220c388" src="https://github.com/jumpserver/jumpserver/assets/136306850/fcb974cd-0033-4372-b6b5-4c23b279795e">
4. jumpserver.log如下
<img width="869" alt="3e94a1e0422d1ea6e9615a3dbbe7dd6" src="https://github.com/jumpserver/jumpserver/assets/136306850/e2695be0-178d-4089-8f1d-af544e14d964">

**Comment by BaiJiangJie** [comment]
问题不好处理，v4+ 之后调研一下。

**Comment by BaiJiangJie** [comment]
升级到 v3.10.13 试试。
