### ISSUE TITLE
smtp用户名不可设置为空

### ISSUE THREAD

**Issue by guanbear** [jumpserver/jumpserver#1338]
[简述你的问题]

##### 使用版本
1.3.0

##### 问题复现步骤
内网 smtp 代理服务器，对内网ip不校验用户名，但是在smtp设置里面必须设置用户名，导致django 报错 ‘SMTP AUTH extension not supported by server’

很多开源系统都是允许smtp空用户名的，希望jumpserver也修改下

解决方案，修改 apps/common/forms.py 在 EMAIL_HOST_USER 相关位置添加 required=False

如果数据库里已经有相关配置，删除了就好。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
请测试一段时间，如果没有问题请提交一个 pull request

**Comment by ibuler** [comment]
请测试一段时间，如果没有问题请提交一个 pull request
