### ISSUE TITLE
[Question] CPU 波动问题

### ISSUE THREAD

**Issue by Zubenxing** [jumpserver/jumpserver#13387]
### 产品版本

v3.9.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7.9 docker部署的jumpserver  还有使用了 k3s 部署的awx 

### 🤔 问题描述

我们的core组件的CPU 不稳定 且通过 /date/jumpserver/core/date/log/jumpserver.log 有一些数据库报错  如2024-06-06 10:26:42 [decorators ERROR] delay run error: (2006, 'MySQL server has gone away') （只是有时候） 然后就是core组件的cpu不稳定
![微信图片_20240607142846](https://github.com/jumpserver/jumpserver/assets/133339362/aa40eb36-9eff-4124-a66a-da60d71d3bb7)

### 期望结果

我希望知道这是怎么回事 以及需要做什么调整

**Comment by BaiJiangJie** [comment]
不用调整，正常波动，可能有一些定时任务或者异步任务再执行。

对于 `(2006, 'MySQL server has gone away')` 的情况，`SHOW VARIABLES LIKE 'wait_timeout';` `wait_timeout` 的值调大一些。

**Comment by BaiJiangJie** [comment]
由于长时间未回复，暂时关闭当前 issue，如果有任何问题请重新打开。
