### ISSUE TITLE
[Feature] windows资产客户端访问提供“连接向导”功能。

### ISSUE THREAD

**Issue by Linkjie-11** [jumpserver/jumpserver#13382]
### 产品版本

V3

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

用户场景为 非运维人员访问桌面资产，但不想总登录jms，再进行连接，有时候用户外出需要临时操作，目前的移动端适配web页面打开windows基本无法操作，移动端场景也可使用rdp文件，选择RDP客户端打开。但RDP文件只能使用一次，如果需要再次连接需要重新生成文件。

### 解决方案

提供类似DB连接向导，ssh连接向导方式，生成临时账号密码，由用户自行在rdp客户端内输入进行连接。

移动端场景也可使用rdp文件，选择RDP客户端打开。是否可以优化由浏览器直接拉起microsoft-remote客户端。

### 补充信息

如果使用连接向导，pc端和移动端都可以由用户手动输入进行连接。

**Comment by BaiJiangJie** [comment]
Windows 资产的 DB 向导方式在 >= [v3.10.8](https://github.com/jumpserver/jumpserver/releases/tag/v3.10.8) 中已经支持。

<img width="1211" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/88d98177-b409-4753-b380-635ee3fe13b9">
