### ISSUE TITLE
[Bug] 删除节点后命令过滤中节点不会消失会留下原id

### ISSUE THREAD

**Issue by Evo555** [jumpserver/jumpserver#13390]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

标准环境

### 🐛 缺陷描述

删除节点后命令过滤中节点不会消失会留下原id

### 复现步骤

1.创建节点
2.创建命令过滤并以属性筛选中的节点为筛选属性，选择创建的节点为属性值
3.删除节点
4.查看命令过滤中的详细内容

### 期望结果

属性值应为空

### 补充信息

手动删除可以解决，另外，用户反馈可能导致用此命令过滤的资产之后再连接资产会导致资产连接失败，用户认为可能是一个资产多个节点导致的，本地未复现，跟进一周未得到用户其他反馈，疑似bug

**Comment by BaiJiangJie** [comment]
节点删除后命令过滤规则中的资产节点字段会存在原始的 UUID（暂不优化），之前版本连接资产时会报错，在 v3.10.8-lts 版本中已修复。

确认你提交的版本是不是准确。
