### ISSUE TITLE
[Question] 如何查询远程桌面调用记录

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#13392]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

normal

### 🤔 问题描述

远程发布机有多台，有很多网页调用，想知道  是哪个用户的哪个账号从哪个ip，调用了哪台远程发布机
请问下可以在哪里查询

**Comment by BaiJiangJie** [comment]
在`在线/离线会话`中可以看到 `用户-账号-登录IP`，目前版本看不了远程发布机。

**Comment by BaiJiangJie** [comment]
/
