### ISSUE TITLE
[Bug] 无法访问云上服务器 ssh: handshake failed

### ISSUE THREAD

**Issue by la-cat** [jumpserver/jumpserver#13391]
### Product Version

v3.10.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jump 在内网，同时有云上（阿里、华为）服务器以及本地服务器

### 🐛 Bug Description

在jump通过密钥或密码方式无法连接服务器。
不使用jump ，通过ssh -i 或者密码，可以进行连接。
内网服务器则可以正常使用。
![SCR-20240611-jnxl](https://github.com/jumpserver/jumpserver/assets/37959871/e36b9837-0af3-415c-99fa-7a478d6dd02b)

### Recurrence Steps

新装jump，添加云山服务器，使用密码或者密钥连接测试。

**Comment by BaiJiangJie** [comment]
是不是云服务器的防火墙问题，在 koko 容器 ssh 连接一下资产试试。

**Comment by la-cat** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/37959871/f0b1f36f-a4a5-41eb-add8-0e069f658c48)

上面是在koko上连接

**Comment by la-cat** [comment]
我又在容器koko内多次尝试，然后出现有时不能，有时可以
![image](https://github.com/jumpserver/jumpserver/assets/37959871/c30bec89-8773-4c30-a32f-d235816c9540)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10066
https://help.aliyun.com/noticelist/articleid/1060784724.html?spm=0.2020520154.sas.34.1f88CZChCZCh6i

看看是不是跟这个问题一样，是云服务商的云防火墙安全防护开启了。

**Comment by BaiJiangJie** [comment]
咨询一下服务商的安全策略。

**Comment by BaiJiangJie** [comment]
由于长时间未回复，暂时关闭当前 issue，如果有任何问题请重新打开。
