### ISSUE TITLE
[Bug] Web 终端中，使用客户端连接 ssh/sftp 资产时，会使用硬编码的 2222 端口，而非 koko 配置的 sshd 端口

### ISSUE THREAD

**Issue by Fallen-Breath** [jumpserver/jumpserver#13399]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

使用 https://github.com/jumpserver/installer 部署的 v3.10.10 社区版

koko 的 sshd 端口被设置为了 11122，而非默认的 2222

![image](https://github.com/jumpserver/jumpserver/assets/28978806/dd0df60c-72d5-4d63-9988-726b8f65be2b)

浏览器为 Microsoft Edge 125.0.2535.92 (正式版本) (64 位)

### 🐛 缺陷描述

下面的 issue 描述以 sftp 协议作为例子，因为 filezilla 客户端比较好展示信息。ssh 协议也有一样的问题

web 终端连接资产时，可选择使用客户端连接。选择 sftp

![image](https://github.com/jumpserver/jumpserver/assets/28978806/ddfbc96b-d378-48ad-8ba4-cf4bc2322f41)

![image](https://github.com/jumpserver/jumpserver/assets/28978806/1c2bfec1-f06a-4b47-9d57-b30646c5daf7)

点击连接按钮后，会借助 jumpserver 客户端，打开一个 sftp 客户端（这里配置为 filezilla）来连接该资产

![image](https://github.com/jumpserver/jumpserver/assets/28978806/6cd16488-5c0c-41f3-a79c-fb9cc56a5cc1)

此时，filezilla 客户端会使用默认的 2222 端口进行 sftp 连接。由于 koko 的配置的 sshd 端口并非 2222（见环境信息），sftp 连接会失败

![image](https://github.com/jumpserver/jumpserver/assets/28978806/b24ca457-10cb-4bbc-a608-dd4ae40ca449)

### 复现步骤

见上文“缺陷描述”

### 期望结果

启用的 filezilla 客户端将使用我自定义配置的 11122 端口，而非 2222 端口，来通过 jumpserver 来连接所选择的资产

### 补充信息

在 Web 终端里，选择使用 jumpserver 客户端来连接资产时，使用了一个 `jms://` 开头的 url 来启动 jumpserver，这个 url 是一个 base64 编码的 json，存着这次资产连接操作的相关信息

![image](https://github.com/jumpserver/jumpserver/assets/28978806/3dadf708-2fe5-4ac6-9cff-939c73353afe)

可以发现，里面有一个 endpoint 字段，其 port 值正是 2222

尝试修改这个 port 的值为 11122，编码回 base64，再然后拼回 `jms://` url，用浏览器打开，启动 jumpserver 客户端，可发现 filezilla 正确地使用了 11122 端口建立连接（注意，该操作有时效性，等太久的话 token 会过期）

![image](https://github.com/jumpserver/jumpserver/assets/28978806/596969af-6c06-4d9c-b2c1-b284a0a44312)

即可确定是这个 url 的数据取值不对的问题

----

进一步定位这个 url 的来源，可发现它是通过 `/api/v1/authentication/connection-token/${token.id}/client-url/` 接口拉取的

https://github.com/jumpserver/luna/blob/8950b49435efc5b426ec70cd37ae5474f8052b17/src/app/services/http.ts#L307-L308C26

定位相关代码，可发现 json 里的 endpoint 是从 db 里捞出来的，数据源是 `Endpoint` 这个 model，且其 ssh_port 的默认值是写死的 2222：

https://github.com/jumpserver/jumpserver/blob/7ad4d9116ae1db53c35e1e8c882ecc1b30da0899/apps/terminal/models/component/endpoint.py#L11-L17

进 jms_mysql 里看了下 db 里的里相关表的取值，确认里面的 ssh_port 确实是 2222

![image](https://github.com/jumpserver/jumpserver/assets/28978806/99456217-d663-4f64-a90f-9de388134756)

### 尝试过的解决方案

进 jms_mysql 容器，改 jumpserver 数据库的 terminal_endpoint 表中，ssh_port 的取值。从默认的 2222 改成连接 koko 的期望端口，可解决此问题

![image](https://github.com/jumpserver/jumpserver/assets/28978806/8e63b0d0-1b31-46f5-b073-35d3fa9fd882)

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/guide/system/component/?h=%E7%AB%AF%E7%82%B9#5

系统设置-组件设置-服务端点里就可以修改。不用手动去改数据库。

**Comment by Fallen-Breath** [comment]
了解了，感谢
