### ISSUE TITLE
[Feature] 平台列表可以统计各个平台的资产数

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13404]
### 产品版本

3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

期望平台列表这里可以加一个字段，统计各个平台的资产数量
![image](https://github.com/jumpserver/jumpserver/assets/136306850/234cec88-60a3-4910-aa77-bb4ac41a31b5)

### 解决方案

添加一个字段统计属于对应平台的资产数量

**Comment by BaiJiangJie** [comment]
v4+.

**Comment by w940853815** [comment]
https://github.com/jumpserver/jumpserver/pull/13804
https://github.com/jumpserver/lina/pull/4260
已实现

**Comment by jym503558564** [comment]
v4.1.0， 平台列表支持统计各个平台的资产数，请升级进行体验。
