### ISSUE TITLE
交换机命令过滤tab补全不生效

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13408]
### 产品版本

3.7.1

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

交换机：huawei ce68
堡垒机版本：3.7.1

### 🐛 缺陷描述

在huawei ce68交换机上审批命令时，直接输入是可以审批的，但是如果用tab键补全命令的话，不会触发审批

### 复现步骤

linux上的tab补全没问题，可以触发，交换机上正常输入命令可以触发，tab补全不能触发
![c6df0464afaaec9f93daa722bd995443_](https://github.com/jumpserver/jumpserver/assets/136306850/13cb09cf-380a-421e-ac6f-3aa29d04e4df)

**Comment by BaiJiangJie** [comment]
是的，目前命令过滤匹配逻辑有缺陷，技术突破比较困难。

**Comment by 1223ruiyin** [comment]
不是所有的交换机不生效的，部分交换机这样的场景下命令过滤是可以的，会不会是某些交换机存在的特性决定的

**Comment by BaiJiangJie** [comment]
核心原因就是命令解析的不够完整，可能不会是最终执行的命令。
