### ISSUE TITLE
[Bug] 创建用户密码策略为设置密码时同样会发生邮件给用户重置密码

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#13409]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [x] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

常规环境

### 🐛 缺陷描述

![image](https://github.com/jumpserver/jumpserver/assets/102132588/1f161dae-c5bb-4be8-ba96-c376ae3b0ed8)
![image](https://github.com/jumpserver/jumpserver/assets/102132588/8e9dde5d-52b8-4714-8f8a-355a33586f7e)
![image](https://github.com/jumpserver/jumpserver/assets/102132588/13a4033f-2d8b-42c6-866c-a192ccbb8c51)
![image](https://github.com/jumpserver/jumpserver/assets/102132588/0a10d77a-d04b-42ac-95aa-30b798aedc26)
users_users这个接口创建用户的时候选 设置密码 也发送重置密码邮件了

### 复现步骤

打开浏览器开发者模式，查看网络，创建一个用户，发现response的密码策略返回的是email,并且有发送邮件到用户邮箱中

### 期望结果

应返回
  "password_strategy": {
    "value": "custom",
    "label": "设置密码"
  },

### 补充信息

创建出来的用户可以使用设置的密码登录，不为预期的发送了email给用户邮箱，如果是策略如此，期望加上提示以说明

**Comment by BaiJiangJie** [comment]
1. 无论密码策略选择邮件或是设置密码，邮件都会发送，这个邮件是用户创建成功的通知邮件，只不过附带了重置密码链接。
2. 密码策略的区别在于，使用设置密码策略，用户创建成功后可以直接使用管理员设置的密码登录；而使用邮件策略，用户必须通过邮件中的重置链接设置密码后才能登录。

上面 API 的 Response 中密码策略为 email 是因为这是这个字段的默认值，只要看提交的正确的就可以。

**Comment by BaiJiangJie** [comment]
v4+ 后考虑增加提示说明。

**Comment by BaiJiangJie** [comment]
v4.0.0 已修改。
