### ISSUE TITLE
推送用户，发现用户的id不正确，家目录权限错误

### ISSUE THREAD

**Issue by nineaiyu** [jumpserver/jumpserver#1341]
[简述你的问题]

##### 问题复现步骤
1. 推送新用户
2. 新推送的用户，家目录权限异常，多次遇到

#####

![default](https://user-images.githubusercontent.com/19207867/40226624-bf5de6c6-5abe-11e8-9df9-b94a6945c95e.png)

##### 

[注:] 完成后请关闭 issue

**Comment by jimingsong** [comment]
我也遇到。和老广确认有这个问题。

**Comment by ibuler** [comment]
#1381

**Comment by ibuler** [comment]
使用ansible 推送的，不知道为何会出现这个问题，如果还存在这个问题，麻烦看看是否能复现

**Comment by Lunatictwo** [comment]
@ibuler 如何解决？

**Comment by gangh** [comment]
@ibuler  @jimingsong  @nineaiyu

**Comment by gangh** [comment]
@ibuler @jimingsong @nineaiyu @ibuler 
这一错误在当前版本( 1.4.6-2 GPL) 中仍未解决
https://github.com/jumpserver/jumpserver/blob/master/apps/assets/tasks.py#L360


在该 /home/{user_name} 目录已存在时会修改已有此目录的权限,导致对该目录下文件进行读写的服务出错
为什么在这个地方这样设计,对已有目录进行权限编辑挺奇怪的?这个地方有计划修改么  @ibuler

**Comment by ibuler** [comment]
已处理
