### ISSUE TITLE
连接远程应用浏览器时，希望将右边设置按钮隐藏

### ISSUE THREAD

**Issue by abc5588** [jumpserver/jumpserver#13417]
### Product Version

V3.10.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

连接远程应用浏览器时，希望将右边（如图）的设置按钮隐藏，或者将它移动导航栏上。因为在操作网页时，这个按钮很碍事。

![微信图片_20240613144725](https://github.com/jumpserver/jumpserver/assets/155609349/59bc031d-54bb-4e11-98aa-e5c7a595fa16)

1. 

### Proposed Solution

希望下个版本更新时，这个按钮已经去掉。功能设置放到导航栏上。

![111](https://github.com/jumpserver/jumpserver/assets/155609349/65c3cb51-3d22-4e29-b49d-049cd2521b15)

**Comment by BaiJiangJie** [comment]
暂不考虑。

**Comment by abc5588** [comment]
应在按钮上加一个“隐藏”选项，让用户选择隐藏还是显示。
