### ISSUE TITLE
怎么设置用户显示的服务器列表

### ISSUE THREAD

**Issue by dongbozhou** [jumpserver/jumpserver#1342]
版本：
Version 1.2.1-2 GPLv2.

求教，用户登录到跳板机后，按“p”显示的是他有权限的机器列表，但是有时候想要显示的是他最关心的一些机器，而不是整个有权限的机器列表，比如我对1000台机器有权限，但我常操作但是其中10台，有没有一种方式只显示这10台

**Comment by kemenkai** [comment]
之给他授权10台不久好了吗

**Comment by ibuler** [comment]
是个不错的功能，可以显示最近登录的几台

**Comment by jym503558564** [comment]
现可搜索资产，可以解决这个问题。
