### ISSUE TITLE
申请临时授权后，在资产列表，授权用户，显示有bug，实际已过期，但外面显示有效；

### ISSUE THREAD

**Issue by shaohuayangfit2** [jumpserver/jumpserver#13422]
### 产品版本

v3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

https://js-internal.fit2cloud.com/

### 🐛 缺陷描述

![1](https://github.com/jumpserver/jumpserver/assets/47516608/c0fbefd5-33a1-41cf-91a3-b3693bf5fb9c)
![2](https://github.com/jumpserver/jumpserver/assets/47516608/2515ca16-4d55-4fae-ada8-80b37fb7a4c5)

### 复现步骤

1，去掉该用户链接资产权限；
2，提交工单，申请该资产的临时权限；
3，权限到期后，点击资产详情，授权用户显示有效，但是点击查看授权，其实授权已经过期

### 期望结果

期望保持一致；

**Comment by BaiJiangJie** [comment]
授权用户列表中的有效，指的是用户本身是否有效。

这里有歧义，v4 版本会去掉这个字段。

**Comment by shaohuayangfit2** [comment]
好的好的
