### ISSUE TITLE
Luna页面连接终端输入命令时无法输入空格键及数字

### ISSUE THREAD

**Issue by snowkity2005** [jumpserver/jumpserver#1343]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.0-2 GPLv2
##### 问题复现步骤
1. [步骤1]
使用普通用户登录jumpserver
2. [步骤2]
点击“Web终端”打开Luna页面
3.[步骤3]
选择一台终端连接成功以后，输入命令，发现无法输入空格键及数字，以继续输入命令参数（我想输入ifconfig eth0命令)。
##### 具体表现[截图可能会更好些,最好能截全]
<img width="756" alt="2018-05-20 4 09 00" src="https://user-images.githubusercontent.com/37360601/40276929-69bcdc8c-5c48-11e8-9ab4-63e83fcbdc67.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
暂时可以通过更换浏览器解决。

**Comment by snowkity2005** [comment]
这应该是软件的一个BUG吧，暂时可以通过更换浏览器解决。

**Comment by ibuler** [comment]
已修复，如有问题请重新打开issue
