### ISSUE TITLE
我们的redis没有账号和密码  怎么才能通过wenCli连接呢[Question] 

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [jumpserver/jumpserver#13432]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu 22.04 edge

### 🤔 问题描述

我们好多redis实例都没有设置账号和密码  现在想通过jumpServer的cli来访问   我在网上找了很多信息 也没能解决这个问题

### 期望结果

支持redis 没有账号和密码的方式接入

**Comment by BaiJiangJie** [comment]
Redis 支持没有用户名连接，不支持没有密码连接。
