### ISSUE TITLE
[Bug] 推送用户账号偶尔会出现无法sudo的情况

### ISSUE THREAD

**Issue by shalou93** [jumpserver/jumpserver#13433]
### 产品版本

3.8.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS7.9 系统部署了jumpserver 3.8.2版本

### 🐛 缺陷描述

使用api接口（/api/v1/assets）去推送账户模板的时候，间歇性会出现一个用户无法执行sudo su -切换到root用户，后面排查发现是推送的时候，opsadmin用户sudo配置没有写入到 /etc/sudoers，正常应有如下两行，异常的时候只有如下第一行
ops ALL=(ALL) NOPASSWD: /bin/whoami
opsadmin ALL=(ALL) NOPASSWD: /bin/su

![image](https://github.com/jumpserver/jumpserver/assets/13365304/145e0d45-5540-4e9a-b590-94fa38369d74)

### 复现步骤

间歇性出现，貌似不是必现

### 期望结果

推送账户能百分百成功，不至于说当出现生产问题，上服务器要免密切换root，结果切换不了

### 尝试过的解决方案

1、开始以为是推送顺序的问题，后面在post时候，先推送root，再推送opsadmin用户也仍然会出现上述opsadmin用户无法免密切换root的情况

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13383#issuecomment-2153768042

应该是推送参数没有推送过去。

调用 accounts API 创建账号并推送，只有主机上新创建的账号会使用推送参数，如果已经存在了，推送参数不会覆盖。
