### ISSUE TITLE
通过softether VPN连接2222、web页面时，一会不敲命令的动作就会卡住

### ISSUE THREAD

**Issue by leqii-com** [jumpserver/jumpserver#13441]
### 产品版本

Version v3.6.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

虚拟机系统：centos 7.5
内存：8G
CPU：4核心
docker：19.03.13, build 4484c46d9d
资产活跃度低，资源充足

### 🤔 问题描述

我司是softether vpn，用jumpserver Version v3.6.3，使用WEB连接linux ssh端口、使用终端2222端口连接linux ssh端口、windows RDP，均出现一会没有敲命令、或者鼠标动作，就会卡住，然后 等十几秒二十秒 敲入的命令才出现、甚至没任何反应，得关闭终端或者web页面 重连 又好了。不知道是VPN还是jumpserver原因，之前旧版本jumpserver和windows VPN没有遇到过，像是一直需要交互，一会不交互就卡住了。内网没有这种现象，但是通过softether VPN直接连接SSH没有出现这种情况，就是通过jumpserver连接资产时才出现。如果是web页面出现，可能怀疑是websocks造成，但是2222没有经过nginx转发也同样出现。

### 补充信息

之前在jumpserver群里反馈过，无人能够答复，通过销售反馈过，无人能够答复。

**Comment by BaiJiangJie** [comment]
由于长时间未回复，暂时关闭当前 issue，如果有任何问题请重新打开。
