### ISSUE TITLE
[Feature] 通过Web GUI连接数据库，双击表查询添加一个默认limit，用于防呆。

### ISSUE THREAD

**Issue by FreezeJ** [jumpserver/jumpserver#13448]
### 产品版本

V3.10.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

![QQ图片20240619111622](https://github.com/jumpserver/jumpserver/assets/26806873/3072b252-b87c-45ad-8262-86ac2ca0f9cf)
![QQ图片20240619111552](https://github.com/jumpserver/jumpserver/assets/26806873/2900eef3-f3d4-4e36-be8e-7a16eb2316b1)

图一：使用Navicat连接Mysql数据库，双击表只会默认查询1000条数据。
图二：jumpserver通过web gui连接会默认查询所有，没有做limit限制。对于一些大表如果误点了可能会对服务器造成一定压力，也无法返回任何结果。

### 解决方案

建议默认也加上limit 1000限制，限制查询范围，防呆，又可以对表进行一定预览。

**Comment by Aaron3S** [comment]
请问是什么类型的数据库？ 我们默认有加 limit

**Comment by FreezeJ** [comment]
使用的是mysql哦。实际上有加limit，但是下放查询没有显示出来么，默认的值是多少呢？
我尝试查询一张2w条数据的表，直接双击是会返回所有内容的。

**Comment by BaiJiangJie** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/32935519/bebd25d1-52e1-41ff-9c80-5713f8d77f69)

双击数据库表，默认会 limit 50 条。

如果是自己输入的 SQL，不会 limit。

**Comment by FreezeJ** [comment]
> ![image](https://private-user-images.githubusercontent.com/32935519/342258332-bebd25d1-52e1-41ff-9c80-5713f8d77f69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjA1MDQsIm5iZiI6MTcxOTIyMDIwNCwicGF0aCI6Ii8zMjkzNTUxOS8zNDIyNTgzMzItYmViZDI1ZDEtNTJlMS00MWZmLTljODAtNTcxM2Y4ZDc3ZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA5MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OWY4NjBiMDZiOWM3ZDI4NWQxZmM3ZWJmYzcyOWIxYTEwOTQ0MTgwYmYzOTEyZGI2OWM1ODIyNDI3MzVkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwiLVPscYrL44DukM-Y1wxHjQB73u5htkrlcQAez2ig)
> 
> 双击数据库表，默认会 limit 50 条。
> 
> 如果是自己输入的 SQL，不会 limit。

我又试了一下，我发现我的情况与你是相反的，我在查询里面select语句会加上limit 50，但是我双击表，就没有Limit。
![image](https://github.com/jumpserver/jumpserver/assets/26806873/dc076162-1a72-4d53-9f49-1df8771d05a0)

可以告诉一下你所使用的版本吗？我直接升级一下，感谢！
