### ISSUE TITLE
VSCode 连接Jumpserver 无法记录用户操作命令[Bug] 

### ISSUE THREAD

**Issue by Xfireman** [jumpserver/jumpserver#13444]
### 产品版本

3.4.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

版本:	v3.4.1

### 🐛 缺陷描述

用户通过vscode连接jumpserver到GPU服务器上，审计台记录操作命令。

### 复现步骤

通过vscode 连接到jumpserver即可在审计台复现。

**Comment by BaiJiangJie** [comment]
是的，VS Code 连接资产是记录不了操作命令的。
如果要记录，需要解析 VS Code 的协议。
暂时没有计划支持。
