### ISSUE TITLE
[Feature] 远程应用方式运维web资产存在越权漏洞&解决问题的一点思路

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13456]
### Product Version

V3.10.10

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

1. 堡垒机版本：V3.10.10
2. 堡垒机服务器版本：centos7.6
3. 应用发布服务器版本：WinSer2019

### 🐛 Bug Description

1. 在应用发布服务器创建的jms_开头的账号数量较少的情况下，假设堡垒机A用户使用jms_A账号运维web资产时，进入发布器的控制台（控制台指cmd，控制面板等，操作步骤见复现步骤），进行一些设置，比如本地代理，然后关闭jms_A的回话。
2. 堡垒机B用户使用jms_A账号运维web资产，进入发布器控制台，发现代理等配置还在。
3. 我理解这种应该是RemoteApp的问题导致。
4. 我想了一种解决办法，供参考。

### Recurrence Steps

1. 堡垒机上的jms账号数量为1，这种情况下最容易复现问题。
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/9ea8fef1-4e21-4489-aec0-3f4bc6047737)
2. 登陆web资产，保证两次会话使用的同一个jms_的账号（堡垒机登陆admin账号，第一个运维web资产的账号是js_admin，第二个运维web资产的账号就是jms_A，在浏览器界面右键，打开控制台）

![图片](https://github.com/jumpserver/jumpserver/assets/156915989/46ea83f0-c224-4332-bbaa-bf6094b79931)
3. 关闭第二个会话，登陆堡垒机B账号，建立两个会话，第一个会话使用js_B的账号登陆资产，第二个账号用jms_A的账号登陆资产，进入控制台，之前的配置还在，我理解这种配置是因为时系统层面的配置，所以还在。

### Expected Behavior

1. 希望可以想办法处理这个问题。
2. 提供了个人的解决思路，希望得到回复。

### Attempted Solutions

1.  我个人的解决思路是，限制堡垒机自动创建的jms_*数量不可以太少，并且堡垒机创建到发布服务器的jms_*的账号，不要共享使用，比如在堡垒机用户A使用了jms_A账号，会话关闭之后，堡垒机自动销毁jms_A账号，然后重新创建一个jms_*的账号。

2. 我自己测试的，不同的Windows账号下，代理等系统配置是不通用的，只针对当前账号有效，在其他账号下，还是默认关闭状态。

**Comment by BaiJiangJie** [comment]
你好，感谢提问。

发布机应用账号的生成使用了两种格式，
1. `jms_` 为前缀的账号
2. `js_` 为前缀的账号

`js_` 为前缀的账号，是每一个 JumpServer 用户独享的账号，别的用户连接远程应用不会用到的。

`jms_` 为前缀的账号，是所有 JumpServer 用户共享的账号，主要为了解决一些远程应用不能并发连接的问题。

上面提到的“越权”的问题，是所有用户都通过同一个 `jms_` 账号登录到发布机后，修改当前账号的一些配置，会出现。
这种情况没有办法解决，如果要求比较严格，建议去掉 `jms_` 账号的生成，只使用 `js_` 开头的账号。

**Comment by zjdc** [comment]
您好，我理解的上述的“越权”问题，属于remote-app的问题，这个我们没办法去修复。那能否堡垒机创建到发布服务器的jms_*的账号，不要共享使用，比如在堡垒机用户A使用了jms_A账号，会话关闭之后，禁用jms_A的账号，等到禁用的jms_*账号到了一定数量，然后定期去销毁这些账号，重新建立一批。这样的话可能也能解决问题，也不需要堡垒机去经常销毁和创建账号，对系统的压力应该不大。

上面您说的去掉jms开头的账号，只用js开头的账号，这样应该就没办法正常使用远程应用了，因为远程应用的用户也不少呢，同时登录的概率还是蛮大的。

**Comment by BaiJiangJie** [comment]
正常应该是不会出现的，使用账号连接远程应用后，会话结束，会立即清理掉windows上的会话。

不过，`jms_` 开头的账号使用策略可以考虑再优化一下，按照最后使用时间降序排序，进行选择。

**Comment by rooode** [comment]
> 正常应该是不会出现的，使用账号连接远程应用后，会话结束，会立即清理掉windows上的会话。
> 
> 不过，`jms_` 开头的账号使用策略可以考虑再优化一下，按照最后使用时间降序排序，进行选择。

关于“正常情况下会清理会话”，实际测试并不会，能确定清理会话可以将个人代理设置清理掉吗？
对于使用策略优化“按照最后使用时间降序排序”，如有人故意利用此漏洞，安装一个Fiddler类代理，然后直接将所有jms_用户设置一遍代理，之后就可以使用Fiddler查看账号密码类的敏感信息。

**Comment by LeeEirc** [comment]
清理会话，指是当前 rdp 的连接会话。至于公共账户的代理配置问题，后续会考虑进行如下优化：使用公共账号的会话结束之后，会删除其账号及其 home 目录，然后再重新创建一个同名的公共账号。

**Comment by BaiJiangJie** [comment]
Please stay tuned for future version releases.

**Comment by jym503558564** [comment]
v4.1.0已优化账号隔离策略。
优化如下：使用公共账号的会话结束之后，会删除其账号及其 home 目录，然后再重新创建一个同名的公共账号。
请升级进行体验。
