### ISSUE TITLE
[Feature] 支持HANA数据库

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#13458]
### 产品版本

v3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

多个用户使用SAP，对其HANA数据库纳管是刚需，希望能尽快支持

### 解决方案

。

**Comment by BaiJiangJie** [comment]
使用远程应用方式连接。

**Comment by jstbw** [comment]
远程应用只能录屏录像，没法做命令阻断、审计

**Comment by BaiJiangJie** [comment]
暂时不考虑。
