### ISSUE TITLE
coco长时间不操作卡死问题

### ISSUE THREAD

**Issue by shenhongbin7854** [jumpserver/jumpserver#1345]
你好：
        版本Version 1.3.0-2 GPLv2
  
        现象：连接到目标服务器之后，如果长时间（其实5分钟左右）不操作，就会页面卡死，不能输入，只能关闭连接工具，重新连接。
        系统xshell连接linux。
        
        输出日志，没有错误输出

**Comment by wojiushixiaobai** [comment]
网络问题，自己排查下
