### ISSUE TITLE
[Bug] 我设置了token超时时间为12小时，但是还是五分钟不操作就过期了

### ISSUE THREAD

**Issue by XiaoMuCOOL** [jumpserver/jumpserver#13453]
### 产品版本

3.10.9

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu系统，docker安装

### 🐛 缺陷描述

我在config.txt设置了：CONNECTION_TOKEN_EXPIRATION=12 * 60 * 60，并重启了：docker restart jumpserver/core-ce
就是说我设置了token超时时间为12小时，但是还是五分钟不操作就过期了。请问应该如何设置？
<img width="1044" alt="image" src="https://github.com/jumpserver/jumpserver/assets/1594808/f56e6c5e-00ec-42d0-91f5-6790e6d784ca">

### 复现步骤

修改配置文件，重启，前台页面还是现实5分钟。

### 尝试过的解决方案

我在config.txt设置了：CONNECTION_TOKEN_EXPIRATION=12 * 60 * 60，12个小时还是五分钟就过期。

**Comment by BaiJiangJie** [comment]
还少一个配置：CONNECTION_TOKEN_REUSABLE=true

**Comment by BaiJiangJie** [comment]
由于长时间未回复，暂时关闭当前 issue，如果有任何问题请重新打开。
