### ISSUE TITLE
自定义字段的列宽是否可以自主加宽

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13462]
### 产品版本

V3.10.9

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

备注信息目前是悬停暂时，需求可以自定义增加列宽或不悬停展示

### 解决方案

不通过悬停，直接看全字段信息
![image](https://github.com/jumpserver/jumpserver/assets/136306850/639b47e3-f2ce-4f2b-b1ed-5c1ba205106a)

**Comment by BaiJiangJie** [comment]
可以拖拽列宽，临时有效。
