### ISSUE TITLE
[Bug] 搭建完成后，文件管理没有任何资源

### ISSUE THREAD

**Issue by leipore** [jumpserver/jumpserver#13460]
### Product Version

Version v3.10.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu 22.04  Version v3.10.10

### Recurrence Steps

文件管理页面 全面资源看不到，文件空。没有看到报错。

**Comment by leipore** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/17704595/6e9c6b7f-4947-4266-b1b6-540310e886f5)

**Comment by LeeEirc** [comment]
有没有添加授权对应的 sftp 资产？

**Comment by leipore** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/17704595/e45526d3-fd97-4851-8ce3-7106e24b8ba5)
我用的系统管理员

**Comment by LeeEirc** [comment]
对应的资产是否都添加了 sftp 协议，不仅仅是 ssh 协议

**Comment by leipore** [comment]
明白了。新版功能不太了解。
