### ISSUE TITLE
jumpserver使用ldap功能后，AD用户密码更新后，jumpserver ldap无法自动同步！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#1346]
[简述你的问题]

##### 使用版本
1.3.0-2

##### 问题复现步骤
1. 使用ldap连接AD后，AD用户可以使用登陆名直接登陆，非常的完美方便，
2. 当AD用户更改了密码后，发现jumpserver的ldap无法自动同步最新的AD账号密码，用户使用旧密码可以登录jumpserver，但是新密码无法登陆

##### 其他
因为不同的用户，环境不同，有的用户无需自动同步账号密码，
是否可以做成默认不同步，但是功能存在，让有需要的用户，自行更改打开功能进行使用？
谢谢！
[注:] 完成后请关闭 issue

**Comment by wang415** [comment]
我这里遇到的是问题的，新密码和老密码都是可以登录的。
这应该是个产品的bug

**Comment by ibuler** [comment]
缓存引起的已修复，

```
settings.py  增加解决
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1
```

**Comment by ibuler** [comment]
如果还存在问题，欢迎继续讨论
