### ISSUE TITLE
[Question] 使用账号推送功能时，ansible报错，提示 Unable to connect to asset: No password or public key available!

### ISSUE THREAD

**Issue by huanglaoqian** [jumpserver/jumpserver#13464]
### 产品版本

v3.10.5

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：CentOs 7.9
浏览器：Google Chrome
部署架构：单节点

### 🤔 问题描述

在使用账号推送的时候，手动执行提示以下报错

```
TASK [Verify test password (paramiko)] *****************************************
[WARNING]: Distribution debian 11 on host 192.168.10.92(test) should use
/usr/bin/python3, but is using /opt/py3/bin/python3.11, since the discovered
platform python interpreter was not present. See
https://docs.ansible.com/ansible-
core/2.14/reference_appendices/interpreter_discovery.html for more information.
fatal: [192.168.XX.XX(test) -> localhost(127.0.0.1)]: FAILED! => {"changed": false, "msg": "Unable to connect to asset: No password or public key available!"}

PLAY RECAP *********************************************************************
192.168.10.92(test)        : ok=3    changed=1    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0
成功: 0, 失败: 1, 总数: 1
```

![1](https://github.com/jumpserver/jumpserver/assets/131110393/9ab97d50-bd76-43e7-9972-bcae35098dc2)

密文生成策略 手动配置和 随机生成都提示这个报错

看了推送资产的账号列表，账号已经推送成功，但是密码不显示

![2](https://github.com/jumpserver/jumpserver/assets/131110393/95086c9b-4929-442e-a698-95157b70e889)

检查了机器上的账号，也创建成功了

现在我该怎么处理呢？

### 期望结果

please  help

thanks

**Comment by BaiJiangJie** [comment]
详情页面不显示密码，点击查看按钮可以查看。

报错应该是，账号推送成功了，但是密码没有设置成功。
