### ISSUE TITLE
[Question] 模版管理Playbook可否支持版本管理？

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#13466]
### 产品版本

v3.10.9

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

产品:	JumpServer 社区版 GPLv3
版本:	v3.10.9
Copyright:	FIT2CLOUD 飞致云 © 2014-2024

### 🤔 问题描述

记录Playbook的变更记录，增加版本管理？
或者支持获取Git仓储内容？通过Git做版本管理？

**Comment by BaiJiangJie** [comment]
暂时不支持共享。
