### ISSUE TITLE
个人工作台中，我的资产中添加备注字段信息，重新登录后字段信息会恢复默认，需要重新勾选备注这一字段

### ISSUE THREAD

**Issue by 1223ruiyin** [jumpserver/jumpserver#13461]
### 产品版本

V3.10.9

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

环境信息 3.10.9  3.9.2

### 🐛 缺陷描述

个人工作台中，资产添加备注信息，换个浏览器重新登录或无痕登录，字段信息会恢复默认，其他字段测试如上一致

### 复现步骤

1.登录个人工作台，修改自定义字段，添加备注字段。
![image](https://github.com/jumpserver/jumpserver/assets/136306850/26039a56-ef26-429e-9931-71dd702ca203)
2.当前浏览器退出用户重新登录，备注字段还在。
3.浏览器开启无痕，或切换浏览器，备注字段不存在，需要重新开启。
![image](https://github.com/jumpserver/jumpserver/assets/136306850/c697ebe8-9371-4c94-a4ec-017505465ab8)

### 期望结果

期望字段可以保存，不会恢复默认

**Comment by BaiJiangJie** [comment]
列表字段的显示，目前是存放在 Cookie 中的， 所以无痕、或者其他浏览器会恢复默认。

如果要实现需要将用户偏好，持久化存储到服务端。暂时不考虑优化。
