### ISSUE TITLE
[Question] 作业中心模版Playbook如何共享给其他用户？

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#13465]
### 产品版本

v3.10.9

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

产品:	JumpServer 社区版 GPLv3
版本:	v3.10.9
Copyright:	FIT2CLOUD 飞致云 © 2014-2024

### 🤔 问题描述

如题：作业中心模版Playbook如何共享给其他用户？

**Comment by BaiJiangJie** [comment]
暂时不支持共享。
