### ISSUE TITLE
[Bug] 用户资产授权提问

### ISSUE THREAD

**Issue by zhigang327** [jumpserver/jumpserver#13482]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

linux  centos系统

### 🐛 缺陷描述

新建一个用户   由用户通过邮箱链接自行设置密码，我对他账号授权了一台资产设备，但是他可以对没有授权的资产进行操作和链接

### 复现步骤

1 创建一个账号 ，账号在没有设置密码的情况下首先对账号授权了资产  然后账号通过邮件链接设置了登录密码  登录之后居然可以对没有授权的资产进行操作

**Comment by BaiJiangJie** [comment]
查看一下资产授权，进入用户详情查看资产授权规则页面，看看有几条规则。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
