### ISSUE TITLE
jumpserver1.0登陆后关闭浏览器，下次打开不要认证直接进入主页？

### ISSUE THREAD

**Issue by py0426** [jumpserver/jumpserver#1348]
##### 使用版本
jumpserver1.0

##### 问题复现步骤
1. 登陆账号

2. 关闭浏览器

3.打开浏览器，输入跳板机网址，无需认证直接进入

**Comment by ibuler** [comment]
认证是有缓存期的，如果你想每次关闭浏览器重新认证可以参考  http://docs.jumpserver.org/zh/docs/faq.html 第14条
