### ISSUE TITLE
[Feature] 会话安全-连接最大空闲时间无法限制Web SFTP会话

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [jumpserver/jumpserver#13492]
### Product Version

v3.7.2

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Edge 126.0.2582.68
RedHat 7.9

### 🐛 Bug Description

会话安全-连接最大空闲时间无法限制Web SFTP会话。
即使连接最大空闲时间设置了5分钟，Web SFTP超过20分钟未操作，也不会被关闭会话，依旧可以正常操作。

### Recurrence Steps

会话安全-连接最大空闲时间设置为5分钟，
打开Web SFTP会话，等待超时后继续操作。

**Comment by BaiJiangJie** [comment]
目前 SFTP 会话没有空闲时间超时中断策略。

计划将来在 v4 版本中支持。

**Comment by jym503558564** [comment]
v4.1.0,SFTP会话支持会话空闲超时断开连接。请升级体验。
