### ISSUE TITLE
[Question] 多层Nginx报CSRF Failed: CSRF token missing.

### ISSUE THREAD

**Issue by cttino** [jumpserver/jumpserver#13501]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

运行方式：前端Nginx用于反向解析，后端2个jumpserver web集群+Redis+DB
浏览器: Chrome， Opera
从浏览器登录URL（已发布至公网，经过统一前端Nginx），在页面修改增加删除任何东西都会报错CSRF Failed: CSRF token missing. 前端启用证书

=>HTTPS (testing.abc.com) =>Firewall 映射Nginx主机,upstream=>JumpServer 2 台主机Nginx
*Nginx主机与Jumpserver非相同VLAN*

前端log *275 client canceled stream 25 while sending request to upstream, client: 192.168.0.1, server: [testing.abc.com](http://testing.abc.com/), request: “DELETE /api/v1/authentication/user-session/ HTTP/2.0”, upstream: “[http://192.168.2.1:80/api/v1/authentication/user-session/](http://192.168.2.1/api/v1/authentication/user-session/)”, host: “[testing.abc.com](http://testing.abc.com/)”, referrer: “https://testing.abc.com/ui/”

后端Nginx log没有任何有价值信息

请教如何解？谢谢

### 🤔 问题描述

浏览器开发者模式发现的错误 {“detail”:“CSRF Failed: CSRF token missing.”,“code”:“permission_denied”}

后端Nginx按照官方建议配置

server {
listen 80;
server_name [demo.jumpserver.org](http://demo.jumpserver.org/); # 自行修改成你的域名
return 301 https://$server_name$request_uri;
}
server {
listen 443 ssl http2;
server_name [demo.jumpserver.org](http://demo.jumpserver.org/); # 自行修改成你的域名
ssl_certificate sslkey/1_jumpserver.org_bundle.crt; # 自行设置证书
ssl_certificate_key sslkey/2_jumpserver.org_bundle.key; # 自行设置证书
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;
ssl_protocols TLSv1.1 TLSv1.2;
add_header Strict-Transport-Security “max-age=63072000” always;

client_max_body_size 4096m;  # 录像及文件上传大小限制
location / {
    # 这里的 ip 是后端 JumpServer nginx 的 ip
    proxy_pass http://192.168.244.144;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
}
}

### 期望结果

期望能够得到一个帮助

**Comment by wojiushixiaobai** [comment]
直接访问 `Firewall 映射Nginx主机,upstream` 是否有问题。
如果无问题，确定是反向代理的问题的话，确定你的域名已经正确配置在 DOMAINS 里面
```sh
# proxy_set_header Host $host;
# 可以尝试使用
proxy_set_header Host $http_host;
```

**Comment by cttino** [comment]
直接访问 Firewall 映射Nginx主机,upstream 是否有问题。
=>没有问题，登录什么都正常，就是一直有CSRF Failed: CSRF token missing

如果无问题，确定是反向代理的问题的话，确定你的域名已经正确配置在 DOMAINS 里面
=>之前没有配置DOMAINS，后来在排查过程中，在/opt/jumpserver/config/config.txt中配置，域名:443和公网IP：80，stop jmsctl, start jmsctl,并且重启jumpserver

后端jumpserver里Nginx配置
=> location / {
    proxy_pass http://192.168.1.1; #jumpserver 主机IP
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header Origin https://$host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Connection $http_connection;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-CSRFToken $http_x_csrf_token;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # 如果上层还有其他 slb 需要使用 $proxy_add_x_forwarded_for 获取真实 ip

 都是同样的报错，如果单纯访问jumpserver ip，则不会有这个问题

**Comment by wojiushixiaobai** [comment]
直接访问 `Firewall 映射Nginx主机,upstream` 地址，也出现 `CSRF Failed: CSRF token missing` 表示有问题。
检查你的 `WAF` 是不是拦截了相应的请求。

**Comment by cttino** [comment]
Firewall上允许Https和http，Nginx到Jumpserver端口全开，反过来Jumpserver到Nginx端口全开，Nginx出去端口全开
172.31.3.1 - - [27/Jun/2024:12:22:56 +0800] "PATCH /api/v1/settings/setting/?category=announcement HTTP/1.1" 403 72 "https://testing.abc.com/ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "192.168.0.2"  #日志有403
注：172.31.3.1为Nignx的host IP，192.168.1.1为Jumpserver的host IP, 有Vlan隔离，但策略互通，192.168.250.1为jumpserver的DockerIP，但从Nginx上是ping不通Docker IP的，但在Jumpserver上可以ping通Docker IP，不知道是不是问题所在

**Comment by wojiushixiaobai** [comment]
沟通可能有点问题，如果 7 层代理无法解决的话，你可以尝试用 4 层代理处理看看。
这样可以绕开 `WAF` 的相关策略，先排除 `WAF` 的影响。

另外反向代理这块，`proxy_set_header` 的相关配置还是根据 `Nginx` 官方文档详细了解下。
