### ISSUE TITLE
[Bug] 远程应用方式连接数据库审计命令不完整

### ISSUE THREAD

**Issue by kk545141** [jumpserver/jumpserver#13502]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.10

通过远程应用方式连接oracle数据库，无法进行命令记录方式的完整审计。
有时候记录到的命令中包含很多其他字符，见下图，有时候干脆记录不到。

![图片3](https://github.com/jumpserver/jumpserver/assets/29938714/259d6479-b88f-4bec-828a-8b03f471e84a)
![图片2](https://github.com/jumpserver/jumpserver/assets/29938714/409e3716-2f29-4f2a-8aad-f2d4696e1092)
![图片1](https://github.com/jumpserver/jumpserver/assets/29938714/4a219454-fd49-4586-b6ca-4396c402ecd4)

### 🐛 缺陷描述

通过远程应用方式连接oracle数据库，无法进行命令记录方式的完整审计。
有时候记录到的命令中包含很多其他字符，见下图，有时候干脆记录不到。

![图片3](https://github.com/jumpserver/jumpserver/assets/29938714/6bd99e94-be59-4220-9524-0f9d7f1ac429)
![图片2](https://github.com/jumpserver/jumpserver/assets/29938714/5ac7c930-c393-4784-a3e7-3acb20e484e6)
![图片1](https://github.com/jumpserver/jumpserver/assets/29938714/f8e882a2-9c21-4a57-adc2-70e62139f5aa)

### 复现步骤

远程应用方式连接oracle数据库，结果如上，oracle服务器端是11g

复现步骤：通过远程应用web端形式连接oracle资产，执行select 或者 delete等命令，有时无法获取到命令，导致命令过滤无法生效，以及命令记录审计中记录不到。

### 期望结果

提供远程应用连接方式的完整审计。

**Comment by BaiJiangJie** [comment]
是的，远程应用连接方式，不记录命令审计以及命令过滤规则。
