### ISSUE TITLE
[终端水印可自定义] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13515]
### 产品版本

v3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

终端连接资产的水印能否支持自定义，部分资产名称太长，显示不全，例如可以自定义水印内容，或者支持修改字体大小

### 解决方案

终端连接资产的水印能否支持自定义，部分资产名称太长，显示不全，例如可以自定义水印内容，或者支持修改字体大小

**Comment by BaiJiangJie** [comment]
暂时不考虑。
