### ISSUE TITLE
管理用户-测试可连接性时没有返回结果，一直输出点点点

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1351]
![image](https://user-images.githubusercontent.com/8511007/40399967-99c50248-5e72-11e8-9414-bfd25dc0937e.png)

![image](https://user-images.githubusercontent.com/8511007/40399995-aed484ec-5e72-11e8-83d0-254ae03096d1.png)

ops_celerytask表中的数据达到145万多，这还没正式上线，程序只跑了几天而已：
![image](https://user-images.githubusercontent.com/8511007/40401860-32ad5520-5e7b-11e8-9872-abb93d62a668.png)

版本：1.3

**Comment by wojiushixiaobai** [comment]
尝试重启下celery，./jms restart celery
如果还是不行的话需要清理celery产生的数据(无法正常推送及连接资产可以使用)
    $ source /opt/py3/bin/activate
    $ cd /opt/jumpserver/apps
    $ python manage.py shell
    $ from celery.task.control import discard_all
    $ discard_all()
    $ exit()
    $ cd /opt/jumpserver
    $ ./jms restart celery

任然不行，把所有jumpserver有关进程都停止，然后重新启动（确定系统编码是zh_CN.UTF8）

**Comment by gengkeye** [comment]
@wojiushixiaobai 谢谢 celery -A ops purge -f，然后重启celery也可以解决

**Comment by vspark** [comment]
还有一种情况，就是 jumpserver/tmp/ 目录下的celery.pid，没有被正常删除，手工删除一下，再重启celery可以解决。

**Comment by swq-github** [comment]
# ./jms restart celery
Traceback (most recent call last):
  File "./jms", line 16, in <module>
    import daemon
ModuleNotFoundError: No module named 'daemon'

jumpserver1.5.4 提示这个。在系统用户界面发现新加的用户没有进去手动点了一下推送，然后就推送了default所有的机器。
现在想终止这个推送，求命令。总不能直接./jms restart吧
