### ISSUE TITLE
[Bug] 商业版试用到期后，在会话记录界面会进入错误的组织

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#13510]
### 产品版本

3.10.10

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

离线安装包，单机部署的企业版试用环境，license已到期

### 🐛 缺陷描述

进入会话记录页面，无法看到历史会话记录

### 复现步骤

1.进入会话记录界面，无法看到会话记录信息
2.查看请求，请求头X-JMS-ORG的id是4，没有会话数据
<img width="1117" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89773363/289efb28-1f69-4a60-bb76-05db011a97c8">

3.清理浏览器缓存，重新打开界面，可以看到请求头X-JMS-ORG的id是2，并且可以看到会话数据
<img width="1114" alt="image" src="https://github.com/jumpserver/jumpserver/assets/89773363/fc6cf173-ba28-4551-b5b5-b95d67827c68">

4.如果进入了系统设置页面，后续会继续发生进入错误组织的情况。

### 期望结果

试用license到期后，可以继续正常使用社区版功能

**Comment by BaiJiangJie** [comment]
原因是企业版中有组织功能，社区版不支持切换组织。

如果 License 到期了，清除浏览器缓存（Local Storage）和 Cookie 应该就正常了。
