### ISSUE TITLE
录像无法回放

### ISSUE THREAD

**Issue by github-eric** [jumpserver/jumpserver#1352]
[简述你的问题]
各种功能一切正常，唯有录像无法回放（录像无法下载）。

##### 使用版本
Jumpserver 1.3.0
Centos: CentOS Linux release 7.5.1804   3.10.0-862.2.3.el7.x86_64

##### 问题复现步骤
1. 点击Sessions --> Session offline --> Replay
2. 弹出框出现”录像无法下载“
3. 在/opt/jumpserver/data/media/目录中有录像的压缩文件。
4. 在nginx的access log中发现这种log
10.10.2.77 - - [23/May/2018:07:13:35 +0000] "GET /socket.io/?EIO=3&transport=polling&t=MEBs2pa&sid=8aeb2d64fbf54e54b99fc34f756e8669 HTTP/1.1" 200 14 "http://10.10.19.91/luna/replay/d7ecf150-7969-41cf-8351-319c2f54fdc" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15" "-"

5. 在/opt/luna是没有replay目录。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28553907/40409357-3e5f451e-5e9d-11e8-87b6-2a87959844b2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wanyang1989** [comment]
我也碰到了这个问题，有的可以回放，有的不能回放，找不到规律，问题不好解决，求解答！

**Comment by dinglitong** [comment]
同问

**Comment by zhnxin** [comment]
(all for 1.3.2)我在Firefox浏览器上也遇到这个问题，看到data/media目录下的确有相应的录像文件,后来换成chrome就没问题了。

**Comment by ibuler** [comment]
可能和录像大小有关系，如果还有问题，请继续讨论该话题

**Comment by lanmaodage** [comment]
我也遇到了，使用的版本是最新的1.4.6，安装的步骤和文档的一样的，也是无法播放
Not Found
The requested URL /index.html was not found on this server.
各位朋友有没有处理方法

**Comment by superbeanmr** [comment]
我遇到了jumpserver  录像无法回放的问题
NGINX配置如下
![image](https://user-images.githubusercontent.com/32116764/57567391-00e54b00-740b-11e9-8ab4-b2d011536b82.png)

点击回放的时候
![image](https://user-images.githubusercontent.com/32116764/57567402-2e31f900-740b-11e9-8ad1-7967ee2ae37a.png)

NGINX已经改用了root用户，但是还是一样的问题

请大神给予指导，谢谢 谢谢
