### ISSUE TITLE
[Bug] v3.10.11 web终端页面下方的输入栏没有了

### ISSUE THREAD

**Issue by liubo637** [jumpserver/jumpserver#13520]
### Product Version

v3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu , 官方升级包，docker , win11 , edge 126.0.2592.68 

### 🐛 Bug Description

v3.10.11 web终端页面下方的输入栏没有了

### Recurrence Steps

![QQ截图20240627084022](https://github.com/jumpserver/jumpserver/assets/1932666/58327928-aa9d-43bc-a62c-220dc16dd6da)

**Comment by BaiJiangJie** [comment]
系统设置-功能设置-任务中心，开启`作业中心`。
