### ISSUE TITLE
[Question] 切换自不成功

### ISSUE THREAD

**Issue by Windywind** [jumpserver/jumpserver#13526]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Ubuntu 24.04 单机部署

### 🤔 问题描述

Ubuntu上有

- 可以sudo的用户ubuntu （支线：请问这里的ubuntu是不是“特权用户”？）
- 特权用户root

ubuntu可以sudo su免密码切换到root （但是su - root需要密码）

这种情况下，我希望所有SSH会话都是使用ubuntu账号连接到资产，需要root权限的使用sudo su切换过去

我在jumpserver配置root账号，切换自ubuntu，但我不希望在平台配置root密码或者密钥

那么root账号的密码部分我该如何配置？
![image](https://github.com/jumpserver/jumpserver/assets/9924858/d1c9eb17-68ac-4e29-ac44-8185ad5b59ec)

配置密码为空的时候，账号测试root账号不能成功
![image](https://github.com/jumpserver/jumpserver/assets/9924858/b727486e-c4b9-47be-a4ab-308e4c36b2a2)

### 期望结果

root账号能正常通过ubuntu切换，账号测试可以正常进行且通过

**Comment by Windywind** [comment]
如果我在“root账号的密码部分”随意填写一个密码，那么root账号可以通过测试
![image](https://github.com/jumpserver/jumpserver/assets/9924858/1700630f-a93a-46ab-a62d-278382ed1835)
但无法实际使用？
![image](https://github.com/jumpserver/jumpserver/assets/9924858/2e89a4ba-2300-4929-bca4-a93873afed60)

**Comment by BaiJiangJie** [comment]
root 配置切换自 ubuntu 用户，要求 root 的密码必须托管，ubuntu 的密码可以不托管。

**Comment by BaiJiangJie** [comment]
设置 `sudo su -` 的切换方式，参考 https://github.com/jumpserver/jumpserver/issues/13527。

**Comment by Windywind** [comment]
@BaiJiangJie 感谢回复，请问是否可以只托管密钥，而不是密码呢？(我测试依旧如上图EOF

因为不想配置
PermitRootLogin yes
而只想配置
PermitRootLogin prohibit-password

**Comment by LeeEirc** [comment]
切换账号登陆，koko 使用密码带填。切换自的登录原理：使用 **切换自的账号** ssh 登陆到服务器资产（这个可以配置密码和密钥），然后使用 **su -** 或者 **sudo su -**  切换到需要登陆的账户（这个代填使用的是密码）

**Comment by Windywind** [comment]
了解，也就是使用“切换自”的情况下，只能密码鉴权。

**Comment by LeeEirc** [comment]
是的，但是不影响你使用 **PermitRootLogin prohibit-password**  这个配置，这针对的是 ssh 登陆。使用 **sudo su -** 或者 **su -** 时，已经不涉及这个参数了。

**Comment by LeeEirc** [comment]
根据不同的情况切换账号的密码需要不同的配置
1）使用 **sudo su -** 时，切换的账号密码，需要更改成 **切换自账号** 的密码
2）使用 **su -** 时，切换的账号密码，就是自身的密码

**Comment by Windywind** [comment]
感谢支持

**Comment by charles-liming** [comment]
如果，切换自用户 没有密码只有密钥，怎么办
