### ISSUE TITLE
[Performance] 增添功能菜单描述

### ISSUE THREAD

**Issue by jzyt1999** [jumpserver/jumpserver#13525]
### 产品版本

V3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

对于平台列表，windwos平台，高级选项中，能否对安全协议层的协议进行简单描述下

![image](https://github.com/jumpserver/jumpserver/assets/74956878/ed0cac39-8638-4549-aa80-e9e1c402309a)

### 解决方案

一.增加描述，简单描述下每个协议层的内容
二.建议用户使用哪个协议层去连接windows资产平台

**Comment by BaiJiangJie** [comment]
https://guacamole.apache.org/doc/gug/configuring-guacamole.html#authentication-and-security

将来考虑增加。先看上面链接中的描述。

**Comment by jzyt1999** [comment]
好的，谢谢解答

**Comment by jym503558564** [comment]
v4.1.0，已优化对windows平台安全协议层的协议进行简单描述，请升级进行体验。
