### ISSUE TITLE
[Feature] 企业版堡垒机对接飞书，获取到用户名，邮箱等字段不明，希望添加一个可以映射字段的配置功能。

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13524]
### 产品版本

V3.10.9

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

1. 企业版堡垒机对接飞书获取用户，获取到的用户名是飞书的用户ID，邮箱是用户ID@example.com，如下图：
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/c5f6698e-8e67-46f4-9228-72c58a9e8b32)
2. 用户名为一串ID，在使用连接向导去连接资产的时候没办法区分具体是哪个用户在连接资产。
3. 在飞书上尝试了没办法修改。希望可以在堡垒机上添加一个字段映射的配置功能。

### 解决方案

希望可以在堡垒机上添加一个字段映射的配置功能。就像是CAS认证时可以配置的用户属性映射功能。如下图：
![图片](https://github.com/jumpserver/jumpserver/assets/156915989/c07e5a31-b76d-4b71-b9f8-acf96300e7b6)

### 补充信息

感谢回复。

**Comment by BaiJiangJie** [comment]
将来考虑增加。

**Comment by jym503558564** [comment]
v4.1.0，已支持第三方认证进行属性映射配置，请升级进行体验。
