### ISSUE TITLE
[Feature] 关于添加一个从普通账号切换到root的需求

### ISSUE THREAD

**Issue by haitang5445** [jumpserver/jumpserver#13527]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

给资产添加账号时，配置一个普通用户sysisc, 此sysisc有sudo 的权限（需要密码的），再添加root账号,从sysisc的ssh二次登录，按照当前情况是使用su - 切换到root,如何自定义使用的是 sudo -i切换？

### 解决方案

![image](https://github.com/jumpserver/jumpserver/assets/59681546/7c88e0cc-28bb-4891-9111-91a414946c69)
![image](https://github.com/jumpserver/jumpserver/assets/59681546/58208f42-969a-48c5-b1ea-f4f52c94fbe9)
如图例子

**Comment by BaiJiangJie** [comment]
克隆一个 Linux 平台，开启 `Su enabled` (默认) , 设置 `Su method` 方式为 `sudo su -`。

**Comment by haitang5445** [comment]
e.....   找到了，謝謝

**Comment by Windywind** [comment]
> 克隆一个 Linux 平台，开启 `Su enabled` (默认) , 设置 `Su method` 方式为 `sudo su -`。

请问这个在哪里能配置呢？没有找到，谢谢

**Comment by BaiJiangJie** [comment]
克隆 Linux 平台后，更新平台表单中就可以看到。`切换/切换方式`选项。
