### ISSUE TITLE
视频文件下载过来有mp4的 有.gz的，官方自带的播放器不能拉快进。需要提供转换mp4的脚本

### ISSUE THREAD

**Issue by niugengtian** [jumpserver/jumpserver#13521]
### Product Version

JumpServer 企业版 v3.10.9

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

我们目前两个worker 节点 一个LB节点 一个数据库 一个minio

### 🐛 Bug Description

<img width="733" alt="image" src="https://github.com/jumpserver/jumpserver/assets/33859108/fc59a5be-0098-4c96-888e-2a58e783f99b">

### Recurrence Steps

<img width="1204" alt="image" src="https://github.com/jumpserver/jumpserver/assets/33859108/c63d4750-0850-4010-b339-416d78b21b31">

**Comment by LeeEirc** [comment]
目前仅对 rdp 和 vnc 会话有转码方式。其他 字符类 会话如 ssh、mysql 等无转换 mp4 工具。
