### ISSUE TITLE
Windows服务器是否支持录屏回放

### ISSUE THREAD

**Issue by liuwenru** [jumpserver/jumpserver#1353]
[简述你的问题]

请问windows 服务器是否有计划支持录屏回放功能？

##### 使用版本
最新版本

##### 问题复现步骤
无

##### 其他

[注:] 完成后请关闭 issue

**Comment by zzwgary** [comment]
现在版本支持

**Comment by liuwenru** [comment]
好的，谢谢，我checkout新版本测试一下

**Comment by liuwenru** [comment]
@zzwgary  您好，我现在可以使用windows的桌面登录，但是我发现在“历史会话”中并未看见windows的录屏，当我远程连接windows主机时，在“在线会话中”也看不好相关的会话记录，请问我该如何调试？麻烦指导下，谢谢！

**Comment by liuwenru** [comment]
@ibuler  我看到一些windows相关录屏的功能说已经开发好，请问该功能代码在何分支上？
