### ISSUE TITLE
[Bug] web终端这边，点击资产的时候，第一次点击不生效，需要再次点击才能打开

### ISSUE THREAD

**Issue by xxl82** [jumpserver/jumpserver#13538]
### Product Version

v3.10.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

# cat /etc/debian_version 
12.0
# uname -a
Linux ecs-yxops-jumpserver 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

# docker info
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.332GiB
 Name: ecs-yxops-jumpserver
 ID: 9ad0eb8b-a315-4d9b-b765-137e03edbab5
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

### 🐛 Bug Description

打开jumpserver的web终端，点击左边的资产树后，点击资产的时候，第一点击会出现不能弹出连接的选择界面，要再点击一次才能弹出界面

### Recurrence Steps

打开jumpserver的web终端，点击左边的资产树后，点击资产的时候，第一点击会出现不能弹出连接的选择界面，要再点击一次才能弹出界面

**Comment by BaiJiangJie** [comment]
我使用 `v3.10.11` 版本，没有出现这个问题。

你 `F12` 打开浏览器控制台，看一下 Console 有没有报错信息？

**Comment by BaiJiangJie** [comment]
Not reproduced.
