### ISSUE TITLE
[Question] v3.10.10 升到 v3.10.11 jmsctl.sh没有upgrade

### ISSUE THREAD

**Issue by b-ing** [jumpserver/jumpserver#13531]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS Linux release 7.9.2009 (Core)，chrome，docker

### 🤔 问题描述

v3.10.10 升到 v3.10.11 jmsctl.sh没有upgrade

[root@VM-0-15-centos jumpserver-installer-v3.10.10]# ./jmsctl.sh --help

JumpServer Deployment Management Script

Usage: 
  ./jmsctl.sh [COMMAND] [ARGS...]
  ./jmsctl.sh --help

Installation Commands: 
  install           Install JumpServer

Management Commands: 
  config            Configuration  Tools
  start             Start     JumpServer
  stop              Stop      JumpServer
  restart           Restart   JumpServer
  status            Check     JumpServer
  down              Offline   JumpServer
  uninstall         Uninstall JumpServer

More Commands: 
  load_image        Loading docker image
  backup_db         Backup database
  restore_db [file] Data recovery through database backup file
  raw               Execute the original docker-compose command
  tail [service]    View log

**Comment by wojiushixiaobai** [comment]
不显示而已，参考更新文档操作即可
