### ISSUE TITLE
[web cli 连接mongo数据库执行语句提示MongoServerError: Retryable writes are not supported] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#13547]
### 产品版本

3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

测试Mongo为AWS DocumentDB 5.0.0
1、使用web cli连接mongo数据库，执行语句报错
<img width="785" alt="wecom-temp-54097-fc05b685c214ff2baca0c5ff3e79f7e9" src="https://github.com/jumpserver/jumpserver/assets/38065018/f78405e0-fe0e-4a86-b864-88e1d3220ed5">
2、测试使用mongo原生命令执行相同语句，正常
<img width="1115" alt="wecom-temp-256062-876e85c3fc74a51da6494e3093a92da3" src="https://github.com/jumpserver/jumpserver/assets/38065018/85a0fee5-795b-44d4-b771-3de43b7ac81a">
3、进入koko容器，使用koko mongo命令执行，也是报错
<img width="1180" alt="image" src="https://github.com/jumpserver/jumpserver/assets/38065018/3e0fc04d-f893-4952-93a4-54245fea43a0">

### 解决方案

较早版本的 MongoDB 服务器可能不支持可重试的写入操作。确保你使用的是支持可重试写入操作的 MongoDB 版本（例如，MongoDB 4.2 及以上），建议将Koko容器内Mongo驱动程序升级到最新版

**Comment by BaiJiangJie** [comment]
先尝试手动替换一下 KoKo 容器中的 MongoDB 客户端，重启容器，看能否解决。

**Comment by wangzhishang02** [comment]
目前根据测试环境验证，和aws DocumentDB不支持重试写操作有关，和当前客户端版本无关
连接字符串中加入 `--retryWrites=false`取消重试写操作即可
<img width="1262" alt="image" src="https://github.com/jumpserver/jumpserver/assets/63093589/d1323814-2c31-4593-b70a-cd4a694cf41e">

根据反馈后续优化为增加一个参数，用户可自定义连接参数

**Comment by BaiJiangJie** [comment]
v3.10.12 已支持。
