### ISSUE TITLE
[Feature] WEB 终端的 Web CLI 内的内容可以进行字符串搜索

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#13546]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

目前WEB终端无法搜索字符串，这对于查找一些信息不是很方便。

### 解决方案

增加查找字符串的按钮，或支持浏览器原生的Ctrl+F搜索。

**Comment by BaiJiangJie** [comment]
Web CLI 的用户交互界面使用 `https://xtermjs.org/` 库进行实现的，看了一下原生库中不支持，所以暂时也支持不了。

将来会考虑单独在 Web LCI 中增加一些搜索功能。

**Comment by BaiJiangJie** [comment]
v4.2.0 版本已支持使用浏览器内置搜索功能。
