### ISSUE TITLE
[Feature] 用户可以自定义属于自己的资产名称

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#13542]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

1、在同一个资产host1中有“xx系统nginx”和“xx系统tomcat”两个应用，分别是用户user1和用户user2来维护的。
2、用户user1和user2管理的host非常多，而host1是jumpserver管理员定义的一个统一名称。
3、为了便于维护，user1和user2想通过自定义名称，进而方便查找。比如user1可以编辑名称“host1”改为“xx系统nginx”，user2也可以编辑名称“host1”改为“xx系统tomcat”。
4、类比：类似于Xshell等终端工具直连同一个资产，不同用户可能对于同一个资产命名不一样。

### 解决方案

1、管理员定义的host1作为全局名称，这个名称所有普通用户是不可修改。
2、授予user1和user2可以在全局名称的基础上修改名称，这个新名称实际上是添加一个属于用户自己的名称，用户自己才能看得到。

**Comment by BaiJiangJie** [comment]
嗯，了解。

计划在后面版本支持一下。

**Comment by jym503558564** [comment]
v4.1.0，已支持用户自定义资产名称，请升级进行体验。
