### ISSUE TITLE
[Question] 网页资产自动认证

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13551]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver版本：3.10.10

### 🤔 问题描述

![image](https://github.com/jumpserver/jumpserver/assets/44529247/9d28cc1e-fd2b-4ed4-b545-2e35aab91102)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/176be3db-50c1-49c5-9adf-ce5b88781d99)

对于这种页面的认证方式，账号密码代填部分怎么写呢

**Comment by gerry-fit** [comment]
使用 Basic Authentication 远程应用：https://apps.fit2cloud.com/jumpserver/basic-authentication
