### ISSUE TITLE
[Question] linux资产通过RDP协议访问提示错误

### ISSUE THREAD

**Issue by wugh888** [jumpserver/jumpserver#13559]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS 7

### 🤔 问题描述

centos7 安装了xrdp 想通过RDP访问该服务器。测试连通性时提示这个，请问需要做什么配置吗？

>>> 任务准备阶段
>>> 开始执行任务

PLAY [all] *********************************************************************

TASK [Test asset connection (pyfreerdp)] ***************************************
[WARNING]: Module invocation had junk after the JSON data: [09:55:42:022]
[58238:58238] [INFO][com.freerdp.core] -
freerdp_connect:freerdp_set_last_error_ex resetting error state [09:55:42:385]
[58238:58238] [INFO][com.freerdp.primitives] - primitives autodetect, using
optimized [09:55:42:387] [58238:58238] [INFO][com.freerdp.core] -
freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error
state [09:55:42:387] [58238:58238] [INFO][com.freerdp.core] -
freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[09:55:52:834] [58238:58238] [INFO][com.freerdp.core] -
freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error
state [09:55:52:834] [58238:58238] [INFO][com.freerdp.core] -
freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
fatal: [el-qc-sz-01]: FAILED! => {"changed": false, "msg": "Unable to connect to asset."}

PLAY RECAP *********************************************************************
el-qc-sz-01                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Task assets.tasks.ping.test_assets_connectivity_task[9945c125-be8a-4e13-acdb-5b9eee2564f4] succeeded in 20.555482786003267s: None

**Comment by BaiJiangJie** [comment]
显示的就是连不上，你是原生的 RDP 客户端先试试。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
