### ISSUE TITLE
[Bug] Web 终端连接 windows 设置翻译切换未生效

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#13563]
### 产品版本

v3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机部署 v3.10.11，  Chrome 浏览器

### 🐛 缺陷描述

在 Web 终端连接 windows，打开 “设置” 时，语言与左边资产树不一致
![image](https://github.com/jumpserver/jumpserver/assets/95400700/4542332d-e06f-425c-8232-b666d87136d0)

### 复现步骤

默认中文简体，在 web 终端页面切换繁体后，连接windows资产, 再切换回中文简体，关闭 windows 重新连接，打开“设置” 显示的是繁体，此时若要切换成简体需要清空浏览器缓存

### 期望结果

字体切换及时生效

**Comment by BaiJiangJie** [comment]
v4 支持。修改语言后，重新建立会话可以同步。
