### ISSUE TITLE
[Bug]  koko 连接MySQL数据库不能打开-A功能

### ISSUE THREAD

**Issue by gnayfly** [jumpserver/jumpserver#13566]
### Product Version

3.10.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jumpserver 版本3.10.10，redis和数据库使用外部之外，其余组件都是使用docker

### 🐛 Bug Description

koko连接MySQL数据库，默认是使用参数--auto-rehash，但是由于我有一个数据库里面的表非常多1000+，所以我需要关闭参数--auto-rehash或者添加参数-A，我登录到koko运行时容器(docker exec -it koko_container_id /bin/bash)，修改脚本/opt/koko/mysql，将参数：
exec su -s /bin/bash --command="mysql ${EXTRAARGS} --user=${USERNAME} --host=${HOSTNAME} --port=${PORT} --password ${DATABASE} -A" nobody
修改成:
exec su -s /bin/bash --command="mysql  --user=${USERNAME} --host=${HOSTNAME} --port=${PORT} --password ${DATABASE} -A" nobody
重启koko容器，重新连接mysql，仍然不能关闭参数--auto-rehash

### Recurrence Steps

在jumpserver安装的服务器下，执行命令ps -ef|grep mysql，则可以看到从jumpserver连接到MySQL数据库时使用的参数

### Expected Behavior

通过koko连接到MySQL的参数可以修改

**Comment by BaiJiangJie** [comment]
命令行方式连接不支持。

**Comment by xmabul** [comment]
@gnayfly koko模块连接mysql写的有点糙，官方也不想管，建议自己改代码，重新构建。
可以参考我之前修改的[issues 12515](https://github.com/jumpserver/jumpserver/issues/12515)，构建后默认不开启补全，已试可以

**Comment by LeeEirc** [comment]
> @gnayfly koko模块连接mysql写的有点糙，官方也不想管，建议自己改代码，重新构建。 可以参考我之前修改的[issues 12515](https://github.com/jumpserver/jumpserver/issues/12515)，构建后默认不开启补全，已试可以

欢迎提个 pr 帮助 koko 提升 mysql 的使用体验。
