### ISSUE TITLE
[Bug] 审计台导出命令记录后登录状态丢失，需重新登录

### ISSUE THREAD

**Issue by xusongtao** [jumpserver/jumpserver#13565]
### 产品版本

v3.10.11

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

在审计台导出  命令记录、历史会话  后用户登录状态丢失，约 20s 内提示自动退出，需重新登录

### 🐛 缺陷描述

![image](https://github.com/jumpserver/jumpserver/assets/40846859/9ed3b2d8-770e-4bbb-92df-58371edf9d49)

### 复现步骤

1、进入审计台
2、导出命令记录或历史会话
3、等待约 20s 以内

### 期望结果

修复此问题

**Comment by BaiJiangJie** [comment]
Not reproduced.
