### ISSUE TITLE
[Bug] 推送资产的时候，报错："msg": "Unable to connect to asset: q must be exactly 160, 224, or 256 bits long"

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#13564]
### Product Version

3.7.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

两台机器集群安装Jumpserver3.7.1

### 🐛 Bug Description

<img width="892" alt="image" src="https://github.com/jumpserver/jumpserver/assets/85990572/31b3e31e-4da9-43f7-93ce-bdbd5c313398">
推送账号出现报错："msg": "Unable to connect to asset: q must be exactly 160, 224, or 256 bits long"

### Recurrence Steps

重新推送 重复报错

### Expected Behavior

推送成功

**Comment by BaiJiangJie** [comment]
看着像是你的 SSH Key 不正确。

**Comment by xiaoxiongxyy** [comment]
> 看着像是你的 SSH Key 不正确。

私钥不对吗？在其他机器上推送都是正常的诶 用的都是同一个模版

**Comment by BaiJiangJie** [comment]
机器配置都一样吗？

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
