### ISSUE TITLE
[Question] RDP服务端键鼠和客户端键鼠均可用配置或方案

### ISSUE THREAD

**Issue by llm163520** [jumpserver/jumpserver#13577]
### 产品版本

v3.4.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

服务端：w10
客户端：chrome

### 🤔 问题描述

远程windows连接后服务端的鼠标键盘不可用

### 期望结果

服务端和客户端鼠标需要均可以正常使用

**Comment by BaiJiangJie** [comment]
没有遇到过，升级到最新版本。
