### ISSUE TITLE
website资产

### ISSUE THREAD

**Issue by HuaxuDuan** [jumpserver/jumpserver#13578]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

服务器：ubuntu18.04.6
应用发布机：windows server 2019
远程应用：chrome、firefox

### 🤔 问题描述

在Web终端界面，通过远程应用（chrome或firefox）可以打开web资产，并登录；
web资产是一个视频管理平台，此时无法实时预览视频；
直接登录应用发布机，在浏览器中访问该视频管理平台，可以实时预览视频；

### 期望结果

期望在Web终端界面，通过远程应用打开该web资产时，也可以实时预览视频

**Comment by BaiJiangJie** [comment]
为什么不能实时预览？

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
