### ISSUE TITLE
当网域网关前面有负载均衡或者NAT，添加网关时测试连接失败会报404

### ISSUE THREAD

**Issue by billy98** [jumpserver/jumpserver#1359]
[简述你的问题]
当网域网关前面有负载均衡或者NAT延时SSH端口，添加网关时测试连接失败会报404，虽然测试连接失败但是实际上还是可以正常使用。
如果直接用网关的IP测试连接会成功。

##### 使用版本
版本：V1.3
阿里云环境
##### 问题复现步骤
1. [步骤1]：在网关前面添加负载均衡或者做NAT映射
2. [步骤2]：添加网关，点击测试连接

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13307862/40522482-b883a90e-6003-11e8-8611-70aeb1c92528.png)

![image](https://user-images.githubusercontent.com/13307862/40522492-c9eb8a54-6003-11e8-937d-2a8cdbbb97d7.png)

**Comment by ibuler** [comment]
已修复，有问题重新打开issue
