### ISSUE TITLE
[Bug] 离线安装问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13590]
### Product Version

3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jumpserver：3.10.11
系统：ubuntu22.04

### 🐛 Bug Description

新安装ubuntu22.04  用离线安装脚本部署失败
![image](https://github.com/jumpserver/jumpserver/assets/44529247/da301826-702f-4ea2-a2f2-7580b750a550)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/a54fc69f-9152-4927-8459-317e2f408e94)

### Recurrence Steps

新安装ubuntu22.04  用离线安装脚本部署失败
![image](https://github.com/jumpserver/jumpserver/assets/44529247/da301826-702f-4ea2-a2f2-7580b750a550)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/a54fc69f-9152-4927-8459-317e2f408e94)

**Comment by wojiushixiaobai** [comment]
错误："group docker not found" 自行解决下。
或者参考 Docker 官方文档部署即可
