### ISSUE TITLE
[Question] 容器镜像体积大问题，是否考虑优化

### ISSUE THREAD

**Issue by NHZEX** [jumpserver/jumpserver#13602]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker compose 部署

### 🤔 问题描述

![image](https://github.com/jumpserver/jumpserver/assets/14545600/237a6bce-ae46-4ef5-ad7f-cf848b6934f9)
无意间发现容器镜像这么大。有点离谱。

### web
![image](https://github.com/jumpserver/jumpserver/assets/14545600/9140e867-a3d1-4258-85ca-dbf66cec2e67)

### koko
![image](https://github.com/jumpserver/jumpserver/assets/14545600/eb849d9e-862d-4fc4-ae3d-5b092a91f9b1)

### 期望结果

是否应当把静态资源的层尽量前置让层更容易复用到或者独立外置

**Comment by wojiushixiaobai** [comment]
v4.0 版本修复
