### ISSUE TITLE
想了解下怎么部署guacamole不依靠docker

### ISSUE THREAD

**Issue by zzwgary** [jumpserver/jumpserver#1360]
[简述你的问题]
想在本机centos6.9上安装guacamole，并实现自动注册，无奈官网上只有docker的使用
##### 使用版本
Jumpserver版本Version 1.3.0-2 GPLv2

##### 问题复现步骤
1. 想在本机环境centos6.9上把jumpser的所有环境装在一起
2. guacamole官方提供的是docker模块，我想直接在jumpser本机环境centos6.9不安装docker进行安装
3.按照网上的办法安装好了guacamole，但是打开需要输入账户名和密码
4.如何把安装好的guacamole往jumpser的终端管理去自动注册，这个官网上相关文档没有结论

##### 其他

[注:] 完成后请关闭 issue

**Comment by segafansljx** [comment]
我也想知道

**Comment by gxk001** [comment]
看dockerfile 
里面就是一步步的安装过程，
需要把对应软件包换成centos 版本。
![image](https://user-images.githubusercontent.com/32119424/40699178-7f9987b6-6405-11e8-9236-85c6b4f6aaa5.png)

**Comment by zzwgary** [comment]
2楼的回复怎么是流媒体的 ffmpeg，不是和python的guacamole有关系的吗

**Comment by ibuler** [comment]
使用dockerfile安装应该没问题，有问题重新打开issue
