### ISSUE TITLE
[Question] How to cancel the system task of "import LDAP user"

### ISSUE THREAD

**Issue by Ricardo-X-Chen** [jumpserver/jumpserver#13604]
### Product Version

v3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

CentOS 8 (64-bit)

### 🤔 Question Description

the task of "import LDAP user" is running continuously for several days. And no cancel option. I need to cancel these task, please help on this, thanks.
![Snipaste_2024-07-02_11-34-39](https://github.com/jumpserver/jumpserver/assets/117529739/a04454d5-031b-4b53-ac02-6268dd0ef0e0)
![Snipaste_2024-07-02_11-35-05](https://github.com/jumpserver/jumpserver/assets/117529739/ce0252f3-32f7-4d0a-ac35-9ccf989da245)

### Expected Behavior

Cancel the task of "import LDAP user"

**Comment by BaiJiangJie** [comment]
Check the configuration of `system settings -> Auth -> LDAP -> Sync setting`

**Comment by Ricardo-X-Chen** [comment]
> Check the configuration of `system settings -> Auth -> LDAP -> Sync setting`检查配置 `system settings -> Auth -> LDAP -> Sync setting`
The Sync isn't enabled.
![Snipaste_2024-07-05_16-10-51](https://github.com/jumpserver/jumpserver/assets/117529739/920e55f3-0155-4796-be4e-6251620f3829)

**Comment by BaiJiangJie** [comment]
Maybe you have enabled scheduled synchronization before, and now you need to clear redis and restart all services.

**Comment by Ricardo-X-Chen** [comment]
> Maybe you have enabled scheduled synchronization before, and now you need to clear redis and restart all services.

Yes.I have enabled it before.
so should me do this below there?
docker exec -it jms_redis bash
redis-cli
flushall

./jmsctl.sh restart  or  rebboot the machine

**Comment by BaiJiangJie** [comment]
Yeah.

**Comment by Ricardo-X-Chen** [comment]
> Yeah.
> 
> Just `./jmsctl.sh restart`.

Clear redis without effect.And I have rebuilded the jumpserver last week😅.

**Comment by BaiJiangJie** [comment]
Is it ok after rebuilding?

**Comment by Ricardo-X-Chen** [comment]
> Is it ok after rebuilding?

Yes.It's ok now.
