### ISSUE TITLE
[Question] 网页基本认证的密码代填问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13607]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：ubuntu22.04
堡垒机：3.10.11

### 🤔 问题描述

网页采用基本认证，已从应用市场下载并安装基本认证组件，并在应用发布机里安装selenium-wire，密码无法代填
1、已安装基本认证组件
![image](https://github.com/jumpserver/jumpserver/assets/44529247/8f355597-b726-410c-a3f4-05b4f9280691)
2、通过方式二实现密码代填，已安装selenium-wire
![image](https://github.com/jumpserver/jumpserver/assets/44529247/38e1ff27-5276-46d2-ba67-f63ebb09a7a2)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/50027d76-c3b3-48d1-9b75-2002cea7cfa3)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/2f4c39fc-1533-464a-aa95-6994640373e5)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/955cc152-6898-43c1-8d1e-97ec626b9da7)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/f1365fae-be37-4426-a5da-79b82b95754c)

**Comment by BaiJiangJie** [comment]
安装这个应用连接 web 资产：https://apps.fit2cloud.com/jumpserver/basic-authentication

**Comment by ryswork1993** [comment]
> 安装这个应用连接 web 资产：https://apps.fit2cloud.com/jumpserver/basic-authentication

您看我上面的截图，我已经安装过这个基本认证组件，也在应用发布机执行了pip install selenium-wire -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by BaiJiangJie** [comment]
连接资产的时候选的是 `基本认证` 的应用吗？

**Comment by ryswork1993** [comment]
> 网页采用基本认证，已从应用市场下载并安装基本认证组件，并在应用发布机里安装selenium-wire，密码无法代填
> 1、已安装基本认证组件

![image](https://github.com/jumpserver/jumpserver/assets/44529247/e299358f-374c-4c82-96aa-a504fcd40e9d)
![image](https://github.com/jumpserver/jumpserver/assets/44529247/28331954-d176-4bdf-963d-dee43c1aa1c4)
未代填
![image](https://github.com/jumpserver/jumpserver/assets/44529247/b9e1677d-48e9-4b77-8165-9da6c9384941)

**Comment by ryswork1993** [comment]
> 连接资产的时候选的是 `基本认证` 的应用吗？

是勾选的基本认证，这里需要写什么东西吗
![image](https://github.com/jumpserver/jumpserver/assets/44529247/9346bcb8-b92c-4f4c-8dc6-fa6a88182f37)

**Comment by LeeEirc** [comment]
检查下你这个认证类型是 basic 吗？参考下[web资产代填](https://blog.csdn.net/weixin_44734350/article/details/139978334)

**Comment by ryswork1993** [comment]
> 检查下你这个认证类型是 basic 吗？参考下[web资产代填](https://blog.csdn.net/weixin_44734350/article/details/139978334)

认证类型是Basic

**Comment by LeeEirc** [comment]
请使用 v3.10.11 测试，或者使用全新 v4 测试，保持当前测试环境一致。正常上传自定义应用之后，会自动创建 basic 平台。

**Comment by ryswork1993** [comment]
> 请使用 v3.10.11 测试，或者使用全新 v4 测试，保持当前测试环境一致。正常上传自定义应用之后，会自动创建 basic 平台。

用全新系统离线安装的方式测试了，上传基本认证组件后，没有自动创建basic平台
![image](https://github.com/user-attachments/assets/ab1fdb74-ab6d-4e50-bf2e-f7ab8407d8c7)
![image](https://github.com/user-attachments/assets/b61e0b16-7262-4af3-a600-737de2078e01)

**Comment by BaiJiangJie** [comment]
你的逻辑和上面描述的一样吗？第2步，资产平台选择的是 basic 吗？

**Comment by ryswork1993** [comment]
> > 请使用 v3.10.11 测试，或者使用全新 v4 测试，保持当前测试环境一致。正常上传自定义应用之后，会自动创建 basic 平台。
> 
> 用全新系统离线安装的方式测试了，上传基本认证组件后，没有自动创建basic平台 ![image](https://private-user-images.githubusercontent.com/44529247/348203613-ab1fdb74-ab6d-4e50-bf2e-f7ab8407d8c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjU3NTAsIm5iZiI6MTcyMTAyNTQ1MCwicGF0aCI6Ii80NDUyOTI0Ny8zNDgyMDM2MTMtYWIxZmRiNzQtYWI2ZC00ZTUwLWJmMmUtZjdhYjg0MDdkOGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA2MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODhkYzU2MjY5MTgxMjM2ZWVjMDhjOTJlMzI5YTBmNzcxNjYzMDIyM2NhYjM2YTU3MTk3NjRiYzg2NDRiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8fsRh689Yg4zOJ6v6dtphFPyqNq95iRj01cQSDVTiU) ![image](https://private-user-images.githubusercontent.com/44529247/348203641-b61e0b16-7262-4af3-a600-737de2078e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjU3NTAsIm5iZiI6MTcyMTAyNTQ1MCwicGF0aCI6Ii80NDUyOTI0Ny8zNDgyMDM2NDEtYjYxZTBiMTYtNzI2Mi00YWYzLWE2MDAtNzM3ZGUyMDc4ZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA2MzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNjc3N2FhYjI5ZmY4N2NkNzllZDdiMmIxNmE5OWM5YzA2OTczZGNmZWRhNTk3NmE0YzkwZDk1ZThkNTY1M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ftz8V2-u-wR9hsZ0k_gC_XEILWeNpWBw2F1n4MSWo4c)

用全新系统离线安装的方式测试了，上传基本认证组件后，没有自动创建basic平台，自己创建又提示basic平台已存在

**Comment by BaiJiangJie** [comment]
可能是 v4.0 版本社区版有 Bug，没有显示出自定义类型的平台。

**Comment by BaiJiangJie** [comment]
The issue will be fixed in `v4.0.1`.
