### ISSUE TITLE
Version 1.3.0-2 GPLv2 上sftp连接不正常

### ISSUE THREAD

**Issue by zzwgary** [jumpserver/jumpserver#1361]
[简述你的问题]
sftp服务器在linux下不正常
##### 使用版本
Version 1.3.0-2 GPLv2

##### 问题复现步骤
1. 安装成功通过ssh服务器的2222端口访问远程正常
2. 通过sftp访问服务2222端口会报错
3.该admin用户为jumpser登陆的账户，在本机上是没有该账户会报错，有什么办法可以通过呢？
4.在windows下用ftp客户端是没问题的

##### 具体表现[截图可能会更好些,最好能截全]
![qq 20180525153206](https://user-images.githubusercontent.com/23518095/40532184-3a169ef4-6031-11e8-87d4-7b50a6fd6965.png)

![qq 20180525153236](https://user-images.githubusercontent.com/23518095/40532185-3af9546a-6031-11e8-8fe1-4307e2431a11.png)
![qq 20180525153246](https://user-images.githubusercontent.com/23518095/40532187-3c57634c-6031-11e8-8755-dea9b1a0b46c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
确定coco的版本已经更新到与jumpserver一致的版本
部分系统无法直接使用sftp命令连接到服务器，请尝试通过gui工具进行连接（如xftp，filezilla等）

**Comment by kemenkai** [comment]
我没遇到过这个问题，我的问题是，sftp命令登录的时候直接报错了。回事一大堆数字。
不过我是因为设置了session长链接，所以导致ssh链接冲突。

**Comment by zzwgary** [comment]
谢谢这个问题已经解决，小白说的很对，不过我现在是升级到最新的，确认好了coco的版本，没问题了
