### ISSUE TITLE
windows资产平台上传文件卡住

### ISSUE THREAD

**Issue by 0xo7** [jumpserver/jumpserver#13617]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

浏览器为谷歌，电脑系统为win10，采用部署架构集群部署，上传文件到windows平台的时候，会卡在50%一会，然后显示传输速度会明显下降。

### 🤔 问题描述

上传文件到windows平台会卡住，而且如果选择的平台是windows有的时候会很慢，选择remoteapphost或者windows tls平台，则胡快一些。但是都会传输文件到50%会卡住一会，然后传输速度明显下降很多。

**Comment by 0xo7** [comment]
另外，上传文件到windwos平台的时候，会先把文件传到哪里呢 ？传输文件的规则是啥呀

**Comment by LeeEirc** [comment]
相关规则如下：
- Web gui 通过侧边栏的上传文件都是暂存到组件 Lion 的 Driver 目录路径 `/data/jumpserver/lion/data/drive{user_id}/ `
这个目录是以用户的 id 隔离的，同一个用户打开多个 Windows rdp 是可以共享这个目录的。
- 上传速度 会卡在 50%，是正常情况，等待后端上传处理逻辑。
- 机器平台不会影响上传的速度，主要还是当时的网络及负载影响。
