### ISSUE TITLE
升级v4.0.0之后，快捷命令没有了

### ISSUE THREAD

**Issue by lxq-max** [jumpserver/jumpserver#13614]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

rocky linux 9.3

### 🤔 问题描述

从v3.10.11升级到v4.0.0之后，没有快捷命令功能

**Comment by lxq-max** [comment]
已经处理了，需要在设置开启快捷命令功能

**Comment by bigbig-ha** [comment]
在设置里没找到开启快捷命令地方啊
