### ISSUE TITLE
[Bug] 快捷命令操作华为交换机时报错

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#13623]
### Product Version

4.0.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu22.04
jumpserver4.0.0

### 🐛 Bug Description

快捷命令用华为模块执行命令到华为交换机时报错
"changed": false,
    "msg": "Command: dis ip int bri, unable to decode json from response to exec_command('{\"command\": \"dis ip int bri\", \"output\": \"text\", \"prompt\": null, \"answer\": null}'). received 'none'."
![image](https://github.com/jumpserver/jumpserver/assets/44529247/d37a30b9-c389-4a9d-9a78-fcf762fb0147)

### Recurrence Steps

在快捷命令里勾选华为交换机，选择华为模块执行dis ip int bri 报错
![image](https://github.com/jumpserver/jumpserver/assets/44529247/3d0c0a1f-6a29-42ba-9c71-f82b627adea2)

**Comment by ryswork1993** [comment]
这个是否能帮忙排查，我可以提供测试环境
qq：854407887

**Comment by BaiJiangJie** [comment]
不支持使用缩写形式，使用完整的命令：
display  ip interface brief

**Comment by BaiJiangJie** [comment]
<img width="1141" alt="WeChatd7a5b7b69089f8f2b506c24ac1a4c207" src="https://github.com/jumpserver/jumpserver/assets/32935519/d19756bd-5fd1-4eff-9147-8fa53237c270">

**Comment by ryswork1993** [comment]
> <img alt="WeChatd7a5b7b69089f8f2b506c24ac1a4c207" width="1141" src="https://private-user-images.githubusercontent.com/32935519/347761834-d19756bd-5fd1-4eff-9147-8fa53237c270.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTA0NjEsIm5iZiI6MTcyMDY5MDE2MSwicGF0aCI6Ii8zMjkzNTUxOS8zNDc3NjE4MzQtZDE5NzU2YmQtNWZkMS00ZWZmLTkxNDctOGZhNTMyMzdjMjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA5MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MDYxOGY1YmViNjIzOGMzZGE5MDE3NTBlODk2NTFmMzNmNDA3ZDY3NTBkNTk2MGFkZWI5Nzg4ZGYxMmI3NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FUiTJ4e30Bky5v4S4UHOp-m8wCHf1CUM9LhzM3njUmM">

一样不行
![image](https://github.com/jumpserver/jumpserver/assets/44529247/885c5f44-9e56-4c5a-a9be-cf95b2a1837f)

**Comment by BaiJiangJie** [comment]
你用原生 Ansible 试试。

**Comment by ryswork1993** [comment]
> 你用原生 Ansible 试试。

没用过ansible -·-

**Comment by BaiJiangJie** [comment]
学习一下，如果原生 Ansible 执行没问题，再提上来。

**Comment by ryswork1993** [comment]
之前的3.10.10的时候就是正常的






| |
任永帅
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月11日 17:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Bug] 快捷命令操作华为交换机时报错 (Issue #13623) |

学习一下，如果原生 Ansible 执行没问题，再提上来。

**Comment by BaiJiangJie** [comment]
v4 和 v3 的 Ansible 逻辑一致，没有改动。
