### ISSUE TITLE
[Question] 如何对已经入库的系统用户公钥私钥反解读取出来？

### ISSUE THREAD

**Issue by zhoushoujianwork** [jumpserver/jumpserver#13621]
### 产品版本

当前版本

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

任何

### 🤔 问题描述

![image](https://github.com/jumpserver/jumpserver/assets/40590631/267f7369-2778-4f72-a052-721aebb0a8e8)
![image](https://github.com/jumpserver/jumpserver/assets/40590631/a03f19e3-a82a-4828-b51c-5fd53cdb2bc5)
这块加密加盐后的数据如何反找回来，是否支持后续快速出一个反解析 python脚本，实现入参加密后的字符串+secret等信息反解回来，防止丢失后无法恢复。

### 期望结果

可以通过脚本实现数据库信息反解得到。

**Comment by BaiJiangJie** [comment]
使用 django shell 进入到后台可以直接读取。
