### ISSUE TITLE
[Feature] Windows 虚拟磁盘磁盘中的文件下载

### ISSUE THREAD

**Issue by Chang228** [jumpserver/jumpserver#13622]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

想建立 windows 文件传出的途径，
通过增加 jumper server 所在服务器，并把 SFTP 协议指向路径 {data}/lion/data/driver 方式实现了共享 windows 中的虚拟磁盘，但是路径中有一层用户ID，在多用户登录时因为多了一层uuid路径，无法分辨用户

![1720265867595](https://github.com/jumpserver/jumpserver/assets/5670521/94778473-374f-4593-b201-40350c4bf165)
![1720265893384](https://github.com/jumpserver/jumpserver/assets/5670521/44befdbf-58a9-4287-a985-0f4177bb9e4c)

### 解决方案

现在只提供了三个变量,ACCOUNT,USER,HOME，希望增加 ACCOUNTID 变量来代表这个 UUID

**Comment by BaiJiangJie** [comment]
这个 `8b12cfbe-` ID 就是登录 Windows 的用户 ID。根据 ID 就可以分辨出这个用户。

**Comment by Chang228** [comment]
可否把这个变量作为 变量设置到
