### ISSUE TITLE
[Question]  4.0 版本 admin 账户的默认密码是啥？

### ISSUE THREAD

**Issue by dmanbu** [jumpserver/jumpserver#13626]
### 产品版本

v4.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

OS: CentOS 7.9

### 🤔 问题描述

想知道 jumpserver 4.0 版本 admin 账户的默认密码是啥？
已经试过 admin 这个密码了，但不正确

**Comment by Ewall555** [comment]
![1720412443851](https://github.com/jumpserver/jumpserver/assets/102132588/e277b4bb-c0e6-4dde-9be0-ff14283b4c12)
ChangeMe，readme中有说明
