### ISSUE TITLE
[Feature] 建议增加mongodb的web gui连接方式

### ISSUE THREAD

**Issue by mangobowl** [jumpserver/jumpserver#13629]
### Product Version

v3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

现有的web cli方式连接mongodb，在查询文档较大，或内容较多时，展示效果一般。如果能有类似mysql gui的展示效果的话，会方便得多。

### Proposed Solution

增加mongodb gui的连接方式。

**Comment by BaiJiangJie** [comment]
暂时没有计划。
