### ISSUE TITLE
[Question]  Remote App Host Issue

### ISSUE THREAD

**Issue by m7mdcc** [jumpserver/jumpserver#13638]
### Product Version

v4.0.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

HOST IS DEBIAN 11

### 🤔 Question Description

The issue is when creating Remote App Host , with windows server 2019 
when choosing rdp :
on test : ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'set_options'
on refresh : fatal: [helper]: FAILED! => {"msg": "the connection plugin 'rdp' was not found"} 
I have tried those command with no success :

```
docker exec -it jms_celery bash

cd apps/

python manage.py shell

import pyfreerdp

```

if use winrm : 
everything work ok , else 

Remote App chrome connect its say : 
Core API failed: connect API core err: No host account available

I bypass the issue with " FAILED! => {"msg": "the connection plugin 'rdp' was not found"} " on console with assets by choosing Platform to Windows2016 

then its work . 

Could we choose platform for Remote App host  "from RemoteAppHost to Windows2016  "? then maybe its will be solved ?  I think Remote App need RDP not winrm ?

**Comment by LeeEirc** [comment]
Open ```System settings -- RemoteApp -- RemoteApp machine```

You should check the following:
- Verify that the Load status of the RemoteApp machine is normal.
- Open the detail page of the RemoteApp machine, navigate to the RemoteApp tab, and ensure that the release status of all applets is successful. If not, initialize and deploy them by clicking the Initialize and Deploy buttons on the right side.
- Open the detail page of the RemoteApp machine, navigate to the Account tab, and confirm that all accounts are active.

**Comment by m7mdcc** [comment]
> Open `System settings -- RemoteApp -- RemoteApp machine`
> 
> You should check the following:
> 
> * Verify that the Load status of the RemoteApp machine is normal.
> * Open the detail page of the RemoteApp machine, navigate to the RemoteApp tab, and ensure that the release status of all applets is successful. If not, initialize and deploy them by clicking the Initialize and Deploy buttons on the right side.
> * Open the detail page of the RemoteApp machine, navigate to the Account tab, and confirm that all accounts are active.

for reason i don't know , many attemps done from my side . but the applets start working

but still have the issue that rdp not found

**Comment by LeeEirc** [comment]
Try to add ssh protocol for the Remote App Host. Some Ansible tasks need ssh protocol to execute commands.

**Comment by Niu1234561221** [comment]
Thank you very much. After adding the SSH protocol, it is now ready to use

**Comment by TaqnyatNocTeam** [comment]
> Try to add ssh protocol for the Remote App Host. Some Ansible tasks need ssh protocol to execute commands.

Winrm should work fine ?

**Comment by rudstone** [comment]
Hi,

I have the same problem with Windows 10 in RemoteApp configured. I don't have "Load statut" defined in Online... 
I try to add rdp/3389 & ssh/22 & winrm/5985 ; without result.

Any help?

Thank's
