### ISSUE TITLE
[Bug] 容器不定期出现 Unhealthy 状态

### ISSUE THREAD

**Issue by susongtest** [jumpserver/jumpserver#13632]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS7.9系统，Docker version 23.0.6，在线一键安装的所有组件。
从v3版本的低版本慢慢升级到3.10.10版本。

### 🐛 缺陷描述

环境运行一段时间后，容器状态会变成不健康状态，系统 messages 日子有报错，修改系统的 limit 文件限制也没有用。
dockerd: time="2024-07-06T07:47:24.239834152+08:00" level=warning msg="Health check for container b048915f2c379266e5b073ae18c1dfa615ea354f2b744607495f7e9ea019dec2 error: OCI runtime exec failed: exec failed: unable to start container process: exec /bin/sh: too many open files in system: unknown"

此问题在最近两个版本都有出现，出现时间不确定。

### 复现步骤

在线一键安装，所有组件在容器内运行。运行一段时间后就会出现容器 不健康状态，导致服务不可用。

### 期望结果

期望能解决。

### 尝试过的解决方案

尝试修改系统的文件数限制，貌似没有用。
想修改容器的限制，但是不知道怎么去修改

**Comment by BaiJiangJie** [comment]
具体到哪个容器会出现 unhealth？

**Comment by susongtest** [comment]
系统message 的部分报错。
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.447901542+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.447901549+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.449431499+08:00" level=warning msg="Health check for container 3cac8c15cf55060aa514cce9618e81c99bca8c4793e0217b2af8dd87c7dce346 error: OCI runtime exec failed: exec failed: unable to start container process: exec /bin/sh: too many open files in system: unknown"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.810088532+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.810095289+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.811378664+08:00" level=warning msg="Health check for container dc2f95e529f45befcbb8340ad4dad779bfc79a6aab6bfa43a297dec038733467 error: OCI runtime exec failed: exec failed: unable to start container process: exec /bin/sh: too many open files in system: unknown"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.820773165+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.820777302+08:00" level=error msg="stream copy error: reading from a closed fifo"
Jul 15 01:02:59 jms dockerd: time="2024-07-15T01:02:59.821952491+08:00" level=warning msg="Health check for container af4264f98be36721e775d333d1e054ed9f53cee1126aeae755d6cac217076fd2 error: OCI runtime exec failed: exec failed: unable to start container process: exec /bin/sh: too many open files in system: unknown"
Jul 15 01:03:01 jms dockerd: time="2024-07-15T01:03:01.941453136+08:00" level=error msg="stream copy error: reading from a closed fifo"


容器状态查询：
CONTAINER ID   IMAGE                         COMMAND                   CREATED      STATUS                       PORTS                                                                                                                                                  NAMES
87761e41a08d   jumpserver/kael:v3.10.10      "./entrypoint.sh"         9 days ago   Up 9 days (unhealthy)        8083/tcp                                                                                                                                               jms_kael
a2b27585e5f1   jumpserver/lion:v3.10.10      "./entrypoint.sh"         9 days ago   Up 9 days (unhealthy)        4822/tcp, 8081/tcp                                                                                                                                     jms_lion
f60153b4828d   jumpserver/core-ce:v3.10.10   "./entrypoint.sh sta…"   9 days ago   Restarting (1) 7 hours ago                                                                                                                                                          jms_core
f0862350123e   jumpserver/core-ce:v3.10.10   "./entrypoint.sh sta…"   9 days ago   Restarting (1) 7 hours ago                                                                                                                                                          jms_celery
af4264f98be3   jumpserver/redis:6.2          "docker-entrypoint.s…"   9 days ago   Up 9 days (unhealthy)        6379/tcp                                                                                                                                               jms_redis
18386b952f55   jumpserver/mariadb:10.6       "docker-entrypoint.s…"   9 days ago   Up 9 days (unhealthy)        3306/tcp                                                                                                                                               jms_mysql
3cac8c15cf55   jumpserver/web:v3.10.10       "/docker-entrypoint.…"   9 days ago   Up 9 days (unhealthy)        0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                                               jms_web
d825fa0a24be   jumpserver/chen:v3.10.10      "./entrypoint.sh"         9 days ago   Up 9 days (unhealthy)        8082/tcp                                                                                                                                               jms_chen
dc2f95e529f4   jumpserver/magnus:v3.10.10    "./entrypoint.sh"         9 days ago   Up 9 days (unhealthy)        8088/tcp, 14330/tcp, 0.0.0.0:33061-33062->33061-33062/tcp, :::33061-33062->33061-33062/tcp, 54320/tcp, 0.0.0.0:63790->63790/tcp, :::63790->63790/tcp   jms_magnus
12564f1342d6   jumpserver/koko:v3.10.10      "./entrypoint.sh"         9 days ago   Up 9 days (healthy)          0.0.0.0:2222->2222/tcp, :::2222->2222/tcp, 5000/tcp                                                                                                    jms_koko

执行 ./jmsctl stop 后，容器状态：
![stop后](https://github.com/user-attachments/assets/d6bf5b1d-a0a7-436a-9e3b-f94a0a0d5217)

**Comment by susongtest** [comment]
出问题时，容器状态查询。我排查后，感觉好像是凌晨时 ，堡垒机自己执行的 容器状态检查 时，报的错。
出问题基本都是在凌晨，不定时的周期性问题，出现问题后，只能强制对系统进行断电操作后，才能回复。
![企业微信截图_17210028165920](https://github.com/user-attachments/assets/3135acb8-b740-4472-bf9e-f2e0e45e6eda)

**Comment by BaiJiangJie** [comment]
看容器状态是所有容器都 unhealthy 了。

看下 core 的日志，找 jumpserver.log 和 gunicorn.log 文件。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
