### ISSUE TITLE
[Question] 升级后无法连接mongo

### ISSUE THREAD

**Issue by lai-vson** [jumpserver/jumpserver#13631]
### 产品版本

v4.0.0-ce

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

利用docker部署。./jmsctl.sh upgrade

### 🤔 问题描述

从版本v3.10.11升级后就无法连接mongo。一直无法找到mongosh。该如何解解决呢？

![image](https://github.com/jumpserver/jumpserver/assets/81406180/9010b173-bdef-457c-bb37-6d2d9c942202)
![image](https://github.com/jumpserver/jumpserver/assets/81406180/401cc6e0-c75a-4070-b888-fa41b922ca40)

**Comment by lai-vson** [comment]
mongosh似乎已被移除。

**Comment by BaiJiangJie** [comment]
mongosh 没有移除，你去 jms_koko 容器里看一下。

**Comment by lai-vson** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/81406180/e546dc15-0bc9-45f6-bbbf-a6a744c17eda)

进入了jms_koko容器没找到mongosh。反而v3.10.11 是没问题的。

![image](https://github.com/jumpserver/jumpserver/assets/81406180/794e16d5-0b6d-4a53-8c5d-4230c090d30a)
升级到v4.0.0-ce就有问题了

安装版本v3.10.11 和v3.10.12都还有mongosh
![image](https://github.com/jumpserver/jumpserver/assets/81406180/6ba2dbaa-980a-4631-8f7e-4613ee5abbe8)
![image](https://github.com/jumpserver/jumpserver/assets/81406180/7e36bf16-35ad-413b-8700-f8a77d684ece)

看了镜像是用不同的Dockerfile打包镜像的.

![image](https://github.com/jumpserver/jumpserver/assets/81406180/0cf38672-65d3-48df-a3f6-955c29304a2d)
![image](https://github.com/jumpserver/jumpserver/assets/81406180/b7bbba81-aa19-45f1-a7c9-7f5478ab07c7)

为什么v4.0.0 没有呢？ 现在勉强用着v3.10.12 jms_koko镜像

**Comment by BaiJiangJie** [comment]
确认了一下，v4 版本的 mongosh 确实移除了，v4.1 版本会加回来。

现在你使用 v4 版本，在 jms_koko 容器中，手动安装一下就可以了。

**Comment by BaiJiangJie** [comment]
v4.0.1 和 v4.1 都会修复。

**Comment by BaiJiangJie** [comment]
The issue will be fixed in `v4.0.1`.
