### ISSUE TITLE
点击组用户列表中的授权资产不同的标签不会自动刷新对应的资源

### ISSUE THREAD

**Issue by ljpwinxp2** [jumpserver/jumpserver#1363]
创建了一个组，组内授权了资产。点不同的标签页时，资产不会自动刷新

##### 使用版本
Version 1.3.0-2 GPLv2
阿里云，Centos 7.4
依照官网安装的jumpserver

##### 问题复现步骤
1. [步骤1]
   进入组> 选一个用户组
2. [步骤2]
  选授权的资产，点击左边的资产标签，注意切换标签，观察右边的资源列表是否更新。

3.同样的功能，在用户列表内的资产操作，是显示正常的。

##### 具体表现[截图可能会更好些,最好能截全]
[图片](http://i2.51cto.com/images/blog/201805/26/cfeba25f5184d4c3cd0caee2108c9f82.gif)
[图片2](http://i2.51cto.com/images/blog/201805/26/5020c7ee1c4d7d08b2424b7a76121e36.jpg?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复，有问题重新打开issue
