### ISSUE TITLE
使用jumpserver出现的一些问题

### ISSUE THREAD

**Issue by py0426** [jumpserver/jumpserver#1364]
[简述你的问题]
    1.使用浏览器的web终端功能，会话管理显示的远端地址为127.0.0.1，应该是一个bug。
    2.在web终端内登录到某台机器后，退出必须要输入exit，才能正常从在线会话转为历史会话，若是直接关闭会话，则会一直存在于在线会话中。

##### 使用版本
[Jumpserver  Version 1.3.1-2]

**Comment by wojiushixiaobai** [comment]
是的，目前存在这个问题，第二个问题与使用者的习惯有关，后续需要看下开发老哥那边怎么处理。

**Comment by ibuler** [comment]
1. nginx 设置 header,参考文档
2. 关闭浏览器后，几分钟后才会转为历史会话

**Comment by ibuler** [comment]
有问题重新打开issue
