### ISSUE TITLE
jms_magnus  | 2024-07-09 10:43:28 [ERRO] create session failed, auth failed, EOF,from: 127.0.0.1:57694 db_type: mysql[Question] 

### ISSUE THREAD

**Issue by ChenJustin666** [jumpserver/jumpserver#13642]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

root@master-01:/jumpserver/Dockerfile# cat .env 
# 版本号可以自己根据项目的版本修改
VERSION=v3.10.10

# 构建参数, 支持 amd64
TARGETARCH=amd64

# Compose
COMPOSE_PROJECT_NAME=jms
# COMPOSE_HTTP_TIMEOUT=3600
# DOCKER_CLIENT_TIMEOUT=3600
DOCKER_SUBNET=192.168.250.0/24

# 持久化存储
VOLUME_DIR=/opt/jumpserver

# 时区
TZ=Asia/Shanghai

# MySQL
DB_HOST=192.168.178.122
DB_PORT=3306
DB_USER=jumpserver
DB_PASSWORD=KXOeyNgDeTdpeu9q
DB_NAME=jumpserver

# Redis
REDIS_HOST=192.168.178.122
REDIS_PORT=6379
REDIS_PASSWORD=8URXPL2x3HZMi7xoGTdk3Upj

# Core
SECRET_KEY=CRqqTIjheqkkyPHZqHUljsxqC9IndwMjcm5lUMSKaoRpFH8wSh
BOOTSTRAP_TOKEN=a180aKa4pS3ArBcn
LOG_LEVEL=ERROR
DOMAINS=www.csq.com

# Web
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_MYSQL_PORT=33061
MAGNUS_MARIADB_PORT=33062
MAGNUS_REDIS_PORT=63790

##
# SECRET_KEY 保护签名数据的密匙, 首次安装请一定要修改并牢记, 后续升级和迁移不可更改, 否则将导致加密的数据不可解密。
# BOOTSTRAP_TOKEN 为组件认证使用的密钥, 仅组件注册时使用。组件指 koko、guacamole

### 🤔 问题描述

https://gitee.com/hadf/jumpserver.git 这里安装的

### 期望结果

https://gitee.com/hadf/jumpserver.git

### 补充信息

https://gitee.com/hadf/jumpserver.git

**Comment by BaiJiangJie** [comment]
Issue 提交不符合规范。问题描述不清楚。
