### ISSUE TITLE
[Feature] 菜单显示问题

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13651]
### Product Version

4.0

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

应为 ”账号改密“
![image](https://github.com/jumpserver/jumpserver/assets/15103510/2561e5c8-2c26-4c7a-84dc-47a7c3f0bb94)

### Proposed Solution

应为 ”账号改密“

**Comment by BaiJiangJie** [comment]
The issue will be fixed in `v4.0.1`.
