### ISSUE TITLE
[Feature] 默认新增的Linux资产只有sftp协议

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13652]
### Product Version

4.0

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

 默认新增的Linux资产只有sftp协议
![image](https://github.com/jumpserver/jumpserver/assets/15103510/d8cf6f15-9862-4af4-a7c9-510c06c33143)

### Proposed Solution

默认协议应加上 ssh

**Comment by ibuler** [comment]
测试没有问题

![image](https://github.com/jumpserver/jumpserver/assets/17382885/e99b652c-0386-407f-ad6b-b566a68ab1a3)

**Comment by w940853815** [comment]
https://github.com/jumpserver/jumpserver/pull/13669 已修复
