### ISSUE TITLE
[Bug] 点击登录，提示登录超时

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13655]
### Product Version

4.0

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

点击登录，提示登录超时,地址栏强制刷新也用，去掉域名后面的所有参数刷新也没有用，切换到无痕模式或者清除浏览器缓存才解决。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/106cbe08-b17f-4812-877b-202ad39765ce)

### 🐛 Bug Description

点击登录，提示登录超时,地址栏强制刷新也用，去掉域名后面的所有参数刷新也没有用，切换到无痕模式或者清除浏览器缓存才解决。

### Recurrence Steps

点击登录，提示登录超时,地址栏强制刷新也用，去掉域名后面的所有参数刷新也没有用，切换到无痕模式或者清除浏览器缓存才解决。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13352#issuecomment-2146863894

**Comment by liufei20151013** [comment]
![image](https://github.com/user-attachments/assets/0d70ecbb-8f06-4f65-b9c8-4aeb7fc5f8aa)
配置是这样的，而且是刚刚退出，然后重新登录的时候出现的

**Comment by BaiJiangJie** [comment]
开启 SESSION_COOKIE_AGE > 30s 试试。
