### ISSUE TITLE
[Question] 创建或修改资产授权规则时的账号推送问题

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#13653]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS7
v3.10.7，离线安装
火狐浏览器v127.0.2

### 🤔 问题描述

问题：
最近添加了一个用户为管理员，以帮助进行Jumpserver的后台管理。他修改一个资产授权规则，添加用户时选择了“模板添加”，导致了这个授权的资产节点下所有资产全部进行了添加帐号的操作，一方面为堡垒机上的资产添加了帐号，另一方面为实际的资产推送了帐号。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/30d865e5-ad24-4a18-8772-074f288851f1)
由于这个规则中的用户节点资产的范围很大，所以出现了大量主机的/etc/passwd告警。

经查，至少有这几种情况：
1、主机资产上没有这个帐号的，会创建这个帐号。
2、主机资产上有这个帐号的，会更改密码为模板密码。
3、一些网络设备应该没有推送成功，但堡垒机上网络设备也关联了这个帐号。

### 期望结果

1、因为在“资产授权规则”中的“帐号”框中本身可以通过输入帐号来添加，那么是否有必要有“模板添加”这个功能，这个功能或可去掉。
2、结合“1”的问题，因为有直接输入帐号的替代授权方式，并且“模板添加”会有堡垒机资产创建堡垒机帐号以及为资产推送帐号的额外功能，如果保留，那么建议放到“帐号管理”里面。这样避免新手管理人员的误解（虽然有提醒）。
3、资产上有帐号的，推送时不改资产上现有用户的密码。
4、对于批量操作的，提供比较详细的日志或分析报表。

### 补充信息

**======2024.7.10补充======**
经确认，所有模板帐号的“自动推送”开关是关闭状态。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/7da27d03-9764-4f3a-9d9e-9c11985b0aa5)

我做了4个测试，这4个测试都是在资产有特权账户的情况下进行的。
发现“1”和“2”原本**可能**会在操作系统上创建帐号的地方反而不会创建。当然因为“自动推送”开关是关闭的，这个应该算是正常情况：
**测试1**、堡垒机在“资产列表”下创建新主机资产，添加模板帐号后。在实际的主机没有这个帐号的情况下，也不会在实际的主机上自动推送创建此帐号。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/6b642da6-d573-4100-8c70-96d6dcd7ec1f)
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/4b587fd2-954f-4e64-b696-ee3ab316f84c)

**测试2**、堡垒机在“帐号列表”下选择“模板添加”到资产后，在实际的主机没有这个帐号的情况下，也不会在实际的主机上自动推送创建此帐号。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/3d90712b-2485-4bd2-ab39-34dfb4439b49)
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/c671d334-6b8a-4d81-a407-0b8b380dc750)

**测试3**、堡垒机在主机资产没有添加此帐号的情况下，只要在“资产授权”通过“模板添加”此帐号，在实际的主机没有这个帐号的情况下，会在主机推送添加此帐号。
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/dbda7f15-3739-44d7-ad41-e4ed2e341a22)
![图片](https://github.com/jumpserver/jumpserver/assets/82021637/b143e4e7-c0a4-4f12-b64a-ac4275c6c22d)

**测试4**、堡垒机在主机资产**没有**添加此账号的情况下，只要在“资产授权”通过“模板添加”此帐号，在实际的主机**有**这个帐号的情况下，会修改此帐号的密码。如果堡垒机主机资产原本已经**有**此账号的情况下不会修改实际主机的账号密码。

**Comment by BaiJiangJie** [comment]
感谢提问。

### 对于期望结果中提到的4个问题的回复

1. 因为在“资产授权规则”中的“帐号”框中本身可以通过输入帐号来添加，那么是否有必要有“模板添加”这个功能，这个功能或可去掉。
> 资产授权中的`账号`框只允许授权资产上已存在的账号。
> 资产授权中的`模版账号`的概念，是 v2 版本中`动态系统用户`的概念。实现了，自动添加资产账号并推送到目标主机中。
> 虽然在账号列表，已经存在使用账号模版可以批量创建并推送资产账号，但是很多用户还是希望能够继承到资产授权规则中。
> 所以，是有必要的。

2. 结合“1”的问题，因为有直接输入帐号的替代授权方式，并且“模板添加”会有堡垒机资产创建堡垒机帐号以及为资产推送帐号的额外功能，如果保留，那么建议放到“帐号管理”里面。这样避免新手管理人员的误解（虽然有提醒）。
> 账号管理中也有这个功能。

3. 资产上有帐号的，推送时不改资产上现有用户的密码。
> 推送的概念，就是添加账号到目标主机上，包括账号密码。因为推送完，需要使用密码登录。如果不修改密码，那么推送后在连接资产时会失败。也就是，推送的目的，是保证主机上账号的密码和JumpServer中保存的密码一致。

4、对于批量操作的，提供比较详细的日志或分析报表。
> 这是建议很好，下一步提供授权规则相关的推送任务日志，供管理员查看。

### 对于补充信息中提到的问题的回复

通过模版添加账号是为了实现自动创建并推送账号的需求，目前总共有4个地方可以关联：
  - 账号管理 > 账号列表
  - 资产详情 > 账号列表
  - 资产创建/更新 > 添加账号模版
  - 资产授权创建/更新 > 添加账号模版

这4个地方，使用模版添加账号时，是否推送到远端，都应该遵循账号模版中的 `自动推送` 选项是否开启，只有开启的时才执行推送任务（目前逻辑上有 Bug，后面版本 v3.10.13、v4.1 中修复）。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13708#issuecomment-2244784271
