### ISSUE TITLE
[Bug] 今日活跃资产数有问题

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13658]
### Product Version

4.0

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

今日活跃资产数有问题，应不大于1；资产总数统计延时较大，确认是统计延时导致。
![image](https://github.com/jumpserver/jumpserver/assets/15103510/01e3bb0f-a670-47c8-82df-90f7fb4ffa76)
![image](https://github.com/jumpserver/jumpserver/assets/15103510/96d7f945-a7ab-4a7c-8525-63b2eeb657f7)

### 🐛 Bug Description

今日活跃资产数有问题，应不大于1

### Recurrence Steps

今日活跃资产数有问题，应不大于1

**Comment by BaiJiangJie** [comment]
关注后续版本发布。

**Comment by BaiJiangJie** [comment]
Please stay tuned for future version releases.
