### ISSUE TITLE
[Bug] 今日登录账号数占比有问题

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13650]
### 产品版本

4.0

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

今日登录账号数占比有问题，应不大于1
![image](https://github.com/jumpserver/jumpserver/assets/15103510/55ca3961-e625-493e-860c-82a8a3c7a1ea)

### 🐛 缺陷描述

今日登录账号数占比有问题，应不大于1

### 复现步骤

今日登录账号数占比有问题，应不大于1

### 期望结果

今日登录账号数占比有问题，应不大于1

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13658

重复。
