### ISSUE TITLE
[Feature] 希望在偏好设置里面增加一个默认语言设置，不想每次登陆后都要切换语言

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13659]
### Product Version

v3、v4

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

希望在偏好设置里面增加一个默认语言设置，不想每次登陆后都要切换语言。有些外企还是希望用英文的，而我们的产品默认是中文，切换英文后，清空浏览器缓存或者重启浏览器，再次登录又会切换回中文。

### Proposed Solution

希望在偏好设置里面增加一个默认语言设置，不想每次登陆后都要切换语言。有些外企还是希望用英文的，而我们的产品默认是中文，切换英文后，清空浏览器缓存或者重启浏览器，再次登录又会切换回中文。

**Comment by ibuler** [comment]
为什么要清空缓存

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13416

自己验证一下。

**Comment by liufei20151013** [comment]
> 为什么要清空缓存

难道广老师从来没清过浏览器缓存吗
