### ISSUE TITLE
v3升级v4.0后连不上mysql

### ISSUE THREAD

**Issue by lxq-max** [jumpserver/jumpserver#13663]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

系统：rocky9
配置：8C32G，SSD

### 🐛 缺陷描述

![image](https://github.com/jumpserver/jumpserver/assets/172480474/8b17d4e4-0dec-4722-9b83-7ec33b5e93c5)

连接mysql提示连接关闭
Receive Connection closed
Connection websocket closed

### 复现步骤

连接mysql提示连接关闭，账号密码正确，连接地址正确，网络端口放通
Receive Connection closed
Connection websocket closed

**Comment by BaiJiangJie** [comment]
看看 koko 日志有没有报错？

**Comment by flacce** [comment]
@BaiJiangJie 请问下
jms_magnus按照理解是数据库代理连接器，但是按照v4的脚本升级是没有拉取部署的
[magnus](https://github.com/jumpserver/magnus-release/l)在github的更新v4了（[首页文档](https://github.com/jumpserver/.github/blob/master/profile/README.md)[magnus地址](https://github.com/jumpserver/magnus)也放错了），DockerHub却没更新[magnus镜像](https://hub.docker.com/r/jumpserver/jms_magnus/tags)
实际使用只有部分数据库能连接，33061端口都没有映射出来，客户端连接方式是用不了的
在v4版本中该怎么才能正常连接使用数据库呢？

**Comment by LeeEirc** [comment]
@lxq-max 检查下相关 nginx 的配置，是否是 Websocket 连接无法保持。

**Comment by BaiJiangJie** [comment]
[v4.0 版本中已经移除了 jms_magnus 组件]
(https://github.com/jumpserver/jumpserver/issues/13615#issuecomment-2221888828)

**Comment by zhongjun96** [comment]
检查下连接的账号，昨晚升级了4.0。发现有些连接的账号被删除了，添加回来就能正常连接了。

**Comment by dhfsqxz** [comment]
> jms_magnus

建议继续支持jms_magnus
web端并不好用，我们所有人都是用的本地客户端

**Comment by fengmikaelson** [comment]
> @flacce [v4.0 版本中已经移除了 jms_magnus 组件] ([#13615 (comment)](https://github.com/jumpserver/jumpserver/issues/13615#issuecomment-2221888828))

但是健康检测一直在报magnus离线。。。是不是得手动删除

**Comment by BaiJiangJie** [comment]
是的，手动删除就好了。
