### ISSUE TITLE
[Question] 如何手动停止Celery系统任务

### ISSUE THREAD

**Issue by Ricardo-X-Chen** [jumpserver/jumpserver#13660]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS Linux 8

### 🤔 问题描述

系统任务如何手动停止 无法找到停止任务的地方
想通过Flower对task进行terminate操作，提示需要enable API without authentication
![Snipaste_2024-07-09_15-33-41](https://github.com/jumpserver/jumpserver/assets/117529739/d2f5ed2a-3406-4612-bc36-4d73b90af1b3)
![Snipaste_2024-07-09_15-34-41](https://github.com/jumpserver/jumpserver/assets/117529739/0f7d7c53-e8f3-4234-8907-57a46bc6aeb5)

### 期望结果

能停止系统任务

**Comment by BaiJiangJie** [comment]
管理员重新登录一下看看是不是可以解决 FLOWER_UNAUTHENTICATED_API 的问题。

**Comment by Ricardo-X-Chen** [comment]
> 管理员重新登录一下看看是不是可以解决 FLOWER_UNAUTHENTICATED_API 的问题。

 不行 还是一样报错

**Comment by BaiJiangJie** [comment]
没遇到过这个报错，不知道你是不是修改什么东西了。

config.txt 中配置 `FLOWER_UNAUTHENTICATED_API=true`，重启所有服务试试。

**Comment by Ricardo-X-Chen** [comment]
> 没遇到过这个报错，不知道你是不是修改什么东西了。
> 
> config.txt 中配置 `FLOWER_UNAUTHENTICATED_API=true`，重启所有服务试试。 这样可能会导致访问 flower 服务所有用户都可以访问了。

Flower 能revoke/terminate task了，但是进行revoke/terminate task操作后，task状态没有变化，jumpserver下的系统任务仍在运行，没有变化。故上周已进行重建jumpserver操作。

**Comment by BaiJiangJie** [comment]
好的，flower 库本身可能有点问题，如果出现任务确实无法停止，可以清除 Redis 后，重启服务。
