### ISSUE TITLE
[Question] 私有证书部署

### ISSUE THREAD

**Issue by jauer925** [jumpserver/jumpserver#13675]
### 产品版本

4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

[jumpserver_docker.sh.txt](https://github.com/user-attachments/files/16154486/jumpserver_docker.sh.txt)

### 🤔 问题描述
两个问题：
1.使用安装dokcer jumpserver 4.0完以后账号开启mfa以后手机安装ckey令牌以后口令一直不通过，一直提示令牌或者时间不对，我已经将容器时间和宿主机同步为一致了，

2.就是添加ssl协议访问我是修改/etc/nginx/nginx.conf文件以后添加一个server块复制下面的参数，然后web界面就一直无法登录了，下面127.0.0.1我换成了192.168.230.10也不行。

#详细安装步骤可以看附件脚本
#手动生成证书
openssl genrsa -des3 -out server.key 2048
openssl req -new -key server.key -out server.csr
cp server.key server.key.org
openssl rsa -in server.key.org -out server.key
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
#添加ssl协议访问

server {
    listen 443 ssl;
    ssl_certificate      cert/server.crt;
    ssl_certificate_key  cert/server.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_protocols TLSv1.1 TLSv1.2;
    add_header Strict-Transport-Security "max-age=63072000" always;
    client_max_body_size 5000m;
    location / {
        proxy_pass http://127.0.0.1;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

**Comment by jauer925** [comment]
脚本替换一下新的，上面那个脚本有问题。
[jumpserver_docker.sh.txt](https://github.com/user-attachments/files/16156521/jumpserver_docker.sh.txt)

**Comment by wojiushixiaobai** [comment]
脚本看得头疼，- https://github.com/jumpserver/Dockerfile/tree/master/allinone 参考这个项目写个 compose 吧

SSL 的问题可能是证书有问题。

OTP 的问题，使用 NTP 同步下宿主时间即可，容器不需要修改。

**Comment by jauer925** [comment]
FROM jumpserver/guacd:1.5.5-bookworm AS guacd 镜像拉不下来啊
error pulling image configuration: download failed after attempts=6: dial tcp 128.121.243.106:443: connect: connection refused

**Comment by wojiushixiaobai** [comment]
allinone 哪来的 guacd？你看错目录了？？
- https://github.com/jumpserver/Dockerfile/tree/master/allinone

**Comment by jauer925** [comment]
我是直接把你这个网站下面dockerfile.txt文件下来然后docker build成镜像行吗？

**Comment by wojiushixiaobai** [comment]
😂，自己构建吗，国内的话你得自己配置下代理了。。

**Comment by jauer925** [comment]
你叫我参考，- https://github.com/jumpserver/Dockerfile/tree/master/allinone 参考这个项目写个 compose 没懂你什么意思，我的pull的镜像有问题吗？dokcer pull jumpserver/jms_all:v4.0.0 这样下载的，现在使用http;//ip是可以登录只是mfa开启令牌一直通过不了，宿主机和容器时间我是用ntpdata做了时间同步没有问题

**Comment by wojiushixiaobai** [comment]
使用方法看 readme

**Comment by jauer925** [comment]
开启步骤没有问题，就是安装官方文档来操作的，输入令牌码怎么看后台日志啊，我想看看后台日志？

**Comment by wojiushixiaobai** [comment]
你最好查下你的时区，我本地测试了下确定没能复现你的问题。
或者你也可以尝试换一个 app 工具

**Comment by jauer925** [comment]
ckey令牌吗

**Comment by BaiJiangJie** [comment]
自己研究一下。
@jauer925

**Comment by jauer925** [comment]
你怎么安装的，可以发给我看看吗？
