### ISSUE TITLE
luna搜索资产问题

### ISSUE THREAD

**Issue by mrgaozy** [jumpserver/jumpserver#1367]
[简述你的问题]
当在luna搜索节点后，再点击节点会发现节点里面没有机器

##### 使用版本

Version 1.3.1-2 GPLv2.
##### 问题复现步骤
1. 搜索资产节点
2. 点击节点为空

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
Windows资产吗？

**Comment by ibuler** [comment]
已修复，有问题重新打开issue
