### ISSUE TITLE
[Bug] GPT 功能的设置页面文字错误

### ISSUE THREAD

**Issue by bubbleatgit** [jumpserver/jumpserver#13676]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker compose 部署

### 🐛 缺陷描述

![image](https://github.com/jumpserver/jumpserver/assets/7858776/fd7a898e-d9c3-449f-81ff-06704339d9b8)

这里的 `jumpserver 地址` 应该是写错了，应该是 `OpenAI API 地址`。

### 复现步骤

`ui/#/settings/features` 页面可以看到

**Comment by BaiJiangJie** [comment]
The issue will be fixed in v4.0.1.
