### ISSUE TITLE
SSL not Work

### ISSUE THREAD

**Issue by giledi92** [jumpserver/jumpserver#13687]
### Product Version

v 4

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu 22.04
jumpserver-installer-v4.0.0

### 🤔 Question Description

I have install a new version 4 with 1click installation, and I upload the SSL with these name (server.crt + server.key) /opt/jumpserver/config/nginx/cert/, and I change the config file /opt/jumpserver/config/config.txt to enable the SSL and this is the configuration 

# /opt/jumpserver/config/config.txt
 HTTPS_PORT=443
 SERVER_NAME=10.204.104.10
 SSL_CERTIFICATE=server.crt
 SSL_CERTIFICATE_KEY=server.key

/opt/jumpserver-installer-v4.0.0/./jmsctl.sh start

SSL not listening on port 443, only http 80 works only

**Comment by BaiJiangJie** [comment]
Restart the service using the `./jmsctl.sh restart` command.

**Comment by giledi92** [comment]
> Restart the service using the `./jmsctl.sh restart` command.

i try it without any result..

**Comment by wojiushixiaobai** [comment]
```sh
cat /opt/jumpserver/config/config.txt | egrep 'HTTPS_|SERVER_|SSL_'
```

**Comment by giledi92** [comment]
> ```shell
> cat /opt/jumpserver/config/config.txt | egrep 'HTTPS_|SERVER_|SSL_'
> ```

cat /opt/jumpserver/config/config.txt | egrep 'HTTPS_|SERVER_|SSL_'
 HTTPS_PORT=443
 SERVER_NAME=10.204.104.10
 SSL_CERTIFICATE=server.crt
 SSL_CERTIFICATE_KEY=server.key
JUMPSERVER_ENABLE_FONT_SMOOTHING=true
MAGNUS_SQLSERVER_PORT=14330
SERVER_HOSTNAME=jumpsrv1.alaan-dc.ly

**Comment by wojiushixiaobai** [comment]
```sh
cd /opt/jumpserver-installer-v4.0.0
./jmsctl.sh raw config | egrep 'HTTPS_|SERVER_|SSL_'
```

**Comment by giledi92** [comment]
> ```shell
> ```shell
> ./jmsctl.sh raw config | egrep 'HTTPS_|SERVER_|SSL_'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

![Screenshot 2024-07-12 201634](https://github.com/user-attachments/assets/0da04754-9033-49b5-bbe8-83dc9ef79783)
![Screenshot 2024-07-12 201712](https://github.com/user-attachments/assets/f75cf62e-4f39-4573-a6de-f61ad31aa7a8)

**Comment by wojiushixiaobai** [comment]
Remove extra spaces in front of key.
```sh
 HTTPS_PORT=443
…
```
fix to
```sh
HTTPS_PORT=443
…
```

**Comment by giledi92** [comment]
> Remove extra spaces in front of key.
> 
> ```shell
>  HTTPS_PORT=443
> …
> ```
> 
> fix to
> 
> ```shell
> HTTPS_PORT=443
> …
> ```

cool, works now,, 

Thanks
