### ISSUE TITLE
[Feature] 希望能够增加资产间的scp认证传输功能

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#13694]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

只是有这个想法，不知道能不能实现，需求场景如下：
1、用户同时拥有主机1的test1帐号和主机2的test2帐号的权限。
2、主机1到主机2之间有传输文件的需求。
3、test1帐号和test2帐号的密码都是堡垒机代管的，用户并不知道，实际也不会提供给用户。
4、问题：由于文件很大，而往往用户的带宽有限，如果先从主机1下载到用户本地再传输到主机2，势必效率会很低也会占用机房对外的带宽。虽然各主机用户间可以通过临时创建ssh密钥的方式无密码访问传输，但这种比较麻烦，且不及时清理也有安全隐患。
5、需求：能否有一种传输方式，主机1和主机2之间只需要通过堡垒机用户认证就可以传输数据的，即便这个传输是通过堡垒机转发的，效率也会高很多。

### 解决方案

1、用户**必须**同时拥有主机1的test1帐号和主机2的test2帐号的权限才可以在这两个主机用户间传输。
2、在主机1的test1帐号上执行如scp命令，如“scp [文件或目录名] -rp -l 100M -P[端口] [堡垒机用户]@[堡垒机地址]/test2@[主机2地址]:/home/test2/”，此时输入的密码是堡垒机用户的密码，就可以将主机1的test1账号下的文件或目录传送到主机2的test2的用户目录下。
3、如果用户没有主机2上的test2的权限，则传输不会成功，并显示“没有用户或没有权限”的错误提示。
4、以上只是一个猜想，如果能实现，实际的命令可能有所不同，甚至堡垒机有一个简单的专有命令，执行后弹出对话框等，只要能实现这个功能即可。

**Comment by BaiJiangJie** [comment]
config.txt 文件配置下面的配置项
```
ENABLE_VSCODE_SUPPORT=true
ENABLE_LOCAL_PORT_FORWARD=true
```
比如你想要从 a 主机的 a.txt 文件传输到 b 主机。

打开 b 主机的连接向导页面，复现 ssh 命令后面的连接信息。

`scp -P2222 a.txt  admin#root#a0ab3195-b007-43cf-a65a-4892cf8ea3f5@your-jumpserver-ip:/`

输入当前 JumpServer 用户的密码，就可以传输了。

需要主机 b 开启 sftp 协议。

**Comment by akang1798** [comment]
如果所有数据传输都过堡垒机，内网的传输势必会影响堡垒机的性能，且传输效率也不能达到最优。能不能堡垒机只作为一个认证中介，当建立信任之后，就只是主机之间的传输？

**Comment by BaiJiangJie** [comment]
设想不错，但是做不到。

**Comment by lhj18054979020** [comment]
为啥我升级了3.10.12 版本还是不行呢?
        - name: ENABLE_LOCAL_PORT_FORWARD
          value: "true"
        - name: ENABLE_VSCODE_SUPPORT
          value: "true"

image: docker.io/jumpserver/koko:v3.10.12

scp -P32222 a.txt admin#root#989738ac-4bec-4b2b-bb36-7f246d6cfe21@xxxx.com:/
admin#root#989738ac-4bec-4b2b-bb36-7f246d6cfe21: invalid user name
