### ISSUE TITLE
[Bug] jumpserver V4 移除magnus

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#13699]
### Product Version

v4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

使用 jumpserver V3 升级到 V4 社区版本已经移除了 Magnus 但是设置里还存在

### 🐛 Bug Description

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/26fecee5-b95b-420b-8710-a98798157341">

### Recurrence Steps

设置---组件设置----DB & Magnus 还是存在Magnus开关

**Comment by BaiJiangJie** [comment]
好的，感谢提交。

**Comment by BaiJiangJie** [comment]
The issue will be fixed in `v4.0.1`.
