### ISSUE TITLE
[Bug] 连接方式禁用 Web Gui 和远程桌面客户端对 web 资产无效

### ISSUE THREAD

**Issue by gerry-fit** [jumpserver/jumpserver#13697]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

版本：v3.10.12
浏览器：Chrome

### 🐛 缺陷描述

连接方式禁用 Web Gui 和远程桌面客户端后，远程应用依然可以连接

### 复现步骤

权限管理-连接方式 添加规则，连接方式选择 Web Gui 和远程桌面客户端，web 终端选择 web 资产连接

### 期望结果

连接方式禁用 Web Gui 和远程桌面客户端后，远程应用连接方式应同步禁用

**Comment by BaiJiangJie** [comment]
在这里，远程应用不包含在 Web GUI 中，如果要禁用远程应用，下拉选项中选择对应的远程应用。

**Comment by gerry-fit** [comment]
期望的是能控制远程应用的 web / 客户端拉起方式
