### ISSUE TITLE
[Question] 连接windows资产的时候，如果连接时间超过10秒，系统会默认为连接失败。请问这个时间可以修改吗？

### ISSUE THREAD

**Issue by hutang79** [jumpserver/jumpserver#13692]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

数据库和jumpserver分开部署，windows资产登录时启用了2FA认证，当超时未通过认证（超时批准2FA）会出现连接失败的情况

### 🤔 问题描述

在连接windows资产的时候，当连接时间超过10秒，系统会默认连接超时，此时会显示为连接中，需要重新连接方可连上。
lion容器日志中会提示：”[error] 录像文件小于1024字节，可判断连接失败，未能产生有效的录像文件“。请问这个超时时间可以修改吗？
![WechatIMG307](https://github.com/jumpserver/jumpserver/assets/103434519/291578f8-56bd-45a1-8d36-4c652a4bbb8a)
![WechatIMG305](https://github.com/jumpserver/jumpserver/assets/103434519/0a2faf70-d8e8-4645-b24d-d4de7c07a987)

### 期望结果

如何修改windows资产连接超时时间

**Comment by LeeEirc** [comment]
Windows资产是什么版本？你这个情况就是没有连接成功。如何启用 Windows 的 `2FA认证`，Lion 尚无这个认证方式。更详尽的日志，可以开启 DEBUG 日志，查看日志文件 `/data/jumpserver/lion/data/logs/guacd.log`

**Comment by BaiJiangJie** [comment]
目前 Windows 连接不支持 2FA 认证方式，所以调整连接超时时间也是无效的。

**Comment by hutang79** [comment]
可能我没解释清楚，我们在windows server服务器上安装了一个cs的安全软件，这个软件对于登录windows server启用了2FA，当我们通过jumpserver去连接该windows server的时候，需要进行2次验证，如果在10秒内没有完成2次验证（从发起连接-到批准连接），就会连接失败
![1720691876951](https://github.com/jumpserver/jumpserver/assets/103434519/e02b568f-5622-4a98-b6b5-ae5a6a781fde)

**Comment by LeeEirc** [comment]
开启 DEBUG 日志，查看下 guacd.log 的日志。建议还是把 cs 架构的软件审批超时时间设置大一些

**Comment by hutang79** [comment]
> 开启 DEBUG 日志，查看下 guacd.log 的日志。建议还是把 cs 架构的软件审批超时时间设置大一些

请问下怎么开启debug日志？

**Comment by LeeEirc** [comment]
配置文件  `/opt/jumpserver/config/config.txt` 修改或者添加以下参数
```
LOG_LEVEL=DEBUG
```
重启整个服务

**Comment by hutang79** [comment]
> 配置文件 `/opt/jumpserver/config/config.txt` 修改或者添加以下参数
> 
> ```
> LOG_LEVEL=DEBUG
> ```
> 
> 重启整个服务

我在11:01正常连接了windows server 2019资产10.53.3.7，在11:02连接资产10.53.3.8时，超时批准，jms_lion容器日志和guacd.log日志详见附件
[docker_log.txt](https://github.com/user-attachments/files/16188012/docker_log.txt)
[guacd.log](https://github.com/user-attachments/files/16188017/guacd.log)

**Comment by LeeEirc** [comment]
不清楚这个 2FA 软件的拦截原理，从 `guacd.log` 中只能判断连接响应超时。
翻看了下 Guacamole Server 依赖的 FreeRDP 源码，tcp 响应超时是 9 秒，这个无可配置选项。可能无法满足这个软件的拦截要求。

**Comment by hutang79** [comment]
> 不清楚这个 2FA 软件的拦截原理，从 `guacd.log` 中只能判断连接响应超时。 翻看了下 Guacamole Server 依赖的 FreeRDP 源码，tcp 响应超时是 9 秒，这个无可配置选项。可能无法满足这个软件的拦截要求。

好的，谢谢了！
这个CS的安全软件没有进行拦截，只是通过jumpserver连接windows server的时候，会有一个批准/允许的操作，告知我们从jumpserver登录这台windows server是否批准，手动批准过后就可以登录了。

**Comment by LeeEirc** [comment]
嗯，CS 安全软件的审批流程会造成响应时间的超时。
