### ISSUE TITLE
[Bug] 账号推送：推送参数 sudo 不能覆盖的问题

### ISSUE THREAD

**Issue by ZeroSSH** [jumpserver/jumpserver#13708]
### Product Version

v4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

系统: Kylin V10 SP3
内核：Linux 4.19.90
docker：27.0.3
docker-compose：docker-compose

### 🐛 Bug Description

在已存在账号，推送账号，推送参数不会覆盖，`/etc/sudoers`没有被修改。

### Recurrence Steps

1. 点击账号列表
2. 点击右侧，推送账号的推送
3. 修改sudo（`/bin/whoami,/usr/bin/touch`）
4. 确认

### Expected Behavior

/etc/sudoers应该被修改，用户应该被提权。

### Additional Information

- 个人理解：只有主机上新创建的账号会使用推送参数，如果已经存在了，推送参数不会覆盖。
- 不会影响生产，就是要通过其他去修改比较麻烦。
- 3.8.2版本曾经出现此类问题[https://github.com/jumpserver/jumpserver/issues/13433](url)

### Attempted Solutions

在新创建用户时，推送账号的sudo是可以被修改。

**Comment by BaiJiangJie** [comment]
是的，主机上新创建的用户可以设置，已存在的用户不会覆盖。

后面版本考虑支持一下。

**Comment by ZeroSSH** [comment]
Hi Bryan!

  感谢你的回信。非常感激你对 [账号推送<https://github.com/jumpserver/jumpserver/issues/13708>] 的关注。
[https://opengraph.githubassets.com/2d0f31fb426132625605f0141477f0f2c19a80053cc476dc1691dc7706a27d11/jumpserver/jumpserver/issues/13708]<https://github.com/jumpserver/jumpserver/issues/13708>
[Bug] 账号推送：推送参数 sudo 不能覆盖的问题 ・ Issue #13708 ・ jumpserver/jumpserver<https://github.com/jumpserver/jumpserver/issues/13708>
Product Version v4.0 Product Edition Community Edition Enterprise Edition Enterprise Trial Edition Installation Method Online Installation (One-click command installation) Offline Package Installat...
github.com



黄绍杰  Alern
Trainee | TESTING

Capgemini China | Beijing
Mob:+17763819184
***@***.***
[cid:e1b93ed4-81e4-438b-981a-1309290aaa3d]

________________________________
发件人: Bryan ***@***.***>
发送时间: 2024年7月15日 15:02
收件人: jumpserver/jumpserver ***@***.***>
抄送: ZeroSSH ***@***.***>; Author ***@***.***>
主题: Re: [jumpserver/jumpserver] [Bug] (Issue #13708)


是的，主机上新创建的用户可以设置，已存在的用户不会覆盖。

后面版本考虑支持一下。

―

**Comment by ZeroSSH** [comment]
非常感谢你对 [账号推送](https://github.com/jumpserver/jumpserver/issues/13708) 的关注。

**Comment by BaiJiangJie** [comment]
问题已修复，关注后续版本发布。
