### ISSUE TITLE
新增机器时，ansible自动触发推送系统用户报错，手动推送则正常。

### ISSUE THREAD

**Issue by idczuojun** [jumpserver/jumpserver#13700]
### 产品版本

jumpserver-v2.28.8

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [X] 源码安装

### 环境信息

CentOS Linux release 8.5.2111

### 🤔 问题描述

celery_ansible.log 日志如下，系统用户已经开启自动推送。
Task assets.tasks.push_system_user.push_system_user_to_assets[b18c7a56-bbf7-41b7-9f6d-f71abf54fac5] received
Task assets.tasks.push_system_user.push_system_user_to_assets[c2e28991-df27-445f-bb6f-64541330fe54] received
2024-07-12 16:33:49 [utils ERROR] DoesNotExist: <Asset: {UUID('8578a281-aae7-437b-a2c0-25792f5e7dad')}>
DoesNotExist: <Asset: {UUID('8578a281-aae7-437b-a2c0-25792f5e7dad')}>
2024-07-12 16:33:49 [utils ERROR] DoesNotExist: <Asset: {UUID('8578a281-aae7-437b-a2c0-25792f5e7dad')}>
DoesNotExist: <Asset: {UUID('8578a281-aae7-437b-a2c0-25792f5e7dad')}>
Task assets.tasks.asset_connectivity.test_asset_connectivity_util[cc5cb05e-ad39-4b1f-9248-1bf3a7853707] received
Task assets.tasks.push_system_user.push_system_user_to_assets[b18c7a56-bbf7-41b7-9f6d-f71abf54fac5] succeeded in 0.45257941191084683s: {}

PLAY [Test assets connectivity.] ***********************************************
Task assets.tasks.push_system_user.push_system_user_to_assets[c2e28991-df27-445f-bb6f-64541330fe54] succeeded in 0.46552954497747123s: {}

TASK [ping] ********************************************************************
ok: [kafka-005]

PLAY RECAP *********************************************************************
kafka-005                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
Task assets.tasks.asset_connectivity.test_asset_connectivity_util[cc5cb05e-ad39-4b1f-9248-1bf3a7853707] succeeded in 2.600361348129809s: {'contacted': {'kafka-005': {'ping': {...}}}, 'dark': {}, 'success': True}

**Comment by BaiJiangJie** [comment]
报错的原因是“8578a281-aae7-437b-a2c0-25792f5e7dad” 资产不存在了。

v2.28 已经停止维护了，建议升级到 v3 或者 v4 最新版本使用。
