### ISSUE TITLE
[Feature] 同时支持使用「用户名」或「邮箱」登录

### ISSUE THREAD

**Issue by ainuoyan** [jumpserver/jumpserver#13706]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

对接 LDAP 时，用户名一般为 xxx，邮箱一般为 xxx@xxx.com，用户登录时有人会习惯用 xxx 进行登录，有人会习惯用 xxx@xxx.com 进行登录

### 解决方案

希望可以同时支持使用「用户名」或「邮箱」登录

**Comment by ibuler** [comment]
好，已完成

https://github.com/jumpserver/jumpserver/pull/13713
