### ISSUE TITLE
[Bug] 登录时提示需要浏览器设置Cookie，但实际上浏览器已经勾选了「允许所有Cookie」

### ISSUE THREAD

**Issue by cangyin** [jumpserver/jumpserver#13711]
### Product Version

N/A

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

N/A

### 🐛 Bug Description

N/A

### Recurrence Steps

N/A

### Expected Behavior

N/A

### Additional Information

N/A

### Attempted Solutions

N/A

**Comment by cangyin** [comment]
关联 https://github.com/jumpserver/jumpserver/issues/7252

输入登录信息之后，出现这个 “设置你的浏览器支持cookie”页面，返回登陆页面，还需要再次输入账户信息。非常不方便。

**Comment by BaiJiangJie** [comment]
升级到最新版本。
