### ISSUE TITLE
[Question] 应用发布机初始化部署报错“Failed to deploy applet host"

### ISSUE THREAD

**Issue by zhengkang2020** [jumpserver/jumpserver#13718]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

- 系统：RockyLinux 9.4
- Docker：Docker version 27.0.3
- 浏览器：Microsoft Edge  126.0.2592.87

### 🤔 问题描述

新安装的Jumpserver v4.0.0 ，测试web资产需要添加远程应用发布机，按下图添加： 
- 远程发布机系统：windows server 2019
- 远程发布机状态：本地用户administrator、关闭防火墙、已安装OpenSSH

![image](https://github.com/user-attachments/assets/770c4de5-12de-445f-8699-a671574838d2)

- 账号列表：

![image](https://github.com/user-attachments/assets/9e4f8f1d-f425-4f9d-8555-4bf87b885e8c)

- 初始化部署：

![image](https://github.com/user-attachments/assets/6d5e6d66-daba-4a83-a604-773e609ba015)

**Comment by BaiJiangJie** [comment]
修改一下 `Core 服务地址`，保证发布机能访问到 Core。

**Comment by zhengkang2020** [comment]
谢谢，已解决！

**Comment by waixing2024** [comment]
> 修改一下`Core 服务地址`，保证发布机能访问Core。 <img alt="图像" width="773" src="https://private-user-images.githubusercontent.com/32935519/348964170-92ffc5c1-56db-44ac-8e2b-abefcdd7ab35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTg5NjAsIm5iZiI6MTcyNTExODY2MCwicGF0aCI6Ii8zMjkzNTUxOS8zNDg5NjQxNzAtOTJmZmM1YzEtNTZkYi00NGFjLThlMmItYWJlZmNkZDdhYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDE1Mzc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MDhiODFmYzdkM2UxYmJiMGZkMDVkYmM1OWEyNTU3MmU1ZDk3YjczMDNkMWIzOWMyODY4NjRjOGRlZWI3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jFhY9z9W84qByQJvsSirJC6SGFVJRbWeDOS3iNeq3ak">

您好，我修改了Core服务地址为JumpServer地址，还是报Failed to deploy applet host错误

**Comment by waixing2024** [comment]
JumpServer版本是4.1.0，Windows应用发布服务器版本是 windows server 2019 标准版

**Comment by waixing2024** [comment]
"msg": "Error downloading 'http://192.168.1.23/download/applets/Tinker_Installer_v0.1.7.exe' to 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\Tinker_Installer_v0.1.7.exe': The remote name could not be resolved: 'static.jumpserver.org'",
        "status_code": null,
        "url": "http://192.168.1.23/download/applets/Tinker_Installer_v0.1.7.exe"
    }
}
2024-09-01 00:17:19
TASK [fail] ********************************************************************
2024-09-01 00:17:19 fatal: [192.168.1.26]: FAILED! => {"changed": false, "msg": "Failed to deploy applet host"}
2024-09-01 00:17:19
PLAY RECAP *********************************************************************
192.168.1.26               : ok=5    changed=1    unreachable=0    failed=0    skipped=1    rescued=2    ignored=0
2024-09-01 00:17:19 Task terminal.tasks.run_applet_host_deployment[b4a44c85-6aa7-4fbc-8f28-4fbaf68edffc] succeeded in 110.76780369500011s: None

**Comment by waixing2024** [comment]
后面发现要开启互联网访问才能在线安装Tinker，不然一直都是失败的，安装成功后应用发布服务器可以连接，但是重启一下应用服务器及JumpServer服务器，应用发布服务器又无法连接了，感觉4.1版本的JumpServer还是不适合没有互联网的环境布署，准备回退到V3版本了
![9571725149988_ pic](https://github.com/user-attachments/assets/27ddaa77-86ca-41de-9d11-16a7e2112e28)

**Comment by ibuler** [comment]
为了减小安装包体积，二进制这下下载版不再打到容器里了，有需要可以下载下来手动放进去

**Comment by waixing2024** [comment]
> 为了减小安装包体积，二进制这下下载版不再打到容器里了，有需要可以下载下来手动放进去

您好，如果想放到容器里的话要怎样操作呢，具体的路径在哪里

**Comment by tianxiayu007** [comment]
> "msg": "Error downloading 'http://192.168.1.23/download/applets/Tinker_Installer_v0.1.7.exe' to 'C:\Users\Administrator\AppData\Local\Temp\Tinker_Installer_v0.1.7.exe': The remote name could not be resolved: 'static.jumpserver.org'", "status_code": null, "url": "http://192.168.1.23/download/applets/Tinker_Installer_v0.1.7.exe" } } 2024-09-01 00:17:19 TASK [fail] ******************************************************************** 2024-09-01 00:17:19 fatal: [192.168.1.26]: FAILED! => {"changed": false, "msg": "Failed to deploy applet host"} 2024-09-01 00:17:19 PLAY RECAP ********************************************************************* 192.168.1.26 : ok=5 changed=1 unreachable=0 failed=0 skipped=1 rescued=2 ignored=0 2024-09-01 00:17:19 Task terminal.tasks.run_applet_host_deployment[b4a44c85-6aa7-4fbc-8f28-4fbaf68edffc] succeeded in 110.76780369500011s: None

遇到同样的问题，内网地址解析到了static.jumpserver.org，不知道什么鬼，bug啊

**Comment by Arensi9801** [comment]
> > 为了减小安装包体积，二进制这下下载版不再打到容器里了，有需要可以下载下来手动放进去
> 
> 您好，如果想放到容器里的话要怎样操作呢，具体的路径在哪里

放到jms_web容器的/opt/download/applets/目录下

**Comment by SamourM** [comment]
in automation api url i used my domain name xyz.example.com instead of 127.0.0.1
