### ISSUE TITLE
[Question] mac下快捷切换会话 快捷键冲突

### ISSUE THREAD

**Issue by fengmikaelson** [jumpserver/jumpserver#13712]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

系统 mac
浏览器 chrome

### 🤔 问题描述

切换会话 → 快捷键 Option + Left / Option + Right

这个快捷键，在mac下，和快速移动命令按键冲突了，有办法调整吗？有时候想移动命令，结果标签页动了起来

**Comment by seaurching** [comment]
> ### 产品版本
> v4.0.0
> 
> ### 版本类型
> * [x]  社区版
> * [ ]  企业版
> * [ ]  企业试用版
> 
> ### 安装方式
> * [x]  在线安装 (一键命令安装)
> * [ ]  离线包安装
> * [ ]  All-in-One
> * [ ]  1Panel
> * [ ]  Kubernetes
> * [ ]  源码安装
> 
> ### 环境信息
> 系统 mac 浏览器 chrome
> 
> ### 🤔 问题描述
> 切换会话 → 快捷键 Option + Left / Option + Right
> 
> 这个快捷键，在mac下，和快速移动命令按键冲突了，有办法调整吗？有时候想移动命令，结果标签页动了起来
> 
> ### 期望结果
> _No response_
> 
> ### 补充信息
> _No response_

这个不光mac上有，windows也有，不管是谷歌还是edge都一样

**Comment by fengmikaelson** [comment]
> > ### 产品版本
> > v4.0.0
> > ### 版本类型
> > 
> > * [x]   社区版
> > * [ ]   企业版
> > * [ ]   企业试用版
> > 
> > ### 安装方式
> > 
> > * [x]   在线安装 (一键命令安装)
> > * [ ]   离线包安装
> > * [ ]   All-in-One
> > * [ ]   1Panel
> > * [ ]   Kubernetes
> > * [ ]   源码安装
> > 
> > ### 环境信息
> > 系统 mac 浏览器 chrome
> > ### 🤔 问题描述
> > 切换会话 → 快捷键 Option + Left / Option + Right
> > 这个快捷键，在mac下，和快速移动命令按键冲突了，有办法调整吗？有时候想移动命令，结果标签页动了起来
> > ### 期望结果
> > _No response_
> > ### 补充信息
> > _No response_
> 
> 这个不光mac上有，windows也有，不管是谷歌还是edge都一样

无解咯？

**Comment by ibuler** [comment]
没有道理啊，我们避开了 mac 自带的快捷键

**Comment by fengmikaelson** [comment]
> 没有道理啊，我们避开了 mac 自带的快捷键

事实上，按着option+左右，会移动单词，并且切换标签页。。。

**Comment by BaiJiangJie** [comment]
我也是 MacBook + Chrome，Option + Left/Right 可以左右移动会话卡片，你是不是有浏览器插件冲突了。

**Comment by fengmikaelson** [comment]
> 我也是 MacBook + Chrome，Option + Left/Right 可以左右移动会话卡片，你是不是有浏览器插件冲突了。
你误会啦。。。是可以移动 但是跟其他功能冲突了

option+left/right 还可以快速移动命令行的单词

**Comment by BaiJiangJie** [comment]
⌘ + ← or ⌘ + → 有冲突吗？

**Comment by fengmikaelson** [comment]
> #14022
> 
> 打算在 v4.2 上支持一下，切换窗口换成 Alt + Shift + 左右，Option + Shift + 左右（Mac）。
> 
> @fengmikaelson

太好了，期待一下
