### ISSUE TITLE
【BUG】WEB终端连接资产没有反应，请问是可能是什么原因造成的？

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1372]
VERSION：1.3
如图：
![image](https://user-images.githubusercontent.com/8511007/40637564-3587ee38-6338-11e8-8fd1-8a6585068ca9.png)

也没有看到有日志输出

**Comment by fevel** [comment]
可能是授权问题

**Comment by gengkeye** [comment]
@fevel 已经授权了，coco中也可以登录

**Comment by gengkeye** [comment]
发现是COCO的问题，回滚COCO后正常

**Comment by wojiushixiaobai** [comment]
@gengkeye 抱歉，是luna的问题，已经提交了新的更新文档，重新更新就好。需要各组件保存一致

**Comment by gengkeye** [comment]
@wojiushixiaobai 你好，luna目前最新版本仍然是1.3.1，请问怎么更新，直接pull源码吗

**Comment by wojiushixiaobai** [comment]
@gengkeye 对，保证组件的版本一致即可。

**Comment by gengkeye** [comment]
@wojiushixiaobai 按照操作还是没有反应～

**Comment by gian2008** [comment]
换一个浏览器，我也遇到过

**Comment by radiogit** [comment]
全部使用了1.3.1版本，依然存在这个问题，怎么解决呢？

**Comment by wojiushixiaobai** [comment]
@gengkeye @radiogit 参考[http://docs.jumpserver.org/zh/docs/faq_linux.html](url)，确定已经授权当前用户资产，并清理浏览器缓存或禁用浏览器缓存

**Comment by gengkeye** [comment]
找到了原因，是CDN解析造成的。

**Comment by xudongbo888** [comment]
cdn要怎么解决呢？楼主

**Comment by mach8686devops** [comment]
> cdn要怎么解决呢？楼主

同问这个问题
