### ISSUE TITLE
[Question] v4.0.0社区版 怎么添加PostgreSQL资产

### ISSUE THREAD

**Issue by ZhangTianyi-1998** [jumpserver/jumpserver#13722]
### 产品版本

4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

![image](https://github.com/user-attachments/assets/d2db473b-633d-471c-a661-44bf7bab4c19)

### 🤔 问题描述

我看更新日志社区版本支持了PostgreSQL 我在创建资产的时候没有看到
![image](https://github.com/user-attachments/assets/2618695f-8598-41df-a96d-e0eb325a7ead)
![image](https://github.com/user-attachments/assets/403c45dd-f8e2-437c-a83a-b3fe6055f328)

### 期望结果

能添加PostgreSQL

**Comment by SwarmKit** [comment]
还是不支持的，希望社区版能够支持！！！
![20240716092053](https://github.com/user-attachments/assets/912a53b2-ff8f-45e2-bc8a-3748bcffb5dd)
![20240716092042](https://github.com/user-attachments/assets/84165dae-01a1-4bdc-8199-8ad79b066b78)

**Comment by maninhill** [comment]
PostgreSQL 社区版会支持，已经修复了，会尽快发布。

**Comment by BaiJiangJie** [comment]
v4.0.1 会支持添加。

**Comment by BaiJiangJie** [comment]
The issue will be fixed in `v4.0.1`.
