### ISSUE TITLE
[Question] 一键部署 初始化数据库出问题

### ISSUE THREAD

**Issue by 15672927** [jumpserver/jumpserver#13728]
### Product Version

v4.0.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

failed to create network jms_net: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space

### 🤔 Question Description

failed to create network jms_net: Error response from daemon: invalid pool request: Pool overlaps with other one on this address space

**Comment by BaiJiangJie** [comment]
docker network 看一下，网段重复了。

**Comment by 15672927** [comment]
问题已解决。
