### ISSUE TITLE
[Bug] 站内信一直发组件健康检查警告

### ISSUE THREAD

**Issue by wdwnet** [jumpserver/jumpserver#13729]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v4.0.0

### 🐛 缺陷描述

Component health check warning
[Magnus]-localhost.localdomain-94920739d85f
The component is offline: [Magnus]-localhost.localdomain-94920739d85f
[Kael]-localhost.localdomain-71579ace061e
The component is offline: [Kael]-localhost.localdomain-71579ace061e

### 复现步骤

首页-站内信

**Comment by BaiJiangJie** [comment]
组件已经移除了，你在终端列表中删除就可以。

**Comment by wdwnet** [comment]
> 组件已经移除了，你在终端列表中删除就可以。

具体怎么操作，没有“终端列表”这个功能啊，还是要执行shell命令？

**Comment by BaiJiangJie** [comment]
终端列表直接删除就可以了。

或者，升级到 v4.0.1。
