### ISSUE TITLE
[Feature] 如何在 web terminal 搜索机器的时候 显示完整的目录树？ 

### ISSUE THREAD

**Issue by tanguofu** [jumpserver/jumpserver#13727]
### 产品版本

v4.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

如何在 web terminal 搜索资产的时候 显示 完整的目录树？

比如 demo 这里的 ：
<img width="535" alt="企业微信截图_17211125262031" src="https://github.com/user-attachments/assets/5f755800-37b3-4ce5-b247-cb79884c9128">

如何 在搜索的时候显示：
<img width="392" alt="企业微信截图_17211125501739" src="https://github.com/user-attachments/assets/4ab905c7-f264-4ec0-818a-345a44148956">

### 解决方案

期望能 搜索的结果 展示完整的上层目录的结构

**Comment by BaiJiangJie** [comment]
<img width="1814" alt="image" src="https://github.com/user-attachments/assets/c938f5ab-4160-4f24-89d6-78fc97d7346e">

资产树设置：异步加载为否，可以搜索到完整路径。

**Comment by tanguofu** [comment]
@BaiJiangJie  ok， thanks
