### ISSUE TITLE
JumpServer无法连接Mongodb

### ISSUE THREAD

**Issue by sweet-kkk** [jumpserver/jumpserver#13736]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

本地ubuntu部署的jumpserver，使用的微软浏览器，数据库登入无密码

### 🤔 问题描述

使用mongodb客户端，或者使用python调用都能够直接连上去，同时是没有密码的，但是使用jumpserver连接超时，一直连接不上
![屏幕截图 2024-07-17 083143](https://github.com/user-attachments/assets/d662be45-1552-49e3-89af-492c87c8b9ff)
![屏幕截图 2024-07-17 082749](https://github.com/user-attachments/assets/63cf2ef5-fb4b-4631-85ae-1dcfcd9d5776)

### 期望结果

能成功连接到mongodb

**Comment by Ewall555** [comment]
https://bbs.fit2cloud.com/t/topic/6788/2

**Comment by BaiJiangJie** [comment]
升级到 v4.0.1 版本解决。
