### ISSUE TITLE
[Bug] 控制台-用户列表-导入模版：缺少可填信息的提示（比如密码策略可以填写custom，没有给出相应的提示）。

### ISSUE THREAD

**Issue by liuxinxin2020** [jumpserver/jumpserver#13730]
### 产品版本

v3.0.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

内部测试环境

### 🐛 缺陷描述

需求场景：导入用户的同时导入密码，不通过邮件重置密码。
遇到问题：
1、根据下载的模版进行用户导入，各种尝试之后，依然没办法直接使用直接导入的密码进行登录；
2、经过各种咨询得知：密码策略处填写custom即可。
3、基于以上情况，建议在模版中给出提示，避免或减少不必要的困扰。

### 复现步骤

用户导入模版中缺少可填信息的提示，比如下图，没有提示密码策略可以填写custom。
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/c9a00554-8edb-42d6-a0ff-4dd187efc448">

### 期望结果

用户导入模版中给出每个参数可填信息的说明或提示。

**Comment by BaiJiangJie** [comment]
嗯，后面版本会考虑一下怎么提示比较好。

**Comment by jym503558564** [comment]
v4.2.0已优化模版提示
![image](https://github.com/user-attachments/assets/b36ee03b-5854-4737-a977-10752dca29bb)
