### ISSUE TITLE
[Bug] 开启 CAS 认证后登录系统时无法自动使用 CAS 认证

### ISSUE THREAD

**Issue by ainuoyan** [jumpserver/jumpserver#13735]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v4.0.0

### 🐛 缺陷描述

开启 CAS 认证后，登录堡垒机不会自动跳转 CAS 登录认证，而是直接打开内部登录页面，配置文件中添加 LOGIN_REDIRECT_TO_BACKEND=CAS 并重启 Jumpserver 也不生效，多次尝试均如此

### 复现步骤

开启 CAS 登录认证，然后访问堡垒机首页

### 期望结果

LOGIN_REDIRECT_TO_BACKEND 参数可以生效，可以自行配置是否自动跳转 CAS 登录页面

### 尝试过的解决方案

配置文件中使用 LOGIN_REDIRECT_TO_BACKEND=CAS 测试不起作用

**Comment by BaiJiangJie** [comment]
目前只有企业版可以配置直接跳转。

你可以按照下面的方式操作：
1. config.txt 配置文件修改：
`LOGIN_REDIRECT_TO_BACKEND=CAS`
`LOGIN_REDIRECT_MSG_ENABLED=false`

2. 使用 jmsctl 重启容器：
`./jmsctl restart`

3. 然后进入 core 容器，执行命令：
`mkdir /opt/jumpserver/apps/xpack`

4. 使用 docker 命令单独重启 jms_core 容器：
`docker restart jms_core`

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/13770/files

v4.1 之后直接修改配置文件就可以了。
