### ISSUE TITLE
jumpserver 更改权限后，推送用户失败，每次都要更新全部是不是太繁琐

### ISSUE THREAD

**Issue by comk88** [jumpserver/jumpserver#1373]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.0

##### 问题复现步骤
1. 将资产添加到一个新组---在新组中的用户测试登陆（失败）
2. 去系统用户 推送全部资源。。。
    ERROR：   fatal:[sg-adserver-http]: FAILED:=>{"changed": false, "msg": "Failed to lookup user fhf: 'getpwnam():name not found: fhf'"}
依旧登陆不上
3.手动登陆把目标机器 添加系统用户
推送成功

##### 具体表现[截图可能会更好些,最好能截全]
问：这个是否能支持 权限变动 自动推送 或者 更新单个资源推送权限呢？  这每次改了一点小权限都要全部更新，是不是不太好，还是我哪里理解的有问题，谢谢

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@comk88 如果权限设置正确，系统是会触发任务自动推送的，可以前台启动jumpserver查看详细日志
