### ISSUE TITLE
[Bug]  3.10.11 web登录界面 "1天免登录" 按钮没有了

### ISSUE THREAD

**Issue by thiszhao** [jumpserver/jumpserver#13744]
### Product Version

v3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

kubernetes v1.28.4
helm chat version 3.10.2
imags: ghcr.io/jumpserver/core-ce:v3.10.11 ...

### 🐛 Bug Description

从v3.10.2升级到v3.10.11后，web登录页面，"1天免登录" 按钮没有了，请问是官方有意去掉这块功能吗？
![Snipaste_2024-07-17_10-30-57](https://github.com/user-attachments/assets/f0b57580-85b1-43fb-88d9-f50c9165c84f)

### Recurrence Steps

web登录页面

**Comment by Ewall555** [comment]
安全设置->会话安全->会话在浏览器关闭时过期 这个选项在影响

**Comment by thiszhao** [comment]
> 安全设置->会话安全->会话在浏览器关闭时过期 这个选项在影响

谢谢，的确是这个选项，设置后，web登录页“自动登录”这个按钮了。
![Snipaste_2024-07-17_13-41-55](https://github.com/user-attachments/assets/802b0f31-f7e8-4c12-bc1b-a48b2ee1e9a2)

**Comment by BaiJiangJie** [comment]
1. `SESSION_EXPIRE_AT_BROWSER_CLOSE=true` 不显示自动登录。
2. `SESSION_COOKIE_AGE` 配置的时间就是自动登录的最大时间。
