### ISSUE TITLE
[Bug] web终端跳出异常图框，点击无效

### ISSUE THREAD

**Issue by supertobby** [jumpserver/jumpserver#13748]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [x] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/beac17b3-3d7b-4f08-8b3e-b241037f3416">

### 🐛 缺陷描述

web终端界面经常跳出这种方框，必须刷新界面才能去除，这样会导致已经链接的终端需要全部断开了，很麻烦

### 复现步骤

web终端中打开新的ssh连接，会偶尔出现，出现一次就要刷新网页，断开所有已经链接的ssh终端，很麻烦，会影响操作

**Comment by BaiJiangJie** [comment]
能稳定复现一下吗？打开 F12 看浏览器控制台有没有报错。

**Comment by jym503558564** [comment]
v4.0.1无法复现

**Comment by supertobby** [comment]
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/972ecc5b-6f18-46cb-ab4d-605f8a2bfcd2">
我这经常出现，出现的时候整个界面什么都点不了了，通常发生在我点击重新连接的时候，在web终端界面

**Comment by BaiJiangJie** [comment]
右击会话标签->重新连接，还是未能复现。

看 Chrome 的 Network 网络请求有异常的吗？

**Comment by supertobby** [comment]
有的时候web终端界面自动跳出这个框，有的时候是打开新终端时候，或者重新连接一个终端。
跳出这个框之后整个界面无法点击，所有的终端都无法使用，只能刷新浏览器了，这样所有终端都关闭了，非常影响使用。
感谢追踪这个bug

**Comment by BaiJiangJie** [comment]
health 和 exchange 两个 API 的 Response 截一下图。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
