### ISSUE TITLE
[Question] 配置CONNECTION_TOKEN_EXPIRATION后不是设置的时间，希望2小时后过期

### ISSUE THREAD

**Issue by ChenJustin666** [jumpserver/jumpserver#13759]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

# 版本号可以自己根据项目的版本修改
VERSION=v3.10.10

# 构建参数, 支持 amd64
TARGETARCH=amd64

# Compose
COMPOSE_PROJECT_NAME=jms
# COMPOSE_HTTP_TIMEOUT=3600
# DOCKER_CLIENT_TIMEOUT=3600
DOCKER_SUBNET=192.168.250.0/24

# 持久化存储
VOLUME_DIR=/data/jumpserver

# 时区
TZ=Asia/Shanghai

# MySQL
DB_HOST=172.19.
DB_PORT=3306
DB_USER=jump
DB_PASSWORD="wI#Fq9
DB_NAME=jumpserver

# Redis
REDIS_HOST=172.1
REDIS_PORT=6379
REDIS_PASSWORD=8URXPL2x3HZMi7x

# Core
SECRET_KEY=DEDRa5xTjJC72cY9dAvIRhQJ0WGXnjQWKk
BOOTSTRAP_TOKEN=5q5GXCcCxLI
LOG_LEVEL=ERROR
DOMAINS=

# Web
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_MYSQL_PORT=33061
MAGNUS_MARIADB_PORT=33062
MAGNUS_REDIS_PORT=63790

##
# SECRET_KEY 保护签名数据的密匙, 首次安装请一定要修改并牢记, 后续升级和迁移不可更改, 否则将导致加密的数据不可解密。
# BOOTSTRAP_TOKEN 为组件认证使用的密钥, 仅组件注册时使用。组件指 koko、guacamole

#feishu:
#  client_id: 'your_feishu_client_id'
#  client_secret: 'your_feishu_client_secret'
#  redirect_uri: 'https://<your_jumpserver_domain>/core/auth/feishu/callback/'

### 🤔 问题描述

services:
  core:
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        VERSION: ${VERSION}
        TARGETARCH: ${TARGETARCH}
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_core
    restart: always
    command: start web
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT:-33061}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT:-33062}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT:-63790}
      DOMAIN: ${DOMAIN:-}

     这下面写对了吗
      CONNECTION_TOKEN_ONETIME_EXPIRATION: 7200
      CONNECTION_TOKEN_EXPIRATION: 7200
      CONNECTION_TOKEN_REUSABLE: true
      CONNECTION_TOKEN_EXPIRATION_MAX: 7200
      CONNECTION_TOKEN_EXPIRATION: 7200

### 期望结果

连接数据库希望两个小时后断开，但是现在连接出现报错
![img_v3_02cs_31e31a35-0238-4f6a-9ad8-65cbfee4658g](https://github.com/user-attachments/assets/e3b4c7e3-210f-4476-a67d-42470a4c5988)

**Comment by ChenJustin666** [comment]
我是用docker-compose安装的

**Comment by ChenJustin666** [comment]
`services:
  core:
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        VERSION: ${VERSION}
        TARGETARCH: ${TARGETARCH}
    image: jumpserver/jms_core:${VERSION}
    container_name: jms_core
    restart: always
    command: start web
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      LOG_LEVEL: $LOG_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      REDIS_HOST: $REDIS_HOST
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT:-33061}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT:-33062}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT:-63790}
      DOMAIN: ${DOMAIN:-}
      CONNECTION_TOKEN_ONETIME_EXPIRATION: 7200
      CONNECTION_TOKEN_EXPIRATION: 7200
      CONNECTION_TOKEN_REUSABLE: true
      CONNECTION_TOKEN_EXPIRATION_MAX: 7200
      CONNECTION_TOKEN_EXPIRATION: 7200
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net
`这是我的部署方式

**Comment by BaiJiangJie** [comment]
配置完之后，Web Luna 连接页面，打开开关才支持复用 Token。

**Comment by ChenJustin666** [comment]
![image](https://github.com/user-attachments/assets/767f12aa-0120-4512-a29a-d9d4329df79c)
我在web页面开启后打开有问题，请问是哪里原因？

**Comment by BaiJiangJie** [comment]
看 core 日志的报错信息。

**Comment by zhangping940810** [comment]
![image](https://github.com/user-attachments/assets/408b80ef-18e9-4a8b-b2c6-22b55a0e25c1)

CONNECTION_TOKEN_REUSABLE=True
CONNECTION_TOKEN_REUSABLE_EXPIRATION=7200
