### ISSUE TITLE
[Bug] 全新安装的4.0，指定在新窗口打开连接的功能失效了

### ISSUE THREAD

**Issue by wqinf** [jumpserver/jumpserver#13758]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

系统是Rocky Linux 9.4 X64，最小化安装

### 🐛 缺陷描述

全新安装的jumpserver 4.0，指定在新窗口打开连接的功能失效了

### 复现步骤

偏好设置中，将连接默认打开方式设置为“新窗口”，然后在前台访问Windows资产

### 期望结果

默认打开方式设置为“新窗口”之后，前台访问Windows资产默认在新窗口打开，效果等同于在资产树右键选择在新窗口打开

**Comment by jym503558564** [comment]
按照上述操作，v4.0.1无法复现。
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/03bc50a5-25eb-4fb2-b471-f5c2cbe2fb70">

**Comment by wqinf** [comment]
> 按照上述操作，v4.0.1无法复现。 <img alt="image" width="1466" src="https://private-user-images.githubusercontent.com/40739051/350269504-03bc50a5-25eb-4fb2-b471-f5c2cbe2fb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzAyNDEsIm5iZiI6MTcyMTM2OTk0MSwicGF0aCI6Ii80MDczOTA1MS8zNTAyNjk1MDQtMDNiYzUwYTUtMjVlYi00ZmIyLWI0NzEtZjVjMmNiZTJmYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA2MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YjU0ODVmMWExZGNmMmEzZTdlZWY3YWFmNmM4OWE0YWY1ZDMzNTdkMDBlZjM2NTAzZGM5MTk5NDlhMzkyYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7SHUgzeHO2LKafl7uqeD3K0x8uM1jAqeVg3C09SfnfE">
> 
> 请问上述问题是否必现？

4.0.0版本必现，详见录屏文件，如果v4.0.1已修复的话，如何升级到v4.0.1？

https://github.com/user-attachments/assets/21e6f815-7bec-457b-90ee-c3c4d9501775

**Comment by BaiJiangJie** [comment]
个人设置的新窗口打开，是指在 Luna 页面点击左侧资产树中的资产时会在新窗口中刚打开，不是在我的资产页面就用单独的新窗口打开。

**Comment by wqinf** [comment]
> 个人设置的新窗口打开，是指在 Luna 页面点击左侧资产树中的资产时会在新窗口中刚打开，不是在我的资产页面就用单独的新窗口打开。

啊，可是这样的话，就要多点一步了，最早的时候提这个建议的时候，就是希望我的资产页面点击连接就直接用单独的新窗口打开，因为这样可以保证窗口直接最大化，取消左侧和顶部的内容。
