### ISSUE TITLE
在已授权的节点下添加资产后，系统用户未自动推送

### ISSUE THREAD

**Issue by jimingsong** [jumpserver/jumpserver#1375]
[在已授权的节点下添加资产后，系统用户未自动推送]

##### 使用版本
[ 1.3.1-2 ]

##### 问题复现步骤
1. [步骤1]
添加资产后，系统用户未自动推送。（确认对应系统用户已勾选'自动推送'）

##### 具体表现[截图可能会更好些,最好能截全]
以下为JMS日志：

##### 其他

![](http://images.cnblogs.com/cnblogs_com/jimingsong/1111724/o_444.png)
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
经测试不存在了，如还有问题请重新打开
