### ISSUE TITLE
[Bug] Razor 组件，在替换SSL 证书后，需要手动 copy 证书到容器中去

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#13767]
### 产品版本

V3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

离线安装包，v3.10.10.一键安装

### 🐛 缺陷描述

在修改完 SSL 证书后，使用 rdp 客户端连接 windows 资产的时候，报证书错误。需要手动 copy 到容器中去。
cd /opt/jumpserver/config/nginx/cert
docker cp server.key jms_razor:/opt/razor/
docker cp server.crt jms_razor:/opt/razor/

### 复现步骤

如上。通过 docker inspect jms_razor 发现映射路径有问题。
![WX20240718-192914](https://github.com/user-attachments/assets/5d244b24-f2ec-4464-b5df-36e3099e5e5b)
应该在目标文件夹那只到 /opt/razor/

### 期望结果

希望解决

**Comment by wojiushixiaobai** [comment]
参考 `Razor` 组件的 `entrypoint.sh`
```
cat /opt/razor/entrypoint.sh
```
```
#!/bin/bash
##

while [ "$(curl -I -m 10 -o /dev/null -s -w %{http_code} ${CORE_HOST}/api/health/)" != "200" ]
do
    echo "wait for jms_core $CORE_HOST ready"
    sleep 2
done

if [ -n "${LOG_LEVEL}" ]; then
  export WLOG_LEVEL=${LOG_LEVEL}
fi

if [ -n "${SSL_CERTIFICATE}" ] && [ -n "${SSL_CERTIFICATE_KEY}" ]; then
  cp -rf /opt/razor/cert/${SSL_CERTIFICATE} /opt/razor/server.crt
  cp -rf /opt/razor/cert/${SSL_CERTIFICATE_KEY} /opt/razor/server.key
  chmod 644 /opt/razor/server.crt /opt/razor/server.key
fi

if [ ! -f "/opt/razor/server.crt" ] && [ ! -f "/opt/razor/server.key" ]; then
  openssl req -x509 -newkey rsa:2048 -nodes -keyout /opt/razor/server.key -out /opt/razor/server.crt -days 3650 -subj "/C=CN/ST=Beijing/L=Beijing/O=JumpServer/OU=Dev/CN=dev" > /dev/null 2>&1
fi

if [ -n "${RDP_PORT}" ] && [ "${RDP_PORT}" != "3389" ]; then
  sed -i "0,/Port = /{s/Port = .*/Port = ${RDP_PORT}/}" /opt/razor/config.ini
fi

echo
date
echo "Razor Version $VERSION, more see https://www.jumpserver.org"
echo "Quit the server with CONTROL-C."
echo

razor /opt/razor/config.ini
```

**Comment by wxcen** [comment]
所以问题是什么了？ 如果说脚本没问题的话，但是现实就是遇到了替换证书之后每次都需要手动处理证书的问题。看最终的结果就是有问题的。

**Comment by wojiushixiaobai** [comment]
你的问题请参考下列代码
```sh
if [ -n "${SSL_CERTIFICATE}" ] && [ -n "${SSL_CERTIFICATE_KEY}" ]; then
  cp -rf /opt/razor/cert/${SSL_CERTIFICATE} /opt/razor/server.crt
  cp -rf /opt/razor/cert/${SSL_CERTIFICATE_KEY} /opt/razor/server.key
  chmod 644 /opt/razor/server.crt /opt/razor/server.key
fi
```

你可能会有新的疑问，这里一并解答：
1.  `SSL_CERTIFICATE` 与 `SSL_CERTIFICATE_KEY` 是什么意思
答：参考 `/opt/jumpserver/config/config.txt` 和 https://docs.jumpserver.org/zh/v3/installation/proxy/

2. 为什么需要定义 `SSL_CERTIFICATE` 与 `SSL_CERTIFICATE_KEY`
答：因为我们事先并不知道用户的证书名称，目录里面可能存在多个证书文件。

如果以上回答无法解决你的问题，请按照你现有的逻辑自行处理即可。

**Comment by wxcen** [comment]
SSL_CERTIFICATE 和 SSL_CERTIFICATE_KEY 都是有配置的，不然就算是手动 docker copy 也不知道是什么证书文件。现在证书配置都是正确，core 组件都能够通过域名访问。

**Comment by wxcen** [comment]
config.txt 里面配置上述说的文件名称。

**Comment by wojiushixiaobai** [comment]
请提交可以复现此问题的步骤或者环境，否则按照上一个回复处理即可。
