### ISSUE TITLE
postgresql报root帐户不存在

### ISSUE THREAD

**Issue by haohetao** [jumpserver/jumpserver#13769]
### Product Version

4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu 24.04

### 🐛 Bug Description

>jms_postgresql  | 2024-07-19 08:36:29.014 CST [63481] FATAL:  role "root" does not exist

这条错误每秒出现一次

### Recurrence Steps

开机就有

**Comment by jym503558564** [comment]
忽略，不影响使用。
