### ISSUE TITLE
[Question] v4.0 版本后社区版镜像 tag 后缀导致的镜像拉取失败问题

### ISSUE THREAD

**Issue by Fallen-Breath** [jumpserver/jumpserver#13760]
### 产品版本

v3.10.11, v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

- AlmaLinux 9.4 x86_64
- Docker client / server 26.1.3
- 已正确配置 Docker Registry Mirrors

### 🤔 问题描述

JumpServer v4.0 后社区版的 docker 镜像 tag 多了个 `-ce` 后缀，导致 jumpserver-installer 里的 docker compose 里定义的镜像无法正常拉取

installer 里的相关代码：https://github.com/jumpserver/installer/blob/e034874a9d3800d46d53c734f50d1073d5cf7163/compose/core.yml#L3C34-L3C61

DockerHub 里的 tag 例子（https://hub.docker.com/r/jumpserver/core/tags 、https://hub.docker.com/r/jumpserver/koko/tags ）。注意 v3 v4 版本之间的 tag 后缀差异

![image](https://github.com/user-attachments/assets/04dc693f-4b8d-4b2f-831f-ee644e1d0434)

问题触发方式：使用 v3.10.11 的 jumpserver-installer，执行 `jmsctl check_update` 指令，会出现拉镜像的失败

![image](https://github.com/user-attachments/assets/cb732249-4945-4c5f-afab-005e53ca4190)

### 期望结果

Docker 镜像可拉取成功

### 补充信息

把配置文件 `/opt/jumpserver/config/config.txt` 的 `DOCKER_IMAGE_MIRROR` 设置成 `1`，也会出现一样的问题

![image](https://github.com/user-attachments/assets/e7fc01a2-536e-4262-82b2-510aa2fd6275)

**Comment by HOLYshitIjustWANTaNAMEFFFFFFFuck** [comment]
vim /opt/jumpserver-installer-v4.0.1/scripts/utils.sh
edit func get_images()

echo "jumpserver/core:${VERSION}" -> echo "jumpserver/core:${VERSION}-ce"
echo "jumpserver/koko:${VERSION}" -> echo "jumpserver/koko:${VERSION}-ce"
echo "jumpserver/lion:${VERSION}" -> echo "jumpserver/lion:${VERSION}-ce"
echo "jumpserver/chen:${VERSION}" -> echo "jumpserver/chen:${VERSION}-ce"
echo "jumpserver/web:${VERSION}" -> echo "jumpserver/web:${VERSION}-ce"

vim /opt/jumpserver-installer-v4.0.1/compose/core.yml
image: ${REGISTRY:-docker.io}/jumpserver/core:${VERSION} -> image: ${REGISTRY:-docker.io}/jumpserver/core:${VERSION}-ce

vim /opt/jumpserver-installer-v4.0.1/compose/koko.yml
image: ${REGISTRY:-docker.io}/jumpserver/koko:${VERSION} -> image: ${REGISTRY:-docker.io}/jumpserver/koko:${VERSION}-ce

vim /opt/jumpserver-installer-v4.0.1/compose/lion.yml
do the same thing

vim /opt/jumpserver-installer-v4.0.1/compose/chen.yml
do the same thing

vim /opt/jumpserver-installer-v4.0.1/compose/web.yml
do the same thing

finally:
cd /opt/jumpserver-installer-v4.0.1
./quick_start.sh

it works ok for me.

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v4/installation/setup_linux_standalone/online_upgrade/

下载最新的 installer 进行升级。

@Fallen-Breath

**Comment by Fallen-Breath** [comment]
使用 v4 版本的 intaller 里面的 `jmsctl.sh` 进行升级，可成功拉取带 `-ce` 后缀的镜像
