### ISSUE TITLE
[Question] rdp协议无法访问window11

### ISSUE THREAD

**Issue by minskiter** [jumpserver/jumpserver#13774]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Ubuntu 22.04
Chrome
Docker部署 App版本v4.0.1

### 🤔 问题描述

使用rdp协议访问windows server 2019正常，但是访问windows 11一直提示：
连接错误
The remote desktop server does not appear to exist, or cannot be reached over the network.
测试使用ssh访问该服务器是正常的（账户密码正确）
<img width="430" alt="image" src="https://github.com/user-attachments/assets/c283ef44-8ed1-4416-b9fe-85f132359427">

### 期望结果

正常连接windows 11

**Comment by BaiJiangJie** [comment]
不支持连接 windows 10、11 操作系统。

**Comment by BaiJiangJie** [comment]
在目标 Windows 机器上，确保远程桌面已启用且允许连接。

**Comment by minskiter** [comment]
> 在目标 Windows 机器上，确保远程桌面已启用且允许连接。

![image](https://github.com/user-attachments/assets/1b0eb823-3757-4cb8-826a-d8a2e9eea3ec)
是的

**Comment by minskiter** [comment]
Allow connetions only from computers running Remote Desktop with Network Level Authentication. 无论是否勾选都无法连接

**Comment by BaiJiangJie** [comment]
<img width="906" alt="image" src="https://github.com/user-attachments/assets/308d0937-a940-4ee4-8181-f309d07e848e">
这三种内置的 Windows 类型ping tai平台，都试一下。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
