### ISSUE TITLE
[Bug] Passkey 无法注册

### ISSUE THREAD

**Issue by Karlatemp** [jumpserver/jumpserver#13778]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机 Linux, 使用一键安装, 进行过版本升级

### 🐛 缺陷描述

Passkey 不能注册

Bitwarden:
![image](https://github.com/user-attachments/assets/cae85d86-848d-43a7-8aea-da0a0b581292)

远程桌面连接:

![image](https://github.com/user-attachments/assets/5b09a29f-79a8-4b70-bde6-5af7f7507ad4)

![image](https://github.com/user-attachments/assets/d9f56277-31f1-4103-bc98-7764835cf041)

### 复现步骤

1. 系统设置开启 Passkey 功能
2. 切换到个人界面添加 Passkey

### 期望结果

Bitwarden 可以录入，远程桌面连接可以录入

### 补充信息

远程桌面:

```
Google Chrome	126.0.6478.128 (Official Build) (64-bit) (cohort: Control) 
Revision	ae45fc71651ae70786a0af5755dd747eb2ac1f9d-refs/branch-heads/6478@{#1593}
OS	Windows 10 Version 22H2 (Build 19045.4046)
JavaScript	V8 12.6.228.21
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Command Line	"C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
```

本地:

```
Host Name:                 DESKTOP-I7HHF8V
OS Name:                   Microsoft Windows 10 Pro N
OS Version:                10.0.19045 N/A Build 19045
System Manufacturer:       LENOVO
System Model:              21HX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 2 GenuineIntel ~2600 Mhz
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
```

**Comment by BaiJiangJie** [comment]
看报错是 token 字段长度有点短。

**Comment by BaiJiangJie** [comment]
测试不支持 Bitwarden 的 Passkey。

**Comment by Karlatemp** [comment]
直接关闭此议题是否可以认定为不考虑支持？token字段过短也不会修复？
