### ISSUE TITLE
[Feature] 客户端拉起支持设置 Token 复用

### ISSUE THREAD

**Issue by 92icu** [jumpserver/jumpserver#13773]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

当前数据库资产使用客户端连接操作时，很容易就出现 Token 过期的报错，稍微离开一会或者编写个复杂 sql 就需要重连，使用体验不佳
![image](https://github.com/user-attachments/assets/aa91c8e0-c37c-4f78-8116-68b525840fc3)

### 解决方案

方案一：
类似 RDP 客户端连接，在高级选项中添加连接复用的选项

![image](https://github.com/user-attachments/assets/12e242df-fd46-47f9-8faa-cd823fee3aa8)

方案二：
添加配置参数，在配置文件中全局开启/关闭

**Comment by BaiJiangJie** [comment]
使用 DB Guide 方式可以设置打开。跟 RDP 连接类似。

**Comment by 92icu** [comment]
DB Guide 的方式是可以，但是能用客户端拉起肯定不想自己去一个个复制粘贴的，动不动就过期客户端的方式就很鸡肋了，所以希望能满足一下这个场景

**Comment by BaiJiangJie** [comment]
是的，必须使用 DB Guide。
