### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hectorchou** [jumpserver/jumpserver#13779]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

1.docker部署，从v3.8.1升级到v3.10.11
2.然后再从v3.10.11升级到v4.0.1
3.16C32G虚拟机 centos 7.9 x86环境

### 🐛 缺陷描述

1.每小时定时会报错：The component is offline: [Tinker]-测试-XXX-发布机-tsuh1AM
2，组件设置中，确实看到了此组件离线，且无法删除删除，提示“被其他对象关联，无法删除
![3](https://github.com/user-attachments/assets/24ed680d-ff08-4fd1-9747-058028b39125)
![2](https://github.com/user-attachments/assets/ae0c42e8-c309-40dc-bc10-f1366a1834f0)
![1](https://github.com/user-attachments/assets/f4bbca9e-e1ed-40d0-bdf1-433000721454)
”

### 复现步骤

docker ps 没有thinker相关组件的容器
![图片](https://github.com/user-attachments/assets/30ed09d0-118d-407f-b4da-359d62939f13)

### 期望结果

不再报错和发送消息，组件是否可以删除

**Comment by Ewall555** [comment]
到远程应用发布机中查看你配置的发布机，可能有两台，其中一台离线了
