### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by shanjunmei** [jumpserver/jumpserver#13783]
### Product Version

4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

4.0.1 的安装包中没有jmsctl.sh 文件了，咋升级上去，现在是版本4.0.0 

### 🤔 Question Description

4.0.1 的安装包中没有jmsctl.sh 文件了，咋升级上去，现在是版本4.0.0

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v4/installation/setup_linux_standalone/online_upgrade/
升级文档。
