### ISSUE TITLE
ssh直连koko支持同名账号缓存密码

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#13789]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

目前针对此功能只有web登录后，使用ssh连接到koko上才能进行免密
需要web、ssh方式都可以缓存用户登录密码使用同名用户免密登录
![image](https://github.com/user-attachments/assets/8f052982-8d9a-43af-831b-e462ec236067)

### 解决方案

需要能够单独使用任意一种连接方式（web、ssh）就能缓存用户密码，实现同名账号的免密登录

**Comment by BaiJiangJie** [comment]
默认应该支持。

**Comment by jym503558564** [comment]
LDAP用户，Web或者SSH登录，密码都会在redis进行缓存user_sect_{user_id} ，默认时间是1天。连接资产时，选择同名账号，在v3.10.12测试，验证通过，无法复现该问题。
