### ISSUE TITLE
[Bug] 连接阿里云mongodb失败"error: exec: "mongosh": executable file not found in $PATH"

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#13780]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

使用jumpserver直连mongodb

### 🐛 缺陷描述

连接阿里云mongodb失败：“error: exec: "mongosh": executable file not found in $PATH”
mongodb版本：4.0

### 复现步骤

在jumpserver上配置直连mongodb副本集集群其中一个节点

### 期望结果

无

### 补充信息

无

### 尝试过的解决方案

无

**Comment by Ewall555** [comment]
更新至v4.0.1

**Comment by BaiJiangJie** [comment]
Fixed in v4.0.1.

**Comment by Lynxhide** [comment]
收到，谢谢
