### ISSUE TITLE
[Bug] Wrong timezone on emails

### ISSUE THREAD

**Issue by dbrifox** [jumpserver/jumpserver#13784]
### Product Version

4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Timezone is set to America/Sao_Paulo
![image](https://github.com/user-attachments/assets/864809cc-105d-4474-97a2-ce97ecc0ec25)

### 🐛 Bug Description

Login alert email is not following set timezone. 

![image](https://github.com/user-attachments/assets/a8979a66-4d2e-46c1-b3c0-4824a00d8d26)

### Recurrence Steps

All emails

**Comment by BaiJiangJie** [comment]
You need to configure the `TIME_ZONE` configuration item in `/opt/jumpserver/config.txt`.

Such as: TIME_ZONE=Asia/Shanghai

**Comment by dbrifox** [comment]
I'm using docker all in one deployment method, there's no "config.txt" file, I believe timezone is set on container env file variable.

**Comment by dbrifox** [comment]
Also related to timings there's some chinese characters being displayed on column "Duration" on screen Asset sessions > Historical sessions

![image](https://github.com/user-attachments/assets/991c4cb3-4fed-4a29-bdbe-71d12f145f0d)

**Comment by dbrifox** [comment]
Exported data from report is also showing wrong timezone (GMT +08)

![image](https://github.com/user-attachments/assets/408b8535-beeb-433c-9316-0dee943d8296)

**Comment by BaiJiangJie** [comment]
Can you install it in the following way? 
Because for long-term use, it is not recommended to use All-in-One.

https://www.jumpserver.com/docs/installation

After installation, change the time zone and check if the issue still exists?

**Comment by BaiJiangJie** [comment]
1. Change to the following directory:
`cd /opt/Dockerfile/allinone`

2. Edit the .env file:
`vi .env`
```
TZ=America/Sao_Paulo
TIME_ZONE=America/Sao_Paulo
```

3. Edit the docker-compose.yml file:
`vi docker-compose.yml`
<img width="685" alt="image" src="https://github.com/user-attachments/assets/70e06fc2-b539-4603-a7a5-e5cebd4e3912">

**Comment by dbrifox** [comment]
After adding TIME_ZONE variable it seems to be fixed, thank you!

The only issue that remains is cosmetic, Chinese characters on session offline screen.
https://github.com/jumpserver/jumpserver/issues/13784#issuecomment-2242949414

**Comment by BaiJiangJie** [comment]
What version are you using? I don't have this problem in my environment.

**Comment by dbrifox** [comment]
4.0

**Comment by BaiJiangJie** [comment]
You need to manually switch the language settings. 
Chinese will be used by default. This problem will be fixed in the next version.

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/4259

**Comment by BaiJiangJie** [comment]
Please stay tuned for future version releases.
