### ISSUE TITLE
[Bug] Client Executable is detected as "Trojan.Linux.Coinminer" / Virustotal

### ISSUE THREAD

**Issue by derkahless** [jumpserver/jumpserver#13788]
### Product Version

2.1.3

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

-

### 🐛 Bug Description

Checking the actual "JumpServer-Client-Installer-x86_64.msi" via Virustotal results in a finding from the Google engine:

https://www.virustotal.com/gui/file/ade2c4f796ff6371ec59e01f853f991c85ab812738dca329c8b2cb54bc09feda/detection

![grafik](https://github.com/user-attachments/assets/0732cd13-d5f4-4657-b555-79e8be756727)

Maybe this is whitelistable.

### Recurrence Steps

Check files via Virustotal

### Expected Behavior

No finding

### Additional Information

-

### Attempted Solutions

-

**Comment by LeeEirc** [comment]
the windows client do not be packaged with certificate, it must be virus false positive.

**Comment by derkahless** [comment]
sure, this is a false positive, but should be fixed with google to get a 100% reputation.

**Comment by LeeEirc** [comment]
We have been using the relevant rules. this false positive can be ignored.
If you have any doubt, you can check the [client repository](https://github.com/jumpserver/clients)
