### ISSUE TITLE
[Bug] ldap导入的用户，在详情中显示异常

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#13781]
### 产品版本

v4.0.0,v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

标准环境

### 🐛 缺陷描述

ldap 导入一个用户后，在用户列表中显示为用户，在用户详情界面中，显示的系统角色为系统审计员，v4.0.0,v4.0.1这两个发行版中稳定复现，是社区版本中稳定复现，企业版测试未见异常

### 复现步骤

1.导入一个ldap用户
2.查看用户列表，系统角色为用户
3.点击用户详情，显示系统角色为系统审计员，且该选项没有被下拉列表识别，可以多选，重复选如下
![1721378343073](https://github.com/user-attachments/assets/e757d863-94a8-4aae-b535-c5862ecfed63)

### 期望结果

正常显示，正常被下拉列表识别

### 补充信息

f12 中返回的 response 正常，其他未检查
![1721378661148](https://github.com/user-attachments/assets/eccc07a8-54b7-4e04-a27a-2ef7e87ec01b)

**Comment by BaiJiangJie** [comment]
嗯，目前显示有问题。

**Comment by BaiJiangJie** [comment]
fix: https://github.com/jumpserver/lina/commit/65ed7217cd708d767c0ff29ce42c942f1c95743f

**Comment by Ewall555** [comment]
已有相关commit
