### ISSUE TITLE
[Bug] LDAP “用户导入” 搜索框手动点击搜索用户按钮闪退

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#13785]
### 产品版本

3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

LDAP “用户导入” 搜索框手动点击搜索用户按钮闪退

### 🐛 缺陷描述

LDAP “用户导入” 搜索框手动点击搜索用户按钮闪退

### 复现步骤

1、输入搜索用户，手动点击查询
![image](https://github.com/user-attachments/assets/3a5f25f2-e20f-4cc9-90a5-e96965c595c1)

2、直接退出搜索窗口，可以手动多点几次搜索，即可复现

**Comment by BaiJiangJie** [comment]
看一下控制台报什么错？

**Comment by jym503558564** [comment]
连续点击，鼠标第二次点击可能在表单外了，所以会被关闭。
