### ISSUE TITLE
[Bug]  在通知设置中无法使用邮件功能，debug查看填入的密码没有向后端传输，测试邮件一直提示 {"error":"5.7.1 Authentication required"}

### ISSUE THREAD

**Issue by freshgeek** [jumpserver/jumpserver#13782]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver-jms_all:v4.0.0 安装

### 🐛 缺陷描述

[Bug]  在通知设置中无法使用邮件功能，debug查看填入的密码没有向后端传输，测试邮件一直提示 {"error":"5.7.1 Authentication required"}

### 复现步骤

[Bug]  在通知设置中无法使用邮件功能，debug查看填入的密码没有向后端传输，测试邮件一直提示 {"error":"5.7.1 Authentication required"}

**Comment by BaiJiangJie** [comment]
测试的时候输入密码，打开控制台，看一下API请求数据，负载和响应。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
