### ISSUE TITLE
v4.0.0不支持向资产中添加k8s资源吗?

### ISSUE THREAD

**Issue by puleiC** [jumpserver/jumpserver#13792]
### 产品版本

v4.0.0-ce

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

没有看到资产管理有k8s相关的配置呢

### 🐛 缺陷描述

![1721642696653](https://github.com/user-attachments/assets/e1e26bbd-cf7c-49c1-ad24-e4e2890af15d)

### 复现步骤

没有看到资产管理有k8s相关的配置呢

**Comment by BaiJiangJie** [comment]
升级到 v4.0.1 就有了。
