### ISSUE TITLE
[Bug] 调起本地filezilla没法上传文件

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#13796]
### 产品版本

v3.10.11

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.11单机版，企业安装包

### 🐛 缺陷描述

ftp协议调起本地filezilla没法上传下载文件，winscp和xftp是可以正常上传文件的

### 复现步骤

点击拉起是可以，但是没法上传，显示“认证失败，严重文件传输错误”
多个filezilla版本都试过
![image](https://github.com/user-attachments/assets/d5d82cbc-9c24-405f-af15-4970dffbd563)

**Comment by jstbw** [comment]
空文件可以上传，有内容的不行

**Comment by BaiJiangJie** [comment]
show koko.log.

**Comment by BaiJiangJie** [comment]
认证没有成功，使用向导模式连接。

**Comment by jstbw** [comment]
那为啥一开始能自动连接，也能选择到路径-------- 原始邮件 --------发件人： Bryan ***@***.***>日期： 2024年7月24日周三 15:55收件人： jumpserver/jumpserver ***@***.***>抄送： jstbw ***@***.***>, Author ***@***.***>主    题： Re: [jumpserver/jumpserver] [Bug] 调起本地filezilla没法上传文件 (Issue #13796)
认证没有成功，使用向导模式连接。

**Comment by BaiJiangJie** [comment]
应该是你的认证信息变了。
