### ISSUE TITLE
[Bug] 连接k8s会打开新的浏览器标签页

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#13793]
### Product Version

3.10.12

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Linux安装环境 X86系统，单机部署

### 🐛 Bug Description

点击连接k8s时，会打开新的浏览器标签页

### Recurrence Steps

1、连接k8s
![1](https://github.com/user-attachments/assets/9193c010-763c-4090-8f89-3d180e632146)

2、打开了新的标签页
![2](https://github.com/user-attachments/assets/be020da8-dd4b-4dbd-bf5b-6f5ea15d7280)

**Comment by Ewall555** [comment]
正常逻辑
