### ISSUE TITLE
[Bug] Wrong system role displayed on update user screen

### ISSUE THREAD

**Issue by dbrifox** [jumpserver/jumpserver#13794]
### Product Version

4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Docker all in one

### 🐛 Bug Description

User details screen shows the correct system role
![image](https://github.com/user-attachments/assets/a254cdee-f81c-4b88-be0f-874456ee6bfd)

Update user screen shows wrong system role (system auditor instead of user)
![image](https://github.com/user-attachments/assets/b4e5ebc0-499f-419f-a395-18a6e7e1de00)

### Recurrence Steps

Always

**Comment by Ewall555** [comment]
https://github.com/jumpserver/jumpserver/issues/13781#issuecomment-2241938103

**Comment by BaiJiangJie** [comment]
Fixed in v4.0.2.

**Comment by BaiJiangJie** [comment]
Please stay tuned for future version releases.
