### ISSUE TITLE
[Bug] 资产授权设置了账号模板添加后再次更新授权添加资产时没有推送模板账号

### ISSUE THREAD

**Issue by haiyu1234** [jumpserver/jumpserver#13798]
### Product Version

v3.10.10

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

主备 国内国外两套

### 🐛 Bug Description

（国内）在资产授权操作的时候我设置了账号模板添加（也就是说可以自动推送）我点击提交后他第一次是会推送账号（账号那里会变成绿色，但也仅仅是第一次的时候），但是我更新这个资产授权，往里面添加资产的时候（模板账号变成白色），他不会把那个账号模板的账号推送到我新添加的资产里，我必须要在账号里重新添加账号模板然后点击提交才能够推送账号

### Recurrence Steps

（国内）创建两个资产（都别填写账号让资产授权自动添加），创建一个资产授权，然后添加一个资产和指定账号，再指定账号里添加一个账号模板，点击提交之后会发现这个资产会推送了这个账号，然后再次更新这个资产授权，再添加一个别的资产，点击提交，然后去别的资产下看会发现并没有推送账号

### Expected Behavior

（国内）正常来讲，我已经在资产授权里添加了账号模板，那么我在往这个授权里添加新资产的时候，应该会自动推送这个账号模板的账号。

### Attempted Solutions

目前来讲只能通过账号推送任务和去资产下自己手动添加账号。

**Comment by BaiJiangJie** [comment]
是的，目前是这个逻辑，只有首次创建授权的时候会推送。

**Comment by xulongju** [comment]
哈喽，账号推送中，我修改了推送参数，修改了sudo可以执行的命令，没有生效。

**Comment by BaiJiangJie** [comment]
<v3.10.12 和 <v4.0 的版本，如果账号已存在，就不会推送了。

v3.10.13 和 v4.1 中会支持。

@xulongju

**Comment by hale177** [comment]
> <= v3.10.12 和 <= v4.0 的版本，如果账号已存在，就不会推送了。
> 
> v3.10.13 和 v4.1 中会支持。
> 
> @xulongju

恰好我这两天刚安装了 3.10.13 版本，问题依旧 ，帐号模板下增加资产并没有推送，
其次我发现用了 账号模板推送了帐号到目标资产，在批量连接性测试根本不通过 ，提示帐号密码错误，同样 ssh 也就无法通过 推送的帐号进行登录 

![image](https://github.com/user-attachments/assets/f697ac92-c860-46dd-84c5-60f280d6187c)
