### ISSUE TITLE
如何给jumpserver中的1panel应用添加一个安全访问的方法

### ISSUE THREAD

**Issue by yu4n2h1** [jumpserver/jumpserver#13800]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

浏览器为safari，jumpserver是all in one的docker部署在ubuntu 22。04上

### 🤔 问题描述

在1panel的应用上找不到website的安全模式
<img width="820" alt="image" src="https://github.com/user-attachments/assets/c26cd06f-42dd-4f36-b6a7-a39ee2768c56">
访问1panel的时候存在地址栏，感觉又点危险
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/f574d4c9-efab-45e0-a880-c34db3931d68">

### 期望结果

希望能够获得1panel的安全模式的开启方式

**Comment by Ewall555** [comment]
这是没有开启https的浏览器提示，你需要给1panel开启https然后更新对应web资产上的url就可以了

**Comment by yu4n2h1** [comment]
感谢
