### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hhjhappy** [jumpserver/jumpserver#13801]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

堡垒机连接Centos7.8系统使用sz 命令下载文件时候会卡主没反应

### 🐛 缺陷描述

堡垒机连接Centos7.8系统使用sz 命令下载文件时候会卡主没反应

### 复现步骤

用堡垒机连接centos7.8系统，使用sz下载文件大概率会卡主没反应

**Comment by BaiJiangJie** [comment]
目前针对大文件 rz、sz 有点问题，优先建议使用 sftp 方式。
未来会进行优化。
