### ISSUE TITLE
[Bug] v2 版本 rz、sz 下载文件卡住的问题

### ISSUE THREAD

**Issue by DuanNengxin** [jumpserver/jumpserver#13807]
### 产品版本

v2.16.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7

### 🐛 缺陷描述

连接ubuntu机器(内核版本5.15.0-1039-gcp），使用sz下载文件（很小的文件也会），会触发链接框卡死，当前连接不可用了

### 复现步骤

连接ubuntu机器，使用sz命令下载文件；
sz 命令下载文件 任务完成之后，后端会多发一个OO二进制信息，前端应该是使用这个去判断任务是否完成，然后再显示内容，但是碰巧这种机器不会发送OO这个二进制信息导致前端无法判断是否终止，然后就一直卡在那，貌似是前端bug；

<img width="640" alt="image" src="https://github.com/user-attachments/assets/02aef75a-f4d6-43ee-823b-1ff768753b6f">

**Comment by BaiJiangJie** [comment]
目前最新版本的 rz、sz 使用虽然有问题，应该比 v2 版本要好一些。

可以尝试升级。

**Comment by fengmikaelson** [comment]
v4卡的更夸张。。。而且一下载就卡死。。。
