### ISSUE TITLE
[Question] 文件传输和文件管理的用途

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#13810]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

无

### 🤔 问题描述

问题：已修改了sftp上传的默认路径为/data/tmp，使用文件管理上传文件是传输到了/data/tmp中，使用文件传输功能上传时为什么还是/tmp，按照我目前的理解，请问一下文件传输是不是当资产没有开启sftp时，也能让用户通过文件传输将文件传输至服务器中？

**Comment by BaiJiangJie** [comment]
没有开启 sftp 文件管理和文件传输功能都不能使用。

sftp 中的路径，只用做文件管理；文件传输因为是批量任务路径只能选一个，所以限定到 /tmp 下。

**Comment by Lynxhide** [comment]
![image](https://github.com/user-attachments/assets/b67c8772-a474-4bc2-9622-6c2ab1994bbd)
您好，我这么配置也是可以使用文件传输功能。

**Comment by BaiJiangJie** [comment]
上面描述不准确。
ssh、sftp、winrm 只要包含其中任一协议就可以使用文件传输功能。

**Comment by Lynxhide** [comment]
好嘞 谢谢  明白了
