### ISSUE TITLE
家目录推送权限不正确引起登录失败 ('Bad authentication type', ['publickey']) (allowed_types=['publickey'])

### ISSUE THREAD

**Issue by comk88** [jumpserver/jumpserver#1381]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
现象：  通过操作登不上目标机器
报错：('Bad authentication type', ['publickey']) (allowed_types=['publickey'])

手动登陆目标机器，对比与其他机器通用户文件
/home/op/.ssh/authorized_keys
一致，仍旧登录不上：
后发现家目录 竟然权限不太对：
drwx------  3       509       510 4096 5月  31 03:57 op
于是：
chmod -R op:op /home/op 立马就好了

##### 其他

[注:] 完成后请关闭 issue

**Comment by comk88** [comment]
第二个问题：
目标机器：
[root@ip-10-230-5-227 op]# ls -al
总用量 20
drwxr-xr-x 2 op   op   4096 5月   8 17:48 .
drwxr-xr-x 5 root root 4096 5月  31 07:40 ..
-rw-r--r-- 1 op   op     18 8月  30 2017 .bash_logout
-rw-r--r-- 1 op   op    193 8月  30 2017 .bash_profile
-rw-r--r-- 1 op   op    124 8月  30 2017 .bashrc

家目录竟然没有.ssh 目录  如何登陆的上去,每次都要上去放key 。。。。。

**Comment by gengkeye** [comment]
@comk88 默认是没有.ssh目录的，你可以些shell脚本去批处理，一台台累死人啊

**Comment by comk88** [comment]
@gengkeye 那为啥会登陆不上呢~加上.ssh目录，然后添加对应pub key到authorized_keys 后就可以登录成功了

**Comment by ibuler** [comment]
存在 ansible推送家目录权限不对的问题

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues

**Comment by gangh** [comment]
@ibuler @comk88

**Comment by gangh** [comment]
@ibuler @comk88 
这个问题是因为在推用户时将用户对应 home 目录的权限进行了修改吧,修改为了 700
https://github.com/jumpserver/jumpserver/blame/master/apps/assets/tasks.py#L328

在该 /home/{user_name} 目录已存在时会修改已有此目录的权限,导致对该目录下文件进行文件读写的服务出错
为什么在这个地方这样设计?这个地方有计划修改么 @BaiJiangJie
