### ISSUE TITLE
[Feature] 通过堡垒机实现端口转发功能

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13819]
### 产品版本

V3.10.10

### 版本类型

- [X] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

1. 希望通过堡垒机可以实现SSH-Tunnel功能，就是将资产上的某一个端口通过堡垒机转发到本地电脑上。
2. 经过测试，可以通过服务器的root账号实现端口转发，但是通过堡垒机的admin账号不能实现转发。
3. 目前多个客户有这样的需求，启明的堡垒机可以实现。

### 解决方案

1. 希望通过堡垒机可以实现SSH-Tunnel功能，就是将资产上的某一个端口通过堡垒机转发到本地电脑上。
2. 经过测试，可以通过服务器的root账号实现端口转发，但是通过堡垒机的admin账号不能实现转发。
3. 如下图
![图片](https://github.com/user-attachments/assets/4d2fd33f-c960-4136-b41c-960b6f686e96)

**Comment by BaiJiangJie** [comment]
为什么要转发呢？是为了实现什么场景？

**Comment by zjdc** [comment]
拓扑如下：
本地电脑------堡垒机------目标资产

本地电脑和堡垒机路由可达，堡垒机和资产路由可达，本地电脑和资产路由不可达。
堡垒机登陆资产通过22端口连接，资产上还有其他的业务端口，需要通过端口映射的功能转发到本地电脑进行访问。

因为网络环境的限制，不能使用远程应用的方式访问资产上面的业务端口。

**Comment by BaiJiangJie** [comment]
可以直接使用 SSH 连接堡垒机，再跳转登录资产。

SSH:2222 -> JumpServer -> 资产:22

我理解这样就可以解决。

**Comment by BaiJiangJie** [comment]
Check the gateway of asset configuration. This situation usually occurs when the gateway of asset configuration is unavailable.
