### ISSUE TITLE
[Question] 取消了工作台-作业中心功能？

### ISSUE THREAD

**Issue by 406226161** [jumpserver/jumpserver#13812]
### 产品版本

4.00-4.001

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

4.0以后取消了作业中心功能了吗？多么好用的功能一键下发命令，可以恢复这个功能吗？

### 解决方案

可以恢复这个功能吗？

**Comment by BaiJiangJie** [comment]
没有取消，只是默认关闭了，你可以在系统设置中手动打开。

**Comment by BaiJiangJie** [comment]
<img width="1817" alt="image" src="https://github.com/user-attachments/assets/26e431d5-3b73-482d-9d95-686e4881ec00">
