### ISSUE TITLE
[Question] 直接修改 lb_http_server.conf 文件来做双向认证，似乎不生效？

### ISSUE THREAD

**Issue by Jerrylovescoding** [jumpserver/jumpserver#13816]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

OS: Ubuntu
Deployment Arch: Docker
Browser: Chrome & Firefox

### 🤔 问题描述

为实现双向认证，尝试在 Jumpserver 的 nginx 配置文件 lb_http_server.conf 里，增加两行 ssl_client_certificate 和 ssl_verify_client 参数，似乎不生效，是我操作的方法不对，还是 Jumpserver 不支持这么直接操作呢？

**Comment by BaiJiangJie** [comment]
修改完重启服务 ./jmsctl restart

**Comment by Jerrylovescoding** [comment]
> 修改完重启服务 ./jmsctl restart

我之前尝试修改config.txt那个配置文件，不起作用，后面在 lb_http_server.conf 文件里加多二行，可能是根证书和key相关的有问题导致重启服务也不行，现在加多三行，然后再重启服务 ./jmsctl restart，确实OK了。
  ssl_client_certificate cert/root.crt;  # 客户端根证书
  ssl_verify_client on;  # 开启客户端验证
  ssl_verify_depth 2;
  
  @BaiJiangJie 谢谢！❤
