### ISSUE TITLE
[Question] 请问，是否支持k8s pod exec的终端命令审计，以及，如果支持的话，是否意味着基础镜像中必须增加一些组件，比如ssh

### ISSUE THREAD

**Issue by yxxchange** [jumpserver/jumpserver#13817]
### Product Version

latest

### Product Edition

- [X] Community Edition
- [X] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

k8s 1.27

### 🤔 Question Description

是否支持k8s pod exec的终端命令审计，以及，如果支持的话，是否意味着基础镜像中必须增加一些组件，比如ssh

**Comment by BaiJiangJie** [comment]
不需要啊，命令记录中你应该可以看到。
