### ISSUE TITLE
[Question] 请问web终端是否可以限制用户自己输入用户名和密码

### ISSUE THREAD

**Issue by OPPig** [jumpserver/jumpserver#13820]
### Product Version

v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

websit

### 🤔 Question Description

登录web终端以后，我在web应用中注销我的当前用户，我可以使用其他账号登录web应用，这样就不方便进行审计操作了，我用账号A登录后，自己注销，然后还可以登录账号B

### Expected Behavior

No response

### Additional Information

No response

**Comment by BaiJiangJie** [comment]
如果你的注销操作在web网站的页面内那就限制不了。
