### ISSUE TITLE
[Bug] 资产授权中用户数据丢失的问题

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#13826]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

版本号：v3.10.12
版本类型：企业版
单机部署

### 🐛 缺陷描述

在资产授权中用户数量比较大时>50左右或更多，点击更新资产授权后快速点击用户选择框，会造成已授权的用户丢失的情况
1、用户信息加载不全时，更新用户会照成用户数据部分的丢失
2、用户还在加载时，如果用户点击了提交，会照成用户数据的全部丢失
![image](https://github.com/user-attachments/assets/19411718-2867-465a-94ae-1a3e0ac598c3)

### 复现步骤

复现环境中：
已授权的用户数为106
![image](https://github.com/user-attachments/assets/8f57e389-68fa-4b2d-9e84-ef91efe2f096)
点击资产更新后，快速点击用户选择框，这时已授权的用户显示为20，如果此时提交更新，会照成用户数据的丢失
![image](https://github.com/user-attachments/assets/44aedf4f-d32f-417d-a299-1d06eaf02dae)

### 期望结果

1、增加loading状态，等待用户数据计算完成后，在加载用户信息，并提交
2、在用户信息未加载完成时，把提交按钮显示为灰色不允许提交信息

### 补充信息

更新资产授权时需加载后快速点击用户选择框

**Comment by BaiJiangJie** [comment]
弹窗加载完成之前，不允许点 确认 按钮。

**Comment by wangzhishang02** [comment]
以上两个问题复现视频如下：
1、用户点击用户选择框如果过快，会造成已选择的用户数据不准确，如下视频
![iShot_2024-08-07_18 03 13](https://github.com/user-attachments/assets/dadc0cd1-bd86-40e6-bd77-c920d0bb3b9c)
2、用户数据未加载全时点击提交会造成所有数据丢失，如下视频
![iShot_2024-08-07_18 09 01](https://github.com/user-attachments/assets/fe3da791-f9e0-4937-8edd-95d7326ff656)

**Comment by jym503558564** [comment]
该问题将在下个版本进行修复

**Comment by BaiJiangJie** [comment]
Released!
