### ISSUE TITLE
[Question] vscode无法通过jumpserver连接未联网的服务器

### ISSUE THREAD

**Issue by Abner1zhou** [jumpserver/jumpserver#13822]
### 产品版本

v3.10.9

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

本地电脑： Mac
jumpserver v3.10.9 （config文件夹中已经启用vscode配置）
被连接服务器：CentOS 7.3 内网服务器，无法连接互联网

### 🤔 问题描述

vscode remote-ssh 连接的过程会卡在这一步，分析发现是scp命令无法执行
Copying VS Code Server to host with scp

### 期望结果

通过vscode连接服务器

**Comment by BaiJiangJie** [comment]
不通过 JumpServer 使用 VS Code Remote-SSH 能连吗？

**Comment by Abner1zhou** [comment]
> 不通过 JumpServer 使用 VS Code Remote-SSH 能连吗？

可以连接的

**Comment by BaiJiangJie** [comment]
本质上是因为 scp vscode server 到 host 的时候失败了。

升级到 v3.10.x 最新版本，或者 v4 最新版本试试，针对 scp 的操作有优化。

**Comment by Abner1zhou** [comment]
升级到v4.0.1 能够进行scp操作，但是还是会卡在这一步
<img width="1605" alt="image" src="https://github.com/user-attachments/assets/be1dfcd4-c447-499d-bad9-ecfc564c5813">

**Comment by Abner1zhou** [comment]
已解决

**Comment by cheetah747** [comment]
> 调整下你资产平台的 sftp 根路径为 `/` 内置平台无法修改，可以创建一个新的平台，调整这个路径 默认都是 /tmp 作为跟路径，可能不满足 VSCode 的要求。
> 
> ![image](https://github.com/user-attachments/assets/d9d7dc44-c094-45e9-8b7e-cb23bb4b2d9f)

特意前来道谢，感谢老哥。
我也是卡这里，Copying VS Code Server to host with scp。按你说的重新创建Linux资产，根目录全设为/，把现有资产全改为这个，然后就很丝滑了。
