### ISSUE TITLE
用户创建存在XSS漏洞

### ISSUE THREAD

**Issue by huweiqing915** [jumpserver/jumpserver#1383]
[简述你的问题]

##### 使用版本
[Jumpserver版本1.3.1]

##### 问题复现步骤
1. 表单提交存在xss漏洞

##### 具体表现[截图可能会更好些,最好能截全]
![tim 20180531144907](https://user-images.githubusercontent.com/6898731/40766373-d600f8c8-64e1-11e8-9d43-3a6cd319031f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by qwqmeow** [comment]
大清都亡了
https://github.com/jumpserver/jumpserver/releases/tag/1.3.1

**Comment by huweiqing915** [comment]
@qwqmeow 
没明白，链接里面好像没有解决这个bug

**Comment by ibuler** [comment]
#1436 参见，打算修改，请关注
