### ISSUE TITLE
[Question]  Component health check warning , 应用发布机离线告警提醒

### ISSUE THREAD

**Issue by gzbenson** [jumpserver/jumpserver#13843]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Host : Proxmox VE 8.2 

Guest OS: Debian GNU/Linux 12 (bookworm) -- Jump Server v4.0.1 

Guest OS: Windows Server 2019 Standrad 

### 🤔 问题描述

系统会不断的提示 ： 应用发布及离线 

Component health check warning
3 小时前
[Tinker]-WinSvr2019-TXJdS
The component is offline: [Tinker]-WinSvr2019-TXJdS

### 期望结果

是需要针对性的设置 Windows Server 2019 ，还是 Jumpserver 还有其他设置，可以让应用发布机检测一直在线 ，不会那么多告警信息 ？ 

另外，虽然系统不断的有多个告警提示应用发布机离线， 但是实际是可以正常使用的，还是可以连接应用发布机并拉起chrome 打开web 应用的。

**Comment by BaiJiangJie** [comment]
看终端列表中的 Tinker 组件是不是有离线的。

**Comment by kvchoi** [comment]
可能你重装过对应的组件服务，新注册的组件可用，所以不影响使用。旧注册的组件已下线，导致系统定时检查会报警。
