### ISSUE TITLE
[Bug]  安装4.0.1版本，使用腾讯云的mysql，出现错误。

### ISSUE THREAD

**Issue by caesarym** [jumpserver/jumpserver#13841]
### 产品版本

4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

2024-07-30 17:44:33 Migrate model change to database ...
ALLOWED_HOSTS:
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
ALLOWED_HOSTS:
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying assets.0001_initial... OK
  Applying terminal.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20220616_0021... OK
  Applying accounts.0003_automation... OK
  Applying acls.0001_initial... OK
  Applying acls.0002_auto_20210926_1047... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying assets.0002_auto_20180105_1807... OK
  Applying assets.0003_auto_20180109_2331... OK
  Applying assets.0004_auto_20240709_1819... OK
  Applying ops.0001_initial... OK
  Applying audits.0001_initial... OK
  Applying audits.0002_ftplog_org_id... OK
  Applying audits.0003_auto_20180816_1652... OK
  Applying tickets.0001_initial... OK
  Applying authentication.0001_initial... OK
  Applying authentication.0002_auto_20190729_1423... OK
  Applying captcha.0001_initial... OK
  Applying captcha.0002_alter_captchastore_id... OK
  Applying django_cas_ng.0001_initial... OK
  Applying django_cas_ng.0002_auto_20201023_1400... OK
  Applying django_cas_ng.0003_auto_20210813_1226... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
  Applying django_celery_beat.0006_auto_20180322_0932... OK
  Applying django_celery_beat.0007_auto_20180521_0826... OK
  Applying django_celery_beat.0008_auto_20180914_1922... OK
  Applying django_celery_beat.0006_auto_20180210_1226... OK
  Applying django_celery_beat.0006_periodictask_priority... OK
  Applying django_celery_beat.0009_periodictask_headers... OK
  Applying django_celery_beat.0010_auto_20190429_0326... OK
  Applying django_celery_beat.0011_auto_20190508_0153... OK
  Applying django_celery_beat.0012_periodictask_expire_seconds... OK
  Applying django_celery_beat.0013_auto_20200609_0727... OK
  Applying django_celery_beat.0014_remove_clockedschedule_enabled... OK
  Applying django_celery_beat.0015_edit_solarschedule_events_choices... OK
  Applying django_celery_beat.0016_alter_crontabschedule_timezone... OK
  Applying django_celery_beat.0017_alter_crontabschedule_month_of_year... OK
  Applying django_celery_beat.0018_improve_crontab_helptext... OK
  Applying labels.0001_initial... OK
  Applying labels.0002_label_color... OK
  Applying notifications.0001_initial... OK
  Applying notifications.0002_auto_20210909_1946... OK
  Applying notifications.0003_initial_admin_msg... OK
  Applying ops.0002_celerytask... OK
  Applying orgs.0001_initial... OK
  Applying rbac.0001_initial... OK
  Applying orgs.0002_auto_20180903_1132... OK
  Applying perms.0001_initial... OK
  Applying perms.0002_auto_20171228_0025... OK
  Applying rbac.0002_auto_20210929_1409... OK
  Applying rbac.0003_auto_20211130_1037...[ERROR] Failed to change the table structure!

### 🐛 缺陷描述

安装不通过。

### 复现步骤

直接离线安装

**Comment by BaiJiangJie** [comment]
看一下 MySQL 的日志，什么操作下报错了。

**Comment by BaiJiangJie** [comment]
详细说明使用的腾讯云什么配置的 MySQL 数据库。

**Comment by jym503558564** [comment]
经测试无法复现上述问题，请提供具体mysql配置信息，以及安装过程的详细日志信息。
![image](https://github.com/user-attachments/assets/893990b8-b6a5-4ec3-adfc-3b37c3c3f02e)
![image](https://github.com/user-attachments/assets/83d29543-e08a-467e-93ec-171c3e295e2d)
![image](https://github.com/user-attachments/assets/ee005aaa-2f2a-4943-98f7-fee6bbacc332)

**Comment by caesarym** [comment]
我的是腾讯云的云mysql，版本为5.7，我用postgresql的镜像也出现这个问题。我的云主机的版本为centos7.2，内核版本为3.10.0-514.26.2.el7.x86_64

**Comment by caesarym** [comment]
我安装的时候选择的是外部的mysql，输入db ip和数据库据信息

**Comment by caesarym** [comment]
云mysql看不到日志的。

**Comment by caesarym** [comment]
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying assets.0001_initial... OK
  Applying terminal.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20220616_0021... OK
  Applying accounts.0003_automation... OK
  Applying acls.0001_initial... OK
  Applying acls.0002_auto_20210926_1047... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying assets.0002_auto_20180105_1807... OK
  Applying assets.0003_auto_20180109_2331... OK
  Applying assets.0004_auto_20240709_1819... OK
  Applying ops.0001_initial... OK
  Applying audits.0001_initial... OK
  Applying audits.0002_ftplog_org_id... OK
  Applying audits.0003_auto_20180816_1652... OK
  Applying tickets.0001_initial... OK
  Applying authentication.0001_initial... OK
  Applying authentication.0002_auto_20190729_1423... OK
  Applying captcha.0001_initial... OK
  Applying captcha.0002_alter_captchastore_id... OK
  Applying django_cas_ng.0001_initial... OK
  Applying django_cas_ng.0002_auto_20201023_1400... OK
  Applying django_cas_ng.0003_auto_20210813_1226... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
  Applying django_celery_beat.0006_auto_20180322_0932... OK
  Applying django_celery_beat.0007_auto_20180521_0826... OK
  Applying django_celery_beat.0008_auto_20180914_1922... OK
  Applying django_celery_beat.0006_auto_20180210_1226... OK
  Applying django_celery_beat.0006_periodictask_priority... OK
  Applying django_celery_beat.0009_periodictask_headers... OK
  Applying django_celery_beat.0010_auto_20190429_0326... OK
  Applying django_celery_beat.0011_auto_20190508_0153... OK
  Applying django_celery_beat.0012_periodictask_expire_seconds... OK
  Applying django_celery_beat.0013_auto_20200609_0727... OK
  Applying django_celery_beat.0014_remove_clockedschedule_enabled... OK
  Applying django_celery_beat.0015_edit_solarschedule_events_choices... OK
  Applying django_celery_beat.0016_alter_crontabschedule_timezone... OK
  Applying django_celery_beat.0017_alter_crontabschedule_month_of_year... OK
  Applying django_celery_beat.0018_improve_crontab_helptext... OK
  Applying labels.0001_initial... OK
  Applying labels.0002_label_color... OK
  Applying notifications.0001_initial... OK
  Applying notifications.0002_auto_20210909_1946... OK
  Applying notifications.0003_initial_admin_msg...[ERROR] Failed to change the table structure!
重新创建db后再次执行，卡在这里，能看一下执行什么语句会卡在这里吗？

**Comment by jym503558564** [comment]
整个安装过程日志，截图下，怎么安装的？

**Comment by BaiJiangJie** [comment]
`Perform migrate failed, exit`

执行迁移时有这一行报错吗？

@caesarym

**Comment by caesarym** [comment]
[root@prod-bj-ops-influxd-01 jumpserver-ce-v4.0.1-x86_64]# ./jmsctl.sh install


       ██╗██╗   ██╗███╗   ███╗██████╗ ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
       ██║██║   ██║████╗ ████║██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
       ██║██║   ██║██╔████╔██║██████╔╝███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
  ██   ██║██║   ██║██║╚██╔╝██║██╔═══╝ ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
  ╚█████╔╝╚██████╔╝██║ ╚═╝ ██║██║     ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
   ╚════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

                                                                   Version:  v4.0.1-ce

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

>>> Install and Configure Docker
1. Install Docker
complete

2. Configure Docker
complete

3. Start Docker
complete

>>> Loading Docker Image
redis:7.0-bullseye <= images/redis:7.0-bullseye.tar
Loaded image: redis:7.0-bullseye
Docker image not found: images/mariadb:10.6.tar
jumpserver/core:v4.0.1-ce <= images/core:v4.0.1-ce.tar
Loaded image: jumpserver/core:v4.0.1-ce
jumpserver/koko:v4.0.1-ce <= images/koko:v4.0.1-ce.tar
Loaded image: jumpserver/koko:v4.0.1-ce
jumpserver/lion:v4.0.1-ce <= images/lion:v4.0.1-ce.tar
Loaded image: jumpserver/lion:v4.0.1-ce
jumpserver/chen:v4.0.1-ce <= images/chen:v4.0.1-ce.tar
Loaded image: jumpserver/chen:v4.0.1-ce
jumpserver/web:v4.0.1-ce <= images/web:v4.0.1-ce.tar
Loaded image: jumpserver/web:v4.0.1-ce
complete

>>> Install and Configure JumpServer
1. Configure Private Key
complete

2. Configure Persistent Directory
Do you need custom persistent store, will use the default directory /data/jumpserver? (y/n)  (default n):
complete

3. Configure DB
Do you want to use external MySQL? (y/n)  (default y): y
Please enter DB server IP (default xxxx):
Please enter DB server port (default 3306):
Please enter DB database name (default xxxx):
Please enter DB username (default xxxx):
Please enter DB password (default xxxx):
complete

4. Configure Redis
Please enter Redis Engine? (redis/sentinel)  (default redis):
Do you want to use external Redis? (y/n)  (default y):
Please enter Redis server IP (default xxxx):
Please enter Redis server port (default xxxx):
Please enter Redis password (default xxxx):
complete

5. Configure External Access
Do you need to customize the JumpServer external port? (y/n)  (default n): y
JumpServer web port (default 8080):
complete

6. Init JumpServer Database
WARN[0000] Found orphan containers ([jms_redis]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 1/0
 ⠿ Container jms_core  Running                                                                                                                                                          0.0s
2024-07-31 13:35:42 Collect static files
2024-07-31 13:35:43 Collect static files done
2024-07-31 13:35:43 Check database structure change ...
2024-07-31 13:35:43 Migrate model change to database ...
ALLOWED_HOSTS:
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
ALLOWED_HOSTS:
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying users.0001_initial... OK
  Applying assets.0001_initial... OK
  Applying terminal.0001_initial... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20220616_0021... OK
  Applying accounts.0003_automation... OK
  Applying acls.0001_initial... OK
  Applying acls.0002_auto_20210926_1047... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying assets.0002_auto_20180105_1807... OK
  Applying assets.0003_auto_20180109_2331... OK
  Applying assets.0004_auto_20240709_1819... OK
  Applying ops.0001_initial... OK
  Applying audits.0001_initial... OK
  Applying audits.0002_ftplog_org_id... OK
  Applying audits.0003_auto_20180816_1652... OK
  Applying tickets.0001_initial... OK
  Applying authentication.0001_initial... OK
  Applying authentication.0002_auto_20190729_1423... OK
  Applying captcha.0001_initial... OK
  Applying captcha.0002_alter_captchastore_id... OK
  Applying django_cas_ng.0001_initial... OK
  Applying django_cas_ng.0002_auto_20201023_1400... OK
  Applying django_cas_ng.0003_auto_20210813_1226... OK
  Applying django_celery_beat.0001_initial... OK
  Applying django_celery_beat.0002_auto_20161118_0346... OK
  Applying django_celery_beat.0003_auto_20161209_0049... OK
  Applying django_celery_beat.0004_auto_20170221_0000... OK
  Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
  Applying django_celery_beat.0006_auto_20180322_0932... OK
  Applying django_celery_beat.0007_auto_20180521_0826... OK
  Applying django_celery_beat.0008_auto_20180914_1922... OK
  Applying django_celery_beat.0006_auto_20180210_1226... OK
  Applying django_celery_beat.0006_periodictask_priority... OK
  Applying django_celery_beat.0009_periodictask_headers... OK
  Applying django_celery_beat.0010_auto_20190429_0326... OK
  Applying django_celery_beat.0011_auto_20190508_0153... OK
  Applying django_celery_beat.0012_periodictask_expire_seconds... OK
  Applying django_celery_beat.0013_auto_20200609_0727... OK
  Applying django_celery_beat.0014_remove_clockedschedule_enabled... OK
  Applying django_celery_beat.0015_edit_solarschedule_events_choices... OK
  Applying django_celery_beat.0016_alter_crontabschedule_timezone... OK
  Applying django_celery_beat.0017_alter_crontabschedule_month_of_year... OK
  Applying django_celery_beat.0018_improve_crontab_helptext... OK
  Applying labels.0001_initial... OK
  Applying labels.0002_label_color... OK
  Applying notifications.0001_initial... OK
  Applying notifications.0002_auto_20210909_1946... OK
  Applying notifications.0003_initial_admin_msg...[ERROR] Failed to change the table structure!

**Comment by caesarym** [comment]
我这样安装的，用的离线安装包

**Comment by BaiJiangJie** [comment]
尝试换一下 MySQL 的版本，或者其他云服务商的 MySQL。

**Comment by caesarym** [comment]
本地的话用mariadb也可以的吧

**Comment by caesarym** [comment]
[root@prod-bj-ops-influxd-01 jumpserver-ce-v4.0.1-x86_64]# ./jmsctl.sh install


       ██╗██╗   ██╗███╗   ███╗██████╗ ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
       ██║██║   ██║████╗ ████║██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
       ██║██║   ██║██╔████╔██║██████╔╝███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
  ██   ██║██║   ██║██║╚██╔╝██║██╔═══╝ ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
  ╚█████╔╝╚██████╔╝██║ ╚═╝ ██║██║     ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
   ╚════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

                                                                   Version:  v4.0.1-ce

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

>>> Install and Configure Docker
1. Install Docker
complete

2. Configure Docker
complete

3. Start Docker
complete

>>> Loading Docker Image
redis:7.0-bullseye <= images/redis:7.0-bullseye.tar
Loaded image: redis:7.0-bullseye
Docker image not found: images/mariadb:10.6.tar
jumpserver/core:v4.0.1-ce <= images/core:v4.0.1-ce.tar
Loaded image: jumpserver/core:v4.0.1-ce
jumpserver/koko:v4.0.1-ce <= images/koko:v4.0.1-ce.tar
Loaded image: jumpserver/koko:v4.0.1-ce
jumpserver/lion:v4.0.1-ce <= images/lion:v4.0.1-ce.tar
Loaded image: jumpserver/lion:v4.0.1-ce
jumpserver/chen:v4.0.1-ce <= images/chen:v4.0.1-ce.tar
Loaded image: jumpserver/chen:v4.0.1-ce
jumpserver/web:v4.0.1-ce <= images/web:v4.0.1-ce.tar
Loaded image: jumpserver/web:v4.0.1-ce
complete

>>> Install and Configure JumpServer
1. Configure Private Key
complete

2. Configure Persistent Directory
Do you need custom persistent store, will use the default directory /data/jumpserver? (y/n)  (default n):
complete

3. Configure DB
Do you want to use external MySQL? (y/n)  (default y): n
complete

4. Configure Redis
Please enter Redis Engine? (redis/sentinel)  (default redis):
Do you want to use external Redis? (y/n)  (default y):
Please enter Redis server IP (default 10.10.4.8):
Please enter Redis server port (default 6379):
Please enter Redis password (default crs-9ltb97ds:i33dkxshh):
complete

5. Configure External Access
Do you need to customize the JumpServer external port? (y/n)  (default n): y
JumpServer web port (default 8080):
complete

6. Init JumpServer Database
[+] Running 9/9
 ⠿ mysql Pulled                                                                                                                                                                        14.6s
   ⠿ 9ea8908f4765 Pull complete                                                                                                                                                         5.2s
   ⠿ 7cb3a4df67e2 Pull complete                                                                                                                                                         5.5s
   ⠿ 4d2d4c02d11f Pull complete                                                                                                                                                         6.4s
   ⠿ 3e1f3619136a Pull complete                                                                                                                                                         6.5s
   ⠿ 7761768b6965 Pull complete                                                                                                                                                         6.6s
   ⠿ 56a0f21847dd Pull complete                                                                                                                                                        12.8s
   ⠿ 0d82f4c8dbd8 Pull complete                                                                                                                                                        12.9s
   ⠿ a362108bc1af Pull complete                                                                                                                                                        13.0s
[+] Running 2/2
 ⠿ Container jms_mysql  Started                                                                                                                                                        12.8s
 ⠿ Container jms_core   Started                                                                                                                                                        11.9s
[ERROR] Failed to change the table structure!我用本地跑docker mysql的方式运行安装程序，还是报错。

**Comment by BaiJiangJie** [comment]
不应该啊，要不你用内置的试试？

**Comment by jym503558564** [comment]
数据库新建的吗？上次装失败后，再次重新安装，数据库有清空表吗？

**Comment by jym503558564** [comment]
把你JS服务器的配置信息，外置MySQL的配置信息。

**Comment by caesarym** [comment]
我每次安装失败以后，都是删除数据库重新安装的。
服务器：腾讯云服务器，1核 1GB 5Mbps, CentOS 7.2 64位,
系统盘：SSD云硬盘 50G.
mysql:腾讯云 MySQL5.7 20180918

**Comment by caesarym** [comment]
是不是配置太低了？

**Comment by caesarym** [comment]
数据库因为有程序在跑，不敢升级。

**Comment by BaiJiangJie** [comment]
配置确实有点低。

备份好数据库，在新的机器上导入升级。
