### ISSUE TITLE
[Question]  Create Custom Applet

### ISSUE THREAD

**Issue by ikblmhndra** [jumpserver/jumpserver#13848]
### Product Version

JumpServer Community version GPLv3 v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [x] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

I want to create a custom Applet

### 🤔 Question Description

I want to implement application access using remoteApp, for example the application is Winbox from proxy, I have searched the App Market the application is not available, and I tried to create a custom according to the following documentation.

https://en-docs.jumpserver.org/guide/system/remoteapp/#34-page-layout

point = 4 Customized Applet

when I uploaded it unsuccessfully, it said `Applet pkg not valid, missing manifest.yml file`

**Comment by ikblmhndra** [comment]
Heres the setup.yml

```
type: exe # exe, zip, manual
source: https://download.mikrotik.com/routeros/winbox/3.41/winbox64.exe
arguments:
  - /qn
  - /norestart
destination: C:\Program Files\Winbox\
program: C:\Program Files\Winbox\winbox64.exe
md5: 74753834bb2808b26473249d0ace96fa
```

manifest.yml

```
name: Winbox
display_name: Winbox
comment: A tool for working with Mikrotik, to configure a routeros
version: 3.41
exec_type: python 
author: Ikbal
type: general
update_policy: none
```

**Comment by BaiJiangJie** [comment]
Show me the complete directory structure of your custom Remote App package.

**Comment by BaiJiangJie** [comment]
https://apps.fit2cloud.com/jumpserver

You can download an application from the app store, unzip it, and examine the directory structure to implement the customizations accordingly.

**Comment by ikblmhndra** [comment]
> Show me the complete directory structure of your custom Remote App package.

Here's the directory structure

```
├── main.py
├── manifest.yml
└── setup.yml
```
  
and heres, the main.py

```
import subprocess

def main():
    app_name = "winbox"
    user = {
        "id": "your_user_id",
        "name": "Administrator",
        "username": "admin"
    }
    asset = {
        "asset_id": "your_asset_id",
        "asset_name": "router",
        "address": "192.168.88.1",
        "protocols": [
            {
                "id": 1,
                "name": "winbox",
                "port": 8291
            }
        ]
    }
    account = {
        "account_id": "your_account_id",
        "username": "admin",
        "secret": "your_password"
    }
    platform = {
        "charset": "UTF-8"
    }

    subprocess.run(["C:\\Program Files\\Winbox\\winbox.exe", f"{asset['address']}"])

if __name__ == "__main__":
    main()

```

**Comment by BaiJiangJie** [comment]
Upload your zip package and I'll check it.

**Comment by BaiJiangJie** [comment]
You should compress all files in the upper directory, not select all files to perform compression.

**Comment by ikblmhndra** [comment]
[Archive.zip](https://github.com/user-attachments/files/16450127/Archive.zip)

heres the zip files

**Comment by ikblmhndra** [comment]
that custom app has successfully uploaded to jumpserver. But when I want deploy to Remote App its failed
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/8bc89eec-3c50-460d-b3b2-ebae2254aa92">
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/434a7107-8768-4615-ad37-d8f3fb541ab9">

**Comment by BaiJiangJie** [comment]
You need to see tinker's log.

**Comment by ikblmhndra** [comment]
Here's the tinker's logs

```
024-08-01 00:30:19 [INFO] Install applet winbox_1.0
2024-08-01 00:30:19 [INFO] download applet to C:\Users\Administrator\AppData\Local\Programs\Tinker\data\tmp\applet_zip1556917944\winbox_1.0.zip
2024-08-01 00:30:19 [INFO] unzip applet to C:\Users\Administrator\AppData\Local\Programs\Tinker\data\tmp\winbox2093013874
2024-08-01 00:30:22 [INFO] download source file to C:\Users\Administrator\AppData\Local\Programs\Tinker\data\tmp\winbox2093013874\winbox64.exe

```

full log
[remote.log](https://github.com/user-attachments/files/16451882/remote.log)

**Comment by BaiJiangJie** [comment]
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/df1ecafe-1a85-4fac-9e46-f8768c4c27e7">
Are there any more logs?

**Comment by BaiJiangJie** [comment]
https://download.mikrotik.com/routeros/winbox/3.41/winbox64.exe
Is this software sure it can be installed in windows?

**Comment by BaiJiangJie** [comment]
<img width="449" alt="image" src="https://github.com/user-attachments/assets/c0d98f18-eea0-4849-a863-57c2bce8c4c9">

Write setup.yml as follows
``` yml
type: manual # exe, zip, manual
destination: C:\Program Files\Winbox
program: C:\Program Files\Winbox\winbox64.exe
md5: 74753834bb2808b26473249d0ace96fa
```

Manually install `https://download.mikrotik.com/routeros/winbox/3.41/winbox64.exe`
Go to the `\Program Files\Winbox\winbox64.exe` location.

**Comment by ikblmhndra** [comment]
Thank's Its successfully deployed.
And I want add Asset for running that winbox, but i didn't see the platform?

**Comment by ikblmhndra** [comment]
I didn't see the custom menu in the asset or platforms

<img width="770" alt="image" src="https://github.com/user-attachments/assets/a1cb9e31-b220-449c-b53c-19792f57df99">

<img width="591" alt="image" src="https://github.com/user-attachments/assets/bd2c71b0-de91-4617-9efd-e1f8966588fc">

**Comment by BaiJiangJie** [comment]
The platform.yml file is missing in your zip package.

[platform.yml.zip](https://github.com/user-attachments/files/16469411/platform.yml.zip)

**Comment by ikblmhndra** [comment]
I have rebuild the custom applet, when I deploy the asset it can't be connect

<img width="611" alt="image" src="https://github.com/user-attachments/assets/579b1918-98a5-415b-875f-7f067b134e1d">

**Comment by ikblmhndra** [comment]
here's
[mikrotik-applet.zip](https://github.com/user-attachments/files/16492400/mikrotik-applet.zip)

**Comment by BaiJiangJie** [comment]
I would like to take a look at your remote application deployment, including the list of publishing machines and the list of applications in the publishing machines.

**Comment by BaiJiangJie** [comment]
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/3d5598d9-0001-4568-91b1-04e8341a42eb">
This may be because the protocols field in manifest.yml does not match the protocols in the platform. Change `winbox -> winbox64` and try again.

**Comment by ikblmhndra** [comment]
> <img alt="image" width="1476" src="https://private-user-images.githubusercontent.com/32935519/355076965-3d5598d9-0001-4568-91b1-04e8341a42eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTk5NTUsIm5iZiI6MTcyMjkxOTY1NSwicGF0aCI6Ii8zMjkzNTUxOS8zNTUwNzY5NjUtM2Q1NTk4ZDktMDAwMS00NTY4LTkxYjEtMDRlODM0MWE0MmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA0NDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMmY4ZTgzYTkyMWQ5MDg3Y2M1MjE5ZTdjNGJhZDUwYWYxNmZkOTEyNGM3N2ViMjNlYTNlNjc5MTc2ZjM3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dz-7ktTdRF_2GX1QqIzwM-hs6u_XPGYBdBfhEAji2wA"> This may be because the protocols field in manifest.yml does not match the protocols in the platform. Change `winbox -> winbox64` and try again.

I have rebuild the custom app, and when I create the asset show the error like this
<img width="490" alt="image" src="https://github.com/user-attachments/assets/7ffb8f54-3a2e-427f-83c0-88c675917abb">

**Comment by BaiJiangJie** [comment]
> I have rebuild the custom applet, when I deploy the asset it can't be connect
> 
> <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/32354274/354960217-579b1918-98a5-415b-875f-7f067b134e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjQ5MDMsIm5iZiI6MTcyMjkyNDYwMywicGF0aCI6Ii8zMjM1NDI3NC8zNTQ5NjAyMTctNTc5YjE5MTgtOThhNS00MTViLTg3NWYtN2YwNjdiMTM0ZTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2MTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzM2U4M2U0YTY1NTQ0ZDNjMjE0ZWM0NzkwNWE5MTRlNGEzMDg4MzgwMDA0ZGQ2Nzg0ZDBiMmE1NDNiNTQ1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9bDwKc--x-C0VlPZMcwc71db2TKEVfxl3QVMYPfMTM">

Did you pass this step?

**Comment by ikblmhndra** [comment]
Sorry I can't see your attachment / image

**Comment by ikblmhndra** [comment]
I don't understand what step you mean ?

**Comment by BaiJiangJie** [comment]
Whether the Connect button can be clicked in the pop-up window of connecting assets on the Luna page.

**Comment by BaiJiangJie** [comment]
You should delete all previous applications, reinstall them in windows, and re-deploy them in JumpServer.

**Comment by ikblmhndra** [comment]
yeah already reinstall, even to reset the remote app (windows server) and still error like that,

Is there something wrong with the main.py?

**Comment by BaiJiangJie** [comment]
"C:\\Program Files\\Winbox\\winbox.exe"

Check to see if this file exists.

**Comment by ikblmhndra** [comment]
yes this file is exists

<img width="812" alt="image" src="https://github.com/user-attachments/assets/c8cc58bc-13e9-495f-8c56-4c9e57d6e58e">

**Comment by BaiJiangJie** [comment]
Maybe you should write winbox64.exe

`C:\Program Files\Winbox\winbox64.exe`

**Comment by ikblmhndra** [comment]
I have rewrite the code like this, for main.py app.py common.py

[mikrotik-applet 2.zip](https://github.com/user-attachments/files/16506964/mikrotik-applet.2.zip)

My reference from DBeaver application
https://apps.fit2cloud.com/jumpserver/dbeaver

**Comment by ikblmhndra** [comment]
for the automate filling the IP address, username, password. and auto click for connect

**Comment by BaiJiangJie** [comment]
The customization of applications is an enterprise Edition function, and if you want to customize your own applications, you can consider Enterprise Edition.

**Comment by ikblmhndra** [comment]
Thank you for you support.

I have already fixed the custom app. 

Here's my code if you want to publish in Jumpserver market
https://github.com/ikblmhndra/mikrotik-applet
