### ISSUE TITLE
[Bug] 命令记录功能，回显结果记录不准确，总是少记录了最后一行，实际输出n行回显结果，但只记录了n-1行，未记录最后一行

### ISSUE THREAD

**Issue by hyzyxmj** [jumpserver/jumpserver#13844]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [x] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

使用1panel一键安装

### 🐛 缺陷描述

命令回显结果只有一行时，未记录回显结果，只记录了执行的命令没有返回结果，
![image](https://github.com/user-attachments/assets/d49cfdce-9273-41e6-8cbe-c2f2a202c180)
![image](https://github.com/user-attachments/assets/b383b29d-0ede-479c-b15b-fe546fd96b87)

### 复现步骤

执行任意命令，回显结果记录不准确，总是少记录了最后一行，实际输出n行回显结果，但只记录了n-1行，未记录最后一行

### 期望结果

记录所有命令回显完整结果

**Comment by jym503558564** [comment]
下个版本修复
