### ISSUE TITLE
[Bug] 快捷命令执行，输出信息缺失。

### ISSUE THREAD

**Issue by Linkjie-11** [jumpserver/jumpserver#13854]
### 产品版本

V3

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

标准部署，和k8s部署环境测试快捷命令。

### 🐛 缺陷描述

资源名称带冒号＋数字后缀部分快捷命令输出信息不完整，
![8cca6468-4e79-4fc0-9bf4-93799bd8d67f](https://github.com/user-attachments/assets/a435a710-c766-4d8c-8aa7-a9219d2f7fb0)
![e557eadb-83fc-4c5e-83bc-e205d0bf0861](https://github.com/user-attachments/assets/8212fc1f-3472-43f6-8ae1-8923cc287d14)

### 复现步骤

资源名称:
name:01
name:02
1name:01
1name:02
选中执行命令，输出得信息显示可能为
name |*****
1name |***** 
冒号连同后边得信息缺失。

### 期望结果

输出完整信息。

### 尝试过的解决方案

更改资源名称方式不适用。

**Comment by BaiJiangJie** [comment]
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/67ff063c-a5d3-4909-a61e-7fe9bc1edb97">

**Comment by BaiJiangJie** [comment]
ansible 会解析资产的 name，如果 : 后面是数字会尝试解析为 port，所以只要 : 号后面不是全数字就可以。
