### ISSUE TITLE
[Bug] 资产授权页面的账号数量显示错误

### ISSUE THREAD

**Issue by FiendFEARing** [jumpserver/jumpserver#13859]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS8单机部署

### 🐛 缺陷描述

资产授权页面的账号数量显示错误
![image](https://github.com/user-attachments/assets/00287f99-0c3a-429e-858e-c7bf4b9d09d9)
![image](https://github.com/user-attachments/assets/344867bd-3c77-474f-8404-ac00a9fec607)

### 复现步骤

1、创建资产授权规则
2、选“指定账号”并指定一个账号
3、保存后回到资产授权页面刷新后显示账号数量为2
4、尝试多加一个账号，保存刷新后显示账号数量为3
5、尝试删除所有账号，保存刷新后显示账号数量为1

**Comment by BaiJiangJie** [comment]
在计算逻辑是，`指定账号` 这个选项也统计在内了。
有问题，v4.1.0 中修复。

**Comment by jym503558564** [comment]
v4.1.0 已修复。
