### ISSUE TITLE
[Question] Windows AD的ldap无法导入用户组信息

### ISSUE THREAD

**Issue by pwnfox** [jumpserver/jumpserver#13858]
### Product Version

v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

debian11

### 🤔 Question Description

Windows AD的ldap无法导入用户组信息
![image](https://github.com/user-attachments/assets/53aa17bc-5f42-43cd-bb98-8fbe128c9840)
![image](https://github.com/user-attachments/assets/daa0b865-33c7-47cb-badc-912e218f01df)

**Comment by BaiJiangJie** [comment]
确认你的 AD 中 memberOf 属性是否存在。
