### ISSUE TITLE
[Feature] MySQL 数据库 < 5.5 版本的支持问题

### ISSUE THREAD

**Issue by huskiesir** [jumpserver/jumpserver#13857]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

Mysql数据库为5.0.x的(5.5之前的版本都没有utf8-mb4字符集的支持)，JumpServer连接这种老版本的数据库提示字符集utf8的问题，JumpServer能否适配并支持这种5.5版本以下的数据库。

### 解决方案

JumpServer能否支持多字符集，我看现在只有utf-8，这样能否就可以支持mysql5.5之前的版本了？

### 补充信息

![image](https://github.com/user-attachments/assets/c19a4610-6347-4a83-a500-4799beee8f3f)

**Comment by BaiJiangJie** [comment]
截图中的测试可连接性，显示是用户名密码不正确，不是字符集问题。
