### ISSUE TITLE
[Bug]  jumpserver redis DB 直连（客户端-DB直连向导的方式），执行命令：set aaa "\naa" 报错：Error: Server closed the connection

### ISSUE THREAD

**Issue by leiziang** [jumpserver/jumpserver#13856]
### 产品版本

v4.0.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

/

### 🐛 缺陷描述

jumpserver redis DB 直连，执行命令：set aaa "\naa" 报错：Error: Server closed the connection

### 复现步骤

必现

**Comment by leiziang** [comment]
> <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/32935519/354123994-873ebdd0-27ee-4a46-9559-7098a3ea638a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDI5ODQsIm5iZiI6MTcyMjUwMjY4NCwicGF0aCI6Ii8zMjkzNTUxOS8zNTQxMjM5OTQtODczZWJkZDAtMjdlZS00YTQ2LTk1NTktNzA5OGEzZWE2MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4NTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZjhmNzQ3ZWJmMjUzNmM0ODM1OGM2Y2MxMjhjYWQ5NWMwYWJkMDZjOGVhYzdiNjJlZTEyYjEwM2QxZWRhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPiamIhi9H8OQeWq_iXBa1IxX6V3GEmufchJRNr5i1U">
> 看 koko 日志。

你这个应该不是通过DB直连的方式。
![image](https://github.com/user-attachments/assets/e332b2a2-706d-4fe5-8fa6-888ce4fc7ddf)
我这边也是，通过web cli的方式也没问题。但是通过DB直连的方式就会报错

**Comment by BaiJiangJie** [comment]
DB 直连的方式是通过 Magnus 连接的。
v4.0 已经没有 Magnus 组件了，你是怎么连接的？
