### ISSUE TITLE
[Feature] 对接ES中传输“远端地址”这个字段

### ISSUE THREAD

**Issue by haiyu1234** [jumpserver/jumpserver#13855]
### 产品版本

3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

在命令记录对接ES过程中，发现命令记录中的远端地址字段没有传输过去

### 解决方案

加上这个字段

### 补充信息

远端地址是属于会话属性的，可以根据session去关联获得远端地址，但是还是希望命令记录通过ES传输过程中加上这个字段

**Comment by BaiJiangJie** [comment]
暂时不考虑。
