### ISSUE TITLE
如何使用Jumpserver解决文件上传下载问题

### ISSUE THREAD

**Issue by snowkity2005** [jumpserver/jumpserver#1385]
[简述你的问题]
Version 1.3.0-2 GPLv2.

##### 问题复现步骤

如何使用Jumpserver解决文件上传下载问题

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. lrzsz
2. sftp

未来 web terminal也会支持文件上传下载
有问题可以重新打开issue
