### ISSUE TITLE
[Question] 新主机安装4.0版本，如何将旧的3.8版本数据连同MFA一起导入新主机。

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#13868]
### 产品版本

3.8

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS7

### 🤔 问题描述

如题，因更换主机，在新主机安装了4.0版本，如何将旧的3.8版本数据连同MFA一起导入新主机，让用户不用因为重新安装而重新新绑定MFA。

**Comment by BaiJiangJie** [comment]
先 v3.8 升级到 v3.10.x 的最后一个版本，数据库全部导入到 v4.0 中就可以。
