### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by liujiawen** [jumpserver/jumpserver#13867]
### Product Version

4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

centos 7.9

### 🤔 Question Description

jumpserver如何实现对一部分资产支持vscode，一部分资产不支持？

### Additional Information

目前我们有这样的场景，一部分机器需要支持vscode，用于开发人员开发。另一部分资产里有较高密级的数据，为了防止被拷贝出去，需要禁止vscode。需要什么样的配置可以满足这样的区分？

**Comment by BaiJiangJie** [comment]
不支持。
