### ISSUE TITLE
[Bug] Web Terminal上使用sz命令下载二进制文件或其他无文件后缀的文件，会自动添加.txt后缀，与原始文件命名不一致

### ISSUE THREAD

**Issue by hyzyxmj** [jumpserver/jumpserver#13869]
### Product Version

v3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

1Panel一键安装

### 🐛 Bug Description

Web Terminal上使用sz命令下载二进制文件或其他无文件后缀的文件，会自动添加.txt后缀，与原始文件命名不一致，其他带有后缀(.txt,.mp4...)的文件不受影响，与原始文件命名一致
![image](https://github.com/user-attachments/assets/1e4e0871-43ae-404b-bc4b-5201b6eaac46)

![image](https://github.com/user-attachments/assets/be6dfeff-3b9b-4732-bfa9-c25ccf61c8d7)
![image](https://github.com/user-attachments/assets/5cef70fc-42a9-4af9-96ff-261b052b7bbe)

### Recurrence Steps

下载任意二进制文件或者无文件后缀的文件，会自动添加.txt后缀

### Expected Behavior

返回不带文件后缀的，文件名，后缀与原始格式一样的文件，而不是自动添加txt

**Comment by LeeEirc** [comment]
对于没有后缀的文件，浏览器自动给调整加上后缀名。

**Comment by BaiJiangJie** [comment]
应该是浏览器的问题问题，测试发现，不同的浏览器后缀名不同，有的不会自动增加。
比如下载 x 文件。

```
Safari: x
Firefox: x.dms
Chrome: x.txt
```
