### ISSUE TITLE
[Question] sftp路径无法修改

### ISSUE THREAD

**Issue by arlequinfei** [jumpserver/jumpserver#13863]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos 8.10

### 🐛 缺陷描述

SFTP 根路径 无法修改，如下图所示

![image](https://github.com/user-attachments/assets/ff8b66b2-4697-41ad-a7f4-e6df824900da)

### 复现步骤

在平台协议配置中，Linux主机无法修改sftp根路径

1. 进入平台列表
2. 选择linux平台编辑
3. 在右侧 选择 平台协议配置：sftp
4. 编辑 SFTP 根路径

**Comment by BaiJiangJie** [comment]
内置平台不能修改，copy 一个新的平台操作。
