### ISSUE TITLE
[Bug] 账号推送会推送到其他资产上

### ISSUE THREAD

**Issue by arlequinfei** [jumpserver/jumpserver#13873]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver 操作系统：CentOS 8.10
资产主机操作系统：AlmaLinux 9.4

### 🐛 缺陷描述

有两台linux主机，名称分别为RTX4090PA和RTX4090TUF。
在jumpserver里已经建立了root用户。

建立test账号，使用账号推送功能会将账号推送到其他资产上，如下图所示：

![pp20240802223417](https://github.com/user-attachments/assets/0089c0e4-4436-4e67-8d65-9f24e31b1141)

![pp20240802223327](https://github.com/user-attachments/assets/1f7916da-9340-4498-be23-353324180fb4)

### 复现步骤

有两台linux主机，名称分别为RTX4090PA和RTX4090TUF。

1. 账号推送里建立test用户
2. 资产选择RTX4090PA
3. 提交，手动执行
4. 发现日志里，RTX4090TUF主机里也被推送了test用户

**Comment by BaiJiangJie** [comment]
出现这个问题，是因为你选择了 DEFAULT 节点。

推送任务，会推送选择的资产和选择的节点下的所有资产。
