### ISSUE TITLE
[Question] koko 的命令识别能能支持到什么程度， 如果回显延迟导致的命令解析问题

### ISSUE THREAD

**Issue by haiweikarry** [jumpserver/jumpserver#13880]
### 产品版本

v4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [X] 源码安装

### 环境信息

无，产品能力咨询

### 🤔 问题描述

1. koko 我看代码是通过解析字符方式渲染回显。 我的问题是 咱们koko现有功能 能支持所有xtem协议的字符吗？
2. koko 是通过回显数据流来实现命令识别的， 如果input已经收到回车，那么上个字符的回显环没有回来，这种情况怎么解决的

**Comment by LeeEirc** [comment]
1、并没有支持所有xtem协议的字符，基于 vt100 的终端协议字符（xterm 的子集），对于 bash 的终端识别效果整体还可以。
2、对用户输入的字符做了辅助记录。
命令解析还有很多的完善空间，后续还会迭代。

**Comment by haiweikarry** [comment]
有具体支持字符啥的列表吗，针对xtem不支持的字符 我可以添加下限制。
在一个是上述问题2有解决方案吗， 快速复制命令会直接携带回车， 这时回显延迟。 比如：ls回车，这时shell的out只有l字符，没有s，那么解析出来的命令只有l，没有s。这种这问有解决方案或者思路没

**Comment by LeeEirc** [comment]
xterm 的终端字符协议不是可见字符，你应该无法限制，否则字符显示会存在问题。
针对2，我们有做了一些 tick 的操作，应该是可以解析记录的。
