### ISSUE TITLE
[Question] About DB pf Jumpserver

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#13889]
### Product Version

4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

RHEL version 8.5

### 🤔 Question Description

I want update Jumpserver version 3.9.1 into 4.0.2
But In old version (before version 4.0), Jumpserver use MySQL for DB and version 4.0, Jumpserver use PostgreSQL
How can I do to update

**Comment by BaiJiangJie** [comment]
The v4.0 version defaults to using PostgreSQL as the backend database. However, MySQL is still supported, so existing setups will remain unaffected. If you wish to switch to PostgreSQL, you will need to handle the data migration process yourself.
