### ISSUE TITLE
[Question] Is Jumpserver PCI compliance?

### ISSUE THREAD

**Issue by ziadanex99** [jumpserver/jumpserver#13890]
### Product Version

JumpServer Latest

### Product Edition

- [X] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

PCI Environment.

### 🤔 Question Description

Is Jumpserver has a compliance or does it meet the standard requirements for PCI-DSS?

**Comment by BaiJiangJie** [comment]
Which rules are you referring to specifically in PCI-DSS?

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
