### ISSUE TITLE
[Bug] cas同步的用户，ssh密钥连接到堡垒机，mac操作系统无法使用重置并下载的私钥进行连接

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#13899]
### 产品版本

v3.10.10

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

标准单机

### 🐛 缺陷描述

![img_v3_02dg_91178197-18b9-42a3-ab95-34221a6bacix](https://github.com/user-attachments/assets/debacbd2-86b7-49aa-bf73-16990c49c3d9)

cas同步的用户，ssh密钥连接堡垒机，提示需要输入密码，堡垒机数据库没存密码所以输入密码也无法登录

### 复现步骤

1.cas同步一个用户
2.重置并下载密钥，通过ssh连接堡垒机
3.需要输入密码

### 期望结果

建立连接

### 尝试过的解决方案

1.自己创建的ssh公钥私钥上传可以正常连接
2.重置并下载私钥 再连接提示需要密码
3.删除用户再同步，重置并下载私钥 再连接需要输入密码
4.mac操作系统，pc未测试
5.怀疑提供的重置并下载私钥这个选项有问题
6.进数据库看过用户，pubkey password source ，pukey存在，password不存在，source 为cas
7.个别几个用户会出现，并且同样操作，类似删公钥重置用户信息，重置各种，此个别用户依旧连不上
8.本地mac操作系统复现

**Comment by Ewall555** [comment]
由于后续再通过自建密钥对上传的公钥去连接也需要输入密码了
客户需要提供解密数据库的方法以对比pubkey和上传的是否一致
个人目前认为要么有缓存（感觉不对），要么是bug，有没有相关日志可以看的，或描述一下，第三方认证或者密钥登录的逻辑细节

**Comment by BaiJiangJie** [comment]
不用 CAS 用户，用 Local 用户可以吗？

**Comment by Ewall555** [comment]
未知问题，其他机器可以，就那一个客户机器不行，目前已有备用方案
