### ISSUE TITLE
[Question] 开启MFA后，密钥登录终端还要输入的OTP Code，能不能支持1小时内重复登陆无需再次验证MFA，一直需要输入的话很麻烦

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#13893]
### 产品版本

v3.7.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

无

### 🤔 问题描述

开启MFA后，密钥登录终端还要输入的OTP Code，能不能支持1小时内重复登陆无需再次验证MFA，一直需要输入的话很麻烦
![image](https://github.com/user-attachments/assets/3829434a-5ae0-436f-aa06-93fe5d111144)

### 期望结果

期望无需重复输入

**Comment by BaiJiangJie** [comment]
不符合安全产品设计的逻辑。

**Comment by xiaoxiongxyy** [comment]
> 不符合安全产品设计的逻辑，你使用的产品中有这样的设计吗？

<img width="808" alt="image" src="https://github.com/user-attachments/assets/b5c87851-2ae0-4896-ba58-d3935005ae16">

**Comment by BaiJiangJie** [comment]
别找浏览器端，找 SSH 方式的。
