### ISSUE TITLE
[Question] 通过 API 给资产授权规则增加授权账号

### ISSUE THREAD

**Issue by alexjs001** [jumpserver/jumpserver#13891]
### 产品版本

v3.19.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

mysql、redis外部部署
其他组件docker部署

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/a1c81329-a660-4884-93f7-37e1a0d19611)
权限管理--->>>资产授权--->>>账号
![image](https://github.com/user-attachments/assets/f9225334-f11c-4629-b773-c6c20d36a8f0)
![image](https://github.com/user-attachments/assets/b52263b9-2b1c-4baf-a537-269bcd34b122)
如何通过api或者数据库操作，增加授权账号

**Comment by BaiJiangJie** [comment]
```
PATCH /api/v1/perms/asset-permissions/41b2fd60-6858-45ca-9de0-433913a2ddc6/

data:
{
    "accounts": [
        "@SPEC",
        "1",
        "2"
    ]
}
```

accounts 的值需要每次都是完整的。

**Comment by BaiJiangJie** [comment]
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/8b28430a-77ed-4192-8223-2a44cdf7ed5e">

你可以在授权详情中手动操作添加账号，通过浏览器控制台的 API 调用了解具体的接口使用。
