### ISSUE TITLE
[Question] 自己写的navicat15远程应用调起app后没有后续

### ISSUE THREAD

**Issue by Niu1234561221** [jumpserver/jumpserver#13894]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：ubuntu22.04

### 🤔 问题描述

我根据提供的applets模板自己写了一个navicat15的脚本，在本地测试是正常的，但是上传到jumpserver之后，将navicat15启动之后就页面没有反应了。
<img width="749" alt="587c40a3e72b7f297786c7e5fe0d18d" src="https://github.com/user-attachments/assets/ef4ce424-70d2-4137-aeed-9a0c89b04e46">

之后我就在发布机上找到我写的脚本，通过python手动执行了一下脚本，发现也是可以成功调起和代填的。

<img width="960" alt="91a6867b700b331c41cacd12d87c107" src="https://github.com/user-attachments/assets/cc4a6a88-e9b3-420f-9317-964739b7d4a8">

附上我的脚本：

```
import sys
import time

if sys.platform == 'win32':
    from pywinauto import Application
    from pywinauto.controls.uia_controls import (ButtonWrapper, EditWrapper, MenuItemWrapper,
                                                 MenuWrapper, ComboBoxWrapper, ToolbarWrapper)
from common import (BaseApplication, wait_pid, )

_default_path = r"C:\navicat\Navicat Premium 15\navicat.exe"


class AppletApplication(BaseApplication):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.path = _default_path
        self.username = self.account.username
        self.password = self.account.secret
        self.host = self.asset.address
        self.port = self.asset.get_protocol_port(self.protocol)
        self.db = self.asset.spec_info.db_name
        self.pid = None
        self.app = None

    def run(self):
        app = Application(backend='uia')
        app.start(self.path)
        self.pid = app.process
        if not all([self.username, self.password, self.host]):
            print(f'缺少必要的参数')
            return

        # 定位主窗口
        win = app.window(class_name='TNavicatMainForm')
        time.sleep(7)
        menubar = win['Menu']

        # 打开新建连接窗口
        menubar.child_window(title='文件', control_type="MenuItem").click_input()
        menubar.item_by_path("文件->新建连接").click_input()
        menubar.item_by_path("文件->新建连接->MySQL...").click_input()

        # 选择新建连接窗口
        # 连接名
        win["常规"].Edit5.type_keys(self.host)
        # ip输入框
        # new_dlg["常规"]["Edit1"],报错，此时应该更换.的方式
        win["常规"].Edit1.type_keys(self.host)
        # 端口输入框
        win["常规"].Edit4.type_keys(self.port)
        # 用户名输入框
        win["常规"].Edit3.type_keys(self.username)
        # 密码输入框
        win["常规"].Edit2.type_keys(self.password)

        # 点击确定按钮,Button类型的就可以直接调用click()
        win["确定"].click()

        self.app = app
# 等待进程退出
    def wait(self):
        wait_pid(self.pid)

```

### 期望结果

希望可以确定一下是我脚本的问题还是我jumpserver配置或者环境的问题导致的。谢谢

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13892#issuecomment-2270886430

**Comment by BaiJiangJie** [comment]
如果你不熟悉自定义远程应用的开发，建议考虑购买企业版，因为实现逻辑较为复杂，且定制化指导会比较困难。

**Comment by Niu1234561221** [comment]
好的，我会考虑的，公司规模比较小，现在主要是还是抱着学习的目的来使用jumpserver。

下面是tinker的日志，好像没啥有用的信息，我执行一遍操作之后日志并没有增加。

![image](https://github.com/user-attachments/assets/44ec4c6c-5dfa-42df-8375-f52ba46afe70)

**Comment by BaiJiangJie** [comment]
你可以研究一下不通过 JumpServer 的远程应用是否可以拉起并代填。
具体步骤如下：
1. 在 windows 上手动发布一个 python 脚本，用来执行 main.py 文件（参考工具：https://github.com/kimmknight/remoteapptool）
2. 创建 windows 的 remoteapp.rdp 连接文件，修改对应的参数
3. 使用 windows remote desktop 工具连接测试。

**Comment by Niu1234561221** [comment]
好的，非常感谢！我会尝试的
