### ISSUE TITLE
[Question] 账号模板中的自動推送生效方式

### ISSUE THREAD

**Issue by GOGOrun2** [jumpserver/jumpserver#13909]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

rocky linux 9.3
docker 27.1.1
chrome 127.0.6533.89 

### 🤔 问题描述

1. 帳號模版中的自動推送沒有生效,操作步驟如下：
    控制台-帳號管理-帳號模版-創建
    1. root(開啟特權帳號,vm主機有此帳號）
    2. op_user  (開啟自動推送,系統平台 ：Linux , vm主機無此帳號）

2. 控制台- 資產列表-創建
    基本：
    名稱：vm01(centos7.9),平台：Linux
    帳號：帳號列表-模版添加-root
    其他：預設值

3.控制台- 資產列表- vm01- 操作更多-測試-可連接-成功

4.連線至 vm01 底層查看 "/home/ , /etc/sudoers "沒有 op_user 的資訊,應該沒有將此帳號建立

### 期望结果

預期 控制台-帳號管理-帳號模版-創建 有勾選自動推送 系統平台：Linux

往後新增 資產(vm)時 , 只需要給 root 模版, 

jumpserver 會自動推送 設定的帳號
1.vm 無此帳號 - 創建
2.vm 有此帳號- 取代（密碼 or sudo 如: /bin/whoami,/sbin/ifconfig)

也許對於"自動推送"的使用方式,我的認知有誤,再麻煩團隊協助,感謝～

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13383#issuecomment-2153768042

版本：<= v3.10.12 和 <= v4.0，只有在账号列表中创建账号时支持推送。

v3.10.13 和 v4.1 中都会支持。

**Comment by GOGOrun2** [comment]
感謝協助
