### ISSUE TITLE
[Question] Dual Access In Jump Server Community Edition

### ISSUE THREAD

**Issue by alandrma** [jumpserver/jumpserver#13900]
### Product Version

JumpServer Community Version:	v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Dear All,

We would like to inquire about Dual Access in Jump Server Community Edition. Is it possible to implement this?

### 🤔 Question Description

Dear All,

We would like to inquire about Dual Access in Jump Server Community Edition. Is it possible to implement this?

**Comment by BaiJiangJie** [comment]
Hi, What exactly do you mean by Dual Access?

**Comment by alandrma** [comment]
> What exactly do you mean by Dual Access?

"More or less related to dual access like in this image, is there a feature in the Jumpserver community edition that we can utilize which is similar to this?"

<img width="516" alt="image" src="https://github.com/user-attachments/assets/716ad6fa-4eeb-4c5b-9baa-99afb33dc62a">

https://docs.cyberark.com/privilege-cloud-shared-services/latest/en/Content/Privilege%20Cloud/privCloud-setup-workflow.htm

**Comment by BaiJiangJie** [comment]
This feature is an enterprise version feature.

There are two levels of related features in JumpServer:

1. Users can apply for the assets they need to access and the accounts they need to use through work orders.

2. Administrators can set login review for users to access assets. Users can only connect to assets after the administrator approves it.

**Comment by alandrma** [comment]
Thank you for the explanation.

I want to ask again, but outside of dual access, can matters related to audit logs be forwarded to a third-party log collector?

**Comment by BaiJiangJie** [comment]
Yes, Audit logs can now be forwarded to Syslog.
Session command logs can be stored in Elasticsearch (ES).
Session recordings are supported for storage in object storage solutions such as S3, Ceph, Azure, and others.

**Comment by alandrma** [comment]
@BaiJiangJie Is there any link or documentation that I can follow?

**Comment by BaiJiangJie** [comment]
https://docs.jumpserver.org/zh/v3/guide/admin/admin_tickets/#42
https://docs.jumpserver.org/zh/v3/guide/user/user_tickets/
https://docs.jumpserver.org/zh/v3/guide/admin/permission/host_acls/#2

This is the v3 work order document, currently only available in Chinese.

You can apply for an enterprise trial version to experience the work order function and verify whether it can meet your usage scenario.

**Comment by alandrma** [comment]
@BaiJiangJie 

So, to be able to forward logs to a third party, can we use a work order? Does that include login logs, audit logs, operation logs, and other types of logs?

**Comment by alandrma** [comment]
@BaiJiangJie If we initially installed using `./jmsctl.sh install` and it was deployed into a Docker container, how can we add to it without redeploying?

**Comment by alandrma** [comment]
@BaiJiangJie 

We have already tried adding the following configuration:

```
SYSLOG_ENABLE=true
SYSLOG_ADDR=
```

Is it sufficient to set `SYSLOG_ADDR=` to just `IP_ADDRESS:PORT`?

How do we check syslog from within the Docker container?

**Comment by alandrma** [comment]
dear @BaiJiangJie This ticket can be closed.

We have successfully completed the integration. Thank you so much

**Comment by BaiJiangJie** [comment]
Awesome, hope you enjoy using it.
