### ISSUE TITLE
[Feature] 希望堡垒机云同步功能支持比格云

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#13901]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

希望堡垒机云同步功能支持比格云，来实现比格云下的主机资源，通过同步任务定期管理云上资源。

### 解决方案

比格云提供了python 的sdk 方式支持对接：https://help.biggeryun.com/show/104

**Comment by BaiJiangJie** [comment]
区域贡献。
