### ISSUE TITLE
[Bug] 创建资产授权是，指定账号选择从模板中添加，提交资产授权提示服务器错误

### ISSUE THREAD

**Issue by AmadaDeusa** [jumpserver/jumpserver#13906]
### 产品版本

4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

![image](https://github.com/user-attachments/assets/a1eea70f-57d1-4c3c-bbc5-18ecbcc94795)

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/cf5367e1-4eea-442c-92dd-93ac9eeb3cc4)

### 复现步骤

创建资产授权，账号选择指定账号，模板添加，不全选，点击提交

**Comment by BaiJiangJie** [comment]
浏览器打开控制台，看一下报错 API 的 Response。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
