### ISSUE TITLE
[Feature] 能否在同一条命令过滤规则中使用多个动作

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#13908]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

同一个命令过滤规则能否支持通知拒绝和告警动作

### 解决方案

在选择动作时，可同时选择多个动作。
![image](https://github.com/user-attachments/assets/d0082854-5696-44e4-9ec9-cd209e0817d2)

**Comment by BaiJiangJie** [comment]
拒绝： 拒绝 + 告警
允许： 允许
告警： 允许 + 告警

所以，不用多选。

**Comment by Lynxhide** [comment]
我测试了一下，仅选择拒绝的话，不会发送邮件告警，谢谢

**Comment by BaiJiangJie** [comment]
如果是拒绝的话，消息接受人需要在系统设置中配置。

<img width="2556" alt="image" src="https://github.com/user-attachments/assets/e4af8547-e254-4ee5-95c7-62c2fc3a693d">

**Comment by Lynxhide** [comment]
好嘞，谢谢您，已经解决了，请问下社区版会支持钉钉以及飞书之类的机器人告警通知不？

**Comment by Lynxhide** [comment]
好嘞，谢谢
