### ISSUE TITLE
[Question] 消息通知里面没有找到批量危险命令告警这个功能选项

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#13902]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7.9

### 🐛 缺陷描述

在系统管理里面没有找到危险命令告警和批量危险命令告警这个选项
![image](https://github.com/user-attachments/assets/81147d1d-d10a-4471-900c-b61e03ef6865)

### 复现步骤

无

### 期望结果

无

### 补充信息

无

### 尝试过的解决方案

无

**Comment by BaiJiangJie** [comment]
会话和作业，下面的 命令拒绝 就是。

**Comment by Lynxhide** [comment]
再麻烦请问一下，怎么才能触发这个告警推送呢，是要符合命令过滤里面的规则吗？

**Comment by BaiJiangJie** [comment]
当用户执行的命令为拒绝的动作时会触发。

配置命令过滤规则，比如：命令为 ls，动作是拒绝。用户执行 ls 会触发。

**Comment by Lynxhide** [comment]
好嘞，谢谢，明白了
