### ISSUE TITLE
[Bug] 命令过滤把误判输出结果当成输入指令去执行，导致命令被拦截，稳定复现。

### ISSUE THREAD

**Issue by wxcen** [jumpserver/jumpserver#13904]
### 产品版本

V3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

V3.10.12 离线安装包环境，在 huawei 网络设备执行，输出的文字被当成了输入的文字执行，导致命令被拦截。

### 🐛 缺陷描述

V3.10.12 离线安装包环境，在 huawei 网络设备执行，输出的文字被当成了输入的文字执行，导致命令被拦截。

### 复现步骤

huawei 网络设备。
1、命令过滤中，增加一条禁止所有命令，优先级设置为 99。
2、命令过滤中，增加一条允许执行的命令，优先级设置为 50。
![image](https://github.com/user-attachments/assets/fd297c23-04da-4602-be25-c113b3b07c75)
![image](https://github.com/user-attachments/assets/85f0c980-5406-422b-971b-d144c7087485)
3、授权给访问，链接 huawei 网络设置资产，输入 display interface brief，然后会出现--more-- ，输入空格翻页，直到结束。
4、然后再回车，就会报错，‘ 禁止输入，，，，，’
![image](https://github.com/user-attachments/assets/72bc4380-227f-45ef-a739-cc85fde190a1)
5、然后再命令会话中看到的命令是最后输出的字符。
![image](https://github.com/user-attachments/assets/ae63a981-419c-4605-bcd8-0973738618d8)

### 期望结果

看看这么解决

**Comment by BaiJiangJie** [comment]
输入命令记录的机制，是通过回显来记录的。

输入空格翻页时，由于回显了 --more-- 之后的信息，所以当作是命令来记录了；
输入回车后，表示一条命令结束，进行解析匹配规则，显示拒绝了。

目前命令过滤存在一些问题，更好的解决方案还在寻找中。

对于你的问题，可以使用 Ctrl+c 来结束 --more-- 信息的显示，就不会记录为命令了。

**Comment by wxcen** [comment]
好的，谢谢。
