### ISSUE TITLE
[Question] 开启全局MFA后，调用生成Token接口也需要验证MFA，我们需要程序生成Token的话，如何跳过这层MFA验证？

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#13915]
### 产品版本

v3.7.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

无

### 🤔 问题描述

开启全局MFA后，调用生成Token接口也需要验证MFA，我们需要程序生成Token的话，如何跳过这层MFA验证？

### 期望结果

调用Token接口，无需验证MFA

### 补充信息

无

**Comment by BaiJiangJie** [comment]
不能跳过，MFA 也可以调用 API 完成认证。

**Comment by xiaoxiongxyy** [comment]
> 不能跳过，MFA 也可以调用 API 完成认证。

这块具体是调用哪个接口呀？

**Comment by BaiJiangJie** [comment]
在调用 API 创建 token 时， /api/v1/authentication/token/ ，如果需要认证 MFA，响应中会有。

**Comment by xiaoxiongxyy** [comment]
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/8678fcc5-bc26-4fc5-b3d7-7ede4932eee6">
这个code每次调用的时候都需要改变吗？

**Comment by xiaoxiongxyy** [comment]
> <img alt="image" width="1431" src="https://private-user-images.githubusercontent.com/85990572/357025677-8678fcc5-bc26-4fc5-b3d7-7ede4932eee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjIwNzgsIm5iZiI6MTcyMzQ2MTc3OCwicGF0aCI6Ii84NTk5MDU3Mi8zNTcwMjU2NzctODY3OGZjYzUtYmMyNi00ZmM1LWIzZDctN2VkZTQ5MzJlZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDExMjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYWM3ZDM1ZGQzNTQ0MDNkNDliZTczNmUzNjNkYjNjNDcyNDc1OGNmYWNlM2EyZTQxYzQ4ZWE2MTBmNmY3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CqSOTL5rhZ1CKOr3HvadStmqyqzv9XTGJeSkBLPd4fQ"> 这个code每次调用的时候都需要改变吗？

定时任务的时候该如何处理呢 再写一个API工具来生成code吗

**Comment by BaiJiangJie** [comment]
对啊，你可以写一个生成 code 的程序，算法都是标准的。

**Comment by xiaoxiongxyy** [comment]
> 对啊，你可以写一个生成 code 的程序，算法都是标准的。

好的 感谢🙏
