### ISSUE TITLE
[Question] Cookie里面的jms_sessionid有办法通过接口获取吗

### ISSUE THREAD

**Issue by hy520520** [jumpserver/jumpserver#13919]
### 产品版本

3.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

python Ubuntu

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/479853f1-b7fa-412a-850d-7f0dea22ecf5)
通过接口获取执行历史的命令输出，需要通过wss wss://jumpserver.com/ws/ops/tasks/log/ 获取执行的结果，使用接口获取的时候需要在Cookie携带 jms_session 
![image](https://github.com/user-attachments/assets/19655195-bd70-45bc-b5ee-8c252d31dabf)
![image](https://github.com/user-attachments/assets/bf657d9f-5be1-493b-b92d-ba79993bda95)
似乎通过token接口获取到的session无法使用，会出现403错误，直接网页登录的jumpserver拿到的session正常
![image](https://github.com/user-attachments/assets/e773e581-e413-448b-8700-0cffe03e5196)
也尝试过通过代码请求网页登录接口，也会出现403
![image](https://github.com/user-attachments/assets/bf79e000-3029-4e04-9510-b2812d6d2458)
![image](https://github.com/user-attachments/assets/54ed77b1-0c81-42f7-b7d3-5efaca1f2301)

### 期望结果

请问大家如何解决呢？

**Comment by hy520520** [comment]
直接使用网页端登录的session是可以正常使用
![image](https://github.com/user-attachments/assets/d17710bd-19df-43b3-a10c-9d5aec71ba01)

**Comment by BaiJiangJie** [comment]
是的，jms_sessionid 不能通过 API 获取。

**Comment by csi0n** [comment]
遇到了一样的问题，想将 wss://jumpserver.com/ws/ops/tasks/log/这个做为接口使用，发现使用/auth/接口获取到的jms_sessionid不能在/log/里面使用，请问有别的方法吗？

**Comment by 878816** [comment]
@hy520520 @csi0n  Hello,  这个问题解决了没，我也遇到了查询不了接口wss://jumpserver.com/ws/ops/tasks/log/的问题
