### ISSUE TITLE
[Bug] 添加资产的IP的时候不会验证格式

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13925]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

添加资产的IP的时候，随便输入都可以输进去，没有格式对错校验

### 🐛 缺陷描述

添加资产的IP的时候，随便输入都可以输进去，没有格式对错校验

### 复现步骤

添加资产的IP的时候，随便输入都可以输进去，没有格式对错校验

### 期望结果

添加资产的IP的时候，希望有校验的步骤

**Comment by Ewall555** [comment]
那个输入需要的是资产的地址，主机资产地址包含ip和域名，web资产还包含协议头，还有其他等等，前端不会去验证这个，就像浏览器url不会在前端验证你输入的url一样
