### ISSUE TITLE
[Bug] 连接 postgres 无法使用\c切换数据库

### ISSUE THREAD

**Issue by la-cat** [jumpserver/jumpserver#13928]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v4.0.1 版本是从v3.10.12升级上来的，使用docker-compose部署

### 🐛 缺陷描述

postgres 配置的默认数据库是postgres，使用pg命令:\c dbname 无法切换数据库
报错：error: unknown command
![image](https://github.com/user-attachments/assets/4a1f7240-7adf-414f-ae92-eb9089fa7a8f)

### 复现步骤

增加postgres 数据库并连接，使用`\c dbname`切换数据库

### 期望结果

\c dbname 能切换数据库增删查改数据

**Comment by Ewall555** [comment]
现在是用usql工具来连接数据库的，默认连接到的数据库是你在jumpserver中配置的数据库资产里的那个默认数据库，连接后，你可以直接使用sql语句

**Comment by MissakaI-Cloudtrix** [comment]
Is this issue resolved or is there a workaround. Because I am having the same issue and usql command `\c` is not available in the `\?` either. If so how to resolve this.
