### ISSUE TITLE
[Feature] web终端操作优化

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13921]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

Web端进行Linux操作系统操作的时候，下面有一个命令行，希望可以可以输入多行命令，就像xshell客户端那样

### 解决方案

就像xshell客户端那样

**Comment by BaiJiangJie** [comment]
使用 && 呢？
