### ISSUE TITLE
[Bug] 资产和资产组删掉之后仍然会有数字显示

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13924]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

资产和资产组删除之后，统计数据不会第一时间刷新，还会保留删除之前的数据

### 🐛 缺陷描述

资产和资产组删除之后，统计数据不会第一时间刷新，还会保留删除之前的数据

### 复现步骤

资产和资产组删除之后，统计数据不会第一时间刷新，还会保留删除之前的数据

### 期望结果

资产和资产组删除之后，统计数据第一时间刷新

**Comment by BaiJiangJie** [comment]
有缓存，等一段时间就会更新。
