### ISSUE TITLE
[Question]  平台列表网络设备中H3C 设备某些功能无法更改

### ISSUE THREAD

**Issue by de-conf** [jumpserver/jumpserver#13929]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v4.0.1 版本 是二次升级   V2.28.6 ----> V3.0.12 --->V4.0.1  升级上来的，使用docker-compose部署,单机模式

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/cc276b7d-e6e8-46ef-a6de-719a30f23d9e)
平台列表中 H3C 某些功能项目无法更改,如图 SSH OLD VERSION
导致无法连接设备

![image](https://github.com/user-attachments/assets/6fd92879-2478-4aa7-acf6-eb17309c71c2)

H3C 自动化功能也无法使用,如上图所示

### 期望结果

上述功能正常使用,或者提供可以正常使用的方法

**Comment by BaiJiangJie** [comment]
克隆一个平台，进行修改。

**Comment by de-conf** [comment]
克隆后某些项目依旧无法修改.是企业功能吗?
![image](https://github.com/user-attachments/assets/aa2618a5-7fac-4878-a5e6-5b54508c2d01)
