### ISSUE TITLE
[Feature] 授权批量选中之后无法批量逆操作

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13926]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

授权批量选中之后无法批量逆操作，比如选中100个资产，现在这100个资产不想选了，这个时候就需要一个一个取消，没有批量取消

### 解决方案

授权批量选中之后无法批量逆操作，比如选中100个资产，现在这100个资产不想选了，这个时候有一个批量取消打钩

**Comment by Ewall555** [comment]
将批量勾选的选项框取消勾选
