### ISSUE TITLE
Luna左侧栏无法完全隐藏，Windows资产分辨率低

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#1392]
[简述你的问题]

##### 使用版本
1.3.1-2

##### 问题复现步骤
1. luna 1.3.1-101 web终端点击隐藏左侧栏，页面右侧依然是一块留空，没有完全展开
2. 连接Windows资产时发现分辨率较低，模糊不清，体验感不好，

##### 具体表现[截图可能会更好些,最好能截全]
建议：资产桌面做成可全屏显示比较好，这样就无需下拉滚动条显示整个资产桌面。

##### 其他

[注:] 完成后请关闭 issue

**Comment by anjia0532** [comment]
代码里写死的dpi:96

**Comment by vicentwu** [comment]
dpi参数是否可以不指定参数？让其自适应？

**Comment by anjia0532** [comment]
我不是开发者，只是用的时候发现的，这需要官方开发人员回复。
