### ISSUE TITLE
[Feature] 授权界面的时候选择账号的时候，账号需要有个排序

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13927]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

授权界面的时候选择账号的时候，目前账号是乱序的，需要有排序

### 解决方案

授权界面的时候选择账号的时候，账号需要有个排序

**Comment by BaiJiangJie** [comment]
授权页面的账号选择，只是提示，用户可以手动输入任何账号。

排序的规则是按所选资产中共有同名账号的数量倒序排列的。
