### ISSUE TITLE
[Feature] 资产平台的默认资产可以编辑

### ISSUE THREAD

**Issue by Richard-kkk** [jumpserver/jumpserver#13923]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

资产那边有一个资产平台，资产平台里面有好多的默认模板，现在默认模板不可以更改，想要变成可更改，然后旁边有一个回复默认设置，这样更简洁。

### 解决方案

资产那边有一个资产平台，资产平台里面有好多的默认模板，现在默认模板不可以更改，想要变成可更改，然后旁边有一个回复默认设置，这样更简洁。

**Comment by Ewall555** [comment]
克隆一个平台，然后资产使用这个创建的克隆平台即可自定义了
