### ISSUE TITLE
[Bug] 账号推送失败：机器上 /home/appuser 目录已删除，但是 appuser 用户未删除，导致账号推送失败

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#13936]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

创建账户推送任务，执失败：机器上 /home/appuser 目录已删除，但是用户 appuser 用户未删除，导致账号推送失败。

### 🐛 缺陷描述

创建账户推送任务，执失败：机器上 /home/appuser 目录已删除，但是用户 appuser 用户未删除，导致账号推送失败。
<img width="802" alt="image" src="https://github.com/user-attachments/assets/5eed494d-594f-449c-a7e8-c0a337e4dcea">

### 复现步骤

1.在一台机器上创建用户 appuser:  useradd appuser；
2.删除 /home/appuser 目录；
3.创建账号推送任务，推送 appuser 账号，推送失败。

### 期望结果

判断出用户存在，但是家目录不存在，则创建家目录并设置家目录权限。

**Comment by BaiJiangJie** [comment]
为什么要手动删掉用户 Home 目录。

**Comment by liufei20151013** [comment]
有客户那边的镜像没处理感觉，删了home目录，没删除用户，以前v2.6是支持这种账号推送，会判断用户是否存在，home目录是否存在，不存在就新建home目录，v3判断用户存在后，没有去判断home是否存在，如果home目录不存在，账号推送就会报上面的错误。

**Comment by BaiJiangJie** [comment]
后面版本处理一下。
