### ISSUE TITLE
[Feature] 提供一个配置管理员角色，允许某部门TL管理配置部门下的资产授权

### ISSUE THREAD

**Issue by opsarno** [jumpserver/jumpserver#13934]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

RT，提供一个配置管理员角色，允许某部门TL管理配置部门下的资产授权。 目前有实现的方式吗？ 如没有后续是否考虑此需求？

### 解决方案

系统管理员 拥有最高权限
配置管理员 拥有授权节点的所有权限
审计管理员 主要用于审计
普通用户  日常用户使用

**Comment by opsarno** [comment]
补充一个需求：帐号创建 高级参数能否提供指定 UID GID 的能力？  

比如我想从现有堡垒机迁移到 JMS ，但我之前帐号已经规范化了 UID GID，如果 JMS 不能直接支持，就只能在机器安装的时候，初始化提前创建好了。

**Comment by BaiJiangJie** [comment]
企业版支持自定义用户角色，管理员可以自定义配置管理员角色。

**Comment by BaiJiangJie** [comment]
账号的，UID GID 将来可以支持管理员配置，目前不支持。
