### ISSUE TITLE
[Feature] Luna 配置设置里新增键盘布局：US English (Dvorak)

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#13938]
### 产品版本

V3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

Luna 配置设置里新增键盘布局：US English (Dvorak)
https://kbdlayout.info/KBDDV/

### 解决方案

Luna 配置设置里新增键盘布局：US English (Dvorak)
https://kbdlayout.info/KBDDV/

### 补充信息

无

**Comment by BaiJiangJie** [comment]
https://guacamole.apache.org/doc/gug/configuring-guacamole.html#session-settings

这是所有可以支持的 Keyboard layout，没有发现 US English (Dvorak)。
