### ISSUE TITLE
[Question] Problem with the endpoint

### ISSUE THREAD

**Issue by jonatanfreire** [jumpserver/jumpserver#13935]
### Product Version

v4.0.2

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

I'm trying to access other databases from the same PMA

### 🤔 Question Description

I created an endpoint and linked it via TAG to a device.

However, when I try to access this device via the endpoint, I receive a message that the connection was refused.

Validating the koko container log, I receive the information that authentication failed.

Where do I configure authentication for the endpoint?

[GIN] 2024/08/10 - 23:30:01 | 200 |      66.212µs |             ::1 | GET "/koko/health/"
2024-08-10 23:30:02 [ERROR] Check user cookie failed: map[] GET http://core:8080/api/v1/users/profile/ failed, get code: 401, {"detail": "Authentication credentials were not provided.","code":"not_authenticated"}
[GIN] 2024/08/10 - 23:30:02 | 302 |    29.73061ms |  192.168.100.1 | GET "/koko/connect/?disableautohash=false&token=e04f36f3-517f-4ca6-bc89-d8394f970959&_=1723303802462"
[GIN] 2024/08/10 - 23:30:11 | 200 |      64.943µs |             ::1 | GET "/koko/health/"
[GIN] 2024/08/10 - 23:30:21 | 200 |      193.84µs |             ::1 | GET "/koko/health/"
[GIN] 2024/08/10 - 23:30:31 | 200 |      68.608µs |             ::1 | GET "/koko/health/"
root@jumpserver:/var/log# docker logs jms_koko

**Comment by BaiJiangJie** [comment]
`SESSION_COOKIE_DOMAIN`

You need to configure SESSION_COOKIE_DOMAIN in the `config.txt`.

For example, you have two domain addresses, one is `a.example.com`, and the other is `b.example.com`

Then you should configure:

`SESSION_COOKIE_DOMAIN=example.com`

`DOMAINS=a.example.com,b.example.com`

After modifying the configuration, restart the service `./jmsctl restart`

**Comment by BaiJiangJie** [comment]
Also, I need the error message on your asset connection page.

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
