### ISSUE TITLE
[Question] 負載均衡 haproxy 設定

### ISSUE THREAD

**Issue by GOGOrun2** [jumpserver/jumpserver#13930]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Rocky 9.3
HAProxy version 2.4.22
docs https://docs.jumpserver.org/zh/master/install/setup_by_lb/#haproxy

### 🤔 Question Description

1. 依據文檔中的配置,jumpserver 01~03 都沒有監聽 30000 這個 Port, 在 haproxy stats 上面接會呈現 down,
請問段配置是否為必要的存在,

![image](https://github.com/user-attachments/assets/baf03223-3ecb-4a73-8d2b-bbe7f0e8f8e4)

---官方範例內容---
listen jms-magnus
    bind *:30000
    mode tcp

    option tcp-check

    fullconn 500
    balance source
    server 192.168.100.21 192.168.100.21:30000 weight 1 check inter 2s rise 2 fall 3 send-proxy
    server 192.168.100.22 192.168.100.22:30000 weight 1 check inter 2s rise 2 fall 3 send-proxy
    server 192.168.100.23 192.168.100.23:30000 weight 1 check inter 2s rise 2 fall 3 send-proxy
    server 192.168.100.24 192.168.100.24:30000 weight 1 check inter 2s rise 2 fall 3 send-proxy

2. 依據文檔中的配置  listen jms-koko  與 listen jms-lion 是否有需要  bind 端口

感謝協助

**Comment by wojiushixiaobai** [comment]
不需要，只检查健康状态，不需要对外提供服务

**Comment by GOGOrun2** [comment]
感謝回復～
我的理解若有誤,再麻煩您指點
1. listen jms-magnus bind *:30000 可以移除
2. listen jms-koko 與 listen jms-lion 不需要 bind 
謝謝您

**Comment by wojiushixiaobai** [comment]
v4 社区版已经没有 magnus 组件，可以移除。
高可用可以尝试使用 [Docker Swarm 集群](https://github.com/jumpserver/Dockerfile#%E9%9B%86%E7%BE%A4%E9%83%A8%E7%BD%B2) 方案

**Comment by GOGOrun2** [comment]
感謝協助.
