### ISSUE TITLE
[Question]  How to configure a fixed account for user access in Jumpserver?

### ISSUE THREAD

**Issue by HuaweiDonor** [jumpserver/jumpserver#13937]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

-

### 🤔 Question Description

Hello,

We are currently using Jumpserver to manage access to our virtual machines. During the process of adding users for access via Jumpserver, it seems that the first available account is automatically used for this purpose.

Is it possible to configure Jumpserver to always use a fixed, predefined account for this access instead of selecting the first available one? If so, could you please provide guidance or point me to the relevant documentation?

Thank you!

### Additional Information

-

**Comment by BaiJiangJie** [comment]
After the user has authorized assets and multiple accounts, the user can choose the account to log in when connecting assets on the Luna page.

The documentation is still being improved, you can take a look at the Quickstart.

https://www.jumpserver.com/docs/quickstart

**Comment by HuaweiDonor** [comment]
What about first time adding assets? Can use fixed account for adding assets?

**Comment by BaiJiangJie** [comment]
Yes, you can add an account when you create an asset for the first time.

**Comment by HuaweiDonor** [comment]
"When using Jump Server, when adding a new account, we encounter the following issue. If we have a user, John, who can log in to the server and he adds a user named Pavel, the system logs show that John added Pavel. However, we need it to always appear as a technical account, such as Jump Server Administrator, who adds the user Pavel."

**Comment by BaiJiangJie** [comment]
Not supported

**Comment by HuaweiDonor** [comment]
Will you be adding these functionality in future releases?

**Comment by BaiJiangJie** [comment]
There are no plans yet.

**Comment by HuaweiDonor** [comment]
Thanks for your replay.
