### ISSUE TITLE
[Question] RemoteApp Configuration

### ISSUE THREAD

**Issue by lesou98** [jumpserver/jumpserver#13933]
### Product Version

jumpServer Community version GPLv3 Version: 	v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jumpServer Community version GPLv3 Version: 	v4.0.2

### 🤔 Question Description

cant accesss to website asset t(HTTPS) from jumserver . i got this error Tips: No valid remote application deployment machine found, current resource cannot be connected. Please contact the administrator for assistance  even if i already configure website asset in my jumpserver

**Comment by BaiJiangJie** [comment]
You also need to configure the RemoteApp machine on the `System Settings - RemoteApp` page.

**Comment by BaiJiangJie** [comment]
<img width="2557" alt="image" src="https://github.com/user-attachments/assets/35ab9cd2-add0-4d8e-98f3-fe26b8323318">
