### ISSUE TITLE
[Bug]  Zmodem 传输文件出现 CRC 错误

### ISSUE THREAD

**Issue by de-conf** [jumpserver/jumpserver#13939]
### Product Version

v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

server: ubuntu 20.04
cilent: arch linux
终端:  kconsole
通过jumpsever ssh连接

### 🐛 Bug Description

server 端 终端乱码如下:
```
sz xxx.tar.gz
���▒K���▒�▒@��▒\N�^������'[�▒[▒�C[`�▒��▒�q▒S���Z▒��▒Y@▒^��%▒�>D���S▒�L^�q�▒S�M▒IQ▒ر��▒X▒I�5▒��▒�m▒Ȳe)�;W▒��I�U�H��IP�▒S^���▒��▒��=��▒I�}▒V|▒K▒�s��{▒�&L▒@�d▒P�▒��\�▒���▒[��(▒�O=��h��▒^▒�ع▒�7▒Ͽ▒A�|▒Yo▒^��▒\��r^�V��"▒TM▒����▒�▒H1v9�z▒[▒D�z▒_▒B�w9�zߧ�▒T�▒R�▒MC▒�▒�$�WR?�w�▒�▒]�B▒S▒�V�▒\Q# ▒MV�▒\�` ▒CW�▒\�\ ?▒Al▒OY▒�1G▒��6Gd▒���<▒IǱ]%▒�HI▒O��0C%}▒I�~WI▒�Vj��J�▒J▒�J+�wG@�▒Bl��?
```

客户端kconsole 提示如下:    

```
Note: pressing Cancel will almost certainly cause the terminal to be unusable.
-----------------
rz waiting to receive.
Receiving: zabbix-agent-7-upgrade.tar.gz...................................................................................................................
Retry 0: Bad CRC
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Got ERROR
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Bad CRC
Retry 0: Got ERROR
Retry 0: Got ERROR
Retry 0: Got ERROR
Transfer incomplete
```

此外,使用 ` trz `  [trzsz 见此链接](https://trzsz.github.io/cn/) 也无法进行传输. server 执行命令如下. 会一直停留,无法弹出下载页面
```
~/go/bin/tsz zabbix-agent-7-upgrade.tar.gz 
::TRZSZ:TRANSFER:S:1.1.7:2343152736600:18731
```

### Recurrence Steps

server sz 传输文件 100%复现

server tsz 传输文件 100%复现

### Expected Behavior

正常文件传输下载

### Additional Information

null

### Attempted Solutions

null

**Comment by BaiJiangJie** [comment]
应该是不支持这个终端工具。

**Comment by de-conf** [comment]
> 应该是不支持这个终端工具。
是jump server 不支持 Zmodem 传输文件吗? 还是我的终端有问题?

另外能否集成下 trzsz 的功能?
我换到trzsz 传输目前也卡住了

**Comment by BaiJiangJie** [comment]
暂时不考虑集成 trzsz。

**Comment by de-conf** [comment]
ok,了解了,谢谢!

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10679#issuecomment-1586963270
