### ISSUE TITLE
SSH key如何设置自动生成

### ISSUE THREAD

**Issue by blank614** [jumpserver/jumpserver#1393]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.1
##### 具体表现[截图可能会更好些,最好能截全]
新版本的SSH key，都是要用户自己上传，如何修改，让系统自动生成？并且将SSH key加密码？
每次新建用户的时候，通过用户的邮箱，推送给他？

##### 其他

[注:] 完成后请关闭 issue

**Comment by blank614** [comment]
我的意思是，在新建用户的时候，直接发的第一份邮件里面带自动生成的key（带密码保护），屏蔽掉用户上传自己的key的操作。这个要如何修改呢？

**Comment by wojiushixiaobai** [comment]
@blank614 新版本新增了MFA验证，key推荐使用系统自动生成或者让用户自己上传，如果想要像0.3一样，直接发送key给用户需要修改下代码。

**Comment by blank614** [comment]
如何修改代码呢？可否指点一下，哪几个关键类？谢谢~

**Comment by ibuler** [comment]
暂时不考虑这个功能，不够通用，我认为用户是有修改需求的，用户可能使用同一个key登陆 Jumpserver github等，如果是jumpserver自动生成的话，key可能就不一样了，登录 jumpserver和github使用不同的key, 操作的时候可能需要手工指定了，带来了新的麻烦。

先关闭issue了，有问题，可以重新打开
