### ISSUE TITLE
Syslog not working

### ISSUE THREAD

**Issue by Benjaminnworah** [jumpserver/jumpserver#13947]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Jumpserver community Edition installed on Ubuntu endpoint

### 🤔 Question Description

I installed Jumpserver on an Ubuntu endpoint, i want to send syslog messages to my syslog server. i have followed the below steps to configure syslog on my jumpserver. Please not i have tried using `true` as well in the parameter "SYSLOG_ENABLE"

vi /opt/jumpserver/config/config.txt

# Syslog setting
SYSLOG_ENABLE=True
SYSLOG_ADDR=<ip_address_of_my_syslog_server>:514   # Host Ip and port number of Syslog service

./jmsctl.sh restart

After the configuration, i added a user to my jumpserver following this link https://www.jumpserver.com/docs/quickstart#create-user, and i expected to see this event sent to my syslog server, but unfortunately i see no such user creation event on my syslog srever.

please assist

**Comment by BaiJiangJie** [comment]
create user, create asset, create authorization, none of them?

**Comment by Benjaminnworah** [comment]
yes. none of them worked

**Comment by BaiJiangJie** [comment]
Take a screenshot to see the data in the operation log?

**Comment by BaiJiangJie** [comment]
And execute the following command to check whether the configuration is successful:
```

docker exec -it jms_core bash

cd apps

from django.conf import settings

settings.SYSLOG_ENABLE
settings.LOGGING

```

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13900

Maybe it's a problem with your environment. The user of this issue has successfully configured it.
