### ISSUE TITLE
[Bug] 4.0.1 资产树列表点击下拉框后无内容展示

### ISSUE THREAD

**Issue by si3041242** [jumpserver/jumpserver#13943]
### 产品版本

4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Ubuntu22.04 
4C8G

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/abb979af-5318-4cfd-9163-b1a73c549f70)
小箭头已经是下拉状态，但是都无内容，只能在右侧列表中看到

### 复现步骤

无痕模式也点过 下拉资产树列表都看不到资产

**Comment by BaiJiangJie** [comment]
资产列表页面中的左侧资产树只显示节点，不显示资产。
右侧资产列表显示的是当前选中节点下的资产或所有子节点下的资产。（右击节点可以设置）
