### ISSUE TITLE
[Feature] V4版本账号管理，资产关联账号问题

### ISSUE THREAD

**Issue by laodengto** [jumpserver/jumpserver#13944]
### 产品版本

V4.01

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

V4 版本账号管理，账号批量关联资产问题
操作过程：账号管理-->账号列表--->添加--->选择资产
V3 可以批量，V4 没有了
![image](https://github.com/user-attachments/assets/9104cdf0-5789-474c-9986-496f3b3f1265)
![image](https://github.com/user-attachments/assets/18eef204-fecd-4659-b01f-ab7846c14b8e)

### 解决方案

在V4版本，账号列表创建账号，可以批量选择资产节点

**Comment by BaiJiangJie** [comment]
可以搜索添加，避免页面中弹窗太多。
