### ISSUE TITLE
[Bug] 资产连接性测试会产生defunct进程

### ISSUE THREAD

**Issue by newton163** [jumpserver/jumpserver#13940]
### Product Version

v4.0.1-ce

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 20.04.5 LTS
Linux 5.4.0-125-generic

REPOSITORY                                          TAG             IMAGE ID       CREATED         SIZE
jumpserver/web                                      v4.0.1-ce       a0ef6bf1950c   3 weeks ago     208MB
jumpserver/koko                                     v4.0.1-ce       f4a36144e852   3 weeks ago     587MB
jumpserver/chen                                     v4.0.1-ce       8bf5bd4d3715   3 weeks ago     442MB
jumpserver/lion                                     v4.0.1-ce       8f4ae77a1311   3 weeks ago     269MB
jumpserver/core                                     v4.0.1-ce       962c206958ac   3 weeks ago     1.04GB

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/8314c7ea-7e85-4cfb-9358-866f74e81140)
点击连接性测试并成功后，会产生defunct僵尸进程，重启jms_celery后恢复

![image](https://github.com/user-attachments/assets/af543aae-2447-47b8-9cde-9deb9e43a963)

### Recurrence Steps

资产列表点击连接性测试

### Expected Behavior

jumpserver服务器系统内会有僵尸进程

### Attempted Solutions

重启celery容器

**Comment by BaiJiangJie** [comment]
这个僵尸进程，一般情况下会自动回收的。

**Comment by newton163** [comment]
是后台程序有回收周期吗？目前看两小时以上还是没有回收的
![image](https://github.com/user-attachments/assets/44d744fe-1ac3-448e-b1d8-e0245d56efd8)

**Comment by BaiJiangJie** [comment]
Fixed in v4.1.0
