### ISSUE TITLE
登陆验证码留空也能提交

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#1394]
[简述你的问题]

##### 使用版本
1.3.0

##### 问题复现步骤
登陆输入了账号密码后, 验证码留空也能回车提交.

##### 其他
建议对验证码进行基本4个字符校验再提交 避免无意义请求

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
#1416

**Comment by ibuler** [comment]
处理一下PR 冲突问题
