### ISSUE TITLE
[Feature] 命令过滤的告警功能

### ISSUE THREAD

**Issue by laodengto** [jumpserver/jumpserver#13945]
### 产品版本

V3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

设置命令过滤规则为告警，用户再匹配对应执行命令后，希望有提示：是否继续执行用户自己输入y/n就行
![image](https://github.com/user-attachments/assets/3841982f-782c-4d99-bc33-cff800d48e87)
![image](https://github.com/user-attachments/assets/30ff17ee-49ca-4733-bcca-6b12ccfe563d)

### 解决方案

设置命令过滤规则为告警，用户再匹配对应执行命令后，希望有提示：是否继续执行用户自己输入y/n就行
例如：如下截图，不是需要审批人员去审批
![image](https://github.com/user-attachments/assets/647c7f10-2267-4722-9b26-caee55fb1821)

**Comment by BaiJiangJie** [comment]
嗯，不错的提议，后面版本考虑一下。
