### ISSUE TITLE
[Bug] 使用SSH客户端的方式拉起 MobaXterm 只能打开一个会话

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#13950]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

 使用SSH客户端的方式拉起 MobaXterm 只能打开一个会话

### 🐛 缺陷描述

 使用SSH客户端的方式拉起 MobaXterm 只能打开一个会话

### 复现步骤

1、ssh客户端方式连接Linux资产，客户端 MobaXterm v24.2
![image](https://github.com/user-attachments/assets/00c9e3a3-b432-4f01-8223-51b4909d7e6f)

2、第一次拉起连接正常
![image](https://github.com/user-attachments/assets/a15e37ae-288f-476f-81da-91dd31066812)

3、再次拉起一次会话，连接失败，无反应。

补充：使用Putty、Xshell、SecureCRT 客户端可以正常拉起多个会话，使用正常

**Comment by BaiJiangJie** [comment]
那是客户端的问题吧

**Comment by LinuxLeader** [comment]
其他同事使用MobaXterm也是相同的问题，单独使用MobaXterm是可以打开多个会话的。

**Comment by BaiJiangJie** [comment]
找 @Halo1236 帮忙看一下客户端拉起逻辑。
