### ISSUE TITLE
[Question] docs active/stand-by cluster installation

### ISSUE THREAD

**Issue by jonatanfreire** [jumpserver/jumpserver#13952]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

I want to create a cluster with 2 or 3 servers

### 🤔 Question Description

I would like to know how to install using an active/stand-by cluster.

Do you have any documentation about this?

**Comment by BaiJiangJie** [comment]
There is no documentation for v4 yet, but there is Chinese documentation for v3.

https://docs.jumpserver.org/zh/v3/installation/setup_linux_lb/requirements/
