### ISSUE TITLE
[Bug] Docker Version > 27

### ISSUE THREAD

**Issue by GoodGitGot** [jumpserver/jumpserver#13955]
### Product Version

v3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

cpu architecture : x86_64
os : amazon linux 2
linux kernel : 5.10
docker : Docker version 18.06.3-ce, build d7080c1

### 🐛 Bug Description

During the upgrade process from v3.10.12 to v4.0.2, an error 'failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header' occurred while pulling the jumpserver/lion:v4.0.2-ce image. (jumpserver/web:v4.0.2-ce, jumpserver/core:v4.0.2-ce, jumpserver/koko:v4.0.2-ce, jumpserver/chen:v4.0.2-ce is fine)

### Recurrence Steps

There is no DOCKER_IMAGE_MIRROR, DOCKER_IMAGE_PREFIX, DOCKER_DIR variables in /opt/jumpserver/config/config.txt file.

[root@xxx jumpserver-installer-v4.0.0]# ./jmsctl.sh upgrade

### Additional Information

.
.
.
[jumpserver/lion:v4.0.2-ce] pulling
v4.0.2-ce: Pulling from jumpserver/lion
57500d4e37bb: Extracting [==================================================>]  26.39MB/26.39MB
bf7a4579d02d: Download complete
83edcc9a511b: Download complete
09d04cf4b7d0: Download complete
87b291206e85: Download complete
ac531ca64c21: Download complete
5e6d013e8ebb: Download complete
2fee8e9887e8: Download complete
f571ba183429: Download complete
b31c8804ea82: Download complete
ba1f1a34b13c: Download complete
c77d43991b3c: Download complete
cfde6317b29a: Download complete
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header

Failed to pull image jumpserver/lion:v4.0.2-ce

3. Backup database
Backing up...
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
  --config string      Location of client config files (default "/root/.docker")
 -D, --debug              Enable debug mode
 -H, --host list          Daemon socket(s) to connect to
 -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
  --tls                Use TLS; implied by --tlsverify
  --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
  --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
  --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
  --tlsverify          Use TLS and verify the remote
 -v, --version            Print version information and quit

Management Commands:
 checkpoint  Manage checkpoints
 config      Manage Docker configs
 container   Manage containers
 image       Manage images
 manifest    Manage Docker image manifests and manifest lists
 network     Manage networks
 node        Manage Swarm nodes
 plugin      Manage plugins
 secret      Manage Docker secrets
 service     Manage services
 stack       Manage Docker stacks
 swarm       Manage Swarm
 system      Manage Docker
 trust       Manage trust on Docker images
 volume      Manage volumes

Commands:
 attach      Attach local standard input, output, and error streams to a running container
 build       Build an image from a Dockerfile
 commit      Create a new image from a container's changes
 cp          Copy files/folders between a container and the local filesystem
 create      Create a new container
 deploy      Deploy a new stack or update an existing stack
 diff        Inspect changes to files or directories on a container's filesystem
 events      Get real time events from the server
 exec        Run a command in a running container
 export      Export a container's filesystem as a tar archive
 history     Show the history of an image
 images      List images
 import      Import the contents from a tarball to create a filesystem image
 info        Display system-wide information
 inspect     Return low-level information on Docker objects
 kill        Kill one or more running containers
 load        Load an image from a tar archive or STDIN
 login       Log in to a Docker registry
 logout      Log out from a Docker registry
 logs        Fetch the logs of a container
 pause       Pause all processes within one or more containers
 port        List port mappings or a specific mapping for the container
 ps          List containers
 pull        Pull an image or a repository from a registry
 push        Push an image or a repository to a registry
 rename      Rename a container
 restart     Restart one or more containers
 rm          Remove one or more containers
 rmi         Remove one or more images
 run         Run a command in a new container
 save        Save one or more images to a tar archive (streamed to STDOUT by default)
 search      Search the Docker Hub for images
 start       Start one or more stopped containers
 stats       Display a live stream of container(s) resource usage statistics
 stop        Stop one or more running containers
 tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
 top         Display the running processes of a container
 unpause     Unpause all processes within one or more containers
 update      Update configuration of one or more containers
 version     Show the Docker version information
 wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

Failed to backup the database. Continue to upgrade? (y/n)  (default n): n

### Attempted Solutions

The same error occurs not only v4.0.2 but also v4.0.1 and v4.0.0

**Comment by BaiJiangJie** [comment]
Try the command on the host:
`docker pull jumpserver/lion:v4.0.2-ce`

**Comment by GoodGitGot** [comment]
[root@xxx jumpserver-installer-v4.0.2]# docker pull jumpserver/lion:v4.0.2-ce
v4.0.2-ce: Pulling from jumpserver/lion
57500d4e37bb: Extracting [==================================================>]  26.39MB/26.39MB
bf7a4579d02d: Download complete
83edcc9a511b: Download complete
09d04cf4b7d0: Download complete
87b291206e85: Download complete
ac531ca64c21: Download complete
5e6d013e8ebb: Download complete
2fee8e9887e8: Download complete
f571ba183429: Download complete
b31c8804ea82: Download complete
ba1f1a34b13c: Download complete
c77d43991b3c: Download complete
cfde6317b29a: Download complete
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
[root@xxx jumpserver-installer-v4.0.2]#

**Comment by BaiJiangJie** [comment]
docker -v

**Comment by GoodGitGot** [comment]
[root@xxx jumpserver-installer-v4.0.2]# docker -v
Docker version 18.06.3-ce, build d7080c1
[root@xxx jumpserver-installer-v4.0.2]#

**Comment by BaiJiangJie** [comment]
Upgrade to the latest Docker version.

**Comment by BaiJiangJie** [comment]
For example, Docker version 27.1.1

**Comment by GoodGitGot** [comment]
All right.  I will give feedback tomorrow.  thank you very much.

**Comment by GoodGitGot** [comment]
Thank you! It work's!
Below is the procedure I followed.  Hope this helps.
====================================

The admin account was changed to a different name for security reasons, but restored to its original name as admin (otherwise an error will occur during upgrade).

systemctl stop docker
systemctl disable docker

rm -rf /etc/systemd/system/docker.service
rm -rf /etc/docker/*
rm -rf /usr/bin/docker*

cd /opt/jumpserver-installer-v4.0.2/scripts
./2_install_docker.sh

ln -s /usr/local/bin/* /usr/bin/
ln -s /usr/local/libexec/docker/cli-plugins/docker-compose /usr/bin/

[root@xxx jumpserver-installer-v4.0.2]# docker -v
Docker version 27.0.3, build 7d4bcd8
[root@xxx jumpserver-installer-v4.0.2]# docker-compose -v
Docker Compose version v2.29.0

**Comment by BaiJiangJie** [comment]
Yes, must have the **admin** username when upgrading. This issue will be fixed in v4.1.0.
