### ISSUE TITLE
[Bug] web页面无法通过lrzsz的sz指令下载文件

### ISSUE THREAD

**Issue by GabeCloy** [jumpserver/jumpserver#13954]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

linux 一键安装,跑在docker容器上
Chrome 版本 127.0.6533.100 (正式版本) (arm64)

### 🐛 Bug Description

web页面无法通过lrzsz的sz指令下载文件,显示100%后一直卡住,

### Recurrence Steps

web终端上使用sz下载任意文件

**Comment by BaiJiangJie** [comment]
lrzsz 对大文件支持的不是很好，大文件使用文件管理，小文件可以使用 lrzsz。

你下载的文件多大？

**Comment by GabeCloy** [comment]
237byte , 目前发现清空浏览器缓存后就可以使用了(升级版本后)
