### ISSUE TITLE
[Bug] minio 地区问题

### ISSUE THREAD

**Issue by wmbin** [jumpserver/jumpserver#13951]
### Product Version

3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [X] Source Code

### Environment Information

docker环境

### 🐛 Bug Description

新版本minio默认带有地区,jumpserver 储存里面Ceph没有填写地区地方，导致上传报错

### Recurrence Steps

新版本minio默认带有地区,jumpserver 储存里面Ceph没有填写地区地方，导致上传报错

**Comment by BaiJiangJie** [comment]
你的 MinIO 使用的是 Ceph 类型创建的吗？

**Comment by wmbin** [comment]
> 你使用的 MinIO 是 Ceph 类型创建的吗？

是的

**Comment by BaiJiangJie** [comment]
最新版本 Ceph 本身会有地区问题吗？

**Comment by wmbin** [comment]
> 最新版本 Ceph 本身会有地区问题吗？

使用的是3.10.12，暂时不想升级4.x

**Comment by BaiJiangJie** [comment]
有没有使用 s3 的配置试试？MinIO 也是兼容 s3 接口的。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
