### ISSUE TITLE
[Question]  POST /accounts/accounts/bulk/

### ISSUE THREAD

**Issue by szr20010820** [jumpserver/jumpserver#13960]
### Product Version

4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

4.0.1

### 🤔 Question Description

![image](https://github.com/user-attachments/assets/ad3dde70-37ee-4429-aadc-4bab66f2d657)

`[
  {
    "asset": "game-1(172.18.50.30)",
    "error": "密钥不合法或密钥密码错误",
    "state": "error"
  }
]`

``

### Expected Behavior

通过API 添加账号 密钥不合法 这里前端二次加密是怎么加密的 我根据src/utils/crypto.js  文件进行加密后 仍然密钥不合法

**Comment by BaiJiangJie** [comment]
页面上提交一下，把 payload 数据 copy 过来改一下账号信息提交试试。

**Comment by szr20010820** [comment]
> 页面上提交一下，把有效负载数据复制过来改一下账号信息提交尝试。

使用 页面提交的 payload 中secret的值是可以的 但是这个值会过期吧 我退出账号登录 然后在使用这个去添加账号会出现 
`{
  "detail": "身份认证信息未提供。",
  "code": "not_authenticated"
}`
实际上 我在 /api/docs/ 并未退出

以下是我 模拟crypto.js 的测试密钥代码
![image](https://github.com/user-attachments/assets/e3b10a8f-1036-4a9e-8fdd-1764d32f1912)

**Comment by BaiJiangJie** [comment]
那就是你的 key 不对。

**Comment by szr20010820** [comment]
> 这就是你的关键，跟加不加密没有关系。

key是对的呀 web端用的key 和代码里的key是一样的

**Comment by BaiJiangJie** [comment]
校验一下。
```
docker exec -it jms_core bash

cd apps

python manage.py shell

from accounts.utils import *

ssh_key = "输入你的sshkey"

validate_ssh_key(ssh_key)

```

**Comment by szr20010820** [comment]
> 执行下面的命令检查一下。
> 
> ```
> docker exec -it jms_core bash
> 
> cd apps
> 
> python manage.py shell
> 
> from accounts.utils import *
> 
> ssh_key = "输入你的sshkey"
> 
> validate_ssh_key(ssh_key)
> ```
我根据命令检查发现 确实密钥不可用
我现在 是这样的 
有两对密钥 分别用来连接root 和普通用户 我使用root的这对密钥来通过API添加账号是可以添加的，但是不能登录，因为密钥不匹配，通过普通用户的密钥对来通过API添加 是添加不了的  我需要怎么做才能使用普通用户的密钥也可以通过API来添加 账号
![image](https://github.com/user-attachments/assets/f78ae872-6ce8-4a97-8dc2-45a6a96a04fd)
![image](https://github.com/user-attachments/assets/b7a799d5-375f-48a8-9a5d-7a86672c5526)

**Comment by BaiJiangJie** [comment]
JumpServer 在保存私钥的时候都会转化为 OpenSSH 格式。

https://bkssl.com/ssl/ssh_transform

使用上面的网站，测试一下你的两对私钥是否可以转化。

**Comment by szr20010820** [comment]
> https://bkssl.com/ssl/ssh_transform

使用转换后的密钥 可以成功添加 谢谢

**Comment by BaiJiangJie** [comment]
好的，那也可以。

**Comment by BaiJiangJie** [comment]
能帮我生成一个测试的密钥吗？
直接上传失败，在线转码后可以成功的。

**Comment by szr20010820** [comment]
> 能帮我生成一个测试的密钥吗？ 直接上传失败，在线转码后可以成功的。
普通用户与root用户密钥不同
使用root 用户可以 使用私钥直接使用通过API添加
普通用户 通过web端直接上传 是可以的 但是通过API 直接上传是失败的  需要通过转码后在通过API上传成功
以下为普通 直接上传失败
![image](https://github.com/user-attachments/assets/b3d14782-8258-41f8-bee7-494f1dd851c1)
通过转码后上传成功
![image](https://github.com/user-attachments/assets/903842d7-6916-4934-bb3c-3d0465b44b8a)
