### ISSUE TITLE
[Question] 请问开启MFA后，第一次在终端登陆，能否将MFA的二维码显示出来？或者提示应该去Jump网址注册绑定MFA

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#13965]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

腾讯云
Centos 7
单机部署

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/c21cbe9f-bc97-4263-8155-97b697f352e6)
目前只会存在这样的提示，如果第一次使用的话，就完全没有任何提示需要绑定MFA设备，能否在终端提示二维码？或者提示网址

### 期望结果

能够显示二维码和网址

### 补充信息

无

**Comment by BaiJiangJie** [comment]
后面版本优化一下。
