### ISSUE TITLE
[Bug] V3升级V4版本时如果管理员名称不是默认时会升级错误

### ISSUE THREAD

**Issue by pmddds** [jumpserver/jumpserver#13962]
### 产品版本

V4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos

### 🐛 缺陷描述

如果v3旧版本修改了管理员的username 升级v4时会升级失败,需要把管理员的username恢复成admin

### 复现步骤

V3版本修改admin的username 再执行升级V4版本时会提示找不到admin

**Comment by BaiJiangJie** [comment]
嗯，目前是这样的，会在 v4.1.0 版本中修复。

**Comment by BaiJiangJie** [comment]
有一些功能是需要给 admin 用户设置的，比如 RBAC 的超级管理员角色。否则可能会导致功能无法使用。

如果考虑到安全问题，可以禁用 admin 账户，但是不要删除。
