### ISSUE TITLE
[Feature] v4 社区版本恢复支持使用本地客户端方式连接数据库

### ISSUE THREAD

**Issue by cleanwind** [jumpserver/jumpserver#13976]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

如果需要执行比较大型的 SQL 指令 (200 KB 以上)，例如完整恢复数据库或多条插入指令。在 v3 版本的 Cli 与 Web GUI 都无法贴上执行。这是我们会采用本地连接数据库向导的方式完成工作。

### 解决方案

v4 社区版本恢复支持使用本地客户端方式连接数据库

### 补充信息

或者能让 Cli 与(或) Web GUI 支援大型的 SQL 指令执行。

**Comment by BaiJiangJie** [comment]
后面版本会考虑 Web GUI 大 SQL 语句的支持。

如果急需此功能，建议考虑企业版。

**Comment by fengmikaelson** [comment]
在阉割功能。。。只好回退了

**Comment by BaiJiangJie** [comment]
去掉的原因主要是考虑缩小安装包的大小，去掉了 MySQL 客户端的连接方式，新增了 Web GUI 连接 PostgreSQL 数据库的功能。
