### ISSUE TITLE
[Bug] V3.10.9 升级到 V3.10.12 后，作业管理，定时任务执行记录显示1次，执行命令输出中显示命令执行了2次

### ISSUE THREAD

**Issue by Carriezhangyan** [jumpserver/jumpserver#13977]
### Product Version

V3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

V3.10.9 升级到 V3.10.12

### 🐛 Bug Description

V3.10.9 升级到 V3.10.12 后，作业管理，定时任务执行记录显示1次，执行命令输出中显示定时任务命令执行了2次

### Recurrence Steps

当前版本 V3.10.9 
下载 jumpserver-installer-v3.10.12.tar.gz
tar -xvf  jumpserver-installer-v3.10.12.tar.gz 
cd  jumpserver-installer-v3.10.12
./jmsctl.sh upgrade
./jmsctl.sh start

重新登录jumpserver，工作台 - 作业中心 - 作业管理 - 执行历史 - 输出（显示2条执行记录）

**Comment by BaiJiangJie** [comment]
提供一下截图信息。

**Comment by jym503558564** [comment]
v4.1.0已修复，请升级进行体验。
v3.10.13下周发布，请持续关注我们产品发布信息。
