### ISSUE TITLE
[Question] 是否可以关闭 Web CLI 方式访问资产？

### ISSUE THREAD

**Issue by Lee-Z** [jumpserver/jumpserver#13972]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

离线安装。
版本：社区版 3.10.12

### 🤔 问题描述

使用web登陆jumpserver，连接资产ssh协议的时候有个 web cli，这个是调用的哪个服务，能在配置文件中进行关闭不(想关闭这个服务，不是关闭授权ssh协议权限)？

### 期望结果

想实现的结果为：
web端访问时，连接资产ssh协议权限打开，但是web cli服务关闭，在web端能看到ssh协议权限，但是不能ssh连接资产。
在非web终端能使用ssh 协议连接到资产。
这样能实现不？为什么？

**Comment by BaiJiangJie** [comment]
企业版功能。

<img width="1565" alt="image" src="https://github.com/user-attachments/assets/0e373771-4b3e-42d3-9e03-c990a7fe054e">
