### ISSUE TITLE
自主设置分组和资产名称

### ISSUE THREAD

**Issue by ruiyin1223** [jumpserver/jumpserver#13978]
### 产品版本

V3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

除了新建角色分配更新资产、更新节点权限外，可以支持用户工作台自行更改资产名称和资产分组吗

### 解决方案

除角色分配权限外，希望用户可以在工作台自行更改资产名称，自己的工作台可以自己分组

**Comment by BaiJiangJie** [comment]
v4.1.0 支持用户在工作台修改`我的资产`的名称和描述信息，分组不支持。

**Comment by ruiyin1223** [comment]
好的

**Comment by ruiyin1223** [comment]
V3中有考虑上线吗

**Comment by BaiJiangJie** [comment]
不考虑。
