### ISSUE TITLE
[Question] Jump的web界面一直待在一个地方 会触发超时504 这如何定位问题？F12里没有具体请求信息

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#13983]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

linux部署
腾讯云

### 🤔 问题描述

报错信息如下：
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html>      

### 期望结果

不报错

### 补充信息

无

**Comment by xiaoxiongxyy** [comment]
<img width="861" alt="image" src="https://github.com/user-attachments/assets/71075d0f-1aff-4b8d-b1d5-46ed9d2548ae">

**Comment by xiaoxiongxyy** [comment]
还有一个问题 刚刚koko组件使用CPU瞬时增高 导致机器卡死 这是目前4.0.2版本的bug吗？
![image](https://github.com/user-attachments/assets/981ff2e0-fc9d-4f6a-a01a-cb38bd0f2ebf)

**Comment by xiaoxiongxyy** [comment]
> 还有一个问题 刚刚koko组件使用CPU瞬时增高 导致机器卡死 这是目前4.0.2版本的bug吗？ ![image](https://private-user-images.githubusercontent.com/85990572/358184406-981ff2e0-fc9d-4f6a-a01a-cb38bd0f2ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzMzEsIm5iZiI6MTcyMzcxNTAzMSwicGF0aCI6Ii84NTk5MDU3Mi8zNTgxODQ0MDYtOTgxZmYyZTAtZmM5ZC00ZjZhLWEwMWEtY2IzOGJkMGYyZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MmU1ZDg0M2RmMmRmMTliNDYzNmJjOTk1YjY5YWZkZDY2YWQ2NWYwYTQ0ZmU3NWQ4ODhlODk4Mjk1OTRhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4LQqdpFSL2krKSet50rgcd84dxJYOTaHr_TotSGT5o)

报错日志 这是什么含义？一秒钟几乎刷了500条
![image](https://github.com/user-attachments/assets/11f229ed-d0ce-4e9f-aabb-bd3e6e39aff2)

**Comment by xiaoxiongxyy** [comment]
> > 还有一个问题 刚刚koko组件使用CPU瞬时增高 导致机器卡死 这是目前4.0.2版本的bug吗？ ![image](https://private-user-images.githubusercontent.com/85990572/358184406-981ff2e0-fc9d-4f6a-a01a-cb38bd0f2ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUzMzEsIm5iZiI6MTcyMzcxNTAzMSwicGF0aCI6Ii84NTk5MDU3Mi8zNTgxODQ0MDYtOTgxZmYyZTAtZmM5ZC00ZjZhLWEwMWEtY2IzOGJkMGYyZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MmU1ZDg0M2RmMmRmMTliNDYzNmJjOTk1YjY5YWZkZDY2YWQ2NWYwYTQ0ZmU3NWQ4ODhlODk4Mjk1OTRhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4LQqdpFSL2krKSet50rgcd84dxJYOTaHr_TotSGT5o)
> 
> 报错日志 这是什么含义？一秒钟几乎刷了500条 ![image](https://private-user-images.githubusercontent.com/85990572/358184767-11f229ed-d0ce-4e9f-aabb-bd3e6e39aff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTU0MzEsIm5iZiI6MTcyMzcxNTEzMSwicGF0aCI6Ii84NTk5MDU3Mi8zNTgxODQ3NjctMTFmMjI5ZWQtZDBjZS00ZTlmLWFhYmItYmQzZTZlMzlhZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NTFkNzFjNGRiM2M4MjYwNDM2YjMwZGEwNjJkNjVlNzA5MmQ2MmUyMWJlMDQ3MjQzYjg1ZjRiMjYzNzQ2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5uzndDP3laBTrHReCrVHyvTtFZnw7AQA4Mq27mtUWRc)

辛苦关注下 这是否是bug？

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
