### ISSUE TITLE
[Bug] 无法同时使用用户名或邮箱登录

### ISSUE THREAD

**Issue by ainuoyan** [jumpserver/jumpserver#13989]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Jumpserver v4.1.0 版本并启用 LDAP 对接
LDAP AD 对接映射参数
```
{
  "username": "sAMAccountName",
  "name": "displayName",
  "email": "mail",
  "groups": "memberOf"
}
```

### 🐛 缺陷描述

使用用户名可以登录系统，使用邮箱无法登录系统

### 复现步骤

使用用户名登录成功，使用邮箱登录失败报错
```
* 您输入的用户名或密码不正确，请重新输入。 您还可以尝试 5 次 (账号将被临时 锁定 30 分钟)
```

### 期望结果

在 LDAP AD 对接情况下可以同时使用用户名和密码登录系统

### 补充信息

可能还需要改造 LDAP 登录相关模块

**Comment by BaiJiangJie** [comment]
LDAP 认证一直支持 username 和 email 的认证，但是需要在 LDAP 中进行配置。

比如映射属性为：

```
{
  "name": "sAMAccountName",
  "email": "mail",
  "username": "sAMAccountName"
}
```

那么用户过滤器应该配置为：

`(|(sAMAccountName=%(user)s)(mail=%(user)s))`

这样，就同时支持了。

**Comment by ainuoyan** [comment]
> LDAP 认证一直支持 username 和 email 的认证，但是需要在 LDAP 中进行配置。
> 
> 比如映射属性为：
> 
> ```
> {
>   "name": "sAMAccountName",
>   "email": "mail",
>   "username": "sAMAccountName"
> }
> ```
> 
> 那么用户过滤器应该配置为：
> 
> `(|(sAMAccountName=%(user)s)(mail=%(user)s))`
> 
> 这样，就同时支持了。

非常感谢，测试成功，是我的问题，抱歉
