### ISSUE TITLE
[Feature] About the creation of the Job center Playbook

### ISSUE THREAD

**Issue by krnltask** [jumpserver/jumpserver#13993]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

The job center should be more customizable, allowing specific functions and scripts/playbooks to be assigned individually to each user group.

Currently, only system administrators can use this feature.

### Proposed Solution

The job center should be more customizable, allowing specific functions and scripts/playbooks to be assigned individually to each user group.

Currently, only system administrators can use this feature.

**Comment by BaiJiangJie** [comment]
All users can create their own playbooks in the Job Center - Templates - Playbook.

**Comment by BaiJiangJie** [comment]
That's not currently supported.

**Comment by Phong005** [comment]
I can't find Job Center in the latest version of Jumpserver
