### ISSUE TITLE
[Question] 批量导入主机或数据库的账户格式是什么？导出模板后账号的地方是空值，没有可以参考的

### ISSUE THREAD

**Issue by elysium-w** [jumpserver/jumpserver#14007]
### Product Version

4

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [x] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

debian 12

### 🤔 Question Description

![image](https://github.com/user-attachments/assets/08c45b9c-e46e-44cb-89eb-e35acad005ac)官方文档中没有相关功能的描述

**Comment by elysium-w** [comment]
尝试修改为以下格式，和只有账户名的方式均失败，官方文档中没有关于批量导入方法的详细说明
![image](https://github.com/user-attachments/assets/147263bb-c12c-4550-a181-90eba80245fb)

**Comment by BaiJiangJie** [comment]
参考下面的教程：

https://kb.fit2cloud.com/?p=4e54d4cc-259d-4cd1-9cd0-c99b3998ccac#heading-7

**Comment by elysium-w** [comment]
> 参考下面的教程：
> 
> [kb.fit2cloud.com?p=4e54d4cc-259d-4cd1-9cd0-c99b3998ccac#heading-7](https://kb.fit2cloud.com/?p=4e54d4cc-259d-4cd1-9cd0-c99b3998ccac#heading-7)

ok，解决了
