### ISSUE TITLE
[Question] 3.10.12升级到4.1.0时失败

### ISSUE THREAD

**Issue by pearl-he** [jumpserver/jumpserver#14003]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

cenos 7.6
目前安装jumpserver 3.10.12

### 🤔 问题描述

使用在线升级至4.1.0时,提示如下错误,具体现象就是在拉取lion:v4.1.0-ce失败:
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce

如下为全部错误信息:

`[root@localhost jumpserver-installer-v4.1.0]# ./jmsctl.sh upgrade
是否将版本更新至 v4.1.0-ce ? (y/n)  (默认为 y): y

1. 检查配置文件
配置文件位置: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

完成

2. 加载 Docker 镜像
[jumpserver/chen:v4.1.0-ce] exist, pass
[jumpserver/lion:v4.1.0-ce] pulling
[redis:7.0-bullseye] exist, pass
[mysql:5.7-debian] exist, pass
[jumpserver/koko:v4.1.0-ce] exist, pass
[jumpserver/core:v4.1.0-ce] exist, pass
[jumpserver/web:v4.1.0-ce] exist, pass
v4.1.0-ce: Pulling from jumpserver/lion
57500d4e37bb: Extracting [==================================================>]  26.39MB/26.39MB
bf7a4579d02d: Download complete 
83edcc9a511b: Download complete 
09d04cf4b7d0: Download complete 
87b291206e85: Download complete 
42cfe418b2f5: Download complete 
1db88d6ef09f: Download complete 
1fc3326550f2: Download complete 
14e8d1d414e1: Download complete 
96ff7c67a213: Download complete 
74a19389d880: Download complete 
0023d5c2da93: Download complete 
54d7446f1dc8: Download complete 
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce

[jumpserver/lion:v4.1.0-ce] pulling
v4.1.0-ce: Pulling from jumpserver/lion
57500d4e37bb: Extracting [==================================================>]  26.39MB/26.39MB
bf7a4579d02d: Download complete 
83edcc9a511b: Download complete 
09d04cf4b7d0: Download complete 
87b291206e85: Download complete 
42cfe418b2f5: Download complete 
1db88d6ef09f: Download complete 
1fc3326550f2: Download complete 
14e8d1d414e1: Download complete 
96ff7c67a213: Download complete 
74a19389d880: Download complete 
0023d5c2da93: Download complete 
54d7446f1dc8: Download complete 
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce

拉取镜像失败 jumpserver/lion:v4.1.0-ce

3. 备份数据库
正在备份...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
[SUCCESS] 备份成功! 备份文件已存放至: /opt/jumpserver/db_backup/jumpserver-v3.10.12-2024-08-19_22:07:50.sql

4. 备份配置文件
备份至 /opt/jumpserver/db_backup/config-v3.10.12-2024-08-19_22:07:51.conf

5. 进行数据库变更
表结构变更可能需要一段时间, 请耐心等待
检测到 JumpServer 正在运行, 是否需要关闭并继续升级? (y/n)  (默认为 y): 

unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  checkpoint  Manage checkpoints
  config      Manage Docker configs
  container   Manage containers
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  deploy      Deploy a new stack or update an existing stack
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  checkpoint  Manage checkpoints
  config      Manage Docker configs
  container   Manage containers
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  deploy      Deploy a new stack or update an existing stack
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

[root@localhost jumpserver-installer-v4.1.0]# docker pull swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
v4.1.0-ce: Pulling from jumpserver/lion
57500d4e37bb: Extracting [==================================================>]  26.39MB/26.39MB
bf7a4579d02d: Download complete 
83edcc9a511b: Download complete 
09d04cf4b7d0: Download complete 
87b291206e85: Download complete 
42cfe418b2f5: Download complete 
1db88d6ef09f: Download complete 
1fc3326550f2: Download complete 
14e8d1d414e1: Download complete 
96ff7c67a213: Download complete 
74a19389d880: Download complete 
0023d5c2da93: Download complete 
54d7446f1dc8: Download complete 
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
[root@localhost jumpserver-installer-v4.1.0]# docker pull swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce^C
[root@localhost jumpserver-installer-v4.1.0]# ./jmsctl.sh status
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  checkpoint  Manage checkpoints
  config      Manage Docker configs
  container   Manage containers
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  deploy      Deploy a new stack or update an existing stack
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.
`

### 期望结果

希望修补错误

### 补充信息

无

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13955#issuecomment-2285643584

升级到最新版本 Docker。

**Comment by pearl-he** [comment]
> [#13955 (comment)](https://github.com/jumpserver/jumpserver/issues/13955#issuecomment-2285643584)
> 
> 升级到最新版本 Docker。

已经解决,谢谢.
