### ISSUE TITLE
[Bug] 4.0.1 vi、vim编辑页面卡死

### ISSUE THREAD

**Issue by bigmouths** [jumpserver/jumpserver#14004]
### Product Version

v4.0.1

### 🐛 Bug 描述

浏览器版本
chrome 127.0.6533.120

Bug 描述
1、使用vi或者vim编辑文本，控制台卡死
2、控制台报错rCannot read properties of undefined (reading 'writeText')

问题解决：
降级其他之前版本可以解决

**Comment by LiGang1204** [comment]
> v4.1.1 中会修复。
> 
> 在发布之前，你可以配置并启用 HTTPS 协议，也可以。

经过测试v4.1.0使用自签证书是可以解决vim编辑页面卡死问题的
步骤如下：
openssl genrsa -out server.key 1024
openssl req -new -key server.key -out server.csr
openssl x509 -req -in server.csr -out server.crt -signkey server.key -days 3650
将生成的文件server.key、server.csr、server.crt放置于/opt/jumpserver/config/nginx/cert/
切换到目录/opt/jumpserver-installer-v4.1.0/
执行./jmsctl.sh restart

检查是否成功：
docker ps | grep jms
其中jumpserver/web:v4.1.0-ce容器出现0.0.0.0:443->443/tcp, :::443->443/tcp即为成功
登录JumpServer浏览器提示“证书是安全的、自签证书”

**Comment by seaurching** [comment]
> v4.1.1 中会修复。
> 
> 在发布之前，你可以配置并启用 HTTPS 协议，也可以。

我这里无法开启443端口已经被4层占用了。防火墙只开放了80 443端口，有没有相关的commit信息我自己修复一下？

**Comment by LeeEirc** [comment]
@seaurching 可以基于 koko v4.1 分支新构建镜像替换，相关 pr 参考 https://github.com/jumpserver/koko/commit/033f518f8d41c4d036dd2f896ac6737c84b7bcda

**Comment by seaurching** [comment]
> @seaurching 可以基于 koko v4.1 分支新构建镜像替换，相关 pr 参考 [jumpserver/koko@033f518](https://github.com/jumpserver/koko/commit/033f518f8d41c4d036dd2f896ac6737c84b7bcda)

已经按照这个修复了，现在正常使用
