### ISSUE TITLE
[Question] jumpserver添加website资产问题

### ISSUE THREAD

**Issue by lsx1205** [jumpserver/jumpserver#14001]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

rocky linux 9.4
docker部署

### 🤔 问题描述

我想要在jumpserver上面添加一个web资产进行测试，但是看官方文档没有很明白，需要添加一个应用发布服务器？社区版是只能通过windows server吗？而且添加完成发布服务器后，进行测试一直超时，这台服务器 我已经添加了windows连接，可以正常连接，测试不通过的原因是什么我不清楚
如果我忽略测试的结果，直接进行连接的话，会报错Core API 发生错误: No host account available，能否提供一些帮助，或者让我进入vx社区交流群，一直没给我通过

**Comment by BaiJiangJie** [comment]
看这篇教程：
https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665
