### ISSUE TITLE
[Question] 关于更新日志的问题

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#14018]
### 产品版本

v4

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

浏览器

### 🤔 问题描述

以前官方门户中选择在线文档，可查看更新日志，不记得什么时候又链接到Github上了，也没中文了。

**Comment by BaiJiangJie** [comment]
英文文档右上角有中文文档。

**Comment by BaiJiangJie** [comment]
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/a8091f3d-0cb6-48ae-80cd-03f28a301403">
