### ISSUE TITLE
[Question] 会话录像问题

### ISSUE THREAD

**Issue by lsx1205** [jumpserver/jumpserver#14013]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

rocky linux 9.4

### 🤔 问题描述

在jumpserver的存储目录中将会话录像删除后，web页面记录的历史会话记录并不会更新，这是jumpserver的机制吗？需要等到设置的定时任务 清除历史会话记录的天数后，他会自动清除吗？

**Comment by BaiJiangJie** [comment]
只删除录像文件目录不会影响历史会话页面的数据显示，但是会导致点击录像播放的时候报错（找不到）。

历史会话列表的数据是存储在后端数据库中的，如果要删除需要等定时任务执行。
