### ISSUE TITLE
[Question] 用户认证里的 同步注销的作用是什么？似乎并没有生效吧

### ISSUE THREAD

**Issue by lsx1205** [jumpserver/jumpserver#14014]
### 产品版本

3.10.12

### 版本类型

- [x] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [x] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

rocky linux 9.4

### 🤔 问题描述

我使用的单点登录认证方式，casdoor进行认证，有一个同步注销的按钮，但是这个按钮似乎并不生效吧，我现在不清楚它的作用是什么，我以为的是：
使用casdoor作为认证方式，当casdoor中的用户删除后，同jumpserver的用户也会跟随删除。但是如果按照同步注销的这个名词来看的话，casdoor登录注销后 jumpserver的登录状态也会随之注销，但似乎也没有生效

**Comment by lsx1205** [comment]
还有一个问题，如果使用第三方认证，在连接资产时 使用客户端连接方式，根据ssh向导提供的信息，连接命令行 (用户名指定连接的资产和账号)这种方式的话，jumpserver根本无法获取第三方认证的密码信息，这种连接方式就废弃了，只能使用web或者token的方式

**Comment by BaiJiangJie** [comment]
CAS 同步注销的意思是，当 JumpServer 中的用户退出时，同时从 CAS Server 端退出。

相同用户名的用户只会有一个。

账号管理中有虚拟用户-同名用户的设置，开启密码（与用户登录时相同）选项，可以在登录JumpServer和资产时，对于用户名相同的账号使用相同的密码。
