### ISSUE TITLE
[Feature] Web Protection via reverse proxy

### ISSUE THREAD

**Issue by GreatAg** [jumpserver/jumpserver#14020]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

Hi, Do you have any plan to support web access protection using reverse proxy?
I mean jumpserver acts as a reverse proxy for accessing the website.

### Proposed Solution

Teleport already using this approach. maybe their documents can helps you.
Also if you see a security risk i'll be grateful if you share with me.
Please explain which one is better for web access? using remoteApp or reverse proxy?

**Comment by ibuler** [comment]
Does the Teleport visit the website support session replay and account auto input ?

**Comment by GreatAg** [comment]
No, can you tell me what is difference between your approach and teleport approach for websites from security perspective?

**Comment by ibuler** [comment]
JumpServer visit a web site:

1. Open the web site URL
2. Find the username and password input 
3. Type username and password then Enter
4. Login success and record the replay

**Comment by ibuler** [comment]
I install teleport now, but I can't find the way to add a web asset

![image](https://github.com/user-attachments/assets/129786bc-ca26-4eb4-8bab-5f4b206a220d)

**Comment by GreatAg** [comment]
Ok, my question is why you use remote webApp and not use reverse proxy just like teleport? what is the benefits of remote webApp? better security?

**Comment by ibuler** [comment]
1. Record and replay session
2. Use selenium to input username password or others

Our method is same like CyberArk
