### ISSUE TITLE
[用户来源为ldap时，也会提示登录完成前，请先修改密码] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14028]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver v3.10.13的版本，配置了认证方式ldap

### 🐛 缺陷描述

用户来源为ldap时，会提示“登录需修改密码”，当前用户来自ldap 是无法修改密码的

### 复现步骤

数据库 创建一个用户  user1  邮箱配置 [user1@123.com]并勾选“下次登录需修改密码”
ldap存在用户 user1 邮箱配置 [user1@456.com]

导入 ldap用户 user1,，就会覆盖 数据库的user1，用户来源为LDAP
但是登录user1用户的时候，会提示“需要修改密码”， (当前用户来自ldap 是无法修改密码的) 

<img width="698" alt="image" src="https://github.com/user-attachments/assets/00893b91-5b1c-48c9-a75f-65f633c6b525">

### 期望结果

用户已存在的时候，不能导入，需要先删除本地用户，或者导入时重置用户设置，取消“登录需修改密码”选项

**Comment by yuanxixue** [comment]
我在更新user1用户的时候，也没有取消“登录需修改密码”的选项

**Comment by BaiJiangJie** [comment]
看一下 user1 的数据库字段 need_update_password 是什么值？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/14038#pullrequestreview-2265348391

v4 版本已优化。

只有本地认证的用户才会判断 too_simple、need_update_password 和 password_expired
