### ISSUE TITLE
[Question] alert for sensitive assets login

### ISSUE THREAD

**Issue by katagiri-yuichii** [jumpserver/jumpserver#14021]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Operating System: Ubuntu 22.04 server
Active Directory Configured
Syslog Configured
Video Storage Configuration: Minio
behiend Nginx reverse proxy

### 🤔 Question Description

Hi there,

I'm wondering if it's possible to set up login alerts for specific assets in Jumpserver based on tags or other criteria.

 I've read about IP-based notifications from docs, but I'd like to be able to trigger alerts when a user logs in to a particular asset (like a production database) when connection is established.

Is this functionality currently available, or is it something that could be considered for future development?

Thanks for your time and assistance.

**Comment by BaiJiangJie** [comment]
<img width="1904" alt="image" src="https://github.com/user-attachments/assets/b7b91cdf-c052-45db-9130-6ca9db3b695a">

User connection to asset notification administrator is an Enterprise Edition feature and is supported in the latest version. You can purchase the Enterprise Edition directly or apply for a trial of the Enterprise Edition before purchasing.

**Comment by katagiri-yuichii** [comment]
Thank you for your response and clarification.
I'll go ahead and close this issue now.
