### ISSUE TITLE
[Question] 普通用户用户信息更改认证出现空白页面

### ISSUE THREAD

**Issue by Nickyang00** [jumpserver/jumpserver#14037]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机架构

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/ba5df6fd-356f-4062-a8ec-03e9db339972)
这里是否需要优化一下逻辑和显示方式，普通用户点进去白屏

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/14051

Will be fixed in v4.1.1 and v4.2.0

**Comment by sanpichen** [comment]
V4.2.0 复验仍有此问题

**Comment by BaiJiangJie** [comment]
<img width="1743" alt="image" src="https://github.com/user-attachments/assets/2fd6be43-c76f-46f5-8c72-5c35382e00c8">

没问题啊。
@sanpichen

**Comment by sanpichen** [comment]
我知道原因了。
升级后用户角色没有维持到，用户角色没有了。



***@***.***
 
发件人： Bryan
发送时间： 2024-09-25 16:19
收件人： jumpserver/jumpserver
抄送： sanpichen; Mention
主题： Re: [jumpserver/jumpserver] [Question] 普通用户用户信息更改认证出现空白页面 (Issue #14037)
image.png (view on web) 
没问题啊。
@sanpichen

**Comment by bacterous** [comment]
> 我知道原因了。 升级后用户角色没有维持到，用户角色没有了。 ***@***.*** 发件人： Bryan 发送时间： 2024-09-25 16:19 收件人： jumpserver/jumpserver 抄送： sanpichen; Mention 主题： Re: [jumpserver/jumpserver] [Question] 普通用户用户信息更改认证出现空白页面 (Issue #14037) image.png (view on web) 没问题啊。 @sanpichen — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

这种情况下该如何修复呢
