### ISSUE TITLE
[bug]vi vim 命令使用了

### ISSUE THREAD

**Issue by Wajle** [jumpserver/jumpserver#14035]
### 产品版本

4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

linux

### 🐛 缺陷描述

vi vim 命令使用了 会卡死

### 复现步骤

vi vim

**Comment by Nickyang00** [comment]
重复issue：https://github.com/jumpserver/jumpserver/issues/14004
