### ISSUE TITLE
[Question] JumpServer v4+ 版本，如何撰写 systemd 服务

### ISSUE THREAD

**Issue by OpsDarren** [jumpserver/jumpserver#14036]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

- 系统: Rocky Linux 9.2 (5.14.0-284.11.1.el9_2.x86_64)
- 部署架构: JumpServer v4.1.0 (内置 PG、内置 Redis)

### 🤔 问题描述

请问针对当前 v4+ 版本，是否有合适的 systemd 模板参考，谢谢

### 期望结果

JumpServer 作为 systemd 服务，开机自启动

**Comment by BaiJiangJie** [comment]
默认情况下，JumpServer 服务就是开机启动的。

**Comment by BaiJiangJie** [comment]
写一个开机启动脚本就可以，执行 `./jmsctl start`

**Comment by OpsDarren** [comment]
> 默认情况下，JumpServer 服务就是开机启动的。

> 写一个开机启动脚本就可以，执行 `./jmsctl start`

好的，谢谢大佬，因为看了下之前版本的一些相关文档，是有人写到 systemd 里面了，感觉跟我多年以前安装 JumpServer 已经差别挺大了，所以特来请教。
