### ISSUE TITLE
[Question] Build process

### ISSUE THREAD

**Issue by GreatAg** [jumpserver/jumpserver#14048]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Linux; ubuntu 20.04

### 🤔 Question Description

Hello, how can i make some changes in project and build images?
I mean please explain me the build process of jumpserver's components.
Also please update the release page of lina and luna and other repos for version 4.1.0 when i want to build web image i got 404 for this resource:

https://github.com/jumpserver/lina/releases/download/v4.1.0/lina-v4.1.0.tar.gz

**Comment by BaiJiangJie** [comment]
You can refer to the [components](https://github.com/jumpserver/jumpserver?tab=readme-ov-file#components) descriptions and the Dockerfile files in their repositories. For docker_web, please refer to:
https://github.com/jumpserver/docker-web/

**Comment by GreatAg** [comment]
For changing logos and images of UI, what should i do? where should i change in code? this is really confusing.
does core component includes front-end code?

**Comment by GreatAg** [comment]
Anything ?!

**Comment by BaiJiangJie** [comment]
Icon change is an enterprise version feature. If necessary, please consult the official website sales.
