### ISSUE TITLE
[Feature] 用户组支持多级，并且在同步LDAP的时候可以同步组织架构（OU）内容到用户组中，同步组织架构中的用户到对应用户组织中。

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#14049]
### Product Version

3.10.13

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

 用户组支持多级，并且在同步LDAP的时候可以同步组织架构（OU）内容到用户组中，同步组织架构中的用户到对应用户组织中。

### Proposed Solution

 用户组支持多级，并且在同步LDAP的时候可以同步组织架构（OU）内容到用户组中，同步组织架构中的用户到对应用户组织中。

### Additional Information

无

**Comment by BaiJiangJie** [comment]
LDAP 用户同步时支持同步用户组，但是仅支持一级用户组。

多级用户组的架构，暂时不考虑。
