### ISSUE TITLE
[Question] Show Windows Background with RDP

### ISSUE THREAD

**Issue by Adevill20** [jumpserver/jumpserver#14042]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Jumpserver hosted in local cluster

### 🤔 Question Description

How can I configure JumpServer or the sub-components to show the Windows Background during RDP? Currently, the background is set to black when connecting.

**Comment by Nickyang00** [comment]
Add this to your config file and restart JumpServer:  JUMPSERVER_ENABLE_WALLPAPER=True

**Comment by Adevill20** [comment]
@Nickyang00 I tried the command you suggested, but it didn't work. For confirmation, I edited the /opt/jumpserver/config.txt file and added the below, then restarted the VM.

`
# 使用内置 SLB, 如果 Web 页面获取到的客户端 IP 地址不正确, 请将 USE_LB 设置为 0
# USE_LB 设置为 1 时, 使用配置 proxy_set_header X-Forwarded-For $remote_addr
# USE_LB 设置为 0 时, 使用配置 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
USE_LB=0

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#

# Enable the Windows Desktop Wallpaper during RDP
JUMPSERVER_ENABLE_WALLPAPER=True
#


CURRENT_VERSION=v4.1.0-ce
`

**Comment by BaiJiangJie** [comment]
You should restart JumpServer, not VM.

`./jmsctl restart`

**Comment by Adevill20** [comment]
Ahhh, ok. That worked. Thank you
