### ISSUE TITLE
[Feature] K8s纳管的功能需求

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#14046]
### 产品版本

3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

 k8s 的使用，主要缺这么两个功能：
1. 快速切换namespace，kubectl有个插件 https://github.com/ahmetb/kubectx    (GitHub - ahmetb/kubectx: Faster way to switch between clusters and namespaces in kubectl），这样不用每次输入 k -n monitoring xxxx 能节约好多输入的时间。
2. 快速查找history，我用的是fzf，https://github.com/junegunn/fzf     (GitHub - junegunn/fzf: :cherry_blossom: A command-line fuzzy finder)， 这样很多敲过的命令不用再敲了。

3. 在 k8s 登录环境里，发现 vim head 这些命令都是可以运行的， 但是 cat mkdir 却不行，想请教下这个是基于什么考虑呢？
bash: /bin/cat: Permission denied
bash: /bin/mkdir: Permission denied

### 解决方案

暂无

**Comment by BaiJiangJie** [comment]
1、2 目前需要通过第三方插件解决的暂时不考虑。
3 主要考虑禁用一些系统级别的命令来降低安全风险。
