### ISSUE TITLE
[Bug] 组织管理员的角色具备的权限无法执行

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#14045]
### Product Version

4.1.0/3.10.12

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

JS版本：3.10.12/4.1.0
浏览器：EDGE/Chorme

### 🐛 Bug Description

1. 堡垒机创建一个系统角色为用户，组织角色为组织管理员的用户。
![image](https://github.com/user-attachments/assets/13d8feb8-7984-49bd-99e3-170421235060)
2. 在资产管理-资产列表执行批量探测功能，提示无权限，但是单个资产的探测是可以的，查看了下组织管理员的角色具备相关权限。
![image](https://github.com/user-attachments/assets/fe628573-6b5c-48b6-9231-8ea13e0d162f)

![image](https://github.com/user-attachments/assets/348f5091-93a1-4bdd-b675-4a8d10c68719)

3. 同样的问题，堡垒机创建一个系统角色为用户，组织角色为组织管理员的用户。组织管理员没有权限查看组织下面的作业日志，只能看到有作业日志，但是点击输出，提示无权限。

### Recurrence Steps

1. 堡垒机创建一个系统角色为用户，组织角色为组织管理员的用户
2. 组织下面添加资产，在资产管理-资产列表中执行批量探测。
3. 在作业中心中创建批量命令执行的作业，在作业日志中点击输出。

**Comment by BaiJiangJie** [comment]
将会在 v4.2.0 和 v3.10.14 中修复。

**Comment by w940853815** [comment]
https://github.com/jumpserver/jumpserver/commit/1712a9a1041cfa09fdf840b4a4520b3c0dfa435a
https://github.com/jumpserver/jumpserver/commit/ecaf19563fc118917a229cfbd93f6366795ce298

**Comment by qin-nz** [comment]
@BaiJiangJie @w940853815  在作业中心中创建批量命令执行的作业，在作业日志中点击输出。
这个也会一起修复了么？

**Comment by w940853815** [comment]
@qin-nz fix

**Comment by w940853815** [comment]
> @BaiJiangJie @w940853815 在作业中心中创建批量命令执行的作业，在作业日志中点击输出。 这个也会一起修复了么？

fix
