### ISSUE TITLE
[Question] 使用pycharm远程开发，添加解释器后，软件包列表为空，执行代码报错，可能的原因是什么

### ISSUE THREAD

**Issue by wsdszhou** [jumpserver/jumpserver#14050]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

pycharm 2023.1 mac环境 

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/a0b172c4-bea3-49b7-a9c5-2ea6ccdf03b2)
![image](https://github.com/user-attachments/assets/bd68ed09-17eb-4100-8e7f-d19f17848248)

使用pycharm远程开发，添加解释器后，软件包列表为空，执行代码报错

### 期望结果

希望帮我找出可能的原因，需要在jumpserver做什么配置修改吗

### 补充信息

pycharm直接连接对应的资产是正常的，通过jumpserver就会报错,终端ssh、sftp远程连接都是正常的

**Comment by wsdszhou** [comment]
补充一下报错内容
![image](https://github.com/user-attachments/assets/a8235c92-4e42-4a86-8705-71803df5295c)

**Comment by LeeEirc** [comment]
v3并不支持pycharm的远程开发，v4 做过相关优化，可以升级到 v4 测试体验下。

**Comment by jym503558564** [comment]
v4版本，config.txt 加上参数：ENABLE_REVERSE_PORT_FORWARD=true，重启
![image](https://github.com/user-attachments/assets/f9eb1998-a485-45de-8f0f-07cd11bacff9)
