### ISSUE TITLE
[Bug] 部分会话无法下线

### ISSUE THREAD

**Issue by jackpliu** [jumpserver/jumpserver#14059]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

通过网域网关连接 linux资产，会话可能出现无法下线和清理的情况

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/8d0117be-51a1-426b-8f3d-e0e435206892)
通过网域网关连接 linux资产，会话可能出现无法下线和清理的情况

### 复现步骤

偶发

**Comment by BaiJiangJie** [comment]
升级到最新版本试试。
