### ISSUE TITLE
coco能否同时在两个jumpserver上注册

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1405]
现在coco是否只能注册到一个jumpserver？
我这里搭建两套环境做热备，计划两个coco同时使用，但两个coco只能注册到一个jumpserver，如果这个jumpserver宕了，需要使用额外的方法才能实现自动切换。
能否coco同时在多台jumpserver上注册，mysql使用双主，这样即时主jumpserver宕了也不会影响正常使用

**Comment by gengkeye** [comment]
你可以搞两个jumpserver，两个coco，而且coco可以在nginx里设置域名来访问的

**Comment by yaoluoye** [comment]
这种方法还是需要在jumpserver体系之外来解决，希望能在jumpserver体系内搞定。

**Comment by gengkeye** [comment]
coco同时注册两个JP是行不通的，它要从JP获取数据，如果是同时注册两个，那要从哪个去获取数据呢

**Comment by wojiushixiaobai** [comment]
域名负载，coco的conf.py里面执行jumpserver的地址为负载的域名就好。没什么难度
nginx设置
upstream jumpserver{
    server xx.xx.xx.xx;
    server xx.xx.xx.xx;
    server xx.xx.xx.xx;
{

server {
        listen 80;
        server_name jms.domain.com;
        location / {
                proxy_pass http://jumpserver;
                proxy_set_header    Host             $host;
                proxy_set_header    X-Real-IP        $remote_addr;
                proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header    HTTP_X_FORWARDED_FOR $remote_addr;
                proxy_redirect      default;
        }


coco/conf.py

CORE_HOST = http://jms.domain.com;

**Comment by yaoluoye** [comment]
嗯，引入etcd来做分布式也许可以更好的解决这个问题。
跳板机作为唯一入口，SLA要求很高的，最好要做到秒级自动切换。否则跳板机故障和生产故障同时发生，会死的很惨。
使用域名方案的话，心跳检测，dns自动切换也要跟上，如果公司已有相应的机制还好，否则还需要从头搭建。

**Comment by ibuler** [comment]
暂时不考虑
