### ISSUE TITLE
[Question] 调用MFA API报错    "detail": "Authentication credentials were not provided.",

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#14058]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Docker部署 腾讯云

### 🤔 问题描述

API调用提示
requests.exceptions.SSLError: HTTPSConnectionPool(host='jump.shuidi.io', port=443): Max retries exceeded with url: /api/v1/authentication/mfa/challenge/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

需要访问 /api/v1/authentication/mfa/challenge/
但是访问这个URI提示 
{
    "detail": "Authentication credentials were not provided.",
    "code": "not_authenticated"
}
需要怎么处理呢？

**Comment by BaiJiangJie** [comment]
需要先调用用户认证的 API，再调用 MFA 的 API。

**Comment by xiaoxiongxyy** [comment]
> 需要先调用用户认证的 API，再调用 MFA 的 API。

第一个这个用户认证的接口是什么呀？/api/v1/authentication/auth/ 这个不行呀？能详细说下是哪个API吗

**Comment by xiaoxiongxyy** [comment]
> 需要先调用用户认证的 API，再调用 MFA 的 API。

我这连续调用都是报错呀
{"error":"mfa_required","msg":"MFA required","data":{"choices":["otp"],"url":"/api/v1/authentication/mfa/challenge/"}}
{"detail":"Authentication credentials were not provided.","code":"not_authenticated"}
而且这不是两个请求吗

**Comment by BaiJiangJie** [comment]
首先调用：/api/v1/authentication/auth/
然后传入 OTP Code：调用 /api/v1/authentication/mfa/challenge/

**Comment by BaiJiangJie** [comment]
POST /api/v1/authentication/tokens/
{
"username": "",
"password": ""
}

POST /api/v1//authentication/otp/verify/

{
 "code": "123123"
}

**Comment by xiaoxiongxyy** [comment]
> POST /api/v1/authentication/tokens/ { "username": "", "password": "" }
> 
> POST /api/v1/authentication/otp/verify/
> 
> { "code": "123123" }

/api/v1/authentication/otp/verify/ 我这边看 没有这个接口呀

**Comment by DBA-family** [comment]
我也碰到这个问题，之后是怎样解决的？版本是4.0以上

**Comment by SnelsSM** [comment]
> 我也碰到这个问题，之后是怎样解决的？版本是4.0以上

@DBA-family @xiaoxiongxyy 
Look at issue [#14665](https://github.com/jumpserver/jumpserver/issues/14665)
