### ISSUE TITLE
[Bug] sftp远程连接资产后，根目录下出现以资产名称命名的目录

### ISSUE THREAD

**Issue by AndersWantall** [jumpserver/jumpserver#14055]
### 产品版本

v3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

在jumpserver里面创建了一个基于linux平台的资产（k8s里的pod），家目录设置的是 /，用sftp远程连接这个资产，输入ls命令

### 🐛 缺陷描述

在jumpserver里面创建了一个基于linux平台的资产（k8s里的pod），家目录设置的是 /，用sftp远程连接这个资产，输入ls命令，看到的是以资产名称命名的目录（比如我的资产名称是test3，ls看到的是test3），进入test3之后看到的才是资产文件系统本身的内容
![微信图片_20240829165646](https://github.com/user-attachments/assets/6afbf84b-0faa-48e2-a141-9dcdfa3faa02)

### 复现步骤

在jumpserver里面创建了一个基于linux平台的资产（k8s里的pod），家目录设置的是 /，用sftp远程连接这个资产，输入ls命令

### 期望结果

在jumpserver里面创建了一个基于linux平台的资产（k8s里的pod），家目录设置的是 /，用sftp远程连接这个资产，输入ls命令，看到的应该就直接是资产文件系统下的内容，而不应该再有一层资产名称命名的目录

### 补充信息

对于一些应用场景，是会受到影响的。比如通过pycharm远程连接到资产后，需要选择远程的python解释器。应该是/usr/bin/python3，而加了一层资产名称命名的目录之后，比如就是/test3/usr/bin/python3，那对于远程环境来说是找不到这个路径的

_No response_

**Comment by BaiJiangJie** [comment]
v3 最新版本支持。

**Comment by AndersWantall** [comment]
> v3 最新版本支持。

您好，我提出这个问题的所在版本是v3.10.11 （昨天忘在版本号上明确指出了，不好意思），请问您是指最新版本里面，sftp连上去之后，目录层级不会带资产名称一级了么？请问具体是从哪个版本开始支持的呢？

**Comment by BaiJiangJie** [comment]
在 v3.10.12 中做的优化。
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/9b5f99b4-2562-4fed-aa7b-2797855c3345">

https://github.com/jumpserver/jumpserver/releases/tag/v3.10.12

你直接升级到最新的 v3 就可以。

**Comment by AndersWantall** [comment]
> 在 v3.10.12 中做的优化。 <img alt="image" width="1175" src="https://private-user-images.githubusercontent.com/32935519/363013474-9b5f99b4-2562-4fed-aa7b-2797855c3345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjc4MTUsIm5iZiI6MTcyNTMyNzUxNSwicGF0aCI6Ii8zMjkzNTUxOS8zNjMwMTM0NzQtOWI1Zjk5YjQtMjU2Mi00ZmVkLWFhN2ItMjc5Nzg1NWMzMzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAxMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YWQ0YjMwYjM4ZmYwNWE2NGRlMjllMWJjYjIyMGY4MTZjNWNkZWQ0NmZkYjkzMGY5ZDY1NzE2ODIwZWQ0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l7SrxdnYEstiGUKTOuE8zC8iuvpHjJUQFd36v7sHiu0">
> 
> https://github.com/jumpserver/jumpserver/releases/tag/v3.10.12
> 
> 你直接升级到最新的 v3 就可以。

      您好，我已经升级倒最新v3版本了，现在这个问题是解决了。还有另一个问题想咨询一下：jumpserver对于pycharm ssh连到资产进行远程开发是如何支持的？具体场景就是：pycharm ssh连到linux平台创建的k8s pod资产，这里面是有python环境的。通过pycharm选择资产里的python命令所在路径作为远程解释器，也能看到相关python依赖包，然后用远程解释器执行python代码。
      我们目前连上去之后基于远程解释器执行代码是报错的，所以想了解下是需要做什么配置，或安装什么插件来解决吗

**Comment by BaiJiangJie** [comment]
当前 issue 已解决。重新提一个 issue 来处理。

**Comment by AndersWantall** [comment]
> 您好，我已经升级倒最新v3版本了，现在这个问题是解决了。还有另一个问题想咨询一下：jumpserver对于pycharm ssh连到资产进行远程开发是如何支持的？具体场景就是：pycharm ssh连到linux平台创建的k8s pod资产，这里面是有python环境的。通过pycharm选择资产里的python命令所在路径作为远程解释器，也能看到相关python依赖包，然后用远程解释器执行python代码。
>   我们目前连上去之后基于远程解释器执行代码是报错的，所以想了解下是需要做什么配置，或安装什么插件来解决吗

好的 我重新提一个
