### ISSUE TITLE
跳板机选择资产后系统用户无需密码登录问题

### ISSUE THREAD

**Issue by 13247380098** [jumpserver/jumpserver#1406]
[简述你的问题]
       在xshell通过用户列表用户登录跳板机后，按p查看用户授权服务器，选择其中一台服务器后，会显示可登录的系统用户，此时任意选择一个系统用户登录，都没有密码登录验证？？哪个大神帮帮忙，我在创建系统用户的时候是设置了密码的。
##### 使用版本
Jumpserver版本 1.0

##### 问题复现步骤
1、xshell登录跳板机后
2、按p显示授权的服务器
3、选择其中一台进入
4、显示可登录的用户
5、选择要登录的用户
6、直接进入系统
从步棸5到6过程中，没有登录用户密码验证？？

##### 具体表现[截图可能会更好些,最好能截全]

![_20180608120921](https://user-images.githubusercontent.com/38271261/41138575-ced4af20-6b14-11e8-8d49-1e5a7646c263.png)

**Comment by gengkeye** [comment]
这个本来就不用输入密码的，因为coco后台自动验证了系统用户的密码

**Comment by wojiushixiaobai** [comment]
楼上的老哥已经解释了。

**Comment by 13247380098** [comment]
请问修改了系统用户密码为什么作业中心没有推送的记录，后台也没有推送成功呢？
