### ISSUE TITLE
[Bug] 当资产 IP 为 IPv6 时无法通过网关测试资产可连接性或更新硬件信息

### ISSUE THREAD

**Issue by ztelliot** [jumpserver/jumpserver#14069]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

helm 部署版本，通过网关对 IPv6 资产测试可连接性和更新硬件信息，luna 连接正常

### 🐛 Bug Description

报错如图：
![image](https://github.com/user-attachments/assets/d5887c28-7f03-4678-8871-26837cda2b9f)

通过抓取 celery 容器进程获取到的 playbook 如下：
![image](https://github.com/user-attachments/assets/2c02c16e-b839-4f5a-967a-c08b19e54fd5)

使用 ssh 命令尝试连接：
![image](https://github.com/user-attachments/assets/04c59f37-ac52-463c-b030-5c4d6a2249ec)

可以看到，当 IPv6 地址未被 [] 包裹时会报错
```
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

但是，当前节点的 IP 字段中不允许填入特殊符号，希望能够修复

### Recurrence Steps

- 资产 IP 为 IPv6 地址
- 设置网关

**Comment by jym503558564** [comment]
存在问题，待下个版本修复。

**Comment by jym503558564** [comment]
v4.2.0已修复，请升级进行体验。
![image](https://github.com/user-attachments/assets/d7042927-d686-47ae-906e-702404ab94c2)
