### ISSUE TITLE
[Bug] Jumpserver v4.0.2-ce 回放录像无法拖动进度条 解压出来也不是MP4 请问这个正常吗

### ISSUE THREAD

**Issue by TheRyan9311** [jumpserver/jumpserver#14064]
### 产品版本

Jumpserver v4.0.2-ce

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

[Bug] Jumpserver v4.0.2-ce 回放录像无法拖动进度条 解压出来也不是MP4 请问这个正常吗

### 🐛 缺陷描述

[Bug] Jumpserver v4.0.2-ce 回放录像无法拖动进度条 解压出来也不是MP4 请问这个正常吗

### 复现步骤

[Bug] Jumpserver v4.0.2-ce 回放录像无法拖动进度条 解压出来也不是MP4 请问这个正常吗

### 期望结果

录像可以拖动

### 尝试过的解决方案

重新安装,使用本地录像播放客户端均无效

**Comment by BaiJiangJie** [comment]
转码问题查看 video-player 组件。

不是 mp4 格式不能拖动是正常情况，针对在线录像播放会在后续版本中优化。

**Comment by BaiJiangJie** [comment]
v4.2.0 针对 windows 的录像播放有优化。

**Comment by softboy99** [comment]
最新的4.7还是无法在线直接播放回放，是少安装什么东西吗？
