### ISSUE TITLE
[Bug] 第一个资产节点命名过长的情况下，无法点击搜索和刷新

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#14063]
### Product Version

v3.10.13

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

JumpServer Version v3.10.13 ，离线包环境

### 🐛 Bug Description

第一个资产节点命名过长的情况下，无法点击搜索和刷新
<img width="1580" alt="image" src="https://github.com/user-attachments/assets/1eb8ee11-491b-4acc-ae9c-f9c0023182e9">

### Recurrence Steps

1.给第一个资产节点 创建一个比较长的名称如 xx-xxxxxxxx.xxxxxxx.com-20240830-17:00:00
2.无法点击搜索和刷新

### Expected Behavior

正常点击搜索和刷新

**Comment by BaiJiangJie** [comment]
v4 版本已解决。
