### ISSUE TITLE
[Feature] 连接方式以协议,资产进行限制

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#14076]
### 产品版本

v3，v4

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

https://bbs.fit2cloud.com/t/topic/7819

### 解决方案

https://bbs.fit2cloud.com/t/topic/7819

**Comment by BaiJiangJie** [comment]
短期内没有计划。
