### ISSUE TITLE
[Bug] 修改密码的页面空白没反应

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#14078]
### Product Version

V4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

DOCKER容器运行

### 🐛 Bug Description

进入 认证配置-》更新密码 点击 “更新” 出来的空白页面，无法修改密码.后台不知道看那里的错误日志

### Recurrence Steps

进入 认证配置-》更新密码 点击 “更新” 出来的空白页面，无法修改密码

### Attempted Solutions

![微信图片_20240903113410](https://github.com/user-attachments/assets/0957932e-0a97-411f-9cd5-324c2c105df8)
![微信图片_20240903113341](https://github.com/user-attachments/assets/e323d298-7894-49b4-92fa-483bb229b43a)

**Comment by BaiJiangJie** [comment]
v4.2.0 版本会修复。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/14037

和这个问题一样。
