### ISSUE TITLE
[Bug] Core API failed: connect API core err: No host account available, please check the applet, host and account

### ISSUE THREAD

**Issue by derkahless** [jumpserver/jumpserver#14075]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 24.04 LTS Server
Windows 2019 remote App Server

### 🐛 Bug Description

When trying to connect to a https site via Applet (Chrome)out of the WebTerminal i get:

"Core API failed: connect API core err: No host account available, please check the applet, host and account"

Chrome is deployed (all deployments were made), connection via SSH and/or winrm to the Remote App Windows 2019 machine works. Account and Password are working, too. 

What can i do? Thank you in advance!

### Recurrence Steps

Connect to HTTPS endpoint

### Expected Behavior

Showing Website

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665

You need to check whether the remote application publisher and the account on the publisher are available. Currently there is only Chinese documentation, which you can translate and read.

**Comment by derkahless** [comment]
The Remote App Machine seems to be working fine.

```
ok: [WindowsJumphost] => {
    "info": {
        "arch": "x86_64",
        "cpu_cores": 1,
        "cpu_count": 2,
        "cpu_vcpus": 2,
        "distribution": "Microsoft Windows Server 2019 Datacenter",
        "distribution_version": "10.0.17763.0",
        "kernel": "10.0.17763.0",
        "memory": "4.0",
        "model": "Standard PC (i440FX + PIIX, 1996)",
        "sn": null,
        "vendor": "QEMU"
    }
}
```

It shows me installed Chrome and Firefox on the RemoteApp Machine, too.

**Comment by BaiJiangJie** [comment]
Okay, Now you need to check if the account in the publisher details is valid?
