### ISSUE TITLE
[Feature] pycharm远程连接资产后能够支持远程代码调试运行

### ISSUE THREAD

**Issue by AndersWantall** [jumpserver/jumpserver#14077]
### 产品版本

v3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

jumpserver对于pycharm ssh连到资产进行远程开发是如何支持的？具体场景就是：pycharm ssh连到linux平台创建的k8s pod资产，这里面是有python环境的。通过pycharm选择资产里的python命令所在路径作为远程解释器，也能看到相关python依赖包，然后用远程解释器执行python代码。
我们目前连上去之后基于远程解释器执行代码是报错的，所以想了解下是需要做什么配置，或安装什么插件来解决吗

### 解决方案

希望能支持pycharm远程连接资产后，支持远程代码调试运行

**Comment by LeeEirc** [comment]
重复 https://github.com/jumpserver/jumpserver/issues/14050

**Comment by jym503558564** [comment]
v4版本，config.txt 加上参数：ENABLE_REVERSE_PORT_FORWARD=true，重启

![image](https://github.com/user-attachments/assets/34268dd6-cbc1-4e43-9593-2e47f2749695)
