### ISSUE TITLE
[Bug] CAS 认证中的 email 地址异常

### ISSUE THREAD

**Issue by qin-nz** [jumpserver/jumpserver#14073]
### 产品版本

3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CAS - 用户属性映射：
```json
{
  "user_id": "username",
  "chinese_name": "name",
  "email": "email"
}
```

消息通知-邮件设置-邮件后缀： example.com

### 🐛 缺陷描述

当 CAS 返回的数据为 
```json
{"user_id": "a",
"chinese_name": "哈哈",
"email": "b@example.com"
}
```

创建的用户的邮箱预期应该是 b@example.com ，但是实际为 a@example.com

### 复现步骤

用上面的用户使用 CAS 首次登录。

### 期望结果

按照 CAS 中返回的 email 创建用户

**Comment by BaiJiangJie** [comment]
默认构造的邮箱是 username@example.com

**Comment by qin-nz** [comment]
@BaiJiangJie 啊，这不合理啊…… 明明你们都提供的 CAS 里面的 email 映射字段了， 还是去构造，而不是遵循 CAS ……

**Comment by BaiJiangJie** [comment]
我说的是默认，如果认证配置中有映射 email 字段，那就会用 CAS 认证服务中的用户邮箱。

**Comment by zl** [comment]
同样遇到这个问题，配置CAS的email和giveName不起效。CAS返回如下：

`<cas:serviceResponse xmlns:cas="http://www.yale.edu/tp/cas">
    <cas:authenticationSuccess>
        <cas:user>zhangsan</cas:user>
        <cas:attributes>
            <cas:mail>zhangsan@example.com</cas:mail>
            <cas:givenName>三</cas:givenName>
            <cas:sn>张</cas:sn>
            <cas:cn>三 张</cas:cn>
        </cas:attributes>
    </cas:authenticationSuccess>
</cas:serviceResponse>`

JumpServer里认证设置的CAS无论怎么配置都不成功。

**Comment by qin-nz** [comment]
@zl 你配置的 CAS - 用户属性映射 也提供一下吧

**Comment by zl** [comment]
@qin-nz 解决了。

之前尝试了如对象写法`"cas:attributes":{"cas:mail":"email"}`、索引写法`cas:attributes[cas:mail]:"email"`都不对，这里的文档应该补全，误导很多人。

通过了源码逐步debug才找到问题。映射的key-value应该是这么写：

```
{
  "cas:user": "username",
  "cn": "name",
  "mail": "email"
}
```
