### ISSUE TITLE
[Bug] v3 通过 Magnus 执行的命令，会记录非人为操作的命令

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#14082]
### Product Version

3.10.13

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jumpserver3.10.3，审计台会记录非正常的命令

### 🐛 Bug Description

SQLServer数据库操作命令，在审计台的命令记录被误判风险等级为“拒绝”，并且记录的命令也为错误，并不是用户手动操作的
![image](https://github.com/user-attachments/assets/5b043b79-7279-41ab-abdd-a4bcbb6a26e7)
![image](https://github.com/user-attachments/assets/0fe01170-a7e2-4d9d-a672-8b436b5e0120)

### Recurrence Steps

1.数据库审计台记录非用户正常执行的命令

**Comment by BaiJiangJie** [comment]
是的，因为是协议转发，所以程序中不能分辨是人为执行的还是 Client 端执行的。
