### ISSUE TITLE
[Question] jumpserver审计视频的默认压缩算法采用的是哪种，还是说没有采用视频压缩算法

### ISSUE THREAD

**Issue by shibosen** [jumpserver/jumpserver#14085]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver审计视频的默认压缩算法采用的是哪种，还是说没有采用视频压缩算法

### 🤔 问题描述

jumpserver审计视频的默认压缩算法采用的是哪种，还是说没有采用视频压缩算法

**Comment by BaiJiangJie** [comment]
没有使用视频压缩算法，只是用了文本文件的 gzip 压缩。
