### ISSUE TITLE
[Bug] 通过jms，调起本地的ssms客户端，去连接sqlserver数据库，配置命令过滤drop会调起失败；

### ISSUE THREAD

**Issue by shaohuayangfit2** [jumpserver/jumpserver#14087]
### 产品版本

3.10.11

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单机部署v3.10.11

### 🐛 缺陷描述

通过jms，调起本地的ssms客户端，去连接sqlserver数据库
1，配置命令过滤drop，调起本地客户端，会失败，看日志发现，ssms连接时会创建和删除临时表，如:drop table #tmp_sp_get_sqlagent_properties|和drop table #SVer；所以被jms匹配到了，调用客户端失败；
2，关闭命令过滤，可以成功调起客户端，但是就拦截不了drop命令了；
3，配置了复杂的命令过滤，如：^(?!.*drop table tmp_sp_get_sqlagent_properties|.*drop table SVer).*drop.*$；调起客户端成功，但是拦截不了drop命令

### 复现步骤

通过jms，调起本地的ssms客户端，去连接sqlserver数据库
1，配置命令过滤drop，调起本地客户端，会失败，看日志发现，ssms连接时会创建和删除临时表，如:drop table #tmp_sp_get_sqlagent_properties|和drop table #SVer；所以被jms匹配到了，调用客户端失败；
2，关闭命令过滤，可以成功调起客户端，但是就拦截不了drop命令了；
3，配置了复杂的命令过滤，如：^(?!.*drop table tmp_sp_get_sqlagent_properties|.*drop table SVer).*drop.*$；调起客户端成功，但是拦截不了drop命令

**Comment by BaiJiangJie** [comment]
先创建高优先级的命令过滤规则，放行客户端执行的语句；
再创建一个低优先级的规则，拒绝到 drop 语句。
