### ISSUE TITLE
[Bug] sftp 文件管理，资产目录之间复制文件时选择替换无效

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#14086]
### 产品版本

v3.10.13

### 版本类型

- [X] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

标准环境

### 🐛 缺陷描述

复制文件时提示选项框，选择替换无效

### 复现步骤

1.用sftp连接一个资产，或工作台文件管理中打开资产目录
2.在test文件夹中包含back文件夹和test.txt文件，其中test.txt内容为1
3.复制test.txt到back文件夹中两次，第二次出现替换的提示框，选择是
4.未能替换，出现test.txt~文件，且这个文件不是替换前的文件，就是没能替换过去的文件

### 期望结果

正常替换

### 补充信息

发现f12包含字段 suffix: ~
![image](https://github.com/user-attachments/assets/7627aaa6-272c-49c3-980c-a5ee5d87189e)

**Comment by BaiJiangJie** [comment]
文件名称重复策略可以配置：

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/ecc5298e-5450-4023-b575-64693253b5f4">

**Comment by Ewall555** [comment]
> 文件名称重复策略可以配置：
> 
> <img width="1259" alt="image" src="https://github.com/user-attachments/assets/ecc5298e-5450-4023-b575-64693253b5f4">
> 
> 
> 

不生效，这个只对本地上传的文件生效，资产本身目录之间的复制覆盖不生效，按步骤可复现

**Comment by BaiJiangJie** [comment]
文件夹之间的复制、粘贴，后面版本看看能不能也走这个策略。
@LeeEirc

**Comment by BaiJiangJie** [comment]
看了一下不支持，暂时不考虑处理，目前的策略就是如果粘贴有重命名的文件，会在后面增加后缀 ~
