### ISSUE TITLE
[Bug] 登录一个不通的机器会一直尝试，无法中断

### ISSUE THREAD

**Issue by qin-nz** [jumpserver/jumpserver#14081]
### 产品版本

3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

无

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/c97eee04-41df-4acb-a28e-891c09cfc5ab)

如图所示，尝试登录一个资产（但是这个 ip 是不通的）， 会一直等待 129s 左右才会超时
```
error: gateway dial addr failed: ssh: rejected: connect failed (Connection timed out)
```

未到超时时间时，使用键盘 `Ctrl + C` 无法中断登录的尝试，只能等足 2 分钟才行。

### 复现步骤

连接一个不通的资产

### 期望结果

 `Ctrl + C` 可以中断登录的尝试

**Comment by BaiJiangJie** [comment]
是的，连接过程中不能中断。

**Comment by qin-nz** [comment]
@BaiJiangJie  这个对用户使用体验不好，要卡住 2 分钟才行。 那能不能改成可以让用户中断啊
