### ISSUE TITLE
开启HTTPS访问之后，页面点击打开新的Web终端，之前的粘贴内容会消失，不限于部分浏览器

### ISSUE THREAD

**Issue by ruiyin1223** [jumpserver/jumpserver#14096]
### 产品版本

V3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

环境是单机部署的V3.10.13企业版安装包

### 🐛 缺陷描述

页面粘贴内容之后，点击web终端，剪贴板上复制的内容会消失

### 复现步骤

1、在开启HTTPS访问的环境上，本地PC复制一段文本。
![image](https://github.com/user-attachments/assets/b006cebf-137d-4fd5-b74c-9d5c47e1cd52)
2、点击终端按钮。
![image](https://github.com/user-attachments/assets/19d4f808-95d7-4164-ab56-d2c8cf7ea808)
3、再选择粘贴，剪贴板的内容已经消失，只有开启HTTPS的情况下会有这样的现象。

### 期望结果

复制之后，点击新的终端页面不清空系统的粘贴板

**Comment by BaiJiangJie** [comment]
确实存在问题，后面版本研究一下是什么原因。

**Comment by ruiyin1223** [comment]
有大概的修复时间么，或者预计版本修复么

**Comment by BaiJiangJie** [comment]
暂定 v4.3.0

**Comment by ruiyin1223** [comment]
大佬，V3版本能不能考虑优化进去呢

**Comment by BaiJiangJie** [comment]
v3 不考虑。

**Comment by BaiJiangJie** [comment]
这个问题，只是首次打开的时候会丢失，打开以后再复制是可以的。

**Comment by BaiJiangJie** [comment]
所以，暂时不修改了。

> 这个问题，只是首次打开的时候会丢失，打开以后再复制是可以的。
