### ISSUE TITLE
[Bug] 4.1.0版本 WEBCLI中不能使用vim编辑文件了

### ISSUE THREAD

**Issue by systemctl529** [jumpserver/jumpserver#14097]
### Product Version

v4.1.0

### Product Edition

- [x] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

官方离线包部署。自4.0.0版本一路通过/jmsctl.sh  upgrade升级到4.1.0。外置mysql5.7.44版本数据库

### 🐛 Bug Description

通过webcli访问服务器时，vim 编辑文件会卡在空白页，无法进行操作，亦无法执行vim快捷指令。通过重启，删除容器重建等操作无法解决。

### Recurrence Steps

webcli连接服务器，vim编辑任意文件，100%触发。

**Comment by systemctl529** [comment]
vi vim nano等交互式编辑器都没办法用了，之前4.0.x版本web交互式编辑文件存在概率数据丢，目前4.1.0是无法交互编辑了。

**Comment by maninhill** [comment]
重复issue：https://github.com/jumpserver/jumpserver/issues/14004
