### ISSUE TITLE
[Feature] 云同步自定义同步属性

### ISSUE THREAD

**Issue by pearfjl** [jumpserver/jumpserver#14093]
### 产品版本

3.4

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

在Jumpserver资产列表中，对由私有云 vSphere 中同步过来的相关资产，可以由用户按需要重新自定义 Jumpserver 中资产目录结构，而不是完全照搬 vSphere 中现有的目录结构

### 解决方案

在Jumpserver资产列表中，对由私有云 vSphere 中同步过来的相关资产，可以由用户按需要重新自定义 Jumpserver 中资产目录结构，而不是完全照搬 vSphere 中现有的目录结构

**Comment by BaiJiangJie** [comment]
升级到最新版本，可以自定义。
