### ISSUE TITLE
[Feature] 希望能固定显示搜索栏

### ISSUE THREAD

**Issue by zolinxu** [jumpserver/jumpserver#14098]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

web终端上的搜索栏能固定显示吗 每次搜索都要先点一下
![企业微信截图_17256135045337](https://github.com/user-attachments/assets/712927c4-b27c-436e-a319-7d3577e4d7f3)

### 解决方案

简化操作 直接输入搜索内容即可不需要点击搜索按钮

**Comment by BaiJiangJie** [comment]
暂时不考虑放开，点了搜索之后，输入文本后不会缩小，可以持续搜索。
