### ISSUE TITLE
[Question] Web终端打不开了

### ISSUE THREAD

**Issue by jzhao20230918** [jumpserver/jumpserver#14107]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [x] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

版本：v4.1.0
linux，docker部署

### 🤔 问题描述

页面可以正常打开及登录，但是点击右上角web终端，则一直转圈打不开，如下图：
![1725864670831](https://github.com/user-attachments/assets/c6deeff3-a1c2-4f7c-b5ef-9b2ce6c4e45e)

以上问题存在以域名登录的情况，如果以IP登录jumpserver则一切正常。
看docker，所有docker都是health。

**Comment by jzhao20230918** [comment]
解决了，是因为开了cloudflare的一个统计服务，有个js可能下不下来。

**Comment by shaxiaozz** [comment]
@jzhao20230918 请问具体是cloudflarwe那个功能？我也遇到一样的问题了

**Comment by icrazt** [comment]
关闭一下 jumpserver 这个页面的 Rocket Loader 优化就好了 @shaxiaozz

**Comment by shaxiaozz** [comment]
是的。cloudflare实在有点坑坑的。 @icrazt
