### ISSUE TITLE
[Question] RDP协议的录像功能怎么关闭

### ISSUE THREAD

**Issue by alexjs001** [jumpserver/jumpserver#14101]
### Product Version

v3.10.11

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

v3.10.11 如何关闭录像功能功能

### 🤔 Question Description

v3.10.11 如何关闭录像功能功能

**Comment by BaiJiangJie** [comment]
找对对应的组件，比如：Lion。编辑设置录像存储为 null。

**Comment by alexjs001** [comment]
具体在哪里修改，方便说下嘛

**Comment by BaiJiangJie** [comment]
系统设置-组件设置中。
