### ISSUE TITLE
[Bug] ssh远程连接资产，命令无论是否执行成功都返回“成功”

### ISSUE THREAD

**Issue by AndersWantall** [jumpserver/jumpserver#14100]
### Product Version

v3.10.13

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

![image](https://github.com/user-attachments/assets/8594210e-8987-4671-8559-c6a87264d13f)
如图，远程连资产时，这个路径实际是不存在的，执行echo命令应当返回1，但返回了0

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/8594210e-8987-4671-8559-c6a87264d13f)
如图，远程连资产时，这个路径实际是不存在的，执行echo命令应当返回1，但返回了0

### Recurrence Steps

1、jumpserver创建资产
2、远程连接资产
3、按图例执行命令
4、跳过jumpserver，直连资产执行命令以比对

### Expected Behavior

希望能解答这个问题

**Comment by BaiJiangJie** [comment]
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/2d020c90-ad6a-4f88-8697-3adb9f40692c">

错误命令会返回对应的错误代码，成功的会返回0，没问题。

**Comment by wojiushixiaobai** [comment]
会出现这个问题是因为你的命令是通过跳板机连接的，所以返回的状态码是跳板机返回的，而不是真实服务器返回的。
因为执行完成了命令，所以返回了 0，这是正确的。

我在微信回复过你，你应该使用脚本，然后在脚本里面写你的逻辑，最后执行脚本即可。

**Comment by AndersWantall** [comment]
> 会出现这个问题是因为你的命令是通过跳板机连接的，所以返回的状态码是跳板机返回的，而不是真实服务器返回的。 因为执行完成了命令，所以返回了 0，这是正确的。
> 
> 我在微信回复过你，你应该使用脚本，然后在脚本里面写你的逻辑，最后执行脚本即可。

您好，因为我们是通过pycharm经过jumpserver远程连接到资产的。这中间存在的命令交互是由pycharm发起的，而不是我们能够控制的。所以也不好让pycharm使用脚本而不是命令。

**Comment by wojiushixiaobai** [comment]
没你想的这么复杂，可以参考：https://serverfault.com/questions/215756/how-do-i-run-a-local-bash-script-on-remote-machines-via-ssh

**Comment by AndersWantall** [comment]
> 没你想的这么复杂，可以参考：https://serverfault.com/questions/215756/how-do-i-run-a-local-bash-script-on-remote-machines-via-ssh 就是把你多次执行的命令合并到一起发送执行，这样你就能正确处理。

这个过程是pycharm工具自动进行的，我干预不了啊

**Comment by wojiushixiaobai** [comment]
> > 没你想的这么复杂，可以参考：https://serverfault.com/questions/215756/how-do-i-run-a-local-bash-script-on-remote-machines-via-ssh 就是把你多次执行的命令合并到一起发送执行，这样你就能正确处理。
> 
> 这个过程是pycharm工具自动进行的，我干预不了啊

你的最新问题与你的最开始的问题已经不一致。
我们目前尚不支持 pycharm 中你的这种用法。
