### ISSUE TITLE
[Bug] vi编辑文本卡死

### ISSUE THREAD

**Issue by 1165303548** [jumpserver/jumpserver#14103]
### Product Version

4.1.0-ce

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

uname -a
Linux i-5D66650E 4.19.90-2112.8.0.0131.oe1.x86_64 #1 SMP Fri Dec 31 19:54:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### 🐛 Bug Description

通过Jumpserver web方式访问linux主机，使用vi编辑文本会卡死

### Recurrence Steps

通过Jumpserver web方式访问linux主机，使用vi编辑文本会卡死

### Additional Information

![33](https://github.com/user-attachments/assets/4a21d194-6d92-4552-80b7-f069f2f7a1f9)

**Comment by Ewall555** [comment]
开https临时修复

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/14004

重复 issue。
