### ISSUE TITLE
能否在windows部署jumpserver开发环境？我在windows里面装环境有几个lib包装不了，跑不起来，求大神帮忙解答，跪谢！！！

### ISSUE THREAD

**Issue by Niclaus** [jumpserver/jumpserver#1411]
能否在windows部署开发环境？
我在本地跑不起来
        pyldap==2.4.45
	python-gssapi==0.6.4
	django-auth-ldap==1.3.0
	ephem==3.7.6.0
	pycrypto==2.6.1
这几个依赖包装不了

想在windows开发调试，然后再部署到centos

##### 使用版本
1.3.1

**Comment by jokimina** [comment]
windows我尝试是跑不起来. lib支持不太好
建议两种方式开发:
1. 如果一定要windows开发,  可以本地安装docker, 代码目录Volumes挂到linux的容器.
2. 直接在linux服务器开发, 我自己用的spacevim+tmux, 挺好使的

**Comment by Niclaus** [comment]
谢谢，我也试试。是在没办法哈哈

**Comment by ibuler** [comment]
没有在windows开发的经验，研究出来可以分享一下

有问题请重新打开issue
