### ISSUE TITLE
[Question]  v3.10.13-lts 在MAC下使用safari浏览器远程Windows机器不能复制

### ISSUE THREAD

**Issue by wsxedcer** [jumpserver/jumpserver#14112]
### Product Version

 v3.10.13-lts

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

操作系统为阿里云os3，离线安装的jump，使用内置redis和mysql，通过https访问

### 🤔 Question Description

在使用开源版的jump v3.10.13-lts时，遇到了以下的问题，测试远程win系统为 Windows 2022系统
1、在MAC下使用safari浏览器远程登录Windows机器后，不能复制字符串到远程win机器
2、使用同一台mac上的chrome浏览器就可以正常复制字符串到远程win系统
3、使用同一台mac上的safari或者chrome浏览器远程登录linux机器，均能正常复制字符串到远程机器

**Comment by BaiJiangJie** [comment]
一般建议使用 Chrome 浏览器，产品开发时主要适配的也是 Chrome。

可以研究一下，Safari 是不是需要开启一下复制、粘贴权限。

**Comment by wsxedcer** [comment]
@BaiJiangJie 使用Safari登录linux时是使用的ssh服务，登录后本地复制的字符串能正常粘贴到远程服务器上，登录win机器之后 不管是键盘复制粘贴还是鼠标复制粘贴都是空白的

**Comment by BaiJiangJie** [comment]
那可能就是不支持，暂时没有考虑适配 Safari 的计划。

**Comment by wsxedcer** [comment]
刚用手上的v2版本测试了下，Safari登录win机器需要在本地pc复制字符串之后，粘贴到浏览器远程界面的那个设置里面的剪贴板的方框里面，然后win机器里面就可以粘贴了
![image](https://github.com/user-attachments/assets/f71058bb-1774-41c0-b0ed-9ed607cbecfb)
