### ISSUE TITLE
[Bug] v4.1.0版本使用Web CLI连接服务器时，vi/vim编辑文件不出现文件内容信息，ssh命令窗口卡住

### ISSUE THREAD

**Issue by awei007** [jumpserver/jumpserver#14113]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

系统centos7.9，通过一键部署启动的jumpserver服务v4.1.0版本。

### 🐛 缺陷描述

使用Web CLI连接服务器，vi/vim编辑文件时，黑屏卡住了。通过F12开发者模式观察控制台，发现报错如下：
![Uploading image.png…]()

### 复现步骤

使用Web CLI连接服务器，vi/vim编辑文件.

**Comment by awei007** [comment]
又通过在线升级，将jumpserver版本升级v4.1.0-ce版本，问题依然存在。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/14004

下个版本修复。
