### ISSUE TITLE
[Question] assets_historicalauthbook 占42G，可以直接清空掉吗？

### ISSUE THREAD

**Issue by cuibaiyi** [jumpserver/jumpserver#14115]
### 产品版本

v2.28

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu 22.04

### 🤔 问题描述

jumpserver table assets_historicalauthbook 占用了42G。直接 TRUNCATE TABLE assets_historicalauthbook 会有什么影响吗。delete掉太慢了。

### 期望结果

清空assets_historicalauthbook表

**Comment by BaiJiangJie** [comment]
`**首先备份好数据库。**`

使用应该不会有影响，这张表是每次更新账号信息时保留的历史密码。

**Comment by cuibaiyi** [comment]
已经清空掉啦，没有影响，感谢!
我查了一下 audits_operatelog 这个表占用了15G，可以直接清空掉吗？

**Comment by BaiJiangJie** [comment]
嗯，操作日志也可以清除，只是会影响将来的审计。

**Comment by cuibaiyi** [comment]
十分感谢!
