### ISSUE TITLE
Windows Web登录超过一分钟后，回放不了

### ISSUE THREAD

**Issue by blueskyxu** [jumpserver/jumpserver#1412]
[简述你的问题]

##### 使用版本
 使用的Jumpserver版本 1.3.1

##### 问题复现步骤
1. [步骤1]
配置完成Windows所有信息
2. [步骤2]
新建的jumpserver用户已授权Windows登录；
也可以WEB远程登录；
在管理端能看到登录时长及回放，并且在/opt/jumpserver/data/media/目录也能生成回放文件；
Linux资产WEB登录，时长几十分钟可以回放；
现在的 问题是：Windows登录超过一分钟，可生成回放文件，在管理端回放不了，少于一分钟可以回放；
![image](https://user-images.githubusercontent.com/14010088/41158775-c2282200-6b5c-11e8-895d-a5b92e1cee43.png)

![image](https://user-images.githubusercontent.com/14010088/41158622-2c12ee94-6b5c-11e8-8928-930de8080897.png)
![image](https://user-images.githubusercontent.com/14010088/41158803-e27980e4-6b5c-11e8-8bd9-db13b7154e73.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
网络问题，自己排查下。

**Comment by blueskyxu** [comment]
Windows录像超过一分钟，可生成录像文件，但是无法回放。
Linux录像超过一分钟，可生成录像并可回放。

**Comment by ibuler** [comment]
应该是上传文件失败了，启动guacamole时写的jumpserver的地址是nginx的地址吗

**Comment by MikeMiao** [comment]
经过调试发现，回放页面拉取录像文件时nginx报403

![403-01](https://user-images.githubusercontent.com/17871086/42078513-635e9188-7baf-11e8-955e-d076968b54ed.png)

到录像目录内查看，发现该录像文件权限有问题正常的录像文件权限为644，出现问题的录像文件权限为600，nginx因为没有读权限，直接抛出了403错误

![403-02](https://user-images.githubusercontent.com/17871086/42083044-56881db4-7bbc-11e8-81b7-b9c90c6462e5.png)

测试将该文件的权限改为644，录像即可正常播放
![403-03](https://user-images.githubusercontent.com/17871086/42083058-5ec39b0c-7bbc-11e8-8030-b472c263d830.png)

![403-04](https://user-images.githubusercontent.com/17871086/42082906-d3e64b88-7bbb-11e8-900e-12a0cc4211c9.png)
