### ISSUE TITLE
[Bug]  授权用户资产权限，需要很久才能更新才可以用

### ISSUE THREAD

**Issue by xiaxiantao** [jumpserver/jumpserver#14123]
### Product Version

3.0.4

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

The asset permission for the user is authorized. It takes a long time to take effect. Why is this? What's the problem? How can it be solved?

### 🐛 Bug Description

The asset permission for the user is authorized. It takes a long time to take effect. Why is this? What's the problem? How can it be solved?

### Recurrence Steps

The asset permission for the user is authorized. It takes a long time to take effect. Why is this? What's the problem? How can it be solved?

**Comment by BaiJiangJie** [comment]
Upgrading to the latest version of v3.10 or upgrading to v4 can resolve the issue.

**Comment by xiaxiantao** [comment]
> Upgrading to the latest version of v3.10 or upgrading to v4 can resolve the issue.



> Upgrading to the latest version of v3.10 or upgrading to v4 can resolve the issue.
In addition, authorization can only be applied to node nodes and cannot be applied to specific assets. Is this issue also resolved in version 3.10?

**Comment by xiaxiantao** [comment]
> Upgrading to the latest version of v3.10 or upgrading to v4 can resolve the issue.

In addition, authorization can only be applied to node nodes and cannot be applied to specific assets. Is this issue also resolved in version 3.10?

**Comment by BaiJiangJie** [comment]
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/448a851a-c65f-4d7f-8547-20d9f3a7d95e">

**Comment by xiaxiantao** [comment]
> <img alt="image" width="1259" src="https://private-user-images.githubusercontent.com/32935519/366702488-448a851a-c65f-4d7f-8547-20d9f3a7d95e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzA1MjUsIm5iZiI6MTcyNjEzMDIyNSwicGF0aCI6Ii8zMjkzNTUxOS8zNjY3MDI0ODgtNDQ4YTg1MWEtYzY1Zi00ZDdmLTg1NDctMjBkOWYzYTdkOTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4MzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiM2MxYjYzN2JkYTBkN2JiNWUzZTZjZTRiMjlmNWQxNjgwY2IwOTIxNGNjNWQ3MWFiMjViMmVhNzQ4MGRmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.onne6_cFipMzJd95sjegIcpKIX-iMWcy_X6SI6GTb5o">

OK，thank you very much
