### ISSUE TITLE
[Bug] 普通用户-认证设置访问全部空白

### ISSUE THREAD

**Issue by hkhking** [jumpserver/jumpserver#14121]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

在线安装 docker运行

### 🐛 Bug Description

普通用户点击-认证设置 空白

### Recurrence Steps

进入 认证配置-》更新密码 点击 “更新” 出来的空白页面，无法修改密码

进入 认证配置-》更新ssh公钥 点击 “更新” 出来的空白页面，无法修改密码

**Comment by w940853815** [comment]
https://github.com/jumpserver/jumpserver/issues/14037 重复issue
