### ISSUE TITLE
[Bug] 可信任域名或主机配置无效

### ISSUE THREAD

**Issue by la-cat** [jumpserver/jumpserver#14129]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

docker-compose 部署
原先版本为v4.0.1，配置DOMAINS无效后，进行版本升级到v4.1.0，结果还是无效，还是可以使用ip访问，使用无痕还是清除缓存都无用。

### 🐛 Bug Description

**config.txt**
```bash
# 可信任 DOMAINS 定义,
# 定义可信任的访问 IP, 请根据实际情况修改, 如果是公网 IP 请改成对应的公网 IP,
# DOMAINS="demo.jumpserver.org:443"
# DOMAINS="172.17.200.191:80"
# DOMAINS="demo.jumpserver.org:443,172.17.200.191:80"
DOMAINS="it.***intl.com:443"
```
使用以上配置，可以用宿主机ip 与域名访问，
![image](https://github.com/user-attachments/assets/66a746a8-abcb-4d16-b355-8c28f771a520)
![image](https://github.com/user-attachments/assets/ba3903f2-1012-4f37-bb28-d3d62bf944cb)
![image](https://github.com/user-attachments/assets/f3e266af-3a64-4d7a-b2ce-bbf7ab527636)

### Recurrence Steps

从v3版本升级到v4.0.1，目前我这样升级上来的

### Expected Behavior

只能使用域名：it.***intl.com:443 进行访问

**Comment by BaiJiangJie** [comment]
修改完配置文件，重启服务。
