### ISSUE TITLE
[Bug]  拉取镜像失败 jumpserver/lion:v4.1.0-ce

### ISSUE THREAD

**Issue by hckk2024** [jumpserver/jumpserver#14120]
### Product Version

v4.1.0

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

v4.1.0

### 🐛 Bug Description

failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce

拉取镜像失败 jumpserver/lion:v4.1.0-ce

### Recurrence Steps

从V3最新版升级到V4.10 出错，提示拉去镜像失败

**Comment by wojiushixiaobai** [comment]
**Docke** 版本需要 `>= 22.0`
- https://github.com/jumpserver/jumpserver/issues/13955
- https://github.com/jumpserver/jumpserver/issues/14003
