### ISSUE TITLE
[[资产使用sftp协议手动输入账号密码连接，如果输入密码错误没有提示，只有传文件的时候才会报错connection lost] ] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14131]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

资产使用sftp协议手动输入账号密码连接，如果输入密码错误没有提示，只有传文件的时候才会报错connection lost

<img width="834" alt="image" src="https://github.com/user-attachments/assets/6703c1cb-649f-4e44-bce3-72765960870b">
<img width="909" alt="image" src="https://github.com/user-attachments/assets/37997787-9e35-4d0a-9ed2-9946aa477094">

### 解决方案

直接报错connection lost，并不知道是账号密码的问题，希望在sftp协议连接的时候如果账号密码错误直接提示出来

**Comment by LeeEirc** [comment]
因为是懒加载机制，只有真正有文件目录操作才会通过 sftp 连接资产。报错信息会考虑优化下，暴露底层的连接信息。
