### ISSUE TITLE
[Bug] vscode远程连接基于jumpserver创建的包含notebook的资产后，无法选择kernel

### ISSUE THREAD

**Issue by AndersWantall** [jumpserver/jumpserver#14147]
### Product Version

v3.10.13

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

详见Bug Description

### 🐛 Bug Description

在k8s里创建一个pod，包含了jupyterlab，python，并在jumpserver里创建了它对应的资产。用vscode远程连接，打开notebook后，kernel选择不了：如图：
![image](https://github.com/user-attachments/assets/1fb1e0c2-d8f0-4749-82c7-eefd93df5d02)

### Recurrence Steps

详见Bug Description

**Comment by wojiushixiaobai** [comment]
是否可以给一个完整的复现过程。

我搜索了下，这个现象好像是一个比较常见的现象，是否是在 JumpServer 上面必然复现？

**Comment by AndersWantall** [comment]
> 是否可以给一个完整的复现过程。
> 
> 我搜索了下，这个现象好像是一个比较常见的现象，是否是在 JumpServer 上面必然复现？

是的，如果越过jumpserver，直接远程连资产是可以的

**Comment by LeeEirc** [comment]
如果此软件使用了 sftp 的功能，调整下平台的目录为根路径 /。相关的镜像名称可以提供一份吗，方便测试。描述下复现的步骤，使用那个快捷键选择 kernel 。
