### ISSUE TITLE
[Feature] 可选允许记住MFA验证状态 7 天，而不是每次都进行MFA二次认证

### ISSUE THREAD

**Issue by zolinxu** [jumpserver/jumpserver#14149]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

可选允许记住MFA验证状态 7 天，每次都进行MFA二次认证，比较麻烦，但是关闭又很不安全。目前各云平台都有类似的功能
![image](https://github.com/user-attachments/assets/3ce41176-b7b5-43bd-b173-0e2176860420)
![image](https://github.com/user-attachments/assets/b85589be-c237-475d-98bd-c0507f8ccffd)

### 解决方案

可选允许记住MFA验证状态 7 天

**Comment by BaiJiangJie** [comment]
暂时不考虑，为了方便、忽略了安全，安全第一。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/14108

这个将来会考虑。

如果觉得麻烦，你可以装一个浏览器的 MFA 插件，这样每次就不用拿手机了，但是要保护好浏览器的安全。
