### ISSUE TITLE
[Feature] ldap登录需要修改初始密码问题

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#14140]
### 产品版本

v3.10.9

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

ldap认证如果域控账号设置了初始密码，登录之后需要修改初始密码，我登录其他用域控密码的系统都会提示修改初始密码，同时弹出个修改密码的框，可是我登录堡垒机的时候没提示我修改初始密码，就直接提示密码错误，这个能不能改一下，让堡垒机登录域控账号的时候提示修改初始密码，同时弹出修改密码的框

### 解决方案

目前在对接ldap需要修改初始密码的，能够有修改密码入口吗？否则会报认证失败，不能登录。

**Comment by BaiJiangJie** [comment]
JumpServer 不保存第三方用户的密码，所以也不支持修改。
