### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Lorenjia** [jumpserver/jumpserver#14148]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu 20.04 x86 

### 🤔 问题描述

lion pull 失败 
[+] Running 1/1
 ✘ lion Error Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)                                                                         31.0s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by Lorenjia** [comment]
failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
Error response from daemon: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce
Error: No such image: swr.cn-north-1.myhuaweicloud.com/jumpserver/lion:v4.1.0-ce

**Comment by wojiushixiaobai** [comment]
@Lorenjia 
- https://github.com/jumpserver/jumpserver/issues/13955
- https://github.com/jumpserver/jumpserver/issues/14003
- https://github.com/jumpserver/jumpserver/issues/14120
