### ISSUE TITLE
[Question] 中国大陆用户使用 README 中一键脚本安装失败的问题

### ISSUE THREAD

**Issue by GeorgeQii** [jumpserver/jumpserver#14150]
### 产品版本

latest

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Debian 12 AMD64

### 🤔 问题描述

使用推荐的sh脚本安装jumpserver，但是好像是因为docker源的问题，没办法安装。

### 补充信息

root@ubuntu-container:~# curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
curl: (16) Error in the HTTP2 framing layer
root@ubuntu-container:~# curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
curl: (28) Failed to connect to github.com port 443 after 134873 ms: Couldn't connect to server
root@ubuntu-container:~# curl -sSL https://github.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
download install script to /opt/jumpserver-installer-v4.1.0

       ██╗██╗   ██╗███╗   ███╗██████╗ ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
       ██║██║   ██║████╗ ████║██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
       ██║██║   ██║██╔████╔██║██████╔╝███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
  ██   ██║██║   ██║██║╚██╔╝██║██╔═══╝ ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
  ╚█████╔╝╚██████╔╝██║ ╚═╝ ██║██║     ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
   ╚════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

                                                                   Version:  v4.1.0-ce  

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

>>> Install and Configure Docker
1. Install Docker
complete

2. Configure Docker
complete

3. Start Docker
complete

>>> Loading Docker Image
[postgres:16.3-bullseye] pulling
[redis:7.0-bullseye] pulling
[jumpserver/core:v4.1.0-ce] pulling
[jumpserver/chen:v4.1.0-ce] pulling
[jumpserver/koko:v4.1.0-ce] pulling
[jumpserver/web:v4.1.0-ce] pulling
[jumpserver/lion:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[redis:7.0-bullseye] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[postgres:16.3-bullseye] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded

[jumpserver/core:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/koko:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[jumpserver/lion:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/chen:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[jumpserver/web:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Failed to pull image redis:7.0-bullseye
Failed to pull image postgres:16.3-bullseye
Failed to pull image jumpserver/core:v4.1.0-ce
Failed to pull image jumpserver/koko:v4.1.0-ce
Failed to pull image jumpserver/lion:v4.1.0-ce
Failed to pull image jumpserver/chen:v4.1.0-ce
Failed to pull image jumpserver/web:v4.1.0-ce
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
[+] Running 8/8
 ✘ core Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ celery Error     context canceled                                                                                                                                                                                             15.1s 
 ✘ koko Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ lion Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ chen Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ web Error        context canceled                                                                                                                                                                                             15.1s 
 ✘ redis Error      context canceled                                                                                                                                                                                             15.1s 
 ✘ postgresql Error Get "https://registry-1.docker.io/v2/": dial tcp [2a03:2880:f12c:183:face:b00c:0:25de]:443: i/o timeout                                                                                                      15.1s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2a03:2880:f12c:183:face:b00c:0:25de]:443: i/o timeout
root@ubuntu-container:~#

**Comment by BaiJiangJie** [comment]
https://community.fit2cloud.com/#/products/jumpserver/getstarted

使用这种方式安装。

**Comment by GeorgeQii** [comment]
您好，BaiJiangJie，谢谢您的支持，但是尝试您这个方法后，问题依旧。
Debian GNU/Linux 12 ubuntu-container tty1

ubuntu-container login: root
Password: 
Linux ubuntu-container 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Sep 14 09:56:44 UTC 2024 on tty1
root@ubuntu-container:~# curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash
download install script to /opt/jumpserver-installer-v4.1.0


       ██╗██╗   ██╗███╗   ███╗██████╗ ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
       ██║██║   ██║████╗ ████║██╔══██╗██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
       ██║██║   ██║██╔████╔██║██████╔╝███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
  ██   ██║██║   ██║██║╚██╔╝██║██╔═══╝ ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
  ╚█████╔╝╚██████╔╝██║ ╚═╝ ██║██║     ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
   ╚════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

                                                                   Version:  v4.1.0-ce  

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

>>> Install and Configure Docker
1. Install Docker
complete

2. Configure Docker
complete

3. Start Docker
complete

>>> Loading Docker Image
[postgres:16.3-bullseye] pulling
[jumpserver/web:v4.1.0-ce] pulling
[redis:7.0-bullseye] pulling
[jumpserver/lion:v4.1.0-ce] pulling
[jumpserver/core:v4.1.0-ce] pulling
[jumpserver/koko:v4.1.0-ce] pulling
[jumpserver/chen:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[redis:7.0-bullseye] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[postgres:16.3-bullseye] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/core:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/koko:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

[jumpserver/lion:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/chen:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[jumpserver/web:v4.1.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Failed to pull image redis:7.0-bullseye
Failed to pull image postgres:16.3-bullseye
Failed to pull image jumpserver/core:v4.1.0-ce
Failed to pull image jumpserver/koko:v4.1.0-ce
Failed to pull image jumpserver/lion:v4.1.0-ce
Failed to pull image jumpserver/chen:v4.1.0-ce
Failed to pull image jumpserver/web:v4.1.0-ce
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string. 
[+] Running 8/8
 ✘ chen Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ web Error        context canceled                                                                                                                                                                                             15.1s 
 ✘ celery Error     context canceled                                                                                                                                                                                             15.1s 
 ✘ redis Error      context canceled                                                                                                                                                                                             15.1s 
 ✘ core Error       context canceled                                                                                                                                                                                             15.1s 
 ✘ postgresql Error context canceled                                                                                                                                                                                             15.1s 
 ✘ koko Error       Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)                                                             15.1s 
 ✘ lion Error       context canceled                                                                                                                                                                                             15.1s 
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
root@ubuntu-container:~#

**Comment by GeorgeQii** [comment]
<html>
<body>

服务商 | DoH 地址 | 备注
-- | -- | --
阿里DNS | https://dns.alidns.com/dns-queryhttps://223.5.5.5/dns-queryhttps://223.6.6.6/dns-query |  
DNSPod Public DNS（腾讯DNS） | https://doh.pub/dns-queryhttps://1.12.12.12/dns-queryhttps://120.53.53.53/dns-query |  
360安全DNS（不推荐） | https://doh.360.cn/dns-query |  
apad.pro | https://doh.apad.pro/dns-query | 国内网友自建的无污染DNS分流


</body>
</html>

**Comment by windice** [comment]
我这边遇到一样的问题

uname -m
x86_64


[jumpserver/chen:v4.2.0-ce] pulling
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)


> https://github.com/jumpserver/installer/blob/e5f1a7e9dd64cb9a22dac263f0fc1e35790bcbf5/scripts/utils.sh#L626
> 
> uname -m 看一下系统架构

**Comment by BaiJiangJie** [comment]
应该是 Docker 镜像源地址没配置好，应该使用国内的镜像源才对。

看一下 DOCKER_IMAGE_MIRROR 配置项是不是 1。

**Comment by BaiJiangJie** [comment]
查看一下下载的离线包中：/opt/jumpserver-installer-v4.1.0

config-example.txt 文件中 `DOCKER_IMAGE_MIRROR=1` 是否是打开的。

<img width="934" alt="image" src="https://github.com/user-attachments/assets/b10741bb-0c92-4309-8ee4-765ff09bbab0">

@windice @GeorgeQii
