### ISSUE TITLE
[Question] windows RDP 卡在 Connecting ...

### ISSUE THREAD

**Issue by BEF841CA** [jumpserver/jumpserver#14165]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

* OS: Debian GNU/Linux 12
* Docker: 27.0.3
* Docker Compose: v2.27.0
* Windows: Windows Server 2022 Standard 21H2
* Browser: Microsoft Edge 128.0.2739.67

### 🤔 问题描述

连接 - RDP    页面卡在 Connecting ... 中没有反应

![image](https://github.com/user-attachments/assets/9be38abf-b165-48da-bf6f-69c984825371)
 

### 期望结果

可以正常通过RDP连接资源

### 补充信息

jumpserver到资源的网络是通的（SSH 可以连接）
![17263057421593](https://github.com/user-attachments/assets/d4a27c64-1601-4d8e-b5fc-4bd2409aa228)
资源的账号有远程桌面的权限，可以通过远程桌面连接

**Comment by BaiJiangJie** [comment]
查看一下 Lion 组件的日志。

**Comment by BEF841CA** [comment]
> 查看一下 Lion 组件的日志。

[GIN] 2024/09/14 - 18:19:44 | 200 |     193.131µs |             ::1 | GET      "/lion/health/"
[GIN] 2024/09/14 - 18:19:53 | 200 |   83.918395ms |     192.168.7.8 | GET      "/lion/connect/?token=781f3dfc-f211-445a-94df-71afe15f9cb3"
[GIN] 2024/09/14 - 18:19:53 | 200 |     171.339µs |     192.168.7.8 | GET      "/lion/assets/css/app.bc2d844d.css"
[GIN] 2024/09/14 - 18:19:53 | 200 |    1.044663ms |     192.168.7.8 | GET      "/lion/assets/css/chunk-vendors.5f7cea88.css"
[GIN] 2024/09/14 - 18:19:53 | 200 |    1.435408ms |     192.168.7.8 | GET      "/lion/assets/js/app.0a3dbc45.js"
[GIN] 2024/09/14 - 18:19:53 | 200 |      6.7691ms |     192.168.7.8 | GET      "/lion/assets/js/chunk-vendors.f2af44c4.js"
[GIN] 2024/09/14 - 18:19:53 | 200 |    1.898277ms |     192.168.7.8 | GET      "/lion/assets/js/45.9b36e21e.js"
[GIN] 2024/09/14 - 18:19:53 | 200 |    3.361896ms |     192.168.7.8 | GET      "/lion/assets/css/45.84062b25.css"
[GIN] 2024/09/14 - 18:19:53 | 200 |     466.553µs |     192.168.7.8 | GET      "/lion/assets/fonts/element-icons.ff18efd1.woff"
[GIN] 2024/09/14 - 18:19:54 | 200 |     107.014µs |             ::1 | GET      "/lion/health/"
2024/09/14 18:19:54 5.audio,1.1,31.audio/L16; instruction with bad Content: 5.audio,1.1,31.audio/L16
2024-09-14 18:19:54 tunnel conn.go [ERROR] Session[bd275d29-3ef0-408a-873e-93b66620a705] guacamole server read err: EOF
2024-09-14 18:19:54 session server.go [ERROR] 录像文件小于1024字节，可判断连接失败，未能产生有效的录像文件
[GIN] 2024/09/14 - 18:19:55 | 200 |  1.746150665s |     192.168.7.8 | GET      "/lion/ws/connect/?TOKEN_ID=781f3dfc-f211-445a-94df-71afe15f9cb3&GUAC_WIDTH=1530&GUAC_HEIGHT=862&GUAC_DPI=96&GUAC_KEYBOARD=en-us-qwerty&GUAC_IMAGE=image%2Fjpeg&GUAC_IMAGE=image%2Fpng&GUAC_IMAGE=image%2Fwebp&GUAC_AUDIO=audio%2FL8&GUAC_AUDIO=audio%2FL16"
[GIN] 2024/09/14 - 18:20:04 | 200 |      97.889µs |             ::1 | GET      "/lion/health/"

**Comment by LeeEirc** [comment]
日志级别开启 DEBUG，`vi /opt/jumpserver/config/config.txt`

```
LOG_LEVEL=DEBUG
```

重启服务，查看下 guacd.log 日志

```
tail -f /data/jumpserver/lion/data/logs/guacd.log
```

**Comment by BEF841CA** [comment]
之前是Windows-RDP，切换成Windows-TLS 依旧是卡在 Connecting ... ，切换成Windows 就可以正常连接了。这三者有什么区别么？

**Comment by LeeEirc** [comment]
如果Windows没有特殊定制的情况下，默认使用 Windows 平台就好了。
![image](https://github.com/user-attachments/assets/2fb2a321-868e-4ff6-863e-42b2b0e5da04)

**Comment by BEF841CA** [comment]
明白。非常感谢！
