### ISSUE TITLE
[Question] redis.sentinel.MasterNotFoundError: No master found for 'mymaster'

### ISSUE THREAD

**Issue by dxg0716** [jumpserver/jumpserver#14166]
### Product Version

4.1.0

### Product Edition

- [x] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

k8s version: 1.25.4
jumpserver chart: v4.1.0
redis: v7.2.3
redis-sentinel: v7.2.3

### 🤔 Question Description

redis svc & redis-sentinel
`$ kubectl get svc -n redis 
NAME                                            TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)             AGE
redis-replication-jumpserver                    ClusterIP   192.168.238.60    <none>        6379/TCP,9121/TCP   30h
redis-replication-jumpserver-additional         ClusterIP   192.168.65.240    <none>        6379/TCP            30h
redis-replication-jumpserver-headless           ClusterIP   None              <none>        6379/TCP            30h
redis-sentinel-jumpserver-sentinel              ClusterIP   192.168.240.231   <none>        26379/TCP           56m
redis-sentinel-jumpserver-sentinel-additional   ClusterIP   192.168.217.213   <none>        26379/TCP           56m
redis-sentinel-jumpserver-sentinel-headless     ClusterIP   None              <none>        26379/TCP           56m`

values.yaml写了headless svc地址
`externalSentinel:
  hosts: mymaster/redis-sentinel-jumpserver-sentinel-headless.redis:26379
  password: "Bdxxxxx"
  socketTimeout: 5`

helm install 初始化数据库job 失败，pod日志
`kubectl logs -f -n jumpserver jumpserver-jms-init-db-nxjq6
2024-09-14 16:54:20 [DEBU] Start subscribe for expire orgs mapping from memory
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 19, in ready
    django_ready.send(CommonConfig)
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/orgs/signal_handlers/common.py", line 50, in subscribe_orgs_mapping_expire
    orgs_mapping_for_memory_pub_sub.subscribe(
  File "/opt/jumpserver/apps/common/utils/connection.py", line 29, in subscribe
    ps.subscribe(self.ch)
  File "/opt/py3/lib/python3.11/site-packages/redis/client.py", line 927, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/client.py", line 756, in execute_command
    self.connection = self.connection_pool.get_connection(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/sentinel.py", line 55, in connect
    return self.retry.call_with_retry(self._connect_retry, lambda error: None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/opt/py3/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/sentinel.py", line 45, in _connect_retry
    self.connect_to(self.connection_pool.get_master_address())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/sentinel.py", line 107, in get_master_address
    master_address = self.sentinel_manager.discover_master(self.service_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/sentinel.py", line 301, in discover_master
    raise MasterNotFoundError(f"No master found for {service_name!r}{error_info}")
redis.sentinel.MasterNotFoundError: No master found for 'mymaster'`

请问是哪里配置有问题呢

**Comment by wojiushixiaobai** [comment]
Redis Sentinel 没配置好，使用 redis-cli 验证下，应该是 Sentinel 或者 Redis 其中的一个密码不对或者没有密码

**Comment by dxg0716** [comment]
> Redis Sentinel 没配置好，使用 redis-cli 验证下，应该是 Sentinel 或者 Redis 其中的一个密码不对或者没有密码

redis pod中链接redis是没问题的
`$ **kubectl exec -it -n redis redis-replication-jumpserver-0 -c redis-replication-jumpserver -- bash**
bash-5.1$ **redis-cli -h $(hostname) -p ${REDIS_PORT} -a ${REDIS_PASSWORD}**
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis-replication-jumpserver-0:6379> 
**redis-replication-jumpserver-0:6379> info**
# Server
redis_version:7.2.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:c9995ccd1c9928ca
redis_mode:standalone
os:Linux 5.15.0-48-generic x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll`

Sentinel 链接也是没问题的
`$ **kubectl exec -it -n redis redis-sentinel-jumpserver-sentinel-1 -- bash**
bash-5.1$ **redis-cli -h $(hostname) -p ${SENTINEL_PORT} -a ${REDIS_PASSWORD}**
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
redis-sentinel-jumpserver-sentinel-1:26379> 
**redis-sentinel-jumpserver-sentinel-1:26379> sentinel master mymaster**
 1) "name"
 2) "mymaster"
 3) "ip"
 4) "172.16.0.209"
 5) "port"
 6) "6379"
 7) "runid"
 8) ""
 9) "flags"
10) "s_down,master,disconnected"`

**Comment by wojiushixiaobai** [comment]
去掉 -a 和密码重新测试

**Comment by dxg0716** [comment]
@wojiushixiaobai  去掉也是是不行的

> 去掉 -a 和密码重新测试

`**kubectl get pod -n redis -owide**
NAME                                   READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
redis-replication-jumpserver-0         2/2     Running   0          38h     172.16.0.209   10.1.41.255   <none>           <none>
redis-replication-jumpserver-1         2/2     Running   0          38h     172.16.1.39    10.1.10.1     <none>           <none>
redis-replication-jumpserver-2         2/2     Running   0          38h     172.16.1.102   10.1.55.253   <none>           <none>
redis-sentinel-jumpserver-sentinel-0   1/1     Running   0          9m13s   172.16.0.198   10.1.41.255   <none>           <none>
redis-sentinel-jumpserver-sentinel-1   1/1     Running   0          9m12s   172.16.1.68    10.1.55.253   <none>           <none>
redis-sentinel-jumpserver-sentinel-2   1/1     Running   0          9m10s   172.16.1.43    10.1.10.1     <none>           <none>`

**redis pod中直连**
`kubectl exec -it -n redis redis-replication-jumpserver-0 -- bash
Defaulted container "redis-replication-jumpserver" out of: redis-replication-jumpserver, redis-exporter
bash-5.1$ redis-cli -h $(hostname) -p ${REDIS_PORT}
redis-replication-jumpserver-0:6379> info
NOAUTH Authentication required.`

Sentinel pod中直连
`kubectl exec -it -n redis redis-sentinel-jumpserver-sentinel-0 -- bash
bash-5.1$ redis-cli -h $(hostname) -p ${SENTINEL_PORT} 
redis-sentinel-jumpserver-sentinel-0:26379> sentinel master mymaster
(error) NOAUTH Authentication required.`

**Comment by dxg0716** [comment]
@wojiushixiaobai 我这边redis、jumpserver、Sentinel是部署在k8s中的，Sentinel使用了statefulsets了，同时jumpserver helm chart的values.yaml中的externalSentinel.hosts写的是Sentinel的headless service，会跟headless service有关系吗？

#kubectl get svc -n redis 
NAME                                            TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)             AGE
redis-replication-jumpserver                    ClusterIP   192.168.238.60    <none>        6379/TCP,9121/TCP   38h
redis-replication-jumpserver-additional         ClusterIP   192.168.65.240    <none>        6379/TCP            38h
redis-replication-jumpserver-headless           ClusterIP   None              <none>        6379/TCP            38h
redis-sentinel-jumpserver-sentinel              ClusterIP   192.168.123.225   <none>        26379/TCP           25m
redis-sentinel-jumpserver-sentinel-additional   ClusterIP   192.168.112.206   <none>        26379/TCP           25m
redis-sentinel-jumpserver-sentinel-headless     ClusterIP   None              <none>        26379/TCP           25m

**Comment by wojiushixiaobai** [comment]
那只能用 python 的 redis 模块手动连接看看了。节后我找个环境验证下
