### ISSUE TITLE
[Question] 请问，jumpserver 连接k8s pod，使用的是什么协议，ssh吗，还是和kubectl exec使用的协议保持一致？

### ISSUE THREAD

**Issue by yxxchange** [jumpserver/jumpserver#14174]
### Product Version

latest

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

无

### 🤔 Question Description

请问，jumpserver 连接k8s pod，使用的是什么协议，ssh吗，还是和kubectl exec使用的协议保持一致？

**Comment by LeeEirc** [comment]
类似与 kubectl exec 的方式
