### ISSUE TITLE
[Question] 4.1.0版本还有批量命令和作业中心这两项吗

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#14176]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

4.1.0社区版

### 🤔 Question Description

我部署了4.1.0的社区版本，登录后发现找不到批量命令和作业中心这两个功能了。新版本是否取消了这两个功能

**Comment by BaiJiangJie** [comment]
有的，在工作台中。

**Comment by seaurching** [comment]
> 有的，在工作台中。

![image](https://github.com/user-attachments/assets/52222eec-bce1-4df9-af48-151a04a50c2f)
我这里没有

**Comment by BaiJiangJie** [comment]
系统设置-功能设置-作业中心，开启。

新版本默认没有开启。

**Comment by seaurching** [comment]
已经开启
