### ISSUE TITLE
[Bug] 最近登录记录不完整

### ISSUE THREAD

**Issue by tianmaxingkong168** [jumpserver/jumpserver#14179]
### 产品版本

v3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：ubuntu22.04
安装方式：初始安装v.3.10.12，然后升级到v3.10.13

### 🐛 缺陷描述

9月10号登录系统，9月11号登录系统，9月12号登录系统，最近登录记录不完整，没有9月11号登录系统的记录

### 复现步骤

1、周一至周五每天登录系统；
2、查看右侧最近登录；
3、发现不是每天的登录都记录。

### 期望结果

每次登录都有记录。

### 尝试过的解决方案

初始安装v3.10.12存在此问题，最近升级到v3.10.13依然存在此问题。

**Comment by BaiJiangJie** [comment]
上传截图，详细说明问题。
