### ISSUE TITLE
[Feature] 工作台的作业管理能否自动添加某个节点下面的新资产

### ISSUE THREAD

**Issue by zjdc** [jumpserver/jumpserver#14177]
### 产品版本

3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

1. 工作台-作业中心-作业管理能否自动添加某个节点下面的新资产，目前在堡垒机纳管了新的资产之后，需要手动的在作业管理里面添加资产。
![image](https://github.com/user-attachments/assets/08257047-52fa-4b4e-a70d-c5cee0f8e682)

### 解决方案

暂无

### 补充信息

暂无

**Comment by BaiJiangJie** [comment]
不可以，作业管理只能选资产。

**Comment by zjdc** [comment]
目前明确了是不行的，后续能否新增添加节点的功能呢？
