### ISSUE TITLE
录像和命令分开设置保存时间

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#14181]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

分别设置录像和命令的保留时长
![image](https://github.com/user-attachments/assets/880b10a3-bfed-4a39-b906-2b9edd74965f)

### 解决方案

分别设置录像、命令记录的保留时间

**Comment by BaiJiangJie** [comment]
暂时不考虑。
