### ISSUE TITLE
审计日志无法对接es

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#14188]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.13
单机环境
审计日志对接es

### 🐛 缺陷描述

目前审计日志无法对接es，添加es配置参数报错
默认存储在MySQL中，如果审计数据过大，会导致审计数据中间部分丢失
![image](https://github.com/user-attachments/assets/c7d20e3a-0c24-46fa-a334-36fb81f09000)

### 复现步骤

按照官网示例配置报错
![image](https://github.com/user-attachments/assets/1502d0b2-917b-4c58-b696-aa127506632a)
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/021768d3-536b-4ffa-ad08-d59fc830970b">

**Comment by BaiJiangJie** [comment]
配置文件看一下。

**Comment by wangzhishang02** [comment]
<img width="755" alt="image" src="https://github.com/user-attachments/assets/97d48df9-400d-4696-88ea-02bb971ee47d">

**Comment by BaiJiangJie** [comment]
{} 使用 "" 包起来。

**Comment by wangzhishang02** [comment]
启动日志报错，无法正常启动
<img width="865" alt="image" src="https://github.com/user-attachments/assets/07b1811a-dbe3-4797-88c4-3dc875c70662">
