### ISSUE TITLE
[使用gpt资产，发现回复的文本过长时输出不全] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14183]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.12的环境，使用chrome浏览器，在gpt对话时，展示内容不全，放大缩放浏览器也没用

### 🐛 缺陷描述

v3.10.12的环境，使用chrome浏览器，在gpt对话时，展示内容不全，放大缩放浏览器也没用

### 复现步骤

v3.10.12的环境，使用chrome浏览器，在gpt对话时，展示内容不全，放大缩放浏览器也没用
<img width="514" alt="wecom-temp-85090-8a7240fe633127bc7f1bd9e788fb4a45" src="https://github.com/user-attachments/assets/9fe45f8e-9243-4fda-9342-c39e6c757a68">

**Comment by BaiJiangJie** [comment]
v3 的 GPT 资产暂时不修复了，v4 版本没有了 GPT 资产，只有 Chat AI 聊天助手。
