### ISSUE TITLE
[Bug]  在 web 终端上 ctrl +c  变成了 ctrl + z

### ISSUE THREAD

**Issue by tanguofu** [jumpserver/jumpserver#14189]
### 产品版本

v4.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

使用helm 部署

### 🐛 缺陷描述

在web 终端里面, ctrl +c , ctrl +z 都变成了 ^z

### 复现步骤

在web 终端里面, ctrl +c , ctrl +z 都变成了 ^z

### 期望结果

求解决方案 谢谢

**Comment by BaiJiangJie** [comment]
可能是你主机上的 bash 环境配置问题？连接不同的主机试试
