### ISSUE TITLE
[Bug] 网域网关-连接mongo资产，如果是域名的地址，无法解析dns

### ISSUE THREAD

**Issue by ghqzsong** [jumpserver/jumpserver#14186]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

v4.1.0离线安装

### 🐛 Bug Description

网域网关-连接mongo资产，如果是域名的地址，会无法解析dns
报错： Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp: lookup xxxx.mongodb.ivolces.com on 127.0.0.11:53: no such host
另外：自建的mongo，用IP是可以连接的，用域名也不可以连

### Recurrence Steps

如上

**Comment by BaiJiangJie** [comment]
场景是连接 MongoDB 数据库时，配置了网域网关，对吗？

MongoDB 资产地址和网域网关地址，分别适用 IP 和 域名是可连接性是什么样的？

- [ ] Gateway IP + MongoDB IP
- [ ] Gateway Domain + MongoDB Domain
- [ ] Gateway IP + MongoDB Domain
- [ ] Gateway Domain + MongoDB IP

**Comment by ghqzsong** [comment]
网关连接配置是IP
自建的mongo是单机版，使用IP可以连接，使用域名不可以
云商的mongo是副本集，使用域名或者IP都不可以

**Comment by BaiJiangJie** [comment]
那应该是你的 JumpServer 服务器配置问题，ping 一下 IP 或者域名，测试一下。

**Comment by ghqzsong** [comment]
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/771d20a1-6b77-4f42-a529-fe95f65e302e">
网关机器上，数据库域名是可用的

**Comment by ghqzsong** [comment]
之前在这台网关机器上，部署过jumpserver
在网关机器上的jumpserver，通过域名连接云商的mongo副本集，是可以的

**Comment by BaiJiangJie** [comment]
那就不知道是什么原因了。

**Comment by Duke1616** [comment]
这个问题是副本集模式连接会进行 DNS 的协商，但是看 koko 的实现方式是把远端的 mongo 代理到了本地运行，连接的时候是直接和本地的 127.0.0.1:0 地址建立连接，但是真实连接后程序是通过 koko 容器的 dns 去解析远端mongo副本集，所以导致无法连接。
