### ISSUE TITLE
[Bug] 经常无法复制粘贴

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#14180]
### 产品版本

V4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

V4.1.0
Firefox 130.0 (64 位)）

### 🐛 缺陷描述

升级后经常有反馈说无法复制粘贴，浏览器有firefox,chrome等，使用web cli 登录 linux资产。右键复制选定内容，再右键粘贴，就经常粘贴不到内容，多试验几次又可能会成功。我本人测试 （Firefox 130.0 (64 位)）也常见此类现象，应该跟浏览器关系不大。复制后我直接粘贴到写字版是没问题的，右键页面在webcli钟粘贴没反应。

### 复现步骤

web cli 登录资产，选择内容，右键“复制”，右键“粘贴"
结果并没有按预期贴出上一步复制到的内容。

**Comment by BaiJiangJie** [comment]
我测试没有出现过。

**Comment by fengmikaelson** [comment]
我以为我是个例，没想道有人提case了
没错，经常没复制上！！！很频繁。

**Comment by sunming2017** [comment]
chrome表示同样无法复制

**Comment by jym503558564** [comment]
@sunming2017 @fengmikaelson @fengmikaelson  录屏一下操作，我们这边复现看看？

**Comment by SmallGaoX** [comment]
同样的问题，多个浏览器测试都是一样，刷新之后大概率可以粘贴

**Comment by satsuki887** [comment]
我这边有几种情况：
1、打开和退出vi编辑器都会清除粘贴板的内容
2、当前窗口，框选任意内容复制后，保持原内容在框选状态，直接粘贴没问题；但复制后，点一下空白处，原内容没有了框选，粘贴板也清空了

**Comment by BaiJiangJie** [comment]
v4.1.0 的 Bug，v4.2.0 版本已修复。
