### ISSUE TITLE
[Question] Can't login Jumpserver

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#14199]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

RHEL 8.4

### 🤔 Question Description

After upgrading from 3.8.1 to 4.1.0, some users can't login Jumpserver like: Access web site Jumpserver -> Login Account -> Input OTP -> Return Screen Login Jumpserver again.
Most of users use Chrome version 128.
Now bypass through use microsoft edge or incognito tab chrome.

How can I do to fix it?

**Comment by BaiJiangJie** [comment]
This is a bit strange. It only happens to some users? Do these users have any common characteristics? By the way, let’s take a look at the jumpserver.log log file.

**Comment by BaiJiangJie** [comment]
Will there be any issues if you use Chrome version 102 to log into another user’s account?

**Comment by tsukiazuma** [comment]
No, I tried with other user's account and admin account success

**Comment by BaiJiangJie** [comment]
Will users who fail to log in using Chrome versions 125 or 128 be able to log in successfully with your version 102?

**Comment by tsukiazuma** [comment]
Yeah, can do it

**Comment by BaiJiangJie** [comment]
Other users have not encountered a similar issue so far. Can you continue upgrading to v4.2?
