### ISSUE TITLE
[Question] 初始数据失败

### ISSUE THREAD

**Issue by huisebug** [jumpserver/jumpserver#14197]
### Product Version

v4.1.0-ce

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

![image](https://github.com/user-attachments/assets/dc77f227-0b60-49de-bed9-210fb2dcf476)

### 🤔 Question Description

初始数据失败

**Comment by BaiJiangJie** [comment]
报错显示你的 Redis 服务没启动成功。
