### ISSUE TITLE
节点Comment 值配置问题

### ISSUE THREAD

**Issue by yuanguoping** [jumpserver/jumpserver#1420]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.1]

##### 问题复现步骤
 输入 g 显示您有权限的节点
Comment 值在哪里配置呢？

![qq 20180611195121](https://user-images.githubusercontent.com/34155972/41230034-d98acaa0-6db0-11e8-8b71-08668768582b.jpg)

**Comment by jokimina** [comment]
1.3.1 的资产组(AssetGroup)已经被节点(Node)取代,  看目前Node的model不支持comment

**Comment by ibuler** [comment]
已处理掉
