### ISSUE TITLE
[Bug] 账号推送已存在的用户，推送参数中用户组不生效

### ISSUE THREAD

**Issue by wangzhishang02** [jumpserver/jumpserver#14207]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v3.10.13
资产：centos 7.9

### 🐛 缺陷描述

账号推送
如果资产上已经存在被推送的账号，推送参数中的用户组不生效
![image](https://github.com/user-attachments/assets/4eca53a4-e37c-4104-90c8-7383ead2de40)

### 复现步骤

1、先推送一个账号，不额外设置用户组进行推送
2、推送完成后，更新推送参数中的用户组
3、查看推送的用户所属组，发现是没有更改的

### 期望结果

推送时能够更新用户组信息

**Comment by BaiJiangJie** [comment]
是的，只有首次推送的时候生效。
