### ISSUE TITLE
[Question] File Manager (file transfer) error 400 backend.

### ISSUE THREAD

**Issue by obgranat** [jumpserver/jumpserver#14214]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

We using Jumpserver in cluster mode on Ubuntu 22.04.

### 🤔 Question Description

How fix error "Unable to connect to backend. HTTP error 400" in File Manager PAM Jumpserver?

### Additional Information

The problem occured after realize LB on HAproxy. If i use any node PAM Jumpserver directly the problem don't occur. HAproxy we configured only for balance and redirection web interface the PAM. Maybe there need additional parameter in the config file special for redirect sftp protocol?

**Comment by obgranat** [comment]
![file_manager_problem](https://github.com/user-attachments/assets/98d045a3-5661-4e80-aa0a-edfc2767a4d2)

**Comment by BaiJiangJie** [comment]
This issue occurs because the client initially connected to KoKo-01 when connecting to the SFTP server, but subsequent operations were routed to KoKo-02, causing the connection to fail.

You need to configure IP hashing in HA Proxy to ensure that the client always connects to the same component when accessing the asset.

**Comment by obgranat** [comment]
Hello!
We have already done this setup, maybe there are other reasons for sftp errors through HA proxy?
![haproxy_cgf_by_sftp_case](https://github.com/user-attachments/assets/30b9b429-04e0-461a-a812-6d7bb09b9a6a)

**Comment by BaiJiangJie** [comment]
To set up the source IP hash-based algorithm, you need to use `balance source` in your configuration.

**Comment by BaiJiangJie** [comment]
The two HA nodes must share the same Redis service.

**Comment by LeeEirc** [comment]
try to add  configuration `hash-type consistent`  to ensure that requests from the same browser are consistently directed to the same KoKo server.
"""
balance source
hash-type consistent
"""

**Comment by obgranat** [comment]
The problem was solved by configuration 
balance hdr(X-Forwarded-For) for the http mode
sorry for the slow feedback
