### ISSUE TITLE
[Bug] 配置LDAP会自动还原

### ISSUE THREAD

**Issue by yulinor** [jumpserver/jumpserver#14217]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

helm 包安装 

### 🐛 缺陷描述

admin账号登陆后，配置ldap登陆。配置信息填写完毕、开启ldap功能，选择提交。测试链接正常，可以获取到用户数；测试ldap用户登陆提示Authentication failed (before login check failed): not enabled auth ldap。刷新页面再看即可发现ldap开关已被关闭，配置信息已被还原。

### 复现步骤

admin账号登陆后，配置ldap登陆。配置信息填写完毕、开启ldap功能，选择提交。测试链接正常，可以获取到用户数；测试ldap用户登陆提示Authentication failed (before login check failed): not enabled auth ldap。刷新页面再看即可发现ldap开关已被关闭，配置信息已被还原。

### 期望结果

能够正常保存ldap信息，不被还原。

**Comment by yulinor** [comment]
在ldap页面提交配置后，使用同步用户功能，选择导入某几个用户，偶尔可以成功，多数情况失败。
导入后可以在用户组中找到用户，但是用户登陆失败。
admin查看登陆日志发现用户的登录认证方式为「-」，没有触发ldap模式，再次查看ldap配置又被还原为空

**Comment by yulinor** [comment]
重启所有pod解决，

可能的原因与解决方法：
1. 除了chen web pod数量为1，其他都为2
2. 刚部署的时候没找到admin默认密码，v3文档里是admin/admin，由于v4文档内容少，没有注意到v4的账密 admin/ChangeMe，所以exec po 执行python manage.py修改的密码
3. 重启所有Pod且修改core pod数量为1
4. 确认已正常保存了ldap数据，此前core pod 的日志中都是些固定任务形式的日志，没有看到error。

**Comment by BaiJiangJie** [comment]
多个 core 的 pod 节点之间使用的 MySQL 和 Redis 是同一个吗？

**Comment by yulinor** [comment]
> 多个 core 的 pod 节点之间使用的 MySQL 和 Redis 是同一个吗？
> 
> 将 core 的 pod 数量修改为一个应该也可以解决。

helm install 部署的所以是统一的中间件，不会有二义性
确实缩减core 数量为1后解决了，也可能是先重启就解决了。当时没有在重启所有deployment后验证，接着就缩了core，这点没办法查了。

**Comment by BaiJiangJie** [comment]
应该还是多个之间信息不同步的问题，系统设置改变后，每一个 core 的 pod 进程检测到会使用 Redis 的 Pub、Sub 机制同步给其他 pod 的进程，你从这个角度考虑考虑，pod 应该怎么设置。

**Comment by yulinor** [comment]
> 应该还是多个之间信息不同步的问题，系统设置改变后，每一个 core 的 pod 进程检测到会使用 Redis 的 Pub、Sub 机制同步给其他 pod 的进程，你从这个角度考虑考虑，pod 应该怎么设置。

前面解决后，扩容到2，又多次重启所有dep都没有相关问题了，暂时没时间搞这个了
