### ISSUE TITLE
[Feature] Encryption algorithm choice for account template

### ISSUE THREAD

**Issue by obgranat** [jumpserver/jumpserver#14215]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

Encryption algorithm functionality for creation and management account template. please to add this ability in next release in future.

### 解决方案

Be able to manage encryption algorithm settings in the web interface for an account template or a push accounts.

### 补充信息

Are you planning to add the ability to select the algorithm and key size for the management account template? 
RSA 2048 is hardcoded into the PAM code by default. But PAM supports any encryption algorithms. (eg ed25519 or DSA). Is there any better way to properly change this default configuration?

**Comment by BaiJiangJie** [comment]
Currently, there are no plans for this. By default, RSA algorithm will be used, but we may consider supporting the option to choose in the future.

**Comment by obgranat** [comment]
Thanks for your replay.
