### ISSUE TITLE
[Bug] Web 终端使用 sz 下载 100kb 左右的文件卡在 99% 并控制台报错

### ISSUE THREAD

**Issue by SmallGaoX** [jumpserver/jumpserver#14216]
### Product Version

v4.2.0; v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Rocky Linux release 9.4 (Blue Onyx)

Client: Docker Engine - Community
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 27.2.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-427.28.1.el9_4.x86_64
 Operating System: Rocky Linux 9.4 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.382GiB
 Name: jumpserver
 ID: 494993a3-2aaf-4d9e-9fb7-8278d4825beb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.ccs.tencentyun.com/
 Live Restore Enabled: true

### 🐛 Bug Description

使用web终端在下载文件报错：
<img width="424" alt="image" src="https://github.com/user-attachments/assets/a7085cdf-2726-4f07-a087-9a64353d658b">

### Recurrence Steps

使用web终端使用sz下载文件，卡在百分之九十几

**Comment by BaiJiangJie** [comment]
多大的文件？

**Comment by SmallGaoX** [comment]
> 多大的文件？

测试过六次，在100kb以上百分比卡着，以下大概率能下载

**Comment by SmallGaoX** [comment]
> > 多大的文件？
> 
> 测试过六次，在100kb以上百分比卡着，以下大概率能下载

Edge版本 128.0.2739.79 (正式版本) (arm64)
Chrome版本 128.0.6613.85（正式版本） (arm64)

还有我们同事的Windows平台也是同样的问题
Google Chrome 版本 128.0.6613.114（正式版本）
Microsoft Edge 版本 128.0.2739.79 (正式版本) (64 位)

**Comment by BaiJiangJie** [comment]
rz、sz 这块确实问题比较明显，目前还没有比较好的方案来解决。

**Comment by SmallGaoX** [comment]
> rz、sz 这块确实问题比较明显，目前还没有比较好的方案来解决。

那我们现在只有回退或者使用其它方式下载了哈

**Comment by BaiJiangJie** [comment]
使用 SFTP 文件管理吧，回退估计也不行。

还在找解决方案。

**Comment by de-conf** [comment]
有什么最新进展吗?  或者考虑下内置trzsz, sftp 老是需要网页登录下载不方便

**Comment by SmallGaoX** [comment]
> 有什么最新进展吗? 或者考虑下内置trzsz, sftp 老是需要网页登录下载不方便

已在4.4.0中修复了，升级后没问题
