### ISSUE TITLE
[Question] ssl证书加载后无法正常访问

### ISSUE THREAD

**Issue by angel20009123** [jumpserver/jumpserver#14226]
### 产品版本

4.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

[root@Rocky9 nginx]# cat lb_http_server.conf 
# Todo: May be can auto discovery
upstream http_server {
  ip_hash;
  server web:8080;  # 这个是可以通过容器访问, 外部访问是 80端口
  # server HOST2:80;  # 另外的要写真实IP
}
server {
  listen 80;
  # listen [::]:80;
  server_name jumpserver.kq.gov.cn;  # 取消注释并自行修改成你自己的域名
  return 307 https://$server_name$request_uri;
}
server {
  listen 443 ssl http2;
  # listen [::]:443 ssl http2;
  server_name jumpserver.kq.gov.cn;      # 取消注释并自行修改成你自己的域名
  server_tokens off;
  ssl_certificate /opt/jumpserver-installer-v4.2.0/config_init/nginx/cert/server.crt;        # 修改 server.crt 为你的证书, 不要改路径 certs/
  ssl_certificate_key /opt/jumpserver-installer-v4.2.0/config_init/nginx/cert/server.key;    # 修改 server.key 为你的证书, 不要改路径 certs/
  ssl_session_timeout 1d;

[root@Rocky9 nginx]# ping jumpserver.kq.gov.cn
PING jumpserver.kq.gov.cn (10.59.0.35) 56(84) bytes of data.
64 bytes from Rocky9.3.x (10.59.0.35): icmp_seq=1 ttl=64 time=0.099 ms
64 bytes from Rocky9.3.x (10.59.0.35): icmp_seq=2 ttl=64 time=0.115 ms

10.59.0.35为本地IP

[root@Rocky9 nginx]# firewall-cmd --list-ports
443/tcp 60422/tcp
[root@Rocky9 nginx]# 

### 🤔 问题描述

80端口正常打开可以访问 ,HTTPS  无法正常访问
![image](https://github.com/user-attachments/assets/97466bfd-725d-41d4-b883-400a2b553511)

**Comment by wojiushixiaobai** [comment]
请通过下面的方式修改
```sh
vi /opt/jumpserver/config/config.txt
```
```vim
...

## Nginx 配置
HTTP_PORT=80

## HTTPS 配置
HTTPS_PORT=443               # 对外 https 端口, 默认 443
SERVER_NAME=www.domain.com   # 你的 https 域名
SSL_CERTIFICATE=xxx.pem      # /opt/jumpserver/config/nginx/cert 目录下你的证书文件
SSL_CERTIFICATE_KEY=xxx.key  # /opt/jumpserver/config/nginx/cert 目录下你的 key 文件
```
注意：不要填绝对路径，使用相对路径即可。`Docker` 会将证书文件映射到容器里面

**Comment by angel20009123** [comment]
![1727250018618](https://github.com/user-attachments/assets/1b04c868-9828-4c57-b9d9-af6f2c97d3b4)
![1727250044735](https://github.com/user-attachments/assets/bd945dcc-559c-494f-80e5-58ad346574c2)
证书没改过来，咋搞搞

**Comment by wojiushixiaobai** [comment]
改完后重启 JumpServer
```sh
./jmsctl.sh restart
```

**Comment by wojiushixiaobai** [comment]
docker 会自己管理 iptables 规则，不需要动
