### ISSUE TITLE
[Feature] 设置连接Windows资产使用客户端方式登录

### ISSUE THREAD

**Issue by shibosen** [jumpserver/jumpserver#14221]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

如何设置登录Windows资产通过客户端方式，目前只找到了linux类型资产的设置方式
<img width="783" alt="image" src="https://github.com/user-attachments/assets/a5f2bbd8-80e4-4489-ba35-8f2a730ad2ce">
<img width="740" alt="image" src="https://github.com/user-attachments/assets/a803dcf1-069a-4b02-81aa-6db357061875">
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/e0b1a287-be2a-41a5-ab21-8ba433730d7e">

### 解决方案

设置Windows资产的采用客户端登录

**Comment by BaiJiangJie** [comment]
RDP 的客户端连接方式是企业版功能。
