### ISSUE TITLE
v4.2.0 版本会修复。

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#14229]
v4.2.0 版本会修复。

_Originally posted by @BaiJiangJie in https://github.com/jumpserver/jumpserver/issues/14078#issuecomment-2328425651_
            

升级道4.2后测试并没有修复。

**Comment by wojiushixiaobai** [comment]
没复现，清理掉浏览器缓存后再试试。
可以通过 https://demo.jumpserver.org 进行验证
