### ISSUE TITLE
[Bug] ValueError: Unknown level: 'ERRO'

### ISSUE THREAD

**Issue by THZ34** [jumpserver/jumpserver#14228]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu : 22.04
docker : 26.1.3

### 🐛 Bug Description

bash install_jumpserver.sh
download install script to /opt/jumpserver-installer-v4.1.0

>>> 安装配置 JumpServer
1. 配置加密密钥
完成

2. 配置持久化目录
是否需要自订持久化储存的路径？不自订将使用默认目录 /data/service/jumpserver/storage? (y/n)  (默认为 n): 完成

3. 配置数据库
是否使用外部 MySQL? (y/n)  (默认为 n): 完成

4. 配置 Redis
请输入 Redis 模式? (redis/sentinel)  (默认为 redis): 是否使用外部 Redis? (y/n)  (默认为 n): 完成

5. 配置外部访问
是否需要配置 JumpServer 对外访问端口? (y/n)  (默认为 n): 完成

6. 初始化数据库
WARN[0000] Found orphan containers ([jms_lion jms_chen jms_web jms_celery jms_koko]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 3/3
 ✔ Container jms_mysql  Running                                                                                                                                            0.0s
 ✔ Container jms_core   Started                                                                                                                                          799.7s
 ✔ Container jms_redis  Running                                                                                                                                            0.0s
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/config.py", line 627, in configure
    self.configure_logger(name, loggers[name])
  File "/usr/local/lib/python3.11/logging/config.py", line 808, in configure_logger
    self.common_logger_config(logger, config, incremental)
  File "/usr/local/lib/python3.11/logging/config.py", line 793, in common_logger_config
    logger.setLevel(logging._checkLevel(level))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 207, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'ERRO'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/py3/lib/python3.11/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.11/logging/config.py", line 629, in configure
    raise ValueError('Unable to configure logger '
ValueError: Unable to configure logger 'django'
[ERROR] 表结构变更失败!
[+] Running 6/8
[+] Running 6/8s_koko    Recreated                                                                                                                                       310.9s
 ✔ Container jms_koko    Recreated                                                                                                                                       310.9s
 ✔ Container jms_web     Recreated                                                                                                                                       198.8s
 ✔ Container jms_redis   Running                                                                                                                                           0.0s
 ✔ Container jms_mysql   Running                                                                                                                                           0.0s
 ✔ Container jms_lion    Recreated                                                                                                                                       427.8s
 ⠦ Container jms_core    Recreate                                                                                                                                        960.6s
 ⠦ Container jms_celery  Recreate                                                                                                                                        960.6s
 ✔ Container jms_chen    Recreated                                                                                                                                       349.5s
canceled

### Recurrence Steps

bash install_jumpserver.sh  # v4.1.0

**Comment by wojiushixiaobai** [comment]
修修正配置文件 `LOG_LEVEL` 
```sh
LOG_LEVEL=ERROR
```
报错是因为你写的是 `ERRO` 需要更正成 `ERROR`

**Comment by THZ34** [comment]
> 修修正配置文件 `LOG_LEVEL`
> 
> ```shell
> LOG_LEVEL=ERROR
> ```
> 
> 报错是因为你写的是 `ERRO` 需要更正成 `ERROR`

我用的是一键安装脚本，既没有改过LOG_LEVEL，也不知道配置文件在哪。
但是把本地镜像清除重新下载就可以运行了。
