### ISSUE TITLE
helm 安装了jumpserver，默认账号密码是什么，使用admin提示不对

### ISSUE THREAD

**Issue by dxg0716** [jumpserver/jumpserver#14224]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

1、Kubernetes 1.25
2、jumpserver 4.1.0
 

### 🤔 问题描述

第一次通过helm安装了jumpserver，使用默认admin/admin登录 提示用户名或密码不对

### 期望结果

请问helm安装的jumpserver账号密码是什么

**Comment by wojiushixiaobai** [comment]
![image](https://github.com/user-attachments/assets/935c37a1-aacd-45ac-8307-16f4fd945332)
```
用户名: admin
密码: ChangeMe
```
