### ISSUE TITLE
[企业微信工单审批-可在浏览器关闭状态下，免登陆审批工单] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14227]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

浏览器关闭状态下，在企业微信内，点直接批准，会跳转到浏览器登录页面，重新企业微信扫码登录，才能审批。

### 解决方案

企业微信内，在浏览器未登录堡垒机的情况下，可直接审批工单。

可以参考其他应用，应用主页把appid参数都传过去，可自动跳转登录页面，无需重复扫码登录
![企业微信截图_17261960433436](https://github.com/user-attachments/assets/d298df09-1f5f-406e-9b30-0ddd888db376)

**Comment by BaiJiangJie** [comment]
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/117c6c2d-307c-49ae-b758-efb9d611604f">

开启配置。

**Comment by yuanxixue** [comment]
开启这个不太安全，拿到链接的用户都能审批，有没有更安全的方法

**Comment by BaiJiangJie** [comment]
没有了。

**Comment by yuanxixue** [comment]
后期会优化吗，可以参考我上面的解决方案，在应用主页把appid参数都传过去，可实现

**Comment by BaiJiangJie** [comment]
@O-Jiangweidong
在所有消息通知方式中，有没有通用的方案，能够更安全一些？
