### ISSUE TITLE
【两个安全问题】SECRET_KEY硬编码 和 登陆验证码绕过爆破

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#1422]
[简述你的问题]

##### 使用版本
1.3.0

#####  参考: https://stackoverflow.com/questions/15170637/effects-of-changing-djangos-secret-key/15383766#15383766

![image](https://user-images.githubusercontent.com/11460661/41274013-68317270-6e4e-11e8-90ec-49c07a895d4a.png)

### 2.  验证码绕过爆破.
![image](https://user-images.githubusercontent.com/11460661/41275372-4e0cbbe8-6e53-11e8-8b9a-347289463a45.png)

#####  登陆验证码是否出现是根据ip生成的cache进行判断的, get_login_ip的判断过于简单, 可以通过伪造X-FORWARDED-FOR来绕过验证码进行爆破.
![image](https://user-images.githubusercontent.com/11460661/41326688-b9b71db2-6ef2-11e8-9485-23ccc7ac644f.png)
![image](https://user-images.githubusercontent.com/11460661/41326263-d87b404a-6ef0-11e8-98e1-d3079207e278.png)
![image](https://user-images.githubusercontent.com/11460661/41326697-cbbcee60-6ef2-11e8-9bbb-cd5dcd4dab93.png)

![image](https://user-images.githubusercontent.com/11460661/41326298-f1feaf02-6ef0-11e8-94a5-0df07de6e707.png)

##### 建议：
- 增加其他因子组合识别
- 提示用户在使用了代理节点的情况下, 在自己信任的入口(SLB,或者NGINX)覆盖掉X-FORWARDED-FOR
- 增加配置选项, 1. 代理层数设置, 如果为0则忽略 , 根据层数倒序获取真实ip 例如2层  x_forwarded_for[-2]
##### 其他

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
#1428

**Comment by jokimina** [comment]
@ibuler 更新了验证过程, 希望能关注下

**Comment by ibuler** [comment]
SECRET_KEY的问题是需要注意一下，但是需要在使用上做个平衡，怎么让用户去设置SECRET_KEY

**Comment by ibuler** [comment]
验证码的确实有问题，不行就再加上用户名进行cache，输入过一次错的，下次就强制验证码

**Comment by jokimina** [comment]
直接用户名cache不太好, 有个折中方式:
增加代理层数设置,  默认1(大多数情况都只有一层)
如果为0则忽略直接取remote_addr , 大于1则根据层数倒序获取真实ip 例如2层 x_forwarded_for[-2]. 同时也需要校验下ip的有效性. 这样比较稳妥. 觉得可以的话 晚上我提一个pr

**Comment by ibuler** [comment]
这个策略需要有代理层数的设置，这个不太好处理， 最后一个nginx带上proxy的层数？

**Comment by ibuler** [comment]
已处理，不再默认SECRET_KEY
