### ISSUE TITLE
[Bug] Mac win10 清除缓存之后，首次登录提示用户名和密码认证失败，再次登录即可成功

### ISSUE THREAD

**Issue by gaohonghai** [jumpserver/jumpserver#14222]
### 产品版本

V3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

已经是成交客户，几个运维分别在 win10 和 mac 上有反馈清除缓存之后，首次登录提示用户密码不对。

### 🐛 缺陷描述

复现步骤已录制视频，有劳参考视频
[iShot_2024-09-23_16.23.22.mp4.zip](https://github.com/user-attachments/files/17097245/iShot_2024-09-23_16.23.22.mp4.zip)

### 复现步骤

[iShot_2024-09-23_16.23.22.mp4.zip](https://github.com/user-attachments/files/17097270/iShot_2024-09-23_16.23.22.mp4.zip)

**Comment by BaiJiangJie** [comment]
v4 中复现后直接提给 @jym503558564 .
