### ISSUE TITLE
使用helm 部署jumpserver，无法使用ssh的方式登录堡垒机

### ISSUE THREAD

**Issue by dxg0716** [jumpserver/jumpserver#14231]
### Product Version

V4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

k8s 1.25
jumpserver v4.2.0

### 🐛 Bug Description

使用helm安装了jumpserver，只通过ingress暴露了80端口，但是没有暴露ssh登录的2222端口，这个怎么实现

### Recurrence Steps

只要是helm安装的就可以复现

**Comment by wangzhishang02** [comment]
把你的2222暴露出来，ingress或者NodePort方式

**Comment by dxg0716** [comment]
> 把你的2222暴露出来，ingress或者NodePort方式

ingress-nginx 是不是得使用4层tcp暴露呢，这种方式https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

**Comment by dxg0716** [comment]
> > 把你的2222暴露出来，ingress或者NodePort方式
> > @wangzhishang02
> > ingress-nginx 是不是得使用4层tcp暴露呢，这种方式https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

@wangzhishang02 按照这个配置了，现在可以命令行登录jumpserver了，想问题下5000端口需要暴露吗？

**Comment by wangzhishang02** [comment]
5000不用
所暴露端口的功能关系列表可以参考：https://docs.jumpserver.org/zh/v3/installation/network_port/

**Comment by dxg0716** [comment]
好的
