### ISSUE TITLE
[Feature] 管理员能管理其他账号的作业中心

### ISSUE THREAD

**Issue by dimsumc** [jumpserver/jumpserver#14237]
### 产品版本

v3.10.5

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

目前作业中心内的作业只能由该账号自行管理, 希望可以提供让系统管理员或其他有权限的账号管理作业中心内的作业. 

### 解决方案

例如员工 A 在作业中心建立了每天清除系统日志的作业, 目前哪怕是系统管理员也没办法更改, 只能查看日志. 
希望可以让系统管理员或给予权限让别的账号修改作业

**Comment by BaiJiangJie** [comment]
为什么需要让系统管理员来修改作业？

**Comment by dimsumc** [comment]
> 为什么需要让系统管理员来修改作业？

目前有一个情景是.. 员工休假的时候, 作业出问题, 需要去修改/停止. 又或者想套用该作业到别的机器上

另一方面现在作业分散了各账号内, 比较不好直观有什么作业在跑, 必须在日志里面分析有哪些作业在跑然后再找对应的员工更改.

**Comment by BaiJiangJie** [comment]
总结一下，是下面两个需求：
1. 管理员，可以查看、修改、停止用户的定时作业
2. 作业可以共享

第2个需求，v4.2 可以共享查看，v4.3 不仅支持查看，还允许用户创建副本，自己使用。

第1个需求，可以考虑一下。

**Comment by dimsumc** [comment]
> 总结一下，是下面两个需求：
> 
> 1. 管理员，可以查看、修改、停止用户的定时作业
> 2. 作业可以共享
> 
> 第2个需求，v4.2 可以共享查看，v4.3 不仅支持查看，还允许用户创建副本，自己使用。
> 
> 第1个需求，可以考虑一下。

4.2 这边好像只是支援模版 template 的共享, 而不是作业本身? 
Job Center's Playbook and Adhoc templates now support setting a public visibility scope, allowing all users to view them.

**Comment by BaiJiangJie** [comment]
嗯，作业不能共享。因为作业包含有权限的资产，只能共享模版。

**Comment by dimsumc** [comment]
嗯... 那看看有没有可能用权限方式去共享作业... 或者最少让管理员可以查看/修改所有用户的作业

**Comment by BaiJiangJie** [comment]
可以考虑，让管理员查看和停止用户作业，其他操作不能放开给管理员。

**Comment by stevenxu333** [comment]
@BaiJiangJie 你好，V3版本是否可以支持作业模版共享查看和根据模版创建用户自己作业或快捷命令？

另外V3和V4版新功能开发什么关系？新的feature是否同时在V3和V4添加? 
是否建议长期使用V3 lts版本？

**Comment by BaiJiangJie** [comment]
v3 不支持了，所有新功能都会在 v4 上搞。

v3 版本只修复严重 Bug，如果计划长期使用，推荐使用 v4 版本。

**Comment by BaiJiangJie** [comment]
v4.4.0 管理员管理用户作业任务已上线。
