### ISSUE TITLE
[Bug] 资产树拖拉拽功能不为预期效果

### ISSUE THREAD

**Issue by Ewall555** [jumpserver/jumpserver#14239]
### 产品版本

v3,v4

### 版本类型

- [X] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [X] All-in-One
- [X] 1Panel
- [X] Kubernetes
- [X] 源码安装

### 环境信息

通用环境

### 🐛 缺陷描述

1. 资产授权中的资产树，拖拉拽报错“common.updateErrorMsg AxiosError: Request failed with status code 404”
2. 任意树，节点旁数量显示问题
3. 任意树，任意节点移动至根节点的显示问题
4. 全局组织中的任意树，移动节点导致的跨组织问题（注：全局组织下上是无法右键的，但是拖拉拽没有被限制）

### 复现步骤

1. 按缺陷描述操作稳定复现
2. 有两个节点分别有1个资产，将节点1拖进节点2，此时节点旁数量显示(2),将节点2拖出原位置，数量显示将保持不变（刷新缓存等操作无效，永远生效）
3. 任意节点移动至根节点会导致和根节点同级，刷新后恢复，仅显示问题
4. 全局组织的任意树，移动节点将导致跨组织权限问题，显示权限等将会出现问题

### 期望结果

1. 待讨论期望结果，是否能移动某条授权所在节点的位置，假设可以移动且移动了，节点授权规则应该如何分配
2. 正确显示数量，且数量显示总是会慢，但列表显示总是立即的，需要立即反应数量
3. 显示正常
4. 待讨论期望结果，跨组织的资产或节点是否可以移动，假设可以移动且移动了，节点或资产所对应的其它内容（如账号，授权）是否一并移动，假设不可以移动，跨组织的资产如何迁移资产

**Comment by BaiJiangJie** [comment]
v4.2 版本，全局组织下节点不允许拖动。
