### ISSUE TITLE
[Question] 远程应用发布机部署报错

### ISSUE THREAD

**Issue by angel20009123** [jumpserver/jumpserver#14238]
### 产品版本

3.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

![image](https://github.com/user-attachments/assets/73f06e70-708b-457d-8010-8d2cb4bfb78a)

### 🤔 问题描述

![image](https://github.com/user-attachments/assets/e254d658-81ac-40ed-bcf6-4c8fdf1d023c)

**Comment by BaiJiangJie** [comment]
参考：https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665

主要关注：
![image](https://github.com/user-attachments/assets/07aac538-13d1-49bb-98be-5d6307f311ec)
