### ISSUE TITLE
jumpserver在线会话无法断开

### ISSUE THREAD

**Issue by sz233** [jumpserver/jumpserver#1423]
[简述你的问题]
jumpserver上的会话在断开终端后也会一直保持，只能手动在web界面中断会话，服务器上可以看到tcp连接数一直在增加，这个策略比较影响性能。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
v1.3.1
##### 具体表现[截图可能会更好些,最好能截全]
jumpserver服务器截图，部分连接
![image](https://user-images.githubusercontent.com/30258956/41274414-da7fe90a-6e4f-11e8-85f5-3987024b768a.png)

web控制台的截图
![image](https://user-images.githubusercontent.com/30258956/41274128-e659ef38-6e4e-11e8-8a38-bba42c30724c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不应该啊，已经做了优化，连接断开后会断开用户连接的

**Comment by bruce-zu** [comment]
我的也有该问题，所有连接有会话都没有自动断开。

**Comment by bruce-zu** [comment]
我的是1.0版本

**Comment by wojiushixiaobai** [comment]
@bruce-zu 更新到最新版本，看更新文档[http://docs.jumpserver.org/zh/docs/upgrade.html](url)

**Comment by bruce-zu** [comment]
@wojiushixiaobai 更新到那个版本

**Comment by opstrip** [comment]
我的是1.3.3的版本，在线会话不自动断开的问题还在。22号查看15号的会话还在，积累到现在有288个会话了，超级卡。
<img width="1421" alt="111" src="https://user-images.githubusercontent.com/14342611/44451672-00134b80-a627-11e8-9e3d-22a380c4db97.png">

**Comment by opstrip** [comment]
然而这个“在线会话”手动结束不掉的，目前是凌晨定时任务重启跳板机服务来清理掉的。请问下各位大佬有没有提供手动清理已经断开的在线会话的命令什么的？
