### ISSUE TITLE
jumpserver sftp 报错400

### ISSUE THREAD

**Issue by dxg0716** [jumpserver/jumpserver#14234]
### Product Version

V4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

1、jumpserver v4.2.0
2、kubernetes 1.25

### 🤔 Question Description

jumpserver web sftp登录返回400
![WechatIMG1](https://github.com/user-attachments/assets/a3400bc7-a6db-4f61-8286-92d09f278b6d)

### Expected Behavior

可以正常sftp登录

**Comment by dxg0716** [comment]
https://github.com/jumpserver/jumpserver/issues/3886 是不是跟这个issue一样的问题呢，我这边koko是2个pod，在不同节点，我这边使用了redis sentinel

**Comment by dxg0716** [comment]
我把koko pod副本改为1个之后sftp功能可以使用了，应该是跟koko副本数有关系的，我看可能是跟会话监控和共享变量有关系，但是我已经是redis了
![WechatIMG2956](https://github.com/user-attachments/assets/caca42c6-db63-4959-8846-75756ea11e2c)

**Comment by BaiJiangJie** [comment]
跟 https://github.com/jumpserver/jumpserver/issues/14214 类似。

**Comment by dxg0716** [comment]
> 跟 #14214 类似。

@BaiJiangJie 如果是这样的话，那我使用的是云厂商的负载均衡（clb），并且jumpserver部署在k8s里面，clb调度算法需要使用源地址哈希（SH）并且koko svc需要将internalTrafficPolicy改为Local了？

**Comment by dxg0716** [comment]
> > 跟 #14214 类似。
> 
> @BaiJiangJie 如果是这样的话，那我使用的是云厂商的负载均衡（clb），并且jumpserver部署在k8s里面，clb调度算法需要使用源地址哈希（SH）并且koko svc需要将internalTrafficPolicy改为Local了？

我按照这个配置了下，并不好使

**Comment by BaiJiangJie** [comment]
这是规则：
保证一个资产会话，多次访问都能分发到同一个 koko 中。
