### ISSUE TITLE
[Bug] 文件传输中的审计文件无法下载

### ISSUE THREAD

**Issue by daviadong** [jumpserver/jumpserver#14240]
### 产品版本

3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

下载安装包安装的3.10.13版本

### 🐛 缺陷描述

审计台里面的会话审计-文件传输中的审计文件呈现灰色，无法点击下载，显示“当前动作不记录文件，或者文件大小超过阈值（默认100M），或者还未保存到对应存储中”，但文件并未到100M，只是个简单的txt文件，是需要配置存储到什么位置内。

### 复现步骤

通过rz命令和SFTP网页端上传到linux机器中的2个txt文件，大小为4K，在审计台里面的会话审计-文件传输中可以看到审计记录，但文件无法下载，提示：当前动作不记录文件，或者文件大小超过阈值（默认100M），或者还未保存到对应存储中。
文件在系统中也并没有删除。

<img width="844" alt="截屏2024-09-26 下午3 00 10" src="https://github.com/user-attachments/assets/60b8991f-4b1a-498e-aa00-d5e4c92341be">

**Comment by BaiJiangJie** [comment]
提示信息有问题，以前是默认 100M，后来默认关闭了。

修改 config.txt 配置文件：

__备注：FTP 文件上传下载备份阈值，单位(M)，当值小于等于0时，不备份__
`FTP_FILE_MAX_STORE=100`
只保存 100M 以内的文件，

配置好后，重启服务，再测试传输和下载。

**Comment by BaiJiangJie** [comment]
文案信息优化在 v4.3.0 中会实现。
