### ISSUE TITLE
[Bug] nginx error log不停地刷

### ISSUE THREAD

**Issue by nanoguo** [jumpserver/jumpserver#14246]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Ubuntu 24.04， docker一键安装

### 🐛 缺陷描述

nginx的错误日志不停地在刷同一个请求
2024/09/29 11:27:34 [error] 37#37: *2772 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.xx.xx, server: , request: "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1", upstream: "http://[::1]:51980/api/v1/users/profile/?fields_size=mini", host: "10.xx.xx.xx", referrer: "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002"
2024/09/29 11:27:34 [warn] 37#37: *2772 upstream server temporarily disabled while connecting to upstream, client: 10.10.xx.xx, server: , request: "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1", upstream: "http://[::1]:51980/api/v1/users/profile/?fields_size=mini", host: "10.xx.xx.xx", referrer: "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002"

### 复现步骤

查看nginx error log

### 补充信息

不知道这个请求是哪里发出做什么的，查看历史issue发现类似的在旧版本被修复，https://github.com/jumpserver/jumpserver/issues/12190

**Comment by BaiJiangJie** [comment]
这个日志是正常的，有用户打开 Luna 页面时，会定时检测用户的在线状态。

**Comment by nanoguo** [comment]
为啥是拒绝连接呀

**Comment by BaiJiangJie** [comment]
用户过期了就会显示拒绝，你看 core 的日志，应该有 403

**Comment by nanoguo** [comment]
core 的日志没有403，倒是nginx的access log中有大量的401，请求就是error log中的:

127.0.0.1 - - [29/Sep/2024:15:46:17 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1" 401 70 "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "10.10.40.34"
10.xx.xx.xx2 - - [29/Sep/2024:15:46:17 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1" 401 70 "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"
127.0.0.1 - - [29/Sep/2024:15:46:22 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1" 401 70 "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "10.10.40.34"
10.xx.xx.xx2 - - [29/Sep/2024:15:46:22 +0800] "GET /api/v1/users/profile/?fields_size=mini HTTP/1.1" 401 70 "http://10.xx.xx.xx/luna/?_=1727243070616&oid=00000000-0000-0000-0000-000000000002" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" "-"

**Comment by BaiJiangJie** [comment]
对，是 401 的状态码，没问题。
