### ISSUE TITLE
[Bug] 1Panel 不支持使用 aarch64 架构，只支持 x86_64

### ISSUE THREAD

**Issue by kattocloud** [jumpserver/jumpserver#14244]
### 产品版本

4.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

System: debian-12.7 [aarch64]
CPU: [ "Neoverse-N1 4 Virtual Core" ]
Disk: 24.03G/146.09G
RAM: 8.8G/23.44G

**Oracle ARM Server** 

### 🐛 缺陷描述

stderr: jumpserver Pulling no matching manifest for linux/arm64/v8 in the manifest list entries

之前安装一直不存在问题，不知道是1Panel的问题，还是jumpserver的问题，无法安装，安装就报此错误

### 复现步骤

stderr: jumpserver Pulling no matching manifest for linux/arm64/v8 in the manifest list entries

之前安装一直不存在问题，不知道是1Panel的问题，还是jumpserver的问题，无法安装，安装就报此错误

### 期望结果

重新支持 Oracle ARM 服务器

**Comment by BaiJiangJie** [comment]
1Panel 不支持使用 aarch64 架构，只支持 x86_64。

**Comment by wojiushixiaobai** [comment]
v4 之前的版本支持 arm64 架构，v4 开始不再支持 arm64 架构

**Comment by BaiJiangJie** [comment]
计划在 v4.4 版本的 All-in-One 中重新支持一下 ARM 架构。

@kattocloud
