### ISSUE TITLE
windows 文件传输

### ISSUE THREAD

**Issue by gian2008** [jumpserver/jumpserver#1424]
[简述你的问题]

##### 使用版本
1.3.1-1

##### 问题复现步骤
1. 上传压缩文件出现：“You do not have permission to upload this file. If you require access, please check your system settings, or check with your system administrator.”
   这个该如何解决？

##### 其他

[注:] 完成后请关闭 issue

**Comment by gian2008** [comment]
`该怎样传输压缩文件及一些工具

**Comment by jokimina** [comment]
错误不是写了么 没权限...

**Comment by gian2008** [comment]
正常传文件，怎么就没权限了，并且只能传单个文档，也不能传文件夹

**Comment by wojiushixiaobai** [comment]
不能传文件夹。等待后续功能更新

**Comment by gian2008** [comment]
已经解决，是需要在nginx里修改文件传输大小，有同样问题者可以百度下nginx修改传输文件大小
