### ISSUE TITLE
[Bug] Postgresql WebUI 无法读取任意数据库下schema包含下划线的表

### ISSUE THREAD

**Issue by wujunyi792** [jumpserver/jumpserver#14245]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

裸机一件部署、外部pg、本地redis

### 🐛 缺陷描述

在使用WebUI操作pg数据的时候，可以读取到不同database下schema名字不包含`-`的所有表的数据，如果名称包含`-`，则无法读取任何数据，日志显示如图，没有报错
![image](https://github.com/user-attachments/assets/4e0b1a61-3172-4ae3-980b-7dabbbf379c7)

正常应该是这样：
![image](https://github.com/user-attachments/assets/cda735e4-a192-4efa-8e00-e651f3fd8fd9)

![image](https://github.com/user-attachments/assets/d3d4758a-7e5b-40ee-b5fb-a075e0e6c1c1)

### 复现步骤

1. 准备一个pg，随便建一个数据库
2. 在数据库里新建两个schema，一个包含`-`，一个不包含，加入一些测试数据
3. 使用webui连接pg数据库，尝试访问数据

### 期望结果

应该能看见两个schema下所有table的数据

**Comment by BaiJiangJie** [comment]
现在按钮操作查询数据库有问题。

手动输入查询命令时用双引号包裹一下，如：

`select * from "my-schema"."my-table" limit 10;`

**Comment by wujunyi792** [comment]
希望尽快修复！社区版jumpserver的pg不能client直连，web ui也有一些问题，导致目前pg数据查询不太可用。

**Comment by BaiJiangJie** [comment]
表名中包含中横线 `-` 不能直接查询的问题，计划 v4.3 修复。

**Comment by jym503558564** [comment]
v4.3.0 已修复，并发布，请升级进行体验。
