### ISSUE TITLE
[Bug] 收起左侧导航栏后，提示框位置错误

### ISSUE THREAD

**Issue by FiendFEARing** [jumpserver/jumpserver#14247]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

CentOS8单机部署

### 🐛 缺陷描述

收起左侧导航栏后，提示框位置错误
![msedge_TcBo4sJVNX](https://github.com/user-attachments/assets/a8c53859-a5b1-49fc-b013-1ed8ec67d8e6)

### 复现步骤

1、使用无痕模式访问jumpserver主页。
2、在有左侧导航栏的页面上，点击左下角收起导航栏。
3、鼠标移动到任一选项上均会复现。

### 期望结果

![image](https://github.com/user-attachments/assets/a36944f6-a269-463c-a91f-9d54c52394ec)

**Comment by BaiJiangJie** [comment]
确实有问题，下个版本优化一下。

**Comment by jym503558564** [comment]
v4.3.0 已修复，并发布，请升级进行体验。
