### ISSUE TITLE
[Bug]  重启容器会删除持久化数据

### ISSUE THREAD

**Issue by CooperWanng** [jumpserver/jumpserver#14254]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker

### 🐛 缺陷描述

每次重启容器，会将持久化数据删除，比如录像，日志等

### 复现步骤

重启容器

**Comment by wojiushixiaobai** [comment]
新版本修改了持久化的目录规则，参考 https://github.com/jumpserver/Dockerfile/blob/master/allinone/entrypoint.sh#L29

**Comment by casualfish** [comment]
https://github.com/jumpserver/jumpserver/issues/14211#issuecomment-2376601395 可以参考这个
