### ISSUE TITLE
[Feature] 希望控制台首页可以显示当前服务器的资源占用情况（CPU/RAM/硬盘等）

### ISSUE THREAD

**Issue by wqinf** [jumpserver/jumpserver#14250]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

希望控制台首页可以显示当前服务器的资源占用情况（CPU/RAM/硬盘等）

### 解决方案

控制台首页增加显示当前服务器的资源占用情况（CPU/RAM/硬盘等），以便直观的查阅，并在资源占用较高时能及时进行优化或升级。

**Comment by BaiJiangJie** [comment]
组件管理中各组件都有所在服务器的资源占用情况，还有告警通知。
如果在首页中显示，多节点的情况下，也不太好全部显示出来。

**Comment by wqinf** [comment]
> 组件管理中各组件都有所在服务器的资源占用情况，还有告警通知。 如果在首页中显示，多节点的情况下，也不太好全部显示出来。

是否可以考虑单节点部署的时候显示，若是多节点则只显示主节点的负载情况？

**Comment by BaiJiangJie** [comment]
暂时不考虑。

**Comment by wqinf** [comment]
> 暂时不考虑。

好的。
