### ISSUE TITLE
怎么把系统用户的权限修改为不输入密码sudo root权限

### ISSUE THREAD

**Issue by snowkity2005** [jumpserver/jumpserver#1425]
[简述你的问题]

##### 使用版本
Version 1.3.0-2 GPLv2

##### 问题复现步骤
请问怎么把系统用户的权限修改为:ALL=(ALL) NOPASSWD: ALL，就是把被管理主机的visudoers文件中加入ALL=(ALL) NOPASSWD: ALL
<img width="982" alt="2018-06-12 5 36 00" src="https://user-images.githubusercontent.com/37360601/41282610-1b98e7a4-6e67-11e8-9d0f-2f00bd4d31b2.png">

[注:] 完成后请关闭 issue

**Comment by sz233** [comment]
创建系统用户时把sudo改成ALL
![image](https://user-images.githubusercontent.com/30258956/41285630-62a6b916-6e6f-11e8-9373-7c5773b21521.png)

**Comment by jokimina** [comment]
就是ALL, 刚才试了下是可以的.  不行的话手动推送下系统用户
不过不建议你把系统用户权限弄这么高
