### ISSUE TITLE
Install permission denied[Bug] 

### ISSUE THREAD

**Issue by VincentKlanderman** [jumpserver/jumpserver#14255]
### Product Version

latest

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

fresh ubuntu server install

### 🐛 Bug Description

getting the following error when trying to install:
![image](https://github.com/user-attachments/assets/c6af02b9-cde6-4f5c-83e5-8e0b6d773082)

### Recurrence Steps

trying to install again.

### Expected Behavior

expecting it install

### Additional Information

N/A

### Attempted Solutions

tried running it as the root user and still getting access denied

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/jumpserver/issues/14256
Please use the root account to re-execute the installation script.

**Comment by VincentKlanderman** [comment]
That worked
