### ISSUE TITLE
[Feature] 强烈建议个人偏好设置可以设置工作台资产列表点击连接按钮之后可以直接全屏打开

### ISSUE THREAD

**Issue by wqinf** [jumpserver/jumpserver#14252]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

强烈建议个人偏好设置可以设置工作台资产列表点击连接按钮之后可以直接全屏打开（新窗口的模式），目前如果要全屏打开，需要这样做：
方案一：连接任意一台资产，进入到包含资产树的界面右键，然后选择新窗口打开
方案二：在个人账号偏好设置连接默认打开方式为“新窗口”，但是还是得进入到包含资产树的界面右键，然后点击资产才能在新窗口打开，此时资产树的界面会弹出提示当前页面连接已中断，还得再确认一下，体验非常的不好。
![QQ20240930-090825](https://github.com/user-attachments/assets/8a5f99bc-ebd1-43f3-9af7-96b0bd242d8d)

因为资产树页面的左侧和顶部的工具栏都会挤占一定的空间，让可操作区域明显变小，在全屏页面（新窗口的模式）的可操作性更强，因此，如果可以设置在工作台资产列表点击连接按钮之后可以直接全屏打开（新窗口的模式），那么就可以少几步操作，这样的体验会更友好，请再次考虑一下，谢谢。

### 解决方案

将偏好设置中的连接默认打开方式中的“新窗口”，逻辑调整为工作台资产列表点击连接按钮之后直接全屏打开（新窗口的模式），而不是先跳转到资产树页面之后再点击一次才行，尽可能让用户减少操作。

或者不改变现有逻辑，另外提供一种可以直接实现的方式，谢谢。

**Comment by BaiJiangJie** [comment]
v4.3.0 考虑根据个人偏好设置来控制。

**Comment by wqinf** [comment]
> v4.3.0 考虑根据个人偏好设置来控制。

非常期待。

**Comment by jym503558564** [comment]
v4.3.0 已优化，并发布，请升级进行体验。

**Comment by wqinf** [comment]
> v4.3.0 已优化，并发布，请升级进行体验。

已更新验证，非常感谢！
