### ISSUE TITLE
[Bug] bash quick_start.sh Permission denied

### ISSUE THREAD

**Issue by edgeunizyx** [jumpserver/jumpserver#14256]
### Product Version

4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

### 🐛 Bug Description
bash quick_start.sh出現以下錯誤：
![image](https://github.com/user-attachments/assets/116009e6-d81e-47ff-95dd-be08e65c5ae3)

### Recurrence Steps

無法開啟https://resource.fit2cloud.com網站
![image](https://github.com/user-attachments/assets/2dcb56a5-b527-4f79-8b09-73d53b18a10c)

**Comment by wojiushixiaobai** [comment]
提示是权限不够，请使用 **root** 账户执行

**Comment by edgeunizyx** [comment]
更換成root執行後仍是會失敗
![image](https://github.com/user-attachments/assets/629d95d5-58b5-4d72-9a83-9bae18b61a93)
