### ISSUE TITLE
[Feature] CONNECTION_TOKEN_EXPIRATION 支持在向导页面自定义 token 过期时间

### ISSUE THREAD

**Issue by RedCG** [jumpserver/jumpserver#14251]
### 产品版本

V3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

资产向导连接功能补充了开启复用功能之后，管理员开放临时链接给临时用户变的非常可控，给你们点赞。

场景问题：不过目前 JumpServer 临时链接的过期时间是写死在后台的配置文件的，每个资产的连接都是只能固定的过期时间，无法根据不同的临时用户操作资产的需求进行开放。

### 解决方案

这一点有没有可能可以让我们用户支持在向导页面上自定义时间呢，这样将极大提升我们运维跟研发、测试的安全协同效率，相信 JumpServer 在资产连接的灵活性也会更强。

**Comment by BaiJiangJie** [comment]
目前没有考虑，如果让用户来控制，复用时间可能会很长。
