### ISSUE TITLE
Passwords are stored plain text in logs [Bug] 

### ISSUE THREAD

**Issue by TheKourosh** [jumpserver/jumpserver#14257]
### Product Version

3.10.13

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Operating System: Ubuntu 20.04
Shell: Bash

### 🐛 Bug Description

The issue occurs when users are connected to a Linux system via JumpServer (using SSH key authentication), and then need to input passwords within the session for specific commands. For example:

    When switching to a root user using the su - command, the root password is logged in cleartext within the session logs.
    When connecting to a database using mysql -u root -p, the password entered is also logged in cleartext.

This poses a significant security risk, as sensitive information such as passwords should not be captured or logged in plain text within session logs.

### Recurrence Steps

Log into JumpServer.
Use SSH key-based authentication to connect to a Linux system.
Once connected, run a command that prompts for a password, such as:

    su - (to switch to root)

Enter the password when prompted.
Review the session logs in JumpServer and observe that the entered password is logged in cleartext.

### Expected Behavior

Password inputs, such as those for su - or mysql -u root -p, should not be captured or stored in cleartext within JumpServer session logs. Password fields should be masked or excluded from logs entirely to protect sensitive information.

**Comment by BaiJiangJie** [comment]
You’re right, it shouldn’t be recorded, but we don’t have a better way to handle it at the moment. We will look into it.

**Comment by LeeEirc** [comment]
we will sovle it in v3.10.13 or v4.3.0 above, you can add new configuraion to control the behavior of the command record.

```bash
# config.txt in /opt/jumpserver/config/config.txt
DISABLE_INPUT_AS_COMMAND=true
```

**Comment by BaiJiangJie** [comment]
v4.3.0 Released.
