### ISSUE TITLE
[Bug] 因为web终端中的vim异常，从v4.1.0升级到v4.2.0，升级之后web终端中无法使用快捷键复制终端中的字符。

### ISSUE THREAD

**Issue by anjianghua** [jumpserver/jumpserver#14260]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

MacBook Pro 14''
macOS 14.3
Safari浏览器 版本17.3 (19617.2.4.11.8)

### 🐛 缺陷描述

因为web终端中的vim异常，从v4.1.0升级到v4.2.0，升级之后web终端中无法使用快捷键(Command + C)复制终端中的字符。

### 复现步骤

能稳定复现

**Comment by BaiJiangJie** [comment]
v4.2.0 版本中 vim 异常的问题已经修复。

最新版本 Web CLI 不能使用快捷键复制确实有问题，和 vim 没关系。

**Comment by BaiJiangJie** [comment]
v4.2.0 版本 command + c 复制没问题。
