### ISSUE TITLE
[Question] the ability to forward a token (including FIDO) to VDI for authentication

### ISSUE THREAD

**Issue by obgranat** [jumpserver/jumpserver#14261]
### Product Version

4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

We using Jumpserver in cluster mode on Ubuntu 22.04.

### 🤔 Question Description

Is there any option in Jumpserver to forward a token (including FIDO type) to a remote Jumphost (VDI) for authentication?

**Comment by BaiJiangJie** [comment]
Currently, Passkey authentication is supported, but other password-free authentication methods are not supported.
