### ISSUE TITLE
[Bug] 更新密码和重置密码两边特殊字符集不一致

### ISSUE THREAD

**Issue by guoheng888** [jumpserver/jumpserver#14264]
### 产品版本

v3.10.12

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

3.10.12版本

### 🐛 缺陷描述

重置密码时，+ - 被识别为特殊字符
![87f714c9-403c-40bc-8614-3b91f9b1ddf3](https://github.com/user-attachments/assets/8636dd3e-c257-4521-89d2-98fe9518435d)

更新密码时 + - 不识别为特殊字符
<img width="392" alt="企业微信截图_17275895425405" src="https://github.com/user-attachments/assets/528e3f49-8c39-4505-814f-28f3c97423f9">

用户更新密码信息和重置密码时，两边特殊字符不一致，给客户造成了困扰

### 复现步骤
1.更新用户密码
![image](https://github.com/user-attachments/assets/84bcc291-fb6a-406d-a59b-c5ffe6c62da4)
2.重置密码
![image](https://github.com/user-attachments/assets/6cff3679-52ab-42c1-9823-da36f9919cd4)
![87f714c9-403c-40bc-8614-3b91f9b1ddf3](https://github.com/user-attachments/assets/026f5c32-2c0e-40a1-88e9-6abaebd70ac8)

### 期望结果

明确提示哪些是特殊字符，或者统一规范

**Comment by BaiJiangJie** [comment]
v4.3 版本修复一下。

**Comment by BaiJiangJie** [comment]
Fixed pr: https://github.com/jumpserver/lina/commit/c62cd27690e37c2d52665879c34a6516a90c5519

**Comment by jym503558564** [comment]
v4.3.0 已修复，并发布，请升级进行体验。
