### ISSUE TITLE
[Question] jumpserver 4.2 web终端中的字体有堆叠现象

### ISSUE THREAD

**Issue by caihuazhg** [jumpserver/jumpserver#14267]
### 产品版本

4.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker allinone 部署

### 🤔 问题描述

web 终端中的字体错位堆叠
![1](https://github.com/user-attachments/assets/f8021780-3057-472c-a80b-df39fe4f50c9)

### 期望结果

不知道是设置问题还是bug

如果是设置问题  哪里设置可以调整

**Comment by BaiJiangJie** [comment]
v4.2.0 有 Bug，字体没有加载上，v4.3.0 修复。

**Comment by jym503558564** [comment]
v4.3.0 已修复，并发布，请升级进行体验。

**Comment by roywqs** [comment]
我当前版本v4.3.0，也遇到这个问题，要怎么处理。
![image](https://github.com/user-attachments/assets/bafb4ad3-0d7f-415b-a29b-3ccbd3acbfd0)
![image](https://github.com/user-attachments/assets/97aef8de-d86f-4af0-9edd-7301f8b69323)

**Comment by roywqs** [comment]
用chrome堆积，edge正常
