### ISSUE TITLE
[Bug] 作业中心作业无法停止

### ISSUE THREAD

**Issue by qiushuo29** [jumpserver/jumpserver#14263]
### 产品版本

V4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver web界面 工作台 执行测试作业

### 🐛 缺陷描述

![image](https://github.com/user-attachments/assets/56f4d405-1a3e-4e53-ad0c-34e091d0295a)
测试任务 执行时 不报错也不超时，就一直卡着了

### 复现步骤

在任务中心设置任务，参数shell  加 sudo -i   可能是因为这个命令引起的，执行用户是可以sudo的用户

### 期望结果

希望能知道怎么停止这些执行中的作业，如果没办法，希望加个功能，感觉有必要

### 补充信息

用户自己添加密钥也不行，添加密钥会进入白板页面，解决方式是 给了管理员权限才能添加密钥，添加完密钥再收回权限，其他没有了

### 尝试过的解决方案

重启jumserver 没有用

**Comment by BaiJiangJie** [comment]
看看任务输出日志中，有报错吗？
