### ISSUE TITLE
cocod无法启动：Failed register terminal Response json couldn't be decode

### ISSUE THREAD

**Issue by zx289317972** [jumpserver/jumpserver#1426]
(py3) [root@localhost coco]# ./cocod start
Start coco process
2018-06-12 17:47:13 [service DEBUG] Initial app service
2018-06-12 17:47:13 [service DEBUG] Load access key
2018-06-12 17:47:13 [service INFO] No access key found, register it
2018-06-12 17:47:13 [terminal ERROR] Response json couldn't be decode: 
2018-06-12 17:47:13 [service ERROR] Failed register terminal Response json couldn't be decode: 
(py3) [root@localhost coco]# lsof -i :2222
(py3) [root@localhost coco]# ./cocod status
Coco is stopped

**Comment by radiogit** [comment]
同样的问题，请问有解决方案吗？

**Comment by wojiushixiaobai** [comment]
@zx289317972 @radiogit 
# # 修改 Coco 配置文件
$ cd /opt/coco
$ cp conf_example.py conf.py
$ vi conf.py

#注意: 配置文件是 Python 格式，不要用 TAB，而要用空格，请手动修改，注意对其，不要直接复制本文内容

...
class Config:
"""
Coco config file, coco also load config from server update setting below
"""
    # 项目名称, 会用来向Jumpserver注册, 识别而已, 不能重复
    # NAME = "localhost"

    # Jumpserver项目的url, api请求注册会使用
    # CORE_HOST = os.environ.get("CORE_HOST") or 'http://127.0.0.1:8080'
    # 修改下面的192.168.100.100为你的 jumpserver url
    CORE_HOST = 'http://192.168.100.100'

**Comment by zx289317972** [comment]
@wojiushixiaobai  @radiogit 应该就是你说的这个问题，忘记修改配置了，谢谢。这两天放假，才答复，抱歉。
