### ISSUE TITLE
[Question] jms_all如何设置syslog转发

### ISSUE THREAD

**Issue by casualfish** [jumpserver/jumpserver#14269]
### Product Version

v4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

无

### 🤔 Question Description

如题，做了如下尝试（syslog接收端确认可以正常工作）：
1.参照v3版本的配置 https://kb.fit2cloud.com/?p=123 中的内容，配置config.txt后，使用supervisorctl reload，转发无效；
2.容器启动后docker exec -it jumpserver bash，修改/opt/jumpserver/config.yml（文件本身是空的），使用supervisorctl reload，转发无效，写入内容如下:
```bash
SYSLOG_ENABLE : true
SYSLOG_ADDR : "10.1.0.58:514" # Syslog 服务器的IP以及端口
SYSLOG_FACILITY : local2  #根据 Syslog 配置文件的配置
```
请问v4版本的all in one docker中如何配置syslog转发？

### Expected Behavior

无

### Additional Information

无

**Comment by BaiJiangJie** [comment]
修改完 config.txt 后重启服务。

**Comment by casualfish** [comment]
> 修改完 config.txt 后重启服务。

重启命令是supervisorctl restart all吗？没搜到jmsctl的命令

**Comment by casualfish** [comment]
> > 修改完 config.txt 后重启服务。
> 
> 重启命令是supervisorctl restart all吗？没搜到jmsctl的命令

试了supervisorctl restart all也无效

**Comment by wojiushixiaobai** [comment]
写入 **ENV** 即可，
```
docker run \
  -e SYSLOG_ENABLE=true \
  SYSLOG_ADDR=10.1.0.58:514 \
```

**Comment by casualfish** [comment]
> 写入 **ENV** 即可，
> 
> ```
> docker run \
>   -e SYSLOG_ENABLE=true \
>   SYSLOG_ADDR=10.1.0.58:514 \
> ```

确实可以了，SYSLOG_ENABLE、SYSLOG_ADDR、SYSLOG_FACILITY三个都可以作为环境变量传入。
