### ISSUE TITLE
[Bug] 批量添加账号，系统无响应，报504

### ISSUE THREAD

**Issue by 8x48** [jumpserver/jumpserver#14279]
### Product Version

3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

<img width="2552" alt="image" src="https://github.com/user-attachments/assets/2ba1e25c-f490-49de-8b55-a9b99cb27f75">

### 🐛 Bug Description

如图，资产数量过多的情况下，接口504

### Recurrence Steps

如图

**Comment by BaiJiangJie** [comment]
200+ 资产，不至于吧。
