### ISSUE TITLE
[Bug] gunicorn进程把4核cpu吃满

### ISSUE THREAD

**Issue by paochiang** [jumpserver/jumpserver#14278]
### 产品版本

v2.23.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

Ubuntu 18.04.5 LTS 机器上部署的k8s集群，然后在k8s环境中部署jumpserver，jms-core启动了2副本。启动的相关组件和个数参考：
<img width="739" alt="image" src="https://github.com/user-attachments/assets/95b54892-b90f-427a-ace0-e39bd956b391">

### 🐛 缺陷描述

1、jms-core pod的cpu我们限制了limit为4核。平常消耗的cpu都不到1核。

2、在使用过程中，有时会出现jms-core 2个pod的cpu打满，导致jms-core pod的liveness探活失败，最终导致jms-core pod反复重启。

3、进行了一些排查发现，jms-core pod的cpu被打满期间(大概2024-10-9:11:15:00 ~ 2024-10-9:13:08:00)，是4个gunicorn进程把cpu吃满了。
<img width="642" alt="image" src="https://github.com/user-attachments/assets/2d70a3d8-d9ee-40a0-8dc2-cea3deb9cc15">

4、jms-core pod的cpu被打满期间，gunicorn.log日志里有很多post请求： /api/v1/authentication/tokens/：
![image](https://github.com/user-attachments/assets/74968515-5c73-467e-8942-616386c3398d)
其中一个pod的gunicorn.log日志：
[筛选时间后-gunicorn.log](https://github.com/user-attachments/files/17337234/-gunicorn.log)

5、2个jms-core pod的cpu被打满并反复重启期间，容器内的内存和连接数也有明显的增长：
![image](https://github.com/user-attachments/assets/0d5afae7-eaee-4f7d-8f9b-36d8aaafd8e6)
![image](https://github.com/user-attachments/assets/c764fd71-24c9-4acd-a80e-d2fed9c36f6e)

### 复现步骤

线上的环境，线下暂无法模拟复现。

### 期望结果

我们已经在v2.23.0版本上做了一些二次修改，希望能帮忙定位到问题的原因，然后我们尝试在v2.23.0上修复，谢谢！

**Comment by BaiJiangJie** [comment]
看日志，应该是有大量请求导致的，请求多 Gunicorn 的负载就会高。

查看网络监控是否有大量请求在同一时间进入，有没有可能是恶意攻击行为？

如果长时间生产环境使用，还是建议升级到最新版本。

**Comment by paochiang** [comment]
> 看日志，应该是有大量请求导致的，请求多 Gunicorn 的负载就会高。
> 
> 查看网络监控是否有大量请求在同一时间进入，有没有可能是恶意攻击行为？
> 
> 如果长时间生产环境使用，还是建议升级到最新版本。

从日志看，QPS不会大于10，应该是密码或秘钥错误后的重试（可能是客户端的重试行为），不像是恶意攻击，看连接数一直在上涨，我感觉像是资源泄露。
正常情况下，4核CPU，Gunicorn能承受的QPS是多少？

**Comment by BaiJiangJie** [comment]
理论上，一台 4 核 CPU 的服务器上，每个请求的平均响应时间为 100ms，Gunicorn 工作进程数为 4 来计算，
每个工作进程的每秒请求处理能力为 10 QPS，
总的 QPS 为 4 * 10 = 40 QPS

**Comment by BaiJiangJie** [comment]
POST /api/v1/authentication/tokens/ 请求看起来有处理时间很长， 16s、32s 的情况都有。

环境中是否有配置第三方认证，比如 LDAP。

**Comment by paochiang** [comment]
> 理论上，一台 4 核 CPU 的服务器上，每个请求的平均响应时间为 100ms，Gunicorn 工作进程数为 4 来计算， 每个工作进程的每秒请求处理能力为 10 QPS， 总的 QPS 为 4 * 10 = 40 QPS。
> 
> POST /api/v1/authentication/tokens/ 请求看起来有处理时间很长， 16s、32s 的情况都有，但实际上没有太多的数据库查询。
> 
> 环境中是否有配置第三方认证，比如 LDAP。

没有配置第三方认证。

**Comment by BaiJiangJie** [comment]
现在 SSH 登录 KoKo还会有问题吗？

**Comment by paochiang** [comment]
> 现在 SSH 登录 KoKo还会有问题吗？

现在正常，上面jms-core的cou打满的问题是不定期出现的。

**Comment by BaiJiangJie** [comment]
关注一下 MySQL 数据库的操作，看看 CPU 打满的时候数据库有没有异常。

**Comment by paochiang** [comment]
> 关注一下 MySQL 数据库的操作，看看 CPU 打满的时候数据库有没有异常。
hi @BaiJiangJie 

我又手动测试复现了，复现环境里16个并发SSH登录就会出现把jms-core的4核cpu打满，然后我们在自己的v2.23.0二开版本上改动代码测试了一下 "POST /api/v1/authentication/tokens/ "  在服务端create方法的耗时：
https://github.com/jumpserver/jumpserver/blob/d3355ab0ec3732cf00946fb1fba9af09e0e4ca13/apps/authentication/api/token.py#L27-L47
在问题出现时，create方法本身没有超过2s，但实际SSH登录命令执行耗时会达到10s+，gunicorn的日志里打印的"POST /api/v1/authentication/tokens/ " 耗时也是10s+。

根据这段实践说明：
![image](https://github.com/user-attachments/assets/5a01cba4-cb8b-45f5-8e34-5d0e255b4a5b)

我们尝试修改 https://github.com/jumpserver/jumpserver/blob/d3355ab0ec3732cf00946fb1fba9af09e0e4ca13/apps/common/management/commands/services/services/gunicorn.py#L19-L28
为：
 ```
       cmd = [
            'gunicorn', 'jumpserver.wsgi',
            '-b', bind,
            '-k', 'sync',
            '-w', str(self.worker),
            '--max-requests', '4096',
            '--access-logformat', log_format,
            '--access-logfile', '-'
        ]

```
调整gunicorn为sync模式后(仍然未4个worker)，再次测试，发现16并发的SSH登录均能正常在1s内响应，gunicorn的cpu负载不再打满，达到预期了。

准备把我们线上做上述的修改调整，将gunicorn从gthread为sync模式，因为对gunicorn不太了解，所以想请假下，这个修改调整不会对jumpserver造成其他影响呀。
