### ISSUE TITLE
[Feature] 是否可以增加一个消息推送的机制，推送堡垒机一些临时消息，比如升级、临时维护等信息

### ISSUE THREAD

**Issue by ttkanni** [jumpserver/jumpserver#14270]
### Product Version

3.10.12

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

需求来源：
1，Jumpserver的公告板通常写的是安全使用要求这类固定信息；
2，Jumpserver升级、停机维护这类临时消息没有推送渠道；
3，堡垒机其他需要广泛通知的消息，没有有效推送的途径。

### Proposed Solution

是否考虑增加一个类似QQ右下角新闻弹窗的消息推送机制，用来通知一些临时消息。临时消息推送后，（指定时间段内）用户每次登录堡垒机右下角就弹窗提示一下，将临时消息及时传达给用户。
![消息弹窗图例](https://github.com/user-attachments/assets/92b8c5f5-d836-4ed4-9d89-e7e797116560)

**Comment by BaiJiangJie** [comment]
JumpServer 公告设置的定位就是临时消息推送，v4 新版本支持设置公告显示时间段。

**Comment by BaiJiangJie** [comment]
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/2e0efad9-084d-47e1-85e7-629572d69b45">
