### ISSUE TITLE
[Question] 支持对接 ELK 日志存储

### ISSUE THREAD

**Issue by xingyunliuyue** [jumpserver/jumpserver#14274]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver集群部署，linux环境

### 🤔 问题描述

jumpserver的日志什么时候方便的接入到elk中，直接传输的日志无法解析

### 期望结果

有官方的接入设置教程

**Comment by BaiJiangJie** [comment]
目前没有计划，现在支持将命令记录日志和用户操作日志存储到 es 中。
