### ISSUE TITLE
[Bug] 使用Web CLI方式连接MySQL数据库失败

### ISSUE THREAD

**Issue by wdwnet** [jumpserver/jumpserver#14275]
### Product Version

v4.0.1 v4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

v4.0.1 v4.2.0

### 🐛 Bug Description

使用Web CLI方式连接MySQL数据库失败，而改为使用Web GUI可以连接成功

### Recurrence Steps

使用Web CLI方式连接MySQL数据库失败，而改为使用Web GUI可以连接成功

**Comment by BaiJiangJie** [comment]
提供一下MySQL 数据库版本和报错信息截图。

**Comment by wdwnet** [comment]
![1](https://github.com/user-attachments/assets/46e9a0f3-a688-405d-8e32-eecfae1577c2)
![2](https://github.com/user-attachments/assets/6c2625e1-9890-46ba-b5cb-7f847fc3e719)

**Comment by BaiJiangJie** [comment]
Web CLI 连接时查一下 KoKo 日志。

**Comment by wdwnet** [comment]
见如下错误信息，另外还有个问题，4.0不支持db_client方式连接了吗，如果支持如何配置
![3](https://github.com/user-attachments/assets/62cd0ab0-5c63-4d17-9df9-5f6a61da6801)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/14235#issuecomment-2394955550

包含下划线的用户名登录失败，会在 v4.3.0 版本修复。

是的，v4 不支持 DB Client 方式连接。
