### ISSUE TITLE
[Bug] 通知设置中测试连接发送测试邮件报错Connection unexpectedly closed

### ISSUE THREAD

**Issue by zhouweihua713714** [jumpserver/jumpserver#14286]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu 20.04 

### 🐛 Bug Description

通知设置配置好后点测试连接，提示报错Connection unexpectedly closed
![image](https://github.com/user-attachments/assets/f34f3ae5-e18c-447e-acb6-d44b0378c277)
[](url)
![image](https://github.com/user-attachments/assets/b4b7aaaa-1ef3-4770-aba2-d7793d1fdc38)

### Recurrence Steps

linux系统：Ubuntu 20.04.6
离线安装，安装包为jumpserver-ce-v4.1.0-amd64.tar.gz ，4.2.0版本试过，有同样的问题
安装过程一切按默认安装
登录后按上图进行通知设置，点测试连接，报错Connection unexpectedly closed

### Expected Behavior

能正常发送测试邮件

### Additional Information

该系统上用heirloom-mailx 验证可以正常发送邮件，同时该系统docker安装的其他软件，比如grafana ，alertmanager等软件都能正常发送通知邮件
<img width="687" alt="image" src="https://github.com/user-attachments/assets/d7b3e861-ea1d-4315-8019-82131bec1de9">
![image](https://github.com/user-attachments/assets/7858904f-4020-485d-8afb-298d58c0e7d3)
![image](https://github.com/user-attachments/assets/a2206c2a-e8ec-46f0-a33a-c0f165844100)
![image](https://github.com/user-attachments/assets/5f1bce1e-cd7a-479b-a7fd-2de185afae05)

**Comment by BaiJiangJie** [comment]
尝试修使用 TLS 。

**Comment by zhouweihua713714** [comment]
> 尝试使用 TLS 。
报错一样
![image](https://github.com/user-attachments/assets/14a7fa5a-335b-4c29-b718-e774ae390ac0)

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/apps/settings/api/email.py#L50-L58

进入 django shell 中手动执行一下这两行命令，看看具体的报错信息。

**Comment by zhouweihua713714** [comment]
qq邮箱重新生成授权码，用新的授权码后可以正常发送邮件了。但是上一个授权码其他软件里有配置，一直正常工作在，不明白为什么在jumpserver中使用异常

**Comment by zhouweihua713714** [comment]
更新一下，是提交问题。需要输入正确的授权码，然后提交，然后再发送测试邮件。两个授权码都是正常可用的。
