### ISSUE TITLE
[mongodb连接报错] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14280]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

3.10.13的版本，主备环境

### 🐛 缺陷描述

web cli连接mongo 3.4版本的数据库，报错，如下图，
<img width="516" alt="wecom-temp-128261-7241bf87902e6de199978b5bbfc01d7d" src="https://github.com/user-attachments/assets/6cd0df64-0ba0-4d06-8ea1-7e061caf1234">

进入koko容器连接也是相同的错误，是否是版本兼容性问题，如果不支持连接3.4版本的Mongo数据库，后期是否有计划支持
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/026b155d-70b3-43a7-b788-0892fb702ae5">

### 复现步骤

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/72a6f9d8-5ea9-4413-9191-356d0f524fc9">

**Comment by BaiJiangJie** [comment]
mongoclient 本身不支持那就不支持。

**Comment by yuanxixue** [comment]
好的，了解，感谢

**Comment by bryanzl** [comment]
mongo版本太低，各位大佬如何重装客户端，在哪个组件里面重装
