### ISSUE TITLE
[Question] How to User website 

### ISSUE THREAD

**Issue by barto95100** [jumpserver/jumpserver#14282]
### Product Version

v4.0.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Jumpserver on linux (virtuel) and windows 2019 server fresh installed in other (virtual) all is VM on proxmox

### 🤔 Question Description

How to use and configure website ? I don't know how to configure to work I test to translate this documentation https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665 with google translate but difficult

### Expected Behavior

Connection to chrome andwebsite url configured

### Additional Information

When I test to connecte a received 

ErrTitle

JMSErrAPIFailed: connect API core err: No host account available

the applet host is green and applet chrome is green (deployed)

**Comment by BaiJiangJie** [comment]
Check whether the account list for the RemoteApp Host details is activated?

**Comment by barto95100** [comment]
> Check whether the account list for the RemoteApp Host details is activated?
> 
> Refer to the link: [#14074 (comment)](https://github.com/jumpserver/jumpserver/issues/14074#issuecomment-2337772709)

It's ok I connecte with webservie to windows server, but I received after second (websocket error....) do you have the url for websocket autorization ? I used the reverse proxy Fortiweb and its necessary to add the URI for websocket with regex maybe is the fortiweb to block websocket but no log in fortiweb .... :(

**Comment by barto95100** [comment]
I received this error in console :
<img width="1962" alt="image" src="https://github.com/user-attachments/assets/52834678-4513-4787-b85a-b42639eeaf64">

**Comment by BaiJiangJie** [comment]
Refer to the Nginx configuration at https://github.com/jumpserver/docker-web/blob/dev/includes/lion.conf and check if the corresponding configuration should be modified for FortiWeb.

**Comment by barto95100** [comment]
OK i look and test to configure de fortiweb with the same config

other question it's possible to configure de website with no url and juste the user chose the url to visite ?

it's for user access many router (~10000) but I test and I don't know how to configure the applet chrome with no url :(

**Comment by BaiJiangJie** [comment]
You can configure `https://google.com` so that after the user logs in successfully, they can press `Ctrl + t` to open a new tab and enter the URL or directly perform a search.

**Comment by BaiJiangJie** [comment]
Refer to https://github.com/jumpserver/jumpserver/issues/14539#issuecomment-2503538728.
