### ISSUE TITLE
[Feature] 数据库客户端方式拉起之后没法自定义设置token过期时间

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#14284]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

客户端方式访问数据库，建立连接之后不操作就会过期失效
<img width="725" alt="b62db472b7c8cda119221670c418e55" src="https://github.com/user-attachments/assets/3a85b0df-fd17-4797-ad21-19fefc47975e">
<img width="365" alt="a7afd57157ac8beeacd5dad7a0cacb7" src="https://github.com/user-attachments/assets/398dd76c-6ca5-4986-b594-288d6f511c0d">

### 解决方案

这个数据库客户端方式可以跟连接向导一样设置成可配置项，由用户自己设置他的过期时间么

**Comment by BaiJiangJie** [comment]
直接拉起客户端方式不支持配置有效期，复用 Token 必须是在 DB 连接向导页面打开。

**Comment by seaurching** [comment]
> 户端方式不支持配置有效期，

这个可以自定义时间吗
