### ISSUE TITLE
[Bug] 远程应用chrome界面可以通过下载界面访问windows文件夹桌面操作远程windows发布机

### ISSUE THREAD

**Issue by jixuuse** [jumpserver/jumpserver#14285]
### Product Version

4.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

win2019远程应用发布机

### 🐛 Bug Description

远程应用chrome界面可以通过下载界面访问windows文件夹桌面操作远程windows发布机

### Recurrence Steps

1、查看网页源码
![图片](https://github.com/user-attachments/assets/408e7ca4-3d3d-4465-ae8e-fd51e2d124e0)

2、浏览器地址栏直接访问系统分区
![图片](https://github.com/user-attachments/assets/1d1e18c4-659b-4d88-aa34-3083add82fcd)

3、任意下载一个文件并保存，选择打开下载文件夹
![图片](https://github.com/user-attachments/assets/f8c3baa1-c941-4ed5-8999-d8675bb03067)

4、此时已经可以随意操作远程应用服务器，传输各种工具软件到本地执行，访问和查看系统设置
![图片](https://github.com/user-attachments/assets/1435bb3b-de4b-4685-81a5-e10fa2a7bb21)

![图片](https://github.com/user-attachments/assets/d1b10255-f45c-4b23-ac78-bf9b3daa826d)

**Comment by BaiJiangJie** [comment]
1. 新创建一个 Website 平台，协议设置中开启安全模式。
2. 使用新平台创建 Web 资产。

<img width="2342" alt="image" src="https://github.com/user-attachments/assets/3079b57e-6a2c-4aab-9e5f-aa56fc93f1d9">

**Comment by jixuuse** [comment]
你试试在安全模式下的website里按F1，虽然禁止了直接打开浏览器下载窗口，但是按照上面操作下载本机文件完成后会有提示，选择上面的打开文件夹以后又可以执行任意操作了

![图片](https://github.com/user-attachments/assets/566ae996-144f-4806-8dad-460ef5013967)

![图片](https://github.com/user-attachments/assets/2fcd5962-289a-476c-bb33-8c4eac7e483e)

**Comment by BaiJiangJie** [comment]
你的 Web 应用打开时就显示了地址栏了吗？

**Comment by jixuuse** [comment]
虽然你屏蔽了f12调试，但是按f1会弹出正常浏览器界面

**Comment by BaiJiangJie** [comment]
按 F1 会闪一下，但是会立即关掉还是不能操作。

**Comment by BaiJiangJie** [comment]
https://github.com/user-attachments/assets/8229f118-ed81-4f8b-99ba-b736d347e8fb

**Comment by jixuuse** [comment]
我已经升级到最新的4.2.0-ce了，f1确实可用

https://github.com/user-attachments/assets/dc34a54e-9058-4775-beb7-9e511d42720f

**Comment by jixuuse** [comment]
我找了一个可以显示输入的录屏软件


https://github.com/user-attachments/assets/04c14964-a24d-44df-aad0-6c3b7931b74f

**Comment by BaiJiangJie** [comment]
F1 是打开 Google Chrome 的帮助页面，https://support.google.com/，在你的发布机上可以访问到吗？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/14308

v4.3.0 会禁用掉 F1 键。
