### ISSUE TITLE
[Question] helm 部署jumpserver到k8s集群，控制台显示koko离线

### ISSUE THREAD

**Issue by yxxchange** [jumpserver/jumpserver#14294]
### Product Version

v4.20

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

Amazon Linux 2 EC2 实例
k8s版本：v1.25.0 

### 🤔 Question Description

刚刚利用helm部署的jumpserver实例，显示koko集群离线，其他组件都正常，但koko的pod是正常的，请问，该如何排查这个问题
站内信信息：The component is offline: [KoKo]-paas-jumpserver-jms-koko-75786c48cf-nvhkp-EhcQvKU

**Comment by wojiushixiaobai** [comment]
如果 **koko** 的持久化没问题，那你看看 **koko** 组件的日志。
如果都无异常那就可以忽略，如果有异常可以尝试把 **pod** 重启。

出现此问题的原因也可能是 **core** 组件的异常导致的

**Comment by yxxchange** [comment]
koko的replica数是1，但是组件列表那里记录到了两个，我猜，可能是部署的时候出了什么问题，导致koko的pod起了一个被杀死了，然后又起来一个，记录到了两个pod导致的
