### ISSUE TITLE
[Question] 关于JumpServer config.txt的问题

### ISSUE THREAD

**Issue by fantasy0v0** [jumpserver/jumpserver#14291]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Debian：12
1Panel：v1.10.18-lts
JumpServer：v4.2.0

### 🤔 问题描述

我想修改jumpserver的一些参数，但是根据文档里面提示的 https://docs.jumpserver.org/zh/master/admin-guide/env/ 
硬盘上不存在这个目录和文件。

/opt/jumpserver/config/config.txt

```bash
root@1panel:~# docker exec -it 1Panel-jumpserver-hsst bash
root@ada3a2454b0b:/opt# find / -name config.txt
root@ada3a2454b0b:/opt# 

```

### 期望结果

请问目前应该如何修改参数呢？

**Comment by BaiJiangJie** [comment]
重启 docker 的时候，-e 传入配置。
