### ISSUE TITLE
[Bug] 应用发布机部署成功，无法通过web访问http服务

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#14298]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

环境：centos7.9

### 🐛 缺陷描述

应用发布机部署成功，无法通过web访问http服务，出现报错
报错截图：
![image](https://github.com/user-attachments/assets/009fa867-4edb-47d8-9779-706fda05d16b)

website配置截图：
![image](https://github.com/user-attachments/assets/21fb52a1-cb4d-42c3-8e91-f7b0fdaa47f9)

发布机配置：
![image](https://github.com/user-attachments/assets/be39338c-0b7d-49b8-b064-629ecb9a0ba3)
![image](https://github.com/user-attachments/assets/d9879dc5-3d0f-40ed-ac12-6da0da349d6c)
![image](https://github.com/user-attachments/assets/3e6cead7-74b8-4a08-9430-caeb9c8349a4)

### 复现步骤

无

**Comment by BaiJiangJie** [comment]
查看应用发布机详情中的账号列表的有效性。

**Comment by Lynxhide** [comment]
好嘞，谢谢您，问题已解决
