### ISSUE TITLE
[Question] How do I use the new Object storage feature in components?

### ISSUE THREAD

**Issue by Chocopediaa** [jumpserver/jumpserver#14295]
### Product Version

v4.0.2

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Multi worker server to server JumpServer backend
Using HAProxy to serve frontend
Using MinIO separated to use as storage

### 🤔 Question Description

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/fbde6dcd-79f7-4784-b702-c1cdafddd348">
As image shown, I create connection to MinIO server and tested OK. But when I record video for playback, it doesn't save to MinIO bucket (assumption that video still on backend server).

### Expected Behavior

Video saved in MinIO bucket.

### Additional Information

I couldn't find "terminal" menu, to point where video resource will be saved as mentioned on guidance.

**Comment by BaiJiangJie** [comment]
You need to modify the "replay storage" of each component to MinIO.

Navigate to "System settings > Components > Components".

**Comment by Chocopediaa** [comment]
Hi,
Yes we do change all of the components the same as previews pictures. Here is all of components that we changed.
[PastedGraphic-1.png]

But still no luck.

Regards

On 14 Oct 2024, at 13.25, Bryan ***@***.***> wrote:



You need to modify the "replay storage" of each component to MinIO.

Navigate to "System settings > Components > Components".

**Comment by BaiJiangJie** [comment]
<img width="2383" alt="image" src="https://github.com/user-attachments/assets/52d4aec5-b055-435c-be2a-599f8d01bfbb">

Check the column on this page.

**Comment by Chocopediaa** [comment]
Hi Bryan, here is the screenshot of your request. We didn’t take any action yet.
[PastedGraphic-1.png]


On 14 Oct 2024, at 14.10, Bryan ***@***.***> wrote:


image.png (view on web)<https://github.com/user-attachments/assets/52d4aec5-b055-435c-be2a-599f8d01bfbb>

Check the column on this page.

**Comment by Chocopediaa** [comment]
Sorry for wrong platform, I reply it on mail.
Here is the last condition.
<img width="1683" alt="SCR-20241014-pdra" src="https://github.com/user-attachments/assets/2a21e040-e97e-487a-8503-5fcfaab812e0">

**Comment by Chocopediaa** [comment]
Update information:
At the first configuration, I set NFS on /etc/fstab to other VM environment, and the videos are there for the moment.
Should we disable it to allow MinIO access video playback?

**Comment by BaiJiangJie** [comment]
Yes, you try it.

**Comment by Chocopediaa** [comment]
I did, but still no luck. The content is still in `/opt/jumpserver/core/data/media/replay/`, but not linked to NFS as before. And not linked to MinIO as wished.

**Comment by BaiJiangJie** [comment]
Which protocol session are you connected to? After the session ends, check the logs of the component, such as koko (SSH) or lion (RDP)

Restart the service using the `./jmsctl restart` command.
