### ISSUE TITLE
[Question] 管理k8s集群时，初始化连接（获取到namespace，pod，container这些信息）时，直接通过apiserver list获取的吗？还是有缓存层？

### ISSUE THREAD

**Issue by yxxchange** [jumpserver/jumpserver#14300]
### 产品版本

v4.20

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

linux aws ec2
helm部署

### 🤔 问题描述

我希望能够通过jumpserver管理我的云资源，在方案评估中遇到了一个问题，希望大佬们能帮忙解答一下。
我们集群规模比较大，如果频繁访问apiserver对集群压力会比较大。所以，在这里咨询一下，在jumpserver连接k8s资源的时候，其实连接初始化时，会初始化获取pod、ns、container这些信息，请问，是每次连接都会直接走apiserver获取吗？还是说，jumpserver内部做了缓存层。

**Comment by BaiJiangJie** [comment]
每次打开 K8s 资产连接页面加载左侧 K8s 资源树的时候会获取一次，后续连接中不会调用 API。

相当于每次刷新页面都会调用 API 获取。

**Comment by yxxchange** [comment]
请问大佬，有没有直接进入到容器的能力，不获取资源树。
从接口上看，进入terminal界面时，就是ws连接了。然后第一次，获取资源树时，传入的参数时K8sTree。第二次，才是具体的容器。
请问，是否能直接跳过第一步的传参，传入第二个参数。

**Comment by BaiJiangJie** [comment]
不可以，需要先加载出资源树才知道有哪些 Pod，才能连接。
