### ISSUE TITLE
[Question] 在使用web应用时，应用登录页面会跳转怎么办？

### ISSUE THREAD

**Issue by D5EB6AEC** [jumpserver/jumpserver#14302]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Windows 2019的应用发布服务器

### 🤔 问题描述

在一些类似vmware vcenter的应用，访问登录页面时会自动跳转到一个带单点登录token之类的链接上，虽然链接主体还是原本的域名，但整体多了很多其他字符，关键是每次生成的都会不一样，这种还有啥办法解决吗？

**Comment by BaiJiangJie** [comment]
只看文字没有理解具体的问题在哪儿，你就正常配置 Web 资产地址和用户名、密码代填，中加加一些 sleep 延迟一下呢？

**Comment by D5EB6AEC** [comment]
> 只看文字没有理解具体的问题在哪儿，你就正常配置 Web 资产地址和用户名、密码代填，中加加一些 sleep 延迟一下呢？

大概就是这么个意思，某些应用，譬如应用地址是：https://www.test.cn 
访问后，它会自动跳转一下变成 https://www.test.cn/SSO/token=b618ce1e67e3051dd7b318098220681243bec5e2 这种，然后下次访问跳转的地址又不一样，可能是 https://www.test.cn/SSO/token=19dad50dfec1a3748499213d070fbd67ad4d257a，每次token都是不一样的，登录后又跳转回https://www.test.cn，这个token会有时效性，譬如1分钟后就失效了，再访问就会报错。

类似这种情况

不知道有什么好的解决办法吗？

**Comment by BaiJiangJie** [comment]
没关系，找到输入用户名密码的页面，自定义认证信息输入步骤就行。

跟 token 是什么值没关系。
