### ISSUE TITLE
[Question] 在虚拟机桌面里面打开web终端界面，web终端里面右键没有反应

### ISSUE THREAD

**Issue by wzqiang1332** [jumpserver/jumpserver#14305]
### 产品版本

3.10-4.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [x] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：centos7
物理机客户端浏览器chrome，操作系统win11
虚拟机客户端浏览器chrome，操作系统win10

### 🤔 问题描述

在外面的物理机上访问jumpserver的web终端，终端里面右键菜单正常，
但是在虚拟机里面打开web终端，右键没有任何菜单，无法复制粘贴体验很不好。

### 期望结果

期望在虚拟机里面打开web终端时可以和外面物理机一样，终端里面右键菜单能正常显示

**Comment by BaiJiangJie** [comment]
在哪个虚拟机里面打开的 Web 终端？

**Comment by wzqiang1332** [comment]
> 在哪个虚拟机里面打开的 Web 终端？

vmvare horizon client里面

**Comment by BaiJiangJie** [comment]
你在虚拟机的浏览器里，打开其他页面可以右键吗？

**Comment by wzqiang1332** [comment]
![image](https://github.com/user-attachments/assets/cd5bfc52-7ab8-43b9-883f-1064e7abd8f2)
只有终端这块区域右键没有反应，其他地方都是正常的，其他的网页也是正常的。

**Comment by BaiJiangJie** [comment]
这个页面，选中=复制，右击=粘贴，没有弹窗。
