### ISSUE TITLE
[Question] web类型自动代填功能，具体怎么使用，看文档好像只提到了比如类似"登录"按钮之类的用法，用户名和密码怎么代入？

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#14301]
### 产品版本

v4.0.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7.9

### 🤔 问题描述

web类型自动代填功能，具体怎么使用，看文档好像只提到了比如类似"登录"按钮之类的用法，用户名和密码怎么代入？
![image](https://github.com/user-attachments/assets/d749b89e-e6ed-49a9-9b33-96ec700b003f)
比如grafana之类的开源工具

**Comment by BaiJiangJie** [comment]
代填参考链接：
https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f

**Comment by Lynxhide** [comment]
好嘞，谢谢，问题已解决
