### ISSUE TITLE
[Bug] 手动账号无法使用SSH直连

### ISSUE THREAD

**Issue by Coldfengzi** [jumpserver/jumpserver#14316]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

SSH直连工具：MobaXterm或XShell

### 🐛 缺陷描述

使用ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP方法直连服务器时，如果是手动账户的话：
![image](https://github.com/user-attachments/assets/37768eff-bca3-43be-8dfa-3e46d83747c0)
SSH直连时，systemUsername无论是留空或者输入自定义的用户名，都报：未发现匹配的用户名

### 复现步骤

每次必现

### 期望结果

手动账户时给一个特殊的用户名或者支持指定用户登录。

**Comment by BaiJiangJie** [comment]
手动输入账号后，使用SSH向导方式连接。

**Comment by laven807** [comment]
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP  这条命令是不是用不了了

**Comment by laven807** [comment]
feat: 支持通过 ssh 命令直连资产的连接格式，使用分割符号 #，且可使用系统用户 ID 和资产 ID 登录（两者必须同时为 UUID）

这是2.13.0 更新日志里的说明，也没有举例，然后官方文档里也没有说明

**Comment by snowpubby** [comment]
使用jenkins部署，需要配置ssh连接到jumpserver，再连接到资产服务器，在页面上是能手动点，怎么才能在jenkins配置能直连呢？

**Comment by snowpubby** [comment]
在JumpServer v2.11.0版本中，支持通过SSH工具直连资产。使用命令格式：ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222，如果能匹配到唯一资产、唯一系统用户名，则可直接登录该资产。如匹配到多个同IP资产，则用户可自主选择资产以及系统用户进行登录。

哈哈哈，试了下这个，可以ssh直连了
