### ISSUE TITLE
节点的数据结构问题

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1431]
版本：1.3.1
目前父节点不会自动继承子节点的资产，这样页面上点击父节点的时候看不到所有资产，需要点子节点查看，在搜索资产的时候会比较麻烦。

**Comment by gengkeye** [comment]
个人认为这样设计更符合树的结构，不过灵活性会损失一些。

**Comment by ibuler** [comment]
右击树，显示子节点的资产就可以了

**Comment by gengkeye** [comment]
@ibuler 能否改成默认显示所有子节点资产?
