### ISSUE TITLE
[Question] nginx二级目录代理 jms 无法访问

### ISSUE THREAD

**Issue by caichangchun** [jumpserver/jumpserver#14314]
### 产品版本

jumpserver/jms_all:latest

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker部署

### 🤔 问题描述

 nginx二级目录代理 jms 无法访问，具体配置如下：
![image](https://github.com/user-attachments/assets/5966ea24-7ee3-43be-9cf7-86e70b1857f7)

### 期望结果

nginx二级目录代理 jms 如何配置？

**Comment by caichangchun** [comment]
location /jms {
           proxy_pass http://xxxx:8081;

           rewrite "/jms/(.*)$" /$1 break;
           proxy_http_version 1.1;
           proxy_buffering off;
           proxy_request_buffering off;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header Host $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_redirect ~^/(.*) https://$http_host/jms/$1;
           sub_filter_types *;
           sub_filter_once off;
           sub_filter '/static/' '/jms\/static/';
           sub_filter '/ui/' '/jms/';
           sub_filter '/api/' '/jms/api/';
           sub_filter '/core/' '/jms/core/';
           sub_filter '/ws/notifications/' '/jms/ws/notifications/';
           sub_filter '/luna/' '/jms/luna/';
           sub_filter '/koko/' '/jms/koko/';
           sub_filter '/lion' '/jms/lion';
           sub_filter '/media/' '/jms/media/';
           sub_filter '/omnidb/' '/jms/omnidb/';
    }

**Comment by caichangchun** [comment]
参考这个链接部署的
https://github.com/jumpserver/docs/pull/213/files
但是依然有问题

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/docs/pull/213#issuecomment-1805005302

https://github.com/jumpserver/docs/pull/213#issuecomment-2182189876

这两个都配置一下，试试。
