### ISSUE TITLE
[Feature] 同名账号支持使用 ssh-key 登录

### ISSUE THREAD

**Issue by liyahui2012** [jumpserver/jumpserver#14323]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

在不使用 ldap 的情况下，如果有多台主机，每台主机有多个不同的账号（同用户账号），目前只能手动在每台主机上把这些用户账号建好（并且还需要知道用户的密码，存在管理问题）。
希望同名账号能实现使用统一 ssh-key 登录或者托管密码的方式进行登录（由主机管理员自行创建好账号密码/ssh-key，认证信息托管在堡垒机上，用户无需知晓）

### 解决方案

以下方案可选：
1. 同名账号支持推送到指定主机资产
2. 同名账号支持配置全局 ssh-key 并在登录资产时使用
![image](https://github.com/user-attachments/assets/be22b2e0-cddf-4ad7-acac-ba3d59e895be)
3. 主机资产中的账号创建可用 @USER 作为账号名，密码/ssh-key 可自行配置（目前可以填 @USER，但实际连接资产时还是走同名账号的逻辑，主机资产账号设置的密码或者 ssh-key 无效）
![image](https://github.com/user-attachments/assets/23652661-f1b0-4c08-b7e7-5306fde0b462)

**Comment by BaiJiangJie** [comment]
使用账号推送功能完美解决。

**Comment by liyahui2012** [comment]
> 使用账号推送功能完美解决。
> 
> <img alt="image" width="1269" src="https://private-user-images.githubusercontent.com/32935519/377749497-42bcba0d-7f18-4764-af17-c48e60a79c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQ5MzgsIm5iZiI6MTcyOTI0NDYzOCwicGF0aCI6Ii8zMjkzNTUxOS8zNzc3NDk0OTctNDJiY2JhMGQtN2YxOC00NzY0LWFmMTctYzQ4ZTYwYTc5YzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA5NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkODA3OWJhZjZiZTJjZDZmZGY4ZTZhZTk0YWY4ZjI1NTM4MDNjMTI0YzM4MGU5ZTM3Nzg4ZTRiMDY3NjQ0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iXg6UwT1E6XR6SwyjUfkEe8NuwryfjHRosmyVK8rCEI">

对于账号数量很多且需要频繁新增账号、以及每台主机账号都不一样的情况下，每次都要手动推送创建账号的人工成本很高

**Comment by BaiJiangJie** [comment]
企业版有定时任务推送。

**Comment by BaiJiangJie** [comment]
方案 2、3 暂不考虑。

**Comment by techmouse84** [comment]
+1
在 v3 的版本 ，是可以用动态用户名来达到这个目的的。 
到了v4 后， 这个操作就没了。 

![image](https://github.com/user-attachments/assets/263fa7b5-63a2-4ac1-b547-b5afef57b0a4)

**Comment by BaiJiangJie** [comment]
v4 中可以通过账号模版与资产关联，或者在授权规则中授权账号模版，来实现自动推送。

**Comment by omigo** [comment]
> > 使用账号推送功能完美解决。
> > <img alt="image" width="1269" src="https://private-user-images.githubusercontent.com/32935519/377749497-42bcba0d-7f18-4764-af17-c48e60a79c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQ5MzgsIm5iZiI6MTcyOTI0NDYzOCwicGF0aCI6Ii8zMjkzNTUxOS8zNzc3NDk0OTctNDJiY2JhMGQtN2YxOC00NzY0LWFmMTctYzQ4ZTYwYTc5YzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA5NDM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkODA3OWJhZjZiZTJjZDZmZGY4ZTZhZTk0YWY4ZjI1NTM4MDNjMTI0YzM4MGU5ZTM3Nzg4ZTRiMDY3NjQ0MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iXg6UwT1E6XR6SwyjUfkEe8NuwryfjHRosmyVK8rCEI">
> 
> 对于账号数量很多且需要频繁新增账号、以及每台主机账号都不一样的情况下，每次都要手动推送创建账号的人工成本很高

你们后来怎么解决的？
