### ISSUE TITLE
[Question] 使用客户端方式连接windows时无法用mstsc中的选择连接速度功能

### ISSUE THREAD

**Issue by haipeng-fit2** [jumpserver/jumpserver#14322]
### 产品版本

V3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

使用的centos单机部署的jumpserver，通过谷歌浏览器129版本（最新版）访问

### 🤔 问题描述

通过jumpserver客户端方式连接windows，打开工业制图软件，会比较卡顿。
在使用windows原本的mstsc连接时，通过调整体验-选择连接速度来优化性能-低速带宽，远程就不会卡顿
<img width="575" alt="image" src="https://github.com/user-attachments/assets/0bead924-51a4-4ca2-8e78-1fa7a1fd5748">
在使用jumpserver客户端方式时没有出现可以选择的界面而直接跳过连接了，导致操作图像卡顿，
<img width="701" alt="image" src="https://github.com/user-attachments/assets/20b1203d-9c4a-4014-8705-573ebcae4d50">
在高级选项中调整过rdp分辨率，但效果不明显
<img width="719" alt="image" src="https://github.com/user-attachments/assets/a6851498-9387-46b4-a1d1-4a9da6f7350a">
通过下载rdp文件的方式是可以到选择连接速度来优化性能界面，但每次连接windows都需要下载，比较麻烦。
是否可以直接在客户端阶段选择mstsc的一些选项，如体验中的性能选项

### 期望结果

如何配置才能在客户端连接方式可选择mstsc中的体验中的性能选项
如现在还不满足的话，或者能加入需求池中进行迭代

**Comment by BaiJiangJie** [comment]
意思是通过 .rdp 文件连接可以看到 远程桌面连接中的体验 页面，在 Luna 上使用客户端方式直接拉起就看不到？

**Comment by haipeng-fit2** [comment]
> 意思是通过.rdp文件连接可以看到远程桌面连接中的体验页面，在Luna上使用客户端方式直接拉起就看不到？

是的，下载的.rdp文件在windows系统中可以通过右键编辑打开mstsc控制台，而Luna上使用客户端方式没有可以编辑的地方，拉起直接进入了目标资产中
![image](https://github.com/user-attachments/assets/52215ae2-61e1-4aa2-b7a4-dabebce97c6d)

**Comment by haipeng-fit2** [comment]
> 另一个问题是，修改体验中的宽带配置，确定能够提升流畅度吗？
是的，现场测试过修改体验中的宽带配置后，有明显提升
这是提升前

https://github.com/user-attachments/assets/f67de034-7178-4c58-9c05-a11652467744


这是修改宽带配置后

https://github.com/user-attachments/assets/6019859e-9461-4793-b2da-bf94db7a4492

**Comment by BaiJiangJie** [comment]
@LeeEirc Guacamole 如果支持参数，可以考虑增加。

**Comment by LeeEirc** [comment]
试试 rdp 文件类型里加上以下参数

```
connection type:i:2
disable wallpaper:i:1
allow font smoothing:i:0
allow desktop composition:i:0
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:1
disable cursor setting:i:0
bitmapcachepersistenable:i:1
```
