### ISSUE TITLE
[Question] 请问在“工作台-我的资产-连接资产”页面，资产列表如何按照IP从小到大的方式排列？

### ISSUE THREAD

**Issue by wqinf** [jumpserver/jumpserver#14327]
### 产品版本

v4.3.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Linux单机部署

### 🤔 问题描述

请问在“工作台-我的资产-连接资产”页面，资产列表如何按照IP从小到大的方式排列？
![微信截图_20241019225527](https://github.com/user-attachments/assets/4cc75183-a339-4776-b59e-a9a43978da67)

如不支持的话，是否可以考虑增加此个性化设置在偏好设置中？谢谢

### 期望结果

支持资产列表设置默认按照IP从小到大的方式排列

**Comment by BaiJiangJie** [comment]
默认按照 Name 进行排序，如果要按照地址排序，点地址右侧的上线箭头可以临时按照地址排序。

默认排序方式暂不考虑支持。

**Comment by wqinf** [comment]
> 默认按照 Name 进行排序，如果要按照地址排序，点地址右侧的上线箭头可以临时按照地址排序。
> 
> 默认排序方式暂不考虑支持。

希望可以支持在偏好设置中自定义排序方式，原本的排序方式可以保持原样，有需要的可以进行调整，希望考虑一下，谢谢。

**Comment by BaiJiangJie** [comment]
因为 Web 页面有左侧资产树，并且可以在列表中操作，所以默认方式不考虑。

SSH 登录 KoKo 页面显示资产的排序方式有默认的设置。
