### ISSUE TITLE
[对象存储支持使用 AWS S3存储基于角色的IAM认证] 

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14325]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

对象存储支持使用 AWS S3存储基于角色的IAM认证
<img width="989" alt="image" src="https://github.com/user-attachments/assets/f0ff87c2-3832-4e78-a24e-75a389d4dfae">

### 解决方案

对象存储支持使用 AWS S3存储基于角色的IAM认证

**Comment by BaiJiangJie** [comment]
需求用户数量达到 20+，再考虑支持。
