### ISSUE TITLE
[Bug] 本地数据库 命令记录记录不完整，会使用 ... 代替的问题

### ISSUE THREAD

**Issue by sp4rkw** [jumpserver/jumpserver#14336]
### Product Version

3.10

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

无

### 🐛 Bug Description

审计模块-命令记录，记录的命令不完整，大量的命令中间出现...做代替，即使使用syslog链路投递出审计日志
![image](https://github.com/user-attachments/assets/fb3aa444-f671-4d96-8470-2bc3da035257)

不知道是否可以通过修改什么配置，来保障完整的命令记录

### Recurrence Steps

无

**Comment by BaiJiangJie** [comment]
本地数据库存储会限制命令的长度，使用 ... 代替，如果要保留完整日志，配置使用外部 es 存储，可以保存。

**Comment by sp4rkw** [comment]
> 使用本地数据库存储命令时，会限制命令的长度并使用 ... 代替。如果要保留完整日志，建议配置使用外部 es 存储。

使用外部es时，无需做其他的设置，就会保留完整日志么？另外syslog也是受这个影响么？

**Comment by BaiJiangJie** [comment]
SYSLOG 和 本地数据库逻辑一致。

使用 ES 配置好之后，不用做其他操作。

**Comment by sp4rkw** [comment]
> SYSLOG 和 本地数据库逻辑一致。
> 
> 使用 ES 配置好之后，不用做其他操作。

已解决，非常感谢

**Comment by sp4rkw** [comment]
> SYSLOG 和 本地数据库逻辑一致。
> 
> 使用 ES 配置好之后，不用做其他操作。

遇到一个新的问题，切换成es之后，session_command_log 类型的日志在syslog就看不到了。这个问题是预期的么？

**Comment by sp4rkw** [comment]
问题死锁了，我其实想通过syslog消费命令记录来做实时审计，但是因为命令记录不全，所以按给到的方案切换成了es存储。此时es这边确实可以看到完整的命令了，但是syslog这边没有命令记录。

所以我该如何在syslog获得完整的命令呢？

**Comment by BaiJiangJie** [comment]
目前，JumpServer 的命令日志，存储逻辑是这样的：

1. 保存到本地数据库，可以同时存储到 SYSLOG 系统（但是命令长度会有限制，命令记录不完整）
2. 保存到 ES 数据库，此时不会存储到本地和SYSLOG 系统（命令长度没有限制，命令记录完整）

需求：命令长度记录完整 & 记录到 SYSLOG 系统
解决：JumpServer 使用 ES 存储，并且在 ES 服务中配置 SYSLOG 系统同步。

**Comment by sp4rkw** [comment]
> 目前，JumpServer 的命令日志，存储逻辑是这样的：
> 
> 1. 保存到本地数据库，可以配置同时存储到 SYSLOG 系统（但是命令长度会有限制，命令记录不完整）
> 2. 保存到 ES 数据库，此时不会存储到本地和SYSLOG 系统（命令长度没有限制，命令记录完整）
> 
> 需求：命令长度记录完整 & 记录到 SYSLOG 系统 解决：JumpServer 使用 ES 存储，并且在 ES 服务中配置 SYSLOG 系统同步。

get，明白了
