### ISSUE TITLE
Remote Apps Error

### ISSUE THREAD

**Issue by bnrs009** [jumpserver/jumpserver#14334]
### Product Version

v4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Install jumpserver on ubuntu 22 and remote apps on windows server 2019

### 🤔 Question Description

I add website access but error shown
![jumpservererror](https://github.com/user-attachments/assets/d879523e-f58e-4f9d-9d2e-57c5bdb107b3)

**Comment by BaiJiangJie** [comment]
Refer to https://github.com/jumpserver/jumpserver/issues/14282.
