### ISSUE TITLE
[Bug] 企业版回退的开源版里面的时候，里面只显示system组织，但是资产都在default组织里面，回退到开源版本就无法使用了。建议回退默认指定到default组织下，这样回到到开源版本还可以继续使用。

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#14338]
### 产品版本

3.10.13

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

全新安装的3.10.13版本，centos7.9。运行正常。

### 🐛 缺陷描述

企业版回退的开源版里面的时候，里面只显示system组织，但是资产都在default组织里面，回退到开源版本就无法使用了。建议回退默认指定到default组织下，这样回到到开源版本还可以继续使用。

### 复现步骤

企业版回退的开源版里面的时候，里面只显示system组织，但是资产都在default组织里面，回退到开源版本就无法使用了。建议回退默认指定到default组织下，这样回到到开源版本还可以继续使用。

### 期望结果

建议回退默认指定到default组织下，这样回到到开源版本还可以继续使用。

### 尝试过的解决方案

尝试过使用不同的浏览器，但是依然只能访问到system组织下。

**Comment by BaiJiangJie** [comment]
清除 LocalStorage。
