### ISSUE TITLE
[Bug] 反馈2个jumpserver v4.3.0版本的bug

### ISSUE THREAD

**Issue by chown1987** [jumpserver/jumpserver#14337]
### Product Version

v4.3.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

OS版本：ubuntu 24.04
docker版本：27.0.3
docker-compose版本：v2.28.1

### 🐛 Bug Description

1、在jumpserver v4.3.0版本的web终端上无法通过ssh连接centos 7系统的目标主机，和之前websocket连接异常的bug现象一致。
2、在jumpserver v4.3.0版本通过web终端连接进k8s集群后，某pod中有多个容器的情况下，无法选择连接指定的某个容器。

### Recurrence Steps

1、在jumpserver v4.3.0版本的web终端上无法通过ssh连接centos 7系统的目标主机，和之前websocket连接异常的bug现象一致。
2、在jumpserver v4.3.0版本通过web终端连接进k8s集群后，某pod中有多个容器的情况下，无法选择连接指定的某个容器。

**Comment by BaiJiangJie** [comment]
第一个问题提供一下报错信息。

第二个问题，K8s 连接的左侧资源树最低一级会显示到容器层，应该可以选择连接。

**Comment by chown1987** [comment]
第1个问题的截图如下：
![企业微信截图_20241023154220](https://github.com/user-attachments/assets/37a64c08-8146-489d-9229-2aaff2aa4a73)
第2个问题的截图如下：
![微信截图_20241023154427](https://github.com/user-attachments/assets/1d5b8a0c-6b67-4e83-9947-40f500ed877e)

**Comment by chown1987** [comment]
第2个问题追加的截图如下：
![企业微信截图_20241023161400](https://github.com/user-attachments/assets/5c68f1b2-d393-4456-bb90-3b5b44d428a3)
单个pod内有多个容器的情况，无法连接对应的容器。

**Comment by BaiJiangJie** [comment]
第2个问题原因是，容器内没有 shell 没有办法连接。

**Comment by chown1987** [comment]
第1个问题，其它不是centos 7系统的资产是可以连接的。
第2个问题，容器内是有shell的。

**Comment by chown1987** [comment]
之前v3.x.x系列最新的版本没有遇到这两个问题

**Comment by BaiJiangJie** [comment]
两个问题都看一下 koko.log 日志。

**Comment by chown1987** [comment]
koko的日志截图如下：
![企业微信截图_20241024095330](https://github.com/user-attachments/assets/6f8231f1-daef-422b-83ff-f479c2792433)

**Comment by LeeEirc** [comment]
第一个问题：
进 koko 容器手动测试下 ssh 是否能连接上 centos 机器

```
docker exec -it jms_koko bash
ssh xxx@xxx
```
第二个问题：
可以试试 手动 docker exec -it xxx bash 的方式进容器

**Comment by chown1987** [comment]
第1个问题：
我通过docker exec命令进到jms_koko容器中，尝试用ssh命令连接目标服务器，提示没有ssh命令，安装上ssh命令后，执行ssh命令连接目标服务器，一直卡在那里不动，也没有返回信息。

第2个问题：
我用docker exec -it xxx bash方式是可以正常进到容器里边的，这个问题是在jumpserver 的k8s web终端，点开pod后，是多个容器是并排显示的，而不是像之前那样pod下显示一行一个容器，连接的时候显示多个容器一起连接，才报的连接失败的错误。

**Comment by LeeEirc** [comment]
1、ssh 卡住，说明你的网络存在问题，可以自己排查下。
2、多个容器应该是一行一个显示，截图看下你的容器显示

**Comment by chown1987** [comment]
1、ssh 卡住，说明你的网络存在问题，可以自己排查下。
PS：目前我这边连接其它目标服务器没有问题的，连接centos 7的目标服务器连不上。
2、多个容器应该是一行一个显示，截图看下你的容器显示。
PS：这个截图如下所示：
![微信截图_20241023154427](https://github.com/user-attachments/assets/66258485-5730-4ed8-ac1a-4b88aec225b2)

**Comment by feng626** [comment]
打开开发者模式 看看websocket信息 type类型是TERMINAL_K8S_TREE这个的数据 返回了什么

**Comment by chown1987** [comment]
怎样打开开发者模式？没有弄过这个。

**Comment by feng626** [comment]
![image](https://github.com/user-attachments/assets/ce93be48-4d02-4b2a-9ebb-47ee160dd2ab)

**Comment by chown1987** [comment]
我打开开发者模式，返回空白，没有TERMINAL_K8S_TREE的相关信息

**Comment by feng626** [comment]
刷新页面 让k8s的树重新生成一遍

**Comment by chown1987** [comment]
请查看，截图如下：
![企业微信截图_20241024190307](https://github.com/user-attachments/assets/2beb58e1-d724-498a-b1b5-96384b8695f3)

**Comment by feng626** [comment]
对的 
<img width="421" alt="image" src="https://github.com/user-attachments/assets/e7778ea1-84df-454a-8f06-e885057a759e">
ba把这个信息发出来看看

**Comment by chown1987** [comment]
[TERMINAL_K8S_TREE.txt](https://github.com/user-attachments/files/17518765/TERMINAL_K8S_TREE.txt)

**Comment by BaiJiangJie** [comment]
产品有 Bug，没有将多个 containers 拆分开。

**Comment by chown1987** [comment]
好的，这个bug请记得修复。
