### ISSUE TITLE
[Question] 文件管理服务接口 /koko/elfinder/connector/_/ ws长链接问题

### ISSUE THREAD

**Issue by yulinor** [jumpserver/jumpserver#14347]
### 产品版本

v4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

k8 1.27
cilium 1.14

### 🤔 问题描述

当前使用文件管理服务时，从上层文件夹一直点到最底层文件夹，接口不定时反馈400 ws already disconnected。之前v2版本的环境没有问题，甚至于将ng链路改成了使用v2版本的网络链路下发也是同样的情况。
根据在jms-web 添加 upstream_status upstream_addr 日志输出，后端都是 koko的svc，status则不定的显示400。
根据两个koko的日志，发现请求路径sid相同、其他参数不同的请求，会先后发送到不同的koko。
前几次请求到的koko-a反馈200，但是突然到了koko-b就反馈了400。

所以问题是，这个接口不论点击多少次都是要复用第一次的长链接是吧？v2 v4 版本有没有较大的改动呢

**Comment by BaiJiangJie** [comment]
是的，网络请求层面要保证同一个资产连接会话，始终代理到同一个 KoKo 后端。

**Comment by yulinor** [comment]
所以，接口请求协议https，不是wss，但是仍然要求接口始终保持到同一个koko咯，只是刚好jms-web里对koko的配置使用ws常用的ng配置

**Comment by yulinor** [comment]
> 是的，网络请求层面要保证同一个资产连接会话，始终代理到同一个 KoKo 后端。

所以，接口请求协议https，不是wss，但是仍然要求接口始终保持到同一个koko咯，只是刚好jms-web里对koko的配置使用ws常用的ng配置
