### ISSUE TITLE
[Bug] k8s 部署的jumpserver 添加资产通过文件上传的方式进行创建，下载模版修改文件后上传，无任何反应，浏览器调试模式看，无任何请求发送

### ISSUE THREAD

**Issue by bryant-rh** [jumpserver/jumpserver#14340]
### 产品版本

v4.3.0

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

k8s

### 🐛 缺陷描述

k8s 部署的jumpserver 添加资产通过文件上传的方式进行创建，下载模版修改文件后上传，无任何反应，浏览器调试模式看，无任何请求发送

### 复现步骤

上传文件方式添加资产

**Comment by wojiushixiaobai** [comment]
waf 拦截了？

**Comment by bryant-rh** [comment]
> waf 拦截了？

内网环境，直接通过nodeport方式访问的

**Comment by BaiJiangJie** [comment]
浏览器没有请求发送，Console 有报错吗？

**Comment by bryant-rh** [comment]
> 浏览器没有请求发送，Console 有报错吗？

没有，很诡异，没有请求接口，看控制台信息，也毫无报错

**Comment by BaiJiangJie** [comment]
那导入一下用户试试

**Comment by bryant-rh** [comment]
,

> 那导入一下用户试试

一样的现象，我是先下载创建模版，然后改了必填项，然后保存文件进行上传，但是依然没有任何响应

**Comment by BaiJiangJie** [comment]
手动创建资产可以吗？

**Comment by bryant-rh** [comment]
> 手动创建资产可以吗？

手动创建资产是可以正常添加

**Comment by BaiJiangJie** [comment]
导入本质上也是通过 POST 请求创建的，你在研究研究，还没有遇到过这种情况。

**Comment by bryant-rh** [comment]
> 导入本质上也是通过 POST 请求创建的，你在研究研究，还没有遇到过这种情况。

这个导入的日志是看core组件吗，我通过helm部署的，查了所有组件日志，导入的时候，都没有日志输出

**Comment by BaiJiangJie** [comment]
浏览器还没有发出请求，后端肯定没有日志。

核心问题是浏览器为什么没有发送请求。

**Comment by wojiushixiaobai** [comment]
根据描述感觉是 waf 拦截了请求，导致请求没有到堡垒机上，检查下看看。

**Comment by bryant-rh** [comment]
> 根据描述感觉是 waf 拦截了请求，导致请求没有到堡垒机上，检查下看看。

没有waf，我通过调用api创建成功了
