### ISSUE TITLE
[Question] 为什么我看不了自己作业的输出

### ISSUE THREAD

**Issue by minorCoder** [jumpserver/jumpserver#14354]
### Product Version

v4.3.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

为什么我没有权限看自己的作业的输出

### 🤔 Question Description

为什么我没有权限看自己的作业的输出

**Comment by BaiJiangJie** [comment]
提供一下报错的截图信息和复现步骤。

**Comment by minorCoder** [comment]
![image](https://github.com/user-attachments/assets/2de82758-940d-44f6-a09f-4af51d7d1906)

**Comment by minorCoder** [comment]
我就在执行列表打开，点击输出显示 no permission  这个是我账号创建的作业 执行的输出 我自己看不了

**Comment by BaiJiangJie** [comment]
用户是什么角色。

**Comment by minorCoder** [comment]
> 用户是什么角色。

![image](https://github.com/user-attachments/assets/cfdf5477-6c26-40f3-83c1-cc150fc9d75b)

**Comment by BaiJiangJie** [comment]
没能复现，这个作业是在哪儿执行的，完整的复现步骤描述一下。

**Comment by minorCoder** [comment]
我是 CAS 快速登录的用户
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/2712c771-72de-41ac-af2c-5df5dc79807e">
在这里点击创建一个定时任务
然后在执行列表里面看这个脚本运行的记录 显示的就是 no permission

如果是我直接点击运行的话 是可以看到脚本到运行日志到

**Comment by BaiJiangJie** [comment]
那问题大概定位到了，应该是定时任务的输出日志看不到。

**Comment by minorCoder** [comment]
对的  自己看不到自己定时任务的输出日志

**Comment by BaiJiangJie** [comment]
Fixed in v4.4.0
