### ISSUE TITLE
请问如何设置sudo来禁用-i -s等选项

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1435]
要求：可以无密码执行所有命令，但sudo命令的-i -s等选项除外。 
示例：/etc/sudoers
```
seven   ALL=(ALL) NOPASSWD:ALL, !/bin/sudo -i
```
按照上面这个写法是无法禁用的sudo -i，只是禁用了sudo sudo -i
那么问题来了，如何禁用sudo的选项呢？

**Comment by gengkeye** [comment]
找到了解决方法，如下：
```
seven ALL=(ALL) NOPASSWD:NOEXEC:ALL, !/bin/passwd, !/bin/chattr
```
在NOPASSWD后面追加NOEXEC标签，可以禁止用户使用其它用的shell,
参考连接：https://www.sudo.ws/man/1.8.3/sudoers.man.html

**Comment by ibuler** [comment]
应该禁用 sudo bash就行

**Comment by gengkeye** [comment]
@ibuler 禁用!/bin/bash 仍然可以sudo -i

**Comment by waxi-i** [comment]
禁用 sudo bash 可以通过 sudo sudo -i 还能行
