### ISSUE TITLE
[Bug] 作业中心的作业管理模块问题

### ISSUE THREAD

**Issue by heyonglong1221** [jumpserver/jumpserver#14350]
### Product Version

v3.10.13

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

正式使用

### 🐛 Bug Description

当我在作业管理模块执行一个任务时，这个任务是备份数据上传的，控制备份服务器将备份数据上传到我们的一个异地备份服务器上，因为网速问题，上传时间久需要7个小时左右，在上传过程中次模块整个就会发生故障，显示不出其他任务或者直接报错这样的情况，导致其他想要主动去执行的任务无法执行。我已在官方qq群反馈次问题，工作人员说让我提交问题给你们复现。
![3](https://github.com/user-attachments/assets/748e917b-782c-4aa2-b951-d45abece49a9)
![4](https://github.com/user-attachments/assets/6638b21b-9362-475f-8130-a038b3b75456)

![1](https://github.com/user-attachments/assets/a1f55a60-d1c3-40af-9623-53ffb65861f9)
![2](https://github.com/user-attachments/assets/695c2cea-0feb-44a1-ac11-5e3ff57ef9f4)

### Recurrence Steps

无

**Comment by BaiJiangJie** [comment]
查一下 core 服务的日志， jumpserver.log 日志文件

**Comment by heyonglong1221** [comment]
你好，我将日志附上，请查收
[Uploading jumpserver.log…]()

**Comment by heyonglong1221** [comment]
[jumpserver.log](https://github.com/user-attachments/files/17504102/jumpserver.log)

**Comment by BaiJiangJie** [comment]
再看一下作业管理中执行的命令内容。

**Comment by BaiJiangJie** [comment]
日志中显示有两个报错：
```
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x96 S...' for column `jumpserver`.`terminal_command`.`output` at row 1")
```
```
django.db.utils.DataError: (1406, "Data too long for column 'output' at row 1")
```

需求手动执行一下作业管理，看看日志输出。

**Comment by heyonglong1221** [comment]
具体是哪个作业呢，我这边写的作业不少
![10](https://github.com/user-attachments/assets/01f2356b-f372-4cb3-bbc8-99f7b56b65dc)
![11](https://github.com/user-attachments/assets/51cf3401-fc03-4740-9ba1-ff0f41ec5927)

**Comment by BaiJiangJie** [comment]
上面的两条报错信息，不是作业管理加载时报的，是有用户连接资产时的报错。

先看作业管理加载不出来的问题，报错时看看对应的日志输出。
