### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dragon877** [jumpserver/jumpserver#14356]
### Product Version

v4.1.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

linux 使用ｖｉｍ    命令，直接就卡死界面

### 🐛 Bug Description

linux 使用ｖｉｍ    命令，直接就卡死界面

### Recurrence Steps

linux 使用ｖｉｍ    命令，直接就卡死界面

**Comment by BaiJiangJie** [comment]
升级到 v4.3.0 解决。
