### ISSUE TITLE
[Bug] 目录名称是normalize.css，上传文件夹报错，提示 ”不能创建文件夹"" mkdir /tmp/normalize.css: not a directory“

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#14368]
### Product Version

3.10.13

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

企业版 v3.10.13

### 🐛 Bug Description

文件夹名称是normalize.css，上传文件夹报错，提示 ”不能创建文件夹"" mkdir /tmp/normalize.css: not a directory“

### Recurrence Steps

1.新建一个文件夹，名称为normalize.css，文件夹内任意放入一些文件。
2.堡垒机web端使用sftp协议打开一个linux资产。
3.选择上传文件夹normalize.css，上传时报错。
<img width="875" alt="image" src="https://github.com/user-attachments/assets/7b9902c3-abf8-4c3c-ae66-7679807b6db4">

**Comment by BaiJiangJie** [comment]
别的文件能上传吗？

**Comment by liufei20151013** [comment]
可以

**Comment by BaiJiangJie** [comment]
文件上传上来，我测试一下。

**Comment by liufei20151013** [comment]
[normalize.css.zip](https://github.com/user-attachments/files/17567078/normalize.css.zip)

**Comment by liufei20151013** [comment]
上面提出的问题我知道怎么回事了，我是先上传了一个normalize.css文件，然后再上传同名的文件夹才出现上述报错的，这个报错提示可以优化下，比如提示”当前目录已有同名文件或者文件夹“；但是在测试过程中又发现了另一个问题，我上面上传的那个压缩文件，解压后会得到一个文件夹normalize.css，这个文件夹里面有一个文件normalize.css，堡垒机选择上传文件夹normalize.css，就会出现下面的报错：
![image](https://github.com/user-attachments/assets/af2dd78d-a0c3-4872-bf66-54c11169c7d6)
文件夹里面的文件 normalize.css 上传失败并报错。
