### ISSUE TITLE
[Feature] 请问产研有没有考虑集成系统监控平台（类似蓝鲸）。

### ISSUE THREAD

**Issue by jializhu** [jumpserver/jumpserver#14362]
### 产品版本

v4

### 版本类型

- [X] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

希望实现JumpServer既可以连接资产，又可以对纳管的资产进行系统性能监控（比如内存和磁盘资源）。这样会对用户来说更加方便，对堡垒机的粘性也加大。

### 解决方案

考虑集成开源的其他平台比如Zabbix来实现以上需求。

### 补充信息

没有

**Comment by BaiJiangJie** [comment]
暂时不会考虑这个功能，不属于堡垒机产品的范畴，这就需要云管系统了。
