### ISSUE TITLE
Cannot access Web Assests in comunity edition

### ISSUE THREAD

**Issue by ousturali** [jumpserver/jumpserver#14367]
### Product Version

v4.3.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

system installed on Ubuntu server, no issues with windows or ssh to other devices.
setup a remote app machine with windows 2016 ,that server is ok, tested and verified (Load status NORMAL) adn chrome browser succeded install.

we created 2 website asset ,but cannot access them
the error screen splaashes and disappers after a couple of second later

### 🤔 Question Description

![2024-10-24_17h41_26](https://github.com/user-attachments/assets/3bcbafdc-45e3-4e1d-8478-242d8e1bffed)

**Comment by BaiJiangJie** [comment]
The reason may be that the Chrome you installed yourself overwrote the one installed by JumpServer. 
You need to uninstall the original Chrome application on Windows.
