### ISSUE TITLE
[Question] 备机通过./jmsctl.sh restore_db数据恢复后，历史会话提示：没找到录像文件

### ISSUE THREAD

**Issue by vipquan** [jumpserver/jumpserver#14369]
### 产品版本

v3.10.7

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

部署主/备双机

### 🤔 问题描述

1.备机通过./jmsctl.sh restore_db数据恢复后，历史会话提示：没找到录像文件
![WX20241028-115202@2x](https://github.com/user-attachments/assets/83bf0a50-aece-443b-b1a8-8dbdb023b467)

2../jmsctl.sh backup_db不备份历史会话录像数据吗？这个命令都备份哪些数据？

### 期望结果

1.当前版本v3.10.7如何实现备机通过./jmsctl.sh restore_db数据恢复后，查看主机历史会话录像数据？

2.当前版本v3.10.7还有其他方式可以实现查看主机历史会话录像数据吗？

3.希望./jmsctl.sh backup_db备份全量数据，备机通过./jmsctl.sh restore_db数据恢复后，可以保持和主机一样的配置。

### 补充信息
浏览器后缀和SFTP目录文件名有关联吗？
![WX20241028-160832@2x](https://github.com/user-attachments/assets/cdb1a14c-836c-4e66-9481-626b36c1b583)

**Comment by wojiushixiaobai** [comment]
录像持久化目录需要自己还原，目录可能很大所以不会备份
`/data/jumpserver/core/data`

**Comment by vipquan** [comment]
备机通过SFTP方式下载主机/data/jumpserver/core/data/media/replay/目录，有的录像可以打开有的不能打开是什么原因啊？ 确定主备机录像文件数量一致

**Comment by wojiushixiaobai** [comment]
注意文件权限

**Comment by vipquan** [comment]
> 注意文件权限，不能下载的录像可能是数据库里面标识了无法下载。

主机web页面所有文件都可以下载，备机回放正常的也可以下载，不能回放的下载不了。

**Comment by vipquan** [comment]
> 注意文件权限，不能下载的录像可能是数据库里面标识了无法下载。

主机web页面所有文件都可以下载，备机回放正常的也可以下载，不能回放的下载不了。

**Comment by wojiushixiaobai** [comment]
更新到 v3 最新版本看看，我这边测试了下没有复现这个问题

**Comment by vipquan** [comment]
> 更新到 v3 最新版本看看，我这边测试了下没有复现这个问题

恢复了几个日期的数据，发现就恢复第一次日期的数据有问题，后续恢复其他日期数据正常，不知道这算不算BUG。

**Comment by wojiushixiaobai** [comment]
大文件默认不记录，你可以参考参数文档自己定义下

**Comment by vipquan** [comment]
> 大文件默认不记录，你可以参考参数文档自己定义下

/opt/jumpserver/config/config.txt没有找到这个字段，v3.10.7是不是取消这个字段了？
![WX20241030-121402@2x](https://github.com/user-attachments/assets/59e0f758-6746-4829-b0df-f7b0b2da03f0)

**Comment by wojiushixiaobai** [comment]
默认值是 100M

**Comment by vipquan** [comment]
> 默认值是 100M

![WX20241031-155837@2x](https://github.com/user-attachments/assets/2e4955a2-9268-4b8f-b373-b522ca934324)
为什么很小的一个文件不能下载啊？

**Comment by BaiJiangJie** [comment]
提示信息有问题，默认为 0，表示不备份，所以不能下载。

配置文件配置 FTP_FILE_MAX_STORE=100，后重启服务。再试。
