### ISSUE TITLE
【安全问题】用户创建xss漏洞 附验证过程

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#1436]
[简述你的问题]

##### 使用版本
1.3.0
##### 问题复现步骤
#1383  根据 @huweiqing915 老兄提到的xss问题做了一下简单的验证

#### 1. 创建一个测试用户
![image](https://user-images.githubusercontent.com/11460661/41384407-216ab8a0-6fa8-11e8-8ea9-36db13562c67.png)

####2. 用户登陆时会提示补全信息, 登陆后用户也可以修改自己的username和name
![image](https://user-images.githubusercontent.com/11460661/41384422-3e996d7c-6fa8-11e8-9b27-794c26253747.png)

####  3. **/usr/profile** 使用了django的template没有触发
![image](https://user-images.githubusercontent.com/11460661/41384453-72f8f470-6fa8-11e8-841f-5459d409fad1.png)

####  4.  管理员用户列表界面  **/usr/usr**
![image](https://user-images.githubusercontent.com/11460661/41384478-9b646d18-6fa8-11e8-9993-b6a48adac770.png)
![image](https://user-images.githubusercontent.com/11460661/41384480-9d56d520-6fa8-11e8-8f67-c6857e3a2439.png)

#### 5. 如果打算干坏事呢？
![image](https://user-images.githubusercontent.com/11460661/41384486-abf00fb6-6fa8-11e8-8d5a-5b6b0ccd8b1e.png)

**xss平台拿到的内容, cookies等信息** 
![image](https://user-images.githubusercontent.com/11460661/41384502-bbc6ca42-6fa8-11e8-9674-fe9599275764.png)

##### 其他
**主要为/usr/usr未使用django的template且未进行转义处理.**

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
比较简单粗暴的处理方式是禁止用户自己修改用户名和名称, 
其实这个本来也没必要可以让用户修改, 至少用户名是不允许改的, 折中方式是名称允许, 用户名禁止, 用户列表table不展示名称只展示用户名 @ibuler

**Comment by ibuler** [comment]
收到，列表页用的是table的api渲染的，很有可能有问题

**Comment by ibuler** [comment]
已处理
