### ISSUE TITLE
[Bug] 开启虚拟mfa后关闭，账号列表点击查看还是需要验证

### ISSUE THREAD

**Issue by ssrsec** [jumpserver/jumpserver#14377]
### 产品版本

v4.3.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

v4.3.0，在线安装 (一键命令安装)

### 🐛 缺陷描述

开启虚拟mfa后，绑定并登录。后台关闭mfa后，账号列表点击查看还是需要验证

### 复现步骤

开启虚拟mfa后，绑定并登录。后台关闭mfa后，账号列表点击查看还是需要验证
<img width="701" alt="Google Chrome 2024-10-29 20 41 21" src="https://github.com/user-attachments/assets/8f546c92-8878-4a4d-8b3b-f029b79cd8ff">
<img width="736" alt="image" src="https://github.com/user-attachments/assets/b38ec273-dc89-409a-86df-f9ea9c0cfd4f">

**Comment by BaiJiangJie** [comment]
全局未启用，不是禁用。需要到用户详情中单个禁用。
