### ISSUE TITLE
[Bug] 用户可以查看并访问到未授权资产

### ISSUE THREAD

**Issue by jixuuse** [jumpserver/jumpserver#14382]
### Product Version

4.3.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

winrdp资产

### 🐛 Bug Description

![图片](https://github.com/user-attachments/assets/35ce9dbb-e8de-4b0e-a469-4226278e7f1a)

![图片](https://github.com/user-attachments/assets/d11b529a-5ce5-42a7-875d-70e48b9e267c)

![图片](https://github.com/user-attachments/assets/7f519268-a21a-4678-9ea6-3b60ffedadb8)

### Recurrence Steps

无

**Comment by BaiJiangJie** [comment]
导航到用户详情页面，查看用户有多少条授权规则。
