### ISSUE TITLE
[Bug] 本地Golang代码连接PgSQL失败

### ISSUE THREAD

**Issue by ChenTitan49** [jumpserver/jumpserver#14383]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [x] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Jumpserver版本：JumpServer Enterprise Edition      Version:	v3.10.13

部署架构：              jumpserver server    -> 公网网域网关 -> pgsql 

### 🐛 缺陷描述

通过Jumpserver工作台里面获得的 Database connect info 信息，本地Golang代码无法连接

### 复现步骤

登入Jumpserver ，跳转到工作台，选择要连接的PgSQL资产，

连接信息选择 Native -> DB Guide ， 本地Golang代码通过获取的DB Connect信息去调用，无法连接

### 期望结果

可以使用本地代码，通过 DB Guide 获得的信息去连接数据库

### 尝试过的解决方案

1，已经尝试过Tcp抓包处理，无法建立TCP连接；
2，已经尝试过网络防火墙，确认不是因为防火墙原因导致无法建立TCP握手；

**Comment by BaiJiangJie** [comment]
使用获取的 DB Connect 信息，通过本地客户端 Native 可以连接吗？

**Comment by ChenTitan49** [comment]
本地的Native客户端是可以连接的，因为现在有需求每天要从数据库捞数据进行分析，所以想使用Jumpserver生成的临时密钥，通过代码去连接

**Comment by BaiJiangJie** [comment]
理论上是可以的，看看 Magnus 有什么报错日志吗？

**Comment by kingcanfish** [comment]
same issue
