### ISSUE TITLE
[Question] 登录使用默认的admin/admin三次都是失败。账号被锁定

### ISSUE THREAD

**Issue by FangTangJing** [jumpserver/jumpserver#14381]
### Product Version

4.3.0

### Product Edition

- [x] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [x] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

docker部署jms_all版本v4.3.0

### 🤔 Question Description

部署成功后，打开界面登录，使用默认的账号密码admin/admin，三次均报错。然后账号被锁定三十分钟

**Comment by icpd** [comment]
我用 1panel 安装的，文档上说是 admin/admin 不行，网上搜的 ChangeMe 可以。

**Comment by wojiushixiaobai** [comment]
@icpd https://github.com/1Panel-dev/appstore/blob/dev/apps/jumpserver/README.md
看了下 1panel 里面没写错。

**Comment by wojiushixiaobai** [comment]
@icpd v4 之前的版本默认是 admin/admin，v4 开始是 admin/ChangMe，文档里面都有写

**Comment by icpd** [comment]
啊～， v4 居然没有写 1panel 的安装方式，难怪搜不到。

https://bbs.fit2cloud.com/t/topic/8553，我是在这里才知道 v4 密码的
