### ISSUE TITLE
[Bug] Safari浏览器web终端登陆失败

### ISSUE THREAD

**Issue by kubeop** [jumpserver/jumpserver#14388]
### 产品版本

4.3.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### 环境信息

官方helm chart安装，配置了linux机器，使用chrome可以登陆web终端，使用safari登陆失败

### 🐛 缺陷描述

使用chrome可以登陆web终端，使用safari登陆失败

### 复现步骤

使用chrome可以登陆web终端，使用safari登陆失败
<img width="898" alt="image" src="https://github.com/user-attachments/assets/2f686fb9-8d60-4f34-a468-0284df69966c">

**Comment by BaiJiangJie** [comment]
和部署方式没有关系，跟 Safari 浏览器对于 WebSocket 的支持有关。

建议还是使用 Chrome.
