### ISSUE TITLE
[Bug] 在使用vim时浏览器窗口缩小到比打开ssh连接时的窗口小的时候，按下浏览时会不显示，

### ISSUE THREAD

**Issue by dongpengfei1** [jumpserver/jumpserver#14398]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

![Uploading 屏幕截图(3).jpg…]()

### 🐛 缺陷描述

在使用vim时浏览器窗口缩小到比打开ssh连接时的窗口小的时候，按下浏览时会不显示，

### 复现步骤

浏览器最大化，连接主机的ssh，使用vim打开文件。缩小窗口。按下浏览。

**Comment by BaiJiangJie** [comment]
<img width="754" alt="image" src="https://github.com/user-attachments/assets/b137866c-fb8b-47e0-bdfb-6321d438fb4e">

v4.3 版本，最大化浏览器，vi 打开文件，然后缩小浏览器，按 J 向下可以一直查看。
