### ISSUE TITLE
[Question] 代理的情况下审计日志记录的IP是代理的IP

### ISSUE THREAD

**Issue by wzqiang1332** [jumpserver/jumpserver#14393]
### 产品版本

3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

linux环境使用一键部署安装，其中访问时经过了一台nginx代理服务器。

### 🤔 问题描述

审计台界面会话日志记录的IP都是代理nginx服务器IP。
手动修改了docker容器里面的jumpserver/web里面的nginx配置，将  将代理配置项proxy_set_header X-Forwarded-For $remote_addr;修改为$proxy_add_x_forwarded_for后审计会话日志可以正常记录真实IP。
一旦重启又会变成原来的。
我记得以前记录IP都是对的，最近几个版本才出现。是否有对应的config配置项来处理这个？

### 期望结果

在代理的情况下审计台记录日志的IP为真实来源IP

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/12246#issuecomment-1837971985
看下这个解决方法。
