### ISSUE TITLE
[Feature] Language PT-BR

### ISSUE THREAD

**Issue by renan-moraes1** [jumpserver/jumpserver#14396]
### Product Version

Language PT-BR

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [x] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

Language PT-BR

### Proposed Solution

Language PT-BR

**Comment by BaiJiangJie** [comment]
Anyone else want it?

Join the support program with more than 10 likes.

**Comment by BaiJiangJie** [comment]
support: https://github.com/jumpserver/jumpserver/pull/14567

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0
