### ISSUE TITLE
[Bug] LDAP 认证用户过滤器的 memberOf 无法在用户建立后控制用户能否登入

### ISSUE THREAD

**Issue by cleanwind** [jumpserver/jumpserver#14397]
### Product Version

v3.10.15

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Rocky Linux 8

### 🐛 Bug Description

用户在 Jumpserver 建立后，无法利用 用户过滤器 控制能否登入 Jumpserver 。

### Recurrence Steps

1. LDAP 用户过滤器如下配置 (&(uid=%(user)s)(memberOf=cn=cpjumpserverUser,ou=Groups,dc=ds))
2. 登入一个具备 memberOf=cn=cpjumpserverUser,ou=Groups,dc=ds 的账号，例如 test
3. LDAP 移除账号 test 的 memberOf=cn=cpjumpserverUser,ou=Groups,dc=ds
4. 期望无法登入，实际上仍能登入

**Comment by BaiJiangJie** [comment]
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/1eb77242-3183-4c43-9f5b-4d069928c46a">

设置为0，并提交后再重试。
