### ISSUE TITLE
jumpserver终端上不能粘贴

### ISSUE THREAD

**Issue by meijianwei** [jumpserver/jumpserver#1439]
[简述你的问题]
有时候在打开终端的时候，想直接copy命令粘贴，但是发现jumpserver的web终端不支持粘贴，有没有解决方案？？？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by anjia0532** [comment]
windows?支持从里往外复制文本，从外往里不支持。

**Comment by anjia0532** [comment]
linux应该支持的，我一般是<kbd>Shift</kbd>+<kbd>Insert</kbd>.

**Comment by wojiushixiaobai** [comment]
可以复制粘贴。

**Comment by meijianwei** [comment]
能提供下复制粘贴这一块功能的代码吗？非常感谢！

**Comment by ibuler** [comment]
应该是和浏览器有关系，右击看看有没有粘贴的context

**Comment by meijianwei** [comment]
应该不会吧，我用的是chrome，点击右键没有粘贴，只有复制

**Comment by vicentwu** [comment]
Windows从内到外可以，但是从外到内 右键有粘贴，但是无法粘贴，，， 是否考虑实现改功能？

**Comment by wojiushixiaobai** [comment]
@meijianwei 我听你的描述，你这是0.3的版本吗？
