### ISSUE TITLE
[Question] Connect USB Token for Server Remote through Jumpserver

### ISSUE THREAD

**Issue by tsukiazuma** [jumpserver/jumpserver#14399]
### 产品版本

v.4.1.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

- RHEL 8
- Docker 24.0.6

### 🤔 问题描述

Current Activity Flow: User's PC -> Jumpserver -> Remote Server: Window
Requirement: When the user connects the USB Token to the PC, is there a way to mount it to the Remote Server
If using "Remote Desktop Connection" then this can be done

**Comment by BaiJiangJie** [comment]
Not currently supported.

**Comment by tsukiazuma** [comment]
Thank you
