### ISSUE TITLE
[Question] api接口调用问题反馈，API 创建账号，并加密密钥信息

### ISSUE THREAD

**Issue by yuanxixue** [jumpserver/jumpserver#14390]
### 产品版本

v3.10.13

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

我通过API调用的方式添加资产账号，账号为密文，需要用到cookie中的jms_public_key，由于jms_public_key不是固定的，这样自己获取cookies加密的话是不是有些浪费资源了，我调用哪个接口获取cookies呢，实际上我调用的接口只有一个目的那就是获取cookies。但是接口返回的数据并不是我想要的，但这些数据确实占用了请求资源。

是不是可以优化一下提供一个专门加密资产账号的接口？

![企业微信截图_00ee3378-38d1-45b7-9159-b1654c44f468](https://github.com/user-attachments/assets/fdcfbd73-0968-4bec-8bff-394cf126e754)

### 解决方案

提供一个专门加密资产账号的接口？

**Comment by BaiJiangJie** [comment]
通过 API 创建账号时，可以不加密，直接传输。

**Comment by yuanxixue** [comment]
目前有要求，必须通过加密的方式去传输，有什么好的办法吗

**Comment by BaiJiangJie** [comment]
升级到 v3.10.14，全局会使用一个加密 Key，所有用户都一样，每次请求也一样。

**Comment by yuanxixue** [comment]
那这块有示例吗

**Comment by BaiJiangJie** [comment]
什么示例？

**Comment by yuanxixue** [comment]
使用密文添加账号的接口请求示例，新版本

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/blob/dev/src/utils/crypto.js#L36-L51

这就是密钥加密的过程，接口就是 /api/v1/accounts/accounts/
