### ISSUE TITLE
[Bug] Language Settings

### ISSUE THREAD

**Issue by Kevko1337** [jumpserver/jumpserver#14403]
### Product Version

v4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Windows 11 x64 and Browser Microsoft Edge

### 🐛 Bug Description

The default language in the luna website as shown in the picture is not adopted correctly. on all other pages the language is adopted correctly by the settings. if the browser cache is deleted, the language is reset and must be set again manually as shown in the picture. LANGUAGE_CODE=en and the selection of the language at login do not help
![2024-11-04_20h44_24](https://github.com/user-attachments/assets/13a13b8e-33f5-4163-804b-d1801f8923b4)

### Recurrence Steps

Set the language of the website to english and LANGUAGE_CODE=en in config.txt

### Expected Behavior

The standard language set in LANGUAGE_CODE or selected at login interface is also used correctly for this "luna"-page.

### Attempted Solutions

LANGUAGE_CODE=en in config.txt and set language english at login interface.

**Comment by BaiJiangJie** [comment]
I recommend not relying on the backend configuration LANGUAGE_CODE=en，In most cases, it is only useful for scheduled tasks on the back end, and it is recommended to set the language at the front end login.

When you set the language at page login, it will be displayed in both lina and luna.

**Comment by Kevko1337** [comment]
Thanks for the feedback, it works as you describe. The language must be clicked **again** on the login page **explitiz**, although the language is already displayed correctly on the login page, otherwise it does not work, that could be improved.

**Comment by BaiJiangJie** [comment]
Can you provide a screenshot of the browser's default language?

Also provide a recorded video with a description of the problem.

**Comment by Kevko1337** [comment]
https://github.com/user-attachments/assets/5f9c99b8-a69e-4794-8f5d-0148a179a677

Not the best quality but here a video.

**Comment by BaiJiangJie** [comment]
This is indeed an issue, as the default language for the Luna component is set to Chinese. 

It will be fixed in version v4.4.0

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/luna/pull/1181
