### ISSUE TITLE
[Question] web终端访问超时，弹窗提示登录提醒

### ISSUE THREAD

**Issue by FantasyNeurotic** [jumpserver/jumpserver#14409]
### 产品版本

v4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统: centos
浏览器: chrome

### 🤔 问题描述

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/fa7811b1-e45e-444d-90a7-13543ec7c652">

部署了jumpserver, 其他功能目前看起来都能使用，可以通过命令终端访问， 但是在页面的终端这里却受阻了，看这个接口应该最终应是要访问core:8080的，但这里在core里没看到对应日志，在web也没看到什么日志，请问下是哪里配错了么

### 期望结果

期望解决界面终端连接不了的问题

**Comment by BaiJiangJie** [comment]
页面上有什么报错吗？正常服务起来就可以连接了。

**Comment by BaiJiangJie** [comment]
看起来像是 Nginx 的问题，内置 Nginx 之上还有其他 Nginx 吗？

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/10066

是阿里云服务器吗？

**Comment by BaiJiangJie** [comment]
应该是阿里云没有及时更新的问题。
