### ISSUE TITLE
[Bug] Keyboard layout is passed incorrectly

### ISSUE THREAD

**Issue by Kevko1337** [jumpserver/jumpserver#14405]
### Product Version

v4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Windows 11 x64 German  + Microsoft Edge +  Windows Server 2022

### 🐛 Bug Description

If the web interface of the jumpserver is called on the source client with the keyboard layout qwertz and you connect to the target server via rdp, the keyboard layout is transferred as qwerty and you can't set it back to quertz.

### Recurrence Steps

Default language Qwertz client + qwertz server is transfered to qwerty via rdp.

### Expected Behavior

The keyboard layout should not be changed by the rdp session.

### Additional Information

Workaround:
Key: HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layout
Name: IgnoreRemoteKeyboardLayout
Value: 0
Type: DWORD

**Comment by BaiJiangJie** [comment]
The Web GUI allows you to set the keyboard layout in Setting on the Luna page.

<img width="1832" alt="image" src="https://github.com/user-attachments/assets/3592ff5b-76dd-45ad-836d-80a511c47175">
