### ISSUE TITLE
[Feature] SSL-Certificate via Webinterface

### ISSUE THREAD

**Issue by Kevko1337** [jumpserver/jumpserver#14404]
### Product Version

v4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

It would be nice if ssl option and the certificate could be set directly via the web interface console.

### Proposed Solution

SSL certificates could be stored more easily to reach the website via https.

**Comment by BaiJiangJie** [comment]
This parameter cannot be configured on the Web page.

You need to modify the configuration file

**Comment by Kevko1337** [comment]
Thanks for the feedback.
