### ISSUE TITLE
[Bug] 快捷命令中会将主机域名中的大写自动转换成小写导致连接资产失败

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#14416]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu22.04 
jumpserver 4.2.0

### 🐛 缺陷描述

在快捷命令中，连接以域名为主机名的资产是，主机名中的大写字母会自动转换成小写字母导致连接失败
![image](https://github.com/user-attachments/assets/9284bebf-e64c-44a2-83d2-28fce820b128)
![image](https://github.com/user-attachments/assets/6745b3c4-ca90-4270-9634-ebe8a6a40c80)

### 复现步骤

1、将资产地址写成大写域名
2、在快捷命令中连接这个资产执行命令

**Comment by ryswork1993** [comment]
这个问题可以检查验证和修复吗

**Comment by BaiJiangJie** [comment]
有可能是 ansible 的行为，你使用原生 Ansible 试试。
@ryswork1993
