### ISSUE TITLE
[Bug] 快捷命令执行交换机提示登录信息不正常

### ISSUE THREAD

**Issue by FSerKevin** [jumpserver/jumpserver#14410]
### Product Version

JumpServer 社区版 GPLv3  v4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

浏览器版本
Google Chrome
版本 128.0.6613.138（正式版本） (arm64)

### 🐛 Bug Description

进到jms_celery容器，用ssh连接交换机是正常的。
通过快捷命令执行show run 提示登录信息不正确，我该如何解决这个问题

### Recurrence Steps

![WechatIMG227](https://github.com/user-attachments/assets/bb7154e8-2dbc-476b-aeeb-fc0e941be37f)

**Comment by FSerKevin** [comment]
![WX20241106-121554@2x](https://github.com/user-attachments/assets/3e7cde56-620d-47d7-ba48-ea70aa7beb82)
通过web登录也是正常

**Comment by w940853815** [comment]
交换机具体型号是什么？

**Comment by FSerKevin** [comment]
> 交换机具体型号是什么？

BDCOM S5828

**Comment by w940853815** [comment]
使用华为平台创建下资产，再测试能否执行快捷命令

**Comment by w940853815** [comment]
资产创建选择的什么平台？

**Comment by FSerKevin** [comment]
> 资产创建选择的什么平台？

选择的General平台

**Comment by FSerKevin** [comment]
![WX20241106-182155@2x](https://github.com/user-attachments/assets/7a3b0983-2668-48b2-9fda-98fe85a6c004)
其他的交换机 使用快捷命令 信息如图，web访问正常

**Comment by w940853815** [comment]
试一下Linux平台

**Comment by FSerKevin** [comment]
> 试一下Linux平台

![1111](https://github.com/user-attachments/assets/c038645b-7198-41c7-9e60-30d75a807345)
貌似一样的信息

**Comment by FSerKevin** [comment]
![2222](https://github.com/user-attachments/assets/eaab53a5-ef42-48fd-99b3-a17a823b27a8)

**Comment by w940853815** [comment]
模块选择shell

**Comment by FSerKevin** [comment]
> 模块选择shell

![333](https://github.com/user-attachments/assets/0a58dbee-9b5f-4ae5-b427-f41a67aa7417)
应该是超时了

**Comment by FSerKevin** [comment]
![4444](https://github.com/user-attachments/assets/d60b6fbe-0c93-4a51-9981-282ede41e3af)

**Comment by FSerKevin** [comment]
![5555](https://github.com/user-attachments/assets/632aea4b-27a3-470f-807c-25a3812a01d2)
另外一台的报错

**Comment by FSerKevin** [comment]
> 模块选择shell

方便我从交流群里联系你嘛？

**Comment by w940853815** [comment]
我刚进群， 你重新发一下，我看不到之前的聊天记录

**Comment by w940853815** [comment]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/57d90975-b9ab-45d1-ae45-c9408e4c3bab">

暂未找到ansible对该厂商支持的模块
