### ISSUE TITLE
[Feature] 企业版本中工单模块新增使用用户，用于自定义审批流程

### ISSUE THREAD

**Issue by SS8-001** [jumpserver/jumpserver#14415]
### 产品版本

v3.10.13-lts

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

希望企业版本中工单模块新增使用人，用于自定义审批流程，在同一个组织内针对不同使用用户，向不同的领导小组进行审批操作。

### 解决方案

我的申请：
1、资产申请类工单支持克隆；
2、申请资产授权时，后端自动按照优先级匹配用户可用工单流程，如果没有则使用默认流程（不影响默认审批逻辑）。
流程设置-创建流程：
1、新增名称、优先级、流程使用用户字段。
流程设置-流程列表：
1、新增创建按钮。
2、返回所有流程（包括自建流程）。
3、删除自建流程。

**Comment by SS8-001** [comment]
![微信图片_20241108081848](https://github.com/user-attachments/assets/0caf69cb-3ae8-4b1f-ab21-376b2be10683)
![微信图片_20241108081846](https://github.com/user-attachments/assets/88166b53-f7c9-405d-b951-c4347d25d705)

**Comment by BaiJiangJie** [comment]
短期内不考虑。

**Comment by 7ml** [comment]
This feature is excellent, as it allows for the approval process to be differentiated based on the leadership team.

**Comment by SS8-001** [comment]
> This feature is excellent, as it allows for the approval process to be differentiated based on the leadership team.

Thank you for your support @BaiJiangJie
