### ISSUE TITLE
[Question] 3.10.10应用机部署时，下载Tinker_Installer.exe、chrome-win.zip、  chromedriver-win64.zip和dbeaver-patch.msi等文件全部提示404

### ISSUE THREAD

**Issue by JJ-SA** [jumpserver/jumpserver#14421]
### 产品版本

3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

填堡垒机域名后跳转至OSS下载Tinker_Installer.exe、chrome-win.zip、  chromedriver-win64.zip和dbeaver-patch.msi等文件，路径为[https://jms-pkg.fit2cloud.com/download/applets/Tinker_Installer.exe](https://jms-pkg.fit2cloud.com/download/applets/Tinker_Installer.exe)显示404

### 🤔 问题描述

填堡垒机域名后跳转至OSS下载Tinker_Installer.exe、chrome-win.zip、  chromedriver-win64.zip和dbeaver-patch.msi等文件，路径为[https://jms-pkg.fit2cloud.com/download/applets/Tinker_Installer.exe](https://jms-pkg.fit2cloud.com/download/applets/Tinker_Installer.exe)显示404
尝试本地下载对应文件后放到/opt/download目录下让堡垒机直接使用本地文件，但是在安装dbeaver还是提示下载文件404，dbeaver应用却已安装到应用部署机上了，推测是dbeaver-patch.msi这个文件404导致的

**Comment by ibuler** [comment]
v3 这些包，都在 jms_web 中，不会重定向到 jms-pkg，检查一下是不是 jms_web 版本不对

**Comment by JJ-SA** [comment]
使用1panel部署的，并没有独立部署jms_web，检查了jms_all的/etc/nginx/nginx.conf，/download请求本地没找到文件然后重定向到了https://static.jumpserver.org
![image](https://github.com/user-attachments/assets/fd32be6c-fa78-49d0-a34b-f8a6ae9254d0)

![image](https://github.com/user-attachments/assets/969b6c30-fa90-493f-b848-d552c3992964)

然后又被临时重定向到了jms-pkg
![image](https://github.com/user-attachments/assets/6334c771-ca77-4398-9887-92c42e1a1be0)

**Comment by BaiJiangJie** [comment]
建议升级到最新的 v4 版本吧，后期会把资源在 oss 上添加一下。

**Comment by JJ-SA** [comment]
嗯，现在可以下载了，不过上周我已经从web-static 项目把需要的文件都下下来丢容器里通过使用本地文件解决了。
