### ISSUE TITLE
[Question] Error upgrading from 4.0.2 to 4.3.1

### ISSUE THREAD

**Issue by dbrifox** [jumpserver/jumpserver#14426]
### Product Version

4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Docker compose file working on 4.0.2

services:
  core:
    image: jumpserver/core:${VERSION}
    container_name: jms_core
    command: start web
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8080/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net
  
  celery:
    image: jumpserver/core:${VERSION}
    container_name: jms_celery
    command: start task
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
    networks:
      - net

  koko:
    image: jumpserver/koko:${VERSION}
    container_name: jms_koko
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:5000/koko/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/koko/data:/opt/koko/data
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT:-2222}
    networks:
      - net

  guacd:
    image: jumpserver/guacd:1.5.5-bookworm
    container_name: jms_guacd
    user: root
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  lion:
    image: jumpserver/lion:${VERSION}
    container_name: jms_lion
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost:8081/lion/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/lion/data:/opt/lion/data
    networks:
      - net

  chen:
    image: jumpserver/chen:${VERSION}
    container_name: jms_chen
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    volumes:
      - ${VOLUME_DIR}/chen/data:/opt/chen/data
    healthcheck:
      test: "check http://localhost:8082/chen"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - net

  web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - "node.role==worker"
    env_file: .env
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "check http://localhost/api/health/"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/web/data/logs:/var/log/nginx
      - ${VOLUME_DIR}/web/download:/opt/download
    ports:
      - ${HTTP_PORT:-80}:80
    networks:
      - net
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.jump2.rule=Host("jump.xxx.com")
      - traefik.http.routers.jump2.middlewares=hsts-headers@file
      - traefik.http.routers.jump2-secure.entrypoints=https
      - traefik.http.routers.jump2-secure.rule=Host("jump.xxx.com")
      - traefik.http.routers.jump2-secure.middlewares=hsts-headers@file
      - traefik.http.routers.jump2-secure.tls=true
      - traefik.http.routers.jump2-secure.tls.certresolver=http
      - traefik.http.services.jump2.loadbalancer.server.port=80
      - traefik.docker.network=web

  redis:
    image: redis:7.0
    container_name: jms_redis
    restart: always
    command: redis-server --requirepass $REDIS_PASSWORD --loglevel warning --maxmemory-policy allkeys-lru
    environment:
      TZ: ${TZ:-America/Sao_Paulo}
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${VOLUME_DIR}/redis/data:/data
    networks:
      - net

  mysql:
    image: mariadb:10.6
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: ${TZ:-America/Sao_Paulo}
      DB_PORT: $DB_PORT
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
      MARIADB_DATABASE: $DB_NAME
      MARIADB_AUTO_UPGRADE: 1
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/mariadb/data:/var/lib/mysql
    networks:
      - net

networks:
  net:
    driver: ${NETWORK_DRIVER:-bridge}
    ipam:
      driver: default
      config:
        - subnet: $DOCKER_SUBNET
  web:
    external: true

### 🤔 Question Description

When upgrading to 4.3.1 web container is unhealthy

CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS                                 PORTS                                                                                      NAMES
8c2a3273ea6f   jumpserver/core:v4.3.1-ce         "./entrypoint.sh sta…"   About a minute ago   Up About a minute (healthy)            8080/tcp                                                                                   jms_celery
8ecac796a343   jumpserver/koko:v4.3.1-ce         "./entrypoint.sh ./k…"   About a minute ago   Up About a minute (healthy)            0.0.0.0:2221->2221/tcp, :::2221->2221/tcp, 2222/tcp                                        jms_koko
bdc0ac655fc0   jumpserver/lion:v4.3.1-ce         "./entrypoint.sh sup…"   About a minute ago   Up About a minute (healthy)            4822/tcp, 8081/tcp                                                                         jms_lion
873ee17127e2   jumpserver/chen:v4.3.1-ce         "./entrypoint.sh wisp"   About a minute ago   Up About a minute (healthy)            8082/tcp                                                                                   jms_chen
9a6306fa5969   jumpserver/web:v4.3.1-ce          "/docker-entrypoint.…"   About a minute ago   Up About a minute (unhealthy)          0.0.0.0:7004->80/tcp, :::7004->80/tcp                                                      jms_web
524e1aa1d66c   jumpserver/guacd:1.5.5-bookworm   "/bin/sh -c '/opt/gu…"   About a minute ago   Up About a minute (health: starting)   4822/tcp                                                                                   jms_guacd
dcf9e4eb34d2   jumpserver/core:v4.3.1-ce         "./entrypoint.sh sta…"   About a minute ago   Up About a minute (healthy)            8080/tcp                                                                                   jms_core
b0cc4f9d10f7   mariadb:10.6                      "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)            3306/tcp                                                                                   jms_mysql
8d824cd1836e   redis:7.0                         "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)            6379/tcp                                                                                   jms_redis

docker logs -f jms_web
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by BaiJiangJie** [comment]
Is the startup successful now?

**Comment by dbrifox** [comment]
I have roll back to 4.0.2 while investigating this issue.
