### ISSUE TITLE
[Question] 我想问一下 这个 /users/users/remove 接口的作用 是指什么？如何调用才正确呢？

### ISSUE THREAD

**Issue by xiaoxiongxyy** [jumpserver/jumpserver#14422]
### 产品版本

4.0.2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

腾讯云

### 🤔 问题描述

<img width="1513" alt="image" src="https://github.com/user-attachments/assets/fdfb6a8d-4a5d-4aa6-bcea-96289762c28b">
这个接口 能删除单独一个用户吗？传入的user和username参数是什么含义呢
我传入了user和username 参数，本来是只想删除一个测试用户的，这个接口会把所有用户移除吗？

### 期望结果

只删除一个用户

### 补充信息

无

**Comment by w940853815** [comment]
https://github.com/jumpserver/jumpserver/blob/11b3bafd5a85be84f1a726b47d9cb1dcd1021253/apps/users/models/user/_role.py#L349

将用户移除当前组织

**Comment by BaiJiangJie** [comment]
<img width="832" alt="image" src="https://github.com/user-attachments/assets/568ba113-a854-4c58-b88e-9b6b53180b08">

删除用户调这个 API，使用 DELETE 方法。地址中传入用户 id

**Comment by BaiJiangJie** [comment]
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/b4968dab-f75d-4294-b267-079d9b061df9">
