### ISSUE TITLE
[Bug] K8s duplicate message

### ISSUE THREAD

**Issue by paraddise** [jumpserver/jumpserver#14437]
### Product Version

4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

Locally on virtual machine in one-node kubernetes set up with kubeadm, kubernetes 1.31.

### 🐛 Bug Description

When you open web terminal and connect to kubernetes cluster you can get shell with kubectl and if you get this shell several time, your terminal starts repeating every line and character in console.
So if you started this shell 2 times, all you output and input in console will be duplicated.

### Recurrence Steps

1. Create Kubernetes asset
2. Connect to it with Web Terminal
3. Get the shell with kubectl
4. Get the shell in any container
5. Close the shell with kubectl
6. Again get the shell with kubectl

### Expected Behavior

In the last stepe you should get working terminal

### Additional Information

Such output I get in second time
```
Connecting to Kubernetes https://172.17.100.10:6443  0.0Connecting to Kubernetes https://172.17.100.10:6443  0.0

Welcome to JumpServer kubectl, try kubectl --help.
Welcome to JumpServer kubectl, try kubectl --help.
bash: /usr/share/bash-completion/bash_completion: No such file or directory
bash: /usr/share/bash-completion/bash_completion: No such file or directory
jumpserver-kubernetes# jumpserver-kubernetes# aassddffaassddff
bash: asdfasdf: command not found

bash: asdfasdf: command not found
jumpserver-kubernetes# jumpserver-kubernetes# llss

jumpserver-kubernetes# jumpserver-kubernetes# llss  --llaa

total 8
drwxrwxrwt 3 root         root           80 Nov 12 17:00 .
drwxr-xr-x 1 root         root         4096 Nov 12 16:23 ..
-rw-r--r-- 1 jms_k8s_user jms_k8s_user  197 Nov 12 17:00 .bashrc
drwxr-xr-x 2 jms_k8s_user jms_k8s_user   60 Nov 12 17:00 .kube
total 8
drwxrwxrwt 3 root         root           80 Nov 12 17:00 .
drwxr-xr-x 1 root         root         4096 Nov 12 16:23 ..
-rw-r--r-- 1 jms_k8s_user jms_k8s_user  197 Nov 12 17:00 .bashrc
drwxr-xr-x 2 jms_k8s_user jms_k8s_user   60 Nov 12 17:00 .kube
jumpserver-kubernetes# jumpserver-kubernetes#
```

### Attempted Solutions

If you connect to kubernetes and try to open this shell several times it will work normally.

**Comment by BaiJiangJie** [comment]
This issue will be fixed in version v4.4.0
