### ISSUE TITLE
[Bug] 添加账号密钥接口，密钥参数内容需要手动加换行符（\n）且合并为一整行，才能调用成功

### ISSUE THREAD

**Issue by hedanhedan** [jumpserver/jumpserver#14443]
### 产品版本

3.10.1

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

JumpServer 版本为 v3.10.15

### 🐛 缺陷描述

添加账号密钥接口，密钥参数直接复制密钥内容报错
![Uploading 336f2ac9bd40e5ae279ccaf5846ba28.png…]()

### 复现步骤

1. 调用创建账号密钥的接口
2. 密钥参数直接复制密钥内容报错
3. 密钥内容每行末尾加换行符，写到密钥参数里面，重新调用接口成功
![9c4eb6896cdc5c2695a23a186dd92a9](https://github.com/user-attachments/assets/81a62865-85a6-4769-85e1-947cde6736b9)

**Comment by BaiJiangJie** [comment]
通过 API 创建账号时，传入的密钥必须是一行并且确认使用了 `\n` 进行换行，`\n` 前后保证不能有空格，否则也会失败。
