### ISSUE TITLE
[Bug] 安全角色索引异常

### ISSUE THREAD

**Issue by kingofeagles** [jumpserver/jumpserver#14441]
### Product Version

4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

![QQ_1731468482483](https://github.com/user-attachments/assets/306c6435-8e7f-4641-9ed5-083e7020675c)
我选了管理员和审计员，直接显示两个审计员

### 🐛 Bug Description

估计是你们索引混乱

### Recurrence Steps

功能还能用

**Comment by w940853815** [comment]
https://github.com/jumpserver/lina/commit/65ed7217cd708d767c0ff29ce42c942f1c95743f v4.0.2已修复
