### ISSUE TITLE
[Question] The installation of ver 4.3.1 stops during "Init JumpServer Database" 

### ISSUE THREAD

**Issue by t6035dt** [jumpserver/jumpserver#14448]
### Product Version

4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 24.04

### 🤔 Question Description

The installation of ver 4.3.1 stops during "Init JumpServer Database" with error stat /var/lib/snapd/void/compose/init-db.yml and betwork.yml "No such file or directory" on Ubuntu 24.04 while the installation directory is /opt/jumpserv-installer-v4.3.1!? Any idea? Thanks

### Expected Behavior

Successful installation

**Comment by BaiJiangJie** [comment]
Can you provide a screenshot?

**Comment by et7179** [comment]
The screenshot shows a new installation with same result.

<img width="668" alt="screenshot1" src="https://github.com/user-attachments/assets/c3a2ff10-55f0-4744-9baf-9b32c8fd5a46">

**Comment by wojiushixiaobai** [comment]
Snap docker is not supported.

**Comment by et7179** [comment]
Thanks for your feedback.
Could you please inform which docker is supported? Any recommendation for having a successful installation?

**Comment by wojiushixiaobai** [comment]
[Install Docker Engine on Ubuntu](https://docs.docker.com/engine/install/ubuntu/)

**Comment by et7179** [comment]
Thanks. It is functioning now.
Case closed!
