### ISSUE TITLE
[Bug] ssh自定义端口不生效

### ISSUE THREAD

**Issue by helomng** [jumpserver/jumpserver#14447]
### Product Version

v3.10.14 lts

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [x] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

almalinux 9.4 ubuntu 2404 均存在此问题

### 🐛 Bug Description

JumpServer的3.x和4.x版本均存在的bug，在config.txt中修改了ssh端口（比如从2222到12222）.
web端可以正常连接，但是调用本地ssh工具时，仍沿用旧的端口，同时web页面的连接向导里面也显示仍为2222。

### Recurrence Steps

![image](https://github.com/user-attachments/assets/8989014a-424d-471b-b416-aedda907117f)

### Expected Behavior

应当可以自定义端口，避免部分网络环境下因为安全限制封禁了特定端口后无法修改。

**Comment by BaiJiangJie** [comment]
在终端管理-服务端点中，修改默认的端口。
