### ISSUE TITLE
[Feature]集成SupraRBI-VNC，无需部署应用发布服务器即可支持Web资源

### ISSUE THREAD

**Issue by yy8402** [jumpserver/jumpserver#14459]
### Product Version

4.3.1

### Product Edition

- [X] Community Edition
- [X] Enterprise Edition
- [X] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### ⭐️ Feature Description

当前依赖应用发布服务器提供Web资源，部署、配置和使用都比较麻烦

### Proposed Solution

集成SupraRBI-VNC，https://github.com/supraaxes/suprarbi-vnc
直接利用现有对VNC资源的支持即可全面支持Web资源，部署更简单，配置和使用更方便，用户体验更好

**Comment by BaiJiangJie** [comment]
使用 SupraRBI-VNC 的话，每一个用户每一次连接资产都会起一个容器来提供服务，会很浪费资源。还有其他方案吗？

**Comment by BaiJiangJie** [comment]
目前企业版本中同时支持 RPD 和 VNC 方式的远程应用发布，社区版仅支持 RDP 方式。
