### ISSUE TITLE
[Question] 堡垒机是否支持自动清理用户账户

### ISSUE THREAD

**Issue by xingyunliuyue** [jumpserver/jumpserver#14450]
### 产品版本

v3.10.12

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver集群式部署，使用cas做单点登录

### 🤔 问题描述

是否支持自动清理失效账户，定期检测cas账户是否存在，不在了就自动清理堡垒机上的账户

**Comment by BaiJiangJie** [comment]
可以自动禁用长时间未登录的用户，但是不会删除。
