### ISSUE TITLE
[Question] 使用4.3.1遇到登录问题

### ISSUE THREAD

**Issue by GeekHeroown** [jumpserver/jumpserver#14456]
### 产品版本

4.3.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos 8，单机在线一键安装，chrome

### 🤔 问题描述

部署好之后，创建了第一个系统用户、第一个资产(root免密登录)、第一个资产账号(root)、第一个资产授权。但是当我尝试切换至普通的系统用户界面，连接资产时，居然还会让我输入密码？？？不确认是哪里配置得有问题。

### 期望结果

普通的授权用户通过root免密登录。

### 补充信息

请查看我的所有截图，谢谢
![Uploading 11.png…]()

**Comment by GeekHeroown** [comment]
![11](https://github.com/user-attachments/assets/c3d256d1-716a-454e-a5e7-0aa97e18ab53)
![22](https://github.com/user-attachments/assets/817cd385-61f4-48f4-8b34-ba88a26980bb)
![33](https://github.com/user-attachments/assets/837d24af-3b2f-4fc7-bb09-fb1bccd7d3a9)
![44](https://github.com/user-attachments/assets/69055c6d-c0a7-4227-a57e-8ad82cef77a8)
![55](https://github.com/user-attachments/assets/761be4b0-34f0-4187-8d05-2be023d08944)
![66](https://github.com/user-attachments/assets/82516820-c3df-4cf7-90d6-7ae20d3aa00a)
![77](https://github.com/user-attachments/assets/6b04adf8-7480-48de-a96d-cea639007f55)
![88](https://github.com/user-attachments/assets/aff4049d-b80a-46b5-94cd-45b3108f36d2)
![99](https://github.com/user-attachments/assets/c9479c2b-7b3b-4ced-af47-bf3e7fd6a1b3)

**Comment by GeekHeroown** [comment]
问题已经解决，看起来是当创建资产账号时，导入私钥后，不能勾选“立即推送”，否则就会出现以上问题。

**Comment by BaiJiangJie** [comment]
是的，root 用户不用开启立即推送，其他非 root 用户创建时，如果远端服务器不存在，可以使用立即推送。
