### ISSUE TITLE
[Question] 请问，远程web应用，有些网页登录是分两步的应该怎么弄呢？

### ISSUE THREAD

**Issue by TruthInIllusion** [jumpserver/jumpserver#14458]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Chrome浏览器

### 🤔 问题描述

请教一下，在web代填的时候，有些网站的登录分两步，大致就是填入用户名后按一下按钮，然后进入密码填写，填写后再点一下按钮进行登录。这种有什么办法吗？能否给一点示例参考？谢谢。

### 期望结果

能告知我如何解决或者分享一些示例给我自己摸索。

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f

可以参考第三种代填方式，脚本代填，其中 command 有一个 sleep 的选项，target 是等待的秒数：

```
{
    "step": 4,
    "value": "",
    "target": "5",
    "command": "sleep"
}
```

比如第一个页面输入 用户名 点击下一步按钮后，可以让程序 sleep 5 s（具体场景需要的时间），然后在执行后面的步骤，比如输入密码，点击登录。

**Comment by TruthInIllusion** [comment]
> https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f
> 
> 可以参考第三种代填方式，脚本代填，其中 command 有一个 sleep 的选项，target 是等待的秒数：
> 
> ```
> {
>     "step": 4,
>     "value": "",
>     "target": "5",
>     "command": "sleep"
> }
> ```
> 
> 比如第一个页面输入 用户名 点击下一步按钮后，可以让程序 sleep 5 s（具体场景需要的时间），然后在执行后面的步骤，比如输入密码，点击登录。

我参考测试下，感谢。

**Comment by SpyFax** [comment]
> > https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f
> > 可以参考第三种代填方式，脚本代填，其中 command 有一个 sleep 的选项，target 是等待的秒数：
> > ```
> > {
> >     "step": 4,
> >     "value": "",
> >     "target": "5",
> >     "command": "sleep"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 比如第一个页面输入 用户名 点击下一步按钮后，可以让程序 sleep 5 s（具体场景需要的时间），然后在执行后面的步骤，比如输入密码，点击登录。
> 
> 我参考测试下，感谢。
> 
> 补充：经过测试，部分成功，也就是用户名填上了，但没有点击按钮，不知道是不是网页特殊的原因。不知道哪位在群晖的DSM登录页面代填成功没？

群晖 DSM 7.0 以后可以用下边的

```
[
  {
    "step": 1,
    "value": "{USERNAME}",
    "target": "name=username",
    "command": "type"
  },
  {
    "step": 2,
    "value": "",
    "target": "css=#sds-login-vue-inst > div > span > div > div.login-body-section > div.login-tab-panel > div > div.tab-wrapper > div.tab-content-ct > div > div.login-tabs-content-wrapper.login-content-section > div.login-btn > div.login-btn-spinner-wrapper",
    "command": "click"
  },
  {
    "step": 3,
    "value": "{SECRET}",
    "target": "name=current-password",
    "command": "type"
  },
  {
    "step": 4,
    "value": "",
    "target": "css=#sds-login-vue-inst > div > span > div > div.login-body-section > div.login-tab-panel > div > div.tab-wrapper > div.tab-content-ct > div > div.login-content-section > div.login-tabs-content-wrapper > div.login-btn",
    "command": "click"
  }
]
```

**Comment by TruthInIllusion** [comment]
> > > https://kb.fit2cloud.com/?p=9f9610c2-a211-4abc-8b6b-7aae7bcf3a3f
> > > 可以参考第三种代填方式，脚本代填，其中 command 有一个 sleep 的选项，target 是等待的秒数：
> > > ```
> > > {
> > >     "step": 4,
> > >     "value": "",
> > >     "target": "5",
> > >     "command": "sleep"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 比如第一个页面输入 用户名 点击下一步按钮后，可以让程序 sleep 5 s（具体场景需要的时间），然后在执行后面的步骤，比如输入密码，点击登录。
> > 
> > 
> > 我参考测试下，感谢。
> > 补充：经过测试，部分成功，也就是用户名填上了，但没有点击按钮，不知道是不是网页特殊的原因。不知道哪位在群晖的DSM登录页面代填成功没？
> 
> 群晖 DSM 7.0 以后可以用下边的
> 
> ```
> [
>   {
>     "step": 1,
>     "value": "{USERNAME}",
>     "target": "name=username",
>     "command": "type"
>   },
>   {
>     "step": 2,
>     "value": "",
>     "target": "css=#sds-login-vue-inst > div > span > div > div.login-body-section > div.login-tab-panel > div > div.tab-wrapper > div.tab-content-ct > div > div.login-tabs-content-wrapper.login-content-section > div.login-btn > div.login-btn-spinner-wrapper",
>     "command": "click"
>   },
>   {
>     "step": 3,
>     "value": "{SECRET}",
>     "target": "name=current-password",
>     "command": "type"
>   },
>   {
>     "step": 4,
>     "value": "",
>     "target": "css=#sds-login-vue-inst > div > span > div > div.login-body-section > div.login-tab-panel > div > div.tab-wrapper > div.tab-content-ct > div > div.login-content-section > div.login-tabs-content-wrapper > div.login-btn",
>     "command": "click"
>   }
> ]
> ```

太感谢了～成功了，之前折腾了好久也没成功。

再次感谢！谢谢～
