### ISSUE TITLE
[Feature] 支持ssh ca证书方式登录认证

### ISSUE THREAD

**Issue by GeekHeroown** [jumpserver/jumpserver#14454]
### 产品版本

4.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

是否可以支持第三种登陆方式，即ssh ca证书登陆。证书和密钥登陆的区别是密钥登陆需要将公钥上传到资产里，有几个密钥，就要上传几个公钥，后期运维麻烦。而证书只要往资产里导入ca公钥即可，后续使用ca签发的证书都可以登陆到资产。

### 解决方案

支持上传证书和私钥，然后使用证书和私钥登陆资产。
或者jumpserver自动生成公私钥，然后将公钥去指定的证书签发机构去申请证书，然后使用申请的证书和私钥登陆资产。

### 补充信息

之前有人提过这个需求：https://github.com/jumpserver/jumpserver/issues/13393

**Comment by BaiJiangJie** [comment]
It is not currently supported, but will be considered in a future release.

**Comment by BaiJiangJie** [comment]
In order to facilitate management, we use the previous issue together to follow up the progress.

https://github.com/jumpserver/jumpserver/issues/13393
