### ISSUE TITLE
上传文件到 windows 获得错误信息

### ISSUE THREAD

**Issue by purevita** [jumpserver/jumpserver#1445]
[问题]
上传文件到 windows 时

测试 jpg 档案可以正常上传多个

1. 但传了一个 gif 档案时出现
"You do not have permission to upload this file. If you require access, please check your system settings, or check with your system administrator." 
的错误信息

2. 以及拖拽整个文件夹时出现
"An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs."

是设定错误或是操作问题？

##### 使用版本
1.3.1

##### 具体表现
![2018-06-19 10 22 49](https://user-images.githubusercontent.com/17267802/41572503-c629efcc-73aa-11e8-9a84-1e62735a05ba.png)

**Comment by ibuler** [comment]
nginx的设置，client_max_body_size 必须要设置
```
location /guacamole/ {
    proxy_pass http://guacamole:8080/;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    client_max_body_size 1000m;
}
```

**Comment by purevita** [comment]
传档案问题已解决
另拖拽整个文件夹上传是否并不支援

**Comment by wojiushixiaobai** [comment]
@purevita 暂不支持文件拖拽上传
