### ISSUE TITLE
[Bug] 企业版客户端方式访问 Windows 资产复制文字到资产上立即丢失链接的问题

### ISSUE THREAD

**Issue by MAOUXSAKI** [jumpserver/jumpserver#14457]
### 产品版本

3.10.15

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

单节点部署的3.10.15企业版，直接从3.10.6升级上来的

### 🐛 缺陷描述

使用客户端模式连接windows server后，往内部复制任何文字就会直接断连，升级前该功能是正常的。通过web端访问windowsserver是正常的。
![image](https://github.com/user-attachments/assets/615ecdbd-b286-4ebe-8ef0-7d2ce0f8b997)

### 复现步骤

同缺陷描述

### 尝试过的解决方案

jumpserver client已经从升级好的系统中下载了最新版并安装

**Comment by BaiJiangJie** [comment]
看一下 razor 组件的日志。

**Comment by BaiJiangJie** [comment]
v3.10.16 解决。
