### ISSUE TITLE
[Feature] vscode romote ssh支持日志审计

### ISSUE THREAD

**Issue by kundisun** [jumpserver/jumpserver#14467]
### 产品版本

最新版

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

公司要求记录下连接资产时的所有操作，但目前通过vscode连接的方式只记录登录信息，不支持日志审计

### 解决方案

通过vscode连接也实现日志统计

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/13444#issuecomment-2178134310

是的，目前支持不了。

**Comment by kundisun** [comment]
那是否有可能将支持vscode登录做成对不同级别的资产可以做不同配置？比如安全级别高的资产不允许vscode登录，安全级别低的则允许？

**Comment by BaiJiangJie** [comment]
目前没有计划，要么全部可连，要么全不可连。
