### ISSUE TITLE
[Question] SSL does not work

### ISSUE THREAD

**Issue by Kevko1337** [jumpserver/jumpserver#14463]
### Product Version

v4.3.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 22.04

### 🤔 Question Description

I installed jumpserver with one-click installation and I upload the SSL files with these name (server.crt + server.key). The config.txt was edited and the services restarted with jmsctl restart. The connection via sll port 443 does not work. I get the error ERR_CONNECTION_REFUSED. Can anyone here help me or know how i can fix this?

![image](https://github.com/user-attachments/assets/68370b34-408b-4a2e-8f97-a4cbe45aa533)
![image](https://github.com/user-attachments/assets/5a42fe05-42bc-4bcd-b70e-4d4e15332361)
![image](https://github.com/user-attachments/assets/737d8a54-f013-49fd-8a36-6d9e4852b5eb)

After this website not work with 80 and 433. If i change the config.txt back to http i can open site again.

### Expected Behavior

JumpServer Website accessible via https

**Comment by Kevko1337** [comment]
![image](https://github.com/user-attachments/assets/09fabc11-ab56-430c-9963-6d176a725819)

**Comment by wojiushixiaobai** [comment]
```sh
## Nginx 配置
HTTP_PORT=80
SSH_PORT=2222
RDP_PORT=3389

## HTTPS 配置
HTTPS_PORT=443               # 对外 https 端口, 默认 443
SERVER_NAME=www.domain.com   # 你的 https 域名
SSL_CERTIFICATE=xxx.pem      # /opt/jumpserver/config/nginx/cert 目录下你的证书文件
SSL_CERTIFICATE_KEY=xxx.key  # /opt/jumpserver/config/nginx/cert 目录下你的 key 文件
```
去掉 `/opt/jumpserver/config/nginx/cert`

**Comment by Kevko1337** [comment]
Hi, thanks for the feedback. i adjusted the config.txt and restarted the services, unfortunately without success. still the same problem ERR_CONNECTION_REFUSED.

![image](https://github.com/user-attachments/assets/d456e0de-16ac-4b80-aaae-8d2cb1f4d481)

**Comment by wojiushixiaobai** [comment]
Run the following command:
```sh
./jmsctl.sh restart
docker logs -f jms_web --tail 200
```

**Comment by Kevko1337** [comment]
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] cannot load certificate "/etc/nginx/cert/server.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] cannot load certificate "/etc/nginx/cert/server.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)

**Comment by wojiushixiaobai** [comment]
`nginx: [emerg] cannot load certificate "/etc/nginx/cert/server.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM`

Check if your certificate file exists.
```sh
ls -al /opt/jumpserver/config/nginx/cert
```

**Comment by wojiushixiaobai** [comment]
See: 
- [Install Docker Engine](https://docs.docker.com/engine/install/)

**Comment by Kevko1337** [comment]
Yes the certificate exists 
![image](https://github.com/user-attachments/assets/ae4f7d74-596e-48f4-a27f-5e54f5d47add)

**Comment by wojiushixiaobai** [comment]
SSL certificate format error.
- https://stackoverflow.com/questions/51899844/nginx-ssl-no-start-line-expecting-trusted-certificate

**Comment by Kevko1337** [comment]
Thank you, i have now other. I think we come a solution closer. 
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
Enter PEM pass phrase:
nginx: [emerg] cannot load certificate key "/etc/nginx/cert/server.key": PEM_read_bio_PrivateKey() failed (SSL: error:2807106B:UI routines:UI_process:processing error:while reading strings error:0906406D:PEM routines:PEM_def_callback:problems getting password error:0907B068:PEM routines:PEM_read_bio_PrivateKey:bad password read)

**Comment by wojiushixiaobai** [comment]
Please remove the certificate's private key password protection.

**Comment by Kevko1337** [comment]
Thank you that worked. Can be closed. Have a nice day! :)
