### ISSUE TITLE
[Question] 开启了第三方认证默认是否可以设置为内置登录页面

### ISSUE THREAD

**Issue by morrow-lw-dog** [jumpserver/jumpserver#14471]
### 产品版本

v2.28

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

centos7.9

### 🤔 问题描述

我配置了keyclaok通过SAML2的方式对接，但是只想针对部分账号生效，但现在其他人访问jumpserver域名的时候，也会自动跳转到keycloak的登入页面，怎么配置只允许由keycloak发起才会跳转

### 期望结果

怎么配置只允许由keycloak发起才会跳转

**Comment by morrow-lw-dog** [comment]
开启了SAML后，访问域名会默认跳转到SAML方式登入，能设置低于本地登入的优先级吗

**Comment by BaiJiangJie** [comment]
config.txt中 设置 `LOGIN_REDIRECT_TO_BACKEND=DIRECT`
配置好后，重启服务。

这样会每次用户登录时会默认打开 JumpServer 内置的登录页面，其他用户可以点击登录按钮下方的其他认证方式跳转。
