### ISSUE TITLE
[Question] 关于调用API接口进行资产更新的问题

### ISSUE THREAD

**Issue by MabeTrue** [jumpserver/jumpserver#14478]
### 产品版本

v3

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Centos7

### 🤔 问题描述

使用/api/v1/assets/assets/ 进行资源创建之后，需要使用patch 对资源进行更新，更新时需要再将一个新账号模板和该资产关联，应该使用哪个接口进行处理呢

### 期望结果

希望能够提供一个实例代码或者提供一个可用的接口

**Comment by BaiJiangJie** [comment]
一个比较好用的方式是，你在页面上创建资产并关联账号模版时，打开浏览器控制台，通过 Network 工具栏，查看发送的 API 请求地址和数据。这样以后有其他 API 调用你想通过程序来实现也会更方便查看。

**Comment by BaiJiangJie** [comment]
POST https://yy.cmdb.cc/api/v1/accounts/accounts/

{
    "template": "7e9f48c2-5766-452e-9724-af77f7ededf2",
    "name": "F2C-Linux-root",
    "username": "root",
    "secret_type": "password",
    "privileged": true,
    "asset": "8dae34e1-0f90-4feb-b4e1-cc476231c167"
}
