### ISSUE TITLE
[Feature] 建议账号改密执行列表增加任务执行的成功和失败数列

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#14470]
### 产品版本

v3.10.15

### 版本类型

- [ ] 社区版
- [X] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

![image](https://github.com/user-attachments/assets/915c3f3f-8c75-464a-ac05-256533d27472)
账号改密执行列表只显示了任务成功执行完成，但是账号改密是否成功没有显示，需要点开详情才能看到。
如果定时任务创建的比较多，需要一个个任务点开详情，进入任务执行记录页才能看到执行情况，比较麻烦。

### 解决方案

建议增加任务执行的成功和失败数列，点击成功或者失败数，可以跳转到任务执行记录页。
![image](https://github.com/user-attachments/assets/2814ae81-4de5-4424-892e-ca165c49612c)

**Comment by BaiJiangJie** [comment]
v3 和 <= v4.4 版本暂时不考虑，将会在 PAM 重构时考虑。
