### ISSUE TITLE
创建资产授权规则为何不能只选节点

### ISSUE THREAD

**Issue by AmpletecGo** [jumpserver/jumpserver#1449]
[简述你的问题]
创建资产授权规则
只选中节点，不选资产是不会把系统用户推送到资产

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
原则上，一个授权只能同时授予一个用户或者一个组
你的问题我暂时没有发现，你可以在前台启动jumpserver，然后创建授权规则，注意看控制台输出log，有推送信息显示

**Comment by ibuler** [comment]
如果有问题请重新打开issue
