### ISSUE TITLE
cat index.html 录像无法回放

### ISSUE THREAD

**Issue by jiaxiangkong** [jumpserver/jumpserver#145]
1.wget http://www.jumpserver.org 然后cat index.html 录像无法回放

![ark 6 1wjbg 3d5iw o 5a2](https://cloud.githubusercontent.com/assets/16377458/13972850/80445608-f0d7-11e5-88bf-6ac5ebacfe0b.png)

**Comment by liuzheng712** [comment]
https://github.com/jumpserver/jumpserver/tree/TermLogRecorder
在改分支中，正在完善
