### ISSUE TITLE
[Question] ssh登录到资产自动执行指定命令或登录到资产带参数

### ISSUE THREAD

**Issue by daviadong** [jumpserver/jumpserver#14508]
### 产品版本

3.10.15

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

操作系统：centos7.6；
浏览器：chrome  130.0.6723.117
部署架构：命令一键安装

### 🤔 问题描述

目前是否支持在web页面ssh登录到资产带参数，类似使用ssh root@192.168.11.4 "uname -a"命令，登录后自动执行uname -a命令；ssh在web页面登录时没有可以配置带参数的地方，目前是否支持带参数，如何配置。

### 期望结果

我看到平台列表里面有自动化-ansible配置，是否可以在其中加配置实现web页面登录资产自动带参数。
<img width="1407" alt="截屏2024-11-21 下午6 14 12" src="https://github.com/user-attachments/assets/1d015a0e-18eb-4926-ad1e-b678013f9e6d">

**Comment by BaiJiangJie** [comment]
目前不支持配置。
