### ISSUE TITLE
Python incompatible requirement pytz==2018.3 and pytz==2017.2

### ISSUE THREAD

**Issue by ulnaz** [jumpserver/jumpserver#1451]
Just start to install with this [docs](http://docs.jumpserver.org/zh/docs/setup_by_centos7.html).
After this step # 安装 Python 库依赖
i get an error **"jumpserver-python-sdk 0.0.42 has requirement pytz==2017.2, but you'll have pytz 2018.3 which is incompatible**." 
After deleting old one and installing pytz==2017.2 i get new error  : 
**jms-storage 0.0.17 has requirement pytz==2018.3, but you'll have pytz 2017.2 which is incompatible.**

Please, help.
And one more question, is there any button to switch to english? Because your web site look translated)
Good luck!

**Comment by wojiushixiaobai** [comment]
Don't worry, this is not an error
You can continue
Good luck!

**Comment by ulnaz** [comment]
Thank for your job

**Comment by wojiushixiaobai** [comment]
@ulnaz 
After installation, the WEB interface can be based on current system settings.
Automatic language switching

![1](https://user-images.githubusercontent.com/24326988/41752681-950ec19e-75fb-11e8-9794-f9afc2454e8a.jpg)
