### ISSUE TITLE
[Bug] Warp 终端一连接上去就被断开

### ISSUE THREAD

**Issue by goodwin2077** [jumpserver/jumpserver#14525]
### Product Version

v4.2.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Centos7

### 🐛 Bug Description

wrap 终端一连接上去就被断开

Welcome to JumpServer SSH Server
Connection to x.x.x.x closed.

显示 Welcome to JumpServer SSH Server 之后马上断开

### Recurrence Steps

稳定重现

**Comment by BaiJiangJie** [comment]
是这个吗？
https://www.warp.dev/mac-terminal?gad_source=1&gclid=CjwKCAiA3ZC6BhBaEiwAeqfvyuEZfslvZ_abaYNMChzQONY8UEJg8s2EJW4hOBmr-8SsMLjXLJucRRoC40YQAvD_BwE

**Comment by goodwin2077** [comment]
> 是这个吗？ https://www.warp.dev/mac-terminal?gad_source=1&gclid=CjwKCAiA3ZC6BhBaEiwAeqfvyuEZfslvZ_abaYNMChzQONY8UEJg8s2EJW4hOBmr-8SsMLjXLJucRRoC40YQAvD_BwE

是的，其他终端工具都是正常的

**Comment by jym503558564** [comment]
设置中关掉该选项，重启下终端，再进行测试一下。
<img width="741" alt="image" src="https://github.com/user-attachments/assets/9de76e89-1695-46b0-8ad4-d26ee9e5510b">

**Comment by goodwin2077** [comment]
> 设置中关掉该选项，重启下终端，再进行测试一下。 <img alt="image" width="741" src="https://private-user-images.githubusercontent.com/40739051/390630326-9de76e89-1695-46b0-8ad4-d26ee9e5510b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzQzMzYsIm5iZiI6MTczMjc3NDAzNiwicGF0aCI6Ii80MDczOTA1MS8zOTA2MzAzMjYtOWRlNzZlODktMTY5NS00NmIwLThhZDQtZDI2ZWU5ZTU1MTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2MDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NzFmZGI2YmIxZjNhOGM1YzVhZTYyMDI1ODdlYzA5NTIzZmQ5MWZmYzFkZWRlZTQ5YjNjYzA4ZTAxMzc3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AtZryXJyzWBH8Q8A2uGTBX4I7QCedequO_UbsE8YscY">

确认这样没问题，感谢回复， 如果这是机器级别的设置就好了，这个 SSH 封装还是不错的
