### ISSUE TITLE
[Question] SECRET_KEY and BOOTSTRAP_TOKEN leaked

### ISSUE THREAD

**Issue by ohnnnooo** [jumpserver/jumpserver#14526]
### 产品版本

3.5.3

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Linux

### 🤔 问题描述

Hello,

My SECRET_KEY and BOOTSTRAP_TOKEN got leaked
What exactly can someone do if they have those, they only have that and the ip of my server where installed it

How do i proceed ? Where do i check if someone did something

**Comment by BaiJiangJie** [comment]
If the SECRET_KEY is leaked, attackers can decrypt account and password information if they gain access to your database.

If the BOOTSTRAP_TOKEN is leaked, attackers can impersonate a component to access the service.

It is recommended to update the value of the BOOTSTRAP_TOKEN and restart the service. All components will re-register, rendering the old token invalid.

Handling a SECRET_KEY leak is more challenging. The only reliable solution is to use a new database.

**Comment by ohnnnooo** [comment]
> If the SECRET_KEY is leaked, attackers can decrypt account and password information if they gain access to your database.
> 
> If the BOOTSTRAP_TOKEN is leaked, attackers can impersonate a component to access the service.
> 
> It is recommended to update the value of the BOOTSTRAP_TOKEN and restart the service. All components will re-register, rendering the old token invalid.
> 
> Handling a SECRET_KEY leak is more challenging. The only reliable solution is to use a new database.

they have no way to get access to my database so it should be fine even if i dont change it right?
as for bootstrap token they can access services without having access to anything internal like the database?

**Comment by BaiJiangJie** [comment]
> they have no way to get access to my database so it should be fine even if i dont change it right?

Yes.

**Comment by ohnnnooo** [comment]
> > as for bootstrap token they can access services without having access to anything internal like the database?
> 
> If they intend to use the BOOTSTRAP_TOKEN, they must first register a service terminal (which you can view in the system settings under the component list, such as KoKo, Lion, etc.).
> 
> You can also disable service registration in the system settings to prevent the token from being used.
> 
> <img alt="image" width="1701" src="https://private-user-images.githubusercontent.com/32935519/390369049-5287e9cc-f319-4cf9-829f-a5324b344a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDI0MDMsIm5iZiI6MTczMjc0MjEwMywicGF0aCI6Ii8zMjkzNTUxOS8zOTAzNjkwNDktNTI4N2U5Y2MtZjMxOS00Y2Y5LTgyOWYtYTUzMjRiMzQ0YTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIxMTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNjIxMDkxZmM5OTBmODhkZDZhM2I2ZTUwMGVhODg1YmFlNDUzN2FiNTMwYTVjYTQ3YmVjOGUzMGE2YzU4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FR9YVfLZMW9pVWsgTNF1Dl7l_wuZrUhqNF9vsGXuOWY">
> This way, there is essentially no risk.

but they dont have an account so they cant login, does that meant they cant register a service terminal so i dont have to change that one either?

**Comment by BaiJiangJie** [comment]
No, if they successfully register, they will become a service user and gain access to resources.

**Comment by ohnnnooo** [comment]
> No, if they successfully register, they will become a service user and gain access to resources.

But how can they register
