### ISSUE TITLE
[Bug] Remote App - Chrome applet

### ISSUE THREAD

**Issue by Kevko1337** [jumpserver/jumpserver#14539]
### Product Version

v4.4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 22.04
Windows Server 2022

### 🐛 Bug Description

When trying to connect to a  website via Applet (Chrome) out of the WebTerminal i get this error:

"Core API failed: connect API core err: No host account available, please check the applet, host and account"

The connection to the windows server machine looks ok. Local Account and Password are working.

What can i do? Thank you in advance!

The doc i followed: https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665

![error](https://github.com/user-attachments/assets/49c3aa12-22c7-4e3b-a01b-5332c66c8da7)

![2](https://github.com/user-attachments/assets/bc848616-af0d-4efa-8446-805329896f7a)
![3](https://github.com/user-attachments/assets/c6f62fc7-441f-4eb9-b534-d293295d6947)
![4](https://github.com/user-attachments/assets/93c29979-274e-4958-8259-6dd80941d9db)

I would be very grateful for support.

### Recurrence Steps

Installed remoteapp via jumpserver on Windowsserver 2022

### Expected Behavior

Website shows

**Comment by Kevko1337** [comment]
I got it to work by manually running the thinker application/service + manually adding the automatically created accounts to the group for remotedesktop authorization.

**Comment by BaiJiangJie** [comment]
That's great.
