### ISSUE TITLE
[Question]  CSRF Failed: Origin checking failed - https://172.16.18.132:18818 does not match any trusted origins.

### ISSUE THREAD

**Issue by xiao-yuluo** [jumpserver/jumpserver#14532]
### 产品版本

4.4.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

system:ubuntu24.04,chrome 

### 🤔 问题描述

![新建 BMP 图像](https://github.com/user-attachments/assets/2e7323cc-2365-4ee6-9667-ab8a567a00d9)

### 期望结果

这个问题怎么解决

**Comment by you-can-change** [comment]
如果你是在线安装的、 那么配置文件在`/opt/jumpserver/config/config.txt`、添加如下行、如果IP和端口变了、注意替换:
`DOMAINS="172.16.18.132:18818"`

然后重启下就好了、
