### ISSUE TITLE
[Question] 关于Mysql端口是否需要显式声明

### ISSUE THREAD

**Issue by ChanaLii** [jumpserver/jumpserver#14530]
### Product Version

Charts: jumpserver (v4.4.0)

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] Source Code

### Environment Information

Kubernetes版本：AWS-EKS-v1.29
Mysql版本：AWS-RDS-v8.x

### 🤔 Question Description

我们在使用外部Mysql数据源时，因为使用的是AWS-RDS云数据库，其提供的连接地址不需要port。那么我们的自定义参数安装指令要怎么配置？externalDatabase.port配置项是否需要声明？

配置一：
```
helm install jms-k8s jumpserver/jumpserver -n jump-server \
--set externalDatabase.engine=mysql \
--set externalDatabase.host=mysql-prod.cluster-12345667.us-east-1.rds.amazonaws.com/jumpserver?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai \
--set externalDatabase.port= \
--set externalDatabase.user=admin \
--set externalDatabase.password=12345678 \
--set externalDatabase.database=jumpserver 
```

配置二：
```
helm install jms-k8s jumpserver/jumpserver -n jump-server \
--set externalDatabase.engine=mysql \
--set externalDatabase.host=mysql-prod.cluster-12345667.us-east-1.rds.amazonaws.com/jumpserver?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai \
--set externalDatabase.user=admin \
--set externalDatabase.password=12345678 \
--set externalDatabase.database=jumpserver 
```

以上两种方式我们都尝试过了，提示安装失败。我们应该怎么配置？

**Comment by wojiushixiaobai** [comment]
可能不支持这种架构的数据库
