### ISSUE TITLE
[Bug] 从jumpserver-offline-installer-v3.7.1升级至jumpserver-offline-installer-v3.10.15，更改数据库结构是报错

### ISSUE THREAD

**Issue by apxx-xqy** [jumpserver/jumpserver#14538]
### Product Version

V3.10.15

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

升级前操作系统：CentOS Linux release 7.8.2003 (Core)
升级前数据库：mysql5.7
升级后操作系统：openEuler release 24.03 (LTS)
升级前数据库：mariadb10.6

### 🐛 Bug Description

MySQLdb.OperationalError: (1005, 'Can\'t create table `jumpserver`.`accounts_accountbackupautomation_obj_recipients_part_one` (errno: 150 "Foreign key constraint is incorrectly formed")')
检查后发现，表 accounts_accountbackupautomation_obj_recipients_part_one 中的 accountbackupautomation_id 列与被引用的 accounts_accountbackupautomation 表中的 id 列在字符集或排序规则（collation）上存在差异。
由于 accountbackupautomation_id 列继承了表的默认排序规则 utf8mb3_general_ci，而被引用的 id 列使用的是 utf8mb3_bin，这导致了字符集排序规则不匹配，从而无法创建外键约束。

### Recurrence Steps

cd /opt/jumpserver-offline-installer-v3.10.15
./jmsctl.sh upgrade

**Comment by BaiJiangJie** [comment]
这个很经典的一个问题，应该是你曾经某个版本恢复过数据库，恢复的时候使用 create 命令创建数据库时没有和之前的字符集保持一致。

参考这个 issue：https://github.com/jumpserver/jumpserver/issues/14211#issuecomment-2376577808

将 .sql 文件内的字符集统一后，再创建同字符集的数据库，恢复数据后再重新升级。

**Comment by apxx-xqy** [comment]
> 这个很经典的一个问题，应该是你曾经某个版本恢复过数据库，恢复的时候使用 create 命令创建数据库时没有和之前的字符集保持一致。
> 
> 参考这个 issue：[#14211 (comment)](https://github.com/jumpserver/jumpserver/issues/14211#issuecomment-2376577808)
> 
> 将 .sql 文件内的字符集统一后，再创建同字符集的数据库，恢复数据后再重新升级。
核对了备份文件jumperserver.sql 所有表的COLLATE=utf8_bin
