### ISSUE TITLE
[Feature] 邮件配置AWS SES

### ISSUE THREAD

**Issue by jzhao20230918** [jumpserver/jumpserver#14540]
### 产品版本

4.4.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

![image](https://github.com/user-attachments/assets/13001993-9d6a-405e-92ca-d0876e7d04f1)
配置邮件账号只能是个邮箱地址，但是AWS SES的账号不是个邮件地址，所以没法配置。之前哪个版本还是可以不配邮箱的。

### 解决方案

邮件账号可以不止是邮箱地址。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0

**Comment by jzhao20230918** [comment]
Hello,

Thanks for the update and I can input the SES account key and id. But  now I got an error message with "Please run connect() first". What does it mean?

**Comment by jzhao20230918** [comment]
> https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0

Hello,

Thanks for the update and I can input the SES account key and id. But now I got an error message with "Please run connect() first". What does it mean?
