### ISSUE TITLE
[Question] 请问使用模板添加账号时，在账号列表下的资产管理中怎么能一次性将需要添加的资产信息匹配到

### ISSUE THREAD

**Issue by Lynxhide** [jumpserver/jumpserver#14545]
### Product Version

v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

system version： centos7.9

### 🤔 Question Description

![image](https://github.com/user-attachments/assets/702d4dc9-7e17-4ab1-8b18-4ba6cf951ff1)

**Comment by BaiJiangJie** [comment]
直接选择可以。

**Comment by BaiJiangJie** [comment]
<img width="940" alt="image" src="https://github.com/user-attachments/assets/9e00779f-9d33-4cda-bab7-4e6df3bd43e4">

**Comment by Lynxhide** [comment]
感谢您的恢复，尝试过确实可以，请问在使用xlsx批量添加资产的时候，能否有加上账号这一栏？

**Comment by Lynxhide** [comment]
好嘞，谢谢

**Comment by Lynxhide** [comment]
其实上面这个模板选择问题，能否优化成，我输入一批ip地址或者是已存在的资产名称，然后就匹配到了资产，而不用一个个去匹配呢？谢谢

**Comment by BaiJiangJie** [comment]
目前没有了。

**Comment by Lynxhide** [comment]
后续会考虑支持吗？我觉得这个功能还是会经常用的
