### ISSUE TITLE
[Feature] 支持管理需要端口敲门的 ssh 资产

### ISSUE THREAD

**Issue by LiaoSirui** [jumpserver/jumpserver#14541]
### 产品版本

v3.10.15

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [X] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

默认 ssh 端口是关闭的，现在所有服务都是部署在 k8s 上的，具体执行的 k8s 节点无法确认

端口敲门是一种通过在预设的一组关闭端口上生成连接尝试来从外部打开防火墙端口的方法。一旦收到正确的连接尝试序列，防火墙规则就会动态修改，允许发送连接尝试的主机通过特定端口连接。此技术通常用于隐藏重要服务（例如SSH），以防止暴力破解或其他未经授权的攻击

### 解决方案

暂无

**Comment by BaiJiangJie** [comment]
我理解，在 JumpServer 中，资产连接之前使用特定的序列号“敲门”，会话结束后使用另一个序列号来“关门”。

不是只需要敲门就可以了吧。

**Comment by LiaoSirui** [comment]
> 我理解，在 JumpServer 中，资产连接之前使用特定的序列号“敲门”，会话结束后使用另一个序列号来“关门”。
> 
> 不是只需要敲门就可以了吧。

是的，但是很多时候都是根据 ip 来开启的，可以开了不关，能敲门是最基础的
