### ISSUE TITLE
[Bug] IPv6 clients unable to login starting from 4.4.1

### ISSUE THREAD

**Issue by wfjsw** [jumpserver/jumpserver#14547]
### Product Version

v4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Jumpserver is installed on a IPv6-only machine and load-balanced by nginx.

### 🐛 Bug Description

Unable to login when client ip is IPv6. Error when writing audit log.

### Recurrence Steps

1. Login with an IPv6 address

### Expected Behavior

```
jms_postgresql  | 2024-11-28 18:21:07.735 CST [335] ERROR:  invalid input syntax for type inet: "2400" at character 221
jms_postgresql  | 2024-11-28 18:21:07.735 CST [335] STATEMENT:  INSERT INTO "audits_userloginlog" ("id", "username", "type", "ip", "city", "user_agent", "mfa", "reason", "status", "datetime", "backend") VALUES ('bbfe7a8d-c711-4bab-b218-99bf951491a2'::uuid, '*', 'W', '2400'::inet, 'Unknown', '***', 1, '', true, '2024-11-28T10:21:07.734824+00:00'::timestamptz, 'Password')
```

**Comment by BaiJiangJie** [comment]
可以提供一个操作视频吗？

**Comment by BaiJiangJie** [comment]
看一下 jumpserver.log 的日志，报错信息。

**Comment by BaiJiangJie** [comment]
我找到问题了，你将下面的行修改一下，再试试。

https://github.com/jumpserver/jumpserver/blob/dev/apps/common/utils/common.py#L161

docker exec -it jms_core bash
vi apps/common/utils/common.py
(在 161 行左右)

修改
`login_ip = x_forwarded_for[0].split(":")[0]`
为
`login_ip = x_forwarded_for[0]`

然后退出容器，重启：

`docker restart jms_core`

再尝试重新登录。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/14548/files

或者，按照这样的方式修改一下。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0
