### ISSUE TITLE
更改lina NavHeader组件，build完之后部署很多jumpserver后端接口无法访问

### ISSUE THREAD

**Issue by ingoxx** [jumpserver/jumpserver#14550]
### 产品版本

Version v2.21.3 GPLv2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

build环境
windows10
node：v16.13.2
npm：8.1.2

部署环境：
centos7.9
docker 20.10.14
容器：jms_web

### 🤔 问题描述

说明：
没有更改jumpserver后端的任何接口
jms_lb容器nginx配置没有修改

问题：
在build完后部署到jms_web容器时jumpserver接口无法访问
容器jms_web的nginx配置：
server {
    listen 80;
    # listen [::]:80;

    client_max_body_size 4096m;

    location /ui/ {
        try_files $uri / /index.html;
        alias /opt/release/lina/;
    }

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
    }

    location /download/ {
        alias /opt/download/;
    }

    location /media/replay/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /media/ {
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
    }

    location /koko/ {
        proxy_pass http://koko:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /lion/ {
        proxy_pass http://lion:8081;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ignore_client_abort on;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 6000;
    }

    location /omnidb/ {
        resolver 127.0.0.11 valid=30s;
        set $upstream http://omnidb:8082;
        proxy_pass $upstream$request_uri;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /ws/ {
        proxy_pass http://core:8070;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://core:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /core/ {
        proxy_pass http://core:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }
}
![req](https://github.com/user-attachments/assets/357fb9ce-d113-41d0-bf65-fec4a6fc5169)

### 期望结果

可以访问到更新lina NavHeader组件的ui界面

### 补充信息
希望能得到一些提示，感谢
_No response_

**Comment by BaiJiangJie** [comment]
<img width="618" alt="image" src="https://github.com/user-attachments/assets/f6b4968d-b872-4a0b-960d-0a6df35f237b">

参考这两个配置，一种是直接启动的服务，一种是直接访问编译后的 lina。

**Comment by BaiJiangJie** [comment]
升级到最新版本使用吧。

**Comment by BaiJiangJie** [comment]
<img width="460" alt="image" src="https://github.com/user-attachments/assets/a78d418c-301b-4ee7-aa49-0a1b81a8d898">

编译后，放到这个目录下。

**Comment by ingoxx** [comment]
@BaiJiangJie 是直接编译好放到你说的这个目录的，你的意思是说jumpserver用最新版本对不？现在的jumpserver版本Version v2.21.3 GPLv2，要对应前端的某个lina版本么？

**Comment by BaiJiangJie** [comment]
建议直接使用离线包安装，自己编译相对复杂。
