### ISSUE TITLE
Web terminal点击隐藏左侧栏，右侧屏幕大小不自适应。

### ISSUE THREAD

**Issue by AIKiller** [jumpserver/jumpserver#1455]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Jumpserver 1.3.2 
##### 问题复现步骤
1. Web terminal 点击视图-》隐藏左边栏。
2. 右侧屏幕不自动进行大小适应

##### 具体表现[截图可能会更好些,最好能截全]
![](http://ww1.sinaimg.cn/large/93d61c99ly1fshp9bq5cuj21h70qdade.jpg)
点击隐藏之后
![](http://ww1.sinaimg.cn/large/93d61c99ly1fshpaousa0j21h70qdtaw.jpg)
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
最新版本已处理
