### ISSUE TITLE
[Question] Does the community edition support Keycloak?

### ISSUE THREAD

**Issue by MatinZ626** [jumpserver/jumpserver#14554]
### Product Version

4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Hello.
I have installed it and and wanna add keycloak for it authentication so I made some change in /opt/jumpserver/config/config.txt and  restart jmsctl.
but noting add to my login page.
![pwfiohowei](https://github.com/user-attachments/assets/3fe480af-ccfc-42c6-ad44-b7748fd97a7a)

### 🤔 Question Description

So is it even possible to integrate them? 
if the answer is yes, which part of my config in /opt/jumpserver/config/config.txt should to change?
`
OAUTH2_AUTH=true

OAUTH2_SERVER=https://MY_DOMAIN/realms/MY_REALM/protocol/openid-connect

OAUTH2_CLIENT_ID=MY_CLINETID

OAUTH2_CLIENT_SECRET=MY_SECRET
`

**Comment by BaiJiangJie** [comment]
Keycloak and OIDC authentication are enterprise features. In the community edition, support is available for LDAP, CAS, and Passkey.

**Comment by MatinZ626** [comment]
> Keycloak and OIDC authentication are enterprise features. In the community edition, support is available for LDAP, CAS, and Passkey.

Thank you.
