### ISSUE TITLE
[Bug] docker 部署的旧版本，某一天重启容器后给我更新了，然后直接开不起来.新版本的文档也没看到有支持docker部署的

### ISSUE THREAD

**Issue by wintsa123** [jumpserver/jumpserver#14566]
### 产品版本

v2

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker

### 🐛 缺陷描述

1

### 复现步骤

1

**Comment by BaiJiangJie** [comment]
长期使用，推荐使用离线安装包方式部署。
