### ISSUE TITLE
[Bug] JumpServer all-in-one安装nginx配置报错

### ISSUE THREAD

**Issue by funet8** [jumpserver/jumpserver#14570]
### Product Version

docker pull jumpserver/jms_all

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Centos7  2核4G

### 🐛 Bug Description

参考： https://github.com/jumpserver/Dockerfile/tree/master/allinone安装

docker volume create jsdata
docker volume create pgdata
docker run --name jms_all \
     -e SECRET_KEY=PleaseChangeMe \
     -e BOOTSTRAP_TOKEN=PleaseChangeMe \
     -v jsdata:/opt/data \
     -v pgdata:/var/lib/postgresql \
     -p 2222:2222 \
     -p 82:80 jumpserver/jms_all

### Recurrence Steps

报错：
/opt/web/entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] host not found in upstream "facelive" in /etc/nginx/includes/facelive.conf:2
2024-12-03 16:55:49,570 INFO exited: web (exit status 1; not expected)
2024-12-03 16:55:50,571 INFO gave up: web entered FATAL state, too many start retries too quickly

**Comment by funet8** [comment]
用容器all-in-one有个好处就是方便，但是安装之后有两个BUG。

一个是nginx的一个报错，“nginx: [emerg] host not found in upstream "facelive" in /etc/nginx/includes/facelive.conf:2”

一个是需要配置配置文件，“配置文件有问题，无法登录，请联系管理员或查看最新文档，如果你是管理员，可以更新配置文件解决，设置配置项”

**Comment by funet8** [comment]
修复nginx报错：
# docker exec -it jms_all /bin/bash
vim /etc/nginx/includes/facelive.conf
把
proxy_pass http://facelive:9999;
改成：
proxy_pass http://127.0.0.1:9999;
保存退出，再重启容器
docker restart jms_all

**Comment by funet8** [comment]
修复第二个配置项
# docker exec -it jms_all /bin/bash

vim /opt/jumpserver/apps/jumpserver/conf.py
找到 'DOMAINS': '', 这一行。
把改为：
'DOMAINS': '192.168.1.121:82', # 这里换成你的地址
保存退出
再重启容器
exit
docker restart jms_all

**Comment by BaiJiangJie** [comment]
第一个问题， facelive 的配置 @jym503558564 测试一下。
第二个问题，通过其他 IP/Domain 访问，默认是需要修改 DOMAINS 的。

**Comment by BaiJiangJie** [comment]
刚才重新构建了一下 jms_all 镜像，重新测试一下。

**Comment by funet8** [comment]
@BaiJiangJie 好的，我再构建一下看看
