### ISSUE TITLE
[Feature] 官方二级代理无法使用

### ISSUE THREAD

**Issue by armored-glitch** [jumpserver/jumpserver#14577]
### 产品版本

v4.4.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

尊敬的JumpServer团队：
        按照官方建议的二级代理配置方法进行配置，发现无效。gzip 打开会导致 sub_filter 失效 ，需要进入jms-web容器将gzip off。

### 解决方案

后续考虑将jms-web容器 nginx 的 gzip 设置为off

**Comment by BaiJiangJie** [comment]
你好，下个版本(v4.5) 支持注入环境变量来关闭：
`GZIP=off`

https://github.com/jumpserver/docker-web/pull/257/
https://github.com/jumpserver/installer/pull/504
