### ISSUE TITLE
[Bug] An SMTP account will not always have a domain

### ISSUE THREAD

**Issue by viniciusgruske** [jumpserver/jumpserver#14598]
### Product Version

4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

A dual stack installation with docker.

### 🐛 Bug Description

I have contracted an SMTP server for sending mass messages, and the credentials for this server do not involve a domain, since I can send from different domains.

However, the web form for this configuration does not allow me to enter a user without a domain.

![imagem_2024-12-05_140448537](https://github.com/user-attachments/assets/ca990f8d-86ad-49e1-a9b9-177e4ae47f45)

### Recurrence Steps

1. Login with admin account
2. Open system settings
3. Open notification settings
4. Try input and save the email config with an account without domain

**Comment by BaiJiangJie** [comment]
This restriction will be removed in version v4.5.

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0
