### ISSUE TITLE
[Question] API ?

### ISSUE THREAD

**Issue by bzctoons** [jumpserver/jumpserver#14597]
### Product Version

4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Linux Debian 12

### 🤔 Question Description

Hi, 
I would like to know if an API exists  and if the documentation exists
Thanks

**Comment by BaiJiangJie** [comment]
You can access it directly `/api/docs`, to  view the API documentation.

`https://jumpserver.com/docs`. English documentation is still being developed.

This is the Chinese document, `https://docs.jumpserver.org/`
