### ISSUE TITLE
[Question] is it possible to install jump server on specific folder? 

### ISSUE THREAD

**Issue by aryasenawiryady** [jumpserver/jumpserver#14599]
some of our servers doesn't support Internet, and we doesn't have user roles that allow us to modify some directory. ex (root/sroot),

do u have a tgz file for installation?

**Comment by BaiJiangJie** [comment]
The enterprise edition provides an offline installation package (.tar.gz format).

**Comment by aryasenawiryady** [comment]
> The enterprise edition provides an offline installation package (.tar.gz format).

where can I access this enterprise edition?

**Comment by BaiJiangJie** [comment]
You can contact and purchase by sending an email to `support@fit2cloud.com`.
