### ISSUE TITLE
【功能需求】用户权限细化以及分离：只对资产的增、删、改、查的用户，不需要登陆主机的权限

### ISSUE THREAD

**Issue by woaiyangxinyao** [jumpserver/jumpserver#1459]
[简述你的问题]
希望可以把用户权限进一步细化分离：
    只对资产进行增、删、改、查的用户，不需要登陆主机的权限（只分配给这些用户“资产管理”->“资产列表”的增删改查的权限），这样可以把一些资产登记和统计的工作交给没有主机运维经验的人员来做；

##### 使用版本
Version 1.3.2-2 GPLv2

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
权限这里确实需要优化一下，拆分权限

用户 动作 对象 
A 登录 B资产
A 修改 B资产

但是如果这样需要抽象 Role和权限点的功能

**Comment by zxl78585** [comment]
我这边创建了一个普通用户，然后，普通用户也是可以看到所有的节点的，只是没有权限登录而已，能不能让指定的人只看到指定的几个资产

**Comment by jym503558564** [comment]
目前有用户，审计员，管理员角色区分权限，可持续跟踪官网更新
