### ISSUE TITLE
[Feature] 对 JumpServer 功能的一些思考和改进

### ISSUE THREAD

**Issue by zjdc128** [jumpserver/jumpserver#14600]
### 产品版本

V3.10.14

### 版本类型

- [ ] 社区版
- [X] 企业版
- [X] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

1. 希望实现以代理的形式支持哪管goldendb数据库，而不是通过远程应用的方式。

2. 资产改密的功能，现在只能手动的选择账号，希望可以实现通过通配符匹配账号。

3. 希望实现资产和账号的定期探测，并且可以自定义探测的范围和周期，在探测到失败后，希望可以实现一键检索出来失败的资产和账号，作为待处理资产和账号，可以实现将待处理账号一键执行自动密码修改。

4. 自动化的日志太过分散，比如探测日志，自动改密日志，账号推送日志，只能在单独的功能那查看日志，不能在统一的审计台看到，希望自动化日志可以看到成功率。

5. 命令过滤的名单中的命令不连续时就不阻断；比如curl命令，在资产中输入cu""rl，c\u\r\l时就无法阻断，还是能正常执行。
![图片](https://github.com/user-attachments/assets/ebb10f3f-2f8e-4d33-baf0-52a8807d8a01)

6. 命令记录不准确，命令中存在主机名、多余回显等问题。如图，有时候就会出现记录到了主机名，有的时候就没有记录。
![图片](https://github.com/user-attachments/assets/cfc293a8-e376-44be-afa3-5ab3dd403878)

7. 图形化审计界面，现在只能记录下来输入的命令和键盘的操作，希望也可以记录下来点击元素，比如在web上点击了登录按钮，或者在系统里面点击了关机按钮等，也可以记录下来。

8. 浏览器上可以记录执行的命令和结果，支持txt文件导出。如图，比如说在红圈那可以有个勾选框，勾上之后可以把打印的回显导出为txt。V2的堡垒机应该是支持的，但是V3现在没有了。
![图片](https://github.com/user-attachments/assets/b8234a5b-9166-47d8-98f8-a4ecedf9bb79)

9. 在登录CLI界面的时候，希望可以有一个常用命令的功能，比如说在登陆交换机，Linux，数据库的时候，输入了一个很长的命令，可以记录下来，下次输入的时候可以有记忆，可以很方便的复用。

### 解决方案

1. 如上问需求描述中的记录

### 补充信息

暂无

**Comment by BaiJiangJie** [comment]
1. 提到区域客户成功部。
2. v4 将来可能会考虑。
3. v4 PAM 上线后考虑支持。
4. v4 PAM 上线后考虑支持。
5. 通过正则表达式来匹配。
6. 是否记录，主要看服务器回显，如果问题影响比较大，提给客户成功部。
7. 目前没有计划，科技达不到。
8. 暂时不考虑。
9. 作业中心-快捷命令中支持提前创建常用命令进行复用。
