### ISSUE TITLE
[Question] app.dd25a578.js:1  Uncaught SyntaxError: Unexpected token '<' 错做了一会儿控制界面后页面空白，请问是什么原因

### ISSUE THREAD

**Issue by Zhengyueewee2e** [jumpserver/jumpserver#14601]
### Product Version

v4.40

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

linux部署，外置db和redis，其他组件时docker。两台做了高可用，前面有nginx和keepalived做proxy

### 🤔 Question Description

在操作页面重命名节点，有点卡，刷新一下界面就变成全空白的了。按f5刷新没反应，关掉浏览器重启也没有反应。开无痕浏览可以正常进入登录界面

![image](https://github.com/user-attachments/assets/f353bd2c-da6e-428d-82d7-305f3bcebab9)

**Comment by Zhengyueewee2e** [comment]
清楚浏览器缓存以后就好了，请问这个可以避免吗？

**Comment by BaiJiangJie** [comment]
正常应该不会有这个问题的。

下次出现的话，打开浏览器检查，刷新页面，查看 API 或者 Console 输出什么报错。

上面图片中的 token 语法错误，看不出来。

**Comment by BaiJiangJie** [comment]
Due to the lack of reply for a long time, the issue will be temporarily closed.
