### ISSUE TITLE
windows web远程 无法录像

### ISSUE THREAD

**Issue by Nevss** [jumpserver/jumpserver#1460]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.2-2
##### 问题复现步骤
ssh 可以录像， windows不可以 看代码更新了windows录像播放。请问如何windows 远程管理录屏？

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
windows是可以录像的，我这边正常

**Comment by wojiushixiaobai** [comment]
@Nevss 确定jumpserver 、luna、和guacamole已经更新到最新版本

**Comment by gxk001** [comment]
jumpserver / coco
git log --stat
显示#1417 / #64
luna wget 1.3.2

linux ssh 录像正常；手动下载录像文件可以解压；
windows 应该是产生了录像文件，但是replay 提示无法下载，这时，
guacamole日志：
![image](https://user-images.githubusercontent.com/32119424/41901364-4ddecc22-7963-11e8-97d0-3b945270f2b0.png)
![image](https://user-images.githubusercontent.com/32119424/41901399-63b46d4a-7963-11e8-9f7a-104113256b3f.png)
![image](https://user-images.githubusercontent.com/32119424/41901431-7ac6fee4-7963-11e8-844f-8cdb16caf6d8.png)

nginx 日志：
![image](https://user-images.githubusercontent.com/32119424/41901269-0ab45052-7963-11e8-95d5-5d140fe07937.png)

手动下载录像没问题，但是无法解压，提示损坏。

**Comment by gxk001** [comment]
![image](https://user-images.githubusercontent.com/32119424/41916826-7d01e05c-798b-11e8-9762-7150e7157b63.png)

又看了下，windows 的录像文件看起来都没有被压缩（虽然后缀是gz）。
但是尝试把未压缩的文件压缩成 gz 格式的，还是提示无法下载。

可以手动下载，下载后可以正常解压。

**Comment by gxk001** [comment]
![image](https://user-images.githubusercontent.com/32119424/41950688-cbc331f0-79f9-11e8-9673-0bf2065b237d.png)


![image](https://user-images.githubusercontent.com/32119424/41950614-63672c6a-79f9-11e8-9591-a65cb4eaf6a0.png)

今天又根据guacomole-server 里 dockerfile ， yum update $RUNTIME_DENPENDENCIES $BUILD_DENPENDENCIES 
之后似乎又可以正常压缩了。

但是历史会话里 又看不到 windows  rdp 记录了？

jumpserver/ tomcat都重启了。

**Comment by Nevss** [comment]
Windows服务器是否支持录屏回放 #1353  跟这个问题是一样的 找不到windows 会话

**Comment by Nevss** [comment]
通过docker 安装的guacmole 也可以正常配置 想问一下guacmole是您那边单独修改了一个版本吗

**Comment by Nevss** [comment]
服务器版本是centos 7 其他的都是按照官网文档部署的

**Comment by Nevss** [comment]
弄好了， 原因是官网一步一步安装文档 guacamole 默认安装的是1.0.0版本 该版本无法使用windows录屏 及在线会话中windows状态显示相关功能，已提交pr。
