### ISSUE TITLE
[Bug] 认证协议在前端页面能开不能关

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#14613]
### Product Version

3.10.13

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

ubuntu docker

### 🐛 Bug Description

认证协议，比如ldap、cas，在前端页面能开不能关

### Recurrence Steps

认证协议，比如ldap、cas，在前端页面能开不能关

**Comment by BaiJiangJie** [comment]
可以关闭。

**Comment by wellsyu** [comment]
> 可以关闭。

可是我测试了，就是不能关闭。关闭按钮确实是可以滑动，但是一刷新页面就有是开着的。这个反复测试过了

**Comment by wellsyu** [comment]
> 可以关闭。

可以的，可能是昨天我测试的时候忘记提交了，以为点了关闭按钮就关闭了，不好意思。
