### ISSUE TITLE
登录日志无法获取ssh登录的用户ip地址

### ISSUE THREAD

**Issue by haofeann** [jumpserver/jumpserver#1461]
[简述你的问题]
阿里云ecs安装jumpserver, 创建好账号资产后使用ssh登录在登录日志处得到的用户ip为127.0.0.1

##### 使用版本
Jumpserver版本  1.3.2-2 GPLv2

##### 问题复现步骤
启动MFA验证以后
使用ssh登录服务器
coco上能显示客户端连接ip地址，但在登录日志处无法取得类型信息，ip也显示为127.0.0.1
web登录正常

**Comment by ibuler** [comment]
nginx tcp代理后无法获取到用户的真实ip，再等一段时间处理

**Comment by wojiushixiaobai** [comment]
@haofeann 请更新版本，已经修复。

**Comment by Coyote5** [comment]
@wojiushixiaobai 请问1.4版本这个问题修复了吗？
