### ISSUE TITLE
[Bug] 存储为Minio时，上传录像到MinIO报错

### ISSUE THREAD

**Issue by BuckHome** [jumpserver/jumpserver#14616]
### Product Version

v4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

系统：ubuntu 24.04.1

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/978eac14-f44a-4f3b-8327-edbf7f6c2038)

### Recurrence Steps

1. docker安装MinIO
2. JumpServer新增存储，选择Ceph
3. 更新组件存储为MinIO
4. 开启一个Web终端会话
5. 查看回放记录
6. 查看koko日志，发现上传MinIO报错

### Attempted Solutions

1、存储配置选择Ceph时界面添加region参数填写
2.上传到Minio时，region参数放在header请求即可

**Comment by BaiJiangJie** [comment]
按照标准的 URL 填写，region 写到 URL 中。

**Comment by BuckHome** [comment]
> 按照标准的 URL 填写，region 写到 URL 中。

https://docs.jumpserver.org/zh/v4/installation/setup_linux_lb/minio_install/?h=minio#35-minio-buckets ，我是按照这个来配置的，请问怎么修改

**Comment by aozima** [comment]
同问，如何在URL中添加region？

**Comment by aozima** [comment]
✅问题已解决，更新记录下。

如果原来的URL为 `http://10.22.2.23:9000` 或 `http://minio.test.com:9000`。
应该按下面的格式，建立1个域名解析，以实现设置 region 的目的。

新的URL为 `http://minio.region.test.com:9000`。

---

> ```go
> class ReplayStorageTypeS3Serializer(ReplayStorageTypeBaseSerializer):
>     endpoint_help_text = '''
>         S3 format: http://s3.{REGION_NAME}.amazonaws.com <br>
>         S3(China) format: http://s3.{REGION_NAME}.amazonaws.com.cn <br>
>         Such as: http://s3.cn-north-1.amazonaws.com.cn
>     '''
> 
> ```

**Comment by aozima** [comment]
至于为什么添加存储时，测试可以成功？

通过抓包发现，在测试的时候，不管URL是哪种类型，默认都按固定的us-east-1发出，然后没设置location的minio会返回成功。

如果有设置的location的，则会返回`X-Amz-Bucket-Region`，然后再次请求时，会自动修正。

抓包日志如下（只提取本话题关注的内容）

## 第1次
```
PUT /jumpserver-prod/tests.py HTTP/1.1
Host: 10.22.2.23:9000
Accept-Encoding: identity
User-Agent: Boto3/1.28.9 md/Botocore#1.31.9
X-Amz-Date: 20250508T160139Z
Authorization: AWS4-HMAC-SHA256 Credential=jumpserver-prod-wXxF/20250508/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=a49be91ca95feb302ba6c7fab21c70439c957557c06e81dc7a061ffe9d8c6ba9

HTTP/1.1 400 Bad Request
Server: MinIO
X-Amz-Bucket-Region: shenzhen
```

## 第2次自动修正
```
PUT /jumpserver-prod/tests.py HTTP/1.1
Host: 10.22.2.23:9000
User-Agent: Boto3/1.28.9
X-Amz-Date: 20250508T160140Z
X-Amz-Content-SHA256: ede2b314746fa1457415687afa770226523584a519781a0585d281d3a5066689
Authorization: AWS4-HMAC-SHA256 Credential=jumpserver-prod-wXxF/20250508/shenzhen/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=e7f48358aae97957ab67b23b53a9fd5de29233bdbdeecb35cd35a1849ce5083a
Content-Length: 363

HTTP/1.1 200 OK
Server: MinIO
Vary: Origin
X-Amz-Bucket-Region: shenzhen
```
