### ISSUE TITLE
[Bug] v4.4.0版本，前端不能滚动问题

### ISSUE THREAD

**Issue by wppzxc** [jumpserver/jumpserver#14626]
### Product Version

v4.4.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

![image](https://github.com/user-attachments/assets/bffa2fa0-4a97-4848-99c4-7d61df13209e)
如图，下面明明还有数据，但是滚动条却无法继续滚动了，缩小网页尺寸可以看到下面的内容
![image](https://github.com/user-attachments/assets/99cb69cb-633c-4fe9-8665-3de706969c9e)

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/bffa2fa0-4a97-4848-99c4-7d61df13209e)
如图，下面明明还有数据，但是滚动条却无法继续滚动了，缩小网页尺寸可以看到下面的内容
![image](https://github.com/user-attachments/assets/99cb69cb-633c-4fe9-8665-3de706969c9e)

### Recurrence Steps

将每页显示数量调整到一页显示不全需要滚动的情况下就会复现

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.4.1

Fixed in v4.4.1

**Comment by wppzxc** [comment]
我这边升级到4.4.1有问题，用的all in one镜像，什么参数都没改，4.4.1一直起不来，容器没有监听80端口，但是4.4.0版本的就没问题，请问这是什么原因

**Comment by wppzxc** [comment]
看日志也没看到什么报错，但是容器80端口就是不通

**Comment by BaiJiangJie** [comment]
https://hub.docker.com/r/jumpserver/jms_all/tags

对比一下是最新的镜像 ID 吗？

**Comment by BaiJiangJie** [comment]
长期使用的话，最好使用离线包方式部署。

**Comment by wppzxc** [comment]
好的好的
