### ISSUE TITLE
【BUG】CDN解析域名会导致LUNA无法连接LINUX资产

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1462]
version: 1.3.2
nginx中配置了域名，该域名通过公司CDN解析，发现该种情况下会导致LUNA在连接LINUX服务器时一直卡着不动。当不使用CDN解析时，可以正常连接。
另外WIN资产不受影响。

**Comment by wojiushixiaobai** [comment]
静态文件可以使用cdn，其他的需要真实的IP（CDN后，服务器真实ip不对，不能请求到真实的后端服务器，除非 后端服务器也能在公网上访问）

**Comment by gengkeye** [comment]
@wojiushixiaobai 意思是不能使用内网IP通讯吗？

**Comment by wojiushixiaobai** [comment]
@gengkeye 你理解错了，使用CDN后，你域名对应的IP就不是唯一的，你后端的IP如果不是公网，服务器怎么去联系？

**Comment by gengkeye** [comment]
@wojiushixiaobai 那为啥windows的资产可以连接呢？

**Comment by wojiushixiaobai** [comment]
@gengkeye 检查你的cdn设置，什么内容回源，什么内容缓存

**Comment by ibuler** [comment]
是否还存在问题？

**Comment by gengkeye** [comment]
@ibuler 问题依然存在，尚未解决

**Comment by wojiushixiaobai** [comment]
@gengkeye cdn 配置发下图，对于sockit url要做回源处理。

**Comment by gengkeye** [comment]
CDN的目的是为了隐藏后端IP，只能手动绑定IP和域名到hosts文件了
