### ISSUE TITLE
没有网域列表功能

### ISSUE THREAD

**Issue by 84795949** [jumpserver/jumpserver#1463]
没有网域功能

##### 使用版本
docker 镜像：registry.jumpserver.org/public/jumpserver
 Version 1.0.0-2 GPLv2.

##### 问题复现步骤
1. docker-compose 启动容器
2. 进入web界面
3.查看左侧“资产管理”一栏，没有网域列表功能

##### 具体表现
docker-compose配置文件： ![image](https://user-images.githubusercontent.com/21697438/41806717-e641f414-76f5-11e8-9a22-0a02143eed6e.png)

启动后资产管理栏目：
![image](https://user-images.githubusercontent.com/21697438/41806742-14110984-76f6-11e8-964e-e870410208b6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
网域1.1.0才加入的

**Comment by 84795949** [comment]
@jokimina 搜嘎 我用的镜像是last的，看样子docker镜像最新的镜像都没1.10咯。。
