### ISSUE TITLE
[Bug] issue with selector on websites

### ISSUE THREAD

**Issue by killmasta93** [jumpserver/jumpserver#14644]
### Product Version

v4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

using ubuntu 20-04LTS

### 🐛 Bug Description

issue with using the selector on adding the assets web such as pfSense and proxmox

### Recurrence Steps

using the default selector username and password 
![image](https://github.com/user-attachments/assets/1bfc4bfc-0ea7-4fd1-b188-4634bb19ebaa)
![image](https://github.com/user-attachments/assets/82b685e8-7bc0-4958-aa62-ba1b27aa6f96)

### Attempted Solutions

tried changing the selectors but does not work

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=9beffa46-3b58-456b-9db0-7a0b2a9cc665

You need to configure the remote application publisher.

**Comment by BaiJiangJie** [comment]
For creating a remote application publishing machine, only SSH and RDP are required. The connection process involves logging into Windows using the RDP protocol and launching the Chrome browser to access a web website.

**Comment by killmasta93** [comment]
hi thanks for the reply, so i configured the remote app, and published as now it shows the login but does not fill out
![image](https://github.com/user-attachments/assets/aa4f6186-e7b8-4858-8536-56373791176d)

![image](https://github.com/user-attachments/assets/1d08273a-9fae-49db-b25d-5c9b651d0e73)

![image](https://github.com/user-attachments/assets/116bdcea-79a0-44b4-ae36-5fa06999b7a0)

`
//*[@id="total"]/div/div[2]/div/form/input[4]`
