### ISSUE TITLE
[Bug] 用户视图下【我的资产】- Default 页面加载时间长，超过20s才显示资产清单

### ISSUE THREAD

**Issue by ttkanni** [jumpserver/jumpserver#14649]
### 产品版本

v3.10.15

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Jumpserver 在 Linux 8 虚拟机上 All in one模式部署，接入SLB负载均衡，一直运行正常。

### 🐛 缺陷描述

1，无论是管理员还是用户在【我的资产】- Default 页面加载时间特别长，超过20s，资产数仅90左右；
2，Default 页面UI加载很快，1s左右完成，但一直转圈加载各项资产清单，直到最终加载完成，资产才显示；
3，此现象在 v3.10.15每次必现，v3.10.x 之前未出现过；
4，进行了简单的定位，F12性能数据如附件：
![页面性能截图3](https://github.com/user-attachments/assets/22fc51f9-3750-410d-a0ba-92d0e04b1443)
![页面性能截图2](https://github.com/user-attachments/assets/7fcd6c99-4024-4d0c-96dc-4ccb8397920c)
![页面性能截图1](https://github.com/user-attachments/assets/507573b9-2a9f-4b79-9289-c80242bce6e5)

### 复现步骤

登录堡垒机，点击【我的资产】- Default 页面，加载时间特别长才显示全部资产

**Comment by BaiJiangJie** [comment]
浏览器控制台 - Network 中，显示哪个 API 最慢？

然后，单独刷新一下资产列表看看速度？

**Comment by ttkanni** [comment]
> 浏览器控制台 - Network 中，显示哪个 API 最慢？
> 
> 然后，单独刷新一下资产列表看看速度？

在20s之后执行的只有https://xxxx/api/v1/users/profile/（耗时650ms）和wss://xxxxx/ws/notifications/site-msg/（未完成）,见附件：
![页面性能截图4](https://github.com/user-attachments/assets/c5c31dbc-eede-42ee-ad3d-6cc69f97ab08)
![页面性能截图5](https://github.com/user-attachments/assets/62b8e391-b88c-41bf-97cc-86b9d7a13bcd)


执行最慢的参考最上面的图，抓了【性能】的图（Case里最开始的两张）

**Comment by ttkanni** [comment]
补一张这个webss执行完的图

![页面性能截图6](https://github.com/user-attachments/assets/28bf497b-a9dc-4276-886b-d783dd794e58)

**Comment by BaiJiangJie** [comment]
研究一下 site-msg 怎么这个慢？

**Comment by ttkanni** [comment]
> 研究一下 site-msg 怎么这么慢？

昨天让前端帮忙Trace了一下，这个site-msg 调用了一个js，chunk-libs.xxxx.js （参考第一、第二张图）每次都执行18+ s，不知道是做什么处理的，差不多这个时间后资产清单就能显示出来。

**Comment by BaiJiangJie** [comment]
<img width="2590" alt="image" src="https://github.com/user-attachments/assets/a92a5f70-2136-45ac-b1de-16928985ca5a" />

在我的环境中，这张是不使用 cache 的。

<img width="2595" alt="image" src="https://github.com/user-attachments/assets/66f42cb7-f658-42de-8804-2d5aea8cdfe4" />

这张是使用缓存的。

你也是分别试一下。

**Comment by BaiJiangJie** [comment]
<img width="2576" alt="image" src="https://github.com/user-attachments/assets/c9068347-6ab5-4c18-ae5f-90342b289b75" />

**Comment by ttkanni** [comment]
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/32935519/395939170-a92a5f70-2136-45ac-b1de-16928985ca5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjEzNTcsIm5iZiI6MTczNDUyMTA1NywicGF0aCI6Ii8zMjkzNTUxOS8zOTU5MzkxNzAtYTkyYTVmNzAtMjEzNi00NWFjLWIxZGUtMTY5Mjg5ODVjYTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZTg3ZGM2MDkwOGU1MjU0ZjI4M2I5ZmM1MmNhNDQxN2FmNDU5NzEwZjlkOWQxZTZhOWE2YWViOThkNzU0MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8I-IV__ZB1B7ZQQYXilS4m5bNni_QsMIqRfm27FLEoA">
> 在我的环境中，这张是不使用 cache 的。
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/32935519/395939293-66f42cb7-f658-42de-8804-2d5aea8cdfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjEzNTcsIm5iZiI6MTczNDUyMTA1NywicGF0aCI6Ii8zMjkzNTUxOS8zOTU5MzkyOTMtNjZmNDJjYjctZjY1OC00MmRlLTg4MDQtMmQ1YWVhOGNkZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmRjZjUxODAzMjBmY2E5MTE4NzJlM2QxYTVjZjZkNTU1ZmRmZjEyNDA4MTJhN2EwNjhiOWExMjgyNzFlZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pOEf5aocVL-5jWIHhoe0PuYZxjwMrdu6WFp5hpNEeJ4">
> 这张是使用缓存的。
> 
> 你也是分别试一下。

我试了下【禁用缓存】，目前看到的情况一样~
![页面性能截图7](https://github.com/user-attachments/assets/44dd8210-e807-49f0-918a-fc2b68177e3a)

明天我先查下这个websocket执行的问题，稍后反馈。

**Comment by BaiJiangJie** [comment]
截图：筛选 `chunk` 关键字 和 取消勾选禁用缓存。

**Comment by ttkanni** [comment]
@BaiJiangJie 
1，今天拿一台全新的ECS来测试，浏览器Edge/Chrome默认初始配置，无问题。

2，用办公电脑Edge/Chrome测试发现 F12-性能，发现“脚本执行”占用了86%时间，偶然间想到可能是浏览器插件导致，逐一开启插件测试，发现开启 **AdGuard 浏览器扩展** 后问题复现。例外Jumpserver网站后，恢复正常。

最终原因---AdGuard 浏览器扩展
