### ISSUE TITLE
[Bug] Windows 10 PIN 下无法添加 Passkeys，返回: {"error": "Server internal error"}

### ISSUE THREAD

**Issue by hho2002** [jumpserver/jumpserver#14645]
### Product Version

v4.4.1

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

AlmaLinux 9

### 🐛 Bug Description

authentication_passkey token 字段默认长度 255 太小，修改为 1000 可正常添加 passkey

### Recurrence Steps

jumpserver.log 异常信息：
```
[ERRO] Internal Server Error: /api/v1/authentication/passkeys/register/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)
```

**Comment by BaiJiangJie** [comment]
你的 Token 是多长的？

v4.5 中会修改为 1024。

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/14647

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v4.5.0
