### ISSUE TITLE
网域包含多个不同网段的网关时不能连接资产

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1465]
版本1.3.1
问题描述：一个机房有两个内网网段，这样需要在该机房对应的网域添加两个网关，但是这样会导致资产无法连接。一个网域只添加一个网关时没有问题。

**Comment by jokimina** [comment]
错误提示信息或者操作时对应后台的日志呢...不一定能复现的, 让人咋猜呢

**Comment by gengkeye** [comment]
@jokimina 这个是之前遇到的，当时没有截取日志

**Comment by gengkeye** [comment]
又测试了一下，当一个网域包含两个不通网段的网关时，会导致资产无法连接。

**Comment by ibuler** [comment]
网域问题可能是由于当时的bug存在的，现在应该没问题了

如果有问题请重新打开issue
