### ISSUE TITLE
[Question] 关于Windows SFTP功能相关问题

### ISSUE THREAD

**Issue by huangsijun17** [jumpserver/jumpserver#14658]
### 产品版本

v3.10.10

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

被控为Windows Server 2016，安装有：

> OpenSSH_for_Windows_9.4p1, LibreSSL 3.7.3
> sftp-server 9.4.0.0

### 🤔 问题描述

通过不同渠道传入文件的位置不统一，不便于批量控制。
渠道一：SFTP，传入位置未找到。
渠道二：批量文件传输（ansible），传入位置 C:\tmp\。
渠道三：RDP，传入位置，映射的网络驱动器。

### 期望结果

统一各种方式传入的文件位置，便于使用ansible、ssh批量处理。

**Comment by BaiJiangJie** [comment]
第 1、2 种：SFTP 默认位置也是 /tmp/，不同类型的资产在平台中都可以设置。
第 3 种：挂载方式。
