### ISSUE TITLE
[Bug] 4.x Postgresql web ui直连方式, 无录像, 无法监控

### ISSUE THREAD

**Issue by sunyakun00** [jumpserver/jumpserver#14661]
### 产品版本

4.2.0

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jms_all镜像, docker 启动的

### 🐛 缺陷描述

如题, 升级到4.0.3(问题一直到4.4.1依然存在)之后, 连Postgresql使用web ui的方式的话, 监控按钮是灰色, 历史会话的回访是空白的
![V7r5qbdBGg](https://github.com/user-attachments/assets/be9a86d4-145f-4210-8f86-7b5f6d8da8af)
![Sn11kwNMpX](https://github.com/user-attachments/assets/4196058c-cb1d-4ad8-aa01-787070f668f8)

### 复现步骤

创建资产时候, 选择 数据库->Postgresql类型
连接资产时候, 选择 Web->Web GUI

### 期望结果

可以监控和录像回放

**Comment by BaiJiangJie** [comment]
先不说监控和回放的问题，用户能成功连接资产并执行操作吗？

**Comment by sunyakun00** [comment]
> 先不说监控和回放的问题，用户能成功连接资产并执行操作吗？
> 
> 或者你使用离线安装包部署一下。

操作是没问题的, Web CLI 和 Web GUI 的方式, 都可以. Web CLI有录像和监控, 不过我没搞明白怎么导出csv的查询结果. Web GUI的方式可以导出, 但是没有监控和录像.

**Comment by BaiJiangJie** [comment]
其他类型的数据库，使用 Web GUI 方式连接，有录像吗？

**Comment by BaiJiangJie** [comment]
我刚才使用最新的 v4.4.1 版本测试，没问题，有录像的。

或者你升级到最新版本试试，当前版本的话，会话关闭时查看一下 chen 组件的日志，有没有录像上传相关的报错信息。

**Comment by sunyakun00** [comment]
> 我刚才使用最新的 v4.4.1 版本测试，没问题，有录像的。
> 
> 或者你升级到最新版本试试，当前版本的话，会话关闭时查看一下 chen 组件的日志，有没有录像上传相关的报错信息。

这就有意思了, 我刚刚创建了一个全新的VM,使用最新的4.4.1的quick_start.sh走的全默认设置,创建了一个新环境.
请看截图:
![o7ZMmElOlK](https://github.com/user-attachments/assets/8dd2426d-0d73-433f-aa11-91f1773c9cf6)
![a2ZHTxBA7h](https://github.com/user-attachments/assets/add78e43-51ba-4520-84b9-932d21440bbf)
![tJw5ZwcEdC](https://github.com/user-attachments/assets/4782a34e-11b3-4994-a1aa-f355b5410e81)

**Comment by sunyakun00** [comment]
> 其他类型的数据库，使用 Web GUI 方式连接，有录像吗？

我试了一下mysql, Web GUI方式, 监控按钮也是会掉的.
![Uploading NVuwD2xvqS.png…]()

**Comment by sunyakun00** [comment]
> 我刚才使用最新的 v4.4.1 版本测试，没问题，有录像的。
> 
> 或者你升级到最新版本试试，当前版本的话，会话关闭时查看一下 chen 组件的日志，有没有录像上传相关的报错信息。

会话连接的时候,监控是灰色, 会话关闭的时候, chen的wisp.log里是有日志的, 而且录像文件也上传了. 
录像压缩文件也是有的
![TU8A619Cxi](https://github.com/user-attachments/assets/7c197516-40b5-4626-a195-48ddbad85ae9)

但是录像回放是空白内容:
![ZkdDXTW4qY](https://github.com/user-attachments/assets/f1d725ad-cd4d-43ad-b155-4dea1901e2cb)

**Comment by BaiJiangJie** [comment]
Web GUI 方式的数据库连接，不支持监控。

你执行了命令之后，才会有录像回放。

**Comment by sunyakun00** [comment]
> Web GUI 方式的数据库连接，不支持监控。
> 
> 你执行了命令之后，才会有录像回放。

好吧, 还真是, 之前以为会录屏幕呢. 多谢多谢.
