### ISSUE TITLE
[Question] How to get api token via user-pass and MFA?

### ISSUE THREAD

**Issue by SnelsSM** [jumpserver/jumpserver#14665]
### Product Version

v4.4.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Ubuntu 22.04
docker 27.1.1

### 🤔 Question Description

The api authentication question for a user with multi-factor authentication has already been asked in issue [#14058](https://github.com/jumpserver/jumpserver/issues/14058).
However, no working solution was proposed. And the issue was closed.

The API documentation also does not describe a solution to this issue.

What is the way to get an API access token when using a username-password+MFA?

```bash
curl -X POST https://jump.xxxxx/api/v1/authentication/auth/ -H 'Content-Type: application/json' -d '{"username": "xxxx", "password": "yyyy"}'
{"error":"mfa_required","msg":"MFA required","data":{"choices":["otp"],"url":"/api/v1/authentication/mfa/challenge/"}}

curl -X POST https://jump.xxxxx/api/v1/authentication/mfa/verify/ -H 'Content-Type: application/json' -d '{"code":"016675"}'
{"detail":"Authentication credentials were not provided.","code":"not_authenticated"}
```
So... How to pass authentication credentials to /api/v1/authentication/mfa/verify/ ?
And what is the right way to solve this issue and get token?

**Comment by SnelsSM** [comment]
It was only necessary to ask a question and I figured out how to solve the problem =)

```bash
curl -v -X POST https://jump.xxxxx/api/v1/authentication/auth/ -H 'Content-Type: application/json' -d '{"username": "xxxx", "password": "yyyy"}'
# get jms_sessionid cookie from ansver
curl -X POST --cookie 'jms_sessionid=xxxxxxx' https://jump.xxxxx/api/v1/authentication/mfa/verify/ -H 'Content-Type: application/json' -d '{"type":"otp","code":"452184"}'
```
It looks like everything is OK.

**Comment by iriskins** [comment]
I'm trying to use your method, but in response I get {"msg":"ok"}
