### ISSUE TITLE
[Bug] 工单审批选择指定账号时无可选账号

### ISSUE THREAD

**Issue by gerry-f2c** [jumpserver/jumpserver#14675]
### Product Version

v3.10.16

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

单机部署，Chrome 新版

### 🐛 Bug Description

管理人员进行工单审批时，修改账号为“指定账号”，可选列表会闪现账号列表，然后就没有可选值了，同一个资产在创建授权规则时设置“指定账号”是有可选账号的

### Recurrence Steps

1、多组织，例如 A、B
2、用户申请 A 组织资产授权
3、审批人在 B 组织工作，此时打开站内信工单进行审批，就会出现如上所述问题

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/4525

Fixed in v4.5.0.

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/lina/pull/4526

Fixed in v3.10.17.
