### ISSUE TITLE
[Bug] Pending Upload File via File Transfer

### ISSUE THREAD

**Issue by sakd3rmo** [jumpserver/jumpserver#14708]
### Product Version

v.4.5.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
JumpServer: v.4.5.0

### 🐛 Bug Description

I have installed v4.5.0, and I tried to upload a file using Workbench File Transfer. The result shows as Pending with the output "Status: Success: 0 Skip this asset: 0 Failed: 0 Time cost: 0.00." 

How can I fix this?

### Recurrence Steps

**Procedure:**

1. Log in as an Administrator.
2. Navigate to the Workbench Console.
3. Select the File Transfer feature.
4. Choose an asset, upload a file, and the result is Pending.

![Screenshot 2024-12-20 141833](https://github.com/user-attachments/assets/5122a661-af6a-4563-ab03-e0457af65137)

### Expected Behavior

Can upload file via Workbench File Transfer

**Comment by w940853815** [comment]
What is the asset type?

**Comment by w940853815** [comment]
What did the browser request `ws/ops/tasks/log/` output?

**Comment by sakd3rmo** [comment]
Type Asset : Platform Ubuntu
Output : 
`/data/jumpserver/core/data/logs/celery_ansible.log `
Task ops.tasks.run_ops_job_execution[557f0eaf-32c1-4b30-b95e-8d03c3a13f04] succeeded in 1.0261953030003497s: None

![Screenshot 2024-12-20 164758](https://github.com/user-attachments/assets/3329547c-07c5-494a-98a9-8d90f08f2e44)

**Comment by w940853815** [comment]
In System Settings- Feature -Job center- Adhoc, check this. And then try the file transfer again.

**Comment by sakd3rmo** [comment]
Thank you
It's work

**Comment by w940853815** [comment]
fix https://github.com/jumpserver/jumpserver/pull/14716
