### ISSUE TITLE
[Question] JumpServer server requirement

### ISSUE THREAD

**Issue by aryasenawiryady** [jumpserver/jumpserver#14718]
### Product Version

Latest

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

Linux Server

### 🤔 Question Description

What are the specifications or server requirements for jumpserver?
example =  OS version, Cpu cores, Ram, etc
minimum, recommended, and best practice.

**Comment by BaiJiangJie** [comment]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/1f4255fc-abd8-44b4-bd0e-2d6d1ad27ae1" />

https://www.jumpserver.com/docs/installation

**Comment by BaiJiangJie** [comment]
There are no other restrictions.
