### ISSUE TITLE
[Feature] 提供SSO功能的建议

### ISSUE THREAD

**Issue by wellsyu** [jumpserver/jumpserver#14721]
### 产品版本

3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### ⭐️ 需求描述

个人觉得jumpserver 础了堡垒机功能外，只差少许功能，也能成为keycloak一样的认证授权中心。堡垒机功能大部分是在jumpserver里面管理资产，如果同时也是是认证授权中心，可以管理授权公司无需在堡垒机里面管理的资产。
个人粗见，不知道有没有这方面的打算

### 解决方案

无

**Comment by BaiJiangJie** [comment]
感谢提问，暂时没有计划。
