### ISSUE TITLE
[Question] V3.10.15升级V3.10.16后设置新增加的用户仅拥有两个资产权限，但实际拥有所有资产权限

### ISSUE THREAD

**Issue by tianmaxingkong168** [jumpserver/jumpserver#14737]
### Product Version

V3.10.16

### Product Edition

- [ ] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

1、os: Openeuler22.03sp04

### 🤔 Question Description

V3.10.15升级V3.10.16后设置新增加的用户仅拥有两个资产权限，但实际拥有所有资产权限

### Expected Behavior

新增加的用户仅拥有设置的资产权限。

**Comment by Ewall555** [comment]
是否添加了用户组进去或者添加了节点给用户，截图看一下资产授权配置

**Comment by tianmaxingkong168** [comment]
原来是添加了用户组。
