### ISSUE TITLE
[Question] Docker容器作为网域Gateway时，需要安装哪些服务？

### ISSUE THREAD

**Issue by akang1798** [jumpserver/jumpserver#14735]
### 产品版本

v3.10.14

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

运行堡垒机的操作系统：RockyLinux9
Docker版本：26.1.2

### 🤔 问题描述

1、背景：
1.1、早前运行Jumpserver的CentOS7操作系统因为已经不受支持，故最近更新了同为RedHat内核的RockyLinux9。
1.2、发现RockyLinux9的ssh版本比较高，访问一些比较低版本的ssh资产时会有一些算法不受支持的情况，无法正常连接。

2、想法：
想在Jumpserver拉取一个centos7的镜像，创建容器后将容器实例作为网域gateway纳管到堡垒机中，再将低版本ssh的资产添加此网域。

3、问题：
3.1、发现系统平台为Gateway的时候服务不可连接，提示：
![图片](https://github.com/user-attachments/assets/864eeff4-de3d-4546-8697-13d71789274d)

3.2、但我尝试将系统平台由Gateway改为“Linux”后就能正常连接了：
![图片](https://github.com/user-attachments/assets/06414131-3b76-49ae-ac28-c1c752c2e5be)

3.3、可以肯定的是我有其他非Docker容器的网域，且正常使用，当我使用Docker容器作为网域时仅安装了sshd服务（具体见“补充信息”）。由“3.2”可知，容器的sshd服务正常可连接，但从“3.1”看测试Gatway失败，那么除了sshd服务，网域的正常使用还需要安装哪些服务呢，是服务缺失还是其他因素呢？

### 补充信息

安装centos镜像的Dockerfile内容如下：
```
# 使用 centos 镜像
FROM centos:7

# 设置 root 密码
RUN echo 'root:test' | chpasswd

# 设置非交互模式，以便安装过程中不会出现提示
ENV DEBIAN_FRONTEND=noninteractive

# 配置yum源为本地局域网源（默认公网源已不受支持）
RUN cp /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak.$(date -d "today" +"%Y%m%d_%H%M%S")
RUN sed -i 's/^mirrorlist=https/#mirrorlist=https/g' /etc/yum.repos.d/*
RUN sed -i "s/^#baseurl=http:\/\/mirror.centos.org/baseurl=http:\/\/192.168.1.100/g" /etc/yum.repos.d/*

# 安装 OpenSSH 服务
RUN yum -y install openssh-server
RUN yum clean all

# 创建 SSH 服务所需的目录
RUN mkdir /var/run/sshd

# 生成 SSH 主机密钥
RUN ssh-keygen -A

# 配置 SSH 服务允许 root 登录（可选，根据需要配置）
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

# 启动 SSH 服务
CMD ["/usr/sbin/sshd", "-D"]

```

**Comment by Ewall555** [comment]
纳管资产后，连接资产是通过koko容器去连接的，与安装jumpserver本身的服务器发行版或者ssh无关联了，如果无法连接可以发一下纳管资产后的报错截图

**Comment by BaiJiangJie** [comment]
配置文件开始 `DEBUG_ANSIBLE` 重启所有服务，然后再执行测试网关的任务，可以看到详细的报错信息。

**Comment by akang1798** [comment]
原来是通过koko去连接的，我通过jumpserver本机去ssh会有ssh版本问题，还以为是通过jumpserver堡垒机所在主机本身去连接。目前已经解决，感谢支持。
