### ISSUE TITLE
[Question] dfdf

### ISSUE THREAD

**Issue by antonewaccount** [jumpserver/jumpserver#14736]
### Product Version

df bdfbd

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

dfbdfbdfbdfbfd df df df df df df df 

### 🤔 Question Description

df  df df ddf df df df df

**Comment by Ewall555** [comment]
bad issue
