### ISSUE TITLE
权限授权主机后，再取消授权，，系统用户并没有取消关联。

### ISSUE THREAD

**Issue by zhupengyugit** [jumpserver/jumpserver#1475]
[简述你的问题]
权限授权主机后，再取消授权，，系统用户并没有取消关联。
如果是初步使用和测试各功能模块，多个一两台主机并不影响，但如果上百台主机管理，或是更多。这样管理起来会特别混乱。希望大佬们，可以有更好的解决办法，更好的优化。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.1-2 GPLv2
##### 问题复现步骤
1. [步骤1]
添加用户，添加系统用户，添加权限管理组，授权比如5台服务器。用户登录jumpserver看到5台主机。OK
2. [步骤2]
进入权限管理，删除掉其中2台或是多台，保存。修改系统私钥，同步系统用户，系统用户并没有取消关联，已经删除授权的主机。同样还是会同步5台主机。。如果实际管理中，有上百台服务器，管理将会很混乱，而且也会对jumpserver主机造成一定的负载压力。可以删除系统用户再同步，则还是同样问题，还要重新同步上百台服务器。
##### 具体表现[截图可能会更好些,最好能截全]
系统用户  无取消关联主机功能 。会一直增加。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
参考 #1499 

如果有问题请重新打开issue
