### ISSUE TITLE
WINDOWS拖拽文件无法上传和下载

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1476]
版本:1.3.2
描述：在LUNA上登录WIN机器，拖拽文件无法上传，也无法下载。
Nginx已配置
```
client_max_body_size 1000m;
```
文件上传没有发生错误，但是上传速率几乎为零，一直卡着不动
![Uploading image.png…]()

**Comment by brucegogo** [comment]
同问

**Comment by gengkeye** [comment]
在我的电脑里会有自动生成一个Guacamole RDP的盘，
上传：直接拖拽文件到windows窗口，然后文件会自动保存到Guacamole RDP这个盘根目录；
下载：把文件复制到Guacamole RDP盘的Download目录里，会自动下载到本地；

**Comment by afreetgo** [comment]
远程windows 2008机器 没找到Guacamole RDP 这个盘，但ctrl+alt+shift 里面有一个驱动盘，能看到我上传的文件。但在远程机上无法看到。

**Comment by xionghui** [comment]
远程windows 2008机器 没找到Guacamole RDP 这个盘，但ctrl+alt+shift 里面有一个驱动盘，能看到我上传的文件。但在远程机上无法看到。

**Comment by ErYoung2** [comment]
上传还是挺方便的，就是下载慢如狗。如果碰到大文件，死的心都有了~
