### ISSUE TITLE
【分布式部署】gunicorn和celery在不同节点导致ops/celery/task 输出日志异常

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#1480]
[简述你的问题]

##### 使用版本
1.3.2
##### 问题复现步骤
![image](https://user-images.githubusercontent.com/11460661/41956702-27f0d046-7a17-11e8-99d1-4365fa2a686e.png)

手动做任意会让前端出现ops/celery/task日志弹窗的操作, 如果gunicorn和celery不是在同一节点启动,会导致日志前端日志弹窗无法正常显示

##### 具体表现[截图可能会更好些,最好能截全]
不同组件用了本地文件通信

CeleryTask的log_path是在当前节点创建的日志文件,  celery调用ansible写入,gunicorn读取..如果跨节点就前端日志输出无法正常工作了(实际celery任务在正常跑)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
可以考虑下基于redis的Pub/Sub模式替代本地文件

**Comment by jokimina** [comment]
#1489

**Comment by ibuler** [comment]
参考 楼上方案，或等待新的架构

如果有问题请重新打开issue
