### ISSUE TITLE
新建的系统用户推送不成功。

### ISSUE THREAD

**Issue by 13247380098** [jumpserver/jumpserver#1484]
[简述你的问题]
新建的系统用户，新的资产，授权后，系统的一直测试连接不上机子，后来发现老的系统用户老的资产测试连接性也时好时坏，经常都是出现点点点点点点.....很久都没出现连接成功或者失败的结果。
##### 使用版本
[1.3.1 ]

##### 问题复现步骤
1. 后面吧老系统用户在机子中删除后，并把用户home文件夹也删除了，重新授权资产和系统用户
2. 也不知道推送成功没有，测试连接性一直点点点点点......
3.在jumpserver服务器上登录系统用户也显示Authentication failed.

##### 具体表现[截图可能会更好些,最好能截全]
![_20180627174154](https://user-images.githubusercontent.com/38271261/41966379-8b5598aa-7a31-11e8-934f-5f16020e51f0.jpg)
![_20180627174227](https://user-images.githubusercontent.com/38271261/41966381-8bafafa2-7a31-11e8-9a6c-ea41b8854b23.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
一直点点的可能是因为你启动了beat. 把beat关掉，清一下celery的task.
参考：http://docs.jumpserver.org/zh/docs/faq.html 中的9.其它问题 （11）
解决后，请关闭issue

**Comment by ibuler** [comment]
如果有问题请重新打开issue
