### ISSUE TITLE
【BUG】资产树上节点资产数显示错误

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1487]
版本：1.3.2
描述：资产树上节点资产的数量显示错误，存在重复计算的问题，导致子节点显示的资产数超过父节点，或父节点的资产数超过实际资产总数。
PS：不方便截图

**Comment by gxk001** [comment]
![image](https://user-images.githubusercontent.com/32119424/42018753-9a2f59d8-7ae5-11e8-9349-d578682b87ab.png)
没看出来啊

**Comment by gengkeye** [comment]
@gxk001 你试下把子节点的机器添加到父节点上

**Comment by ibuler** [comment]
右击树，切换模式。  现在树显示有两种模式，1. 只显示当前节点下的资产  2. 显示当前节点和子节点的资产

**Comment by gengkeye** [comment]
子节点的资产应该默认属于父节点，个人观点。这样使用起来更方便一些。

**Comment by ibuler** [comment]
已修复
