### ISSUE TITLE
navicat 通过jumpser代理mysql数据库

### ISSUE THREAD

**Issue by luckylgit** [jumpserver/jumpserver#1491]
[简述你的
问题]
之前版本（0.3.3）的可以通过下载pem证书，navicat可以通过证书做做代理连接数据库，但是现版本的证书，不能连接，
看到新版本的用户授权是通过coco控制，不知道如何解决
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
目前版本.1.3
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时不支持，透明模式无法记录日志

**Comment by koupeng** [comment]
@ibuler 你好。关于这个问题有开发计划么？

**Comment by huwenbiao** [comment]
+1，升级后无法连接数据库了，希望能增加这个功能。

**Comment by Jiangshan00001** [comment]
+1，升级后无法连接数据库了，希望能增加这个功能。

**Comment by jym503558564** [comment]
请持续关注官网更新情况，如有其它问题可重新打开issues
