### ISSUE TITLE
请问JP的Roadmap是？

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1494]
想了解JP以后的开发计划，我们也在做二次开发，避免有些功能做重了。

**Comment by ibuler** [comment]
ok, 我写一下

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/milestone/3

**Comment by ibuler** [comment]
可以加我qq或微信

**Comment by gengkeye** [comment]
@ibuler 感谢，请问您的微信号是？

**Comment by ibuler** [comment]
@gengkeye 我的邮箱  ibuler#qq.com  ，我发给你
