### ISSUE TITLE
支持组织 二级管理员

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#1495]
[简述你的问题]
现在 Jumpserver只有一个超级管理员，公司大了以后所有工作量都落到管理员身上，所以打算做一个组织的功能，一个组织就是一个namespace，组织管理员负责该组织下的资源管理

**Comment by ScofieldLiu** [comment]
期待。。。

**Comment by gengkeye** [comment]
额 这个我们已经做了，加了一个组长的概念。

**Comment by ibuler** [comment]
已完成该功能
