### ISSUE TITLE
【BUG】在用户列表内，点击删除，居然删除的是当前登录的用户

### ISSUE THREAD

**Issue by peileijp** [jumpserver/jumpserver#1498]
[简述你的问题]
在用户列表内，点击删除，居然删除的是当前登录的用户
删除的不是这个用户，而是登录用户，删的是admin
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.0-2 GPLv2.
##### 问题复现步骤
1. [步骤1]
点击“用户管理”-->“用户列表”--->随便点一个用户到“用户详情”
2. [步骤2]
点击右上角“删除”，删除的是当前登录的管理用户，而不是用户详情显示的用户

**Comment by ibuler** [comment]
修复在dev了，等待release，感谢
