### ISSUE TITLE
【功能需求】取消授权后，系统用户取消主机关联。要不然，系统用户会一直保留有之前授权过的资产，如果服务器下架了，系统用户还在推送用户。管理混乱

### ISSUE THREAD

**Issue by zhupengyugit** [jumpserver/jumpserver#1499]
[简述你的问题] 
权限授权主机后，再取消授权,,系统用户并没有取消关联。
如果是初步使用和测试各功能模块，多个一两台主机并不影响，但如果上百台主机管理，或是更多。这样管理起来会特别混乱。希望大佬们，可以有更好的解决办法，更好的优化。

使用版本

[请提供你使用的Jumpserver版本0.3.2或0.5.0] 
版本1.3.1-2 GPLv2

问题复现步骤

[步骤1] 
添加用户，添加系统用户，添加权限管理组，授权比如5台服务器。用户登录jumpserver看到5台主机.OK
[步骤2] 
进入权限管理，删除掉其中2台或是多台，保存。修改系统私钥，同步系统用户，系统用户并没有取消关联，已经删除授权的主机。同样还是会同步5台主机。 。如果实际管理中，有上百台服务器，管理将会很混乱，而且也会对jumpserver主机造成一定的负载压力。可以删除系统用户再同步，则还是同样问题，还要重新同步上百台服务器。
具体表现[截图可能会更好些，最好能截全]

系统用户无取消关联主机功能。会一直增加。

其他

[注：]完成后请关闭问题

**Comment by ibuler** [comment]
这里确实存在这个问题，由于授权时计数问题，没有研究好的算法。
另外贸然回收系统用户也会存在问题，之前一位群友因为回收了系统用户导致业务停止，家目录丢失，然后被离职了

**Comment by awklinux** [comment]
对于这个问题有两点想法，不知是否可行
1. 清除账号的时候的不清理家目录
2. 创建一个默认的备份文件夹，也可以在设置里让用户自己指定，当删除用户家目录时，直接将家目录mv到这个备份文件，然后建立一个定时任务，比如一个月后自动删除这个备份，也可以让用户手动去清理
