### ISSUE TITLE
持久化文件太多，需要重新考虑

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#150]
1.  /etc/passwd /etc/shadow /etc/group
2. keys
3. logs
4. /home/

并且移动目录需要更改数据库记录

**Comment by liuzheng712** [comment]
3.logs文件目录正在迁移持久化文件，将原先的xx.time 和 xx.log归并为一个zip文件，过度期间三种文件类型共存，后期写个脚本一键整合

**Comment by ibuler** [comment]
1. 使用python实现ssh server
2. keys放到数据库中
4. 同1

**Comment by ibuler** [comment]
3. 考虑一下扩展到elk

**Comment by EverCurse** [comment]
@ibuler  请问迁移成功了吗？ 现在我也遇到这个问题 能请教下吗
