### ISSUE TITLE
jumpserver v1.0版本集群部署

### ISSUE THREAD

**Issue by chenglu01** [jumpserver/jumpserver#1501]
[简述你的问题]

求提供一份jumpserver集群部署文档，目前有1200多台主机需要管理，害怕单节点故障！

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

版本v1.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by gxk001** [comment]
简单一点的：
8台vm

centos7u5 * 2
pcs / vip+nginx + luna => 主备

centos7u5 * 2
pcs / vip+jumpserver + coco + redis => 主备

centos7u5 *2
pcs / vip+guacamole（tomcat）=> 主备

centos7u5 * 2
pcs /vip + mysql => 主备

**Comment by ibuler** [comment]
如果还有问题请重新打开issue
