### ISSUE TITLE
Terminal终端  能不能只显示Linux节点资产？

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#1505]
[简述你的问题]

##### 问题复现步骤
1. [# ssh -p2222 admin@jumpserver  登陆JumpServer Terminal终端后]
2. Windows资产竟然也显示在 Terminal列表，这对使用造成困扰，有无方法只显示Linux节点？？？
3. 用户肯定需要同时授权 Win + Linux资产

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
新版本默认不会显示windows资产，请检查coco组件的版本

**Comment by NeilyoSH** [comment]
“$ git clone https://github.com/jumpserver/coco.git”
这个源的 我git pull 过几次了，确定是最新了，还是如上所述。

**Comment by NeilyoSH** [comment]
@wojiushixiaobai

现有的coco  git pull 几次了 还是如上描述，确定是Master分支 实现此功能？？？

**Comment by ibuler** [comment]
会显示的，如果不显示用户可能会迷惑，为何看到的授权列表和登陆coco的不一致。

再coco里登陆windows会给用户提示: 请使用luna登录windows资产

**Comment by ibuler** [comment]
如果还有问题请重新打开issue
