### ISSUE TITLE
Web Terminal - Linux 语句过长会无法显示

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#1506]
[简述你的问题]

##### 问题复现步骤
1. [Web Terminal终端上 Linux目录过深 或者 命令语句过长，会无法正常显示]

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
截图可能更明确一些

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
