### ISSUE TITLE
资产管理中的cpu、内存等应该都能实现批量，要不太麻烦了

### ISSUE THREAD

**Issue by wenskys** [jumpserver/jumpserver#151]
资产管理中的cpu、内存等应该都能实现批量，要不太麻烦了，每个都要手动去加，台数多了麻烦，而且迁移也不方便

**Comment by ibuler** [comment]
本来就可以自动实现，可以点击更新来更新资产硬件信息，也可以定时更新

**Comment by wenskys** [comment]
试了下，点击更新没什么反应，就是刷新了列表
