### ISSUE TITLE
【BUG】资产的批量移动在源节点还存在

### ISSUE THREAD

**Issue by peileijp** [jumpserver/jumpserver#1511]
[简述你的问题]

在资产管理界面，选中几个资产，想迁到另一个节点，但是源节点还存在此资产。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.0-2 GPLv2
##### 问题复现步骤
1. [步骤1]
点击“资产管理”--->“资产列表”---->选中列表内的一个节点，在此节点下选中几个资产，选中”批量更新”，点击“提交”
2. [步骤2]
在“批量更新资产”界面，“节点管理”选项可以修改资产归属节点。
但是在提交之后，虽然在新的节点内存在了这些修改的资产，但是在老的节点还是存在这些资产。

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
选中原节点下想移除的资产，点击 (批量) 从节点移除，提交

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
