### ISSUE TITLE
登录交换机等网络设备提示could not get keys from ssh-agent，无法登录设备。

### ISSUE THREAD

**Issue by zengao2000** [jumpserver/jumpserver#1512]
[在建立系统用户时，没有选择自动生成密钥，没有选择自动推送。但是用户无法登录网络设备，提示could not get keys from ssh-agent，coco后台提示 [connection ERROR] Connect xxxxx@xxxxxxxx:22 auth failed, password:                                  xxxx****, key: None]

##### 使用版本
[Jumpserver版本1.3.2-2]

##### 问题复现步骤
1. 添加资产，类别选other
2. 添加管理用户，具有高权限的交换机ssh登录用户，填写登录密码，未选择密钥。（在使用putty登录设备时，会提示是否接受一个证书，当然接受就可登录）
3. 添加系统用户，即设备已经具有的用户，填入用户名密码，未选择自动生成密钥，未选择自动推送。

求助各位，如何管理交换机、路由器、防火墙等设备。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zengao2000  选择linux试试，不要用other

**Comment by dwk715** [comment]
/coco/coco/connection.py

`ssh.connect(gateway.ip, port=gateway.port,
                            username=gateway.username,
                            password=gateway.password,
                            pkey=gateway.private_key_obj,
                            timeout=TIMEOUT)`

改一下试试，我改了就好了cisco 2960

**Comment by ibuler** [comment]
已修复，思科设备的问题，已做兼容
