### ISSUE TITLE
LDAP认证时参数类型异常

### ISSUE THREAD

**Issue by hywangyc** [jumpserver/jumpserver#1516]
LDAP认证时参数类型异常

##### 使用版本
1.3.2-2

##### 问题复现步骤
1. 启用LDAP认证
2. 使用LDAP用户登录

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7285108/42504597-dc064a1e-846e-11e8-886e-acbc62c50d9e.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
映射的ldap三个字段不可删，可以替换
映射到jumpserver的三个字段不可删不可替换

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
