### ISSUE TITLE
Jumpserver是否可以通过api来添加删除资产？

### ISSUE THREAD

**Issue by topicgit** [jumpserver/jumpserver#1520]
[简述你的问题]
Jumpserver是否可以通过api来添加删除资产？
##### 使用版本
最新

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
参考 jumpserver-python-sdk

**Comment by liuwenru** [comment]
你可以使用python-jdk来创建，当然你可以通过restapi来创建，部分API供你参考

1、用户登录
curl -XPOST -d 'username=admin;password=admin' http://192.168.188.40/api/users/v1/token/

{"Token":"14a9f25397444abb8666c9fa00c294c9","Keyword":"Bearer"}


2、获取所有的用户
curl -H 'Authorization: Bearer 14a9f25397444abb8666c9fa00c294c9' -XGET  http://192.168.188.84:8080/api/users/v1/users/



3、创建用户组
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -H 'Authorization: Bearer 14a9f25397444abb8666c9fa00c294c9' -d  '{"id":"1162e7a4-90f6-4e5e-b7cf-14581adb7621","is_discard": false,"discard_time": "","name":"epointgroup","comment":"","created_by": "administrator","date_created":"2018-06-06 06:03:03 +0000","discard_time":"2018-06-11 06:03:03 +0000"}' 'http://192.168.188.84/api/users/v1/groups/'

4、创建用户并设置用户组

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -H 'Authorization: Bearer 14a9f25397444abb8666c9fa00c294c9' 'http://192.168.188.84/api/users/v1/users/' -d '{"id": "13f1432d-9a8c-4d83-aad9-c3177e3a387d","groups": ["1162e7a4-90f6-4e5e-b7cf-14581adb7620"],"last_login": "2018-05-19 06:03:03 +0000","is_active": true,"date_joined": "2018-06-06 06:03:03 +0000","username": "ijarvis","name": "ijarvis","email": "ijarvis@sina.com","role": "Admin","avatar": null,"wechat": "","phone": "","otp_level": 0,"comment": "","is_first_login": true,"date_expired": "2088-05-19 06:03:03 +0000","created_by": "2018-05-19 06:03:03 +0000"}'



5、 获取所有资产列表

curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/json' -H 'Authorization: Bearer 14a9f25397444abb8666c9fa00c294c9' 'http://192.168.188.84/api/assets/v1/assets/'


 6、创建用户资产

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -H 'Authorization: Bearer 14a9f25397444abb8666c9fa00c294c9' -d '{"id": "9f7a3cd5-b3be-4a4f-a7f6-0cbcb8529e71","ip": "192.168.186.66","hostname": "Hadoop_186_66","port": 22,"platform": "Linux","is_active": true,"public_ip": null,"created_by": null,"comment": "","admin_user": "06fe163e-aacd-48ce-a7a7-a15800587b99", "nodes": ["7c0b0eda-8555-42e4-9205-992957c46d56"]}' 'http://192.168.188.84/api/assets/v1/assets/'

**Comment by topicgit** [comment]
好的，多谢

**Comment by Gourds** [comment]
@BigbigY  我刚写了一个导入资产的脚本https://github.com/Gourds/jms-assets-import，里面有，
```
curl -H 'Authorization: Bearer xxxxxx' -XGET http://xxx:8080/api/assets/v1/system-user/?name={ops-user}
```

**Comment by ZuoGuocai** [comment]
这个接口失效了吗？我想通过POST 新增资产，结果直接返回全部资产信息了。

**Comment by zhangdavids** [comment]
同问楼上的情况

**Comment by KeithTt** [comment]
> 参考 jumpserver-python-sdk

我试了一下 SDK，`from jms import UserService` 直接变红提示找不到引用。

这个 SDK 的文档能完善一下嘛...

参考：https://pypi.org/project/jumpserver-python-sdk/
