### ISSUE TITLE
Jumperserver在Linux与Windows远程中上传与下载的功能支持

### ISSUE THREAD

**Issue by liuwenru** [jumpserver/jumpserver#1521]
[简述你的问题]

##### 使用版本
最新版本的Jumperserver，dev分支

##### 功能需求

请问Windows和Linux的web页面远程是否支持文件上传与下载操作？ 或者说后续是否有计划支持文件上传与下载操作？

**Comment by ibuler** [comment]
windows是支持的，linux的需要再等等

**Comment by Kisen-Chin** [comment]
@ibuler  你好，想问下， windows哪里支持这个功能？ 怎么用呢？ 我没看到相应的按钮啊

**Comment by zxl0715** [comment]
@ibuler  windows 有支持文件上下传吗？
