### ISSUE TITLE
授权问题:

### ISSUE THREAD

**Issue by yuedingwangji** [jumpserver/jumpserver#1522]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.2 最新版

##### 问题
   jumpserver 能实现给一个组内有多个jumpserver登陆用户，   对应登录的系统账号多个，  能限制用户通过jumpserver登录的时候，限制该用户能使用的系统账号只有一个么，就是他自己么

**Comment by yuedingwangji** [comment]
你好， 我现在是向这样的， 比方说我有 3个同事， a,b,c 我现在需要给这3个同事开通系统账号，然后如果我希望他们登录的时候用的都是他们自己的系统账号，我就只能一个个用户去授权，我现在想通过直接授权给组， 但是授权给组的时候， 如果只给一个系统用户， 就变成了他们3个登录的时候都是同一个用户了， 如果给多个系统用户， 那么现在登录的时候，他们可以选择其他的账户， 我想不让他们选择， 就登他们自己的账号

**Comment by wojiushixiaobai** [comment]
@yuedingwangji 只能创建三个授权，权限细化。

**Comment by yuedingwangji** [comment]
好吧， 理解，  看下api 文档， 看能不能快速授权，一个个用户授权点起来有点烦 哈哈
