### ISSUE TITLE
资产上有多个系统账号怎么和用户关联

### ISSUE THREAD

**Issue by mingup** [jumpserver/jumpserver#1527]
[简述你的问题]

在我的场景中，我们的资产上有多个系统账号，怎么把资产上不同的系统账号，和不同的人员关联起来？

**更具体一点**

我们使用了ldap做jumperserver登录，jumperserver之后有一台资产，配置了pam_ldap.so模块，所以该资产也是通过ldap登录。我们考虑的是，在用户通过ldap账号登录jumperserver之后，可以登录到这台资产上他个人的系统账号下。请问有什么解决办法么？

感谢！

##### 使用版本
Version 1.3.2-2

**Comment by wojiushixiaobai** [comment]
@mingup 
可以让用户手动输入用户密码登录，目前的版本可以在系统用户，点击系统用户的名称，点击清除认证信息（此操作不可逆），使用该系统用户的资产都需要用户自行输入资产账户密码进行登录

下个版本会新增手动登录功能

**Comment by gengkeye** [comment]
@wojiushixiaobai 清除认证信息功能还没放出来，我看页面上的代码是注释掉的。

**Comment by wojiushixiaobai** [comment]
@gengkeye 可用的，1.3.3已经用手动登录功能替换清除认证信息
请更新体验

**Comment by gengkeye** [comment]
@wojiushixiaobai 多谢，更新后看到了。
