### ISSUE TITLE
Luna中rz命令无法上传文件，而且终端会卡死

### ISSUE THREAD

**Issue by LemWong** [jumpserver/jumpserver#1531]
[简述你的问题]
在Luna客户端中使用rz命令后Luna终端会直接卡死，按ctrl+c也无响应
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
使用的是jumpser1.3  Luna1.3.2-101
##### 问题复现步骤
1. [步骤1]
net@debian:~$sudo rz
**B0100000023be50eive.**B0100000023be50
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/35365558/42742574-4c9ba89a-88ee-11e8-92f2-5fd0c81d57d9.png)

##### 其他
给我的感觉是使用rz命令后Luna无法弹出文件选择框，而使用Xshell等工具可以弹出文件选择框；
以下是使用Xshell工具中弹出的选择框界面：
![image](https://user-images.githubusercontent.com/35365558/42742669-32a554ee-88ef-11e8-9034-fe2fd6cfaa0e.png)

[注:] 完成后请关闭 issue

**Comment by liuwenru** [comment]
貌似这个是不可以实现的把，使用的都不是同一个东西的吧！
