### ISSUE TITLE
Version 1.3.2-2 資產無法導入

### ISSUE THREAD

**Issue by pigchanc** [jumpserver/jumpserver#1534]
資產列表無法使用csv導入新資料

##### 使用版本
Version 1.3.2-2

##### 问题复现步骤
1. 點選資產列表
2. 點選導入
3.下載模板
4.填入要匯入資產資料 （填寫B-I的資料,G網域是空白）
5. 顯示出 Must be same format as template or export file

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/23327485/42747543-6bfbf91c-890f-11e8-9483-0a4e345ebb4d.png)

![image](https://user-images.githubusercontent.com/23327485/42747570-90e7dcb4-890f-11e8-9389-4be3b818e6c7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@pigchanc 另存为，不要直接保存

**Comment by pigchanc** [comment]
另存新檔就可以導入了,謝謝

**Comment by gengkeye** [comment]
那就关闭issue吧
