### ISSUE TITLE
求问windows如何在web shell下载文件？

### ISSUE THREAD

**Issue by whoistr** [jumpserver/jumpserver#1535]
[简述你的问题]
拖拽下载不了

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
同问。

**Comment by RorschachChan** [comment]
![image](https://user-images.githubusercontent.com/31002078/43297683-55afaafe-9185-11e8-8acf-6b7fec72a145.png)
我的版本是1.3.2-101 GPLv2.   在luna界面里使用sz 就卡住了，请问如何下载？

**Comment by whoistr** [comment]
@RorschachChan rz和sz是xshell支持的，webshell不可以的。下载用xftp相关软件就可以上传下载，sftp协议2222端口，用户名密码jumpserver的就可以。

**Comment by whoistr** [comment]
而且windows的luna界面没办法完成与本机的复制粘贴 是还不支持还是我本机问题呢~

**Comment by whoistr** [comment]
发现怎么用了~  把文件拖到download目录就可以了

**Comment by gengkeye** [comment]
@whoistr 拖到download目录也不行好像

**Comment by xionghui** [comment]
远程windows 2008机器 没找到Guacamole RDP 这个盘，但ctrl+alt+shift 里面有一个驱动盘，能看到我上传的文件。但在远程机上无法看到。
