### ISSUE TITLE
堡垒机无法全屏

### ISSUE THREAD

**Issue by AIKiller** [jumpserver/jumpserver#1537]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.2-2 GPLv2
##### 问题复现步骤
1. ![](http://ww1.sinaimg.cn/large/93d61c99ly1ftckwieyg5j21h70qdgo7.jpg)
2. 隐藏左侧栏后，链接画面仍然无法全屏显示。 
![](http://ww1.sinaimg.cn/large/93d61c99ly1ftckx766a3j21h70qdjtm.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
#1455 参考，关注一下，到时修复一下
