### ISSUE TITLE
[1.3.3]用户管理→用户列表的中文名称显示乱码

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#1545]
用户名称使用中文，在列表里显示成了unicode码了，例如%u8881

##### 使用版本
[1.3.3]

##### 问题复现步骤
1. [1.3.1]升级到1.3.3
2.查看用户列表，或用户修改名称再提交，还是显示乱码

##### 具体表现[截图可能会更好些,最好能截全]
![qq20180717-231455](https://user-images.githubusercontent.com/2853517/42826677-8fd0db88-8a17-11e8-8519-2800697eae8a.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yuanhaoliang 抱歉，已经解决了，请更新下代码。
