### ISSUE TITLE
Jumpserver Ajax错误

### ISSUE THREAD

**Issue by bb652826616** [jumpserver/jumpserver#1546]
Jumpserver版本1.3.2-101

1.以下是打开资产授权列表-点击节点时，报错截图：
![jumpserver error](https://user-images.githubusercontent.com/34960554/42857379-3a725d82-8a7c-11e8-8e0d-3d1e5f654aeb.jpg)

2.浏览器控制台返回的结果
jquery-2.1.1.js:4 GET http://192.168.20.210/api/perms/v1/asset-permissions/?node=20c0a088-aaf5-4a62-8d3d-e7826b23371a&asset=&draw=3&search=&limit=15&offset=0&_=1531883810192 500 (Internal Server Error)

**Comment by gengkeye** [comment]
这个一般是你的API里有错误，或者返回的结果和表格的数据结构不匹配。

**Comment by wojiushixiaobai** [comment]
@bb652826616 很抱歉，已经修复了这个问题，请更新一下代码。

**Comment by gengkeye** [comment]
@wojiushixiaobai 已更新，没问题了。

**Comment by bb652826616** [comment]
更新代码后，已解决，谢谢你们！
