### ISSUE TITLE
coco最新版本内部执行requests报错问题，待解决

### ISSUE THREAD

**Issue by Jonnter** [jumpserver/jumpserver#1553]
[简述你的问题]

##### 使用版本
jumpserver和coco最新版本（2018.7.18日）

##### 问题复现步骤
1. 在coco interactive.py文件内加入requests报错
2. requests http没有问题，https会有问题

##### 具体表现[截图可能会更好些,最好能截全]

![9ac6801881105577dd35bb19829c80ad](https://user-images.githubusercontent.com/21307121/42869818-bf838f56-8aa8-11e8-9c37-161a9673f33e.jpg)
![2ca7200a2ec188fbd3f5b8620c6c3d2a](https://user-images.githubusercontent.com/21307121/42869820-c21d60b6-8aa8-11e8-82d1-f893791ec3fd.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
需要自己解决一下
