### ISSUE TITLE
Windows 资产连接后白屏

### ISSUE THREAD

**Issue by bb652826616** [jumpserver/jumpserver#1554]
Jumpserver版本1.3.3

Windows 资产连接后白屏
![image](https://user-images.githubusercontent.com/34960554/42875267-ec962226-8ab5-11e8-8bab-4d13eb87930c.png)

排查过程：检查nginx配置文件的guacamole设置ip，检查终端管理的gua状态，检查资产设置及系统用户都未发现问题

**Comment by wojiushixiaobai** [comment]
请参考此文档 http://docs.jumpserver.org/zh/docs/faq_windows.html 进行解决

**Comment by bb652826616** [comment]
已解决此问题，但是guacamole有时会离线，要把guacamole容器重启，才能显示在线
