### ISSUE TITLE
在线会话的来源ip都是127.0.0.1

### ISSUE THREAD

**Issue by LivesMountain** [jumpserver/jumpserver#1557]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.3-2 GPLv2

##### 问题复现步骤
1. 在线会话的来源ip都是127.0.0.1
2. 查看了nginx日志获取到了网关ip，感觉应该是jumperserver传到coco的数据
3.要获取nginx转过来的ip我需要怎么设置
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/19382017/42926235-6087bf70-8b63-11e8-8102-bfd26893d81e.png)
nginx配置
![image](https://user-images.githubusercontent.com/19382017/42926307-90480454-8b63-11e8-9c57-47f5c3de63cc.png)

**Comment by LivesMountain** [comment]
![image](https://user-images.githubusercontent.com/19382017/42915497-df3dc3a4-8b32-11e8-9cae-828f6e2ca3ba.png)
![image](https://user-images.githubusercontent.com/19382017/42915522-02839c08-8b33-11e8-840b-eed8068d6be9.png)

**Comment by LivesMountain** [comment]
![zx7kj z4 7u6e_3139 djsf](https://user-images.githubusercontent.com/19382017/42915991-77fdf9c2-8b35-11e8-9460-37c1557d4231.png)

**Comment by LivesMountain** [comment]
[https://github.com/jumpserver/jumpserver/issues/1546](url)我更新了版本后可以打开luna 但是我的资产出现了数据问题
![image](https://user-images.githubusercontent.com/19382017/42919992-2e2f253e-8b47-11e8-9079-b5393f4232bb.png)
请问这个 数据是在那个表里保存的

**Comment by gengkeye** [comment]
JP部署在和用户同一网段吗？

**Comment by wojiushixiaobai** [comment]
@LivesMountain @gengkeye 
proxy_set_header要写在location {} 才有效
FAQ文档和安装文档已经更新；

**Comment by LivesMountain** [comment]
ok
已解决
![image](https://user-images.githubusercontent.com/19382017/43177432-dadc6398-8ffa-11e8-9969-75cd499e5cab.png)
谢了
