### ISSUE TITLE
SSH连接下，无法显示分组下的机器列表

### ISSUE THREAD

**Issue by plakhp** [jumpserver/jumpserver#1558]
[简述你的问题]
通过ssh连接后，输入G，可以显示出分组列表。但再输入分组列表的ID号，以显示分组下的机器时，就显示请输入正确的ID。但分组ID号是存在的。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.32
##### 问题复现步骤
1. [步骤1]
ssh连接。
G
2. [步骤2]
![image](https://user-images.githubusercontent.com/26219798/42920361-d218a80e-8b48-11e8-92c9-2f379cec9ede.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
你理解错了，请仔细看命令说明。
```
    1) 输入 ID 直接登录 或 输入部分 IP,主机名,备注 进行搜索登录(如果唯一).
    2) 输入 / + IP, 主机名 or 备注 搜索. 如: /ip
    3) 输入 p 显示您有权限的主机.
    4) 输入 g 显示您有权限的节点
    5) 输入 g + 组ID 显示节点下主机. 如: g1
    6) 输入 h 帮助.
    0) 输入 q 退出.
```
