### ISSUE TITLE
JumpServer支持敏感命令阻断吗？

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#1565]
请问JumpServer支持敏感命令阻断吗？如何设置？

**Comment by wojiushixiaobai** [comment]
@Coyote5 http://docs.jumpserver.org/zh/docs/admin_create_asset.html 创建系统用户
里面有sudo说明

**Comment by Coyote5** [comment]
@wojiushixiaobai 问题解决，谢谢。
