### ISSUE TITLE
无法登陆资产，提示protocol are inconsistent

### ISSUE THREAD

**Issue by dingpamaoo** [jumpserver/jumpserver#1577]
配置好资产和用户后无法登陆。
提示：System user <系统用户> and asset <资产名称> protocol are inconsistent.
无论是使用终端还是web页面都是这样。

##### 使用版本
照着教程直接从docker上拉下来的，不知道是啥版本
docker run -d -p 8080:80 -p 2222:2222 registry.jumpserver.org/public/jumpserver:1.0.0

##### 问题复现步骤
1. [步骤1]配置好用户和资源
2. [步骤2]使用web或终端登陆

##### 具体表现
![image](https://user-images.githubusercontent.com/8704246/43128967-de1b665c-8f65-11e8-9383-3a4c61dc0d93.png)
![image](https://user-images.githubusercontent.com/8704246/43128983-ea2b204a-8f65-11e8-9278-de35aea1a547.png)

##### 其他
配置了ldap登陆

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
资产协议和系统用户协议不一致。

**Comment by dingpamaoo** [comment]
> 资产协议和系统用户协议不一致。

你说的协议是指什么？
![image](https://user-images.githubusercontent.com/8704246/43174725-3849857c-8fee-11e8-9d1a-be8520287d0e.png)
这个么？

**Comment by ibuler** [comment]
已处理，不会显示协议不一致的系统用户了。

添加资产时有协议字段 ssh rdp telnet，系统用户也有同样的字段，授权同样的才会支持登录

**Comment by dingpamaoo** [comment]
> 已处理，不会显示协议不一致的系统用户了。
> 
> 添加资产时有协议字段 ssh rdp telnet，系统用户也有同样的字段，授权同样的才会支持登录

手动安装了最新版的，没有这个问题了

**Comment by mumulizi** [comment]
添加资产时没有协议字段让设置啊
