### ISSUE TITLE
web终端404报错

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#1578]
访问web终端的时候出现404报错

Jumpserver版本 0.3.2 或 0.5.0]

**出现问题**
10.2.4.25 [24/Jul/2018:17:56:26 +0800] "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2
2018-07-24 17:56:28 [base WARNING] Not Found: /index.html
10.2.4.25 [24/Jul/2018:17:56:28 +0800] "GET /index.html HTTP/1.0" 404 4219
![image](https://user-images.githubusercontent.com/20556236/43131387-7b9f6d4c-8f6b-11e8-8841-985dce00a0a9.png)
**操作步骤**
location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/; 
    }

# ls /opt/luna
……
index.html                                   
……

**Comment by wojiushixiaobai** [comment]
应该访问http://10.2.4.25/luna/

**Comment by Sandra299** [comment]
![image](https://user-images.githubusercontent.com/20556236/43174764-6d12bb2a-8fee-11e8-8f66-31b8f057edf9.png)
访问的是http://10.2.4.25/luna/

**Comment by Sandra299** [comment]
![image](https://user-images.githubusercontent.com/20556236/43174855-e1002496-8fee-11e8-9170-8411e562b2a1.png)
访问的是http://10.2.4.25/luna/但是会跳转到10.2.4.25/index.html下

**Comment by ibuler** [comment]
贴出你的nginx配置

**Comment by Sandra299** [comment]
server {
    listen       80;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass http://jumpserver;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /luna/ {
        try_files $uri /index.html;
        alias /opt/luna/; 
    }

    location /socket.io/ {
        proxy_pass    http://cocows/socket.io/; 
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }
}
