### ISSUE TITLE
API使用问题

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#1581]
[简述你的问题]

问题一：
Token获取失败,确实可以通过admin这个用户登陆
```
curl -X POST -d '{"username": "admin", "password": "admin"}' http://localhost/api/users/v1/token/
{"error":"User not exist"}
```
问题二：
如何使用api 通过json 来添加主机，id填什么，使用HTML_from表单可以不填id添加完成，但是使用json就会抛id不能为空

##### 使用版本
- Version 1.3.3-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
` -H "Content-Type:application/json"`

**Comment by BigbigY** [comment]
再请教个问题，手头有一批机器需要加入Jumpserver,使用web上的HTML_from可以提交，但是我id没填，如果使用脚本通过api
{
    "id": null,
    "ip": "",
    "hostname": "",
    "protocol": null,
    "port": null,
    "platform": null,
    "is_active": false,
    "public_ip": "",
    "number": "",
    "vendor": "",
    "model": "",
    "sn": "",
    "cpu_model": "",
    "cpu_count": null,
    "cpu_cores": null,
    "memory": "",
    "disk_total": "",
    "disk_info": "",
    "os": "",
    "os_version": "",
    "os_arch": "",
    "hostname_raw": "",
    "created_by": "",
    "comment": "",
    "domain": null,
    "admin_user": null,
    "nodes": [],
    "labels": []
}


有几个value不清楚填写什么：
"id": null,
"sn": "ec276d3c-1bfc-5e50-2cdd-fc99f4908509",
"admin_user": "916a3384-5df4-4dfc-9e70-0fd545c586eb",
"nodes": [
            "308ff532-bfa1-4639-99a6-ada4670c8b00"
        ],
请教下这几个value是如何获取的

**Comment by BigbigY** [comment]
![image](https://user-images.githubusercontent.com/16998173/43188362-8076070c-9026-11e8-8fa9-4529fb779ff6.png)

**Comment by BigbigY** [comment]
![image](https://user-images.githubusercontent.com/16998173/43188440-a97c2b22-9026-11e8-9e00-7f8e5c60801d.png)

**Comment by BigbigY** [comment]
使用脚本批量post增加，但是不清楚id,sn,admin_user,nodes这几串id怎么获取

**Comment by wojiushixiaobai** [comment]
@BigbigY 应该是数据库的相应字段，你看下

**Comment by BigbigY** [comment]
@wojiushixiaobai 谢谢，我已经使用资产数量增加完了
