### ISSUE TITLE
如何迁移到一个新版本的jms

### ISSUE THREAD

**Issue by z8772083** [jumpserver/jumpserver#1582]
当前版本：Version 1.2.0-2
装了一台新的JMS 版本为Version 1.3.3-2 的机器

如何将 1.2.0-2 里面的数据 迁移到 1.3.3-2的机器上去，想通过数据备份导入形式迁移，好像新版本字段格式有点不一样，有什么好的办法吗？

**Comment by ibuler** [comment]
没有，两个独立部署的无法迁移，升级到同一个版本方可迁移

**Comment by z8772083** [comment]
也就是先说可以建一个和原来版本一样的JMS，然后将数据迁移过去，迁移完数据之后再讲版本升级到高版本就可以了是吧？ @ibuler

**Comment by z8772083** [comment]
按照上面的步骤迁移数据成功了，但是在登录机器的时候有以下提示：
![image](https://user-images.githubusercontent.com/18564603/43205063-1036bf2a-9055-11e8-9cd8-7d6cd4f6bef9.png)
是什么原因呢？
如果直接升级到1.3.3-2 是否可以修复该问题？

**Comment by ibuler** [comment]
是的

**Comment by ibuler** [comment]
如果还有问题请重新打开issue
