### ISSUE TITLE
开启LDAP认证后无法从ldap服务器获取用户组

### ISSUE THREAD

**Issue by slan77** [jumpserver/jumpserver#1585]
[简述你的问题]
开启LDAP认证后无法从ldap服务器获取用户组
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.3
##### 问题复现步骤
1. [步骤1]
开启LDAP认证

2. [步骤2]
LDAP属性映射 增加 groups 选项
{"username": "uid", "name": "cn", "email": "mail", "groups": "gidnumber"}
用户登录时报错
<img width="1089" alt="qq20180725-170334 2x" src="https://user-images.githubusercontent.com/15992537/43191049-f51be436-902c-11e8-8319-3864ad28ad44.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by dingpamaoo** [comment]
还能这么用吗？我还以为只能匹配前面3个属性……

**Comment by slan77** [comment]
现在就是不行，加了"groups": "gidnumber"后会报错，但加"group": "gidnumber"就不会报错，但也没有拿到组的权限

**Comment by dingpamaoo** [comment]
> 现在就是不行，加了"groups": "gidnumber"后会报错，但加"group": "gidnumber"就不会报错，但也没有拿到组的权限

我也试了下，定义成"groups": "departmentNumber"，第一次登陆也会报错，刷新两次就进去了，但是仍然没有自动加入这个组。

**Comment by slan77** [comment]
找到一个获取LDAP用户组的临时办法
1：在LDAP属性映射中增加LDAP 组的字段
![image](https://user-images.githubusercontent.com/15992537/43558624-fb1b8aba-963c-11e8-9fc1-62b2cecf8f76.png)
2：用附件中的内容替换apps/users/signals_handler.py 文件
[signals_handler.py.zip](https://github.com/jumpserver/jumpserver/files/2251835/signals_handler.py.zip)
3：说明：如果LDAP 中的组在jumpserver 中有定义的话，则在用户登录后自动添加组，如果在jumpserver 中没有定义的话，则忽略。支持一个用户属于多个组  
4:每次登录成功后会更新组的信息
![image](https://user-images.githubusercontent.com/15992537/43558998-9c7e9e50-963e-11e8-9401-acf70b4db9ec.png)
![image](https://user-images.githubusercontent.com/15992537/43559094-12f199de-963f-11e8-9e9c-9d5b55fd13cf.png)

**Comment by slan77** [comment]
一个获取LDAP用户组的临时解决方法：
1：修改apps/users/utils.py 
      增加导入from .models import UserGroup
      增加一个类LdapUserGroup和一个函数add_ldap_group
      修改check_user_valid ，增加两行
          if password and authenticate(username=username, password=password):
                if user.source=="ldap":
                     add_ldap_group(username,LdapUserGroup.usergruopfromldap)
                return user, ''


2：修改apps/users/signals_handler.py 
      增加新的导入
      添加函数add_ldap_user_groups
      修改 on_ldap_create_user增加两行
          ldapgroup = settings.AUTH_LDAP_USER_ATTR_MAP["ldapgroup"]
          LdapUserGroup.usergruopfromldap=ldap_user.attrs[ldapgroup]

3：修改系统LDAP设置：
4：一个用户可以属于多个组，每次登录时会更新组的权限
5：通过web 和 SSH 登录均可获取组的信息，已测试通过
[signals_handler.py.zip](https://github.com/jumpserver/jumpserver/files/2252727/signals_handler.py.zip)


![image](https://user-images.githubusercontent.com/15992537/43572060-17070d56-9671-11e8-81bc-f705faad829b.png)
![image](https://user-images.githubusercontent.com/15992537/43572084-2c3b94ee-9671-11e8-911e-bc601ec6bc8d.png)
![image](https://user-images.githubusercontent.com/15992537/43572108-3f7a8790-9671-11e8-8ee4-a963d029a838.png)

**Comment by duanzhanling** [comment]
这个需求，我们这边也是需要的，辛苦了。
谢谢

**Comment by duanzhanling** [comment]
@slan77 
你这个脚本是否支持uniqueMember格式的用户组属性

**Comment by duanzhanling** [comment]
我这边都是这种格式的用户组，不过还好用户组可以多定义

**Comment by huangxin121** [comment]
请问，如果我想增加失效日期的ldap映射，应该修改哪里?

**Comment by slan77** [comment]
如果用ldap登录的话，帐号的所有信息应该都通过ldap来控制，失效日期对ldap帐户来说没有意义了。

**Comment by huangxin121** [comment]
> 如果用LDAP登录的话，帐号的所有信息应该都通过LDAP来控制，失效日期对LDAP帐户来说没有意义了。

明白了，谢谢

**Comment by huangpeng0817** [comment]
> 一个获取LDAP用户组的临时解决方法：
> 1：修改apps/users/utils.py
> 增加导入from .models import UserGroup
> 增加一个类LdapUserGroup和一个函数add_ldap_group
> 修改check_user_valid ，增加两行
> if password and authenticate(username=username, password=password):
> if user.source=="ldap":
> add_ldap_group(username,LdapUserGroup.usergruopfromldap)
> return user, ''
> 
> 2：修改apps/users/signals_handler.py
> 增加新的导入
> 添加函数add_ldap_user_groups
> 修改 on_ldap_create_user增加两行
> ldapgroup = settings.AUTH_LDAP_USER_ATTR_MAP["ldapgroup"]
> LdapUserGroup.usergruopfromldap=ldap_user.attrs[ldapgroup]
> 
> 3：修改系统LDAP设置：
> 4：一个用户可以属于多个组，每次登录时会更新组的权限
> 5：通过web 和 SSH 登录均可获取组的信息，已测试通过
> [signals_handler.py.zip](https://github.com/jumpserver/jumpserver/files/2252727/signals_handler.py.zip)
> 
> ![image](https://user-images.githubusercontent.com/15992537/43572060-17070d56-9671-11e8-81bc-f705faad829b.png)
> ![image](https://user-images.githubusercontent.com/15992537/43572084-2c3b94ee-9671-11e8-911e-bc601ec6bc8d.png)
> ![image](https://user-images.githubusercontent.com/15992537/43572108-3f7a8790-9671-11e8-8ee4-a963d029a838.png)

增加一个类LdapUserGroup和一个函数add_ldap_group  请问这两个在怎么写的。是写在utils.py么

**Comment by shen-joe** [comment]
类LdapUserGroup和一个函数add_ldap_group,内容是啥
