### ISSUE TITLE
资产登陆及录像

### ISSUE THREAD

**Issue by yshyydx** [jumpserver/jumpserver#1592]
[简述你的问题]
用户登陆windows资产时，系统管理采用手动登陆模式时，在线会话及历史会话中不会显示该用户任何信息包括录像，而采用自动登陆，一切都没有问题，希望解决手动登陆模式下的在线会话及历史会话
##### 使用版本
Jumpserver 1.3.3

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yshyydx 更新jumpserver与guacamole，最新代码已经支持

**Comment by ibuler** [comment]
如果还有问题请重新打开issue
