### ISSUE TITLE
telnet到cisco交换机上，系统用户能不能不写用户名？

### ISSUE THREAD

**Issue by lqhanll** [jumpserver/jumpserver#1597]
telnet到cisco交换机上，系统用户必须写用户名导致登录不上交换机上。不使用堡垒机正常登录交换机telnet 交换机IP   输入密码就ok了。不需要输入用户名
jumpserver版本1.3.3
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
![image](https://user-images.githubusercontent.com/41765973/43297176-471e05e2-9182-11e8-9847-64f775d6205b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lqhanll 系统用户选择手动登录，用户名和密码可不填

**Comment by lqhanll** [comment]
@wojiushixiaobai 您好，能不能给个例子。比如密码为12345，文档有点不太会修改。

**Comment by wojiushixiaobai** [comment]
@lqhanll telnet设备成功或者失败都会有提示符，coco根据设备的提示符判断登录失败还是成功，文档里面就有例子

如果你的设备没有账户，密码12345，那么在jumpserver后台，系统用户里面创建一个系统用户，
名称随意填写（不可重名）
登录模式  自动登录
用户名随意填写
优先级 10（默认）
协议  telnet（beta）
密码  12345
保存，授权即可

需要修改代码的说明请参考我上面发的文档，仔细阅读

**Comment by lqhanll** [comment]
好的，我测试下。 谢谢了
