### ISSUE TITLE
a logic bug 当修改用户资料，同时修改密码和用户信息，，用户信息不会保存。

### ISSUE THREAD

**Issue by dhh123** [jumpserver/jumpserver#160]
db_update_user 函数 

应该
        user.update(**kwargs)
        user_get = User.objects.get(id=user_id)

**Comment by dhh123** [comment]
这样改会导致一个新的问题。。。

**Comment by ibuler** [comment]
用户自己修改信息的时候？

**Comment by dhh123** [comment]
管理员给用户修改

**Comment by dhh123** [comment]
应该说是走def db_update_user 这个函数的都有问题

**Comment by ibuler** [comment]
应该没有大问题，里面有个 get_user.setpasswd，不过我还是简单fix了一下
