### ISSUE TITLE
openldap AUTH_LDAP_USER_FLAGS_BY_GROUP 设置管理员

### ISSUE THREAD

**Issue by orgliny** [jumpserver/jumpserver#1601]
[简述你的问题]
在AUTH_LDAP_USER_FLAGS_BY_GROUP可以设置is_active 属性，来确认是否允许ldap用户登录，
通过is_super不能映射为管理员，看代码中是通过role字段来确定用户角色，
 后期是否有计划修复这个问题

##### 使用版本
1.3.2

**Comment by ibuler** [comment]
AUTH_LDAP_USER_FLAGS_BY_GROUP 不了解是做什么的

is_superuser 就是超级管理员，通过role来确认，为何要修复？

**Comment by orgliny** [comment]
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    'is_active': 'cn=active,ou=django,ou=groups,dc=example,dc=com',
    'is_superuser': 'cn=superuser,ou=django,ou=groups,dc=example,dc=com',
}
可以通过这个配置设置cn=active,ou=django,ou=groups,dc=example,dc=com组的用户可以登录django，
cn=superuser,ou=django,ou=groups,dc=example,dc=com组内的用户是管理员，
role字段不是bool值，所以没法使用这个方式来设置管理员

**Comment by ibuler** [comment]
管理员没必要设置，毕竟没有多少管理员
