### ISSUE TITLE
请问怎么用批量执行命令！

### ISSUE THREAD

**Issue by HaAlan** [jumpserver/jumpserver#1605]
[简述你的问题]
看到功能介绍里面有批量执行命令的功能，但是在使用过程中只一直不知道怎么使用。另外在登入跳板机之后能不能不展示未激活的资源呢？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
  版本 1.3.2
##### 问题复现步骤
1. [步骤1]
   ssh登入2222端口后，没有出现有批量操作的提示。 
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/40971943/43312210-277cf350-91bf-11e8-82a3-f88d14a885e1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
很快就要来了

有问题可以重新打开issue
