### ISSUE TITLE
如何跨机房部署？

### ISSUE THREAD

**Issue by sungy2014** [jumpserver/jumpserver#1607]
[简述你的问题]
现有3地机房，北京，上海，深圳，
jumpserver如何跨机房部署?
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
最新版本
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@sungy2014 需求请详细说明，如果只是部署jumpserver连接多地的服务器，可以把jumpserver部署在可以连接所有资产的网络上即可。

**Comment by awklinux** [comment]
在一个机器量相对多的节点，或者网络中间节点，部署jumpserver（如上海，北京与深圳的中间），然后可以在北京和深圳各部署一个coco，做为登陆节点

**Comment by ibuler** [comment]
coco 需要调用 jumpserver提供的api，需要上传日志文件，请确保网络延迟

**Comment by ibuler** [comment]
有问题可以重新打开issue
