### ISSUE TITLE
管理用户创建只能选择一个ssh私钥。那么创建多个资产的时候，如何指定相同管理用户呢？

### ISSUE THREAD

**Issue by tglgame** [jumpserver/jumpserver#1611]
创建资产的时候需要指定管理用户，管理用户创建的时候要选择资产的ssh私钥，一个管理用户只能选择一个资产的ssh私钥，只有选择了私钥的资产连接才是成功的

那么在创建多个资产的时候，该怎么指定相同的管理用户啊？  
求解答

**Comment by wojiushixiaobai** [comment]
@tglgame 创建多个管理用户
如资产1_管理用户
资产2_管理用户

**Comment by tglgame** [comment]
@wojiushixiaobai  创建管理用户的时候是要指定资产的私钥，一个管理用户只能指定一个资产的私钥的吧，此时管理用户只能连接指定私钥的那个资产。
 那多资产如何指定同一个管理用户的啊？

**Comment by wojiushixiaobai** [comment]
@tglgame 上一个回答已经回答你，你的管理用户支持连接所有资产，你可以只选这个管理用户

如果不支持，那么你要么创建多管理用户，要么，把你的那一套key应用到所有资产

**Comment by ibuler** [comment]
有问题可以重新打开issue
