### ISSUE TITLE
jumpserver文档里不知道是我没找到还是没有    密钥账户直连coco的文档这部分 ，是官方不建议这样使用还是什么

### ISSUE THREAD

**Issue by LivesMountain** [jumpserver/jumpserver#1612]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

 1.3.3-2

**Comment by wojiushixiaobai** [comment]
@LivesMountain 登录时选择key认证即可。

**Comment by requestdaye** [comment]
登陆需要等待10秒 为什么？

**Comment by LivesMountain** [comment]
@wojiushixiaobai 嗯，但是直连coco的2222端口的那部分文档是没有的，是不建议这么做了么
