### ISSUE TITLE
不是bug

### ISSUE THREAD

**Issue by zhangming0922** [jumpserver/jumpserver#1616]
文件: jumpserver/apps/assets/models/node.py  # line: 67
正则表达式少一个占位符

def get_children(self, with_self=False):
        pattern = r'^{0}$|^{**0**}:[0-9]+$' if with_self else r'^{}:[0-9]+$'
        return self.__class__.objects.filter(
            key__regex=pattern.format(self.key)
        )

**Comment by ibuler** [comment]
应该无所谓， {0} 和 {} 没有区别，有问题请再打开
