### ISSUE TITLE
历史会话录像超过半小时的有丢失

### ISSUE THREAD

**Issue by 758109577** [jumpserver/jumpserver#1617]
[简述你的问题]
超过半小时的录像文件有丢失
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.3
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/27673595/43431613-41a93308-94a1-11e8-907c-8443527946e9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. 请检查该会话的日志是否上传成功
2. 请检查nginx设置，是否允许上传这么大的日志文件

**Comment by wojiushixiaobai** [comment]
@758109577 请查看安装文档的nginx部分，已做修改。

**Comment by wojiushixiaobai** [comment]
@758109577 请问问题是否已经解决，如果解决请关闭下问题，谢谢
