### ISSUE TITLE
机器信息中包含相同关键字，出现两个相同asset的问题

### ISSUE THREAD

**Issue by dhh123** [jumpserver/jumpserver#162]
例子：如果 hostname 或者 group  都包含一个 haha  ,那么通过关键字搜 haha ，会出现两个相同的资产。

可通过在keyword的asset_find 后面加上.distinct() 解决

**Comment by ibuler** [comment]
这个bug存在吗？ 为什么关闭了呢？

**Comment by dhh123** [comment]
按道理来说是会出现的。。但是我在你们的demo上没有模拟出来。。不知道什么问题。。有可能是我自己改出来的bug
