### ISSUE TITLE
1366, Incorrect string value

### ISSUE THREAD

**Issue by Panzus** [jumpserver/jumpserver#1620]
[简述你的问题]
coco和jumpserver日志一直報錯，/api/terminal/v1/command/ 500

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.0-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/13779486/43437682-dfe2f55c-94bc-11e8-96c9-c22c62d16363.png)

![default](https://user-images.githubusercontent.com/13779486/43437705-06e33d24-94bd-11e8-8ae9-7e1b4ff8494e.png)

##### 其他
數據庫編碼配置如下：
![default](https://user-images.githubusercontent.com/13779486/43437709-0b4baf2c-94bd-11e8-8f56-b62bcf5ebd5c.png)
![Uploading 图片.png…]()

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是否解决了？

**Comment by leoowu** [comment]
How to fix ?

**Comment by Panzus** [comment]
重启服务器之后正常了几天，这几天又出现了



在 2018-08-14 16:50:53，"老广" <notifications@github.com> 写道：


是否解决了？

**Comment by Panzus** [comment]
sorry, i don't know, it seems work after reboot the host, but again some days later.






At 2018-08-20 13:42:50, "leowu" <notifications@github.com> wrote:


How to fix ?

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/44730266-2186a280-ab13-11e8-8a33-31645625db0b.png)

表情字符，数据库字符集改为 utf8mb4

**Comment by Panzus** [comment]
这个编码我试过了，一样不行，我现在还是在用这个编码




在 2018-08-28 22:41:36，"老广" <notifications@github.com> 写道：


表情字符，数据库字符集改为 utf8mb4

**Comment by qq77moon** [comment]
请问这个问题解决没？我也遇到了同样的问题，mysql字符集修改为utf8mb4也没用

**Comment by Panzus** [comment]
没有，服务器重启之后会正常一段时间，之后又会出现

> 
> 
> 请问这个问题解决没？我也遇到了同样的问题，mysql字符集修改为utf8mb4也没用

**Comment by nika86v** [comment]
这个问题，对于已建好的表。要改下表结构才可以解决。命令如下: 

```
alter  table terminal_command MODIFY COLUMN input varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  ;

 alter  table terminal_command MODIFY COLUMN output varchar(1024)  CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  ;

```

**Comment by jym503558564** [comment]
问题是否解决了？
