### ISSUE TITLE
window server2016 连接不上

### ISSUE THREAD

**Issue by allen5460** [jumpserver/jumpserver#1625]
[简述你的问题]
window server2016 连接不上，不知道怎么弄，麻烦高人指点一下。。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
![image](https://user-images.githubusercontent.com/33114140/43501720-9573f25a-9589-11e8-83e6-d2679e6d3cb1.png)

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@allen5460 版本说明一下，提示内部错误，应该是资产信息填写不当
可以参考 [http://docs.jumpserver.org/zh/docs/faq_windows.html](url)

**Comment by ibuler** [comment]
如果是windows 2016，请设置操作系统为 windows 2016.
![image](https://user-images.githubusercontent.com/17382885/44081628-c10e146a-9fe1-11e8-8469-cbb0924497a8.png)

因为 windows 2016的协议升级了安全策略

**Comment by ibuler** [comment]
有问题可以重新打开issue
