### ISSUE TITLE
【COCO】多核CPU如何做负载均衡

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1630]
发现COCO会消耗较多CPU资源，多个CPU的情况下，只跑满了一个CPU，而其它CPU多处于空闲状态。如下图htop的输出：
![image](https://user-images.githubusercontent.com/8511007/43560836-ef7e0aca-9646-11e8-8918-c7a1ba65b083.png)
其中11号CPU被COCO跑满了。
问题：如何配置使各个CPU之间负载均衡？

**Comment by ibuler** [comment]
python的多线程不支持跑在多个cpu下，之前大师做多进程模型，后来放弃了，flask.io不支持

**Comment by gengkeye** [comment]
感谢您的回复

**Comment by ibuler** [comment]
有问题请再次打开issue

**Comment by nanguawu** [comment]
我也遇到这个问题了
