### ISSUE TITLE
网域网关密码特殊字符限制

### ISSUE THREAD

**Issue by hryGithub** [jumpserver/jumpserver#1631]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.3]

##### 问题复现步骤
网域机器内网机器无法连通，网域网关测试连接是ok的。
测试网域资产连通性的时，查阅网关机器ssh日志显示密码验证失败。
更改了网关机器的密码，然后资产能够正常联通了。(之前密码中含有特殊字符@开头的)

网域网关机器的密码是否有特殊字符限制？？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
或许存在该情况，ansible没有处理好特殊字符

**Comment by hryGithub** [comment]
了解了，目前只能在设置中规避这个问题

**Comment by ibuler** [comment]
有问题请再次打开issue
