### ISSUE TITLE
初始化数据报错

### ISSUE THREAD

**Issue by gitplyx** [jumpserver/jumpserver#1636]
sh make make_migrations.sh
File "/opt/py3/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6739. Connection refused.

**Comment by AnndaGH** [comment]
你这个不是 redis 连接被拒接了么..

**Comment by gitplyx** [comment]
但是本地连接起来没有问题啊

**Comment by ibuler** [comment]
redis错误，检查配置文件设置
