### ISSUE TITLE
1.3.2-2版本 ssh连接超时问题

### ISSUE THREAD

**Issue by snake0126** [jumpserver/jumpserver#1639]
[简述你的问题]
1.3.2-2版本 ssh连接超时问题
用户通过ssh连接到服务器，1分钟后自动断开，但是服务器上并没有设置timeout时间，且不使用jumpserver ssh连接的时候是正常的。

##### 问题复现步骤
连接ssh 没有操作后 1 分钟断开

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
jumpserver没有timeout类似的设置，请多添加几台机器试试

**Comment by ibuler** [comment]
有问题请再次打开issue
