### ISSUE TITLE
关于国际化的问题，怎么设置中文？

### ISSUE THREAD

**Issue by dwk715** [jumpserver/jumpserver#1640]
[简述你的问题]
我在安装好jumpserver后发现是英文的，安装的过程中也没看的有设置中文界面，在设置中没有找到有国际化的选项，查了文档也没看的，想请教各位怎样设置成中文界面呢？

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
v1.3.3 

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by dwk715** [comment]
嗯。。。是不是jumpserver主机没法设置中文，只有客户端是中文。

**Comment by wojiushixiaobai** [comment]
@dwk715 浏览器设置成中文优先

**Comment by dwk715** [comment]
@wojiushixiaobai 好的，谢谢
