### ISSUE TITLE
误删guacamole终端后，无法重新注册

### ISSUE THREAD

**Issue by Mikedu1988** [jumpserver/jumpserver#1643]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
删除guacamole中断后，重启guacamole的container，重启jms，依然无法看到guacamole的注册。终端只剩下COCO

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/24424690/43696311-f25fa164-996f-11e8-9395-5d146360435a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
去删掉gucamole 的 key，具体可以参考FAQ文档
    rm /opt/guacamole/key/*  # guacamole, 如果你是按文档安装的，key应该在这里

**Comment by Mikedu1988** [comment]
多谢大佬 问题解决了

**Comment by menglike** [comment]
请问删除key之后，需要重启jumpserver吗？  不重启的话，还是无法注册成功
