### ISSUE TITLE
更改Guacamole的IP

### ISSUE THREAD

**Issue by ldh603** [jumpserver/jumpserver#1650]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.0]

##### 问题复现步骤
1. [因为Guacamole容器默认的IP段172.17.0.0和内网地址段有冲突，这边需要更改成其它段，修改完后是否需要重新删除注册？或者需要怎么操作?]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ldh603  文档http://docs.jumpserver.org/zh/docs/faq_windows.html
第一步的重新注册就是，更换网络应该没有影响，可以自己测试下，没关系。

**Comment by ibuler** [comment]
有问题请再次打开issue
