### ISSUE TITLE
1.3.3升级至1.4.0后, "资产管理" -> "资产列表" 功能无法正常工作, 错误信息`(1305, 'FUNCTION jumpserver.REGEXP_LIKE does not exist')`

### ISSUE THREAD

**Issue by sdjnmxd** [jumpserver/jumpserver#1654]
### 问题原因: 
因为jms 1.4.0版本所使用的`Django`为2.0.7版本, 该版本Django在使用Mariadb作为DB Engine时会触发一个Bug, 导致正则查询功能会使用Oracle的查询语法, 因此查询失败, 官方Ticket:  <https://code.djangoproject.com/ticket/29544>

### 解决方法:
临时解决方法: 
- 在jumpserver目录执行`pip install --upgrade django-filter==2.0.0`, 将Django更新至2.1版本即可修复该问题.

永久解决方法:
- 等jumpserver系统更新至下一个Release版本

<hr>

### 使用版本
1.4.0 (提交issue前已pull过Master最新代码并Restart过, 仍存在此问题)

### 问题复现步骤
1.  根据官方文档[更新升级](http://docs.jumpserver.org/zh/docs/upgrade.html)步骤将1.3.3版本jms升级至1.4.0 (`Jumpserver`, `Coco`, `Luna` 均进行了更新)
2. 使用有权限账号登陆jms系统
3. 在左侧导航点击"资产管理"
4. 页面无法打开, HTTP Code为500, 错误信息为: `(1305, 'FUNCTION jumpserver.REGEXP_LIKE does not exist')`
> 堆栈报告: [http://dpaste.com/1CV2PXW](http://dpaste.com/1CV2PXW)

### 具体表现
![image](https://user-images.githubusercontent.com/6388562/43830231-663492a6-9b33-11e8-956d-6cb2bffa832a.png)

### 其他
 - 使用MySQL作为数据库, 版本: `10.2.12-MariaDB`
 - `Web Terminal`无法显示服务器列表, `Coco`无法显示服务器列表, 除此之外其他功能工作正常

**Comment by liuxiaoxiong** [comment]
我今天在测试环境里安装了1.4版本的jumpserver，遇到的问题和你的一模一样，感觉是代码缺了。

**Comment by wojiushixiaobai** [comment]
@ibuler 可以复现

**Comment by sdjnmxd** [comment]
@wojiushixiaobai 经过测试, Master分支的最新代码依旧有相同问题, 堆栈几乎一样, 这里我就不贴了

### 具体表现
![image](https://user-images.githubusercontent.com/6388562/43946249-49f4894a-9cb7-11e8-9921-3ffd7ae9f074.png)

**Comment by ibuler** [comment]
这个错误应该是 数据库不支持正则表达式，错误栈信息可以更详细吗？看看具体哪里抛的异常

**Comment by sdjnmxd** [comment]
关于这个问题我尝试自行解决过, 经过查阅资料, `MySQL`在**5.x**版本是不支持堆栈报告中提到的`REGEXP_LIKE`操作的, 在8.x以上的版本才[支持](https://dev.mysql.com/doc/refman/8.0/en/regexp.html). 
而其他支持的数据库环境: `PostgreSQL`和`SQLite`似乎都支持

不确定你们测试时是否有在MySQL环境中测试过正则搜索这个行为, 我猜测可能和这个问题有关系. 更详细的堆栈报告稍后我会贴出.

**Comment by ibuler** [comment]
我的环境是 mysql 5.x，使用没有遇到问题

**Comment by ibuler** [comment]
报错的地是 
`root = cls.objects.filter(key__regex=r'^[0-9]+$')`

**Comment by sdjnmxd** [comment]
详细的堆栈报告在这: [click me](https://gistpreview.github.io/?67bbecff627df84e38d54aa8caadc8f5)
希望能帮到你们 😄

**Comment by sdjnmxd** [comment]
因为安全性等相关问题, 已经对堆栈报告里不影响Debug的部分数据做了脱敏处理, 脱敏后的数据均为: `[hidden]`如果需要未脱敏版的我可以发送至你邮箱

**Comment by ibuler** [comment]
按如下操作手动执行一下

```
(py3)➜  jumpserver git:(dev) ✗ cd apps
(py3)➜  apps git:(dev) ✗ python manage.py shell
In [1]: from assets.models import Node
In [2]: Node.objects.filter(key__regex=r'^[0-9]+$')
Out[2]: <QuerySet [<Node: Default>, <Node: Gaga>]>
```

**Comment by sdjnmxd** [comment]
执行结果: [click it](http://dpaste.com/1EBVTXK)

**Comment by ibuler** [comment]
django提供的api 

https://docs.djangoproject.com/zh-hans/2.1/ref/models/querysets/#regex 

所以应该是数据库的问题，上个版本也有如此的用法

**Comment by sdjnmxd** [comment]
在Django的issue上面找到了非常符合这个场景的Ticket: [Django 2.0.7 broke regex lookup on MariaDB](https://code.djangoproject.com/ticket/29544)

看起来最终是有对应的补丁发布, 想请问一下jms使用的Django是否包含了此补丁呢?

**Comment by liuxiaoxiong** [comment]
感觉就是这个问题，感觉各位大佬好专业。我把jumpserver目录退回1.3.3重新install requirements，发现就是django版本改回了1.11,然后再把jumpserver拉起来，一点问题都没有。

**Comment by ibuler** [comment]
升级到 django 2.1试试如何

**Comment by ibuler** [comment]
是否尝试了？

**Comment by sdjnmxd** [comment]
正在尝试... 遇到了一些无法启动的问题

**Comment by sdjnmxd** [comment]
升级至2.0.8问题解决, 2.1出现了无法启动的问题, 暂时放弃深入, 问题已经解决.

**Comment by ibuler** [comment]
```
pip install --upgrade django-filter==2.0.0

```

**Comment by ibuler** [comment]
我没有这个环境，麻烦升级到 2.1测试一下

**Comment by sdjnmxd** [comment]
运行`pip install --upgrade django-filter==2.0.0`后jms工作正常
命令回显: [click it](http://dpaste.com/184A8Z3)

**Comment by sdjnmxd** [comment]
已在issue主题内附加解决方法, 我先把issue close了, 非常感谢你们的帮助
