### ISSUE TITLE
请问是否支持通过API调用COCO和guacamole?

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#1658]
[简述你的问题]

##### 使用版本
1.3.3-2 

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

我的需求是：
通过调用JUMPSERVER API整合LUNA（COCO / guacamole） 到自有项目中。
请问支持吗？

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@HuanMeng0 可以调用api，开源的项目，自行研究开发即可。

**Comment by ibuler** [comment]
coco和guacamole和Jumpserver结合比较紧密，如果只是想利用部分功能暂时不可以

**Comment by ibuler** [comment]
有问题请再次打开issue
