### ISSUE TITLE
删除系统账户后，服务器的用户没有被删除

### ISSUE THREAD

**Issue by liulidong882004** [jumpserver/jumpserver#1664]
[简述你的问题]
删除系统账户后，服务器的用户没有被删除，/etc/sudoers规则也没有被清除
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0-2 
##### 问题复现步骤
1. [步骤1]创建系统用户，推送系统用户
2. [步骤2]删除系统用户

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@liulidong882004  这样操作可能会存在安全风险，因为这个系统用户可能被其他人使用，由用户自行处理比较好，后期开发老哥们可能会加入选项，让用户勾选是否在资产上删除该用户。
