### ISSUE TITLE
请问如何添加与ROOT同级的资产节点？

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#1665]
[简述你的问题]

##### 使用版本
1.4.0-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

请问如何添加与ROOT同级的资产节点？

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@HuanMeng0 不能，root是主节点，树形结构

**Comment by ibuler** [comment]
不支持，可以在root节点下分节点
