### ISSUE TITLE
历史会话升级后找不到录像文件

### ISSUE THREAD

**Issue by zhouyuyong** [jumpserver/jumpserver#1669]
[简述你的问题]
升级到1.4.0后 回放功能不好用了
##### 使用版本
1.4.0

##### 问题复现步骤
1. 从1.3.3 按照文档进行离线升级到1.4.0
2. 打开'历史回话',点击回放

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7124402/43944330-1c5219d6-9cb1-11e8-9bb8-7b1b31319507.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by zhouyuyong** [comment]
不知到什么原因 重启几遍好了, 但是有几个回话还是无法回放

**Comment by zhouyuyong** [comment]
更新后的很多历史回话都找不到录像文件,之前老版本没出现过,此问题我会继续观察

**Comment by zhouyuyong** [comment]
查看了media的文件记录, 确实少了不少会话的文件
![image](https://user-images.githubusercontent.com/7124402/43944925-36953fec-9cb3-11e8-828b-d60834c17db9.png)

web端的'历史会话'截图,有会话没有录像文件
![image](https://user-images.githubusercontent.com/7124402/43945044-93791ec2-9cb3-11e8-85e9-aa9c4f1ca9c4.png)

**Comment by ibuler** [comment]
有没有升级luna ?

**Comment by zhouyuyong** [comment]
一开始只升级了jumpserver ,发现这个问题后 升级了coco和luna

**Comment by BackFire** [comment]
我这里也找不到replay，升级了1.4.0

**Comment by wojiushixiaobai** [comment]
@zhouyuyong @BackFire 请查看安装文档的nginx部分，在server {} 加入
client_max_body_size 100m;  # 录像上传大小限制

这样操作后，大于1M的文件可以正常录像，但是部分录像的文件权限不对，暂时未查询到原因，可以自行写个shell临时解决下。

**Comment by ibuler** [comment]
新版本做了稍微写变更，放到 media/replay下了，不过同样兼容之前的方式

有问题请再次打开issue

**Comment by fengxianxp** [comment]
各位，找到解决的办法了么，看录屏文件，已经录到【jumpserver根目录】/data/media/replay/日期/文件名.replay.gz
![image](https://user-images.githubusercontent.com/42258930/44253637-d4612180-a232-11e8-916d-e83219309a06.png)

但是看nginx的错误日志，找的是【luna根目录】/replay/文件名
![image](https://user-images.githubusercontent.com/42258930/44253738-21dd8e80-a233-11e8-9bf3-02ae1f62bdaf.png)

知道怎样解决的话，有劳分享

**Comment by yangkghjh** [comment]
同样的问题

**Comment by ibuler** [comment]
@yangkghjh 你现在是哪个版本？可以qq联系我

**Comment by yangkghjh** [comment]
1.4.4 解决了
在 nginx  luna 的配置中增加了 ` try_files $uri / /index.html;` 一行
```
    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径,如果修改安装目录,此处需要修改
    }
```

**Comment by ibuler** [comment]
ok
