### ISSUE TITLE
资产节点名字不完整

### ISSUE THREAD

**Issue by BackFire** [jumpserver/jumpserver#1671]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0

##### 问题复现步骤
资产节点的名字，在1.3.2版本中是树状的完整路径，比如/ROOT/上海/nginx，
升级到1.4.0之后，资产节点的名字只剩下叶子名称，比如/ROOT/上海/nginx和/ROOT/杭州/nginx，显示出来都是nginx，造成混乱，搞不清是上海节点下的nginx，还是杭州的

##### 具体表现[截图可能会更好些,最好能截全]
![_2018-08-10_16-38-09](https://user-images.githubusercontent.com/5419211/43947971-0e3305ee-9cbc-11e8-8fe6-92bbfad73dbf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
我再考虑一下，解决了后麻烦测试一下

**Comment by ibuler** [comment]
已修改，请更新master分支

**Comment by BackFire** [comment]
已更新，有full value了
