### ISSUE TITLE
资产列表报错： OSError at /assets/asset/ [Errno 5] Input/output error

### ISSUE THREAD

**Issue by dc26002** [jumpserver/jumpserver#1674]
[简述你的问题]
资产列表报错：
OSError at /assets/asset/
[Errno 5] Input/output error

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.3-2 GPLv2
##### 问题复现步骤
1. [步骤1]资产管理
2. [步骤2]资产列表

##### 具体表现[截图可能会更好些,最好能截全]
OSError at /assets/asset/
[Errno 5] Input/output error

Request Method: | GET
-- | --
http://114.115.136.57/assets/asset/
1.11
OSError
[Errno 5] Input/output error
/opt/jumpserver/apps/assets/models/node.py in root, line 169
/opt/py3/bin/python3.6
3.6.1
['/opt/jumpserver/apps',  '/opt/py3/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/opt/py3/lib/python3.6/site-packages',  '/opt/jumpserver',  '/opt/jumpserver/apps']
星期六, 11 八月 2018 10:44:48 +0800

##### 其他

[注:] 完成后请关闭 issue

**Comment by dc26002** [comment]
[资产列表报错信息.docx](https://github.com/jumpserver/jumpserver/files/2279859/default.docx)

**Comment by wojiushixiaobai** [comment]
@dc26002 Input/output error 错误，看安装文档的开始部分

**Comment by ibuler** [comment]
有问题请再次打开issue
