### ISSUE TITLE
dockerfilce安装报错

### ISSUE THREAD

**Issue by shuyabin** [jumpserver/jumpserver#1678]
[简述你的问题]

##### 使用版本

 docker run -d -p 8080:80 -p 2222:2222 registry.jumpserver.org/public/jumpserver:1.0.0

##### 问题复现步骤
1. centos7.2安装了docker
2. 运行docker 容器

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/14884581/44002139-d09b7908-9e70-11e8-8fbd-711046fb88ad.png)

##### 其他
进入容器后看了一下nginx日志一直是端口被占用 netstat 发现并没有其他端口占用 修改了nginx.conf 到81 查看日志后.81端口被占用

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@wojiushixiaobai 会处理，将来会继续维护
