### ISSUE TITLE
Jumpserver创建组织的问题

### ISSUE THREAD

**Issue by GuoYingLong** [jumpserver/jumpserver#1680]
[简述你的问题]

##### 使用版本
[使用的Jumpserver版本 1.4.0-2 ]

##### 问题复现步骤
1.建议创建组织建议使用界面创建,admin的用户列表可以查看所有组织的用户
2. admin可以创建用户,也可以分配用户到组织
3.admin用户在创建的组织里添加用户,此用户可以访问所有组织

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. 界面的方式在付费包里体现，之所以这么安排也是不得已而为之，毕竟要养活自己
2. 3 同样

**Comment by GuoYingLong** [comment]
OK
