### ISSUE TITLE
coco异常关闭的会话不释放

### ISSUE THREAD

**Issue by lu604386020** [jumpserver/jumpserver#1682]
[简述你的问题]
在线会话异常退出的 不会自动释放，必须手动在控制台里终止会话。

##### 使用版本
1.0.0
1.3.3
##### 问题复现步骤
正常使用服务，肯定会出现不少异常退出的情况，这时候在控制台的在线会话里依旧可以看到。必须人工手动的终止，否则会越累计越多。造成服务器压力过大。
##### 其他
![1](https://user-images.githubusercontent.com/22024220/44016067-0e7eb4f2-9f06-11e8-9da1-7e995b377dcf.png)

**Comment by ibuler** [comment]
收到
