### ISSUE TITLE
希望增强作业中心功能，提出两点建议

### ISSUE THREAD

**Issue by awklinux** [jumpserver/jumpserver#1685]
[简述你的问题]

1. 增加一个默认执行的脚本，每次添加一个资产时自动执行，用来初始化系统参数，这个功能非常实用，个人认为这个需要很实用
2. 可以手动在作业中心创建作业，如果安装apache nginx mysql 这些，自己写ansible Playbook，可以选择指定的机器执行，这个算是批量执行命令吧，很需要

希望希望能考虑上面的建议

[注:] 完成后请关闭 issue

**Comment by HuanMeng0** [comment]
同样有这样的需求。

**Comment by ibuler** [comment]
第一个没考虑到场景，添加资产到jumpserver应该不需要什么操作

第二个需求开始做了

**Comment by ibuler** [comment]
有问题请再次打开issue
