### ISSUE TITLE
在多coco和guacamole的情况下，如何指定使用哪个终端连接？

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#1686]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
在多coco和guacamole的情况下，如何指定使用哪个终端连接？
具体需求情况：
资产遍布世界各地机房，就近资产部署coco和guacamole再和jumpserver建立通信。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@HuanMeng0 目前的版本还不支持由jumpserver来指定组件连接，都是基于nginx的负载或者HA。

@ibuler 老哥，后面要不要考虑弄一个。。这个貌似以前讨论过。有点印象

**Comment by HuanMeng0** [comment]
了解。

**Comment by ibuler** [comment]
ssh 是长连接，建立连接后无法重定向，所以没办法选择。

已知的方式是DNS智能解析，不同的地区解析到不同的coco

**Comment by wojiushixiaobai** [comment]
原来还有这种姿势。。了解了。。

**Comment by HuanMeng0** [comment]
了解。

**Comment by gxk001** [comment]
配置nginx 根据不同url 来分流怎么样？

/beijingcoco/ => upstream { beijingcoco}
/shanghaicoco/ => upstream {shanghaicoco}
