### ISSUE TITLE
资产授权后，登录终端显示多个系统用户，需要选择

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#1687]
[简述你的问题]
我在资产授权里，创建一个规则，有多个用户，对应多个系统用户，访问几组服务器。

![default](https://user-images.githubusercontent.com/40048968/44077980-f5907160-9fd7-11e8-8fcb-446ecff646a3.png)

当我使用其中一个用户登录终端，提示选择系统用户。
![default](https://user-images.githubusercontent.com/40048968/44078222-8d8d4b32-9fd8-11e8-807e-130c1d6d3021.png)

Web 终端：
![default](https://user-images.githubusercontent.com/40048968/44078321-c36dd49c-9fd8-11e8-816e-a0ba63d05d7c.png)

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
授权有误，自己检查下授权

**Comment by ibuler** [comment]
看不出问题在哪里？

**Comment by brucegogo** [comment]
我以test-linux用户登录终端，不应该显示yanyue用户

**Comment by brucegogo** [comment]
用户与系统用户之间没有唯一对应关系

**Comment by brucegogo** [comment]
难道我需要为每一个用户建立一个授权规则？不能一条规则为多个用户授予权限？

**Comment by wojiushixiaobai** [comment]
@brucegogo 
你一次授权出现了多个系统用户，或者多个授权有重复的授权
多个用户需要授权一个资产，同样的权限可以用组。
灵活授权，可以授权用户，授权用户组，授权资产，授权节点。
系统用户也有优先级，优先级高的用户自动登录，并行的情况下用户自己选择，会产生什么样的结果是因为你做了相应的操作

**Comment by brucegogo** [comment]
@wojiushixiaobai 

谢谢你的回复。
我理解你的意思。
但我觉得登录用户与系统用户应该有一个一对一的关系，或者一对多，而不应该是多对多。

像这种一个组内多个用户，每个用户有对应的系统用户，但他们具有相同的权限，相同的优先级。
我在授权的时候通过添加多个用户和系统用户,或者按组授权，都会出现我上面的现象。

感觉这个方式不是很合适。应该是每个用户登录后，默认就是自己对应的系统用户，直接选择资产登录。如果这个用户有对应多个系统用户的时候，才选择。

**Comment by ibuler** [comment]
用户和系统用户之间现在没有 一对一的关系，之所以没有采用这种方案有以下原因

1. 如果一个用户一个系统用户，需要把所有用户在资产上建立账号，小公司还好，大公司开发、测试、运维可能有很多人
2. 生产环境服务器保持纯净
3. 一个人在不同资产上的权限可能不一样，sudo在各个资产上怎么设置？授权时指定？如果授权规则相互覆盖呢？
4. 会带来推送的压力，添加用户就要推送资产，比较频繁

**Comment by brucegogo** [comment]
@ibuler 

有些理解，谢谢你的回复。
也非常感谢你们提供的这个产品。

**Comment by ibuler** [comment]
这个也是不得已的折中方法，毕竟 一对一是容易理解的

有问题欢迎讨论
