### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#1692]
[简述你的问题]
我使用Filezilla上传文件，
sftp能够连接到jumpserver,可以列出资产,也能看到系统用户，但是无法打开，没法上传文件

![default](https://user-images.githubusercontent.com/40048968/44135787-1654122e-a09d-11e8-8520-ba99be7832a4.png)

不太明白什么原因。

通过Linux ,也不行：
![default](https://user-images.githubusercontent.com/40048968/44135644-931b0480-a09c-11e8-8807-c522c4d9e326.png)

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.3-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by brucegogo** [comment]
大家都怎么上传文件的？

**Comment by brucegogo** [comment]
没有人了解吗？还是我描述的不清楚？

**Comment by wojiushixiaobai** [comment]
@brucegogo 通过jumpserver的ssh方式连接，确定可以正常登录资产

**Comment by brucegogo** [comment]
@wojiushixiaobai   SSH 登录没有问题。Web 终端登录也没有问题。
但是SFTP不行。

**Comment by wojiushixiaobai** [comment]
@brucegogo ssh的方式连接，发个图，通过coco连接，不是直接ssh到资产
我需要你证明你的通过jumpserver的跳板机可以使用yangyue01这个用户登录资产

**Comment by brucegogo** [comment]
@wojiushixiaobai 
我换个用户test01来测试。
如下图
SSH可以：
<img width="317" alt="ssh" src="https://user-images.githubusercontent.com/40048968/44844670-2156e600-ac7e-11e8-9c3d-fd53bef0243f.png">

Filezilla上能列出stg-monitor101上用户test01,但是无法读取列表：
<img width="508" alt="filezilla" src="https://user-images.githubusercontent.com/40048968/44844682-2ae04e00-ac7e-11e8-8ce2-fe995bd6aa81.png">

**Comment by wojiushixiaobai** [comment]
@brucegogo 你的ssh有问题看不出来？用户home目录权限不对

**Comment by brucegogo** [comment]
@wojiushixiaobai 
这个问题拖得比较久了。 这个home权限很奇怪，不知道在哪里设置的。 我在资产上已经设成777了，这里还是这样。
$ls -al /home/|grep test01
drwxrwxrwx   2 test01           Dev    4096 Oct 29 14:13 test01

**Comment by brucegogo** [comment]
@wojiushixiaobai 
问题已解决。
原因居然是我的系统用户没有设置保存密码。真是😓。。。


![default](https://user-images.githubusercontent.com/40048968/48936533-2a3a1980-ef46-11e8-844e-fbcc7ce7f8b2.png)
