### ISSUE TITLE
System user <xxx> and asset <xxx> protocol are inconsistent

### ISSUE THREAD

**Issue by fengxianxp** [jumpserver/jumpserver#1695]
[简述你的问题]

##### 使用版本
[Jumpserver7月17日下载的版本]

##### 问题复现步骤
1. [按照官方文档安装]
2. [System user <xxx> and asset <xxx> protocol are inconsistent]
2. [资产协议没有找到选择协议的地方]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42258930/44185177-61c64800-a145-11e8-96bf-746214a9b6e1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
更新下，并到jumpserver/utils 下执行
    $ sh 2018_07_15_set_win_protocol_to_ssh.sh

**Comment by fengxianxp** [comment]
@wojiushixiaobai 这个是针对windows主机的吧，我是linux主机也要执行这个么。

**Comment by fengxianxp** [comment]
升级到jumpserver1.4，这个问题能够解决。但是1.4录屏碰都问题，正在解决。
