### ISSUE TITLE
centos5.8无法推送用户，手动创建后，如何在每次推送后，不提示该机器

### ISSUE THREAD

**Issue by liulidong882004** [jumpserver/jumpserver#1696]
[简述你的问题]
我们有一台机器是centos5.8，运行ansible 报错，现已手动添加用户，但每次推送系统用户时都会报该机器的错误，想问下，如果修改 让系统认为他已经成功或者 如何让这个错误不再提示
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.02
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@liulidong882004 资产python版本需要大于等于2.6

**Comment by liulidong882004** [comment]
@wojiushixiaobai 还有一个问题，我怎么能拿到系统用户的公钥

**Comment by wojiushixiaobai** [comment]
@liulidong882004  在数据库里面

**Comment by ibuler** [comment]
#1730

**Comment by ibuler** [comment]
有问题重新打开issue
