### ISSUE TITLE
1.3.3升级1.4.0报数据库错误

### ISSUE THREAD

**Issue by xjj001** [jumpserver/jumpserver#1697]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.3
##### 问题复现步骤
按照文档升级是 走到cd utils && sh make_migrations.sh这一步 出错。

##### 具体表现[截图可能会更好些,最好能截全]
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NULL)' at line 1")

##### 其他
后重新删除jumpserver 重新安装1.4.0 也是报这个错误。

[注:] 完成后请关闭 issue

**Comment by AIKiller** [comment]
我是1.3.2 升级1.4.0 数据库报错。
![](http://ww1.sinaimg.cn/large/93d61c99ly1fubhicc0s7j211x0ipwh2.jpg)

**Comment by fengxianxp** [comment]
我升到1.4，这块没问题，我把新版的rpm和python依赖装了一遍，把数据库删掉重建了，把jumpserver的配置文件改了。
我碰到别的问题，正在研究。

**Comment by ibuler** [comment]
保留项目中上自带的migrations

**Comment by zyi1992** [comment]
> 保留项目中上自带的migrations

麻烦说下  具体操作的办法 我也遇到这个问题
