### ISSUE TITLE
Jumpserver v1.4，录屏（录像）文件无法正常打开

### ISSUE THREAD

**Issue by fengxianxp** [jumpserver/jumpserver#1704]
[简述你的问题]
录屏（录像）文件无法正常打开

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Jumpserver v1.4

##### 问题复现步骤
1. [按照官方文档正常安装]
2. [按照官方文档正常启动]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42258930/44255263-0a54d480-a238-11e8-8a1e-1b052b707b8a.png)

**查看录屏文件，已经录到【jumpserver根目录】/data/media/replay/日期/文件名.replay.gz**
![image](https://user-images.githubusercontent.com/42258930/44253637-d4612180-a232-11e8-916d-e83219309a06.png)

**但是看nginx的错误日志，找的是【luna根目录】/replay/文件名**
![image](https://user-images.githubusercontent.com/42258930/44253738-21dd8e80-a233-11e8-9bf3-02ae1f62bdaf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@fengxianxp luna安装完成没有，确定版本与jumpserver版本一致

**Comment by fengxianxp** [comment]
@wojiushixiaobai 感谢！我用的就是最新版了，前几天下载安装的，用的最新版。

![qq 3](https://user-images.githubusercontent.com/42258930/44258087-8c48fb80-a240-11e8-9563-842d4d4544f6.jpg)

**Comment by fengxianxp** [comment]
已经解决。具体解决过程如下：
nginx的配置文件，配置luna的部分，luna的index.html要配置，和官方的指导文档一样就行。
try_files $uri / /index.html;
