### ISSUE TITLE
测试资产出现fatal，但资产可达

### ISSUE THREAD

**Issue by SemiLavender** [jumpserver/jumpserver#1705]
测试资产无法通过但可以通过web连接到资产

##### 使用版本
jumpserver 1.4.0-2

##### 问题复现步骤
1. 测试资产可连接性出现：fatal: [*****]: UNREACHABLE! => {"changed": false, "msg": "Failed toconnect to the host via ssh: ssh_exchange_identification: Connection closed by remote host\r\n", "unreachable"
![image](https://user-images.githubusercontent.com/39018164/44260749-fe710e80-a247-11e8-9354-9761e8ce74d1.png)

2. 通过web端登入结果：
![image](https://user-images.githubusercontent.com/39018164/44260891-793a2980-a248-11e8-9eee-8b6a88b92a1c.png)

这是bug还是正常问题
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@SemiLavender 应该是ssh的连接数上限了，这个一般是资产ssh服务的问题

**Comment by SemiLavender** [comment]
@wojiushixiaobai 这个连接上限可以修改吗

**Comment by wojiushixiaobai** [comment]
@SemiLavender 如果确定是ssh连接数的问题，自己到资产设置就好，jumpserver没有并发限制

**Comment by chenrizhi** [comment]
我也遇到过这个问题，我的解决办法是删除.ssh/known_hosts相关的条目。出现这个问题是由于目标服务器HostKey发生了变化（重装过系统、删除过HostKey文件等），希望开发组能修复这个问题。 @wojiushixiaobai
