### ISSUE TITLE
怎么关联资产上已有的用户（系统用户）而不更改原来密码

### ISSUE THREAD

**Issue by psk071312** [jumpserver/jumpserver#1707]
[简述你的问题]
资产上原有用户user01，在jumpserver上创建同名系统用户。通过jumpserver登陆资产后，user01的密码被更改，使其不能通过其他方式进行密码登陆。
怎么才能概可以用jumpserver自动登陆，又保留原密码供其它方式正常登陆？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.4.0-2 GPLv2.

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@psk071312 创建系统用户时，取消勾选自动生成密码与自动推送，输入正确的系统用户和密码即可。

**Comment by psk071312** [comment]
@wojiushixiaobai 但我很多资产有这用户，而且密码都不一样。

**Comment by ibuler** [comment]
暂时不支持该情况
