### ISSUE TITLE
链接Windows-2008报错连不上Guacamole Server

### ISSUE THREAD

**Issue by leoowu** [jumpserver/jumpserver#1709]
[简述你的问题]
Web Terminal 连Windows-2008报错连不上Guacamole Server

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Version 1.3.3-2 GPLv2

##### 问题复现步骤
1. [步骤1] Sessions-Web Terminal  打开windows机器

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/6262327/44318085-12df2200-a467-11e8-80cb-7400d96ee19f.png)

docker logs -f jms_guacamole
----------------------------------------------
02:48:22.088 [http-apr-8080-exec-9] INFO  o.a.g.a.j.JumpserverAuthenticationService - 添加资产成功,userId: c3bcad5e-8967-4fde-b4ee-a56f6ca8a4d5, assetId: 94b0793b-05a3-44ba-924a-cad272393256, systemUserId: 96744c9b-da2c-4468-9d61-9edc955a812b
02:48:22.271 [http-apr-8080-exec-10] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:c3bcad5e-8967-4fde-b4ee-a56f6ca8a4d5
02:48:22.450 [http-apr-8080-exec-2] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: Non-numeric character in element length.
02:48:22.547 [http-apr-8080-exec-4] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: Non-numeric character in element length.
02:48:22.607 [http-apr-8080-exec-5] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:c3bcad5e-8967-4fde-b4ee-a56f6ca8a4d5

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@leoowu 把组件都更新到最新版本。

**Comment by ibuler** [comment]
难道是端口不对？

`guacamoleHTTPTunnelServlet - HTTP tunnel request failed: Non-numeric character in element length.`

**Comment by 932340583** [comment]
我也碰到这个问题了，代码是1.4版本的，都是最新的，我连windows server 2012也是报这个问题。也尝试过修复，但还是这样。
