### ISSUE TITLE
更改资产系统用户未生效

### ISSUE THREAD

**Issue by ptoeia** [jumpserver/jumpserver#1710]
[简述你的问题]
为何更改资产的系统用户后，并未生效
##### 使用版本
v1.3.3
##### 问题复现步骤
1. 设置了多个系统用户，在系统用户详情页，将某个系统用户绑定到某节点下的资产
但是，ssh登陆的时候LoginAs 列并未改变

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
看看是不是有的系统用户优先级比较高，如果有高优先级的，低的不会显示
