### ISSUE TITLE
windows手动登录模式下无法录像

### ISSUE THREAD

**Issue by sysant** [jumpserver/jumpserver#1712]
[简述你的问题]
windows 改为手动登录模式，无法在历史会话中看到录像，没有录像？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
jumpserver版本:Version 1.3.3-2 
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@sysant 请更新版本

**Comment by sysant** [comment]
最新版本1.4.0吗？没有看到这个修复呢！

**Comment by sysant** [comment]
我已经把所有组件更新了哦，不知道是不是我的表达不够清楚导致的，配置windows系统账号中  自动登录是有录像 改为手动登录则没有录像

**Comment by wojiushixiaobai** [comment]
@sysant 这个问题已经解决，如果不相信，在demo网站自己验证就好。

**Comment by wojiushixiaobai** [comment]
@sysant demo网站看7月26的rdp录像
