### ISSUE TITLE
windows 在web端登录后可以下载文件吗？

### ISSUE THREAD

**Issue by gengwan** [jumpserver/jumpserver#1714]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
在我的电脑里会有自动生成一个Guacamole RDP的盘，
上传：直接拖拽文件到windows窗口，然后文件会自动保存到Guacamole RDP这个盘根目录；
下载：把文件复制到Guacamole RDP盘的Download目录里，会自动下载到本地；
