### ISSUE TITLE
立即推送系统用户及测试系统连接无反应

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#1719]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
版本1.4.0

##### 问题复现步骤
立即推送系统用户无响应
![image](https://user-images.githubusercontent.com/20556236/44394671-5ec6bf80-a56a-11e8-9330-a92e55fa2793.png)

测试系统连接和更新硬件信息无反应
![image](https://user-images.githubusercontent.com/20556236/44394642-4fe00d00-a56a-11e8-806a-28256da7bbd1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
看看后台日志，如果还有问题，qq联系我
