### ISSUE TITLE
用户使用2048 bit的 dsa公钥无法上传，提示公钥错误

### ISSUE THREAD

**Issue by jaikewhh166** [jumpserver/jumpserver#1720]
[简述你的问题]
用户使用2048 bit的 dsa公钥无法上传，提示公钥错误
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Jumpserver 4
##### 问题复现步骤
1. [步骤1]
登录用户，上传公钥，1024的dsa公钥可以正常的上次，2048的无法上次，提示公钥错误，实际公钥是正确的
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
dsa最大长度为 1024, 不支持2048，以下是手动生成2048长度DSA key的截图，命令行也是不支持的

![image](https://user-images.githubusercontent.com/17382885/44561808-218c4880-a789-11e8-838c-fa90b9ccf9fb.png)

**Comment by ibuler** [comment]
有问题重新打开issue

**Comment by jaikewhh166** [comment]
命令行ssh-keygan是不支持大于1024的dsa，但其他软件是支持生成的，如SecureCRT，我们这边有用户就生成了2048的上传不上去，最后被迫重新生成1024的

**Comment by ibuler** [comment]
那推荐用户使用 2048的rsa吧
