### ISSUE TITLE
测试资产可连接性时报错

### ISSUE THREAD

**Issue by plckOne** [jumpserver/jumpserver#1726]
在添加资产后测试资产可连接性，报了如下错误，未弹出可连接，只弹出更新成功。
<img width="1416" alt="2018-08-22 2 10 40" src="https://user-images.githubusercontent.com/25770147/44445896-642d1400-a615-11e8-9aa4-b51ce35089f8.png">
管理用户上传了私钥，系统用户选择手动并没有让我填写密码，请问哪里设置的不对

**Comment by ibuler** [comment]
sudo需要密码
