### ISSUE TITLE
jumpserver 短暂卡死

### ISSUE THREAD

**Issue by wenfei3** [jumpserver/jumpserver#1728]
[简述你的问题]
jumpserver 短暂地卡死，已出现三次，每次在5分钟左右。

##### 使用版本
1.4

##### 问题复现步骤
没有找到稳定复现问题的办法

##### 具体表现

* 从本地使用ssh无法连接jumpserver服务器
* 访问jumpserver web页面返回404
* 已经通过jumpserver连接到资源服务器的命令窗口会卡死
* 查看当时的服务器状况，发现CPU的一个核被占满得到100%，在jumpserver从卡死状态恢复正常以后，依然保持99%以上

**Comment by 191801737** [comment]
我遇到的情况是 内存被耗尽

**Comment by wenfei3** [comment]
@191801737 
内存耗尽以后，会卡死吗？然后你们怎么处理的

**Comment by wenfei3** [comment]
补充一下截图：
这是我的阿里云的监控，部署jumpserver是在8月中旬，可以很明显看到从21号开始，CPU的使用率飙升，然后一直没有降下来，从21号开始，每天都会出现几次jumpserver卡死的情况。
![image](https://user-images.githubusercontent.com/25998180/44504955-53da6f00-a6d1-11e8-91a8-2937f6b8b19b.png)
不知道是什么原因导致CPU使用率突然飙升？如果有需要，我可以提供更多的日志或者截图。

下面是coco的strace
```
ps -ef|grep 21701
root     21701     1 29 8月14 ?       2-14:18:28 python3 ./cocod start -d
```

```
sudo strace -c -p 21701
strace: Process 21701 attached
strace: [ Process PID=21701 runs in x32 mode. ]
strace: [ Process PID=21701 runs in 64 bit mode. ]
^Cstrace: Process 21701 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 78.25    4.490581           3   1720817           epoll_wait
 13.58    0.779465           4    207910           epoll_ctl
  6.34    0.363850           3    103970    103938 recvfrom
  1.40    0.080129          10      8177        17 readlink
  0.20    0.011698          23       517           read
  0.07    0.004067         107        38           getdents
  0.03    0.001665           6       289           lseek
  0.03    0.001658          10       170           open
  0.03    0.001458           7       206           close
  0.02    0.001140           5       221           fstat
  0.01    0.000827          24        34        17 connect
  0.01    0.000821           5       170       153 ioctl
  0.01    0.000737           9        85        34 stat
  0.01    0.000572          15        39           sendto
  0.00    0.000144           8        19           openat
  0.00    0.000086           5        17           getsockopt
  0.00    0.000072           4        17           socket
  0.00    0.000039           2        17           setsockopt
------ ----------- ----------- --------- --------- ----------------
100.00    5.739009               2042713    104159 total
```
不太清楚epoll_wait和epoll_ctl是用来做什么的，有人了解吗？

**Comment by wojiushixiaobai** [comment]
@wenfei3 jumpserver和coco的log，发下图。

**Comment by wenfei3** [comment]
@wojiushixiaobai 
coco的日志
![image](https://user-images.githubusercontent.com/25998180/44511236-6bbded00-a6e9-11e8-81f9-3d44a806db20.png)

jumpserver没有error日志。

**Comment by wojiushixiaobai** [comment]
@wenfei3 log等级改成debug，重新发一下，如果是1.4.0，请更新一下代码。

**Comment by wenfei3** [comment]
@wojiushixiaobai coco日志的这些报错，我感觉是不正常的啊
刚刚把日志改成debug级别了，重启以后日志如下
![image](https://user-images.githubusercontent.com/25998180/44514937-e5f36f00-a6f3-11e8-824c-89d198eb25e0.png)

重启coco以后，cpu使用率降下来了，从99%恢复到20%-30%了

**Comment by wenfei3** [comment]
@ibuler 好的，期待新版本，目前只能依靠重启coco来过渡一下。

**Comment by liquanzhou** [comment]
我们目前使用也是依靠重启度日.
看起来像是ssh没有正常关闭.  
ssh,前台运行个web, 窗口断开后, 那个web依然活着

**Comment by wenfei3** [comment]
请问这个bug什么时候修复？？没有看到后续版本有修复的日志

**Comment by BaiJiangJie** [comment]
您好，请问你们使用的是哪个版本？目前最新的版本还没有用户反馈这个问题。 @liquanzhou @wenfei3

**Comment by liquanzhou** [comment]
是半年左右安装的,  Version 1.3.2-2 GPLv2.   当时应该是最新版. 应该是这个bug已经被修复了.昨天在Q群里已经咨询大家了

**Comment by BaiJiangJie** [comment]
好的，那请更新一下版本吧！

**Comment by wenfei3** [comment]
好的，我明天更新一下，感谢！
