### ISSUE TITLE
jumpserver内存飙高

### ISSUE THREAD

**Issue by AIKiller** [jumpserver/jumpserver#1734]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0
##### 问题复现步骤
1. 开启jumpserver之后，内存会有直线飙高的现象。
2. 白天有人在用的时候内存一直都在90%以上，晚上会出现周期性的飙高。
![](http://ww1.sinaimg.cn/large/93d61c99ly1fukiodg5ojj20ew08pq2u.jpg)
重启之后gunicorn相关进程仍然存在，需要手动kill才行
同时在线的人数一般不会超过8个人。
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
查看一下是什么进程导致的，guanicorn还是 coco？ 

如果重启后gunicorn还在，证明可能没有关闭gunicorn

**Comment by AIKiller** [comment]
通过htop查看的是guanicorn导致了内存占用率高，4个guanicorn进程能占到90%左右。 如果用`./jms restart ll -d` 的话guanicorn无法关闭，会重新开心的进程，之前的进程需要手动删除才行。 @ibuler

**Comment by AIKiller** [comment]
![](http://ww1.sinaimg.cn/large/93d61c99ly1fuknt5vyzjj20dt0a4weg.jpg)
这个是通过strace追踪guanicorn进程的结果。stat命令是在统计性能指标之类的吗？ @ibuler

**Comment by ibuler** [comment]
这个不清楚

**Comment by jym503558564** [comment]
手动删除后，问题是否解决了？
