### ISSUE TITLE
更新硬件信息报错

### ISSUE THREAD

**Issue by onchiao** [jumpserver/jumpserver#1739]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/42470468/44567604-c3219300-a7a5-11e8-887c-9ecb587706ad.png)

##### 其他
资产连接全部正常，部分服务器更新硬件会报错

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@onchiao 提示是超时，检查下资产
