### ISSUE TITLE
更新硬件信息/测试资产可连接性有问题

### ISSUE THREAD

**Issue by zhanglezxm** [jumpserver/jumpserver#1740]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
Jumpserver1.4

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/24641986/44568892-23ff9a00-a7ab-11e8-8cde-5e118fbdf79d.png)

2. [步骤2]
![image](https://user-images.githubusercontent.com/24641986/44568916-3bd71e00-a7ab-11e8-9e7b-ae996783cdc6.png)

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/24641986/44568939-57dabf80-a7ab-11e8-8317-9585d9535df8.png)

##### 其他
![image](https://user-images.githubusercontent.com/24641986/44569146-0252e280-a7ac-11e8-8aad-fc8a2828aefc.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhanglezxm 请更新代码，已经修复。

**Comment by zhanglezxm** [comment]
已更新代码已修复，太感谢了
