### ISSUE TITLE
Windows录像无法回放【Bug】

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#1742]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0
##### 问题复现步骤
1. [步骤1]
部分会话回放不了（1/10）
查看录像文件是存在的，但无法回放
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![jump1](https://user-images.githubusercontent.com/20255706/44577185-04746b80-a7c3-11e8-867a-667dfedd1d31.png)
这个是时间短的录像，文件是存在的，但无法回放
![jump2](https://user-images.githubusercontent.com/20255706/44577191-076f5c00-a7c3-11e8-896e-419623beca7a.png)
这个是比较长时间的，不是文件过大的原因，因为这个图片下面那个5h的录像都能正常回放的。
![jump3](https://user-images.githubusercontent.com/20255706/44577514-e4917780-a7c3-11e8-95e8-a7504ac39ddd.png)
仔细看录像文件的权限是有问题的，如图片。
![jump4](https://user-images.githubusercontent.com/20255706/44577538-f96e0b00-a7c3-11e8-8d9a-0063d33d7f0f.png)
看Nginx日志可以看到403的报错，请核实是否为Bug。
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 暂时还没找到问题，文件大于1M的录像有概率出现这个情况，请临时用shell解决下

**Comment by ChampionWolf** [comment]
临时配置了计划任务：
* */1 * * * /bin/bash chmod -R 755 /opt/jumpserver/data/media
此问题解决的时候能否回复一下？谢谢。

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 
推荐用 find /opt/jumpserver/data/media/replay/ -name "*.gz" -exec sudo chmod 644 {} \ 
自己加入时间判断即可

**Comment by ChampionWolf** [comment]
谢谢。
