### ISSUE TITLE
资源列表打开报错；无法登录远程机器

### ISSUE THREAD

**Issue by xiaobei-ihmhny** [jumpserver/jumpserver#1743]
[简述你的问题]

##### 使用版本
Version 1.4.0-2 GPLv2

##### 问题复现步骤
使用docker打好Image之后，发现两个地方出错，
1. 点击任务列表报错：
![image](https://user-images.githubusercontent.com/26052371/44616770-8f6b6980-a888-11e8-8c01-11456b65ed6a.png)
![image](https://user-images.githubusercontent.com/26052371/44616775-c17ccb80-a888-11e8-87c3-d880ada06493.png)
2. 无法登录资源机器
提示认证失败！
3. dockerfile为：
# pull down centos image
# 指定所创建镜像的基础镜像
# 最好把相关镜像下载到本地
FROM centos:7.3.1611
# 指定维护者信息
MAINTAINER ihmhny "xiaobei-ihmhny@163.com"
WORKDIR /opt
# 0. 安装相关依赖
RUN yum -y install wget sqlite-devel xz gcc gcc-c++ automake zlib-devel openssl-devel epel-release git libtool make
# 1. 指定环境变量，
ENV COCO_SERVER_ADDR= \
    COCO_SERVER_PORT= \
    GUACAMOLE_SERVER_ADDR= \
    GUACAMOLE_SERVER_PORT= \
    JUMP_SERVER_ADDR= \
    JUMP_SERVER_PORT= 
# 2. 编译安装Python3 和 Python 虚拟环境
ADD ./Python-3.6.1 /opt/Python-3.6.1
RUN cd /opt/Python-3.6.1 && \
	./configure && make && make install && \
	cd /opt && python3 -m venv py3 && source /opt/py3/bin/activate
# 3. 安装jumpserver环境
ADD ./jumpserver /opt/jumpserver
RUN cd /opt/jumpserver && source /opt/py3/bin/activate && \
	echo "source /opt/py3/bin/activate" > /opt/jumpserver/.env && \
	cd /opt/jumpserver/requirements && yum -y install $(cat rpm_requirements.txt) && \
	pip install --upgrade pip && pip install -r requirements.txt
## 3.4. 修改jumpserver配置文件，打开mysql
ADD ./config.py /opt/jumpserver/config.py
# 4. 安装 SSH Server 和 WebSocket Server: Coco
ADD ./coco /opt/coco
RUN cd /opt && source /opt/py3/bin/activate && \
	cd /opt/coco && \
	echo "source /opt/py3/bin/activate" > /opt/coco/.env && \
	cd /opt/coco/requirements && yum -y  install $(cat rpm_requirements.txt) && \
	pip install -r requirements.txt
ADD ./conf.py /opt/coco/conf.py
# 5. 安装luna
ADD ./luna /opt/luna
# 6. 安装nginx
RUN yum -y install nginx
RUN rm -rf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
# 7. 指定镜像的默认入口
COPY ./start.sh /usr/bin/
RUN chmod 777 /usr/bin/start.sh
ENTRYPOINT ["/usr/bin/start.sh"]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaobei-ihmhny 该任务没有正常执行（没有结果），所以报了异常，更新一下代码，已经解决了推送、资产测试和硬件刷新容易卡死的问题
