### ISSUE TITLE
user_edit.html  

### ISSUE THREAD

**Issue by dhh123** [jumpserver/jumpserver#175]
{% if group.id|int2str in groups_str %}  这个貌似有问题。。如果我获取groups_str='15 18 19'
group.id|int2str='8'的话。照样会判定到selected里面。。

**Comment by dhh123** [comment]
groups_str = ' '.join([str(group.id) for group in user.group.all()])  这个 group_str应该返回list才对啊？？

**Comment by ibuler** [comment]
![image](https://cloud.githubusercontent.com/assets/17382885/14100626/6aa7f2c0-f5c1-11e5-89f1-0429b9f2670b.png)

**Comment by dhh123** [comment]
"he" in b 也行。。。

**Comment by ibuler** [comment]
嗯，考虑欠佳

**Comment by ibuler** [comment]
@liuzheng712
