### ISSUE TITLE
创建新用户内网无法发邮件

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#1752]
由于 jumpserver 部署在内网，创建新用户时，无法发邮件。
是否可以把 重置密码连接 直接展示；或者生成一个初始密码，用户第一次登录提示修改密码。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@huangzx  内网自行搭建邮箱服务器，或者从终端里面直接提url，把log等级调整为debug，创建用户时就能看到，复制后发给用户，也可以自己修改下代码，把url显示到页面上。

**Comment by huangzx** [comment]
谢谢。
但还是希望官方改哦。

**Comment by ibuler** [comment]
用户可能连地址都不清楚

**Comment by ibuler** [comment]
暂时先不考虑
