### ISSUE TITLE
批量发布任务跳过jumpserver并记录操作问题

### ISSUE THREAD

**Issue by qq77moon** [jumpserver/jumpserver#1753]
[简述你的问题]

公司以前未采用跳板机，有很多自动化部署的脚本，如ansible、fabric、rsync等。采用jumpserver后自动化部署的脚本可能就不能执行，但又不能一台一台的登录部署。尝试采用过上面脚本的网关模式，但网关模式走的是默认的22端口，且需要目标主机的用户名和密码，这就失去了jumpserver跳转的意义。尝试修改过coco终端源码，新建了一个coco终端的端口接受命令转发，实现过fabric发起的命令能成功转发，但不能获取数据包的命令，无法记录这些命令。不知前辈思路解决，谢谢。

##### 使用版本
使用的版本是1.4.0-2

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
转发模式是隧道模式无法记录命令，因为两层数据加密
