### ISSUE TITLE
JumpServer LDAP已在web端配置完毕，如何通过已经匹配的域用户登录？

### ISSUE THREAD

**Issue by hanjlong** [jumpserver/jumpserver#1754]
[简述你的问题]

使用版本
[请提供你使用的Jumpserver版本 Version 1.4.0-2 GPLv2.]

JumpServer LDAP已在web端配置完毕，如何通过已经匹配的域用户登录？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hanjlong 参考这个文档 http://docs.jumpserver.org/zh/docs/faq_ldap.html
设置后重启jumpserver，用映射的属性直接登录即可。
