### ISSUE TITLE
通过API创建用户之后，没有发送邮件，导致无法设置密码

### ISSUE THREAD

**Issue by mianbao-cn-com** [jumpserver/jumpserver#1760]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新版本已修复
