### ISSUE TITLE
Windows资产 登录密码框下方 “大写已开启提示!” 无法显示

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#1762]
[简述你的问题]

##### 使用版本
Version 1.4.0-2 GPLv2.
##### 问题复现步骤
1. 手动登录模式连接上Windows资产后，按下capsLK键，密码输入框下方并未显示大写已开启的提示。
2. 偶发性的出现连接资产后自动切换到大写模式。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可能与库有关，暂时无法处理
