### ISSUE TITLE
多个终端产生的web访问问题

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#1764]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.3
##### 问题复现步骤
请问创建了两个终端，通过Web终端访问时，可以对终端进行选择吗？查看日志的结果是两个终端都有在发起请求，结果就连接失败了。
##### 具体表现[截图可能会更好些,最好能截全]
第一个coco的日志信息
![image](https://user-images.githubusercontent.com/20556236/44965471-69b92100-af68-11e8-9aa8-7a74c177ce88.png)
第二个coco的日志信息
![image](https://user-images.githubusercontent.com/20556236/44965517-9bca8300-af68-11e8-9b0e-4429df87f76a.png)
Web终端访问结果
![image](https://user-images.githubusercontent.com/20556236/44965532-ac7af900-af68-11e8-8b6c-8562c8adeba0.png)

**Comment by wojiushixiaobai** [comment]
@Sandra299 请参考最新安装文档的nginx部分处理。

**Comment by Sandra299** [comment]
好的，谢谢
