### ISSUE TITLE
coco中同时开启密码保护和密钥保护并未进行双认证【Bug】

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#1765]
[简述你的问题]

##### 使用版本
1.3.3

##### 问题复现步骤
coco配置中同时开启密码和密钥保护，但是在用户登录时只要密码正确就不会对密钥进行认证

##### 具体表现[截图可能会更好些,最好能截全]
coco配置
![image](https://user-images.githubusercontent.com/20556236/44965727-c1a45780-af69-11e8-9cf3-d08668c38803.png)
用户登录并未上传密钥
![image](https://user-images.githubusercontent.com/20556236/44965717-ae918780-af69-11e8-9389-948a60dfc5ca.png)

查看代码后发现造成的原因是并未增加密码密钥双认证的逻辑
![image](https://user-images.githubusercontent.com/20556236/44965790-2e1f5680-af6a-11e8-9768-479e5ac84e24.png)

**Comment by ibuler** [comment]
ssh协议不是这样的，只要一个能成功就不会验证下一个

**Comment by Sandra299** [comment]
我们有提出密码和密钥都需要认证的需求，但是操作之后发现只要成功一个就能够登录，已在逻辑上进行修改，可以实现双认证

**Comment by ibuler** [comment]
需要自己定制，不再讨论范围，有问题重新打开Issue
