### ISSUE TITLE
jumpserver支持redis集群吗？

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#1767]
jumpserver支持redis集群吗，如何配置？

**Comment by wojiushixiaobai** [comment]
@Coyote5 redis集群请参考redis官方文档说明

**Comment by Coyote5** [comment]
我理解需要把所有哨兵节点的IP:PORT配置到应用中（一个哨兵节点故障自动切换到其他节点），例如：
redis_nodes =  [{'host':'192.168.222.66','port':6378},
                    {'host':'192.168.222.66','port':6380},
                    {'host':'192.168.222.66','port':6381},
                    {'host':'192.168.222.66','port':6382},
                    {'host':'192.168.222.66','port':6383},
                    {'host':'192.168.222.66','port':6384},
                    {'host':'192.168.222.66','port':6385}
                   ]
请问在config.py中怎么修改配置，谢谢。

**Comment by npcomet** [comment]
@Coyote5 redis集群前面加nginx做代理 对外提供统一URL 更便于维护

**Comment by Coyote5** [comment]
是个办法
