### ISSUE TITLE
LDAP配置测试成功，LDAP用户无法登陆

### ISSUE THREAD

**Issue by 2han9we1** [jumpserver/jumpserver#1768]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0
##### 问题复现步骤
1. 录入AD域控信息
2. 测试通过并尝试登陆显示异常。

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/31976699/44996479-b3daea80-afda-11e8-9ac8-ff888489b05a.png)

![image](https://user-images.githubusercontent.com/31976699/44995876-9b1d0580-afd7-11e8-84e2-202d585a25fc.png)

##### 其他
提交后已重启jms。

[注:] 完成后请关闭 issue

**Comment by jielixiansheng** [comment]
我也遇到了这个问题，这个该怎么处理？

**Comment by ontherd** [comment]
我新升级的 JMS 版本 1.4.10 也同样遇到这个问题。注册成功 LDAP 域账号，重新登录时，报用户名已存在。
Exception Value: (1062, "Duplicate entry 'xxxx' for key 'username' ")。期待解决。
