### ISSUE TITLE
migrations会在JP运行期间发生变化吗

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1769]
[简述你的问题]
将JP打包成镜像，在JP运行一段时间之后（期间有添加资产、授权等操作），migrations会发生变化吗？就是以后能否从镜像升级，还是必须要从容器内升级？
##### 使用版本
1.3.2

##### 问题复现步骤
从镜像升级会报Table 'xxx' already exists的错误

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不会，Migrations代表表结构的变化
