### ISSUE TITLE
私钥密码问题，辛苦看下谢谢

### ISSUE THREAD

**Issue by luteng2018** [jumpserver/jumpserver#1790]
[简述你的问题]
用户私钥，通过xshell类似的软件登录，需要输入用户秘钥密码，新版中似乎没有看到密码，邮件也没有收到密码

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@luteng2018 确定你的端口正确，默认2222
私钥可以自己重置或者自己上传公钥
