### ISSUE TITLE
希望能添加嵌套多层网域的功能

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#1799]
[简述你的问题]

##### 使用版本
1.4.0-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

JUMPSERVER->网域1->网域2->资产

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
多级嵌套，请手动修改/root/.ssh/config，设置

**Comment by jarveis** [comment]
能不能给一个参考示例。
