### ISSUE TITLE
为什么新建资产的时候必须要有管理员账号？

### ISSUE THREAD

**Issue by Aaron0-wang** [jumpserver/jumpserver#1801]
[简述你的问题]
新建资产的时候能不能不填管理员账号？因为我公司领导认为堡垒机拿到管理员权限是一件危险的事情，所以把jumpserver排除出了备选方案。虽然其实可以乱填一个管理员账号，貌似也没有多大影响，我不需要你推送系统用户，也不需要你获取资产硬件信息。所以为什么创建资产管理员账号是必填项？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
可以随意指定一个管理用户，如果对此有疑问，可以手动修改代码，去掉管理用户的必填项
