### ISSUE TITLE
jumpServer LDAP已在web端配置完毕，可以通过web终端登陆服务器，但是重置下载密钥，不能通过Xshell，或者SecureCRT登陆。

### ISSUE THREAD

**Issue by l-duan** [jumpserver/jumpserver#1803]
[简述你的问题]
JumpServer LDAP已在web端配置完毕，可以通过web终端登陆服务器，但是重置下载密钥，不能通过Xshell，或者SecureCRT登陆。

##### 使用版本
[请提供你使用的Jumpserver版本  1.4.0-101 GPLv2.]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@l-duan 检查你登录的ssh端口，默认2222，不是22

**Comment by l-duan** [comment]
确认默认端口是2222，但是多次更换密钥但是不能登陆。

**Comment by l-duan** [comment]
![image](https://user-images.githubusercontent.com/12080822/45417305-6c2c2100-b6b4-11e8-8fb2-a19f0dc964e0.png)

![image](https://user-images.githubusercontent.com/12080822/45417330-7a7a3d00-b6b4-11e8-988a-481a73e4d412.png)

**Comment by wojiushixiaobai** [comment]
@l-duan 换一个客户端试试，你的证书路径可能不正确
