### ISSUE TITLE
在线会话，历史会话，命令记录页面报错。

### ISSUE THREAD

**Issue by ThirteenPo** [jumpserver/jumpserver#1806]
[简述你的问题]
点击“在线会话”，“历史会话”，“命令记录”页面，跳转到如下报错页面。
开始以为是python版本问题，把python升级上3.6.1之后重启机器，问题还是没有解决。
麻烦各位大哥大姐帮忙看一下，
折腾一天了。请求大哥大姐给个方向
selinux  firewalld 都是不可以状态
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.1-2 GPLv2.
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/38515532/45348691-e93a9600-b5e1-11e8-8d97-a81241d12671.png)
[](url)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ThirteenPo 还原如下操作
![qq20180912-074300](https://user-images.githubusercontent.com/24326988/45393658-8c7dc080-b65f-11e8-820e-94c11ee43b2c.jpg)

**Comment by ThirteenPo** [comment]
好了好了~谢谢楼上的大哥！！！
