### ISSUE TITLE
单台机器推送页面一点击就莫名其妙报错！！

### ISSUE THREAD

**Issue by Helloyanxuan** [jumpserver/jumpserver#1816]
[简述你的问题]
![image](https://user-images.githubusercontent.com/31366611/45434767-c7283d00-b6e1-11e8-8372-e11a17f4358c.png)

##### 使用版本1.4.1
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
1.4.1新增单台机器推送，但是页面一打开就报datatable初始化error,重复刷新页面会出现时而正常时而报这个弹窗错误，要么就是报500，查了一下后台日志报500原因是ajax_url: "{% url 'api-assets:system-user-assets' pk=system_user.id %}"这个反向解析找不到对应的视图，但是根据控制台报出来的api url是可以请求到数据的，报500错误信息如下：
Reverse for 'system-user-assets' not found. 'system-user-assets' is not a valid view function or pattern name
##### 其他

[注:] 完成后请关闭 issue

**Comment by Helloyanxuan** [comment]
测试环境都ok，但是发布到生产环境就会出现上述问题，请问这是不是datatable初始化出现问题导致，应该怎么处理

**Comment by wojiushixiaobai** [comment]
@Helloyanxuan 更新下代码，升级到最新版本即可。

**Comment by Helloyanxuan** [comment]
有一些地方做了二次开发的，所以不可以直接拉代码更新呢
