### ISSUE TITLE
通过jumpserver的api创建组织报错

### ISSUE THREAD

**Issue by JeffGannon** [jumpserver/jumpserver#1817]
[简述你的问题]
通过jumpserver的api创建组织报错

##### 使用版本
1.4.1

##### 问题复现步骤
通过http://127.0.0.1:8000/docs的api操作页面新增组织，创建报错

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/7790038/45477207-9d1f5b00-b773-11e8-8b09-e85225072703.png)
![2](https://user-images.githubusercontent.com/7790038/45477214-9f81b500-b773-11e8-8576-0eb5d966cc66.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
