### ISSUE TITLE
coco sftp网域连接认证失败

### ISSUE THREAD

**Issue by shuoliu1** [jumpserver/jumpserver#1818]
[使用网域功能sftp无法连接,日志显示认证失败
#系统用户不是自动登陆,需要手动输入密码的]

##### 使用版本
1.4.1
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 设置好网域和资产
2.配置系统用户,选择手动登陆,sftp客户端打开对应机器目录报错

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16146661/45526067-4748c280-b808-11e8-803f-542f4539b5b7.png)
![image](https://user-images.githubusercontent.com/16146661/45526075-516ac100-b808-11e8-89a7-43dbae8ca1d9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@shuoliu1 在旧版本尚未验证，但是在新版本未复现此问题。请更新至新版本后继续尝试。
