### ISSUE TITLE
未开启MFA，登陆的时候提示需要输入MFA的6位验证码

### ISSUE THREAD

**Issue by huangzgx** [jumpserver/jumpserver#1824]
[简述你的问题]
1. MFA功能并未启用，但是在Jumpserver系统上ssh登陆提示要输入6位验证码，详情见下图；
2. 使用Xshell登陆登陆终端导入pem密钥后登陆显示是灰色的，无法连接系统；

##### 使用版本
[Jumpserver版本 Version 1.4.1-2 GPLv2]

##### 具体表现[截图可能会更好些,最好能截全]
![20180915014015](https://user-images.githubusercontent.com/39511964/45566235-a4845880-b888-11e8-807a-7754532ee1fe.png)

![20180915014545](https://user-images.githubusercontent.com/39511964/45566406-2f655300-b889-11e8-9279-94f4e6ccc1e3.png)

![20180915014119](https://user-images.githubusercontent.com/39511964/45566245-a9490c80-b888-11e8-9976-72e72fdacdf7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by james0479** [comment]
请问解决了吗？
