### ISSUE TITLE
在线会话无法清理

### ISSUE THREAD

**Issue by myhoop** [jumpserver/jumpserver#1825]
[简述你的问题]
在线会话无法清理，点击中断无效果。很多都是历史的会话了，已经没有用了。还是显示在在线会话里。

##### 使用版本
1.4.0-2

![image](https://user-images.githubusercontent.com/18286793/45593962-ad7a4480-b9c4-11e8-82a0-907119f6221b.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@myhoop 更新到1.4.1版本

**Comment by switchchow** [comment]
请检查下资产里是否有已经下线的机器，将其清理掉；重启coco进程；再来检查在线会话，清理不掉的在线会话，到目标机器检查，是否有登录时间很早的终端，将其踢掉，再来看‘在线会话’是否还存在，存在再次清理试试；

**Comment by sky-sunny** [comment]
同样的问题 最新的1.14.10
