### ISSUE TITLE
jumpserver求助：：ModuleNotFoundError: No module named 'django_auth_ldap'怎么回事，安装不上这个模块

### ISSUE THREAD

**Issue by yyzusb** [jumpserver/jumpserver#1827]
没有  django_auth_ldap模块，我安装了，但是显示“
    ----------------------------------------
Command "/opt/py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-q_bh_i_h/python-ldap/setup.py
';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3g39un6l/install-record.txt --single-version-externally-managed --compile --install-headers /opt/py3/include/site/python3.6/python-ldap" failed with error code 1 in /tmp/pip-install-q_bh_i_h/python-ldap/
”
无法安装，这个问题，怎么解决

**Comment by wojiushixiaobai** [comment]
@yyzusb 有版本要求，直接安装不能使用
