### ISSUE TITLE
使用系统用户不能登录资产机子

### ISSUE THREAD

**Issue by jiaminxu** [jumpserver/jumpserver#1828]
[是不是现在的版本不能自动创建系统用户了？我记得我更新之前0.5版本会ansible 推送然后创建用户信息的？现在登录就报Authentication failed]

##### 使用版本
 1.4.1-2 GPLv2.]

##### 问题复现步骤
1. [创建管理用户 输入正确的登录信息账号和密码]
![image](https://user-images.githubusercontent.com/20829899/45610197-bc78f980-ba8d-11e8-93b3-b4aaa2615d47.png)

2. [创建系统用户  此用户在资产的机子上并不存在]
![image](https://user-images.githubusercontent.com/20829899/45610228-db778b80-ba8d-11e8-8f4d-929c18124507.png)

3.[通过2222端口登录报错]
![image](https://user-images.githubusercontent.com/20829899/45610255-ef22f200-ba8d-11e8-8309-88b81c912d4f.png)
![image](https://user-images.githubusercontent.com/20829899/45610338-2f827000-ba8e-11e8-9a7e-4e98533cff1d.png)

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/20829899/45610197-bc78f980-ba8d-11e8-93b3-b4aaa2615d47.png)
![image](https://user-images.githubusercontent.com/20829899/45610228-db778b80-ba8d-11e8-8f4d-929c18124507.png)
![image](https://user-images.githubusercontent.com/20829899/45610255-ef22f200-ba8d-11e8-8309-88b81c912d4f.png)
![image](https://user-images.githubusercontent.com/20829899/45610338-2f827000-ba8e-11e8-9a7e-4e98533cff1d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
系统用户的名称可以点击，右边有测试按钮
