### ISSUE TITLE
centos6.5 安装jumpserver，Error loading MySQLdb module. Did you install mysqlclient?

### ISSUE THREAD

**Issue by yyzusb** [jumpserver/jumpserver#1829]
我安装4.0出现如下问题

django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?

大家是怎么解决的？

**Comment by BigbigY** [comment]
请问下解决了吗

**Comment by wojiushixiaobai** [comment]
@yyzusb 请贴上详细的log

**Comment by BigbigY** [comment]
@wojiushixiaobai 我是初始化的数据库的时候遇见的，我在apps/manage.py 加入以下2行解决这步，但是在启动jms的时候又启动失败，看logs/celery.log日志中有以下截图错误
```
import pymysql
pymysql.install_as_MySQLdb()
```
![image](https://user-images.githubusercontent.com/16998173/46071449-9d2b4c00-c1b2-11e8-97c7-7e2b40ecfcdb.png)

**Comment by BigbigY** [comment]
centos6.5安装的mariadb

**Comment by wojiushixiaobai** [comment]
@yyzusb 6.5安装的mariadb我记得mysql版本是5.1，需要至少5.5

**Comment by zhangtianguang** [comment]
我是在ubuntu上面装的，也是报这个错，不知道怎么解决
