### ISSUE TITLE
任务列表输出Page not found

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1831]
[简述你的问题]
作业中心的任务列表，任何一个任务的输出都报404

##### 使用版本
1.4.1-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26393744/45668994-2d351a00-bb51-11e8-954c-6f2529ae5418.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yaoluoye 

清理 celery
    $ source /opt/py3/bin/activate
    $ cd /opt/jumpserver/apps
    $ celery -A ops purge -f

然后重启下jumpserver的进程，这个问题已经知道，需要等待解决

**Comment by ibuler** [comment]
已修复
