### ISSUE TITLE
组织、用户和资产的关系

### ISSUE THREAD

**Issue by BackFire** [jumpserver/jumpserver#1834]
[简述你的问题]
同一个用户只能属于一个组织。同一个自然人要使用两个组织的资产，就需要建立两个不同的用户，这样不方便。另外，在不同组织之间迁移用户，从免费版的页面上没法操作。

建议：
用户跟组织没有隶属关系，用户的维护，放在全局。资产的维护、用户跟资产授权关系的维护，放在组织里面。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.1-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@BackFire 一个用户可以在多个组织

**Comment by wojiushixiaobai** [comment]
@BackFire  代码里面有update的用法，或者直接修改数据库
