### ISSUE TITLE
有办法连接linux的图形界面吗？

### ISSUE THREAD

**Issue by zxl78585** [jumpserver/jumpserver#1836]
[简述你的问题]
我使用的是1.4.1，没有找到在哪里使用linux的图形界面，我要通过jumpserver连接到机房，给centos6.8上安装oracle数据库

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by leniy** [comment]
@zxl78585 
linux为啥要用图形界面，桌面用户用不着跳板机，服务器用户用不着图形界面啊

**Comment by zxl78585** [comment]
@leniy 场景是这样的，如果讲jumpserver用于生产环境，肯定是所有的机器都走堡垒机（要保留服务器操作历史记录的，供审计用），服务器不是完全的图形化的，就是安装了x11，想通过设置export 本机ip:0.0，本地启动一个x11服务，将图形展示到本机。安装orale数据库集群，好像静默方式不太号整。

**Comment by leniy** [comment]
@zxl78585 
额，我们部署业务，都是先在公网环境全部部署完，然后网线一拔切换到内网^_^
