### ISSUE TITLE
ssh登陆超时设置不生效

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#1837]
[ssh登陆超时设置不生效]
根据文档中配置后，登陆没操作自动断开不生效
```
$ vim /opt/coco/conf.py
# 把 SSH_TIMEOUT = 60 修改成你想要的数字 单位为：秒
```

##### 使用版本
[Version 1.3.1-2 GPLv2]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/16998173/45727579-ec8fdc00-bbf6-11e8-947b-e202185310b4.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@BigbigY 这个是连接超时，ssh连接资产的超时时间
你问的是ssh空闲断开时间，这个在web页面系统设置-安全设置里面
![qq20180919-171555](https://user-images.githubusercontent.com/24326988/45744031-0863a400-bc30-11e8-84db-ad98ff9459b6.png)

**Comment by BigbigY** [comment]
你好，我的版本是Version 1.3.1-2 GPLv2，并没有这个功能
![image](https://user-images.githubusercontent.com/16998173/45744753-deab7c80-bc31-11e8-9e11-4cdad81e20dd.png)
我想做到的就是连接到jumpserver终端，在下图所示，不做任何操作会有办法让它超时退出吗
![image](https://user-images.githubusercontent.com/16998173/45744838-0b5f9400-bc32-11e8-9048-9512453d94f7.png)
