### ISSUE TITLE
终端心跳设置无效

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1840]
[简述你的问题]
系统设置中的终端设置的心跳间隔设为5秒，coco中心跳设置为3秒，但是停止coco后很久，终端管理中的在线状态才会改变

##### 使用版本
1.4.1

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26393744/45745854-5084c580-bc34-11e8-8ec6-630c8281d5e0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yaoluoye 目前是这样的
