### ISSUE TITLE
显示节点下的主机列表需要在几秒后操作

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1842]
[简述你的问题]
输入g显示节点列表，在几秒内输入数字会直接登陆相应的主机，若是过几秒在输入数字则显示该节点下的主机列表。
就是说要看节点下的主机列表，需要等几秒

##### 使用版本
1.4.1

##### 问题复现步骤
1. 通过ssh登陆到JP
2. 输入g显示节点列表
3. 等待几秒后输入节点编号，立即输入编号会直接登陆到对应主机中
4. 显示主机列表

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26393744/45792055-ca619100-bcbe-11e8-97eb-68ebe4d48890.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yaoluoye g的用法是
g 回车出现列表
g1  选择id 1
g2   选择id 2
