### ISSUE TITLE
能够ssh登录jumpserver服务器，但sftp失败

### ISSUE THREAD

**Issue by Aaron0-wang** [jumpserver/jumpserver#1845]
[简述你的问题]
linux系统，测试连接
ssh -p2222 admin@10.10.80.42 没问题，正常登陆
sftp -p2222 admin@10.10.80.42 提示Permission denied, please try again.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.2
##### 具体表现[截图可能会更好些,最好能截全]
我使用tail -f /var/log/secure来查看登录日志
ssh -p2222 admin@10.10.80.42正常登陆了，而且日志没有任何反应
然后尝试sftp -p2222 admin@10.10.80.42 ，无法登录
![_ _20180920141549](https://user-images.githubusercontent.com/38186870/45799464-37395300-bce0-11e8-9d03-83849c9a86f5.png)
此时日志提示无效的用户名
![_ _20180920141627](https://user-images.githubusercontent.com/38186870/45799496-56d07b80-bce0-11e8-8efc-6dc0e3eda0aa.png)
我想知道这是为什么？
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@Aaron0-wang sftp -P  大写的P 不是小写的p
PpPpPp

**Comment by Aaron0-wang** [comment]
非常感谢，tmd我想抽自己。。。
