### ISSUE TITLE
Unknown column 'users_user.source

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#1849]
[简述你的问题]
1.3.1离线升级1.4.1

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16998173/46000874-67b42f00-c0dc-11e8-8704-dee9bd686e28.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BigbigY** [comment]
![image](https://user-images.githubusercontent.com/16998173/46003454-2a9f6b00-c0e3-11e8-869c-fc1a1b11b64c.png)

在更新执行表结构更新抛异常
![image](https://user-images.githubusercontent.com/16998173/46003517-473ba300-c0e3-11e8-8b52-967b481127fc.png)

**Comment by wojiushixiaobai** [comment]
@BigbigY 对，1.4之后的版本因为django更新到了2.1，所以需要mysql版本最低5.6

**Comment by wojiushixiaobai** [comment]
@BigbigY 已验证，mysqlserver需要版本大于等于5.6
mariadb 5.5.6及以上
