### ISSUE TITLE
使用vim的时候:wq保存的时候，终端就是卡死

### ISSUE THREAD

**Issue by jijianming** [jumpserver/jumpserver#1850]
[简述你的问题]
使用vim的时候:wq保存的时候，终端就是卡死，无法操作只能断开重新连接

##### 使用版本
Version 1.4.0-2

##### 问题复现步骤
1. vim xxx.html
2. :wq就卡死

##### 其他

[注:] 完成后请关闭 issue

**Comment by jijianming** [comment]
补充：
重连终端后、发现后台进程还有vim xxx.html的进程。

**Comment by wojiushixiaobai** [comment]
@jijianming 多大的文件，大概多少字节。我看下能不能复现

**Comment by jijianming** [comment]
才4K 
du -sh templates/cloud_instance_type_tx.html    
4.0K    templates/cloud_instance_type_tx.html

**Comment by jijianming** [comment]
ssh, 用的CRT

**Comment by wojiushixiaobai** [comment]
@jijianming 已验证，无法复现，使用vim打开4M大小的文件，然后修改保存
没有异常，可以提供录像，就在demo网站

**Comment by jijianming** [comment]
好、等我这边在遇到这种情况，把日志帖出来。

**Comment by ibuler** [comment]
如还有问题重新打开issue
