### ISSUE TITLE
gunicorn 运行内存占用过高

### ISSUE THREAD

**Issue by xingyueGK** [jumpserver/jumpserver#1851]
[简述你的问题]
运行一段时间后gunicorn占用的内存就会增高

##### 使用版本
1.4.1-2
##### 问题复现步骤
每次运行一段时间就要重启一次

##### 其他

[注:] 完成后请关闭 issue

**Comment by leniy** [comment]
@xingyueGK 
docker可以设置内存限制，然后你再把这个container设置一下定时重启就可以了。
docker本来就是干这个用的
