### ISSUE TITLE
特殊命令黑名单或命令过滤

### ISSUE THREAD

**Issue by duanzhanling** [jumpserver/jumpserver#1855]
在https://github.com/jumpserver/jumpserver/issues/64 中看到说已经支持该功能了，但是在
v1.4.1版本没有看到命令过滤功能。
请问是不是没有开发还是？

**Comment by duanzhanling** [comment]
好的，谢谢，辛苦了 @wojiushixiaobai

**Comment by ibuler** [comment]
已支持，1.4.2版本，今天release的
