### ISSUE TITLE
不能清除过期session

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#1858]
[简述你的问题]
用keepalived做健康检查，每次curl就会在django_session中生成一条记录，几天下来有几十万条。能否在代码里执行自动清除过期session的功能，或者提供一个不生成session的健康检查方法。

##### 使用版本
1.4.1

##### 问题复现步骤
清除脚本如下，但过期的session一条也没删除掉。
#!/bin/bash

source /opt/py3_jump/bin/activate
exec python /opt/jumpserver/apps/manage.py clearsessions

##### 其他

[注:] 完成后请关闭 issue

**Comment by yaoluoye** [comment]
问题依旧，在8点41分执行清理，早上2点47分过期的数据依然存在。
![image](https://user-images.githubusercontent.com/26393744/46181903-ff8f6400-c2fa-11e8-8b7a-8288b2e3b1a2.png)

**Comment by wojiushixiaobai** [comment]
@yaoluoye 请检查你设置的过期时间是多久
配置在jumpserver/apps/jumpserver/settings.py

**Comment by yaoluoye** [comment]
我没有改动settings.py，不知道django_session中的记录是否准确。从数据库日志来看，是根据session_key删的，而不是expire_date，莫非session过期是另外的表控制的。

**Comment by yaoluoye** [comment]
curl产生的session_data是相同的，可以用脚本直接删除，不需要clearsessions了。
