### ISSUE TITLE
1.4.0 升级 1.4.1 "Unknown column 'settings.encrypted' in 'field list'"

### ISSUE THREAD

**Issue by AiotCEO** [jumpserver/jumpserver#1865]
1.4.0 升级 1.4.1 "Unknown column 'settings.encrypted' in 'field list'"
![2018-09-28 10-45-41](https://user-images.githubusercontent.com/18225207/46185311-f1960f00-c30b-11e8-8233-68ff40c9c373.png)

**Comment by wojiushixiaobai** [comment]
@AiotCEO 升级过程有错误，请检查下

**Comment by AiotCEO** [comment]
问题已经解决，原因不在升级过程

1.4.0 和 1.4.1 的表结构不一样，手动改表结构才可以升级
