### ISSUE TITLE
docker安装的jumpserver删除终端后怎么恢复

### ISSUE THREAD

**Issue by bruce-zu** [jumpserver/jumpserver#1866]
[简述你的问题]

使用docker安装的jumpserver，终端删除后怎么重新注册，现在终端列表为空。
##### 使用版本
1.0.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bruce-zu 进入容器，重新注册即可
docker exec -it jms_server /bin/bash

**Comment by bruce-zu** [comment]
@wojiushixiaobai  谢谢，已解决。
