### ISSUE TITLE
web终端luna windows 无法复制目标主机内容到本地

### ISSUE THREAD

**Issue by kongfei09** [jumpserver/jumpserver#1870]
[简述你的问题]

在使用web终端Luna Windows连接后，无法把本地内容复制到远程机器中。（可以把远端内容复制到本地）

##### 使用版本
Version 1.4.1-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ctrl+alt+shift弹出来，使用这中转一下

**Comment by kongfei09** [comment]
非常感谢





在 2018-10-12 17:04:57，"老广" <notifications@github.com> 写道：


ctrl+alt+shift弹出来，使用这中转一下

**Comment by xiaofeng283** [comment]
现在有方法能直接粘贴吗？

**Comment by ballghost** [comment]
有办法直接从外部复制了，然后直接粘贴到windows系统里吗？
通过“ctrl+alt+shift”方式实在是太麻烦了，完全不符合正常使用习惯
