### ISSUE TITLE
最后一条命令  "命令记录"  查看不到

### ISSUE THREAD

**Issue by slan77** [jumpserver/jumpserver#1871]
[简述你的问题]
通过堡垒机登录linux 主机的最后一条命令  在"会话管理"--》"命令记录"  查看不到

##### 使用版本
Jumpserver 1.4

##### 问题复现步骤
1. 通过jumperserver 登录到主机，进行操作后退出。 最后一条命令是exit
2. 在命令记录查看命令 最后一条命令是 cd 

##### 具体表现[截图可能会更好些,最好能截全]
![1538278162838](https://user-images.githubusercontent.com/15992537/46253018-8469b180-c4a4-11e8-89ca-e45e4ce94a4b.jpg)

<img width="984" alt="qq20180930-113002 2x" src="https://user-images.githubusercontent.com/15992537/46253007-68661000-c4a4-11e8-9f84-6cfcfdf1b551.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
等一会儿是否可以看到，周期性上传命令的

**Comment by slan77** [comment]
最后一条命令一直不会上传。

**Comment by Aaron0-wang** [comment]
@wojiushixiaobai 我也发现了这个问题，在一次会话中：
输入第1条命令，不会记录，
输入第2条命令，显示记录了第1条命令，
输入第3条命令，显示记录了第2条命令，
以此类推，永远都少记录一条命令（如果连接上只输入一条命令就×掉，就没有命令记录）

**Comment by wojiushixiaobai** [comment]
@slan77 @Aaron0-wang 嗯，已经验证存在这个问题

**Comment by ibuler** [comment]
已处理
