### ISSUE TITLE
关于jumpserver通过ansible更新硬件信息的问题

### ISSUE THREAD

**Issue by zhanglezxm** [jumpserver/jumpserver#1873]
[简述你的问题]
我们这边的场景是位于jumpserver后端的服务器ssh时是禁止root登录的，只能登录work用户后在su到root用户；按照文档上所说，jumpserver上的管理用户是用来推送系统用户和获取资产硬件信息的，我在jumpserver创建了一个管理用户为root，系统用户为work；这个时候无法获取资产硬件信息，不知道是否有其他方式

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
sudo NOPASSWD ALL的权限
