### ISSUE TITLE
新加资产没有推送系统用户

### ISSUE THREAD

**Issue by iiopstianya** [jumpserver/jumpserver#1874]
[简述你的问题]
新加资产没有推送系统用户

##### 使用版本
Version 1.4.1-2 GPLv2

##### 问题复现步骤
1. 添加了资产，并且也已经授权，可连接性 正常，连硬件信息都获取到了，但是 系统用户并没有推送到资产上面去
2. 昨天添加了20多台都正常，今天添加就出问题了

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/43904178/46569977-b640b380-c98f-11e8-97b9-325ec8e33de5.png)
![image](https://user-images.githubusercontent.com/43904178/46569991-01f35d00-c990-11e8-9c36-4fa68abfb178.png)
![image](https://user-images.githubusercontent.com/43904178/46570006-76c69700-c990-11e8-9051-90b116424e29.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by vincent927** [comment]
@iiopstianya 请问下你怎么解决的，我碰到同样的问题
