### ISSUE TITLE
【Bug】系统用户设置为改为手动登陆，不需要密码仍然可以登陆

### ISSUE THREAD

**Issue by iiopstianya** [jumpserver/jumpserver#1875]
[简述你的问题]
系统用户设置为改为手动登陆，不需要密码仍然可以登陆

##### 使用版本
Version 1.4.1-2 GPLv2

##### 问题复现步骤
1. 系统用户最开始是设置的自动登陆，在web终端那里是可以自动登陆的

2. 后面改为手动登陆，虽然会有提示让输入密码 ，但直接回车，或者随便输入几个字母仍然可以登陆进去
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/43904178/46570622-8e564d80-c999-11e8-9235-8b8ab27c10a5.png)

回车登陆截图
![image](https://user-images.githubusercontent.com/43904178/46570633-acbc4900-c999-11e8-84d3-0c10fca99b10.png)
随便输入几个字母登陆截图
![image](https://user-images.githubusercontent.com/43904178/46570639-c362a000-c999-11e8-9b16-faf1ab5ca381.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
已验证，存在这个问题

**Comment by ibuler** [comment]
已fix，等待push
