### ISSUE TITLE
users_user表中的_otp_secret_key字段是通过什么加密方式保存的

### ISSUE THREAD

**Issue by ninglianjie** [jumpserver/jumpserver#1876]
[简述你的问题]
我已有一些Google Auth，不想让用户换成新的，想把这些数据导入到users_user表中，但是_otp_secret_key字段不知道是用的什么加密算法

##### 使用版本
1.4.1

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/1515239/46603304-42381400-cb25-11e8-95d0-ca3f4f748a3d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ninglianjie** [comment]
谢谢，搞定了

**Comment by sukabuliet** [comment]
> 谢谢，搞定了



> 谢谢，搞定了

你好，请问是加密的代码是在哪里的？
