### ISSUE TITLE
web sftp能否添加浏览Linux根目录的功能

### ISSUE THREAD

**Issue by badgtgcs** [jumpserver/jumpserver#1883]
[简述你的问题]
web sftp可不可以添加浏览Linux根目录的功能？
比如：用户要上传文件到路径/usr/local/test

##### 使用版本
1.4.2

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@badgtgcs 参考 [docs](http://docs.jumpserver.org/zh/docs/faq_sftp.html)
