### ISSUE TITLE
录像目录映射后不能回放，但是可以录制新的录像。

### ISSUE THREAD

**Issue by lindong629** [jumpserver/jumpserver#1887]
Jumpserver版本 1.4.1

1. [使用FTP挂载录像目录到本地]
curlftpfs -o codepage=gbk ftp://test:123456@192.168.1.23/replay /opt/jumpserver/data/media/replay

2. [步骤2]
录像会存储在FTP服务器的目录下

3. [步骤3]
使用luna/replay回放时白屏。
![image](https://user-images.githubusercontent.com/32184005/46675865-f6af6400-cc11-11e8-880e-78c98964d218.png)

![image](https://user-images.githubusercontent.com/32184005/46675963-28282f80-cc12-11e8-87ef-0e09834cf56e.png)

4. [步骤4]
如果将目录文件copy到本地后回放正常。

curlftpfs -o codepage=gbk ftp://test:123456@192.168.1.23/replay /home/jumpserver/replay

cp -r /home/jumpserver/replay /opt/jumpserver/data/media/

![image](https://user-images.githubusercontent.com/32184005/46675516-2dd14580-cc11-11e8-94ff-89b8d2e4fb85.png)

5. [步骤5]
我有试过通过本地目录进行映射故障依旧存在。（将FTP挂载取消，所有文件存放在/home/jumpserver/replay后进行目录映射）

ln -nsf /home/jumpserver/replay /opt/jumpserver/data/media/

**Comment by wojiushixiaobai** [comment]
@lindong629 验证后无法复现，请检查文件及文件夹权限是否正确

**Comment by lindong629** [comment]
@wojiushixiaobai > 检查过文件权限都是777.

![image](https://user-images.githubusercontent.com/32184005/46735592-3b4a0680-ccc9-11e8-990e-26abbcf4112b.png)

**Comment by lindong629** [comment]
![image](https://user-images.githubusercontent.com/32184005/46735720-a5fb4200-ccc9-11e8-8fb9-27031f6f3277.png)
还是白屏
![image](https://user-images.githubusercontent.com/32184005/46735756-c0cdb680-ccc9-11e8-997d-ca5c6374f1e3.png)

文件权限
![image](https://user-images.githubusercontent.com/32184005/46735796-dcd15800-ccc9-11e8-9027-ad71c3061e6b.png)

**Comment by lindong629** [comment]
好像是nginx没有权限读取这个文件，请问如何解决。
![image](https://user-images.githubusercontent.com/32184005/46736693-3c306780-cccc-11e8-8ce6-be367e03acc8.png)

**Comment by wojiushixiaobai** [comment]
@lindong629 nginx的用户改一下试试？

**Comment by lindong629** [comment]
@wojiushixiaobai 改为root用户运行还是不行。
![image](https://user-images.githubusercontent.com/32184005/46738157-0ab99b00-ccd0-11e8-95b5-c1708e7028f3.png)

**Comment by lindong629** [comment]
已经解决这个问题，是由于系统开启了SELinux关闭后问题解决。
