### ISSUE TITLE
删除子节点报错“存在资产，不能删除”，但节点下并无资产

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#1888]
[简述你的问题]

##### 使用版本
1.4.2

##### 问题复现步骤
1. 资产管理-资产树-新建节点
2. 删除新建的节点报错“存在资产，不能删除”
但是新建的节点没有资产，只有Default节点有资产

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/10399425/46707715-c09fcd80-cc6d-11e8-9805-a03107833f3d.png)

**Comment by wojiushixiaobai** [comment]
@vincent927 刷新一下页面

**Comment by vincent927** [comment]
好了，这个是不是可以改进下？
