### ISSUE TITLE
几天前的“在线会话”无法终断

### ISSUE THREAD

**Issue by badgtgcs** [jumpserver/jumpserver#1889]
[简述你的问题]
几天前的“在线会话”无法终断。
issues #1825 中已经描述了该问题，版本1.4.1-2问题依然存在

##### 使用版本
1.4.1-2 

![image](https://user-images.githubusercontent.com/43986554/46708375-e7133800-cc70-11e8-91ae-7f0520ac5961.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@badgtgcs 到资产上检查下会话是否还存在，存在的话kill掉，然后再观察下。我这样的环境没有出现这个问题，如果可以的话把出问题的环境说明一下（内网or外网），有没有复现（同一个资产），方便排查问题

**Comment by badgtgcs** [comment]
10月8日的，资产上没有会话进程
昨天又出现了，同一用户登录同一资产，今天查看进程，有两个10月11日启动的关于python3的defunc进程，kill其父进程号后，defunc进程虽然没有了，但“在线会话”仍然无法终断。
简单说明一下环境：jumpserver安装在阿里云的ECS上，从我们办公室登jumpserver，是通过ECS的外网IP，资产是阿里云内网。
![image](https://user-images.githubusercontent.com/43986554/46851693-ec1be700-ce2a-11e8-9857-c80c1918479e.png)
