### ISSUE TITLE
jumpserver终端断开，sshd不自动断开

### ISSUE THREAD

**Issue by liuhoom** [jumpserver/jumpserver#1890]
[简述你的问题]
通过jumpserver跳板机登录到客户机，N天后登录发现sshd的连接还没有断开。这个问题是jumpserver引起的吗？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.0.0-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/6359476/46709461-7bcc6480-cc76-11e8-99f1-2d5dbe7c71d7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@liuhoom 请更新到最新的版本
