### ISSUE TITLE
接入AD域测试连接成功，但是登陆有问题

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#1898]
[简述你的问题]
接入AD域测试连接成功，但是登陆有问题

##### 使用版本
Version 1.3.1-2 GPLv2

##### 问题复现步骤
1. 配置AD域，并测试连接成功
2. 重启./jms restart -d
3. 登陆AD域账号密码提示失败

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16998173/46793061-64c16b80-cd77-11e8-9545-175707446218.png)
![image](https://user-images.githubusercontent.com/16998173/46793253-dac5d280-cd77-11e8-9604-92410d8e6952.png)

##### 其他
我的AD信息
```
dn:: Q049546L6Ziz6ZizLE9VPeacrOWcsasASDwqngavluIHnvZEsT1U954Gr5
 biB6ZuG5ZuiLERDPUh1b0JpSU5DLERDPWNvbQ==
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn:: 546L6Ziz6Ziz
sn:: 546L
givenName:: 6Ziz6Ziz
distinguishedName:: Q049546L6ZiasASDwqnacrOWcsOWMluS6i+S4mumDqCxPVT3ngavluI
 HnvZEsT1U954Gr5biB6ZuGasASDwqnPUh1b0JpSU5DLERDPWNvbQ==
instanceType: 0
whenCreated: 20180502090412.0Z
whenChanged: 20181010030412.0Z
displayName:: 546L6aZiz
uSNCreated: 501132
memberOf:: Q0496ZuG5Zui5Lqk5piT5omA5LasASDwqn6kLUROQSxPVT1ETkFCSixEQz1IdW9CaUl
 OQyxEQz1jb20=
memberOf:: Q04954Gr5biB5YWo5L2TLEasASDwqne7hCxEQz1IdW9CaUlOQyxEQz1jb20=
uSNChanged: 2909516
name:: 546L6Ziz6Ziz
objectGUID:: qUr9XBMGbESw1mINnYTjyA==
userAccountControl: 512
badPwdCount: 0
codePage: 0
countryCode: 0
badPasswordTime: 131805868882860013
lastLogon: 131806204730311741
pwdLastSet: 131775851857420442
primaryGroupID: 513
objectSid:: AQUAAAAAAAUVAAAAdhuFWl2zCNI6GQq5HxEAAA==
accountExpires: 9223372036854775807
logonCount: 57
sAMAccountName: wangtiantian
sAMAccountType: 805306368
userPrincipalName: wangtiantian@xxxx.com
lockoutTime: 0
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=xxxx,DC=com
```
[注:] 完成后请关闭 issue

**Comment by BigbigY** [comment]
@wojiushixiaobai 求助

**Comment by wojiushixiaobai** [comment]
@BigbigY OU必须包含至少一个OU，不能直接指向根
如: ou=jumpserver,dc=jumpserver,dc=org

**Comment by BigbigY** [comment]
@wojiushixiaobai 是这个影响的吗，使用根就不行吗

**Comment by wojiushixiaobai** [comment]
@BigbigY 目前只能看出这个问题，你先验证下，不行的话群里找我远程看下

**Comment by BigbigY** [comment]
@wojiushixiaobai 有个问题，我根OU下面都是中文，是不是不支持啊，比如```ou=研发,dc=jumpserver,dc=org```，报错为 {"error":"Search no entry matched"}

**Comment by wojiushixiaobai** [comment]
@BigbigY 支持中文，检测你的dn和密码

**Comment by wojiushixiaobai** [comment]
@BigbigY 你的jumpserver版本是什么版本？

**Comment by BigbigY** [comment]
@wojiushixiaobai Version 1.3.1-2 GPLv2

**Comment by BigbigY** [comment]
@wojiushixiaobai 上次尝试过升级，我mysql是5.5的，升级后会遇到问题

**Comment by BigbigY** [comment]
@wojiushixiaobai 方便指点下哪块代码支持中文OU吗，我尝试修改下

**Comment by wang415** [comment]
(sAMAccountName=%(user)s)
{"username": "cn", "name": "sAMAccountName", "email": "mail"}
