### ISSUE TITLE
TypeError: 'ManyRelatedManager' object is not iterable

### ISSUE THREAD

**Issue by onlywelio** [jumpserver/jumpserver#1899]
[简述你的问题]
测试资产可连接性时，弹出一个黑框，没反应了
日志报错：TypeError: 'ManyRelatedManager' object is not iterable

##### 使用版本
1.4.1-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/9045802/46795998-1c597c00-cd7e-11e8-9af7-68a7af9ee474.png)
![image](https://user-images.githubusercontent.com/9045802/46796035-2b402e80-cd7e-11e8-9ff4-dc47be958e0a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
新版本已修复
