### ISSUE TITLE
Can't add coreos vm

### ISSUE THREAD

**Issue by iwasnobody** [jumpserver/jumpserver#1901]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
Since the /usr/bin is read-only file system in coreos, the python is installed in /opt/bin. Then the jumper will report error:
Get matched hosts: [s1-master-3]

PLAY [更新资产硬件信息]

TASK [setup]
fatal: [s1-master-3]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.22.21.68 closed.\r\n", "module_stdout": "/bin/sh: /usr/bin/python: No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 0}

2018-10-12 10:46:17 Task finish

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@iwasnobody ubuntu一般会有这个问题，apt-get install python 即可
[FAQ](http://docs.jumpserver.org/zh/docs/faq_ssh.html) 第12条

**Comment by iwasnobody** [comment]
@wojiushixiaobai 我用的coreos，/usr/bin下面没有python，并且该目录在coreos中是read only的，python只能安装在其他目录下

**Comment by wojiushixiaobai** [comment]
@iwasnobody 加个软连接

**Comment by iwasnobody** [comment]
read-only的，软连接也是需要写的啊

ip-172-22-21-68 ~ # uname -r
4.14.67-coreos
ip-172-22-21-68 ~ # ln -s /opt/bin/python 
.bash_history                .kube/                       get-pip.py                   install-python-on-coreos.sh  
ip-172-22-21-68 ~ # ln -s /opt/bin/python /usr/bin/python
ln: failed to create symbolic link '/usr/bin/python': Read-only file system

**Comment by iwasnobody** [comment]
@wojiushixiaobai 如何将/bin/sh: /usr/bin/python改成/bin/sh: python，这样只要python安装路径在$PATH中，就能够成功

**Comment by ibuler** [comment]
https://github.com/ansible/ansible/issues/6345

**Comment by iwasnobody** [comment]
@ibuler 
ANSIBLE_PYTHON_INTERPRETER just control which python used by ansible running in the jump server.
It can't control which python used in the target managed machine. The error shows the target machine has no python in /usr/bin/
