### ISSUE TITLE
系统用户设置成手动登录时密码框没显示出来

### ISSUE THREAD

**Issue by easonjim** [jumpserver/jumpserver#1904]
系统用户设置成手动登录时密码框没显示出来，导致无法设置密码。

##### 使用版本
1.4.2-2

**Comment by ibuler** [comment]
测试了一下，没有复现，请详细截图

**Comment by easonjim** [comment]
![image](https://user-images.githubusercontent.com/5625433/46865810-74ad7e00-ce51-11e8-8875-83b9d7883119.png)

**Comment by easonjim** [comment]
我理解错了，手动登录应该是要求用户输入密码才对，这一步在web客户端上做；我理解的是以为手动登录要在web后台上线输入密码，然后实现web客户端自动跳转。
