### ISSUE TITLE
是否考虑对scp协议对支持

### ISSUE THREAD

**Issue by abxuz** [jumpserver/jumpserver#1908]
[简述你的问题]
在openwrt的系统进行堡垒机管理的时候，openwrt上默认没有带上sftp功能，但scp是可以用的。是否会考虑对scp协议进行支持来进行文件读写

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by hackrole** [comment]
jumpserver有其他的开源竞品么？
