### ISSUE TITLE
Client端python3版本无法推送用户

### ISSUE THREAD

**Issue by inxming** [jumpserver/jumpserver#191]
跳板机推送用户的时候Client端必须是默认为python2的版本，python3的版本则提示报错，只有更改全局变量的python版本为python2的时候才可以正常推送用户。

具体报错信息如下：
BECOME-SUCCESS-wetjtmllaaonyxwkmzkaowhzlljmybeo File "/home/tom/.ansible/tmp/ansible-tmp-1459518156.59-116087642935608/authorized_key", line 173 except KeyError, e: ^ SyntaxError: invalid syntax

**Comment by yumaojun03** [comment]
这个 可以通过预先建好用户，进行空推送来临时解决。

**Comment by inxming** [comment]
嗯，现在也是这么做的  事先创建用户只是临时解决办法  只能等下个版本修复了在进行批量部署用户了
