### ISSUE TITLE
用户登录后不设置邮箱地址，新用户无法登陆

### ISSUE THREAD

**Issue by miaoyb** [jumpserver/jumpserver#1915]
[简述你的问题]

用户登录后不设置邮箱地址，新用户无法登陆
##### 使用版本
1.3.3-2
##### 问题复现步骤
1. 用户1登陆，不设置邮箱退出
2. 用户2登陆，无法登陆

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/7277129/46952103-7f1f8000-d0bc-11e8-9b40-8c29b00e7cbf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@miaoyb 具有唯一性，不能重复。

**Comment by miaoyb** [comment]
> @miaoyb 具有唯一性，不能重复。

对的，但是不是重复，是没设置邮箱，这个字段默认设置为空了，其他用户是无法登陆的，是从LDAP同步过来的
