### ISSUE TITLE
系统用户删除后，目标资产用户没删除

### ISSUE THREAD

**Issue by easonjim** [jumpserver/jumpserver#1919]
系统用户删除后，目标资产用户没删除

##### 使用版本
1.4.3

**Comment by ibuler** [comment]
由于无法判断是否存在该系统用户运行的程序等安全原因，系统用户需要自己回收

**Comment by easonjim** [comment]
可以实现这样的情况吗？：返回错误的信息，提示有运行的程序在哪台机，然后自行关闭程序后再进行删除。
