### ISSUE TITLE
coco 报错：'AppService' object has no attribute 'get_system_user_cmd_filter_rules'

### ISSUE THREAD

**Issue by Jonnter** [jumpserver/jumpserver#1920]
[简述你的问题]

##### 使用版本
Jumpserver版本 1.4.3 

##### 问题复现步骤
1. 命令行ssh user@IP 
出现闪断问题，
服务器coco报错：
[sshd ERROR] Unexpected error occur: 'AppService' object has no attribute 'get_system_user_cmd_filter_rules'

##### 具体表现[截图可能会更好些,最好能截全]

![12](https://user-images.githubusercontent.com/21307121/47001057-33241800-d15c-11e8-91a9-76e88073aeac.jpg)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
更新sdk
```
$ pip install jumpserver-python-sdk==0.0.50
```

**Comment by Jonnter** [comment]
问题已经解决，更换coco版本到1.4.1，最新版本还没有

> 更新SDK
> 
> ```
> $ pip install jumpserver-python-sdk==0.0.50
> ```

问题已经解决，将coco版本改为1.4.1可以了，最新的coco版本还没有jumpserver-python-sdk==0.0.50
