### ISSUE TITLE
请问可以增加增加用户后执行自定义命令的功能吗

### ISSUE THREAD

**Issue by easonjim** [jumpserver/jumpserver#1921]
请问可以增加增加用户后执行自定义命令的功能吗？可能有很多情况增加的用户需要增加到不同的用户组上，那么需要在增加用户后执行附加到指定的用户组的命令。

##### 使用版本
1.4.3

**Comment by easonjim** [comment]
这个功能我可以直接添加到task里面执行吗？我想提交到pull request，我直接在这个页面增加这个功能
![image](https://user-images.githubusercontent.com/5625433/47007728-7a65d500-d16b-11e8-8a37-139c877c5c9e.png)
请问这样增加会不会有什么规范吗？会不会影响你们现有的部署功能规划？

**Comment by ibuler** [comment]
看看需求多不多吧

**Comment by easonjim** [comment]
请问后续版本可以增加这个功能吗？
