### ISSUE TITLE
网关连接无法使用自定义端口

### ISSUE THREAD

**Issue by huangzgx** [jumpserver/jumpserver#1924]
[简述你的问题]
网域列表里面的网关功能，无法使用自定义自定义端口连接，必须使用22端口才行

##### 使用版本
Version 1.4.3-2 GPLv2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![wl5 b ny_y u1m3q96 bn e](https://user-images.githubusercontent.com/39511964/47066390-865ba080-d218-11e8-94b3-75965d1e9202.png)
![f25yl1_mqsq 3yp72swv5rw](https://user-images.githubusercontent.com/39511964/47066395-88bdfa80-d218-11e8-9bf5-d3df3ee7b4a1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不要使用nat，可能测试不通过，但是可以正常使用
