### ISSUE TITLE
SSH登录跳板机，提示MFA auth，实际并未启用MFA功能

### ISSUE THREAD

**Issue by hyqf** [jumpserver/jumpserver#1925]
SSH登录跳板机，提示MFA auth，实际并未全局和根据用户启用MFA功能，不管是管理员还是普通用户都提示，版本是1.4.1，MFA auth不输入6位数字，敲三次回车，就会提示输入密码，输入密码可以登录，怎么才可以关闭MFA auth的提示，直接提示密码登录。

**Comment by MRwangyd** [comment]
请问 问题解决了么，碰到了一样的问题，关闭MFA后登陆还是提示

**Comment by qianzhou87** [comment]
一样的问题，我的是1.4.3，关闭MFA后登陆还是提示
