### ISSUE TITLE
新建用户为自己更新【认证—ssh公钥】时，提交返回500错误页面

### ISSUE THREAD

**Issue by DullBird** [jumpserver/jumpserver#1926]
[简述你的问题]
新建的用户在添加认证-ssh公钥时，报错错误，返回500页面，没有任何错误提示

##### 使用版本
1.4.3-2

##### 问题复现步骤
1. 个人信息—设置—ssh公钥
2. 复制公钥并粘贴，点击提交

**Comment by DullBird** [comment]
开启了debug模式后返回的错误是

TypeError at /users/user/0bc51ae1-9125-4e7d-a125-24c48e46654c/update/
size() takes 0 positional arguments but 1 was given

Request Method: POST
Request URL: http://x.x.x.x/users/user/0bc51ae1-9125-4e7d-a125-24c48e46654c/update/
Django Version: 2.1
Exception Type: TypeError
Exception Value: size() takes 0 positional arguments but 1 was given
Exception Location: home/soft/jumpserver/py3/lib/python3.6/site-packages/sshpubkeys/__init__.py in _process_ssh_rsa, line 281
Python Executable: /home/soft/jumpserver/py3/bin/python3
Python Version: 3.6.1
Python Path: ['/home/soft/jumpserver/jumpserver/apps',
                    '/home/soft/jumpserver/py3/bin',
                    '/usr/local/lib/python36.zip',
                    '/usr/local/lib/python3.6',
                    '/usr/local/lib/python3.6/lib-dynload',
                    '/home/soft/jumpserver/py3/lib/python3.6/site-packages',
                    '/home/soft/jumpserver/jumpserver',
                    '/home/soft/jumpserver/jumpserver/apps']

**Comment by kongxiangsheng** [comment]
最新版本遇到相同的问题

**Comment by DullBird** [comment]
> 升级sshpubkeys库版本，不知道为何突然兼容不好了
> 
> ```
> $ pip install -U sshpubkeys
> ```

升级了之后可以了，谢谢支持
