### ISSUE TITLE
数据库使用的AWS RDS，升级Jumpserver时报错

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#1927]
[简述你的问题]
数据库用的rds mysql 5.6，因为是托管数据库，所以不能直接重建jumpserver表
执行：cd utils && sh make_migrations.sh 的时候报错如下：
    db.query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, 'Can\'t create table `jumpserver`.`#sql-d29_2202` (errno: 150 "Foreign key constraint is incorrectly formed")')
有什么办法解决么？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.3.2

##### 其他

[注:] 完成后请关闭 issue

**Comment by ChampionWolf** [comment]
截图如下
![1](https://user-images.githubusercontent.com/20255706/47079413-02191580-d238-11e8-97a0-bb92c53bb3ae.png)

**Comment by ChampionWolf** [comment]
之后我执行了：sh clean_migrations.sh
然后又执行了一次：sh make_migrations.sh
报错如下：
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration users.0001_initial is applied before its dependency auth.0009_alter_user_last_name_max_length on database 'default'.

**Comment by ibuler** [comment]
数据库操作请谨慎，不能任意做操作，否则无法成功升级

**Comment by ChampionWolf** [comment]
> 数据库操作请谨慎，不能任意做操作，否则无法成功升级

我想是不是可以先这样,我把库先导回本地的MySQL,然后做升级操作,升级完成后再把库导入RDS MySQL
或者您有什么更好的办法么?针对我数据库在AWS RDS上的这种情况.

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 参考升级失败文档 http://docs.jumpserver.org/zh/docs/faq_upgrade.html 第三条处理一下，数据库部分你可以改成在你rds新建一个新的数据库即可，初始化完成后，把旧的数据库忽略 django_migrations 表导入新的数据库然后正常升级即可
