### ISSUE TITLE
JumpServer有考慮机器是容器的情况，不在容器里开ssh，通过exec -it connainer_id的方式登录容器？

### ISSUE THREAD

**Issue by xionghui** [jumpserver/jumpserver#1928]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
怎么标示机器呢？另外容器经常重启调度，不好连接

**Comment by chenyanshan** [comment]
容器用 kubernetes 管理挺好的。
