### ISSUE TITLE
coco做分布式部署后web终端进入资产卡顿

### ISSUE THREAD

**Issue by LivesMountain** [jumpserver/jumpserver#1930]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.3
##### 问题复现步骤
1. 单coco不会卡顿。分布式部署coco后，通过web终端进入资产严重卡顿。停掉一个coco后，恢复正常，再启动刚才停掉的coco。终端又只往往一个coco节点分配，ssh的话可以平均分配，应该不是stream的那问题。就感觉是有一个coco节点timeout分配到另一个coco上面了。找不到具体是什么问题，麻烦帮忙排查一下。谢谢大哥！
2. 参考了
![image](https://user-images.githubusercontent.com/19382017/47201330-0f571100-d3ac-11e8-930d-6dba79245a7c.png)
加入了nginx的配置 ，感觉还是没什么改变

##### 具体表现[截图可能会更好些,最好能截全]
终端只往一个节点上分配
![image](https://user-images.githubusercontent.com/19382017/47201043-12053680-d3ab-11e8-8848-476fafb49128.png)
开发者模式报错
![image](https://user-images.githubusercontent.com/19382017/47201263-d1f28380-d3ab-11e8-9061-fe8a639684ba.png)
![image](https://user-images.githubusercontent.com/19382017/47201298-edf62500-d3ab-11e8-98eb-f9542abfd363.png)

nginx配置
![image](https://user-images.githubusercontent.com/19382017/47201460-8391b480-d3ac-11e8-8970-92551d732b37.png)

![image](https://user-images.githubusercontent.com/19382017/47201471-8d1b1c80-d3ac-11e8-8dd5-8a379648c0f8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LivesMountain** [comment]
忘记说了  这种卡顿大概等一会就能进去了。但是F12还是如上图所示的那写报错，这时候查看coco的话
![image](https://user-images.githubusercontent.com/19382017/47202769-d3727a80-d3b0-11e8-93c9-4fda6be3a53c.png)
就分配到另一个coco上了    coco日志开启了debug模式   查看了没有任何报错

**Comment by LivesMountain** [comment]
![image](https://user-images.githubusercontent.com/19382017/47203678-b8edd080-d3b3-11e8-8695-76f4688aa697.png)
看起来像WebSocket有毒

**Comment by wojiushixiaobai** [comment]
@LivesMountain 默认是轮滚，如果需要使用轮滚，建议使用proxy_next_upstream http_500 http_502 http_503 http_504 http_404; 约束

**Comment by LivesMountain** [comment]
![image](https://user-images.githubusercontent.com/19382017/47281427-ac64b480-d60d-11e8-9c32-c1cfb3492c29.png)
proxy_next_upstream http_500 http_502 http_503 http_504 http_404;
加入限制重试参数400过滤不了，打开终端还是要需要很久

**Comment by hzbd** [comment]
![image](https://user-images.githubusercontent.com/3000843/47474850-96443780-d84b-11e8-812c-c9bdf94548e0.png)

与楼上遇到的问题一样啊，web console 要好一会儿才能连接上

**Comment by hzbd** [comment]
```
server {
    listen 80;
    listen 443 ssl http2;
    server_name jp.a.com;

    ssl_certificate  a.com.cer;
    ssl_certificate_key  a.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    client_max_body_size 100m;

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
    }

    location /socket.io/ {
        proxy_pass       http://127.0.0.1:5000/socket.io/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_next_upstream http_500 http_502 http_503 http_504 http_404;
        access_log /var/log/nginx/socket.log;
    }

    location /coco/ {
        proxy_pass       http://127.0.0.1:5000/coco/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://127.0.0.1:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by LivesMountain** [comment]
单节点coco我是正常的  @hzbd ，我是做了upstream后貌似要保持回话和长链接请求到一个coco上面，所以只能用ip_hash。但是ip_hash打的不是那么散，不过也能凑活用。单一节点我没遇到过，不过看起来你也是websocket的问题。引发原因应该和我的不一样

**Comment by wojiushixiaobai** [comment]
@LivesMountain @hzbd 文档已经更新，请修改下

**Comment by hzbd** [comment]
我的问题原因找到了：是因为办公无线网络问题导致首次连接设备超时。
