### ISSUE TITLE
邮件配置出错

### ISSUE THREAD

**Issue by sengeng** [jumpserver/jumpserver#1935]
[简述问题]
根据文档搭建起来以后，在邮件配置这个地方，无论如何也发送不成功，细节如下图

##### 使用版本
版本1.4.3

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/25051113/47283204-dcfc1c80-d614-11e8-9626-f80c45058711.png)

![image](https://user-images.githubusercontent.com/25051113/47283219-f0a78300-d614-11e8-96b4-db2453ca3553.png)

![image](https://user-images.githubusercontent.com/25051113/47283246-17fe5000-d615-11e8-9d55-288a41957ab5.png)

[注:] 完成后请关闭 issue

**Comment by sengeng** [comment]
补充一下coco的日志：
![image](https://user-images.githubusercontent.com/25051113/47283387-cbffdb00-d615-11e8-9a87-37f3bf774714.png)

**Comment by wojiushixiaobai** [comment]
@sengeng 邮件，勾选下面的ssl
coco 问题

运行 ./cocod start 后提示 Connect endpoint http://xxxx:8080 error: HTTPConnectionPool(host='xxxx', port=8080)

      # 这是因为 coco 无法连接到 jumpserver 报的错误，确定 http://xxxx:8080 设置正确（配置文件 coco/conf.py）
      # 如果 jumpserver 的IP和端口不对，请手动修改 conf.py 的 CORE_HOST
