### ISSUE TITLE
测试可连接性失败

### ISSUE THREAD

**Issue by zhouxuefeng123** [jumpserver/jumpserver#1942]
[简述你的问题]
添加管理用户测试可连接性失败
![image](https://user-images.githubusercontent.com/39616599/47352527-a98cc100-d6ec-11e8-92cc-98a464c3a393.png)

##### 使用版本1.4.3
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]jps服务器上创建私钥并上传，但上传完再点开就不显示了，不知道这个是否正常
![image](https://user-images.githubusercontent.com/39616599/47352679-f7a1c480-d6ec-11e8-835d-b128ab3fc828.png)

2. [步骤2]管理用户测试连接不可达，但在服务器上使用秘钥可以连接
![image](https://user-images.githubusercontent.com/39616599/47352894-7860c080-d6ed-11e8-8179-fef8e3ac785f.png)

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/39616599/47352769-2f107100-d6ed-11e8-934d-d411d058d603.png)
点提交再点更新发现没有任何记录（不知道是否属于正常情况）
![image](https://user-images.githubusercontent.com/39616599/47352789-3e8fba00-d6ed-11e8-8635-4499cd03cd03.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
确定私钥正确。

**Comment by zhouxuefeng123** [comment]
> 确定私钥正确。

私钥正确。

**Comment by zhouxuefeng123** [comment]
会不会跟docker环境有关系

**Comment by zhouxuefeng123** [comment]
确实跟docker环境有关，不知道缺少了什么

**Comment by wojiushixiaobai** [comment]
@zhouxuefeng123 第一个问题，上传保存后不显示问题，正常。

第二个问题，测试不可达的详细报错发出来看下，（小窗口有报错显示）

**Comment by wojiushixiaobai** [comment]
@zhouxuefeng123 你管理的资产是容器里面的?

**Comment by zhouxuefeng123** [comment]
> @zhouxuefeng123 你管理的资产是容器里面的?

不是容器

**Comment by wojiushixiaobai** [comment]
@zhouxuefeng123 这不科学呀，连接自身试试？127.0.0.1

**Comment by zhouxuefeng123** [comment]
> @zhouxuefeng123 这不科学呀，连接自身试试？127.0.0.1
刚试了一下不行

**Comment by zhouxuefeng123** [comment]
官方centos7镜像有问题，换个镜像好了

**Comment by PanPen** [comment]
我的也是这个问题，小窗口全是点点

**Comment by wojiushixiaobai** [comment]
问题过于久远，如果任然存在请重新打开
