### ISSUE TITLE
ldap登录问题

### ISSUE THREAD

**Issue by arnolix** [jumpserver/jumpserver#1943]
[简述你的问题]
ldap连接测试ok， 但是登录有问题

##### 使用版本
Version 1.4.1-2 GPLv2

##### 问题复现步骤
1. jms start 
2. web页配置ldap
3. 重启 jms
4. 使用ldap账户登录有问题（登录账户是uid）

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/11156826/47355255-80236380-d6f3-11e8-8560-08a748c3aa82.png)

##### 其他
查看日志：
[backend WARNING] Caught LDAPError while authenticating test100: LDAPError(2, 'No such file or directory')

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
ldap地址填写不规范不对，ou有误
请参考官方文档的ldap说明

**Comment by arnolix** [comment]
确实是ldap地址没按规范填写，ldap://x.x.x.x:389 , 类似这样填写。感谢！
