### ISSUE TITLE
任务列表删除任务后，无法在资产上找到更新、测试按钮

### ISSUE THREAD

**Issue by fuziyuan** [jumpserver/jumpserver#1944]
[简述你的问题]
任务列表删除任务后，无法在资产上找到更新、测试按钮

##### 使用版本
Version 1.4.2 GPLv2

##### 问题复现步骤
1. 在资产内，点击连接测试，测试不成功；
2. 在任务列表内，看到有任务生成；
3. 删除任务
4. 发现资产内，无更新、测试按钮了。

##### 具体表现[截图可能会更好些,最好能截全]
![qq 20181024090321](https://user-images.githubusercontent.com/35143787/47400063-388ded80-d76e-11e8-9f8b-40f2685a99e4.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@fuziyuan Linux资产才有
