### ISSUE TITLE
gua终端删除后重启docker也不会出现

### ISSUE THREAD

**Issue by eryuanxiansheng** [jumpserver/jumpserver#1949]
[简述你的问题]
gua终端删除后重启docker也不会出现

##### 使用版本 1.4.3
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44429776/47418334-80cc0080-d7ac-11e8-95e3-a6e6346d4df4.png)
![image](https://user-images.githubusercontent.com/44429776/47418363-8cb7c280-d7ac-11e8-8879-8c312c3d57b5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
问题描述不清楚

**Comment by wojiushixiaobai** [comment]
@eryuanxiansheng 需要删除key

**Comment by wojiushixiaobai** [comment]
@eryuanxiansheng 那就是JUMPSERVER_SERVER有误，自己检查下
