### ISSUE TITLE
使用tmux时命令历史记录异常

### ISSUE THREAD

**Issue by Erazx** [jumpserver/jumpserver#1951]
[简述你的问题]
在 webterminal 使用 tmux 时，会出现命令记录异常

##### 使用版本
Version 1.4.3-2 GPLv2.

##### 问题复现步骤
1. tmux new -s test 新建会话
2. 依次执行 free -m, top, htop 命令

##### 截图
![jms_issue001](https://user-images.githubusercontent.com/18753065/47484481-5e022080-d86e-11e8-8623-73c4b97184b8.png)

**Comment by ibuler** [comment]
命令处理目前的确没有特别精确的办法，暂时关闭了
