### ISSUE TITLE
vi/vim 中文显示乱码

### ISSUE THREAD

**Issue by xiaobei-ihmhny** [jumpserver/jumpserver#1954]
[简述你的问题]

##### 使用版本
版本：1.4.1

##### 问题复现步骤
1. 通过主机直接登录docker中查看日志中文显示正常
2. 通过jumpserver登录docker中查看日志中文出现乱码

##### 具体表现[截图可能会更好些,最好能截全]
云主机直接登录
![image](https://user-images.githubusercontent.com/26052371/47552194-b7358700-d936-11e8-9d2c-9df4c7fc42b8.png)

 jumpserver登录
![image](https://user-images.githubusercontent.com/26052371/47555866-84dc5780-d93f-11e8-9d1a-049891654788.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaobei-ihmhny 请尝试更新版本，新版本中未能复现此问题
