### ISSUE TITLE
无法获取系统信息

### ISSUE THREAD

**Issue by inxming** [jumpserver/jumpserver#196]
更新系统信息的无法获取,查看日志报错信息为：
ERROR - save setup info failed! argument of type 'NoneType' is not iterable

**Comment by yumaojun03** [comment]
你客户端 的 gentoo版本， python环境。最好能贴出来下，这样方便我们 模拟你的环境。

**Comment by inxming** [comment]
Gentoo版本为2.1  内核版本多为3.7.10 Python环境为2.7版本  服务端Python为2.6版本 多数都无法获取成功140多台Gentoo的客户端只获取到几台服务器的信息。

**Comment by ibuler** [comment]
@halcyonone 跟踪一下
