### ISSUE TITLE
空闲时间超过 30 分钟，断开连接，ctrl+w直接关闭页面

### ISSUE THREAD

**Issue by xujingbin** [jumpserver/jumpserver#1968]
[简述你的问题]

##### 使用版本
Version 1.4.3-2 GPLv2

##### 问题复现步骤
1、空闲时间超过 30 分钟，断开连接，如何设置保持长连接
ctrl+w直接关闭页面，是否可以增加确认对话框，习惯性地关闭页面，整个操作都没了

**Comment by dinggel** [comment]
3、终端界面不支持ctrl+f功能

**Comment by dinggel** [comment]
终端的ctrl+w功能是删除前一个单词，可是在这里直接就关闭页面了

**Comment by dinggel** [comment]
同个组的普通账户，登录后端服务器时，可以选择同组的账户，可以选择关掉这个功能吗

**Comment by ibuler** [comment]
关闭浏览器标签增加提示

**Comment by wojiushixiaobai** [comment]
@xujingbin 新版本已经更新了关闭浏览器标签增加提示的功能，请更新
