### ISSUE TITLE
资产列表不显示资产

### ISSUE THREAD

**Issue by xiaochaohasun** [jumpserver/jumpserver#1972]
[简述你的问题]
先增加标签5个以上，再添加资产，在资产列表不显示资产，显示资产数量是正确的。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.3
##### 问题复现步骤
1. [步骤1] 增加5个标签
2. [步骤2] 增加一台资产，在资产列表查看，资产不显示。

##### 其他

[注:] 完成后请关闭 issue

**Comment by xiaochaohasun** [comment]
添加一个名称为search的标签，资产就不显示了

**Comment by wojiushixiaobai** [comment]
@xiaochaohasun 已修复，请更新一下代码

**Comment by junly917** [comment]
1.5.3为什么没有显示标签功能了？
