### ISSUE TITLE
打开web终端，第一次无法连接上服务器，需要再打开一个，才能正常连接

### ISSUE THREAD

**Issue by zxl78585** [jumpserver/jumpserver#1984]
[简述你的问题]
打开web终端，第一次打开，没有动静，也没有计时的东西，只有再打开一个当前的服务器链接，才可以正常脸上，我使用的是docker部署的，里面配置了我的物理机和我的其他所有的docker。我在docker内部去链接其他的机器，都是很快的，直接就连上去了。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.3-2
##### 问题复现步骤
1. [步骤1]
第一次打开服务器的链接，无响应
2. [步骤2]
再打开该链接（新的tab页），可以正常连接

##### 具体表现[截图可能会更好些,最好能截全]
第一次
![image](https://user-images.githubusercontent.com/19941977/47837015-62d25180-dde5-11e8-9960-6f00c0d4a898.png)
第二次
![image](https://user-images.githubusercontent.com/19941977/47837022-68c83280-dde5-11e8-9c66-a2b65030818d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zxl78585 未复现，请确认下

**Comment by zxl78585** [comment]
@wojiushixiaobai 日志在什么路径下，我用的是docker，我给你贴一下日志吧。wojiushixiaobai/jumpserver我用的这个1.4.3的版本

**Comment by wojiushixiaobai** [comment]
@zxl78585 进入容器看nginx的log看有没有错误
第一个图开发者工具里面有没有error字段

换个网络环境重新检查下是否能复现

**Comment by zxl78585** [comment]
@wojiushixiaobai 谢谢哈，我已经找到原因了。我是内网，没有公网，然后，通过frp软件，做的内网穿透，不是jumpserver的问题，我在内网发现每次都和很顺利就打开了，在公网每次需要刷新一下才能打开，应该是frp的问题。
