### ISSUE TITLE
MFA启用后无法更新

### ISSUE THREAD

**Issue by freshcn** [jumpserver/jumpserver#1985]
[简述你的问题]
系统开启了强制使用二次认证的功能，现在用户第一次设置了认证后。需要更新认证时会出现，快速修改位置上面的“更改MFA设置:”为禁用

##### 使用版本
1.3.2

##### 问题复现步骤
1. 开启强制二次认证
2. 设置账号的MFA
3. 登录后

##### 具体表现[截图可能会更好些,最好能截全]
![qq20181101-154958](https://user-images.githubusercontent.com/1764041/47839473-d1b3a880-dded-11e8-9b1d-a2436301022e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by holt0420** [comment]
遇到类似场景，和你版本不一样，我的MFA启用后无法更新原因：管理员在系统设置-安全设置-用户登录设置强制开启了MFA二次认证。

**Comment by ibuler** [comment]
1.4.4 已解决
![image](https://user-images.githubusercontent.com/17382885/48997213-2565a780-f18a-11e8-83e6-e87b111f2c39.png)
