### ISSUE TITLE
jumpserver推送系统用户，是否可以指定系统用户sudo的

### ISSUE THREAD

**Issue by melpozhang** [jumpserver/jumpserver#1989]
![image](https://user-images.githubusercontent.com/16367781/47895615-5660fe00-dea4-11e8-8d5d-057e4fa40dfa.png)
也就是 ALL=(ALL)希望是 ALL=(XXX)

**Comment by wojiushixiaobai** [comment]
@melpozhang 可以，sudo 写入ALL 即可，勾选自动推送，确认管理用户有权限进行sudo修改

**Comment by ibuler** [comment]
现在还不能，建议授权 sudo su - xxx来解决
