### ISSUE TITLE
基于jumpserver自研发告警系统插件

### ISSUE THREAD

**Issue by kobehaha** [jumpserver/jumpserver#1995]
[简述你的问题]

我这边针对我们系统开发了一些功能，想贡献给项目，因为使用这个系统的大多数是运维人员，可能需要处理一些告警功能，统一所有告警，告警分析，然后对告警可追溯所有增对这样的需求做了一个告警系统

告警系统汇总了所有的告警:

告警来源: 

```

目前有三种来源 1 对接zabbix 2 grafana 3 自定义接口告警

```
告警分析: 

```
基于jumpserver的账户系统，针对用户做一些告警分析

a 用户接受时长，b 用户处理时长，c 告警条数 d 最近一条未处理时间 e 今天告警数 等等等

```
值班表:

```

sre里边有提到ONCALL, 每日可能有不同的人可以进行值班，可以根据jumpserver的用户体系，选择进行排值班表.

```

告警处理:

```
每条告警可追溯，每条告警可查看故障处理流程,添加评论

```

还有很多小的优化，如果需要我可以做适当调整提一个pull request

**Comment by ibuler** [comment]
可否作为一个插件存在，用户简单配置一下就可以使用。

django鼓励使用app来开发，app是可插拔的，你的app可以依赖jms的app，配置信息可以保存在settings.py中

**Comment by kobehaha** [comment]
截图如下: 

![image](https://user-images.githubusercontent.com/14839922/47977185-b0a2ce80-e0f1-11e8-976d-c1c0b17be437.png)
![image](https://user-images.githubusercontent.com/14839922/47977195-bac4cd00-e0f1-11e8-8155-8b9815664074.png)
![image](https://user-images.githubusercontent.com/14839922/47977224-d62fd800-e0f1-11e8-9ba4-196a19ee3191.png)

![image](https://user-images.githubusercontent.com/14839922/47977235-dfb94000-e0f1-11e8-9875-ac7dad37cd8d.png)


![image](https://user-images.githubusercontent.com/14839922/47977244-f1024c80-e0f1-11e8-83a5-96bef0c7b8e7.png)

![image](https://user-images.githubusercontent.com/14839922/47977269-13946580-e0f2-11e8-8fcd-8f93344e63b3.png)
![image](https://user-images.githubusercontent.com/14839922/47977287-2c9d1680-e0f2-11e8-89c3-d5d22e77f251.png)

![image](https://user-images.githubusercontent.com/14839922/47977300-39ba0580-e0f2-11e8-9907-9a3d4d789e7c.png)

**Comment by kobehaha** [comment]
这边是可以做成一个插件的，如果说你们这边觉得可以，我可以提交一个插件版本的pull requests，方便大家使用

**Comment by kobehaha** [comment]
目前的话我是做了一个 alert的app, 配置在setting.py中

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by PostgreSQL1989** [comment]
这个功能好，赞

**Comment by yakexi07** [comment]
这个功能好

**Comment by wojiushixiaobai** [comment]
@ibuler 收到了老哥
@kobehaha 老哥可否先提个代码，容我测试一下

**Comment by kobehaha** [comment]
@wojiushixiaobai 好的,我整理一下

**Comment by mansoncui** [comment]
兄得能否共享下，我这边也测试下

**Comment by wojiushixiaobai** [comment]
@kobehaha 已收到回复，老哥辛苦。

**Comment by Aaron0-wang** [comment]
你们都不用钉钉机器人告警的吗？

**Comment by mansoncui** [comment]
用的，别的方式可以吗

发自我的 iPhone

**Comment by l-duan** [comment]
下一个版本可以加进来么？

**Comment by luolenny** [comment]
感觉挺好的，希望能早日看到这个功能

**Comment by anjia0532** [comment]
热切期待[呲牙]

**Comment by kobehaha** [comment]
我周末弄下😅

**Comment by anjia0532** [comment]
请问有新进展么

**Comment by ibuler** [comment]
欢迎提PR
