### ISSUE TITLE
luna web终端时常无法连接主机

### ISSUE THREAD

**Issue by CharkeyQK** [jumpserver/jumpserver#1997]
[简述你的问题]
web终端中，点击左侧主机，右侧会新开tab，然后会光标闪烁很久，有时连不上，有时重新打开web终端页面再次点击就能连接
在未登录过jumpserver 的浏览器上通常都出现这么问题

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
version 1.4.3-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
登录 jumpserver
2. [步骤2]
点击打开web终端

##### 具体表现[截图可能会更好些,最好能截全]
看到 error.log 是这样，对应浏览器network很多 400 bad request
2018/11/06 22:33:13 [error] 32628#0: *335925 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 120.***.255.***, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=MRfS3RS&sid=4d0e8a7f683443eba1b848a2d4ffc07f HTTP/1.1", upstream: "http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=MRfS3RS&sid=4d0e8a7f683443eba1b848a2d4ffc07f", host: "106.***.190.***", referrer: "http://106.***.190.***/luna/"

##### 其他
nginx 配置参考 http://docs.jumpserver.org/zh/docs/step_by_step.html#nginx 完成的；
另外安装后优化参考：http://docs.jumpserver.org/zh/docs/setup_by_optimization.html

[注:] 完成后请关闭 issue

**Comment by hzbd** [comment]
@CharkeyQK 
可能跟这个问题差不多。
https://github.com/jumpserver/jumpserver/issues/1930

**Comment by CharkeyQK** [comment]
@hzbd 
看过 #1930 ，console 的报错是一样样的。
我这边就是单节点 coco；大概率需要进入 Luna 页面之后，等待一小会，或者重新打开页面（可能两三次）才能 ok

附上 jumpserver.conf

`upstream jumpserver {
    server 127.0.0.1:8080;
    # 这里是 jumpserver 的后端ip
}
server {
    listen 80;
    server_name jump.domain.name;  # 自行修改成你的域名
    return 301 https://$server_name$request_uri;  # 自行修改成你的域名
}
server {
    listen 443;

    server_name jump.domain.name;

    ssl on;
    ssl_certificate   /etc/nginx/cert/cert_jump.domain.name.crt;
    ssl_certificate_key  /etc/nginx/cert/cert_jump.domain.name.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    client_max_body_size 200m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径，如果修改安装目录，此处需要修改
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;  # 录像位置，如果修改安装目录，此处需要修改
    }

    location /static/ {
        root /opt/jumpserver/data/;  # 静态资源，如果修改安装目录，此处需要修改
    }

    location /socket.io/ {
        proxy_pass       http://127.0.0.1:5000/socket.io/;  # 如果coco安装在别的服务器, 请填写它的ip
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_next_upstream http_500 http_502 http_503 http_504 http_404;
        access_log /var/log/nginx/socket.access.log;
        error_log /var/log/nginx/socket.error.log;
        #access_log off;
    }

    location /coco/ {
        proxy_pass       http://127.0.0.1:5000/coco/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://127.0.0.1:8081/;  # 如果docker安装在别的服务器, 请填写它的ip
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location / {
        proxy_pass http://jumpserver;  # 如果jumpserver安装在别的服务器, 请填写它的ip
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
        # proxy_next_upstream http_500 http_502 http_503 http_504 http_404;
    }

}`

**Comment by wojiushixiaobai** [comment]
@CharkeyQK proxy_next_upstream http_500 http_502 http_503 http_504 http_404;

**Comment by CharkeyQK** [comment]
```
location /socket.io/ {
        ...
        # 文档更新了只是去掉了下面这行配置是吧
        # proxy_next_upstream http_500 http_502 http_503 http_504 http_404;
        ...
    }
```

问题貌似依旧。 @wojiushixiaobai 

![image](https://user-images.githubusercontent.com/5127583/48131591-97557a00-e2cb-11e8-8d11-c1361e16501f.png)
打开 web 终端之后，等待 console 不再刷 400 请求之后可能点击服务器就立马连接 ok，
或者，一开始 console 不会刷 400，点击服务器开始刷，不刷之后再次点击服务器也是可以立马连接的。

以上，谢谢。

**Comment by wojiushixiaobai** [comment]
@CharkeyQK 单节点出现问题，检查网络，多组件检查nginx 负载模式

**Comment by CharkeyQK** [comment]
好吧。Issue 先关掉啦。
