### ISSUE TITLE
关于Jumperserver 产生僵尸进程的问题。

### ISSUE THREAD

**Issue by aapelismith** [jumpserver/jumpserver#1999]
[简述你的问题]
关于Jumperserver 产生僵尸进程的问题。
请看下图： jumperserver产生了4个僵尸进程。

<img width="794" alt="default" src="https://user-images.githubusercontent.com/44763019/48117419-1fc02480-e2a4-11e8-807b-7c293456d350.png">

<img width="685" alt="default" src="https://user-images.githubusercontent.com/44763019/48117689-f0f67e00-e2a4-11e8-8bce-93f4121a0103.png">

# 进程树
<img width="690" alt="default" src="https://user-images.githubusercontent.com/44763019/48117889-8d208500-e2a5-11e8-9539-e68e2ea31ca8.png">

# 由进程树可知其父进程为 `31386`

<img width="1279" alt="default" src="https://user-images.githubusercontent.com/44763019/48117875-842fb380-e2a5-11e8-8a35-cdec474bd313.png">

故此可得出结论 `jumpserver` 所使用的`celery`可能会产生僵尸进程.

##### 使用版本

<img width="692" alt="default" src="https://user-images.githubusercontent.com/44763019/48118022-eee0ef00-e2a5-11e8-9326-968144400a4b.png">

[注:] 完成后请关闭 issue

**Comment by evannian** [comment]
僵尸进程一旦出现之后，很难自己消亡，会一直存在下去，直至系统重启。虽然僵尸进程几乎不占系统资源，但是，这样下去，数量太多了之后，终究会给系统带来其他的影响。

**Comment by ibuler** [comment]
这个问题一直存在，celery启动后就开始有这个进程，请帮助排查

**Comment by ibuler** [comment]
未来版本处理
