### ISSUE TITLE
关于centos7系统的问题和主机名的问题

### ISSUE THREAD

**Issue by sapser** [jumpserver/jumpserver#200]
Hi，在使用中遇到如下几个问题，不是很理解：
1、在centos7系统执行install.py识别不了系统，我是把self.dist直接赋值为"redhat"才安装成功，在ipython跑了下"platform.linux_distribution(supported_dists=['system'])[0].lower()"，返回"system"
2、添加资产时为什么主机名是必填项呢，而IP是可选项，不是很理解，理论上来说应该输入IP，然后自动去机器上获取对应主机名
3、添加一台centos7机器，不能正确获取到操作系统信息，页面显示为"WelcomeWelcome"

**Comment by ibuler** [comment]
1. 这个问题没仔细研究，请研究一下给反馈
2. IP地址是不唯一的，因为可能会映射，一个ip地址映射到不同的服务器，或docker，所以我们设计了hostname唯一
3. 获取不了系统信息，请尝试用 ansible -m setup试试

**Comment by sapser** [comment]
我用的阿里云虚拟机，应该是阿里云对系统镜像做了修改，通过ansible -m setup抓下来的系统信息如下：
    "ansible_distribution": "Welcome", 
    "ansible_distribution_major_version": "Welcome", 
    "ansible_distribution_release": "to", 
    "ansible_distribution_version": "Welcome",

**Comment by sapser** [comment]
补充一下，又看了下ansible的setup模块源码，如果/etc/redhat-release文件存在且不为空的话，红帽系列会从这个文件获取操作系统及版本信息，否则从platform.linux_distribution()函数获取，我这里通过手动回复/etc/redhat-release文件，然后重新更新资产信息可以正确获取到系统及版本了。
