### ISSUE TITLE
LDAP 测试连接报错

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#2000]
##### 使用版本
1.4.3

##### 问题复现步骤
按照官方文档配置后点击连接测试报错

![image](https://user-images.githubusercontent.com/10399425/48123390-b98fcd80-e2b4-11e8-80b7-6b55e6854ccd.png)

日志
```
2018-11-07 16:02:57 [log WARNING] Unauthorized: /api/common/v1/ldap/testing/
2018-11-07 16:03:13 [log WARNING] Unauthorized: /api/common/v1/ldap/testing/
2018-11-07 16:03:23 [log WARNING] Unauthorized: /api/common/v1/ldap/testing/
```

**Comment by vincent927** [comment]
@wojiushixiaobai 麻烦帮忙看看

**Comment by vincent927** [comment]
有没有人碰到过类似问题？

**Comment by wojiushixiaobai** [comment]
@vincent927 没有匹配到用户，检查下ou

**Comment by vincent927** [comment]
> @vincent927 没有匹配到用户，检查下ou

我是Windows AD 
下面是我的配置，我单独创建了一个OU用做测试
![image](https://user-images.githubusercontent.com/10399425/48172954-b6402480-e33c-11e8-9ed1-6374de3d1f80.png)

这样做有问题吗？

**Comment by vincent927** [comment]
我新建了一个jumpserver的ou,然后新建了一个jumpserver的cn,把dn改成这个就好了···  
但是之前的test ou 和 test cn 为什么会有问题···不明白
ou配置不变
