### ISSUE TITLE
关于 windows 资产文件上传速度

### ISSUE THREAD

**Issue by CharkeyQK** [jumpserver/jumpserver#2001]
[简述你的问题]
windows 资产进行文件上传，先上传到 Guacamole docker 容器里面了吗？
后续从 Guacamole RDP 剪切到 windows 磁盘上，传输速度是被什么因素限制了？
谢谢~

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
latest

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他
谢谢~

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@CharkeyQK 对，是上传到了Guacamole的一个共享盘里面，速度受网络影响
