### ISSUE TITLE
新建用户如何自动创建密钥方式登录，而不是密码？

### ISSUE THREAD

**Issue by wuyanteng** [jumpserver/jumpserver#2004]
[简述你的问题]

##### 使用版本
V1.4.3-2 

##### 问题复现步骤
打算创建一个普通用户，后分配资产。但用户创建完成后，邮箱中收到的登陆方式是密码，如何修改为创建完用户就自动就发送用户密钥到邮箱？

对于普通用户，不想让他们使用密码方式

辛苦给解答下，感谢！

**Comment by wojiushixiaobai** [comment]
@wuyanteng 需要手动修改
