### ISSUE TITLE
通过API无法创建指定父节点的资产节点

### ISSUE THREAD

**Issue by Aaron0-wang** [jumpserver/jumpserver#2006]
[简述你的问题]
通过API无法创建指定父节点的资产节点

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
如图所示，我想通过API创建一些和1同一级别的节点，但是无论我怎么写，都会创建到2这个级别
![default](https://user-images.githubusercontent.com/38186870/48187491-33d45680-e376-11e8-94ff-201b92178154.png)
我把父节点写为“1”，创建的节点父节点为‘0’
![default](https://user-images.githubusercontent.com/38186870/48187390-e821ad00-e375-11e8-819e-1ff595e11242.png)
我把父节点写为“0:6”，创建到父节点还是‘0’
![default](https://user-images.githubusercontent.com/38186870/48187399-eeb02480-e375-11e8-9356-fa599546ba69.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by dyangqaq** [comment]
@Aaron0-wang 请问下这个api的文档链接是什么？

**Comment by Aaron0-wang** [comment]
> @Aaron0-wang 请问下这个api的文档链接是什么？

http://10.10.80.42/docs/

**Comment by Aaron0-wang** [comment]
@wojiushixiaobai 这个bug能复现确认吗？

**Comment by Aaron0-wang** [comment]
@wojiushixiaobai 请教怎么解决这个问题？怎么才能通过API创建指定父节点的子节点？我指定key，指定tree_id，指定tree_parent都不行，通过API怎么创建都只会生成二级节点，不能生成三级节点

**Comment by Aaron0-wang** [comment]
我知道了，不是通过这个接口
