### ISSUE TITLE
系统用户不推送，但是资产可连接性正常

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#2011]
[简述你的问题]

##### 使用版本
V1.4.3-2

##### 问题复现步骤
1. 创建一个新资产
2. 资产的硬件详情都能看到
3. 测试资产的连接性也都正常
4. 但是登录资产找不到对应的系统用户

![image](https://user-images.githubusercontent.com/10399425/48239270-4055bf00-e409-11e8-88f7-1d984879bb58.png)
![image](https://user-images.githubusercontent.com/10399425/48239287-4d72ae00-e409-11e8-8eb5-ba6813a756d8.png)
![image](https://user-images.githubusercontent.com/10399425/48239309-5cf1f700-e409-11e8-8fc1-cb8c1a630ae3.png)

![image](https://user-images.githubusercontent.com/10399425/48239343-75621180-e409-11e8-9fec-920096974ff5.png)

##### 其他

后面新创建的资产都有这个问题

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@vincent927 无法复现，使用id命令检查其他用户看看是否正常，检查/etc/passwd文件是否存在用户

**Comment by shiwen5** [comment]
同样的问题，查看celery日志提示信息push_system_user_util .......Not hosts, passed

**Comment by vincent927** [comment]
> @vincent927 无法复现，使用id命令检查其他用户看看是否正常，检查/etc/passwd文件是否存在用户

/etc/passwd 下没有该用户

**Comment by ibuler** [comment]
No hosts 可能代表这个系统用户没有开自动推送，或者服务器类型是windows等
