### ISSUE TITLE
系统用户-公钥存储路径问题

### ISSUE THREAD

**Issue by wuyanteng** [jumpserver/jumpserver#2012]
[简述你的问题]

##### 使用版本
1.4.3-2

##### 问题描述
这个版本中，底层系统用户的ssh公钥和私钥存储到哪儿了？数据库？具体的表？

0.x版本存储到了jumpserver目录中，已找到，但不知道新版本是如何存放的，求告知，谢谢。

**Comment by wojiushixiaobai** [comment]
@wuyanteng 数据库assets_systemuser表里面

**Comment by gotofuck** [comment]
请教为什么数据库里看到的用户公钥和推送到系统的公钥不一致呢？里面的私钥可以拷贝出来直接使用吗？

**Comment by lovese** [comment]
@hmi12 可以用吗？
