### ISSUE TITLE
请问下 SSH 连接方式是不支持中文用户名吗？

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#2021]
[简述你的问题]

##### 使用版本
1.4.3-2

请问下 SSH 连接方式是不支持中文用户名吗？

**Comment by wojiushixiaobai** [comment]
@vincent927 系统支持，但是你的客户端支不支持得验证下

**Comment by vincent927** [comment]
> @vincent927 系统支持，但是你的客户端支不支持得验证下

我的是XSHELL，用户是从AD过来的

**Comment by wojiushixiaobai** [comment]
@vincent927 换客户端试试

**Comment by vincent927** [comment]
我都是默认配置

**Comment by wojiushixiaobai** [comment]
@vincent927 尝试修改客户端编码，如果不行的话咨询下客户端的相关工作人员

**Comment by vincent927** [comment]
额~Xshell不好咨询啊。我相信应该有挺多人碰到我这个问题的吧···希望官方给出解决方案，谢谢

**Comment by vincent927** [comment]
Windows 大部分都是用Xshell

**Comment by vincent927** [comment]
@wojiushixiaobai 多谢，希望能够尽快验证

**Comment by wojiushixiaobai** [comment]
@vincent927 验证xshell不支持

**Comment by vincent927** [comment]
@wojiushixiaobai 多谢
