### ISSUE TITLE
升级至1.4.4-2版本之后，文件管理找不到页面

### ISSUE THREAD

**Issue by vyunwei** [jumpserver/jumpserver#2022]
[简述你的问题]

升级至1.4.4-2版本之后，文件管理找不到页面

##### 使用版本
[1.4.4-2]

##### 问题复现步骤
1. 点击文件管理
2. 
![image](https://user-images.githubusercontent.com/18206104/48339891-25eb4200-e6a4-11e8-8d6d-44b7b1e7117f.png)

##### 具体表现[截图可能会更好些,最好能截全]
jumpserver版本
![image](https://user-images.githubusercontent.com/18206104/48339806-ffc5a200-e6a3-11e8-9f1f-217770432383.png)
coco版本
![image](https://user-images.githubusercontent.com/18206104/48339834-0c49fa80-e6a4-11e8-8e00-26ab87eed949.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@vyunwei 检查coco版本是否更新，检查nginx是否已经加上相应的设置

**Comment by vyunwei** [comment]
找到问题了，nginx没有加coco的配置，多谢
