### ISSUE TITLE
jumpserver升级后，之前“历史会话”记录的“命令”数显示全为0

### ISSUE THREAD

**Issue by badgtgcs** [jumpserver/jumpserver#2025]
[简述你的问题]
jumpserver升级后，之前的“历史会话”记录“命令”数显示全为0，但回放录像却是有记录的。
不知道是不是我配置有问题？

##### 使用版本
[jumpserver 1.4.3 升级至 1.4.4]
1.4.1至1.4.2至1.4.3 好像都有该问题

##### 问题复现步骤
1. [步骤1]
这里显示命令记录为0
![image](https://user-images.githubusercontent.com/43986554/48394198-8f735b00-e74d-11e8-9f4b-de5fb4b894fd.png)
2. [步骤2]
点击“回放”，里面是有操作记录的
![image](https://user-images.githubusercontent.com/43986554/48394232-b03bb080-e74d-11e8-8ef0-67faab37c523.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@badgtgcs 已知问题，拦截的命令并没有执行，所以没有执行记录。

**Comment by wojiushixiaobai** [comment]
@badgtgcs 已验证存在此问题

**Comment by ibuler** [comment]
bug已找到，下个版本解决
