### ISSUE TITLE
请教批量修改密码的实现思路

### ISSUE THREAD

**Issue by 0000sir** [jumpserver/jumpserver#2026]
我最近工作中遇到需要批量修改服务器密码的问题，SSH没问题，用命令跑一遍就差不多了，现在是不知道windows服务器要如何实现，看到项目说明里提到能够实现，求提示实现思路，多谢。

PS. 对python不熟悉，未能找到代码实现

**Comment by lincolnhuang** [comment]
关注，能否实现密码管理的功能

**Comment by jym503558564** [comment]
在xpack已支持改密计划
