### ISSUE TITLE
终端批量上传bug

### ISSUE THREAD

**Issue by jiaxiangkong** [jumpserver/jumpserver#203]
上传 压缩包，文件，文档都失败
如图
![11](https://cloud.githubusercontent.com/assets/16377458/14636287/1a1af81e-065d-11e6-8a16-005af5f0edaf.png)

**Comment by yumaojun03** [comment]
上传文件 走这儿是不通的。

**Comment by ibuler** [comment]
可以的

**Comment by ibuler** [comment]
![image](https://cloud.githubusercontent.com/assets/17382885/14636755/009653b8-0660-11e6-9818-04b153a989d4.png)

**Comment by yumaojun03** [comment]
你专门做的上传模式对吧。 我说通过ansible shell 走 rz应该是不行的。

**Comment by ibuler** [comment]
@jiaxiangkong 直接进入jumpserver内部，使用rz上传试试
