### ISSUE TITLE
测试可连接性、更新硬件信息均失败（显示UNREACHABLE错误）

### ISSUE THREAD

**Issue by morningyi** [jumpserver/jumpserver#2030]
[简述你的问题]

##### 使用版本
Jumpserver 1.4.4
使用Docker安装（ All in one Docker）

##### 问题复现步骤
添加完『管理用户』、『资产』后，使用『测试可连接性』、『更新硬件信息』均失败，失败信息见下图截图（『管理用户』使用root，上传了私钥）。

但资产使用Web终端能正常登录。

截图：
![image](https://user-images.githubusercontent.com/807167/48402367-7a56f600-e766-11e8-8b41-ac9e09abd0df.png)

##### 其他
找到相关问题，但也没给出具体的解决方案：https://github.com/jumpserver/jumpserver/issues/1942

**Comment by wojiushixiaobai** [comment]
@morningyi 这个问题是你资产的安全设置或者ssh设置导致的，非jumpserver产生的问题

**Comment by morningyi** [comment]
> @morningyi 到资产进行检查
能不能描述的详细一些，做哪些检查？（下图是我的资产配置）

![image](https://user-images.githubusercontent.com/807167/48403884-e71fbf80-e769-11e8-842c-1d276c48285f.png)

![image](https://user-images.githubusercontent.com/807167/48403906-f868cc00-e769-11e8-9bc8-1c3a0812e951.png)

**Comment by wojiushixiaobai** [comment]
@morningyi 登录无法测试的资产，检查ssh连接数限制，检查防火墙限制

**Comment by wojiushixiaobai** [comment]
问题过于久远，如果任然存在请重新打开

**Comment by leonanu** [comment]
v2.18.1 也遇到这个问题。WEB 终端可正常 SSH 登录资产。但更新硬件信息、测试连通性均 unreachable。
