### ISSUE TITLE
同一用户隶属于多个组织，在web terminal和ssh中仅显示一个组织的资产列表

### ISSUE THREAD

**Issue by lincolnhuang** [jumpserver/jumpserver#2031]
[简述你的问题]
同一用户隶属于多个组织，在web terminal和ssh中仅显示一个组织的资产列表，但可以搜索到另一组织的列表

##### 使用版本
1.4.4-2

##### 问题复现步骤
1. 操作数据库，把用户添加到orgs_organization_admins和orgs_organization_users表
使一个用户隶属于多个组织
2. 分别在2个组织创建授权规则
3. 在web terminal和ssh terminal（2222）里查看资产组仅显示一个组织的资产列表，但可以搜索到另一组织的资产列表

##### 具体表现[截图可能会更好些,最好能截全]
![qq 20181113183718](https://user-images.githubusercontent.com/30144073/48408318-03285e80-e774-11e8-84a6-543fd428a2d1.png)
![qq 20181113183750](https://user-images.githubusercontent.com/30144073/48408330-07ed1280-e774-11e8-9a4e-7b3bbd904dcf.png)
![qq 20181113183806](https://user-images.githubusercontent.com/30144073/48408336-0d4a5d00-e774-11e8-8160-28f760916dde.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lincolnhuang

**Comment by ibuler** [comment]
fixed

**Comment by lincolnhuang** [comment]
亲测有效，感谢修复

**Comment by lincolnhuang** [comment]
![image](https://user-images.githubusercontent.com/30144073/48529941-70510680-e8d0-11e8-9a7e-b40d2e63c93b.png)
SSH Terminal下显示有权限的节点还是有问题，麻烦检查下。

**Comment by lincolnhuang** [comment]
都OK了，感谢修复！
