### ISSUE TITLE
windows支持上下传文件

### ISSUE THREAD

**Issue by zxl0715** [jumpserver/jumpserver#2032]
[简述你的问题]

操作windows和 linux 如何通过jumpserver 进行文件上传和下载，是否可以支持拖拽上下传文件。
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zxl0715 请仔细看文档，ssh支持websftp和sftp

**Comment by xionghui** [comment]
2008怎么没有G盘？

**Comment by auqf** [comment]
无法上传和下载文件，提示报错，有什么特殊设置吗？
![image](https://user-images.githubusercontent.com/8895540/84750611-12c1f600-afee-11ea-9d7b-30fcddeeb53c.png)
