### ISSUE TITLE
web端 session超时   资产组授权问题

### ISSUE THREAD

**Issue by xujingbin** [jumpserver/jumpserver#2033]
使用版本
Version 1.4.3-2 GPLv2

问题复现步骤
1、连接后端服务器，空闲时间超过 30 分钟会断开连接，如何设置保持更长时间的空闲会话连接
2、同组用户，授权给该组登录机器权限时，组员之间可以登录彼此的账号，这个可以改成只能登录自己账号吗

**Comment by wojiushixiaobai** [comment]
@dinggel 
第一个问题，web后台--系统设置--安全设置--SSH最大空闲时间
第二个问题，授权有误，请给各个用户分开授权

**Comment by dinggel** [comment]
web终端操作，灵敏度好差，可以调节吗？
web终端的字符没办法进行command+f搜索
若是windows系统  进行ctrl +w  会关闭该浏览器标签的所有session

**Comment by wojiushixiaobai** [comment]
@dinggel 设置需要重启，请根据需求定制系统用户并进行合理的授权。

**Comment by ibuler** [comment]
已对关闭窗口增加拦截，让用户确认

**Comment by dinggel** [comment]
提交新代码了吗？
