### ISSUE TITLE
ssh 连接 rz,sz命令经常卡住

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#2041]
[简述你的问题]

##### 使用版本
1.4.3-2

##### 问题复现步骤
1. 通过ssh到一个服务器，sz 一个日志文件到本地
2. 如图卡住不动了
3. 时好时坏

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/10399425/48472315-fe75b000-e830-11e8-9f34-b76105383630.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@vincent927 请使用sftp

**Comment by vincent927** [comment]
可是sftp只能在/tmp目录上传下载 😢

**Comment by ibuler** [comment]
平时连接服务器，rzsz也有失败的情况，这个确实不好处理

**Comment by vincent927** [comment]
> 平时连接服务器，rzsz也有失败的情况，这个确实不好处理

好的，感谢 😄
