### ISSUE TITLE
LDAP用户可以通过忘记密码处修改密码

### ISSUE THREAD

**Issue by Aaron0-wang** [jumpserver/jumpserver#2042]
[简述你的问题]
1. 忘记密码问题
- 我之前看到你们的验证逻辑是先去ldap验证密码，如果不通过就去自己的数据库里验证密码。如果用户是ldap用户，在个人信息里自己是修改不了密码的，这个逻辑没问题。但是他可以在**登陆处忘记密码**，从而达到修改密码的目的，这样又是**两套密码都能够使用**。。。
- 建议所有的ldap用户不能修改密码，不能忘记密码，所有关于密码的操作全都干掉——或者直接**把ldap用户和创建的用户分表存**，ldap用户的表不设置密码字段，这样就能杜绝了（ldap本来就有统一的修改自己密码的手段，不需要jumpserver来做）
2. MFA问题
- 如果开启了MFA，然后**管理员丢掉了自己的MFA**，比如不小心卸载了应用，或者手机丢了，那连管理员也登录不了系统了，该怎么找回呢？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.2和1.4.4
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@Aaron0-wang ldap用户的问题会在后面进行优化

**Comment by Aaron0-wang** [comment]
ok，期待之后的优化
