### ISSUE TITLE
能否关闭SSH终端的翻页功能

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2049]
[简述你的问题]
SSH的翻页功能感觉不是很好用，想关闭掉该功能

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

主要是想关闭SSH terminal的翻页功能
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 异步，资产过多情况这个是需要的，你可以直接输入资产信息进行匹配登录

**Comment by ibuler** [comment]
需要更多反馈

**Comment by jym503558564** [comment]
在成千上万资产的情况下，翻页功能还是很有必要的。或者您可直接搜索资产进行匹配登录。如有其它问题可重新打开issues~
