### ISSUE TITLE
sftp 无法访问

### ISSUE THREAD

**Issue by chenlin0802** [jumpserver/jumpserver#2050]
[简述你的问题]
当系统用户设置手动登录时， sftp 无法访问，提示没有权限。 当改为自动登录后可以正常通过sftp上传下载文件。 

##### 使用版本
[1.4.4]

可以通过 修改代码 coco/sftp.py 来解决这个问题？ 如下图：
![image](https://user-images.githubusercontent.com/9802633/48597837-d6a25b80-e99a-11e8-9620-d324b7264ea2.png)

注释掉  and su.login_mode == 'auto'  部分， 但是不知道这样做的话会有没有其他影响？ 

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chenlin0802 不支持手动方式登录，在系统用户里面修改为自动登录
