### ISSUE TITLE
跳板机搜索资产，提示错误：Connection closing...Socket close.

### ISSUE THREAD

**Issue by wuyanteng** [jumpserver/jumpserver#2052]
[简述你的问题]
![qq 20181116171543](https://user-images.githubusercontent.com/26731482/48612293-8ee3fa00-e9c3-11e8-9718-42cd52e2d70a.png)

跳板机搜索资产，提示错误：Connection closing...Socket close.

#### 问题描述
做了个jumpserver备机，备机各项服务均启动正常，资产也均已导入正常，跳板机2222端口可以正常连接并且进入，搜索资产时，直接退出。【主jumpserver不存在这个问题】

#### 版本
V1.4.4

**Comment by wuyanteng** [comment]
COCO Log:
2018-11-16 18:04:00 [sshd ERROR] Unexpected error occur: request() got an unexpected keyword argument 'user_auth'

**Comment by wuyanteng** [comment]
自己已解决

**Comment by 191801737** [comment]
@wuyanteng  是啥问题？怎么解决的

**Comment by wuyanteng** [comment]
@191801737 coco得从主的拷贝过来

**Comment by ibuler** [comment]
该问题升级一下sdk可以解决
