### ISSUE TITLE
增加支持安卓远程桌面

### ISSUE THREAD

**Issue by OwenSharpKing** [jumpserver/jumpserver#2060]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
表述内容太少，不太命名

**Comment by yssnet** [comment]
@ibuler 他说的是手机客户端吧
