### ISSUE TITLE
在线会话遇到的新问题

### ISSUE THREAD

**Issue by switchchow** [jumpserver/jumpserver#2063]
[简述你的问题]

##### 使用版本
Version 1.4.1-2

##### 问题复现步骤
在线会话无法清理，和之前的朋友是同一个问题，已经升级版本了。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
升级到 1.4.4再看看吧，我记得是在某个版本解决了

**Comment by switchchow** [comment]
@ibuler ，谢谢，我使用的还是1.4.1-2，今天又在群里提问了....后来我自己排查了一下，在线绘话和coco占cpu率高的问题暂时算解决了吧，目前运行良好，我新提了一个issue当作反馈.....不知道有没有用.......
