### ISSUE TITLE
禁止用户修改个人信息， 包括用户名、名称及邮箱

### ISSUE THREAD

**Issue by chenlin0802** [jumpserver/jumpserver#2066]
[简述你的问题]

是否可以关闭用户自己修改个人信息？ 
![image](https://user-images.githubusercontent.com/9802633/48767537-ecdd4e00-ecf1-11e8-94a3-da90deeff198.png)

**Comment by chenlin0802** [comment]
如果每个人都恶意的随便改改的话， 会乱掉的

**Comment by ibuler** [comment]
已支持
