### ISSUE TITLE
coco中断

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2068]
[简述你的问题]
连接到ssh终端以后输入需要访问的IP或者Hostname，会立刻中断连接

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4
##### 问题复现步骤
1. [步骤1]打开并连接到ssh终端
2. [步骤2]立刻输入Hostname或者IP
3.访问中断

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42203736/48774562-94b04700-ed05-11e8-9b38-639453daecb0.png)
![image](https://user-images.githubusercontent.com/42203736/48774589-a1cd3600-ed05-11e8-80be-02b4c1884dd2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 检查下依赖和coco的版本

**Comment by RaynorAZ** [comment]
python3的依赖都是按照需求安装的，coco的版本是1.4.4配套的版本。怀疑是否是异步加载导致的问题？1.4.3更新到异步之前并没有发生这样的情况。安装方法和代码都是相同的。

**Comment by ibuler** [comment]
该问题已知，目前可以通过修改  jumpserver-python-sdk代码解决

```
https://github.com/jumpserver/jumpserver-python-sdk/blob/dev/jms/perms.py#L87

$ cd /opt/py3/lib/python3.6/site-packages/jms
$ vim perms.py
resp = self.http.get('user-assets', pk=user.id, **user_auth**=True, params=params)
改为
resp = self.http.get('user-assets', pk=user.id, **use_auth**=True, params=params)

```
