### ISSUE TITLE
v1.4.4 LDAP无法登录

### ISSUE THREAD

**Issue by jackeri0** [jumpserver/jumpserver#2075]
ldap配置成功，web端无法登录

##### 使用版本
1.4.4

##### 问题复现步骤
1. 在web端配置LDAP，测试连接可以获取用户数
![ldap_config](https://user-images.githubusercontent.com/22347496/48879825-8dde1d00-ee48-11e8-80bd-52413469bcbd.png)
![ldapuser](https://user-images.githubusercontent.com/22347496/48879887-e01f3e00-ee48-11e8-87bf-7b659ae7ae23.png)

2. 重启服务
```
./jms stop
./jms start all -d
```
3.web登录失败，日志显示：
```
[config ERROR] result(2) raised INVALID_DN_SYNTAX({'info': 'invalid DN', 'desc': 'Invalid DN syntax'},)
```

##### 其他

[注:] 完成后请关闭 issue

**Comment by jackeri0** [comment]
@wojiushixiaobai 确定进程都结束了再重启的，还是不行。openldap的日志是这样的：
![ldap_log](https://user-images.githubusercontent.com/22347496/48886955-a52d0280-ee68-11e8-8087-4e0d060e0399.png)

**Comment by wojiushixiaobai** [comment]
@jackeri0 确定映射的属性都存在，且username和email不能与其他用户相同

**Comment by jackeri0** [comment]
我检查了一遍，属性映射都存在，测试用的openldap只留了一个用户，所以username和email肯定是唯一的。
为什么openldap的日志会是`invalid dn: "None"`?

**Comment by wojiushixiaobai** [comment]
@jackeri0 把内容清空后重新手打一遍试试，看是不是有多余的字符等

**Comment by jackeri0** [comment]
@wojiushixiaobai 谢谢您的耐心解答！
其实相关的检查我都做了好几遍了，还是同样的报错。我不懂python，不知是不是代码里有bug，还是我部署有问题？我再重新部署一次试一下，要崩溃了。 😕

**Comment by jackeri0** [comment]
@wojiushixiaobai 已加入群，群内名称：“重庆-生生不息”，有空的时候麻烦帮我看一下
