### ISSUE TITLE
新版1.4.4主机组功能在哪？

### ISSUE THREAD

**Issue by zhouzhenhua** [jumpserver/jumpserver#2077]
[简述你的问题]
新版1.4.4主机组功能在哪？

##### 使用版本
V1.4.4

##### 问题复现步骤
1. 0.3.2有一个所属主机组功能，在数据库jasset_assetgroup表存储数据，新版1.4.4系统后台界面怎么找不到？ 我登录新版的数据库，有看到assets_assetgroup表，疑惑？

##### 具体表现[截图可能会更好些,最好能截全]

> 

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新版本使用 节点，可以嵌套的 资产组
