### ISSUE TITLE
CELERY_BROKER_URL拼写有误

### ISSUE THREAD

**Issue by ymping** [jumpserver/jumpserver#2080]
[简述你的问题]
位于 [apps/jumpserver/settings.py](https://github.com/jumpserver/jumpserver/blob/c0d51e22d77213e460a6389289cd3c56de91aee3/apps/jumpserver/settings.py#L417) 中的 CELERY_BROKER_URL 拼写有误
在 config_example.py 中的定义的变量为 `REDIS_DB_CELERY = os.environ.get('REDIS_DB') or 3`
在 settings.py 中使用的变量语句是 `'db':CONFIG.REDIS_DB_CELERY_BROKER or 3`
REDIS_DB_CELERY_BROKER 未定义导致直接取到了默认db 3，而非在 config.py 中的设置的 REDIS_DB_CELERY

##### 使用版本
Version 1.4.4-2 

##### 问题复现步骤
参考[文档](https://jumpserver.readthedocs.io/zh/docs/setup_by_ubuntu.html#jumpserver)安装JumpServer, cp config_example.py 为 config.py，编辑 config.py 设置  `REDIS_DB_CELERY = os.environ.get('REDIS_DB') or 5`，其它设置按文档，启动 jumpserver 后，redis的 db 5 没有被使用，无数据，redis的 db 3 被使用，有数据。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ymping 已收到，感谢

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/config_example.py#L76  
已修复，下个版本更新

**Comment by ibuler** [comment]
ok, 已更改

**Comment by ymping** [comment]
@ibuler 这个问题好像还是没对哦，是不是更改没有合进来。现在的 master 分支 apps/jumpserver/settings.py 和 config_example.py 2个文件中的 REDIS DB CELERY 命名还是不一至呢

**Comment by ibuler** [comment]
已处理
