### ISSUE TITLE
用户页面下，标签点击没有选项，无法使用

### ISSUE THREAD

**Issue by lincolnhuang** [jumpserver/jumpserver#2082]
[简述你的问题]
在用户页面下，点击资产标签没有下拉框，无法使用

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4-2

##### 问题复现步骤
1. [步骤1]
在管理页面下，标签配置后正常显示
![qq 20181123162851](https://user-images.githubusercontent.com/30144073/48934000-47b6b580-ef3d-11e8-8ecd-922b4ea2e738.png)

2. [步骤2]
切换到用户页面，点击标签没有下拉框，无法使用
![qq 20181123162903](https://user-images.githubusercontent.com/30144073/48934017-58ffc200-ef3d-11e8-88e6-98c12ebe76da.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lincolnhuang 根据资产列表的设置显示的，资产列表未分级导致的。非bug

**Comment by lincolnhuang** [comment]
@wojiushixiaobai 资产列表分级指的是？

**Comment by wojiushixiaobai** [comment]
@lincolnhuang 未看清楚内容，抱歉，以为你说的是资产不在节点下显示

**Comment by jym503558564** [comment]
目前已修复，将在未来新版本里更新，请持续关注。
