### ISSUE TITLE
是否考虑兼容高版本mysql

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#2084]
从1.4.2的时候将mysql升级到了mysql8.0.13，今天准备升级到1.4.4，结果sh make_migrations.sh报错，提示创建约束失败，重复执行就提示admin_log已存在

**Comment by ibuler** [comment]
和数据库版本无关，可能是你的migrations文件重复了，以后官方统一提供migraitons

**Comment by mrbaiwei** [comment]
这就奇怪了，我用备份中的程序(确认和失败的是相同的)和老的数据库重新操作就升级成功了，唯一的区别就是数据库版本，还有改为了远程调用

**Comment by mrbaiwei** [comment]
> 和数据库版本无关，可能是你的migrations文件重复了，以后官方统一提供migraitons

这就奇怪了，我用备份中的程序(确认和失败的是相同的)和老的数据库重新操作就升级成功了，唯一的区别就是数据库版本，还有改为了远程调用
