### ISSUE TITLE
cocodCPU过高

### ISSUE THREAD

**Issue by xiaosadexiaohai** [jumpserver/jumpserver#2089]
[简述你的问题]
cocod只使用单线程导致CPU过高,cpu一直保持在100

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.2-2 GPLv2.
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/18409309/48989963-7912c980-f167-11e8-809c-23e7718af507.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by switchchow** [comment]
就我这边的情况来看，有一部分机器是下线了，就是说连接不上了，先把它从资产列表里清除。重启一下coco进程，目前情况还比较好。

**Comment by chenglu01** [comment]
cocod 组件负载有没有针对jumpserver-1.3.3-2版本的，使用jms_coco:1.4.8镜像发现docker容器中的cocod启动不了

**Comment by ibuler** [comment]
已修复
