### ISSUE TITLE
系统用户推送，原用户密码被覆盖

### ISSUE THREAD

**Issue by zhouzhenhua** [jumpserver/jumpserver#2093]
[简述你的问题]
系统用户推送，原用户密码被覆盖

##### 使用版本
jumpserver v1.4.4

##### 问题复现步骤
1. 比如服务器上已有admin帐号，设admin系统用户，自动推送后，原admin密码好像被覆盖，用xhell直连登录不上了

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果是已存在的用户，不要开启自动推送

**Comment by zhouzhenhua** [comment]
谢谢，验证OK，关单吧

**Comment by zhouzhenhua** [comment]
验证OK，关单

**Comment by vincent927** [comment]
> 如果是已存在的用户，不要开启自动推送

我也碰到这种情况，我后来又把系统用户改成了之前的密码，后续影响Jumpserver使用吗？
