### ISSUE TITLE
网域网关功能使用

### ISSUE THREAD

**Issue by zhouzhenhua** [jumpserver/jumpserver#2095]
[简述你的问题]
网域网关功能使用?

##### 使用版本
v1.4.4

##### 问题复现步骤
产品
1. 网域列表: 创建一个网域，并设置网关，测试连接返回【可连接】。
2. 资产列表: 添加云端主机内网IP,绑定网域。

网络拓扑：公司内网JMS服务器可SSH连到云主机内网某一台linuxＶＭ【公网IP+端口方式】,比如想用这台LINUX充当网关服务角色，让内网的JMS,可管理主端内部所有VM.  
最后验证更新资产硬件信息时出错。

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/13253021/48999537-ec313580-f191-11e8-8af1-256bad57e1de.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yubinhong** [comment]
我现在也遇到这个问题了

**Comment by zhouzhenhua** [comment]
网域网关密码不允许包含特殊字符, 基本上功能无BUG

**Comment by EricBatty** [comment]
你好，网关测试我都没有测试通，网关哪里是写云主机内网的一个服务器的ip地址吗？

**Comment by jym503558564** [comment]
目前关于这个问题是否已解决？

**Comment by jym503558564** [comment]
git pull 更新一下，如有其它问题，可重新打开issues

**Comment by wandouduoduo** [comment]
解决了吗？我也遇到了，jms到网关测试成功，但新建虚机资产选择该网域，测试该虚机连不通
