### ISSUE TITLE
如何让用户自己填写系统用户密码？

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#2096]
[简述你的问题]
我的Jump server使用LDAP认证，系统用户也是使用的LDAP用户，所以没有自动推送。
我作为管理员，创建系统用户后，并不知道用户的系统用户密码，如何能让用户自己填写系统用户密码（填写LDAP用户密码）？
我发现用户登录Web界面后，并没有可以填写系统户密码的地方。

还有，就是以后每次用户修改LDAP密码的时候，都得更新系统用户密码？

##### 使用版本
1.4.3-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/49009984-eb59cd00-f1ac-11e8-8b64-875dba51c29d.png)

**Comment by brucegogo** [comment]
@ibuler 
系统用户这个界面是只有管理员用户才能看到的，普通用户无法看到。
我不能让每个用户都来我电脑上输入密码吧。管理员用户也不应该改知道用户自己的密码。

**Comment by brucegogo** [comment]
不知道大家是怎么管理系统用户密码的，难道都是由管理员输入？用户改了密码后，都要找管理员来更新？

**Comment by brucegogo** [comment]
还有就是如何LDAP账户密码更改后，用户也得上我这来输入密码？  

这个是不是可以考虑增加一个功能啊，让用户自己输入系统用户密码。

**Comment by wojiushixiaobai** [comment]
@brucegogo 新版本系统用户已经支持手动登录，请更新后尝试
