### ISSUE TITLE
增加minio支持

### ISSUE THREAD

**Issue by iceking2nd** [jumpserver/jumpserver#2097]
请求增加对minio作为第三方存储的支持。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
你可以尝试共享一下哦，最近开发组没有时间支持这个

**Comment by iceking2nd** [comment]
> 
> 
> 你可以尝试共享一下哦，最近开发组没有时间支持这个

哈哈，这个我就有心无力了，我不会Python，不过简单的查了一下，好像boto3的库自定义一下endpoint的地址就可以直接支持minio。
