### ISSUE TITLE
联动LDAP后，如果与LDAP连接断开，本地用户也无法登陆

### ISSUE THREAD

**Issue by 41672** [jumpserver/jumpserver#2105]
联动LDAP后，如果与LDAP连接断开，本地用户也无法登陆

##### 使用版本
[1.4.3]

##### 问题复现步骤
1. 关联windows ad域
2. 测试可以使用域账户登录
3. 防火墙阻挡jumpserver到windows域服务器的网络连接
4. 使用jumpserver本地admin账户登录，登录失败，页面无法正常跳转

##### 具体表现
![image](https://user-images.githubusercontent.com/36252096/49122288-c40b1900-f2ee-11e8-9527-0ed35f5705cf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
修改配置文件，AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_TIMEOUT: 30
}

修改这个值小于nginx 的 timeout值
