### ISSUE TITLE
登陆centos7.5 不超过3分钟，就出现死机

### ISSUE THREAD

**Issue by chenghali** [jumpserver/jumpserver#2107]
[简述你的问题]

通过跳板机连接欸cenots7.5系统，刚开始可以输入命令，过3分钟后，出现卡死状态，输入命令没有反应，测试centos7.2系统没有出现这个问题，windows系统也正常。请问是否不支持centos7.5？
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
 Version 1.4.4-2 GPLv2. 
##### 问题复现步骤
1.连接--输入命令
2. 不做任何操作，过3分钟后-出现卡死状态

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/45415934/49133724-08f97480-f31c-11e8-83b9-002043fdba83.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
没有更多信息，无法判断

**Comment by chenghali** [comment]
> 没有更多信息，无法判断

![image](https://user-images.githubusercontent.com/45415934/50411135-a8852680-0838-11e9-8c46-48771e496318.png)
这是7.2系统 ，超过空闲30分钟会提示 


![image](https://user-images.githubusercontent.com/45415934/50411149-c8b4e580-0838-11e9-8992-18294458617b.png)
这是7.5系统，超过2分钟，自动卡机，输入不了命令


历史会话对比图
![image](https://user-images.githubusercontent.com/45415934/50411163-dff3d300-0838-11e9-9cfb-b9f831773133.png)


![image](https://user-images.githubusercontent.com/45415934/50411175-fc900b00-0838-11e9-9c39-7edcde746b04.png)
