### ISSUE TITLE
关于在线会话无法清理、coco进程占cpu高的个人反馈

### ISSUE THREAD

**Issue by switchchow** [jumpserver/jumpserver#2109]
##### 使用版本
Version 1.4.1-2

##### 问题复现步骤
在线会话问题：也采取了在目标机器踢终端的方法，但有很多在线会话始终无法清理。
coco的cpu使用率比较高：查看日志，发现有 ”Socket exception: Connection timed out “报错，经过检查，存在一部分已经下线的机器，将其从资产列表中清除，重启coco进程。
后续观察：在线会话基本被清理了（重启coco后直接观察），coco进程cpu占用率也回归一个正常的状态。

[注:] 目前使用良好，coco进程cpu占用率也正常，权当一个反馈了。

**Comment by xiaosadexiaohai** [comment]
也就说coco占用cpu高是因为没有及时把下线的机器删除导致的？我这边也是coco非常高 每次都得重启

**Comment by switchchow** [comment]
@xiaosadexiaohai 我没有研究过代码.....但就我是这样处理的，截至现在只处理了一次，没有复现。
