### ISSUE TITLE
coco分布式部署后，jumpserver的远端IP地址为jumpserver 机器IP

### ISSUE THREAD

**Issue by a604745584** [jumpserver/jumpserver#2112]
[简述你的问题]
安装官网分布式文档，配置本机 双coco 进程 后，通过XSHELL 等SSH 工具登录jumpserver后 ，在线会话 和历史命令 里的的远端 IP 均为jumpserver本机IP，而不是真实的 客户端IP

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
 Version 1.4.3-2 GPLv2. 
##### 问题复现步骤
1. [步骤1]
jumpserver     coco  coco1   redis  mysql  nginx  均部署在 10.0.13.103 这台机器上，配置 coco多进程 用nginx 反向代理后，在线会话和历史记录里的远端ip  均为 本机ip:10.0.13.103
但是在 nginx 日志/var/log/nginx/tcp-access.log 能看到 SSH 连接的客户端地址，
请教这个 该 如何修改？
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/15830347/49266629-e1c4b380-f491-11e8-9c71-e07f6f2a7b62.png)

<img width="1052" alt="default" src="https://user-images.githubusercontent.com/15830347/49266729-3cf6a600-f492-11e8-805c-175f79251550.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@a604745584 ssh本身也存在这个问题，后面看看有没有更好的解决方案
