### ISSUE TITLE
使用web终端的时候可以直接执行一个脚本或命令么

### ISSUE THREAD

**Issue by minnan0422** [jumpserver/jumpserver#2113]
[简述你的问题]
我们可能需要这样的一个场景，用户使用web终端的时候直接跳到进入mysqlUI，用户不需要知道mysql的账号及密码，看到之前的issue有提到新版本不能直接连接mysql，oracle了

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是一个不错的场景
