### ISSUE TITLE
系统用户推送修改密码

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#2116]
[简述你的问题]

系统用户推送到资产，如果该资产之前已经有这个用户了，是会修改这个用户的密码吗？

##### 使用版本
1.4.3-2

**Comment by vincent927** [comment]
我之前存在的用户密码被覆盖了，有没有办法不覆盖已经存在的系统用户密码

**Comment by BaiJiangJie** [comment]
目前情况是这样的，
如果资产上系统用户不存在，推送时，会在对应资产上创建该系统用户；
如果资产上系统用户已存在，推送时，会更新对应资产上该系统用户的密码；

您是想在推送时，如果资产上已有该系统用户，则跳过；如果没有，再创建用户吗？

在推送的时候，您可以设置和已存在系统用户相同的密码。

**Comment by vincent927** [comment]
> 在推送的时候，您可以设置和已存在系统用户相同的密码。

谢谢

其实我想要的最好方法是，我创建系统用户的时候已经选择了密钥，就不要去修改我已经存在的系统用户密码了 😢 

没搞清楚Jumpserver为什么要去修改已存在的系统用户密码，不是都已经通过密钥验证了吗

**Comment by vincent927** [comment]
也就是 
1、我选择了密钥，就更新我的密钥就行，不更新密码
2、我选择了密码，就更新我的密码就行，不更新密钥

我觉得这样逻辑上更行的通也更合理
