### ISSUE TITLE
web终端 登陆windows server2016报错 "该主机没有授权登录用户"

### ISSUE THREAD

**Issue by scott3721** [jumpserver/jumpserver#2119]
[简述你的问题]
会话管理-web终端 登陆windows server2016报错 "该主机没有授权登录用户"
重复faq里的介绍，重新注册guacamole，配置管理用户，系统用户，windows资产，但问题依旧。
还请协助，谢谢。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
版本1.4.4-101

##### 问题复现步骤
1.创建管理用户
2.创建系统用户
3.创建 Windows 资产
4.授权资产给用户
5.使用web终端登陆

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/20701458/49326453-49abf480-f58d-11e8-8ba4-565bbf8c5a97.png)

guacamole在线
![default](https://user-images.githubusercontent.com/20701458/49326528-71e82300-f58e-11e8-8a48-598dbe2f7dcf.png)

资产管理员已建立
![default](https://user-images.githubusercontent.com/20701458/49326482-a4dde700-f58d-11e8-84d8-9bbd0ff37f9e.png)

资产管理员已绑定
![default](https://user-images.githubusercontent.com/20701458/49326461-5cbec480-f58d-11e8-8582-baa3a0e90ed2.png)

系统管理员已建立
![default](https://user-images.githubusercontent.com/20701458/49326500-04d48d80-f58e-11e8-994e-d3bdbb13fb33.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
授权的是一个rdp协议的系统用户吗

**Comment by redkins** [comment]
请在电脑属性设置。

**Comment by jym503558564** [comment]
问题是否已解决？

**Comment by anjia0532** [comment]
@scott3721 你应该是没有配置授权吧？

**Comment by jym503558564** [comment]
问题是否还复现，鉴于使用版本较低，可更新一下各个组件，再进行测试。如有其它问题，可重新打开issues~

**Comment by wumandi** [comment]
请问一下问题最后怎么解决的？
