### ISSUE TITLE
jumpserver,无法更新CentOS 7.3.1611 x86_64磁盘容量

### ISSUE THREAD

**Issue by zx289317972** [jumpserver/jumpserver#2122]
[简述你的问题]
jumpserver,无法更新CentOS 7.3.1611 x86_64磁盘容量
![qq 20181203105219](https://user-images.githubusercontent.com/34121470/49350586-7aee0700-f6ea-11e8-9371-fed5c64bd7cb.png)

##### 使用版本
Version 1.4.0-2 GPLv2

##### 问题复现步骤
1. [步骤1]
测式连接，更新硬件信息
![qq 20181203104837](https://user-images.githubusercontent.com/34121470/49350603-83ded880-f6ea-11e8-98b2-7c316725cfc5.png)
具体哪个模块城要提供日志呢？
2. [步骤2]
另外在CentOS 6.3 x86_64测式连接，更新硬件信息 ok,可获取磁盘容量

##### 其他

[注:] 完成后请关闭 issue

**Comment by npcomet** [comment]
跟系统无关 跟磁盘连接方式有关 看下你的硬盘设备路径是什么

**Comment by zx289317972** [comment]
是指的磁盘挂载路径么。
![image](https://user-images.githubusercontent.com/34121470/49416493-1481eb00-f7b5-11e8-887c-9ee833b183e2.png)

**Comment by jym503558564** [comment]
问题是否已解决？

**Comment by zx289317972** [comment]
@jym503558564  额，没有，你不提醒我都忘记了还有这个问题
