### ISSUE TITLE
1.4.1版本添加计划任务后删除代码后依旧会跑 

### ISSUE THREAD

**Issue by ismallpotato** [jumpserver/jumpserver#2126]
[简述你的问题]

##### 使用版本
jumpserver 1.4.1 版本

##### 问题复现步骤
添加计划任务，删除计划任务，重新 jms restart 后删除的计划任务依旧在跑，情况redis 后重启项目也是一样，求教

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
哪里的计划任务？

**Comment by ismallpotato** [comment]
![image](https://user-images.githubusercontent.com/31843586/49714683-d1c68400-fc88-11e8-89f3-d85076a12027.png)
在assets 下面的task 增加的测试

**Comment by ibuler** [comment]
在加上装饰器 @after_app_shutdown_clean，当关闭时才会清除

````
@shared_task
@register_as_period_task(interval=3600)
@after_app_ready_start
@after_app_shutdown_clean
def task():
    ....

```

**Comment by ismallpotato** [comment]
好的，我改一下，十分感谢!
