### ISSUE TITLE
升级遇到问题

### ISSUE THREAD

**Issue by cailangnick** [jumpserver/jumpserver#2127]
[简述你的问题]
当前版本：Version 1.2.0-2 GPLv2
升级版本：Version 1.4.4
执行此步骤
$ cd utils && sh make_migrations.sh出错
(py3) root@ubuntu:/opt/jumpserver# cd utils && sh make_migrations.sh
2018-12-05 10:29:12 [signals_handler DEBUG] Receive django ready signal
2018-12-05 10:29:12 [signals_handler DEBUG]   - fresh all settings
Migrations for 'assets':
  /opt/jumpserver/apps/assets/migrations/0002_auto_20181205_1029.py
    - Create model CommandFilter
    - Create model CommandFilterRule
    - Create model Domain
    - Create model Gateway
    - Create model Label
    - Create model Node
    - Change Meta options on adminuser
    - Change Meta options on asset
    - Change Meta options on assetgroup
    - Change Meta options on cluster
    - Change Meta options on systemuser
    - Add field org_id to adminuser
    - Add field cpu_vcpus to asset
    - Add field org_id to asset
    - Add field protocol to asset
    - Add field assets to systemuser
    - Add field login_mode to systemuser
    - Add field org_id to systemuser
    - Alter field created_by on adminuser
    - Alter field name on adminuser
    - Alter field username on adminuser
    - Alter field admin_user on asset
    - Alter field hostname on asset
    - Alter field platform on asset
    - Alter field created_by on assetgroup
    - Alter field created_by on systemuser
    - Alter field name on systemuser
    - Alter field priority on systemuser
    - Alter field protocol on systemuser
    - Alter field sudo on systemuser
    - Alter field username on systemuser
    - Alter unique_together for adminuser (1 constraint(s))
    - Remove field cabinet_no from asset
    - Remove field cabinet_pos from asset
    - Remove field cluster from asset
    - Remove field env from asset
    - Remove field groups from asset
    - Remove field remote_card_ip from asset
    - Remove field status from asset
    - Remove field type from asset
    - Add field domain to asset
    - Add field labels to asset
    - Add field nodes to asset
    - Alter unique_together for asset (1 constraint(s))
    - Remove field cluster from systemuser
    - Add field cmd_filters to systemuser
    - Add field nodes to systemuser
    - Alter unique_together for systemuser (1 constraint(s))
    - Alter unique_together for label (1 constraint(s))
    - Alter unique_together for gateway (1 constraint(s))
Migrations for 'common':
  /opt/jumpserver/apps/common/migrations/0001_initial.py
    - Create model Setting
Migrations for 'ops':
  /opt/jumpserver/apps/ops/migrations/0002_celerytask.py
    - Create model CeleryTask
Migrations for 'orgs':
  /opt/jumpserver/apps/orgs/migrations/0001_initial.py
    - Create model Organization
Migrations for 'terminal':
  /opt/jumpserver/apps/terminal/migrations/0002_auto_20181205_1029.py
    - Add field org_id to command
    - Add field date_last_active to session
    - Add field org_id to session
    - Add field protocol to session
    - Add field remote_addr to session
    - Add field terminal to session
    - Add field terminal to status
    - Add field terminal to task
    - Add field command_storage to terminal
    - Add field replay_storage to terminal
    - Add field user to terminal
    - Alter field asset on command
    - Alter field system_user on command
    - Alter field user on command
    - Alter field date_start on session
    - Alter field name on terminal
Migrations for 'users':
  /opt/jumpserver/apps/users/migrations/0003_auto_20181205_1029.py
    - Change Meta options on user
    - Change Meta options on usergroup
    - Remove field enable_otp from user
    - Remove field secret_key_otp from user
    - Add field mfa to loginlog
    - Add field reason to loginlog
    - Add field status to loginlog
    - Add field _otp_secret_key to user
    - Add field otp_level to user
    - Add field source to user
    - Add field org_id to usergroup
    - Alter field username on loginlog
    - Alter field date_expired on user
    - Alter field is_first_login on user
    - Alter field last_name on user
    - Alter field created_by on usergroup
    - Remove field discard_time from usergroup
    - Remove field is_discard from usergroup
    - Alter unique_together for usergroup (1 constraint(s))
Migrations for 'audits':
  /opt/jumpserver/apps/audits/migrations/0001_initial.py
    - Create model FTPLog
    - Create model OperateLog
    - Create model PasswordChangeLog
    - Create proxy model UserLoginLog
Migrations for 'perms':
  /opt/jumpserver/apps/perms/migrations/0002_auto_20181205_1029.py
    - Create model NodePermission
    - Change Meta options on assetpermission
    - Add field date_start to assetpermission
    - Add field nodes to assetpermission
    - Add field org_id to assetpermission
    - Add field user_groups to assetpermission
    - Add field users to assetpermission
    - Alter field date_expired on assetpermission
    - Alter field name on assetpermission
    - Remove field asset_groups from assetpermission
    - Alter unique_together for assetpermission (1 constraint(s))
2018-12-05 10:29:16 [signals_handler DEBUG] Receive django ready signal
2018-12-05 10:29:16 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 85, in handle
    executor.loader.check_consistent_history(connection)
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 294, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration audits.0001_initial is applied before its dependency users.0003_auto_20181205_1029 on database 'default'.
2018-12-05 10:29:18 [signals_handler DEBUG] Receive django ready signal
2018-12-05 10:29:18 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 103, in handle
    loader.check_consistent_history(connection)
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 294, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration audits.0001_initial is applied before its dependency users.0003_auto_20181205_1029 on database 'default'.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@cailangnick 
- 从 1.4.x 版本开始 mysql 版本需要大于等于 5.6,mariadb 版本需要大于等于 5.5.6

数据库表结构不完整导致升级失败的, 按如下内容进行处理

.. code-block:: shell

    # 一定要知道自己升级之前的版本, 在升级之前可以通过如下代码进行查询, 记住是升级之前, 也可以通过 web 页面的右下角来查看当前版本信息
    $ cat /opt/jumpserver/apps/__init__.py | grep version
    $ cat /opt/jumpserver/apps/templates/_footer.html | grep Version

    # 备份当前版本数据库, 忽略 django_migrations 表
    $ mysqldump -uroot -p jumpserver --ignore-table=jumpserver.django_migrations > /opt/jumpserver.sql

    # 重命名 Jumpserver 目录
    $ mv /opt/jumpserver /opt/jumpserver_bak

    # 重新 clone 代码
    $ cd /opt
    $ git clone https://github.com/jumpserver/jumpserver.git
    $ cd jumpserver

    # 检出你之前的版本, 比如之前的版本是1.4.0
    $ git checkout 1.4.0  # 1.4.0 表示版本号, 自己手动更换成你当前的版本, 如 1.3.1 则输入 git checkout 1.3.1

    # 依赖安装
    $ source /opt/py3/bin/activate
    $ yum -y install $(cat /opt/jumpserver/requirements/rpm_requirements.txt)
    $ pip install --upgrade pip setuptools
    $ pip install -r /opt/jumpserver/requirements/requirements.txt

    # 重新创建一个数据库
    $ mysql -uroot
    > create database jumpserver01 default charset 'utf8';
    > grant all on jumpserver01.* to 'jumpserver01'@'127.0.0.1' identified by 'weakPassword';
    > flush privileges;
    > quit

    # 修改配置文件
    $ cp /opt/jumpserver_bak/config.py /opt/jumpserver/
    $ vim /opt/jumpserver/config.py
    DB_ENGINE = 'mysql'
    DB_HOST = '127.0.0.1'
    DB_PORT = 3306
    DB_USER = 'jumpserver01'
    DB_PASSWORD = 'weakPassword'
    DB_NAME = 'jumpserver01'

    # 初始化数据库
    $ cd /opt/jumpserver/utils
    $ sh make_migrations.sh

    # 确定初始化没有错误, 把旧的数据库导入
    $ mysql -uroot
    > use jumpserver01;
    > source /opt/jumpserver.sql

    # 启动 jumpserver, 确定没有错误
    $ cd /opt/jumpserver
    $ ./jms start all

    # 打开 web 页面检查是否都正常

    $ 参考升级文档继续升级到最新版本即可

    # 删除原数据库命令
    $ mysql -uroot
    > drop database jumpserver;
    > quit
