### ISSUE TITLE
在[基本配置]中新增[主机名]的需求

### ISSUE THREAD

**Issue by wsnsnsns** [jumpserver/jumpserver#2130]
[简述你的问题]
1.搭建了多台jumpserver
2.在title中无法进行区分
3.在MFA中无法区分

so....希望能增加一个servername,即:主机名

##### 使用版本
Version 1.4.4-2

##### 问题复现步骤
无

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/43594614/49562878-54cd9e80-f958-11e8-805f-611c7b314aee.png)
![default](https://user-images.githubusercontent.com/43594614/49562964-b2fa8180-f958-11e8-9ba4-24cee55a1569.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by vipwangtian** [comment]
#2133 #

**Comment by ibuler** [comment]
merged

**Comment by wsnsnsns** [comment]
棒棒哒....
