### ISSUE TITLE
调用delete api不指定对象删除所有数据

### ISSUE THREAD

**Issue by opsummer** [jumpserver/jumpserver#2131]
[简述你的问题]
调用api不加参数删除所有数据

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.3
##### 问题复现步骤
1. [步骤1]
调用任何api，使用delete的method，如果不加参数，会删除所有数据
如
curl -X DELETE "http://192.168.162.120/api/assets/v1/assets/" -H "accept: application/json" -H "X-CSRFToken: 7pq62678bhHPT9oVq10o6OUEEz17BGQ2eLRgTvLkiq1f8Bhxyo56Gy9MKg8vgmie"
，未指定删除的对象，将删除所有资产。
还没有使用新版，所以不知道是否新版已经不是这样，但是希望能加一下，删除判断一下是否有参数，即使手工调用时会判断是否传参数，但是在页面上，不传参数，执行一把，就GG了。

来自一枚初次使用API，不知道怎么肥死，就已经删了一次库的新手。。。。
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by 191801737** [comment]
这个bug  有办法规避么。。。。

**Comment by huangpeng0817** [comment]
我使用的最新版，调用资产的批量接口，业务删除的时候会全部删除，批量删除上删除指定的不知道咋传值，怎么用都不对。请问你这边是怎么传值的啊。

**Comment by jym503558564** [comment]
感谢提出这个bug,这边会反馈这个问题。请持续关注。

**Comment by Pefeng** [comment]
我也遇到这个问题，想指定资产进行删除，怎么传值都不行。没传值执行了一把，把所有资产全删除了，差点gg了。还好我删除之前备份了数据库

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/commit/dda34cb17aa3ed7a9b0395f08264d19cabaf254d 等待 merge
