### ISSUE TITLE
自己开发的的一些功能， 随便围观~

### ISSUE THREAD

**Issue by skyoo** [jumpserver/jumpserver#2136]
[简述你的问题]
新版Jumpserver更新日志 - 2018-12-06
1. 增加WEB和终端的SSH连接在微信小秘书通知
2. 增加SSH连接的时间显示，(本机-jms-目标)的总时间
3. 增加对非管理员的授权功能项
     *创建授权规则中可见, WEB SSH和SFTP的授权项
     *授权规则详情直观显示规则权限， 可快速更新WEB SSH和SFTP的权限
     *授权规则的体现, 在非管理员界面 
           a)WEB终端和文件管理导航菜单是否可见
           b)没有WEB SSH的权限情况下连接主机的提示
           c)对于文件管理界面中的菜单(上传、下载、新建、重命名、删除)，根据授权规则决定是否可见。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
@1.4.3

##### 具体表现[截图可能会更好些,最好能截全]
![1544416705](https://user-images.githubusercontent.com/456769/49711785-55c63f00-fc7c-11e8-9ada-0052deea75a4.png)
![1544416669](https://user-images.githubusercontent.com/456769/49711795-5fe83d80-fc7c-11e8-8580-432df0fd6075.png)
![1544415593](https://user-images.githubusercontent.com/456769/49711801-67a7e200-fc7c-11e8-969a-d4578f484b86.png)
![1544415863](https://user-images.githubusercontent.com/456769/49711770-3e875180-fc7c-11e8-81da-3efe1d98c770.png)
![1544416017](https://user-images.githubusercontent.com/456769/49711817-77bfc180-fc7c-11e8-9cb2-34e696cab88c.png)
![1544415945](https://user-images.githubusercontent.com/456769/49711821-81e1c000-fc7c-11e8-932e-20d1d6db3085.png)
![1544415785](https://user-images.githubusercontent.com/456769/49711825-860ddd80-fc7c-11e8-8462-acd65cce5c88.png)
![1544415834](https://user-images.githubusercontent.com/456769/49711828-87d7a100-fc7c-11e8-95be-56cde9946290.png)
![qq 20181210124221](https://user-images.githubusercontent.com/456769/49711831-8c03be80-fc7c-11e8-8e0e-2c312f070459.jpg)
![1544416460](https://user-images.githubusercontent.com/456769/49711832-8dcd8200-fc7c-11e8-9177-e8f4e5e5b62a.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
欢迎提 Pull Request
