### ISSUE TITLE
登录资产没有反应且退出jump

### ISSUE THREAD

**Issue by dr0216** [jumpserver/jumpserver#2137]
[简述你的问题]

##### 使用版本

Version 1.4.4-2 GPLv2

##### 问题复现步骤
上周部署新版JUMPSER1.4.4-2，全局开启MFA，开始一天测试MFA通过，并且正常登录。这周一发现通过coco登录的时候，直接输入资产没有反应，并且自动退出jumpserver。
用新版本jumpserver的几个人全都遇到过这个问题。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34674920/49722943-c2533500-fca0-11e8-876b-ae0c8fa63896.png)
尝试登录后，直接回车，显示各资产。
![image](https://user-images.githubusercontent.com/34674920/49723084-08a89400-fca1-11e8-82cb-1e7a11fcc7d9.png)
然后再输入资产ID就能登录了
![image](https://user-images.githubusercontent.com/34674920/49723424-b7e56b00-fca1-11e8-94b9-a98220a9e768.png)

##### 其他
把MFA关了，还是能重现故障。
从coco日志里能看到报错
2018-12-11 13:16:29 [sshd ERROR] Unexpected error occur: request() got an unexpected keyword argument 'user_auth'
2018-12-11 13:18:03 [sshd ERROR] Unexpected error occur: request() got an unexpected keyword argument 'user_auth'

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
