### ISSUE TITLE
支持saltstack

### ISSUE THREAD

**Issue by fmnisme** [jumpserver/jumpserver#214]
有没有考虑把ansilbe做成插件的形式，可以替换成saltstack或者其他的自动化工具，这样应用面会更广。

**Comment by fmnisme** [comment]
如果感兴趣的话我们可以协作下。

**Comment by liuzheng712** [comment]
这是一个很好的想法，暂时团队内精力有限，正在做ansible的工作，其他插件暂时未做考虑

**Comment by ibuler** [comment]
下个版本准备大规模使用ansible, 由于ansible不需要客户端，我们尽可能做的通用些，我们也不排除会在推送用户等上提供saltstack插件api

**Comment by fmnisme** [comment]
我的意思是你们提通用的抽象接口，然后只实现ansbile驱动，其他的驱动例如如saltstack可以由其他人来贡献，这样通用性会更强些，毕竟有很多公司已经有自己的自动化运维工具了。

**Comment by ibuler** [comment]
@yumaojun03 和 @fmnisme 联系一下，聊聊想法

**Comment by zsjohny** [comment]
@ibuler  老广啊，我觉得 ansible 对于初级的自动化 ，其实很好用我个人也比较倾向于salt 因为他的高级功能 发射灯塔啥的 都挺好的 如果有可能的话，我有时间 提一个PR 我们一起研究研究 @fmnisme

**Comment by ibuler** [comment]
如果能提供抽象层最好了，作为引擎，让用户自己选择

**Comment by ibuler** [comment]
刚离职到小米，最近开发时间较少，可以关注一下  https://github.com/jumpserver/jumpserver/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v0.4.0+beta%22 有空帮PR，代码在dev分支

**Comment by ppabc** [comment]
建议通用化，ansbile 其实有很好用的API接口了，也是开源的，呵呵
