### ISSUE TITLE
Windows Server2016 资产连接不上，/config/tomcat8/logs/catalina.out报错java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by LianWilliam** [jumpserver/jumpserver#2144]
[简述你的问题]
Windows Server2016 资产连接不上，/config/tomcat8/logs/catalina.out报错java.lang.NullPointerException: null

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
目前的最新版本v1.4.4 Released

##### 问题复现步骤
1. [步骤1] 按照一步一步安装(CentOS)执行“五. 安装 Windows 支持组件” 安装Guacamole
2. [步骤2] jumpserver中的终端管理也显示正常
![image](https://user-images.githubusercontent.com/35838730/49783891-621eca80-fd56-11e8-9f14-980bd2af0211.png)
3.也检查了密码，能通过远程连接登录Windows Server服务器
![image](https://user-images.githubusercontent.com/35838730/49784003-cb9ed900-fd56-11e8-9913-3fcc340edfab.png)

##### 具体表现[截图可能会更好些,最好能截全]

/config/tomcat8/logs/catalina.out具体报错报错
![image](https://user-images.githubusercontent.com/35838730/49784121-34865100-fd57-11e8-96de-e924d030d549.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@LianWilliam 资产系统平台选择windows（2016）
资产远程设置仅勾选 允许远程连接到此计算机(L)

系统用户设置手动登陆

**Comment by LianWilliam** [comment]
![image](https://user-images.githubusercontent.com/35838730/49840193-677b2400-fded-11e8-94ef-7afb421d2267.png)
