### ISSUE TITLE
升级1.4.5后 测试资产可连接性  不可用卡住无反应，获取资产信息失败 

### ISSUE THREAD

**Issue by onchiao** [jumpserver/jumpserver#2152]
[简述你的问题]
升级1.4.5后 测试资产可连接性  不可用卡住无反应，获取资产信息失败 

##### 使用版本
[1.4.5]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42470468/49856733-91ebd200-fe2b-11e8-8896-584c7d55f3c5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by onchiao** [comment]
Log 报错 [tasks ERROR] 'NoneType' object is not iterable

**Comment by ibuler** [comment]
fixed
