### ISSUE TITLE
希望JumpServer团队增加以下功能：

### ISSUE THREAD

**Issue by shaonblack** [jumpserver/jumpserver#2164]
1.开关禁止单个用户重复登录
2.单独配置审计日志保存天数
3.用户角色新增审计角色（最好是模块化自定义角色权限）
4.权限管理里面添加命令过滤权限，可以自定义过滤一些危险命令

使用版本
Version 1.4.1-2 GPLv2.

**Comment by ibuler** [comment]
1 功能不是很理解，禁止重复登录是指 错误登录吗？
2 功能考虑中
3 功能已开始做
4 功能 1.4.4版本已支持。

**Comment by ibuler** [comment]
2 功能已完成，请更新Master分支

**Comment by ibuler** [comment]
1. 功能只能仅限于 web，因为coco用户可能多个窗口登录
