### ISSUE TITLE
任务列表 404 Page not found

### ISSUE THREAD

**Issue by KennyCHK** [jumpserver/jumpserver#2170]
##### 使用版本
1.4.5
0f61b36

##### 问题复现步骤
根據 安装文档 一步一步安装(CentOS)
![image](https://user-images.githubusercontent.com/45858258/49962623-a37aca00-ff50-11e8-968a-101b1555a4c6.png)

##### 其他
參考此頁
https://github.com/jumpserver/jumpserver/issues/1831
清理 celery
$ source /opt/py3/bin/activate
$ cd /opt/jumpserver/apps
$ celery -A ops purge -f
重启了 jumpserver 的进程, 問題沒改變.

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed

**Comment by ymping** [comment]
按照文档从 1.4.4 升级到 1.4.5 后出现同样情况。
