### ISSUE TITLE
回放

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#2176]
[简述你的问题]
RDP回放的分辨率能否放大, 否则都看不清楚录像回放时屏幕上的文字, 谢谢.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.5

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by HuanMeng0** [comment]
可以按CTRL + 鼠标滚轮 放大。是无损放大的，RDP回放不是视频。

**Comment by bigbird1985** [comment]
好吧....但是解决了我的问题, 谢谢!
