### ISSUE TITLE
可否增加限制用户IP登录资产、用户登录时段限制、实时录像监控三个功能

### ISSUE THREAD

**Issue by muse117** [jumpserver/jumpserver#2177]
[简述你的问题]
可否增加三个功能：
1、限制用户IP登录特定资产，如IP地址：192.168.1.10-192.168.1.20这个段的用户无法登录资产A
2、限制用户登录时段，如星期一的9:00-10:00用户A无法登录。
![_20181102171403](https://user-images.githubusercontent.com/9733486/50041778-33299100-0095-11e9-9937-59baf31ea115.png)

3、实时录像监控

**Comment by awklinux** [comment]
这个在iptables上就可以实现了吧

**Comment by muse117** [comment]
> 这个在iptables上就可以实现了吧

普通用户管理员会配置iptables规则的不多啊

**Comment by jackwang-github** [comment]
> > 这个在iptables上就可以实现了吧
> 
> 普通用户管理员会配置iptables规则的不多啊

那是需要学习

**Comment by jackwang-github** [comment]
JMS的商业版本应该可以支持这些功能。

**Comment by muse117** [comment]
> JMS的商业版本应该可以支持这些功能。

因为jms采用分布式部署，实时监控貌似不太好实现。
