### ISSUE TITLE
1.4.3无法升级至1.4.4

### ISSUE THREAD

**Issue by lu604386020** [jumpserver/jumpserver#2179]
[简述你的问题]
目前版本1.4.3，升级至1.4.4的时候，sh make_migrations.sh报错图1。之前比对检查数据库表结构文件是没问题的。
然后当 数据库表结构不完整处理恢复，又遇到报错图2，但是能正常启动jms
##### 使用版本
1.4.3
##### 问题复现步骤
步骤跟官方文档一致。

##### 具体表现[截图可能会更好些,最好能截全]
图1
![image](https://user-images.githubusercontent.com/22024220/50055072-ba096700-0184-11e9-8e17-4d8118d2bcd5.png)

图2
![image](https://user-images.githubusercontent.com/22024220/50055091-f341d700-0184-11e9-9f8a-9edc9393ac99.png)

**Comment by lu604386020** [comment]
Mysql版本 5.6.41

**Comment by wojiushixiaobai** [comment]
@lu604386020 严格按照文档执行，一定要新clone的代码

**Comment by lu604386020** [comment]
> @lu604386020 严格按照文档执行，一定要新clone的代码

..是新克隆的  严格按照文档执行了。。。所以很难受

**Comment by wojiushixiaobai** [comment]
@lu604386020 还没好？使用第三条是新的数据库？新的数据库为啥会报错？？
