### ISSUE TITLE
sftp服务权限划分需求

### ISSUE THREAD

**Issue by henyufeiyang** [jumpserver/jumpserver#2186]
根据美国404IT审计标准，上线部署的入口应该尽量统一。
针对sftp服务的上传下载能否配置单独的开关？
例如：
哪些用户对哪些机器可以有上传权限，哪些机器可以有下载权限。
或者机器层面统一的禁止上传、禁止下载？

##### 使用版本
1.3.1

**Comment by ibuler** [comment]
已支持
