### ISSUE TITLE
web用户登录审计日志显示不全

### ISSUE THREAD

**Issue by nickHP** [jumpserver/jumpserver#2188]
1.用户登录审计日志
数据库表user_loginlog里面有的登录记录，为什么在web上面无法查看到？web界面上只能看到已存在的账户登录成功/失败记录？
2.审计日志如果不清理的话是否会永久保存？

##### 使用版本
Version 1.4.1-2 GPLv2
![图片](https://s1.ax1x.com/2018/12/17/F0uGw9.png)

**Comment by wojiushixiaobai** [comment]
@nickHP 新版本已经修复，请更新
