### ISSUE TITLE
功能需求，资产管理中删除设备后同步删除推送的系统用户

### ISSUE THREAD

**Issue by ts4649** [jumpserver/jumpserver#219]
在资产管理中删除了一台linux服务器，然后登录被删除的服务器，查看用户文件（/etc/passwd）。
发现推送过的用户还存在，建议考虑删除设备同时，先删除推送的系统用户后再从列表中删除设备。

**Comment by ibuler** [comment]
好的，感谢提的需求

**Comment by ibuler** [comment]
删除系统用户这个以后再考虑，删除用户存在安全性
