### ISSUE TITLE
无法设置 oss 存储位置,提示Error: Account invalid

### ISSUE THREAD

**Issue by shiboyumm** [jumpserver/jumpserver#2193]
[在系统设置-创建录像存储,设置存储类型为 oss 类型时报错]

##### 使用版本
[版本为1.4.4]

##### 问题复现步骤
1. 创建录像存储位置无法创建oss, 提示名称报错
2. 具体日志
- nginx 错误日志: 2018/12/17 20:10:04 [error] 9852#0: *9673 connect() failed (111: Connection refused) while connecting to upstream, client: 10.254.20.60, server: , request: "POST /api/common/v1/terminal/replay-storage/create/ HTTP/1.1", upstream: "http://[::1]:8080/api/common/v1/terminal/replay-storage/create/", host: "10.254.11.90", referrer: "http://10.254.11.90/settings/terminal/replay-storage/create"

- gunicorn.log
127.0.0.1 [17/Dec/2018:20:16:46 +0800] "POST /api/common/v1/terminal/replay-storage/create/ HTTP/1.0" 401 34

3. nginx 代理配置同官网文档相同.

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26832937/50086523-5476b280-0238-11e9-9ccc-93ddaeb1b543.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by shiboyumm** [comment]
修改 nginx 代理配置后,错误日志不再报错,但是页面依然报错 error, nginx 访问日志报404错误

10.254.20.60 - - [18/Dec/2018:15:34:28 +0800] "POST /api/common/v1/terminal/replay-storage/create/ HTTP/1.1" 401 34 "http://10.254.11.90/settings/terminal/replay-storage/create" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" "-"

![image](https://user-images.githubusercontent.com/26832937/50138793-abcd5f00-02da-11e9-80c3-9262ae7b5c97.png)

**Comment by ibuler** [comment]
ACCESS_KEY不正确，无法通过验证

**Comment by shiboyumm** [comment]
> ACCESS_KEY不正确，无法通过验证

已经解决, bucket 没有给权限....
