### ISSUE TITLE
ldap能否支持memberUid或者uniqueMember进行组权限划分

### ISSUE THREAD

**Issue by duanbaihong** [jumpserver/jumpserver#2194]
[简述你的问题]
ldap以否支持memberUid或者uniqueMember进行组权限划分，并且现在也不无进行组进行映射！

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
和 #1585 重复了
