### ISSUE TITLE
能否映射把ldap的sshpublickey映射到jumpserver的sshkey

### ISSUE THREAD

**Issue by duanbaihong** [jumpserver/jumpserver#2195]
[简述你的问题]
能否映射把ldap的sshpublickey映射到jumpserver的sshkey

**Comment by vkill** [comment]
+1

**Comment by nanguawu** [comment]
+1 

建议同时支持系统用户的ssh登陆和ldap验证ssh登陆。

**Comment by duanbaihong** [comment]
在我的项目下面，我fork了一个jumpserver实现了ＬＤＡＰ的。组权限映射，sshkey映射，本地用户优先登陆。并且优化了一些界面上的小问题！可以去试试.

**Comment by nanguawu** [comment]
> 在我的项目下面，我fork了一个jumpserver实现了ＬＤＡＰ的。组权限映射，sshkey映射，本地用户优先登陆。并且优化了一些界面上的小问题！可以去试试.

coco默认使用的system_user，这个项目不调整吗？

**Comment by duanbaihong** [comment]
> > 在我的项目下面，我fork了一个jumpserver实现了ＬＤＡＰ的。组权限映射，sshkey映射，本地用户优先登陆。并且优化了一些界面上的小问题！可以去试试.
> 
> coco默认使用的system_user，这个项目不调整吗？
这个我也已经优化了，coco认证先本地认证，再从ＬＤＡＰ认证。所以改动的就是jumpserver不需要改coco
![image](https://user-images.githubusercontent.com/17972226/50805191-45ad8800-132c-11e9-9282-8a86f32a32a5.png)
