### ISSUE TITLE
jumpserver3.0.1 send  mail error

### ISSUE THREAD

**Issue by xuedihualu** [jumpserver/jumpserver#220]
SMTPException at /juser/user/add/
STARTTLS extension not supported by server.
Request Method:	POST
Request URL:	http://10.1.88.14:8000/juser/user/add/
Django Version:	1.6
Exception Type:	SMTPException
Exception Value:	
STARTTLS extension not supported by server.
Exception Location:	/usr/lib64/python2.7/smtplib.py in starttls, line 643
Python Executable:	/bin/python
Python Version:	2.7.5
Python Path:	
['/data/jumpserver',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib64/python2.7/site-packages/gtk-2.0',
 '/usr/lib/python2.7/site-packages']
Server time:	Fri, 29 Apr 2016 14:19:31 +0800

**Comment by ibuler** [comment]
修改 jumpserver.conf
email_use_tls = False
