### ISSUE TITLE
多组件基于ip_hash的负载均衡问题

### ISSUE THREAD

**Issue by sisco501** [jumpserver/jumpserver#2202]
[简述你的问题]
典型使用场景为：用户集中在有限几个网段，甚至全集中在一个网段
查了下nginx的ip_hash算法只取IPV4的前三位作为参数加入hash函数
因此在此种场景下，ip_hash负载均衡无法发挥应有的作用

在公司内部，即使是使用DHCP，IP地址在一段时间内也是相对固定的
很少会有短时间内频繁变更IP的情况

所以不知道是否有更好的解决方案

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.5-2

##### 问题复现步骤
1. 测试同一网段用户同时打开远程会话，均被分配在了同一后端

##### 其他

[注:] 完成后请关闭 issue

**Comment by duanbaihong** [comment]
nginx的ip_hash应用场景一般是外网的IP

**Comment by sisco501** [comment]
> 
> 
> nginx的ip_hash应用场景一般是外网的IP

是的  所以咨询内网环境应该采取何种方式

**Comment by wojiushixiaobai** [comment]
@sisco501 ip_hash可以解决session问题，其他方式可能会导致无法连接的问题，我找个时间测试下，会尽快给出反馈

**Comment by duanbaihong** [comment]
> @sisco501 ip_hash可以解决session问题，其他方式可能会导致无法连接的问题，我找个时间测试下，会尽快给出反馈

本来就有用到redis，session应该是保存在Redis里的吧！这样就不会有问题！

**Comment by ibuler** [comment]
使用 nginx的 cookie stick 模块吧 http://www.ttlsa.com/nginx/nginx-modules-nginx-sticky-module/
