### ISSUE TITLE
在demo里，点击页面左侧菜单，页面跳转后，左侧菜单状态保持与页面跳转前的状态不变，请问，这是如何实现的？谢谢！

### ISSUE THREAD

**Issue by zhouxinzhe** [jumpserver/jumpserver#221]
在demo里，点击页面左侧菜单，页面跳转后，左侧菜单状态保持与页面跳转前的状态不变，请问，这是如何实现的？谢谢！

**Comment by ibuler** [comment]
其实是变的，因为没有用angular等前端框架，只不过左侧缓存的好，没感觉到变化

**Comment by zhouxinzhe** [comment]
谢谢您的答复，不知是否方便告知左侧缓存是通过什么实现的呢？ 可以在按个文件里看到？ 谢谢~~
