### ISSUE TITLE
在使用ＬＤＡＰ登陆时，把role字段隐射到ldap里的一个字段，和jumpserver 里保持一至时，设置为管理无效

### ISSUE THREAD

**Issue by duanbaihong** [jumpserver/jumpserver#2216]
[简述你的问题]
在使用ＬＤＡＰ登陆时，把role字段隐射到ldap里的一个字段，和jumpserver 里保持一至时，设置为管理无效，应该是保存用户信息是的角色是按ＩＤ来区分，而ldap里没有Id只有名称！

##### 使用版本
[请提供你使用的Jumpserver版本 １4.6]

##### 问题复现步骤
![20181219144109](https://user-images.githubusercontent.com/17972226/50203397-53f72c80-039c-11e9-9302-488be70610f6.png)

![Uploading 20181219144403.png…]()

##### 其他
![Uploading 20181219144403.png…]()

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
role不建议映射，下一步会把role抽出来，用户可以自定义role

**Comment by duanbaihong** [comment]
> 用户可以自定义role

我已经实现了role映射了，ldap里找一个字段定义为Admin 就是管理员，现在主要是，groups映射还存在问题，一直报错，
错误内容如下：

Request Method: | POST
-- | --
http://192.168.1.247:8080/users/login/
2.1
TypeError
Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
/usr/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py in __set__, line 537
/usr/bin/python3.6
3.6.6
['/opt/jumpserver',  '/opt/jumpserver/apps',  '/usr/bin',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/lib/python3.6/site-packages',  '/opt/jumpserver/apps']
星期四, 20 十二月 2018 11:49:02 +0800

**Comment by ibuler** [comment]
映射role意义不大，毕竟没有多少管理员

**Comment by duanbaihong** [comment]
> 映射role意义不大，毕竟没有多少管理员
不是意义不大，想实现在LDAP统计实现用户分组及权限的定义，这样就不需要在JUMPSERVER里再来分配一下用户的权限了，并且这样可以实现用户的权限复用。

**Comment by ibuler** [comment]
同步分组的功能在进行中

**Comment by duanbaihong** [comment]
> 同步分组的功能在进行中

不过，我自己修改了一下源码，已经实现了，我拉了一个clone 改的
![image](https://user-images.githubusercontent.com/17972226/62843470-9800be00-bcec-11e9-840d-5c4efcbe4fec.png)
