### ISSUE TITLE
1.4.6 跳板机登陆时提示输入系统用户的密码

### ISSUE THREAD

**Issue by BackFire** [jumpserver/jumpserver#2218]
[简述你的问题]
跳板机登陆时提示输入系统用户的密码，以前是不需要这个的

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
Opt> emr

选择一个登录:
0 大数据
1 运维
ID> 0

hadoop's password: 

##### 其他

[注:] 完成后请关闭 issue

**Comment by BackFire** [comment]
coco通过sdk去调用jumpserver的api出现404。这个接口通过jumpserver的web域名调用返回200

> 2018-12-19 16:34:03 [log WARNING] Not Found: //api/assets/v1/system-user/b7a7d29b-fbd3-481e-bff9-ee99f6df8832/auth-info/
127.0.0.1 [19/Dec/2018:16:34:03 +0800] "GET //api/assets/v1/system-user/b7a7d29b-fbd3-481e-bff9-ee99f6df8832/auth-info/ HTTP/1.1" 404 5082

**Comment by ibuler** [comment]
或许你的 CORE_HOST应该去掉最后的 '/'
CORE_HOST = 'http://xxx/' => CORE_HOST = 'http://xxxxxx'

**Comment by BackFire** [comment]
全新重装后未见该问题
