### ISSUE TITLE
按照wiki文档安装上去，运行一段时间后很慢，点开页面一直在等待响应。重启后就正常，过一段时间又会这样子。确认机器的负载不高。

### ISSUE THREAD

**Issue by wanygan83** [jumpserver/jumpserver#222]

**Comment by ibuler** [comment]
可以查看一下log，确认慢在哪

**Comment by wanygan83** [comment]
2016-05-07 17:07:03,261 - user_api.py - DEBUG - 生成ssh key， 并设置authorized_keys
最后一条日志是这个。并没有什么错误？

**Comment by wanygan83** [comment]
然后所有的页面都不开，怀疑是server是不是哪儿卡住了，我用的是centos 6.5的操作系统，Python 2.6.6

**Comment by evandeng2009** [comment]
表示同样问题

**Comment by ibuler** [comment]
至今没遇到这种情况，请研究一下，确认是哪的问题

**Comment by wanygan83** [comment]
@ibuler ,你们用的python的web server是哪个？

**Comment by stanhui** [comment]
我也遇到了，不过我是点邮件相关才会触发。其它正常

**Comment by gogogonnn** [comment]
应该是邮件没有配置好，

**Comment by deamwork** [comment]
#282 看看是不是邮件的问题，我重新配置后就好了
