### ISSUE TITLE
周期性任务相关的表适当建立索引或者定期清理不必要数据, 量大后容易导致慢SQL卡死

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#2222]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.3.1 
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

- ops_celerytask
- ops_adhoc
.....
等周期性任务相关的表适当建立索引或者周期性清理无用数据,  示例截图里的表用到的排序字段也是没有索引的...
现在达到ops+adhoc大概100多万条数据, 每次查询返回基本几十秒了..

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/11460661/50210794-04236000-03b2-11e9-870a-86eae4818017.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
另外ops_celerytask的任务如果阻塞会一直waiting, 导致后续任务卡住, 建议定期清理下卡在waiting状态的任务 @ibuler 

PS:`ops_celerytask`的status也没有索引

**Comment by ibuler** [comment]
已merge，并增加定时任务清理adhoc和history
