### ISSUE TITLE
任务详情的输出选项卡URL路径错误

### ISSUE THREAD

**Issue by ymping** [jumpserver/jumpserver#2229]
[简述你的问题]
在 仪表盘 -->  作业中心 -->  任务详情 页面下
处于 “任务详情” 选项卡下无法打开 “输出” 选项卡
处于 “任务各版本”，“执行历史” 选项卡下，“输出”选项卡成功打开

##### 使用版本
Version 1.4.6-2 GPLv2.

##### 问题复现步骤
1. 打开页面 仪表盘 -->  作业中心 -->  任务详情，处于 “任务详情” 选项卡
2. 点击 “输出” 选项卡无法打开

##### 具体表现[截图可能会更好些,最好能截全]
![bug](https://user-images.githubusercontent.com/18373128/50260552-69736180-0443-11e9-9410-796c2e166f17.png)
![ok](https://user-images.githubusercontent.com/18373128/50260554-6b3d2500-0443-11e9-878f-f8ff9dde9e4f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复，merge到了master
