### ISSUE TITLE
使用主机id不能登陆主机，使用ip或者主机名可以

### ISSUE THREAD

**Issue by awklinux** [jumpserver/jumpserver#2232]
[简述你的问题]
使用1.4.6输入id不能登陆主机，使用主机名或者ip地址可以

##### 使用版本
的Jumpserver版本 1.4.6 

##### 问题复现步骤
1. 不支持id登陆主机

**Comment by ibuler** [comment]
已修复，更新coco

**Comment by awklinux** [comment]
果然好了，神速

**Comment by awklinux** [comment]
不能通过备注的关键字登陆，之前使用1.4.3的时候备注了test关键，登陆的时候也可以输入test登陆
