### ISSUE TITLE
请问源码中org应用如何使用呢？

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#2234]
请问源码中org应用的功能是什么呢？
![image](https://user-images.githubusercontent.com/20556236/50272308-4b712580-0472-11e9-842d-8829a02b6b11.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@Sandra299 参考faq文档，或者购买商业版

**Comment by hzbd** [comment]
@Sandra299 
https://jumpserver.readthedocs.io/zh/docs/faq_org.html
开源版本好像只能命令行操作，自己加个管理页面
