### ISSUE TITLE
升级时 git fetch失败

### ISSUE THREAD

**Issue by shuish0071** [jumpserver/jumpserver#2235]
[简述你的问题]
大家好，我按照更新升级文档从1.4.4版本升级到最新版时，git fetch失败
【本人对于git不是很熟】

##### 使用版本 
1.4.4

##### 问题复现步骤
1. 按照升级文档从1.4.4升级，在git fetch时提示：
fatal: Not a git repository (or any of the parent directories): .git

我试过：git fetch https://github.com/jumpserver/jumpserver
但是后续的【git checkout master】也报错，更没有【config_example.py】
大家有什么建议吗？

**Comment by wojiushixiaobai** [comment]
@shuish0071 原代码非git clone获取，请备份数据库表结构后，重新使用git clone方式进行还原

**Comment by shuish0071** [comment]
其实jumpserver这个文件夹都是可替换的吧？我这里试试
感谢回答@wojiushixiaobai
