### ISSUE TITLE
限时授权后，如果用户没有退出session，则可以一直操作，能否自动切断连接？

### ISSUE THREAD

**Issue by apple0407** [jumpserver/jumpserver#2243]
[简述你的问题]
目前授权规则里面有时限设置，但是当用户已经登陆到web terminal后，除非超时或者刷新页面，否则是可以一直操作的，这样还是存在一定的安全问题。
能否有一个机制，在用户的授权时限到达后，直接切断连接？
还有一个问题，不能对windows的RDP在线会话进行切断，只支持ssh的切断。

##### 使用版本
1.4.5

**Comment by wojiushixiaobai** [comment]
@apple0407 会话过期时间自己修改下

**Comment by apple0407** [comment]
修改了会话过期时间后，如果用户持续在操作，间隔没有达到会话时间，则还是可以一直操作的。
我是希望能达到授权时间到了，直接切断用户连接，而不管用户会话是否过期，能实现吗？

**Comment by ibuler** [comment]
并不能
