### ISSUE TITLE
选择主机直接右键，然后选择file manager,标题栏消失了

### ISSUE THREAD

**Issue by zishinan** [jumpserver/jumpserver#2245]
[简述你的问题]
在主机连接页面
选择主机直接右键，然后选择file manager,标题栏没了

##### 使用版本
最新版本

##### 问题复现步骤
1. 选择主机直接右键
2. 选择file manager

##### 具体表现[截图可能会更好些,最好能截全]
标题栏没了

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
升级到1.4.6
