### ISSUE TITLE
使用docker下载最新版本Jump后登陆出现Server Error (500)报错

### ISSUE THREAD

**Issue by bruce-zu** [jumpserver/jumpserver#2255]
[简述你的问题]
采用docker安装1.0.0版本Jumpserver，期间使用正常，重新下载最新版本jump用docker安装后，登陆出现server Erroor(500)

##### 使用版本
[请提供你使用的Jumpserver版本 1.0.0-最新版本

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bruce-zu 未复现，请详细说明情况，并附上log

**Comment by wojiushixiaobai** [comment]
@bruce-zu @or0or1 发一下镜像的地址
