### ISSUE TITLE
SFTP手动登陆没有上传下载权限

### ISSUE THREAD

**Issue by vdministrator** [jumpserver/jumpserver#2259]
[简述你的问题]
HI，我部署了一个JUMPSERVER的测试环境，通过WEB界面使用SFTP时（手动登陆），可以正常显示登陆进去，但是无法创建文件，无法上传，也无法下载。我查阅文档说要自动登陆才可以，我也尝试了系统用户自动登陆，确实可以，但是我想知道如何才能在手动登陆的情况下获得SFTP的上传下载权限？因为基本上用户名密码都是用户手工输入，我没有密码。
请问有什么办法可以解决这个问题 ？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.6-2 GPLv2.
##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/12219743/50389361-668ab080-0764-11e9-9661-eec1237dc771.png)
![image](https://user-images.githubusercontent.com/12219743/50389382-9c2f9980-0764-11e9-82f7-e45208227ea4.png)

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by vdministrator** [comment]
Hi,或者有没有办法，可以让我在连接WEB的SFTP时，让我手动输入系统用户名或密码 ？

**Comment by ibuler** [comment]
还不能

**Comment by ibuler** [comment]
现在连接提供了复用功能，web ssh登陆后，sftp可以直接连接
