### ISSUE TITLE
Docker的磁盘存储空间满了，是否可以清理里面的东西?

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#2260]
[简述你的问题]
Docker的磁盘存储空间满了，是否可以清理里面的东西?

##### 使用版本
1.3.2.2

##### 问题复现步骤
查看磁盘空间，发现是docker存储空间满了，
不清楚这个文件夹里面存储的是什么数据。

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/20255706/50389613-52947e00-0767-11e9-94e5-6cd9edd3f9e6.png)
![2](https://user-images.githubusercontent.com/20255706/50389615-558f6e80-0767-11e9-9fec-e591e772c1f2.png)

##### 其他
图2是df -hT看到的。
感谢回复。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 手动进入容器删除下，record是录像，drive是共享文件，都可以清理
建议在无人登陆资产时清理，防止录像未上传

**Comment by ChampionWolf** [comment]
@wojiushixiaobai  感谢回复。
我想请问，录像的位置不应该是在/opt/jumpserver/data/media下么，为何record下也会存放录像文件呢？感谢解答。

**Comment by wojiushixiaobai** [comment]
@ChampionWolf rdp和vnc协议的资产录像是由guacamole完成的，用户操作完成后录像结束，guacamole会把录像上传给jumpserver

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 嗯，你可以在容器里面手动加个计划任务自动处理下，后面我们这边会加入解决方案，麻烦了

**Comment by ChampionWolf** [comment]
@wojiushixiaobai  感谢！
