### ISSUE TITLE
jquery安全漏洞

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2263]
Jumpserver 1.4.0存在安全漏洞，建议能把jquery的版本升级到2.2.4。
![jq](https://user-images.githubusercontent.com/15603111/50395574-fd289300-079f-11e9-8798-6939c01632af.png)

**Comment by ibuler** [comment]
已修复，等待merge
https://github.com/jumpserver/jumpserver/commit/2693d68e33d6c2e801c591f6305e5d007adc8d62
