### ISSUE TITLE
Guacamole剪贴板不能使用

### ISSUE THREAD

**Issue by 7cristiano** [jumpserver/jumpserver#2265]
[简述你的问题]

##### 使用版本
1.4.4

##### 问题复现步骤
升级到1.4.4版本后，非docker部署的Guacamole连接windows资产后剪贴板失效
需要改用docker部署Guacamole的剪贴板才正常

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@7cristiano 请更新到最新版本，1.4.4升级文档只保留了jumpserver升级说明，其他的文档已经去掉。
