### ISSUE TITLE
删除日志文件jumpserver.log中的密码

### ISSUE THREAD

**Issue by evandeng2009** [jumpserver/jumpserver#227]
当前日志文件中保存有完整的主机名，IP地址，甚至系统用户名及密码，全部明文。建议删除至少密码。

/_更新_/
ok,更改配置文件base中的日志级别为warning，看看之后的效果再说

**Comment by ibuler** [comment]
修改日志模式可以不显示密码的

**Comment by jiaxiangkong** [comment]
修改jumpserver.conf 中log=warning
