### ISSUE TITLE
用户、用户组『备注』中文显示为?????（乱码）

### ISSUE THREAD

**Issue by morningyi** [jumpserver/jumpserver#2277]
[简述你的问题]
在用户、用户组中的『备注』中设置中文，保存后显示为?????（乱码）

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6-2

##### 问题复现步骤
1.在用户、用户组中的『备注』中设置中文
2. 保存后显示为?????（乱码）

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/807167/50431916-4a744400-0909-11e9-838e-4fe45bebb03d.png)

![image](https://user-images.githubusercontent.com/807167/50431938-89a29500-0909-11e9-8db0-bf02381a3015.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
数据库编码是不是 utf8
