### ISSUE TITLE
jumpserver上传文件失败

### ISSUE THREAD

**Issue by vipsql** [jumpserver/jumpserver#2280]
[问题]
jumpserver上传文件失败

##### 使用版本
1.4.6

##### 问题复现步骤
1. 网络状况良好的情况,上传大概200MB大小的文件频繁失败
2.注: nginx已修改为最大上传大小为512MB

##### 具体表现[截图可能会更好些,最好能截全]
无效的服务端响应
服务器返回的数据不符合JSON格式

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
可更新一下版本，如还有其它问题，可重新打开issues
