### ISSUE TITLE
Linux 服务器不能使用lrzsz 上传下载文件

### ISSUE THREAD

**Issue by xjjj064** [jumpserver/jumpserver#2282]
Linux 服务器不能使用lrzsz 上传下载文件，通过web统一管理之后发现lrzsz 命令上传下载没什么用了，平时用这个命令用习惯了，是我不会用还是jumpserver 的web 管理界面不支持呢？

**Comment by hubeixulu** [comment]
web管理界面不支持这两个命令

**Comment by ibuler** [comment]
不支持
