### ISSUE TITLE
 创建命令存储，选择elasticsearch提交时出现Error: Account invalid

### ISSUE THREAD

**Issue by gujiwork** [jumpserver/jumpserver#2285]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.5  docker环境部署
##### 问题复现步骤
1. [步骤1] 
 系统设置 -> 终端设置 -> 创建命令存储，选择elasticsearch提交时出现Error: Account invalid

2. [步骤2]
 系统设置 -> 终端设置-->创建录像存储,  选择OSS提交时出现Error: Account invalid

##### 其他
1、希望加个新功能，添加elasticsearch能否支持添加用户的密码认证功能，因为elastic是带认证的

**Comment by gujiwork** [comment]
同时在命令过滤中新增的命令不会实时生效，如果禁止某个命令需要客户端重新断开在连接才生效，希望能加个实时推送功能

**Comment by wojiushixiaobai** [comment]
@gujiwork 应该不需要重新登录，刷新页面就可以，但是这个建议蛮好。

**Comment by ibuler** [comment]
需要重新登录资产

**Comment by bubbleatgit** [comment]
我也遇到这样的问题了，不知道楼主怎么解决的？
![image](https://user-images.githubusercontent.com/7858776/79406959-ed534480-7fca-11ea-8602-73d6e1e40bed.png)
