### ISSUE TITLE
同一个版本，迁移的时候，登录时报504错误

### ISSUE THREAD

**Issue by zhangiicc** [jumpserver/jumpserver#2289]
[简述你的问题]

##### Jumpserver版本 1.4.3   
两台机器的版本是一样的

##### 问题复现步骤
1. 我要把A机器的jump server迁移到B机器上，B机器我预装好的可以登录用admin/admin登录没有问题

2. 再A机器上执行
mysqldump -uroot -p jumpserver --ignore-table=jumpserver.django_migrations > /opt/jumpserver.sql

3.把jumpserver.sql复制到B机器上,再B机器上执行一下命令
$ mysql -uroot
> use jumpserver;
> source /opt/jumpserver.sql;
> quit

cd /opt/jumpserver
./jms restart all -d

登录网站输入账号密码然后报504错误

**Comment by RaynorAZ** [comment]
504。。。看下nginx配置呢

**Comment by jym503558564** [comment]
问题是否还存在？
迁移后，nginx配置是否正确？

**Comment by jym503558564** [comment]
检查确认nginx配置无误，如还有其它问题，可重新打开issues
