### ISSUE TITLE
网域网关无法通过端口映射方式连接服务器

### ISSUE THREAD

**Issue by hubeixulu** [jumpserver/jumpserver#2290]
[简述你的问题]
我们在IDC机房有一批机器需要通过网域网关的方式连接，IDC里面用作网关的机器ssh端口是映射成别的端口来访问的，采用ssh客户端和在jumpserver机器上通过ssh命令都可以连接这台机器，但是添加这台机器为网域网关测试就不通过，密码没有使用特殊字符

##### 使用版本
1.4.6

##### 问题复现步骤
1. 点击网域列表
2. 创建网域
3. 创建网关，把IP和映射出来的ssh端口填上去，点击测试连接，会出现连接失败

jumpserver.log报错信息如下
![image](https://user-images.githubusercontent.com/20060019/50510496-e39b8a00-0ac4-11e9-8ebe-e4fac9a660ea.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hubeixulu 不影响实际使用，后续会优化测试的流程

**Comment by hubeixulu** [comment]
@wojiushixiaobai 就是说网关测试不通过，也可以关联资产而且正常使用吗

**Comment by wojiushixiaobai** [comment]
@hubeixulu 是的，测试不通过，只是代码的测试流程有问题，不影响实际使用
确保你的设置是正确的，不会影响到你实际使用

**Comment by hubeixulu** [comment]
@wojiushixiaobai 好像不行啊，提示网关连接失败
![image](https://user-images.githubusercontent.com/20060019/50586898-87ff4100-0eb6-11e9-8ed7-52e5ef6dec3b.png)

**Comment by wojiushixiaobai** [comment]
@hubeixulu 确定输入的信息无误，功能是可以正常使用的。

**Comment by xuhuihihi** [comment]
models文件夹中的domain.py中81行附近，修改'127.0.0.1'为self.ip，部分代码如下：
sock = proxy.get_transport().open_channel(
            'direct-tcpip', (**_self.ip_**, self.port), ('127.0.0.1', 0)
        )

**Comment by ibuler** [comment]
已解决
