### ISSUE TITLE
jumserver能否自动添加资产

### ISSUE THREAD

**Issue by FrelDX** [jumpserver/jumpserver#2291]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by KennyCHK** [comment]
有 API可用啊，你是要如何自动呢？

**Comment by jym503558564** [comment]
可否具体描述一下需求，需要如何自动？
