### ISSUE TITLE
jumpserver redis存储为空

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2293]
[简述你的问题]
发现Jumpserver使用的redis并没有数据流入

##### 使用版本
1.4.4

##### 问题复现步骤
在对应的redis中查询keys，发现keys列表为空

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/42203736/50535972-810cc180-0b8a-11e9-964f-cacb4d2f309f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/50580297-bca7d400-0e87-11e9-9de4-2c06cb949916.png)
@RaynorAZ 用法如图

**Comment by RaynorAZ** [comment]
> ![image](https://user-images.githubusercontent.com/24326988/50580297-bca7d400-0e87-11e9-9de4-2c06cb949916.png)
> @RaynorAZ 用法如图

OK多谢。因为我看我这边redis基本没有消耗。多谢指导
