### ISSUE TITLE
AmazonLinux 编译安装 guacamole 服务时报错

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#2294]
[简述你的问题]
AmazonLinux 编译安装 guacamole 服务时报错

##### 使用版本
最新版

##### 问题复现步骤
./configure --with-init-dir=/etc/init.d
![config](https://user-images.githubusercontent.com/20255706/50579948-e01d4f80-0e84-11e9-8257-a5f62a36ab50.png)
make
![1](https://user-images.githubusercontent.com/20255706/50579952-e4e20380-0e84-11e9-99d8-1cddf3cb15ce.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 请使用docker镜像

**Comment by ChampionWolf** [comment]
OK
