### ISSUE TITLE
批量命令执行在输出中文

### ISSUE THREAD

**Issue by 932340583** [jumpserver/jumpserver#2295]
[简述你的问题]
批量执行命令的功能在一开始输出中文，公司里有外国人，所以这里之后可不可以改成英文？其它地方都正常显示英文

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. [步骤1] 使用管理员身份进去用户页面，点击批量执行命令功能，输出提示为中文，当前页面已经设置成英文了，coco的配置也修改成en了

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/17899509/50581527-79ecf880-0e95-11e9-9a23-1b5fd1cfce2b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
已实现，请更新版本进行测试
![image](https://user-images.githubusercontent.com/40739051/58934632-9de29c00-879d-11e9-8a0a-566cf5470157.png)
