### ISSUE TITLE
源码无法在pycharm进行debug调试

### ISSUE THREAD

**Issue by hwx524866** [jumpserver/jumpserver#2299]
[简述你的问题]
源码下载后，无法在pycharm进行debug调试

##### 使用版本
[请提供你使用的Jumpserver版本 1.0.0 注: 0.3.x不再提供支持]
版本 1.0.0 
##### 问题复现步骤
1. [步骤1]
将工程导入pycharm，设置django运行，但是无法进行debug调试
![image](https://user-images.githubusercontent.com/41911091/50623054-20e09b80-0f4d-11e9-99d7-0024143b6de8.png)
这个无法运行
2. [步骤2]
![image](https://user-images.githubusercontent.com/41911091/50623064-38b81f80-0f4d-11e9-9b01-98f65d733d7f.png)
这个可以运行，但无法调试

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
1.在需要调试的地方打断点
2.debug模式运行项目
![image](https://user-images.githubusercontent.com/40739051/58934366-d8980480-879c-11e9-9510-198be1ccbff5.png)

**Comment by LeeYubo** [comment]
加上断点，以debug模式启动也是不能调试的
我觉着是因为在启动web服务的时候是以子进程的形式启动的，已经脱离了pycharm父进程的管理
p = subprocess.Popen(cmd, stdout=sys.stdout, stderr=sys.stderr, cwd=APPS_DIR)

**Comment by LeeYubo** [comment]
@jym503558564 
加上断点，以debug模式启动也是不能调试的
我觉着是因为在启动web服务的时候是以子进程的形式启动的，已经脱离了pycharm父进程的管理
p = subprocess.Popen(cmd, stdout=sys.stdout, stderr=sys.stderr, cwd=APPS_DIR)

**Comment by anjia0532** [comment]
[036-win10搭建python的linux开发环境(pycharm+vagrant+virtualbox)](https://juejin.im/post/5d3a55ece51d454f71439dd2)
