### ISSUE TITLE
LDAP AD配置，连接失败

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#2304]
[简述你的问题]

##### 问题复现步骤
1. 在后台使用ldapsearch 命令，相同参数是可以搜索匹配到AD用户

2. LDAP配置界面从OU组死活匹配 不到用户（排除大小写格式问题）

<img width="1920" alt="screen shot 2019-01-03 at 5 50 16 pm 2" src="https://user-images.githubusercontent.com/27417058/50632279-4f2c9e00-0f82-11e9-9667-dda91f9d3edc.png">

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@NeilyoSH 勾选使用ldap认证，确定过滤器正确

**Comment by pengfei2018** [comment]
@NeilyoSH  请问您的问题解决了吗？我也是这个问题。

**Comment by jym503558564** [comment]
问题是否解决了？

**Comment by jym503558564** [comment]
可更新版本，再进行测试，问题是否还会复现？如有其它问题，可重新打开issues
