### ISSUE TITLE
docker  jms_guacamole中创建录像文件失败

### ISSUE THREAD

**Issue by shuish0071** [jumpserver/jumpserver#2305]
[简述你的问题]
点击离线会话，提示“没找到录像文件”，查看docker jms_guacamole中的/config/tomcat8/logs/catalina.2019-01-03.log
发现如下报错：

03-Jan-2019 17:54:41.411 警告 [http-nio-8081-exec-3] com.sun.jersey.spi.container.servlet.WebComponent.filterFormParameters A servlet request, to the URI http://10.252.90.84/api/session/ext/jumpserver/asset/add?user_id=5d18bdb7-2ffa-48a9-b617-0eb9b1ed402a&asset_id=bbebf930-92d4-4a46-9406-981f70bdce7d&system_user_id=f5b5f19e-20d1-4896-bb75-ee97d25c282c&token=0F3332CB56F306F6BA3D1D9A92F0A6EEA491C75852BAD34526E27BA6A9346737, contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
03-Jan-2019 17:55:01.555 警告 [http-nio-8081-exec-4] com.sun.jersey.spi.container.servlet.WebComponent.filterFormParameters A servlet request, to the URI http://10.252.90.84/api/session/ext/jumpserver/asset/add?user_id=5d18bdb7-2ffa-48a9-b617-0eb9b1ed402a&asset_id=03be8ec8-1664-40b8-8adb-7a622eab4685&system_user_id=f5b5f19e-20d1-4896-bb75-ee97d25c282c&token=0F3332CB56F306F6BA3D1D9A92F0A6EEA491C75852BAD34526E27BA6A9346737, contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
03-Jan-2019 17:58:20.443 警告 [http-nio-8081-exec-1] com.sun.jersey.spi.container.servlet.WebComponent.filterFormParameters A servlet request, to the URI http://10.252.90.84/api/session/ext/jumpserver/asset/add?user_id=5d18bdb7-2ffa-48a9-b617-0eb9b1ed402a&asset_id=bbebf930-92d4-4a46-9406-981f70bdce7d&system_user_id=f5b5f19e-20d1-4896-bb75-ee97d25c282c&token=0F3332CB56F306F6BA3D1D9A92F0A6EEA491C75852BAD34526E27BA6A9346737, contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.

##### 使用版本
1.4.6-2

##### 问题复现步骤
1. 偶发现象，目前测试还可以
2. 顺便问下记录离线会话的是数据库哪张表，我想把不能看的录像在网页上去掉
##### 具体表现[截图可能会更好些,最好能截全]

![default](https://user-images.githubusercontent.com/46020325/50670177-bee36d00-1004-11e9-85cb-3712b2690ba1.png)
![default](https://user-images.githubusercontent.com/46020325/50670188-cefb4c80-1004-11e9-8b55-4e413722a457.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by shuish0071** [comment]
历史记录表找到了【terminal_session】，希望有人指点下报错信息

**Comment by ibuler** [comment]
可能是录像没有上传成功

**Comment by abcdefg2019** [comment]
我有台服务器也是同样的问题，但是其他服务器是正常的。

**Comment by jym503558564** [comment]
现问题是否已解决？
