### ISSUE TITLE
SSH密码登录无法关闭, 请关注！！！

### ISSUE THREAD

**Issue by skyoo** [jumpserver/jumpserver#2306]
[简述你的问题]

配置文件里已经设置
PASSWORD_AUTH = False

还是能正常登录。。。
导致一直被hacker 尝试登录

为什么 Loading config from server 中的PASSWORD_AUTH = True?

![image](https://user-images.githubusercontent.com/456769/50672148-4b942800-1011-11e9-8f44-5f7f90822017.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by skyoo** [comment]
能解决一下这个问题吗？ 老是被尝试密码登录感觉很不安全啊。

**Comment by ibuler** [comment]
哪个版本呢？ coco启动后必须看到的是 AUTH_PASSWORD: false

**Comment by skyoo** [comment]
> 哪个版本呢？ coco启动后必须看到的是 AUTH_PASSWORD: false

1.4.7-2

**Comment by ibuler** [comment]
fixed
