### ISSUE TITLE
批处理命令功能中，ping命令使用会一直Pending

### ISSUE THREAD

**Issue by rockpanda** [jumpserver/jumpserver#2309]
[简述你的问题]
批处理命令功能中，ping命令使用会一直Pending...,应是因为ping在linux 中会一直ping下去，但在ansible是不会一直ping，会限制其请求包。

##### 使用版本
[Jumpserver版本 1.4.6]

##### 问题复现步骤
1. 选择任意服务器执行 ping baidu.com  命令
2. 执行将会一直Pending...等待

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/42989547/50680777-e4dc3200-1043-11e9-8f86-9000002d2eb1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ping命令不会结束，所以不会有结果
