### ISSUE TITLE
jumpserver与ldap集成出现ldap用户第二次无法登陆

### ISSUE THREAD

**Issue by cuizhiyang** [jumpserver/jumpserver#2310]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.6-2 
##### 问题复现步骤
1. [步骤1]与ldap集成 可以匹配到用户test,使用匹配到的用户test第一次去登录jumpserver可以正常登录.
注销用户后重新登录出现报错
2. [步骤2]用管理员账户登录jumpserver,查看用户列表后,发现存在test用户,删除test用户后,用test再次登录可以正常登录.同样注销后再次登录出现报错.

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/37775902/50681396-54ebb780-1046-11e9-9729-57732547f5c2.png)
![image](https://user-images.githubusercontent.com/37775902/50681408-5f0db600-1046-11e9-948a-7533d0b22566.png)
![image](https://user-images.githubusercontent.com/37775902/50681431-7351b300-1046-11e9-8f6b-d8b0458071b0.png)

#
##### 其他

[注:] 完成后请关闭 issue

**Comment by cuizhiyang** [comment]
![image](https://user-images.githubusercontent.com/37775902/50682205-11467d00-1049-11e9-82f3-22a4e25360d1.png)

**Comment by cuizhiyang** [comment]
请问你实验环境的版本是多少，ldap上的配置方式可否发送下，我尝试进行对比，非常感谢

**Comment by wojiushixiaobai** [comment]
@cuizhiyang ldap文档里面就是

**Comment by dbayangzhengyu** [comment]
请问这个问题解决了吗？我Archery集成 LDAP，也是碰到第二次登录报错的问题。我擦
