### ISSUE TITLE
vnc 连接出错

### ISSUE THREAD

**Issue by xiongchuanyang** [jumpserver/jumpserver#2313]
[简述你的问题]
连接vnc资产报错

##### 使用版本
1.4.6

##### 问题复现步骤
1.创建vnc资产通过vnc连接windows
2. 通过终端连接提示无法连接服务器

##### 具体表现[截图可能会更好些,最好能截全]
错误截图：/var/log/syslog错误日志
![image](https://user-images.githubusercontent.com/38678481/50687996-7789ca80-105e-11e9-9bb7-1ae74a93627b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiongchuanyang 通过源码安装请检查设置无误，确定guacamole的组件都是最新

**Comment by ibuler** [comment]
应该是vnc安全协议

**Comment by jym503558564** [comment]
问题是否还存在，可更新到最新版本，各组件保持一致。如有其它问题，可重新打开issues
