### ISSUE TITLE
jumpserver连接被管理机器环境变量写死了吗

### ISSUE THREAD

**Issue by ntboot1** [jumpserver/jumpserver#2318]
[简述你的问题]
jumpserver连接被管理机器环境变量写死了吗

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.4
##### 问题复现步骤
有coreos系统需要管理，coreos系统的python环境默认不是装在/usr/bin下

##### 具体表现[截图可能会更好些,最好能截全]
![4bae9636-93cb-4a92-b0bb-9c8434e132a1](https://user-images.githubusercontent.com/28977355/50754142-9de27c80-128f-11e9-9d95-f2868e91120f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by HuanMeng0** [comment]
ln -s /yourcoreos/path/python /usr/bin/python

**Comment by ntboot1** [comment]
> ln -s /yourcoreos/path/python /usr/bin/python

coreos系统下/usr/bin 目录为只读

**Comment by liuzheng** [comment]
@ntboot1  
CoreOS 这个问题是这样的，Ansible 默认目录是 /usr/bin/python ，如果需要得自己装 Python 版本，*并且* 指定 `ansible_python_interpreter`
官方链接：<https://coreos.com/blog/managing-coreos-with-ansible.html>
中文：<https://www.oschina.net/translate/managing-coreos-with-ansible>
Jumpserve r暂时没有修改 `ansible_python_interpreter` 的方法，你可以先自己尝试一下

CoreOS 个人认为不需要做也不应该做自动化的事情，应该由容器平台去纳管。 CoreOS 的使用应该就仅仅定义好 cloud-config ，然后交给容器平台，容器平台去纳管整个系统的生命周期。当然，Jumpserver 也在努力和容器平台进行集成。
