### ISSUE TITLE
api 获取token

### ISSUE THREAD

**Issue by 191801737** [jumpserver/jumpserver#2319]
[简述你的问题]
参考文档 想要获取token , otp_code 不知怎么获取。
# 如果开启了 MFA, 则返回的是 seed, 需要携带 seed 和 otp_code 再次提交一次才能获取到 token

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6

已经使用 
curl -X POST -H 'Content-Type: application/json' -d '{"username": "admin", "password": "admin"}' http://localhost/api/users/v1/auth/
获取了 seed 

不知道怎么获取otp_code

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@191801737 opt_code是动态密码，6位数

**Comment by 191801737** [comment]
@wojiushixiaobai 用代码调用 jumpsever的接口 这个动态码该如何获取。登陆WEB的时候 可以开打谷歌验证器查看  用代码调用的话 该怎么弄呢？

**Comment by wojiushixiaobai** [comment]
@191801737 网上有解决方案，请自己参照

**Comment by xieyt9** [comment]
请问解决了吗，我必须强制启用MFA，如果给用户强制启用，系统设置那不开启的话，用户是可以禁用MFA的，所以必须强制启用。但是我还需要api自动添加、自动删除跳板机，请问该如何实现

**Comment by miaoyb** [comment]
@xieyt9 修改/jumpserver/apps/users/api/auth.py第72行，
`if not user.otp_enabled:`
改为`if not user.otp_enabled or username == '用户名':`

**Comment by ibuler** [comment]
可以生成个永久 private_token， 这样就避免认证了，生成方法：

```
$ python manage.py shell
>>> from users.models import User
>>> u = User.objects.get(username='admin')
>>> u.create_private_token()
xxxxxxxxxxxxxxxxxxxxxxxxx

$ curl -H 'Authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxx' -H "Content-Type:application/json" http://localhost/api/users/v1/users/
```
