### ISSUE TITLE
请问如何让jumpserver支持rsync呢？

### ISSUE THREAD

**Issue by codeunsolved** [jumpserver/jumpserver#2325]
[简述你的问题]
请问如何让jumpserver支持rsync呢？比如：
`rsync -azv -P [本地文件路径] [user@jumpserver_ip:服务器文件路径]`

##### 使用版本
1.4.4-2

**Comment by skyoo** [comment]
应该直接修改rsync源码
rsync -azv -P [本地文件路径] [user@jumpserver_ip#system_user@target_ip:服务器文件路径]

**Comment by ibuler** [comment]
暂时不支持
