### ISSUE TITLE
资产树节点显示错误

### ISSUE THREAD

**Issue by laiyh31** [jumpserver/jumpserver#2326]
[简述你的问题]
多次移动资产树上节点后，节点显示错误。在资产列表中显示正常，而LUMA和用户“授权资产”中存在错误节点和资产。

##### 使用版本
Version 1.4.6-2 GPLv2

##### 问题复现步骤
1.在资产管理->资产列表中建立多个树节点；
2. 在资产树中多次拖动树节点调整位置，如：A节点原来在Defualt根节点下，拖动放到B节点下；拖出来放到Defualt根节点下，再拖动放到C节点下；

##### 具体表现[截图可能会更好些,最好能截全]
资产列表中正常资产树
![image](https://user-images.githubusercontent.com/46468883/50806695-b061c200-1332-11e9-8f6c-67956391e27d.png)

用户列表中有问题的资产树
![image](https://user-images.githubusercontent.com/46468883/50806839-56153100-1333-11e9-84ed-44327fee8c77.png)

Luna中有问题的资产树
![image](https://user-images.githubusercontent.com/46468883/50806820-3c73e980-1333-11e9-9b20-e7759b333f44.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by laiyh31** [comment]
![image](https://user-images.githubusercontent.com/46468883/50807101-2adf1180-1334-11e9-971f-d8b410a11c11.png)

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by jiangxiaobai** [comment]
我也出现类似问题，在资产列表中各节点及资产都显示正常，但在luna左侧的资产树那边，全部显示在default节点下。

**Comment by laiyh31** [comment]
这是因为节点没有被授权，在某个授权下把节点也加入就可以了




------------------ 原始邮件 ------------------
发件人: "姜志福"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 上午8:37
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "lyh31"<121952736@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326)




我也出现类似问题，在资产列表中各节点及资产都显示正常，但在luna左侧的资产树那边，全部显示在default节点下。

**Comment by jiangxiaobai** [comment]
哦  明白了 感谢！但有个问题，如果我整个节点授权，那不是所有该节点下的机器都能被访问到？但这不是我想要的啊，我只想授权特定节点的特定主机。




------------------ 原始邮件 ------------------
发件人: "laiyh31"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 上午8:49
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "姜小白"<229346459@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326)



这是因为节点没有被授权，在某个授权下把节点也加入就可以了 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "姜志福"<notifications@github.com>; 
 发送时间: 2019年6月28日(星期五) 上午8:37 
 收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>; 
 抄送: "lyh31"<121952736@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326) 
 
 
 
 
 我也出现类似问题，在资产列表中各节点及资产都显示正常，但在luna左侧的资产树那边，全部显示在default节点下。

**Comment by laiyh31** [comment]
所有节点是可以看到，但能否访问还要看有没授权。没有对应授权的主机，点击连接会提示没有授权的系统用户




------------------ 原始邮件 ------------------
发件人: "姜志福"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 上午8:54
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "lyh31"<121952736@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326)



哦  明白了 感谢！但有个问题，如果我整个节点授权，那不是所有该节点下的机器都能被访问到？但这不是我想要的啊，我只想授权特定节点的特定主机。 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "laiyh31"<notifications@github.com>; 
 发送时间: 2019年6月28日(星期五) 上午8:49 
 收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>; 
 抄送: "姜小白"<229346459@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326) 
 
 
 
 这是因为节点没有被授权，在某个授权下把节点也加入就可以了  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "姜志福"<notifications@github.com>;  
  发送时间: 2019年6月28日(星期五) 上午8:37  
  收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;  
  抄送: "lyh31"<121952736@qq.com>;"Author"<author@noreply.github.com>;  
  主题: Re: [jumpserver/jumpserver] 资产树节点显示错误 (#2326)  
   
   
   
   
  我也出现类似问题，在资产列表中各节点及资产都显示正常，但在luna左侧的资产树那边，全部显示在default节点下。

**Comment by jiangxiaobai** [comment]
我尝试了一下创建新的资产授权，只在资产列表添加资产就会没有节点树信息，而在节点列表里添加了节点的话，所有这节点的资产又全部可以访问。并没有达到您说的效果，我不知道您这边是怎么授权的？
