### ISSUE TITLE
使用网域网关无法更新主机硬件信息和测试可连接性

### ISSUE THREAD

**Issue by denwork** [jumpserver/jumpserver#2329]
[简述你的问题]
使用网域网关管理云主机，可以正常使用终端登录。但是无法更新硬件信息和测试可连接性。
日志内容：
2019-01-08 16:44:39 Start task: 测试资产可连接性: app01(172.18.xx.xx)

PLAY [测试资产可连接性: app01(172.18.xx.xx)]

TASK [ping]
fatal: [app01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: percent_expand: unknown key %s\r\n", "unreachable": true}

2019-01-08 16:44:39 Task finished

jumpserver的ssh没有做过任何配置更改。
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver版本1.4.x
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![2](https://user-images.githubusercontent.com/21987200/50819660-ae652680-1365-11e9-92f2-68376fd30122.png)
![1](https://user-images.githubusercontent.com/21987200/50819666-b2914400-1365-11e9-8047-c650649a10c8.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
改问题还存在吗？是不是你的密码有特殊字符？

**Comment by denwork** [comment]
问题还是存在。密码有%@! 这三个字符。是否有影响？下面是仪表盘->作业中心->执行历史详情中看到的错误信息。
vm02:	setup => Failed to connect to the host via ssh: percent_expand: unknown key %D

**Comment by ibuler** [comment]
密码不支持特殊字符

**Comment by Gerrylinux** [comment]
这个问题在 v2.12.1 有复现，我使用的是秘钥登录
