### ISSUE TITLE
windows资产无法显示Guacamole RDP上的 G目录

### ISSUE THREAD

**Issue by elijah-cheung** [jumpserver/jumpserver#2330]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
按照centos安装流程一步步安装的，安装后其余均正常，但windows上的rdp有个问题，不管win server 2008还是2012均无法显示Guacamole RDP上的 G目录，上传没有问题，上传后文件可以在jumpserver的/config/guacamole/drive下找到。
<img width="1036" alt="screen shot 2019-01-08 at 11 21 00 pm" src="https://user-images.githubusercontent.com/46492510/50839846-323a0580-139c-11e9-9ebc-6b6859e19ad4.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by elijah-cheung** [comment]
cp /usr/local/lib/freerdp/* /usr/lib64/freerdp解决

**Comment by clannon** [comment]
ln -s /usr/local/lib/freerdp /usr/lib64/freerdp 这一步
/usr/lib64/freerdp已经存在的情况下，软链后会变成
/usr/lib64/freerdp/freerdp -> /usr/local/lib/freerdp
