### ISSUE TITLE
定期测试管理账号可连接性 No such file or directory

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2334]
[简述你的问题]
更新任务内容: 定期测试管理账号可连接性: root
Failed run adhoc 定期测试管理账号可连接性: root, [Errno 2] No such file or directory

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
celery.log中存在该报错

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42203736/50902805-e13b1780-1456-11e9-92f2-5d9e1f42fbcc.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
问题是否还存在？

**Comment by jym503558564** [comment]
问题是否已解决？如有问题，可重新打开issues
