### ISSUE TITLE
无法使用ID登录

### ISSUE THREAD

**Issue by chenmin1992** [jumpserver/jumpserver#2337]
[简述你的问题]
列表里无法直接用ID登录

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. 打一个关键词使筛选列表只剩几个资产
2. 输入对应ID

##### 具体表现[截图可能会更好些,最好能截全]
输入对应ID后无法登录资产机器，而是显示完整列表
![image](https://user-images.githubusercontent.com/20168118/50945142-5d247680-14ce-11e9-8d04-fa4fede1abff.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
