### ISSUE TITLE
无法使用个位数以上ID登录机器

### ISSUE THREAD

**Issue by chenmin1992** [jumpserver/jumpserver#2338]
[简述你的问题]
当想登录ID>=10的机器时无法登录，而是登录到第一个个位数机器

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6

##### 问题复现步骤
1. 想登录ID=11的集群
2. 输入11

##### 具体表现[截图可能会更好些,最好能截全]
输入11登录的不是ID为11的机器而是ID为1的机器
输入21登录的不是ID为21的机器而是ID为2的机器

##### 其他

[注:] 完成后请关闭 issue

**Comment by chenmin1992** [comment]
![image](https://user-images.githubusercontent.com/20168118/50945306-12efc500-14cf-11e9-9a02-06b00b0a74d3.png)

**Comment by ibuler** [comment]
更新代码，已修复

**Comment by chenmin1992** [comment]
@ibuler 请问版本号或commit

**Comment by chenmin1992** [comment]
@ibuler pull最新镜像没有作用  要自己build吗?

**Comment by stephen8339** [comment]
我也遇到了同样问题，求版本号
