### ISSUE TITLE
文件管理功能不能选择具体的路径

### ISSUE THREAD

**Issue by boy6585948** [jumpserver/jumpserver#2340]
[简述你的问题]
文件管理功能不能选择具体的路径，默认的sftp登录路径是/tmp/

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.5-2注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
[
![default](https://user-images.githubusercontent.com/4413469/52906844-22152000-3290-11e9-9150-4b90a5a612e2.png)
](url)
这里面没有地方可以更改目录。
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@boy6585948 [sftp文档](http://docs.jumpserver.org/zh/docs/faq_sftp.html)

**Comment by ibuler** [comment]
新版本已支持设置：  SFTP_ROOT ，修改配置文件
