### ISSUE TITLE
资产树底层节点不显示资产

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2341]
[简述你的问题]

![image](https://user-images.githubusercontent.com/42203736/51019216-24ab9800-15b5-11e9-8e72-f738699b3d47.png)
原先这边点开是显示最底层的资产列表的。现在不显示了
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
资产列表中
左侧的资产树一层一层节点打开，最后一个节点的目录中不显示资产内容
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42203736/51019278-545aa000-15b5-11e9-9b17-cd9202e1515c.png)

![image](https://user-images.githubusercontent.com/42203736/51019286-5c1a4480-15b5-11e9-9f60-2612c2ecb1f7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
