### ISSUE TITLE
Guacamole 注册不了，提示KEY不存在

### ISSUE THREAD

**Issue by yaocanfeng** [jumpserver/jumpserver#2342]
[简述你的问题]

12:25:04.628 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:04.692 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
12:25:04.837 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:05.012 [localhost-startStop-1] INFO  o.a.g.a.j.r.JumpserverRegisterService - Key文件不存在
12:25:05.384 [Thread-5] WARN  o.a.g.a.j.r.JumpserverRegisterService - 注册终端失败: {code:403,result:{"detail":"身份认证信息未提供。"}}
12:25:05.389 [localhost-startStop-1] INFO  o.a.g.a.j.r.JumpserverRegisterService - 获取终端配置: {code:403,result:{"detail":"Access key id invalid"}}
12:25:05.393 [Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService - 开始心跳，间隔: 10000毫秒
12:25:05.393 [Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过
12:25:05.394 [localhost-startStop-1] INFO  o.a.g.extension.ExtensionModule - Extension "JumpServer Authentication" loaded.
12:25:05.395 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:05.399 [Thread-7] INFO  o.a.g.a.j.s.JumpserverSessionService - 开始处理Session队列
12:25:05.485 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
13-Jan-2019 12:25:05.663 警告 [localhost-startStop-1] com.google.inject.internal.ProxyFactory.<init> Method [public void org.apache.guacamole.rest.user.UserResource.updateObject(java.lang.Object) throws org.apache.guacamole.GuacamoleException] is synthetic and is being intercepted by [org.apache.guacamole.rest.RESTExceptionWrapper@4a7e19f5]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
12:25:07.024 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:07.083 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
12:25:07.310 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:07.421 [localhost-startStop-1] INFO  o.a.g.a.j.r.JumpserverRegisterService - Key文件不存在
12:25:07.614 [localhost-startStop-1] INFO  o.a.g.a.j.r.JumpserverRegisterService - 获取终端配置: {code:403,result:{"detail":"Access key id invalid"}}
12:25:07.614 [Thread-8] WARN  o.a.g.a.j.r.JumpserverRegisterService - 注册终端失败: {code:403,result:{"detail":"身份认证信息未提供。"}}
12:25:07.616 [Thread-9] INFO  o.a.g.a.j.r.JumpserverRegisterService - 开始心跳，间隔: 10000毫秒
12:25:07.616 [Thread-9] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过
12:25:07.619 [Thread-10] INFO  o.a.g.a.j.s.JumpserverSessionService - 开始处理Session队列
12:25:07.619 [localhost-startStop-1] INFO  o.a.g.extension.ExtensionModule - Extension "JumpServer Authentication" loaded.
12:25:07.620 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
12:25:07.680 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
13-Jan-2019 12:25:07.784 警告 [localhost-startStop-1] com.google.inject.internal.ProxyFactory.<init> Method [public void org.apache.guacamole.rest.user.UserResource.updateObject(java.lang.Object) throws org.apache.guacamole.GuacamoleException] is synthetic and is being intercepted by [org.apache.guacamole.rest.RESTExceptionWrapper@2f692a80]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
12:25:15.394 [Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过
12:25:15.401 [Thread-5] WARN  o.a.g.a.j.r.JumpserverRegisterService - 注册终端失败: {code:403,result:{"detail":"身份认证信息未提供。"}}
12:25:17.616 [Thread-9] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过
12:25:17.627 [Thread-8] WARN  o.a.g.a.j.r.JumpserverRegisterService - 注册终端失败: {code:403,result:{"detail":"身份认证信息未提供。"}}
12:25:25.394 [Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过
12:25:25.413 [Thread-5] WARN  o.a.g.a.j.r.JumpserverRegisterService - 注册终端失败: {code:403,result:{"detail":"身份认证信息未提供。"}}
12:25:27.617 [Thread-9] INFO  o.a.g.a.j.r.JumpserverRegisterService - 等待心跳，AccessKey验证未通过

##### 使用版本
Version 1.4.6-2 GPLv2.

安装教程http://docs.jumpserver.org/zh/docs/step_by_step.html#windows-windows
![image](https://user-images.githubusercontent.com/21379210/51081589-82172480-172e-11e9-875f-1d246bc9eadb.png)

**Comment by wojiushixiaobai** [comment]
@yaocanfeng 如图
![qq 20190113135804](https://user-images.githubusercontent.com/24326988/51082100-46368c00-173b-11e9-8ae9-1975a6bf7f99.jpg)

**Comment by yaocanfeng** [comment]
![image](https://user-images.githubusercontent.com/21379210/51082116-8bf35480-173b-11e9-91a9-5b3c4fe6f0c8.png)

**Comment by wojiushixiaobai** [comment]
@yaocanfeng 你的图少了jumpserver/config.py 的内容

**Comment by yaocanfeng** [comment]
![image](https://user-images.githubusercontent.com/21379210/51082127-f4423600-173b-11e9-8e9d-c99652bbfd5c.png)

**Comment by yaocanfeng** [comment]
coco 可以连上的

**Comment by wojiushixiaobai** [comment]
@yaocanfeng 

    $ env | grep TOKEN
    $ cat /opt/jumpserver/config.py | grep TOKEN

对比是否一致，一致的情况下，重启guacamole

**Comment by yaocanfeng** [comment]
可以了，谢谢。再问下
![image](https://user-images.githubusercontent.com/21379210/51082181-230cdc00-173d-11e9-93b9-9afe996a25fa.png)这个用户是干嘛用的，在用户管理没有显示。查FAQ没找到具体介绍
