### ISSUE TITLE
jumpserver 使用 sqlite数据库，数据库被锁

### ISSUE THREAD

**Issue by tobewithyou1996** [jumpserver/jumpserver#2344]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
版本1.4.1  版本，使用的是sqllite 数据库，启动项目后，在日志中发现，数据库被锁了，
##### 问题复现步骤
1. [步骤1]
重启服务也是没有效果的，修复下，还有就是在升级文档中，涉及的都是mysql数据库的升级，可以也附带些sqlite的升级吗？我在升级文档中好像没有看到
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/31532979/51093733-923c0c00-17e1-11e9-93c9-17ebe7affd04.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
SQLite 本身就不能作为生产使用，他的设计就是库级锁，请使用 MySQL 作为生产使用吧
