### ISSUE TITLE
会话管理无法打开

### ISSUE THREAD

**Issue by miaoyb** [jumpserver/jumpserver#2345]
[简述你的问题]
会话管理无法打开，错误提示如下。
RequestError at /terminal/session-offline/
TransportError(400, 'illegal_argument_exception', 'Trying to query 8684 shards, which is over the limit of 8000. This limit exists because querying many shards at the same time can make the job of the coordinating node very CPU and/or memory intensive. It is usually a better idea to have a smaller number of larger shards. Update [action.search.shard_count.limit] to a greater value if you really want to query that many shards at the same time.')

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.3.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by miaoyb** [comment]
我知道这个可以通过修改es的参数修复掉，但是为什么会查我这个es集群的shared数量呢

**Comment by ibuler** [comment]
使用了这个sdk去获取 es上存储的session的命令数量 
https://elasticsearch-py.readthedocs.io/en/master/ 请协助处理，并提交PR
https://github.com/jumpserver/jms-storage-sdk
