### ISSUE TITLE
celery日志目录定时清理, 防止inode或磁盘耗尽

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#2347]
[简述你的问题]

##### 使用版本
1.3.1
##### 问题复现步骤
周期性任务较多, 导致磁盘inode耗尽

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/11460661/51155183-a18a8a80-18b1-11e9-9fb0-3f25843b1b47.png)

##### 其他

https://github.com/jumpserver/jumpserver/blob/e1f1bed9c9b0972c683bceeb8b3d6e4d704d9de3/apps/ops/models/celery.py#L13

建议增加一个定时清理任务
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
下个版本增加

**Comment by ibuler** [comment]
已添加

**Comment by sccblue** [comment]
这个问题有出现了

**Comment by sccblue** [comment]
1.5.6版本
