### ISSUE TITLE
ssh 总是自动断掉，几分钟不操作

### ISSUE THREAD

**Issue by HaAlan** [jumpserver/jumpserver#2348]
[简述你的问题]
ssh总是自动断开，不知道是什么问题。是用docker安装的。 

##### 使用版本
1.4.6-2
docker 一键安装
##### 问题复现步骤
1. 登入跳板机，选择id登入，但是总是不能正确匹配到id所对应的主机。
2. ssh回话连接，不操作大概几分钟就会自动断掉，(跳板机/ssh都会断）

##### 其他

[注:] 完成后请关闭 issue

**Comment by gotofuck** [comment]
也有同样的情况

**Comment by xuboatom** [comment]
版本1.4.7也出现操作几分钟就是卡着不动的情况，应该是因为网络不稳定导致ssh卡死不能操作。
建议：在代码中加入ssh的一些心跳设置参数
  ExitOnForwardFailure=yes
  TCPKeepAlive=yes
  ServerAliveInterval=30
  ServerAliveCountMax=3

**Comment by little7777** [comment]
同样的问题, 求解决.

**Comment by xuboatom** [comment]
> 同样的问题, 求解决.
发送的邮件刚看到，我在上个回复中几写了解决方法，你再读下。

**Comment by ibuler** [comment]
是否解决？

**Comment by gengkeye** [comment]
> 版本1.4.7也出现操作几分钟就是卡着不动的情况，应该是因为网络不稳定导致ssh卡死不能操作。
> 建议：在代码中加入ssh的一些心跳设置参数
> ExitOnForwardFailure=yes
> TCPKeepAlive=yes
> ServerAliveInterval=30
> ServerAliveCountMax=3
> 
> 解决方法：
> 修改 coco/coco/connection.py
> 72 行 transport.set_keepalive(300) 参数为transport.set_keepalive(20)
> 如果使用了网关机器跳转
> 那么在
> 136行sock = ssh.get_transport().open_channel( 前加两行
> transport = ssh.get_transport()
> transport.set_keepalive(20)

按照这个解决方法，仍然会出现卡死的现象

**Comment by xuboatom** [comment]
> > 版本1.4.7也出现操作几分钟就是卡着不动的情况，应该是因为网络不稳定导致ssh卡死不能操作。
> > 建议：在代码中加入ssh的一些心跳设置参数
> > ExitOnForwardFailure=yes
> > TCPKeepAlive=yes
> > ServerAliveInterval=30
> > ServerAliveCountMax=3
> > 解决方法：
> > 修改 coco/coco/connection.py
> > 72 行 transport.set_keepalive(300) 参数为transport.set_keepalive(20)
> > 如果使用了网关机器跳转
> > 那么在
> > 136行sock = ssh.get_transport().open_channel( 前加两行
> > transport = ssh.get_transport()
> > transport.set_keepalive(20)
> 
> 按照这个解决方法，仍然会出现卡死的现象
------------------------------------------------------------------
那应该是你的网络状况比我的不如。我这么修改已经解决。
同时回复@老广  已经解决

**Comment by xuboatom** [comment]
修改transport。set_keepalive（）参数的大小，只是对网络状态引起的故障添加保证，如果不起作用，可以试试设置更小的参数，或者检查局域网网络状态。

**Comment by JulyYin** [comment]
请问你这个问题现在解决了吗？我用的1.4.7 也有这个问题 
![image](https://user-images.githubusercontent.com/8434933/54516933-579a4f80-499b-11e9-905b-9e7676c1d7fd.png)
我设置了这个好像没有效果，1.4.8上说 修复session 10分钟后不在线的问题，不知道是不是这个bug

**Comment by nowingfly** [comment]
![WX20190404-002425](https://user-images.githubusercontent.com/2989998/55495642-f5666d80-566f-11e9-93e1-8039032116c2.png)

在线会话老是莫名其妙没了，但Web终端里的连接还在，还可以继续操作，不知道是为什么？？

**Comment by w01fb0ss** [comment]
这个问题解决了吗，我也遇到了这个问题

**Comment by JulyYin** [comment]
这个地方调整一下就好了
 
 
------------------ Original ------------------

**Comment by jym503558564** [comment]
更新一下版本，看问题是否还会复现。
