### ISSUE TITLE
期待增加对数据库客户端工具的支持，如PLSQL Developer等工具

### ISSUE THREAD

**Issue by wx2018** [jumpserver/jumpserver#2352]
[简述你的问题]
期待增加对数据库客户端工具的支持，如PLSQL Developer等工具

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.2
##### 问题复现步骤
1. [步骤1]
将数据库客户端工具集成到堡垒机里，或者提供接口，记录操作日志
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by l-duan** [comment]
同问，也遇到了这个问题。

**Comment by baoweizhang** [comment]
我也有这个需求。

**Comment by ibuler** [comment]
remote apps已支持，可以解决这个问题，remote apps是xpack付费包里的内容
