### ISSUE TITLE
资产授权给ldap用户

### ISSUE THREAD

**Issue by yuedingwangji** [jumpserver/jumpserver#2353]
[简述你的问题]
我现在接入了openldap，但是每次都要用户登陆第一次后，才能在用户列表看到用户，这样才能在资产授权界面对用户进行资产授权

##### 使用版本
1.4.6-2 

##### 问题复现步骤
使用ladp 用户登陆后，页面上的用户列表就多了一个从ladp/ap 来的用户

##### 具体表现[截图可能会更好些,最好能截全]
![](http://testpicup.zuzuche.net/uploads/201901/keng/attach_157a9f634b9a8072.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，目前还没有一键同步功能

**Comment by slan77** [comment]
临时解决方案可以参考  https://github.com/jumpserver/jumpserver/issues/1585

**Comment by jym503558564** [comment]
1.升级版本已支持ldap一键导入功能
2.导入成功后查看用户列表
