### ISSUE TITLE
2006, "Access denied for user 'jumpserver'@'localhost' (using password: YES)")

### ISSUE THREAD

**Issue by hzhaosh** [jumpserver/jumpserver#2354]
[简述你的问题]
按配置文档，出现2006, "Access denied for user 'jumpserver'@'localhost' (using password: YES)")
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
浏览器访问时出现2006, "Access denied for user 'jumpserver'@'localhost' (using password: YES)")

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hzhaosh 数据库配置有误，请检查

**Comment by hhjie** [comment]
这个问题 真找不到原因 本地连接都没问题！

**Comment by cjm788** [comment]
我也碰到了这个问题，怎么解决？
 File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2006, "Access denied for user 'jumpserver'@'localhost' (using password: NO)")
2020-03-06 14:11:58 Connection database failed, exist
