### ISSUE TITLE
【功能需求】第三方应用的支持

### ISSUE THREAD

**Issue by lennyluosz** [jumpserver/jumpserver#2356]
[简述你的问题]
现在很多堡垒机都支持第三方应用，原理是在一台Windows 服务器上装remoteApp,  然后在堡垒机上支持这种remoteApp(都是RDP协议) 
具体请参考 https://www.cloudbility.com/help/audit/app.html

##### 使用版本
1.4.6-2

**Comment by ibuler** [comment]
jumpserver  rdp是基于 guacamole做的，如果 guacamole可以做到我们会支持的

**Comment by luolenny** [comment]
guacamole 0.9就支持了. 
https://stackoverflow.com/questions/52254357/guacamole-rdp-remote-app-within-a-black-box

**Comment by yssnet** [comment]
这个功能很实用呀

**Comment by ibuler** [comment]
support by jumpserver xpack
