### ISSUE TITLE
web终端不显示服务器列表

### ISSUE THREAD

**Issue by RorschachChan** [jumpserver/jumpserver#2358]
[简述你的问题]
将资产正确授权给了用户，但是在web终端不显示服务器列表。我检查了进程，coco和guacamole容器都在正常运行。是luna和jumpserver版本不匹配的原因么？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver版本：Version 1.3.2-2 GPLv2.
Luna版本:Version 1.4.6-101 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/31002078/51578545-df626100-1ef8-11e9-97f4-abaab8454cef.png)
![default](https://user-images.githubusercontent.com/31002078/51578549-e38e7e80-1ef8-11e9-9011-a4449ae859f0.png)
![default](https://user-images.githubusercontent.com/31002078/51578612-0e78d280-1ef9-11e9-9c1b-869f611515e9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
版本必须一致
