### ISSUE TITLE
【功能需求】请问新版本是否有增加时时监控的开发计划？

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#2359]
记得以前在0.3.X版本中，可以观看在线会话的操作记录，在1.X版本之后这个功能就不见了。请问，之后新版中是否有追加这个功能的计划，谢谢

**Comment by ibuler** [comment]
老版本 都是部署在一块的，实时监控比较容易做，但是现在 coco可以很多个，coco可以连接api server，api server并不能直接连接coco，所以要监控实现起来比较复杂

**Comment by muse117** [comment]
@ibuler 请问可否先把guacamole的监控加上去，coco的慢慢再完善。这样起码能保证rdp、vnc可以有实时监控，不至于这个功能完全都用不了。因为这个功能应该算是堡垒机核心功能之一。

**Comment by muse117** [comment]
@ibuler 通过guacamole接入之后，会有一个connectID，通过这个ID号就可以加入到当前会话中。加入的时候有个参数是read-only设置为true就可以做到只看不能操作。这样就可以实时监控了。
![微信截图_20190626100806](https://user-images.githubusercontent.com/9733486/60145971-537f9880-97fa-11e9-9008-0910010e5aac.png)

![微信截图_20190626100447](https://user-images.githubusercontent.com/9733486/60145829-da804100-97f9-11e9-8ebb-1614363e43a5.png)

**Comment by ibuler** [comment]
@muse117 同样guacamole也是，他们在nginx后面，通常会有多个guacamole，如果nginx没有负载均衡到正确那个guacamole上就会404

**Comment by muse117** [comment]
@ibuler 您的意思是guacamole和coco分布式部署在多台服务器中的情况？另外guacamole不也可以ssh接入么，为什么还要用coco呢？因为coco可以支持客户端xshell，putty么？就这为了这个考虑的？

**Comment by ibuler** [comment]
@muse117 是的我们假定 分布式部署才是部署的正常状态。 ssh不接入guacamole，是因为它提供的功能不满足要求，比如命令拦截，比如sftp server等

**Comment by muse117** [comment]
@ibuler guacamole的ssh应该支持sftp吧，命令拦截，还需要再看下。
![微信截图_20190626104409](https://user-images.githubusercontent.com/9733486/60147361-a9a30a80-97ff-11e9-9fbf-a3d5cab245c0.png)

**Comment by ibuler** [comment]
这个sftp用户无法通过工具连接，只能在页面上操作

**Comment by muse117** [comment]
@ibuler 了解了，希望尽快能完善实时监控功能，需要挺强烈的。

**Comment by muse117** [comment]
@ibuler 可以先做一版集中部署的么？我这里用的是集中部署在一起的。

**Comment by ayzhouwen** [comment]
guacamole 协议是支持sftp的,我用java重构的guacamole ,也是根据原有的实现方式改造了一下,实现的sftp上传,这样就不用接入其他的远程连接框架了,

**Comment by ayzhouwen** [comment]
至于命令拦截,我觉的可以从前端下手,比如监听ssh的回车

**Comment by ibuler** [comment]
> 

什么个逻辑呢，添加资产的时候把 sftp 填写上去？
