### ISSUE TITLE
BEAT自动中断

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2360]
[简述你的问题]
运行一段时间后beat自动挂了。查日志发现存在报错
You can't execute queries until the end of the 'atomic' block.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/42203736/51653026-a5fb2580-1fcc-11e9-9783-b4d0afd13956.png)
"An error occurred in the current transaction. You can't "
django.db.transaction
.
TransactionManagementError
:
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
下个版本升级 celery beat，看看问题是否还会出现
