### ISSUE TITLE
hostname用户可以设置别名

### ISSUE THREAD

**Issue by Antisunny** [jumpserver/jumpserver#2361]
### 问题

现在每个用户不能为每天服务器设置自定义的名字，导致只能使用管理员设置的那个没有意义的字符串。

### 使用版本

Version 1.4.6-2

### 问题复现步骤

登录jumpserver，点击‘我的资产’，列出的hostname列

### 建议

每个人可以设置自己的hostname名称，别名一样的东西，不然不好记忆。

**Comment by xjpresley** [comment]
支持  确实需要这个功能

**Comment by ibuler** [comment]
再等等大家的反馈吧，如果超过20个人有这需求再考虑
