### ISSUE TITLE
测试可连接性失败

### ISSUE THREAD

**Issue by Seally10** [jumpserver/jumpserver#2362]
[简述你的问题]

##### 使用版本
1.4.6-2 运行在docker里面

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
在docker中通过命令 ssh -p 22  manager_user@192.xxx.xxx.xx 可以连，但页面上测试连通性有问题：

{"changed": false, "msg": "Failed to connect to the host via ssh: Control socket connect(/root/.ansible/cp/9eb836ec9c): Connection refused\r\nFailed to connect to new control master\r\n", "unreachable": true}

**Comment by ibuler** [comment]
这是通过ansible来连接的，你可以尝试在里面安装个ansible来测试试试

**Comment by xu-xiang** [comment]
docker run --name jms_all_1 -d -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:1.5.1

这个镜像应该搞定这个问题，镜像默认运行起来就无法连接资产

**Comment by xu-xiang** [comment]
问题已经定位，从jumpserver--ansible--docker--SSH TCP复用--af_unix on overlay才分析出最终原因。

根本原因是ansible使用的SSH TCP复用技术是基于IPC就是UNIX Domain Socket（af_unix），而af_unix在v4.4.16（linux补丁上看起来是这个版本，没有具体测试）内核版本前在overlay 文件系统上是有BUG的，是没法运行的，这就导致jumpserver官方提供的镜像在该内核范围内的docker宿主机上是没法正常ssh连接的。

解决这个问题，两个办法
1、升级内核版本（没有测试，github代码上看已经提交了fix）
2、修改ansible中SSH tcp复用的sokcet路径

```
docker exec -it 容器名/ID bash
mkdir  /etc/ansible/
vi /etc/ansible/ansible.cfg
增加下面内容
[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
control_path = /dev/shm/cp%%h-%%p-%%r
```
原理容器内df -h看下就好，/dev 是tmpfs文件系统，可以支持af_unix。

建议官方docker也修复该问题，兼容下4.4.16内核版本以下的容器环境



附（内核fix代码和说明）：
https://github.com/torvalds/linux/commit/30402c8949934fbaca07d9c20074d0d7a5a8385f
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1607404

**Comment by junan0801** [comment]
补充下,我也是按照@xu-xiang  提供的方法解决,谢谢你的分享, 如果是 使用 docker compose 安装的jumpserver ,需要将 ansible.cfg 映射到jms_core 容器里,问题就能解决了(最初以为是修改coco 容器,耽误了好久,提醒下后来人)
