### ISSUE TITLE
多coco切换时密钥变更问题

### ISSUE THREAD

**Issue by Aaron0-wang** [jumpserver/jumpserver#2363]
[简述你的问题]
## 问题一：coco切换后ssh连接提示密钥变更报错问题
这是我的架构：
![default](https://user-images.githubusercontent.com/38186870/51722892-ebcdf180-2091-11e9-9961-1663388ff3fc.png)  
假如我使用ssh连接到vip，给我分配的coco1，然后我下次连因为是有ip_hash的，所以还会是coco1，但是如果在此期间coco1 down掉了，会自动切换coco。**假设自动切到了coco2上，我再ssh连接，会报错。** 提示：
![default](https://user-images.githubusercontent.com/38186870/51722996-60a12b80-2092-11e9-9d24-bcbefdecdacd.png)  
除了在~/.ssh/下新建一个config，在里面写
```
Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
```
还有什么别的方法吗？因为我不可能让他们每个人都这么做
## 问题二：怎样限制用户使用文件管理功能时的大文件下载、copy问题？
在nginx里做的限制max_size 100m好像没有用。假设我要规定，大于1g的文件，既不允许download，也不允许服务器之间copy，以免长时间占用我的带宽，应该怎么限制呢？
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]   

1.4.4
----
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by Aaron0-wang** [comment]
1. **问题一解决**
方法是将 **/opt/coco/keys/host_rsa_key** 设置为一样的就不会报那个错误了  
![default](https://user-images.githubusercontent.com/38186870/51736643-8ac01100-20c5-11e9-9066-a2597306889b.png)
2. 现在只剩问题二了，需要一个方法来限制文件传输功能，如果限制不了大小，能不能限制 **只有指定的人能够使用sftp功能**？

**Comment by ibuler** [comment]
1. 问题1新版本统一生成host key
2. 问题2 计划中

**Comment by ibuler** [comment]
多个coco记得做ip_hash绑定
