### ISSUE TITLE
如何使用terminal status接口

### ISSUE THREAD

**Issue by Sandra299** [jumpserver/jumpserver#2367]
![image](https://user-images.githubusercontent.com/20556236/51883075-5c3f8000-23bc-11e9-9cf5-1086b93caca1.png)
![image](https://user-images.githubusercontent.com/20556236/51883086-6e212300-23bc-11e9-9576-11a36069febb.png)

**Comment by ibuler** [comment]
目前这个接口没有详细规划，只是同步心跳来用，cpu等信息也没有保存

**Comment by ibuler** [comment]
status接口上报心跳，当不再上报时证明coco出问题了
