### ISSUE TITLE
增加克隆资产或权限等功能

### ISSUE THREAD

**Issue by xornono** [jumpserver/jumpserver#2370]
[简述你的问题]
像资产有会重复添加，但没有使用excel表导入，非常希望有个复制（克隆）功能，这样可以非常之方便，小小的建议，有一点小复制，因为要读取主机或分组下拉选项，显示出真实分组名称等。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时不考虑，毕竟clone出来后差异的东西比较多，没带来多少优势，clone的按钮添加到列表action中也不太美观
