### ISSUE TITLE
是否可以单独限制RDP和SFTP的文件上传和下载

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#2371]
[简述你的问题]
是否可以单独限制RDP和SFTP的文件上传和下载,  可以只允许上传不允许下载?

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
目前还不能，还在计划中

**Comment by July-NetEase** [comment]
这个想法很好啊，这样对权限要求更严格。
期待。

**Comment by ibuler** [comment]
sftp已支持

**Comment by bigbird1985** [comment]
貌似目前Windows上传和下载不能单独设置吧？只能选择要么都行要么都不行
