### ISSUE TITLE
请问是否有从0.3.2版本，将数据（资产、用户）迁移到1.4.x版本的方案

### ISSUE THREAD

**Issue by masato-xd** [jumpserver/jumpserver#2375]
[简述你的问题]
请问是否有从0.3.2版本，将数据（资产、用户）迁移到1.4.x版本的方案

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
并不能
