### ISSUE TITLE
jumpserver 1.4.7 配置里面的SECRET_KEY的位数

### ISSUE THREAD

**Issue by itnikita** [jumpserver/jumpserver#2378]
jumpserver 1.4.7 SECRET_KEY的位数？
cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50
cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49
官方在线版的文档里面写的是50
但是代码里面配置文件的注释上写的是49
应该以哪个为准？

**Comment by itnikita** [comment]
在线文档是这样写的：
$ SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`  # 生成随机SECRET_KEY
$ BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`  # 生成随机BOOTSTRAP_TOKEN

但是配置文件的注释是这样的：
``` bash
# SECURITY WARNING: keep the secret key used in production secret!
# 加密秘钥 生产环境中请修改为随机字符串，请勿外泄, 可使用命令生成 
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
SECRET_KEY:
```

**Comment by wojiushixiaobai** [comment]
无影响

**Comment by ibuler** [comment]
两者都可以
