### ISSUE TITLE
邮件设置报错

### ISSUE THREAD

**Issue by Jiangofstudy** [jumpserver/jumpserver#2381]
[简述你的问题]
邮件设置测试报错

##### 使用版本
1.4.7-2

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28861075/52553917-2b316780-2e20-11e9-9955-a42c3b4c4c21.png)

**Comment by LoongLiWang** [comment]
smtp.exmall.qq.com 这是什么smtp呢，如果要使用qq的smtp ， 那应该是smtp.qq.com ， 阿里云/腾讯云是禁用了25端口的，希望对你有帮助

**Comment by liuzheng** [comment]
请参阅官方文档进行配置<https://service.exmail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001254>
官方说了很明白了 SSL

@LoongLiWang 这个是腾讯的企业邮箱
我直接关了，应该没异议了
