### ISSUE TITLE
求Jumpserver用户公钥的加密算法

### ISSUE THREAD

**Issue by ixrjog** [jumpserver/jumpserver#2385]
[简述你的问题]
求Jumpserver用户公钥的加密算法, users_user表_public_key字段中存储的密文

**Comment by July-NetEase** [comment]
其实没啥，你可以看下xxx/apps/common/utils.py 中的Signer类，写的很清楚。

**Comment by ibuler** [comment]
如上

**Comment by ixrjog** [comment]
好的，谢谢各位！我自己研究下
