### ISSUE TITLE
jms管理脚本的小问题修正

### ISSUE THREAD

**Issue by hzbd** [jumpserver/jumpserver#2386]
[简述你的问题]
jms管理脚本中的调用的执行的`python manage.py showmigrations users`是否可以统一为 `python3 manage.py showmigrations users`,不然在centos7部署的时候，如果不用venv虚拟环境，会踩有个小坑，启动会报错。
```
def check_database_connection():
    os.chdir(os.path.join(BASE_DIR, 'apps'))
    for i in range(60):
        print("Check database connection ...")
        code = subprocess.call("python manage.py showmigrations users ", shell=True)
        if code == 0:
            print("Database connect success")
            return
        time.sleep(1)
    print("Connection database failed, exist")
    sys.exit(10)
```

##### 使用版本
[1.4.7]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3000843/52709577-1abbf100-2fc8-11e9-87c3-0f3fdf24a73a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可自行修改，部署统一使用 venv
