### ISSUE TITLE
请问下如果ldap认证，jp不可以修改密码这个选项在哪里设置？

### ISSUE THREAD

**Issue by hzbd** [jumpserver/jumpserver#2387]
[简述你的问题]
请问下如果ldap认证，jp不可以修改密码这个选项在哪里设置？不知道下面截图的意思是否理解正确

##### 使用版本
V1.4.7

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3000843/52722609-ef94ca00-2fe6-11e9-96c9-312de4866bde.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hzbd 默认策略，ldap用户不可修改密码，强制与ldap服务器同步

**Comment by hzbd** [comment]
> @hzbd 默认策略，ldap用户不可修改密码，强制与ldap服务器同步

ok，了解。web端页面好像还没有关闭修改密码的功能。

**Comment by ibuler** [comment]
用户无法更改
