### ISSUE TITLE
vim 编辑录像和命令统计BUG

### ISSUE THREAD

**Issue by hjc123186** [jumpserver/jumpserver#239]
1、通过web登陆方式 vim 录像正常，但vim后面的一条命令在命令统计中丢失。
2、通过SSH登陆方式vim 录像卡住不能播放，vim后面的一条命令在命令统计中同样丢失。

**Comment by hjc123186** [comment]
我的版本已经升级到现在最新版本0.3.2.

**Comment by liuzheng712** [comment]
@hjc123186 能否告知你是如何退出vim的？

**Comment by hjc123186** [comment]
@liuzheng712 我是：wq  保存退出。

**Comment by hjc123186** [comment]
Jumpserver 安装的服务器是用Centos 7.0 的，和这个有没有关系？

**Comment by liuzheng712** [comment]
略诡异，能否手机拍个视频发给我看看，liuzheng712@gmail.com，最后每个按键都报一下，应该不是服务器问题，你浏览器也显示一下，猜测可能是代码某处的隐藏bug，不过觉得不科学啊~郁闷~

**Comment by hjc123186** [comment]
视频文件已经发送，数据帮忙保密，谢谢。
我所有的按键vim --> i -->录入内容-->Esc键-->:wq

**Comment by hjc123186** [comment]
难道你们测试都没有问题。。-.-

**Comment by liuzheng712** [comment]
这个我们真没问题啊。。。。

**Comment by aaronchou0** [comment]
我也是一样的问题，vim后不能播放录像卡住 还有命令统计出现各种不同的丢失 比如我 ls /tmp/ 可能只记录到了mp/这种

**Comment by hackerain** [comment]
Me too啊，回放到vim打开文件就卡住了，测试过chrome和safari都是同样的问题。

**Comment by ibuler** [comment]
same with #501
