### ISSUE TITLE
用api如何能修该管理用户的密码

### ISSUE THREAD

**Issue by flzhang132** [jumpserver/jumpserver#2390]
[简述你的问题]
请问，用api如何能修该管理用户的密码

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.7 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 进入 http://ip/docs/
2. 选择 /assets/v1/admin-user/{id}/auth/
3.输入data和id，点击执行按钮 
生成如下curl访问命令
curl -X PUT "http://10.150.106.15/api/assets/v1/admin-user/9040a75d-18bc-4557-a638-36d6e4e9a2e2/auth/" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: uxe1Ouc2LqxE6AS5oZAxu9W8qHHSixjhc9lXJ8r7olvAXAdMMf63xLS7vXfNgfUy" -d "{ \"password\": \"12345678\", \"private_key\": \"string\"}"
但总是报403
"detail": "CSRF token missing or incorrect."
那么这个csrf如何获取，或用python如何 去写程序调用api修该管理用户的密码？？

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26810567/52770136-4644e700-306d-11e9-9bed-c9df409c60f3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
使用postman或curl去操作
