### ISSUE TITLE
跨版本升级问题

### ISSUE THREAD

**Issue by npcomet** [jumpserver/jumpserver#2391]
jumpserver 热度一直很高
现在发版本的频率也很高
但是在生产环境，不大可能紧随官方升级，发布新版本的时候能不能标注下支持最低从哪个版本升级？

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.4 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@npcomet [升级文档](http://docs.jumpserver.org/zh/docs/upgrade.html)有注明

**Comment by npcomet** [comment]
好的 感谢
