### ISSUE TITLE
批量执行查看内容多了显示不全，输出框只有一半有显示

### ISSUE THREAD

**Issue by alenas520** [jumpserver/jumpserver#2405]
[简述你的问题]
批量执行查看内容多了显示不全，输出框只有一半有显示
![111](https://user-images.githubusercontent.com/31032699/52938501-cb493c80-339c-11e9-896b-2f683fc84aba.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. tail 批量查看日志内容，行数多无法显示，且查看也不方便，很难找到是哪台机器的日志

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@alenas520 收到，已经反馈

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/commit/0fcbd9fd06241c40f10ec38412520fa9349b4471
