### ISSUE TITLE
最新版本的“luna支持直接登录到某个资产”是什么

### ISSUE THREAD

**Issue by xhncshenxin** [jumpserver/jumpserver#2412]
[简述你的问题]

最新版本的“luna支持直接登录到某个资产”是什么，具体用法能否给个说明，URL格式怎么写？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
http://localhost:8080/luna/?login_to=资产ID
