### ISSUE TITLE
明显的界面显示BUG

### ISSUE THREAD

**Issue by huoqiangwa** [jumpserver/jumpserver#2413]
[简述你的问题]
![tim 20190219173930](https://user-images.githubusercontent.com/31760901/53005373-18491380-346e-11e9-86b2-f7a80923044e.png)

问题
如截图所示，使用widows资产，页面如果隐藏左边，右边也是黑乎乎的一坨无用界面，我记得之前老版本是没有这问题的，我从1.3开始，升级到1.44还是这样，

##### 使用版本
1.44

##### 问题复现步骤
1.windows登录资产就可以

![tim 20190219174438](https://user-images.githubusercontent.com/31760901/53005614-90173e00-346e-11e9-9bfb-ad1b45d8ce88.png)

[注:] 完成后请关闭 issue
[](url)

**Comment by ibuler** [comment]
1.4.8已修复
