### ISSUE TITLE
1.4.7 没法更改资产列表下的root节点名称

### ISSUE THREAD

**Issue by tigerbin** [jumpserver/jumpserver#2416]
[简述你的问题]
1.4.7版本 没法更改资产列表下的root节点名称

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by tigerbin** [comment]
1.4.6版本可以更改root节点名称，一旦升级到1.4.7版本，就不能更改

**Comment by yssnet** [comment]
是Bug还是什么情况？

**Comment by tigerbin** [comment]
是BUG。资产列表下修改root根节点名称，提示不能修改，而且1.4.6版本是可以修改的。
![image](https://user-images.githubusercontent.com/13775090/53282682-19cc5180-3776-11e9-952d-0a7859a5ec8f.png)

**Comment by ibuler** [comment]
先手动修改数据库吧
