### ISSUE TITLE
命令过滤无效问题

### ISSUE THREAD

**Issue by yuetian-li** [jumpserver/jumpserver#2424]
[简述你的问题]
我使用命令过滤连接网络设备，输入的命令是拒绝的，但是实际可用正常执行

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. 使用casa C3K3200设备
2. 所有过滤设置无效

##### 具体表现[截图可能会更好些,最好能截全]
https://github.com/yuetian-li/test/blob/master/P(JHHA8(K86XJ3%7E(M%40LVN(J.png

##### 其他

[注:] 完成后请关闭 issue

**Comment by yuetian-li** [comment]
> 
> 
> [简述你的问题]
> 我使用命令过滤连接网络设备，输入的命令是拒绝的，但是实际可用正常执行
> ##### 使用版本
> 
> [请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
> 1.4.2
> ##### 问题复现步骤
> 
>     1. 使用casa C3K3200设备
> 
>     2. 所有过滤设置无效
> 
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> 
> [https://github.com/yuetian-li/test/blob/master/P(JHHA8(K86XJ3%7E(M%40LVN(J.png](url)
> ##### 其他
> 
> [注:] 完成后请关闭 issue

**Comment by cheerwei** [comment]
同样问题路过，连的华三交换机

**Comment by ibuler** [comment]
命令匹配时可能不太准，暂时还没有好的办法
