### ISSUE TITLE
开机自启脚本有问题

### ISSUE THREAD

**Issue by maorui2k** [jumpserver/jumpserver#2429]
[简述你的问题]
按照文档描述设置自启脚本，提示source: not found.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
1. [步骤1]：在Ubuntu 16.04，按照一步一步安装文档安装1.4.8，并设置开机自启；
2. [步骤2]：执行sh /opt/start_jms.sh出现错误

##### 其他
应该明确指定使用/bin/bash才能成功

**Comment by wojiushixiaobai** [comment]
@maorui2k ubuntu无法使用source命令，可以用.代替
如: 
    $ . /opt/py3/bin/activate
