### ISSUE TITLE
您好, 我在使用jumpserver-1.4.6-2版本web终端无法显示下划线

### ISSUE THREAD

**Issue by StandNorthStar** [jumpserver/jumpserver#2430]
[简述你的问题]
web终端无法显示下划线

##### 使用版本
[1.4.6-2]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
图片上面是web页面显示的内容,  图片下面是通过终端连接显示的内容. 
![image](https://user-images.githubusercontent.com/18138867/53284963-e1d50680-3795-11e9-9589-04a9c71c082f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
![qq20190225-162546](https://user-images.githubusercontent.com/24326988/53323758-05c15500-391a-11e9-9089-b734eb64dd3b.jpg)

@StandNorthStar 请更新到最新的版本，最新版本测试无此问题

**Comment by StandNorthStar** [comment]
我昨天更新了chrome浏览器好了, 应该是浏览器版本问题.  谢谢!
