### ISSUE TITLE
jumpserver执行命令能不能加一个资产搜索功能

### ISSUE THREAD

**Issue by tuyula** [jumpserver/jumpserver#2433]
[简述你的问题]

##### 使用版本
1.4.8

##### 问题复现步骤
1. jms执行命令能不能加一个资产搜索功能

##### 具体表现[截图可能会更好些,最好能截全]
没有搜索，我们资产分类多，查找很繁琐

**Comment by jym503558564** [comment]
目前批量命令是根据选择的系统用户显示授权的资产树
