### ISSUE TITLE
jumpserver导致堆栈溢出

### ISSUE THREAD

**Issue by yanmaipian** [jumpserver/jumpserver#2443]
jumpserver导致堆栈溢出

##### 使用版本
Jumpserver是基于master分支

##### 问题复现步骤
1. [步骤1]
系统信息:Linux iZj6c5bawqtp4mstoe5n3oZ 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
2. [步骤2]
使用systemctl status guacamole启动的时候起始系统堆栈溢出
![image](https://user-images.githubusercontent.com/12362162/53475122-1ef90b80-3aaa-11e9-9832-4b0c9603b5a3.png)

**Comment by ibuler** [comment]
应该不影响使用，暂时忽略吧
