### ISSUE TITLE
命令过滤功能短暂性失效问题

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#2444]
版本：1.4.7
问题描述：
使用coco登入服务器，连续快速输入同一个命令，比如sudo -i，有时会出现执行成功的情况

经反复测试，此BUG可重现。

**Comment by gengkeye** [comment]
@ibuler 大神，请问下这个BUG会在哪个版本中修复～

**Comment by ibuler** [comment]
这个可能是命令匹配有关，暂时可能无法100%精确匹配
