### ISSUE TITLE
web terminal 连接资产没有反应，偶尔可以正常连接

### ISSUE THREAD

**Issue by 932340583** [jumpserver/jumpserver#2445]
[简述你的问题]
从升级到1.4.7开始，这个问题突然出现，升级到1.4.8还是这样。还在在开发者中心可以看到很多400 BAD REQUEST 的请求。在nginx的error log中会有拒绝连接的错误提示。按照http://docs.jumpserver.org/zh/docs/faq.html 第9条提示修改了nginx配置，还是不管用。jumpserver所有部件版本号均为1.4.8

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8
##### 问题复现步骤
1. [步骤1]  在网页终端连接资产无反应
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![tim 20190228142840](https://user-images.githubusercontent.com/17899509/53545790-9d66b380-3b65-11e9-8ded-4c2d847cd9bd.png)
![tim 20190228142906](https://user-images.githubusercontent.com/17899509/53545792-9dff4a00-3b65-11e9-8706-bc0c0b336fc7.png)
![tim 20190228142925](https://user-images.githubusercontent.com/17899509/53545793-9e97e080-3b65-11e9-9da5-c002ea208458.png)
![tim 20190228142954](https://user-images.githubusercontent.com/17899509/53545794-9e97e080-3b65-11e9-9d5c-91095e462d24.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by gengkeye** [comment]
我也遇到过这个问题，有时会没有反应，有时又可以连接，大部分时候是可以连接的

**Comment by ibuler** [comment]
@932340583 现在还是很频繁吗？如果是请通过群里里的qq联系我

**Comment by ibuler** [comment]
@gengkeye 如果有多个coco时要考虑 ip_hash, 保证一个请求只代理到同一个coco上去

**Comment by gengkeye** [comment]
@ibuler 好的，目前只用到了一个COCO

**Comment by 932340583** [comment]
@ibuler 好的，我加您

**Comment by wojiushixiaobai** [comment]
@ibuler 已为用户处理，原因为coco组件未正常退出的同时启动了多个coco进程引起的。

**Comment by jasper-zhang** [comment]
> @gengkeye 如果有多个coco时要考虑 ip_hash, 保证一个请求只代理到同一个coco上去
这里为什么要求到一个coco上去，原理是怎样的呢？求大佬解惑
