### ISSUE TITLE
Web终端窗口自动关闭问题

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#2446]
版本：1.4.7
问题描述：
web终端上登入服务器，有时会发现之前打开过的、闲置的窗口会消失不见，被莫名其妙、悄无声息地关闭了。
不清楚这是系统的设计还是BUG。。

**Comment by ibuler** [comment]
tab会关闭吗？

**Comment by gengkeye** [comment]
@ibuler 是的，偶有发生，不太好重现

**Comment by ibuler** [comment]
暂时关闭了，如有问题，请重新打开
