### ISSUE TITLE
web 终端命令审计bug

### ISSUE THREAD

**Issue by wanggaolin** [jumpserver/jumpserver#2448]
[简述你的问题]

登录web终端执行的命令记录不到，而且录像回放也看不到
##### 使用版本
docker 安装的最新版本

##### 问题复现步骤
登录web终端后改变窗口大小，然后在执行命令，重复上述步骤，有的命令能记录半截，有的命令完全记录不下来

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
截图看看
