### ISSUE TITLE
LDAP配置中关于多重OU的配置

### ISSUE THREAD

**Issue by coologin** [jumpserver/jumpserver#2449]
[简述你的问题]

LDAP配置中关于多重OU的配置。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

版本1.4.7

##### 问题复现步骤

现像1：不配置OU，点击 ‘测试连接‘ 也能验证成功！
           在绑定OU一栏中如果**没有写入OU相关信息**，写入’DC=xxx,DC=cn‘ ，当然其它都写好，**连接测试也能成功**，能读到用户条数。退出后，用域帐户死活不能登录，我一直纠结在这里两天时间，做了如下测试：在域控主机上抓包，换台域控认证，又是改LDAP映射。

         其中有一个报错很普遍：这个报错是抓包得到的，域控发给jumpserver，同样在jumpserver.log中也有

**LdapErr: DSID-0C0907C2**, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

这句话意思 是 提示没有绑定成功。。。

2，按要求提示，尝试加上OU=XX就能正常登录了。但是为什么我没有加OU，是因为用此系统我希望默认是全公司的人，所以没有加OU。现在加上OU就成功的，那么多个OU如何加？

由于提示的‘使用|分隔各OU’，我错误认为OU是这样：
OU=1号项目部|OU=2号项目部,DC=xxx,DC=cn
OU=1号项目部|2号项目部,DC=xxx,DC=cn

正确的多OU配置方法：
OU=1号项目部,DC=manjinba,DC=cn|OU=2号项目部,DC=manjinba,DC=cn

##### 具体表现[截图可能会更好些,最好能截全]
在域主机上看到数据包已发现域用户
![default](https://user-images.githubusercontent.com/19770663/53611044-11f22e80-3c08-11e9-9813-24f16cb4417f.png)

##### 其他

本次多OU正确配置
![default](https://user-images.githubusercontent.com/19770663/53611105-4a920800-3c08-11e9-807d-97bb932d7579.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@coologin 文档里面一直写得有http://docs.jumpserver.org/zh/docs/faq_ldap.html

**Comment by ibuler** [comment]
这样是否就可以了？

**Comment by pengfei2018** [comment]
一直提示  `ou:ou=paat,dc=paat,dc=local中没有匹配条目`

**Comment by ibuler** [comment]
已支持
