### ISSUE TITLE
jp和coco组件版本依赖不一致

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#2451]
版本：v1.4.7
问题描述：
JP1.4.7和COCO1.4.7的文件requirements.txt中，有2个组件指定的版本不一致，如下：

name |   JP    |     coco  
--- | --- | ---
pycparser  | 2.19  |  2.18      
cffi  |  1.11.5   |    1.11.2

**Comment by ibuler** [comment]
感谢反馈，下个版本改成一样的
