### ISSUE TITLE
jumpserver 1.2.1-2版本 手机SSH客户端下按p不返回列表

### ISSUE THREAD

**Issue by wajika** [jumpserver/jumpserver#2453]
[简述你的问题]
使用手机的SSH客户端，按p键后无法返回主机列表
按其他键有返回信息

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.2.1-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
电脑ssh 连接上去, 按p有问题吗？如果没有问题，看看手机上按p时有没有错误日志

**Comment by wajika** [comment]
> 电脑ssh 连接上去, 按p有问题吗？如果没有问题，看看手机上按p时有没有错误日志

电脑操作是正常的，IOS系统 找了好几个ssh工具测试，输入p会卡住输入其他都是可以返回，我想是不是p 返回的列表信息太大？

**Comment by ibuler** [comment]
测试没有问题
