### ISSUE TITLE
ssh终端使用卡死

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2454]
[简述你的问题]
当jms的beat意外中断后，使用ssh连接就开始逐渐卡顿。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.6-2
##### 问题复现步骤
1. beat中断
2. 多次连接ssh终端后开始逐步出现卡顿

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42203736/53631670-088bb500-3c4e-11e9-9dfe-3f02d906c19f.png)
![image](https://user-images.githubusercontent.com/42203736/53631695-193c2b00-3c4e-11e9-8181-96bdec2b5b81.png)

##### 其他
目前排查的结果是无法自动中断连接，连接数持续增长。然后就开始出现卡顿的情况了
初步怀疑是因为beat意外stop后自动断开连接的功能没有启用，旧连接持续，新连接又在增加导致。还请帮忙排查下
[注:] 完成后请关闭 issue

**Comment by RaynorAZ** [comment]
补充下，在无人使用的时候看了下coco的tcp连接，并没有释放这部分的连接。也就是说，如果beat意外中断或者不能正常生效的时候，coco不能正常释放tcp连接，从而导致在使用ssh终端的时候产生卡顿的问题。

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 已收到反馈，感谢。

**Comment by navyaijm2017** [comment]
我也遇到同样的问题，用一段时间，cocod的进程占用cpu就特别卡，用户登录卡顿，等待楼主的解决方案

**Comment by ibuler** [comment]
1.4.6这个问题应该缓解了，很少能看到连接没有断开的

**Comment by RaynorAZ** [comment]
> 1.4.6这个问题应该缓解了，很少能看到连接没有断开的

我这边这种情况相对比较多。每次beat意外中断后，coco这边的连接数就会不断增加。lsof -p <COCO-PID>的时候也会发现已打开的socket和pipe只会增加。今天晚上我们这边会更新到1.4.8，再观察下这个问题

**Comment by jym503558564** [comment]
现在问题是否还会复现？

**Comment by RaynorAZ** [comment]
这个问题目前更新到1.5.1的时候依然存在。通过lsof -p查看还是存在没有release的链接。

八千流 <notifications@github.com> 于2019年8月1日周四 下午6:51写道：

**Comment by ibuler** [comment]
beat和coco没有关系，他们之间没有交集
