### ISSUE TITLE
如何配置radius用户认证

### ISSUE THREAD

**Issue by lo-ok** [jumpserver/jumpserver#2458]
[简述你的问题]
请问如何配置radius用户认证

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by lidfgab** [comment]
同样的问题，
在/opt/jumperserver/config.yml和/opt/jumperserver/apps/jumperserver/config.py里设置了radius信息，但是用户认证仍然不走radius，从radius server上也看不到任何请求信息

**Comment by ibuler** [comment]
jumpserver的radius仅通过了free radius测试，不知道是否支持，另外，可以尝试清理一下配置缓存

```
$ python manage.py shell
>>> from django.core.cache import cache
>>> cache.delete_pattern('_SETTING_*')
```

**Comment by lidfgab** [comment]
我们的测试结果是：如果先配置ldap再配置radius，怎么都不会去radius认证，如果重装只配置radius不配置ldap，那么从radius拉用户和认证没问题。
另外，思科ISE作为radius服务器测试通过

**Comment by ibuler** [comment]
有个缓存的问题，请按照一下命令处理后再试试

```
$ cd JUMPSERVER_DIR
$ cd apps
$ python manage.py shell
>>> from django.core.cache import cache
>>> cache.delete_pattern('_SETTING_*')
```
然后重启
