### ISSUE TITLE
windows 2016配置仅允许网络级别身份验证并将系统平台配置为Windows(2016)无法连接

### ISSUE THREAD

**Issue by kingsxw** [jumpserver/jumpserver#2460]
[简述你的问题]
系统为windows server 2016 std，开启远程桌面并配置仅允许运行使用网络级别的远程桌面的计算机连接。如果将对应资产的系统平台配置为Windows(2016)则无法连接，配置为Windows则可以连接。

##### 使用版本
1.4.8

##### 问题复现步骤
1. 开启仅允许网络级别身份验证，系统平台配置为Windows(2016)无法连接，配置为Windows可以连接。
2. 关闭仅允许网络级别身份验证，系统平台配置为Windows(2016)可以连接，配置为Windows也可以连接。

##### 具体表现[截图可能会更好些,最好能截全]
以下为无法连接的截图
![image](https://user-images.githubusercontent.com/15606960/53717704-f8651700-3e93-11e9-838f-865700cd8773.png)

##### 其他
虽然有说明，Windows 2016的RDP协议与之前不同，如果是请设置，但是配置成Windows依然可以使用，区别就是Windows下桌面背景为黑屏，Windows(2016)下不是黑屏，其他暂时没看出来。
因为公司安全要求必须开启仅允许网络级别身份验证，所以暂时先配置成Windows了，不知道配置成Windows是否会存在其他问题？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不会有其他问题
