### ISSUE TITLE
输入id直接登录，当服务器列表大于9时，以后的服务器如何通过id登录

### ISSUE THREAD

**Issue by jaikewhh166** [jumpserver/jumpserver#2463]
[简述你的问题]

输入id直接登录，当服务器列表大于9时，以后的服务器如何通过id登录

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

jumpserver 4.6
##### 问题复现步骤
1. [步骤1]
 在id列表，当输入1时，就直接登录了id为1 的服务器
 无法输入10，来登录id为10的服务器？

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
最新版本已修复
