### ISSUE TITLE
celery进程导致单核cpu跑满

### ISSUE THREAD

**Issue by zhuzw1015** [jumpserver/jumpserver#2464]
[简述你的问题]
服务器配置：8核16G
问题：单核CPU跑满
进程：/data/jumpserver_data/py3/bin/python3.6 -m celery worker -A ops -l error --autoscale 20,4 --logfile=/data/jumpserver_data/jumpserver/logs/celery.log --pidfile=/data/jumpserver_data/jumpserver/tmp/celery.pid

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.6-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/29407574/53774839-10d44080-3f2b-11e9-9c4d-f8eefced823f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
celery是执行任务的进程，比如 定时测试资产的连接性，推送用户，如果celery进程一直没有结束证明，任务没有结束，是不是有些资产无法连接上，或者 资产数量比较多

**Comment by zhuzw1015** [comment]
设备数量较多，网络不稳定，部分资产会出现失联情况



zhuzw1015@126.com
 
发件人： 老广
发送时间： 2019-03-09 15:14
收件人： jumpserver/jumpserver
抄送： zhuzw1015; Author
主题： Re: [jumpserver/jumpserver] celery进程导致单核cpu跑满 (#2464)
celery是执行任务的进程，比如 定时测试资产的连接性，推送用户，如果celery进程一直没有结束证明，任务没有结束，是不是有些资产无法连接上，或者 资产数量比较多

**Comment by Sandra299** [comment]
我也遇到同样的问题，主要是资产数量比较多，请问对celery的CELERYD_MAX_TASKS_PER_CHILD进行设置能否解决问题呢？同时还遇到了资产数量较多的用户连接慢的问题，查了下用户登陆coco之后会自动获取这个用户的所有资产，从而导致时间过长，请问像这样的问题有没有什么比较好的解决方案呢？ @ibuler

**Comment by ibuler** [comment]
同时还遇到了资产数量较多的用户连接慢的问题，查了下用户登陆coco之后会自动获取这个用户的所有资产，从而导致时间过长，请问像这样的问题有没有什么比较好的解决方案 

这问题已修复
