### ISSUE TITLE
是否支持google oauth

### ISSUE THREAD

**Issue by lishuaisky** [jumpserver/jumpserver#2468]
[简述你的问题]

是否支持google oauth
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lishuaisky http://docs.jumpserver.org/zh/docs/faq_mfa.html

**Comment by laohyx** [comment]
您好，faq_mfa是指两步验证吗？

我想知道google oauth或者其它第三方网站的oauth是否可以集成？因为想把jumpserver的账号使用公司账号同步。

谢谢！
