### ISSUE TITLE
邮件设置后，测试连接报错，提示信息为乱码

### ISSUE THREAD

**Issue by lnngle** [jumpserver/jumpserver#2469]
[简述你的问题]
在“邮件设置”界面设置好后，点击“测试连接”，提示信息为乱码:
{"error":"(501, b'\\xcf\\xb5\\xcd\\xb3\\xd2\\xd1\\xc7\\xbf\\xd6\\xc6\\xbf\\xaa\\xc6\\xf4\\xd5\\xca\\xba\\xc5\\xc9\\xfd\\xbc\\xb6\\xc9\\xe8\\xd6\\xc3\\xa3\\xac\\xc7\\xeb\\xb5\\xc7\\xc2\\xbcexmail.qq.com\\xb0\\xf3\\xb6\\xa8\\xce\\xa2\\xd0\\xc5', 'xxx@xxx.com')"}

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lnngle 页面截个图看看

**Comment by jym503558564** [comment]
请问问题是否已解决？
如果还未解决，能否截图复现看看？

**Comment by jym503558564** [comment]
如问题还存在，可重新提issues. 附带详细信息
