### ISSUE TITLE
资产机器能否主动向jumpserver发起连接

### ISSUE THREAD

**Issue by hanhongshen** [jumpserver/jumpserver#247]
资产机器在内网环境下，外网又不能做静态映射，能否实现资产主动向jumpserver发送连接消息，让jumpserver能否记录其外网地址和端口，实现类似NAT的功能。

**Comment by liuzheng712** [comment]
既然在外网了，正常操作即可啊

**Comment by hanhongshen** [comment]
问题是资产机器都是内网

**Comment by liuzheng712** [comment]
你的意思是你的资产机的外网ip是动态的？
给你的建议是使用域名，然后用这个https://github.com/liuzheng712/ddns 
让他自动update 域名

**Comment by ibuler** [comment]
same with #433
