### ISSUE TITLE
希望给命令执行增加保存命令的功能

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#2471]
[简述你的问题]
**需求场景：**
批量修改系统设置
经常需要执行更新程序的命令

添加保存命令功能，添加好命令后，可以在命令执行页面选择对应的命令项进行批量执行。

##### 使用版本
1.4.7

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@HuanMeng0 自定义任务模块还在制作中，请等待后续的功能更新
