### ISSUE TITLE
配置ldap之后测试成功 但是无法通过ldap登录

### ISSUE THREAD

**Issue by chenyanter** [jumpserver/jumpserver#2472]
[简述你的问题]
配置ldap之后测试成功
但是无法通过ldap登录

##### 使用版本
[使用的Jumpserver版本 1.4.8]

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/9622326/53897465-26538280-4071-11e9-9fef-8e1a8d72f237.png)

2. [步骤2]
![image](https://user-images.githubusercontent.com/9622326/53897530-4b47f580-4071-11e9-870c-bba0ce835c71.png)

##### 其他
openldap中组信息如下
# 条目 1: cn=users,cn=jumpserver,ou=groups,dc=qq,dc=com
dn: cn=users,cn=jumpserver,ou=groups,dc=qq,dc=com
cn: users
description: users
member: cn=testme,ou=people,dc=qq,dc=com
objectclass: groupOfNames
objectclass: top
ou: users

openladp中该用户的信息如下
# 条目 1: cn=testme,ou=people,dc=qq,dc=com
dn: cn=testme,ou=people,dc=qq,dc=com
cn: testme
description: User account
dialupaccess: access_attr
displayname: testme
mail: testme@qq.com
mobile: 18600000000
objectclass: inetOrgPerson
objectclass: top
objectclass: radiusprofile
radiususerpassword: ******
sn: testme
userpassword: {SSHA}*******

日志输出如下
2019-03-07 00:31:19 [backend WARNING] Caught LDAPError while authenticating testme: INVALID_CREDENTIALS({'desc': 'Invalid credentials'},)
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chenyanter 用户过滤器还原成默认设置

**Comment by chenyanter** [comment]
(cn=%(user)s)
写成这样还是不行

**Comment by chenyanter** [comment]
> @chenyanter 用户过滤器还原成默认设置
(cn=%(user)s)
写成这样还是不行
另外发现，配置ldap那里，测试成功过之后，我这里即使把密码改错了，测试的时候仍然可以找到用户，这块可能真的有点问题呢

**Comment by zhouhoujia** [comment]
我遇到一样的问题，LDAP测试通过，但是根本登录不了。排查发现是results = search.execute(self.connection, {'user': self._username})
 这串代码根本过不了，报错误{'desc': "Can't contact LDAP server", 'info': 'error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (self signed certificate in certificate chain)'}

你解决了嘛

**Comment by chenyanter** [comment]
重启了服务器，貌似好了，我也不知道为啥，好担心后面再出问题

**Comment by zhouhoujia** [comment]
终于解决了。这货就代码写错了，还少了参数。今天一天都在看这个问题，终于解决了，不然都不能上线用

**Comment by wojiushixiaobai** [comment]
如果之后还有问题请再打开问题，我先关闭了。

**Comment by chenyanter** [comment]
@zhouhoujia 
那里写错了，能说一下么，我这边部署了一套新环境，又遇到了同样的问题

**Comment by wojiushixiaobai** [comment]
@chenyanter QQ上加我：296015668 ，远程协助你解决下

**Comment by douchen** [comment]
能说说最后是怎么解决的吗？我也遇到这个问题了

**Comment by douchen** [comment]
最后加群解决问题了，一般这种能够测试通过也能够导入用户的，但是登录出错的，原因大多是DN没写对！
