### ISSUE TITLE
更新资产硬件信息报错

### ISSUE THREAD

**Issue by lishuaisky** [jumpserver/jumpserver#2474]
[简述你的问题]
更新资产硬件信息报错

##### 使用版本
[1.4.8]
1. 更新资产硬件信息报错

TASK [ping] ********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: b'ssh'
fatal: [v2-ssr-kcs-ap2]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
2019-03-07 12:42:32 任务结束

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
没有ssh命令？

**Comment by jym503558564** [comment]
问题是否已解决？

**Comment by qizai123** [comment]
systemctl启动程序：
务必Environment变量中包含ssh路径，参考其他文章只写了PATH=/opt/py3/bin，所以找不到SSH
正确如下（按实际修改）：
Environment="PATH=/opt/py3/bin:/data1/nginx/current/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin"
