### ISSUE TITLE
命令过滤功能漏洞 - shell 脚本绕过

### ISSUE THREAD

**Issue by bottlelee** [jumpserver/jumpserver#2479]
[用户可以通过编写 shell 脚本绕过过滤]

##### 使用版本
1.4.8

##### 问题复现步骤
1. 命令过滤里设置禁用 last 命令
2. 通过 Jumpserver 登录到目标机，执行 last 命令，提示“被禁用”
3. 编写 shell 脚本 test.sh，内容如下：
```
#!/bin/sh
last
```
4. 执行 test.sh 成功。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3996146/53950462-2bfba780-4107-11e9-92fa-1bf553151a9b.png)

##### 其他
看来只能监控键盘的输入，不能监控脚本的命令调用咯？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
系统层需要agent的支持吧，目前的做法只是在前端拦截用户的输入！

**Comment by liuzheng** [comment]
你好，这个恶意绕过监测的方式已经被堡垒机捕获了恶意行为，已经可以追溯了。
堡垒机无法对于此类恶意行为进行阻止，其实还有更多的绕过方式，想要完全达到禁止需要结合kernel做到这些事情

**Comment by bottlelee** [comment]
谢谢回复，谢谢 Jumpserver 的开源贡献。
