### ISSUE TITLE
控制台更换字体

### ISSUE THREAD

**Issue by xiaooloong** [jumpserver/jumpserver#248]
现在的控制台字体非等宽，很多排版输出的命令运行起来界面异常

是否支持自定义控制台字体

**Comment by jiaxiangkong** [comment]
templates/jlog/web_terminal.html   代码第14行

**Comment by xiaooloong** [comment]
```
font-family: "Times New Roman", Times, serif;
```
去 http://www.w3schools.com/cssref/css_websafe_fonts.asp 抄了行，观感良好
