### ISSUE TITLE
自动添加资产，资产列表里的资产数量显示不正确（资产已添加进去）

### ISSUE THREAD

**Issue by kenken2018** [jumpserver/jumpserver#2480]
[简述你的问题]
自己写的脚本，调用api接口，资产已添加进资产中去
但资产列表里的资产数的数量显示不正确

##### 使用版本
1.4.5

##### 问题复现步骤
1. 自动扫描资产，使用Asset.objects.create加进去
2. 资产正常加进去了，但，资产数的数量没有改变

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
右击节点，有个刷新菜单，因为计算节点下的数量涉及到递归查询，比较耗费资源，所以加入了缓存

![image](https://user-images.githubusercontent.com/17382885/54067659-8454b580-427d-11e9-97c3-72de9b4b35d7.png)
