### ISSUE TITLE
celery进程太多，导致服务器资源占用太大

### ISSUE THREAD

**Issue by vito16** [jumpserver/jumpserver#2482]
使用jms start all后，系统资源占用比较大，有很多命令为`/opt/py3/bin/python3.6 -m celery worker -A ops`的进程，最少几十个相同进程，这个问题如何解决？

##### 使用版本
1.4.8

##### 问题复现步骤
1. ./jms start all
2. top

##### 具体表现
![celery](https://user-images.githubusercontent.com/746789/53959263-278eb900-411e-11e9-9680-9951c82cbae8.png)

##### 其他
无

**Comment by ibuler** [comment]
可能是任务比较多，celery动态维护进程数量，4-20个

**Comment by ibuler** [comment]
建议安装一个flower，查看后台运行的任务
https://flower-docs-cn.readthedocs.io/zh/latest/index.html
