### ISSUE TITLE
多认证方式支持

### ISSUE THREAD

**Issue by lidfgab** [jumpserver/jumpserver#2483]
[简述你的问题]
jumpserver是否能添加多认证方式支持。
比如我同时配置LDAP认证和radius认证，我通过LDAP协议拉过来用户之后通过radius协议对用户做认证。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
理论上可以的

**Comment by lidfgab** [comment]
测试过，至少现在不行~

**Comment by ibuler** [comment]
或许存在一个bug，请qq联系我

**Comment by ibuler** [comment]
有个缓存的问题，请按照一下命令处理后再试试
```
$ cd JUMPSERVER_DIR
$ cd apps
$ python manage.py shell
>>> from django.core.cache import cache
>>> cache.delete_pattern('_SETTING_*')
然后重启
```
如上 @lidfgab

**Comment by ivansun1994** [comment]
想问下多认证如何配置@lidfgab @ibuler

**Comment by ibuler** [comment]
有问题重新打开
