### ISSUE TITLE
jumpserver迁移后，启动gunicorn进程不起来，显示为‘0’

### ISSUE THREAD

**Issue by coologin** [jumpserver/jumpserver#2484]
[简述你的问题]
通过模板方式，把jumpserver迁移后，后发现启动gunicorn进程不起来。ps没有发现进程，8080端口没有。
开启debug模式后，./log下也无gunicorn.log日志，
验证mysql,redis都正常，可以连接。

(py3) [root@jpsvr jumpserver]# ./jms start all -d
Fri Mar  8 17:50:35 2019
Jumpserver version 1.4.7
**gunicorn is running: 0      ----此处为0**

- Start Celery as Distributed Task Queue

- Start Beat as Periodic Task Scheduler

gunicorn is running: 0
celery is running: 3969
beat is running: 3971

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1，迁移后，改动了IP，但配置中绑定127.0.0.1

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@coologin 迁移之前一定要确认已经停止jms及相关服务。
处理方法：

    $ cd /opt/jumpserver/
    $ source /opt/py3/bin/activate
    $ ./jms stop
    $ rm -rf /opt/jumpserver/tmp/*
    $ ./jms start all

**Comment by ibuler** [comment]
最简单可以前台启动看看报不报错

```
./jms start gunicorn
```

**Comment by coologin** [comment]
> 
> 
> @coologin 迁移之前一定要确认已经停止jms及相关服务。
> 处理方法：
> 
> ```
> $ cd /opt/jumpserver/
> $ source /opt/py3/bin/activate
> $ ./jms stop
> $ rm -rf /opt/jumpserver/tmp/*
> $ ./jms start all
> ```
估计是要删除rm -rf /opt/jumpserver/tmp/*  ，发现只有gunicorn.pid是空的

删除后就发现有ID了，不再是0，

**Comment by wojiushixiaobai** [comment]
@coologin 原因是迁移之前未正常结束gunicorn进程导致，下次请注意。问题先关闭了，有问题再重新提交
