### ISSUE TITLE
debian 7 安装不了

### ISSUE THREAD

**Issue by jqlinux** [jumpserver/jumpserver#249]
[root@jqlinux:] /opt/jumpserver/install# python2.7 install.py 
请务必先查看wiki https://github.com/jumpserver/jumpserver/wiki
支持的平台: CentOS, RedHat, Fedora, Debian, Ubuntu, Amazon Linux, 暂不支持其他平台安装.

<pre>
>>> import platform
>>> platform.linux_distribution(supported_dists=['system'])[0].lower()
''
>>> print platform.linux_distribution(supported_dists=['system'])[0].lower()

>>> print platform.linux_distribution(supported_dists=['system'])
('', '', '')
</pre>

如果修改为：
<pre>
>>> print platform.linux_distribution()[0].lower()
debian
</pre>

**Comment by jiaxiangkong** [comment]
安装脚本 己更新
