### ISSUE TITLE
1.4.4升级到1.4.8

### ISSUE THREAD

**Issue by chen0267** [jumpserver/jumpserver#2490]
[简述你的问题]
1.4.4升级到1.4.8最新版，资产和账户丢失。

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.4 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. sh 1.4.4_to_1.4.5_migrations.sh 报错，提示缺少django_migrations表。
2. 参照升级常见问题，增加jumpserver01库，然后执行 sh 1.4.4_to_1.4.5_migrations.sh 顺利通过，没有报错。
3. ./jms start all -d   启动得到1.4.8版本，但是资产、账户都丢失了。
期间有报数据库错误，如下图。
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48468053/54179093-ba3ea780-44d2-11e9-8da0-2a37e2b828af.png)

**Comment by wojiushixiaobai** [comment]
@chen0267 丢表了，升级不会导致丢失信息，你1.4.4的config.py内容截图

**Comment by chen0267** [comment]
1.4.4资产只支持IP，我修改一下判断，可以支持域名，不知道和这个有关吗？ 很久以前改的，现在忘记了... @wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
@chen0267 从你的配置文件来看，你的数据是保存在默认的sqlite3下，而不是mysql里面，请还原，并把数据导入到mysql后继续升级

**Comment by jym503558564** [comment]
问题是否已解决？
