### ISSUE TITLE
使用nano编辑文件无法保存

### ISSUE THREAD

**Issue by 502647092** [jumpserver/jumpserver#2493]
[简述你的问题]

终端使用nano编辑文件的时候 无法保存
原本操作是 Ctrl + X 然后按Y 按回车保存
但是在Luna的终端里 最后一下回车没法操作 按了没反应

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.2-101 GPLv2.

##### 问题复现步骤
1. 使用Luna链接Linux服务器
2. 使用nano打开文件 任意编辑 然后进行保存操作

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10203793/54248123-700f0200-4576-11e9-816a-ec380524b441.png)

**Comment by wojiushixiaobai** [comment]
@502647092 请更新版本，旧版本尚未验证此问题是否存在，但是新版本无此问题

**Comment by 502647092** [comment]
> @502647092 请更新版本，旧版本尚未验证此问题是否存在，但是新版本无此问题

我拉取的是最新的 `jumpserver/jms_all` 镜像

**Comment by wojiushixiaobai** [comment]
@502647092  emm，1.4.2的时候我记得我没有做过镜像呀
