### ISSUE TITLE
Centos7.5安装guacamole出错

### ISSUE THREAD

**Issue by xiaofeng283** [jumpserver/jumpserver#2494]
[简述你的问题]
完全根据文档的安装步骤，安装到guacamole时，运行make && make install报错

Making all in src/guacd
make[2]: 进入目录“/opt/docker-guacamole/guacamole-server-0.9.14/src/guacd”
  CCLD     guacd
guacd-daemon.o: In function `main':
/opt/docker-guacamole/guacamole-server-0.9.14/src/guacd/daemon.c:371: undefined reference to `OPENSSL_init_ssl'
/opt/docker-guacamole/guacamole-server-0.9.14/src/guacd/daemon.c:372: undefined reference to `OPENSSL_init_ssl'
/opt/docker-guacamole/guacamole-server-0.9.14/src/guacd/daemon.c:373: undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status
make[2]: *** [guacd] 错误 1
make[2]: 离开目录“/opt/docker-guacamole/guacamole-server-0.9.14/src/guacd”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/opt/docker-guacamole/guacamole-server-0.9.14”
make: *** [all] 错误 2

##### 使用版本
安装版本为Jumpserver1.4.8，查看OpenSSL安装版本为1.1.1

##### 问题复现步骤
$ cd /opt
$ git clone https://github.com/jumpserver/docker-guacamole.git
$ cd /opt/docker-guacamole/
$ tar -xf guacamole-server-0.9.14.tar.gz
$ cd guacamole-server-0.9.14
$ autoreconf -fi
$ ./configure --with-init-dir=/etc/init.d
$ make && make install

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/20809418/54266565-99e61a00-45b2-11e9-8b98-7098ee7b5d91.png)
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaofeng283 可以用docker部署组件

**Comment by xiaofeng283** [comment]
用Docker部署后出现错误
![image](https://user-images.githubusercontent.com/20809418/54343971-f57bda80-467a-11e9-990e-2297a6f6125c.png)

然后根据安装文档，手动进容器再次配置了环境变量
![image](https://user-images.githubusercontent.com/20809418/54344057-23611f00-467b-11e9-8f6a-732fbd6bf22d.png)

还是一样的错误，麻烦帮忙看下

**Comment by xiaofeng283** [comment]
再次参考了https://github.com/jumpserver/jumpserver/issues/2342，查看token是一致的：
![image](https://user-images.githubusercontent.com/20809418/54344594-30324280-467c-11e9-87e3-73c16d4e66c8.png)

![image](https://user-images.githubusercontent.com/20809418/54344616-3aecd780-467c-11e9-829b-d6eb994b4782.png)

查看容器内/config/guacamole/keys没有产生

**Comment by wojiushixiaobai** [comment]
@xiaofeng283 容器不能使用127.0.0.1

**Comment by xiaofeng283** [comment]
这个已经改为实际IP了的：192.168.1.21:8080（Jumpserver安装）
![image](https://user-images.githubusercontent.com/20809418/54411904-d0937000-472b-11e9-90a8-c38f55317465.png)

**Comment by wojiushixiaobai** [comment]
还有问题吗？

**Comment by xiaofeng283** [comment]
是的 就是连不上 还是昨天的哪个问题

**Comment by wojiushixiaobai** [comment]
联系下我，我远程给你看下qq：296015668

**Comment by wojiushixiaobai** [comment]
镜像为旧镜像，已为用户解决，问题关闭
