### ISSUE TITLE
cocod卡慢问题

### ISSUE THREAD

**Issue by chenglu01** [jumpserver/jumpserver#2496]
[简述你的问题]
cocod占用cpu过高，导致卡慢现象，发现官方文档有针对组件负载的结局方案，使用docker方式，采用nginx代理tcp，但是我的jumpserver版本是1.3.3-2，官方文档给出的镜像是jms_coco:1.4.8，使用docker方式启动之后发现cocod在容器中没有启动起来，导致客户端连接直接就是端口断开连接

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver1.3.3-2
##### 具体表现[截图可能会更好些,最好能截全]
<img width="869" alt="图片" src="https://user-images.githubusercontent.com/15355034/54331237-08c77f80-4654-11e9-823c-e57bf5f92578.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by chenglu01** [comment]
使用docker logs jms_coco01 可以看到有报错
<img width="825" alt="图片" src="https://user-images.githubusercontent.com/15355034/54331400-ce121700-4654-11e9-8b1b-3fb4d613ecd5.png">

**Comment by wojiushixiaobai** [comment]
@chenglu01 尝试自己构建一个1.3.2的docker镜像，版本需要一致，不能跨版本
