### ISSUE TITLE
新建的资产树节点无法改名

### ISSUE THREAD

**Issue by houfirst2** [jumpserver/jumpserver#2501]
[简述你的问题]
新建资产输节点无法改名，只能是默认的新建节点1  新建节点2 ，如果更改就显示重命名失败，无法更改root节点名称，但是我该的不是root节点。。。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44460481/54419607-da749d80-4742-11e9-8646-d2ed71c39a57.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请勿修改或者在数据库修改

**Comment by jym503558564** [comment]
选中节点：右击重命名节点，节点名不能为空
![image](https://user-images.githubusercontent.com/40739051/58414337-a8ba7400-80ad-11e9-8b52-be5f8dfdf8e6.png)
