### ISSUE TITLE
无法进入web终端

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2503]
[简述你的问题]
登录jumpserver后，点击web终端，浏览器新标签页弹框提示“false 确定离开此页吗”，点击离开后会反复弹出次窗口，无限循环。
查看nginx的error日志，反复刷以下错误

> 2019/03/15 17:36:29 [warn] 18975#18975: *190 upstream server temporarily disabled while connecting to upstream, client: xx.xx.xx.xx, server: , request: "GET /users/login/?next=/luna/ HTTP/1.1", upstream: "http://[::1]:8080/users/login/?next=/luna/", host: "xx.xx.xx.xx", referrer: "http://xx.xx.xx.xx/luna/"
> 2019/03/15 17:36:41 [error] 18975#18975: *189 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: , request: "GET /users/login/?next=/luna/ HTTP/1.1", upstream: "http://[::1]:8080/users/login/?next=/luna/", host: "xx.xx.xx.xx", referrer: "http://xx.xx.xx.xx/luna/"

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
登录后点击web终端

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/9085824/54423557-e31da180-474b-11e9-8b02-9c62a8f9ce15.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zxq1002 暂未复现，能否详细说明下环境

**Comment by zxq1002** [comment]
OS是openSUSE Leap，python版本是3.6.8，安装过程没有问题，所有组件都在一台机器上，安装后可以正常启动登录，也能正常添加资产，刷新硬件信息，目前只发现命令执行和web终端有问题。还有其它日志可以定位具体原因吗？

**Comment by wojiushixiaobai** [comment]
@zxq1002 换个浏览器看看是否能复现
或者访问下demo网站 https://demo.jumpserver.org/luna/

**Comment by zxq1002** [comment]
升级到最新的chrome可以打开和连接主机了，不好意思，公司内网不能访问公网无法及时升级。
连接后执行命令在web终端中正常，但同时发现coco的日志有一些报错信息，似乎跟命令过滤有关？

> 2019-03-18 16:38:28 [models ERROR] multiple repeat at position 13
> Traceback (most recent call last):
>   File "/opt/coco/coco/models.py", line 327, in send
>     data = self.s_filter_cmd_filter(data)
>   File "/opt/coco/coco/models.py", line 257, in s_filter_cmd_filter
>     action, cmd = rule.match(self._input)
>   File "/opt/py3/lib64/python3.6/site-packages/jms/models.py", line 253, in match
>     found = self._pattern.search(data)
>   File "/opt/py3/lib64/python3.6/site-packages/jms/models.py", line 247, in _pattern
>     self.__pattern = re.compile(r'{}'.format('|'.join(regex)))
> File "/usr/lib64/python3.6/re.py", line 233, in compile
>     return _compile(pattern, flags)
>   File "/usr/lib64/python3.6/re.py", line 301, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
>     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/lib64/python3.6/sre_parse.py", line 619, in _parse
>     source.tell() - here + len(this))
> sre_constants.error: multiple repeat at position 13
