### ISSUE TITLE
命令执行抛异常

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2504]
[简述你的问题]
登录后点击命令执行菜单，任意选择一台或多台资产执行命令，例如 df -h，上方回显窗口出现异常信息

##### 使用版本
1.4.8

##### 问题复现步骤
1. 登录jumpserver，点击命令执行
2. 选择资产执行命令

##### 具体表现[截图可能会更好些,最好能截全]
回显日志如下：
> ---------- 任务开始 ----------
> Task ops.tasks.run_command_execution[30d10165-55a3-428b-9797-8eac266a199c] raised unexpected: error('multiple repeat at position 13',)
> Traceback (most recent call last):
>   File "/data/jumpserver-1.4.8/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/data/jumpserver-1.4.8/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/data/jumpserver-1.4.8/apps/ops/tasks.py", line 45, in run_command_execution
>     execution.run()
>   File "/data/jumpserver-1.4.8/apps/ops/models/command.py", line 61, in run
>     ok, msg = self.run_as.is_command_can_run(self.command)
>   File "/data/jumpserver-1.4.8/apps/assets/models/user.py", line 225, in is_command_can_run
>     action, matched_cmd = rule.match(command)
> File "/data/jumpserver-1.4.8/apps/assets/models/cmd_filter.py", line 81, in match
>     found = self._pattern.search(data)
>   File "/data/jumpserver-1.4.8/apps/assets/models/cmd_filter.py", line 75, in _pattern
>     self.__pattern = re.compile(r'{}'.format('|'.join(regex)))
>   File "/usr/local/python3.6.8/lib/python3.6/re.py", line 233, in compile
>     return _compile(pattern, flags)
>   File "/usr/local/python3.6.8/lib/python3.6/re.py", line 301, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/local/python3.6.8/lib/python3.6/sre_compile.py", line 562, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/local/python3.6.8/lib/python3.6/sre_parse.py", line 855, in parse
>     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/local/python3.6.8/lib/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/local/python3.6.8/lib/python3.6/sre_parse.py", line 619, in _parse
>     source.tell() - here + len(this))
> sre_constants.error: multiple repeat at position 13

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
![QQ20190318-101851](https://user-images.githubusercontent.com/24326988/54502757-40da0580-4967-11e9-904d-9578efeec403.jpg)
@zxq1002 检查下安装或者jms组件是否有问题

**Comment by zxq1002** [comment]
请问还以检查什么日志或者服务状态呢，目前情况是安装过程没有报错，启动也正常，也可以正常登录或者登记资产、刷新硬件信息等，但唯独命令执行和web终端不行

**Comment by wojiushixiaobai** [comment]
@zxq1002 检查系统用户的sudo是否有误

**Comment by zxq1002** [comment]
试了sudo没有问题，celery.log中的错误信息跟上面的贴出的一样

**Comment by zxq1002** [comment]
@wojiushixiaobai 去掉命令过滤就不报错了，是我设置的命令过滤规则有问题吗

**Comment by jym503558564** [comment]
目前问题是否还存在？

**Comment by zxq1002** [comment]
我把命令过滤规则删了，暂时不用，问题先关了把，谢谢

**Comment by jym503558564** [comment]
@zxq1002 可在新版本测试一下，目前无法复现您的问题场景。

**Comment by JusticeShi** [comment]
我也遇到这个问题，添加了命令过滤规则就会报这个错，删掉就不会了

**Comment by JusticeShi** [comment]
@jym503558564
