### ISSUE TITLE
VNC连接错误，请帮忙一下，谢谢！

### ISSUE THREAD

**Issue by fangweisi** [jumpserver/jumpserver#2509]
**[简述你的问题]**

在使用web终端时，连接vnc的windows主机出现无限等待连接和连接错误提示.

**使用版本**

Version 1.4.8-2 GPLv2.

**问题复现步骤**

**具体表现[截图可能会更好些,最好能截全]**

![图片](https://user-images.githubusercontent.com/39790074/54517403-8a911300-499c-11e9-8439-f65679073b1d.png)

![图片](https://user-images.githubusercontent.com/39790074/54517482-c6c47380-499c-11e9-89dd-5273fb33d114.png)

其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@fangweisi 参考https://demo.jumpserver.org/users/login/
该文档第2、5、6、8步

**Comment by fangweisi** [comment]
> 
> 
> @fangweisi 参考https://demo.jumpserver.org/users/login/
> 该文档第2、5、6、8步

不好意思，您的这个网站需要进行验证登录，我登录不了

**Comment by wojiushixiaobai** [comment]
抱歉，链接打错了，已更正

**Comment by fangweisi** [comment]
> 
> 
> 抱歉，链接打错了，已更正

你好，你新给出的连接是说明RDP的，我的问题是VNC，谢谢

**Comment by wojiushixiaobai** [comment]
@fangweisi 确定网络没有问题，rdp和vnc都使用guacamole
在vnc服务器检查防火墙及selinux
单独启动一个新的vncserver
    $ vncserver :2  # :2 表示 5902，如果端口被占用往后推
    # 然后根据提示输入密码
在web更新端口为5902
在系统用户添加的vnc协议用户，账户为空，密码为你刚才设置的密码
重新登录

**Comment by wojiushixiaobai** [comment]
@fangweisi 已验证是加密问题，请去掉加密或者更换vnc服务软件
