### ISSUE TITLE
挂载通过jumpserver连接的另一个服务器到本地

### ISSUE THREAD

**Issue by ZhangAllen98** [jumpserver/jumpserver#2514]
如果可以直连服务器A（ipA）的时候，可直接sshfs user@ipA 将服务器相应文件目录挂载到本地，
但是通过jumpserver（ipB）连接的时候，应该怎么操作才能实现挂载呢？
现在的情况是通过ssh user@ipB -p 2222 可登录到一个选项界面，通过”输入 ID 直接登录 或 输入部分 IP,主机名,备注 进行搜索登录“，可登录ipA的服务器，但是没法实现sshfs挂载。

**Comment by ibuler** [comment]
jumpserver内部是不允许登录的，所以没法挂载
