### ISSUE TITLE
用户初始化密码问题以及批量修改用户密码

### ISSUE THREAD

**Issue by yuynagforhacker** [jumpserver/jumpserver#2517]
遇到一个问题，当我批量导入用户的时候，用户的初始密码是什么？

然后又遇到了第二个问题，我想把所有导入的用户批量改一个初始密码，但是批量更新操作里只能改组，没有密码方面的操作

那么在导入的时候我也找了找，模板里也没有密码方面的设置，那么导入的用户该怎么登录？

**Comment by tgyday** [comment]
python manage.py changepassword

**Comment by wojiushixiaobai** [comment]
@yuynagforhacker 通过修改表单支持批量密码修改
或者设置好邮件服务，让用户通过忘记密码自行修改。
通过数据库统一设置。
任选其一即可
