### ISSUE TITLE
jumpserver能否支持多标签搜索

### ISSUE THREAD

**Issue by tuyula** [jumpserver/jumpserver#2520]
[简述你的问题]
我们有很多标签，比如阿里云的标签,腾讯云的标签,zabbix的标签
1.我们想查看在腾讯云,有zabbix的标签的主机,却发现只有一个标签

**Comment by jym503558564** [comment]
目前只支持单标签搜索

**Comment by jym503558564** [comment]
例如：
要查询资产同时包含a标签和b标签，则可以在搜索框搜索多个标签。不用标签之间用空格隔开
格式为： a:a b:b
![image](https://user-images.githubusercontent.com/40739051/59249269-f19a2d00-8c56-11e9-885a-91a11e87e74e.png)
![image](https://user-images.githubusercontent.com/40739051/59249321-0971b100-8c57-11e9-9ca6-f1d293b55723.png)
![image](https://user-images.githubusercontent.com/40739051/59249362-1db5ae00-8c57-11e9-965e-aceeb7234f8e.png)

**Comment by jym503558564** [comment]
请问这样是否能解决您的问题？

**Comment by tuyula** [comment]
应该能的

**Comment by tuyula** [comment]
你好客气哈

**Comment by jym503558564** [comment]
好的，感谢反馈～

**Comment by xuchenCN** [comment]
@jym503558564 这个功能貌似不能用
