### ISSUE TITLE
在创建系统用户的时候，上传ssh私钥提示ssh秘钥不合法

### ISSUE THREAD

**Issue by Jerrywgl** [jumpserver/jumpserver#2522]
[简述你的问题]

##### 使用版本
1.4.8
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/43428100/54737267-0d5add80-4bea-11e9-9332-95a57477cf98.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Jerrywgl** [comment]
![image](https://user-images.githubusercontent.com/43428100/54737313-41ce9980-4bea-11e9-96ff-a9ab7bc6a06d.png)

**Comment by Jerrywgl** [comment]
这个秘钥没有密码，在新用户上传秘钥和更新已有用户上传秘钥汇报这个提示，有排查的思路吗？

**Comment by jym503558564** [comment]
ssh密钥格式是否正确

**Comment by Joen1750** [comment]
使用有密码的私钥的使用总提示秘钥不合法，无密码的却可以完成提交，请教如何排查？

**Comment by ibuler** [comment]
不支持 OPENSSH 格式的秘钥

**Comment by ibuler** [comment]
可以升级到 1.5.2，已经有明确提示
