### ISSUE TITLE
请问 API 文档在哪里？

### ISSUE THREAD

**Issue by rrfeng** [jumpserver/jumpserver#2528]
官方网站只有一个 RESTful 约定，和一篇『如何调用 API』，那具体可用的 API 列表在哪里呢？API 参数定义等？

**Comment by ibuler** [comment]
运行起来项目后，配置文件开启DEBUG

然后访问 http://localhost:8080/docs

**Comment by rrfeng** [comment]
这里不是跟：
https://jumpserver.readthedocs.io/zh/docs/user_api.html

一样吗？也没有具体 API 的说明

**Comment by wangycc** [comment]
官网应该放一个
