### ISSUE TITLE
启用MFA后有没有Windows的客户端可以支持SFTP传输？

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2531]
[简述你的问题]
命令行sftp登录可以输入MFA验证码交互登录，但似乎sftp工具连不上

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by mushanzi1216** [comment]
使用系统:   mac系统
使用版本：jumpserver 版本 1.4.6
使用工具: iterm2
问题复现步骤
     1 iterm通过sshpass 设置自动登录 
     2 未开启mfa时 直接登录成功
      
![image](https://user-images.githubusercontent.com/6134260/59746413-76b1c180-92a9-11e9-8d8b-724e54bcd84b.png)
    3开启mfa后  弹出mfa输入框
     
![image](https://user-images.githubusercontent.com/6134260/59746473-934df980-92a9-11e9-9411-1f527484e5c8.png)
   输入后无效

   4 使用secureCRT 可正常访问

**Comment by ibuler** [comment]
xshell secretCRT都可以
