### ISSUE TITLE
置错误的ldap导致无法登录

### ISSUE THREAD

**Issue by bookgh** [jumpserver/jumpserver#2533]
网页端配置错误的ldap导致无法登录请问在哪里关闭

**Comment by amoscx** [comment]
我遇到过这问题，这种情况下普通用户登录会显示500错误，但本地管理员还能登录

**Comment by bookgh** [comment]
我当时用本地管理员依旧不能登录, 当时直接恢复的快照 放弃使用ldap方式

**Comment by ibuler** [comment]
目前有个脚本 https://github.com/jumpserver/jumpserver/blob/master/utils/disable_ldap_auth.sh
