### ISSUE TITLE
web 终端 出现 No existing session

### ISSUE THREAD

**Issue by damoyelang1992** [jumpserver/jumpserver#2534]
##### 问题简述

用了两个月的 jumpserver 突然出现  `No existing session`, 同时文件管理也出现 `Can not connect asset sftp server: No existing session` 我猜测是 coco 的问题,  所以重启了 coco 问题消失.

##### 使用版本

Version 1.4.6-2 GPLv2

##### 问题复现步骤

问题尚未重现, 似乎无法手动重现

##### 具体表现[截图可能会更好些,最好能截全]
![问题截图](https://s2.ax1x.com/2019/03/25/AtPouV.png)

**Comment by jym503558564** [comment]
收集一下报错日志贴出来。
也可更新一下版本，看是否还会复现此问题。
