### ISSUE TITLE
登录主机变慢以及不支持快捷键

### ISSUE THREAD

**Issue by rrfeng** [jumpserver/jumpserver#2536]
[简述你的问题]
从 0.x 版本升级后，ssh 登录到 jumpserver 的界面没有原来的好用了。

##### 使用版本
[1.4.6]

##### 问题复现步骤
1. 正常添加主机，用户，使用 ssh 登录 jumpserver。
2. 输入主机名（假设 host-a ）登录
3. 退出
4. 重新登录上一个主机

##### 具体表现[截图可能会更好些,最好能截全]
1. 登录变慢，显示正在连接...... 也要 1s 之后才能连上。0.x 版本是秒连的。没有网关，内网直连。
2. 方向键往上翻页不能翻到上一条输入，只会显示 `[[A`，ctrl-w，crtl-b 等按键也都不能使用了。

##### 其他
无

**Comment by jym503558564** [comment]
1.5.0已修复

**Comment by rrfeng** [comment]
不支持快捷键的问题并没有修复。
