### ISSUE TITLE
Jumpserver管理员帐号登录Web会话不过期

### ISSUE THREAD

**Issue by chenglu01** [jumpserver/jumpserver#2537]
[简述你的问题]

使用Jumpserver管理员帐号登录jumpserver的web页面，发现回话始终可用，输入一次帐号密码后，就可以一直处于登录状态，这个怎么破，在安全方面这个是不可避免的问题，求助

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.3.3-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

<img width="423" alt="图片" src="https://user-images.githubusercontent.com/15355034/54968108-76f53600-4fb4-11e9-9886-2915e5bc96db.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chenglu01 请设置浏览器过期，1.3.3在jumpserver/apps/jumpserver/settings.py
第122行

    SESSION_COOKIE_AGE = CONFIG.SESSION_COOKIE_AGE or 3600 * 24
    # 表示1天后cookie才会失效

    # 可修改成
    SESSION_COOKIE_AGE = SESSION_EXPIRE_AT_BROWSER_CLOSE True
    # 表示关闭浏览器cookie失效

**Comment by chenglu01** [comment]
> @chenglu01 请设置浏览器过期，1.3.3在jumpserver/apps/jumpserver/settings.py
> 第122行
> 
> ```
> SESSION_COOKIE_AGE = CONFIG.SESSION_COOKIE_AGE or 3600 * 24
> # 表示1天后cookie才会失效
> 
> # 可修改成
> SESSION_COOKIE_AGE = SESSION_EXPIRE_AT_BROWSER_CLOSE True
> # 表示关闭浏览器cookie失效
> ```

感谢回答，问题解决了
不过我修改为：SESSION_COOKIE_AGE = SESSION_EXPIRE_AT_BROWSER_CLOSE True这个时候，启动报错，提示我语法有误，不知道是不是因为版本的原因，我根据你的提示修改为：
SESSION_COOKIE_AGE = CONFIG.SESSION_COOKIE_AGE or 600 * 1
表示10分钟会话超时，目前满足需求，感谢！！！
