### ISSUE TITLE
是否有只读用户权限，专门用来查看录像

### ISSUE THREAD

**Issue by sherlockren3333** [jumpserver/jumpserver#2540]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
目前已增加审计员角色专门审计权限～
可更新版本～
