### ISSUE TITLE
LDAP接入AD后无法登录

### ISSUE THREAD

**Issue by 786951355** [jumpserver/jumpserver#2543]
[简述你的问题]
在设置中配置好AD的信息，测试匹配了对应OU中的多个账号，然后也能导入成功，但是在登录的时候查看日志揭示“[backend WARNING] Caught LDAPError while authenticating “我的ldap用户名”: LDAPError(0, 'Error')”

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/8830332/55044973-36122580-5077-11e9-97cd-961cb2b9f00e.png)

日志提示：
[backend WARNING] Caught LDAPError while authenticating `ldap的账号`: LDAPError(0, 'Error')
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@786951355 确定dn无误

**Comment by 786951355** [comment]
dn没问题的，我的很多其他系统都接入AD正常使用。

**Comment by yaoluoye** [comment]
'name': 'displayName'，试试这个

**Comment by 786951355** [comment]
> 'name': 'displayName'，试试这个

不行，应该不是ldap的配置问题。

**Comment by mixsome** [comment]
同样的问题  在其他使用LDAP的系统都是正常  只有jumpserver报错 Caught LDAPError while authenticating dushuai: INVALID_CREDENTIALS({'desc': 'Invalid credentials'},)

**Comment by ibuler** [comment]
ldap只可能存在配置的问题，目前很多用户使用了，没有该问题

**Comment by maxianwei** [comment]
我也遇到这个问题了， 在其他使用LDAP的系统比如rabbitmq正常， 但是jumpserver报 Caught LDAPError while authenticating dushuai: INVALID_CREDENTIALS({'desc': 'Invalid credentials'},) 上午还正常使用呢，下午突然不行了。

**Comment by 786951355** [comment]
> 我也遇到这个问题了， 在其他使用LDAP的系统比如rabbitmq正常， 但是jumpserver报 Caught LDAPError while authenticating dushuai: INVALID_CREDENTIALS({'desc': 'Invalid credentials'},) 上午还正常使用呢，下午突然不行了。

我现在依旧不能接入，我猜测是我们的AD是2008R2，新建用户没有邮箱这个属性，而jumpserver必须要有邮箱这个字段，导致对接不上，内部其他五六个系统都在使用AD对接没问题，因为不涉及到邮箱这个字段。
