### ISSUE TITLE
jumpserver是否支持二级管理员，可以分担任务

### ISSUE THREAD

**Issue by ahhqlrg** [jumpserver/jumpserver#2546]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ahhqlrg 
[组织及组织管理员说明文档](http://docs.jumpserver.org/zh/docs/faq_org.html)

**Comment by journeyto0405** [comment]
兄台，这个有操作么，用上了没? @ahhqlrg

**Comment by jym503558564** [comment]
组织管理员可咨询商业版，如有其它问题，可重新打开issues
