### ISSUE TITLE
OpenID Connect (oidc) 兼容性问题

### ISSUE THREAD

**Issue by eastpiger** [jumpserver/jumpserver#2549]
你好，我们团队最近在尝试使用oidc来登陆jumpserver，很感谢最近几个月对这个功能的支持。但是使用过程中有很多问题在这里反馈一下

1. 没有文档

如果不是读了一下代码，真没注意还有oidc的支持

2. keyclack和keyclack-client硬编码url导致兼容性问题

对于Django而言，有很多不错的oidc client实现，Python环境下类似的轮子也很多。我不是很清楚为什么开发者团队会选择keyclack，这两个库均试用了大量硬编码URL路径，而其值并不合适。
比如，对于所有oidc请求路径，keyclack的处理是这样的

realms/{realm_name}/.well–known........

并且将realm name作为一个参数处理。

然而事实上，oidc并没有要求url必须以这样的规则编码，很多oidc提供商按要求提供的是/.well-known.....这样的地址（比如Microsoft Azure AD OpenID and OAuth）。这种写法在常用的Django oidc client里也是十分罕见地。这样就导致了所有url不是realms开头的服务无法接入。

事实上，我们的团队最终只得选择自己维护了上述两个库的fork版本，确保应用的连接。

3. jumpserver对scope硬编码为code

这个问题很显然了，对于不同的提供者，scope是不同的。大多数oidc client的常规操作应当是将其设为选项，而非硬编码进来。

以Azure为例，这里要求的scope就是openid了。

很感谢你们提供这么好的项目。

如果后面有时间，我们可能会push过来我们团队的修改（不过目前还没work）

##### 使用版本
master最新

##### 问题复现步骤
使用Azure AD OIDC连接可复现上述所有问题

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@eastpiger 需求已经反馈到团队，感谢您的建议

**Comment by lilithGao** [comment]
同用Azure遇到了一样的问题

**Comment by ibuler** [comment]
欢迎 PR

**Comment by ibuler** [comment]
因为我司另外一个产品内部集成了keycloak

**Comment by eastpiger** [comment]
难怪。

我们之前做了个换oidc客户端的半成品，然后我们的运维团队上了ldap协议就没再继续完善

**Comment by eastpiger** [comment]
Django oidc客户端的话，我们一般严格用oidc_rp，这个对标准oidc协议的支持和兼容比较好。
感觉你们现在的实现称不上oidc兼容，可以说是keycloak兼容

**Comment by w01fb0ss** [comment]
配置OIDC同样有问题，也是这个url的问题，求大哥给个解决方案

**Comment by eastpiger** [comment]
@w01fb0ss 我们的经验是这样

1. 治标的办法：Fork一份keycloak，修改里面的url硬编码，装上用（我们之前是用这个方法）
2. 治本的办法：换个库

**Comment by w01fb0ss** [comment]
@ibuler 想知道官方会不会替换oidc的库，，，

**Comment by ibuler** [comment]
@w01fb0ss  希望有人能PR解决

**Comment by nomagick** [comment]
对这个问题+1，

本来想使用GitLab提供的OpenID，结果引得这个库根本就是驴唇不对马嘴

难以称为支持OpenID

这部分代码需要重写

**Comment by ibuler** [comment]
能PR一下兼容keycloak吗

**Comment by BaiJiangJie** [comment]
@eastpiger @lilithGao @w01fb0ss @nomagick @wojiushixiaobai @ibuler 

## 关于OpenID功能重构的说明

### OpenID 功能说明:
- 关于JumpServer的OpenID单点登录功能，1.5.8及之前版本只支持对接Keycloak，给需要对接其他OpenID Provider的用户增加了使用的复杂性； 1.5.9及之后版本会支持标准的OpenID协议

### OpenID 功能开发说明:
- 选择依赖包为 django-oidc-rp （项目地址：https://github.com/impak-finance/django-oidc-rp）
- 考虑到JumpServer核心工程的复杂性及后期的升级维护，所以也将其作为单独的django app进行开发。（项目地址：https://github.com/jumpserver/jumpserver-django-oidc-rp）

### 致谢
- 感谢 django-oidc-rp 项目 (https://github.com/impak-finance/django-oidc-rp) 的开发者
- 感谢 Issue (https://github.com/jumpserver/jumpserver/issues/2549) 的提交者 (@eastpiger) 提出的兼容性问题
- 感谢 Issue (https://github.com/jumpserver/jumpserver/issues/3144) 的提交者 (@nomagick) 提供的开发思路
- 感谢 Issue (https://github.com/jumpserver/jumpserver/issues/3458) 和 Pull request (https://github.com/jumpserver/jumpserver/pull/3786/files) 的提交者 (@w01fb0ss)，虽然没有Merge，但此次重构从中借鉴了很多具体的代码实现。

**Comment by BaiJiangJie** [comment]
目前已更新到dev分支，欢迎大家一起来测试。

**Comment by eastpiger** [comment]
谢谢 @BaiJiangJie 的消息

我也是刚刚看jumpserver release的时候注意到了，没想到一年之后这个功能真的改好了。

感谢大家的努力，我们团队近期抽空更新一下试试看
