### ISSUE TITLE
建议在日志审计中增加管理员的操作日志

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2554]
[简述你的问题]
建议增加以下功能，
1、增加管理员对设备、用户、权限进行配置的操作日志
2、增加审计员角色，管理员的操作记录可以由审计员进行审计

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.0 ]

**Comment by jym503558564** [comment]
谢谢反馈和关注，目前已在开发 审计员，将在未来版本发布，请持续关注～
