### ISSUE TITLE
【IP限制】两个小问题

### ISSUE THREAD

**Issue by jokimina** [jumpserver/jumpserver#2555]
[简述你的问题]

在参考jms写内部系统, 关于ip这一块有两个简单的想法
1. https://github.com/jumpserver/jumpserver/blob/dev/apps/authentication/api/auth.py#L42
       允许从客户端传入的参数获取ip觉得不太好. 大部分情况部署在公网,获取x-forward-for的时候反向拿第一个公网ip不知是否可以, 如果内网的话一般就直连了(兼容的话可以考虑加个开关)

```python
def get_request_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', '').split(',')
    if x_forwarded_for:
        for ip in x_forwarded_for[::-1]:
            if not ipaddress.ip_address(ip).is_private:
                login_ip = ip
                break
    else:
        login_ip = request.META.get('REMOTE_ADDR', '')
    return login_ip
 ```
2. 要不要也单独限制下同一个ip的尝试次数, 不然变换username还是可以多次尝试

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
思路不可行，作为一个企业产品，公司出口可能就一个
