### ISSUE TITLE
sudo需要输入密码

### ISSUE THREAD

**Issue by abuxliu** [jumpserver/jumpserver#2556]
[简述你的问题]
几台ubuntu 16.04 都可以自动登录不需要输入密码 有一半的设备登录后sudo不需要输入密码，有2台sudo需要密码

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.9-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/41352815/55204190-0430c880-5209-11e9-9283-d3476ed4c201.png)
![image](https://user-images.githubusercontent.com/41352815/55204214-19a5f280-5209-11e9-9135-ef88ceee52e9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
和你系统用户的sudo设置有关，可以查看 sudoers文件确认
