### ISSUE TITLE
手工登录的用户在【文件管理】页面操作服务器，报“Can not connect asset sftp server: Authentication failed.”

### ISSUE THREAD

**Issue by leeloveying** [jumpserver/jumpserver#2561]
[简述你的问题]
手工登录的用户在【文件管理】页面操作服务器，报“Can not connect asset sftp server: Authentication failed.”

##### 使用版本
Version 1.4.8-2

##### 问题复现步骤
1. 添加系统用户，配置为手工登录（登录时需要密码）
2. 授权用户、服务器权限
3.打开文件管理页面，点击授权的服务器

![image](https://user-images.githubusercontent.com/11881934/55231225-ed1bc600-525c-11e9-95e9-9bb298c91518.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已增加链接复用模式，用户登陆到资产后会自动复用连接
