### ISSUE TITLE
录像有的不能播放，有的不显示时长

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2562]
[简述你的问题]
历史会话中的录像有的不能播放（文件存在），有的不显示时长
![image](https://user-images.githubusercontent.com/15603111/55270734-9b675000-52dd-11e9-8e6c-1bf342934de3.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.0]

**Comment by Coyote5** [comment]
经查看，有问题的录像，目录下的文件大小为0字节。

**Comment by jym503558564** [comment]
可更新一下版本，是否还会复现该问题。
