### ISSUE TITLE
有人能解决 ansible 通过 Jumpserver 去到目标机器上执行的问题吗？

### ISSUE THREAD

**Issue by bottlelee** [jumpserver/jumpserver#2563]
既然 Jumpserver 是堡垒机，那么 ansible 里，bation host 能如何配置，可以让我透过 jumpserver 登录到目标机器并执行 ansible 脚本？

jumpserver 是结合了 Django 和 ansible 来编写的，但目前我本机的 ansible 脚本都不能用了:(

**Comment by tgyday** [comment]
能想到的是原来的ansible不走coco，使用原来的ssh端口~~

**Comment by ibuler** [comment]
jumpserver不支持网关透传方式
