### ISSUE TITLE
docker数据迁移，重启服务，登录报错nginx error!

### ISSUE THREAD

**Issue by ifunplus** [jumpserver/jumpserver#2564]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver 1.4.8
##### 问题复现步骤
1. 在A机器上使用docker安装jumpserver，数据挂载出来
2. 在B机器上使用A的数据，docker安装，作A的备份  
3. 登录admin用户报错nginx error!  
4. secret key 和 bootstrap key均保持一致 !     希望有人能帮忙分析一下，谢谢！

##### 具体表现[截图可能会更好些,最好能截全]

![02](https://user-images.githubusercontent.com/32253100/55302301-1b72ee80-5473-11e9-8212-b418769a8098.PNG)

nginx error.log
![01](https://user-images.githubusercontent.com/32253100/55302221-cd5deb00-5472-11e9-9478-93074bac82ef.PNG)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ifunplus** [comment]
设置nginx之后可以登录成功
  proxy_read_timeout 300;
  proxy_send_timeout 300;
但是需要等待很久才能登录成功，有什么方法可以让备份服务器B可以向A服务器一样快。。

**Comment by ifunplus** [comment]
另外，我的A服务器在内网，备份的B服务器在外网，数据和环境都是一样的

**Comment by wojiushixiaobai** [comment]
@ifunplus 环境交代不清楚
B使用A的数据库?数据库在什么环境?与B在一起？

**Comment by ifunplus** [comment]
A之前在内网ubuntu，使用docker安装到ubuntu，数据库和配置文件挂载到A的宿主机上；
B是阿里云外网ubuntu, 把A宿主机上堡垒机相关数据迁移过来，用docker方式挂载数据，做到和A的数据和配置统一；

可能解决方案是：
内网堡垒机之前配置了内网ldap服务，迁移过去后相当于外网堡垒机也配置了内网ldap服务，第一次登陆成功后，取消外网上的ldap服务之后再登陆admin就正常了。

怀疑原因：
是登陆用户判断逻辑的先后问题吗？先去ldap服务器上匹配，匹配不到再去数据库里查询吗？

**Comment by wojiushixiaobai** [comment]
@ifunplus 设置ldap后，优先判断ldap，ldap有超时时间，超时后才会使用本地认证
