### ISSUE TITLE
如何修改系统用户的家目录配置？

### ISSUE THREAD

**Issue by Light-Gao** [jumpserver/jumpserver#2565]
通过WEB页面添加的系统用户，自动推送到资产主机时默认家目录为/home/xxx.

##### 使用版本
使用Docker镜像版本，jumpserver/jms_all:latest

##### 问题复现步骤
1. 系统用户管理，添加系统用户，提交；
2. 登录主机，查看系统用户的家目录为/home/xxx, 页面没有找到修改入口；

**Comment by ibuler** [comment]
目前不支持
