### ISSUE TITLE
RESTful API 批量更新或者删除错误

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#2566]
[简述你的问题]
最新版在使用RESTful API 调用/assets/v1/assets-bulk 下使用put
'OrgManagerFromAssetQuerySet' object has no attribute 'pk'
此接口下使用delete，不止如何调用删除指定的资产。
用/assets/v1/assets/{id}/是可以正常调用。
批量的调用能否给出例子。。。。

**Comment by jym503558564** [comment]
api批量更新使用PATCH局部更新，例如更新主机名格式如下：
----- id为例 批量更新更新主机名：
[
	{
		"id":"0f35ca24-39ff-44ce-8ade-95c52679f028",
		"hostname":"centos_1"
	},
	{
		"id":"29e1d865-96a2-4d0f-ae22-db13b75e5bce",
		"hostname":"centos_2"
	},
	{
		"id":"7872283a-e853-4bc9-9490-c85cc779c41a",
		"hostname":"centos_3"
	},
	{
		"id":"e374f36b-2a74-4c48-9961-a212ad2a9a19",
		"hostname":"centos_4"
	}
	
]

---- pk为例 批量更新更新主机名：
[
	{
		"pk":"0f35ca24-39ff-44ce-8ade-95c52679f028",
		"hostname":"linux_1"
	},
	{
		"pk":"29e1d865-96a2-4d0f-ae22-db13b75e5bce",
		"hostname":"linux_2"
	},
	{
		"pk":"7872283a-e853-4bc9-9490-c85cc779c41a",
		"hostname":"linux_3"
	},
	{
		"pk":"e374f36b-2a74-4c48-9961-a212ad2a9a19",
		"hostname":"linux_4"
	}
	
]
