### ISSUE TITLE
COCO的地址显示不正确

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2572]
[简述你的问题]

在终端列表里，COCO的地址显示的是127.0.0.1。netstat查看，coco的监听地址是正确。

![image](https://user-images.githubusercontent.com/15603111/55447154-3a00f300-55f5-11e9-8dbc-701e1014995e.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.0]

**Comment by wojiushixiaobai** [comment]
@Coyote5 不影响使用，忽略
