### ISSUE TITLE
ssh最大空闲超时bug

### ISSUE THREAD

**Issue by tuyula** [jumpserver/jumpserver#2573]
[简述你的问题]

##### 使用版本
1.4.8-2

##### 问题复现步骤
1. 系统设置了ssh最大超时时间120
2. 自动断开时间是15min
3. 我们用k8s起的,修改配置重启了k8s,不知是否有关

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@tuyula 超时的设置有三处，请验证下
1. nginx代理超时
2. 资产timeout
3. 网络层环节的其他设置（如防火墙拦截等）

**Comment by tuyula** [comment]
你好，后面继续测试了, 发现web的超时没有问题,可以长达几小时, ssh的超时却有问题

**Comment by tuyula** [comment]
你发,我们发现了ssh超时的原因,因为sshd由客户端和服务端构成, 我们需要在自己的客户端设置~/.sshd保活, 才能在ssh中等待设置的超时时间才中断

**Comment by ibuler** [comment]
已处理，添加了客户端会话心跳
https://github.com/jumpserver/coco/commit/cd4a22d884ffeff595536ca8558b534ceacf0bc6
