### ISSUE TITLE
更新1.4.9版本后前端右下角显示的版本号不对

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2576]
[简述你的问题]
使用release 1.4.9对1.4.8进行更新，完成启动服务后，右下角显示的版本依然是1.4.8-2

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9

##### 问题复现步骤
使用release 1.4.9版本更新后重启服务

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
感谢提醒，1.5.0版本更新过来了
