### ISSUE TITLE
测试smtp提示密码必输

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2577]
[简述你的问题]
系统设置-LDAP设置，填写主机端口账等信息后点击测试，提示
>{"error":"{'EMAIL_HOST_PASSWORD':[ErrorDetail(string='该字段不能为空。',code='blank')]}"
实际页面上并不是必输项，但实际又校验必输

##### 使用版本
1.4.9

##### 问题复现步骤
密码输入框不填，测试SMTP邮件发送

##### 具体表现[截图可能会更好些,最好能截全]
页面非必输，实际测试时校验必输，建议去掉校验。
实际我们公司内部SMTP是不需要账号密码校验的，只需开通25端口防火墙即可～～

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
个人认为一款开源产品在安全性上过于开放是个不好的事情，参考redis和elasticsearch、mongodb
你这里开放email密码非必填，那么就说明其他人也可以不去设置email密码空，且开放认证。
我们并不能保证其他人和你一样设置了防火墙，从而最终一旦发生安全事故的标题就是《使用了jumpserver导致客户邮箱信息泄露》
