### ISSUE TITLE
1.4.9 版本 tar 包更新 找不到静态文件

### ISSUE THREAD

**Issue by ZmDingSi** [jumpserver/jumpserver#2578]
[简述你的问题]
1.4.9  release tar 包；启动后找不到静态文件；

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48982949/55459757-d8f01400-5622-11e9-80c9-520b62464877.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ZmDingSi 请确认是文件夹没有文件还是nginx指向错误

**Comment by ZmDingSi** [comment]
> @ZmDingSi 请确认是文件夹没有文件还是nginx指向错误
直接使用 jumpserver 监听的IP和端口访问的，没使用Nginx代理！

**Comment by ZmDingSi** [comment]
> @ZmDingSi 请确认是文件夹没有文件还是nginx指向错误
今天我尝试从git拉代码更新，启动后加载静态文件没有问题！

**Comment by wojiushixiaobai** [comment]
@ZmDingSi 如问题已经解决请关闭问题，如遇到问题时请再次打开
