### ISSUE TITLE
web终端自动断开时长修改

### ISSUE THREAD

**Issue by xiaooloong** [jumpserver/jumpserver#258]
web终端1分钟不动就会断开，这个时间如何调整？

**Comment by xiaooloong** [comment]
学了一天python，才发现是 nginx 代理的问题
proxy_read_timeout 和 proxy_send_timeout 默认 60 秒，作用是当一个连接前后两次发送/接受数据的时间间隔超过 60 秒就断开
在 websocket 的 location 内修改超时时间即可
···
    location ^~ /ws/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_pass http://jumpserver;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
    }
···

**Comment by zhusas** [comment]
看来得靠社区的力量了啊
