### ISSUE TITLE
更新1.4.9后web终端访问window无法结束会话

### ISSUE THREAD

**Issue by zxq1002** [jumpserver/jumpserver#2580]
[简述你的问题]
web终端访问windows，关闭会话窗口后，打开在线会话菜单，可以看到刚已经关闭的会话还是显示为在线会话，且终断按钮不可用。查看数据库可以看到相应的会话记录，date_end字段为空。linux无此问题。

##### 使用版本
1.4.9

##### 问题复现步骤
1. 打开web终端，访问windows远程桌面，然后关闭会话窗口；
2. 打开在线会话菜单，可以看到刚关闭的会话还在，且终断按钮不可用。

##### 具体表现[截图可能会更好些,最好能截全]
windows通过web终端访问远程桌面正常关闭会话后未正常记录。

##### 其他

[注:] 完成后请关闭 issue

**Comment by djy1121** [comment]
我也遇到这个情况，重启设备，升级到1.4.10，也没有清理对应的在线会话记录。

**Comment by jym503558564** [comment]
1.5.0 版本 已修复
打开web终端，访问windows远程桌面，关闭会话窗口。此时点击在线会话，查看在线会话里不存在刚关闭的windows资产

**Comment by jym503558564** [comment]
目前关于幽灵会话，已修复，请更新至最新版本。
如有其他问题，可再次打开issues~
