### ISSUE TITLE
luna 1.4.1 windows账号手动登录连接很慢，自动登录很快

### ISSUE THREAD

**Issue by xionghui** [jumpserver/jumpserver#2581]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.2  注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1] windows账号选用any登录【手动登录】
![image](https://user-images.githubusercontent.com/2037425/55528293-e2cf5100-56ce-11e9-90cd-d166fdbc9031.png)

需要白屏等待很久！！！
![image](https://user-images.githubusercontent.com/2037425/55528306-eebb1300-56ce-11e9-9986-d7476a484111.png)

2. [步骤2] windows账号选用自动账号登陆，瞬间进去！

##### 其他

[注:] 完成后请关闭 issue

**Comment by xionghui** [comment]
![image](https://user-images.githubusercontent.com/2037425/55529540-75beba00-56d4-11e9-8cf6-3d487a9408ab.png)

**Comment by wojiushixiaobai** [comment]
@xionghui 请更新到最新版本后再尝试，任然有问题再继续打开此问题
