### ISSUE TITLE
一步一步安装(CentOS)  按照此步骤  启动jumpserver后报错 

### ISSUE THREAD

**Issue by xiao-fan** [jumpserver/jumpserver#2584]
[简述你的问题]

一步一步安装(CentOS)  按照此步骤  启动jumpserver,访问:8080会报“jumpserver.terminal_session' doesn't exist”

执行这个 bash make_migrations.sh  没看到生成terminal_session表.  
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
上周刚clone的master  最新版本
##### 具体表现[截图可能会更好些,最好能截全]

![jumpserver-error](https://user-images.githubusercontent.com/10541915/55532102-38135e80-56df-11e9-98c7-3cca51190d59.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiao-fan 新版本没有 bash make_migrations.sh 这个步骤
保证在安装jumpserver时，mysql数据库的jumpserver数据库里面是空的

**Comment by xiao-fan** [comment]
@wojiushixiaobai 谢谢 回复      那导入表结构的部分是在哪部分完成?  ./jms start all -d  这里？

**Comment by wojiushixiaobai** [comment]
@xiao-fan 对，会自动处理，保证配置正确即可。
