### ISSUE TITLE
使用堡垒机管理机器后，不同机器之间如何通过scp命令传递数据

### ISSUE THREAD

**Issue by ifunplus** [jumpserver/jumpserver#2588]
[简述你的问题]

使用堡垒机管理机器后，不同机器间如何通过scp命令传递数据

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8
##### 问题复现步骤
1. A用户通过堡垒机B登陆A机器
2. C用户通过堡垒机B登陆C机器
3. 没用堡垒机管理机器时，A和C之间可以通过scp命令直接连接，现在是
A用户-》堡垒机B-》A机器-》堡垒机B使用C用户-》登陆C机器
那么现在A机器该如何使用scp命令获取C机器上的数据？？
希望大佬们帮忙分析一下，谢谢！！！

##### 其他

[注:] 完成后请关闭 issue

**Comment by ZmDingSi** [comment]
A C 之间做免密

**Comment by ZmDingSi** [comment]
> [简述你的问题]
> 
> 使用堡垒机管理机器后，不同机器间如何通过scp命令传递数据
> 
> ##### 使用版本
> [请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
> 1.4.8
> 
> ##### 问题复现步骤
> 1. A用户通过堡垒机B登陆A机器
> 2. C用户通过堡垒机B登陆C机器
> 3. 没用堡垒机管理机器时，A和C之间可以通过scp命令直接连接，现在是
>    A用户-》堡垒机B-》A机器-》堡垒机B使用C用户-》登陆C机器
>    那么现在A机器该如何使用scp命令获取C机器上的数据？？
>    希望大佬们帮忙分析一下，谢谢！！！
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> ##### 其他
> [注:] 完成后请关闭 issue

A C 用户之间做免密

**Comment by jym503558564** [comment]
创建授权规则后，登录资产。
例如现在登录A资产，需求：拷贝C资产的数据到A资产
scp C资产用户名@C资产IP:/opt/soft/demo.tar /opt/soft/

**Comment by jym503558564** [comment]
问题是否得到解决？

**Comment by ibuler** [comment]
暂不支持
