### ISSUE TITLE
使用堡垒机连接资产后，pycharm配置ssh interpreter失败

### ISSUE THREAD

**Issue by ifunplus** [jumpserver/jumpserver#2589]
[简述你的问题]
使用堡垒机连接资产后，pycharm 配置ssh interpreter失败

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
1. 堡垒机配置完成，A用户可以通过堡垒机登陆A机器。
2. A机器上有相应的python环境
3. 用户只能通过堡垒机登陆A机器的情况下，如何配置用户能在pycharm环境中使用A机器上的python环境

希望有人帮忙解答一下，谢谢！

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ifunplus** [comment]
![image](https://user-images.githubusercontent.com/32253100/55850694-03dce980-5b88-11e9-90ae-59869af741fd.png)

remote host无法自动显示相应文件，配置相应机器目录也是失败，这块目录怎么写才正常？？？？
![image](https://user-images.githubusercontent.com/32253100/55850746-3dadf000-5b88-11e9-9879-d9bf99e843f0.png)

**Comment by ifunplus** [comment]
网上有一个解决方案(https://stackoverflow.com/questions/37827685/pycharm-configuring-multi-hop-remote-interpreters-via-ssh)是通过端口转发的功能解决pycharm ssh interpreter,但我测试了总是失败，请问一下coco 是不是不支持端口转发方式？？？

**Comment by leeloveying** [comment]
> 网上有一个解决方案(https://stackoverflow.com/questions/37827685/pycharm-configuring-multi-hop-remote-interpreters-via-ssh) 是通过端口转发的功能解决pycharm ssh interpreter,但我测试了总是失败，请问一下coco 是不是不支持端口转发方式？？？

coco服务好像是不支持的，日志会有输出[sshd ERROR] Request type `direct-tcpip:direct-tcpip` not support now，在使用堡垒机连接mysql服务时发现的

**Comment by ibuler** [comment]
不支持 转发

**Comment by CHENBIN99** [comment]
现在支持了吗

**Comment by DotaArtist** [comment]
2024/11/11 还不支持吗？
