### ISSUE TITLE
普通用户 ssh 跳板机后，未自动运行 commect.py 

### ISSUE THREAD

**Issue by zxing0214** [jumpserver/jumpserver#259]
建议将  command="python /opt/jumpserver/connect.py" 添加到跳板机普通用户的 .ssh/authorized_keys
文件中，以便自动运行该脚本。

**Comment by jiaxiangkong** [comment]
/etc/passwd  用户的bash为 /opt/jumpserver/init.sh

**Comment by zxing0214** [comment]
谢谢

**Comment by xiaozhi5448** [comment]
这个问题该怎么解决呢？手动把普通用户的bash改成init.sh么？
