### ISSUE TITLE
luna 左侧列表存在超时BUG

### ISSUE THREAD

**Issue by aaabbbaaa** [jumpserver/jumpserver#2593]
正常登陆系统并进入luna界面后，如果设置了超时机制的情况下，当用户长时间没使用超时后，正常的系统页面会自动跳转到登陆界面，但是在luna界面，只要不进行刷新操作，当前的所有设备的远程操作都是没有任何问题的，按理也是应该跳转到登陆界面的。

在上诉问题中，如果设置的是页面关闭后自动注销的，也同样存在这个问题，在操作界面选择web终端，会跳出一个新的窗口打开luna界面，这是如果把主系统窗口关闭，也同样在不刷新luna界面的情况下，可以打开已经列出来的设备远程。

Jumpserver版本 1.4.9

**Comment by wojiushixiaobai** [comment]
@aaabbbaaa 已收到反馈

**Comment by ibuler** [comment]
已添加session缓存，当点击左侧资产连接时都会延长session有效期
