### ISSUE TITLE
前端加了AWS ALB后，访问不了，出现CSRF错误

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#2595]
[简述你的问题]
jumpserver前加了alb，登陆后就会出现CSRF错误，如截图所示，我要怎么调整配置才能解决呢？
感谢支持！

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
最新版

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20255706/56014557-57863900-5d28-11e9-8d70-3d2e09ad5c68.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ChampionWolf 去掉前端的负载均衡，自建

**Comment by ChampionWolf** [comment]
@wojiushixiaobai  您好，之前低版本的jumpserver 还是可以配置到负载均衡后到，现在升级后是调整什么了么，我们生产环境前端只能通过AWS ALB发布服务，，不清楚我这边能否通过修改某些配置，让它可以通过负载均衡进行访问呢？谢谢！

**Comment by wojiushixiaobai** [comment]
@ChampionWolf [参考AWS文档](https://docs.aws.amazon.com/zh_cn/elasticloadbalancing/latest/application/load-balancer-target-groups.html#sticky-sessions)
