### ISSUE TITLE
web 终端最近一直连接失败。。放置半天后，点击服务器，才能连

### ISSUE THREAD

**Issue by tigerbin** [jumpserver/jumpserver#2596]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.8-2 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. web 终端最近一直连接失败。。放置半天后，点击服务器，才能连
2.更奇怪的事情，一个窗口一直可以连，再打开另外一个窗口，却不能连
3、没有任何日志可以查看，都没有新日志。麻烦提供需要查看啥日志。。
![image](https://user-images.githubusercontent.com/13775090/56077663-65fc4f80-5e11-11e9-92a8-13a83ef529ca.png)
![image](https://user-images.githubusercontent.com/13775090/56077676-81fff100-5e11-11e9-9875-7577828ba376.png)
连接失败没任何提示。。。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@tigerbin 禁掉缓存

**Comment by tigerbin** [comment]
![image](https://user-images.githubusercontent.com/13775090/56093243-8fdc7180-5ef8-11e9-8522-d67325621a17.png)
浏览器的无痕模式+禁用缓存，还是不行，而且不停的接口报错

**Comment by wojiushixiaobai** [comment]
@tigerbin 把coco停止后，kill掉卡死的coco进程，然后重启试试。请详细说明下部署环境

**Comment by tigerbin** [comment]
存在多个coco进程，杀掉重启好像好了，先关闭这个话题吧
