### ISSUE TITLE
修改安装脚本，优化git clone速度

### ISSUE THREAD

**Issue by hmilylife** [jumpserver/jumpserver#2598]
[简述你的问题]

安装脚本里面有一步骤 
git clone https://github.com/jumpserver/jumpserver.git
建议添加depth =1. 这样可以不拉取服务器的历史提交。安装下载数量会减少。
git clone --depth=1 https://github.com/jumpserver/jumpserver.git
加快安装速度。

文档也需要最调整。

谢谢。

**Comment by wojiushixiaobai** [comment]
@hmilylife 收到反馈。
