### ISSUE TITLE
mac putty

### ISSUE THREAD

**Issue by mienv567** [jumpserver/jumpserver#260]
mac putty方式连接,  
ssh -i king.pem king@112.124.x.x 输入密钥密码就是错误 win下正常

**Comment by mienv567** [comment]
@lrqrun @pengyao

**Comment by lrqrun** [comment]
密钥文件权限对吗？ 600?

**Comment by mienv567** [comment]
@lrqrun  设置过啦  400 600 777 都不行，好像加密方式不行

**Comment by ibuler** [comment]
权限 600，你可以使用Mac自带 terminal连接。
$ chmod 600 king.pem
$ ssh-add -K king.pem    输入密码, -K代表存到Mac的钥匙库中，以后不用再输入密码
$ ssh king@xxxx
