### ISSUE TITLE
jumpserver登录服务器越来越慢，重启后恢复

### ISSUE THREAD

**Issue by houdaiye** [jumpserver/jumpserver#2603]
[简述你的问题]
用xhell登录jumpserver，选择一台机器进入，输入命令操作一些东西的时候会很慢。

重启后会恢复，但是越用越慢，dashboard中的Online sessions数字会越来越大，不知道是不是跟这个有关系

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.0-2 GPLv2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/24284243/56268787-cdbddd80-6124-11e9-93d6-28065ac6b571.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@houdaiye 新版本已经优化这个问题，请尝试更新

**Comment by houdaiye** [comment]
好的，多谢大佬！
