### ISSUE TITLE
通过控制台方式登陆（ssh），在资产列表应该把vnc和rdp资产过滤掉，不显示

### ISSUE THREAD

**Issue by peixubin** [jumpserver/jumpserver#2604]
[简述你的问题]
通过ssh登陆jumpserver，在资产列表包括了vnc和rdp等图形化资产，这些资产在ssh界面中实际上是无法使用的。

##### 使用版本
1.4.9

##### 问题复现步骤
1. ssh user@<coco server>
2. 按回车，发现图形化资产仍然显示

**Comment by wojiushixiaobai** [comment]
@peixubin 之前反馈过，但是不是很好处理。而且部分场景是需要显示这些资产的，vnc和rdp资产有时候也需要使用ssh方式进行连接。

**Comment by peixubin** [comment]
vnc和rdp资产可以通过ssh方式进行连接？

**Comment by ibuler** [comment]
如果去掉用户可能会觉得和luna列表显示的不一致，所以这里放上去了，输入时，提示用户使用web terminal连接
