### ISSUE TITLE
coco  终端 光标移动 不支持 或出现异常字符

### ISSUE THREAD

**Issue by superoo1** [jumpserver/jumpserver#2605]
[简述你的问题]
coco 终端页面 光标不能移动

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.48
##### 问题复现步骤
1. [步骤1]  登录coco
2. [步骤2]   移动光标

##### 具体表现[截图可能会更好些,最好能截全]

#
![image](https://user-images.githubusercontent.com/29897282/56279277-63b03300-613a-11e9-8a15-322ff04c33d4.png)
#### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@superoo1 目前不支持，已记录
