### ISSUE TITLE
网关密码中包含有(时连接失败

### ISSUE THREAD

**Issue by charnet1019** [jumpserver/jumpserver#2606]
网关密码中包含有(时连接失败

版本： 1.4.9

[注:] 完成后请关闭 issue

**Comment by charnet1019** [comment]
![image](https://user-images.githubusercontent.com/18616254/56332099-93eee480-61c1-11e9-924f-d9294c5b82f4.png)

**Comment by wojiushixiaobai** [comment]
@charnet1019 目前不支持网关特殊字符串，页面有提示
