### ISSUE TITLE
从1.4.3升级到1.4.7

### ISSUE THREAD

**Issue by zhaodanwjk** [jumpserver/jumpserver#2609]
[简述你的问题]
关于用docker-compose升级jumpserver版本的方法，是否可以直接修改版本号进行升级？我现在的jumpserver是使用docker-compose进行安装部署的jumpserver1.4.3，想升级到1.4.7升级失败了，升级后报505 bad servers

##### 使用版本
Version 1.4.3-2 GPLv2.

##### 问题复现步骤
1. 修改docker-compose.yml中jumpserver:1.4.3为jumpserver:1.4.7 
  jumpserver:
    image: wojiushixiaobai/jumpserver:1.4.3
    container_name: "jms_v1.4.3"
——————
  jumpserver:
    image: wojiushixiaobai/jumpserver:1.4.7
    container_name: "jms_v1.4.7"
2. [步骤2]
docker-compose down 停止正在运行的服务，重新启动docker-compose后会拉取1.4.7的镜像，docker ps 查看启动正常

##### 具体表现[截图可能会更好些,最好能截全]
web访问登录后显示 bad servers

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhaodanwjk 如果使用的是我这边的镜像，镜像里面包含完整的git仓库信息，

    $ docker exec -it jms_v1.4.3 /bin/bash
    $ cd /opt/jumpserver
    $ git fetch
    $ git checkout 1.4.4

    # 按照升级文档正常升级到1.4.4然后正常升级到最新即可，之前考虑过docker升级的问题
