### ISSUE TITLE
关于发送邮件的bug

### ISSUE THREAD

**Issue by yulongjun** [jumpserver/jumpserver#261]
描述一下bug：
在创建用户的时候，会默认勾选发送邮件，此时发送的邮件是成功的，有收到文件。

但是在创建好用户之后，在查看用户栏里，点**Email**后显示发送成功，但是邮箱里收不到任何邮件。同样在编辑的时候，勾选发送邮件，也是没有收到任何邮件。

**Comment by jiaxiangkong** [comment]
遇到过类似情况，jumpserver.conf 我是用163，新建用户时发送的邮件是成功的，163却没有收到文件。然后换别的邮箱没问题，应该是邮箱问题。你可以试一下换别的邮箱。
