### ISSUE TITLE
web客户端 一直没有显示资源

### ISSUE THREAD

**Issue by wadeLouis** [jumpserver/jumpserver#2611]
[简述你的问题]

##### 使用版本
jumpserver: 1.4.9-2
os: centos 7

##### 问题复现步骤

略

##### 具体表现[截图可能会更好些,最好能截全]
具体表现
![image](https://user-images.githubusercontent.com/23622761/56368632-65f1ba80-622a-11e9-80f2-7e3271be8a52.png)
主机资源
![image](https://user-images.githubusercontent.com/23622761/56368782-b36e2780-622a-11e9-9492-66f5d2150e55.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@wadeLouis 先授权，用户只能看到被授权给自己的资产
