### ISSUE TITLE
[sshd ERROR] Request type `direct-tcpip:direct-tcpip` not support now

### ISSUE THREAD

**Issue by leeloveying** [jumpserver/jumpserver#2612]
[简述你的问题]
无法使用ssh代理[coco服务]连接mysql数据库

##### 使用版本
Version 1.4.9-2 

##### 问题复现步骤
使用ssh代理方式连接数据库，coco服务日志有报错：[sshd ERROR] Request type `direct-tcpip:direct-tcpip` not support now

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
目前不支持
