### ISSUE TITLE
数据库更换问题

### ISSUE THREAD

**Issue by oc-oc** [jumpserver/jumpserver#2615]
请教下大神，之前部署的同事，将默认数据库设置为sqlite, 现在上了生产，才发现这个问题。

现在需要将sqlite数据库替换为mysql，需要如何操作。

只需要将sqlite数据导入到mysql，然后修改下配置文件就可以了吗。

我的jumpserver版本是  Version 1.4.4

**Comment by wojiushixiaobai** [comment]
@oc-oc 先把sqlite的数据导出，然后导入到mysql数据库，然后正常启动即可。

**Comment by oc-oc** [comment]
好的好的，感谢大佬，明白了，晚上操作试试。
