### ISSUE TITLE
有关 docker的配置使用说明及注意事项能说说吗

### ISSUE THREAD

**Issue by cjd9023** [jumpserver/jumpserver#262]
在 hub.docker 上看到的，docker镜像，没使用说明。
问一下，没有 mysql 下能正常工作吗，新建的用户、操作视频之类的保存在哪，
通过本地 -v 目录挂载到 /data 下即可吗？
期待你的回答！谢谢！

**Comment by techcook** [comment]
没有mysql也能正常工作，使用的是sqlite数据库。

**Comment by jiaxiangkong** [comment]
镜像可以自己制作，可以参考论坛贴
http://bbs.jumpserver.org/read/717.html   Dockerfile封装
在 hub.docker上分享的镜像
http://bbs.jumpserver.org/read/718.html  docker 镜像

**Comment by Catstyle** [comment]
docker-compose方式启动，restart之后，数据丢失了。
已经配置了volume，指向方式是   data:/opt/jumpserver/data
还是说需要其他配置？
