### ISSUE TITLE
开启自动运行，不稳定，

### ISSUE THREAD

**Issue by 156889031** [jumpserver/jumpserver#2621]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本1.49，使用快速安装方式，使用网站提供的脚本配置开机启动，有的时候能够来，多数无法启动启动]

##### 问题复现步骤
1. [步骤1]  我使用安装的时候，是2核CPU 4G内存，使用虚拟机设置了快照，后来修改成1核心2G内存，3G内存 4G内存，等等，都无法自动启动了，相关的 文件给了执行权限也不行，感觉缺少测试。真的无法给个start，功能不错，有些脆弱；最后来，使用原始的快照，配置上了，也无法自动启动。
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@156889031 无法在恶劣的环境启动成功，启动超时会导致失败，代码详情
