### ISSUE TITLE
python-keycloak-client==0.1.3

### ISSUE THREAD

**Issue by bigcong** [jumpserver/jumpserver#2624]
[简述你的问题]
这个版本不存在，最新版本的不兼容，python3 不能安装这个版本

##### 使用版本
最新的版本
##### 问题复现步骤
安装的时候，就能复现

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bigcong 请按照文档进行安装，复制粘贴安装即可。注意系统和环境要求
