### ISSUE TITLE
jumpserver连接windows远程桌面能否做到和mstsc一样全屏显示

### ISSUE THREAD

**Issue by feixiangdao** [jumpserver/jumpserver#2628]
[简述你的问题]
jumpserver连接windows远程桌面能否做到和mstsc一样全屏显示，不然都看不清楚远程的电脑内容。虽然谷歌浏览器可以F11全屏，但是jumpserver自身的菜单栏和标签栏没有办法隐藏。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9-2 
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
1.5.0 已优化
![image](https://user-images.githubusercontent.com/40739051/58861730-9a89da80-86e1-11e9-8b41-3088e6a9c3c3.png)
