### ISSUE TITLE
连接windows资产时全屏显示

### ISSUE THREAD

**Issue by WXQAQ** [jumpserver/jumpserver#2631]
[简述你的问题]

希望可以在下一个新版本时更新有此功能：连接windows资产时可以全屏显示。不然使用笔记本的同事使用本堡垒机在连接win时排版紧凑，看不清楚。

##### 使用版本

Version 1.4.9-2 GPLv2.

##### 问题复现步骤
略

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
1.5.0已修复
![image](https://user-images.githubusercontent.com/40739051/58932371-12b1d800-8796-11e9-8558-6f30255c5f92.png)
