### ISSUE TITLE
如何通过 '{% url "api-ops:command-execution-list" %}'; 指向到 command-executions的路径上

### ISSUE THREAD

**Issue by storm0816** [jumpserver/jumpserver#2639]
[简述你的问题]
如何通过 '{% url "api-ops:command-execution-list" %}'; 指向到 command-executions的路径上

##### 使用版本
Jumpserver1.4.9

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/23227952/56861758-aa254d80-69d6-11e9-9fa7-94ceead5dd98.png)
![image](https://user-images.githubusercontent.com/23227952/56861761-b27d8880-69d6-11e9-9a51-d2b5ca3d8bb7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
请区别url反向解析：
api_url      ====>    '{% url "api-ops:command-execution-list" %}'
view_url    ====>    '{% url "ops:command-execution-list" %}'

**Comment by storm0816** [comment]
谢谢解答
在ops/url/api_url.py中并没有发现 name='command-execution-list'，这个困扰我很久，一直没想通。期待您的解答。
![360截图16780628377016](https://user-images.githubusercontent.com/23227952/58683118-db15eb00-83a5-11e9-883d-ba80949be737.png)

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/59329581-caf4f880-8d21-11e9-8e24-41efc5728629.png)
