### ISSUE TITLE
功能需求--限时授权

### ISSUE THREAD

**Issue by henyufeiyang** [jumpserver/jumpserver#264]
在日常的运维工作中，经常遇到rd临时申请高级别权限的情况。而单独为某个rd添加一条授权规则或者为这个rd修改sudoers文件，如果没有及时撤销高级别权限会照成权限的泛滥。 
能不能增加限时权限的功能。比如rd临时需要root用户权限，预计使用1个小时。我添加授权规则的时候指定权限的有效时间。时间到达后自动清理该授权规则。 
还有，jumpserver有没有HTTP的API可以供其他系统调用？

**Comment by ibuler** [comment]
新版本支持
