### ISSUE TITLE
批量执行的命令没有录像和命令历史记录？

### ISSUE THREAD

**Issue by goldwinner** [jumpserver/jumpserver#2644]
[简述你的问题]
在web终端里面执行命令，可以在“历史会话”和“命令记录”中查看录像回放和历史命令。但是在我的资产—批量执行里面，对多台机器执行的命令却没有录像和历史命令？这是无意中发现一个超大bug？？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.9-2 GPLv2.
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不再录像中, 而在日志审计的批量命令中
