### ISSUE TITLE
你好，我删除了Jumpserver 但是无法 执行su  - 普通用户报错。

### ISSUE THREAD

**Issue by zhangxuebao** [jumpserver/jumpserver#2646]
[简述你的问题]
你好，我删除了Jumpserver 但是无法 执行su  - 普通用户报错。
我没有删除 
[root@jumpboardserver01 tbj]# su - tbj
上一次登录：一 4月 29 16:01:42 CST 2019pts/0 上
没有该用户，或许你是以root运行的 No that user.

删除  jumpserver
 [root@Kafka-Server1 opt]# su - tbj
上一次登录：一 4月 29 16:06:07 CST 2019pts/13 上
python: can't open file '/opt/jumpserver/connect.py': [Errno 2] No such file or directory

##### 使用版本   Version 3.0
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
你好：Version 3.0
##### 问题复现步骤
我没有删除 
[root@jumpboardserver01 tbj]# su - tbj
上一次登录：一 4月 29 16:01:42 CST 2019pts/0 上
没有该用户，或许你是以root运行的 No that user.

删除  jumpserver
 [root@Kafka-Server1 opt]# su - tbj
上一次登录：一 4月 29 16:06:07 CST 2019pts/13 上
python: can't open file '/opt/jumpserver/connect.py': [Errno 2] No such file or directory

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/27907749/56884269-cd660080-6a9b-11e9-94e9-271061f69a26.png)

![image](https://user-images.githubusercontent.com/27907749/56884277-d5be3b80-6a9b-11e9-9afa-f39f43b49108.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by zhangxuebao** [comment]
上一次登录：一 4月 29 16:06:32 CST 2019pts/13 上
python: can't open file '/opt/jumpserver/connect.py': [Errno 2] No such file or directory

**Comment by ibuler** [comment]
0.4之前的版本,请修改 /etc/passwd里面指定的shell, 或查看 ls /etc/profile.d/z*

**Comment by zhangxuebao** [comment]
谢谢您回复：

请教下这个sh 我删除就可以？

[root@jumpboardserver01 ~]# cat /etc/profile.d/zzjumpserver.sh
#!/bin/bash

export LANG='zh_CN.UTF-8'

if [ "$USER" != "admin" ] && [ "$USER" != "root" ];then
        python /opt/jumpserver/connect.py
        if [ $USER == 'guanghongwei' ];then
            echo
        else
            exit 3
            echo
        fi
fi






------------------ 原始邮件 ------------------
发件人: "老广"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 上午10:28
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "HTFUF"<www.765289948@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jumpserver/jumpserver] 你好，我删除了Jumpserver 但是无法 执行su  - 普通用户报错。 (#2646)




0.4之前的版本,请修改 /etc/passwd里面指定的shell, 或查看 ls /etc/profile.d/z*

**Comment by zhangxuebao** [comment]
删除可以了感谢
