### ISSUE TITLE
web终端报错400

### ISSUE THREAD

**Issue by zyq0314** [jumpserver/jumpserver#2647]
[简述你的问题]
使用web终端连接时，刚打开时无法连接，要等一段时间才可以
版本
jump server1.4.9版本

##### 问题复现步骤
1.登陆后，使用web终端，会有报错，如图
![image](https://user-images.githubusercontent.com/50099947/56885916-50895580-6aa0-11e9-9bee-fc0572f71f6d.png)

2. [步骤2]
等一段时间，就可以连接了
![image](https://user-images.githubusercontent.com/50099947/56885537-3ac76080-6a9f-11e9-937e-acd48e99aedb.png)

这是什么原因？

**Comment by ibuler** [comment]
websocket连接失败, 多层nginx都需要加上 那段 Upgrade 配置

**Comment by zyq0314** [comment]
是这段配置吗？
![image](https://user-images.githubusercontent.com/50099947/56945217-f6989680-6b58-11e9-8a85-9f4f2ae5a439.png)
配置文件中有的

**Comment by ibuler** [comment]
无法评估
