### ISSUE TITLE
添加用户时，邮件内的访问地址无端口

### ISSUE THREAD

**Issue by X-Mars** [jumpserver/jumpserver#265]
![Uploading image.png…]()

**Comment by jiaxiangkong** [comment]
方法一使用80端口：
修改jumpserver.conf  中 port = 8000 改为80，然后 ./service.sh restart 一下

方法二：
cd /opt/jumpserver/juser
vim user_api.py +171
![1t 6cfhbfwfaowt 9s 5 cp](https://cloud.githubusercontent.com/assets/16377458/16289713/dd78d246-3929-11e6-86e5-061593a8264a.png)

**Comment by X-Mars** [comment]
明白  可以关闭了
