### ISSUE TITLE
jumpserver从1.4.1升级到1.4.4报错

### ISSUE THREAD

**Issue by amoyx** [jumpserver/jumpserver#2650]
将jumpserver从1.4.1版本升级到1.4.4时报错，执行sh make_migrations.sh 时报错，信息如下。

![image](https://user-images.githubusercontent.com/19795002/56893493-72410780-6ab5-11e9-8da5-e0ac4e4c2713.png)

**Comment by wojiushixiaobai** [comment]
@amoyx 参考faq的升级问题第三条处理即可。注意做好备份
