### ISSUE TITLE
你好：使用 web 终端的时候 centos 无法连接，时好时坏

### ISSUE THREAD

**Issue by zhangxuebao** [jumpserver/jumpserver#2651]
[简述你的问题]
你好：使用 web 终端的时候 有时候可以访问，centos 有时候无法打开失败率很高，但是windows 没有问题。
docker 镜像安装的。
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

你好：版本是 1.4.8-2 docker 镜像安装的。

##### 问题复现步骤
你好：使用 web 终端的时候 有时候可以访问，有时候无法打开。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/27907749/56938824-f4bddb80-6b36-11e9-81b0-8272bf3abf1d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
设置环境变量 USE_EVENTLET=1

**Comment by ibuler** [comment]
据了解，有的系统网络不支持 EVENTLET
