### ISSUE TITLE
windows2008可以登陆，2016及2019登陆报错

### ISSUE THREAD

**Issue by sum86** [jumpserver/jumpserver#2653]
[简述你的问题]
windows2008可以登陆，2016及2019登陆报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.8-2

##### 问题复现步骤
1. [步骤1]
同一网络中的不同windowsServer版本。只有2008R2可以正常登陆。

资产管理里面针对win16及win19 单独选择了win2016

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/14838827/56948505-e5ed1e00-6b62-11e9-832d-9c569207d82d.png)

![image](https://user-images.githubusercontent.com/14838827/56948530-f604fd80-6b62-11e9-8004-7613a1b26fe3.png)
##### 其他

[注:] 完成后请关闭 issue

**Comment by amoscx** [comment]
我也遇到过这种情况，不过选择系统平台为“windows平台”后就正常了，选2016系统反而不能登录

**Comment by liuzheng** [comment]
RDP协议的锅，RDP你们可以理解为两个协议吧，就看你Windows装了那个，一般没人会在意rdp的版本，也不大会看，通俗的以Windows版本做划分，基本上解决了80%的沟通问题，剩余的，自己尝试选择另一个Windows就差不多能解决了

**Comment by sum86** [comment]
![image](https://user-images.githubusercontent.com/14838827/57528013-b8268700-7363-11e9-90ff-3f5577a08fd9.png)
果然是协议问题。我当时是按用户手册加的。改用windows的后正常。
