### ISSUE TITLE
是否可以对数据库客户端工具的支持？如PLSQL、TOAD、Navicat等

### ISSUE THREAD

**Issue by tidefly** [jumpserver/jumpserver#2660]
[简述你的问题]
现在的开源版本是否可以支持数据库客户端？如PLSQL、TOAD、Navicat等。
如果支持，如何设置？如果不支持，何时可能支持？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
xpack有remote apps功能，可以做到，是一个付费包
