### ISSUE TITLE
jumpserver在使用的过程中出现反应慢的现象

### ISSUE THREAD

**Issue by tidefly** [jumpserver/jumpserver#2661]
[简述你的问题]
jumpserver在使用的过程中出现反应慢的现象

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.10 

##### 问题复现步骤
1. [步骤1]双核cpu，内存4G，硬盘100G
2. [步骤2]CPU和内存都不高

##### 具体表现[截图可能会更好些,最好能截全]
当使用人数过多时，出现反应慢、卡顿等现象

##### 其他
以上配置可以接受多少并发？如何调整才能更好？
还有可能出现其他现象吗？如何避免？

[注:] 完成后请关闭 issue

**Comment by sky-sunny** [comment]
加一 同样遇到卡慢 就我自己用都觉得 ，主要会卡死，看日志也没啥错误

**Comment by xx-zhang** [comment]
@tidefly @sky-sunny 尝试优化下内核和nginx的访问设置。 用ab测试下链接的连接数吞吐量，
另外在卡顿时候 使用top查看下cpu内存各个进程的使用情况，再贴出来，让我么看看。 

ps: 堡垒机是设备集中管理的，一般情况下 连接人数都不会很多。

**Comment by jym503558564** [comment]
在1.5.0修复反应慢问题

**Comment by jym503558564** [comment]
新版本做了优化，请更新至最新版本~
