### ISSUE TITLE
建议：在ssh机器列表页面显示标签

### ISSUE THREAD

**Issue by awklinux** [jumpserver/jumpserver#2662]
[简述你的问题]

##### 使用版本
Version 1.4.10-2 GPLv2.

##### 建议
在ssh 机器列表页面，显示标签栏目，可以通过标签区分服务器用途、区域等

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
感谢反馈，会持续关注这个提议。

**Comment by junly917** [comment]
什么时候会更新此功能？ 这个功能还是很需要的
