### ISSUE TITLE
会报错 Server error occur, contact administrator

### ISSUE THREAD

**Issue by Rany-yilian** [jumpserver/jumpserver#2664]
创建资产管理的管理用户时，会报错
Server error occur, contact administrator

##### 使用版本
Version 1.4.10-2 GPLv2

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/25837278/57209011-3e139c80-7009-11e9-8d33-3fb442913e1e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by kun376361** [comment]
我也遇到这个问题了，今天更新到Version 1.4.10-2 GPLv2版本出现的，web页面点多个链接都会偶尔出现报错，不是100%，包括删除授权规则也提示失败。

![image](https://user-images.githubusercontent.com/31032131/57213255-d5ccb700-7018-11e9-83cd-38ea6bccbd54.png)
![image](https://user-images.githubusercontent.com/31032131/57213282-e8df8700-7018-11e9-8a95-6c29595e8300.png)

**Comment by Rany-yilian** [comment]
而且还不止这个地方，有好几个地方，都会这样，

**Comment by kun376361** [comment]
是的，web页面很多链接都会报错，试过多刷新几次可以出来。

**Comment by Rany-yilian** [comment]
那提交信息怎么办，刷新不行吧

**Comment by kun376361** [comment]
我这边报错的话，多刷新几次可以出来，再出来，再刷新，能临时使用。

**Comment by wojiushixiaobai** [comment]
@Rany-yilian 浏览器禁用缓存

**Comment by Rany-yilian** [comment]
刚用google禁用了缓存  disable cache，还是不行哈

**Comment by ibuler** [comment]
更新到 1.5.2吧

**Comment by BosonMao** [comment]
1.5.6 docker 安装好，admin 登录也显示这个问题

**Comment by chldong** [comment]
是不是不兼容弹性IP的事？
