### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by huweiqing915** [jumpserver/jumpserver#2667]
[简述你的问题]
Web Terminal连接主机时，出现Cannot read property 'toLowerCase' of undefined

##### 使用版本
1.4.10

##### 问题复现步骤
1. Web Terminal连接服务器。
2. 无任何操作，出现如上错误

##### 具体表现[截图可能会更好些,最好能截全]

![Snip20190507_5](https://user-images.githubusercontent.com/6898731/57265812-ea0dc400-70ab-11e9-9bdd-3b8c21876b48.png)
##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
浏览器清一下缓存
