### ISSUE TITLE
v1.4.8 不能查看api文档

### ISSUE THREAD

**Issue by ZandaGo** [jumpserver/jumpserver#2671]
[简述你的问题]

##### 使用版本
v1.4.8

##### 问题复现步骤
新版本的jumpserver无法查看api文档了，请问是什么原因？

PS: 配置文件已经开启了DEBUG
/docs 无法访问了，报404

##### 具体表现[截图可能会更好些,最好能截全]

# curl http://127.0.0.1/docs

<h1>Not Found</h1><p>The requested resource was not found on this server.</p>

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ZandaGo 确定打开debug后重启了jms，访问的是http://<jumpserver_url>/docs

**Comment by ZandaGo** [comment]
想重启了jms，请问是在config.yml中将日志级别改成 DEBUG吗？

# DEBUG, INFO, WARNING, ERROR, CRITICAL can set. See https://docs.djangoproject.com/en/1.10/topics/logging/
# 日志级别
LOG_LEVEL: DEBUG
# LOG_LEVEL: ERROR 
# LOG_DIR:

**Comment by wojiushixiaobai** [comment]
```
$ vi jumpserver/config.yml

...
Debug: true
```

**Comment by ZandaGo** [comment]
明白了，非常感谢
