### ISSUE TITLE
系统用户能否支持推送到指定服务器

### ISSUE THREAD

**Issue by kun376361** [jumpserver/jumpserver#2672]
[简述你的问题]

##### 使用版本
[1.4.10-2]

##### 问题复现步骤
1. [系统用户能否支持推送到指定服务器]

##### 具体表现[截图可能会更好些,最好能截全]
比如有10台服务器，我创建了一个普通账户张三，系统用户zhangsan，这个账号只需要登录服务器A，不需要登录其他9台服务器，现在10台服务器都会有zhangsan系统用户，能否只单独推送，其他9台服务器不再创建系统用户zhangsan。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kun376361 根据你的授权规则推送

**Comment by jym503558564** [comment]
问题是否已经得到解决？

根据授权规则推送。
假设你现在只需资产A,那么授权的时候资产只选A，其它资产不选即可。
