### ISSUE TITLE
web终端连接win7报错

### ISSUE THREAD

**Issue by supergmr** [jumpserver/jumpserver#2673]
[简述你的问题]

##### 1.4.10-2
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 系统内部错误，请联系管理员或查看日志
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/34016633/57346392-e8620000-7180-11e9-8358-51790f328687.png)

##### 其他
1.终端管理页面是绿色的
2.资产信息填写没问题
3.网络是通的
4.mstsc能直接连接

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@supergmr 提示内部错误，一般是网络问题

**Comment by Amoaloas** [comment]
同问，远程Windows出现上述错误
telnet 测试网络是通的  连接linux时却正常

**Comment by huweiqing915** [comment]
同问，遇到了同样的问题。网络是正常的。

**Comment by huweiqing915** [comment]
请问这个问题解决了吗 ？@supergmr

**Comment by admin-zoujing** [comment]
请问这个问题解决了没有，公布一下解决方案啊，不然连接windows就是个bug，不能用

**Comment by admin-zoujing** [comment]
问题终于找到了，centos7的开机自启服务，漏掉了一个/etc/init.d/guacd start的服务。结果一直报这个错误！！！

**Comment by archlongbelong** [comment]
> 问题终于找到了，centos7的开机自启服务，漏掉了一个/etc/init.d/guacd start的服务。结果一直报这个错误！！！
哦莫西罗伊，搞了1天没启动gua
