### ISSUE TITLE
仪表盘-在线用户和在线会话数量显示不正确

### ISSUE THREAD

**Issue by shaonblack** [jumpserver/jumpserver#2676]
[简述你的问题]
web路径：仪表盘-在线用户/在线会话
问题：在线用户/在线会话数量显示不正确
描述：从仪表盘来看只有5个在线用户，在线会话为11个，打开链接后只看到7个会话数（链接都是terminal/session-online/）。

疑问：
1.在线会话数不对
2.在线用户数在看起来也不对，7个在线会话里面只能看到4个用户，而仪表盘上面看到5个。

##### 使用版本
Version 1.4.9-2 GPLv2

##### 具体表现[截图可能会更好些,最好能截全]
![仪表盘](https://user-images.githubusercontent.com/5814892/57434485-b084b680-726d-11e9-9251-3796b5971831.png)
![在线会话](https://user-images.githubusercontent.com/5814892/57434489-b11d4d00-726d-11e9-8058-6c3aa2c84b38.png)

**Comment by liuzheng** [comment]
你时间范围选大一点，部分会话连接异常断开，数据库没更新，就这样了

**Comment by shaonblack** [comment]
@liuzheng 那这种问题有办法解决吗，最好是能刷新的时候显示正常的值

**Comment by liuzheng** [comment]
bug

**Comment by shaonblack** [comment]
😢
