### ISSUE TITLE
日志审计登陆日志异常

### ISSUE THREAD

**Issue by shaonblack** [jumpserver/jumpserver#2678]
[简述你的问题]
登陆日志上面出现很多IP为127.0.0.1的地址，Agent 为python-requests/2.18.4，这个是JumpServer内部的操作吗？

##### 使用版本
Version 1.4.9-2 GPLv2.

![微信截图_20190509150916](https://user-images.githubusercontent.com/5814892/57436161-b7adc380-7271-11e9-9981-7d299328f698.png)

**Comment by liuzheng** [comment]
云平台的漏洞扫描，你可以看一下你jumpserver主机的进程

**Comment by shaonblack** [comment]
> 云平台的漏洞扫描，你可以看一下你jumpserver主机的进程

ok 谢谢
