### ISSUE TITLE
EMAIL_USE_SSL不会保存到settings_setting

### ISSUE THREAD

**Issue by lyb610** [jumpserver/jumpserver#2679]
[简述你的问题]
修改设置-> 邮件 -> ssl勾选后，测试邮件发送成功，但是新增用户时celery发送邮件失败.
查看数据库发现settings_setting里面不保存EMAIL_USE_SSL,

手动插入EMAIL_USE_SSL为true

新增用户时邮件发送成功.

##### 使用版本
1.4.10

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by alexdu828** [comment]
EMAIL_USE_SSL在哪个文件中
