### ISSUE TITLE
手动登录RDP资产失败

### ISSUE THREAD

**Issue by 7cristiano** [jumpserver/jumpserver#2687]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. 同一台RDP资产，系统用户用自动登录的模式可以登录到资产
2. 系统用户改用手动登录时提示“无法连接服务器，请联系管理员或查看日志”

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@7cristiano 资产远程设置，需要打开较不安全的那个选项

**Comment by 7cristiano** [comment]
已经是打开的，
![image](https://user-images.githubusercontent.com/33511216/58392285-daaae680-806b-11e9-9d65-fdacfc16688a.png)

**Comment by jym503558564** [comment]
@7cristiano 请确认windows资产
![image](https://user-images.githubusercontent.com/40739051/59895101-dfb64800-9415-11e9-9dde-11bd851634db.png)

**Comment by jym503558564** [comment]
问题是否得到解决？

**Comment by 7cristiano** [comment]
操作系统选的没错，已经改成自动登录模式了

**Comment by lvshuishangshang** [comment]
见了鬼，gua显示的是在线，但是连接Windows2012r2就是显示无法连接服务器，请联系管理员或者查看日志，看了docker日志也没有报错

**Comment by zcchinese** [comment]
解决好了吗
