### ISSUE TITLE
v1.4.10 使用SSH客户端

### ISSUE THREAD

**Issue by lvgang214** [jumpserver/jumpserver#2688]
安装了1.4.10-2 GPLv2.  资产添加好了之后，创建好用户，登录可以使用web终端去登录，怎么使用SSH客户端 链接的 ？  我手动添加了秘钥 也提示我没有注册秘钥，怎么配置可是使用SSH客户端连接堡垒机。

**Comment by investoday2019** [comment]
同问

**Comment by wojiushixiaobai** [comment]
@lvgang214 @lvgang214 
ssh user@cocoserver -p2222

**Comment by jym503558564** [comment]
演示如下：
![image](https://user-images.githubusercontent.com/40739051/58849678-ddd25200-86bd-11e9-864a-751cd596bc39.png)
![image](https://user-images.githubusercontent.com/40739051/58849696-f17db880-86bd-11e9-8724-8628ac14b74f.png)
