### ISSUE TITLE
[功能求助]jumpserver 日志审计如何定期导出，或者将其以邮件发送出去？

### ISSUE THREAD

**Issue by 932340583** [jumpserver/jumpserver#2689]
[简述你的问题]
jumpserver具有强大的日志审计功能，但是只能在web ui上手动导出，如何做到定期自动导出并以邮件形式发送给某个用户？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@932340583 临时写个脚本定期从接口爬？

**Comment by 932340583** [comment]
我看了下api文档，发现好像从jumpserver.terminal_command可以直接导出来，这下省事儿多了，哈哈。
