### ISSUE TITLE
机器数量比较多coco获取机器列表60秒后就会中断连接

### ISSUE THREAD

**Issue by maoxiaochun** [jumpserver/jumpserver#2690]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@maoxiaochun 请说明一下版本，如果coco log中有报错的话请脱敏后一起附上

**Comment by ibuler** [comment]
新版本1.5.2 优化了获取资产逻辑
