### ISSUE TITLE
隐藏左边栏windows不全屏显示

### ISSUE THREAD

**Issue by huweiqing915** [jumpserver/jumpserver#2693]
[简述你的问题]
在web terminal控制台点击隐藏左边栏，windows页面不全屏显示。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.10
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![Snip20190514_11](https://user-images.githubusercontent.com/6898731/57676693-af7dcb80-7657-11e9-8151-f83412ef0707.png)
![Snip20190514_13](https://user-images.githubusercontent.com/6898731/57676706-b60c4300-7657-11e9-9ed1-7480ae9d869e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@huweiqing915 等待后面的版本修复

**Comment by jym503558564** [comment]
已修复.
![image](https://user-images.githubusercontent.com/40739051/58846903-73b4af80-86b3-11e9-9e3e-1e56ef10f3f4.png)
