### ISSUE TITLE
请问下目前版本如何连接switch设备

### ISSUE THREAD

**Issue by jimmag** [jumpserver/jumpserver#2694]
[简述你的问题]

##### 使用版本
Version 1.4.9-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jimmag** [comment]
ssh通道的switch可以  但是telnet 不行，协议选择telnet的系统平台怎么选，报认证失败

**Comment by wojiushixiaobai** [comment]
@jimmag 参考 [Telnet 使用说明](http://docs.jumpserver.org/zh/docs/faq_telnet.html)
