### ISSUE TITLE
远程桌面上传100M限制怎么处理

### ISSUE THREAD

**Issue by amoscx** [jumpserver/jumpserver#2696]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.9

##### 问题复现步骤
RDP连接windows远程桌面时，上传文件有100MB的限制，超过100MB会报错，请问怎么解除这个限制？
![微信截图_20190514230829](https://user-images.githubusercontent.com/34751745/57745867-66825180-7701-11e9-806d-451cb7eed7da.png)

**Comment by wojiushixiaobai** [comment]
@amoscx nginx

**Comment by jym503558564** [comment]
通过修改nginx，问题是否得到解决？

**Comment by amoscx** [comment]
问题已解决，谢谢
