### ISSUE TITLE
Mozilla Firefox浏览器(62.0.2 64位)文件管理界面显示bug

### ISSUE THREAD

**Issue by mrdotyong** [jumpserver/jumpserver#2697]
[简述你的问题]

##### 使用版本
Version 1.4.9-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![bug](https://user-images.githubusercontent.com/48610245/57820329-e15d7200-77be-11e9-983c-111e1889d4fd.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
1.复现概率？
2.其它版本浏览器是否会出现？

**Comment by huang394070956** [comment]
我也会，升级完就这样

**Comment by huang394070956** [comment]
版本是1.4.6，按官方文档升级到最新版1.5.1，升级完成后就这样
![image](https://user-images.githubusercontent.com/50479425/61285319-4a7b5900-a7f3-11e9-9af5-ac1a0addb19b.png)

**Comment by jym503558564** [comment]
只在Mozilla Firefox浏览器(62.0.2 64位)版本会出现？其它浏览器或其它版本是否也复现此问题？

**Comment by ibuler** [comment]
高度问题已确认，新koko中修复
