### ISSUE TITLE
coco ldap 登陆功能修复

### ISSUE THREAD

**Issue by hjlloveff** [jumpserver/jumpserver#2699]
[简述你的问题]
登陆用户可以同步到系统用户么？
如何使用系统用户登陆coco认证？
coco可以不需要验证jumpserver里面的系统用户的密码功能么？

##### 使用版本
coco1.4.10
jumpserver 1.4.10

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by hjlloveff** [comment]
ldap 写入 ldap 的password ！UpiemXojp5Yjdn3vdlX0oKWtcCHkBjmkRb0RDVop 
系统用户写入 password eyJhbGciOiJIUzI1NiJ9.ImZkZmRmZCI.s8jnQER-Ljm9EcDFNZklefpCCGuV67EXb1Ms9Z9yq5M  jws 
这两个密可以关联起来么 ，那样 系统用户也可以登陆了

**Comment by wojiushixiaobai** [comment]
@hjlloveff 参考一下网上的二次开发文档，把系统用户的代码修改下
