### ISSUE TITLE
Upload big files (more than 100 Megabyte) jumpserver web get "Server responded with 0 code."

### ISSUE THREAD

**Issue by tntxyz** [jumpserver/jumpserver#270]
Chrom browser use F12 console get the problem below:
dropzone.js:1449 POST http://xxx.xxx.xxx.xxx:8000/file/upload/ net::ERR_CONNECTION_ABORTED
Dropzone.uploadFiles 
@ dropzone.js:1449Dropzone.processFiles 
@ dropzone.js:1255Dropzone.processQueue 
@ dropzone.js:1228(anonymous function) 
@ (index):361
so how can I fix this problem? how can I upload big files ?

**Comment by ibuler** [comment]
It's because Tornado doesn't support upload file more than 100M.
So we should upload file cross it.

1. start django server
python manage.py runserver 127.0.0.1:8083

2. nginx.conf

location /file/upload/ {
        proxy_pass http://127.0.0.1:8083;
}

**Comment by tntxyz** [comment]
Problem have already resolved！ Thanks ibuler Lao Guang!

**Comment by jiabin1994** [comment]
请问你是怎么解决的，分两个登陆吗 一个进行上传 一个进行远程
