### ISSUE TITLE
ssh客户端首次连接时，请求获取用户权限资产接口时很慢

### ISSUE THREAD

**Issue by linuxu2015** [jumpserver/jumpserver#2700]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.10
##### 问题复现步骤
ssh客户端首次连接时，请求获取用户权限资产接口时很慢，具体接口如下：
http://jumpserver/api/perms/v1/user/e67bab82-8295-47d7-a5a3-5518668a8975/assets/?cache_policy=1
目前有1700台机器，每次请求需要30+秒。
复现步骤：
1. [步骤1]
浏览器模拟请求这个接口，通过F12发现请求完成一共耗时33秒
经过代码中添加logger.debug发现是如下代码耗时
![image](https://user-images.githubusercontent.com/12248480/57971260-3f0bdd00-79be-11e9-9d17-a22f06489efb.png)
![image](https://user-images.githubusercontent.com/12248480/57971414-5350d980-79c0-11e9-97a0-287446032e7f.png)

通过打印时间差发现，每个for循环差不多耗时0.01秒，一个资产需要运行一个for循环，加上node节点，基本和总耗时对上了。
##### 其他
jumpserver机器配置：
内存：64G
cpu：24核 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
硬盘：1.8T
coco目前在两个机器上分别部署了一个（包括jumpserver所在机器）
另外这个请求在新打开ssh客户端标签时上有时会有有时有没有，目前没有发现什么规律，复制的标签有的还是会请求

[注:] 完成后请关闭 issue

**Comment by PostgreSQL1989** [comment]
之前用的v1.4.8，用起来挺快的，升级到v1.4.10，感觉明显慢了

**Comment by ontherd** [comment]
我也是，升级到 1.4.10后，无规律的在字符界面 Opt> 提示符后卡顿。比如输入 p 获取主机列表，卡顿几十秒；输入主机 IP 地址，卡顿等待15秒（界面有连接主机使用时间），然后继续继续卡顿，然后登陆成功。我上面描述的也都是无规律的出行。

**Comment by ibuler** [comment]
1.5.0已修复

**Comment by linuxu2015** [comment]
> 1.5.0已修复

升级到1.5.0之后的确好了，目前最慢的话4秒，基本都是新开窗口或长时间闲置。
另外能否说下在哪种情况下会重新获取，哪种情况下又会从缓存中读取，因为权限变更不会很频繁，即使有变更也可以通过R实现手动刷新。

**Comment by ibuler** [comment]
当授权规则变化时会失效所有缓存，缓存默认有效时间1小时，配置文件可以更改
