### ISSUE TITLE
是否支持推送系统任务到交换机设备上？

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#2704]
Version: 1.4.10
问题描述：目前华为和思科交换机可以通过ssh2.0协议正常登录，但是无法通过ansible推送任务到交换机上，比如远程执行命令、备份日志等，测试资产连接性也是报错状态，所以请问交换机目前是否支持Ansible？如果不支持，是否有进一步支持的开发计划，谢谢～

**Comment by xx-zhang** [comment]
远程执行的命令 要有命令才能执行啊。 比如有可能交换机系统没有`ls -alh`这种命令，当然就不能看到`subprocess`通过调用ssh执行远程命令返回的内容了。

**Comment by wojiushixiaobai** [comment]
@gengkeye 目前是通过ansible下发的命令

**Comment by gengkeye** [comment]
> 远程系统中执行的命令 要远程的设备有命令才能执行啊。 比如有可能交换机系统没有`ls -alh`这种命令，当然就不能看到`subprocess`通过调用ssh执行远程命令返回的内容了。

大哥，我执行的是交换机的命令啊。。

**Comment by gengkeye** [comment]
> @gengkeye 目前是通过ansible下发的命令

那为啥测试连接性是不通的呢～但是coco是可以登录的

**Comment by gengkeye** [comment]
@wojiushixiaobai 
https://docs.ansible.com/ansible/latest/modules/list_of_network_modules.html#ios?extIdCarryOver=true&sc_cid=701f2000001OH7YAAW

这个是ansible网络的模块，其中有Huawei和Cisco设备相关的模块，不知道你们是否是按照这个做的

**Comment by wojiushixiaobai** [comment]
@gengkeye 目前没有加入telnet设备的相关推送命令，主要是不同的厂商，命令都不太一样，一一做适配的话有点麻烦，这个问题我会提上去。

**Comment by gengkeye** [comment]
> @gengkeye 目前没有加入telnet设备的相关推送命令，主要是不同的厂商，命令都不太一样，一一做适配的话有点麻烦，这个问题我会提上去。

好的，感谢您的回复
