### ISSUE TITLE
celery task装饰器问题询问。就是这些函数的作用和意义

### ISSUE THREAD

**Issue by xx-zhang** [jumpserver/jumpserver#2705]
[简述你的问题]
[_after_app_shutdown_clean_periodic_tasks](https://github.com/jumpserver/jumpserver/search?q=_after_app_shutdown_clean_periodic_tasks&unscoped_q=_after_app_shutdown_clean_periodic_tasks)

这个函数的作用范围是什么，我先在就看出来了那个 register_as_period_task 就看出了这个函数是收集 beat 的，其他两个before_app和after_app没看出来是什么功能。求告知下，用过celery, 但是这种逻辑的celery看起来不算好看。所有的只有share_task的都是异步操作的retrive任务。带了period的就是beat收集的的是吧。 

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@after_app_shudown_clean_periodic 装饰器代表是等app结束以后删除建立的定时任务
@after_app_ready_start 等app ready以后启动任务
@django_ready 等项目完成启动且数据库连接上以后再启动任务

**Comment by xx-zhang** [comment]
@ibuler 我很久前都已经看懂了
