### ISSUE TITLE
删除（或设定删除）老的录像档

### ISSUE THREAD

**Issue by ruilung** [jumpserver/jumpserver#2707]
[简述你的问题]
问在那可以删除（或设定删除）老的录像档

##### 使用版本
1.4.4

##### 问题复现步骤
问在那可以删除（或设定删除）老的录像档

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
录像存在 JUMPSERVER_DIR/data/media目录下，可以手动删除一下

**Comment by ruilung** [comment]
ok. thanks. ^^
