### ISSUE TITLE
CSS 中的微软雅黑字体导致 Web Terminal 显示不是等宽字体

### ISSUE THREAD

**Issue by wzxjohn** [jumpserver/jumpserver#271]
由于在 templates/jlog/web_terminal.html 中字体的定义是这么写的:
`font-family: "Monaco", "Microsoft Yahei", "DejaVu Sans Mono", "Liberation Mono", monospace;`
导致如果 Windows 的机器没有安装 Monaco 字体的话，会回落到 Microsoft Yahei 这个非等宽字体上，导致显示效果是非等宽的 Terminal。建议将 "Microsoft Yahei" 这个非等宽字体从列表中去除，或者修改顺序，不要 Monaco 没有就直接回落到雅黑。

**Comment by liuzheng712** [comment]
好的，由于开发时我都是mac，等宽字体我会再找个和谐点的，谢谢反馈

**Comment by liuzheng712** [comment]
都太丑，麻烦自行下载monaco吧
