### ISSUE TITLE
/etc/init.d/guacd start在centos7上开机自启服务脚本开发人员尽快完善

### ISSUE THREAD

**Issue by admin-zoujing** [jumpserver/jumpserver#2719]
[简述你的问题]
centos7开机自启服务漏掉一个，/etc/init.d/guacd start，最终连接windows服务器报系统内部错误，希望开发人员的安装文档尽快完善此服务的开机自启服务脚本。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.10
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
连接windows服务器报系统内部错误

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
文档中已经包含下面命令，请仔细检查是否遗漏
http://docs.jumpserver.org/zh/docs/start_automatically.html
```
$ chkconfig guacd on

**Comment by admin-zoujing** [comment]
chkconfig guacd on与众不同，看漏了，最好写成systemd的开机启动

**Comment by admin-zoujing** [comment]
1、建议#Guacamole开机自启的服务改一下，改成这样：Environment="JUMPSERVER_SERVER=http://127.0.0.1:8080" "JUMPSERVER_KEY_DIR=/config/guacamole/keys" "GUACAMOLE_HOME=/config/guacamole" "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN"
2、开机自启服务也完善一下，改成这样：
# 开机自启设置
$ systemctl enable jms
$ systemctl enable coco
$ chkconfig guacd on
$ systemctl enable guacamole

# 启动
$ systemctl start jms
$ systemctl start coco
$ /etc/init.d/guacd start
$ systemctl start guacamole

# 停止
$ systemctl stop jms
$ systemctl stop coco
$ /etc/init.d/guacd stop
$ systemctl stop guacamole

**Comment by wojiushixiaobai** [comment]
@admin-zoujing 
.....
抱歉，建议你这边尝试一下。。如果可以读到变量，那这里还写干嘛。。。

**Comment by admin-zoujing** [comment]
亲测，能读到变量，可以写成这样

**Comment by wojiushixiaobai** [comment]
@admin-zoujing 建议参考systemd文档，有详细说明，之前的测试结果是读不了。如果可以的话，请验证一下，如何验证

````
1. 在 web 删掉 guacamole 组件的注册，删掉 /confog/guacamole/keys/*
2. 在 ~/bashrc 注释掉 BOOTSTRAP_TOKEN
新增 test_key = 你实际的token指
3. 修改 Environment 的 BOOTSTRAP_TOKEN=$test_key
4. 设置自启，重启jumpserver（可以不用自启，确定环境变量没有BOOTSTRAP_TOKEN即可），看guacamole是否能自动注册
````
