### ISSUE TITLE
批量执行命令的时候，不能换行

### ISSUE THREAD

**Issue by 9527chu** [jumpserver/jumpserver#272]
![piliangmingling](https://cloud.githubusercontent.com/assets/4241041/16572690/ecae6974-429d-11e6-9151-77add3865c83.png)

批量执行命令的时候，如果命令的长度比较长，需要换行的话，第二行的输入就会直接覆盖提示符。
个人的解决办法是去掉提示符（cmd>）的颜色就不会出问题，可能还会有比较好的解决办法，暂时未发现。

**Comment by ibuler** [comment]
收到
