### ISSUE TITLE
windows 白屏

### ISSUE THREAD

**Issue by kcxg** [jumpserver/jumpserver#2723]
[简述你的问题]
windows 白屏

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.10]

##### 问题复现步骤
查看配置没发现问题

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/31840413/58179261-69b9a680-7cda-11e9-979a-1afbc21b8f09.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kcxg 白屏表示guacamole无法访问，请自行检查nginx与guacamole是否设置有误
