### ISSUE TITLE
设置Django Rest 框架的PAGE_SIZE导致资产树变成undefined

### ISSUE THREAD

**Issue by pythonwood** [jumpserver/jumpserver#2724]
[简述你的问题]
不能兼容DRF的分页设置，资产树变UNDEFINED
设置Django Rest 框架的PAGE_SIZE导致资产树变成undefined
注释分页就恢复

##### 使用版本
master分支
a025930 - (grafted, HEAD, origin/master, origin/HEAD, master) Merge pull request #2642 from jumpserver/dev

##### 问题复现步骤
1、git checkout master分支
2、修改settings，添加
`
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5
,
访问/ops/command-execution/start/等地方

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/5157880/58224033-a6bf8080-7d4e-11e9-920c-08349a4c7f02.png)

##### 其他
怪不得原来注释了
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'PAGE_SIZE': 15

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- settings里设置的‘DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination’是对全局进行设置分页。
- 在本项目中例如资产树资源是不需要分页的，所以注视掉全局的分页设置。改为局部资源分页设置。在需要分页的资源对应的api视图加上分页设置` pagination_class = LimitOffsetPagination`

- 'PAGE_SIZE': 15，如您这边有需求可打开，在调api的时候，会返回您想要设置的资源数量。

**Comment by jym503558564** [comment]
这边是否能解决到您的困惑，如有其它问题可重新打开issues～
