### ISSUE TITLE
资产导出时报错

### ISSUE THREAD

**Issue by emperorente** [jumpserver/jumpserver#273]
版本0.3.1，查看资产选择导出时报500错误
错误信息：
IOError at /jasset/asset/list/
[Errno 2] No such file or directory: 'static/files/excels/cmdb_excel_2016_07_07_10_39.xlsx'

**Comment by jiaxiangkong** [comment]
请更新到v0.3.2

**Comment by leon8693** [comment]
我的报错是一样的
Centos 7.3 
jumpserver 0.3.2
还是一样的报错
IOError at /jasset/asset/list/
[Errno 2] No such file or directory: 'static/files/excels/cmdb_excel_2017_08_23_16_34.xlsx'

**Comment by leon8693** [comment]
更新,版本是0.3.2-rc released
