### ISSUE TITLE
请问guacamole可以换目录吗？

### ISSUE THREAD

**Issue by goldstrike77** [jumpserver/jumpserver#2732]
[简述你的问题]
必须在/config/guacamole吗？我试过export GUACAMOLE_HOME到其他目录但是guacd不认可。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@goldstrike77 代码里面限制了目录，目前不开放接口
