### ISSUE TITLE
LDAP user 导入成功 无法登陆

### ISSUE THREAD

**Issue by wanglixiang90** [jumpserver/jumpserver#2740]
openLDAP 配置完成，通过测试，可以导入ldap用户，但是ldap 用户无法通过登陆，ldap user 密码加密方式为 SSHA1 ，jumpserver 1.4.10 版本

**Comment by smarttang** [comment]
同样无法登陆。。。尴尬了。。

**Comment by smarttang** [comment]
算了，也没人处理，还是买商业的吧老弟。

**Comment by wojiushixiaobai** [comment]
@wanglixiang90 @smarttang 参考[LDAP 使用说明](http://docs.jumpserver.org/zh/master/faq_ldap.html)
确定填写内容无误，提问题请一定要详细，否则无法解答

**Comment by smarttang** [comment]
> @wanglixiang90 @smarttang 参考[LDAP 使用说明](http://docs.jumpserver.org/zh/master/faq_ldap.html)
> 确定填写内容无误，提问题请一定要详细，否则无法解答

我这边没问题了，测试通过了。在绑定CN的时候，我这边没有CN，只有uid，所以跟说明不一样，现在自己摸索出来了。

**Comment by yauuzi** [comment]
我这边也是 可以导入用户，无法登录。user = self.authenticate_ldap_user(ldap_user, password) 认证的时候返回none。Authenticate user: None 账号密码确认是对的。谁能帮忙解决下么？ jumpserver Version 1.5.0-2 GPLv2.
