### ISSUE TITLE
cocod 启动报错

### ISSUE THREAD

**Issue by zdong08** [jumpserver/jumpserver#2743]
[简述你的问题]
启动codod 发现报这个错，cpu和内存的使用率会上升

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
启动codod 发现报这个错，cpu和内存的使用率会上升
![image](https://user-images.githubusercontent.com/13311479/58471668-fc44c480-8176-11e9-9c14-b4f504e00cbd.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zdong08 
```
cd /opt/coco
source /opt/py3/bin/activate
./cocod stop
ps aux | grep cocod | awk '{print $2}' | xargs kill -9
./cocod start 
```
如果jms也异常，也使用上面的这种方式结束后，重启即可

**Comment by jym503558564** [comment]
@zdong08 问题是否已得到解决～
