### ISSUE TITLE
使用top vim等命令会影响命令审计内容

### ISSUE THREAD

**Issue by luckychelsea** [jumpserver/jumpserver#2746]
[简述你的问题]
使用top vim等命令会影响命令审计内容

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver coco 1.4.7

##### 问题复现步骤
当使用top vim 等状态停留命令时命令审计会出现很多非用户输入的字符

##### 具体表现[截图可能会更好些,最好能截全]

ID	命令	用户	资产	系统用户	会话	日期
1	Swap: 2064380k total,	admin	字符资产	root	转到	2019-05-29 07:33:52
2	[6;1HPID to kill: ldkdslakksdjfljasd	admin	字符资产	root	转到	2019-05-29 07:33:45
3	top	admin	字符资产	root	转到	2019-05-29 07:33:44

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时还没有好的处理方案
