### ISSUE TITLE
如何连接Oracle数据库之类的资产？

### ISSUE THREAD

**Issue by JayceLau** [jumpserver/jumpserver#2759]
[简述你的问题]
我有很多的Oracle数据库服务器，有很多的开发、运维人员，需要使用图形界面的Pl/SQL Developer连接数据库，如何实现呢？

**Comment by wojiushixiaobai** [comment]
@JayceLau 目前还未实现

**Comment by JayceLau** [comment]
V1.5.0的远程应用不是这个吗？

**Comment by wojiushixiaobai** [comment]
@JayceLau remoteapp可以间接达到你的目的，如果需要使用的话可以联系  support@fit2cloud.com 试用 license

**Comment by JayceLau** [comment]
重定向至 https://github.com/jumpserver/jumpserver/issues/2760
