### ISSUE TITLE
V1.5.0如何配置远程应用？

### ISSUE THREAD

**Issue by JayceLau** [jumpserver/jumpserver#2760]
[简述你的问题]
看到今天更新了V1.5.0版本，新增了RemoteApp功能，但是安装完成之后未在管理页面找到配置的远程应用的入口？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
V1.5.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/16794535/58648607-a7eb4180-833c-11e9-8464-48b0ba4371e2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@JayceLau xpack功能，非开源组件

**Comment by JayceLau** [comment]
这一块有说明吗？能提供试用版本吗？怎么付费？

**Comment by wojiushixiaobai** [comment]
@JayceLau 请联系 support@fit2cloud.com 试用 license

**Comment by JayceLau** [comment]
能具体说明一下远程应用这个功能吗？我看你在另外问题里说连图形界面还未实现，远程应用不是这个吗？我把另外一个关了，都在这个回复吧

**Comment by wojiushixiaobai** [comment]
@JayceLau remoteapp 是windows server的一个功能，通过这个功能用户可以访问windows server发布的app，而不需要登陆到服务器。

目前jumpserver还不支持管理应用，可以通过remoteapp间接达到你的目的。

**Comment by JayceLau** [comment]
好的，感谢！另外，上午发了申请试用License的邮件，还未收到回复。

**Comment by JayceLau** [comment]
仍未回复。。。
