### ISSUE TITLE
希望在未来版本中能解决

### ISSUE THREAD

**Issue by zhezhe101** [jumpserver/jumpserver#2764]
1.在jumpserver创建的系统用户，推送到机器后，默认是普通组，这个在freebsd系统里，用户是不能su切换到root用户的，还须vi /etc/group，在wheel组中添加普通用户，希望创建系统用户时，如果是freebsd系统能多一个选项，解决此访问。

2.关于jumpserver高可能，希望能得到支持，能像很多防火墙里面那样简单几步就可以设置好，没有高可用，生产线上几百几千台服务器根本不敢用jumpserver，更加阻碍了jumpserver在大环境下的应用测试和发展。

3.当一个用户需要登录Linux、Windows 不同类型资产时，目前的解决办法是分别给 Linux 资产和 Windows 资产创建授权规则，希望未来版本中有更好的改进。

4.windows系统，目前不支持帐号推送，所以需要手动增加用户，上千台服务器，这有点不太可能。jumpserver既然有对windows支持，就应该支持彻底，增加用户基本都还没解决，windows这块所以基本生产环境不能用。

**Comment by wojiushixiaobai** [comment]
@zhezhe101 已收到，感觉反馈。

**Comment by bottlelee** [comment]
顺便也提一下，既然 jumpserver 使用了 ansible，能否提供一个允许 ansible 透过 jumpserver 去连接服务器的 module？
我现在就头疼这个，一旦启用 jumpserver，无法使用 ansible 来远程批量运维了。

**Comment by ibuler** [comment]
@bottlelee 不建议ansible任务通过jumpserver来做，毕竟ansible是很频繁的，也无法审计其中操作

**Comment by ibuler** [comment]
1. 这个比较好解决
2. 高可用需要自己来实践
3. 不同资产类型建议分开授权，容易管理，其实不分开授权也可以，同时授权两个系统用户
4. windows的推送下个版本可以解决

**Comment by bottlelee** [comment]
> @bottlelee 不建议ansible任务通过jumpserver来做，毕竟ansible是很频繁的，也无法审计其中操作

OK，那折中的办法就是通过 jumpserver 登录到集群后，选择其中一台服务器作为 ansible controller 了。
