### ISSUE TITLE
命令日志存储到 ES 问题

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#2766]
[简述你的问题]
在 终端设置 - 系统设置 中配置 命令日志存储到 es，已经确定 es 有数据。
但是在 会话管理 - 命令记录中查不到，通过修改 apps/jumpserver/settings.py 解决。

请问，怎样才是正确的配置？文档里也没提。

##### 使用版本
1.5.0

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3265516/58699482-c8aca900-83c7-11e9-8d43-a6250bb8c763.png)

**Comment by linuxu2015** [comment]
我也遇到了这个问题，请问按照你的这个配置文件是可以正常看到的吗？

**Comment by linuxu2015** [comment]
> [简述你的问题]
> 在 终端设置 - 系统设置 中配置 命令日志存储到 es，已经确定 es 有数据。
> 但是在 会话管理 - 命令记录中查不到，通过修改 apps/jumpserver/settings.py 解决。
> 
> 请问，怎样才是正确的配置？文档里也没提。
> 
> ##### 使用版本
> 1.5.0
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> ![image](https://user-images.githubusercontent.com/3265516/58699482-c8aca900-83c7-11e9-8d43-a6250bb8c763.png)

按照你的这个修改后，果然可以在命令记录中看到了，但是历史会话中的命令数量还是显示0，你那边是什么情况呢？

**Comment by huangzx** [comment]
我也一样的情况。等官方回答了。

**Comment by huangzx** [comment]
我也一样的情况。等官方回答了。

**Comment by linuxu2015** [comment]
> 我也一样的情况。等官方回答了。

我发现按照这个配置页面上只能显示最新的10个命令。然后就滚动覆盖了。

**Comment by wojiushixiaobai** [comment]
@huangzx 这个问题再之前的版本就已经出现了，目前还未修复，感谢反馈。
修复后，会写入更新日志里面。
