### ISSUE TITLE
总结JMS_v0.3.2问题

### ISSUE THREAD

**Issue by jiaxiangkong** [jumpserver/jumpserver#277]
版本0.3.2 ：

1.推送用户到服务器数量过多导致超时

2.批量导入几千台机器进去，后台都打不开了

3.批量执行命令,命令长度比较长需要换行,第二行的输入就会直接覆盖提示符。
个人的解决办法是去掉提示符（cmd>）的颜色就不会出问题，见Issues#272

4.有时通过终端批量上传会出现一堆乱码,见Issues#203

5.命令过长导致命令统计不能显示全，录像回放没有问题 

6.终端登陆客户端，vim 编辑文本，一行内容过长，实时监控和录像回放会显示会丢内容

7.客户端通过rz上传文件成功时，录像回放这过程是乱码，也就是审计录像回放看不出用户上传了什么文件，而看到是乱码

8.当客户端系统语言不是LANG="zh_CN.UTF-8"，比如webssh输入有中文时，执行命令如sudo su -可能会引起一些问题

9.上传大文件失败，受限于tornado框架影响

10.连接时间跨天的问题，创建tty日志文件失败, 请修改目录/opt/jumpserver/logs/tty/20160614权限，
可以通过创建计划任务，定时修改日志权限。
vim date.sh 

```
mkdir /opt/jumpserver/logs/tty/$(date +%Y%m%d)
chmod -R 777 /opt/jumpserver/logs/tty/$(date +%Y%m%d)
```

crontab -l
1 0 \* \* \* /root/date.sh

**Comment by daxuehu** [comment]
安装后启动服务报错，请问在哪里可以查看日志，找到错误原因？
