### ISSUE TITLE
1.5.0，urllib3版本冲突问题

### ISSUE THREAD

**Issue by wonxin** [jumpserver/jumpserver#2771]
1.5.0 urllib3版本冲突问题

elasticsearch 6.1.1 与 jms-storage 0.0.23 要求的 urllib3 版本冲突

##### 使用版本
jumpserver 1.5.0

##### 问题复现步骤
1) 执行 pip install -r requirements/requirements.txt

   提示：
   elasticsearch 6.1.1 has requirement urllib3<1.23,>=1.21.1

   但requirements.txt 文件里要求 urllib3==1.25.2

2) 将 requirements.txt 文件里 urllib3 换成 1.22, 
    执行 pip install -r requirements/requirements.txt

   提示：
   jms-storage 0.0.23 has requirement urllib3==1.25.2

**Comment by vitaureatea** [comment]
我也遇到了这个问题。。。。。。。。。。。。。。。。。。。

**Comment by ibuler** [comment]
升级一下elasticsearch到 7.0.2版本

**Comment by wonxin** [comment]
> 升级一下elasticsearch到 7.0.2版本

将 elasticsearh 从 6.1.1 替换为 7.0.2，执行依旧报错：

sed -i 's/elasticsearch==6.1.1/elasticsearch==7.0.2/' requirements/requirements.txt
pip3 install -r requirements/requirements.txt

提示：
ERROR: jms-storage 0.0.23 has requirement elasticsearch==6.1.1

**Comment by wonxin** [comment]
目前情况：

jms-storage 0.0.23 需要：
    elasticsearch==6.1.1
    urllib3==1.25.2

但 elasticsearch==6.1.1 需要 urllib3<1.23,>=1.21.1， 与 urllib3==1.25.2 冲突

**Comment by Cuigeek** [comment]
我也会遇到同样问题 目前没有找到解决方案

**Comment by wojiushixiaobai** [comment]
@wonxin @Cuigeek 忽略即可， 不影响正常使用。

**Comment by wonxin** [comment]
@wojiushixiaobai 
忽略安装错误，目前运行正常。不过还是希望在以后版本解决这个错误。
等后续有问题再反馈，这个issue先关了。
