### ISSUE TITLE
“系统用户”去掉关联的节点资产

### ISSUE THREAD

**Issue by rexlibing** [jumpserver/jumpserver#2772]
[简述你的问题]
在“系统用户”去掉关联的节点资产无效。web终端多用户不出现用户选择，用户优先级都是一样的。

##### 使用版本
[请提供你使用的Jumpserver版本 Version 1.5.0-2 GPLv2]

##### 问题复现步骤
1. 在“系统用户”去掉关联的节点资产无效，点击系统用户关联的设备数未发生变化
2. web终端多用户不出现用户选择，用户优先级都是一样的。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16685466/58873118-27d82980-86f8-11e9-93fc-595ed348953a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@rexlibing 问题1已经知道，感谢反馈。问题2无法复现，请确认下授权

**Comment by rexlibing** [comment]
更换回了1.4.9

**Comment by xiaoyou2018** [comment]
你好，请问问题1现在的Version 1.5.2-2 GPLv2版本解决了吗？我也出现了这个问题

**Comment by rexlibing** [comment]
没有，我换回了1.4.9版



---原始邮件---
发件人: "xiaoyou2018"<notifications@github.com>
发送时间: 2019年7月31日(星期三) 晚上7:16
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "State change"<state_change@noreply.github.com>;"rexlibing"<rex-lee@qq.com>;
主题: Re: [jumpserver/jumpserver] “系统用户”去掉关联的节点资产 (#2772)



你好，请问问题1现在的Version 1.5.2-2 GPLv2版本解决了吗？我也出现了这个问题
