### ISSUE TITLE
通过web终端luna远程连接windows，无法通过Ctrl+C复制本地内容到目标windows主机

### ISSUE THREAD

**Issue by ballghost** [jumpserver/jumpserver#2774]
[简述你的问题]
通过web终端luna连接远程windows，无法通过Ctrl+C复制本地内容后到目标windows主机进行Ctrl+V粘贴，现有的以下粘贴方式实在是难用！！

目前粘贴方式：Ctrl+Shift+Alt的方式进行中转复制粘贴，非常的不符合习惯！！！

希望能采用常规方式（Ctrl+C和Ctrl+V）实现！

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ballghost 正在努力，请等待功能更新。

**Comment by immikez** [comment]
支持这个功能，但愿早点实现。

**Comment by czxin788** [comment]
静静等待复制粘贴功能有新进展
