### ISSUE TITLE
在线会话，中断动作对rdp会话无效

### ISSUE THREAD

**Issue by muse117** [jumpserver/jumpserver#2775]
[简述你的问题]
1、在线会话，中断动作对rdp会话无效。
2、可否在线会话动作中增加实时监控功能？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. [步骤1]
rdp登录资产
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![微信截图_20190605110230](https://user-images.githubusercontent.com/9733486/58927517-85fd1f00-8781-11e9-828f-d8582c55ce24.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@muse117 问题1需要等待功能更新，问题2我会反馈上去。感谢反馈。

**Comment by muse117** [comment]
> @muse117 问题1需要等待功能更新，问题2我会反馈上去。感谢反馈。

好的，谢谢，请问问题2是否已经在开发计划中？开发周期需要多久？实时监控功能应该算是核心功能。
