### ISSUE TITLE
资产登录时系统用户串了

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#2777]
[简述你的问题]
我有两个用户A，B，在登录堡垒机后，选择资产，然后再选择系统用户的时候，
A用户选择B系统用可以登录，反之，B用户也可以选择A系统用户登录资产，互相串了。

这是什么原因？

##### 使用版本
Version 1.4.6-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
连接资产是根据资产授权规则推送系统用户

**Comment by brucegogo** [comment]
我是自建的系统用户，没有推送。系统用户设定的自动登录

**Comment by wojiushixiaobai** [comment]
@brucegogo 展示的结果跟你的授权有关，仔细确认下

**Comment by jym503558564** [comment]
请问问题是都已解决？如过未解决，请复现，并截图详细操作信息。
