### ISSUE TITLE
授权规则管理优化

### ISSUE THREAD

**Issue by henyufeiyang** [jumpserver/jumpserver#278]
bug说明：
用户张三、李四、王五属于客服组
机器A、B、C、D属于客服资产组，四台机器拥有两个系统用户：kefu、root
在授权客服组对客服资产组拥有kefu用户权限的时候，增加 张三仅对机器A拥有root权限后，发现张三对机器A、B、C、D都拥有了root权限。

**Comment by haoweishow** [comment]
权限和用户直接挂钩，这样的做法不好控制。权限和用户分离，通过给组赋予权限。可以参考RBAC的模式

**Comment by jiaxiangkong** [comment]
需要分两条授权规则：
第一条：客服组+客服资产组  只关联 kefu 系统用户 
第二条：张三+机器A  只关联root 系统用户

**Comment by ibuler** [comment]
@haoweishow 你说的是角色，是权限比较固定那种，而这里的是资产授权，经常变动，经常需要授权。
所以用角色显然不合适，用组来规划可以想想

**Comment by ibuler** [comment]
@haoweishow Jumpserver中授权是5种资源的关联
用户 用户组 资产 资产组 系统用户 

其中系统用户是为了将用户和后端服务上用户剥离增加的中间层，这样设计的原因在于 授权的变动不会经常影响后端主机上用户的变动(系统用户)

5中资源关联是比较繁琐，但是粒度可以控制的比较低，1用户 1资产 1 系统用户，所以这里在粒度和易用上没有权衡好，期待你的分析

**Comment by ibuler** [comment]
可以同 #430 一起讨论
