### ISSUE TITLE
WEB终端，主机列表未显示

### ISSUE THREAD

**Issue by ckgmg** [jumpserver/jumpserver#2780]
[简述你的问题]

##### 使用版本
jumpserver
Version 1.4.10-2 GPLv2.

lua
Version 1.4.10-101 GPLv2.

##### 问题复现步骤
1. [在WEB终端，主机列表未显示]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/49260651/59171636-76f9e080-8b76-11e9-84b3-9bbd22a8675f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ckgmg 需要完整的错误log

**Comment by viplurker** [comment]
我也有一个类似的错误,但是我是""新增的资产需要等很久才可以在主机列表中出现"

**Comment by jym503558564** [comment]
更新到最新版本，问题是否还会复现？

**Comment by viplurker** [comment]
直接重做了...
 
------------------
雪白的玫瑰花，寄宿着爱的精灵，当美丽的新娘接过勇士手中的花束，它便成为了爱情和贞洁的唯一象征。如雪的玫瑰，盛开得美丽而凛冽，超越生死。雪玫瑰绽放的一瞬，便是爱情释放魔力之始……


 




------------------ 原始邮件 ------------------
发件人: "八千流"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:20
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>; 
抄送: "孤城的守夜人"<lurker@vip.qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [jumpserver/jumpserver] WEB终端，主机列表未显示 (#2780)




更新到最新版本，问题是否还会复现？

**Comment by wojiushixiaobai** [comment]
@ckgmg 新版本已修复

**Comment by cne304** [comment]
@viplurker https://github.com/viplurker/safeline2aodun 您好，请问可以删除这个仓库吗，里面包含一些敏感信息
