### ISSUE TITLE
录像无法回放

### ISSUE THREAD

**Issue by sky-sunny** [jumpserver/jumpserver#2788]
[简述你的问题]
录像无法回放，linux 和win 服务的录像均出现过，并且多次出现

##### 使用版本
1.4.10

##### 问题复现步骤
1.随机

##### 具体表现[截图可能会更好些,最好能截全]

|| root | 192.168.1x.xxx | ssh | Web Terminal | 8 | 2019年6月12日 13:29 | 17 s | 回放(按钮变浅无法回放)  录像文件不存在 

命令行有记录 就是录像回放和录像文件都不行

**Comment by wojiushixiaobai** [comment]
@sky-sunny 检查网络，确定终端在线，确定组件版本和jumpserver版本一致，通过log检查具体的上传录像失败原因

**Comment by sky-sunny** [comment]
> @sky-sunny 检查网络，确定终端在线，确定组件版本和jumpserver版本一致，通过log检查具体的上传录像失败原因

命令有记录，是有在线的，组件一致，安装centos 推荐生产方式安装，log 无有用信息

**Comment by jym503558564** [comment]
请更新至最新版本，是否还会出现此问题？

**Comment by jym503558564** [comment]
git pull 更新一下版本，看是否会复现此问题

**Comment by sky-sunny** [comment]
好的 感谢 晚点 试试

八千流 <notifications@github.com> 于2019年7月29日周一 下午5:51写道：

**Comment by skygangsta** [comment]
录像回放按钮是灰色检查koko和jms日志，看看录像koko是否成功传给了jms
录像回放提示无法下载的，是官方提供的Nginx配置文件有问题，Nginx只匹配了 /media/ 目录没有匹配到 /media/ 下级目录。大概是下载录像时Nginx没有告诉浏览器内容格式是gzip压缩格式导致JSON解析失败。我是这个原因，解决方法：

    location ^~ /media/ {
        add_header Content-Encoding gzip;
    }
