### ISSUE TITLE
web终端连接超时，但是jumpserver服务器直接SSH可以连接

### ISSUE THREAD

**Issue by hjdo** [jumpserver/jumpserver#2789]
[简述你的问题]
jumpserver中添加的所有资产都不能连接，在web终端中打开都是超时。

##### 使用版本
jumpserver:1.5.0-2
coco:docker jumpserver/jms_coco:1.5.0
guacamole:docker umpserver/jms_guacamole:1.5.0

##### 具体表现[截图可能会更好些,最好能截全]
web终端中加载的所有资产，连接时都在15秒后显示timed out，进入coco容器中查看日志，显示：
auth failed, password:          32c5d*******************************, key: b'10:a6:25:5c:54:ae:84:03:cf:54:7b:8a:3f:7b:2d:ac'

![image](https://user-images.githubusercontent.com/12838659/59338732-82dfd100-8d35-11e9-811a-53faf215fe65.png)
![image](https://user-images.githubusercontent.com/12838659/59338768-955a0a80-8d35-11e9-9de1-85bf1eff7850.png)

但是直接在部署jumpserver和coco的机器上ssh连接是可以的：
![image](https://user-images.githubusercontent.com/12838659/59339090-1fa26e80-8d36-11e9-9cb8-8b87b71b1b22.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
auth failed，代表密码不对，应该多了很多空格导致的

**Comment by hjdo** [comment]
@ibuler 我的所有资产服务器都添加了部署jumpserver服务器的ssh公钥，直接是用root用户无密码连接的，我这种方式应该怎么修改资产配置才能正常连接上？我不太熟悉，还多谢您的回复

**Comment by ibuler** [comment]
jumpserver没有自动使用公钥，可以添加给root这个系统用户

**Comment by hjdo** [comment]
@ibuler 我把部署jumpserver服务器的ssh私钥添加到这里了，但是还是会超时，不知道是不是理解错了您说的“添加给root这个系统用户”，麻烦您啦。
![image](https://user-images.githubusercontent.com/12838659/59398930-a1d97400-8dc4-11e9-9c56-562e59217150.png)

**Comment by hjdo** [comment]
@ibuler 使用管理用户root创建新的用户也是登陆超时，自动创建私钥也不行，设置密码也不行，我的coco是用的docker启动的，是这个原因吗？
用自动推送创建的这个用户去服务器上登可以登陆，但是就是在web终端里面超时，coco中提示auth failed.
![image](https://user-images.githubusercontent.com/12838659/59446126-7c378380-8e33-11e9-8644-dcd11373b2f0.png)
![image](https://user-images.githubusercontent.com/12838659/59446141-83f72800-8e33-11e9-96e8-faa65fb00fd5.png)

**Comment by wojiushixiaobai** [comment]
@hjdo 不能自动推送root，关闭自动推送或者把root改成其他账户

**Comment by jym503558564** [comment]
- 首先创建管理用户(root权限的用户，用来推送系统用户)
![image](https://user-images.githubusercontent.com/40739051/59896622-dd56ec80-941b-11e9-9585-0dfdb1138575.png)
- 接着创建系统用户(系统用户是 Jumpserver跳转登录资产时使用的用户，可以理解为登录资产用户.通过管理用户进行推送的。)
![image](https://user-images.githubusercontent.com/40739051/59896796-856cb580-941c-11e9-92f6-81572fa605ed.png)

您这边的问题：可以对管理用户root添加ssh私钥或者使用密码，然后系统用户改一下其它用户名即可。授权，可测试下。

**Comment by hjdo** [comment]
@jym503558564 非常感谢您的回复，已经正常使用了😋，可以关闭这个issues了

**Comment by tongchao199** [comment]
docker exec -it jms_coco ping 10.0.5.134
enter coco container, and ping hosts

**Comment by xudongbo888** [comment]
我的web终端也显示连接超时！
![image](https://user-images.githubusercontent.com/53531019/64954235-901dd600-d8b7-11e9-964f-2f5e9506eb16.png)连接状态的圆圈是红色的表示不可连接。
配置都是对的，只有两台机子是这样的，其它的都可以正常使用
