### ISSUE TITLE
【全屏显示】屏幕分辨率问题

### ISSUE THREAD

**Issue by huweiqing915** [jumpserver/jumpserver#2791]
[简述你的问题]
web terminal点击全屏显示之后，屏幕分辨率没有改变，并且左右两边没有展开完全。希望在全屏显示之后，分辨率能动态改变。

##### 使用版本
jumpserver版本:1.4.10
luna版本:1.5.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![Snip20190613_45](https://user-images.githubusercontent.com/6898731/59398344-7eadc500-8dc2-11e9-90b3-5231a0380fc8.png)
![Snip20190613_46](https://user-images.githubusercontent.com/6898731/59398345-81a8b580-8dc2-11e9-8144-18e7e5917dd0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@huweiqing915 没有展开完全已经记录，但是动态改变可能暂时不能处理

**Comment by feixiangdao** [comment]
有全屏显示这个功能了吗？我是1.5的也没看到

**Comment by jym503558564** [comment]
@feixiangdao 更新代码到最新版本
![image](https://user-images.githubusercontent.com/40739051/59893194-c067ec80-940e-11e9-8338-037bd7f93f6f.png)

**Comment by primroses2006** [comment]
> @feixiangdao 更新代码到最新版本
> ![image](https://user-images.githubusercontent.com/40739051/59893194-c067ec80-940e-11e9-8338-037bd7f93f6f.png)

牛逼  我找了好久没有找到.
