### ISSUE TITLE
升级到最新版后任务作业执行全都是等待状态

### ISSUE THREAD

**Issue by yuandalu** [jumpserver/jumpserver#2793]
[简述你的问题]

##### 使用版本
[1.5.0]

##### 问题复现步骤
1. 任意的测试可连接
2. 任意的执行各种远程命令

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3860040/59404365-dd7e3900-8dd8-11e9-9ab5-9b00229efab2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yuandalu** [comment]
![image](https://user-images.githubusercontent.com/3860040/59404424-11f1f500-8dd9-11e9-8af4-90a914b2963c.png)

**Comment by wojiushixiaobai** [comment]
@yuandalu 参考[SSH 协议资产连接说明](http://docs.jumpserver.org/zh/master/faq_ssh.html) 第9条处理
````
$ source /opt/py3/bin/activate
$ cd /opt/jumpserver/apps
$ celery -A ops purge -f

# 如果任然异常, 手动结束所有jumpserver进程, 然后kill掉未能正常结束的jumpserver相关进程, 在重新启动jumpserver即可

**Comment by yuandalu** [comment]
@wojiushixiaobai 执行celery -A ops purge -f后 重启了所有服务，问题解决了
之前 仅仅是重启无法解决问题，必须要执行：
`$ source /opt/py3/bin/activate`
`$ cd /opt/jumpserver/apps`
`$ celery -A ops purge -f`
然后重启即可解决
