### ISSUE TITLE
启动jumpserver报错如下，请问是什么原因导致的？

### ISSUE THREAD

**Issue by lutixiaya** [jumpserver/jumpserver#2797]
[简述你的问题]
第一次执行启动jumpserver命令报错

##### 使用版本
Jumpserver version 1.5.0

##### 问题复现步骤
1. 前面的部署和环境都是与文档一致的，就是启动时报错如下

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48750425/59494038-e34e4a00-8ebe-11e9-9dda-7c9000b8e0b3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lutixiaya 需要完整的报错log

**Comment by lutixiaya** [comment]
这就是完整的了哦，下面的就是继续重复这个报错

**Comment by wojiushixiaobai** [comment]
@lutixiaya 那应该是卡在了测试连接数据库和redis这里，仔细检查下。或者重新安装下吧

**Comment by lutixiaya** [comment]
我的问题解决了，是config.yml中DB_PASSWORD:后面的密码应该是字符串不是数字，加了双引号解决了。
