### ISSUE TITLE
Ubuntu 开机自启

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#2798]
[简述你的问题]

##### 使用版本
[1.5.0]

##### 问题复现步骤
文档里只有centos 的自启，没有ubuntu
是通用的吗？
非docker部署

##### 其他

[注:] 完成后请关闭 issue

**Comment by sicode** [comment]
按centos的抄了一下
一会成功，一会失败
./jms start all -d 肯定成功 ,通过服务启动就随缘
用sqlit3当数据库 

[jms.service]
[Unit]
Description=jms
After=network.target redis.service
Wants=redis.service

[Service]
Type=forking
Environment="PATH=/opt/py3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin"
ExecStart=/opt/jumpserver/jms start all -d
ExecReload=
ExecStop=/opt/jumpserver/jms stop

[Install]
WantedBy=multi-user.target

**Comment by wojiushixiaobai** [comment]
@sicode 检查是否是启动超时了，超时会直接判断启动失败，超时时间在jumpserver/jms 
TIMEOUT: 40
单位s

**Comment by sicode** [comment]
不太明白

**Comment by wojiushixiaobai** [comment]
@sicode 
````
$ cat /opt/jumpserver/jms | grep TIMEOUT

**Comment by sicode** [comment]
那我修改时间，放长一些？

**Comment by wojiushixiaobai** [comment]
@sicode 是的，之后如果无问题后请关闭问题

**Comment by sicode** [comment]
嗯，我试试

**Comment by sicode** [comment]
给硬盘扩容后，就每次都成功...
才发现录像把硬盘占满
