### ISSUE TITLE
Windwos-RDP幽灵会话

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#2799]
[简述你的问题]
Windwos-RDP幽灵会话

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. 通过web终端，打开WINDOWS机器的远程
2. 服务器执行关机或者重启
3.重启后，在线会话页面还是会显示刚刚打开的远程

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3986116/59563349-64e2db00-906b-11e9-94b5-06ffac344e0b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@sicode 终段右边的倒三角可以下拉菜单，切换到完成，选择资产然后提交，如果任然提示错误，请在数据库里面手动删除。一般是升级前的遗留会话导致的

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/59843346-f6fc2380-938a-11e9-9d82-eeb235c8b386.png)

**Comment by sicode** [comment]
OK，已清除
