### ISSUE TITLE
安装错误日志在哪里能够查看？

### ISSUE THREAD

**Issue by daxuehu** [jumpserver/jumpserver#280]
jumpserver安装后启动服务报错，请问在哪里可以查看日志，找到错误原因？

Starting jumpserver service:                               [FAILED]
安装成功，Web登录请访问http://ip:8000, 祝你使用愉快。
请访问 https://github.com/jumpserver/jumpserver/wiki 查看文档

**Comment by horizon365** [comment]
默认是在/var/log/jumpserver.log

**Comment by byecom** [comment]
> jumpserver安装后启动服务报错，请问在哪里可以查看日志，找到错误原因？
> 
> Starting jumpserver service: [FAILED]
> 安装成功，Web登录请访问http://ip:8000, 祝你使用愉快。
> 请访问 https://github.com/jumpserver/jumpserver/wiki 查看文档

默认目录：       /opt/jumpserver/logs
