### ISSUE TITLE
通过luna直接跳转到指定机器功能，导致浏览器崩溃

### ISSUE THREAD

**Issue by tiancheng92** [jumpserver/jumpserver#2801]
##### 使用版本
1.5.0

##### 问题复现步骤
1. 访问 http://jumpserver域名/luna/?login_to=主机ID
2. 服务器崩溃

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/42594679/59583135-f7878680-910c-11e9-8bde-488d77873a57.png)
![image](https://user-images.githubusercontent.com/42594679/59583160-0a01c000-910d-11e9-9792-84a1943298a9.png)

**Comment by wojiushixiaobai** [comment]
@tiancheng92 尝试更换浏览器试试，确认下是否所有资产都会崩溃还是特定资产，当前用户的授权资产数量等。

**Comment by tiancheng92** [comment]
> @tiancheng92 尝试更换浏览器试试，确认下是否所有资产都会崩溃还是特定资产，当前用户的授权资产数量等。

试过safari、chrome。所有资产都会这样，当前用户授权数量45台，但所有主机总数2000+，毕现。

**Comment by wojiushixiaobai** [comment]
@tiancheng92 无法复现，请登录demo网站进行复现，或者检查是否有报错log等

**Comment by jym503558564** [comment]
这边测试并未复现上述问题，请检查是否有错误的log日志，截图贴出来。
![image](https://user-images.githubusercontent.com/40739051/60258323-819ece80-9907-11e9-8eb7-b7733e798c67.png)

**Comment by SgtDaJim** [comment]
同上，我这边也有这种问题。机器授权了1台，加上Default总共3级节点，jumpserver和luna都是1.5版本

**Comment by SgtDaJim** [comment]
> 同上，我这边也有这种问题。机器授权了1台，加上Default总共3级节点，jumpserver和luna都是1.5版本

总机器数500左右，coco、nginx、jumpserver和浏览器console均无错误日志

**Comment by jym503558564** [comment]
目前这个问题是否还复现？
