### ISSUE TITLE
Windows录像无法上传到阿里云OSS

### ISSUE THREAD

**Issue by Cuigeek** [jumpserver/jumpserver#2802]
[简述你的问题]
录像存储在阿里云OSS中，Linux录像正常，但Windows录像无法上传&回放

##### 使用版本
Jumpserver版本 1.5.0-2

##### 问题复现步骤
1. 通过【Web终端】连接Windows服务器
2. 在【历史会话】中回放Windows录像提示”没有找到录像“（因为本身就没有上传成功）

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20765447/59590845-7be30500-911f-11e9-869c-57a9e46c447d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@Cuigeek 等待代码更新

**Comment by wojiushixiaobai** [comment]
#2750
