### ISSUE TITLE
在models使用datetime创建字段是 django精度问题

### ISSUE THREAD

**Issue by linxianjie** [jumpserver/jumpserver#2804]
[简述你的问题]
在models使用datetime创建字段是 django默认精度是6，添加时间是后面会添加6个0,怎么把精度去掉

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@linxianjie 默认应该是datetime(6)吧，改成datetime试试

**Comment by ibuler** [comment]
无法控制django的行为
