### ISSUE TITLE
LDAP设置测试成功，登陆失败

### ISSUE THREAD

**Issue by bobt2018** [jumpserver/jumpserver#2805]
[简述你的问题]
LDAP设置成功测试有用户，但是LDAP用户无法登陆。看了其他issue说是OU没有配置正确，
但是freeIPA默认新增用户没有OU

##### 使用版本
Version 1.4.8-2 GPLv2.

##### 问题复现步骤
1. 在freeIPA添加用户
2. 执行如下命令 
ldapsearch -x -b "cn=users,cn=accounts,dc=testipa,dc=co" | grep dn
结果：
dn: uid=haha,cn=users,cn=accounts,dc=testipa,dc=co
dn: uid=gitlab,cn=users,cn=accounts,dc=testipa,dc=co
dn: uid=jump,cn=users,cn=accounts,dc=testipa,dc=co
dn: uid=test,cn=users,cn=accounts,dc=testipa,dc=co
dn: uid=atest,cn=users,cn=accounts,dc=testipa,dc=co
3.jumpserver中设置

##### 具体表现[截图可能会更好些,最好能截全]
测试成功
![image](https://user-images.githubusercontent.com/31361987/59663764-4b17d400-91e2-11e9-9ac5-9bac381702f9.png)
无法登陆
![image](https://user-images.githubusercontent.com/31361987/59663843-7d293600-91e2-11e9-8e30-67075c9a251b.png)
##### 其他
正常来讲测试可以匹配到用户即可已登陆，还有没有OU的情况应该可以配置成功，不然还是要命令手动添加用户和直接使用IDAP区别不大
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bobt2018 用户过滤器和下面的属性映射设置要一样，下面用uid，过滤器也要改成(uid=%(user)s)

**Comment by bobt2018** [comment]
> @bobt2018 用户过滤器和下面的属性映射设置要一样，下面用uid，过滤器也要改成(uid=%(user)s)

过滤器改为(uid=%(user)s)也还是不行，同样的问题，可以匹配到用户，不能登陆

**Comment by bobt2018** [comment]
> @bobt2018 用户过滤器和下面的属性映射设置要一样，下面用uid，过滤器也要改成(uid=%(user)s)

不知道为什么，重新登陆一次又可以了，ths
