### ISSUE TITLE
资产管理-系统用户资产-节点管理 移除无效

### ISSUE THREAD

**Issue by suzj801** [jumpserver/jumpserver#2807]
[简述你的问题]

资产管理 - 系统用户 - 系统用户资产(点名称) -右边的节点管理
移除节点提示成功但无效

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0

另外你们官方演示环境有同样的问题。

**Comment by wojiushixiaobai** [comment]
@suzj801 已验证，感谢反馈

**Comment by BaiJiangJie** [comment]
@suzj801 @wojiushixiaobai Bug已修复，目前仅提交到dev分支。

**Comment by BaiJiangJie** [comment]
请等待新版本更新
