### ISSUE TITLE
register access key failed

### ISSUE THREAD

**Issue by glkappe** [jumpserver/jumpserver#2808]
[简述你的问题]
启动coco时出现

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. [步骤1]
$docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e LOG_LEVEL=ERROR jumpserver/jms_koko:1.5.0
2. [步骤2]
$docker logs c4832a8489e5623a8d7370a609bb2636974fc1464109d8315a83aa3f86f6b1b8
2019-06-18 09:47:45 [ERRO] Post http://:8080/api/terminal/v2/terminal-registrations/: dial tcp :8080: connect: connection refused
2019-06-18 09:47:45 [ERRO] register access key failed

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/21033020/59672495-2c213e00-91f2-11e9-92ae-dfd498d39742.png)

##### 其他
无

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@glkappe 变量Server_IP值为空，参考下面命令解决
```
$ docker stop jms_koko
$ docker rm jms_koko
$ Server_IP=`ip addr | grep inet | egrep -v '(127.0.0.1|inet6|docker)' | awk '{print $2}' | tr -d "addr:" | head -n 1 | cut -d / -f1`
$ docker run --name jms_koko -d -p 2222:2222 -p 5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e LOG_LEVEL=ERROR jumpserver/jms_koko:1.5.0

# 如果按照上面操作后提示403，表示token错误，检查jumpserver/config.yml里面的token

**Comment by glkappe** [comment]
@wojiushixiaobai 非常感谢 ，，，后来我发现了这个低级错误 ，非常感谢
