### ISSUE TITLE
什么破软件，安装N遍都是错误

### ISSUE THREAD

**Issue by ckgmg** [jumpserver/jumpserver#2809]
[简述你的问题]
换Python3.6.1  3.6.8  3.7.3，都是报错，py虚拟环境，麻烦你们测试好，再发出来。

![image](https://user-images.githubusercontent.com/49260651/59741027-5e877580-929c-11e9-88d0-edaf4418f81d.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ckgmg 参考[Jumpserver 1.4.9 自建服务器极速安装](https://www.bilibili.com/video/av49481434/)
复制粘贴，不需要修改任何字符串，剩下的问题请自行解决
