### ISSUE TITLE
在进行命令执行时，报错如下

### ISSUE THREAD

**Issue by lutixiaya** [jumpserver/jumpserver#2814]
[简述你的问题]
在进行命令执行时，报错，而且在执行任务列表中的任务时也都是失败，看日志报错信息差不多。
##### 使用版本
jumpserver 1.5

##### 问题复现步骤
1. 进行命令执行动作时，报错

##### 具体表现[截图可能会更好些,最好能截全]
进行命令执行时的报错如下：
![image](https://user-images.githubusercontent.com/48750425/59815767-31929b80-934c-11e9-810b-63e9b77bfb24.png)

进行任务执行的时，系统日志报错如下：

![image](https://user-images.githubusercontent.com/48750425/59815792-4bcc7980-934c-11e9-8426-9196a77d4b1c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
这个系统日志不是在执行命令的时候输出的，重新执行一次命令，再收集一下错误日志。

**Comment by lutixiaya** [comment]
这个错误日志是在执行任务列表中的任务产生的。这个是两个报错，上面的是执行命令报错。

**Comment by jym503558564** [comment]
您这边截图的系统日志，是定期任务的日志记录
![image](https://user-images.githubusercontent.com/40739051/59897503-85ba8000-941f-11e9-939c-dcbf3c095c06.png)

请检查确认，重新执行，收集对应的错误日志

**Comment by jym503558564** [comment]
问题是否已解决？如未解决，请收集对应的完整错误日志，截图贴出来

**Comment by jym503558564** [comment]
git pull更新一下，如有其它问题，可重新开issues
