### ISSUE TITLE
创建用户发送邮件-服务器卡死

### ISSUE THREAD

**Issue by kingleft** [jumpserver/jumpserver#282]
涉及到发送邮件的地方都会卡死，系统完全没有响应，需要重启才能恢复。是我配置设置问题吗？

**Comment by deamwork** [comment]
刚刚安装完是会这样，你去安装目录下的jumpserver.conf里重新配置下邮件的部分，我用的是qqexmail，只有ssl的，我就是因为这个问题才没法发送邮件卡死的，改了就好了

**Comment by kingleft** [comment]
试了qq和163 ，都不行。服务器防火墙也关了，日志是说连接超时，但是相同的用户密码其他地方都机器用的。

**Comment by kingleft** [comment]
问题已解决，服务器网络问题，使用内部邮箱正常。

**Comment by deamwork** [comment]
那就close了吧
