### ISSUE TITLE
LDAP登录.AD域限定用户使用电脑后 报账户密码错误

### ISSUE THREAD

**Issue by minishiguang** [jumpserver/jumpserver#2821]
[简述你的问题]
由于公司风控策略问题,我们在ad域用户属性-账户-工作站-此用户可以登录到-设置可以登录工作站添加跳板机服务器hostname,会导致域用户无法登录跳板机(报账户密码错误),删除限制登录计算机配置,可以正常登录.
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. [步骤1]我们在ad域用户属性-账户-工作站-此用户可以登录到-设置可以登录到下列计算机,添加跳板机服务器hostname
2. [步骤2]登录跳板机(报账户密码错误)
3. [步骤3]我们在ad域用户属性-账户-工作站-此用户可以登录到-设置可以登录到所有计算机
4. [步骤4]正常登录跳板机
##### 具体表现[截图可能会更好些,最好能截全]

![{D1F53073-98CF-4ABA-94D0-BF1D3A0745DF}](https://user-images.githubusercontent.com/22143662/59830713-c7d9b800-9372-11e9-90a3-cb02d7c5e06f.jpg)

![{EE56799C-17BA-4723-8805-BAB4168F5F1C}](https://user-images.githubusercontent.com/22143662/59830875-1f782380-9373-11e9-8295-838181db40e2.jpg)

![1234566564561313213](https://user-images.githubusercontent.com/22143662/59831211-e68c7e80-9373-11e9-9e6f-bdb226e6320c.jpg)

![{E08B60EC-85E0-4FCC-A439-42D2ED08CD02}](https://user-images.githubusercontent.com/22143662/59831358-366b4580-9374-11e9-9e08-7819ba8e7113.jpg)

##### 其他
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@minishiguang 无解决经验，尝试把jms服务器加入域试试，如果任然不行请单独对ad容器或者组做策略，安全问题MFA应该可以应对

**Comment by minishiguang** [comment]
> @minishiguang无解决经验，尝试把JMS服务器加入域试试，如果任然不行请单独对广告容器或者组做策略，安全问题MFA应该可以应对

已经把jms加入域,结果一样!感觉是linux内核的系统对域的兼容问题,

**Comment by MOOREZHANG64** [comment]
用户名使用用户列表中的用户名。若仍提示用户名或密码错误，重置用户密码后再试。
![image](https://user-images.githubusercontent.com/10070015/65412707-5fdbb780-de22-11e9-8114-934801253f2e.png)
