### ISSUE TITLE
Docker+mysql无法观看回放，目录下没有相关视频文件

### ISSUE THREAD

**Issue by bobt2018** [jumpserver/jumpserver#2822]
[简述你的问题]
Docker外接Mysql数据库无法看回放，快速用docker启动可以看回放

##### 使用版本
Jumpserver ALL 1.4.8

##### 问题复现步骤
1. 生成随机加密秘钥, 勿外泄
$ if [ "$SECRET_KEY" = "" ]; then SECRET_KEY=cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50; echo "SECRET_KEY=$SECRET_KEY" >> ~/.bashrc; echo $SECRET_KEY; else echo $SECRET_KEY; fi
$ if [ "$BOOTSTRAP_TOKEN" = "" ]; then BOOTSTRAP_TOKEN=cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16; echo "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN" >> ~/.bashrc; echo $BOOTSTRAP_TOKEN; else echo $BOOTSTRAP_TOKEN; fi
2. 外置数据库
docker run --name jms_all -d 
-v /opt/mysql:/var/lib/mysql 
-v /opt/jumpserver:/opt/jumpserver/data/media 
-p 80:80 
-p 2222:2222 
-e SECRET_KEY=$SECRET_KEY 
-e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN 
-e DB_HOST=192.168.69.12 
-e DB_PORT=3306 
-e DB_USER=root 
-e DB_PASSWORD=123456789aaa
-e DB_NAME=jumpserver 
jumpserver/jms_all:1.4.8

##### 具体表现
![image](https://user-images.githubusercontent.com/31361987/59834197-28202800-937a-11e9-91f0-3c814197092f.png)

##### 其他
1. (重要)发现/opt/jumpserver/data/media文件夹下没有文件，而快速用docker启动会有replay文件夹
2.mysql与jms不在同一台数据库，但其他功能均正常

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请查看一下日志信息，关注一下上传录像是否成功？

**Comment by bobt2018** [comment]
> 请查看一下日志信息，关注一下上传录像是否成功？

7:M 21 Jun 10:06:27.755 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
7:M 21 Jun 10:06:27.755 # Server started, Redis version 3.2.12
7:M 21 Jun 10:06:27.755 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
7:M 21 Jun 10:06:27.755 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
7:M 21 Jun 10:06:27.776 * DB loaded from disk: 0.021 seconds

启动的时候日志有这几条警告。建立会话在关闭会话后查看日志并没有错误
7:M 21 Jun 10:11:28.099 * 100 changes in 300 seconds. Saving...
7:M 21 Jun 10:11:28.184 * Background saving started by pid 237
237:C 21 Jun 10:11:28.185 * DB saved on disk
237:C 21 Jun 10:11:28.186 * RDB: 2 MB of memory used by copy-on-write
7:M 21 Jun 10:11:28.285 * Background saving terminated with success

**Comment by wojiushixiaobai** [comment]
@bobt2018 无法复现你说的问题，另外，外置数据库不需要-v /opt/mysql:/var/lib/mysql，内置才需要。
/opt/jumpserver/data/media 请自己修改为本地实际目录，当前用户必须有可读写权限。
例：
```
$ docker run --name jms_all -d -v ~/Desktop/jumpserver/mysql:/var/lib/mysql -v ~/Desktop/jumpserver:/opt/jumpserver/data/media -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:1.4.8

$ docker run --name jms_all -d -v /opt/jumpserver:~/Desktop/jumpserver/data/media -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e DB_HOST=192.168.69.12 -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD=123456789aaa -e DB_NAME=jumpserver jumpserver/jms_all:1.4.8

**Comment by bobt2018** [comment]
> @bobt2018 无法复现你说的问题，另外，外置数据库不需要-v /opt/mysql:/var/lib/mysql，内置才需要。
> /opt/jumpserver/data/media 请自己修改为本地实际目录，当前用户必须有可读写权限。
> 例：
> 
> ```
> $ docker run --name jms_all -d -v ~/Desktop/jumpserver/mysql:/var/lib/mysql -v ~/Desktop/jumpserver:/opt/jumpserver/data/media -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:1.4.8
> 
> $ docker run --name jms_all -d -v /opt/jumpserver:~/Desktop/jumpserver/data/media -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e DB_HOST=192.168.69.12 -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD=123456789aaa -e DB_NAME=jumpserver jumpserver/jms_all:1.4.8
> ```

1.换了另一个虚拟机测试，外接另一个mysql数据库，不能看回放问题依旧存在；
2.换另一个虚拟机测试，外接同一个mysql数据库，会出现不能连接web终端的情况，提示
Authentication failed.
![image](https://user-images.githubusercontent.com/31361987/59901990-83602200-942f-11e9-9a73-c949724375f3.png)

**Comment by wojiushixiaobai** [comment]
@bobt2018 自行解决下，镜像我亲自测试了没有问题，如果有需要可以提供录像。

ssh 认证失败，请参考faq文档解决，或者自行确认系统用户是否可以正常连接资产
