### ISSUE TITLE
资产列表刷新机制

### ISSUE THREAD

**Issue by glkappe** [jumpserver/jumpserver#2826]
[简述你的问题]

jumpserver资产列表每天都要测试连接吗，总是黄色的。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
全部都是1.5.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/21033020/59895927-0cb82a00-9419-11e9-9b26-8d3845efb393.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有个定时任务，难道没有执行吗

**Comment by glkappe** [comment]
@ibuler  感谢回复~我是根据https://jumpserver.readthedocs.io/zh/master/setup_by_centos7.html 此文章安装部署的  请问定时任务的相关命令是什么，在哪里有体现？

**Comment by BaiJiangJie** [comment]
![image](https://user-images.githubusercontent.com/32935519/60008675-0dfe8680-96a7-11e9-9fa8-ceae781f906a.png)

**Comment by glkappe** [comment]
@BaiJiangJie  感谢回复
我知道这个 每天他都变黄。。。我不是要每天都点一下吧。

**Comment by glkappe** [comment]
@BaiJiangJie @ibuler   感谢回复。
这个功能我知道。。感谢。
但是具体定时任务几点执行 目前还不清楚。刚才看已经是绿色了
