### ISSUE TITLE
离线安装时无法安装python-gssapi和python-keycloak-client

### ISSUE THREAD

**Issue by victorfun1989** [jumpserver/jumpserver#2830]
[简述你的问题]
我之前已经通过pip download -r requirements.txt在有网络的情况下将安装包都下载下来了，然而在离线环境中安装时始终无法安装python-gssapi和python-keycloak-client。

##### 使用版本
jumpserver 1.5.0

##### 问题复现步骤
1. [步骤1]
pip download -r requirements.txt
2. [步骤2]
pip install -r requirements.txt --no-index --find-links dir

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/18305758/59907235-2f5c3a00-943d-11e9-97e1-4799a1b27923.png)
![image](https://user-images.githubusercontent.com/18305758/59907252-3be09280-943d-11e9-8024-c4ba188b948a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@victorfun1989 
````
$ pip download -r /opt/jumpserver/requirements/requirements.txt -d /tmp/pip/jumpserver/
$ pip install --no-index --find-links="/tmp/pip/jumpserver/" pyasn1 six cffi pycparser
$ pip install -r /opt/jumpserver/requirements/requirements.txt --no-index --find-links="/tmp/pip/jumpserver/"

**Comment by victorfun1989** [comment]
@wojiushixiaobai 已经可以了，谢谢
