### ISSUE TITLE
关于作业中心部分，列名称定义的建议

### ISSUE THREAD

**Issue by adminlinzi** [jumpserver/jumpserver#2834]
[简述你的问题]
如截图，“成功”这一列，仅个人建议，因为用过类似的产品，看到其他产品的展示效果挺好的，这里可以写“状态”，下面的表达内容可以用绿色的对号，黄色的圆圈，红色的差号，进行状态的表达，分别表达成功，进行中，失败。

##### 使用版本
v1.5.0

##### 问题复现步骤
正常使用中。

##### 具体表现[截图可能会更好些,最好能截全]

![图片](https://user-images.githubusercontent.com/6985067/60023431-5da17a00-96c8-11e9-9946-8fcc44e5ff2f.png)

##### 其他
仅个人建议，其他暂无。

[注:] 完成后请关闭 issue
收到。

**Comment by wojiushixiaobai** [comment]
@adminlinzi 已收到反馈，感谢
