### ISSUE TITLE
生成资产标签

### ISSUE THREAD

**Issue by samucc** [jumpserver/jumpserver#2835]
[简述你的问题]
1 资产详情里面能够生成资产标签。
a.二维码内容：资产的UUID。生成二维码保存。
b.显示的资产编号：自定义 / 根据UUID  计算出来长度为8的编号。比如：
def short_uuid(uuid):
    uuid = str(uuid).replace('-', '')
    uuidChars = tuple(uuid)
   result = ''
    for i in range(0,8):
        sub = uuid[i * 4: i * 4 + 4]
        x = int(sub,16)
        next_char = uuidChars[x % len(uuidChars)]
        result += next_char
    return result

2 打印 可以单独打印资产标签。
3 资产真删除操作时，操作日志中的变更前，能够记录完整的JSON串内容。可以在误删除时，做到数据的恢复。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
资产标签样例
![image](https://user-images.githubusercontent.com/5812720/60064440-071d5580-9733-11e9-9c1f-683dc95e3765.png)
打印样例
![image](https://user-images.githubusercontent.com/5812720/60064528-46e43d00-9733-11e9-9bf2-dbcbebc13b07.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by glkappe** [comment]
@samucc 这是什么版本有的功能。。。。？

**Comment by samucc** [comment]
@glkappe 希望很快就有。
