### ISSUE TITLE
koko 1.5版本 

### ISSUE THREAD

**Issue by Degeneratefala** [jumpserver/jumpserver#2842]
[简述你的问题]
docker & 编译 安装koko 1.5版本 在jumpserver注册成功后 连接上登陆任何设备均报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver 1.5.0-2
##### 问题复现步骤
1. [步骤1]
ssh xxx@$koko:2222
2. [步骤2]
登陆任意主机
Connect asset xxx error: parse private key error: asn1: structure error: superfluous leading zeros in length
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/31535969/60158952-b38b3480-9824-11e9-84b9-358d48562b9a.png)
![image](https://user-images.githubusercontent.com/31535969/60158998-c7369b00-9824-11e9-9206-70e1ee857ad2.png)

##### 其他
一开始以为是docker的问题,拿到源码自己编译仍然报这个问题,我们是全ubuntu环境 登陆的用户非root

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@Degeneratefala 资产配置的私钥是什么类型的。koko的源码是否是最新版本。

**Comment by Degeneratefala** [comment]
> @Degeneratefala 资产配置的私钥是什么类型的。koko的源码是否是最新版本。

rsa密钥 koko是下载的最新版本

**Comment by Spinestars** [comment]
我从1.4.7升级到1.5之后，发现当初系统用户自动生成的私钥均出现了问题，无法匹配目标机器里的公钥。
而重新推送也不会生成新的密钥对。

因此我通过以下方式解决：
1. 编辑每一个系统用户，并手动上传任意私钥
2. 重新推送编辑后的系统用户
