### ISSUE TITLE
jumpserver.js中，APIUpdateAttr方法调用jquery ajax方法，但没有设置超时时间。

### ISSUE THREAD

**Issue by SgtDaJim** [jumpserver/jumpserver#2843]
[简述你的问题]
jumpserver.js中，APIUpdateAttr方法调用jquery ajax方法，但没有设置超时时间。这是一种危险行为，当请求时间较长时，用户可能会多次发起请求，并造成不可预知的后果。请在$.ajax方法中加入timeout参数，设置超时时间。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![123](https://user-images.githubusercontent.com/10288044/60162806-d883a580-982c-11e9-92d5-dbabfafd298f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时先这样，未来两个版本会发布vue重构后的前端
