### ISSUE TITLE
jumpserver.js APIUpdateAttr 成功返回错误判断

### ISSUE THREAD

**Issue by ypoison** [jumpserver/jumpserver#2845]
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/19726736/60173435-42a64580-9841-11e9-9075-dade5a33bbb8.png)
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
收到，下个版本修复

**Comment by jym503558564** [comment]
已优化，请更新至最新版本。感谢关注，如有其它问题请重新打开issues~
