### ISSUE TITLE
windows 2012 R2无法点击开始菜单

### ISSUE THREAD

**Issue by xiao567890** [jumpserver/jumpserver#2849]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0
##### 问题复现步骤
1. 其它按钮都正常，就是无法点击开始按钮
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
可否截图一下？

**Comment by jym503558564** [comment]
可否截图下，指的是哪里点击不了？
以下测试截图，能正常点击。不知是不是您所指的开始菜单？
![image](https://user-images.githubusercontent.com/40739051/60249250-0df4c580-98f7-11e9-9d6c-d771ff4cb3aa.png)
![image](https://user-images.githubusercontent.com/40739051/60249286-21a02c00-98f7-11e9-9ed4-fce34aa84ad3.png)

**Comment by xiao567890** [comment]
就是这个开始按钮点不了
![WIN2012r2](https://user-images.githubusercontent.com/20200297/60254770-1520d100-9901-11e9-8100-227d987ad475.png)

**Comment by xiao567890** [comment]
就是这个开始按钮
![WIN2012r2](https://user-images.githubusercontent.com/20200297/60255040-937d7300-9901-11e9-924f-94f34ad9f104.png)

**Comment by xiao567890** [comment]
就是这个开始按钮
![无标题](https://user-images.githubusercontent.com/20200297/60255083-a42de900-9901-11e9-987b-5315ed02f2c6.png)

**Comment by jym503558564** [comment]
如果直接按键盘的windows键能否打开？

**Comment by jym503558564** [comment]
- 打开任务管理器
 - 结束桌面窗口管理器 （需要管理员才可操作）
![image](https://user-images.githubusercontent.com/40739051/60256455-228b8a80-9904-11e9-9bc0-3ee148fa75cf.png)

**Comment by xiao567890** [comment]
直接按键盘windows键也没反应，结束桌面窗口管理器后，还是没用

**Comment by jym503558564** [comment]
不通过jumpserver登录，那个按钮是否能点击？因为这边用同样的机型测试了，未出现上述问题情况。

**Comment by jym503558564** [comment]
不通过jumpserver登录，那个按钮是否能点击？因为这边用同样的机型测试了，未出现上述问题情况。是否考虑重启一下资产试试？

**Comment by xiao567890** [comment]
重启后恢复正常
