### ISSUE TITLE
jumpserver 1.5 版本 sftp 下载文件大小为0

### ISSUE THREAD

**Issue by Spinestars** [jumpserver/jumpserver#2850]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.0-2 GPLv2.

##### 问题复现步骤
1. sftp下载后，文件大小是0

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7272900/60247178-ba807880-98f2-11e9-812c-96fda94675a1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Spinestars** [comment]
用的是 koko1.5版本
换成coco1.5版本，下载正常

**Comment by wojiushixiaobai** [comment]
@Spinestars 检查下组件版本是否一致，我这里无法复现你说的问题

**Comment by bufer** [comment]
@Spinestars 这个问题是因为下载用户没有该文件的读权限
