### ISSUE TITLE
Jumpserver1.5.0-2 数量显示错误

### ISSUE THREAD

**Issue by wiki-qi** [jumpserver/jumpserver#2851]
[简述你的问题]
终端登陆后，数量显示错误

##### 使用版本
版本为 Jumpserver1.5.0-2
##### 具体表现[截图可能会更好些,最好能截全]

页码: 1, 数量: 22, 总页数: 1, 总数量: 13

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
新版本koko ？

**Comment by wiki-qi** [comment]
> 新版本koko ？

是的，看来新版本的koko 问题不少

**Comment by jym503558564** [comment]
目前该问题已修复，请git pull更新一下哈～
