### ISSUE TITLE
升级最新1.5 koko CPU跑满

### ISSUE THREAD

**Issue by xornono** [jumpserver/jumpserver#2852]
[简述你的问题]
koko cpu 飙满....
2u4G配置，云服务器，CentOS 7.5+

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
v1.5.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![xxx](https://user-images.githubusercontent.com/35294135/60260938-4acbb700-990d-11e9-8d9b-ded6b8aafab2.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wiki-qi** [comment]
我也遇到了同样的问题   koko cpu 干满了

**Comment by chenmin1992** [comment]
+1

**Comment by wojiushixiaobai** [comment]
@xornono @wiki-qi @chenmin1992 已收到反馈，正在debug中，如果是线上环境可以先切回coco

**Comment by glkappe** [comment]
@xornono  请问升级到1.5.0有出现过

**Comment by chenmin1992** [comment]
> @xornono 请问升级到1.5.0有出现过#2836
> 这个问题吗

我这边正常

**Comment by glkappe** [comment]
@chenmin1992 感谢回复

**Comment by XingCheng1996** [comment]
想问问最新版怎么切换回COCO，我整个服务器都跑炸了。

**Comment by LeeEirc** [comment]
@XingCheng1996 @xornono cpu问题已经优化，使用最新koko。

**Comment by jym503558564** [comment]
已优化，可升级到最新koko～  如果有其它问题，请重新打开issues
