### ISSUE TITLE
SFTP文件管理-服务端发生错误502、504

### ISSUE THREAD

**Issue by China-Honey** [jumpserver/jumpserver#2853]
[简述你的问题]
网页版"文件管理"无法使用。提示：502或504错误，如下图：

![2](https://user-images.githubusercontent.com/20145158/60277474-2df4ab00-9930-11e9-880a-6c248f15a534.png)

web终端能正常进入服务器，如图
![11](https://user-images.githubusercontent.com/20145158/60277529-55e40e80-9930-11e9-85d2-03e92a5886ac.png)

使用SFTP能正常登陆，列出资产目录，但是进入具体资产tmp目录时很慢（5~10秒），点击上传一个300Kb+的文件，需要将近25秒，才开始上传。

![33](https://user-images.githubusercontent.com/20145158/60277738-ba06d280-9930-11e9-928e-22e4e2b0f5f4.png)

PS:我是用密钥的方式自动登陆。
![44](https://user-images.githubusercontent.com/20145158/60277822-e7538080-9930-11e9-9d56-c215a84f6e19.png)

##### 使用版本
Version 1.5.0-101 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@China-Honey 
````
# 升级前版本小于 1.4.2 , 需要修改 nginx 配置
$ vi /etc/nginx/conf.d/jumpserver.conf  # 部分用户的配置文件是/etc/nginx/nginx.conf

server {
    listen 80;

    client_max_body_size 100m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径, 如果修改安装目录, 此处需要修改
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;  # 录像位置, 如果修改安装目录, 此处需要修改
    }

    location /static/ {
        root /opt/jumpserver/data/;  # 静态资源, 如果修改安装目录, 此处需要修改
    }

    location /socket.io/ {
        proxy_pass       http://localhost:5000/socket.io/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /coco/ {
        proxy_pass       http://localhost:5000/coco/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
# 保存后重新载入配置
$ nginx -s reload

**Comment by China-Honey** [comment]
> @China-Honey
> 
> ```
> # 升级前版本小于 1.4.2 , 需要修改 nginx 配置
> $ vi /etc/nginx/conf.d/jumpserver.conf  # 部分用户的配置文件是/etc/nginx/nginx.conf
> 
> server {
>     listen 80;
> 
>     client_max_body_size 100m;  # 录像及文件上传大小限制
> 
>     location /luna/ {
>         try_files $uri / /index.html;
>         alias /opt/luna/;  # luna 路径, 如果修改安装目录, 此处需要修改
>     }
> 
>     location /media/ {
>         add_header Content-Encoding gzip;
>         root /opt/jumpserver/data/;  # 录像位置, 如果修改安装目录, 此处需要修改
>     }
> 
>     location /static/ {
>         root /opt/jumpserver/data/;  # 静态资源, 如果修改安装目录, 此处需要修改
>     }
> 
>     location /socket.io/ {
>         proxy_pass       http://localhost:5000/socket.io/;
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         access_log off;
>     }
> 
>     location /coco/ {
>         proxy_pass       http://localhost:5000/coco/;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         access_log off;
>     }
> 
>     location /guacamole/ {
>         proxy_pass       http://localhost:8081/;
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         access_log off;
>     }
> 
>     location / {
>         proxy_pass http://localhost:8080;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> # 保存后重新载入配置
> $ nginx -s reload
> 
> # 
> 然后参考[SSH 协议资产连接说明](http://docs.jumpserver.org/zh/master/faq_ssh.html)
> ```
我是全新安装的，与这个配置一样。

图（1）通过网域连接的服务器。长时间连接不上后界面报504错误。
图（2）Jumpserver跳板机同个IP网段，能正常登陆，但是速度极慢。


![GIF11](https://user-images.githubusercontent.com/20145158/60418928-c2079080-9c16-11e9-86d2-f965657c59f9.gif)
                                                   图（1）


![22](https://user-images.githubusercontent.com/20145158/60418942-ca5fcb80-9c16-11e9-835f-5e260fb78550.gif)
                                                    图（2）

**Comment by wojiushixiaobai** [comment]
@China-Honey 打开文件夹慢的问题会在之后的版本优化（慢是因为需要和 core 交互校验权限）
网络问题请自己检查下

**Comment by ZeroWilliam** [comment]
请问这个问题后来又进一步更新吗？遇到同样问题

**Comment by wojiushixiaobai** [comment]
@ZeroWilliam 检查下，应该是网络问题
