### ISSUE TITLE
创建账号时邮件发送的通知链接是本地的

### ISSUE THREAD

**Issue by immikez** [jumpserver/jumpserver#2856]
[简述你的问题]

##### 使用版本
1.5.0
##### 问题复现步骤
这个通知邮件给的链接可以修改或是取消掉吗？

**Comment by wojiushixiaobai** [comment]
@immikez 在web-系统设置-基本设置里面设置一下。可以参考[快速入门文档](http://docs.jumpserver.org/zh/master/quick_start.html)
