### ISSUE TITLE
刚登出资产后第一个按键无响应

### ISSUE THREAD

**Issue by chenmin1992** [jumpserver/jumpserver#2859]
[简述你的问题]
刚登出资产后第一个按键无响应

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver: 1.5.0-2
koko: 1.5.0 官方镜像
##### 问题复现步骤
1. 随便登录一个资产，比如Linux
2. exit命令退出到jumpserver的界面
3. 按任意字母，第一个字母打不出来，后边的正常

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20168118/60336096-ff2f1100-99d1-11e9-9e98-85760ea8092c.png)
##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
已反馈，感谢提醒～

**Comment by LeeEirc** [comment]
@chenmin1992 已经修复，请使用最新koko。

**Comment by jym503558564** [comment]
升级到最新koko,如果有其它问题，请重新打开issues
