### ISSUE TITLE
模糊搜索结果集只使用一次

### ISSUE THREAD

**Issue by chenmin1992** [jumpserver/jumpserver#2860]
[简述你的问题]
现在模糊搜索的结果集无限次使用，能不能只使用一次

##### 使用版本
jumpserver: 1.5.0-2
koko: 1.5.0 官方镜像

##### 问题复现步骤
1. 随便搜索一个主机名或IP的一部分进行模糊搜索
2. 登录一个结果集中的资产
3. 退出到跳板机页面，模糊搜索不在上次模糊搜索结果集的资产，提示没有资产

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20168118/60336887-2a1a6480-99d4-11e9-8ce1-013f42c17fee.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by chenmin1992** [comment]
想要的表现1 :
连接jumpserver
第一次模糊搜索资产
登录资产(此时完全清楚模糊搜索结果集)
登出到jumpserver
第二次模糊搜索资产(刚登出后的模糊搜索应该是全新的一次搜索)
想要的表现2 :
连接jumpserver
第一次模糊搜索资产
第二次模糊搜索资产(如果第二次输入的关键字在第一次搜索的结果集没有, 那就应该是一次全新的搜索)

辛苦

**Comment by m925055631** [comment]
我也遇到了，很奇怪，明明有资产，但是老是搜索不到

**Comment by Yiipanny** [comment]
我觉得这个功能是为了大量资产里寻找对应的资产所做的，第一次搜索的结果可以进行二次搜索，二次搜索的结果再进行三次搜索，得到的结果越来越少，能一步步找到想要的资产，以前是怎么搜都列出一堆含有关键字的资产。

**Comment by chenglu01** [comment]
同样的版本，同样的问题，有没有什么好的解决办法？

**Comment by LeeEirc** [comment]
koko 1.5.6已经支持二次搜索
