### ISSUE TITLE
现在是否有菜单权限管理开发计划

### ISSUE THREAD

**Issue by ypoison** [jumpserver/jumpserver#2861]
[简述你的问题]
现在是否有菜单权限管理的开发计划？
如果有希望可以加入开发，如果没有是否可以讨论个方案进行开发。

**Comment by ibuler** [comment]
有的，这个应该是rbac吧

**Comment by ypoison** [comment]
是的rbac, 目前我已利用中间件简单实现了菜单权限的管理

**Comment by zhangtyps** [comment]
用过一家商业堡垒机，是基于用户分配堡垒机权限的，管理员只要勾一下用户能访问的机器就行了，系统用户是和机器绑定的，所以授权时不需要选择系统用户。这个jumpserver权限管理感觉很麻烦啊，每台机器要一条条添加。要是省事一条授权里添加多个系统用户和多个设备，用户还要选，太麻烦了。希望开发者能优化下授权管理。

**Comment by ibuler** [comment]
@zhangtyps 这样的授权方式是易于使用的，但是颗粒度显然比较大，不能满足好多用户的需求。我们也认为授权时，通过目前这种方式比较繁琐，但的确没有找到更好的方式

**Comment by ibuler** [comment]
@ypoison 可以记录一下你的方式吗，将来参考一下
