### ISSUE TITLE
web终端不能使用

### ISSUE THREAD

**Issue by SunHarvey** [jumpserver/jumpserver#2862]
##  web终端不能使用，后端nginx会报错，5000端口起不来
**报错如下：**

- 2019/06/29 17:22:45 [error] 9222#9222: *588 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.222.1, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=MkYYqda HTTP/1.1", upstream: "http://[::1]:5000/socket.io/?EIO=3&transport=polling&t=MkYYqda", host: "192.168.222.99", referrer: "http://192.168.222.99/luna/"
- 2019/06/29 17:22:45 [warn] 9222#9222: *588 upstream server temporarily disabled while connecting to upstream, client: 192.168.222.1, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=MkYYqda HTTP/1.1", upstream: "http://[::1]:5000/socket.io/?EIO=3&transport=polling&t=MkYYqda", host: "192.168.222.99", referrer: "http://192.168.222.99/luna/"
- 2019/06/29 17:22:50 [error] 9222#9222: *591 no live upstreams while connecting to upstream, client: 192.168.222.1, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=MkYYrsN HTTP/1.1", upstream: "http://localhost/socket.io/?EIO=3&transport=polling&t=MkYYrsN", host: "192.168.222.99", referrer: "http://192.168.222.99/luna/"
- 2019/06/29 17:22:55 [error] 9222#9222: *591 no live upstreams while connecting to upstream, client: 192.168.222.1, server: , request: "GET /socket.io/?EIO=3&transport=polling&t=MkYYt4u HTTP/1.1", upstream: "http://localhost/socket.io/?EIO=3&transport=polling&t=MkYYt4u", host: "192.168.222.99", referrer: "http://192.168.222.99/luna/"

##### 使用版本
Version 1.5.0-2 GPLv2.

##### 问题复现步骤
1. 安装完成后、添加主机。
2. 访问web终端就不能用
3. nginx的配置都是安装脚本自动生成的

##### 具体表现
1.  5000  端口不能起来
![22222](https://user-images.githubusercontent.com/48371415/60382337-3ebe3180-9a94-11e9-8a5f-a1bfd3a364ec.png)

![111111111](https://user-images.githubusercontent.com/48371415/60382297-ab84fc00-9a93-11e9-89f4-4c15291827c1.png)

**Comment by wojiushixiaobai** [comment]
@SunHarvey 
参考[SSH 协议资产连接说明](http://docs.jumpserver.org/zh/master/faq_ssh.html)
