### ISSUE TITLE
升级１.5.0后前端jquery报错

### ISSUE THREAD

**Issue by kentwanwan** [jumpserver/jumpserver#2863]
[简述你的问题]

问题截图
![深度截图_选择区域_20190629211133](https://user-images.githubusercontent.com/49065202/60384683-1eea3600-9ab3-11e9-8aa8-42c26530ccd4.png)

**Comment by jym503558564** [comment]
- 清一下浏览器缓存
- 重启

**Comment by jym503558564** [comment]
问题是否已解决？

**Comment by kentwanwan** [comment]
已经解决，非常感谢。我一般不开邮箱抱歉。

八千流 <notifications@github.com> 于2019年7月22日周一 上午10:31写道：
