### ISSUE TITLE
通过jumpserver如何实现登入内部的数据库等资产

### ISSUE THREAD

**Issue by StuSunSin** [jumpserver/jumpserver#2866]
[简述你的问题]
当前使用的是OPENVPN服务器，作为跳板机，客户端通过openvpn拨号，连接内部资产及查询数据库（本地有台服务器openvpn长期保持在线，每天定时拉取数据，做报表）。

目前打算使用jumpserver替换线上的vpn，ssh、rdp等远程管理功能已经能够实现，现在的问题是如果通过jumpserver访问到数据库服务端口。

##### 使用版本
Version 1.5.0-2

##### 问题复现步骤
反馈问题不需复现

##### 其他

[注:] 完成后请关闭 issue

**Comment by npcomet** [comment]
在的 openvpn 上做端口映射

**Comment by wojiushixiaobai** [comment]
@StuSunSin Jumpserver不支持流量穿透，推送还是使用其他方式来处理
