### ISSUE TITLE
LDAP user 导入成功 无法登陆

### ISSUE THREAD

**Issue by mynameisshiy** [jumpserver/jumpserver#2867]
[简述你的问题]
按照说明配置好了ldap，能导入用户，但是登录提示不对。

##### 使用版本
[请提供你使用的Jumpserver版本 1.5 注: 0.3.x不再提供支持]

##### 具体表现[截图可能会更好些,最好能截全]
![2](https://user-images.githubusercontent.com/8981574/60470485-27996280-9c93-11e9-8ca3-16bb8f57dcd4.jpeg)
![1](https://user-images.githubusercontent.com/8981574/60470490-2c5e1680-9c93-11e9-850a-f19e2a23a7bc.jpeg)
![3](https://user-images.githubusercontent.com/8981574/60470496-2ff19d80-9c93-11e9-9576-07e99014969e.jpeg)
![4](https://user-images.githubusercontent.com/8981574/60470498-3253f780-9c93-11e9-9fe4-eaccc6516c4f.jpeg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@mynameisshiy 确定dn的密码正确，确定用户的密码正确，可以用ldap工具测试下（不要有多余的空格）

**Comment by mynameisshiy** [comment]
> @mynameisshiy 确定dn的密码正确，确定用户的密码正确，可以用ldap工具测试下（不要有多余的空格）

你们一般用什么工具测试？介绍一个呢

**Comment by mynameisshiy** [comment]
> @mynameisshiy 确定dn的密码正确，确定用户的密码正确，可以用ldap工具测试下（不要有多余的空格）

解决了，绑定dn中的dc应该是com，写成了org。。。粗心大意啊。。不过为什么还是可以正常导入账号呢。。。
