### ISSUE TITLE
有大量输出时，内存不回收

### ISSUE THREAD

**Issue by ivanjoy42** [jumpserver/jumpserver#287]
现象：
在命令行有大量输出时（例如上传文件；实时打印日志；执行程序有大量输出等），connect.py进程占用内存越来越高，生产环境一个进程可以占用3-4G，执行程序结束返回到nav界面内存仍然不回收，只要不断开连接，当前进程占用内存只曾不减。

解决：
我尝试将connect.py中的termlog.write(x)一行注掉可以解决问题，内存使用降低，并且内存会回收。查资料是tornado的websocket的self.write_message(msg)操作，具体不懂。

问题：
1.这个self.write_message(msg)做什么用的？
2.我直接注掉termlog.write(x)对系统有什么影响？
3.有什么好的方法可以解决内存不回收问题？

**Comment by ivanjoy42** [comment]
import random
for i in range(1000000):
    print(str(i) + ' ' + str(random.random()), end='\r')
执行上面的测试程序，可以观察内存只曾不减问题。

**Comment by ibuler** [comment]
问题反馈已收到，正在考虑如何处理

**Comment by ivanjoy42** [comment]
能先解答个问题吗，termlog.write(x)是干什么用的，注掉对系统有什么影响？

**Comment by kelianchun** [comment]
这个是用来写日志的，注释之后视频回放会有问题

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/commit/b48af948b6d2020e1ec6856494a67cc77c6a4f0a 
使用这个分支测试一下

**Comment by ivanjoy42** [comment]
@ibuler 内存占用减少了，并且任务完成后内存会回收，非常给力！

**Comment by ibuler** [comment]
别的功能测试是否正常，录像，命令记录， terminal和web terminal的

**Comment by ivanjoy42** [comment]
1. 录像回放和命令统计功能都可用。
2. web terminal我没有使用和测试。
3. 查看命令统计发现偶尔有命令不全、命令丢失的问题。日志文件（logs/tty/ymd/*.log）记录的很准确没有发现问题。这个问题貌似与你提供的补丁无关，可用新开一个话题。初步判断可能与交互程序输出有关，例如vim编辑结束有时会丢失命令，还有top结束可能多一行无效的命令记录。

**Comment by Keleir** [comment]
@ivanjoy42 

# 日志审计 - 命令统计中记录的输入命令不准确

- 1.输入的命令被截断；

- 2.输入的命令被漏记（对比系统history可发现）；

- 3.前一条输入的命令与后一条未换行；

---

> 1、录像回放和命令统计功能都可用。

> 2、web terminal我没有使用和测试。

> 3、查看命令统计发现偶尔有命令不全、命令丢失的问题。日志文件（logs/tty/ymd/*.log）记录的很准确没有发现问题。这个问题貌似与你提供的补丁无关，可用新开一个话题。初步判断可能与交互程序输出有关，例如vim编辑结束有时会丢失命令，还有top结束可能多一行无效的命令记录。

**Comment by liuzheng712** [comment]
@Keleir 命令的准确记录一直是难题，因为jumpserver不作为kernel的一部分，获取命令是通过其他方式来获取的，未来我将尝试*敏感词*的方式来获取，主要看时间是否足够
