### ISSUE TITLE
RDP connection error

### ISSUE THREAD

**Issue by eno16777736** [jumpserver/jumpserver#2870]
[简述你的问题]
公司想通过jumpserver管理阿里云上的虚拟机(Debian OS)，但通过RDP远程登陆时一直卡在连接中直到超时。阿里云的虚拟机的安全组放通了3389端口，而且使用本地win10的远程工具可以正常连接。但jumpserver的web窗口却无法登陆。

##### 使用版本
1.5
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
可否完整截图一下错误日志？

**Comment by jym503558564** [comment]
问题是否已解决？如还存在，收集完整的错误日志，截图贴出来～
