### ISSUE TITLE
建议支持用windows远程桌面连接访问windows服务器

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2873]
[简述你的问题]
使用web终端访问windows服务器，经常会遇到卡顿。同一台服务器，使用windows远程桌面连接，使用正常。
建议模仿COCO，把目前windows的guacamole改造成一个RDP协议代理，用户可以选择用RDP Client或者Web终端访问Windows服务器。

##### 使用版本
[Jumpserver版本 1.4.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jackwang-github** [comment]
这个是个好东西，JMS对windows的支持不好的。

**Comment by netswordster** [comment]
深有通感，JMS下Windows的体验真的不太好，强烈建议直接采用mstsc连接windows服务器，jms仅作为一个跳板和代理。

**Comment by ibuler** [comment]
目前实现起来还有些难度，先把容易的做了，再考虑
