### ISSUE TITLE
【功能建议】通过跳板机登录到服务器后SecureCRT显示框无法显示IP

### ISSUE THREAD

**Issue by liyingxiao94** [jumpserver/jumpserver#2875]
[简述你的问题]
通过跳板机登录多个服务器，类似于SecureCRT的远程终端连接工具无法显示相应登录的服务器IP，因此容易造成混乱，不利于操作人员操作相应的服务器

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/22187621/60573581-830a4400-9daa-11e9-8af4-f88df686d7e6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Jackxun123** [comment]
修改coco下的coco/connection.py，
添加
`ssh.exec_command('echo "echo -ne \\"\e]2;'+asset.hostname+'\\a\\"" > /etc/sysconfig/bash-prompt-xterm && chmod +x /etc/sysconfig/bash-prompt-xterm && echo "PS1=\\"[\\u@'+asset.hostname+'-'+asset.ip+' \\W]\\$\\"" > /etc/profile.d/changePS1.sh && chmod +x /etc/profile.d/changePS1.sh')`

如图

![pic](https://jack-1256432810.cos.ap-beijing.myqcloud.com/image/fxYi3q.png)

效果如图

![1pic](https://jack-1256432810.cos.ap-beijing.myqcloud.com/image/kLW7zt.png)

**Comment by liyingxiao94** [comment]
感谢支持，我尝试修改了coco下的/opt/coco/coco/connection.py
![image](https://user-images.githubusercontent.com/22187621/60778962-8b2c0000-a16b-11e9-9d1c-266527f2711f.png)
重启docker容器后登陆发现无法达到你的效果，我理解这个是把服务器的命令行提示符但是没有生效，也没有重定向成功哪个文件生成。
