### ISSUE TITLE
按照操作指导分布式安装koko和Guacamole不成功

### ISSUE THREAD

**Issue by phlf74** [jumpserver/jumpserver#2876]
[简述你的问题]
通过分布式部署整个Jumpserver各个组件，在安装koko和Guacamole的Docker的时候，按照指导手册中的curl的步骤出现错误提示；
在docker指令中执行koko和jms_guacamole都出现image本地找不到的提示。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
按照https://jumpserver.readthedocs.io/zh/master/distributed_05.html中的指令严格执行安装。

##### 问题复现步骤
1. [步骤1]curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://f1361db2.m.daocloud.io，出现错误提示
2. [步骤2]在docker run jsm_koko中，执行> jumpserver/jms_koko:1.5.0，提示image不存在
3.【步骤3】在docker run jsm_Guacamole中，执行> jumpserver/jms_guacamole:1.5.0，提示image不存在

##### 具体表现[截图可能会更好些,最好能截全]
1.curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://f1361db2.m.daocloud.io
出现：curl: (60) Peer's Certificate issuer is not recognized.
> jumpserver/jms_guacamole:1.5.0
Unable to find image 'jumpserver/jms_guacamole:1.5.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

##### 其他
公司内网环境，已经配置了proxy访问权限。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@phlf74 第一个问题现在应该没有了才对，这是因为daocloud的加速器网站出现问题导致的，你可以尝试换一个加速器
第二个问题尚未复现，可能是第一个问题导致的，镜像地址如下
https://hub.docker.com/r/jumpserver/jms_guacamole
