### ISSUE TITLE
 按照官方指导完全安装了jumpserver的所有分布式组件后，web访问主页显示不正确

### ISSUE THREAD

**Issue by phlf74** [jumpserver/jumpserver#2884]
[简述你的问题]
1.按照官方指导完全安装了所有分布式组件
2.WEB访问站点，页面显示不正确

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver1.5

##### 问题复现步骤
1. 安装所有组件和完成配置
2. 浏览器访问主页，页面显示不正确

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48398411/60693360-92a19e00-9f0c-11e9-8038-a5b7b4dcc84d.png)
![image](https://user-images.githubusercontent.com/48398411/60693373-a3521400-9f0c-11e9-968d-47b416255743.png)

##### 其他
Luna页面访问正常。

[注:] 完成后请关闭 issue

**Comment by Jackxun123** [comment]
nginx配置文件，检查一下

**Comment by jym503558564** [comment]
@phlf74 
请参考官方文档，配置好nginx
https://jumpserver.readthedocs.io/zh/master/distributed_02.html

**Comment by phlf74** [comment]
@
1./etc/nginx/nginx.conf与官方文档完全一致；
2./etc/nginx/conf.d/jumpserver.conf与官方文档只有一处不一样，端口用80出来的是nginx自带的首页面，用8080可以出来jumpserver主页面，但是页面显示还是和问题描述一样，不正确。
upstream jumpserver {
    server 10.120.53.210:8080;
    # 这里是 jumpserver 的后端ip

**Comment by wojiushixiaobai** [comment]
@phlf74 删掉默认的default.conf，然后重启nginx
一些小问题请尽量使用搜索引擎解决，你的nginx没有按照官方文档进行安装导致的
