### ISSUE TITLE
从1.4.4升级1.5.1报错

### ISSUE THREAD

**Issue by uglyliu** [jumpserver/jumpserver#2909]
[简述你的问题]
从1.4.4升级到1.5.1的时候，jumpserver.log报以下错误，升级文档来自https://jumpserver.readthedocs.io/zh/docs/upgrade.html

##### 使用版本
版本：1.5.1
##### 具体表现[截图可能会更好些,最好能截全]
jumpserver.log报django.db.utils.OperationalError: (1054, "Unknown column 'users_user.otp_secret_key' in 'field list'")
![image](https://user-images.githubusercontent.com/22983421/60813870-29997f00-a1c7-11e9-9b03-57abfc4e15c3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个应该是数据库表结构没有升级
