### ISSUE TITLE
历史会话无法显示，一直在加载中

### ISSUE THREAD

**Issue by ehui168** [jumpserver/jumpserver#2912]
[简述你的问题]
     升级到最新版本后，无论使用管理员还是审计员账号查看“历史会话”，都显示不出来会话记录，一直在加载中。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34931383/60863766-4cbe4000-a254-11e9-94fc-aabfcfba65c3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@ehui168 禁用缓存或者更换浏览器即可。

**Comment by TroubleJin** [comment]
更换浏览器无法显示，禁用缓存指的是？

**Comment by ehui168** [comment]
已经通过清除浏览器缓存，解决这个问题，谢谢！

**Comment by TroubleJin** [comment]
清除浏览器缓存也无法显示.
