### ISSUE TITLE
1.5.1 coco组件telnet功能异常

### ISSUE THREAD

**Issue by TanY0Y0** [jumpserver/jumpserver#2913]
[简述你的问题]
完全按照master文档中的一站式安装，在使用telnet功能时，输入账户密码后报错，ssh正常

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
centos 7.6
jumpserver master 1.5.1

##### 问题复现步骤
1. [步骤1]
完全按照master文档中的一站式安装
2. [步骤2]
coco使用docker安装1.5.1，使用自带telnet工具

##### 具体表现[截图可能会更好些,最好能截全]
![WX20190709-171337](https://user-images.githubusercontent.com/51318636/60875906-7041b480-a26d-11e9-816f-fc1d975565b8.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@TanY0Y0 请参考 [Telnet 使用说明](http://docs.jumpserver.org/zh/master/faq_telnet.html)
如果任有问题，请等待修复，感谢反馈

**Comment by ibuler** [comment]
已修复
