### ISSUE TITLE
每天一直发送密码过期邮件

### ISSUE THREAD

**Issue by StandNorthStar** [jumpserver/jumpserver#2916]
[简述你的问题]
我们使用的Jumpserver密码过期时间是180天，在发送密码更改邮件中已经根据链接更改完密码，查看用户管理 “最后更新密码”这个日期也是最新的。但是还是一直发送更改密码邮件，都已经发送有8天了。请问这个是什么情况？

##### 使用版本
Version 1.4.8-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@StandNorthStar 我先验证下，稍后为你反馈

**Comment by StandNorthStar** [comment]
> @StandNorthStar 我先验证下，稍后为你反馈

你好，请问下验证有出现这种状况吗？

**Comment by StandNorthStar** [comment]
MariaDB [jumpserver]> update users_user set is_first_login=0;
在数据库里面设置这个貌似就解决了。

**Comment by ibuler** [comment]
请尝试更新到 1.5.2 ，看看是不是依旧存在

**Comment by ibuler** [comment]
fixed
