### ISSUE TITLE
【功能建议】终端登录时资产层级化

### ISSUE THREAD

**Issue by 311villagehead** [jumpserver/jumpserver#2917]
用CRT或者XSHELL登录junmpserver时显示资产时能不能层级话显示，比如将接入层设备放到一个目录下面，核心层放到一个目录下面，首页就可以显示层级目录，这样结构比较清晰。都显示在一页里面乱糟糟的如下图
![QQ图片20190710110339](https://user-images.githubusercontent.com/29101156/60937291-7897ff00-a302-11e9-9683-149ea6da2884.png)

**Comment by BaiJiangJie** [comment]
新版本有优化，建议升级到1.5.2

**Comment by 311villagehead** [comment]
OK，谢谢


------------------
齐国府

 




------------------ 原始邮件 ------------------
发件人: "BaiJiangJie"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 中午11:30
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>;
抄送: "FinalFantasy"<285942550@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jumpserver/jumpserver] 【功能建议】终端登录时资产层级化 (#2917)




新版本有优化，建议升级到1.5.2
