### ISSUE TITLE
网页连接主机  js regx bug

### ISSUE THREAD

**Issue by liuyangc3** [jumpserver/jumpserver#292]
webterminal.js   line 16 :

```
var endpoint = protocol + 
document.URL.match(RegExp('//(.*?)/'))[1] + '/ws/terminal' + document.URL.match(/(\?.*)/);
```

最后 这个 `document.URL.match(/(\?.*)/)`，如果 url 是`http://jumpserver.com/terminal/?id=1&role=admin`
由于正则使用了分组去匹配问号后的所有字符，那么 match 返回的结果是数组
["?id=1&role=admin", "?id=1&role=admin"]

这就回导致拼接出来的 endpoint 变成这样

`ws://jumpserver.com/ws/terminal?id=1&role=admin,?id=1&role=admin`

而期望的结果应该是

`ws://jumpserver.com/ws/terminal?id=1&role=admin`

所以`document.URL.match(/(\?.*)/)`

里的正则表达式应该去掉分组，变为 `document.URL.match(/\?.*/)`

**Comment by ibuler** [comment]
是有这个问题，你提个PR吧
