### ISSUE TITLE
coco 连接数持续增加

### ISSUE THREAD

**Issue by journeyto0405** [jumpserver/jumpserver#2920]
[简述你的问题]
同事反馈用ssh连接到堡垒机操作时，操作特别卡顿，排除了网络问题后，最终确认是coco链接没有释放。正常情况下， 高峰期只有不到20个用户，但是2222端口的连接数达到了2k. 而且还在持续上升。 我们在重启了服务后，释放了连接，同事反馈也不卡了，但是连接数依然在缓慢的上升中。

##### 使用版本
Version 1.4.9-2 GPLv2

##### 问题复现步骤
通过ssh连接堡垒机进行操作

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@journeyto0405 建议更新到最新版本看下是否还有此问题，请现在测试环境验证。

**Comment by BaiJiangJie** [comment]
更新到最新版本，如果问题还存在，请重新打开Issue。
