### ISSUE TITLE
web终端RDP连接windows 2008的时候报错

### ISSUE THREAD

**Issue by landwee** [jumpserver/jumpserver#2921]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5
##### 问题复现步骤
1. web终端RDP连接windows 2008的时候（已经按照RDP协议资产连接说明--反复查看配置，端口也通，通过windows终端桌面也可连接）

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34813685/60957686-a481a780-a337-11e9-8ab1-0bb18d57eec0.png)

**Comment by jym503558564** [comment]
收集一下gua的日志，截图贴出来

**Comment by landwee** [comment]
> 收集一下gua的日志，截图贴出来

![image](https://user-images.githubusercontent.com/34813685/60960007-cda43700-a33b-11e9-9b70-8ed4301c09dc.png)

**Comment by landwee** [comment]
> > 收集一下gua的日志，截图贴出来
> 
> ![image](https://user-images.githubusercontent.com/34813685/60960007-cda43700-a33b-11e9-9b70-8ed4301c09dc.png)

貌似找到原因了jms_coco没启

**Comment by wojiushixiaobai** [comment]
@landwee emmm，应该和coco没啥关系，guacamole可以不依赖coco运行。
提示没有权限一般是guacamole未注册，如果是已注册状态重启nginx就好。
可以参考faq文档 [RDP 协议资产连接说明](http://docs.jumpserver.org/zh/master/faq_rdp.html)

**Comment by landwee** [comment]
> @landwee emmm，应该和coco没啥关系，guacamole可以不依赖coco运行。
> 提示没有权限一般是guacamole未注册，如果是已注册状态重启nginx就好。
> 可以参考faq文档 [RDP 协议资产连接说明](http://docs.jumpserver.org/zh/master/faq_rdp.html)
 确认不是coco问题；所有组件升级到了1.5.1之后，现在的错误是这个，如图：
![image](https://user-images.githubusercontent.com/34813685/61019024-4acabd00-a3cb-11e9-9fb5-7bb211674695.png)
gua日志如下：
![image](https://user-images.githubusercontent.com/34813685/61018967-1ce57880-a3cb-11e9-8eb2-1aece82bc9f0.png)

**Comment by wojiushixiaobai** [comment]
@landwee 参考该文档进行处理， 下面有说明资产如何设置，防火墙如何设置

**Comment by BaiJiangJie** [comment]
如果还存在问题，请重新打开Issue。
