### ISSUE TITLE
Jumpserver的安装路径是否限定死

### ISSUE THREAD

**Issue by phlf74** [jumpserver/jumpserver#2922]
[简述你的问题]
重新部署分布式的jumpserver，jumpserver无法启动，是否限定了安装的用户必须用root，路径必须是/opt/jumpserver/?

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.1

##### 问题复现步骤
1. [步骤1]按照指导书全部安装完成，未用root用户，jumpserver安装在home/user/下面
2. [步骤2]启动jumpserver时候，执行./jms start all -d，提示错误，信息如下
Import error:No module named ‘yaml‘
Could not find config file,’cp config_example.yml config.yml'

检查/home/user/jumpserver下所有文件都有的。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48398411/61013742-8f982900-a3b6-11e9-965d-78e72565b28c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by China-Honey** [comment]
+1 你是如何解决的。
