### ISSUE TITLE
用docker安装，80端口是tcp6，导致telnet 80端口不通是怎么回事

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#2927]
[简述你的问题]

##### 使用版本
dockder 1.4.8

##### 问题复现步骤
[root@master chenzx]# docker run --name jms_all -d -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:1.4.8

![image](https://user-images.githubusercontent.com/13861904/61025655-f41dad00-a3e3-11e9-9169-23cc65dbd61a.png)

![image](https://user-images.githubusercontent.com/13861904/61025664-fbdd5180-a3e3-11e9-989f-af700c851b04.png)

确认防火墙和selinux都关了
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@czxin788 
```
docker logs -f jms_all
# 如果无报错，检查selinx和firewalld，无异常直接浏览器访问服务器80端口即可。
# 如果有报错，把报错的log完整的贴出来

**Comment by czxin788** [comment]
> @czxin788
> 
> ```
> docker logs -f jms_all
> # 如果无报错，检查selinx和firewalld，无异常直接浏览器访问服务器80端口即可。
> # 如果有报错，把报错的log完整的贴出来
> ```


好的，谢谢，现在又可以用了。自己好的
