### ISSUE TITLE
请问命令执行可以保存起来供下次使用吗

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#2933]
[简述你的问题]
 我看了命令执行功能，很好用。但是没有找到怎么把执行的命令保存起来，供下次使用。
 最好能有个能保存起来的功能，下次就直接调用了，我看opsmanage这个项目里面有保存的的功能，以下是opsmanage的截图：
![image](https://user-images.githubusercontent.com/13861904/61099515-32bf7000-a495-11e9-8f20-b750ad849e23.png)

jumpserver就没有：
![image](https://user-images.githubusercontent.com/13861904/61099389-b3ca3780-a494-11e9-8e45-c901926ff256.png)

##### 使用版本
docker 版本的1.4.8

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@czxin788 感谢反馈，您的建议我会反馈给开发的相关老哥。辛苦了

**Comment by ibuler** [comment]
其实JumpServer的命令执行，没有设计的当，当时是完成之前版本功能而做，没有系统考虑和设计
