### ISSUE TITLE
无法新建系统用户及授权规则

### ISSUE THREAD

**Issue by zaijiejud** [jumpserver/jumpserver#2935]
#
[1.5.1]

##### 问题复现步骤
1，无法添加系统用户，点击提交按钮无反应
2，无法添加授权规则，点击提交按钮无反应
#

**Comment by wojiushixiaobai** [comment]
@zaijiejud 
```
$ cd /opt/jumpserver
$ git pull

**Comment by zaijiejud** [comment]
> @zaijiejud
> 
> ```
> $ cd /opt/jumpserver
> $ git pull
> ```

(py3) [root@jumpserver jumpserver]# git pull
Already up-to-date.
(py3) [root@jumpserver jumpserver]#


执行了之后，还是不行，现在是没办法创建资产授权，新建系统用户没问题了

**Comment by wojiushixiaobai** [comment]
@zaijiejud 提示什么，是否参考官方文档部署?
jumpserver的log截图看下，开发者工具栏里面看下提交的表单内容是什么

**Comment by zaijiejud** [comment]
> @zaijiejud 提示什么，是否参考官方文档部署?
> jumpserver的log截图看下，开发者工具栏里面看下提交的表单内容是什么

嗯，是按照官方文档来部署的，后端没什么log，我已经开到了debug级别，
前端的报错如下：
![image](https://user-images.githubusercontent.com/20198785/61112062-965d9380-a4bd-11e9-9158-c1c14c3f7f26.png)

**Comment by ibuler** [comment]
jumpserver.js不是最新的，强刷一下浏览器

**Comment by zaijiejud** [comment]
> jumpserver.js不是最新的，强刷一下浏览器
试了所有浏览器，清除了缓存，safari和chrome都不行，firefox可以

**Comment by wojiushixiaobai** [comment]
@zaijiejud 奇怪，我这里只有safari不行，其他的都可以

**Comment by zaijiejud** [comment]
> @zaijiejud 奇怪，我这里只有safari不行，其他的都可以

@wojiushixiaobai 谢谢各位大力支持，现在我已经能用了

**Comment by zaijiejud** [comment]
大佬们，还有一个问题，
firefox无法显示历史会话，chrome正常：
报错如下：
![image](https://user-images.githubusercontent.com/20198785/61205958-f2295600-a723-11e9-88ca-36f5b66063d4.png)

**Comment by BaiJiangJie** [comment]
目前主要支持Chrome，尽量使用Chrome进行操作。
