### ISSUE TITLE
为什么没有1.4.10的更新文档

### ISSUE THREAD

**Issue by amoscx** [jumpserver/jumpserver#2941]
[简述你的问题]
为什么没有1.4.10更新到最新版本的官方文档呢，只有1.4.8-1.4.9或1.5.0更新到1.5.1，1.4.10被忽略了？我现在版本正是1.4.10，按1.4.8-1.4.9或1.5.0升级到1.5.1的官方文档更新，都会出现一样的问题，服务崩溃，无法登录管理界面，显示“Internal Server Error”

##### 使用版本
1.4.10

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@amoscx 抱歉，漏掉了，1.4.8-1.4.10

**Comment by wojiushixiaobai** [comment]
已修复
