### ISSUE TITLE
验证用户对某资产的actions权限接口太慢

### ISSUE THREAD

**Issue by jasper-zhang** [jumpserver/jumpserver#2955]
[简述你的问题]
验证用户对某资产的actions权限接口太慢

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.1
##### 问题复现步骤
1. 选择一个资产的系统用户并登录，连接成功需要将近5s，当前用户的资产总数约为2000个。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/6657098/61222692-c91dbb00-a74d-11e9-9fdc-0e4dcb3dc36c.png)

##### 其他
看了下代码发现，慢的原因是`validate-user-asset-permission`这个接口太慢，再对该接口加日志，发现如下代码中第二步耗时将近3s，第三步耗时将近2s：

```
util = AssetPermissionUtil(user, cache_policy=self.cache_policy)
granted_assets = util.get_assets()
granted_system_users = granted_assets.get(asset, {})
```

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
最新版本已处理，master分支

**Comment by jasper-zhang** [comment]
亲测已经好了，谢谢大佬
