### ISSUE TITLE
jumpserver能否支持管理AWS的EC2主机？

### ISSUE THREAD

**Issue by zzhoo8** [jumpserver/jumpserver#296]
需要使用pem秘钥文件登陆
ssh -i "iplay_seoul.pem" ec2-user@ec2-52-78-103-20.ap-northeast-2.compute.amazonaws.com

看了一下jumpserver的web管理界面配置主要有2个问题
1. 系统用户不支持`ec2-user`这种命名规则，不能有`-`符号
2.用户秘钥的文本框总是提示格式不正确，我已经将-----BEGIN RSA PRIVATE KEY-----和-----END RSA PRIVATE KEY-----单独2行，私钥内容单独1行，还是不行

**Comment by jiaxiangkong** [comment]
用户秘钥的文本框总是提示格式不正确，多点两下确认就行了。

**Comment by zzhoo8** [comment]
点了n下都不行啊~~

继续请教如何支持访问AWS机器？

**Comment by jiaxiangkong** [comment]
原因：应该是复制格式问题
解决：私钥直接在shell下cat  key  然后复制

**Comment by lihaijiang920916** [comment]
您装的是哪个版本的jumpserver？
