### ISSUE TITLE
资产管理->查看资产 没有备注信息那一列？

### ISSUE THREAD

**Issue by ximply** [jumpserver/jumpserver#297]
主机名,IP地址,IDC之类的列都有了，备注信息的列怎么没有加进去呢？ 现在只能拿主机名来区分业务了。

**Comment by luashiping** [comment]
可以分资产组，或者改改源代码显示备注！
发自 网易邮箱大师
在2016年09月06日 14:42，ximply 写道:

主机名,IP地址,IDC之类的列都有了，备注信息的列怎么没有加进去呢？ 现在只能拿主机名来区分业务了。
