### ISSUE TITLE
升级到 1.5.2 后 WEB 终端字体改变

### ISSUE THREAD

**Issue by npcomet** [jumpserver/jumpserver#2974]
[简述你的问题]
升级到 1.5.2 后 WEB 终端字体改变

##### 使用版本
[Jumpserver版本 1.5.2]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
升级到 1.5.2 后 WEB 终端字体改变
![屏幕截图_4](https://user-images.githubusercontent.com/43159290/61299412-9be71080-a812-11e9-8896-a65366e35d4c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
从哪个版本升上来的

**Comment by BaiJiangJie** [comment]
重新连接一下资产

**Comment by npcomet** [comment]
> 从哪个版本升上来的

1.4.4 版本升级的

**Comment by BaiJiangJie** [comment]
这个问题会不会稳定复现

**Comment by npcomet** [comment]
> 这个问题会不会稳定复现
只在 Chrome 出现
Firefox 不会出现
把cookie和缓存全部清空 然后Shift + F5还不行
不过好在平时用的是 ssh 浏览器很少用

**Comment by BaiJiangJie** [comment]
每次打开都会出现吗？还是偶尔会有这种情况？

**Comment by wojiushixiaobai** [comment]
@npcomet 请更新一下luna，最新的luna在windows下面尚未复现此问题

**Comment by npcomet** [comment]
> @npcomet 请更新一下luna，最新的luna在windows下面尚未复现此问题

好的 感谢
更新过 清空所有缓存后没有问题了
