### ISSUE TITLE
不能用public key登录

### ISSUE THREAD

**Issue by x0mike0x** [jumpserver/jumpserver#2985]
[简述你的问题]
不能用public key登录

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.8-2 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52434617/61427593-5846f080-a951-11e9-9a28-faff1255d302.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@x0mike0x 检查你的哪个组件版本不是1.4.8，把那个组件换成1.4.8，所有组件版本都需要一致
