### ISSUE TITLE
创建命令过滤无响应

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#2988]
[简述你的问题]
创建命令过滤无响应，console里面报错：
TypeError: Cannot use 'in' operator to search for '7' in 该字段是必填项。

##### 使用版本
jumpserver docker版本的1.5.1

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13861904/61432628-977e3d00-a963-11e9-949f-d7d7566557ea.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
Fixed. 
使用最新版本 1.5.2
