### ISSUE TITLE
jumpserver在windows下web  terminal的字体问题

### ISSUE THREAD

**Issue by luashiping** [jumpserver/jumpserver#299]
@ibuler  在windows的web  terminal下，由于windows没有Monaco字体，所以显示都会错乱，如图https://pan.baidu.com/s/1mio8D0O
包括vim打开一个文件，里面的中文现实都有问题！我在windows下安装了Monaco字体之后，问题就解决了！

**Comment by xiaooloong** [comment]
我是直接把 font-family 里的微软雅黑删掉就等宽了
