### ISSUE TITLE
命令记录加载不出来

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#2992]
[简述你的问题]
命令记录加载不出来

##### 使用版本
用的是docker安装的，版本是1.5.1-2

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13861904/61446041-2188ce80-a981-11e9-8197-9ff35de5b9d5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
Fixed（1.5.2）.
