### ISSUE TITLE
web 终端连接windows问题

### ISSUE THREAD

**Issue by xiaoigl** [jumpserver/jumpserver#2994]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0-2
##### 问题复现步骤
1. [步骤1]
登入web终端，登陆windows
![Snip20190719_1](https://user-images.githubusercontent.com/23494468/61507263-94448900-aa17-11e9-97d0-2827c38f59f0.png)

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/23494468/61507354-fdc49780-aa17-11e9-8d3b-5eb2b3ef60c7.png)
这里是gua日志 感觉像是闪断了 确认网络是通的，私底下rdp可以连接，之前issue说的换window16换成普通window协议不管用，重启nginx也不管用

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaoigl 建议把系统用户自动登录换成手动登录看看，能否出现登录页面，如果不能表示资产的远程设置有误，如果能出现登录界面表示系统用户密码错误
![QQ20190719-142642](https://user-images.githubusercontent.com/24326988/61513951-4177cb00-aa31-11e9-8a75-1923aa313868.png)

**Comment by BaiJiangJie** [comment]
@xiaoigl 问题解决了吗？

**Comment by xiaoigl** [comment]
完美解决 谢谢
