### ISSUE TITLE
历史会话和命令记录搜索资产不能用

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#2997]
[简述你的问题]

历史会话和命令记录搜索资产不能用
##### 使用版本
jumpserver 1.5.2

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/13861904/61518073-5eb19700-aa3b-11e9-95f9-aa2674119dd1.png)
![image](https://user-images.githubusercontent.com/13861904/61518154-8274dd00-aa3b-11e9-8cf2-2d6abe6e9e21.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
资产使用全名搜索测试一下？

**Comment by jym503558564** [comment]
资产支持全名搜索，如有其它问题可重新打开issues
