### ISSUE TITLE
如果授权给单个资产，在ssh终端刷新的时候会异常退出

### ISSUE THREAD

**Issue by jasper-zhang** [jumpserver/jumpserver#2998]
[简述你的问题]
如果授权给单个资产，在ssh终端刷新的时候会异常退出

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1、授权的时候填单个资产；
2、ssh终端刷新报错；

##### 具体表现[截图可能会更好些,最好能截全]
coco报错：
![image](https://user-images.githubusercontent.com/6657098/61526723-9590a880-aa4d-11e9-9211-451d1ed6ffb8.png)

##### 其他
coco里面tree的root的名字叫`ROOT_ALL_ORG_NODE`，而未分组的key是1，导致找不到报错；

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已解决，git pull解决

**Comment by jasper-zhang** [comment]
嗯，谢谢大佬
