### ISSUE TITLE
页面`我的资产`，和ssh终端用`g节点号`查询父节点的时候，查不到其子节点里面的资产

### ISSUE THREAD

**Issue by jasper-zhang** [jumpserver/jumpserver#2999]
[简述你的问题]
页面`我的资产`，和ssh终端用`g节点号`查询父节点的时候，查不到其子节点里面的资产

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/6657098/61527257-970ea080-aa4e-11e9-842d-db1b607432c3.png)

![image](https://user-images.githubusercontent.com/6657098/61527386-e48b0d80-aa4e-11e9-823a-015eff72b419.png)

这个应该显示36条

##### 其他

[注:] 完成后请关闭 issue

**Comment by huangzx** [comment]
1.5.2 我也出现同样的问题，加了资产出不来。
最近 2 个版坑好多，先退回 1.5.0 了

**Comment by ibuler** [comment]
1.5.2版本目前只显示了直接节点下的资产，没有显示子节点资产

**Comment by ibuler** [comment]
@huangzx 这不是bug，而是策略的改变

**Comment by huangzx** [comment]
@ibuler 
我的问题是：新增加的资产，终端不显示。

**Comment by jasper-zhang** [comment]
@ibuler 这个功能还是可以加上吧，在`资产列表`就是这样的策略，耗时也不是很长呢

**Comment by jasper-zhang** [comment]
@huangzx 可能是缓存原因，你`r`刷新一下

**Comment by huangzx** [comment]
不是缓存问题。
强刷，重启 jms，coco 都不出现

**Comment by jasper-zhang** [comment]
我说的是后台redis的缓存，不是浏览器的

**Comment by ibuler** [comment]
已解决，请更新一下，可以查看所有资产了

**Comment by jasper-zhang** [comment]
好的，已验证，thx

**Comment by ibuler** [comment]
感谢反馈
