### ISSUE TITLE
2019-07-22 15:46:02 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

### ISSUE THREAD

**Issue by TroubleJin** [jumpserver/jumpserver#3006]
v1.5.1 --> v1.5.2

koko日志报错

**Comment by jym503558564** [comment]
@LeeEirc

**Comment by jym503558564** [comment]
可先用源码部署 koko

**Comment by Icedroid** [comment]
我也是一直报这个错，用的是1.5.2的koko

**Comment by jym503558564** [comment]
@Icedroid @TroubleJin 可先用koko源码部署
-  克隆koko源码项目 : `git clone  https://github.com/jumpserver/koko.git `
-  安装 go:  `brew install go`
-  设置环境变量：
    -  `vim .bash_profile`
    -  `export GOPROXY=https://goproxy.io`
    -  使环境生效 `source .bash_profile`
- koko项目切换到cmd目录 ,然后复制config_example.yml更改配置
    - cp config_example.yml config.yml 复制一份配置文件
    - vim config.yml 编辑配置文件
        -  修改配置文件里的信息，跟之前coco相似，可参考coco之前部署coco的修改
- 切换到cmd目录，启动koko项目： `go run koko.go`

**Comment by Icedroid** [comment]
我直接用koko的master的源码下的dockerfile 构建镜像，跑起来没有上面的错误，但ssh和web终端都登录不了资源，web终端登录资产都提示：
You don't have permission login test@172.30.0.2

同时koko报错如下：
```bash
[ERRO] GET http://jumpserver:8080/api/perms/v1/asset-permissions/user/validate/?action_name=connect&cache_policy=1&user_id=8d661a84-7df4-4fd7-80f6-a8187f2f7799&asset_id=eecc26e1-da43-4942-8ae2-2442788cc845&system_user_id=25d70aba-a30b-440b-8607-75b70d28f045 failed, get code: 404, <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
```

**Comment by jym503558564** [comment]
git pull 一下core的代码
- 目前关于这个问题可先刷新一下授权
![image](https://user-images.githubusercontent.com/40739051/61997485-ab007500-b0d4-11e9-97d3-00d0c600946c.png)

**Comment by jym503558564** [comment]
git pull 一下core代码
- 是授权的节点新添加的资产吗？目前关于这个问题，可先刷新授权
![image](https://user-images.githubusercontent.com/40739051/61997499-e4d17b80-b0d4-11e9-8411-66190f682b31.png)

**Comment by Icedroid** [comment]
我koko用的是master，jumpserver按照文档用的是1.4.8，所有不行... jumpserver master代码运行不了？jms start all 提示python no modules ipdb

**Comment by jym503558564** [comment]
@Icedroid  jumpserver 1.5.2增加了刷新授权缓存按钮

**Comment by ibuler** [comment]
必须要用同样的版本，koko master不支持 1.4.8

**Comment by mike20190710** [comment]
我也碰到了这个问题。用的1.5.2版本。
ssh端可以连接。web端连接不了，一直卡着。日志报这个错
websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

**Comment by wenbc** [comment]
[ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header  
这个错误怎么解决的？

**Comment by wojiushixiaobai** [comment]
@wenbc @mike20190710 版本一定要一致。包括luna,koko,jms

**Comment by wojiushixiaobai** [comment]
nginx问题，确认下，一般少了这三行
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
