### ISSUE TITLE
SMTP 配置在 jumpserver 服务重启后丢失

### ISSUE THREAD

**Issue by zhb127** [jumpserver/jumpserver#3008]
[简述你的问题]

##### 使用版本

Version 1.5.1-2 GPLv2

##### 问题复现步骤
1. 使用 admin 登录 jumpserver 后，填写完 smtp 配置
2. 点击测试按钮，在发送账号中能够收到 "Test smtp setting" 测试邮件内容
3. 点击提交
4. 页面刷新后，SMTP 密码丢失
5. 重启 jumpserver 服务后，SMTP 配置丢失
6. 检查 redis 配置，发现重启 jumpserver 服务之前，SMTP 配置 key 能够找到，重启后，对应的 key 丢失
7. 检查 mysql 表，发现重启前后，SMTP 相关的配置都没有写入到表中

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/5210208/61618626-cec05700-ac9f-11e9-8c63-d5e8ec87248c.png)

![image](https://user-images.githubusercontent.com/5210208/61618683-e992cb80-ac9f-11e9-85e4-6c6b88a018a4.png)

> 检查 redis 配置，发现重启 jumpserver 服务之前，SMTP 配置 key 能够找到，重启后，对应的 key 丢失

![image](https://user-images.githubusercontent.com/5210208/61618879-6160f600-aca0-11e9-8b57-d2784bd4d5e7.png)

> 检查 mysql 表，发现重启前后，SMTP 相关的配置都没有写入到表中

![image](https://user-images.githubusercontent.com/5210208/61619001-92412b00-aca0-11e9-98b2-3e6bf0c9c9f5.png)

**Comment by BaiJiangJie** [comment]
Fixed. (https://github.com/jumpserver/jumpserver/commit/d93305f6a44e5b02a9049d32c8e6b7042e655175)
请等待Merge到master分支。

**Comment by BaiJiangJie** [comment]
Fixed.（master）
