### ISSUE TITLE
private key invalid

### ISSUE THREAD

**Issue by zhb127** [jumpserver/jumpserver#3010]
[简述你的问题]
从服务器上获取 id_rsa 后，创建系统用户，提示错误。从 jumpserver.log 中，无法确认错误的具体原因

##### 使用版本
Version 1.5.1-2

##### 问题复现步骤
1. 如图

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/5210208/61622974-688c0200-aca8-11e9-860a-8eed2750f11b.png)

![image](https://user-images.githubusercontent.com/5210208/61622782-0b904c00-aca8-11e9-9aaf-15c9897ce4ba.png)

![image](https://user-images.githubusercontent.com/5210208/61622817-1e0a8580-aca8-11e9-838a-ce0fdcf7d4dd.png)

**Comment by ibuler** [comment]
1.5.2 fixed

**Comment by zhb127** [comment]
此处做一下问题总结：

![image](https://user-images.githubusercontent.com/5210208/61781749-7c19a300-ae37-11e9-9a51-5e03019918ff.png)

我遇到的问题是密钥格式问题。

同时，版本需要升级到 1.5.2 才会出现如图的错误提示，之前使用 1.5.1，无法定位到具体原因。

**Comment by ibuler** [comment]
1.5.1 也不支持 OPENSSH 格式的，目前仅支持 PEM格式的

**Comment by zhb127** [comment]
> 1.5.1 也不支持 OPENSSH 格式的，目前仅支持 PEM格式的

嗯嗯，好的。

上面的回复可能有些误解哈，我改一下评论，目前，我遇到的问题已经解决了，这里做一下解决后的回复。
