### ISSUE TITLE
Ldap账号设置为无效后,终端依旧可以登陆

### ISSUE THREAD

**Issue by TroubleJin** [jumpserver/jumpserver#3012]
Ldap账号设置为无效后,终端依旧可以登陆。只是web无法登陆。

**Comment by BaiJiangJie** [comment]
哪个版本？

**Comment by TroubleJin** [comment]
v1.5.1

**Comment by TroubleJin** [comment]
> 哪个版本？

v1.5.1

**Comment by BaiJiangJie** [comment]
> > 哪个版本？
> 
> v1.5.1

看一下终端登录时，core的日志。

**Comment by TroubleJin** [comment]
> > > 哪个版本？
> > 
> > 
> > V1.5.1
> 
> 看一下终端登录时，核心的日志。

您好，哪里应用的日志？ jumpserver.log没有日志产生

**Comment by BaiJiangJie** [comment]
> > > > 哪个版本？
> > > 
> > > 
> > > V1.5.1
> > 
> > 
> > 看一下终端登录时，核心的日志。
> 
> 您好，哪里应用的日志？ jumpserver.log没有日志产生

Log路径：/opt/jumpserver/logs/jumpserver.log
LDAP账号设置为无效，是在Jumpserver里设置的，还是在LDAP服务器上设置的？

**Comment by TroubleJin** [comment]
> > > > 哪个版本？
> > > 
> > > 
> > > V1.5.1
> > 
> > 
> > 看一下终端登录时，核心的日志。
> 
> 您好，哪里应用的日志？jumpserver.log没有日志产生

登录日志没有记录终端登录信息


![image](https://user-images.githubusercontent.com/48788965/61696134-6046cc00-ad67-11e9-87ff-ed9d6b415a90.png)

**Comment by TroubleJin** [comment]
> > > > > 哪个版本？
> > > > 
> > > > 
> > > > V1.5.1
> > > 
> > > 
> > > 看一下终端登录时，核心的日志。
> > 
> > 
> > 您好，哪里应用的日志？jumpserver.log没有日志产生
> 
> Log路径：/opt/jumpserver/logs/jumpserver.log 
> LDAP 账号设置为无效，是在Jumpserver里设置的，还是在LDAP服务器上设置的？

是在Ldap里面设置的无效，结果Web端可以登陆错误，终端正常

**Comment by BaiJiangJie** [comment]
> > > > > > 哪个版本？
> > > > > 
> > > > > 
> > > > > V1.5.1
> > > > 
> > > > 
> > > > 看一下终端登录时，核心的日志。
> > > 
> > > 
> > > 您好，哪里应用的日志？jumpserver.log没有日志产生
> > 
> > 
> > Log路径：/opt/jumpserver/logs/jumpserver.log
> > LDAP 账号设置为无效，是在Jumpserver里设置的，还是在LDAP服务器上设置的？
> 
> 是在Ldap里面设置的无效，结果Web端可以登陆错误，终端正常

测试里下在LDAP里禁用用户，web和终端都不可登录。

**Comment by TroubleJin** [comment]
> > > > > > > 哪个版本？
> > > > > > 
> > > > > > 
> > > > > > V1.5.1
> > > > > 
> > > > > 
> > > > > 看一下终端登录时，核心的日志。
> > > > 
> > > > 
> > > > 您好，哪里应用的日志？jumpserver.log没有日志产生
> > > 
> > > 
> > > Log路径：/opt/jumpserver/logs/jumpserver.log 
> > > LDAP 账号设置为无效，是在Jumpserver里设置的，还是在LDAP服务器上设置的？
> > 
> > 
> > 是在的Ldap里面设置的无效，结果网页端可以登陆错误，终端正常
> 
> 测试里下在LDAP里禁用用户，网络和终端都不可登录。

您好，需要什么特别的配置吗？因为使用的是终端使用的秘钥登陆的，禁用ldap是可以的

**Comment by TroubleJin** [comment]
> > > > > > > 哪个版本？
> > > > > > 
> > > > > > 
> > > > > > V1.5.1
> > > > > 
> > > > > 
> > > > > 看一下终端登录时，核心的日志。
> > > > 
> > > > 
> > > > 您好，哪里应用的日志？jumpserver.log没有日志产生
> > > 
> > > 
> > > Log路径：/opt/jumpserver/logs/jumpserver.log 
> > > LDAP 账号设置为无效，是在Jumpserver里设置的，还是在LDAP服务器上设置的？
> > 
> > 
> > 是在的Ldap里面设置的无效，结果网页端可以登陆错误，终端正常
> 
> 测试里下在LDAP里禁用用户，网络和终端都不可登录。

您好，需要什么特别的配置吗？终端使用秘钥登陆的，Ldap禁用后，xshell之类的终端依旧可以，web端无法登陆。

**Comment by BaiJiangJie** [comment]
![1563877238751](https://user-images.githubusercontent.com/32935519/61704648-c6871b00-ad76-11e9-8955-680f9b4cca8e.jpg)

将LDAP禁用字段和Jumpserver里的is_active字段做个映射。

**Comment by TroubleJin** [comment]
ldap_is_active_field 是Ldap里面自定义的字段吗？我按照您的方式报异常。

**Comment by TroubleJin** [comment]
> ![1563877238751](https://user-images.githubusercontent.com/32935519/61704648-c6871b00-ad76-11e9-8955-680f9b4cca8e.jpg)
> 
> 将LDAP禁用字段和Jumpserver里的is_active字段做个映射。

ldap_is_active_field 是Ldap里面自定义的字段吗？我按照您的方式报异常。

**Comment by TroubleJin** [comment]
> ![1563877238751](https://user-images.githubusercontent.com/32935519/61704648-c6871b00-ad76-11e9-8955-680f9b4cca8e.jpg)
> 
> 将LDAP禁用字段和Jumpserver里的is_active字段做个映射。

LDAP中将用户删除后，终端用秘钥依旧是可以登陆的。

**Comment by BaiJiangJie** [comment]
这个版本确实有问题，逻辑上不是很合理，下一个版本会禁止LDAP/AD等第三方用户添加或更新SSH公钥信息。

**Comment by ibuler** [comment]
如果是 ldap，可以禁用公钥认证，因为 公钥在ldap上没有
