### ISSUE TITLE
sftp Permission deny

### ISSUE THREAD

**Issue by w01fb0ss** [jumpserver/jumpserver#3016]
[sftp Permission deny]

##### 使用版本
jumpserver 1.4.5
coco 1.5.0

##### 问题复现步骤
1. 刚开始提示tmp没有权限，改了个SFTP_ROOT为别的用户还是没有权限
2. 机器上系统用户和管理用户对 tmp 和新的SFTP_ROOT 权限都是1777

##### 具体表现
![image](https://user-images.githubusercontent.com/44709004/61697574-1b706480-ad6a-11e9-8e7f-46155e2bfe65.png)

![image](https://user-images.githubusercontent.com/44709004/61697536-0693d100-ad6a-11e9-87c3-5bd4b22a7409.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by w01fb0ss** [comment]
![image](https://user-images.githubusercontent.com/44709004/61697679-596d8880-ad6a-11e9-93ad-f4c8d7975b86.png)

**Comment by w01fb0ss** [comment]
？？？

**Comment by zhimin-fit2cloud** [comment]
请升级到 1.5.2.

**Comment by w01fb0ss** [comment]
> 请升级到 1.5.2.

已经找到问题，一步一步调试后发现是下面这种情况

![17_07_57__07_30_2019](https://user-images.githubusercontent.com/44709004/62116442-c0e88280-b2ec-11e9-9db4-e624195e48d3.jpg)
