### ISSUE TITLE
通过Web Terminal 访问 Linux 资产无任何提示

### ISSUE THREAD

**Issue by zhangnian2015** [jumpserver/jumpserver#3018]
通过分布式部署jumpservr后通过Web Terminal 访问 Linux 资产无任何提示，但是通过ssh可以连接，并且在控制台点击文件管理显示的是一个空白页面，通过查看日志，发现是koko提示以下错误：
Web Terminal 访问 Linux 资产时报错：{"log":"2019-07-23 16:57:35 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header\n","stream":"stdout","time":"2019-07-23T08:57:35.576820301Z"}
控制台点击文件管理时报错：{"log":"2019-07-23 16:59:11 [ERRO] ERROR: websocket: request origin not allowed by Upgrader.CheckOrigin\n","stream":"stdout","time":"2019-07-23T08:59:11.23117986Z"}

使用的版本是1.5.2，各个组件全部通过docker方式部署，配置基本都是参照官方文档配置的

**Comment by zhangnian2015** [comment]
相同的配置，我发现当我把koko换成coco后，就可以正常通过Web Terminal 访问 Linux 资产，koko则死后不行，这是koko的bug吗？

**Comment by jym503558564** [comment]
可先用源码部署koko

**Comment by jym503558564** [comment]
@zhangnian2015 可先用koko源码部署，步骤参考如下：
- 克隆koko源码项目 : git clone https://github.com/jumpserver/koko.git
- 安装 go: brew install go
- 设置环境变量：vim .bash_profile
   - export GOPROXY=https://goproxy.io
   - 使环境生效 source .bash_profile
- koko项目切换到cmd目录 ,然后复制config_example.yml更改配置
   - cp config_example.yml config.yml 复制一份配置文件
   - vim config.yml 编辑配置文件
       - 修改配置文件里的信息，跟之前coco相似，可参考coco之前部署coco的修改
- 切换到cmd目录，启动koko项目： go run koko.go
