### ISSUE TITLE
向一个节点里面加一个机器后，用户能看到新增加的机器，但登陆报没有权限的错误

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#3019]
[简述你的问题]
向一个节点里面加一个机器后，用户能看到新增加的机器，但登陆报没有权限的错误

##### 使用版本
jumpserver 1.5.2

##### 问题复现步骤
1. 
![image](https://user-images.githubusercontent.com/13861904/61701232-6a20fd00-ad70-11e9-8611-5dedd42a8f24.png)
2.
用户能看到新增加的缓存xxx服务器，但是登陆报“没有权限”
![image](https://user-images.githubusercontent.com/13861904/61701353-963c7e00-ad70-11e9-948c-1b84b8f50fa4.png)
3.
到资产授权里面重新更新一下
![image](https://user-images.githubusercontent.com/13861904/61701488-d439a200-ad70-11e9-8793-94ee1bda2e73.png)
![image](https://user-images.githubusercontent.com/13861904/61701508-dc91dd00-ad70-11e9-95ef-a8a033ded398.png)
4.
这时才能正常登陆，我们感觉这样是不是太麻烦了。
![image](https://user-images.githubusercontent.com/13861904/61701591-06e39a80-ad71-11e9-8c9c-1a6d8a12ed14.png)

不知道我把问题描述清楚了吗

**Comment by BackFire** [comment]
我这边也遇到同样的问题

**Comment by huangzx** [comment]
我这边也遇到同样的问题

**Comment by linuxu2015** [comment]
我这边也遇到同样的问题,如果授权规则多的话，需要更新很多条

**Comment by jym503558564** [comment]
git pull 更新一下
![image](https://user-images.githubusercontent.com/40739051/61920591-bfd1f100-af8c-11e9-8be2-437803a81eeb.png)

**Comment by ibuler** [comment]
已修复，之前自动刷新有些问题
