### ISSUE TITLE
用户组添加用户，编辑用户，所选择应该是username,而不是name吧！

### ISSUE THREAD

**Issue by liulizhi** [jumpserver/jumpserver#302]
`<select id="users" name="users" size="12" class="form-control m-b" multiple>
    {% for user in users_remain %}
          <option value="{{ user.id }}">{{ user.name }}</option>
     {% endfor %}
</select>
`
问题：公司name一样的同学很多，在这里做选择时，基本是同名选项，无法分清对应的user.id是谁。
建议改进：因为username 唯一，name不唯一。将select option的值改为user.username,请dev看看是否需要修改。

**Comment by ibuler** [comment]
fixed 新版本
