### ISSUE TITLE
不支持redis cluster做缓存

### ISSUE THREAD

**Issue by jasper-zhang** [jumpserver/jumpserver#3021]
[简述你的问题]
不支持redis cluster做缓存

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1、如果配置一个redis cluster，服务起来之后会报"keys"命令不存在

##### 其他
应该换个支持redis cluster的django cache库就可以了

[注:] 完成后请关闭 issue

**Comment by jasper-zhang** [comment]
测试了一下，https://github.com/deforestg/django-cluster-redis 这个是可以的，只需要加到requirements里面，然后配置里面支持单机和集群两种方式即可

**Comment by ibuler** [comment]
除了cache库，还有celery库，所以比较麻烦

**Comment by ibuler** [comment]
你可以尝试改改，欢迎PR

**Comment by ibuler** [comment]
暂时不考虑依赖redis的太多
