### ISSUE TITLE
koko启动只能自己现在手动放入后台启动吗？

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#3023]
koko启动只能自己现在手动放入后台启动吗？之前coco是 启动使用-d即可。

**Comment by jym503558564** [comment]
docker部署koko 可以后台启动

**Comment by huangpeng0817** [comment]
> docker部署koko可以后台启动

这个知道的，我们这边都没有用docker，之前的coco有后台启动方式，现在这个koko没有，需要手动&放入后台没那么方便

**Comment by jym503558564** [comment]
是的，目前新koko没有支持

**Comment by huangpeng0817** [comment]
> 是的，目前新koko没有支持

请问下一本版本更新会增加吗？目前这样使用不是那么方便

**Comment by wojiushixiaobai** [comment]
./koko -d
