### ISSUE TITLE
添加权限和编辑权限出现RangeError: Invalid Date

### ISSUE THREAD

**Issue by hp198410** [jumpserver/jumpserver#3025]
[简述你的问题]
权限管理-> 资产授权 添加授权或更新授权 会出现报错
具体错误截图贴在下方

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.2-2 GPLv2
环境 macos 10.14.5 + safari

##### 问题复现步骤
进入 https://jumpserver.xxx.com/perms/asset-permission/create/?assets=&nodes=
填好各参数提交，不会成功
然后在浏览器控制台会报错

##### 具体表现[截图可能会更好些,最好能截全]
![issue](https://user-images.githubusercontent.com/8498080/61783600-ad47a280-ae3a-11e9-8e11-14bc8812a6b1.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
git pull 更新一下到最新版本
