### ISSUE TITLE
上传和下载经常导致cpu彪到100%

### ISSUE THREAD

**Issue by qtfreet00** [jumpserver/jumpserver#3027]
[简述你的问题]
使用rz sz sftp经常会导致docker环境下cpu飙到100%，导致其他用户或者当前用户其他操作完全无法执行

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.3.1-2
##### 问题复现步骤
1. [步骤1]  sz xxx.zip
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1.3.x 已经不提供支持
