### ISSUE TITLE
命令行界面搜索功能失效

### ISSUE THREAD

**Issue by TopSpoofer** [jumpserver/jumpserver#3028]
[简述你的问题]
登录到堡垒机界面后，如果资产比较多出现分页的情况下，无法进行搜索。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver 1.5.1

##### 问题复现步骤
1. [步骤1]
录入多个资产，使登录堡垒机界面后出现分页。
![image](https://user-images.githubusercontent.com/5953930/61838942-36ec8400-aebe-11e9-912e-1e3bd168b53d.png)

2. [步骤2]
输入 :/测试 进行搜索（中文搜索）
出现的结果是：跳到下一页的资产列表去了
期望结果是：搜索出所有带测试字样的资产

如果跳到最后一页，没有了”下一页：Enter|N/n” 字样后进行搜索就可以出现正确结果！
![image](https://user-images.githubusercontent.com/5953930/61839072-c1cd7e80-aebe-11e9-8ea7-8341e2b1e4b8.png)

系统：mac os Mojave 10.14.4，终端 iTerm
或者 win 10 xshell 同样有这个问题

##### 其他

可能是这个终端程序的bug，读入用户输入后判断不正确？

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- 在分页的情况下，可直接输入当前页的资产id进行登录
- 在欢迎界面可进行搜索资产
![image](https://user-images.githubusercontent.com/40739051/62035687-edd06300-b222-11e9-889a-e6fb8a032edd.png)
![image](https://user-images.githubusercontent.com/40739051/62035738-02146000-b223-11e9-976c-b7009b9e8a52.png)

**Comment by TopSpoofer** [comment]
@jym503558564  我个人觉得还是 提供搜索比较靠谱，因为进入了分页的页面好像就不能退出到欢迎页面了，

**Comment by TopSpoofer** [comment]
@jym503558564  刚才试了一下，输入q即可，然后可以搜索了

**Comment by jym503558564** [comment]
因为在分页的时候，输入q,是已经回到欢迎的界面了。在欢迎的界面是可以进行搜索的~

**Comment by TopSpoofer** [comment]
@jym503558564  对，一开始对这个交互有误解

**Comment by jym503558564** [comment]
恩呐～如有其它问题可重新提issues

**Comment by TopSpoofer** [comment]
@jym503558564  谢谢哈
