### ISSUE TITLE
web登陆不过期

### ISSUE THREAD

**Issue by Malcolmjian** [jumpserver/jumpserver#3030]
[简述你的问题]
web关闭后再次打开用户不过期
vi /opt/jumpserver/config.yml
设置 SESSION_EXPIRE_AT_BROWSER_CLOSE: true
多次重启服务均无效果

##### 使用版本
Version 1.5.2-2 GPLv2.

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复  https://github.com/jumpserver/jumpserver/commit/3b67bd3b870dff3ae36314957b4ca86c35fc4bda
