### ISSUE TITLE
jumperserver 不定期无法连接

### ISSUE THREAD

**Issue by junly917** [jumpserver/jumpserver#3031]
[简述你的问题]
 使用监控对cocod的端口进行监控，会提示端口异常，但很快会自动启动恢复.
之后Jumperserver 会出现无法连接， 现有连接可以正常工作, 新的连接无法进行连接;
查看了cocod的日志信息并没有明显的报错信息;
对cocod 进行stop 和start之后, 问题可以解决;
通过监控系统只看到重启cocod 之后连接数会明显的降低(如图)

##### 使用版本
Version 1.4.10-2 GPLv2.

##### 问题复现步骤
不定期出现无法复现问题

##### 其他
现需要如何排查问题? 没有思路,请指教;

[注:] 完成后请关闭 issue
![image](https://user-images.githubusercontent.com/16676780/61853526-aed2a280-aeee-11e9-886f-48643f0c15b5.png)

**Comment by jym503558564** [comment]
新的连接无法进行连接，是指新添加的资产吗？

**Comment by ibuler** [comment]
新版本已修复，当时是由于有些连接没有被释放导致的

**Comment by junly917** [comment]
> 新版本已修复，当时是由于有些连接没有被释放导致的

新版本己修复是多少版本？ 我查看了release，但是好像并没有说明修复这个bug的功能；

**Comment by junly917** [comment]
> 新的连接无法进行连接，是指新添加的资产吗？

不是新添加的资料，就是新建一个会话都无法连接jumperserver 主机；cocod完会没有用了。
