### ISSUE TITLE
批量命令显示的资产不全是怎么回事

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#3037]
[简述你的问题]
我给用户授权了很多linux机器，但是我发现批量命令里面只有几个机器，是怎么回事？

##### 使用版本
jumpserver 1.5.2版本

##### 问题复现步骤
1. 我的资产里面，我给用户授权了83台linux机器：
![image](https://user-images.githubusercontent.com/13861904/61924377-0d088f80-af9a-11e9-932b-bdde3a36f62b.png)
2、可是我在批量命令里面才看到9台机器，请问是哪里控制的看批量命令机器的权限：
![image](https://user-images.githubusercontent.com/13861904/61924464-8607e700-af9a-11e9-9d82-687a56344454.png)

**Comment by jym503558564** [comment]
根据选择的系统用户显示资产
![image](https://user-images.githubusercontent.com/40739051/61925665-e51c2a80-af9f-11e9-9240-6bb388837c33.png)
![image](https://user-images.githubusercontent.com/40739051/61925678-f06f5600-af9f-11e9-82db-9cddca35be60.png)

**Comment by czxin788** [comment]
正解，谢谢。
