### ISSUE TITLE
RDP分辨率AUTO 全屏显示并非全屏！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#3039]
[简述你的问题]

连接RDP资产 rdp分辨率为自动，连接后点击全屏显示，仍然无法全屏，上下均有一块无法显示
##### 使用版本
1.5.2-2
chrome浏览器
windows10操作系统
##### 问题复现步骤
1. 手动设置分辨率1366X768 后全屏可以全部展开，但esc退出全屏后，浏览器内显示
桌面左右各有一块无法显示
2. 目前笔记本的分辨率基本在1920X1080，是否可以改成该分辨率进行手动设定
开发大佬是不是从网络流畅度考虑，才设置的较低分辨率？ 

##### 具体表现[截图可能会更好些,最好能截全]

![TIM图片20190729134216](https://user-images.githubusercontent.com/36059301/62024215-bce23500-b206-11e9-89f7-5c8d1ed07c44.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
通常服务器不是开发机，不需要太高分辨率，高分辨率会带来网络IO比较大，所以限制了

**Comment by huangpeng0817** [comment]
> 通常服务器不是开发机，不需要太高分辨率，高分辨率会带来网络IO比较大，所以限制了

请问需要修改录像记录，就是希望在ssh后在欢迎界面就开始录像，这块代码需要在哪里改动。目前是用户连接到资产后才开始录像

**Comment by huangpeng0817** [comment]
> 通常服务器不是开发机，不需要太高分辨率，高分辨率会带来网络IO比较大，所以限制了

使用的coco

**Comment by vicentwu** [comment]
好的，明白了，

**Comment by Tiny66** [comment]
> 通常服务器不是开发机，不需要太高分辨率，高分辨率会带来网络IO比较大，所以限制了

请教下 ，是否能手动开启1920*1080
