### ISSUE TITLE
Guacamole每天需要重启才能正常运行

### ISSUE THREAD

**Issue by xiaoigl** [jumpserver/jumpserver#3041]
[简述你的问题]
Guacamole每天重启才能正常运行，不然web终端就登陆不了windows，并且日志到23:59:5x就不会有日志了，docker进程显示还在，请问怎么解决。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0-2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/23494468/62024968-4c88e300-b209-11e9-943f-1cb14d4bcecf.png)
![image](https://user-images.githubusercontent.com/23494468/62025009-67f3ee00-b209-11e9-88e0-3e59cabdcf88.png)
两天前启动 到现在日志就没有了
![image](https://user-images.githubusercontent.com/23494468/62025052-8eb22480-b209-11e9-85e8-41aa80d7a841.png)

重启
![image](https://user-images.githubusercontent.com/23494468/62025078-a689a880-b209-11e9-87ea-05ecf85442f1.png)
重启成功后解决问题
![image](https://user-images.githubusercontent.com/23494468/62025128-d042cf80-b209-11e9-8379-b09a62d41275.png)
![image](https://user-images.githubusercontent.com/23494468/62025218-1ac44c00-b20a-11e9-99b8-5335a26bc135.png)

1.首先不想每天定时重启Guacamole，有没有解决方案或者遇到过类似问题
2.为什么Guacamole的运行时间同服务器时间不一致
多谢

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
gua连不上时，收集一下gua的日志截图贴出来

**Comment by xiaoigl** [comment]
> gua连不上时，收集一下gua的日志截图贴出来

您好 是用docker部署的Gua，日志截图如正文所示，每到启动Gua当日23:59:5x就没有日志出了

**Comment by jym503558564** [comment]
建议更新一下版本

**Comment by jym503558564** [comment]
建议更新一下版本，看问题是否还会复现

**Comment by jym503558564** [comment]
您好，更新完版本后，是否问题已解决？

**Comment by xiaoigl** [comment]
> 您好，更新完版本后，是否问题已解决？

您好 更新版本后依然存在这个问题 请问如果我要卸载掉guacamole的docker安装 装原生的guacamole的文档有吗
