### ISSUE TITLE
【功能需求】终端登录，还有web页面的资产显示列表上能加上显示内外IP么？

### ISSUE THREAD

**Issue by l-duan** [jumpserver/jumpserver#3042]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.1注: 0.3.x不再提供支持]

##### 其他

终端登录，还有web页面的资产显示列表上能加上显示内外IP么？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
外网ip目前没有真正使用，存在意义不大，感谢反馈，将来看看怎么好好利用
