### ISSUE TITLE
外网无法通过web访问ssh终端，也无法打开文件管理，局域网都正常

### ISSUE THREAD

**Issue by jnghzhang** [jumpserver/jumpserver#3056]
外网无法通过web访问ssh终端，也无法打开文件管理，局域网都正常。外网情况vnc、rdp都正常，通过crt访问ssh终端也正常。外网是通过端口映射到内部jumpserver

##### 使用版本
版本1.5.2，通过急速安装方式安装

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
报错截图

**Comment by jnghzhang** [comment]
关键没错误日志，十分纳闷.
![image](https://user-images.githubusercontent.com/53485182/62184297-fc885880-b38f-11e9-9c7f-aa7e6ae3cba8.png)
网络抓包，通过外网走的数据包
![image](https://user-images.githubusercontent.com/53485182/62184349-4bce8900-b390-11e9-9c0f-f4fb38e4d8da.png)

**Comment by jnghzhang** [comment]
内外网打开文件管理正常会多个#尾巴

**Comment by jnghzhang** [comment]
2019/07/31 17:33:46 [warn] 1243#1243: *137 upstream server temporarily disabled while connecting to upstream, client: 10.115.0.2, server: , request: "GET /zh-hans/jsi18n/ HTTP/1.1", upstream: "http://[::1]:8080/zh-hans/jsi18n/", host: "bl.jngh.tk:8081", referrer: "http://bl.jngh.tk:8081/assets/user-asset/"
2019/07/31 17:34:33 [error] 1243#1243: *139 connect() failed (111: Connection refused) while connecting to upstream, client: 10.115.0.2, server: , request: "GET /api/users/v1/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/users/v1/profile/", host: "bl.jngh.tk:8081", referrer: "http://bl.jngh.tk:8081/luna/?login_to=45893437-85d0-465c-a7a1-7bea4aa71445"
2019/07/31 17:34:33 [warn] 1243#1243: *139 upstream server temporarily disabled while connecting to upstream, client: 10.115.0.2, server: , request: "GET /api/users/v1/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/users/v1/profile/", host: "bl.jngh.tk:8081", referrer: "http://bl.jngh.tk:8081/luna/?login_to=45893437-85d0-465c-a7a1-7bea4aa71445"
2019/07/31 17:36:32 [error] 1243#1243: *242 connect() failed (111: Connection refused) while connecting to upstream, client: 10.115.0.2, server: , request: "GET /api/users/v1/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/users/v1/profile/", host: "bl.jngh.tk:8081", referrer: "http://bl.jngh.tk:8081/luna/?login_to=45893437-85d0-465c-a7a1-7bea4aa71445"
2019/07/31 17:36:32 [warn] 1243#1243: *242 upstream server temporarily disabled while connecting to upstream, client: 10.115.0.2, server: , request: "GET /api/users/v1/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/users/v1/profile/", host: "bl.jngh.tk:8081", referrer: "http://bl.jngh.tk:8081/luna/?login_to=45893437-85d0-465c-a7a1-7bea4aa71445"

**Comment by panhuachao** [comment]
@jnghzhang 你好，你的情况解决了吗？

**Comment by panhuachao** [comment]
我这边这个问题已解决。因为新版本采取wss协议，而nginx中代理转发要配置兼容wss协议，增加配置即可。

**Comment by jnghzhang** [comment]
部署完最新版本这个问题解决了额，但是redis的问题，邮件发不出去，登录也没信息显示
