### ISSUE TITLE
web terminal 机器列表展示小建议

### ISSUE THREAD

**Issue by liuhetongzi** [jumpserver/jumpserver#3057]
[简述你的问题]
当授权只针对资产授权的时候，web terminal登录的时候机器属于未分组里面，不知道属于哪个节点组里面，有的时候不太直观，不太人性化，能否优化，读取nodes信息，将其分组。（不针对nodes授权，是因为一个nodes组里面的资产，登录的密码有的是不一样的）
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2 
##### 问题复现步骤
1. [步骤1]
![图片](https://user-images.githubusercontent.com/23496061/62179228-5f70f400-b37e-11e9-9376-7735f1eee666.png)
2. [步骤2]
![图片](https://user-images.githubusercontent.com/23496061/62179255-74e61e00-b37e-11e9-969f-d51e309d663a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个是优化后的结果，之前是会把资产放到所属的节点，后来好多用户说，没有授权的节点不应该显示出来

**Comment by liuhetongzi** [comment]
可是有的一个nodes里面机器的登录密码不一样，无法通过nodes赋权，可以设置优先级吗，赋权时候同时有资产和nodes，资产优先级高，赋权的系统用户只对资产生效，不对nodes生效。

**Comment by shyp88** [comment]
还是希望可以展现成之前的带节点名称的界面，或者可以让管理员自己配置选择，好多用户升级完都以为遇到bug了，既然主机都赋权了，没必要那么在意被看到节点名称吧。。。都显示未分组的话如果有很多主机就显得非常凌乱，不好找，毕竟很多用户都只有节点下部分主机的权限。希望考虑，谢谢。

**Comment by ibuler** [comment]
已处理，请更新
