### ISSUE TITLE
重置密码报错

### ISSUE THREAD

**Issue by 7cristiano** [jumpserver/jumpserver#3058]
[简述你的问题]
重置密码有token报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. [步骤1]
收到重置密码的邮件后，点击设置密码
2. [步骤2]
输入完新密码后点击设置，会出现报错
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/33511216/62181692-bda1d500-b386-11e9-8db1-cba3c4b42c27.png)

![image](https://user-images.githubusercontent.com/33511216/62181599-656ad300-b386-11e9-91cc-fe082dcdb595.png)

![image](https://user-images.githubusercontent.com/33511216/62181629-86332880-b386-11e9-8b0f-f7df38b42b8f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by 7cristiano** [comment]
重启后解决了，先关闭了

**Comment by 7cristiano** [comment]
后面还是有问题，求解决

**Comment by wojiushixiaobai** [comment]
@7cristiano 请更新到1.5.2版本后再试试，建议先在测试环境进行测试。

**Comment by ibuler** [comment]
@BaiJiangJie 确认一下
