### ISSUE TITLE
创建用户上传秘钥报错

### ISSUE THREAD

**Issue by jiangtao007** [jumpserver/jumpserver#3060]
[简述你的问题]
创建系统用户时候上传秘钥报错（秘钥不需要密码），提示500.但是创建用户输入密码是可以正常创建的。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
使用的最新的docker镜像jumpserver/jms_all:latest
##### 具体表现[截图可能会更好些,最好能截全]
![111111](https://user-images.githubusercontent.com/26705490/62204281-7dab1400-b3bf-11e9-9df2-f80393a7c0f9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jiangtao007** [comment]
![2222](https://user-images.githubusercontent.com/26705490/62205593-5efa4c80-b3c2-11e9-8a68-558b936b5c9a.png)

**Comment by wojiushixiaobai** [comment]
@jiangtao007 latest还未更新到当前最新的代码，这个问题在最新版本中已经修复，请根据文档部署或者使用1.4.8

**Comment by ibuler** [comment]
已修复
