### ISSUE TITLE
Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#3062]
[简述你的问题]
使用批量命令功能，执行报如下错误：
Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex

但是资产可以通过web 终端登录的。
##### 使用版本
jumpserver 1.5.2

##### 问题复现步骤
1、使用批量命令报错
![image](https://user-images.githubusercontent.com/13861904/62260941-4fbce280-b446-11e9-8593-e7f201b8d83b.png)

2、但该机器可以通过web 终端登录
![image](https://user-images.githubusercontent.com/13861904/62260987-74b15580-b446-11e9-9ae9-fb3d80da0de7.png)

**Comment by wojiushixiaobai** [comment]
@czxin788 确定系统用户可正常连接资产，你登录的系统用户和批量命令使用的系统用户不一样
