### ISSUE TITLE
【文件下载】- 通过sftp下载文件异常，文件损坏

### ISSUE THREAD

**Issue by supershrek** [jumpserver/jumpserver#3063]
[简述你的问题]
文件下载方式有两种：
1、通过web系统进到文件管理界面，做上传/下载操作，上传和下载的文件没任何问题，能正常打开！！！但是因为web没那么稳定，而且不支持断点续传，传大文件没那么方便
2、通过sftp终端来传输，传输稳定，支持断点续传，但是发现上传文件无异常，能正常打开，下载文件，打开出现异常，提示文件损坏等，无论文件大小

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
最新版本，
Version 1.5.0-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]
文件下载方式有两种：
1、通过web系统进到文件管理界面，做上传/下载操作，上传和下载的文件没任何问题，能正常打开！！！但是因为web没那么稳定，而且不支持断点续传，传大文件没那么方便
2、通过sftp终端来传输，传输稳定，支持断点续传，但是发现上传文件无异常，能正常打开，下载文件，打开出现异常，提示文件损坏等，无论文件大小
##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- 关于版本号查看的问题：
      - 在页面右下角可查看

**Comment by supershrek** [comment]
> * 关于版本号查看的问题：
>   - 在页面右下角可查看

谢谢，看到了，版本是：  Version 1.5.0-2

**Comment by ibuler** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
@supershrek 建议使用最新的1.5.2。

**Comment by LeeEirc** [comment]
@supershrek 建议使用最新的1.5.2。

**Comment by supershrek** [comment]
> @supershrek 建议使用最新的1.5.2。

谢谢，我根据官网的升级指引升级到1.5.2之后，出现web终端不能使用的问题，跟踪了一下，发现是koko容器里面的koko进程的问题 直接返回400

**Comment by supershrek** [comment]
> @supershrek 建议使用最新的1.5.2。

能不能麻烦看下，比较着急

**Comment by LeeEirc** [comment]
koko需要使用最新版本的luna。先检查一下各组件是否都正常。nginx配置是否正确。有无异常错误，最好能贴出截图和相关日志。




| |
李智
邮箱：xplzv@126.com
|

签名由 网易邮箱大师 定制

在2019年08月14日 19:10，supershrek 写道：

@supershrek 建议使用最新的1.5.2。

能不能麻烦看下，比较着急

**Comment by supershrek** [comment]
> koko需要使用最新版本的luna。先检查一下各组件是否都正常。nginx配置是否正确。有无异常错误，最好能贴出截图和相关日志。 | | 李智 邮箱：xplzv@126.com | 签名由 网易邮箱大师 定制 在2019年08月14日 19:10，supershrek 写道： @supershrek 建议使用最新的1.5.2。 能不能麻烦看下，比较着急 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

根据你们提供的升级步骤，下载的是1.5.2的luna，其他功能都正常，就只有web 终端展示有问题了
![image](https://user-images.githubusercontent.com/4003378/63021534-6138cc80-bed3-11e9-8eda-d501053f70f8.png)

卡住了一样，下载文件损坏的bug已经修复，window连接也比原来稳定和快了

我跟踪进去发现是koko容器里面访问就是400 反馈异常

**Comment by supershrek** [comment]
> koko需要使用最新版本的luna。先检查一下各组件是否都正常。nginx配置是否正确。有无异常错误，最好能贴出截图和相关日志。 | | 李智 邮箱：xplzv@126.com | 签名由 网易邮箱大师 定制 在2019年08月14日 19:10，supershrek 写道： @supershrek 建议使用最新的1.5.2。 能不能麻烦看下，比较着急 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

版本从1.5.0 升级到 1.5.2 之后会话管理里面的web终端异常，点击不能进入对应的服务器，直接通过ssh终端登录没问题

抓包发现错误为： Status Code: 400 Bad Request 

即访问 5000端口的服务会出现这个问题

进到容器中直接连接 5000，直接反馈 400 Bad Request ，说明容器内的koko服务有问题

**Comment by LeeEirc** [comment]
@supershrek 可能是你的nginx配置不对，你查看一下koko容器的日志？

**Comment by supershrek** [comment]
> koko容器的日志
nginx的配置是按照你们说明配置的，而且我测试了下，其他业务都是正常的，资产都可以测试连通等。看可能是nginx哪里配置的问题？

请教一下，怎么查看koko容器的日志？

**Comment by supershrek** [comment]
> @supershrek 可能是你的nginx配置不对，你查看一下koko容器的日志？

nginx的配置是按照你们说明配置的，而且我测试了下，其他业务都是正常的，资产都可以测试连通等。看可能是nginx哪里配置的问题？

请教一下，怎么查看koko容器的日志？

**Comment by supershrek** [comment]
> @supershrek 可能是你的nginx配置不对，你查看一下koko容器的日志？

2019-08-15 16:48:17 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2019-08-15 16:48:17 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 

感觉是有点问题

**Comment by supershrek** [comment]
@LeeEirc ，koko的log拿到了，麻烦看下要怎么解决

2019-08-15 16:48:17 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
2019-08-15 16:48:17 [ERRO] ERROR: websocket: the client is not using the websocket protocol:

**Comment by LeeEirc** [comment]
@supershrek 如果koko已经是最新的话，那么你luna版本可能不是最新的

**Comment by supershrek** [comment]
> @supershrek 如果koko已经是最新的话，那么你luna版本可能不是最新的

比较了md5确定是最新的

**Comment by LeeEirc** [comment]
@supershrek 加入koko群908100817交流一下。

**Comment by supershrek** [comment]
@BaiJiangJie ，你好，感觉这个是1.5.2的luna的bug，我没有重新部署，直接从1.5.0升级到1.5.2的，就出现web终端无妨访问的问题

**Comment by supershrek** [comment]
升级到1.5.2 后解决了下载文件的损坏问题
