### ISSUE TITLE
【bug】-- 查询“历史会话” 和 “命令记录” 通过 “用户”过滤不能正常过滤出记录

### ISSUE THREAD

**Issue by supershrek** [jumpserver/jumpserver#3064]
[简述你的问题]
进入跳板机web页面

菜单： “会话管理” -> “历史会话” 和 “命令记录” 通过 “用户” 过滤不能正常过滤出记录

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

Version 1.5.0-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]
进入跳板机web页面

菜单： “会话管理” -> “历史会话” 和 “命令记录” 通过 “用户” 过滤不能正常过滤出记录
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1.5.2 fixed

**Comment by shyp88** [comment]
我今天还刚想提这个bug，我就是1.5.2，还是会这样啊，只不过我在历史会话里通过用户过滤异常，但在命令记录里通过用户过滤正常。
我看了数据库表，之前版本历史记录里用户字段只是用户名，新版本写入的是名称(用户名)，以前过滤是正常的。不知道是不是新版本导致的问。
另外，我还发现主机名只要带了空格，就没法通过主机名过滤，因为我习惯于把主机名写成“ip 用途”，如果我主机名只写个ip的话，是可以正常过滤的。
希望官方确认下是不是像我说的这样。
