### ISSUE TITLE
关于录像功能

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#3069]
目前录像功能是在用户登陆到有权限的资产后才有的录像。请问我想提前就要录像，比如他ssh登陆到了jumpserver上，查询自己权限，这样的操作都录像下来，需要在哪里修改代码？

**Comment by huangpeng0817** [comment]
@wojiushixiaobai  就是使用ssh登陆 到欢迎界面就开始录像。这块修改代码是在哪里啊。

**Comment by huangpeng0817** [comment]
是用的coco。

**Comment by wojiushixiaobai** [comment]
@huangpeng0817 ssh协议和telnet协议。用户执行的命令是即时上传的，审计这块开发老哥们还在修改

**Comment by huangpeng0817** [comment]
因为最新用的koko了。go语言写的。我这边新功能希望在coco上二次开发，python语言。自己加端口转发。就是希望能在ssh登陆上就开始录像。增加录像的话，coco上要改动增加录像代码吗？希望能有记录用户使用的记录。想请教下ssh登陆就录像这块代码的修改在不在coco上

**Comment by shyp88** [comment]
感觉记录这部分录像没什么意义啊，在还没登陆主机时，他啥也干不了，只能选择管理员分配的主机，有什么好录的呢。真要看他访问了哪些主机，直接在历史会话里过滤一下就出来。不知道这个需求有何意义

**Comment by huangpeng0817** [comment]
> 感觉记录这部分录像没什么意义啊，在还没登陆主机时，他啥也干不了，只能选择管理员分配的主机，有什么好录的呢。真要看他访问了哪些主机，直接在历史会话里过滤一下就出来。不知道这个需求有何意义

我们这边有这个需求的。目前我们是在现有的coco上增加了端口转发功能，不会去登陆主机。目前只能让记录日志，没录像的话，没那么方便。
