### ISSUE TITLE
web terminal vim编辑打开一个文件复制行出现换行的问题

### ISSUE THREAD

**Issue by luashiping** [jumpserver/jumpserver#307]
web terminal里通过vim编辑打开一个文件复制一行，我在编辑器里粘贴出现了换行
vim打开如下图：
https://pan.baidu.com/s/1bM31cq

编辑器sublime打开如下图：
https://pan.baidu.com/s/1c1GtI2s

**Comment by luashiping** [comment]
@ibuler

**Comment by luashiping** [comment]
@liuzheng712 知道吗

**Comment by liuzheng712** [comment]
这个是一行啊。。。。

**Comment by changxy726** [comment]
粘贴后变成了3行吧

**Comment by liuzheng712** [comment]
才明白过来是想说明什么....
页面上显示当然会做换行截断,这个换行截断是 js 我们做的,不是浏览器行为,典型的例子请看如下:

浏览器做的换行:
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

页面 js 做的 n 字符的换行:
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
ddddddddddddddddddddd

看上去效果一样,实际实现原理不同

为什么不用浏览器自己做换行是因为浏览器处理的不好
