### ISSUE TITLE
web terminal rdp连接 大写锁定后crtl+c无效！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#3070]
[简述你的问题]

##### 使用版本
1.5.2-2

##### 问题复现步骤
1. 当锁定大写键后，web terminal下连接windows服务器ctrl+c复制字符，无法粘贴到本地，
采用右键复制，然后粘贴到本地就OK
2、解除大写锁定，两种方式都可以，

考虑是不是jumpserver设置的快捷键和哪个有冲突导致？

##### 具体表现[截图可能会更好些,最好能截全]

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@vicentwu 测试了一些，无法验证。

**Comment by ibuler** [comment]
原生guacamole不支持，所以不考虑支持
