### ISSUE TITLE
jenkins能不能配合jumpserver使用，目前登录到jumpserver后，需要交互，无法自动完成

### ISSUE THREAD

**Issue by zhiyuanhuhu** [jumpserver/jumpserver#3072]
我想用jenkins进行ssh连接生产环境的服务器
jenkins => jumpserver=>productserver

问题是我ssh到jumpserver后，让我选择服务器。能不能通过一行命令，直接连接到productserver。
目前是jenkins连接到跳板机后，出现交互界面，无法通过脚本继续执行。

##### 使用版本
1.5

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时不支持隧道来直接连接，等待迭代支持

**Comment by chaoyebugao** [comment]
希望支持+1

**Comment by jinggee** [comment]
现在还是不支持吗？

jenkins build完成后，要把生成的文件通过ssh上传到目标服务器，然后再连到目标服务器，执行一些命令。 现在只能连堡垒机，怎么通过堡垒机远程执行命令？

**Comment by jinggee** [comment]
@ibuler

**Comment by ibuler** [comment]
目前支持了，

**Comment by ibuler** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
待调研，后续优化支持。不过可能无法录像和记录操作

**Comment by lizhifengones** [comment]
现在支持了吗？

**Comment by lizhifengones** [comment]
或者说 jenkins + jumpserver 的最佳实践是什么？必须让jenkins能直接访问jumpserver的服务器？暂不支持连通跳板机后通过api对服务器进行增删改查？

**Comment by guvmao** [comment]
> 目前支持了，

请问现在有相关文档或支持计划么  @ibuler @LeeEirc

**Comment by LeeEirc** [comment]
已经支持，参考 https://github.com/jumpserver/jumpserver/issues/9064
