### ISSUE TITLE
软连接无法正常显示

### ISSUE THREAD

**Issue by lovese** [jumpserver/jumpserver#3076]
##### 问题描述
Web文件管理无法正常显示软连接，本来是一个目录，但是显示成了一个未知文件，无法打开该目录，但是用xftp客户端能正常显示和使用

##### 使用版本
最新版

##### 问题复现
创建目录的软连接应该就能发现了

##### 具体表现
![image](https://user-images.githubusercontent.com/13268438/62449806-963f7380-b79d-11e9-88d7-1f679ba37bbd.png)

![image](https://user-images.githubusercontent.com/13268438/62449867-b2431500-b79d-11e9-9c35-e201e69ea8bb.png)

**Comment by ibuler** [comment]
@LeeEirc

**Comment by czblse** [comment]
这个解决了吗？怎么关掉了
