### ISSUE TITLE
Django从1.9版本就支持在settings.py文件中配置TIME_ZONE了，不需要手动+8了

### ISSUE THREAD

**Issue by dean2021** [jumpserver/jumpserver#3077]
Django从1.9版本就支持在settings.py文件中配置TIME_ZONE了，不需要手动+8了，
管理大大改一下吧

**Comment by dean2021** [comment]
我说的是数据库配置哪里的时区

**Comment by ibuler** [comment]
貌似没有哪里设置数据库的时区吧

**Comment by dean2021** [comment]
> 貌似没有哪里设置数据库的时区吧

link : https://docs.djangoproject.com/en/1.9/ref/settings/#time-zone，

e.g：

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydatabase',
        'USER': 'mydatabaseuser',
        'PASSWORD': 'mypassword',
        'HOST': '127.0.0.1',
        'PORT': '5432',
       'TIME_ZONE':'Asia/Shanghai',
    }
}
