### ISSUE TITLE
Jumpserver中手动连接资产：windows server 2019 时 ，报错：连接错误，无法连接服务器，请联系管理员或查看日志。

### ISSUE THREAD

**Issue by CWeThough** [jumpserver/jumpserver#3081]
Jumpserver中手动连接windows server 2019 时 ，报错：连接错误，无法连接服务器，请联系管理员或查看日志。

jumpserver 1.5.2-2

1. 部署一体式jumpserver，添加windows server 2019 作为资源，用户和协议配置完成，自动连接一切正常，手动连接时 报错：无法连接服务器，请联系管理员或查看日志。

2. 添加 windows server 2016 及其他版本时，自动连接正常，手动连接正常。

**Comment by CWeThough** [comment]
![微信截图_20190806130154](https://user-images.githubusercontent.com/53807758/62518038-2db6cc00-b85b-11e9-84d1-097c4ac0145d.png)

**Comment by ibuler** [comment]
只能通过日志来确认

**Comment by zhengqingzhixuan** [comment]
我也发现这个问题了，只能自动登陆

**Comment by zhengqingzhixuan** [comment]
选 windows    不要选windows2016

**Comment by zhengqingzhixuan** [comment]
断开连接后，点重连无效，需要关闭窗口再连接
