### ISSUE TITLE
windows资产连接不上

### ISSUE THREAD

**Issue by johnseen** [jumpserver/jumpserver#3082]
[简述你的问题]
windows资产连接不上

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. [步骤1]
连接windows资产,报错无法连接服务器，请联系管理员或查看日志
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/19249402/62516830-a9634980-b858-11e9-9d97-1a7f31c06a08.png)
![image](https://user-images.githubusercontent.com/19249402/62516859-b97b2900-b858-11e9-8e35-8165ae5cfca8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by awklinux** [comment]
同样的问题，楼主解决了分享下

**Comment by ibuler** [comment]
截图位置不对，应该有个error的日志

**Comment by cliu93** [comment]
应该在session -> terminal 看看Gua是否是active的。
可以参考：
https://jumpserver.readthedocs.io/zh/master/faq_rdp.html

**Comment by johnseen** [comment]
谢谢大家,已经找到问题,是因为主机加域的问题!

**Comment by johnseen** [comment]
已关闭!
