### ISSUE TITLE
jumpserver升级版本后登录返回504

### ISSUE THREAD

**Issue by xymsayly** [jumpserver/jumpserver#3087]
[简述你的问题]
按照官方文档从jumpserver1.3.2升级到了1.5.2，升级完成后可以打开登录页面，但输入用户名和密码，点击登录后，会一直加载，最后返回nginx 502，能否提供一个排查思路或者可能的原因，谢谢

##### 使用版本
[1.5.2]

##### 问题复现步骤
1. 从1.3.2升级到了1.4.4，升级过程未返回报错，升级完成后可以正常登录和连接资产
2. 从1.4.4升级到了1.5.2，升级过程未返回报错，升级完成后所有端口侦听正常
3、本地telnet侦听的端口，均可以通
4、访问80端口可以正常打开登录页面，但登录会一直加载，最后返回超时
（以下截图均为1.5.2版本的问题截图）
##### 具体表现[截图可能会更好些,最好能截全]
端口侦听截图
![image](https://user-images.githubusercontent.com/34665997/62615305-9bd4bf00-b93f-11e9-8a92-298065938da0.png)
nginx配置文件
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
    server {
    listen 80;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
    }
    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }
    location /static/ {
        root /opt/jumpserver/data/;
    }
    location /socket.io/ {
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /guacamole/ {
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        access_log off;
    }
   location /coco/ {
        proxy_pass       http://localhost:5000/coco/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
}
超时界面
![image](https://user-images.githubusercontent.com/34665997/62615563-19003400-b940-11e9-9456-456b008e851e.png)
##### 其他
Guacamole为docker部署，其他均为正常部署

[注:] 完成后请关闭 issue

**Comment by huangpeng0817** [comment]
nginx 配置没贴全吧。 web 侦听80 转到8080 上。

**Comment by ibuler** [comment]
查看一下错误日志，有没有报错

**Comment by xymsayly** [comment]
经过测试，原来的环境配置了ldap,登录的时候好像去ldap认证了，但是连接不到ad服务器，在nginx里将超时时间设置了5分钟，然后在登录进行了4分钟左右登录成功了，在将ldap禁用后，下次登录立马就完成了
