### ISSUE TITLE
【bug】查询“资产授权”通过 “用户”过滤不能正常过滤出记录

### ISSUE THREAD

**Issue by shyp88** [jumpserver/jumpserver#3089]
[简述你的问题]

##### 使用版本
Version 1.5.2-2 GPLv2
20190808 做过git pull 拉取最新代码运行。
20190808下午，用全新服务器，完整安装全套最新版jumpserver，确认有问题。

##### 问题复现步骤
1. WEB界面进入
2. 权限管理
3. 资产授权

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/46096444/62664474-3966d780-b9ae-11e9-80f2-28fd2e2e6ff9.png)

![图片](https://user-images.githubusercontent.com/46096444/62664551-9d899b80-b9ae-11e9-9816-081c93d82b53.png)

![图片](https://user-images.githubusercontent.com/46096444/62664579-ba25d380-b9ae-11e9-913b-0d7b6c296994.png)

其他过滤条件基本都好用，就是用用户过滤，查询某个用户在哪些授权规则中进行了配置，就无法正常过滤，并不是显示无结果，而是感觉没有进行过滤，下面仍然列出的是所有授权规则。

此问题长久以来一直存在，记得在1.4版本时候就不行，从来没有过滤成功过。请官方确认，谢谢

##### 其他

[注:] 完成后请关闭 issue

**Comment by shyp88** [comment]
经大神指点已解决，例如用户名为Test (test)，过滤时需要写成Test+(test)，全匹配，这样就能过滤出来了。感谢大神。

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/commit/785b375f4a3e4e425fed13cf41f02759b6dd7225 已修复，等待merge
