### ISSUE TITLE
内存大小及硬盘容量显示问题

### ISSUE THREAD

**Issue by lovese** [jumpserver/jumpserver#3092]
内存大小显示不准，没有取整，个别容量过大硬盘没有换算，见截图

##### 使用版本
最新版
##### 具体表现
![image](https://user-images.githubusercontent.com/13268438/62677549-54067400-b9e1-11e9-8816-a92e680d3de3.png)

##### 其他
希望可以改进

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/commit/fbfbfcc2743f2faa4c6a145ef4c4cbf536a1bae6 修复，等待merge到master
