### ISSUE TITLE
时间显示问题

### ISSUE THREAD

**Issue by TroubleJin** [jumpserver/jumpserver#3098]
[简述你的问题]

##### 使用版本
1.5.1 版本  会话管理时间慢8小时 ,mysql和系统时间都是CST +8:00
![image](https://user-images.githubusercontent.com/48788965/62757790-fb9da800-baae-11e9-898d-e66f6198d3ec.png)

**Comment by BaiJiangJie** [comment]
1.5.2 版本解决，升级一下。
