### ISSUE TITLE
docker部署jms_all可连接性失败

### ISSUE THREAD

**Issue by SakuraGaara** [jumpserver/jumpserver#3099]
[简述你的问题]

> 2019-08-09 14:03:50 任务开始: 更新资产硬件信息: 192.168.1.192
PLAY [更新资产硬件信息: 192.168.1.192] *************************************************
TASK [setup] *******************************************************************
fatal: [192.168.1.192]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Control socket connect(/root/.ansible/cp/13177e09cf): Connection refused\r\nFailed to connect to new control master", "unreachable": true}
2019-08-09 14:03:51 任务结束
获取资产信息失败：192.168.1.192

##### 使用版本
使用镜像：jumpserver/jms_all:1.5.1

##### 问题复现步骤
1. 创建管理用户root, root是资产上的root账户和密码
2. 创建资产，使用的管理用户root
3. 测试可连接性，失败

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/25793981/62757892-4e775f80-baaf-11e9-8d03-814d4994cb60.png)
![image](https://user-images.githubusercontent.com/25793981/62757916-618a2f80-baaf-11e9-995d-16667896efef.png)

![image](https://user-images.githubusercontent.com/25793981/62757862-31429100-baaf-11e9-89a2-6f9747aa9c2a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yuanhaoliang** [comment]
建议检查一下防火墙设置，docker部署出口IP一般是172开头的IP。
