### ISSUE TITLE
1.5.2 资产节点显示异常

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#3103]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2

##### 问题复现步骤
1. 资产列表，子节点出现大量missing，仅能显示几个节点。
2. 资产列表显示主机数400+，实际点开节点只能看到几十台，Web Terminal 问题同上。
3. 从 1.4.6 按照升级指引  升级到  1.5.2 版本。
##### 其他

[注:] 完成后请关闭 issue

**Comment by NeilyoSH** [comment]
管理员用户，资产列表仅能显示几个节点，Web Terminal则能正常显示
![image](https://user-images.githubusercontent.com/27417058/62847925-7e22a380-bd0b-11e9-9c71-a48cb6ae03b6.png)

![image](https://user-images.githubusercontent.com/27417058/62847895-63e8c580-bd0b-11e9-8ac9-e81a49d8ce24.png)

**Comment by xupeng9** [comment]
我这里的问题是资产显示总数是正确的，每页默认显示15条信息，但是到第二页就是有很多与第一页重复的记录。如果我把每页记录显示条数，选择为大于资产实际条数的话（比如实际资产20条记录，我选择每页显示25条），就能完整的显示出来。感觉前端有问题！版本：1.5.2

**Comment by zhaileilei123** [comment]
我也遇到相同的问题。从1.4.6升级到1.5.2之后  资产列表树 只显示Engineering 下一个节点名。资产数量是正常的。无法在Enginerring显示新创建的子节点。
更新资产信息中选择节点是可以选择新创建的子节点。

**Comment by zhaileilei123** [comment]
![图片](https://user-images.githubusercontent.com/38358012/63407599-722b9580-c41f-11e9-8634-3f8690736b25.png)
![图片](https://user-images.githubusercontent.com/38358012/63407661-9dae8000-c41f-11e9-8ec8-801877d9165e.png)

**Comment by zhaileilei123** [comment]
![图片](https://user-images.githubusercontent.com/38358012/63407834-27f6e400-c420-11e9-8c61-5987bca40bfe.png)

**Comment by rrfeng** [comment]
UP
1. 部分节点（某个时刻之后创建的）无法显示，数据库中存在
2. 新创建的节点刷新后即消失。再次创建会报冲突。

查看 API，请求的是：
`/api/assets/v1/nodes/children/tree/?assets=0&refresh=1`

另外一个 API 可以返回完整的节点：
`/api/assets/v1/nodes/tree/?assets=0&refresh=1`

不知道这俩有什么区别。
请尽快修复。

**Comment by rrfeng** [comment]
受影响的还有资产授权页面，系统用户页面等等。

这个影响太大了，有无回退版本的办法？

**Comment by BaiJiangJie** [comment]
已在 1.5.3 版本中修复，请升级。
感谢对 Jumpserver 的支持。
