### ISSUE TITLE
jumpserver突然不能登陆资产机器

### ISSUE THREAD

**Issue by tfnick** [jumpserver/jumpserver#3106]
[简述你的问题]
之前web控制台中，jumpserver能够访问所有资产，某一天管理员只是做了一些资产的管理操作之后，web控制台中就不能登陆所有的目标资产机器了

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.6-2 GPLv2
##### 问题复现步骤
1. [步骤1] 删除了一些无效的资产
2. [步骤2] 对用户能够访问的资产做了一些修改
![image](https://user-images.githubusercontent.com/28697276/62855524-19744280-bd25-11e9-8595-bddd924ce5ce.png)

##### 具体表现[截图可能会更好些,最好能截全]
管理员登陆web控制台之后，点击左侧某个资产，右侧页签光标一直闪烁，不能进入

##### 其他

[注:] 完成后请关闭 issue

**Comment by Crushlinuxstart** [comment]
你好 你的问题解决了吗

**Comment by wojiushixiaobai** [comment]
coco或koko组件未启动或者启动失败

**Comment by Dragon-zw** [comment]
我这边也出现了类似的问题，Jumpserver突然之间无法正常的Web UI进行登录。
![QQ截图20240422000006](https://github.com/jumpserver/jumpserver/assets/51999823/e70e206f-d07b-4f80-9942-b4509334195f)
使用的最新的Jumpserver v3.10.7
![QQ截图20240422000113](https://github.com/jumpserver/jumpserver/assets/51999823/a0454300-c0e5-494d-806d-8df99204f8ff)
用的是Helm部署的Jumpserver，查看组件都是正常！
