### ISSUE TITLE
漏洞：后台添加用户处（其实不止，其它同类）可执行任意命令

### ISSUE THREAD

**Issue by peter17919** [jumpserver/jumpserver#311]
后台用户管理--添加用户处，如果被恶意构造，即可执行任意命令，因为jumpserver使用的是root权限启动，所以有最高权限，比如添加用户时提交如下代码，即可关机jumpserver系统：
`username=test'%26%26reboot%26%26echo+'1&name=test&role=CU&email=test@test.com`
其它地方如果也是直接调用subprocess.call的话也存在同样的问题，在此不一一列举

大家可千万别在demo上测试，要不老广该生气了

**Comment by ibuler** [comment]
收到，感谢反馈
