### ISSUE TITLE
SSH连接异常

### ISSUE THREAD

**Issue by lovese** [jumpserver/jumpserver#3112]
SSH连接异常，查看日志报session不够，SFTP连接没有得到释放
![image](https://user-images.githubusercontent.com/13268438/62910178-1f643500-bdb2-11e9-905b-a086b18264ee.png)

默认是10个session，刚好满了就再也连接不上了，必须杀掉这些session，才可以连接

##### 使用版本
最新版

##### 问题复现步骤
还不清楚为啥会这样，好像是开发用xftp工具多开连接窗口

##### 具体表现
Connect asset PH-web-server error: ssh: rejected: administratively prohibited (open failed)

**Comment by wojiushixiaobai** [comment]
@lovese 资产的sshd_config  
MaxSession 10  # 默认为10，请自行修改

**Comment by lovese** [comment]
@wojiushixiaobai 我改了这个参数后重启SSH服务，不起作用，最多还是10个，我觉得重点不是这个参数的问题，是session不会释放，一直占用

**Comment by wojiushixiaobai** [comment]
@lovese koko或者coco  config.yml里面关闭连接复用

**Comment by lovese** [comment]
我测试一下看看

**Comment by halfsre** [comment]
这个问题解决了吗？同样问题

**Comment by zhixiangjoy** [comment]
+1 I meet the same problem !

**Comment by auto007** [comment]
我也遇到了这个问题

**Comment by zhougui150** [comment]
+1

**Comment by KeithTt** [comment]
> @lovese 资产的sshd_config
> MaxSession 10 # 默认为10，请自行修改

改了这个参数，但是没起作用
