### ISSUE TITLE
导入资产失败

### ISSUE THREAD

**Issue by lx277856602** [jumpserver/jumpserver#3113]
[简述你的问题]
按规定模板填写并导入资产时，报错导致导入失败

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. [资产管理]-->[导入资料]-->[下载模板]-->填写模板
2. [上传]资产csv文件

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/2842255/62912862-5dfeed00-bdbc-11e9-954b-d4336507c49c.png)
![image](https://user-images.githubusercontent.com/2842255/62912881-7242ea00-bdbc-11e9-9ba9-61680ad39be5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lx277856602 请使用最新的模版，随便导出一个资产，参考该样板导入即可

**Comment by jym503558564** [comment]
- 管理用户请填写管理用户的id
![image](https://user-images.githubusercontent.com/40739051/62989793-13dd4080-be7c-11e9-88f2-6987be559f4c.png)

**Comment by lx277856602** [comment]
@wojiushixiaobai @jym503558564 根据两位建议，尝试了导出后的模板+导入时的模板
![image](https://user-images.githubusercontent.com/2842255/63147788-ce627400-c031-11e9-838d-53ee7a68e4f2.png)
测试结果如下：
1.使用导出的1条记录变更资产名称后以更新形式上传执行成功
2.使用导出的1条记录，新增1条资产，【管理用户】处使用了UUID，以【上传】途径上传时,**出错**【Server error occur, contact administrator】
![image](https://user-images.githubusercontent.com/2842255/63147970-5779ab00-c032-11e9-9119-bf90cab92ea8.png)
3.使用导出的1条记录，新增1条资产，【管理用户】处使用了UUID，以【更新】途径上传时,**出错**
![image](https://user-images.githubusercontent.com/2842255/63148029-83952c00-c032-11e9-85f0-9bde83464944.png)
目前还不知道是什么原因以及如何解决？
