### ISSUE TITLE
使用koko 文件管理跳转 问题

### ISSUE THREAD

**Issue by yaocanfeng** [jumpserver/jumpserver#3114]
[简述你的问题]

##### 使用版本
1.5.2

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/21379210/62921901-91ea0a80-bddc-11e9-8854-ee8dbbcd437d.png)
![image](https://user-images.githubusercontent.com/21379210/62921920-9f9f9000-bddc-11e9-83f8-469573473e05.png)
![image](https://user-images.githubusercontent.com/21379210/62921949-b7771400-bddc-11e9-97f6-cab142ac98a9.png)
![image](https://user-images.githubusercontent.com/21379210/62921971-ccec3e00-bddc-11e9-88ef-3d378b1701d3.png)

2. [步骤2]
资产管理的主节点改不了名称
![image](https://user-images.githubusercontent.com/21379210/62922032-fc9b4600-bddc-11e9-8d52-ab664de187bb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yaocanfeng 文档也没要你改nginx的内容呀。。

只是让你把coco容器或者组件改成koko，没说接口变了。
