### ISSUE TITLE
jumpserver无法将windows录像上传到AWS  S3 问题确认

### ISSUE THREAD

**Issue by xymsayly** [jumpserver/jumpserver#3115]
[简述你的问题]
在jumpserver中配置了aws ak,sk来将录像保存到AWS S3中，llinux服务器录像可以正常上传和播放，但是windows服务器的录像无法上传到AWS S3，只保存到了本地磁盘上
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 具体表现[截图可能会更好些,最好能截全]
coco配置
![image](https://user-images.githubusercontent.com/34665997/62935286-4c880600-bdf9-11e9-81c9-c5c1177c56e5.png)
gucamole配置
![image](https://user-images.githubusercontent.com/34665997/62935301-5c074f00-bdf9-11e9-89e9-322bbf040550.png)
nginx配置文件
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    include /etc/nginx/conf.d/*.conf;
    server {
    listen 80;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
    }
    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }
    location /static/ {
        root /opt/jumpserver/data/;
    }
    location /socket.io/ {
        proxy_pass       http://localhost:5000/socket.io/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }
    location /coco/ {
        proxy_pass       http://localhost:5000/coco/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
   }
    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        access_log off;
        client_max_body_size 100m;
    }
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
｝

nginx 错误日志
2019/08/13 18:36:18 [error] 1041#0: *230 connect() failed (111: Connection refused) while connecting to upstream, client: 119.254.228.2, server: , request: "GET /terminal/terminal/42a2a8ed-0272-44b5-9027-8d87b95061a8/update/ HTTP/1.1", upstream: "http://[::1]:8080/terminal/terminal/42a2a8ed-0272-44b5-9027-8d87b95061a8/update/",host: "52.81.50.52", referrer: "http://52.81.50.52/terminal/terminal/"
2019/08/13 18:36:18 [error] 1040#0: *234 connect() failed (111: Connection refused) while connecting to upstream, client: 119.254.228.2, server: , request: "GET /zh-hans/jsi18n/ HTTP/1.1", upstream: "http://[::1]:8080/zh-hans/jsi18n/", host: "52.81.50.52", referrer: "http://52.81.50.52/terminal/terminal/42a2a8ed-0272-44b5-9027-8d87b95061a8/update/"
2019/08/13 18:36:53 [error] 1040#0: *234 connect() failed (111: Connection refused) while connecting to upstream, client: 119.254.228.2, server: , request: "GET /zh-hans/jsi18n/ HTTP/1.1", upstream: "http://[::1]:8080/zh-hans/jsi18n/", host: "52.81.50.52", referrer: "http://52.81.50.52/terminal/terminal/d2b2ffe3-b4eb-44d0-bdd2-ff8d31e4503f/update/"

终端设备
![image](https://user-images.githubusercontent.com/34665997/62935476-d2a44c80-bdf9-11e9-9e38-b7539d969327.png)

##### 其他
coco正常部署，gucamole使用docker部署

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xymsayly 检查下guacamole容器能不能访问你的AWS S3网络

**Comment by xymsayly** [comment]
我进容器以后是可以ping通AWS S3的节点的，我应该如何进行测试@wojiushixiaobai
