### ISSUE TITLE
1.5.2 Linux上传文件超过10M大小会失败

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#3116]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2]

##### 问题复现步骤
1. Linux 文件管理控制台，传输文件大小超过10M会失败报错 object of type ‘None Type’ has no len()
2. 传10M以内的文件则正常。

##### 其他
![image](https://user-images.githubusercontent.com/27417058/62989339-25254d80-be7a-11e9-875b-2059b2aa020c.png)

[注:] 完成后请关闭 issue

**Comment by shyp88** [comment]
1.5.2release版本是正常的，我上次git pull了一把，也出现同样问题，不知道是否是部分代码更新导致。所以我暂时退回了release版本，坐等下次1.5.3release。

**Comment by LeeEirc** [comment]
已经修复，可等待最新1.5.2版本。




| |
李智
邮箱：xplzv@126.com
|

签名由 网易邮箱大师 定制

在2019年08月14日 11:11，shyp88 写道：

1.5.2release版本是正常的，我上次git pull了一把，也出现同样问题，不知道是否是部分代码更新导致。所以我暂时退回了release版本，坐等下次1.5.3release。
