### ISSUE TITLE
windows文件传输失败

### ISSUE THREAD

**Issue by yutian1224** [jumpserver/jumpserver#3117]
[简述你的问题]
jumpserver的web终端登录windows服务器后,连接文件管理上传文件,出现"No asset or system user explicit "报错

##### 使用版本
1.5.2

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13673671/63001665-aeeb1000-bea6-11e9-9d26-0f87b7d60d3e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yutian1224 目前仅支持自动登录的ssh协议资产

**Comment by yutian1224** [comment]
@wojiushixiaobai 
资源管理器里guacamole的网盘还能看见,我记得好像以前可以用.
那是不是现在版本没有向windows资产上传/下载文件的手段了?
