### ISSUE TITLE
新增的资产，系统用户推送、测试连接都成功，但是连接时，提示没有权限

### ISSUE THREAD

**Issue by zhb127** [jumpserver/jumpserver#3122]
[简述你的问题]

新增的资产，在系统用户推送、测试连接都成功之后，使用 web 终端连接目标服务器，提示没有权限。

##### 使用版本
- Version 1.5.2-2 GPLv2
- 系统环境：linux

##### 问题复现步骤
1. 新增资产
2. 推送系统用户，成功
3. 测试连接，成功
4. 使用 web 终端，连接提示，没有权限

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/5210208/63023141-043f1580-bed7-11e9-8b16-dc3aa1df5bd5.png)

![image](https://user-images.githubusercontent.com/5210208/63023191-1e78f380-bed7-11e9-81c3-b34a8f4e1554.png)

![image](https://user-images.githubusercontent.com/5210208/63023222-30f32d00-bed7-11e9-8218-51215067f7f5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yutian1224** [comment]
现在我的做法是资产授权规则重新开关一下就好了

**Comment by zhb127** [comment]
> 现在我的做法是资产授权规则重新开关一下就好了

非常感谢，我试一下看看

**Comment by zhb127** [comment]
> 现在我的做法是资产授权规则重新开关一下就好了

非感谢，确实可以了。
