### ISSUE TITLE
创建的用户删除后再次创建相同用户，则该用户会有所有资产的权限

### ISSUE THREAD

**Issue by SUMPaul** [jumpserver/jumpserver#3130]
##### 使用版本
jumpserver-1.5.2

##### 问题复现步骤
1. 创建一个新用户
2. 分配资产
3. 删除用户
4. 重新创建
5. 分配资产

![图片](https://user-images.githubusercontent.com/15967174/63117689-e0f79180-bfce-11e9-8507-4fd347787152.png)

创建不同的用户，资产权限没配置的情况下也会有全部权限

![图片](https://user-images.githubusercontent.com/15967174/63118683-efdf4380-bfd0-11e9-981b-79cadc6fee33.png)

更换用户组后就没有资产权限了
![图片](https://user-images.githubusercontent.com/15967174/63118943-89a6f080-bfd1-11e9-9277-e1aeac20e68a.png)

**Comment by jym503558564** [comment]
检查一下授权规则，授权的用户组。新创建的用户是否在该授权的用户组里

**Comment by wojiushixiaobai** [comment]
@SUMPaul 尚未复现，请到demo验证下
