### ISSUE TITLE
Jumpserver使用域名访问 , 时常能连接上 ,时常连接不上 但是使用域名加端口就没有这个问题

### ISSUE THREAD

**Issue by Crushlinuxstart** [jumpserver/jumpserver#3135]
[简述你的问题]
Jumpserver使用域名访问是 时常能连接上 时常连接不上 但是使用域名加端口就没有这个问题
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
docker部署 jumpserver/jms_all:latest
##### 问题复现步骤

问题截图:
你好:
     我的第一张图使用域名访问的时候没有加载出来有时候也能加载出来  第二张是加上端口号 第三张是我nginx配置的 第四张 docker端口
![1566011945(1)](https://user-images.githubusercontent.com/49360339/63206096-d62d2180-c0e0-11e9-9e98-e17326387343.jpg)
![1566012035(1)](https://user-images.githubusercontent.com/49360339/63206109-0b397400-c0e1-11e9-957d-bce3bc641413.jpg)
![image](https://user-images.githubusercontent.com/49360339/63206142-83a03500-c0e1-11e9-8488-ebf20f112e7e.png)
![image](https://user-images.githubusercontent.com/49360339/63206147-9286e780-c0e1-11e9-827b-9748264316f6.png)

[注:] 完成后请关闭 issue

**Comment by Crushlinuxstart** [comment]
我怀疑是Nginx配置有关系但是具体是哪里原因没有找到

**Comment by wojiushixiaobai** [comment]
@Crushlinuxstart [FAQ文档](https://docs.jumpserver.org/zh/docs/faq.html) 第6条

# 具体表现为在luna页面一会可以连接资产, 一会就不行, 需要多次刷新页面
# 如果从开发者工具里面看, 可以看到部分不正常的 502 socket.io
# 此问题一般是由最前端一层的nginx反向代理造成的, 需要在每层的代理上添加(注意是每层)
$ vi /etc/nginx/conf.d/jumpserver.conf  # 配置文件所在目录, 自行修改

...  # 省略

location /socket.io/ {
        proxy_pass http://你后端的服务器url地址/socket.io/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;  # 不记录到 log
}

location /guacamole/ {
        proxy_pass       http://你后端的服务器url地址/guacamole/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;  # 不记录到 log
}
...
