### ISSUE TITLE
1.5.2版本浏览器关闭，再次打开浏览器不用输入账号密码直接登录

### ISSUE THREAD

**Issue by xinyang-yin** [jumpserver/jumpserver#3137]
[简述你的问题]
1.5.2版本浏览器关闭后，再次打开浏览器不用认证，直接进入。
配置文件参数设置成下面这样也没效果
SESSION_EXPIRE_AT_BROWSER_CLOSE:  true

**Comment by ryswork1993** [comment]
改了参数，重启服务吗，我的1.5.2正常

**Comment by wojiushixiaobai** [comment]
@xinyang-yin 更新下代码，最新分支已经修复
