### ISSUE TITLE
可不可以像securecrt那样跑logon script？

### ISSUE THREAD

**Issue by x0mike0x** [jumpserver/jumpserver#3139]
[简述你的问题]
可不可以像securecrt那样跑Logon Actions？

##### 使用版本
1.4.8-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52434617/63236191-61d4b880-c26f-11e9-806f-4af4003585ff.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@x0mike0x 可以

**Comment by x0mike0x** [comment]
要怎么弄啊？求

**Comment by wojiushixiaobai** [comment]
@x0mike0x 类似的需求建议自行搜索或者咨询xshell官方相关人员

Expect         send
Opt>            192.168.1.10
