### ISSUE TITLE
connect.py 问题，之前正常，用户登录后输入p直接异常退出

### ISSUE THREAD

**Issue by gxp2008** [jumpserver/jumpserver#314]
connect.py 问题，之前正常，用户登录后输入p直接异常退出
Traceback (most recent call last):
  File "/usr/local/src/jumpserver/connect.py", line 813, in <module>
    main()
  File "/usr/local/src/jumpserver/connect.py", line 778, in main
    nav.print_search_result()
  File "/usr/local/src/jumpserver/connect.py", line 526, in print_search_result
    self.truncate_str(asset.hostname), str(role).replace("'", ''), asset.comment)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 47-51: ordinal not in range(128)
Connection to 129.10.8.5 closed.

后面使用了docker，发现该问题没有出现。问题是同样的配置文件，没啥变化

**Comment by ibuler** [comment]
数据库改为utf8

**Comment by jiaxiangkong** [comment]
mysql -e "create database jumpserver charset='utf8';"
mysql -e "grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by '5Lov@wife';"
mysql -e "flush privileges;"
mysql -e "show databases;"

**Comment by station19** [comment]
my.cnf修改
[mysqld]
character_set_server=utf8
default-character-set=utf8

[client]
default-character-set=utf8

重启机器
