### ISSUE TITLE
升级到1.5.2以后，Windows的服务器连接不了了

### ISSUE THREAD

**Issue by lvshuishangshang** [jumpserver/jumpserver#3143]
升级到最新版本之后，guacamole一直注册不了，然后导致Windows服务器无法连接了，从guacamole 的docker日志里查看 显示的是 “[Thread-6] INFO o.a.g.a.j.r.JumpserverRegisterService 210 - 等待心跳，AccessKey验证未通过”，我启动docker的时候的那个token确实是和jumpserver的配置文件里面的一样的

jumpserver 版本
1.5.2-2
![image](https://user-images.githubusercontent.com/24688300/63324280-4e524c00-c35a-11e9-9015-b94b82d08f20.png)
![image](https://user-images.githubusercontent.com/24688300/63324304-5c07d180-c35a-11e9-9c94-b1ce8da403f6.png)
![image](https://user-images.githubusercontent.com/24688300/63324324-63c77600-c35a-11e9-9c6f-0675ca10735e.png)

**Comment by wojiushixiaobai** [comment]
@lvshuishangshang 参考此文档解决下[RDP 协议资产连接说明](https://docs.jumpserver.org/zh/master/faq_rdp.html)

**Comment by lvshuishangshang** [comment]
试了的，一直都是这个样子，不变化

**Comment by wojiushixiaobai** [comment]
@lvshuishangshang 根据文档说明，删掉后重新注册，如果重新注册也是这样，表示token不正确
