### ISSUE TITLE
添加完主机后，提示无权限

### ISSUE THREAD

**Issue by zzyaming** [jumpserver/jumpserver#3145]
[简述你的问题]
近期做了一次版本升级，从1.4.9升级到了1.5.2-2，各种小问题。
1）之前已经对a用户针对A节点做过授权，现在新增一台机器B到A节点下，按理说它应该自动刷新a用户的各种权限、密钥等到B机器。但实际上，什么都没有做，直接登录肯定会提示认证失败，这个我忍了，手动去推送一下就行。 但是无法忍受的是，推送完之后，还提示无权限。只能重新把A节点在a用户名下去掉，保存，然后再添加才可以。 
2）找到某系统用户，然后再它名下想推送某台机器时，使用右上角的搜索功能无效，并不能搜到任何机器。 

##### 使用版本
Version 1.5.2-2 GPLv2.

##### 问题复现步骤
1. 对a用户针对A节点授权
2. 新增机器B，划分到A节点下
3. 登录B机器，提示无权限

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/53419379/63423632-51733800-c43f-11e9-86ba-8e60536d1028.png)

![image](https://user-images.githubusercontent.com/53419379/63423776-99925a80-c43f-11e9-8376-0c2ee341d888.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by muchh** [comment]
我也遇到了这个问题，有解决办法了吗？

**Comment by lilei7542** [comment]
同样问题
2019-10-31 15:33:51 任务开始: 测试资产可连接性: 10.20.0.55(10.20.0.55)
PLAY [测试资产可连接性: 10.20.0.55(10.20.0.55)] ****************************************
TASK [ping] ********************************************************************
fatal: [10.20.0.55]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING:REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the ECDSA key sent by the remote host is\nSHA256:dB0LB1fFdGzoOopXYVf9ggCijHAv/LU1TS6RDGbrSSU.\r\nPlease contact your system administrator.\r\nAdd correct host key in /root/.ssh/known_hosts to get rid of this message.\r\nOffending ECDSA key in /root/.ssh/known_hosts:1\r\nPassword authentication is disabled to avoid man-in-the-middle attacks.\r\nKeyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

**Comment by SimpleTea** [comment]
> [简述你的问题]
> 近期做了一次版本升级，从1.4.9升级到了1.5.2-2，各种小问题。
> 1）之前已经对a用户针对A节点做过授权，现在新增一台机器B到A节点下，按理说它应该自动刷新a用户的各种权限、密钥等到B机器。但实际上，什么都没有做，直接登录肯定会提示认证失败，这个我忍了，手动去推送一下就行。 但是无法忍受的是，推送完之后，还提示无权限。只能重新把A节点在a用户名下去掉，保存，然后再添加才可以。
> 2）找到某系统用户，然后再它名下想推送某台机器时，使用右上角的搜索功能无效，并不能搜到任何机器。
> 
> ##### 使用版本
> Version 1.5.2-2 GPLv2.
> 
> ##### 问题复现步骤
> 1. 对a用户针对A节点授权
> 2. 新增机器B，划分到A节点下
> 3. 登录B机器，提示无权限
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> ![image](https://user-images.githubusercontent.com/53419379/63423632-51733800-c43f-11e9-86ba-8e60536d1028.png)
> 
> ![image](https://user-images.githubusercontent.com/53419379/63423776-99925a80-c43f-11e9-8376-0c2ee341d888.png)
> 
> ##### 其他
> [注:] 完成后请关闭 issue

进入资产授权，重新提交一下，就行了。一般是节点授权会有这种情况。
