### ISSUE TITLE
登录操作机，连接资产提示：Connect asset <资源标签名> error: EOF

### ISSUE THREAD

**Issue by jingkonglanxing** [jumpserver/jumpserver#3147]
[简述你的问题]
登录操作机，连接资产提示：
Connect asset <资源标签名> error: EOF

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
koko 1.5.2
jumpserver 1.5.2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/6315997/63481996-c1c69b80-c4c9-11e9-990c-539e8b0dd038.png)

##### 其他
尝试解决：
随机出现这种错误, 目前尝试了以下方式都不行
1. 重新创建权限
2. 重新激活用户
3. 重新激活权限
4. 重新激活资源
5. 重新创建资源
6. 重新推送系统用户

唯一尝试了可行的方法:
1. 删除用户重新创建用户关联权限

[注:] 完成后请关闭 issue

**Comment by huangpeng0817** [comment]
我同事今天用也是出现这样的问题。在web页面使用终端可以连接，使用ssh工具就这样不行。其他人都正常的。就同事账号这样。我自己用同事账号也不行。最后按照这个删除用户的做法，才好。。

**Comment by guozilong110** [comment]
我也遇到了这样的问题.

**Comment by huangpeng0817** [comment]
> 我也遇到了这样的问题.重启了jms_koko docker恢复了

这个问题是用户连接超过126个导致。koko配置文件中
# 是否复用和用户后端资产已建立的连接(用户不会复用其他用户的连接)
# REUSE_CONNECTION: true
改成false，再观察下。更新1.5.3

**Comment by RayLTL** [comment]
我的也是，上午还能用，下午就不能用了，新建一个账号可以解决该问题
