### ISSUE TITLE
非root用户（sudu NOPASSWD ALL）无法更新硬件信息

### ISSUE THREAD

**Issue by baoweizhang** [jumpserver/jumpserver#3150]
[简述你的问题]
创建sudo用户并配置sudoers中NOPASSWD参数，作为jumpserver的管理用户。测试节点连接性和更新硬件信息报错。

##### 使用版本
jumpserver 1.5.2
coco 1.5.2

##### 问题复现步骤
1. 创建sudo用户并配置NOPASSWD参数；
2. 配置该用户为资产管理用户；
3. 测试资产连接性、更新资产硬件信息报错。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/15828887/63506191-9b275580-c507-11e9-96b4-c1d073d2c6e4.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@baoweizhang NOPASSWD: ALL
