### ISSUE TITLE
weib终端中，luna不显示分组，多个组的资产都在一个未分组中

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#3152]
![image](https://user-images.githubusercontent.com/46477158/63577241-8fe43080-c5c0-11e9-8738-8daa199c5753.png)
在资产中，有多个分组。分配权限后，页面登陆，终端web，luna上不会分组。全部都在一个未分组中

**Comment by jym503558564** [comment]
这个在config.yml中通过配置`PERM_SINGLE_ASSET_TO_UNGROUP_NODE`，可自行设置

**Comment by huangpeng0817** [comment]
> 这个在config.yml中通过配置`PERM_SINGLE_ASSET_TO_UNGROUP_NODE`，可自行设置

这个是在哪个程序的config.yml配置中配置。找了一圈没有看到这个参数

**Comment by jym503558564** [comment]
@huangpeng0817 版本？
![image](https://user-images.githubusercontent.com/40739051/65477585-54879b00-deb9-11e9-8ee9-e128c9311723.png)

**Comment by huangpeng0817** [comment]
> @huangpeng0817 版本？
> ![image](https://user-images.githubusercontent.com/40739051/65477585-54879b00-deb9-11e9-8ee9-e128c9311723.png)

1.5.2

**Comment by jym503558564** [comment]
直接取消注释.   PERM_SINGLE_ASSET_TO_UNGROUP_NODE:  false
