### ISSUE TITLE
如何对api进行二次开发

### ISSUE THREAD

**Issue by 15029836736** [jumpserver/jumpserver#3156]
[简述你的问题]
因为某些接口的返回值不符合需求(get接口获取了中文name，但是patch接口更新时候需要id，还需要转换，所以希望get直接返回id，比如/api/perms/v1/asset-permissions/)
故想对jumpserver的api进行二次开发，但是找了一下好像没找到对应的api代码，请问在哪呢？

**Comment by wojiushixiaobai** [comment]
@15029836736 get的接口应该包含了id信息才对。是个json表单，你确认下

**Comment by 15029836736** [comment]
接口/api/perms/v1/asset-permissions/ 返回
"nodes": ["Default / SU", "Default / FD"],
"users": ["\u738b\u82e5\u611a(testwang)"],
"system_users": ["test(test)"]

这些信息信息希望返回id，而不是name

**Comment by wojiushixiaobai** [comment]
@15029836736 返回的表单里面没有缺失的信息呀，你是不是版本不对。
[
  {
    "id": "7e95231f-c22e-4e30-867f-cd99393f2cab",
    "org_id": "",
    "org_name": "DEFAULT",
    "actions": [
      "all",
      "connect",
      "upload_file",
      "download_file",
      "updownload"
    ],
    "name": "1",
    "is_active": true,
    "date_start": "2019-08-27 09:56:00 +0800",
    "date_expired": "2089-08-09 09:56:00 +0800",
    "comment": "",
    "users": [
      "e639cba5-4f9f-4b32-8e94-51a50023997e"
    ],
    "user_groups": [],
    "assets": [
      "1e994909-7e53-482a-a9dd-8ddf00aef2b6"
    ],
    "nodes": [],
    "system_users": [
      "54107c8f-4280-426b-8414-97034c316b92"
    ]
  }
]

**Comment by 15029836736** [comment]
有可能是版本问题，那么请问大神，如果我想自行开发一个api，需要怎么做呢，因为我没有发现对应的openapi代码，只看见了内置的接口

**Comment by sjsfyzs** [comment]
我也遇到了这个问题，请问那个版本中修复了这个问题，我的版本是Version 1.4.10-2 GPLv2
@wojiushixiaobai 

{u'actions': [u'\u5168\u90e8'],
 u'assets': [],
 u'comment': u'ops\u6388\u6743\u89c4\u5219: test11 id: 16',
 u'created_by': u'admin_for_api',
 u'date_created': u'2019-11-07 22:01:09 +0800',
 u'date_expired': u'2089-09-05 12:01:00 +0800',
 u'date_start': u'2019-09-05 12:01:00 +0800',
 u'id': u'0ca63514-0167-11ea-bec2-38f9d3627426',
 u'is_active': True,
 u'is_expired': False,
 u'is_valid': True,
 u'name': u'OPS_test11',
 u'nodes': [u'Default / boss_rocketmq-nameserver', u'Default / boss_wap'],
 u'org_id': u'',
 u'system_users': [u'work(work)'],
 u'user_groups': [u'ops_test10'],
 u'users': [u'admin_for_api(admin_for_api)']}

**Comment by wojiushixiaobai** [comment]
@15029836736 项目里面有api的代码，你仔细看下
@sjsfyzs 目前最新版本是1.5.4，可以尝试更新，注意备份
