### ISSUE TITLE
`audits_userloginlog`登录ip存入的是jumpsever主机的内网ip.

### ISSUE THREAD

**Issue by oldthreefeng** [jumpserver/jumpserver#3165]
[简述你的问题]
这边web端显示的登录ip显示是jumpsever主机的内网ip.从数据库里面查阅也是一样的.很纳闷

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. [步骤1]
web端查看登录日志,查看的ip都是jumpserver的本机的ip,
使用的服务器是ucloud云服务器.
```
# cat /etc/redhat-release
CentOS release 6.5 (Final)
```

2. [步骤2]
通过web端http://ip/;登录jumpserver,显示的ip正常.

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/38313565/63744850-28d1bf00-c8d3-11e9-9ae2-6cf94c7c0e64.png)

##### 其他

找了半天源码 ip = models.GenericIPAddressField(verbose_name=_('Login ip')) ;
在这里获取login_ip的,但是不知道怎么弄~便提了这个issue;
我在想,通过ssh连接jumpserver,获取的ip是通过什么方式获取的.如果这个解决了,就ok了
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@oldthreefeng tcp获取真实ip，1.5.2已经初步支持，等待进一步优化
server {
        listen 2220;
        proxy_pass 127.0.0.1:2222;
        proxy_protocol on;
        proxy_connect_timeout 1s;  # detect failure quickly
    }

**Comment by oldthreefeng** [comment]
ssh获取的真实ip却没有拿到,这是为什么呢~
存入数据库的ip是jumpserver本机的内网ip,很想解决这个问题,
因为想看看登录失败的ip,这样可以利用防火墙阻挡他们,

**Comment by bufer** [comment]
@wojiushixiaobai 1.5.2-2现在通过SSH登录IP显示正常，但登录状态不对，全部显示为失败
