### ISSUE TITLE
celery定时任务停止

### ISSUE THREAD

**Issue by purevita** [jumpserver/jumpserver#3168]
[简述你的问题]
celery 的定时任务总会在UTC时间20：00停止到4：00

##### 使用版本
1.5.0 and 极速安装 Version 1.5.2-2 

##### 问题复现步骤
1. [步骤1] celery 的定时任务总会在UTC时间20：00停止到4：00
2. [步骤2] restart jms 或重开机皆无效，等到UTC 4：00任务又会开始

##### 具体表现[截图可能会更好些,最好能截全]
Version 1.5.2-2 
在20:00 ~ 4:00定时任务都没作动
![螢幕快照 2019-08-29 下午4 54 45](https://user-images.githubusercontent.com/17267802/63926097-d97bc200-ca7d-11e9-9242-01605cc26d46.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by int32bit** [comment]
@purevita 请问如何打开celery页面？

**Comment by purevita** [comment]
@int32bit 我是装[Flower - Celery](https://flower.readthedocs.io/en/latest/)来看的

**Comment by zgcanfly** [comment]
我遇到过同样的问题 并且已经解决和反馈给jumpserver开发人员了
这个bug是celery自己的bug
解决办法:
pip install celery==4.2.0
pip install kombu==4.2.0 
然后重启jumpserver 即可!

**Comment by purevita** [comment]
昨日将 celery 升到4.2 似乎还是会停，我会再尝试看看
有试著将django时区设定UTC时间后重启 celery period task 又会跑了

**Comment by purevita** [comment]
pip install celery==4.2.0
pip install kombu==4.2.0
app/junpserver/settings.py  加一行 CELERY_TIMEZONE = 'Asia/Shanghai'
重启jumpserver
解决此问题
