### ISSUE TITLE
添加S3存储报错

### ISSUE THREAD

**Issue by spark8103** [jumpserver/jumpserver#3174]
[简述你的问题]
在系统设置中添加了S3存储，在会话管理的终端管理中更新coco和guacamole的录像存储为s3存储时，接口返回400错误
{"error":"service account registration disabled"}

##### 使用版本
jumpserver 1.5.2

##### 问题复现步骤
在系统设置中添加一个S3的存储类型
在会话管理的终端管理中配置录像存储为S3存储

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@spark8103 更新到最新版本试试
