### ISSUE TITLE
连接web终端时报错：No asset id or system user id found, exit

### ISSUE THREAD

**Issue by dfdf10086** [jumpserver/jumpserver#3179]
[简述你的问题]
测试可连接性时能通，在进行web终端连接是报错：No asset id or system user id found, exit

##### 问题复现步骤
1. [步骤1] 略
2. [步骤2] 略

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/9738922/64002285-46559180-cb3c-11e9-90f8-f8d03f359a5f.png)

![image](https://user-images.githubusercontent.com/9738922/64001878-620c6800-cb3b-11e9-8778-9cf8daf43b0e.png)

[注:] 完成后请关闭 issue

**Comment by dfdf10086** [comment]
我是用docker安装的koko，刚删除了data/keys/.access_key，重启koko,终端注册成功了！
但是又报如下错误了：
![image](https://user-images.githubusercontent.com/9738922/64005892-c8958400-cb43-11e9-8528-3f0fbeffeebf.png)
我看有人说是阿里云主机的事情，但是我之前的也是阿里云就么有问题！

**Comment by LeeEirc** [comment]
@dfdf10086 复查一下授权和asset关联的系统用户的密码是否正确。

**Comment by Eva-Mai** [comment]
> [简述你的问题]
> 测试可连接性时能通，在进行web终端连接是报错：No asset id or system user id found, exit
> 
> ##### 使用版本：Version 1.5.2-2 GPLv2
> ##### 问题复现步骤
> 1. [步骤1] 略
> 2. [步骤2] 略
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> ![image](https://user-images.githubusercontent.com/9738922/64002285-46559180-cb3c-11e9-90f8-f8d03f359a5f.png)
> 
> ![image](https://user-images.githubusercontent.com/9738922/64001878-620c6800-cb3b-11e9-8778-9cf8daf43b0e.png)
> 
> [注:] 完成后请关闭 issue

请问解决了吗？现在我也出现同样的问题

**Comment by xbtian** [comment]
同样遇到“No asset id or system user id found, exit”
在koko下有个/data/keys]# cat .access_key  将这个文件删除或者mv走 重启一下koko
（kill kokopid; ./koko -d） 
问题解决
