### ISSUE TITLE
[bug]权限管理-资产授权-授权规则-不能保留上次的文件传输选项

### ISSUE THREAD

**Issue by supershrek** [jumpserver/jumpserver#3180]
[简述你的问题]
[bug]权限管理-资产授权-授权规则-不能保留上次的文件传输选项

第一次吧上传下载等权限取消了，第二次打开又被勾选了

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

Version 1.5.2-2 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/4003378/64002554-e90e1000-cb3c-11e9-87fd-04678dfe2222.png)

![image](https://user-images.githubusercontent.com/4003378/64002509-ced43200-cb3c-11e9-903c-cc276fdd80da.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@supershrek 已验证存在此问题，感谢反馈，我们会尽快修复
