### ISSUE TITLE
无法对新增机器的系统用户推送，只能全部推送

### ISSUE THREAD

**Issue by zhaileilei123** [jumpserver/jumpserver#3182]
无法对新增机器的系统用户批量推送，只能全部推送或者一个一个点推送。

##### 使用版本
1.5.2

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
如果系统用户开启自动推送，新建资产成功，同时创建授权规则将系统用户和资产进行关联后，会自动对新创建的资产进行推送的。

目前还不支持勾选资产进行批量推送。
