### ISSUE TITLE
jumpserver容器內部啟動./jms start 報錯，缺少psycopg2模塊

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#3183]
[简述你的问题]
啟動jumpserver容器時，報以下錯誤：django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'

##### 使用版本
Version 1.5.2-2 GPLv2

##### 问题复现步骤
1. [步骤1]
進入容器內部，使用./jms start命令啟動服務，觀察打印日誌

##### 具体表现[截图可能会更好些,最好能截全]
上傳不了圖片

##### 其他
解決方法：
安裝psycopg2-binary模塊
命令：pip install psycopg2-binary
建議官方將該psycopg2-binary模塊加入到/opt/jumpserver/requirements/requirements.txt文件中
[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请问你们使用的是 PostgreSQL Database 数据库吗？
