### ISSUE TITLE
无法批量执行命令

### ISSUE THREAD

**Issue by hjun881** [jumpserver/jumpserver#3184]
[简述你的问题]
批量执行命令报错. 资产管理用户和系统用户授权没有问题因为可以正常更新到资产硬件系统并且使用系统用户可以在web 终端上正常登陆资产.

##### 使用版本
1.5.2

##### 问题复现步骤
1. 在用户界面点击命令执行
2. 选择资产
3. 选择系统用户
4. 输入命令
5. 点击执行

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/18508499/64078885-19a7a280-cd13-11e9-94db-7e5b38925ca1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
![image](https://user-images.githubusercontent.com/32935519/67196292-197f7580-f42d-11e9-91e5-66330c330143.png)
调换一下 第2、3步操作顺序（先选择系统用户，再选择资产）
