### ISSUE TITLE
系统用户资产单独推送出现空白页，

### ISSUE THREAD

**Issue by zhaileilei123** [jumpserver/jumpserver#3186]
[简述你的问题]
系统用户资产单独推送出现空白页，

##### 使用版本
1.5.2

##### 问题复现步骤
勾选后后面动作的按钮出现空白窗口，
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/38358012/64103973-df3b1580-cda5-11e9-84a8-8434f45a7e66.png)

##### 其他
剩下的疑虑是前面的选择框有什么用？又不能批量对资产进行管理

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhaileilei123 23333，不勾选就行了，这个后面会处理掉。感谢反馈

**Comment by jym503558564** [comment]
1.5.3版本已修复，请关注新版本的发布情况。感谢反馈～
