### ISSUE TITLE
授权管理选择某个节点授权给某个用户组，在web终端连接时会报“Authentication failed”

### ISSUE THREAD

**Issue by MacroJG** [jumpserver/jumpserver#3188]
授权管理选择某个节点授权给某个用户组，在web终端连接时会报“Authentication failed”

Version 1.5.2-2 GPLv2.

**Comment by wojiushixiaobai** [comment]
@MacroJG 在新建授权出下拉，选择更新授权
此问题已经记录，下个版本解决，感谢反馈
