### ISSUE TITLE
1.5.0升级到1.5.2后，部分用户上传文件报错'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bufer** [jumpserver/jumpserver#3191]
[简述你的问题]
1.5.0升级到1.5.2后，部分用户在上传文件过程中报错'NoneType' object is not subscriptable，导致文件上传不成功

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. [步骤1]

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/6928347/64312703-ae442600-cfdb-11e9-8887-f753edd12bfd.png)

##### 其他
使用有管理员权限的用户上传没问题，检查过权限设置都有文件上传权限，在升级之前没有问题

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@bufer 升级一下coco，可使用v52分支。

**Comment by xihefeng** [comment]
> @bufer 升级一下coco，可使用v52分支。

请问下，现在docker是不是也没有跟新啊
