### ISSUE TITLE
想问问大佬，RDP录屏大致实现流程是什么？

### ISSUE THREAD

**Issue by H4ckForJob** [jumpserver/jumpserver#3193]
[简述你的问题]
想问问大佬，RDP录屏大致实现流程是什么？如果直接通过rdp协议连接云主机，不经过jumpserver能录屏吗？

##### 使用版本
1.4.8

**Comment by wojiushixiaobai** [comment]
@H4ckForJob 可以用其他插件，其实就是基于rdp协议的会话录制，网上有相应的方案，可以自行搜索下。

**Comment by H4ckForJob** [comment]
> @H4ckForJob 可以用其他插件，其实就是基于rdp协议的会话录制，网上有相应的方案，可以自行搜索下。

thx，赶deadline，打算采取ffmpeg录制的方法弄了
