### ISSUE TITLE
安装依赖的时候在python-gssapi一直报错，

### ISSUE THREAD

**Issue by tlya** [jumpserver/jumpserver#3194]
安装依赖的时候在python-gssapi一直报错

##### 使用版本
用的是1.4.8的版本，装了python3.6做为虚拟环境,使用了阿里云的源

##### 问题复现步骤
1.pip install --upgrade setuptools pip
2.pip install -r requirements.txt

##### 具体表现[截图可能会更好些,最好能截全]
Collecting python-gssapi==0.6.4
  Downloading http://mirrors.aliyun.com/pypi/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-is8_30r3/python-gssapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-is8_30r3/python-gssapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-is8_30r3/python-gssapi/
    Complete output (152 lines):
    running egg_info
    creating pip-egg-info/python_gssapi.egg-info
    writing pip-egg-info/python_gssapi.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/python_gssapi.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/python_gssapi.egg-info/requires.txt
    writing top-level names to pip-egg-info/python_gssapi.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/python_gssapi.egg-info/SOURCES.txt'
    gssapi/bindings/__pycache__/_cffi__xa7d82a3cx47db505c.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xb6db7234xa2d82a13.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>

##### 其他

[注:] 完成后请关闭 issue

**Comment by L00J** [comment]
是的一直装不起来，产品很浮躁发布出来不测试吗？以前还可以一键安装，这么知名的产品真不应该！

**Comment by jym503558564** [comment]
@tlya  @L00J 手动下载包 python-gssapi==0.6.4，本地安装下，看看报什么错，截图。

**Comment by wojiushixiaobai** [comment]
@tlya 关键报错  Python.h: No such file or directory
$ yum update
$ yum install python36-devel

然后重新执行pip install 命令
