### ISSUE TITLE
关于网域，可否支持windows 机器

### ISSUE THREAD

**Issue by DreamDZhu** [jumpserver/jumpserver#3195]
[简述你的问题]

请问网域可以配置windows网域吗，许多公司部署的项目都必须要windows 用IE的VPN ，不像OpenVpn 可以用linux

##### 使用版本
1.5.2

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@DreamDZhu Windows支持使用ssh网关跳转，因为部署windows网关有点复杂，当前版本去掉了，后续会看需求是否重新添加

**Comment by DreamDZhu** [comment]
感谢回复，我配置的win10 的 ssh-keygen 。我可以使用JumpServer 的那台服务器免密直接登陆win10 ,可是JumpServer 网页配置网关却连接不上。是我操作有问题吗

**Comment by DreamDZhu** [comment]
@wojiushixiaobai  经过各种系统测试后。发现jumpserver 可以通过windows 的网关跳板，检测到内网服务器上线，也可以读取到内网服务器的配置，说明是登陆成功的，但是从web 终端就使用提示登陆失败。。。

**Comment by wojiushixiaobai** [comment]
@DreamDZhu 失败提示什么，在系统用户那里测试连接看看

**Comment by DreamDZhu** [comment]
@wojiushixiaobai  Connect GATEWAY faild timed out  。 但是网域网关测试是连接成功，系统用户测试也是连接Ok, 用任务指定执行命令也是成功的。唯独web连接终端始终连不上。
