### ISSUE TITLE
ldap用户登入自动设置分组与授权

### ISSUE THREAD

**Issue by ZandaGo** [jumpserver/jumpserver#3197]
[简述你的问题]
请问，jumpserver接入ldap后，是否可以实现ldap中的用户自动分配到jumpserver中提前设置好的指定用户组中 （现在是需要手动导入ldap中的用户，并手动设置相关用户的权限，如在哪个分组中，系统用户要手动配置，服务器授权要手动授权）

如：
ldap中有 用户 testuser2
jumpserver 中有分组 users

testuser1 登录后默认在users分组中，且自动创建了 testuser1 的系统用户，并分配授权 users 组中的用户可以登录指定组中的服务器

##### 使用版本
1.5.2
##### 具体表现[截图可能会更好些,最好能截全]
ldap配置：
<img width="324" alt="WX20190907-095009@2x" src="https://user-images.githubusercontent.com/19302901/64468253-ec188a00-d154-11e9-8736-5f17745d6c4d.png">

jumpserver配置：
<img width="536" alt="WX20190907-095216@2x" src="https://user-images.githubusercontent.com/19302901/64468269-3dc11480-d155-11e9-8630-c8cf1d79a338.png">

使用 ldap 登录 jumpserver
<img width="447" alt="WX20190907-095343@2x" src="https://user-images.githubusercontent.com/19302901/64468285-74972a80-d155-11e9-8d2a-2f3d790ca571.png">

**默认没有任何资产可以登录使用，需要使用管理员账户再对这个testuser2的用户进行授权等操作**

<img width="1028" alt="WX20190907-095544@2x" src="https://user-images.githubusercontent.com/19302901/64468296-af00c780-d155-11e9-8222-61bae42bacd1.png">

**需要每个用户再做授权才可以让 testuser2 正常使用**

<img width="739" alt="WX20190907-100059@2x" src="https://user-images.githubusercontent.com/19302901/64468359-83321180-d156-11e9-8c3a-c3bd106997ac.png">

**Comment by ZandaGo** [comment]
这个事情有回复吗？

**Comment by BaiJiangJie** [comment]
目前 LDAP 用户的同步，还不支持同步用户组。
