### ISSUE TITLE
请问现在支持使用vscode的remote ssh连接管理的机器吗？

### ISSUE THREAD

**Issue by YuiTH** [jumpserver/jumpserver#3198]
考虑使用jumpserver管理多云结点，做内外网隔离。但是在观察主页的所谓“支持ssh登陆”的视频后，发现登陆上去还是要手动进行一些输入操作，如果想要使用例如pycharm或者vscode这类软件进行远程开发，则至少要允许通过ProxyCommand来连接远程机器。请问当前jumpserver的版本支持这样的连接方式吗？

**Comment by wojiushixiaobai** [comment]
@YuiTH 不支持

**Comment by xgdgsc** [comment]
支持这个还是会方便很多的

**Comment by pan3793** [comment]
+1 request this feature

**Comment by huihuiustc** [comment]
+1 request this feature

**Comment by LeeEirc** [comment]
已经支持使用 VSCode 的 remote ssh 连接

**Comment by ery** [comment]
> 已经支持使用 VSCode 的 remote ssh 连接

请指教一下，怎么配置？

**Comment by oliveagle** [comment]
@ery 我看新版是支持了这个功能.   

https://blog.fit2cloud.com/?p=2267
