### ISSUE TITLE
windows 上传文件中断故障

### ISSUE THREAD

**Issue by play0591** [jumpserver/jumpserver#3199]
[简述你的问题]
jumpserver  上传5G 文件，传送一半左右，失败，是因为超时，还是文件大小限制，请问如何解决；

##### 使用版本
1.5.2
##### 问题复现步骤
1. 登陆jumpserver，连接windows 2008服务器
2. 拖拽文件到服务器桌面，显示上传中，传一半后失败

##### 具体表现[截图可能会更好些,最好能截全]

![window上传文件失败](https://user-images.githubusercontent.com/55069937/64498580-b2c45380-d2e7-11e9-8007-d0b147b44497.PNG)

##### 其他

[注:] 完成后请关闭 issue

**Comment by play0591** [comment]
为什么没人答复，跟进

**Comment by BaiJiangJie** [comment]
查看下 Nginx 配置文件的大小限制。
