### ISSUE TITLE
单台服务器在线连接最多20个

### ISSUE THREAD

**Issue by junly917** [jumpserver/jumpserver#3201]
[简述你的问题]
从1.4.10升级到最新版本（1.5.2）后进行压力测试，发现单台服务器上的单个账号， 在线连接数小于20个(最多情况下，一般只有13-15个左右)，再选择账号就会直接断开了请求，如果断开一个在线连接后，新的连接可以正常登录；

查看日志发现coco己经接受 连接，并且进入了交互模式，但是后台服务器并没有接受到登录请求；
是不是coco的进行限制连接数？ 如何调整这个连接数？

##### 使用版本
1.4.10升级到最新后

##### 问题复现步骤
jumpserver配置了多个账号，使用单个账号只能10几个在线连接，换其他账号又是10几个连接；

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@junly917 有个连接复用的功能，关闭试试。在coco/config.yml里面

**Comment by junly917** [comment]
己经启动了配置，但是好像还是一样的效果。没有啥用
