### ISSUE TITLE
网域机器上的ssh连接关闭会话后进程未释放

### ISSUE THREAD

**Issue by linguohu** [jumpserver/jumpserver#3202]
[简述你的问题]
1.5.2版本关闭使用网域连接目标机器的luna会话后,网域机器上的ssh连接进程未释放，用久后很多ssh连接进程

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. [步骤1]
luna连接有使用网域的机器目标机器
2. [步骤2]
网域机器上查看ssh进程
netstat -apn|grep "网域IP"
3.[步骤3]
关闭luna上的会话后查看网域机器上查看ssh进程依然存在
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/12726197/64579420-6e06ee00-d3b5-11e9-8585-4ea86588ec6c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liufeng6582** [comment]
同问题，sshd进程连接后未释放。连接多少次就会有多少个进程

**Comment by LeeEirc** [comment]
@liufeng6582 @linguohu 在最新的koko里面，做了优化，应该解决了资源释放问题。
