### ISSUE TITLE
用户名不能包含特殊字符

### ISSUE THREAD

**Issue by Dollyn** [jumpserver/jumpserver#3203]
[简述你的问题]
![image](https://user-images.githubusercontent.com/184413/64580089-b32c1f80-d3b7-11e9-94cd-9673d3a44f00.png)

##### 使用版本
 1.5.2-2 

##### 问题复现步骤
1. [步骤1]
资产管理 > 管理用户
2. [步骤2]
新增或者更新用户
3. [步骤3]
提交

##### 具体表现[截图可能会更好些,最好能截全]
因为这个windows服务器是用域用户登录，必须加上域前缀 sn\， 但jumpserver不支持

**Comment by wojiushixiaobai** [comment]
@Dollyn user@domain.com
