### ISSUE TITLE
登陆失败？？？why？？？？？

### ISSUE THREAD

**Issue by wufuhello** [jumpserver/jumpserver#321]
![image](https://cloud.githubusercontent.com/assets/23399803/20213457/a3d71ec8-a7bd-11e6-8bdf-9e516b23eb72.png)
安装成功！！！
登陆web界面，默认的账号：admin 密码：5Lov@wife
为什么登陆失败？？为什么？？？？求解啊

**Comment by jiaxiangkong** [comment]
我测试没有问题 表示妥妥的可以登录

**Comment by wufuhello** [comment]
谢谢！我已经解决，是浏览器的问题！之前用IE浏览器登录的，后来换成谷歌浏览器就可以了


发自网易邮箱大师
在2016年11月14日 11:25，假想控 写道:

我测试没有问题 表示妥妥的可以登录
