### ISSUE TITLE
一个资产使用一个系统用户，在系统用户列表中却显示两个资产

### ISSUE THREAD

**Issue by rexonegit** [jumpserver/jumpserver#3213]
[简述你的问题]
正常添加管理用户，系统用户，然后添加资产，之后添加授权
会莫名出现 系统用户列表有2个资产

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2]

##### 问题复现步骤
1. [步骤1] 添加管理用户，系统用户，然后添加资产，之后添加授权 centos , ssh 
添加第一个资产正常，
再添加 第2个 centos , ssh  资产的 管理用户系统用户，资产授权后
2. [步骤2] 查看 系统用户显示2个资产
3. [步骤3] 打开 web  切换资产1 和资产2 会提示需要选择用户

##### 其他

[注:] 完成后请关闭 issue
![1](https://user-images.githubusercontent.com/55189028/64692059-c37ef000-d4c6-11e9-8bb1-cd3705dc9e99.png)
![2](https://user-images.githubusercontent.com/55189028/64692060-c4178680-d4c6-11e9-9a7c-65b7ab9e5381.png)
![3](https://user-images.githubusercontent.com/55189028/64692061-c4178680-d4c6-11e9-9257-da92b2867619.png)
![4](https://user-images.githubusercontent.com/55189028/64692063-c4178680-d4c6-11e9-8a38-e2fc72d1f7fc.png)
![5](https://user-images.githubusercontent.com/55189028/64692205-122c8a00-d4c7-11e9-9466-bf8d8f122ed6.png)

**Comment by jym503558564** [comment]
这两个资产是否在同一节点下，您这边授权是否是选择节点授权

**Comment by jym503558564** [comment]
根据您授权规则来显示来决定该资产的系统用户。
- 这边看您的授权规则，选择了节点，也选择了资产。如选择节点，该节点下的资产都会授权同一个系统用户。
- 根据您创建了两个授权规则，这两个授权规则的系统用户是否不一样，两个授权的资产/节点 是否有相同，一个资产如果有多个授权系统用户，那么就会提示您需要选择哪个系统用户登录

**Comment by rexonegit** [comment]
> 根据您授权规则来显示来决定该资产的系统用户。
> 
> * 这边看您的授权规则，选择了节点，也选择了资产。如选择节点，该节点下的资产都会授权同一个系统用户。
> * 根据您创建了两个授权规则，这两个授权规则的系统用户是否不一样，两个授权的资产/节点 是否有相同，一个资产如果有多个授权系统用户，那么就会提示您需要选择哪个系统用户登录


感谢，回复 提示系统用户的问题已经解决。
授权问题 已经理解，但是 **系统用户** 关联的资产我还是不太理解，我在授权中，给 server 1 关联了 系统用户 srvuser-1 并没有做  资产2 与 srvuser-1 的关联，但是系统用户管理界面会显示  srvuser-1用户下有2个资产

**Comment by jym503558564** [comment]
按照您上面的授权规则，查看一下授权规则的授权节点，该节点下面是否包涵资产2
![image](https://user-images.githubusercontent.com/40739051/66822012-f6a91900-ef75-11e9-9fe6-64ba8af92dd6.png)

**Comment by BaiJiangJie** [comment]
@rexonegit 
![image](https://user-images.githubusercontent.com/32935519/67001533-93052400-f10c-11e9-8c0b-6e03e962697d.png)
