### ISSUE TITLE
最新版的安装，启动时数据库初始化直接报错。

### ISSUE THREAD

**Issue by meyer-net** [jumpserver/jumpserver#3215]
##### 问题描述
以前并没发生类似的问题，因为一直在使用。
现在新环境通过 ./jms start all -d 启动直接报错

##### 使用版本
master 分支 1.5.2

##### 问题复现步骤
1. 参考 https://docs.jumpserver.org/zh/docs/step_by_step.html 安装
2. 当执行到 ./jms start all -d 时
3. 出错

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16422453/64698622-cf25e300-d4d5-11e9-95ec-f0db9525498a.png)
![image](https://user-images.githubusercontent.com/16422453/64698667-e2d14980-d4d5-11e9-8b1c-b7f5e60823ed.png)
![image](https://user-images.githubusercontent.com/16422453/64698700-f41a5600-d4d5-11e9-9bb1-7600d62a0e57.png)

##### 其他
系统：centos 7.6

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
数据库也是重新建的吗？

**Comment by meyer-net** [comment]
是的，全部都是全新的。

**Comment by wojiushixiaobai** [comment]
@meyer-net 数据库里面把jumpserver drop 后重建

**Comment by meyer-net** [comment]
@wojiushixiaobai 不行的，我重复试过很多次了。

**Comment by meyer-net** [comment]
@jym503558564 包括py虚拟环境重建，都不行。这段报错了，后续的压根无法执行。

**Comment by jym503558564** [comment]
在 perms 的migrations中'0002_auto_20171228_0025_squashed_0009_auto_20180903_1132.py'这张表，注释掉一些内容试试：
![image](https://user-images.githubusercontent.com/40739051/64931865-d0586680-d86d-11e9-96a1-e00ed76c381e.png)
![image](https://user-images.githubusercontent.com/40739051/64931885-f4b44300-d86d-11e9-8dc2-c386c0d0aaa5.png)
之后重新建表再启动试试

**Comment by meyer-net** [comment]
@jym503558564  that's ok ，问题解决。非常感谢。
