### ISSUE TITLE
两层nginx代理导致连接服务器异常

### ISSUE THREAD

**Issue by MrYHM** [jumpserver/jumpserver#3218]
[简述你的问题]
在172.18.0.2上搭建jumpserver，nginx监听172.18.0.2:80，
在172.18.0.3上只配置nginx，代理172.18.0.2:80。
通过http://172.18.0.2:80访问Luna页面，链接服务器一切正常。
通过http://172.18.0.3:80访问Luna页面链接服务器，有时连接不上服务器，需要刷新页面才可以连接服务器（有时需要多刷新几次）。并且链接不上服务器时，点击服务器，nginx，jumpserver、coco都没有打印出日志。

##### 使用版本     ：1.5.2
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@MrYHM https://docs.jumpserver.org/zh/master/faq.html 第6条

**Comment by teazj** [comment]
两层nginx 没法连接服务器
Error during WebSocket handshake: Unexpected response code: 400

**Comment by teazj** [comment]
![image](https://user-images.githubusercontent.com/6780969/74552001-454fd980-4f8f-11ea-8c99-c6657be0b635.png)

**Comment by teazj** [comment]
server {
  listen 80;
  server_name jmp.opscom;
  access_log /data/nginx/logs/opsgjbc.log;
  client_max_body_size 100m;  # 录像及文件上传大小限制

  location /luna/ {
    proxy_pass http://jumpserver-docker-compose/luna/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /media/ {
    proxy_pass http://jumpserver-docker-compose/media/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /static/ {
    proxy_pass http://jumpserver-docker-compose/static/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /koko/ {
    proxy_pass http://jumpserver-docker-compose:5000;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    access_log off;
  }
  location /guacamole/ {
    proxy_pass http://jumpserver-docker-compose:8081;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    access_log off;
  }
  location /ws/ {
    proxy_pass http://jumpserver-docker-compose:8070;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }


    location / {
        proxy_pass http://jumpserver-docker-compose:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

**Comment by teazj** [comment]
1,5.4版本

**Comment by teazj** [comment]
![image](https://user-images.githubusercontent.com/6780969/74552199-a5df1680-4f8f-11ea-96de-0e722170b227.png)
