### ISSUE TITLE
Windows Server一直是等待任务开始。。。

### ISSUE THREAD

**Issue by RocsSun** [jumpserver/jumpserver#3220]
Windows Server测试资产可连接性的状态：一直是等待任务开始。。。

- Version 1.5.2-2 GPLv2.

配置Windows Server之后，链接不过去

截图如下：

![image](https://user-images.githubusercontent.com/41471196/64756328-16a58100-d561-11e9-8276-060eec2a186d.png)

![image](https://user-images.githubusercontent.com/41471196/64756351-29b85100-d561-11e9-8673-16cce3ac15b2.png)

![image](https://user-images.githubusercontent.com/41471196/64756360-38066d00-d561-11e9-9bd4-e717764ea4c2.png)

**Comment by BaiJiangJie** [comment]
尝试重启一下 celery
