### ISSUE TITLE
請問如何修改與"資產"間的心跳頻率(預設是4點到19點每小時一次）

### ISSUE THREAD

**Issue by viruskingkk** [jumpserver/jumpserver#3226]
[简述你的问题]
心跳頻率太頻繁造成登入紀錄不好管理,想請問該在哪個位置修改設定檔才能更改與"資產"間的心跳頻率.

##### 其他

[注:] 完成后请关闭 issue

**Comment by eli261** [comment]
代码位置：

https://github.com/jumpserver/jumpserver/blob/91d1a62c98af88c265a48b486962991a5beb67a3/apps/assets/tasks/admin_user_connectivity.py#L41

函数：

```python
@shared_task(queue="ansible")
@register_as_period_task(interval=3600)
def test_admin_user_connectivity_period():
```

将`interval=3600`改为你想要的值即可，例如，你想改成每3个小时触一次，那么就改为`interval=3600*3`

**Comment by wojiushixiaobai** [comment]
@viruskingkk
