### ISSUE TITLE
严重问题，普通用户登陆后可访问/jperm/rule/add/给任意用户赋权

### ISSUE THREAD

**Issue by caozhangni** [jumpserver/jumpserver#323]
严重问题，普通用户登陆后可访问/jperm/rule/add/给任意用户赋权

**Comment by jiaxiangkong** [comment]
你所说的普通用户登陆是指哪个，web 、webssh、tty

**Comment by caozhangni** [comment]
普通用户web登录，在目前的master分支，应该是def perm_rule_add(request):这个函数没有添加角色检查的装饰器

**Comment by jiaxiangkong** [comment]
谢谢你的反馈 已修复
