### ISSUE TITLE
登录个人信息页面报错

### ISSUE THREAD

**Issue by 15029836736** [jumpserver/jumpserver#3231]
[简述你的问题]
公司部分用户打开个人信息页面报错
![image](https://user-images.githubusercontent.com/18047710/65007888-11b64800-d93a-11e9-8208-29048191bc8f.png)

##### 使用版本
1.5.2
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/18047710/65007895-15e26580-d93a-11e9-9d09-debc3cd979a5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
能否复现一下步骤，截图。以及完成的错误日志截图。

**Comment by 15029836736** [comment]
步骤就是web页面登录，打开个人页，就会报错。
![image](https://user-images.githubusercontent.com/18047710/65501185-1d35e000-def3-11e9-9bbc-4723cadcf30a.png)

前置条件：
 所有用户数据都是我从旧的数据库把信息搞下来，包括加密后的公钥，是利用base64解密第二段获取的。然后通过创建用户的api接口重新创建一遍用户。这是造成这一情况的前置操作，部分用户会有问题。

解决办法：
目前是利用admin账号在web页面对有问题的用户重新更新一下就好了。
![image](https://user-images.githubusercontent.com/18047710/65501508-afd67f00-def3-11e9-8d2f-1bb0adf751d9.png)

错误日志：
没有错误日志，只有接口的500报错。因为是python的hash_md5函数报错，在渲染页面之前就报错了。

**Comment by BaiJiangJie** [comment]
导致这个问题的原因可能是因为从旧的数据库中把信息搞下来的时候，公钥信息前后包含了空白字符，然后在进行 hash_md5 的时候报错了。
至于更新用户后问题被解决，可能是由于将用户保存到数据库的时候会把公钥信息的前后空白字符 strip 掉。
如果想校验一下是否是所述原因，可以在更新用户前后将用户的 publik_key 字段值进行比较。

如果仍存在问题，请重新打开 Issue。
