### ISSUE TITLE
给用户授权多个系统用户，然后用户连接资产跳转到luna会弹出多个用户选择框

### ISSUE THREAD

**Issue by supmatch** [jumpserver/jumpserver#3233]
[简述你的问题]
给用户授权多个系统用户，然后用户连接资产跳转到luna会弹出多个用户选择框

##### 使用版本
[jumpserver1.5.2-2，luna1.5.2]

##### 问题复现步骤
1. 授权用户资产多个系统用户
2. 用户登录之后连接资产跳转到luna
3. 跳转到luna之后，跳出连接资产用户选择框，选择一个确定之后，连接上主机，但是又会出现一个选择框
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/45656710/65016116-f8bb9000-d955-11e9-87b9-865bf8d7704a.png)
![image](https://user-images.githubusercontent.com/45656710/65016134-0e30ba00-d956-11e9-9632-59551b43c818.png)
![image](https://user-images.githubusercontent.com/45656710/65016152-20aaf380-d956-11e9-9a25-5ea1fa87095e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
复现的概率？
是否是双击？

**Comment by supmatch** [comment]
已发现问题：当一个资源在不同的节点都存在时
直接从资产列表点击连接过去
连接就会弹出多个框





------------------ 原始邮件 ------------------
发件人: "八千流"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 中午11:02
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com>; 
抄送: "火柴"<120612671@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [jumpserver/jumpserver] 给用户授权多个系统用户，然后用户连接资产跳转到luna会弹出多个用户选择框 (#3233)




复现的概率？
 是否是双击？

**Comment by jym503558564** [comment]
1.5.3已修复，请关注新版本发布情况
