### ISSUE TITLE
coco start error

### ISSUE THREAD

**Issue by MOOREZHANG64** [jumpserver/jumpserver#3237]
从terminal中启动coco报错

##### 使用版本
1.5.2

##### 问题复现步骤
1. 进入py3虚拟环境

2. 运行 ./cocod start -d

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10070015/65102151-ce70dd80-d9fc-11e9-920d-9a3aa60f136b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@MOOREZHANG64 token不正确，删掉web终断和coco/data/keys/下面的文件后，确定token，重启coco
