### ISSUE TITLE
命令记录内容太长，显示不完整

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3238]
[简述你的问题]
命令记录内容太长，显示不完整，而且没有划轴拉到右侧看不到的内容，只能把网页缩小到很小才能看全

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/44529247/65131343-a780ce80-da31-11e9-95ad-10c03a18026b.png)

2. [步骤2]
![image](https://user-images.githubusercontent.com/44529247/65131546-fc244980-da31-11e9-81c0-31720afe7b08.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
命令记录有最大长度限制，为防止消耗大量内存。命令的完整内容，可以通过录像查看。
