### ISSUE TITLE
使用sftp传文件老是会出问题

### ISSUE THREAD

**Issue by lovese** [jumpserver/jumpserver#3245]
使用sftp传文件老是会出问题，提示无法显示远程文件夹
![image](https://user-images.githubusercontent.com/13268438/65295732-dc596680-db94-11e9-9b5c-209407ca50d4.png)
每次都要重启koko容器，重启完就可以了，很烦！！！
有的人又不会碰到这种问题，很奇怪
还有的人会提示shell无法连接，也得重启koko就好了
不知道问题出在哪里？希望给予支持！！！
jumpserver version 1.5.2-2

**Comment by wojiushixiaobai** [comment]
@lovese koko/config.yml 里面关闭连接复用试试

**Comment by lovese** [comment]
我试试先
