### ISSUE TITLE
测试邮件不能指定接收人

### ISSUE THREAD

**Issue by Dollyn** [jumpserver/jumpserver#3246]
[简述你的问题]
邮件设置 ->  测试连接
系统默认发送账号和接收人一样， 而一般来说发送账号是不允许收件的，会导致测试连接报错。

##### 使用版本
1.5.2-2

##### 问题复现步骤
1. 系统设置
2. 邮件设置
3. 填写各个字段
4. 点击  测试连接 按钮

希望测试连接能指定收件人

**Comment by BaiJiangJie** [comment]
@Dollyn 感谢您对 Jumpserver 的支持
此需求目前已 Merge 到 dev 分支，请等待后续版本发布。

https://github.com/jumpserver/jumpserver/pull/3311

**Comment by BaiJiangJie** [comment]
@Dollyn 此功能已 Merge 到 master 分支，请及时更新，如有问题，请重新打开 Issues ～
