### ISSUE TITLE
磁盘统计不准确

### ISSUE THREAD

**Issue by maojianyou** [jumpserver/jumpserver#3247]
磁盘统计跟机器上实际不符合

Jumpserver版本1.52最新版本

能否统计出，固体硬盘多少个，机械硬盘多少个，各多少存储吗？
![image](https://user-images.githubusercontent.com/55315920/65326480-261d6d80-dbe4-11e9-9ce3-d0a484c75553.png)

**Comment by BaiJiangJie** [comment]
项目中资产硬件信息是通过 Ansible 进行获取的，您可以先手动编写 Ansible 脚本手动获取一下，查看返回信息中，磁盘信息是否和资产实际情况相符。

**Comment by ibuler** [comment]
目前还没有这个计划
