### ISSUE TITLE
安全问题扫描2222端口可以看到版本号及sudo su切换问题

### ISSUE THREAD

**Issue by maojianyou** [jumpserver/jumpserver#3248]
jumpserver 1.52最新版本

coco1.52版本  直接登录到系统用户普通用户界面，敲键盘sudo su不能切换，但通过CRT 自动登录动作，可以直接进去。
![image](https://user-images.githubusercontent.com/55315920/65326732-ba87d000-dbe4-11e9-8dd8-3955ab4685c3.png)

![image](https://user-images.githubusercontent.com/55315920/65326691-a512a600-dbe4-11e9-999f-f67dbac68f4b.png)

**Comment by BaiJiangJie** [comment]
@LeeEirc 请帮助确认一下用户所遇到的问题。

**Comment by LeeEirc** [comment]
@maojianyou coco是使用paramiko提供ssh server的，版本号能显示是正常的。至于sudo问题，如果没有设置限制，应该是可以切换的。能更详尽描述一下，你预期的结果和遇到的问题吗？
