### ISSUE TITLE
1.5.2更新后访问报错

### ISSUE THREAD

**Issue by findix** [jumpserver/jumpserver#3249]
升级到1.5.2之后，第一次访问（之前登陆过，有Cookie）页面会报错

##### 使用版本
1.5.2

##### 问题复现步骤
1. 登陆
2. 升级到最新版本
3. 访问任意页面

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3446387/65377517-c86e4b80-dcdf-11e9-85e8-1dcbb9371ec5.png)

##### 其他
无

**Comment by wojiushixiaobai** [comment]
@findix 用master分支

**Comment by findix** [comment]
是在 master 分支，也试过直接checkout 1.5.2 的 tag，都会报错

**Comment by BaiJiangJie** [comment]
从错误日志来看，您所登录用户的 is_expired 字段为 None，请问这个用户是如何创建的呢？

**Comment by BaiJiangJie** [comment]
您可以进入到项目目录的 apps 目录下（例如：cd /opt/jumpserver/apps/）：
执行一下命令：
/opt/jumpserver/apps/ >>> python manage.py shell
>>> from users.models import User, date_expired_default
>>> u = User.objects.get(username="登录报错的用户的用户名")
>>> u.is_expired = date_expired_default()
>>> u.save()
然后尝试登录。

**Comment by findix** [comment]
用户是在Web界面创建的，已经用了很久了，这次是从1.4.9升级之后发生的问题

```bash
(py3) [root@jumpserver apps]# python manage.py shell
2019-09-29 20:55:34 [signals_handler DEBUG] Monkey patch settings
Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from users.models import User, date_expired_default
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'date_expired_default'
>>> from common.utils import get_signer, date_expired_default, get_logger
>>> u = User.objects.get(username="username")
>>> u
<User: 用户名(username)>
>>> date_expired_default()
datetime.datetime(2089, 9, 11, 12, 56, 12, 77250, tzinfo=<UTC>)
>>> u.is_expired
False
>>> u.is_expired = date_expired_default()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: can't set attribute
>>> 
```

尝试失败，看了一下代码，
https://github.com/jumpserver/jumpserver/blob/7502a372b58ff42969d7cbae58f9d2c93991d134/apps/users/models/user.py#L441-L446

执行
```shell
>>> u.date_expired  = date_expired_default()
```
可以登录进去了！有点奇怪啊，`is_expired` 是个 property，感觉不可返回 None 呀。

感谢帮忙解决了问题~~~
