### ISSUE TITLE
历史会话录像丢失，没做过删除处理

### ISSUE THREAD

**Issue by yangyang198599** [jumpserver/jumpserver#3252]
[简述你的问题]

##### 使用版本
1.48

##### 问题复现步骤
历史会话 记录丢失

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
请确认历史会话列表的时间段，默认会列出最近 5-7 天内的历史会话记录。

**Comment by yangyang198599** [comment]
一条都没有了


杨阳
重庆超集通信息科技有限公司
Mobile：13658313405
Email：yang.yang@365cjt.com
http://www.hhg365.cn

**Comment by BaiJiangJie** [comment]
好的，最近可能会有 Jumpserver 的成员联系您，帮您看一下是什么原因导致。
