### ISSUE TITLE
[Server][1.5.2]从AD域中导入堡垒机的用户，如果只删除其在堡垒机中的账号，未删除其在AD域中的账号，该用户仍可登录堡垒机；

### ISSUE THREAD

**Issue by MOOREZHANG64** [jumpserver/jumpserver#3255]
[简述你的问题]
[Server][1.5.2]从AD域中导入堡垒机的用户，如果只删除其在堡垒机中的账号，未删除其在AD域中的账号，该用户仍可登录堡垒机；

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2 ]

##### 问题复现步骤
1. 配置好LDAP，并从Windows Server AD域中导入用户。
2. 使用某用户AD域账号登录jumpserver，登录成功。
3. 使用管理员账户从用户列表中删除上面的AD域用户。
4. 使用该被删除的AD域用户登录jumpserver，仍能登录成功。

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
正常情况下，如果用户（LDAP）满足 Jumpserver 中 LDAP 配置的信息（即可以搜索到该用户），那么该用户是可以登录的。
基于对以上问题的描述，您可以尝试以下几种方式，来限制不希望 LDAP 用户登录的场景：
1. 编写 LDAP 配置中的用户过滤器，过滤掉不希望登录的一些用户。
2. 在 LDAP 服务端，禁用不希望登录的用户。
3. 如果用户之前登录过 Jumpserver，可尝试在 Jumpserver 中禁用该用户。
