### ISSUE TITLE
部署最后提示：Starting jumpserver service:  [FAILED]

### ISSUE THREAD

**Issue by kewaike** [jumpserver/jumpserver#326]
部署最后提示：Starting jumpserver service:  [FAILED]，换了几台机器尝试仍然出现该问题，发现部署jumpserver一段时间好一段时间坏，跟黄历有关么？？，centos6.8系统，日志均无异常，请大牛协助。

**Comment by ibuler** [comment]
手动运行试试， python run_server.py  wiki上应该有说明
