### ISSUE TITLE
点击推送主机之后网站卡死

### ISSUE THREAD

**Issue by zghember** [jumpserver/jumpserver#327]
就跟mail没配置好就直接卡死一样，只能重启
用的docker镜像
另外，没搞懂sudo别名到底是什么，已经看了wiki的名词解释还是不懂。。

**Comment by zghember** [comment]
试了一下，如果不勾选使用秘钥，就不会卡死。
然后会显示推送成功，实际上什么都没有发生

**Comment by zghember** [comment]
在web页面创建的用户，需要到容器中执行passwd -u username之后才能正常登陆跳板机，估计这是bug？

**Comment by zghember** [comment]
另外，容器里面时区还是时间不太对，在页面上显示是错的

**Comment by ibuler** [comment]
这个bug已经知晓，修复中
