### ISSUE TITLE
无法访问Web终端资产 Register host error, register token then connect

### ISSUE THREAD

**Issue by MOOREZHANG64** [jumpserver/jumpserver#3271]
[简述你的问题]
无法访问Web终端资产 Register host error, register token then connect

##### 使用版本
[请提供你使用的Jumpserver版本  ]
1.5.2

##### 问题复现步骤
1. 安装jumpserver在一个VM，并测试通过（包括luna，coco）。
2. 将该VM打包成vmdk，并部署到一台新的VM上。
3. 登录后打开Web终端

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10070015/65512613-267f7680-df0c-11e9-87e0-8855d641854a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
从截图来看，报错信息是在连接 Windows 资产时出现的。在 VM 打包之前，测试通过（luna、coco），是否有测试过 guacamole 呢？

**Comment by BaiJiangJie** [comment]
同时也建议您将版本升级到最新版（v1.5.3【2019.09.29】）进行使用。
