### ISSUE TITLE
502 Bad Gateway COCO服务报错

### ISSUE THREAD

**Issue by MOOREZHANG64** [jumpserver/jumpserver#3272]
[简述你的问题]
502 Bad Gateway

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10070015/65566839-9af6fb80-df86-11e9-8030-9d9c7fba2402.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by NeilyoSH** [comment]
如果开启了Selinux, 修改对应路径的luna fcontext安全上下文即可.

$ semanage fcontext -a -t httpd_sys_content_t '/data/luna(/.*)?'
$ restorecon -vvFR /data/luna

**Comment by wojiushixiaobai** [comment]
@MOOREZHANG64 参考faq文档的 [ssh资产连接说明](https://docs.jumpserver.org/zh/docs/faq_ssh.html) 第一条，检查coco是否在线，确定nginx设置正确。建议更新到最新的master分支
