### ISSUE TITLE
多个 Linux机器切换tab，显示的输出会回到最上面

### ISSUE THREAD

**Issue by xyggun** [jumpserver/jumpserver#3277]
[简述你的问题]
web终端登录多个 Linux机器，切换tab。隐藏的tab上的输出在重新切换回来之后，显示的输出会回到最上面。

##### 使用版本
1.4.8-2 GPLv2

##### 问题复现步骤
1. 链接多台linux，cat 某个日志
2. 切换其它机器，再切回来

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
非常感谢您细心的提问，建议您能升级到最新版本（v1.5.3【2019.09.29】）使用，同时查看以上问题是否依旧会出现。
