### ISSUE TITLE
jms 1.5.3 添加中文名资产，出现错误： 主机名包含不被允许的字符

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#3282]
[简述你的问题]

jms 1.5.3 添加中文名资产，出现错误： 
```
只允许包含数字，字母，特殊字符（ . _ @ ）
* 主机名包含不被允许的字符
```

##### 使用版本
1.5.3

##### 问题复现步骤
资产名称包含中文及中文标点符号

##### 其他

[注:] 完成后请关闭 issue

**Comment by HuanMeng0** [comment]
目前资产名称可以输入中文了，能否可以允许输入“【】”？

**Comment by jym503558564** [comment]
- 目前命名规则支持中文，字母，数字，以及特殊字符(.  _  @)
