### ISSUE TITLE
在安装过程中，出现错误。

### ISSUE THREAD

**Issue by 2994186010** [jumpserver/jumpserver#3296]
[简述你的问题]
当我运行“pip install -r requirements.txt”时，总是无法通过，错误如下所示：
ERROR: pyasn1-modules 0.2.6 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.4.2 which is incompatible.
ERROR: autobahn 19.9.3 has requirement cryptography>=2.7, but you'll have cryptography 2.3.1 which is incompatible.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 执行“pip install -r requirements.txt”

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/15965075/65812665-a94e4d00-e1fc-11e9-9d8a-00437239876a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
从日志来看，应属于 Python 第三方包安装的问题，可能是由于 Jumpserver 需要安装的第三方包，所依赖的其他第三方包存在于本地环境中，但是版本可能较低，需要升级依赖包到指定版本或以上。
比如：ERROR: autobahn 19.9.3 has requirement cryptography>=2.7, but you'll have cryptography 2.3.1 which is incompatible.
autobahn 19.9.3 需要 cryptography>=2.7 的包，本地环境可能是 2.3.1 版本，所以不是很合适。
解决：尝试升级一下 cryptography 包的版本，当然也包含  pyasn1 等包。

**Comment by wojiushixiaobai** [comment]
@2994186010 前面两条error忽略，解决最后一条error即可
