### ISSUE TITLE
连接服务器时hang住，无任何响应

### ISSUE THREAD

**Issue by flzhang132** [jumpserver/jumpserver#3297]
[简述你的问题]
进入web终端，选择linux服务器后，界面中不会出现连接时的数秒过程
界面无任何响应。但使用个别客户端连接时无此问题。大数据客户端通过jumpserver
连接服务器时都是无响应状态。请给予帮助非常感谢

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. 进入jumpserver
2. 打开web终端，选择某台linux服务器后，界面中不会出现连接时的数秒过程
界面无任何响应。但使用个别客户端连接时无此问题。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26810567/65825790-becf7f80-e2ad-11e9-9bdd-56cf8f24c4f0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
资产连接在最新的版本中做了优化，建议您升级到最新版本（v1.5.3【2019.09.29】）进行使用。

**Comment by ibuler** [comment]
应该是websocket没有连接上，刷新一下要么是否可以解决

**Comment by huangpeng0817** [comment]
setsebool -P httpd_can_network_connect 1 遇到过此问题使用这个看看是否有效。我之前配置的selinux也是关闭的。

**Comment by ibuler** [comment]
如问题依然，重新打开issue

**Comment by Lewisyixin** [comment]
我也遇到过几次同样问题， 连接的时候就卡死没有任何日志，通过其他方式登录到需要登录的机器后netstat看连接应该是没有建立ssh连接，而且最奇怪的是，出现A用户无法登录01机器的时候，用B，C账户都能正常登录01机器，而且A用户也能登录02机器，在多台电脑都试过，所以应该不是用户PC的问题。
