### ISSUE TITLE
remoteapp 配置入口问题

### ISSUE THREAD

**Issue by gls3** [jumpserver/jumpserver#3300]
[部署后没有remoteapp的配置入口，应该如何添加remoteapp呢]

##### 使用版本
Version 1.5.3-2 GPLv2.

**Comment by BaiJiangJie** [comment]
@gls3 
首先感谢您对 Jumpserver 功能的密切关注， 对于 RemoteApp 功能目前开源版本不能正常使用，因为此功能是 Jumpserver 商业版中包含的功能之一，如果您对此功能感兴趣，请联系 Jumpserver 的商业团队进行咨询。

**Comment by BaiJiangJie** [comment]
如果还有其他问题，请重新打开 Issues。
