### ISSUE TITLE
1.5.2升级到1.5.3以后,与ansible相关的操作都会报错

### ISSUE THREAD

**Issue by eagleye1115** [jumpserver/jumpserver#3301]
[简述你的问题]
1.5.2升级到1.5.3以后,与ansible相关的操作都会报错

##### 使用版本
1.5.3

##### 问题复现步骤
1.作业中心-命令执行  随便执行什么命令,命令都有成功返回最后会报错
2.资产管理-资产列表 更新硬件信息、测试可连接线 也是有成功返回最后会报错
##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/11611725/65847943-51d3ec80-e376-11e9-9f4c-c503381df942.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@eagleye1115 后台运行的bug，等待修复即可。

**Comment by ibuler** [comment]
已更新到master分支
