### ISSUE TITLE
全新安装的1.5.3 windows 连接不上

### ISSUE THREAD

**Issue by lvshuishangshang** [jumpserver/jumpserver#3303]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
创建Windows 2012机器之后，在luna界面连接不上，一直显示的是“无法连接服务器，请联系管理员或查看日志”
查看docker日志上，注册是正常的，但是好像有异常

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/24688300/66185614-903d1480-e6b2-11e9-863b-e3acfcebc3f8.png)
![image](https://user-images.githubusercontent.com/24688300/66185659-af3ba680-e6b2-11e9-9f20-2636be1f6df2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
@lvshuishangshang 
其他版本的 windows 服务器（如：windows 7、windows 8、windows 2016）可以连接成功吗？

**Comment by lvshuishangshang** [comment]
目前没有试，因为我的服务器都是Windows2012的

**Comment by lvshuishangshang** [comment]
这个是不是个bug呢，我看其他用户也反馈其他版本的Windows连不上了

**Comment by wojiushixiaobai** [comment]
@lvshuishangshang 参考此演示视频 https://www.bilibili.com/video/av70885582
