### ISSUE TITLE
全新安装1.5.3使用公钥连接centos6服务器异常

### ISSUE THREAD

**Issue by lvshuishangshang** [jumpserver/jumpserver#3304]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
全新安装的1.5.3，使用公钥连接资产，ubuntu服务器能够正常添加连接，但是centos的服务器，添加后连接有异常，使用不了
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/24688300/66185775-0477b800-e6b3-11e9-8611-4bc80d463deb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
@lvshuishangshang 使用密码可以登录成功吗？

**Comment by lvshuishangshang** [comment]
用密码登录是正常的，这个是不是也是个小bug呢

**Comment by BaiJiangJie** [comment]
私钥是自动生成的，还是在 centos 端生成然后上传到 Jumpserver 的？
如果是自动生成的应该没问题，如果是手动上传的私钥，请使用 rsa、dsa 格式。
