### ISSUE TITLE
1.5.2升级到1.5.3后，添加到资产的新机器，不会自动推送，手动也无法推送，导致无法连接

### ISSUE THREAD

**Issue by William-1989** [jumpserver/jumpserver#3305]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
1.5.2升级到1.5.3后，添加到资产的新机器，用户公钥不会自动推送.
手动也无法推送，会出现Connect websocket server error.
导致无法连接，尝试重启服务./jms stop & ./jms start -d 后 ，可能推送成功可以连接，但不会每次重启服务都会成功。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/56165110/66217846-9c4cc480-e6fa-11e9-96c4-013cfa8ad587.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
@William-1989 当自动推送失败时（出现 Connect websocket server error），看一下 Core 的日志信息，有没有对应的错误日志输出？

**Comment by wojiushixiaobai** [comment]
@William-1989 nginx缺少 ws 的内容，请更新下nginx配置文件
````
        location /ws/ {
            proxy_pass http://localhost:8070;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }

        location / {
            proxy_pass http://localhost:8080;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
````

**Comment by evenson419** [comment]
> @William-1989 nginx缺少 ws 的内容，请更新下nginx配置文件
> 
> ```
>         location /ws/ {
>             proxy_pass http://localhost:8070;
>             proxy_buffering off;
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             access_log off;
>         }
> 
>         location / {
>             proxy_pass http://localhost:8080;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
> ```

配置了也不行，何解，服务器防火墙也没有开启
