### ISSUE TITLE
cat binary file导致终端无响应

### ISSUE THREAD

**Issue by caijq4ever** [jumpserver/jumpserver#3309]
如题

##### 使用版本
1.5.2

##### 问题复现步骤
1. `$ cat /bin/ls`

##### 具体表现
![image](https://user-images.githubusercontent.com/5621857/66381402-d4e6e980-e9eb-11e9-9860-e0a496ce6bdd.png)

在终端运行`cat /bin/ls`之后，如图，一直停留在这个界面，按回车，Ctrl+C等都不会重新回到命令行首。

直接ssh远程服务器运行上面的命令是没有问题的。

**Comment by BaiJiangJie** [comment]
@LeeEirc 有空帮忙排查一下问题，验证后确实会卡住。

**Comment by LeeEirc** [comment]
@caijq4ever 感谢反馈问题，已经在1.5.3更新修复。

**Comment by caijq4ever** [comment]
OK!
