### ISSUE TITLE
web终端连接成功，资产管理链接失败

### ISSUE THREAD

**Issue by dearblen** [jumpserver/jumpserver#3310]
[简述你的问题]
资产管理链接失败，获取硬件信息失败
确认密码，密钥没有配错
是不是由于SSH 登录时间长，导致的获取资产信息失败？
有什么办法可以更改超时时间？

##### 使用版本
使用的Jumpserver版本 1.5.3

##### 问题复现步骤
1. 确认密钥没有错误
  使用相同密钥WEB终端登录成功
2.web终端登录用时10S以上
开始连接到 topdraw@192.168.4.242 11.5
Last login: Tue Oct  8 17:17:57 2019 from 172.25.42.107
 Authorized users only. All activity may be monitored and reported
[topdraw@hebeictcc_lb01 ~]$

**Comment by BaiJiangJie** [comment]
先排查一下为什么登录资产需要 10s，是网络问题吗？

**Comment by dearblen** [comment]
@BaiJiangJie  你好
网络环境确实不太好 ，ping 的延时在 100MS 以上
但是应该不是网络的问题，因为从内网的其他服务器ssh登录 也是10S 以上
尝试配置过 SSH server端 useDNS no, GSSAPIAuthentication no，不能解决的SSH 登录慢的问题
所以来看看 是不是有其他解决方案

**Comment by BaiJiangJie** [comment]
@dearblen 
你好：
    获取资产硬件信息的超时时间配置可修改 apps/assets/tasks/const.py 文件中选项 TASK_OPTIONS 中 timeout 对应的值（默认 10s）
    如果从内网中的其他服务器 SSH 登录也需要 10s 以上的话，建议先定位一下 SSH 登录慢的原因，因为对上面的配置进行修改后，其他的任务也有可能会变慢。
