### ISSUE TITLE
Windows上传下载权限问题

### ISSUE THREAD

**Issue by Tiny66** [jumpserver/jumpserver#3318]
[简述你的问题]
windows资产只能同时授予上传下载权限，如果只单纯授予上传权限，则无法上传，并且windows资产上看不到共享磁盘

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2

##### 问题复现步骤
1. windows资产只授予上传权限
2. 上传文件无反应，windows资产上看不到共享磁盘

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
目前 Windows 资产只能同时控制上传下载权限，尚不支持单独控制上传或下载权限。
