### ISSUE TITLE
1.5.3的几个bug 希望早日修复 

### ISSUE THREAD

**Issue by lafitecao** [jumpserver/jumpserver#3322]
第一个问题 改节点名字 报更新时发生未知错误

![QQ图片20191010155329](https://user-images.githubusercontent.com/29372470/66549883-dbee3300-eb76-11e9-9463-308dd3673129.png)

![QQ图片20191010155313](https://user-images.githubusercontent.com/29372470/66549914-f0323000-eb76-11e9-802a-3bee70afbbe3.jpg)

第二个问题 全站加ssl证书后  no asset id or system user id found  用http则正常
![QQ图片20191010155302](https://user-images.githubusercontent.com/29372470/66549997-10fa8580-eb77-11e9-8dc9-e3d00fdf979c.png)

第三个问题
字体大小 调整无效 ,后期希望能加入自已选字体的功能。

**Comment by BaiJiangJie** [comment]
@lafitecao 
第一个问题：重命名节点报错如何复现？

**Comment by wojiushixiaobai** [comment]
@lafitecao 问题2无法复现，参考[demo网站](https://demo.jumpserver.org)

**Comment by lafitecao** [comment]
> @lafitecao
> 你好
> 第一个问题：重命名节点报错如何复现？

没有日志 我也查不到原因

**Comment by BaiJiangJie** [comment]
> > @lafitecao
> > 你好
> > 第一个问题：重命名节点报错如何复现？
> 
> 没有日志 我也查不到原因

每次更新都会有报错吗？

**Comment by BaiJiangJie** [comment]
> @lafitecao 问题2无法复现，参考[demo网站](https://demo.jumpserver.org)

是不是用户 @lafitecao SSL 证书配置的不正确，导致 koko 获取资产和系统用户的时候失败。

【No asset id or system user id found, exit】报错信息是 SSH 登录进去什么操作下出现的？

**Comment by wojiushixiaobai** [comment]
@lafitecao 组件的注册地址改成http://<jms_ip>:8080 不通过nginx注册试试
