### ISSUE TITLE
版本1.5.3，用户管理下面的用户组，更新用户界面的“取消”键失效

### ISSUE THREAD

**Issue by williams-lu** [jumpserver/jumpserver#3326]
[简述你的问题]
用户管理下面的用户组，更新用户界面的“取消”键失效

##### 使用版本
版本1.5.3

##### 问题复现步骤
1. [步骤1]
![1](https://user-images.githubusercontent.com/3540017/66635613-2b4d6580-ec42-11e9-966f-92f14cb05091.png)

2. [步骤2]
![2](https://user-images.githubusercontent.com/3540017/66635632-36a09100-ec42-11e9-998a-51a1a796b29a.png)

##### 具体表现[截图可能会更好些,最好能截全]
无法跳转上一级界面

**Comment by jym503558564** [comment]
取消会撤销刚修改的表单信息，表单恢复到默认修改前的信息，例如：
![image](https://user-images.githubusercontent.com/40739051/66734526-0a7d4e00-ee96-11e9-9840-ec85802d9263.png)
![image](https://user-images.githubusercontent.com/40739051/66734553-22ed6880-ee96-11e9-931b-124351d77672.png)
![image](https://user-images.githubusercontent.com/40739051/66734586-46181800-ee96-11e9-8b9a-c84638231433.png)

**Comment by BaiJiangJie** [comment]
@williams-lu 
感谢您细心的使用 Jumpserver ～
很抱歉，这是因为按钮文案描述的不够准确，才导致理解产生了歧义，后面的版本会修改 取消 -> 重置。
