### ISSUE TITLE
web 连接不到目标服务器

### ISSUE THREAD

**Issue by justinmjc** [jumpserver/jumpserver#3327]
[简述你的问题]
在web界面上连接某台服务器，
web 报错：
2019-10-11 16:39:35 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

查看koko 的日志:
2019-10-11 16:39:35 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
2019-10-11 16:41:17 [ERRO] ERROR: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.3
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by justinmjc** [comment]
https://github.com/gorilla/websocket/blob/master/server.go:
源码
if !tokenListContainsValue(r.Header, "Connection", "upgrade") {
		return u.returnError(w, r, http.StatusBadRequest, badHandshake+"'upgrade' token not found in 'Connection' header")
	}

请求头
GET ws://10.88.10.58/koko/ws/?X-Websocket-Header-X-Namespace=ssh HTTP/1.1
Host: 10.88.10.58
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Upgrade: websocket
Origin: http://10.88.10.58
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: csrftoken=AciCESV0g3nFIUkd07XK68np0HSCvwhzmSUWEDgaritfNAtoz87QGIi67O9y7To8; sessionid=hgqoo5wzscwmkct5g5lldmlridbdmnhg
Sec-WebSocket-Key: zYHeEZF/X3wYPQvt+ROtCw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits


看上去请求头里的 Upgrade 是大写的，源码里检验的是小写的

**Comment by justinmjc** [comment]
问题解决了
我是用docker-compose方式安装的，
nginx.conf:
        location /koko/ {
            proxy_pass       http://koko:5000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }


配置确少了header，加上就好了。
    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

**Comment by wh0am111** [comment]
Thanks,I resolve it!
