### ISSUE TITLE
1.4.8升级1.5.3，终端无法连接

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3328]
[简述你的问题]
1.4.8升级1.5.3，coco替换koko，终端无法连接，文件管理502

##### 使用版本
1.5.3

##### 问题复现步骤
1. [1.4.8升级1.5.3，原先是coco，替换为koko，重启后web终端无法连接，文件管理502]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
http://i1.fuimg.com/701324/6a91d91b6935b9e8.png
http://i1.fuimg.com/701324/1eaffd2ff4c6a1aa.png
##### 其他
jumpserver.conf文件内容如下

server { 
    listen 80 default;
    server_name _;
    return 403;
}

server {
    listen 80;

    
  
    client_max_body_size 1000m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径, 如果修改安装目录, 此处需要修改
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;  # 录像位置, 如果修改安装目录, 此处需要修改
    }

    location /static/ {
        root /opt/jumpserver/data/;  # 静态资源, 如果修改安装目录, 此处需要修改
    }

    location /socket.io/ {
        proxy_pass       http://localhost:5000/socket.io/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
从以下几个方面排查下：
1. 打开浏览器调试窗口，有无报错
2.查看luna组件是否为最新版本
3.查看koko日志，是否有异常信息
4.手动通过工具进行ssh连接是否异常

**Comment by BaiJiangJie** [comment]
@zxxxxxxd 问题解决了吗？
