### ISSUE TITLE
1.5.3测试连接性问题以及账号动作限制问题

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3330]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
1. [添加资产后测试可连接性报错]
2. [在jumpserver服务器上ssh连接时可以连接到对方服务器，因为服务器在异地，可能第一次连接时很慢]
3.[限制了授权动作权限，无法上传下载文件，但是在文件管理中还是可以上传和下载文件]
##### 具体表现[截图可能会更好些,最好能截全]

http://chuantu.xyz/t6/702/1570863788x1031866013.png
http://chuantu.xyz/t6/702/1570864305x1031866013.png
##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
正常连接资产大概需要几秒？
测试可连接性的问题可能是由于延时太久然后报超时了。

**Comment by BaiJiangJie** [comment]
截图里的授权规则没有取消上传和下载文件的动作，如果想禁用上传/下载功能，请只勾选 “连接”。

**Comment by zxxxxxxd** [comment]
测试连接性的时间能不能更改，因为有些托管的服务器因为机房的网络限制，可能延时会久一点

**Comment by zxxxxxxd** [comment]
在web终端连接服务器时，我看上限好像是10S，这个时间能不能更改，正常的资产大概1-3S左右

**Comment by BaiJiangJie** [comment]
可以修改 apps/assets/tasks/const.py 文件中的：

TASK_OPTIONS = {
    'timeout': 10,
    'forks': 10,
}

timeout 修改的大一些（单位 s），比如修改为 15

备注：不过不建议对其进行修改，因为这个选项会影响 Jumpserver 中其他任务的执行速度
