### ISSUE TITLE
1.5.3 web终端字符乱码问题

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3331]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
1. [web终端乱码问题，在命令行输入中文会显示乱码，有没有什么能切换UTF-8或者默认语言的方式]
2. [通过xshell工具，使用 ssh -p2222 user@IP 的方式可以切换语言]

##### 具体表现[截图可能会更好些,最好能截全]
http://chuantu.xyz/t6/702/1570866851x1033347913.png
http://chuantu.xyz/t6/702/1570866987x1033347913.png
##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
你的服务器资产语言设置是什么？

**Comment by zxxxxxxd** [comment]
默认的是GBK的

**Comment by BaiJiangJie** [comment]
目前还不支持类似 XShell 工具中的设置编码功能，尝试修改资产的系统编码 UTF-8，乱码问题是否可以解决？
