### ISSUE TITLE
1.5.2历史会话中远端地址问题

### ISSUE THREAD

**Issue by Universe91** [jumpserver/jumpserver#3333]
[简述你的问题]
历史会话里显示的远端地址一直是本地，不是登陆用户的IP地址

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. [步骤1]
连接资产
2. [步骤2]
刷新历史会话
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52906754/66699720-a9ca0600-ed1b-11e9-96a6-12141839478f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- 查看一下hosts文件   cat /etc/hosts  
![image](https://user-images.githubusercontent.com/40739051/66734117-7959a780-ee94-11e9-8180-6d67f744f69e.png)

**Comment by Universe91** [comment]
这里的远端地址应该是用户登陆的IP吧，类似日志审计-改密日志中的远端地址，不是指::1
![image](https://user-images.githubusercontent.com/52906754/66734543-1b2dc400-ee96-11e9-9a4c-6efb95ea4d31.png)

**Comment by BaiJiangJie** [comment]
这里需要对 Nginx 配置文件增加一些对应的配置项：
1. HTTP
![image](https://user-images.githubusercontent.com/32935519/66798088-7f589280-ef3f-11e9-956f-bc4416f7b376.png)
2. TCP
![image](https://user-images.githubusercontent.com/32935519/66798115-96978000-ef3f-11e9-9454-e8a8ea50c73f.png)

**Comment by Universe91** [comment]
感谢您耐心的解答，我Http的本身就有这个配置
![image](https://user-images.githubusercontent.com/52906754/66810146-37e2fe00-ef61-11e9-9cd2-535a068b7ada.png)
2222没有设置这个监听，但显示记录是正常的
![image](https://user-images.githubusercontent.com/52906754/66810420-d66f5f00-ef61-11e9-91c5-12e517444220.png)

**Comment by BaiJiangJie** [comment]
从 Web 到 Jumpserver 过程中的每一层 Nginx 配置中都需要添加上面红框中的配置，请检查～
