### ISSUE TITLE
1.5.3 SZ命令下载问题

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3336]
[简述你的问题]

##### 使用版本
[1.5.3]

##### 问题复现步骤
1. [web终端使用sz命令下载文件，并且账号已经授权了下载权限]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
http://chuantu.xyz/t6/702/1571019179x1033347913.png

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
@zxxxxxxd 
是在 web 中操作的吗？

**Comment by zxxxxxxd** [comment]
Web Terminal不能使用命令下载文件吗，只能通过sftp的方式吗，或者使用xshell或者crt之类的软件使用sz命令吗

**Comment by BaiJiangJie** [comment]
Web Terminal 不能使用命令 rz、sz 下载文件，目前只能通过 sftp 方式；
但 Xshell 等命令行工具是可以使用命令 rz、sz 下载文件。
