### ISSUE TITLE
文件夹不存在

### ISSUE THREAD

**Issue by justinmjc** [jumpserver/jumpserver#3340]
[简述你的问题]
step:1 添加资产 linux 服务器。用户可正常登陆资产
step2： 文件管理     10.88.10.59 这个文件夹是自动生成的
               点击此文件 ，报错 文件夹不存在
               点击页面左上方的创建文件夹 或者 文件 都不能创建

感谢！
            
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
v1.5.3
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16958022/66749795-54c5f580-eebd-11e9-8228-393d1435a2ec.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
图中【新文件夹】所在的目录是为了方便用户使用所采用的一种资产显示方式，如果想要创建 文件/文件夹，需要点开资产（例如：10.88.10.59），进入到资产中进行相关操作。

对于此文件夹是自动生成的情况，还不能判断是什么原因所致，刷新一下页面文件夹还存在吗？

**Comment by justinmjc** [comment]
> 图中【新文件夹】所在的目录是为了方便用户使用所采用的一种资产显示方式，如果想要创建 文件/文件夹，需要点开资产（例如：10.88.10.59），进入到资产中进行相关操作。
> 
> 对于此文件夹是自动生成的情况，还不能判断是什么原因所致，刷新一下页面文件夹还存在吗？

感谢您的回复

1‘新建文件夹’ 是我手动创建的，不是自带生产的，只是我手动创建报错

2“如果想要创建 文件/文件夹，需要点开资产（例如：10.88.10.59）”
我就是在左边点击这个资产10.88.10.59 ，然后直接报错文件夹不存在

3是不是我遗漏了什么步骤？
比如要先登录到资产10.88.10.59 ，手动在/tmp 目录下创建 10.88.10.59这个目录？

**Comment by BaiJiangJie** [comment]
> > 图中【新文件夹】所在的目录是为了方便用户使用所采用的一种资产显示方式，如果想要创建 文件/文件夹，需要点开资产（例如：10.88.10.59），进入到资产中进行相关操作。
> > 对于此文件夹是自动生成的情况，还不能判断是什么原因所致，刷新一下页面文件夹还存在吗？
> 
> 感谢您的回复
> 
> 1‘新建文件夹’ 是我手动创建的，不是自带生产的，只是我手动创建报错不能创建
> 
> 2“如果想要创建 文件/文件夹，需要点开资产（例如：10.88.10.59）”
> 我就是在左边点击这个资产10.88.10.59 ，点不开，然后直接报错文件夹不存在
> 
> 3是不是我遗漏了什么步骤？
> 比如要先登录到资产10.88.10.59 ，手动在/tmp 目录下创建 10.88.10.59这个目录？

1. 下图是展示（资产/系统用户/tmp目录）的基本结构，左侧没有上图中的【Home】是因为下图是只针对一个资产进行的 sftp 操作，对我们的问题没有影响。
![image](https://user-images.githubusercontent.com/32935519/66814764-bc397f00-ef69-11e9-9775-0e81d02f3d23.png)

2. 你进行文件操作的目录并不是资产中的 tmp 目录，点开资产（10.88.10.59）应该会列出该资产的 tmp 目录内容（操作如下图）
![image](https://user-images.githubusercontent.com/32935519/66815153-5994b300-ef6a-11e9-8cac-2e491eba1c43.png)

**Comment by justinmjc** [comment]
@BaiJiangJie  问题解决了
应该是我们公司网安部门对那台机器做了特殊限制
我后来又加了一台机器，可以正常打开文件
再次感谢您的协助
