### ISSUE TITLE
1.5.2连接windows问题

### ISSUE THREAD

**Issue by Universe91** [jumpserver/jumpserver#3341]
[简述你的问题]
测试电脑自带的mstsc是可以连接到远程的windows主机，堡垒机连接一直不通。
有2个问题：
1、始终无法连接上，出现如下面第一个图的提示
2、没有测试连接性和刷新硬件配置信息的按钮，如第二张图

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52906754/66793832-ad36da80-ef31-11e9-826e-4b4b0ef56cac.png)
![image](https://user-images.githubusercontent.com/52906754/66793907-f9821a80-ef31-11e9-994c-814e1f44a021.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
针对问题一：
1. 检查 Guacamole 服务状态（查看终端列表中以 [gua] 开头的终端是否在线？）
2. 检查 Windows 服务器中远程连接的设置是否勾选允许任意版本远程桌面的计算机连接（如下图）。
![image](https://user-images.githubusercontent.com/32935519/66796398-1ae70480-ef3a-11e9-8a54-f224b50457e7.png)
3. 如果以上两点都正常，请查看 Guacamole 的日志信息（连接 Windows server 时）。

针对问题二：
目前 Windows 资产还不支持刷新硬件配置信息。

**Comment by Universe91** [comment]
guacamole日志报错如下，
![image](https://user-images.githubusercontent.com/52906754/66812469-84303d00-ef65-11e9-8b55-e3ef4e8fc08f.png)
![image](https://user-images.githubusercontent.com/52906754/66812509-97dba380-ef65-11e9-98a3-705b13082749.png)
请问是和这个key有关吗，如果不重装该如何修改

**Comment by BaiJiangJie** [comment]
看日志有可能是 Guacamole 组件注册不成功。
排查：
查看 Guacamole 组件使用的 BOOTSTRAP_TOKEN 和 Jumpserver 配置文件的 BOOTSTRAP_TOKEN，是否一致；然后将终端列表中的 [Gua] 终端删除；最后重启 Guacamole 组件，查看日志是否注册成功。

**Comment by Universe91** [comment]
删除后重启直接启不起来了，笑哭😂
![image](https://user-images.githubusercontent.com/52906754/66821244-b301df80-ef74-11e9-84d0-76eb15e752ec.png)
![image](https://user-images.githubusercontent.com/52906754/66821256-b7c69380-ef74-11e9-879d-02b71caf8caf.png)

**Comment by BaiJiangJie** [comment]
jumpserver 和 guacamole 的 BOOTSTRAP_TOKEN 一致吗？

**Comment by BaiJiangJie** [comment]
这是心跳的日志，有 Guacamole 注册时的日志吗？

**Comment by Universe91** [comment]
token是一致的
![image](https://user-images.githubusercontent.com/52906754/66881190-a1fab200-eff8-11e9-8feb-10959a04401d.png)

**Comment by BaiJiangJie** [comment]
升级到 1.5.3 版本再看看情况吧
