### ISSUE TITLE
1.5.3 网关服务器跳转问题

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3346]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.3
##### 问题复现步骤
1. [步骤1]
有3台服务器A、B、C，需要从A服务器跳转到B服务器，在从B服务器跳转C
2. [步骤2]
创建网域之后，B服务器能直接登录，有没有能够直接登录C服务器的方法
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zxxxxxxd 在B服务器做一个端口映射，比如把2222映射成C的22端口
访问B的2222端口即为访问C的22端口。
