### ISSUE TITLE
jumpserver1.4没有官方提供的docker镜像?

### ISSUE THREAD

**Issue by funlake** [jumpserver/jumpserver#3347]
[简述你的问题]
公司要过等保3级，明确需要jumpserver 1.4版本，因为你们只有这个版本在公安部那边有销售许可证
www.ispl.cn 这里可以查到
能提供1.4的官方镜像吗？
不行只能自己打镜像了

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@funlake 请使用1.4.8版本，文档里面都有入口说明。
https://docs.jumpserver.org/zh/1.4.8/
