### ISSUE TITLE
关于登录linux服务器本地私钥注册问题

### ISSUE THREAD

**Issue by kun376361** [jumpserver/jumpserver#3349]
[简述你的问题]
登录到linux服务器后能否带上本地私钥，便于在服务器上pull以及push代码库。

##### 问题复现步骤
1. 现在通过jumpserver登录服务器后，在linux服务器上执行ssh-add -l是没有注册私钥的。这样就没有办法pull或者push服务器上代码库，代码库权限通过key管理。同一个服务器账号会有多个人登录，各自使用本地电脑生成的key，不在服务器公共账号生成key。

2. 通过命令行登录ssh admin@192.168.1.100 -A，带上-A参数在服务器执行ssh-add -l可以看到带上本地注册的key到服务器，这样就能够操作代码库。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kun376361 请自行添加，这样的操作可能会产生其他问题。
一般线上服务器拉代码应该有单独设置的共用账户才对。
个人测试代码，请在个人资产上面进行设置
