### ISSUE TITLE
1.5.3 公钥登录服务器

### ISSUE THREAD

**Issue by zxxxxxxd** [jumpserver/jumpserver#3350]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.3
##### 问题复现步骤
1. [步骤1]
使用公钥登录服务器，web端无法连接，在本地服务器ssh可以连接
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
http://chuantu.xyz/t6/702/1571218426x1031866013.jpg

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
web 端无法连接，有具体报错信息吗？

**Comment by wojiushixiaobai** [comment]
@zxxxxxxd jumpserver支持的是私钥连接资产，确定设置无误
