### ISSUE TITLE
1.5.3 无法通过WEB终端连接到资产

### ISSUE THREAD

**Issue by ChampionWolf** [jumpserver/jumpserver#3351]
[简述你的问题]
 无法通过WEB终端连接到资产

##### 使用版本
1.5.3 无法通过WEB终端连接到资产

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
打开web终端一直为此状态：
![image](https://user-images.githubusercontent.com/20255706/66912088-769db480-f044-11e9-87ab-7f53ebbea7e5.png)
容器状态正常：
![image](https://user-images.githubusercontent.com/20255706/66912291-e1e78680-f044-11e9-883e-6a23de57cfb0.png)
终端状态正常，尝试了多次重新注册：
![image](https://user-images.githubusercontent.com/20255706/66912254-d300d400-f044-11e9-9d55-e8cfe84cf3cd.png)
通过查看koko的日志，发现错误：
![image](https://user-images.githubusercontent.com/20255706/66912120-8b7a4800-f044-11e9-9021-838bff015dfa.png)
其他功能正常，通过ssh也可以登录跳板机
![image](https://user-images.githubusercontent.com/20255706/66912190-b1075180-f044-11e9-8b65-a03088d873ac.png)
SFTP也可以正常连接
批量推送命令也正常
只有通过web终端连接Server，连接不上，一直处于黑屏状态

希望帮忙看一下可能的原因，感谢

##### 其他

[注:] 完成后请关闭 issue

**Comment by ChampionWolf** [comment]
补充一下当前的端口监听情况
![image](https://user-images.githubusercontent.com/20255706/66969985-5d394e80-f0be-11e9-920f-ae16e6fd378b.png)

**Comment by ChampionWolf** [comment]
![image](https://user-images.githubusercontent.com/20255706/66971385-97f1b580-f0c3-11e9-9acd-2c2e8e64bcb7.png)
我重启了Docker，没有Ws connection disconnect,但当我luna点击任何一个资产，便会收到以下信息：
2019-10-17 09:49:46 [DEBU] A new ws connection arrive
2019-10-17 09:49:46 [DEBU] Ws connection disconnect

**Comment by ChampionWolf** [comment]
补充，在重启koko后可以看到这样的信息：
![image](https://user-images.githubusercontent.com/20255706/66973797-9cba6780-f0cb-11e9-848d-b6fe9b892f21.png)
另外，Nginx Errorlog中有很多错误信息
![image](https://user-images.githubusercontent.com/20255706/66973891-eb680180-f0cb-11e9-9363-d4d0bf772875.png)

**Comment by ChampionWolf** [comment]
打开WEB终端中的SFTP，也是一样的问题
![image](https://user-images.githubusercontent.com/20255706/66974846-14d65c80-f0cf-11e9-8f2f-b7c065434fa6.png)
综合，我怀疑时WS的问题，但不清楚具体该怎么解决，希望开发大大能帮忙看一下，非常感谢

**Comment by LeeEirc** [comment]
@ChampionWolf  在服务器上执行一下这个命令`setsebool -P httpd_can_network_connect 1`，怀疑是seLinux的策略，阻断了连接。

**Comment by ChampionWolf** [comment]
@LeeEirc  感谢，但我的Selinux早就关掉的。。很奇怪
![image](https://user-images.githubusercontent.com/20255706/66980372-4527f600-f0e3-11e9-9435-54cde6fb720b.png)

**Comment by LeeEirc** [comment]
@ChampionWolf 文件管理直接访问5000端口，会有报错吗？ nginx的配置是什么？

**Comment by ChampionWolf** [comment]
@LeeEirc  因为这个排查太浪费时间了，我重装了系统，现在已经好了，感谢。
