### ISSUE TITLE
1.4.4升级到1.5.3后，Guacamole组件无法注册

### ISSUE THREAD

**Issue by plly0090** [jumpserver/jumpserver#3353]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.3
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
/etc/init.d/guacd start
sh /config/tomcat9/bin/startup.sh
组件无法注册成功。
##### 具体表现[截图可能会更好些,最好能截全]
日志提示：
17-Oct-2019 17:33:57.057 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.26
17-Oct-2019 17:33:57.059 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 16 2019 15:51:39 UTC
17-Oct-2019 17:33:57.059 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.26.0
17-Oct-2019 17:33:57.059 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-693.2.2.el7.x86_64
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_191-b12
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /config/tomcat9
17-Oct-2019 17:33:57.060 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /config/tomcat9
17-Oct-2019 17:33:57.061 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/config/tomcat9/conf/logging.properties
17-Oct-2019 17:33:57.061 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/config/tomcat9
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/config/tomcat9
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/config/tomcat9/temp
17-Oct-2019 17:33:57.062 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
17-Oct-2019 17:33:57.263 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8081"]
17-Oct-2019 17:33:57.282 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
17-Oct-2019 17:33:57.284 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [378] milliseconds
17-Oct-2019 17:33:57.304 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
17-Oct-2019 17:33:57.304 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.26]
17-Oct-2019 17:33:57.320 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/config/tomcat9/webapps/ROOT.war]
17-Oct-2019 17:33:57.949 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2019-10-17 17:33:58.231 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
2019-10-17 17:33:58.291 [main] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
2019-10-17 17:33:58.480 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
2019-10-17 17:33:58.717 [main] INFO  o.a.g.a.j.r.JumpserverRegisterService - 读取Key文件成功
2019-10-17 17:33:58.718 [main] INFO  o.a.g.a.j.r.JumpserverRegisterService - AccessKey验证成功
2019-10-17 17:33:58.917 [Thread-6] INFO  o.a.g.a.j.s.JumpserverSessionService - 开始处理Session队列
2019-10-17 17:33:58.918 [main] INFO  o.a.g.extension.ExtensionModule - Extension "JumpServer Authentication" loaded.
2019-10-17 17:33:58.920 [main] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
2019-10-17 17:33:58.933 [Thread-5] WARN  o.a.g.a.j.r.JumpserverRegisterService - 心跳失败{code:403,result:{"detail":"Invalid signature."}}
2019-10-17 17:33:59.018 [main] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
17-Oct-2019 17:33:59.298 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.RESTExceptionMapper as a provider class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
17-Oct-2019 17:33:59.299 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
17-Oct-2019 17:33:59.302 INFO [main] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
17-Oct-2019 17:33:59.362 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.RESTExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton"
17-Oct-2019 17:33:59.363 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
17-Oct-2019 17:33:59.694 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
17-Oct-2019 17:33:59.697 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
17-Oct-2019 17:33:59.698 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
17-Oct-2019 17:33:59.700 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
17-Oct-2019 17:33:59.701 INFO [main] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"
17-Oct-2019 17:33:59.715 INFO [main] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
17-Oct-2019 17:33:59.728 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/config/tomcat9/webapps/ROOT.war] has finished in [2,408] ms
17-Oct-2019 17:33:59.731 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8081"]
17-Oct-2019 17:33:59.738 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
17-Oct-2019 17:33:59.740 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [2,456] milliseconds
2019-10-17 17:34:08.946 [Thread-5] WARN  o.a.g.a.j.r.JumpserverRegisterService - 心跳失败{code:403,result:{"detail":"Invalid signature."}}

##### 其他

[注:] 完成后请关闭 issue

**Comment by plly0090** [comment]
BOOTSTRAP_TOKEN是一样的

**Comment by BaiJiangJie** [comment]
删除 guacamole 的 key 后重新启动，然后顺便看下 Jumpserver 的日志。

**Comment by plly0090** [comment]
删除guacamole的密钥后重新启动，组件目前已经成功注册
