### ISSUE TITLE
设置命令过滤后，首次登陆无效，过几分钟才生效

### ISSUE THREAD

**Issue by lwx2615** [jumpserver/jumpserver#3357]
[简述你的问题]
设置了一个命令过滤，首次进入web终端，输入
tail  test.php
发现没有过滤，过几分钟之后再输入命令，提示被禁止
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1.  在命令过滤规则中设置一条less .*test.php|vim .*test.php|head .*test.php|tail .*test.php|vi .*test.php|cat .*test.php
2.  点击web终端
3.  在web终端输入 tail  test.php
4.  更换浏览器登录后第一次输入过滤命令没过滤，第二次才生效。
5.  绑定的机器表现不一致，有的机器相互切换命令会一直不生效，当连续执行命令时才会过滤生效，如下图所示
##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/2578319/67077231-5f380600-f1c1-11e9-9b1b-cf574ed14f71.png)
![图片](https://user-images.githubusercontent.com/2578319/67085308-2c960980-f1d1-11e9-8cf9-a440ea7c9828.png)

##### 其他
在设置新规则，修改规则时也有这种情况出现

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
试过重启 coco 吗？

**Comment by lwx2615** [comment]
> 
> 
> 试过重启 coco 吗？

没有，我用的是docker启动的整合在一起的服务。应该不是等待几分钟，是第一次不生效。第二次才生效。两个命令切换的时候也没有生效。只有连续两次命令一样的时候后面的才生效。本来过了一个周末，打开看，而且新建一个规则，开始的时候竟然不能复现，表现的很正常。过了一段时间，又可以复现，和原来的情况一样。

**Comment by ibuler** [comment]
```
less .*test.php|vim .*test.php|head .*test.php|tail .*test.php|vi .*test.php|cat .*test.php
```

这个规则的类型是命令还是正则表达式？

**Comment by BaiJiangJie** [comment]
这个可能是之前版本的 bug，建议您升级到 1.5.4 版本使用。
1.5.4 相对于 1.5.2 使用 koko 替换了 coco 的功能，性能和使用上有比较大的优化。

**Comment by lwx2615** [comment]
![图片](https://user-images.githubusercontent.com/2578319/67538174-e7ae2d80-f710-11e9-9987-478dbbddcc44.png)

**Comment by lwx2615** [comment]
> 
> 
> 这个可能是之前版本的 bug，建议您升级到 1.5.4 版本使用。
> 1.5.4 相对于 1.5.2 使用 koko 替换了 coco 的功能，性能和使用上有比较大的优化。

![图片](https://user-images.githubusercontent.com/2578319/67538276-512e3c00-f711-11e9-95ba-ed749e54c0a3.png)
升级到了1.5.4版本，问题仍然存在，这次的测试比较有意思，开始的时候vi，vim都是禁止的，less，tail，cat这些命令都没有禁止。然后执行了几波tail，less之后，vi又可以打开了。
![图片](https://user-images.githubusercontent.com/2578319/67538462-b7b35a00-f711-11e9-977a-68114c0731f2.png)
然后任务列表显示全部失败，但实际上我这边终端都可以连上

**Comment by ibuler** [comment]
太久远版本的问题了，暂时归档，如果新版本依然有，请重新打开issue, 会协助处理
