### ISSUE TITLE
python 如何登录 jumpserver ，连接服务器，发送shell 命令？

### ISSUE THREAD

**Issue by lhsaq2009** [jumpserver/jumpserver#3361]
python 如何登录 jumpserver ，连接服务器，发送shell 命令？

**Comment by lhsaq2009** [comment]
# 需求
最近捣鼓Python 连接服务器，然后本地 拼装zgrep 等命令，发送目的服务器，查询日志并返回。
但是中间有个跳板机(跳板机)，用的 jumpserver，

# 问题
现在没有解决python 通过 jumpserver，连接服务器。

请求指导。

**Comment by BaiJiangJie** [comment]
目前不支持使用 Python 代码连接 Jumpserver 里的服务器
