### ISSUE TITLE
jumpserver Restful api 升级到1.5.3后调用资产删除接口失败

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#3362]
jumpserver Restful api  之前。1.5.2版本都使用正常，1.5.3接口有改动，例如创建资产由之前的批量创建和单台合并成一个接口了。但是删除资产的接口改动的不知道怎么传值。在docs页面测试无法删除。1.5.2之前用delete方法调用api/v1/assets/assets/?hostname=x.x.x.x就可以删除了。现在这样调用则报错。没有具体的接口问题调用说明，突然就不能用了。基本用接口来批量同步资产和删除资产都是经常需要使用的，能否给个调用方法示例，更新有修改能否说明下了。目前无法通过api删除资产，请问需要怎么传值
![image](https://user-images.githubusercontent.com/46477158/67138740-6707b100-f27a-11e9-86e2-26e179edf1b3.png)
@BaiJiangJie

**Comment by BaiJiangJie** [comment]
1.5.3 版本不允许以下方式删除资产
DELETE /api/v1/assets/assets/?hostname={HOSTNAME}
可以调用下面的 API 进行删除
DELETE /api/v1/assets/assets/{HOST_ID}/

**Comment by huangpeng0817** [comment]
> 1.5.3 版本不允许以下方式删除资产
> DELETE /api/v1/assets/assets/?hostname={HOSTNAME}
> 可以调用下面的 API 进行删除
> DELETE /api/v1/assets/assets/{HOST_ID}/

那就是只能是先查询获取到id值后拿id去删除咯。也不能批量删除了对吧。docs里面的文档，一点说明都没有，接口方法又保留在，却不能用。。

**Comment by BaiJiangJie** [comment]
对，先查询资产id，再进行删除。
API 批量删除禁用了，但 Web 页面可以对资产进行批量删除。

**Comment by huangpeng0817** [comment]
> 对，先查询资产id，再进行删除。
> API 批量删除禁用了，但 Web 页面可以对资产进行批量删除。

好吧。更新之后突然接口不能用。都炸了。。
