### ISSUE TITLE
vim协议特殊字符匹配

### ISSUE THREAD

**Issue by ivanjoy42** [jumpserver/jumpserver#337]
self.vim_end_pattern = re.compile(r'\x1b\[\?1049', re.X)
这句中的\x1b是esc，请问\[\?1049是什么字符？

**Comment by ivanjoy42** [comment]
google查到了，改变xterm模式

能否使用[?1049h和[?1049l判断vim开始和结束呢？

修改vim判断模式：
[https://github.com/jumpserver/jumpserver/pull/338](https://github.com/jumpserver/jumpserver/pull/338)

**Comment by ibuler** [comment]
vim里面也可以执行命令，这些命令也需要审计

**Comment by ivanjoy42** [comment]
现在的判断是\x1b[?1049，我写的判断是\x1b[?1049h。如果vim里面执行了\x1b[?1049h，那么必然也执行\x1b[?1049了。

**Comment by ivanjoy42** [comment]
看一下代码吧https://github.com/jumpserver/jumpserver/pull/338/commits/60656522dcff7eaaa8c145b4a263f45f7ff842f8
self.vim_data变量记录了大量的数据，但是这些数据并没有写入数据库，而是用于判断当前是否为vim状态。
你可以测试一下，原来的程序也没有记录vim里面执行的命令。

**Comment by ibuler** [comment]
你在公司测试一下，使用一阵，看看有没有问题
