### ISSUE TITLE
使用web终端进入服务器后，服务器编码为zh_CN.gbk,然后切换用户后中文显示乱码

### ISSUE THREAD

**Issue by jetyte** [jumpserver/jumpserver#3371]
[简述你的问题]
1、使用web终端进入服务器后，服务器编码为zh_CN.gbk,然后切换用户后中文显示乱码，并且点击了语言选择中文或者英文，效果都是一样，还是乱码。
2、添加windos资产，发现可连接状态一直都是红色或者黄色，但是授权给用户后，却可以web终端访问。
##### 使用版本
使用的Jumpserver版本1.5.3-101

##### 问题复现步骤
1. [步骤1]
使用web终端进入服务器后，服务器编码为zh_CN.gbk。然后切换用户后中文显示乱码。
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/38210885/67348503-b817ed80-f577-11e9-8845-ac5a25398c11.png)

1. [步骤1]
添加windos资产，发现可连接状态一直都是红色或者黄色，但是授权给用户后，却可以web终端访问。
首先添加了管理用户
![image](https://user-images.githubusercontent.com/38210885/67348624-0dec9580-f578-11e9-9e23-d725ceaaa5de.png)

添加系统用户
![image](https://user-images.githubusercontent.com/38210885/67348660-2d83be00-f578-11e9-8023-28deb8ef384c.png)

添加win资产
![image](https://user-images.githubusercontent.com/38210885/67348715-615ee380-f578-11e9-9107-2bef538526e8.png)

发现可连接状态一直都是红色
![image](https://user-images.githubusercontent.com/38210885/67348767-8fdcbe80-f578-11e9-9b21-ecf38e662e2f.png)

[注:] 完成后请关闭 issue

**Comment by jetyte** [comment]
补充一下：
![image](https://user-images.githubusercontent.com/38210885/67348885-e8ac5700-f578-11e9-92e5-3c323c3aa747.png)

**Comment by ibuler** [comment]
1. 编码问题已知，后续解决
2. windows是可连接性测试，需要windows安装openssh，否则不探测是黄色

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by jetyte** [comment]
编码问题已解决？

**Comment by frozenpine** [comment]
同问，什么时候能支持GBK或者GB18030字符编码

**Comment by wuqiang3424** [comment]
同问，已用2.1版本，编码还是无法设置，老难受了
