### ISSUE TITLE
Web网站可以作为资产吗？登录jumpserver后直接访问内网的网站。

### ISSUE THREAD

**Issue by immikez** [jumpserver/jumpserver#3372]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不可以
