### ISSUE TITLE
是否支持ssh port forward

### ISSUE THREAD

**Issue by hackrole** [jumpserver/jumpserver#3382]
你好，我们这边处理每次要登陆jumpserver, 跳转到代码机器A，在代码机器上才能访问阿里与RDS.
这样我需要写些代码拉数据库数据时就必须把代码写好放到A,在去执行。如果代码有问题，调试很麻烦，以前有陪过ssh port forward, 可以把本地端口转发到远程机器上，调试和开发都很方便。
```
# ssh-config
Host jump
       Hostname jumpserver
       User me
       IdentityFile ~/.ssh/id_rsa
Host ahost
       HostName AHost
       User me
       IdentityFile ~/.ssh/id_rsa
       ProxyCommand ssh jump %h %p

# shell command
ssh -NL 3307:<RDS-ip>:3306 ahost
```

**Comment by BaiJiangJie** [comment]
您好：
你觉得基于上面描述的情况，怎么样操作比较方便呢？或者能具体描述一下你的需求吗？

**Comment by BaiJiangJie** [comment]
好的，大致了解清楚了。
不过，因为考虑到 Jumpserver 的审计操作和其他方面的一些功能，目前还不能够支持 SSH PORT FORWARDING 这种服务器连接模式。

**Comment by hackrole** [comment]
好的，理解
