### ISSUE TITLE
tty.setraw(sys.stdin.fileno())和tty.setcbreak(sys.stdin.fileno())具体是什么作用？

### ISSUE THREAD

**Issue by crone77** [jumpserver/jumpserver#3384]
[简述你的问题]
我查看jumpserver的连接模块的代码，不懂tty.setraw(sys.stdin.fileno()和tty.setcbreak(sys.stdin.fileno())是干什么用的，辛苦作者解答下

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
连接模块的代码指的是哪个？

**Comment by ibuler** [comment]
https://docs.python.org/zh-cn/3/library/tty.html
