### ISSUE TITLE
删除系统用户时，会误删除掉其它前缀匹配的系统用户sudo权限

### ISSUE THREAD

**Issue by changxy726** [jumpserver/jumpserver#339]
/etc/sudoers配置文件内容
wangxiaotian        ALL=(ALL)       NOPASSWD: ABC
wangxiao              ALL = (root)     NOPASSWD: ABC
在管理页面上删除系统用户wangxiao， 那么wangxiaotian的sudo配置行也被删了

看源代码就是sed替换 前缀.*     就是这样设计的么？

版本master commit 4b593e56f9e097f5329b57b43e58b427990b6a4e

**Comment by colinlabs** [comment]
我也被这个坑过，导致大量配置被删除

**Comment by ibuler** [comment]
新版本删掉了删除系统用户功能
