### ISSUE TITLE
[建议] Windows 资产认证增加 `默认系统用户` 绑定

### ISSUE THREAD

**Issue by tupunco** [jumpserver/jumpserver#3390]
[简述你的问题]
Windows 资产安全期间会设置不同的 `系统用户` 密码, 所以需要建了很多 `系统用户`.
如果一个 `用户` 需要管理很多 WIndows 资产, 需要把对应的 `系统用户` 都分配给相应 `用户`.
在 `Web 终端` 选择 `Windwos` 资产的时候, 会弹出一个巨长的 `下拉框` 来选择对应 `系统用户`, 并滚动查找对应的 `系统用户`.

如果在 `Windows 资产`  编辑页面直接提供类似于 `认证->管理用户` 这样的绑定, 并提供 `多绑定`,  其次 `Web 终端`  所弹出的  `系统用户` 选择对话框默认对应当前用户 `有权限` 的已绑定的 `系统用户`, 减少选择的繁琐, 感觉是一个不错的体验.
另外  `Web 终端`  弹出的  `系统用户`  选择对话框对于存在大量 `系统用户` 情况可以做几个优化:
1. 数量大于某个阈值, 提供一个搜索框.
2. 数量大于某个阈值, 提供翻页功能.

##### 使用版本
Version 1.5.4-2 GPLv2.

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@tupunco 仔细的看了下你的描述，你的问题应该是授权错误，你应该单独对没一个资产授权，而不是一个授权里面包含了100台资产和100个系统用户
或者手动登录用户自己输入密码即可

**Comment by tupunco** [comment]
@wojiushixiaobai `资产授权` 内允许选择 `单用户->多资产+多系统给用户` 的授权策略, 我的使用方法应该没有错误.
如果一个 `用户` 需要对 `N 个资产` 有权限, 做 `N 条` 授权, 这样跟上面的规则有冲突. 有简单的方法授权, 为什么使用复杂的方式.
`使用堡垒机` 有个很重要的 `策略` 就是不希望 `用户` 知道 `被管理资产的真实密码`, 资产密码周期性更换, 不需要通知用户. 所以让用户输入密码的方式不可取.

**Comment by BaiJiangJie** [comment]
资产授权规则提供 `多资产 + 多系统用户 -> 单用户` 的授权策略，比较合适的使用场景（隐含的使用规则）是：
一条授权规则中的 资产 和 系统用户（无论单个/多个），最好是有实际关系的（即：这些系统用户在这些资产上都是真实存在的，登录的时候也确实需要）

如果授权多个资产，同时也把多个资产上的系统用户都添加到一个授权规则中，那么在后期管理起来就会显得不方便，使用起来也会变得冗余。

对于你提出来的建议，其实是资产授权规则的另一个作用，就是将资产和系统用户进行绑定，这样不是更灵活吗？

**Comment by tupunco** [comment]
@BaiJiangJie 我可能没有描述清楚环境:
1. 每个 `资产` 只有一个 `系统用户`,  `不是` 一个` 资产` 有多个 `系统用户`.
2. 一个 `用户` 需要管理多个 `资产`.
3. 希望一条 `资产授权` 规则把 `多个资产` 授权给一个 `用户`, 那么每个 `资产` 的 `系统用户` 都需要授权给 `用户`.

如果 `正确` 的使用 `资产授权` 流程为 `下面` 的方式:

a. 前提工作: 添加相关 `系统用户`,  添加 `资产`,  添加 `用户`.
b. 给每个 `资产`  加一个 `系统用户` 的是 `资产授权`
c.  给需要管理多个 `资产` 的 `用户` 加一条 `资产授权`

感觉 `b` 步骤有点冗余, 假如把这步放到添加 `资产` 的 `认证->系统用户` 是不是显得更便捷? 或者在 `资产->认证->系统用户` 这步操作后 `自动生成` 一条跟 `b` 操作一致的 `资产授权` 规则是不是也可以?
