### ISSUE TITLE
docker hub上【woshixiaobai】和【jumpserver】有什么关系

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#3394]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.3 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

docker hub上搜索，有一个用户叫【woshixiaobai】，有一个用户叫【jumpserver】，请问这两个用户有什么关系，为什么【woshixiaobai】里面的镜像比【jumpserver】的还要新，哪一个是官方的。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
之前 @wojiushixiaobai 没有 jumpserver这个仓库的权限，后来加了，现在由 **小白** 统一维护

**Comment by leim** [comment]
现在【woshixiaobai】这个仓库下的jms_core版本已经更新到了1.5.4 （10月24号更新），但是【jumpserver】下的jms_core版本仍然还是1.5.3（9月26号更新）

**Comment by wojiushixiaobai** [comment]
@leim 抱歉，wojiushixiaobai/jms_core 是 docker-compose 里面的镜像，jumpserver/jms_core 其实和 jumpserver/core 重复了，所以之前没有设置autobuild，我刚才出现build了一下，如果有需要的话你可以更新一下。

**Comment by leim** [comment]
感谢
