### ISSUE TITLE
ssh终端批量执行命令和上传下载文件

### ISSUE THREAD

**Issue by pc10201** [jumpserver/jumpserver#3398]
[简述你的问题]

在0.3.2的版本中
ssh登陆后，有批量执行命令和上传下载文件的功能

我新部署了一套1.5.4的版本
ssh登陆后，发现这些功能消失了
只能在web端使用吗？

##### 使用版本
1.5.4

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
1.5.4 版本批量命令只能在 Web 端使用，上传下载文件可以在 Web 端使用，也可以通过 sftp 命令使用。
