### ISSUE TITLE
邮件不发送

### ISSUE THREAD

**Issue by marginheart** [jumpserver/jumpserver#3399]
[简述你的问题]
测试邮件可以正常发送， 创建用户，找回密码等日志均提示发送成功，但是未发送邮件

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
版本“：Version 1.5.4-2 GPLv2 
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/17331107/67828288-d2207580-fb0d-11e9-8217-2fe9583c233c.png)

![image](https://user-images.githubusercontent.com/17331107/67830077-5a097e00-fb14-11e9-9ae0-b1ab82c7ab40.png)

**Comment by BaiJiangJie** [comment]
在找回密码或是创建用户的时候，多截一些日志。

**Comment by zhouyuyong** [comment]
遇到同样的问题,测试可以通过,但是无法收到重置邮件  版本1.5.4

**Comment by BaiJiangJie** [comment]
查看日志文件 logs/celery_default.log

**Comment by zhouyuyong** [comment]
> 查看日志文件 logs/celery_default.log

我使用tail -f 实时监控这个文件的内容变化,  当我点击重置时 ,此文件没有发生任何变化

**Comment by Yiipanny** [comment]
我也遇到了和楼主一模一样的问题，收不到邮件

**Comment by xiaochaohasun** [comment]
和楼主一样的问题， 版本 1.5.3  请问，有解决方案了吗？

**Comment by eagleye1115** [comment]
和楼主一样的问题,版本1.5.4 
celery日志都是空的

**Comment by xiaochaohasun** [comment]
问题已解决，登录redis库3号库的celery key队列拥堵，执行bgsave，重启redis,然后重启jms。

**Comment by eagleye1115** [comment]
> 问题已解决，登录redis库3号库的celery key队列拥堵，执行bgsave，重启redis,然后重启jms。

使用同样的办法,问题依旧

**Comment by marginheart** [comment]
我这里恢复了，具体原因不知。 我在 jumpserver/apps/jumpserver/settings.py中添加了邮箱的相关信息，然后我想看邮件发送的调用在  jumpserver/apps/common/task.py中添加了邮件内容写入到文本中，然后重启自行恢复了。感觉是有时发送邮件并没有调用到发送邮件的方法，只是生成了日志内容并写入了日志。
![image](https://user-images.githubusercontent.com/17331107/69121305-f4872c80-0ad6-11ea-9381-c85dd051c0b0.png)
