### ISSUE TITLE
选择资产组推送用户失败的问题

### ISSUE THREAD

**Issue by jevic** [jumpserver/jumpserver#340]
1. 在推送用户时,有时候回出现推送失败提示，但是主机中却已经创建了该用户；
2. 推送用户，选择资产组会导致网页直接卡死，这个问题之前有仁兄提出但是现在依旧如此；
3. 在使用批量导入的时候  提交模板文件会报错；

**Comment by jiangtao007** [comment]
我推送用户也是这样，但是用户已经成功建立，提示有错误
![image](https://cloud.githubusercontent.com/assets/26705490/24584337/1fb12472-179d-11e7-90af-b86e605f24c3.png)

**Comment by nevfo** [comment]
我推送新用户的时候,如果资产里面的管理账户是其他用户带sudo权限,就会卡死.  但如果是root,就不会卡死,这个有人知道怎么回事吗?

**Comment by jiangtao007** [comment]
推送用户时，我用的是root推送的，其他用户没有试过。我猜是其他用户（有sudo权限）并没有实际添加成功用户吧？回头我也实验看看。
