### ISSUE TITLE
通过VNC协议能正常连接 Windows ，但不能上传下载文件，拖拽文件后提示不支持或未启用

### ISSUE THREAD

**Issue by guoshuaifeng** [jumpserver/jumpserver#3401]
[简述你的问题]
通过VNC协议能正常连接  Windows，
但无法上传下载文件，拖拽文件后提示不支持或未启用。
单独使用VNC客户端远程连接目标是可以互传文件的。

##### 使用版本
[1.5.4-2 ]

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/17470757/67840127-22103400-fb30-11e9-9e84-b56311745b2e.png)

![image](https://user-images.githubusercontent.com/17470757/67834785-4580b200-fb23-11e9-8daf-94cf6659ce88.png)

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
目前还不支持通过 VNC 连接，上传/下载 文件。

**Comment by guoshuaifeng** [comment]
明白了，谢谢！
多问一句，是 guacamole 自身不支持，还是哪些参数没配置到位？

**Comment by guoshuaifeng** [comment]
> 目前还不支持通过 VNC 连接，上传/下载 文件。

明白了，谢谢！
多问一句，是 guacamole 自身不支持，还是哪些参数没配置到位？
