### ISSUE TITLE
无法使用批量删除资产

### ISSUE THREAD

**Issue by pc10201** [jumpserver/jumpserver#3402]
[简述你的问题]

无法使用批量删除资产的API接口
{jumpserver_url}/api/v1/assets/assets/
返回400错误

web端也不能批量删除，只能分批操作

##### 使用版本
1.5.4

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
资产的批量删除，做了限制，只能通过 Web 端删除
