### ISSUE TITLE
多个终端登陆JMS，不能同时登陆同一台设备

### ISSUE THREAD

**Issue by wangmingming19880605** [jumpserver/jumpserver#3407]
[简述你的问题]
比如，两个都登录了JMS，想要同时登陆某一台交换机，第一个登录交换机的人正常，第二个登录交换机的会不能登录，并且JMS界面自动关闭

##### 使用版本
docker部署
版本：1.5.2

##### 问题复现步骤
1. 使用CRT登录JMS，然后登陆一台交换机
2. 使用CRT新开一个页面，登录JMS，也去登录这台交换机，此时不能登录，并且JMS登录被迫中断

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/55092797/68017076-da74de00-fcd0-11e9-9190-c5c88a9ac8fa.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
docker部署的是koko还是coco？任何部署的？交换机是否有限制？

**Comment by wangmingming19880605** [comment]
> 部署

docker all in one部署，docker内部是coco，交换机确认是没有限制的，特定测试过。

**Comment by LeeEirc** [comment]
@wangmingming19880605  除了利用CRT，使用其他ssh终端连接也会出现这样的情况吗？分别使用两个不同SSH终端去连接呢，例如xshell和CRT？

**Comment by wangmingming19880605** [comment]
> @wangmingming19880605 除了利用CRT，使用其他ssh终端连接也会出现这样的情况吗？分别使用两个不同SSH终端去连接呢，例如xshell和CRT？

一样的，刚刚测试了下，一台PC开CRT，一台PC开XSHELL，一样的情况。。

**Comment by LeeEirc** [comment]
@wangmingming19880605 看一下coco的日志有什么报错信息吧。

**Comment by wangmingming19880605** [comment]
/opt/coco/data/logs/coco-50b2883a8c15.log，没有刚刚出错的日志，最早的日志是11月02日

需要修改日志level吗

**Comment by ibuler** [comment]
新版koko已解决该问题
