### ISSUE TITLE
如何手动解锁账户

### ISSUE THREAD

**Issue by brucegogo** [jumpserver/jumpserver#3410]
[简述你的问题]
我设置了连续3次登录失败就禁止登录30分钟。
有时候用户比较着急，我想手动给他解锁，请问怎么弄？

##### 使用版本
Version 1.4.6-2 GPLv2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
使用脚本解锁：
sh   {项目目录}/utils/unblock_all_user.sh
