### ISSUE TITLE
资产连接异常

### ISSUE THREAD

**Issue by zhouyuyong** [jumpserver/jumpserver#3411]
[简述你的问题]
使用web 终端连接linux服务器时,出现个别用户无法连接,查看授权规则无错误,同授权规则下其他人都可以正常登录, 提示错误信息为:error: ssh: rejected: administratively prohibited(open failed)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.3 koko使用容器方式部署

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by AsherBoone** [comment]
遇到同样问题，且多次出现。删除用户重建就好了。不知道哪里的问题。望修复

**Comment by LeeEirc** [comment]
应该是连接复用造成的，可升级到最新的1.5.4。

**Comment by zhouyuyong** [comment]
> 应该是连接复用造成的，可升级到最新的1.5.4。

@LeeEirc 版本升级到1.5.4 依然有这个问题, 发现有问题的资产中存在很多sftp-server的进程, 杀掉这些sftpd的进程后,可以连接了
![选区_026](https://user-images.githubusercontent.com/7124402/68283698-f86a8600-00b6-11ea-9eee-17f4725be4b1.png)

**Comment by LeeEirc** [comment]
@zhouyuyong 能否核实一下，是koko未释放sftp连接，还是用户建立了大量的sftp连接。sftp和ssh复用连接的情况下，都是用的同一个client。

**Comment by zhouyuyong** [comment]
@LeeEirc  查看了一下koko的连接情况发现,同一资产下,1)有几个在线的用户就会有几个ssh连接,2)当使用'文件管理'进行上传下载时每打开一个新的窗口此资产下就会新产生一个sftp-server进程 3) 正常关闭'文件管理'窗口,资产内会对应结束sftp-server 4)在资产内查看会发现一些过期的sftp-server进程,如图,
![选区_027](https://user-images.githubusercontent.com/7124402/68356286-d4598400-014c-11ea-8987-b9aab330db28.png)
第一和第二个sftp进程,怀疑为异常进程,在'在线会话'页面未发现对应的会话 如图
![选区_028](https://user-images.githubusercontent.com/7124402/68356483-6d889a80-014d-11ea-9eb7-424737a83477.png)
同时在koko容器中的连接 如图
![选区_029](https://user-images.githubusercontent.com/7124402/68356647-ce17d780-014d-11ea-8cf8-11816bb0cc75.png)

每次发生异常时 都是无例外出现大量sftp-server的进程,当kill掉这些进程,连接恢复正常, 当前在所维护的系统中暂时没有发现正在处于异常的连接,无法提供异常现场数据,如再次发生会进行补充

**Comment by wojiushixiaobai** [comment]
@zhouyuyong 更新到1.5.4再试试看

**Comment by xuqing** [comment]
版本1.5.4-101 问题依旧

**Comment by KeithTt** [comment]
Same problem in Version 1.5.4-2 GPLv2.

**Comment by tonny008** [comment]
Version 1.5.6-2 GPLv2 问题还没修复

**Comment by LeeEirc** [comment]
如果坚持使用 v1.5.x的版本，请升级到v1.5.9的版本。
