### ISSUE TITLE
koko CPU打满

### ISSUE THREAD

**Issue by wzhlinux** [jumpserver/jumpserver#3412]
[简述你的问题]

##### 使用版本
1.5.2

##### 问题复现步骤
1. top查看硬件状态，CPU呗koko打满
2. 运行时间两个月
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26629417/68121825-b79e3000-ff43-11e9-8eab-378b64159f9b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@wzhlinux 感谢你的反馈，koko近期修复了部分引发cpu高的问题。请更新使用最新的1.5.2镜像。
