### ISSUE TITLE
koko 用户

### ISSUE THREAD

**Issue by hsggj002** [jumpserver/jumpserver#3415]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
问题描述不完整，请修改后重新打开
