### ISSUE TITLE
使用中突然批量命令无法执行

### ISSUE THREAD

**Issue by wzhlinux** [jumpserver/jumpserver#3419]
[简述你的问题]

##### 使用版本
1.5.4

##### 问题复现步骤
1. 使用中查看用户资产时出现了一个资产节点，无法删除
2. 批量命令目前无法执行，没有执行结果

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26629417/68280097-d4577680-00af-11ea-8974-0e5b34309802.png)
![image](https://user-images.githubusercontent.com/26629417/68280118-de797500-00af-11ea-9f50-57b5421179f9.png)
![image](https://user-images.githubusercontent.com/26629417/68280170-f8b35300-00af-11ea-81f3-45d905c88543.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wzhlinux** [comment]
目前jump中的服务器都可以连接，使用正常。唯独ansible批量命令不能使用

**Comment by wzhlinux** [comment]
![image](https://user-images.githubusercontent.com/26629417/68288196-ec82c200-00be-11ea-99cd-e2ea535b1255.png)

**Comment by wojiushixiaobai** [comment]
@wzhlinux 任务进程出现故障，可以尝试重启jumpserver解决，如果重启不行，请kill掉进程后，重启即可
