### ISSUE TITLE
create table Warning

### ISSUE THREAD

**Issue by keryoo** [jumpserver/jumpserver#342]
_mysql_exceptions.Warning: Incorrect string value: '\xE6\x9C\xBA\xE6\x88\xBF' for column 'name' at row 1

**Comment by ibuler** [comment]
创建数据库时，字符集使用 utf-8

`create database jumpserver default charset utf8`

**Comment by keryoo** [comment]
ok  tks

**Comment by calistochen** [comment]
对

**Comment by sogog** [comment]
_centos6_
/etc/my.cnf
加入
```
[client]
default-character-set = utf8

[mysqld]
default-storage-engine = INNODB
character-set-server = utf8
collation-server = utf8_general_ci
```
重启mysql
