### ISSUE TITLE
其他系统如何跳转到jumpserver的web终端

### ISSUE THREAD

**Issue by DamaoShao** [jumpserver/jumpserver#3423]
我现在运维使用一个可以自动创建虚拟机的系统，每次创建完一个虚拟机后，手动添加到jumpserver，然后使用jump server中的web终端功能。

但有时候，我创建完虚拟机后，想立刻用web终端，上面的流程，就有点麻烦orz
所以我想运维系统创建完虚拟机后，通过api，将虚拟机信息添加到jumpserver中，
然后**在运维系统上加一个按钮，点这个按钮，可以跳转到jumpsever对应虚拟机的web终端里面**

请问加黑的部分，可以实现嘛，如何实现会比较好？
谢谢

**Comment by DamaoShao** [comment]
或者是虚拟机通过api加入jumpserver，可以生成一个链接来进入虚拟机的web终端中。

**Comment by wojiushixiaobai** [comment]
@DamaoShao https://你的jumpserverurl地址/luna/?login_to=资产id
即可

**Comment by DamaoShao** [comment]
Thanks!
