### ISSUE TITLE
批量命令提示权限 too open

### ISSUE THREAD

**Issue by ypoison** [jumpserver/jumpserver#3425]
[简述你的问题]
批量命令提示权限 too open, 但是是临时产生文件也无法去修改其权限。
使用的是密码方式登陆

##### 使用版本
1.5.4

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/19726736/68560466-2c112b80-047c-11ea-88a7-40f252e0b3d5.png)

**Comment by wojiushixiaobai** [comment]
@ypoison jumpserver 文件夹权限
jumpserver/tmp 文件夹权限
jumpserver 运行的用户，都检查下

**Comment by ypoison** [comment]
@wojiushixiaobai root用户运行，现在是新建的临时key文件权限为0444， 通过手动修改文件权限为600后可以运行
![image](https://user-images.githubusercontent.com/19726736/68586924-bd09f600-04c0-11ea-92c2-155813e80022.png)

**Comment by wojiushixiaobai** [comment]
@ypoison 测试了下，目前无法复现此情况，如果可以的话请换个测试环境验证下。
