### ISSUE TITLE
按照官方文档自建服务器极速安装,启动报错ModuleNotFoundError: No module named 'daemon'

### ISSUE THREAD

**Issue by dongdarui** [jumpserver/jumpserver#3431]
安装最新版的，执行./jms 报错
  File "./jms", line 16, in <module>
    import daemon
ModuleNotFoundError: No module named 'daemon'

请问什么原因

**Comment by dongdarui** [comment]
之前下载组件有个报错，不知道是不是这个影响
ERROR: pyasn1-modules 0.2.7 has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.4.2 which is incompatible.
ERROR: django-radius 1.3.3 has requirement future==0.16.0, but you'll have future 0.18.2 which is incompatible.
ERROR: autobahn 19.11.1 has requirement cryptography>=2.7, but you'll have cryptography 2.3.1 which is incompatible.

**Comment by hansenshi** [comment]
jms[27894]: File "/opt/jumpserver/jms", line 16, in <module>
jms[27894]: import daemon
jms[27894]: ModuleNotFoundError: No module named 'daemon'
遇到同样的问题

**Comment by lnanhao** [comment]
Traceback (most recent call last):
  File "./jms", line 16, in <module>
    import daemon
ModuleNotFoundError: No module named 'daemon'
--------------------
同样问题，python-daemon有正常安装，暂未找到解决办法

**Comment by seokwong** [comment]
https://jumpserver.readthedocs.io/zh/master/faq_core.html#jms-core
官方文档有解决办法
