### ISSUE TITLE
sudoers not work

### ISSUE THREAD

**Issue by mousazade** [jumpserver/jumpserver#3432]
jumpserver 1.4.5

1-Difficulty setting sudoers through the panel :
Values ​​that are allowed in sudo are added in tandem or below, but the user still cannot use the command added with sudo.
Only the "Whoami" command works

Please guide me to these problems so I can use this service

Thanks

**Comment by wojiushixiaobai** [comment]
@mousazade 
You can click Update on the web page - Asset - system user - your system user

see:
![1](https://user-images.githubusercontent.com/24326988/68823391-96b9a580-06ce-11ea-848a-7e68a8cd841c.jpg)

**Comment by mousazade** [comment]
Please provide a solution other than ALL 
example :
only sudo command (vim,fdisk,rm)

**Comment by wojiushixiaobai** [comment]
@mousazade 
You can log in to your asset and use the which command to query the specific path, such as 
````
which vim
which <command>
````

/bin/vim,/sbin/fdisk,/bin/rm
![2](https://user-images.githubusercontent.com/24326988/69001441-2b174880-0919-11ea-8a40-8693b525d06b.jpg)
