### ISSUE TITLE
assets.backends.base代码错误

### ISSUE THREAD

**Issue by caostorm** [jumpserver/jumpserver#3436]
[简述你的问题]
master分支的最新版本代码
apps/assets/backends/base.py
的57行应该有误，会导致需要全字符串匹配才能正常运行。
尚未确认其他分支版本是否存在该问题。

**Comment by BaiJiangJie** [comment]
什么情况下会报错，另外截图一下错误信息。

**Comment by caostorm** [comment]
不会报错，但是assets.backends.base.AssetUserQuerySet.filter_in()这个函数会失效，你可以单独对这个函数进行单元测试。

**Comment by BaiJiangJie** [comment]
可以展示一下你的测试用例吗？

**Comment by BaiJiangJie** [comment]
这个问题的另一中描述是：对资产用户列表不支持模糊搜索，对吗？
