### ISSUE TITLE
Jumpserver 1.5.2-2 Bug:添加资产授权是忘记勾选资产保存后无法再次编辑

### ISSUE THREAD

**Issue by careylipu** [jumpserver/jumpserver#3437]
[简述你的问题]

##### 使用版本
1.5.2-2

##### 问题复现步骤
1. [步骤1] 添加资产授权是忘记勾选资产保存
2. [步骤2]无法再次编辑

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/15045646/68841218-2f681980-06ff-11ea-8796-fd87bd9117bb.png)

##### 其他
Jumpserver Bug 添加资产授权是忘记勾选资产保存后无法再次编辑
解决办法手动插入对应的记录，之后才可以恢复编辑
INSERT INTO perms_assetpermission_assets (assetpermission_id,asset_id) VALUES ('856a3873a67f47fa92cb70d7cdd93a0c', '8fde645a8cda4fda825a24f8d1fc525f');

**Comment by BaiJiangJie** [comment]
无法再次编辑的时候，提示什么信息？

**Comment by careylipu** [comment]
比如选中在左侧菜单树内选择那个资产授权实体，右侧不会出现对应的记录
