### ISSUE TITLE
登录频繁, 稍后重试

### ISSUE THREAD

**Issue by TopSpoofer** [jumpserver/jumpserver#3439]
[简述你的问题]
web正常登录操作，显示：登录频繁, 稍后重试

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@TopSpoofer 
- 提示登录频繁
$ source /opt/py3/bin/activate
$ cd /opt/jumpserver/utils
$ sh unblock_all_user.sh
