### ISSUE TITLE
怎么集成ansible呢

### ISSUE THREAD

**Issue by 106848748** [jumpserver/jumpserver#344]
求大神帮忙解答，或者哪里有帮助文档呢？

**Comment by 106848748** [comment]
安装了最新版本的jumpserver也没看到哪里可以执行ansible-playbook啊？

**Comment by jackiehope** [comment]
@106848748  哪里有说可以执行ansible-playbook，只看到可以执行命令。

**Comment by Nidhoggur1993** [comment]
同问，webUI上是不是可以加一个ansible的入口？

**Comment by fyqls** [comment]
用的是ansible1.9.4 api,  ansible2.X 不支持api

**Comment by Huangzsnone** [comment]
同问，如何集成ansible

**Comment by ibuler** [comment]
新版本支持了 ansible 2.2.2
