### ISSUE TITLE
jumpserver1.5.4 web端访问window手动登录只能跳过到window界面登录。无法自动登录

### ISSUE THREAD

**Issue by fuly2020** [jumpserver/jumpserver#3442]
版本：jumpserver1.5.4
安装：纯centos最小安装+官方自建服务器极速安装
测试：4台 window，三台2008R2 一台2016。目前只有一台2008R2出现登录异常的。
表现：自动登录即提示  连接错误   无法连接服务器，请联系管理员或查看日志。
手动登录：弹出窗直接输入  请输入密码  点击登录也是同样无法登录。跟自动登录错误一样
手动登录：选择跳过，进入到window登录界面 在输入密码 可正常进入window系统。
docker logs jms_guacamole  没看到报错信息。不知道是否还有其他日志记录。
通过上面，应该可以排除资产信息错误。手动登录直接输入密码登录也不行，说明帐号密码信息应该不是导致登录不了的原因。
注释：这台window 防火墙完全关闭。关闭杀毒软件 也无法自动登录
详请教一下。window系统是否需要设置什么。或者可以用什么方式去跟踪异常。

**Comment by wojiushixiaobai** [comment]
@fuly2020 如果资产上面有安全软件设置了安全登陆，则不可以实现自动登陆，至于账户密码问题，请自行验证

**Comment by fuly2020** [comment]
@wojiushixiaobai 安装了安全狗，已退出关闭，防火墙已关闭，帐号密码没问题。就是登陆不进去。有日志能否查看到返回信息？或者window需要开启什么服务或策略
