### ISSUE TITLE
 unable to authenticate

### ISSUE THREAD

**Issue by furyamber** [jumpserver/jumpserver#3444]
[简述你的问题]

##### 使用版本
1.5.4

##### 问题复现步骤
1. 网域列表增加后测试网关一直报错测试失败
2. 在web终端直接报错
Connect asset wojiushiwo error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
通常都是系统用户的账户和密码存在问题。
