### ISSUE TITLE
如何在ssh中添加参数实现自动登陆，ssh -t似乎没有作用

### ISSUE THREAD

**Issue by songtaoshi** [jumpserver/jumpserver#3450]
[简述你的问题]
你好，请问现在是否有方式可以在ssh里面添加参数，可以直接feed 到当前的窗口中，而不需要拆分称为两个步骤。

![image](https://user-images.githubusercontent.com/20240391/69227577-ff1bf180-0bbc-11ea-867e-fe380bcf750e.png)

**Comment by BaiJiangJie** [comment]
两个步骤指哪两步？

**Comment by songtaoshi** [comment]
就是能否ssh 登陆上了服务器，可以添加参数，使得他能执行我之前选择的服务器

**Comment by wojiushixiaobai** [comment]
@songtaoshi 使用登录脚本，或者参考ssh自动登录脚本
