### ISSUE TITLE
邮件发不出去。一直加载页面

### ISSUE THREAD

**Issue by EverCurse** [jumpserver/jumpserver#346]
安装的时候测试邮箱通过了，再添加用户的时候给用户发送邮件一直加载。后台日志

当我ctrl c  日志弹出来的是:

ERROR:tornado.access:500 GET /juser/mail/retry/?uuid=f1b41177ffd747988921283f00f0a48c (192.168.132.229) 2193727.89ms

**Comment by jackiehope** [comment]
这个问题一直都存在的，如果邮件发送不成功，jumpserver页面直接卡住。

**Comment by coolbreezeqf** [comment]
同样的问题，测试的时候通过了，在web就卡主了。
我是腾讯企业邮箱，在配置文件里开启ssl就好了。

**Comment by EverCurse** [comment]
@coolbreezeqf  请问能不能给个配置路径，怎么配置？万分感激。

**Comment by coolbreezeqf** [comment]
@EverCurse 就在jumpserver项目路径下的jumpserver.conf
`email_use_tls = True`
`email_use_ssl = True`

**Comment by movekj** [comment]
我页碰到了这个问题

**Comment by sum86** [comment]
腾讯的邮箱会卡死web页面，按照楼上方法在jumpserver项目路径下的jumpserver.conf
email_use_tls = True
email_use_ssl = True
SSL配置为true后正常。

**Comment by EverCurse** [comment]
@sum86  腾讯邮箱没问题 我就用的腾讯邮箱

**Comment by hellorocky** [comment]
没问题后close这个issue吧

**Comment by EverCurse** [comment]
@hellorocky ok thx
