### ISSUE TITLE
安装后启动报错: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hcking** [jumpserver/jumpserver#3462]
[简述你的问题]
安装后启动报错: SyntaxError: invalid syntax
系统版本: CentOS Linux release 7.6.1810 (Core)  
./jms start
./make_migrations.sh 
都会提示报错，截图如下

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver version 1.5.4
##### 问题复现步骤
1. [步骤1]
./jms start
2. [步骤2]
cd utils
./make_migrations.sh 
##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/22334655/69611995-ddfa4b80-1069-11ea-95ff-6aa597688924.png)
![2](https://user-images.githubusercontent.com/22334655/69612007-e05ca580-1069-11ea-9252-410978df21ec.png)
![3](https://user-images.githubusercontent.com/22334655/69612018-e2beff80-1069-11ea-9ed7-61437d00fa29.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by hcking** [comment]
附上缺少的一张图
![4](https://user-images.githubusercontent.com/22334655/69612354-798bbc00-106a-11ea-9fff-e0279eee8b78.png)

**Comment by wojiushixiaobai** [comment]
@hcking 
1. 请看官方文档
2. 官网文档里面有明确指出，只支持python3.6
