### ISSUE TITLE
工程师您好，web终端连接有点问题

### ISSUE THREAD

**Issue by tiangangdai** [jumpserver/jumpserver#3464]
[简述你的问题]
在web终端，打开资产的时候，提示资产xxx没有包含xx账号的ssh协议
![image](https://user-images.githubusercontent.com/40078697/69705068-b5d52000-112f-11ea-811a-7f06aa3e4122.png)
但是用用户登入以后，还可以执行命令
![image](https://user-images.githubusercontent.com/40078697/69705136-e5842800-112f-11ea-8a87-23c14afab679.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
版本1.4.8
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@tiangangdai 
确定下授权里面是否包含多个不同协议的系统用户
确定各组件的版本是否一致，需要个版本保存一致

**Comment by tiangangdai** [comment]
你好，我重新安装最新版，然后按照文档，用docker 按照的coco和guac，解决这个问题了
