### ISSUE TITLE
用户通过LDAP方式登录，如何通过组去筛选登录用户

### ISSUE THREAD

**Issue by abdxj407** [jumpserver/jumpserver#3466]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.8注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 已配置LDAP，目前只能通过OU控制用户，但是用户数如果多，且分布到不同OU，会比较麻烦，
因此想通过权限组控制登录堡垒机的用户。
但是目前不知道如何处理，

**Comment by wojiushixiaobai** [comment]
@abdxj407 支持多OU
ou=ou1,dc=domain,dc=com | ou=ou2,dc=domain,dc=com | ou=ou3,dc=domain,dc=com

**Comment by hugeng1979** [comment]
(&(sAMAccountName=%(user)s)(memberOf=CN=堡垒机用户组,DC=youcomapny,DC=com,DC=cn))
