### ISSUE TITLE
curl get请求 &符号后面参数不能识别，需要将&符转义才可以

### ISSUE THREAD

**Issue by redrain-wang** [jumpserver/jumpserver#3467]
curl get请求 &符号后面参数不能识别，需要将&符转义才可以

##### 使用版本
版本：1.5.2-2

##### 问题复现步骤
curl http://www.baidu.com/?a=b&b=a

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@redrain-wang 批量命令还是连接资产时的？

**Comment by qyvlik** [comment]
@redrain-wang  可以试试将命令改写为

```bash
curl "http://www.baidu.com/?a=b&b=a"
```
