### ISSUE TITLE
安装jumpservce一些依赖关系的错误

### ISSUE THREAD

**Issue by xishuaige** [jumpserver/jumpserver#347]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 autoconf : Depends: m4 (>= 1.4.13) but it is not going to be installed
 automake : Depends: autotools-dev (>= 20020320.1) but it is not going to be installed
 cups : Depends: cups-core-drivers (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-daemon (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-common (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
        Depends: cups-server-common (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-client (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
        Depends: cups-filters (>= 1.0.24-3~) but 1.0.17-0bzr0.1 is to be installed
 cups-bsd : Depends: cups-client (= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
            Depends: cups-common (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
 dpkg : Breaks: fontconfig (< 2.11.1-0ubuntu5~) but 2.8.0-3ubuntu9 is to be installed
        Breaks: install-info (< 5.1.dfsg.1-3~) but 4.13a.dfsg.1-8ubuntu2 is to be installed
        Breaks: man-db (< 2.6.3-6~) but 2.6.1-2 is to be installed
 gcc : Depends: cpp (>= 4:5.2.1-3ubuntu1) but 4:4.6.3-1ubuntu5 is to be installed
       Depends: gcc-5 (>= 5.2.1-12~) but it is not going to be installed
 libcairo-perl : Depends: perlapi-5.14.2 but it is not installable
 libglib-perl : Depends: perlapi-5.14.2 but it is not installable
 libgtk2-perl : Depends: perlapi-5.14.2 but it is not installable
 liblocale-gettext-perl : PreDepends: perlapi-5.14.2 but it is not installable
 libmysqld-dev : Depends: libmysqlclient-dev (>= 5.6.31-0ubuntu0.15.10.1) but it is not going to be installed
 libpango-perl : Depends: perlapi-5.14.2 but it is not installable
 libperl5.14 : Depends: perl-base (= 5.14.2-6ubuntu2) but 5.20.2-6ubuntu0.2 is to be installed
 libpurple0 : Depends: perlapi-5.14.2 but it is not installable
 libreadline-dev : Depends: libreadline6-dev (= 6.3-8ubuntu1) but it is not going to be installed
 libtext-charwidth-perl : Depends: perlapi-5.14.2 but it is not installable
 libtext-iconv-perl : Depends: perlapi-5.14.2 but it is not installable
 libuuid-perl : Depends: perlapi-5.14.2 but it is not installable
 python-all-dev : Depends: python (= 2.7.9-1) but 2.7.3-0ubuntu2 is to be installed
                  Depends: python-all (= 2.7.9-1) but it is not going to be installed
                  Depends: libpython-all-dev (= 2.7.9-1) but it is not going to be installed
                  Depends: python-dev (= 2.7.9-1) but it is not going to be installed
                  Depends: python2.7-dev (>= 2.7-7) but it is not going to be installed
 python-pip : Depends: python-colorama but it is not going to be installed
              Depends: python-distlib but it is not going to be installed
              Depends: python-html5lib but it is not going to be installed
              Depends: python-requests but it is not going to be installed
              Depends: python-setuptools (>= 0.6c1) but it is not going to be installed
              Depends: python-six but it is not going to be installed
              Depends: python (>= 2.7.5-5~) but 2.7.3-0ubuntu2 is to be installed
              Recommends: build-essential but it is not going to be installed
              Recommends: python-dev-all (>= 2.6) but it is not installable
              Recommends: python-wheel but it is not going to be installed
 software-center : Depends: python-gi (>= 3.4.0-1ubuntu0.1) but 3.2.0-3 is to be installed
                   Depends: python-lxml but it is not going to be installed
                   Recommends: xz-utils (>= 5.1.1alpha+20120614-1) but 5.1.1alpha+20110809-3 is to be installed
 vim : Depends: vim-common (= 2:7.4.712-2ubuntu4) but 2:7.3.429-2ubuntu2.2 is to be installed
       Depends: vim-runtime (= 2:7.4.712-2ubuntu4) but 2:7.3.429-2ubuntu2.2 is to be installed
       Depends: libacl1 (>= 2.2.51-8) but 2.2.51-5ubuntu1 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

虽然是简单的依赖错误有大神能指点一下吗？
我用了

apt-get -f install以后会是这样的错误
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cups is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 cups : Depends: cups-core-drivers (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-daemon (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-common (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
        Depends: cups-server-common (>= 2.1.0-4ubuntu3) but it is not going to be installed
        Depends: cups-client (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
        Depends: cups-filters (>= 1.0.24-3~) but 1.0.17-0bzr0.1 is to be installed
 cups-bsd : Depends: cups-client (= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
            Depends: cups-common (>= 2.1.0-4ubuntu3) but 1.5.2-9ubuntu1 is to be installed
 dpkg : Breaks: fontconfig (< 2.11.1-0ubuntu5~) but 2.8.0-3ubuntu9 is to be installed
        Breaks: install-info (< 5.1.dfsg.1-3~) but 4.13a.dfsg.1-8ubuntu2 is to be installed
        Breaks: man-db (< 2.6.3-6~) but 2.6.1-2 is to be installed
 libcairo-perl : Depends: perlapi-5.14.2 but it is not installable
 libglib-perl : Depends: perlapi-5.14.2 but it is not installable
 libgtk2-perl : Depends: perlapi-5.14.2 but it is not installable
 liblocale-gettext-perl : PreDepends: perlapi-5.14.2 but it is not installable
 libpango-perl : Depends: perlapi-5.14.2 but it is not installable
 libperl5.14 : Depends: perl-base (= 5.14.2-6ubuntu2) but 5.20.2-6ubuntu0.2 is to be installed
 libpurple0 : Depends: perlapi-5.14.2 but it is not installable
 libtext-charwidth-perl : Depends: perlapi-5.14.2 but it is not installable
 libtext-iconv-perl : Depends: perlapi-5.14.2 but it is not installable
 libuuid-perl : Depends: perlapi-5.14.2 but it is not installable
 software-center : Depends: python-gi (>= 3.4.0-1ubuntu0.1) but 3.2.0-3 is to be installed
                   Depends: python-lxml but it is not going to be installed
                   Recommends: xz-utils (>= 5.1.1alpha+20120614-1) but 5.1.1alpha+20110809-3 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

如果有大神，麻烦帮我解答一下，或者是给我一点方法

**Comment by jiaxiangkong** [comment]
sudo apt-get --fix-broken install

**Comment by choldrim** [comment]
`-f` 就是 `--fix-broken` 了
@xishuaige 你的是什么系统，感觉是系统太旧了，或者选的源不对
