### ISSUE TITLE
windows访问白屏

### ISSUE THREAD

**Issue by guyaozhou** [jumpserver/jumpserver#3470]
jumpserver版本是1.4.8

1、通过web连接Windows显示白屏
![image](https://user-images.githubusercontent.com/24237876/69800041-65cd8a80-120f-11ea-91e0-e39f9afbcdc2.png)

2、查看会话管理，发现gua在线
![image](https://user-images.githubusercontent.com/24237876/69800096-84338600-120f-11ea-8bd2-a69c67390bb3.png)

3、测试端口3389是正常的
![image](https://user-images.githubusercontent.com/24237876/69800251-d4124d00-120f-11ea-8c81-3762eebb1a65.png)

4、资产列表显示是可连接
![image](https://user-images.githubusercontent.com/24237876/69800319-f99f5680-120f-11ea-9653-d64b1f3071e3.png)

5、资产授权显示如下
![image](https://user-images.githubusercontent.com/24237876/69800375-150a6180-1210-11ea-9627-822b7b96d2c7.png)

6、web连接debug显示，界面报错如下
![image](https://user-images.githubusercontent.com/24237876/69800492-51d65880-1210-11ea-8fc3-986fa4688a2c.png)

7、参考的部署方法：
https://docs.jumpserver.org/zh/1.4.8/setup_by_centos7.html

**Comment by wojiushixiaobai** [comment]
@guyaozhou 测试下8081端口是否正常

**Comment by guyaozhou** [comment]
@wojiushixiaobai 谢谢您，这个问题我已经解决了，是我重新彻底清空了jms_guacamole的所有组件，重新创建完成的。
