### ISSUE TITLE
服务器部署好后可以改录像保存位置吗？

### ISSUE THREAD

**Issue by immikez** [jumpserver/jumpserver#3473]
[简述你的问题]

服务器部署好后可以改录像保存位置吗
##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- (1)系统设置==>终端设置==>添加录像存储
![image](https://user-images.githubusercontent.com/40739051/70104885-63898700-167a-11ea-8c50-c7f7ed9f057f.png)
 - (2)会话管理==> 终端管理==>更新终端==>选择录像存储==>提交
![image](https://user-images.githubusercontent.com/40739051/70105002-af3c3080-167a-11ea-83f6-432e898fb35b.png)
