### ISSUE TITLE
1.5.2版本文件提示文件夹不存在

### ISSUE THREAD

**Issue by roger-gs** [jumpserver/jumpserver#3476]
[简述你的问题]
在使用文件管理时，部分主机提示“文件夹不存在”
##### 使用版本
1.5.2-2

在文件管理界面点击具体的某台服务器提示“文件夹不存在”

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@roger-gs 确定资产上面有对应设置的sftp目录
