### ISSUE TITLE
无法更新和删除管理用户

### ISSUE THREAD

**Issue by maorui2k** [jumpserver/jumpserver#3477]
[简述你的问题]
创建一个管理用户，无法更新用户名、密码等信息，同时也无法删除这个用户。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4-2

##### 问题复现步骤
1. 创建管理用户xxxxx
2. 点击更新，进入编辑界面
3. 修改用户名和密码，点击提交
4. 返回管理用户列表，选择删除管理用户xxxxx

##### 具体表现[截图可能会更好些,最好能截全]
点击提交，无响应
点击删除，提示“更新时发生未知错误”

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@maorui2k 无法复现
