### ISSUE TITLE
登录Windows资产，无法获取剪贴板内容

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3479]
[简述你的问题]

##### 使用版本
Version 1.5.4-2 GPLv2

##### 问题复现步骤

1. Mac笔记本登录Jumpserver后，使用web终端连接Windows服务器
2. 在windows服务器粘贴Mac上复制的密码文本，在Windows终端中无法获取到

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@jackwang-github 在nginx里面加入ssl的相关设置后再试试

**Comment by jackwang-github** [comment]
> @jackwang-github 在nginx里面加入ssl的相关设置后再试试

然而并没有什么用，每次都要按ctrl+shfit+alt把复制的内容贴到框框里面，就像这样子：
![image](https://user-images.githubusercontent.com/58414586/70304203-63d18000-183c-11ea-86a4-235846829eca.png)

你的能正常访问剪贴板么？

**Comment by zhouyuyong** [comment]
@wojiushixiaobai 我这边也是一样1.5.4-2版本 配置了https，在本地复制后ctrl+shift+alt中可以看到复制的内容，但是在服务器的粘贴板里没有内容

**Comment by zhouyuyong** [comment]
重装了freerdp可以复制粘贴了

**Comment by jackwang-github** [comment]
我配置了https后能直接复制了
