### ISSUE TITLE
在连接某个具体服务器资源时，需要实时的权限检查，是否可以禁用后台的redis缓存？

### ISSUE THREAD

**Issue by peixubin** [jumpserver/jumpserver#3480]
将授权过期后，jumpserver用户仍然可以登陆已经过期的资源。

##### 使用版本
1.4.9

##### 问题复现步骤
1. 首先使用某个jumpserver用户(如user1)登陆，并确认某资源可以登录
2. 将某资源的授权过期
3.user1仍然可以登录过期的资源

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@peixubin 更新至新版本，在config.yml 里面设置
