### ISSUE TITLE
文件管理中默认资产目录为（/tmp），如何修改

### ISSUE THREAD

**Issue by cnxue** [jumpserver/jumpserver#3490]
[简述你的问题]
默认资产目录为（/tmp），如何修改

##### 使用版本
1.5.4-2 GPLv2

**Comment by jym503558564** [comment]
修改koko配置文件中的参数： SFTP_ROOT 
![image](https://user-images.githubusercontent.com/40739051/70131537-6f4a6d00-16bd-11ea-8890-985320bc4a81.png)

**Comment by cnxue** [comment]
搞定了，谢谢！

**Comment by FreezeJ** [comment]
@jym503558564 我使用的1.5.6版本，设置了config.yaml不生效，现在这个要怎么设置？

**Comment by linrilian** [comment]
@FreezeJ   我使用的是1.5.8版本，SFTP的根目录可以在针对具体系统用户设置，你可以尝试看看
![image](https://user-images.githubusercontent.com/65593245/82304458-f0d55380-99ee-11ea-8991-ffc0f51d32dc.png)

**Comment by FreezeJ** [comment]
@linrilian 感谢告知，我翻了一下代码，发现1.5.6版本没有这个配置的，我现在已经升级为1.5.8了，这个功能已经没问题了。
顺便贴一下官方的[升级文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/1.5.0/?tdsourcetag=s_pctim_aiomsg)，升级其实也很方便。

**Comment by wajika** [comment]
> @FreezeJ 我使用的是1.5.8版本，SFTP的根目录可以在针对具体系统用户设置，你可以尝试看看
> ![image](https://user-images.githubusercontent.com/65593245/82304458-f0d55380-99ee-11ea-8991-ffc0f51d32dc.png)

普通用户好像还是无法跳转，怎么授权？
![image](https://user-images.githubusercontent.com/17058349/115133058-d01ae100-a037-11eb-8094-dadcb64f0265.png)

**Comment by asdfec** [comment]
好像3.1.0去掉了相关选项，只能在py文件里改了吗？
