### ISSUE TITLE
jumpserver有没有客户端？

### ISSUE THREAD

**Issue by superdeva** [jumpserver/jumpserver#3493]
[简述你的问题]
使用浏览器访问jumpserver不太方便，有没有一个客户端，然后通过客户端访问jumpserver?

##### 使用版本
v1.5.2

##### 问题复现步骤
无

##### 其他

[注:] 完成后请关闭 issue

**Comment by npcomet** [comment]
putty
SecureCRT
Xshell
Bitvise
等等 很多很多
