### ISSUE TITLE
為什麼不能用中鍵關閉視窗?

### ISSUE THREAD

**Issue by michael1018** [jumpserver/jumpserver#3498]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by michael1018** [comment]
thanks

**Comment by ibuler** [comment]
不明白是什么意思？关闭窗口？
