### ISSUE TITLE
jumpserver文件上传jenkins的rpm安装包时出现错误

### ISSUE THREAD

**Issue by reY2ox** [jumpserver/jumpserver#3499]
[简述你的问题]
jumpserver文件上传jenkins的rpm安装包时出现错误。

##### 使用版本
1.5.4-2

##### 问题复现步骤
1、进入jumpserver文件管理界面
2、拖动jenkins的rpm安装包，进入文件管理的服务器tmp目录
3、上传进度条显示10%就消失
4、浏览器查看statuscode为405

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/49467163/70131266-f2b78e80-16bc-11ea-80ba-9ed63e8e0999.png)

##### 其他
与文件大小、名字、后缀无关，我上传其他文件都可以完成，上传jenkins的rpm包时，修改名字和后缀都不可以。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
改问题还依然存在吗？
