### ISSUE TITLE
Jumpserver v0.4.0 新版本预览

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#350]
各位喜欢Jumpserver的朋友，你们好，这里给大家说声抱歉，
很久没有关于新版本的消息，我们曾承诺过各种发布期限，然而一直在延期，对不起。

可能有朋友认为我们放弃了，抛弃了，然而还没有，我们一直在坚持

今天发布这个新版本预览说明，有以下两个目的：

**1. 一直在坚持，并没有放弃**

大家知道做开源是辛苦的事，何况只是业余时间来做做，开发者的时间不固定，有的可能一周写一些，有的可能一个月写一些，所以我们一直没有兑现我们的诺言，这里说声抱歉，不过，真的，我们没有放弃

**2. 我们需要帮助**

我们需要更多的朋友加入我们，帮我们完成这个版本的开发。希望有懂 python, django, angular的朋友帮帮我们，也需要有开源项目管理经验的帮帮我们，非常感谢

### 一. 实现了一个ssh server: Coco项目

v0.3版本及之前，我们使用linux自带的ssh server和connect完成跳转，本次版本我们使用paramiko实现了
一个ssh server, 不再依赖linux的ssh server，也就意味着不需要依赖linux 的用户认证，可以实现更多的认证方式 如: google auth. 用户登录 Coco，会通过调用jumpserver api完成认证，用户的输入会发送到jumpserver,用来审计。

仓库： [Coco](https://github.com/jumpserver/coco)

![coco](https://cloud.githubusercontent.com/assets/17382885/23537616/39f64968-0008-11e7-9ae9-926eb4884b7b.gif)

### 二. 实现了一个新的 web terminal

之前版本的web terminal功能简陋，这里我们想提供给大家一个更易用的 web terminal，于是我们写了 Luna项目，界面更加简洁，实用。 和Coco一样，需要调用jumpserver api完成认证，审记。 Luna是由 Flask Flask-socketio angular实现。

仓库: [Luna](https://github.com/jumpserver/luna)

![luna](https://cloud.githubusercontent.com/assets/17382885/23537662/9d1e1066-0008-11e7-9eda-4c075c8b57f3.gif)

### 三. 重构了 Jumpserver

新版本Jumpserver使用 python2.7(ansible不支持python3), django最新版本来实现，并且使用Django Class Base View, 更通用一些(可能会比较难以理解)

仓库: [Jumpserver](https://github.com/jumpserver/jumpserver/tree/dev) 

![jumpserver](https://cloud.githubusercontent.com/assets/17382885/23537700/e52d1758-0008-11e7-809d-c17fef5fd9c3.gif)

## 最后

我们还没有完全完成这个版本，甚至还没有完全把所有功能跑通。

但是，我迫切的像大家透露这个消息，并把代码push到了github，是想告诉大家，或许未来你会看到新版本的Jumpserver

感谢   **尚委，小彧，刘正，茂峻，书僮，王墉，董帅，连春，成维，Tad**，感谢你们在不同阶段给予的帮助， 感谢未来为Jumpserver奉献的人，感谢喜欢我们的用户，新版本见

**Comment by foreveryan** [comment]
大爱Jumpserver，
希望能搞定0.3版本到新版本的简单过渡，对于升级来说就可以更加方便，
现在公司线上已经用它管理者茫茫的用户和机器了，离不开Jumpserver!
继续加油！

**Comment by supertaodi** [comment]
赞赞赞,  不借助linux ssh server 这点真的不错

**Comment by LinuxEA-Mark** [comment]
非常期待这次更新

**Comment by xskh2007** [comment]
不错，不错

**Comment by fujinzhou** [comment]
赞。支持下。期待啊

**Comment by mohongshu** [comment]
加油

**Comment by xiaooloong** [comment]
非常棒👍

**Comment by xxrenzhe** [comment]
赞开源精神，赞开发者精神，赞业余开发实践！

**Comment by lxshopping** [comment]
期待新版本

**Comment by leoiceo** [comment]
期待新版本，项目非常适合python学习

**Comment by superzr8** [comment]
给各位城蓄猿点赞！

**Comment by ye92101578** [comment]
加油

**Comment by suntao098** [comment]
不错 什么时候发布

**Comment by jokimina** [comment]
参与项目有什么限制条件 么,  统一调度,还是自由选取模块开发？ 开发者规范等等.
可以一并说明下. 方便大家知道如何一起贡献.
项目持续这么久 我相信很多人都想尽一份力,但是不知道具体如何来. @ibuler,

**Comment by caozhangni** [comment]
非常不错! 我也一直在做jumpserver的二次开发工作，从之前版本的jumpserver源码中学习到了很多，有什么帮的上的，一定尽力而为！

**Comment by qiaofuli** [comment]
值得学习！

**Comment by ibuler** [comment]
@jokimina  https://github.com/jumpserver/jumpserver/tree/dev 这里有一些说明和规范，如果可以可以提issue

**Comment by ibuler** [comment]
@caozhangni 见上条，风格要和原来代码相似，遵守基本规范

**Comment by jokimina** [comment]
@ibuler  这个说明和规范链接到的gitlab需要账号密码访问

**Comment by ibuler** [comment]
@jokimina 已经更新为 github链接

**Comment by seacoastboy** [comment]
(ansible不支持python3)? ansible 2是支持python 3的。

**Comment by ibuler** [comment]
@seacoastboy 如果 ansible2支持 python3, 最终版本会以 python3发布

**Comment by choldrim** [comment]
被坑了，以为你们不在维护了，自己fork了一个分支，打算自己继续维护，弄了一个多星期，今天才发现了dev分支.. T.T

**Comment by choldrim** [comment]
@ibuler ansible 2.2 开始支持python3了
https://docs.ansible.com/ansible/python_3_support.html

**Comment by ibuler** [comment]
@choldrim 可以来一起写？

**Comment by choldrim** [comment]
@ibuler 可以呀，到时我提一些PR :)

**Comment by kingsxw** [comment]
能不能支持ad或者ldap认证啊

**Comment by seacoastboy** [comment]
@choldrim 快加入吧，然后把我也带上
@ibuler 现在如果有人加入的话，应该是无从下手的，大家不知道进度如何，而且也不知道那些在开发中，那些在冻结中， 如果有进度列表就就方便多了。

**Comment by TopZJ** [comment]
您好,我也想参加开发工作 熟悉 Python 和 django

**Comment by Accpet** [comment]
期待新版本，项目非常适合python学习

**Comment by rfyiamcool** [comment]
好屌

**Comment by shencan** [comment]
好屌

**Comment by chenyingcong1** [comment]
666不知道能不能0.3升级过去

**Comment by amazingbing** [comment]
jumpserver生级的话，只需要新装一个，把备份的数据导进去就行吧？

**Comment by jettying** [comment]
目前正在基于0.3.2做开发，扩展了一个作业平台【类似于EasyOps】，所以想问下0.4.0中的作业中心具体是个什么功能，能否展示一下？

**Comment by shineforever** [comment]
请问新版本大概什么时间放出来啊！？有个大概时间吗？

**Comment by ibuler** [comment]
@jettying 本来打算做 作业平台的，但由于负责的开发者后续没有时间，所以不得已砍掉了，只保留了推送，可以测试dev，方式见 docs目录中的install.md

**Comment by ibuler** [comment]
@shineforever 具体时间没定，大流程没问题了，小问题还不少

**Comment by choldrim** [comment]
@ibuler 弱弱的问一句，在哪里打开连接服务器的terminal？ 找了好久 T.T

**Comment by ibuler** [comment]
@choldrim coco 项目

**Comment by kevinzu007** [comment]
过来，朕赏你一个吻^_^

**Comment by ibuler** [comment]
Coco 项目和Luna项目

在 2017年4月6日 下午6:12:37, Caijun (notifications@github.com) 写到:

@ibuler 弱弱的问一句，在哪里打开连接服务器的terminal？ 找了好久 T.T

**Comment by tz6618** [comment]
大赞，我用了2.0，也早已经升级到3.0 目前管理主机数量560+。期待4.0

**Comment by iamsk** [comment]
coco 和 新的 jumpserver 很赞同，建议不要在 luna 上花太多时间，把核心功能做好，期待使用稳定版的 0.4。我们已基于原先的 0.4 分支二次开发，我们尽快反馈给现有的 dev 分支。

**Comment by ibuler** [comment]
@iamsk 感谢反馈，Luna确实不是核心功能，但是是一个比较炫的功能。 感谢你的支持，期待你的反馈

**Comment by tz6618** [comment]
非常棒。感谢

**Comment by anjia0532** [comment]
非常感谢。
