### ISSUE TITLE
用户登录验证错误OperationalError at /auth/login/

### ISSUE THREAD

**Issue by hcking** [jumpserver/jumpserver#3503]
[简述你的问题]
用系统用户，和其他用户登录报错
OperationalError at /auth/login/

##### 使用版本
最新版 

##### 问题复现步骤
进入登录界面，用户登录

##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/22334655/70203036-97d27580-1756-11ea-972a-2ddb37bea4f3.png)

##### 其他
找到原因了，因为mariadb 开启了binlog ，关掉binlog就好了
cat /etc/my.conf
# server-id=1
# log-bin=/var/lib/mysql/mysql-bin

上面这两条注释就好了，但是想问下为什么不支持binlog？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hcking 和binlog无关，和binlog_format有关
