### ISSUE TITLE
ProxyJump

### ISSUE THREAD

**Issue by Kurt-Shiwz** [jumpserver/jumpserver#3512]
有计划支持ProxyJump（or ProxyCommand）吗？？

**Comment by 297242448** [comment]
jumpserver 不支持 命令代理转发、端口转发等功能，我们选择使用openssh 实现堡垒机。

**Comment by Kurt-Shiwz** [comment]
> jumpserver 不支持 命令代理转发、端口转发等功能，我们选择使用openssh 实现堡垒机。

公司不在乎这个 也不大可能调整了，木有办法

**Comment by 297242448** [comment]
解决办法。只能再启用openssh-server  用作代理转发 即可，这个功能其实很有用。机房网络和办公网网络不通，办公网要查询数据库、或者调试等功能 就很不方便

**Comment by ibuler** [comment]
没有计划，ProxyJump 只是把堡垒机当做转发，可以转发tcp协议，然而我们也无法解开其中数据，没有审计的价值

**Comment by xgdgsc** [comment]
对于有些公司，不需要解开数据，仅仅计算数据量已经具有审计价值了

**Comment by gzm55** [comment]
> 没有计划，ProxyJump 只是把堡垒机当做转发，可以转发tcp协议，然而我们也无法解开其中数据，没有审计的价值

登录任意一台设备后, 可以使用基于 tty 的隧道实现tcp转发, 依赖这种隧道从客户端登录其他服务器后, jumperserver 还是解析不了数据.

**Comment by Kurt-Shiwz** [comment]
换了公司 发现还是jumpserver，依然不能支持ProxyJump，「流泪中」.jpg

**Comment by Mutefish0** [comment]
使用pty模块，照样可以通过脚本控制
https://www.npmjs.com/package/node-pty

**Comment by zhanbinHo** [comment]
阿里云的堡垒机器可以使用ProxyJump，并有审计日志
