### ISSUE TITLE
API认证接口不可用

### ISSUE THREAD

**Issue by zhouyuyong** [jumpserver/jumpserver#3516]
[简述你的问题]
更新到1.5.5 ，API认证接口失效

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
从1.5.4升级到1.5.5 后 一次性Token认证方式失效

##### 其他

[注:] 完成后请关闭 issue

**Comment by zachaway** [comment]
遇到相同的问题。api获取token的时候，在有MFA认证的情况下会查询session里面是否有user信息

**Comment by wojiushixiaobai** [comment]
@zhouyuyong @zachaway 验证无误。可以使用此脚本验证 https://github.com/wojiushixiaobai/jumpserver_script/blob/master/jms_api.py
