### ISSUE TITLE
迁移至docker环境，用户名登录时出现Server error occur, contact administrator

### ISSUE THREAD

**Issue by johnnyzhouzhou** [jumpserver/jumpserver#3519]
[简述你的问题]
之前是用centos7部署的，现在想改为docker部署，我将数据库复制到Azure云上 ，dokcer logs显示连接都是正常的。SECRET_KEY和BOOTSTRAP_TOKEN都是用的以前的，在登录界面输入用户名和密码登录会出现Server error occur, contact administrator

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
我是用docker部署的，版本jumpserver/jms_all:latest
##### 问题复现步骤
1. [步骤1]任务账户登录，提示：Server error occur, contact administrator
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28947961/70423489-8962c180-1aa8-11ea-85da-04020b99ac5d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
查看后台日志，看看具体报错内容

```
cd $JUMPSERVER_DIR/logs/ 
tail -f jumpserver.log
```
