### ISSUE TITLE
mysql 5.7.17 + Ubuntu 16.04,  root 安全性修正后的安装问题

### ISSUE THREAD

**Issue by houyi314** [jumpserver/jumpserver#352]
mysql 5.7.17 + Ubuntu 16.04,  由于 root 用户不再采用空密码，所以安装脚本中采用root 空密码方式登录，似乎有问题。

**Comment by jiaxiangkong** [comment]
1.可以手动先创建jumpserver数据库
create database jumpserver charset='utf8'; 
grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by '5Lov@wife';

2. ./install.py  是否安装新的MySQL服务器  这步选 N
