### ISSUE TITLE
导出资产时，标签字段为ID（无法正常识别），不是名称

### ISSUE THREAD

**Issue by junly917** [jumpserver/jumpserver#3520]
[简述你的问题]
在使用资产导出的时候，导出来的xls 的标签字段为ID，无法显示名称或可识别的内容。
另外，有没有将能不能将标签显示到jumpserver 登录选择资产清单后面的配置？
我想在选择资产的时候，可以看到服务器的标签有哪些，最好是可以搜索的标签的功能，类似备注信息

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.3-2版本

##### 问题复现步骤
资产管理-  选中导出功能，

##### 具体表现[截图可能会更好些,最好能截全]
截图不能上传。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
标签这里设计的确存在问题，应该使用非关系型数据结构来描述

**Comment by xiaohinata** [comment]
这个2019年的问题还没有优化，现在资产导出标签还是id的形式，而不是设置的可识别样式

**Comment by ibuler** [comment]
老用户你好，我现在就去优化

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/143542624-b2268603-0ae9-458a-a08b-85f7e5c5735b.png)

https://github.com/jumpserver/jumpserver/pull/7292
