### ISSUE TITLE
jumpserver Version 1.5.3-2 GPLv2发送邮件功能不可用。

### ISSUE THREAD

**Issue by glkappe** [jumpserver/jumpserver#3522]
[简述你的问题]
jumpserver Version 1.5.3-2 GPLv2发送邮件功能不可用。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver Version 1.5.3-2 GPLv2
##### 问题复现步骤
1. [步骤1]
重置密码
2. [步骤2]
查看邮箱，
##### 其他

[注:] 完成后请关闭 issue

**Comment by EndingCode** [comment]
我也遇到了，请求解决方案

**Comment by zhouyuyong** [comment]
@glkappe 这个问题我的解决方法是重启jms服务

**Comment by glkappe** [comment]
@zhouyuyong 信邪了，重启jms没有作用，我测试邮件都发的出去。
![Uploading image.png…]()

**Comment by EndingCode** [comment]
> @zhouyuyong 信邪了，重启jms没有作用，我测试邮件都发的出去。
> ![image](https://user-images.githubusercontent.com/21033020/70519137-69013880-1b76-11ea-9f1e-3f9a125a76f4.png)

重启没用的，我上个月就遇到了，隔了好几天，突然间别人就收到了之前没发出去的邮件。 测试邮件自己发自己是正常的

**Comment by zhouyuyong** [comment]
@EndingCode @glkappe   如果重启不起作用，把redis用flushall 刷新下，我是这样做后可以收到重置邮件了，如果还不行就智能尝试升级了 目前1.5.5 测试没问题

**Comment by ibuler** [comment]
应该是celery出现了问题，重启celery应该能解决，后续版本更新了celery配置

**Comment by ibuler** [comment]
如果问题仍然存在，请重新打开issue
