### ISSUE TITLE
Luna界面资产排序异常

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#3525]
[简述你的问题]
**Luna界面资产排序异常**

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.5-101

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![图片](https://user-images.githubusercontent.com/4084548/70518025-92b96000-1b74-11ea-94e5-902741806299.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
节点名为 -10是另一个组织名称为-10的吗？

**Comment by bigbird1985** [comment]
不是的。
目前总共两个组织，一个是“DEFAULT”，一个是“服务器组”
只有“DEFAULT”下有资产，“服务器组”下没有资产。

**Comment by bigbird1985** [comment]
> 
> 
> 节点名为 -10是另一个组织名称为-10的吗？

今天突然发现原因了，是因为某些资产的授权的时候，单独对资产授权而不是对资产所在的子节点授权，我把授权规则改成对子节点授权后就可以了。这个算Bug吗？
