### ISSUE TITLE
windows 空闲连接不自动断开

### ISSUE THREAD

**Issue by zhouyuyong** [jumpserver/jumpserver#3526]
[简述你的问题]
连接最大空闲时间设置的是1分钟，linux的连接可以在超过1分钟后自动端看，但是windows不会断开

##### 使用版本
1.5.5

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhouyuyong rdp和vnc协议目前不支持，guacamole默认超时时间为60分钟
