### ISSUE TITLE
ansible v2 推送用户推送

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#353]
使用 ansible v2版本完成系统用户推送， 基本api功能已完成

参考  https://github.com/Joshuapy/ansible2_myAPI

**Comment by ibuler** [comment]
需要celery支持异步推送

**Comment by seacoastboy** [comment]
辛苦了。 去测试看看

**Comment by ibuler** [comment]
还没有push

**Comment by seacoastboy** [comment]
现在的api适合版本是ansible 2.2+。 如果是2.1就会有问题问题的
