### ISSUE TITLE
RDP的远程自动断开时间

### ISSUE THREAD

**Issue by immikez** [jumpserver/jumpserver#3531]
[简述你的问题]
请问哪里可以设置RDP远程连接在一段时间没有操作后自动断开？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@immikez 资产可以设置远程超时自动断开，guacamole默认断开时间为1小时
