### ISSUE TITLE
1.5.5 web终端连接被拒绝

### ISSUE THREAD

**Issue by purevita** [jumpserver/jumpserver#3533]
[简述你的问题]
web终端连接被拒绝
显示：Connect asset Net_test error: dial tcp 127.0.0.1:22: connect: connection refused

##### 使用版本
1.5.5

##### 问题复现步骤
1. 系统用户设为自动登录、推送
2. 开启web终端连接资产
3. Connect asset Net_test error: dial tcp 127.0.0.1:22: connect: connection refused

##### 具体表现[截图可能会更好些,最好能截全]
系统用户推送、连接测试都正常
如改为手动登录则正常

**Comment by wojiushixiaobai** [comment]
@purevita 不要用127.0.0.1
