### ISSUE TITLE
强制开启MFA认证后，用户通过ssh登录密钥正确，但是没有弹出认证框，无法二次认证登录。

### ISSUE THREAD

**Issue by USDao** [jumpserver/jumpserver#3534]
[简述你的问题]

强制开启MFA认证后，用户通过ssh登录密钥正确，但是没有弹出认证框，无法二次认证登录。
##### 使用版本
Version 1.5.5-2 GPLv2.

##### 问题复现步骤
1. [步骤1]强制开启MFA认证后，用户通过ssh登录密钥正确，但是没有弹出认证框，无法二次认证登录。
2. [步骤2]禁用MFA后，登录正常。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@USDao 使用交互式登录

**Comment by Wyerchen** [comment]
交互登录也失败 更新到1.5.6后正常
