### ISSUE TITLE
不生效：设置浏览器关闭Session自动失效

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3537]
[简述你的问题]
根据官方文档说明，我希望用户浏览器关闭后cookie失效。检查了配置是：SESSION_EXPIRE_AT_BROWSER_CLOSE: true
ESSION_EXPIRE_AT_BROWSER_CLOSE: true
但用户关闭浏览器后，等几分钟再打开jumpserver却自动登录了。

![image](https://user-images.githubusercontent.com/58414586/70856695-52fbcb00-1f1c-11ea-960f-316062a0f78e.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

Version 1.5.4-2 GPLv2.
docker部署

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@jackwang-github 无法复现，请把浏览器完全退出

**Comment by jackwang-github** [comment]
@wojiushixiaobai xiaobai,使用chrome浏览器无法实现关闭浏览器session自动失效的功能，其他浏览器测试正常。
