### ISSUE TITLE
如何往windows资产传文件呢？

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3538]
[简述你的问题]
如何往windows资产传文件呢？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.4-2 GPLv2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@jackwang-github 把文件直接拖到windows窗口即可

**Comment by jackwang-github** [comment]
> @jackwang-github 把文件直接拖到windows窗口即可
Hi Xiaobai,
拖进去确实是传到JMS了，但它只是在这里。没办法拷贝到目标主机的。
![image](https://user-images.githubusercontent.com/58414586/71050325-de28cb00-217f-11ea-8db9-7a592def97dc.png)
