### ISSUE TITLE
新建用户，或更新用户信息，会导致用户不可用

### ISSUE THREAD

**Issue by tianshaokui** [jumpserver/jumpserver#3541]
[简述你的问题]

新建用户，或更新用户信息，会导致用户不可用

##### 使用版本
master分支
commit a88db3d9db115bd6ab24962de80e2ed24f1fbdbd
Author: BaiJiangJie <32935519+BaiJiangJie@users.noreply.github.com>
Date:   Wed Dec 4 17:55:26 2019 +0800

    Merge pull request #3501 from jumpserver/dev

##### 问题复现步骤
1. 更新已存在用户信息， 或者新建用户
2. 用户失效日期无法修改， 导致过期

##### 其他
直接修改用户的mysql用户记录， 已经恢复

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
无法复现此问题，可否提供更详细的信息以及日志信息

**Comment by tianshaokui** [comment]
1. 手动点击更新用户
![image](https://user-images.githubusercontent.com/11375339/70959582-a0f90600-20b7-11ea-8316-bcc18c864928.png)
2. 有效期无法选择
![image](https://user-images.githubusercontent.com/11375339/70959691-da317600-20b7-11ea-849e-3f83f5107944.png)
![image](https://user-images.githubusercontent.com/11375339/70959704-e0bfed80-20b7-11ea-81da-d24bcc31c9ac.png)
![image](https://user-images.githubusercontent.com/11375339/70959809-21b80200-20b8-11ea-8ecb-c0c97111d226.png)

**Comment by tianshaokui** [comment]
chrome,firefox,safari浏览器均不支持

**Comment by wojiushixiaobai** [comment]
@tianshaokui 无法复现，可以自行到demo环境验证，https://demo.jumpserver.org

**Comment by RyanZhang2015** [comment]
ubuntu 18.04 日期不可选

**Comment by ihuanglei** [comment]
https://demo.jumpserver.org 也是一样的问题，日期无效
问题和上面的图一样

**Comment by wojiushixiaobai** [comment]
@ihuanglei 换个设备验证，或者换个浏览器

**Comment by RyanZhang2015** [comment]
1.5.4没有这个问题，1.5.5才有，涉及到选日期的都是无效。

**Comment by tianshaokui** [comment]
以前好像也有， 也是无法修改日期， 但是默认的时间是很晚。 现在是无法修改，默认时期太早了

**Comment by Mukvin** [comment]
version:1.5.6
该问题已经出现，试用最新的docker repo，结果出现这种问题，该类问题应当优先级最高，并且提供的demo地址中，完全也是一样的错误！
![image](https://user-images.githubusercontent.com/34978943/71768816-f442d380-2f54-11ea-9e0c-c20dca4250ed.png)

**Comment by wojiushixiaobai** [comment]
@Mukvin 请更换浏览器或者更换设备，此问题有用户反馈，但是我无法复现

**Comment by Mukvin** [comment]
@wojiushixiaobai 你好，目前已经验证，在windows和mac上可以进行测试，全部用chrome浏览器，发现mac上提示的是invalid date!而windows正常，这里的时间修改插件是否应该适配下。
