### ISSUE TITLE
资产授权无法添加单个资产

### ISSUE THREAD

**Issue by busyboy-ws** [jumpserver/jumpserver#3542]
[简述你的问题]
资产授权时，选择无法选择对单个资产授权，前端页面报错如下:
![image](https://user-images.githubusercontent.com/21153799/70958164-51b0d680-20b3-11ea-8959-48bf2e64a2a9.png)
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver: 1.4.8
##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/21153799/70958266-ab190580-20b3-11ea-8d70-71cd28463e80.png)

2. [步骤2]
点击确认后报错如上图！
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@busyboy-ws 无法复现，建议更新到最新版本验证下
