### ISSUE TITLE
强制开启MFA可以绕过

### ISSUE THREAD

**Issue by chjtwork** [jumpserver/jumpserver#3543]
[简述你的问题]

##### 使用版本
1.5.5-2

##### 问题复现步骤
1. 给用户强制开启MFA后，此用户只要一直不绑定，就可以一直免MFA登录
2. 如图，登录后进入绑定MFA的页面。只要在绑定页面点击左上角图标，或者直接就地址栏输入访问网页的根路径，就能回到正常的jumpsever页面，使用下来功能也都正常

##### 具体表现[截图可能会更好些,最好能截全]
![a](https://user-images.githubusercontent.com/32709877/70978669-2ba72880-20eb-11ea-83dd-9f1806bef466.png)
![image](https://user-images.githubusercontent.com/32709877/70978946-af611500-20eb-11ea-9dea-7e35122bca17.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个不算绕过，而是这次可以跳过设置，每次登陆的时候，都有这个

**Comment by chjtwork** [comment]
主要考虑是强制让用户使用MFA，如果有人偷懒不想用MFA一直这样跳过的话，并且跳过后，各项功能也可以正常使用，那么强制MFA也无从谈起了

**Comment by jackwang-github** [comment]
感觉是个重大安全漏洞

**Comment by jackwang-github** [comment]
> 这个不算绕过，而是这次可以跳过设置，每次登陆的时候，都有这个

用户可以轻易的绕过，一点也不费力，就谈不上强制验证MFA了哦。

**Comment by feng-2019** [comment]
建议修复此问题，使用jumpserver本身就是为了监控操作，安全，这样跳过，如果用户密码出现泄漏，容易造成严重问题。

**Comment by BaiJiangJie** [comment]
强制用户开启使用 MFA 后可自主绕过的问题，已经在 v1.5.6 版本中做了修复，大家及时更新。

**Comment by jackwang-github** [comment]
@BaiJiangJie 牛逼
