### ISSUE TITLE
为Linux管理用户使用密钥登录，如何配置呢？

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3544]
[简述你的问题]
如题：我想Jumpserver上配置root管理用户使用密钥登录资产和推送，不知道为什么这里要上传私钥，没有理解。
另外我把Linux资产的私上传后。然后并不能链接资产。

![image](https://user-images.githubusercontent.com/58414586/71049735-4f677e80-217e-11ea-9d9e-0dce51182d33.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这里的私钥就是管理用户使用进行ansible任务的私钥，管理用户目前是无法被使用登录到资产的
