### ISSUE TITLE
windows主机远程多个终端使用导致经常冲突

### ISSUE THREAD

**Issue by nameissoso** [jumpserver/jumpserver#3545]
公司内使用windows远程较多，有没有提示当前windows正在被xxx使用中的方法吗？

**Comment by jym503558564** [comment]
管理员可以查看在线会话有哪些

**Comment by nameissoso** [comment]
> 管理员可以查看在线会话有哪些

业务中使用的windows机器比较多，所以如果每次都要向管理员询问是否有人使用，就太浪费时间了，我只是想提个建议，让别人使用之前可以看到谁在使用

**Comment by ibuler** [comment]
即使没有jumpserver也会出现如上问题，目前还不能有统计信息，因为guacamole可能部署多台，下个版本实现了一个动态系统用户，用户名和访问者的用户名一致，避免固定系统用户名的问题
