### ISSUE TITLE
命令记录存储到ES日期格式改成date以及按照日期创建索引的建议

### ISSUE THREAD

**Issue by benevolence-doctor** [jumpserver/jumpserver#3547]
[简述你的问题]
命令记录存储到ES
1. 索引能不能按照日期进行创建例如：jumpserver-2019-12-18
2. ES内查看日期类型是long的格式，能不能换成date ，有的时候需要从ES进行搜索命令日期是long无法查看正确的日期

##### 使用版本
v1.5.5
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13461419/71076286-6a5ae280-21c0-11ea-8ccc-5b21ac186a48.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
es中使用timestamp不是常用的方式吗

**Comment by hzbd** [comment]
https://github.com/jumpserver/jumpserver/issues/3547 相同提问
