### ISSUE TITLE
更新升级至最新版1.5.5-2，新加的资产无法SSH，报错：该主机没有授权系统用户

### ISSUE THREAD

**Issue by dongsong** [jumpserver/jumpserver#3548]
[该主机没有授权系统用户]

##### 使用版本
旧版本[1.4.8]  新版本[1.5.5]

##### 问题复现步骤
1. [添加资产，添加授权]
2. [资产挂载已有Default组，用户加入Default组，可以SSH，更新升级后，挂载至新组，用户也该加入新组则报错：该主机没有授权系统用户]

##### 具体表现
<img width="814" alt="1" src="https://user-images.githubusercontent.com/1272308/71087694-c2e9aa00-21d7-11ea-8bb2-0eb1fb4e2a63.png">

##### 其他
更新最新版后，更新用户加新组时，保存后会置空用户原有ssh公钥。

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
确保各组件版本保持一致，例如升级后，coco ==> koko

**Comment by dongsong** [comment]
早就一起升级为koko了，问题倒是找到了，是由于资产授权添加了动作设置，默认5个动作都是未勾选的，勾选了就可以连接了。不过给用户添加组是覆盖用户的公钥这个bug依然存在。
