### ISSUE TITLE
docker一键部署的，但是web终端无法使用，sftp也无法使用

### ISSUE THREAD

**Issue by l764191074** [jumpserver/jumpserver#3558]
[简述你的问题]

![image](https://user-images.githubusercontent.com/19549484/71310586-c045b980-2450-11ea-87d0-c66c6376295f.png)
始终这个样子，文件管理直接502了，但是不知道为什么批量执行是可以使用的
##### 使用版本
Version 1.5.5-2 
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
koko没启动？

**Comment by l764191074** [comment]
> koko没启动？
好像确认没启动

**Comment by jym503558564** [comment]
koko和gua都启动一下

**Comment by wojiushixiaobai** [comment]
@l764191074 
在web删除所有不在线的组件
docker exec -it jms_all /bin/bash
rm -rf /opt/koko/data/keys/*
rm -rf /config/guacamole/keys/*
exit
docker restart jms_all
