### ISSUE TITLE
邮件设置 测试连接报错

### ISSUE THREAD

**Issue by zyj522931** [jumpserver/jumpserver#3561]
[简述你的问题]
在邮件设置里配置了发件邮箱，测试连接的时候报错，报错代码为：{"error":"(535, b'5.7.3 Authentication unsuccessful')"}  和 {"error":"(501, b'5.1.7 Invalid address', '=?utf-8?q?jiguan?=')"}   xxxx表示smtp账号
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.8-2 GPLv2

##### 问题复现步骤
1. smtp 主机：smtp.xxxx.com
    smtp 端口：25
    smtp 账号：jiguan@xxx.com
    smtp 密码：*
这样配置测试连接报错 {"error":"(535, b'5.7.3 Authentication unsuccessful')"}
2. smtp 主机：smtp.xxxx.com
    smtp 端口：25
    smtp 账号：jiguan
    smtp 密码：*
这样配置测试连接报错 {"error":"(501, b'5.1.7 Invalid address', '=?utf-8?q?jiguan?=')"}

同样的账户 我在Ubuntu系统中的nail.rc配置文件中按照第二种方式配置可以正常发送邮件，配置如下：
set from="jiguan@xxxx.com"
set smtp="smtp://smtp.xxxx.com:25"
set smtp-auth-user="jiguan"
set smtp-auth-password="*"
set smtp-auth=login
set ssl-verify=ignore
set nss-config-dir=/etc/pki/nssdb

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zyj522931 无法复现

**Comment by jym503558564** [comment]
端口是25吗？？

**Comment by nailuozhi** [comment]
{"error":"authentication 
<img width="908" alt="_20200301171230" src="https://user-images.githubusercontent.com/33954460/75622867-e077be80-5bdf-11ea-876c-6cb92f5b7dc9.png">
is required,163 smtp13,EcCowACnwNIUfFteZ+AjkA--.687S2 1583053844"}
