### ISSUE TITLE
1.5.5-2web终端无法连接部分RDP主机

### ISSUE THREAD

**Issue by dukong** [jumpserver/jumpserver#3565]
[简述你的问题]
按照官方文档中的这种模式安装：
Koko、Guacamole 正常部署(仅测试环境使用)
$ yum -y install wget
$ cd /opt
$ wget -O jms_localinstall.sh https://demo.jumpserver.org/download/jms_localinstall.sh
$ sh jms_localinstall.sh

##### 使用版本
1.5.5-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
大部分的主机都是win2016，在新增资产时选择windows2016会导致无法连接，改为windows，大部分都可以了，但是还是有部分主机无法连接。
先是提示：连接中，正在连接，请等待...
大概10秒后，出现：连接错误，无法连接服务器，请联系管理员或者查看日志。
但是可以通过mstsc连接成功。也排除了网络连接和防火墙的问题，ssh到堡垒机可以ping通那台windows主机。
一台win2008r2的主机也出现类似的问题，但是在其系统日志中看到了一些线索，是加密方式的问题，这个2016的主机就没有任何线索。
因为不知道在哪里看web终端的日志，所以无法继续排错，发帖求助来了。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@dukong 
```
# 打开 Windows 远程设置 勾选允许远程到此计算机(L)
# Windows 8/10/2012/2016 手动登录 不要勾选 仅允许运行使用网络级别身份验证的远程桌面的计算机连接(建议)(N)
# Windows 7/2008 手动登录 要勾选 允许运行任意版本远程桌面的计算机连接(较不安全)(L)
```

**Comment by dukong** [comment]
# Windows 8/10/2012/2016 手动登录 不要勾选 仅允许运行使用网络级别身份验证的远程桌面的计算机连接(建议)(N)
这个方法先前已经看到，并尝试了，无效。

**Comment by LeonLiu0804** [comment]
遇到了类似问题，部分资产（windows 2012）rdp无法连接（Guacamole 1.5.2），没有特别的错误log，
通过其他同网段主机远程连接目标资产可以连接，通过堡垒机连接还是刷新不出远程页面，但是可以把之前已经成功连接的主机挤出去。
页面弹出的错误弹框是
"连接错误 远程桌面服务器不在线，如果问题持续，请通知您的系统管理员，或检测您的系统日志。"

**Comment by wangshishuai** [comment]
> @dukong
> 
> ```
> # 打开 Windows 远程设置 勾选允许远程到此计算机(L)
> # Windows 8/10/2012/2016 手动登录 不要勾选 仅允许运行使用网络级别身份验证的远程桌面的计算机连接(建议)(N)
> # Windows 7/2008 手动登录 要勾选 允许运行任意版本远程桌面的计算机连接(较不安全)(L)
> ```
> 
> ```
> "系统平台" 注意下, Windows 10/2012/2016/2019 选择 Windows(2016), 其他的选择 Windows 即可
> ```

最后一句话解决了无法远程windows这个问题。感谢
