### ISSUE TITLE
资产、网关添加支持域名的方式

### ISSUE THREAD

**Issue by yakexi07** [jumpserver/jumpserver#3566]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1.创建网域网关-创建网关-IP  只能填写ipv4或者ipv6，不能填写类似域名或者IP的加速域名，比如54.169.179.xx.ipssh.net类似的加速域名，服务器在海外，国内jumpserver 通过网关去连接的时候很慢，想通过加速域名解决，但是网关只能写IPv4 或者ipv6

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/11204632/71464731-6e58b700-27f5-11ea-90b0-a2b73c2bdb96.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
资产已添加
