### ISSUE TITLE
用nginx转发时koko报错[ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

### ISSUE THREAD

**Issue by linguohu** [jumpserver/jumpserver#3568]
[简述你的问题]
jumpserver使用docker部署在内网，需要nginx代理到外网，链接资产时koko报错提示[ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.5
##### 问题复现步骤
1. [步骤1]
内网机器docker 启动jumpserver/jms_all:1.5.5版本 
2. [步骤2]
在有外网的机器用nginx代理，
nginx配置：
  server {
        listen       8070;

        location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_http_version 1.1;
          proxy_pass http://10.18.1.32;
         }

        location ^~ /ws/ {
          proxy_pass http://10.18.1.32:8070/ws/;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
   }

##### 具体表现[截图可能会更好些,最好能截全]
koko 无法连接资产
![image](https://user-images.githubusercontent.com/12726197/71496809-2c308380-2890-11ea-9c52-55387a491adc.png)
koko 日志报错
[ERRO] ERROR: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@linguohu 
 location / {
        proxy_pass       http://jumpserver;  # jumpserver
        proxy_buffering  off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

**Comment by Linuxrgw** [comment]
我也遇到类似的问题，按照上面的方法未解决。
容器安装 jumpserver, 版本2.5.1 
![image](https://user-images.githubusercontent.com/37529019/109907558-81aac080-7cdd-11eb-8da5-c5d210f52bc3.png)
![image](https://user-images.githubusercontent.com/37529019/109907639-a9018d80-7cdd-11eb-8e38-b87bccb39d71.png)
报错信息
Bad Request
Websocket upgrade err websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
希望大佬能够协助一下
