### ISSUE TITLE
1.5.5-v2jumpserver无法执行批量操作

### ISSUE THREAD

**Issue by kentwanwan** [jumpserver/jumpserver#3569]
[简述你的问题]

1.5.5-v2jumpserver无法执行批量操作任务

如图：
![深度截图_选择区域_20191227140657](https://user-images.githubusercontent.com/49065202/71503932-3cf1f100-28b2-11ea-818b-23d2b0d6dfe9.png)

![深度截图_选择区域_20191227140757](https://user-images.githubusercontent.com/49065202/71503962-5eeb7380-28b2-11ea-80e3-2a6854c7a16a.png)
在任务列表中会提示数据有问题如图：

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
可更新到最新版本，再测试一下，目前最新版本不存在该问题。

**Comment by kentwanwan** [comment]
重新升级最新版本，问题解决。
