### ISSUE TITLE
批量执行命令（部分机器成功，部分机器失败）

### ISSUE THREAD

**Issue by dessler** [jumpserver/jumpserver#357]
Ansible> w

[ dubboService2 => failed]

Failed to open session: SSH session not active

server1 => failed]

Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1489031378.24-261265883741534 && echo $HOME/.ansible/tmp/ansible-tmp-1489031378.24-261265883741534, exited with result 1

[ server2 => failed]

Failed to open session: SSH session not active

[ server3 => failed]

Failed to open session: SSH session not active

[ server4 => failed]

Failed to open session: SSH session not active

[ server5 => Ok]

11:49:28 up 254 days, 18:28, 23 users, load average: 0.00, 0.01, 0.05

**Comment by xm-y** [comment]
我也是

**Comment by rovkxu** [comment]
me too

**Comment by ibuler** [comment]
错误

**Comment by superkzh** [comment]
重启websocket
