### ISSUE TITLE
1.5.5-2web终端无法通过rpd连接一台win2016主机

### ISSUE THREAD

**Issue by dukong** [jumpserver/jumpserver#3573]
[简述你的问题]
按照官方文档中的这种模式安装：
Koko、Guacamole 正常部署(仅测试环境使用)
$ yum -y install wget
$ cd /opt
$ wget -O jms_localinstall.sh https://demo.jumpserver.org/download/jms_localinstall.sh
$ sh jms_localinstall.sh
使用版本

1.5.5-2

具体表现[截图可能会更好些,最好能截全]

先是提示：连接中，正在连接，请等待...
大概10秒后，出现：连接错误，无法连接服务器，请联系管理员或者查看日志。
但是可以通过mstsc连接成功。
也排除了网络连接和防火墙的问题。
win2016主机的日志上也没有线索。
终端管理页面的终端列表显示两个都是激活在线。

已经尝试了：
一，从自动登录改成手动登录。（从表现来看还没到输用户名和密码的阶段）
二，系统平台windows和windows2016都换过。（其他windows2016主机可以换到windows解决）
三，仅允许运行使用网络级别身份验证的远程桌面的计算机连接(建议)，勾不勾选都试过。
四，尝试通过组策略修改。具体是：
打开本地组策略，进入列表目录【计算机配置】-【管理模板】-【windows组件】-【远程桌面服务】-【远程桌面会话主机】-【安全】：
1.设置客户端连接加密级别：已启用，加密级别：客户端兼容
2.远程（RDP）连接要求使用指定的安全层：已启用，安全层：协商（或者其他两项）
3.要求使用网络级别的身份验证对远程连接的用户进行身份验证：已禁用

因为不知道在哪里看web终端的日志，所以无法继续排错，发帖求助来了。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@dukong 在关闭TLS1.0的情况下，修改本地计算机策略
```
计算机策略-Windows设置-安全设置-安全选项-系统加密：将FIPS兼容算法用于加密、哈希和签名-已启用。
重启即可
```
不建议直接开放资产的rdp服务到外网，内网你可以启用tls1.0

**Comment by dukong** [comment]
TLS1.0没有关闭。
尝试了一下启用：将FIPS兼容算法用于加密、哈希和签名。
还是不行。
另一台，将FIPS兼容算法用于加密、哈希和签名，处于禁用状态也是可以正常连接的。
还尝试了使用另一台测试的jumpserver，去连接这台win2016，也是不行。

**Comment by wojiushixiaobai** [comment]
@dukong 检查下资产上面的安全软件，确认下是哪里拦截了。确认系统用户是否正确，以上

**Comment by dukong** [comment]
> 
> 
> @dukong 检查下资产上面的安全软件，确认下是哪里拦截了。确认系统用户是否正确，以上

没装任何安全软件，自带的windows defender也是关闭状态。

**Comment by wojiushixiaobai** [comment]
@dukong 测试无法复现，如果防火墙和远程设置无误
将系统用户改为手动，系统平台换成windows(2016)
web登录时选择跳过，看是否出现登录窗口，如果无法出现，检查资产是否有其他的策略限制。
也可以更换另外的资产测试
