### ISSUE TITLE
Guacamole组件，RDP协议能否开启 console 参数

### ISSUE THREAD

**Issue by guoshuaifeng** [jumpserver/jumpserver#3577]
[简述你的问题]
1、在 Guacamole 的官方文档
http://guacamole.apache.org/doc/gug/configuring-guacamole.html#rdp
对于RDP连接可以开启 console 这个参数，文档中说：
If set to "true", you will be connected to the console (admin) session of the RDP server.

2、目的：在某些版本Windows中远程桌面多人登录会出现一个程序多次启动的现象，用了这个参数。就跟win上面 mstsc /admin 效果一样。

不知道JMS 在哪里开启这个，谢谢！

##### 使用版本：1.5.4-2 
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
最新版本 1.5.6 开始支持设置 console 参数：
创建资产前，先创建自定义系统平台
创建系统平台时，基础平台选择 windows 或 windows 2016后，会出现 console 字段的控制。
![image](https://user-images.githubusercontent.com/32935519/71886506-482d0280-3177-11ea-9161-4e934ac74f38.png)
最后，在创建资产页面，选择自定义系统平台。
![image](https://user-images.githubusercontent.com/32935519/71886460-321f4200-3177-11ea-90ce-27596237c6d7.png)

**Comment by guoshuaifeng** [comment]
OK，我去升级先。谢谢
