### ISSUE TITLE
coco/koko登陆终端均不支持不支持上下键，翻阅历史命令

### ISSUE THREAD

**Issue by sjsfyzs** [jumpserver/jumpserver#3578]
[简述你的问题]
coco登陆终端不支持上下键，翻阅历史命令

##### 使用版本
jumpserver的 版本是1.4.10，coco的版本也是1.4.10

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16409120/71572269-2dc0ac80-2b19-11ea-8c40-619fe4e7d915.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@sjsfyzs @ibuler  koko可以上下键，翻阅历史命令，coco则不行。

**Comment by sjsfyzs** [comment]
@LeeEirc koko从哪个版本，开始支持上下键翻阅历史命令的

**Comment by LeeEirc** [comment]
@sjsfyzs 一直就支持，你先装试一下，自己操作一下。
