### ISSUE TITLE
日期选择组件异常

### ISSUE THREAD

**Issue by e1vish** [jumpserver/jumpserver#3584]
[日期选择组件异常]

##### 使用版本
[1.5.5]

##### 问题复现步骤
1. [登陆Jumpserver管理界面]
2. [打开权限管理-资产授权]
3. [点击创建授权规则]
4. [有效期一栏日期选择显示invalid date]

##### 具体表现[]
![image](https://user-images.githubusercontent.com/17349011/71620899-4a3b1280-2c07-11ea-9a38-1d058d2b6c93.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by e1vish** [comment]
Finished.

**Comment by laiwahwing** [comment]
我也遇到了这个问题, 怎么解决的呢?

**Comment by JarodWan** [comment]
我也遇到了这个问题， 能否讲解一下怎么解决这个问题啊

**Comment by JarodWan** [comment]
Finished,  原来是姿势不对

**Comment by paraparak** [comment]
> Finished, 原来是姿势不对

請問怎樣解決,什麼是姿势不对??

**Comment by JarodWan** [comment]
> > Finished, 原来是姿势不对
> 
> 請問怎樣解決,什麼是姿势不对??

你在日期选择框里面 输入一个数字而不是直接去选择，比如1 ，系统就会协助你了   不知道我表达是否清晰明确

**Comment by paraparak** [comment]
> > > Finished, 原来是姿势不对
> > 
> > 
> > 請問怎樣解決,什麼是姿势不对??
> 
> 你在日期选择框里面 输入一个数字而不是直接去选择，比如1 ，系统就会协助你了 不知道我表达是否清晰明确

謝謝解答,這樣只能每次都打一次數字才能正常,不像以前一進入就可以正顯示
