### ISSUE TITLE
jumpserver命令行界面提示没有批量执行

### ISSUE THREAD

**Issue by sccblue** [jumpserver/jumpserver#3587]
[简述你的问题]

##### 使用版本
Version 1.5.5-2 GPLv2.
Copyright FIT2CLOUD 飞致云 © 2014-2019

##### 问题复现步骤
ssh zhihe@jumpserver -p 2222
		志和,  欢迎使用Jumpserver开源堡垒机系统

	1) 输入 部分IP、主机名、备注 进行搜索登录(如果唯一).
	2) 输入 / + IP，主机名 or 备注 进行搜索，如：/192.168.
	3) 输入 p 进行显示您有权限的主机.
	4) 输入 g 进行显示您有权限的节点.
	5) 输入 r 进行刷新最新的机器和节点信息.
	6) 输入 h 进行显示帮助.
	7) 输入 q 进行退出.
##### 具体表现[截图可能会更好些,最好能截全]
没有E/e批量执行的选择

**Comment by jym503558564** [comment]
批量执行功能可在web页面执行

**Comment by sccblue** [comment]
我知道可以在web执行，我想知道是不是关闭了命令行的批量执行功能，毕竟之前的版本是可以的
