### ISSUE TITLE
Version 1.5.5-2 GPLv2. 出现 [log WARNING] Not Found: /socket.io/

### ISSUE THREAD

**Issue by zhb127** [jumpserver/jumpserver#3590]
[简述你的问题]
使用代码仓库：https://github.com/jumpserver/Dockerfile/tree/b57b816eb0be6aca0154d21ccff2933ffb1c29c5
部署后，出现大量告警日志：2020-01-03 16:37:23 [log WARNING] Not Found: /socket.io/

##### 使用版本
Version 1.5.5-2 GPLv2.
![image](https://user-images.githubusercontent.com/5210208/71714018-19e1b700-2e47-11ea-8daf-de90c411fd90.png)

##### 问题复现步骤
使用代码仓库：https://github.com/jumpserver/Dockerfile/tree/b57b816eb0be6aca0154d21ccff2933ffb1c29c5
部署后，出现大量告警日志：2020-01-03 16:37:23 [log WARNING] Not Found: /socket.io/

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/5210208/71713985-f74f9e00-2e46-11ea-9694-f871fcd80e4d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhb127 检查你的nginx配置是否有问题

**Comment by zhb127** [comment]
目前问题已解决，/etc/nginx/conf.d/jumpserver.conf 添加 location /socket.io/ {} 解决。
不过，应该是代码仓库：https://github.com/jumpserver/Dockerfile/tree/b57b816eb0be6aca0154d21ccff2933ffb1c29c5
更换了 koko 以后，有调整 socket.io 所致，有在 koko server.go 文件，找到如下代码片段：
![image](https://user-images.githubusercontent.com/5210208/71811872-ba86df80-30b0-11ea-8af5-458a26e17609.png)

**Comment by MinuxL** [comment]
```text
# 1.4.10升级到2.3.2 发现存在大量的请求到"/socket.io/"的链接. 我看升级引导nginx配置是没有这个的后端的配置的, 以前的配置是指向coco的后端服务 如今更新为koko.
# 限制我很困惑 我不知道这个是哪里发起的 怎么去掉他 我这2.3.2下好像没有找到需要请求到/socket.io/的地方. (以下502状态吗是手动配置的)
"GET /socket.io/?EIO=3&transport=polling&t=NKtb5U0 HTTP/2.0" 502 0.000 559 "https://domain.com/luna/?login_to=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
```

**Comment by zhb127** [comment]
> ```
> # 1.4.10升级到2.3.2 发现存在大量的请求到"/socket.io/"的链接. 我看升级引导nginx配置是没有这个的后端的配置的, 以前的配置是指向coco的后端服务 如今更新为koko.
> # 限制我很困惑 我不知道这个是哪里发起的 怎么去掉他 我这2.3.2下好像没有找到需要请求到/socket.io/的地方. (以下502状态吗是手动配置的)
> "GET /socket.io/?EIO=3&transport=polling&t=NKtb5U0 HTTP/2.0" 502 0.000 559 "https://domain.com/luna/?login_to=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
> ```

发起请求的地方得从源码里面去搜索关键字找了。
之前我是这么找的，后面是自己重新弄了一下 dockerfile 把 nginx.conf 里面缺的 scoket.io 补充上去。

**Comment by MinuxL** [comment]
> > ```
> > # 1.4.10升级到2.3.2 发现存在大量的请求到"/socket.io/"的链接. 我看升级引导nginx配置是没有这个的后端的配置的, 以前的配置是指向coco的后端服务 如今更新为koko.
> > # 限制我很困惑 我不知道这个是哪里发起的 怎么去掉他 我这2.3.2下好像没有找到需要请求到/socket.io/的地方. (以下502状态吗是手动配置的)
> > "GET /socket.io/?EIO=3&transport=polling&t=NKtb5U0 HTTP/2.0" 502 0.000 559 "https://domain.com/luna/?login_to=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
> > ```
> 
> 发起请求的地方得从源码里面去搜索关键字找了。
> 之前我是这么找的，后面是自己重新弄了一下 dockerfile 把 nginx.conf 里面缺的 scoket.io 补充上去。

```text
经过两天的运行 今天想把这个问题重新收集下信息的 发现“/socket.io/”的请求不见了 
不过在升级后我检测的时候就怀疑是有人为了会话保持用浏览器插件刷的 
加上是前版本遗留的资源 后来重启加载新版资源就好了 我想应该是这样 目前也没发现有我就暂时不管了 
后面如果还出现再提吧 thanks
```
