### ISSUE TITLE
Jumpserver 1.5.3 报错:connect websocket server error

### ISSUE THREAD

**Issue by garywu520** [jumpserver/jumpserver#3593]
[简述你的问题]
很久没使用jumpserver配置系统用户了，今天使用过程中报错:connect websocket server error

##### 使用版本
 Jumpserver 1.5.3 

##### 问题复现步骤
系统用户 -- 测试连通性 -- 报错：connect websocket server error

自己检查了各个组件服务均正常，各组件服务重启问题依旧，nginx中ws已配置，配置如下：
    location /ws/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8070;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

**Comment by garywu520** [comment]
Web浏览器访问ws接口:
https://xx.xx.xx.xx/ws/ 返回如下字符串，看起来正常
{"msg": "Websocket server run on port: 8081, you should proxy it on nginx"}

**Comment by BaiJiangJie** [comment]
外层 Nginx 应该没有配 /ws 的路由

**Comment by mlshaw** [comment]
@garywu520 请问这个问题解决了吗，我也是这样

**Comment by garywu520** [comment]
> @garywu520 请问这个问题解决了吗，我也是这样，我使用的版本是1.5.5

还没解决

**Comment by garywu520** [comment]
> 外层 Nginx 应该没有配 /ws 的路由

怎么讲？

**Comment by garywu520** [comment]
升级到1.5.6问题依然存在，URL改成HTTPS也没解决这个问题。谁来给解答下？

**Comment by zhangax** [comment]
我也发现这个问题了，这不坑了么？我用的1.5.4

**Comment by zhangax** [comment]
有哪位大佬解决了吗？还望不吝赐教

**Comment by BaiJiangJie** [comment]
看看后台后没有报错

**Comment by zhangax** [comment]
报错并没有看到，我还部署过1.5.3，也有这个问题

**Comment by jetyte** [comment]
> Web浏览器访问ws接口:
> https://xx.xx.xx.xx/ws/ 返回如下字符串，看起来正常
> {"msg": "Websocket server run on port: 8081, you should proxy it on nginx"}

我和你遇到的情况一样，我的解决方式为：我仔细研究了安装文档，发现防火墙没有开放8081端口，所以添加防火墙策略：firewall-cmd --permanent --add-rich-rule="rule family="ipv4" source address="172.17.0.0/16" port protocol="tcp" port="8081" accept"  ，然后把重启了一下服务器，问题解决。

**Comment by dongbo0737** [comment]
我遇到的问题是，服务端的web socket服务挂掉了

**Comment by dongbo0737** [comment]
问题是日志里面根本没报错。。很神奇。。

**Comment by DDDDDDDDDDDDLANG** [comment]
应该是nginx没配置好，可以参考下dockerhub里jms_all镜像的dockerfile配置，或者起一个jms_all容器查看内部nginx的jumpserver.conf配置，如下
`server {
    listen 80;
    # server_name _;

    client_max_body_size 100m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
        expires 24h;
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
        expires 24h;
    }

    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /ws/ {
	proxy_pass http://localhost:8070;
	proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://localhost:8080;
	proxy_request_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}`

**Comment by DDDDDDDDDDDDLANG** [comment]
应该是nginx没配置好，可以参考下dockerhub里jms_all和docker文件配置，或者从一个jms_all容器查看内部nginx的jumpserver.conf配置，如下：
`
server {
    listen 80;
    # server_name _;

    client_max_body_size 100m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
        expires 24h;
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
        expires 24h;
    }

    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /ws/ {
	proxy_pass http://localhost:8070;
	proxy_buffering off;
        proxy_http_version 1.1;
	proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://localhost:8080;
	proxy_request_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
`

**Comment by geniuscirno** [comment]
打开推送的页面,按F12
![image](https://user-images.githubusercontent.com/23693514/84256741-e8cc8780-ab46-11ea-9ab2-339ec845f23d.png)
可以看到具体的报错信息,我这边的情况是,我最外层有一个https->http的nginx代理,只代理了http请求,没有代理ws请求,添加wss的代理规则就好了.
` 
   location / {
        proxy_pass http://172.31.61.143:8080;
    }

    location /ws/ {
        proxy_pass http://172.31.61.143:8080;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }
`

**Comment by guoqingcun** [comment]
问题解决了吗？咋就关了呢

**Comment by DDDDDDDDDDDDLANG** [comment]
https://github.com/jumpserver/jumpserver/issues/3593#issuecomment-637889922




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月14日(星期二) 下午5:55
收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送:&nbsp;"潮汐"<396174609@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] Jumpserver 1.5.3 报错:connect websocket server error (#3593)





 
问题解决了吗？咋就关了呢

**Comment by evenson419** [comment]
> 打开推送的页面,按F12 ![image](https://user-images.githubusercontent.com/23693514/84256741-e8cc8780-ab46-11ea-9ab2-339ec845f23d.png) 可以看到具体的报错信息,我这边的情况是,我最外层有一个https->http的nginx代理,只代理了http请求,没有代理ws请求,添加wss的代理规则就好了. `
> 
> ```
> location /ws/ {
>     proxy_pass http://172.31.61.143:8080;
>     proxy_buffering off;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     access_log off;
> }
> ```
> 
> `

所有都配置了，但还是不行？

**Comment by evenson419** [comment]
> 打开推送的页面,按F12 ![image](https://user-images.githubusercontent.com/23693514/84256741-e8cc8780-ab46-11ea-9ab2-339ec845f23d.png) 可以看到具体的报错信息,我这边的情况是,我最外层有一个https->http的nginx代理,只代理了http请求,没有代理ws请求,添加wss的代理规则就好了. `
> 
> ```
> location /ws/ {
>     proxy_pass http://172.31.61.143:8080;
>     proxy_buffering off;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     access_log off;
> }
> ```
> 
> `

我的配置
![image](https://user-images.githubusercontent.com/35451163/145319197-e0c2520f-9407-48a1-b066-c552333606e5.png)

**Comment by Hamerle** [comment]
这个问题要结合情况看吧，官方文档结尾有说是代理配置的问题https://docs.jumpserver.org/zh/master/admin-guide/proxy/，
我是多层代理，jumpserver外边还有一层nginx，我在外层nginx中配置了websocket长连接后就恢复正常了。
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
