### ISSUE TITLE
日期組件失效問題

### ISSUE THREAD

**Issue by paraparak** [jumpserver/jumpserver#3595]
[简述你的问题]
在創建新用戶時的失效日期都變了:invalid date

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver 1.5.6
##### 问题复现步骤
1. [步骤1]用戶管理 >>>>>>>用戶列表
2. [步骤2]創建用戶 後失效日期都變了invalid date

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/59550921/71796164-6bc35080-3084-11ea-93a3-9fbf4f3016f8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
最好使用 Chrome 瀏覽器，右擊查看一下 console 控制台有沒有抱錯信息

**Comment by paraparak** [comment]
> 最好使用 Chrome 瀏覽器，右擊查看一下 console 控制台有沒有抱錯信息
我開了應該是沒錯誤
![image](https://user-images.githubusercontent.com/59550921/71804820-9373e200-309f-11ea-8d5b-60d748b7fe64.png)
有其他用家說在日期上打一個數字就可以正常了,但不能治根

**Comment by BaiJiangJie** [comment]
這個問題已經修復到 dev 分支了，master 還未更新。

**Comment by BaiJiangJie** [comment]
問題已修復，及時更新最新的 master 分支。

**Comment by paraparak** [comment]
> 問題已修復，及時更新最新的 master 分支。

你好,請問怎樣更新到最新的master?
