### ISSUE TITLE
我知道可以在web执行，我想知道是不是关闭了命令行的批量执行功能，毕竟之前的版本是可以的

### ISSUE THREAD

**Issue by sccblue** [jumpserver/jumpserver#3599]
我知道可以在web执行，我想知道是不是关闭了命令行的批量执行功能，毕竟之前的版本是可以的

_Originally posted by @sccblue in https://github.com/jumpserver/jumpserver/issues/3587#issuecomment-570984690_

**Comment by BaiJiangJie** [comment]
之前的版本支持，最新的版本不支持在 Terminal 端进行批量命令的执行

**Comment by sccblue** [comment]
可以指定下是基于什么背景关闭的吗？

**Comment by sccblue** [comment]
可以指定下是基于什么考虑而关闭它的吗？

**Comment by sccblue** [comment]
可以指导下是基于什么考虑而关闭它的吗？

**Comment by ibuler** [comment]
之前版本，jumpserver就一个组件，单独部署的，所以命令行，页面都支持，现在koko/coco独立成组件了，分布式部署，另外现在执行批量命令使用了celery任务异步执行，之前本身就直接连接服务器执行了。这为coco/koko实现带来了难度，所以从命令行移除了

**Comment by sccblue** [comment]
好的，理解了
