### ISSUE TITLE
koko占用load较高

### ISSUE THREAD

**Issue by wzhlinux** [jumpserver/jumpserver#3601]
[简述你的问题]
用户操作录像是否可以不记录系统返回信息？用户长时间查看日志导致录像持续生成，io负载高；
目前服务器400台左右，在线会话50左右。服务器16C

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.2
##### 问题复现步骤
1. 初步发现koko的机器负载较高
2. 最终发现有用户使用tail -f 会持续在磁盘生成录像导致磁盘io崩溃

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/26629417/71866524-59f3b300-3141-11ea-92b7-3cfffb7c04b0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by superman1qaz** [comment]
这个问题怎么处理的？

**Comment by liangxy-luf** [comment]
升级版本解决

**Comment by superman1qaz** [comment]
只升级koko组件就可以吧，其他不需要升级吧？

**Comment by liangxy-luf** [comment]
是的         统一升级一下也好 ，我是直接都升级了


 原始邮件 
发件人: superman1qaz<notifications@github.com>
收件人: jumpserver/jumpserver<jumpserver@noreply.github.com>
抄送: liangxy-luf<18310407638@163.com>; Comment<comment@noreply.github.com>
发送时间: 2020年1月14日(周二) 12:05
主题: Re: [jumpserver/jumpserver] koko占用load较高 (#3601)


只升级koko组件就可以吧，其他不需要升级吧？

**Comment by wzhlinux** [comment]
> 这个问题怎么处理的？
升级最新这个问题也解决不了，我把长时间在线的用户踢出去。用elk代替登录服务器看日志

**Comment by wzhlinux** [comment]
问题已解决，将koko单独拉出给与docker挂载路径ssd磁盘，cpu等待磁盘问题解决。目前一千台服务器100GB SSD硬盘使用3%，日活用户40左右
