### ISSUE TITLE
节点下新增的机器批量命令执行报没权限

### ISSUE THREAD

**Issue by chestarss** [jumpserver/jumpserver#3607]
[简述你的问题]
授权用户 使用admin 用户访问资产节点下的所有机器， 后续在资产节点下新增机器，用户权限并没有继承。

jango.core.exceptions.ObjectDoesNotExist: AssetUserManager Object matching query does not exist
AssetUserManager Object matching query does not exist
Traceback (most recent call last):
  File "/opt/xd/jumpserver/apps/ops/inventory.py", line 113, in get_run_user_info
    run_user = manager.get(self.run_as, asset)
  File "/opt/xd/jumpserver/apps/assets/backends/manager.py", line 75, in get
    self.raise_does_not_exist(self.__class__.__name__)
  File "/opt/xd/jumpserver/apps/assets/backends/manager.py", line 80, in raise_does_not_exist
    raise self.ObjectDoesNotExist(self.MSG_NOT_EXIST.format(name))
django.core.exceptions.ObjectDoesNotExist: AssetUserManager Object matching query does not exist
$ df (2020-01-07 20:04:28) ************************************************************************************
xxxxx.xxx.hostname. | FAILED! =>
Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by sccblue** [comment]
我也碰到过了，老铁
临时解决方案是：
 1 删除整个授权，等一会后重新添加节点的授权
 2 在授权里面单独选择没有权限的机器或者节点再次添加，等待系统完成更新后，去掉这个”有碍观瞻“的名称

**Comment by BaiJiangJie** [comment]
问题已修复到最新的master分支，及时更新。
