### ISSUE TITLE
求助，怎么关闭网页404的debug显示，不显示错误信息，只显示404界面。

### ISSUE THREAD

**Issue by liujinye213** [jumpserver/jumpserver#361]
现在网页会显示debug信息，应该是Django的bebug是开启的，求助怎么关闭？

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by ibuler** [comment]
关闭debug模式，但这时需要nginx来作为web服务器，负责静态文件响应

**Comment by yang-sheep** [comment]
求问在哪里管理debug信息，小白找不到，谢谢
