### ISSUE TITLE
提示优化

### ISSUE THREAD

**Issue by neighbour-oldhuang** [jumpserver/jumpserver#3610]
[简述你的问题]
当管理用户被用于资产时候, 删除此管理用户会直接报 internal error , 建议提示当前用户在使用中不可删除

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.6]
1.5.6
##### 问题复现步骤
1. 添加管理用户a
2. 资产关联管理用户a
3. 删除管理用户

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
已更新到 dev 分支

**Comment by BaiJiangJie** [comment]
@neighbour-oldhuang master 已修复，及时更新。
