### ISSUE TITLE
用nginx反向代理内网JMS后，登录windows主机非常慢，有人遇到过这个问题吗？

### ISSUE THREAD

**Issue by amoscx** [jumpserver/jumpserver#3611]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.4.10 注: 0.3.x不再提供支持]

##### 问题复现步骤
1.用内网地址连接正常。
2.在网关用任意端口转发到外网连接也正常。
3.用nginx反向代理内网地址发布到外网，登录进windows主机后延迟非常大，几乎无法操作。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@amoscx 
每层nginx都加上下面这三行

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
