### ISSUE TITLE
这个问题没有解决，我在最新的1.5.6版本也碰到了，我是因为1.5.5没解决，升级到最新的1.5.6上来看看的，还是没解决

### ISSUE THREAD

**Issue by sccblue** [jumpserver/jumpserver#3612]
这个问题没有解决，我在最新的1.5.6版本也碰到了，我是因为1.5.5没解决，升级到最新的1.5.6上来看看的，还是没解决

_Originally posted by @sccblue in https://github.com/jumpserver/jumpserver/issues/3314#issuecomment-572360135_

**Comment by sccblue** [comment]
接上一个issue https://github.com/jumpserver/jumpserver/issues/3314

**Comment by BaiJiangJie** [comment]
看了一下确实存在，已经修复到 master 了，及时更新。

**Comment by sccblue** [comment]
谢谢
