### ISSUE TITLE
关于服务器账号绕过jumpserver登录问题

### ISSUE THREAD

**Issue by kun376361** [jumpserver/jumpserver#3615]
[简述你的问题]

##### 使用版本
[1.4.10-2]

##### 具体表现[截图可能会更好些,最好能截全]
通过jumpserver为用户A开通授权服务器账号root或其他普通账号，这时用户A将用户B用户C的公钥添加到~/.ssh/authorized_keys，用户B用户C即可不通过jumpserver登录服务器。

网络层可以通过策略限制只允许访问jumpserver端口来实现，我想知道不通过网络层，jumpserver侧有办法实现限制吗？

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
需要在网络层、防火墙或者服务器端对SSH连接的访问进行控制，目前 Jumpserver 端还不能够进行限制。

**Comment by unixchina** [comment]
> 

这是属于系统层面控制的事情，jumpserver管不了。你可以在jumpserver所在主机上只允许指定的账号ssh登录
