### ISSUE TITLE
关于Linux服务器互信问题

### ISSUE THREAD

**Issue by kun376361** [jumpserver/jumpserver#3616]
[简述你的问题]

##### 使用版本
[1.4.10-2]

##### 具体表现[截图可能会更好些,最好能截全]
关于服务器互信如何实现，目前通过jumpserver登录服务器无法在服务器之间传输文件，如何配置实现服务器互信。服务器通过私钥登录。

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
最好贴一下日志

**Comment by kun376361** [comment]
会提示没有权限。

比如我通过jumpserver分别可以登录服务器A和服务器B，服务器是通过私钥管理，当我登录服务器A的时候scp文件到服务器B的时候会提示没有权限。因为服务器配置的是jumpserver服务器的密钥登录，我不通过jumpserver的话就没办法登录服务器B，这种服务器之间scp的情况有办法解决吗？

**Comment by awklinux** [comment]
少量文件可以使用nc互传
A服务器接收 nc -l 9995 > test.txt
B服务器发送 nc aip 9995 < test.txt
不需要验证，只要防火墙允许端口即可，很方便
