### ISSUE TITLE
如何修改jumpserver的登陆首页？

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#3619]
[简述你的问题]
我想把Jumpserver的首页进行修改，改成我自定义的文字内容，或者是去掉首页左侧的那一串文字，还有就是替换成我自己的logo图片，具体怎么实现呢？

##### 使用版本
V1.5

**Comment by ibuler** [comment]
修改 authentication/templates/authentication/login.html

**Comment by wangjiadongpro** [comment]
为啥我没有找到 authentication/templates/authentication/login.html 这个页面
