### ISSUE TITLE
1.5.5版本koko进展的CPU占用率很高

### ISSUE THREAD

**Issue by superman1qaz** [jumpserver/jumpserver#3620]
[简述你的问题]
koko进程的cpu占用率很高，4U的机器4个核全部100%跑满了呢

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.5
##### 问题复现步骤
1. [步骤1]
koko进程CPU占用率持续100%
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52227054/72134246-7ea88e80-33be-11ea-97cf-45fb48934cea.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
@LeeEirc 最新的 master 修复了吗？

**Comment by LeeEirc** [comment]
@superman1qaz 更新到1.5.6的最新版本，修复了因输入卡顿造成的CPU高问题。

**Comment by BaiJiangJie** [comment]
@superman1qaz 更新到最新版本试一下

**Comment by zhixiangjoy** [comment]
同样 jumpserver 1.5.5-2 coco cpu占用100%,明天升级看下
