### ISSUE TITLE
v1.4.10版本使用API添加资产报错

### ISSUE THREAD

**Issue by mds1455975151** [jumpserver/jumpserver#3623]
[简述你的问题]
v1.4.10版本使用API添加资产报错

##### 使用版本
v1.4.10

##### 问题复现步骤
使用API添加资产报错脚本如下
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
import json
import yaml
import sys
import uuid

reload(sys)
sys.setdefaultencoding('utf-8')

if len(sys.argv) != 3:
    print("Usages: python %s conf_file host_info_list" % (sys.argv[0]))
    exit(1)

conf_file = sys.argv[1]
host_info_file = sys.argv[2]

def read_config(config_file):
    f = open(config_file)
    conf_yaml = yaml.load(f, Loader=yaml.FullLoader)
    _config = conf_yaml
    return _config

def assets_create(_asset_info):
    url = '{}/api/assets/v1/assets/'.format(
        jms_url,
    )
    response = requests.patch(url, data=json.dumps(_asset_info), headers=header_info)
    if response.status_code == 200:
        print("资产添加成功")
    else:
        # print(response.text)
        error_message = json.loads(response.text).get('non_field_errors')
        if error_message:
            print("资产添加失败: {}".format(json.loads(response.text)['non_field_errors'][0]))
        else:
            print(response.text)

def get_asset_admin_user_id_by_name(_admin_user):
    url = '{}/api/assets/v1/admin-user/'.format(
        jms_url
    )
    response = requests.get(url, headers=header_info)
    admin_user_list = json.loads(response.text)
    for admin_user_info in admin_user_list:
        name = admin_user_info['name']
        _admin_user_id = admin_user_info['id']
        if name == _admin_user:
            return _admin_user_id

def get_asset_node_id_by_name(_node_name):
    url = '{}/api/assets/v1/nodes/'.format(
        jms_url
    )
    response = requests.get(url, headers=header_info)
    nodes_list = json.loads(response.text)
    for nodes_info in nodes_list:
        value = nodes_info['value']
        _node_name_id = nodes_info['id']
        if value == _node_name:
            return _node_name_id

def read_asset_info():
    asset_list = []
    f = open(host_info_file)
    for line in f:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        _hostname, _wan_ip, _lan_ip, _admin_user, node_name = line.split()[:5]
        admin_user_id = get_asset_admin_user_id_by_name(_admin_user)
        nodes_id = get_asset_node_id_by_name(node_name)
        # asset_id = str(uuid.uuid4())
        info = {
            # "id": asset_id,
            "ip": _wan_ip,
            "hostname": _hostname,
            "protocol": "ssh",
            "port": 22,
            "platform": "Linux",
            "is_active": True,
            "public_ip": _wan_ip,
            "admin_user": admin_user_id,
            "nodes": nodes_id
        }
        print(info)
        asset_list.append(info)
        assets_create(asset_list)

def main():
    print("#" * 10, "start create assets", "#" * 10)
    read_asset_info()

if __name__ == '__main__':
    config = read_config(conf_file)
    token = config['api_private_token']
    jms_url = config['jms_url']
    header_info = {'content-type': "application/json", "Authorization": 'Token ' + token}
    main()

config文件
---
jms_url: 'https://xxx/
api_private_token: 'xxx'

资产列表
cat host_info_file.txt 
# node_name                                   wan_ip         lan_ip         admin_user      node
jms-api-test-1.1.1.1-1.1.1.1    1.1.1.1 1.1.1.1 global_keys     Default

执行方法：
 python jms_api_assets_bulk_create.py config.yml host_info_file.txt 

报错信息
![image](https://user-images.githubusercontent.com/12950929/72145779-28474a00-33d6-11ea-991d-2fb216955fdc.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
这个问题在最新版本中已经修复

**Comment by mds1455975151** [comment]
啥问题 有相关说明吗 暂时不能直接升级版本

**Comment by BaiJiangJie** [comment]
获取提交数据的id值失败了
