### ISSUE TITLE
从1.5.5更新到1.5.6后出现严重bug

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#3625]
[简述你的问题]

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
不论是移动资产到某个节点、更改授权规则，都会出现以下的错误：
![image](https://user-images.githubusercontent.com/11138015/72216959-ed265180-3562-11ea-8041-759f73d3a760.png)

导致：
无法移动资产到某个节点；
添加资产到授权规则后，在系统用户里搜索不到被新添加的资产；
在系统用户里搜索任何关键词都返回空结果。

但是可以过jms启动时检查数据库迁移的自检。

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
已修复到 master 分支，及时更新。

**Comment by BaiJiangJie** [comment]
在系统用户里搜索任何关键词都返回空结果。
这是因为系统用户详情->资产管理页面，搜索使用全名搜索，不支持模糊搜索。
