### ISSUE TITLE
新版本ssh terminal无法切换英文

### ISSUE THREAD

**Issue by gm12367** [jumpserver/jumpserver#3626]
[简述你的问题]
新版本ssh terminal无法切换英文

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4
##### 问题复现步骤
1. ssh JumpserverIP:2222
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16630392/72228831-28696480-35e5-11ea-8791-6b6f92362a4e.png)

##### 其他
旧版本的ssh terminal可以输入s切换中英文，新版本无法切换英文

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新版本已无法直接切换，可以修改配置文件，
LANG: en
