### ISSUE TITLE
有没有一键登录ssh机器的功能呢

### ISSUE THREAD

**Issue by me10zyl** [jumpserver/jumpserver#3627]
ssh -p 2222 user@ip '192.168.1.9'
每次ssh jumpserver后还要选择机器特别麻烦，比如这样，他会提示Request type `session:exec` not support now，我想直接通过一个命令连接到这个机器有没有办法呢。

**Comment by BaiJiangJie** [comment]
目前没有

**Comment by huyangcheng** [comment]
目前还是没用吗

**Comment by LeeEirc** [comment]
自 JumpServer v2.11.0版本中，支持通过SSH工具直连资产。
使用命令格式：ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222，如果能匹配到唯一资产、唯一系统用户名，则可直接登录该资产。如匹配到多个同IP资产，则用户可自主选择资产以及系统用户进行登录。
