### ISSUE TITLE
[请注意]账号密码明文登录

### ISSUE THREAD

**Issue by xeooon** [jumpserver/jumpserver#3635]
[简述你的问题]
    web登录jumpserver时，输入用户名和密码，此过程为明文传输。

##### 使用版本
[版本为1.5.6]

##### 问题复现步骤
1. 打开jumpserver的登录页面
2. 输入jumpserver的用户名和密码
3. 点击登录

##### 具体表现[截图可能会更好些,最好能截全]
百度云盘的照片地址:https://pan.baidu.com/s/1raLASJUkhXyjKmMrJzCh2A
![密码明文传输](https://user-images.githubusercontent.com/22724267/72247011-f54bc300-362e-11ea-93f9-a7fd21661f1e.jpg)

##### 其他

[注:] 完成后请关闭 issue

**Comment by KubeOperator** [comment]
你可以用同样办法测试其他系统的登录，都会在本地浏览器中看到明文密码。如果你想在传输过程加密，可以可以使用 https。

**Comment by xeooon** [comment]
> 你可以用同样方法测试其他系统的登录，都会在本地浏览器中看到明文密码。如果你想在传输过程加密，可以可以使用https。

您好:
       非常感谢您的回复，谢谢。
       通过简单查看源码，我理解的情况是这样的，前端未加密，密码明文传输到后端，后端直接与数据库进行对比。

建议:
       1.如果是全链路加密的话，是需要在前端js进行加密，后端接收解密与数据库进行对比。
       2.如果前端不加密，密码明文传输到后端，后端进行加盐加密后与数据库秘钥进行对比。


期待您的再次回复，谢谢。

**Comment by ibuler** [comment]
已排期  #4170

**Comment by ibuler** [comment]
暂时关闭这个issue, 查看最新的处理结果
