### ISSUE TITLE
历史会话中的遠端地址問題

### ISSUE THREAD

**Issue by paraparak** [jumpserver/jumpserver#3637]
[简述你的问题]
在內聯使用jumpserver 登錄後出來的遠端地址會是172.16.0.X,不是真正client的地址,有些使用者是可以正常記錄client ip,但有時就只會記錄jumpserver 自己的內部IP,求解答

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Jumpserver版本 1.5.6
##### 问题复现步骤
1. [步骤1] 会话管理
2. [步骤2] 历史会话

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/59550921/72308515-a007c400-36b7-11ea-954e-72250793a638.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@paraparak 请说明部署方式

**Comment by paraparak** [comment]
資產是用ssh
![image](https://user-images.githubusercontent.com/59550921/72488912-5e108680-384d-11ea-9353-27d4ec2bfbfa.png)

管理和系統用戶 都是用ssh私匙,都有sudo權限
