### ISSUE TITLE
你们的软件商业使用需要授权吗？

### ISSUE THREAD

**Issue by CodeIsWorld** [jumpserver/jumpserver#3640]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by KubeOperator** [comment]
Jumpserver 采用 GPL 开源协议，可以免费试用；如果您需要企业版及商业服务，可以致电：400-052-0755。

**Comment by yaojunWang** [comment]
企业版的区别是什么呢?  开源版本是免费试用?  还是免费使用?
