### ISSUE TITLE
rdp authentication 

### ISSUE THREAD

**Issue by mousazade** [jumpserver/jumpserver#3641]
jumpserver  1.4.5

1.We want to ask for usernames and passwords in the terminal environment when connecting to the server with rdp
is it possible ? How ?
Please see the photo.

![Screenshot from 2020-01-14 11-22-19](https://user-images.githubusercontent.com/33278412/72324560-7acb8380-36c0-11ea-8e42-7ed42569f522.png)
![Screenshot from 2020-01-14 11-22-11](https://user-images.githubusercontent.com/33278412/72324561-7acb8380-36c0-11ea-8fd1-52cea7e3b95a.png)

**systemuser setting for myUser -- > (rdp protocol)and(manulay login) Not Working For Manualy Connect to Remote Desktop**

**Comment by jym503558564** [comment]
The systemuser settings are shown in the figure.
![image](https://user-images.githubusercontent.com/40739051/72332808-a87eef80-36f5-11ea-873b-892cf55b7f4d.png)

**Comment by mousazade** [comment]
Yes, these are the settings for logging in manually
But the problem we have is shown in the image below
![Screenshot from 2020-01-14 11-22-19](https://user-images.githubusercontent.com/33278412/72342358-8c715300-36e1-11ea-901c-4af2e83b27f1.png)

**This problem can be resolved when the settings to auomatic login

**Comment by lvxiaohu** [comment]
In Jumpserver 1.4.6, you need to close the Windows NLA.
You can try it.
![image](https://user-images.githubusercontent.com/29087369/72397802-dad33000-377b-11ea-9c12-a2775b3f476d.png)

**Comment by mousazade** [comment]
Is it possible to create a system user with two types of protocols that can also include ssh, rdp?
In this image we can only select one type of protocol 

![Screenshot from 2020-01-25 10-46-17](https://user-images.githubusercontent.com/33278412/73117832-a6702880-3f60-11ea-815f-1adf64b282b1.png)

Our usernames are the same in all systems.
need is to use a username with multi protocols to connect to different console types

**Comment by primroses2006** [comment]
computer (win10 or win7)
if you need remote win10, you need chose (server2016)
and win10 need allow remote. if still dispaly this you need choose allow user(you can see the  "Select user...')
