### ISSUE TITLE
非管理员个人登录后页面上没有批量命令执行入口

### ISSUE THREAD

**Issue by chestarss** [jumpserver/jumpserver#3642]
[简述你的问题]
个人页面没有批量命令执行入口

##### 使用版本
1.5.6-2 GPLv2. Copyright FIT2CLOUD 飞致云 © 2014-2019

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
超级管理员在安全设置里，开启命令执行
![image](https://user-images.githubusercontent.com/40739051/72330872-38229f00-36f2-11ea-9825-aed0401fd9f4.png)
