### ISSUE TITLE
关于用户角色权限问题

### ISSUE THREAD

**Issue by GithubCheewah** [jumpserver/jumpserver#3645]
我司有分子公司较多，希望子公司管理员的账号可自行添加子公司服务器到资产中，但不希望子公司管理员看到其他公司的服务器。目前用户角色只有“用户”、“审计员”、“管理员”三个角色，
用户不能自行添加服务器，审计员和管理员又能看到其余的资产，有什么解决方法吗？

##### 使用版本
Version 1.5.3-2 GPLv2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
Xpack包有组织管理功能，组织管理员只拥有管理该组织的权限。
