### ISSUE TITLE
windows登录问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3654]
[简述你的问题]

如果windows资产只设置了rdp协议，而且同时授权了rdp系统用户和ssh系统用户，登录widnows资产的时候直接就用rdp系统用户登录了
但是我授权全部节点，节点里有windows linux 我同时将这个节点授权给了rdp用户和ssh用户，而且我windows资产设置了rdp和ssh协议登录的时候 我远程登录windows的时候就只让选择ssh账户了，这个你们后期会优化吗，还是说需要单独授权rdp资产

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
授权错误，请单独对不同的协议进行单独授权
