### ISSUE TITLE
Centos7极速安装报错

### ISSUE THREAD

**Issue by shanying2017** [jumpserver/jumpserver#3657]
[简述你的问题]
系统为Centos7，7.7.1908,内核3.10.0-957.el7.x86_64，纯净环境
执行命令如下：
![image](https://user-images.githubusercontent.com/25327419/72674560-41758800-3ab3-11ea-9943-6f5b643c4282.png)

极速安装报错，但安装完成后页面依然可以访问
![image](https://user-images.githubusercontent.com/25327419/72674537-ed6aa380-3ab2-11ea-9cf2-ff047d9809b0.png)
![image](https://user-images.githubusercontent.com/25327419/72674565-5a7e3900-3ab3-11ea-86f0-6aea98485f08.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
版本1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
![image](https://user-images.githubusercontent.com/25327419/72674590-72ee5380-3ab3-11ea-9d7c-654b10205fa8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@shanying2017 忽略，不影响使用
