### ISSUE TITLE
我现在用的1.5.6版本，这个版本是否还有windows录屏不能回放的问题呢

### ISSUE THREAD

**Issue by HiGayMan** [jumpserver/jumpserver#3663]
在终端管理 - > 回放管理里面，所有windows的录屏回放按钮是不可点击的？
linux的我还没有添加资产，不知道能否录屏。

##### 使用版本
jumpserver版本1.5.6
coco版本1.5.6
Guacamole 版本 1.5.6

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/47979247/72772518-16b83a80-3c3f-11ea-9608-3d81ed3de95d.png)

![image](https://user-images.githubusercontent.com/47979247/72772446-d658bc80-3c3e-11ea-9817-c4d65754f474.png)

##### 其他

Please help me！各位大佬！
[注:] 完成后请关闭 issue

**Comment by nszhsl** [comment]
您好，我这里也出了这个问题，请问解决了吗？

**Comment by Ision-Dong** [comment]
没有解决。发自我的华为手机-------- 原始邮件 --------发件人： sl <notifications@github.com>日期： 2020年2月5日周三 晚上9:25收件人： jumpserver/jumpserver <jumpserver@noreply.github.com>抄送： zhoudongdong <17621337632@163.com>, State change <state_change@noreply.github.com>主    题： Re: [jumpserver/jumpserver] 我现在用的1.5.6版本，这个版本是否还有windows录屏不能回放的问题呢 (#3663)您好，我这里也出了这个问题，请问解决了吗？

**Comment by nszhsl** [comment]
docker logs -f看了jms_guacamole的日志，发现创建文件的过程中有两个null什么的，重启一下jms_guacamole就好了
docker stop jms_guacamole && docker start jms_guacamole

**Comment by Ision-Dong** [comment]
好的，我一会试试。感谢！发自我的华为手机-------- 原始邮件 --------发件人： sl <notifications@github.com>日期： 2020年2月6日周四 中午12:22收件人： jumpserver/jumpserver <jumpserver@noreply.github.com>抄送： zhoudongdong <17621337632@163.com>, State change <state_change@noreply.github.com>主    题： Re: [jumpserver/jumpserver] 我现在用的1.5.6版本，这个版本是否还有windows录屏不能回放的问题呢 (#3663)docker logs -f看了jms_guacamole的日志，发现创建文件的过程中有两个null什么的，重启一下jms_guacamole就好了

docker stop jms_guacamole && docker start jms_guacamole

**Comment by Ision-Dong** [comment]
你好，我又遇到问题了，刚根据官方文档部署jump server  ，在web中能成功访问了，但是访问后再终端管理中没有koko和gua...的注册。
麻烦帮我分析下是什么问题呢？









在 2020-02-06 12:22:57，"sl" <notifications@github.com> 写道：

docker logs -f看了jms_guacamole的日志，发现创建文件的过程中有两个null什么的，重启一下jms_guacamole就好了
docker stop jms_guacamole && docker start jms_guacamole

**Comment by Ision-Dong** [comment]
你好，我又遇到问题了，刚根据官方文档部署jump server  ，在web中能成功访问了，但是访问后再终端管理中没有koko和gua...的注册。
麻烦帮我分析下是什么问题呢？
之前按照官方文档部署的时候，第一次访问时，会有这两个东西的注册，现在直接就看不到这两个中间件的注册了。。。到底是什么问题呢。









在 2020-02-06 12:22:57，"sl" <notifications@github.com> 写道：

docker logs -f看了jms_guacamole的日志，发现创建文件的过程中有两个null什么的，重启一下jms_guacamole就好了
docker stop jms_guacamole && docker start jms_guacamole
