### ISSUE TITLE
如何手动推送系统用户？

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#3665]
有些资产不知为啥不会推送系统用户，root测试是连通的，单独新增这台机器的授权，也不会推送。
没有找到手动触发推送系统用户的入口。

但有些资产在新增授权后是会推送的。

##### 使用版本
1.5.6

##### 问题复现步骤
1、新增资源
2、新增授权
3、没有推送系统用户，作业中心→任务列表 也没出现推送系统用户 

##### 具体表现[截图可能会更好些,最好能截全]
![QQ20200121-162817](https://user-images.githubusercontent.com/2853517/72787516-0e75f480-3c6b-11ea-9624-df0c9b7cd0c8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可能是之前已自动推送过了，系统用户和资产以及关联上了，下个版本对系统用户和资产提供手动推送接口

**Comment by wenbc** [comment]
我也出现同样的问题，手动推送系统用户到服务器不行。
![image](https://user-images.githubusercontent.com/8147297/74996688-36858d00-548f-11ea-8a78-50feff5e2453.png)

服务器celery_ansible.log日志信息：
![image](https://user-images.githubusercontent.com/8147297/74996991-01c60580-5490-11ea-854c-5fddc816533a.png)

Flower的执行任务也有日志
![image](https://user-images.githubusercontent.com/8147297/74997102-4c478200-5490-11ea-8237-6698b55edd14.png)

**Comment by LongTaiJun** [comment]
我也遇到这个问题了，新建授权都不会自动推送用户，找不到问题所在。。。
