### ISSUE TITLE
dial tcp  i/o timeout

### ISSUE THREAD

**Issue by echoo99** [jumpserver/jumpserver#3666]
[简述你的问题]

##### 使用版本
Version 1.5.5-2 GPLv2

##### 问题复现步骤
1.进入用户界面后，点击WEB终端
2. 资产无法连接，报错如下：
开始连接到 root@10.14.13.8 14.9
Connect asset 10.14.13.8 error: dial tcp 10.14.13.8:22: i/o timeout
所有资产都报同样的错
![image](https://user-images.githubusercontent.com/60162852/72855861-e41c4980-3cf3-11ea-841d-a76bc0c04989.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@echoo99 
```
# 如果在 系统用户 详情里面测试提示 ok, 但是 web 连接资产提示 timeout, 请手动登录该资产修改 /etc/ssh/sshd_config 的 usedns 为 no
$ vim /etc/ssh/sshd_config

...

# UseDNS no
UseDNS no

...

# 修改后, 重启 ssh 服务, 再次在web上连接资产
```

如果情况任然一样，登陆到koko所在的宿主服务器，把防火墙处理下，你可以尝试
```
systemctl restart docker
```
