### ISSUE TITLE
1.5.6 version,历史会话无法回放，在服务器上找不到录屏文件。

### ISSUE THREAD

**Issue by Ision-Dong** [jumpserver/jumpserver#3667]
[简述你的问题]
1.5.6 version,历史会话无法回放，在服务器上找不到录屏文件。

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/47979247/72879288-8b6ea000-3d37-11ea-8f12-524cded13d6e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Ision-Dong** [comment]
请大佬们帮忙解决下，实在不知道咋弄了。

**Comment by nszhsl** [comment]
@Ision-Dong 我这里也出了一模一样的问题.

**Comment by jinghao1** [comment]
我这也是同样的问题

**Comment by jinghao1** [comment]
linux可以回放，windows不可以

**Comment by Ision-Dong** [comment]
windows可以回放。我这边已经弄好了。发自我的华为手机-------- 原始邮件 --------发件人： cm <notifications@github.com>日期： 2020年2月13日周四 半夜11:24收件人： jumpserver/jumpserver <jumpserver@noreply.github.com>抄送： zhoudongdong <17621337632@163.com>, Mention <mention@noreply.github.com>主    题： Re: [jumpserver/jumpserver] 1.5.6 version,历史会话无法回放，在服务器上找不到录屏文件。 (#3667)linux可以回放，windows不可以

**Comment by Ision-Dong** [comment]
解决了，可以回放。发自我的华为手机-------- 原始邮件 --------发件人： cm <notifications@github.com>日期： 2020年2月13日周四 半夜11:24收件人： jumpserver/jumpserver <jumpserver@noreply.github.com>抄送： zhoudongdong <17621337632@163.com>, Mention <mention@noreply.github.com>主    题： Re: [jumpserver/jumpserver] 1.5.6 version,历史会话无法回放，在服务器上找不到录屏文件。 (#3667)我这也是同样的问题

**Comment by Ision-Dong** [comment]
解决了吗。你现在。我这边已经解决了，如果有需要可以告知你解决方法。发自我的华为手机-------- 原始邮件 --------发件人： sl <notifications@github.com>日期： 2020年2月5日周三 晚上9:25收件人： jumpserver/jumpserver <jumpserver@noreply.github.com>抄送： zhoudongdong <17621337632@163.com>, Mention <mention@noreply.github.com>主    题： Re: [jumpserver/jumpserver] 1.5.6 version,历史会话无法回放，在服务器上找不到录屏文件。 (#3667)@Ision-Dong 我这里也出了一模一样的问题.
