### ISSUE TITLE
xftp下载文件时，偶尔出现文件内容缺失

### ISSUE THREAD

**Issue by ugtim1** [jumpserver/jumpserver#3673]
[简述你的问题]
用xftp工具下载文件时，偶尔会出现代码文件下载下来，打开后出现内容缺失不完整，只有部分代码

##### 使用版本
jumpserver 1.5.5-2

##### 问题复现步骤
1. [步骤1]

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/59792983/73048699-f691b100-3eb4-11ea-8d39-65c1c8b835af.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by iiopstianya** [comment]
我也遇到过这种情况，用xftp打开服务器上代码文件时有丢失，只打开一半

一个月会出现好几次，jumpserver 版本1.5.4

**Comment by LeeEirc** [comment]
@ugtim1 @iiopstianya 1.5.6最新版本已经修复这个问题，请使用最新版本。

**Comment by wojiushixiaobai** [comment]
@
