### ISSUE TITLE
centos8安装jumpserver，jms_guacamole安装不成功，一直报错误，终端列表中也没有发现相应设备

### ISSUE THREAD

**Issue by funpower518** [jumpserver/jumpserver#3675]
[简述你的问题]
我按照https://jumpserver.readthedocs.io/zh/master/setup_by_centos8.html 一步步安装，安装完成后RDP远程管理WINDOWS不成功（ssh telnet是正常的），发现是jms_guacamole有问题(运行是正常的koko)。在终端管理中也没出现jms_guacamole的终端列表。日志中也一直报错误。

麻烦看下是啥问题，谢谢。

##### 使用版本
Version 1.5.6-2 GPLv2.

##### 问题复现步骤
# 安装 podman 部署 koko 与 guacamole
$ yum install -y podman-docker
$ alias docker=podman
$ echo "alias docker=podman" >> ~/.bashrc

# 配置 podman 镜像源
$ vi /etc/containers/registries.conf

...

[registries.search]
# registries = ['registry.redhat.io', 'quay.io', 'docker.io']
registries = ['bmtrgdvx.mirror.aliyuncs.com', 'f1361db2.m.daocloud.io', 'docker.io']

...

# 允许 容器ip 访问宿主 8080 端口, (容器的 ip 可以进入容器查看)
$ firewall-cmd --permanent --add-rich-rule="rule family="ipv4" source address="10.88.0.0/16" port protocol="tcp" port="8080" accept"
$ firewall-cmd --reload
# 10.88.0.x 是 podman 容器默认的IP池, 这里偷懒直接授权ip段了, 可以根据实际情况单独授权IP

# 获取当前服务器 IP
$ Server_IP=`ip addr | grep 'state UP' -A2 | grep inet | egrep -v '(127.0.0.1|inet6|docker)' | awk '{print $2}' | tr -d "addr:" | head -n 1 | cut -d / -f1`
$ echo -e "\033[31m 你的服务器IP是 $Server_IP \033[0m"

# http://<Jumpserver_url> 指向 jumpserver 的服务端口, 如 http://192.168.244.144:8080
# BOOTSTRAP_TOKEN 为 Jumpserver/config.yml 里面的 BOOTSTRAP_TOKEN
$ docker run --name jms_koko -d -p 2222:2222 -p 127.0.0.1:5000:5000 -e CORE_HOST=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_koko:1.5.6
$ docker run --name jms_guacamole -d -p 127.0.0.1:8081:8080 -e JUMPSERVER_SERVER=http://$Server_IP:8080 -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_guacamole:1.5.6

##### 具体表现[截图可能会更好些,最好能截全]
终端管理列表中没有相关设备：
![image](https://user-images.githubusercontent.com/60332176/73146228-92f1c880-40ec-11ea-8275-188cdb02c7b7.png)

错误日志：
docker logs -f jms_guacamole
![image](https://user-images.githubusercontent.com/60332176/73146252-ba489580-40ec-11ea-983b-56cd3b6cfedf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@funpower518 把jumpserver/jms_guacamole改成wojiushixiaobai/jms_guacamole即可
