### ISSUE TITLE
请提供一个稳定版本的Jumpserver的安装镜像

### ISSUE THREAD

**Issue by stealth1024** [jumpserver/jumpserver#3677]
[简述你的问题]
今天尝试了最新的Jumpserver，文档和操作很多地方都对不上。我理解目前JumpServer还在不断改进的过程中，但是体验实在是太差了。希望Jump Server Team 能够给大家提供一个稳定的版本（不需要特别多fancy的功能），但是可以安装简便的，可以考虑：

1）一个docker的镜像；
2）一个巨大的tar.gz，解压就可以安装；

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@stealth1024 请您专业一点，你的很多地方有问题请指出具体问题
```
问题1：https://docs.jumpserver.org/zh/master/dockerinstall.html
问题2：github提供tar.gz

**Comment by stealth1024** [comment]
![image](https://user-images.githubusercontent.com/52139850/73584824-6667f300-44d6-11ea-87c6-3ba4ceebba32.png)

**Comment by stealth1024** [comment]
以下是我按照https://docs.jumpserver.org/zh/master/dockerinstall.html的操作截屏。唯一不一样的地方是我把docker容器中的80端口映射到了8088端口。但是使用WGET工具去模拟访问8088端口没有任何反应，请问何解？
----------------------------------------------------------------------------------------------------------
[root@gateway lihuod]# if [ "$SECRET_KEY" = "" ]; then SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`; echo "SECRET_KEY=$SECRET_KEY" >> ~/.bashrc; echo $SECRET_KEY; else echo $SECRET_KEY; fi
UyyK2gO6QrnfJDofQqVN0jDXbr7u6A7uVYArrv8Vp2hzf6Pdua
[root@gateway lihuod]# if [ "$BOOTSTRAP_TOKEN" = "" ]; then BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`; echo "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN" >> ~/.bashrc; echo $BOOTSTRAP_TOKEN; else echo $BOOTSTRAP_TOKEN; fi
DQ68lNTI6aUvlua8
[root@gateway lihuod]# docker run --name jms_all -d -p **8088:80** -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:latest 
Unable to find image 'jumpserver/jms_all:latest' locally
Trying to pull repository docker.io/jumpserver/jms_all ... 
latest: Pulling from docker.io/jumpserver/jms_all
ab5ef0e58194: Pull complete 
8b71967260a9: Pull complete 
eeedd724a29d: Pull complete 
48da443aa024: Pull complete 
38e5107fe521: Pull complete 
2fba63594fd2: Pull complete 
Digest: sha256:7f83918362a3696e530d3dcb046d5d60eeb429ec24c16c74232d72a71cb630a6
Status: Downloaded newer image for docker.io/jumpserver/jms_all:latest
c8c5496578c7bc1486ba1be1f611b12519f74304cfeb356e430399f29465b032
[root@gateway lihuod]# docker ps
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS                                          NAMES
c8c5496578c7        jumpserver/jms_all:latest   "entrypoint.sh"     22 seconds ago      Up 21 seconds       0.0.0.0:2222->2222/tcp, 0.0.0.0:8088->80/tcp   jms_all
[root@gateway lihuod]# 
[root@gateway lihuod]# 
[root@gateway lihuod]# wget http://127.0.0.1:8088
--2020-02-01 09:32:07--  http://127.0.0.1:8088/
正在连接 127.0.0.1:8088... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (Connection reset by peer)。
重试中。

--2020-02-01 09:32:08--  (尝试次数： 2)  http://127.0.0.1:8088/
正在连接 127.0.0.1:8088... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (Connection reset by peer)。
重试中。

**Comment by stealth1024** [comment]
已经完成测试，OK，谢谢您的支持。不过你们的其它的安装文档确实很难搞，主要是Python的依赖。
