### ISSUE TITLE
LDAP导入用户之后，无法用LDAP的密码登陆

### ISSUE THREAD

**Issue by stealth1024** [jumpserver/jumpserver#3678]
[简述你的问题]
LDAP导入了用户lihuod，但是无法用LDAP的密码登陆到系统。
![image](https://user-images.githubusercontent.com/52139850/73586213-ce253a80-44e4-11ea-955b-ba32392f5a4e.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
我是用的是最新的DOCKER镜像

![image](https://user-images.githubusercontent.com/52139850/73586229-104e7c00-44e5-11ea-883b-a16d77e6fa10.png)

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by maoqin** [comment]
建议检查下ldap配置

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/74118342-0966ee00-4bf6-11ea-9542-721cc4b814e9.png)
启用LDAP认证

**Comment by ben0112** [comment]
同样问题，使用过docker jms_all镜像部署和centos7自建服务器快速安装脚本，均不能实现ldap用户登录，ldap用户可以正常导入，用户名密码没有问题，相同ldap过滤条件在openvpn上ldap用户认证没有问题。

**Comment by CyrilCh** [comment]
遇到相同的问题，用户导入正常，但是导入后不能使用登录，使用的是docker安装

**Comment by wojiushixiaobai** [comment]
确定设置无误，请重新检查下
