### ISSUE TITLE
无法连接windows服务，日志显示-心跳成功{code:201,result:[]}

### ISSUE THREAD

**Issue by flzhang132** [jumpserver/jumpserver#3683]
[简述你的问题]
无法连接windows服务，
日志显示(Guacamole虽然注册成功，但心跳日志里result中总是没有值，且连接windows服务器时，日志显示不能正常建立websocket通道。
INFO  o.a.g.a.j.r.JumpserverRegisterService - 心跳成功{code:201,result:[]}
Creation of WebSocket tunnel to guacd failed: java.net.ConnectException: Connection refused (Connection refused)

##### 使用版本
Jumpserver版本 1.4.8

##### 问题复现步骤
1. 选择windows服务器
2. 无法连接，

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/26810567/73931585-89016e00-4913-11ea-91a6-fd5b6c57e823.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有没有nginx，是不是设置了Upgrade 什么的
