### ISSUE TITLE
部署jumpserver1.5.6后页面访问有问题

### ISSUE THREAD

**Issue by shanying2017** [jumpserver/jumpserver#3684]
[简述你的问题]
挂载一块新的 硬盘到/opt目录下，使用脚本极速安装，完成后页面访问异常，

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]挂载一块新硬盘到/opt目录下
2. [步骤2]
$ cd /opt
$ yum -y install wget
$ wget -O /opt/jms_install.sh https://demo.jumpserver.org/download/jms_install.sh
$ sh jms_install.sh
##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/25327419/74078861-777eaa00-4a6a-11ea-8d99-b656c838beec.png)
nginx的错误日志
![image](https://user-images.githubusercontent.com/25327419/74078872-ae54c000-4a6a-11ea-8d03-7827a4a6a929.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by sunnoy** [comment]
静态文件文件夹 直接 777 权限试一下

**Comment by wojiushixiaobai** [comment]
@shanying2017 目录授权nginx访问
