### ISSUE TITLE
多个koko轮询不均

### ISSUE THREAD

**Issue by sunnoy** [jumpserver/jumpserver#3685]
[简述你的问题]
koko终端没有轮询

##### 使用版本
1.5.6

##### 问题复现步骤
1. 多人打开web 终端
2. 查看会话始终在一个koko上

##### 都已经注册上了

<img width="1344" alt="WX20200209-113349@2x" src="https://user-images.githubusercontent.com/19342276/74095759-2b963880-4b30-11ea-96bc-016c154f66da.png">

##### nginx配置

```bash
    upstream koko {
        ip_hash;
        server koko1:5000;
        server koko2:5000;
        server koko3:5000;
        server koko4:5000;
    }
```

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ip hash的，nginx是根据ip的前三段确定的，可以考虑使用基于cookie的方式

**Comment by sunnoy** [comment]
least_conn; 改成了他 试了一下不会在一个终端上了 谢谢
