### ISSUE TITLE
jumpserver Version 1.5.3-2 GPLv2发送邮件功能不可用

### ISSUE THREAD

**Issue by rookie-z** [jumpserver/jumpserver#3687]
可以发送测试并且成功接收测试邮件，但是如果使用发送重置密码邮件，那么将收不到邮件
查看celery_default.log 日志
日志的报错为
Received task: common.tasks.send_mail_async[dd69c175-f33e-47e0-ab3d-004cf3ba5bd7]  
Task common.tasks.send_mail_async[dd69c175-f33e-47e0-ab3d-004cf3ba5bd7] raised unexpected: TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'",)
Traceback (most recent call last):
  File "/usr/local/jumpserver/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/jumpserver/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/jumpserver/jumpserver/apps/common/tasks.py", line 27, in send_mail_async
    args[0] = settings.EMAIL_SUBJECT_PREFIX + args[0]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by primroses2006** [comment]
这个我也遇到了,如果在邮件测试地方点测试邮件. 我是可以收到邮件的.
如果在用户地方点击更改密码发送邮件,用户收不到.

**Comment by zhangjianjian** [comment]
和你一样的问题，一样的报错内容，系统设置里邮件测试可以发送，其他的都不行。

**Comment by zhangjianjian** [comment]
一样的问题，有解吗？

**Comment by yongxiaodong** [comment]
在config.yml 中添加一个名为EMAIL_SUBJECT_PREFIX的配置，可以解决你的这个问题
例如：
`EMAIL_SUBJECT_PREFIX: "[Jumpserver]"`


但是我遇到了新的问题，接收到的邮件中 重置密码链接为localhost:8080/*****   ，这导致我不能正常访问设置我的密码，我暂时还不知道如何修改这个链接前缀
![image](https://user-images.githubusercontent.com/23717585/83374663-db085b00-a3fe-11ea-8d1e-0e6b6dc6b667.png)
