### ISSUE TITLE
guacamole RDP分辨率问题

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#3688]
[简述你的问题]
通过Jumpserver连接Windows，设置了1920 * 1080的分辨率，在同样分辨率的显示屏上，始终无法达到1920 * 1080，即便是使用新窗口打开并设置浏览器全屏，也只能达到1920*937。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/4084548/74299867-f0db0d00-4d88-11ea-802c-c3501f33ad44.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Hello-Linux** [comment]
请详细描述您的问题

**Comment by bigbird1985** [comment]
@Hello-Linux 已经添加截图。
