### ISSUE TITLE
Luna Web Terminal  前端页面中文前端页面显示乱码

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#3689]
[简述你的问题]

##### 使用版本
V1.5.6-2

##### 问题复现步骤
Luna Web Terminal  前端页面中文前端页面显示乱码
执行node 的forever list命令 后中文字符偶尔乱码，比如第一次运行命令，中文显示都正常，第二次运行后出现了两个？？乱码，服务器本身应该没有问题，都能正常显示中文。
![2020-02-10 17-12-51 的屏幕截图](https://user-images.githubusercontent.com/17851645/74136458-0802e900-4c29-11ea-8569-678b8d59b692.png)
![2020-02-10 17-13-12 的屏幕截图](https://user-images.githubusercontent.com/17851645/74136473-0c2f0680-4c29-11ea-9c24-7f536af9d788.png)

**Comment by wojiushixiaobai** [comment]
@Hello-Linux 暂未复现，看看是否能100%复现
