### ISSUE TITLE
文件下载不成功

### ISSUE THREAD

**Issue by coolbreezeqf** [jumpserver/jumpserver#369]
客户端系统：macOS
web: 端无法下载
终端：使用 Secure CRT 可以下载，普通终端不行。
代码中是使用`bash('tar czf %s.tar.gz %s && sz %s.tar.gz' % (tmp_dir, tmp_dir_name, tmp_dir))`下载的。这个 `sz` 命令似乎只能在 Secure CRT 中使用。

**Comment by ibuler** [comment]
需要终端支持 x/y/z modem
