### ISSUE TITLE
luna界面连接多个机器会卡住

### ISSUE THREAD

**Issue by sunnoy** [jumpserver/jumpserver#3690]
[简述你的问题]
在luna界面同时连接多个机器会卡住

##### 使用版本

1.5.6
##### 问题复现步骤
1. 打开luna
2. 连接多台机器
3 会出现卡住

[注:] 完成后请关闭 issue
<img width="1678" alt="WX20200210-175132@2x" src="https://user-images.githubusercontent.com/19342276/74139250-025bd200-4c2e-11ea-8b7c-f687a53e5366.png">

**Comment by Hello-Linux** [comment]
这个目前我们没有复现，请查看您的服务器配置

**Comment by sunnoy** [comment]
你好服务器配置负载什么的很低的，偶发会出现卡住的情况，怀疑是js代码相关的问题
![image](https://user-images.githubusercontent.com/19342276/76501775-d1193080-647d-11ea-8221-cb5c2cc5f4df.png)
