### ISSUE TITLE
jumperserver 远程桌面时频繁 连接错误 

### ISSUE THREAD

**Issue by primroses2006** [jumpserver/jumpserver#3691]
[简述你的问题]
使用网站的一键脚本安装的jumperserver, 在内网环境下使用远程桌面连接电脑,使用特别稳定,不出现连接错误.

通过FortiClient VPN拨入公司后再使用jumperserver就会经常连接错误,有时候两分钟有时候五分钟,不定时中断. 直接使用RDP远程连接就不会出现中断现象.

但是连接VPN ping jumperserver时不丢包,延迟只有20ms.

##### 使用版本
版本1.5.6-101 GPLv2。

##### 问题复现步骤
1. [步骤1]
FortiClient VPN 拨入公司内网(10.10.10.X) 获得地址 192.168.1.X (VPN地址)
2. [步骤2]
访问10.10.10.88 登陆帐号 访问 10.10.10.1 (win10)  不定时 连接错误

##### 其他

[注:] 完成后请关闭 issue

**Comment by primroses2006** [comment]
我怀疑是 因为我vpn拨入获得地址和内网不是一段.  但是我找供应商查了防火墙日志没有任何错误.
如果不能用 应该直接不能用,这种不定时断开实在不知道是啥原因.

**Comment by primroses2006** [comment]
找到原因了, 内网策略 websocket经常会被阻止,做了个策略放行websocket就好了.
咨询一下如何特定用户不录屏哇?

**Comment by wojiushixiaobai** [comment]
@primroses2006 暂时不支持禁止录屏

**Comment by leqii-com** [comment]
我司是softether vpn，用jumpserver Version v3.6.3，使用WEB连接linux ssh端口、使用终端2222端口连接linux ssh端口，均出现一会没有敲命令 就会卡住，然后 等十几秒二十秒 敲入的命令才出现、甚至没任何反应，得关闭终端或者web页面 重连 又好了。不知道是VPN还是jumpserver原因，之前旧版本jumpserver和windows VPN没有遇到过。
