### ISSUE TITLE
每小时都会自动发送Disk used more than邮件

### ISSUE THREAD

**Issue by imokex** [jumpserver/jumpserver#3692]
[简述你的问题]
服务器上安装有zabbix-agent，用于检测。

问题是：每个小时jumpserver都会给管理员邮箱发送一个邮件
Disk used more than 80%: /boot => 86.5
请问如何关闭？

从邮件服务器上看日志，确实是jumpserver用专属于jumpserver的邮箱账号，从jumpserver发出来的。

##### 使用版本
1.5.6-2

##### 问题复现步骤
1. 修改管理员邮箱为有效邮箱

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可能没有排除boot这个目录

**Comment by mengqykids** [comment]
> 可能没有排除boot这个目录，这个目录是不是单独一块盘？

您好，是的。但是一般情况下不是都会给/boot单独分区吗？

**Comment by cjm788** [comment]
我的也是不断发邮件报警。
![image](https://user-images.githubusercontent.com/61697322/77885976-9c3d1400-729a-11ea-9178-5b9583a98916.png)

**Comment by abert1991** [comment]
同样的问题。怎样修改这个磁盘监控告警呢？比如调高使用率、修改告警间隔时间，或者直接关闭这个告警？

**Comment by abert1991** [comment]
进入jms_core容器内部，修改/opt/jumpserver/apps/ops/tasks.py文件
for path, usage in usages.items():
        need_check = True
        for uncheck_path in uncheck_paths:
            if path.startswith(uncheck_path):
                need_check = False
        if need_check and usage.percent > 80:
            send_server_performance_mail(path, usage, usages)
