### ISSUE TITLE
请问：RDP回放记录使用什么软件可以离线播放？

### ISSUE THREAD

**Issue by imokex** [jumpserver/jumpserver#3693]
RT，在线回放不支持快进，
请问RDP的保存路径是什么？
请问回放记录如何通过其他软件打开？

##### 使用版本
1.5.6-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by bigbird1985** [comment]
据说1.5.7支持。

**Comment by ibuler** [comment]
https://github.com/orangemio/videoplayer-electron/releases 使用这个
