### ISSUE TITLE
jumpserver无法录制视频

### ISSUE THREAD

**Issue by Michael754267513** [jumpserver/jumpserver#3694]
[简述你的问题]

##### 使用版本
Version 1.5.6-2

##### 问题复现步骤
回话管理-->历史回话   回放按钮无法点击，锁定状态，在/opt/jumpserver/data/media/ 下面无录制视频。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@Michael754267513 RDP协议资产无录像，把guacamole重启即可
