### ISSUE TITLE
资产授权成功用户没推送

### ISSUE THREAD

**Issue by LongTaiJun** [jumpserver/jumpserver#3695]
[简述你的问题]
我的堡垒机升级了最新的版本，但是资产授权规则上去添加资产后不推送用户，资产详情下看不到这个授权用户，另一个新建的堡垒机也是这样，查看目标资产home目录没有相关用户目录，证明没推送过去，只有把这个授权删了重新添加才没问题。

##### 使用版本
1.5.6

##### 问题复现步骤
1. 权限管理
2. 资产授权

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@LongTaiJun 旧版本升级上来的，有概率出现此问题，目前还不知道如何100%复现此问题。会继续关注

**Comment by wojiushixiaobai** [comment]
@LongTaiJun 旧版本升级上来的，有概率出现此问题，目前还不知道如何100%复现此问题。会继续关注

**Comment by codech** [comment]
目前我也遇到这个问题

**Comment by LongTaiJun** [comment]
我目前升级在1.5.7-2的版本，手动推送没问题，不敢升级动了，就这个版本维护着吧。
