### ISSUE TITLE
1.5.6全屏bug 请指教

### ISSUE THREAD

**Issue by rexlibing** [jumpserver/jumpserver#3696]
[简述你的问题]
连接windows后，点击“视图”--“全屏显示”结果屏幕缩小了

##### 使用版本
[使用的Jumpserver版本 1.5.6]

##### 问题复现步骤
1. [点击web终端]
2. [连接上windows机器]
3.点击“视图”--“全屏显示”结果屏幕缩小了

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16685466/74396919-665ce100-4e4e-11ea-9499-03b64f847887.png)

##### [其他](url)

[注:] 完成后请关闭 issue

**Comment by rexlibing** [comment]
无法粘贴图片~~

**Comment by rexlibing** [comment]
@fit2cloudrd @pengyao  ~_~点击全屏，桌面显示反而变很小遇到过没？

**Comment by rexlibing** [comment]
> [简述你的问题]
> 连接windows后，点击“视图”--“全屏显示”结果屏幕缩小了
> 
> ##### 使用版本
> [使用的Jumpserver版本 1.5.6]
> 
> ##### 问题复现步骤
> 1. [点击web终端]
> 2. [连接上windows机器]
>    3.点击“视图”--“全屏显示”结果屏幕缩小了
> 
> ##### 具体表现[截图可能会更好些,最好能截全]
> ##### [其他](url)
> [注:] 完成后请关闭 issue
![image](https://user-images.githubusercontent.com/16685466/74396881-462d2200-4e4e-11ea-8af8-3cfa8aa8994a.png)

**Comment by ibuler** [comment]
是不是你固定了分辨率？

**Comment by ibuler** [comment]
@jym503558564 测试一下，看看能不能复现

**Comment by jym503558564** [comment]
- 无法复现屏幕缩小情况
![image](https://user-images.githubusercontent.com/40739051/74646512-f97e7980-51b4-11ea-8903-72280f9864d5.png)

**Comment by rexlibing** [comment]
设置里面好像分辨率一直是auto的，怎么现在是可以的了。这个版本我前两天都是点资产右键“新窗口打开”这样也挺好用的! 这样的话，非常OK了，jump几乎完美了~-~

**Comment by rexlibing** [comment]
估计是浏览器问题 @jym503558564 @ibuler ,谷歌打开可以全屏，360打开会缩屏。
