### ISSUE TITLE
RDP协议的录像功能怎么关闭？

### ISSUE THREAD

**Issue by Sea-Flying** [jumpserver/jumpserver#3699]
从节约资源考虑，录像功能目前不需要，有没有全局的或者针对会话的关闭配置

没有的话，以后可否提供，因为Guacamole本身是可以关闭录像的

版本：Jumpserver ALL 1.5.6

**Comment by ibuler** [comment]
暂时无法关闭，将来提供方法关闭

**Comment by Satan023** [comment]
现在可以了吗？
