### ISSUE TITLE
koko服务启动报错

### ISSUE THREAD

**Issue by alvin6666** [jumpserver/jumpserver#3701]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.6]

##### 问题复现步骤
1. ./koko start

##### 其他
![image](https://user-images.githubusercontent.com/13924849/74451242-495df780-4eba-11ea-99cb-be6accc08cb9.png)

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@alvin6666 修改一下你的config.yml 里面的name字段，小于32个字符。
