### ISSUE TITLE
jumpserver两层nginx 没法连接服务器 Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by teazj** [jumpserver/jumpserver#3704]
两层nginx 没法连接服务器
Error during WebSocket handshake: Unexpected response code: 400

##### 使用版本
1,5.4版本 docker-compose 

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/6780969/74552335-f48cb080-4f8f-11ea-93c0-576b1693cfd5.png)

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/6780969/74552345-fce4eb80-4f8f-11ea-8bcf-07fb7bbdf44e.png)

server {
  listen 80;
  server_name jmp.opscom;
  access_log /data/nginx/logs/opsgjbc.log;
  client_max_body_size 100m;  # 录像及文件上传大小限制

  location /luna/ {
    proxy_pass http://jumpserver-docker-compose/luna/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /media/ {
    proxy_pass http://jumpserver-docker-compose/media/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /static/ {
    proxy_pass http://jumpserver-docker-compose/static/;
    proxy_set_header   Host    $host;
    proxy_set_header   X-Real-IP   $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  location /koko/ {
    proxy_pass http://jumpserver-docker-compose:5000;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    access_log off;
  }
  location /guacamole/ {
    proxy_pass http://jumpserver-docker-compose:8081;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    access_log off;
  }
  location /ws/ {
    proxy_pass http://jumpserver-docker-compose:8070;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

    location / {
        proxy_pass http://jumpserver-docker-compose:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

**Comment by wojiushixiaobai** [comment]
@teazj 每层都需要加上websocket的设置

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
