### ISSUE TITLE
默认ESC退出全屏，是否有方式可以改为其他的按键或者组合按键？

### ISSUE THREAD

**Issue by zhiyunliu** [jumpserver/jumpserver#3706]
[简述你的问题]
【全屏显示】模式下，默认按ESC退出全屏模式，但ESC按键在平时的使用中属于高频按键，有没有一个方式修改这个退出全屏的默认按键方式，如改成CTRL+ESC或者通过配置 等。

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2-2 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1] 全屏显示
2. [步骤2] 按ESC退出全屏

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ESC是浏览器设置的，我遇到的所有的退出全屏的方式都是ESC

**Comment by zhiyunliu** [comment]
> ESC是浏览器设置的，我遇到的所有的退出全屏的方式都是ESC
是的，大多其他全屏都是ESC的做法。但是，其他的产品大多是用来观看（如：X手视频，X奇异等），而该产品主要是用来操作，具有很多的输入性动作。所以建议能变更这个设计或者可以自定义按键组合。

**Comment by Ryanszu** [comment]
也遇到这个问题了。远程端用vi这些需要Esc按键的，都会退出全屏。还有ctrl+W alt+TAB 这些和浏览器冲突的快捷键，都不能使。有没有可能像Hyper-V或者别的虚拟机软件那样，全局托管键盘。

**Comment by wojiushixiaobai** [comment]
目前尚无更好的解决方案
