### ISSUE TITLE
LDAP导入用户操作是否可以集成到用户管理里操作?

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#3708]
[简述你的问题]
LDAP导入用户操作是否可以集成到用户管理里操作?
在我们的环境里，用户需要使用堡垒机，需要通过OA流程申请的，最近流程非常多，每次处理一个流程就要操作一次导入用户，每次从设置里进入，太繁琐了。
如果可以放在用户管理里操作，就比较顺了。
用户管理-导入用户→资产管理-新建资产→权限管理-资产授权。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
合理

**Comment by bigbird1985** [comment]
@ibuler 资产树的节点是不是可以增加一个搜索功能？我们节点比较多，查找起来比较麻烦，谢谢。
