### ISSUE TITLE
命令记录混乱

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3709]
[简述你的问题]
多条命令混合在一起

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/74715991-a5cd6800-5268-11ea-8403-6e6b4aea8f57.png)
![image](https://user-images.githubusercontent.com/44529247/74716072-d1505280-5268-11ea-8e8b-6914ee2f86a2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
