### ISSUE TITLE
1.5.6远程win10

### ISSUE THREAD

**Issue by rexlibing** [jumpserver/jumpserver#3710]
[简述你的问题]
windows刚开始安装上时，选择连接类型为Windows2016，可以连接。系统安装完软件并修复重启几次后，突然无法连接了。但是windows自带的mstsc是可以的，服务器ping win10这台3389端口也是通的。却总是显示“无法连接服务器，请联系网络管理员...”

##### 使用版本
使用的Jumpserver版本 1.5.6

##### 问题复现步骤
1. [步骤1] 
2. [步骤2]
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16685466/74917649-caf5de00-5402-11ea-9fa9-4f1ec4d8b48a.png)
![image](https://user-images.githubusercontent.com/16685466/74917984-6424f480-5403-11ea-9a58-9e2d8208cce0.png)

[注:] 完成后请关闭 issue

**Comment by bailiang27** [comment]
试着去掉远程桌面的要求NLA试试，我测试2016和Win10，也有这个问题。

**Comment by bailiang27** [comment]
通过关闭NLA后就能连上了，但是做测试，guacamole的，是可以连接NLA打开的服务器。不知道这种是设计的问题还是个BUG

**Comment by wojiushixiaobai** [comment]
Windows2016 需要关闭 NLA
Windows 不需要
