### ISSUE TITLE
用接口创建节点的问题

### ISSUE THREAD

**Issue by llinwei** [jumpserver/jumpserver#3712]
[简述你的问题]
节点创建接口不能直接创建与父节点名相同的子节点
只能通过上诉接口创建新节点，再用重命名接口修改子节点与父节点同名

##### 使用版本
1.5.6
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@llinwei 请在新版本验证此问题是否复现，感谢反馈
