### ISSUE TITLE
使用密钥对ssh登录堡垒机的时候，会忽略掉私钥的passphrase

### ISSUE THREAD

**Issue by tomatoyu** [jumpserver/jumpserver#3717]
使用密钥对ssh登录堡垒机的时候，会忽略掉私钥的passphrase
##### 使用版本
Version 1.5.6-2 GPLv2.
##### 问题复现步骤
使用密钥对ssh登录堡垒机的时候，会忽略掉私钥的passphrase

**Comment by xiuno** [comment]
同问。

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
