### ISSUE TITLE
如何修改默认语言为英文

### ISSUE THREAD

**Issue by chjtwork** [jumpserver/jumpserver#3718]
[简述你的问题]
jumpserver页面端怎样配置默认为英文，比如一开始的登录页面默认英文，以及普通用户登录后默认为英文；ssh端的koko倒是直接有配置LANG: en可以改掉，jumpserver有这种配置吗？

##### 使用版本
Version 1.5.6-2

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chjtwork 默认根据浏览器语言自动显示中文或者英文

**Comment by chjtwork** [comment]
之前一开始只是把chrome默认显示语言改为英文，发现访问jumpserver还是中文，刚才又试了下，原来还需要把英文的顺序调到最上面，然后访问就默认为英文了。谢谢
