### ISSUE TITLE
电脑1能正常使用堡垒机 ssh资产A，和堡垒机同网段的电脑2使用堡垒机却不能ssh资产A

### ISSUE THREAD

**Issue by yq513** [jumpserver/jumpserver#3719]
电脑1能正常使用堡垒机 ssh资产A，和堡垒机同网段的电脑2使用堡垒机却不能ssh资产A，如下图
![image](https://user-images.githubusercontent.com/39945790/75317942-1b0dee00-58a4-11ea-9b72-d8b32183e45d.png)

nginx的配置如下图
![image](https://user-images.githubusercontent.com/39945790/75318078-5e685c80-58a4-11ea-982f-13a5be54eda2.png)
![image](https://user-images.githubusercontent.com/39945790/75318100-75a74a00-58a4-11ea-9894-79fd8a52d4a0.png)
![image](https://user-images.githubusercontent.com/39945790/75318110-7f30b200-58a4-11ea-93e8-ee7f883423c1.png)

linux资产  防火墙和 iptableds 请空了， 相互之间能ping和telnet 22 端口

##### 使用版本
1.5.6
请教下   nginx的配置有没有问题，或者哪里没配置对

**Comment by BaiJiangJie** [comment]
nginx 配置应该没什么问题，另一台能够连接成功，看下连接失败是 koko 的日志

**Comment by yq513** [comment]
> nginx 配置应该没什么问题，另一台能够连接成功，看下连接失败是 koko 的日志

提示连接被拒绝，但这些端口是没有终端的所以连接不上。   koko.log 也没有失败的日志，真的很奇怪········
![image](https://user-images.githubusercontent.com/39945790/75620168-54a26a00-5bc0-11ea-9cb7-fa749e96dfb0.png)
