### ISSUE TITLE
启动时guncorn 及其他组件无故stop

### ISSUE THREAD

**Issue by LuckyDogg** [jumpserver/jumpserver#3721]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.6 

##### 问题复现步骤
1. 输入 ./jms start
2.查看日志，发现进程被stop了，但是看到8080端口的gunicorn 依然活跃，但是请求各种都很卡，怀疑启动的时候有问题，麻烦帮忙看下

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16526987/75322668-354cc980-58ae-11ea-9b8a-343fa1c66278.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LuckyDogg** [comment]
https://jumpserver.huami.com/api/v1/assets/assets/?draw=1&limit=15&offset=0  这个请求很慢 
还有一个 /js18n 也比较慢

**Comment by LuckyDogg** [comment]
api/v1/assets/assets/?draw=1&limit=15&offset=0&_=1582703357027 这个请求 很慢

还有一个 /js18n 也比较慢

**Comment by ibuler** [comment]
看一下gunicorn的配置文件

**Comment by LuckyDogg** [comment]
嗯嗯，通过查看日志解决了，gunicorn有个僵尸进程
