### ISSUE TITLE
pip install -r requirements.txt 报错 ERROR: Failed building wheel for cffi

### ISSUE THREAD

**Issue by bigblue0** [jumpserver/jumpserver#3724]
pip install -r requirements.txt -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com
安装时，会报错 ERROR: Failed building wheel for cffi

Jumpserver版本 1.5.6 

安装环境： 
Centos 7.4  python 3.8

执行安装命令后，出现如下报错信息：

Requirement already satisfied: azure-nspkg>=2.0.0 in /opt/py3/lib/python3.8/site-packages (from azure-storage-nspkg>=2.0.0->azure-storage-blob==1.3.1->jms-storage==0.0.26->-r requirements.txt (line 62)) (3.0.2)
Building wheels for collected packages: cffi
  Building wheel for cffi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/py3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xi42ahxv
       cwd: /tmp/pip-install-ijn7c9d2/cffi/
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/c
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/opt/py3/include -I/usr/local/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
  c/_cffi_backend.c: 在函数‘b_do_dlopen’中:
  c/_cffi_backend.c:4197:31: 警告：assignment discards ‘const’ qualifier from pointer target type [默认启用]
           *p_printable_filename = PyText_AsUTF8(s);
                                 ^
  In file included from c/cffi1_module.c:20:0,
                   from c/_cffi_backend.c:7370:
  c/call_python.c: 在函数‘_get_interpstate_dict’中:
  c/call_python.c:20:30: 错误：提领指向不完全类型的指针
       builtins = tstate->interp->builtins;
                                ^
  c/call_python.c: 在函数‘_update_cache_to_call_python’中:
  c/call_python.c:160:39: 错误：提领指向不完全类型的指针
       new1 = PyThreadState_GET()->interp->modules;
                                         ^
  c/call_python.c: 在函数‘cffi_call_python’中:
  c/call_python.c:249:63: 错误：提领指向不完全类型的指针
           if (externpy->reserved1 != PyThreadState_GET()->interp->modules) {
                                                                 ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cffi
  Running setup.py clean for cffi
Failed to build cffi
Installing collected packages: cffi, cryptography, ansible, bcrypt, billiard, kombu, celery, configparser, decorator, Django, django-auth-ldap, django-timezone-field, python-crontab, django-celery-beat, django-filter, django-formtools, djangorestframework, django-rest-swagger, ecdsa, monotonic, dnspython, eventlet, gunicorn, ldap3, PyNaCl, paramiko, passlib, pyotp, redis, sshpubkeys, uritemplate, urllib3, ruamel.yaml.clib, ruamel.yaml, inflection, drf-yasg, Werkzeug, drf-nested-routers, tencentcloud-sdk-python, lockfile, python-daemon, httpsig, django-proxy, txaio, autobahn, daphne, channels, msgpack, async-timeout, hiredis, aioredis, channels-redis
  Attempting uninstall: cffi
    Found existing installation: cffi 1.14.0
    Uninstalling cffi-1.14.0:
      Successfully uninstalled cffi-1.14.0
    Running setup.py install for cffi ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-shee3pfq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/py3/include/site/python3.8/cffi
         cwd: /tmp/pip-install-ijn7c9d2/cffi/
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/c
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/opt/py3/include -I/usr/local/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o
    c/_cffi_backend.c: 在函数‘b_do_dlopen’中:
    c/_cffi_backend.c:4197:31: 警告：assignment discards ‘const’ qualifier from pointer target type [默认启用]
             *p_printable_filename = PyText_AsUTF8(s);
                                   ^
    In file included from c/cffi1_module.c:20:0,
                     from c/_cffi_backend.c:7370:
    c/call_python.c: 在函数‘_get_interpstate_dict’中:
    c/call_python.c:20:30: 错误：提领指向不完全类型的指针
         builtins = tstate->interp->builtins;
                                  ^
    c/call_python.c: 在函数‘_update_cache_to_call_python’中:
    c/call_python.c:160:39: 错误：提领指向不完全类型的指针
         new1 = PyThreadState_GET()->interp->modules;
                                           ^
    c/call_python.c: 在函数‘cffi_call_python’中:
    c/call_python.c:249:63: 错误：提领指向不完全类型的指针
             if (externpy->reserved1 != PyThreadState_GET()->interp->modules) {
                                                                   ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of cffi
  Moving to /opt/py3/lib/python3.8/site-packages/.libs_cffi_backend/
   from /opt/py3/lib/python3.8/site-packages/~libs_cffi_backend
  Moving to /opt/py3/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-6td4w_19/_cffi_backend.cpython-38-x86_64-linux-gnu.so
  Moving to /opt/py3/lib/python3.8/site-packages/cffi-1.14.0.dist-info/
   from /opt/py3/lib/python3.8/site-packages/~ffi-1.14.0.dist-info
  Moving to /opt/py3/lib/python3.8/site-packages/cffi/
   from /opt/py3/lib/python3.8/site-packages/~ffi
ERROR: Command errored out with exit status 1: /opt/py3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ijn7c9d2/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-shee3pfq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/py3/include/site/python3.8/cffi Check the logs for full command output.

请帮看下怎么解决，十分感谢！

**Comment by wojiushixiaobai** [comment]
参考官方安装文档进行安装 https://docs.jumpserver.org/zh/master/step_by_step.html
