### ISSUE TITLE
使用install.py安装时，能否删除对iptables的操作

### ISSUE THREAD

**Issue by roybliss** [jumpserver/jumpserver#373]
使用install.py安装时，能否删除对iptables清空的操作，这样会删除掉我的防火墙策略，而且还保留了链默认策略，若没有备份，就麻烦大了。而且，我的INPUT默认是DROP，直接把我ssh踢下线，很吓人的。

**Comment by ibuler** [comment]
可以

**Comment by ibuler** [comment]
你是 ubuntu ?

**Comment by roybliss** [comment]
是的，ubuntu14.04

**Comment by ibuler** [comment]
ok, 你可以修改一下，提一个pr
