### ISSUE TITLE
命令存储问题

### ISSUE THREAD

**Issue by nilsir** [jumpserver/jumpserver#3734]
命令存储怎么存储到阿里es服务上?

##### 使用版本
Version 1.4.10-2 GPLv2.

##### 问题复现步骤
1. 里边的主机是什么意思呢
2. 如何才能把命令上传到es里边呢

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/15967737/75537691-71b92a80-5a52-11ea-8b0b-5d7c164aee43.png)

##### 其他
无

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@nilsir 根据页面说明填写你的ES服务器即可
