### ISSUE TITLE
网络不好的情况下，按键粘包的问题，同一个按键重复一直出现

### ISSUE THREAD

**Issue by zhiyunliu** [jumpserver/jumpserver#3735]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/29598760/75540760-a1b6fc80-5a57-11ea-840f-f45d9a7a63fb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
观察一下，看看其他用户有没有该问题，我的蓝牙机械键盘有事也这样，有线没有问题，不知道是不是tcp层的问题
