### ISSUE TITLE
出现未知错误 退出登陆

### ISSUE THREAD

**Issue by sccblue** [jumpserver/jumpserver#3737]
[简述你的问题]

##### 使用版本
[使用的Jumpserver版本 1.5.6]

##### 问题复现步骤
1. [步骤1]
在通过chrome或者火狐浏览器浏览的时候经常异常退出，提示是“出现未知错误”，重新登陆是可以进入，但是过一会（可能几秒也可能几分钟，浏览的时候回再次自动退出）。

恢复方式：
重启整个jumpserver会恢复，但是线上服务，特别是白天也不能随意重启

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/30214440/75655249-6d804d80-5c9c-11ea-8cbd-22c6a51466b8.png)

**Comment by ibuler** [comment]
查看后台报的是什么错误，请附加一下日志

**Comment by sccblue** [comment]
没开debug，后台日志很少，查了jms.log jumpserver.log都没有提示相关错误，然后其他文件celery flower.log也大概看了，没写任何log

**Comment by sccblue** [comment]
因为jumpserver/logs日志文件众多，麻烦你这边告知下应该查jumpserver/logs下的哪个日志文件，我下次出现的时候特地留意下

**Comment by sccblue** [comment]
今天发现了一个场景会退出，在维护资产树时，点开树下节点没成功，见截图，然后就弹出“出现未知错误”，需要重新登陆了
![image](https://user-images.githubusercontent.com/30214440/75967065-3614d980-5f06-11ea-8aba-a3c6e804bd95.png)
附上可能的相关log，gunicorn.log中有如下比较奇怪的异常log
172.31.240.2 [05/Mar/2020:17:06:20 +0800] "PATCH /api/v1/terminal/sessions/ab1436e1-9d27-4217-89ee-1368855ec3bb/ HTTP/1.1" 200 463
172.31.240.2 [05/Mar/2020:17:06:20 +0800] "POST /api/v1/terminal/sessions/ab1436e1-9d27-4217-89ee-1368855ec3bb/replay/ HTTP/1.1" 201 81
172.31.240.2 [05/Mar/2020:17:06:20 +0800] "PATCH /api/v1/terminal/sessions/ab1436e1-9d27-4217-89ee-1368855ec3bb/ HTTP/1.1" 200 461
127.0.0.1 [05/Mar/2020:17:06:21 +0800] "GET /api/v1/assets/assets/?node_id=bc4b4a4e-034c-4983-8fd1-c19a2bf8a32d&show_current_asset=null&draw=11&limit=15&offset=0&_=1583399066205 HTTP/1.0" 200 1
4177
172.31.240.2 [05/Mar/2020:17:06:22 +0800] "POST /api/v1/terminal/terminals/status/ HTTP/1.1" 201 2
127.0.0.1 [05/Mar/2020:17:06:23 +0800] "GET /api/v1/assets/assets/?node_id=bc4b4a4e-034c-4983-8fd1-c19a2bf8a32d&show_current_asset=null&draw=12&search=r&limit=15&offset=0&_=1583399066206 HTTP/1
.0" 200 14101
172.31.240.2 [05/Mar/2020:17:06:23 +0800] "GET /api/v1/terminal/terminals/config/ HTTP/1.1" 200 2116
127.0.0.1 [05/Mar/2020:17:06:24 +0800] "GET /api/v1/assets/assets/?node_id=bc4b4a4e-034c-4983-8fd1-c19a2bf8a32d&show_current_asset=null&draw=13&search=ris&limit=15&offset=0&_=1583399066207 HTTP
/1.0" 403 43
127.0.0.1 [05/Mar/2020:17:06:24 +0800] "GET /api/v1/assets/assets/?node_id=bc4b4a4e-034c-4983-8fd1-c19a2bf8a32d&show_current_asset=null&draw=14&search=rispee&limit=15&offset=0&_=1583399066208 H
TTP/1.0" 200 52
127.0.0.1 [05/Mar/2020:17:06:25 +0800] "GET /api/v1/assets/assets/?node_id=bc4b4a4e-034c-4983-8fd1-c19a2bf8a32d&show_current_asset=null&draw=15&search=rispeed&limit=15&offset=0&_=1583399066209
HTTP/1.0" 403 43
172.31.240.3 [05/Mar/2020:17:06:26 +0800] "POST /api/v1/terminal/terminals/status/?from_guacamole=1 HTTP/1.1" 201 2
172.31.240.3 [05/Mar/2020:17:06:36 +0800] "POST /api/v1/terminal/terminals/status/?from_guacamole=1 HTTP/1.1" 201 2
172.31.240.2 [05/Mar/2020:17:06:42 +0800] "POST /api/v1/terminal/terminals/status/ HTTP/1.1" 201 2

**Comment by sccblue** [comment]
还有这些其他时间点的异常退出，也有类似log
127.0.0.1 [05/Mar/2020:10:50:26 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A2&n=aws%20(204)&lv=1&_=1583376621781 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:28 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A0%3A0%3A26&n=cn-beijing%20(603)&lv=3&_=1583376621782 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:29 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A0%3A0%3A26&n=cn-beijing%20(603)&lv=3&_=1583376621783 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:30 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A2&n=aws%20(204)&lv=1&_=1583376621784 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:32 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A2&n=aws%20(204)&lv=1&_=1583376621785 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:32 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A1&n=txy%20(202)&lv=1&_=1583376621786 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:34 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A1&n=txy%20(202)&lv=1&_=1583376621787 HTTP/1.0" 403 43
127.0.0.1 [05/Mar/2020:10:50:35 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0&key=1%3A1&n=txy%20(202)&lv=1&_=1583376621788 HTTP/1.0" 403 43

**Comment by cheekboy** [comment]
我也有同样的问题  请问解决了么？

**Comment by ibuler** [comment]
打开新的页面，看看需不需要重新登录

**Comment by sccblue** [comment]
需要的，强制退出到登陆页
