### ISSUE TITLE
v1.5.6-2 rdp没有录像

### ISSUE THREAD

**Issue by FailEnd** [jumpserver/jumpserver#3738]
[简述你的问题]
jumpserver版本：v1.5.6-2
问题：使用web终端连接windows服务器，会话结束后没有录像；SSH登录的设备有录像

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/39001664/75656452-ef717600-5c9e-11ea-928f-b99249d9973e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by vampniklaus** [comment]
老兄，你这问题咋解决的？

**Comment by FailEnd** [comment]
重启了下docker就好了
________________________________
发件人: vampniklaus <notifications@github.com>
发送时间: 2020年3月6日 下午 04:56
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: FailEnd <xk0720@hotmail.com>; State change <state_change@noreply.github.com>
主题: Re: [jumpserver/jumpserver] v1.5.6-2 rdp没有录像 (#3738)


老兄，你这问题咋解决的？

―
