### ISSUE TITLE
期待syslog的功能

### ISSUE THREAD

**Issue by OrderSY2017** [jumpserver/jumpserver#3741]
希望增加一个syslog的功能接第三方日志接入方便更好的安全审计 用户登录用户操作主机等日志输出的功能还希望有日志格式文档方便做日志泛化

**Comment by ibuler** [comment]
已支持，手机不方便发说明，明天补充

**Comment by ibuler** [comment]
config.yml

SYSLOG_ENABLE: true
SYSLOG_FACILITY: user
SYSLOG_SOCKTYPE: udp
SYSLOG_ADDR: 192.168.1.1:514

**Comment by OrderSY2017** [comment]
收到,您有时间受累写在 ,"日志介入格式说明"。就是每个关键字对应的意思。我好做第三方日志系统接入泛化。例如：
{"center_version":"1.0.5.8","event_type":"","event":{}}
| 关键字 | 描述 |
| center_version | 当前中心版本 |
| event_type | 日志类型（中文） |
| event | 日志数据 |
| |
ordersy
|
|
ordersy@126.com
|
签名由网易邮箱大师定制
在2020年3月10日 14:59，老广<notifications@github.com> 写道：

config.yml

SYSLOG_ENABLE: true
SYSLOG_FACILITY: user
SYSLOG_SOCKTYPE: udp
SYSLOG_ADDR: 192.168.1.1:514

**Comment by luweijun1992** [comment]
@ibuler syslog这块在官网文档并没用看到相关介绍，包括现在版本的config.txt中并没有看到你上面介绍的参数。请问是否有相关资料，谢谢。

**Comment by ibuler** [comment]
高级货，隐藏功能 (其实是文档不全)

**Comment by Lllly101** [comment]
syslog支持打入kafka吗？
