### ISSUE TITLE
jumpserver/data/celery/目录下inode占满

### ISSUE THREAD

**Issue by sccblue** [jumpserver/jumpserver#3743]
[简述你的问题]
jumpserver/data/celery/目录下inode占满

##### 使用版本
Jumpserver版本 1.5.6

##### 问题复现步骤
1. 问题
jumpserver/data/celery/目录下一堆小文件，占满系统的inode资源
2. 处理方案
需要停jumpserver，然后整个目录删除后重新启动jumpserver

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈

**Comment by sccblue** [comment]
好的，多谢回复
昨天升级到2.0.1，观察几天看看
