### ISSUE TITLE
windows资产怎么录制视频？

### ISSUE THREAD

**Issue by s2wcn** [jumpserver/jumpserver#3744]
[简述你的问题]
windows资产的连接记录，无法回放，回放按钮不能点击。

##### 使用版本
1.56

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@s2wcn 重启guacamole即可。

**Comment by ibuler** [comment]
应该是某个会话的录像没有上传
