### ISSUE TITLE
新建资产授权无法在系统用户中找到相应的资产

### ISSUE THREAD

**Issue by LongTaiJun** [jumpserver/jumpserver#3745]
[简述你的问题]
新建资产授权无法在系统用户中找到相应的资产
相应的账户也没有推送到服务器

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]新建资产授权添加资产服务器
2. [步骤2]在资产管理中的系统用户下看不到授权的服务器

##### 具体表现[截图可能会更好些,最好能截全]
简单来说就是服务器添加到授权规则，但是在相应的系统用户下却看不到关联的服务器资产，对应的系统用户也没油推送。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
重新修改一下授权规则，先去掉原来的资产和系统用户，然后重新添加，

另外 新版本增加了手动添加
