### ISSUE TITLE
登录之后经常跳首页

### ISSUE THREAD

**Issue by cheekboy** [jumpserver/jumpserver#3747]
[简述你的问题]

##### 使用版本
1.56-2
##### 问题复现步骤
1. 登录之后经常出现 cook丢失  访问页面 调试是403  自动跳转到首页  
![image](https://user-images.githubusercontent.com/16200728/75851619-1a85d200-5e25-11ea-9597-e75e3c175d93.png)

重新登录有时候会出现设置浏览器cookie
![image](https://user-images.githubusercontent.com/16200728/75851663-42753580-5e25-11ea-827f-1aa36fcdadba.png)

[注:] 完成后请关闭 issue

**Comment by cheekboy** [comment]
问题和#3737是一样的  出现未知错误  403返回登录页面

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/issues/3737  相同，暂时关闭该issue，关注同一个

**Comment by cheekboy** [comment]
我的已经解决   开了两个jumpserver  redis连的同一个    后面改掉就可以了
