### ISSUE TITLE
vnc或rdp协议怎么配置超时？

### ISSUE THREAD

**Issue by peixubin** [jumpserver/jumpserver#3748]
通过vnc或rdp协议登录资产时，客户端长时间没有活动，怎么让他自动退出？好像默认是60分钟？
希望能够在10分钟没有活动就自动退出。

##### 使用版本
1.5.5

##### 问题复现步骤
1. 使用vnc或rdp协议配置并登录资产；
2. 无法在较短的时间内，没有活动就自动中断。

**Comment by ibuler** [comment]
和ssh一样，系统设置-- 安全设置 -- 连接最大空闲时间 修改即可

**Comment by peixubin** [comment]
改了，没生效

**Comment by peixubin** [comment]
比如改为10分钟，但到点了没中断

**Comment by wojiushixiaobai** [comment]
这个是guacamole的设置,或者你可以修改资产的超时设置即可
