### ISSUE TITLE
ftp 文件管理功能提示文件夹不存在

### ISSUE THREAD

**Issue by 932340583** [jumpserver/jumpserver#3749]
[简述你的问题]
jumpserver连接某个linux资产正常，但是使用ftp功能连接该资产就会提示文件夹不存在。这种情况只会在使用网关登录的资产中出现，非网关登录的资产不会出现此问题

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6

##### 问题复现步骤
1. [步骤1] 使用文件管理功能连接使用网关登录的资产
2. [步骤2] 等待几秒出现”文件夹不存在.“的提示，但使用web终端连接该资产是正常的

##### 具体表现[截图可能会更好些,最好能截全]

koko错误日志：
2020-03-04 17:07:32 [ERRO] Get new SSH client err: dial tcp 10.251.72.100:22: i/o timeout
2020-03-04 17:07:32 [ERRO] Get Sftp Client err: dial tcp 10.251.72.100:22: i/o timeout

nginx错误日志：
2020/03/05 08:42:44 [error] 5346#5346: *54625 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: x.x.x.x, request: "GET /api/v1/perms/users/nodes/children-with-assets/tree/?cache_policy=1&key=1%3A0%3A0&n=NA%20(2)&lv=2&_=1583368904557 HTTP/1.1", upstream: "http://[::1]:8080/api/v1/perms/users/nodes/children-with-assets/tree/?cache_policy=1&key=1%3A0%3A0&n=NA%20(2)&lv=2&_=1583368904557", host: "x.x.x.x", referrer: "https://x.x.x.x/luna/?_=1582990095"

##### 其他
koko中配置的upload目录是存在的，日志中出现I/O timeout， 已经关闭sshd中的DNS解析功能，也重启过docker。

[注:] 完成后请关闭 issue

**Comment by 932340583** [comment]
jumpserver中没有发现相关日志错误，只在koko中和nginx中发现上述错误日志

**Comment by 932340583** [comment]
在web终端中右键资产使用文件管理功能，则不会出现此问题，但这种方式不提供跨主机复制文件的功能。

**Comment by LeeEirc** [comment]
@932340583 节点名称和资产名称是否存在特殊的字符如 "/"  "\" 等。

**Comment by 932340583** [comment]
节点名称和资产名称均为字母数字和下划线组成，没有其它特殊符号，如dev_master_server, dev2_slave2_server之类的名称。且之前使用正常，给jumpserver使用的网关主机突然挂掉后启动起来，jumpserver才出现了这种问题，之前是正常的。

**Comment by 932340583** [comment]
![image](https://user-images.githubusercontent.com/17899509/76175524-0278ce80-61e8-11ea-812b-31bb50dd1fd4.png)
这是在文件管理功能中的情况
![image](https://user-images.githubusercontent.com/17899509/76175546-1de3d980-61e8-11ea-9cf2-0e8d3de6e467.png)
这是在web终端中的文件管理功能情况
都是同一台主机
@LeeEirc

**Comment by LeeEirc** [comment]
@932340583 网关重启之后，网关的配置是否发生变化了，再核查一下吧。

**Comment by 932340583** [comment]
具体核查哪方面的信息？jumpserver和网关主机都没有发生任何配置改变

**Comment by 932340583** [comment]
而且我今天还发现个现象，如果在需要网关登陆的资产cd进ftp的目录，这时候文件管理功能就可以用，除此之外都会报没有文件夹的问题，我排查了网关主机和jumpserver的设置，都没什么问题，连接网关资产也没什么问题。非网关资产所有功能都正常。

**Comment by LeeEirc** [comment]
@932340583 文件管理只有在登录进某个资产的系统用户后才可使用， 外层的都是资产展示。如果无法登录的情况下，或者 SSH 连接出错的情况下，都无法进行创建文件。后期会优化错误提示信息。

**Comment by 932340583** [comment]
那现在我碰到的情况，是正常的呢，还是不正常的，我有点搞不懂了，因为非网关资产ftp是直接可以用的呀？我又在koko的日志发现了这个错误，以上面贴的错误都是在网关资产ftp报错的情况下出来的。

2020-03-10 11:20:29 [DEBU] volume Parents: /
2020-03-10 11:20:31 [INFO] Request 5c51257c-0111-435d-b3c1-0db568d73412: web folder ws disconnect
2020-03-10 11:20:31 [ERRO] Close SSH client 0xc002260e60 err: EOF 
2020-03-10 11:20:31 [INFO] SSH client 0xc002260e60 keep alive stop
2020-03-10 11:20:32 [ERRO] Close SSH client 0xc0022607d0 err: EOF 
2020-03-10 11:20:32 [INFO] SSH client 0xc0022607d0 keep alive stop
2020-03-10 11:20:32 [INFO] User rt.lucascheng's volume close
2020-03-10 11:20:32 [DEBU] Ws connection disconnect

也就是说，我现在想用ftp必须先登录资产，而且之后的版本会按照这个逻辑设计，想用ftp必须要登录资产，对吗？如果是这样的话，这个问题我就不追查了，然后关闭此issue，谢谢。
@LeeEirc 

> @932340583 文件管理只有在登录进某个资产的系统用户后才可使用， 外层的都是资产展示。如果无法登录的情况下，或者 SSH 连接出错的情况下，都无法进行创建文件。后期会优化错误提示信息。

**Comment by 932340583** [comment]
当前的状态是网关资产的ssh登录连接没有问题，只是ftp报错，非网关资产是正常的。这个错就是因为日志里连接i/o超时导致的？那这个失败是因为哪里失败的？我在jumpserver各个组件的日志中只在koko和nginx中找到了相关报错，其它都没有。我要执行哪些操作进行修复？

**Comment by LeeEirc** [comment]
@932340583 应该是web sftp登录资产的时候，没有使用网关，造成使用网关的资产无法建立连接。也就是你看到的koko日志的错误，连接报i/o timeout 错误。下个版本修复。你的情况和这个类似[issue](https://github.com/jumpserver/koko/issues/238)

**Comment by 932340583** [comment]
@LeeEirc OK, 了解了，感谢支持。
