### ISSUE TITLE
用户连接到服务器报错：ssh: rejected: administratively prohibited

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#3751]
[简述你的问题]

##### 使用版本
1.5.6-2

docker容器化部署
jumpserver/jms_core:1.5.6
jumpserver/jms_koko:1.5.6
jumpserver/jms_guacamole:1.5.6

##### 问题复现步骤
1. 用户使用webterminal  或者 ssh client 跳转连接一台服务器，会出现错误，参见截图

##### 具体表现[截图可能会更好些,最好能截全]
![微信图片_20200305103803](https://user-images.githubusercontent.com/1665397/75942582-bd922680-5ecd-11ea-9d69-c8edf0b80ec4.png)

##### 其他

这台机器是在另一个网域，使用网域网关进行的转发。
只有这个用户连接到这台服务器才会报错，该用户连接其他机器，或者其他用户连接这台机器，都没有问题。

[注:] 完成后请关闭 issue

**Comment by leim** [comment]
查看这台服务器的进程，发现有大量sftp进程，但是此时并没有任何用户在使用jumpserver进行sftp上传下载。


![捕获](https://user-images.githubusercontent.com/1665397/75943455-f92df000-5ecf-11ea-876e-847904cc99f3.PNG)

**Comment by ibuler** [comment]
应该是连接复用导致的

**Comment by ibuler** [comment]
@LeeEirc

**Comment by LeeEirc** [comment]
@leim 先手动关闭这些连接吧。可能是web sftp的连接没释放造成的。你们可以先停用ssh的连接复用。

**Comment by leim** [comment]
目前已经手动关闭ssh连接复用，状况已消失

**Comment by leim** [comment]
关闭ssh连接复用之后，又出现了另外一个问题，参见
https://github.com/jumpserver/jumpserver/issues/3757
