### ISSUE TITLE
Feature Request: 支持ECDSA、ED25519算法的SSH私钥

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#3752]
[简述你的问题]

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
OpenSSH 8.2版本中，因RSA算法密钥的碰撞成本降低，已禁用ssh-rsa算法。
请支持ECDSA、ED25519算法的SSH私钥。
![image](https://user-images.githubusercontent.com/11138015/75955388-b4668100-5ef0-11ea-8bbd-641ad086775f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
jumpserver依赖了 paramiko, paramiko 本身不支持，https://github.com/paramiko/paramiko/issues/243

paramiko支持了，我们第一时间处理

**Comment by naizhao** [comment]
paramiko现在已经支持ed25519了吧

**Comment by ibuler** [comment]
已添加支持， https://github.com/jumpserver/jumpserver/pull/5604，感谢 @naizhao
