### ISSUE TITLE
添加资产到节点，怎么添加不了。

### ISSUE THREAD

**Issue by 84067176** [jumpserver/jumpserver#3753]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6-2
##### 问题复现步骤
1. [步骤1]
我使用docker-composer 安装的，这个地址
git clone https://github.com/wojiushixiaobai/docker-compose.git
2. [步骤2]
为什么我点击添加资产到节点，老是不行。
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20683869/76072126-60cc6400-5fd2-11ea-9866-2b910862dc80.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@84067176 看下日志是否有提示错误

**Comment by 84067176** [comment]
![image](https://user-images.githubusercontent.com/20683869/76269192-a4adba80-62ab-11ea-98dd-5163cdaac764.png)
![image](https://user-images.githubusercontent.com/20683869/76269225-be4f0200-62ab-11ea-9a50-8b9d314cc4e4.png)
我重新再虚拟机里面，用docker-compose搭建一个新的环境，也是发送右键点击添加资产节点，点击添加了没有反应。

**Comment by 84067176** [comment]
![image](https://user-images.githubusercontent.com/20683869/76274774-80a6a500-62bc-11ea-9646-99eff2e5cc59.png)

**Comment by ibuler** [comment]
api报错了，发一下日志，看看到底问题在哪

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
