### ISSUE TITLE
新增普通用户无法连接服务器

### ISSUE THREAD

**Issue by zhaosr** [jumpserver/jumpserver#3754]
[简述你的问题]
我创建了新的普通用户，通过系统自动推送，并确认系统用户已经创建成功。详情页中测试资产可连接性没问题，在命令行终端连接，无任何反应

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
系统版本：CentOS Linux release 7.3.1611
jumpserver版本：Version 1.5.6-2
##### 问题复现步骤
1. [新建普通用户,推送普通用户,测试连接都ok，同时将普通用户优先级调高了]
2. [删除旧的普通用户]
3. [使用新的用户登录服务器]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/27752545/76181615-af5d4680-61fc-11ea-9ad5-6dd9e86119b5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@zhaosr 有什么报错信息吗？koko的日志贴一下。

**Comment by zhaosr** [comment]
![image](https://user-images.githubusercontent.com/27752545/76610348-bd3ffe00-6553-11ea-9ce5-2a896fb9db19.png)
账户登录的时候会有报错日志，但也能够正常登录。登录以后，连接远程服务器的操作，日志里没有任何刷新

**Comment by zhaosr** [comment]
我今天把所有无法登录的资产删除掉，重新创建，重新推送普通用户，celery没有报错，登录上服务器去看也正常创建了普通用户，测试连接也都ok，但是通过终端去连接，现象跟之前一致，我不知道是不是数据库的某个关联关系还没有解除

**Comment by LeeEirc** [comment]
你说的没反应，是输入卡死，还是直接就跳过登录信息，没有任何输出？

**Comment by zhaosr** [comment]
直接就跳过登录信息，没有任何输出

**Comment by LeeEirc** [comment]
这个没道理呀？只要新创建的普通用户都存在这种情况吗？还是所有资产都存在这种情况？你koko使用的什么版本？jumpserver和koko两个都是最新的吗？

**Comment by zhaosr** [comment]
我这个koko是 1.5.6
jumpserver Version 1.5.6-2 GPLv2

还没测试别的机器，目前就这部分资产是这个情况。
其他机器还是用的管理用户去登录的

**Comment by LeeEirc** [comment]
@zhaosr 加我qq 2970298425，我远程看下。

**Comment by zhaosr** [comment]
已加

**Comment by zhaosr** [comment]
忘了普通用户的授权了，实在是尴尬了，谢谢大佬，问题成功解决！
