### ISSUE TITLE
升级jumpserver1.5.6后,出现两个问题请求帮忙谢谢！

### ISSUE THREAD

**Issue by lyric2018** [jumpserver/jumpserver#3755]
[简述你的问题]
升级jumpserver1.5.6后，
问题1
      报错 Connect asset java-cloud-consumer02 error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
问题2 
  发现系统普通用户不可以sudo了这是怎么回事？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1 问题  @LeeEirc 处理一下
2 问题 查看该系统用户是否有sudo权限，是否和推送有关

**Comment by LeeEirc** [comment]
@lyric2018 第一个问题，可以先看一下是否资产的sshd配置里面是否开启了password的认证。
