### ISSUE TITLE
jumpserver升级数据库为mysql8时migration数据时报错

### ISSUE THREAD

**Issue by jiangxiaobai** [jumpserver/jumpserver#3756]
[简述你的问题]
jumpserver升级数据库为mysql8时migration数据时报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
在原有的服务器上不动mysql5.6的情况下，安装上mysql8监听在不同端口,创建好jumpserver数据库和用户以及赋权
2. [步骤2]
修改jumpserver的配置文件config.yml，修改数据库配置（修改端口号），重启jumpserver服务
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/17025080/76274814-a2079100-62bc-11ea-8587-8d9cacad6eca.png)

#### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
mysql 8 没有经过测试
