### ISSUE TITLE
使用网域网关跳转的机器SFTP时连接问题

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#3757]
[简述你的问题]

有一组服务器，在另外一个网域内，使用网域网关进行跳转连接，

##### 使用版本
1.5.6-2
docker容器化部署
jumpserver/jms_core:1.5.6
jumpserver/jms_koko:1.5.6
jumpserver/jms_guacamole:1.5.6

##### 问题复现步骤
假设有一台在另外一个网域下的服务器A，需要通过网域网关进行跳转连接。

1. 直接打开 koko/elfinder，找到服务器A，打开这台机器的文件夹，直接超时，无法打开，查看koko的日志，显示如下：
[DEBU] Dial host 172.31.1.4:22
[ERRO] Get new SSH client err: dial tcp 172.31.1.4:22: i/o timeout
[ERRO] Get Sftp Client err: dial tcp 172.31.1.4:22: i/o timeout

2. 首先打开luna，在luna中通过webterminal 连接这台机器，然后在通过 elfinder 打开这台服务器，如果koko配置了连接复用，会立刻连接成功，如果koko关闭了连接复用，那么也会连接失败，报错和上面相同。

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@leim 下个版本修复这个问题。可以目前你可以先参考这个[issue](https://github.com/jumpserver/koko/issues/238)
