### ISSUE TITLE
文件下载时，针对服务器有多个系统用户授权，下载时权限匹配不了，导致下载失败

### ISSUE THREAD

**Issue by caltonwu** [jumpserver/jumpserver#376]
下载时，如何选择授权的系统用户？

**Comment by caltonwu** [comment]
ssh方式

**Comment by caltonwu** [comment]
找到了具体原因：
用户授权使用NOPASSWD: ALL sudo权限 
下载的文件放在另一普通用户家目录，命令行d/D下载时，导致下载不下来，日志报debug:the remote file does not exist, not transferring, ignored,

如果文件没有读的权限也会报错：no read permission on remote file

既然针对普通用户授权了，下载普通用户家目录下的文件应该也是被允许的，同时web会下载一个tar.gz但没有文件

**Comment by ibuler** [comment]
收到反馈，文件上传，下载，确实存在一些问题，这么做文件传输也存在一定的不合理
