### ISSUE TITLE
官网：Docs » 安装文档 » 一站式、分布式安装文档 » CentOS 7 安装文档

### ISSUE THREAD

**Issue by bailiang27** [jumpserver/jumpserver#3761]
[简述你的问题]
官方安装文档，多了个wget

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
https://jumpserver.readthedocs.io/zh/master/setup_by_centos7.html

# 安装 docker 部署 koko 与 guacamole  小节

$ yum install -y yum-utils device-mapper-persistent-data lvm2
$ yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
$ yum makecache fast
$ rpm --import https://mirrors.aliyun.com/docker-ce/linux/centos/gpg
$ yum -y install docker-ce
$ systemctl enable docker wget
$ mkdir /etc/docker
$ wget -O /etc/docker/daemon.json http://demo.jumpserver.org/download/docker/daemon.json
$ systemctl restart docker

systemctl enable docker wget         《------------------------- 这里，多了个wget。
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bailiang27 感谢提醒，已修复
