### ISSUE TITLE
关于windows连接问题

### ISSUE THREAD

**Issue by momaixi** [jumpserver/jumpserver#3762]
[简述你的问题]
windows终端远程故障。web终端报错：

“
连接错误
无法连接服务器，请联系管理员或查看日志。

”

点击重连  无效

或无任何响应。

不做任何改动，一段时间后，可能又可以打开一次，一旦关闭web终端就 又无法打开。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.6-2 GPLv2.

浏览器版本 IE11 、chrome  79.0.3945.88 、FireFox 72.0.2

#### 问题复现步骤
1. [步骤1]
docker正常安装或官网快速部署，顺利且正常。
配置标准流程，正常。

2. [步骤2]
切换普通用户登录，从首页我的资产 动作 启动web终端第一次登陆一切正常，关闭后，再重新再打开时，web终端报错，或无任何响应。

3. [步骤3]
不做任何改动，只需等待若干时间后，可能会恢复，如果没恢复就继续等待，恢复后重复步骤2.

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/61999393/76311331-b161fb00-630b-11ea-9bac-70c35250890b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@momaixi 如果有外网资产的话，可以尝试在demo复现试试

**Comment by watson6** [comment]
不做任何改动，一段时间后，可能又可以打开一次，一旦关闭web终端就 又无法打开。
_____
我在1.5.8版本也同样遇到这个问题。第一次登录是可以连接远程桌面，如果关闭页面之后，再连接就不行了。

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈

**Comment by watson6** [comment]
> 请验证新版本是否仍然出现此问题，感谢反馈

Version 1.5.8-2 GPLv2.  在用这个版本仍然出现过这个问题。
