### ISSUE TITLE
jms_install.sh脚本执行到MarkupSafe时报错

### ISSUE THREAD

**Issue by Faith-Hao** [jumpserver/jumpserver#3763]
[简述你的问题]
Docker部署执行脚本jms_install.sh到MarkupSafe时报错，具体如下：
Downloading https://mirrors.aliyun.com/pypi/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g8se99n7/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g8se99n7/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-g8se99n7/MarkupSafe/pip-egg-info
         cwd: /tmp/pip-install-g8se99n7/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g8se99n7/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

##### 使用版本
1.5

##### 问题复现步骤
1. sh jms_install.sh
2. 执行到pip install -r /opt/jumpserver/requirements/requirements.txt
时报错

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/8134311/76348367-0836f700-6343-11ea-8c6d-92d9702fc20c.png)

**Comment by wojiushixiaobai** [comment]
@Faith-Hao 注释掉 pip install --upgrade pip setuptools 即可，setuptools 版本导致的
