### ISSUE TITLE
jumpserver1.5.6正常部署完成，但无法打开首页

### ISSUE THREAD

**Issue by jorlen** [jumpserver/jumpserver#3765]
[简述你的问题]
##### 使用版本
Centos 7
jumpserver 1.5.6
esxi6.7平台
---------------------
使用极速安装，Koko、Guacamole 容器化部署。

步骤一：
之前一直是markupsave依赖库报错，自己修改版本后可以正常安装完成，但无法访问首页。

步骤二：
现在不用修改依赖库，用脚本也可以正常安装完成了，但完成后，用ip访问依旧打不开首页，
感觉是安装有问题，查询jumpserver/logs没有发现错误，nginx启动也正常，
Koko、Guacamole ，状态为waiting for jms_core ready

Help：
请问各位大拿，哪里出了问题？
搞了一个星期，精疲力尽了，能力有限，请多多指点，谢谢！

**Comment by ibuler** [comment]
截图看看首页报的什么错

**Comment by wojiushixiaobai** [comment]
@jorlen 检查下防火墙和端口有没有被占用，可以尝试手动启动看看错误
手动启动命令如下
```
cd /opt/jumpserver
source /opt/py3/bin/activate
./jms start
```

**Comment by jorlen** [comment]
已经解决，关闭其他虚拟机就正常了，估计是虚机之间有服务冲突，谢谢支持！
