### ISSUE TITLE
?cache_policy=1 - 404 Not Found

### ISSUE THREAD

**Issue by aa6my** [jumpserver/jumpserver#3768]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4
##### 问题复现步骤
1. After all complete follow tutorial at https://www.alibabacloud.com/blog/how-to-set-up-jumpserver-bastion-host-on-alibaba-cloud-ecs_594787
2. After create new user
3. Login as new user for access terminal
4. Access terminal not working

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7272163/76486094-53432e00-6459-11ea-9ade-ba53df53b4be.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
Please COPY the url in the browser, then direct visit, let me see the error msg detail

**Comment by wojiushixiaobai** [comment]
@aa6my Try updating to the latest version
