### ISSUE TITLE
ssh心跳检测无重试机制配置，导致使用体验较差

### ISSUE THREAD

**Issue by huangpeng0817** [jumpserver/jumpserver#3772]
现网生产环境，目前使用下来，出现多起反馈，连接上资产的时候，突然会被断开。
后台错误：[ERRO] SSH client 0xc00161fae0 keep alive err: EOF
keepalive 心跳检测无重试机制，一次检测问题即连接关闭，网络稍有波动，导致需要频繁重新登陆。
希望在增加心跳重试机制，配置文件中增加重试次数配置，方便不同网络环境使用
![image](https://user-images.githubusercontent.com/46477158/76585943-8a2d4880-651a-11ea-8c82-06c2b64fc896.png)

**Comment by LeeEirc** [comment]
将在新版本koko中增加重试机制的设置。

**Comment by ibuler** [comment]
新版本已解决，感谢反馈，有问题可以重新打开

**Comment by teesa-git** [comment]
您好，我的1.5.8版本，还是遇到一样的问题。

![20200515161211](https://user-images.githubusercontent.com/52067473/82027580-0a149200-96c7-11ea-9ab1-c221e8523ec1.png)

![20200515160947](https://user-images.githubusercontent.com/52067473/82027629-20bae900-96c7-11ea-9af6-1d3c2a1248ed.png)

![20200515160707](https://user-images.githubusercontent.com/52067473/82027727-43e59880-96c7-11ea-8a2d-8f6b8ebcd6b7.png)

到KOKO容器里面修改配置文件，重启后还是连接一会就中断。
