### ISSUE TITLE
用户通过LDAP导入，公司强制LDAP每三个月修改一次密码。LDAP用户密码更改后，jumpserver就无法登陆了，新老密码都不行，需要重新导入。 求帮助验证。谢谢

### ISSUE THREAD

**Issue by 13691432320** [jumpserver/jumpserver#3774]
[简述你的问题]
用户通过LDAP导入，公司强制LDAP每三个月修改一次密码。LDAP用户密码更改后，jumpserver就无法登陆了。新老密码都不行！

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.6-2 GPLv2.
Copyright FIT2CLOUD 飞致云 © 2014-2020
##### 问题复现步骤
1. [步骤1]
通过LDAP导入用户 分配相关资产权限。这一步没问题 可以正常使用
2. [步骤2]
LDAP用户密码更改后，jumpserver无法同步。新老密码都登陆不上去。
这是需要在jumpserver中删除之前的用户，然后重新导入。才行

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/41263103/76588759-daa8a400-6522-11ea-8f81-a94c9ccef01c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
JumpServer是不保存用户密码的，请尝试清理一下redis数据，ldap认证库好像有个设置缓存的东西

```
$ redis-cli 
$ select 4
$ keys :1:django_auth_ldap*

```

清理一下

**Comment by 13691432320** [comment]
好的我试试， 对了 广总，windows电脑用xshell  连接 输入
ssh -p 2222 user@ip  这样好像不行 应该是xshell 默认把-p 参数化了 
可以出一版教程

**Comment by ibuler** [comment]
如果问题存在请重新打开issue

**Comment by binco** [comment]
同样的问题，怎么处理的？
