### ISSUE TITLE
资产授权列表左侧有多台机器重复显示在未分组列表里

### ISSUE THREAD

**Issue by jitangshaobing** [jumpserver/jumpserver#3776]
[资产授权列表左侧有多台机器重复显示在未分组列表里]

##### 使用版本
1.5.6-2

![image](https://user-images.githubusercontent.com/13791128/76597554-b1e0d880-653b-11ea-94ac-f8a626f87260.png)

**Comment by wojiushixiaobai** [comment]
@jitangshaobing 资产详情里面手动删掉多余的节点

**Comment by jitangshaobing** [comment]
![image](https://user-images.githubusercontent.com/13791128/76602708-7697d700-6546-11ea-92a1-c52e28533053.png)
资产列表是正常的
