### ISSUE TITLE
wojiushixiaobai和jumpserver哪个是以后的官方镜像

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#3777]
[简述你的问题]
wojiushixiaobai/jms_*和jumpsever/jms_*不能通用，考虑到日后升级，在生产环境要用哪个版本。

##### 使用版本
1.5.6
##### 问题复现步骤
1，搭建了两套jumpserver，主jms使用wojiushixiaobai/jms_*镜像搭建，可以正常使用
2，用jumpserver/jms_*镜像搭建一套测试jms，docker-compose.yml是一个，只是image换了。
3，从主jms导出数据库导入到测试jms，发现用户的密钥丢失了，需要重新输入才行，系统用户也是一样，管理用户没测。
4，用wojiushixiaobai/jms_*搭建另一套测试jms就可以正常使用。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
今天开始整理，以后使用 jumpserver下的镜像
