### ISSUE TITLE
Jumpserver web控制台等宽字体显示异常问题

### ISSUE THREAD

**Issue by zengyongjie** [jumpserver/jumpserver#3778]
[简述你的问题]

Ubuntu下Web终端字体异常。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.8

##### 问题复现步骤
1. 使用Web终端功能连接远程主机

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/62204644/76725713-024d7580-678a-11ea-80d1-2820f505483b.png)

这个字体总是无法调整过来 ，看起来总是全角的。

我浏览器的字体设置如下：
![image](https://user-images.githubusercontent.com/62204644/76725749-26a95200-678a-11ea-8af5-452a4e7cf02b.png)

操作系统字体如下：
![image](https://user-images.githubusercontent.com/62204644/76725769-3f196c80-678a-11ea-96fb-7bf2112f8e6f.png)

只有这一个网站是这样子的，显示等宽字体感觉总是全角的  ，其余的显示等宽字体都OK。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
https://github.com/jumpserver/luna/blob/master/src/app/utils/common.ts#L25

luna默认使用了这些字体，ubuntu上可能不支持，你可以修改一下build，测试一下哪个是最好的，然后反馈一下

**Comment by zengyongjie** [comment]
> https://github.com/jumpserver/luna/blob/master/src/app/utils/common.ts#L25
> 
> luna默认使用了这些字体，ubuntu上可能不支持，你可以修改一下build，测试一下哪个是最好的，然后反馈一下

我把系统等宽字体改成列表中的字体“monaco”就可以了

**Comment by herbertpengbo** [comment]
在字体的高级设置中，取消勾选“允许页面选择自己的字体……”
