### ISSUE TITLE
跨公网分布式部署时的加密问题

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#3779]
[简述你的问题]
公司是多云环境，打算把core和koko跨公网部署，这样koko可以部署在目标主机附近。不过koko默认连接core的8080是明文传输的，简单看一下似乎都是访问/api，和其它特殊路径如ws没有冲突，能否把koko连接到443端口，然后nginx转给core的8080。
guacamole也是同样的需求。

##### 使用版本
1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@yaoluoye 可以

**Comment by ibuler** [comment]
可以用https协议来完成传输

CORE_HOST=https://xxxxx
