### ISSUE TITLE
【求助】安装时没写邮箱设置，现在想设置后台没有地方设置？Version 0.3.2 GPL

### ISSUE THREAD

**Issue by xiaoliu2012** [jumpserver/jumpserver#378]
安装时没写邮箱设置，现在想设置后台没有地方设置？
需要vi哪个文件填入邮箱设置呢？我想发送邮件的

**Comment by coolbreezeqf** [comment]
wiki 里有写, 你看完 wiki 再来提问吧, 还有你可以先搜一下已存在的 issues.

**Comment by ibuler** [comment]
修改配置文件 jumpserver.conf
