### ISSUE TITLE
任务监控功能不可用

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3780]
[简述你的问题]
docker 部署

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4-2

##### 问题复现步骤
1.点击任务监控菜单，出现以下错误：

Flow service unavailable, check it

HTTPConnectionPool(host='127.0.0.1', port=5555): Max retries exceeded with url: / (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
查看flower进程是否在运行中
```
$ ps axu | grep flower
```

如果没有代表监控组件停止了

```
$ ./jms start flower 
或者一次性启动web
$ ./jms stop 
$ ./jms start all 
```
