### ISSUE TITLE
root用户问题！

### ISSUE THREAD

**Issue by lhamburger** [jumpserver/jumpserver#3784]
[简述你的问题]
root用户登录资产。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
因环境需要用root用户登录，发现无法使用root登录。

**Comment by ibuler** [comment]
root作为系统用户是可以用来登录的

**Comment by lhamburger** [comment]
我设置的是密钥登录，未设置密码登录。登陆时总是先尝试用密码登录，然后再用密钥登录上去，导致因密码频繁登录失败，被加入ip黑名单。
