### ISSUE TITLE
文件上传不了，出错。

### ISSUE THREAD

**Issue by Jawenba** [jumpserver/jumpserver#3787]
[简述你的问题]
使用jumpserver/jms_all:latest 镜像部署的Jumpserver ，启用MFA.在web terminal 上文件上传不了，linux资产上传差不多1MB左右就不行了，而且上传的速度超慢。windows资产上传文件更差。下载文件正常。测试过用SecureCRT连接linux资产上传文件正常，速度也很快。一体安装的我从1.4.8测试到1.5.6都是有这样的问题。
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.6-2 GPLv2
##### 问题复现步骤
1. 升级windows 7 powershell 5.0
2. 配置资产，rdp,ssh协议
3、web terminal 连接资产。
4、拖拉文件到资产的 g盘。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/47962033/76917618-f20ad700-68fe-11ea-9b61-65b7a60c39bd.png)
![image](https://user-images.githubusercontent.com/47962033/76917648-06e76a80-68ff-11ea-9711-ffc92321567c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不要往G盘里上传，直接上传到桌面试试

**Comment by Jawenba** [comment]
@ibuler 一样不行。
![image](https://user-images.githubusercontent.com/47962033/76934671-85a5cd00-692a-11ea-953f-6a1ff9c9d4c6.png)
我测试在linux上传，报错是这样的。
![image](https://user-images.githubusercontent.com/47962033/76934709-99e9ca00-692a-11ea-9284-2bb642948c7c.png)

**Comment by Jawenba** [comment]
已找到问题根源，是由k8s的nginx-ingress-controller限制了，默认是1MB，需要设置参数。
nginx.ingress.kubernetes.io/proxy-body-size:"500m"
是我没有描述清楚部署环境。谢谢@ibuler的支持！
