### ISSUE TITLE
 复用能不能自动检测资产类型啊 如果是linux设备就复用 网络设备不复用

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3788]
[简述你的问题]
网络设备不能复用

复用能不能自动检测资产类型啊 如果是linux设备就复用 网络设备不复用

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新的版本将会优化这个逻辑，复用失败会自动创建新的连接
