### ISSUE TITLE
后期命令记录里搜索支持正则吗

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3800]
[简述你的问题]

1:后期命令记录里搜索支持正则吗

2:
![image](https://user-images.githubusercontent.com/44529247/77079969-b58cc780-6a33-11ea-9c2a-afdad3bd330e.png)
勾选资产之后，然后再切换右下角的用户，上面还显示已经选择了资产，但实际执行命令的时候提示没有勾选资产

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
问题已经修复,正则问题暂时没有考虑
