### ISSUE TITLE
Feature Request: Luna界面内，资产条目菜单添加复制资产功能

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#3801]
[简述你的问题]

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他
简易示意图
![image](https://user-images.githubusercontent.com/11138015/77130469-0da6e680-6a93-11ea-9405-23524e143b62.png)

除复制资产名称，还可以添加复制资产IP与端口的功能。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
已收到,我会将意见反馈上去
