### ISSUE TITLE
web和终端登录堡垒机分别设置开启MFA

### ISSUE THREAD

**Issue by liujing1087** [jumpserver/jumpserver#3802]
[简述你的问题]
希望通过web和终端登录堡垒机时能分别设置是否开启MFA二次认证。

##### 使用版本
1.5.7

##### 问题复现步骤
目前使用的场景：
1： 终端登录堡垒机采用ssh公私钥认证，堡垒机登录业务服务器集成ldap账号认证
2： web登录堡垒机集成LDAP账号密码认证，堡垒机登录业务服务器集成ldap账号认证

对于场景1， 已经使用了ssh公私钥+ldap账号密码两种认证方式，相对安全
对于场景2，仅使用了ldap账号密码认证，有安全风险。

所以，希望可以设置场景1终端登录堡垒机可以不开启MFA，场景2web登录堡垒机单独开启MFA

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
过多的认证其实不太应该,但是从安全角度考虑也不是没有道理.此建议我会反馈
