### ISSUE TITLE
1.5.7-2更新和部署还有使用中的几个问题

### ISSUE THREAD

**Issue by MaxGaius** [jumpserver/jumpserver#3805]
[简述你的问题]
##### 使用版本
1.5.7-2
##### 问题复现步骤
1. [问题1]
执行 pip install -r /opt/jumpserver/requirements/requirements.txt 版本不匹配
![image](https://user-images.githubusercontent.com/51019831/77204843-9161e100-6b2e-11ea-868a-9d726c743070.png)
尝试更新botocore和s3transfer会报 jms-storage版本不匹配
![image](https://user-images.githubusercontent.com/51019831/77204914-b6565400-6b2e-11ea-90ba-4b943a94634e.png)
![image](https://user-images.githubusercontent.com/51019831/77204927-bf472580-6b2e-11ea-839e-8a8019b168b6.png)
###多次尝试还是不行,但是不影响使用.
[注:] 完成后请关闭 issue

**Comment by bigbird1985** [comment]
已经更新了，重新pull一下
