### ISSUE TITLE
浏览器登录之后一直不会自动退出

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3806]
[简述你的问题]
升级1.5.7之后，浏览器登录之后一直不会自动退出

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7
##### 问题复现步骤
![image](https://user-images.githubusercontent.com/44529247/77241320-5691a300-6c2b-11ea-8400-b54334b4a1d1.png)

[注:] 完成后请关闭 issue

**Comment by zhangtyps** [comment]
一样1.5.7，也出现了这个问题，关闭浏览器没有作用，本人使用的firefox

`# Session expiration setting, Default 24 hour, Also set expired on on browser close
# 浏览器Session过期时间，默认24小时, 也可以设置浏览器关闭则过期
# SESSION_COOKIE_AGE: 86400
SESSION_EXPIRE_AT_BROWSER_CLOSE: true`

**Comment by zhangtyps** [comment]
一样1.5.7，很多天不用登陆了，打开jumpserver网页就自动在线
用的火狐74.0
```
# Session expiration setting, Default 24 hour, Also set expired on on browser close
# 浏览器Session过期时间，默认24小时, 也可以设置浏览器关闭则过期
# SESSION_COOKIE_AGE: 43200
SESSION_EXPIRE_AT_BROWSER_CLOSE: true
```

**Comment by BaiJiangJie** [comment]
请提供以下信息:
1. 使用的操作系统类型
2. 使用的浏览器类型
3. 浏览器退出的方式，比如直接关闭窗口呢？还是会同时退出后台程序？

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
