### ISSUE TITLE
请问数据库审计具体怎么用的？

### ISSUE THREAD

**Issue by xiaohuazi123** [jumpserver/jumpserver#3808]
[简述你的问题]
请问数据库审计具体怎么用的？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaohuazi123 快速入门已经更新了mysql的使用方式，请参考下

**Comment by xiaohuazi123** [comment]
看到了，谢谢
https://jumpserver.readthedocs.io/zh/master/quick_start.html#
