### ISSUE TITLE
变更了客户机的网卡网段，重新给jumpserver 用户加入客户机，无法发现路由的问题

### ISSUE THREAD

**Issue by intentc** [jumpserver/jumpserver#3812]
[简述你的问题]
变更了客户机到jumpserver的管理网段，重新给jumpserver 用户加入客户机，无法发现路由的问题
提示报错：
Connect asset CZIDC-SER-APP-B21 error: read tcp 172.17.0.3:53932->10.16.138.91:22: read: no route to host
jumpserver ip 10.16.138.230 可以ssh  客户机10.16.138.91

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
docker 部署的话，得把docker 重启
