### ISSUE TITLE
批量命令Error occur: SoftTimeLimitExceeded问题

### ISSUE THREAD

**Issue by Zshining** [jumpserver/jumpserver#3813]
[简述你的问题]
任务中心批量命令celery的SOFT_TIME_LIMIT已经设置为3600,但是没有生效，一直是60s，尝试升级celery版本到4.1.1,4.2.0,升级django-celery-beat到1.6.0后依然存在，直接在jms的celery启动命令里添加--soft-time-limit 3600参数也没有效果
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
作业中心批量命令执行 sleep 65 测试，在60秒时会报错

##### 具体表现[截图可能会更好些,最好能截全]
<img width="824" alt="图片" src="https://user-images.githubusercontent.com/19199818/77285499-16562180-6d0c-11ea-9cad-6af30e9075b4.png">

<img width="1262" alt="图片" src="https://user-images.githubusercontent.com/19199818/77285094-31746180-6d0b-11ea-9203-57288b3c0cf8.png">
<img width="1289" alt="图片" src="https://user-images.githubusercontent.com/19199818/77285121-48b34f00-6d0b-11ea-9a49-d92a92484341.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by Almira2020** [comment]
您好！您发布的“批量命令Error occur: SoftTimeLimitExceeded问题” ，有解决吗？

**Comment by Zshining** [comment]
是的，后来发现是soft_time_limit那里被写死了，感谢🙏
