### ISSUE TITLE
Time_zone问题

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#3814]
[简述你的问题]
我使用jumpserver_all容器部署的堡垒机，系统和容器时间都已经改成America/Chicago，但是jumpserver的登录日志及操作录制的视频时间还是Asia/Shanghai，这个怎么改呢？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.9
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@liujunfei980 默认使用了全局变量，你设置的应该没有生效。这个是在制作镜像的时候定义了。
