### ISSUE TITLE
jumpserver对应windows资产的上传下载功能

### ISSUE THREAD

**Issue by powertiandi** [jumpserver/jumpserver#3815]
[简述你的问题]

##### 使用版本
[1.5.6]

##### 问题复现步骤
1. [步骤1]
   目前搭建了jumpserver1.5.6 开源测试环境，用于测试各种基础功能，目前linux的管理还是可以的，在windows 这一块的文件上传和下载功能还没能很好的使用起来，是该版本还不支持文件的上传和下载功能吗。对于文件的上传和下载的大小有无限制。
2. [步骤2]
![image](https://user-images.githubusercontent.com/45549784/77298922-9e492500-6d26-11ea-8f77-00895b61401c.png)
windows的设备可以通过远程管理，但是文件管理这个里边不能列出来windows的资产。
![image](https://user-images.githubusercontent.com/45549784/77299039-d2bce100-6d26-11ea-925f-0f969b9f3c38.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
windows上传下载不再这里，windows可以直接拖动进去上传

https://docs.jumpserver.org/zh/master/user_terminal_web-sftp.html

**Comment by powertiandi** [comment]
看到了，多谢。不知道文件上传的大小是否有限制。
