### ISSUE TITLE
ssh连接异常

### ISSUE THREAD

**Issue by zichuanxiu06** [jumpserver/jumpserver#3820]
[简述你的问题]
ssh连接机器异常。

##### 使用版本
1.5.6

##### 问题复现步骤
1、打开web终端，再次点击目标机器，速度较慢，输入密码后无反应。
2、关掉该终端tab
3、再次点击该目标机器，无反应
4、重复10次后，出现无法连接的提示

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/9688151/77432399-f8c2ae00-6e18-11ea-979a-83e94b03d297.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by zichuanxiu06** [comment]
复现好几次了 请问有根治理的方法吗

**Comment by LeeEirc** [comment]
> 复现好几次了 请问有根治理的方法吗

使用最新的1.5.9版本，或者你资产上修改`sshd_config` 文件里 `MaxSessions`的值，设置的大一些
