### ISSUE TITLE
关于授权管理的建议

### ISSUE THREAD

**Issue by zhangtyps** [jumpserver/jumpserver#3821]
[简述你的问题]
当前的用户授权是基于资产→分配用户这样的形式授权。当我想给一个用户分配多台机器，且每台机器的系统用户都不同时，为了省事，我可能会一条授权绑定多台机器和多个系统用户，但这在用户使用时选择账户就很麻烦。但是如果一个授权只给一个系统账户，也就是用户登陆时无需选择系统用户，那我就要写很多很多的授权，使用起来也很麻烦。请问有没有计划做基于用户→资产这样形式的授权？这样授权只用在各个用户下点选资产+资产绑定的系统账户即可。

##### 使用版本
1.5.7

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
授权优化已在计划中，感谢支持
