### ISSUE TITLE
升级1.5.7后，管理员首页的月数据总览都是0

### ISSUE THREAD

**Issue by cszhi** [jumpserver/jumpserver#3823]
[简述你的问题]
升级1.5.7后，管理员首页的月数据总览都是0

##### 使用版本
1.5.7

##### 问题复现步骤
管理员登录后，首页的月数据总览，数据都是0

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/4081852/77492439-8b943480-6e7b-11ea-91cc-13a211bf24e1.png)

**Comment by wojiushixiaobai** [comment]
更新一下最新的代码，已经修复
