### ISSUE TITLE
历史会话处理规则

### ISSUE THREAD

**Issue by younikey** [jumpserver/jumpserver#3824]
[简述你的问题]
jumpeserver是不是没有对于历史会话录像的储存相关的管理设置，我想对保管的录像进行一定的规则设置，比如保留30天之类的，不然它本省是一个怎样地处理规则，我想知道一下

##### 使用版本
[1.5.7]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
新版本在系统设置-终端设置里面可以设置审计保留时长
