### ISSUE TITLE
录像bug，可复现

### ISSUE THREAD

**Issue by zhangtyps** [jumpserver/jumpserver#3827]
[简述你的问题]

##### 使用版本
1.5.7

##### 问题复现步骤
1. 快速点击web终端里同一台机器，让其同一时间开两台（windows）
2. 查看录像，必定会消失一个最长时间的

##### 具体表现[截图可能会更好些,最好能截全]
![微信截图_20200325192005](https://user-images.githubusercontent.com/34223881/77531382-c757ea00-6ecd-11ea-8bb9-7137ab8d4506.png)

##### 其他
有些用户用，鼠标估计是习惯了双击，在web终端界面同一台机器开了两个界面，结果同一时间的录像只保留了最短的那个。请问web终端界面可以屏蔽双击开两台的操作么？或者修改下同一时间录像文件，名字错开之类的，让其保留2个录像。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhangtyps 未复现，可以到demo环境尝试复现
demo.jumpserver.org

**Comment by zhangtyps** [comment]
> 
> 
> @zhangtyps 未复现，可以到demo环境尝试复现
> demo.jumpserver.org

测试环境都无法回放录像啊，此外demo里没有windows啊。
我用docker部署的，linux机器刚自行测试没什么问题，windows几乎可以完美复现。
![微信截图_20200325194024](https://user-images.githubusercontent.com/34223881/77532832-a218ab00-6ed0-11ea-96ab-740c3227ec33.png)

**Comment by wojiushixiaobai** [comment]
RDP协议，确实出现了此问题。之前没注意看以为是ssh协议，我反馈下

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
