### ISSUE TITLE
【求助】如图，我错在哪里？为啥sudo了别名还是要root密码？？

### ISSUE THREAD

**Issue by xiaoliu2012** [jumpserver/jumpserver#384]
![003](https://cloud.githubusercontent.com/assets/19356315/24538639/034f560e-161d-11e7-9621-4246359feb7b.png)
![004](https://cloud.githubusercontent.com/assets/19356315/24538640/037d88da-161d-11e7-88b0-8bd8c087d953.png)
![005](https://cloud.githubusercontent.com/assets/19356315/24538642/03acec24-161d-11e7-81bf-cb459c958187.png)

**Comment by coolbreezeqf** [comment]
sudo yum

**Comment by jiaxiangkong** [comment]
@xiaoliu2012 你没有理解    是以sudo 方式去执行命令   如sudo ifconfig   过程免输入root密码
