### ISSUE TITLE
API获取celery_task结果出错

### ISSUE THREAD

**Issue by 2120160893** [jumpserver/jumpserver#3843]
[简述你的问题]
调用"/ops/celery/task/{id}/result"接口获取task的执行结果时报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.5
##### 问题复现步骤
1. 调用“/assets/system-users/{id}/assets/{aid}/push/”接口，添加推送系统用户到资产任务。获取task_id
2. 调用"/ops/celery/task/{id}/result"接口获取任务的执行结果。

##### 具体表现[截图可能会更好些,最好能截全]
![问题截图](https://user-images.githubusercontent.com/22293578/77869458-35efcb80-7271-11ea-8cca-2c5e7d9b7b5b.JPG)

##### 其他
暂时的解决方案：
![image](https://user-images.githubusercontent.com/22293578/77869509-5ae43e80-7271-11ea-809d-2133c88d9ccb.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
