### ISSUE TITLE
/api/v1/settings/ldap/users/ 409 Conflict

### ISSUE THREAD

**Issue by SamPeng87** [jumpserver/jumpserver#3844]
响应
{"msg":"synchronization is running."}

##### 使用版本
最新1.5.7

##### 问题复现步骤
未知，刚装好，配错了ldap的地址，可能有路由回环，然后无论怎么操作都是这样。

##### 具体表现[截图可能会更好些,最好能截全]
点击ldap导入，一直转圈。抓包看synchronization is running

**Comment by wojiushixiaobai** [comment]
帮助文档有说明如何禁用
