### ISSUE TITLE
jumpserver安装完成后普通无法登录资产

### ISSUE THREAD

**Issue by cugxuetao** [jumpserver/jumpserver#3845]
[简述你的问题]
安装完成后无法登录资产

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.7注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 普通用户登录jumpserver
2. 点击Linux资产
3.报错，提示如图

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/796046/78001811-d379f680-7368-11ea-9ad8-3107c00f1cdf.png)
jumpserver和目标资产在同一网段，可以ping通

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@cugxuetao 进入部署koko的容器里或者服务器上，测试下是能否正常ping通。

**Comment by wojiushixiaobai** [comment]
@cugxuetao 如果动过防火墙和iptables的话，重启下docker。然后重启下容器即可
如果不是，检查下网络，也可以到koko容器里面ping下资产试试
