### ISSUE TITLE
新装完机器连报错

### ISSUE THREAD

**Issue by alvin6666** [jumpserver/jumpserver#3847]
[简述你的问题]
新装完堡垒机机器连报错
![image](https://user-images.githubusercontent.com/13924849/78214860-cc79f200-74e8-11ea-9f89-4c26b7ce19cb.png)

##### 使用版本
v1.5.7

##### 问题复现步骤
在web界面推送用户或者测试都是黑屏
![image](https://user-images.githubusercontent.com/13924849/78214908-e9162a00-74e8-11ea-8ea9-9a45062a6e48.png)

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/13924849/78215020-24185d80-74e9-11ea-8475-d7a5f28b57e4.png)

这个是看日志lim里面的截图，看都是OK的

##### 其他

[注:] 完成后请关闭 issue

**Comment by alvin6666** [comment]
![image](https://user-images.githubusercontent.com/13924849/78218271-19ad9200-74f0-11ea-9e31-50949afe9e20.png)
这个是我通过ssh工具连，然后日志报的错，

**Comment by alvin6666** [comment]
然后这边看koko容器里面日志有报错
![image](https://user-images.githubusercontent.com/13924849/78228901-d6f4b580-7501-11ea-83f0-1e6b92d71401.png)

**Comment by wojiushixiaobai** [comment]
@alvin6666 报错是因为无法推送，无法推送是因为任务系统celery出了问题，如果是全新安装的，请检查下nginx反向代理设置，你域名指向的那台nginx服务器，要把websocket的相关设置加上
```
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
```

**Comment by alvin6666** [comment]
这个都有正常配的，页面推送、测试都是黑屏，看日志
![image](https://user-images.githubusercontent.com/13924849/78236387-80d93f80-750c-11ea-8eae-631b4856c562.png)

**Comment by alvin6666** [comment]
之前用的1.5.6没有问题，然后今天换了新装1.5.7有这个问题，装了两次都同样的问题

**Comment by alvin6666** [comment]
@wojiushixiaobai 大哥操空帮忙瞅瞅

**Comment by wojiushixiaobai** [comment]
@alvin6666 加qq296015668过来
