### ISSUE TITLE
安装文档的一处错误

### ISSUE THREAD

**Issue by kaiixing** [jumpserver/jumpserver#3848]
[简述你的问题]
安装文档中第9节  正常安装并启动 guacamole 组件，里面创建目录
$ mkdir -p   /config/guacamole     /config/guacamole/extensions     /config/guacamole/record
$ chown daemon:daemon     /config/guacamole/record     /config/guacamole/drive

其中mkdir执行后应该是漏掉了   /config/guacamole/drive这个目录。所以执行下面那句chown的时候会提示没有那个文件或目录。

##### 使用版本
1.5.7

##### 问题复现步骤
1. mkdir -p /config/guacamole /config/guacamole/extensions /config/guacamole/record
2. chown daemon:daemon /config/guacamole/record /config/guacamole/drive

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/9694835/78231890-0f968e00-7506-11ea-8f4f-8b5dc6edf6b2.png)
![image](https://user-images.githubusercontent.com/9694835/78231939-1fae6d80-7506-11ea-91db-ae485fb4d02c.png)

**Comment by wojiushixiaobai** [comment]
@kaiixing 感谢反馈，已经修复
