### ISSUE TITLE
【建议】如图，这个Connected配色能否换个颜色？我一看红色以为是出错主机！

### ISSUE THREAD

**Issue by xiaoliu2012** [jumpserver/jumpserver#385]
![00000000000](https://cloud.githubusercontent.com/assets/19356315/24538685/4c8d90ec-161d-11e7-818e-693d369fa143.png)

**Comment by coolbreezeqf** [comment]
这个可以自己修改啊.

**Comment by ibuler** [comment]
外观问题自己可以修改
