### ISSUE TITLE
microphone 不可用

### ISSUE THREAD

**Issue by shihyulee** [jumpserver/jumpserver#3851]
連接 windows 時無法抓取 microphone
但 guacamole 有針對 rdp 的 parameter: enable-audio-input (default: false)
(https://guacamole.apache.org/doc/gug/configuring-guacamole.html#rdp)
如何在 jumpserver 使用 microphone ?

##### 使用版本
1.5.7

**Comment by wojiushixiaobai** [comment]
暂时不支持设备重定向。
