### ISSUE TITLE
关于jumpserver的windows远程桌面全屏

### ISSUE THREAD

**Issue by zhuyh1986** [jumpserver/jumpserver#3852]
[简述你的问题]
选择分辨率为auto，最大化后，分辨率没有自适应变化，只是把画面按当前分辨率拉大，造成画面模糊。

##### 使用版本
[Version 1.5.6-2 GPLv2]

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
