### ISSUE TITLE
会话标识未更新

### ISSUE THREAD

**Issue by peicheng-chen** [jumpserver/jumpserver#3853]
Web 应用程序编程或配置不安全
测试请求和响应：
POST /auth/login/?next=/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.10.22/auth/login/?next=/
Cookie: csrftoken=88qqg3kJJbngxQtTnbaWrh8cqX5fz2iMvoci58UxmsSRO5KaDM2FlsCI7seq5UDi; sessionid=csl2oqgvfvtwoogd4qqxx5dvawq8upyp
Connection: Keep-Alive
Host: 192.168.10.22
Pragma: no-cache
Content-Length: 114
Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, */*
Accept-Language: zh-CN
Content-Type: application/x-www-form-urlencoded

csrfmiddlewaretoken=7npfiVDyUi4bdSI2dpavRAGSecbsL4FluDb770dmxzzMu7Zjt02eLLaoVHkDhW0R&username**CONFIDENTIAL 1**&password**CONFIDENTIAL 1**

HTTP/1.1 302 Found
Content-Length: 0
Location: /auth/login/guard/?next=/
Content-Language: zh-hans
Server: Tengine
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
Set-Cookie: sessionid=csl2oqgvfvtwoogd4qqxx5dvawq8upyp; HttpOnly; Path=/; SameSite=Lax
X-Content-Type-Options: nosniff
Expires: Sun, 05 Apr 2020 17:42:13 GMT
X-XSS-Protection: 1; mode=block
Connection: keep-alive
Vary: Accept-Language, Cookie
Date: Sun, 05 Apr 2020 17:42:13 GMT
Content-Type: text/html; charset=utf-8
Cache-Control: max-age=0, no-cache, no-store, must-revalidate

GET /auth/login/guard/?next=/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.10.22/auth/login/?next=/
Cookie: csrftoken=88qqg3kJJbngxQtTnbaWrh8cqX5fz2iMvoci58UxmsSRO5KaDM2FlsCI7seq5UDi; sessionid=csl2oqgvfvtwoogd4qqxx5dvawq8upyp
Connection: Keep-Alive
Host: 192.168.10.22
Pragma: no-cache
Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, */*
Accept-Language: zh-CN

HTTP/1.1 302 Found
Content-Length: 0
Location: /auth/login/otp/
Content-Language: en
Server: Tengine
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Connection: keep-alive
Vary: Accept-Language, Cookie
Date: Sun, 05 Apr 2020 17:35:42 GMT
Content-Type: text/html; charset=utf-8

GET /auth/login/otp/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Referer: http://192.168.10.22/auth/login/guard/?next=/
Cookie: sessionid=csl2oqgvfvtwoogd4qqxx5dvawq8upyp; csrftoken=88qqg3kJJbngxQtTnbaWrh8cqX5fz2iMvoci58UxmsSRO5KaDM2FlsCI7seq5UDi
Connection: Keep-Alive
Host: 192.168.10.22
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US

HTTP/1.1 200 OK
Content-Length: 3048
Content-Language: zh-hans
Server: Tengine
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
Set-Cookie: csrftoken=88qqg3kJJbngxQtTnbaWrh8cqX5fz2iMvoci58UxmsSRO5KaDM2FlsCI7seq5UDi; expires=Sun, 04 Apr 2021 17:42:13 GMT; Max-Age=31449600; Path=/; SameSite=Lax
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Connection: keep-alive
Vary: Accept-Encoding
Vary: Cookie, Accept-Language
Date: Sun, 05 Apr 2020 17:42:13 GMT
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/static/img/facio.ico" type="image/x-icon">
    <title></title>

    

<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/font-awesome.min.css" rel="stylesheet">
<link href="/static/css/plugins/toastr/toastr.min.css" rel="stylesheet">
<link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">
<link href="/static/css/plugins/vaildator/jquery.validator.css" rel="stylesheet">
<link href="/static/css/plugins/datatables/datatables.min.css" rel="stylesheet">

<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/plugins/datatables/datatables.min.js"></script>
<link href="/static/css/plugins/select2/select2.min.css" rel="stylesheet">

    <link href="/static/css/jumpserver.css" rel="stylesheet">
    <script type="text/javascript" src="/zh-hans/jsi18n/"></script>
    <script src="/static/js/jumpserver.js"></script>
    <style>
        .passwordBox {
            max-width: 560px;
            margin: 0 auto;
            padding: 100px 20px 20px 20px;
        }
    </style>
     
</head>

<body class="gray-bg">
    <div class="passwordBox animated fadeInDown">
        <div class="row">
            <div class="col-md-12">
                <div class="ibox-content">
                    <img src="/static/img/logo.png" style="margin: auto" width="50" height="50">
                    <h2 class="font-bold" style="display: inline">
    多因子认证
</h2>
                    <h1></h1>
                    
    <form cla
...
...
...

**Comment by ibuler** [comment]
明文传送密码了？好多网站现在都还是这样的，安全依赖https来解决

**Comment by peicheng-chen** [comment]
密码没有明文

> 明文传送密码了？好多网站现在都还是这样的，安全依赖https来解决
