### ISSUE TITLE
浏览器登录后频繁提示重新登录

### ISSUE THREAD

**Issue by chestarss** [jumpserver/jumpserver#3854]
[简述你的问题]

##### 使用版本
Version 1.5.6-2 GPLv2
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]登录，点击页面的其他链接，时不时会跳到登录页面
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chestarss 多组件部署，注意session的问题，如果是单节点，请检查nginx的设置

**Comment by wojiushixiaobai** [comment]
@chestarss 多组件部署，注意session的问题，如果是单节点，请检查nginx的设置
