### ISSUE TITLE
移动资产到节点后资产会默认添加一个Default节点

### ISSUE THREAD

**Issue by wanglong668** [jumpserver/jumpserver#3856]
[简述你的问题]

##### 使用版本
[Version 1.5.7-2]

##### 问题复现步骤
调整资产树时使用了移动资产到目标节点，移动完后，在资产授权列表的Default节点下出现了移动后的机器列表，排查后发现移动后的机器都会默认给资产加一个Default节点

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
