### ISSUE TITLE
创建系统用户使用“自动生成密钥”后，怎么使用sudo命令？

### ISSUE THREAD

**Issue by N-lucky** [jumpserver/jumpserver#3858]
[简述你的问题]
如果创建系统用户的时候，在认证--选择“自动生成密钥”，那普通用户使用sudo命令的时候需要输入“普通用户”的密码才能执行命令，可密码应该输入什么呢？

虽然可以使用“NOPASSWD”参数，执行sudo命令不需要输入用户密码，可很多时候总是需要普通用户的密码执行一些命令（如其他主机使用scp传输文件到本机）。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

1.5.7-2 GPLv2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
系统用户sudo处，加入需要授权的命令。临时使用可以临时授权

**Comment by N-lucky** [comment]
> 系统用户sudo处，加入需要授权的命令。临时使用可以临时授权

感谢，获得一种新思路。
