### ISSUE TITLE
收到 “磁盘使用率超过 80%: /snap/core/8689 => 100.0” 这样的报警邮件

### ISSUE THREAD

**Issue by zhongyiio** [jumpserver/jumpserver#3859]
[简述你的问题]
升级到 1.5.7 后，总是收到 “磁盘使用率超过 80%: /snap/core/8689 => 100.0” 这样的报警邮件，想知道怎么禁用？（/snap/core 是 aws ec2 默认的磁盘，不用报警。）

##### 使用版本
1.5.7

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/10026361/78645233-c79eaf00-78e9-11ea-8092-37c4a2737ca8.png)

**Comment by zhongyiio** [comment]
```
--- a/apps/ops/tasks.py
+++ b/apps/ops/tasks.py
@@ -107,7 +107,7 @@ def create_or_update_registered_periodic_tasks():
 @register_as_period_task(interval=3600)
 def check_server_performance_period():
     usages = get_disk_usage()
-    uncheck_paths = ['/etc', '/boot']
+    uncheck_paths = ['/etc', '/boot', '/snap']

     for path, usage in usages.items():
         need_check = True
```
现在的想法是在这里加上 /snap。

**Comment by ibuler** [comment]
可以，每个公司磁盘可能不太一样，无法完全满足，将来排除项放到 配置文件中
