### ISSUE TITLE
批量命令执行咨询

### ISSUE THREAD

**Issue by sunsky-cn** [jumpserver/jumpserver#3862]
请问为什么现在版本的批量命令执行不能支持统配或正则匹配，甚至都不支持搜索功能啊，机器多的批量执行相当不方便，后续会考虑类似功能吗？谢谢！

**Comment by ibuler** [comment]
后续会考虑的

**Comment by sunsky-cn** [comment]
> 后续会考虑的

非常期待，谢谢！
