### ISSUE TITLE
使用ldap是能关闭email map吗

### ISSUE THREAD

**Issue by CN-JV-SunseaIoT** [jumpserver/jumpserver#3863]
[简述你的问题]
jp在使用ldap时，是否一定要map user、username和email这三项，能否通过配置来自定义？

##### 使用版本
1.5.7
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，因为这些字段数据库里是必填项
