### ISSUE TITLE
对接openLDAP

### ISSUE THREAD

**Issue by hejiazhen1203** [jumpserver/jumpserver#3866]
##### 使用版本
1.5.7

##### 问题复现步骤
1. 配置好ldap设置后,使用的openLDAP
2. 使用其中一个ldap用户登录，这个时候能正常登录，且用户管理页面已经能查看到该ldap用户，授权也正常，然后注销登录再次登录该账号就一直登录不了了，前端报错：
Server error occur, contact administrator
![image](https://user-images.githubusercontent.com/22071818/78864532-5e947400-7a6e-11ea-8b40-a26c6236c713.png)
查看core的日志如下：
django.db.utils.IntegrityError: (1062, "Duplicate entry ' test3' for key 'username'")
![image](https://user-images.githubusercontent.com/22071818/78864567-6fdd8080-7a6e-11ea-815a-857cb16f4c39.png)

**Comment by hejiazhen1203** [comment]
管理员删掉该账号后可正常登录，也就是只能登录一次

**Comment by zhengwh2010** [comment]
我也碰到了该问题，仔细查了下ldap用户信息之后发现，名称和用户名获取的数据 是反的。
既ldap配置页面的LDAP属性映射中默认是
{"username": "cn", "name": "sn", "email": "mail"}
我修改成
{"username": "sn", "name": "cn", "email": "mail"}
就是 cn和sn的位置换一下，就可以了

**Comment by hejiazhen1203** [comment]
通过@zhengwh2010的回复已解决：
{"username": "cn", "name": "sn", "email": "mail"}修改成{"username": "sn", "name": "cn", "email": "mail"}
