### ISSUE TITLE
【建议】如图，帮助既然点上去没啥东西还放在banner上干吗？右侧边栏又不是经常用到，为何不整合到“设置”中？

### ISSUE THREAD

**Issue by xiaoliu2012** [jumpserver/jumpserver#387]
![00000000000](https://cloud.githubusercontent.com/assets/19356315/24538859/3b5aa1d8-161e-11e7-9039-3e94d6d40c13.png)
如题，帮助既然点上去没啥东西还放在banner上干吗？右侧边栏又不是经常用到，为何不整合到“设置”中？

**Comment by ibuler** [comment]
新版本已经干掉
