### ISSUE TITLE
删除对系统用户的资产授权之后，如何删除之前在资产上创建出来的账户呢？

### ISSUE THREAD

**Issue by guolvting4u** [jumpserver/jumpserver#3870]
[简述你的问题]
对系统用户进行资产授权时，会在授权的资产上自动创建出系统账户。但是当我撤销对资产的授权后，之前在系统上创建的账户依然存在。如果想做到关联删除，应该如何操作？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
目前还不自动删除在资产上的账户，因为不太安全，比较服务器在运行中，有可能该系统用户运行着服务，需要用户自行删除
