### ISSUE TITLE
管理用户的作用

### ISSUE THREAD

**Issue by zzzxx** [jumpserver/jumpserver#3873]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.7-2 GPLv2.

##### 问题复现步骤
我想咨询一下这个管理用户的作用是什么，为什么我这里是瞎的一个管理的用户和密码，
为什么在WEB终端也能够练到资产服务器上？
系统用户写的是资产上正确的账号和密码

##### 具体表现[截图可能会更好些,最好能截全]

![图片](https://user-images.githubusercontent.com/22747106/78975218-38420780-7b46-11ea-8930-9a74e073de55.png)
![图片](https://user-images.githubusercontent.com/22747106/78975329-73dcd180-7b46-11ea-9172-7fd5580d5eb1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
jumpserver使用管理用户对资产进行检活，推送系统用户。
用户登录资产，使用系统用户。


管理用户被用来维护资产，被ansible调用。
系统用户被用来登录资产，被使用jumpserver的用户使用。
