### ISSUE TITLE
资产连接性问题

### ISSUE THREAD

**Issue by hifer** [jumpserver/jumpserver#3874]
[简述你的问题]

##### 使用版本
1.5.7

##### 具体表现[截图可能会更好些,最好能截全]
连接测试没问题
![image](https://user-images.githubusercontent.com/16734310/78978598-a5f13200-7b4c-11ea-8d7d-688dabfc4f6d.png)
通过后台ssh也没问题，但是这里一直显示黄点
![image](https://user-images.githubusercontent.com/16734310/78978656-c7521e00-7b4c-11ea-8569-21e6bcdc6f6b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@hifer 不影响使用，之后的版本修复

**Comment by hifer** [comment]
> @hifer 不影响使用，之后的版本修复

好的，多谢！
