### ISSUE TITLE
添加用户后资产列表里看不到新密码

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3875]
[简述你的问题]
1、我在系统用户里更新系统用户密码，并手动推送后资产密码没有改变
2、我将系统用户删除重新添加，并手动推送更改资产密码之后在系统用户里点击用户名再点击资产列表看到密码不会更新成最新密码

##### 使用版本
1.5.7

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
系统用户配置的密码是默认密码，如果为系统用户单独在某个资产上设置过密码，那么这个密码会存储到 authbook这张表中，字段如下：

ID    用户名     资产ID    密码
1      web          {UUID}   xxxx

如果你的系统用户的用户名 为 web, 那么去获取 web 在资产 {UUID} 上的密码，永远获取的是上述authbook中的设置
