### ISSUE TITLE
ssh终端登录资产显示问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3876]
[简述你的问题]
通过ssh终端登录jumpserver，在欢迎界面输入g ID显示对应的节点资产，然后输入h返回欢迎界面，再通过回车显示的不是全部资产，而是刚才的g ID节点的资产，这是正常现象吗

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
按p来重置，回车代表的意义有些多
