### ISSUE TITLE
咨询： 如何给jms加一层路径，以方便nginx反代配置

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#3877]
[简述你的问题]
前端想使用nginx对jumps做反向代理，如何给jms加入一层路径**jumpserver**/。比如将访问jms的路径变成http://xxxxxxxx/jumpserver/.....

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@jackwang-github 你可以尝试rewrite，但是工作量稍大。具体可以参考nginx的官方文档

**Comment by ibuler** [comment]
FORCE_SCRIPT_NAME 这个参数可以设置，可以查询一下 Django FORCE_SCRIPT_NAME, 编辑config.yml可以设置
