### ISSUE TITLE
咨询Jumpserver安装好以后再改IP，访问window资产黑屏

### ISSUE THREAD

**Issue by huabuxiang** [jumpserver/jumpserver#3878]
[简述你的问题]
Jumpserver安装好以后更改Jumpserver的IP地址，如果是更改内网IP访问windows资产黑屏，更改外网IP访问正常

还有就是如果直接用外网IP安装好以后，再切换到内网中，能远程访问window资产，但远程连接很慢很慢，基本不能操作，跟在外面中使用远程访问windows资产速度不好比

目前的情况事，Jumpserver能访问互联网的话，访问Windows资产正常，一旦Jumpserver不能访问互联网了，访问windows资产就出现问题，或者黑屏，或者连接很慢，基本不能远程操作
##### 使用版本
[使用的Jumpserver版本 1.5.7]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

#3877 

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@huabuxiang 在纯离线环境验证了下，没发现你说的问题。
jumpserver部署完成后不需要再访问外网，切换ip导致资产无法连接是因为容器里面使用了宿主的ip，ip变了，自然组件无法连接上资产，ip变更后，需要把容器删掉重新运行即可。

**Comment by huabuxiang** [comment]
还有个问题，是我IP没变，只是切换了内外网，但切换到内网后windows资产连接很慢，基本无法操作，内外网的jumpserver的IP是同一个，只是切换了网络，在外网访问同一网段的机器速度很快，但切换到内网后，访问同一网段的IP基本不行

**Comment by huabuxiang** [comment]
![image](https://user-images.githubusercontent.com/51272154/79086828-0dd39280-7d70-11ea-9983-b5a5b3d0d91e.png)
连接时候是这样的，很慢

**Comment by huabuxiang** [comment]
但部署在外网就正常

**Comment by wojiushixiaobai** [comment]
@huabuxiang 你这样的回答我很难帮助到你，你应该给我具体的日志，如果方便的话让我远程看下，我qq296015668，请自备teamviewer

**Comment by ibuler** [comment]
1. 网络慢
2. nginx没有开启websocket

**Comment by wojiushixiaobai** [comment]
@ibuler 已经检查过，用户自身的网络的问题，同网段的资产连接jumpserver无异常。其他网段的资产连接jumpserver异常。用户自行解决

**Comment by yubug** [comment]
> @huabuxiang 在纯离线环境验证了下，没发现你说的问题。
> jumpserver部署完成后不需要再访问外网，切换ip导致资产无法连接是因为容器里面使用了宿主的ip，ip变了，自然组件无法连接上资产，ip变更后，需要把容器删掉重新运行即可。

我也是一样的问题，修改宿主IP之后连资产黑屏，请问怎样删掉重新运行？改过IP之后是不能连互联网的，需要重新下载吗？
