### ISSUE TITLE
>>> /tmp/TPv5gsg: syntax error near line 32 <<< parse error in /tmp/TPv5gsg near line 32

### ISSUE THREAD

**Issue by benq1211** [jumpserver/jumpserver#388]
推送用户到新机器的时候提示：
>>> /tmp/TPv5gsg: syntax error near line 32 <<< parse error in /tmp/TPv5gsg near line 32

**Comment by ibuler** [comment]
或许是sudo有问题，请去客户机查看 这个文件，确认sudo有没有问题
