### ISSUE TITLE
jumpserver 任务监控打开报错

### ISSUE THREAD

**Issue by zhihaoding** [jumpserver/jumpserver#3880]
[简述你的问题]
点击任务监控 报错404

Request Method: | GET
-- | --
http://jumpserverUrl/storePDStorage/?confirm=Continue%2CI+accept+this+risk.%2F%E7%BB%A7%E7%BB%AD%2C%E6%88%91%E6%8E%A5%E5%8F%97%E6%AD%A4%E9%A3%8E%E9%99%A9.

Using the URLconf defined in jumpserver.urls, Django tried these URL patterns, in this order:

[name='index']
api/v1/
api/v2/
api/(?P<app>\w+)/(?P<version>v\d)/.*
api/health/ [name='health']
luna/.* [name='luna-view']
koko/.* [name='koko-view']
ws/.* [name='ws-view']
i18n/<str:lang>/ [name='i18n-switch']
settings/
captcha/
users/
assets/
perms/
terminal/
ops/
audits/
orgs/
auth/
applications/
tickets/
flower/(?P<path>.*) [name='flower-view']
^media\/(?P<path>.*)$
^static\/(?P<path>.*)$
zh-hans/
^swagger(?P<format>\.json|\.yaml)$ [name='schema-json']
docs/ [name='docs']
redoc/ [name='redoc']
^v2/swagger(?P<format>\.json|\.yaml)$ [name='schema-json']
docs/v2/ [name='docs']
redoc/v2/ [name='redoc']
The current path, storePDStorage/, didn't match any of these.

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
没有这个地址啊，正常地址应该是  http://URL/flower/

**Comment by zhihaoding** [comment]
> 没有这个地址啊，正常地址应该是 http://URL/flower/

看了一下，nginx配置中没有为 /flower/配置路由，实际上点任务监控访问的是URL:5555
