### ISSUE TITLE
极速安装脚本逻辑建议

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#3887]
[简述你的问题]
极速安装脚本依赖于本地/etc/yum.repos.d/* ，若仓库没有对应的软件包则会提示错误。但还会执行下一步的命令没有退出。
jmsctl.sh 开头加上set -e ，这样每个命令执行完成后，会验证是否为0。从而到达失败即停止

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7
##### 问题复现步骤
1. [步骤1]

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28751302/79133679-00092600-7ddf-11ea-99a7-4d8260843f0b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chinazzb emmm，网络正常的情况下都可以正常部署完成，不是不能做很多判断，里面已经写了n多判断，每次我自己看都有点晕，脚本会继续优化。

目前的逻辑确实存在些问题，但是不影响实际使用
后面准备改成
安装-->判断各个组件安装是否完成---启动各个组件---判断各个组件启动是否完成

当前是直接安装然后启动---判断组件这样

**Comment by chinazzb** [comment]
我又尝试了，发现是网络不稳定造成yum install SOFTARE 失败，从而导致安装失败。
