### ISSUE TITLE
1.5.7版本win10 win2012 rdp 提示“连接错误”

### ISSUE THREAD

**Issue by beanliang** [jumpserver/jumpserver#3888]
[简述你的问题]
ping 和telnet 3389 win10和win2012都是通的，同时测试过用其他设备rdp win10 win2012可以正常访问，但用jumpserver rdp 提示“连接错误-----无法连接服务器，请联系管理员或查看日志。”,求解。

##### 使用版本
[请提供你使用的Jumpserver版本Version 1.5.7-101 GPLv2.]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/33873441/79140973-7875e400-7deb-11ea-8307-c730fef40114.png)

![image](https://user-images.githubusercontent.com/33873441/79142531-3bf7b780-7dee-11ea-9234-6ab88f29188f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
查看一下后端日志

**Comment by N-lucky** [comment]
之前俺遇到过，重新注册koko和guacamole就好了。

https://jumpserver.readthedocs.io/zh/master/faq_koko.html

https://jumpserver.readthedocs.io/zh/master/faq_guacamole.html
