### ISSUE TITLE
连接linux服务器会出现验证无法通过

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#3895]
[简述你的问题]

有一台无法正常连接(以下称为A服务器)，连接linux服务器会出现以下提示。
Connect asset project-jenkins error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain

对比能正常连接的服务器，发现audit日志没有指定导致grantors 和acct 。导致无法连接

1、查看A服务器passwd，内没有正常创建对应账户
2、通过wireshark抓取http协议put /api/v1/assets/admin-users/，传入后台的密码正确。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7-2
##### 问题复现步骤
1. [步骤1]
通过csv模板添加批量资产。
2. [步骤2]
通过csv模板添加系统用户。
3.[步骤3]
开始测试资产是否能正常连接。

##### 具体表现[截图可能会更好些,最好能截全]
图1 A服务器
![image](https://user-images.githubusercontent.com/28751302/79209267-c0d9e400-7e75-11ea-9665-d6669e0090a3.png)
图2 能连接的主机
![image](https://user-images.githubusercontent.com/28751302/79209315-d0592d00-7e75-11ea-9497-227fb3785de0.png)

##### 其他
通过删除A资产，再次添加A资产。对应用户已创建，并且能正常连接

[注:] 完成后请关闭 issue

**Comment by Forget-C** [comment]
hi 我也遇到了这个问题。 我的用户是正常创建的。 请问您发现解决方法了吗？

**Comment by chinazzb** [comment]
> hi 我也遇到了这个问题。 我的用户是正常创建的。 请问您发现解决方法了吗？

把资产删除了，然后再重新创建新的。多尝试几次链接就成功了

**Comment by Forget-C** [comment]
> > hi 我也遇到了这个问题。 我的用户是正常创建的。 请问您发现解决方法了吗？
> 
> 把资产删除了，然后再重新创建新的。多尝试几次链接就成功了

这个确实可以，但是资产太多了，都删除重新加不现实。  ～～～   您有发现其他的方法吗

**Comment by Forget-C** [comment]
@ibuler  大佬帮忙看一下这个问题吧

**Comment by chinazzb** [comment]
> > > hi 我也遇到了这个问题。 我的用户是正常创建的。 请问您发现解决方法了吗？
> > 
> > 
> > 把资产删除了，然后再重新创建新的。多尝试几次链接就成功了
> 
> 这个确实可以，但是资产太多了，都删除重新加不现实。 ～～～ 您有发现其他的方法吗

在不考虑官方修复的情况下，可以通过模板添加进去。(ps，模板添加无法直接添加管理用户，需要将管理用户列的UUID填上)
