### ISSUE TITLE
【求助】系统用户密码推送失败 Version 0.3.2

### ISSUE THREAD

**Issue by oc-oc** [jumpserver/jumpserver#390]
您好，请教您一个问题:

[授权管理] -->[系统用户] -->[添加系统用户]-->用户密码 

这里的用户密码是指的什么密码?

个人理解是系统用户在终端上的一个密码，及username、password这样对应的一个密码。

目前我遇到的情况是推送ok，也在终端上生成了用户，但是用户的密码是空的(通过查看/etc/shadow得知)，因而在登录的时候无法连接成功，服务器上的日志如下:
Apr  2 09:22:23 web1  sshd[17326]: User testuser not allowed because account is locked
Apr  2 09:22:23 web1  sshd[17326]: input_userauth_request: invalid user testuser [preauth]
Apr  2 09:22:23 web1  sshd[17326]: Connection closed by 192.168.80.100 [preauth]

临时解决办法是在终端机器上passwd testuser,为testuser设置一个密码就可以连接上了。

我的终端版本是centos7 64bit。

麻烦告知下，要如何才能让推送的密码不为空呢?

**Comment by ibuler** [comment]
默认是推送的秘钥

**Comment by oc-oc** [comment]
恩，其实推送密钥是没错的，安全性更高，我们在这之前也是使用密钥登录。
但是用户密码为空的话，就没办法登录，除非更改ssh安全配置，这个有另外的办法么?

**Comment by ibuler** [comment]
默认不允许秘钥登陆？

**Comment by oc-oc** [comment]
我们默认就是用私钥登录，不允许密码登录，但使用推送过去的系统账号登录时，系统安全日志里面，就会提示账号locked，只有使用管理账号登录进去之后，用passwd修改下系统账号的密码，就可以连接了。
不太明白是不是因为我ssh配置的问题。

**Comment by oc-oc** [comment]
我们的ssh配置里面有这样一个配置：
UsePAM no
把这个改为UsePAM yes就没有问题了。

**Comment by EverCurse** [comment]
请问最后怎么解决的呢 我也遇到这个问题 docker 安装的0.3.2
