### ISSUE TITLE
服务器账号

### ISSUE THREAD

**Issue by zzzxx** [jumpserver/jumpserver#3901]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.7-2 GPLv2.
##### 问题复现步骤
我想咨询你们是否建议在每个资产上创建都一个同一的账号， 即作为管理用户，又作为系统用户？

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
这个根据自己的需求设置即可。
一般情况下，我们不建议这样操作。

管理用户是给jumpserver的ansbile使用
系统用户是给使用jumpserver的开发或者测试人员使用

两者的用途不同，权限也不同。不应该混在一起使用。
