### ISSUE TITLE
Web登陆权限和Token登陆权限不一致，是否可以在API中指定组织？

### ISSUE THREAD

**Issue by fox2zz** [jumpserver/jumpserver#3903]
[简述你的问题]
添加组织及组织管理员后，组织管理员通过token方式登陆，访问资产接口或者用户接口，显示没有权限，而通过web方式在api docs中可以正常获取。推测是token登陆后默认为default组织，是否可以在api中指定组织？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7-2

##### 问题复现步骤
1. [步骤1]
添加组织及组织管理员
2. [步骤2]
组织管理员用token方式登陆，获取资产或者用户信息

##### 具体表现[截图可能会更好些,最好能截全]
{"detail":"您没有执行该操作的权限。"}

##### 其他
主要是想结合AWX做一些自动化的管理

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
