### ISSUE TITLE
是否不能直接在已存在的系统用户里设置新密码然后推送以修改资产密码

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3905]
[简述你的问题]
修改jumpserver上已存在的系统用户密码并推送新密码到资产，资产密码没有修改成功

##### 使用版本
1.5.7

##### 问题复现步骤
1. 更新已存在系统用户的密码，然后手动推送新密码到资产，并且任务也自动执行过，手动也执行过任务，
2. 不经过jumpserver用新密码登录资产失败，用老密码登录成功
3.删除已存在的系统用户重新添加，然后密码到资产，然后不经过jumpserver用新密码可以登录资产
4.是否不能直接在已存在的系统用户里设置新密码然后推送。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
