### ISSUE TITLE
通过ssh登录windows的文件管理显示文件不全

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3906]
[简述你的问题]
问题1：通过ssh登录windows的文件管理显示文件不全,如下面截图没显示网站虚拟机文件夹
问题2：在widnows的文件管理里的搜索功能搜索不到存在的英文文件或者中文文件
##### 使用版本
1.5.7
##### 问题复现步骤
1. 通过ssh登录到windows 2016的文件管理界面,有些文件夹没有显示

##### 具体表现[截图可能会更好些,最好能截全]
文件夹显示不全截图，没显示网站虚拟机文件夹
<img width="185" alt="图片1" src="https://user-images.githubusercontent.com/44529247/79443641-ab4af280-800c-11ea-86b4-833310dbe7f8.png">
<img width="170" alt="图片2" src="https://user-images.githubusercontent.com/44529247/79443645-adad4c80-800c-11ea-843e-e6baa51eb12b.png">
<img width="374" alt="图片3" src="https://user-images.githubusercontent.com/44529247/79443647-ae45e300-800c-11ea-84a9-1ecaa960e1de.png">

文件无法搜索截图：
<img width="908" alt="图片4" src="https://user-images.githubusercontent.com/44529247/79443692-bdc52c00-800c-11ea-9dfc-128c3dab496d.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
隐藏文档需要单独在koko里面设置
