### ISSUE TITLE
在线会话监控建议和显示中断资产连接的管理员名称

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#3909]
[简述你的问题]
建议1：在线会话监控界面显示正在操作的系统用户名，资产名称，登录时间，和中断操作按钮，在看到危险操作可以及时中断，要不然点开监控之后过一会就不知道是点的哪个会话的监控了
建议2：在资产端显示是哪个管理员中止的操作，在多个管理员的情况下，不知道是谁中止了资产连接，而且没有中止资产连接的日志信息，如果在重要操作的时候被中止，导致故障不好追责
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
v2.15版本已增加相关功能。
