### ISSUE TITLE
【求助】资产信息更新不准确 Version 0.3.2 GPL

### ISSUE THREAD

**Issue by oc-oc** [jumpserver/jumpserver#391]
使用资产信息的自动更新功能，发现得到的硬盘大小比实际大了很多倍。

在资产列表中，我的硬盘大小显示为17904G，点击编辑项，硬盘表单数据为:

{u'sdd': 744.62, u'sde': 5820.0, u'sdf': 5820.0, u'sdg': 59.63, u'sda': 1820.0, u'sdb': 1820.0, u'sdc': 1820.0}

其中，sde，sdf 这2块硬盘获取的数据是错误的，实际的大小应为:
sde      8:64   0 744.6G  0 disk 
sdf      8:80   0 744.6G  0 disk 

也就是说，这2块硬盘大小为744.6G，但不知为何获取大小为5820G，比实际大小多了这么多。

**Comment by ibuler** [comment]
ansible取的对吗？还是计算出问题了

**Comment by oc-oc** [comment]
抱歉，我python比较烂。我尝试跟踪了下，在jasset->asset_api.py->asset_ansible_update()函数里面
asset_info = get_ansible_asset_info(asset.ip, setup_info)
 print asset_info

这时候取到的asset_info就已经是错误的数值了。

**Comment by jettying** [comment]
![image](https://cloud.githubusercontent.com/assets/24908599/24999864/c1c45054-2071-11e7-8acf-6e7270b0f25d.png)
![image](https://cloud.githubusercontent.com/assets/24908599/24999909/ee783728-2071-11e7-984f-3d1435752d27.png)

实际硬盘大小不到1T，资产信息显示7280g。

**Comment by ibuler** [comment]
新版本fixed
