### ISSUE TITLE
创建系统用户这步是干嘛的，有机器/etc/sudoers文件被改，导致不能使用sudo

### ISSUE THREAD

**Issue by alvin6666** [jumpserver/jumpserver#3912]
[简述你的问题]
创建系统用户这步是干嘛的，修改/etc/sudoers文件？

##### 使用版本
【1.5.6】

##### 问题复现步骤
1. 创建系统用户这步是干嘛的，修改/etc/sudoers文件？

2.有机器/etc/sudoers文件被改，导致不能使用sudo

##### 其他
![image](https://user-images.githubusercontent.com/13924849/79544183-2f5eb200-80c1-11ea-8701-4898d1cbeee7.png)

![image](https://user-images.githubusercontent.com/13924849/79544662-f07d2c00-80c1-11ea-82bd-feb26bb6af68.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
开启推送的情况下会推送系统用户到资产
