### ISSUE TITLE
网域机器上的 ssh 连接关闭会话后进程未释放

### ISSUE THREAD

**Issue by dbarobin** [jumpserver/jumpserver#3913]
[简述你的问题]
1.5.6 版本关闭使用网域连接目标机器的 luna 会话后，网域机器上的 ssh 连接进程未释放，用久后很多 ssh 连接进程

##### 使用版本
1.5.6

##### 问题复现步骤
1. luna 连接有使用网域的机器目标机器
2. 网域机器上查看 ssh 进程，ps -ef | grep sshd | grep -v grep

##### 具体表现[截图可能会更好些,最好能截全]

关闭 luna 上的会话后查看网域机器上查看 ssh 进程依然存在

![image](https://user-images.githubusercontent.com/3949252/79546236-a9446a80-80c4-11ea-8066-73ebb8bd7602.png)

##### 其他

跟这个 issue 类似，不过版本不一样，https://github.com/jumpserver/jumpserver/issues/3202

[注:] 完成后请关闭 issue

**Comment by dbarobin** [comment]
升级到 1.5.8 仍未解决。

**Comment by ggxp2008** [comment]
我1.5.2 jumpserver没这个问题。

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然存在此问题，感谢反馈
