### ISSUE TITLE
jumpserver使用私钥的问题

### ISSUE THREAD

**Issue by wangzhuolong** [jumpserver/jumpserver#392]
没用 jumpserver之前服务器已经设置好账号密码。 后来用jumpserver进行管理。 系统用户  设置的是之前存在的账号与相应密码。 默认管理用户  用的为一个不存在的用户（1234）。推送系统用户，虽然显示失败但是授权之后用户可以连接被管理的服务器。

现在想用秘钥登陆，自己生成秘钥，公钥丢到被管理的服务器，私钥贴到系统用户上，推送---->授权，用户无法连接被管理的服务器。   但是跳过jumpserver直接用  putty 私钥登陆是可以的。

求助问题原因所在。谢谢大家

**Comment by ibuler** [comment]
新版本支持了
