### ISSUE TITLE
JumpServer的RDP连接可否设置禁用复制粘贴？

### ISSUE THREAD

**Issue by playhere** [jumpserver/jumpserver#3923]
目前发现RDP只能设置是否具备文件上传下载权限，没发现设置是否允许复制粘贴的权限。

##### 使用版本
Version 1.5.7-2 GPLv2

##### 问题复现步骤
新建了一个账号，禁用了文件上传下载功能，但是发现复制文本还可用。
期望：可以配置当前用户是否可以使用剪贴板从堡垒机内复制出内容，或者粘贴进内容。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@playhere 参考下https://guacamole.apache.org/doc/gug/configuring-guacamole.html

**Comment by playhere** [comment]
> @playhere 参考下https://guacamole.apache.org/doc/gug/configuring-guacamole.html

能否具体一点，内容看不出来和禁用复制粘贴有什么关系。

**Comment by wojiushixiaobai** [comment]
@playhere guacamole 并发由 jumpserver 团队开发的组件，我们只是写了个 api 调用 guacamole ，所以功能的控制方面，参考 guacamole 的官方文档即可

**Comment by playhere** [comment]
> @playhere guacamole 并不是由 jumpserver 团队开发的组件，我们只是写了个 api 调用 guacamole ，所以功能的控制方面，参考 guacamole 的官方文档即可

感谢，能帮忙告诉下在哪里改guacamole的配置吗，我找到了“disable-copy","disable-paste”这2个参数，但不知道在哪里配置。

**Comment by wojiushixiaobai** [comment]
@playhere

**Comment by playhere** [comment]
> @playhere 可以参考
> guacamole.properties
> 部分内容

麻烦问下，jumpserver用的哪个版本的guacamole？貌似guacamole 1.2 才支持这2个参数。

**Comment by wojiushixiaobai** [comment]
如果guacamole支持的话，我们在后续会陆续支持
