### ISSUE TITLE
可以设置密码不可以使用近6次相同的密码

### ISSUE THREAD

**Issue by liuyjishg** [jumpserver/jumpserver#3924]
[简述你的问题]
可以设置密码不可以使用近6次相同的密码

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. [步骤1]  改密码，改成现在相同的密码，依然可以改
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
建议使用ldap或者其他身份认证。
