### ISSUE TITLE
可连接性的图标颜色不会变化？

### ISSUE THREAD

**Issue by kaibinyuan** [jumpserver/jumpserver#3928]
[简述你的问题]
可连接性的图标颜色不会变化？一直是橙色吗？

##### 使用版本
` 1.5.8`

##### 问题复现步骤
`1. 资产管理`
`2. 资产列表`

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/17471338/79817818-df316980-83b8-11ea-8a10-9c611848acec.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kaibinyuan 已修复，更新一下jumpserver
