### ISSUE TITLE
安装的时候没有配置好邮箱，后面在jumpserver.conf里面做了修改，还是报错！

### ISSUE THREAD

**Issue by sharon0113** [jumpserver/jumpserver#393]
error at /juser/user/edit/
[Errno 110] Connection timed out
Request Method:	POST
Request URL:	http://XXX.XXX.XXX.XXX:8000/juser/user/edit/?id=3
Django Version:	1.6
Exception Type:	error
Exception Value:	
[Errno 110] Connection timed out
Exception Location:	/usr/lib64/python2.7/socket.py in create_connection, line 571
Python Executable:	/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/jumpserver',
 '/usr/lib/python2.7/site-packages/AliyunUtil-0.0.1-py2.7.egg',
 '/usr/lib/python2.7/site-packages/cloud_init-0.7.6-py2.7.egg',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages']
Server time:	Thu, 6 Apr 2017 19:13:38 +0800

**Comment by sharon0113** [comment]
换了好几个邮件服务商，都是提示超时。

**Comment by zhaowencheng1991** [comment]
同问，邮箱设置确实有些麻烦

**Comment by g4zhuj** [comment]
看一下是不是25端口被禁了，之前遇到这个问题，排查后发现25端口被禁。使用的是阿里ecs。

**Comment by rowinzhuang** [comment]
阿里云25端口是禁用的。
使用465加密端口就好了
