### ISSUE TITLE
获取系统用户条件判断问题

### ISSUE THREAD

**Issue by yougaUsth** [jumpserver/jumpserver#3931]
[简述你的问题]
获取系统用户条件判断问题

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.6
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/33892298/79935966-cbedcf00-8488-11ea-8cb3-93d989d5fad4.png)
https://github.com/jumpserver/jumpserver/blob/master/apps/perms/utils/asset_permission.py#L368
是否应该是要判断kwargs参数len == 1?

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然存在此问题，感谢反馈
