### ISSUE TITLE
使用sz命令下载数据失败

### ISSUE THREAD

**Issue by wangxiaochuang** [jumpserver/jumpserver#3933]
为什么使用sz命令会下载失败呀？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然存在此问题，感谢反馈
