### ISSUE TITLE
连接windows 报错

### ISSUE THREAD

**Issue by Neo110** [jumpserver/jumpserver#3934]
[简述你的问题]

![C0F3AA4B-32F5-4C39-B4D1-74983B39651F](https://user-images.githubusercontent.com/12504669/79974077-3fb0cb80-84cb-11ea-99ce-c96a4850c9b0.png)
![24218481-2FAA-41AA-B27F-DFFA081C2940](https://user-images.githubusercontent.com/12504669/79974138-59521300-84cb-11ea-9ae0-90ce47ec7a2f.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请参考帮助文档
