### ISSUE TITLE
db数据插入抛异常1366

### ISSUE THREAD

**Issue by soulsall** [jumpserver/jumpserver#3936]
异常报错_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8C\\xB9||...' for column 'output' at row 1")   \\提示说是字符编码问题,但重启jumpserver后正常。
[log ERROR] Internal Server Error: /api/terminal/v1/command/

频繁请求 /api/terminal/v1/command/接口
![image](https://user-images.githubusercontent.com/20919353/80073144-dcca3d80-8579-11ea-8049-dfce611dcab1.png)

代码未发现 /api/terminal/v1/command/接口,请问是在那个文件有定义了这个接口？

**Comment by wojiushixiaobai** [comment]
@soulsall 应该是出现了不识别的字符串，请检查下

**Comment by wxzhe** [comment]
请问重启jumpserver之后，还是报这样的错？有什么解决办法

**Comment by wojiushixiaobai** [comment]
数据库字符集，检查下

**Comment by wxzhe** [comment]
> 数据库字符集，检查下

谢谢已经解决；更改output字段的字符集。
