### ISSUE TITLE
求支持自定义添加任务

### ISSUE THREAD

**Issue by hjun881** [jumpserver/jumpserver#3938]
[简述你的问题]
目前jumpserver不支持自定义添加任务,希望可以添加自定义任务并且能定义或手动触发任务

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver1.5.4

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
已在计划中
