### ISSUE TITLE
跳板机直连需求

### ISSUE THREAD

**Issue by mazesoul87** [jumpserver/jumpserver#3939]
您好，
最近在使用jumpserver的过程中发现一个问题，由于我们部分测试主机也在线上集群中，以前版本的jumpserver通过本地配置proxycommand是可以绕开跳板机的控制。但是这样实际上跳板机的控制也被绕开了，确实有点不安全。最近我们升级了新版本的jumpserver，发现已经不能使用proxycommand这样的方式，封死了这种漏洞。但是目前我们确实有测试环境主机使用proxycommand直连的需求，想问一下，有没有什么办法可以实现绝大部分机器继续安全的情况下，让部分主机可以直连

**Comment by wojiushixiaobai** [comment]
目前不支持这种不安全的方式，如果非要使用的话可以修改源码，源码本身支持，只是我们没有开放
