### ISSUE TITLE
自动更新资产硬件信息

### ISSUE THREAD

**Issue by david666-cc** [jumpserver/jumpserver#3940]
[简述你的问题]
jumpserver无法自动更新资产硬件信息，需要手动一个个点，有什么办法解决吗，机器太多了，手动点不可能

##### 使用版本
1.4.8-2 

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/62531071/80302911-75152c00-87df-11ea-8a7d-02a5359ba218.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by zhangtyps** [comment]
资产管理，资产列表
在节点上右键，不是有个更新节点资产硬件信息的功能么？

**Comment by david666-cc** [comment]
> 资产管理，资产列表
> 在左边列表显示的节点上右键，不是有个更新节点资产硬件信息的功能么？

**非常感谢，已经搞好！**

**Comment by david666-cc** [comment]
在左边列表显示的节点上右键，有个更新节点资产硬件信息的功能
