### ISSUE TITLE
从ldap服务器中导入用户后，和原本的jumpserver用户同名冲突

### ISSUE THREAD

**Issue by wangqian0818** [jumpserver/jumpserver#3945]
[简述你的问题]
我在ldap服务器中添加了一个admin用户，并导入jumpserver，和本地的admin用户有些冲突

jumpserver没有区分哪个admin是ldap里面导入的，同名的都算管理员了，并且两个密码都可以登录，登录后都是超级管理员。

其他不同名不冲突的用户，导入后默认是普通用户，不是管理员，和jumpserver自建用户同名时，导入后就是jumpserver用户的身份了

##### 使用版本
Version 1.5.8-2 GPLv2.

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/57213445/80454728-137acc00-895d-11ea-8095-fb0e2ed80bb6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然存在此问题，感谢反馈
