### ISSUE TITLE
firefox 无法粘贴文本内容到 远程主机

### ISSUE THREAD

**Issue by tonyfud** [jumpserver/jumpserver#3950]
[简述你的问题]

chrome 可以复制粘贴文本内容到 远程windows 主机 ， firefox 不行呢？ 

firefox 75.0 版本 ,  你们有这样的问题吗？ 

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@tonyfud 这个与浏览器有关，需要剪贴板的权限，请检查下权限是否已经给了。请部署ssl

**Comment by zjcnew** [comment]
Windows rdp远程桌面，我测试Chrome可正常复制，Firefox只能里面复制到外面，外面无法复制进去。关闭了弹窗拦截，但并没有什么弹出授权提示，而Chrome是有的。
