### ISSUE TITLE
堡垒机使用三四天之后，登录资产的时间边长。

### ISSUE THREAD

**Issue by stayhungry001** [jumpserver/jumpserver#3952]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7-2
##### 问题复现步骤
1. [步骤1] 刚启动jms的时候，登录资产只需要0.5s左右，4-5天不重启jms，登录资产的时间会长达5秒。jms重启即可恢复。问题必现。资产数量4000+，使用人数100+。
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/56304049/80660656-e9411f80-8abe-11ea-81af-1e52e664cac1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by stayhungry001** [comment]
查看CPU和内存，没有性能瓶颈。

**Comment by wml3** [comment]
楼上的并发量大概有多少

**Comment by stayhungry001** [comment]
并发50左右。

**Comment by N-lucky** [comment]
> 并发50左右。

您好，你的是单节点的jumpserver吗？可以达到并发量50？
