### ISSUE TITLE
连接Windows资产上传文件，不能大于4G

### ISSUE THREAD

**Issue by liangbangke** [jumpserver/jumpserver#3953]
连接Windows资产上传文件，不能大于4G。如果是例如8G这种远大于4G的文件，会在8个G上传进度条完成后报错，而如果是4.1G或4.2G左右的文件，上传进度条完成后不会提示上传错误，而是在Windows资产的共享目录里面的文件正好是4G整，经排查应该是Guacamole组件的Bug，

##### 使用版本
使用的版本1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
https://issues.apache.org/jira/browse/GUACAMOLE-764
<img width="668" alt="Guacamole" src="https://user-images.githubusercontent.com/19382308/80661133-56a18000-8ac0-11ea-84ea-a131ee4f74fb.png">

请问可以单独进行Guacamole组件升级吗？或者有在后续版本中升级Guacamole组件的计划吗？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@liangbangke 有的。
