### ISSUE TITLE
docker-compose 部署jumpserver 报错 Server error occur, contact administrator

### ISSUE THREAD

**Issue by zc-hemenfei** [jumpserver/jumpserver#3955]
今天使用docker-compose 部署jumpserver ，登录admin密码后，报错 Server error occur, contact administrator。
版本1.58 
数据mysql 5.7.30版本的
附上截图：
![image](https://user-images.githubusercontent.com/64582421/80692107-b66d4a80-8b03-11ea-8a4c-b5f5311ff424.png)

**Comment by wojiushixiaobai** [comment]
@zc-hemenfei 我测试了下，未复现你的问题，你应该是多次安装，redis里面的信息未清空导致的

**Comment by zc-hemenfei** [comment]
> @ zc-hemenfei我测试了下，未复现你的问题，你应该是多次安装，redis里面的信息未清空导致的

谢谢,我再去试试，那请问不停服务，进行数据迁移到容器里，该怎么做呢？

**Comment by zc-hemenfei** [comment]
> @zc-hemenfei 我测试了下，未复现你的问题，你应该是多次安装，redis里面的信息未清空导致的
可以把数据库 改为mysql吗？把你的dockerfile修改一下？

**Comment by zc-hemenfei** [comment]
> @zc-hemenfei 我测试了下，未复现你的问题，你应该是多次安装，redis里面的信息未清空导致的

容器起来了，就是导入SQL数据后，界面没有变化，是容器不支持导入数据吗?

**Comment by wojiushixiaobai** [comment]
@zc-hemenfei 导入后重启，确定导入流程无误
