### ISSUE TITLE
修改了NGINX80 端口为其他端口 只有关闭防火墙才能SSH和连接windows 正常，请问修改80端口防火墙后应该如何配置

### ISSUE THREAD

**Issue by mrpretext886** [jumpserver/jumpserver#3956]
[简述你的问题]
修改了NGINX80 端口为其他端口 只有关闭防火墙才能SSH和连接windows 正常，请问修改80端口防火墙后应该如何配置

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.7
加入了新端口策略但是还是不正常，只有关闭防火墙。

[注:] 完成后请关闭 issue

**Comment by mrpretext886** [comment]
[root@jms ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client
  ports: 80/tcp 2222/tcp 2020/tcp 5000/tcp 8081/tcp 3306/tcp 6379/tcp 3389/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv4" source address="172.17.0.0/16" port port="8080" protocol="tcp" accept

**Comment by wojiushixiaobai** [comment]
@mrpretext886 脚本安装的，会自动处理selinux，自行安装的，请在selinux策略里面添加规则。
如是8888端口作为对外端口：
```
yum install -y policycoreutils-python
semanage port -m -t http_port_t -p tcp 8888
setsebool -P httpd_can_network_connect 1
```

**Comment by mrpretext886** [comment]
添加了SElinux 策略，windows无法访问，关闭防火墙正常~！！
yum install -y policycoreutils-python
semanage port -m -t http_port_t -p tcp 2020
setsebool -P httpd_can_network_connect 1

**Comment by wojiushixiaobai** [comment]
@mrpretext886 guacamole 默认使用了 8081 端口，请在防火墙放行此端口。

**Comment by mrpretext886** [comment]
[root@jms ~]# firewall-cmd --list-all
public (active)
target: default
icmp-block-inversion: no
interfaces: eth0
sources:
services: ssh dhcpv6-client
ports: 80/tcp 2222/tcp 2020/tcp 5000/tcp 8081/tcp 3306/tcp 6379/tcp 3389/tcp   



8081端口是放行的！

**Comment by wojiushixiaobai** [comment]
@mrpretext886
docker 依赖 iptables
修改防火墙后请重启docker。

**Comment by mrpretext886** [comment]
jms连同系统都重启了，依然



---原始邮件---
发件人: "wojiushixiaobai"<notifications@github.com&gt;
发送时间: 2020年5月17日(周日) 晚上7:04
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"mrpretext886"<6555591@qq.com&gt;;
主题: Re: [jumpserver/jumpserver] 修改了NGINX80 端口为其他端口 只有关闭防火墙才能SSH和连接windows 正常，请问修改80端口防火墙后应该如何配置 (#3956)




 
@mrpretext886
 docker 依赖 iptables
 修改防火墙后请重启docker。

**Comment by mrpretext886** [comment]
[root@jms ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: ssh dhcpv6-client
  ports: 80/tcp 2222/tcp 2020/tcp 5000/tcp 8081/tcp 3306/tcp 6379/tcp 3389/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv4" source address="172.17.0.0/16" port port="8080" protocol="tcp" accept
-----------------------------------------------------------------------------------------------------------
[root@jms ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:commplex-main
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:EtherNet/IP-1
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:webcache

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere

**Comment by wojiushixiaobai** [comment]
请发nginx的报错和guacamole容器的报错

**Comment by mrpretext886** [comment]
备注“”x.x.x.x 访问IP  xx.xx.xx.xx JMS服务器IP  nginx日志
[root@jms nginx]# cat error.log
2020/05/26 09:57:47 [error] 1532#1532: *2 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET / HTTP/1.1", upstream: "http://[::1]:8080/", host: "xx.xx.xx.xx:2020"
2020/05/26 09:57:47 [warn] 1532#1532: *2 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "GET / HTTP/1.1", upstream: "http://[::1]:8080/", host: "xx.xx.xx.xx:2020"
2020/05/26 09:58:01 [error] 1532#1532: *6 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET /api/v1/perms/users/assets/9cc215ba-7d61-4571-a43e-a41982ab1524/system-users/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/perms/users/assets/9cc215ba-7d61-4571-a43e-a41982ab1524/system-users/", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 09:58:01 [warn] 1532#1532: *6 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "GET /api/v1/perms/users/assets/9cc215ba-7d61-4571-a43e-a41982ab1524/system-users/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/perms/users/assets/9cc215ba-7d61-4571-a43e-a41982ab1524/system-users/", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 09:58:02 [error] 1532#1532: *6 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "POST /guacamole/api/session/ext/jumpserver/asset/add?user_id=23b8ccee-c442-4052-b92f-b5e5b27c9d87&asset_id=9cc215ba-7d61-4571-a43e-a41982ab1524&system_user_id=c5ca7cdd-dfd8-47ba-bd0c-c2cf30c3ac0a&token= HTTP/1.1", upstream: "http://[::1]:8081/api/session/ext/jumpserver/asset/add?user_id=23b8ccee-c442-4052-b92f-b5e5b27c9d87&asset_id=9cc215ba-7d61-4571-a43e-a41982ab1524&system_user_id=c5ca7cdd-dfd8-47ba-bd0c-c2cf30c3ac0a&token=", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 09:58:02 [warn] 1532#1532: *6 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "POST /guacamole/api/session/ext/jumpserver/asset/add?user_id=23b8ccee-c442-4052-b92f-b5e5b27c9d87&asset_id=9cc215ba-7d61-4571-a43e-a41982ab1524&system_user_id=c5ca7cdd-dfd8-47ba-bd0c-c2cf30c3ac0a&token= HTTP/1.1", upstream: "http://[::1]:8081/api/session/ext/jumpserver/asset/add?user_id=23b8ccee-c442-4052-b92f-b5e5b27c9d87&asset_id=9cc215ba-7d61-4571-a43e-a41982ab1524&system_user_id=c5ca7cdd-dfd8-47ba-bd0c-c2cf30c3ac0a&token=", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 09:58:32 [error] 1532#1532: *1 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET /guacamole/app.js?v=1.0.0 HTTP/1.1", upstream: "http://[::1]:8081/app.js?v=1.0.0", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/guacamole/"
2020/05/26 09:58:32 [warn] 1532#1532: *1 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "GET /guacamole/app.js?v=1.0.0 HTTP/1.1", upstream: "http://[::1]:8081/app.js?v=1.0.0", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/guacamole/"
2020/05/26 10:31:42 [error] 1532#1532: *84 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET /api/v1/users/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/users/profile/", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 10:31:42 [warn] 1532#1532: *84 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "GET /api/v1/users/profile/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/users/profile/", host: "xx.xx.xx.xx:2020", referrer: "http://xx.xx.xx.xx:2020/luna/?_=1590458274"
2020/05/26 10:31:44 [error] 1532#1532: *89 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "GET /koko/ws/?X-Websocket-Header-X-Namespace=ssh HTTP/1.1", upstream: "http://[::1]:5000/koko/ws/?X-Websocket-Header-X-Namespace=ssh", host: "xx.xx.xx.xx:2020"
2020/05/26 10:31:44 [warn] 1532#1532: *89 upstream server temporarily disabled while connecting to upstream, client: x.x.x.x, server: , request: "GET /koko/ws/?X-Websocket-Header-X-Namespace=ssh HTTP/1.1", upstream: "http://[::1]:5000/koko/ws/?X-Websocket-Header-X-Namespace=ssh", host: "xx.xx.xx.xx:2020"
You have new mail in /var/spool/mail/root

**Comment by wojiushixiaobai** [comment]
自行解决下
