### ISSUE TITLE
vnc资产有时提示权限不足，有时可以登录

### ISSUE THREAD

**Issue by peixubin** [jumpserver/jumpserver#3957]
[简述你的问题]
刚刚从1.5.5升级到1.5.8，发现使用vnc资产时有个问题，vnc资产有时可以登录，有时提示没有权限。
附上guacamole后台日志 、前端错误提示和正常界面截图。
##### 使用版本
1.5.8

##### 问题复现步骤
 略。

##### 具体表现[截图可能会更好些,最好能截全]
![guacamole_error1](https://user-images.githubusercontent.com/23612384/80872326-c3e12b00-8ce3-11ea-93bf-63de5c06a8de.png)
![normal](https://user-images.githubusercontent.com/23612384/80872329-c9d70c00-8ce3-11ea-97b7-6f2835b0bbfd.png)
![vnc_error1](https://user-images.githubusercontent.com/23612384/80872333-ccd1fc80-8ce3-11ea-8db7-15b984bb2a1b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@peixubin 部署了多组件？还是多层反向代理？

**Comment by peixubin** [comment]
确实是多层反向代理,jms_core是部署 在k8s中，通过ingress进行路径分发，目前core服务只部署了一个。guacamole使用docker部署在两个虚拟机中，前端使用haproxy作为负载均衡。
在 1.5.5和 1.5.6上运行都正常。

**Comment by peixubin** [comment]
已经解决。
原来是有一个guacamole注册未成功。

**Comment by thippo** [comment]
> guacamole

请问是那个guacamole没有注册成功？
