### ISSUE TITLE
独立安装数据库是报错

### ISSUE THREAD

**Issue by sdwxp** [jumpserver/jumpserver#396]
请输入您服务器的IP地址，用户浏览器可以访问 [10.0.0.61]: 
是否安装新的MySQL服务器? (y/n) [y]: n
请输入数据库服务器IP [127.0.0.1]: 
请输入数据库服务器端口 [3306]: 
请输入数据库服务器用户 [jumpserver]: 
请输入数据库服务器密码: 123456
请输入使用的数据库 [jumpserver]: 
Traceback (most recent call last):
  File "install.py", line 307, in <module>
    pre_setup.start()
  File "install.py", line 299, in start
    self._input_mysql()
  File "install.py", line 267, in _input_mysql
    if self._test_db_conn():
  File "install.py", line 192, in _test_db_conn
    import MySQLdb
  File "/usr/lib64/python2.6/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
[root@m01 install]#

**Comment by jiaxiangkong** [comment]
需先创建jumpserver数据库：
mysql> create database jumpserver charset='utf8';
mysql> grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by '5Lov@wife';

**Comment by choldrim** [comment]
> @jiaxiangkong 
> mysql> grant all on jumpserver.* to 'jumpserver'@'127.0.0.1' identified by '5Lov@wife';

Good password! 👍

**Comment by sdwxp** [comment]
创建了jumpserver 库也不行
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| jumpserver         |
| mysql              |
| performance_schema |
| test               |
+--------------------+
5 rows in set (0.33 sec)

mysql> select user,host from mysql.user;
+------------+-----------+
| user       | host      |
+------------+-----------+
| jumpserver | 127.0.0.1 |
| root       | 127.0.0.1 |
| root       | ::1       |
|            | localhost |
| root       | localhost |
|            | m01       |
| root       | m01       |
+------------+-----------+
7 rows in set (0.00 sec)

mysql> 
还是报错

请输入您服务器的IP地址，用户浏览器可以访问 [10.0.0.61]: 
是否安装新的MySQL服务器? (y/n) [y]: n
请输入数据库服务器IP [127.0.0.1]: 
请输入数据库服务器端口 [3306]: 
请输入数据库服务器用户 [jumpserver]: 
请输入数据库服务器密码: 5Lov@wife
请输入使用的数据库 [jumpserver]: 
Traceback (most recent call last):
  File "./install.py", line 307, in <module>
    pre_setup.start()
  File "./install.py", line 299, in start
    self._input_mysql()
  File "./install.py", line 267, in _input_mysql
    if self._test_db_conn():
  File "./install.py", line 192, in _test_db_conn
    import MySQLdb
  File "/usr/lib64/python2.6/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
[root@m01 install]#

**Comment by jiaxiangkong** [comment]
系统32位：
ln -s /usr/local/mysql/lib/libmysqlclient.so.18 /usr/lib/libmysqlclient.so.18

系统64位：
ln -s /usr/local/mysql/lib/libmysqlclient.so.18 /usr/lib64/libmysqlclient.so.18

**Comment by Magicbrust** [comment]
yum install mysql-devel -y

**Comment by zhusas** [comment]
我也遇到这个问题，一模一样，尝试解决中~~~

**Comment by zhusas** [comment]
系统64位：
ln -s /usr/local/mysql/lib/libmysqlclient.so.18 /usr/lib64/libmysqlclient.so.18 这个正解

![qq 20170711153541](https://user-images.githubusercontent.com/17040150/28056295-0b1eb820-664f-11e7-8fbc-1b784eb497d7.png)
