### ISSUE TITLE
guacamole运行时提示获取用户权限失败

### ISSUE THREAD

**Issue by graveskeeper** [jumpserver/jumpserver#3961]
[问题]
guacamole运行中提示获取用户权限失败添加资产异常，web端登录linux正常，登录Windows环境异常，/config/guacamole/keys下没有生成认证key，/root/.bashrc中的BOOTSTRAP_TOKEN和/opt/jumpserver/config.yml中的BOOTSTRAP_TOKEN相同，请问还有哪里配置有问题呢？
![guacamole](https://user-images.githubusercontent.com/12812213/81158398-836eff00-8fba-11ea-9e6e-f138aac947e1.png)

参考安装步骤：https://docs.jumpserver.org/zh/master/step_by_step.html
中的：9.正常安装并启动 guacamole 组件 

##### 使用版本
[1.5.5]

**Comment by wojiushixiaobai** [comment]
@graveskeeper 抱歉，因正常部署guacamole步骤太多，暂时不知道问题出现在哪，还请自行检查下或者考虑使用docker快速部署guacamole。
我们不再推荐正常部署guacamole，后续文档中也会逐步去掉此步骤
