### ISSUE TITLE
网络设备登录与 cisco acs 上的用户关联

### ISSUE THREAD

**Issue by teesa-git** [jumpserver/jumpserver#3962]
请教一个问题。
我现在是的使用环境是网络设备登录管理使用 cisco acs 统一认证登录，现在想增加一台堡垒机，就是想问下，在堡垒机上如何配置登录堡垒机的用户和登录资产的用户与cisco acs 上的用户保持致。
我最终想实现的就是在ACS上的用户A、B、C、D，用户同样的账户和密码登录堡垒机，再登录网络设备进行相关操作。

**Comment by wojiushixiaobai** [comment]
请参考cas文档
