### ISSUE TITLE
1.5.5 命令行访问新主机失败 ssh: unable to authenticate

### ISSUE THREAD

**Issue by wangyjx** [jumpserver/jumpserver#3966]
[简述你的问题]
添加一台新主机(Centos 7.6 64bit), 使用了和其他主机一样的root用户和密码，顺利通过连接测试，以及硬件信息更新。通过命令行进入时，报错

ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none password], no supported methods remain

测试直接通过ssh从本地访问目标主机没有问题，在跳板机上通过ssh访问目标主机也没有问题. 删掉机器重新添加也是一样的问题。之前添加的其他机器没有问题

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.5-2
##### 问题复现步骤
1.  添加服务器
2. 连接测试成功
3. 通过命令行访问失败

##### 具体表现[截图可能会更好些,最好能截全]
![Screen Shot 2020-05-07 at 1 54 39 PM](https://user-images.githubusercontent.com/1570571/81259362-63971400-906a-11ea-8850-c7cd6bb9403d.png)
![Screen Shot 2020-05-07 at 1 55 01 PM](https://user-images.githubusercontent.com/1570571/81259371-66920480-906a-11ea-81c7-33a471165223.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wangyjx** [comment]
解决了，这台新添加的机器没有自动被创建admin系统用户，手动推送后成功连接。

**Comment by HUAN-u** [comment]
![img_v3_02d9_a140ca8c-9d99-486d-bb98-b93f92f46e3g](https://github.com/user-attachments/assets/ad1c5880-35e7-4a41-acd1-a58734e12d76)
我这个也是重新上传也不行,这是有什么问题
