### ISSUE TITLE
ssh:rejected:administratively prohibited（open failed）

### ISSUE THREAD

**Issue by s2wcn** [jumpserver/jumpserver#3970]
[简述你的问题]
部分用户ssh连接客户机会提示这个错误，其他用户正常。奇怪

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.8

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/54429435/81362814-533b7380-9114-11ea-9f5d-e04f43d37b2c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by yhegago** [comment]
![image](https://user-images.githubusercontent.com/53813080/83728943-8ae8fd00-a679-11ea-8877-bf23391cf701.png)
我也遇到了同样的问题。奇怪的是，同权限组的其他用户登录正常，就这一个用户登录的时候，报这个错误。

**Comment by wojiushixiaobai** [comment]
尚未复现，请更新新版本验证看看。

**Comment by luciferYu** [comment]
![image](https://user-images.githubusercontent.com/18610586/88142580-5aa8ee00-cc28-11ea-8418-4de461145960.png)
遇到相同问题
