### ISSUE TITLE
不支持快捷键

### ISSUE THREAD

**Issue by lodian** [jumpserver/jumpserver#3977]
Ubuntu机器上使用JumpServer连接Windows Server，组合键命令无效

##### 使用版本
JumpServer 1.5.8

##### 问题复现步骤
1. 在Ubuntu16.04机器上使用JumpServer连接Windows Server使用时，由于Windows Server机器处于锁定状态，必须使用Ctrl+Alt+Delete才能弹出密码输入框，而在Web页面中按下此组合键，则触发的是Ubuntu系统下对应的快捷功能，组合键命令没有传递到远端的Windows Server。
2. 同样的，进入到Windows Server之后，按下Win+L锁屏组合键，触发的是Ubuntu的锁屏，远端Windows Server只收到了Win的命令。

**Comment by wojiushixiaobai** [comment]
@lodian 请参考guacamole官方网站，看是否有其他的解决方案。
