### ISSUE TITLE
正在等待 jumpserver **** 的响应

### ISSUE THREAD

**Issue by zhaowencheng1991** [jumpserver/jumpserver#398]
当创建用户时到最后一步点击完成时并且勾住发邮件的选项就卡主不动，一直说正在等待 *.*.*.* 的响应，修改过smtp服务器地址，也是不行。谁有遇到过类似情况。

**Comment by zhaowencheng1991** [comment]
问题已经解决，也分享给大家，首先排查网络因素。  好尴尬！！

**Comment by wtli** [comment]
我也一样的，怎么排查网络？带宽已经从1M升到10M了。还是没有用
