### ISSUE TITLE
jumpserver安装后默认admin账号问题

### ISSUE THREAD

**Issue by mylanvv** [jumpserver/jumpserver#3991]
[简述你的问题]

##### 使用版本
1.5.8版本

##### 问题复现步骤
使用docker-compose安装，安装完成后，默认管理员账号为：admin
请教，如果更改admin账号？
##### 
请教，如果更改admin账号？

##### 其他

[注:] 完成后请关闭 issue

**Comment by mylanvv** [comment]
一、尝试操作了一种方法：
1、先使用admin创建一个xxx的管理员账号。
2、然后登录xxx管理员账号，将admin账号的个人信息，修改，如用户名、邮件、设置为普通用户等等。
3、然后使用新建的xxx管理，进行删除admin账号。
4、完成。
![image](https://user-images.githubusercontent.com/37101066/81668988-122ac280-9478-11ea-8868-1d29051eac6f.png)


二、使用mysql数据库进行修改

三、是否有在初始化安装时，可以设置其他管理员账号的方式？

**Comment by wojiushixiaobai** [comment]
@mylanvv 可以通过控制台修改，参考django方式即可。
