### ISSUE TITLE
JumpServer 1.5.8版本使用的一些问题

### ISSUE THREAD

**Issue by mylanvv** [jumpserver/jumpserver#3995]
##### 使用版本
JumpServer 1.5.8

##### 问题复现步骤
https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/81797352-3bfbec00-9541-11ea-9901-ffb5e333de6c.png
1、仪表板->活跃用户资产占比
问题描述：使用鼠标移动至此处会信息一直闪
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/81797352-3bfbec00-9541-11ea-9901-ffb5e333de6c.png)

2、资产管理->资产列表->创建资产->认证->管理用户  （此处是否可不是必选条件？）
https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/81797838-dbb97a00-9541-11ea-8b0f-24abce7afa92.png
在使用过程中，发现创建资产时，这个选项必选，而且使用此功能的前提下是需要给root权限或NOPASSWD: ALL权限  这对于服务器来说是不安全的，建议设置为可选。（虽然可通过创建一个假的管理用户避免，但是感觉设置为可选更可行）

![image](https://user-images.githubusercontent.com/37101066/81797838-dbb97a00-9541-11ea-8b0f-24abce7afa92.png)

3、会话管理->终端管理
有一次将这2个删除了，发现没有创建按钮，一旦删除后，就需要重建服务
也没找到这2个终端具体的文档/使用说明/注意事项
![image](https://user-images.githubusercontent.com/37101066/81798055-25a26000-9542-11ea-98ce-568d096384cd.png)

4、会话管理->终端管理->存储配置->创建录像存储->创建阿里云oss->修改问题3提到的2个终端里面的录像存储配置，使用阿里云oss

当配置完成后，录像视频是可以顺利存放到阿里云oss的，
但是在JumpServer查看回放视频时，提示找不到录像视频，猜测播放视频还是在本地找视频了

**Comment by mylanvv** [comment]
![image](https://user-images.githubusercontent.com/37101066/81909633-75922d00-95fd-11ea-92bc-780ac2b3f152.png)
在个人信息->api key->创建api key后 无法删除

**Comment by wojiushixiaobai** [comment]
@mylanvv 感谢反馈

问题1.  暂时忽略，在做前后端分离。会优化

问题2.  我们的初衷是管理员把资产托管到 jumpserver，然后由 jumpserver 完成资产自动化授权操作（体验方面会优化的），否则授权的同时还需要先到资产上面进行操作。

问题3.  文档里面是包含这部分说明的，具体在帮助文档，koko和guacamole文档的第一条。或者你没留意直接连接了资产，根据报错在帮助文档的 luna 文档里面也有对应的提示。

问题4.  录像上传阿里云后，用户需要播放时还会通过oss下载到本地，然后播放，录像比较大的话可能是下载未完成或者出现了网络故障。建议检查下log

问题5.  此问题已经复现，提交到开发组了。
