### ISSUE TITLE
(docker)能否支持环境变量修改开放端口(ssh/web)

### ISSUE THREAD

**Issue by GuiBin2013** [jumpserver/jumpserver#3999]
[简述你的问题]

想通过环境变量改变容器内部开放的端口号(不确定是否支持这个，找不到)

##### 使用版本
最新的docker镜像 > 1.4

##### 问题复现步骤
1. 目前我们使用docker部署服务，服务器都做了【ip限制】，只能通过堡垒机所在的ip访问进去。
2. 现在的问题在于，docker部署使用端口映射(bridge模式)，通过【堡垒机】访问【堡垒机所在的宿主机】，会被拒绝，原因是容器会走内部网络访问物理机。

解决的办法：
1. 将堡垒机容器的ip加入该物理机的白名单，可以解决。
2. 通过docker host模式部署堡垒机，问题在于，我不希望开放2222/80端口，想改变开放的端口号。

##### 其他
当然通过1解决了这个问题，但更希望2的问题能够解决(当然，我自己改代码也可以实现)，主要考虑到之后可能会更新的功能。

thx！

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
内部的不支持修改，但是你可以改外部的。可以参考docker官方文档
比如你想使用外部的 8888 和 55222 来作为 http 和 ssh 端口，可以参考下面命令
```
docker run --name jms_all -d
  -p 8888:80 -p 55222:2222
  -e SECRET_KEY=$SECRET_KEY
  -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN
  jumpserver/jms_all:latest
```

**Comment by GuiBin2013** [comment]
@wojiushixiaobai 
你好，是这样的，我们目前希望所有服务器都通过jumpserver跳转，所以给所有远程服务器都做了ip限制，即只允许堡垒机所在的服务器(假设为172.8.8.8)。

在使用docker网桥模式(-p 8888:80 -p 55222:2222)，容器会获得一个内部ip(假设为10.10.10.10)，此时有出现一个问题，从堡垒机去远程堡垒机所在的服务器172.8.8.8，堡垒机会通过10.10.10.10去访问自己的宿主机，而不是172.8.8.8这个地址，会导致这台服务器拒绝了远程。

要解决这个问题，我们只能将堡垒机的容器内部ip(10.10.10.10)，加入该宿主机的白名单(这种操作显得有点奇怪)，目前也是这么解决的。

后来有考虑docker的host模式，这时主机和容器共享网络，堡垒机访问宿主机就会通过外部的ip，但这样的话容器开放了什么端口，主机就开放什么端口，才有了想要改变内部端口的一个想法。

**Comment by wojiushixiaobai** [comment]
@GuiBin2013 可以直接到容器里面修改配置文件，或者重新制作一份镜像
