### ISSUE TITLE
系统用户的sudo 修改失败

### ISSUE THREAD

**Issue by stayhungry001** [jumpserver/jumpserver#4000]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7-2 GPLv2.
##### 问题复现步骤
1. [步骤1]  配置多个系统用户，并且都有sudo配置，应用到服务器节点上。
2. [步骤2] 批量添加服务器，自动推送系统用户。偶尔出现部署服务器的部分系统用户出现sudo失败。

##### 具体表现[截图可能会更好些,最好能截全]
系统用户推送是并行的，导致同一时间会有多个推送任务同时修改/etc/sudoers权限，部分系统用户修改完之后被其他系统用户任务覆盖了。
建议自动推送，同一台服务器的推送任务合并到同一个task，串行推送。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
已在优化列表中，感谢反馈
