### ISSUE TITLE
jumpserver  WEB页面登陆后关闭浏览器（不做注销操作），再次打开web不需要输入密码（已经开启动态码验证）

### ISSUE THREAD

**Issue by lucongyong** [jumpserver/jumpserver#4006]
[简述你的问题]
jumpserver  WEB页面登陆后关闭浏览器（不做注销操作），再次打开web不需要输入密码（已经开启动态码验证）。因为工作机是公用的，如果上一个人操作完成只是关闭了浏览器，未登出。后面来操作的人打开堡垒机就自动登陆上一位操作者的账号。
请问这个问题哪里能够设置和避免。测试清除浏览器缓存时可以解决这个问题，但是每次操作完成都清除浏览器缓存不太现实。
##### 使用版本
[请提供你使用的Jumpserver版本 1.5.8 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. 打开浏览器登陆堡垒机页面；
2.使用web客户端登陆服务器（我这里使用web 终端登陆linux 服务器）；
3. 不注销账户，关闭浏览器（很多人没有注销账户习惯）；
4.再次打开浏览器，无需输入账号密码就可以登陆堡垒机web页面；

我想咨询一下，web页面有没有地方可以配置超时登出的地方。（提示：不是SSH登陆超时，是堡垒机页面空闲自动登出）

##### 其他

[注:] 完成后请关闭 issue

**Comment by lucongyong** [comment]
目前我做了几轮测试，确认是浏览器cookie,问题。而且这种现象是间断性发生。我想咨询一下，web页面有没有地方可以配置超时登出的地方。（提示：不是SSH登陆超时，是堡垒机页面空闲自动登出）

**Comment by orangemio** [comment]
请参考
https://github.com/jumpserver/jumpserver/blob/c700b101c190acdfc2e37d71957a96c13c59e2fd/config_example.yml#L21

**Comment by lucongyong** [comment]
请问是不是直接修改jumpserver/config_example.yml这个文件，重启服务就可以生效？

**Comment by lucongyong** [comment]
> 请参考
> https://github.com/jumpserver/jumpserver/blob/c700b101c190acdfc2e37d71957a96c13c59e2fd/config_example.yml#L21

请问是不是直接修改jumpserver/config_example.yml这个文件，重启服务就可以生效？

**Comment by orangemio** [comment]
`config_example.yml` 是配置的模板文件，请修改`config.yml`然后重启服务。

**Comment by lucongyong** [comment]
> `config_example.yml` 是配置的模板文件，请修改`config.yml`然后重启服务。

经过查看确认目前config.yml  中的SESSION_EXPIRE_AT_BROWSER_CLOSE:  true。 现象依然存在。

**Comment by orangemio** [comment]
True

**Comment by wojiushixiaobai** [comment]
@lucongyong Windows 浏览器默认都会关闭后在进程驻留，详情请看浏览器设置页面。如果进程不完全退出此参数无效。

**Comment by lucongyong** [comment]
@orangemio  @wojiushixiaobai   感谢二位耐心解答，目前我的解决方案是SESSION_EXPIRE_AT_BROWSER_CLOSE: True
SESSION_COOKIE_AGE:  1800
这两个参数同时开启，基本可以满足目前需求。

**Comment by xiaoyou2018** [comment]
您好，我在jms_core 容器中
cp config_example.yml  config.yml
然后按照上面的修改了
SESSION_EXPIRE_AT_BROWSER_CLOSE: True
SESSION_COOKIE_AGE: 600
重启容器报错，unhealthy
打开页面  nginx error
