### ISSUE TITLE
jumpsever1.5.8版本，api创建assets_node等关联记录后，容易获取node值为None报错

### ISSUE THREAD

**Issue by fgf01** [jumpserver/jumpserver#4013]
[简述你的问题]
数据库里创建assets_node 表记录，
数据库里api增加记录后，打开页面展示
![image](https://user-images.githubusercontent.com/18435457/82335864-77ecf080-9a1c-11ea-876b-6eb81197d6d6.png)

##### 使用版本
使用的Jumpserver版本 1.5.8

##### 问题复现步骤
代码里 node为None 就报错了，如下1.5.8 和1.5.6 的版本对比
![image](https://user-images.githubusercontent.com/18435457/82336179-d4e8a680-9a1c-11ea-9368-75423b95cca9.png)
感觉还是1.5.6版本这部分稳定。

导致用户资产除非bug后，无资产。

##### 具体表现[截图可能会更好些,最好能截全]
<img width="1191" alt="QQ20200519-215744@2x" src="https://user-images.githubusercontent.com/18435457/82335385-d2d21800-9a1b-11ea-8d05-d359ae0f9ed3.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by fgf01** [comment]
我源码做了如下调整，不会有上边的报错，不知道这样调整有没有影响
![Uploading image.png…]()

**Comment by fgf01** [comment]
我源码做了如下调整，不会有上边的报错，不知道这样调整有没有影响
![image](https://user-images.githubusercontent.com/18435457/82338613-b1732b00-9a1f-11ea-9b09-022b26c0fd4d.png)

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
