### ISSUE TITLE
ssh心跳检测没有效果

### ISSUE THREAD

**Issue by teesa-git** [jumpserver/jumpserver#4014]
您好，我的1.5.8版本，还是遇到一样的问题。
![1](https://user-images.githubusercontent.com/52067473/82393416-e069bb00-9a78-11ea-98ac-d43fe7884d3f.png)

到KOKO容器里面修改配置文件，重启后还是连接一会就中断。
![82027629-20bae900-96c7-11ea-9af6-1d3c2a1248ed](https://user-images.githubusercontent.com/52067473/82393466-042d0100-9a79-11ea-9582-40f9cf471e9f.png)
![3](https://user-images.githubusercontent.com/52067473/82393472-08591e80-9a79-11ea-8166-9ace96d02057.png)

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈

**Comment by teesa-git** [comment]
> 请验证新版本是否仍然出现此问题，感谢反馈

您好，已经升级到最新的2.3.0版本，还是会出现同样的问题。

**Comment by LeeEirc** [comment]
@teesa-git 加我q，2970298425，远程看下。
