### ISSUE TITLE
有没有保存个人书签功能？

### ISSUE THREAD

**Issue by lingkdong** [jumpserver/jumpserver#4016]
保存个人访问记录，作为个人书签

类似这个
![pic](https://user-images.githubusercontent.com/10709160/82401789-524bff80-9a8d-11ea-80c9-6fba75a96b17.png)
或者加个 常用服务器列表
![image](https://user-images.githubusercontent.com/10709160/82402017-f59d1480-9a8d-11ea-9a7d-65cb270ef557.png)

**Comment by githubforyour** [comment]
需要，尽快支持一下！

**Comment by wojiushixiaobai** [comment]
有，可以收藏资产
