### ISSUE TITLE
docker-compose部署，SMTP问题

### ISSUE THREAD

**Issue by yananshiwo** [jumpserver/jumpserver#4018]
按照官方文档docker-compose部署1.5.8
系统设置——邮箱设置
无论修改什么样的邮箱账号，测试成功后，在提交后，设置还原为admin

![image](https://user-images.githubusercontent.com/63760169/82425711-7de4df00-9ab9-11ea-840f-37a95f1b8bf4.png)

SMTP账号无法修改，TLS也测试了不能修改保存

**Comment by yananshiwo** [comment]
![image](https://user-images.githubusercontent.com/63760169/82425580-483ff600-9ab9-11ea-8547-cdff798030cd.png)

**Comment by wojiushixiaobai** [comment]
@yananshiwo 把你保存的浏览器账户密码清理掉即可

**Comment by yananshiwo** [comment]
ok，换了一个浏览器是正常的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wojiushixiaobai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 晚上9:12
收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送:&nbsp;"安安"<8287373@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] docker-compose部署，SMTP问题 (#4018)





 
@yananshiwo 把你保存的浏览器账户密码清理掉即可
