### ISSUE TITLE
能否增加个功能：将历史会话导出为视频存储起来

### ISSUE THREAD

**Issue by jackwang-github** [jumpserver/jumpserver#4023]
[简述你的问题]
能否增加个功能：将历史会话导出为视频存储起来

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
暂时没有此计划， 但是会优化审计模块
