### ISSUE TITLE
使用RDP协议方式，添加windowns server 2016机器，提示“该主机没有授权登录用户”

### ISSUE THREAD

**Issue by mahb2018** [jumpserver/jumpserver#4024]
[简述你的问题]

##### 使用版本
[Jumpserver版本 1.4.7-2 GPLv2]

##### 问题复现步骤
1. 根据官方文档操作说明，无论使用系统用户 自动登录 设置 或是 手动登录，都提示“该主机没有授权登录用户”

[注:] 完成后请关闭 issue

**Comment by zhangtyps** [comment]
资产有没有设置rdp协议？

**Comment by mahb2018** [comment]
设置过了

**Comment by mahb2018** [comment]
官方技术能解决下吗

**Comment by mahb2018** [comment]
自已解决了，需要单独加一下超级管理员，默认超级管理员是没有权限的
