### ISSUE TITLE
Web终端希望可以增加记录展开状态的功能

### ISSUE THREAD

**Issue by zjcnew** [jumpserver/jumpserver#4031]
[简述你的问题]
因为项目比较多，分类按照不同环境不同项目，Web终端操作，每次打开都需要重新展开授权的资产列表，资产树节点路径比较深，这样操作变的很繁琐，希望可以增加自动记录资产树展开状态；收藏并功能对我环境并不能起到良好的效果，主机都是按项目分类的，且数量众多。

![企业微信截图_20200522140645](https://user-images.githubusercontent.com/22335594/82636568-819d7080-9c35-11ea-9dd9-7e1ed894267e.png)

##### 使用版本
1.5.8

**Comment by wojiushixiaobai** [comment]
@zjcnew 感谢反馈，问题已经收到，我会反馈上去。

**Comment by david666-cc** [comment]
> @zjcnew 感谢反馈，问题已经收到，我会反馈上去。

顺便问下大佬，ssh连接coco能否像这个web terminal一样支持资产树展开的形式。毕竟密密麻麻的机器实在不好找，我现在都是在web terminal上找到对应机器IP，然后用这个ssh连上coco，再输入IP找那个机器。
