### ISSUE TITLE
JumpServer配置了CAS单点登录之后MFA认证是否还生效？

### ISSUE THREAD

**Issue by charliewch** [jumpserver/jumpserver#4032]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
v1.5.8
##### 问题复现步骤
1. JumpServer配置了CAS单点登录之后MFA认证是否还生效？

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@charliewch 无法生效，你应该在CAS认证做限制。而非对应用做限制
