### ISSUE TITLE
资产树无法修改，报400错误

### ISSUE THREAD

**Issue by miaoyt** [jumpserver/jumpserver#4034]
[简述你的问题]
资产树无法修改，报400错误

##### 使用版本
1.5.9
##### 问题复现步骤
1. 点左侧资产数，重命名

##### 具体表现
![image](https://user-images.githubusercontent.com/18459102/82676734-72d8ad00-9c79-11ea-8de4-93fe189753f3.png)
![image](https://user-images.githubusercontent.com/18459102/82676833-9865b680-9c79-11ea-9ea8-bb65d7737fd9.png)

日志搜索不到错误

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@miaoyt 抱歉，根节点不支持重命名
