### ISSUE TITLE
应用管理添加mongo 数据库

### ISSUE THREAD

**Issue by towithyou** [jumpserver/jumpserver#4035]
[简述你的问题]
目前mysql  管理的不错。可否添加个mongo 和redis 管理。这样就更棒了

##### 使用版本
Jumpserver版本 1.5.9

**Comment by wojiushixiaobai** [comment]
@towithyou 已经有用户反馈过，后期应该会加的，请带耐心等待。

**Comment by happysonline** [comment]
请问这个近期有计划吗？

**Comment by qiyongxiao** [comment]
我们也想加入这个功能
