### ISSUE TITLE
1.5.9版本资产备注字段太短bug

### ISSUE THREAD

**Issue by w7374520** [jumpserver/jumpserver#4037]
问题：
       资产创建中的备注字段太短，只有128个字符串
  其它
      备注
       请确保这个字段不能超过 128 个字符。

数据库assets_asset表结构为：
         
MariaDB [jumpserver]> desc assets_asset;
+---------------+---------------+------+-----+---------+-------+
| Field         | Type          | Null | Key | Default | Extra |
+---------------+---------------+------+-----+---------+-------+
| id            | char(32)      | NO   | PRI | NULL    |       |
| ip            | varchar(128)  | NO   | MUL | NULL    |       |
| hostname      | varchar(128)  | NO   |     | NULL    |       |
| port          | int(11)       | NO   |     | NULL    |       |
| is_active     | tinyint(1)    | NO   |     | NULL    |       |
| public_ip     | varchar(128)  | YES  |     | NULL    |       |
| number        | varchar(32)   | YES  |     | NULL    |       |
| vendor        | varchar(64)   | YES  |     | NULL    |       |
| model         | varchar(54)   | YES  |     | NULL    |       |
| sn            | varchar(128)  | YES  |     | NULL    |       |
| cpu_model     | varchar(64)   | YES  |     | NULL    |       |
| cpu_count     | int(11)       | YES  |     | NULL    |       |
| cpu_cores     | int(11)       | YES  |     | NULL    |       |
| memory        | varchar(64)   | YES  |     | NULL    |       |
| disk_total    | varchar(1024) | YES  |     | NULL    |       |
| disk_info     | varchar(1024) | YES  |     | NULL    |       |
| os            | varchar(128)  | YES  |     | NULL    |       |
| os_version    | varchar(16)   | YES  |     | NULL    |       |
| os_arch       | varchar(16)   | YES  |     | NULL    |       |
| hostname_raw  | varchar(128)  | YES  |     | NULL    |       |
| created_by    | varchar(32)   | YES  |     | NULL    |       |
| date_created  | datetime(6)   | YES  |     | NULL    |       |
**| comment       | longtext      | NO   |     | NULL    |       |**    # 为longtext
| admin_user_id | char(32)      | YES  | MUL | NULL    |       |
| domain_id     | char(32)      | YES  | MUL | NULL    |       |
| protocol      | varchar(128)  | NO   |     | NULL    |       |
| org_id        | varchar(36)   | NO   | MUL | NULL    |       |
| cpu_vcpus     | int(11)       | YES  |     | NULL    |       |
| protocols     | varchar(128)  | NO   |     | NULL    |       |
| platform_id   | int(11)       | NO   | MUL | NULL    |       |
+---------------+---------------+------+-----+---------+-------+

models限制为：
(py3) [root@wdyz models]# pwd
/home/jumpserver/apps/assets/models
(py3) [root@wdyz models]# vim asset.py
223     labels = models.ManyToManyField('assets.Label', blank=True, related_name='assets', verbose_name=_("Labels"))
224     created_by = models.CharField(max_length=32, null=True, blank=True, verbose_name=_('Created by'))
225     date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name=_('Date created'))
226     comment = models.TextField(max_length=2000, default='', blank=True, verbose_name=_('Comment'))            #默认限制为128字符串，修改为2000

应用修改
(py3) [root@wdyz apps]# pwd
/home/jumpserver/apps
(py3) [root@wdyz apps]# python manage.py makemigrations
Migrations for 'assets':
  assets/migrations/0050_auto_20200525_1048.py
    - Alter field comment on asset
(py3) [root@wdyz apps]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying assets.0050_auto_20200525_1048... OK

请修复。。。感谢

**Comment by ibuler** [comment]
修复了

**Comment by w7374520** [comment]
thks
