### ISSUE TITLE
Edge浏览器远程登录win系统键盘输入会失灵

### ISSUE THREAD

**Issue by a1711hw** [jumpserver/jumpserver#4038]
[简述你的问题]

##### 使用版本

Version 1.5.8-2 GPLv2.

##### 问题复现步骤
1、Microsoft Edge浏览器登录jumpserver
2、连接Windows服务器
3、输入账号和密码

##### 具体表现[截图可能会更好些,最好能截全]
当使用Microsoft Edge浏览器进行远程连接Windows服务器时，在账户登录界面键盘输入会失灵

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
