### ISSUE TITLE
用户可见的资产显示比实际授权的多

### ISSUE THREAD

**Issue by dshowing** [jumpserver/jumpserver#4044]
[简述你的问题]
我给用户授权一台节点，但是上层目录的资产用户也能看到，虽然不能登录，单这些机器的信息都暴露了。我现在用的是1.5.7版本，请问是已知的bug吗？

##### 使用版本
Jumpserver 1.5.7

##### 问题复现步骤
1、给普通用户授权一台非根目录下的服务器
2、普通用户登录，查看资产，发现上级父目录下的资产信息也能看到（web终端不能登录这些多出来的服务器）

##### 具体表现
![image](https://user-images.githubusercontent.com/24406597/82896904-54c8c080-9f89-11ea-9b8b-409ba68e169b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@dshowing 可以看到目录是正常的，如果看到不应看到的资产表示授权不当，请仔细检查。
旧版本的问题请更新到新版本后看是否复现。
另外，如果不想让用户看到节点信息，可以在 config.yaml 里面加入
```
# Perm show single asset to ungrouped node
# 是否把未授权节点资产放入到 未分组 节点中
PERM_SINGLE_ASSET_TO_UNGROUP_NODE: true
```
然后重启 core 即可
