### ISSUE TITLE
pam_ldap 用户登录时需要使用密码

### ISSUE THREAD

**Issue by slzcc** [jumpserver/jumpserver#4045]
在服务器开启 pam_ldap 认证后，堡垒机选择机器通过个人账户登录需要输入密码才可以进入，是否可以直接记录当前登入用户的 session 直接登录呢？，模式是自动登录使用用户名与用户相同的模式

v1.5.8

![image](https://user-images.githubusercontent.com/16853525/82984411-b7bb6580-a024-11ea-8dad-c495d9e59a66.png)

**Comment by wojiushixiaobai** [comment]
@slzcc 抱歉，目前不会记录第三方认证系统的密码。
