### ISSUE TITLE
1.5.4升级到最新版本启动报错

### ISSUE THREAD

**Issue by dongdarui** [jumpserver/jumpserver#4051]
[简述你的问题]
1.5.4升级到最新版本启动报错

##### 使用版本
1.5.4

##### 问题复现步骤
1. ./jms start -d
报错：django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
2. 日志中
报错：django.db.utils.OperationalError: (1054, "Unknown column 'users_user.mfa_level' in 'field list'")

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
抱歉，暂时无法复现，请考虑手动修复一下表结构看看
