### ISSUE TITLE
资产授权无效

### ISSUE THREAD

**Issue by kernelzhen** [jumpserver/jumpserver#4053]
[简述你的问题]
资产授权之前有这个权限我删除了 重新添加就 变成无效

##### 使用版本
之前用1.5.6也是 这个问题 我升级到1.5.9还有

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/20443637/83260932-c781a800-a1e4-11ea-9817-d9fde43af856.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kernelzhen 能否详细描述复现过程
