### ISSUE TITLE
jms_core进程自动终止，8080端口down

### ISSUE THREAD

**Issue by yongxiaodong** [jumpserver/jumpserver#4054]
[简述你的问题]

当jms_core 运行的时候，看起来一切正常。但是过几分钟jms_core 就会自动终止，8080端口也down掉了，web页面显示502

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version=1.5.9
部署方式：使用了官网的极速部署方案，https://jumpserver.readthedocs.io/zh/master/install/setup_by_fast/

##### 问题复现步骤
1. 编辑config.conf 使用外部Mysql和Redis（链接数据库正常）
2. sh jmsctl.sh install 安装完成后使用提示的IP：Port 访问web页面正常，可以成功登陆web页面并进行相关操作
3、过几分后页面Nginx就是提示502 ， 我核实了服务器上8080端口已经被终止
4、我通过 systemctl start jms_core重新启动了jms_core，web页面又恢复了正常访问，8080端口也监听正常，但是几分钟后jms_core 又自动终止了

###### 这是gunicorn.log最后的日志
![image](https://user-images.githubusercontent.com/23717585/83344143-8816a100-a335-11ea-9ba8-74adebe5e837.png)

###### 这是flower.log日志，其中有一个reids报错，我不确定这个异常是不是导致jms_core 终止的原因（我使用的是redis集群）
![image](https://user-images.githubusercontent.com/23717585/83344143-8816a100-a335-11ea-9ba8-74adebe5e837.png)

###### 这是 daphne.log 
![image](https://user-images.githubusercontent.com/23717585/83344155-b09e9b00-a335-11ea-96cc-fbb262de1270.png)

**Comment by wojiushixiaobai** [comment]
@yongxiaodong core 目前不支持集群，请更换自带的仓库包
