### ISSUE TITLE
RDP是否支持键盘呼出和复制粘贴

### ISSUE THREAD

**Issue by EvanQuCN** [jumpserver/jumpserver#4055]
RDP是否支持键盘呼出和复制粘贴

**Comment by wojiushixiaobai** [comment]
ctrl + alt + shift
ssl 部署后即可支持剪贴板复制粘贴（需要浏览器剪贴板权限）

**Comment by EvanQuCN** [comment]
> ctrl + alt + shift
> ssl 部署后即可支持剪贴板复制粘贴（需要浏览器剪贴板权限）

也就是 必须支持外界键盘?
我一开始用ios手机试了下,没办法自动呼出虚拟键盘
