### ISSUE TITLE
koko  runtime error: integer divide by zero

### ISSUE THREAD

**Issue by invincibluke** [jumpserver/jumpserver#4056]
[简述你的问题]

##### 问题复现步骤
1. docker 运行的koko,  会不定时重启，查看日志可看到

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/34088075/83371428-0ab26580-a3f5-11ea-8779-11e62bdfb82e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
终端设置-资产分页每页数量选项，建议先选择 `自动 `选项。该问题是由于数据库分页处理不当，造成的问题。
