### ISSUE TITLE
多用户linux VNC设置

### ISSUE THREAD

**Issue by luxutao** [jumpserver/jumpserver#4060]
[简述你的问题]
是否支持不同用户登录资产时使用不同的vnc端口？

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.8
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他
使用单个端口设置，多用户登录时使用的都是资产中的唯一vnc端口，好像也不支持范围设置，有没有办法可以让不同的用户登录资产时，使用跟当前用户对应的端口进行登录，这样桌面之间的环境是相互隔离的。

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@luxutao jumpserver没办法知道你的端口对应啥用户呀，你得先指定这个对应

**Comment by luxutao** [comment]
@wojiushixiaobai 确实，看来本身是没有这个功能了
