### ISSUE TITLE
无法正确对数据库应用进行授权

### ISSUE THREAD

**Issue by leocd** [jumpserver/jumpserver#4061]
[简述你的问题]
权限管理模块下，数据库应用创建授权规则时，需要选取系统用户，但无法拉取资产管理中的系统用户；应用管理中的创建数据库应用没有添加系统用户的地方。

##### 使用版本
1.6

##### 问题复现步骤
1. 打开应用管理---数据库应用---创建数据库应用，页面无添加系统用户选项
2. 打开权限管理---数据库应用---创建授权规则，系统用户为必填选择项，但无法拉取到任何内容

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7478643/83471156-8cb69300-a4b6-11ea-9378-d97f846081b8.png)

![image](https://user-images.githubusercontent.com/7478643/83471142-7f99a400-a4b6-11ea-8e0a-5ac5cee4dbc3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@leocd 系统用户，协议选择 mysql 即可

**Comment by leocd** [comment]
> 议选择 mysql 即可

建了一个测试例子以便更好的传达要表述的意思
![image](https://user-images.githubusercontent.com/7478643/83497528-30229a80-a4ed-11ea-838d-203709fc77be.png)
![image](https://user-images.githubusercontent.com/7478643/83497593-44669780-a4ed-11ea-97d2-f13fd94c0606.png)

**Comment by wojiushixiaobai** [comment]
@leocd 资产管理-系统用户-新建系统用户，协议选择 mysql ，然后授权选择该用户

**Comment by leocd** [comment]
@wojiushixiaobai 好的，已解决，感谢！
