### ISSUE TITLE
内部资产使用非22端口时, web终端和FTP都无法使用

### ISSUE THREAD

**Issue by hsxiaoma** [jumpserver/jumpserver#4062]
## 问题

内部资产使用非22端口时(如: 5000), web终端和FTP都无法使用

## 使用版本
1.5.8

> 在资产管理中, 协议组选择 ssh 端口也指定为: 5000.

**Comment by wojiushixiaobai** [comment]
@hsxiaoma 确定你手动可以正常连接，这边测试可以正常使用

**Comment by zhengweisk** [comment]
我也遇见了这个问题 。非22的ssh主机 1个都连接不上
