### ISSUE TITLE
配置https访问，在login.html，表单提交通过F12 可以清晰看到是明文

### ISSUE THREAD

**Issue by Michael754267513** [jumpserver/jumpserver#4065]
[简述你的问题]
配置https访问，登入处，账号密码均是明文

##### 使用版本
1.5.6-2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

谷歌浏览器，打开登入页面，按F12, 输入账号密码，点击登入，在F12弹出的选项框里面选择 network，
在login post提交URI 里面，有个from data 显示的username password 均是明文，

##### 其他
有没有在不改动后端代码的同时，在前段HTML 进行处理，在from提交的时候不显示，或者显示为密文？

[注:] 完成后请关闭 issue

**Comment by mago960806** [comment]
https的加密是在传输链路中生效的，你手持合法的证书去看解密后的明文信息有何意义？

**Comment by Michael754267513** [comment]
post提交的时候，是明文的，这个能在前段提交的时候进行加密，在显示的时候也是密文，在后端在进行解密

**Comment by mago960806** [comment]
你这个叫做表单加密，比如表单的password字段进行md5计算，然后后端对比md5值判断密码是否正确。但当有https的情况下，只有你本机和服务器能解密https里的信息，中间人是不可能可以获取到数据的。那你这个加密到底是防什么呢？

**Comment by Michael754267513** [comment]
安全部门要求配置https，在表单提交也是密文的，这个在修改了部分代码已经实现。感谢耐心解答！
