### ISSUE TITLE
ldap登录报错 module 'ldap' has no attribute '_trace_level'

### ISSUE THREAD

**Issue by zmleasy** [jumpserver/jumpserver#4068]
[简述你的问题]

##### 使用版本
[Jumpserver版本 Version 1.5.9-2 GPLv2.]

##### 问题复现步骤
1. [ldap登录报错]
![image](https://user-images.githubusercontent.com/25140849/83588912-fe5d1280-a584-11ea-9a35-78d254947b4c.png)
报错日志：2020-06-03 09:54:06 [ldap ERROR] Authentication failed (Unknown): module 'ldap' has no attribute '_trace_level'

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
