### ISSUE TITLE
对资产树节点授权的优化建议

### ISSUE THREAD

**Issue by zjcnew** [jumpserver/jumpserver#4072]
[简述你的问题]
有这样的需求，在对根节点Default进行授权后
![企业微信截图_20200603181135](https://user-images.githubusercontent.com/22335594/83624878-c88c4e00-a5c5-11ea-9c84-eacc096c462a.png)
又会因为某个单独的节点或某个单独的服务器，排除这个授权，比如这里的数据库跳板机节点，因为是Linux服务器帐号授权，而这里Windows服务器不适合。
![企业微信截图_20200603181258](https://user-images.githubusercontent.com/22335594/83624973-de9a0e80-a5c5-11ea-9c89-7f9b27c99e6a.png)
我仅针对这个节点或服务器直接删除这个授权后，发现根节点的授权随着一起被全部删除。
![企业微信截图_20200603181417](https://user-images.githubusercontent.com/22335594/83625211-291b8b00-a5c6-11ea-8f00-39cc441e424d.png)
所以我希望有这样一个授权的优化，删除单独的某个节点授权而不继承上层的授权。
##### 使用版本
1.5.8

**Comment by Martwu** [comment]
感觉还是建议你直接把windows跟Linux分开成defaults下的两个大组。
