### ISSUE TITLE
./configure: line 13283: syntax error near unexpected token `AVCODEC,' ./configure: line 13283: `    PKG_CHECK_MODULES(AVCODEC, libavcodec,, have_libavcodec=no);'

### ISSUE THREAD

**Issue by superHuang476** [jumpserver/jumpserver#4075]
[简述你的问题]

##### 使用版本
Version 1.5.9

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/34533975/83633267-40ad4080-a5d3-11ea-8bda-6e0d59235645.png)

**Comment by superHuang476** [comment]
---问题复现
(py3) [root@localhost opt]# autoreconf -fi && \
./configure --with-init-dir=/etc/init.d && \
make && \
make install

**Comment by wojiushixiaobai** [comment]
@superHuang476 请说明系统，请参考视频
