### ISSUE TITLE
Web Terminal连接到Windows服务器后剪贴版异常

### ISSUE THREAD

**Issue by zjcnew** [jumpserver/jumpserver#4076]
##### 问题
使用Web Terminal连接到Windows服务器后，QQ、微信，输入法等常规截图/截屏工具粘贴功能均失效。

##### 版本
1.5.8

**Comment by ibuler** [comment]
windows里面的，还是外面使用的

**Comment by zjcnew** [comment]
外面，开启浏览器支持剪贴板复制功能，截图工具都失效了。
