### ISSUE TITLE
复制粘贴命令可以使跳板机命令过滤无效

### ISSUE THREAD

**Issue by FreezeJ** [jumpserver/jumpserver#4080]
[简述你的问题]
跳板机命令过滤无效

##### 使用版本
Jumpserver 1.5.8
CentOS release 6.8 (Final)

##### 问题复现步骤
 在web或terminal连接跳板机时，由于设置了命令过滤，输入违规命令确实会被禁止。
**但是**鼠标选择右键复制这个命令，重新粘贴后修改（如中间加一个空格），这个命令就可以被执行了，没有被过滤掉。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26806873/83730952-5c205600-a67c-11ea-8bb3-53189d31414f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
koko 处理解析命令需要优化
