### ISSUE TITLE
jumpserver在数据库添加一条机器数据,web端不是实时获取么？

### ISSUE THREAD

**Issue by scjianlin** [jumpserver/jumpserver#4085]
[简述你的问题]
我在jumpserver数据库添加一条机器数据（在assets_asset表添加1条机器数据，在assets_asset_nodes表中增加和node关联数据），然后在web端查看和数据库的数据不一致。
1.数据的count：
![image](https://user-images.githubusercontent.com/25558117/83961129-c9252d00-a8c2-11ea-9d63-345c52d70616.png)

2.web端node的count:
![image](https://user-images.githubusercontent.com/25558117/83961151-f540ae00-a8c2-11ea-8a5e-ceaae4679be0.png)

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
jumpserver == 1.5.9

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不能直接添加，是有缓存的，点击一下节点上的刷新按钮就行
