### ISSUE TITLE
登陆日志只有3个月的

### ISSUE THREAD

**Issue by 787771075** [jumpserver/jumpserver#4087]
[简述你的问题]

登录日志只有3个月的,但是其他日志保留了所有的
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.2-2 GPLv2.
##### 问题复现步骤
1. 系统设置里会话保留时长是9999天
2. 操作回放能看到1年前的操作
3. 数据库里查,其他日志都有1年前的记录
4. 只有用户登录日志只有3个月的记录(比如今天6月9,数据库里最早的记录就是3月10)

##### 具体表现[截图可能会更好些,最好能截全]
![A 0I}}`1 Z@M9_ _64GC}I](https://user-images.githubusercontent.com/31592492/84103198-f39ef380-aa44-11ea-9f05-f809962dfc06.png)
![H$P{ 8FCE1E`(F0 YA_L@MP](https://user-images.githubusercontent.com/31592492/84103206-fac60180-aa44-11ea-8f17-8845a55e2316.png)
![RK)X}${1DSGLU906XMNMDVB](https://user-images.githubusercontent.com/31592492/84103211-fdc0f200-aa44-11ea-8eb7-1a1be704dd44.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by 787771075** [comment]
![A 0I}}`1 Z@M9_ _64GC}I](https://user-images.githubusercontent.com/31592492/84103227-0b767780-aa45-11ea-9878-73f3425f2f09.png)

**Comment by ibuler** [comment]
设置 LOGIN_LOG_KEEP_DAYS 配置，默认是90天

**Comment by 787771075** [comment]
这个具体在哪个配置文件改呢?

**Comment by ibuler** [comment]
config.yml

**Comment by 787771075** [comment]
我看示例里面没有写这个参数,哪里能看到完整的参数列表吗?

**Comment by ibuler** [comment]
所有配置 见 https://github.com/jumpserver/jumpserver/blob/master/apps/jumpserver/conf.py#L122

**Comment by 787771075** [comment]
好的,感谢
