### ISSUE TITLE
JumpServer 通过web终端ssh服务器很慢 有时候超过15s

### ISSUE THREAD

**Issue by codech** [jumpserver/jumpserver#4089]
[简述你的问题]

##### 使用版本
1.5.9

##### 问题复现步骤
JumpServer 通过web终端ssh服务器很慢 有时候超过15s

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/35618896/84138502-f0c1f400-aa80-11ea-9e1f-d98417ed44d5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by xionghui** [comment]
检查你的系统用户是用密码还是私钥登录。如果采用私钥登录，把密码清空。
