### ISSUE TITLE
ESC退出全屏模式和vi编辑模式的ESC键冲突

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#4091]
[简述你的问题]
在luna页面登录远程服务器，然后选择rdp方式登录，发现进入全屏模式之后vi编辑文件，然后按ESC退出编辑模式，结果导致退出全屏模式，但是没有退出文本编辑模式。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.5.9-2 GPLv2
##### 问题复现步骤
1. [步骤1]点击web终端，然后点击需要连接的服务器，选择rdp方式登录系统
2. [步骤2]centos7.8 2003 图形桌面模式 输入账户和密码完成后，选择视图-全屏显示，通过vi 打开需要编辑的文件，编辑完成后按ESC退出编辑模式，但是却退出了页面全屏，并没有退出文件编辑模式。已经影响了全屏模式下的正常工作，希望能给一个解决方法。谢谢！

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是需要优化的功能，调研一下是否可以支持 @orangemio

**Comment by orangemio** [comment]
F11 可以退出全屏模式

**Comment by elite8** [comment]
你好，这个F11全屏模式，是在浏览器登录luna界面之后手动开启的是吗?不能做到在luna界面点击全屏模式设置成自动变为F11开启吗？请百忙之中给予答复，谢谢！
















在 2020-06-28 15:00:29，"Orange" <notifications@github.com> 写道：

F11 可以退出全屏模式

**Comment by orangemio** [comment]
> 你好，这个F11全屏模式，是在浏览器登录luna界面之后手动开启的是吗?不能做到在luna界面点击全屏模式设置成自动变为F11开启吗？请百忙之中给予答复，谢谢！ 在 2020-06-28 15:00:29，"Orange" <notifications@github.com> 写道： F11 可以退出全屏模式 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

F11和ESC都可以退出全屏模式

**Comment by elite8** [comment]
你好，可能没有描述清楚我的意思，我通过luna页面，调取rdp或者vnc登录centos服务器，登录服务器点击全屏，之后通过vim 编辑文件退出的时候用到了ESC键，但是这个键是退出全屏模式，因此会导致没有退出vim编辑模式。再次在非全屏模式下按ESC才能退出编辑模式，这个问题已经被我们这边的开发反应多次了。
       我现在只能是折中的方法先用F11全屏浏览器进入到luna页面，然后右键打开新窗口的方法开启服务器全屏模式，并且ESC退出vim编辑文件不会退出浏览器全屏。但这毕竟多了一步操作，作为开发他们自然觉着用着不习惯。
















在 2020-06-28 22:41:45，"Orange" <notifications@github.com> 写道：

你好，这个F11全屏模式，是在浏览器登录luna界面之后手动开启的是吗?不能做到在luna界面点击全屏模式设置成自动变为F11开启吗？请百忙之中给予答复，谢谢！ 在 2020-06-28 15:00:29，"Orange" notifications@github.com 写道： F11 可以退出全屏模式 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

F11和ESC都可以退出全屏模式

**Comment by orangemio** [comment]
想了一下，没办法绕过. 这个ESC快捷键是Chrome规范定义的，我拦截之后会影响其正常退出流程。

**Comment by elite8** [comment]
另外，请问一个事情，我现在遇到一个问题，我在xrdp登录centos系统之后，用vim编辑文件在里面输入小写英文字母没有问题，但是如果按了capslock转换成大写之后，在编辑模式下输入的内容依然是小写字母。如果按住shift+字母，输入的就是大写字母。还有什么可以解决的办法吗？
        在vnc方式登录的时候就不会出现大小写不能切换的问题。
















在 2020-06-29 00:32:59，"Orange" <notifications@github.com> 写道：

想了一下，没办法绕过. 这个ESC快捷键是Chrome规范定义的，我拦截之后会影响其正常退出流程。

**Comment by ibuler** [comment]
https://stackoverflow.com/questions/21279174/prevent-esc-from-exiting-fullscreen-mode

这个的确是做不到的，ESC是作为浏览器的API，优先于 dom捕捉onKey事件的

**Comment by mathsyouth** [comment]
Control+C 可以将代替 Esc 将 Vim 从 insert 模式切换到 normal 模式

**Comment by MaqingOnes** [comment]
可以在普通模式
inoremap jk <Esc>
这样就不需要esc退出了  每次在insert模式中连按 jk 直接跳回普通模式
