### ISSUE TITLE
 系统用户删除单个资产列表后无法正常显示

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#4094]
[简述你的问题]
资产管理-系统用户-资产列表- 删除资产后无法正常显示

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.8-2 GPLv2
##### 问题复现步骤
1. [步骤1]
打开系统用户-资产列表 
2. [步骤2]
删除资产列表内的任意资产
##### 具体表现[截图可能会更好些,最好能截全]
![add-test](https://user-images.githubusercontent.com/28751302/84344028-465ee380-abdc-11ea-8530-dd52ae8bc629.png)
![has](https://user-images.githubusercontent.com/28751302/84344029-4828a700-abdc-11ea-89db-3d56c2f807a4.png)
![noall](https://user-images.githubusercontent.com/28751302/84344034-4a8b0100-abdc-11ea-9063-615f70b132ef.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
刷新一下看看

**Comment by chinazzb** [comment]
> 刷新一下看看
chrome version:  83.0.4103.97
firefox version: 77.0.1
1、已清空chrome缓存。
2、更换firefox浏览器还是无法显示。

**Comment by ibuler** [comment]
还有一个可能，这个系统用户是不是动态系统用户，如果是动态的，则需要关联用户才行
