### ISSUE TITLE
二级搜索无法使用

### ISSUE THREAD

**Issue by agbt** [jumpserver/jumpserver#4097]
[简述你的问题]
提示：输入资产ID直接登录，二级搜索使用 // + 字段，如：//192 上一页：b 下一页：n
Q: ssh登陆终端后，二级搜索可否是对第一次搜索结果的过滤；或者是对二级目录的过滤

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7.2  &  1.5.9.2
##### 问题复现步骤
1. 先加入大量host，加入10条
2. 使用xshell连接终端
3. 首次连接时，当总的主机数在xshell 终端无需翻页时（每页行数>10），二级搜索为对第一次搜索结果的过滤。
4. 任何一个连接xshell后出现主机列表需要翻页的情况(每页行数<10)，则二级搜索和一级搜索结果完全相同。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/30456120/84415466-65459000-ac45-11ea-9739-f9536a99367a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@LeeEirc 确认一下
