### ISSUE TITLE
无法确定是否升级成功，除了页面右下角这个版本信息外，还有什么地方可以检查版本

### ISSUE THREAD

**Issue by dukong** [jumpserver/jumpserver#4099]
[简述你的问题]
按照官方文档https://docs.jumpserver.org/zh/master/admin-guide/upgrade/other/
使用./jmsctl.sh upgrade进行快速安装升级的时候，提示：1.5.9 已是最新版本，但是管理页面右下角显示：Version 1.5.5-2 GPLv2.
不清楚到底升级有没有成功。请问除了页面右下角这个版本信息外，还有什么地方可以检查版本？

##### 使用版本
1.5.5-2或者1.5.9

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
使用极速安装的才可以使用脚本的 upgrade 功能，而不是你部署完成后再下载 setuptools 工具升级。你的顺序搞错了。

你现在需要升级，请使用正常升级

**Comment by dukong** [comment]
> 
> 
> 使用极速安装的才可以使用脚本的 upgrade 功能，而不是你部署完成后再下载 setuptools 工具升级。你的顺序搞错了。
> 
> 你现在需要升级，请使用正常升级

1.5.5-2版本是极速安装的。

**Comment by wojiushixiaobai** [comment]
@dukong 请使用手动升级，使用setuptools安装的才支持 脚本自动升级功能
