### ISSUE TITLE
juser app 用户组编辑存在小的异常

### ISSUE THREAD

**Issue by qils** [jumpserver/jumpserver#411]
![error1](https://cloud.githubusercontent.com/assets/13659718/25061600/d1910b7c-21ec-11e7-89e6-bbc8dc820dd7.png)

如果大于等于1， 每次对用户组编辑的时候必须要修改用户组名， 如果只是大于1，在对组名修改时， 修改的组名在数据表中和另外一个组名相同时，源码下面在调用save（）保存记录时触发UserGroup模型中组名唯一异常，这个异常没有被捕获。

**Comment by ibuler** [comment]
新版本修复
