### ISSUE TITLE
通过ldap导入用户提示找不到用户组字段

### ISSUE THREAD

**Issue by watson6** [jumpserver/jumpserver#4111]
[简述你的问题]
通过接口导入用户，提示group字段不存在，查看代码发现是在导入用户过程中，使用了错误的组字段信息。

##### 使用版本
1.5.8
##### 问题复现步骤
curl --location --request POST 'https://jump.cn/api/v1/settings/ldap/users/import/' \
--header 'Authorization: Token 2d4f9d68ac81f6bd9667ef9c2' \
--header 'Content-Type: application/json' \
--data-raw '{"username_list":["zhuxi"]}'
返回错误信息
{
    "errors": [
        {
            "zhuxi": "Invalid field name(s) for model User: 'group'."
        }
    ]
}
+++++++++++++++++++++
apps/users/models/user.py 模型文件里面对应的字段是groups
    groups = models.ManyToManyField(
        'users.UserGroup', related_name='users',
        blank=True, verbose_name=_('User group')
    )
+++++++++++++++++++++
具体重现代码里面，在创建用户过程中提交了什么样的数据，打印看具体用户信息
apps/settings/api.py 在这个文件里面打印出导入数据的实际的内容是
235     def post(self, request):
236         try:
237             users = self.get_ldap_users()
238             print(users)
239         except Exception as e:
240             return Response({'error': str(e)}, status=401)
通过日志获取到的用户数据是
[{'username': 'zhuxi', 'name': '朱熙', 'email': 'leonie@jump.cn', 'groups': '总经办'}]

+++++++++++++++++++++
再次验证直接在程序里面构建一个用户数据
apps/settings/api.py 
235     def post(self, request):
236         try:
237             users = self.get_ldap_users()
238             users = [{'username': 'zhuxi', 'name': '朱熙', 'email': 'leonie@jump.cn', 'groups': '总经办'}]
239             print(users)
240         except Exception as e:
241             return Response({'error': str(e)}, status=401)
再次触发导入用户的功能
接口报错提示
{
    "errors": [
        {
            "zhuxiaoxi": "Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead."
        }
    ]
}

##### 其他

[注:] 完成后请关闭 issue

**Comment by watson6** [comment]
1.5.8 的bug到了2.2.0 还没修复好，这太不给力了，明显的bug完全可以重现。通过接口没法导入用户，这个接口就相当于费了。 @BaiJiangJie  @ibuler

**Comment by ibuler** [comment]
> 1.5.8 的bug到了2.2.0 还没修复好，这太不给力了，明显的bug完全可以重现。通过接口没法导入用户，这个接口就相当于费了。 @BaiJiangJie @ibuler

目前不支持导入组了所以映射字段里不要有groups
