### ISSUE TITLE
jumpserver-1.5.9 配合 CAS-5.3 实现单点登陆时,jumpserver 退出 logout CAS 问题

### ISSUE THREAD

**Issue by chenjisheng** [jumpserver/jumpserver#4112]
[简述你的问题]
jumpserver-1.5.9 + CAS-5.3 单点登陆

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.9
##### 问题复现步骤
1. 配置文件config.yml: CAS_LOGOUT_COMPLETELY: True
2. 重启服务后退出 jumpserver,服务异常

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26665677/84761224-b9f95a00-affb-11ea-90bf-73909af2dac9.png)
源代码: apps/authentication/views/login.py 两行注释需要取消
![image](https://user-images.githubusercontent.com/26665677/84761299-d5fcfb80-affb-11ea-98c3-2f6d9a7ee56a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chenjisheng 这里的逻辑判断没有问题阿，如果设置了CAS，则返回 CAS 退出 url 地址
