### ISSUE TITLE
感觉这个页面显示不舒服

### ISSUE THREAD

**Issue by MaxGaius** [jumpserver/jumpserver#4119]
[简述你的问题]
![image](https://user-images.githubusercontent.com/51019831/85105407-11d2d380-b23d-11ea-93e9-7ebec6849523.png)
命令记录栏应该更宽些

##### 使用版本
[2.0.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
正在对表格宽度做整体调整，感谢建议。

**Comment by ibuler** [comment]
已处理
