### ISSUE TITLE
请问如何修改数据库地址

### ISSUE THREAD

**Issue by sakufo** [jumpserver/jumpserver#412]
由于服务器原来，我迁移了数据库。现在老数据库已经连不上
请大神指教在Jumpserver的哪个配置文件可以修改数据库连接地址，谢谢。

**Comment by sakufo** [comment]
找到，在Jumpserver.conf内修改。但发现一个bug,数据库连接地址好象不能用localhost，否则服务无法启动

**Comment by qils** [comment]
可以查看下你的系统/etc/hosts 文件里面是否有对localhost 做解析, 一般解析都是127.0.0.1的地址

**Comment by ibuler** [comment]
和你的数据库授权有关系
