### ISSUE TITLE
jumpserver 2.0.0版本Nginx升级ssl文档不够清晰问题(容器版安装)

### ISSUE THREAD

**Issue by mylanvv** [jumpserver/jumpserver#4120]
[简述你的问题]
jumpserver 2.0.0版本Nginx升级ssl文档不够清晰问题

##### 使用版本
jumpserver 2.0.0 (容器版安装)

##### 问题复现步骤
Nginx升级ssl文档不够清晰问题

####
文档地址：https://jumpserver.readthedocs.io/zh/master/admin-guide/proxy/
按照该地址的步骤修改，缺少一些步骤 (容器版安装)
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/85110068-ebb13180-b244-11ea-8762-13a59463abe2.png)
文档中是提示修改 vi /etc/nginx/conf.d/jumpserver.conf   在容器中  这个文件是不存在的，并且nginx.conf中 引用路径也是注释了

---------
从git clone 下来的配置  nginx.conf 在 Dockerfile/nginx/nginx.conf
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/85110419-798d1c80-b245-11ea-8bea-d45233dbe398.png)

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/85110683-d983c300-b245-11ea-9a16-691dd17f185f.png)

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/37101066/85110780-fddf9f80-b245-11ea-9201-24e4a0510f9d.png)

-----问题总结
  缺少一个容器部署升级ssl的文档

升级过程中大概遇到的问题
1、修改 Dockerfile/nginx/nginx.conf  发现不生效，因为这个配置 是在build镜像就复制进去了，怎么修改也没用的，  除非使用挂载去替换镜像内（个人觉得在docker-compose 挂载nginx配置更好）
2、docker-compose 缺少对应ssl的目录
3、整个步骤下来，如果不熟悉docker使用的来说  不容易部署

**Comment by wojiushixiaobai** [comment]
@mylanvv 你应该在外部单独部署 反向代理服务器，并不需要直接修改容器或者镜像

**Comment by ibuler** [comment]
里面的nginx只是用来处理代理到不同的组件，可以外挂一层，来处理ssl等其他问题
