### ISSUE TITLE
这个统计信息栏希望能统一风格.两边的风格能统一.谢谢!

### ISSUE THREAD

**Issue by MaxGaius** [jumpserver/jumpserver#4124]
[简述你的问题]
这个统计信息栏希望能统一风格.
##### 使用版本
[2.0.0]
##### 问题复现步骤
界面优化
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/51019831/85156887-47071200-b28d-11ea-863c-9449438b53b2.png)
[注:] 完成后请关闭 issue

**Comment by MaxGaius** [comment]
![image](https://user-images.githubusercontent.com/51019831/85157041-7b7ace00-b28d-11ea-9171-5171491fdcee.png)

**Comment by ibuler** [comment]
最后一个需要更多数据，所以没有用同一的风格，比如试讲，比如头像
