### ISSUE TITLE
core还需要redis吗

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#4127]
[简述你的问题]
在分布式部署文档中明确写出redis是给koko的，那2.0.0版本的core不使用redis了？
还有就是所有的koko都使用同一个redis，那koko就不能跨云跨地域部署了？

##### 使用版本
2.0.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
core 是必须有redis的, koko 的redis是可选的，redis可以用来共享会话
