### ISSUE TITLE
JumpServer 2.0  不支持LDAP 用户空格

### ISSUE THREAD

**Issue by liuyjishg** [jumpserver/jumpserver#4128]
[简述你的问题]
JumpServer 2.0之前是支持 LDAP用户有空格的，但升级到2.0后不支持了

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有更多信息吗？ 比如说日志，2.0 不曾更改这里的逻辑

**Comment by liuyjishg** [comment]
不好意思，我刚又重新验证了一下，是我搞错了，我写反了cn，2.0是支持ad 用户空格的。2.0界面比之前的版本确实要舒服一点。

**Comment by ibuler** [comment]
好的，那先关闭 issue了
