### ISSUE TITLE
websftp没有会话超时，会有不安全风险

### ISSUE THREAD

**Issue by xionghui** [jumpserver/jumpserver#4131]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
所有版本

##### 问题复现步骤
1. [步骤1]
web终端连接websftp到某个机器

2. [步骤2]
等待几天
依然可以操作

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
web sftp是对会话做校验的，只要通过浏览器登陆未退出，就一直可以操作。

**Comment by xionghui** [comment]
那应该像koko的ssh连接一样，有个超时时间。时间超时后，websftp自动中断。会话也应该多久没有操作自动断开。否则有安全风险。

**Comment by xionghui** [comment]
这个有什么计划和思路么？

**Comment by ibuler** [comment]
session 不过期，即使断开了，再刷新一下还是能穿的
