### ISSUE TITLE
终端怎么设置搜索资产忽略大小写

### ISSUE THREAD

**Issue by zhaozhuang-ti** [jumpserver/jumpserver#4132]
[简述你的问题]
终端怎么设置搜索资产忽略大小写

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
2.0.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/58674081/85270466-e99cdc00-b4ab-11ea-95fe-57b9704bb4eb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by zhaozhuang-ti** [comment]
![image](https://user-images.githubusercontent.com/58674081/85270809-72b41300-b4ac-11ea-9264-063c3a27ff93.png)

**Comment by ibuler** [comment]
这个功能待讨论
