### ISSUE TITLE
通过网域无法连接上Windows Server 2003资产

### ISSUE THREAD

**Issue by djy1121** [jumpserver/jumpserver#4135]
[简述你的问题]
Jumpserver通过网域连接Windows Server 2003资产，无法连接上，提示连接错误。
同样通过网域连接Windows Server 2016和2008的资产没有出现同样问题。

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.8

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![TIM截图20200623114126](https://user-images.githubusercontent.com/37651113/85358502-7eecae80-b546-11ea-9167-5fe2dd52391d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
需要查看 后台日志，尝试设置不同的 平台实时，因为不同的平台 选择使用不同的加密方式

**Comment by djy1121** [comment]
这个应该在哪查日志？

**Comment by binco** [comment]
same issue
