### ISSUE TITLE
希望能支持多TAB页功能

### ISSUE THREAD

**Issue by JusticeShi** [jumpserver/jumpserver#4136]
jumpserver2.0已经使用vue+element ui 前后端分离，应该是可以支持多tab页功能，目前系统每点击一个菜单之前的菜单就被覆盖了，希望系统可以优化多tab支持，让使用操作上可以更加便利

##### 使用版本
jumpserver 2.0.0

##### 问题复现步骤
1. 点击菜单，原菜单页面就被覆盖
2. 想查看之前的菜单数据，必须得重新点击之前的菜单，比如查询条件或者其他操作已经执行一半的化又要重新输入

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@orangemio 能做到缓存 一个页面吗

**Comment by ibuler** [comment]
讨论了一下，这个暂时不考虑了，因为有时候切换菜单可能是想重启请求数据
