### ISSUE TITLE
无法自动推送系统用户至资产

### ISSUE THREAD

**Issue by xh-78** [jumpserver/jumpserver#4137]
[简述你的问题]
不会自动推送系统用户至资产

##### 使用版本
JumpServer 版本2.0.0

##### 问题复现步骤
1. 创建一个系统用户,勾选用户名与用户相同以及自动推送
2. 创建一个jumpserver用户
3. 为新创建的用户授权资产并指定系统用户(步骤1创建的)

此时并不会向资产推送一个与新建用户相同用户名的系统用户

**Comment by woniuzhang** [comment]
版本2.0.2也有这样的问题

**Comment by huangy10** [comment]
2.4.3，还是这个问题。步骤略有不同

1. 创建一个系统用户,勾选用户名与用户相同以及自动推送
2. 为一个jumpserver用户组创建授权，并指定上一步创建的系统用户
3. 创建一个jumpserver用户，分配到这个组下。

此时并不会向资产推送一个与新建用户相同用户名的系统用户

**Comment by jym503558564** [comment]
升级到最新版本，最近几个版本都有优化自动推送系统用户。
