### ISSUE TITLE
安装koko的时候一直提示2020-06-24 23:55:50 [ERRO] POST http://10.10.8.111:18080/api/v2/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"} 2020-06-24 23:55:50 [ERRO] register access key failed

### ISSUE THREAD

**Issue by RalapZ** [jumpserver/jumpserver#4141]
[简述你的问题]
安装koko一直报错，2020-06-24 23:55:50 [ERRO] POST http://10.10.8.111:18080/api/v2/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}
2020-06-24 23:55:50 [ERRO] register access key failed
用docker模式以及源码安装都有这个错误

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
koko版本2.0.1

##### 问题复现步骤
1. 
2. [步骤2]

![image](https://user-images.githubusercontent.com/64999166/85523017-00246e00-b639-11ea-8750-4f590b063263.png)

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
注册KOKO失败 看样子是端口18080的问题

**Comment by ibuler** [comment]
解决了吗？查看一下 JumpServer  的日志

**Comment by hezhiqiang8909** [comment]
我也遇到这个问题了，想知道一下是如何解决的

**Comment by RalapZ** [comment]
版本问题，需要用指导里面的版本

**Comment by hezhiqiang8909** [comment]
问题已经解决，8080端口的问题
