### ISSUE TITLE
web terminal中windows機器鏈接時報錯502

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#4143]
版本：2.0
報錯截圖：
![錯誤2](https://user-images.githubusercontent.com/8511007/85588854-a7bf9180-b675-11ea-8e79-36b6ba411cb7.PNG)
![錯誤1](https://user-images.githubusercontent.com/8511007/85588887-adb57280-b675-11ea-9afa-0591c2f29585.PNG)

guacamole已啓動docker部署，nginx已配置guacamole，防火墻已關閉

**Comment by orangemio** [comment]
麻烦贴一下请求Response是什么

**Comment by gengkeye** [comment]
> 麻烦贴一下请求Response是什么

![image](https://user-images.githubusercontent.com/8511007/85819811-72b35c00-b7a7-11ea-87ef-b8ce61f1d996.png)

**Comment by ibuler** [comment]
是不是 guacamole 组件没有正常启动呢?
