### ISSUE TITLE
作业中心/批量命令   任务60秒超时，时间可否调整

### ISSUE THREAD

**Issue by tony3154** [jumpserver/jumpserver#4145]
[简述你的问题]

##### 使用版本
1.5.9

##### 问题复现步骤
大批量执行任务，超过60秒会自动中断
在60秒中断后，没有显示未执行任务的服务器

##### 其他

[注:] 完成后请关闭 issue

**Comment by tony3154** [comment]
这个超时时间是否可以增加一个调整的设置，并且提示出未执行的主机？

**Comment by ibuler** [comment]
由于批量任务是用户可以执行的，为了避免因为用户执行命令导致阻塞队列，所以限制了 60s，如果想修改，可以暂时通过修改文件完成，https://github.com/jumpserver/jumpserver/blob/master/apps/ops/tasks.py#L48

**Comment by tony3154** [comment]
收到，多谢
