### ISSUE TITLE
邮件设置里面，邮件密码无法保存

### ISSUE THREAD

**Issue by Passerby-Z** [jumpserver/jumpserver#4152]
[简述你的问题]
        邮件设置里面设置好服务器、账号、密码以后，点击提交、测试，可以正常接收邮件，看起来一切正常。但是当却换到【系统设置】以外的其他界面以后，再切换回邮件设置，点击测试就会报错，然后再次填写密码，点击提交、测试，又正常了，看起来它并没有保存邮箱的密码。

##### 使用版本
Version 2.0.1

##### 问题复现步骤
1. 正常设置邮件服务器、账号、密码；
2. 点击提交、测试，一切正常；
3. 切换到【邮件设置】以外的其他界面，或者退出登录；
4. 再次打开邮寄设置，点击测试，会有报错；
5. 重新填写密码，点击提交、测试，一切又看起来正常了。

**Comment by orangemio** [comment]
你点击提交之后已经保存到后台了，但是不会在前端展示出来。
