### ISSUE TITLE
koko编码问题，需要考虑GBK等

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#4158]
[简述你的问题]
koko 目前仅支持 UTF8 编码，有些服务器可能是 GBK编码，所以要支持一下

##### 使用版本
v1.5.9

##### 问题复现步骤
1. 服务器编码设置成 gbk
2. 新建文件名改成中文
3. ls 显示乱码

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
Duplicate of #4206
