### ISSUE TITLE
sftp log页面操作翻译

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#4160]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/40739051/85937282-b2f41500-b934-11ea-9bf4-bd2b45fa9515.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/jumpserver/commit/6e3369c9445c7b0c54cdd0df2a67f7bc26cb9685
