### ISSUE TITLE
数据库应用连接可视化Web版

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#4169]
## 需求 

支持 MySQL, Oracle, PgSQL  界面操作，替代 navicat

## 方案

- 方案1：实现  各种服务器代理，作为中转服务器，像我们现在 ssh 那样
- 方案2：Web 页面去操作，我们实现的是 客户端

方案1过于复杂，每种数据库都要实现，所以采用第二种。调研后发现一开源项目 OminiDB 支持，好像阿里云也是基于此二次开发的，详见 https://github.com/OmniDB/OmniDB

## 安排

双11之前发版，10月14号之基本功能都完成，可以提测

## 说明

放到 X-Pack 企业版中，社区版不再支持

**Comment by loganXugit** [comment]
能不能顺便增加Redis GUI 作为应用程序
