### ISSUE TITLE
增加一键推送按钮

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#4178]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
v2.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/commit/1d741371442d8cfe378c15e328f24dde26813757
