### ISSUE TITLE
SESSION_EXPIRE_AT_BROWSER_CLOSE

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#4179]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
v2.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/jumpserver/pull/4139

**Comment by qizai123** [comment]
@ibuler 是配置的问题吗？还是确实是bug，我在使用也遇到了这个问题
