### ISSUE TITLE
批量命令 菜单按钮没有联动显示或隐藏

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#4180]
[简述你的问题]
【v2.0】设置- 更新批量命令显示或隐藏，左侧菜单作业中心中的批量命令不会联动显示或隐藏，需刷新页面才能联动显示或隐藏

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/40739051/85939386-96ada380-b947-11ea-9dab-23d7b96946b8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/commit/f7c3a3ac3ba5ab476ef725dd5229efdadb77aaef
