### ISSUE TITLE
JMS 2.0.1版本系统用户推送问题

### ISSUE THREAD

**Issue by Gourds** [jumpserver/jumpserver#4185]
[简述你的问题]
多网域多服务器情况下，系统用户的授权规则改变后，无法成功全部推送，但没有成功的资产，手动推送就可以了
想了解
- 自动推送逻辑
- 是否可以添加手动选择节点批量推送功能

##### 使用版本
v2.0.1

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
已在计划中，感谢反馈

**Comment by woniuzhang** [comment]
v2.1.0 也有这样的问题，目前修复了吗？

**Comment by woniuzhang** [comment]
@Gourds 如何手动推送？

**Comment by Gourds** [comment]
> @Gourds 如何手动推送？
系统用户 -> 资产列表 -> 更多 -> 推送
