### ISSUE TITLE
登录认证是否支持yubikey

### ISSUE THREAD

**Issue by leoowu** [jumpserver/jumpserver#4187]
[简述你的问题]

jumpserver是否支持yubikey产品，企业版还是社区版本支持？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时没有计划支持，你们公司在使用这个产品吗？这是款硬件产品？

**Comment by levie-vans** [comment]
> 暂时没有计划支持，你们公司在使用这个产品吗？这是款硬件产品？

是一款硬件Key，支持动态密码

**Comment by 027xiatian** [comment]
安全等级高的公司，有这个需求

**Comment by ibuler** [comment]
已支持， yubikey 可以作为 passkey 使用

**Comment by zhourainsun** [comment]
请问这个yubikey产品咋配置
