### ISSUE TITLE
ssh登录命令带参数，使得登录堡垒机就直接打开参数指定的资产(shell会话)

### ISSUE THREAD

**Issue by orwithout** [jumpserver/jumpserver#4189]
[简述你的问题]
ssh登录堡垒机，允许带参数，使得登录堡垒机就直接抵达参数指定的资产（主机）（跳过按p后选择资产号码步骤）。
自然，也就可以达到允许传递命令到参数指定的资产（主机）（ssh远程执行命令）的功能。
一、例如：
**ssh myJumpUser@jumpserver "p;1"**
或者
**ssh myJumpUser@jumpserver "p;1;bash"**
自动选择1号资产，打开shell

**ssh myJumpUser@jumpserver "p;1;uname -a"**
显示1号资产的uname -a信息。

二、
不知道这类功能是否已经支持。在linux和windows的终端中使用以上命令，提示：
**No PTY requested.**

三、
在windows上不通过跳板机远程1号资产（主机），（ip为192.168.2.13）：

**C:\Users\asdf>ssh root@192.168.2.13 uname -a
root@192.168.2.13's password:
Linux OpenWrt 4.14.180 #0 SMP Sat May 16 18:32:20 2020 x86_64 GNU/Linux
C:\Users\asdf>**

可以正常打印出uname -a信息

##### 使用版本
Version 1.5.9-2

##### 问题复现步骤
[1]准备1台jumpserver；1台支持ssh登录的linux服务器；一台windows或linux终端电脑
[2]在linux或windows终端电脑中，打开命令行界面，使用以上相关命令。

**Comment by liulwx** [comment]
这个问题现在是已经有解决方案了么？

**Comment by orwithout** [comment]
像vs远程调试之类的功能，也会需要用到

**Comment by Conghuajidaner** [comment]
目前powershell还是不能通过加参数的方式直接登录指定资产

**Comment by jym503558564** [comment]
目前还不支持，请关系我们后续版本发布情况。

**Comment by Conghuajidaner** [comment]
期待




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月7日(星期三) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] ssh登录命令带参数，使得登录堡垒机就直接打开参数指定的资产(shell会话) (#4189)





 
目前还不支持，请关系我们后续版本发布情况。

**Comment by uzxmx** [comment]
如果你们是想自己通过terminal，每次能够自动选择资产的话，其实在Linux/Mac下通过 expect 脚本就可以实现。例如

```
expect -c 'spawn ssh -p 2222 user@host; expect "Opt>"; send "p\r"; expect "Opt>"; send "1\r"; interact'
```

Linux下，可能需要将 \r 换成 \n。

因为我平常可能要连接许多不同的ssh服务器，所以我结合fzf实现了快速选择ssh host的功能，[这儿](https://github.com/uzxmx/templates/blob/master/src/ssh_hosts.tpl)有常用的快速执行ssh命令的例子，解析的程序我使用Perl写的，在[这儿](https://github.com/uzxmx/dotfiles/blob/master/scripts/perl/ssh.pl)，感兴趣的，可以了解一下。

如果你们的jumpserver启用了MFA，[这儿](https://github.com/uzxmx/dotfiles/blob/master/bin/auto_mfa)是一个能够自动输入MFA的脚本，这样就能自动进入到资产了。

这种expect的方式，我觉得不适合CI/CD；因为我们的CI/CD（gitlab）是部署在jumpserver之外的，所以为了能够自动选择资产，我更改了 coco (koko）的一些代码，实现了自动选择资产，执行命令。

顺便说一下，这是我的[dotfiles](https://github.com/uzxmx/dotfiles)，里面还包含了许多其他方便的工具。

**Comment by uzxmx** [comment]
> 指定

如果是想在Windows下使用的话，强烈建议启用 Windows Subsystem For Linux，这样你能用到大量的Linux命令。

**Comment by Conghuajidaner** [comment]
OK,thanks you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] ssh登录命令带参数，使得登录堡垒机就直接打开参数指定的资产(shell会话) (#4189)





  
指定
  
如果是想在Windows下使用的话，强烈建议启用 Windows Subsystem For Linux，这样你能用到大量的Linux命令。

**Comment by qyvlik** [comment]
可以使用 v2.11.0 提供的 SSH 直连

https://docs.jumpserver.org/zh/master/about/change_log/#v2110

**Comment by qiulang** [comment]
@qyvlik  SSH ⼯具直连资产：ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP

如果我的资产服务器不是运行在22端口要怎么直连，比如我的机器运行在22227端口，我执行

`ssh qiulang@root@60.205.207.101:22227@192.168.1.16 -p 2222`

报错

未发现匹配的资产 60.205.207.101:22227

**Comment by qyvlik** [comment]
@qiulang 去掉端口。因为你在 jumpserver 中录入资产并设置权限时就已经指定了资产的登录端口。
所以你的直连命令应该是如下：

```
ssh qiulang@root@60.205.207.101@192.168.1.16 -p 2222
```

**Comment by qiulang** [comment]
@qyvlik 这个我试过，但是因为 60.205.207.101 这个ip 配了好几台机器，我们是通过端口区分哪一台机器，如果 我只输入 `ssh qiulang@root@60.205.207.101@192.168.1.16 -p 2222` 就会提示让我 ”选择其中一个资产登录“

但我的本意是想直接登录 22227这个端口对应的机器

**Comment by qyvlik** [comment]
@qiulang  那你得另外开 issues 问问官方怎么处理这种情况吧。

**Comment by qiulang** [comment]
好，谢谢

**Comment by qiulang** [comment]
@uzxmx 我也写了写expect脚本方便登录，但是就有一个问题，当我想从目标服务器下载文件时候没什么好办法，scp没法用，因为没法端口转发，用lrzsz 但是lrzsz 和expect脚本有冲突，调试了好久才发现 https://github.com/robberphex/iTerm2-zmodem

>This tool may also fail if you are using expect or rlogin as it expects a mostly-clean 8-bit connection between the two parties.

另外你的脚本expect prompt 可以再改写下，我用
`set prompt "(%|#|>|\\$ )"`

**Comment by orwithout** [comment]
ssh -J jumpuser@jumpserver:port username@server:port

**Comment by orwithout** [comment]
ssh 有 -J 、RemoteCommand、proxyCommand 等可选参数
ssh -J jumpuser@jumpserver:port username@server:port
https://man.openbsd.org/OpenBSD-6.2/ssh_config#RemoteCommand

**Comment by orwithout** [comment]
ssh 有 -J 参数：
ssh -J jumpuser@jumpserver:port username@server:port

proxyCommand 参数：
https://www.cyberciti.biz/faq/linux-unix-ssh-proxycommand-passing-through-one-host-gateway-server/

RemoteCommand：
https://www.bloglibre.net/2020/06/28/remotecommand-en-ssh/
https://man.openbsd.org/OpenBSD-6.2/ssh_config#RemoteCommand

不知道能不能有所帮助，我现在没有junpserver

**Comment by orwithout** [comment]
学习到 ssh 有 -J 参数：
ssh -J jumpuser@jumpserver:port username@server:port

proxyCommand 参数：
https://www.cyberciti.biz/faq/linux-unix-ssh-proxycommand-passing-through-one-host-gateway-server/

RemoteCommand：
https://www.bloglibre.net/2020/06/28/remotecommand-en-ssh/
https://man.openbsd.org/OpenBSD-6.2/ssh_config#RemoteCommand

不知道能不能有所帮助，我现在没有junpserver
