### ISSUE TITLE
连接windows过程中，上传文件大于35M就失败

### ISSUE THREAD

**Issue by garywu520** [jumpserver/jumpserver#4190]
[简述你的问题]
连接windows过程中，上传35M以内的文件成功。但若上传文件大于35M的文件就失败，错误如下：
An internal error has occurred within the Guacamole server, and the connection has been terminated. If the problem persists, please notify your system administrator, or check your system logs.
Guacamole服务器内发生内部错误，并且连接已终止。如果问题仍然存在，请通知系统管理员，或检查系统日志。

##### 使用版本
Docker V1.5.9  jms_all

##### 问题复现步骤
当上传的文件大小超过35M，上传到35M的时候，就会出现此错误。

##### 其他
**我的Nginx关于文件大小限制已经改为4096M，如下：**
```
    client_max_body_size 4096m;
    client_body_buffer_size 5m;
```

**我的Tomcat9已经取消了上传限制，如下：**
```
    <Connector port="8081" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443"
               maxPostSize="-1"
               disableUploadTimeout="true" />
```

我已经修改了如上配置，问题依旧。怎么办？

**Comment by dmanbu** [comment]
2.1.0 版本也具有同样的问题
