### ISSUE TITLE
xrdp登录centos服务器，vim编辑模式下不能自由切换大小写

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#4191]
[简述你的问题]
我luna页面通过xrdp登录centos系统之后，用vim编辑文件在里面输入英文字符大小写切换的问题。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.9
##### 问题复现步骤
1. [步骤1]
在luna页面通过xrdp登录centos系统之后，用vim编辑文件在里面输入小写英文字母没有问题，但是如果按了capslock转换成大写之后，在编辑模式下输入的内容依然是小写字母。
2. [步骤2]
如果按住shift+字母，输入的就是大写字母。并且关闭capslock之后，依然输入的还是大写字母，不能再切换回小写。
在vnc方式登录的时候就不会出现大小写不能切换的问题。

##### 其他

[注:] 完成后请关闭 issue

**Comment by scholarchen** [comment]
该问题解决了么
