### ISSUE TITLE
建议系统管理员权限分离

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4196]
[简述你的问题]
jumpserver作为一个运维审计系统，要完善权限分配和审计的功能，建议对系统账号进行三权分立，设置系统管理员、配置操作的和审计员（已有），admin权限过大，不利于管理和审计。
系统管理员配置“系统设置”模块；
配置操作员为资产管理、用户管理、资产授权
审计员为审计用户的操作记录和系统管理员、配置操作员的操作记录

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
很好的建议，之前打算实现RBAC来着，重构耽搁了，再实现RBAC之前可以考虑增加一个 配置员

**Comment by aiaiduo** [comment]
> 很好的建议，之前打算实现RBAC来着，重构耽搁了，再实现RBAC之前可以考虑增加一个 配置员

嗯，好的，谢谢！
