### ISSUE TITLE
开启CAS认证后通过数据库里的用户密码仍可以登录

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4197]
[简述你的问题]
配置开启CAS认证后，用户的“用户来源”选择CAS后该用户仍可以通过数据库的密码登录堡垒机，建议开启CAS后就关闭本地认证，只留一种认证方式。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jp版本为： 2.0.0
##### 问题复现步骤
1. config.yml中启用CAS认证，用户的“用户来源”设置为CAS
2. 用户通过CAS和数据库中密码都可以登录堡垒机系统

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，JumpServer 中的认证是插件式的，只要有一个能登录就可以登录，之所以没有考虑关闭本地认证，是为了防止 CAS 出问题后，还可以用本地登录

**Comment by aiaiduo** [comment]
> 是的，JumpServer 中的认证是插件式的，只要有一个能登录就可以登录，之所以没有考虑关闭本地认证，是为了防止 CAS 出问题后，还可以用本地登录

那既然可以多种方式都可以登录的话那能否在“作业中心”-“登录日志”里加一列就是记录用户是采用什么方式登录的，比如“数据库”、“CAS”、“LDAP”等方式登录的，方便审计管理。
