### ISSUE TITLE
最新版启动jms一直报错

### ISSUE THREAD

**Issue by JIANGXIAOBAO** [jumpserver/jumpserver#4200]
通过官网配置后，使用./jms start -d启动一直异常
File "manage.py", line 23, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

我尝试升级Django和重新部署。但结果还是这个错误，目前环境都是在python3.6虚拟环境运行的，系统为ubutu18.04 LTS
安装参考：https://jumpserver.readthedocs.io/zh/master/install/step_by_step/

**Comment by ibuler** [comment]
应该是虚拟环境问题，提示很明显，Django 没有安装

**Comment by JIANGXIAOBAO** [comment]
实际已经安装指定版本，但依旧是这个错误
