### ISSUE TITLE
最新版终端管理问题咨询

### ISSUE THREAD

**Issue by JIANGXIAOBAO** [jumpserver/jumpserver#4203]
1、容器部署的最新版的Version 2.0.1 GPLv2，查看终端管理，没有显示相关的配置。这是改成了默认的本地存储吗？是否需要做相关配置，更新按钮是灰色的，无法点击。
2、未添加节点信息，打开文件管理报502。
![TIM图片20200630160610](https://user-images.githubusercontent.com/21222280/86100594-a665ed00-baeb-11ea-9f82-be5a999fdb13.png)

**Comment by ibuler** [comment]
你应该是点了 zhong终端列表上的按钮

![image](https://user-images.githubusercontent.com/17382885/86113362-c00f3080-bafb-11ea-9ed1-8e38c5764418.png)

**Comment by JIANGXIAOBAO** [comment]
不点击默认是没有数据的，另外访问文件管理直接报502，我是通过官网容器部署方式部署的，这个镜像是不是有问题，到容器里面看2222端口没有。
![image](https://user-images.githubusercontent.com/21222280/86192133-69e1d200-bb7b-11ea-8b2c-176fa0613974.png)

![image](https://user-images.githubusercontent.com/21222280/86192004-12dbfd00-bb7b-11ea-8e8b-76bb8cd00086.png)
