### ISSUE TITLE
资产详情中网域信息优化建议

### ISSUE THREAD

**Issue by youliyuan-fit2cloud** [jumpserver/jumpserver#4208]
[简述你的问题]
创建资产时，选择了一个网域，成功后，网域显示为ID，不能清晰显示对应哪个网域名称，建议修改为显示网域名称

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.0.1

##### 问题复现步骤
1. 创建资产时，选择了一个网域，成功后，网域显示为ID，不能清晰显示对应哪个网域名称，建议修改为显示网域名称

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/54612864/86197363-cea32980-bb87-11ea-83ee-7e965cbf0ab1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
后台已返回，前端未修改

**Comment by jym503558564** [comment]
https://github.com/jumpserver/lina/pull/219
