### ISSUE TITLE
用户 资产→协议组 里面的端口号是不是可以做成对用户隐藏不可见？

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#4214]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.0.1
##### 问题复现步骤
由于针对Windows资产rdp连接采用了特殊端口号，所以不希望用户知晓这个端口号，
能否在 用户→我的资产→Title→协议组→rdp/xxxx：只需要显示rdp协议即可，后面的端口号不显示。

##### 具体表现[截图可能会更好些,最好能截全]

![TIM图片20200701133257](https://user-images.githubusercontent.com/36059301/86206641-77a94e80-bb9f-11ea-88cb-32de361a802c.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有的用户需要，有的不需要，不能增加这么多设置开关啊，先代码中自己更改吧
