### ISSUE TITLE
dockers镜像不可用

### ISSUE THREAD

**Issue by Alecyrus** [jumpserver/jumpserver#422]
next.py里，用bash终端运行service.sh脚本。 可是docker镜像里，没有bash终端环境。

![image](https://cloud.githubusercontent.com/assets/13865581/25415977/d3379084-2a6d-11e7-9c05-4c437c66d967.png)
文档里已经提示这个错误了。

**Comment by ibuler** [comment]
0.3.2 的docker支持不是很好，新版本支持良好
