### ISSUE TITLE
普通用户登录提示 Server error occur,contact administrator

### ISSUE THREAD

**Issue by RalapZ** [jumpserver/jumpserver#4225]
[简述你的问题]
    普通用户登录提示Server error occur,contact administrator
![image](https://user-images.githubusercontent.com/64999166/86233534-23669480-bbc8-11ea-9b0f-8d0e64f12951.png)
  后面shu'r输入 /ui就能开打资源列表，出现异常时候，后台日志显示
![image](https://user-images.githubusercontent.com/64999166/86233612-43965380-bbc8-11ea-9c6f-2339cccbcdff.png)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jumpserver  版本2.0.1

##### 问题复现步骤
1. [步骤1]
创建普通用户，授权资源
2. [步骤2]
登录就显示以上问题
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
jumpserver api 应该没有更新到 2.0.1 吧

**Comment by RalapZ** [comment]
> jumpserver api 应该没有更新到 2.0.1 吧

都是2.0.1用快速安装的方法，应该是接口有问题

**Comment by RalapZ** [comment]
> jumpserver api 应该没有更新到 2.0.1 吧

![image](https://user-images.githubusercontent.com/64999166/86344833-5d4d9e80-bc8d-11ea-8a4e-62503372e43e.png)
是不是这个地方的调用名称不一致导致的？url里面谢的是asset-user，但是调用的是user-asset
![image](https://user-images.githubusercontent.com/64999166/86344902-73f3f580-bc8d-11ea-9071-dbbd19ad83cd.png)

**Comment by RalapZ** [comment]
@ibuler @xuxinwen

**Comment by jfrenhub** [comment]
我使用2.4.3 这个问题依旧
