### ISSUE TITLE
ldap导入的用户不能自己设置公钥吗？

### ISSUE THREAD

**Issue by gojuukaze** [jumpserver/jumpserver#4232]
ldap导入的用户个人信息里没有ssh公钥选项，怎么能让用户自己设置？

## 版本： 
* JumpServer 2.0.1

**Comment by chestarss** [comment]
+1

**Comment by ibuler** [comment]
设计的初衷在于，LDAP的用户因离职已经禁用了或移除了，但验证的登录的时候，使用公钥还能登录，这会引起问题，有更好的想法，欢迎交流

**Comment by gojuukaze** [comment]
嗯，看到那个issue了。
不太清楚公钥登录的认证机制，在验证前是否能加一步用户状态的确认？

**Comment by chestarss** [comment]
> @ibuler
> 嗯，看到那个issue了。
> 不太清楚公钥登录的认证机制，在验证前是否能加一步用户状态的确认？

赞同在公钥登录前check下用户状态来避免离职用户依然可以用公钥登录的问题

**Comment by guozilong110** [comment]
> 设计的初衷在于，LDAP的用户因离职已经禁用了或移除了，但验证的登录的时候，使用公钥还能登录，这会引起问题，有更好的想法，欢迎交流

 宁愿牺牲安全性,也需要公钥登陆

**Comment by xyziven** [comment]
jumpserver用户(无论本地还是ldap用户)应该需要一个“状态”标记（enable/disable），用以启用/禁用账号。这样，ldap用户也可以设置“状态”，通过定时同步机制，当发现ldap上用户不存在或者已经disable的情况下，将已经同步到本地的ldap用户标记为disable，禁止用户登录。这样，跟用户的登录认证方式就解耦了。

**Comment by wml3** [comment]
插一个和该问题相关的，就是接入LDAP后，本地用户，无法使用忘记密码功能去重置密码

**Comment by JadeQin** [comment]
什么时候LDAP用户能够用证书登录

**Comment by Xuejicha0** [comment]
重置并下载SSH密钥无效，不能通过终端命令行登录

**Comment by AchillesLiL** [comment]
不能一刀切了，这种选择是否需要这个功能，应该给用户选择

**Comment by ibuler** [comment]
下个版本放开，让用户自己关闭 public key 认证

**Comment by ibuler** [comment]
已还原 https://github.com/jumpserver/jumpserver/pull/6037
