### ISSUE TITLE
双机高可用环境创建用户后备机提示输入yes/no

### ISSUE THREAD

**Issue by pangqiss1986** [jumpserver/jumpserver#4235]
[简述你的问题]
我在尝试使用双机高可用，有一些问题想咨询下，谢谢
1、创建一个用户，主机使用xshell正常，第一次使用备机的IP登录需要输入个类似know_host 的yes/no，之后的登录就没有问题了，请问这个在哪个目录一直找不到
2、由于是高可用，默认都使用主机，所以redis主机和备机各一个独立的是否有影响？目前测试没问题，不知道redis的具体作用
3、官网koko提示需要使用同一个redis，我也是使用的主机备机各个独立的redis。之后把主机的kokodir/data/keys/目录同步到备机，在主机和备机的终端管理里面只有一个koko。但是主备机ssh正常，不知道这样是否合理
##### 使用版本
2.0.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/49937922/86425232-291ec000-bd17-11ea-94dc-3fac7dcb0eaa.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
### Redis作用

Api server redis有以下作用 

- 作为cache
- 作为celery任务broker
- 作为session存储
- 作为websocket的broker

koko的redis是可有可无的，如果部署多个 koko，并且需要实时监控，koko才需要 redis

**Comment by pangqiss1986** [comment]
> ### Redis作用
> API服务器Redis有以下作用
> 
> * 作为缓存
> * 作为芹菜任务经纪人
> * 作为会话存储
> * 作为websocket的经纪人
> 
> koko的redis是可有可无的，如果部署多个koko，并且需要实时监控，koko才需要redis
> 
> ## 快捷键
> Terminal注册会生成访问密钥，如果两个koko用同一个密钥，那么Api服务器会认为是同一个终端

非常感谢您的回复，我看官网是在负载均衡使用的会话保持。我的koko  access_key是同一个，但是第一次使用备机会有上面截图的提示

**Comment by pangqiss1986** [comment]
> ### Redis作用
> Api server redis有以下作用
> 
> * 作为cache
> * 作为celery任务broker
> * 作为session存储
> * 作为websocket的broker
> 
> koko的redis是可有可无的，如果部署多个 koko，并且需要实时监控，koko才需要 redis
> 
> ## Access key
> Terminal注册会生成 access key, 如果两个koko用同一个key, 那么 Api server会认为是同一个 terminal

感谢您的回复，我的koko access_key是同一个，但是第一次使用备机会有上面截图的提示

**Comment by ibuler** [comment]
这是正常的，如果走的vip，应该不会有这个问题
