### ISSUE TITLE
导入资产失败

### ISSUE THREAD

**Issue by wangtianshang** [jumpserver/jumpserver#4237]
[简述你的问题]

##### 版本： 1.5.9-2
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. 导入资产的时候  csv会会出现导入失败，有时候可以导入成功，这是怎么回事
2. [步骤2]

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新版本一直再优化 csv 导入，建议有时间升级到 2.0
