### ISSUE TITLE
WEB终端里的vim无法批量注释

### ISSUE THREAD

**Issue by jllbc** [jumpserver/jumpserver#4238]
WEB终端打开服务器窗口，vim编辑文件时，无法批量注释。正常情况下，vim打开文件后，使用ctrl+v即可多选需要注释的行，然后，键入大写的I和#号，然后键入Esc即可多行注释，但是jumpserver的ctrl+v是被粘贴覆盖了！不止到这个问题有没有好的解决方案。感谢！

##### 使用版本
Version 1.5.6-101 GPLv2

##### 问题复现步骤
1. vim打开文件
2. 键入ctrl+v

**Comment by orangemio** [comment]
ctrl + v 被拦截成默认的粘贴快捷键了，以后可能会提供快捷建自定义的选项。

**Comment by jllbc** [comment]
> ctrl + v 被拦截成默认的粘贴快捷键了，以后可能会提供快捷建自定义的选项。

是的。非常感谢。

**Comment by charnet1019** [comment]
这个问题目前是否有快捷键设置了？
