### ISSUE TITLE
stmp service无法连接网络

### ISSUE THREAD

**Issue by JcQSteven** [jumpserver/jumpserver#424]
用./service restart重启服务后，在添加用户里要开启发送邮件，点击保存就会跳转页面提示
【network is unreachable】

error at /juser/user/edit/
[Errno 101] Network is unreachable
Request Method:	POST
Request URL:	http://192.168.31.112:8000/juser/user/edit/?id=3
Django Version:	1.6
Exception Type:	error
Exception Value:	
[Errno 101] Network is unreachable
Exception Location:	/usr/lib/python2.7/socket.py in create_connection, line 571
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/jumpserver',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 26 Apr 2017 16:05:25 +0800

**Comment by ibuler** [comment]
smtp发送邮件失败
