### ISSUE TITLE
windows资产上G盘已上传好的文件自动消失

### ISSUE THREAD

**Issue by junit** [jumpserver/jumpserver#4240]
[简述你的问题]
windows资产上G盘已上传好的文件自动消失

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.1
##### 问题复现步骤
1.  通过luna登录windows资产，上传文件到G盘。
2. 同一用户通过luna登录其它windows资产，打开G盘，正常看到上一步上传的文件。
3. 在别的电脑上用其它用户登录任一windows资产，打开G盘，文件列表显示空。
4. 上传文件的原用户刷新G盘，文件列表显示空，文件已丢失。

##### 具体表现[截图可能会更好些,最好能截全]
当用户登录windows资产时，会在 /config/guacamole/drive/ 目录下创建该session的文件夹，上传的文件都在此目录中，当别的用户同一时刻登录windows任意资产时，/config/guacamole/drive/ 目录会生成并使用新的session文件夹，原session文件夹中的内容被清空。

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
上传挂载的目录是以用户区分的，不同用户之间无法共享数据。为了防止上传的文件占用大量磁盘空间，会话结束后，会删掉上传到目录的文件。如果需要共享，请尽可能上传后，复制到Windows资产的目录，而不仅仅只上传到挂载的目录。

**Comment by junit** [comment]
@LeeEirc 我在1.5.x版本升级之前是没有任何问题的

**Comment by vicentwu** [comment]
这个问题，当一个用户同时更新多台服务器的时候，原本可以共享这个上传的文件，但是当断开其中一个服务器连接，这个文件就自动删除了，那么我在另外一台服务器上就得再次上传该文件，有些许的困扰，是否可以弄一个删除时间频率设定，比如半个小时 一个小时候后自动删除，而不是根据用户会话的状态判定自动删除?

**Comment by junit** [comment]
@vicentwu 是的，以前的版本是没有这个问题的，我也是最近升级2.x才遇到，这是个BUG，非常困扰。

**Comment by wojiushixiaobai** [comment]
@junit 此问题是因为默认设置了 连接断开时清理上传文件
```
JUMPSERVER_CLEAR_DRIVE_SESSION=true
```
后续版本已经处理此参数

完整参数列表参考
https://docs.jumpserver.org/zh/master/admin-guide/env/
