### ISSUE TITLE
新版中如何获取用户登录跳扳机秘钥的密码

### ISSUE THREAD

**Issue by yanchaoguo** [jumpserver/jumpserver#4241]
Jumpserver2配置完成后使用 ssh -p2222 admin@myjumpserverip 是可以链接成功的 ，然后从个人用户信息里下载的ssh 秘钥导入到xshell登录老提示需要输入秘钥密码  请问密码从哪里获取呢

**Comment by ibuler** [comment]
JumpServer生成的密钥是没有密码的，如果提示输入密码，有可能是这个密钥文件的权限不对

```
# chmod 400 $KEY_FILE
```
