### ISSUE TITLE
我的之前是docker部署，版本是1.4.8，现在升级到2.0.1后权限管理中的终端管理的组件不显示在线，请问怎么处理？

### ISSUE THREAD

**Issue by mygitabc** [jumpserver/jumpserver#4243]
![图片](https://user-images.githubusercontent.com/47732194/86504702-85084800-bdee-11ea-80d3-ef9b08d73355.png)

**Comment by ibuler** [comment]
请检查 Koko和Guacamole是否依然有是否依然发心跳给 Api Server, api为 /api/v1/terminal/status/

**Comment by yuchunyun** [comment]
我也有这个问题。我使用的jumpserver/jms_all:latest镜像部署的，结果在页面上Guacamole显示不在线！
