### ISSUE TITLE
mysql应用授权无法显示mysql类型的系统用户

### ISSUE THREAD

**Issue by vision-ken** [jumpserver/jumpserver#4244]
[简述你的问题]
mysql应用授权无法显示mysql类型的系统用户。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
docker镜像：jumpserver/jms_all:2.0.1

##### 问题复现步骤
1. [步骤1]
进入资产管理->系统用户，新建系统用户：
- 名称：aaa
- 登录模式：自动登录
- 用户名：aaa
- 优先级：20
- 协议：mysql
- 自动推送：否
- 密码：<数据库密码>

2. [步骤2]
进入应用管理->数据库应用，新建数据库应用：
- 名称：bbb
- 类型：mysql
- 主机：xxx
- 端口：3306
- 数据库：xxx

3. [步骤3]
进入权限管理->数据库授权，创建数据库授权规则：
- 名称：ccc
- 数据库应用：bbb
- 系统用户：应该显示aaa用户，但是没有显示

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/24715266/86504940-7d966e00-bdf1-11ea-8f4e-89f395d5cd25.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/commit/85012d95584b77f81f5bda1fb6df4219b7505fdc#diff-0b46aa42a14956ab95141067e8c33229R53
已修复，暂未发布。
