### ISSUE TITLE
用户组添加用户时，如果不滚动列表到所添加的用户名，则无法添加，详情请看gif图

### ISSUE THREAD

**Issue by Jackxun123** [jumpserver/jumpserver#4246]
[用户组添加用户时，如果不滚动列表则无法添加]

##### 使用版本
[2.0.1]

##### 问题复现步骤
1. 随便选一个用户组
2. 在搜索框搜索用户，并鼠标左键或者回车选择
3. 直接提交不能正常添加，需滚动列表至添加用户后才可添加用户

##### 具体表现
![jumpserver_user](https://cdn.jsdelivr.net/gh/Jackxun123/ImageHosting/Upload/20200705173639.gif)

图片地址：
[点我看gif](https://cdn.jsdelivr.net/gh/Jackxun123/ImageHosting/Upload/20200705173639.gif)

**Comment by bigbird1985** [comment]
我们也碰到这个问题。

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/pull/155
