### ISSUE TITLE
系统用户只有KEY时 测试资产可连接性时会报错

### ISSUE THREAD

**Issue by 3dfxmax** [jumpserver/jumpserver#4247]
[简述你的问题]
在系统用户没密码 只有KEY存在时 测试资产可连接性会报错误

##### 使用版本
[请提供你使用的JumpServer版本 
2.0.1

##### 问题复现步骤

1.点选系统用户
2. 点选系统用户名称
3.测试资产可连接性

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/24647797/86543182-c283e700-bf4e-11ea-8230-84f662396db1.png)

##### 其他

另外发现汇入系统用户之后不会自动生成KEY 只能手动建立

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这应该是没有自动推送成功吧

**Comment by 3dfxmax** [comment]
> 这应该是没有自动推送成功吧，重新推送试试

感谢答覆

目前状况是这样子

这个帐号推送是显示有成功的 然后使用这个系统用户的User可以正常登入主机 就是测试资产可连接性的时候会出错

**Comment by 3dfxmax** [comment]
进一步测试发现 新建系统用户时 会自动产生一组key 与 password(内容是uid)
推送时会将key与password 一起推送到主机

由于我们主机的系统用户是也是使用LDAP验证 不存在本机passwd 中推送时会引发
FAILED! => {"changed": false, "msg": "usermod: user 'adminuser' does not exist in /etc/passwd\n", "name": "adminuser", "rc": 6}
所以我们有另外把系统用户的密码做清除好让系统用户成功推送

但在测试资产可连接性时就引发了问题

请问广兄对于这个情况有什么解决的办法吗?
