### ISSUE TITLE
koko与celery_ansible进程无法结束

### ISSUE THREAD

**Issue by qizai123** [jumpserver/jumpserver#4248]
[简述你的问题]
通过以下命令无法关闭程序：
./jms stop
./koko stop

##### 使用版本
程序版本：2.0.1
系统版本：centos7.4
python：python3.6

##### 问题复现步骤
./jms stop
![image](https://user-images.githubusercontent.com/33274304/86550402-d9d5cb00-bf74-11ea-9010-c37b8573c027.png)

jms手动关闭无效，使用kill -9 关闭，会自动生成新进程无法关闭
![image](https://user-images.githubusercontent.com/33274304/86550615-75ffd200-bf75-11ea-8dad-84ffffd00c0d.png)

./koko stop
![image](https://user-images.githubusercontent.com/33274304/86550504-1dc8d000-bf75-11ea-86c9-b06e14a73720.png)

**Comment by ibuler** [comment]
1. kill 的 pid不是celery的，因为监听了端口 8080, celery是不监听端口的， 这应该是 jms 进程在监测

2. koko 是 ./koko -s stop

**Comment by qizai123** [comment]
抱歉koko的关闭是个低级错误，感谢你的帮助。

另外我想使用systemctl来管理jms，但是在编写脚本的时候发现手动无法关闭jms，./jms stop后，依然有Python的8080监听，并且web访问正常，不知道这个该如何处理

**Comment by ibuler** [comment]
查看一下进程，应该是jms在保持，需要先结束 jms 进程，再kill 其它
```
# ps axu | grep 'python'
```

**Comment by qizai123** [comment]
感谢，解决了，将ps axu | grep 'python'查询到的所有进程号，一次性结束后，再次启动停止就正常了
