### ISSUE TITLE
centos 7 安装提示不支持

### ISSUE THREAD

**Issue by kevinzu007** [jumpserver/jumpserver#425]
安装jumpserver0.3.2 提示如下：
请务必先查看wiki https://github.com/jumpserver/jumpserver/wiki
支持的平台: CentOS, RedHat, Fedora, Debian, Ubuntu, Amazon Linux, 暂不支持其他平台安装.

详细信息如下：
--------------------------------------------------
环境：Centos 7 X64
           安装jumpserver 0.3.2 （tar.gz包）
提示信息如下：
[root@VT-16-3-199-ssh-b install]# python install.py 
请务必先查看wiki https://github.com/jumpserver/jumpserver/wiki
支持的平台: CentOS, RedHat, Fedora, Debian, Ubuntu, Amazon Linux, 暂不支持其他平台安装.

[root@VT-16-3-199-ssh-b install]# pwd
/opt/jumpserver/install
[root@VT-16-3-199-ssh-b install]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@VT-16-3-199-ssh-b install]# 
[root@VT-16-3-199-ssh-b install]# python -V
Python 2.7.5
[root@VT-16-3-199-ssh-b install]# 
[root@VT-16-3-199-ssh-b install]# uname -a
Linux VT-16-3-199-ssh-b.idc1.fdr 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kevinzu007** [comment]
centos 7 的输出是 “ centos linux”
版本号输出的也是 “ centos linux”，所以不能安装

**Comment by vincent927** [comment]
@kevinzu007 可以自己修改一下安装脚本，把centos linux加进去就好了
```
    @property
    def _is_redhat(self):
        if self.dist == "centos" or self.dist == "redhat" or self.dist == "fedora" or self.dist == "amazon linux ami" or self.dist == "centos linux":
            return True
```

**Comment by vincent927** [comment]
更好的方式是这样修改,以下是修改后的代码。
```
   def _is_centos7(self):
        if self.dist == "centos" or self.dist == "centos linux"  and self.version.startswith("7"):
            return True
```
```
    def check_platform(self):
        if not (self._is_redhat or self._is_ubuntu or self._is_centos7):
            print(u"支持的平台: CentOS, RedHat, Fedora, Debian, Ubuntu, Amazon Linux, 暂不支持其他平台安装.")
            exit()
```
修改这2个函数即可
