### ISSUE TITLE
数据库授权无法选取“系统用户”

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4252]
[简述你的问题]
在“资产管理”--“系统用户”里已新建协议为“mysql”的系统用户，但是数据库授权选择“系统用户”的时候找不到已新新建的系统用户

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.1
##### 问题复现步骤
1. 在“资产管理”--“系统用户”里已新建协议为“mysql”的系统用户
2. 在“权限管理”--“数据库授权”里创建数据库授权规则，“系统用户”下拉为“无数据”，无法选择系统用户

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/28044296/86575519-00fabf80-bfaa-11ea-8dfc-70c9fd41aace.png)
![image](https://user-images.githubusercontent.com/28044296/86575591-1ec82480-bfaa-11ea-9be2-1701016ba399.png)
![image](https://user-images.githubusercontent.com/28044296/86575640-31425e00-bfaa-11ea-8060-69b516fa83e9.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
关注 #4244
