### ISSUE TITLE
1.5.8 升级2.0.1后web界面无法访问

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#4253]
[简述你的问题]
1.5.8 升级2.0.1后web界面无法访问

##### 使用版本
2.0.1

##### 问题复现步骤
1. [步骤1] ./jmsctl.sh upgrade (这一步没更新git pull)
2. [步骤2] 访问web页面

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/28751302/86577881-82a01c80-bfad-11ea-9103-5efec9aedcef.png)

##### 其他
[jumpserver-nginx-conf.zip](https://github.com/jumpserver/jumpserver/files/4877953/jumpserver-nginx-conf.zip)

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
- ./jmsctl load_image 升级镜像

**Comment by chinazzb** [comment]
> * ./jmsctl load_image 升级镜像

![image](https://user-images.githubusercontent.com/28751302/86597118-e0446100-bfcd-11ea-9203-fa254c25e324.png)
我用的是极速安装。
![image](https://user-images.githubusercontent.com/28751302/86597368-2bf70a80-bfce-11ea-9b26-1ad1d10395d6.png)

可以看到登陆界面，输入账号密码进入后跳转至
![image]https://user-images.githubusercontent.com/28751302/86577881-82a01c80-bfad-11ea-9103-5efec9aedcef.png

**Comment by ibuler** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/upgrade/1.5.0/

2.0 升级添加了新组建 lina, 她是我们的前段项目，可以参考文档来升级
