### ISSUE TITLE
firefox 78无法显示日期，Chrome正常。

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#4254]
[简述你的问题]
firefox 78无法显示日期，Chrome正常。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
Firefox 78
![图片](https://user-images.githubusercontent.com/4084548/86689925-09024000-c03a-11ea-9c92-d69d242f1c83.png)

Chrome 83
![图片](https://user-images.githubusercontent.com/4084548/86690222-51b9f900-c03a-11ea-96de-d473cc17d5bf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/commit/dac04cfa61d9145867d6bfa26971f88369fbadf7

**Comment by bigbird1985** [comment]
> 
> 
> [jumpserver/lina@dac04cf](https://github.com/jumpserver/lina/commit/dac04cfa61d9145867d6bfa26971f88369fbadf7)

啥时候发布呀？

**Comment by bigbird1985** [comment]
> 
> 
> [jumpserver/lina@dac04cf](https://github.com/jumpserver/lina/commit/dac04cfa61d9145867d6bfa26971f88369fbadf7)

好像并没有修复？
我测试了2.0.2，还是没有显示日期，也无法正常选择日期，但是在点击了“此刻”以后，就可以正常选择日期了

**Comment by orangemio** [comment]
稍等我再检查一波
