### ISSUE TITLE
数据库应用，mysql 语法无法输入中文，copy进去也不支持。

### ISSUE THREAD

**Issue by kwz1993** [jumpserver/jumpserver#4262]
[简述你的问题]
数据库应用，mysql 语法无法输入中文，copy进去也不支持。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.7-2 

##### 问题复现步骤
1. [步骤1]
由于业务需要，使用堡垒机-数据库应用，想要输入中文字段，不支持。
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/62632544/86749246-aaf04f80-c06f-11ea-90a9-555a2c6d8892.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by qiyongxiao** [comment]
我也是无法输入中文

**Comment by ibuler** [comment]
已解决 https://github.com/jumpserver/koko/releases/tag/v2.1.0
