### ISSUE TITLE
CSRF 驗證失敗。已中止請求。

### ISSUE THREAD

**Issue by post707** [jumpserver/jumpserver#4263]
在k8s中部署，然后使用ingress代理，ingress配置HTTP访问登录正常，使用https配置登陆的时候就报禁止 (403)，CSRF 驗證失敗。已中止請求
如果使用http方式登陆后，在使用https访问是可以操作的，只有在验证用户的时候使用https就报错

想请教一下这是服务端的问题还是ingress配置问题， ingress的http和https配置之多了个证书，其他都一样。

##### 使用版本
[JumpServer版本 如 2.0.1 ]

**Comment by orangemio** [comment]
Ingress配置问题

**Comment by post707** [comment]
@orangemio 知道根本原因在哪里吗？

**Comment by orangemio** [comment]
建议去社区问一下其他成员是在K8S里面安装的。
