### ISSUE TITLE
Asset model update 不生效

### ISSUE THREAD

**Issue by luozhijunroy18** [jumpserver/jumpserver#4275]
[简述你的问题]
在2.0.1版本上，我在二次开发该项目，使用  num = Asset.objects.filter(id=id).update(cpu_cores=5) 这个执行， 没有报错， 返回的影响行数num不为1, 但是实际数据库却没有生效， 这是为什么？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.1

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
没有道理才对，你再研究一下吧

**Comment by luozhijunroy18** [comment]
后来我找到原因了， 是因为update 和 save 同时使用了，update 就不会生效， 谢谢！
