### ISSUE TITLE
用户授权资产不能及时更新

### ISSUE THREAD

**Issue by BaiJiangJie** [jumpserver/jumpserver#4288]
操作步骤：

1）创建节点(test)

2）节点添加资产(linux-node1)

3）节点授权，这个时候授权正常

4）在节点(test)下添加资产(linux-node2),web界面不会自动刷新。需要手动去更新jumpserver的系统用户，点击保存，授权才会生效。

更新系统用户后添加的资产就能在luna界面看到这些资产，没有更新就不能看到这些资产

2.0.1、1.5.9有这个问题。（南）

**Comment by ibuler** [comment]
尝试未能浮现
