### ISSUE TITLE
会话框表格宽度

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4296]
[简述你的问题]
用户自己设置表格宽度之后，能不能每次登录宽度就按照用户自己设置的显示

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.2
##### 问题复现步骤

![image](https://user-images.githubusercontent.com/44529247/87218595-daac9980-c386-11ea-8242-c11190cc5864.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个后续优化

**Comment by ibuler** [comment]
已优化处理了一波，请再看看

**Comment by jym503558564** [comment]
表格宽度已优化，现在显示比较友好，也可以自行拉宽某一列的宽度。
