### ISSUE TITLE
Jumpserver的API文档打开404

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#4298]
[简述你的问题]
jms 主程序debug已打开，重启进程，打开api文档404，浏览器页面：
“

Request Method: | GET
-- | --
http://192.168.51.208/core/api/docs
jumpserver.views.other.redirect_old_apps_view
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
”
具体见截图
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jumpserver2.0.2
##### 问题复现步骤
1. [步骤1]
打开debug
2. [步骤2]
浏览器出入  http://192.168.51.208/core/api/docs 出现404
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48144475/87229232-1ff9b700-c3d9-11ea-82f2-740f5d49fa4e.png)

![image](https://user-images.githubusercontent.com/48144475/87229277-6222f880-c3d9-11ea-9d3e-3f23c2cf608d.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
/api/docs/

**Comment by cuijianzhe** [comment]
thanks
