### ISSUE TITLE
请问动态用户是否会在机器上创建非授权规则的用户

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4301]
[简述你的问题]
发现了这个问题，请问是否为预期行为？

##### 使用版本
2.01

##### 问题复现步骤
1.创建两个用户AB
2.分别授权两个资产，资产1，资产2。使用同一个系统“动态”用户，ssh
3.在查看ssh的系统资产时，分别有A @ 1，A @ 2，B @ 1，B @ 2的资产。.并会推送到服务器中

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
机器上是否创建的用户，要看资产和系统用户是否关联，这才是根本。

当添加授权规则的时候，自动会让资产和系统用户关联，如果 系统用户是动态系统用户，那么系统用户还会和用户进行关联

**Comment by whiskyy** [comment]
> 机器上是否创建的用户，要看资产和系统用户是否关联，这才是根本。
> 
> 当添加授权规则的时候，自动会让资产和系统用户关联，如果 系统用户是动态系统用户，那么系统用户还会和用户进行关联

您好，我在授权 用户A对应资产1的动态系统用户SSH时，资产1上出现用户A是没问题的
用户B对应资产2的动态系统用户SSH时，资产2上出现用户B是没问题的
，结论是资产1上出现了用户A和B，资产2上出现用户AB，但是没有对B进行1的授权，没有对A进行2的授权。
我是想问问这个关联关系是否是预期设计？
如果确认为预期设计的话
这个资产12对于系统动态用户SSH关联了，但是对于资产来说，并没有授权一个用户对资产的授权行为，却出现了资产用户，
这个会存在一些安全风险或者资源占用，如果想解决这个问题，用户管理员需要对每个人生成创建不同机器的系统用户，对应的机器创建不同的授权规则，我理解这个不太利于管理，您觉得呢？

**Comment by ibuler** [comment]
是符合预期的，控制不了那么细，因为中间是 系统用户

1. 用户A对应资产1的动态系统用户a时
系统用户a关联了 用户A 和 资产1

2. 用户B对应资产2的动态系统用户a时
系统用户a关联了 用户B 和 资产2


目前是用的组合的形式

**Comment by whiskyy** [comment]
十分感谢老广，我已经得到想要的答案。
我遇到的问题也写到了Issues中，不再邮件中重复了，希望贵司会讨论相关问题


| |
陈昱州
|
|
whisky_y@163.com
|
签名由网易邮箱大师定制


在2020年07月13日 17:52，老广<notifications@github.com> 写道：

是符合预期的，控制不了那么细，因为中间是 系统用户

用户A对应资产1的动态系统用户a时
系统用户a关联了 用户A 和 资产1

用户B对应资产2的动态系统用户a时
系统用户a关联了 用户B 和 资产2

目前是用的组合的形式

**Comment by whiskyy** [comment]
对于资产来说，并没有授权一个用户对资产的授权行为，却出现了资产用户，这个会存在一些安全风险或者资源占用。
如果想解决这个问题，用户管理员需要对每个人生成创建不同机器的系统用户，对应的机器创建不同的授权规则
我理解这个用起来体验不是很好，在逻辑层是可以分开授权创建同步系统用户的，希望贵司考虑增加细节优化。感谢
