### ISSUE TITLE
获取Windows系统资产配置信息问题

### ISSUE THREAD

**Issue by lovese** [jumpserver/jumpserver#4303]
[简述你的问题]
无法通过SSH协议获取Windows系统服务器的配置信息

##### 使用版本
[2.0.2]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
按照文档安装了sshd服务，通过xshell等ssh客户端可以连接到这台Windows服务器，说明sshd服务端没问题，
跳板机可以正常登陆服务器，也就是说RDP协议也可以正常登陆，授权也没问题，
管理用户和系统用户都是一样的，都是administrator，密码也一样。
资产那也添加了ssh协议，但是测试连接就是不通

![TIM截图20200713115822](https://user-images.githubusercontent.com/13268438/87270053-8b3ea880-c501-11ea-8674-6d63b8a1f3a9.png)

希望帮忙分析一下！谢谢！

**Comment by ibuler** [comment]
安装 openssh 以后，应该需要配置一下 openssh 默认用的shell, 有两种 一种是 cmd, 一种是 powershell  [参见](https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html#configuring-the-win32-openssh-shell)

jumpserver默认用的是cmd方式，如果用powershell，请设置配置文件 config.yml
WINDOWS_SSH_DEFAULT_SHELL: powershell

**Comment by lovese** [comment]
@ibuler 我改成 powershell 后还是不行，我用 xshell 连接显示是 powershell 了，改成功了，现在报错也不一样了
![TIM截图20200715104640](https://user-images.githubusercontent.com/13268438/87497772-d2a37100-c688-11ea-9afa-d3ed4420b3d1.png)

**Comment by lovese** [comment]
![TIM截图20200715105231](https://user-images.githubusercontent.com/13268438/87498033-73922c00-c689-11ea-85ca-99151749b600.png)
![TIM截图20200715105308](https://user-images.githubusercontent.com/13268438/87498039-75f48600-c689-11ea-9e30-a63723d1896e.png)

**Comment by lovese** [comment]
系统是Windows server 2008 R2 企业版

**Comment by ibuler** [comment]
默认是cmd, 如果是 Powershell的话，需要改jumpserver配置文件

**Comment by lovese** [comment]
配置文件路径在哪？

**Comment by lovese** [comment]
我设置Windows的sshd默认shell为cmd后，跳板机连接显示被拒绝，然后我用xshell连接也一样被拒绝，这是什么情况，账号和密码肯定是对的。

**Comment by lovese** [comment]
@ibuler 可以指导下嘛？

**Comment by lovese** [comment]
![TIM截图20200720122832](https://user-images.githubusercontent.com/13268438/87899706-930fc700-ca84-11ea-9d34-f486c8ae7d5c.png)
配置了这三项

**Comment by lovese** [comment]
![TIM截图20200720123706](https://user-images.githubusercontent.com/13268438/87900060-c4d55d80-ca85-11ea-9e2b-e95973e05f41.png)
这是连接debug信息

**Comment by lovese** [comment]
我换一台机器试了一下，报错不一样
![TIM截图20200720143856](https://user-images.githubusercontent.com/13268438/87907301-eee34b80-ca96-11ea-9b4b-9ff465d117dd.png)
Windows安装的sshd默认shell为cmd，xshell能连接上，跳板机网页端RDP也能连接上

**Comment by ibuler** [comment]
@lovese 用原生的ansible试试

**Comment by ibuler** [comment]
先关闭了 issue， 有问题再打开
