### ISSUE TITLE
jumpserver 创建系统用户能否指定目录进行创建？

### ISSUE THREAD

**Issue by NEWgaofeng** [jumpserver/jumpserver#4308]
[简述你的问题]
jumpserver 创建系统用户能否指定目录进行创建？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
Version: JumpServer2.0.1
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

比如：linux内的创建方式是useradd -d /data/mingyiyang -m mingyiyang
如果jumpserver创建的用户都在/home/xxx下面
能否使创建的系统用户 创建到/data目录下面呢

如能解答，感激不尽，谢谢

##### 其他

[注:] 完成后请关闭 issue

**Comment by qiyongxiao** [comment]
这个可以自定义的。

**Comment by NEWgaofeng** [comment]
能否分享下链接 或者自定义的方式

**Comment by NEWgaofeng** [comment]
> 这个可以自定义的。

您好，可否分享下具体做法呢，感谢

**Comment by ibuler** [comment]
已支持
