### ISSUE TITLE
通过左右键修改内容导致录屏混乱

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4309]
[简述你的问题]

通过左右键修改内容导致录屏混乱
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
通过左右键修改内容导致录屏混乱
![image](https://user-images.githubusercontent.com/44529247/87380935-1aad8f80-c5c6-11ea-9520-621b081a7c2f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这应该和左右键没有关系，应该是播放录像时的 长宽设置过低

**Comment by ibuler** [comment]
有问题再打开
