### ISSUE TITLE
Windows资产管理时未出现Guacamole RDP远程盘，无法上传文件

### ISSUE THREAD

**Issue by yamin-zou** [jumpserver/jumpserver#4310]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.8 
##### 问题复现步骤
1. [步骤1]连接windows 2012 r2 的服务器
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
Windows资产管理时未出现Guacamole RDP远程盘，
仅一台windows出现该问题，其他正常
授权权限也是全开的。

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
或许是那台机器的问题吧，使用 原生 windows remote 试试
