### ISSUE TITLE
如何屏蔽同一IP进行多次测试密码攻击

### ISSUE THREAD

**Issue by hugeng1979** [jumpserver/jumpserver#4320]
[简述你的问题]
jumpserver发布在非443端口上，但是还是被人攻击。
看日志，经常在一段时间内有同一个IP，使用不同的用户名进行测试登录。
由于我使用是LDAP登录，所以这些不存在的用户名，在登录日志中提示是password_failed

根据以往的issues，发现你们的安全规则是：IP+用户名 ，如果出错次数超过安全设置中的次数才会进行阻止。
是否可以增加一个选项，允许仅根据 IP的出错次数超限就进行阻止呢？
因为仅根据IP，是会误杀一片，所以这个新增加的选项由最终用户决定是否打开。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0.2

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![微信截图_20200715085932](https://user-images.githubusercontent.com/35301810/87492062-51de7800-c67c-11ea-80ea-8d0d35559879.png)
![微信截图_20200715090623](https://user-images.githubusercontent.com/35301810/87492064-530fa500-c67c-11ea-9564-134ead45f864.png)
![微信截图_20200715090637](https://user-images.githubusercontent.com/35301810/87492065-53a83b80-c67c-11ea-992b-852bd83eb9d3.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
现在还没有开关，可以通过设置限制次数为 9999 来解决

**Comment by hugeng1979** [comment]
> 现在还没有开关，可以通过设置限制次数为 9999 来解决

不好意思，请问设置哪个参数为9999？
我之前已经设置“限制登录失败次数”为3了，但是对方是不停的换用户名来测试，IP不变。
而jumpserver关于这个参数是以 IP+用户名来判断的，所以无法屏蔽他换用户名测试。

**Comment by Phoebus888** [comment]
> > 现在还没有开关，可以通过设置限制次数为9999来解决
> 
> 不好意思，请问设置其中参数为9999？
> 我之前已经设置“限制登录失败次数”为3了，但是对方是不停的换用户名来测试，IP不变。
> 而jumpserver关于这个参数采用IP +用户名来判断的，因此无法屏蔽他换用户名测试。

你现在是怎么解决这个问题的，是通过修改端口号吗？

**Comment by ibuler** [comment]
@hugeng1979 如果是大规模的来爆破，还是需要一切其他辅助，比如说WAF，可能更专业一些
