### ISSUE TITLE
资产搜索结果需要显示节点信息

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#4336]
资产搜索时，无法显示节点信息，在资产较多的情况下，无法快速确认资产

**Comment by ibuler** [comment]
IP 不比节点信息有用？

**Comment by wojiushixiaobai** [comment]
资产较多的情况下，一般不会刻意去记资产的 ip，而是记资产的节点和名称。

**Comment by ibuler** [comment]
像Luna那样搜索？

**Comment by RaviRockz** [comment]
sir did you solved the issue

**Comment by ibuler** [comment]
或许应该是联动搜索，搜索资产时，左侧的树也跟着变动

**Comment by Chas-IO** [comment]
> 或许应该是联动搜索，搜索资产时，左侧的树也跟着变动

Luna那里搜索时，可以搜索节点名也可以搜索IP，当搜索节点时，会显示节点以及该节点下主机。

**Comment by Chas-IO** [comment]
我也有这个需求

**Comment by Chasii** [comment]
请问这个需求完成了吗
