### ISSUE TITLE
jumpserver如何直接登录已有账户

### ISSUE THREAD

**Issue by daisylv** [jumpserver/jumpserver#434]
现在很多服务器有统一的账户了，不希望再通过jumpserver重新推送新的用户上去，继续沿用老用户，试着不输入密码，仅仅勾选使用密钥，但是老是登不上去，看日志是说登录失败需要转密码登陆
请问有什么好的解决办法么

**Comment by ibuler** [comment]
添加系统用户时，选择使用密码，填入原来用户的密码即可
