### ISSUE TITLE
下载资产模板无法正常下载，会自动跳转错误页面

### ISSUE THREAD

**Issue by yzg784534398** [jumpserver/jumpserver#4348]
jumpserver 2.0.1打开资产列表，选择下载模板，点击下载，然后会自动跳转到
http://xxx/api/v1/assets/assets/?node_id=75375b02-25df-4fe8-9611-f0d93b4db1e8&show_current_asset=0?format=csv&template=import&limit=1 这个地址，无法进行模板下载，但是导出又是可以正常使用

**Comment by ibuler** [comment]
的确有问题

**Comment by yzg784534398** [comment]
那像这种问题，到时候会修复现有的版本吗？ 还是推新的版本去更新升级？

**Comment by ibuler** [comment]
会的，很快会修复，也会在release note中体现

**Comment by orangemio** [comment]
https://github.com/jumpserver/lina/pull/285
