### ISSUE TITLE
Connect asset hg error: dial tcp 192.68.60.234:22: i/o timeout

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4349]
[简述你的问题]
用jumpserver本地ssh可以登录资产，通过2222登录的界面登录资产不成功，通过koko容器登录资产也不成功，通过gua容器登录资产可以成功，只有一个资产是这种问题，其他正常

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.0
##### 问题复现步骤
1. [步骤1]
gua容器登录
![image](https://user-images.githubusercontent.com/44529247/87848617-8a987e80-c914-11ea-8582-26327de481f1.png)
koko容器登录
![image](https://user-images.githubusercontent.com/44529247/87848698-36da6500-c915-11ea-9542-434efc07e8ae.png)
jumpserver本地
![image](https://user-images.githubusercontent.com/44529247/87848709-48237180-c915-11ea-9d2c-bd000d21cd14.png)
web终端登录
![image](https://user-images.githubusercontent.com/44529247/87848725-7012d500-c915-11ea-927d-c9a7da7b83bc.png)
koko日志
![image](https://user-images.githubusercontent.com/44529247/87848817-0d6e0900-c916-11ea-8d76-fd0775881cd9.png)

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是不是 **容器网络** 的问题呢
