### ISSUE TITLE
jumpserver如何使用agent

### ISSUE THREAD

**Issue by daiyongjian** [jumpserver/jumpserver#435]
Jumpserver登入后，如何使用agent,比如xagent之类的

**Comment by ibuler** [comment]
使用Jumpserver后不支持 x等工具的转发

**Comment by dataviruset** [comment]
Would be great if the jumpserver could support SSH agent for key forwarding :)

**Comment by xuanyunhui** [comment]
Would be great if the jumpserver could support SSH agent for key forwarding :)
