### ISSUE TITLE
管理用户、系统用户完成后，显示的创建时间为1970/1/1 08:00:00

### ISSUE THREAD

**Issue by zh0u0liver** [jumpserver/jumpserver#4360]
[简述你的问题]
创建管理用户、系统用户完成后，显示的创建时间为1970/1/1 08:00:00

##### 使用版本
2.0.2

##### 问题复现步骤
1. [用户管理-->管理用户-->创建]，完成后，进入管理用户详情, 显示创建时间为1970/1/1 08:00:00
2. [用户管理-->系统用户-->创建]，完成后，进入系统用户详情, 显示创建时间为1970/1/1 08:00:00

##### 具体表现[截图可能会更好些,最好能截全]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/52630652/87815562-64cd9400-c898-11ea-8545-4bc9a6d20a31.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/52630652/87815497-4a93b600-c898-11ea-8b7e-1f27be95062d.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
什么浏览器？

**Comment by orangemio** [comment]
测试了下Firefox和Chrome还有edge, 没有问题

**Comment by zh0u0liver** [comment]
操作系统：macOS
浏览器: Safari, Chrome, Firefox，
ps: 应该是[资产管理-->管理用户-->创建],[资产管理-->系统用户-->创建]

**Comment by chengpeng21186** [comment]
我的macOS,
Firefox 没问题
Safari 也有这个问题。
