### ISSUE TITLE
最新2.1.0重置下载个人私钥贴入主机，每次登陆还需要密码

### ISSUE THREAD

**Issue by cuijianzhe** [jumpserver/jumpserver#4361]
[简述你的问题]
最新2.1.0重置下载个人私钥贴入主机，每次登陆还需要密码
另附：难道只能让管理员把每个人的公钥文件贴入Jumpserver web端？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
个人web页面重置ssh秘钥
2. [步骤2]
把个人秘钥加入自己的机器或者mac，每次登陆需要密码

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/48144475/87849509-ce42b680-c91b-11ea-9dce-623499a58c3b.png)

![image](https://user-images.githubusercontent.com/48144475/87849537-f8947400-c91b-11ea-8dd7-df2c8ec952c4.png)
![image](https://user-images.githubusercontent.com/48144475/87849549-0e099e00-c91c-11ea-999e-7306a94211eb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
-i 指定下这个私钥文件看看

**Comment by cuijianzhe** [comment]
> -i 指定下这个私钥文件看看

还是不行
![image](https://user-images.githubusercontent.com/48144475/87891177-a6626880-ca6b-11ea-8a7c-ac5106131be1.png)

**Comment by ibuler** [comment]
再查看一下是否开启了密钥认证  系统设置-终端设置-密钥认证

**Comment by cuijianzhe** [comment]
> 再查看一下是否开启了密钥认证 系统设置-终端设置-密钥认证

是的，我开启密钥认证密码认证了
![image](https://user-images.githubusercontent.com/48144475/87892947-027bbb80-ca71-11ea-945f-31a22d688830.png)

**Comment by cuijianzhe** [comment]
> 再查看一下是否开启了密钥认证 系统设置-终端设置-密钥认证

2.0版本之前可以让用户自己上传公钥的，现在没有这个功能了？为什么要砍掉这个功能？难过……
![image](https://user-images.githubusercontent.com/48144475/87910109-0a048a00-ca9c-11ea-8615-efa09f5b59d9.png)

**Comment by ibuler** [comment]
@orangemio  为什么砍掉了？

**Comment by cuijianzhe** [comment]
> @orangemio 为什么砍掉了？

难道不是吗？现在没有让个人上传公钥的功能了，而最新版本的个人私钥还不生效。

**Comment by ibuler** [comment]
@cuijianzhe 如果你没有看到这两个设置的tab，那么看这个 FAQ

问: 设置了公钥却无法登录
答：可能是设置了其它的登录方式，而没有使用本地数据库认证方式，假如 使用LDAP登录，也设置了公钥登录，当 LDAP 中删除了用户，或设置了禁用，无法完成LDAP认证，但是用户却使用公钥登录了，这个问题就比较棘手，所以除了数据库认证，都关闭了设置公钥和使用公钥登录

**Comment by cuijianzhe** [comment]
好的，明白了

**Comment by ibuler** [comment]
说明一下你的情况，对后来人也许有用

**Comment by cuijianzhe** [comment]
> 说明一下你的情况，对后来人也许有用

我们这里采用LDAP认证的方式，现在如你所说，没有个人上传公钥认证的功能，只能管理员在后台添加比如mac os用户的公钥，他们登录Jumpserver每次都需要使用密码，个人后台使用私钥不成功。注：其他可记住密码工具登录的用户不受影响。因为之前的版本比如1.5.4使用不管什么用户都是可以上传自己的公钥的。在此感谢Jumpserver团队，谢谢

**Comment by ibuler** [comment]
@cuijianzhe 可能页面上没有好的提示，这才是造成误解的原因，产品上的选择 有时A, 有时B，需要结合多方的需求来中和，如果页面上做好了很好的提示，或许就不会有疑惑了
