### ISSUE TITLE
jumpserver里面的系统账号删除问题

### ISSUE THREAD

**Issue by qiyongxiao** [jumpserver/jumpserver#4364]
[简述你的问题]
jumpserver里设置了系统账户，在做了主机授权之后可以登录这台主机，如果删除了这个系统账户后，推送到linux主机中的账号会进行删除吗？

##### 使用版本
2.0.1

##### 其他需求
有这样一个需求，我有十几个人的账号，这些账号要/data目录进行读写，并且也可每个人登录后也可以操作其他人生成的数据文件。这个场景下就使用采用“用户组”来进行权限管理，添加一个用户组，给组授予777权限。因此得出下面结论：
创建的系统账户能不能指定用户组？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. 推送的系统账号不会删除，这里需要手动来删除
因为当时做过删除的功能，后来用户没看提示，确认删除系统用户，把正在运行服务的系统用户删掉了，所以这里需要用户自己来做

2. 添加用户组的选项下个版本有计划

**Comment by qiyongxiao** [comment]
> 1. 把正在运行服务

ok,已收到这个回复。
能否增加都winserver 2019的支持？

**Comment by ibuler** [comment]
应该是支持的,rdp协议中的安全策略应该没有改变

**Comment by chaiyd** [comment]
> 1. 推送的系统账号不会删除，这里需要手动来删除
>    因为当时做过删除的功能，后来用户没看提示，确认删除系统用户，把正在运行服务的系统用户删掉了，所以这里需要用户自己来做
> 2. 添加用户组的选项下个版本有计划

关于删除用户，这一块，有没有想过做成可选的呢，删除用户时，有个选择框之类，选择是否删除系统用户
还有推送用户的规则是什么，发现创建完账号，有时候推送的不是很急时

**Comment by ibuler** [comment]
- 暂时先不考虑删除，在安全和方便上，安全优先级比较高
- 推送用户是基于信号做的，系统用户新关联了一个用户，就会进行推送
