### ISSUE TITLE
系统主动发出的用户密码过期提醒邮件使用的语言问题

### ISSUE THREAD

**Issue by chjtwork** [jumpserver/jumpserver#4365]
[简述你的问题]

请问下，系统主动发出的用户密码过期提醒邮件，发的是中文或者英文邮件是怎样逻辑？
如何指定给用户发送使用英文邮件？

##### 使用版本
1.5.9

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
任务用的是系统的语言设置，不能对某个用户进行设置， 可以通过更改配置文件 LANGUAGE_CODE 来完成，详见 [Django文档](https://docs.djangoproject.com/en/3.0/topics/i18n/translation/)

```
LANGUAGE_CODE: zh    # en 是英文 
```

**Comment by chjtwork** [comment]
谢谢！
