### ISSUE TITLE
2.1版本添加资产后，无法连接

### ISSUE THREAD

**Issue by liyuanzhuafan** [jumpserver/jumpserver#4366]
[简述你的问题]
已经添加好系统用户和管理用户，添加资产后，一直无法连接资产。点资产进去测试连接一直在加载中，也不报错。
本地服务器使用ssh和用户可以登录资产。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.1.1 ]

##### 问题复现步骤

![image](https://user-images.githubusercontent.com/52233604/87926957-0e896c80-cab5-11ea-977a-efb77e7b1eab.png)

**Comment by ibuler** [comment]
去 菜单中  任务中心 - 任务监控 中看看是否
