### ISSUE TITLE
被禁用的用户可以通过ssh进行端口转发

### ISSUE THREAD

**Issue by gitchs** [jumpserver/jumpserver#437]
![image](https://cloud.githubusercontent.com/assets/1871878/25941994/06084b32-366e-11e7-89eb-da0c618cfe21.png)
通过管理后台禁用用户后，用户无法登陆web UI跟直接ssh上来操作，但是端口转发的功能还是可以用的，这样的话内网有安全隐患。

```bash
ssh bannedUsername@jsserver -N -L 10086:somehost:22
```

现在比较快的解决方案是
1. 将禁用的用户加入到ssh的DenyUsers里面去
2. 删除用户而不是禁止用户。
3. 禁止端口转发的功能。

在这个issue https://github.com/jumpserver/jumpserver/issues/130 ，好像实现了一个sshd，如果是这样的话是否应该加上
1. 正常用户可以进行端口转发。
2. 被禁用的用户直接关闭ssh链接。

**Comment by ibuler** [comment]
新版本修复
