### ISSUE TITLE
2.0.1急速部署后，可以正常使用，但是删除资产或者授权或者用户时报错，删除失败 Error: Network Error，只能采取禁用的方式，请问如何解决

### ISSUE THREAD

**Issue by 492083363** [jumpserver/jumpserver#4371]
2.0.1急速部署后，所有组件正常，也可以正常使用
在删除资产或者授权的时候，会报错，删除失败 Error: Network Error，从而无法删除资产或者授权

##### 使用版本
2.0.1

##### 问题复现步骤
1. 急速部署后，功能可以正常使用，使用./jmsctl status查看状态都是正常
2. 添加资产，授权用户都没问题，只是在删除资产或者授权时报错，删除失败 Error: Network Error
3../jmsctl upgrade成功升级到2.10，问题依旧
4../jmsctl restart 或者重启服务器，问题依旧

##### 具体表现[截图可能会更好些,最好能截全]

![jumpserver](https://user-images.githubusercontent.com/33111224/87950092-6e920a00-cad9-11ea-9475-bdcb45d1f18c.jpg)

##### 其他

请问：
1、如何解决这个问题？
2、如何查看日志，定位问题

[注:] 完成后请关闭 issue

**Comment by 492083363** [comment]
![image](https://user-images.githubusercontent.com/33111224/87953818-1c9fb300-cade-11ea-9e17-87372de98eb9.png)
调试网页的时候，发现个错误，不知道是不是bug啥的

**Comment by ibuler** [comment]
这个应该是缓存的问题，nginx 可能做了缓存，你重新打开一个隐身窗口应该是可以解决的

**Comment by 492083363** [comment]
> 这个应该是缓存的问题，nginx 可能做了缓存，你重新打开一个隐身窗口应该是可以解决的

使用了google浏览器的隐身模式，问题依旧

请问如何解决

**Comment by wojiushixiaobai** [comment]
@492083363 是不是被 waf 拦截了？

**Comment by 492083363** [comment]
> @492083363 是不是被 waf 拦截了？
没有部署WAF，也没有网页防篡改配置

**Comment by 492083363** [comment]
> @492083363 是不是被 waf 拦截了？

谢谢已经找到原因了。确实存在waf等防止网页篡改的程序阻拦了，关闭后WEB功能正常

**Comment by 492083363** [comment]
问题已经解决确实是WAF拦截导致
