### ISSUE TITLE
JumpServer版本 如 2.0.1  安装后，启动服务，输入用户密码提示：密码解密失败

### ISSUE THREAD

**Issue by FORWAY79** [jumpserver/jumpserver#4379]
部署完成后，通过./jms start -d 启动服务后
通过浏览器登陆界面，输入用户密码，提示错误信息如图。
![错误](https://user-images.githubusercontent.com/50607628/88025276-a09d7d80-cb66-11ea-9792-52e950ec3b36.png)

刚开始以为是密码错误，通过 python manage.py changepassword admin 修改了密码还是一样的错误。创建了一个账户也是一样的，不知道是什么地方出错。

**Comment by FORWAY79** [comment]
部署文档关于修改config.yml，这个文章中关于数据库的设置，有坑： 
原文件
DB_ENGINE: mysql
DB_HOST: 127.0.0.1
DB_PORT: 3306
DB_USER: jumpserver
DB_PASSWORD: 123456
DB_NAME: jumpserver

Redis 配置
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379

会提示数据库无法连接，大概意思是连接不到数据库。
必须修改为： 
DB_ENGINE: mysql
DB_HOST: '127.0.0.1'
DB_PORT: '3306'
DB_USER: 'jumpserver'
DB_PASSWORD: '123456'
DB_NAME: 'jumpserver'

REDIS_HOST: '127.0.0.1'
REDIS_PORT: '6379'
才能正常启动服务。

**Comment by ibuler** [comment]
DB_PASSWORD 引起来应该就行 别的不需要

**Comment by wojiushixiaobai** [comment]
文档里面对这个做了特别说明，请自行查看帮助文档或者安装文档。
