### ISSUE TITLE
Jumpserver v0.4.0 beta1 发布 (高清图)

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#438]
## 一. 更新Log

-- 代码部分 --
1. 使用最新版Python和Django开发  Python3.6.1， Django 1.11 
2. 完全使用 Django Class Base View开发
3. 代码结构更加合理规整，分组件开发
4. 支持Restful API 
5. 拆分 Jumpserver, terminal, web terminal为三个项目 [Jumpserver](https://github.com/jumpserver/jumpserver), [coco](https://github.com/jumpserver/coco), [luna](https://github.com/jumpserver/luna)。
    coco和luna为无状态的，支持扩展。
   
6. 支持国际化，英文+中文
7. Ansible使用 2.1 版本

项目地址： https://github.com/jumpserver/jumpserver 如果喜欢 请点右上角 给颗星星，感谢

-- 功能部分 --
1. 各组件功能都有所加强
2. 支持登陆验证码
3. 命令详细解析存储到数据库
4. 登录记录审计
5. 原来的手动推送用户改为自动推送
6. 原来的connect脚本，改为实现 ssh server，统一了认证
7. web terminal 无与伦比的漂亮
8. 资产用户批量导入导出，批量修改
9. 界面更加优雅漂亮
10. 支持Docker部署

说明：这不是一个阉割的版本，而是还未完成的版本，一些非核心的功能暂时还没加入，如 上传下载，命令执行，对于录像 功能还没有做好。

## 二. 截图

0. 没人觉得 Luna 这个web terminal 特别好看吗

![18 luna](https://cloud.githubusercontent.com/assets/17382885/26289776/39fec64a-3ed5-11e7-9398-87a384fc26d5.gif)

1. 登录页面

![1](https://cloud.githubusercontent.com/assets/17382885/26289701/b453fb32-3ed4-11e7-9ef6-dacfda7b94b2.jpg)

2. 仪表盘

![2](https://cloud.githubusercontent.com/assets/17382885/26289705/b90470c6-3ed4-11e7-9e7d-ec0976c08eaa.jpg)

3. 用户列表

![3](https://cloud.githubusercontent.com/assets/17382885/26289710/beeaee16-3ed4-11e7-9171-7d96c2ce40e9.jpg)

4. 用户详情

![4](https://cloud.githubusercontent.com/assets/17382885/26289734/f90839d2-3ed4-11e7-9164-6a2377b97448.jpg)

5. 资产列表

![5](https://cloud.githubusercontent.com/assets/17382885/26289738/fe1682d0-3ed4-11e7-855c-8ead5a812770.jpg)

6. 资产详情

![6](https://cloud.githubusercontent.com/assets/17382885/26289743/0310a7e8-3ed5-11e7-87a9-3ca4cde6d107.jpg)

7. 授权列表

![7](https://cloud.githubusercontent.com/assets/17382885/26289745/06f22512-3ed5-11e7-8c82-f3c8f3460777.jpg)

8. 授权详情

![8](https://cloud.githubusercontent.com/assets/17382885/26289747/0e176884-3ed5-11e7-8582-489eac2fb539.jpg)

9. terminal列表

![9 terminal](https://cloud.githubusercontent.com/assets/17382885/26289749/11e9fef4-3ed5-11e7-93f5-ea9e50e8a44e.jpg)

10. 推送历史

![10](https://cloud.githubusercontent.com/assets/17382885/26289750/158d7a86-3ed5-11e7-83fa-d0351fcc9632.jpg)

11. 在线session

![11 session](https://cloud.githubusercontent.com/assets/17382885/26289753/19df6c48-3ed5-11e7-8c9d-0e6c44d38e2e.jpg)

12. 命令记录

![12](https://cloud.githubusercontent.com/assets/17382885/26289755/1e254d4a-3ed5-11e7-8e7c-0667220c70b6.jpg)

13. 登陆日志

![13](https://cloud.githubusercontent.com/assets/17382885/26289757/223e0f7a-3ed5-11e7-9664-fb0c7543411d.jpg)

14. 用户添加

![14](https://cloud.githubusercontent.com/assets/17382885/26289758/2648d87a-3ed5-11e7-8524-8050e382ab45.jpg)

15. 资产添加

![15](https://cloud.githubusercontent.com/assets/17382885/26289761/2a3c67d0-3ed5-11e7-93f9-a78a5c8dafc9.jpg)

16. 授权添加

![16](https://cloud.githubusercontent.com/assets/17382885/26289766/2f0303b4-3ed5-11e7-9cb7-403cddaa4e5f.jpg)

17. coco

![17 coco](https://cloud.githubusercontent.com/assets/17382885/26289775/37893fb2-3ed5-11e7-9388-75d10ecb6f8a.gif)

18. luna <web terminal>

![18 luna](https://cloud.githubusercontent.com/assets/17382885/26289776/39fec64a-3ed5-11e7-9398-87a384fc26d5.gif)

## 三. 感谢

感谢 **刘正，小侠** 的牛逼代码，没有他们就没有Luna，主要负责 Luna 前端

感谢 **小彧**  Django 水平绝对牛逼，主要负责了 用户模块

感谢 **尚委，闲云野鹤** 的管理

感谢 **王墉，茂峻，书僮，董帅，连春，成维，Tad** 感谢付出

## 四. 引用项目
1. [Django](https://www.djangoproject.com/start/overview/)

Django 是一个非常牛逼的 Python Web 框架，效率之高，功能之全，叹为观止

2. [Ansible](https://www.ansible.com/)

Ansible 运维人都知道，无Agent，使用方便，被redhat收购了

3. [INSPINA](https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S) 

Jumpserver前端牛逼，全靠她了，不敢独享，分享给大家，请支持人的劳动成果，拒绝盗版 

4. [Paramiko](http://www.paramiko.org/)

Python 上牛逼的 ssh 协议工具，支持ssh v2, 没有它就没有 Jumpserver

待续

项目现在还是 beta版本，不推荐在生产中使用，除非你知道你在做什么，有问题欢迎交流 qq群: 552054376

项目地址： https://github.com/jumpserver/jumpserver 如果喜欢 请点右上角 给颗星星

**Comment by foreveryan** [comment]
好赞~~越看越想赶快从0.3迁移到0.4上~~~~
0.4.0 期待release的那天！~希望Jumpserver越来越好~~

**Comment by aruncre** [comment]
赞,这么好的堡垒系统

**Comment by boyxiaopang** [comment]
牛B的不要不要的

**Comment by vincent927** [comment]
Ansible 支持 python3了?

**Comment by calilylu** [comment]
虽然不懂，给颗星星

**Comment by bfliujinlong** [comment]
[root@PRCSGIZAB01 install]# python install.py
Traceback (most recent call last):
  File "install.py", line 8, in <module>
    import mysqldb
ImportError: No module named mysqldb
[root@PRCSGIZAB01 install]# ls

**Comment by bfliujinlong** [comment]
hi 大家好 

我在运行检查时候没有 此命令

[root@PRCSGIZAB01 install]# pip install -r requirement.txt
bash: pip: command not found
[root@PRCSGIZAB01 install]#

**Comment by ibuler** [comment]
@bfliujinlong 去查看dockerfile怎么写的

**Comment by choldrim** [comment]
赞！

**Comment by vincent927** [comment]
@bfliujinlong 
```
yum install python-pip 
```

**Comment by gongchengcheng** [comment]
没编写安装步骤和启动方式呀。哈哈。

**Comment by abrahamBear** [comment]
必须学习一下。

**Comment by ibuler** [comment]
@gongchengcheng 一键Docker安装，成功率99.9%，简直不要不要的

**Comment by tanghw** [comment]
都部署成功了,但不知道初始的用户名与密码,登录不进去,囧了

**Comment by jamswu** [comment]
启动 后加载不上静态文件
![image](https://cloud.githubusercontent.com/assets/10230162/26450919/4bd305b6-418c-11e7-81dd-acc56e215fc0.png)

**Comment by guangzhimen** [comment]
希望早日支持rdp协议，和资产基础数据上报功能，把cmdb和堡垒机结合起来

**Comment by laiwahwah** [comment]
终于支持python3了，赞

**Comment by yin32167** [comment]
@tanghw 都是 admin

**Comment by xiaojinbian** [comment]
不行啊 docker-compose up 运行 老报这个错  ERROR:root:Load access key failed     啥意思？

**Comment by 117111302** [comment]
超赞！！！

**Comment by qiangleizang** [comment]
04de78d95341: Downloading执行到这个的时候就报错ERROR: unauthorized: authentication required

**Comment by jokimina** [comment]
4.0代码写得更赞了, 要看懂要费点劲了 .

**Comment by wlwpz** [comment]
感谢您的分享，很精彩的项目！！

**Comment by g4zhuj** [comment]
期待新版本的发布!

**Comment by hondajojo** [comment]
@bfliujinlong pip install pymysql

**Comment by kvc0769** [comment]
0.4版，创建新用户时，如果邮件地址已经使用会提示邮件已经被使用了，手动更改新的邮件地址后提交，会出现错误，并且web上数据读写错误。

**Comment by choldrim** [comment]
@kvc0769 可以提个Issue，把详细信息说一下

**Comment by gordy2015** [comment]
很好的东西，虽然我这没用起，但还是支持大神们

**Comment by cycwll** [comment]
0.4版本什么时候支持录像

**Comment by wwwcto** [comment]
赞赞

**Comment by net592** [comment]
求RDP功能

**Comment by dishuihengxin** [comment]
0.4版本具体什么时候发布正式版本？就等着线上用了

**Comment by kiven517** [comment]
正在学习django最佳实践，看到这个，正好借鉴项目设计。这个需求可能以后也会有用。点个赞👍

**Comment by ibuler** [comment]
@kiven517 给颗星星不更好吗

**Comment by kiven517** [comment]
@ibuler 必须给呀⭐，还 watch 了呢

**Comment by boluobuyaofengli** [comment]
请教解决办法
(jump_server) [boluo@localhost coco]$ python run_server.py 

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_server.py", line 34, in <module>
    coco.run_forever()
  File "/opt/coco/coco/app.py", line 173, in run_forever
    self.bootstrap()
  File "/opt/coco/coco/app.py", line 119, in bootstrap
    self.make_logger()
  File "/opt/coco/coco/app.py", line 98, in make_logger
    create_logger(self)
  File "/opt/coco/coco/logger.py", line 55, in create_logger
    dictConfig(config)
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'
(jump_server) [boluo@localhost coco]$ python run_server.py 
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_server.py", line 34, in <module>
    coco.run_forever()
  File "/opt/coco/coco/app.py", line 173, in run_forever
    self.bootstrap()
  File "/opt/coco/coco/app.py", line 119, in bootstrap
    self.make_logger()
  File "/opt/coco/coco/app.py", line 98, in make_logger
    create_logger(self)
  File "/opt/coco/coco/logger.py", line 55, in create_logger
    dictConfig(config)
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'
(jump_server) [boluo@localhost coco]$ ^C
(jump_server) [boluo@localhost coco]$ python run_server.py 
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 558, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 731, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/python3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_server.py", line 34, in <module>
    coco.run_forever()
  File "/opt/coco/coco/app.py", line 173, in run_forever
    self.bootstrap()
  File "/opt/coco/coco/app.py", line 119, in bootstrap
    self.make_logger()
  File "/opt/coco/coco/app.py", line 98, in make_logger
    create_logger(self)
  File "/opt/coco/coco/logger.py", line 55, in create_logger
    dictConfig(config)
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 795, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/python3/lib/python3.6/logging/config.py", line 566, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'file': [Errno 2] No such file or directory: '/opt/coco/logs/coco.log'
