### ISSUE TITLE
文件管理里边文件夹只显示文件夹大小

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4381]
[简述你的问题]
文件管理里边文件夹不显示整体文件夹包含里边文件共的大小，只显示了文件夹的大小

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/88027273-9466ef80-cb69-11ea-93c8-d7582292b898.png)

![image](https://user-images.githubusercontent.com/44529247/88027187-77322100-cb69-11ea-9ded-0ca95690ecfd.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是统计的 ll -a 中显示的大小，不会递归统计的，如果递归统计的话，当文件大，层级多的时候，页面时不能正常打开的，所有的都不会这么设计的，十项一个目录里有很多小文件，du -sh 需要10分钟，那这个页面该如何显示

```
(py3) ➜  /tmp ll -a
total 24
drwxrwxrwt  9 root   wheel   288B  7 21 17:27 .
drwxr-xr-x  6 root   wheel   192B  5 28 10:28 ..
-rw-r--r--  1 guang  wheel   8.4K  7 21 11:44 abc.json
drwxr-xr-x  2 root   wheel    64B  7 18 20:49 powerlog
drwx------  3 guang  wheel    96B  7 20 10:18 vmware-guang
```
