### ISSUE TITLE
极速部署第一步提示curl: (35) TCP connection reset by peer

### ISSUE THREAD

**Issue by zhengkang2020** [jumpserver/jumpserver#4383]
[简述你的问题]

##### 使用版本

极速部署2.1版本

##### 问题复现步骤
1. [步骤1]

`curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.1.0/quick_start.sh | sh`

2. [步骤2]

> 提示curl: (35) TCP connection reset by peer

##### 具体表现[截图可能会更好些,最好能截全]

传不了截图

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
你的网络访问github有问题, 建议检查下网络环境。

**Comment by zhengkang2020** [comment]
直接打开链接提示没有页面

https://github.com/jumpserver/jumpserver/releases/download/v2.1.0

换了手机4G也打不开

**Comment by orangemio** [comment]
`https://github.com/jumpserver/jumpserver/releases/download/v2.1.0/quick_start.sh` 可以正常访问文件

**Comment by zhengkang2020** [comment]
是本地防火墙问题，谢谢

**Comment by zhengkang2020** [comment]
本地防火墙问题
