### ISSUE TITLE
0.4版本dev分支BUG

### ISSUE THREAD

**Issue by Siffre** [jumpserver/jumpserver#439]
![x7_ k_h9vi q77y9qvm45l](https://cloud.githubusercontent.com/assets/12948798/26291458/08426074-3ee1-11e7-873e-b9444bc0e6a8.png)

![hqn a1ow3uu2kilw fg2bc](https://cloud.githubusercontent.com/assets/12948798/26291468/158afa7a-3ee1-11e7-9173-d07505bc75e3.png)

问题：模板继承中缺少文件或模板中未删除
解决：添加空文件或删除模板中的继承相关语句

![7 rekrl j04zx82ad 5ab h](https://cloud.githubusercontent.com/assets/12948798/26291473/1dbfa7b8-3ee1-11e7-95a4-64923d5ddb1e.png)

![q6cq imojvns 0fdz5n x3](https://cloud.githubusercontent.com/assets/12948798/26291482/261932c6-3ee1-11e7-9ee2-f7bcc20b1c82.png)

问题：bootstrap3语法使用错误
解决：{% bootstrap_field 字段 %}

**Comment by junechouiscoming** [comment]
亲，具体点肿么操作啊(╯﹏╰)我也碰到了这bug

**Comment by junechouiscoming** [comment]
哈哈，bug这么快就修复了。

**Comment by Siffre** [comment]
@junechouiscoming    老广，昨天晚上就在修复

**Comment by ibuler** [comment]
你们喜欢就好，不给星不是中国人

**Comment by Siffre** [comment]
O(∩_∩)O哈哈~
