### ISSUE TITLE
有终端宕机后，web终端连接其他正常服务器会无响应

### ISSUE THREAD

**Issue by chaos-26** [jumpserver/jumpserver#4391]
[简述你的问题]
有个别终端发生宕机，web终端连接其他正常服务器时会没有响应也没有显示连接信息

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.7-2

##### 问题复现步骤
1. [步骤1]正常管理多台主机，使1台主机无法响应
2. [步骤2]web终端连接其他正常主机，也无响应

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@chaos-26 请在最新版本验证此问题是否可以复现

**Comment by ibuler** [comment]
新版已修复
