### ISSUE TITLE
0.4版本dev分支deb_requirements.txt依赖补全

### ISSUE THREAD

**Issue by Siffre** [jumpserver/jumpserver#440]
libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev
libwebp-dev tcl8.5-dev tk8.5-dev python-tk
build-essential libssl-dev libffi-dev python-dev
libcurl4-openssl-dev libtiff5-dev libmysqlclient-dev

**Comment by ibuler** [comment]
测试没问题后，提个PR
