### ISSUE TITLE
docker方式安装

### ISSUE THREAD

**Issue by njqaaa** [jumpserver/jumpserver#441]
github地址（存放dockerfile）：https://github.com/njqaaa/dockerfiles/tree/master/jumpserver
dockerhub地址（已构建完成的镜像，centos7 python 3.6.1）：https://hub.docker.com/r/njqaaa/jumpserver/
总计3个docker镜像（jumpserver应用，mysql，redis）详细操作请看docker hub的Full Description
备注：请使用https://www.daocloud.io/加速器

所有操作都在宿主机上操作，不需要exec到docker容器内（配置文件使用环境变量方式）。
如果需要最新的jumpserver代码，则如下操作
`git clone https://github.com/njqaaa/dockerfiles.git`
`cd dockerfiles/jumpserver`
`docker build -t njqaaa/jumpserver .`

以上，谢谢。

**Comment by Siffre** [comment]
@njqaaa   Good

**Comment by ibuler** [comment]
这个不够完整，还有 Luna，coco的，
建议直接使用 docker-compose 安装

**Comment by njqaaa** [comment]
@ibuler 缺少哪些 我完善下

**Comment by keithkuk** [comment]
已用docker测试成功！jumpserver越做越好！

**Comment by keithkuk** [comment]
jumpserver容器 添加envinfo邮件参数添加后无法启动

**Comment by njqaaa** [comment]
@keithkuk 可以启动的  你是不是报错`docker: poorly formatted environment: variable 'EMAIL_HOST ' has white spaces.` 
envinfo里面不要有空格

**Comment by keithkuk** [comment]
无法收到新建用户来的邮件

**Comment by junechouiscoming** [comment]
您好，我用的0.4的版本，coco界面可以登录，但是打不了命令咋回事(╯﹏╰)

**Comment by njqaaa** [comment]
@ibuler  coco luna已经加了 关于这块使用 有文档吗？

**Comment by jiaxiangkong** [comment]
@keithkuk 要用python3
