### ISSUE TITLE
windows资产 上传超过30M的文件到服务器G盘，再从G盘复制到服务器本地磁盘，连接错误！

### ISSUE THREAD

**Issue by vicentwu** [jumpserver/jumpserver#4410]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jms2.1.0 Lunav2.1.0-101 guacamole2.1.0 
##### 问题复现步骤
1. 上传超过30M的打包文件到远端windows服务器的guacamolefile盘正常，
2. 再从guacamolefile盘将刚刚上传的文件复制或者拖到服务器的本地磁盘如C盘，就出现：
连接错误  远程桌面服务器不在线，如果问题持续，请通知您的系统管理员，或检查您的系统日志

##### 具体表现[截图可能会更好些,最好能截全]

![TIM图片20200724164726](https://user-images.githubusercontent.com/36059301/88375034-6a156c00-cdcd-11ea-9dc1-4f7c6c0a86af.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by vicentwu** [comment]
感谢群管理员 -小白的远程协助，后又经过大量测试发现windows2008R2均出现这个问题，win2016不存在（win2012R2由于没有环境未测试）！

**Comment by zhiruiwang128** [comment]
Version v2.4.0 也有这样的问题。请问有解决方法吗？
