### ISSUE TITLE
交换机命令过滤无法生效

### ISSUE THREAD

**Issue by dcl-lily** [jumpserver/jumpserver#4412]
华为系列交换机，我想限制用户使用sys命令进入特权模式，发现无法限制。
交换机有两种登陆方式，Telnet登陆的完全没有效果，SSH登陆的，输入sys命令进入特权模式后，在次输入，会有提示(猜测是进入特权模式后会变成中括号)

##### 使用版本
Version v2.1.0 GPLv2

[TELNET login](https://user-images.githubusercontent.com/13383230/88455130-766cf800-cea5-11ea-8994-32f869ed7eea.png)
[规则](https://user-images.githubusercontent.com/13383230/88455133-7836bb80-cea5-11ea-9735-2fc2c7862ffe.png)
[规则1](https://user-images.githubusercontent.com/13383230/88455134-7967e880-cea5-11ea-97f3-0868915b7fb1.png)
[SSH登陆](https://user-images.githubusercontent.com/13383230/88455135-7a007f00-cea5-11ea-8738-fcd28c702087.png)

**Comment by dcl-lily** [comment]
![SSH登陆](https://user-images.githubusercontent.com/13383230/88455189-f7c48a80-cea5-11ea-81bc-31e1ee1446c6.png)
![TELNET login](https://user-images.githubusercontent.com/13383230/88455192-f98e4e00-cea5-11ea-91fa-b056044f389b.png)
![规则](https://user-images.githubusercontent.com/13383230/88455195-fa26e480-cea5-11ea-9ce8-61a60e439382.png)
![规则1](https://user-images.githubusercontent.com/13383230/88455197-fabf7b00-cea5-11ea-95c9-d86b05d35507.png)

**Comment by LeeEirc** [comment]
@dcl-lily v2.4.0 对telnet协议的命令拦截做了优化，欢迎试用。
