### ISSUE TITLE
如何通过SSH终端连接主机

### ISSUE THREAD

**Issue by byronjxb** [jumpserver/jumpserver#4413]
版本：2.0.1
问题：
如何通过SSH终端连接方式？
[图片]
![image](https://user-images.githubusercontent.com/21222280/88496411-9d374580-cfef-11ea-920a-96dc0d754bbc.png)

**Comment by orangemio** [comment]
命令提示已经非常清楚了

**Comment by byronjxb** [comment]
我的意思是如何通过web终端改成SSH终端方式

**Comment by orangemio** [comment]
ssh admin@<jms_host> -p2222
