### ISSUE TITLE
升级2.1后AWS S3无法在线回放录像

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4416]
[简述你的问题]

升级2.10后 使用AWS S3存储录像，无法播放录像可以下载录像，升级前没有这个问题，能看到S3已经写入了文件，但却无法读取
使用default 无法找到文件(多节点)
##### 使用版本
2.1

##### 问题复现步骤
播放回放
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28191563/88565943-df9c6900-d067-11ea-800e-5b376f74bfda.png)

![image](https://user-images.githubusercontent.com/28191563/88565925-d4e1d400-d067-11ea-97d3-cc6acc2bf021.png)
附nginxerrorlog
![image](https://user-images.githubusercontent.com/28191563/88566158-330eb700-d068-11ea-94db-1a1e05a6eb50.png)

![image](https://user-images.githubusercontent.com/28191563/88567517-2f7c2f80-d06a-11ea-8b87-83b2180278d7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
正常获取 replay path 的时候，应该会检查本地是否存在，如果不存在回去远端拉的

**Comment by whiskyy** [comment]
> 正常获取 replay path 的时候，应该会检查本地是否存在，如果不存在回去远端拉的

您好，在nginx独立出来，core多节点情况，检查本地会显示不存在，
远端会显示无法下载。
无法下载的log
Failed download replay file: An error occurred (404) when calling the HeadObject operation: Not Found

**Comment by whiskyy** [comment]
> 正常获取 replay path 的时候，应该会检查本地是否存在，如果不存在回去远端拉的
请问，我应该怎么修复这个问题？

**Comment by wojiushixiaobai** [comment]
@whiskyy 使用官方推荐的部署方式不会出现此问题才对。多个 core 的 jumpserver/data 目录是否已经同步

**Comment by whiskyy** [comment]
> @whiskyy 使用官方推荐的部署方式不会出现此问题才对。多个 core 的 jumpserver/data 目录是否已经同步

没有同步，是什么组件出了问题呢

**Comment by whiskyy** [comment]
> @whiskyy 使用官方推荐的部署方式不会出现此问题才对。多个 core 的 jumpserver/data 目录是否已经同步

找到问题了是nfs 共享data这块有点问题。谢谢老广

**Comment by qiyongxiao** [comment]
@whiskyy 我用docker jms_all部署的，也是无法回放视频，视频存储在本地，是可以找到这个文件，就是无法读取，无法进行回放
