### ISSUE TITLE
增加数据库应用之后，会话管理，web终端，资产显示不全，需要刷新很多次才会正常，以及有显示bug

### ISSUE THREAD

**Issue by chaiyd** [jumpserver/jumpserver#4418]
[简述你的问题]
增加数据库应用之后，会话管理，web终端，资产显示不全，需要刷新很多次才会正常，以及有显示bug

![image](https://user-images.githubusercontent.com/34934673/88625386-3d1dcd80-d0db-11ea-9fd2-462eeb02cea9.png)
![image](https://user-images.githubusercontent.com/34934673/88625430-4c9d1680-d0db-11ea-8bbe-7414c7a6d8c6.png)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
版本：v2.1.0

##### 问题复现步骤
1. [步骤1]
  增加数据库应用，添加相应权限，访问web终端
  删除数据库应用之后，恢复正常

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
检查下日志是否有报错，尚未复现此问题。可以到 demo 环境进行测试
https://demo.jumpserver.org

**Comment by orangemio** [comment]
浏览器什么版本？

**Comment by chaiyd** [comment]
> 浏览器什么版本？

版本 84.0.4147.89（正式版本） （64 位）

**Comment by chaiyd** [comment]
> 检查下日志是否有报错，尚未复现此问题。可以到 demo 环境进行测试
> https://demo.jumpserver.org

并没有看到看到有报错

**Comment by chaiyd** [comment]
> 浏览器什么版本？



> 检查下日志是否有报错，尚未复现此问题。可以到 demo 环境进行测试
> https://demo.jumpserver.org

我把服务全部重启之后，没有再出现上诉问题。。
