### ISSUE TITLE
open filezilla by chrome 

### ISSUE THREAD

**Issue by yamin-zou** [jumpserver/jumpserver#4425]
[简述你的问题]
现在打开ftp工具都是自己登录然后选服务器，而且还需要一级级选到对应的服务器在选用户，是否可以在页面上选择，
通过chrome 打开本地filezilla 自动进入到对应服务器

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
暂时还没有计划写浏览器插件，不过未来会考虑的
