### ISSUE TITLE
0.4dev分支web界面报bug

### ISSUE THREAD

**Issue by junechouiscoming** [jumpserver/jumpserver#443]
web界面左上角头像点击后有注销登录，但是点击注销不了，右上角的注销可以提出

**Comment by junechouiscoming** [comment]
顺便再问一下，登录时间有错，怎么改撒O(∩_∩)O~~

**Comment by Siffre** [comment]
@junechouiscoming    你看看模板文件中的{% url %}

**Comment by junechouiscoming** [comment]
@Siffre 模板文件是哪个？ config.py还是run_server.py

**Comment by njqaaa** [comment]
@junechouiscoming 
./apps/templates/_user_profile.html  第22行
替换如下
<li><a href="{% url 'users:logout' %}">{% trans 'Logout' %}</a></li>

**Comment by njqaaa** [comment]
@junechouiscoming  搞开源项目的最好还是要了解代码的 要么就是直接使用稳定版

**Comment by junechouiscoming** [comment]
@njqaaa 谢谢啦，正在了解n(*≧▽≦*)n

**Comment by ibuler** [comment]
@njqaaa 这种小bug，请发PR
