### ISSUE TITLE
Jumpserver 2.1.0版本时间日期显示不正确，看附图

### ISSUE THREAD

**Issue by caojielinux** [jumpserver/jumpserver#4433]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
2.1.0版本 前端页面显示时间不正确
##### 具体表现[截图可能会更好些,最好能截全]

#
<img width="1929" alt="FAC44214-550A-4DD8-A736-43706BC01082" src="https://user-images.githubusercontent.com/43571451/88875881-a9700c80-d254-11ea-9e7f-37753d063c0a.png">
#### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
测试了下，没有异常。请说明下复现步骤

**Comment by orangemio** [comment]
什么浏览器？
