### ISSUE TITLE
ssh终端不显示子节点资产

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4434]
[简述你的问题]

ssh终端不显示子节点资产

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.0
##### 问题复现步骤

![image](https://user-images.githubusercontent.com/44529247/88891714-34adca00-d276-11ea-8cf3-d4b03bebb5dc.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
看下luna Web终端页面下，该节点是否存在资产。Koko的显示应该会跟 Luna 的Web终端节点显示保持一致。
