### ISSUE TITLE
python-gssapi报错

### ISSUE THREAD

**Issue by ericdong2012** [jumpserver/jumpserver#4435]
[简述你的问题]
官网一键安装脚本，快速安装教程， python-gssapi 都报错，按照网上所谓的做法也解决不了，求解。 

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
发图看下

**Comment by ericdong2012** [comment]
![Snipaste_2020-07-30_19-11-35](https://user-images.githubusercontent.com/36787305/88916383-8c5d2d00-d298-11ea-82d8-c13aa2c94cc7.png)

**Comment by wojiushixiaobai** [comment]
@ericdong2012 错误已经很明确的告知你问题，而且使用极速安装不会出现此问题。
关键错误 Download Error on https://pypi.python.org/simple/

**Comment by ericdong2012** [comment]
> @ericdong2012 错误已经很明确的告知你问题，而且使用极速安装不会出现此问题。
> 关键错误 Download Error on https://pypi.python.org/simple/

按照你的意思，我换个源就好了是么？

**Comment by wojiushixiaobai** [comment]
@ericdong2012 极速安装默认使用了 阿里云 的镜像源，包括 download 和 setuptools 的源。
https://github.com/jumpserver/setuptools/blob/master/scripts/install_py3.sh#L13 参考

**Comment by ericdong2012** [comment]
> @ericdong2012 极速安装默认使用了 阿里云 的镜像源，包括 download 和 setuptools 的源。
> https://github.com/jumpserver/setuptools/blob/master/scripts/install_py3.sh#L13 参考

我本地安装之前也配了豆瓣源的，如果是这样，那估计是缓存问题，我把虚拟环境删了再试试吧
