### ISSUE TITLE
SESSION_EXPIRE_AT_BROWSER_CLOSE问题

### ISSUE THREAD

**Issue by qizai123** [jumpserver/jumpserver#4436]
[简述你的问题]

SESSION_EXPIRE_AT_BROWSER_CLOSE: true
关闭chrome及firefox浏览器均不过期

about chrome：版本 84.0.4147.89（正式版本） （64 位）
about firefox：60.4.0esr (64-bit)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

Version 2.0.1 GPLv2.

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
浏览器里面把 关闭后允许程序后台运行 的选项关闭，即可
