### ISSUE TITLE
容器启动报错

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#4441]
[简述你的问题]
容器启动报错

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
最新版

##### 问题复现步骤
run时报错，访问502

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/12181410/89051775-50ed5c00-d387-11ea-9068-da6c2bc0fbee.png)
![image](https://user-images.githubusercontent.com/12181410/89051894-809c6400-d387-11ea-9be9-7e95b3f10526.png)
![image](https://user-images.githubusercontent.com/12181410/89051933-8d20bc80-d387-11ea-8e81-d081f5bd1d73.png)
![image](https://user-images.githubusercontent.com/12181410/89051964-9742bb00-d387-11ea-8c76-a50a70463531.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
配置文件错误，提示已经告诉你
