### ISSUE TITLE
录像回放无法下载

### ISSUE THREAD

**Issue by qiyongxiao** [jumpserver/jumpserver#4442]
[简述你的问题]
录下回放提示无法下载视频，点击下载按钮，下载下来的文件不对,文件在data目录下是可以找到的

##### 使用版本
jumpserver 2.1.0 docker部署的，使用的镜像为jms_all

##### 问题复现步骤
从 1.5.8升级上来后就变成这个样子了

##### 具体表现
![image](https://user-images.githubusercontent.com/7349963/89100196-d294c680-d427-11ea-938a-b2cde079d198.png)

**Comment by wojiushixiaobai** [comment]
@qiyongxiao 升级过程是否有误？录像文件夹重新挂载了吗？

**Comment by qiyongxiao** [comment]
@wojiushixiaobai 升级没有错误，文件夹已经挂载，就是找不到，我不挂载任何目录，录像也打不开

**Comment by wojiushixiaobai** [comment]
@qiyongxiao 所有录像？

**Comment by qiyongxiao** [comment]
@wojiushixiaobai 是的，所有录像

**Comment by qiyongxiao** [comment]
已经找到相关问题所在。关闭这个issue

**Comment by lichengrun1345641495** [comment]
下载下来的视频如何查看

**Comment by SeanWei-lab** [comment]
@seaurching 请问问题在哪，我也遇到这个情况了，希望可以分享下

**Comment by seaurching** [comment]
> @seaurching 请问问题在哪，我也遇到这个情况了，希望可以分享下

确认一下nginx是否还有其他的配置影响了这个url的转发
