### ISSUE TITLE
 数据库应用无法输入中文

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#4443]
[简述你的问题]
无论是通过命令行连接（通过2222）还是web浏览器连接，MYSQL会话无法输入中文

##### 使用版本
JumpServer版本2.1.0

##### 问题复现步骤
1. 创建数据库：
mysql> create database sample_db character set utf8mb4 collate utf8mb4_general_ci; 

2 创建表
mysql> create table joke(id INT NOT NULL AUTO_INCREMENT,title VARCHAR(20),PRIMARY KEY(id));
Query OK, 0 rows affected (0.02 sec)

3. 通过Linux OS本地客户端连接，并插入含中文字符的记录：
MySQL [sample_db]> insert into joke(id,title) value(1,"相声1");
Query OK, 1 row affected (0.01 sec)
注意：这是用操作系统上的mysql命令行客户端，没涉及到jumpserver

4.命令行连接jumpserver，能正常显示中文
MySQL [sample_db]> select * from joke;
+----+---------+
| id | title   |
+----+---------+
|  1 | 相声1   |
+----+---------+
1 row in set (0.00 sec)

5. 在jumpserver命令行连接中，再插入一条含中文字符的记录，结果无法录入中文：

6. 同样的问题存在于web terminal中。

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/24548477/89113913-54790400-d4a9-11ea-80b2-88955842c62b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
SET character_set_results = utf8 ;

**Comment by ibuler** [comment]
问题所在是, koko 容器的编码没有指定，进入 koko 容器中，手动 mysql 连接也不能输入中文，

如下方式可以解决:
```
# export LANG=C.UTF-8
# mysql -uroot .....
```

可以在 Dockerfile 或 启动 koko 容器时加上这个变量
