### ISSUE TITLE
SFTP的根目录配置项问题

### ISSUE THREAD

**Issue by iwzd520** [jumpserver/jumpserver#4444]
[简述你的问题]
koko的config.yml以下配置是否不生效？
我配置了自定义目录，但始终是/tmp目录。

# SFTP的根目录, 可选 /tmp, Home其他自定义目录
SFTP_ROOT: /

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jms_all:2.1.0和v2.1.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可在 创建更新系统用户 中设置

**Comment by iwzd520** [comment]
66666666666666666666666666666666666666666666666666666
赞一个，可以为不同用户设置了
