### ISSUE TITLE
 2.1.0的web终端打开后一直登陆不上主机

### ISSUE THREAD

**Issue by zhygit0610** [jumpserver/jumpserver#4448]
![image](https://user-images.githubusercontent.com/51645139/89193308-63aa9f80-d5d8-11ea-9bd6-7f189da032f9.png)
web终端一直呈现如上图所示情况（linux机器），通过浏览器的调式界面所有的请求都是200的，查看nginx日志，jumpserver.log , jms.log,  gunicorn.log均无异常，luna, lina目录的属主也给了nginx用户，请问下这是什么情况，或者有什么排查思路吗？

**Comment by orangemio** [comment]
Websocket

**Comment by zhygit0610** [comment]
找到原因了，是由于我的前端的ng配置的问题，我的jumpserver在内网，通过一个有公网IP的nginx转发到jumpserver的nginx上，我在jumpserver上直接配置一个公网IP就不会出现这个问题。我的前端的nginx的配置：
![image](https://user-images.githubusercontent.com/51645139/89203282-eaff0f80-d5e6-11ea-9912-65eaecd4aed9.png)
请问下，这种情况下的前端的nginx该如何配置呢？

**Comment by orangemio** [comment]
你没有做WS转发 
```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection  $connection_upgrade;
```

**Comment by zhygit0610** [comment]
非常感谢您的帮助，问题已解决。也大概知道什么问题了，谢谢了☺
