### ISSUE TITLE
jumpserver 2.1 版本 put assets/labels 接口出现异常错误

### ISSUE THREAD

**Issue by breaklinux** [jumpserver/jumpserver#4452]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 ]

版本: v2.1.0 GPLv2.

put /api/v1/assets/labels/ 接口出现:

![image](https://user-images.githubusercontent.com/23096478/89271110-d9f9e100-d66e-11ea-93ee-be1d088d8a46.png)

#### 问题复现步骤
1. [步骤1]

开启jumpserver api/docs/ 功能

2. [步骤2]

PUT /assets/labels/  

{
  "id": "851bccc6-92e3-4cc8-9779-bf6b81f31fc5",
  "name": "nginx",
  "value": "haha",
  "is_active": true,
  "comment": "测试",
  "assets": [
    "edac25dd-f502-4b13-8fad-1a587f45879a"
  ]
}

##### 具体表现[截图可能会更好些,最好能截全]

Undocumented | Error: Bad RequestResponse bodyDownload
{   "non_field_errors": [     "期望为一个包含物件的列表，得到的类型是“dict”。"   ] }

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这是批量更新接口，所以数据应该是列表(数组)，单独更新接口是 

```
PUT /assets/labels/{ID}/
{
"name": "nginx",
"value": "haha",
"is_active": true,
"comment": "测试"
}
```
