### ISSUE TITLE
docker-compose搭建完毕后，每次登录都会报There were 2 failed login attempts since the last successful login.

### ISSUE THREAD

**Issue by liufeng6582** [jumpserver/jumpserver#4453]
[简述你的问题]
我查看/var/log/secure
有以下信息
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=172.20.0.6  user=root
Failed password for root from 172.20.0.6 port 42892 ssh2

##### 使用版本
2.0.1

##### 问题复现步骤
使用密钥对登录，那为什么每次登录前会验证一次密码登录呢？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可能是这个系统用户存在密码

**Comment by liufeng6582** [comment]
可能是使用密码+密钥的方式登录，后来改成密码登录就好了
