### ISSUE TITLE
celery定时任务调度时间不准确且有缺失

### ISSUE THREAD

**Issue by JusticeShi** [jumpserver/jumpserver#4457]
[简述你的问题]
新增了一个半小时调度一次的celery定时任务，但是从日志显示只在12：00到第二天4：00之间执行，4:00到12：00之间不执行，然后查看数据库的表里最后一次执行时间又是19:40多，jumpserver采用了分布式部署，确认jumpserver redis mysql的服务器时间都是一致的，从现象看是缺失了小时，数据库记录的时间也比日志输出的晚了8小时，是不是jumpserver对于时区的设置有些问题

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.8
##### 问题复现步骤
1.新增了一个半小时调度一次的celery定时任务，但是从日志显示只在12：00到第二天4：00之间执行，4:00到12：00之间不执行
2. 查看数据库的表里最后一次执行时间又是19:40多
3.jumpserver采用了分布式部署，确认jumpserver redis mysql的服务器时区和时间都是一致，
4.从现象看是缺失了8个小时，数据库记录的时间也比日志输出的晚了8个小时

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果是准确8小时的话，那应该是和时区有关的

**Comment by JusticeShi** [comment]
> 如果是准确8小时的话，那应该是和时区有关的

但是我看jumpserversetting里没有关于时区的设置，不知道默认是使用什么时区，检查了服务器的时区都是一样的，我在查看jumpserver源码的时候发现有的地方使用了时区时间方法，有些地方没有使用时区方法，会不会和这个有关系

**Comment by JusticeShi** [comment]
> 如果是准确8小时的话，那应该是和时区有关的
补充一下，我们的服务求是suse  时区是CST-8

**Comment by ibuler** [comment]
https://www.jianshu.com/p/59a1c6efa98f

https://www.jianshu.com/p/745d469652b9

感觉稍微有些复杂， 可以帮测试一番

**Comment by JusticeShi** [comment]
> https://www.jianshu.com/p/59a1c6efa98f
> 
> https://www.jianshu.com/p/745d469652b9
> 
> 感觉稍微有些复杂， 可以帮测试一番

这个问题我最近也在看，最核心的问题是出在setting配置里
#jdango时区配置
TIME_ZONE = 'Asia/Shanghai'
**# 如果USE_TZ设置为True时，Django会使用系统默认设置的时区，此时的TIME_ZONE不管有没有设置都不起作用
# 如果USE_TZ 设置为False,TIME_ZONE = 'Asia/Shanghai', 则使用上海的UTC时间。**
USE_TZ = False

目前jumpserver的USE_TZ 是设置的true，所以不管有没有设置北京时间，都是用的utc，我尝试将use_tz关闭，但是登录就报错了，"ValueError: MySQL backend does not support timezone-aware datetimes. "，
另外可以执行下timezone.now().now()和timezone.now()两个方法，第一是返回北京时间，第二个是返回utc时间，jumpserver里只有一处代码使用timezone.now().now(),其他地方的代码都是使用的timezone.now()，所以都是utc时间，涉及改动的代码比较多，不敢轻易改，

另外我搜了django-celery-beat里关于时区的源码，好像只读取了DJANGO_CELERY_BEAT_TZ_AWARE这个配置
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE
这两个配置没有用到，如果DJANGO_CELERY_BEAT_TZ_AWARE=True，则调用timezone.now()获取当前时间，所以数据库里记录last_run_at时间都是utc时间。

**Comment by ibuler** [comment]
USE_TZ 应该是不能关闭的，多时区支持是必须的

**Comment by JusticeShi** [comment]
> USE_TZ 应该是不能关闭的，多时区支持是必须的
> 
> timezone.now() 返回的是 带时区的 UTC时间，
> timezone.now().now() 是当前时区的时间
> 
> 另外数据库应该存储的都是 UTC 时间，不管JumpServer 还是celery beat

不是特别了解django的时区设定，因为以前遇到的系统数据库里存的都是本地时间，django现在是数据库存的是美国时间，页面展示会自动处理成北京时间，但是日志记录的又是北京时间，对于问题排查也不太友好，而且要通过查数据库数据的化日期还得再手工加工下。现在celery又有时区陷阱bug，有点头大。
