### ISSUE TITLE
使用docker快速部署后 web终端无法打开win服务器，并且linux 及win文件管理无法使用。

### ISSUE THREAD

**Issue by segastar660** [jumpserver/jumpserver#4459]
[简述你的问题]

使用docker快速部署后 win服务器及文件管理无法使用。
![image](https://user-images.githubusercontent.com/24826498/89599818-26256b00-d893-11ea-8bc9-b7e4538b1e20.png)
明明已经添加了 win系统的 系统用户后 。提示该主机没有授权系统用户
![image](https://user-images.githubusercontent.com/24826498/89599924-5cfb8100-d893-11ea-8cdb-6ff5e4305bfa.png)
配置如下图所示 密码手动输入。开启/关闭自动推送 都尝试过。还手动添加了 用户到 win服务器。并且还尝试了 使用administrator来当做系统用户。故障还是依旧。资产设置是win
![image](https://user-images.githubusercontent.com/24826498/89600073-b663b000-d893-11ea-93ba-cf57990f1c45.png)
![image](https://user-images.githubusercontent.com/24826498/89600224-16f2ed00-d894-11ea-8154-801064463cc1.png)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果提示没有系统用户需要检查， 授权系统用户的协议，是不是rdp

**Comment by segastar660** [comment]
授权协议 已经设置成rdp了
![image](https://user-images.githubusercontent.com/24826498/89603444-bc5d8f00-d89b-11ea-979e-08e1b222cb14.png)

**Comment by segastar660** [comment]
![image](https://user-images.githubusercontent.com/24826498/89603471-c8495100-d89b-11ea-8200-fae7a7766de8.png)

**Comment by alwaystest18** [comment]
使用docker部署，遇到了相同的问题

**Comment by segastar660** [comment]
> 使用docker部署，遇到了相同的问题

之前用过 手动部署是没问题的 2,0后还是第一次用

**Comment by wojiushixiaobai** [comment]
@alwaystest18 @segastar660  参考此视频 https://www.bilibili.com/video/BV19a4y1i7i9?p=4

**Comment by alwaystest18** [comment]
@wojiushixiaobai 这里用的是docker部署，并非极速部署，应该很容易复现的

**Comment by wojiushixiaobai** [comment]
@alwaystest18 我的意思是让你参考如何添加资产和连接。视频安装好后有演示

**Comment by segastar660** [comment]
win2012 2008的服务器都有这个问题。删除资产后，重新添加管理用户，和系统用户。手动设置密码 手动登录。问题还是依然存在。有人碰到同样的情况吗？

**Comment by wojiushixiaobai** [comment]
请仔细看管理文档，资产要求文档 @segastar660
