### ISSUE TITLE
 install目录下没有安装文件，现在只支持docker部署吗？

### ISSUE THREAD

**Issue by iamzhaoguang** [jumpserver/jumpserver#447]
如题。。。

**Comment by choldrim** [comment]
直接 `python run_server.py`

**Comment by ibuler** [comment]
你可以查看 Dockerfile，里面描述了怎么构建这个Docker的，可以完全使用里面的命令来安装

**Comment by luokeli59** [comment]
choldrim "直接 python run_server.py: 
############################
显示如下：
start celery
/bin/sh: celery: command not found
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "run_server.py", line 22, in start_django
    http_host = CONFIG.HTTP_BIND_HOST or '127.0.0.1'
TypeError: 'NoneType' object is not callable
############################

环境centos6.9最小版x86_64
依赖包：
yum -y install git python-pip mysql-devel gcc automake autoconf python-devel vim sshpass lrzsz readline-devel
yum install libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel sshpass

哪里能找到部署文档？还是必须要DOCKER部署？

**Comment by luokeli59** [comment]
不好意思！已经找到问题所在！是我下载的版本不对，应该先选择版本再下载。
https://github.com/jumpserver/jumpserver/wiki/安装图解。

**Comment by ibuler** [comment]
新版本  https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F
