### ISSUE TITLE
严重BUG，严重影响使用

### ISSUE THREAD

**Issue by liang2025** [jumpserver/jumpserver#4477]
[简述你的问题]
在登录linux系统后，输入一段命令，按大小写切换时，会把前面输入的命令重复打印出来 这个问题已提半年了，例如：

##### 使用版本
原先使用的版本1.5.2  更新后最新版 2.1.1问题依旧

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/58716359/90087445-59fb0780-dd4f-11ea-8f2c-63a44b5840f6.png)

如图，我要输入的命令其实是: iptables -nL  当中需要切换大写L  当按下大写键时，就打出这么大一串鬼东西，从最老的版本开始就有问题，一直到现在问题依旧

**Comment by liang2025** [comment]
追加：
      使用浏览器：firefox

**Comment by LeeEirc** [comment]
@liang2025 是什么系统版本，ssh协议登陆的，还是telent的方式？

**Comment by liang2025** [comment]
> 
> 
> @liang2025 是什么系统版本，ssh协议登陆的，还是telent的方式？

CentOS 7 系统   SSH协议登录，我感觉跟这没关系   你们可以测试下firefox浏览器下，远程个linux系统测试下，随便输一段字，然后反复按“CapsLock”大小写切换键，很容易复现问题！

**Comment by wojiushixiaobai** [comment]
@liang2025 无法验证，请关闭你的浏览器插件后验证下。可以更换一台PC测试

**Comment by ibuler** [comment]
@wojiushixiaobai firefox尝试复现一下

不过大概率可能和浏览器插件有关系，可以尝试使用 无痕模式的 chrome 试试

**Comment by liang2025** [comment]
@ibuler @wojiushixiaobai 我一早就换到chrome浏览器上暂时未发现这个问题，但是firefox很明显   而其它应用登录，我是习惯用firefox的。我觉得这种不应该是由客户去操作这些关闭浏览器啊，清缓存啊（打个比方）来解决这些问题。应该是兼容市面上所有主流浏览器的

**Comment by ibuler** [comment]
如果定位到时firefox问题，我们就再研究一下
