### ISSUE TITLE
api/doc 访问不了，API帮助文档能有一个全面的吗。

### ISSUE THREAD

**Issue by chengpeng21186** [jumpserver/jumpserver#4478]
[简述你的问题]
<img width="1009" alt="图片" src="https://user-images.githubusercontent.com/22363556/90089042-0094d780-dd53-11ea-9909-59b007cf08f8.png">

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
https://demo.jumpserver.org/api/docs/

**Comment by ibuler** [comment]
下个版本做了适配，/api/docs也可以访问了
