### ISSUE TITLE
小白用docker-compose安装遇到问题

### ISSUE THREAD

**Issue by JcQSteven** [jumpserver/jumpserver#448]
服务器安装了docker和docker-compose以后，git clone了jumpserver项目，
然后cd jumpserver，执行命令docker-compose up
然后界面就开始执行，然后就一直报错，大概是coco no access key,还有luna no access key,jumpserver 
 http 403错误，然后一直循环在这里。
这个问题怎么处理呀

**Comment by ibuler** [comment]
403是正常，你需要去 jumpserver web页面-应用程序里面接受一下
