### ISSUE TITLE
jumpserver 远程登陆机器问题

### ISSUE THREAD

**Issue by zhangshuaiming** [jumpserver/jumpserver#4484]
[简述你的问题]
jumpserver 远程登陆机器问题，系统用户是jumpserver的登陆用户，如何改成自己设置的系统用户
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zhangshuaiming 系统用户里面自己改

**Comment by zhangshuaiming** [comment]
![image](https://user-images.githubusercontent.com/19390230/90377359-7c23bb00-e0aa-11ea-9095-6f7ef873571e.png)
我已经改了

**Comment by zhangshuaiming** [comment]
添加root 但还是不行
