### ISSUE TITLE
数据库应用sql较长的时候，会往左缩进隐藏

### ISSUE THREAD

**Issue by banqinghong** [jumpserver/jumpserver#4485]
[简述你的问题]
使用数据库应用登陆mysql之后，如果输入的SQL比较长，屏幕上不会完整的显示整个的SQL，而是会隐藏一部分，不确定这个地方是不是可以设置，让所有的字符全都显示出来

##### 使用版本
版本：2.1.1

##### 问题复现步骤
1. 登陆数据库应用
2. 输入一个较长的SQL

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/24997106/90101019-7491a880-dd70-11ea-8150-24a17f5b31ec.png)

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
可先通过调整窗口大小，适应下宽度

**Comment by banqinghong** [comment]
可以直接设置什么参数吗？调整为字符串到了窗口最后面的时候自动显示到下一行  
这个需求的主要原因是一个习惯的问题，就是看不到完整的sql体验上差点意思

**Comment by LeeEirc** [comment]
是自适应的，不过可能初始化的时候，宽度没匹配对，可以自己调整下这个窗口。
