### ISSUE TITLE
Audit日志无法设置保存时间

### ISSUE THREAD

**Issue by gm12367** [jumpserver/jumpserver#4487]
[简述你的问题]
v1.5.x版本以及最新v2.1.1版Jumpserver无法设置audit日志保存时间

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v1.5.x版本以及最新v2.1.1

##### 问题复现步骤
1. 审计日志无法设置保存时间
2. 只能再系统设置->终端设置中配置录象保存时间，但是无法配置日志审计保存时间
##### 具体表现[截图可能会更好些,最好能截全]
日志审计默认最大保存3个月，无法自行加大设置保存时间

##### 其他
![image](https://user-images.githubusercontent.com/16630392/90203446-5466f580-de13-11ea-81f2-6b734e98e32c.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
现在有个配置选项可以配置保存的时间：

```
LOGIN_LOG_KEEP_DAYS: 90
```

**Comment by gm12367** [comment]
审计中的其他日志，比如操作日志，密码修改日志，FTP日志的保存时间可以设置吗，在配置文件里面没找到。目前只能通过导出的方式或者通过API扒下来定期存储，如果可以设置的话就方便多了

**Comment by N-lucky** [comment]
> 现在有个配置选项可以配置保存的时间：
> 
> ```
> LOGIN_LOG_KEEP_DAYS: 90
> ```

你好，请问"LOGIN_LOG_KEEP_DAYS: 90" 是在 "/opt/jumpserver/config.yml" 文件里配置吗？里面没有 “LOGIN_LOG_KEEP_DAYS” 配置项啊？

**Comment by ibuler** [comment]
可能有一些配置，没有在config.yml 中体现，所有配置项在这里  [点我](https://github.com/jumpserver/jumpserver/blob/master/apps/jumpserver/conf.py#L123)

**Comment by N-lucky** [comment]
> 可能有一些配置，没有在config.yml 中体现，所有配置项在这里 [点我](https://github.com/jumpserver/jumpserver/blob/master/apps/jumpserver/conf.py#L123)

非常感谢，https://docs.jumpserver.org/zh/master/admin-guide/env/  也有说明该参数O(∩_∩)O哈哈~
