### ISSUE TITLE
网域网关不支持非22端口

### ISSUE THREAD

**Issue by zhygit0610** [jumpserver/jumpserver#4489]
[简述你的问题]
网域的网关设置为非22号端口时连接不上，改成22号端口时就正常。想问下，怎么配置可以让网关支持非22端口呢？

#使用版本
 2.0.1

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/51645139/90209205-4cac4e80-de1d-11ea-8071-53b4dd9f5beb.png)

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
支持，只是测试会提示失败，网关会去连接 user@localhost -p22 验证，非22端口自然会提示失败

**Comment by ibuler** [comment]
测试的时候，是可以手动填写测试的

**Comment by ibuler** [comment]
@orangemio

**Comment by zhygit0610** [comment]
好的，谢谢哈。是可以使用的
