### ISSUE TITLE
添加资产必须关联管理用户,管理用户关联资产.

### ISSUE THREAD

**Issue by sgr-smile2015** [jumpserver/jumpserver#449]
资产和管理用户都添加不成功,添加系统用户的公钥时出现错误.
TypeError at /assets/system-user/1/update/
initial_value must be str or None, not bytes

**Comment by ibuler** [comment]
好吧， /assets/system-user/1/update/ 这个可能是 python3引起的兼容问题，有空修复了，可以先用密码测试

**Comment by njqaaa** [comment]
@sgr-smile2015 这个报错主要是使用kwy导致的 先添加管理用户 系统用户（密码方式）  再创建资产

**Comment by crisewng** [comment]
@sgr-smile2015 已经做了更新

**Comment by sgr-smile2015** [comment]
谢谢回复,我是不是要重新拉取代码,重新构建一下

**Comment by crisewng** [comment]
@sgr-smile2015 pull 下代码就可以了

**Comment by sgr-smile2015** [comment]
ok,谢谢啦
