### ISSUE TITLE
修改网站标题无效

### ISSUE THREAD

**Issue by JimmyTinsley** [jumpserver/jumpserver#4490]
[简述你的问题]
同时修改完`jumpserver/apps/jumpserver/context_processor.py` 中的JMS_TITLE和`lina/index.html`中的`<title>`之后, 刷新页面的瞬间会显示修改过后的title, 但是大概零点几秒后又变回了JumpServer. 修改网站标题的原因是需要部署多套环境隔离的JumpServer, 想通过网页标题来区分标签页.

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.1.1 `docker all-in-one` 部署

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
Chrome  83.0.4103.116/ Firefox 79.0 

##### 问题复现步骤
1. 修改`jumpserver/apps/jumpserver/context_processor.py` 中JMS_TITLE的值, 和`lina/index.html`中的`<title>`的值
2. `./jms restart` 重启服务

##### 具体表现[截图可能会更好些,最好能截全]
![i7baepPDye](https://user-images.githubusercontent.com/37508117/90222664-1d0e3e00-de3f-11ea-9056-6061f6b44d16.gif)

##### 其他

[注:] 完成后请关闭 issue

**Comment by JimmyTinsley** [comment]
按照https://docs.jumpserver.org/zh/master/install/step_by_step/ 这个方式正常部署也是一样的结果, 是我修改的方式不对吗?

**Comment by ibuler** [comment]
社区版本不支持更改
