### ISSUE TITLE
using jmsctl.sh update jumpserver 2.1.1 to 2.1.2 error

### ISSUE THREAD

**Issue by usami-muzugi** [jumpserver/jumpserver#4493]
[简述你的问题]
upgrade error: 502 bad gateway

##### 使用版本
2.1.1-2.1.2

##### 问题复现步骤
./jmsctl.sh upgrade 

##### 具体表现[截图可能会更好些,最好能截全]
[root@jms setuptools]# journalctl -xe
8月 17 00:53:45 jms.ximcloud.cn dbus[809]: [system] Reloaded configuration
8月 17 00:53:45 jms.ximcloud.cn setsebool[2523]: The httpd_can_network_connect policy boolean was changed to 1 by root
8月 17 00:53:46 jms.ximcloud.cn polkitd[805]: Registered Authentication Agent for unix-process:2626:78102373 (system bus name :1.520 [
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: Reloading.
8月 17 00:53:46 jms.ximcloud.cn polkitd[805]: Unregistered Authentication Agent for unix-process:2626:78102373 (system bus name :1.520
8月 17 00:53:46 jms.ximcloud.cn polkitd[805]: Registered Authentication Agent for unix-process:2644:78102378 (system bus name :1.521 [
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: Starting Jumpserver Core Server...
-- Subject: Unit jms_core.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit jms_core.service has begun starting up.
8月 17 00:53:46 jms.ximcloud.cn jms[2650]: /opt/py3/bin/python
8月 17 00:53:46 jms.ximcloud.cn jms[2650]: 2020-08-17 00:53:46 0
8月 17 00:53:46 jms.ximcloud.cn jms[2650]: Not found __version__: No module named 'apps.jumpserver'
8月 17 00:53:46 jms.ximcloud.cn jms[2650]: Python is:
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: jms_core.service: control process exited, code=exited status=1
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: Failed to start Jumpserver Core Server.
-- Subject: Unit jms_core.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit jms_core.service has failed.
-- 
-- The result is failed.
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: Unit jms_core.service entered failed state.
8月 17 00:53:46 jms.ximcloud.cn systemd[1]: jms_core.service failed.

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@usami-muzugi 请参考此文档第一条 https://docs.jumpserver.org/zh/master/admin-guide/upgrade/other/
```
cd /opt/setuptools
git pull
./jmsctl.sh upgrade
```

**Comment by usami-muzugi** [comment]
@wojiushixiaobai
