### ISSUE TITLE
v2.1.2 Docker版本koko注册终端失败

### ISSUE THREAD

**Issue by gm12367** [jumpserver/jumpserver#4494]
[简述你的问题]
docker版本的koko注册终端时候，提示“wait for jms_core ready”

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.1.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
79.0 (64 位)

##### 问题复现步骤
1. 注册新的koko终端或者删除旧的，重新注册新版本koko
2. docker run --name jms_koko -d \
  -p 2222:2222 \
  -p 127.0.0.1:5000:5000 \
  -e CORE_HOST=http://192.168.56.129:8080/ \
  -e BOOTSTRAP_TOKEN="FE3xM9kkqb6DoSW0" \
  -e LOG_LEVEL=ERROR \
  --restart=always \
  jumpserver/jms_koko:v2.1.2

##### 具体表现[截图可能会更好些,最好能截全]
1 Docker logs里面提示“wait for jms_core ready”
2 经过检查docker中entrypoint.sh，发现是利用“curl -I -m 10 -L -k -o /dev/null -s -w %{http_code} ${CORE_HOST}/api/health/”获取返回结果，然后启动koko。
在容器中可以获取URL的返回为正常200，但是path加上/api/health就为404。但是在host主机中都是正常返回200，未开防火墙，selinux，并且尝试通过iptables -F清空规则，依然不行。初步判断有可能和nginx转发规则有关，具体现象如下图：
![图片](https://user-images.githubusercontent.com/16630392/90391056-0ece5500-e0bf-11ea-8471-bf51bcc84084.png)
![图片](https://user-images.githubusercontent.com/16630392/90391511-d713dd00-e0bf-11ea-97a4-9f60290f1017.png)
3 直接进到容器内，手动开启koko，可以正常注册
![图片](https://user-images.githubusercontent.com/16630392/90391599-fdd21380-e0bf-11ea-8a00-0d4e762284b1.png)
4 通过执行./jmsctl.sh upgrade升级上来的koko终端，正常注册

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
8080 不走 nginx，是 core 的服务，我测试未复现此问题。请勿随意修改 firewalld 规则
