### ISSUE TITLE
无法同时进行多个windows会话连接

### ISSUE THREAD

**Issue by brandewang** [jumpserver/jumpserver#4495]
[简述你的问题]
无法同时进行多个windows会话连接
在web终端，同时打开第二个windows服务器(RDP协议)，第一个连接会显示：连接已关闭，请重新连接

##### 使用版本
Version v2.0.2 GPLv2.

##### 使用浏览器版本
版本 84.0.4147.125（正式版本） （64 位）

##### 问题复现步骤
windows服务器均使用RDP协议连接
1. 进入web终端
2. 连接第一个windows服务器（正常）
3. 连接第二个Windows服务器 (正常), 但是第一个windows服务器显示：连接已关闭，请重新连接

##### 具体表现[截图可能会更好些,最好能截全]
![WX20200818-130400](https://user-images.githubusercontent.com/15993566/90472530-50a8db00-e153-11ea-9fec-b6875f66100b.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by whiskyy** [comment]
我也遇到了同样的问题
