### ISSUE TITLE
增加一个全局选项禁止guacamole复制粘贴

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#4501]
增加一个全局选项禁止guacamole复制粘贴，包括 v1.5

因为现在我们guacamole已经使用了 v1.2.0，这个包是可以控制复制粘贴的，不如我们就可以设置全局的上传下载复制粘贴，默认是打开的，如果设置了，全局禁用上传下载，复制粘贴

**Comment by Jackxun123** [comment]
0.0请问有没有可能在授权规则那里进行单独控制呢
![20200818191740-e4ILx0](https://cdn.jsdelivr.net/gh/Jackxun123/ImageHosting@master/Upload/20200818191740-e4ILx0.png)
官方的disable-copy和disable-paste参数

**Comment by ibuler** [comment]
这个已经单独控制了，也想增加一个全局的，省的管理员不小心设置了

**Comment by Jackxun123** [comment]
> 这个已经单独控制了，也想增加一个全局的，省的管理员不小心设置了

请问是在下一个版本也实现复制粘贴的单独控制吗？0.0之前的版本我看只有上传下载的权限控制

**Comment by ibuler** [comment]
是的，v2.2

**Comment by Jackxun123** [comment]
> 是的，v2.2

٩( 'ω' )و get！
