### ISSUE TITLE
windows之间通过文件管理复制粘贴大文件报错

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4502]
[简述你的问题]
windows之间通过文件管理复制粘贴传输之后，文件大小是一样的，文件时可以用的，但是会报错

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.2
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/90571397-3bc85800-e1e4-11ea-9545-8ca3681adf14.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
sftp 不支持 windows

**Comment by ryswork1993** [comment]
windows安装了openssh是可以通过文件管理实现windows资产之间复制粘贴的啊
![image](https://user-images.githubusercontent.com/44529247/90859770-66203e00-e3bb-11ea-9253-20935f37a756.png)

**Comment by LeeEirc** [comment]
可能是nginx超时了，你可以把nginx的超时时间调大一些。

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/109279166-63177600-7854-11eb-8beb-491a41179636.png)

未复现，复制粘贴能使用
