### ISSUE TITLE
文件管理资产显示的问题

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4503]
[简述你的问题]

1：文件管理左侧能不能只显示linux资产和设置ssh的windows资产，现在交换机资产也显示了
2：左侧能不能不显示展开的资产目录，展开的资产目录只在右侧展示，要不然切换资产不好找

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.2
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ryswork1993** [comment]
1：文件管理左侧能不能只显示linux资产和设置ssh的windows资产，现在交换机资产也显示了  ：这个问题请开发者忽略吧
2：左侧能不能不显示展开的资产目录，展开的资产目录只在右侧展示，要不然切换资产不好找：这个问题可以优化

**Comment by LeeEirc** [comment]
> 2：左侧能不能不显示展开的资产目录，展开的资产目录只在右侧展示，要不然切换资产不好找：这个问题可以优化

文件管理把一切资产和系统用户都虚拟成目录了，左侧的目录是跟右侧是联动的。如果要查找资产，可以通过右上角的搜索解决。
