### ISSUE TITLE
首次登录中的“向导”点击后无效

### ISSUE THREAD

**Issue by spalagu** [jumpserver/jumpserver#4505]
[简述你的问题]
首次登录中的“向导”点击后无效

##### 使用版本
v2.1.2

##### 使用浏览器版本
Chrome 84.0.4147.125

##### 问题复现步骤
1. 用新用户登录
2. 进入首次登录-完善个人信息页，同意并提交
3. 进入首次登录-向导页，点击“向导”链接

##### 具体表现[截图可能会更好些,最好能截全]
点击后页面无任何反应

**Comment by wojiushixiaobai** [comment]
系统设置 - 基本设置 - 用户向导URL 是否已经设置

**Comment by spalagu** [comment]
sorry, 是我没有设置
