### ISSUE TITLE
如何通过ssh终端连接服务器？？

### ISSUE THREAD

**Issue by byronjxb** [jumpserver/jumpserver#4506]
你好：
    目前是通过目录树结构访问所需的节点服务器，看见网上还可以通过ssh终端选择登录方式，请问下该如何配置?
目前的登录方式：
![image](https://user-images.githubusercontent.com/21222280/90597854-70f49a80-e224-11ea-9363-339d33518f68.png)

期望的登陆方式：
![image](https://user-images.githubusercontent.com/21222280/90597878-8073e380-e224-11ea-9240-4c5c0e4e99fe.png)

**Comment by wojiushixiaobai** [comment]
ssh client:
```
ssh user@host -p2222
```

xshell:
```
ssh user@host 2222
```

**Comment by byronjxb** [comment]
我的理解是user是登录堡垒机的用户名，pw是用户名对应的密码，host是堡垒机的地址？？

**Comment by wojiushixiaobai** [comment]
@byronjxb 准确的说是 koko 服务器，2222是koko 服务的端口，
以 demo 网站为例
```
ssh test@demo.jumpserver.org -p2222
```
密码: test01

demo 网站地址: https://demo.jumpserver.org

**Comment by byronjxb** [comment]
多谢~
