### ISSUE TITLE
怎样禁止作业中心---任务列表中的任务自动创建？

### ISSUE THREAD

**Issue by vyunwei** [jumpserver/jumpserver#4507]
[简述你的问题]
怎样禁止作业中心---任务列表中的任务自动创建？

##### 使用版本
1.4.9

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有些任务是无法控制的，比如推送系统用户，监测可连接性

一些周期的任务可以控制的，有参数 
```
PERIOD_TASK_ENABLED: false

```

**Comment by vyunwei** [comment]
> 有些任务是无法控制的，比如推送系统用户，监测可连接性
> 
> 一些周期的任务可以控制的，有参数
> 
> ```
> PERIOD_TASK_ENABLED: false
> ```

你好 PERIOD_TASK_ENABLED 这个参数在哪个配置文件呢？
