### ISSUE TITLE
是否提供MAC绑定

### ISSUE THREAD

**Issue by easayliu** [jumpserver/jumpserver#4509]
[简述你的问题]
用户登录限制mac地址，用来保证安全性，在哪里有配置，或者能否通过其他插件实现

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.2
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有计划支持，只不过mac地址经过nginx，跨网络后，怎么获取？

**Comment by dingpamaoo** [comment]
mac地址绑定不太现实吧，除非出终端软件能直接获取本地mac，否则经过3层传输肯定就没了
