### ISSUE TITLE
上传文件大小限制，修改了nginx的上传大小参数，最大还是只支持4G 的文件！

### ISSUE THREAD

**Issue by mrpretext886** [jumpserver/jumpserver#4518]
[简述你的问题]

##### 使用版本
[JumpServer版本 1.5.8]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

erver {
    listen 80;
    # server_name _;

    client_max_body_size 5000m;  # 录像及文件上传大小限制

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径, 如果修改安装目录, 此处需要修改

**Comment by wojiushixiaobai** [comment]
guacamole 自身 bug，请等待官方修复。
