### ISSUE TITLE
rdp未授权复制，但是复制权限有效

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4524]
[简述你的问题]
1：已测试上传下载，不管单独勾选上传或者下载都有效果
2：如果单独勾选粘贴没勾选复制，通过web终端访问widnows桌面还是可以复制内容到本机
3：如果单独勾选复制没勾选粘贴，通过web终端访问windows桌面是禁止了从本机复制内容到windows资产
有时间你们可以测试一下，也可以联系我提供环境

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/90836431-f80b5500-e381-11ea-9475-07ad65b94d09.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
经测试 Apache Guacamole 官方版本也存在此问题

**Comment by ibuler** [comment]
apache guacamole 新版本已修复，v2.7 解决这个问题

**Comment by lawrence191** [comment]
在版本2.7.1中该bug有了新变化。第一个是上传下载文件问题，如果终端在运行中，然后修改权限关闭上传下载权限，如果终端不断开，则仍可以继续使用该权限，如果终端刷新则可以生效。复制粘贴问题。无法单独只使用其中一个权限。且如果权限建立时为关闭，之后再打开，刷新重新登录仍然不能生效。
