### ISSUE TITLE
登录日志模块中能否将用户名改为用户名称+用户名的方式进行显示

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4525]
[简述你的问题]
在“日志审计”的“登录日志”中采用的是显示用户名的信息（仅显示用户名，不显示用户名称），能否和“日志审计”模板中的“FTP日志”、“操作日志”和“改密日志”中的保持已知，采用显示用户名称的方式【用户名称+用户名】的方式。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
V2.1.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/28044296/90856509-a92ae300-e3b4-11ea-8da6-bc2698b56f01.png)
![image](https://user-images.githubusercontent.com/28044296/90856564-c6f84800-e3b4-11ea-98a7-a795ae2b842f.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@xuxinwen 修改一下登陆日志的用户名
