### ISSUE TITLE
web终端收藏的资产，ssh终端不会同步

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4529]
[简述你的问题]
web终端收藏的资产，ssh终端不会同步，ssh终端r刷新也不行

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/90906409-38abb280-e404-11ea-9f2f-acacbd53e637.png)
![image](https://user-images.githubusercontent.com/44529247/90906452-47926500-e404-11ea-8f82-d960eec04413.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by LeeEirc** [comment]
@ryswork1993 使用最新版本，无法复现。

**Comment by ryswork1993** [comment]
使用2.2.1根据我的描述操作，没有同样的问题是吗

**Comment by LeeEirc** [comment]
@ryswork1993 没有。

**Comment by ryswork1993** [comment]
忽略
