### ISSUE TITLE
手动升级到最新版本，终端连接k8s应用显示“k8s 协议的数据库客户端未安装”

### ISSUE THREAD

**Issue by lhc19890816** [jumpserver/jumpserver#4530]
[简述你的问题]

**之前的2.1.1版本是手动部署，采用手动升级的方式升级到最新版2.2.0，创建k8s应用后，终端登录显示报错信息“k8s 协议的数据库客户端未安装”；使用急速部署一键安装最新版本2.2.0后，则可以正常使用k8s应用**

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

**旧版：v2.1.1
新版：v2.2.0**

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

**Chrome 75.0.3770.100**

##### 问题复现步骤
1. **[步骤1]：手动升级至最新版本，创建k8s应用**
2. **[步骤2]：终端登录测试时报错**

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/62022074/91022808-4d689000-e628-11ea-9982-04c116ccc1b1.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
由于没有测试 allinone的镜像，所以才有这个问题，默认的Dockerfile 用的是 debian，所以没有问题，未来统一各个版本

https://github.com/jumpserver/koko/blob/master/Dockerfile#L31

**Comment by ibuler** [comment]
今天处理完成，支持 CentOS，不需要单独配置

**Comment by ibuler** [comment]
新版本 v2.2.1 已 Released，请查收

https://github.com/jumpserver/jumpserver/releases
