### ISSUE TITLE
Using Jquery lesser than 3.5.0 leads to security issue

### ISSUE THREAD

**Issue by jrsenthilk** [jumpserver/jumpserver#4531]
Great piece of work on creating the jumpserver but may i request for a build with jquery version of 3.5.0 or higher. The current Jquery version, 3.1.1 and ist affected by a cross-site scripting vulnerability. 

This was reported in various security scanner and it will be really helpful if we can have a version of the Jumpserver build with the latest Jquery version.

Thanks

**Comment by LeeEirc** [comment]
The jquery has been deprecated from the version v2.0. And we use vue.js as front-end JavaScript framework now. This is our front-end repo [lina](https://github.com/jumpserver/lina). Thanks for the information.

**Comment by jrsenthilk** [comment]
Got it.. Thanks
