### ISSUE TITLE
报错：redis未设置密码

### ISSUE THREAD

**Issue by thirdcountry** [jumpserver/jumpserver#4532]
[简述你的问题]
使用docker部署，启动命令中有-e REDIS_PASSWORD=password，但是通过docker logs test，看日志报错结果是：redis没有设置密码

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.2.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
不涉及
##### 问题复现步骤
1. [步骤1]
启动命令如下：
docker run --name test -d \
    -v /home/docker/jumpserver/data:/opt/jumpserver/data \
    -v /home/docker/jumpserver/mysql:/var/lib/mysql \
    -p 800:80 \
    -p 2222:2222 \
    -e SECRET_KEY=$SECRET_KEY \
    -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
    -e DB_HOST=10.20.1.238\
    -e DB_PORT=3306 \
    -e DB_USER=jumpserver\
    -e DB_PASSWORD= password \
    -e DB_NAME=jumpserver \
    -e REDIS_HOST=10.20.1.238 \
    -e REDIS_PORT=6379 \
    -e REDIS_PASSWORD=password \
    jumpserver/jms_all:v2.2.0 
2. [步骤2]
docker logs test 

##### 具体表现[截图可能会更好些,最好能截全]
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django_redis/client/default.py", line 145, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: Client sent AUTH, but no password is set

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@thirdcountry 无法复现，请确认 redis 配置无误

**Comment by thirdcountry** [comment]
我这也没复现了。。
