### ISSUE TITLE
一键安装脚本执行总是卡住

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#4533]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.2.0/quick_start.sh | sh
2. [步骤2]卡住又没有任何提示也不知道是脚本里哪一步卡住了，取消后再次执行又能跑一些步骤，后面又卡住。

https://prnt.sc/u4yj13
https://prnt.sc/u4ykn1

安装脚本安装过程不是应该输出一些debug信息吗

取消再次执行提示

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
[ERROR] 下载 lina 失败

https://prnt.sc/u4ylgi

然后卡这又不动了

https://prnt.sc/u4ymv1

##### 其他

[注:] 完成后请关闭 issue

**Comment by louishot** [comment]
还是不支持国外服务器安装？

**Comment by louishot** [comment]
`Job for jms_core.service failed because the control process exited with error code. See "systemctl status jms_core.service" and "journalctl -xe" for details.
MySQL   Check   ........................ [ OK ]
Redis   Check   ........................ [ OK ]
Ninx    Check   ........................ [ OK ]
Py3     Check   ........................ [ OK ]
Core    Check   ........................ [ ERROR ]
Koko    Check   ........................ [ OK ]
Guaca.  Check   ........................ [ OK ]
[ ERROR ] 部分组件安装失败，请查阅上述检测结果
[ Tip ] 你可以尝试重新执行 ./jmsctl.sh install 来继续尝试`

**Comment by wojiushixiaobai** [comment]
systemctl status jms_core.service 截图

**Comment by louishot** [comment]
> 
> 
> systemctl status jms_core.service 截图

装了10多次终于成功了，Core Check ........................ [ ERROR ]的时候提示的未找到manage.py

**Comment by louishot** [comment]
> 
> 
> systemctl status jms_core.service 截图

@wojiushixiaobai 安装是成功了，但是好像有错误，后台很多功能不正常

https://prnt.sc/u50jrr
https://prnt.sc/u50kg5

权限 问题我修复了，但是还是有错误。chmod 644 chunk-1355aeb4.f881030e.js
https://prnt.sc/u50oc3

现成这个版本是稳定版吗?

**Comment by louishot** [comment]
估计demo.jumpserver.org这个服务器国外连接巨慢无比。另外脚本里把所有mirror全部改成了aliyun境内的服务器地址。
反代demo.jumpserver.org后并把aliyun全系列地址替换成官方源地址，安装一切正常了。aliyun的仓库比较烂，以前用的aliyun源装一个pip包，安装成功了但是import后用不了，搞了几个小时，后来换成官方源安装上import使用就没问题了。
