### ISSUE TITLE
是否考虑，在资产列表中，添加备注信息

### ISSUE THREAD

**Issue by vipwangtian** [jumpserver/jumpserver#4534]
[简述你的问题]
是否考虑，在资产列表中，添加备注信息

##### 使用版本
2.1.0

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
主要是怕太长了，左侧有树，每行上还有占空间的硬件信息，所以没有显示

**Comment by vipwangtian** [comment]
> 主要是怕太长了，左侧有树，每行上还有占空间的硬件信息，所以没有显示

@ibuler 
了解，但是确实觉得，在管理资产的时候没有备注不是很方便，因为主机名很多时候是随机码或者看不出用途
