### ISSUE TITLE
后端 API 统一 多对多格式

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4535]
[简述你的问题]
能否将“资产管理”-“资产列表”-"导出"-“导出所有”导出的资产清单的csv文件中将“节点”和“标签管理”列的内容默认导出为实际的值而非数据库中的字段ID，不然还要自己从数据库中导出对应的ID然后再进行拼接替换为实际的节点名称。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.1.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

![image](https://user-images.githubusercontent.com/28044296/91134713-6896d680-e6e0-11ea-99d7-6c984eb54444.png)
![image](https://user-images.githubusercontent.com/28044296/91135231-8c5a1c80-e6e0-11ea-9ddd-49aa58072345.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个其实也是我们一直想解决的，未来解决这个问题

**Comment by aiaiduo** [comment]
> 这个其实也是我们一直想解决的，未来解决这个问题
> 
> 由于现在这种多对多（就是一个资产可能有好几个节点，一个节点中可能有好几个资产），打算输出两个列，一个是id列，一个是显示列，如
> 
> nodes: ['xxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxx'],
> nodes_display: ['节点1', ’节点2']

恩恩，好的，我的资产都是只属于一个节点，我还真没有考虑过这个情况，但是现在的就是感觉不太友好，不方便进行资产统计分析。

**Comment by ibuler** [comment]
在多对多整体可控情况下(可预测个数基本少于10个)，列表页可以显示显示多对多的字段，增强体验，如果数量不可以控制的情况下，则不显示，比如节点下的资产，如果列表显示速度会非常慢

**Comment by jym503558564** [comment]
在新版本中已优化，能够显示节点实际名称
