### ISSUE TITLE
无法推送系统用户

### ISSUE THREAD

**Issue by yxiaoy6** [jumpserver/jumpserver#4536]
[简述你的问题]

##### 使用版本
版本：v2.0.2

##### 使用浏览器版本
谷歌浏览器

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/43592152/91143978-ee695080-e6e5-11ea-9b0d-6f390e030b41.png)

![image](https://user-images.githubusercontent.com/43592152/91143941-de517100-e6e5-11ea-9431-a44ed13a7478.png)

我应该怎么查这个问题，或者怎么解决？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
确定 nginx 设置无误，把 jms 退出后 kill 掉卡死的进程，然后重启 jms 即可
```
cd /opt/jumpserver
source /opt/py3/bin/activate
./jms stop
ps aux | grep py3  # 确定无异常卡死进程, 有请手动 kill 掉
./jms start -d

**Comment by yxiaoy6** [comment]
> 确定 nginx 设置无误，把 jms 退出后 kill 掉卡死的进程，然后重启 jms 即可
> 
> ```
> cd /opt/jumpserver
> source /opt/py3/bin/activate
> ./jms stop
> ps aux | grep py3  # 确定无异常卡死进程, 有请手动 kill 掉
> ./jms start -d
> ```

直接结束服务不好吧，有没有其他解决方法
