### ISSUE TITLE
系统迁移 问题

### ISSUE THREAD

**Issue by flyingfz** [jumpserver/jumpserver#4538]
[简述你的问题]
你好， 我们目前正在使用  1.5.7  这个版本的 JumpServer ，Docker 方式部署 在一个KVM 的虚拟机上，用起来很正常。 最近，我们 打算在另外一台机器上，重新部署正在用的跳板机。

考虑到升级或者数据迁移 ， 都比较麻烦， 所以，我 把虚拟机关机后，在KVM宿主机上，把虚拟机的磁盘文件 拷贝到了新的KVM宿主机上，再在新的机器上，使用这个磁盘文件定义了新的虚拟机，

两个 KVM宿主机的硬件型号有不一样的， 重新定义新的虚拟机时，部分参数也有变化，主要是 libvirt 版本不一致需要对应调整 。但最终使用原来的虚拟机 qcow2 文件 能启动新的虚拟机。

这个新虚拟机开机后,  按道理应该和原JumpServer 所在的那个虚拟机 是一模一样的(新虚拟机的网卡是重新添加的)，使用新的IP 能登陆 JumpServer ， 但进去之后，不能登陆其中定义的资源，

查看 "会话管理"-> "终端管理" ， 终端列表 里的两个记录的 ”在线“列都是红色。
docker ps -a  看到两个容器都正常启动。
两个容器的 docker logs 也没发现可疑的日志
进入 虚拟机的 /opt/jumpserver/logs 目录，其中的日志也没有发现可疑的日志

请问， 这个问题， 能否提供一些帮助或者建议 ？  感谢。

**Comment by wojiushixiaobai** [comment]
@flyingfz 因为宿主 ip 变更，koko 和 guacamole 里面与 core 通信的 ip 无法访问导致此问题。把 koko 和 guacamole 删掉重建即可

**Comment by flyingfz** [comment]
多谢了。  
昨晚按照  https://docs.jumpserver.org/zh/master/faq/koko/   和 https://docs.jumpserver.org/zh/master/faq/guacamole/
这两篇文章 的说明，删掉容器，重新运行就可以了。  再次感谢。
