### ISSUE TITLE
批量执行命令部分服务器提示Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#4539]
[简述你的问题]

批量执行命令部分服务器提示Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)
##### 使用版本
2.1.2

##### 使用浏览器版本
firefox 75.0 

##### 问题复现步骤
批量执行命令部分服务器提示Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic)
使用的系统内置用户root和推送用户都提示错误，但是通过Luna - Jumpserver web terminal连接这些失败的服务器无论是使用root还是推送用户均正常。

如果说系统用户推送失败导致登录失败，为何在Luna - Jumpserver web terminal连接时完全正常。如果说root用户加的密钥不正确为何在Luna - Jumpserver web terminal连接时也完全正常。

##### 具体表现[截图可能会更好些,最好能截全]
https://prnt.sc/u5eu2u
https://prnt.sc/u5evrb
https://prnt.sc/u5ewot

**Comment by wojiushixiaobai** [comment]
多个系统用户，请在批量命令下方正确选择用户，请确认系统用户无误。
JumpServer 默认使用最后一个可以登陆资产用户的密码来作为最终认证凭据，保证用户可以正确连接到资产。

**Comment by louishot** [comment]
> 
> 
> 多个系统用户，请在批量命令下方正确选择用户，请确认系统用户无误。
> JumpServer 默认使用最后一个可以登陆资产用户的密码来作为最终认证凭据，保证用户可以正确连接到资产。
> 批量命令则直接使用系统用户的对应账号密码。

试过了批量命令下方无论是选root用户还是推送用户都无法连接。在Luna - Jumpserver web terminal在无论是选择推送用户还是root用户都可以正常连接。

**Comment by wojiushixiaobai** [comment]
@louishot 暂时没有复现此问题，请检测下授权规则是否有误，可以在系统用户详情里面测试资产可连接性

**Comment by louishot** [comment]
资产可连接性是正常的
