### ISSUE TITLE
luna rz和sz后没反应。

### ISSUE THREAD

**Issue by keithkuk** [jumpserver/jumpserver#454]
如题，已下最新docker镜像。

**Comment by choldrim** [comment]
没反应是对的，rz和sz都是xsh、secureCRT等这些本地shell客户端自己去支持的，luna是网页版，现在还没实现这个功能呢

**Comment by NoSongmaster** [comment]
sz下载文件的时候，为什么文件内容会乱码形式保存在操作日志中？怎么解决？

**Comment by ibuler** [comment]
可以修改源码，不记录rzsz内容

**Comment by NoSongmaster** [comment]
我已经修改源码，不记录sz的内容了。
起始标志，我以命令中包含sz为开始，通过检查command 作为开始。
结束标志，暂时以，下一条命令作为结束。（这条命令不会被日志记录）
存在问题：日志记录中会缺少(下一条)这个命令的记录
有什么好的方法可以明确找到sz结束的位置吗？

**Comment by ibuler** [comment]
结束应该也有结束标识，抓取一下结束即可
