### ISSUE TITLE
管理用户的ssh证书添加显示证书指纹

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#4540]
[简述你的问题]
1、当管理用户是使用ssh证书登录的时候，希望添加显示该证书的指纹，例如证书直接md5的值
2、显示该管理用户是使用证书登录，还是密码登录

有时候不确定这个管理用户是哪个证书，有指纹就能快速确定是哪个证书了，而不用去数据库里找或者重新创建。

##### 使用版本
v2.2.1
##### 使用浏览器版本
chrome

##### 问题复现步骤
1. 资产管理
2. 管理用户

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/2853517/91247425-d7c60680-e784-11ea-8a47-c282edc15472.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不错的优化点
