### ISSUE TITLE
修改用户信息！比如修改MFA为禁用或者强制启用！就会报错误！

### ISSUE THREAD

**Issue by MaxGaius** [jumpserver/jumpserver#4542]
[简述你的问题]
修改用户信息！比如修改MFA为禁用或者强制启用！就会报错误！
![image](https://user-images.githubusercontent.com/51019831/91280740-c77c4e80-e7b9-11ea-876f-bfc5d452c540.png)
![image](https://user-images.githubusercontent.com/51019831/91280775-d400a700-e7b9-11ea-9407-74eb365ac7ea.png)
##### 使用版本
 2.2.1 
##### 使用浏览器版本
edge
[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@MaxGaius http://demo.jumpserver.org
自行到 demo 网站验证你说的问题，请在 waf 放行拦截

**Comment by MaxGaius** [comment]
是浏览器的问题 原来是微软的edge浏览器。后来换成谷歌内核的edge浏览器就可以了。
