### ISSUE TITLE
通过文件管理登录网络设备下载文件为空，大小为0，用xshell不通过jumpserver登录网络设备sftp，下载正常

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4545]
[简述你的问题]
通过文件管理登录网络设备下载文件为空，大小为0，用xshell不通过jumpserver登录网络设备sftp，下载正常
如果你们没有环境可以联系我，我提供环境

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
用xshell不通过jumpserver登录网络设备sftp，下载文件
![image](https://user-images.githubusercontent.com/44529247/91293938-5b0a4b00-e7cb-11ea-966a-c4d5d02f937d.png)

通过jumpserver文件管理登录网络设备sftp下载文件
![image](https://user-images.githubusercontent.com/44529247/91293422-90faff80-e7ca-11ea-9ad4-6f5f380cf071.png)
![image](https://user-images.githubusercontent.com/44529247/91293435-95bfb380-e7ca-11ea-8b86-3d292a37b913.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
确定授权文件下载，确定系统用户有权限读取该文件

**Comment by ryswork1993** [comment]
刚重新测试，确认文件管理登录网络设备sftp的用户和用xshell不通过jumpserver登录网络设备sftp的用户一样

**Comment by wojiushixiaobai** [comment]
发个远程我看下，群里联系下我。QQ: 296015668

**Comment by ryswork1993** [comment]
@wojiushixiaobai     我qq名大神在线，加你了



rys_work1993@163.com
 
发件人： wojiushixiaobai
发送时间： 2020-08-27 09:44
收件人： jumpserver/jumpserver
抄送： ryswork1993; Author
主题： Re: [jumpserver/jumpserver] 通过文件管理登录网络设备下载文件为空，大小为0，用xshell不通过jumpserver登录网络设备sftp，下载正常 (#4545)
发个远程我看下，群里联系下我。QQ: 296015668

**Comment by wojiushixiaobai** [comment]
暂时未能复现。看看是否有其他用户反馈一样的问题
