### ISSUE TITLE
windows连接会话超时后，进程不会杀掉

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4546]
[简述你的问题]
windows连接会话超时后，进程不会杀掉，进程占用内存，这个设计是预期内的吗？请问是否会优化这个功能

##### 使用版本
2.1.0

##### 使用浏览器版本
chrome 84.0.4147.135
##### 问题复现步骤
1.连接windows会话，
2.会话超时
3.进程不杀掉，占用内存
##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/28191563/91320007-a0407400-e7ef-11ea-90cc-f03b5c9feeaf.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请自行定义组策略，超时后自动注销不是超时自动断开。这与 JumpServer 无关

**Comment by N-lucky** [comment]
Windows的"服务器管理器"，配置，本地用户和组，用户，右键“用户”，属性中找到会话，可以看到，默认配置的是“自动断开”，也可以选择“会话自动结束”

**Comment by whiskyy** [comment]
谢谢各位
