### ISSUE TITLE
关于在添加资产界面创建节点的建议

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4547]
[简述你的问题]
希望可以在添加资产界面创建节点

类似这样，输入名称，如果已存在这个节点名字就直接选，如果没有，后面写个新字代表没有，选择带新的名字，提交的时候就创建了，并分到这个节点里
![image](https://user-images.githubusercontent.com/44529247/91422973-7a1be200-e88a-11ea-8508-e5b0e92890e2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
嗯，很好的建议，尤其是标签那里应该这么做。

总结一下什么场景是比较适合这个的呢，
这种多对多，只是一个容器，或者标签，没有太多别的字段，比如说 **标签**  和 **用户组**，对于 **节点** 来说，多少有点不合适，因为节点有层级关系

对于复杂的多对多，可以提供弹窗式添加，这样会比较友好

**Comment by ryswork1993** [comment]
可以参考一下zabbix的添加主机页面创建分组的办法，他们应该有源码可以看，至于源码在哪我不懂。

**Comment by BaiJiangJie** [comment]
这个需求现在实现起来其实还是比较复杂的，简单的资源可以快速添加，但是对于一些比较复杂的资源就不太好处理了。

所以，暂时先不考虑了。
