### ISSUE TITLE
新用户注册邮件、重置密码时，页面均出现“Token错误或失效”，则无法为新用户设置密码

### ISSUE THREAD

**Issue by cnzg** [jumpserver/jumpserver#455]
如题。。。

**Comment by njqaaa** [comment]
https://github.com/jumpserver/jumpserver/pull/458/commits/3f0c35a6a1cc24010ecf137874efa7bf1cf6709f

**Comment by andro-ajp** [comment]
Same question
无论是密码输对还是输错，都会这种情况
