### ISSUE TITLE
多gua组件，无法同时连接多个windows

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4550]
[简述你的问题]

多节点部署gua，在同一个web页面连接多个windows终端，新终端连接时，旧终端会被中断

##### 使用版本
2.2.1
##### 使用浏览器版本
chrome 85.0.4183.83
##### 问题复现步骤
1.多节点部署dockerGua组件（双core双Koko双gua）
2.连接多个windows终端
##### 具体表现[截图可能会更好些,最好能截全]

1.
![image](https://user-images.githubusercontent.com/28191563/91441673-371a3880-e8a3-11ea-8a80-48c1c0c3c970.png)
![image](https://user-images.githubusercontent.com/28191563/91441708-44372780-e8a3-11ea-926e-835a70f15081.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by whiskyy** [comment]
我尝试在nginx上指定了一个gua，不会出现这个问题，同理尝试stop一个gua，也不会出现这个问题。（两个都stop过，所以排除gua组件的问题）

**Comment by whiskyy** [comment]
也尝试在修改了upstream的轮训方式，ha还是会失败
![image](https://user-images.githubusercontent.com/28191563/91442109-e8b96980-e8a3-11ea-825c-bb877fb61ee3.png)

**Comment by whiskyy** [comment]
o.a.g.a.j.session.RecordService - 重命名会话录像文件名失败

**Comment by wojiushixiaobai** [comment]
最新版本的 LB 文档已经更新，请直接使用

**Comment by whiskyy** [comment]
> 最新版本的 LB 文档已经更新，请直接使用

感谢
