### ISSUE TITLE
新添加资产之后，打开web终端页面，然后再刷新web终端网页，新加的资产就没了，再刷新网页就有了

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4551]
[简述你的问题]
新添加资产之后，打开web终端页面，然后再刷新web终端网页，有时看不到新增的资产，有时能看到新增加的资产，但是显示的资产数量不正确，再刷新网页就有了，也可以多刷新几次

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.1
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
问题复现录屏
http://43.241.76.236:1818/QQ%E5%BD%95%E5%B1%8F20200827224659.mp4  打开之后右键下载
![image](https://user-images.githubusercontent.com/44529247/91514668-e72a8880-e919-11ea-8ee8-28f5bbbe4651.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
不要直接从数据库增删资产

**Comment by ryswork1993** [comment]
正常的在资产添加管理页面添加的节点，节点下添加了一个资产，就这样了

**Comment by ibuler** [comment]
或许是缓存策略有问题了，下个版本会优化缓存策略
