### ISSUE TITLE
命令记录会把操作命令和显示结果记录成一行

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4552]
[简述你的问题]

![image](https://user-images.githubusercontent.com/44529247/91522133-0cc08d80-e92c-11ea-84e6-a13d4fa287ce.png)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
命令解析正在优化中
