### ISSUE TITLE
ssh终端当从资产退出到[Host]> ，然后回车会出现没有资产的提示，正常应该进入到所有资产显示页面

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4555]
[简述你的问题]
ssh终端当从资产退出到[Host]> ，然后回车会出现没有资产的提示，正常应该进入到所有资产显示页面

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.1
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/44529247/91679185-26571480-eb7a-11ea-9d49-00151c7302b7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
按 p 试试
