### ISSUE TITLE
能增加资产和授权复制功能吗

### ISSUE THREAD

**Issue by hubeixulu** [jumpserver/jumpserver#4556]
[简述你的问题]

##### 使用版本
版本： 1.5.6-2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 具体表现[截图可能会更好些,最好能截全]
比如我要添加三个资产，这三个资产其他都一样除了ip地址有点不一样以外，又或者我给用户添加资产授权，两个用户之间只差了其中某一台的机器权限，如果能复制的话，我直接就把资产复制一下，然后改个ip就行。用户授权也是同样的，我复制一下用户，给他改个名字加台机器就行

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已放在计划中

**Comment by ibuler** [comment]
已完成
