### ISSUE TITLE
如果不使用自动推送，是否可以不在目标资产上创建“管理用户”？

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#4557]
[简述你的问题]
刚接触jumpserver，看了下管理用户的用途，想问问，如果不用自动推送，而是先在目标资产上建好系统用户，然后将用户名密码在堡垒机里填好，是否就可以不用创建这个NOPASSWORD的用户也不用将root配置在堡垒机里了？谢谢

##### 使用版本
2.2.1

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
完全可以

**Comment by Gianthard-XYZ** [comment]
> 完全可以

好的，明白了，谢谢！
