### ISSUE TITLE
参照docs下install.md安装0.4报错

### ISSUE THREAD

**Issue by fedora1125** [jumpserver/jumpserver#457]
fedora26，参照dosc下的install.md安装，出现以下错误：

[He@shine rpm]$ uname -a
Linux shine 4.11.2-300.fc26.x86_64 #1 SMP Mon May 22 16:15:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[He@shine rpm]$ pip install -r requirements.txt -i https://pypi.doubanio.com/simple
    gcc: 错误：/usr/lib/rpm/redhat/redhat-hardened-cc1：No such file or directory
    error: command 'gcc' failed with exit status 1  
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KvBr7R/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ssGvVL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-KvBr7R/cryptography/

**Comment by crisewng** [comment]
@fedora1125  sudo dnf install redhat-rpm-config 安装这个就可以了
