### ISSUE TITLE
在资产列表添加资产节点时，资产节点不显示，同时添加资产选择节点时不再有default/节点名称

### ISSUE THREAD

**Issue by shuboGe** [jumpserver/jumpserver#4575]
[简述你的问题]
在资产列表添加资产节点时，资产节点不显示，同时添加资产选择节点时不再有default/节点名称
会
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. 资产列表-资产节点-新建节点-输入名称后-显示创建完成
2. 在资产节点看不到新创建的节点
3、再次创建同名的节点---提示 **更新时发生未知错误**

##### 具体表现[截图可能会更好些,最好能截全]
![jump1](https://user-images.githubusercontent.com/50095637/91963644-b47cf780-ed40-11ea-8128-c183f36b20c9.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
刷新一下页面看看呢
