### ISSUE TITLE
Windows是不是不能开启加密RDP？今后会支持吗？

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#4576]
[简述你的问题]
最初发现Windows远程桌面都无法连接，后来看到文档里有描述“远程设置 不要勾选 仅允许运行使用网络级别身份验证的远程桌面的计算机连接(建议)(N)”，看上去是不支持加密RDP连接，那今后有可能会支持吗？测试过几个闭源的堡垒机，都能启用加密RDP，加密RDP更安全嘛……

##### 使用版本
[2.2.1]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by bigbird1985** [comment]
可以支持，用户名格式要写成user@domain.com格式

**Comment by Gianthard-XYZ** [comment]
> 可以支持，用户名格式要写成[user@domain.com](mailto:user@domain.com)格式

谢谢，非域环境也要这么写？只能用user@domain.com么？还是可以用xxxxx\user的方式？
因为不在域环境，用你说的这种方式能登陆吗？domain随意用什么替代吗？
谢谢

**Comment by ibuler** [comment]
Guacamole 是支持加密的，JumpServer 通过系统平台的特殊设置，也支持了加密

![image](https://user-images.githubusercontent.com/17382885/92087610-48f95f80-edfe-11ea-8909-bfe02d17eed2.png)

**Comment by Gianthard-XYZ** [comment]
> Guacamole 是支持加密的，JumpServer 通过系统平台的特殊设置，也支持了加密
> 
> ![image](https://user-images.githubusercontent.com/17382885/92087610-48f95f80-edfe-11ea-8909-bfe02d17eed2.png)

okay，感谢，我马上测试一下

**Comment by Gianthard-XYZ** [comment]
领域

> Guacamole 是支持加密的，JumpServer 通过系统平台的特殊设置，也支持了加密
> 
> ![image](https://user-images.githubusercontent.com/17382885/92087610-48f95f80-edfe-11ea-8909-bfe02d17eed2.png)

我测试了一下，发现虽然我选了TLS，但保存后再点进去却发现选项变成了空的，这是什么问题？然后设备依然无法登陆……
