### ISSUE TITLE
2.1.0版本通过web界面刷新资产和测试连接均失败,但是通过ssh客户端可以连接

### ISSUE THREAD

**Issue by caojielinux** [jumpserver/jumpserver#4578]
[简述你的问题]

##### 使用版本
2.1.0

##### 使用浏览器版本
Chrome

##### 问题复现步骤
2.1.0版本通过web界面刷新资产和测试连接均失败,但是通过ssh客户端可以连接

##### 具体表现[截图可能会更好些,最好能截全]
![7700B9D8-1324-4d91-BE7A-F229CC609EA8](https://user-images.githubusercontent.com/43571451/92076894-f152f800-eded-11ea-9c9f-ccff2a5c4edb.png)
![99360BB1-A022-4b09-9624-58FFBA6039E3](https://user-images.githubusercontent.com/43571451/92076898-f31cbb80-eded-11ea-99f7-d1e732597083.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
登录使用的是 系统账号，测试连接和更新硬件信息用的是 管理账号，或许是你的管理账号配置的不对
