### ISSUE TITLE
启动过程mariadb服务起不来，怎么调试？

### ISSUE THREAD

**Issue by panghu1986** [jumpserver/jumpserver#4579]
[简述你的问题]

Job for mariadb.service failed because the control process exited with error code. See "systemctl status mariadb.service" and "journalctl -xe" for details.

手动也起不了，可否帮忙协助一下。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个就不清楚了，建议 google 一下
