### ISSUE TITLE
V2.2.2 容器部署 mariadb redis外置 部署后 2222端口不通，防火墙inactive状态

### ISSUE THREAD

**Issue by gantengjun** [jumpserver/jumpserver#4581]
[简述你的问题]
V2.2.2 容器部署 mariadb redis外置 部署后 2222端口不通，防火墙inactive状态

##### 使用版本
2.2.2

##### 使用浏览器版本
正在更新 Google Chrome (47%)
版本 84.0.4147.135

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/51731822/92191414-52360b00-ee96-11ea-890a-ba1dfa989afe.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
jumpserver没有正常启动

**Comment by gantengjun** [comment]
jumpserver怎么启动了？要进容器？

**Comment by gantengjun** [comment]
怎么查看了或者启动了 要去容器中看？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "老广"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 上午10:17
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;; 
抄送: "gantengjun"<252491673@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jumpserver/jumpserver] V2.2.2 容器部署 mariadb redis外置 部署后 2222端口不通，防火墙inactive状态 (#4581)





 
jumpserver没有正常启动

**Comment by gantengjun** [comment]
搞好了，docker logs -f jms_all，显示数据库
![image](https://user-images.githubusercontent.com/51731822/92195839-7a2a6c00-eea0-11ea-851f-26a7ee002efe.png)
docker run 的时候 ，DB_USER=root,改成jumpserver;
