### ISSUE TITLE
后期是否可以在会话管理-在线会话-监控界面添加相关的用户信息，登录信息，资产信息等等

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4582]
[简述你的问题]

后期是否可以在会话管理-在线会话-监控界面添加相关的用户信息，登录信息，资产信息等等
1：因为当有多个在线会话的时候，打开了其中一个会话监控后，时间长了再想知道是打开的哪个会话监控比较麻烦
2：后期是否可以支持在监控界面添加终止用户操作的按钮，当用户操作危险命令的时候，可以及时制止
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
合理的需求，安排一下
