### ISSUE TITLE
容器部署后，防火墙需要开放的端口有哪些，80 2222都开放了 客户端telnet 80是通的 2222不通  关闭防火墙可以进入首页

### ISSUE THREAD

**Issue by gantengjun** [jumpserver/jumpserver#4583]
[简述你的问题]

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
自行研究一下防火墙
