### ISSUE TITLE
移除系统用户,主机上的系统用户并未删除

### ISSUE THREAD

**Issue by hanxinhisen** [jumpserver/jumpserver#4584]
[简述你的问题]

##### 使用版本
v2.2.2
##### 使用浏览器版本
 Chrome 85.0.4183.83

##### 问题复现步骤
1. [步骤1]
docker 方式部署
在系统用户中移除资产,或在资产中移除系统用户，系统用户在主机上依然存在
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
移除主机上用户太危险，需要自己手动处理
