### ISSUE TITLE
某个资产能具体指定某个系统用户吗？

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#4586]
[简述你的问题]
目前我是给某个用户在一个权限规则里分配了N个Windows和Linux的资产，并将这些资产有不同的系统用户（因为密码各有不同）授权给了用户，不过没有开自动推送，现在用户在使用的时候，点击任何资产，都会弹出选项要求选择具体的系统用户。
在资产不多的情况下还好，资产一多，选择可能会比较麻烦……

非常感谢！

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.1

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
85.0.4183.83

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by leim** [comment]
同这个问题，对特定资产分配特定用户进行登录，真是太需要了

**Comment by ibuler** [comment]
系统用户可以单独为某个资产设置密码，如果你建立的系统用户，除了密码不一样，别的都一样，那么可以把几个系统用户合并一下，具体操作：

进入 系统用户详情，右侧的资产列表：

可以为资产单独设置

**Comment by Gianthard-XYZ** [comment]
> 系统用户可以单独为某个资产设置密码，如果你建立的系统用户，除了密码不一样，别的都一样，那么可以把几个系统用户合并一下，具体操作：
> 
> 进入 系统用户详情，右侧的资产列表：
> 
> 可以为资产单独设置

你好，我查看了这个地方，确实有个单独配置，但是问题是，输入密码后没有保存按钮……
然后我又尝试将之前创建的那些系统用户中资产列表中的其他资产删掉，只保留系统用户对应的资产，但在实际使用的时候依然会列出所有系统用户……
