### ISSUE TITLE
RDP会话白屏

### ISSUE THREAD

**Issue by toclyc** [jumpserver/jumpserver#4587]
[简述你的问题]
通过RDP连接的资产，在web内打开均是白屏

##### 使用版本
JumpServer版本   2.0.1

##### 使用浏览器版本
Chrome 85.0.4183.83 

##### 问题复现步骤
无法复现

##### 具体表现[截图可能会更好些,最好能截全]
以前是正常使用，没有问题，后面突然间，通过RDP连接的资产，在web内打开均是白屏，会话管理-终端管理，gua组件激活、在线状态都为绿色
通过尝试，停止gua组件，删除gua容器，重新部署gua容器，并重新注册成功后，依然是打开后白屏
![image](https://user-images.githubusercontent.com/70417589/92318922-87cd2680-f045-11ea-8fe6-60d329d09399.png)
![image](https://user-images.githubusercontent.com/70417589/92318925-90256180-f045-11ea-8cf4-9eaa402fd4e0.png)
![image](https://user-images.githubusercontent.com/70417589/92318930-9ca9ba00-f045-11ea-84a2-3493a8586418.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by toclyc** [comment]
经过测试，发现问题在google浏览器，后将缓存清理，重新打开，恢复正常

**Comment by ibuler** [comment]
右击新窗口打开呢？

**Comment by toclyc** [comment]
> 右击新窗口打开呢？

已经解决，清空浏览器缓存，重新访问即可打开

**Comment by aiaiduo** [comment]
> 右击新窗口打开呢？
我也遇到过，右击打开新窗口和开启无痕模式都不行，最后是清理浏览器缓存后恢复正常。
