### ISSUE TITLE
Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“

### ISSUE THREAD

**Issue by 447475489** [jumpserver/jumpserver#4589]
[简述你的问题]
通过RDP连接的Windows网域资产，在web内打开均提示“连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。”

##### 使用版本
2.2.1

##### 使用浏览器版本
 Chrome 85.0.4183.83 ]

##### 问题复现步骤
1. 添加网域Windows资产
2. 通过RDP连接网域Windows资产

##### 具体表现[截图可能会更好些,最好能截全]
以前是正常使用，没有问题，docker部署插件后（**和Jumpserver不在一台服务器，因为Jumpserver是CentOS6不支持docker**），通过RDP连接的资产，在web内打开提示”“连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“，会话管理-终端管理，gua组件激活、在线状态都为绿色
通过尝试，停止gua组件，删除gua容器，重新部署gua容器，并重新注册成功后，依然是打开后问题依旧。
![image](https://user-images.githubusercontent.com/45656189/92344410-fb7c3b80-f0f8-11ea-8d22-934ed2c53b03.png)
![image](https://user-images.githubusercontent.com/45656189/92344432-0e8f0b80-f0f9-11ea-972c-625b96fa37ff.png)
![image](https://user-images.githubusercontent.com/45656189/92344510-3c745000-f0f9-11ea-93b8-487147ffe686.png)
![image](https://user-images.githubusercontent.com/45656189/92344546-56ae2e00-f0f9-11ea-90a1-3d663faf9068.png)

##### 其他
1、网域网关测试连接正常
2、Jumpserver到网域网关设备的telnet 22端口正常也能ping通，网域网关设备到网域Windows资产的3389端口正常，也能ping通

[注:] 完成后请关闭 issue

**Comment by haitang5445** [comment]
我也出现了，一开始以为公网有问题，后来在内网访问也会出现
![image](https://user-images.githubusercontent.com/59681546/93191129-c3b76880-f776-11ea-96a2-89818ad5b9fc.png)

**Comment by 447475489** [comment]
解决了可以分享一下吗？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Tuesday, September 15, 2020 5:14:11 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


我也出现了，一开始以为公网有问题，后来在内网访问也会出现
[image]<https://user-images.githubusercontent.com/59681546/93191129-c3b76880-f776-11ea-96a2-89818ad5b9fc.png>

―

**Comment by haitang5445** [comment]
能否告知我们看哪个日志 2333

**Comment by mach8686devops** [comment]
我也遇到了 版本2.3.1😂

**Comment by mach8686devops** [comment]
windows设置远程连接允许打开，还有就是不要公有云别自认为密钥可以正常，更改为密码已经解决了此问题。感谢楼上的分享！

**Comment by 447475489** [comment]
你是说网关改用密码吗？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: mach8686devops<mailto:notifications@github.com>
发送时间: 2020年9月26日 17:43
收件人: jumpserver/jumpserver<mailto:jumpserver@noreply.github.com>
抄送: xingtong<mailto:tx447475489@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


windows设置远程连接允许打开，还有就是不要公有云别自认为密钥可以正常，更改为密码已经解决了此问题。感谢楼上的分享！

―

**Comment by haitang5445** [comment]
我采用分离式部署，将guacamole降级到1.5.9后，暂时没发现windows中断的情况了

**Comment by 447475489** [comment]
我的组件也是分离式部署的，都是docker部署的，组件可以不和jms同版本么，这么说新版本的组件有bug咯。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 一只小菜鸟<mailto:notifications@github.com>
发送时间: 2020年9月28日 11:55
收件人: jumpserver/jumpserver<mailto:jumpserver@noreply.github.com>
抄送: xingtong<mailto:tx447475489@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


我采用分离式部署，将guacamole降级到1.5.9后，暂时没发现windows中断的情况了

―

**Comment by haitang5445** [comment]
我从2.1.2 测到2.3.0 都发现，当连windows，在其桌面打开应用的时候，大概率出现中断的情况。而很早以前部署的1.5.7版本未发现这类情况，于是我抱着尝试的心理将gua降级到1.5.9后，暂时未发现问题。你可以试试，不知道有没有用

**Comment by haitang5445** [comment]
![Uploading image.png…]()

**Comment by 447475489** [comment]
感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Monday, September 28, 2020 3:15:41 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


我从2.1.2 测到2.3.0 都发现，当连windows，在其桌面打开应用的时候，大概率出现中断的情况。而很早以前部署的1.5.7版本未发现这类情况，于是我抱着尝试的心理将gua降级到1.5.9后，暂时未发现问题。你可以试试，不知道有没有用

―

**Comment by 447475489** [comment]
昨天降级到1.5.9了还是有连不上Windows网域设备的情况，就提示这个。
[cid:image002.png@01D6963F.5BFFDFD0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 童 星<mailto:tx447475489@live.com>
发送时间: 2020年9月28日 15:18
收件人: jumpserver/jumpserver<mailto:reply@reply.github.com>; jumpserver/jumpserver<mailto:jumpserver@noreply.github.com>
抄送: Author<mailto:author@noreply.github.com>
主题: 回复: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)

感谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用


发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Monday, September 28, 2020 3:15:41 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


我从2.1.2 测到2.3.0 都发现，当连windows，在其桌面打开应用的时候，大概率出现中断的情况。而很早以前部署的1.5.7版本未发现这类情况，于是我抱着尝试的心理将gua降级到1.5.9后，暂时未发现问题。你可以试试，不知道有没有用

―

**Comment by haitang5445** [comment]
看不见图片，邮件发的图片是不是有问题。。。。

**Comment by 447475489** [comment]
提示如下：

连接错误
无法连接服务器，请联系系统管理员或查看日志。


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 一只小菜鸟<mailto:notifications@github.com>
发送时间: 2020年9月29日 9:40
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


看不见图片，邮件发的图片是不是有问题。。。。

―

**Comment by haitang5445** [comment]
终端管理中gua在线么

**Comment by 447475489** [comment]
在线，都是Windows网域设备，有的可以连有的不行（提示如上所说），排除防火墙远程设置等基本设置，网关到Windows设备网络端口都是通的。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Tuesday, September 29, 2020 9:58:00 AM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


终端管理中gua在线么

―

**Comment by haitang5445** [comment]
![image](https://user-images.githubusercontent.com/59681546/94504448-61ad3780-023b-11eb-8237-88774033dcb7.png)
不要勾选

**Comment by haitang5445** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_rdp/   你检查下是不是有些勾选了有些没有勾选

**Comment by 447475489** [comment]
图片好像挂了，看不到。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Tuesday, September 29, 2020 10:06:23 AM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


[image]<https://user-images.githubusercontent.com/59681546/94504448-61ad3780-023b-11eb-8237-88774033dcb7.png>
不要勾选

―

**Comment by haitang5445** [comment]
那个链接有帮助么？

**Comment by 447475489** [comment]
没，这个设置之前看过了，都是最最基础的配置。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Tuesday, September 29, 2020 3:05:47 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


那个链接有帮助么？

―

**Comment by haitang5445** [comment]
连不上的windows 有没有什么共同点

**Comment by 447475489** [comment]
Docker和nginx都没日志，好像没有发起请求一样。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Tuesday, September 29, 2020 3:17:00 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


连不上的windows 有没有什么共同点

―

**Comment by haitang5445** [comment]
![image](https://user-images.githubusercontent.com/59681546/96242373-fc489d00-0fd5-11eb-91de-a4b83ff112bb.png)
哈哈 2.4.0这个gua 还是一如既往的凉凉

**Comment by 447475489** [comment]
那看来没有升级的必要。。。。。。。不注重基础功能的完善，步子跨太大了。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 一只小菜鸟 <notifications@github.com>
发送时间: Friday, October 16, 2020 5:36:20 PM
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: xingtong <tx447475489@live.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


[image]<https://user-images.githubusercontent.com/59681546/96242373-fc489d00-0fd5-11eb-91de-a4b83ff112bb.png>
哈哈 2.4.0这个gua 还是一如既往的凉凉

―

**Comment by 447475489** [comment]
我用nginx实现了，哈哈哈，然后集成到jumpserver，稳得一匹。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 一只小菜鸟<mailto:notifications@github.com>
发送时间: 2020年10月16日 17:36
收件人: jumpserver/jumpserver<mailto:jumpserver@noreply.github.com>
抄送: xingtong<mailto:tx447475489@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


[image]<https://user-images.githubusercontent.com/59681546/96242373-fc489d00-0fd5-11eb-91de-a4b83ff112bb.png>
哈哈 2.4.0这个gua 还是一如既往的凉凉

―

**Comment by jym503558564** [comment]
- windows资产打开允许远程连接。
![image](https://user-images.githubusercontent.com/40739051/109285781-73cbea00-785c-11eb-9003-eb90a3eb4f68.png)

@447475489 该问题现在还存在吗？如还存在可再次打开Issues

**Comment by zjcnew** [comment]
我的也出现了此问题，2008 r2系统一直以来都正常，今天突然就这样了，死活连不上。jumpserver version v2.3.1，Linux服务器一切正常，Windows全线瘫痪。。

**Comment by zjcnew** [comment]
> 我的也出现了此问题，2008 r2系统一直以来都正常，今天突然就这样了，死活连不上。测试mstsc远程桌面直接连接Windows一切正常，就jumpserver不行。jumpserver version v2.3.1，Linux服务器一切正常，Windows全线瘫痪。。
> ![企业微信截图_20210524110505](https://user-images.githubusercontent.com/22335594/119290846-ec85eb00-bc7f-11eb-9062-3a82e99b7ff3.png)

jms_guacamole容器没有任何日志输出，jumpserver日志我附下面了。
[jms.log](https://github.com/jumpserver/jumpserver/files/6529592/jms.log)
[jumpserver.log](https://github.com/jumpserver/jumpserver/files/6529594/jumpserver.log)

**Comment by 447475489** [comment]
2.10的新组件试过没，远程Windows效果咋样。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年5月24日 11:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jumpserver/jumpserver] Windows网域资产提示”连接出错，联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。“ (#4589)


我的也出现了此问题，2008 r2系统一直以来都正常，今天突然就这样了，死活连不上。测试mstsc远程桌面直接连接Windows一切正常，就jumpserver不行。jumpserver version v2.3.1，Linux服务器一切正常，Windows全线瘫痪。。
[企业微信截图_20210524110505]<https://user-images.githubusercontent.com/22335594/119290846-ec85eb00-bc7f-11eb-9062-3a82e99b7ff3.png>

jms_guacamole容器没有任何日志输出，jumpserver日志我附下面了。
jms.log<https://github.com/jumpserver/jumpserver/files/6529592/jms.log>
jumpserver.log<https://github.com/jumpserver/jumpserver/files/6529594/jumpserver.log>

―
