### ISSUE TITLE
建议kubernetes资产、应用资产提供使用网域功能

### ISSUE THREAD

**Issue by deerjoe** [jumpserver/jumpserver#4593]
[简述你的问题]

Kubernetes功能比较实用，但是k8s资产位于不可连通的子网内，希望完善一下网域功能，让应用资产和kubernetes资产也能通过网域穿透。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，之前设计不够周到，没有关联网域，所以还得改进改进

**Comment by ibuler** [comment]
已排期

**Comment by kys1230** [comment]
期待 应用资产(MySQL)支持网域, 目前 jumpserver 在单独的网络环境, 通过网域链接各个区域的主机群, 不支持网域目前无法使用..

**Comment by ibuler** [comment]
已支持 v2.6
