### ISSUE TITLE
/opt/py3/bin/python /opt/jumpserver/jms start all -d 放在计划任务里执行报错，请问怎么在计划任务里写。

### ISSUE THREAD

**Issue by lianfulei** [jumpserver/jumpserver#4598]
/opt/py3/bin/python /opt/jumpserver/jms start all -d 
放在计划任务里crontab执行报错，请问怎么在计划任务里写启动命令！

**Comment by lhc19890816** [comment]
要先载入py3虚拟环境，试试这样行不行
source /opt/py3/bin/activate && /opt/jumpserver/jms start all -d &>/dev/null

**Comment by lianfulei** [comment]
最终写法
source /opt/py3/bin/activate && /opt/jumpserver/jms start all -d;deactivate
