### ISSUE TITLE
jenkins如何绕过堡垒机

### ISSUE THREAD

**Issue by jiangfeiyu** [jumpserver/jumpserver#4599]
[简述你的问题]
想通过jenkins   publish over ssh 部署到堡垒机后的测试机，是否支持？支持的话需要操作？

##### 使用版本
 2.x.x

##### 使用浏览器版本
 Chrome

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不支持
