### ISSUE TITLE
migrate 错误

### ISSUE THREAD

**Issue by berlinsaint** [jumpserver/jumpserver#460]
![image](https://cloud.githubusercontent.com/assets/10629930/26483323/0438a04c-421f-11e7-8b29-33089071a34a.png)
初始化 数据key有错误

**Comment by berlinsaint** [comment]
另外 fixtures/init.json 下的json最后少一个] 符号

**Comment by berlinsaint** [comment]
第一个错帮你们看楼下  ，INNODB引擎 索引不能超767 byte 你们的为1000的 字段创建了索引

**Comment by ibuler** [comment]
ok

**Comment by ibuler** [comment]
fixed
