### ISSUE TITLE
sftp中文编码以及新加用户账号推送

### ISSUE THREAD

**Issue by qiyongxiao** [jumpserver/jumpserver#4601]
[简述你的问题]
v2.1.0版本的
请问，我用securityfx工具上传文件时，发现这里的中文乱码，我尝试了utf8，gbk，gb18030，default，none都不行，这里用的是什么编码？
![image](https://user-images.githubusercontent.com/7349963/92431171-639a5280-f1c9-11ea-8ea8-874e7cc9d19e.png)

另外，我原来的资产授权是给用户组进行授权的。现在我将新用户添加到这个组里面，在用户资产授权这里没有，需要到系统用户那里重新添加一下授权。这个操作步骤我也无奈操作了，可是为什么还要我自己手动推送一下用户信息，这个不是自动推送的吗（我设置的就是自动推送，这个没有定时任务是吗）？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
securityfx 勾选 utf-8
软件问题，与 JumpServer 无关， Xftp 也有此问题
