### ISSUE TITLE
iOS下登录web的时候白屏，进度条不停反复，页面似乎在不停刷新

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#4612]
[简述你的问题]
用ios登录web的时候白屏，进度条不停反复，页面似乎在不停刷新，尝试了chrome和safari都一样，请问这是什么情况？
P.S.尝试了两台设备都一样。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.1

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
iPhone 10
iOS 13.7
Chrome 85.0.4183.92
Safari 版本不明……已经更新至最新

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
登录页面也无法看到？

**Comment by Gianthard-XYZ** [comment]
> 登录页面也无法看到？

谢谢你的回复

可以看到登录页面，在登录输入完二步密码后就进入我描述的状况，但今天我再尝试，在多次刷新后最终还是进入了web界面，只是界面比较乱
但环境也有变化了，目前服务器已经是2.4.0版本，iOS是14.0.1了，浏览器也相应进行了升级，但之前可以确定，至少数分钟后都没有进入web界面，今天大约不到一分钟的样子登录进去了
