### ISSUE TITLE
测试发现的问题列表，请看看能不能改

### ISSUE THREAD

**Issue by pan2za** [jumpserver/jumpserver#4614]
[简述你的问题]
1.	仪表盘>活跃用户资产占比：鼠标放在相应位置一直跳动 
2.	未找到对源地址和账户的访问控制
3.	历史会话无法对用户进行查询
4.	未找到通过管理方式进行审计记录
5.	未找到通过操作内容进行审计记录
6.	命令记录中部分命令未解析正确 
7.	告警功能未实现
8.	超时锁功能生效时再次操作界面应跳到登陆页面
9.	未找到制定和修改安全策略功能

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
chrome 版本 79.0.3945.88（正式版本） （64 位）

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

如问题
##### 其他

无
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. 仪表盘>活跃用户资产占比：鼠标放在相应位置一直跳动
v2.0修复了

2. 未找到对源地址和账户的访问控制
计划排期中

3. 历史会话无法对用户进行查询
支持的

4. 未找到通过管理方式进行审计记录
不明白

5. 未找到通过操作内容进行审计记录
不明白

6. 命令记录中部分命令未解析正确
计划中

7. 告警功能未实现
计划中

8. 超时锁功能生效时再次操作界面应跳到登陆页面
是这样的

9. 未找到制定和修改安全策略功能
不支持
