### ISSUE TITLE
推送用户serial是1, 单线程太慢了

### ISSUE THREAD

**Issue by oldthreefeng** [jumpserver/jumpserver#4615]
[简述你的问题]

推送用户serial 感觉是1, 单线程太慢了.  几十几百台机器. 跑半天
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.4
官网安装

如何提高并发,有的话在哪设置?   类似 ansible-playbook  -f 10 . 提高并发为10.  @ibuler 

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
默认是 5，目前不支持更改

**Comment by oldthreefeng** [comment]
> 默认是 5，目前不支持更改

有修改的打算么?
