### ISSUE TITLE
希望jumpserver支持，k8s APP上传kubeconfig

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4617]
[简述你的问题]
希望jumpserver支持，k8s APP上传kubeconfig
某些托管集群需要证书访问api server，现有页面不支持配置证书

##### 使用版本
2.2.1
##### 使用浏览器版本
不重要
##### 问题复现步骤
不重要
##### 其他

[注:] 完成后请关闭 issue

**Comment by whiskyy** [comment]
或者是可以增加上传证书功能

**Comment by ibuler** [comment]
目前在优化账号这里，如果支持证书的话，系统用户还需要添加一个证书的字段，等账号优化完成了支持一下

**Comment by whiskyy** [comment]
感谢

**Comment by seaurching** [comment]
我在istio的k8s集群中部署了之后，web终端建立连接后一会就自动断开了。这个是相关的截图。
![image](https://user-images.githubusercontent.com/7349963/113376036-65b14200-93a3-11eb-883f-3ad9ee9bb226.png)
