### ISSUE TITLE
2.2.2 启用CAS认证登录用户登录手动点“退出”后页面不能自动跳转

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4619]
[简述你的问题]
2.2.2 启用CAS认证登录用户登录手动点“退出”后页面不能自动跳转，浏览器使用chrome 85，一直在“退出登录成功，返回到登录页面，”，然后在该浏览器中输入登录地址不需要密码验证仍可自动登录，config.yml配置内容详见图片。
##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28044296/92691397-1824a780-f375-11ea-819d-de3cbd79043a.png)

![image](https://user-images.githubusercontent.com/28044296/92691182-c5e38680-f374-11ea-9742-23be2f1479fc.png)
![image](https://user-images.githubusercontent.com/28044296/92691230-d7c52980-f374-11ea-9e60-5ad85667e01e.png)
![image](https://user-images.githubusercontent.com/28044296/92691457-2e326800-f375-11ea-947a-1585da3530eb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Shangxj** [comment]
我也碰到了一模一样的问题，请问这个怎么解决呢

**Comment by aiaiduo** [comment]
我记得新版本就不存在这个问题，你可以测试下新版本。
















在 2021-01-22 15:08:45，"商学军" <notifications@github.com> 写道：

我也碰到了一模一样的问题，请问这个怎么解决呢
