### ISSUE TITLE
无法为用户分配资产

### ISSUE THREAD

**Issue by radishboo** [jumpserver/jumpserver#4620]
[简述你的问题]
进行资产授权后，用户在“web终端”无法看到资产

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.2.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
chrome 59.0.3071.115（正式版本） （64 位）
firefox 80.0.1 （64 位）

##### 问题复现步骤
1. 新建资产
2. 新建资产的管理用户
3. 新建资产的系统用户
4. 为admin账户授权资产

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/23442863/92691323-fb886f80-f374-11ea-89f5-8f79427099da.png)
![图片](https://user-images.githubusercontent.com/23442863/92691368-0cd17c00-f375-11ea-9224-3fc726a362b8.png)
![图片](https://user-images.githubusercontent.com/23442863/92691400-18bd3e00-f375-11ea-8e2d-0fd450651bc4.png)
![图片](https://user-images.githubusercontent.com/23442863/92691441-25419680-f375-11ea-9eaa-63b1acaa6adb.png)
![图片](https://user-images.githubusercontent.com/23442863/92691456-2d013b00-f375-11ea-9a7f-6e2d82f46b05.png)

##### 其他
之前正常过，不知进行了什么操作，再也看不到资产了。数据全部删除重新来一遍也看不到。

[注:] 完成后请关闭 issue

**Comment by zhengdazhi** [comment]
我也遇到相同的问题

**Comment by wojiushixiaobai** [comment]
刷新缓存看看。
资产授权 - 创建授权那里可以下拉，选择刷新授权缓存

确定授权有效（注意时间同步下 NTP）

**Comment by wojiushixiaobai** [comment]
@orangexw 把服务器时间调准

**Comment by orangexw** [comment]
@wojiushixiaobai 服务器时间准确，是内网环境使用。

**Comment by radishboo** [comment]
@orangexw 我的问题确实是服务器时间问题，选择的开始时间不对。
授权有效性应该就是判断的时间有效性，时间改正后红叉会变成绿勾。
