### ISSUE TITLE
模糊搜索功能

### ISSUE THREAD

**Issue by yxiaoy6** [jumpserver/jumpserver#4622]
[简述你的问题]
系统用户没有自动推送成功。去手动推送，但是资产页面不能模糊搜索。

##### 使用版本
v2.0.2

##### 问题复现步骤

![image](https://user-images.githubusercontent.com/43592152/92716438-634cb380-f391-11ea-80f2-560570dfd85e.png)

![image](https://user-images.githubusercontent.com/43592152/92716500-7bbcce00-f391-11ea-8b38-60e34fae3f04.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by HuanMeng0** [comment]
附议，只能精确搜索是缺陷

**Comment by ibuler** [comment]
系统用户和管理用户详情中，从设计上是存在问题的，这个不应该是资产列表，而是账号列表。

或者应该有两个 TAB，一个资产列表，一个账号列表

**Comment by jym503558564** [comment]
在2.7.1版本中，已经重构设计，资产列表和账号列表。
