### ISSUE TITLE
新版本的鼠标右键粘贴的问题

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#4623]
[简述你的问题]
新版后添加了鼠标选中即可用右键粘贴，如果不小心选中多行，按下右键后会将选中内容的在命令行全部粘贴，这会导致很多没必要的报错。
希望可以有一个设置项来设置右键的功能。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.2.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
火狐80.0.1

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by vyunwei** [comment]
我遇到的问题是从其他位置复（txt、notepad、其他工具）制粘贴过来粘贴，还是上一次在浏览器复制的内容，不能粘贴最新复制的内容

**Comment by ibuler** [comment]
可以考虑添加上配置
