### ISSUE TITLE
批量更新，终端管理的存储介质时，gua组件报错

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4624]
[简述你的问题]
批量更新，终端管理的存储介质时，gua组件报错，导致无法连接windows

##### 使用版本
Version v2.2.1 GPLv2.

##### 使用浏览器版本
 85.0.4183.83

##### 问题复现步骤
1.点击这个
![image](https://user-images.githubusercontent.com/28191563/92874682-d52d0780-f43a-11ea-9b5e-73b0a0a121d9.png)
2.
![image](https://user-images.githubusercontent.com/28191563/92874729-dfe79c80-f43a-11ea-8a6f-6a729889a208.png)

##### 其他
稳定复现，这块倒不是刚需，但是多gua组件不能同时连接多个windows的问题和kubeconfig证书的问题希望给处理下

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
目前 kubeconfig 仅支持 token 的形式

**Comment by ibuler** [comment]
批量更新那里有bug  @orangemio ，更新填写的内容是 name，不是 id，另外 更多操作 下拉 文案改为 更新存储
