### ISSUE TITLE
“命令过滤”优化建议

### ISSUE THREAD

**Issue by N-lucky** [jumpserver/jumpserver#4625]
[简述你的问题]

匹配 “命令过滤设置的命令”时，类似 “精准匹配”，如果能设置成 “类似模糊匹配” 可能更好。
例如下面图片中：
我在JumpServer的 命令过滤 界面，配置 “reboot” 命令是 拒绝；
连接Linux资产（SUSE11系统）；
普通用户使用重启命令需要执行 “命令的绝对路径”，不然不生效；
执行 "reboot" 命令时，JumpServer识别到此命令，提示拒绝，
但执行 "sudo /sbin/reboot" 命令时，JumpServer识别不到 “reboot” 字符，使得此命令生效。

##### 使用版本
JumpServer版本  2.2.2 

##### 使用浏览器版本
Chrome 84.0.4147.105

##### 具体表现[截图可能会更好些,最好能截全]
![](https://s4.51cto.com/images/blog/202009/11/1709f066fd0d3e0329d5ab06093c906c.jpg?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=)

**Comment by ibuler** [comment]
不太好实现，没想好

**Comment by ryswork1993** [comment]
不是支持正则吗，用正则包含所有关于关键字的方式

**Comment by N-lucky** [comment]
> 不是支持正则吗，用正则包含所有关于关键字的方式

**Comment by N-lucky** [comment]
> 不是支持正则吗，用正则包含所有关于关键字的方式

不行，正则的格式是  “字符|字符”。例如配置 "*reboot|*reboot*"为拒绝，在执行 "sudo reboot"时是不会拦截这个命令的，正则配置没有生效。

**Comment by ibuler** [comment]
其实意义不大吧，现在匹配用的是 search，如果可以的话需要用match

**Comment by LeeEirc** [comment]
@N-lucky 应该是可以使用正则完成。命令解析，使用v2.7.0版本试一下。
