### ISSUE TITLE
Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by sunsymbol** [jumpserver/jumpserver#463]
TypeError at /assets/asset/create/
Unicode-objects must be encoded before hashing
Request Method:	POST
Request URL:	http://10.211.55.5:8080/assets/asset/create/
Django Version:	1.11.1
Exception Type:	TypeError
Exception Value:	
Unicode-objects must be encoded before hashing
Exception Location:	/root/jumpserver/apps/assets/models/user.py in private_key_file, line 84
Python Executable:	/usr/bin/python
Python Version:	3.6.1
Python Path:	
['/root/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/root/jumpserver',
 '/root/jumpserver/apps']

**Comment by sunsymbol** [comment]
已解决 84行 key_name = md5((self._private_key).encode('utf-8')).hexdigest()

**Comment by ibuler** [comment]
resolved
