### ISSUE TITLE
创建资产的时候提交出现：Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by bingoku** [jumpserver/jumpserver#464]
TypeError at /assets/asset/create/
Unicode-objects must be encoded before hashing
Request Method:	POST
Request URL:	http://docker-registry.py3k.com:8080/assets/asset/create/
Django Version:	1.11.1
Exception Type:	TypeError
Exception Value:	
Unicode-objects must be encoded before hashing
Exception Location:	/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84
Python Executable:	/usr/bin/python
Python Version:	3.6.1
Python Path:	
['/opt/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']
Server time:	星期日, 28 五月 2017 00:18:27 +0800

**Comment by zsjohny** [comment]
@ibuler  
 更新资产授权 :
```
Exception Type: | TypeError
-- | --
Unicode-objects must be encoded before hashing
/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84
/usr/bin/python
```

**Comment by ibuler** [comment]
fixed
