### ISSUE TITLE
仪表盘   权限管理   创建权限规则  这一步出现问题

### ISSUE THREAD

**Issue by cp-m** [jumpserver/jumpserver#465]
TypeError at /perms/asset-permission/create
Unicode-objects must be encoded before hashing
Request Method:	POST
Request URL:	http://120.76.102.150:8080/perms/asset-permission/create
Django Version:	1.11.1
Exception Type:	TypeError
Exception Value:	
Unicode-objects must be encoded before hashing
Exception Location:	/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84
Python Executable:	/usr/bin/python
Python Version:	3.6.1
Python Path:	
['/opt/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']
Server time:	星期日, 28 五月 2017 09:23:54 +0800

**Comment by ibuler** [comment]
fixed
