### ISSUE TITLE
v2.2.2 个人用户无法更新公钥

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#4653]
[简述你的问题]

个人信息--> 更新SSH公钥

更新并没有生效，包括页面显示都没有变化，目前只能通过管理员更新用户，设置SSH公钥可以更新成功

##### 使用版本
v2.2.2

##### 使用浏览器版本
Chrome及safari都试过不行

##### 问题复现步骤
1. 更新个人公钥
2. 然后刷新页面，显示还是老的，并没有上传更新

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/16998173/93285749-3290d200-f808-11ea-9715-15e1eaf5d049.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
启用LDAP认证后，就不能设置公钥，所以这个页面看不到才对

**Comment by BigbigY** [comment]
![image](https://user-images.githubusercontent.com/16998173/93422251-f5027680-f8e5-11ea-97f2-59a6175c3095.png)

我启动了LDAP，用户登陆后更新SSH公钥就会到这个页面，需要用户自己上传自己的公钥，但是上传不成功

**Comment by BigbigY** [comment]
上传提示上传成功，但是刷新后并没有上传成功

**Comment by ibuler** [comment]
使用LDAP后，这里不应该出现更新密钥的按钮的，修复一下

**Comment by 5jen** [comment]
重置秘钥也不成功, 非LADP用户就可以, 这个是否也需要修复

**Comment by BigbigY** [comment]
@ibuler 使用LDAP的用户要通过密钥连接jumpserver,但是如果用户key丢失或者第一次上传公钥请问下在哪可以操作，还是说用了ldap后的用户只能通过账号密码来ssh连接堡垒机了

**Comment by dingpamaoo** [comment]
使用ldap登录的用户不能使用密钥登录，只能用ldap的密码，这个我记得之前有人问过。
我是写了个程序定时把ldap登录的用户改成数据库用户😂

**Comment by ibuler** [comment]
迁移一下回答，假如 使用LDAP登录，也设置了公钥登录，用户离职后，在 LDAP 中删除了用户，或设置了禁用，无法完成LDAP认证，但是用户却使用公钥登录了，这个问题就比较棘手，所以除了数据库认证，都关闭了设置公钥和使用公钥登录。

**Comment by ibuler** [comment]
后续再考虑一下优化

**Comment by omigo** [comment]
这个问题也结论了吗，我们也发现 开启 CAS　后，部分用户　无法 SSH 登录了。
