### ISSUE TITLE
remoteApp窗口最小化后，无法找回

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#4657]
打开微软原生的由remoteApp发布出来的应用，最小化后会在本地任务栏，可以“找回”。
而通过JumpServer的RemoteApp功能打开的应用窗口最小化后，却“消失”了，用户无法接着使用。因此需要支持用户能自助找回。

**Comment by ibuler** [comment]
remote app 不再社区功能中，可以联系对应的销售
