### ISSUE TITLE
remoteApp窗口背景色调整

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#4658]
目前remoteApp打开后背景色时黑色，用户不知道是否发生了问题，特别是当应用窗口最小化后，点哪都没反应，让人抓狂，不利于推广。
建议调成windows标准的背景色或者允许用户/管理员可调。

**Comment by ibuler** [comment]
removeApp 不再社区功能中，如果是企业用户，请联系对应的销售
