### ISSUE TITLE
coco 连上操作一会，会自己卡死

### ISSUE THREAD

**Issue by cp-m** [jumpserver/jumpserver#466]
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 2, 'command': 'ls', 'output': '', 'timestamp': 1495944098.0787811}]
coco          | 2017-05-28 04:01:43 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 2, 'command': 'ls', 'output': '', 'timestamp': 1495944098.0787811}]
coco          | Exception in thread Thread-4:
coco          | Traceback (most recent call last):
coco          |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
coco          |     self.run()
coco          |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
coco          |     self._target(*self._args, **self._kwargs)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
coco          |     self.action(data)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
coco          |     d['output'] = base64.b64encode(d['output']).decode("utf-8")
coco          |   File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
coco          |     encoded = binascii.b2a_base64(s, newline=False)
coco          | TypeError: a bytes-like object is required, not 'str'
coco          |
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:01:44 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:01:44 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:01:44 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:01:48 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 1, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944095.5945272}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 3, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944099.4355934}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 4, 'command': 'ls -anh', 'output': 'total 24K                                                                       \ndrwx------  2 1005 ', 'timestamp': 1495944104.0031745}]
coco          | 2017-05-28 04:01:49 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 1, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944095.5945272}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 3, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944099.4355934}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 4, 'command': 'ls -anh', 'output': 'total 24K                                                                       \ndrwx------  2 1005 ', 'timestamp': 1495944104.0031745}]
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:01:49 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:01:49 [basehttp INFO] "POST /api/audits/v1/command-log/ HTTP/1.1" 201 421
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/audits/v1/command-log/ HTTP/1.1" 201 421
coco          | 2017-05-28 04:01:49 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/audits/v1/command-log/ HTTP/1.1" 201 421
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:01:49 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:01:49 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:01:49 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:01:53 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 5, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944106.659906}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 6, 'command': 'cd /opt/', 'output': '', 'timestamp': 1495944109.1381927}]
coco          | 2017-05-28 04:01:54 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 5, 'command': 'pwd', 'output': '/home/my                                                                        ', 'timestamp': 1495944106.659906}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 6, 'command': 'cd /opt/', 'output': '', 'timestamp': 1495944109.1381927}]
coco          | Exception in thread Thread-3:
coco          | Traceback (most recent call last):
coco          |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
coco          |     self.run()
coco          |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
coco          |     self._target(*self._args, **self._kwargs)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
coco          |     self.action(data)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
coco          |     d['output'] = base64.b64encode(d['output']).decode("utf-8")
coco          |   File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
coco          |     encoded = binascii.b2a_base64(s, newline=False)
coco          | TypeError: a bytes-like object is required, not 'str'
coco          |
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:01:54 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:01:54 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:01:54 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:01:58 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:01:59 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:01:59 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:01:59 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 7, 'command': 'ls', 'output': 'app                                                                             \nblue               ', 'timestamp': 1495944111.4535458}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 8, 'command': 'cd /tmp/', 'output': '', 'timestamp': 1495944115.5612931}]
coco          | 2017-05-28 04:02:00 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 7, 'command': 'ls', 'output': 'app                                                                             \nblue               ', 'timestamp': 1495944111.4535458}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 8, 'command': 'cd /tmp/', 'output': '', 'timestamp': 1495944115.5612931}]
coco          | Exception in thread Thread-2:
coco          | Traceback (most recent call last):
coco          |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
coco          |     self.run()
coco          |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
coco          |     self._target(*self._args, **self._kwargs)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
coco          |     self.action(data)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
coco          |     d['output'] = base64.b64encode(d['output']).decode("utf-8")
coco          |   File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
coco          |     encoded = binascii.b2a_base64(s, newline=False)
coco          | TypeError: a bytes-like object is required, not 'str'
coco          |
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 9, 'command': 'ls', 'output': 'Aegis-<Guid(5A2C30A2-A87D-490A-9281-6765EDAD7CBA)>                              \nbksuite.log        ', 'timestamp': 1495944116.775077}]
coco          | 2017-05-28 04:02:01 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 9, 'command': 'ls', 'output': 'Aegis-<Guid(5A2C30A2-A87D-490A-9281-6765EDAD7CBA)>                              \nbksuite.log        ', 'timestamp': 1495944116.775077}]
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:02:01 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:02:01 [basehttp INFO] "POST /api/audits/v1/command-log/ HTTP/1.1" 201 141
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/audits/v1/command-log/ HTTP/1.1" 201 141
coco          | 2017-05-28 04:02:01 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/audits/v1/command-log/ HTTP/1.1" 201 141
jumpserver    | 2017-05-28 12:02:03 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:02:04 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:02:04 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:02:04 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:02:08 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:02:09 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:02:09 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:02:09 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:root:Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 10, 'command': 'tail -f git_pull_docker.log', 'output': '', 'timestamp': 1495944124.636118}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 11, 'command': 'ls -anh', 'output': '7                                                                               \n-rw-r--r--   1 0 0 ', 'timestamp': 1495944127.632317}]
coco          | 2017-05-28 04:02:12 [tasks DEBUG] Sending data: [{'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 10, 'command': 'tail -f git_pull_docker.log', 'output': '', 'timestamp': 1495944124.636118}, {'proxy_log_id': 2, 'user': 'admin', 'asset': '120.44.11.22', 'system_user': 'my', 'command_no': 11, 'command': 'ls -anh', 'output': '7                                                                               \n-rw-r--r--   1 0 0 ', 'timestamp': 1495944127.632317}]
jumpserver    | 2017-05-28 12:02:13 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | Exception in thread Thread-1:
coco          | Traceback (most recent call last):
coco          |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
coco          |     self.run()
coco          |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
coco          |     self._target(*self._args, **self._kwargs)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
coco          |     self.action(data)
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
coco          |     d['output'] = base64.b64encode(d['output']).decode("utf-8")
coco          |   File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
coco          |     encoded = binascii.b2a_base64(s, newline=False)
coco          | TypeError: a bytes-like object is required, not 'str'
coco          |
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-05-28 04:02:14 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-05-28 12:02:14 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | 2017-05-28 04:02:14 [connectionpool DEBUG] http://jumpserver:8080 "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-05-28 12:02:18 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | Exception in thread Thread-10:
coco          | Traceback (most recent call last):
coco          |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
coco          |     self.run()
coco          |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
coco          |     self._target(*self._args, **self._kwargs)
coco          |   File "/opt/coco/coco/app.py", line 133, in process_request
coco          |     InteractiveServer(self).run()
coco          |   File "/opt/coco/coco/interactive.py", line 294, in run
coco          |     self.dispatch()
coco          |   File "/opt/coco/coco/interactive.py", line 127, in dispatch
coco          |     return self.search_and_proxy(option=option, from_result=twice)
coco          |   File "/opt/coco/coco/interactive.py", line 268, in search_and_proxy
coco          |     self.return_to_proxy(asset, system_user)
coco          |   File "/opt/coco/coco/interactive.py", line 285, in return_to_proxy
coco          |     proxy_server.proxy()
coco          |   File "/opt/coco/coco/proxy.py", line 199, in proxy
coco          |     self.get_output()
coco          |   File "/opt/coco/coco/proxy.py", line 71, in get_output
coco          |     self.output = parser.parse_output(b''.join(self.output_data))
coco          |   File "/usr/local/lib/python3.6/site-packages/jms/utils.py", line 187, in parse_output
coco          |     self.stream.feed(data)
coco          |   File "/usr/local/lib/python3.6/site-packages/pyte/streams.py", line 378, in feed
coco          |     return super(ByteStream, self).feed(chars)
coco          |   File "/usr/local/lib/python3.6/site-packages/pyte/streams.py", line 166, in feed
coco          |     send(char)
coco          |   File "/usr/local/lib/python3.6/site-packages/pyte/streams.py", line 315, in _parser_fsm
coco          |     dispatch(csi[char], *params)
coco          |   File "/usr/local/lib/python3.6/site-packages/pyte/streams.py", line 215, in dispatch
coco          |     handler(*args, **kwargs)
coco          |   File "/usr/local/lib/python3.6/site-packages/pyte/screens.py", line 688, in erase_in_display
coco          |     for line in interval:
coco          | UnboundLocalError: local variable 'interval' referenced before assignment

**Comment by ibuler** [comment]
py3的问题貌似，string和bytes

**Comment by choldrim** [comment]
后面一个问题是上游`pyte`库的问题：https://github.com/selectel/pyte/issues/79

**Comment by ibuler** [comment]
same with #698
