### ISSUE TITLE
Default language and timeout

### ISSUE THREAD

**Issue by dbrifox** [jumpserver/jumpserver#4668]
Is it possible to set the default language for all users to english? 
How can we setup a timeout for idle websessions?

Thank you.

**Comment by wojiushixiaobai** [comment]
We have done the internationalization process, the page will be based on the current browser preferred language as the display language.

websessions
```
cd /opt/jumpserver
vi config.yml
```
```
SESSION_COOKIE_AGE: 86400  # The number is in seconds
```

**Comment by dbrifox** [comment]
We're using browsers with default language to portuguese - brazil, the login page is displayed in english but after login it changes to chineses and we need to manually change it to english.

**Comment by wojiushixiaobai** [comment]
@dbrifox Thanks for the feedback, we have reproduced the problem and we will fix it as soon as possible

**Comment by ibuler** [comment]
https://github.com/jumpserver/lina/pull/481  fix this
