### ISSUE TITLE
创建用户时邮件的设置无法换行

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#4671]
[简述你的问题]
1. 创建用户时，自定义的邮件内容无法换行。
2. 如果想要将邮件内容设置为全英文，只有在系统为英文的情况下才生效。在中文系统下，配置英文邮件内容，邮件中显示的内容是中英混合。
3. 在自定义邮件内容的时候是否可以将默认的给去掉，这样可以将邮件内容完全自定义，至于用户名以及URL 啥的，可以变量形式代替。比如像这样的设置（只是个例子）
Welcome to use JumpServer System. Your jumpserver account had created done. Pls click below link to set password.

Link: "{{ JMS_Link }}"
UserName: "{{ JMS_UserName }}"
Password: "{{ JMS_ChangePass }}"

Password check rule:
* Password minimum length 8
* Must contain capital letters
* Must contain lowercase letters
* Must contain numeric characters
* Must contain special

4. 我在设置了邮件署名后，发送出来的邮件并没有显示署名。**

##### 使用版本
JMS 2.2.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
的确应该这样，但优先处理一下更紧急的issue，也欢迎你能实现，PR过来
