### ISSUE TITLE
在web terminal一段时间没有操作时候(时间不固定)，需要刷新网页才可以连接服务器

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#4672]
[简述你的问题]

在web terminal一段时间没有操作时候(时间不固定)，需要刷新网页才可以连接服务，在点击收藏夹旁边的刷新按钮的时候，一直显示加载中。

##### 使用版本
JMS 2.2.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![图片](https://user-images.githubusercontent.com/63391681/93549128-3b65dd00-f99b-11ea-9813-3b4dbb9be9ef.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
v2.3做了这个方面的优化，不会再出现这个问题了

**Comment by ibuler** [comment]
如果还有这个问题，请重新打开issue
