### ISSUE TITLE
VNC远程Ubuntu服务器频繁断开

### ISSUE THREAD

**Issue by ehui168** [jumpserver/jumpserver#4673]
[简述你的问题]
VNC远程Ubuntu服务器频繁断开

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.2.2
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
Chrome 84.0.4147.125
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34931383/93584938-9f5ac680-f9d8-11ea-8036-62663efd50f7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果有多层nginx，记得都设置 websocket那个upgrade，记得 ip_hash

**Comment by ehui168** [comment]
没有多层Nginx哟，Jumpserver堡垒机按官方文档一键安装的，Ubuntu服务器单机，堡垒机直连它

**Comment by ehui168** [comment]
补充：本地电脑通过VNC Viewer 客户端直连Ubuntu服务器，没有频繁断线重连情况

**Comment by ibuler** [comment]
你试试 RDP 断不断

**Comment by ehui168** [comment]
RDP不断哟，多个用户同时在远程，也没有断过，只有VNC会出现这个问题

**Comment by LeeEirc** [comment]
@ehui168 请问安装的VNC server是什么？
