### ISSUE TITLE
是否有开发说明相关文档？ （咨询）

### ISSUE THREAD

**Issue by shenmou98** [jumpserver/jumpserver#4674]
[简述你的问题]
请问下是否有开发说明的相关文档？ 
看到[wiki](https://github.com/jumpserver/jumpserver/wiki)中是有一些 REST API规范约定、Jumpserver 项目规范（Draft)、项目骨架的链接的， 但这些链接已全部失败，点开全是跳转到文档首页。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
更新后，丢失了[尴尬]

**Comment by ibuler** [comment]
https://github.com/jumpserver/docs/blob/backup/api_style_guide.rst
https://github.com/jumpserver/docs/blob/backup/project_structure.rst
https://github.com/jumpserver/docs/blob/backup/python_style_guide.rst
