### ISSUE TITLE
如何删除会话历史记录

### ISSUE THREAD

**Issue by Fancy-Guo** [jumpserver/jumpserver#4675]
[简述你的问题]
录像信息,录像文件/opt/jumpserver/data/media/replay 已删除
如何删除会话管理的历史会话记录呢

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
有定期清理，也可以手动数据库清理，定期清理

![image](https://user-images.githubusercontent.com/17382885/93728753-e2dd4c80-fbf3-11ea-83b6-d8e5bf8336e9.png)

**Comment by Fancy-Guo** [comment]
> 
> 
> 有定期清理，也可以手动数据库清理，定期清理
> 
> ![image](https://user-images.githubusercontent.com/17382885/93728753-e2dd4c80-fbf3-11ea-83b6-d8e5bf8336e9.png)

能否请教下手动数据库清理

**Comment by Fancy-Guo** [comment]
Jumpserver会产生的数据主要涉及mysql 的：
Terminal_command 历史命令
Terminal_session 录像信息,录像文件/opt/jumpserver/data/media/replay
Users_loginlog 登陆信息
Audits_operatelog 操作日志
Audits_ftplog 文件上传日志
Audits_passwordchangelog 改密日志

**Comment by zjcnew** [comment]
@Fancy-Guo 有自动推送的系统用户，jumpserver是不是会自动定期为所有资产推送系统用户，这个能不能更改推送时间间隔或计划任务的时间？

**Comment by Fancy-Guo** [comment]
已从数据库删除
