### ISSUE TITLE
V2.2.2 Linux客户端系统的命令行中选中内容后右击就直接粘贴选中的内容的这个功能能否自行设置取消

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4676]
[简述你的问题]
V2.2.2 在Linux客户端系统的命令行中选中内容后右击就直接将选中的内容进行粘贴，这个容易误操作，能否手动取消这个功能，让我右键自行点击“粘贴”选项来进行粘贴。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
V2.2.2
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![20200921](https://user-images.githubusercontent.com/28044296/93729100-96930c00-fbf5-11ea-8fe8-4f815e245eeb.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
v2.3 已提供了设置

**Comment by aiaiduo** [comment]
> v2.3 已提供了设置

嗯，好的，多谢！
