### ISSUE TITLE
Connect websocket server error

### ISSUE THREAD

**Issue by itshu** [jumpserver/jumpserver#4678]
[简述你的问题]
配置好资产，管理用户和系统用户，点击测试连接
提示：Connect websocket server error
连不上window7服务器、为啥？？？？？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
1.5.6

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
Chrome 84.0.4147.105

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/3169117/93737029-9b1aed00-fc14-11ea-8d75-cd11c79f6368.png)
![image](https://user-images.githubusercontent.com/3169117/93737042-a706af00-fc14-11ea-8b73-0de56edd6da6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果有多次nginx，记得都要设置 Nginx 的 Upgrade
