### ISSUE TITLE
资产列表是default组，添加资产后，打开web终端是favorite组

### ISSUE THREAD

**Issue by caixuechun** [jumpserver/jumpserver#4681]
[简述你的问题]
资产列表是default组，添加资产后，打开web终端是favorite组
看不到添加的资产。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.3.0
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
chrome
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
截图看一看

**Comment by caixuechun** [comment]
你好，解决了，是我没有授权。谢谢回复~我去结束问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 晚上6:45
收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送:&nbsp;"蔡薛春"<18640935@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] 资产列表是default组，添加资产后，打开web终端是favorite组 (#4681)





 
截图看一看
