### ISSUE TITLE
系统用户指定资产推送

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#4682]
系统用户支持推送到指定的资产，用户可以自行选择推送到指定的资产

**Comment by dingpamaoo** [comment]
你用的什么版本？我用2.2.1已经可以推送用户到指定资产了啊。
![image](https://user-images.githubusercontent.com/8704246/94091341-98094200-fe4a-11ea-8c50-417385d362f7.png)

**Comment by wojiushixiaobai** [comment]
@dingpamaoo 多个资产

**Comment by jym503558564** [comment]
在2.7.1版本已支持
![image](https://user-images.githubusercontent.com/40739051/109286506-46cc0700-785d-11eb-93ce-55a718677fe3.png)
