### ISSUE TITLE
希望可以支持标签栏的左右移动

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#4683]
[简述你的问题]
1. 希望可以支持web端的server 标签左右移动，使用鼠标可以拖动左右移动。
![图片](https://user-images.githubusercontent.com/63391681/93836536-b1c55080-fcb5-11ea-882e-3f7a5752d86a.png)

2. 点击上面的左右箭头没任何反应
![图片](https://user-images.githubusercontent.com/63391681/93836583-d28da600-fcb5-11ea-907f-0b9236036066.png)

##### 使用版本
JMS 2.2.2

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by dingpamaoo** [comment]
同求这个功能，希望能够手动给标签页排序

**Comment by jym503558564** [comment]
@Allenzhang-92  luna界面中的窗口列表可以选择切换资产。
![image](https://user-images.githubusercontent.com/40739051/109286870-c954c680-785d-11eb-91a5-1681375fd312.png)
