### ISSUE TITLE
工单通知以及仪表盘展示优化

### ISSUE THREAD

**Issue by wml3** [jumpserver/jumpserver#4684]
[简述你的问题]

当前工单功能没有站内通知以及外部邮件或其他方式通知，工单审批信息接收不及时，希望增加通知功能；
此外，在首页仪表盘展示页面，是否可以考虑增加工单统计信息的展示。

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]

Version v2.2.3

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已记录，内部已经开始计划，暂时关闭
