### ISSUE TITLE
功能优化（需求）

### ISSUE THREAD

**Issue by thirdcountry** [jumpserver/jumpserver#4687]
[简述你的问题]
需求来源：
当阿里云启用MFA认证后，登陆时可以选择7天内无需再次验证。

但是当堡垒机启用MFA认证后，每次登陆都要输MFA验证码，在开启多个SSH会话的场景下，就显得比较麻烦

所以能否让堡垒机让同一个用户在X天内只输入一次MFA验证码？

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
不涉及
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
不涉及
##### 问题复现步骤
1. [步骤1]
2. [步骤2]
不涉及
##### 具体表现[截图可能会更好些,最好能截全]

不涉及
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
ssh登录后，可以使用复制(克隆)会话，这样就不需要再次输入了。xshell, crt应该都是支持的

![image](https://user-images.githubusercontent.com/17382885/94531834-a94db680-026f-11eb-8f24-54c704c1e661.png)
