### ISSUE TITLE
windows无法看到 Guacamole Filesystem

### ISSUE THREAD

**Issue by shuoliu1** [jumpserver/jumpserver#4688]
##### 使用版本
jms_guacamole:1.5.9
jumpserver 1.5.9

##### 使用浏览器版本
 如 Chrome 84.0.4147.105 

##### 问题复现步骤
1. 登录服务器后无法看到RDP盘
2.文件上传后无法在远程机器上看到,可以在堡垒机服务器中/config/guacamole/drive/ 下的子目录找到

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/16146661/94014009-86d61c00-fddd-11ea-9f11-ec53918c337e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@shuoliu1 请使用新版本

**Comment by shuoliu1** [comment]
> @shuoliu1 请使用新版本

具体是什么问题呢

**Comment by ibuler** [comment]
应该和windows的安全配置有关系，换一台看看是不是好的
