### ISSUE TITLE
ssh终端使用b查看上一页时无效

### ISSUE THREAD

**Issue by dingpamaoo** [jumpserver/jumpserver#4689]
使用ssh终端查看资产，翻页时使用b查看上一页时无效，只是刷新了当前显示的页面。
试过xshell和secureCRT都不行，猜测应该不是终端软件的问题。

##### 使用版本
v2.2.1

##### 使用终端版本
![image](https://user-images.githubusercontent.com/8704246/94090619-aeae9980-fe48-11ea-8d82-8817dbffb5b1.png)
![image](https://user-images.githubusercontent.com/8704246/94090662-c5ed8700-fe48-11ea-9516-e49257d6ecc0.png)

##### 问题复现步骤
1. 使用终端ssh登录跳板机
2. 按p列出全部资产
3. 按n翻下一页
4. 按b翻上一页无效

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
测试 v2.3 没有发现问题，是不是没有上一页呀

**Comment by dingpamaoo** [comment]
> 测试 v2.3 没有发现问题，是不是没有上一页呀

是有的
![image](https://user-images.githubusercontent.com/8704246/95534943-c3c72300-0a19-11eb-96f0-7e584d60cd11.png)

**Comment by dingpamaoo** [comment]
等我更新了再试试吧

**Comment by dingpamaoo** [comment]
另外我用的是从docker hub上下载的镜像，会不会和这个有关系？
![image](https://user-images.githubusercontent.com/8704246/95535172-5f589380-0a1a-11eb-8904-951157c3c46d.png)
