### ISSUE TITLE
Connection Reset ByPeer

### ISSUE THREAD

**Issue by yin32167** [jumpserver/jumpserver#469]
请重视一下这个问题, 目前见到很多人提出来, 我自己也遇到了, 翻遍了文档和issues, 未见开发人员出来回复处理, 难道开发过程中未遇到? 希望能够重视一下, 指明原因

**Comment by sifksky** [comment]
赞一个. 我也遇到这个问题了,就是点击连接的时候出现这个问题的.测试过0.3.0 和 0.3.2 都有这个问题.

**Comment by choldrim** [comment]
可能是ssh的连接参数中`ServerAliveInterval`没有设置的原因，看看手动的在堡垒机的`/etc/ssh/ssh_config`加这项设置试试：`ServerAliveInterval 60`

**Comment by berlin493** [comment]
也遇到同样的问题，同时也在/etc/ssh/ssh_config中加了：ServerAliveInterval 60这项，问题依旧。希望作者能尽快解决这个问题

**Comment by liuhetongzi** [comment]
我也遇到这个问题了,就是点击连接的时候出现这个问题的,希望作者能尽快解决这个问题.

**Comment by qianghong000** [comment]
还没解决吗

**Comment by qianghong000** [comment]
已经解决，
经过测试，jms需要跑在80端口，通过nginx代理是不可以的！

**Comment by qianghong000** [comment]
已经解决，
经过测试，jms通过nginx代理是不可以的！

**Comment by yin32167** [comment]
@qianghong000     好像官方有提供nginx代理的方案, 但是设置没什么效果

**Comment by chinasjok** [comment]
真的不可以？？

**Comment by ibuler** [comment]
直接运行jumpserver没有遇到这种情况，如果使用Nginx代理有问题，应该是相关websocket设置问题

**Comment by ibuler** [comment]
same with #568
