### ISSUE TITLE
Jumpserver 2.3.0 Web终端使用的用户名错误，导致不能登录

### ISSUE THREAD

**Issue by zealinux** [jumpserver/jumpserver#4691]
[简述你的问题]
Jumpserver 2.3.0 Web终端使用的用户名错误，导致不能登录。
使用登录用户名，ec2-user，

但是web终端始终使用系统管理员的账号admin，

```
ssh admin@<IP>
```

导致不能登录。

JumpServer v2.3.0 docker版
Chrome 85

**Comment by wojiushixiaobai** [comment]
请修改系统用户为正确的系统用户，并授权。
