### ISSUE TITLE
CAS 配置问题

### ISSUE THREAD

**Issue by TIGERRAN** [jumpserver/jumpserver#4693]
[简述你的问题]
CAS 配置请教怎么配置

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
v2.2.3
##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
chrome 85.0.4183.102
##### 问题复现步骤
1. [步骤1]
cas按照core config.yml中去掉注释配置，配置完毕后不会跳到cas认证，直接就可以正常登陆了，配置如下：
# CAS 配置
```
AUTH_CAS: True
CAS_SERVER_URL: "https://test.cas/cas/1/66"
CAS_ROOT_PROXIED_AS: 'http://jumpserver.text.com:32637'
CAS_LOGOUT_COMPLETELY: False
CAS_VERSION: 1
```

2. [步骤2]
用管理文档中的cas配置，但是会报错
# CAS 配置
```
AUTH_CAS: True
CAS_SERVER_URL: "https://test.cas/cas/1/66"
CAS_ROOT_PROXIED_AS: 'http://jumpserver.text.com:32637'
CAS_LOGOUT_COMPLETELY: False
CAS_VERSION: 1
```
![image](https://user-images.githubusercontent.com/41050950/94132449-eaba1c80-fe91-11ea-991e-c78b234e9bb5.png)
![image](https://user-images.githubusercontent.com/41050950/94132474-f574b180-fe91-11ea-8d87-3eb17b854bb3.png)

还需要其他地方配置吗？还是配置有问题呢？
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
自签证书？

**Comment by TIGERRAN** [comment]
不是自签证书，花钱买的。

**Comment by wojiushixiaobai** [comment]
@TIGERRAN 检查下是不是配置不当，比如版本，都试试

**Comment by ibuler** [comment]
CAS版本是 v1 ? 这个还没有测试过

**Comment by TIGERRAN** [comment]
是的，CAS版本是 v1的，配置我也检查、测试好多遍了，应该是没有问题的；
@ibuler 大佬有时间可以测试下CASv1版本的

**Comment by ibuler** [comment]
已明确问题所在，并给使用库提交了 issue https://github.com/django-cas-ng/django-cas-ng/pull/258

**Comment by TIGERRAN** [comment]
@ibuler 大佬根据您以上说的修复后，现在登陆web登陆页面进行跳转cas用户验证后就提示403没有权限，这个权限是那里没有呢？
![image](https://user-images.githubusercontent.com/41050950/96113930-75cd8600-0f17-11eb-88f7-c0bbcb9c6d86.png)

**Comment by Gooooodman** [comment]
@TIGERRAN 解决了吗

**Comment by 78778443** [comment]
问题解决了吗？

**Comment by lixpng** [comment]
解决了吗？
