### ISSUE TITLE
远程Windows服务器录屏高清问题

### ISSUE THREAD

**Issue by zjcnew** [jumpserver/jumpserver#4695]
远程Windows服务器分辨率能不能再调高些，或怎么实现高清些，视频回放字体总是看不清楚，不便于审核。

**Comment by wojiushixiaobai** [comment]
@zjcnew emmmm，你的ID很优秀。。。

视频其实可以手动放大窗口，显示的大小跟用户连接资产的窗口一样。目前还没有做自适应，手动 ctrl++ 放大就行

**Comment by zjcnew** [comment]
@wojiushixiaobai 你的ID太过于低调。。。
ctrl++是调整浏览器缩放比例，看完视频还得调回来，有些繁琐，还有些low。实际上我需要的不是这个，你懂得~

**Comment by ibuler** [comment]
把浏览器窗口调大一下，默认就是全屏播放的

**Comment by zjcnew** [comment]
行、行吧。。
