### ISSUE TITLE
window2016主机上传下载问题

### ISSUE THREAD

**Issue by youpai** [jumpserver/jumpserver#4696]
[简述你的问题]
主机：windows 2016服务器版，权限只给上传，连接到服务器后不能看到G盘，上传文件，报错见截图，反复测试均是如此

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
jumperserver：v2.0.0

##### 使用浏览器版本
[请提供你使用的浏览器版本 如 Chrome 84.0.4147.105 ]
microsoft edge(chrome版): 84.0.522.59

##### 问题复现步骤
1. [步骤1]
主机授权，只给上传权限
2. [步骤2]
打开window主机，查看无G盘，上传文件失败，只有上传下载权限都给，才可以看到G盘，上传下载均可。

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/29447211/94224807-efc8ab80-ff25-11ea-9b0a-871c45ae1aa6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by youpai** [comment]
chrome浏览器：85.0.4183.121，存在同样问题。   
补充下：部署方式问docker，外部入口加了nginx组件，代理到后端jumpserver的nginx

**Comment by youpai** [comment]
下午升级到了最新版本v2.3.1，似乎没有这个问题，不过另外一个问题，所有windows的G盘都是同步共享的，是这样设计的吗，实测是这个现象。

**Comment by ibuler** [comment]
G盘是从服务器上挂载过去的，一个用户会分配一个目录，会挂到各个服务器上，这样做有个好处，就是上传上去后，登录别的服务器，可以直接复制过去，不用再上传了

**Comment by youpai** [comment]
同一用户下所有windows资源是共享的，不同用户之间是隔离的，是这样子吧

**Comment by youpai** [comment]
哦，对了，另外一个问题，系统主机是阿里云上2016 64位中文版，创建资产，系统平台选择“windows(2016)“，会导致登录失败，选择"windows"，登录是没有问题的。

**Comment by ibuler** [comment]
windows(2016) 其实遗留下来的一个问题，之前我们以为 windows 2016都会使用tls的加密方式，结果发现不是，所以不应该叫 windows 2016，而是 windows via TLS
