### ISSUE TITLE
请问是否可以给windows文件上传增加文件夹上传功能[提问] 

### ISSUE THREAD

**Issue by whiskyy** [jumpserver/jumpserver#4701]
**请描述您的问题.**
请问是否可以给windows文件上传增加文件夹上传功能

**Comment by wojiushixiaobai** [comment]
@whiskyy 目前只支持单文件的上传，这个受 Guacamole 的限制

**Comment by whiskyy** [comment]
> @whiskyy 目前只支持单文件的上传，这个受 Guacamole 的限制

谢谢您的回答
