### ISSUE TITLE
新用户重置密码点设置后无法正常返回登陆页V2.3.1

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#4704]
新用户在收到创建账户成功邮件后，点击重置密码点设置密码链接，在打开的重置密码页面输入密码确认设置后无法正常返回登陆页，页面一直处于Pending状态，手动转到登陆页可以用新密码正常登陆。

**Comment by jym503558564** [comment]
- 未复现该问题，新创建的用户收到邮件重置密码能够跳转至登录页面。
 - 管理员登录，查看系统设置-基本信息：当前站点URL是否设置正确？
![image](https://user-images.githubusercontent.com/40739051/109287630-cdcdaf00-785e-11eb-96f3-a6c5819d8865.png)

 - 如果该问题还存在，可再次打开issues。
