### ISSUE TITLE
jumpserver luna 终端无法使用[Question] 

### ISSUE THREAD

**Issue by zlylong** [jumpserver/jumpserver#4705]
jumpserver luna 终端无法使用，链接服务器仅显示光标，文件管理器可以用。
![iShot2020-09-27 09 41 32](https://user-images.githubusercontent.com/16534456/94353614-b323be00-00a5-11eb-8729-598f46be1a05.png)

通过脚本部署：
```
# 以下设置默认情况下不需要修改, 系统会自动生成随机字符串填入

# 需要安装的版本
Version=v2.3.1

# Jms 加密配置
SECRET_KEY=
BOOTSTRAP_TOKEN=

# 数据库 配置, 如果 数据库 安装在其他的服务器, 请修改下面设置
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=jumpserver
DB_PASSWORD=
DB_NAME=jumpserver

# Redis 配置, 如果 Redis 安装在其他的服务器, 请修改下面设置
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=

# 服务端口设置, 如果云服务器未备案请修改 http_port 端口为其他端口
http_port=80
ssh_port=2222

# 服务安装目录
install_dir=/root/jumpserver

Server_IP=`ip addr | grep 'state UP' -A2 | grep inet | egrep -v '(127.0.0.1|inet6|docker)' | awk '{print $2}' | tr -d "addr:" | head -n 1 | cut -d / -f1`
Docker_IP=`ip addr | grep docker.* | grep inet | awk '{print $2}' | head -n 1`
```

**Comment by ibuler** [comment]
按一下F12，看看 控制台 有没有报错

**Comment by zlylong** [comment]
> 按一下F12，看看 控制台 有没有报错

没有任何报错信息：
![image](https://user-images.githubusercontent.com/16534456/94354405-35fc4700-00ad-11eb-8b0b-c1657ebcf01b.png)

**Comment by zlylong** [comment]
nginx配置如下
```
server {
    listen 80;
    # server_name _;

    client_max_body_size 1024m;  # 录像及文件上传大小限制

    location /ui/ {
        try_files $uri / /index.html;
        alias /opt/lina/;
        expires 24h;
    }

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
        expires 24h;
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
        expires 24h;
    }

    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /ws/ {
        proxy_pass http://localhost:8070;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /core/ {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }
}
```

**Comment by ibuler** [comment]
代码应该是有问题的，确认是 v2.3.1 版本的代码，如果确认，请强刷一下浏览器，好像浏览器用的缓存的代码

**Comment by zlylong** [comment]
> 代码应该是有问题的，确认是 v2.3.1 版本的代码，如果确认，请强刷一下浏览器，好像浏览器用的缓存的代码

清除浏览器缓存都试过。无法使用。

**Comment by ibuler** [comment]
@zlylong 方便的时候，@orangemio 远程支持一下你，群里加一下 qq

**Comment by zlylong** [comment]
好的，谢谢。

**Comment by wojiushixiaobai** [comment]
@zlylong 此问题是 koko 异常（如未正常注册、或者宿主IP变更、宿主 firewalld 或者 iptables 变更导致）
脚本里面内置了 reset 命令可以处理

```
./jmsctl.sh reset koko
```

**Comment by zlylong** [comment]
> @zlylong 此问题是 koko 异常（如未正常注册、或者宿主IP变更、宿主 firewalld 或者 iptables 变更导致）
> 脚本里面内置了 reset 命令可以处理
> 
> ```
> ./jmsctl.sh reset koko
> ```
> 
> 如果问题依旧一样
> 
> ```
> systemctl restart docker
> ./jmsctl.sh reset koko
> ```
> 
> 即可

应该不是这个问题，实际上我是重启过相关服务的。

**Comment by wojiushixiaobai** [comment]
@zlylong 请发出对应的 log 以方便查看问题
```
docker logs -f jms_koko --tail 200
```

**Comment by zlylong** [comment]
> ```
> docker logs -f jms_koko --tail 200
> ```

[GIN] 2020/10/13 - 18:07:23 | 400 |   24.353445ms |   192.168.11.20 | GET      "/koko/ws/?X-Websocket-Header-X-Namespace=ssh"
2020-10-13 18:09:04 [ERRO] Conn[2a7d0af3-4682-4ead-bf53-3914680b20c4] did not found cache ssh client(admin@NC-APP)
2020-10-13 18:09:07 [ERRO] Conn[2a7d0af3-4682-4ead-bf53-3914680b20c4] did not found cache ssh client(admin@NC-Oracle)
2020-10-13 18:23:29 [ERRO] User zly Authenticate err: POST http://172.16.0.8:8080/api/v1/authentication/tokens/ failed, get code: 400, {"error":"password_failed","msg":"您输入的用户名或密 码不正确，请重新输入。 您还可以尝试 6 次（账号将被临时 锁定 30 分钟）"}
2020-10-13 18:23:40 [ERRO] Conn[60264898-4e44-4784-87b3-5d100857ad8b] did not found cache ssh client(admin@jumpserver)
2020-10-13 18:29:52 [ERRO] Ws miss required params (type and target_id).
[GIN] 2020/10/13 - 18:29:52 | 400 |   24.795011ms |   192.168.11.20 | GET      "/koko/ws/?X-Websocket-Header-X-Namespace=ssh"
2020-10-14 09:03:16 [ERRO] User zly Authenticate err: POST http://172.16.0.8:8080/api/v1/authentication/tokens/ failed, get code: 400, {"error":"password_failed","msg":"您输入的用户名或密 码不正确，请重新输入。 您还可以尝试 6 次（账号将被临时 锁定 30 分钟）"}
2020-10-14 09:03:24 [ERRO] Conn[bd9a8822-237e-4574-9daa-0c194fae2214] did not found cache ssh client(admin@jumpserver)
2020-10-14 09:04:11 [ERRO] Ws miss required params (type and target_id).
[GIN] 2020/10/14 - 09:04:11 | 400 |    26.00835ms |   192.168.11.20 | GET      "/koko/ws/?X-Websocket-Header-X-Namespace=ssh"

**Comment by wojiushixiaobai** [comment]
@zlylong 无法复现需要远程查看

**Comment by zlylong** [comment]
> @zlylong 无法复现需要远程查看

重新搭建了一个服务就正常了。。。怀疑是当初搭建的时候设置的密钥有问题。
