### ISSUE TITLE
用户触发登陆限制后，在哪里手动解除[Question] 

### ISSUE THREAD

**Issue by qingfengfenga** [jumpserver/jumpserver#4718]
**请描述您的问题.**
用户触发登陆限制后，在哪里手动解除，官方文档没找到哪里有写
![image](https://user-images.githubusercontent.com/41416092/94414398-e56d1280-01ae-11eb-9d2c-8119f746e5da.png)

**Comment by ibuler** [comment]
用户详情中，右侧快捷操作中

**Comment by qingfengfenga** [comment]
没有找到你说的快捷操作在哪里，我不是最新版本
![image](https://user-images.githubusercontent.com/41416092/94501443-68847c00-0234-11eb-9689-ea208b4c3c9d.png)

**Comment by ibuler** [comment]
那是因为这个用户没有被 block掉，如果被禁用了，右侧会有的

**Comment by qingfengfenga** [comment]
好的，我再试一下，昨天找了好久没找到，谢谢！
