### ISSUE TITLE
重新生成密钥时，第一次发到邮箱里的密钥密码就不能用了

### ISSUE THREAD

**Issue by linuxu2015** [jumpserver/jumpserver#472]
重新生成的也不知道密钥是什么

**Comment by ibuler** [comment]
表述不详细，没有截图和Jumpserver 版本

**Comment by qils** [comment]
重新生成秘钥时, 源码里面处理的方式是:  调用 api.py 里面的 gen_rand_pass() 函数随机生成一个16位的随机密码字符, 然后用登录的username, 新生成的密码作为参数来生成一个新的秘钥,并且重写公钥到authorized_keys,  私钥密码会在响应信息中返回, 所以重新生成秘钥时，秘钥密码会变, 新的私钥密码不在是第一次的密码
