### ISSUE TITLE
[Bug] 添加节点并迁移节点位置显示异常， && 资产添加节点异常

### ISSUE THREAD

**Issue by lujay** [jumpserver/jumpserver#4724]
**JumpServer 版本**
您所使用的 JumpServer 版本是？
v2.3.1
**浏览器 版本**
您所使用的 浏览器版本是? 
chrome 85.0.4183.102

**Bug 描述**
1.我在default下 新增子节点，在子节点上新增机器， 然后把子节点移动为和default同等级的节点，迁完就不显示了
2.添加资产，选择节点的时候，如果这个节点不存在， 系统不会报错， 而是直接创建， 导致在前端页面看不到该节点
3. 新增资产授权，对系统用户授权后， 在 系统用户 下 并没有看到授权后的资产列表，仍然需要手动添加
**Bug 重现步骤**
1.
    a.  资产管理-资产列表-default下 右键新增子节点
    b. 新增子节点test-添加服务器信息
    c. 迁移子节点-鼠标左键选中Prod，拖动Prod和default平级
    d. Prod节点消失， 刷新页面， Prod下面的服务器列表还在
2. 
    ![节点](https://user-images.githubusercontent.com/6263244/94505157-04b28100-023d-11eb-8344-886fabce705c.png)

    

     

**期待的正确结果**
1. Prod 节点正常显示
2. 在将资产添加进不存在的节点时，应该报错，此节点不存在，(节点列表可能是chrome缓存的)

**截图**
以下截图是问题1 的截图
![prod1](https://user-images.githubusercontent.com/6263244/94505169-09773500-023d-11eb-8b36-110829e43265.png)
![prod2](https://user-images.githubusercontent.com/6263244/94505171-0aa86200-023d-11eb-98d4-e70cba2e33bf.png)

以下是问题3 的截图
![image](https://user-images.githubusercontent.com/6263244/94506670-88ba3800-0240-11eb-9d73-e90faffa073c.png)
![image](https://user-images.githubusercontent.com/6263244/94506933-2281e500-0241-11eb-883c-3ad126de2589.png)

**Comment by ibuler** [comment]
节点移动没有做出限制，default 节点不能有 平级节点

**Comment by ibuler** [comment]
下个版本去掉了节点的移动
