### ISSUE TITLE
[Bug] 终端工具复制jumpserver资产界面

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4727]
**JumpServer 版本**
您所使用的 JumpServer 版本是？如 v2.2.1 (注: v1.5.9以下版本不再支持)
2.3.0
**浏览器 版本**
您所使用的 浏览器版本是? 如 Chrome 84.0.4147.105

**Bug 描述**
简要描述您碰到的问题
用xshell登录jumpserver，然后通过标题复制ssh渠道后的界面会自动输入一个字符
https://43.241.76.254:8888/
**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by ibuler** [comment]
截图看一下

**Comment by ryswork1993** [comment]
![image](https://user-images.githubusercontent.com/44529247/94510962-a8565e00-024a-11eb-9803-22d74b022ec6.png)
![image](https://user-images.githubusercontent.com/44529247/94510973-b0ae9900-024a-11eb-8245-0017b7121ef6.png)

**Comment by ibuler** [comment]
这个是不是你的xshell有设置呢，你重新新建一个连接试试，我本地没有复现

**Comment by ryswork1993** [comment]
xshell一直没动过，之前用着正常，可能jumpserver卡在哪了吧  等下个版本再说吧
