### ISSUE TITLE
centos7 jumpserver3 安装时候，报“错”

### ISSUE THREAD

**Issue by chenjack007** [jumpserver/jumpserver#473]
File "/opt/jumpserver/apps/jumpserver/settings.py", line 36, in <module>
    SECRET_KEY = CONFIG.SECRET_KEY or '2vym+ky!997d5kkcc64mnz06y1mmui3lut#(^wd=%s_qj$1%x'
TypeError: 'NoneType' object is not callable
执行命令如下：
python manage.py  migrate
很是无奈，求解

**Comment by ibuler** [comment]
配置文件没有copy
