### ISSUE TITLE
系统用户 -- 资产列表-资产删除失败

### ISSUE THREAD

**Issue by lujay** [jumpserver/jumpserver#4730]
**JumpServer 版本**
您所使用的 JumpServer 版本是
v2.3.1 
**浏览器 版本**
 Chrome 85.0.4183.102

**Bug 描述**
系统用户 -- 资产列表-资产删除失败

**Bug 重现步骤**
如下图

**期待的正确结果**
系统用户下正常删除资产

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/6263244/94512645-1b61d380-024f-11eb-8e4d-62877e5e4da2.png)

**Comment by ibuler** [comment]
目前在用的密码，可以更新一个，再删除这个

**Comment by ibuler** [comment]
其实这里设计上有些问题

**Comment by ibuler** [comment]
需求已添加 https://github.com/jumpserver/jumpserver/issues/4733，重构这里的逻辑

**Comment by ibuler** [comment]
这里暂时先关闭了
