### ISSUE TITLE
[Bug] 开启MFA认证后，登录时需要下载Google Authenticator应用，但是登录页面给出的二维码中国区用户无法使用

### ISSUE THREAD

**Issue by zengyongjie** [jumpserver/jumpserver#4736]
开启MFA认证后，登陆时需要下载Google Authenticator应用，但是登录页面给出的二维码中国区用户无法使用

**Comment by ibuler** [comment]
说明一下版本，后续应该是有修复的

**Comment by zengyongjie** [comment]
> 说明一下版本，后续应该是有修复的

Version 1.4.8-2

**Comment by ibuler** [comment]
哦，那是因为 腾讯商店下架了那个应用，后续版本更新了，你可以升级到 1.5.9 版本

**Comment by zengyongjie** [comment]
> 下架了那个应用，后续版本更新了，你可以升级到 1.5.9 版本

好的 谢谢。
