### ISSUE TITLE
v0.4 的 api 怎么通过 url 访问，GET 输登录的账户也一直报403。

### ISSUE THREAD

**Issue by sunsymbol** [jumpserver/jumpserver#474]
v0.4 的 api 怎么通过 url 访问，GET 输登录的账户也一直报403。

**Comment by ibuler** [comment]
需要认证，可以查看 user里面的支持的认证方式，最简单的可以复制 浏览器的cookie进去

**Comment by sunsymbol** [comment]
我把 cookie 下载下来试了下 发现还是 {"detail":"Authentication credentials were not provided."}，能给个用 curl 调用 api 的例子嘛

**Comment by sunsymbol** [comment]
我把 cookie 下载下来试了下 发现还是 {"detail":"Authentication credentials were not provided."}，能给个用 curl 调用 api 的例子嘛

**Comment by choldrim** [comment]
```shell
curl -XPOST -d 'username=$username&password=$pwd' http://jms-host:port/api/users/v1/token/
# {"Token":"47b44dfbd4194f89a2a8ed9c4bcdd2xx","Keyword":"Bearer"}
```

```shell
curl -H 'Authorization: Bearer 47b44dfbd4194f89a2a8ed9c4bcdd2xx'  http://jms-host:port/api/assets/v1/assets/
```

**Comment by sunsymbol** [comment]
curl -XPOST -d 'username=admin&password=admin' http://jumpserver:8080/api/users/v1/token/
# {"Token":"0468729f688d4635ad5c77731c9d9426","Keyword":"Bearer"}

curl -H 'Authorization:Bearer 0468729f688d4635ad5c77731c9d9426' http://jumpserver:8080/api/assets/
返回：{"detail":"Invalid token or cache refreshed."} 无效

**Comment by sunsymbol** [comment]
curl -XPOST -d 'username=admin&password=admin' http://jumpserver:8080/api/users/v1/token/

`# {"Token":"0468729f688d4635ad5c77731c9d9426","Keyword":"Bearer"}`

curl -H 'Authorization:Bearer 0468729f688d4635ad5c77731c9d9426' http://jumpserver:8080/api/assets/
返回：{"detail":"Invalid token or cache refreshed."} 无效

**Comment by sunsymbol** [comment]
```
curl -XPOST -d 'username=admin&password=admin' http://jumpserver:8080/api/users/v1/token/
# {"Token":"0468729f688d4635ad5c77731c9d9426","Keyword":"Bearer"}
```
```
curl -H 'Authorization:Bearer 0468729f688d4635ad5c77731c9d9426' http://jumpserver:8080/api/assets/
```
返回：{"detail":"Invalid token or cache refreshed."} 无效

**Comment by choldrim** [comment]
@sunsymbol 刚fix的bug，你拉取dev分支的最新版

**Comment by sunsymbol** [comment]
@choldrim 好的 谢谢诶
