### ISSUE TITLE
[Feature] 资产变更事件及订阅功能

### ISSUE THREAD

**Issue by tangx** [jumpserver/jumpserver#4747]
**请描述您的需求或者改进建议.**

## 描述

prometheus 使用 consul 作为数据源，以动态管理监控对象列表。

现在想实现以 jumpserver 作为数据源的 agent， 以管理维护 consul 中的数据字段。

目前通过文档和 API 等相关信息， 发现只能通过不断轮训 asset/asset 接口更新数据。

## 疑问或需求

请问 ，jumpserver 本身已有 或计划生成资产事件变更事件？

**Comment by ibuler** [comment]
目前还没有收到其他用户的这个需求，所以暂无有计划，等用户多了，再考虑
