### ISSUE TITLE
[Bug] 添加资产发生错误，测试连接、更新硬件时常失灵并且无法登陆web终端

### ISSUE THREAD

**Issue by Teddyzhao94** [jumpserver/jumpserver#4749]
**JumpServer 版本(v1.5.9以下不再支持)**
您所使用的 JumpServer 版本是？
v2.3.1
**浏览器版本**
您所使用的 浏览器版本是?
chrome 85.0.4183.121
**Bug 描述**
1.在添加华为云公网上的测试服务器及生产服务器时，有时可以测试连接和更新硬件但是大多数情况不行。
2.用户无法正常通过系统用户登陆web终端。
提示的报错已经全部找过原因，目前网上没有任何一种方法是有效的，目标资产的ssh、系统环境、防火墙策略、hostallow、hostdeny全部没有问题，/var/log/secure日志中显示的是Received disconnect from *****IP***** port 54088:11: disconnected by user，应该是连接方主动断开的，但是完全不应该这样，/var/log/messages显示的也是连接成功后立刻断开。

**Bug 重现步骤(有截图更好)**
1.
  [WARNING]: Unhandled error in Python interpreter discovery for host UAT: Failed
to connect to the host via ssh: ssh_exchange_identification: read: Connection
reset by peer

[WARNING]: sftp transfer mechanism failed on [*****IP******]. Use
ANSIBLE_DEBUG=1 to see detailed information

[WARNING]: scp transfer mechanism failed on [*****IP*****]. Use
ANSIBLE_DEBUG=1 to see detailed information

fatal: [UAT]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"*****IP*****\". Make sure this host can be reached over ssh: ssh_exchange_identification: read: Connection reset by peer\r\n", "unreachable": true}
2. 
![image](https://user-images.githubusercontent.com/72121962/94661457-a7e8c080-0339-11eb-9164-c61a77b51cab.png)
3. 
![image](https://user-images.githubusercontent.com/72121962/94661292-707a1400-0339-11eb-9827-245c9fdf00c0.png)

**Comment by ibuler** [comment]
手动使用 ansible 试试
