### ISSUE TITLE
Python使用mysqldb连接mysql抛出errorclass errorvalue？

### ISSUE THREAD

**Issue by yyjinlong** [jumpserver/jumpserver#475]
查了下，MySQLdb does not support Python 3 。

使用python3.6 执行makemigrations时报错，现在只能换成python27来搞。恕我愚钝，不知道你们用python3.6时是否遇到该问题，谢谢。

**Comment by ibuler** [comment]
https://github.com/PyMySQL/mysqlclient-python  不谢
