### ISSUE TITLE
希望能够添加web资产

### ISSUE THREAD

**Issue by zzunc** [jumpserver/jumpserver#4751]
我们经常需要管理各种应用系统，主要的管理方式除了登录主机外，有时候也需要使用web访问的方式，进入系统，进行设置。
能否在ssh/telnet/RDP等方式外，添加web资产，使用堡垒机进行web访问，资产的内容可以是URL，含http和https方式，服务器的地址和端口使用URL，用户名和密码自动填充，如果需要，可以手动输入验证码。
十分感谢JumpServer给我们带来的便利。

**Comment by orangemio** [comment]
商业版支持Windows的RemoteApp 远程应用，可以满足你的需求。
