### ISSUE TITLE
请问，有时候有新版本的时候，系统却提示当前版本已经是最新是什么情况？

### ISSUE THREAD

**Issue by LUOZhen-huan** [jumpserver/jumpserver#4753]
**请描述您的问题.**
不好意思，刚接触没多久，我发现有时候虽然看到有新版本的releases，但从系统内使用/opt/setuptools/jmsctl.sh upgrade却提示当前版本是最新版本，譬如现在部署的是2.3.1，releases已经是2.3.2了，但依然提示“v2.3.1 已是最新版本”

请问这是什么情况呢？已经遇到过两次类似的情况了，上次过了两三天后又成功升级了，但这次好像有一个多星期了。

非常感谢！

**Comment by ibuler** [comment]
问题已确认，社区版的 docker 镜像没有 push 成功，以后会避免这个问题
