### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LUOZhen-huan** [jumpserver/jumpserver#4758]
**（不好意思，忘记打标题了）**

**JumpServer 版本(v1.5.9以下不再支持)**
v2.3.1

**浏览器版本**
Chrome 85.0.4183.121

**Bug 描述**
Web登录后，在无任何操作并超过“系统设置-安全设置-连接最大空闲时间”所设置的时间后，web端并未注销退出，是我设置不对还是理解有误？****

**Bug 重现步骤(有截图更好)**
1.  “系统设置-安全设置-连接最大空闲时间”中设置超时时间为30分钟
2. 用户登录web页面后停止一切操作，等待超过30分钟（发现问题时我已经一夜没有操作计算机）
3. 发现web登录依然有效，可以继续操作所有操作。

**Comment by wojiushixiaobai** [comment]
@LUOZhen-huan [参考此文档处理](https://docs.jumpserver.org/zh/master/admin-guide/env/)
```
SESSION_COOKIE_AGE: 86400     # session 有效期  默认界面用户不需要密码自动化登录时间
SESSION_EXPIRE_AT_BROWSER_CLOSE: FALSE  # 关闭浏览器失效登录的 session
```
