### ISSUE TITLE
[Bug] nginx代理之后无法ssh终端连接服务器，

### ISSUE THREAD

**Issue by silenceGuo** [jumpserver/jumpserver#4761]
**JumpServer 版本(v1.5.9以下不再支持)**
2.3.1 版本通过容器启动
部署命令
docker run --name jms_all -d \
  -p 80:80 -p 2222:2222 \
  -e SECRET_KEY=$SECRET_KEY \
  -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
  -v /opt/jumpserver/data:/opt/jumpserver/data \
  -v /opt/jumpserver/mysql:/var/lib/mysql \
  --privileged=true \
  jumpserver/jms_all:v2.3.1

**Bug 描述**
通过容器启动，直接访问ip+端口 可以实现访问 ssh终端，
![image](https://user-images.githubusercontent.com/28891624/95649228-10405a80-0b0f-11eb-9cef-a1acb8fdd8cf.png)

通过nginx代理，ssh终端，文件管理。mysql连接，都报错，但是windows 终端可以连接，已确认ssh 连接用户 密码正确，
同一台机器同时容器化部署了1.5.2版本，一样的 nginx代理配置文件，可以web终端连接ssh
Connection error
Connection closed

![image](https://user-images.githubusercontent.com/28891624/95649262-3ebe3580-0b0f-11eb-8b30-0d1b525ee2b9.png)

**Comment by wojiushixiaobai** [comment]
@silenceGuo [请参考此文档进行处理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/)
有问题请继续反馈。

**Comment by silenceGuo** [comment]
参考更新nginx配置解决问题，

upstream jumpserver-bak {
         #server 192.168.0.64:808 weight=1 max_fails=2 fail_timeout=2;      
         server 192.168.0.64:808;      
         #ip_hash;
}
server {
    listen 80;
    server_name jumpserver-bak.xx.com;
    #rewrite ^/(.*)$ https://$host/$1 permanent;
	return 301 https://$server_name$request_uri;
}
server {
        listen 443 ssl;
        server_name jumpserver-bak.xiaokangjun.com;
        ssl_certificate /etc/nginx/cert/xx.com.pem;
        ssl_certificate_key /etc/nginx/cert/xx.com.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
        ssl_prefer_server_ciphers on;
        client_max_body_size 100m;
        access_log  /data/log/nginx/jumpserver-bak.xx.com_access.log  main;
        error_page 502 /html/504.html;       
        location / {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 600;
            proxy_connect_timeout 600;
            proxy_send_timeout 600;
            proxy_pass http://jumpserver-bak;
        }
}
