### ISSUE TITLE
[Question] ssh命令行登录问题

### ISSUE THREAD

**Issue by icearios** [jumpserver/jumpserver#4775]
版本2.2.3
cmd用ssh命令登录jumpserver里的目标主机提示以下
No PTY requested.
![无标题](https://user-images.githubusercontent.com/71049984/95840702-10db2a00-0d77-11eb-9cf9-ec85e204e1ce.png)
官网文档是这样的
![无标题1](https://user-images.githubusercontent.com/71049984/95840971-66afd200-0d77-11eb-85d7-64609cf3717d.png)
请教下是什么问题？？

**Comment by LeeEirc** [comment]
ssh登陆方式连接 不支持执行命令，去掉后面的192.168.10.4试试 @icearios

**Comment by icearios** [comment]
> ssh登陆方式连接 不支持执行命令，去掉后面的192.168.10.4试试 @icearios

去掉后面的IP可以登录到选择列表里选择，再想问下有通过命令行登录到jumpserver前如命令行加上目标主机的IP，直接连进，而不用在选择列表里一层一层选择，快速连接目标主机这类或相似效果的方式吗？

**Comment by ibuler** [comment]
还不支持隧道模式，因为无法记录命令
