### ISSUE TITLE
[Bug] 登陆长时间Pending无法正常进入管理页

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#4776]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.3.1

**浏览器版本**
版本 84.0.4147.105（正式版本） （64 位）

**Bug 描述**
登陆页输入用户名、密码后点击登陆，页面长时Pending无法自动跳转到JS管理控制台。手动点击刷新按钮再次输入用户名密码点击登陆就可以正常登陆显示管理控制台。

**Bug 重现步骤(有截图更好)**
1.  地址栏输入JS服务器URL，打开JS登陆页
2. 输入用户名密码点击登陆（页面长时间Pending）
3. 刷新页面重新输入用户名密码可以正常跳转到管理控制台
4.退出再次登陆也可以正常
5.感觉每次打开浏览器首次登陆时就是出现此问题，和之前提到的Issues很像：“新用户重置密码点设置后无法正常返回登陆页V2.3.1 #4704”

**Comment by ibuler** [comment]
F12一下，提供更多 log 信息

**Comment by yearnxiao** [comment]
![jp1](https://user-images.githubusercontent.com/12027882/96061885-e5675500-0ec6-11eb-93a0-d7cff9b6abe0.png)
![11](https://user-images.githubusercontent.com/12027882/96062188-a8e82900-0ec7-11eb-913f-aee166ca1231.png)
图1是旧版，图2是新版本都经常遇到pending的问题，感觉后端某个接口会休眠必需请求激活一下才可以响应用户请求
