### ISSUE TITLE
资产页面，搜索时会显示多条相同的记录

### ISSUE THREAD

**Issue by leeloveying** [jumpserver/jumpserver#478]
使用的jumpserver-master分支
发现的问题：
    导入完成资产后，再次编辑选择机房等信息后保存，然后进行搜索时会显示多条相同的记录

**Comment by leeloveying** [comment]
问题定位：
找到导致此问题的原因了，搜索的时候按照组进行匹配了，当某一个主机存在于多个组内时，搜索后就会显示多条记录
建议：
当前面条件下拉框不选择时，搜索进行全字匹配（有多条则显示多条），选择条件下拉框后，再进行条件匹配

**Comment by ibuler** [comment]
0.3.3的小bug不再修复了，请测试新版本
