### ISSUE TITLE
[优化需求]更改asset.comment的字段限制 

### ISSUE THREAD

**Issue by faith2god** [jumpserver/jumpserver#4785]
优化需求
1.	Assets_asset表数据库comment是longtext类型，可容纳的字符很多，是否可以在model里放宽字段限制，方便用户使用？
2.	如果comment放宽限制，主机名和备注是否缩略显示，能否抛出设置，可以用户自定义
![assets_asset comment字段类型](https://user-images.githubusercontent.com/16483557/96210288-27b29400-0fa4-11eb-8622-7cb576ae510b.png)
![model中comment字段限制](https://user-images.githubusercontent.com/16483557/96210295-2a14ee00-0fa4-11eb-8aa8-ad9c0d7b6892.png)
![放宽comment字段显示后xshell终端显示](https://user-images.githubusercontent.com/16483557/96210299-2da87500-0fa4-11eb-8476-4f4cd2d2e8b8.png)

**Comment by faith2god** [comment]
![image](https://user-images.githubusercontent.com/16483557/96107737-56caf600-0f0f-11eb-98a2-3cb17c6e270b.png)
另外comment内容添加之后，主机列宽就特别小，这边能修改一下前端设置吗？或者抛出设置，用户可以自定义？

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/pull/4812

**Comment by faith2god** [comment]
好的，谢谢。
comment放宽限制后，主机名和备注有可能缩略显示。
这方面能否抛出设置，可以用户自定义？或者是主机名默认不折叠？
