### ISSUE TITLE
[Feature] jumpserver登录资产ssh超时时间中断

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4792]
**JumpServer 版本(v1.5.9以下不再支持)**
2.2.1

**浏览器版本**

**Bug 描述**
这是网络设备测试出现的，linux资产没测试过
jumpserver设置了ssh超时时间30分钟之后，资产ssh默认超时时间为10分钟，最终中断时间不是以jumpserver的超时时间为中断时间，无操作10分钟之后就断开连接了。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
ssh 超时中断是指的和 SSH Server 多长时间无法建立连接则放弃，默认是 30s,   ssh 空闲时间才是无操作时间
