### ISSUE TITLE
windows服务器的支持

### ISSUE THREAD

**Issue by fengjing1009** [jumpserver/jumpserver#4799]
1、添加资产后windows服务器连接状态显示未知
2、windows服务器的配置信息无法采集到

**Comment by wojiushixiaobai** [comment]
@fengjing1009 [参考此文档](https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_ssh/) 自行解决

**Comment by wojiushixiaobai** [comment]
[参考此文档处理下](https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_ssh/)
