### ISSUE TITLE
有计划 做成一个ansible ui 吗

### ISSUE THREAD

**Issue by vTNT** [jumpserver/jumpserver#48]

**Comment by ibuler** [comment]
目前还没计划，也还没一个好的思路

**Comment by vTNT** [comment]
确实我在github也没找到个 可以借鉴的

**Comment by someonebw** [comment]
供参考
https://github.com/alaxli/ansible_ui

**Comment by vTNT** [comment]
这个也可以参考这ui   功能其实差不多就是实现不一样 仅供参考 https://github.com/Hasal/dzhops

**Comment by vTNT** [comment]
这个也还可以 https://github.com/dogdep/dogpro

**Comment by jackiehope** [comment]
这些项目都不怎么维护了，如果你有这个水平或者想学习一下的话，可以使用一下，比较遗憾的是这些项目貌似都不提供restful的接口，所以和其他平台集成难度会高。我用觉得还可以2个https://github.com/ansible-semaphore/semaphore和https://github.com/rundeck/rundeck。
