### ISSUE TITLE
[Question] 批量导入资产授权表报错

### ISSUE THREAD

**Issue by zhangtianlin1** [jumpserver/jumpserver#4811]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/61460715/96366453-45d1ed00-117a-11eb-89d1-95c9ee1abd7d.png)
![image](https://user-images.githubusercontent.com/61460715/96366487-7ade3f80-117a-11eb-9b5e-cc4e6b38d330.png)

批量导入资产授权表报错，是我的操作哪里有问题吗？

**Comment by ibuler** [comment]
问题确实存在

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/pull/4826/files 等待发版
