### ISSUE TITLE
[Question]1.5.8 如何升级到最新版，无操作文档

### ISSUE THREAD

**Issue by anyouuu** [jumpserver/jumpserver#4813]
**请描述您的问题.**
如何升级到最新版，每次更新的时候都没有写升级方案。

**Comment by MinuxL** [comment]
> **请描述您的问题.**
> 如何升级到最新版，每次更新的时候都没有写升级方案。

看[官网-升级指导](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/1.5.0/)
我想能够处理了吧

**Comment by ibuler** [comment]
1.5 以后升级很简单的，看文档吧
