### ISSUE TITLE
[Bug] v2.4.0版本SSH终端资产显示不全

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#4821]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.0

**浏览器版本**
ssh连接，没有用浏览器

**Bug 描述**
通过ssh连接到jumpserver后，在v2.3.2版本的时候，输入p，可以看到我所有节点下的所有资产。但是我升级到v2.4.0版本后，输入p，只显示了我其中一个节点里面的资产，其他两个节点的资产都看不到，也无法直接搜索到，会提示“没有资产”。
但是，如果我先输入g，就能看到我的全部节点，然后通过g+节点ID，就可以成功的显示之前搜不到的资产，并能够成功连接。
浏览器的web终端是OK的，能看到全部资产。

**Bug 重现步骤(有截图更好)**
1.  输入p，可以看到只有少数的资产，并且无法搜索到其他资产
![微信截图_20201020093607](https://user-images.githubusercontent.com/22488813/96529425-b2063b00-12b7-11eb-93a8-36c756168190.png)

2. 输入g，可以看到全部节点，以及资产数量
![Snipaste_2020-10-20_09-31-24](https://user-images.githubusercontent.com/22488813/96529167-0826ae80-12b7-11eb-872a-bfd3324fdc75.png)

3. 输入g+节点ID，就可以看到第一步看不到的节点
![Snipaste_2020-10-20_09-32-33](https://user-images.githubusercontent.com/22488813/96529236-33110280-12b7-11eb-92a2-4903d6bff137.png)

4. 通过浏览器的web终端，可以看到所有节点
![Snipaste_2020-10-20_09-33-33](https://user-images.githubusercontent.com/22488813/96529284-55a31b80-12b7-11eb-8dcc-553aa22d4587.png)

**Comment by ibuler** [comment]
@jym503558564

**Comment by ibuler** [comment]
问题已确认，api 返回的是直接授权的资产，非全部资产，正在修复

**Comment by rty813** [comment]
ok 辛苦了

> 问题已确认，api 返回的是直接授权的资产，非全部资产，正在修复

**Comment by ibuler** [comment]
已修复，感谢反馈 https://github.com/jumpserver/jumpserver/releases/tag/v2.4.1

**Comment by rty813** [comment]
> 已修复，感谢反馈 https://github.com/jumpserver/jumpserver/releases/tag/v2.4.1

为什么我用jmsctl update显示已是最新版本呢？
![Screenshot_20201020-130218~2](https://user-images.githubusercontent.com/22488813/96542502-cad11980-12d4-11eb-9f8c-64c6ff988080.jpg)

**Comment by ibuler** [comment]
再试试

**Comment by rty813** [comment]
依然提示已是最新版本
![Uploading Snipaste_2020-10-20_14-06-28.png…]()

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by rty813** [comment]
现在可以了，谢谢
