### ISSUE TITLE
[Bug] 文件管理模块部分不可用

### ISSUE THREAD

**Issue by MinuxL** [jumpserver/jumpserver#4824]
**JumpServer 版本(v1.5.9以下不再支持)**
```text
Version v2.4.0 GPLv2
```

**浏览器版本**
```text
Mozilla Firefox 81.0.2
```

**Bug 描述**
```text
会话管理->文件管理(会话管理->web终端->导航栏：文件管理)
进入全局文件管理模块 部分网络直连设备使用正常 部分通过网域转接的无法访问到目标主机的“/tmp"目录
大概有如下请求，会比直连网络慢（卡一会然后返回）
https://domain.com/koko/elfinder/connector/_/?sid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&cmd=open&target=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxlZmF1bHQv5rex5Zyz5YWs5Y-4L-i_kOe7tOeuoeeQhi9MblNoZW56aGVuLVZMYxxxxxxxxxxx&reqid=1754410e43bb7

会话管理->web终端->具体资源选择文件管理不可用

我没办法收集更多信息 以前有版本会被我的广告屏蔽插件屏蔽文件管理功能 但这次广告屏蔽似乎不影响了
```

**Bug 重现步骤(有截图更好)**
```text
见描述
```

**Comment by MinuxL** [comment]
> **JumpServer 版本(v1.5.9以下不再支持)**
> 
> ```
> Version v2.4.0 GPLv2
> ```
> 
> **浏览器版本**
> 
> ```
> Mozilla Firefox 81.0.2
> ```
> 
> **Bug 描述**
> 
> ```
> 会话管理->文件管理(会话管理->web终端->导航栏：文件管理)
> 进入全局文件管理模块 部分网络直连设备使用正常 部分通过网域转接的无法访问到目标主机的“/tmp"目录
> 大概有如下请求，会比直连网络慢（卡一会然后返回）
> https://domain.com/koko/elfinder/connector/_/?sid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx&cmd=open&target=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxlZmF1bHQv5rex5Zyz5YWs5Y-4L-i_kOe7tOeuoeeQhi9MblNoZW56aGVuLVZMYxxxxxxxxxxx&reqid=1754410e43bb7
> 
> 会话管理->web终端->具体资源选择文件管理不可用
> 
> 我没办法收集更多信息 以前有版本会被我的广告屏蔽插件屏蔽文件管理功能 但这次广告屏蔽似乎不影响了
> ```
> 
> **Bug 重现步骤(有截图更好)**
> 
> ```
> 见描述
> ```

**补充说明**
```text
通过网域网关连接到的服务器正常 web终端ssh连接正常
```

**Comment by rty813** [comment]
我也是相同的问题

1. 通过scp可以正常访问文件
![Snipaste_2020-10-20_17-12-37](https://user-images.githubusercontent.com/22488813/96565845-77bc8e00-12f7-11eb-9513-b600755e1805.png)

2. 通过web终端->文件管理->连接，然后跳转到File Manager，可以正常访问文件
![Snipaste_2020-10-20_17-13-01](https://user-images.githubusercontent.com/22488813/96565966-9cb10100-12f7-11eb-8e7d-8a980eeec733.png)


3. 通过web终端->资产树->右击资产->文件管理，看不到文件
![Snipaste_2020-10-20_17-13-23](https://user-images.githubusercontent.com/22488813/96565930-91f66c00-12f7-11eb-8015-cff44fd152dc.png)


并且，我发现不是所有资产都有问题，只有部分资产是可以的。

**Comment by rty813** [comment]
v2.4.1版本没有出现这个问题，貌似已经修复了

**Comment by MinuxL** [comment]
> v2.4.1版本没有出现这个问题，貌似已经修复了

```text
版本：Version v2.4.1 GPLv2.

问题描述：
问题改善，在web终端点击具体资源，然后文件管理可用。相对于前面可用的资源在全局进入文件管理里没有修复（该资源web终端ssh连接正常），该资源是通关网域网关连接过去的。
```

**Comment by LeeEirc** [comment]
@MinuxL 有koko的报错日志吗，贴一下？

**Comment by MinuxL** [comment]
> @MinuxL 有koko的报错日志吗，贴一下？

```text
# 全局文件管理
2020-10-22 14:16:55 [ERRO] Get new SSH client err: dial tcp 192.168.0.60:22: i/o timeout
2020-10-22 14:16:55 [ERRO] Get Sftp Client err: dial tcp 192.168.0.60:22: i/o timeout
[GIN] 2020/10/22 - 14:16:55 | 200 | 15.087896607s |   123.231.123.231 | GET      "/koko/elfinder/connector/_/?sid=28b4707b-34b8-4f6a-852b-76e84dbab649&cmd=open&target=1191293448ef0849925aa3bb757d9359_L0RlZmF1bHQv5rex5Zyz5YWs5Y-4L-i_kOe7tOeuoeeQhi9MblNoZW56aGVuLVZMYzdULTAtNjA&reqid=1754ef3c5be56"

# web终端具体服务器进入文件管理
[GIN] 2020/10/22 - 14:17:31 | 200 |   27.243134ms |   123.231.123.231 | GET      "/koko/elfinder/sftp/c173eb0d-7564-44a1-a7ea-56279e64473f/"
[GIN] 2020/10/22 - 14:17:32 | 200 |  871.338124ms |  123.231.123.231 | GET      "/koko/elfinder/connector/c173eb0d-7564-44a1-a7ea-56279e64473f/?sid=0efeb739-c29c-43a4-8eb6-4a0397a98f31&cmd=open&target=&init=1&tree=1&_=1603347451496"

以上两段是操作同一台远程服务器
```

**Comment by LeeEirc** [comment]
感谢回复，找到原因了，API有变动，未能正确获取到网域的数据，目前应该仅对网域的资产有影响，稍后会修复这个问题

**Comment by MinuxL** [comment]
```text
从v2.4.1升级到v2.4.3 网域的文件管理可用了
```

**Comment by smallhorsegg** [comment]
v2.5.2有这个问题吗?   我在2.5.2中也遇到相同的问题

**Comment by MinuxL** [comment]
> v2.5.2有这个问题吗? 我在2.5.2中也遇到相同的问题

目前新版无发现问题 正常使用中
