### ISSUE TITLE
[Feature] 当授权很多台资产时 - 授权资产的IP段给用户

### ISSUE THREAD

**Issue by sosogh** [jumpserver/jumpserver#4828]
试用了下jumpserver，目前看，是先建立（导入）好资产，再把这些已经“录入”的资产授权给用户。
如果需要授权很多台，例如1万台资产给用户时候，那是需要提前建立（导入）好这1万台资产的信息？

是否考虑，增加一个选择：
1.  授权的时候，管理员定义资产的IP（段）而不是指定具体那台，例如192.168.10.0/24，10.0.0.0/8
2.  用户远程连接资产时候，可以自己输入目标资产的IP，jumpserver去判断该用户是否有目标资产的连接权限。

如果有这个选择，那么管理员在授权1万台资产给用户时候，只需定义好这些资产的IP段，这比“录入”1万台资产会容易。
并且，假设我的资产IP是在10.0.0.0/8范围内，以后新增服务器后，我也无需再针对新上的服务器进行授权了，我只需定义一条10.0.0.0/8就足够了。

谢谢！

**Comment by ibuler** [comment]
嗯，是需要考虑的功能，不过就是生成树的时候比较麻烦
