### ISSUE TITLE
[Feature] 类似SecureCRT的button bar功能

### ISSUE THREAD

**Issue by oldunclez** [jumpserver/jumpserver#4829]
SecureCRT有个button bar的功能，如下图，其本质就是：
把常用的命令，写到button里面，然后，点击button就可以快速地把命令输入到目标主机里执行。
是否考虑下这个功能？ 谢谢！

![image](https://user-images.githubusercontent.com/6986430/96550688-bea08880-12e3-11eb-8e54-d956df48e9b2.png)

![image](https://user-images.githubusercontent.com/6986430/96550954-28b92d80-12e4-11eb-850a-1c1546e9465d.png)

**Comment by ibuler** [comment]
期待 社区用户贡献
