### ISSUE TITLE
推送的理解问题

### ISSUE THREAD

**Issue by plutoid** [jumpserver/jumpserver#483]
hi,

````
推送系统用户

添加完系统用户，需要推送，推送操作是使用ansible，把添加的系统用户和系统用户管理的sudo，推送到资产上，具体体现是在资产上useradd该系统用户，设置它的key,然后设置它的sudo，为了让用户可以登录它
````

对于这点不明白的地方是 ansible 要登录资产上去 useradd 用户, 但前提是得有另一个账号登录后才能操作吧, 这另一个人账号是在哪里设置的呢?

regards, Howard

**Comment by ibuler** [comment]
admin user 管理用户

**Comment by plutoid** [comment]
谢谢, 看了这个,了解了为什么会莫名卡住了,  既然ansible 有 become_users 的 sudo 模块, 应该只要有 sudo权限的普通用户不需要再设成 NOPASSWD: ALL . 

如果后者做为管理用户就需要添加sudo权限又是NOPASSWD: ALL,

https://github.com/jumpserver/jumpserver/wiki/%E5%BA%94%E7%94%A8%E5%9B%BE%E8%A7%A3

**Comment by ibuler** [comment]
添加sudo密码，就需要管理用户中添加的内容更多
