### ISSUE TITLE
2.4版本jms启动提示找不到AES.MODE_GCM，哪个包不对？谢谢

### ISSUE THREAD

**Issue by cabbage18** [jumpserver/jumpserver#4830]
**请描述您的问题.**
  File "/opt/jumpserver/apps/common/fields/model.py", line 161, in get_prep_value
    return aes_crypto.encrypt(value)
  File "/opt/jumpserver/apps/common/utils/crypto.py", line 76, in encrypt
    cipher = AES.new(self.key, AES.MODE_GCM)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'

**Comment by ibuler** [comment]
看看依赖库的版本对不对

```
# pip freeze | grep -i 'crypto'
asn1crypto==0.24.0
cryptography==2.8
pycrypto==2.6.1
pycryptodome==3.9.7
pycryptodomex==3.9.7

```

**Comment by cabbage18** [comment]
@ibuler 感谢，是库的问题，pycrypto这个可以不要
pip uninstall crypto
pip uninstall pycryptodome
pip install pycryptodome

**Comment by xiao2016Online** [comment]
pycrypto==2.6.1
这个库应该去掉吧，不然还会报错
