### ISSUE TITLE
[Feature] web终端实现在配置多用户时手动选择登录用户

### ISSUE THREAD

**Issue by MinuxL** [jumpserver/jumpserver#4831]
**请描述您的需求或者改进建议.**
```text
鉴于目前基于优先级的策略 优先级第二跟后面的无差别 用户只能强迫使用优先级最高的系统账户进行登录
但系统用户分配上会给某个帐号分配处理特定的任务 ...
所以最理想的结果是: 能够实现让用户选择管理员给他分配好的账户进行系统登录为妙
(目前"系统用户"里建立用户有"手动登录"选项, 但不能记录密码)
```

**Comment by ibuler** [comment]
当时设置优先级的初衷就是避免用户再去选择登录，

如果说 两个系统用户一个高一个低，那么可以任务高级别的用户有低级别用户的所有权限。
如果不是如上，那么可以设置两个用户的优先级是一样的

**Comment by MinuxL** [comment]
> 当时设置优先级的初衷就是避免用户再去选择登录，
> 
> 如果说 两个系统用户一个高一个低，那么可以任务高级别的用户有低级别用户的所有权限。
> 如果不是如上，那么可以设置两个用户的优先级是一样的

```text
谢谢 能完美达到需要的效果
```
