### ISSUE TITLE
[Question] 关于系统用户无法推送到资产中

### ISSUE THREAD

**Issue by onlineyh** [jumpserver/jumpserver#4832]
您好 请问下  我是使用docker 部署 jumpserver ，不知道怎么回事 系统用户无法推送到资产中 主机 需要手动在主机中创建用户才能登陆?我在任务列表中查看推送任务不成功 显示

2020-10-21 11:48:43 任务开始: 推送系统用户到入资产: user03
PLAY [推送系统用户到入资产: user03] ******************************************************
TASK [Add user user03] *********************************************************
fatal: [testing]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "Group admin does not exist"}
2020-10-21 11:48:47 任务结束
.

.
Task ops.tasks.run_ansible_task[982e7e61-61a8-4cb1-aa9d-5b0eeca060ad] succeeded in 4.18514110147953s: ({'ok': {}, 'failed': {'testing': {...}}, 'unreachable': {}, 'skippe': {}}, {'contacted': {}, 'dark': {'testing': {...}}, 'success': False})

我不知道怎么回事？麻烦大牛 解答下疑惑？

**Comment by sxueck** [comment]
***请输入用户组，多个用户组使用逗号分隔（需填写已存在的用户组）***
你在添加系统用户的时候能看到这句话

**Comment by appop** [comment]
我没有用户组 不会自动创建么？

**Comment by jym503558564** [comment]
目前是，需要填写已存在的用户组，我们在页面上有很友好提示。
