### ISSUE TITLE
[新安装的jumpserver 无法使用WEB终端 本人新学小白 请问一下原因在哪 ] 

### ISSUE THREAD

**Issue by enoch6910** [jumpserver/jumpserver#4835]
**JumpServer 版本(2.4.0)** 操作系统CENTOS7 7.8 2003

**浏览器版本** Google Chrome 版本 85.0.4183.102（正式版本） （64 位）
 

**Bug 描述**
资产1：WIN7系统， RDP协议  用WEB终端联接无反应黑屏。
资产2：CENTOS7系统  SSH协议  用WEB终端提示502 Bad Gateway
nginx/1.18.0

**Bug 重现步骤(有截图更好)**
1.  
![Dingtalk_20201021144130](https://user-images.githubusercontent.com/73163298/96683110-49e55100-13ac-11eb-9bc2-fc96c9a8bde3.jpg)
![Dingtalk_20201021144216](https://user-images.githubusercontent.com/73163298/96683117-4baf1480-13ac-11eb-9038-da97e3500abd.jpg)

2.

**Comment by wojiushixiaobai** [comment]
执行下面的命令
```
cd /opt/setuptools
./jmsctl.sh reset koko
./jmsctl.sh reset guacamole
```
如果问题依旧
```
systemctl restart docker
docker restart jms_koko jms_guacamole
```
即可
