### ISSUE TITLE
[Bug] 多个RDP远程桌面，前面开启的自动关闭，显示“连接已关闭，请重新连接”

### ISSUE THREAD

**Issue by Fancy-Guo** [jumpserver/jumpserver#4836]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer2.4.0

**浏览器版本**
Firefox81.0.2 (64 位)

**Bug 描述**
[多个RDP远程桌面，前面开启的自动关闭，显示“连接已关闭，请重新连接”](url)

**Bug 重现步骤(有截图更好)**
1. ![图片](https://user-images.githubusercontent.com/45280948/96684578-608ca780-13ae-11eb-9f38-f5bf4c6859c5.png)
2. ![图片](https://user-images.githubusercontent.com/45280948/96684622-6edac380-13ae-11eb-8aab-e9316d5ebaf7.png)

**Comment by wojiushixiaobai** [comment]
无法复现

**Comment by ibuler** [comment]
windows rdp 如果没有 license，一个用户只能有一个连接，所以上一个被挤出来了
