### ISSUE TITLE
[Bug] 升级到2.4.1 设置主机名排序不起作用

### ISSUE THREAD

**Issue by lacatc** [jumpserver/jumpserver#4838]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.1

**浏览器版本**
chrome  86.0.4240.111

**Bug 描述**
使用docker 容器从v2.1.1 升级到v2.4.1 按主机名排序不起作用，在原v2.1.1时是没有这个问题的。
现在资产列表、web终端、ssh终端都没无法做到主机名排序。

**Bug 重现步骤(有截图更好)**
1.  docker v2.1.1 升级到 v2.4.1

![图片](https://user-images.githubusercontent.com/37959871/96691228-3b506700-13b7-11eb-8bf4-4807ed1c56c4.png)
![图片](https://user-images.githubusercontent.com/37959871/96691255-44413880-13b7-11eb-8b92-7cd3c0fd3604.png)

**Comment by lacatc** [comment]
我使用的是docker jms_all 的方式进行升级，在发生以上情况后，我又回溯以前的版本，发现这个问题在2.4.0就出现了，同时2.4.0也有一个问题，资产授权用节点方式授权没用，在2.4.1已经恢复正常。

资产排序在2.3.0、2.2.0都是正常的，2.4.0、2.4.1都是无法排序的情况。

2.1.1 是我原先使用的版本，我这边无法进行回溯回去，启动后docker无日志产生，但就是无法进行ssh 链接，web也无用。这边就简单测试一下，所有也没有升入查看日志。

**Comment by lycclsltt** [comment]
hostname-[01-04],  01 03显示在第一页， 02,04显示在第二页

**Comment by enthanlee** [comment]
升级2.4.x版本后遇见同样的问题。排序不生效，无论如何设置均是新建的资产排在最末。

**Comment by lukchiyung** [comment]
2.4.2 也是这个样子 资产无法按照主机名排序   这个问题也困扰着我  等待修复这个问题再升级

**Comment by lycclsltt** [comment]
改一下Koko这里，排序就正常了。但是官方没有确认，https://github.com/jumpserver/jumpserver/issues/4878

**Comment by ibuler** [comment]
已修复 v2.4.4
