### ISSUE TITLE
能否增加用户对资产添加备注的功能。。。  

### ISSUE THREAD

**Issue by sadbosan** [jumpserver/jumpserver#4839]
能否增加用户对资产添加备注的功能。。。  
资产量一大只看ip和主机名有点难以分辨了。。

**Comment by faith2god** [comment]
备注功能已有，检查下版本吧

**Comment by sadbosan** [comment]
我看最新版本也只是用户可以看到备注，并不能自己定义或修改备注

**Comment by faith2god** [comment]
用户可以自定义的。
两个方法，1是使用web端更新资源备注，2是使用api
