### ISSUE TITLE
[Bug] 远程应用授权 Server internal error

### ISSUE THREAD

**Issue by New-GitHub** [jumpserver/jumpserver#4841]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.1

**浏览器版本**
Google Chrome 已是最新版本
版本 86.0.4240.111（正式版本） （64 位）

**Bug 描述**
权限管理 -> 远程应用授权
创建或更新远程应用授权规则，只要用户选择组，远程应用系统用户选择（登陆模式为自动登陆、开启用户名与用户相同属性）点击提交后提示 Server internal error。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/27144127/96739663-9e132400-13f2-11eb-9ca6-56705f0a690c.png)
![image](https://user-images.githubusercontent.com/27144127/96739682-a23f4180-13f2-11eb-9089-014da0d9cc31.png)

**Comment by jym503558564** [comment]
@New-GitHub 新版本无该问题存在，请更新至最新版本进行测试。
