### ISSUE TITLE
[Bug] X-Pack 云管中心 同步实例管理用户设计不合理

### ISSUE THREAD

**Issue by New-GitHub** [jumpserver/jumpserver#4842]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.1

**浏览器版本**
Google Chrome 已是最新版本
版本 86.0.4240.111（正式版本） （64 位）

**Bug 描述**
X-Pack -> 云管中心 -> 同步实例任务列表 -> 创建或更新同步实例任务
同步设置 -> 管理用户只能定义一个（云环境同步资产操作系统会存在多种，管理用户也会根据操作系统类型定义多种。现在这个选项只能选一种管理用户，导致同步上来的资产管理用户均为一种类型，无法满足企业生产场景。）

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/27144127/96740866-d49d6e80-13f3-11eb-894b-9b164030960a.png)
![image](https://user-images.githubusercontent.com/27144127/96741060-03b3e000-13f4-11eb-9eb5-2c2df2302ab7.png)

**Comment by jym503558564** [comment]
https://github.com/jumpserver/jumpserver/issues/5843 重复问题
