### ISSUE TITLE
[Bug] 资产管理界面右上角导入导出图标反了

### ISSUE THREAD

**Issue by c12q** [jumpserver/jumpserver#4846]
**JumpServer 版本v2.4.1**

**浏览器版本**
谷歌浏览器最新版

**Bug 描述**
资产导出导入图标反了

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/57549979/96879315-7c777280-14ae-11eb-8bbd-12e38433866f.png)

2. 
![image](https://user-images.githubusercontent.com/57549979/96879339-81d4bd00-14ae-11eb-9a30-2134cb11d065.png)

3.

**Comment by wojiushixiaobai** [comment]
23333333333333....
我擦。。

**Comment by orangemio** [comment]
没反 第一个图标是`download` 第二个图标是 `upload`
