### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by touch888** [jumpserver/jumpserver#4848]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer 2.3.3 docker 版

**浏览器版本**

chrome 86.0.4240.75 (64位)
**Bug 描述**

修改服务器密码之后服务器的可连接性显示为红叉,但是可以登录服务器
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/20635217/96950902-f0049880-151d-11eb-883f-7a71cc68709f.png)

**Comment by wojiushixiaobai** [comment]
@touch888 登陆用的系统密码，这里测试用的管理里面。这两者不是一个账户

**Comment by touch888** [comment]
我设置没问题,就是修改过密码之后不能获取服务器硬件信息,但是可以登录,我自己生产环境用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wojiushixiaobai"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 上午9:11
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;; 
抄送: "风一样的男子"<535217631@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jumpserver/jumpserver] [Bug]  (#4848)





 
@touch888 登陆用的系统密码，这里测试用的管理里面。这两者不是一个账户
