### ISSUE TITLE
[Question] 网域网关功能遇到一个奇怪的问题

### ISSUE THREAD

**Issue by LeeXN** [jumpserver/jumpserver#4857]
**JumpServer 版本(v1.5.9以下不再支持)**
v1.5.5

**浏览器版本**
Chrome 86.0.4240.111

**Bug 描述**
由于业务问题，我们在其他云也有机器，所以要通过网关机器去跳转到其他机器
在配置完成之后，除了终端/web终端登录，其他地方都可以连上这台主机(比如使用作业中心-批量命令功能），怀疑是终端/web终端处并未使用网关连接

**Bug 重现步骤(有截图更好)**
1.  创建网域、网关（网关为公网ip）
2. 新建机器，选择该网关
3. 测试账号，发现已经通4
4.终端登录，失败
![ssh](https://user-images.githubusercontent.com/11554917/97144904-43861900-17a0-11eb-9a6e-349954d40c8e.png)
![微信图片_20201026152834](https://user-images.githubusercontent.com/11554917/97144911-45e87300-17a0-11eb-97e2-c5e5bb4fa3f6.png)
![image](https://user-images.githubusercontent.com/11554917/97145039-8516c400-17a0-11eb-9749-c163605bc159.png)

**Comment by LeeEirc** [comment]
@LeeXN 建议使用v2.x版本测一下，1.5.x版本已经不再维护。
