### ISSUE TITLE
使用docker-compose up启动报错

### ISSUE THREAD

**Issue by riwcwt** [jumpserver/jumpserver#486]
coco          | ERROR:root:Load access key failed
coco          | WARNING:root:Connect endpoint: http://jumpserver:8080 error
coco          | ERROR:root:Register terminal coco failed
coco          | Register terminal failed, may behave been exist, you should look forthe terminal access key, set in config, or put it in access key store
luna          | ERROR:root:Load access key failed
luna          | WARNING:root:Connect endpoint: http://jumpserver:8080/ error
luna          | ERROR:root:Register terminal luna failed
luna          | Register terminal failed, may be have been exist, you should look for the terminal access key, set in config, or put it in access key store

**Comment by riwcwt** [comment]
dev分支

**Comment by jiangchao2016** [comment]
i also have this error，how do you solve the problem

**Comment by riwcwt** [comment]
报错，但是程序能正常启动，但是使用不是很稳定！

**Comment by ibuler** [comment]
这是正常情况，去jumpserver后台，应用程序，接受一下coco 和 luna就行了

**Comment by jiangchao2016** [comment]
jmp 4.0 安装成功后，不要修改coco和luna的默认配置，可正常激活

**Comment by Password2008** [comment]
**(py3) [root@jms-v0_4 coco]# python run_server.py
ERROR:root:Load access key failed
WARNING:root:Connect endpoint: http://127.0.0.1:8080 error
ERROR:root:Register terminal coco failed
Register terminal failed, may behave been exist, you should look forthe terminal access key, set in config, or put it in access key store
(py3) [root@jms-v0_4 coco]# 
**

**Comment by Password2008** [comment]
我也是0.4. 启动不了coco
