### ISSUE TITLE
[Feature] 作业中心-任务列表批量操作

### ISSUE THREAD

**Issue by MinuxL** [jumpserver/jumpserver#4867]
**请描述您的需求或者改进建议.**
```text
作业中心 -> 任务列表 能够进行批量选择 但没有相应的操作 目前想清理下这些任务记录 一个个的点实在太多了
```

**Comment by MinuxL** [comment]
> **请描述您的需求或者改进建议.**
> 
> ```
> 作业中心 -> 任务列表 能够进行批量选择 但没有相应的操作 目前想清理下这些任务记录 一个个的点实在太多了
> ```

**版本**
` Version v2.4.1 GPLv2. `

**Comment by ibuler** [comment]
安排

**Comment by jym503558564** [comment]
@xuxinwen 需后端配合允许该api批量删除方法

**Comment by jym503558564** [comment]
https://github.com/jumpserver/lina/pull/468
