### ISSUE TITLE
[Bug] jms stop 无法关闭 beat 服务

### ISSUE THREAD

**Issue by hho2002** [jumpserver/jumpserver#4872]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.1

**浏览器版本**
chrome

**Bug 描述**
jms stop 无法关闭 beat 服务

**Bug 重现步骤(有截图更好)**
1.  ./jms start -d
2. ./jms stop
3. ps xf
4. /opt/py3/bin/python3.6 /opt/py3/bin/celery beat... 进程还在
5. jms stop_service:  建议用os.killpg替换os.kill
-        os.kill(pid, sig)
+        os.killpg(os.getpgid(pid), sig)

**Comment by ibuler** [comment]
收到
