### ISSUE TITLE
[Bug] koko代码里 authClient.SetHeader("X-JMS-ORG", "ROOT") 改为 authClient.SetHeader("X-JMS-ORG", "DEFAULT")，排序就正常了，问下改为DEFAULT有没有其他影响？

### ISSUE THREAD

**Issue by lycclsltt** [jumpserver/jumpserver#4878]
koko v 2.4

koko代码里 authClient.SetHeader("X-JMS-ORG", "ROOT") 改为 authClient.SetHeader("X-JMS-ORG", "DEFAULT")，排序就正常了，问下改为DEFAULT有没有其他影响？

**Comment by LeeEirc** [comment]
没有影响，但不应该影响排序。请使用v2.7.0 测试下。

**Comment by LeeEirc** [comment]
有问题再开
