### ISSUE TITLE
[Bug] ldap导入用户分大小写

### ISSUE THREAD

**Issue by fit2cloud-wangye** [jumpserver/jumpserver#4881]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.0

**浏览器版本**
chrome

**Bug 描述**
系统设置 —— LDAP设置 —— 一键导入 —— LDAP用户列表 "搜索框" 搜索用户不支持大写搜索,例如：输入：XUE，无法搜索出来用户。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
用户名是小写的，想用大写也能搜到是吧，也就是忽略大小写搜索

**Comment by xyziven** [comment]
是的，要忽略大小写，LDAP本身也是不区分大小写的。

**Comment by jym503558564** [comment]
@xyziven 已支持忽略大小写搜索，请更新至新版本进行测试。
