### ISSUE TITLE
[Bug] 创建本地用户能选ldap

### ISSUE THREAD

**Issue by fit2cloud-wangye** [jumpserver/jumpserver#4882]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer2.4.0

**浏览器版本**
Chrome

**Bug 描述**
创建本地用户能选ldap，能创建成功，实际是保存在本地数据库中的，然后页面仍然显示为ldap用户。

**Bug 重现步骤(有截图更好)**
1.用户列表 —— 创建新用户 —— 选择用户来源 —— ldap ，但是这个用户保存在JumpServer后台数据库中，然后用户列表页面仍然显示为ldap用户。
![image](https://user-images.githubusercontent.com/73286167/97534172-804a4e00-19f4-11eb-8ad7-79dfe3177dbe.png)

**Comment by ibuler** [comment]
创建用户只会创建到数据库中，不会再 AD 或其它系统上创建，这个只是标记来源而已
