### ISSUE TITLE
[功能增强] 创建新用户在设置密码时增加确认密码功能

### ISSUE THREAD

**Issue by fit2cloud-wangye** [jumpserver/jumpserver#4883]
**请描述您的需求或者改进建议.**
用户列表 —— 创建新用户 —— 设置密码位置增加一个确认密码输入框（功能:二次确认密码的功能）

**Comment by jym503558564** [comment]
@fit2cloud-wangye 创建用户时，目前只支持打开密码框的小眼睛，可查看您当前的密码。
![image](https://user-images.githubusercontent.com/40739051/111931856-20fdef00-8af7-11eb-82de-89de2e5b4a6f.png)
