### ISSUE TITLE
[Feature] 启用CAS认证后增加用户登录认证方式的日志记录

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#4884]
**请描述您的需求或者改进建议.**
当启用CAS登录认证后，公司内部员工使用CAS认证，外部厂商使用本地数据库认证，这样存在本地数据库和CAS混合登录的情况，现在默认要求内部员工全部使用CAS认证，现在的“日志审计”-“登录日志”里支持无法查看账户是通过CAS认证还是本地数据库认证登录，日志审计无法查看对应的登录方式，能否在日志审计”-“登录日志”增加一列来记录用户是通过哪种方式登录系统的，谢谢！

**Comment by jym503558564** [comment]
@aiaiduo 新版本已增加登录的认证方式，请更新至最新版本进行测试。
![image](https://user-images.githubusercontent.com/40739051/109289077-a2e45a80-7860-11eb-9220-5520cda32db3.png)
