### ISSUE TITLE
[Bug] docker-compose 部署jumpserver  jms_core一直重启

### ISSUE THREAD

**Issue by superkit01** [jumpserver/jumpserver#4889]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.2.0  v 2.3.0  v2.4.0 均发现此问题
**浏览器版本**

**Bug 描述**
jumpserver启动之后初始化完成大概过个一分钟左右，jms_core就开始一直重启，报错请看下面附件
相关的之前issue看了，我这边都不是这个情况 :
https://github.com/jumpserver/jumpserver/issues/3837
https://github.com/jumpserver/jumpserver/issues/3838
**Bug 重现步骤(有截图更好)**
1.  本地安装docker-compose  版本为1.24.0
2. git  clone  https://github.com/jumpserver/Dockerfile.git
3. 进入目录。重命名配置文件为.env   然后docker-compose up -d 
4. jms_core的报错
![微信截图_20201030105000](https://user-images.githubusercontent.com/22300000/97654362-b1328d80-1a9d-11eb-965f-8489358118fe.png)
容器内部的报错beat.log
![微信截图_20201030105136](https://user-images.githubusercontent.com/22300000/97654472-eb9c2a80-1a9d-11eb-92ab-44c47e920f2f.png)

**Comment by wojiushixiaobai** [comment]
@superkit01 无法复现，检查下是不是环境有问题

**Comment by superkit01** [comment]
因为所有组件都是容器化运行的。。跟本地环境应该没有关系吧。。
你那边docker的版本已经docker-compose的版本是多少？
还有镜像仓库你那边是用的阿里云的镜像加速的么？
最近一段时间群里有不少人反馈相似的情况。。

**Comment by wojiushixiaobai** [comment]
@superkit01 我测试了 阿里云 腾讯云 华为云 的云服务器和自己本地的虚拟机
暂时没有复现此问题，安装 docker 的命令如下
```
curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
sed -i -e '/mirrors.cloud.aliyuncs.com/d' -e '/mirrors.aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo
yum install -y wget epel-release git
curl -o /etc/yum.repos.d/epel.repo https://mirrors.aliyun.com/repo/epel-7.repo
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
yum install -y docker-ce
yum install -y docker-compose
mkdir /etc/docker
wget -O /etc/docker/daemon.json https://demo.jumpserver.org/download/docker/daemon.json
systemctl enable docker
systemctl start docker
```

**Comment by HKChen** [comment]
使用非 docker 或 docker 安裝 jumpserver v2.4.2 版本也遇到相同問題，執行 ./jms start 後大概幾分鐘內就會有 Logging Error 服務就直接停止的問題。

**Comment by xuxiaoyuspallow** [comment]
https://docs.jumpserver.org/zh/master/install/prod/distributed_05/   按照这个教程装的，也出现了这个问题， 版本是v2.4.3

**Comment by xuxiaoyuspallow** [comment]
可能是这个原因.  https://github.com/jumpserver/jumpserver/issues/4872

**Comment by lyitt1987** [comment]
我也遇到这种问题，我的解决方法是

**Comment by lyitt1987** [comment]
我的解决方法是

**Comment by superkit01** [comment]
我试了几台服务器发现同样的一份docker-compose.yml和.env文件，有的是可以成功。。。
我想了一些可能。。因为以容器方式启动，理论上来说跟本地环境应该没有关系才对。。
然后我就发现下面这个情况：
![image](https://user-images.githubusercontent.com/22300000/99204378-6a100080-27f0-11eb-9c4e-25601461cff5.png)
![image](https://user-images.githubusercontent.com/22300000/99204584-18b44100-27f1-11eb-87ea-0fbad5601622.png)

**Comment by CJFJack** [comment]
我也遇到这个问题，发现是beat起了多个进程，全部kill掉再重启jms就解决了

**Comment by superkit01** [comment]
> 我也遇到这个问题，发现是beat起了多个进程，全部kill掉再重启jms就解决了

你也是容器部署的么。。我应该不一样。。容器停止了里面的进程应该都停止了。。不应该出现多个进程挂起的情况
