### ISSUE TITLE
centos客户端问题Connecting...Connection Reset By Peer

### ISSUE THREAD

**Issue by onlyoneday** [jumpserver/jumpserver#489]

**Comment by xm-y** [comment]
我也是

**Comment by ooppwwqq0** [comment]
### 总结一下关于Connection Reset By Peer的问题出现原因以及解决办法

### 出现报错会有两种情况

* Connection Reset By Peer
* Connecting...Connection Reset By Peer

### Connection Reset By Peer 出现原因及解决办法

* 使用的是0.3.2版本的代码（本身代码有bug）；
* 并且直接访问的jumpserver端口，没有nginx代理；
* 解决办法-->将代码升级到master分支即可。

### Connecting...Connection Reset By Peer 出现原因及解决办法

* 使用nginx代理了jumpserver并且使用的是http代理；
* 代码版本无论是0.3.2还是master都会出现此问题；
* 解决办法-->http代理修改成tcp代理；
* nginx 1.9.x版本以上，编译时使用--with-stream参数可以支持tcp代理；
* 缺点是使用tcp代理之后无法配置server_name；
* 以下内容加到http{}外。

``` bash
stream {
    upstream backend{
        hash $remote_addr consistent;
        server 127.0.0.1:8000 weight=10;
    }

    server{
        listen 80;
        proxy_connect_timeout 20s;
        proxy_timeout 5m;
        proxy_pass backend;
    }
}
```

### 是否有其他情况造成此类问题没有测试过
