### ISSUE TITLE
[Feature] Linux动态用户在推送时增加name(Display Name)信息

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#4893]
**请描述您的需求或者改进建议.**
场景描述：目前jumpserver配置了ldap登录，username是员工号或者uid的缩写，推送到目标机器后，不能看出用户的所有者。
建议在推送动态用户的时候，同时将name（display name）也推送（假如存在name/display name），效果类似useradd -c "display name" username。/etc/passwd类似以下效果：
zhangsan:x:1001:1001:Zhang,San:/home/zhangsan:/bin/bash

补充：目前动态用户推送显示的是“动态用户名”，看不出来真实用户，尤其是当username是ldap中的员工id时：
E3GSH2G:x:1002:1003:**Linux-Dynamic-user**:/home/E3GSH2G:/bin/bash
TGAKA3Q:x:1003:1004:**Linux-Dynamic-user**:/home/TGAKA3Q::/bin/bash

**Comment by ibuler** [comment]
我记得上个版本做了这个功能了

**Comment by jym503558564** [comment]
@xyziven 已优化，新版本将发布。请持续关注我们后续版本发布。
