### ISSUE TITLE
[Question] v2.4.3-jmsn内存占用过高

### ISSUE THREAD

**Issue by MinuxL** [jumpserver/jumpserver#4905]
**请描述您的问题.**
```text
使用上看v2.4.3比v2.4.1占用内存高了
```
---

![图片](https://user-images.githubusercontent.com/29914264/97771046-1fe21a80-1b74-11eb-9266-aa0e8c04ee63.png)

---

![图片](https://user-images.githubusercontent.com/29914264/97771063-4acc6e80-1b74-11eb-9cb7-a59fd6ffe67c.png)

```text
这方面有没有优化的方案，或者建议啥的。单一个jms跑2G, 我感觉是高了。
```

**Comment by wojiushixiaobai** [comment]
@MinuxL 修改 jms 启动脚本，把相关的应用进程给下调即可
修改后一些任务的执行可能需要更新的时间
