### ISSUE TITLE
登录资产后发现是黑屏状态，请问是什么情况？

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#4908]
**请描述您的问题.**
发现所有的资产登录后都是黑屏状态，不同的是，Windows资产是全黑，Linux资产黑色背景有“502 Bad Gateway - nginx/1.18.0”的字样，请问这是什么情况？

目前版本是2.4.3

浏览器是chrome86和firefox78

谢谢

**Comment by wojiushixiaobai** [comment]
@Gianthard-XYZ 后端的组件没有注册成功，请到 会话管理 - 终端管理 检查组件状态
请根据 FAQ 文档重置 KoKo 组件和 Guacamole 组件

通过脚本安装的可以使用下面命令重置
```
cd /opt/setuptools
git pull
./jmsctl.sh reset koko
./jmsctl.sh reset guacamole
```
如果现象依旧
```
systemctl restart docker
docker restart jms_koko jms_guacamole
```
即可
