### ISSUE TITLE
jmp 4.0，创建用户没有发送email

### ISSUE THREAD

**Issue by jiangchao2016** [jumpserver/jumpserver#491]
docker-compose.yml里配置了自己的163  mail，不能使用

jumpserver    | [2017-06-08 17:14:09,670: DEBUG/MainProcess] Task accepted: common.tasks.send_mail_async[077a5619-17ab-48de-abe7-1e47c2072c26] pid:45
jumpserver    | 2017-06-08 17:14:09 [basehttp INFO] "POST /users/user/create HTTP/1.1" 302 0
jumpserver    | 2017-06-08 17:14:09 [basehttp INFO] "GET /users/user HTTP/1.1" 200 21379
jumpserver    | 2017-06-08 17:14:09 [basehttp WARNING] "GET /static/js/plugins/dataTables/dataTables.min.js HTTP/1.1" 404 1732
jumpserver    | 2017-06-08 17:14:10 [basehttp WARNING] "GET /static/js/plugins/dataTables/dataTables.min.js HTTP/1.1" 404 1732
jumpserver    | [2017-06-08 17:14:10,430: ERROR/PoolWorker-2] Task common.tasks.send_mail_async[077a5619-17ab-48de-abe7-1e47c2072c26] raised unexpected: SMTPAuthenticationError(535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
jumpserver    | Traceback (most recent call last):
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 367, in trace_task
jumpserver    |     R = retval = fun(*args, **kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 622, in __protected_call__
jumpserver    |     return self.run(*args, **kwargs)
jumpserver    |   File "/opt/jumpserver/apps/common/tasks.py", line 29, in send_mail_async
jumpserver    |     send_mail(*args, **kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/__init__.py", line 62, in send_mail
jumpserver    |     return mail.send()
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
jumpserver    |     return self.get_connection(fail_silently).send_messages([self])
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
jumpserver    |     new_conn_created = self.open()
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 71, in open
jumpserver    |     self.connection.login(force_str(self.username), force_str(self.password))
jumpserver    |   File "/usr/local/lib/python3.6/smtplib.py", line 729, in login
jumpserver    |     raise last_exception
jumpserver    |   File "/usr/local/lib/python3.6/smtplib.py", line 720, in login
jumpserver    |     initial_response_ok=initial_response_ok)
jumpserver    |   File "/usr/local/lib/python3.6/smtplib.py", line 641, in auth
jumpserver    |     raise SMTPAuthenticationError(code, resp)
jumpserver    | smtplib.SMTPAuthenticationError: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
jumpserver    | 2017-06-08 17:14:10 [basehttp INFO] "GET /api/users/v1/users/?_=1496913249816 HTTP/1.1" 200 1887
jumpserver    | 2017-06-08 17:14:12 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
jumpserver    | 2017-06-08 17:14:13 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
coco          | DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): jumpserver
coco          | 2017-06-08 09:14:14 [connectionpool DEBUG] Starting new HTTP connection (1): jumpserver
jumpserver    | 2017-06-08 17:14:14 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28

**Comment by jiaxiangkong** [comment]
python 要用 v3.6.x

**Comment by vki** [comment]
贴上配置文件看看

**Comment by lanbing222** [comment]
同问，我也遇到了

**Comment by hellorocky** [comment]
@lanbing222  邮箱认证问题, 去掉邮箱的二次认证, 或者换一个不用二次验证的邮箱

**Comment by lanbing222** [comment]
@hellorocky 测试，去掉也不行

**Comment by hellorocky** [comment]
我用python写了一个简单的发邮件的脚本, 你把相应的地址修改成你自己的, 试试, 看看行不行, 这个脚本如果可以发邮件的话, jumpserver肯定可以发, 这个脚本都不能发, 那肯定不行

**Comment by hellorocky** [comment]
https://raw.githubusercontent.com/hellorocky/LearnByCoding/master/python/mail/send_mail.py

**Comment by lanbing222** [comment]
多谢多谢，现在可以了 @hellorocky

**Comment by hellorocky** [comment]
怎么解决的,写出来呗, 以后有人遇到类似问题也可以参考

**Comment by lanbing222** [comment]
应该是项目的setting读取config.py配置文件有问题，我把邮箱配置直接配置到setting文件，问题得到解决

**Comment by lanbing222** [comment]
@hellorocky

**Comment by wocswang** [comment]
@lanbing222 把邮箱配置写到setting中那config中的就屏蔽掉是吧

**Comment by lanbing222** [comment]
是的
