### ISSUE TITLE
Web终端登录用户为jumpserver用户导致无法登录

### ISSUE THREAD

**Issue by master336** [jumpserver/jumpserver#4910]
[版本：] Docker jumpserver/jms_all:v2.4.0
问题描述：
 为资源配置用户及权限后，打开web终端，Linux平台显示登录的用户名为jumpserver当前登录用户名，而非配置的用户名，且修改jumpserver用户名后重新登录打开web终端，Linux平台显示登录的用户名也更换为更新后的jumpserver用户名；

**Comment by wojiushixiaobai** [comment]
@master336 系统用户取消 用户名与用户相同

**Comment by master336** [comment]
疑似缓存问题，选择“用户名与用户相同”后取消，保存后回显选中，但最新版本已无此问题
