### ISSUE TITLE
推送用户的问题

### ISSUE THREAD

**Issue by xutao3653** [jumpserver/jumpserver#492]
如题，比如我建一个ops用户，sudo 给的是ALL，然后推送到资产上。会在/etc/sudoers中生成这样一条记录：ops ALL = (root) NOPASSWD: ALL
想问下，为什么不是 ALL = (ALL) ，而是root呢？这个可以在哪里修改

**Comment by qils** [comment]
![source](https://user-images.githubusercontent.com/13659718/27428900-01887158-5776-11e7-972c-a79eba8891c8.png)

在Jumpserver 模板文件中有一个role_sudo.j2文件，是一个shell文件， 在推送sudo时， 要调用这个文件渲染, 在红圈里面写的是root
