### ISSUE TITLE
Jumpserver网域配置

### ISSUE THREAD

**Issue by Alary** [jumpserver/jumpserver#4923]
有台A服务器，通过Jumpserver可访问A服务器，A服务器通过SSH 访问B服务器，Jumpserver无法直接访问B服务器。
麻烦问下，jumpserver的网域配置，我配置的A服务器作为网关，在新建资产中，创建B资产服务器，网域选择的是A，一直连接不上，是哪里有问题吗？

**Comment by wojiushixiaobai** [comment]
确定网关可正常连接，点击网关测试。
然后在资产点击测试连接看提示

**Comment by Alary** [comment]
> 确定网关可正常连接，点击网关测试。
> 然后在资产点击测试连接看提示

1：网关测试了，点击网关测试，显示连接成功。
2：资产测试，点击测试连接，连不上。fatal: [master-大数据]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange", "unreachable": true}

**Comment by airgull** [comment]
@Alary 我也遇到了同样的问题
