### ISSUE TITLE
[Bug] JumpServer 连接 腾讯云 Kubernetes 报错

### ISSUE THREAD

**Issue by Degeneratefala** [jumpserver/jumpserver#4927]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.1

**浏览器版本**
Chrome 86.0.4240.111

**Bug 描述**
JumpServer连接腾讯云Kubernetes后没有返回
查看koko后端日志显示2020-11-03 17:43:08 [ERRO] K8sCon command exit err: exit status 1

直接访问Kubernetes地址 返回结果
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

另:文档对于Kubernetes的管理已经操作描述过少

**Comment by ibuler** [comment]
怎么部署的？docker 吗？

**Comment by Degeneratefala** [comment]
> 怎么部署的？docker 吗？

JumpServer 组件使用物理机 koko使用docker部署的
