### ISSUE TITLE
[Question] 通过api调用时nginx日志报错connect() failed (111: Connection refused)

### ISSUE THREAD

**Issue by Gerogeqd** [jumpserver/jumpserver#4929]
python代码片断：
for i in assets_dict:
    if i['ip'] == ipaddr:
        print('系统中已存在相同IP主机，主机名为： %s，正在进行自动清除', i['hostname'])
        tmp_data = {
            'ip': i['ip'],
            'hostname': i['hostname']
        }
        headers.update(tmp_data)
        ip_cls = requests.delete(base_url+'assets/assets/', auth=auth, headers=headers， data=tmp_data)
===================
代码执行时报错 400 bad request
Nginx日志报错如下：
2020/11/04 09:43:59 [error] 11474#0: *213 connect() failed (111: Connection refused) while connecting to upstream, client: 144.0.51.197, server: , request: "GET /api/v1/assets/assets/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/assets/assets/", host: "****.**ying.net.cn"
2020/11/04 09:43:59 [error] 11473#0: *216 connect() failed (111: Connection refused) while connecting to upstream, client: 144.0.51.197, server: , request: "DELETE /api/v1/assets/assets/?ip=192.168.6.66 HTTP/1.1", upstream: "http://[::1]:8080/api/v1/assets/assets/?ip=192.168.6.66", host: "****.**ying.net.cn"
2020/11/04 09:44:18 [error] 11473#0: *225 connect() failed (111: Connection refused) while connecting to upstream, client: 144.0.51.197, server: , request: "POST /api/v1/assets/assets/ HTTP/1.1", upstream: "http://[::1]:8080/api/v1/assets/assets/", host: "****.**ying.net.cn"
----------
Jumpserver日志：

127.0.0.1 [04/Nov/2020:09:44:18 +0800] "GET /api/v1/assets/assets/ HTTP/1.0" 200 1337
2020-11-04 09:44:18 [log WARNING] Bad Request: /api/v1/assets/assets/
127.0.0.1 [04/Nov/2020:09:44:18 +0800] "DELETE /api/v1/assets/assets/ HTTP/1.0" 400 0
2020-11-04 09:44:18 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.7/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/opt/py3/lib/python3.7/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/py3/lib/python3.7/site-packages/rest_framework/serializers.py", line 244, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'hostname': [ErrorDetail(string='字段必须唯一', code='invalid')]}
2020-11-04 09:44:18 [log WARNING] Bad Request: /api/v1/assets/assets/
127.0.0.1 [04/Nov/2020:09:44:18 +0800] "POST /api/v1/assets/assets/ HTTP/1.0" 400 35
127.0.0.1 [04/Nov/2020:09:44:20 +0800] "POST /api/v1/terminal/terminals/status/?from_guacamole=1 HTTP/1.1" 201 2
127.0.0.1 [04/Nov/2020:09:44:20 +0800] "GET /api/v1/assets/assets/ HTTP/1.0" 200 1337
2020-11-04 09:44:20 [log WARNING] Bad Request: /api/v1/assets/assets/

---------------------------
Nginx配置如下：
server {
    listen 80;

    client_max_body_size 100m;  # 录像及文件上传大小限制

    location /ui/ {
        try_files $uri / /index.html;
        alias /opt/lina/;
    }

    location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;  # luna 路径, 如果修改安装目录, 此处需要修改
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;  # 录像位置, 如果修改安装目录, 此处需要修改
    }

    location /static/ {
        root /opt/jumpserver/data/;  # 静态资源, 如果修改安装目录, 此处需要修改
    }

    location /koko/ {
        proxy_pass       http://localhost:5000;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /guacamole/ {
        proxy_pass       http://localhost:8081/;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
    }

    location /ws/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8070;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/ {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /core/ {
        proxy_pass http://localhost:8080;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }
}
------------------------
各位大神帮看看什么问题，谢谢

**Comment by jym503558564** [comment]
安装请参照文档 https://docs.jumpserver.org/zh/master/install/setup_by_fast/
