### ISSUE TITLE
用户推送卡死是为什么？

### ISSUE THREAD

**Issue by rainmor** [jumpserver/jumpserver#493]
- jumpserver版本是0.3版本  分支 master
- 使用非root用户推送系统用户的时候，直接卡死了

- 主机端：
![image](https://user-images.githubusercontent.com/5445791/27029693-05ef6760-4f9c-11e7-9bbe-54d4a1872956.png)
- jumpserver
![image](https://user-images.githubusercontent.com/5445791/27029739-2b06c0de-4f9c-11e7-83cb-619d5f8f92fe.png)

**Comment by rainmor** [comment]
@ibuler @liuzheng712

**Comment by rainmor** [comment]
![image](https://user-images.githubusercontent.com/5445791/27114237-bf34aace-50f4-11e7-885f-bc8522224092.png)
- 问题已经解决，导致卡死的原因是因为我的管理用户只能输入密码才能登陆。。。

**Comment by ibuler** [comment]
sudo需要交互式，所以卡死
