### ISSUE TITLE
[Feature] 历史会话里的录像能不能设置备注

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4930]
**请描述您的需求或者改进建议.**
历史会话里的录像能不能设置备注，时间长了根据操作记录命令找到当时做了什么操作，删除了什么，测试了什么会比较麻烦

**Comment by wojiushixiaobai** [comment]
添加审计备注，如：
审计人：张三
审计状态：完成

需要移交审计等等。审计完成后方便清理

**Comment by ibuler** [comment]
用户连接的时候填写？

**Comment by ryswork1993** [comment]
比如今天有因为割接操作，操作完成后可以在历史会话录像里写入备注，做了什么操作，

**Comment by ibuler** [comment]
要写也是在连接的时候填写

**Comment by jym503558564** [comment]
目前未支持，请持续关注我们版本发布。
