### ISSUE TITLE
[Bug] v2.4.3 koko ssh 协议列不出资产

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#4933]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.3

**Bug 描述**
koko ssh 协议列不出资产，如图所示。但 luna 是列出来的。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/3265516/98089775-d10aec80-1eb5-11eb-978c-4cd671ae77a0.png)

![image](https://user-images.githubusercontent.com/3265516/98089988-10d1d400-1eb6-11eb-9738-0cf9b875e73e.png)

**Comment by LeeEirc** [comment]
@huangzx jumpserver各版本都升级到最新的了吗？如何授权的资产？

**Comment by huangzx** [comment]
找到原因了。
core 我用了 master 的代码，其他组件是 v2.4.3，core 换回 v2.4.3 就好了。
