### ISSUE TITLE
[Feature] 资产列表里的节点能按照自己的喜好放置位置吗

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#4935]
**请描述您的需求或者改进建议.**
环境：2.3.0
![image](https://user-images.githubusercontent.com/44529247/98188292-bab06f80-1f4d-11eb-927a-907843e5407a.png)
现在客户测试机我想放到所有节点的最下面，当前好像实现不了或者最新版本已经实现了吗。

**Comment by orangemio** [comment]
暂时没有 顺序是后端生成的

**Comment by jym503558564** [comment]
暂时没有，请继续关注我们更新版本。
