### ISSUE TITLE
[Bug] v2.4.3 file管理中搜索无返回值

### ISSUE THREAD

**Issue by LeiyuanBlog** [jumpserver/jumpserver#4938]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.3

**浏览器版本**
chrome 86.0.4240.111（正式版本） (x86_64)

**Bug 描述**
file管理中搜索无返回值

**Bug 重现步骤(有截图更好)**
1.  登录jumpserver
2. 打开文件管理或者进入web终端后打开文件管理
3. 右上角搜索ip或名称均无返回值

**Comment by ibuler** [comment]
已处理  v2.4.4
