### ISSUE TITLE
[Feature] Web终端中的排序和SSH客户端中的不一样

### ISSUE THREAD

**Issue by clannon** [jumpserver/jumpserver#4940]
一、2.4.3，SSH客户端中排序正常，但Web终端里的不正常，终端设置那里用的默认主机名排序

![微信截图_20201105113452](https://user-images.githubusercontent.com/34529891/98200487-b0e83580-1f68-11eb-973b-441056d334e5.png)

二、“我的应用”在没有应用或者没有授权的情况下能否隐藏，或手动设置不显示

三、一开始以为“数据库应用”那里是类似Navicat、HeidiSQL之类的可视化客户端，但仍然是命令行，希望能有这样的UI

**Comment by ibuler** [comment]
1. 问题已收到

2. 问题已处理

3. 问题新版本在企业版中以增加 web版的 navicat
