### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lp2021** [jumpserver/jumpserver#4947]
**JumpServer 版本(v1.5.9以下不再支持)**
1.5.7升级到2.4.3之后

**浏览器版本**
谷歌版本 86.0.4240.183（正式版本） （64 位）

**Bug 描述**
资产列表点击主机名下对应的名称，会出现
资产: undefined(undefined)
无法显示资产信息
刷新浏览器，才可以正常展示。
可复现。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/55136840/98353335-24b63b00-205a-11eb-94d4-ef1bfaa134c2.png)

**Comment by ibuler** [comment]
没有获取到资产信息，刷新页面试试

**Comment by lp2021** [comment]
是的，刷新浏览器页面是可以加载出现的，但是升级之后经常会遇到这种 首次 点击进入用户信息或者是资产信息，跳转进入详细信息界面的时候加载不出来任何信息的现象，必须每次都再刷新下浏览器

**Comment by Anorpi** [comment]
这个问题能不能解决下 2022年11月1日了  最新版本的 这个问题还在

**Comment by wojiushixiaobai** [comment]
检查下你的 waf，应该是被拦截或者过滤掉了

**Comment by ibuler** [comment]
浏览器 URL 粘贴一下

**Comment by Anorpi** [comment]
同样的问题见：
https://github.com/jumpserver/jumpserver/issues/7135

URL:  http://x.x.x.62/ui/#/console/assets/assets/62aa85b1-f410-4f69-b62b-e388824a16c6
部署方式为：离线部署
版本为：v2.27.0 （最新版本）
阿里云主机IP直接访问，前面没有SLB 没有WAF
浏览器使用chrome 和 Opera 都试过了  一样有问题。


![Snipaste_2022-11-02_14-24-28](https://user-images.githubusercontent.com/7035867/199413979-0240feaf-7c44-47c4-9e43-47b3a2862d86.jpg)

**Comment by wojiushixiaobai** [comment]
无法复现，请检测下是否网络问题导致。

**Comment by Anorpi** [comment]
> 无法复现，请检测下是否网络问题导致。
我本地虚拟机部署后 多次点击确实没有出现 undefined
但正式环境一般 jumpserver 会部署在云主机 有时甚至香港、海外等。
是否有一种可能是因为下面这个接口返回超过了一定时间（1s以上？） 导致前端没有拿到数据进行渲染 从而显示为 “undefined”。
http://x.x.x.x/api/v1/assets/assets/c3629d12-896e-42d9-957f-0ea5e2046181/

若是这个原因，前端渲染是否可以优化下 等待接口返回 或 有个重试机制，等待拿到数据后 再渲染出页面。

**Comment by huailei000** [comment]
> 看到的问题： #7135
> 
> 网址： [http://xxx62/ui/#/console/assets/assets/62aa85b1-f410-4f69-b62b-e388824a16c6](http://x.x.x.62/ui/#/console/assets/assets/62aa85b1-f410-4f69-b62b-e388824a16c6) 部署方式：离线部署 版本为：v2.27.0（最新版本） 阿里云主机IP直接访问，前面没有 使用SLBchrome没有WAF浏览器和Opera都有同样的问题。
> 
> ![Snipaste_2022-11-02_14-24-28](https://user-images.githubusercontent.com/7035867/199413979-0240feaf-7c44-47c4-9e43-47b3a2862d86.jpg)
> 
> @wojiushixiaobai @ibuler

![image](https://user-images.githubusercontent.com/31801270/199671609-4f465297-a36e-4c48-914c-da28ec178651.png)
把网速调成慢速的3G网络，接口返回时间2秒多也没有出现报错

**Comment by Anorpi** [comment]
好的 这边看到 返回有被注入一个js文件：`http://1.1.1.3:89/cookie/flash.js`
这个查了下 像是 深信服设备造成的，我这边看下
