### ISSUE TITLE
[Bug] 网页版命令行无法删除命令

### ISSUE THREAD

**Issue by c12q** [jumpserver/jumpserver#4951]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.1

**浏览器版本**

谷歌最新版
**Bug 描述**

用户从网页版登陆，并打开一个交换机的远程，输错一个命令想删除，没反应
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
@c12q 试试 
ctrl + backspace
或者 
shift + backspace
并非 JumpServer bug
