### ISSUE TITLE
禁止执行的命令不生效

### ISSUE THREAD

**Issue by orsfey** [jumpserver/jumpserver#4952]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
我发现一个问题，如果在堡垒机中设置rm命令禁止执行，在web端和终端都可以生效，但是如果这个命令在脚本中执行无法生效。

比如我创建一个脚本文件delfile ，文件内容
rm aa -rf
然后给这个文件700权限，执行这个文件，那么rm命令无法被阻断。

另外域账户我在已经登陆堡垒机的时候为什么不能sso直接授权登陆资产（假设授权资产已经做ldap集成）？还需要继续输入一次域账户资产密码？不能直接读取登陆堡垒机的账户登陆呢？其实已经有选项与用户相同按理来说直接读取堡垒机登陆信息登陆很正常

**Comment by wojiushixiaobai** [comment]
@orsfey 非 agent 方式禁止命令执行，只能防呆，基于字符串的拦截
