### ISSUE TITLE
1.5.2升级到最新版本无法登陆

### ISSUE THREAD

**Issue by CWeThough** [jumpserver/jumpserver#4954]
今天我在使用1.5.3-2版本升级到最新版之后，输入url准备进行登录时，无法登陆。

在输入账号和密码后，点击登录，输入到密码栏的字符串消失了，提示我“* 该字段是必填项。”

升级参考文文档中的“1.4.9 及之后的版本升级到最新版本”部分
https://jumpserver.readthedocs.io/zh/latest/upgrade.html#id9

**Comment by CWeThough** [comment]
![Uploading 微信截图_20201109024221.png…]()

**Comment by ibuler** [comment]
刷新一下浏览器缓存试试
