### ISSUE TITLE
web终端不能使用

### ISSUE THREAD

**Issue by xiaozhiqi2000** [jumpserver/jumpserver#4963]
### Bug 描述
资产：WIN10系统， RDP协议 用WEB终端联接无反应黑屏。

![image](https://user-images.githubusercontent.com/16703381/98528734-aeaf0f80-22b7-11eb-9f9e-318a2217133a.png)

### nginx 报错
- 2020/11/09 18:12:10 [error] 10584#10584: *5507 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.121.161, server: jms.xxx.com, request: "POST /guacamole/api/session/ext/jumpserver/asset/add?user_id=2ea4b827-0e91-4047-a090-593e12f4e49d&asset_id=f56d441c-e595-42d1-bd12-b278f114e5a1&system_user_id=f29ba22d-5e00-424f-9fe7-53edf9995002&token= HTTP/1.1", upstream: "http://192.168.83.35:8081/api/session/ext/jumpserver/asset/add?user_id=2ea4b827-0e91-4047-a090-593e12f4e49d&asset_id=f56d441c-e595-42d1-bd12-b278f114e5a1&system_user_id=f29ba22d-5e00-424f-9fe7-53edf9995002&token=", host: "jms.xxx.com", referrer: "https://jms.xxx.com/luna/?_=1604914772980"
- 2020/11/09 18:12:10 [warn] 10584#10584: *5507 upstream server temporarily disabled while connecting to upstream, client: 192.168.121.161, server: jms.xxx.com, request: "POST /guacamole/api/session/ext/jumpserver/asset/add?user_id=2ea4b827-0e91-4047-a090-593e12f4e49d&asset_id=f56d441c-e595-42d1-bd12-b278f114e5a1&system_user_id=f29ba22d-5e00-424f-9fe7-53edf9995002&token= HTTP/1.1", upstream: "http://192.168.83.35:8081/api/session/ext/jumpserver/asset/add?user_id=2ea4b827-0e91-4047-a090-593e12f4e49d&asset_id=f56d441c-e595-42d1-bd12-b278f114e5a1&system_user_id=f29ba22d-5e00-424f-9fe7-53edf9995002&token=", host: "jms.xxx.com", referrer: "https://jms.xxx.com/luna/?_=1604914772980"
- 2020/11/09 18:12:10 [error] 10584#10584: *5507 no live upstreams while connecting to upstream, client: 192.168.121.161, server: jms.xxx.com, request: "POST /guacamole/api/tokens HTTP/1.1", upstream: "http://guacamole/api/tokens", host: "jms.xxx.com", referrer: "https://jms.xxx.com/luna/?_=1604914772980"

### gua后端注册是正常

![image](https://user-images.githubusercontent.com/16703381/98529101-3268fc00-22b8-11eb-911c-0807a56d5166.png)

**Comment by xiaozhiqi2000** [comment]
ssh web终端是正常登陆的，jumpserver 是分布式部署的

**Comment by wojiushixiaobai** [comment]
guacamole 组件注册异常，请检查

**Comment by xiaozhiqi2000** [comment]
![image](https://user-images.githubusercontent.com/16703381/98533875-8bd42980-22be-11eb-8b9e-29dca99e40d7.png)

windows server出现这个问题，window10正常登陆
