### ISSUE TITLE
install目录中没有安装脚本install.py

### ISSUE THREAD

**Issue by Robin911** [jumpserver/jumpserver#497]
![11](https://user-images.githubusercontent.com/18026355/27172773-f11d03ca-51e8-11e7-8270-a7f38c473f92.png)
install目录中没有安装脚本install.py

**Comment by jinghunao** [comment]
要选主分支，你打开默认是dev，要选master！

**Comment by jiaxiangkong** [comment]
git clone 完后切换一下分支 git checkout master
