### ISSUE TITLE
[Question] Jumpserver 2.4.2版本 通过LDAP 登陆的账号，在下载key后，无法ssh登陆

### ISSUE THREAD

**Issue by qiuyuetao** [jumpserver/jumpserver#4970]
**请描述您的问题.**

Jumpserver 2.4.2版本 通过LDAP 登陆的账号，在下载key后，ssh 2222端口时，无法登陆jumpserver，如何修复？

![image](https://user-images.githubusercontent.com/32032648/98625023-e2d31080-2349-11eb-9b56-9b60fabfcc5c.png)

**Comment by wojiushixiaobai** [comment]
ldap用户不支持key登陆

**Comment by qiuyuetao** [comment]
为什么会有这种变更？ 很不方便啊

**Comment by ibuler** [comment]
因为在 ldap server 上删除用户后，用户还可以通过 key 登录 JS

**Comment by ssx1235690** [comment]
l

> 因为在 ldap server 上删除用户后，用户还可以通过 key 登录 JS

我理解这个可以加一步用户验证的步骤，校验一下域名有无这个用户。而不是禁用key

**Comment by ssx1235690** [comment]
> 因为在 ldap server 上删除用户后，用户还可以通过 key 登录 JS

我理解这个可以加一步用户验证的步骤，校验一下域名有无这个用户。而不是禁用key

**Comment by ssx1235690** [comment]
> 因为在 ldap server 上删除用户后，用户还可以通过 key 登录 JS

我理解这个可以加一步用户验证的步骤，校验一下域内有无这个用户。而不是禁用key

**Comment by BigbigY** [comment]
同样的疑惑，这样很多用户会找运维来设置公钥，而不是之前的用户自己可以修改自己的公钥，我觉得可以让运维来屏蔽清理用户公钥也行

**Comment by ibuler** [comment]
@ssx1235690 是一个好的方案，我们研究一下，看看能不能解决一下

**Comment by jym503558564** [comment]
移至该Issues: https://github.com/jumpserver/jumpserver/issues/5710
