### ISSUE TITLE
[Bug] Version 1.5.9-2 GPLv2 升级到v2.4以上版本的luna限制鼠标和键盘复制的问题

### ISSUE THREAD

**Issue by elite8** [jumpserver/jumpserver#4974]
**JumpServer 版本(v1.5.9以下不再支持)**
Version 1.5.9-2 GPLv2

**浏览器版本**
Chrome  88.0.4298.4 
Firefox 82.0.2 (64 位)

**Bug 描述**
我现在部署的版本在luna的index.html文件中添加部分限制鼠标右键以及键盘复制的代码，但是当我升级到v2.4以上版本之后，在新版本的luna中的index.html文件中添加限制的代码没有生效。请帮忙看看我如果要在新版本中继续使用如下的功能限制应该如何操作，谢谢！附件是我的index.html文件
[index.html.txt](https://github.com/jumpserver/jumpserver/files/5516239/index.html.txt)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
@orangemio

**Comment by elite8** [comment]
请问这个问题能解决吗？我上次升级2.4版本发现这个不能禁用的功能不能生效，还原到1.5.9版本就好了，但是以后你们这边不支持我现在这个版本了。那我总不能一直就使用1.5.9版本吧。

**Comment by ibuler** [comment]
目前没有时间处理二次开发的问题，请自行研究一下吧
