### ISSUE TITLE
[Question] 开启多因子认证后，终端连不上

### ISSUE THREAD

**Issue by jinyanroot** [jumpserver/jumpserver#4984]
版本：2.3.0

我的终端是用密钥连接的，未开启多因子认证，可以正常连接。
开启多因子后，Web端可以正常登录。
但是用终端连接，提示"The client has disconnected from the server.  Reason:Unable to authenticate using any of the configured authentication methods."。

终端哪里输入Google Authenticator的验证码呢？

**Comment by wojiushixiaobai** [comment]
@jinyanroot 认证方式请选择交互式登陆

**Comment by jinyanroot** [comment]
可以了，多谢。

如下
![image](https://user-images.githubusercontent.com/16056880/99206734-240a6b00-27f7-11eb-9366-de8567b43aab.png)

**Comment by SocketNet** [comment]
linux 终端如何登录
