### ISSUE TITLE
[Bug] SESSION_COOKIE_AGE配置问题

### ISSUE THREAD

**Issue by Gary0317** [jumpserver/jumpserver#4985]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer 2.2.1

**浏览器版本**

**Bug 描述**
关于SESSION_COOKIE_AGE配置  实际是从登陆开始算时间。不是从最后一次操作算时间

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
是这样的，如果在 lina 中有操作，或者 在 luna中 点击过树，会自动续期的
