### ISSUE TITLE
加急！！！！telnet协议bug

### ISSUE THREAD

**Issue by ltd-3611** [jumpserver/jumpserver#4992]
**JumpServer 版本(v1.5.9以下不再支持)**
版本jumpserver v2.2.2

**浏览器版本**
谷歌浏览器      版本 86.0.4240.183（正式版本） （64 位

**Bug 描述**
1、资产使用telnet协议后webshell连接会提示：该资产没有系统用户；
2、将telnet协议改成ssh协议后可正常显示可连接的系统用户；
3、资产为思科交换机，只能通过telnet方式登录。

**Bug 重现步骤(有截图更好)**
1.  ssh的22端口情况下，可以显示资产用户
![image](https://user-images.githubusercontent.com/56915670/99043032-b5e06100-25c8-11eb-81e1-cf9279a223dd.png)
![image](https://user-images.githubusercontent.com/56915670/99043206-f7710c00-25c8-11eb-97bd-e6aa24888b36.png)

2. 改成telnet协议23端口就无法显示可用的系统用户
![image](https://user-images.githubusercontent.com/56915670/99043310-1e2f4280-25c9-11eb-938a-466ef62d517a.png)
![image](https://user-images.githubusercontent.com/56915670/99043473-41f28880-25c9-11eb-8810-84d33eb1b0e7.png)

3. 问题连接性描述不是很好，意思很好理解，ssh22可以正常显示交换机系统用户，telnet23无法显示可连接交换机系统用户。
另外，ssh测试连接华为、华三、锐捷交换机都可正常显示连接，思科比较特殊只能telnet登录，但是发现这么个bug。望尽早答复，感谢。

**Comment by LeeEirc** [comment]
@ltd-3611 系统用户的协议需要设置成telnet，资产的协议组添加telnet的端口。 这样你的授权才能正常显示。

**Comment by ltd-3611** [comment]
> @ ltd-3611系统用户的协议需要设置成telnet，资产的协议组添加telnet的端口。这样你的授权才能正常显示。

好的 已解决，万分感谢，同时希望官方可以将系统支持同时配置多种登录协议。
