### ISSUE TITLE
debian ubuntu系统什么时候也做一个脚本呢

### ISSUE THREAD

**Issue by arnolix** [jumpserver/jumpserver#50]
debian ubuntu系统什么时候也做一个脚本呢

**Comment by ibuler** [comment]
手里没有debian，ubuntu，也没有维护过，你可以试试写个

**Comment by jiaxiangkong** [comment]
一、环境 
debian，ubuntu 系统

二、安装依赖
apt-get install vim git python-pip libmysqlclient-dev gcc automake autoconf  python-dev  sshpass lrzsz python-mysqldb

注：如果报没有找安装包，请添加系统更新源

三、 下载jumpserver 
cd /opt 
git clone https://github.com/ibuler/jumpserver.git 

四、 执行快速安装脚本 
cd jumpserver/install && pip install -r requirements.txt 

五、修改安装脚本
vim install.py

`#!/usr/bin/python
# coding: utf-8

import subprocess
import time
import os
import sys
import MySQLdb
from smtplib import SMTP, SMTPAuthenticationError, SMTPConnectError
import ConfigParser
import socket
import fcntl
import struct
import readline

jms_dir = os.path.dirname(os.path.abspath(os.path.dirname(__file__)))
sys.path.append(jms_dir)


def bash(cmd):
    """
    run a bash shell command
    执行bash命令
    """
    return subprocess.call(cmd, shell=True)


def color_print(msg, color='red', exits=False):
    """
    Print colorful string.
    颜色打印字符或者退出
    """
    color_msg = {'blue': '\033[1;36m%s\033[0m',
                 'green': '\033[1;32m%s\033[0m',
                 'yellow': '\033[1;33m%s\033[0m',
                 'red': '\033[1;31m%s\033[0m',
                 'title': '\033[30;42m%s\033[0m',
                 'info': '\033[32m%s\033[0m'}
    msg = color_msg.get(color, 'red') % msg
    print msg
    if exits:
        time.sleep(2)
        sys.exit()
    return msg


def get_ip_addr(ifname='eth0'):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        return socket.inet_ntoa(fcntl.ioctl(
            s.fileno(),
            0x8915,
            struct.pack('256s', ifname[:15])
        )[20:24])
    except:
        ips = os.popen("LANG=C ifconfig | grep \"inet addr\" | grep -v \"127.0.0.1\" | awk -F \":\" '{print $2}' | awk '{print $1}'").readlines()
        if len(ips) > 0:
            return ips[0]
    return ''


class PreSetup(object):
    def __init__(self):
        self.db_host = '127.0.0.1'
        self.db_port = 3306
        self.db_user = 'jumpserver'
        self.db_pass = '5Lov@wife'
        self.db = 'jumpserver'
        self.mail_host = 'smtp.qq.com'
        self.mail_port = 25
        self.mail_addr = 'hello@jumpserver.org'
        self.mail_pass = ''
        self.ip = ''

    def write_conf(self, conf_file=os.path.join(jms_dir, 'jumpserver.conf')):
        color_print('开始写入配置文件', 'green')
        conf = ConfigParser.ConfigParser()
        conf.read(conf_file)
        conf.set('base', 'url', 'http://%s' % self.ip)
        conf.set('db', 'host', self.db_host)
        conf.set('db', 'port', self.db_port)
        conf.set('db', 'user', self.db_user)
        conf.set('db', 'password', self.db_pass)
        conf.set('db', 'database', self.db)
        conf.set('websocket', 'web_socket_host', '%s:3000' % self.ip)
        conf.set('mail', 'email_host', self.mail_host)
        conf.set('mail', 'email_port', self.mail_port)
        conf.set('mail', 'email_host_user', self.mail_addr)
        conf.set('mail', 'email_host_password', self.mail_pass)

        with open(conf_file, 'w') as f:
            conf.write(f)

    def _setup_mysql(self):
        color_print('开始安装设置mysql (请手动设置mysql安全)', 'green')
        color_print('默认用户名: %s 默认密码: %s' % (self.db_user, self.db_pass), 'green')
        bash('apt-get -y install mysql-server')
        bash('/etc/init.d/mysql start')
        bash('mysql -e "create database %s default charset=utf8"' % self.db)
        bash('mysql -e "grant all on %s.* to \'%s\'@\'%s\' identified by \'%s\'"' % (self.db,
                                                                                     self.db_user,
                                                                                     self.db_host,
                                                                                     self.db_pass))

    @staticmethod
    def _set_env():
        color_print('开始关闭防火墙和selinux', 'green')
        bash('ufw disable && setenforce 0')

    def _test_db_conn(self):
        try:
            MySQLdb.connect(host=self.db_host, port=self.db_port,
                            user=self.db_user, passwd=self.db_pass, db=self.db)
            color_print('连接数据库成功', 'green')
            return True
        except MySQLdb.OperationalError, e:
            color_print('数据库连接失败 %s' % e, 'red')
            return False

    def _test_mail(self):
        try:
            smtp = SMTP(self.mail_host, port=self.mail_port, timeout=2)
            smtp.login(self.mail_addr, self.mail_pass)
            smtp.sendmail(self.mail_addr, (self.mail_addr, ),
                          '''From:%s\r\nTo:%s\r\nSubject:Jumpserver Mail Test!\r\n\r\n  Mail test passed!\r\n''' %
                          (self.mail_addr, self.mail_addr))
            smtp.quit()
            return True

        except (SMTPAuthenticationError, socket.timeout, socket.gaierror), e:
            color_print(e, 'red')
            return False

    @staticmethod
    def _rpm_repo():
        color_print('开始安装epel源', 'green')
        bash('yum -y install epel-release')

    @staticmethod
    def _depend_rpm():
        color_print('开始安装依赖rpm包', 'green')
        bash('apt-get -y install git python-pip libmysqlclient-dev gcc automake autoconf python-dev vim sshpass')

    @staticmethod
    def _require_pip():
        color_print('开始安装依赖pip包', 'green')
        bash('pip install -r requirements.txt')

    def _input_ip(self):
        ip = raw_input('\n请输入您服务器的IP地址，用户浏览器可以访问 [%s]: ' % get_ip_addr())
        self.ip = ip if ip else get_ip_addr()

    def _input_mysql(self):
        while True:
            mysql = raw_input('是否安装新的MySQL服务器? (y/n) [y]: ')
            if mysql != 'n':
                self._setup_mysql()
            else:
                db_host = raw_input('请输入数据库服务器IP [127.0.0.1]: ')
                db_port = raw_input('请输入数据库服务器端口 [3306]: ')
                db_user = raw_input('请输入数据库服务器用户 [root]: ')
                db_pass = raw_input('请输入数据库服务器密码: ')
                db = raw_input('请输入使用的数据库 [jumpserver]: ')

                if db_host: self.db_host = db_host
                if db_port: self.db_port = db_port
                if db_user: self.db_user = db_user
                if db_pass: self.db_pass = db_pass
                if db: self.db = db

            if self._test_db_conn():
                break

            print

    def _input_smtp(self):
        while True:
            self.mail_host = raw_input('请输入SMTP地址: ').strip()
            mail_port = raw_input('请输入SMTP端口 [25]: ').strip()
            self.mail_addr = raw_input('请输入账户: ').strip()
            self.mail_pass = raw_input('请输入密码: ').strip()

            if mail_port: self.mail_port = int(mail_port)

            if self._test_mail():
                color_print('\n\t请登陆邮箱查收邮件, 然后确认是否继续安装\n', 'green')
                smtp = raw_input('是否继续? (y/n) [y]: ')
                if smtp == 'n':
                    continue
                else:
                    break
            print

    def start(self):
        # self._rpm_repo()
        # self._depend_rpm()
        # self._require_pip()
        self._set_env()
        self._input_ip()
        self._input_mysql()
        self._input_smtp()
        self.write_conf()
        os.system('python %s' % os.path.join(jms_dir, 'install/next.py'))


if __name__ == '__main__':
    pre_setup = PreSetup()
    pre_setup.start()
`

六、安装

python install.py 
注：debian，ubuntu系统上安装完成最后会出现服务启动失败 
1）根据提示输入相关信息，完成安装，完成安装后，请访问web，继续查看后续文档 
2）如果启动失败，请返回上层目录，手动运行 ./service.sh start启动 
3）如果./service.sh start启动失败 
请进入jumpserver目录，手动运行 
python manage.py runserver 0.0.0.0:80 
python run_websocket.py 
4）如果启动失败，可能是由于 80端口和3000端口已经被占用，或者数据库账号密码不对，请检查

七、运行crontab，定期处理失效连接，定期更新资产信息 
cd .. && python manage.py crontab add

**Comment by yumaojun03** [comment]
now the install.py can use to install jumpserver on ubuntu 14.04 and 15.10 (tested).
with ubuntu you mast use root to execute the install script.
eg: 
    sudo -i
    python install.py

note:
    the python version 2.x

**Comment by liuzheng712** [comment]
@yumaojun03 python version 2.6- 测过没？

**Comment by yumaojun03** [comment]
ubunt 14.04 和 ubuntu 15.10 系统自带的python版本至少是2.7。所有没测试过2.6

**Comment by liuzheng712** [comment]
所以指定Python version的时候不要写2.x吧，写2.7+

**Comment by yumaojun03** [comment]
恩，我更新了。
