### ISSUE TITLE
[Bug] 最新社区版一键脚本安装KoKo失败

### ISSUE THREAD

**Issue by aheig** [jumpserver/jumpserver#5001]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.4

**浏览器版本**
v80

**Bug 描述**
最新社区版（2.4.4）一键脚本安装KoKo失败，网络是香港网络

**Bug 重现步骤(有截图更好)**
1.  ··
>> Download Core
>> Download Lina
>> Download Luna
/opt/setuptools/scripts/download.sh:行70: docker: 未找到命令
>> Download KoKo
/opt/setuptools/scripts/download.sh:行46: docker: 未找到命令
[ERROR] 下载 KoKo 失败
··
2. 
3. 
![image](https://user-images.githubusercontent.com/61814388/99141969-5dbe6300-268b-11eb-8107-eec18476864f.png)

**Comment by wojiushixiaobai** [comment]
@aheig 请使用全新的操作系统进行安装
该错误是 docker 安装失败导致

**Comment by aheig** [comment]
是全新的系统，最小安装和带桌面安装都试过。到图上那一步就失败了

**Comment by aheig** [comment]
系统版本7.x  2003  和2009都是这个报错

**Comment by aheig** [comment]
更换yum源安装成功！比较迷的是，先后试过腾讯云、中科大、阿里云的yum源都失败。最后换成网易云yum源安装成功！
