### ISSUE TITLE
最新社区版2.4.4需要升级MySQL到5.7+？

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5002]
升级到2.4.4后出现下面的错误。
![image](https://user-images.githubusercontent.com/10806595/99142519-96ad0680-2690-11eb-84cc-85c6ff472536.png)

**Comment by wojiushixiaobai** [comment]
@bingws 未复现此问题，请群里联系我远程看下

**Comment by bingws** [comment]
@wojiushixiaobai 上班不用qq。我先回退到上个版本了。暂不影响。
好像是新加的这个文件产生的错误：https://github.com/jumpserver/jumpserver/blob/master/apps/applications/models/application.py
![image](https://user-images.githubusercontent.com/10806595/99201778-9a06d600-27e7-11eb-8baa-a3789368c926.png)

![image](https://user-images.githubusercontent.com/10806595/99201799-adb23c80-27e7-11eb-897c-72edfe35989f.png)

**Comment by ibuler** [comment]
是的，需要升级到 5.7+
