### ISSUE TITLE
[Question] 关于jumpserver配置连接 MacOS VNCServer的问题

### ISSUE THREAD

**Issue by T4di5** [jumpserver/jumpserver#5006]
JumpServer 版本
v2.4.4

状况描述：
在配置完毕MacOS server资产后，在MacOS server资产上配置自带的VNCServer，配置端口5900，在jumpserver web端vnc连接

MacOS server始终不成功，log报错为无法转换“录像session”

**Comment by wojiushixiaobai** [comment]
需要关闭加密

**Comment by T4di5** [comment]
> 需要关闭加密
> 自带的远程管理不支持，因为他不支持关闭加密。
> 需要第三方的 vncserver 服务端

这个可以在doc.jumpserver.net中备注一下吗

**Comment by ibuler** [comment]
@wojiushixiaobai 备注一下， issue 我关闭了

**Comment by wojiushixiaobai** [comment]
文档里面一直有此说明

**Comment by reyleon** [comment]
> 需要关闭加密
> 自带的远程管理不支持，因为他不支持关闭加密。
> 需要第三方的 vncserver 服务端

并不是吧。我自测通过 Guacamole 0.9.14 ， VNC是 可以连接自带的macOS屏幕共享（VNC）的。
我的macOS版本 10.14。

但是我配置的jumpserver 2.1.0 也是无法vnc到macOS，不知道哪里有问题。
rdp到windows 10
vnc到centos 7桌面
都正常。

唯独 macOS 连不上。
