### ISSUE TITLE
[Bug] 当资产节点占满一页时右键菜单显示不全

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5007]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.3

**浏览器版本**
FF82 & Chrome Version 86.0.4240.193 

**Bug 描述**
当有资产节点占满一页时，在页面底部的资产节点右键菜单，不能显示全，也无法选择右键菜单相关操作。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![图片](https://user-images.githubusercontent.com/24548477/99219502-c33f5a80-2817-11eb-8ff3-f0774e91b590.png)

**Comment by ibuler** [comment]
完成
