### ISSUE TITLE
[0.3.2 master版本] 通过ssh方式登录的vi操作，都无法审计

### ISSUE THREAD

**Issue by xieyuanpeng** [jumpserver/jumpserver#501]
[0.3.2 master版本] 通过ssh方式登录的vi操作，日志审计的录像回放时会播放到vi打开文件的操作之后就停了，后续的操作都无法播放。
而通过web方式登录的vi操作，则都可以完美审计。

**Comment by xieyuanpeng** [comment]
这个是无解么？

**Comment by lichenglongqi** [comment]
弱弱的问一句，视频审计vim的这个bug解决了么？ @ibuler

**Comment by ibuler** [comment]
0.5.0 已解决
