### ISSUE TITLE
增加basepath定义

### ISSUE THREAD

**Issue by jasen2002** [jumpserver/jumpserver#5014]
能不能把这个系统所有访问的url放到某一固定根目录下进行访问？
这样好与现有的一些系统集成到一个域名下，如www.test.com/jumpserver/*，www.test.com/zabbix/* 这样部署到一个子目录下。
我看了lina目录下的js文件都是写死从根目录开始的，如/ui/, /api/,这样没法用重写路径来解决我想要的。
不知道这个功能是否存在，或是可以增加

**Comment by ibuler** [comment]
目前可能不行了，之前前后端没有分离的时候是可以的
