### ISSUE TITLE
[Feature] 可变动态用户

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5015]
**请描述您的需求或者改进建议.**
动态系统用户可以使用户名与用户想同，但是对于(一台windows)有多个远程应用的情况下，一个用户名还是只能打开安装于某台机器上的一个远程应用（打开第二个远程应用会断开第一个远程应用）。建议增加一类含变量的动态用户：变量部分为远程应用名字，这样在授权后，与该“变动态用户”关联的、将要被推送的系统用户名为：<用户名>_<应用名>，如：zhangsan_chrome, zhangsan_navicat。这样，zhangsan这个用户可以同时打开同一台windows上的2个远程应用：以zhangsan_chrome用户打开chrome浏览器，以zhangsan_navicat打开navicat。

**Comment by ibuler** [comment]
太复杂了，目前动态用户都让整个权限，变得很复杂了
