### ISSUE TITLE
[Question] windows 如何下载文件到本地？

### ISSUE THREAD

**Issue by jfrenhub** [jumpserver/jumpserver#5016]
**请描述您的问题.**
Version v2.4.3 GPLv2
windows 不能下载文件到本地，文件管理中都是空的，linux 可以看到目录

**Comment by ibuler** [comment]
windows不在文件管理中， windows的可以放到 G 盘中，通过快捷键  alt + ctrl + shift 展开左侧边栏，从目录中下载
