### ISSUE TITLE
[Feature] 登录日志显示列的优化

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5017]
**请描述您的需求或者改进建议.**
公司内网有22开头的网段，登录日志的“登录城市”显示美国，显然也不合理，而且“登录城市”的显示我司场景中也没意义。建议：
1. 允许管理员将内网使用的公网IP段定义为企业内网，以覆盖IP地址库的查询
2. 去掉或允许管理员配置是否显示“登录城市”列。

**Comment by ibuler** [comment]
计划在支持表格用户自己控制显示的列
