### ISSUE TITLE
[Bug] Centos 7.9.2009最小化安装，极速部署失败

### ISSUE THREAD

**Issue by zhanglei0310** [jumpserver/jumpserver#5018]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.4

**浏览器版本**
与浏览器无关

**Bug 描述**
![image](https://user-images.githubusercontent.com/438092/99343869-ba0ec600-28c9-11eb-8921-309be35e1057.png)

**Bug 重现步骤(有截图更好)**
1.  Centos 7.9.2009 mini安装
2. 极速部署脚本执行curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.4.4/quick_start.sh | sh
3. 安装失败，尝试了2次结果都是一样的
4. Package python3-devel-3.6.8-13.el7.x86_64 already installed and latest version
Nothing to do
>> Download Core
>> Download Lina
>> Download Luna
/opt/setuptools/scripts/download.sh: line 70: docker: command not found
>> Download KoKo
/opt/setuptools/scripts/download.sh: line 46: docker: command not found
[ERROR] 下载 KoKo 失败

**Comment by zhanglei0310** [comment]
看起来提示是需要先安装docker运行环境？前序说明文档并没有看到有对应的说明要求。操作系统是全新安装的

**Comment by zhanglei0310** [comment]
回退到 CentOS-7-x86_64-Minimal-2003.iso 安装成功。

**Comment by palkiller** [comment]
看提示是没有安装docker的缘故，docker-ce手工安装一下应该就可以了吧

**Comment by zhanglei0310** [comment]
> 看提示是没有安装docker的缘故，docker-ce手工安装一下应该就可以了吧

脚本内理应自动安装部署docker的，提示我看懂了，我反馈主要是基于初始化系统版本为2009的情况下没有被正常自动执行的情况反馈一下。

**Comment by wojiushixiaobai** [comment]
@zhanglei0310 测试可以，请检查系统是否做过修改；可以参考极速安装的视频演示，视频里面的新版本均使用最新版本的 CentOS 7
