### ISSUE TITLE
密码长度过长导致系统报错

### ISSUE THREAD

**Issue by nineaiyu** [jumpserver/jumpserver#502]
添加资产的时候，我们服务器的密码一般为32随机码，当我通过文件导入的时候，报错了，我
![jumpserver](https://user-images.githubusercontent.com/19207867/27360884-6fc2bed8-5656-11e7-9498-06f1e33ccc63.png)
需要改哪些东西可以让jumpserver支持32长度的密码？

**Comment by hellorocky** [comment]
看着像是数据库字段设置的字符数限制

**Comment by qils** [comment]
![source](https://user-images.githubusercontent.com/13659718/27428502-d2fc72f4-5774-11e7-83be-5c064203fa6c.png)

批量从execl中添加资产, 源码里面没有对密码长度做限制
