### ISSUE TITLE
[Bug] Jumpserver无法继续添加Windows资产

### ISSUE THREAD

**Issue by CWeThough** [jumpserver/jumpserver#5020]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.3

**浏览器版本**
Chrome 85.0.4183.121（正式版本） （32 位

**Bug 描述**
现在环境中有Linux机器120台、Windows机器78台，当我尝试继续添加一台Windows2016资产时，可以添加到资产列表，但是无法在Web终端连接资产，在屏幕中央显示“连接出错 联系不上传承桌面服务器，如果问题持续，请通知您的系统管理员，或检查您的系统日志”。
在F12的Network中，发现了一个404：

Request URL: http://192.168.0.1/guacamole/api/session/tunnels/34f306f2-8784-4f96-9d60-26a03d935725/activeConnection/connection/sharingProfiles?token=4792FF71893F51D2C86CC9FB9DC78777CB4174A0AA24D830A128B22675B1DCC0

Request Method: GET
Status Code: 404 

在服务器上telnet这台资产的3389端口是没问题的，连接其他Windows2016资产也没问题

**Bug 重现步骤(有截图更好)**
1.  在资产列表中添加资产
2.  web终端连接失败

**Comment by CWeThough** [comment]
在/opt/jumpserver/log/jumpserver.log中：

2020-11-17 16:55:37 [base ERROR] AssetUserManager Object matching query does not exist
Traceback (most recent call last):
  File "/opt/jumpserver/apps/assets/models/base.py", line 172, in get_asset_user
    other = manager.get(username=self.username, asset=asset, prefer_id=self.id)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 74, in get
    self.raise_does_not_exist(self.__class__.__name__)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 79, in raise_does_not_exist
    raise self.ObjectDoesNotExist(self.MSG_NOT_EXIST.format(name))
django.core.exceptions.ObjectDoesNotExist: AssetUserManager Object matching query does not exist

**Comment by ibuler** [comment]
已发现问题所在，这个资产应该没有关联系统用户

**Comment by CWeThough** [comment]
您好，根据检查，该资产和之前添加的Windows2016资产一样，都关联了专门给Windiws创建的手动登录系统用户

**Comment by CWeThough** [comment]
今天上午，我在没有动这台Windows2016资产的情况下，又在资产列表中依次添加了2012R2、2019、2016的资产发现2012R2和2019可以连接，2016无法连接。后来将寻添加的2016资产的系统由Windows（2016）改为Windows后，2016新添加的就可以连接了。然后又尝试将之前连不上那台2016机器的系统由Windows（2016）改为Windows后，也可以连接了。
