### ISSUE TITLE
[Bug] 连接mysql输入较长sql向右翻页

### ISSUE THREAD

**Issue by alwaystest18** [jumpserver/jumpserver#5026]
**JumpServer 版本(v2.2.1)**

**Bug 描述**

连接mysql输入较长sql会向右翻页，而不是像正常mysql客户端那样换行显示，是个小问题，不过体验还是很明显的

**Comment by LeeEirc** [comment]
@alwaystest18 有优化过，使用最新的版本试一下吗？

**Comment by jym503558564** [comment]
新版本已修复，请更新测试。
