### ISSUE TITLE
0.3.2 web terminal无法使用

### ISSUE THREAD

**Issue by zzlyzq** [jumpserver/jumpserver#503]
第一处修改
/opt/jumpserver/jumpserver/jlog/views.py
268行修改如下
self.log[str(time.time() - self.recoderStartTime)] = msg.decode('utf-8', 'replace')

第二处修改
/usr/lib/python2.6/site-packages/paramiko/message.py
244行修改如下:
self.packet.write(struct.pack('>I', long(n)))

上述两种修改之后，虽然点击 连接 后，可以有命令提示符提示登录成功，但是无法输入东西。

0.3.0 版本中可以使用，暂时切换回去了。

[0.3.2 web terminal 无法使用](http://ojv12llai.bkt.clouddn.com/0.3.2.png)

**Comment by ibuler** [comment]
same with #568
