### ISSUE TITLE
1.5.0版本这个requirements/requirements.txt文件里面urllib3这个包

### ISSUE THREAD

**Issue by yuanchao-sh** [jumpserver/jumpserver#5030]
git clone https://github.com/jumpserver/jumpserver.git
#检出1.5.0分支
git checkout 1.5.0

requirements/requirements.txt文件里面urllib3这个包默认是要下载urllib3==1.25.2版本
操作报错：
pip install -r jumpserver/requirements/requirements.txt -i  https://mirrors.aliyun.com/pypi/simple/
![image](https://user-images.githubusercontent.com/66761562/99387063-522e9e80-290e-11eb-9b20-44b7d0dc2404.png)

The conflict is caused by:
    The user requested urllib3==1.25.2
    elasticsearch 6.1.1 depends on urllib3<1.23 and >=1.21.1

elasticsearch 6.1.1需要urllib3<1.23 and >=1.21.1，我requirements.txt改成urllib3==1.21.1
![image](https://user-images.githubusercontent.com/66761562/99387249-9f127500-290e-11eb-866a-8bbb8ec96343.png)
The conflict is caused by:
    
    The user requested urllib3==1.21.1
    elasticsearch 6.1.1 depends on urllib3<1.23 and >=1.21.1
    requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
    jms-storage 0.0.23 depends on urllib3==1.25.2

urllib3==1.21.1满足了elasticsearch 6.1.1， requests 2.22.0，但是    jms-storage 0.0.23这个又不行了
不指定版本也不行，2个版本都下载也不行
请问怎么处理一下

**Comment by yuanchao-sh** [comment]
https://github.com/jumpserver/jumpserver/issues/2771
找到了这个

**Comment by xiezhengdong** [comment]
我也遇见了这个问题，请问怎么解决呢

**Comment by yuanchao-sh** [comment]
试着去忽略。



She400800@163.com
 
发件人： xiezhengdong
发送时间： 2020-12-28 09:38
收件人： jumpserver/jumpserver
抄送： yuanchao-sh; State change
主题： Re: [jumpserver/jumpserver] 1.5.0版本这个requirements/requirements.txt文件里面urllib3这个包 (#5030)
我也遇见了这个问题，请问怎么解决呢
