### ISSUE TITLE
[Feature] 在监控页面添加中断用户操作的选项

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5035]
**请描述您的需求或者改进建议.**
1：在监控页面看到违规操作的时候，希望在监控页面直接中断操作人的资产登录会话，现在的版本中监控页面只能看到操作，看到违规操作之后返回到主页面找到相关会话再去中止比较麻烦，
2：在监控页面中断会话时，先执行中断操作，然后出现弹窗或者其他提示框写入中断原因，然后把执行中断人的信息和中断原因通过邮件发送给被中断人

**Comment by jym503558564** [comment]
目前未支持，请持续关注我们版本发布。感谢反馈
