### ISSUE TITLE
[Feature] 高危命令告警功能建议

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5036]
**请描述您的需求或者改进建议.**
我看到2.5支持高危操作邮件通知功能，希望可以在定义高危命令的时候，也可以写入把命令列为高危命令的注释，然后通过高危命令告警的时候把注释也发送过去
比如：交换机上执行删除默认路由的命令：ip route 0.0.0.0 0.0.0.0 192.168.1.1  然后我通过过滤命令限制正常输入命令会被阻断，需要在前4个0后面多写几个空格ip route 0.0.0.0     0.0.0.0 192.168.1.1就可以执行，我这个删除默认命令写到高危命令列表，然后写上注释如果要成功执行需要怎么操作的步骤，有人执行失败的时候就可以知道怎么执行可以成功了。防止有些高危命令需要执行，但是又不想用常规方法执行，可以减少误操作。

**Comment by palkiller** [comment]
多个空格用正则表达式可以匹配的吧，不过我感觉这个命令过滤功能有点问题，我在2.4.4版本上设置了正则表达式[^sys]*，输入命令之后，会提示高危，但不会阻断-_-|||
