### ISSUE TITLE
[Bug] 调用 /api/v1/assets/nodes/{id}/children/ 新建资产节点时报错

### ISSUE THREAD

**Issue by walnut-tom** [jumpserver/jumpserver#5039]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.0

**浏览器版本**

**Bug 描述**
调用 /api/v1/assets/nodes/{id}/children/ 新建资产节点时报错
argument of type 'NoneType' is not iterable

**Bug 重现步骤(有截图更好)**
1.  调用接口 获取 Default 资产节点的id，假设id为 73b94fb8-8e30-2296-c6a5-b32ffc42b236
2. 调用 /api/v1/assets/nodes/{id}/children/ 新建资产节点时报错 argument of type 'NoneType' is not iterable
body：
`{"id":"633cc300-e5ab-437a-b38b-75c42753d4de","value":"test"}`

**Comment by walnut-tom** [comment]
以前用 2.4.3 是好的，升级到 2.5.0 就开始报错了

**Comment by jym503558564** [comment]
在最近几个版本，无法复现该问题。可升级进行测试。如还存在该问题可再次打开Issues
