### ISSUE TITLE
[Bug] 关于系统用户下资产数量的计算逻辑

### ISSUE THREAD

**Issue by PollosD** [jumpserver/jumpserver#5045]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.4

**浏览器版本**
谷歌

**Bug 描述**
发现在系统用户下后面的资产数量是根据资产授权来的，比如说同一个授权规则里面出现了多个系统用户与节点，那么对应的系统用户下面就会显示所有相关的节点服务器数量，而且只有初次设置有效，即使后面更改了节点数量也不会变化。
私以为系统用户的资产数量计算应该是可以使用该系统用户可以登录的资产数量。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
并不是，系统用户和资产的关系 是客观存在的，这个资产上有没有这个系统用户，应该是确定好的，只不过 JumpServer 有了自动推送，如果这个资产上 不存在 这个系统用户，则会协助 创建。

**Comment by ibuler** [comment]
还有一个考量就是 如果 系统用户和资产的关系，如果是随着授权改变的话，那么是不稳定的，授权规则随时可能改变
