### ISSUE TITLE
Centos7极速部署V2.5.0 web界面不显示“Web终端”，同时ssh时连不上

### ISSUE THREAD

**Issue by IvanWongw** [jumpserver/jumpserver#5047]
**请描述您的问题.**
Centos7极速部署了V2.5.0，部署过程中没报错，但web端不显示“web终端”，而“终端管理”中的Gua和koko都正常激活
![微信截图_20201120102729](https://user-images.githubusercontent.com/16550054/99750270-0a309700-2b1b-11eb-9c4a-b54d97546826.png)

**Comment by wojiushixiaobai** [comment]
右上角

**Comment by IvanWongw** [comment]
@wojiushixiaobai 谢谢！web端看到了登录入口，但是在secuCRT使用ssh key连接时，一直连接失败，koko.log提示如下：
![koko log](https://user-images.githubusercontent.com/16550054/99751040-6942db80-2b1c-11eb-8b2c-f4f06d24f3f1.png)

**Comment by IvanWongw** [comment]
使用key单独连接该资产时，正常连接，但通过JMS时报上面的错误

**Comment by IvanWongw** [comment]
可以了，原因是web端中的“终端设置”，不允许“密码认证”和“密钥认证”都勾选上，如果都勾选后，当配置只允许key登录时，判断语句只检查第一个勾选，而没做轮询判断
