### ISSUE TITLE
批量命令一直在等待

### ISSUE THREAD

**Issue by yuanchao-sh** [jumpserver/jumpserver#5048]
1.5.9
批量命令一直在等待，执行不下去
![image](https://user-images.githubusercontent.com/66761562/99767326-d2871680-2b3d-11eb-8723-a122fa8e1214.png)

哪里有日志，怎么处理

**Comment by ibuler** [comment]
可能是 celery 卡住了，看看 celery 的监控，有没有任务 hang 住

**Comment by wineejam** [comment]
我也遇到这个问题了，求助
![图片](https://user-images.githubusercontent.com/8789004/104671422-c328e180-5718-11eb-9e3a-4156a89573fd.png)

查看celery_ansible.log的日志，实际上命令已经执行了，也有结果返回，但是web界面却是一直是在等待
![图片](https://user-images.githubusercontent.com/8789004/104671427-c8862c00-5718-11eb-9515-c453d923294e.png)

**Comment by dong9205** [comment]
版本 2.7.1 遇到相同问题, 在web前端查看celery是空的, 从终端tail -f 实时查看了celary_ansible.log.  是成功的

![image](https://user-images.githubusercontent.com/40266166/107205005-53b4c200-6a38-11eb-8352-25ca0faff301.png)

**Comment by dong9205** [comment]
> 版本 2.7.1 遇到相同问题, 在web前端查看celery是空的, 从终端tail -f 实时查看了celary_ansible.log. 是成功的
> 
> ![image](https://user-images.githubusercontent.com/40266166/107205005-53b4c200-6a38-11eb-8352-25ca0faff301.png)

已解决，redis版本问题, 使用的默认镜像源，装了4.x的，手动安装了6.x就可以了.

**Comment by hansenshi** [comment]
> > 版本 2.7.1 遇到相同问题, 在web前端查看celery是空的, 从终端tail -f 实时查看了celary_ansible.log. 是成功的
> > ![image](https://user-images.githubusercontent.com/40266166/107205005-53b4c200-6a38-11eb-8352-25ca0faff301.png)
> 
> 已解决，redis版本问题, 使用的默认镜像源，装了4.x的，手动安装了6.x就可以了.
====
正解：我也是2.7.1，也是这个问题，redis从3.2.12版本而升级到6.0.10，就可以了。
![image](https://user-images.githubusercontent.com/19355780/108583198-d27ff800-7372-11eb-9508-5bf8c1b796b8.png)

**Comment by hansenshi** [comment]
> > 版本 2.7.1 遇到相同问题, 在web前端查看celery是空的, 从终端tail -f 实时查看了celary_ansible.log. 是成功的
> > ![image](https://user-images.githubusercontent.com/40266166/107205005-53b4c200-6a38-11eb-8352-25ca0faff301.png)
> 
> 已解决，redis版本问题, 使用的默认镜像源，装了4.x的，手动安装了6.x就可以了.
====
感谢，我也是2.7.1，也是这个问题，redis从3.2.12版本而升级到6.0.10，问题解决了。
![image](https://user-images.githubusercontent.com/19355780/108583238-1541d000-7373-11eb-95f8-13472b83a74a.png)

**Comment by ibuler** [comment]
好的，那么关闭 issue 了

**Comment by dengbin40** [comment]
> 好的，那么关闭 issue 了

jumpserver/redis:6-alpine  我现在是redis6版本，也还是无限等待

**Comment by omigo** [comment]
Redis 7.0.4 也是无限等待

# Server
redis_version:7.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d50f3e9745d9d82
redis_mode:standalone
os:Linux 3.10.0-1160.76.1.el7.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:8.3.1

**Comment by Shulong123** [comment]
2.14 版本，也有这个问题，redis 版本 5.0.6

**Comment by taoshanghu** [comment]
我有一样的问题，我的jumpserver版本2.28.8，使用的是官方提供的安装工具下载的指定docker 镜像版本，搜索了所有的日志没有celary_ansible.log文件，只有ansible.log 文件，日志是空的
