### ISSUE TITLE
master分支，资产导出功能不可用

### ISSUE THREAD

**Issue by leocd** [jumpserver/jumpserver#505]
master分支，点击资产导出无响应，使用chrome的开发者工具可以看到出现了500错误。
http://192.168.1.5:8000/jasset/asset/list/?export=true&idc=&group=&asset_type=&status=&keyword=&checkall=checkall&id=26&id=24&id=21&id=19&id=16&id=25&id=22&id=23&id=20&id=17&id=18&id=14&id=15&id=58&id=57&id=56&id=55&id=54&id=53&id=52
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
直接打开地址
IOError at /jasset/asset/list/
[Errno 2] No such file or directory: 'static/files/excels/cmdb_excel_2017_06_22_18_10.xlsx'
查看该目录确认xlsx未生成
权限的话jumpserver 755 static 755 files 755 excels 755，也试过全改成777，依然没有生成xlsx文件。
能否麻烦解决下这个问题呢？

**Comment by leocd** [comment]
……已解决，阿里云ecs，通过修复安全上下文解决了。

**Comment by Humhunter** [comment]
请问你是怎么解决的？
