### ISSUE TITLE
急速安装2.4.4升级2.5.0 mysql问题

### ISSUE THREAD

**Issue by mrpretext886** [jumpserver/jumpserver#5074]
更新提示 要求5.7及以上版本mysql，卸载mariadb安装mysql5.7 更新完成后登陆失败，提示联系管理员！

**Comment by mrpretext886** [comment]
登陆界面正常，输入账号密码后报错！

**Comment by enthanlee** [comment]
遇到同样的问题,已完成数据库升级.

**Comment by enthanlee** [comment]
Server error occur, contact administrator

**Comment by palkiller** [comment]
我也一样，将mariadb从5.5升级到10.3，还是提示需要5.7版本以上的mysql，恢复快照，安装mysql5.7，再把数据库升级，可以正常升级jms到2.5.1了，但是登陆页面进去之后报错，提示“Server error occur, contact administrator”，把jms卸载后，重新极速安装，这会儿core运行不起来了，残念...

**Comment by mrpretext886** [comment]
重新急速安装了，在原来版本导出的资源清单，导入到新版本失败，数据也回不去！！

**Comment by palkiller** [comment]
> 重新急速安装了，在原来版本导出的资源清单，导入到新版本失败，数据也回不去！！

数据库没备份吗？导出的资源清单跟导入模板的格式不同，需要手工调整一下

**Comment by mrpretext886** [comment]
我试试，谢谢~！！只注意到了账号模板，没注意资源也有模板！！

**Comment by ibuler** [comment]
关于 v2.5.0 版本 mariadb 不兼容问题，非常抱歉，依赖的一个库，文档中声明支持 MariaDB，发布新版本后发现不支持。，但版本已发布，不能回退。暂时只能通过mariadb 切换到MySQL 来解决，如果不想迁移到 mysql，可以等待一个版本，下个版本 升级到 Django 3.0，使用原生的库来支持 

依赖库文档说明 :https://django-mysql.readthedocs.io/en/latest/installation.html 

库作者的Issue: https://github.com/adamchainz/django-mysql/issues/342

**Comment by palkiller** [comment]
> 关于 v2.5.0 版本 mariadb 不兼容问题，非常抱歉，依赖的一个库，文档中声明支持 MariaDB，发布新版本后发现不支持。，但版本已发布，不能回退。暂时只能通过mariadb 切换到MySQL 来解决，如果不想迁移到 mysql，可以等待一个版本，下个版本 升级到 Django 3.0，使用原生的库来支持
> 
> 依赖库文档说明 :https://django-mysql.readthedocs.io/en/latest/installation.html
> 
> 库作者的Issue: [adamchainz/django-mysql#342](https://github.com/adamchainz/django-mysql/issues/342)

ibuler 大大，是不是2.5.1的upgrade.sh脚本已经修订过了？我重新恢复快照，再升级没提示需要mysql5.7，已经顺利升级完成，但是core启动报错 -_-b

**Comment by mrpretext886** [comment]
非常感谢

**Comment by mrpretext886** [comment]
2.5.1依旧需要mysql,再等等吧

**Comment by palkiller** [comment]
> 2.5.1依旧需要mysql,再等等吧

是的，升级的时候没提示，但是core启动的时候会有验证，连不上服务器，启动不了，郁闷了

**Comment by wojiushixiaobai** [comment]
[MariaDB5.5 迁移到 MySQL5.7 文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/mariadb-mysql/)

**Comment by mrpretext886** [comment]
> [MariaDB5.5 迁移到 MySQL5.7 文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/mariadb-mysql/)

非常感谢

**Comment by mrpretext886** [comment]
> > [MariaDB5.5 迁移到 MySQL5.7 文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/mariadb-mysql/)
> 
> 非常感谢
手动安装，替换MYSQL后，启动报  django.db.utils.OperationalError: (2006, "Access denied for user 'jumpserver'@'localhost' (using password: YES)")
使用脚本迁移，升级后登陆正常，但是无WEB终端

**Comment by mrpretext886** [comment]
![image](https://user-images.githubusercontent.com/63313310/100221268-664c4e80-2f53-11eb-8015-9138689fecc8.png)
![image](https://user-images.githubusercontent.com/63313310/100221294-6f3d2000-2f53-11eb-9034-5c146d6de48d.png)
![image](https://user-images.githubusercontent.com/63313310/100221226-5a608c80-2f53-11eb-97bd-8e4b757d88af.png)

**Comment by wojiushixiaobai** [comment]
右上角

**Comment by mrpretext886** [comment]
> 右上角

点进去了的，一直在加载状态，重启了服务依然无法现在资产 

![image](https://user-images.githubusercontent.com/63313310/100296288-bf08ff00-2fc6-11eb-9240-16a9a95dc011.png)

**Comment by mrpretext886** [comment]
> 右上角

彻底从新迁移升级了一遍，升级成功，正常使用，非常感谢！

**Comment by mrpretext886** [comment]
迁移升级成功

**Comment by qiyongxiao** [comment]
> 登陆界面正常，输入账号密码后报错！

得亏我在线下自己做了测试,从 2.2.2 迁移 2.5.0 发现无法启动,解决了 mysql 版本的问题,有遇到其他问题.看来我还是静待其他版本吧.等解决了账号登录后报错的问题我再升级吧
报错后我看了相关日志,内容如下:
```
  response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/authentication/views/login.py", line 88, in form_valid
    self.check_user_auth(decrypt_passwd=True)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 113, in check_user_auth
    elif user.password_has_expired:
  File "/opt/jumpserver/apps/users/models/user.py", line 120, in password_has_expired
    if self.is_local and self.password_expired_remain_days < 0:
  File "/opt/jumpserver/apps/users/models/user.py", line 115, in password_expired_remain_days
    date_remain = self.date_password_expired - timezone.now()
  File "/opt/jumpserver/apps/users/models/user.py", line 110, in date_password_expired
    days=int(interval))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
```

**Comment by mrpretext886** [comment]
> > 登陆界面正常，输入账号密码后报错！
> 
> 得亏我在线下自己做了测试,从 2.2.2 迁移 2.5.0 发现无法启动,解决了 mysql 版本的问题,有遇到其他问题.看来我还是静待其他版本吧.等解决了账号登录后报错的问题我再升级吧
> 报错后我看了相关日志,内容如下:
> 
> ```
>   response = get_response(request)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
>     return func(*args, **kwds)
>   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
>     return self.form_valid(form)
>   File "/opt/jumpserver/apps/authentication/views/login.py", line 88, in form_valid
>     self.check_user_auth(decrypt_passwd=True)
>   File "/opt/jumpserver/apps/authentication/mixins.py", line 113, in check_user_auth
>     elif user.password_has_expired:
>   File "/opt/jumpserver/apps/users/models/user.py", line 120, in password_has_expired
>     if self.is_local and self.password_expired_remain_days < 0:
>   File "/opt/jumpserver/apps/users/models/user.py", line 115, in password_expired_remain_days
>     date_remain = self.date_password_expired - timezone.now()
>   File "/opt/jumpserver/apps/users/models/user.py", line 110, in date_password_expired
>     days=int(interval))
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
> ```

官方给出的升级步骤是可行的，已成功升级

**Comment by aiaiduo** [comment]
> 关于 v2.5.0 版本 mariadb 不兼容问题，非常抱歉，依赖的一个库，文档中声明支持 MariaDB，发布新版本后发现不支持。，但版本已发布，不能回退。暂时只能通过mariadb 切换到MySQL 来解决，如果不想迁移到 mysql，可以等待一个版本，下个版本 升级到 Django 3.0，使用原生的库来支持
> 
> 依赖库文档说明 :https://django-mysql.readthedocs.io/en/latest/installation.html
> 
> 库作者的Issue: [adamchainz/django-mysql#342](https://github.com/adamchainz/django-mysql/issues/342)

这个现在最新的的V2.5.2版本解决了这个问题了吗？

**Comment by ibuler** [comment]
@aiaiduo v2.6解决了

**Comment by swq-github** [comment]
> [MariaDB5.5 迁移到 MySQL5.7 文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/mariadb-mysql/)

大兄弟给的文档会出现css乱掉的问题。这个什么情况

**Comment by swq-github** [comment]
> 迁移升级成功

迁移升级成功了?

**Comment by mrpretext886** [comment]
迁移正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月16日(周五) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [jumpserver/jumpserver] 急速安装2.4.4升级2.5.0 mysql问题 (#5074)




  
迁移升级成功
  
迁移升级成功了?
