### ISSUE TITLE
[Bug] v2.4.1升级到v2.5.0 管理界面下看不到资产

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#5075]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.4.1升级到v2.5.0 
**浏览器版本**

**Bug 描述**
v2.4.1升级到v2.5.0 后，管理界面下看不到资产，用户界面或者luna下没有问题。

**Bug 重现步骤(有截图更好)**
1.  
![图片](https://user-images.githubusercontent.com/4084548/99939044-24c97100-2da4-11eb-9d90-e36cb5b5d6f1.png)

2. 
![图片](https://user-images.githubusercontent.com/4084548/99939274-ad481180-2da4-11eb-8ce1-8360996a3156.png)

3.

**Comment by l-duan** [comment]
我也遇到了，这么严重的bug，太吓人了

**Comment by bigbird1985** [comment]
> 
> 
> 我也遇到了，是从2.3.0升级少2.5.1遇到的，这么严重的bug，太吓人了，好好，小心翼翼的回滚成功了；

是的，我测试升级了很多次，在管理界面，资产树的根目录自动生成了一个1的Default，原来0的Default根本不认。但是在用户界面，却是完全正常的，0的Default下资产也都能看到。

**Comment by bigbird1985** [comment]
2.4.1升级到2.4.4没有问题。

**Comment by bigbird1985** [comment]
> 
> 
> 我也遇到了，是从2.3.0升级少2.5.1遇到的，这么严重的bug，太吓人了，好好，小心翼翼的回滚成功了；

今天测试从2.4.4升级到2.5.2，还是一样的看不见资产，但是发现一个神操作，右击Default，选择删除，然后刷新页面，原来的资产就出现了。。。。。
但是每次重启jms，都会出现一个新的Default，每次都要删除下，好在平时没啥事不会去重启jms。。。

**Comment by bigbird1985** [comment]
@l-duan

**Comment by linux0x5c** [comment]
同样问题......厉害了啥数据看不到了

**Comment by wojiushixiaobai** [comment]
@bigbird1985 @l-duan @linux0x5c 
这个问题应该是之前手动改过Default根节点的名字或者创建异常的组织导致的；
问题上面 @bigbird1985  已经说明，手动在数据库里面把多余的 Defalut 处理即可

# 操作前请注意备份

**Comment by l-duan** [comment]
删除具体是哪一个库里呢，前端页面上删除了，不会删除库了的么？

**Comment by bigbird1985** [comment]
> 
> 
> 删除具体是哪一个库里呢，前端页面上删除了，不会删除库里的default么？

直接在web页面把新生成的Default根节点删除就行。

**Comment by linux0x5c** [comment]
我的问题不是这个default多个的问题  我是跨域前后端冲突的问题

**Comment by bigbird1985** [comment]
升级到2.5.3，问题解决了。 @l-duan
