### ISSUE TITLE
[Question]  v2.4.3 按照方法WEB去连接windows服务器，一直没有反应，无法登录

### ISSUE THREAD

**Issue by lucongyong** [jumpserver/jumpserver#5078]
**请描述您的问题.**
v2.4.3 按照方法WEB去连接windows服务器，一直没有反应，无法登录
![image](https://user-images.githubusercontent.com/32756178/99957760-2eae9c80-2dc3-11eb-882c-98c78feaa65c.png)

下发一直提示发送文本到SSH终端，我确认我的资产配置的是windows    rdp
![image](https://user-images.githubusercontent.com/32756178/99958319-2440d280-2dc4-11eb-9ace-9100c6a35384.png)

系统用户和管理用户都使用的是administrator
![image](https://user-images.githubusercontent.com/32756178/99958575-95808580-2dc4-11eb-9a12-169ec70a035a.png)
![image](https://user-images.githubusercontent.com/32756178/99958598-a204de00-2dc4-11eb-9004-778739dbb2ae.png)

**Comment by lucongyong** [comment]
开始截图中administrator  打错已经更正，但是故障依然存在

**Comment by lucongyong** [comment]
![image](https://user-images.githubusercontent.com/32756178/99984762-74ca2700-2de8-11eb-90e7-c1954107209c.png)

这是Guacamole报错

**Comment by ibuler** [comment]
Guacamole 终端不在线，去终端管理看看
