### ISSUE TITLE
[Feature] 命令记录无法选择性导出，只能导出所有。

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5080]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/10806595/99967438-d7b0c380-2dd2-11eb-890d-a64d8c009101.png)

**Comment by ibuler** [comment]
已知问题，导出所有，其实是导出搜索结果

**Comment by ibuler** [comment]
另外可能无法导出选中的内容，因为命令可能是从 ES 搜索出来的，无法根据 ID 导出
