### ISSUE TITLE
[Bug] 启动数据库网关失败no available domain     连接数据库报这个错是什么原因？

### ISSUE THREAD

**Issue by fency12** [jumpserver/jumpserver#5081]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.5.0 GPLv2

**浏览器版本**
![image](https://user-images.githubusercontent.com/19307432/100041690-cb654e80-2e44-11eb-9433-bc0ed4a5de52.png)

**Bug 描述**
数据库权限和账号分配都没问题，子账号已经能看到mysql应用了，但是连接的时候报错“”启动数据库网关失败no available domain“”

**Bug 重现步骤(有截图更好)**
1.  

2. 
3.

**Comment by LeeEirc** [comment]
数据库的网域设置是正常的吗？
![image](https://user-images.githubusercontent.com/32626707/100041315-0c109800-2e44-11eb-88da-ba1232f57c17.png)

**Comment by fency12** [comment]
![image](https://user-images.githubusercontent.com/19307432/100041445-4c701600-2e44-11eb-8664-1816b1486dad.png)
![image](https://user-images.githubusercontent.com/19307432/100041490-6a3d7b00-2e44-11eb-9433-905113a13801.png)

是正常的呀。且网域也不是必填项，不就是一个分类吗，跟这个有关系吗？

**Comment by LeeEirc** [comment]
如果配置了网域，会通过网域去连接。确保这个网域里的网关可用。

**Comment by fency12** [comment]
嗯，去掉网域确实可以了，但是不明白的是这个网域到底有啥用，他在创建的时候就是一个分类的感觉啊，我看了创建的时候根本就没有配置网关的选项，就是一个名字，请问这个网域到底有啥用？如图
![image](https://user-images.githubusercontent.com/19307432/100042688-f2248480-2e46-11eb-93d5-bb5cf49c4797.png)

**Comment by fency12** [comment]
![Uploading image.png…]()

**Comment by LeeEirc** [comment]
`网域功能是为了解决部分环境（如：混合云）无法直接连接而新增的功能，原理是通过网关服务器进行跳转登录。JMS => 网域网关 => 目标资产` 你需要进入详情，创建网关。
![image](https://user-images.githubusercontent.com/32626707/100042821-3a43a700-2e47-11eb-96f3-786521918009.png)

**Comment by fency12** [comment]
![image](https://user-images.githubusercontent.com/19307432/100043146-c48c0b00-2e47-11eb-8982-7adbb78373c7.png)
明白了，这个地方是可以点击创建的。这个太隐蔽了，建议优化下在创建的时候就创建网关，不然很难发现。谢谢！那就是如果都是直连的话就不需要设置网域了是吧？

**Comment by LeeEirc** [comment]
嗯，直接连接是不需要设置网域的

**Comment by fency12** [comment]
明白了，明白了开发者的用心，谢谢。还是建议优化下在创建网域的时候就创建网关，不然很难发现。
