### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#5089]
jumpserver 2.2.2

通过excel批量导入新用户的时候，用户导入成功，但用户不能及时收到邮件，需要点击用户管理页面右上角的刷新按钮，邮件才可以收到。

![图片](https://user-images.githubusercontent.com/63391681/100184573-c247b080-2f1c-11eb-8e33-8a630e8878e0.png)

**Comment by jym503558564** [comment]
@Allenzhang-92 无法复现该问题
