### ISSUE TITLE
[Bug] vim后操作卡顿

### ISSUE THREAD

**Issue by 1275788667** [jumpserver/jumpserver#5092]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.1

**浏览器版本**
chrome最新版

**Bug 描述**
服务器里面的vim开了彩色还有其他的插件  在jump能显示  但是操作很卡

**Bug 重现步骤(有截图更好)**
1.  
![X%HS72H2 QYPEK9 M~J5VD](https://user-images.githubusercontent.com/58962460/100188900-2e7ae200-2f26-11eb-8706-35e39662b7ea.png)

2.  ![Y6CWCZ)_6CFXNJW9@BO1VRV](https://user-images.githubusercontent.com/58962460/100188905-32a6ff80-2f26-11eb-8959-13f73725a766.png)

**Comment by ibuler** [comment]
是不是网络原因呢？

**Comment by 1275788667** [comment]
不是的  经测试 只有这种带颜色的会出现卡顿

**Comment by ibuler** [comment]
我觉得有可能是 xterm.js 引起的渲染问题

**Comment by ibuler** [comment]
F12后，检查 websocket的 收发速度来确定 是前端问题还是后端问题 

![image](https://user-images.githubusercontent.com/17382885/100823800-dbf27600-348f-11eb-9d10-8ee26a21a985.png)
