### ISSUE TITLE
[Question]获取系统资产配置信息问题

### ISSUE THREAD

**Issue by xiaozhiqi2000** [jumpserver/jumpserver#5094]
JumpServer 版本
2.4.0

浏览器版本
Chrome 85.0.4183.121（正式版本）

Bug 描述
![image](https://user-images.githubusercontent.com/16703381/100195825-e57d5a80-2f32-11eb-908d-b992d9d8b605.png)

Bug 重现步骤(有截图更好)

在资产列表中添加资产
web终端连接正常

**Comment by xiaozhiqi2000** [comment]
再次获取资产信息的时候出现的，web终端正常登录

**Comment by xiaozhiqi2000** [comment]
#### 运行很长时间才获取，
![image](https://user-images.githubusercontent.com/16703381/100197190-f29b4900-2f34-11eb-81ef-29bfb51502f4.png)

**Comment by xiaozhiqi2000** [comment]
### 获取windows的cpu和硬盘获取不到
![image](https://user-images.githubusercontent.com/16703381/100200641-df3eac80-2f39-11eb-8d81-103028c6d5c7.png)

**Comment by jym503558564** [comment]
@xiaozhiqi2000 可能是任务堆满了，现在问题还存在吗
