### ISSUE TITLE
ubuntu系统应该怎么安装

### ISSUE THREAD

**Issue by xianyacheng** [jumpserver/jumpserver#51]
gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.7 -c src/MD2.c -o build/temp.linux-x86_64-2.7/src/MD2.o

src/MD2.c:31:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

**Comment by leearic** [comment]
没安装 python-all-dev 这个软件包吧



leearic@126.com
 
发件人： xianyacheng
发送时间： 2016-01-29 10:22
收件人： ibuler/jumpserver
主题： [jumpserver] ubuntu系统应该怎么安装 (#51)
gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python27 -c src/MD2c -o build/templinux-x86_64-27/src/MD2o
src/MD2c:31:20: fatal error: Pythonh: No such file or directory
compilation terminated
error: command 'gcc' failed with exit status 1

**Comment by xianyacheng** [comment]
是没有安装那个软件包，安装完后是成功的，但是启动服务失败了
然后我网上查了ubuntu系统是没有这个 /etc/init.d/functions 文件，又应该如何应对，求破！！谢谢
root@SZX1000065443:/opt/jumpserver# ./service.sh start
./service.sh: line 12: /etc/init.d/functions: No such file or directory
Starting jumpsever service:manage.py not running
run_websocket.py not running
./service.sh: line 43: failure: command not found

**Comment by leearic** [comment]
我记得这个好像是用的node  你是不是没安装node呀...
其实我也是新手，我没安装过  仅仅看过介绍




leearic@126.com
 
发件人： xianyacheng
发送时间： 2016-01-29 10:52
收件人： ibuler/jumpserver
抄送： leearic
主题： Re: [jumpserver] ubuntu系统应该怎么安装 (#51)
是没有安装那个软件包，安装完后是成功的，但是启动服务失败了
然后我网上查了ubuntu系统是没有这个 /etc/init.d/functions 文件，又应该如何应对，求破！！谢谢
root@SZX1000065443:/opt/jumpserver# ./service.sh start
./service.sh: line 12: /etc/init.d/functions: No such file or directory
Starting jumpsever service:manage.py not running
run_websocket.py not running
./service.sh: line 43: failure: command not found

**Comment by xianyacheng** [comment]
@leearic 已经弄好了，按照说明文档
3）如果./service.sh start启动失败 
请进入jumpserver目录，手动运行 
python manage.py runserver 0.0.0.0:80 
python run_websocket.py

**Comment by liuzheng712** [comment]
解决的issue，关了啊
