### ISSUE TITLE
[0.4.0]创建用户出错

### ISSUE THREAD

**Issue by EndingCode** [jumpserver/jumpserver#510]
4.0版本跟着安装说明步骤搭建到2.6步时，创建用户出错，是否有解决方法？

![image](https://user-images.githubusercontent.com/29228445/27536079-25da4cac-5aa0-11e7-85ae-7336189e661f.png)

上面的问题解决了，问题又来了，创建好用户没有邮件，多创建几次出现对话框：
![image](https://user-images.githubusercontent.com/29228445/27550386-0a111fbe-5ad2-11e7-8800-7851ff8d94b8.png)
这是数据库的问题吗？

**Comment by EndingCode** [comment]
...好像说句粗口。。。除了celery用pip装到2.7的链接库，其他都要用装到python3的链接库。上面的报错要把DJango装到pip 9.0.1 from /usr/local/python3/lib/python3.6/site-packages (python 3.6)这个lib里

**Comment by ibuler** [comment]
这个是你python版本的问题，要使用python3.5+
