### ISSUE TITLE
[Bug] Docker-compose 2.4.4升级至2.5.1 Luna点击资产报错“请求的连接不存在。请先检查连接的名字再重试。”

### ISSUE THREAD

**Issue by deerjoe** [jumpserver/jumpserver#5101]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.1 

**浏览器版本**
Firefox 、Chrome 最新版本

**Bug 描述**
从2.4.4升级至2.5.1后，Luna点击资产报错“请求的连接不存在。请先检查连接的名字再重试。”

**Bug 重现步骤(有截图更好)**
1.  备份2.4.4数据库，执行 sed -i 's@CHARSET=utf8;@CHARSET=utf8 COLLATE=utf8_bin;@' /opt/jumpserver.sql操作
2. docker-compose up 后停止其他业务 仅保留jms_mysql容器，导入数据
3. 重启jms_core ，数据库migrate日志正常，各组件运行正常
4.点击luna资产，报错，请求的连接不存在。请先检查连接的名字再重试。

查看koko日志

`2020-11-25 16:21:48 [ERRO] POST http://core:8080/api/v1/terminal/terminals/status/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}`

**Comment by deerjoe** [comment]
需要到后台删除koko 和 Gua的终端后重新启动才正常。但是.env内的key并没有变过。

**Comment by wojiushixiaobai** [comment]
@deerjoe keys无法和之前的容器匹配，所以需要重新注册。这并不是bug
