### ISSUE TITLE
[Bug] 当授权的应用为空的前提下，点击更新会有bug提示

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5104]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.5.1

**浏览器版本**
chrome

**Bug 描述**
当授权的应用为空的前提下，在应用授权列表中，点击更新按钮会有不必要的提示。不为空不提示。虽然不影响使用。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/10806595/100300586-51160500-2fd1-11eb-807d-c42eb4a2d9e3.png)
![image](https://user-images.githubusercontent.com/10806595/100300778-b36f0580-2fd1-11eb-891d-82abf92b89d1.png)

**Comment by jym503558564** [comment]
新版本未发现该问题，请更新至新版进行测试使用。
