### ISSUE TITLE
分布式部署功能建议

### ISSUE THREAD

**Issue by qiyongxiao** [jumpserver/jumpserver#5107]
现在有一个多机房部署的需求。希望可以通过公司内的一个jumpserver可以连接多个机房的内网主机，不知道这个现在支不支持。如果支持，如何进行部署？
现在我们有3个jumpserver，登录服务器需要切换三个服务器，想把这个整合到一起，如何实现？

**Comment by clannon** [comment]
这个不叫分布式吧，跨机房统一管理服务器用网域，“资产管理”里“网域列表”里创建一个网域，再添加一个网关，这个网关就相当于一个跳板机了，不复杂。不知道现在官网上为啥没这些功能的使用说明了，可能太简单了……

**Comment by qiyongxiao** [comment]
> 这个不叫分布式吧，跨机房统一管理服务器用网域，“资产管理”里“网域列表”里创建一个网域，再添加一个网关，这个网关就相当于一个跳板机了，不复杂。不知道现在官网上为啥没这些功能的使用说明了，可能太简单了……
我找到这个功能了。要添加另外一个机房的数据库应用，可就不能这么做了吧

**Comment by clannon** [comment]
> > 我找到这个功能了。要添加另外一个机房的数据库应用，可就不能这么做了吧

应用的话不清楚了，我用的旧版本，还不能这么做，不过我一般都用nginx转发出来的
