### ISSUE TITLE
[Bug] web终端连接到服务器 很快就被断开 Connection closed 30秒内

### ISSUE THREAD

**Issue by umena337** [jumpserver/jumpserver#5110]
**JumpServer 版本(v1.5.9以下不再支持)**
Jumpserver2.3.0

**浏览器版本**
chrime  版本 86.0.4240.198（正式版本） （64 位）

**Bug 描述**
 web终端连接到服务器 很快就被断开 Connection closed 30秒内
连上很快就断开了

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44667665/100322721-a963fb80-2fff-11eb-94ec-ef0ef53538e9.png)
![image](https://user-images.githubusercontent.com/44667665/100322869-d6b0a980-2fff-11eb-867b-caf6fa6dec3f.png)
![image](https://user-images.githubusercontent.com/44667665/100322920-e9c37980-2fff-11eb-8f98-3657dcfaa47c.png)

2. 
3.

**Comment by umena337** [comment]
持续用date命令 也把我断开了
![image](https://user-images.githubusercontent.com/44667665/100323119-373fe680-3000-11eb-9418-d577ad244f97.png)

**Comment by umena337** [comment]
![Uploading image.png…]()

**Comment by umena337** [comment]
![image](https://user-images.githubusercontent.com/44667665/100323508-d8c73800-3000-11eb-8727-5a7f24881933.png)
./jmsctl.sh status 状态正常

**Comment by umena337** [comment]
重启过jumpserverle 
./jmsctl.sh restart 依然这样

**Comment by umena337** [comment]
cd /opt/jumpserver/logs
tail -999f jumpserver.log
》》》
django.db.utils.OperationalError: (2006, "Can't connect to MySQL server on '127.0.0.1' (111)")

**Comment by umena337** [comment]
会是哪里有问题呢

**Comment by umena337** [comment]
脚本部署的 过程也些改动 但是功能都能正常使用

**Comment by umena337** [comment]
数据库用的mysql5.6

**Comment by umena337** [comment]
![image](https://user-images.githubusercontent.com/44667665/100331440-1df06780-300b-11eb-9930-720013fdca59.png)

**Comment by umena337** [comment]
./jms restart
./jms status

![image](https://user-images.githubusercontent.com/44667665/100331450-234db200-300b-11eb-811a-7eb5b6c81b12.png)

**Comment by umena337** [comment]
一顿操作web终端 终于被我搞坏了
![image](https://user-images.githubusercontent.com/44667665/100332928-f5696d00-300c-11eb-83d0-c52912dbf0f6.png)

**Comment by wojiushixiaobai** [comment]
多层反向代理请自行解决 websocket
最后一个问题是无法连接 koko 组件
可以使用　./jmsctl.sh reset koko 解决
如果依旧无法解决
```
systemctl restart docker
docker restart jms_koko jms_guacamole
```

**Comment by LeeEirc** [comment]
终端连接需要依赖 websocket，中间负载需要自行解决websocket问题，另外如果存在断开的情况，请查看koko组件的日志。` docker logs -f jms_koko --tail=100` 如果不清楚哪一个环节存在问题，建议通过内网环境，直接ip的方式直接访问，看是否存在问题。 以上是解决思路，如有问题，再反馈。
