### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jackxun123** [jumpserver/jumpserver#5117]
**JumpServer 版本**
v2.5.1

**浏览器版本**
Chrome 版本 87.0.4280.66

**Bug 前提描述**
私钥无法使用，以下是检验步骤
密钥对分新，和旧两对
旧为2018年左右在生产环境使用的密钥对，私钥编码格式可能为BMR，1.4.8版本jumpserver可正常使用（使用coco）
新为在centos7.6机器上ssh-keygen -t rsa生成的新密钥对

**Bug 验证步骤**
新密钥对与旧密钥对的公钥一起放在机器上（root账户）
私钥用来上传堡垒机的系统用户和管理用户做测试

1.新旧密钥，ssh -i和管理用户可连接与获取硬件数据，均通过
2.系统用户添加新私钥，通过，可连接资产
2.系统用户添加旧私钥，未通过，不可连接资产

**Bug 排查过程**
通过koko的Debug模式看到在解析旧私钥时报错为
parse private key error: asn1: structure error: superfluous leading zeros in length
通过
[可能是golang的问题](https://github.com/golang/go/issues/14145)
[证书格式的解释](https://binbean.github.io/post/%E8%AF%81%E4%B9%A6certificate/)

**Bug 尝试解决过程**
尝试去转换旧私钥的编码格式，例如转换成DER编码格式，但jumpserver提示无法添加此编码格式密钥

**Bug 个人总结**
管理用户和ssh -i可正常连接代表旧密钥对本身是没问题的
通过koko和coco组件的对比，问题只会是出在koko上

**Comment by Jackxun123** [comment]
[go关于ssh的源码报错](https://tibcosoftware.github.io/tci-flogo/wi-runtime/v1.2.0/src/encoding/asn1/asn1.go.html)
![image](https://user-images.githubusercontent.com/33611532/100603258-c79f6380-333f-11eb-89cc-b63fa5c093ad.png)

**Comment by ibuler** [comment]
这的确是 golang 对这个格式密钥不支持导致的，之前遇到过这个问题，发现暂时无法解决

**Comment by Jackxun123** [comment]
> 这的确是 golang 对这个格式密钥不支持导致的，之前遇到过这个问题，发现暂时无法解决

多谢回复！
