### ISSUE TITLE
[Bug] 内网环境ip访问正常，将jumpserver穿透后web终端功能异常connect error

### ISSUE THREAD

**Issue by umena337** [jumpserver/jumpserver#5120]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.5.1
docker all 部署

**浏览器版本**

**Bug 描述**
内网环境，通过ip访问，所有功能正常
通过frp将jumpserver穿透后
通过域名访问，界面都正常
web终端进入服务器就异常
Connection error
Connection closed

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/44667665/100425194-b9481200-30c9-11eb-9e3e-87b26d1793cb.png)

1.  
2. 
3.

**Comment by umena337** [comment]
Request URL: ws:// 的原因吗

**Comment by umena337** [comment]
不是http类型

**Comment by umena337** [comment]
猜测是websocker的问题 ws://
逻辑上来将堡垒机就是要穿透出来使用把
把内网环境通过堡垒机，在外网能访问

**Comment by umena337** [comment]
Error during WebSocket handshake: Unexpected response code: 404

**Comment by umena337** [comment]
Request URL: ws://xxxxxxxxxxxxxxx/koko/ws/?target_id=81b6e72

**Comment by wojiushixiaobai** [comment]
自行处理 websocket

**Comment by CoderFreeMan** [comment]
遇见同样的问题，最终是如何解决的？
![301616336900_ pic_hd](https://user-images.githubusercontent.com/30991289/111908613-d3e93100-8a94-11eb-9dea-b77198352a43.jpg)
