### ISSUE TITLE
增加调用本地第三方客户端的支持

### ISSUE THREAD

**Issue by xymsayly** [jumpserver/jumpserver#5128]
**请描述您的需求或者改进建议.**
Jumpserver是否会考虑支持本地第三方客户端工具的调用呢，如xshel，xftp，navicate等，同时可以对这些客户端工具记录日志和录屏，有时候web端的体验不是很好，如果有这种第三方客户端的选择，可能会好不少

**Comment by wojiushixiaobai** [comment]
linux ssh:
```
ssh username@jumpserver_ip -p2222
```
windows xshell:
```
ssh username@jumpserver_ip 2222
```

**Comment by ibuler** [comment]
浏览器插件，得适配 mac 和 windows，xshell, sftp 应该是可以的，navicat 应该是不行的

**Comment by ibuler** [comment]
这里也希望有经验的朋友贡献一下

**Comment by wajika** [comment]
@wojiushixiaobai 
![image](https://user-images.githubusercontent.com/17058349/115131933-7a8e0680-a02e-11eb-83c3-315d73cd9250.png)
jumpserver怎么设置跳转到实际目录？

![image](https://user-images.githubusercontent.com/17058349/115131941-985b6b80-a02e-11eb-92b7-037e7209652d.png)
另外web上也可以设置跳转到当前所在目录吗？不然的话需要一层层进入 （另外怎么给 根路径下所有目录的访问权限，就是不限定具体可以访问哪个目录）
