### ISSUE TITLE
[Feature] 高危命令通知备注里的内容

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5129]
**请描述您的需求或者改进建议.**
jms命令过滤可以写备注，建议官方发送高危命令告警邮件时，将备注里的内容也发送邮件，备注里可以管理员自定义内容比如：此命令需要联系某某某申请执行权限或者一些说明：如果需要执行成功需要什么格式就可以执行成功的说明

**Comment by ibuler** [comment]
收到

**Comment by ryswork1993** [comment]
![image](https://user-images.githubusercontent.com/44529247/147816691-e9432026-284a-4c9b-9e10-f4381571ffe0.png)
希望高危命令告警的时候也能发送备注里的内容

**Comment by ibuler** [comment]
安排
