### ISSUE TITLE
是否打算支持2fa?

### ISSUE THREAD

**Issue by g4zhuj** [jumpserver/jumpserver#513]
0.4登陆添加了验证码,提高了登陆安全性,但相对来说验证码还是不够安全,这里是否有打算使用2fa. 使用google authenticator或者身份宝等基于TOTP(Time-Based One-Time Password)的动态密码生成器提高登陆安全性?

**Comment by ibuler** [comment]
打算支持，最近调研LDAP，先加入LDAP再考虑 2fa

**Comment by ibuler** [comment]
#527
