### ISSUE TITLE
[Feature] 开启ldap后，登陆界面“忘记密码”链接点击后提示“正在使用其他认证服务器，请联系管理员”

### ISSUE THREAD

**Issue by dingpamaoo** [jumpserver/jumpserver#5142]
目前使用的是2.4.4版本。
开启ldap后，登陆界面“忘记密码”链接点击后提示“正在使用其他认证服务器，请联系管理员”……
我在项目里搜索了一下，这个好像是9月30号改的。
如果这个是新的改动，而不是bug的话，那么使用数据库认证的用户也同样点不了链接了。
是否能够加个开关，允许用户自行点击登录页面的“忘记密码”来修改密码？

另外，我发现/core/auth/password/forget地址仍然可以使用，于是发给同事让他自己去改了😂

**Comment by ibuler** [comment]
这个提示确实存在迷惑，也存在设计上的问题

**Comment by ibuler** [comment]
正在计划优化这里

**Comment by jym503558564** [comment]
@dingpamaoo 在最新版本中v2.8.1，我们优化了，可自定义忘记密码链接。可升级至最新版本进行体验。
