### ISSUE TITLE
[Question]V1.5.9 修改文件后需要重启jumpserver才能生效

### ISSUE THREAD

**Issue by star-jupiter** [jumpserver/jumpserver#5145]
**请描述您的问题.**
1.5.9版本，更改apps下的不论是templates里的html还是更改模块中的.py文件，都要重启服务以后才能生效
同时还有个1.5.7的版本，改完代码以后保存就直接在页面端生效了，是改动了什么配置文件吗，1.5.9版本怎么修改配置文件
能让改动代码后不重启服务生效，例如修改html文件，并不是更改models，需要执行manage.py文件的那些内容

**Comment by ibuler** [comment]
开启及debug模式
