### ISSUE TITLE
[Feature]用户锁死后，能否在管理员界面增加一个“解锁”的操作按钮

### ISSUE THREAD

**Issue by xiaochaowu** [jumpserver/jumpserver#5148]
**请描述您的需求或者改进建议.**
https://docs.jumpserver.org/zh/master/faq/core/
用户频繁密码错误被锁，这里的操作过于复杂，需要命令行，请问可以在管理员界面增加一个“解锁”的操作按钮吗？谢谢！

**Comment by ibuler** [comment]
用户详情中是有的，可以去详情中解锁
