### ISSUE TITLE
[Feature] 用户的操作录像，可否只auditor角色的用户能看到，admin用户不能看到 

### ISSUE THREAD

**Issue by xiaochaowu** [jumpserver/jumpserver#5149]
**请描述您的需求或者改进建议.**
现在管理员登录，也能看到操作录像，但是希望有auditor的角色，只有这个角色的用户才能看到操作录像，管理员不可以。
谢谢！

**Comment by ibuler** [comment]
现在设计上是 管理员权限 包含 审计员，审计员权限 包含 用户，贸然去改变这个也不太合适，等待将来推出 自定义的角色
