### ISSUE TITLE
[Question] koko 运行go vet 和go test 都跑不通。

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5150]
下面是我流水线下的截图，跑不通。虽然说不管不碍事。
![image](https://user-images.githubusercontent.com/10806595/100818653-8add8480-3485-11eb-86bc-1ac6b3f0dd76.png)

![image](https://user-images.githubusercontent.com/10806595/100818795-d3953d80-3485-11eb-94e1-2be062554706.png)

**Comment by LeeEirc** [comment]
@bingws 感谢指正，Koko代码有重构，test部分未能及时更新。

**Comment by bingws** [comment]
@LeeEirc 加微信，我的微信号：bingws
