### ISSUE TITLE
[Help Wanted]

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#5151]
欢迎有能力有时间的朋友帮助 JumpServer，把需要的一些功能列在下面了

- [ ] 浏览器拉起 本地客户端，自动登录堡垒机和连接 sftp https://github.com/jumpserver/jumpserver/issues/5128

**Comment by bingws** [comment]
添加个资产监控？集成prometheus或grafana?

**Comment by xyziven** [comment]
web terminal支持交互登录（目标资产在操作系统层面启用MFA的场景）：
$ ssh mfatest@192.168.1.49
Password:
**Verification code:**

**Comment by bingws** [comment]
- [ ] LDAP用户组，支持同步。

**Comment by bingws** [comment]
- [ ] webssh添加lrzsz支持。

**Comment by BaiJiangJie** [comment]
最新版本已支持：
1. webssh添加lrzsz支持
2. 浏览器拉起 本地客户端，自动登录堡垒机；
