### ISSUE TITLE
[Bug] xshell登录jumpserver挂着，时间长后输入任何字符都需要按键盘两次才能输入成功

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5158]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.2

**浏览器版本**

**Bug 描述**
我上午10点登录jumpserver后就一直没退出jumpserver，然后下午16点左右打开xshell输入任何字符都需要按两次键盘才能输入成功，已经排除网络问题，重新退出jumpserver重新登录就恢复正常
不知道是不是普遍有这种问题，请官方也测试一下
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
@ryswork1993 使用最新的版本试一下？

**Comment by jym503558564** [comment]
@ryswork1993 无法复现
