### ISSUE TITLE
[0.3]请问0.3版本哪个分支是最新的？

### ISSUE THREAD

**Issue by rotmond** [jumpserver/jumpserver#516]
如题，之前下载了 tag 0.3.2对应的版本，后来发现有个bug是在之后修复的，现在可以用的0.3版本最新的是master分支下的？

**Comment by hellorocky** [comment]
master是0.3.2, tag0.3.2分支好像是0.3.1

**Comment by rotmond** [comment]
好的，我更新试试。

**Comment by hellorocky** [comment]
建议使用0.4
