### ISSUE TITLE
[Bug] 自动推送系统用户失效

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#5162]
**请描述您的问题.**
jms版本：v2.5.2
1. 创建了一个自动推送的系统用户，并授权给了用户test，然后jms会自动推送test到目标主机上。
2. 在主机上，通过`userdel -rf test`命令删除了test用户，然后从jms上面删除掉第一步创建的系统用户和授权规则。
3. 重复第一步操作，会发现，jms并没有重新推送test用户。
4. 重启jms，重复第一步操作，发现jms自动推送了test用户。

所以我想问一下自动推送的机制，我一开始认为，自动推送应该是每次授权时都尝试推送，或者是每次授权时，先检查目标资产上是否已有该用户，若没有则推送。
但是从上面的实验结果来看，jms仿佛是会记录推送的历史，如果推送过，后面再授权时，则不会再推送，是这样么？

**Comment by ibuler** [comment]
每次授权都推送会带来比较大的工作量，在资产少的时候还行，当资产超过 1w，推送一次可能超过 几十 分钟，这样会带来灾难的后果，所以 推送是基于推送历史推送的，如果推送过，就不再推送了

**Comment by rty813** [comment]
明白了。谢谢
