### ISSUE TITLE
[Feature] 在线会话界面点中断之后能不能自动刷新在线会话列表

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5167]
**请描述您的需求或者改进建议.**
在线会话界面点中断之后能不能立即自动刷新在线会话列表

**Comment by ibuler** [comment]
中断后是生成一个终端任务，koko 同步心跳的时候，才会处理任务，所以不是实时的。

设计之初考虑的是分布式部署，koko 能访问 core 的网络，但是 core 无法直接访问 koko 的，所以造成了这个问题
