### ISSUE TITLE
[0.4]用户，管理用户和系统用户的区别

### ISSUE THREAD

**Issue by iwannarock** [jumpserver/jumpserver#517]
如题，请问一下这三者的区别是什么？

**Comment by hellorocky** [comment]
用户是jumpserver给公司开发人员创建的账户,一般用来登录堡垒机,也可以登录网页版的jumpserver,(注意这个用户不是Linux的用户),堡垒机要用管理用户去资产(受堡垒机管理的Linux服务器)上创建普通用户,管理用户一般来说是root或者具有sudo NOPASSWD权限的用户,管理用户在资产上创建的普通用户就是系统用户,授权的动作就是把系统用户授权给jumpserver的用户.我是理解的,刚才说的感觉有点乱, 不知道你理解了没有,举个实际例子,  我叫Rocky, 管理员在jumpserver上给我创建了一个叫Rocky的用户,这是用户, 然后管理员用A机器上的root账户创建了一个work的普通用户, 那个root就是管理用户, work就是一个系统用户,管理员可以把那个work授权给Rocky账户.

**Comment by iwannarock** [comment]
非常感谢，终于理解了，最近看0.4的代码，这部分有点迷糊了..

**Comment by hellorocky** [comment]
嗯嗯,有问题一起交流,最近我们公司也打算往0.4迁移, 我在调研呢

**Comment by ibuler** [comment]
0.4版本bug依然存在，如果遇到问题，请提Issue，或修复后PR上来，感谢
