### ISSUE TITLE
[Question] v2.5.2连centos vnc用一会就断线

### ISSUE THREAD

**Issue by WeiqiuLiu** [jumpserver/jumpserver#5174]
CentOS Linux release 7.9.2009
jumpserver v2.5.2 一键安装

创建centos资产配置vnc，连接后使用不到1分钟就报连接出错。

我用其他软件vnc-viewer连centos正常使用，不会断开。

guacamole的日志在哪里看，我在容器内外都没有找到合适的日志。

![image](https://user-images.githubusercontent.com/31680027/101270723-d7db9680-37b6-11eb-9f30-7e5890436209.png)

**Comment by wojiushixiaobai** [comment]
@WeiqiuLiu 群里联系我远程看下

**Comment by ryswork1993** [comment]
是不是和交换机一分钟无法输入一个毛病
