### ISSUE TITLE
luna设置1920*1080， 但是全屏模式分辨率模糊，达不到1920*1080

### ISSUE THREAD

**Issue by ewinlu** [jumpserver/jumpserver#5179]
问题：全屏分辨率ide例如pycharm，看代码字体模糊
前端设置分辨率luna设置分辨率1920*1080，但是全屏的时候，实际查看后端的虚机他的分辨率只有1920*768，具体如图
![image](https://user-images.githubusercontent.com/50916123/101429562-31ba9880-393e-11eb-890c-928fa17f6b5c.png)
![image](https://user-images.githubusercontent.com/50916123/101432116-40f01500-3943-11eb-84e8-1c4d52abe444.png)

但是直接通过微软的mstsc去连接的话，查看虚机的分辨率却又可以达到1920*1080，所以证明虚机是可以支持1920*1080的分辨率的，是guamole协议无法支持1920*1080的分辨率吗？

有什么方法可以优化这个全屏分辨率问题吗？

**Comment by ibuler** [comment]
可能是之前版本存在的一个小bug, 后来修复了

![image](https://user-images.githubusercontent.com/17382885/104153525-82318400-541d-11eb-8248-b2afe6c84a0a.png)

**Comment by ibuler** [comment]
如果依然存在问题，请重新打开 issue
