### ISSUE TITLE
版本0.3.2.创建用户选择发送邮件，系统会卡死。

### ISSUE THREAD

**Issue by Ishelp** [jumpserver/jumpserver#518]
求助：版本0.3.2.创建用户选择，发送邮件，系统会卡死。邮箱用的163的。选择不发送邮件来创建用户则没问题，会是什么原因呢。本地环境：centos7.2  python2.7。

**Comment by hellorocky** [comment]
看看日志有没有什么报错

**Comment by zhusas** [comment]
把jumpserver.cong里面的修改为就好了
email_use_tls = True
email_use_ssl = True

**Comment by Ishelp** [comment]
已解决

**Comment by qianghong000** [comment]
我也有这个问题，怎么解决的呢
