### ISSUE TITLE
[Question] guacamole正常注册后在web终端无法连接windows.

### ISSUE THREAD

**Issue by wuchuwei** [jumpserver/jumpserver#5181]
**请描述您的问题.**
/guacamole/api/session/ext/jumpserver/asset/add 请求504 Gateway Time-out
/guacamole/api/tokens 请求504 Gateway Time-out 或者502.
在guacamole 安装机器上catalina日志出现
“
appears to have started a thread named [Thread-6] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
”

**Comment by wuchuwei** [comment]
tomcat的server.xml文件中
<Connector port="8081" protocol="HTTP/1.1"
               connectionTimeout="20000"
                redirectPort="8443" />
这个8443端口是不在监听的。server.xml 的8443是注释的。
guacd启动正常监听4822
curl测试了一下8081无任何响应直到超时。

**Comment by wojiushixiaobai** [comment]
请使用docker镜像启动

**Comment by wuchuwei** [comment]
docker也试过。



> 请使用docker镜像启动

**Comment by ibuler** [comment]
没有复现，如果依然存在问题，请重新打开 issue
