### ISSUE TITLE
[Bug] xshell终端上输入g出来的排序是按照节点里的资产数量排序？

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5185]
**请描述您的需求或者改进建议.**
xshell终端上输入g出来的排序是按照节点里的资产数量排序？
![image](https://user-images.githubusercontent.com/44529247/101455466-9a6d3980-396d-11eb-913d-3e47dac29c1b.png)
![image](https://user-images.githubusercontent.com/44529247/101455498-a527ce80-396d-11eb-9ce0-956978bf86a8.png)

**Comment by LeeEirc** [comment]
将在v2.8.0版本中，相同父节点，子节点将按照节点名称排序。
![image](https://user-images.githubusercontent.com/32626707/106432890-53ea1600-64aa-11eb-83de-1bae63c35a0e.png)

**Comment by jym503558564** [comment]
@ryswork1993 新版本将优化，请持续关注我们后续版本发布情况。
