### ISSUE TITLE
在web terminal 中查看大一点的文件就会中断

### ISSUE THREAD

**Issue by imaoxian** [jumpserver/jumpserver#519]
在web terminal 中输出大一点的文件就会中断
例如：`cat /opt/tomcat/logs/cataline.out`
很快就中断了
提示：`Connection Reset By Peer`

版本：0.3.2
如何解决

**Comment by xm-y** [comment]
我是直接连接就报此错误  ```Connection Reset By Peer```

**Comment by ibuler** [comment]
@xm-y  #568
