### ISSUE TITLE
在centos6下使用 docker-compose up安装提示版本不对

### ISSUE THREAD

**Issue by zhengdazhi** [jumpserver/jumpserver#520]
ERROR: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.10.0 or greater.

**Comment by iwannarock** [comment]
docker版本号低了，可以下载get.docker.com的脚本来执行安装最新版本的docker

**Comment by ibuler** [comment]
centos6已经不支持高版本docker了，使用centos7或者ubuntu

**Comment by zhengdazhi** [comment]
必须使用 docker 来启动这个项目吗？能不能直接在centos6上面安装python3 和安装相应的rpm包，然后执行 Dockerfile 里面的命令直接启动 compose ？

**Comment by zhengdazhi** [comment]
centos7 目前还用不习惯

**Comment by iwannarock** [comment]
可以不用docker的，参见docs/install.md文件来部署。
