### ISSUE TITLE
Web终端无法连接mysql8

### ISSUE THREAD

**Issue by xiaoyuit** [jumpserver/jumpserver#5202]
Web终端连接mysql8，提示如下错误：
`开始连接数据库mysql://192.168.2.13:3306/zgqt 0.0
Connect database 192.168.2.13 error: start local pty err: fork/exec /usr/bin/mysql: Setctty set but Ctty not valid in child
Connection closed`
请问，这个可能是哪里出问题了，还是目前不支持mysql8的连接？

**Comment by wojiushixiaobai** [comment]
@xiaoyuit 已修复，请重新更新下 koko 镜像即可

**Comment by xiaoyuit** [comment]
非常感谢，请问我是极速安装脚本安装的环境，需要怎样更新 koko 镜像？
