### ISSUE TITLE
[Bug] Token正確但Web端連不上kubernetes

### ISSUE THREAD

**Issue by Yapcheekian** [jumpserver/jumpserver#5203]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.3

**浏览器版本**
Chrome 87.0.4280

**Bug 描述**
輸入正確的token，但koko連不上谷歌雲kubernetes。
![jump](https://user-images.githubusercontent.com/44357487/101709135-dc12f700-3ac9-11eb-88ab-9556cb044473.png)

**Comment by Yapcheekian** [comment]
KoKo组件是正常部署

**Comment by LeeEirc** [comment]
@Yapcheekian 用docker部署试一下呢？

**Comment by Yapcheekian** [comment]
壓縮檔的init-kubectl.sh file permission錯了。要 chmod 755。
