### ISSUE TITLE
0.3.2 添加用户时未给用户添加密码

### ISSUE THREAD

**Issue by movekj** [jumpserver/jumpserver#521]
0.3.2版的 juser/user_api.py中的server_add_user方法只添加了用户，并没有给用户添加密码。难道是我用的代码版本有问题
我使用的commit号: bb7a3ea05385a49972e4d4e18b4f14851cc239a2
def server_add_user(username, ssh_key_pwd=''):
    """
    add a system user in jumpserver
    在jumpserver服务器上添加一个用户
    """
    bash("useradd -s '%s' '%s'" % (os.path.join(BASE_DIR, 'init.sh'), username))
    gen_ssh_key(username, ssh_key_pwd)

**Comment by hellorocky** [comment]
用key登陆机器, 为什么要设置密码?

**Comment by qils** [comment]
添加用户时， 有一个随机生成的16位字符的密码， 这个密码会在用户填加完后以邮件的方式发出来， 这个密码是用来登录web界面的， 另外也会在堡垒机服务器上创建一个普通的系统用户， 这个用户只能通过秘钥登录， 而且密钥是有密码的， 也会在邮件中发出来的， 可用在登录堡垒机服务器时（用XSHELL）导入密钥， 会提示输入密钥密码，正确后就能登录堡垒机服务器

**Comment by ibuler** [comment]
使用的 秘钥登录
