### ISSUE TITLE
[Bug] Windows会话超时重新连接操作无效

### ISSUE THREAD

**Issue by Andyguo5891** [jumpserver/jumpserver#5214]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.3

**浏览器版本**
Chrome  87.0.4280.88

**Bug 描述**
Windows会话超时后，点击重新连接菜单，无效，查看报错，详情见截图

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/101779677-8aea1e00-3b30-11eb-8308-3f971cd5394f.png)

**Comment by wojiushixiaobai** [comment]
@Andyguo5891  使用了网域功能？

**Comment by mynameisshiy** [comment]
> @Andyguo5891 使用了网域功能？

我也有同样的问题，使用了网域
