### ISSUE TITLE
[Bug] 资产列表里面为空，但有资产。而且无法删除和新增

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#5215]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.5.3 GPLv2.

**浏览器版本**
 chrome 87.0.4280.88

**Bug 描述**
资产管理--系统用户--资产列表
资产列表里面为空，但有资产。而且无法删除和新增

**Bug 重现步骤(有截图更好)**
![jumpserver-bug](https://user-images.githubusercontent.com/28751302/101795442-e02f2b00-3b42-11eb-9f5a-b5ad79f9b39b.gif)

**Comment by ibuler** [comment]
v2.6 之前版本上面的 tab 描述存在误解，那其实是个账号列表，并非资产列表(v2.6已解决)，既然是动态系统用户，名称是随着用户改变的，这个系统用户如果关联了用户，这里就会有数据，

动态系统用户:
系统用户 - 资产 - 用户 生成一条账号记录

普通系统用户:
系统 - 资产 就是一条账号记录


v2.6 已处理了这个问题

![image](https://user-images.githubusercontent.com/17382885/104151776-d0905400-5418-11eb-8d68-6d3103d39729.png)
