### ISSUE TITLE
web terminal 不能登录——Connection Reset By Peer

### ISSUE THREAD

**Issue by ansn001** [jumpserver/jumpserver#522]
使用的是0.3.2版本

![image](https://user-images.githubusercontent.com/6737296/27944065-c5aefe20-6316-11e7-89aa-a7a32f6e9914.png)

按常见问题的试了一下，都没有解决
把 /etc/sudoers的注释掉，把权限的删除掉，资产没有中文

![image](https://user-images.githubusercontent.com/6737296/27944109-0f99619c-6317-11e7-822b-ded592efea5b.png)
exec客户端是正常的。

**Comment by yangzi123456** [comment]
我用的是0.3.1版本，也出现了同样的问题。exec端可以使用，web terminal会出现同样peers的问题

**Comment by ooppwwqq0** [comment]
### 总结一下关于Connection Reset By Peer的问题出现原因以及解决办法

### 出现报错会有两种情况

* Connection Reset By Peer
* Connecting...Connection Reset By Peer

### Connection Reset By Peer 出现原因及解决办法

* 使用的是0.3.2版本的代码（本身代码有bug）；
* 并且直接访问的jumpserver端口，没有nginx代理；
* 解决办法-->将代码升级到master分支即可。

### Connecting...Connection Reset By Peer 出现原因及解决办法

* 使用nginx代理了jumpserver并且使用的是http代理；
* 代码版本无论是0.3.2还是master都会出现此问题；
* 解决办法-->http代理修改成tcp代理；
* nginx 1.9.x版本以上，编译时使用--with-stream参数可以支持tcp代理；
* 缺点是使用tcp代理之后无法配置server_name；
* 以下内容加到http{}外。

``` bash
stream {
    upstream backend{
        hash $remote_addr consistent;
        server 127.0.0.1:8000 weight=10;
    }

    server{
        listen 80;
        proxy_connect_timeout 20s;
        proxy_timeout 5m;
        proxy_pass backend;
    }
}
```

### 是否有其他情况造成此类问题没有测试过

**Comment by ibuler** [comment]
same with #568

**Comment by primexiao** [comment]
0.3.2，按下面配置nginx解决：
https://github.com/jumpserver/jumpserver/wiki/Nginx-Websocket-Proxy
