### ISSUE TITLE
web terminal Connection Reset By Peer 解决办法

### ISSUE THREAD

**Issue by kys1230** [jumpserver/jumpserver#523]
基于 0.3.2 版本 使用 web terminal 会出现 "Connection Reset By Peer" 错误. 原因出在 run_server.py 中
 WebTerminalHandler 类下的 on_message 方法中
1. 
    self.termlog.write(jsondata)  # 这里 jsondata 是通过 json.loads 转换的字典, 而 wirte 方法需要接受一个字符串.
    修改为: self.termlog.write(message)  # 因为 jsondata 就是通过 json.loads(message) 得到的, 这里直接将它替换为 message 即可.
2. 
    self.channel.resize_pty # 方法需要宽高两个参数为int, 而当前获取的值是字符串

整体修改如下: 
```
    if 'resize' in jsondata.get('data'):
-        self.termlog.write(jsondata)
+       self.termlog.write(message)
        self.channel.resize_pty(
-           jsondata.get('data').get('resize').get('cols', 80),
-           jsondata.get('data').get('resize').get('rows', 24)
+          80 if not jsondata.get('data').get('resize').get('cols', 80).isdigit() \
+              else int(jsondata.get('data').get('resize').get('cols'), 80),
+          24 if not jsondata.get('data').get('resize').get('rows', 24).isdigit() \
+              else int(jsondata.get('data').get('resize').get('rows', 24))
            )

```
我的环境里修改这些以后 web terminal 就可以连接了. 大家试试吧.

**Comment by yangzi123456** [comment]
我的版本是V0.3.1，按照版主说的做了修改，但是还是出现同样的问题Connection Reset By Peer

**Comment by calistochen** [comment]
我的也是

**Comment by kys1230** [comment]
我的代码是按照 tag 0.3.2 做的修改, 每个版本的代码可能略微不同.

**Comment by ibuler** [comment]
same with #568
