### ISSUE TITLE
[Bug] 资产为网络设备时，通过ssh、xshell等工具会出现终端卡死

### ISSUE THREAD

**Issue by chinazzb** [jumpserver/jumpserver#5234]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.5.2 

**浏览器版本**

**Bug 描述**
1、通过xshell、openssh 原生等工具，链接网络设备资产时，当终端不活跃一定时间(2-3分钟)，会导致终端卡死(这个不是网络设备发出中断，我这边交换机设置是10分钟)。
2、当到达10分钟后，终端跳回jumpserver首页，但键盘输入的键都要按2次才能生效！！！
3、jumpserver 浏览器，web终端则不会出现这类情况。 （2020-12-15 发现有时也会出现这类情况）

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
能稳定复现吗?

**Comment by chinazzb** [comment]
可以，具体查看如下gif图，注意右下角。
![jumpserver-network](https://user-images.githubusercontent.com/28751302/104265101-d5f8a780-54c7-11eb-8e77-b0ec343a65a6.gif)
我一致在敲键盘，但是终端还是没有反应。

**Comment by LeeEirc** [comment]
@chinazzb 加我q 2970298425 远程看下。

**Comment by chinazzb** [comment]
version:2.6.2
