### ISSUE TITLE
web terminal支持交互登录

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5235]
web terminal支持交互登录（目标资产在操作系统层面启用MFA的场景）：
$ ssh mfatest@192.168.1.49
Password:
**Verification code:**

_Originally posted by @xyziven in https://github.com/jumpserver/jumpserver/issues/5151#issuecomment-743974274_

**Comment by ibuler** [comment]
这个是需要考虑优化的地方

**Comment by LeeEirc** [comment]
v2.13.0 将支持开启 MFA 登录的资产。
