### ISSUE TITLE
启用https时，如何配置websocket，能使用web登录服务器，版本0.3.2

### ISSUE THREAD

**Issue by dianshen** [jumpserver/jumpserver#524]
我按照文章：https://github.com/jumpserver/jumpserver/blob/master/docs/nginx-with-ssl-configuration.md配置了nginx，但是web登录无法使用：
Connecting...Connection Reset By Peer

文章里提到了websocket默认监听tcp3000端口，但是在jumpserver上用netstat -lntp没见到有监听3000端口的进程，版本0.3.2的websocket现在是如何工作的？我改怎么配置nginx和jumpserver，使用https时可以使用web登录了？

**Comment by xm-y** [comment]
我也是！

**Comment by zhusas** [comment]
我在浏览器里面开发者工具发现url在跳转到/login的时候，需要访问一下80端口，nginx里面设置为非80端口都不行，我也是这个问题

**Comment by yangzi123456** [comment]
我用的版本是0.3.1，我没有配置nginx也同样的出现了connection Reset by peers。尝试了其他的各种方法，貌似没有用

**Comment by ooppwwqq0** [comment]
### 总结一下关于Connection Reset By Peer的问题出现原因以及解决办法

### 出现报错会有两种情况

* Connection Reset By Peer
* Connecting...Connection Reset By Peer

### Connection Reset By Peer 出现原因及解决办法

* 使用的是0.3.2版本的代码（本身代码有bug）；
* 并且直接访问的jumpserver端口，没有nginx代理；
* 解决办法-->将代码升级到master分支即可。

### Connecting...Connection Reset By Peer 出现原因及解决办法

* 使用nginx代理了jumpserver并且使用的是http代理；
* 代码版本无论是0.3.2还是master都会出现此问题；
* 解决办法-->http代理修改成tcp代理；
* nginx 1.9.x版本以上，编译时使用--with-stream参数可以支持tcp代理；
* 缺点是使用tcp代理之后无法配置server_name；
* 以下内容加到http{}外。

``` bash
stream {
    upstream backend{
        hash $remote_addr consistent;
        server 127.0.0.1:8000 weight=10;
    }

    server{
        listen 80;
        proxy_connect_timeout 20s;
        proxy_timeout 5m;
        proxy_pass backend;
    }
}
```

### 是否有其他情况造成此类问题没有测试过

**Comment by zhusas** [comment]
**这个问题经过我两周的折磨踩坑，已经解决，且在没非80端口上测试通过，同时也解决了Connection Reset By Peer 问题，关键在于nginx的配置**

#522 

- 下边的配置主要根据系统的open files来设定
events {
    worker_connections  262140;
}

- 下边的配置主要根据自己主机的内存大小来设定
http {
        fastcgi_buffer_size 512k;
        fastcgi_buffers 6 512k;
	fastcgi_busy_buffers_size 512k;
	fastcgi_temp_file_write_size 512k;
	client_max_body_size 4G;
	client_body_buffer_size 4096k;
}

- 下边的配置主要用于非80端口跳转，这里我用的是6666端口
server {
        if ( $scheme = http ) {
	    rewrite ^(.*)$ https://$host:6666$request_uri? permanent;
	}
}

- 下边的配置主要用于location段proxy的链接超时及buffer设置，根据自己主机的内存大小来设定
location / {
        proxy_set_header Connection "";
	proxy_http_version 1.1;
	proxy_pass      http://127.0.0.1:8000;
	proxy_connect_timeout 75;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        proxy_buffer_size 128k;
        proxy_buffers   8 128k;
        proxy_busy_buffers_size 256k;
        proxy_temp_file_write_size 256k;
}


**主要是把nginx的error日志开启debug，报啥错接解决啥，就OK了**

**Comment by ibuler** [comment]
same with #568
