### ISSUE TITLE
未激活主机是否可以不在终端主机列表显示[Feature] 

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#5241]
**请描述您的问题.**

未激活的主机在终端还是可以显示，例如很多主机处于关机状态，在列表中还是可以显示，就导致很多时候登陆主机都处于等待中，网络不通

**Comment by ibuler** [comment]
这个问题其实我们注意到了，由于资产树上要显示授权的资产数量，这个数量还是不确定了，如果资产禁用了，这个数量需要重新计算，资产少的时候没有影响，资产一多，计算非常耗时，所以我们把禁用的也放出来了，不得已的一个折中

**Comment by jym503558564** [comment]
优化了，未激活主机连接时有提示。
