### ISSUE TITLE
添加资产提示错误

### ISSUE THREAD

**Issue by zhengdazhi** [jumpserver/jumpserver#525]
Request Method:
--
http://192.168.15.161:8080/assets/asset/create/
1.11.2
TypeError
Unicode-objects must be encoded before hashing
/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84
/usr/bin/python
3.6.1
['/opt/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']
星期一, 10 七月 2017 10:33:54 +0800

**Comment by hellorocky** [comment]
![qq20170710-121508](https://user-images.githubusercontent.com/7486508/28002627-76a72fbe-6569-11e7-95e9-87de8f017c2b.png)

**Comment by zhengdazhi** [comment]
我在jumpserver/apps/assets/models/user.py中添加 如下行后无法启动了
key_name = md5(self._private_key).encode().hexdigest()

[root@localhost jumpserver]# docker-compose up
redis is up-to-date
Starting jumpserver ... 
Starting jumpserver ... error

ERROR: for jumpserver  Cannot start service jumpserver: driver failed programming external connectivity on endpoint jumpserver (1c949bcd0c6ec4c3bd3cdc83847b1b199bde7c9ae58835b5041c696594abfbb9): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.18.0.3:8080 ! -i br-94c8ace291f8: iptables: No chain/target/match by that name.
 (exit status 1)

ERROR: for jumpserver  Cannot start service jumpserver: driver failed programming external connectivity on endpoint jumpserver (1c949bcd0c6ec4c3bd3cdc83847b1b199bde7c9ae58835b5041c696594abfbb9): iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 172.18.0.3:8080 ! -i br-94c8ace291f8: iptables: No chain/target/match by that name.
 (exit status 1)
ERROR: Encountered errors while bringing up the project.

**Comment by hellorocky** [comment]
.....能仔细点吗?我不是那么写的

**Comment by zhengdazhi** [comment]
我改了，但是还是提示之前一样的错误  ，我下载的代码是放在 /usr/local/src/jumpserver 下然后用docker-compose up 开启的，代码没有出现在/opt/jumpserver，下面的报错中说/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84 这里代码有问题，这要怎么修改
  @property
    def private_key_file(self):
        if not self.private_key:
            return None
        project_dir = settings.PROJECT_DIR
        tmp_dir = os.path.join(project_dir, 'tmp')
        key_name = md5(self._private_key.encode()).hexdigest()
        key_path = os.path.join(tmp_dir, key_name)
        if not os.path.exists(key_path):
            self.private_key.write_private_key_file(key_path)
        return key_path



Request Method:
--
http://192.168.15.161:8080/assets/asset/create/
1.11.2
TypeError
Unicode-objects must be encoded before hashing
/opt/jumpserver/apps/assets/models/user.py in private_key_file, line 84
/usr/bin/python
3.6.1
['/opt/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']
星期一, 10 七月 2017 16:18:17 +0800

**Comment by ibuler** [comment]
可以下载新的docker来测试一下

`$ docker pull jumpserver/jumpserver:v0.4.0-beta1`
