### ISSUE TITLE
最新版 用户管理里的创建用户 点完之后没有输入项 是专门弄成这样的吗 还是bug

### ISSUE THREAD

**Issue by xdelphi** [jumpserver/jumpserver#5276]
如：
![image](https://user-images.githubusercontent.com/4436133/102303527-4f1ee080-3f96-11eb-832f-b765e0149e34.png)

**Comment by wojiushixiaobai** [comment]
换个浏览器试试

**Comment by xdelphi** [comment]
不是浏览器的原因，也不是缓存的原因！其他的功能都正常包括用户组，但就是用户没法添加 ，没有添加那几个输入框

**Comment by ibuler** [comment]
这个问题还存在吗?

**Comment by clcvi123** [comment]
这个问题我也存在，但是我是用源码跑的，也不晓得是哪里的问题

**Comment by jym503558564** [comment]
@xdelphi @clcvi123 使用什么浏览器？JumpServer版本？现在问题还存在吗？

**Comment by jym503558564** [comment]
@xdelphi @clcvi123 如果问题还存在，可再次打开Issues

**Comment by xdelphi** [comment]
> 这个问题还存在吗?

最新的没有问题了正常了

**Comment by xdelphi** [comment]
> 这个问题还存在吗?

最新的没有问题了正常了
