### ISSUE TITLE
[Bug] 切换英文后，云管中心的执行提示仍为中文

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#5277]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.5.3

**浏览器版本**
chrome

**Bug 描述**
切换英文后，云管中心的执行提示仍为中文

**Bug 重现步骤(有截图更好)**
1.  登录jms，界面右上角切换英文
2.  KOKO登录界面切换英文，修改配置文件LANGUAGE_CODE=en
3.  选择“云管中心”，执行同步计划。
![image](https://user-images.githubusercontent.com/34565342/102310099-3ff35f00-3fa5-11eb-9ae7-5efbf9f2b86c.png)

**Comment by ibuler** [comment]
待优化

**Comment by ibuler** [comment]
这是后台任务日志，不受用户页面的控制，因为执行任务的时候，日志已经生成了
