### ISSUE TITLE
改密计划定期执行关闭后再开启，就不执行了

### ISSUE THREAD

**Issue by zyyfit** [jumpserver/jumpserver#5279]
1、创建一个改密计划，填写定时执行表达式，等待定时任务执行。
2、执行成功后，关闭定时执行
3、然后再开启定时执行（这时会默认显示之前的定时执行表达式），等待定时任务执行，定时任务不执行了

**Comment by nondevops** [comment]
@zyyfit 请问改密计划是怎么实现的呢？ 开源版本没找到这个功能呢？

**Comment by ibuler** [comment]
同一个问题 https://github.com/jumpserver/trello/issues/602
