### ISSUE TITLE
[Question] ansible 通过jumpserver作为proxy

### ISSUE THREAD

**Issue by u2bo** [jumpserver/jumpserver#5297]
**请描述您的问题.**
想把jumpserver作为proxy，通过ansible 使用ProxyCommand通过jumpserver管理目标资源，想问下jumpserver目前是否支持这种方式？

**Comment by ibuler** [comment]
目前 koko 不支持 作为 Proxy形式，Proxy用的是 ssh tunnel，这个只是一个通道，无法解析其中的命令，也就无法审计，所以暂不支持

**Comment by ery** [comment]
我们也需要这个功能，希望能尽早实现

**Comment by gzm55** [comment]
@ibuler 不支持 tunnel 会严重影响效率, 为了审计而大大降低工作效率是不是得不偿失呢

**Comment by catsun26** [comment]
需要这个功能，请问有没规划
