### ISSUE TITLE
[Feature] 系统用户中的认证下的ssh密钥建议使用文本，而不是上传文件

### ISSUE THREAD

**Issue by dongye2738** [jumpserver/jumpserver#5300]
## 问题
* 使用文件时，对该用户进行更新时不显示是否采用ssh密钥方式，容易造成困扰
![bug-jumpser-2](https://user-images.githubusercontent.com/54405304/102572599-840e6d00-4127-11eb-99f1-ca0c8ab9dd02.jpg)

## 建议
* 采用文本复制方式,将私钥存储到数据库中，显示时私钥可以显示前面一部分以及后面一部分，这样每次更新时能知道是否采用了ssh私钥方式，以及私钥是用的哪个？

**Comment by ibuler** [comment]
敏感信息是不会回显的，计划把指纹显示出来

**Comment by 384691251** [comment]
> 敏感信息是不会回显的，计划把指纹显示出来

这个好像2.7.1还没做？

**Comment by jym503558564** [comment]
@dongye2738 @384691251 更新至最新版本，指纹已显示。
