### ISSUE TITLE
[Question]  在线会话，历史会话无数据

### ISSUE THREAD

**Issue by Leonn-code** [jumpserver/jumpserver#5302]
**请描述您的问题.**
有在线会话，但是在线会话显示无数据，关闭之后 历史会话里也没有数据
![image](https://user-images.githubusercontent.com/28649602/102579443-6cd77b80-4137-11eb-8c85-ca0244690a08.png)

**Comment by BaiJiangJie** [comment]
手动设置一下时间范围
