### ISSUE TITLE
Radius认证方式支持ssh密钥登录么？

### ISSUE THREAD

**Issue by vslinux** [jumpserver/jumpserver#5303]
现在使用Radius认证方式，而且有令牌，这种方式支持ssh免密钥命令行登录么？之前的版本是可以的。个人用户通过pem登录jumpserver

**Comment by ibuler** [comment]
第三方认证都不再支持 ssh 密钥认证，在第三方平台上禁用后，公钥还能登录 JumpServer，存在一些隐患，好的方案还没想清楚
