### ISSUE TITLE
[Bug] web终端，ssh终端，文件管理里default里都无法展开或者没有资产

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5304]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.0

**浏览器版本**

**Bug 描述**

web终端，ssh终端，文件管理里default里都无法展开或者没有资产
**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44529247/102622472-0759ae00-417c-11eb-830f-97e84f9865f4.png)

2. 
![image](https://user-images.githubusercontent.com/44529247/102622507-16d8f700-417c-11eb-9946-0c813dd23fd5.png)

3. 
![image](https://user-images.githubusercontent.com/44529247/102622574-2d7f4e00-417c-11eb-8a64-54a8a9ad5e83.png)

**Comment by ibuler** [comment]
现在这个问题还存在吗?

**Comment by jym503558564** [comment]
@ryswork1993 可升级至新版本测试，新版本未发现该问题。
