### ISSUE TITLE
[Bug] 节点上右键选择添加资产到节点bug

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5305]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.0

**浏览器版本**

**Bug 描述**
节点上右键选择添加资产到节点，然后选择资产并确认，这样后原节点和新节点都会有这个资产，但是总共的资产数量不会变化，然后删除新节点里添加的资产，就会导致原节点和新节点里的这个资产都被删除

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
资产可以同时存在多个节点，正确的做法是移除节点而不是删除资产
