### ISSUE TITLE
[Bug] 系统用户-批量推送不能勾选

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5306]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.0

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44529247/102738335-c5e81f00-4384-11eb-98ad-d38375b497ea.png)

2. 
3.

**Comment by ibuler** [comment]
右侧单个推送是禁用的，证明这个系统用户不支持推送
