### ISSUE TITLE
[Question] v2.6.0无法连接数据库

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#5307]
最新版v2.6.0安装完成后无法启动，多个镜像无法加载。查看日志发现无法连接数据库，本地和远程的都不行。
操作系统采用CentOS 8.3，不知道是否与之有关。

日志如下：
1、启动时控制台打印信息：
ERROR: for luna  Container "ee6b262f6ec4" is unhealthy.

ERROR: for celery  Container "ee6b262f6ec4" is unhealthy.

ERROR: for lina  Container "ee6b262f6ec4" is unhealthy.

ERROR: for guacamole  Container "ee6b262f6ec4" is unhealthy.

2、日志信息：
The above exception was the direct cause of the following exception:
core_1       | 
core_1       | Traceback (most recent call last):
core_1       |   File "manage.py", line 28, in <module>
core_1       |     execute_from_command_line(sys.argv)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
core_1       |     utility.execute()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
core_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
core_1       |     self.execute(*args, **cmd_options)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
core_1       |     output = self.handle(*args, **options)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 52, in handle
core_1       |     return self.show_list(connection, options['app_label'])
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 71, in show_list
core_1       |     loader = MigrationLoader(connection, ignore_no_migrations=True)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
core_1       |     self.build_graph()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
core_1       |     self.applied_migrations = recorder.applied_migrations()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
core_1       |     if self.has_table():
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
core_1       |     with self.connection.cursor() as cursor:
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
core_1       |     return func(*args, **kwargs)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
core_1       |     return self._cursor()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
core_1       |     self.ensure_connection()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
core_1       |     return func(*args, **kwargs)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
core_1       |     self.connect()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
core_1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
core_1       |     self.connect()
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
core_1       |     return func(*args, **kwargs)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
core_1       |     self.connection = self.get_new_connection(conn_params)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
core_1       |     return func(*args, **kwargs)
core_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
core_1       |     return Database.connect(**conn_params)
core_1       |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
core_1       |     return Connection(*args, **kwargs)
core_1       |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
core_1       |     super().__init__(*args, **kwargs2)
core_1       | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '192.168.1.241' (115)")
core_1       | 2020-12-21 20:33:25 Check database connection ...

**Comment by aiaiduo** [comment]
> 最新版v2.6.0安装完成后无法启动，多个镜像无法加载。查看日志发现无法连接数据库，本地和远程的都不行。
> 操作系统采用CentOS 8.3，不知道是否与之有关。
> 
> 日志如下：
> 1、启动时控制台打印信息：
> ERROR: for luna Container "ee6b262f6ec4" is unhealthy.
> 
> ERROR: for celery Container "ee6b262f6ec4" is unhealthy.
> 
> ERROR: for lina Container "ee6b262f6ec4" is unhealthy.
> 
> ERROR: for guacamole Container "ee6b262f6ec4" is unhealthy.
> 
> 2、日志信息：
> The above exception was the direct cause of the following exception:
> core_1 |
> core_1 | Traceback (most recent call last):
> core_1 | File "manage.py", line 28, in
> core_1 | execute_from_command_line(sys.argv)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/**init**.py", line 401, in execute_from_command_line
> core_1 | utility.execute()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/**init**.py", line 395, in execute
> core_1 | self.fetch_command(subcommand).run_from_argv(self.argv)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
> core_1 | self.execute(*args, **cmd_options)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
> core_1 | output = self.handle(*args, **options)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 52, in handle
> core_1 | return self.show_list(connection, options['app_label'])
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 71, in show_list
> core_1 | loader = MigrationLoader(connection, ignore_no_migrations=True)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in **init**
> core_1 | self.build_graph()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
> core_1 | self.applied_migrations = recorder.applied_migrations()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
> core_1 | if self.has_table():
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
> core_1 | with self.connection.cursor() as cursor:
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
> core_1 | return func(*args, **kwargs)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
> core_1 | return self._cursor()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
> core_1 | self.ensure_connection()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
> core_1 | return func(*args, **kwargs)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
> core_1 | self.connect()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in **exit**
> core_1 | raise dj_exc_value.with_traceback(traceback) from exc_value
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
> core_1 | self.connect()
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
> core_1 | return func(*args, **kwargs)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
> core_1 | self.connection = self.get_new_connection(conn_params)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
> core_1 | return func(*args, **kwargs)
> core_1 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
> core_1 | return Database.connect(**conn_params)
> core_1 | File "/usr/local/lib/python3.8/site-packages/MySQLdb/**init**.py", line 130, in Connect
> core_1 | return Connection(*args, **kwargs)
> core_1 | File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in **init**
> core_1 | super().**init**(*args, **kwargs2)
> core_1 | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '192.168.1.241' (115)")
> core_1 | 2020-12-21 20:33:25 Check database connection ...

你是否用的是本地是数据库，没有用docker里的数据库，我的也遇到过这个问题，我用的本地的数据库，配置数据库哪里的IP我填的是127.0.0.1就出现上面的报错，我填服务器的真实IP就可以了。
![image](https://user-images.githubusercontent.com/28044296/102947880-59455f80-44ff-11eb-8da2-3b51246b42cb.png)
