### ISSUE TITLE
开启服务后一直有报警

### ISSUE THREAD

**Issue by zhengdazhi** [jumpserver/jumpserver#531]
我使用 docker-compose up 启动项目后遗症看到日志里面提示这个
jumpserver    | 2017-07-10 11:43:38 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 31
coco          | WARNING:/opt/coco/coco/service.py:App auth failed, Access key error or need admin active it
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it

**Comment by hellorocky** [comment]
说明： Coco启动后会向jumpserver注册，请去 jumpserver页面 - 应用程序 - terminal - coco - Accept 允许， 这时 coco就 运行在 2222端口，可以ssh来连接

**Comment by zhengdazhi** [comment]
是我要在linux的防火墙里面允许 2222 的入栈请求？

**Comment by hellorocky** [comment]
如果要使用2222的话就得这么做

**Comment by ibuler** [comment]
我认为你可以查看一下：https://v.douyu.com/show/x0zZVvPQmRY7O4E2 可能会给你使用带来帮助

**Comment by zhengdazhi** [comment]
谢谢
