### ISSUE TITLE
[Question] 1.5.0陈年老版本升级

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#5314]
好家伙，版本跳得也太快了吧，文档并没有提及大版本间怎么升级
这种情况是不是只能全新安装并重新录入资产
数据库没法兼容的话，起码弄个资产导出功能吧？

**Comment by wojiushixiaobai** [comment]
请参考 _[升级文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/upgrade/)

**Comment by sicode** [comment]
> 请参考 _[升级文档](https://docs.jumpserver.org/zh/master/admin-guide/upgrade/upgrade/)

要求jumpserver 版本 >= v2.6.0

**Comment by sicode** [comment]
不纠结了
