### ISSUE TITLE
[Bug] 系统用户设置为用户名与用户相同时,用户无法访问家目录

### ISSUE THREAD

**Issue by aaawoyucheng** [jumpserver/jumpserver#5317]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.1

**浏览器版本**

**Bug 描述**
系统用户设置为用户名与用户相同时,用户无法访问家目录

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/11348658/102844524-9bf73100-4446-11eb-81f6-2d2220d61b36.png)

2. 
![image](https://user-images.githubusercontent.com/11348658/102844467-7a964500-4446-11eb-92b1-b026dfa95e4e.png)

3.

**Comment by ibuler** [comment]
这个填写家目录了吗?  动态用户登录的应该是与 自己同名才对

**Comment by gssjl2008** [comment]
同上，设置用户名与用户相同，默认自动推送的家目录是  /home ， 登陆之后家目录就是/home，而没有登陆jumpserver的用户目录

**Comment by jym503558564** [comment]
升级至最新版本进行测试，自动推送后，都在各自的家目录
