### ISSUE TITLE
[Feature] 增加堡垒机审核功能

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#5320]
**请描述您的需求或者改进建议.**
现实工作中有这种场景，当禁用命令后，的确需要执行禁用命名进行操作，此时如通过其他方法处置可能效率不是及时，希望能增加审核功能，当出现执行禁用命令的确需要执行时，终端提示是否确认要执行此条命令，然后输入Y进行确认，最后通知管理员进行命令确认，在后台进行放行操作。

**Comment by ibuler** [comment]
目前还无计划，未来会考虑，这个需要工单系统支持
