### ISSUE TITLE
[Feature] 能否给与选项配置RDP的墙纸、窗口主题、菜单效果和平滑字体等开关。

### ISSUE THREAD

**Issue by wangwujing** [jumpserver/jumpserver#5321]
guacamole，下有标记的。或者有没有其他办法，打开这些呢？
![image](https://user-images.githubusercontent.com/52844258/102857325-2a79ab80-4463-11eb-93d4-91e758d526d5.png)

**Comment by qiyongxiao** [comment]
一个靠终端解决问题的，打开这些没用的做什么。在我看来这个就是伪需求

**Comment by wojiushixiaobai** [comment]
有的。[Guacamole 参数说明](https://docs.jumpserver.org/zh/master/admin-guide/env/#guacamole)
