### ISSUE TITLE
[Question] [v2.6.1]报错：Server error occur, contact administrator

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#5323]
CentOS 7全新部署v2.6.1版本，所有镜像启动正常，后台无报错。
但登录后页面跳转至“http://192.168.50.240:8080/core/auth/login/guard/”并提示错误信息“Server error occur, contact administrator”

**Comment by orangexw** [comment]
版本2.3.1按照迁移手册升级至2.6.1，也出现此错误

**Comment by orangexw** [comment]
> 版本2.3.1按照迁移手册升级至2.6.1，也出现此错误
已通过此方法解决问题。
https://github.com/jumpserver/jumpserver/issues/5351#issuecomment-751675436

**Comment by wojiushixiaobai** [comment]
好的，辛苦了。
