### ISSUE TITLE
jumpserver2.5.3命令过滤有缺陷[Bug] 

### ISSUE THREAD

**Issue by show344** [jumpserver/jumpserver#5330]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver2.5.3

**浏览器版本**
谷歌浏览器

**Bug 描述**
对Linux系统资产配置了命令过滤，但是在Linux系统命令行界面，有发送文本到所有SSH终端功能，无法对Linux系统进行命令过滤控制，不知道是否可以控制或者禁用发送文本到所有SSH终端功能。

**Comment by ibuler** [comment]
这个bug已知悉，正在修复中

**Comment by LeeEirc** [comment]
@show344  命令过滤已经完成一次优化，请使用v2.7.0验证，有问题再反馈。
