### ISSUE TITLE
[Bug] 2.6.1 web终端搜索异常

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#5331]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.1

**浏览器版本**
Chrome 87.0.4280.88

**Bug 描述**
资产列表中有的，打关键字缺搜不出来
资产名Ubuntu-Docker，输docker 搜索不到，输Docker才可以，估计是区分大小写了
资产名windows7，输7 却搜索出 不带7的资产

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/3986116/102965485-df29d080-4528-11eb-8572-9263ec15f70d.png)

2.
![image](https://user-images.githubusercontent.com/3986116/102965535-f799eb00-4528-11eb-9bbc-89f61d8b5a5c.png)

3. 
![image](https://user-images.githubusercontent.com/3986116/102965553-0385ad00-4529-11eb-8ad2-2575c177adec.png)

**Comment by ibuler** [comment]
1. 大小写问题要修复
2. ip 中有7了

**Comment by jym503558564** [comment]
资产名称含大写字母，确实搜索不存来，存在该问题。

**Comment by jym503558564** [comment]
升级至新版本，大小写搜索问题已修复。
