### ISSUE TITLE
[Question] keycloak开启otp后，koko客户端无法登录

### ISSUE THREAD

**Issue by hbgcll** [jumpserver/jumpserver#5332]
**请描述您的问题.**
版本 v2.5.2
使用keycloak进行认证，keycloak开启otp二次验证后，koko客户端无法登录。
使用curl 直接访问keycloak,可以获取到token，看起来是认证的时候不会发送 opt 验证码。
请问如何配置

**Comment by ibuler** [comment]
keycloak 二次验证过没有测试过，web 登录应该是可以的，因为会跳转， 但 ssh 不知道能不能支持

**Comment by ibuler** [comment]
长时间没有反馈，暂时关闭，有问题重新打开
