### ISSUE TITLE
v2.6 升级导致部署迁移繁琐

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#5334]
**请描述您的需求或者改进建议.**
2.6.1升级安装方法完全不按套路来，之前没有用默认/opt,部分组件用docker安装的基本要毁了重新安装，重做数据。

**Comment by yearnxiao** [comment]
之前装了docker的机器直接安装失败原docker环境也被你们的安装脚本搞毁了，能不能给用户更多选择，或者脚本写的更智能点，不要什么都由着你们的性子来？

**Comment by ibuler** [comment]
之前版本是社区维护的，这次想统一社区和企业部署方式，确实带来了不方便的地方，还请谅解，文档中应该描述了迁移方式，这应该是最后一次了

**Comment by yearnxiao** [comment]
原来为了保留更多的操作数据，我把安装目录改到一个单独的大硬盘分区上安装，没用默认的OPT，部分服务用docker。我看脚本里很多地方写死了OPT，我上午全部删除重来了一遍。

关于应用里的Kubernetes是收费版功能吗？添加了集群API URL地址后没有其他任何可操作的了，这是什么情况？

**Comment by luomoxu** [comment]
感觉纯docker容器运行比部署脚本方便多了
上K8S或迁移也成本更低
感觉在开倒车了

**Comment by yearnxiao** [comment]
不论怎么做迁移或升级感觉升级方式处理的不太恰当，这套系统重要的数据无非就是持久化数据Mysql&录像文件，升级只用处理这两部分数据转换迁移就可以了，每次大版本升级搞得用户还要关心应用层的很多东西。不过这次大一统操作后，后面应该会方便很多。

**Comment by ibuler** [comment]
可以找 @wojiushixiaobai 武汉小白 qq聊聊

**Comment by ibuler** [comment]
@luomoxu 这个版本也是  纯 docker 版本啊

**Comment by luomoxu** [comment]
> @luomoxu 这个版本也是 纯 docker 版本啊

我现在使用的2.5.3版本是在阿里云的k8s服务中直接启动的 不需要实体机
但是目前新的部署版本我还需要先部署一台实体机

**Comment by yearnxiao** [comment]
在迁移到新部署方式后，发现仍然不统一，操作繁琐。从2.5升到2.6.1经历了阵痛，2.6.1升级2.7.0又发现用2.6.1的脚本upgrade提示有新版本，但只更新了core一个镜像到2.7.0，其余镜像没有被更新，感觉这样的安装升级脚本还是不要也罢！如果要统一升级能不能把方案考虑周全易用一点？官方升级文档也没可调必需用最新的安装脚本做升级操作。

**Comment by imleafz** [comment]
> 在迁移到新部署方式后，发现仍然不统一，操作繁琐。从2.5升到2.6.1经历了阵痛，2.6.1升级2.7.0又发现用2.6.1的脚本upgrade提示有新版本，但只更新了core一个镜像到2.7.0，其余镜像没有被更新，感觉这样的安装升级脚本还是不要也罢！如果要统一升级能不能把方案考虑周全易用一点？官方升级文档也没可调必需用最新的安装脚本做升级操作。

以下是个人感受，望考虑。感觉之前的一键安装才是真正的一键，现在一键安装脚本，做了太多不应该由脚本做的工作。感觉整个运行环境被绑架了，docker、数据路径这些被脚本定的死死的，完全失去了灵活性呀。我跟@luomoxu一样之前直接跑在k8s上的，真的很方便，还到处跟同事朋友做宣传这个好用呢，现在部署这一步几乎就要劝退了。

**Comment by yearnxiao** [comment]
> > 在迁移到新部署方式后，发现仍然不统一，操作繁琐。从2.5升到2.6.1经历了阵痛，2.6.1升级2.7.0又发现用2.6.1的脚本upgrade提示有新版本，但只更新了core一个镜像到2.7.0，其余镜像没有被更新，感觉这样的安装升级脚本还是不要也罢！如果要统一升级能不能把方案考虑周全易用一点？官方升级文档也没可调必需用最新的安装脚本做升级操作。
> 
> 以下是个人感受，望考虑。感觉之前的一键安装才是真正的一键，现在一键安装脚本，做了太多不应该由脚本做的工作。感觉整个运行环境被绑架了，docker、数据路径这些被脚本定的死死的，完全失去了灵活性呀。我跟@luomoxu一样之前直接跑在k8s上的，真的很方便，还到处跟同事朋友做宣传这个好用呢，现在部署这一步几乎就要劝退了。

深有同感，以前的部署步骤完全虽然繁琐，但是用户自主可控性强，做为IT管理人员这是最基本技能。现在所有操作全部绑死，我上面也有提到过Docker环境都绑死，我之前安装做了很多Docker的环境定制，一下子把我的Docker环境给搞崩了。我认为官方想做到升级迁移方便统一，只用在数据库数据的备份、升级上做好就行了，用户拿一份完整备份数据基础环境随意折腾都不影响才是正道。

**Comment by ibuler** [comment]
@yearnxiao 升级到 v2.7.0, 非常抱歉, 因为和quick_start脚本没有配合好了所以带来了这些问题

**Comment by ibuler** [comment]
这个版本和企业版进行打通，以后统一维护。其中锁定了 docker 版本，是考虑系统安装的版本不对，带来的问题，目的是减少以后的排查问题，在未来一段时间内会推出不交互的安装当时，另外 现在 k8s 也是支持安装的

**Comment by ibuler** [comment]
其实本质上 安装脚本中，就是安装 docker，docker compose，修改配置文件，拉镜像进行启动

**Comment by yearnxiao** [comment]
个人建议你们在安装Docker脚本之前做个判断，如果用户版本符合要求就跳过，不满足就提示用户升级或移除docker再执行脚本。我还是认为升级、迁移的核心就是数据库数据的升级迁移。

**Comment by wojiushixiaobai** [comment]
已经做了优化及相应的判断，等待合并。感谢反馈，我们会持续优化这方面的内容

**Comment by skyrim61** [comment]
打了500个字, 想了想还是删了. 上来就怒喷一波,特定登录账号
