### ISSUE TITLE
在资产列表测试节点资产连接和更新资产硬件不会显示任务结果[Bug] 

### ISSUE THREAD

**Issue by show344** [jumpserver/jumpserver#5337]
**JumpServer 版本(v1.5.9以下不再支持)**

2.6.1
**浏览器版本**
谷歌和火狐

**Bug 描述**
在资产列表测试节点资产连接和更新资产硬件，会弹出任务执行的界面，但是界面不会显示任务执行结果，在查看任务列表可以看到任务已经成功。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/40684246/103076142-0dcaa880-4608-11eb-98b9-46eab2da3323.png)

**Comment by wojiushixiaobai** [comment]
如果使用了外置redis，需要redis 版本 > 5.0.0 ，确认下
如果内置 redis 出现了此问题，请确认下进程是否都已经正常启动
