### ISSUE TITLE
终端管理-koko终端和gua终端状态会断线[Bug] 

### ISSUE THREAD

**Issue by show344** [jumpserver/jumpserver#5338]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.1

**浏览器版本**
谷歌和火狐

**Bug 描述**
终端管理-koko终端和gua终端状态会自动断线，但是登陆Windows和Linux系统是正常的。

**Bug 重现步骤(有截图更好)**
![1608801961(1)](https://user-images.githubusercontent.com/40684246/103078685-5d5fa300-460d-11eb-8195-5c71351ba53b.jpg)

**Comment by ibuler** [comment]
目前还不能复现，请发一下5分钟内 Nginx的日志
