### ISSUE TITLE
不支持常用的终端快捷键

### ISSUE THREAD

**Issue by fency12** [jumpserver/jumpserver#5339]
如输入状态下 ctrl + w 删除当前输入，ctrl+a切到行首， ctrl+e切到行尾 等快捷键 ，他能提高工作效率，也更接近于客户端终端，建议优化增加该支持。

**Comment by ibuler** [comment]
这些是支持的，难道是在选择资产那里?

**Comment by fency12** [comment]
> 这些是支持的，难道是在选择资产那里?

大佬好。测了下只是不能ctrl + w， ctrl + a， ctrl + e没问题的
