### ISSUE TITLE
[Bug]  在管理k8s 1.19集群时报yaml文件格式错误

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#5341]
**JumpServer 版本(v2.6.1以下不再支持)**

**浏览器版本**

**Bug 描述**
在管理k8s V1.19集群时报yaml文件格式错误，直接在集群主机上发布都可以正常解析，用jumpserver执行发布就提示格式解析错误：error: error parsing xxx.yaml: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context

执行kubectl  version,发现客户端版本和服务器端版本不同，初步怀疑可能是问题原因。请问如何自行更换kubectl程序？在jumpserver源码中没搜索到相关关键字。
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
@yearnxiao 加我qq2970298425，远程看下。

**Comment by ibuler** [comment]
处理结果可以记录到这里

**Comment by yearnxiao** [comment]
这个Issues可以删除吗？之前应该是我这边yaml文件服务器配置问题，导致kubectl无法直接拿到真实yaml文件内容导致的。
