### ISSUE TITLE
[Question] 2.6.X如果希望仍旧使用80端口访问主页

### ISSUE THREAD

**Issue by enthanlee** [jumpserver/jumpserver#5343]
**请描述您的问题.**
2.6.X如果希望仍旧使用80端口访问主页，而不是8080或其他端口。应该如何修改设置。
另外Guacamole, 希望所有用户默认跳过手动输入密码，应该如何设置。

**Comment by wojiushixiaobai** [comment]
请参考 _[帮助文档](https://docs.jumpserver.org/zh/master/faq/other/)
