### ISSUE TITLE
[Bug] 命令过滤轻松可绕过

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#5346]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.5.2 GPLv2.

**浏览器版本**
chrome 版本 87.0.4280.88（正式版本） (x86_64)

**Bug 描述**
给系统用户设置了命令过滤，直接输入被过滤的命令，确实是被禁止的，但是如果命令出现在脚本里，就能正常执行了，所以命令过滤几乎是形同虚设？

**Bug 重现步骤(有截图更好)**
1.  设置过滤命令lsattr，直接输入lsattr确实是被禁止了的。
![image](https://user-images.githubusercontent.com/2853517/103130355-53a27200-46d7-11eb-9087-d715afbff2f5.png)

2. 创建shell脚本，里面执行lsattr
![image](https://user-images.githubusercontent.com/2853517/103130389-792f7b80-46d7-11eb-97d6-e92fa0223643.png)

3. 执行sh t.sh
![image](https://user-images.githubusercontent.com/2853517/103130414-96fce080-46d7-11eb-9a2f-7995736712be.png)

lsattr能正常运行。所以这种情况下怎么防范呢？

**Comment by wojiushixiaobai** [comment]
只能作为防呆，不是agent形式，只能根据输入的字符串拦截

**Comment by bubbleatgit** [comment]
用 `sudo` 白名单控制权限，

**Comment by ibuler** [comment]
命令过滤只是过滤从 ssh 发来的字符，至于脚本只能系统级别限制了
