### ISSUE TITLE
升级到v2.6.1后需要重新绑定Google身份验证

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#5349]
**请描述您的需求或者改进建议.**
通过installer升级到v2.6.1，数据也升级成功，但是登陆账户后需要重新设置一遍Google身份验证。不知道是否是bug，如果不是希望能够增强升级功能。

**Comment by wojiushixiaobai** [comment]
测试未复现，请检查是否升级前后的加密 SECRET_KEY 不一致导致

**Comment by seaurching** [comment]
> **请描述您的需求或者改进建议.** 通过installer升级到v2.6.1，数据也升级成功，但是登陆账户后需要重新设置一遍Google身份验证。不知道是否是bug，如果不是希望能够增强升级功能。

方便告诉一下如何配置谷歌账号登陆吗？ @wojiushixiaobai @vzrs 我不知道下面截图中改填写什么地址。方便的话可以回复我一下
<img width="1412" alt="image" src="https://github.com/jumpserver/jumpserver/assets/7349963/5c3eb44e-4055-47fc-a557-31adb06ffb74">
