### ISSUE TITLE
coco项目如何设置用户登录空闲时间超时自动断开

### ISSUE THREAD

**Issue by hellorocky** [jumpserver/jumpserver#535]
当用户登录到某一个资产的时候, 可能很长时间没有进行任何操作, 这时候我想把他的链接给断开, 该怎么设置, 我看了paramiko的文档, 没有找到相关的设置, 有没有知道的, 给提示一下~

**Comment by ibuler** [comment]
之前版本设置的定时任务，现在coco还没有考虑

**Comment by hellorocky** [comment]
@ibuler 嗯嗯,  我去看看之前版本的实现方式

**Comment by zsjohny** [comment]
@hellorocky  找到了@ 我一下 同求

**Comment by hellorocky** [comment]
@zsjohny https://github.com/jumpserver/jumpserver/blob/master/jlog/log_api.py#L97

**Comment by ibuler** [comment]
#569

**Comment by ibuler** [comment]
已处理
