### ISSUE TITLE
[Question] 2.3.0 升级到最新报错

### ISSUE THREAD

**Issue by lanheader** [jumpserver/jumpserver#5351]
**请描述您的问题.**
2.3.0 升级到最新2.6.1，jms_core 报错，
报错是备份2.3.0数据库以后，按照文档，恢复数据库，重启程序开始报错。
![image](https://user-images.githubusercontent.com/52522047/103208434-96648400-493b-11eb-9c88-a86de2e9d60b.png)

**Comment by wojiushixiaobai** [comment]
@lanheader 参考 第二条 [导入数据库报错](https://docs.jumpserver.org/zh/master/faq/other/) 解决即可
注意先 ./jmsctl.sh stop 停止 core 容器
