### ISSUE TITLE
增加系统资源报警阈值设定[Feature] 

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#5355]
**请描述您的需求或者改进建议.**
总是收到 “磁盘使用率超过 80%: /snap/core/8689 => 100.0” 这样的报警邮件。
可不可以自己设定磁盘占用率的阈值？或者是自己选择是否打开该监控。
同时，可不可以增加一些可供用户选择的系统资源监控选项，比如带宽监控、CPU内存监控等

**Comment by wojiushixiaobai** [comment]
已经在计划里面了，感谢反馈。
