### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by miaoyb** [jumpserver/jumpserver#5358]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.3.2

**浏览器版本**
chrome

**Bug 描述**
资产激活状态为否的情况下依然可以通过terminal进行展示以及连接

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
是的，只不过不可以使用，提示资产已禁用下线

**Comment by jym503558564** [comment]
- 资产已禁用情况下，web终端连接资产提示：该资产已被禁用，请联系管理员。
![image](https://user-images.githubusercontent.com/40739051/109459656-348adc80-7a9a-11eb-962f-f85ed35ca221.png)
- 如还有什么疑问，可提Issues
