### ISSUE TITLE
能否在一个docker镜像里面部署？[Feature] 

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#5359]
**请描述您的需求或者改进建议.**
如题。不想在我们现有的服务器里面运行部署脚本，想将所有的jms内容放在同一个docker里面，然后我就只需要管理这一个docker镜像就好了。

**Comment by wojiushixiaobai** [comment]
@rty813 因为新功能里面的部分组件无法合并到一起，所以我们舍弃了以前的 all in one 形式
或者也可以根据此 [Dockerfile](https://github.com/jumpserver/Dockerfile/blob/master/allinone/Dockerfile) 定制一下保留想要的内容即可。

请注意，这样可能会带来一些未经验证的问题，请在使用的时候多测试

**Comment by rty813** [comment]
好吧

**Comment by dislazy** [comment]
那是否有新版本的各镜像的部署方式呢  部署完 使用外部的nginx配置
