### ISSUE TITLE
优化对Fish-shell的命令记录[Bug] 

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#5360]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.6.1

**浏览器版本**

**Bug 描述**
若Linux资产使用的是Fish-shell，[github链接](https://github.com/fish-shell/fish-shell)，则命令记录功能会变的很混乱。
因为fish有命令自动补全功能，而自动补全时的提示，会全部记录在“命令记录”里面。这样会导致很混乱，而且有些命令实际上我并没有执行，但依然会显示在命令记录里面。
这个问题还会造成，命令过滤功能无法使用。比如，命令过滤中增加`systemctl stop httpd`。但只要之前使用过这个命令，当我键入`sys`之类的字符时，fish会自动弹出补全提示，这时无论我执行什么命令，都会被拦截。

**Bug 重现步骤(有截图更好)**
1.  在终端中输入apt
![Snipaste_2020-12-30_15-48-58](https://user-images.githubusercontent.com/22488813/103337508-963cc380-4ab6-11eb-9e03-6d80da7872b8.png)
2. 命令记录里面就会出现很乱的记录
![Snipaste_2020-12-30_15-48-39](https://user-images.githubusercontent.com/22488813/103337520-9fc62b80-4ab6-11eb-8e0e-5254a9c90acb.png)

**Comment by LeeEirc** [comment]
v2.7.0已经对命令记录进行一次优化，请使用v2.7.0测试下，存在问题，再反馈。 @rty813

**Comment by rty813** [comment]
我用2.11.1版本，又试了一次。还是会出现乱的情况
![Snipaste_2021-06-21_15-54-19](https://user-images.githubusercontent.com/22488813/122726916-0f201980-d2a9-11eb-9f5c-94da58f4395b.png)
![Snipaste_2021-06-21_15-54-40](https://user-images.githubusercontent.com/22488813/122726924-11827380-d2a9-11eb-86d3-c54c52eb9a24.png)
