### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wolfguoliang** [jumpserver/jumpserver#5363]
**JumpServer 版本(v1.5.9以下不再支持)**

2.6.1
**浏览器版本**

 chrome 87.0.4280.88
**Bug 描述**

2.6.1 使用ldap 认证，用户无法配置ssh key，即使管理员配置上了也无法用ssk 认证。
**Bug 重现步骤(有截图更好)**

**Comment by ibuler** [comment]
从 v2 开始，开启 ldap 后禁用了 公钥登录，因为在 ldap 删除用户后，允许公钥登录这个用户还能登录

**Comment by wolfguoliang** [comment]
好的，十分感谢！
