### ISSUE TITLE
我想在机器上跑源码的时候。nginx的配置按照文档要求填写，web登录时还总是显示  如果你能看到这个页面，证明你的配置是有问题的，请参考文档设置好nginx, UI由Lina项目提供；官方有没有相应的使用源码的文档

### ISSUE THREAD

**Issue by clcvi123** [jumpserver/jumpserver#5367]
# jumpsrver 服务器
    server {
        listen 8089;  # 代理端口,以后将通过此端口进行访问,不再通过9091端口
        server_name 192.168.5.21;  # 修改成你的域名

        client_max_body_size 100m;  # 录像及文件上传大小限制

        location /luna/ {
            try_files $uri / /index.html;
            alias /opt/developJumpserver/luna-v2.6.1/;  # luna 路径,如果修改安装目录,此处需要修改
        }

        location /media/ {
            add_header Content-Encoding gzip;
            root /opt/developJumpserver/jumpserver-v2.6.0/data/;  # 录像位置,如果修改安装目录,此处需要修改
        }

        location /static/ {
            root /opt/developJumpserver/jumpserver-v2.6.0/data/;  # 静态资源,如果修改安装目录,此处需要修改
        }

        location /socket.io/ {
            proxy_pass       http://localhost:5000/socket.io/;  # 如果coco安装在别的服务器,请填写它的ip
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }

        location /coco/ {
            proxy_pass       http://localhost:5000/coco/;  # 如果coco安装在别的服务器,请填写它的ip
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }

        location /guacamole/ {
            proxy_pass       http://localhost:8081/;  # 如果guacamole安装在别的服务器,请填写它的ip
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }
location / {
                proxy_pass http://localhost:8080;  # 如果jumpserver安装在别的服务器,请填写它的ip
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
    }

使用nginx -t 没有问题，但是浏览器访问的时候就会报   如果你能看到这个页面，证明你的配置是有问题的，请参考文档设置好nginx, UI由Lina项目提供

**Comment by bingws** [comment]
你那个Lina，niginx配置文件里没有。看下官方文档。或加入slack交流群交流。

**Comment by clcvi123** [comment]
多谢问题解决了

**Comment by zmf-maker** [comment]
你好，我也遇到这个问题了，是怎么解决的呢

**Comment by wojiushixiaobai** [comment]
@zmf-maker 源代码部署你还得把 lina 部署出来。
