### ISSUE TITLE
[Question] 我想把录像存储到服务器中其它硬盘上，应该怎么做？

### ISSUE THREAD

**Issue by yiyi99** [jumpserver/jumpserver#5368]
服务器上有两个硬盘，其中一个是启动分区，另外一个是用来存放数据的，容量比较大；我想把录像文件存放到比较大的这个分区，应该如何操作？

**Comment by wangwujing** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/env/

**Comment by yiyi99** [comment]
> https://docs.jumpserver.org/zh/master/admin-guide/env/ 修改JUMPSERVER_RECORD_PATH=/config/guacamole/record # 录像保存目录，目录挂载到另外一个硬盘下，不就可以了？

我试试，谢谢！
