### ISSUE TITLE
自定义python解析器路径

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5375]
场景：资产上有python2.7和3.x，有可能默认的python是3.x.
而ansible对python版本有要求
---------------------------------------------
如：
root@ecs-test-0001  ~  python -V
Python 3.9.0a1

[root@ansible-itops-01 ~]# ansible -i host.list 192.168.1.21   -m ping
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: zipimport.ZipImportError: can't decompress data; zlib not available
192.168.1.21 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 192.168.1.21 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"<frozen zipimport>\", line 520, in _get_decompress_func\r\nModuleNotFoundError: No module named 'zlib'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"<frozen zipimport>\", line 568, in _get_data\r\n  File \"<frozen zipimport>\", line 523, in _get_decompress_func\r\nzipimport.ZipImportError: can't decompress data; zlib not available\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1609728639.37-31335-114576896803266/AnsiballZ_ping.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1609728639.37-31335-114576896803266/AnsiballZ_ping.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1609728639.37-31335-114576896803266/AnsiballZ_ping.py\", line 37, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"<frozen zipimport>\", line 241, in load_module\r\n  File \"<frozen zipimport>\", line 709, in _get_module_code\r\n  File \"<frozen zipimport>\", line 570, in _get_data\r\nzipimport.ZipImportError: can't decompress data; zlib not available\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

---------------------------------------------
建议每个资产可以像协议组那样，增加一个ansible_python_interpreter参数，在连接该资产时用指定python路径。

如在192.168.1.21  ansibler server上设置
ansible_python_interpreter=/usr/bin/python2.7

[root@ansible-itops-01 ~]# ansible -i host.list 192.168.1.21   -m ping
192.168.1.21 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

这是当资产默认python是3.x时，测试连接的报错：
![python-v3-error](https://user-images.githubusercontent.com/24548477/103504914-c65bdc00-4e93-11eb-9a77-e9b00b7fe317.jpg)

**Comment by ibuler** [comment]
这样会让资产添加变得很复杂，添加了很多填写框

**Comment by ibuler** [comment]
不过问题的确是需要解决的

**Comment by ibuler** [comment]
已记录
