### ISSUE TITLE
[Feature] 工单授权与手动授权分开管理、易于查找

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#5376]
**请描述您的需求或者改进建议.**
在授权管理中，工单授权以及手动授权希望可以分开管理和查看，这样当使用工单申请权限的时候，不至于工单授权记录太多，导致手动授权记录查找困难。

**Comment by BaiJiangJie** [comment]
新版本已有 from_ticket（来自工单）字段来进行区分。
