### ISSUE TITLE
[Feature] 能否支持 lrzsz 的功能

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5386]
**请描述您的需求或者改进建议.**

2.x能否在web terminal端支持 lrzsz 功能？[链接](https://github.com/FGasper/zmodemjs)

**Comment by ibuler** [comment]
打算支持来着，现在还没准备好，比较还得考虑是否要记录日志

**Comment by bingws** [comment]
期待，anjular不太懂，不然自己开发了。
