### ISSUE TITLE
ldap对接导入用户后，ldap-server端用户删除后，平台不会禁用用户。[Bug] 

### ISSUE THREAD

**Issue by Gary0317** [jumpserver/jumpserver#5394]
**Bug 描述**
ldap对接导入用户后，ldap-server端用户删除后，平台不会禁用用户。

**Comment by ibuler** [comment]
ldap server删除后，jumpserver中的用户不会禁用，因为收不到ldap-server的事件。同理 cas 和 oidc 一样，如果允许第三方系统登录的用户设置 公钥，那么第三方删除后，还可以用公钥登录，这个显然是有问题的

**Comment by luweijun1992** [comment]
> ldap server删除后，jumpserver中的用户不会禁用，因为收不到ldap-server的事件。同理 cas 和 oidc 一样，如果允许第三方系统登录的用户设置 公钥，那么第三方删除后，还可以用公钥登录，这个显然是有问题的

那请问下，当ldap服务器上禁用用户之后，那该用户还可以在jumpserver上登录成功吗？

**Comment by ibuler** [comment]
不过不启用公钥，ldap上禁用了，是无法登陆成功的
