### ISSUE TITLE
ldap对接后，ldap用户上传ssh-key密码失效。是否能通过配置进行开启。[Feature] 

### ISSUE THREAD

**Issue by Gary0317** [jumpserver/jumpserver#5395]
**请描述您的需求或者改进建议.**
ldap对接导入用户后，ldap用户上传ssh-key秘钥失效。是否能通过配置进行改功能开启。

**Comment by ibuler** [comment]
是的，目前在考虑如何处理这个问题，正在考虑如何处理这个问题，已记录到内部issue中，暂时关闭该 issue
