### ISSUE TITLE
[Question] docker无法重启问题排查

### ISSUE THREAD

**Issue by birdofprey** [jumpserver/jumpserver#5396]
**请描述您的问题.**
OS:Debian Gnu/Linux 10.7

Kernel:Debian 5.9.6-1~bpo10+1 (2020-11-19) x86_64 GNU/Linux

firewall:nftables v0.9.0 (Fearless Fosdick)

docker:Docker version 18.09.1, build 4c52b90

问题描述：本机使用了nftables作为默认防火墙组件，使用apt-get install docker.io安装docker后，执行命令“systemctl restart docker” 后docker异常，通过命令“jjournalctl -u docker.service”查看重启详细过程，发现如下错误：

1月 08 07:43:04 localhost dockerd[18260]: time="2021-01-08T07:43:04.938383895+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000884200, CONNECTING" module=grpc
1月 08 07:43:05 localhost dockerd[18260]: Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create FILTER chain DOCKER: iptables failed: iptables -t filter -N DOCKER: iptables v1.8.2 (nf_tables): Chain already exists
1月 08 07:43:05 localhost dockerd[18260]:  (exit status 1)

问题解决方法：

1、systemctl stop docker

2、ip link set docker0 down

3、brctl delbr docker0

4、systemctl restart nftables.server

5、systemctl start docker

**Comment by ibuler** [comment]
具体的docker问题，不是很清楚了

**Comment by birdofprey** [comment]
> 具体的docker问题，不是很清楚了

测试了一下，应该是和nftables防火墙兼容性的问题。我没有使用默认的iptables，而是使用了nftables作为系统的防火墙组件

**Comment by ColinZeb** [comment]
最新版本还能用docker吗

**Comment by birdofprey** [comment]
> 最新版本还能用docker吗

apt-get install docker.io 试试吧

**Comment by ibuler** [comment]
可以的
