### ISSUE TITLE
[Question] 自动推送系统用户不生效

### ISSUE THREAD

**Issue by einsone** [jumpserver/jumpserver#5397]
## 问题

通过API `/assets/assets/`创建资产后，没有自动推送系统用户到资产。手动推送可以成功。系统用户自动推送的开关也开着的

**Comment by ibuler** [comment]
Web页面也是这个api创建的

**Comment by einsone** [comment]
> Web页面也是这个api创建的

自动推送系统用户的触发条件是什么呢，这个情况并不总是出现

**Comment by ibuler** [comment]
当系统用户关联到资产时，会自动推送

**Comment by einsone** [comment]
> 当系统用户关联到资产时，会自动推送

系统用户关联到资产了， 没有触发推送， 登录不上系统

**Comment by ibuler** [comment]
没有自动推送，就需要看看日志了，是不是系统用户没有开启自动推送

**Comment by thb7758** [comment]
我这边也遇到了系统没有自动推送用户 ，还有这个日志路径在哪了
