### ISSUE TITLE
2.6.1 telnet连接不上设备

### ISSUE THREAD

**Issue by mrpretext886** [jumpserver/jumpserver#5398]
更新到2.6.1后 telnet无法连接设备，无任何提示，密码和连通性均无误

![image](https://user-images.githubusercontent.com/63313310/103980846-9f671800-51bb-11eb-8008-824c383b6842.png)
没有任何的提示

**Comment by LeeEirc** [comment]
@mrpretext886 可以看下koko的错误日志吗？ `docker logs -f jms_koko --tail=100`

**Comment by mrpretext886** [comment]
![image](https://user-images.githubusercontent.com/63313310/103983071-a55ef800-51bf-11eb-845b-cf082e3b4f2b.png)

**Comment by mrpretext886** [comment]
升级前备份了2.5.3版本的，2.5.3版本正常

**Comment by mrpretext886** [comment]
![image](https://user-images.githubusercontent.com/63313310/103983631-8f056c00-51c0-11eb-8049-e107afb902b0.png)
2.6.1的终端状态也是正常的，ssh正常，telnet连接不上设备，没有提示

**Comment by LeeEirc** [comment]
页面上，系统设置-终端设置-Telnet正则表达式 先去掉你写的正则。另外加我q 2970298425 远程看下。

**Comment by mrpretext886** [comment]
感谢大神解惑 ，删除 终端设置-Telnet 成功正则表达式 ，登录正常！！！
