### ISSUE TITLE
萌新求救，二次开发只能在linux上开发吗？

### ISSUE THREAD

**Issue by clcvi123** [jumpserver/jumpserver#5401]
现在专门架了一台机器来搞这个，但是在linux下调试taimafan1，想问下各位是用什么样的方式进行开发调试的

**Comment by ibuler** [comment]
mac也是可以的

**Comment by clcvi123** [comment]
这个开发太麻烦了，在window下改了，要传到linux上跑调试，调试还贼不方便

**Comment by ibuler** [comment]
你可以尝试代码挂载到 linux 上，nfs, samba 等

**Comment by bingws** [comment]
我有个闲置的mac2019款 @clcvi123

**Comment by clcvi123** [comment]
这个倒是不需要了发自坚果 Pro 2
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }binghang <notifications@github.com>
于 2021年1月11日 下午2:18写道：

我有个闲置的mac2019款 @clcvi123



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/jumpserver/jumpserver/issues/5401#issuecomment-757647940",

"url": "https://github.com/jumpserver/jumpserver/issues/5401#issuecomment-757647940",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by bingws** [comment]
GitHub都被你搞出bug了==
