### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xiamengyou** [jumpserver/jumpserver#5402]
**JumpServer 版本：v2.5.3**

**Bug 描述**
在JumpServer的任务监控中，发现一个定时任务一直运行失败，重启了JumpServer该定时任务依然如此。同时，一些已经过期的会话也没有被自动清除。

![image](https://user-images.githubusercontent.com/5858044/104140561-e8ea7980-53ec-11eb-8210-cc6b218867ac.png)

在日志中的错误表现为：
![image](https://user-images.githubusercontent.com/5858044/104140659-7b8b1880-53ed-11eb-8f37-145612487476.png)

**Bug 重现步骤(有截图更好)**
不清楚如何触发该bug。

**Comment by ibuler** [comment]
这应该是 celery 的问题，现在问题依然存在吗？

**Comment by xiamengyou** [comment]
是的，仍存在该问题。

**Comment by xiamengyou** [comment]
> 这应该是 celery 的问题，现在问题依然存在吗？

是的，该问题仍然存在。
