### ISSUE TITLE
[Bug] 复制的命令无法被命令过滤禁用掉

### ISSUE THREAD

**Issue by ilike123** [jumpserver/jumpserver#5403]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.4.1

**浏览器版本**
chrome 87.0.4280.88

**Bug 描述**
复制一条命令，手动添加空格并执行时无法被命令过滤禁用。

**Bug 重现步骤(有截图更好)**
1. 手动输入命令没有问题，加任意空格都会被命令过滤禁用掉。
2. 随便复制一条命令，我测试的时候是用刚刚被禁用掉的命令。
3. 在命令上手动添加空格并执行，命令并不会被命令过滤禁用。（如果不加空格是会禁用的）
4. 再次执行刚刚添加空格后的命令，成功被禁用掉。
![image](https://user-images.githubusercontent.com/37267878/104154593-3e8c4980-5420-11eb-8868-569e63a0c075.png)

**Comment by LeeEirc** [comment]
@ilike123 命令解析已经进行优化，请使用v2.7.0测试下，有问题，再反馈。
