### ISSUE TITLE
docker安装后无法创建用户

### ISSUE THREAD

**Issue by sakufo** [jumpserver/jumpserver#541]
创建用户一直报以下错误：

Request Method: | POST
-- | --
http://10.0.4.22:8080/users/user/create
1.11.3
AttributeError
'str' object has no attribute 'decode'
/opt/jumpserver/apps/users/models/user.py in generate_reset_token, line 192
/usr/bin/python
3.6.1
['/opt/jumpserver/apps',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']

应该是smtp配置引起的，我已经修改config.py文件，提交后重启了相应容器和run_server.py。哪位大神解救一下我。以下是容器内/opt/jumpserver/config.py关于邮件部分的配置：
    # Email SMTP setting, we only support smtp send mail
    EMAIL_HOST = 'smtp.exmail.qq.com'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = 'admin@aojuedu.com'
    EMAIL_HOST_PASSWORD = 'xxxxxx'
    # EMAIL_USE_SSL = False  # If port is 465, set True
    # EMAIL_USE_TLS = False  # If port is 587, set True
    # EMAIL_SUBJECT_PREFIX = '[Jumpserver] '

    CAPTCHA_TEST_MODE = False

**Comment by ibuler** [comment]
/opt/jumpserver/apps/users/models/user.py in generate_reset_token, line 192 这里有bug

**Comment by sakufo** [comment]
创建用户的时候强制要求邮件发送密码，连个选择都不给用户
问题是发也发不出去，安装文档里也不提怎么解决。完全没法用，还不如老版本

**Comment by ibuler** [comment]
发布出去可以重设密码

**Comment by sakufo** [comment]
不能提交，提交直接报python错误
返回后创建的用户也不存在，所以也没法重设密码。

**Comment by ibuler** [comment]
稍等，现在修复

**Comment by sakufo** [comment]
ok后麻烦回复一下，感谢。

**Comment by ibuler** [comment]
已修复，只不过没有提交到docker，不知道你是否是手动安装的

**Comment by sakufo** [comment]
能加个微信么？23927235
我是docker安装的，我手动安装的时候无法初始化数据库，见我的上一个问题“mysql_config”

**Comment by ibuler** [comment]
ok,我可以帮助你手动安装，你安装成功后，写一篇文章介绍一下如何手动安装，可好？

**Comment by ibuler** [comment]
从qq群里 加我 qq吧

**Comment by sakufo** [comment]
还有群，群号在哪儿找？

**Comment by sakufo** [comment]
好的，写文章没问题哦

**Comment by ibuler** [comment]
qq群： 552054376
