### ISSUE TITLE
[Feature] 建议新增将系统的操作日志和登录等日志发送至外置的syslog日志服务器功能

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5412]
**请描述您的需求或者改进建议.**
现在的系统产生的操作日志和登录日志均在服务器本地存储，若本地日志被恶意删除将无法进行追溯，建议新增一个外置的syslog日志接收的功能，将日志实时发送到外部的syslog日志服务器上。

**Comment by wojiushixiaobai** [comment]
有的，参考下参数说明文档

**Comment by aiaiduo** [comment]
> 有的，参考下参数说明文档
> 
> ```shell
> vi /opt/jumpserver/config/config.txt
> ```
> 
> ```viml
> SYSLOG_ADDR=192.168.0.1          # syslog 的地址，多个地址逗号隔开(,)
> ```

已看到，还能否增加一个自定义syslog发送的端口号的参数，因为syslog日志服务器要区分下发送的设备的端口号，这个默认的应该是udp514吧。

**Comment by ibuler** [comment]
SYSLOG_ADDR=192.168.0.1:514

**Comment by aiaiduo** [comment]
> SYSLOG_ADDR=192.168.0.1:514
收到，多谢！

**Comment by aiaiduo** [comment]
> SYSLOG_ADDR=192.168.0.1:514

我加了端口号后再从2.6.2直接升级到2.8.2时就报错，报错信息看这2张图片，我把/opt/jumpserver/config/config.txt中的SYSLOG_ADDR=192.168.0.1:514中的：514端口给删掉后就不报错了，麻烦给看下这个后面要怎么配置，我是想要在syslog服务器后面跟上特殊的端口。
![image](https://user-images.githubusercontent.com/28044296/111935427-712c7f80-8afe-11eb-94f8-c9f8660883c2.png)
![image](https://user-images.githubusercontent.com/28044296/111935439-77226080-8afe-11eb-8314-bef32f4e95bf.png)

**Comment by liukai-ops** [comment]
这个syslog,中包含web terminal 的日志记录么，如果不包括的话，如何配置web terminal 日志到rsyslog 服务器

**Comment by BaiJiangJie** [comment]
目前 SYSLOG_ADDR 不支持多服务的配置。
单服务配置请使用：SYSLOG_ADDR=host:port 格式。
