### ISSUE TITLE
[Bug] 2.6.1版本Port out of range 0-65535

### ISSUE THREAD

**Issue by reformc** [jumpserver/jumpserver#5416]
下载了quick_start.sh，
安装使用了外部mysql和redis，
使用jmsctl.sh start启动提示：
jms_core is up-to-date

ERROR: for guacamole  Container "853b9a565f50" is unhealthy.

ERROR: for luna  Container "853b9a565f50" is unhealthy.

ERROR: for celery  Container "853b9a565f50" is unhealthy.

ERROR: for lina  Container "853b9a565f50" is unhealthy.

ERROR: for koko  Container "853b9a565f50" is unhealthy.
ERROR: Encountered errors while bringing up the project.

执行docker logs -f jms_core --tail 200提示：

  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1034, in from_url
    'port': int(url.port or 6379),
  File "/usr/local/lib/python3.8/urllib/parse.py", line 176, in port
    raise ValueError("Port out of range 0-65535")
ValueError: Port out of range 0-65535

redis我已经检查过端口和密码是可用的

**Comment by reformc** [comment]
执行docker logs -f jms_core --tail 200提示

**Comment by ibuler** [comment]
查看配置文件中的 REDIS_PORT 位置: /opt/jumpserver/config/config.txt
