### ISSUE TITLE
启动脚本报错./jmsctl.sh start

### ISSUE THREAD

**Issue by xiaochende01** [jumpserver/jumpserver#5425]
安装成功，启动脚本报错
[root@VM-48-5-centos jumpserver-installer-v2.6.1]# ./jmsctl.sh start
Pulling core (jumpserver/core:v2.4.5)...
ERROR: manifest for jumpserver/core:v2.4.5 not found

**Comment by ibuler** [comment]
镜像拉取失败

**Comment by jym503558564** [comment]
@xiaochende01 现在是否能部署成功？

**Comment by xiaochende01** [comment]
可以部署成功。换成最新版本就行了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午2:36
收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送:&nbsp;"▍▋|/°兲閊"<281678445@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] 启动脚本报错./jmsctl.sh start (#5425)





 
@xiaochende01 现在是否能部署成功？
