### ISSUE TITLE
[Bug] VNC连接不上

### ISSUE THREAD

**Issue by superhyp** [jumpserver/jumpserver#5428]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.61  v2.62

**浏览器版本**
chrome 87

**Bug 描述**
ssh和rdp都可连接上，vnc一直连接不上，
在windows上安装vnc server，使用vncviewer等可以正常连接，
macos使用vncviewer等可以正常连接，
jumpserver无法连接

**Bug 重现步骤(有截图更好)**
1.  
![微信截图_20210115181745](https://user-images.githubusercontent.com/65394834/104712877-18d3ad00-575e-11eb-9ace-6fe2a3b2da78.png)
![2](https://user-images.githubusercontent.com/65394834/104712890-1c673400-575e-11eb-9943-412c26f41ea1.png)

2. 
3. 
![微信截图_20210116101943](https://user-images.githubusercontent.com/65394834/104794718-6a267f80-57e4-11eb-84da-6d5c7fd7743c.png)

**Comment by superhyp** [comment]
从jms_all 1.4.10测试到 2.6.2 都不行，

**Comment by superhyp** [comment]
使用guacamole/guacd原版docker部署，配置好centos和macos的vnc后可以正常连接上。
现在确认应该是jumpserver连接vnc的问题，不是我这边环境的问题

**Comment by superhyp** [comment]
我测试了所有的jms_all的docker包，没有一个版本能连上vnc的

**Comment by superhyp** [comment]
原来是jumpserver中vnc不支持手动登陆，系统用户中只能选择自动登陆才可以

**Comment by reyleon** [comment]
> 原来是jumpserver中vnc不支持手动登陆，系统用户中只能选择自动登陆才可以

请问一下，您是可以在jumpserver通过 vnc 连上 macOS 吗？
为什么我连不上呢，我的macOS 也是 10.14.6，自带的vnc服务（屏幕共享）
