### ISSUE TITLE
已经存在的系统用户无法更新

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#543]
<img width="1180" alt="qq20170717-013949 2x" src="https://user-images.githubusercontent.com/8543865/28249907-3282f7b4-6a91-11e7-9cd5-bd78c802de11.png">

<img width="1171" alt="qq20170717-014426 2x" src="https://user-images.githubusercontent.com/8543865/28249923-80273160-6a91-11e7-980c-7e27bd58c9e5.png">

**Comment by ibuler** [comment]
更新内容了码?

**Comment by zsjohny** [comment]
@ibuler  这个是之前执行成功 的  正常点再次执行或通过 再次授权都能触发 但是 上面这次 并没有触发 然而后台日志显示 生成密钥 什么的都是成功的

**Comment by ibuler** [comment]
好吧，没有触发更新的动作

https://github.com/jumpserver/jumpserver/blob/dev/apps/assets/views/system_user.py#L64-L80

**Comment by ibuler** [comment]
fixed
