### ISSUE TITLE
[Question] 为什么2.6.2的安装脚本，下载的还是2.6.1版本的包

### ISSUE THREAD

**Issue by Vince--** [jumpserver/jumpserver#5430]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/10022221/104740677-2e0f0280-5783-11eb-8676-00cd0517eaa3.png)
这样岂不是还是有bug，只是版本号变了，里面的tar包还是老的

**Comment by zgao264** [comment]
2.6.2 和 2.6.1 安装脚本是一样的，最终还是拉取的2.6.2的镜像。

**Comment by ibuler** [comment]
可能是有bug了，已修复
