### ISSUE TITLE
域名登录

### ISSUE THREAD

**Issue by shupian235** [jumpserver/jumpserver#5431]
**请描述您的需求或者改进建议.**
希望增加ssh 域名登录 以及增加 SSH 登录域名和授权用户不不必导入key 识别用户名和域名端口 进行SSH 登录

**Comment by ibuler** [comment]
是支持 ssh 域名登录的，使用密码登录，使用密钥登录

**Comment by shupian235** [comment]
可以做个 授权登录吗 不用导入key 用户直接读取服务器里面的密钥进行登录
