### ISSUE TITLE
更改操作日志以及字符审计的存放位置[Feature] 

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#5436]
**请描述您的需求或者改进建议.**

建议日志以及字符审计内容通过其他方式存放，目前存放在mysql数据中的情况下，升级过程中如果用户数据量大的情况下，每次备份的时间以及数据占用的大小都比较大。

**Comment by ibuler** [comment]
命令是支持存储到 elasticsearch 的，请配置
