### ISSUE TITLE
当前版本的api有没有使用文档呢？

### ISSUE THREAD

**Issue by sadlar** [jumpserver/jumpserver#544]
想测试下api的简单流程，以后准备和其他管理平台做对接，目前卡在token获取到之后，使用request 带token的方式获取数据报错 信息为 “错误的token" 在源码里 也没有找到相关的注解

**Comment by hellorocky** [comment]
参考这个视频 , 里面有提到 https://v.douyu.com/show/x0zZVvPQmRY7O4E2

**Comment by sadlar** [comment]
多谢 非常有用
