### ISSUE TITLE
之前是一键安装261的如何升级到262

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#5444]
**请描述您的问题.**
之前是一键安装261版本的

一键安装 JumpServer
curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.6.1/quick_start.sh | sh

如何能一键升级到262呢？

**Comment by mrpretext886** [comment]
cd /opt/jumpserver-installer-v2.6.1/
./jmsctl.sh check_update


> **请描述您的问题.**
> 之前是一键安装261版本的
> 
> 一键安装 JumpServer
> curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.6.1/quick_start.sh | sh
> 
> 如何能一键升级到262呢？

**Comment by luweijun1992** [comment]
> **请描述您的问题.**
> 之前是一键安装261版本的
> 
> 一键安装 JumpServer
> curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.6.1/quick_start.sh | sh
> 
> 如何能一键升级到262呢？

cd /opt/jumpserver-installer-v2.6.1/
./jmsctl.sh check_update

**Comment by enthanlee** [comment]
./jmsctl.sh check_update检测到可以升级2.6.2
但是确认后实际还是升级2.6.1，也就是说实际不能升级。
[root@localhost jumpserver-installer-v2.6.1]# ./jmsctl.sh check_update
最新版本是: v2.6.2
当前版本是: v2.6.1

你确定要升级到 v2.6.2 版本吗? (y/n)  (默认为n): y

1. 检查配置变更
完成

2. 检查程序文件变更
完成

3. 升级镜像文件
[jumpserver/redis:6-alpine]
6-alpine: Pulling from jumpserver/redis
Digest: sha256:4920debee18fad71841ce101a7867743ff8fe7d47e6191b750c3edcfffc1cb18
Status: Image is up to date for jumpserver/redis:6-alpine
docker.io/jumpserver/redis:6-alpine

[jumpserver/mysql:5]
5: Pulling from jumpserver/mysql
Digest: sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd
Status: Image is up to date for jumpserver/mysql:5
docker.io/jumpserver/mysql:5

[jumpserver/nginx:alpine2]
alpine2: Pulling from jumpserver/nginx
Digest: sha256:d25ed0a8c1b4957f918555c0dbda9d71695d7b336d24f7017a87b2081baf1112
Status: Image is up to date for jumpserver/nginx:alpine2
docker.io/jumpserver/nginx:alpine2

[jumpserver/luna:v2.6.1]
v2.6.1: Pulling from jumpserver/luna
Digest: sha256:6889bc5825c8b608d3d086fa6713da5098665d9caaa6de0d2de2e30f27246fa4
Status: Image is up to date for jumpserver/luna:v2.6.1
docker.io/jumpserver/luna:v2.6.1

[jumpserver/core:v2.6.1]
v2.6.1: Pulling from jumpserver/core
Digest: sha256:1332e03847e45f1995845e1b74f1f3deb1f108da72ac5b8af087bc3775690e7b
Status: Image is up to date for jumpserver/core:v2.6.1
docker.io/jumpserver/core:v2.6.1

[jumpserver/koko:v2.6.1]
v2.6.1: Pulling from jumpserver/koko
Digest: sha256:242e96c7a992bf44ccbda321fb69c8ea4d39d5ff423cf8f1505e9856b1ac2496
Status: Image is up to date for jumpserver/koko:v2.6.1
docker.io/jumpserver/koko:v2.6.1

[jumpserver/guacamole:v2.6.1]
v2.6.1: Pulling from jumpserver/guacamole
Digest: sha256:cb80c430c14ad220edd6f20855da5f7ea256d75f5f87bebe29d7e27275c4beeb
Status: Image is up to date for jumpserver/guacamole:v2.6.1
docker.io/jumpserver/guacamole:v2.6.1

[jumpserver/lina:v2.6.1]
v2.6.1: Pulling from jumpserver/lina
Digest: sha256:8d63a0716558b4384f0eab2220bcfefe5ba2e040cbd33634576ba444c215212a
Status: Image is up to date for jumpserver/lina:v2.6.1
docker.io/jumpserver/lina:v2.6.1

完成
4. 备份数据库
正在备份...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
备份成功! 备份文件已存放至: /opt/jumpserver/db_backup/jumpserver-2021-01-18_09:52:35.sql.gz

5. 进行数据库变更
表结构变更可能需要一段时间，请耐心等待 (请确保数据库在运行)
2021-01-18 09:52:36 Collect static files
2021-01-18 09:52:36 Collect static files done
2021-01-18 09:52:36 Check database structure change ...
2021-01-18 09:52:36 Migrate model change to database ...

472 static files copied to '/opt/jumpserver/data/static'.
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
完成

6. 升级成功, 可以重启程序了
./jmsctl.sh restart

**Comment by mrpretext886** [comment]
我刚升级的，升级成功，但是https://IP+8443&nbsp;不能直接跳转，http://IP+8080正常

**Comment by luweijun1992** [comment]
> 我刚升级的，升级成功，但是https://IP+8443&nbsp;不能直接跳转，http://IP+8080正常
检查下所有组件是否都正常，jms_nginx 端口映射。

**Comment by mrpretext886** [comment]
> > 我刚升级的，升级成功，但是[https://IP+8443&nbsp;不能直接跳转，http://IP+8080正常](https://IP+8443&nbsp;%E4%B8%8D%E8%83%BD%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC%EF%BC%8Chttp://IP+8080%E6%AD%A3%E5%B8%B8)
> > 检查下所有组件是否都正常，jms_nginx 端口映射。

![image](https://user-images.githubusercontent.com/63313310/104865721-b0f8ae80-5977-11eb-95dd-d71166da096f.png)
都是正常的

**Comment by luweijun1992** [comment]
> > > 我刚升级的，升级成功，但是[https://IP+8443 不能直接跳转，http://IP+8080正常](https://IP+8443%C2%A0%E4%B8%8D%E8%83%BD%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC%EF%BC%8Chttp://IP+8080%E6%AD%A3%E5%B8%B8)
> > > 检查下所有组件是否都正常，jms_nginx 端口映射。
> 
> ![image](https://user-images.githubusercontent.com/63313310/104865721-b0f8ae80-5977-11eb-95dd-d71166da096f.png)
> 都是正常的

不行就restart看看。8443端口是通的吗

**Comment by mrpretext886** [comment]
> > > > 我刚升级的，升级成功，但是[https://IP+8443 不能直接跳转，http://IP+8080正常](https://IP+8443%C2%A0%E4%B8%8D%E8%83%BD%E7%9B%B4%E6%8E%A5%E8%B7%B3%E8%BD%AC%EF%BC%8Chttp://IP+8080%E6%AD%A3%E5%B8%B8)
> > > > 检查下所有组件是否都正常，jms_nginx 端口映射。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/63313310/104865721-b0f8ae80-5977-11eb-95dd-d71166da096f.png)
> > 都是正常的
> 
> 不行就restart看看。8443端口是通的吗

端口当然是通的只是需要加路径访问，不会直接跳转，http 8080访问正常，jms_nginx 包括服务，都重启个过，无效

**Comment by luweijun1992** [comment]
> 端口当然是通的只是需要加路径访问，不会直接跳转，http 8080访问正常，jms_nginx 包括服务，都重启个过，无效

其他人访问也是一样情况吗。浏览器换个，清理下缓存看看。

**Comment by mrpretext886** [comment]
所有浏览器都试过了~这点判断还是有的~！！

**Comment by ibuler** [comment]
不能跳转是怎样的体现呢？

**Comment by mrpretext886** [comment]
无法打开页面，



---原始邮件---
发件人: "老广"<notifications@github.com&gt;
发送时间: 2021年1月19日(周二) 中午1:23
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送: "mrpretext886"<6555591@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [jumpserver/jumpserver] 之前是一键安装261的如何升级到262 (#5444)




 
不能跳转是怎样的体现呢？

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/104997091-fa262c80-5a63-11eb-8662-c00586dab358.png)

浏览器告警而已

**Comment by jym503558564** [comment]
@sshnuke3 关于升级请参考文档升级 https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/
