### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by brunochen980** [jumpserver/jumpserver#5445]
docker 镜像什么时候推2.6.2/2.5.4/2.4.5 以上的版本
1.15发布的漏洞通知
目前docker还没有对应版本的镜像

**Comment by ibuler** [comment]
docker 上更改了名称，由之前的 jumpserver/jms_core 更改为 jumpserver/core，具体可以参考 docker hub的说明，v2.6 以后做了安装部署的调整，避免社区和企业版的安装撕裂

**Comment by dbrifox** [comment]
I can't find the version 2.4.5 on https://hub.docker.com/r/jumpserver/jms_mysql how can I use this version?
