### ISSUE TITLE
[Question]之前安装的是 Version 1.5.6-2 GPLv2. 可否直接升级到v2.6.2 ？

### ISSUE THREAD

**Issue by yangtea** [jumpserver/jumpserver#5450]
**请描述您的问题.**
如题：之前安装的是 Version 1.5.6-2 GPLv2. 可否直接升级到v2.6.2 ？
升级步骤过程是？

**Comment by ibuler** [comment]
可以直接升级，只不过从 v2.6 开始，统一了社区和企业的安装方式，略微变化，数据库是可以直接使用的，唯一的就是配置文件变化
参考 https://docs.jumpserver.org/zh/master/admin-guide/upgrade/upgrade/

**Comment by wojiushixiaobai** [comment]
@yangtea 如果升级过程中遇到无法解决的问题我们提供远程技术支持。可以通过官方QQ群找到我们
