### ISSUE TITLE
[Feature] docker镜像如何升级到最新

### ISSUE THREAD

**Issue by dislazy** [jumpserver/jumpserver#5451]
***jumpserver已升级到2.6.2但是dockerhub中的镜像仍然维持在2.5.3***
希望版本发布时维持docker镜像，感谢

**Comment by BigbigY** [comment]
遇到同样的问题，之前升级都是改个版本号就完事了，现在镜像貌似都改名，不维护原来那套，我现在是部署在kubernetes中，现在升级有点问题

**Comment by ibuler** [comment]
新版本统一了社区版和商业版本，docker 可以拉去下来 docker tag 一下

**Comment by dislazy** [comment]
无法再打包到一个镜像中对吗

**Comment by ibuler** [comment]
all in one 吗？

**Comment by dislazy** [comment]
对的  all in one

**Comment by ibuler** [comment]
all in one 只是一个测试运行的，后续不再打算维护了

**Comment by dislazy** [comment]
好的  这样的话  容器数量还比较的多  我的低配服务器一运行起来就挂
