### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 297242448** [jumpserver/jumpserver#5458]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
360安全浏览器

**Bug 描述**
跳板机危险命令告警发送邮件失败

**Bug 重现步骤(有截图更好)**
1.  系统设置->邮件设置->测试连接，测试邮件发送正常
2. 资产管理->命令过滤->添加高危命令
3. 执行高危命令，查看邮箱，无邮件
4. 查看日志：2021-01-18 15:12:30 [tasks ERROR] Sending mail error: Header values can't contain newlines (got '跳板机危险命令告警: [xxx (xxx)->Web Terminal@10.170.172.143] $sy\r\n<D05_CE6855_37U_14>system-view' for header 'Subject')

**Comment by ibuler** [comment]
已处理 https://github.com/jumpserver/jumpserver/pull/5460

**Comment by ibuler** [comment]
等待 release
