### ISSUE TITLE
SESSION_COOKIE_AGE导致从登录就开始计算超时时间

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5466]
管理员登录后，即使一直在页面做操作，到期（SESSION_COOKIE_AGE指定的时间）后，会自动登出（无资产连接）。对于普通用户也是。
正常的逻辑应该是不操作以后的空闲时间作为超时退出的时间。

**Comment by ibuler** [comment]
今天我想了一下，设置 1分钟可能存在问题，我们的逻辑是  用户操作后，30s 后刷新 session，如果 用户一直操作，可能就一直没有刷新

**Comment by xyziven** [comment]
1分钟是为了方便测试，设成10分钟和半小时也一样。

**Comment by youliyuan-fit2cloud** [comment]
仅刷新页面时会更新超时时间

**Comment by ibuler** [comment]
已修复，下个版本发布
