### ISSUE TITLE
更新用户列表中无法给用户分配 系统审计员角色

### ISSUE THREAD

**Issue by byronjxb** [jumpserver/jumpserver#5481]
版本：Version v2.6.2 GPLv2
浏览器：谷歌、360极速浏览器
问题：
用户列表无法给用户分配 系统审计员 角色。添加后提示成功，但控制台 角色组名显示为空

**Comment by byronjxb** [comment]
需要在下个版本解决吗？？

**Comment by jym503558564** [comment]
@byronjxb 没有复现
![image](https://user-images.githubusercontent.com/40739051/105272305-0df0a080-5bd4-11eb-8312-0c959c7f33ab.png)
![image](https://user-images.githubusercontent.com/40739051/105272374-2f518c80-5bd4-11eb-8b3f-d6b8cdc8d31d.png)

**Comment by byronjxb** [comment]
发现针对用户分组、或者在用户组里添加用户，提示成功，实际是没有添加进去。
![image](https://user-images.githubusercontent.com/21222280/105318780-e9f68480-5bfe-11eb-8ebd-2a54d9f049df.png)
![image](https://user-images.githubusercontent.com/21222280/105318823-f549b000-5bfe-11eb-98f4-9d1e9fd43203.png)

**Comment by byronjxb** [comment]
或者说 给用户添加 审计员角色后就无法添加到新的分组里

**Comment by jym503558564** [comment]
之前审计员确实存在该问题，审计员不能加入用户组。
