### ISSUE TITLE
[Bug] 建议修改表：terminal_command的input和output字段长度

### ISSUE THREAD

**Issue by leonpenn** [jumpserver/jumpserver#5493]
**升级JumpServer 2.6.2：在恢复数据到自建数据库MySQL 8.0.23时，报错，提示插入字段过长**

问题现场如下：
./jmsctl.sh restore_db /root/jumpserver.sql
开始还原数据库: /root/jumpserver.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1406 (22001) at line 2423: Data too long for column 'input' at row 74
read unix @->/var/run/docker.sock: read: connection reset by peer
 数据库恢复失败,请检查数据库文件是否完整，或尝试手动恢复！

./jmsctl.sh restore_db /root/jumpserver.sql
开始还原数据库: /root/jumpserver.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1406 (22001) at line 2423: Data too long for column 'output' at row 897
read unix @->/var/run/docker.sock: read: connection reset by peer
 数据库恢复失败,请检查数据库文件是否完整，或尝试手动恢复！

建议：
默认input、output字段过小，建议修改两者的长度：
  `input` varchar(1024) NOT NULL,
  `output` varchar(4096) NOT NULL
并指定前缀索引长度：
例如：KEY `terminal_command_input_9acfd946` (input(32))

**Comment by ibuler** [comment]
这个是由于编码更换导致的吗？

**Comment by ibuler** [comment]
指定索引长度这个 Django 可能无法实现，因为 Django 是面向对数据库的，你可以尝试手动改变 MySQL 的索引长度
