### ISSUE TITLE
最新远程命令执行漏洞修复版本没有在dockerhub中同步？

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#5494]
**请描述您的问题.**
最新的远程命令执行漏洞修复版本我看在dockerhub中没有同步，最新的是2.5.3版本的基础镜像，由于好多生产环境都是使用的容器构建，请官方抓紧时间同步dockerhub上的基础镜像jumpserver/jms_all

**Comment by wojiushixiaobai** [comment]
@Hello-Linux 请使用升级文档 https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

**Comment by Hello-Linux** [comment]
这样不合适吧，毕竟是容器化部署的，依靠k8s管理，对于应用的升级本应该是基础镜像的升级，而不是让客户自己手动升级镜像包，

**Comment by ibuler** [comment]
是容器话部署的，那个快速安装中只不过是封装到 docker compose，如果你部署到了 k8s 肯定能看懂的 https://github.com/jumpserver/installer

**Comment by ibuler** [comment]
并且为了区分和之前的不同，我们更改了名称 https://hub.docker.com/repository/docker/jumpserver/core

**Comment by Hello-Linux** [comment]
@ibuler  您更改的这个项目名称(https://hub.docker.com/repository/docker/jumpserver/core)只是jumpserver的组件之一吧,跟jms_all不一样吧

**Comment by Hello-Linux** [comment]
如果我现在想要升级jumpserver的基础镜像该如何升级呢?我们现在使用的是v2.5.2版本的基础镜像，我看install支持的是2.6.0版本

**Comment by wojiushixiaobai** [comment]
@Hello-Linux 可以直接参考官方升级文档
