### ISSUE TITLE
Authenticator无法绑定两套jumpserver多因子认证

### ISSUE THREAD

**Issue by MRwangyd** [jumpserver/jumpserver#5498]
我部署了两套jumpserver，使用Authenticator只能扫码绑定一个，绑定第二个的时候第一个被覆盖了。只能使用多因子登录最后一次扫描绑定的jumpserver
使用Authenticator为Microsoft Authenticator

**Comment by wojiushixiaobai** [comment]
@MRwangyd 更换名称，同名会被覆盖
参数文档说明文档里面有

**Comment by MRwangyd** [comment]
感谢 @wojiushixiaobai 的回答，我从官网上找到了参数配置。
但是在jumpserver-installer-v2.6.2的过程中，在jumpserver-installer-v2.6.2/config-example.txt 和/opt/jumpserver/config/config.txt 中没有找到OTP_ISSUER_NAME参数，直接添加到文件中就可以么？

![image](https://user-images.githubusercontent.com/27405334/105270120-324a7e00-5bd0-11eb-99e2-5e74cd257ddf.png)

**Comment by ibuler** [comment]
是的，直接填写即可

**Comment by MRwangyd** [comment]
已经修改并生效，谢谢 @ibuler @wojiushixiaobai
