### ISSUE TITLE
[Question] v1.4.10升级v.2.6.2  jmsctl.sh start失败

### ISSUE THREAD

**Issue by areswxin** [jumpserver/jumpserver#5499]
**请描述您的问题.**
v1.4.10升级v.2.6.2，参考文档https://docs.jumpserver.org/zh/master/admin-guide/upgrade/upgrade/操作，执行完jmsctl.sh install之后，config.txt文件也生成了，同时生成了core  koko  nginx 三个目录，在 jmsctl.sh start的时候报错。
ERROR: for jms_core  Cannot start service core: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/opt/jumpserver/config/core/config.yml\\\" to rootfs \\\"/data/docker/overlay2/bccc7134355da9297b10c0be0dcf46bf4d8a1cce91fea21db2242959be4a364b/merged\\\" at \\\"/data/docker/overlay2/bccc7134355da9297b10c0be0dcf46bf4d8a1cce91fea21db2242959be4a364b/merged/opt/jumpserver/config.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for core  Cannot start service core: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/opt/jumpserver/config/core/config.yml\\\" to rootfs \\\"/data/docker/overlay2/bccc7134355da9297b10c0be0dcf46bf4d8a1cce91fea21db2242959be4a364b/merged\\\" at \\\"/data/docker/overlay2/bccc7134355da9297b10c0be0dcf46bf4d8a1cce91fea21db2242959be4a364b/merged/opt/jumpserver/config.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
查看core目录下生成了config.yml目录。并未生成config.yml配置，麻烦问下这个配置需要自己提前创建吗，是从v1.4.10的jump目录下拷贝过来么

**Comment by areswxin** [comment]
config_init目录中生成的config.yml也是空的

**Comment by areswxin** [comment]
新建config.yml启动成功，但是发现web登录，选中服务器502，luna 容器也没看到错误日志

**Comment by areswxin** [comment]
同步进度，config.txt中添加了CORE_HOST，现在web页面可以打开了，但是之前的认证信息没了，需要从新输入密码

**Comment by areswxin** [comment]
同步进度,发现使用jmsctl.sh install生成的SECRET_KEY还有BOOTSTRAP_TOKEN与 config-example.txt 中配置的不一样，手工更改，重启后web登录正常

**Comment by areswxin** [comment]
同步进度,ssh登录需要重置密钥才可以

**Comment by wojiushixiaobai** [comment]
@areswxin 2333.我现在才看到，都在群里回消息了抱歉。已经处理完毕了嘛？更新文档里面已经更新了详细的操作说明，如果有问题的话可以联系我们。

**Comment by areswxin** [comment]
现在发现一个问题，重置mfa失败，点击重置按钮会有一个401的错误，日志如下2021-01-25 13:50:19 [log WARNING] Unauthorized: /api/v1/users/users/61a6b545-01b0-4k39-a25e-cdbbb5fd2366/otp/reset/，没有看到其他明显的报错，麻烦问下这个报错怎么排查下~。~

**Comment by jym503558564** [comment]
@areswxin 如果升级依然失败，可qq群联系武汉小白。
