### ISSUE TITLE
luna table 开超过六个会卡死

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#550]
日志正常 只是 窗口卡死

**Comment by ibuler** [comment]
浏览器卡死？可以描述的更清楚些

**Comment by zsjohny** [comment]
@ibuler  左边不是 资产么 正常点 资产 会弹出登录的server ，点一次新建一个table，超过六个，第七个table 就是黑的

**Comment by ibuler** [comment]
测试了，确实有该问题  @zxysofia

**Comment by zsjohny** [comment]
@ibuler  请标记为bug

**Comment by ibuler** [comment]
这个应该是后端问题，不是前端的问题，我尝试在两个窗口里打开，结果也最多5个，打开第6个需要等半天

**Comment by ibuler** [comment]
这个确认了，是chrome的问题，一个页面最多打开5个

**Comment by liuzheng** [comment]
这个问题已经fix了，需要配合新版本的coco，luna的这个fix我还没release发布，关注一下吧https://github.com/jumpserver/luna/releases
