### ISSUE TITLE
[Bug] web终端无法连接部分RDP主机

### ISSUE THREAD

**Issue by LeonLiu0804** [jumpserver/jumpserver#5500]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome 版本 72.0.3626.119（正式版本） 

**Bug 描述**

部分资产（windows 2012）rdp无法连接（Guacamole 1.5.2），没有特别的错误log，
通过其他同网段主机远程连接目标资产可以连接，通过堡垒机连接还是刷新不出远程页面，但是可以把之前已经成功连接的主机挤出去。
页面弹出的错误弹框是
"连接错误 远程桌面服务器不在线，如果问题持续，请通知您的系统管理员，或检测您的系统日志。"

**Bug 重现步骤(有截图更好)**
1.   通过运维管理/资产运维/进入
2.   连接目标windows资产（windows2012）
3.    目标资产连接一直无法成功，弹出错误信息弹框“连接错误 远程桌面服务器不在线，如果问题持续，请通知您的系统管理员，或检测您的系统日志。”

![image](https://user-images.githubusercontent.com/25121270/105276050-8575fe00-5bdb-11eb-8963-31b9c4787b5e.png)

![image](https://user-images.githubusercontent.com/25121270/105276117-9b83be80-5bdb-11eb-8ac5-1f966f4cf869.png)

**Comment by LeeEirc** [comment]
@LeonLiu0804 先使用最新的2.6.2版本测试一下？

**Comment by LeonLiu0804** [comment]
服务器部署不在本地，而且目前在使用中，更新版本暂时比较困难。 对了这个是通过docker部署的。
请问这种情况有什么可能的检讨方法和排查方向吗？

**Comment by LeeEirc** [comment]
`docker logs -f jms_guacamole --tail=100 ` 看下有没有什么错误日志吧。主要看guacd开头的日志

**Comment by jym503558564** [comment]
@LeonLiu0804 该问题是否还存在，如还不能正常连接windows 2012. 请查看guacamole的报错日志，截图出来。

**Comment by xiaozhiqi2000** [comment]
@jym503558564 @LeonLiu0804 @LeonLiu0804 我现在也碰到这个问题，winserver2008 正常登录，2012 平台改成windows或者windows 2016 都不好使，一点击资产，马上显示联系管理员。瓜的日志，现贴出来，好像也没有太别异常明显的错误
![image](https://user-images.githubusercontent.com/16703381/111268420-3ba01600-8668-11eb-8d4e-eefbe43dbc4d.png)

**Comment by jym503558564** [comment]
如果该问题还存在，可再次打开Issues，附上guacamole报错日志截图。
