### ISSUE TITLE
[Bug] v2.6.2升级至V2.7.0 sysylog配置的端口报错

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5508]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.7.0
**浏览器版本**

**Bug 描述**
在v26.2版本是在/opt/jumpserver/config/config.txt文件中新增了syslog的配置SYSLOG_ADDR=192.168.0.1:565 但是在由v2.6.2升级至2.7.0 的第5步“进行数据库变更”时报错。
![image](https://user-images.githubusercontent.com/28044296/105430010-86fffe80-5c8d-11eb-91bf-d82d94ff3c21.png)

![image](https://user-images.githubusercontent.com/28044296/105430061-a26b0980-5c8d-11eb-8c35-46e42792d8ba.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
把后面的注释先去掉吧，这个逻辑没有做改动

**Comment by aiaiduo** [comment]
> 把后面的注释先去掉吧，这个逻辑没有做改动

恩恩，好的，我试下，正常有注释应该也不影响吧。

**Comment by jym503558564** [comment]
@aiaiduo 去掉注视，问题还存在吗？

**Comment by aiaiduo** [comment]
![Snipaste_2021-03-02_15-47-43](https://user-images.githubusercontent.com/28044296/109620174-8acc4e00-7b74-11eb-8c06-3b0e6000c68d.png)
![Snipaste_2021-03-02_15-52-10](https://user-images.githubusercontent.com/28044296/109620179-8d2ea800-7b74-11eb-87f1-d6913af80b50.png)
![Snipaste_2021-03-02_15-52-20](https://user-images.githubusercontent.com/28044296/109620182-8e5fd500-7b74-11eb-83b0-565d2024e300.png)
![Snipaste_2021-03-02_15-52-28](https://user-images.githubusercontent.com/28044296/109620185-8ef86b80-7b74-11eb-9005-dd1f4430cbe1.png)
去掉注释，还是有报错。
@jym503558564

**Comment by ibuler** [comment]
看着注释还在啊

**Comment by aiaiduo** [comment]
> 看着注释还在啊
嗯 ，明白了，是要把syslog addr这一行后面的注释删掉，我再试试，

**Comment by jym503558564** [comment]
@aiaiduo问题解决了吗

**Comment by aiaiduo** [comment]
> @aiaiduo问题解决了吗

已经解决了，谢谢！
