### ISSUE TITLE
[Question] v2.7.0 能否强制用户进行CAS认证

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5509]
**请描述您的问题.**
现在2.7.0版本用户配置的CAS认证在用户登录界面时需要手动点CAS认证，能否还像老版本一样强制cas认证的用户强制到cas认证页面，新版本的“用户来源”选择“数据库”或“CAS”在哪里配置，2.7.0在用户基础信息里没有找到“用户来源”的配置，想咨询下2.7.0用户需要CAS认证要在哪里进行配置。
![image](https://user-images.githubusercontent.com/28044296/105430199-f4ac2a80-5c8d-11eb-9623-81eb4840bb47.png)
![image](https://user-images.githubusercontent.com/28044296/105430378-4bb1ff80-5c8e-11eb-826e-8768ef8f44a1.png)
![image](https://user-images.githubusercontent.com/28044296/105430459-87e56000-5c8e-11eb-8674-5d94c4ccbcc4.png)

**Comment by ibuler** [comment]
这次改动是借鉴了  腾讯云 和 阿里云 公有云厂商，因为之前存在这个问题，就是虽然启用了 openid或cas, 但是一些账号还是在数据库中，这样就无法页面登录了

![image](https://user-images.githubusercontent.com/17382885/105438877-d1d64200-5c9e-11eb-9513-9eefc9b423e0.png)

**Comment by ibuler** [comment]
用户来源只是表示用户是从 cas 来的，只是个标记而已，而不会强制用户去那 验证

**Comment by aiaiduo** [comment]
> 用户来源只是表示用户是从 cas 来的，只是个标记而已，而不会强制用户去那 验证

嗯，但是我想让公司内部员工强制从cas认证，外部协作单位在cas里没有账号的还是和之前的版本一样从http://IP/core/auth/login/?admin=1从数据库登录，内部用户在登录页面哪里直接去cas认证然后直接跳转，而不是要手工去选择下CAS认证，这个要怎么配置。

**Comment by aiaiduo** [comment]
@ibuler 麻烦问下用户登录的时候能强制他进行CAS方式认证么，我不想用户进行数据库密码方式登录。

**Comment by ibuler** [comment]
v2.8 强制用户从来源登录

**Comment by aiaiduo** [comment]
> v2.8 强制用户从来源登录

ok，收到！

**Comment by aiaiduo** [comment]
现在我已经升级到2.8.2版本了，用户那里我也设置为CAS认证了，但是登录的时候用默认的登录地址用“数据库”中的认证也可以登录，但是点“更多登录方式”选择cas也可以登录，我还是想默认只能是cas认证登录.
![image](https://user-images.githubusercontent.com/28044296/111937479-c7032680-8b02-11eb-8418-591105bae697.png)
![image](https://user-images.githubusercontent.com/28044296/111937502-d2565200-8b02-11eb-8ab8-05091e03e0b1.png)

**Comment by aiaiduo** [comment]
> v2.8 强制用户从来源登录

@ibuler 
> 现在我已经升级到2.8.2版本了，用户那里我也设置为CAS认证了，但是登录的时候用默认的登录地址用“数据库”中的认证也可以登录，但是点“更多登录方式”选择cas也可以登录，我还是想默认只能是cas认证登录.
> ![image](https://user-images.githubusercontent.com/28044296/111937479-c7032680-8b02-11eb-8418-591105bae697.png)
> ![image](https://user-images.githubusercontent.com/28044296/111937502-d2565200-8b02-11eb-8ab8-05091e03e0b1.png)

**Comment by jym503558564** [comment]
### 可通过修改配置文件：
- `ONLY_ALLOW_EXIST_USER_AUTH: true `   是否仅允许 已创建 的用户登录
-  `ONLY_ALLOW_AUTH_FROM_SOURCE: true` 是否仅允许从 用户来源 处登录
- 根据您的需求，您可配置`ONLY_ALLOW_AUTH_FROM_SOURCE: true`

**Comment by aiaiduo** [comment]
@jym503558564 
这个是要加载/opt/jumpserver/config/config.txt中的CAS部分的后面是吧？如果加在cofnig.txt中是否要改为ONLY_ALLOW_AUTH_FROM_SOURCE=True

**Comment by jym503558564** [comment]
@aiaiduo 是的

**Comment by jym503558564** [comment]
@aiaiduo
