### ISSUE TITLE
[Question] 2.6.2  回话录像的S3存储配置问题

### ISSUE THREAD

**Issue by daxuxu** [jumpserver/jumpserver#5510]
目前使用版本2.6.2，在配置中找不到录像的S3存储配置项目？请问是否已经不支持录像存储在S3上了。

**Comment by ibuler** [comment]
支持的啊
![image](https://user-images.githubusercontent.com/17382885/105440703-05ff3200-5ca2-11eb-8a97-ab3be4d163f9.png)
