### ISSUE TITLE
为什么无法进行Google Auth二次认证?

### ISSUE THREAD

**Issue by yuba316** [jumpserver/jumpserver#5514]
我在登陆JumpServer时莫名其妙要求我进行身份认证。
而按照操作下载了Authenticator后，MFA扫描二维码输入验证码显示：验证码错误或服务器端时间不对。

请问如何解决？

**Comment by LeeEirc** [comment]
查看服务器的时间和手机的时间是否一致，另外管理员开启MFA的情况下，会要求进行身份认证。

**Comment by jym503558564** [comment]
- 管理员查看系统设置-安全设置，是否勾选了多因子认证。
- 另外验证码错误或服务器端时间不对可能是由于服务器时间与手机时间不一致。请自行设置好
- 如还有存在该问题，可再次打开该Issues
