### ISSUE TITLE
[Windows远程问题] 2.7.0版本远程2003和2008R2显示远程桌面服务器不在线，2012正常

### ISSUE THREAD

**Issue by Dragovish** [jumpserver/jumpserver#5517]
版本：2.7.0，全新极速部署模式安装，https模式
问题：远程2003和2008R2显示远程桌面服务器不在线，远程Windows 2012 R2服务器一切正常
![2003](https://user-images.githubusercontent.com/7078962/105580648-933ca680-5dc8-11eb-9d26-20a437d619fe.jpg)
![2008](https://user-images.githubusercontent.com/7078962/105580649-95066a00-5dc8-11eb-9d0c-9e9d21b8372d.jpg)
日志：

guacd[5606]: DEBUG:     guac_rdp_fs_open: path="/", access=0x80000000, file_attributes=0x0, create_disposition=0x1, create_options=0x0
guacd[5606]: DEBUG:     guac_rdp_fs_open: Normalized path "/" to "\".
guacd[5606]: DEBUG:     guac_rdp_fs_open: Translated path "\" to "/config/guacamole/data/drive/e2509283-0e20-42e1-b174-d99239b25226/".
guacd[5606]: DEBUG:     guac_rdp_fs_open: native open: real_path="/config/guacamole/data/drive/e2509283-0e20-42e1-b174-d99239b25226/", flags=0x0
guacd[5606]: DEBUG:     guac_rdp_fs_open: Opened "\" as file_id=0
guacd[5606]: DEBUG:     guac_rdp_fs_close: Closed "\" (file_id=0)
guacd[5606]: DEBUG:     primitives autodetect, using optimized
guacd[5606]: DEBUG:     freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     Error: SSL_NOT_ALLOWED_BY_SERVER
guacd[5606]: DEBUG:     freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     Error: SSL_NOT_ALLOWED_BY_SERVER
guacd[5606]: DEBUG:     freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     ShareCapabilitySet (length 4):
guacd[5606]: DEBUG:             nodeId: 0x03EA
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     GeneralCapabilitySet (length 20):
guacd[5606]: DEBUG:             osMajorType: 0x0001
guacd[5606]: DEBUG:             osMinorType: 0x0003
guacd[5606]: DEBUG:             protocolVersion: 0x0200
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             generalCompressionTypes: 0x0000
guacd[5606]: DEBUG:             extraFlags: 0x041D
guacd[5606]: DEBUG:             updateCapabilityFlag: 0x0000
guacd[5606]: DEBUG:             remoteUnshareFlag: 0x0000
guacd[5606]: DEBUG:             generalCompressionLevel: 0x0000
guacd[5606]: DEBUG:             refreshRectSupport: 0x01
guacd[5606]: DEBUG:             suppressOutputSupport: 0x01
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     VirtualChannelCapabilitySet (length 4):
guacd[5606]: DEBUG:             flags: 0x00000002
guacd[5606]: DEBUG:             VCChunkSize: 0x00000640
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     DrawGdiPlusCacheCapabilitySet (length 36):
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     FontCapabilitySet (length 0):
guacd[5606]: DEBUG:             fontSupportFlags: 0x0000
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     BitmapCapabilitySet (length 24):
guacd[5606]: DEBUG:             preferredBitsPerPixel: 0x0010
guacd[5606]: DEBUG:             receive1BitPerPixel: 0x0001
guacd[5606]: DEBUG:             receive4BitsPerPixel: 0x0001
guacd[5606]: DEBUG:             receive8BitsPerPixel: 0x0001
guacd[5606]: DEBUG:             desktopWidth: 0x0800
guacd[5606]: DEBUG:             desktopHeight: 0x04A5
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:             desktopResizeFlag: 0x0001
guacd[5606]: DEBUG:             bitmapCompressionFlag: 0x0001
guacd[5606]: DEBUG:             highColorFlags: 0x00
guacd[5606]: DEBUG:             drawingFlags: 0x00
guacd[5606]: DEBUG:             multipleRectangleSupport: 0x0001
guacd[5606]: DEBUG:             pad2OctetsB: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     OrderCapabilitySet (length 84):
guacd[5606]: DEBUG:             pad4OctetsA: 0x000F4240
guacd[5606]: DEBUG:             desktopSaveXGranularity: 0x0001
guacd[5606]: DEBUG:             desktopSaveYGranularity: 0x0014
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             maximumOrderLevel: 0x0001
guacd[5606]: DEBUG:             numberFonts: 0x0000
guacd[5606]: DEBUG:             orderFlags: 0x0022
guacd[5606]: DEBUG:             orderSupport:
guacd[5606]: DEBUG:                     DSTBLT: 1
guacd[5606]: DEBUG:                     PATBLT: 1
guacd[5606]: DEBUG:                     SCRBLT: 1
guacd[5606]: DEBUG:                     MEMBLT: 1
guacd[5606]: DEBUG:                     MEM3BLT: 1
guacd[5606]: DEBUG:                     ATEXTOUT: 0
guacd[5606]: DEBUG:                     AEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     DRAWNINEGRID: 1
guacd[5606]: DEBUG:                     LINETO: 1
guacd[5606]: DEBUG:                     MULTI_DRAWNINEGRID: 1
guacd[5606]: DEBUG:                     OPAQUE_RECT: 1
guacd[5606]: DEBUG:                     SAVEBITMAP: 1
guacd[5606]: DEBUG:                     WTEXTOUT: 0
guacd[5606]: DEBUG:                     MEMBLT_V2: 0
guacd[5606]: DEBUG:                     MEM3BLT_V2: 0
guacd[5606]: DEBUG:                     MULTIDSTBLT: 1
guacd[5606]: DEBUG:                     MULTIPATBLT: 1
guacd[5606]: DEBUG:                     MULTISCRBLT: 1
guacd[5606]: DEBUG:                     MULTIOPAQUERECT: 1
guacd[5606]: DEBUG:                     FAST_INDEX: 1
guacd[5606]: DEBUG:                     POLYGON_SC: 1
guacd[5606]: DEBUG:                     POLYGON_CB: 1
guacd[5606]: DEBUG:                     POLYLINE: 1
guacd[5606]: DEBUG:                     UNUSED23: 0
guacd[5606]: DEBUG:                     FAST_GLYPH: 1
guacd[5606]: DEBUG:                     ELLIPSE_SC: 1
guacd[5606]: DEBUG:                     ELLIPSE_CB: 1
guacd[5606]: DEBUG:                     GLYPH_INDEX: 1
guacd[5606]: DEBUG:                     GLYPH_WEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     GLYPH_WLONGTEXTOUT: 0
guacd[5606]: DEBUG:                     GLYPH_WLONGEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     UNUSED31: 0
guacd[5606]: DEBUG:             textFlags: 0x06A1
guacd[5606]: DEBUG:             orderSupportExFlags: 0x0000
guacd[5606]: DEBUG:             pad4OctetsB: 0x000F4240
guacd[5606]: DEBUG:             desktopSaveSize: 0x000F4240
guacd[5606]: DEBUG:             pad2OctetsC: 0x0001
guacd[5606]: DEBUG:             pad2OctetsD: 0x0000
guacd[5606]: DEBUG:             textANSICodePage: 0x0000
guacd[5606]: DEBUG:             pad2OctetsE: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     ColorCacheCapabilitySet (length 4):
guacd[5606]: DEBUG:             colorTableCacheSize: 0x0006
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     BitmapCacheHostSupportCapabilitySet (length 4):
guacd[5606]: DEBUG:             cacheVersion: 0x01
guacd[5606]: DEBUG:             pad1: 0x00
guacd[5606]: DEBUG:             pad2: 0x0000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     PointerCapabilitySet (length 6):
guacd[5606]: DEBUG:             colorPointerFlag: 0x0001
guacd[5606]: DEBUG:             colorPointerCacheSize: 0x0019
guacd[5606]: DEBUG:             pointerCacheSize: 0x0019
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     InputCapabilitySet (length 84)
guacd[5606]: DEBUG:             inputFlags: 0x0035
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             keyboardLayout: 0x00000000
guacd[5606]: DEBUG:             keyboardType: 0x00000000
guacd[5606]: DEBUG:             keyboardSubType: 0xEFDA3F80
guacd[5606]: DEBUG:             keyboardFunctionKey: 0xFFFFFADF
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     RemoteProgramsCapabilitySet (length 4):
guacd[5606]: DEBUG:             railSupportLevel: 0x00000000
guacd[5606]: DEBUG:     Receiving
guacd[5606]: DEBUG:     WindowListCapabilitySet (length 7):
guacd[5606]: DEBUG:             wndSupportLevel: 0x00000000
guacd[5606]: DEBUG:             numIconCaches: 0x00
guacd[5606]: DEBUG:             numIconCacheEntries: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     GeneralCapabilitySet (length 20):
guacd[5606]: DEBUG:             osMajorType: 0x0000
guacd[5606]: DEBUG:             osMinorType: 0x0000
guacd[5606]: DEBUG:             protocolVersion: 0x0200
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             generalCompressionTypes: 0x0000
guacd[5606]: DEBUG:             extraFlags: 0x0415
guacd[5606]: DEBUG:             updateCapabilityFlag: 0x0000
guacd[5606]: DEBUG:             remoteUnshareFlag: 0x0000
guacd[5606]: DEBUG:             generalCompressionLevel: 0x0000
guacd[5606]: DEBUG:             refreshRectSupport: 0x01
guacd[5606]: DEBUG:             suppressOutputSupport: 0x01
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     BitmapCapabilitySet (length 24):
guacd[5606]: DEBUG:             preferredBitsPerPixel: 0x0010
guacd[5606]: DEBUG:             receive1BitPerPixel: 0x0001
guacd[5606]: DEBUG:             receive4BitsPerPixel: 0x0001
guacd[5606]: DEBUG:             receive8BitsPerPixel: 0x0001
guacd[5606]: DEBUG:             desktopWidth: 0x0800
guacd[5606]: DEBUG:             desktopHeight: 0x04A5
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:             desktopResizeFlag: 0x0001
guacd[5606]: DEBUG:             bitmapCompressionFlag: 0x0001
guacd[5606]: DEBUG:             highColorFlags: 0x00
guacd[5606]: DEBUG:             drawingFlags: 0x00
guacd[5606]: DEBUG:             multipleRectangleSupport: 0x0001
guacd[5606]: DEBUG:             pad2OctetsB: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     OrderCapabilitySet (length 84):
guacd[5606]: DEBUG:             pad4OctetsA: 0x00000000
guacd[5606]: DEBUG:             desktopSaveXGranularity: 0x0001
guacd[5606]: DEBUG:             desktopSaveYGranularity: 0x0014
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             maximumOrderLevel: 0x0001
guacd[5606]: DEBUG:             numberFonts: 0x0000
guacd[5606]: DEBUG:             orderFlags: 0x002A
guacd[5606]: DEBUG:             orderSupport:
guacd[5606]: DEBUG:                     DSTBLT: 1
guacd[5606]: DEBUG:                     PATBLT: 0
guacd[5606]: DEBUG:                     SCRBLT: 1
guacd[5606]: DEBUG:                     MEMBLT: 1
guacd[5606]: DEBUG:                     MEM3BLT: 0
guacd[5606]: DEBUG:                     ATEXTOUT: 0
guacd[5606]: DEBUG:                     AEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     DRAWNINEGRID: 0
guacd[5606]: DEBUG:                     LINETO: 0
guacd[5606]: DEBUG:                     MULTI_DRAWNINEGRID: 0
guacd[5606]: DEBUG:                     OPAQUE_RECT: 0
guacd[5606]: DEBUG:                     SAVEBITMAP: 0
guacd[5606]: DEBUG:                     WTEXTOUT: 0
guacd[5606]: DEBUG:                     MEMBLT_V2: 0
guacd[5606]: DEBUG:                     MEM3BLT_V2: 0
guacd[5606]: DEBUG:                     MULTIDSTBLT: 0
guacd[5606]: DEBUG:                     MULTIPATBLT: 0
guacd[5606]: DEBUG:                     MULTISCRBLT: 0
guacd[5606]: DEBUG:                     MULTIOPAQUERECT: 0
guacd[5606]: DEBUG:                     FAST_INDEX: 1
guacd[5606]: DEBUG:                     POLYGON_SC: 0
guacd[5606]: DEBUG:                     POLYGON_CB: 0
guacd[5606]: DEBUG:                     POLYLINE: 0
guacd[5606]: DEBUG:                     UNUSED23: 0
guacd[5606]: DEBUG:                     FAST_GLYPH: 1
guacd[5606]: DEBUG:                     ELLIPSE_SC: 0
guacd[5606]: DEBUG:                     ELLIPSE_CB: 0
guacd[5606]: DEBUG:                     GLYPH_INDEX: 1
guacd[5606]: DEBUG:                     GLYPH_WEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     GLYPH_WLONGTEXTOUT: 0
guacd[5606]: DEBUG:                     GLYPH_WLONGEXTTEXTOUT: 0
guacd[5606]: DEBUG:                     UNUSED31: 0
guacd[5606]: DEBUG:             textFlags: 0x0000
guacd[5606]: DEBUG:             orderSupportExFlags: 0x0000
guacd[5606]: DEBUG:             pad4OctetsB: 0x00000000
guacd[5606]: DEBUG:             desktopSaveSize: 0x00038400
guacd[5606]: DEBUG:             pad2OctetsC: 0x0000
guacd[5606]: DEBUG:             pad2OctetsD: 0x0000
guacd[5606]: DEBUG:             textANSICodePage: 0xFDE9
guacd[5606]: DEBUG:             pad2OctetsE: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     BitmapCacheV2CapabilitySet (length 36):
guacd[5606]: DEBUG:             cacheFlags: 0x0003
guacd[5606]: DEBUG:             pad2: 0x00
guacd[5606]: DEBUG:             numCellCaches: 0x05
guacd[5606]: DEBUG:             bitmapCache0CellInfo: numEntries: 600 persistent: 0
guacd[5606]: DEBUG:             bitmapCache1CellInfo: numEntries: 600 persistent: 0
guacd[5606]: DEBUG:             bitmapCache2CellInfo: numEntries: 2048 persistent: 0
guacd[5606]: DEBUG:             bitmapCache3CellInfo: numEntries: 4096 persistent: 0
guacd[5606]: DEBUG:             bitmapCache4CellInfo: numEntries: 2048 persistent: 0
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     PointerCapabilitySet (length 6):
guacd[5606]: DEBUG:             colorPointerFlag: 0x0001
guacd[5606]: DEBUG:             colorPointerCacheSize: 0x0014
guacd[5606]: DEBUG:             pointerCacheSize: 0x0014
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     InputCapabilitySet (length 84)
guacd[5606]: DEBUG:             inputFlags: 0x003D
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:             keyboardLayout: 0x00000409
guacd[5606]: DEBUG:             keyboardType: 0x00000004
guacd[5606]: DEBUG:             keyboardSubType: 0x00000000
guacd[5606]: DEBUG:             keyboardFunctionKey: 0x0000000C
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     BrushCapabilitySet (length 4):
guacd[5606]: DEBUG:             brushSupportLevel: 0x00000002
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     GlyphCacheCapabilitySet (length 48):
guacd[5606]: DEBUG:             glyphCache0: Entries: 254 MaximumCellSize: 4
guacd[5606]: DEBUG:             glyphCache1: Entries: 254 MaximumCellSize: 4
guacd[5606]: DEBUG:             glyphCache2: Entries: 254 MaximumCellSize: 8
guacd[5606]: DEBUG:             glyphCache3: Entries: 254 MaximumCellSize: 8
guacd[5606]: DEBUG:             glyphCache4: Entries: 254 MaximumCellSize: 16
guacd[5606]: DEBUG:             glyphCache5: Entries: 254 MaximumCellSize: 32
guacd[5606]: DEBUG:             glyphCache6: Entries: 254 MaximumCellSize: 64
guacd[5606]: DEBUG:             glyphCache7: Entries: 254 MaximumCellSize: 128
guacd[5606]: DEBUG:             glyphCache8: Entries: 254 MaximumCellSize: 256
guacd[5606]: DEBUG:             glyphCache9: Entries: 64 MaximumCellSize: 256
guacd[5606]: DEBUG:             fragCache: Entries: 256 MaximumCellSize: 256
guacd[5606]: DEBUG:             glyphSupportLevel: 0x0002
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     VirtualChannelCapabilitySet (length 8):
guacd[5606]: DEBUG:             flags: 0x00000000
guacd[5606]: DEBUG:             VCChunkSize: 0x00000640
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     SoundCapabilitySet (length 4):
guacd[5606]: DEBUG:             soundFlags: 0x0001
guacd[5606]: DEBUG:             pad2OctetsA: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     ShareCapabilitySet (length 4):
guacd[5606]: DEBUG:             nodeId: 0x0000
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     FontCapabilitySet (length 4):
guacd[5606]: DEBUG:             fontSupportFlags: 0x0001
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     ControlCapabilitySet (length 8):
guacd[5606]: DEBUG:             controlFlags: 0x0000
guacd[5606]: DEBUG:             remoteDetachFlag: 0x0000
guacd[5606]: DEBUG:             controlInterest: 0x0002
guacd[5606]: DEBUG:             detachInterest: 0x0002
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     ColorCacheCapabilitySet (length 4):
guacd[5606]: DEBUG:             colorTableCacheSize: 0x0006
guacd[5606]: DEBUG:             pad2Octets: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     WindowActivationCapabilitySet (length 8):
guacd[5606]: DEBUG:             helpKeyFlag: 0x0000
guacd[5606]: DEBUG:             helpKeyIndexFlag: 0x0000
guacd[5606]: DEBUG:             helpExtendedKeyFlag: 0x0000
guacd[5606]: DEBUG:             windowManagerKeyFlag: 0x0000
guacd[5606]: DEBUG:     Sending
guacd[5606]: DEBUG:     OffscreenBitmapCacheCapabilitySet (length 8):
guacd[5606]: DEBUG:             offscreenSupportLevel: 0x00000001
guacd[5606]: DEBUG:             offscreenCacheSize: 0x1E00
guacd[5606]: DEBUG:             offscreenCacheEntries: 0x07D0
guacd[5606]: DEBUG:     CLIPRDR (clipboard redirection) channel connected.
guacd[5606]: DEBUG:     SVC "rdpdr" connected.
guacd[5606]: DEBUG:     SVC "rdpsnd" connected.
guacd[5606]: INFO:      Connected to RDPDR 1.10 as client 0x522e
guacd[5606]: DEBUG:     Ignoring server capability set type=0x0001, length=44
guacd[5606]: DEBUG:     Ignoring server capability set type=0x0002, length=8
guacd[5606]: DEBUG:     Ignoring server capability set type=0x0003, length=8
guacd[5606]: DEBUG:     Ignoring server capability set type=0x0004, length=8
guacd[5606]: DEBUG:     Ignoring server capability set type=0x0005, length=8
guacd[5606]: DEBUG:     Sending capabilities...
guacd[5606]: DEBUG:     Capabilities sent.
guacd[5606]: DEBUG:     Client ID confirmed
guacd[5606]: DEBUG:     Clipboard data received. Reporting availability of clipboard data to RDP server.
guacd[5606]: DEBUG:     invalid bitmap bpp 0
guacd[5606]: DEBUG:     SECONDARY ORDER [0x00] Cache Bitmap failed
guacd[5606]: DEBUG:     order flags 03 failed
guacd[5606]: DEBUG:     Fastpath update Orders [0] failed, status 0
guacd[5606]: DEBUG:     fastpath_recv_update() - -1
guacd[5606]: DEBUG:     fastpath_recv_update_data() fail
guacd[5606]: DEBUG:     transport_check_fds: transport->ReceiveCallback() - -3
guacd[5606]: DEBUG:     freerdp_check_fds() failed - 0
2021-01-23 14:16:40.966 [http-nio-8080-exec-2] INFO  o.a.g.a.j.s.JumpserverSessionService - uploadSessionRecord: 6380da80-5d95-4ea5-ba21-8bfb36bc4cd2
2021-01-23 14:16:40.966 [http-nio-8080-exec-2] INFO  o.a.g.a.j.s.JumpserverSessionService - 插入队列: {"error":0,"type":"UPLOAD","uuid":"6380da80-5d95-4ea5-ba21-8bfb36bc4cd2"}
2021-01-23 14:16:40.966 [http-nio-8080-exec-2] INFO  o.a.g.tunnel.TunnelRequestService - User "e2509283-0e20-42e1-b174-d99239b25226" disconnected from connection "262b11a5-19d8-4879-a6a6-01d4a2b6f056". Duration: 2254 milliseconds
guacd[5606]: ERROR:     Connection closed.
guacd[5606]: DEBUG:     Unloading device 0 (Guacamole Filesystem)
guacd[5606]: DEBUG:     SVC "rdpdr" disconnected.
guacd[5606]: DEBUG:     SVC "rdpsnd" disconnected.
guacd[5606]: INFO:      Internal RDP client disconnected
guacd[5606]: INFO:      User "@a9cc32ac-12cd-453a-8b6b-5d08d5874f95" disconnected (0 users remain)
guacd[5606]: INFO:      Last user of connection "$b09d81f2-dfa3-4399-a440-ba3169030884" disconnected
guacd[5606]: DEBUG:     Requesting termination of client...
Exception in thread "Thread-128" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:439)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:311)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:251)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:192)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
guacd[5606]: DEBUG:     Client terminated successfully.
guacd[201]: INFO:       Connection "$b09d81f2-dfa3-4399-a440-ba3169030884" removed.
23-Jan-2021 14:16:41.070 WARNING [http-nio-8080-exec-12] org.apache.http.client.protocol.ResponseProcessCookies.processCookies Invalid cookie header: "Set-Cookie: sessionid=bod5shz833l6dbc1duogr72i7uc492qv; expires=Sun, 24 Jan 2021 14:16:41 GMT; HttpOnly; Max-Age=86400; Path=/; SameSite=Lax". Invalid 'expires' attribute: Sun, 24 Jan 2021 14:16:41 GMT
2021-01-23 14:16:41.071 [http-nio-8080-exec-12] INFO  o.a.g.a.j.api.JumpserverService - getUser by cookie: e2509283-0e20-42e1-b174-d99239b25226
2021-01-23 14:16:41.998 [Thread-130] INFO  o.a.g.a.j.s.JumpserverSessionService - Session Type: UPLOAD
2021-01-23 14:16:41.998 [Thread-130] INFO  o.a.g.a.j.s.JumpserverSessionService - 录像文件:/config/guacamole/data/record/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.replay
2021-01-23 14:16:41.998 [Thread-130] INFO  o.a.g.a.j.session.RecordService - compress to /config/guacamole/data/record/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.gz
2021-01-23 14:16:41.998 [Thread-130] INFO  o.a.g.a.j.s.JumpserverSessionService - 压缩文件:/config/guacamole/data/record/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.gz
2021-01-23 14:16:41.998 [Thread-130] INFO  o.a.g.a.j.session.RecordService - 上传录像: /config/guacamole/data/record/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.gz, 上传方式: server
2021-01-23 14:16:42.000 [Thread-131] INFO  o.a.g.a.j.s.JumpserverSessionService - Session Type: FINISH
2021-01-23 14:16:42.000 [Thread-131] INFO  o.a.g.a.j.api.JumpserverService - finishSession: {date_end=2021-01-23 14:16:40 +0000, is_finished=true}
2021-01-23 14:16:42.036 [Thread-130] INFO  o.a.g.a.j.session.RecordService - {code:201,result:{"url":"/media/replay/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.replay.gz"}}
2021-01-23 14:16:42.036 [Thread-130] INFO  o.a.g.a.j.session.RecordService - 上传录像成功
2021-01-23 14:16:42.037 [Thread-130] INFO  o.a.g.a.j.session.RecordService - 上传录像成功: /config/guacamole/data/record/2021-01-23/6380da80-5d95-4ea5-ba21-8bfb36bc4cd2.gz
2021-01-23 14:16:42.037 [Thread-130] INFO  o.a.g.a.j.api.JumpserverService - 更新Session成功(录像上传完毕){has_replay=true}
2021-01-23 14:16:42.064 [Thread-131] INFO  o.a.g.a.j.api.JumpserverService - {code:200,result:{"id":"6380da80-5d95-4ea5-ba21-8bfb36bc4cd2","user":"*****","asset":"Win2003轻应用服务器","system_user":"administrator","user_id":"e2509283-0e20-42e1-b174-d99239b25226","asset_id":"b30af0e4-6c51-467e-bd08-363f5f40b3cc","system_user_id":"a9c1dd37-0f67-4d14-977a-30799244143c","login_from":"WT","login_from_display":"Web Terminal","remote_addr":"172.20.10.1","is_success":false,"is_finished":true,"has_replay":false,"can_replay":false,"can_join":false,"can_terminate":false,"protocol":"rdp","date_start":"2021-01-23 22:16:38 +0800","date_end":"2021-01-23 22:16:40 +0800","terminal":"2fd0bea5-6e97-46e8-ae07-1665aa69c98d","command_amount":0,"org_id":"","org_name":"DEFAULT"}}
2021-01-23 14:16:42.064 [Thread-131] INFO  o.a.g.a.j.api.JumpserverService - 更新Session成功
2021-01-23 14:16:42.064 [Thread-131] WARN  o.a.g.a.j.s.JumpserverSessionService - ForwardPort 为空，port: 3389
2021-01-23 14:16:42.064 [Thread-131] INFO  o.a.g.a.j.s.JumpserverSessionService - 开始清理Drive: /config/guacamole/data/drive/e2509283-0e20-42e1-b174-d99239b25226
2021-01-23 14:16:42.064 [Thread-131] INFO  o.a.g.a.jumpserver.utils.ExecuteUtil - exec: rm -rf /config/guacamole/data/drive/e2509283-0e20-42e1-b174-d99239b25226/*
2021-01-23 14:16:42.073 [Thread-131] INFO  o.a.g.a.jumpserver.utils.ExecuteUtil - success: rm -rf /config/guacamole/data/drive/e2509283-0e20-42e1-b174-d99239b25226/*
2021-01-23 14:16:42.076 [Thread-130] INFO  o.a.g.a.j.api.JumpserverService - {code:200,result:{"id":"6380da80-5d95-4ea5-ba21-8bfb36bc4cd2","user":"******","asset":"Win2003轻应用服务器","system_user":"administrator","user_id":"e2509283-0e20-42e1-b174-d99239b25226","asset_id":"b30af0e4-6c51-467e-bd08-363f5f40b3cc","system_user_id":"a9c1dd37-0f67-4d14-977a-30799244143c","login_from":"WT","login_from_display":"Web Terminal","remote_addr":"172.20.10.1","is_success":false,"is_finished":true,"has_replay":true,"can_replay":true,"can_join":false,"can_terminate":false,"protocol":"rdp","date_start":"2021-01-23 22:16:38 +0800","date_end":"2021-01-23 22:16:40 +0800","terminal":"2fd0bea5-6e97-46e8-ae07-1665aa69c98d","command_amount":0,"org_id":"","org_name":"DEFAULT"}}
2021-01-23 14:16:42.076 [Thread-130] INFO  o.a.g.a.j.api.JumpserverService - 更新Session成功(录像上传完毕)
2021-01-23 14:16:46.043 [Thread-4] INFO  o.a.g.a.j.r.JumpserverRegisterService - 开始获取终端配置
2021-01-23 14:16:46.069 [Thread-4] INFO  o.a.g.a.j.r.JumpserverRegisterService - 获取终端配置成功
2021-01-23 14:16:46.069 [Thread-4] INFO  o.a.g.a.j.r.JumpserverRegisterService - 录像存储方式: server
2021-01-23 14:16:58.228 [Thread-5] INFO  o.a.g.a.j.r.JumpserverRegisterService - 心跳成功: []
2021-01-23 14:16:59.735 [Thread-6] INFO  o.a.g.a.j.api.JumpserverService - 上报状态成功{code:201,result:{"system_cpu_load_1":0.09,"system_memory_used_percent":86.22,"system_disk_used_percent":13.93,"session_active_count":0}}

**Comment by xintiao9243** [comment]
一个版本，我也遇到问题了，不过我win_server2012和win_server2008r2都不行，win10可以。资产配置是按照官方资产管理文档处配置的，都是手动密码，win_server2008的rdp开启任意级别访问，win_server2012开启高级安全访问。防火墙也关了，在jumpserver服务器上telnet rdp端口也是通的。很奇怪

**Comment by wojiushixiaobai** [comment]
@Dragovish @xintiao9243 [Win7/2008 频繁断开解决方案](https://docs.jumpserver.org/zh/master/faq/guacamole/#2)

**Comment by kerrylau** [comment]
> @Dragovish @xintiao9243 [Win7/2008 频繁断开解决方案](https://docs.jumpserver.org/zh/master/faq/guacamole/#2)

After applied the above setting, still can't connect to win2003 or win2008

**Comment by Dragovish** [comment]
JUMPSERVER_DISABLE_GLYPH_CACHING=true   # 禁用RDP会话中的字形缓存
加了这一句后问题解决了。其他配置没加
