### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wike2019** [jumpserver/jumpserver#5519]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.6.1 GPLv2.
Copyright FIT2CLOUD 飞致云 © 2014-2020

**浏览器版本**

谷歌浏览器
**Bug 描述**
window 和 mac 电脑无法连接 linux系统是好的
**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/5925704/105626946-7d81bc80-5e6e-11eb-9c5a-bfd55c300b8e.png)
)

**Comment by ibuler** [comment]
截图页面上的内容

**Comment by jym503558564** [comment]
该问题还存在吗？windows无法连接，查看一下guacamole终端有在线吗？

**Comment by jym503558564** [comment]
@wike2019 请确保各个终端组件在线，如测试连接不上，可分别查看各组件报错日志，并附上截图。
如linux: docker logs -f jms_koko
如windows: docker logs -f jms_guacamole

如该问题还存在，可再次打开Issues
