### ISSUE TITLE
jumpserver推送用户问题

### ISSUE THREAD

**Issue by yumsu** [jumpserver/jumpserver#552]
推送用户提示“/bin/bash: /root/.ansible/tmp/ansible-tmp-1500551391.99-143978688196819/tmpv3Ej1L: /bin/bash^M: bad interpreter: 没有那个文件或目录”
求解，谢谢

**Comment by ibuler** [comment]
没有bash ？

**Comment by yumsu** [comment]
有吧，没有的话应该不能执行脚本吧
