### ISSUE TITLE
管理用户使用sudo免密用户，系统用户推送失败

### ISSUE THREAD

**Issue by wml3** [jumpserver/jumpserver#5520]
该/etc/sudoers文件里配置了Defaults    !env_reset，默认是Defaults    env_reset  ，该参数是控制sudo用户环境变量是否强制变更

**Comment by wml3** [comment]
2.6.2以及1.5.9版本都有该问题

**Comment by wml3** [comment]
![image](https://user-images.githubusercontent.com/49503874/105652289-d6476880-5ef3-11eb-90da-cdd6b8772f9a.png)

![image](https://user-images.githubusercontent.com/49503874/105652326-ebbc9280-5ef3-11eb-9979-54c6a2b50728.png)

**Comment by ibuler** [comment]
Defaults env_reset  配置这个以后可以吗？

**Comment by wml3** [comment]
Defaults env_reset 可以的
