### ISSUE TITLE
[Question] 请问1月15日的漏洞通过代码单点修改如何修复？

### ISSUE THREAD

**Issue by WhiteN1ght** [jumpserver/jumpserver#5522]
**请描述您的问题.**
线上服务不方便大版本更新，希望单点修改修复，2.x版本的。请问怎么通过代码怎么单点修复？不知道是否方便提供对应的修复commit链接。
https://github.com/jumpserver/jumpserver/commit/043d24a8f7c864233efd3038c0652a8afe9abf75。找到这一次问题修复代码，请问还有其他修复点吗？这个改完后查看任务详情无法查看。

**Comment by WhiteN1ght** [comment]
找到这个修复点：https://github.com/jumpserver/jumpserver/commit/043d24a8f7c864233efd3038c0652a8afe9abf75
不知道是否全？根据这个修复后8070端口起不来了

**Comment by wojiushixiaobai** [comment]
@WhiteN1ght 可以临时屏蔽下，后续通过升级修复

**Comment by ibuler** [comment]
通过 github readme 上的说明，nginx 屏蔽
