### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by albert0807** [jumpserver/jumpserver#5523]
**JumpServer 版本(v1.5.9以下不再支持)**
最新 2.62
**浏览器版本**
Google Chrome
版本 87.0.4280.141
**Bug 描述**
无法批量导入资产，一个资产可以使用 csv 导入，多个就不行了，也没有任何提示。

**Bug 重现步骤(有截图更好)**
a	127.0.0.1	ssh	123456	['ssh/123456']																			d4d55ec66fc94152b2e409441122		Linux
b	127.0.0.1	ssh	123456	['ssh/123456']																			d4d55ec66fc94152b2e409441122		Linux

**Comment by jym503558564** [comment]
未能复现
![image](https://user-images.githubusercontent.com/40739051/105794690-7b327600-5fc6-11eb-8dda-96f477fce94c.png)
![image](https://user-images.githubusercontent.com/40739051/105794693-7e2d6680-5fc6-11eb-8bd6-c474b49447a2.png)

**Comment by jym503558564** [comment]
@albert0807 
刚看了一下您填写的示例，请确认一下端口是不是写了6位数？官方规定端口最高65535。我们不支持无效6位数端口的导入
