### ISSUE TITLE
[Question]部署开源的jumpserver2.7.0 登录不了windows服务器

### ISSUE THREAD

**Issue by flygaga** [jumpserver/jumpserver#5524]
**请描述您的问题.**
部署开源的jumpserver2.7.0 登录不了windows服务器，Linux机器可以登录，测试端口3389 是通的，就是连不上

**Comment by wojiushixiaobai** [comment]
@flygaga [参考此文档设置下](https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_rdp/)

**Comment by wang509020** [comment]
可能是guacamole的问题，我也出现过类似问题。
