### ISSUE TITLE
[Question]  Luna页面，使用微信，钉钉自带快捷键对windows 会话截图时无法自动保存到粘贴板

### ISSUE THREAD

**Issue by wml3** [jumpserver/jumpserver#5526]
**请描述您的问题.**
如题，截图完成后，可以保存到本地；但无法在其他地方，如word，如微信对话框里保存。
哪里的快捷键冲突？或者什么配置

**Comment by ibuler** [comment]
试试 原生的 rdp

**Comment by wml3** [comment]
这个问题，后来试了一下，luna只要不再图层最前端，就能正常复制，可能是粘贴板到了会话里？
