### ISSUE TITLE
[Bug] 管理用户创建失败

### ISSUE THREAD

**Issue by bingcongam** [jumpserver/jumpserver#5527]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.7.0 GPLv2.

**浏览器版本**
谷歌

**Bug 描述**
ssh密钥 导入文件的时候没有反应
之前用旧版本1.5.9是可以的
**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![1611586103](https://user-images.githubusercontent.com/69688013/105721428-843c2c80-5f5f-11eb-99e2-b719914ce8b1.jpg)
![1611586504(1)](https://user-images.githubusercontent.com/69688013/105722250-6f13cd80-5f60-11eb-9ce6-6232bd25d981.jpg)

**Comment by ibuler** [comment]
response 是什么？

![image](https://user-images.githubusercontent.com/17382885/105790877-0bb98800-5fc0-11eb-916a-3b319d5dfa6c.png)

**Comment by bingcongam** [comment]
![image](https://user-images.githubusercontent.com/69688013/105794046-2f330180-5fc5-11eb-92f7-6b9e34754189.png)
是空的

**Comment by jym503558564** [comment]
@bingcongam 无法复现该问题，请确认密钥格式是否正确？
