### ISSUE TITLE
v2.7.0升级完成后，未找到“支持批量测试资产的可连接性”的功能入口

### ISSUE THREAD

**Issue by missing-cn** [jumpserver/jumpserver#5528]
如题

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/105790741-cac17380-5fbf-11eb-8595-d2e07ce75cb1.png)

**Comment by ibuler** [comment]
可能是指的系统用户的批量测试

**Comment by missing-cn** [comment]
感谢楼上，就是这个。
