### ISSUE TITLE
[Question] 组件redis的读写是否支持传输中加密（TLS）

### ISSUE THREAD

**Issue by mceternity** [jumpserver/jumpserver#5529]
**请描述您的问题.**
想使用aws的elasticcache（redis）来替代自建redis，但aws redis必须要使用 传输中加密（TLS），请问是否支持呢？或是有案例嘛？

**Comment by ibuler** [comment]
这个你调研一下

**Comment by mceternity** [comment]
> 这个你调研一下

那是否支持不用auth的redis呢？ 配置文件redis password字段直接留空？

**Comment by luweijun1992** [comment]
> > 这个你调研一下
> 
> 那是否支持不用auth的redis呢？ 配置文件redis password字段直接留空？

可以啊，之前旧版本有密码没密码都行，不知道新版有没有变化。
