### ISSUE TITLE
在线session显示不正确

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#553]
如图： 实际上这些session已经退出
![image](https://user-images.githubusercontent.com/8543865/28401888-7061e26e-6d4f-11e7-8d7a-20abd2db616a.png)

**Comment by ibuler** [comment]
可以是退出时没有通知到api，感谢反馈

**Comment by zsjohny** [comment]
@ibuler 请叫我找别扭小王子

**Comment by ibuler** [comment]
我想叫你 解bug小王子

**Comment by gengkeye** [comment]
此bug尚未修复，目前仍有这个问题。

**Comment by ibuler** [comment]
新版本修复了
