### ISSUE TITLE
[Question] 请问如何设置可以让用户只能登录sftp上传下载文件，不能登录shell？

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#5530]
我想用jumpserver来当FTP管理工具来用，提供给前端同事上传图片等静态资源，但又不能允许他们登录shell。
请问怎么设置能达到这个效果？还有路径权限管控，不同的路径分配不同的权限。

**Comment by ibuler** [comment]
只分配上传下载的权限应该就可以

**Comment by LeeEirc** [comment]
暂时还不可以在JMS的页面上设置，如果想屏蔽shell，可以自己修改 nginx 配置，禁用 koko/ws/terminal 的路径。

**Comment by yuanhaoliang** [comment]
> 只分配上传下载的权限应该就可以

试了，不行的，因为sftp是基于shell的。。

**Comment by yuanhaoliang** [comment]
我使用mysecureshell实现了我想要的只能使用sftp不能登录shell效果了。
