### ISSUE TITLE
[Question] 今天登入時候出現了問題

### ISSUE THREAD

**Issue by kitkit123456** [jumpserver/jumpserver#5531]
今天登入時出現了
查看了DB和REDIS 都是正常的
版本是2.5.3
Server error occur, contact administrator
![image](https://user-images.githubusercontent.com/78039446/105879118-c38c7b00-603c-11eb-877e-dae1c860494d.png)

**Comment by kitkit123456** [comment]
版本是2.5.3

**Comment by ibuler** [comment]
看一下后台日志 ?

```
$ docker logs -f jms_core 
$ cd /opt/jumpserver/logs/core/ && tail jumpserver.log
```

**Comment by jym503558564** [comment]
@kitkit123456 请问该问题还存在吗？如果还存在请贴出详细日志

**Comment by jym503558564** [comment]
@kitkit123456 如果该问题还存在，可再次打开Issues，并贴上详细的日志，方便我们团队帮您查看问题并解决。
