### ISSUE TITLE
[Feature] 建议在资产授权时，权限增加“删除文件”的控制开关

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#5534]
在使用SFTP的文件管理器的时候，为了防止误删文件，希望如下图所示，增加一个“删除文件”的开关，防止删文件跑路的可能。
现在我使用mysecureshell做到不允许登录shell,只能使用sftp上传下载文件了。

![image](https://user-images.githubusercontent.com/2853517/105955513-62eb5580-60b1-11eb-9d95-4aaa3a7690fe.png)

**Comment by ibuler** [comment]
linux 可以控制，windows 应该无法控制

**Comment by yuanhaoliang** [comment]
> linux 可以控制，windows 应该无法控制

嗯，就需要在linux里控制。

**Comment by Laplacence** [comment]
一个想法，控制删除虽好，但是应该把sftp的根目录放在/tmp之类的地方，这样即使全部被删除也没问题。
