### ISSUE TITLE
[Question] redis主要用途及存放数据

### ISSUE THREAD

**Issue by mceternity** [jumpserver/jumpserver#5536]
**请描述您的问题.**
你好，请问redis主要是用于什么用途，存放了什么样类型的数据呢？ 是否有文档介绍，同时如果作为队列的话 是否能用其他队列来替代？例如kafka？

**Comment by ibuler** [comment]
- [ ] 存放session
- [ ] celery 任务队列
- [ ] 数据 cache
- [ ] django channel websocket broker
- [ ] 订阅发布事件处理

目前是以上用途
