### ISSUE TITLE
[Bug] 2.7.0系统用户导入更新失败且无提示

### ISSUE THREAD

**Issue by apolin1** [jumpserver/jumpserver#5537]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by apolin1** [comment]
使用excel导入无提示，使用csv导入，只要文件有变动就出错有提示，只改下单元格长度都会出错，
line 0. 0: id or pk not in data
line 1. 0: id or pk not in data
line 2. 0: id or pk not in data
line 3. 0: id or pk not in data
line 4. 0: id or pk not in data
line 5. 0: id or pk not in data
line 6. 0: id or pk not in data
line 7. 0: id or pk not in data
line 8. 0: id or pk not in data
line 9. 0: id or pk not in data
line 10. 0: id or pk not in data

**Comment by ibuler** [comment]
csv 导入设计上存在问题，提示不明显。

这个问题应该是批量更新，但是没有 id

**Comment by apolin1** [comment]
是批量更新，下载下来的模板不做任何修改上传就可以，只要一做修改，比较我只是修改了一下单元格长度，保存就出上边的问题

**Comment by jym503558564** [comment]
无法复现该问题，更新时，ID需要填写。请问是否未填ID，或者填写了不存在的ID?
如果根据上述进行更新，如还存在问题，可再次打开issues
