### ISSUE TITLE
2.7.0邮件smtp无法连接

### ISSUE THREAD

**Issue by foxh1s** [jumpserver/jumpserver#5539]
已确定smtp服务器无问题，测试连接时无反应

**Comment by jym503558564** [comment]
测试链接时需要填写SMTP密码，有什么报错信息吗？

**Comment by foxh1s** [comment]
> 测试链接时需要填写SMTP密码，有什么报错信息吗？

您好，已解决。思维没有转变，一直以为是jumpserver的问题。实际上是网关丢弃了二层NAT数据，导致docker虚拟网络无法访问外网，网关配好规则已解决。
