### ISSUE TITLE
[Feature] Kubernetes应用终端窗口可输入范围过小

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#5540]
**请描述您的需求或者改进建议.**
Kubernetes应用终端窗口可输入范围过小,单行只能输入142个字符，并且单行命令超过142字符时不会自动换行，而是转到行首覆盖了行首输入的内容，严重影响长命令行使用。希望可以尽快修复。

**Comment by ibuler** [comment]
已修复到 v2.7，明天发布 v2.7.1

**Comment by yearnxiao** [comment]
> 已修复到 v2.7，明天发布 v2.7.1

非常感谢！

**Comment by yearnxiao** [comment]
年前不发版了吗？等了两天没动静了 @_@

**Comment by jym503558564** [comment]
v2.7.1已发布，请更新测试

**Comment by liyangFileRepository** [comment]
不更新版本，有什么方式可以解决这个问题吗？
