### ISSUE TITLE
[Bug] 已经没有登录资产了，但是会话还是显示在线

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5545]
**JumpServer 版本(v1.5.9以下不再支持)**
2.7.0

**浏览器版本**

**Bug 描述**
已经没有登录资产了，但是会话还是显示在线
这种情况怎么处理，重启koko吗

**Bug 重现步骤(有截图更好)**
1.
这资产已经没在登录了，但是还显示在线，而且无法中断
![image](https://user-images.githubusercontent.com/44529247/106380708-1d9b9080-63ef-11eb-93dc-2aad736d3e90.png)

会话监控里边显示已经关闭
![image](https://user-images.githubusercontent.com/44529247/106380745-3d32b900-63ef-11eb-8915-9e44074d9548.png)

3.

**Comment by ibuler** [comment]
需要一段时间，会定时处理的，应该是每 30 s

**Comment by jym503558564** [comment]
@ryswork1993 等待一段时间，刷新页面，幽灵会话还存在吗？如果还存在可再次打开issues
