### ISSUE TITLE
升级到2.7.0之后，磁盘读流量和cpu特别高

### ISSUE THREAD

**Issue by guoyunlong666** [jumpserver/jumpserver#5547]
配置：2C4G
系统：CentOS Linux release 7.7.1908 (Core) 和 CentOS Linux release 7.4.1708 (Core)
部署2台jumpserver机器，一台是内部mysql和redis，一台是外接mysql和redis，都出现磁盘读流量特别高的情况：
![image](https://user-images.githubusercontent.com/35826444/106450889-c239d300-64c0-11eb-89a7-5423626149e0.png)
使用内部mysql和redis的，只要jms_celery容器启动，磁盘读和cpu就跑满了；使用外接mysql和redis，偶尔会出现io和cpu跑满的情况，celery的状态也是unhealthy
![image](https://user-images.githubusercontent.com/35826444/106451646-d0d4ba00-64c1-11eb-8f54-c92c639b8b19.png)

**Comment by ibuler** [comment]
你是从哪个版本升级上来的？

应该是在 2.4 版本，新增了好几个 celery 进程，导致的内存占用比较多，并且会有任务，定时生成用户的授权树，本质原因应该还是 内存占用太多了

**Comment by ibuler** [comment]
近期在优化这里，下个版本解决

**Comment by guoyunlong666** [comment]
好像是从2.0.1升级上来的，我们打算升级配置到4c8g试试

**Comment by ibuler** [comment]
嗯，启动了好几个 异步任务进程，所以占用的有点多了
