### ISSUE TITLE
docker-compose安装报错

### ISSUE THREAD

**Issue by k782411998** [jumpserver/jumpserver#555]
umpserver    | 2017-07-20 18:04:06 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
jumpserver    | 2017-07-20 18:04:11 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
coco          | WARNING:/opt/coco/coco/service.py:App auth failed, Access key error or need admin active it

**Comment by k782411998** [comment]
好了

**Comment by zsjohny** [comment]
@k782411998  没问题请关闭 issue

**Comment by kaishidongle90** [comment]
我用Mac 装的 ，碰到一样的问题， 这是啥原因嘞
