### ISSUE TITLE
[Bug] Edge浏览器登录JumpServer，关闭浏览器后web会话不过期

### ISSUE THREAD

**Issue by JeffJiang1024** [jumpserver/jumpserver#5551]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.0 社区版

**浏览器版本**
Microsoft Edge     版本 88.0.705.56 (官方内部版本) (64 位)
Google Chrome    版本 88.0.4324.104（正式版本） （64 位）
均已关闭 ”关闭浏览器后继续运行后台应用“ 的开关

**Bug 描述**
config.txt参数设置为：
SESSION_EXPIRE_AT_BROWSER_CLOSE=True

使用微软Edge浏览器登录Jumpserver账号，不注销登录的情况下直接关闭浏览器，重新打开并访问JumpServer web管理界面时，不需要登录，直接进入了未退出账号的仪表盘界面（重启计算机后再打开Edge浏览器访问JumpServer管理界面也是如此）

**Bug 重现步骤(有截图更好)**
1.  浏览器设置情况：
![image](https://user-images.githubusercontent.com/44266597/106453567-7ab54600-64c4-11eb-9292-e25955ed1ead.png)
![image](https://user-images.githubusercontent.com/44266597/106453884-eac3cc00-64c4-11eb-8e91-5e11f9d27525.png)

2. 使用Edge浏览器访问JumpServer登录界面并登录账号
3. 不退出账号，直接关闭浏览器（确认没有残留标签页）
4. 重新打开Edge浏览器，访问JumpServer登录界面（URL不带任何参数）
5. 无需操作，跳过登录界面，直接跳转到未退出账号的仪表盘页面（重启计算机后重复步骤5仍如此）
    地址栏显示URL：`https://堡垒机内网域名/ui/#/dashboard`

6. 使用Chrome浏览器重复步骤2~4，在步骤4能正确显示登录界面，要求输入用户名和密码登录
    地址栏显示URL：`https://堡垒机内网域名/core/auth/login/`

**Comment by ibuler** [comment]
应该是和浏览器有关的

**Comment by ibuler** [comment]
本质上，是不是过期时浏览器控制的，cookie的过期时间决定了登录是否过期，正常情况是有有效期的，设置 close 选项后，会标记为 session

![image](https://user-images.githubusercontent.com/17382885/106551247-d0830000-654f-11eb-873f-0445475c531a.png)

**Comment by JeffJiang1024** [comment]
感谢，今天重新尝试一次复现步骤，目前已经没有异常。
