### ISSUE TITLE
[Question]服务器搭起来后，数据库保存的加密串，跟以前不一样 

### ISSUE THREAD

**Issue by jxqiuhan** [jumpserver/jumpserver#5552]
**请描述您的问题.**
你好，请问保存系统用户的密码，采用的是什么样的加密方式，加密密码是在配置文件配置的？

**Comment by ibuler** [comment]
并没有不一样啊，还是 aes 加密的，可以截图看看吗？或者你启用了国密？

**Comment by jxqiuhan** [comment]
你好，aes的加密key是哪个配置？
如下是，这两个是同一个字符，存储到数据库不一样

![image](https://user-images.githubusercontent.com/14574097/106682057-a89da600-65fc-11eb-976b-6865f071d8b4.png)

**Comment by jxqiuhan** [comment]
补充，每次修改都不一样，就像随机生成的uuid一样，版本安装的是最新的docker镜像

**Comment by jym503558564** [comment]
@jxqiuhan 加盐了，这样安全性更高。如还有其他疑问，可自行了解一下加盐算法。
