### ISSUE TITLE
[Question] Version v2.7.0 jumpserver中websocket访问被阿里云WAF阻断

### ISSUE THREAD

**Issue by viazry** [jumpserver/jumpserver#5553]
访问websocket的uri：/ws/ops/tasks/log/
功能为更新硬件信息、测试资产可连接性等。
阿里云WAF规则名称：JumpServer本地文件读取
规则ID：115127
防护类型：本地文件包含
导致使用WAF后此通信被阻断

**Comment by wojiushixiaobai** [comment]
@viazry 请升级到最新版本
