### ISSUE TITLE
[Bug]  2.7.0 通过installer一键拉起来的服务koko无法多个注册

### ISSUE THREAD

**Issue by watson6** [jumpserver/jumpserver#5557]
**JumpServer **
版本2.7.0。
jumpserver-installer-v2.7.0 这个脚本一键拉起服务。

**浏览器版本**
Google Chrome 版本 88.0.4324.96（正式版本） (x86_64)

**Bug 描述**
问题一、增加的koko不会自动注册到终端管理里面。
问题二、koko对应的5000端口服务对应负载均衡，没有可以配置的地方。最严重的还是这个地方，直接导致组件无法拓展负载使用。

**Bug 重现步骤(有截图更好)**
在docker-compose-app.yml 增加多个koko服务
![image](https://user-images.githubusercontent.com/10827194/106584552-4c497080-6581-11eb-916c-5b274f2956e5.png)
后台看到只有默认的koko配置了。
![image](https://user-images.githubusercontent.com/10827194/106584684-70a54d00-6581-11eb-9f3a-44a46567c136.png)

在script/utils.sh 脚本里面增加了这个服务器
  services="core koko koko2 koko3 guacamole lina luna nginx"

再次重启重新注册也发现后台只能注册一个koko服务。但是其他koko容器状态也是启动正常。
![image](https://user-images.githubusercontent.com/10827194/106588343-a0565400-6585-11eb-934d-e94f91e515e7.png)
后台服务的终端管理
![image](https://user-images.githubusercontent.com/10827194/106588422-b8c66e80-6585-11eb-9b42-05a2f8c7cb95.png)

**Comment by wojiushixiaobai** [comment]
参考下：https://docs.jumpserver.org/zh/master/install/setup_by_lb/
该文档还不完善，仅供参考
