### ISSUE TITLE
luna 使用cat命令卡死

### ISSUE THREAD

**Issue by sadlar** [jumpserver/jumpserver#556]
luna 使用cat命令会卡死

**Comment by hellorocky** [comment]
是不是cat的那个文件太大了

**Comment by zsjohny** [comment]
@sadlar  估计是太大了

**Comment by sadlar** [comment]
@zsjohny  @hellorocky  我重启了下django主程序 解决。 是手动在ubuntu上源码安装的。cat的是passwd文档，应该是偶然事件。
