### ISSUE TITLE
[Question] 是否有非docker的，传统的部署模式的部署方法？

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#5565]
**请描述您的问题.**
不是很想使用docker模式进行部署，个人倾向于使用之前的模式来部署jumpserver，但是目前文档似乎都已经没有了。

**Comment by ibuler** [comment]
部署组件太多，手动一步步安装太繁琐，如果有需求，可以看各组件的 Dockerfile
