### ISSUE TITLE
[Bug] 进入某一具体资产授权规则后显示「资产授权: undefined」

### ISSUE THREAD

**Issue by WeiZhixiong** [jumpserver/jumpserver#5566]
JumpServer 版本：v2.7.0 (从v1.5.2升级到v2.7.0)

浏览器版本：
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36

Bug 描述：
进入某一具体资产授权规则后显示「资产授权: undefined」
![image](https://user-images.githubusercontent.com/28281165/106729791-da3c5e80-6648-11eb-81a4-5703791b8429.png)

**Comment by ibuler** [comment]
没有复现，难道说是 js 问题？强刷一下浏览器看看

**Comment by WeiZhixiong** [comment]
我现在也复现不了了。
这个问题是在升级后出现的，当时我也试过关闭浏览器缓存和无痕模式，都会大概率出现。
现在又没有这个问题了，中间也没有做什么操作。
可以先把这个 issue  关了

> 没有复现，难道说是 js 问题？强刷一下浏览器看看

**Comment by WeiZhixiong** [comment]
> 没有复现，难道说是 js 问题？强刷一下浏览器看看

我现在也复现不了了。
这个问题是在升级后出现的，当时我也试过关闭浏览器缓存和无痕模式，都会大概率出现。
现在又没有这个问题了，中间也没有做什么操作。
可以先把这个 issue  关了
