### ISSUE TITLE
[Feature] 用户可以对加入收藏夹的资产自定义资产树

### ISSUE THREAD

**Issue by enan820** [jumpserver/jumpserver#5571]
**请描述您的需求或者改进建议.**
用户将资产添加进收藏夹后，右击可以新建、删除、更改树节点，自定义收藏夹资产树。（不会对Default资产树有任何影响）
![_ NGZN3{6LSAEXM1G_31NGD](https://user-images.githubusercontent.com/18327082/106865836-ae7fae00-6706-11eb-9dc7-f5cb0f6db4e2.png)

**Comment by ibuler** [comment]
非常不错的 feature，我们研究一下

**Comment by jym503558564** [comment]
欢迎pull requests
