### ISSUE TITLE
是否可以调用本地的终端，例如windows调用mstsc，ssh调用powershell或者xshell之类的工具

### ISSUE THREAD

**Issue by xuwenjj** [jumpserver/jumpserver#5574]
是否可以调用本地的终端，例如windows调用mstsc，ssh调用powershell或者xshell之类的工具，web终端用起来不方便。

**Comment by luweijun1992** [comment]
> 是否可以调用本地的终端，例如windows调用mstsc，ssh调用powershell或者xshell之类的工具，web终端用起来不方便。

终端可以连接服务器:2222 端口，比如xshell连接服务器IP:2222 
![image](https://user-images.githubusercontent.com/58923704/107136016-a019d800-693a-11eb-91c9-04c3fc753e25.png)

**Comment by ibuler** [comment]
windows 目前还不支持 mstsc 登录，linux 倒是可以用 ssh server

**Comment by ipyker** [comment]
> > 是否可以调用本地的终端，例如windows调用mstsc，ssh调用powershell或者xshell之类的工具，web终端用起来不方便。
> 
> 终端可以连接服务器:2222 端口，比如xshell连接服务器IP:2222
> ![image](https://user-images.githubusercontent.com/58923704/107136016-a019d800-693a-11eb-91c9-04c3fc753e25.png)

这样ssh连接主机后，如果命令过长会出现光标错乱，请问如何解决？

**Comment by jym503558564** [comment]
@ipyker 我们已修复该问题，将在新版本中发布，请关注我们后续版本发布进行测试。
