### ISSUE TITLE
[Question] jumpserver 向ubuntu 16推送authorized key时提示python错误

### ISSUE THREAD

**Issue by watara** [jumpserver/jumpserver#5575]
jumpserver版本：2.6.2
描述：jumpserver 向ubuntu 16推送authorized key时提示python错误
目标服务器统版本：16.04.6 
目标服务器默认python版本：2.7.12
具体：
我们主要的系统是centos，6和7都有，唯独这一台是用的ubuntu，同时也唯独这台服务器推送不了authorized key（其他推送阶段没问题），会提示下面的错误，请问可能是哪里出了问题？
`fatal: [hostname]: FAILED! => {"changed": false, "module_stderr": "Shared connection to x.x.x.x closed.\r\n", "module_stdout": "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.\r\n  from cryptography import x509\r\nTraceback (most recent call last):\r\n  File \"/home/sys_admin/.ansible/tmp/ansible-tmp-1612498111.3775268-241349410943455/AnsiballZ_authorized_key.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/sys_admin/.ansible/tmp/ansible-tmp-1612498111.3775268-241349410943455/AnsiballZ_authorized_key.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/sys_admin/.ansible/tmp/ansible-tmp-1612498111.3775268-241349410943455/AnsiballZ_authorized_key.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_authorized_key_payload_TtTBLr/__main__.py\", line 230, in <module>\r\n  File \"/tmp/ansible_authorized_key_payload_TtTBLr/ansible_authorized_key_payload.zip/ansible/module_utils/urls.py\", line 97, in <module>\r\n  File \"/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\r\n    import OpenSSL.SSL\r\n  File \"/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\r\n    from OpenSSL import crypto, SSL\r\n  File \"/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py\", line 12, in <module>\r\n    from cryptography import x509\r\n  File \"/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py\", line 8, in <module>\r\n    from cryptography.x509.base import (\r\n  File \"/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py\", line 23, in <module>\r\n    from cryptography.x509.extensions import Extension, ExtensionType\r\n  File \"/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py\", line 22, in <module>\r\n    from cryptography.hazmat.primitives import constant_time, serialization\r\n  File \"/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/serialization/__init__.py\", line 22, in <module>\r\n    from cryptography.hazmat.primitives.serialization.ssh import (\r\n  File \"/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/serialization/ssh.py\", line 27, in <module>\r\n    from bcrypt import kdf as _bcrypt_kdf\r\n  File \"/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py\", line 57\r\n    def gensalt(rounds: int = 12, prefix: bytes = b\"2b\") -> bytes:\r\n                      ^\r\nSyntaxError: invalid syntax\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

**Comment by wojiushixiaobai** [comment]
在 ubuntu 资产执行下面命令即可
```sh
apt-get install python
```

**Comment by ibuler** [comment]
手动使用 ansible 试试？估计应该是和 python 有关

**Comment by jym503558564** [comment]
@watara 问题现在还存在吗？

**Comment by watara** [comment]
> @watara 问题现在还存在吗？

我自己未能处理这个问题，不过只是推送用户authorized key这个环节卡住了，而且只有这一台服务器，所以我现在是手动把ssh密钥给处理了，其他功能上一切正常。抱歉长久未能答复，这个问题或许是个例。

**Comment by gzalanhu** [comment]
请问最后怎么解决的，我现在遇到同样的问题
