### ISSUE TITLE
[Question] 能否使用登录用户直接登录服务器，而不是使用系统用户登录

### ISSUE THREAD

**Issue by knwng** [jumpserver/jumpserver#5581]
**请描述您的问题.**
您好，我们由于有不同用户使用跳板机登录到服务器上工作，如果使用单一系统用户，用户的环境和文件会很混乱，所以希望能让不同的用户用自己登录账号的身份登录到服务器上，请问应该如何实现？谢谢！

**Comment by ibuler** [comment]
建立一个动态的系统用户，也就是 系统用户的用户名和用户相同，然后手动登录

**Comment by knwng** [comment]
好的谢谢，我找到了这个方法，但是我看社区版只能为一个系统用户开启这个开关，这个是对社区版的限制吗？商业版可以支持更多的动态系统用户吗？

**Comment by ibuler** [comment]
商业版和社区版，一个协议只能有一个动态系统用户

**Comment by knwng** [comment]
我们现在的一个需求是，在同一协议下，给一部分用户一些服务器的root权限，而另一些用户不给root权限，这种情况除了用两个不同的动态系统用户之外，还有什么推荐的实现方案吗？

**Comment by Laplacence** [comment]
@knwng 你可以在服务器上操作sudo组实现这个功能。

**Comment by knwng** [comment]
@Laplacence 好的谢谢，我在使用中还发现了一个问题，虽然动态系统用户会以不同的用户身份登录系统，但他们的HOME目录都被设定成了相同的系统用户的HOME目录，这样不同用户的文件还是容易混淆，可以让不同的动态系统用户使用不同的HOME目录吗？谢谢！

**Comment by jym503558564** [comment]
@knwng 目前动态系统用户都使用各自的home目录
