### ISSUE TITLE
[Question] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5583]
**请描述您的问题.**
我遇到同样的问题：https://github.com/jumpserver/coco/issues/280
version：jumpserver和coco的tag都是1.5.2  

![image](https://user-images.githubusercontent.com/10806595/107137650-951a7400-6949-11eb-9ea6-aa6b31dec74f.png)
![image](https://user-images.githubusercontent.com/10806595/107137651-9e0b4580-6949-11eb-9c39-12d83a3b8332.png)

**Comment by ibuler** [comment]
是不是 key 没有注册成功，没有从服务器获取到配置

**Comment by bingws** [comment]
![image](https://user-images.githubusercontent.com/10806595/108299782-0bd13000-71da-11eb-89d7-aeb03d38f95b.png)
有注册成功

**Comment by bingws** [comment]
猜测是jumpserver-python-sdk部分路由不兼容了。。
