### ISSUE TITLE
[Feature] luna界面默认显示当前用户水印

### ISSUE THREAD

**Issue by TheNovemberRain** [jumpserver/jumpserver#5584]
为了防止第三方运维直接在堡垒机上截图，把数据泄露出去，然后又很难找到源头，建议在luna上加上水印。
各种协议下的运维界面都有水印，像奇安信的堡垒机就有这种功能。
理想的效果图如下：
![1](https://user-images.githubusercontent.com/27805633/107142271-9c04af00-6968-11eb-834f-98d964693f37.png)

**Comment by ibuler** [comment]
你刚才这个图是 图片上添加的？还是修改的 css ? guacamole 可能没那么容易修改

**Comment by TheNovemberRain** [comment]
> 你刚才这个图是 图片上添加的？还是修改的 css ? guacamole 可能没那么容易修改

效果图是我自己P的，不是CSS。
说下我个人的一些想法：
本身是觉得如果只在guacamole上加，或许会更好，理由是如果guacamole传输过来的png就有水印在上面，能够有效防止有人打开开发者工具直接删掉水印。
但是又有另外一个问题：这样会不会导致监控界面，显示的也是当前运维者的水印，这估计也不好。

但如你所说，应该很困难……于是觉得就算在luna上实现也行吧
看了下奇安信堡垒机的水印用的就是CSS，恐怕我想得太多。
水印覆盖整个luna或者只覆盖luna中winContainer这个div，感觉都可以。

**Comment by ibuler** [comment]
年后研究一下

**Comment by TheNovemberRain** [comment]
> 年后研究一下

谢谢，也祝官方新年快乐

**Comment by chenlin0802** [comment]
> 年后研究一下

问下官方， 这个功能有开发计划么。 谢谢
