### ISSUE TITLE
[Question] 2.7.0 普通用户登录堡垒机web页面的时候间歇性出现账户密码都正确但是提示“用户名或密码不正确”

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5585]
**JumpServer 版本(v1.5.9以下不再支持)**

2.7.0
**浏览器版本**

chrome 88
**Bug 描述**
普通用户登录堡垒机的web页面的时候会偶尔出现“用户名或密码不正确，请重新输入”，但是用户输入的密码都是正确的，查看登录日志，认证方式为空，原因为 “password_failed”，麻烦帮看下可能是哪里有问题，谢谢！

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![image](https://user-images.githubusercontent.com/28044296/107167590-365e0480-69f4-11eb-868e-046ba7bfc85c.png)
![image](https://user-images.githubusercontent.com/28044296/107167811-c603b300-69f4-11eb-941e-3638b4ec5a8c.png)

**Comment by ibuler** [comment]
容易复现吗？

**Comment by aiaiduo** [comment]
> 容易复现吗？我有个怀疑就是密码的 **加解密**，现在密码传输是单独加密的，使用的是 浏览器会话的 id，这个是有过期时间的，如果说登录页面打开了很长时间了，登录可能会出错，再登录一次就好了

经常出现这个问题，但是有基本都是页面超时退出后重新登录的时候才会出现这个问题，第一次打开浏览器登录貌似没有出现过，页面超时后登录经常出现这个，有办法优化下不？

**Comment by ibuler** [comment]
这个可能是由于这个用户是 英文模式下登录的，所以是 Password 了，https://github.com/jumpserver/jumpserver/blob/master/apps/audits/signals_handler.py#L42

**Comment by aiaiduo** [comment]
> 这个可能是由于这个用户是 英文模式下登录的，所以是 Password 了，https://github.com/jumpserver/jumpserver/blob/master/apps/audits/signals_handler.py#L42

嗯，好的，那只要是和这个密码错误的问题没有关系就没事的，那这个超时后再登录提示密码错误这个有啥解决办法吗？

**Comment by ibuler** [comment]
@wojiushixiaobai 我们 demo 站能复现这个问题吗？

**Comment by aiaiduo** [comment]
> > 这个可能是由于这个用户是 英文模式下登录的，所以是 Password 了，https://github.com/jumpserver/jumpserver/blob/master/apps/audits/signals_handler.py#L42
> 
> 嗯，好的，那只要是和这个密码错误的问题没有关系就没事的，那这个超时后再登录提示密码错误这个有啥解决办法吗？

@ibuler 这个问题你们能复现么？

**Comment by ibuler** [comment]
不能

**Comment by aiaiduo** [comment]
> 不能

@ibuler 我的配置了这一个，你们可以试试，还有我电脑前一天一直不关机，浏览器一直是是堡垒机登录状态不关掉，第二天早上直接用未关闭的页面登来登录也会出现这个问题。
![image](https://user-images.githubusercontent.com/28044296/108789592-8c66a680-75b5-11eb-89d2-a94f68e160ac.png)

**Comment by aiaiduo** [comment]
> > 不能
> 
> @ibuler 我的配置了这一个，你们可以试试，还有我电脑前一天一直不关机，浏览器一直是是堡垒机登录状态不关掉，第二天早上直接用未关闭的页面登来登录也会出现这个问题。
> ![image](https://user-images.githubusercontent.com/28044296/108789592-8c66a680-75b5-11eb-89d2-a94f68e160ac.png)
有啥排查的方式么，比如开启debug 在哪些日志中可以查看下，只要是前天不关机，堡垒机是登录状态，第二天早上直接按F5刷新堡垒机登录界面后然后输入用户名、密码登录，就会出现这个问题。

**Comment by zhglhy** [comment]
我用的版本2.7.1，新建的用户密码登录方式，设置完密码一直登录不进去，跟上面描述一样。之前新建一个用户是可以正常登录jumpserver的。

**Comment by kuugen96** [comment]
这个问题最后是如何的解决的？请问
