### ISSUE TITLE
[Question] 0.3.1 升级为正式版本

### ISSUE THREAD

**Issue by dong9205** [jumpserver/jumpserver#5587]
现有版本: 0.3.1
问题: 升级为正式版, 无文档.

从0.3.1版本我们开始使用, 后边一直为升级.  现在希望能在生产环境使用上正式版本的jumpserver, 但是我百度、谷歌、查看先关github issue 并未找到一个从0.3.x 版本升级的文档, 求一份0.3.1 升级到正式版本的文档.

多谢!!!

**Comment by ibuler** [comment]
0.3 和 2.0 版本 是不能直接升级的，所以没有文档

**Comment by dong9205** [comment]
> 0.3 和 2.0 版本 是不能直接升级的，所以没有文档

是否可以通过升级一些中间版本进行兼容升级呢？ 如不没办法的话，我这边就重建一套新的jumpserver. 非常感谢!

**Comment by ibuler** [comment]
没有办法，只能重新部署

**Comment by dong9205** [comment]
> 没有办法，只能重新部署

多谢!
