### ISSUE TITLE
邮件磁盘告警上限设置

### ISSUE THREAD

**Issue by Zyp-gdhz** [jumpserver/jumpserver#5588]
最近一直收到这种邮件告警

磁盘使用率超过 80%: /opt/jumpserver/data => 80.1

实际挂载的目录磁盘空间还很大，这个80%的峰值在哪里可以设置

**Comment by ibuler** [comment]
这个目前是不能设置的，直接写死到代码中的

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/pull/5605/files 

已修改，下个版本支持 关闭

**Comment by Zyp-gdhz** [comment]
> https://github.com/jumpserver/jumpserver/pull/5605/files
> 
> 已修改，下个版本支持关闭

在哪个版本，还是只有企业版有此功能
