### ISSUE TITLE
[Bug] 在系统用户指定了资产 , 还是会弹出框来让选择一个用户.

### ISSUE THREAD

**Issue by lian233** [jumpserver/jumpserver#5589]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.7.1 

**浏览器版本**
 87.0.4280.88

**Bug 描述**

在系统用户指定了1个资产 , 还是会弹出框来选择一个用户.

![image](https://user-images.githubusercontent.com/14799111/107180999-efccd200-6a14-11eb-9fac-2b4082239354.png)
![image](https://user-images.githubusercontent.com/14799111/107181121-2571bb00-6a15-11eb-943a-d3a5f8d45cdc.png)
![image](https://user-images.githubusercontent.com/14799111/107181024-f9563a00-6a14-11eb-849c-b82fa9134d33.png)
![image](https://user-images.githubusercontent.com/14799111/107181041-03783880-6a15-11eb-8879-68c470ce6efb.png)

**Comment by ibuler** [comment]
那里的弹出判断是根据授权规则来的，而不是资产上有几个系统用户
