### ISSUE TITLE
[Bug] 发送邮件修改密码发送成功，但是收不到邮件

### ISSUE THREAD

**Issue by jinkunzhao** [jumpserver/jumpserver#5591]
**JumpServer 版本(v1.5.9以下不再支持)**
1.5.4-2 GPLv2

**浏览器版本**
Google Chrome   88.0.4324.146

**Bug 描述**
发送邮件修改密码发送成功，但是收不到邮件，redis中的key  celery中有消息生产，列表长度为5000多，但是没有消费，flower中worker celery@jms_core状态显示“Offline”，core容器中没有看到报错日志，在redis中执行bgsave后重启所有组建也不行，求各位大神帮忙

**Bug 重现步骤(有截图更好)**
1.  
![FED2E7C1-5CA2-490B-851A-111211C6873F](https://user-images.githubusercontent.com/35217424/107205865-4d731580-6a39-11eb-875f-9dba881fd1f8.png)

2. 
3.

**Comment by ibuler** [comment]
离线了应该会自动重启才对啊，为什么一直离线呢？怎么部署安装的呢？

**Comment by jinkunzhao** [comment]
> 离线了应该会自动重启才对啊，为什么一直离线呢？怎么部署安装的呢？

**Comment by jinkunzhao** [comment]
> 离线了应该会自动重启才对啊，为什么一直离线呢？怎么部署安装的呢？

用docker-compose编排部署的，将redis中celery  key删除，然后再docker-compose down && docker-compose up -d 之后celery@jms_core状态会显示“Online”，但是运行一段时间就“Offline”了，查看celery key有消息产生，但是不能消费

**Comment by jinkunzhao** [comment]
> 离线了应该会自动重启才对啊，为什么一直离线呢？怎么部署安装的呢？

重启jms_core之后会出现“Online”但是马上就“Offline”，请问消费redis的机制是怎样的 @ibuler

**Comment by ibuler** [comment]
看看进程是不是还在 

```
ps axu | grep celery 
```

**Comment by jinkunzhao** [comment]
![1A5AB1FB-7241-4E95-BFC2-AC25ED23B4FE](https://user-images.githubusercontent.com/35217424/108447277-8feaec80-729a-11eb-931e-edb6e669a2fa.png)

**Comment by jinkunzhao** [comment]
上面图片是在core容器里面看到的，进程好像还在 @ibuler

**Comment by ibuler** [comment]
那再排查一下 内存和cpu 情况

**Comment by jinkunzhao** [comment]
cpu和内存都还够用  在什么情况下会出现“offline”   是因为版本太低了吗  @ibuler

**Comment by ibuler** [comment]
这个还不太清楚，进程应该会定时心跳，写到 redis 中

**Comment by jinkunzhao** [comment]
我点击忘记密码发送邮件后，会写入redis 3库中的celery key，但是没有消费，请问这个消费的机制是怎么样的，这个异步过程程序的消费者是怎么消费的，什么情况下会显示“offline”呢  @ibuler

**Comment by ibuler** [comment]
offline 才是根本原因

**Comment by jinkunzhao** [comment]
> offline 才是根本原因

什么情况下会导致offline，也看不到具体的日志
