### ISSUE TITLE
[Bug]推送系统用户到资产时会推送多次 

### ISSUE THREAD

**Issue by wanglong168** [jumpserver/jumpserver#5596]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**浏览器版本**
chrome 版本 88.0.4324.150

**Bug 描述**
当资产有多个版本的密码时，推送系统用户到资产时会推送多次

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
可以截图吗？

**Comment by wanglong168** [comment]
2.6版本之前 我更新完密码后推送系统用户到资产 默认只会推送最新的密码到资产也就是推送一次 现在推送会推送和版本一致的次数 如下图所示就是会推送四次
[cid:image001.png@01D6FF9A.A4ABB050]

[cid:image002.png@01D6FF9A.A4ABB050]
发件人: 老广 <notifications@github.com>
发送时间: 2021年2月9日 21:21
收件人: jumpserver/jumpserver <jumpserver@noreply.github.com>
抄送: Longbao Wang <Longbao.Wang@shangri-la.com>; Author <author@noreply.github.com>
主题: Re: [jumpserver/jumpserver] [Bug]推送系统用户到资产时会推送多次 (#5596)

This e-mail is from an external source. Be alert and exercise care.
此邮件发送自公司外部，请保持警惕。



可以截图吗？

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjumpserver%2Fjumpserver%2Fissues%2F5596%23issuecomment-775930002&data=04%7C01%7Clongbao.wang%40shangri-la.com%7C58ae43e6d5364622e21608d8ccfd894f%7Cb4b94aa124084fce9babf498c1f95951%7C0%7C0%7C637484736620243043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BkvNgW62htJCs8ywHlptnkWBy4X8qmnnzl45gHPFnqc%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASZDSXV7B65UME2Q6BA5YHTS6EZDPANCNFSM4XKR5WCA&data=04%7C01%7Clongbao.wang%40shangri-la.com%7C58ae43e6d5364622e21608d8ccfd894f%7Cb4b94aa124084fce9babf498c1f95951%7C0%7C0%7C637484736620253041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oDvu%2FHnyjyNqkpY9oXWDfG2efNJKAwNLATUrvrHfijk%3D&reserved=0>.

******************************************************************************
The information contained in this message may be privileged and confidential and protected from disclosure. Any dissemination, distribution, copying of or taking of any action in reliance upon this message, other than to/by the addressee, is strictly prohibited.
If you have received this in error, please destroy it and notify us immediately. Opinions, conclusions and other information in this message that do not relate to the official business of our company shall be understood as neither given nor endorsed by it and we disclaim all liability for any such statements.
******************************************************************************
