### ISSUE TITLE
[Bug] 内存小于 8G，JumpServer 所在机器的内存需要至少 8G

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#5597]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**[root@ip-172-31-25-39 centos]# curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.7.1/quick_start.sh | bash
[ ERROR ] Memory less than 8G (内存小于 8G，JumpServer 所在机器的内存需要至少 8G)

**Bug 重现步骤(有截图更好)**
1.  准备一台 2核4G （最低）且可以访问互联网的 64 位 Linux 主机；
2. 文档中写的不是4G最低吗，怎么变成8G最低了
3.

**Comment by ibuler** [comment]
上上个版本，启动了几个任务队列，导致内存占用过多，下个版本优化一下，保证 4G 可用

**Comment by dandannnn** [comment]
可以自己改一下脚本判断，然后bash一下

**Comment by ibuler** [comment]
是的，可以直接修改那个安装脚本
