### ISSUE TITLE
[Question] jumpserver支持的ssh私钥到底是什么格式

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#5598]
**请描述您的问题.**
ppk不行
openssh不行
ssh.com不行

**Comment by ibuler** [comment]
就是 rsa 格式的，centos 上生成的证书是可以的

**Comment by ibuler** [comment]
mac上现在生成的是 openssh 格式的，Python库不支持，不过我们应该考虑一下转换

https://stackoverflow.com/questions/45829838/paramiko-connect-with-private-key-not-a-valid-openssh-private-public-key-fil

未来支持

**Comment by ibuler** [comment]
https://github.com/paramiko/paramiko/issues/1313

在mac上可以这样生成证书 

```
ssh-keygen -t rsa -b 4096 -C "email@email.com" -m PEM
```

**Comment by ibuler** [comment]
新的 paramiko 版本好像支持了 OPENSSH 格式

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/pull/5604
