### ISSUE TITLE
[Bug] 用iOS safari 浏览器访问Jumpserver 无限跳转

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#5599]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本** safari 

**Bug 描述**

用iOS safari 浏览器访问Jumpserver 登录后无限跳转，不能进入后台

**Bug 重现步骤(有截图更好)**
1.  用iOS safari 浏览器访问Jumpserver 登录后无限跳转，不能进入后台
2. 
3.

**Comment by ibuler** [comment]
收到，节后处理

**Comment by ibuler** [comment]
@orangemio 看看

**Comment by orangemio** [comment]
@louishot 你用的什么版本？ 我用最新版本测试了下 可以用

**Comment by louishot** [comment]
> @louishot 你用的什么版本？ 我用最新版本测试了下 可以用

Version v2.7.1 GPLv2.
IOS 14.4

**Comment by jym503558564** [comment]
测试了IOS 14.0没有复现
