### ISSUE TITLE
4.0资产组推送报错，无法推送系统用户

### ISSUE THREAD

**Issue by yokiy0828** [jumpserver/jumpserver#560]
4.0资产组推送报错，无法推送系统用户
<img width="1422" alt="wx20170721-194224 2x" src="https://user-images.githubusercontent.com/25323406/28462214-cf18ecfa-6e4c-11e7-9ba8-68e3cd3c48cb.png">

**Comment by zsjohny** [comment]
@yokiy0828  https://github.com/jumpserver/jumpserver/pull/542/files

**Comment by yokiy0828** [comment]
还是不行
<img width="1439" alt="jump" src="https://user-images.githubusercontent.com/25323406/28490367-ece64822-6f0a-11e7-8ae9-8b6503d68b24.png">

**Comment by yokiy0828** [comment]
<img width="632" alt="jump2" src="https://user-images.githubusercontent.com/25323406/28490373-206e2cd2-6f0b-11e7-98c8-1ba6eacd277b.png">

**Comment by yokiy0828** [comment]
@zsjohny

**Comment by yokiy0828** [comment]
@ibuler 帮忙看看这个bug啊

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28497010-525ce7b2-6fae-11e7-8f19-8208e318c5db.png)

**Comment by ibuler** [comment]
fixed
