### ISSUE TITLE
[Question] ssh客户端连接jumpserver进入到最终资产服务器后无法退出。

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#5600]
**请描述您的问题.**
ssh客户端连接jumpserver进入到最终资产服务器后无法退出返回资产列表。
因为是服务器ssh转串口连路由器，exit不能发送断开信号，所以不能退出。jumpserver有没有一种快捷键用于强制断开当前资产服务器。这在资产服务器卡死，断流时也非常有用。

**Comment by ibuler** [comment]
直接关闭连接，重新连接不就可以了

**Comment by louishot** [comment]
> 直接关闭连接，重新连接不就可以了

但是这得每次都要OTP了啊。

**Comment by jym503558564** [comment]
exit 可以退出。
