### ISSUE TITLE
[Question] 2.7.1 无法RDP Windows服务器

### ISSUE THREAD

**Issue by greatzhangq** [jumpserver/jumpserver#5601]
**请描述您的问题.**
新部署2.7.1版本，尝试RDP Windows 2016服务器时遇到如下错误，系统平台尝试使用过Windows和Windows 2016。
直接mstsc到服务器没有问题

![Capture](https://user-images.githubusercontent.com/22163793/108008275-fbcf1a00-703a-11eb-9559-4afacd8b6ca1.PNG)

**Comment by ibuler** [comment]
系统用户和资产协议改成都支持 rdp

**Comment by greatzhangq** [comment]
谢谢，没留意到系统用户这边还有选项。  另外一个新问题在文件管理界面， 上传文件时显示 “Unable to upload "Connection Lost", 这个应如何排查，谢谢！

**Comment by LeeEirc** [comment]
@greatzhangq 查看` jms_koko`日志， 大概率是资产` sftp`  连接失败。

**Comment by jym503558564** [comment]
连接rdp资产，创建资产和创建系统用户应该都选择rdp协议。如还有其他问题，欢迎提Issues
