### ISSUE TITLE
[Feature] 不支持 vscode 差评

### ISSUE THREAD

**Issue by innerlee** [jumpserver/jumpserver#5602]
Thanks!

**Comment by ibuler** [comment]
研究中，不太理解机制

**Comment by innerlee** [comment]
加油！

**Comment by Kingflyinger** [comment]
大哥加油，兄弟真的很需要支持vscode 的remote-ssh插件

**Comment by tkisme** [comment]
都很需要，目前因为这个将迁移计划都搁置了，希望早日支持proxycommand

**Comment by gssjl2008** [comment]
同上， 开了堡垒机给同事，同事非要用vscode remote ssh。。。蛋疼

**Comment by jym503558564** [comment]
最新版本已支持vscode remote ssh，可更新至最新版本进行测试。
