### ISSUE TITLE
[Feature] 判断资产是否已经开启，不应重复开启而应该切换TAB。

### ISSUE THREAD

**Issue by enthanlee** [jumpserver/jumpserver#5603]
同一资产重复点击前应该判断是否已在Luna中开启，如果已经开启，则切换至该tab页面，而不是重复开启。

**Comment by ibuler** [comment]
那假如用户就是想连接两个呢，一个操作着，一个看日志

**Comment by enthanlee** [comment]
> 那假如用户就是想连接两个呢，一个操作着，一个看日志

但是实际上情况是：
1。如果点击的是vnc，则两个连接窗口内容是一样的，所以并无意义。
2。如果点击的是自动登陆的RDP资产，则会踢出第一个rdp连接。

需求的标题我写的不严谨。
实际应该是在点击资产之后，判断是否是vnc，以及是否是已经自动登陆的rdp资产。以此来决定是否新开tab还是切换已存在的tab。

另外，关于点击资产后的新建tab还有一个很明显的bug：
如果点击完资产后，不等tab中显示画面就去点击下一个资产，则第一个资产的tab就会黑屏，只能关闭重开。
这在需要批量登陆大量资产时非常不方便，必须一个一个慢慢等画面及登陆完成。
