### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mike0476** [jumpserver/jumpserver#5606]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.2.2 GPLv2.

**浏览器版本**
chrome 

**Bug 描述**
web终端连接主机报错error: ssh: could not start shell
只有个别两台主机偶尔有问题，其它主机都是正常的。尝试删除有问题的资产重新添加问题仍未解决。

**Bug 重现步骤(有截图更好)**
1.  
2. 
![image](https://user-images.githubusercontent.com/11345000/108306613-7dfc4180-71e7-11eb-89e9-2a3ac9763da5.png)
![image](https://user-images.githubusercontent.com/11345000/108306663-9e2c0080-71e7-11eb-9c83-a44b5bc86a54.png)

**Comment by LeeEirc** [comment]
@mike0476 新版本已经修复这个问题

**Comment by mike0476** [comment]
> @ mike0476新版本已经修复这个问题

不升级版本，有什么临时修复的方法吗？

**Comment by LeeEirc** [comment]
没有。需要升级，这是代码层面的优化。
