### ISSUE TITLE
[Bug] ES认证无效

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#5607]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.5 - v2.7.1

**浏览器版本**
无关

**Bug 描述**
ES：http://es_user:es_password@es_host:es_port
无法提交使用

**Bug 重现步骤(有截图更好)**
1.  创建 ES 命令存储
2.  主机使用带账号密码的身份认证 http://elastic:elastic@192.168.100.215:9200
3.  提交报错 
```
  File "/opt/jumpserver/apps/terminal/serializers/storage.py", line 161, in command_storage_es_host_format_validator
    _host, _port = h.netloc.split(':')
ValueError: too many values to unpack (expected 2)
```

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/pull/5609
