### ISSUE TITLE
docker 版 重定向 https  luna 5000 报错

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#561]
builtins.RecursionError
RecursionError: maximum recursion depth exceeded while calling a Python object

@ibuler

**Comment by zsjohny** [comment]
@ibuler

**Comment by ibuler** [comment]
https ?

**Comment by zsjohny** [comment]
@ibuler  对 proxy 我代理  127 过不去 只能代理 已经解析好的域名，另外 如图

**Comment by yokiy0828** [comment]
我也出现，但是多搞几次无缘无故就好了

**Comment by zsjohny** [comment]
@yokiy0828  你怎么搞的给我一下配置被

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28493146-c14e3614-6f43-11e7-94d6-9f24beb7d02f.png)

**Comment by yokiy0828** [comment]
上面是跳板机外网IP，下面是域名

**Comment by zsjohny** [comment]
http 加端口没问题 主要是 https

**Comment by yokiy0828** [comment]
转跳https？

**Comment by zsjohny** [comment]
@yokiy0828  对
    environment:
      - "JUMPSERVER_ENDPOINT=http:/XXX:8080"  不能是https  如果是就会有和你一样的报错

**Comment by yokiy0828** [comment]
这不用设置呀，我这是设置的127.0.0.1:8080

**Comment by zsjohny** [comment]
WARNING:root:Connect endpoint: http://127.0.0.1:8080 error
coco          | ERROR:root:Register terminal coco failed
coco          | Register terminal failed, may behave been exist, you should look forthe terminal access key, set in config, or put it in access key store
@yokiy0828

**Comment by yokiy0828** [comment]
你coco没注册激活吧

**Comment by zsjohny** [comment]
根本不会提示激活 提示激活 会提示如下日志：
WARNING:luna.service:App auth failed, Access key error or need admin active it

**Comment by yokiy0828** [comment]
激活是需要去jumpserver里面的

**Comment by zsjohny** [comment]
对 但是也有log 提示啊 兄弟

**Comment by yokiy0828** [comment]
激活后可以忽略啊

**Comment by yokiy0828** [comment]
coco没问题，现在有问题的是luna

**Comment by zsjohny** [comment]
我说的不清晰么 走回环不会提示 激活 会提示 已经激活完毕 实际没激活呢  明白了吗

**Comment by zsjohny** [comment]
原理不是一样么  有什么区别么

**Comment by yokiy0828** [comment]
截图看看你问题在哪？ luna 是https的问题。

**Comment by zsjohny** [comment]
最后说一下：问题点在于：
1. 走回环可以解决 但是 我不能通过回环走endpoint 会有激活的bug。
2. 走解析过去 由于Django 调用的原因 会有重定向循环的问题。
so clear？

**Comment by yokiy0828** [comment]
激活什么bug？我是走的回环正常激活了。

**Comment by ibuler** [comment]
#564

**Comment by zsjohny** [comment]
@ibuler   
我已经 移除 https://github.com/jumpserver/jumpserver/blob/dev/apps/templates/_footer.html#L4
为什么还会加载？（👇这个影响https，我不想加载他）
http://www.jumpserver.org/img/evaluate_avatar1.jpg
<img width="566" alt="qq20170724-150616 2x" src="https://user-images.githubusercontent.com/8543865/28511839-a8e45b0a-7081-11e7-98df-152e3d2a91df.png">
