### ISSUE TITLE
[Question] V2.6.2 部分用户使用chrome浏览器从linux服务器上下载超过1024兆的文件就失败报“网络错误”

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5613]
**请描述您的问题.**
部分用户使用chrome 88.0.4324.182（正式版本） （64 位）的浏览器下载超过2个G的文件 ，下载到1024兆时就提示“失败-网络错误”，有一部分用户chrome也是这个版本下载又是正常的， nginx里我也配置的是 client_max_body_size 4096m;  不知道这个是哪里的问题。

**Comment by LeeEirc** [comment]
看下 `jms_koko` 日志，有没有错误，再检查下是否是网络不稳定？

**Comment by aiaiduo** [comment]
![image](https://user-images.githubusercontent.com/28044296/108585188-03b3f480-7382-11eb-995a-3fe6b24f5272.png)
网络是正常的，日志这里没有看出来是啥问题。

**Comment by aiaiduo** [comment]
![image](https://user-images.githubusercontent.com/28044296/108585197-19291e80-7382-11eb-87f9-eb7672363022.png)

**Comment by LeeEirc** [comment]
从日志上看，大概率是中间网络出现问题了。

**Comment by aiaiduo** [comment]
> 看下 `jms_koko` 日志，有没有错误，再检查下是否是网络不稳定？
我c测试从终端到堡垒机，从终端到要下载文件的服务器，从堡垒机到要下载文件的服务器网络正常，ping都不丢包，这个图是另外一台终端到同一台服务器上下载文件，这是下载是正常的，是否类似和websocket超过默认的6个有关。
![image](https://user-images.githubusercontent.com/28044296/108585430-80939e00-7383-11eb-95f3-c2b3b32428b5.png)
![image](https://user-images.githubusercontent.com/28044296/108585510-d36d5580-7383-11eb-80c9-711177055476.png)
![image](https://user-images.githubusercontent.com/28044296/108585534-ed0e9d00-7383-11eb-880d-293a77273329.png)

**Comment by aiaiduo** [comment]
> 从日志上看，大概率是中间网络出现问题了。

我感觉下载失败的那台电脑下载速率是没有我可以正常下载的这台电脑快，但是下载失败的时候从终端到堡垒机，从终端到要下载文件的服务器，从堡垒机到要下载文件的服务器ping 一个包都不丢，我觉得网络没有问题。

**Comment by aiaiduo** [comment]
@LeeEirc 我测试了一下，果然是我把可以正常下载终端的网卡的速率强制为百兆全双工后就出现下载2G的问题下载到1024兆的时候就出现“网络错误” 然后就下载失败了，您可以按照这个设置复现下问题，我们终端速率是百兆的电脑还是挺多的，这个能在哪里进行优化下么？
![image](https://user-images.githubusercontent.com/28044296/108586147-7d021600-7387-11eb-92b3-0fe2b3715ccf.png)
![image](https://user-images.githubusercontent.com/28044296/108586101-43310f80-7387-11eb-9975-d7c1a6ae6dab.png)
![image](https://user-images.githubusercontent.com/28044296/108586119-547a1c00-7387-11eb-9aa5-321476da02f4.png)

**Comment by LeeEirc** [comment]
@aiaiduo 检查是否存在超时的配置

**Comment by aiaiduo** [comment]
> @aiaiduo 检查是否存在超时的配置

![image](https://user-images.githubusercontent.com/28044296/108590403-556a7800-739e-11eb-876a-5f5488f5a3ab.png)
您指的是这里么？这个是我有配置

**Comment by LeeEirc** [comment]
@aiaiduo 浏览器到JMS服务的中间网络，如 nginx 等负载设备。下载速率慢，从而引发连接超时。

**Comment by aiaiduo** [comment]
> @aiaiduo 浏览器到JMS服务的中间网络，如 nginx 等负载设备。下载速率慢，从而引发连接超时。

这个能啥优化下么， 比如延长超时时间呢？

**Comment by LeeEirc** [comment]
这不是产品上面需要修改的地方，而是看你部署。

**Comment by aiaiduo** [comment]
> 这不是产品上面需要修改的地方，而是看你部署。

ok，多谢！我再检查下。
