### ISSUE TITLE
关于luna和lina v2.7.1容器镜像的bug建议[Bug] 

### ISSUE THREAD

**Issue by zhangwa5** [jumpserver/jumpserver#5615]
**JumpServer 版本(v1.5.9以下不再支持)**
Jumpserver版本为2.7.1，采用手动安装，mysql和redis单独安装。

**浏览器版本**
浏览器是谷歌，本次bug与浏览器无关。

**Bug 描述**
按照手动安装步骤安装完成后，执行jms_ctl start，发现容器jms_luna和jms_lina处于（unhealthy）状态。通过对两个镜像执行docker inspect jms_lina/jms_luna，发现报错信息为【"Output": "Connecting to localhost ([::1]:80)\nwget: can't connect to remote host: Connection refused\n"】，分析发现是容器的健康检查healthcheck出错，healthcheck命令为【wget http://localhost/luna/ -O -】。于是分别进入jms_luna和jms_lina容器，执行此命令，发现报错一致，这个命令是访问Nginx 80 端口，ipv6协议。但是在两个容器里查看端口监听，发现ipv6 80端口并没有监听起来。所以我才用的解决办法是修改两个容器内/etc/nginx/conf.d/default.cong，增加【listen [::]:80 ipv6only=on;】启用Nginx ipv6的80端口监听。然后重启两个容器，发现问题解决，状态为健康。

**建议
建议修改luna和lina原始镜像，修改里面Nginx配置文件，启用ipv6 80端口监听。

**Comment by ibuler** [comment]
已通过 使用 curl 探测解决

**Comment by ibuler** [comment]
https://github.com/jumpserver/installer/blob/dev/compose/docker-compose-app.yml#L96
