### ISSUE TITLE
无法访问web！【关闭这个issue，问题已解决】

### ISSUE THREAD

**Issue by calistochen** [jumpserver/jumpserver#562]
我按照v0.3.2 基于 RedHat 的系统安装在腾讯云上完之后运行python run_server.py，无法访问到web。腾讯云环境是内弯10.154.**的网络，对应一个公网IP（gre网络）。
下面是我的配置
[base]
url = http://10.154.**
key = 5v2lj7ax4rjjghmm
ip = 0.0.0.0
port = 8000
log = debug

[db]
engine = mysql
host = 127.0.0.1
port = 3306
user = jumpserver
password = 5Lov@wife
database = jumpserver

[mail]
mail_enable = 1
email_host = 10.154.***
email_port = 25
email_host_user = 
email_host_password = 
email_use_tls = False
email_use_ssl = False

[connect]
nav_sort_by = ip

**Comment by calistochen** [comment]
请求一直到达不了，telnet端口不通！可是netstat显示端口正在监听，iptables和selinux都已经关闭

**Comment by hellorocky** [comment]
你确定这是jumpserver的问题, 不是网络的问题?

**Comment by calistochen** [comment]
什么问题？没有任何输出

**Comment by calistochen** [comment]
因为腾讯云上安全组没有开放端口
