### ISSUE TITLE
文档typo

### ISSUE THREAD

**Issue by BilibiliHentai** [jumpserver/jumpserver#5620]
[官网文档中的文件管理页面](https://docs.jumpserver.org/zh/master/user-guide/terminal/web-sftp/)给出了命令`sftp -p 2222 用户名@JumpServer IP地址`，其中`-p`应该是`-P`

**Comment by wojiushixiaobai** [comment]
感谢反馈，已经修正。[ffd06660998e7eadf5c175cf404bf48647e870ec](https://github.com/jumpserver/docs/commit/ffd06660998e7eadf5c175cf404bf48647e870ec)
