### ISSUE TITLE
[Bug] 文件管理功能在禁用资产时，依然可以使用

### ISSUE THREAD

**Issue by tonyaszhu** [jumpserver/jumpserver#5622]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**浏览器版本**
Google chrome  v-88.0.4324.182

**Bug 描述**

linux资产当禁用时，合理现象是
1、用户无法远程登录命令行
2、用户无法通过sftp文件管理功能上传下载删除文件

但是实际现象是
1、确实无法登录
2、仍可上传下载删除文件

注：希望通过禁用资产的方式管理，比如服务器正常运行时不希望任何人登录操作，只有当维护或更新时，管理员临时手动激活相应资产，以达到更好的安全性。希望团队予以帮助，谢谢！

**Bug 重现步骤(有截图更好)**
1.  禁用某个linux资产

2. 验证：命令行不能远程
![image](https://user-images.githubusercontent.com/33281209/108596596-fec26580-73c0-11eb-90a8-be82500627b3.png)

3. 验证：文件管理依然可以使用
![Uploading image.png…]()

**Comment by jym503558564** [comment]
- 确实存在该问题，已反馈给开发人员，请关注我们后续版本发布。

**Comment by tonyaszhu** [comment]
好的，感谢！
