### ISSUE TITLE
[Question] 请问，web页面有超时退出的设置吗？

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#5623]
**请描述您的问题.**
在使用中留意到web端登录后就不会自动注销，但点击资产后弹出的luna页面，会在设定的30分钟后自动断开会话，但也仅仅是断开会话，完全可以在页面重新点击资产连接。
请问是否有办法在设定的时间（譬如无任何动作30分钟）后将web端注销掉呢？或者所谓可选项？
谢谢

**Comment by wojiushixiaobai** [comment]
[参数列表](https://docs.jumpserver.org/zh/master/admin-guide/env/)
```
SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间
SESSION_EXPIRE_AT_BROWSER_CLOSE=FALSE  # 关闭浏览器失效登录的 session
```
