### ISSUE TITLE
[Bug] MFA认证弹框重复出现

### ISSUE THREAD

**Issue by dream-mo** [jumpserver/jumpserver#5624]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.5

尝试了多个版本, 一直到最新版本都试了一下, 该bug一直存在.
**浏览器版本**
无

**Bug 描述**

shell登录koko.  开启MFA认证后, 第一次输入认证弹框信息通过认证, 进入主页, 重复又弹出认证框.

**Bug 重现步骤(有截图更好)**
1.  输入正确的用户名、密码后出现第一个认证弹框(正确)
2. 认证通过后， 又重复出现一次认证弹框. (这个弹窗关闭不影响使用, 可输入验证码也可关闭弹窗, bug)

![image](https://user-images.githubusercontent.com/22147280/108622086-7780fa80-7471-11eb-8f84-6ae930ee550e.png)

**Comment by LeeEirc** [comment]
Duplicate of #https://github.com/jumpserver/koko/issues/551
