### ISSUE TITLE
[Bug] Windows上传文件失败

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#5625]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.0+xpack

**浏览器版本**
Chrome 88.0.4324.182 (Official Build) (64-bit)

**Bug 描述**
Windows上传文件到guacamole网络驱动器，经常上传失败。

**Comment by wojiushixiaobai** [comment]
[参数列表](https://docs.jumpserver.org/zh/master/admin-guide/env/)
```
SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间
SESSION_EXPIRE_AT_BROWSER_CLOSE=FALSE  # 关闭浏览器失效登录的 session
```

**Comment by Laplacence** [comment]
@wojiushixiaobai 有使用过上述配置，依旧会有失败的情况。

**Comment by jym503558564** [comment]
最新版本已使用lion组件替换原有的guacamole组件，请更新至最新版本进行测试。如有其他问题可再次提issues.
