### ISSUE TITLE
有什么办法可以直接远程桌面连堡垒机吗

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#5626]
可以不通过web页面直接远程桌面连堡垒机然后选择windows机器访问吗
就跟ssh 堡垒机的9022端口一样

**Comment by Laplacence** [comment]
看看README就知道，很显然目前提供的功能没有直接通过rdp登陆的。

**Comment by jym503558564** [comment]
感谢反馈，目前windows只能通过web页面。请持续关注我们后续版本发布情况。
