### ISSUE TITLE
开源版本的可以在连接linux远程主机是调用本地的第三方工具例如xshell,putty之类登录吗？

### ISSUE THREAD

**Issue by clcvi123** [jumpserver/jumpserver#5627]
**请描述您的问题.*现在的开源版本远程登录linux主机的时候只能在其网页的框里进行操作，感觉效率不是最高，想知道能不能直接拉起ssh工具直接登录上远程的这台机器

**Comment by luweijun1992** [comment]
> **请描述您的问题.*现在的开源版本远程登录linux主机的时候只能在其网页的框里进行操作，感觉效率不是最高，想知道能不能直接拉起ssh工具直接登录上远程的这台机器

连接堡垒机IP:2222 端口；可以连接非图形界面的资产
