### ISSUE TITLE
使用类似xshell连接jumper server 希望加上分类功能[Feature] 

### ISSUE THREAD

**Issue by leearic18** [jumpserver/jumpserver#5628]
**请描述您的需求或者改进建议.**
我们目前使用的是开源版jumper server, 就个人而言, 我们觉得使用web 控制台不方便, 所以我们更愿意通过xshell连接的方式登陆jumper server进行主机管理.
但是我们目前遇到的主要问题是：
xshell 只是把主机罗列出来,  并没有对主机进行分类(其实我们有对主机进行分类), 或者能实现这个功能, 我们没有配置出来, 请告知一下如何配置.

我们希望能够更加细化, 这样使用就更加方便了

**Comment by luweijun1992** [comment]
可以通过输入 g 来展示分组

**Comment by leearic18** [comment]
收到. 感谢.
