### ISSUE TITLE
远程桌面服务器不在线。如果问题持续，请通知您的系统管理员，或检查您的系统日志

### ISSUE THREAD

**Issue by xiao567890** [jumpserver/jumpserver#5629]
**JumpServer 版本(v1.5.9以下不再支持)**

jumpserver v2.7.0

**浏览器版本**
chrome 88.0.4324.182

**描述**
连接windows(windows server2008 r2)资产报错，远程桌面服务器不在线。如果问题持续，请通知您的系统管理员，或检查您的系统日志，连接其它windows资产正常

** 重现步骤(有截图更好)**
1.  添加windows资产(windows server 2008 R2)
2. 使用rdp协议连接资产
![QQ截图20210222152007](https://user-images.githubusercontent.com/20200297/108676600-727c8380-7523-11eb-8750-8c3fdc46e11d.png)

3.

**Comment by paddy235** [comment]
win2016也是如此，不是所有都无法连接，部分win2016会这样，都是同样的虚拟机创建，事件查看器没有看到关键问题，包括审核失败。
win2008和win2016都是部分可以使用，目前我只有这两种操作系统。

**Comment by paddy235** [comment]
经过使用官方的guacadmin的测试，问题原因找到了，官方使用的认证选择有几种，jumpserver只使用了一种，失败的因为选择了错误的连接,我使用了nls认证解决的,有的是rdp加密。

可以使用这个项目进行测试，https://github.com/boschkundendienst/guacamole-docker-compose

**Comment by LeeEirc** [comment]
@paddy235 可以通过增加 平台 设置，修改 这个连接的安全模式。

**Comment by xiao567890** [comment]
升级到2.7.1解决问题
