### ISSUE TITLE
安装coco提示报错

### ISSUE THREAD

**Issue by 727023460** [jumpserver/jumpserver#563]
[root@redis coco]# python run_server.py 
Using access key 32d352e1-16f9-4e2f-9f22-013612d28382:***
No handlers could be found for logger "/var/www/coco/coco/service.pyc"
然后就卡住不动了

**Comment by ibuler** [comment]
需要去jumpserver后台接受注册

**Comment by 727023460** [comment]
注册了，没效果，没注册会提示要认证

**Comment by zhaojiang1980** [comment]
差不多，我去后台页面注册，点确认没反应，删除了，结束进程，重启coco，终端里不能识别了。

**Comment by ibuler** [comment]
jumpserver后台 - 应用程序 - 终端  接受
