### ISSUE TITLE
[Bug] v2.7.1 版本的切换用户无法远程

### ISSUE THREAD

**Issue by kafka2017** [jumpserver/jumpserver#5631]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  使用admin账号，配置资源正常，新建另一个用户，访问之后
![image](https://user-images.githubusercontent.com/29690239/108792911-51687100-75bd-11eb-8238-8feeedf4608f.png)

**Comment by wojiushixiaobai** [comment]
已知问题，下版本修复
