### ISSUE TITLE
连接资产 xxx 发生错误：认证失败（用户名或密码错误）

### ISSUE THREAD

**Issue by pptfz** [jumpserver/jumpserver#5632]
dcoker安装，版本2.7.1，连接资产报错 `认证失败（用户名或密码错误）`，用户已经创建，资产已经授权，请问该如何排查呢？

**Comment by wojiushixiaobai** [comment]
Web页面 - 资产管理 - 系统用户

点击系统用户的名称，在系统用户详情的右侧点击资产列表里面的对应资产，选择推送或者测试资产可怜性

此问题一般是系统用户账号密码错误不正确导致。

![QQ截图20210225110009](https://user-images.githubusercontent.com/24326988/109096700-fbc8cb80-7758-11eb-8736-fcd722d5b179.png)

**Comment by pptfz** [comment]
系统用户设置的自动生成密钥，没有设置密码，我现在遇到的问题是部分主机可以连接，部分主机就不可连接，请问这是为什么呢？
如果说我设置的有问题，那所有的机器应该都是不可以连接的，但是为什么会部分不成功，部分成功呢？

**Comment by howge** [comment]
遇到同样的问题，我迁移了整个数据库，但是登入选定资产时还是提示要我输入**系统用户**的密码

**Comment by howge** [comment]
> 

犯了个错误，迁移**要保证SECRET_KEY 跟之前的一致**,问题解决！

**Comment by andro-ajp** [comment]
> 系统用户设置的自动生成密钥，没有设置密码，我现在遇到的问题是部分主机可以连接，部分主机就不可连接，请问这是为什么呢？ 如果说我设置的有问题，那所有的机器应该都是不可以连接的，但是为什么会部分不成功，部分成功呢？

一码一样，请问你的解决了吗

**Comment by XingTom** [comment]
ssh web登录遇到同样问题，请问怎么解决的呢
