### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sunzqe** [jumpserver/jumpserver#5635]
**JumpServer 版本(v1.5.9以下不再支持)**

2.6.2
**浏览器版本**
chrome 版本 88.0.4324.146（正式版本） (x86_64)
**Bug 描述**
web终端ssh链接30s超时断开，ssh server设置ClientAliveInterval 600无效
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
检查中间层是否有其他限制，比如JumpServer的 连接最大空闲时间，nginx的相关设置等
