### ISSUE TITLE
[Bug] vi窗口就变小了。

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5638]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.3

**浏览器版本**
Chrome

**Bug 描述**
访问k8s集群，vi窗口就变小了，直接截断换行。如下所示。
![image](https://user-images.githubusercontent.com/10806595/108964104-01b9a080-76b6-11eb-9ded-1cbc86406286.png)
我试了下，登录linux服务器没有这个bug。如下所示。
![image](https://user-images.githubusercontent.com/10806595/108965513-ea7bb280-76b7-11eb-84e5-34808d75269f.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
尝试调整下窗口大小，或者升级到v2.7.1版本试试。

**Comment by bingws** [comment]
好的。
