### ISSUE TITLE
luna登录报错-登陆跳转问题

### ISSUE THREAD

**Issue by yokiy0828** [jumpserver/jumpserver#564]
连接跳转后报错
<img width="1415" alt="luna" src="https://user-images.githubusercontent.com/25323406/28490190-4bed17ce-6f06-11e7-9191-086c86a81c2c.png">

**Comment by zsjohny** [comment]
@yokiy0828  不能指定https

**Comment by yokiy0828** [comment]
我是http也报错。

**Comment by yokiy0828** [comment]
你nginx反代上的https？

**Comment by zsjohny** [comment]
嗯 对 @yokiy0828

**Comment by yokiy0828** [comment]
我之前也试过，好像不显示。白屏

**Comment by ibuler** [comment]
luna用了websocket，如果反向代理，请支持

**Comment by yokiy0828** [comment]
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}这样就支持了吗？

**Comment by yokiy0828** [comment]
亲测 有效。
![image](https://user-images.githubusercontent.com/25323406/28496655-7972519e-6fa3-11e7-9db2-32672367636e.png)

**Comment by yokiy0828** [comment]
我发现只有谷歌可以，其他浏览器不行。

**Comment by ibuler** [comment]
jumpserver项目没有对其他浏览器做过测试

**Comment by yokiy0828** [comment]
其他浏览器就转跳http://127.0.0.1:8080/users/login?next=http://xxx.com:443/

**Comment by yokiy0828** [comment]
换另一台机器的谷歌都不行，都是转跳127.0.0.1:8080

**Comment by ibuler** [comment]
需要再了解一下 jumpserver和luna的认证机制

luna的认证机制是依赖的cookie，而cookie是jumpserver登陆设置的，所以如果你正常登陆了jumpserver,登陆luna就不需要认证了。

那么如果你未曾登陆过jumpserver,这时你访问luna，就会跳转到jumpserver的登陆界面，输入账号密码，如果登陆成功，会将你再次redirect到luna的页面。

好的，如果了解了这些，就可以解释了，你换了另一台机器的chrome, 登陆不了是因为没有登陆jumpserver, 而关于跳转出错的问题是因为 你的luna用的默认的配置，这时你要修改一下 luna下的config.py, 将JUMPSERVER_ENDPOINT改成一个你浏览器可以访问的

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28506924-65d615b2-7061-11e7-80be-c46e11f02bde.png)
这样有问题吗@ ibuler

**Comment by ibuler** [comment]
JUMPSERVER_ENDPOINT改为 = 'http://jumpserver的内网IP:8080/'

**Comment by yokiy0828** [comment]
server
{
    listen 443 ;
    server_name xxx.com;
    ssl on;
    ssl_certificate   /usr/local/nginx/conf/ssl/luna.nfvpn.com.pem;
    ssl_certificate_key  /usr/local/nginx/conf/ssl/luna.nfvpn.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    keepalive_timeout 120;
    keepalive_requests 20000;
    access_log /data/log/nginx/xxx.com.log;
    location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Connection "";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:5000;
    error_log /data/log/nginx/error.log;
}
}
我是nginx反代  https，这样对吗？

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28507015-2b189d2c-7062-11e7-9682-6563d19ea3da.png)
she'zhi设置了内网iP

**Comment by ibuler** [comment]
你登陆jumpserver是什么地址？ 按道理来说 10.27.108.190:8080就是你的Jumpserver的ip

**Comment by yokiy0828** [comment]
我登录是用域名解析的外网IP。奇怪的是我本机可以正常访问luna，但是其他机器都不行。都登录过jumpserver了

**Comment by yokiy0828** [comment]
改成外网域名后
![image](https://user-images.githubusercontent.com/25323406/28507083-ae03f1e6-7062-11e7-9581-dcde1829389d.png)

**Comment by yokiy0828** [comment]
地址不是https 而是加了端口443

**Comment by ibuler** [comment]
嗯，这时又要了解一个问题，cookie的跨域问题，luna和jumpserver使用同一个域名是没问题的，但如果 jumpserver使用  jumpserver.abc.com  而 luna使用 luna.abc.com就有了跨域问题，cookie是不通用的。

这时你需要设置cookie域名  https://github.com/jumpserver/jumpserver/blob/dev/config_example.py#L80-L81

**Comment by yokiy0828** [comment]
原来可以正常访问的机器就成了
![image](https://user-images.githubusercontent.com/25323406/28507110-df1b4f0e-7062-11e7-84dc-075f039c184f.png)

**Comment by ibuler** [comment]
跳转到了 http加了 443这个应该是跳转bug

**Comment by yokiy0828** [comment]
server
{
    listen 443 ;
    server_name xxx.com;
    ssl on;
    ssl_certificate   /usr/local/nginx/conf/ssl/jump.nfvpn.com.pem;
    ssl_certificate_key  /usr/local/nginx/conf/ssl/jump.nfvpn.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    keepalive_timeout 120;
    keepalive_requests 20000;
    access_log /data/log/nginx/xxx.com.log;
    location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Connection "";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://127.0.0.1:5000;
    error_log /data/log/nginx/error.log;
}
}

设置成同一个域名报错：
![image](https://user-images.githubusercontent.com/25323406/28507236-cd1391d0-7063-11e7-943a-8018c760534c.png)

**Comment by yokiy0828** [comment]
我增加了cookie 域名，但是报错依旧
![image](https://user-images.githubusercontent.com/25323406/28507404-1cc48fe4-7065-11e7-9f39-6664c62638dd.png)

**Comment by ibuler** [comment]
RecursionError的意思是重定向太多，来回的重定向导致的，建议先用同一个域名，不同的端口测试

**Comment by yokiy0828** [comment]
我现在用同一个域名 ，但是我想把luna也用上https，5001端口重定向到5000，但是依旧报错

**Comment by ibuler** [comment]
用同一个域名应该就不是认证的问题了，可以先登陆jumpserver, 然后手动访问luna，这时有问题应该就是nginx的问题

**Comment by yokiy0828** [comment]
还是会报
![image](https://user-images.githubusercontent.com/25323406/28510268-f4c9ec68-7079-11e7-8106-46f26130f2d0.png)

**Comment by ibuler** [comment]
same #561

**Comment by ibuler** [comment]
新版本逻辑已改变，请测试
