### ISSUE TITLE
[Question] jumpserver接入了LDAP后，怎么屏蔽原密码登录

### ISSUE THREAD

**Issue by dmanbu** [jumpserver/jumpserver#5643]
Jumpserver接入LDAP后，由于原有用户名和LDAP的用户名相同，导致使用原密码和LDAP账号的密码都能登录同一个用户，怎么屏蔽原密码登录？

**Comment by ibuler** [comment]
下个版本会支持，只能从 用户的来源 登录

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/pull/5592
