### ISSUE TITLE
[Bug] django error : curl http://{docker网络->容器名称}/api/** 错误

### ISSUE THREAD

**Issue by mojocn** [jumpserver/jumpserver#5644]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

在其他容器 curl http://jms_nginx/api/users/users/
django 报错

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
curl http://jms_nginx/api/v1/users/users/
