### ISSUE TITLE
[Bug] 切换用户后rdp会话白屏

### ISSUE THREAD

**Issue by kele1997** [jumpserver/jumpserver#5645]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**浏览器版本**
chrome 87.0.4280.88

**Bug 描述**
使用一个用户登录后，通过 luna 打开 windows rdp 窗口。  然后退出登录(浏览器不关闭)，使用另一个账号登录，再次通过 luna 打开windows rdp 窗口，白屏

浏览器 console 显示  403 
`Failed to load resource: the server responded with a status of 403 ()   :8080/guacamole/api/tokens:1`    

查看  docker 容器  jumpserver/guacamole:v2.7.1  日志为 "用户与 sessionID" 不匹配

```
42bd-a5a1-24f32d21f7cf, assetId: b63a93f5-0e35-46e8-ad1e-b39a1ee582c4, systemUserId: 032f0035-4cf8-46fa-b55a-89bcb6a7ec70
26-Feb-2021 01:30:21.231 WARNING [http-nio-8080-exec-5] org.apache.http.client.protocol.ResponseProcessCookies.processCookies Invalid cookie header: "Set-Cookie: sessionid=iciqel9vrowhcls6xp21013mi71v37rn; expires=Sat, 27 Feb 2021 01:30:21 GMT; HttpOnly; Max-Age=86400; Path=/; SameSite=Lax". Invalid 'expires' attribute: Sat, 27 Feb 2021 01:30:21 GMT
2021-02-26 01:30:21.231 [http-nio-8080-exec-5] INFO  o.a.g.a.j.api.JumpserverService - getUser by cookie: cdbddc3f-366c-42bd-a5a1-24f32d21f7cf
2021-02-26 01:30:21.231 [http-nio-8080-exec-5] INFO  o.a.g.a.j.c.JumpserverConfigurationService - 用户与SessionID不匹配
2021-02-26 01:30:29.269 [http-nio-8080-exec-2] ERROR o.a.g.rest.RESTExceptionMapper - An internal error occurred, but did not contain an error message. Enable debug-level logging for details.
```

**Bug 重现步骤(有截图更好)**
1.  登录 user1 账号，打开web终端，打开一个 rdp 会话，此时 rdp 会话显示正常
2.  退出登录 user1, 登录 user2
3.  打开web终端，再次打开 一个 rdp 会话，白屏

**临时解决办法**
打开浏览器开发者面板中的 "Application" , 清除 "local storage" ,之后登录其他账号，rdp 会话正常显示  
更准确的说，是清除 "local storage" 中的 `GUAC_AUTH` 属性，因为其中的 username ,再重新登录后，没有更新

**Comment by ibuler** [comment]
@wojiushixiaobai 复现一下

**Comment by orangemio** [comment]
@kele1997  https://github.com/jumpserver/luna/pull/331/files 修复了

**Comment by jym503558564** [comment]
@kele1997 已修复，请持续关注我们下个版本发布。
