### ISSUE TITLE
[Bug] 2.7.1版本在web终端使用vim的块视图时，响应的是粘贴。

### ISSUE THREAD

**Issue by roger-gs** [jumpserver/jumpserver#5647]
**JumpServer 版本(v1.5.9以下不再支持)**
2.7.1

**浏览器版本**
edge 88

**Bug 描述**
在web终端中，使用vim编辑文本，在使用Ctrl+v进入块视图时，是windows操作系统粘贴的效果。

**Comment by afunGame** [comment]
两年了 大哥 给个解决方案呀
