### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 763216512** [jumpserver/jumpserver#5649]
jumpserver版本：Version v2.7.1 GPLv2.

**浏览器版本**
Google Chrome版本 88.0.4324.104 

**Bug 描述**
已知此主机开放3389端口，通过mstsc命令可以连入，jumpserver服务器与此主机之间网络可以连通。
使用rdp连接windows2012R2主机时显示
联系不上远程桌面服务器。如果问题持续，请通知您的系统管理员，或检查您的系统日志。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/35587826/109373971-f7cdb280-78ec-11eb-8710-aef51f4d5f3d.png)
2.
![47连接](https://user-images.githubusercontent.com/35587826/109373996-2ba8d800-78ed-11eb-8ce8-defafeec77fe.png)
3.
![image](https://user-images.githubusercontent.com/35587826/109374016-598e1c80-78ed-11eb-8d56-b331cd87c176.png)

**Comment by ibuler** [comment]
需要通过后台日志来确定

**Comment by 763216512** [comment]
感谢您的回复，请问如何获取系统后台日志？

**Comment by jym503558564** [comment]
@763216512 可查看gua的日志，docker logs -f jms_guacamole

**Comment by 763216512** [comment]
[docker.log](https://github.com/jumpserver/jumpserver/files/6080674/docker.log)
获取了RDP报错后的日志，麻烦看看什么问题，感谢！

**Comment by bobo19920612** [comment]
问题解决了吗

**Comment by bobo19920612** [comment]
大佬  遇到同样问题  教教怎么解决
