### ISSUE TITLE
COCO，资产组没用户

### ISSUE THREAD

**Issue by yokiy0828** [jumpserver/jumpserver#565]
选择资产组没用户，登录不了。
<img width="595" alt="coco" src="https://user-images.githubusercontent.com/25323406/28490347-5a91947c-6f0a-11e7-98a9-64523d0c5e93.png">

**Comment by ibuler** [comment]
普通用户里有是吧

**Comment by yokiy0828** [comment]
是的呢。

**Comment by ibuler** [comment]
已修复

**Comment by yokiy0828** [comment]
我怎么更新？git pull ?

**Comment by ibuler** [comment]
这个更新的是jumpserver的sdk

> pip install --upgrade jumpserver-python-sdk

**Comment by yokiy0828** [comment]
我安装这个就行了吗？

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28496754-cab582e0-6fa5-11e7-8f5b-e2318f8176d0.png)
但是没有更新。

**Comment by ibuler** [comment]
那就先卸载原来的

`pip uninstall jumpserver-python-sdk`

再安装
`pip install jumpserver-python-sdk`

确保安装的是 0.0.15版本

**Comment by yokiy0828** [comment]
重新安装是0.0.14  怎么安装0.0.15？

**Comment by ibuler** [comment]
我刚上传的，可能pypi索引时间比较慢

https://pypi.python.org/pypi/jumpserver-python-sdk/0.0.15

可以直接下载下来

> python setup.py install

**Comment by ibuler** [comment]
`pip install --upgrade jumpserver-python-sdk==0.0.15` 也是可以的

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28496800-eb56d14c-6fa6-11e7-9682-10214139b579.png)
可能还没同步吧

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28496812-15a50004-6fa7-11e7-8bc1-45afb40a2d1b.png)
xu需要接什么参数?

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/28496817-37059e7a-6fa7-11e7-9306-0cb7285ed1ed.png)

**Comment by yokiy0828** [comment]
我为什么一直这样？
![image](https://user-images.githubusercontent.com/25323406/28496821-5d0db3c8-6fa7-11e7-8f13-c79f6447193b.png)

**Comment by yokiy0828** [comment]
我是在py3虚拟环境里装的.
