### ISSUE TITLE
机器批量更新遇到的问题

### ISSUE THREAD

**Issue by pptfz** [jumpserver/jumpserver#5651]
现在有一个需求，批量修改机器的备注信息
我下载了官方的更新模版，在这个模版中有 `主机名`，`IP `，`系统平台`是带*号的，把这3个必须项填上了，然后把响应的备注信息填写好，更新的时候报错如图所示
![image](https://user-images.githubusercontent.com/44946546/109383040-e0a7b880-791e-11eb-9787-b993489b2fe6.png)

官方给的更新模版，我只填写了一个示例，一共有100多机器，这个哪里没有填写对呢？
![image](https://user-images.githubusercontent.com/44946546/109383064-01700e00-791f-11eb-85ef-614cb68858c8.png)
![image](https://user-images.githubusercontent.com/44946546/109383097-26fd1780-791f-11eb-986a-d269cb2efeee.png)

**Comment by ibuler** [comment]
需要填写更新哪个资产，也就是第一列 id

**Comment by jym503558564** [comment]
- 更新时ID，需要填写。如还有问题，可再次代开Issues.
![image](https://user-images.githubusercontent.com/40739051/109442032-faa5e000-7a71-11eb-8c79-792c67279b0e.png)

**Comment by pptfz** [comment]
明白了，多谢多谢
