### ISSUE TITLE
部署完成后，浏览器访问出现错误 

### ISSUE THREAD

**Issue by ajieup** [jumpserver/jumpserver#5656]
**请描述您的问题.**
浏览器登陆时报：Server error occur, contact administrator。请问如何解决？
官方的安装资料还是太少了，也不够详细。

**Comment by ajieup** [comment]
希望官方能出一些详细的安装文档。
我的环境如下：
centos 8.3
mysql 8.0.19
redis 5.0.5
jumpserver and 各组件为最新的v2.7.1

**Comment by luweijun1992** [comment]
./jmsctl.sh status 看看状态

**Comment by ajieup** [comment]
> ./jmsctl.sh状态看看状态

![image](https://user-images.githubusercontent.com/79831323/109468646-dbc24080-7aa7-11eb-8edd-dc21e8e205bb.png)

**Comment by luweijun1992** [comment]
> > ./jmsctl.sh状态看看状态
> 
> ![image](https://user-images.githubusercontent.com/79831323/109468646-dbc24080-7aa7-11eb-8edd-dc21e8e205bb.png)

难道不是这样的吗？
![image](https://user-images.githubusercontent.com/58923704/109468811-20e67280-7aa8-11eb-8fa9-540b472c597c.png)

**Comment by ajieup** [comment]
> > > ./jmsctl.sh状态看看状态
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/79831323/109468646-dbc24080-7aa7-11eb-8edd-dc21e8e205bb.png)
> 
> 难道不是这样的吗？
> ![image](https://user-images.githubusercontent.com/58923704/109468811-20e67280-7aa8-11eb-8fa9-540b472c597c.png)

我是离线部署的

**Comment by luweijun1992** [comment]
离线部署最终也能通过这个查询啊
docker ps -a 看看启动的容器。

**Comment by ajieup** [comment]
> 离线部署最终也能通过这个查询啊
> docker ps -a 看看启动的容器。

我没有部署docker，刚接触jumpserver。相关的资料很少

**Comment by ajieup** [comment]
希望有经验的同学能帮帮我

**Comment by wojiushixiaobai** [comment]
# [Core 常见问题](https://docs.jumpserver.org/zh/master/faq/core/)

- 2. Server error occur, contact administrator

!!! question "Server Internal Error"
    ```sh
    docker logs -f jms_core --tail 200
    # 查看是否有报错，如果没有或者不完整请进入容器查看日志
    ```
    ```sh
    docker exec -it jms_core /bin/bash
    cat logs/jumpserver.log
    # 根据报错处理
    ```

**Comment by ajieup** [comment]
> * [Server error occur, contact administrator](https://docs.jumpserver.org/zh/master/faq/core/)
>   ```shell
>   docker logs -f jms_core --tail 200
>   # 查看是否有报错，如果没有或者不完整请进入容器查看日志
>   ```
>   
>   
>   ```shell
>   docker exec -it jms_core /bin/bash
>   cat logs/jumpserver.log
>   # 根据报错处理
>   ```

我没有部署docker环境

**Comment by wojiushixiaobai** [comment]
cd /opt/jumpserver
cat logs/jumpserver.log
# 根据报错处理

**Comment by ajieup** [comment]
> ```
> cd /opt/jumpserver
> cat logs/jumpserver.log
> # 根据报错处理
> ```

![image](https://user-images.githubusercontent.com/79831323/109609392-3ae68a80-7b66-11eb-9d72-ad30b9229c12.png)
请问该怎么处理呢

**Comment by wojiushixiaobai** [comment]
找到第一个报错，并且完整的错误发出来。

**Comment by ajieup** [comment]
> 找到第一个报错，并且完整的错误发出来。

只有这个错误信息
![image](https://user-images.githubusercontent.com/79831323/109642292-bf003880-7b8d-11eb-9975-21e1f1593ec0.png)

**Comment by wojiushixiaobai** [comment]
@ajieup 执行下面的命令
```sh
cd /opt/jumpserver
. /opt/py3/bin/activate
./jmsctl.sh stop
ps aux | grep py3 | awk '{print $2}' | xargs kill -9
```
```sh
deactivate
rm -rf /opt/py3
```
```sh
python3.6 -m venv /opt/py3
source /opt/py3/bin/activate
pip install -r requirements/requirements.txt
```

**Comment by ajieup** [comment]
> @ajieup 执行下面的命令
> 
> ```shell
> cd /opt/jumpserver
> . /opt/py3/bin/activate
> ./jms stop
> ps aux | grep py3 | awk '{print $2}' | xargs kill -9
> ```
> 
> ```shell
> deactivate
> rm -rf /opt/py3
> ```
> 
> ```shell
> python3.6 -m venv /opt/py3
> source /opt/py3/bin/activate
> pip install -r requirements/requirements.txt
> ```
> 
> ```shell
> ./jms start -d
> ```
> 
> 不要有任何多余操作

![image](https://user-images.githubusercontent.com/79831323/110932071-f62cd180-8365-11eb-977a-4440c5c53b3f.png)
![image](https://user-images.githubusercontent.com/79831323/110932185-178dbd80-8366-11eb-8a2b-afa883560e58.png)
从mysql换到了mariadb 起不来了，这两个错误是什么情况

**Comment by ajieup** [comment]
> @ajieup 执行下面的命令
> 
> ```shell
> cd /opt/jumpserver
> . /opt/py3/bin/activate
> ./jms stop
> ps aux | grep py3 | awk '{print $2}' | xargs kill -9
> ```
> 
> ```shell
> deactivate
> rm -rf /opt/py3
> ```
> 
> ```shell
> python3.6 -m venv /opt/py3
> source /opt/py3/bin/activate
> pip install -r requirements/requirements.txt
> ```
> 
> ```shell
> ./jms start -d
> ```
> 
> 不要有任何多余操作

我按你的提示操作重新装了依赖，过程没有错误。但在启动时报错了：
![image](https://user-images.githubusercontent.com/79831323/111132419-4ac58c00-85b4-11eb-88f7-028b6a99a19b.png)
