### ISSUE TITLE
没有该用户，或许你是以root运行的 No that user

### ISSUE THREAD

**Issue by czxin788** [jumpserver/jumpserver#566]
安装jumserver之后，为啥我再切换到普通用户后就报如下错误呢：
[root@m-ubonex-elk ~]# su - elk
上一次登录：日 7月 23 16:54:15 CST 2017pts/0 上
没有该用户，或许你是以root运行的 No that user.

**Comment by xuops20177** [comment]
同样的问题，还未解决，求教

**Comment by xuops20177** [comment]
安装目录jumpserver/connect.py修改下，注释掉
 #if not login_user:  # 判断用户是否存在
 #color_print('没有该用户，或许你是以root运行的 No that user.', exits=True)
然后再次尝试

**Comment by qils** [comment]
堡垒机服务器上面没有创建 elk 这个授权用户, 判断条件是: User.objects.get(username='elk'), 也就是在juser.models User模型中没有创建一个elk的授权用户

**Comment by ibuler** [comment]
请修改 ？/etc/passwd 查看该用户的 shell设置，应改为 /bin/bash

**Comment by cloud1213** [comment]
@ibuler  不是这个问题， @xuops20177 说的方法有用，之后切换到普通用户会直接进入jumpserver命令行终端
