### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by manfoon** [jumpserver/jumpserver#5661]
**JumpServer 版本(v1.5.9以下不再支持)**
2.71版

**浏览器版本**

**Bug 描述**
审计人员不能添加分组，其他两个权限可以分组。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
新版本已放开审计员能够添加到用户组，请持续关注我们后续版本发布。
