### ISSUE TITLE
[Bug] webterminal 快速打开多个终端，页面崩溃，out of memory

### ISSUE THREAD

**Issue by tonyaszhu** [jumpserver/jumpserver#5662]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**浏览器版本**
Google chrome v-88.0.4324.182

**Bug 描述**
在终端里同时快速打开超过3个终端，页面会崩溃，浏览器提示out of memory

重点：
1、快速指1秒内点击连接3个或以上的终端
2、打开才会出现这个问题，打开第一个等2秒后再打开第二个就正常
3、快速打开3个以上都会有这个问题，每次都能复现，打开2个以下正常

**Bug 重现步骤(有截图更好)**
1.  
![1](https://user-images.githubusercontent.com/33281209/109488813-0371d280-7ac1-11eb-9a0f-d887a0870227.png)

**Comment by tonyaszhu** [comment]
虚拟机部署，8c 16g 配置，提示out of memory时查看机器资源正常

**Comment by wojiushixiaobai** [comment]
没有复现，是否是本地的客户端有问题，更换浏览器或者换一台电脑看看

**Comment by jym503558564** [comment]
@tonyaszhu 谢谢反馈，我们将后续修复。请持续关注我们版本发布情况。
