### ISSUE TITLE
[Bug] 管理后台：系统用户菜单-> 用户资产选项下，点击推送按钮，经常出现...

### ISSUE THREAD

**Issue by kxs2008** [jumpserver/jumpserver#5671]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1社区版

**浏览器版本**
Google Chrome 
版本 88.0.4324.192（正式版本） (x86_64)

**Bug 描述**
系统用户菜单-> 用户资产选项下，点击推送按钮，经常出现............（但实际已经推送成功了），需要刷新很多次以后（等待1分钟左右），再点推送才能显示成功。页面地址为：http://xxx/ui/#/ops/celery/task/948448ec-2fd7-47c3-82a8-5def445c5843/log, 感觉是celery 资源不够或是浏览器缓存问题（猜测），请确认

**Comment by wojiushixiaobai** [comment]
ws 问题，多组件请保证 task 节点唯一

**Comment by ibuler** [comment]
多节点，多组件，需要共享 data 目录

**Comment by ibuler** [comment]
新版本 v2.8 也在这方面做了优化，可以试试

**Comment by jym503558564** [comment]
目前新版本该问题未复现，可更新至新版进行测试，如还有其他问题可再次打开Issues
