### ISSUE TITLE
[Question]jumpserver rz上传速度 快速下降

### ISSUE THREAD

**Issue by UINWZ** [jumpserver/jumpserver#5672]
**请描述您的问题.**
使用jumpserver版本：v2.7.0
连接方式：ssh
出现问题：使用rz命令在SCRT中上传文件出现掉速情况。
![image](https://user-images.githubusercontent.com/19307326/109769360-0e4d7400-7c35-11eb-805d-5c0d07decb57.png)

**Comment by LeeEirc** [comment]
因获悉原因，将在后续版本优化。

**Comment by UINWZ** [comment]
请问这个是什么原因造成的，原因可以分享一下吗？看是不是可以做一些修改

**Comment by jym503558564** [comment]
https://github.com/jumpserver/jumpserver/issues/5672   已专门修复，请更新至对应版本
