### ISSUE TITLE
Jumpserver1.5.3-2 GPLv2升级到v2.7.1 GPLv2失败

### ISSUE THREAD

**Issue by CWeThough** [jumpserver/jumpserver#5676]
伟大的开发团队和大佬们 你们好，我使用的jumpserver版本是1.5.3-2，由于前段时间API漏洞的隐患，我希望将jumpserver升级到最新的v2.7.1版本。
----------------------------------------------------------------------------------------------------------------------------------------------
遇到的问题：
登录jumpserver时，输入（1.5.3-2版本时使用的）用户名和密码后，进行MFA认证，认证完成后弹出错误页面，显示“Server error occur, contact administrator”。随后根据官方文档“https://docs.jumpserver.org/zh/master/faq/core/#2-server-error-occur-contact-administrator”连接到jms_core容器进行排查，错误日志请查看附件jumpserver.log!
----------------------------------------------------------------------------------------------------------------------------------------------
升级流程：
1.在一台新的服务器上，根据部署文档来部署jumpserver，执行了以下命令：
export DOCKER_IMAGE_PREFIX=swr.cn-north-1.myhuaweicloud.com
cd /opt
yum -y install wget
wget https://github.com/jumpserver/installer/releases/download/v2.7.1/jumpserver-installer-v2.7.1.tar.gz
tar -xf jumpserver-installer-v2.7.1.tar.gz
cd jumpserver-installer-v2.7.1
vi config-example.txt     -----------------（将1.5.3-2版本时使用的SECRET_KEY和BOOTSTRAP_TOKEN的值写入到文件中）
./jmsctl.sh install

./jmsctl.sh start
当jms_redis、jms_mysql的进度变为done后，按下Ctrl+C中断启动，此时使用docker ps -a命令查看容器状态，发现mysql和redis容器的状态都是健康。

随后我使用mysqldump将装有jumpserver1.5.3-2服务器的机器上Mysql的jumpserver表备份出来，传到新服务器中，运行以下命令：

if grep -q 'COLLATE=utf8_bin' /opt/jumpserver.sql; then
    echo "备份数据库字符集正确";
else
    cp /opt/jumpserver.sql /opt/jumpserver_bak.sql
    sed -i 's@CHARSET=utf8;@CHARSET=utf8 COLLATE=utf8_bin;@g' /opt/jumpserver.sql
fi

结果显示 “备份数据库字符集正确”

再将文件传到jms_mysql容器中，连接到数据库，执行以下命令：
drop database jumpserver;
create database jumpserver default charset 'utf8' collate 'utf8_bin';
source /opt/jumpserver.sql;

随后退出容器，重启jms_mysql容器，然后再次执行Jumpserver启动命令：
./jmsctl.sh start
待所有组件状态变为done后，使用docker ps -a命令查看所有容器的状态，全部为“健康”

然后使用浏览器测试访问时，就GG了.........

----------------------------------------------------------------------------------------------------------------------------------------------

根据容器内jumpserver日志，可以看到“django.db.utils.OperationalError: (1054, "Unknown column 'backend' in 'field list'")”，有哪位大佬帮忙看一下，我该如何进行修复，谢谢！

**给各位老板拜个晚年！**

**Comment by CWeThough** [comment]
[Uploading jumpserver.log…]()

**Comment by CWeThough** [comment]
[jumpserver.log](https://github.com/jumpserver/jumpserver/files/6075256/jumpserver.log)
jumpserver日志

**Comment by ibuler** [comment]
应该表结构变更有些有问题

**Comment by swq-github** [comment]
> 应该表结构变更有些有问题

表结构在哪个版本有更新呀
求升级步骤
