### ISSUE TITLE
[Feature] 优化RDP远程桌面抗锯齿效果

### ISSUE THREAD

**Issue by wandga** [jumpserver/jumpserver#5677]
发现windows远程桌面锯齿严重，这个能怎么优化一下

**Comment by jym503558564** [comment]
@wandga 截个图看看

**Comment by wandga** [comment]
![2d0090438d64d491b3aa3570fb12ac2](https://user-images.githubusercontent.com/55781685/109907145-b66a4800-7cdc-11eb-9cc1-740d29ae8829.png)
![6db461b24223a709095470ab3520b20](https://user-images.githubusercontent.com/55781685/109907160-bb2efc00-7cdc-11eb-9ee5-12618477bb63.png)
都是相同分辨率下面的对比  文字还好，但是字母就特别明显  敲代码不太友好

**Comment by ibuler** [comment]
原生 Guacamole 试试，是不是有参数可以控制

```
$ docker run -d -p 8083:8080 -v /tmp/config:/config oznu/guacamole

账号密码: guacadmin/guacadmin
```

**Comment by huyifanstar** [comment]
> 原生 Guacamole 试试，是不是有参数可以控制
> 
> ```
> $ docker run -d -p 8083:8080 -v /tmp/config:/config oznu/guacamole
> 
> 账号密码: guacadmin/guacadmin
> ```

这个镜像run起来无法访问？
![image](https://user-images.githubusercontent.com/15685376/132845113-968207ae-59b7-43d9-9643-4a582da62daf.png)

![image](https://user-images.githubusercontent.com/15685376/132845083-b16a7e0d-585a-4af9-ad97-1dbbc437f07c.png)
