### ISSUE TITLE
[Question] 系统用户选择页面排序是乱的

### ISSUE THREAD

**Issue by dukong** [jumpserver/jumpserver#5678]
1.5版本的时候是按首字母排序的，2.6版本后就乱了，不知道有什么办法可以排序一下。
![jmp账号乱序](https://user-images.githubusercontent.com/11550593/109897675-05f54780-7cce-11eb-84c9-7d5869b75004.png)

**Comment by ibuler** [comment]
收到

**Comment by xuxinwen** [comment]
现在是按 优先级排序的

**Comment by dukong** [comment]
> 
> 
> 现在是按 优先级排序的

什么优先级？

**Comment by jym503558564** [comment]
@dukong 创建系统用户时，有个优先级。

**Comment by dukong** [comment]
> 
> 
> @dukong 创建系统用户时，有个优先级。

是否可以在优先级相同的时候，按照首字母排序？
