### ISSUE TITLE
jumpserver v0.3.x 打开web terminal无法连接 Connection Reset by peers

### ISSUE THREAD

**Issue by yangzi123456** [jumpserver/jumpserver#568]
各位好，本人前几天尝试使用jumpserver，安装v0.3.1完毕后在web一直登录不上，
提示Connection Reset ByPeer
FAQ上面的情况都排查了，确认没有FAQ上面说的问题。

以下是DEBUG日志：
2017-07-24 12:24:17,933 - run_server.py - DEBUG - Websocket: session_key: 7k6yyk0ijn7mycbjl7wud086lh0pdvnu
2017-07-24 12:24:17,936 - run_server.py - DEBUG - Websocket: session: Session object
2017-07-24 12:24:17,938 - run_server.py - DEBUG - Websocket: user [ admin ] request websocket
2017-07-24 12:24:17,939 - run_server.py - DEBUG - Websocket: Open request
2017-07-24 12:24:17,962 - run_server.py - DEBUG - set([<PermRole: minion>, <PermRole: test>])
2017-07-24 12:24:17,962 - run_server.py - DEBUG - 系统用户: test
2017-07-24 12:24:17,962 - run_server.py - DEBUG - Websocket: request web terminal Host: master-devtest User: admin Role: test
2017-07-24 12:24:17,964 - connect.py - DEBUG - {'ip': u'10.0.61.150', 'role_name': u'test', 'role_key': u'/opt/jumpserver/keys/user/admin_test.pem', 'user': <User: admin>, 'role_pass': 'xFyxvxvbQyotjocmbvOA', 'port': 22, 'asset': <Asset: 10.0.61.150>}
2017-07-24 12:24:18,123 - run_server.py - DEBUG - Websocket: Close request

打开web terminal 就会报错
![image](https://user-images.githubusercontent.com/24835333/28508400-2518f33a-706d-11e7-9edb-d12f889aee0c.png)

但是exec端却可以正常执行命令！有些不解
![image](https://user-images.githubusercontent.com/24835333/28508434-676d0e42-706d-11e7-955d-e168c6356869.png)

我还尝试的配置了一下nginx1.10版本，按照git上提供配置文件进行修改，但是还是会出现上述问题。
没有发现是哪里有问题。

请问是哪里出了问题，或者有没有其他的排查方法？

**Comment by ibuler** [comment]
不使用nginx呢？

**Comment by yangzi123456** [comment]
@ibuler 没有使用nginx，直接访问的。谢谢了

**Comment by nice-jj** [comment]
@yangzi123456 我也是这个问题，请问您解决了吗？

**Comment by yangzi123456** [comment]
还没有解决，目前基本全都用命令行操作，就先凑乎用了！ @nice-jj

**Comment by nice-jj** [comment]
@yangzi123456 兄弟，我搞定了，需要改一段JS代码，路径：/jumpserver-0.3.2/static/js/webterminal.js，里面有一段是这样的：
function openTerminal(options) {
    var client = new WSSHClient();
    var rowHeight, colWidth;
    try {
        rowHeight = localStorage.getItem('term-row');
        colWidth = localStorage.getItem('term-col');
    } catch (err) {
        rowHeight = 24;
        colWidth = 80
    }
改为：
function openTerminal(options) {
    var client = new WSSHClient();
    var rowHeight, colWidth;
    try {
        rowHeight = localStorage.getItem('term-row');
        colWidth = localStorage.getItem('term-col');
    } catch (err) {
        rowHeight = 35;
        colWidth = 100
    }
    if (rowHeight) {
    } else {
        rowHeight = 35
    }
    if (colWidth) {
    } else {
        colWidth = 100
    }
除了这一段，还有一处需要改，在这个js文件的最后面有一段是这样的：
    $('#col-row').click(function () {
        var col = $('#term-col').val();
        var row = $('#term-row').val();
        localStorage.setItem('term-col', col);
        localStorage.setItem('term-row', row);
        term_client.term.resize(col, row);
        term_client.client.send({'resize': {'rows': row, 'cols': col}});
        $('#ssh').show();
    })
新增：
    $('#col-row').click(function () {
        var col = $('#term-col').val();
        var row = $('#term-row').val();
        localStorage.setItem('term-col', col);
        localStorage.setItem('term-row', row);
        term_client.term.resize(col, row);
        term_client.client.send({'resize': {'rows': row, 'cols': col}});
        $('#ssh').show();
    })
    $(".terminal").mouseleave(function () {
        $(".termChangBar").slideDown();
    });
    $(".terminal").mouseenter(function () {
        $(".termChangBar").slideUp();
    })
});

重启/jumpserver-0.3.2/service.sh restart  搞定！

**Comment by ooppwwqq0** [comment]
### 总结一下关于Connection Reset By Peer的问题出现原因以及解决办法

### 出现报错会有两种情况

* Connection Reset By Peer
* Connecting...Connection Reset By Peer

### Connection Reset By Peer 出现原因及解决办法

* 使用的是0.3.2版本的代码（本身代码有bug）；
* 并且直接访问的jumpserver端口，没有nginx代理；
* 解决办法-->将代码升级到master分支即可。

### Connecting...Connection Reset By Peer 出现原因及解决办法

* 使用nginx代理了jumpserver并且使用的是http代理；
* 代码版本无论是0.3.2还是master都会出现此问题；
* 解决办法-->http代理修改成tcp代理；
* nginx 1.9.x版本以上，编译时使用--with-stream参数可以支持tcp代理；
* 缺点是使用tcp代理之后无法配置server_name；
* 以下内容加到http{}外。

``` bash
stream {
    upstream backend{
        hash $remote_addr consistent;
        server 127.0.0.1:8000 weight=10;
    }

    server{
        listen 80;
        proxy_connect_timeout 20s;
        proxy_timeout 5m;
        proxy_pass backend;
    }
}
```

### 是否有其他情况造成此类问题没有测试过

**Comment by yangzi123456** [comment]
@nice-jj 我用的是0.3.1的版本，按你说的，还是没有成功！好的，谢谢各位前辈了，我等不忙的时候换到0.3.2版本试试

**Comment by ooppwwqq0** [comment]
@yangzi123456 不要换到0.3.2版本，0.3.2版本也是存在这个bug的，@nice-jj的方式是在0.3.2的基础上修改，如果想解决这个问题，直接升级到master版本即可

**Comment by chenglu01** [comment]
问题：  Connecting...Connection Reset By Peer 

解决办法：
websocket代理
 upstream jumpserver{
   server 127.0.0.1:8000;
   check interval=3000 rise=2 fall=5 timeout=1000;
   }
server {
        listen       80;
        server_name  jumpadmin.qq.com;
        location / {
            proxy_pass  http://jumpserver;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
       }
}

**Comment by ibuler** [comment]
大家记得查看jumpserver日志，确认一下是不是账号密码不对导致的
