### ISSUE TITLE
[Question] 开启标准的OPENID协议后，通过OPENID服务器进入平台的账号强制开启MFA不生效

### ISSUE THREAD

**Issue by yc-01** [jumpserver/jumpserver#5682]
**请描述您的问题.**
后台开启标准的openid协议后，强制开启的mfa对账号不生效，通过点击openid进入的账号可以直接跳过mfa认证。
配置如下：
![image](https://user-images.githubusercontent.com/75774974/109902648-b31f8e00-7cd5-11eb-8592-2c23ee9a9b56.png)
![image](https://user-images.githubusercontent.com/75774974/109902853-f4b03900-7cd5-11eb-9ade-f4c2420f62d1.png)

**Comment by ibuler** [comment]
设计上就是这样的，openid 和 cas 属于 统一认证，认证由 第三方来完成，是否验证 MFA，由 openid 来控制

**Comment by ibuler** [comment]
mfa的作用是防止密码泄露带来的安全问题，既然没在  JumpServer 平台输入密码，那就不存在这个问题
