### ISSUE TITLE
jumpserver 管理windows机器，显示未知

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#5684]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1
**浏览器版本**
google 88.0.4324.190

**Bug 描述**
jumpserver 在添加windows机器后，显示未知，已确认用户名密码是正确的，也可以telnet通windows机器的3389端口。
配置系统账户后也可以管理管理windows机器，就是资产展示的时候，一直显示未知，也获取不到服务器配置信息，linux的现在都正常
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/29726716/109906766-0e547f00-7cdc-11eb-829b-c22b764da72b.png)

![image](https://user-images.githubusercontent.com/29726716/109906307-38597180-7cdb-11eb-925e-b941c35be9e6.png)

**Comment by wandga** [comment]
获取配置信息是通过ssh协议 你要在Windows安装ssh才可以 官方文档里面的资产要求有写的

**Comment by jym503558564** [comment]
@QinQiang666 windows需要安装ssh，并在资产上配置上ssh端口，才可获取服务器配置信息
