### ISSUE TITLE
[Question]ssh 超时时间设置

### ISSUE THREAD

**Issue by sadbosan** [jumpserver/jumpserver#5685]
使用CRT ssh 到jumpserver ，再选择资产连接
设置了空闲时间120分钟，故120分钟 资产连接自动退出，但jumpserver 没有超时，如何设置能让长时间未连接资产自动退出

![image](https://user-images.githubusercontent.com/25677157/109916446-98a5de80-7cee-11eb-96cf-d03e6bffde6b.png)

**Comment by sadbosan** [comment]
版本1.5.8

**Comment by ibuler** [comment]
目前还没有这个，我们排期一下
