### ISSUE TITLE
ldap删除账号可以同步删除jumpserver的账号吗

### ISSUE THREAD

**Issue by liuyanmei069** [jumpserver/jumpserver#5686]
ldap那边删除账号后可以同步删除jumpserver的ldap账号吗？可以怎么实现呢？

**Comment by liuyanmei069** [comment]
ldap那边删除账号后可以同步删除jumpserver的ldap账号吗？

**Comment by jym503558564** [comment]
目前没有

**Comment by jym503558564** [comment]
重复问题 https://github.com/jumpserver/jumpserver/issues/5689
