### ISSUE TITLE
能否添加mysql的ssh隧道连接

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#5694]
希望添加通过“网域”功能提供ssh隧道，和mysql相连。我目前是通过VPN打通内网实现连接数据库，如果可以提供ssh隧道就好了。我在看源码，希望得到一些技术支持添加这个功能

**Comment by ibuler** [comment]
新版本已支持

**Comment by seaurching** [comment]
> 新版本已支持

版本是多少呀

**Comment by ibuler** [comment]
2.5 以后支持的
