### ISSUE TITLE
[Feature] 关于LDAP，用户的几个需求总结。

### ISSUE THREAD

**Issue by jym503558564** [jumpserver/jumpserver#5710]
**请描述您的需求或者改进建议.**

- [ ] LDAP用户删除之后，能够同步清理jumpserver的用户列表 。https://github.com/jumpserver/jumpserver/issues/5689
- [ ] 希望增加LDAP用户组同步 https://github.com/jumpserver/jumpserver/issues/5709  https://github.com/jumpserver/jumpserver/issues/3958
- [ ] 希望LDAP用户能够用证书登录 https://github.com/jumpserver/jumpserver/issues/4232

**Comment by wojiushixiaobai** [comment]
- [ ] LDAP 开启 SSL 认证的证书建议可以在 WEB 上传

**Comment by fanthos** [comment]
有把ssh key保存在ldap的方案
https://github.com/jirutka/ssh-ldap-pubkey

**Comment by rty813** [comment]
@wojiushixiaobai  @jym503558564   请问这个现在仍未实现么，有没有计划？
