### ISSUE TITLE
部分思科交换机的telnet登录问题

### ISSUE THREAD

**Issue by kongcz** [jumpserver/jumpserver#5712]
请问：
部分思科交换机telnet登录涉及到两个密码，命令执行如下
User Access Verification

Password: 
ac>en
Password: 
ac#

需要输入两个密码，中间还要输入enable。这种应该如何填写？

**Comment by LeeEirc** [comment]
不支持这种方式。操作有点像 Linux 系统普通用户切换 root 用户。
