### ISSUE TITLE
koko db 终端 长命令回删跳转编辑显示混乱[Bug] 

### ISSUE THREAD

**Issue by WilliamGuozi** [jumpserver/jumpserver#5714]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**Bug 描述**
长命令回删跳转编辑显示混乱

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/30142292/110613680-820af600-81cc-11eb-85aa-b1d5a2a641df.png)

2. 
3.

**Comment by jym503558564** [comment]
已知问题
