### ISSUE TITLE
[Bug] 权限到期失效，会话不能自动强制退出

### ISSUE THREAD

**Issue by lawrence191** [jumpserver/jumpserver#5716]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.7.1
**浏览器版本**
Chrome 89.0.4389.82 64位

**Bug 描述**
原先在版本2.5.4时，就有关注到这一bug的存在（https://github.com/jumpserver/jumpserver/issues/4845），在2.5.4时，从会话管理中，当权限到期后，则会被从在线会话删除，放到历史会话，但是客户端并未断开。历史会话也无法查看录像，应该是录像还在进行。现在升级到2.7.1版本后，发生变化，权限到期后，从权限管理可以看到打上交叉了，但是客户端并未强行断开。且在会话管理中的在线会话仍存在。该账户也无该主机的相关权限，但是终端会话还是可以访问操作等。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by lawrence191** [comment]
最新测试，如果使用管理员账户强行中断会话。是可以正常中断掉当前会话。中断之后会弹出一个可点击的重新连接的弹窗，不管闭浏览器页面的情况下，再点击那个重新连接按钮，则就算该用户已经没有该主机的访问权限了，但是仍可以重新连接，且可以在会话管理的在线会话中见到该会话处于在线状态。再次操作中断，重复点击重新连接，仍可以访问。只要浏览器不关闭，网络不断开，则可以一直重新连接访问。

**Comment by lawrence191** [comment]
再测试，再发现一个bug。通常使用web终端，会新开一个页面进行操作。现在发现这样一个情况，权限到期，原登录页面已经退出。但是web终端页面，只要未关闭，仍旧可以进行操作。

**Comment by LeeEirc** [comment]
通过web终端登录上资产，只要连接不断就可一直操作。如果你取消了该用户的授权，就算重连应该也无法连接，除非你还有授权规则。可以检查授权规则里面是否有节点、用户组等。

**Comment by lawrence191** [comment]
> 通过web终端登录上资产，只要连接不断就可一直操作。如果你取消了该用户的授权，就算重连应该也无法连接，除非你还有授权规则。可以检查授权规则里面是否有节点、用户组等。

确认了，没有其他权限规则的。在测试的时候，有多次的尝试，在关闭浏览器后，再重新登录账户，该账户确实已经不可见已经取消授权的资产了。
再重复一下测试步骤：
1.开启测试账户，并授权该账户以RDP协议方式远程登录Windows server。授权时间设定为5分钟。
2.登录测试账户，打开web终端，远程Windows server。不断操作远程桌面。
3.5分钟过后，管理员查看权限管理，该权限已经被打上红×。
4.管理员到会话管理，手动强制中断测试账户的远程会话。过几秒后，测试账户的远程桌面，弹出“重新连接”窗口。如果此时，新开浏览器页面，登录测试账户，该账户是查看不到Windows server。但是，测试账户点击重新连接，又是可以重新连接到远程桌面的。且再刷新管理员的会话管理页面，又重新可见测试账户的远程会话。
5.如果重复操作4。理论上，只要网络不断，页面不关。测试账户是可以持续的点击重新连接，持续操作远程桌面。（为此我们，写了脚本，检查过期权限，则强制下线，尽管可以点击重新连接，重新远程）

**Comment by LeeEirc** [comment]
> > 通过web终端登录上资产，只要连接不断就可一直操作。如果你取消了该用户的授权，就算重连应该也无法连接，除非你还有授权规则。可以检查授权规则里面是否有节点、用户组等。
> 
> 确认了，没有其他权限规则的。在测试的时候，有多次的尝试，在关闭浏览器后，再重新登录账户，该账户确实已经不可见已经取消授权的资产了。
> 再重复一下测试步骤：
> 1.开启测试账户，并授权该账户以RDP协议方式远程登录Windows server。授权时间设定为5分钟。
> 2.登录测试账户，打开web终端，远程Windows server。不断操作远程桌面。
> 3.5分钟过后，管理员查看权限管理，该权限已经被打上红×。
> 4.管理员到会话管理，手动强制中断测试账户的远程会话。过几秒后，测试账户的远程桌面，弹出“重新连接”窗口。如果此时，新开浏览器页面，登录测试账户，该账户是查看不到Windows server。但是，测试账户点击重新连接，又是可以重新连接到远程桌面的。且再刷新管理员的会话管理页面，又重新可见测试账户的远程会话。
> 5.如果重复操作4。理论上，只要网络不断，页面不关。测试账户是可以持续的点击重新连接，持续操作远程桌面。（为此我们，写了脚本，检查过期权限，则强制下线，尽管可以点击重新连接，重新远程）

如果你指的是RDP协议的Windows机器，这算已知问题，后续会优化guacamole的组件。
