### ISSUE TITLE
[Feature] 能否添加socks5代理代替SSH网关的功能

### ISSUE THREAD

**Issue by pc10201** [jumpserver/jumpserver#5721]
能否添加socks5代理代替SSH网关的功能？

socks5代理可以做到自动挑选速度最快的节点

但SSH网关做不到

**Comment by ibuler** [comment]
不太清楚 socks5 怎么使用，ssh 的隧道用的比较多些

**Comment by pc10201** [comment]
> 不太清楚 socks5 怎么使用，ssh 的隧道用的比较多些

有一些socks5软件可以自动选择最快的上游节点，SSH无法实现

**Comment by Srar** [comment]
同样需求

场景: 直接连接境外服务器速度比较慢，通过某些Socks5代理可以缓解这个现象。

**Comment by louishot** [comment]
也有这个需求，不行就只能自己用iptables把流量导到socks5上
