### ISSUE TITLE
jumpserver2.7.1版本 发出密码即将过期邮件后，完成修改密码操作，密码过期邮件依然发送

### ISSUE THREAD

**Issue by yc-01** [jumpserver/jumpserver#5724]
jumpserver2.7.1版本，数据是从原来的1.5.0版本迁移过来的，迁移到新版本2.7.1后，一直在发送密码过期的邮件，更改后邮件依然发送。
![image](https://user-images.githubusercontent.com/75774974/110767399-2fdfd880-8291-11eb-9a79-3fb6c93f4dc2.png)

**Comment by ibuler** [comment]
应该是 异步任务 问题，之前过期了，可能没有成功发送，现在还有问题吗？
