### ISSUE TITLE
修改系统用户的sudo，必须重新上传秘钥，有点不合理

### ISSUE THREAD

**Issue by yokiy0828** [jumpserver/jumpserver#573]
我只需要修改sudo的权限，但是更新的时候必须上传秘钥，修改秘钥，我并不想改秘钥。
![image](https://user-images.githubusercontent.com/25323406/28525791-00f3c034-70b8-11e7-9ce4-d4b83cef8857.png)

**Comment by yokiy0828** [comment]
并且这些按钮都没用
![image](https://user-images.githubusercontent.com/25323406/28525860-36ec8af4-70b8-11e7-946b-feb45fd925b8.png)

**Comment by ibuler** [comment]
一个前端的bug，里面的按钮还没做

**Comment by yokiy0828** [comment]
能不能修改sudo 不修改秘钥呢？

**Comment by yokiy0828** [comment]
而且修改秘钥，不会删除之前的key。

**Comment by ibuler** [comment]
可以手动把html里面的required去掉

**Comment by yokiy0828** [comment]
请问路径是哪个？

**Comment by ibuler** [comment]
已经fix，git pull

**Comment by yokiy0828** [comment]
ok,3Q

**Comment by yokiy0828** [comment]
需要重启服务吗？我没重启服务，还是需要上传秘钥。

**Comment by yokiy0828** [comment]
重启了，还是需要穿秘钥。

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28527117-2c4aa780-70bc-11e7-99a5-1a586d6fb96f.png)

**Comment by ibuler** [comment]
强制刷新一下页面即可

**Comment by yokiy0828** [comment]
还是不行啊，哥。

**Comment by yokiy0828** [comment]
![image](https://user-images.githubusercontent.com/25323406/28527285-aba3b1b6-70bc-11e7-86f9-70b838004624.png)

**Comment by ibuler** [comment]
嗯，刚才理解错了

**Comment by yokiy0828** [comment]
额。。我是修改sudo的配置，但是我不想修改秘钥，我点确认，他必须让我传个秘钥。

**Comment by yokiy0828** [comment]
可以改么？

**Comment by ibuler** [comment]
再git pull一下

**Comment by yokiy0828** [comment]
可以了，谢谢。另外那个资产组推送系统用户的bug什么时候修复呀。
