### ISSUE TITLE
[Bug] 被禁用的资产仍然会出现在koko 的console列表里

### ISSUE THREAD

**Issue by WilliamGuozi** [jumpserver/jumpserver#5743]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1

**浏览器版本**

**Bug 描述**
被禁用的资产仍然会出现在koko 的console列表里

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
暂且无法禁用console的列表显示，不过会调整登录策略。如果选中该禁用资产会有提示，且文件管理也不会显示。#https://github.com/jumpserver/koko/pull/565

**Comment by WilliamGuozi** [comment]
之前的版本 禁用的主机 是不会显示在console列表里

**Comment by jym503558564** [comment]
v2.9.0版本将优化，可等待新版本发布进行测试。
