### ISSUE TITLE
[Question]资产IP无法使用主机名方式，是否有办法解决

### ISSUE THREAD

**Issue by MRwangyd** [jumpserver/jumpserver#5748]
![image](https://user-images.githubusercontent.com/27405334/111122824-87d85100-85a9-11eb-9844-04988dcf8792.png)
![image](https://user-images.githubusercontent.com/27405334/111122830-8ad34180-85a9-11eb-89f5-a62165cb98b3.png)

根据应用场景，部分主机只能通过主机名登录（使用ngrok做内网穿透，指定了ssh的config），修改jms_celery增加ssh的config配置后可以通过连接检测
jms_koko同样配置了ssh的config，但是登录的时候报主机名解析错误

**Comment by MRwangyd** [comment]
@wojiushixiaobai  请帮助回答一下

**Comment by MRwangyd** [comment]
jms版本2.6.2，容器化部署

**Comment by ibuler** [comment]
去容器里解析一下

nslookup monitor22855
