### ISSUE TITLE
[Bug] V2.6.1网页打开缓慢

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#5755]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.6.1

**浏览器版本**
Chrome

**Bug 描述**
之前是在ubuntu 下搭建1.5.0 版，网页打开很快，web终端的资产列表秒速加载。硬件配置：2C2G
后来改成centos7 下搭建2.6.1，登录页面，登录后跳转，资产清单，web终端的资产列表要转圈圈，而且连接RDP 和SSH连接比之前慢很多。硬件配置：4C6G 

两者均使用SSD

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
@sicode 可升级至最新版本进行测试，最近版本有优化登录页面、资产、资产授权树等
