### ISSUE TITLE
好像没人问子目录的问题，我来问问

### ISSUE THREAD

**Issue by zrx879582094** [jumpserver/jumpserver#577]
请问一下，jumpserver是否支持配置子目录呢？我想把jumpserver的服务部署在nginx后端，用nginx代理访问，但是机器上有多个服务，例如jenkins，zabbix。想实现通过子目录反代jumpserver的web服务，即通过nginx访问www.example.com/jumpserver代理到jumpserver的服务，但是好像nginx的rewrite规则与jumpserver的规则冲突，请问能否提供一个修改为子目录的方法呢？

**Comment by ibuler** [comment]
不支持

**Comment by ChowRex** [comment]
那请问以后有没有增加的计划？

**Comment by shuxiao9058** [comment]
同问，现在怎么配置呢？
