### ISSUE TITLE
[Bug] xpack云管无法同步azure资源

### ISSUE THREAD

**Issue by LeiyuanBlog** [jumpserver/jumpserver#5784]
**JumpServer 版本(v1.5.9以下不再支持)**

2.7.1
**浏览器版本**
chrome mac

**Bug 描述**
 xpack云管无法同步azure资源

**Bug 重现步骤(有截图更好)**
1.  
2. 

<img width="799" alt="截屏2021-03-17 下午6 52 22" src="https://user-images.githubusercontent.com/44362360/111456524-138ce180-8752-11eb-9a4c-1cd56eb88775.png">

**Comment by LeiyuanBlog** [comment]
大佬们有看出来是什么问题吗，期待大佬们的回复～～～

**Comment by ibuler** [comment]
已修复，2.8.0
