### ISSUE TITLE
仪表盘优化建议

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#5786]
- [ ] 希望可以在一个界面上显示所有组织下面的资产总数、用户总数等信息；
- [ ] 高危操作次数及详细信息在仪表盘页面可以显示
- [ ] 命令记录中如果包含高危命令，希望可以高亮显示
- [ ] TOP10的列表有按天及按周两种显示方式，默认按天实现
- [ ] 资产TOP10列表增加IP及系统名称字段显示

**Comment by ibuler** [comment]
东区反馈

**Comment by weishuo6** [comment]
4、TOP10的列表有按天及按周两种显示方式，默认按天实现
5、资产TOP10列表增加IP及系统名称字段显示
