### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ewinlu** [jumpserver/jumpserver#5792]
**JumpServer 版本(v1.5.9以下不再支持)**

jms版本2.5.4  
**浏览器版本**
chrome  89.0.4389.90

**Bug 描述**
发现如果nginx配置server_name和ssl证书后，windows上传文件超过约5mb后就会报错，没有权限，但是传小文件20kb左右没问题。

**Bug 重现步骤(有截图更好)**
1.  
![upload_failed](https://user-images.githubusercontent.com/50916123/111586128-548d0080-87fb-11eb-95d8-68c99a397e94.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
- [多层 nginx 反向代理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)
