### ISSUE TITLE
连接资产 xxx 发生错误：认证失败（用户名或密码错误）

### ISSUE THREAD

**Issue by kun376361** [jumpserver/jumpserver#5795]
**请描述您的问题.**

从1.4.10迁移到2.7.1出现所有服务器root账号无法登录，报错连接资产 xxx 发生错误：认证失败（用户名或密码错误），其他账号可以正常登录。

升级参考文档https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

koko错误日志
[ERRO] Conn[865f9c04-e30d-4b0d-8d02-76233b7c9752] did not found cache ssh client(root@xxx)
[ERRO] parse private key with passphrase error: ssh: not an encrypted key
Conn[865f9c04-e30d-4b0d-8d02-76233b7c9752] create ssh client (root@xxx) err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain
[ERRO] Conn[865f9c04-e30d-4b0d-8d02-76233b7c9752] getting srv conn failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password publickey], no supported methods remain

1.4.10版本可以正常登录，迁移到2.7.1出现这个问题，所有服务器除root账号外其他账号可以正常登录。

**Comment by wml3** [comment]
core的token是否替换？

**Comment by kun376361** [comment]
已经替换过了，其他普通账号登录正常。

**Comment by wml3** [comment]
以前也遇到过类似的情况，低版本升级上来认证失败，root账号不多的话，手动更新一下密码

**Comment by kun376361** [comment]
我的服务器全部使用密钥登录，尝试更新某一台机器的root账号私钥，依然无法登录，还是认证报错。但是发现启用某台服务器的密码认证后，更新root账号的密码，可以正常登录。服务器的密钥配置不会有问题，旧版本和手动执行ssh都可以正常使用密钥登录。

**Comment by kun376361** [comment]
我不能启用所有服务器的密码登录，现在的问题就是root账号无法使用密钥登录了，单独更新密钥以及删除服务器再次添加依然无效，只有root账号有这个问题。

**Comment by CandySunPlus** [comment]
有同样的问题，不知道问题解决了么 @kun376361

**Comment by ChenNengNeng** [comment]
有同样的问题，是默认采用密码验证了么？

**Comment by TheBestLL** [comment]
not an encrypted key.  同样的问题 而且机器比较多 请问一下如何处理

**Comment by wumingbin** [comment]
> 有同样的问题，是默认采用密码验证了么？

感觉默认是采用密码验证

**Comment by fanmaoyang** [comment]
2023-03-28 22:12:31 [ERRO] connection() error occured during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.
