### ISSUE TITLE
[Bug] 命令过滤对交换机设备无效

### ISSUE THREAD

**Issue by conupefox** [jumpserver/jumpserver#5801]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.8.0 GPLv2.

**浏览器版本**
ssh

**Bug 描述**
已设置好命令过滤，输入的命令提示是禁止的，但是实际可正常执行。

![dis](https://user-images.githubusercontent.com/3516647/111734129-75655c80-88b4-11eb-8e5c-215b0984c1d3.png)

<h3c 6800>sys  
命令 `sys  ` 是被禁止的 ...

System View: return to User View with Ctrl+Z.
[h3c 6800]int te1/0/3
命令 `int te1/0/3` 是被禁止的 ...

[h3c 6800-Ten-GigabitEthernet1/0/3]

[h3c 6800-Ten-GigabitEthernet1/0/3]dis version
H3C Comware Software, Version 7.1.070, Release 2612P06
Copyright (c) 2004-2019 New H3C Technologies Co., Ltd. All rights reserved.
H3C S6800-54QF uptime is 1 week, 4 days, 3 hours, 14 minutes
Last reboot reason : Cold reboot

**Comment by yuanhaoliang** [comment]
同类问题还有：
https://github.com/jumpserver/jumpserver/issues/4412
https://github.com/jumpserver/jumpserver/issues/2424


然而每次都没解决就把issue强行关掉了。T_T

**Comment by LeeEirc** [comment]
交换机 ssh 登录 ，如果中止输入，使用的快捷键是什么？

**Comment by conupefox** [comment]
http://www.h3c.com/cn/d_200801/329116_30005_0.htm#_Toc185390654

CTRL+X试试？

**Comment by conupefox** [comment]
CTRL_E | 将光标移动到当前行的末尾。
CTRL_X | 删除光标左侧所有的字符。

**Comment by LeeEirc** [comment]
好的，后续调研下。

**Comment by conupefox** [comment]
问题解决了吗？

**Comment by LeeEirc** [comment]
已经优化，参考下 https://github.com/jumpserver/jumpserver/issues/7974
