### ISSUE TITLE
POST /api/terminal/v2/terminal-registrations/ HTTP/1.0" 404

### ISSUE THREAD

**Issue by zhanghba** [jumpserver/jumpserver#5802]
**1.4.1 版本 重新启动guacamole 连接不上**
guacamole 启动信息
![image](https://user-images.githubusercontent.com/35982572/111738690-c1b49a80-88bc-11eb-837b-1e9e5a982338.png)
docker logs
![image](https://user-images.githubusercontent.com/35982572/111738712-cb3e0280-88bc-11eb-915c-46c20a1b7d56.png)
jump gunicorn.log
![image](https://user-images.githubusercontent.com/35982572/111738733-d6912e00-88bc-11eb-88df-7f855afcffc7.png)

**Comment by ibuler** [comment]
2.8.0 去掉了 v2 的api，请把所有组件升成同一个版本

**Comment by ajieup** [comment]
> 2.8.0 去掉了 v2 的api，请把所有组件升成同一个版本

大佬请看一下我的问题，谢谢
