### ISSUE TITLE
[Bug] K8S Web终端无法使用vi命令

### ISSUE THREAD

**Issue by yearnxiao** [jumpserver/jumpserver#5803]
**JumpServer 版本(v1.5.9以下不再支持)**
2.8.0

**浏览器版本**
88.0.4324

**Bug 描述**
K8S Web终端无法使用vi/vim命令编辑文件，使用vi/vim窗口只会出现一个光标，再也无法继续进行其他操作，也无法退出，只能强制关闭窗口。以前vim编辑器粘贴文件格式错乱也就忍了，这次直接连简单的查看编辑功能都无法工作了。还有为什么不能和ssh的终端用相同的方案？每次升级这里都出各种bug.

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![BAFAD675-5445-4a77-8D38-D20A2245EA9F](https://user-images.githubusercontent.com/12027882/111739397-f2490400-88bd-11eb-953c-9d924fa17e2e.png)

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/koko/pull/568
