### ISSUE TITLE
[Feature] 开发部署文档

### ISSUE THREAD

**Issue by Mukvin** [jumpserver/jumpserver#5804]
**请描述您的需求或者改进建议.**
需求：当前想要贡献一些想法，但是对应的开发部署文档却没有，踩了很多坑还是没有部署启动起来

如果可以，应该把贡献的流程做些相关的文档，方便开发者贡献代码啊

**Comment by jym503558564** [comment]
- 欢迎贡献～
@Mukvin 可群里联系@wojiushixiaobai 帮忙部署。

**Comment by Mukvin** [comment]
> * 欢迎贡献～
>   @Mukvin 可群里联系@wojiushixiaobai 帮忙部署。

额，请问哪个什么群，没找到啊

**Comment by jym503558564** [comment]
@Mukvin qq群号：1050391720
