### ISSUE TITLE
授权管理里面添加系统用户使用root

### ISSUE THREAD

**Issue by calistochen** [jumpserver/jumpserver#581]
授权管理里面添加系统用户怎么样才能使用root

**Comment by hellorocky** [comment]
可以给普通的系统用户加上sudo, 把系统用户的sudo字段值改为`ALL`

**Comment by calistochen** [comment]
我这边 现在大部分操作必须用到root用户！sudo不行

**Comment by hellorocky** [comment]
sudo nopasswd 和 root是一样的, 你是什么操作?

**Comment by calistochen** [comment]
部署应用，每天N个

**Comment by ibuler** [comment]
如果想用root，二次修改吧，这个是为了安全，之前有用户不小心删除了系统用户root

**Comment by calistochen** [comment]
删除系统用户的时候会删除了操作系统上对应的系统用户？

**Comment by jiaxiangkong** [comment]
可以在删除系统用户时 加一个复选项  是否同步删除客户端上的用户  如果在细一点 可以选哪些客户端需要同步删除
