### ISSUE TITLE
[Feature] 仪表盘【最近登录记录】

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#5814]
**请描述您的需求或者改进建议.**
v2.8.0
![image](https://user-images.githubusercontent.com/58923704/111874347-d6ce1e00-89cf-11eb-9a34-8b2c0d80850e.png)
如图所示，左侧显示用户的登录时间，日期与时间没有通过字符进行隔开，比如使用空格。影响查看体验
现有:2021/03/2014:43:00 建议改进:2021/03/20 14:43:00
右侧“8 小时，11 分钟”，显示这个的意义不是很大，实际跟左侧什么时间点连接差不多；建议可以显示用户连接到该资产并连接了多长时间。

**Comment by jym503558564** [comment]
非常感谢提出瑕疵，已反馈开发人员进行修改

**Comment by luweijun1992** [comment]
@ibuler 是否收下进行修改完善

**Comment by jym503558564** [comment]
已知问题，未来版本修复
