### ISSUE TITLE
[Feature] 【系统平台】显示建议

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#5815]
**请描述您的需求或者改进建议.**
v2.8.0
当前系统中【平台列表】并没有针对网络设备单独一个，所以单独创建了一个为“Network”平台名称
![image](https://user-images.githubusercontent.com/58923704/111874522-b18ddf80-89d0-11eb-94eb-16a6e798ca6b.png)
当资产选择该平台也是可以正常显示
![image](https://user-images.githubusercontent.com/58923704/111874542-cb2f2700-89d0-11eb-97f5-55ca43b900f2.png)
当使用运维用户登录后，看到的信息并不是创建的“Network”平台名称，而且"Network"名称的基础平台“Other”
![image](https://user-images.githubusercontent.com/58923704/111874669-2eb95480-89d1-11eb-9588-51e4eb4912d4.png)
![image](https://user-images.githubusercontent.com/58923704/111874738-85269300-89d1-11eb-9f4c-f76a265b5587.png)
建议修改运维用户登录后看到的信息为创建的平台名称，而不是基础平台名称。

**Comment by ibuler** [comment]
收到

**Comment by ibuler** [comment]
已完成 https://github.com/jumpserver/jumpserver/pull/5912
