### ISSUE TITLE
堡垒机访问数据库无法跑批，数据无法导入导出。

### ISSUE THREAD

**Issue by liuzhiteng** [jumpserver/jumpserver#5816]
堡垒机-应用管理-数据库，通过这里访问数据库，一个query里面无法跑多条sql，同时select 查询出来的数据也无法导出。同时如果想通过堡垒机向数据库中导入大量的数据，也无法操作。

**Comment by dingpamaoo** [comment]
数据库终端功能是基于omnidb做的二次开发，等导入导出功能做出来不知猴年马月了。我们公司本来打算买企业版了，奈何db终端功能实在是太简陋，最终还是放弃了……

**Comment by ibuler** [comment]
等待排期
