### ISSUE TITLE
[问题]通过堡垒机使用Oracle库

### ISSUE THREAD

**Issue by liuzhiteng** [jumpserver/jumpserver#5817]
**请描述您的问题.**
通过应用管理-数据库来登录Oracle库，点击视图，部分视图正常打开，部分视图无法打开，页面提示：ORA-06502: numeric or value error: character string buffer too small
ORA-06512 ：at line 1
![image](https://user-images.githubusercontent.com/47170523/111890935-31e02f00-8a29-11eb-8048-d606c899450f.png)

**Comment by ibuler** [comment]
https://blog.csdn.net/a214919447/article/details/72964436


这应该和 连接的系统用户的角色有关，换个高级别权限的

**Comment by jym503558564** [comment]
该问题还存在吗？
