### ISSUE TITLE
[Question]部署guacamole组件成功后终端管理里看不到---help me please

### ISSUE THREAD

**Issue by ajieup** [jumpserver/jumpserver#5818]
**请描述您的问题.**
本人环境如下：centos 8 + jumpserver2.7.1 + guacamole_client2.7.1 + guacamole_server1.3 + **java-11-openjdk** + **tomcat10**
部署过程和启动都ok没有报错，不知是哪里的问题就是在jumpserver终端管理不到guacamole? what's the fuck!!!
还是说guacamole组件对于环境有要求？因网上的资料jdk都是装的**java-1.8.0-openjdk**的所以我有这个怀疑，但细想也不太可能。
官方的部署文档是基于docker部署的，我的环境不适合docker所以没有按官方的文档部署guacamole。
求解决！

**Comment by wojiushixiaobai** [comment]
CentOS8 好像不行，我之前测试过，一部分依赖没办法安装
这是我之前使用的部署  [Dockerfile](https://github.com/wojiushixiaobai/Dockerfile/blob/master/guacamole/Dockerfile)

**Comment by ajieup** [comment]
> CentOS8 好像不行，我之前测试过，一部分依赖没办法安装
> 这是我之前 CentOS 7使用的部署 [Dockerfile](https://github.com/wojiushixiaobai/Dockerfile/blob/master/guacamole/Dockerfile)
> 
> ```shell
> set -e \
>     && yum install -y epel-release wget \
>     && yum clean all \
>     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
>     && echo "LANG=$LANG" > /etc/locale.conf \
>     && yum -y localinstall --nogpgcheck https://mirrors.aliyun.com/rpmfusion/free/el/rpmfusion-free-release-7.noarch.rpm \
>     && yum install -y make gcc java-1.8.0-openjdk nc \
>     && yum install -y cairo-devel libjpeg-turbo-devel libpng-devel libtool uuid-devel \
>     && yum install -y ffmpeg-devel freerdp-devel pango-devel libssh2-devel libtelnet-devel libvncserver-devel libwebsockets-devel pulseaudio-libs-devel openssl-devel libvorbis-devel libwebp-devel \
>     && mkdir -p /config/guacamole/lib /config/guacamole/extensions /config/guacamole/data/log/ /config/guacamole/data/record /config/guacamole/data/drive \
>     && cd /config \
>     && TOMCAT_VER=`curl -s http://tomcat.apache.org/tomcat-9.0-doc/ | grep 'Version ' | awk '{print $2}' | sed 's/.$//'` \
>     && wget http://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-9/v${TOMCAT_VER}/bin/apache-tomcat-${TOMCAT_VER}.tar.gz \
>     && tar -xf apache-tomcat-${TOMCAT_VER}.tar.gz \
>     && mv apache-tomcat-${TOMCAT_VER} tomcat9 \
>     && rm -rf apache-tomcat-${TOMCAT_VER}.tar.gz \
>     && rm -rf tomcat9/webapps/* \
>     && echo "java.util.logging.ConsoleHandler.encoding = UTF-8" >> /config/tomcat9/conf/logging.properties \
>     && wget -O docker-guacamole-${Version}.tar.gz https://github.com/jumpserver/docker-guacamole/archive/master.tar.gz \
>     && mkdir /config/docker-guacamole \
>     && tar -xf docker-guacamole-${Version}.tar.gz -C /config/docker-guacamole --strip-components 1 \
>     && rm -rf docker-guacamole-${Version}.tar.gz \
>     && chown -R root:root /config/docker-guacamole \
>     && cd /config/docker-guacamole \
>     && wget http://download.jumpserver.org/public/guacamole-server-1.3.0.tar.gz \
>     && tar -xf guacamole-server-1.3.0.tar.gz \
>     && cd guacamole-server-1.3.0 \
>     && ./configure --with-init-dir=/etc/init.d \
>     && make \
>     && make install \
>     && ldconfig \
>     && cd .. \
>     && wget http://download.jumpserver.org/public/ssh-forward.tar.gz \
>     && tar -xf ssh-forward.tar.gz -C /bin/ \
>     && chmod 755 /bin/ssh-forward \
>     && wget http://download.jumpserver.org/release/${Version}/guacamole-client-${Version}.tar.gz \
>     && tar -xf guacamole-client-${Version}.tar.gz \
>     && cp guacamole-client-${Version}/guacamole-*.war /config/tomcat9/webapps/ROOT.war \
>     && cp guacamole-client-${Version}/guacamole-*.jar /config/guacamole/extensions/ \
>     && cd /config \
>     && mv /config/docker-guacamole/guacamole.properties /config/guacamole/ \
>     && rm -rf /config/docker-guacamole \
>     && yum clean all \
>     && rm -rf /var/tmp/yum*
> ```

所有的依赖我都成功安装的，没有报错。我看了下docker部署的组件都是一个版本，如2.7.1。如果不是同一个版本就会有问题。我的guacamole server是1.3，client是2.7.1，jumpserver是2.7.1，不知是不是这个有问题。但是guacamole server最新的版本就是1.3啊，不知docker里的jumpserver/guacamole:v2.7.1是在哪里下载..跪了...好痛苦~

**Comment by ajieup** [comment]
我的KoKo组件是2.7.1是手动部署的没有通过docker，能正常在线使用。

**Comment by wojiushixiaobai** [comment]
我发给你的就是 v2.8.1 可以用的 guacamole
[jumpserver/guacamole](https://github.com/jumpserver/docker-guacamole) 镜像是基于 Debian 构建

**Comment by ajieup** [comment]
问题自己解决了，果然是版本的问题

**Comment by jym503558564** [comment]
@ajieup 问题解决的话，我先把Issues关了，如还有其他问题，可再次提Issues
