### ISSUE TITLE
coco项目是不是有内存泄漏现象

### ISSUE THREAD

**Issue by hellorocky** [jumpserver/jumpserver#582]
![qq20170730-182934](https://user-images.githubusercontent.com/7486508/28752580-b00b2b4c-7555-11e7-86ac-421bddf11153.png)
![qq20170730-183155](https://user-images.githubusercontent.com/7486508/28752582-b49daf0e-7555-11e7-8b7b-1ec3a77b451a.png)

**Comment by hellorocky** [comment]
用户也就20个左右

**Comment by ibuler** [comment]
这么看，确实有些多，有个内存队列，用来发消息，看看是不是那里

**Comment by hellorocky** [comment]
@ibuler 从哪儿看, 哪一个接口, 能否把代码片段贴过来

**Comment by ibuler** [comment]
https://github.com/jumpserver/coco/blob/master/coco/proxy.py#L83

**Comment by ibuler** [comment]
https://github.com/jumpserver/coco/blob/master/coco/tasks.py#L10-L12

**Comment by ibuler** [comment]
消费 https://github.com/jumpserver/coco/blob/master/run_server.py#L21-L22

**Comment by ibuler** [comment]
最简答的测试方法，去掉put到queue的代码，运行一段时间看看

**Comment by ibuler** [comment]
有进展吗？

**Comment by hellorocky** [comment]
@ibuler 重启了一次就好了, 等下次遇到再试试这个方法吧

**Comment by hellorocky** [comment]
![objgraph-j_d7e455](https://user-images.githubusercontent.com/7486508/29174522-2a24857e-7e19-11e7-98f3-dd6b0043a421.jpeg)

使用objgraph画了一张图, 不知道能不能看出那一块内存泄漏了, 请查看大图

**Comment by ibuler** [comment]
这个工具好形象啊

**Comment by ibuler** [comment]
多运行一段 时间可能比较直观

**Comment by zsjohny** [comment]
@hellorocky @ibuler  确实有内存泄漏，我这边是docker 跑一段就挂。是骤然的增多，然后就下去了，但是不一定哪次骤然的增多就扛不住

**Comment by eli261** [comment]
coco有个现象：线程数会累积，不知内存增长和这个是否有关系。


![image](https://user-images.githubusercontent.com/1914870/33228757-80ce6aa6-d1fd-11e7-9f92-813cde159673.png)

jumpserver0.4 , coco
如上图，我的coco只有两个在线用户，但是，coco线程数已达到300多个。coco已持续运行一个多月。线程数是使用过程中积累的。
线程数会累积这个现象，可以用下面的实验来演示：
我每按照这个步骤操作一次：通过coco连接一个受控机器----退出连接----查询线程数，都会发现线程数加一：
![image](https://user-images.githubusercontent.com/1914870/33229068-978ab704-d202-11e7-9e82-3d637ad386db.png)


![image](https://user-images.githubusercontent.com/1914870/33229069-a7245102-d202-11e7-84e5-7e4390e73eef.png)

**Comment by ibuler** [comment]
应该是的

**Comment by ibuler** [comment]
我在dev分支上重构代码呢，有能力的伙伴参与一下，给点指点

**Comment by liuzheng** [comment]
我猜应该是命令解析这部分fork了一个线程

**Comment by ibuler** [comment]
请各位测试一下新的代码，是否存在内存泄露问题？
