### ISSUE TITLE
仪表盘优化建议（ new）

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#5820]
4、TOP10的列表有按天及按周两种显示方式，默认按天实现
5、资产TOP10列表增加IP及系统名称字段显示

_Originally posted by @weishuo6 in https://github.com/jumpserver/jumpserver/issues/5786#issuecomment-803594078_

**Comment by jym503558564** [comment]
重复 https://github.com/jumpserver/jumpserver/issues/5786
