### ISSUE TITLE
[Question] H3C V5交换机无法删除字符

### ISSUE THREAD

**Issue by HankTrees** [jumpserver/jumpserver#5825]
**请描述您的问题.**
使用Jumpserver配置交换机远程SSH时，H3C V7版本的SSH能正常使用，V5版本的就无法删除字符
网上看了下说是SSH终端的模式要改VT100，这个请问如何进行修改

**Comment by wooveep** [comment]
使用 “Ctrl+h” 可以删除

**Comment by HankTrees** [comment]
谢谢，还想咨询下，这个快捷键可否进行修改？

**Comment by wojiushixiaobai** [comment]
新版本在 luna 设置里面可以修改
