### ISSUE TITLE
日志审计页面都没显示数据，但相应的表有数据

### ISSUE THREAD

**Issue by hugoren** [jumpserver/jumpserver#5826]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver 2.8.1

**浏览器版本**
chrome Version 89.0.4389.90 (Official Build) (x86_64

**Bug 描述**
历史会话，审计不显示，页面报
app.9e4a5dca.js:1 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined

**Bug 重现步骤(有截图更好)**
1.  打开历史会话，就会出现
2. 打开审计(所有的审计), 都会出现app.9e4a5dca.js:1 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
3.  查看数据库的审计表是有数据的

**Comment by jym503558564** [comment]
@hugoren 您说的是审计员角色，打不开历史会话吗

**Comment by hugoren** [comment]
是管理员角色。
日志审计页面能打开，但没数据。
页面报 app.9e4a5dca.js:1 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined

**Comment by jym503558564** [comment]
@hugoren 可在社区群，艾特 我们管理员帮忙查看并解决问题。该问题在我们开发版本测试未复现。

**Comment by hugoren** [comment]
好的，谢～
