### ISSUE TITLE
云管中心同步VMware部分虚拟机无法同步

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#5827]
**JumpServer 版本(v1.5.9以下不再支持)**
2.8.1

**浏览器版本**
Google 88.0.4324.190（正式版本） （64 位）

**Bug 描述**
VC里面虚拟机命名有特殊字符会同步异常
**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/35896106/112005523-d06dac80-8b5d-11eb-9440-788eb08f215e.png)

2. 
![image](https://user-images.githubusercontent.com/35896106/112005594-debbc880-8b5d-11eb-8414-6b57e98baa8c.png)

3.

**Comment by ibuler** [comment]
数据库是 utf8 字符集，不支持表情
