### ISSUE TITLE
Python字符集的问题导致存储过程无法执行

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#5828]

**Comment by ibuler** [comment]
于此相同 https://github.com/jumpserver/trello/issues/911

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/113653332-39a9ff80-96c8-11eb-96cb-937d3e1453c5.png)

**Comment by jym503558564** [comment]
v2.9.0已修复
