### ISSUE TITLE
api如何使用，调用api报错{"detail":"Authentication credentials were not provided."}

### ISSUE THREAD

**Issue by linclin** [jumpserver/jumpserver#583]
curl -X POST -i -v 'http://192.168.18.250:8080/api/assets/v1/groups/' -d '{"name": "test"}'
返回　{"detail":"Authentication credentials were not provided."}
请问如何做ＡＰＩ认证

**Comment by ibuler** [comment]
查看斗鱼分享视频： https://v.douyu.com/show/x0zZVvPQmRY7O4E2

**Comment by ibuler** [comment]
了解后可以在这里描述一下，或者添加到wiki，谢谢

**Comment by linclin** [comment]
视频最后部分讲解了ＡＰＩ的使用，已经很详细了．jumperver现在的ＡＰＩ功能已经能满足常见使用场景了，十分期待后续的ＬＤＡＰ接入和谷歌认证支持．
