### ISSUE TITLE
启动容器时候报错volume 错误

### ISSUE THREAD

**Issue by deep-cds** [jumpserver/jumpserver#5832]
[root@public-component-server2 jumpserver-installer-v2.8.1]# ./jmsctl.sh  start
ERROR: Named volume "y/core/data:/opt/jumpserver/data:rw" is used in service "core" but no declaration was found in the volumes section.

**Comment by wojiushixiaobai** [comment]
如果你不清楚需要按什么，请直接回车，而不是输入y回车
路径变成 y/core/data 导致系统根本找不到这个路径
解决方法：
```bash
rm -rf /opt/jumpserver/config/
./jmsctl.sh install 即可
```

**Comment by deep-cds** [comment]
好的
