### ISSUE TITLE
请问取消修改“用户来源”选项是出于什么目的？

### ISSUE THREAD

**Issue by dingpamaoo** [jumpserver/jumpserver#5838]
目前刚刚升级2.6.2版本，发现无法修改用户来源。
我们公司目前是使用ldap认证，登陆后用户来源默认为LDAP，认证后由后台程序定期使用jumpserver的api修改为数据库（local）用户来源，然后让用户可以使用jumpserver页面来修改密码。
如果取消了该选项，我只能修改后台程序去数据库里改来源了……
请问取消了“用户来源”的修改选项是出于怎样的目的？以后有没有计划再开放该选项？

**Comment by dingpamaoo** [comment]
2.4.4版本是可以修改的
![image](https://user-images.githubusercontent.com/8704246/112267761-e6d84d00-8cb0-11eb-89af-9cd9084abb89.png)
![image](https://user-images.githubusercontent.com/8704246/112267779-ee97f180-8cb0-11eb-94c3-882a40b47681.png)

**Comment by jym503558564** [comment]
@dingpamaoo 最新版本重新放开了修改用户来源，可更新进行测试

**Comment by jym503558564** [comment]
@dingpamaoo 请升级至2.8.2版本，该版本已重新开放修改用户来源。感谢持续关注并使用JumpServer。
