### ISSUE TITLE
你好,我在使用jumpserver应用配置数据库连接的时候报错

### ISSUE THREAD

**Issue by XzBuleSky** [jumpserver/jumpserver#5839]
Connect database 192.168.1.252 error: start local pty err: exec: not started

Connect database 192.168.1.252 error: start local pty err: fork/exec /usr/bin/mysql: Setctty set but Ctty not valid in child

**Comment by jym503558564** [comment]
@XzBuleSky 什么版本？

**Comment by cjwsmw** [comment]
Version v2.5.3 GPLv2  版本出现这个问题

**Comment by cjwsmw** [comment]
Connect database 192.168.5.134 error: start local pty err: fork/exec /usr/bin/mysql: Setctty set but Ctty not valid in child
开始连接数据库mysql://192.168.5.134:3306/ 0.0Connection closed

**Comment by cjwsmw** [comment]
我是用的是docker部署的，使用的jms_all镜像，koko兼容在容器内，如何升级？官方文档太简陋

**Comment by jym503558564** [comment]
MySQL 版本最低要求是大于 >= 5.7

**Comment by yuzhengyao** [comment]
请问你是怎样解决这个问题的？
