### ISSUE TITLE
昨天创建用户都能登录的，今天就在开提示没权限

### ISSUE THREAD

**Issue by 727023460** [jumpserver/jumpserver#584]
版本：0.4.0 GPL.
/opt/jumpserver/logs/jumpserver.log:2017-08-01 17:50:18 [exception WARNING] Forbidden (Permission denied): /assets/asset/
/opt/jumpserver/logs/jumpserver.log:2017-08-01 17:50:18 [basehttp WARNING] "GET /assets/asset/ HTTP/1.1" 403 22

**Comment by 727023460** [comment]
我将jumpserver整个目录的权限都改成了777，还是无效

**Comment by 727023460** [comment]
好神奇，我再创建个用户，就都正常了

**Comment by hellorocky** [comment]
修改过 token过期时间吗?
