### ISSUE TITLE
[Bug] 升级到v2.8.2后无法显示资产列表

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#5842]
/ui/#/assets/assets

只显示了一个Default
[{"id":"1","name":"Default (0)","title":"Default (0)","pId":"","isParent":true,"open":true,"meta":{"node":{"id":"xxxxx","key":"1","value":"Default"},"type":"node"}}]

早期版本中我们创建了其他根节点 key为0，可能程序没有正确读取出来

**Comment by jym503558564** [comment]
@mrbaiwei 有报错日志吗

**Comment by mrbaiwei** [comment]
> @mrbaiwei 有报错日志吗
没有报错，nginx的状态码200

**Comment by jym503558564** [comment]
@mrbaiwei 可以在社区群联系我们的管理员，帮忙重新迁移一下数据。

**Comment by jym503558564** [comment]
@mrbaiwei 我们将发布v2.8.3版本，持续关注我们版本发布。等升级到此版本后，可再看看是否数据正常。

**Comment by ibuler** [comment]
@mrbaiwei 可以qq群里联系一下 小白 吗

**Comment by mrbaiwei** [comment]
@jym503558564 @ibuler 谢谢，我已经通过手工修改节点归属于Default来解决。
