### ISSUE TITLE
[Feature] 企业版同步vmware资产的问题

### ISSUE THREAD

**Issue by zuluzone** [jumpserver/jumpserver#5843]
1. 同步vmware资产时，只能选择一个系统用户，而vmware上的虚拟机必然有windows、Linux等多种类型
2. 同步过来的虚拟机不能与原来就创建了资产自动合并或者忽略，结果就重复了

**Comment by jym503558564** [comment]
https://github.com/jumpserver/jumpserver/issues/4842 ： 云环境同步资产操作系统会存在多种，管理用户也会根据操作系统类型定义多种。现在这个选项只能选一种管理用户，导致同步上来的资产管理用户均为一种类型，无法满足企业生产场景
