### ISSUE TITLE
[Question] mysql 协议的数据库客户端未安装

### ISSUE THREAD

**Issue by jacknotes** [jumpserver/jumpserver#5845]
**请描述您的问题.**
连接mysql资产的时候，显示mysql协议 的数据库客户端未安装，可是查看python包，有客户端，详情如图。

![image](https://user-images.githubusercontent.com/58760465/112416328-6ec96000-8d60-11eb-932e-43885c0a34dd.png)
![image](https://user-images.githubusercontent.com/58760465/112416391-8c96c500-8d60-11eb-873d-9b12ea36dbc5.png)

**Comment by wojiushixiaobai** [comment]
自行部署的 koko 组件请自行安装 mysql-client

**Comment by jacknotes** [comment]
mysql-client是已经安装的，但是koko-2.5.4版本就是不行，我回滚到koko-2.5.3后，可以使用了。不会报“mysql协议的数据库客户端未安装这个错误了”。

![image](https://user-images.githubusercontent.com/58760465/112471082-6bf15e00-8da6-11eb-8011-be3943f9b3bc.png)

**Comment by jym503558564** [comment]
@jacknotes 好的，问题已决定，我先关掉Issues。如还有其他问题，可再次提Issues。非常感谢使用并持续关注JumpServer。

**Comment by madalion** [comment]
你好，我也碰到这个问题了，客户端都安装了，还是提示这个
koko版本：  v2.1.2
