### ISSUE TITLE
[Feature] 得到执行命令的执行时间而不仅仅是记录时间

### ISSUE THREAD

**Issue by Z000000** [jumpserver/jumpserver#5846]
**请描述您的需求或者改进建议.**

现在terminal_command的timestamp记录的是记录command的时间而不是command产生的时间，对于安全生产排查问题会产生时间不一致性，加入create_timestamp就更加完美了

**Comment by jym503558564** [comment]
重复问题 https://github.com/jumpserver/jumpserver/issues/5847
