### ISSUE TITLE
[Feature]记录commad的执行的时候的时间而不仅仅是记录command的时间

### ISSUE THREAD

**Issue by Z000000** [jumpserver/jumpserver#5847]
现在terminal_command的timestamp记录的是记录command的时间而不是command产生的时间，对于安全生产排查问题会产生时间不一致性，加入create_timestamp就更加完美了

**Comment by jym503558564** [comment]
@Z000000 https://github.com/jumpserver/jumpserver/issues/5849 重复问题，可在一个Issues里提，无需提多个重复提多次
