### ISSUE TITLE
[Bug] 仪表盘在线用户和会话跳转链接有误

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#5850]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver2.8.2

**浏览器版本**
chrome 89.0.4389.90（正式版本） (x86_64) for mac
**Bug 描述**
1 、在会话管理首先点击历史会话后，再切换到仪表盘，点击在线用户，跳转到了历史会话。
2、同样在仪表盘点击在线会话，也是一样跳转到历史会话了。

**Bug 重现步骤(有截图更好)**
1.  按步骤测试可以重现
2. 
3.

**Comment by jym503558564** [comment]
@uranus829  已知问题，已反馈给开发人员，将在未来版本进行优化。请持续关注我们版本发布情况。
