### ISSUE TITLE
远程连接Win10 LTSC版本的系统，会导致黑屏

### ISSUE THREAD

**Issue by zhengkang2020** [jumpserver/jumpserver#5852]
**问题**

远程连接Win10 LTSC版本的系统，会导致黑屏

**需求**

通过2.7和2.8版本的Jumpserver添加Win10 LTSC版本的资产，只需要远程功能；

添加域管理员权限的用户为管理用户和系统用户（同一个域用户）

**描述**

1. 导致系统用户（域用户）登录黑屏，有鼠标，没有桌面，CRTL+ALT+DEL能弹出界面，打不开任务管理器

2. 导致原来能正常登录的本地管理员用户再次登录后也是黑屏，情况同域用户

3. 在电脑前登录同样黑屏，只能还原或者重新安装系统。（安全模式能进，但是解决不了问题）

![image](https://user-images.githubusercontent.com/67989011/112604791-87657300-8e51-11eb-9171-59c81b2cd5ca.png)

同样使用正常版本安装的系统能正常远程

![image](https://user-images.githubusercontent.com/67989011/112605980-d52eab00-8e52-11eb-9d6a-c55b40b7d692.png)

![image](https://user-images.githubusercontent.com/67989011/112606143-014a2c00-8e53-11eb-9cf3-766c78d299a0.png)

系统镜像都是在itellyou下载的

Win10 LTSC 版本：cn_windows_10_enterprise_ltsc_2019_x64_dvd_9c09ff24.iso

Win10 正常版本：cn_windows_10_enterprise_version_1703_update_march_2017_x64_dvd_10194191.iso

**Comment by jym503558564** [comment]
@zhengkang2020 测试连接正常，请查看账户密码是否设置正确。其他windows版本能登录吗，还是只有windows-10不能登录？
![image](https://user-images.githubusercontent.com/40739051/112925178-0a354900-9144-11eb-8234-42eb45ed8377.png)

**Comment by zhengkang2020** [comment]
> @zhengkang2020 测试连接正常，请查看账户密码是否设置正确。其他windows版本能登录吗，还是只有windows-10不能登录？
> ![image](https://user-images.githubusercontent.com/40739051/112925178-0a354900-9144-11eb-8234-42eb45ed8377.png)

感谢回复，用的是一个管理、系统用户（域用户）分别登录Win10 LTSC及Win10 专业版，您这边测试的是域用户吗？

**Comment by jym503558564** [comment]
@zhengkang2020 windows-10，连接失败，guacamole日志截图一下。方面我们这边开发人员排查一下问题

**Comment by jym503558564** [comment]
@zhengkang2020 问题有进展吗？

**Comment by zhengkang2020** [comment]
现在将Win10 LTSC2019版本升级到20H2版本，暂时没有问题了

**Comment by zhengkang2020** [comment]
过一段时间重新连接，发现不管什么版本的Win10都重新出现这个问题。包括20H2版本

**Comment by zhengkang2020** [comment]
问题已经解决，是域账号未在domain users组导致远程桌面黑屏
