### ISSUE TITLE
jumpserver/jms_all:v2.8.2 web页面出不来docker安装，别的正常

### ISSUE THREAD

**Issue by menglingqian0218** [jumpserver/jumpserver#5855]
![image](https://user-images.githubusercontent.com/29305786/112711137-12ea0d00-8f01-11eb-8087-fb759e2e1e27.png)

jumpserver/jms_all:v2.8.2 web页面出不来，

**Comment by jym503558564** [comment]
@menglingqian0218 参考安装文档，查看配置文档是否正确https://docs.jumpserver.org/zh/master/install/setup_by_lb/

**Comment by wojiushixiaobai** [comment]
验证无问题，应该是koko没有注册上，建议使用最新版本的安装方式。
或者到容器里面检查下 koko 的状态
```bash
docker exec -it jms_all bash
cd /opt/koko
cd logs
```
看看里面的日志
