### ISSUE TITLE
[Bug] 资产树文件夹无法重命名

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#5859]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.2 GPLv2

**浏览器版本**
windows edge 89.0.774.63 

**Bug 描述**
已穿创建的资产数里的文件夹无法重命名，只能用默认名字 “新节点 1” 等

**Bug 重现步骤(有截图更好)**
1.  在资产数Default目录下创建新节点。
2. 创建的时候对文件夹重命名，输入新的名字后回车保存会提示“请求错误，请检查填写内容”，只能用“新节点 1”
3. 已创建的文件夹也无法重命名，报他同样的错误
4. 再穿创建新的文件夹也是他同样的情况。

**Comment by jym503558564** [comment]
@rex5652 社区版本吗？

**Comment by rex5652** [comment]
@jym503558564 对的，社区版

**Comment by jym503558564** [comment]
@rex5652 无法复现该问题，把错误日志截图一下。

**Comment by rex5652** [comment]
@jym503558564 日志应该在哪里看呢？界面上的错误我截了
![Snipaste_2021-03-30_11-11-20](https://user-images.githubusercontent.com/1674158/112928257-dc063800-9148-11eb-879f-a8d4c560c1d3.png)

**Comment by jym503558564** [comment]
- F12 控制台截图一下报错信息
- 部署服务器上 docker logs -f jms_core ，查看一下core的报错信息，并截图。

**Comment by rex5652** [comment]
@jym503558564 F12前端能看到错误，但是core并没有报错
![Snipaste_2021-03-30_16-14-07](https://user-images.githubusercontent.com/1674158/112956454-1389da00-9173-11eb-9c54-c2d5b186b538.png)
![Snipaste_2021-03-30_16-14-16](https://user-images.githubusercontent.com/1674158/112956460-15539d80-9173-11eb-9b62-b8194c7e0335.png)

**Comment by jym503558564** [comment]
`cd /opt/jumpserver/core/logs`
`tail -f jumpserver.log`

**Comment by rex5652** [comment]
@jym503558564 修改时报错，并没日志

> `cd /opt/jumpserver/core/logs`
> `tail -f jumpserver.log`

![Snipaste_2021-03-31_10-20-45](https://user-images.githubusercontent.com/1674158/113081200-ceb18200-920a-11eb-99dd-88f57ced90f4.png)

**Comment by jym503558564** [comment]
创建完节点之后，刷新下资产树能重命名成功吗？

**Comment by rex5652** [comment]
@jym503558564 不行的，还是同样的问题

**Comment by jym503558564** [comment]
@rex5652 社区群里联系一下武汉小白

**Comment by jym503558564** [comment]
@rex5652 该问题有得到解决吗

**Comment by rex5652** [comment]
暂时还没来得及联系武汉小白，之后再联系。谢谢
