### ISSUE TITLE
资产授权不支持模糊搜索？[Question] 

### ISSUE THREAD

**Issue by Xuejicha0** [jumpserver/jumpserver#5860]
最近刚从1.5 版本升级到 2.8  发现资产授权只能精确搜索，，查找授权规则相当不方便，现在是不支持模糊搜索了吗

**Comment by zuluzone** [comment]
是的，大小写敏感，用起来不方便

**Comment by jym503558564** [comment]
感谢反馈，我们开发人员正在优化。请耐心等待，持续关注我们版本发布情况。

**Comment by ibuler** [comment]
重复 https://github.com/jumpserver/jumpserver/issues/5905，按照提示来解决
