### ISSUE TITLE
[Docs] JumpServer API 变更记录

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#5866]
## 这里将维护 JumpServer 以后的 API 变更

提交 PR 到 dev 之前，请务必更新这个 issue

**Comment by ibuler** [comment]
### v2.8
#### 新增 api

- 新增各类型通用api, render-to-json，可以将用户提交的 excel，csv 渲染成 json，为上传下载优化做准备


路径 | 新增
-- | --
/api/v1/assets/admin-users/render-to-json/ |  
/api/v1/assets/asset-users/render-to-json/ |  
/api/v1/assets/assets/render-to-json/ |  
/api/v1/assets/cmd-filters/{filter_pk}/rules/render-to-json/ |  
/api/v1/assets/cmd-filters/render-to-json/ |  
... | 


- 新增 登录 JumpServer ACL 控制 api

名称 | 方法 | 路径 | 参数
-- | -- | -- | --
acls_login-acls_partial_update | PATCH | /api/v1/acls/login-acls/{id}/ | 见文档
acls_login-acls_delete | DELETE | /api/v1/acls/login-acls/{id}/ | 见文档 
acls_login-acls_update | PUT | /api/v1/acls/login-acls/{id}/ | 见文档
acls_login-acls_render_to_json | POST | /api/v1/acls/login-acls/render-to-json/ | 见文档 
acls_login-acls_partial_bulk_update | PATCH | /api/v1/acls/login-acls/ | 见文档 
acls_login-acls_bulk_delete | DELETE | /api/v1/acls/login-acls/ | 见文档
acls_login-acls_create | POST | /api/v1/acls/login-acls/ | 见文档 
acls_login-acls_bulk_update | PUT | /api/v1/acls/login-acls/ | 见文档 

- 新增 登录资产 ACL 控制 api

名称 | 方法 | 路径 | 参数
-- | -- | -- | -- 
acls_login-asset-acls_partial_update | PATCH | /api/v1/acls/login-asset-acls/{id}/ | 见文档 
acls_login-asset-acls_delete | DELETE | /api/v1/acls/login-asset-acls/{id}/ | 见文档
acls_login-asset-acls_update | PUT | /api/v1/acls/login-asset-acls/{id}/ | 见文档
acls_login-asset-acls_read | GET | /api/v1/acls/login-asset-acls/{id}/ | 见文档 
acls_login-asset-acls_render_to_json | POST | /api/v1/acls/login-asset-acls/render-to-json/ | 见文档
acls_login-asset-acls_partial_bulk_update | PATCH | /api/v1/acls/login-asset-acls/ | 见文档
acls_login-asset-acls_bulk_delete | DELETE | /api/v1/acls/login-asset-acls/ | 见文档
acls_login-asset-acls_create | POST | /api/v1/acls/login-asset-acls/ | 见文档
acls_login-asset-acls_bulk_update | PUT | /api/v1/acls/login-asset-acls/ | 见文档 
acls_login-asset-acls_list | GET | /api/v1/acls/login-asset-acls/ | 见文档

**Comment by jym503558564** [comment]
### v2.7
#### 新增 api

**Comment by BaiJiangJie** [comment]
不再维护。
