### ISSUE TITLE
资产页面，自定义显示没有标签选项（萤石用户需求）

### ISSUE THREAD

**Issue by Fit2Cloud-Onedream** [jumpserver/jumpserver#5867]
资产页面，显示的字段自定义里面没有标签这个选项
![image](https://user-images.githubusercontent.com/80380041/112926542-2a660780-9146-11eb-99a9-bcad9d39ab6d.png)

**Comment by wml3** [comment]
萤石客户需求，可以提高优先级

**Comment by Fit2Cloud-Onedream** [comment]
迁移需求至内部仓库https://github.com/jumpserver/trello/issues/967
