### ISSUE TITLE
docker build 镜像之后 静态文件全是404[Bug] 

### ISSUE THREAD

**Issue by TencentJeyan** [jumpserver/jumpserver#5869]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.2

**浏览器版本**
chrome 版本 89.0.4389.90（正式版本） (x86_64)

**Bug 描述**
使用 Dockerfile 构建之后 docker run 启动 -p 8080:8080
访问 localhost:8080 静态文件全部404

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/69785820/112958942-8431f600-9175-11eb-836b-c03c80e8dec5.png)

**Comment by jym503558564** [comment]
@TencentJeyan  请查看Dockerfile的说明。

**Comment by TencentJeyan** [comment]
> @TencentJeyan 请查看Dockerfile的说明。

请请教一下 Dockerfile 说明是哪个文件 可以给个链接吗

**Comment by TencentJeyan** [comment]
> @TencentJeyan 请查看Dockerfile的说明。

@jym503558564  请教一下 Dockerfile 说明哪里可以看到，没找到

**Comment by wojiushixiaobai** [comment]
https://github.com/jumpserver/Dockerfile
https://github.com/wojiushixiaobai/Dockerfile
参考下，集成方法参考 nginx 的配置

**Comment by TencentJeyan** [comment]
> https://github.com/jumpserver/Dockerfile
> https://github.com/wojiushixiaobai/Dockerfile
> 参考下，集成方法参考 nginx 的配置

@wojiushixiaobai 意思是 这个镜像直接 docker run 跑起来是不成功的 必须配套 nginx 吗

**Comment by ibuler** [comment]
是的
