### ISSUE TITLE
[Question] Not found __version__: No module named 'django.db.models.functions'

### ISSUE THREAD

**Issue by unslur** [jumpserver/jumpserver#5872]
**请描述您的问题.**
最新版本 2.8.2
无法启动
![image](https://user-images.githubusercontent.com/15623689/113015992-a137ea80-91b0-11eb-8353-5a64339f94ad.png)
是一个python module 找不到了

**Comment by unslur** [comment]
我在2.7.1的时候就是这个错误。升级后还是这样的
镜像：jumpserver/core:v2.8.2

**Comment by unslur** [comment]
貌似2.7.1的数据库备份不支持2.8.2的。还原后访问就是500报错

**Comment by wojiushixiaobai** [comment]
你的持久化路径可能有问题，或者你的镜像有问题
此问题一般是由于缺少 JumpServer 代码导致
你可以尝试
```bash
docker pull jumpserver/core:v2.8.2
./jmsctl.sh upgrade
```

**Comment by unslur** [comment]
今天jms_core又挂了， 镜像已经是2.8.2。好奇怪，还是这个错误：“Not found __version__: No module named 'django.db.models.functions'”，升级也报错
![image](https://user-images.githubusercontent.com/15623689/113266508-efabcd00-9307-11eb-9f64-acb2133c0e52.png)

**Comment by ibuler** [comment]
很久以前某个用户也有这问题，docker 容器的代码丢了
