### ISSUE TITLE
一键安装启动脚本报错./jmsctl.sh start

### ISSUE THREAD

**Issue by mingzhu1985** [jumpserver/jumpserver#5875]
我用github上的一键安装命令安装了一台jumpserver，提示成功了。启动的时候会报错
[root@feiw-jumpserver ~]# ./jmsctl.sh start
-bash: ./jmsctl.sh: 没有那个文件或目录
请问，这要怎么处理。

谢谢。

**Comment by wojiushixiaobai** [comment]
```bash
cd /opt/jumpserver-installer-v2.8.2
./jmsctl.sh --help
```

**Comment by mingzhu1985** [comment]
> ```shell
> cd /opt/jumpserver-installer-v2.8.2
> ./jmsctl.sh --help
> ```

谢谢，进入这个目录后可以运行了。

**Comment by jym503558564** [comment]
@mingzhu1985 解决了，我先把Issues关了，如还有其他疑问可再次提Issues.
