### ISSUE TITLE
2.8.2版本linux终端链接，系统用户显示成堡垒机用户名，不是配置的linux到系统用户

### ISSUE THREAD

**Issue by woshidafengzi** [jumpserver/jumpserver#5876]

**Comment by jym503558564** [comment]
@woshidafengzi 2.8.8版本？我们目前最新的版本是2.8.2

**Comment by woshidafengzi** [comment]
![Uploading image.png…]()

**Comment by jym503558564** [comment]
@woshidafengzi 是与用户名同名的系统用户？ 截图看一下比较清晰

**Comment by woshidafengzi** [comment]
不是，堡垒机系统用户名是admin，Linux系统用户名是root和hkai

**Comment by woshidafengzi** [comment]
点击“web终端”，点击一个资产，登录资产自动使用登录堡垒机用户（admin）的账号登录资产，不是使用的资产的系统用户（hkai）登录的

**Comment by woshidafengzi** [comment]
![image](https://user-images.githubusercontent.com/22409098/113105950-c40be280-9234-11eb-9dd3-cfabec8755a2.png)

**Comment by jym503558564** [comment]
@woshidafengzi 该系统用户详情截图一下

**Comment by jym503558564** [comment]
@woshidafengzi 是否有多个授权规则，多个系统用户，同时授权该资产。

**Comment by woshidafengzi** [comment]
不好意思，找到原因了，是“用户名与用户相同”这个配置的原因

**Comment by jym503558564** [comment]
@woshidafengzi 好的～
