### ISSUE TITLE
添加新的用户时，需要手动推送系统用户，但是推送后用户登录时环境变量无法生效

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#5877]
截图是用户登录时的情况，

![图片](https://user-images.githubusercontent.com/63391681/113110739-fff57680-9239-11eb-8c8e-54054ef6b922.png)

**Comment by Allenzhang-92** [comment]
手动将/etc/skel 目录下的.bash 文件复制到用户家目录后，才可以正常显示

**Comment by uranus829** [comment]
这边遇到也是一样

**Comment by ibuler** [comment]
什么操作系统呢？默认创建用户 用的是 

useradd 操作，有没有 skel ，应该是系统的默认操作

**Comment by Allenzhang-92** [comment]
> 
> 
> 什么操作系统呢？默认创建用户 用的是
> 
> useradd 操作，有没有 skel ，应该是系统的默认操作

红帽的操作系统，这个情况只是在个别机器上出现了，大多数都没问题。

**Comment by uranus829** [comment]
centos7.9测试系统用户自动推送，有这个问题。
