### ISSUE TITLE
[Bug] koko无法启动

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#5878]
**JumpServer 版本(v1.5.9以下不再支持)**
2.8.2

**浏览器版本**

**Bug 描述**
默认的极速安装，完成后启动，koko一直处于无法启动状态。看日志，报错。

2021-03-31 20:15:58 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"name":["名称重复"]}
2021-03-31 20:15:58 [ERRO] register access key failed

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
-可把重名的koko离线终端删掉，另外koko name 参数在 koko 的配置文件中 config.yml，可以自定义。

**Comment by vicenkaka** [comment]
更改name 解决不了问题

**Comment by vicenkaka** [comment]
虽然都报的“register access key failed” 但我这个不是name 问题，是koko 的版本2.7.1 ,jumpserver 版本2.8.3，版本不一致导致。
http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 404已解决
