### ISSUE TITLE
关于RZ上传慢的问题

### ISSUE THREAD

**Issue by wenjun8888** [jumpserver/jumpserver#5879]
目前版本2.7.0 已知Bug，rz上传会越来越慢，之后卡死。
请问这个Bug会在哪个版本修复？目前使用诸多不便。
非常感谢~

**Comment by jym503558564** [comment]
重复问题 https://github.com/jumpserver/jumpserver/issues/5672。 我们将在后续版本修复，请持续关注我们版本发布。每个月发布一次大版本，若干小版本。
