### ISSUE TITLE
如何调用ansible的api 使用copy模块和file模块啊

### ISSUE THREAD

**Issue by onlywelio** [jumpserver/jumpserver#588]
module_name = 'copy' #script,cp,file....
    module_args = 'src=/root/install.log dest=/tmp'
    # module_name = 'shell' #script,cp,file....
    # module_args = 'ls /'
    task_tuple = ((module_name,module_args),)
    assets = [
        {
        "hostname": "128",
        "ip": "192.168.3.128",
        "port": 22,
        "username": "root",
        "password": "123456",
        #"private_key":	"/host/1.txt"
        }
    ]
    a = run_AdHoc(assets,task_tuple)
    print(a)

返回：
{'contacted': {'128': {'cmd': None, 'stderr': None, 'stdout': None, 'rc': None}}, 'dark': {}}

**Comment by ibuler** [comment]
就是这样使用的

**Comment by onlywelio** [comment]
这样调用，返回是空的，也没执行copy和报错

**Comment by ibuler** [comment]
参考一下 推送系统用户那的逻辑
