### ISSUE TITLE
[Question] jumpserver需要redis几个DB，配置一个DB报错了。

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5880]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/10806595/113229164-f36c2f00-92c8-11eb-9b9a-5fdac1ca6710.png)

**Comment by leim** [comment]
我这边默认使用的0、3、4、5这几个db

**Comment by ibuler** [comment]
JumpServer 会使用以下  Redis DB

0: 默认的
3: celery 异步任务
4: 缓存
5: 保存session
6. websocket 异步数据交换
