### ISSUE TITLE
[Question] 无法获取服务器资产信息

### ISSUE THREAD

**Issue by liqiuyuan** [jumpserver/jumpserver#5885]
使用docker 安装jumpserver 2.8.2版本，添加资产，授权后，手动更新硬件信息，有如下错误

![image](https://user-images.githubusercontent.com/13620049/113277392-3fdc5c80-9313-11eb-82e2-1baf056ce725.png)

**Comment by ibuler** [comment]
设置的 管理用户 密钥有问题

**Comment by liqiuyuan** [comment]
普通用户和管理用户使用同一个密钥, 普通用户通过xshell 可以登录，管理用户无法获取资产信息

**Comment by liqiuyuan** [comment]
管理用户使用密钥无法连接，使用密码可以连接
