### ISSUE TITLE
[Question] 关于2.7.1版本的一些问题

### ISSUE THREAD

**Issue by wenjun8888** [jumpserver/jumpserver#5886]
您好：

上周我于1.4.8版本迁移到了2.7.0版本，昨天又迁移到了2.7.1版本。
目前使用上的几个最主要的问题是：

1.rz的问题，官方说近期修复，这个不提了。
2.复制文本的卡顿，如果我把大段的文本，比如超过20行的文本，使用vim粘贴，会很明显的感觉到画面的卡顿感，如果是直连就没有这个问题，不知是否有优化的方案。
3.有时候某些功能会卡死，比如过一段时间添加了几台主机，那又可能后面几台添加之后推送用户等操作都会失败，我在UI页面手动推送用户也一直处于冒号阶段，有概率通过强刷浏览器解决，但更大的可能是要重启jumpserver才能完成操作。

ps：我试图升级到2.8.2的最新版，但所有权限列表都会消失，我通过SSH登陆只有DEFAULT，组里面没有任何一台服务器。
非常抱歉打扰，请给一些建议，非常感谢~

**Comment by jym503558564** [comment]
@wenjun8888 企业版？

**Comment by wenjun8888** [comment]
> @wenjun8888 企业版？

您好，不是企业版，是普通的社区版本。

**Comment by jym503558564** [comment]
- 关于第二个问题：无法复现。vim粘贴几十行，无卡顿现象。

**Comment by wenjun8888** [comment]
> * 关于第二个问题：无法复现。vim粘贴几十行，无卡顿现象。
> * 关于最后一个问题，升级至最新版本权限列表消失。在升级过程中有没有报什么错，按照社区文档来升级吗？

1.我这里的直观感受比较明显，同一台服务器，直接连和堡垒机，差别挺明显的，不过这个问题还可以接受。

最后一个问题，是的完全按照官方的升级方式，从2.7.1到2.8.2，获取jumpserver-tools，进入upgrade，之后restart。
期间一切正常，没有任何报错。

**Comment by ibuler** [comment]
可以在qq群中找到 @wojiushixiaobai 武汉小白

**Comment by jym503558564** [comment]
@wenjun8888 rz 上传慢的问题已修复，参考该Issues，升级至对应版本https://github.com/jumpserver/jumpserver/issues/5672
