### ISSUE TITLE
ssh密钥登录不上,按照wiki的排查过都没问题

### ISSUE THREAD

**Issue by krisbai** [jumpserver/jumpserver#589]
版本：jumpserver_docker:0.3.2 
日志：
User xiaobai not allowed because account is locked
input_userauth_request: invalid user xiaobai [preauth]
Received disconnect from IP port 52518:0:  [preauth]
Disconnected from IP port 52518 [preauth]

**Comment by ibuler** [comment]
0.3.2的docker已经不再维护
