### ISSUE TITLE
[Question] jumpserver v2.8.2 Windows资源怎么才能上传大文件

### ISSUE THREAD

**Issue by huabuxiang** [jumpserver/jumpserver#5890]
**请描述您的问题.**
 jumpserver v2.8.2 Windows资源怎么才能上传大文件，没有2.8.x版本nginx的jumpserver.conf，最新版本的上传文件大小配置是修改/opt/jumpserver/config/nginx/lb_http_server.conf 里的client_max_body_size 参数？

**Comment by ibuler** [comment]
超过 4G 文件，修改 nginx 配置也不行，guacamole 目前版本不支持
