### ISSUE TITLE
终端无法直接ssh连接资产，No PTY requested.[Bug] 

### ISSUE THREAD

**Issue by 78778443** [jumpserver/jumpserver#5891]
**JumpServer 版本2.8.2**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  资产有权限，使用ssh连接时候必须要进入列表才能连接

```
ssh -p 2222   qingsong.tang@jumpserver.funplus.io    111.111.111.111
qingsong.tang@jumpserver.funplus.io's password:
No PTY requested.
```

**Comment by jym503558564** [comment]
- 不支持使用终端登录时，指定ip

**Comment by 78778443** [comment]
为什么官方文档上的命令示例上显示这个？  https://jumpserver.readthedocs.io/zh/master/user-guide/terminal/web-terminal/

**Comment by jym503558564** [comment]
@78778443 理解可能有误，官网的`ssh -p 2222 用户名@JumpServer IP地址` 中的JumpServer IP地址是指部署jumpsever的ip地址

**Comment by jym503558564** [comment]
@78778443 如还有其他问题，可再次打开Issues
