### ISSUE TITLE
guacamole 无法查看在线监控、历史会话不能快进快退

### ISSUE THREAD

**Issue by wcb0414** [jumpserver/jumpserver#5892]
**请描述您的问题.**
RDP 连接的主机无法查看在线监控、历史会话不能快进快退，也不能拖动播放。

**Comment by jym503558564** [comment]
- 暂不支持rdp连接在线监控

**Comment by ibuler** [comment]
guacamole 官方的 player 目前也不支持快进  https://player.glyptodon.com/
