### ISSUE TITLE
资产导入没有任何提示，但是资产实际并未导入

### ISSUE THREAD

**Issue by xlogin** [jumpserver/jumpserver#5896]
版本:V2.8.2
部署方式：一键docker部署

问题描述：
     下载Excel导入模版，按照提示，新增了带星号的三项内容：主机名、IP、系统平台。
      然后使用文件类型为Execl的导入创建功能，选择上传文件后，点击确认后，没有任何提示，同时相关内容并未导入到堡垒机中。

**Comment by jym503558564** [comment]
@xlogin 节点也是需要填写的。我们在新版本将对导入导出这块有重大优化，可持续关注我们的版本发布情况，进行体验。
