### ISSUE TITLE
终端超时设置不生效

### ISSUE THREAD

**Issue by suxiaojin** [jumpserver/jumpserver#5897]
终端是linux服务器，一段时间无操作（40分钟左右）之后页面就卡住了。应该是超时了。但我在系统设置里面已经更改了超时时间，麻烦查看下。
![image](https://user-images.githubusercontent.com/12642225/113671083-7980df00-96e8-11eb-9861-e2e82308f1a6.png)
这里选项卡变为灰色了

![image](https://user-images.githubusercontent.com/12642225/113667702-bdbdb080-96e3-11eb-9be0-fed099c87a85.png)

**Comment by ibuler** [comment]
应该是 websocket 断开了，是不是休眠了？

**Comment by suxiaojin** [comment]
> 应该是 websocket 断开了，是不是休眠了？
你说的是什么休眠？centos机器，不存在休眠的吧。我用crt连都是正常的

**Comment by suxiaojin** [comment]
你说的是什么休眠？centos机器，不存在休眠的吧。我用crt连都是正常的

**Comment by mike0476** [comment]
> 你说的是什么休眠？centos机器，不存在休眠的吧。我用crt连都是正常的

遇到相同问题，请问是否解决啦？

**Comment by suxiaojin** [comment]
没有，没人回答
