### ISSUE TITLE
config.py配置DEBUG =False导致页面加载无样式

### ISSUE THREAD

**Issue by linclin** [jumpserver/jumpserver#590]
由于调用API报错：
      You're seeing this error because you have <code>DEBUG = True</code> in your
      Django settings file. Change that to <code>False</code>, and Django will
      display a standard page generated by the handler for this status code.
所以将config.py文件的DEBUG =True 改为False，继续访问http://localhost:8080/api/users/，无css样式，js和css请求全部404。将DEBUG =False改为True之后访问回复正常，但是API又不能正常调用

**Comment by ibuler** [comment]
查看一下 Django的部署机制

Django在开启DEBUG·的时候会启动内置的静态文件服务器提供服务，
关闭·DEBUG，Django认为你要生产中部署，需要专业的HTTP SERVER，如 nginx apache
所以这时你需要搭建HTTP SERVER, 把 /static/指向过去
