### ISSUE TITLE
不能使用外部mysql

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#5901]
jumpserver2.8.2
mysql:5.7.33
安装时选择外部数据库

一直提示：ERROR 2002 (HY000): Can't connect to local MySQL server through socket '' (2)
之前使用mariadb10.5.9也是这样

“[root@localhost jumpserver-installer-v2.8.2]# mysql -p -ujpserver -S /var/run/mysqld/mysqld.sock
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.33 MySQL Community Server (GPL)

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
”

**Comment by wojiushixiaobai** [comment]
不要使用127.0.0.1，请使用局域网地址
```
# mysql -h<DB_HOST> -P<DB_PORT> -u<DB_USER> -p<DB_PASSWORD>
mysql -h172.16.0.1 -P3306 -uroot -p******
```
