### ISSUE TITLE
[Question] 如何关闭命令执行时候显示的DEPRECATION WARNING信息？

### ISSUE THREAD

**Issue by bluesdawn** [jumpserver/jumpserver#5903]
2.7.1版本，在命令执行菜单中批量执行命令，显示的内容会带有ansible的 DEPRECATION WARNING 信息，如下：                                Distribution Ubuntu 18.04 on host test should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. 
A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for 
more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
docker容器中没找到ansible.cfg 配置文件进行修改，希望能告知处理方法，谢谢！

**Comment by ibuler** [comment]
@jym503558564 复现一下

**Comment by jym503558564** [comment]
无法复现
