### ISSUE TITLE
V2.8.2 不支持大小写字母模糊搜索 【已解决】

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#5905]
**请描述您的问题.**
V2.8.2在luna的搜索框里现在的版本不支持大小写字母模糊搜索查询了了，比如我有一个资产名称中有关键字“ABC”，现在我只能输入大写的ABC，之前的2.6.2版本是我可以输入小写的“abc”也可以搜索到这个资产，在“资产授权”里也不能根据关键字进行模糊搜索，以后的版本都不支持大小写字母模糊搜索么？建议以后的版本还是支持模糊搜索，方便根据关键字查询。

**Comment by ibuler** [comment]
这个应该是和数据库有关的，因为后来改了数据库的字符校对集导致的，和代码没有关系

```
mysql> show create database jumpserver;
+------------+--------------------------------------------------------------------------------------+
| Database   | Create Database                                                                      |
+------------+--------------------------------------------------------------------------------------+
| jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */ |
+------------+--------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

```

**Comment by aiaiduo** [comment]
> 这个应该是和数据库有关的，因为后来改了数据库的字符校对集导致的，和代码没有关系
> 
> ```
> mysql> show create database jumpserver;
> +------------+--------------------------------------------------------------------------------------+
> | Database   | Create Database                                                                      |
> +------------+--------------------------------------------------------------------------------------+
> | jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */ |
> +------------+--------------------------------------------------------------------------------------+
> 1 row in set (0.01 sec)
> ```

我的这个和您的这个字符集是一样的，但是不修改的话我升级到2.8.2是报错的。
![image](https://user-images.githubusercontent.com/28044296/113803489-404f7a00-978f-11eb-86ba-5e6f07b6c044.png)
这个是我从2.6.2直接升级到2.8.2的字符集的报错，在只能是按照文档修改字符集后才正常升级到2.8.2
![image](https://user-images.githubusercontent.com/28044296/113803625-860c4280-978f-11eb-9ea1-a109bde5ecff.png)
![image](https://user-images.githubusercontent.com/28044296/113803649-945a5e80-978f-11eb-9713-f20bfb77c4fe.png)

**Comment by ibuler** [comment]
还原会不区分大小写的校对集

1. 备份数据库

```
$ mysqldump -uroot -h127.0.0.1 -p jumpserver > jumpserver.sql
$ cp jumpserver.sql jumpserver.sql.$(date '+%Y-%m-%d_%H:%M:%S')
```

2. 修改数据中的校对集

```

$ sed -i 's@COLLATE=utf8_bin@@g' jumpserver.sql
$ sed -i 's@COLLATE utf8_bin@@g' jumpserver.sql

```

3. 创建新库，使用新库

```
mysql > CREATE DATABASE jumpserver_v2 DEFAULT CHARSET utf8;
```

4. 导入表结构和数据
```
$ mysql -uroot -h127.0.0.1 -p  jumpserver_v2 < jumpserver.sql
```

5. 修改配置文件，使用新数据库

```

$ vim /opt/jumpserver/config/config.txtDB_NAME=jumpserver_v2$ ./jmsctl.sh restart
--



```

**Comment by ibuler** [comment]
反馈一下效果

**Comment by aiaiduo** [comment]
我直接按您说的方法修复字符集后导入新的jumpserverV2库bing并修改config配置文件将库修改为jumperver-v2后启动服务提示koko等容器unhealthy，当我直接把原始的jumpserver库导出修改替换字符集后直接导入

原jumpserver库时提示“ Cannot add foreign key constraint”
![Snipaste_2021-04-08_11-15-58](https://user-images.githubusercontent.com/28044296/113963612-79095500-985c-11eb-90a9-b766bb41d2a9.png)

![Snipaste_2021-04-08_11-16-41](https://user-images.githubusercontent.com/28044296/113963606-7444a100-985c-11eb-926f-2dc17bff2b27.png)

**Comment by ibuler** [comment]
@aiaiduo 资产授权里搜不了那是bug，下个版本修复

**Comment by Xuejicha0** [comment]
我已经升级到 v2.8.3 了,   资产授权还是不支持模糊搜索吗?

**Comment by aiaiduo** [comment]
> @aiaiduo 资产授权里搜不了那是bug，下个版本修复

@ibuler V2.8.3版本我测试了一下，“资产授权”里的模糊搜索还是没有修复。

**Comment by aiaiduo** [comment]
> 我已经升级到 v2.8.3 了, 资产授权还是不支持模糊搜索吗?

嗯，是的，我也测试了一下2.8.3 ，是还没有修复。

**Comment by jym503558564** [comment]
马上v2.9.0版本，优化了该问题

**Comment by jym503558564** [comment]
@aiaiduo 升级至v2.9.0
