### ISSUE TITLE
[Bug] SMTP 设置

### ISSUE THREAD

**Issue by fengcharles** [jumpserver/jumpserver#5908]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.8.2 GPLv2.

**浏览器版本**
chrome firefox

**Bug 描述**
邮箱账号密码设置后，无法保存，下次打开还是原来的。

**Bug 重现步骤(有截图更好)**
1.  jms刚装好以后，设置了一次邮箱。由于邮箱录入错误，导致无法发送邮件
2. 选择修改以后，点击测试，是没有问题的，邮件可以正常收到。
3. 点击更新以后提示成功，跳转到其他页面，然后再打开邮箱设置的页面，又恢复成原来的了。
![1](https://user-images.githubusercontent.com/6244198/113798998-d7640400-9786-11eb-874f-f3d3f6d541a6.jpg)
![2](https://user-images.githubusercontent.com/6244198/113799011-db902180-9786-11eb-9d86-cc7bed68af19.jpg)
![3](https://user-images.githubusercontent.com/6244198/113799016-ddf27b80-9786-11eb-9ceb-a40beb873fe9.jpg)
![4](https://user-images.githubusercontent.com/6244198/113799072-f498d280-9786-11eb-9c3b-fb7fedec6a45.jpg)

**Comment by wojiushixiaobai** [comment]
账户密码的问题请取消浏览器账户密码保存

**Comment by fengcharles** [comment]
好的 反复折腾了一堆操作以后，还好保存上了
