### ISSUE TITLE
[Question] 系统用户的推送逻辑

### ISSUE THREAD

**Issue by jxqiuhan** [jumpserver/jumpserver#5916]
**请描述您的问题.**
你好，我想咨询下Jumpserver推送系统用户到资产时，是怎么实现的；
系统用户的权限/home/usr是怎么样的

推送系统用户的目的，就是给系统创建一个新的用户？

**Comment by ibuler** [comment]
推送系统用户，是用 ansible 实现的，根据设置的 sudo，password，密钥等，进行创建用户

**Comment by jym503558564** [comment]
@jxqiuhan 如还有其他问题，可再次打开Issues。如想更深入了解推送，可自行学习ansible.
