### ISSUE TITLE
[Bug] 密码不能包含特殊字符

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#5917]
**JumpServer 版本(v1.5.9以下不再支持)**
- v2.5.2

**浏览器版本**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68

**Bug 描述**
- 更新密码时，提示不能包含特殊字符。
- 下面这个是密码
![image](https://user-images.githubusercontent.com/7349963/113958759-35aae880-9854-11eb-819a-13cd8be1bb0e.png)

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/7349963/113958089-0cd62380-9853-11eb-80ba-2bcab3ef861f.png)

**Comment by jym503558564** [comment]
- 网关暂不支持密码是特色字符

**Comment by ibuler** [comment]
网关这里 ansible 会使用 ssh proxy command 在 shell 中，有特殊字符会导致失效，如 & 代表后台，有 > 可能代表追加，所以屏蔽了

**Comment by seaurching** [comment]
> 网关这里 ansible 会使用 ssh proxy command 在 shell 中，有特殊字符会导致失效，如 & 代表后台，有 > 可能代表追加，所以屏蔽了

这个使用单引号引起来也不行吗？在shell中单引号引起来的特殊字符会原样输出，双引号的会进行转移什么的

**Comment by howge** [comment]
昨天也发现这个问题了，原来是ansible限制了

**Comment by ibuler** [comment]
@seaurching 密码中也有可能有单引号，双引号等，所以干脆所有特殊字符都不允许

**Comment by seaurching** [comment]
> @seaurching 密码中也有可能有单引号，双引号等，所以干脆所有特殊字符都不允许

原来是这个情况呀，那我改掉这个复杂密码吧。
