### ISSUE TITLE
想让各部门可以管理自己的机器[Feature] 

### ISSUE THREAD

**Issue by 78778443** [jumpserver/jumpserver#5918]
**请描述您的需求或者改进建议.**
资产属于多个部门，想让各部门可以管理自己的机器；目前jumpserver只有三种角色，管理员能管理所有资产，希望能加一个资产分配的功能，让各部门管理自己的机器。

**Comment by ibuler** [comment]
rbac正在研究中

**Comment by ibuler** [comment]
不过我们企业版，有多组织的功能，组织管理员可以完全控制这个组织下的资源

**Comment by luweijun1992** [comment]
老广说的没错，企业版的多组织功能可以解决你的需求。
