### ISSUE TITLE
[Errno -3] Try again

### ISSUE THREAD

**Issue by krisbai** [jumpserver/jumpserver#592]
创建用户时发送邮件报错，日志无提示。

Request Method:	POST
Request URL:	http://xxx/juser/user/add/
Django Version:	1.6
Exception Type:	gaierror
Exception Value:	
[Errno -3] Try again
Exception Location:	/usr/lib/python2.7/socket.py in create_connection, line 557
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/jumpserver',
 '/usr/lib/python27.zip',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7/site-packages']
Server time:	Wed, 2 Aug 2017 07:05:15 +0000

**Comment by powerful-heart** [comment]
我现在也遇见了这个问题
