### ISSUE TITLE
[已解决] JMS ssh连接华为交换机成功后,复制或手工建立相同设备窗口一直黑屏没显示。

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#5925]
**REUSE_CONNECTION=false  关闭复用同一用户的 SSH 连接就可以了**

**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.2

**浏览器版本**
 86.0.4240.111

**Bug 描述**
(1)、交换机型号:huawei S5735S-L48T4S-A,ssh已经成功连接华为交换机，但是复制窗口一直显示黑屏，无内容显示,KOKO日志报错，见附件
(2)、交换机会话数设置是vty 0 4,Xshell是可以复制会话的。
(3)、相同的设备，手工添加和复制窗口也不行。

**Bug 重现步骤(有截图更好)**
1.钩选用户名和用户相同，或者固定用户，均测试相同设备复手工连接第二个窗口和复制窗口都不行。

![image](https://user-images.githubusercontent.com/46716344/114003574-70327680-9890-11eb-840d-eddc6ceb13d8.png)

![image](https://user-images.githubusercontent.com/46716344/114028090-a846b300-98aa-11eb-9141-e175de2074f6.png)

2.第一个窗口
![image](https://user-images.githubusercontent.com/46716344/114028744-65390f80-98ab-11eb-8b09-e48a6e139d3a.png)

第二个窗口一直停留在黑屏，无内容状态
![image](https://user-images.githubusercontent.com/46716344/114028406-05daff80-98ab-11eb-90b8-e4e52584b2dd.png)

3.
![image](https://user-images.githubusercontent.com/46716344/114028590-3ae75200-98ab-11eb-8b50-c695aa9c5e8b.png)

4. 当第一个窗口会话超时自动Connection closed后，第二个窗口自动连上了。
![image](https://user-images.githubusercontent.com/46716344/114028979-a03b4300-98ab-11eb-91eb-d69904fe1bdc.png)
![image](https://user-images.githubusercontent.com/46716344/114029146-ceb91e00-98ab-11eb-8bc5-31847c33da58.png)

5.此时koko日志显示
![image](https://user-images.githubusercontent.com/46716344/114029390-088a2480-98ac-11eb-8be1-ab91a6472391.png)

**Comment by luweijun1992** [comment]
> (1)、交换机型号:huawei S5735S-L48T4S-A,ssh已经成功连接华为交换机，但是复制窗口一直显示黑屏，无内容显示,KOKO日志报错，见附件

你的意思是一台设备不能同事打开2个窗口吗？我这边测试是可以正常打开2个窗口，正常使用的。

**Comment by uranus829** [comment]
> > (1)、交换机型号:huawei S5735S-L48T4S-A,ssh已经成功连接华为交换机，但是复制窗口一直显示黑屏，无内容显示,KOKO日志报错，见附件
> 
> 你的意思是一台设备不能同事打开2个窗口吗？我这边测试是可以正常打开2个窗口，正常使用的。

不是你这个意思，我手工连接两个窗口是正常的，就是复制窗口不行。
我交换机用的是域用户，另外我的系统用户钩选的是自动登陆，然后，用户名与用户相同，进去后，手工输入密码的。
