### ISSUE TITLE
求助：版本2.8.2，登录后打开系统设置一直是空白页，看日志返回一直是200.

### ISSUE THREAD

**Issue by Junxieshiguan** [jumpserver/jumpserver#5928]
显示一直都是空白页：![image](https://user-images.githubusercontent.com/37820283/114028385-01aee200-98ab-11eb-9174-fa5e1eb2cabf.png)
返回的日志：![image](https://user-images.githubusercontent.com/37820283/114028429-0b384a00-98ab-11eb-9ed2-d94afd9540f5.png)

**Comment by ibuler** [comment]
浏览器F11，打开调试模式，看看有没有报错

**Comment by Junxieshiguan** [comment]
> 浏览器F11，打开调试模式，看看有没有报错

![image](https://user-images.githubusercontent.com/37820283/114122744-82112980-9923-11eb-87c9-b475cbc829bd.png)
看上去有个base_url的错误，但是从代码中
![image](https://user-images.githubusercontent.com/37820283/114122790-96edbd00-9923-11eb-823f-b6b9efcb72ec.png)可以看到这里是有默认配置的，

**Comment by Junxieshiguan** [comment]
![image](https://user-images.githubusercontent.com/37820283/114123745-8a6a6400-9925-11eb-94cf-d0ce9e645616.png)
这是network

**Comment by Junxieshiguan** [comment]
已解决，原因是jumpserver前后端版本不一致导致的。
