### ISSUE TITLE
[Feature] 升级备份数据库的时候自动备份的数据库名上加上jumpserver的版本

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#5933]
**请描述您的需求或者改进建议.**
升级备份数据库的时候自动备份的数据库名上加上jumpserver的版本，因为时间长了就不知道是从哪个jumpserver版本备份的数据库，时间长后恢复数据库就不能确认是否和最新版本数据库结构兼容

**Comment by ibuler** [comment]
收到

**Comment by sicode** [comment]
是啊，一旦装好没什么问题都不会频繁更新，时间久了动不动就不兼容老版本数据，有点难受

**Comment by jym503558564** [comment]
v2.10版本以后已支持，请更新至最新版本进行测试。
