### ISSUE TITLE
JMS英文界面还有很多中文

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#5934]
**请描述您的需求或者改进建议.**
1、JMS英文界面还有很多中文，建议全部完善成中文
2、左边菜单里面单词首字母建议大写
![image](https://user-images.githubusercontent.com/35896106/114332983-dad9ff80-9b79-11eb-9c93-8c6e39f29cf5.png)
![image](https://user-images.githubusercontent.com/35896106/114333016-ecbba280-9b79-11eb-9221-63ae650f71d1.png)

**Comment by jym503558564** [comment]
正在优化

**Comment by jym503558564** [comment]
@v2.9.0版本已优化，请持续关注我们版本发布情况。
