### ISSUE TITLE
录像回放问题

### ISSUE THREAD

**Issue by YiZhu-2019** [jumpserver/jumpserver#5943]
尊敬的开发者：您好!感谢你们的付出。在录像回放时有如下问题，录像时间特别长，但其中操作的时间很短，我在回放录像时需要检索很长时间，尽管有快进功能，但还是很耗时间，请问能不能过滤掉没有操作的录像时间。

**Comment by orangemio** [comment]
Windows还是Linux录像？

**Comment by jym503558564** [comment]
linux是可以快进倍数
