### ISSUE TITLE
是否能在2.7.1的基础上修复rz问题？

### ISSUE THREAD

**Issue by wenjun8888** [jumpserver/jumpserver#5955]
您好：

非常抱歉打扰了。
看到2.8.3修复了rz功能之后，我连夜升级了2.8.3，确认rz问题修复。
但是2.8版本之后显示目录树的问题依旧没有解决，目前十分混乱，我尝试过将权限定义在不同的目录下，区别精度，结果还是不行，并且每次使用g，目录结构都是不一样的，我也不懂原因了。
目前已知2.7.1版本目录层级是好的，不知道是否可以在2.7.1的基础上修复rz的问题，后续我将用这个版本作为稳定版本使用。
非常抱歉给你们带来麻烦了。
非常感谢~！

**Comment by ibuler** [comment]
可以的，今天为你发布 2.7.2

**Comment by LeeEirc** [comment]
@wenjun8888 使用  `g` 展示目录结构不一样，指的是 ssh 登录展示的节点排序吗？

**Comment by wenjun8888** [comment]
> 可以的，今天为你发布 2.7.2

非常感谢~真的非常感谢~

**Comment by wenjun8888** [comment]
> @wenjun8888 使用 `g` 展示目录结构不一样，指的是 ssh 登录展示的节点排序吗？

是的，而且每次再打一次g，有些目录结构又会不一样，始终有一些会不在目录结构中。

**Comment by LeeEirc** [comment]
@wenjun8888 参考下这个 #5185，节点排序做了一个优化，同一父节点，子节点按名字排序。

**Comment by wenjun8888** [comment]
> @wenjun8888 参考下这个 #5185，节点排序做了一个优化，同一父节点，子节点按名字排序。

您好，我不是这个意思，我贴图您看：

正常的2.7.1版本的是这样的：

![image](https://user-images.githubusercontent.com/23557780/114649720-a306bf80-9d13-11eb-93f1-e6b95f4b9fdc.png)

不正常的2.8.+版本是这样的：

![image](https://user-images.githubusercontent.com/23557780/114649824-ca5d8c80-9d13-11eb-985f-e8dabcba61b9.png)

有很多子节点不是根据我资产的节点编排的，会游离于应该的根(UAT)节点之外，并且每次按一下g，这些子节点还会变化，我尝试过在各个子节点来控制权限，但是无一例外都失败了。。。
这个问题2.7.x的版本是好的。

**Comment by ibuler** [comment]
**已发布** https://github.com/jumpserver/jumpserver/releases/tag/v2.7.2

**Comment by xuxinwen** [comment]
加我 qq 远程处理下节点问题  784642966

**Comment by wenjun8888** [comment]
> **已发布** https://github.com/jumpserver/jumpserver/releases/tag/v2.7.2

非常感谢~

**Comment by wenjun8888** [comment]
> 加我 qq 远程处理下节点问题 784642966

好的 ，稍后我添加你~
