### ISSUE TITLE
[Bug] 资产改名后用新的资产名搜索不到之前的会话和命令记录

### ISSUE THREAD

**Issue by itest6** [jumpserver/jumpserver#5959]
**JumpServer 版本(v1.5.9以下不再支持)** v2.8.2

**浏览器版本** Google Chrome 89

**Bug 描述**  资产改名后用新的资产名搜索不到之前的会话和命令记录

**Bug 重现步骤(有截图更好)**
1.  资产管理界面更新资产的主机名
2. 使用新的资产名在会话管理或命令记录界面搜索
3.

**Comment by jym503558564** [comment]
@itest6 确实存在该问题，之后版本修复。
