### ISSUE TITLE
Mysql login prompt characters did not match: unshare: unshare[Bug] 

### ISSUE THREAD

**Issue by TencentJeyan** [jumpserver/jumpserver#5966]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.3
**浏览器版本**
chrome  89.0.4389.128

**Bug 描述**
web 终端可以连接
mysql 连接时报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/69785820/114805977-87b0b880-9dd6-11eb-9407-44dde3a5803b.png)

**Comment by LeeEirc** [comment]
@TencentJeyan 使用什么方式部署的？

**Comment by TencentJeyan** [comment]
> @TencentJeyan 使用什么方式部署的？

把所有依赖的内容 build 在一个镜像里部署的

**Comment by TencentJeyan** [comment]
> @TencentJeyan 使用什么方式部署的？

@LeeEirc 把所有服务和依赖全部 build 进一个镜像部署的

**Comment by TencentJeyan** [comment]
@LeeEirc 我们会在腾讯云开源应用上架 JumpServer 开源版，届时，你们团队可以体验一下。看看有没有地方可以合作一下。

**Comment by LeeEirc** [comment]
如果是自己 build 镜像，请按照 koko 的 [Dockerfile](https://github.com/jumpserver/koko/blob/master/Dockerfile)；部署相关的参考 [installer](https://github.com/jumpserver/installer);
