### ISSUE TITLE
[Bug] 连接资产出现"发生错误：ssh: handshake failed: EOF"（已查出原因但是不知道如何修复）

### ISSUE THREAD

**Issue by tttlkkkl** [jumpserver/jumpserver#5975]
**JumpServer 版本(v1.5.9以下不再支持)**
2.9.0

**浏览器版本**

**Bug 描述**
添加系统用户并选择自动推送，账号能在目标资源创建成功但是无法使用。
经过排查是在目标资源机器中创建的用户有效期是过时的。请确认并修复此问题。

**Bug 重现步骤(有截图更好)**
1.  添加系统用户 testuser2 如下：
![image](https://user-images.githubusercontent.com/8353103/115053585-dca51980-9f11-11eb-8ba5-3a2d39ef3533.png)
2.  用 testuser2 对资产进行授权 如下:
![image](https://user-images.githubusercontent.com/8353103/115054030-59d08e80-9f12-11eb-872d-69bf6cef9deb.png)
此时资产机器打印如下系统消息：
```bash
Apr 17 00:17:38 iZwz9d2nq2e6oos6rr7sdtZ sshd[1242837]: rexec line 49: Deprecated option RSAAuthentication
Apr 17 00:17:38 iZwz9d2nq2e6oos6rr7sdtZ systemd[1]: Started Session 45 of user root.
Apr 17 00:17:38 iZwz9d2nq2e6oos6rr7sdtZ systemd-logind[854]: New session 45 of user root.
Apr 17 00:17:39 iZwz9d2nq2e6oos6rr7sdtZ ansible-user[1242947]: Invoked with comment=testuser2 ssh_key_bits=0 update_password=always non_unique=False force=False ssh_key_type=rsa create_home=True password_lock=None ssh_key_passphrase=NOT_LOGGING_PARAMETER uid=None home=/home/testuser2 append=False skeleton=None ssh_key_comment=ansible-generated on iZwz9d2nq2e6oos6rr7sdtZ group=None system=False state=present role=None hidden=None local=None authorization=None profile=None shell=/bin/bash expires=99999.0 ssh_key_file=None groups=[''] move_home=False password=NOT_LOGGING_PARAMETER name=testuser2 seuser=None remove=False login_class=None generate_ssh_key=None
Apr 17 00:17:40 iZwz9d2nq2e6oos6rr7sdtZ ansible-group[1243134]: Invoked with non_unique=False name=testuser2 system=False state=present gid=None local=False
Apr 17 00:17:40 iZwz9d2nq2e6oos6rr7sdtZ ansible-user[1243271]: Invoked with comment=None ssh_key_bits=0 update_password=always non_unique=False force=False ssh_key_type=rsa create_home=True password_lock=None ssh_key_passphrase=NOT_LOGGING_PARAMETER uid=None home=None append=False skeleton=None ssh_key_comment=ansible-generated on iZwz9d2nq2e6oos6rr7sdtZ group=None system=False state=present role=None hidden=None local=None authorization=None profile=None shell=/bin/bash expires=None ssh_key_file=None groups=None move_home=False password=NOT_LOGGING_PARAMETER name=testuser2 seuser=None remove=False login_class=None generate_ssh_key=None
Apr 17 00:17:41 iZwz9d2nq2e6oos6rr7sdtZ ansible-lineinfile[1243376]: Invoked with directory_mode=None force=None remote_src=None backrefs=False owner=None path=/etc/sudoers insertafter=None follow=False line=testuser2 ALL=(ALL) NOPASSWD: /bin/whoami group=None insertbefore=None unsafe_writes=None create=False setype=None content=NOT_LOGGING_PARAMETER serole=None state=present dest=/etc/sudoers selevel=None regexp=^testuser2 ALL= validate=visudo -cf %s src=None seuser=None delimiter=None mode=None firstmatch=False attributes=None backup=False
```
3. 在资产端查看 testuser2 的信息如下：
![image](https://user-images.githubusercontent.com/8353103/115054341-b633ae00-9f12-11eb-8473-060aaeca778e.png)
请注意截图中的 `帐户过期时间                                            ：1月 02, 1970`本bug正是因为此属性的值没有正确设置。
4. 在资产端尝试用 testuser2 进行登录：
![image](https://user-images.githubusercontent.com/8353103/115054789-36f2aa00-9f13-11eb-80da-b1b7c818c9b0.png)
如图最后提示账号过期:`Your account has expired; please contact your system administrator`
5. 此时在jumpserver尝试登录会报错: `发生错误：ssh: handshake failed: EOF`,如下图：
![image](https://user-images.githubusercontent.com/8353103/115055042-8cc75200-9f13-11eb-856f-576a4d504945.png)

6. 手动修改 testuser2 的账户过期时间再尝试登录可以成功，如下图：
![image](https://user-images.githubusercontent.com/8353103/115055400-f34c7000-9f13-11eb-8a97-fc77acf9384a.png)
![image](https://user-images.githubusercontent.com/8353103/115055431-ff383200-9f13-11eb-9227-d2c863afe796.png)

**Comment by tttlkkkl** [comment]
根本原因是自动推送的系统用户在资产端的账号有效期没有被正确设置，设置成 1970 年了。导致账号一创建就过期。辛苦开发团队尽快修复此问题。

**Comment by zlylong** [comment]
关闭自动推送，然后运行`chage -E '2099-12-30' XXXX`

**Comment by wojiushixiaobai** [comment]
已验证存在此问题。

**Comment by zlylong** [comment]
> 已验证存在此问题。

另外还有一个问题。管理用户若使用`用户名与用户相同`，多用户就显示`用户名或密码错误`

**Comment by jym503558564** [comment]
@tttlkkkl 马上发布v2.9.1 版本，解决该问题。

**Comment by jym503558564** [comment]
@tttlkkkl v2.9.1 已发版，可升级至该版本。

**Comment by tttlkkkl** [comment]
给力！
