### ISSUE TITLE
[Question] ssh xxx@xxx.jumpserver 

### ISSUE THREAD

**Issue by ZhangDewei** [jumpserver/jumpserver#5977]
**请描述您的问题.**
如题 当我 ssh 到 jumpserver的时候 输入密码后 报了 permission denined 请问 是什么问题

**Comment by jym503558564** [comment]
@ZhangDewei 
 - 该用户使用Web 登录JumpServer 能否登录成功。  
 - 用户密码是否正确？如果密码正确，是否过期？
 - 如果用户账号密码正确，也没有过期，是有效的用户，查看系统用设置-终端设置，是否又勾选密码认证。
 - 
![image](https://user-images.githubusercontent.com/40739051/115176533-e12f2500-a0ff-11eb-8d5e-d1bcca161ccc.png)

**Comment by Xuejicha0** [comment]
同样的问题，使用密码认证，重置秘钥后用秘钥登录，都提示 permission denined

**Comment by jym503558564** [comment]
密钥登录是开启 密钥认证  @Xuejicha0

**Comment by Xuejicha0** [comment]
![2](https://user-images.githubusercontent.com/70891502/115191046-7986d300-a11b-11eb-8838-e5c17d337de4.jpg)
![1](https://user-images.githubusercontent.com/70891502/115191054-7d1a5a00-a11b-11eb-8eb7-63ca08c7c753.jpg)

还是不行的

**Comment by jym503558564** [comment]
@Xuejicha0 哪个版本？

**Comment by Xuejicha0** [comment]
2.8.0  ，昨天刚升级到2.9.0  一样的,都不行

**Comment by jym503558564** [comment]
@Xuejicha0 通过Web 使用密码登录，该用户能登录成功吗？

**Comment by Xuejicha0** [comment]
通过web 是可以的

**Comment by jym503558564** [comment]
@Xuejicha0 无法复现。。
