### ISSUE TITLE
[Question] 资产信息中“管理用户”必填选项

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#5979]
**请描述您的问题.**
针对资产信息中的“管理用户”，该字段是否可以设置成非必填选项。
该参数只针对Linux有意义，或者装了ssh服务的windows；如果并不需要推送用户至服务器或者获取服务器硬件信息的情况下。
这个设置就是没用的，所有建议是否可以留空，非必填

**Comment by jym503558564** [comment]
@luweijun1992 大部分用户还是需要的，企业用户等也有一些功能也是需要此。若改为非必填，真的要使用时，有时候忘记设置，真的要使用时，就会出现问题。
