### ISSUE TITLE
你好，我也碰到这个问题了，客户端都安装了，还是提示这个

### ISSUE THREAD

**Issue by madalion** [jumpserver/jumpserver#5983]
你好，我也碰到这个问题了，客户端都安装了，还是提示这个
koko版本：  v2.1.2

_Originally posted by @madalion in https://github.com/jumpserver/jumpserver/issues/5845#issuecomment-822898609_

**Comment by jym503558564** [comment]
@madalion 各组件保持版本保持一致。
