### ISSUE TITLE
关于django多对多关系的维护

### ISSUE THREAD

**Issue by YoLoveLife** [jumpserver/jumpserver#599]
提一个项目外的问题希望能得到解答：
       目前我在参照jumpserver的源码写自己的cmdb系统，遇到了多对多关系的维护问题。页面上的多对多关系数据可以通过rest-framework提供的API来进行获取，但是在页面多对多关系post请求上遇到了很大的问题。通过form-data的方式，在rest-framework中无法获取到完整的多选信息，但是如果采用json+ajax请求的方式的话，报头无法包含csrf-token信息而导致请求400。
       请问对于提交post请求如何让后端接受到完整的前端多选信息。
ps: 多选关系指的是我需要提交一个select列表中的多个option到后端，然后后端维护多对多的数据库关系。

**Comment by YoLoveLife** [comment]
以下是部分代码
class Host(models.Model):
    id=models.AutoField(primary_key=True) #全局ID
    group = models.ForeignKey(Group,default=1)#所属应用
    storages = models.ManyToManyField(Storage)

class Storage(models.Model):
    id=models.AutoField(primary_key=True)#全局ID
    disk_size=models.CharField(max_length=100,default="0G")
    disk_path=models.CharField(max_length=100,default="//10.100.100.246/storage")

class HostSerializer(serializers.ModelSerializer):
    group=GroupSerializer()
    class Meta:
        model=Host
        fields = ('id','group','systemtype','manage_ip','service_ip','outer_ip','server_position','hostname',
                  'normal_user','sshpasswd','sshport','coreness','memory','root_disk','info'
                  ,'storages','group'
                  )

**Comment by hellorocky** [comment]
提供一个思路, 不一定是最好的解决办法,  关闭csrf验证

```
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

class IsExist(APIView):
    """判断机器是否存在于JMS"""
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsSuperUser,)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(IsExistApi, self).dispatch(request, *args, **kwargs)

    def post(self, request, format=None):
        ipaddrs = json.loads(request.data.get("ipaddrs"))
        result = [{ip: Asset.objects.filter(ip=ip).exists()} for ip in ipaddrs]
        return JsonResponse(result, safe=False, json_dumps_params={"ensure_ascii": False})
```

**Comment by YoLoveLife** [comment]
@hellorocky 我又去浏览了一下jumpserver对ManyToMany类型的处理，针对一个包含多数据类型的models，jumpserver是做了多个Srializer配合多个API来处理update或者是add的情况。是否我不该使用太过复杂的前端逻辑，直接将数据拆分然后做不同的逻辑来提交会清晰明了一些。

**Comment by hellorocky** [comment]
我用serializer也不太熟悉, 所以开发接口我都是直接操作model的

**Comment by hellorocky** [comment]
https://docs.djangoproject.com/en/1.11/topics/db/examples/many_to_many/  参考

**Comment by YoLoveLife** [comment]
通过models操作ManyToMany其实并不是问题。如何通过api接口在传递过程中还能维持这种关系并且被前后端识别、操作数据是我遇到的问题。我决定先试一试关闭csrf，用ajax+json来传递数据试试。谢谢。 @hellorocky

**Comment by ibuler** [comment]
@YoLoveLife Jumpserver针对一个model可能有多个serializer，是由于需求决定的，添加object需要的字段可能和更新object的字段不同，从逻辑上应该使用不同的serializer

**Comment by YoLoveLife** [comment]
那是否就意味着同一个models信息的新增或者更新，根据逻辑上划分的serializer就需要多个不同的页面(每个页面都包含若干个需要维护的数据字段)去进行用户的数据交互，因为我没有实际去部署jumpserver，就看源码前后端来重构了自己原本的项目，jumpserver是这么处理的吗？ @ibuler
