### ISSUE TITLE
[Bug] /assets/assets update接口bug

### ISSUE THREAD

**Issue by miaoyb** [jumpserver/jumpserver#5992]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.9.0
**浏览器版本**

**Bug 描述**
update 资产只传递必传字段。如果不传递protocols，资产的协议组就会变成下图这样。
![image](https://user-images.githubusercontent.com/7277129/115352215-b02b1f00-a1e9-11eb-9a70-d3fef174f199.png)
数据库中相应字段为
![image](https://user-images.githubusercontent.com/7277129/115352262-c042fe80-a1e9-11eb-884a-7453f0f55799.png)
这样，web终端就会提示资产无管理用户，无法登陆。
**解决方案**
update接口protocols字段传递为[]即可
data=json.dumps({
                "protocols": [],
                "nodes": [
                    "c339f70f-25b6-4b8c-9c09-9c56feaf48e9"
                ],
                "hostname": "MTest2",
                "ip": "172.17.42.150",
                "platform": "Windows"
            })

**Comment by miaoyb** [comment]
这个update接口nodes也无法更新。

**Comment by jym503558564** [comment]
@miaoyb 将在未来版本进行修复。

**Comment by ibuler** [comment]
v2.9.3 已修复
