### ISSUE TITLE
[Question] 某些页面具体项目打开报错

### ISSUE THREAD

**Issue by tim1670** [jumpserver/jumpserver#5994]
**请描述您的问题.**
我最近将jumpserver从2.5版本升级到了2.71版本，使用官方的jumpserver-installer，发现升级后部分页面点击具体项目有时会报错，例如资产管理的具体项目和网域列表具体项目，奇怪的是返回上级页面后再重新点击就正常了。但账号注销后登陆又出现同样情况.有如下报错：

"undefined"不是一个有效UUID"
请求错误，请检查填写内容，

请问可能是什么原因？
![1](https://user-images.githubusercontent.com/42209293/115354134-e10c5380-a1eb-11eb-96e2-8d457a974546.JPG)
![2](https://user-images.githubusercontent.com/42209293/115354148-e49fda80-a1eb-11eb-8fed-858da970e39e.JPG)
![3](https://user-images.githubusercontent.com/42209293/115354162-e7023480-a1eb-11eb-9e4a-f00f882334c2.JPG)

**Comment by jym503558564** [comment]
部署请按照我们官方文档来操作：https://docs.jumpserver.org/zh/master/install/setup_by_fast/
