### ISSUE TITLE
[Feature] 连接 K8s 资产的命令提示符支持显示资源名称和集群名称

### ISSUE THREAD

**Issue by ghost** [jumpserver/jumpserver#5995]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/46479118/115354174-e9fd2500-a1eb-11eb-95f6-56df793bfe7c.png)
这个k8s应用，不同的应用，命令行前面没有提示符么，这样进入不同的k8s环境显示都一样不易区分啊

**Comment by laurelgithub** [comment]
因为我是shell命令行操作的，可以在#位置加入 应用的名称么，类似这样的 k8s-m-1#   wuhu.master.1#, 这样在不同的环境就防止误操作了，我们这边是jumpserver的重度用户，另外k8s环境比较多，但是现在这个应用功能还没使用，希望可以在下个版本加入一个改进

**Comment by ibuler** [comment]
可以考虑 @LeeEirc

**Comment by BaiJiangJie** [comment]
计划在 v3 版本中支持

**Comment by BaiJiangJie** [comment]
v3.3 版本已支持；

[perf: 优化连接 Kubernetes 资产时，命令行前缀显示资源名称和集群名称](https://github.com/jumpserver/jumpserver/releases/tag/v3.3.0)
