### ISSUE TITLE
[Feature] 公有云资产按照公网IP进行检索

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#5996]
**请描述您的需求或者改进建议.**
[同步公有云资产后，在jumpserver中可以显示公网IP，但是不能按照公网IP进行检索，希望可以添加按照公网IP检索的功能。
<img width="1064" alt="WechatIMG154" src="https://user-images.githubusercontent.com/57253444/115357625-69d8be80-a1ef-11eb-82bb-56df027d9a38.png">

**Comment by BaiJiangJie** [comment]
v3 版本中已不支持公网IP的配置。
