### ISSUE TITLE
[Feature] 公有云同步资源、机器名显示不一致

### ISSUE THREAD

**Issue by Ankers-liu** [jumpserver/jumpserver#5997]
**请描述您的需求或者改进建议.**
同步公有云资源的时候，
<img width="399" alt="WechatIMG156" src="https://user-images.githubusercontent.com/57253444/115358229-056a2f00-a1f0-11eb-873e-0ec25c9bdcde.png">
Jumpserver机器名那一列会自动加上IP后两位，而且没有办法去除，希望可以把这两位IP去掉，只显示机器名称。

**Comment by jym503558564** [comment]
@Ankers-liu 创建同步实例任务时，【主机名策略】可选【实例名称】
![image](https://user-images.githubusercontent.com/40739051/115507779-22b20280-a2af-11eb-8783-d952aa6c6f5b.png)
