### ISSUE TITLE
资产列表右击节点名称的时候，菜单显示问题

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#6004]
![图片](https://user-images.githubusercontent.com/63391681/115482372-20d14a80-a281-11eb-8fd9-23131a6b48ef.png)

在资产列表页面，选择节点右击的时候，菜单无法全部显示。

**Comment by jym503558564** [comment]
@Allenzhang-92 之前有个版本确实存在该问题，可更新至最新版本。

**Comment by jym503558564** [comment]
@Allenzhang-92 在2.7版本，这个问题就已经修复了，请更新。
