### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#6007]
**请描述您的问题.**
版本为v2.9.2+xpack
在web终端内的左下角，显示的版本号与配置的版本号不一致。
配置的为 jumpserver-release-v2.9.2-119
![image](https://user-images.githubusercontent.com/22720300/115489054-1a959b00-a28e-11eb-8050-664befdb79ee.png)

**Comment by wojiushixiaobai** [comment]
只看 vx.x.x
-后面的数字是编译时防止名字冲突，随机生成的。
