### ISSUE TITLE
[Question] 2.9.2企业版本，mysql命令过滤

### ISSUE THREAD

**Issue by LeiyuanBlog** [jumpserver/jumpserver#6008]
**请描述您的问题.**
创建了命令过滤器用来过滤drop、delete命令，使用系统用户连接数据库之后命令仍可以执行。
企业版2.9.2

**Comment by luweijun1992** [comment]
> **请描述您的问题.**
> 创建了命令过滤器用来过滤drop、delete命令，使用系统用户连接数据库之后命令仍可以执行。
> 企业版2.9.2

系统用户是否关联上过滤规则

**Comment by LeiyuanBlog** [comment]
> > **请描述您的问题.**
> > 创建了命令过滤器用来过滤drop、delete命令，使用系统用户连接数据库之后命令仍可以执行。
> > 企业版2.9.2
> 
> 系统用户是否关联上过滤规则

创建、更新系统用户时没有添加过滤规则的选项。我在规则-》用户中手动添加了mysql用户但是规则不生效

**Comment by LeiyuanBlog** [comment]
<img width="1209" alt="截屏2021-04-21 下午6 06 21" src="https://user-images.githubusercontent.com/44362360/115536349-4a639380-a2cc-11eb-8b92-8c74f7f2ea82.png">
<img width="1209" alt="截屏2021-04-21 下午6 06 54" src="https://user-images.githubusercontent.com/44362360/115536430-5cddcd00-a2cc-11eb-9ea7-41f64170db33.png">
如上图

**Comment by LeiyuanBlog** [comment]
<img width="1209" alt="截屏2021-04-21 下午6 07 34" src="https://user-images.githubusercontent.com/44362360/115536513-74b55100-a2cc-11eb-9391-b2b91614da57.png">

**Comment by jym503558564** [comment]
@LeiyuanBlog 目前还不支持数据库协议的命令规则限制

**Comment by LeiyuanBlog** [comment]
> @LeiyuanBlog 目前还不支持数据库协议的命令规则限制

2.7的版本是可以支持的吧，2.7中mysql系统用户可以选择添加过滤规则

**Comment by enan820** [comment]
> > @LeiyuanBlog 目前还不支持数据库协议的命令规则限制
> 
> 
> 
> 2.7的版本是可以支持的吧，2.7中mysql系统用户可以选择添加过滤规则

SQL客户端是命令行方式是可以过滤，WebUI方式无法过滤

**Comment by jym503558564** [comment]
@LeiyuanBlog web UI 还是 Cli 模式连接的

**Comment by jym503558564** [comment]
@LeiyuanBlog 
 - Cli模式连接时，是支持的。如果是Web UI方式，占不支持。
 - 系统用户mysql协议，之后版本会优化一下，把命令过滤规则重新添加进来。

**Comment by LeiyuanBlog** [comment]
我是否可以自行选择使用cli还是web ui？

**Comment by jym503558564** [comment]
Luna界面-设置：SQL 客户端选项选择Cli
![image](https://user-images.githubusercontent.com/40739051/115647116-d7066400-a355-11eb-955b-9ac020e03b90.png)

**Comment by LeiyuanBlog** [comment]
> @LeiyuanBlog Luna界面-设置：SQL 客户端选项选择Cli
> ![image](https://user-images.githubusercontent.com/40739051/115647116-d7066400-a355-11eb-955b-9ac020e03b90.png)

收到。感谢，是用户自行选择是吧，管理员这边没办法全局控制对吗？

**Comment by jym503558564** [comment]
@LeiyuanBlog 是的。Cli目前还只支持mysql协议数据库，oracle、postgresql、mairaDB，还不支持。感谢您的持续关注与使用，如还有其他问题，可再提Issues.

**Comment by luweijun1992** [comment]
> @LeiyuanBlog Luna界面-设置：SQL 客户端选项选择Cli
> ![image](https://user-images.githubusercontent.com/40739051/115647116-d7066400-a355-11eb-955b-9ac020e03b90.png)

设置 中 SQL客户端 这个选项是否企业版才有，开源版没有看到此选项。

**Comment by jym503558564** [comment]
@luweijun1992 是的，企业版有此选项。开源版本没有
