### ISSUE TITLE
[Feature] 全局设置源IP登录限制

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#6009]
**请描述您的需求或者改进建议.**
现在acl源IP登录限制是针对单个用户，如果用户多需要一个一个单独添加，设置麻烦；
是否增加个全局设置，针对所有人生效
当全局与用户设置存在存在，以用户设置为准。

**Comment by luweijun1992** [comment]
@ibuler 请问近期会考虑加上此功能吗？谢谢

**Comment by jym503558564** [comment]
已记录，并反馈给开发人员。感谢持续关注JumpServer
