### ISSUE TITLE
coco能否支持LDAP登录

### ISSUE THREAD

**Issue by linclin** [jumpserver/jumpserver#601]
１．jumpserver支持ldap登录，登录之后会将用户信息写入user表，但是并未将该用户ldap的密码也同步写入，导致连接coco不知道密码．
２．如若ldap用户未从jumpserver登录，则用户数据表没有此ldap用户数据，coco连接还是无法登录
建议coco项目支持ldap用户＋密码登录验证，感谢项目组开源了jumpserver这么好的产品

**Comment by ibuler** [comment]
如果用户登陆过 Jumpserver，是否可以从coco登陆成功？

**Comment by linclin** [comment]
如果用户登陆过 Jumpserver，是否可以从coco登陆成功？不行
用ldap帐号密码可以登录jumpserver，登录成功之后用同样的帐号密码登录coco失败．

**Comment by ibuler** [comment]
ok, 我考虑一下怎么修复

**Comment by drmfly** [comment]
这个问题我也遇到、规避用法就是发个重置密码链接修改 
大多用的public key登录 这个时候 其实coco 登录密码就不必要了

**Comment by ibuler** [comment]
same with #676

**Comment by ibuler** [comment]
@linclin 这个bug我尝试修复了一下，你看看还有没有问题

**Comment by ibuler** [comment]
fixed
