### ISSUE TITLE
为啥升级检测获取到的最新版版本号不正确了

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#6011]
从2.6.1一路 ./jmsctl.sh check_update升级上来的
然后今天发现这样了

```
[root@iZuf6dj5ddkv7mdb9989qiZ jumpserver-installer-v2.6.1]# ./jmsctl.sh check_update
最新版本是: v2.7.3
当前版本是: v2.8.3

你确定要升级到 v2.7.3 版本吗? (y/n)  (默认为n): 
```

**Comment by luweijun1992** [comment]
> 从2.6.1一路 ./jmsctl.sh check_update升级上来的
> 然后今天发现这样了
> 
> ```
> [root@iZuf6dj5ddkv7mdb9989qiZ jumpserver-installer-v2.6.1]# ./jmsctl.sh check_update
> 最新版本是: v2.7.3
> 当前版本是: v2.8.3
> 
> 你确定要升级到 v2.7.3 版本吗? (y/n)  (默认为n): 
> ```

github上最新的是v2.7.3确实没错
![image](https://user-images.githubusercontent.com/58923704/115640931-ac62de00-a34a-11eb-991c-a76e3a90086f.png)

**Comment by luweijun1992** [comment]
> 从2.6.1一路 ./jmsctl.sh check_update升级上来的
> 然后今天发现这样了
> 
> ```
> [root@iZuf6dj5ddkv7mdb9989qiZ jumpserver-installer-v2.6.1]# ./jmsctl.sh check_update
> 最新版本是: v2.7.3
> 当前版本是: v2.8.3
> 
> 你确定要升级到 v2.7.3 版本吗? (y/n)  (默认为n): 
> ```

可以手动指定需要更新的版本。
./jmsctl.sh upgrade v2.9.2

**Comment by luweijun1992** [comment]
github上已经将最新版本改成 v2.9.2

**Comment by wojiushixiaobai** [comment]
已修复
