### ISSUE TITLE
[Feature] 用户&授权规则 快速启用禁用

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#6012]
**请描述您的需求或者改进建议.**
当前版本v2.9.2

针对用户&授权规则，需要先点击进入该用户或者该授权规则后，再将激活状态选择禁用；操作上不够便捷
![image](https://user-images.githubusercontent.com/58923704/115642349-59d6f100-a34d-11eb-92c7-386756fc3728.png)

建议可以直接点击“有效”栏目对该用户&授权规则进行快速启用禁用操作，操作更加快捷方便
![image](https://user-images.githubusercontent.com/58923704/115642002-c2719e00-a34c-11eb-9503-eb0617f8d44c.png)

**Comment by luweijun1992** [comment]
@ibuler 请问近期会考虑加上此功能吗？谢谢

**Comment by jym503558564** [comment]
目前未支持，请持续关注我们版本发布情况。
