### ISSUE TITLE
[Question] 版本部署问题

### ISSUE THREAD

**Issue by lilianxiang** [jumpserver/jumpserver#6013]
**请描述您的问题.**
1）jumpserver 2.7以上版本可以使用2.5版本的手动部署说明文档部署吗？
2）jumpserver 2.7版本更新  ，guacamole 使用1.3.0版本，请问2.5版本可以使用guacamole 1.3.0部署吗？
3）最新版本使用手动部署，需要注意什么？

**Comment by jym503558564** [comment]
@lilianxiang 各组件版本最好保持一致，否则容易出问题。

**Comment by lilianxiang** [comment]
所有组件不用docker ， 是不是和以前的手动部署文档一致

**Comment by lilianxiang** [comment]
我不想用最新版本，有没有推荐生产使用的稳定版本

**Comment by jym503558564** [comment]
参考升级文档
https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/
