### ISSUE TITLE
[Question] Dashboard 在线用户&在线会话

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#6014]
**请描述您的问题.**
v2.9.2
 只登录（koko&web terminal）并没有连接资产，Dashboard 在线用户并没有计数
![image](https://user-images.githubusercontent.com/58923704/115651085-14babb00-a35d-11eb-8019-b7557a514730.png)
我登录了（koko&web terminal），但是我没有连接资产，那是不是在线用户应该+1、在线会话不计数；
当我连了1个资产、对应的在线会话+1
Dashboard分2个计数 在线用户&在线会话，那是不是应该存在差异

**Comment by jym503558564** [comment]
@luweijun1992 
- 在线用户数，连接资产、应用时，才算是在线用户数
- 在线用户数和线会话数不同，一个用户可以连接很多资产和很多应用。只记一个在线用户数，但记多个在线会话数。

**Comment by luweijun1992** [comment]
> * 在线用户数，连接资产、应用时，才算是在线用户数

这样的话就明白了这2个具体对应的意思了。了解

**Comment by jym503558564** [comment]
@luweijun1992 好的，该Issues先关闭了，如还有其他问题可再次提Issues
