### ISSUE TITLE
自定义系统用户推送(针对那些推送失败的机器)

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#6015]
在推送系统用户的界面，是否可以增加一个功能，用来手动推送系统用户到指定的机器，也就是说，我假如有些机器自动推送失败了，但是我还得一个一个的找到每一个机器，都再手动推送一遍，如果加一个复选框，我把没推送成功的机器勾选，然后再推送，这样就可以一次推送这些失败的机器。

**Comment by jym503558564** [comment]
@Allenzhang-92 自定义选择资产进行推送，我们将在未来版本修复该问题。

**Comment by jym503558564** [comment]
https://github.com/jumpserver/trello/issues/989 已在计划中
