### ISSUE TITLE
指执行命令，匹配不到主机

### ISSUE THREAD

**Issue by opser-gavin** [jumpserver/jumpserver#602]
资产管理-》我的资产-》批量执行命令 ，明明选中了好多，但是匹配的主机就那么几个，少了很多，为什么啊？这里日志输出正常。

当我选中那些配置不到的机器批量执行命令的时候，都匹配不到，日志如下：
2017-08-07 10:07:56,769 - ansible_api.py - DEBUG - {'dark': {}, 'contacted': {}}

这是为什么？我做错了什么？求指导，谢谢

**Comment by ibuler** [comment]
查看一些节目左侧的提示，有没有提示选择了多少个主机
