### ISSUE TITLE
[Question] 部署建议

### ISSUE THREAD

**Issue by lilianxiang** [jumpserver/jumpserver#6022]
**请描述您的问题.**
我们打算在生产环境使用，推荐用哪个jumpserver版本？一年内没有更新计划，用于管理windows系统，追求稳定。

**Comment by lilianxiang** [comment]
还有一个问题：请问单个jumpserver core 最大支持多少并发用户？

**Comment by wojiushixiaobai** [comment]
推荐最新，无用户限制
