### ISSUE TITLE
[Question] JMS特殊字符限制咨询

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#6027]
**请描述您的问题.**
---
针对JMS上一些名称的格式要求、字符的要求，是否有明确的限制说明
比如一些特殊字符 - _ { } ( ) [ ] , . / " ' 空格
是否可以在：资产、管理用户、系统用户、授权规则等其它选项的“名称”中使用。
请告知下哪些允许使用，哪些是不被允许使用的。

**Comment by luweijun1992** [comment]
还有冒号；比如下面这种名称
SystemUser::root
SystemUser::Administrator

**Comment by jym503558564** [comment]
如有特殊字符限制，创建时，会提示。

**Comment by luweijun1992** [comment]
> 如有特殊字符限制，创建时，会提示。

现在JMS有对一个标准的字符使用吗。
比如我现在使用了某特殊字符、至少现在版本是正常支持的，但是到了以后新版本，可能不支持这个特殊字符了，那会不会导致升级失败或者升级后出现异常呢。
所有是不是给出一些建议，哪些可以用，哪些最好不用，形成一个标准化来执行。
