### ISSUE TITLE
[Question] jumpserver怎么设置跳转到实际目录？

### ISSUE THREAD

**Issue by wajika** [jumpserver/jumpserver#6029]
**请描述您的问题.**
我已经配置好了 sftp目录为/ ,可以从服务器目录上看到根目录信息，登陆的账号属于管理员组下。

![image](https://user-images.githubusercontent.com/17058349/115977592-3eb5ec80-a5ac-11eb-9145-4be8e144b911.png)

但是在xshell上做跳转到实际目录时，还是没法跳转
![image](https://user-images.githubusercontent.com/17058349/115977572-1c23d380-a5ac-11eb-89fc-1b5e4f87a1f5.png)

在jumpserver web上操作也是没法跳转到实际目录
![image](https://user-images.githubusercontent.com/17058349/115977634-5c835180-a5ac-11eb-8025-5494d7048b29.png)

**Comment by jym503558564** [comment]
系统用户-设置sftp目录

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/115977835-18914c00-a5ae-11eb-9dd0-231d7d69112e.png)

**Comment by ibuler** [comment]
sftp 根路径 是值得 你服务器上能看到的 顶级路径，比如设置为 /tmp，那么 用户不会看到 /tmp 以外的目录，/tmp 就是 sftp 的根路径

**Comment by wajika** [comment]
> sftp 根路径 是值得 你服务器上能看到的 顶级路径，比如设置为 /tmp，那么 用户不会看到 /tmp 以外的目录，/tmp 就是 sftp 的根路径

谢谢你的回复，我上面已经提到sftp目录我已经设置为 “/” 了

**Comment by wajika** [comment]
没人可以提供建议了吗
