### ISSUE TITLE
[Question]容器jms_celery 一直为 unhealthy 状态

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#6033]
才装好的系统，容器jms_celery 一直为 unhealthy 状态，似乎也没影响什么功能（也可能是我没用到），是否需要或者应该怎么排除这个问题？

[root@localhost jumpserver-installer-v2.8.2]# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                                         NAMES
a6f12574ccc9        jumpserver/nginx:alpine2      "sh -c 'crond -b -d …"   37 minutes ago      Up 37 minutes (healthy)     0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   jms_nginx
31a45b2ba04d        jumpserver/guacamole:v2.8.2   "/init"                  38 minutes ago      Up 38 minutes (healthy)     8080/tcp                                      jms_guacamole
22a1f8542be0        jumpserver/koko:v2.8.2        "./entrypoint.sh"        38 minutes ago      Up 38 minutes (healthy)     0.0.0.0:2222->2222/tcp, 5000/tcp              jms_koko
e355d8ea7c38        jumpserver/lina:v2.8.2        "/docker-entrypoint.…"   38 minutes ago      Up 38 minutes (healthy)     80/tcp                                        jms_lina
d145923372a3        jumpserver/luna:v2.8.2        "/docker-entrypoint.…"   38 minutes ago      Up 38 minutes (healthy)     80/tcp                                        jms_luna
ab526d02c0f0        jumpserver/core:v2.8.2        "./entrypoint.sh sta…"   38 minutes ago      Up 38 minutes (unhealthy)   8070/tcp, 8080/tcp                            jms_celery
6e6ece5ce46f        jumpserver/core:v2.8.2        "./entrypoint.sh sta…"   39 minutes ago      Up 39 minutes (healthy)     8070/tcp, 8080/tcp                            jms_core
429218a2e47c        jumpserver/mysql:5            "docker-entrypoint.s…"   2 weeks ago         Up 3 hours (healthy)        3306/tcp, 33060/tcp                           jms_mysql
8b1c84572bb4        jumpserver/redis:6-alpine     "docker-entrypoint.s…"   2 weeks ago         Up 3 hours (healthy)        6379/tcp                                      jms_redis

**Comment by wojiushixiaobai** [comment]
修改 docker-compose-task.yml 里面的 timeout ，加长
