### ISSUE TITLE
如何启用防火墙

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#6034]
根据安全要求，我需要限制源对堡垒机的使用。
譬如我要限制源为：192.168.1.0/24对8080、8443、2222的访问，我直接在操作系统的firewall里配置似乎不起效，是否可以提供帮助？是否需要iptables -R DOCKER 1 -p tcp -m tcp -s  192.168.1.0/24 -d  192.168.250.5/32 --dport 2222 -j ACCEPT 类似这样的命令？怎样使其永久化配置（重启或似乎都会被清除）

[root@localhost jumpserver-installer-v2.8.2]# iptables -L DOCKER -n --line-number
Chain DOCKER (2 references)
num  target     prot opt source               destination         
1    ACCEPT     tcp  --  0.0.0.0/0            192.168.250.8        tcp dpt:2222
2    ACCEPT     tcp  --  0.0.0.0/0            192.168.250.10       tcp dpt:443
3    ACCEPT     tcp  --  0.0.0.0/0            192.168.250.10       tcp dpt:80

**Comment by Laplacence** [comment]
建议在上联交换机进行ACL限制
