### ISSUE TITLE
[Bug] ssh 连接资产视图全屏显示，VI编辑退出保存的时候，按esc会退出全屏，不能直接在VI界面退出保存。

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#6041]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**
89.0.4389.114 for mac
**Bug 描述**
ssh 连接资产视图全屏显示，VI编辑退出保存的时候，按esc会退出全屏，不能直接在VI界面退出保存。
退出全屏显示和vi编辑退出保存快捷键冲突。
**Bug 重现步骤(有截图更好)**
1.  按以上操作即可重现
2. 
3.

**Comment by jym503558564** [comment]
确实存在该问题
