### ISSUE TITLE
web终端长时间不操作连接会被断开 

### ISSUE THREAD

**Issue by mike0476** [jumpserver/jumpserver#6045]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.2.2 GPLv2.

**浏览器版本**
chrome 89.0.4389.128

**Bug 描述**
web终端长时间不操作连接会被断开 ，设置的连接最大空闲时间不生效

系统设置--安全设置--连接最大空闲时间设置为60分钟

**Bug 重现步骤(有截图更好)**
浏览器一段时间不操作连接会被端口，需要重新刷新浏览器才能重新连接。

**Comment by Allenzhang-92** [comment]
这个问题我也遇到了，谷歌浏览器会这样。

**Comment by huwsun** [comment]
我们碰到的问题挂在远程桌面什么也不干，即便超过最大空闲时间，也不退出，还在显示远程桌面，鼠标移动到窗口，才会触发超时断开。版本是2.9.2
