### ISSUE TITLE
[Bug] JumpServer2.5和JumpServer2.8版本同步公有云资产中英文问题

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#6053]
**JumpServer 版本(v1.5.9以下不再支持)**

JumpServer版本：2.5和2.8
浏览器类型：Chrome
bug描述：
   在企业版公有云同步模块中创建的同步计划，中文同步和英文同步会产生不同的节点，看起来非常乱。建议同步同步时候用到的中英文内容信息

**Comment by jym503558564** [comment]
https://github.com/jumpserver/trello/issues/1015  已记录。
