### ISSUE TITLE
[Feature] 能否增加参数CSRF_TRUSTED_ORIGINS

### ISSUE THREAD

**Issue by jeessy2** [jumpserver/jumpserver#6056]
**请描述您的需求或者改进建议.**
能否增加参数CSRF_TRUSTED_ORIGINS。通过ingress导出https会报`Referer checking failed - https://jumpserver.xxxxxxx.com/core/auth/login/ does not match any trusted origins.`

**Comment by wojiushixiaobai** [comment]
在 ingress 配置 ssl 证书就行了吧，我使用 helm 部署未遇到此问题，能详细说明下嘛
- [ ] [JumpServer-Helm](https://github.com/jumpserver/helm)

**Comment by jeessy2** [comment]
我是直接在机器上原生安装的. 通过ingress转入到内网.
以前没注意到有helm项目, 有helm那更好了, 直接使用helm安装.

**Comment by pytomtoto** [comment]
```
目前jumpserver2.27环境使用django3.2版本

需要在core容器web（还有个celery别找错了）

添加如下配置CSRF_TRUSTED_ORIGINS = ['你的域名']

root@bc8bc3c7f2e2:/opt/jumpserver/apps/jumpserver/settings# cat [base.py](http://base.py/) |grep CSRF
CSRF_TRUSTED_ORIGINS = ['jumpserver.example.com']
```

相关的Issue #8805

现象就是在jumpserver2.27版本里 使用外部代理访问jumpserver 登录提示CSRF错误 需在django配置中添加CSRF_TRUSTED_ORIGINS

**Comment by jeessy2** [comment]
> CSRF_TRUSTED_ORIGINS

我在容器中运行，修改也无效。

**Comment by pytomtoto** [comment]
> > CSRF_TRUSTED_ORIGINS
> 
> 我在容器中运行，修改也无效。

你检查下你版本修改后需不需要重启生效
目前jumpserver2.27 也是容器运行，但是﻿gunicorn 启动django有加重载机制 配置修改后直接生效了

**Comment by jeessy2** [comment]
> > > CSRF_TRUSTED_ORIGINS
> > 
> > 
> > 我在容器中运行，修改也无效。
> 
> 你检查下你版本修改后需不需要重启生效 目前jumpserver2.27 也是容器运行，但是﻿gunicorn 启动django有加重载机制 配置修改后直接生效了 gunicorn --reload
> 
> ```
> root@jumpserver:/opt# docker exec -ti 0056372c3234 bash
> root@0056372c3234:/opt/jumpserver# ps -ef
> UID          PID    PPID  C STIME TTY          TIME CMD
> root           1       0  0 13:43 pts/0    00:00:00 /bin/bash ./entrypoint.sh start web
> root           8       1  0 13:43 pts/0    00:00:10 python jms start web
> root          18       8  0 13:43 pts/0    00:00:06 /usr/local/bin/python /usr/local/bin/daphne jumpserver.asgi:application -b 0.0.0.0 -p 8070
> root          20       8  0 13:43 pts/0    00:00:09 /usr/local/bin/python /usr/local/bin/celery -A ops flower -logging=info --url_prefix=/core/flower --auto_refresh=False --max_tasks=1000 --persistent=True -db=/opt/jumpserver/data/flower.db --state_save_interval=600000
> root          31       8  0 13:43 pts/0    00:00:01 /usr/local/bin/python /usr/local/bin/gunicorn jumpserver.wsgi -b 0.0.0.0:8080 -k gthread --threads 10 -w 4 --max-requests 4096 --access-logformat %(h)s %(t)s %(L)ss "%(r)s" %(s)s %(b)s  --access-logfile - --reload
> root         142      31  4 13:44 pts/0    00:03:46 /usr/local/bin/python /usr/local/bin/gunicorn jumpserver.wsgi -b 0.0.0.0:8080 -k gthread --threads 10 -w 4 --max-requests 4096 --access-logformat %(h)s %(t)s %(L)ss "%(r)s" %(s)s %(b)s  --access-logfile - --reload
> root         143      31  4 13:44 pts/0    00:03:47 /usr/local/bin/python /usr/local/bin/gunicorn jumpserver.wsgi -b 0.0.0.0:8080 -k gthread --threads 10 -w 4 --max-requests 4096 --access-logformat %(h)s %(t)s %(L)ss "%(r)s" %(s)s %(b)s  --access-logfile - --reload
> root         144      31  5 13:44 pts/0    00:04:27 /usr/local/bin/python /usr/local/bin/gunicorn jumpserver.wsgi -b 0.0.0.0:8080 -k gthread --threads 10 -w 4 --max-requests 4096 --access-logformat %(h)s %(t)s %(L)ss "%(r)s" %(s)s %(b)s  --access-logfile - --reload
> root         145      31  5 13:44 pts/0    00:04:14 /usr/local/bin/python /usr/local/bin/gunicorn jumpserver.wsgi -b 0.0.0.0:8080 -k gthread --threads 10 -w 4 --max-requests 4096 --access-logformat %(h)s %(t)s %(L)ss "%(r)s" %(s)s %(b)s  --access-logfile - --reload
> root        3867       0  1 15:02 pts/1    00:00:00 bash
> root        3881    3867  0 15:02 pts/1    00:00:00 ps -ef
> root@0056372c3234:/opt/jumpserver# 
> ```

k8s中的容器运行，改了下次也会不在的。。回滚2.24.2
