### ISSUE TITLE
navicate通过jumpserver 作ssh代理无法访问mysql数据库问题

### ISSUE THREAD

**Issue by YiZhu-2019** [jumpserver/jumpserver#6058]
我的jumpserver 版本是2.9.0  ，通过jumpserver可以正常访问到mysql数据库。如图所示：navicate通过jumpserver 作ssh代理无法访问mysql数据库 图中显示从navicate 到jumpserver是通了的，但jumpserver无法连接到数据库
![1619578444(1)](https://user-images.githubusercontent.com/53223923/116340824-63ab9900-a812-11eb-8cab-dee3086e6db2.jpg)

**Comment by leim** [comment]
jumpserver不支持ssh隧道

**Comment by hi-KK** [comment]
同问+1，也是在排查为什么不能ssh隧道中转，22原生系统ssh可以，2222的jumpserver却不行 @wojiushixiaobai

**Comment by leim** [comment]
当然不能支持隧道了，支持隧道的话，能连接数据库就可以直接通过隧道去连接其他服务器了，堡垒机的意义就失去了啊。

**Comment by cupen** [comment]
> 当然不能支持隧道了，支持隧道的话，能连接数据库就可以直接通过隧道去连接其他服务器了，堡垒机的意义就失去了啊。

这是一项正常需求，堡垒机就算不做，开发运维也会用别的方式去做的。

**Comment by leim** [comment]
> > 当然不能支持隧道了，支持隧道的话，能连接数据库就可以直接通过隧道去连接其他服务器了，堡垒机的意义就失去了啊。
> 
> 这是一项正常需求，就算堡垒机不做，开发运维也会用别的方式去做的。

所以jumpserver提供了magnus组件来连接数据库啊。

使用隧道连接数据库，没办法对用户的操作进行审计，就失去堡垒机的意义了，连接数据库的需求，对于开发运维人员来说，非常正常，解决方法也有很多种，但是安全合规的手段，却不多。
