### ISSUE TITLE
版本0.3.2 master vim，vi等编辑窗口录像回放异常

### ISSUE THREAD

**Issue by apachen** [jumpserver/jumpserver#606]
vim ,vi 等交互式命令编辑窗口 ，录像回放存在异常 卡住不动，交互窗口之后的命令记录回放都存在异常

**Comment by apachen** [comment]
网页版web方式登录的vi操作 无异常，可以正常回放；
ssh客户端形式登录存在此问题；  
是已经的缺陷？

**Comment by apachen** [comment]
和客户端连接工具有关系？

**Comment by xyaxlz** [comment]
遇到了相同的问题，回访录像卡住

**Comment by ibuler** [comment]
same with #501
