### ISSUE TITLE
[Bug] SSH连接终端后,运行cat命令查看txt文本内容，浏览器最大化，最小化切换，显示内容会丢失。

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#6061]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**
89.0.4389.114

**Bug 描述**
1、SSH连接终端后,运行cat命令查看txt文本内容，浏览器最大化，最小化切换，显示内容会丢失。
2、cat命令后显示的位置不对

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/46716344/116373224-b94a6a80-a83f-11eb-94e4-0645eb1c3efb.png)

最大化后，显示的txt文本内容不见了
![image](https://user-images.githubusercontent.com/46716344/116373502-fca4d900-a83f-11eb-81e2-f948c79a9e38.png)

**Comment by jym503558564** [comment]
什么浏览器？

**Comment by uranus829** [comment]
> 我使用chrome浏览器测试，无法复现。
> ![image](https://user-images.githubusercontent.com/40739051/116387244-3203f380-a84d-11eb-9d7e-e3557fd8221e.png)

我这边在mac或者windows都有这个问题，问题100%可以重现，方便 远程看一下吗？

**Comment by jym503558564** [comment]
意思是连接mac系统和windows-ssh资产时，cat信息时会出现这种情况吗？

**Comment by jym503558564** [comment]
@uranus829 qq群或者企业微信群，联系一下我们管理员，有空可以帮忙看看。
