### ISSUE TITLE
[Bug] 英文界面下审计日志还有中文

### ISSUE THREAD

**Issue by xyziven** [jumpserver/jumpserver#6062]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**

**Bug 描述**
Audits---> Login logs: **Authentication backend** 和 **Login City** 列
Audits ---> Operation logs: **Resource Type**列

![image](https://user-images.githubusercontent.com/24548477/116418221-81a6e700-a86e-11eb-9545-f0030ff732d9.png)

![image](https://user-images.githubusercontent.com/24548477/116418372-a8651d80-a86e-11eb-85eb-d62537018db3.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
@xyziven 感谢提醒。

**Comment by jym503558564** [comment]
重复问题
