### ISSUE TITLE
[Question] 创建资产时管理用户如何改为非必填项

### ISSUE THREAD

**Issue by qihang-liu** [jumpserver/jumpserver#6068]
因为用不到管理用户的功能，所以想把创建资产时的管理用户改为非必填项，请问下在哪里修改呢
我自己试了下在apps\assets\models\assets.py里的admin_user字段里添加blank=true和apps\assets\serializers\assets.py里AssetSerializer中extra_kwargs添加一行'admin_user': {"required": False}，但是都没有用，admin_user还是必填
![捕获](https://user-images.githubusercontent.com/81737984/116513052-954c5f00-a8fb-11eb-9b5b-5e0c67e6f434.JPG)
![捕获](https://user-images.githubusercontent.com/81737984/116513102-a85f2f00-a8fb-11eb-92c1-3fc5c68678b2.JPG)

**Comment by wojiushixiaobai** [comment]
前端 lina 也有限制

**Comment by jym503558564** [comment]
已优化。将在未来版本发布，请持续关注我们版本发布情况，及时更新体验。
