### ISSUE TITLE
[Feature] K8s 连接功能优化

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#6069]
**请描述您的需求或者改进建议.**
现在连接 k8s 时 只能连接到集群，不能连接到 pod，需要手动，kuberctl 进入，现在想 Luna 上，点击 k8s 集群时，能获取集群下的 namespace, 展开 namespace 能获取 pod container，点击 container 可以直接进去

**Comment by xmapst** [comment]
可否增加pod container的文件浏览/管理功能, 类似[kubefilebrowser](https://github.com/xmapst/kubefilebrowser)

**Comment by umialpha** [comment]
+1 这个功能很需要。我们目的在于提供一个安全的、可记录的环境进入到容器做debug

**Comment by LeeEirc** [comment]
新版本已经支持连接k8s集群的pod容器.
