### ISSUE TITLE
[Bug] 命令行登录堡垒机后可以永久使用堡垒机（会话不会失效）

### ISSUE THREAD

**Issue by 384691251** [jumpserver/jumpserver#6072]
**JumpServer 版本(v1.5.9以下不再支持)**
版本：v2.9.2

**浏览器版本**
linux命令行界面

**Bug 描述**
linux命令行用ssh登录堡垒机后，选择一台机器连接，虽然不操作机器情况下30分钟后显示断开，但我回车一下就可以重新连接目标机器（即堡垒机账号会话没失效），堡垒机账号超过了24小时都不会断开（这里和web登录不同，使用web的时候超过24小时session会失效，命令行登录不会失效），不用重新输入密码和OTP，回车一下就能继续用。而且，在邮件改了该账号的登录之后，已经登录过的账号还是没有自动断开，还是可以继续使用该账号连接服务器，假设要连接的目标主机是授过权的前提下，那么一个用户可以只登录一次并且一直使用这台机器。

**Bug 重现步骤(有截图更好)**
1.  linux系统下，用ssh连接登录堡垒机
2. 过了24小时，不用重新输入账号密码，可继续在上面连接其他目标机器
3. web上修改堡垒机账号的密码也不会影响已经登录的账号使用

**Comment by leim** [comment]
经过测试已经重现，用户与堡垒机之间的session不会失效，断开的只是堡垒机到目标机的连接。

**Comment by 384691251** [comment]
> 经过测试已经重现，用户与堡垒机之间的session不会失效，断开的只是堡垒机到目标机的连接。

感谢回复，请问下这个问题会安排修复吗？我感觉还是有一定的风险（虽然可以强制用双因子认证）。之前我在群里有提过，不过几次更新都没有看到修复，特地来这边提个bug。
