### ISSUE TITLE
[Bug]  生成的SECRET_KEY重复率较高

### ISSUE THREAD

**Issue by 384691251** [jumpserver/jumpserver#6073]
**JumpServer 版本(v1.5.9以下不再支持)**
版本：v2.9.2

**浏览器版本**

**Bug 描述**
堡垒机首次安装时生成的SECRET_KEY重复率较高，其算法是根据ifconfig（如果有的话）输出最后10行进行base64编码后，再取前49个字符。这个算法其实很容易重复，只要最后10行的前面一些字符相同，就可以生成一样的SECRET_KEY。没有匹配到一些特有或者唯一的字符的话，就容易被其他人获取到这个编码。在机器标准初始化后，其实很多机器是可以生成一样的SECRET_KEY。BOOTSTRAP_TOKEN也是同理，算法都是一样的。个人认为这样存在较大安全风险，应该想办法去获取机器的特定唯一字符去生成。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/15191138/116640008-64703680-a99c-11eb-9d98-e29dbbe91fcf.png)
这个是生成的算法代码

**Comment by wojiushixiaobai** [comment]
用机器码？
```bash
sudo dmidecode -t 1 | grep UUID | awk '{print $2}' | base64 | head -c 49;echo
```

**Comment by 384691251** [comment]
或者根据机器码结合时间戳生成一串字符，时间不同，字符也不同，重复的概率比较低
