### ISSUE TITLE
[Bug]api/v1/assets/nodes/id/children/ post创建子节点失败

### ISSUE THREAD

**Issue by zhangwei0181** [jumpserver/jumpserver#6075]
JumpServer 版本
2.9.2

api/v1/assets/nodes/id/children/ 接口创建node失败。报错信息为： '{"value":["同级别节点名字不能重复"]}' 。实际上同样路径下并没有相同的节点名，只是在其他路径下相同节点名。
举例：
如果存在/Default/project1/ops ，就不能通过api创建/Default/project2/ops

web页面没有此问题，页面中可以创建成功

**Comment by miaoyb** [comment]
感觉他们API接口都没有仔细测试过。必传和非必传的字段都没更新
