### ISSUE TITLE
[Bug] 启用 LDAP 认证，数据库密码也可以登录堡垒机

### ISSUE THREAD

**Issue by 384691251** [jumpserver/jumpserver#6077]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**

**Bug 描述**
同步了ldap的数据之后，管理员主动把其中一个用户的用户来源改成数据库（原来是ldap），并修改其密码，该用户不仅可以通过原来的ldap的密码登录，也可以通过新改的数据库密码登录。如果在设置上规定了ldap认证的话，应该是不允许数据库密码登录成功的吧？这样不是增加了其风险面吗？

**Bug 重现步骤(有截图更好)**
1.  开始是用ldap同步数据，也设置了ldap的认证方式，用ldap同步的密码登录堡垒机是没有问题的。
![image](https://user-images.githubusercontent.com/15191138/116674214-ed0bc880-a9d6-11eb-8e4f-3896e5f96c79.png)
![image](https://user-images.githubusercontent.com/15191138/116674364-23494800-a9d7-11eb-97e2-69ac812fc684.png)

2. 管理员选择一个用户，改成数据库方式，修改其密码，然后提交
![image](https://user-images.githubusercontent.com/15191138/116674989-e3cf2b80-a9d7-11eb-8ec2-a47f4b74422b.png)

**注意，这时候ldap认证还是启用状态，我没有去调整它**
![image](https://user-images.githubusercontent.com/15191138/116675228-2bee4e00-a9d8-11eb-9099-424071179637.png)

3. 我用被修改密码的用户用新的密码登录，登录成功
4. 我用被修改密码的用户用之前的ldap的密码登录，也可以登录成功

**Comment by wojiushixiaobai** [comment]
一些用户有这个需求，你的操作是由于管理员自行修改了用户来源才导致这个问题，不修改即可。

**Comment by 384691251** [comment]
> 一些用户有这个需求，你的操作是由于管理员自行修改了用户来源才导致这个问题，不修改即可。

我这边有个需求，就是不想使用ldap的密码去登录认证，又想使用ldap的同步用户的功能。

**Comment by jym503558564** [comment]
修改配置文件：
 - ONLY_ALLOW_AUTH_FROM_SOURCE=true  是否仅允许从 用户来源 处登录
 - ONLY_ALLOW_EXIST_USER_AUTH=true 是否仅允许 已创建 的用户登录，如果是，则 ldap 需先导入再登录

**Comment by 384691251** [comment]
> 修改配置文件：
> 
> * ONLY_ALLOW_AUTH_FROM_SOURCE=true  是否仅允许从 用户来源 处登录
> * ONLY_ALLOW_EXIST_USER_AUTH=true 是否仅允许 已创建 的用户登录，如果是，则 ldap 需先导入再登录

第一行配置我能理解。第二行仅允许 已创建 的用户登录，那如果false是什么情况？是允许未创建的用户登录吗？未创建的用户如何能登录，求教

**Comment by 384691251** [comment]
> 修改配置文件：
> 
> * ONLY_ALLOW_AUTH_FROM_SOURCE=true  是否仅允许从 用户来源 处登录
> * ONLY_ALLOW_EXIST_USER_AUTH=true 是否仅允许 已创建 的用户登录，如果是，则 ldap 需先导入再登录

我的需求是，想利用LDAP的同步数据功能（一直定时同步数据），但不用LDAP认证，自己去数据库改密码，用自己的数据库密码登录。现阶段是否能做到呢？

**Comment by jym503558564** [comment]
那你可以同步过来，更改source为数据库，自行更改密码。

**Comment by 384691251** [comment]
> 那你可以同步过来，更改source为数据库，自行更改密码。

嗯嗯，这个问题我已经解决了，和你说的办法一样，稍微改了下代码，定时同步ldap并且每次同步自动将source更改成数据库。感谢回复~

**Comment by jym503558564** [comment]
好的，如还有其他问题，可再次提Issues
