### ISSUE TITLE
无法导入pycharm进行二次开发

### ISSUE THREAD

**Issue by zhangrandl** [jumpserver/jumpserver#608]
我想把这个项目导入到pycharm学习源代码，顺便进行二次开发，但是目前尝试多次，依然无法正常使用。有没有一个类似的说明，或者开发环境文档一类的？

**Comment by ibuler** [comment]
直接打开apps

**Comment by zhangrandl** [comment]
代码好复杂，有没有带注释的代码……

**Comment by hellorocky** [comment]
看代码的话, 建议从某一个小功能开始看, 比如用户模块,看看是如何处理用户的增删改查等等, 代码复杂更多的是使用了Class Base View, 可以先从网上查查Class Base View和http://www.django-rest-framework.org/

**Comment by zhangrandl** [comment]
好的，多谢。
