### ISSUE TITLE
[Question] 浏览器无法登录，控制台显示 jsencrypt.min.js 404

### ISSUE THREAD

**Issue by philipy1219** [jumpserver/jumpserver#6080]
**请描述您的问题.**
部署v2.9.2的服务，启动所有docker container。通过浏览器访问，输入密码无法登录。查看控制台显示jsencrypt.min.js 404错误。
jsencrypt.min.js在源码中的位置为，源码中未找到/static/js/plugins/jsencrypt/jsencrypt.min.js。请问该脚本的存放位置。

https://github.com/jumpserver/jumpserver/blob/471cb455359530942d8257d74a1d48795e120695/apps/authentication/templates/authentication/login.html#L211

**Comment by wojiushixiaobai** [comment]
请通过默认的 8080 端口进行访问，如果需要自行配置外部 nginx，请参考 [Nginx 反向代理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)

**Comment by oren-git** [comment]
这个问题我还是经常用到，现在我用的版本是v3.10.12，在这个版本之前也是经常遇到，重启之后就好了
