### ISSUE TITLE
极速部署方式如何远程链接静默数据库呢，密码和账户是啥呢 谢谢[Question] 

### ISSUE THREAD

**Issue by isslower** [jumpserver/jumpserver#6082]
**请描述您的问题.**
curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.9.2/quick_start.sh | bash  采用这个脚本部署的

**Comment by luweijun1992** [comment]
> **请描述您的问题.**
> curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.9.2/quick_start.sh | bash 采用这个脚本部署的

/opt/jumpserver/config/config.txt 该配置文件中查看下

**Comment by wojiushixiaobai** [comment]
目前mysql不对外开放，只供自身服务使用。你可以修改 docker-compose-mysql.yml 文件进行端口暴漏
账户密码在 /opt/jumpserver/config/config.txt 里面有定义

**Comment by isslower** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1256813506
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年5月6日 ***@***.***> 写道： 




目前mysql不对外开放，只供自身服务使用。你可以修改 docker-compose-mysql.yml 文件进行端口暴漏

账户密码在 /opt/jumpserver/config/config.txt 里面有定义



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by isslower** [comment]
![image](https://user-images.githubusercontent.com/45580748/117391097-e1158e80-af21-11eb-9389-7f919b9bb32a.png)
还有个问题咨询下  一键安装的 忘记管理员密码 如何修改呢 网页登录密码        按照网上说的 在安装目录下 输入命令  `python manage.py changepassword admin`  不行 报错如图   非常感谢

**Comment by luweijun1992** [comment]
> ![image](https://user-images.githubusercontent.com/45580748/117391097-e1158e80-af21-11eb-9389-7f919b9bb32a.png)
> 还有个问题咨询下 一键安装的 忘记管理员密码 如何修改呢 网页登录密码 按照网上说的 在安装目录下 输入命令 `python manage.py changepassword admin` 不行 报错如图 非常感谢

需要进入对 core 应容器操作
`
docker exec -it jms_core /bin/bash
cd /opt/jumpserver/apps
python manage.py shell

from users.models import User
u = User.objects.get(username='admin')
u.reset_password('password')
u.save()
`

**Comment by isslower** [comment]
感谢感谢。

**Comment by isslower** [comment]
![微信截图_20210507181307](https://user-images.githubusercontent.com/45580748/117435367-5c963080-af60-11eb-8050-8af311b32c21.png)
![微信截图_20210507181249](https://user-images.githubusercontent.com/45580748/117435372-5dc75d80-af60-11eb-8599-d7ed3ffca015.png)
还有个问题 社区版没有这个设置录像位置的地方 我按照官方文档找了下 没找到 v2.9.2 GPLv2.
是否只有企业版才支持呢。

**Comment by isslower** [comment]
忽略 看到了
