### ISSUE TITLE
[Question] JumpServer 可以使用PostgreSQL 作为后台数据库吗？

### ISSUE THREAD

**Issue by dragon6678** [jumpserver/jumpserver#6084]
**请描述您的问题.**
JumpServer 可以使用PostgreSQL 作为后台数据库吗？如果可以是否有想关的例子。非常感谢。

**Comment by wojiushixiaobai** [comment]
支持

**Comment by dragon6678** [comment]
请问需要如何设置？可以给个例子吗或是给个文档。感谢感谢。

**Comment by cd06b9** [comment]
# 数据库设置
# See https://docs.djangoproject.com/en/1.10/ref/settings/#databases
#https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-DATABASE-ENGINE

DB_ENGINE=mysql           # 数据库配置
DB_NAME=jumpserver        # 数据库配置
DB_HOST=127.0.0.1         # 数据库配置
DB_PORT=3306              # 数据库配置
DB_USER=root              # 数据库配置
DB_PASSWORD=****          # 数据库配置
