### ISSUE TITLE
[Feature] 应用管理建议添加 mongodb, redis 等常见数据库

### ISSUE THREAD

**Issue by 987william987** [jumpserver/jumpserver#6085]
**请描述您的需求或者改进建议.**
目前 mysql 管理很方便。
而业务上除了 mysql 以外，还有使用诸如 mongodb, redis 等等，如果也能纳入应用管理，就更好了!
请问近其是否有这规划呢?

**Comment by jym503558564** [comment]
企业版现在已支持：Mysql、Oracle、MariaDB、PostgreSQL

**Comment by 987william987** [comment]
那请问开源版未来会支援 mongodb, redis 等相关 nosql 吗

**Comment by jym503558564** [comment]
目前企业版已支持多种数据库
![image](https://user-images.githubusercontent.com/40739051/152743268-432f33fc-7e6c-4a4c-95cb-075248a4f249.png)
