### ISSUE TITLE
[Question] OSS存储有点问题

### ISSUE THREAD

**Issue by isslower** [jumpserver/jumpserver#6091]
**请描述您的问题.**
jumpserver 视频存储 测试存储桶OSS正常 
但是同步过去只有
![未命名1620456454](https://user-images.githubusercontent.com/45580748/117529847-a4729180-b00c-11eb-94f5-0b97a20c6681.png)
![未命名1620456417](https://user-images.githubusercontent.com/45580748/117529849-a5a3be80-b00c-11eb-8ef7-b8884bb0a943.png)
其他啥都没有 此时间段下面系统用户通过jumpserver进行过操作

**Comment by wojiushixiaobai** [comment]
在 终端管理 页面选择 更新 组件
- [ ] 选择你需要的存储方式即可, 大概需要 1 分钟的时间完成同步
- [ ] 之前已经存储在本地的录像需要自己手动上传到你新的存储环境

**Comment by isslower** [comment]
![image](https://user-images.githubusercontent.com/45580748/117530519-2adca280-b010-11eb-9a0d-e3c2afd5b6d6.png)
![image](https://user-images.githubusercontent.com/45580748/117530529-392abe80-b010-11eb-9b10-4217fc2b0686.png)
你好 我更新后 管理用户随便操作了下 然后是一个Python文件 test.py 文件内容如图

**Comment by isslower** [comment]
![image](https://user-images.githubusercontent.com/45580748/117530612-a3436380-b010-11eb-81ba-6996e4ab4a78.png)
我又更新了一遍  管理用户再次操作下  我再试试

**Comment by isslower** [comment]
![image](https://user-images.githubusercontent.com/45580748/117531437-0800bd00-b015-11eb-91d2-c50e4df1bb0f.png)
这个位置也更新了。

**Comment by isslower** [comment]
你好 还是不行
![image](https://user-images.githubusercontent.com/45580748/117531721-8873ed80-b016-11eb-8c24-7da47757423f.png)h还是这样的
