### ISSUE TITLE
[Question] 日志审计 里面没有任何日志.

### ISSUE THREAD

**Issue by natsu-ten** [jumpserver/jumpserver#6092]
**请描述您的问题.**
日志审计里面,不管是登录,操作,ftp 都没有日志,请问各位大哥 大概是啥问题?
数据库5.7 链接正常

**Comment by wojiushixiaobai** [comment]
你可以看下 jms_core 容器里面的日志
```bash
docker exec -it jms_core bash
tail -f -n 200 /opt/jumpserver/logs/jumpserver.log
```

**Comment by natsu-ten** [comment]
![image](https://user-images.githubusercontent.com/18704985/117536213-57061c80-b02c-11eb-860d-2434e8573c85.png)
日志里面只有错误日志, 其他操作好像不在这个里面

**Comment by natsu-ten** [comment]
> 你可以看下 jms_core 容器里面的日志
> 
> ```shell
> docker exec -it jms_core bash
> tail -f -n 200 /opt/jumpserver/logs/jumpserver.log
> ```
> 
> 如果有异常的话，将日志发给我们

![image](https://user-images.githubusercontent.com/18704985/117536303-d72c8200-b02c-11eb-8b14-a896cca53052.png)
日志里面只有错误日志, 其他操作好像不在这个里面
