### ISSUE TITLE
工单需求

### ISSUE THREAD

**Issue by Eric-Hyiboo** [jumpserver/jumpserver#6094]
1. 能否在工单申请处设置IP为必填项，避免用户提交无效工单？
2. 内否在工单申请处添加系统平台选项，方便管理员识别操作系统，进行授权系统用户？

**Comment by Eric-Hyiboo** [comment]
1. 申请的时候用户输的申请信息是有效的，比如IP、主机名、系统用户组任意一个必填，或者其他解决方案
2. 审批人可以通过申请信息看到系统平台，比如windows、Linux之类的

**Comment by BaiJiangJie** [comment]
v3 版本已有优化。
