### ISSUE TITLE
jumpserver-v2.9.2邮件设置新bug

### ISSUE THREAD

**Issue by cncentoscn** [jumpserver/jumpserver#6095]
配置完邮件设置：点击测试没有反应，点击重置没有反应。

**Comment by cncentoscn** [comment]
![Uploading Snip20210510_5.png…]()

**Comment by cncentoscn** [comment]
![Snip20210510_5](https://user-images.githubusercontent.com/39993331/117621283-09142480-b1a4-11eb-81a4-2437fb3d9cb1.png)

**Comment by jym503558564** [comment]
测试连接性须输入：SMTP 密码

**Comment by jym503558564** [comment]
- 重置，是在你现有新输入，然后点击重置，会把新输入的重置。
- 测试连接时，应当输入SMTP密码
![Uploading image.png…]()

**Comment by pangchaocheng** [comment]
最新版这个问题还是存在

**Comment by pangchaocheng** [comment]
![image](https://user-images.githubusercontent.com/35793030/124342654-f5ab9580-dbf7-11eb-9780-304290263433.png)
这是前端的bug，这几个选项不选，就默认传NULL ，后端不允许为NULL

2021-07-03 11:56:30 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/settings/api/common.py", line 29, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'EMAIL_USE_SSL': [ErrorDetail(string='该字段不能为 null。', code='null')], 'EMAIL_USE_TLS': [ErrorDetail(string='该字段不能为 null。', code='null')]}

**Comment by wuqiang3424** [comment]
v2.12.0也有这个问题，希望能够修复一下，非常感谢

**Comment by wuqiang3424** [comment]
我勾选了TLS就可以了
