### ISSUE TITLE
[Bug] JumpServer标签不显示内容

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#6097]
**JumpServer 版本(v1.5.9以下不再支持)**
版本：JumpServer 2.9.2
问题：JumpServer标签内容在添加资产的时候不显示标签值。建议可以显示标签值这样方便使用。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/29521063/117746901-c6078f00-b23f-11eb-869f-b56ff377308f.png)
![image](https://user-images.githubusercontent.com/29521063/117746911-cbfd7000-b23f-11eb-8c2c-d0a20c43b1ad.png)

**Comment by ibuler** [comment]
已完成 https://github.com/jumpserver/lina/pull/785
