### ISSUE TITLE
开发群加不进

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#610]
# 开发群加不进去 489385245

**Comment by ibuler** [comment]
不对外开放的

**Comment by ibuler** [comment]
如果给Jumpserver修复过bug，或添加过需求，可以申请加入

**Comment by vincent927** [comment]
我修复过bug 😂

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/graphs/contributors

**Comment by ibuler** [comment]
再接再厉

**Comment by vincent927** [comment]
![image](https://user-images.githubusercontent.com/10399425/29165603-d254ee56-7df5-11e7-8fc9-1b222ac17740.png)
这个不算吗？

**Comment by vincent927** [comment]
![image](https://user-images.githubusercontent.com/10399425/29165661-11cb3c34-7df6-11e7-9001-97ca6752da3a.png)

**Comment by ibuler** [comment]
加群没有别的特权，就是聊一下bug，然后商量谁来改的

**Comment by ibuler** [comment]
从这个PR可能看不出你的开发能力

**Comment by vincent927** [comment]
噢噢。好吧
