### ISSUE TITLE
[Bug] JumpServer账号被禁用后显示信息不清楚

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#6100]
JumpServer版本：任何版本

**Bug 描述**
JumpServer的用户账号被禁用、登录的时候不能正常正常显示

![image](https://user-images.githubusercontent.com/29521063/117787601-3088f100-b279-11eb-9f6b-8a3d13612814.png)
![image](https://user-images.githubusercontent.com/29521063/117787613-32eb4b00-b279-11eb-80ed-ae3630324234.png)

**Comment by jym503558564** [comment]
最新版本已优化，请更新至最新版本进行体验。
