### ISSUE TITLE
 Session历史无法回放  命令记录不全

### ISSUE THREAD

**Issue by fity2013** [jumpserver/jumpserver#611]
![image](https://user-images.githubusercontent.com/30862821/29200319-e9fd4256-7e86-11e7-997d-087ec2fc0859.png)
查看日志文件没报错 

![image](https://user-images.githubusercontent.com/30862821/29200350-2e0053da-7e87-11e7-8c7f-6902e88ab67c.png)
有建议吗

**Comment by hellorocky** [comment]
这块功能应该没有开发暂时

**Comment by fity2013** [comment]
哦 谢谢

**Comment by fity2013** [comment]
这是要自己二次开发吗？

**Comment by hellorocky** [comment]
有时间和精力就自己开发, 然后可以反馈到社区

**Comment by fity2013** [comment]
嗯
