### ISSUE TITLE
[Bug] admin用户重置MFA后登录还是之前的MFA验证

### ISSUE THREAD

**Issue by lls205** [jumpserver/jumpserver#6115]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**
chrome 版本 90.0.4430.212（正式版本） （64 位）

**Bug 描述**
admin重置MFA退出登录后，重新登录还是之前的MFA验证

**Bug 重现步骤(有截图更好)**
1.  admin用户登录的情况下，进入admin用户基本信息页面
2. 点击重置MFA 的重置按钮
3. 弹出是否重置用户MFA，确认后小窗口还在
4. 点击右上角的×关闭后提示重新登录
5. 实际上并没有重新登录，只是回到了首页
6. 手动退出后，重新登录还是使用之前的MFA验证，并没有走重新绑定新的MFA验证

**Comment by ibuler** [comment]
@wojiushixiaobai 验证一发

**Comment by chenhuxy** [comment]
v2.11.4也有，admin不能重置自己？

**Comment by wojiushixiaobai** [comment]
@lls205 @chenhuxy 自己改自己需要在个人页面操作
