### ISSUE TITLE
[Question] 请问如何保证会话连接永不断开

### ISSUE THREAD

**Issue by MicroCountry** [jumpserver/jumpserver#6135]
你好，我这边有个需求，通过jumpserver去连接windows机器，但是有逻辑必须一直要打开这个远程，现在是每隔几分钟，会话就会断开，如何能保证这个远程会话不断开呢，有没有api可以不停的去保持这个会话活跃

**Comment by wojiushixiaobai** [comment]
每隔几分钟的话是 rdp 自身的超时限制，你可以修改组策略来修改注销时间。
Guacamole 自身是限制 60 分钟断开，目前不能定义。也就是最多只允许 1 小时无操作，否则会断开

**Comment by MicroCountry** [comment]
那我们这个rdp连接的具体参数有吗？比如：
![image](https://user-images.githubusercontent.com/16758768/119349091-50d09b00-bcd0-11eb-937d-8310bc59e0d9.png)
