### ISSUE TITLE
[Bug] 系统用户功能BUG

### ISSUE THREAD

**Issue by Areturn** [jumpserver/jumpserver#6137]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.2

**浏览器版本**
谷歌浏览器

**Bug 描述**
系统用户启用‘’用户名与用户相同‘’功能+自动推送，创建的用户有bug
![image](https://user-images.githubusercontent.com/25275823/118643289-ed95c300-b80e-11eb-910d-5c7385c88718.png)
![image](https://user-images.githubusercontent.com/25275823/118643313-f71f2b00-b80e-11eb-89d4-caca25e18d58.png)
![image](https://user-images.githubusercontent.com/25275823/118643406-18801700-b80f-11eb-899e-c740d6a752bb.png)

**Bug 重现步骤(有截图更好)**
1.  看bug描述图。

**Comment by ibuler** [comment]
@wojiushixiaobai 验证一下
