### ISSUE TITLE
登录服务器后，执行部分命令卡住

### ISSUE THREAD

**Issue by liyehaha** [jumpserver/jumpserver#614]
阿里云ecs环境，通过堡垒机远程到后端服务器上执行部分命令会卡住不动，没有响应，日志中没有报错，之前未发生过类似情况

**Comment by hellorocky** [comment]
使用的哪个版本?

**Comment by ibuler** [comment]
会不会是网络问题？

**Comment by liucyao** [comment]
在luna上使用clear清屏会卡住

**Comment by hellorocky** [comment]
@liucyao 服务端升级一下pyte到0.6版本试试, 我也遇到了类似的问题, 之前是0.5.2升级到0.6后就不会出现了, 你也试试!

```
pip3 install pyte==0.6
```

**Comment by liyehaha** [comment]
是挂载NFS，NFS硬盘卡住的问题
