### ISSUE TITLE
[Question] JumpServer的用户信息在库表中存储的时候，密码是如何加密的？SHA256加盐？ 源码实现在哪里？

### ISSUE THREAD

**Issue by rogerwangzy** [jumpserver/jumpserver#6141]
**请描述您的问题.**
JumpServer的用户信息在库表中存储的时候，密码是如何加密的？SHA256加盐？ 源码实现在哪里？
基于JumpServer过安全认证，需要提供密码存储安全的证据。

**Comment by ibuler** [comment]
Django 原生的加密 https://docs.djangoproject.com/zh-hans/3.2/topics/auth/passwords/

**Comment by rogerwangzy** [comment]
好的，多谢！
