### ISSUE TITLE
/user/login登陆验证问题

### ISSUE THREAD

**Issue by zhangrandl** [jumpserver/jumpserver#615]
我看登陆页用户账号密码校验鉴权这块，但是在源代码中并未找到具体代码，请问处理校验，识别账号密码是否正确是在哪里做的？

**Comment by hellorocky** [comment]
这一块应该是django admin 自己带的功能

**Comment by ibuler** [comment]
是的，用的django自己的 auth认证系统

**Comment by zhangrandl** [comment]
但是我没明白的是具体哪里指定的用django自己的auth，没有找到相关的代码……是在setting.py里设置还是？

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/apps/users/views/login.py#L48

**Comment by zhangrandl** [comment]
但是我把这行代码注释掉，也丝毫不影响用户密码校验啊。包括我把整个form_valid方法注释掉

**Comment by ibuler** [comment]
登录以后会设置cookie，以后api校验都是校验的cookie里面的sessionid

**Comment by zhangrandl** [comment]
那第一次登录的时候，是如何进行校验的？
