### ISSUE TITLE
[Bug] 配置问题

### ISSUE THREAD

**Issue by einsone** [jumpserver/jumpserver#6156]
**JumpServer 版本(v1.5.9以下不再支持)**
> v2.8.2

**浏览器版本**
> 90.0.4430.212 (正式版本) （64 位） (cohort: Stable)

**Bug 描述**

1. 配置字段不一致： `settings.PERIOD_TASK_ENABLE`。实际用到的是`settings.PERIOD_TASK_ENABLED`
https://github.com/jumpserver/jumpserver/blob/0380be51dd8fb4c8391ee92736445aef3bb35b91/apps/jumpserver/conf.py#L282

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
的确是bug，已修复 https://github.com/jumpserver/jumpserver/pull/6159
