### ISSUE TITLE
仪表盘用户总数显示问题[Bug] 

### ISSUE THREAD

**Issue by wcb0414** [jumpserver/jumpserver#6162]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer 版本 v2.10.0

**浏览器版本**
Microsoft Edge 90.0.818.56

**Bug 描述**
仪表盘用户总数显示不对[Bug] 

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/81307592/119073105-3ae87f00-ba1f-11eb-9572-6202ac360580.png)
![image](https://user-images.githubusercontent.com/81307592/119073118-42a82380-ba1f-11eb-8f04-7f029b7dc5f5.png)

**Comment by china-live** [comment]
更新到v2.10.0一登录就发现，我的用户数显示的17，实际上只有8个用户

**Comment by ibuler** [comment]
修复中，等待 2.10.1

**Comment by ibuler** [comment]
已修复
