### ISSUE TITLE
希望能够加入企业微信oauth2登录[Feature] 

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#6170]
企业微信新建一个应用为jumpserver 主页默认设置为了自建的jumpserver主页 点击应用还是登录页面点击的企业微信登录还是扫码登录 希望能够优化成免登录模式

**Comment by china-live** [comment]
支持这个建议，不光用企业微信新建的应用该这么做，所有登录都应该支持QQ、微信登录，让用户不用记那么多密码。

**Comment by ibuler** [comment]
这个应该是企业微信  oauth

**Comment by wushengmin** [comment]
是的 现在支持企业微信的oauth吗> 这个应该是企业微信  oauth

**Comment by wushengmin** [comment]
> 这个应该是企业微信 oauth

是的 现在支持企业微信的oauth吗？或者以后会支持吗？

**Comment by jym503558564** [comment]
最新版本已支持Oauth 2认证，请升级至最新版本进行测试。
