### ISSUE TITLE
企业微信登录可以不使用MFA验证[Feature] 

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#6171]
企业微信登录希望能够不使用MFA验证。本来MFA是为了账户密码不安全使用了手机的二步认证的登录方式，但是现在已经使用了企业微信来登录了系统，是不是取消企业微信的二步认证比较合理

**Comment by huwsun** [comment]
支持这个需求，可以强制要求启用一种安全的登录方式，企业微信和mfa二选一就可以了

**Comment by 2156yy** [comment]
强烈建议SSH登陆的时候支持只用key验证，在web端登陆时用密码及MFA或别的方式二次验证。打开MFA后SSH登陆频繁的情况下每次二次验证太麻烦了，但是web端只用密码又不是特别安全。
