### ISSUE TITLE
[Bug] jumpserver2.10.1 cannot edit text in Full screen mode

### ISSUE THREAD

**Issue by chonatee** [jumpserver/jumpserver#6178]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by chonatee** [comment]
jumserver 2.10.1 cannot edit in Full screen mode

**Comment by chonatee** [comment]
effect on windows rdp.  On ssh  work properly.

**Comment by sevenclockseven** [comment]
不是全屏rdb无法键盘输入，而是鼠标有点击非rdp画面范围操作时都会导致键盘无法输入，点击rdp画面右侧功能区后就可以恢复键盘输入，是否全屏都适用。 @chonatee  It’s not that the keyboard cannot be input in full screen RDB, but the keyboard cannot be input when the mouse is clicked on the non-rdp screen range. After clicking the function area on the right side of the rdp screen, keyboard input can be restored. It is applicable to full  谷歌翻译，凑合着看吧

**Comment by chonatee** [comment]
It works . Thank you for your advice.
