### ISSUE TITLE
[Feature] 全屏快捷键、右侧快捷键能否设置成自定义

### ISSUE THREAD

**Issue by zhangjiwei** [jumpserver/jumpserver#6180]
**请描述您的需求或者改进建议.**
1、全屏快捷键自定义，因为Esc外围pc在用。
2、右侧的快捷键自定义，并且可以隐藏起来。
3、web终端能否做成Moba一样快捷键都能正常使用

**Comment by BaiJiangJie** [comment]
1. ESC 退出全屏已修改为 `长按ESC键`，不影响外部的 ESC 功能。
2. 暂时不考虑
