### ISSUE TITLE
[Bug] 2.10.x VNC显示问题

### ISSUE THREAD

**Issue by enthanlee** [jumpserver/jumpserver#6185]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
2.10.x 的lion组件如果连接vnc，画面默认不是缩放，因此如果超出窗口的部分需要用滚动条显示，但横向缺少滚动条，以致无法完全显示。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wp5970** [comment]
版本用的是20.10.1
我遇到的问题是，vnc链接到Centos之后，如果切换到全屏，则画面不会自动铺满屏幕，还是按窗口大小显示在左上角，不知道是不是BUG
