### ISSUE TITLE
[Feature] 更新和使用中遇到的问题

### ISSUE THREAD

**Issue by wp5970** [jumpserver/jumpserver#6186]
**请描述您的需求或者改进建议.**
1.升级到2.10.x版本后，在登录日志中，所有登录IP都是：192.168.250.1，而不能真实显示源IP，而在2.9.x版本时是可以显示的。
2.升级到2.10.x版本后，Web终端增加了右边栏，首先右边栏会占用画面；其次还容易在鼠标右移的时候误触，导致鼠标焦点切换，中断当前操作；最后，右边栏还会抢占输入焦点，导致在实体机和Web终端之间切换时，出现Web终端内无法输入的问题，必须再用鼠标点击一次右边栏，再切换回Web终端内才能正常输入。
3.使用telnet协议增加部分厂商的设备资产之后，在Web终端相应资产中，可以输入字符，但是却无法使用退格键删除字符。（如瑞斯康达部分设备、华为OLT、中兴交换机）
4.升级到2.10.x版本后，Web终端连接资产时，如果没有完全进入桌面就选择全屏显示，则画面无法自动缩放，仅以初始画面大小显示在屏幕右上角，需要等待完全进入桌面后再选择全屏显示才行，之前的版本则不会这样。
5.升级到2.10.x版本后，Web终端连接Centos资产时，选择全屏显示，画面无法自动缩放，仅以初始画面大小显示在屏幕右上角。

**Comment by wangyu0310** [comment]
Version v2.10.1-101遇到以上同样问题

**Comment by jym503558564** [comment]
@wp5970 鼠标失焦点问题，在2.10.2版本已解决，请升级。
