### ISSUE TITLE
[Feature] windows连接界面右边工具栏存在遮挡，建议不要悬浮到画板上面

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#6188]
**请描述您的需求或者改进建议.**
建议将工具栏放到面板外面，分辨率大的情况下会遮挡窗口的按钮
![1641621996512_ pic_hd](https://user-images.githubusercontent.com/44662176/119594553-972c1400-be0e-11eb-80b6-d51074dbf47e.jpg)

**Comment by huwsun** [comment]
远程桌面里面最右边的按钮都被挡住了，点不到，确实有问题

**Comment by jym503558564** [comment]
现版本，点击快捷键后，可再次点击窗口随意位置，即可收缩快捷窗口，不会遮挡到。
