### ISSUE TITLE
[Bug] windows远程桌面没法输入

### ISSUE THREAD

**Issue by yuchunyun** [jumpserver/jumpserver#6190]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.10.0

**浏览器版本**
chrome

**Bug 描述**
web终端里打开俩个设备的连接，切换窗口后，windows里的输入就不行了，鼠标可以移动，但键盘输入不了

**Bug 重现步骤(有截图更好)**
1.  打开两个连接
2. 在windows里输入--正常
3. 切换到另外一个窗口
4. 再切回windows，输入--异常

**Comment by wangyu0310** [comment]
遇到了同样的问题 Version v2.10.1-101
输入不好使，点击右侧的剪切板之后又能正常输入，中英文切换支持也不是很好。

**Comment by wp5970** [comment]
> 遇到了同样的问题 Version v2.10.1-101
> 输入不好使，点击右侧的剪切板之后又能正常输入，中英文切换支持也不是很好。

升级到2.10.2就好了，官方更新解决了问题

**Comment by jym503558564** [comment]
@wangyu0310  @yuchunyun 升级到2.10.2,已解决。

**Comment by uranus829** [comment]
> @wangyu0310 @yuchunyun 升级到2.10.2,已解决。

2.11.3为什么还是有中英文的问题啊？经常小写变为大写了。
