### ISSUE TITLE
[Bug] Request failed with status code 500   /api/v1/index/?total_count=1

### ISSUE THREAD

**Issue by tonyfud** [jumpserver/jumpserver#6192]
Version v2.10.2 

![image](https://user-images.githubusercontent.com/15663374/119654849-750cb300-be5b-11eb-94a9-2bcc74cea138.png)

**Comment by tonyfud** [comment]
![image](https://user-images.githubusercontent.com/15663374/119655882-a6d24980-be5c-11eb-8766-6c31d5e87aa4.png)

**Comment by enan820** [comment]
redis版本要求6以上

**Comment by jym503558564** [comment]
该问题还存在吗。
