### ISSUE TITLE
[Bug] 仪表盘用户数统计不正确

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#6194]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.2

**浏览器版本**

**Bug 描述**

 仪表盘用户数统计不正确

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44529247/119762088-a3cc6d00-bedf-11eb-8c3e-38eba4ef16dc.png)
![image](https://user-images.githubusercontent.com/44529247/119762147-c068a500-bedf-11eb-808a-974154384561.png)
![image](https://user-images.githubusercontent.com/44529247/119762175-c78fb300-bedf-11eb-88d9-8edcab6f2132.png)

2. 
3.

**Comment by jym503558564** [comment]
@ryswork1993 你重新创建一个用户或者删除用户，再刷新一下页面。会重新去拉去数据。这个在2.10.1版本有解决。
