### ISSUE TITLE
[Bug] 升级到2.10.1版本后，windows服务无法访问了

### ISSUE THREAD

**Issue by jaychang1989** [jumpserver/jumpserver#6197]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
chrome 90

**Bug 描述**
![image](https://user-images.githubusercontent.com/2285653/119782361-adb19880-befe-11eb-919c-238e0aeddf22.png)
![image](https://user-images.githubusercontent.com/2285653/119782400-bc984b00-befe-11eb-8898-a2821e176857.png)

**Bug 重现步骤(有截图更好)**
1.  看到升级说明，升级到2.10版本后，使用lion替代Guacamole，结果windows资源无法访问了，日志也没有记录

**Comment by huwsun** [comment]
#6193 可以看这个问题，有临时的解决办法

**Comment by jaychang1989** [comment]
> #6193 可以看这个问题，有临时的解决办法
使用临时方法解决了，麻烦尽快合并到主分支
