### ISSUE TITLE
admin账户重置密码的问题(v0.4.0)

### ISSUE THREAD

**Issue by everroad** [jumpserver/jumpserver#620]
admin帐号未修改邮箱，重置密码的时候收不到验证码？现在登录不了系统了，请问还有其他方式修改登录密码吗？

**Comment by hellorocky** [comment]
可以修改数据库, 直接使用django的model,参考修改如下代码:

```python
import os
import sys
import json

import django
os.environ['DJANGO_SETTINGS_MODULE'] = 'jumpserver.settings'
django.setup()

from users.models import User

user = User.objects.get(username="admin")
user.password = "123456"
user.save()
```

把这个脚本放到jumpserver/apps目录下使用启动jumpserver的python执行试试

**Comment by xubinxinant** [comment]
请问3.0版本如何重置admin密码，我的密码也忘记了

**Comment by xubinxinant** [comment]
已经解决v0.3.2
[root@ssjumpserver ~]# cd /opt/jumpserver/
[root@ssjumpserver jumpserver]# ls
a.py  connect.py  connect.pyc  docs  install  jasset  jlog  jperm  jumpserver  jumpserver.conf  juser  keys  LICENSE  logs  manage.py  README.md  run_websocket.py  service.sh  static  templates
[root@ssjumpserver jumpserver]# cd install/
[root@ssjumpserver install]# ls
developer_doc.txt  initial_data.yaml  install.py  install.pyc  next.py  requirements.txt  zzjumpserver.sh
[root@ssjumpserver install]# 
[root@ssjumpserver install]# 
[root@ssjumpserver install]# 
[root@ssjumpserver install]# python next.py 
开始安装Jumpserver, 要求环境为 CentOS 6.5 x86_64
开始更新jumpserver
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

请输入管理员用户名 [admin]: 
请输入管理员密码: [5Lov@wife]: 
请再次输入管理员密码: [5Lov@wife]: 
jumpserver  is running...
                                                           [  确定  ]
安装成功，请访问web, 祝你使用愉快。
请访问 https://github.com/ibuler/jumpserver 查看文档
