### ISSUE TITLE
[Question] AttributeError: 'module' object has no attribute 'lru_cache'

### ISSUE THREAD

**Issue by hitechbeijing** [jumpserver/jumpserver#6200]
环境是centos7 python3.6，运行jms start报错AttributeError: 'module' object has no attribute 'lru_cache'

**Comment by wojiushixiaobai** [comment]
检查下python依赖是否没安装完全

**Comment by hitechbeijing** [comment]
确定已经安装完requirements.txt所有pip包

**Comment by ibuler** [comment]
使用 python3.7 试试，可以参考 dockerfile 完成手动安装

**Comment by hitechbeijing** [comment]
我先用容器弄了，有空再试试，但是我还发现其他问题。
