### ISSUE TITLE
[Bug] 快捷键冲突

### ISSUE THREAD

**Issue by zhangjiwei** [jumpserver/jumpserver#6201]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.2

**浏览器版本**
chrome 91.0.4472.77

**Bug 描述**
1、远程linux桌面全屏后vi编辑文件按Esc退出编辑与退出全屏冲突
2、远程windows桌面快捷键与外围的PC windows快捷键冲突，操作输入法快捷键冲突，所有win键+访问的都是外围PC机冲突

**Comment by wp5970** [comment]
ESC和WIN键冲突是一直都存在的，毕竟是WEB终端，对于本地主机来说，你就是用浏览器在浏览一个网页而已。

**Comment by ibuler** [comment]
esc 可以尝试用 ctrl+c 代替

**Comment by zhangjiwei** [comment]
你好
可以用其他快捷键代替嘛，ctrl+c复制再用






张继伟
长春嘉诚信息技术股份有限公司


 联系我









&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 上午10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Bug] 快捷键冲突 (#6201)





 
esc 可以尝试用 ctrl+c 代替
