### ISSUE TITLE
[Bug] Windows7 x86和x64版本的远程主机 画面无法全屏

### ISSUE THREAD

**Issue by wp5970** [jumpserver/jumpserver#6202]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.2

**浏览器版本**
Microsoft Edge  版本 91.0.864.37 (官方内部版本) (64 位)
Google Chrome 版本 91.0.4472.77（正式版本） （64 位）
Firefox Browser 版本 88.0.1 (64 位)

**Bug 描述**
Windows7 x86和x64版本的远程主机

Windows RDP 远程 画面无法全屏显示

Windows10 则正常

**Bug 重现步骤(有截图更好)**
1. 
2. 
3.

**Comment by LeeEirc** [comment]
自动调整屏幕需要Windows服务的支持，依据guacamole的文档，rdp 版本需要大于等于8.1， 可查看官网更新到 [rdp 8.1](https://support.microsoft.com/en-us/topic/update-for-rdp-8-1-is-available-for-windows-7-sp1-2f676d97-efda-f251-e7ec-3b6f99e071ec) 尝试下。
