### ISSUE TITLE
[Bug] 2.10.2更新失败

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#6205]
**JumpServer 版本(v1.5.9以下不再支持)**
2.9.2升级到2.10.2

**浏览器版本**
无

**Bug 描述**
更新失败

**Bug 重现步骤(有截图更好)**
1.  命令为./jmsctl.sh check_update
2. 输出：[jumpserver/guacamole:v2.10.2]
Error response from daemon: manifest for jumpserver/guacamole:v2.10.2 not found: manifest unknown: manifest unknown
3. 命令./jmsctl.sh restart
输出：
Pulling guacamole (jumpserver/guacamole:v2.10.2)...
ERROR: manifest for jumpserver/guacamole:v2.10.2 not found: manifest unknown: manifest unknown

**Comment by jimersylee** [comment]
同样的问题 jumpserver/guacamole:v2.10.2  这个镜像在仓库中没找到,可以在堡垒机上自己建个镜像
docker tag jumpserver/guacamole:v2.9.2 jumpserver/guacamole:v2.10.2
然后./jmsctl restart

**Comment by wushengmin** [comment]
从github下载最新的启动脚本 新版使用lion了

**Comment by zhangjiwei** [comment]
可以把之前的2.9.2删掉，重新下载2.10.2安装部署。就ok了

**Comment by sshnuke3** [comment]
> 
> 
> 可以把之前的2.9.2删掉，重新下载2.10.2安装部署。就ok了

生产环境也可以？只要把原来的volume保留就行了么？

**Comment by wushengmin** [comment]
是的 换新的直接走更新> > 
> 
> > 
> 
> > 可以把之前的2.9.2删掉，重新下载2.10.2安装部署。就ok了
> 
> 
> 
> 生产环境也可以？只要把原来的volume保留就行了么？

**Comment by jym503558564** [comment]
2.10版本开始，Lion组件替换了原来guacamole组件。
