### ISSUE TITLE
[Bug] RDP类型的系统账号会被推送到非rdp协议的机器

### ISSUE THREAD

**Issue by neighbour-oldhuang** [jumpserver/jumpserver#6206]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.1

**浏览器版本**
chrome90

**Bug 描述**
创建的RDP协议的账号开启了自动推送，当赋权给某个用户时候，即使服务器是ssh协议登陆， RDP协议的系统账号也会推送

**Bug 重现步骤(有截图更好)**
1.  添加RDP协议的系统用户
2. 给某个jumpserver用户赋权一批机器的权限，ssh/rdp都有 
4. 将此用户赋权给上述用户

**Comment by wojiushixiaobai** [comment]
错误授权导致
