### ISSUE TITLE
[Feature] 权限管理-资产授权列表显示和检索条件添加操作系统、版本、系统用户名

### ISSUE THREAD

**Issue by liulongleo** [jumpserver/jumpserver#6208]
在日常使用资产授权过程中有一些场景如果能通过 ** 「操作系统、版本、系统用户名（root、admin）」 ** 一类信息过滤筛选，则能大大提升操作便捷性，希望能添加这些筛选条件。
同时也希望能直接将「操作系统、版本、」在列表的列也能显示，请酌情考虑，谢谢。

**Comment by wojiushixiaobai** [comment]
加入了系统平台和协议。
