### ISSUE TITLE
[Feature] X-Pack改密计划-选择节点后无法根据操作系统区分设置改密策略

### ISSUE THREAD

**Issue by liulongleo** [jumpserver/jumpserver#6209]
一般情况 Linux 和 Windows 的用户名和密码策略都有所不同，肯定需要区分处理；
当前设置改密计划，资产相关信息可以填写一个用户名、选择一个节点或者添加指定资产；
**问题：**
+ 如果按节点添加资产，则不能满足有多种操作系统时的场景
+ 如果一台一台添加资产选择同一类型的操作系统，则不能满足日常资产增加的场景

**建议：**
在资产区域添加操作系统的数据项，当选择的资产为节点或多台时，进一步根据操作系统过滤执行范围，提高易用性。
感谢

**Comment by BaiJiangJie** [comment]
不同平台密码不同可以通过创建不同的改密计划来进行，如果在一个改密计划里区分，处理逻辑会比较麻烦。
