### ISSUE TITLE
[Bug] v2.10.2版本创建数据库应用时，数据库字段变成了必填项

### ISSUE THREAD

**Issue by chjtwork** [jumpserver/jumpserver#6211]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.10.2

**浏览器版本**
Chrome 90

**Bug 描述**
不知道算不算是bug，当前版本，创建数据库时的 数据库字段 变成了必填项，以前使用旧版本(v2.4.4)，包括官方文档里，数据库这个字段都是可选项。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/32709877/120288192-88ec6500-c2f2-11eb-8fa0-e2a5efef7574.png)

**Comment by jym503558564** [comment]
在之前几个版本，就是必填字段了，

**Comment by chjtwork** [comment]
能否请教下这个修改的用意？
个人觉得对于日常使用来说，并不需要给每个数据库应用都设置一个初始的db。包括官方文档的快速入门一节中也是这样描述的：“数据库 选项可以留空, 如果是某些特定用户, 只允许访问指定的数据库, 这里指定数据库名称即可”
