### ISSUE TITLE
[Bug] luna 设置显示分辨率无法生效

### ISSUE THREAD

**Issue by apxx-xqy** [jumpserver/jumpserver#6212]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.10.2

**浏览器版本**
Chrome 91.0.4472.77

**Bug 描述**
设置显示分率无法生效

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
最新版本已修复，可升级至最新版本进行测试。如果还有其他问题，可再次提Issues
