### ISSUE TITLE
[Question] 请问jumpserver是否有计划支持原生RDP客户端(如mstsc)连接windows资产？

### ISSUE THREAD

**Issue by stephsix** [jumpserver/jumpserver#6213]
**请描述您的问题:**
当前js连接windows资产(rdp协议)时，需要通过浏览器以Guacamole的方式连接；但是对于linux/unix资产(ssh协议)提供了ssh server，即可通过2222端口直连：
ssh -p 2222 用户名@JumpServer_IP地址
请问：
目前是否有计划支持原生RDP客户端，如mstsc来连接windows资产？

**Comment by luweijun1992** [comment]
据说月底会有对应版本出来，但是需要企业版才支持。

**Comment by jym503558564** [comment]
企业版已支持

**Comment by ChenRuihua** [comment]
开源版本会支持么？
