### ISSUE TITLE
[Feature] 代理跳板

### ISSUE THREAD

**Issue by fisherwei** [jumpserver/jumpserver#6215]
**请描述您的需求或者改进建议.**
希望能增加一个类似于 zabbix-proxy 的跳板代理功能，我公司目前的有3个网络隔离的数据中心，少量服务器可以开放特定端口，这就造成了需要在3个IDC部署三套 jumpserver 才可以正常使用，希望可以在每个IDC部署一个比如 ssh-proxy 的机器，然后只针对这一台机器做网络打通，jumpserver集中部署在一个安全的内网机器上，统一管理所有的服务器。

**Comment by cdisk** [comment]
支持，同求。

**Comment by huangzx** [comment]
网域就可以解决了。

**Comment by fisherwei** [comment]
> 现有的网域功能就可以解决了。

感谢回复，确实可以实现功能。只是我遇到的情况比较麻烦，我公司安全部门严格禁止ssh协议穿透防火墙，这也是之所以我们会用到jumpserver的原因，如果可以实现走https协议的proxy是比较好的办法。

**Comment by cdisk** [comment]
有没有可能在代理服务器上部署一个proxy程序，让这个proxy程序反过来连接jumpserver服务提供代理服务。
比如在甲机房的服务器A上服务proxy，从而不需要在互联网上开放服务器A的SSH端口映射。

**Comment by ibuler** [comment]
> 有没有可能在代理服务器上部署一个proxy程序，让这个proxy程序反过来连接jumpserver服务提供代理服务。
> 比如在甲机房的服务器A上服务proxy，从而不需要在互联网上开放服务器A的SSH端口映射。
> 

复杂度太高，要实现长连接，服务器暴露 tcp 端口，如果社区可以贡献那是极好的
