### ISSUE TITLE
[Feature] SCRT终端Clone Session问题优化

### ISSUE THREAD

**Issue by 384691251** [jumpserver/jumpserver#6217]
**请描述您的需求或者改进建议.**
用SCRT终端登录堡垒机后，选择一台目标机器进入。
![image](https://user-images.githubusercontent.com/15191138/120572999-7b002680-c44f-11eb-960e-14c49719f773.png)
我需要对这台机器再开一个N个窗口，SCRT右键然后点击Clone Session，并不能直接进入连接的机器，只能克隆登录堡垒机的状态，还需要手动选择目标机器再进入，体验不是很好。

**Comment by luweijun1992** [comment]
那是肯定的啊，CRT连的是JumpServer:2222，克隆出来肯定也还是。
就好比你CRT连接到S1服务器、然后你通过S1服务器SSH跳到S2服务器、这时候你克隆S1会话，不也还是S1服务器。

**Comment by 384691251** [comment]
> 那是肯定的啊，CRT连的是JumpServer:2222，克隆出来肯定也还是。
> 就好比你CRT连接到S1服务器、然后你通过S1服务器SSH跳到S2服务器、这时候你克隆S1会话，不也还是S1服务器。

我看齐治堡垒机用CRT是可以做到克隆是直接连到目标机器（S2）的
