### ISSUE TITLE
[Bug] mysql审计日志语句记录不完整

### ISSUE THREAD

**Issue by hitechbeijing** [jumpserver/jumpserver#6223]
**JumpServer 版本(v1.5.9以下不再支持)**
最新

**浏览器版本**

chrome
**Bug 描述**

mysql审计日志语句经常记录不完整。
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/9780601/120594841-16a38e00-c474-11eb-8b14-4da519c944be.png)
![image](https://user-images.githubusercontent.com/9780601/120594893-29b65e00-c474-11eb-8af6-d08378419b55.png)
![image](https://user-images.githubusercontent.com/9780601/120594941-3a66d400-c474-11eb-9b59-cebe9598bf4e.png)

**Comment by jym503558564** [comment]
什么版本。目前在最新版本v2.10.3未发现该问题。

**Comment by hitechbeijing** [comment]
v2.10.2
