### ISSUE TITLE
[Bug]  Conn[0af10688-e199-47a3-a6c9-b21a0c40d462] did not found cache ssh

### ISSUE THREAD

**Issue by TroubleJin** [jumpserver/jumpserver#6227]
**JumpServer 版本(v1.5.9以下不再支持)**
2.0.2

**浏览器版本**

**Bug 描述**
ssh  连接时间较长
[ERRO] Conn[0af10688-e199-47a3-a6c9-b21a0c40d462] did not found cache ssh

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/48788965/120606889-3cd02a80-c482-11eb-876f-66d434ff721d.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
把资产的ssh配置文件usedns关闭试试

**Comment by TroubleJin** [comment]
关闭了也不行
