### ISSUE TITLE
not found iamge jumpserver/guacamole:v2.10.3

### ISSUE THREAD

**Issue by jiangqinghuang** [jumpserver/jumpserver#6237]
not found iamge jumpserver/guacamole:v2.10.3
![image](https://user-images.githubusercontent.com/32115295/120910667-38d71f00-c6b3-11eb-902e-8566dc06eb77.png)

**Comment by luweijun1992** [comment]
现在没有guacamole了吧，变成是lion

**Comment by jym503558564** [comment]
@jiangqinghuang 2.10版本开始，重构Lion，代替了原来guacamole组件。
