### ISSUE TITLE
[Bug] 升级2.10.3 之后 一键脚本启动失败

### ISSUE THREAD

**Issue by mojocn** [jumpserver/jumpserver#6239]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
Pulling guacamole (jumpserver/guacamole:v2.10.3)...
[root@kae-jumperserver01 installer]# ./jmsctl.sh start
Pulling guacamole (jumpserver/guacamole:v2.10.3)...
ERROR: manifest for jumpserver/guacamole:v2.10.3 not found
[root@kae-jumperserver01 installer]#

**Comment by wushengmin** [comment]
把你的启动器更新下
