### ISSUE TITLE
[Bug] docker image  jumpserver/jms_all  > v2.9.2

### ISSUE THREAD

**Issue by mojocn** [jumpserver/jumpserver#6240]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
容器启动报这个错误
wait for jms_redis 127.0.0.1 ready

**Comment by wojiushixiaobai** [comment]
新版本因为mysql和redis的版本要求不一样，不能直接进行持久化升级，考虑到用户可能不关注更新说明，我们去掉了内置的 mysql 和 redis，访问数据污染。请自行部署外置数据库和redis并还原数据
