### ISSUE TITLE
[Bug] 用户导入密码策略文档显示不对

### ISSUE THREAD

**Issue by imkratos** [jumpserver/jumpserver#6251]
**JumpServer 版本(v1.5.9以下不再支持)**
2.20.3 

**浏览器版本**
chrome

**Bug 描述**
用户导入时，[文档](https://docs.jumpserver.org/zh/master/admin-guide/data-import/csv_import/)里写明的是密码策略是0或1，但在实际操作时 0 或1 显示参数不对，自定义密码是custom

**Bug 重现步骤(有截图更好)**
1.  下载导入模板
2. 填写用户参数
3. 上传模板

**Comment by wojiushixiaobai** [comment]
感谢反馈，已经修复。
