### ISSUE TITLE
[Bug] 使用升级脚本升级的时候，有错误提示

### ISSUE THREAD

**Issue by HolyGu** [jumpserver/jumpserver#6254]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.10.1升级v2.10.4

**浏览器版本**
不涉及

**Bug 描述**
在使用升级脚本./jmsctl.sh upgrade升级版本的时候，升级到最后提示
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

**Bug 重现步骤(有截图更好)**
1.  
<img width="669" alt="截屏2021-06-09 下午10 17 38" src="https://user-images.githubusercontent.com/28488437/121371983-87fda800-c970-11eb-979c-eeb5f504369e.png">

**Comment by wojiushixiaobai** [comment]
文档已经添加对应的说明，请看 commit 即可
一般情况下忽略此提示。我们后在后续的版本优化
