### ISSUE TITLE
windows AD 域帐号导入成功，但是看不到AD域帐号

### ISSUE THREAD

**Issue by chenglu01** [jumpserver/jumpserver#6260]
快速安装方式安装：
Version v2.10.4 GPLv2

连接AD域正常，也匹配到250个用户：
<img width="1046" alt="图片" src="https://user-images.githubusercontent.com/15355034/121520323-614d7900-ca25-11eb-8985-06d42aafb1c5.png">

使用一键导入，也可以正常导入用户：
<img width="732" alt="图片" src="https://user-images.githubusercontent.com/15355034/121520472-8641ec00-ca25-11eb-9987-e75c50b1e41f.png">

使用导入的AD域帐号登录，也可以正常登录网页：
<img width="1419" alt="图片" src="https://user-images.githubusercontent.com/15355034/121520529-96f26200-ca25-11eb-8f48-e1350c99945b.png">

但是管理员账户确看不到用户，导致没法给用户授权：
<img width="1275" alt="图片" src="https://user-images.githubusercontent.com/15355034/121520597-ac678c00-ca25-11eb-928c-b8bea40e5ce9.png">

另外通过终端使用密码登录提示无法登录

请教一下这个问题是怎么回事？

**Comment by wojiushixiaobai** [comment]
存在此bug，请等待修复或者回退到 v2.10.2 版本即可

**Comment by chenglu01** [comment]
好的，已经回退到2.10.2版本了，确实使用正常。谢谢答复。

**Comment by uranus829** [comment]
请问回退版本如何操作呢？是否要还原数据库？
