### ISSUE TITLE
官方是否有社区版技术交流群

### ISSUE THREAD

**Issue by lls205** [jumpserver/jumpserver#6262]
有官方的社区版技术交流群吗，有些使用和技术上的问题想交流

**Comment by wojiushixiaobai** [comment]
https://docs.jumpserver.org/zh/master/img/weixin-group.jpg

**Comment by lls205** [comment]
qq的链接不行额，一直是"正在前往QQ"

**Comment by jym503558564** [comment]
QQ:![image](https://user-images.githubusercontent.com/40739051/122719148-62da3500-d2a0-11eb-90f8-2c4a34b73869.png)
微信企业群：
![Uploading image.png…]()
