### ISSUE TITLE
[Bug] LDAP用户导入之后，不会显示在用户列表

### ISSUE THREAD

**Issue by lizhenwei** [jumpserver/jumpserver#6264]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.10.4 

**浏览器版本**

**Bug 描述**
LDAP用户导入之后，不会显示在用户列表

**Bug 重现步骤(有截图更好)**
1.  admin登录【系统设置】
2. 选择【LDAP设置】页签
3. 输入正确的LDAP信息
4. 点击【一键导入】按钮
5. 成功导入5个用户
![image](https://user-images.githubusercontent.com/13379136/121674326-7ccb8900-cae4-11eb-9f3e-7a1b4bed56ec.png)
6.发现只有admin，没有导入成功的LDAP用户
![image](https://user-images.githubusercontent.com/13379136/121674407-9967c100-cae4-11eb-8f47-ab08bf21e3bf.png)

**Comment by luweijun1992** [comment]
> **JumpServer 版本(v1.5.9以下不再支持)**
> v2.10.4
> 
> **浏览器版本**
> 
> **Bug 描述**
> LDAP用户导入之后，不会显示在用户列表
> 
> **Bug 重现步骤(有截图更好)**
> 
> 1. admin登录【系统设置】
> 2. 选择【LDAP设置】页签
> 3. 输入正确的LDAP信息
> 4. 点击【一键导入】按钮
> 5. 成功导入5个用户
>    ![image](https://user-images.githubusercontent.com/13379136/121674326-7ccb8900-cae4-11eb-9f3e-7a1b4bed56ec.png)
>    6.发现只有admin，没有导入成功的LDAP用户
>    ![image](https://user-images.githubusercontent.com/13379136/121674407-9967c100-cae4-11eb-8f47-ab08bf21e3bf.png)

存在此bug，请等待修复或者回退到 v2.10.2 版本即可
https://github.com/jumpserver/jumpserver/issues/6260

**Comment by liuqing-datacloak** [comment]
已经同步过LDAP的用户，把版本2.10.4 回退到 2.10.2之后，再同步LDAP也不会把用户加进去（新的用户可以同步进来）
