### ISSUE TITLE
[Question] 2.10.4版不能显示OpenID认证用户

### ISSUE THREAD

**Issue by gtinging** [jumpserver/jumpserver#6287]
使用2.10.3docker部署时，配置openid登陆，用户使用openid登录后，管理员在用户列表可以显示用户信息，带过来的用户名称信息都正常。
在升级了2.10.4docker版后，新登录的openid用户，管理员在用户列表看不到用户信息。想添加用户提示
“具有 用户名 的 用户 已存在。“
”具有 邮件 的 用户 已存在。“

在另一台服务器尝试编译文档部署2.10.4，也是同样的问题，用户列表不显示，其他功能一切正常。

大家有这样的问题吗？谢谢！

**Comment by gtinging** [comment]
再次确认2.11.0也没有修复这个问题。

**Comment by jym503558564** [comment]
好的，感谢反馈。v2.11.2 版本解决

**Comment by jym503558564** [comment]
@gtinging 请升级至v2.11.2，该问题已解决。如还有其他问题，可再次提issues
