### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by dragonhaimax** [jumpserver/jumpserver#6288]
**请描述您的需求或者改进建议.**
英文版界面  “1天内自动登录” 改为英文字样
![image](https://user-images.githubusercontent.com/18454230/122229104-0c10dc00-ceeb-11eb-8eb0-f1708913ebbb.png)

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/pull/6311 等待小版本
