### ISSUE TITLE
[Bug] 鼠标指针、右侧快捷键

### ISSUE THREAD

**Issue by zhangjiwei** [jumpserver/jumpserver#6289]
鼠标指针不变化，导致是否选中很模糊，体验不是很好
鼠标滑过或者拽滚动条，右侧快捷键很碍事，能否做成隐藏式，或者去掉。体验不是不好

**Comment by ibuler** [comment]
后来版本已经修复了，改成 点击了

**Comment by zhangjiwei** [comment]
鼠标指针样式不变，尤其拖拽窗口大小的时候，都不知道选没选中

**Comment by ibuler** [comment]
截图说明一下

**Comment by zhangjiwei** [comment]
截图也带不了鼠标指针
再举个例子吧，鼠标放到URL上显示的还是指针图标，而不是小手
任何窗体，左右，上下调整窗体大小，移动到窗体边框都是显示鼠标指针样式，而不是上下或左右箭头样式。

**Comment by wumuhappy** [comment]
登录windows资产时的确有这类现象，比如无法拖拽调整文件夹窗口大小
