### ISSUE TITLE
记录操作日志时，将sz下载文件内容同时保存到log文件中 3.2版本

### ISSUE THREAD

**Issue by NoSongmaster** [jumpserver/jumpserver#629]
你们在通过jumpserver堡垒机连接到服务器后，使用sz下载大文件，本地会同时将此文件的内容同时存储在logs/下的操作日志文件中，有什么解决的办法吗？
文件下载500M ， 日志文件就会保存500M。

**Comment by ibuler** [comment]
是的，目前存在这个问题

**Comment by ibuler** [comment]
已处理
