### ISSUE TITLE
[Question] jms更改config.txt的IP段

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#6297]
**请描述您的问题.**
更改/opt/jumpserver/config/config.txt里的docker_subnet IP段后，重启docker服务和重启服务器不生效。因为地址和内网地址冲突了，请大佬们指点一下，感谢！
另外docker服务是部署jms_core服务时脚本一键下载的，部署完成是没有docke.socket的套接文件服务的，如果是单独部署的才有。
![image](https://user-images.githubusercontent.com/46716344/122491301-4dea7100-d016-11eb-8d49-496736f1e4bc.png)

**Comment by wojiushixiaobai** [comment]
./jmsctl.sh down

**Comment by uranus829** [comment]
已解决，谢谢！

**Comment by netyjq** [comment]
> 已解决，谢谢！

@uranus829 请问是如何解决的？
