### ISSUE TITLE
[v3.0 beta] https wss支持

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#63]
需求：https wss支持
需求说明：此前https wss等硬编码到了代码中，导致 web terminal，监控，web命令等无法使用

**Comment by mrbaiwei** [comment]
我用的nginx做前端已经实现，分享下配置
url = https://jumper.xxx.com
web_socket_host = jumper.xxx.com/websocet

nginx:
`location /websocet {
		proxy_http_version 1.1;
		proxy_read_timeout 86400s;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		rewrite /websocet/(.+)$ /$1 break; 
		proxy_pass http://192.168.0.2:3000;
}`

**Comment by wptad** [comment]
一些wss的问题，在最新的代码里已经解决，我会增加相关的文档使用说明。 #88 
@mrbaiwei 感谢分享，现在的使用过程中，关于SSL方面的，如果还有什么问题，请新建ISSUE提出，感谢。
