### ISSUE TITLE
[Bug] nginx 8443配置失效

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#6300]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
Version 91.0.4472.114 (Official Build) (64-bit)

**Bug 描述**
在部署机器上查看 docker ps，对应的nginx容器无8443端口。

**Comment by wojiushixiaobai** [comment]
新版本中，需要开启USE_LB才会开启https，请参考 [反向代理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/) 文档第一条进行设置

**Comment by Laplacence** [comment]
@wojiushixiaobai 感谢，已修复。
