### ISSUE TITLE
[Bug] 无法使用rdp登陆堡垒机

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#6301]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
Version 91.0.4472.114 (Official Build) (64-bit)

**Bug 描述**
使用用户密码作为凭证，无法登录堡垒机，当前堡垒机已强制开启MFA。

**Bug 重现步骤(有截图更好)**
1. windows环境下使用mstsc
2. 使用用户名/密码 用户名/MFA 进行登录
3. 提示登陆失败

**Comment by wojiushixiaobai** [comment]
请改为手动登录方式。

**Comment by wml3** [comment]
RDP无法直接登陆jumpserver
在浏览器或者shell client登陆jumpserver

**Comment by Laplacence** [comment]
@wml3 2.11.0不是更新了？
新增XRDP组件，支持通过本地客户端直接连接资产，建立RDP等协议的图形会话【企业版】

**Comment by jym503558564** [comment]
配置文件需要配置两个参数：
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

**Comment by jym503558564** [comment]
系统设置-终端设置：RDP地址填写了吗
![image](https://user-images.githubusercontent.com/40739051/122549447-10f99b00-d065-11eb-820e-4eacf57ad448.png)

**Comment by ibuler** [comment]
企业版开放的功能

**Comment by Laplacence** [comment]
@ibuler 我这边使用的就是企业版

**Comment by Laplacence** [comment]
@jym503558564 已填写，windows资产更改为手动登陆，依旧提示no current username。
