### ISSUE TITLE
[Question] 关于上传文件时效的问题

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#6302]
请问，2.11.0版本是否有添加上传文件持久化相关开关，如果这次没有增加该功能，计划哪个版本会增加该功能。感谢！！

**Comment by ibuler** [comment]
上传文件持久化的问题，有考虑

**Comment by vzrs** [comment]
目前我在使用v2.6.1的版本，通过配置Guacamole的配置可以实现上传文件的持久化。既然Lion是Guacamole的重构也应该具备这个功能吧。实际上对于大多数运维人员而言，后台使用Lion或者Guacamole并没有实质上的区别，终端用户更是不关注，我们甚至都不知道这两者有何区别。希望大神们能尽快考虑，这样我们也能更快的加入到新版本的使用，更好的反馈使用情况。再次感谢！
