### ISSUE TITLE
[Bug] 用ssh终端直接登录jms里的资产时，使用了错误的资产用户名登录提示认证失败，但是web页面上显示会话在线

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#6303]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.0

**浏览器版本**

**Bug 描述**
用ssh终端直接登录jms里的资产时，使用了错误的资产用户名登录提示认证失败，但是web页面上显示会话在线

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by stefen-jms** [comment]
我测试使用正确的用户名和密码也提示认证失败...请问一下是什么原因

**Comment by ibuler** [comment]
@stefen-jms 马上修复一个 bug，v2.11.1，在单独设置过系统用户密码时，会出现无法登录的情况

**Comment by stefen-jms** [comment]
> @stefen-jms 马上修复一个 bug，v2.11.1，在单独设置过系统用户密码时，会出现无法登录的情况

明白

**Comment by stefen-jms** [comment]
> @stefen-jms 马上修复一个 bug，v2.11.1，在单独设置过系统用户密码时，会出现无法登录的情况

hello,升级v2.11.1后,还是有相同的问题,难道是我命令的格式不对吗?
我的命令: ssh  Jumpserver用户名@资产系统用户名@资产IP@Jumpserver IP

**Comment by ibuler** [comment]
发现这个 bug,下个小版本修复

**Comment by stefen-jms** [comment]
> 发现这个 bug,下个小版本修复

好的,谢谢

**Comment by jym503558564** [comment]
v2.11.2版本 修复

**Comment by ibuler** [comment]
@ryswork1993 麻烦 qq 群里加一下 小白 或者 我，送你个礼物
