### ISSUE TITLE
[Bug] 更新新版本不能全屏

### ISSUE THREAD

**Issue by zhangjiwei** [jumpserver/jumpserver#6304]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
91.0.4472.77

**Bug 描述**
更新到v2.11.0版本，web终端不能最大化

**Bug 重现步骤(有截图更好)**
1.  ![image](https://user-images.githubusercontent.com/859782/122508890-4edecb00-d035-11eb-9bab-891bc5af7cb3.png)
2. 
3.

**Comment by wojiushixiaobai** [comment]
什么浏览器？禁用浏览器缓存再试试

**Comment by zhangjiwei** [comment]
啥浏览器都一样，火狐、Chrome、Edge都是我截图的这个效果

**Comment by ibuler** [comment]
没有道理啊，demo 上也没有复现，锁定分辨率后，长宽比例固定了，只有有一个达到，就不会扩展了

**Comment by zhangjiwei** [comment]
更新到2.11.1，此问题依然存在，目前机器上的三种浏览器，全屏都是这个效果。
chrome 91.0.4472.77
firefox 89.0 (64 位)
Edge  91.0.864.48 

perf: 优化连接RDP会话的窗口显示（可自适应窗口）拖拽和隐藏左边栏，窗口不自动适应
perf: 优化连接RDP会话的分辨率（可手动配置）       没看到能手动配置的地方

**Comment by ibuler** [comment]
@wojiushixiaobai 远程帮处理一下看看

**Comment by zhangjiwei** [comment]
单位远程已经被限制了

**Comment by wangyu0310** [comment]
> @wojiushixiaobai 远程帮处理一下看看



> 没有道理啊，demo 上也没有复现，锁定分辨率后，长宽比例固定了，只有有一个达到，就不会扩展了

2.11.1同样的问题，而且资产窗口关闭后重新点击资产列表无响应且控制台有报错

**Comment by jym503558564** [comment]
@wangyu0310 报错贴出来一下

**Comment by jym503558564** [comment]
v2.11.3版本已修复，请更新至最新版本
