### ISSUE TITLE
我想通过调用接口更新资产的部分字段，使用patch方法，请求成功，但是字段不更新？

### ISSUE THREAD

**Issue by newertp** [jumpserver/jumpserver#6306]
我想通过调用接口更新资产的部分字段，使用patch方法，请求成功，但是字段不更新？
data = {"is_active": False}
header_info = { "Authorization": 'Bearer ' + token }
req = requests.patch('https://{}/api/v1/assets/assets/{}'.format(self.host, host_id), headers=header_info, data=data)

**Comment by ibuler** [comment]
由于你的 data 是 python 的数据结构，所以应该是 json=data，否则你需要 data=json.dumps(data)

```
req = requests.patch('https://{}/api/v1/assets/assets/{}'.format(self.host, host_id), headers=header_info, json=data)
```
