### ISSUE TITLE
[Bug] Linux-SSH直连及VScode直连中特殊字符的问题

### ISSUE THREAD

**Issue by deerjoe** [jumpserver/jumpserver#6314]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.1

**浏览器版本**
Chrome

**Bug 描述**
当用户名带有@字符时，使用jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP方式连接失败，建议采用其他字符分割

**Bug 重现步骤(有截图更好)**
1.  新建账号，用户名类似邮箱格式 deerjoe@qq.com
2. 使用jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP方式连接失败
3. 将用户名更改为无@字符，则连接成功

**Comment by jym503558564** [comment]
该需求将在后续版本进行优化，敬请期待我们后续版本发布情况。

**Comment by ibuler** [comment]
使用哪个字符是不是都有可能重复

**Comment by ibuler** [comment]
计划支持两种分割符

1. 使用 @ 如 jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP
2. 使用 # 如 jumpserverUsername#systemUsername#AssetIP@jumpserverHostIP

**Comment by deerjoe** [comment]
:作为分隔符重复的可能性会不会小一点？

**Comment by gzm55** [comment]
> :作为分隔符重复的可能性会不会小一点？

用 `~` 分割不会有冲突
