### ISSUE TITLE
[Bug] 通过Excel导入资产时填写了管理用户名称字段，导入后发现管理用户为空

### ISSUE THREAD

**Issue by zhoufanqi** [jumpserver/jumpserver#6315]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.10.3

**浏览器版本**
Chrome

**Bug 描述**
通过Excel导入资产时填写了管理用户名称字段，导入资产成功后发现管理用户为空。经测试发现需要在Excel表中的管理用户字段填入该管理用户名称对应的管理用户ID（后台数据库可查出），才可在资产导入完成后成功将管理用户导入

**Bug 重现步骤(有截图更好)**
1.  准备导入资产的Excel，管理用户和管理用户名称字段如下图
![BUG截图1](https://user-images.githubusercontent.com/85146580/122721533-5e634b80-d2a3-11eb-8091-8e4c56b7c18f.jpg)

2.导入后发现上面的资产成功与途中管理用户匹配，下面的资产没有管理用户

**Comment by jym503558564** [comment]
- 资产导入不支持填写“管理用户名称”导入

**Comment by wml3** [comment]
后续版本有可能增加支持用名称填写的方式么，另外属性字段描述不准，比如“管理用户”，用“管理用户id”是不是更准确

**Comment by jym503558564** [comment]
感谢反馈，填写管理用户id，是否导入成功。如还有其他问题，可再次提Issues
