### ISSUE TITLE
0.4.0资产管理导入导出报错

### ISSUE THREAD

**Issue by kingsxw** [jumpserver/jumpserver#632]
系统CentOS 7.3，Python 3.6.2
点击导入的下载模板或者导按钮就报错

Request Method: | GET
-- | --
http://192.168.11.11/assets/asset/export/
1.11.4
AttributeError
'NoneType' object has no attribute 'id'
/opt/jumpserver/apps/assets/views/asset.py in get, line 203
/usr/bin/python
3.6.2
['/opt/jumpserver/apps',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/root/.local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/site-packages',  '/opt/jumpserver',  '/opt/jumpserver/apps']
星期一, 21 八月 2017 10:12:38 +0800

**Comment by ibuler** [comment]
fixed
