### ISSUE TITLE
[Bug] 更新新版本后web无法打开

### ISSUE THREAD

**Issue by wcb0414** [jumpserver/jumpserver#6327]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.3

**浏览器版本**
Google Chrome  91.0.4472.114

**Bug 描述**
直接从v2.10.3 更新升级至v2.11.1后，web服务无法使用；从v2.10.4 升级至v2.11.1 没有问题。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by Lcw9054321** [comment]
![image](https://user-images.githubusercontent.com/86364716/123114160-b354bc80-d471-11eb-9c05-0cbf4d186579.png)
同問, 由2.10.4更新至2.11.1后, jms_lb这个container起不來, web服务无法使用, 有甚麽方法?

**Comment by luweijun1992** [comment]
> ![image](https://user-images.githubusercontent.com/86364716/123114160-b354bc80-d471-11eb-9c05-0cbf4d186579.png)
> 同問, 由2.10.4更新至2.11.1后, jms_lb这个container起不來, web服务无法使用, 有甚麽方法?

可以使用8080端口进行访问
![image](https://user-images.githubusercontent.com/58923704/123188096-00ff1280-d4ce-11eb-923d-a1fa46ad6e0c.png)

**Comment by Laplacence** [comment]
配置文件内启用 USE_LB=1
否则不会使用8443端口

**Comment by wcb0414** [comment]
![image](https://user-images.githubusercontent.com/81307592/123267166-4a337e80-d52f-11eb-8c9f-54fcd8ffba62.png)
![image](https://user-images.githubusercontent.com/81307592/123267233-5b7c8b00-d52f-11eb-9e5f-828b912a2dc0.png)
2.10.3升级2.11.2后，可以使用8080端口进行访问，但8443端口无法访问

**Comment by luweijun1992** [comment]
> ![image](https://user-images.githubusercontent.com/81307592/123267166-4a337e80-d52f-11eb-8c9f-54fcd8ffba62.png)
> ![image](https://user-images.githubusercontent.com/81307592/123267233-5b7c8b00-d52f-11eb-9e5f-828b912a2dc0.png)
> 2.10.3升级2.11.2后，可以使用8080端口进行访问，但8443端口无法访问

配置文件内启用 USE_LB=1
否则不会开启https/8443端口

**Comment by wojiushixiaobai** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/proxy/

```
## Nginx 配置, USE_LB=1 表示开启, 为 0 的情况下, HTTPS_PORT 定义不生效
HTTP_PORT=80
SSH_PORT=2222
RDP_PORT=3389

USE_LB=1           # 1 表示开启此选项
HTTPS_PORT=443     # 对外 https 端口
```
