### ISSUE TITLE
Linux rdp或者vnc是否支持文件上传

### ISSUE THREAD

**Issue by youpai** [jumpserver/jumpserver#6329]
**问题描述**

Ubuntu 16.04通过rdp协议管理，文件上传下载管理，没有找到如何上传下载，请问是否支持？

堡垒机版本：v2.3.1

**Comment by youpai** [comment]
是不是不支持外部copy，堡垒机内主机paste呢，文档上没有看到相关说明，测试结果是不可以

**Comment by ibuler** [comment]
vnc 协议是不支持上传下载的

**Comment by youpai** [comment]
@ibuler linux 下rdp是否支持上传下载呢，目前测试不行，官网文档提到的是window下的rdp是可以的

**Comment by jym503558564** [comment]
- 关于 ubuntu - rdp 未支持上传下载的问题，我们已验证确实存在该问题：已反馈开发人员，我们将调研一下，请持续关注我们版本的发布情况，未来版本有可能优化此问题。

**Comment by youpai** [comment]
好的，谢谢，我会保持持续关注的
