### ISSUE TITLE
[Question] 如何获取用户的密钥设置时间，并发送通知给用户来更新？

### ISSUE THREAD

**Issue by pyang30** [jumpserver/jumpserver#6330]
**请描述您的问题.**
在0.3x版本中，每过3个月，当用户登录跳板机时，会收到类似提示：密钥将在5天内过期，请到网页上更新密钥。

现在版本中是否有这个功能？

我在数据库中没有发现用户密钥的更新时间

**Comment by ibuler** [comment]
一直只有密码的有效期，没有密钥的有效期
