### ISSUE TITLE
[Bug] 升级到2.11.2 rdp 资产不能全屏

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#6332]
**JumpServer 版本(v1.5.9以下不再支持)**

version:2.11.2

**浏览器版本**
Microsoft Edge91.0.864.54
Chrome-91.0.4472.114 64位

**Bug 描述**
RDP windows7 资产不可以全屏

**Bug 重现步骤(有截图更好)**
1
![image](https://user-images.githubusercontent.com/46716344/123270933-ec089a80-d532-11eb-94d6-0fa54b1355a4.png)

2. 
3.

**Comment by netswordster** [comment]
出现同样情况，浏览器：Microsoft Edge版本 91.0.864.54 
![image](https://user-images.githubusercontent.com/60777831/123392591-cc737f80-d5cf-11eb-873e-01d51d21844e.png)

**Comment by ibuler** [comment]
今天会发布一下 fix 版本

**Comment by jym503558564** [comment]
v2.11.3已修复，请更新至最新版本进行测试。
