### ISSUE TITLE
[Bug] RDP连接，全屏后显示有问题

### ISSUE THREAD

**Issue by Lancelot380** [jumpserver/jumpserver#6335]
**JumpServer 版本(v1.5.9以下不再支持)**
Jumpserver v2.11.2

**浏览器版本**
Chrome 91.0.4472.114
Firefox 89.0.2

**操作系统**
Windows Server 2008 R2

**Bug 描述**
全屏后显示如图，不能完整显示

![image](https://user-images.githubusercontent.com/49552264/123395791-2cb7f080-d5d3-11eb-9232-7013f6723857.png)

**Comment by jym503558564** [comment]
- 无法复现
![image](https://user-images.githubusercontent.com/40739051/123569923-d37dd600-d7f9-11eb-99ee-2730ae79c2f0.png)

**Comment by jym503558564** [comment]
v2.11.3版本已修复，请关注我们的版本发布情况，进行升级。
