### ISSUE TITLE
[Bug] 下载文件超过1G时，提示 cannot open file

### ISSUE THREAD

**Issue by dmanbu** [jumpserver/jumpserver#6337]
koko 版本 v2.1.0
在通过sftp下载文件超过1G时，提示 cannot open file ，无法下载
看了下配置，只有一个 ZIP_MAX_SIZE 跟大小相关的参数，尝试调整到了 2048M ，但依然不行
请问怎么回事？

**Comment by dmanbu** [comment]
koko 日志提示：Download file err: sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
但我下载同一个服务器的其他小文件是没有问题的

**Comment by LeeEirc** [comment]
资产上，登陆使用的系统用户对该大文件是否有权限。另外使用最新的版本测试一下。

**Comment by dmanbu** [comment]
> 资产上，登陆使用的系统用户对该大文件是否有权限。另外使用最新的版本测试一下。

这个大文件和其他小文件的权限是一样的

**Comment by LeeEirc** [comment]
从日志角度看，是文件权限问题。有没有 waf 等中间层设备拦截。

**Comment by dmanbu** [comment]
没有中间设备，直接访问的，把这个大文件拆成小文件就没有问题

**Comment by dmanbu** [comment]
> 从日志角度看，是文件权限问题。有没有 waf 等中间层设备拦截。

没有中间设备，直接访问的，把这个大文件拆成小文件就没有问题

**Comment by dmanbu** [comment]
> > 从日志角度看，是文件权限问题。有没有 waf 等中间层设备拦截。
> 
> 没有中间设备，直接访问的，把这个大文件拆成小文件就没有问题

我再次检查了一遍，应该是文件权限的问题

**Comment by jym503558564** [comment]
@dmanbu 该问题现在还存在吗

**Comment by dmanbu** [comment]
> @dmanbu 该问题现在还存在吗

已经没问题了，确实是文件权限的问题，我这边jumpserver连服务器是一个有限权限的账号，而文件是一个只有root用户能访问文件，我之前一直以为是Jumpserver权限配置的问题

**Comment by jym503558564** [comment]
好的，如还有其他问题，可再次提Issues。感谢持续关注并使用JumpServer～
