### ISSUE TITLE
jumpserver v0.3.2 无外网怎么安装

### ISSUE THREAD

**Issue by lichenglongqi** [jumpserver/jumpserver#634]
请问Redhat Linux 7.x 的系统，不能访问外网，怎么用本地包安装啊，就是把包都下载到本地，然后pip install ，有没有这方面的文档啊

**Comment by hellorocky** [comment]
pip依赖太多, 没办法不联网安装所有python依赖

**Comment by lichenglongqi** [comment]
没办法将所有的pip包都下载下来后，然后再安装么？  我感觉这个方法还可以，麻烦帮看看   http://jude90.github.io/2015/09/30/pip-from-dir.html

**Comment by zsjohny** [comment]
@hellorocky   pip  wheel 先把包保存本地 ，然后在安

**Comment by hellorocky** [comment]
我的意思是安装pip依赖的时候会涉及很多系统的包

**Comment by lichenglongqi** [comment]
@hellorocky 我找到怎么无外网安装jumpserver v3.0.2了，写个篇博客，方便后来人吧http://blog.csdn.net/baidu_35635926/article/details/77509034

**Comment by hellorocky** [comment]
赞, 666
