### ISSUE TITLE
添加用户、资产页面的「保存继续添加」按钮执行后，应该清空当前页面的信息

### ISSUE THREAD

**Issue by Andyguo5891** [jumpserver/jumpserver#6342]
**请描述您的需求或者改进建议.**
添加用户、资产页面的「保存继续添加」按钮执行后，完整的保留了上一个添加的用户、资产信息，让人感觉不确定是否点击了这个按钮，另外在更新的时候也很容易遗漏，建议点击「保存继续添加」后清空当前页面的信息。

**Comment by ibuler** [comment]
这样其实也不好，因为好多是重复的，用户可以少填写很多
