### ISSUE TITLE
[help] Publish jms_mysql port 3306

### ISSUE THREAD

**Issue by elemeguweijie** [jumpserver/jumpserver#6344]
我使用 "curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.11.2/quick_start.sh | bash" 快速自动部署，现在想对mysql进行高可用，但是发现无法将jms_mysql的3306端口映射至服务器3306端口，望大神们指点~谢谢！

**Comment by wojiushixiaobai** [comment]
```
compose/docker-compose-mysql.yml
```
里面添加外置的端口
