### ISSUE TITLE
4.0 从github的dev还是master分支下载

### ISSUE THREAD

**Issue by kexl** [jumpserver/jumpserver#635]
github上master和dev分支是不一样的  master没有requirements 。安装步骤就不一样了。dev是没有上传下载的是不是还有一些功能没有开发完。
那么现在用哪个分支比较好！！ 谢谢

要是安装3.2版本是不是在tag地方切换到3.2 就可以了

**Comment by hellorocky** [comment]
dev是0.4, master是0.32

**Comment by kexl** [comment]
0.4的目前还没有开发完么 稳定版0.32？？

**Comment by hellorocky** [comment]
master分支是稳定版, 但是使用的python, django等比较旧, 不利于二次开发, 如果打算二次开发的话建议使用0.4版本, 而且0.4版本采用全新的架构, 值得花时间研究

**Comment by kexl** [comment]
我部署了两次 
0.4的  dev分支 没有上传下载的功能 其他的看起来没有问题
0.32的 就是从master分支拉下来的  新建个账户页面就卡住了  悲剧了

**Comment by ibuler** [comment]
新建用户卡住可能是 发送邮件卡住了
