### ISSUE TITLE
[Question] v2.11.2 docker-compose文件疑问

### ISSUE THREAD

**Issue by gunaiqiu** [jumpserver/jumpserver#6351]
系统:CentOS7
环境描述：
全新安装jumpserver
docker 安装完成
所有依赖包pull完毕

错误说明：
通过quick_start.sh进行初始化数据库步骤时，提示docker-compose文件出错。
经确认，所有的yml文件里面版本都对，是2.4。

————————————————告警信息开始————————————————
7. 初始化数据库
ERROR: Version in "././compose/docker-compose-redis.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
/usr/bin/docker-current: Error response from daemon: network jms_net not found.

ERROR: Version in "././compose/docker-compose-redis.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

[ERROR] 表结构变更失败!
————————————————告警信息结束————————————————

**Comment by wojiushixiaobai** [comment]
compose bug，请更新compose版本或者使用脚本自带的版本

**Comment by gunaiqiu** [comment]
通过脚本安装docker-ce配合最新版本的docker-compose已解决。
