### ISSUE TITLE
添加系统用户vnc后，发现web终端登录时无法使用，发现找不到该系统用户

### ISSUE THREAD

**Issue by xs9716** [jumpserver/jumpserver#6352]
**请描述您的问题.**
我使用的是社区版2.11.2，我在资产管理里面添加一个VNC系统用户,并通过权限管理对系统用户、用户和资产进行关联。让后通过web终端去登录该资产，提示无系统用户。
![image](https://user-images.githubusercontent.com/49193075/123753076-099b8280-d8ec-11eb-9f18-c9b990df58e3.png)
![image](https://user-images.githubusercontent.com/49193075/123753114-10c29080-d8ec-11eb-9be0-2f402b3b3316.png)
![image](https://user-images.githubusercontent.com/49193075/123753141-18823500-d8ec-11eb-92d9-626eac4d3f19.png)

**Comment by wojiushixiaobai** [comment]
确定资产和系统用户的协议一致
