### ISSUE TITLE
使用jms_all容器镜像部署咨询

### ISSUE THREAD

**Issue by Swireb** [jumpserver/jumpserver#6359]
**请描述您的问题.**
您好，请问我想通过`docker`的方法部署`jms_all:v2.7.1`和`jms_all:v2.11.3`的两个镜像有什么区别？

**Comment by Swireb** [comment]
**我部署`v2.7.1`的版本使用如下参数，部署`v2.11.3`需要更改哪些地方？**
docker run --name jms_all -d \
  --restart=always \
  -p 80:80 -p 2222:2222 \
  -e SECRET_KEY=$SECRET_KEY \
  -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
  -e DB_USER=jumpserver \
  -e DB_PASSWORD=jumpserver \
  -e DB_NAME=jumpserver \
  -v /opt/jumpserver/data:/opt/jumpserver/data \
  -v /opt/jumpserver/mysql:/var/lib/mysql \
  jumpserver/jms_all:v2.7.1

**Comment by wojiushixiaobai** [comment]
- link: [Dockerfile](https://github.com/jumpserver/Dockerfile/tree/master/allinone)
