### ISSUE TITLE
Xshell 6 连接堡垒机 g显示您有权限的节点目录树与实际目录结构不符[Bug] 

### ISSUE THREAD

**Issue by apxx-xqy** [jumpserver/jumpserver#6360]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.3

**浏览器版本**

**Bug 描述**
Xshell 6 连接堡垒机 g显示您有权限的节点目录树与实际目录结构不符

**Bug 重现步骤(有截图更好)**
4) 输入 g 进行显示您有权限的节点.
![image](https://user-images.githubusercontent.com/78672357/123901343-5723f800-d99d-11eb-8084-cc5a4e733898.png)
![image](https://user-images.githubusercontent.com/78672357/123901352-5b501580-d99d-11eb-9a06-8b697b25c427.png)

实际节点目录结构
![image](https://user-images.githubusercontent.com/78672357/123901229-280d8680-d99d-11eb-97cc-003d02afa337.png)
![image](https://user-images.githubusercontent.com/78672357/123901242-2e9bfe00-d99d-11eb-8e22-ea628cafabfa.png)

**Comment by LeeEirc** [comment]
从数据库里查看下 node 的key的值。
```shell
cd apps
python manage.py shell
```

```python
from assets.models import Node
for item in Node.objects.all():
    print(item.key, item.value)

```

**Comment by jym503558564** [comment]
v2.12.1 优化了资产节点树排序乱序问题，现实更加友好。请更新至最新版本进行体验。
