### ISSUE TITLE
[Bug] 企业版 应用授权可以通过web快捷键绕过

### ISSUE THREAD

**Issue by 111234567890** [jumpserver/jumpserver#6362]
新版本web页面有快捷键 使用快捷键 Ctrl+Alt+Delete 可以唤出任务管理器，从而打开资源管理器 绕过应用的限制。打开机器自带的别的应用。

**Comment by wojiushixiaobai** [comment]
目前没有太好的办法处理，这是 remoteapp 本身就存在的问题
