### ISSUE TITLE
[Bug] Jmservisor无法使用

### ISSUE THREAD

**Issue by 111234567890** [jumpserver/jumpserver#6363]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.1

**浏览器版本**

chrome 最新版
**Bug 描述**
使用最新的V0.2.3的Jmservisor，远程连上应用会直接黑屏 无法唤醒应用。回退到V0.2.2版本的Jmservisor使用即正常。

**Comment by wojiushixiaobai** [comment]
重新上传了下，你试试
