### ISSUE TITLE
【企业级】Jumpserver通过OmniDB连Oracle中文显示乱码

### ISSUE THREAD

**Issue by 2han9we1** [jumpserver/jumpserver#6364]
**请描述您的问题.**
Jumpserver通过OmniDB连Oracle中文显示乱码，此问题如何处理？
目前访问英文、中文简体、中文繁体、西班牙语等语言。
![image](https://user-images.githubusercontent.com/31976699/123940571-e47e4100-d9cb-11eb-9828-6fb3b54702ea.png)

**Comment by wojiushixiaobai** [comment]
测试下新版本看问题是否解决
