### ISSUE TITLE
邮件测试bug

### ISSUE THREAD

**Issue by pangchaocheng** [jumpserver/jumpserver#6373]
![image](https://user-images.githubusercontent.com/35793030/124342857-b8480780-dbf9-11eb-96fb-b2c1a593fbb4.png)

前端bug：
1. TSL  SSL  选项不选，就默认传NULL ，后端不允许为NULL。勾选一次，再取消勾选，就可以传false值。
2. 发件人没有默认值。
3. 以上异常，前端没有弹窗提示，只有控制台有异常信息。

后端日志：
2021-07-03 11:56:30 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/settings/api/common.py", line 29, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'EMAIL_USE_SSL': [ErrorDetail(string='该字段不能为 null。', code='null')], 'EMAIL_USE_TLS': [ErrorDetail(string='该字段不能为 null。', code='null')]}

这个问题最新版2.11.3和前几个版本都存在。

**Comment by jym503558564** [comment]
- 我们提示文字已经告诉您，根据您的设置需要自行开启SSL或 TLS
![image](https://user-images.githubusercontent.com/40739051/126585167-f2d789d2-0525-4674-9b44-8f30fe8ffba9.png)

- 关于发送人，提示信息也告诉您：发送邮件账号，默认使用 SMTP 账号作为发送账号。
![image](https://user-images.githubusercontent.com/40739051/126585252-3de09b88-89f5-4935-81bd-2b9da6a862df.png)
