### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by xiaoyaolaotou** [jumpserver/jumpserver#6375]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/23049347/124350228-083cc380-dc26-11eb-942f-01f59b2ef875.png)
显示添加的资产无法连接， 不知什么原因， 管理帐号和密码也是正确的。

**Comment by Adwinsw** [comment]
windows资产ansible并不能直接管理，得是windows2012R2及以上的版本或者更新过powershell4.0才行，不过不影响你远程控制的吧，最新版本没用过，之前版本不影响登陆的

**Comment by xiaoyaolaotou** [comment]
不是windows，&nbsp;是Linux




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月3日(星期六) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Question]  (#6375)





 
windows资产ansible并不能直接管理，得是windows2012R2及以上的版本或者更新过powershell4.0才行，不过不影响你远程控制的吧，最新版本没用过，之前版本不影响登陆的

**Comment by wojiushixiaobai** [comment]
导入的资产当前策略是这样，手动创建的资产才会进行检测
