### ISSUE TITLE
[Bug] 2.11.1 未激活资产，在SSH可以检查到

### ISSUE THREAD

**Issue by Coylexiao** [jumpserver/jumpserver#6377]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
当前使用版本为V2.11.1，资产激活状态改为关闭后，在ssh登陆堡垒机，还能检索到未激活的资产。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
可以监测到未激活资产，但是连接时会提示：该资产已禁用

**Comment by Coylexiao** [comment]
你好，我是从以前的低版本升到2.11.1版的，以前的版本未激活的资产是不会检索到的（通过ssh），因为我们有大量资产会更新为未激活，同时后续又可能再使用，需要激活，
如果未激活资产也显示在ssh的检索页面，会不方便 我们直接使用。
是否可以增加全局全关，让未激活资产不显示到ssh的检索页中。。。




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jul 5, 2021 02:25 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [jumpserver/jumpserver] [Bug] 2.11.1 未激活资产，在SSH可以检查到 (#6377)





 
可以监测到未激活资产，但是连接时会提示：该资产已禁用
