### ISSUE TITLE
[Question]  ssh登陆的【日志审计】的登陆日志、【会话管理】等的远端地址无法记录真户客户端IP

### ISSUE THREAD

**Issue by Coylexiao** [jumpserver/jumpserver#6378]
**请描述您的问题.**
负载均衡部署方式，通过ssh登陆的【日志审计】的登陆日志、【会话管理】等的远端地址显示为入口负载均衡器的IP，无法有效记录真实客户端的登陆IP。
我已在两台core web 的nginx 4层代理中去掉了上一层的负载均衡器的IP。
core web nginx4层配置如下：

upstream ssh_server {
    server koko:2222;
    # server HOST2:2222;
}

server {
    listen 2222;
    proxy_pass  ssh_server;
    proxy_protocol on;
    set_real_ip_from 10.83.0.0/24;  ## 入口负载均衡器网段
    proxy_connect_timeout 30s;

**Comment by wojiushixiaobai** [comment]
关闭 ipv6，ipv6 nat 无法获取真实 ip 问题请向 docker 官方提交 issue
非 ipv6 导致的，请仔细检查中间件，从 nginx 日志里面查看是否上层可以把真实的后端 ip 传递过来
