### ISSUE TITLE
ansible docker接入跳板机无法推送用户

### ISSUE THREAD

**Issue by guoyinzhao** [jumpserver/jumpserver#638]
Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1503392205.16-46743311566194 && echo $HOME/.ansible/tmp/ansible-tmp-1503392205.16-46743311566194, exited with result 254

**Comment by guoyinzhao** [comment]
已解决，ansible远程推送问题，因为没自动生成/etc/ansible的配置文件目录，手动创建了放上去的，在配置文件中变更的临时文件目录为/tmp，回避推送用户时的权限报错。

**Comment by ibuler** [comment]
描述一下你的系统版本，我没有遇到该问题
