### ISSUE TITLE
[Bug] Session duration in chinese

### ISSUE THREAD

**Issue by dbrifox** [jumpserver/jumpserver#6381]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.3

**浏览器版本**
Chrome 91

**Bug 描述**
Session duration is displayed in chinese even when english is selected as display language

**Bug 重现步骤(有截图更好)**
![jump_cn](https://user-images.githubusercontent.com/71386189/124463452-4abae900-dd69-11eb-981e-f07fce9c9ed0.JPG)

**Comment by wojiushixiaobai** [comment]
Thank you for feedback. We have received it.

**Comment by dbrifox** [comment]
Issue still exists on 2.12.1
