### ISSUE TITLE
如何通过vscode连接jumpserver? 目标资产默认终端为Fish Shell时,连接失败

### ISSUE THREAD

**Issue by gssjl2008** [jumpserver/jumpserver#6384]
**请描述您的问题.**
刚看到提示说jumpserver支持vscode，找了半天没有找到方法，请大佬指点下

**Comment by jym503558564** [comment]
配置文件：
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

vscode 下载插件：remote-ssh
- 直接编辑ssh配置文件，如: vim .ssh/config
![image](https://user-images.githubusercontent.com/40739051/124561625-af14a000-de70-11eb-8786-517ad122b357.png)
- 然后连接，输入用户密码即可

**Comment by gssjl2008** [comment]
> 配置文件：
> ENABLE_LOCAL_PORT_FORWARD=true
> ENABLE_VSCODE_SUPPORT=true
> 
> vscode 下载插件：remote-ssh
> 
> * 直接编辑ssh配置文件，如: vim .ssh/config
>   ![image](https://user-images.githubusercontent.com/40739051/124561625-af14a000-de70-11eb-8786-517ad122b357.png)
> * 然后连接，输入用户密码即可

多谢，容我尝试一番，谢谢🙏

**Comment by jym503558564** [comment]
@gssjl2008 如果你是windows 下的vscode，得稍等下，等会儿发新包，即可支持windows 下的vscode

**Comment by gssjl2008** [comment]
> @gssjl2008 如果你是windows 下的vscode，得稍等下，等会儿发新包，即可支持windows 下的vscode

谢谢，我的是mac的，
请教下

ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

这2个具体配置位置？

**Comment by jym503558564** [comment]
vi /opt/jumpserver/config/config.txt

**Comment by gssjl2008** [comment]
我添加了 /opt/jumpserver/config 目录并添加 config.txt，
使用vscode remote ssh 连接仍然提示 No PTY requested.

![image](https://user-images.githubusercontent.com/43020699/124566618-cdc96580-de75-11eb-8eb1-3fbcb599b58d.png)

**Comment by jym503558564** [comment]
系统用户需要匹配唯一的，且该系统用户自动登录的，连接的资产也是需要匹配唯一

**Comment by jym503558564** [comment]
配置文件配置后，也是需要重启一下服务。

**Comment by gssjl2008** [comment]
我用ssh jumserveruser@systemuser@assetip@jumpserverIp 能够进入，使用vscode 就不行

**Comment by rty813** [comment]
@jym503558564 升级了2.11.4，也是报no pty requested。
![image](https://user-images.githubusercontent.com/22488813/124694408-c789c680-df13-11eb-884b-d63c2ec8f6db.png)

**Comment by jym503558564** [comment]
- 系统用户需匹配唯一
- 系统用户需自动登录
- 资产需匹配唯一

**Comment by gssjl2008** [comment]
> * 配置参数设置好后，需重启服务。
> * 系统用户需匹配唯一
> * 系统用户需自动登录
> * 资产需匹配唯一
> 
> @gssjl2008 @rty813 以上条件均满足吗？

是的， 
配置文件 /opt/jumpserver/config/config.txt 没错
通过命令行 ssh jumpserverUser@systemUser@assetsIp@jumpserverIp  可以成功登入，

**Comment by rty813** [comment]
> * 配置参数设置好后，需重启服务。
> * 系统用户需匹配唯一
> * 系统用户需自动登录
> * 资产需匹配唯一
> 
> @gssjl2008 @rty813 以上条件均满足吗？

1. 重启过：
![image](https://user-images.githubusercontent.com/22488813/124729117-c0c67800-df42-11eb-96ef-2307a95011aa.png)
2. 
![image](https://user-images.githubusercontent.com/22488813/124729283-e0f63700-df42-11eb-9668-8bebda313fa6.png)
3. 
![image](https://user-images.githubusercontent.com/22488813/124729323-ed7a8f80-df42-11eb-860f-f9cd64a39a1a.png)
4. 
![image](https://user-images.githubusercontent.com/22488813/124729399-fcf9d880-df42-11eb-90fc-36dc555a16d3.png)


补充：通过ssh直连是ok的，如下图：
![image](https://user-images.githubusercontent.com/22488813/124729499-126f0280-df43-11eb-8119-e594d8ae86df.png)

**Comment by rty813** [comment]
我又重新测试了一次，现在可以了。但是有一个bug，就是：如果我的目标主机的默认shell是bash的话，是没有问题的，可以远程链接，
但是如果我的目标主机的默认shell是fish的话，就不可以，就会卡在这个地方：
![image](https://user-images.githubusercontent.com/22488813/124846958-7c7fba00-dfcc-11eb-8cdb-80326770d0c6.png)

---
也就是说，它实际上已经登陆进去了，但是不知道为什么会卡在这里。下面这个图是ssh直连的输出：
![image](https://user-images.githubusercontent.com/22488813/124846967-81446e00-dfcc-11eb-804a-a3e035fc521a.png)

**Comment by LeeEirc** [comment]
对于表现不一样的现象，建议使用 vscode 直接连接资产对比。

**Comment by rty813** [comment]
> 对于表现不一样的现象，建议使用 vscode 直接连接资产对比。

默认终端是fish的情况，上面的截图里面已经说了。
下图是默认终端为bash的情况：
![image](https://user-images.githubusercontent.com/22488813/125011200-8d96fc80-e09a-11eb-9885-20794aaeaf13.png)

**Comment by LeeEirc** [comment]
> > 对于表现不一样的现象，建议使用 vscode 直接连接资产对比。
> 
> @LeeEirc 默认终端是fish的情况，上面的截图里面已经说了。
> 下图是默认终端为bash的情况：
> ![image](https://user-images.githubusercontent.com/22488813/125011200-8d96fc80-e09a-11eb-9885-20794aaeaf13.png)
> 最终可以正常连接。

VSCODE 不通过 koko，直接连接资产看看。

**Comment by rty813** [comment]
> > > 对于表现不一样的现象，建议使用 vscode 直接连接资产对比。
> > 
> > 
> > @LeeEirc 默认终端是fish的情况，上面的截图里面已经说了。
> > 下图是默认终端为bash的情况：
> > ![image](https://user-images.githubusercontent.com/22488813/125011200-8d96fc80-e09a-11eb-9885-20794aaeaf13.png)
> > 最终可以正常连接。
> 
> VSCODE 不通过 koko，直接连接资产看看。

vscode直连没有问题。
![image](https://user-images.githubusercontent.com/22488813/125227199-039e9c00-e305-11eb-8860-22443e572c69.png)

**Comment by gssjl2008** [comment]
我尝试了很多次，仍然不成功，我使用k8s安装的jumpserver，在内部添加
<img width="598" alt="image" src="https://user-images.githubusercontent.com/43020699/127736237-ae75f2f1-c030-4f20-95bd-c2137918d08c.png">
./jms restart 无法生效，有更好的方法吗？

**Comment by jym503558564** [comment]
@gssjl2008 您使用什么部署方式？
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true
加到容器的环境变量里面

**Comment by technologynongmin** [comment]
> @gssjl2008 您使用什么部署方式？
> ENABLE_LOCAL_PORT_FORWARD=true
> ENABLE_VSCODE_SUPPORT=true
> 加到容器的环境变量里面

是需要重新构建镜像么？k8s安装好想没有config目录

**Comment by technologynongmin** [comment]
已经解决可以连接成功

**Comment by Laplacence** [comment]
我阅读了上述的操作后，配置了
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

```
Host jumpserver
  HostName x.x.x.x
  Port 2222
  User user@sysuser@10.x.x.x
```

但是依旧无法使用vsc登陆到远程服务器。
是不是和我启用了全局OTP有关？

**Comment by weitianyuan** [comment]
通过vscode 远程登录，从跳板机登录资产 ，输入完 MFA auth 报这个错误怎么解决的呀 
No PTY requested.
[01:30:11.568] "install" terminal command done
[01:30:11.568] Install terminal quit with output: No PTY requested.
