### ISSUE TITLE
[Bug] /var/log/message 会产生很多Removed slice User日志

### ISSUE THREAD

**Issue by Coylexiao** [jumpserver/jumpserver#6386]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer 版本 V2.11.1

**浏览器版本**

**Bug 描述**
自从升级到v2.11.1后，发现/var/log/message 会产生很多下面的日志

Jul  3 23:04:25 jumpserver systemd: Removed slice User Slice of ops.
Jul  3 23:04:25 jumpserver systemd: Created slice User Slice of ops.
Jul  3 23:04:25 jumpserver systemd: Started Session 12679 of user ops.
Jul  3 23:04:25 jumpserver systemd-logind: New session 12679 of user ops.
Jul  3 23:04:25 jumpserver systemd-logind: Removed session 12679.

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by kingsxw** [comment]
echo 'if $programname == "systemd" and ($msg contains "Starting Session" or $msg contains "Started Session" or $msg contains "Created slice" or $msg contains "Starting user-" or $msg contains "Starting User Slice of" or $msg contains "Removed session" or $msg contains "Removed slice User Slice of" or $msg contains "Stopping User Slice of") then stop' >/etc/rsyslog.d/ignore-systemd-session-slice.conf
