### ISSUE TITLE
[Bug] MySQL应用无法输入中文

### ISSUE THREAD

**Issue by it-liwow** [jumpserver/jumpserver#6387]
**JumpServer 版本(v1.5.9以下不再支持)**
**浏览器版本**
 Edge 版本 91.0.864.59 
Google Chrome   版本 90.0.4430.93

 容器镜像：jumpserver/jms_all:latest  版本：2.11.3

**Bug 描述**
终端，wab页面MySQL应用，在查询语句，update语句，insert语句 时，如果带有中文字体，会被强制替换为----- 乱码。
只有完全无中文的SQL 才可正常，显示和执行。

**Bug 重现步骤(有截图更好)**
原始预期输入：
MySQL [test]> select '中文';
    ->
    ->
    ->
    ->
    ->
    -> select '测试';

输入后回车显示：
MySQL [test]> select '--------
    '> select '--------
    ->
    ->
    ->
    ->
    ->
    -> select ''
    -> select '--------

**Comment by jym503558564** [comment]
无法复现。。请截图看一下情况
![image](https://user-images.githubusercontent.com/40739051/124689633-6eb63000-df0b-11eb-9d70-4a1802a928f3.png)
![image](https://user-images.githubusercontent.com/40739051/124689664-7675d480-df0b-11eb-9fb2-5bcaaf46dba7.png)

**Comment by it-liwow** [comment]
你好，我这边是用的1.5.3版本 逐步升级到  版本：2.11.3  ，用的是docker 容器集成版本 （jumpserver/jms_all:latest ）
很抱歉，我没找到上传图片的地方。我准备完全重装测试下，是否是容器版或 因升级数据冲突引起。

**Comment by jym503558564** [comment]
@it-liwow 重装之后问题有得到解决吗

**Comment by it-liwow** [comment]
删除数据库，清空Redis。  重新拉取最新2.11.4 jumpserver/jms_all:latest 镜像，
依然无法显示中文，无论是web还是在CRT终端登录。在镜像使用mysql客户端连接显示正常。

测试SQL如下：
DROP TABLE IF EXISTS `temp`;

CREATE TABLE `temp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tablename` varchar(255) DEFAULT NULL,
  `LieName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


INSERT INTO `temp` VALUES ('1', '中文', '测试');
INSERT INTO `temp` VALUES ('2', '测试', '测试');


select * from temp where tablename='中文'  and LieName='测试';
web页面
![1](https://user-images.githubusercontent.com/47592525/124710230-1133da80-df2f-11eb-8f85-f6e64c9531e6.png)
CRT终端：
![终端测试](https://user-images.githubusercontent.com/47592525/124710272-1db83300-df2f-11eb-93ce-9ac0981b8b29.png)

docker 容器中：
![3](https://user-images.githubusercontent.com/47592525/124710928-075ea700-df30-11eb-8ea7-f54ca5c80352.png)

**Comment by wojiushixiaobai** [comment]
```mysql
show variables like '%character%';
```
检查下

**Comment by it-liwow** [comment]
- 通过jump登录主机（/p），命令进入MySQL看到字符集如下：

| character_set_client     | utf8                             |
| character_set_connection | utf8                             |
| character_set_database   | utf8                             |
| character_set_filesystem | binary                           |
| character_set_results    | utf8                             |
| character_set_server     | utf8                             |
| character_set_system     | utf8                             |
| character_sets_dir       | /usr/local/mysql/share/charsets/ |

- 通过jump 应用授权（/d）,进入查询字符集如下：

| character_set_client     | utf8mb4                          |
| character_set_connection | utf8mb4                          |
| character_set_database   | utf8                             |
| character_set_filesystem | binary                           |
| character_set_results    | utf8mb4                          |
| character_set_server     | utf8                             |
| character_set_system     | utf8                             |
| character_sets_dir       | /usr/local/mysql/share/charsets/ |

两者显示字符集不一致。通过/d  登录数据库 ，查询的字符集  character_set_server     是utf8 不是 latin1 ， 和这个有关系吗？ 能提供下，测试的版本吗？ 是docker镜像，还是手动安装的版本？ 我想和您 使用同一个版本测试下。

**Comment by wojiushixiaobai** [comment]
我是 jumpserver/jms_all:v2.11.4

**Comment by it-liwow** [comment]
经过多次测试验证。使用jumpserver/jms_all:latest 镜像会存在  中文乱码问题。 下载单个镜像，使用jmsctl.sh 脚本安装则可正常显示。
如下：
![8](https://user-images.githubusercontent.com/47592525/124743526-6af8cc80-df50-11eb-954a-f31e6cf4c3ea.png)
效果如下：
![9](https://user-images.githubusercontent.com/47592525/124743622-7ba94280-df50-11eb-8029-fdb5d8f7473f.png)

**Comment by yangyanqing** [comment]
> 经过多次测试验证。使用jumpserver/jms_all:latest 镜像会存在 中文乱码问题。 下载单个镜像，使用jmsctl.sh 脚本安装则可正常显示。 

兄弟，最终用哪个版本解决的？ 我 v2.14.2 也有这个问题 @it-liwow

**Comment by yangyanqing** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/7357939/184864356-36522e2b-c1c3-4c76-8d83-453b818b55c9.png">
升级到最新的 v2.24.2 还是有这个问题，包括给 jumpserver-all 增加了环境变量 LANG=C.UTF-8
在容器内使用 mysql shell 是能输入中文的
<img width="562" alt="image" src="https://user-images.githubusercontent.com/7357939/184865225-8a8eb146-4fda-4af1-ad23-312605fc5faf.png">

**Comment by MCwrc** [comment]
docker版本 v2.23.2，再koko中设置变量LANG=zh_CN.UTF-8后，同样还是无无法输入中文字符！
![Uploading image.png…]()
