### ISSUE TITLE
docker安装报错循环

### ISSUE THREAD

**Issue by lyjason** [jumpserver/jumpserver#639]
coco          | WARNING:/opt/coco/coco/service.py:App auth failed, Access key error or need admin active it
jumpserver    | 2017-08-23 14:40:10 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it

**Comment by hellorocky** [comment]
https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F 看文档
