### ISSUE TITLE
[Bug] web终端经常断掉

### ISSUE THREAD

**Issue by zhangjiwei** [jumpserver/jumpserver#6391]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.3

**浏览器版本**
Google Chrome 已是最新版本
版本 91.0.4472.124（正式版本） （64 位）

**Bug 描述**
web终端再使用过程中频繁断掉，提示About See logs。希望能解决一下。谢谢

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/859782/124712764-4f7ec900-df32-11eb-84fb-b8de5b6061da.png)

2. 
3.

**Comment by jym503558564** [comment]
截图一下lion日志

**Comment by zhangjiwei** [comment]
![image](https://user-images.githubusercontent.com/859782/124713942-c1a3dd80-df33-11eb-958c-eba6cf8d1979.png)

**Comment by jym503558564** [comment]
https://help.aliyun.com/document_detail/40885.html
尝试一下把会话连接数设置大一点

**Comment by zhangjiwei** [comment]
应该和连接数没关系，是web client read err: websocket: close 1005 (no status)这个断掉了
![image](https://user-images.githubusercontent.com/859782/124871651-ddbc8300-dff6-11eb-8707-5b93e5676574.png)

**Comment by wojiushixiaobai** [comment]
单独的反向代理或者slb请注意websocket和哈希一致性

**Comment by LeeEirc** [comment]
可能是网络等问题，造成 guacd 的服务无法正常连接。如果升级版本还存在，可以新开issue。
