### ISSUE TITLE
[Bug] 2.9.2版本，telnet交换机，disp命令打印出现中文卡死

### ISSUE THREAD

**Issue by Adwinsw** [jumpserver/jumpserver#6392]
**JumpServer 版本(v1.5.9以下不再支持)**
如题描述，使用telnet协议命令到交换机，disp cu命令打印时，终端会卡死在中文字符处

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
使用新版本v2.11.4试一下。

**Comment by Adwinsw** [comment]
> 使用新版本v2.11.4试一下。

新版本不会卡死，但是识别是乱码，交换机是H3C的，也无法使用键盘键backspace

**Comment by LeeEirc** [comment]
![image](https://user-images.githubusercontent.com/32626707/124855196-2fefab00-dfdb-11eb-9ae4-c8c292f1bd23.png)
更改资产的平台字符设置，可显示中文。

**Comment by Adwinsw** [comment]
> ![image](https://user-images.githubusercontent.com/32626707/124855196-2fefab00-dfdb-11eb-9ae4-c8c292f1bd23.png)
> 更改资产的平台字符设置，可显示中文。

确实可以，感谢帮助

**Comment by Adwinsw** [comment]
solved
