### ISSUE TITLE
[Bug] V2.11.3 远程ssh登录linux服务器的时候报错：error: ssh: handshake failed: ssh: not enough answers from keyboard-interactive callback

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#6395]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.3

**浏览器版本**

Google Chrome 已是最新版本
版本 91.0.4472.124（正式版本） （64 位）

**Bug 描述**
SSH登录Linux服务器的时候出现error: ssh: handshake failed: ssh: not enough answers from keyboard-interactive callback，升级到2.11.3之前都是可以正常登录服务器的。

**Bug 重现步骤(有截图更好)**
1.默认用xshell去连这个linux服务器的时候默认是会弹出来这个“public key” 我手动切换为“keyboard interacite”然后输入密码是可以正常登录服务器的。
![image](https://user-images.githubusercontent.com/28044296/124856150-9aedb180-dfdc-11eb-854f-d185a566369f.png)
  但是之前用堡垒机去连这台服务器都是可以正常登录的，但是升级到2.11.3版本之后就连不上了，报错信息如下，是否是这个版本对ssh登录有过优化？
2.
3. 
![image](https://user-images.githubusercontent.com/28044296/124846467-73dab400-dfcb-11eb-9edb-934538174fa1.png)

**Comment by LeeEirc** [comment]
不支持资产使用 keyboard interacite的认证。可能你服务器修改了配置，修改sshd config配置，允许 password 认证。

**Comment by aiaiduo** [comment]
> 不支持资产使用 keyboard interacite的认证。可能你服务器修改了配置，修改sshd config配置，允许 password 认证。

已解决，我修改了/etc/ssh/sshd_config  将PasswordAuthentication no中的no改为yes就可以了，多谢！
