### ISSUE TITLE
[Feature] 能否增加一个账号同一时间只能再一处登录在线的限制

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#6396]
**请描述您的需求或者改进建议.**
现在一个账号可以同时在多处登录，能否增加一个配置，让一个账户同一时间只能登录一处，不能一个账号同一个时间可以在多处同时登录在线，后面登录的自动踢掉前面登录的。

**Comment by luweijun1992** [comment]
支持，可以设置用户的并发数量，如果超过并发数量是踢掉前面用户还是说不允许继续登录。

**Comment by aiaiduo** [comment]
> 支持，可以设置用户的并发数量，如果超过并发数量是踢掉前面用户还是说不允许继续登录。

现有版本2.11.3是在哪里进行配置？这个是对全局用户生效还是可以针对单个用户进行配置？

**Comment by aiaiduo** [comment]
@luweijun1992 踢掉前面用户还是不允许继续登录这个是要在哪里进行配置？谢谢！
