### ISSUE TITLE
[Bug] XRDP 历史会话无法完整播放

### ISSUE THREAD

**Issue by MetalHead77** [jumpserver/jumpserver#6397]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
XRDP 历史会话无法完整播放（一般只能播20秒，实际可能有5分钟或者更长），下载下来用Jumpserver video palyer播放也是一样的效果。如果使用WEB远程的话，录像时长正常，也能正常播放。

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/86470658/124855054-f323b400-dfda-11eb-8daa-d3be888852c9.mp4

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/125386167-66a83580-e3ce-11eb-98cd-338f6cf1f061.png)

**Comment by BaiJiangJie** [comment]
所有通过  XRDP 连接的会话录像都只能播放 20s + 还是只有个别几个会话有问题？
