### ISSUE TITLE
[Bug] 系统用户中删除资源后，账号列表中被删除资源下的账号不会删除

### ISSUE THREAD

**Issue by huoniu** [jumpserver/jumpserver#6406]
**JumpServer 版本(v1.5.9以下不再支持)**
版本v2.11.3

**浏览器版本**
Google Chrome 91.0.4472.124

**Bug 描述**
资产授权时，会将系统用户推送到资产中
然后编辑系统用户，在账号列表中更新密码
此时在系统用户删除该资源后，未更新过密码的账号列表中，与被删除资源相符的账号会自动删除
但是账号列表中，更新过密码的，在相应资源被删除后，并不会消失
导致使用该系统用户的资源授权用户，可以在luna登录时，看到本应被删除，不应该看到的账号选择
重建系统用户后，凡是更新过密码的账号列表条目，依然不会消失

**Bug 重现步骤(有截图更好)**
1.  新建系统用户osuser1，用户名为root
2.  新建资源授权，关联资源node1，node2，关联人员user1，关联系统用户osuser1
3.  点击系统用户，点击账户列表，点击node2的条目选择更新，输入新密码
4.  点击系统用户的资源列表，删除node1与node2
5.  点击系统用户的账户列表，发现node1的条目正常删除，node2未被删除
6.  user1登录luna后，依然可以看到node2的未被成功删除的账户
7.  删除系统用户osuser1，新建osuser2，用户名为root
8.  资源默认为空，且未被任何资源授权关联，账户列表中依然存在node2未被成功删除的用户

**Comment by wojiushixiaobai** [comment]
包含历史记录，不会删除。授权关系只存在授权表
