### ISSUE TITLE
[Question] 加密数据解密

### ISSUE THREAD

**Issue by whoamisky** [jumpserver/jumpserver#6407]
运维离职交接的时候没交接清楚，需要解密出assets_adminuser这个表里面的private_key，请问这个怎么做

**Comment by wojiushixiaobai** [comment]
参考 https://github.com/jumpserver/jumpserver/blob/master/apps/common/utils/crypto.py#L123

**Comment by xirotech** [comment]
运维离职的时候要是跟你这种黑客交接清楚了，那还不吃不了兜着走 :see_no_evil:
