### ISSUE TITLE
[Feature] jmsctl 执行文件 建议

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#6408]
**请描述您的需求或者改进建议.**
你好，近期使用了 DataEase，发现部署完成后会生成 dectl 可执行文件；
我们JumpServer是否也可以借鉴下，这样就不需要在安装工具目录下去使用这个脚本了；
对用户体验感好
![image](https://user-images.githubusercontent.com/58923704/125007922-f62eab00-e093-11eb-83f0-a27394dfa493.png)

**Comment by linl12138** [comment]
安装包目录下有jmsctl.sh执行脚本

**Comment by luweijun1992** [comment]
> 安装包目录下有jmsctl.sh执行脚本

操作上不方便呗。

**Comment by F2C-Jiang** [comment]
jmsctl就在可执行文件的环境中呢，直接执行jmsctl status就可以
