### ISSUE TITLE
[Bug] 2.11.3从Windows主机上下载文件下载到1.6G后无法下载

### ISSUE THREAD

**Issue by aiaiduo** [jumpserver/jumpserver#6409]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.3

**浏览器版本**

Google Chrome 已是最新版本
版本 91.0.4472.124（正式版本） （64 位）

**Bug 描述**
升级到2.11.3版本后从Windows主机上通过rdp的download目录来下载一个2G的文件，每次下载到1.6G时就无法下载了，但是上传一个2G的文件没有问题，下载失败后之前登录的Windows主机的那个窗口也无法操作，但是也没有任何报错，反向代理也配置了,从linux上下载这个文件又没有问题。
![image](https://user-images.githubusercontent.com/28044296/125010849-ec0fab00-e099-11eb-957c-f7175af45104.png)

**Bug 重现步骤(有截图更好)**
1.  复制一个文件到Windows主机的RDP的download目录来下一个一个2G的文件。
2. 
3.

**Comment by wojiushixiaobai** [comment]
下个版本修复。

**Comment by aiaiduo** [comment]
> 下个版本修复。

收到，谢谢！
