### ISSUE TITLE
无法资产导出500

### ISSUE THREAD

**Issue by leon8693** [jumpserver/jumpserver#641]
Centos 7.3
jumpserver 0.3.2-rc
报错如下
IOError at /jasset/asset/list/
[Errno 2] No such file or directory: 'static/files/excels/cmdb_excel_2017_08_23_16_34.xlsx'
权限777和selinux关闭
文件没有生成
什么原因呢？

**Comment by ibuler** [comment]
貌似没有生成这个文件，0.3.2不支持 centos7吧，centos7默认是python2.7
