### ISSUE TITLE
[Bug] windows设置系统用户为自动登录后，再取消，可以不输入密码直接登录

### ISSUE THREAD

**Issue by toolhubcn** [jumpserver/jumpserver#6410]
**JumpServer 版本**
Version v2.11.4 GPLv2.

**浏览器版本**
版本 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
windows设置系统用户为自动登录后，再取消，可以不输入密码直接登录

**Bug 重现步骤(有截图更好)**
1.  在系统用户中新建一个系统用户，并设置为自动登录
2. 授权用户使用此账号登录
3. 修改系统用户为手动登录
4. 在web终端登录的时候不输入密码，直接点击登录即可进入系统（期望结果应该提示输入密码，而不应该使用数据库中存储的密码直接登录）

**Comment by ibuler** [comment]
刷新一下页面
