### ISSUE TITLE
开源版本支持组织划分吗？划分完是不是有问题？

### ISSUE THREAD

**Issue by GuoYingLong** [jumpserver/jumpserver#6420]
**请描述您的问题.**
jumpserver版本：v2.11.4

创建完组织以后，比如创建一个开发组，在开发组里创建一个管理员账号，这个管理员账号可以登录所有组，是不是权限有问题？

还有就是创建完的组织能否删除？

**Comment by ibuler** [comment]
社区版不支持组织
