### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by jiaowc** [jumpserver/jumpserver#6423]
**组织排序**
 现在有很多组织 默认排序是按照时间或者创建时间排序的 （查找起来很不方便），希望默认排序可以自定义 或者按照字母或者数字进行排序。

**Comment by ibuler** [comment]
收到

**Comment by BaiJiangJie** [comment]
目前组织列表默认会按照名称进行排序。

顶部菜单栏的组织下拉列表按照名称排序，计划在 v3.3 版本支持。
