### ISSUE TITLE
[Bug] 重置 MFA 没有发送邮件

### ISSUE THREAD

**Issue by LalexH** [jumpserver/jumpserver#6430]
**JumpServer 版本(v1.5.9以下不再支持)**
2.11.4

**浏览器版本**

**Bug 描述**
创建新用户 和 重置密码 接收不到邮件，重置MFA 和 重置SSH密钥 邮件都可以接收到。

**Bug 重现步骤(有截图更好)**
1.  创建用户test，celery日志中发送邮件的task显示成功
![01](https://user-images.githubusercontent.com/34831384/125443794-b571e32d-7db3-44b9-bf8d-94a1b349cfc2.jpg)
![02](https://user-images.githubusercontent.com/34831384/125443807-a976b401-4b0f-47dc-91d3-3913bff221ea.jpg)
![03](https://user-images.githubusercontent.com/34831384/125443868-fe3e4e7c-a219-46b0-a977-b4352bda3040.jpg)

2. 但是没有接收到邮件
3. 重置MFA，可以接收到邮件

![20210713192633](https://user-images.githubusercontent.com/34831384/125444080-a9534bd2-e1bc-4d4f-a025-e3693ddbdc83.jpg)

**Comment by wojiushixiaobai** [comment]
垃圾箱里面

`主题前缀` 不要包含 `jumpserver` `堡垒机` 等字样

**Comment by LalexH** [comment]
> 垃圾箱里面
> 
> `主题前缀` 不要包含 `jumpserver` `堡垒机` 等字样

好的，多谢，还有一个问题。
1、通过Api创建jumpserver系统用户，不会给新用户发送邮件，请问是什么原因呢？
data = {
          "name": "test1",
          "username": "test1",
          "email": "xxx@xxx.com", # 此处在请求时使用真实的邮箱地址
          "mfa_level": 2,
          "source": "local",
          "need_update_password": True,
          "is_active": True,
          "role": "User",
          "org_roles": [
            "User"
          ],
          "password_strategy": "email"
        }

    resp = HTTP.post(url='/api/v1/users/users/', json=data)

2、返回正常

{'id': 'a18b094f-860a-4920-b802-72b9fbe65845', 'name': 'test1', 'username': 'test1', 'email': 'xxx@xxx.com'(此处为真实邮箱), 'wechat': '', 'phone': None, 'mfa_level': 2, 'source': 'local', 'source_display': '数据库', 'can_public_key_auth': True, 'need_update_password': True, 'mfa_enabled': True, 'is_valid': True, 'is_expired': False, 'is_active': True, 'date_expired': '2091-06-27 14:10:34 +0800', 'date_joined': '2021-07-14 14:10:34 +0800', 'last_login': None, 'created_by': 'Administrator', 'comment': None, 'is_wecom_bound': False, 'is_dingtalk_bound': False, 'total_role_display': '用户', 'org_role_display': '用户', 'mfa_level_display': '强制启用', 'mfa_force_enabled': True, 'is_first_login': True, 'date_password_last_updated': '2021-07-14 14:10:34 +0800', 'avatar_url': '/static/img/avatar/user.png', 'role': 'User', 'role_display': '用户', 'groups': [], 'groups_display': '', 'org_roles': ['User'], 'can_update': True, 'can_delete': True, 'login_blocked': False}

**Comment by ibuler** [comment]
api 创建也会发送邮件的
