### ISSUE TITLE
[Bug] Docker部署的要怎么去改SoftTimeLimitExceeded

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#6432]
[Bug] Docker部署的要怎么去改SoftTimeLimitExceeded
有没有提供相关变量？

**Comment by louishot** [comment]
批量执行命令60秒就超时了，这个时间也太短了了

**Comment by wojiushixiaobai** [comment]
link: https://github.com/jumpserver/jumpserver/blob/master/apps/ops/tasks.py#L51

**Comment by ibuler** [comment]
目前无法更改

**Comment by louishot** [comment]
> 目前无法更改

应该把这个时间变量加到管理后台配置吧或配置文件里。静态写死太蛋疼了

**Comment by louishot** [comment]
这个问题改进了吗

**Comment by louishot** [comment]
@wojiushixiaobai 没办法了，目前只能这样用着
docker exec -it 8361297933a6 /bin/bash
cp /opt/jumpserver/apps/ops/tasks.py /opt/jumpserver/data/
exit
cp /opt/jumpserver/data/tasks.py /opt/jumpserver/core/tasks.py

then update docker-compose-app.yml

`core:
    image: jumpserver/core:${VERSION}
    container_name: jms_core
    restart: always
    tty: true
    command: start web
    env_file:
      - ${CONFIG_FILE}
    volumes:
      - ${CONFIG_DIR}/core/config.yml:/opt/jumpserver/config.yml
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/core/logs:/opt/jumpserver/logs
      **- ${VOLUME_DIR}/core/tasks.py:/opt/jumpserver/apps/ops/tasks.py**
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - net
`

change `@shared_task(soft_time_limit=60, queue="ansible")` to `@shared_task(soft_time_limit=3600, queue="ansible")` in file /opt/jumpserver/core/tasks.py
