### ISSUE TITLE
[Question] 需要lion源码

### ISSUE THREAD

**Issue by rayPan2333** [jumpserver/jumpserver#6434]
**看不到lion源码.**
作为重要组件，lion只有release的二进制文件，看不到源码，无法保证安全性，希望遵循GPL协议尽快给出**lion的源码**，多谢

**Comment by ibuler** [comment]
内部讨论中，等待企业版有更多内容时会开放出来

**Comment by liyimeng** [comment]
@ibuler lion源码已经公布了吗？

**Comment by wangchaoHeart** [comment]
@ibuler  什么时候可以开源lion源码呀？

**Comment by maninhill** [comment]
该组件目前没有开源的计划。

**Comment by TinyWuP** [comment]
@maninhill 最近有开源lion源码的计划吗？

**Comment by maninhill** [comment]
没有开源计划。
