### ISSUE TITLE
DNS解析2台jumpserver的A记录时，jump的某些功能时不时不能正常响应，报502。

### ISSUE THREAD

**Issue by test-ffb** [jumpserver/jumpserver#6437]
V2.11.3版本：
DNS解析2台jumpserver的A记录时，jump的某些功能时不时不能正常响应，报502。
解析1台时，没有出现问题。

另外一套V1.5.9版本解析2台时，也没有出现这种现象。

请问是哪个地方的问题呢？

**Comment by wojiushixiaobai** [comment]
共用 redis 和 mysql
使用 NFS 共享 jumpserver/data 目录
nginx 反向代理里面做好健康判断

**Comment by test-ffb** [comment]
您好！
目前mysql、redis已经是独立部署并且是共享的。

**Comment by wojiushixiaobai** [comment]
可以参考[负载均衡](https://docs.jumpserver.org/zh/master/install/setup_by_lb/)文档进行修改下。
