### ISSUE TITLE
[Feature] 提供方法强制不复用SSH链接

### ISSUE THREAD

**Issue by jarod** [jumpserver/jumpserver#6438]
**2.11.3版本，好像没办法不复用SSH链接，导致目标机器用户信息变更没办法生效**

**Comment by LeeEirc** [comment]
参考配置 https://github.com/jumpserver/koko/blob/master/config_example.yml#L33 
修改 `/opt/jumpserver/config/config.txt ` 增加一行配置
```
REUSE_CONNECTION=true
```

重启JMS服务。

**Comment by jarod** [comment]
> 参考配置 https://github.com/jumpserver/koko/blob/master/config_example.yml#L33 
> 修改 `/opt/jumpserver/config/config.txt ` 增加一行配置
> ```
> REUSE_CONNECTION=true
> ```
> 
> 重启JMS服务。

好的，谢谢
