### ISSUE TITLE
添加不了用户，请问是什么原因，之前用过网易邮箱，可以添加用户的，现在为什么用不了，请问谁知道原因？

### ISSUE THREAD

**Issue by xiang-luo** [jumpserver/jumpserver#644]
SMTPDataError at /juser/user/add/
(554, 'DT:SPM 163 smtp14,EsCowAC3XkffVJ1ZcxWrFQ--.5037S2 1503483104,please see http://mail.163.com/help/help_spam_16.htm?ip=101.95.108.90&hostid=smtp14&time=1503483104')

Request Method:
POST 

Request URL:
http://10.199.110.65:8000/juser/user/add/ 

Django Version:1.6 

Exception Type:SMTPDataError 

Exception Value:
(554, 'DT:SPM 163 smtp14,EsCowAC3XkffVJ1ZcxWrFQ--.5037S2 1503483104,please see http://mail.163.com/help/help_spam_16.htm?ip=101.95.108.90&hostid=smtp14&time=1503483104')
 
Exception Location:
/usr/lib64/python2.6/smtplib.py in sendmail, line 725 

Python Executable:/usr/bin/python 

Python Version:2.6.6 

Python Path:
['/srv/install/jumpserver',
 '/usr/lib64/python26.zip',
 '/usr/lib64/python2.6',
 '/usr/lib64/python2.6/plat-linux2',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-old',
 '/usr/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6/site-packages',
 '/usr/lib64/python2.6/site-packages/gtk-2.0',
 '/usr/lib/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info']
 
Server time:
Thu, 24 Aug 2017 02:15:28 +0800

**Comment by xiang-luo** [comment]
554 DT:SPM 发送的邮件内容包含了未被许可的信息，或被系统识别为垃圾邮件。请检查是否有用户发送病毒或者垃圾邮件
我之前装的可以呀，觉得上面这个原因不合理，请问有谁知道为什么吗？

**Comment by qils** [comment]
网易邮箱有个设置， 需要开启SMTP第三方客户端登录权限， 开启这个功能需要你输入一个授权码， 这个授权码可以取代邮箱密码通过smtp.163.com来登录， 授权码设置好后需要修改jumpserver.conf 里面的[mail]  email_host_password 将这个参数值改为添加的授权码， 可以试试看能否解决
