### ISSUE TITLE
[Bug] ladp服务响应超时，本地用户也无法登陆

### ISSUE THREAD

**Issue by F2C-Jiang** [jumpserver/jumpserver#6441]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Google Chrome 已是最新版本
版本 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
ladp服务有问题，对过来的请求不及时响应。jms登录本地用户也会超时

**Bug 重现步骤(有截图更好)**
1.  配置ladp登录，且让ladp服务不及时返回响应
2. 使用jms本地用户登录jms，无法登陆，返回504

**Comment by ibuler** [comment]
设置 ldap 超时时间短些，或者直接禁用 ldap登录，utils 中有个脚本
