### ISSUE TITLE
使用jumpserver连接主机出现Connection Reset by peer

### ISSUE THREAD

**Issue by 5up3rc** [jumpserver/jumpserver#645]
安装jumpserver完毕后连接主机出现Connection Reset by peer,
jumpserver的服务器是centos7。连接主机一直提示Connection Reset by peer。
jumpserver是从master分支下载的。提示Connection Reset by peer但是日志审计中的在线却存在。
在执行命令的时候出现
`Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1503484394.23-74313223586932 && echo $HOME/.ansible/tmp/ansible-tmp-1503484394.23-74313223586932, exited with result 3`
这个问题该如何解决？

**Comment by 5up3rc** [comment]
运行端口修改为80后，连接主机变成Connecting...Connection Reset by peer

**Comment by daxin2017** [comment]
使用master分支代码（0.3.2）如果还出现这个错误 调整一下web terminal的行高和列宽就好了

**Comment by fxqmifi** [comment]
我和你遇到的是同一一个问题，你解决没有？

**Comment by ibuler** [comment]
0.3.2版本不支持centos 7

**Comment by ops0824** [comment]
我的centos6.5，连接也是这个错误，ssh端口未使用默认。
