### ISSUE TITLE
[Feature] 终端窗口koko那个，在搜索时只显示了主机，未显示主机所属的子目录关系

### ISSUE THREAD

**Issue by liuyjishg** [jumpserver/jumpserver#6453]
**JumpServer 2.9.2，2.11.4**

**谷歌浏览器**

**Bug 描述**
终端窗口koko那个，在搜索时只显示了主机，未显示主机所属的子目录关系

**Bug 重现步骤(有截图更好)**
1.未使搜索时的主机所属路径 是 default->test->a1
![image](https://user-images.githubusercontent.com/33978477/125719996-7d41b562-fe34-4522-ba1f-745465b74bde.png)

2. 使用搜索时，只显示了 default ->主机名，但未显示子目录
![image](https://user-images.githubusercontent.com/33978477/125720083-be1f0677-b72e-4e63-9188-45cc4c4580a2.png)

**Comment by liuyjishg** [comment]
2.11.4，我刚部署了一套，也是一样。
我是从1.4.9版本升级过来的，原来的版本是有可以显示这个层级关系的，这个功能很实用，可以快速确认是哪个项目的模块服务器。

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/125883652-9924169b-9683-4cbc-8238-bcee15565cdd.png)

同步加载树就好了

**Comment by liuyjishg** [comment]
好的好的，果然有效，这个功能太爱了。
