### ISSUE TITLE
2.11.4版本有一些问题,升了2.12rc4后mfa无法认证

### ISSUE THREAD

**Issue by Changego** [jumpserver/jumpserver#6456]
2.11.4版本有一些问题,升了2.12rc4后mfa无法认证.原环境强制mfa
现尝试了:
1. manager shell
2.修改 库 settings_setting  SECURITY_MFA_AUTH false
3.修改 库users_user 的 mfa_level  0
不晓得方法对不对,请帮忙看下,或者给予其他解决办法.感谢.

**Comment by wojiushixiaobai** [comment]
检查 secret_key 是否与旧版本一致

**Comment by Changego** [comment]
的确不一致,多谢.库已清空.

**Comment by Changego** [comment]
麻烦关闭下,感谢.

**Comment by ibuler** [comment]
rc版本不要升级，那是测试版本  @Changego
