### ISSUE TITLE
[Bug] xrdp连接方式在双屏模式下，不支持完整地显示在其中一个屏幕上

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#6459]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
Chrome

**Bug 描述**
PC 连接双屏后，通过堡垒机启动xrdp客户端，不支持完整地显示在其中一个屏幕上，只能把两块屏当作一块屏显示
通过堡垒机启动xrdp连接资产：
![image](https://user-images.githubusercontent.com/34565342/125768700-362898b0-8b82-4a51-8b84-13060e51a1ff.png)

**Bug 重现步骤(有截图更好)**
1. 连接双屏
2. 登陆JumpServer调用xrdp客户端连接RDP资产 
3. 双屏下不支持只显示在一个屏幕上

**Comment by ibuler** [comment]
使用 rdp 客户端直连可以吗？

**Comment by chenxin2001** [comment]
不经过堡垒机，用rdp客户端直练是正常的

发自我的iPhone

在 2021年7月16日，10:41，老广 ***@***.***> 写道：

﻿

使用 rdp 客户端直连可以吗？

**Comment by jym503558564** [comment]
@chenxin2001 已优化，将在未来小版本发布。请持续关注我们版本发布情况

**Comment by jym503558564** [comment]
v2.12.1版本已优化该问题，请更新至最新版本进行体验。感谢持续关注JumpServer,如有其他问题可再次提Issues
