### ISSUE TITLE
jms 4.0 资产批量导入bug

### ISSUE THREAD

**Issue by jackkeyang** [jumpserver/jumpserver#646]
- 1：    资产批量导入根据id去update，而不能批量新增（资产导入的时候那行“If set id, will use this id update asset existed”希望能用红色标记）。这个坑导致我导入的时候把原资产全部覆盖，导致所有关联资产的东西混乱

- 2：资产授权 授权规则详细页无法关联系统用户，点击加入系统用户无反应。需进入资产授权规则修改页面关联系统用户

**Comment by ibuler** [comment]
1. 之所以设置更新，是提供一种方式让用户可以批量更新，标红色是个不错的主意
2. 详情页bug已收到
