### ISSUE TITLE
[web 终端连接linux, 不操作几分钟就断开] 

### ISSUE THREAD

**Issue by szlyunnan** [jumpserver/jumpserver#6465]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.4

**浏览器版本**
Google Chrome
版本 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
1.  空闲时间默认30分钟, 发现几分钟就断开了; 看了koko报错如图

**Bug 重现步骤(有截图更好)**
koko 报错
![image](https://user-images.githubusercontent.com/12928768/125886178-2aca1edd-cb2c-48a8-8d3a-22c80fe91a16.png)

web 页面配置
![image](https://user-images.githubusercontent.com/12928768/125886231-b1be65c1-b212-4e17-baef-a3cdd2999fcb.png)

**Comment by LeeEirc** [comment]
检查自己的浏览器到部署JMS服务器的中间网络，是否有waf防火墙等拦截设备。貌似你的websocket无法保持长连接， 会异常主动断开。

**Comment by szlyunnan** [comment]
运行着两个版本, 这个版本没有这个现象; 只有最新的有这个情况, 同样的都是服务器直接出来的网络
1.4.8-2 GPLv2

**Comment by LeeEirc** [comment]
> 运行着两个版本, 这个版本没有这个现象; 只有最新的有这个情况, 同样的都是服务器直接出来的网络
> 1.4.8-2 GPLv2

新版本使用原生websocket，对网络有一定的要求。
