### ISSUE TITLE
[Question] 旧事重提，关闭远程清除上传文件的问题。

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#6467]
盯了两个小版本的更新，都没有看到关于“关闭远程链接后是否清理上传文件”的开关，没有这个功能极大影响了使用体验。
希望能尽快恢复这个功能。

**Comment by LeeEirc** [comment]
已经支持，详见[参数](https://github.com/jumpserver/lion-release/blob/master/config_example.yml#L48)

**Comment by vzrs** [comment]
辛苦
