### ISSUE TITLE
luna跳转失败，循环提示：重定向到web terminal， 。。。

### ISSUE THREAD

**Issue by yangruizeng** [jumpserver/jumpserver#647]
![image](https://user-images.githubusercontent.com/24568680/29649126-b751f5e8-88c4-11e7-8403-4b3f43411438.png)

**Comment by yangruizeng** [comment]
跳转web terminal页面，倒计时3、2、1一直循环，3、2、1、3、2、1、3、2、1,没有正常跳转到web terminial页面

**Comment by ibuler** [comment]
same with #564
