### ISSUE TITLE
[jms升级v2.12.0 jumpserver/luna:v2.12.0 not found] 

### ISSUE THREAD

**Issue by szlyunnan** [jumpserver/jumpserver#6471]
**请描述您的问题.**
升级jms到v2.12.0版本的时候提示jumpserver/luna:v2.12.0 not found

![企业微信截图_004c4107-07d1-4d25-984d-66ae8a118d30](https://user-images.githubusercontent.com/12928768/125902675-0da767c7-4490-4046-a032-a7c67648d044.png)

**Comment by Changego** [comment]
这个多试吧.有的源 镜像没同步到位.
友情提醒,谨慎升级:
我这资产 报 Request failed with status code 500
web终端,直接玩不起来了.

**Comment by szlyunnan** [comment]
之前是v2.11.4版本, 发现web终端的时间控制不了; 就是几分钟就断开了

**Comment by jym503558564** [comment]
installer不是最新版本
最新版本：jumpserver-installer-v2.12.0.tar.gz

**Comment by jym503558564** [comment]
升级请参考：https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

**Comment by jym503558564** [comment]
@szlyunnan 升级成功了吗
