### ISSUE TITLE
[Bug] V2.11.3版本，chrome、Edge无法访问web管理、文件管理（报错信息已补充，麻烦再确认一下）

### ISSUE THREAD

**Issue by test-ffb** [jumpserver/jumpserver#6475]
**JumpServer 版本(v1.5.9以下不再支持)**
 V2.11.3

**浏览器版本**
chrome、Edge

**Bug 描述**
1、web终端管理连接不上服务器，报错：Connection error     Connection  closed
2、文件管理打开报：Connection closed

**Comment by wojiushixiaobai** [comment]
未复现，检查koko组件是否正常

**Comment by test-ffb** [comment]
![image](https://user-images.githubusercontent.com/81751505/126098295-b7e1bc53-d07e-4837-a1b7-2339deb32100.png)

**Comment by test-ffb** [comment]
您好，查看jms_koko日志报错信息如下：
![image](https://user-images.githubusercontent.com/81751505/126098454-ebda9ad3-d062-4e2c-998f-ca5bd2e228c1.png)

**Comment by test-ffb** [comment]
![image](https://user-images.githubusercontent.com/81751505/126099300-86350930-1635-4732-b000-ef55d5a2678c.png)

**Comment by wojiushixiaobai** [comment]
websocket设置错误，检查反向代理，如果是单独的反向代理，参考 [多层 nginx 反向代理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)

```bash
server {

    listen 80;
    server_name demo.jumpserver.org;  # 自行修改成你的域名

    client_max_body_size 4096m;  # 上传文件大小限制

    location / {
            # 这里的 ip 是后端 JumpServer nginx 的 ip
            proxy_pass http://192.168.244.144;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by Ro0tk1t** [comment]
同样的问题，从2.11.1升级到2.12.0后，跟上面一模一样的问题。
@wojiushixiaobai 
没有多层nginx代理

**Comment by test-ffb** [comment]
使用火狐浏览器就没有问题，只是chrome、Edge浏览器才出现问题。所以说是配置的问题，解释不通啊。

**Comment by Ro0tk1t** [comment]
我所有浏览器都是同样的问题。现在一个资产都连不上了，版本能降级吗

**Comment by test-ffb** [comment]
能降级，但是不知道降级哪个版本才能正常。我测试的是V2.10.3还是存在同样的问题。

**Comment by Ro0tk1t** [comment]
降级的时候程序不知道为啥把docker的所有iptables链删除了。。。然后容器一直起不来。
遂一怒之下重启之， 而后奇迹般正常了。
重启大法好啊。 但https还是没有了

**Comment by test-ffb** [comment]
已解决，是代理的问题。
