### ISSUE TITLE
[Bug] kubectl logs -f 查看实时日志，然后执行“Ctrl + C”会断开连接

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#6481]
**JumpServer 版本(v1.5.9以下不再支持)**
2.6.0

**浏览器版本**
Chrome

**Bug 描述**

 登录到k8s集群，查看pod实时日志，执行：kubectl logs -f  【某个pod】，日志滚动时，然后执行“Ctrl + C”，直接断开连接，如下图所示：

![image](https://user-images.githubusercontent.com/10806595/125943551-4ba23be9-8909-4ae3-a8ca-60f8ad3265d8.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
新版本已经修复
