### ISSUE TITLE
[Bug] 目标资产默认终端为Fish Shell时部分功能无法正常使用

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#6482]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.12.0

**浏览器版本**
Edge 91.0.864.67

**Bug 描述**
当目标资产的默认终端为Fish Shell时，部分功能无法正常使用：
1. VSCode Remote-SSH无法连接
2. 命令记录里面无法正常记录，里面的命令非常混乱。

**Bug 重现步骤(有截图更好)**
### VSCode Remote-SSH问题
1.  使用VSCode Remote-SSH直连时，会卡在如下界面处：
![image](https://user-images.githubusercontent.com/22488813/126028091-80e11d9b-30bf-4cd3-954d-32171f079d3e.png)
2. 将目标主机的默认终端改为bash以后，使用VSCode Remote-SSH直连，可以成功连接：
![image](https://user-images.githubusercontent.com/22488813/126028111-4695dc53-97dd-4c38-98ab-685ae1fcfaf2.png)
3. 使用SSH直连，可以成功连接：
![image](https://user-images.githubusercontent.com/22488813/126028118-a5303926-14c7-4779-b706-cb4cb88735e0.png)
4. 不通过Jumpserver堡垒机，而是直接连接资产，当默认终端为Fish时，可以成功连接：
![image](https://user-images.githubusercontent.com/22488813/126028144-162e1d07-03cc-4847-a7bb-38c75104c36c.png)

---
### 命令记录问题
1. 在终端输入apt，如下图：
![image](https://user-images.githubusercontent.com/22488813/126028178-676b5a1a-7ee6-42e2-83e7-3250d8616e8e.png)
2. 命令记录里会出现一些乱七八糟的内容：
![image](https://user-images.githubusercontent.com/22488813/126028188-17cf5d43-856e-430f-9eec-f260bb9e581f.png)
3. 如果换为bash，则一切正常

**Comment by jym503558564** [comment]
已知问题

**Comment by jym503558564** [comment]
重复问题：https://github.com/jumpserver/jumpserver/issues/6384
