### ISSUE TITLE
复制粘贴功能

### ISSUE THREAD

**Issue by Eric-Hyiboo** [jumpserver/jumpserver#6485]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.3

**浏览器版本**
谷歌91.0.4472.114

**Bug 描述**
从本地复制到远端资产，复制千行以上字段，会有丢失现象

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wumuhappy** [comment]
遇到同样的问题，复制粘贴经常莫名失效，而且快捷键也经常不可用（版本v 2.10.2）

**Comment by Primeyang** [comment]
遇到同样的问题，复制粘贴经常莫名失效，而且快捷键也经常不可用（版本v 2.6.1）

**Comment by wangyu0310** [comment]
快捷键确实不好用  经常错乱

**Comment by LeeEirc** [comment]
部署原生guacamole的环境，测试连接Windows资产，发现复制超大文件也会出现相同的问题。
