### ISSUE TITLE
[Feature] 资产列表和web终端使用体验什么时候优化下啊

### ISSUE THREAD

**Issue by rayshen3** [jumpserver/jumpserver#6486]
1. 资产列表每次手动增加、变更完节点， 所有列表全部关闭到默认状态，想查看，还要一层一层再打开去找，是故意这么设置的吗？ 如果我设置路径有3/4级，每次添加节点简直加到绝望
2. web终端登录多个机器，从节点1切换到节点2后，默认不能直接输入命令，需要用鼠标点一下窗口区，这效率和体验...    
3. 服务器登录方式建议，用户通过CRT类终端登录jumpserver，再选择对应的主机登录，这种效率很低，如果我们已确定登录哪台服务器最不建议这种，建议用户在资产列表点击主机名或IP可以直接登录，这里可以省去在web终端或CRT终端 检索主机的时间，或者登录跳板机后用户可以手动直接ssh ip，灵活选择，感觉这种效率都比现在的"强迫菜单选择"高，建议 

> 资产列表中，主机名 跳到主机详情，主机详情页可以直接更新主机信息，不要再点击右上角的"更新"；IP跳到web登录， 某里好像就是这样

4. 仪表盘最右侧的"在线会话 Connected" 可以从红色改成别的颜色吗？  红色一般代表断开或失联，“在线用户 Online "还是绿色，在线会话就变成红色，每次打开以为多少会话中断了，哎

**Comment by ibuler** [comment]
1. 这个的确是个bug，提了好久了，没有改
2. 这个下个版本搞定
3. 计划中，想办法能导出 crt 的配置文件，或者支持 拉本地的 terminal 去连接
4. 这个我们看看改什么颜色

**Comment by ibuler** [comment]
1. 解决方案，点击创建，新建一个标签，创建完成，重定向到详情页，如果回到列表页，需要右侧的刷新

**Comment by ibuler** [comment]
2. 尝试了一下，搞不定，不点击不行

**Comment by ibuler** [comment]
2. 又尝试了一下，请教了一下大神搞定了

**Comment by ibuler** [comment]
4. 直接干掉了右侧的标签

**Comment by szlyunnan** [comment]
> 1. 解决方案，点击创建，新建一个标签，创建完成，重定向到详情页，如果回到列表页，需要右侧的刷新

试过了没看到效果, 有截图吗？

**Comment by ibuler** [comment]
> > 1. 解决方案，点击创建，新建一个标签，创建完成，重定向到详情页，如果回到列表页，需要右侧的刷新
> 
> 试过了没看到效果, 有截图吗？
> 
> 

下个版本发布

**Comment by szlyunnan** [comment]
可以支持修改默认的default 跟目录名称吗？

**Comment by rayshen3** [comment]
> 可以支持修改默认的default 跟目录名称吗？

+1

**Comment by BaiJiangJie** [comment]
大多数问题在 v3 版本中已经优化了，如果 v3 还有问题再提交对应的 Issue。
