### ISSUE TITLE
[Bug] 2.12.0 8443的https废弃掉了？

### ISSUE THREAD

**Issue by Ro0tk1t** [jumpserver/jumpserver#6493]
**Bug 描述**
升级到2.12.0之后，8443的https无法访问了

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
vi /opt/jumpserver/config/config.txt
## Nginx 配置, USE_LB=1 表示开启, 为 0 的情况下, HTTPS_PORT 定义不生效
HTTP_PORT=80
SSH_PORT=2222
RDP_PORT=3389

USE_LB=1
HTTPS_PORT=443

**Comment by Ro0tk1t** [comment]
好的
