### ISSUE TITLE
[Feature] 查询Node->Assets 接口响应慢

### ISSUE THREAD

**Issue by olajowon** [jumpserver/jumpserver#6495]
/api/v1/assets/nodes/<nodeid>/assets/
这个接口可以优化下吗，v2.11.4的这个接口比以前v1.15版本响应要慢，
同版本下的  /api/v1/assets/assets/?node_id=<nodeid> 这个接口都比/api/v1/assets/nodes/<nodeid>/assets/ 响应快。

**Comment by wojiushixiaobai** [comment]
/api/v1/assets/assets/?fields_size=mini
