### ISSUE TITLE
[Bug] web终端访问windows打开的还是堡垒机页面

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#6497]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.0

**浏览器版本**
Microsoft Edge
版本 92.0.902.49 (官方内部版本) beta (64 位)

**Bug 描述**
web登陆windows机器打开的还是堡垒机页面

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/70014578/126255758-11da852e-741a-4f2a-8a25-5823e84ef665.png)

2. 
![image](https://user-images.githubusercontent.com/70014578/126255814-5bfbf80c-2668-4fe3-9473-01d5e8f1de5f.png)

3.

**Comment by wojiushixiaobai** [comment]
反向代理设置不当导致。请检查下

**Comment by jym503558564** [comment]
返现代理参考：https://docs.jumpserver.org/zh/master/admin-guide/proxy/

**Comment by jym503558564** [comment]
@sshnuke3 参照文档修改后，该问题解决了吗

**Comment by sshnuke3** [comment]
我用的是./jmsctl.sh start一键启动的
是要到nginx容器里改配置吗
而且并不是所有浏览器都有问题
在edge和其他chromium浏览器里都是正常的
只有chrome里会这样
