### ISSUE TITLE
3.2安装错误，求大神帮看下

### ISSUE THREAD

**Issue by dingzhaopeng** [jumpserver/jumpserver#650]
新人一枚，贴上错误截图。
![1](https://user-images.githubusercontent.com/31378441/29746443-f3746d86-8b0c-11e7-949f-a34d3227e5f8.png)

**Comment by qils** [comment]
python2.6环境试试用 yum -y install python-devel 安装这个包， 如果是python2.7试试安装yum -y install mysql-delel 这个包

**Comment by dingzhaopeng** [comment]
多谢大哥。刚才那个解决了。又有新错误了。麻烦看下新帖子
