### ISSUE TITLE
[Bug] rz sz命令乱码，无法上传

### ISSUE THREAD

**Issue by jhsswl** [jumpserver/jumpserver#6500]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.12.0 

**浏览器版本**
xshell ssh 2222端口登录跳板机

**Bug 描述**
ssh 2222端口登录跳板机，在到资产主机，在资产主机上rz 上传4M左右的文件就乱码，传输出错，几百K的文件是可以的

**Bug 重现步骤(有截图更好)**
1.  
![QQ截图20210720163756](https://user-images.githubusercontent.com/35069629/126290229-a5c5eb98-4d19-457e-804f-174fbab6f703.png)

**Comment by wojiushixiaobai** [comment]
属于网络问题，得后续慢慢优化

**Comment by kong62** [comment]
> 属于网络问题，得后续慢慢优化

新版本解决了吗
