### ISSUE TITLE
[Bug] 升级2.12.0，提示找不到luna镜像

### ISSUE THREAD

**Issue by liuqing-datacloak** [jumpserver/jumpserver#6501]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.0

**浏览器版本**
版本 91.0.4472.124（正式版本） （64 位）

**Bug 描述**
从2.10.2 升级至 2.12.0 ，出现问题，找不到 luna v2.12.0 的镜像

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/53427603/126294778-cd4c23f6-fba6-4e90-be9d-c3d4239a573e.png)

**Comment by liuqing-datacloak** [comment]
我把 2.11.4 的 luna 的镜像 重新打了个v2.12.0的标签， 结果成功了， 不知道有没有啥后遗症，还在体验中

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/126419774-02f5d9b1-f553-443c-8d5f-8d4a426d0161.png)
installer 也需要最新版本

**Comment by ibuler** [comment]
@liuqing-datacloak Luna Lina 镜像已经整合到 nginx 中了，使用新的 installer 安装
