### ISSUE TITLE
[Feature] 建议X-Pack云管中心的同步任务资产更新时，可以筛选有效IP

### ISSUE THREAD

**Issue by Andyguo5891** [jumpserver/jumpserver#6505]
**请描述您的需求或者改进建议.**
作为企业用户，在使用 X-Pack 云管中心资产同步任务时，我希望在开启「资产信息保持最新」时，可以通过正则等方式匹配和筛选有效 IP。
目前如果资产有多个 IP（多张网卡、EIP 和内网 IP） ,在自动同步的时候极有可能同步的是与 JumpServer 网络隔离的 IP ，这将导致同步之后堡垒机无法与资产连接。
![image](https://user-images.githubusercontent.com/46042812/126319174-7276b868-411a-4178-b11b-f30e358b9715.png)

**Comment by BaiJiangJie** [comment]
预计在 v2.12.0 版本实现，创建同步任务时可以配置 IP网段组，将优先使用匹配网段的IP作为资产IP。

**Comment by jym503558564** [comment]
已实现，请更新至最新版本进行测试
