### ISSUE TITLE
V2.12.0版本 管理用户和系统用户合并后，特权用户不能创建rdp协议？创建Windows资产时不能选rdp协议？[Bug] 

### ISSUE THREAD

**Issue by yaodunlin** [jumpserver/jumpserver#6507]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by yaodunlin** [comment]
![image](https://user-images.githubusercontent.com/37436336/126425007-75ef0514-863a-4b3d-a108-50a1ef25d184.png)
![image](https://user-images.githubusercontent.com/37436336/126425107-604d8642-2069-4c73-8c7e-c190d93e3e59.png)

**Comment by wojiushixiaobai** [comment]
随便指定一个，非SSH协议此设置无效，也无任何实际作用

**Comment by yaodunlin** [comment]
这个有点误导性吧

**Comment by jym503558564** [comment]
这边的特权用户，是资产已存在的, 并且拥有 高级权限 的系统用户， JumpServer 使用该用户来 `推送系统用户`、`获取资产硬件信息` 等;
理论上默认SSH协议也是合理。

**Comment by wojiushixiaobai** [comment]
之后的版本会取消掉管理用户必填
