### ISSUE TITLE
[Bug]资产授权节点，web终端看不到授权的资产

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#6508]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.0

**浏览器版本**

**Bug 描述**
资产授权节点，web终端看不到授权的资产，必须要资产里也要选择一个资产，web终端才能看到所有授权的节点，然后把授权的资产取消授权只留节点，就正常了

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by jym503558564** [comment]
无法复现
![image](https://user-images.githubusercontent.com/40739051/126584207-1ef7e668-0eae-479c-817d-0b726b72627a.png)
![image](https://user-images.githubusercontent.com/40739051/126584242-c0cc333d-5386-4a8d-9e7a-0ffbd4bec133.png)
