### ISSUE TITLE
[Feature] [Bug]数据库直连、工单优化、命令记录优化、录像优化

### ISSUE THREAD

**Issue by LeiyuanBlog** [jumpserver/jumpserver#6509]
**请描述您的需求或者改进建议.**
一、 数据库直连
    希望可以像 ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP 这种方式连接数据库，或者添加navicat第三方组件。

二、 工单优化
    目前工单模块，用户申请时无法选择资产，审核人在授权是只可单选，当需要很多的资产时非常的反人类，希望可以弄成批量选择或者是添加节点选择模式。

三、 命令记录
    目前命令记录会有裁剪，如果命令或sql过长，会导致记录不全等问题，希望可以放开长度或优化截取方案。

四、 录像优化
    录像中同样存在上一条目中的记录问题，过长的命令不会另起一行记录，而是在原行从头覆盖性记录，造成记录不全或者记录丢失等问题。

**Comment by jym503558564** [comment]
1.企业版增强包 现支持数据库 GUI 图形界面化操作。

**Comment by LeiyuanBlog** [comment]
> 1.企业版增强包 现支持数据库 GUI 图形界面化操作。

操作有一定的限制性
