### ISSUE TITLE
安装错误，大神求救。

### ISSUE THREAD

**Issue by dingzhaopeng** [jumpserver/jumpserver#651]
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

这个我按大部分文档说的卸载了pycrypto模块，重新装了。还是这个错。想尽办法了。新人求指教。

**Comment by dingzhaopeng** [comment]
难道跟我是centos6.8有关系么。我装的3.0的jump

**Comment by jiaxiangkong** [comment]
去看wiki 常见问题  v0.3.2 有 可以搜索 HAVE_DECL_MPZ_POWM_SEC
