### ISSUE TITLE
[Bug] 文件管理标签小图标没有跟随设置改变

### ISSUE THREAD

**Issue by zhoufanqi** [jumpserver/jumpserver#6513]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.2

**浏览器版本**
chrome 91.0.4472.164

**Bug 描述**
文件管理标签页的小图标没有跟随设置改变，还是原来的图标

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/85146580/126446907-73dfc577-f48b-451d-9807-64fe00e913ea.png)

2. 
3.

**Comment by jym503558564** [comment]
已知问题

**Comment by LeeEirc** [comment]
v2.15版本已解决
