### ISSUE TITLE
[Feature] 管理用户和系统用户模块合并后, 资产授权的时候, 选择系统用户的时候; 下拉框都显示了普通用户和特权用户

### ISSUE THREAD

**Issue by szlyunnan** [jumpserver/jumpserver#6515]
**请描述您的需求或者改进建议.**
1. 管理用户和系统用户模块合并后, 资产授权的时候, 选择系统用户的时候; 下拉框都显示了普通用户和特权用户, 如果命名不特别的话, 还真不好区分普通和用户和特权用户; 体验不太友好

**Comment by wojiushixiaobai** [comment]
用颜色或者其他字符串区分下？

**Comment by lyc7456** [comment]
管理用户和系统用户模块合并后，无法创建RDP协议的特权用户，那么如何连windows主机呢？

**Comment by china-live** [comment]
这个是什么时候改的，现在版本是v1.12.0，无法添加windows主机（严格来说，是可以添加，但没法设置管理用户，导致无无法连接windows系统）

**Comment by smilealgernon** [comment]
各种用户确实不好理解，文档里也没找到更详细的说明，找到一段文案看了更晕了，希望能改善下。
找到的文案：
系统用户 是JumpServer 登录资产时使用的账号，如 root `ssh root@host`，而不是使用该用户名登录资产（ssh admin@host)`;
特权用户 是资产已存在的, 并且拥有 高级权限 的系统用户， JumpServer 使用该用户来 `推送系统用户`、`获取资产硬件信息` 等;
普通用户 可以在资产上预先存在，也可以由 特权用户 来自动创建。

**Comment by denity** [comment]
其实对于特权用户、普通用户的较好的实践是怎样？

比如一个组里有100台服务器，理论上每台服务器上的账号、密码都不一样的，这样势必需要设置100个特权账号或者普通账号进行系统运维。假如对这个组授权，还需要在系统用户中逐一添加这100个特权账号或者普通账号。
然后在Web终端运维的时候（第一次）还需要在这100个账号里面去选择哪一个账号进行运维。
并且，重新进入“资产列表”——“主机”——“系统用户”和“账号列表”中，又会将这100个账号都列出来？

问题1：能否考虑“账号”就和“资产”关联？  

问题2：难道需要所有主机都使用同样的账号/密码/证书登录？

jumpserver 版本：v2.19.0
