### ISSUE TITLE
如何修改管理员预设的资产目录？

### ISSUE THREAD

**Issue by ZJahon** [jumpserver/jumpserver#6517]
如何修改管理员预设的资产目录？

**Comment by wojiushixiaobai** [comment]
系统用户里面，SFTP目录

**Comment by jym503558564** [comment]
系统用户-修改SFTP目录
![image](https://user-images.githubusercontent.com/40739051/126583733-037b2b20-edf9-4ec3-b4b1-a801e97129f8.png)
