### ISSUE TITLE
[Feature] k8s应用命令行增加集群名称的

### ISSUE THREAD

**Issue by 580825** [jumpserver/jumpserver#6524]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/12560237/126596384-2d37d48f-ec50-4089-9226-adf8e7f27dbd.png)

我这边有N个K8S集群，选择一个登录后，红框这边是  #  提示符，当开了多个窗口后很难分辨某个窗口是哪个k8s集群

能否在红框部分改成类似如下提示

[K8S应用名称 ~]# 

比如:

[华北生产环境 ~]#

**Comment by BaiJiangJie** [comment]
上线时间同步记录在 https://github.com/jumpserver/jumpserver/issues/5995 中。

**Comment by BaiJiangJie** [comment]
v3.3 版本已支持；

[perf: 优化连接 Kubernetes 资产时，命令行前缀显示资源名称和集群名称](https://github.com/jumpserver/jumpserver/releases/tag/v3.3.0)
