### ISSUE TITLE
0.4.0 审计功能--操作日志输出结果记录不完全

### ISSUE THREAD

**Issue by yrpapa** [jumpserver/jumpserver#653]
操作日志记录的输出结果不完全，例如执行ip a命令，从页面和数据库的audits_commandlog表得到的结果都是：
      output: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN                                 

实际这台客户机执行ip a的结果应该是：
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:07:61:ac brd ff:ff:ff:ff:ff:ff
    inet 8.8.8.237/24 brd 8.8.8.255 scope global eth1
    inet6 fe80::5054:ff:fe07:61ac/64 scope link 
       valid_lft forever preferred_lft forever
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:55:6f:55 brd ff:ff:ff:ff:ff:ff
    inet 30.0.0.10/24 brd 30.0.0.255 scope global eth0
    inet6 fe80::5054:ff:fe55:6f55/64 scope link 
       valid_lft forever preferred_lft forever
4: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN 
    link/ether 52:54:00:94:7e:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 500
    link/ether 52:54:00:94:7e:8b brd ff:ff:ff:ff:ff:ff

不知道是bug还是我的环境有什么问题？？？

**Comment by ibuler** [comment]
same with #738
