### ISSUE TITLE
[Bug] jumpserver-1.12.1，本机无法连接，其他机器正常

### ISSUE THREAD

**Issue by MRwangyd** [jumpserver/jumpserver#6532]
**JumpServer 版本(v1.5.9以下不再支持)**
1.12.1

**浏览器版本**
chrom 版本 87.0.4280.141（正式版本） （64 位）

**Bug 描述**
使用docker方式安装后，jumpserver所在机器添加资产后无法练级
其他主机资产没有问题

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/27405334/126757749-ba17f7f8-d7c7-4b13-8a3a-c3b0be76b972.png)
2.
10.109.3.14是安装jumpserver的本机，其他机器可以本机不行
![image](https://user-images.githubusercontent.com/27405334/126757847-f7e2c173-b8c9-4e0a-b2fc-d6c937a6f9b6.png)

3. 进入jms_core容器内，可以ping和ssh登录本机的IP，并且使用ansible命令用密码可以连接
![image](https://user-images.githubusercontent.com/27405334/126758048-8d87756f-50de-4d5b-96bb-274acdcc8a44.png)

**Comment by MRwangyd** [comment]
@wojiushixiaobai 能否支持解决，感谢

**Comment by wojiushixiaobai** [comment]
提示是账号密码错误

**Comment by MRwangyd** [comment]
特权用户使用的秘钥方式，测试秘钥已经在资产服务器上授权。本机ssh 本机是可以实现免密的

**Comment by MRwangyd** [comment]
![image](https://user-images.githubusercontent.com/27405334/127112329-cb36f272-efba-4533-b9a8-9054938916de.png)

**Comment by MRwangyd** [comment]
账号免密操作和其他资产的操作一致，其他资产可以登录，只有本机登录的时候报错。

**Comment by wojiushixiaobai** [comment]
改成密码验证下，提示里面已经使用了密钥认证，但是依旧返回了 Permission denied
