### ISSUE TITLE
[Bug] JumpServer xrdp连接失败

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#6542]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
使用xrdp连接资产不稳定，很多资产连接报错协议不正确

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/29521063/126927461-ff4f509f-96b8-4ab8-afdd-d8fc92c4bdeb.png)

**Comment by wojiushixiaobai** [comment]
这个应该是配置错误
