### ISSUE TITLE
3.2-rc2版本创建用户不能以"姓.名"的BUG

### ISSUE THREAD

**Issue by ChowRex** [jumpserver/jumpserver#655]
创建用户的时候不能使用"姓.名"的方式创建，但是实际Linux是支持的

**Comment by ChowRex** [comment]
ServerError at /juser/user/add/
用户名不合法
Request Method:	POST
Request URL:	http://d.wiplatform.com:8000/juser/user/add/
Django Version:	1.6
Exception Type:	ServerError
Exception Value:	
用户名不合法
Exception Location:	/opt/apps/jumpserver-0.3.2-rc2/juser/views.py in user_add, line 179
Python Executable:	/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/apps/jumpserver-0.3.2-rc2',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages/cloud_init-0.7.6-py2.7.egg']
Server time:	Wed, 30 Aug 2017 14:44:52 +0800
Traceback Switch to copy-and-paste view

/usr/lib64/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/opt/apps/jumpserver-0.3.2-rc2/jumpserver/api.py in __deco
            return func(request, *args, **kwargs) ...
▶ Local vars
/opt/apps/jumpserver-0.3.2-rc2/juser/views.py in user_add
                    raise ServerError(error) ...
▶ Local vars
Request information

GET
No GET data
POST
Variable	Value
username	
u'zhang.san'
name	
u'\u5f20\u4e09'
extra	
u'1'
role	
u'CU'
groups	
u'5'
email	
u'zhou.ruixi@jianfeitech.com'
FILES
No FILES data
COOKIES
Variable	Value
_ga	
'GA1.3.48000424.1502767477'
sessionid	
'zmjueezw7wd6zuoetx9mkftl9ofqer7o'
lam_last_language	
'zh_CN.utf8'
lam_login_name	
'root'
META
Variable	Value
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
CONTENT_TYPE	
'application/x-www-form-urlencoded'
HTTP_REFERER	
'http://d.wiplatform.com:8000/juser/user/add/'
wsgi.multithread	
False
SCRIPT_NAME	
u''
wsgi.input	
<_io.BytesIO object at 0x2ea7770>
REQUEST_METHOD	
'POST'
HTTP_HOST	
'd.wiplatform.com:8000'
PATH_INFO	
u'/juser/user/add/'
HTTP_ORIGIN	
'http://d.wiplatform.com:8000'
SERVER_PROTOCOL	
'HTTP/1.1'
QUERY_STRING	
''
HTTP_CONNECTION	
'keep-alive'
HTTP_CACHE_CONTROL	
'max-age=0'
CONTENT_LENGTH	
'102'
HTTP_USER_AGENT	
'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36'
wsgi.version	
(1, 0)
HTTP_COOKIE	
'_ga=GA1.2.48000424.1502767477; _ga=GA1.3.48000424.1502767477; lam_login_name=root; lam_last_language=zh_CN.utf8; sessionid=zmjueezw7wd6zuoetx9mkftl9ofqer7o'
SERVER_NAME	
'd.wiplatform.com'
REMOTE_ADDR	
'49.4.129.98'
wsgi.run_once	
False
wsgi.errors	
<open file '<stderr>', mode 'w' at 0x7f972f6131e0>
wsgi.multiprocess	
True
HTTP_ACCEPT_LANGUAGE	
'zh-CN,zh;q=0.8,en;q=0.6,ja;q=0.4'
wsgi.url_scheme	
'http'
HTTP_DNT	
'1'
SERVER_PORT	
'8000'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_ACCEPT_ENCODING	
'gzip, deflate'
Settings
Using settings module jumpserver.settings
Setting	Value
NAV_SORT_BY	
'ip'
USE_L10N	
True
SSH_KEY_DIR	
u'********************'
USE_THOUSAND_SEPARATOR	
False
CSRF_COOKIE_SECURE	
False
CRONJOBS	
[('0 1 * * *', 'jasset.asset_api.asset_ansible_update_all'),
 ('*/10 * * * *', 'jlog.log_api.kill_invalid_connection')]
LANGUAGE_CODE	
'en-us'
ROOT_URLCONF	
'jumpserver.urls'
MANAGERS	
()
BASE_DIR	
'/opt/apps/jumpserver-0.3.2-rc2'
DEFAULT_CHARSET	
'utf-8'
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT	
''
DB_USER	
'jumpserver'
ALLOWED_HOSTS	
['0.0.0.0/8']
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
WSGI_APPLICATION	
'jumpserver.wsgi.application'
EMAIL_SUBJECT_PREFIX	
'[Django] '
SEND_BROKEN_LINK_EMAILS	
False
STATICFILES_FINDERS	
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
URL	
'http://d.wiplatform.com:8000'
SESSION_CACHE_ALIAS	
'default'
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_NAME	
'sessionid'
ADMIN_FOR	
()
TIME_INPUT_FORMATS	
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.mysql',
             'HOST': '10.0.0.254',
             'NAME': 'jumpserver',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': 3306,
             'TEST_CHARSET': None,
             'TEST_COLLATION': None,
             'TEST_MIRROR': None,
             'TEST_NAME': None,
             'TIME_ZONE': 'Asia/Shanghai',
             'USER': 'jumpserver'}}
KEY_DIR	
u'********************'
BOOTSTRAP_COLUMN_COUNT	
10
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE	
'text/html'
APPEND_SLASH	
True
FIRST_DAY_OF_WEEK	
0
DATABASE_ROUTERS	
[]
DEFAULT_TABLESPACE	
''
YEAR_MONTH_FORMAT	
'F Y'
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SERVER_EMAIL	
'root@localhost'
SESSION_COOKIE_PATH	
'/'
DB_PORT	
3306
MIDDLEWARE_CLASSES	
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')
USE_I18N	
True
THOUSAND_SEPARATOR	
','
SECRET_KEY	
u'********************'
PORT	
'8000'
LANGUAGE_COOKIE_NAME	
'django_language'
DEFAULT_INDEX_TABLESPACE	
''
TRANSACTIONS_MANAGED	
False
LOGGING_CONFIG	
'django.utils.log.dictConfig'
TEMPLATE_LOADERS	
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader')
LOG_DIR	
'/opt/apps/jumpserver-0.3.2-rc2/logs'
SETTINGS_MODULE	
'jumpserver.settings'
TEMPLATE_DEBUG	
True
X_FRAME_OPTIONS	
'SAMEORIGIN'
CSRF_COOKIE_NAME	
'csrftoken'
FORCE_SCRIPT_NAME	
None
USE_X_FORWARDED_HOST	
False
EMAIL_TIMEOUT	
5
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE	
False
CSRF_COOKIE_DOMAIN	
None
FILE_CHARSET	
'utf-8'
DEBUG	
True
SESSION_FILE_PATH	
None
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS	
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_crontab',
 'bootstrapform',
 'jumpserver',
 'juser',
 'jasset',
 'jperm',
 'jlog')
LANGUAGES	
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy-nl', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-tw', 'Traditional Chinese'))
COMMENTS_ALLOW_PROFANITIES	
False
MAIL_ENABLE	
'1'
STATICFILES_DIRS	
('/opt/apps/jumpserver-0.3.2-rc2/static',)
PREPEND_WWW	
False
SECURE_PROXY_SSL_HEADER	
None
SESSION_COOKIE_HTTPONLY	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
MONTH_DAY_FORMAT	
'F j'
LOGIN_URL	
'/accounts/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
TIME_FORMAT	
'P'
AUTH_USER_MODEL	
'juser.User'
DATE_INPUT_FORMATS	
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
AUTHENTICATION_BACKENDS	
('django.contrib.auth.backends.ModelBackend',)
EMAIL_HOST_PASSWORD	
u'********************'
DB_DATABASE	
'jumpserver'
PASSWORD_RESET_TIMEOUT_DAYS	
u'********************'
CACHE_MIDDLEWARE_ALIAS	
'default'
SESSION_SAVE_EVERY_REQUEST	
False
NUMBER_GROUPING	
0
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH	
'/'
LOGIN_REDIRECT_URL	
'/accounts/profile/'
DECIMAL_SEPARATOR	
'.'
IGNORABLE_404_URLS	
()
DB_PASSWORD	
u'********************'
LOCALE_PATHS	
()
TEMPLATE_STRING_IF_INVALID	
''
LOGOUT_URL	
'/accounts/logout/'
EMAIL_USE_TLS	
False
FIXTURE_DIRS	
()
EMAIL_HOST	
'smtp.qiye.163.com'
DATE_FORMAT	
'N j, Y'
MEDIA_ROOT	
''
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
ADMINS	
()
FORMAT_MODULE_PATH	
None
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
KEY	
u'********************'
MEDIA_URL	
''
DATETIME_FORMAT	
'N j, Y, P'
TEMPLATE_DIRS	
('/opt/apps/jumpserver-0.3.2-rc2/templates',)
DISALLOWED_USER_AGENTS	
()
ALLOWED_INCLUDE_ROOTS	
()
LOGGING	
{}
SHORT_DATE_FORMAT	
'm/d/Y'
LOG_LEVEL	
'debug'
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
CACHE_MIDDLEWARE_KEY_PREFIX	
u'********************'
TIME_ZONE	
'Asia/Shanghai'
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
CSRF_COOKIE_HTTPONLY	
False
EMAIL_USE_SSL	
False
TEMPLATE_CONTEXT_PROCESSORS	
('django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.tz',
 'django.contrib.messages.context_processors.messages',
 'jumpserver.context_processors.name_proc')
SESSION_COOKIE_AGE	
1209600
IP	
'0.0.0.0'
USE_ETAGS	
False
LANGUAGES_BIDI	
('he', 'ar', 'fa', 'ur')
FILE_UPLOAD_TEMP_DIR	
None
INTERNAL_IPS	
()
STATIC_URL	
'/static/'
EMAIL_PORT	
'25'
USE_TZ	
False
SHORT_DATETIME_FORMAT	
'm/d/Y P'
PASSWORD_HASHERS	
u'********************'
ABSOLUTE_URL_OVERRIDES	
{}
CACHE_MIDDLEWARE_SECONDS	
600
DB_HOST	
'10.0.0.254'
DATETIME_INPUT_FORMATS	
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER	
'bigdata@jianfeitech.com'
PROFANITIES_LIST	
u'********************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by ibuler** [comment]
你好，请测试一下 useradd_bug 分支

**Comment by ChowRex** [comment]
谢谢老广,那个分支没有问题,请问现有3.2-rc2版本和该分支有何区别?在Comparing changes无法比较release和分支,是已经添加到4.0版本了吗?
