### ISSUE TITLE
[Bug]v2.12.1在使用官网极速安装时出现tar文件无法解压问题

### ISSUE THREAD

**Issue by Archerkong** [jumpserver/jumpserver#6551]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.12.1

**系统版本**
CentOS Stream release 8 最小化安装

**Bug 描述**
download install script to /opt/jumpserver-installer-v2.12.1 (开始下载安装脚本到 /opt/jumpserver-installer-v2.12.1)
quick_start.sh:行46: tar: 未找到命令
[ ERROR ] Failed to unzip jumpserver-installer-v2.12.1 (解压 jumpserver-installer-v2.12.1 失败, 请检查网络是否正常或尝试重新执行脚本)

**Bug 重现步骤(有截图更好)**
执行结果：
![image](https://user-images.githubusercontent.com/40537619/127131010-9ed65b32-cd86-4723-9e10-ae1e56eefb55.png)
查看安装脚本发现
![image](https://user-images.githubusercontent.com/40537619/127131382-a02196e1-5293-43e1-9868-ce6049c3e3d3.png)

**建议**
将安装脚本第32行添加tar命令安装
![image](https://user-images.githubusercontent.com/40537619/127131632-4f9854f7-47a6-4ead-83b2-f82e4b417b37.png)

**Comment by wojiushixiaobai** [comment]
CentOS 8 最新版本的最小化我记得是带 tar 的，上面的操作系统都跑了一遍。
得先验证才能考虑要不要加。。可以加到上面的 DNF 判断里面，加这里可能会导致其他操作系统没这个包退出

**Comment by Archerkong** [comment]
确实
