### ISSUE TITLE
[Feature] 使用tmux 终端环境下，命令过滤器不生效

### ISSUE THREAD

**Issue by daviadong** [jumpserver/jumpserver#6553]
**请描述您的需求或者改进建议.**在centos的系统上安装了tmux工具，并进入tmux 终端环境后，发现命令过滤器不生效，并且在命令记录中也不会记录tmux 终端环境中输入的命令，这样rm等一些高危操作还是可以执行的。
![image](https://user-images.githubusercontent.com/51897467/127180685-2eef4b97-e17c-4e66-8e41-dded84d66d61.png)
![image](https://user-images.githubusercontent.com/51897467/127180823-c9f4a17d-65cf-485a-b71b-004821176974.png)
![image](https://user-images.githubusercontent.com/51897467/127181114-4e88e915-30d5-406b-b07c-c435655bdd7b.png)

**Comment by wojiushixiaobai** [comment]
防呆，不能防绕过，不是C/S架构，没办法做到更精细
