### ISSUE TITLE
[Bug] jumpserver v2.6.1 升级至v2.12.1 提示 1215  Cannot add foreign key constraint

### ISSUE THREAD

**Issue by Primeyang** [jumpserver/jumpserver#6554]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer  V2.6.1

**Bug 描述**
 jumpserver v2.6.1 升级至v2.12.1 提示 1215  Cannot add foreign key constraint

**Bug 重现步骤(有截图更好)**
1、使用 jmsctl.sh upgrade 
![image](https://user-images.githubusercontent.com/17820033/127252763-da72bba1-f49f-4058-932e-e9c060dfd084.png)

**Comment by wojiushixiaobai** [comment]
数据库字符集对不上，仔细检查下。
如果你是迁移
```bash
# 如果你不需要或不想处理数据库字符集可以跳过此步骤, 保证迁移前后的数据库字符集一样即可.
if grep -q 'COLLATE=utf8_bin' /opt/jumpserver.sql; then
    cp /opt/jumpserver.sql /opt/jumpserver_bak.sql
    sed -i 's@ COLLATE=utf8_bin@@g' /opt/jumpserver.sql
    sed -i 's@ COLLATE utf8_bin@@g' /opt/jumpserver.sql
else
    echo "备份数据库字符集正确";
fi
```
/opt/jumpserver.sql 表示旧版本备份的原始数据库

**Comment by wojiushixiaobai** [comment]
请使用原始未修改的数据库进行操作

**Comment by Primeyang** [comment]
使用原始未修改的库报最开始的错误啊！
