### ISSUE TITLE
[Feature] 非root特权用户不配置`NOPASSWD: ALL`的建议

### ISSUE THREAD

**Issue by j0ck1e** [jumpserver/jumpserver#6559]
jumpserver通过ansible实现推送系统用户等功能，ansible有个参数`ansible_become_password`可以直接指定sudo password。
像ubuntu这类的发行版，系统安装好后普通用户默认只能通过sudo password提权，在使用jumpserver添加ubuntu系统的资产会多一个配置sudoers的步骤感觉没有必要，添加特权用户时是设置过密码的。

**Comment by j0ck1e** [comment]
可以将特权用户的密码设置为`ansible_become_password`的值，这样ansible就能直接提权了

**Comment by wojiushixiaobai** [comment]
之后的版本特权用户选填。
此类操作可以在系统封装时解决，看后续其他用户反馈

**Comment by wojiushixiaobai** [comment]
此操作会增加系统的复杂度，暂时不考虑，此问题先关闭。后续有新的反馈请重新打开
