### ISSUE TITLE
[Feature] web终端页面，搜索后按资产名称或者IP地址排序

### ISSUE THREAD

**Issue by sansam** [jumpserver/jumpserver#6565]
**请描述您的需求或者改进建议.**
[当前版本v2.12.0，在web终端页面，按关键词搜索后显示的资产列表希望能按照主机名称或者IP地址进行排序显示，现在显示的很乱。

**Comment by jym503558564** [comment]
已优化：https://github.com/jumpserver/jumpserver/pull/6587
将在未来版本发布，请持续关注JumpServer发布情况。

**Comment by youliyuan-fit2cloud** [comment]
v2.13.0版本已修复
