### ISSUE TITLE
[Question] 为什么要放一张乔布斯的照片？

### ISSUE THREAD

**Issue by YangQing1989** [jumpserver/jumpserver#6568]
**请描述您的问题.**
<img width="223" alt="root" src="https://user-images.githubusercontent.com/26144773/127605742-44e480cd-ca78-471d-9c22-fef28361bb49.png">

**Comment by ibuler** [comment]
很早的版本，乔布斯是 管理员的头像，而不是后来的那个 方块，其实你再 仔细观察，还有 Python 作者的头像

致敬乔布斯改变了世界，
致敬Guido创造了Python

Guido:
![image](https://user-images.githubusercontent.com/17382885/127612053-bf92e902-0fbe-469b-9073-39306557624f.png)


现在：
![image](https://user-images.githubusercontent.com/17382885/127612087-049f4e73-9b71-4a83-bc4a-fb1c25bdb293.png)
