### ISSUE TITLE
[Question] 如何实现退出资产后, 同时自动退出jumpserver环境

### ISSUE THREAD

**Issue by gzm55** [jumpserver/jumpserver#6586]
**请描述您的问题.**

现在从控制台登录 jumper 并连接到一个资产, 操作完之后exit 离开资产shell环境, 这时控制台会留在  jumpserver 上, 使用 `q` 退出. 能否使用类似 exec 的方式登录资产, 离开资产shell 环境后, 同时也断开 jumpserver 的连接?

**Comment by Laplacence** [comment]
你可以通过直接关闭本地终端实现这个功能。

**Comment by gzm55** [comment]
本地终端还需要继续使用, 不能关闭.

**Comment by gzm55** [comment]
本地终端还需要继续使用, 不能关闭.

**Comment by jym503558564** [comment]
使用直连方式应该可以满足您的需求。
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222

**Comment by gzm55** [comment]
这个 ssh 会识别为
```
user jumpserverUsername@systemUsername@AssetIP
hostname jumpserverHostIP
```

jumpserver 对 用户名做了特殊解释吗?

**Comment by gzm55** [comment]
> 使用直连方式应该可以满足您的需求。
> ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222

实际测试也无法登录. @jym503558564 请问这个需要 server 端做配置吗?

**Comment by jym503558564** [comment]
什么版本？

**Comment by jym503558564** [comment]
JumpServer v2.11.0 开始支持直连方式

**Comment by jym503558564** [comment]
@gzm55 升级至 v2.11.0版本以上后，体验有没有满足您的需求？

**Comment by gzm55** [comment]
> @gzm55 升级至 v2.11.0版本以上后，体验有没有满足您的需求？

正在和负责的团队沟通升级事项.
