### ISSUE TITLE
[Question] v2.12.1 版本添加windows 系统用户无法自动生成密码

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#6590]
**请描述您的问题.**
你好，我想问一下 jump server v2.12.1 版本，在给windows创建系统账号的时候，选择托管密码后，也需要输入密码，以前的 v2.7.1版本是可以自动生成密码的，这需要怎么设置哪？

**Comment by jym503558564** [comment]
取消了

**Comment by QinQiang666** [comment]
这个功能很好用啊，这个密码也用不到，每次还有自己生成一个输入上去
