### ISSUE TITLE
[Question] v2.7.1  windows 的上传下载

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#6593]
**请描述您的问题.**
你好，我想问一下，windows的上传下载怎么设置，我已经安装openssh了，但是通过文件管理，或者使用拖拉的方式，都无法上传和下载
![image](https://user-images.githubusercontent.com/29726716/128174083-b14d4d91-0c3c-4983-866b-a6b588fa9aee.png)

**Comment by jym503558564** [comment]
提示已经说明了，先选择一个系统用户登录该资产。然后再进行文件操作

**Comment by QinQiang666** [comment]
在哪选择哪？这个界面上没有把，我其他界面上已经用我的自己账号登录到windows机器上了

**Comment by QinQiang666** [comment]
> 提示已经说明了，先选择一个系统用户登录该资产。然后再进行文件操作

在哪一个选择哪？这个界面上没有把，我其他界面上已经用我自己的账号登录到windows机器上了

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/128452703-fedb1eb0-5c1f-445f-8882-53480ea6d402.png)

**Comment by QinQiang666** [comment]
> 提示已经说明了，先选择一个系统用户登录该资产。然后再进行文件操作
不是啊，下边就没有了
![image](https://user-images.githubusercontent.com/29726716/128462034-9cc3f6fa-c31e-47b2-ab40-a02206a43810.png)

**Comment by jym503558564** [comment]
资产协议加上ssh，然后授权该资产和系统用户

**Comment by QinQiang666** [comment]
> 资产协议加上ssh，然后授权该资产和系统用户

也添加了，我现在可以使用jumpser来推送windows账号，登录机器，就是没办法上传下载
![image](https://user-images.githubusercontent.com/29726716/128464849-a4ef189f-cfd5-4857-84ca-e528b973b630.png)

**Comment by jym503558564** [comment]
系统用户协议也是ssh吗

**Comment by QinQiang666** [comment]
> 系统用户协议也是ssh吗

不是，系统用户是rdp，换成ssh后就远程不机器了，系统用户添加不了两个协议

**Comment by QinQiang666** [comment]
> 系统用户协议也是ssh吗

感谢，我知道怎么弄了，要创建两个系统账号，一个rdp协议一个ssh协议
