### ISSUE TITLE
[Question] 关于jumpserver openid 对接keycloak 的配制问题

### ISSUE THREAD

**Issue by banghansun** [jumpserver/jumpserver#6596]
**请描述您的问题.**
我按照官方文档配制之后，跳转时总是keycloak报错，not dound page
有没有大佬遇到这种问题？
![image](https://user-images.githubusercontent.com/34332009/128310785-c9cbc141-c81f-4ff6-b151-58d511b5a1e8.png)

**Comment by jym503558564** [comment]
配置请参考文档：[https://docs.jumpserver.org/zh/master/admin-guide/authentication/openid/?h=op](url)
