### ISSUE TITLE
[Bug]窗口重新连接问题

### ISSUE THREAD

**Issue by Hidden-Squid-1** [jumpserver/jumpserver#6597]
测试环境：jumpserver 2.12.1 /2.7.0
浏览器：google chrome

此问题出现在窗口超时后手动重新连接，导致画面崩溃的问题
1.利用jumpserver开两个窗口，等待空闲时间超时后，在一个窗口下，重新连接另一个窗口
![1](https://user-images.githubusercontent.com/77652574/128314807-058aefed-2af6-420a-95a6-31137ac339bd.jpeg)

2.切到重新连接后的窗口，发现没有屏幕输出，并且整个终端界面卡死
![2](https://user-images.githubusercontent.com/77652574/128314821-c213d3f5-ddaf-43b3-b1ea-3e7a542185dd.jpeg)

3.等待一段时间后，界面崩溃
![3](https://user-images.githubusercontent.com/77652574/128314832-f1c30e23-f9bf-4fed-ba64-bb1344b580dc.jpeg)

**Comment by jym503558564** [comment]
无法复现
