### ISSUE TITLE
[Bug] 用户列表中不显示CAS用户

### ISSUE THREAD

**Issue by charliewch** [jumpserver/jumpserver#6598]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Google Chrome 版本 92.0.4515.131（正式版本） （64 位）

**Bug 描述**
Jumpserver版本 v2.11.1 GPLv2
jumpserver接入CAS之后，用户通过CAS访问之后，在用户列表中无法显示CAS用户。
通过查询数据库可以查到相应的用户记录。

**Bug 重现步骤(有截图更好)**
1.  JumpServer接入CAS
2. 用户通过CAS访问JumpServer（JumpServer数据库中无同名用户）
3. 如下图，通过查询数据库有一个CAS用户记录，界面访问用户列表却没有显示。
![image](https://user-images.githubusercontent.com/25027060/128443963-c72c5c16-8833-4c9c-8766-13853a03e413.png)
![image](https://user-images.githubusercontent.com/25027060/128443987-fe51cd33-a4fb-4cea-a452-76fd3fd5d873.png)

**Comment by jym503558564** [comment]
@charliewch 更新到2.11.4或者2.12.1版本，已解决该问题

**Comment by jym503558564** [comment]
我们在2.11.2时，对此问题进行了修复。可关注我们release更新情况。
![image](https://user-images.githubusercontent.com/40739051/128444725-9a3d2bcd-a0ba-423e-8709-99c25ce6d98d.png)

**Comment by jym503558564** [comment]
@charliewch 更新后，问题还存在吗

**Comment by charliewch** [comment]
升级后解决了，谢谢哈
