### ISSUE TITLE
python3.6登陆提示错误module 'ldap' has no attribute 'dn'

### ISSUE THREAD

**Issue by laiwahwah** [jumpserver/jumpserver#660]
AttributeError at /users/login
module 'ldap' has no attribute 'dn'

使用python2正常
貌似是django-ldap-auth不支持python3
请问有什么好的解决方法

**Comment by ibuler** [comment]
我曾经在 python3.5上测试过

**Comment by laiwahwah** [comment]
更换新的虚拟环境测试通过
