### ISSUE TITLE
[Bug] LDAP用户无法绑定企业微信

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#6604]
**JumpServer 版本(v1.5.9以下不再支持)**

2.12.1
**浏览器版本**

edge 92
**Bug 描述**
用户为ladp用户导入 绑定企业微信按钮为灰色

**Comment by jym503558564** [comment]
目前占不支持第三方认证绑定企业微信或者钉钉

**Comment by wushengmin** [comment]
> 目前占不支持第三方认证绑定企业微信或者钉钉

请问后续会更新支持吗

**Comment by zalmanzhao** [comment]
请问后续会更新支持吗

**Comment by jym503558564** [comment]
目前还未规划



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zalman Zhao ***@***.***&gt;
发送时间: 2021年8月20日 17:27
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[jumpserver/jumpserver] [Bug] LDAP用户无法绑定企业微信 (#6604)

**Comment by wojiushixiaobai** [comment]
v2.14.1 已支持
