### ISSUE TITLE
快速安装脚本出现安装Docker错误

### ISSUE THREAD

**Issue by ppoiissbsjksms** [jumpserver/jumpserver#6605]
>>> Install and Configure Docker
1. Install Docker
Starting to download Docker engine ...

[ERROR] Download docker fails, check the network is normal

 config-example.txt中DOCKER_IMAGE_PREFIX=swr.cn-south-1.myhuaweicloud.com无法ping通
查询得知华为云容器镜像服务 SWR终端节点地址已更换为swr-api.cn-south-1.myhuaweicloud.com
修改DOCKER_IMAGE_PREFIX=swr-api.cn-south-1.myhuaweicloud.com
执行./jmsctl.sh install
安装docker依旧报错[ERROR] Download docker fails, check the network is normal

**Comment by wojiushixiaobai** [comment]
手动执行下面代码验证网络是否有问题
```sh
DOCKER_BIN_URL="https://mirrors.ustc.edu.cn/docker-ce/linux/static/stable/$(uname -m)/docker-${DOCKER_VERSION}.tgz"
wget -q "${DOCKER_BIN_URL}" -O /tmp/docker.tar.gz
```

**Comment by ppoiissbsjksms** [comment]
> 手动执行下面代码验证网络是否有问题
> 
> ```shell
> DOCKER_BIN_URL= " https://mirrors.ustc.edu.cn/docker-ce/linux/static/stable/ $( uname -m ) /docker- ${DOCKER_VERSION} .tgz " 
> wget -q " ${DOCKER_BIN_URL} " -O /tmp/docker.tar.gz
> ```
> 
> * [ ] 链接：[https](https://github.com/jumpserver/installer/blob/master/scripts/0_prepare.sh#L23) : [//github.com/jumpserver/installer/blob/master/scripts/0_prepare.sh#L23](https://github.com/jumpserver/installer/blob/master/scripts/0_prepare.sh#L23)

无法下载docker.tar.gz,如何修改为国外镜像地址?

**Comment by wojiushixiaobai** [comment]
执行下面的命令：
- [ ] Install Docker
```sh
DOCKER_BIN_URL="https://download.docker.com/linux/static/stable/$(uname -m)/docker-${DOCKER_VERSION}.tgz"
wget -q "${DOCKER_BIN_URL}" -O /tmp/docker.tar.gz
```
- [ ] Install Docker-Compose
```sh
curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
然后重新执行安装脚本即可
