### ISSUE TITLE
[Feature] ssh直连服务器命令能否增加 command 功能

### ISSUE THREAD

**Issue by 580825** [jumpserver/jumpserver#6607]
**请描述您的需求或者改进建议.**
现有功能:
        ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP

期望功能:
        ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP "hostname"

就是增加ssh command功能，多谢

**Comment by wojiushixiaobai** [comment]
不支持流量穿透
