### ISSUE TITLE
登陆时报错CSRF验证失败. 请求被中断.

### ISSUE THREAD

**Issue by LonersBoy** [jumpserver/jumpserver#6608]
**请描述您的问题.**
使用jumpserver/jms_all:v2.12.1镜像在k8s 1.18.8-aliyun.1中部署deployment以后，无法正常登陆，一直报错，使用的是外置的redis和mysql

![image](https://user-images.githubusercontent.com/42741069/128659000-6052dcf3-69da-4ede-877f-06c304179a7f.png)

**Comment by linl12138** [comment]
部署在K8s里面访问服务因为有4，7层转发，会导致这个校验不过，建立在源码里面将这个校验取消掉

**Comment by AlliotTech** [comment]
2.24.2 -> 2.25.2 后再次出现csrf验证失败的错误  

### 请求路径： 
client -> 外部nginx -> jumpserver  

### 部署方式  
一键脚本  

![image](https://user-images.githubusercontent.com/24980252/186389057-4c1fd3d4-a717-4e26-a206-c2efbd60343d.png)
