### ISSUE TITLE
如果是linux的系统 但是使用xrdp方式接入jumpserver，会被jumpserver 判断为windows 系统，挂载网盘看不到了，这个怎么解决？

### ISSUE THREAD

**Issue by huyifanstar** [jumpserver/jumpserver#6609]
如果是linux的系统 但是使用xrdp方式接入jumpserver，会被jumpserver 判断为windows 系统，挂载网盘看不到了，这个怎么解决？

似乎linux使用的ssh/scp的方式？
windows 使用的网盘挂载

**Comment by jym503558564** [comment]
可以重新图文并茂描述一下您的问题吗？

**Comment by huyifanstar** [comment]
我后面使用vnc方式了
