### ISSUE TITLE
希望可以在邮件中附带使用方法

### ISSUE THREAD

**Issue by ChowRex** [jumpserver/jumpserver#661]
修改jumpserver/juser/user_api.py 向地171行以后添加一行
文档下载链接: %s//static/files/documents/README.txt

说明内容 README.txt

# 跳板机使用文档说明
# 作者：ChowRex
# 最后更新时间 2017-08-30

# 1.接收到的邮件中附有密钥下载地址，请首先访问该地址
# 2.浏览器此时显示需要提供用户名密码，请输入邮件中提供的用户名和web登录密码
# 3.下载您个人的pem密钥文件，并保存至不会被误删的文件夹中

# Windows 用户
# 列举几个常用的SSH客户端配置方法
# |  4.1. Xshell
# |      a.打开Xshell主界面 -> 工具 -> 用户密钥管理者 -> 导入 -> 选择刚才的pem文件
# |      -> 输入邮件中提供的ssh密钥文件密码
# |      b.点击Xshell左上角的新建 -> 名称:输入一个名称 -> 协议:选择SSH
# |      -> 主机:输入堡垒机地址 -> 端口号:输入堡垒机端口号(选填) -> 左侧类别点击 用户身份验证
# |      -> 方法:选择Public Key -> 用户名:输入邮件中提供的用户名 -> 密钥选择刚才导入完成的pem
# |      -> 密码:输入邮件中的SSH密钥文件密码 -> 左侧类别点击 终端 -> 最下面的编码:选择UTF-8
# |      -> 点击确定保存 -> 测试是否可以登录
# |  4.2. Putty
# |      a.首先打开PuTTY Key Generator(PuTTYgen)工具 -> 点击Load -> 文件类型: 选择All Files
# |      -> 找到刚才下载的pem文件位置并打开pem -> 输入邮件中的SSH密钥文件密码 -> 点击OK
# |      -> 弹出PuTTYgen Notice 点确定 -> 点击 Save private key -> 弹出PuTTYgen Warning 选 是
# |      -> 保存至不会被误删的位置
# |      b.打开PyTTY主界面 -> Host Name 输入堡垒机地址 -> Port 输入堡垒机端口号(选填)
# |      -> Connection type 选择SSH -> 左侧 Category 依次展开 Connection>SSH>Auth
# |      -> 最下面有一项 Private key for authentication 点击Browse.. 选择刚才保存的ppk文件
# |      !!如果需要保存,请先切换到Session然后在Saved Sessions下面输入名称 点击右边Save按钮!!
# |      最后测试能否登录(login as 填写邮件中提供的用户名)
# |  4.3. SecureCRT
# |      a.打开SecureCRT程序 -> 协议:选择SSH2 -> 主机名:输入堡垒机地址 -> 端口:输入堡垒机端口号(选填)
# |      -> 防火墙:选择None -> 用户名:输入邮件中提供的用户名 -> 鉴权>选中公钥>点击属性
# |      -> 选择 使用回话公钥设置 -> 会话设置中选择使用身份或证书文件 -> 点击右边... 
# |      -> 选择刚才保存的pem文件 -> 点击确定 -> 点击连接 -> 提示输入安全外壳密码
# |      -> 点击跳过 -> 提示输入安全外壳通行短语 -> 输入邮件中提供的SSH密钥文件密码
# |      -> 点击确定 -> 此时乱码状态 依次点击 文件>连接>右键刚才的配置文件>属性
# |      -> 左侧的类别展开 终端>外观 -> 右侧字体选项栏中修改字符编码为UTF-8 -> 点击确定
# |      -> 双击刚才的配置文件 测试连接 (提示输入安全外壳密码一律选择跳过)

# Linux & Mac 用户
# 使用下载好的pem文件可以直接连接到服务器 命令如下
# ssh -i [pem文件] (-p [端口号]) [用户名]@[服务器地址]
# 然后按照提示输入邮件中提供的SSH密钥文件密码
# 如果嫌麻烦,可以使用以下命令删除掉密码
# openssl rsa -in [带密码的pem文件] -out [不带密码的pem文件]
# 这样可以通过输入一次密码生成一个不含密码的pem文件
# 每次输入-i,很烦?  执行命令 ssh-add [pem文件]
# 执行报错? {Could not open a connection to your authentication agent}  执行 eval $(ssh-agent) 然后再试一次
# 还嫌麻烦....  好吧 可以用alias实现
# 向.bashrc或.bash_profile中写入类似如下的内容
# alias conn='ssh -i $HOME/.ssh/chowrex.pem chowrex@vps'

**Comment by ChowRex** [comment]
还有一个问题 使用wiki上提供的nginx配置 并不能将前端代理到ssl

**Comment by lanbing222** [comment]
我设置的邮箱一直发送不了邮件，你那里有指导没

**Comment by ibuler** [comment]
不错的建议，0.4版本有个参数可以使用 https://github.com/jumpserver/jumpserver/blob/dev/config_example.py#L96
