### ISSUE TITLE
[Bug] 前端页面执行命令，窗口日志不显示

### ISSUE THREAD

**Issue by lawrence191** [jumpserver/jumpserver#6610]
**JumpServer 版本(v1.5.9以下不再支持)**
2.10.4

**浏览器版本**
chrome  92.0.4515.131

**Bug 描述**
在前端远程操作主机，例如点击【测试】，测试堡垒机到主机的连通性，会弹出一个单独的页面展示ansible执行的过程以及结果。但是该页面有时候会显示，有时候又不显示。
异常时：
![Snipaste_2021-08-09_18-56-24](https://user-images.githubusercontent.com/15275116/128696543-957fca26-a662-4f60-b5bd-27a55ae298e0.png)
但查看服务器上对应的日志是有的：
![Snipaste_2021-08-09_19-00-45](https://user-images.githubusercontent.com/15275116/128696687-c728318f-0633-4e69-8306-a70c2cd05fea.png)

如果此时，再重新刷新整个页面，重新点击【测试】，则又可以看到窗口显示出日志了。
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
确认反向代理添加了websocket相关参数
