### ISSUE TITLE
[Feature] 建议加入区块链技术

### ISSUE THREAD

**Issue by rayPan2333** [jumpserver/jumpserver#6612]
**请描述您的需求或者改进建议.**
是否可以在堡垒机网络安全逻辑里加入区块链技术，构建新的网络安全防御体系，通过对一些敏感数据如用户操作、日志、权限变更记录等数据上链，利用区块链不可篡改的特性提高数据的真实性和可靠性，利用区块链的去中心化结构抵抗针对中心节点的分布式拒绝服务攻击，进一步提高网络安全能力。
～～只是结合当前区块链技术和网络拓扑做一些思考建议，如果可以希望采纳～～
@fit2cloudrd

**Comment by BaiJiangJie** [comment]
@orangemio 爽来研究一下。

**Comment by orangemio** [comment]
没有任何意义

**Comment by BaiJiangJie** [comment]
`没有任何意义`
I think so too！[微笑]
