### ISSUE TITLE
dev分支写环境要求是python3.5 ，但是会调用3.6的一些信息

### ISSUE THREAD

**Issue by lanbing222** [jumpserver/jumpserver#662]
[33mjumpserver    |^[[0m     return view_func(*args, **kwargs)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 86, in view
^[[33mjumpserver    |^[[0m     return self.dispatch(request, *args, **kwargs)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
^[[33mjumpserver    |^[[0m     response = self.handle_exception(exc)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
^[[33mjumpserver    |^[[0m     self.raise_uncaught_exception(exc)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
^[[33mjumpserver    |^[[0m     response = handler(request, *args, **kwargs)
^[[33mjumpserver    |^[[0m   File "/opt/jumpserver/apps/applications/api.py", line 78, in create
^[[33mjumpserver    |^[[0m     TerminalHeatbeat.objects.create(terminal=terminal)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
^[[33mjumpserver    |^[[0m     return getattr(self.get_queryset(), name)(*args, **kwargs)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
^[[33mjumpserver    |^[[0m     obj.save(force_insert=True, using=self.db)
^[[33mjumpserver    |^[[0m   File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
^[[33mjumpserver    |^[[0m     force_update=force_update, update_fields=update_fields)

**Comment by hellorocky** [comment]
应该是python3.5+, python3.5和python3.6对于jumpserver没区别

**Comment by lanbing222** [comment]
安装python3.6.1依然报错，问题一直是创建数据库的时候报错

**Comment by hellorocky** [comment]
我回答的是你的标题, 具体报错, 你提供的错误日志不全
