### ISSUE TITLE
rz、sz方式的文件上传、下载记录在文件审计日志找不到

### ISSUE THREAD

**Issue by superHuang476** [jumpserver/jumpserver#6623]
**请描述您的问题.**
rz、sz方式的文件上传、下载记录在文件审计日志找不到。

**Comment by jym503558564** [comment]
v2.13.0版本将支持rz、sz日志审计

**Comment by superHuang476** [comment]
> v2.13.0版本将支持rz、sz日志审计

什么时候出2.13.0版本【手动狗头】

**Comment by LeeEirc** [comment]
已发布v2.13版本，支持对 rz 、sz的文件日志审计。
