### ISSUE TITLE
[Bug] 在设置上有一个右键快速粘贴，没用； 在用VIM编辑文档的时候，回车总是空好几个字符，不是顶格的

### ISSUE THREAD

**Issue by liang2025** [jumpserver/jumpserver#6625]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.1

**浏览器版本**
google 92.0.4515.131

**Bug 描述**
在设置上有一个右键快速粘贴，没用； 
在用VIM编辑文档的时候，回车总是空好几个字符，不是顶格的，再按回格健，它是直接把空格前的字符给删，而不是把删的这些空格，如果是从外复制粘贴进来的，格式会变得很随意，要么多空好几格，要么少空好几格，要么有格式看着正常，粘贴进去有些空格就报异常，像yml文件对格式要求很严格的，直接就报错，除非是在外面编辑好的文档，整个文档拷贝进来。用得还是有些难受的

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
右键快速粘贴，只有在新的会话生效。vim复制的问题，使用新版本 v2.14.1 试试?

**Comment by dowliu** [comment]
vim复制的问题可以修改/etc/vimrc配置文件，添加set paste试试。

**Comment by dowliu** [comment]
vim复制的问题可以修改/etc/vimrc配置文件，添加set paste试试。
