### ISSUE TITLE
[Bug] 安装的时候出错： [ERROR] 表结构变更失败!

### ISSUE THREAD

**Issue by panda8z** [jumpserver/jumpserver#6630]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.10.5

**Ubuntu版本**

20.04 LTS

**浏览器版本**
不涉及 浏览器

**Bug 描述**

``` log
7. 初始化数据库
jms_mysql is up-to-date
jms_redis is up-to-date
Unable to find image 'jumpserver/core:v2.10.5' locally
docker: Error response from daemon: manifest for jumpserver/core:v2.10.5 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
[ERROR] 表结构变更失败!
```

**Bug 重现步骤(有截图更好)**

1. 执行 一键安装脚本 `curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.10.5/quick_start.sh | bash
`
2. 安装过程全部使用默认配置。
3. 在第七步报错：如下图

<img width="1335" alt="Screen Shot 2021-08-12 at 4 50 52 PM" src="https://user-images.githubusercontent.com/24646937/129168014-93279c5b-7046-4efc-b12d-81cd15586aee.png">

**Comment by panda8z** [comment]
[jumpserver/core Tags | Docker Hub](https://hub.docker.com/r/jumpserver/core/tags?page=1&ordering=last_updated) 我看了下 Docker Hub  确实没有新的 tag，导致 没有拉取到新的 image

**Comment by wojiushixiaobai** [comment]
@panda8z 使用 v2.12.2 即可
