### ISSUE TITLE
[Question] 新建系统用户推送失败

### ISSUE THREAD

**Issue by leozz705** [jumpserver/jumpserver#6636]
新建系统用户推送失败是咋回事？
认证方式选的是 托管密码 自动生成
授权之后登录还是报：  认证失败（用户名或密码错误）
该系统用户的资产列表里测试可连接性和推送系统用户都是失败的，求解！？

**Comment by LizhenQiangCOOL** [comment]
先确认： 资产列表中机器有没有添加  “认证用户”
