### ISSUE TITLE
[Bug] windows资产粘贴板失效

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#6637]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.10.3

**浏览器版本**
Chrome Version 92.0.4515.131 (Official Build) (64-bit)

**Bug 描述**
远程windows粘贴板失效，在切换窗口1次或者多次后无法继续粘贴进堡垒机。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by mynameisshiy** [comment]
感觉是堡垒机里面的输入法和外部的输入法冲突导致的。我切换输入法后，快捷键就有效了。不知道能否解决

**Comment by Laplacence** [comment]
@mynameisshiy 谢谢回复，我复制的是powershell命令，用的微软ENG键盘，现在大致发现是直接进行powershell右键粘贴会导致粘贴板失效，ctrl+v不受影响。其他场景有待观察
