### ISSUE TITLE
V2.12.2 部署环境 K8S+INGRESS 未使用HELM

### ISSUE THREAD

**Issue by micrsun** [jumpserver/jumpserver#6641]
**请描述您的问题.**

问题1： 输入账密后提示“设置你的浏览器支持cookie”  chrome都将该站点加入cookie白名单依旧

问题2： 登陆后台后反复提示“账号已退出，请重新登陆”
<img width="512" alt="不断要求重新登陆" src="https://user-images.githubusercontent.com/41136860/129480314-ac1302d6-2a17-4b9f-be61-28579a4ed32b.png">

问题3： 伴随问题2 报过websocket错误

怀疑是Nginx配置文件导致的，是否有Nginx配置文件供借鉴 ?  看过官网的nginx反代，没测试成功；K8S的ingress本身也是nginx反向代理

**Comment by wojiushixiaobai** [comment]
ingress 需要加上 websocket 相关设置
