### ISSUE TITLE
希望企业版的云管中心对接的云再增加一点

### ISSUE THREAD

**Issue by daviadong** [jumpserver/jumpserver#6642]
打算购买企业版，现在目前公有云有google云和oracle云，希望能在云管中心模块中添加google云和oracle云两种云的对接

**Comment by ibuler** [comment]
谷歌云在计划中

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/152742081-8f97e520-f9b1-459a-bb6a-eb20ca7f47c7.png)
谷歌云已支持
