### ISSUE TITLE
v2.5.3如何开启ipv6[Question] 

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#6655]
**请描述您的问题.**
如题，v2.5.3版本如何开启ipv6？

**Comment by wojiushixiaobai** [comment]
- [ ] [启用 IPV6 支持](https://docs.jumpserver.org/zh/master/install/use_ipv6/)

**Comment by rty813** [comment]
> * [x]  [启用 IPV6 支持](https://docs.jumpserver.org/zh/master/install/use_ipv6/)

2.5.3没有这个配置。
