### ISSUE TITLE
[Bug] 数据库界面连接账号密码正确也提示输入账号密码

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#6661]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
chrome

**Bug 描述**
添加MySQL数据库资产，数据库名称中包含中划线(-)
关联已经托管密码的用户后
登录数据库资产提示重新输入密码

**Bug 重现步骤(有截图更好)**
1.  
![4961629185809_ pic_hd](https://user-images.githubusercontent.com/44662176/129694198-fc299ebd-96d8-4ed6-b4a0-d4a847fef551.jpg)

2. 
3.

**Comment by wojiushixiaobai** [comment]
试试新版本
