### ISSUE TITLE
文件上传下载问题：可以下载文件，不能上传文件

### ISSUE THREAD

**Issue by Owenxh** [jumpserver/jumpserver#667]
上传文件总是提示失败，请问可能是什么原因呢?

ssh和web上传都失败，但均可以从服务器上下载文件

注：进入jumpserver内部使用rz命令可以成功上传文件到jumpserver
       批量执行命令，也不行，提示如下：
      Ansible> pwd

[ app.risk.001 => failed]

Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1504263123.58-9364335342879 && echo $HOME/.ansible/tmp/ansible-tmp-1504263123.58-9364335342879, exited with result 1

**Comment by ibuler** [comment]
你的/tmp目录权限有问题，所以这个用户无法传递过去
