### ISSUE TITLE
升级报错如下

### ISSUE THREAD

**Issue by maomaoaichirou** [jumpserver/jumpserver#6686]
安装部署官方的镜像仓库是否缺少最新版本镜像，麻烦确认下。
升级时报错如下：
Error response from daemon: manifest for swr.cn-south-1.myhuaweicloud.com/jumpserver/lina:v2.12.2 not found: manifest unknown: Not Found tag
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lina:v2.12.2
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/lina:v2.12.2

**Comment by wojiushixiaobai** [comment]
参考文档升级，升级需要先更新 installer，你的 installer 版本不正确导致。
