### ISSUE TITLE
取消系统管理员密码至能30个字符的限制

### ISSUE THREAD

**Issue by sum86** [jumpserver/jumpserver#669]
![image](https://user-images.githubusercontent.com/14838827/29993103-e77b29b6-8fdf-11e7-90c2-023dcea9438b.png)
我的设置的是64个字符

**Comment by ibuler** [comment]
这个意义不大吧，30个应该已经够长了

**Comment by ibuler** [comment]
你可以自己更改那部分代码取消掉这个限制
