### ISSUE TITLE
[Question] v2.5.3如何开启ipv6

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#6690]
v2.5.3如何开启ipv6

**注意版本！是v2.5.3。下图的文档不适用，找不到对应的配置**
![image](https://user-images.githubusercontent.com/22488813/130037080-a3ab6d83-5f9a-49c0-a6a3-947fde854e86.png)

**Comment by wojiushixiaobai** [comment]
请更新至新版本，或者参考 docker 官方文档处理即可。
