### ISSUE TITLE
[Bug] 无法收集AMDcpu型号

### ISSUE THREAD

**Issue by qianshijinshen** [jumpserver/jumpserver#6698]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.12.2

**浏览器版本**
google chrome v92.0.4515.131

**Bug 描述**
Ubuntu收集资产信息时，无法收集AMDcpu型号

**Bug 重现步骤(有截图更好)**
1.  通过web界面点击‘更新节点硬件资产信息’时，无法收集AMD菜谱型号，Intel 的正常
2. 
![image](https://user-images.githubusercontent.com/48887652/130173223-4a3cf496-21b5-4ce9-8790-dd919fde4d08.png)

**Comment by ibuler** [comment]
不知道 amd 返回的数据是什么，手头没有环境

**Comment by qianshijinshen** [comment]
显示未知




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Bug] 无法收集AMDcpu型号 (#6698)





 
不知道 amd 返回的数据是什么，手头没有环境
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jym503558564** [comment]
已记录，等待环境进行测试反馈。
