### ISSUE TITLE
[Bug] lina 资产节点树报错

### ISSUE THREAD

**Issue by yenkeia** [jumpserver/jumpserver#6702]
**JumpServer 版本(v1.5.9以下不再支持)**

2.13.0

**浏览器版本**

**Bug 描述**

2.12.x 资产树是正常的, 升级到 2.13.0 后无法展开资产树, 不知道是不是跟[这个 commit](https://github.com/jumpserver/lina/commit/8906fa32921c5235c0581d551f1e5314db263947) 有关

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/15378777/130189581-083a3eaf-cf91-455f-bebd-dfa3fc197b1a.png)

**Comment by wojiushixiaobai** [comment]
更新 v2.13.1 即可

**Comment by yenkeia** [comment]
已经更新到到 v2.13.1
还是有问题, 创建子节点报错: 
![image](https://user-images.githubusercontent.com/15378777/130715635-5779fe53-1cb5-435d-878f-b3f24c63b829.png)
![image](https://user-images.githubusercontent.com/15378777/130715721-73de58cc-5fbc-4392-a33e-fafdf85f6a51.png)
