### ISSUE TITLE
安装jumpserver是，依赖关系安装错误

### ISSUE THREAD

**Issue by linuxwcy** [jumpserver/jumpserver#6711]
**请描述您的问题.**
jumpserver/requirements/deb_requirements.txt  里面的tcl8.5-dev、tk8.5-dev  安装失败

**Comment by linuxwcy** [comment]
![image](https://user-images.githubusercontent.com/89286735/130309306-c6cfa405-ef3f-497e-8ae5-ea05fc8bae2f.png)

**Comment by wojiushixiaobai** [comment]
参考此文档 https://docs.jumpserver.org/zh/master/dev/build/#_3
