### ISSUE TITLE
[Bug] Nginx版本问题

### ISSUE THREAD

**Issue by Dog4j** [jumpserver/jumpserver#6715]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  无法启动，ERROR: manifest for jumpserver/nginx:v2.13.1 not found
<img width="488" alt="1" src="https://user-images.githubusercontent.com/16625814/130406595-5f212e12-e9a8-4f9f-b6ee-102c7d8299d4.png">

**Comment by wojiushixiaobai** [comment]
更新 installer 到 v2.13.1
