### ISSUE TITLE
[Question] 请问，jumpserver 从版本1.5.7 升级到 2.13.1 应该怎么升级，包括数据迁移？

### ISSUE THREAD

**Issue by lcm-linux** [jumpserver/jumpserver#6716]
**请描述您的问题.**
请问，jumpserver 从版本1.5.7 升级到 2.13.1 应该怎么升级，包括数据迁移？

**Comment by wojiushixiaobai** [comment]
[未使用 installer 部署的用户请参考迁移说明迁移到最新版本](https://docs.jumpserver.org/zh/master/install/migration/)
