### ISSUE TITLE
[Bug] Windows资产快捷键经常无效

### ISSUE THREAD

**Issue by wangyu0310** [jumpserver/jumpserver#6719]
**JumpServer 版本(v1.5.9以下不再支持)**
  Version v2.13.1-101 GPLv2.

**浏览器版本**
 360极速浏览器-极速模式（Chrome内核版本：86.0.4240.198）

**Bug 描述**
 一、Windows资产快捷键经常无效,具体表现为：
    1、按Ctrl+C 出现Ctrl+Shift+C
    2、按Ctrl+V 出现Ctrl+Shift+V
    3、按Ctrl+Z 出现Ctrl+Shift+Z 
      ........
 等等类似快捷键异常问题，重连终端后可恢复。

二、上传文件进度条缺失，记得历史版本会显示上传进度，新版本未体现。

**Bug 重现步骤(有截图更好)**
 1.  
 2. 
 3.

**Comment by jym503558564** [comment]
更新至最新版本进行测试，优化了上传体验，上传进度条等。同时也优化了快捷键使用
