### ISSUE TITLE
[Feature] 通过 LDAP 导入的用户，应该可以使用第三方登录功能

### ISSUE THREAD

**Issue by wy-z** [jumpserver/jumpserver#6720]
### 使用场景

从 AD/LDAP 中导入用户，并支持飞书登录。

### 详细说明

现在的实现不允许任何非 Local 用户使用第三方登录，但是 LDAP 用户与本地用户除密码认证外，并无其他差异，应该是可以使用飞书、微信等作为第三方登录的。
如果愿意接受这个建议，我可以提交个 PR。

#### Core

https://github.com/jumpserver/jumpserver/blob/187329b006d89cc2cb067da8c1f9661ecd13ea6d/apps/authentication/mixins.py#L246

#### Lina

https://github.com/jumpserver/lina/blob/e030fc313eb2d3b976d0aec8c4f2068c9c51f678/src/userviews/users/UserProfile/ProfileInfo.vue#L96

### 感谢🙏

**Comment by xuxinwen** [comment]
可以接受
