### ISSUE TITLE
[Bug] 我的资产无法正常显示和操作

### ISSUE THREAD

**Issue by yangjule126** [jumpserver/jumpserver#6733]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
chrome最新版 92.0.4515.159

**Bug 描述**
1 我的资产的资产目录树显示不正常（少了所属类别）
2 在资产动作那里没有按键，全是全白无法操作。

**Bug 重现步骤(有截图更好)**
1.  点我的资产
2. 查看目录树：没有带资产所在的分类，且资产的动作位置是没有按键的。

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/releases/tag/v2.13.2
