### ISSUE TITLE
[Bug] jumpserver连接的redis数据库不支持特殊字符如“#”，否则会提示连接失败

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#6734]
**JumpServer 版本(v1.5.9以下不再支持)**

v1.12
**浏览器版本**

chrome
**Bug 描述**
 jumpserver连接的redis数据库不支持特殊字符如“#”，否则会提示连接失败

**Bug 重现步骤(有截图更好)**
1.  部署过程中修改redis的默认密码，密码中若带特殊字符“#”
2. core组件提示连接数据库失败
3.

**Comment by ibuler** [comment]
环境变量设置的参数，最好不要有特殊字符
