### ISSUE TITLE
[Feature] 2.13.2能否还原连接资产的账号用户信息允许修改？

### ISSUE THREAD

**Issue by uranus829** [jumpserver/jumpserver#6738]
**请描述您的需求或者改进建议.**
普通用户为动态用户名，认证方式为手工输入。当连接资产的时候，默认把用户名填充了，目前新版本用户名不允许修改了。
PS：我们内部登录资产授权的域用户管理员权限和域登录用户不一样的，域登录用户本身是没有本地管理员权限，所以登录的时候需要修改一下。现在都要添加系统用户授权到资产了。

![ec697b79af3555fe05c6fd6a73fc3e0](https://user-images.githubusercontent.com/46716344/131233561-dbd44446-5d21-4f3c-9b92-ac8551d1e3f8.png)

![d1acc28f27b0b768cb123da091c8b37](https://user-images.githubusercontent.com/46716344/131233567-074b2686-88d1-469d-bbf7-c8a35906f189.png)

**Comment by ibuler** [comment]
动态用户名就是指的和当前用户名一致

**Comment by ibuler** [comment]
不用动态用户名是不是就行了

**Comment by uranus829** [comment]
> 不用动态用户名是不是就行了

不用动态用户名相当于登录的时候就没有把用户名带上来，目前我们的管理员权限只是在原有的用户名上面加上a_ ，钩上动态用户名后，我们直接在登录资产的时候修改下用户名就可以了，这样比没有钩选动态用户名的方便很多。所以希望把修改用户名这个限制还原一下。

**Comment by BaiJiangJie** [comment]
v3 有更新，升级体验一下。
