### ISSUE TITLE
jumpserver 0.3.2 连接超时会断开

### ISSUE THREAD

**Issue by lichenglongqi** [jumpserver/jumpserver#674]
用户通过jumpserver连接服务器之后，过一段时间不使用就会断开，请问修改哪里可以让会话不超时断开？

**Comment by hellorocky** [comment]
https://github.com/jumpserver/jumpserver/blob/64b7fb6a3debb9b319ccfd2a6ada5aa0825cac91/jumpserver/settings.py#L175

https://github.com/jumpserver/jumpserver/blob/64b7fb6a3debb9b319ccfd2a6ada5aa0825cac91/jlog/log_api.py#L97

参考, 最简单的办法注释掉那个crontab, 不过这样的话系统建立的链接越来越多, 越来越慢

**Comment by lichenglongqi** [comment]
@hellorocky   请问，这个是每10分钟会杀空闲的会话？

**Comment by hellorocky** [comment]
每10分钟检查一次, 杀一小时空闲会话, 看看代码, 不难
