### ISSUE TITLE
[Feature] 建议增加或优化的功能

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#6740]
目前已经从v2.6.1升级到v2.13.2，使用了几天后针对新旧版本的使用体验对比，附上一下几个需求点：
1、老版本使用Cua的时候，辅助剪贴板可以通过ctrl+alt+shift呼出，从v2.10开始使用Lion后没有这个快捷键了，通过点击右侧剪贴板按钮非常不方便。希望能后恢复这个快捷键，除非能够很好解决各种浏览器的直接复制粘贴功能。
2、上传文件的进度条消失了，希望在新版中显示进度条。因为组件更换了，所以我没有当做bug提交，就当做是新版本的一项需求吧。
3、连接windows资源时，很明显能感觉到Lion替换了鼠标，这样一些窗口改变尺寸时鼠标的边界特效会不显示，需要自己找感觉。可能是为了解决其他问题而设置吧，希望能够有一个开关来控制是否替代系统鼠标。
4、希望能够优化资产“可连接”状态，目前这个功能全部显示黄色，没有实际作用。我们在一次资产清理工作中，很难判断主机是否停机，只能去对比一些监控工具。这个功能并不影响整体操作体验，如果有精力的情况下，可以考虑优化。

以上拙见。望采纳。

**Comment by ibuler** [comment]
- [ ] 可以考虑快捷键唤出
- [ ] 有计划
- [ ] 应该是个参数 
- [ ] 不太好做，没有成行方案

**Comment by BaiJiangJie** [comment]
可以体验一下 v3 版本，然后再新版本中提一些需求和建议。
