### ISSUE TITLE
[Question] 请问一下搜索主机的时候可以精确匹配么？

### ISSUE THREAD

**Issue by kingsxw** [jumpserver/jumpserver#6742]
**请描述您的问题.**
请问一下搜索主机的时候可以精确匹配么？
比如我只想搜索192.168.1.1，可以不显示192.168.1.1x和192.168.1.1xx吗？

**Comment by todest** [comment]
+1,希望可以有个开关是否可以对资产名称精确搜索，因为名称也是IP，所以搜IP经常会出来一堆。
