### ISSUE TITLE
[Bug] 源码启动core 部分表不存在

### ISSUE THREAD

**Issue by huolunl** [jumpserver/jumpserver#6744]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.13.2

**浏览器版本**

**Bug 描述**

执行 ./jms start 时 ， 部分表不存在
![image](https://user-images.githubusercontent.com/39933378/131434881-0f5bfd6b-8ef4-440f-96ad-c23cb16f332c.png)
![image](https://user-images.githubusercontent.com/39933378/131434920-f634c429-c96b-4296-9b1a-a00e308a7a0d.png)

**Bug 重现步骤(有截图更好)**
1.  ./jms start

**Comment by wojiushixiaobai** [comment]
初始化失败，请删库重新执行
