### ISSUE TITLE
[Bug] windows登录时的loading动画在不同分辨率显示器下位置不一致

### ISSUE THREAD

**Issue by mynameisshiy** [jumpserver/jumpserver#6748]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver v2.11.0 以后的版本

**浏览器版本**
Chrome、safari

**Bug 描述**
高分辨显示器下windows的loading动画在页面的底部，低分辨率时在中间显示

**Bug 重现步骤(有截图更好)**
![45911630457281_ pic](https://user-images.githubusercontent.com/8981574/131595660-9b24d28d-815b-4ac4-b376-e9def5c87801.jpg)
![45921630457281_ pic](https://user-images.githubusercontent.com/8981574/131595673-2a414053-9950-43ca-90ac-e6375946bee7.jpg)

**Comment by wojiushixiaobai** [comment]
不影响使用
