### ISSUE TITLE
[Bug] 会话管理器日期错误

### ISSUE THREAD

**Issue by linfeng521** [jumpserver/jumpserver#6752]
**JumpServer 版本(v1.5.9以下不再支持)**

**Bug 描述**

**### 会话管理器日期过滤器时间错误导致不能显示会话查询结果**
似乎是windows 10 Edge浏览器的问题？？？
使用Google chrome 没有这个问题
**Bug 重现步骤(有截图更好)**
1. 这是默认的显示会话
![image](https://user-images.githubusercontent.com/33599607/131691949-bb9410c8-e883-4f08-9785-845b24afa55c.png)

2.当我手动选择日期区间
![image](https://user-images.githubusercontent.com/33599607/131693345-54a1ce3c-56a2-498e-8a39-9c459fe60812.png)

**Comment by wojiushixiaobai** [comment]
清理缓存即可
