### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#6755]
**JumpServer 版本(v1.5.9以下不再支持)**
jump server  版本 2.13.2

**浏览器版本**
火狐 91.0.2

**Bug 描述**
web 终端在设置1小时的timeout 时间后，已经连接的会话会断开，根据左侧的资产树中选择其他资产进行连接时，出现了无法点击的情况，整个页面像一个图片一样，点任何地方都没反应。
![图片](https://user-images.githubusercontent.com/63391681/131953641-06dc86e8-66ab-4f1e-8d90-ce1f5befdfd7.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by Allenzhang-92** [comment]
我在重新刷新页面后，就可以重新连接了

**Comment by wojiushixiaobai** [comment]
长时间不使用需要重新打开窗口此设计无问题
