### ISSUE TITLE
[Feature] 关于资产定位给到什么用户

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#6756]
**请描述您的需求或者改进建议.**
现状：
     我们针对不同的资产会创建很多个不同的授权规则，里面包含用户组+用户的组合方式。如果我们需要去统计一个资产分配给了多少用户比较麻烦，涉及资产与授权规则太多
1.在资产列表中选中某个资产后可以查看到已经授权的用户或者用户组。

**Comment by jym503558564** [comment]
已支持～
