### ISSUE TITLE
[Feature] 关于云管中心的对接问题，是否支持新华三等私有云

### ISSUE THREAD

**Issue by Keeplingshi** [jumpserver/jumpserver#6757]
现在jumpserver云管中心已经对接了不少公有云和青云、华为私有云。是否有其他云管平台的对接计划，比如新华三私有云，以及其他openstack为结构的私有云？产品本身是否有私有云的对接时间列表？

**Comment by jym503558564** [comment]
现在目前可支持如下：
![image](https://user-images.githubusercontent.com/40739051/152741426-c5b914d4-536b-40dc-9652-f6f9f5dc63a9.png)
