### ISSUE TITLE
[Feature] 七层和四层动态白名单

### ISSUE THREAD

**Issue by pc10201** [jumpserver/jumpserver#6758]
**请描述您的需求或者改进建议.**

现在是有IP白名单的功能，但是是写在配置文件中的，希望有接口来动态调整白名单，不需要重启服务

其中web七层的白名单，能定义屏蔽的信息页面或者跳转到其他页面

ssh的白名单，也能够自定义被屏蔽的友好的提示信息，在shell终端上展示

**Comment by wojiushixiaobai** [comment]
你应该在最前端的 waf 定义，而不是使用 jumpserver 的 alc

**Comment by pc10201** [comment]
> 你应该在最前端的 waf 定义，而不是使用 jumpserver 的 alc

七层可以WAF控制，四层不太灵活~~

**Comment by BaiJiangJie** [comment]
暂时不考虑集成到产品中。
