### ISSUE TITLE
[Question] 官方演示账号可以提供sso的权限吗

### ISSUE THREAD

**Issue by patience00** [jumpserver/jumpserver#6759]
**请描述您的问题.**
我按照文档的请求了https://demo.jumpserver.org/api/v1/authentication/auth/ ,然后根据返回的token请求https://demo.jumpserver.org/api/v1/authentication/sso/login-url/
返回的是
{
    "detail": "您没有执行该操作的权限。",
    "code": "permission_denied"
}
可以开启一下sso,让演示账号可以测试一下sso吗

**Comment by wojiushixiaobai** [comment]
自行部署下环境，给权限也没用，默认sso都是关闭的。这里的无权限是组织id不正确

**Comment by patience00** [comment]
我部署了2.5.3，按照文档修改了/opt/jumpserver/config/config.txt
![image](https://user-images.githubusercontent.com/35128024/132238719-1a812987-bc15-42b4-937a-165793c275cf.png)
/api/v1/authentication/sso/login-url/接口返回的是
{
    "detail": "SSO 认证关闭了",
    "code": "sso_auth_closed"
}
请问是什么问题呢

**Comment by patience00** [comment]
> 自行部署下环境，给权限也没用，默认sso都是关闭的。这里的无权限是组织id不正确

@wojiushixiaobai 
我重新部署了最新的2.13.2,配置了sso,返回的还是无权限, 你说的组织id不正确要怎么配置呢
{
"detail": "您没有执行该操作的权限。",
"code": "permission_denied"
}

**Comment by patience00** [comment]
@wojiushixiaobai   hi,有空帮忙看看吗

**Comment by patience00** [comment]
了解了,是文档理解错了,关联问题 #6774
