### ISSUE TITLE
Jumpser0.3.2版本ldap登录成功，但没有同步对应姓名、邮箱到数据库

### ISSUE THREAD

**Issue by Lancger** [jumpserver/jumpserver#676]
jumpserver----settings.py文件

import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

AUTH_USER_MODEL = 'juser.User'

*# LDAP AUTH
AUTH_LDAP_SERVER_URI = 'ldap://xxxxxx:3268'
AUTH_LDAP_BIND_DN = 'CN=xxxx,CN=Managed Service Accounts,DC=xxx,DC=com'
AUTH_LDAP_BIND_PASSWORD = '*******'
OU = unicode('OU=xxxx,DC=xxxx,DC=com', 'utf8')

AUTH_LDAP_USER_SEARCH = LDAPSearch(OU, ldap.SCOPE_SUBTREE, "(&(objectClass=person)(sAMAccountName=%(user)s))")

AUTH_LDAP_USER_ATTR_MAP = {
    #"last_name": "sn",
    "name": "sn",
    "email": "mail",
    "first_name": "telephoneNumber",
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

![1](https://user-images.githubusercontent.com/16274422/30048358-5d1429ec-9248-11e7-8d90-8a7086fe19a8.png)

如果使用的django默认的auth_user，可以使用下面方法支持ldap登录，但jumpserver里使用的自定义的扩展User表结构。就会出现用户名和邮箱信息不同步的问题
http://www.cnblogs.com/dreamer-fish/p/5474289.html

**Comment by ibuler** [comment]
这个问题和0.4.0版本遇到的一致

**Comment by ibuler** [comment]
fixed

**Comment by wongchao** [comment]
请教如何fix，有哪些特殊配置呢？
