### ISSUE TITLE
[Bug] 更新到2.13.2后启动失败

### ISSUE THREAD

**Issue by sshnuke3** [jumpserver/jumpserver#6762]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.13.2

**浏览器版本**
n/a

**Bug 描述**
启动失败

**Bug 重现步骤(有截图更好)**
1.  [root@iZuf6dj5ddkv7mdb9989qiZ jumpserver-installer-v2.12.0]# ./jmsctl.sh check_update
最新版本是: v2.13.2
当前版本是: v2.12.1
是否将版本更新至 v2.13.2 ? (y/n)  (默认为 n): y
2. 7. 升级成功, 可以重新启动程序了
cd /opt/jumpserver-installer-v2.12.0
./jmsctl.sh start
3. [root@iZuf6dj5ddkv7mdb9989qiZ jumpserver-installer-v2.12.0]# ./jmsctl.sh start
Pulling nginx (jumpserver/nginx:v2.13.2)...
ERROR: manifest for jumpserver/nginx:v2.13.2 not found: manifest unknown: manifest unknown

**Comment by QinQiang666** [comment]
是按照升级文档来操作的吗，要执行 ./jmsctl.sh upgrade

**Comment by sshnuke3** [comment]
> 是按照升级文档来操作的吗，要执行 ./jmsctl.sh upgrade

升级成功的
是2.13.2启动不行
确切的说 是里面的nginx容器启动不行

测试了下别的容器镜像都好的 就nginx的加载不了
=======================================================
 加载 Docker 镜像                                                                                           
[jumpserver/redis:6-alpine]

[jumpserver/mysql:5]

[jumpserver/nginx:v2.13.2]
Error response from daemon: manifest for jumpserver/nginx:v2.13.2 not found: manifest unknown: manifest unknown

[jumpserver/core:v2.13.2]

[jumpserver/koko:v2.13.2]

[jumpserver/lion:v2.13.2]

**Comment by sshnuke3** [comment]
直接重装2.13.2后解决了。。。。
