### ISSUE TITLE
windows 下载成功后，数据丢失

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#6763]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.13.2

**浏览器版本**
谷歌
版本 92.0.4515.159

**Bug 描述**
windows 在下载一个1.22G文件的时候，提示下载成功，下载后文件大小变成了1G

**Bug 重现步骤(有截图更好)**
1.下载前，windows机器上的数据
![image](https://user-images.githubusercontent.com/29726716/132169158-ed0b8e42-cec4-4c07-84d2-b0187b06e82c.png)

2. 下载后本地文件
![image](https://user-images.githubusercontent.com/29726716/132169241-4496e6e2-c701-42e2-a324-844709d16291.png)

3. 浏览器下载记录
![image](https://user-images.githubusercontent.com/29726716/132169294-4da12570-9784-4b9e-b329-178c41d86717.png)

4.nginx 文件下载大小限制为 4096M
![image](https://user-images.githubusercontent.com/29726716/132169807-4c9fd1f6-ce08-4f02-8f69-8d5df2d8c7aa.png)

**Comment by QinQiang666** [comment]
我刚刚用命令行 sftp 测试下载了一下，下载的就是正常的，页面下载就只能下载到1G
![image](https://user-images.githubusercontent.com/29726716/132172528-33c63565-982d-42c3-ab67-6f94fc26d035.png)

**Comment by LeeEirc** [comment]
@QinQiang666 从 windows 下载文件，最大只能到1G吗？是否有别的负载限制？

**Comment by LeeEirc** [comment]
@QinQiang666 猜测可能是 nginx 超时了，造成的问题。你试试修改下nginx的超时设置。

**Comment by QinQiang666** [comment]
> @QinQiang666 修改nginx的超时设置，该问题还存在吗？

是修改反向代理nginx的超时时间吗？现在设置的是 keepalive_timeout  65；目前我是通过sftp方式下载，就不会出现数据丢失的情况

**Comment by LeeEirc** [comment]
无法复现，你使用新版本看看？
