### ISSUE TITLE
批量测试资产可连接性功能

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#6764]
**请描述您的需求或者改进建议.**
jumpserver 在更新后，资产状态全部变成“未知了”，只能一台台进行可连接测试，才能显示可连接，希望添加批量可连接测试按钮
![image](https://user-images.githubusercontent.com/29726716/132186500-e3770c1c-0f42-4aac-948b-f6b8e0bfaf8a.png)

**Comment by linl12138** [comment]
可以使用作业中心-批量命令，批量执行一下命令，成功执行完成后，可连接性就会显示正常。

**Comment by wojiushixiaobai** [comment]
左侧节点右键有对应功能
