### ISSUE TITLE
[Question] 在manjaro下webui的字体显示异常

### ISSUE THREAD

**Issue by yelvlab** [jumpserver/jumpserver#6769]
**请描述您的问题.**
在manjaro系统下，登录jumpserver，在webui页面，命令行的字体显示异常
![image](https://user-images.githubusercontent.com/19227974/132279003-3725d7c3-c4f9-4922-b794-79013743f2e0.png)

**version** ： 2.7.1

**Comment by linl12138** [comment]
是部署在manjaro还是远程连接manjaro

**Comment by yelvlab** [comment]
> 是部署在manjaro还是远程连接manjaro

不是，我本地环境manjaro，部署在ubuntu，之前使用都没问题，之前都是用的windows电脑，然后我最近换了个manjaro的电脑，就发现这里面字体不对，也翻到了前面别人的issue，他是使用的ubuntu系统，改了字体，我改过好多字体依旧没有解决

**Comment by yelvlab** [comment]
安装moncao字体，在系统里面设置即可
