### ISSUE TITLE
用户管理查看用户授权的级别

### ISSUE THREAD

**Issue by xiao12138-wtc** [jumpserver/jumpserver#6770]
在用户管理-用户列表-授权的资产下面这个能取消自动隐藏吗，需要一个一个的点有些麻烦

![@0Q`%UKHPOBOAK4) N`)F8B](https://user-images.githubusercontent.com/57217982/132290722-5d9400ea-c4b6-43c6-b977-746717c494fb.png)

**Comment by wojiushixiaobai** [comment]
减小 api 压力
