### ISSUE TITLE
批量命令在windows上执行不安装openssh

### ISSUE THREAD

**Issue by linl12138** [jumpserver/jumpserver#6771]
当前远程命令在windows资产执行（或者批量改密），需要在windows上安装openssh，但考虑到是ansible实现的，为什么不使用windows的winrm连接，这样就不用额外引入，而且ansible官方推荐的也是这么做。

**Comment by ibuler** [comment]
1. winrm 不支持网关，ssh 类型的网关就不能用了
2. winrm 需要升级 powershell，也需要打一些补丁，然后重启，这个对于生产中的机器可能更难实施

综上所以选择了 openssh 形式

**Comment by linl12138** [comment]
多谢回复，了解了
