### ISSUE TITLE
[Bug] sso免密登陆 luna的接口返回无权限

### ISSUE THREAD

**Issue by patience00** [jumpserver/jumpserver#6774]
**JumpServer 版本(v1.5.9以下不再支持)**

2.13.2
**浏览器版本**
谷歌92.0.4515.107

**Bug 描述**
安装部署了2.13.2,按照文档https://docs.jumpserver.org/zh/master/admin-guide/authentication/sso/
配置了AUTH_SSO=true
然后使用admin的账号sso没有问题,正常返回了免密登录的url也打开了luna
但是其他用户使用账号密码换取token后,调用免密登录接口返回的结果是
{
    "detail": "您没有执行该操作的权限。",
    "code": "permission_denied"
}

**Bug 重现步骤(有截图更好)**
1.  配置AUTH_SSO=true
2. 新建用户,并且管理对应资产
3. 使用新建用户的账号密码调用接口/api/v1/authentication/auth/
4. 根据接口返回的token请求/api/v1/authentication/sso/login-url/

**Comment by patience00** [comment]
在sso.py中,我看到了代码
`@action(methods=[POST], detail=False, permission_classes=[IsSuperUser], url_path='login-url')`


难道只有超级管理员才可以sso?
我新建了一个系统管理员然后使用token调用/api/v1/authentication/sso/login-url/确实返回了免密登录的地址....这跟文档写的不一致呢
![image](https://user-images.githubusercontent.com/35128024/132637350-392cd6e3-ae7f-4681-a160-bbb877c5955e.png)

**Comment by wojiushixiaobai** [comment]
理解错了，这个是使用管理员的 token 为用户生 成 sso token
-H 使用的 token 需要管理员的
-D 里面的 username 是使用用户的登录用户名
