### ISSUE TITLE
[Bug] swagger 无法使用 https

### ISSUE THREAD

**Issue by Halo1236** [jumpserver/jumpserver#6775]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
jms v2.13.2

**Bug 描述**
开启https时swagger 的Base URL 还是http

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/17096387/132460488-5560981c-5bee-4de2-8384-02ab6f9261e9.png)

**Comment by BaiJiangJie** [comment]
已记录到内部 Issue 站点，完成后会进行回复。
