### ISSUE TITLE
用户通过网页端上传文件报错 Server responded with 0 code.

### ISSUE THREAD

**Issue by lichenglongqi** [jumpserver/jumpserver#678]
通过网页端往主机上面上传文件，报错 Server responded with 0 code. 文件上面会显示一个红色的X，请问是什么问题啊。
![image](https://user-images.githubusercontent.com/27465340/30103827-6797f400-9326-11e7-8364-d787c207edb6.png)

**Comment by hellorocky** [comment]
看看服务端有什么错误日志? 顺便可以调试一下前端页面, 右击-->检查-->console  看看有什么报错
