### ISSUE TITLE
[Question] 如何使用8443端口

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#6780]
**请描述您的问题.**
版本：2.13.2
不知道怎么配置开放8443（HTTPS）访问。
我reconfig似乎也无相关配置项目，修改config.txt也没看到效果。

[root@localhost jumpserver-offline-installer-v2.13.2-amd64-11]# ./jmsctl.sh status
   Name                 Command                  State                    Ports
---------------------------------------------------------------------------------------------
jms_celery   ./entrypoint.sh start task       Up (healthy)   8070/tcp, 8080/tcp
jms_koko     ./entrypoint.sh                  Up (healthy)   0.0.0.0:2222->2222/tcp, 5000/tcp
jms_lion     /usr/bin/supervisord             Up (healthy)   4822/tcp
jms_mysql    docker-entrypoint.sh --cha ...   Up (healthy)   3306/tcp, 33060/tcp
jms_redis    docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp
jms_web      /docker-entrypoint.sh ngin ...   Up (healthy)   0.0.0.0:8080->80/tcp

——————————————————————————————————————————
[root@localhost nginx]# pwd
/opt/jumpserver/config/nginx
[root@localhost nginx]# ls -rlt
总用量 16
drwxr-xr-x. 2 root root   42 4月   7 10:16 cert
-rw-r--r--. 1 root root  221 7月  19 11:35 lb_ssh_server.conf
-rw-r--r--. 1 root root  225 7月  19 11:35 lb_rdp_server.conf
-rw-r--r--. 1 root root 1522 7月  19 15:32 lb_http_server.confbak
-rw-r--r--. 1 root root 1203 7月  19 15:37 lb_http_server.conf
[root@localhost nginx]# cat lb_http_server.conf
# Todo: May be can auto discovery
server {
  listen 443 ssl ;
  # server_name demo.jumpserver.org;      # 取消注释并自行修改成你自己的域名
  server_tokens off;
  ssl_certificate /etc/nginx/cert/server.crt;      # 修改成你自己的证书
  ssl_certificate_key /etc/nginx/cert/server.key;  # 修改成你自己的证书
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE:!DES:!ECDHE-RSA-DES-CBC3-SHA;
  add_header Strict-Transport-Security "max-age=31536000" always;
  ssl_prefer_server_ciphers off;

  client_max_body_size 5000m;

  location / {
    proxy_pass http://127.0.0.1:80;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}
[root@localhost nginx]#

**Comment by ibuler** [comment]
修改 /opt/jumpserver/config/config.txt

```
...
HTTPS_PORT=443
```

样例文件：https://github.com/jumpserver/installer/blob/master/config-example.txt#L43

**Comment by sanpichen** [comment]
不行，网页8080和8443都无响应
————————————————————————————————————————————————————
[root@localhost config]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                                     PORTS                                         NAMES
40f14369f1e2        jumpserver/nginx:alpine2    "sh -c 'crond -b -d …"   1 second ago        Up Less than a second (health: starting)   0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   jms_lb
f2bce18b4418        jumpserver/web:v2.13.2      "/docker-entrypoint.…"   13 seconds ago      Up 11 seconds (healthy)                    80/tcp                                        jms_web
4b18809225c1        jumpserver/core:v2.13.2     "./entrypoint.sh sta…"   13 seconds ago      Up 11 seconds (healthy)                    8070/tcp, 8080/tcp                            jms_celery
5b588f87fa7c        jumpserver/lion:v2.13.2     "/usr/bin/supervisord"   13 seconds ago      Up 12 seconds (healthy)                    4822/tcp                                      jms_lion
7c4c18ab33d9        jumpserver/koko:v2.13.2     "./entrypoint.sh"        13 seconds ago      Up 11 seconds (healthy)                    0.0.0.0:2222->2222/tcp, 5000/tcp              jms_koko
7d2f0ae2bc79        jumpserver/core:v2.13.2     "./entrypoint.sh sta…"   2 minutes ago       Up 2 minutes (healthy)                     8070/tcp, 8080/tcp                            jms_core
abbf74fbe8bf        jumpserver/mysql:5          "docker-entrypoint.s…"   3 hours ago         Up About an hour (healthy)                 3306/tcp, 33060/tcp                           jms_mysql
048acc9b882d        jumpserver/redis:6-alpine   "docker-entrypoint.s…"   3 hours ago         Up About an hour (healthy)                 6379/tcp                                      jms_redis


[root@localhost config]# cat config.txtnew
# 以下设置如果为空系统会自动生成随机字符串填入
## 迁移请修改 SECRET_KEY 和 BOOTSTRAP_TOKEN 为原来的设置
## 完整参数文档 https://docs.jumpserver.org/zh/master/admin-guide/env/

## 安装配置, 可以使用华为云加速下载, arm64 用户需要注释掉 DOCKER_IMAGE_PREFIX
# DOCKER_IMAGE_PREFIX=swr.cn-south-1.myhuaweicloud.com
VOLUME_DIR=/opt/jumpserver
DOCKER_DIR=/var/lib/docker
SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxx
BOOTSTRAP_TOKEN=xxxxxxxxxxxxxxxxx
LOG_LEVEL=ERROR

##  MySQL 配置, USE_EXTERNAL_MYSQL=1 表示使用外置 MySQL, 请输入正确的 MySQL 信息
USE_EXTERNAL_MYSQL=0
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
DB_NAME=jumpserver

##  Redis 配置, USE_EXTERNAL_REDIS=1 表示使用外置 Redis, 请输入正确的 Redis 信息
USE_EXTERNAL_REDIS=0
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxx

## Compose 项目设置, 如果 192.168.250.0/24 网段与你现有网段冲突, 请修改然后重启 JumpServer
COMPOSE_PROJECT_NAME=jms
COMPOSE_HTTP_TIMEOUT=3600
DOCKER_CLIENT_TIMEOUT=3600
DOCKER_SUBNET=192.168.250.0/24

## IPV6 设置, 容器是否开启 ipv6 nat, USE_IPV6=1 表示开启, 为 0 的情况下 DOCKER_SUBNET_IPV6 定义不生效
USE_IPV6=0
DOCKER_SUBNET_IPV6=2001:db8:10::/64

## Nginx 配置, USE_LB=1 表示开启, 为 0 的情况下, HTTPS_PORT 定义不生效
HTTP_PORT=8080
SSH_PORT=2222
RDP_PORT=3389

USE_LB=1
HTTPS_PORT=8443

## Task 配置, 是否启动 jms_celery 容器, 单节点必须开启
USE_TASK=1

## XPack, USE_XPACK=1 表示开启, 开源版本设置无效
USE_XPACK=0

# Core 配置, Session 定义, SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期, SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=true

# Koko Lion XRDP 组件配置
CORE_HOST=http://core:8080

# 额外的配置
CURRENT_VERSION=v2.13.2
————————————————————————————————————
![图片](https://user-images.githubusercontent.com/38068938/132617710-7ca6c950-f4bd-4f77-ae3c-15f6a97ec906.png)

![图片](https://user-images.githubusercontent.com/38068938/132617693-a162c675-27e2-442d-97b7-f5871e6c3ff2.png)

**Comment by sanpichen** [comment]
修改
————
USE_LB=1
HTTPS_PORT=8443
————
不能访问的原因大致已经清楚，我进入jms_lb 容器，发现配置文件有问题：
# Todo: May be can auto discovery
server {
  listen 443 ssl ;
  # server_name demo.jumpserver.org;      # 取消注释并自行修改成你自己的域名
  server_tokens off;
  ssl_certificate /etc/nginx/cert/server.crt;      # 修改成你自己的证书
  ssl_certificate_key /etc/nginx/cert/server.key;  # 修改成你自己的证书
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE:!DES:!ECDHE-RSA-DES-CBC3-SHA;
  add_header Strict-Transport-Security "max-age=31536000" always;
  ssl_prefer_server_ciphers off;

  client_max_body_size 5000m;

  location / {
    proxy_pass http://127.0.0.1:80;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}
以上应该是2.12版本的配置，我按照./jmsctl.sh upgrade 不知为何没能更新到？

修改后，可以正常服务了。
但是按照默认的/etc/nginx/conf.d/default.conf 配置是不能为HTTP://IP:PORT 提供服务，只能使用https
自己配置一下算了。
但是这种./jmsctl.sh upgrade升级机制建议完善一下。

**Comment by sanpichen** [comment]
修改
————
USE_LB=1
HTTPS_PORT=8443
————
不能访问的原因大致已经清楚，我进入jms_lb 容器，发现配置文件有问题：
# Todo: May be can auto discovery
server {
  listen 443 ssl ;
  # server_name demo.jumpserver.org;      # 取消注释并自行修改成你自己的域名
  server_tokens off;
  ssl_certificate /etc/nginx/cert/server.crt;      # 修改成你自己的证书
  ssl_certificate_key /etc/nginx/cert/server.key;  # 修改成你自己的证书
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE:!DES:!ECDHE-RSA-DES-CBC3-SHA;
  add_header Strict-Transport-Security "max-age=31536000" always;
  ssl_prefer_server_ciphers off;

  client_max_body_size 5000m;

  location / {
    proxy_pass http://127.0.0.1:80;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}
以上应该是2.12版本的配置，我按照./jmsctl.sh upgrade 不知为何没能更新到？

修改后，可以正常服务了。
但是按照默认的/etc/nginx/conf.d/default.conf 配置是不能为HTTP://IP:PORT 提供服务，只能使用https
自己配置一下算了。
但是这种./jmsctl.sh upgrade升级机制建议完善一下。
