### ISSUE TITLE
jumpserver 启动失败

### ISSUE THREAD

**Issue by alvist0101** [jumpserver/jumpserver#679]
运行./service.sh start 报Starting jumpsever service:manage.py not running 这个错误，然后手动执行
python manage.py runserver 0.0.0.0:8123 能运行起来，访问没有问题，但是ssh 终端只要关闭，服务就停了，有人知道怎么解决吗？

**Comment by hellorocky** [comment]
最简单的办法就是把你手工执行的命令放到后台执行:

```
#nohup python manage.py runserver 0.0.0.0:8123 &
```

**Comment by alvist0101** [comment]
@hellorocky  我一开始也这样想的，就是不知道原因是什么,还有个问题请教您一下，我系统用户授权之后，连接主机只是弹出来一个框，什么都不提示

**Comment by hellorocky** [comment]
提供的信息最好详细些, 有截图更好, 不然不好理解你的问题

**Comment by alvist0101** [comment]
@hellorocky      3.0的jumpserver，安装配置完成后，我切到了一个普通的用户登录jumpserver，在里边点系统用户的那个图标，弹出一个窗口，什么也不显示，后台日志也没有报错，推送用户是能成功的，我手动是可以登录的


错误截图
![ec21a9db-3d6d-4ea4-afdc-3d8ce1a0eef7](https://user-images.githubusercontent.com/31679747/30150803-68a3fab0-93df-11e7-81d3-bd6a6cf80ede.png)

**Comment by hellorocky** [comment]
网页版terminal我没有用过, 不知道怎么解决

**Comment by alvist0101** [comment]
@hellorocky如果不用这个，其他方法也是可以记录到jumpserver么，网上有这方面的文档说明么。这个问题我实在是解决不了。

**Comment by hellorocky** [comment]
根据这个安装, https://github.com/jumpserver/jumpserver/wiki/v0.3.2-%E5%9F%BA%E4%BA%8E-RedHat-%E7%9A%84%E7%B3%BB%E7%BB%9F

另外建议把wiki 翻翻看看, 很多都需要自己来看的

**Comment by hellorocky** [comment]
https://github.com/jumpserver/jumpserver/wiki/v0.3.2-%E5%BA%94%E7%94%A8%E5%9B%BE%E8%A7%A3
