### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by 532780857** [jumpserver/jumpserver#6790]
**请描述您的问题.**
[jumpserver/core:v2.13.2]
v2.13.2: Pulling from jumpserver/core
6ec7b7d162b2: Already exists 
80ff6536d04b: Extracting [==================================================>]   2.75MB/2.75MB
2d04da85e485: Download complete 
998aa32a5c8a: Download complete 
7733ef26f344: Download complete 
b8f2de1a0c00: Download complete 
bce204fa577d: Download complete 
2886eb4524b3: Download complete 
119a097d4cb2: Download complete 
05910b160293: Download complete 
2a3a5a6216d8: Download complete 
cb8ec5e3f08f: Download complete 
0ef3e1bf4247: Download complete 
failed to register layer: lstat /opt/docker/overlay2/8831b179ddfe78eefa1a4cf276cd357aef79fc86d294d1510725df77c3a25000: no such file or directory

docker镜像pull失败是什么问题？

**Comment by wojiushixiaobai** [comment]
存储满了？还是磁盘有问题，检查下
