### ISSUE TITLE
测试资产可连接性失败

### ISSUE THREAD

**Issue by hongcheng88** [jumpserver/jumpserver#6802]
[简述你的问题]

使用版本

CURRENT_VERSION=v2.13.2

问题复现步骤

按照文档提供手动安装jumpserver，添加完 windows资产后，测试可连接性报错，确认jumpserver机器可以ssh连接，也可以通过其他机器远程登录此资产。

终端输出如下：

TASK [ping] ********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [windows10]: FAILED! => {"changed": false, "msg": "internal error: failed to run exec_wrapper action module_powershell_wrapper: Exception calling \"CompileAssemblyFromDom\" with \"2\" argument(s): \"Could not find a part of the path 'C:\\cygwin64\\home\\Administrator\\%TEMP%\\isd4nvmq.tmp'.\""}
PLAY RECAP *********************************************************************
windows10                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Task assets.tasks.asset_connectivity.test_assets_connectivity_manual[49f9abc7-f7b0-40d4-8986-fe448fa0cb82] succeeded in 1.1986022721976042s: (False, {'windows10': {'ping': {...}}})

具体表现[截图可能会更好些,最好能截全]
报错展示
![image](https://user-images.githubusercontent.com/84756119/132822198-362237b2-9f2d-41b6-b6e2-8a4595ad6240.png)

资产信息
![image](https://user-images.githubusercontent.com/84756119/132822493-e658078d-44fb-4b7a-afdf-6e01ef7e7b7c.png)

**Comment by wojiushixiaobai** [comment]
看起来是模块报了错，根据文档检查下ansible的要求

**Comment by hongcheng88** [comment]
ansible这块采用的默认的配置，另外rdp和ssh的配置确认是ok的。用机器的smb链接是可以连上。

**Comment by HernandoR** [comment]
Same Bug in linux host
