### ISSUE TITLE
[Bug] 采用系统账户密码托管之后连接mac资产仍然需要输入账号密码

### ISSUE THREAD

**Issue by hongcheng88** [jumpserver/jumpserver#6805]
**JumpServer 版本(v1.5.9以下不再支持)**
2.13.2

**浏览器版本**
safari 版本14.1.1 (16611.2.7.1.4)

**Bug 描述**
按照官方文档安装配置好jumpserver，配置好mac资产之后登陆，系统用户已经设置了密码托管，授权资产给到用户用户web登陆，用户仍然每次都需要输入账号对应的密码

**Bug 重现步骤(有截图更好)**
1.  直接连接mac资产跳到登陆密码输入界面
![image](https://user-images.githubusercontent.com/84756119/132837030-350e2c2f-5816-4a03-b65d-e329f60994a2.png)
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/84756119/132837217-0a14f9ad-9061-435c-a3d4-76cb92c225b5.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/84756119/132836880-b77027d5-96ca-42ab-8804-5e25b38fe3d5.png">

**Comment by ibuler** [comment]
vnc 只是 vnc 的密码，系统密码还是要输入的，macos，windows 都如此

**Comment by hongcheng88** [comment]
多谢，后来发现了这个问题。把锁屏密码去掉就好了。
