### ISSUE TITLE
使用过程中发现字宽被挤在一起了

### ISSUE THREAD

**Issue by huyifanstar** [jumpserver/jumpserver#6808]
环境说明：
jumpserver 宿主操作系统：Ubuntu 18.05 
jumpserver 版本：v2.13.2
协议类型：rdp
浏览器：google chrom
jumpserver 有针对页面做自适应缩放嘛？

![image](https://user-images.githubusercontent.com/15685376/132842551-eaa13aec-625c-4bcb-ae1d-fcd47cea6049.png)
图一为jumpserver，但无论字宽还是字号及整体看起来都小一些(缩在一起看很不舒服)
![image](https://user-images.githubusercontent.com/15685376/132842525-ed097289-5cc3-40a0-acb3-fe232602ce86.png)
图二为另外一个品牌的堡垒机
jumpserver 有什么地方可以调整字体之类的吗

**Comment by LeeEirc** [comment]
使用的什么方式连接的会话？

**Comment by huyifanstar** [comment]
rdp协议啊

**Comment by LeeEirc** [comment]
rdp的画面有缩放。另一个品牌的堡垒机是什么？

**Comment by huyifanstar** [comment]
> rdp的画面有缩放。另一个品牌的堡垒机是什么？

云匣子

**Comment by huyifanstar** [comment]
缩放是协议默认的还是jumpserver调整了？
我看云匣子是没进行缩放的

**Comment by LeeEirc** [comment]
web端 rdp 连接，会根据配置计算出一个分辨率大小。jumpserver会自动根据你浏览器的窗口大小自动缩放。不是协议默认的。
