### ISSUE TITLE
节点树排序, 升级后显示问题[Bug] 

### ISSUE THREAD

**Issue by Twoling** [jumpserver/jumpserver#6809]
**JumpServer 版本(v1.5.9以下不再支持)**
2.13.2

**浏览器版本**
SSH终端连接时问题

**Bug 描述**
从1.4.8-2升级后的问题，升级过程：使用installer安装2.13.2，然后restore_db导入旧版数据
问题：
1. 升级后节点树显示有问题，大部资产被归类到父节点（不清楚会不是每个资产分配了多个节点的原因，显示可以查看截图1和2）
2. 用户在组内，我给组添加了其他所有节点后，子节点显示是乱序的，可以查看截图3

**Bug 重现步骤(有截图更好)**
1.  ![image](https://user-images.githubusercontent.com/29671889/132843729-a84335ae-a1c2-420d-983e-089b99e29fdb.png)
2.  ![image](https://user-images.githubusercontent.com/29671889/132844644-e41891dd-9d52-436a-9e51-a33b5a862450.png)

3. ![image](https://user-images.githubusercontent.com/29671889/132844563-9c83dd57-f0e8-47d2-9392-001cf16da94d.png)

**Comment by wojiushixiaobai** [comment]
系统设置，终端设置

**Comment by Twoling** [comment]
> 系统设置，终端设置

![jms_term](https://user-images.githubusercontent.com/29671889/133204966-77058963-974c-4ba6-beec-91a632710987.png)

**Comment by Twoling** [comment]
排序不应该按照组序号来嘛，按1、2、3、4、5这种方式排，我看之前的版本就是这么干的呀，这种逻辑是存在什么问题吗？

**Comment by Twoling** [comment]
等待新版吧~~~

**Comment by liurenbao** [comment]
我也是出现一样的现象，作者大大回复下
