### ISSUE TITLE
版本兼容python 3.5的MySQLdb问题

### ISSUE THREAD

**Issue by alicezx** [jumpserver/jumpserver#682]
装了个最新版本，根据版本需求看到需要python 3.5,安装的时候 import MySQLdb报告模块找不到，只支持python2，需要安装pymysql并修改/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py兼容才能使用

追加以下内容
import pymysql
pymysql.install_as_MySQLdb()

**Comment by hellorocky** [comment]
python3+ 可以安装mysqlclient:

```
pip3 install mysqlclient
```
