### ISSUE TITLE
0.4.0连接跳转很慢

### ISSUE THREAD

**Issue by ouyangxudu** [jumpserver/jumpserver#683]
新安装的v0.4.0在不同的导航栏里点击后跳转很慢，
chrome里load 22.38s
哪里需要优化的吗？

**Comment by hellorocky** [comment]
这样的描述谁能看懂?

**Comment by ouyangxudu** [comment]
是这样的，按照文档https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F 要求安装好后，能够登录。从登录开始页面反映就很慢，点击不同的导航栏，如用户管理的用户，再点用户组，页面load得很慢，大概十几二十秒才能load完每一个页面。查看过机器的负载很低的。不知其他用户是有也有类似问题？谢谢

**Comment by ouyangxudu** [comment]
同样配置的机器安装0.3.2 访问的速度就飞快~不知0.4.0为何速度那么慢

**Comment by ibuler** [comment]
建议可以chrome里面查看哪里慢了？资源还是api ?

**Comment by happygnip** [comment]
今天安装了jumpserver v0.4 点击页面异常慢，发现是请求这个url https://fonts.css.network/css?family=Roboto:400,300,500,700 ,该怎么解决

**Comment by ibuler** [comment]
翻墙问题，已经解决
