### ISSUE TITLE
[Bug] 每个版本的快速安装脚本都默认安装的是latest的版本

### ISSUE THREAD

**Issue by patience00** [jumpserver/jumpserver#6839]
**JumpServer 版本(v1.5.9以下不再支持)**
release中任意版本的安装脚本

**浏览器版本**

**Bug 描述**
如题
脚本中get_installer()每次都是取的最新的版本,能否优化一下?

**Bug 重现步骤(有截图更好)**
`function get_installer() {
  echo "download install script to /opt/jumpserver-installe (开始下载安装脚本到 /opt/jumpserver-installe)"
  Version=$(curl -s 'https://api.github.com/repos/jumpserver/installer/releases/latest' | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
  if [ ! "$Version" ]; then
    echo -e "[\033[31m ERROR \033[0m] Network Failed (请检查网络是否正常或尝试重新执行脚本)"
  fi
  cd /opt
  if [ ! -d "/opt/jumpserver-installer-$Version" ]; then
    wget -qO jumpserver-installer-$Version.tar.gz https://github.com/jumpserver/installer/releases/download/$Version/jumpserver-installer-$Version.tar.gz || {
      rm -rf /opt/jumpserver-installer-$Version.tar.gz
      echo -e "[\033[31m ERROR \033[0m] Failed to download jumpserver-installer (下载 jumpserver-installer 失败, 请检查网络是否正常或尝试重新执行脚本)"
      exit 1
    }
    tar -xf /opt/jumpserver-installer-$Version.tar.gz -C /opt || {
      rm -rf /opt/jumpserver-installer-$Version
      echo -e "[\033[31m ERROR \033[0m] Failed to unzip jumpserver-installe (解压 jumpserver-installer 失败, 请检查网络是否正常或尝试重新执行脚本)"
      exit 1
    }
    rm -rf /opt/jumpserver-installer-$Version.tar.gz
  fi
}`

**Comment by wojiushixiaobai** [comment]
我们希望用户使用最新版本

**Comment by patience00** [comment]
> 我们希望用户使用最新版本

如果想安装指定版本,如何快速安装呢

**Comment by wojiushixiaobai** [comment]
手动安装，修改 static.env 里面的版本号即可
