### ISSUE TITLE
您好 我有一个执行命令的问题 希望能够解答 谢谢

### ISSUE THREAD

**Issue by AnndaGH** [jumpserver/jumpserver#684]
我也是刚接触 jumpserver，这边已经推送了一个用户，并且通过ssh登录，我检查sudo权限也手动执行了ifconfig命令，权限没问题，命令也没有问题，但是通过网页或者ssh跳板对其执行ifconfig，却提示这个命令不存在。
不知道这种情况是我哪里 操作不对么？ jumpserver ver 0.3.2
![tim 20170909162908](https://user-images.githubusercontent.com/19545970/30238597-634eb0ca-957c-11e7-9877-4dcd76397f33.png)
![tim 20170909162929](https://user-images.githubusercontent.com/19545970/30238594-6309ea3a-957c-11e7-9cb4-6c33e4c7856e.png)
![tim 20170909163019](https://user-images.githubusercontent.com/19545970/30238596-634a11d2-957c-11e7-8d87-d45f84db75e6.png)
![tim 20170909163053](https://user-images.githubusercontent.com/19545970/30238595-6331fc14-957c-11e7-9942-2fb9705373ee.png)
麻烦看一下是不是哪里操作不对

**Comment by AnndaGH** [comment]
![tim 20170909162908](https://user-images.githubusercontent.com/19545970/30238597-634eb0ca-957c-11e7-9877-4dcd76397f33.png)
![tim 20170909162929](https://user-images.githubusercontent.com/19545970/30238594-6309ea3a-957c-11e7-9cb4-6c33e4c7856e.png)
![tim 20170909163019](https://user-images.githubusercontent.com/19545970/30238596-634a11d2-957c-11e7-8d87-d45f84db75e6.png)
![tim 20170909163053](https://user-images.githubusercontent.com/19545970/30238595-6331fc14-957c-11e7-9942-2fb9705373ee.png)
麻烦看一下是不是哪里操作不对

**Comment by jiaxiangkong** [comment]
是用  /sbin/ifconfig

**Comment by AnndaGH** [comment]
@jiaxiangkong 我试过了 /sbin/ifconfig 他失败的时候提示 /bin/sh /sbin/ifconfig 文件未找到

**Comment by AnndaGH** [comment]
@jiaxiangkong 麻烦了再问一下，是这样您说的这个我昨天有测试，但是当时没有给 /sbin/ifconfig 在sudo中，直接给的 /sbin/* 这个有影响么？还是可能我没操作对
还有就是 是不是建议所有的命令都已绝对路径执行？
万分感谢！
