### ISSUE TITLE
外部webshell集成

### ISSUE THREAD

**Issue by wood-zhang** [jumpserver/jumpserver#6843]
我这里有一个webshell的访问链接，我想在请求jumpserver的时候将webshell的链接传给jumpserver，由jumpserver发起访问，从而使用jumpserver的统一登录和审计功能

**Comment by wood-zhang** [comment]
> 我这里有一个webshell的访问链接，我想在请求jumpserver的时候将webshell的链接传给jumpserver，由jumpserver发起访问，从而使用jumpserver的统一登录和审计功能

我这个webshell是对k8s的pod访问，从而达到通过jumpserver登陆pod，并有审计工作

**Comment by ibuler** [comment]
连接一个资源，需要在 服务端 实现连接，

用户 -> 服务端 -> 资源

JumpServer 需要支持这种资源才行，支持这种资源后，服务端要实现连接

**Comment by ibuler** [comment]
@wood-zhang 已更新群码
