### ISSUE TITLE
git pull 了最新的dev代码，登录的时候提示AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance

### ISSUE THREAD

**Issue by jy-cw** [jumpserver/jumpserver#685]
Request Method:	POST
Request URL:	http://192.168.1.123:8080/users/login?next=/
Django Version:	1.11.1
Exception Type:	ImproperlyConfigured
Exception Value:	
AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.
Exception Location:	/usr/local/python36/lib/python3.6/site-packages/django_auth_ldap/backend.py in _search_for_user_dn, line 509
Python Executable:	/usr/bin/python
Python Version:	3.6.1
Python Path:	
['/opt/jumpserver/apps',
 '/usr/local/python36/lib/python36.zip',
 '/usr/local/python36/lib/python3.6',
 '/usr/local/python36/lib/python3.6/lib-dynload',
 '/usr/local/python36/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']
Server time:	星期六, 9 九月 2017 16:41:32 +0800

**Comment by ibuler** [comment]
没有遇到这个问题，请更新一下代码，然后重新测试一下是否还存在
