### ISSUE TITLE
密钥保存不成功[Bug] 

### ISSUE THREAD

**Issue by Lingshuirong** [jumpserver/jumpserver#6857]
**JumpServer 版本(v1.5.9以下不再支持)**
版本：v2.13.2

**浏览器版本**

chrome 版本 93.0.4577.63（正式版本
**Bug 描述**
不管是特权用户还是普通用户，使用密钥文件连接的时候，都会出现（Failed to connect to the host via ssh），然后通过进入docker交互界面里边查询相关用户的密钥，发现都是空的，多次保存

**Bug 重现步骤(有截图更好)**
1.  
2. 
![截图录屏_选择区域_20210915110652](https://user-images.githubusercontent.com/35438727/133363922-9e576bea-f6d6-4f3c-91df-80598412d546.png)

3. 
![截图录屏_选择区域_20210915111037](https://user-images.githubusercontent.com/35438727/133364351-eed47a48-f497-4a36-a1b2-cf4abe83f231.png)

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/133578074-2e0c7cb1-e6c2-4e87-911c-673dc62fe9c2.png)

没有复现，是不是你的 secret_key 有问题

**Comment by wojiushixiaobai** [comment]
页面显示为空正常，你可以看详情里面的 ssh 指纹
无法复现

**Comment by Lingshuirong** [comment]
找到原因了，权限问题

吴小白 ***@***.***> 于2021年9月16日周四 下午4:29写道：
