### ISSUE TITLE
web中日志审计的显示在线用户，不自动中断，一直显示连接！

### ISSUE THREAD

**Issue by hanjms** [jumpserver/jumpserver#687]
在线用户一直显示保持连接，现在显示在线是在2017-08-31，我对jumpserver 服务器做过一次重启，重启之前是正常，现在突然遇到这个问题。

**Comment by hanjms** [comment]
![image](https://user-images.githubusercontent.com/31839722/30260234-b15439b6-96f8-11e7-8e91-8acf1ef991e5.png)

**Comment by hanjms** [comment]
![image](https://user-images.githubusercontent.com/31839722/30260241-c06c1266-96f8-11e7-87f0-1c548108578f.png)

**Comment by hanjms** [comment]
![image](https://user-images.githubusercontent.com/31839722/30363102-8077c00c-9891-11e7-8bcd-6d22d0c8ba56.png)

**Comment by hanjms** [comment]
![image](https://user-images.githubusercontent.com/31839722/30363119-9c786a40-9891-11e7-9424-3ddcad3e6e42.png)

**Comment by ibuler** [comment]
same with
