### ISSUE TITLE
大量报错，无法安装启动

### ISSUE THREAD

**Issue by veryrich** [jumpserver/jumpserver#690]
作者您好，我 clone仓库后，安装了 docker-ce 与 compose 1.16 ， 运行docker-compose up 后出现大量报错，error 与warrning ，之后屏幕中就一直显示 http403错误。 下面我复制几条报错出来：
Attaching to redis, jumpserver, luna, coco
luna          | ERROR:root:Load access key failed
luna          | ERROR:root:Register terminal luna failed
luna          | Register terminal failed, may be have been exist, you should look for the terminal access key, set in config, or put it in access key store
coco          | ERROR:root:Register terminal coco failed
coco          | Register terminal failed, may behave been exist, you should look forthe terminal access key, set in config, or put it in access key store
luna          | WARNING:luna.service:App auth failed, Access key error or need admin active it
coco          | WARNING:/opt/coco/coco/service.py:App auth failed, Access key error or need admin active it
jumpserver    | 2017-09-12 12:29:07 [basehttp WARNING] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 27

这里的报错我百度谷歌都看了下，也没有具体的方法，请问可以帮我分析一下问题吗，非常感谢各位

**Comment by veryrich** [comment]
i fixd it , thank you

**Comment by zengsf** [comment]
@veryrich 你是如何修复的呢？我这边也遇到了同样的情况，百思不得其解啊

**Comment by morganwu277** [comment]
2 options to solve this:
1. In the `conf.py`, use `NAME = "localhost"` if you have only 1 cocod server. Or, 
1. Comment out the `NAME = "localhost"` in `conf.py` and make sure your cocod server's hostname settings (i.e, `/etc/hostname`) is resolvable in the DNS.
