### ISSUE TITLE
[Question] 更新2.14.0出现了如图报错

### ISSUE THREAD

**Issue by wushengmin** [jumpserver/jumpserver#6906]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/81400245/133656587-c3bfe29e-1aef-436f-b7f8-54aaeacd9da8.png)

**Comment by benma9** [comment]
问题是 数据库编码问题。我也碰到了。官方有解释。

**Comment by wushengmin** [comment]
> 问题是 数据库编码问题。我也碰到了。官方有解释。

我使用了官方的方式，发现有数据无法导入，并且我前几个版本更新都是没问题的，数据库也是按照官方的要求进行的创建，不知道为什么有数据会出现编码问题。

**Comment by ibuler** [comment]
给个文档 

https://github.com/jumpserver/jumpserver/issues/6918

**Comment by wushengmin** [comment]
> 给个文档 
> 
> https://github.com/jumpserver/jumpserver/issues/6918

更新成功，感谢支持

**Comment by ibuler** [comment]
abcdf
