### ISSUE TITLE
admin用户重置密码v0.3.2

### ISSUE THREAD

**Issue by xubinxinant** [jumpserver/jumpserver#691]
web登录admin用户密码忘记，请问如何重置

**Comment by xubinxinant** [comment]
已经解决
[root@ssjumpserver ~]# cd /opt/jumpserver/
[root@ssjumpserver jumpserver]# ls
a.py  connect.py  connect.pyc  docs  install  jasset  jlog  jperm  jumpserver  jumpserver.conf  juser  keys  LICENSE  logs  manage.py  README.md  run_websocket.py  service.sh  static  templates
[root@ssjumpserver jumpserver]# cd install/
[root@ssjumpserver install]# ls
developer_doc.txt  initial_data.yaml  install.py  install.pyc  next.py  requirements.txt  zzjumpserver.sh
[root@ssjumpserver install]# 
[root@ssjumpserver install]# 
[root@ssjumpserver install]# 
[root@ssjumpserver install]# python next.py 
开始安装Jumpserver, 要求环境为 CentOS 6.5 x86_64
开始更新jumpserver
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

请输入管理员用户名 [admin]: 
请输入管理员密码: [5Lov@wife]: 
请再次输入管理员密码: [5Lov@wife]: 
jumpserver  is running...
                                                           [  确定  ]
安装成功，请访问web, 祝你使用愉快。
请访问 https://github.com/ibuler/jumpserver 查看文档

**Comment by ibuler** [comment]
重新安装是一种方式，也可以使用 django提供的方式

`$ python manage.py changepassword admin`
