### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by DiligentNezha** [jumpserver/jumpserver#6916]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.13.1 GPLv2.

**浏览器版本**
Microsoft Edge
版本 93.0.961.47 (官方内部版本) (x86_64)

**Bug 描述**
使用网域功能，更新硬件信息失败，密码包含字符 # 

**Bug 重现步骤(有截图更好)**
1.  资产详情页
2. 点击更新硬件信息对应的刷新按钮
![image](https://user-images.githubusercontent.com/20829924/133871189-b941d67e-8294-45f7-aaf7-9f56b942b333.png)
3.![image](https://user-images.githubusercontent.com/20829924/133871062-0da42f75-4696-47d2-8d24-f7425e4fc9b3.png)

**Comment by ibuler** [comment]
估计密码里有 '%4'，导致的 ansible 出问题了
