### ISSUE TITLE
[Bug] 2.14版本批量命令回车没反应

### ISSUE THREAD

**Issue by 775838893** [jumpserver/jumpserver#6919]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
360极速浏览器13.0

**Bug 描述**
批量执行命令输入，然后回车后没有反应。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/7666283/133886638-5e4d40c4-23a9-4bb4-a14c-bbd5fcc5cbda.png)

2. 
3.

**Comment by 775838893** [comment]
如图，输入ls回车，终端无反应

**Comment by ibuler** [comment]
vue 重构了 koko 的前端，整没了 [尴尬]， 下个小版本修复

**Comment by 775838893** [comment]
哈哈，好哒。

**Comment by ibuler** [comment]
https://github.com/jumpserver/koko/pull/702 已添加

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v2.14.1 已发布
