### ISSUE TITLE
[Feature] 希望可以针对SSH协议支持二级用户托管，主要针对网络设备

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#6921]
**请描述您的需求或者改进建议.**
因为默认的网络设备登录时无法获取最大权限，需要在登录后再登入二级用户获取权限，不希望每个用户都知晓二级用户密码，请支持二级用户密码托管

**Comment by ibuler** [comment]
调研中，linux 设备可能好测试，网络设备，条件不是很充足

**Comment by BaiJiangJie** [comment]
新版本中可以使用 切换自 用户进行配置使用，支持二级用户密码托管。
