### ISSUE TITLE
[Bug] 会话分享

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#6930]
**JumpServer 版本(v1.5.9以下不再支持)**
2.14.0
**浏览器版本**

**Bug 描述**

通过会话分享生成链接，其他人点击链接需要输入账户密码是正常的吗
**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by LeeEirc** [comment]
分享的人必须是jumpserver平台上的用户（即他需要登录）。

**Comment by ibuler** [comment]
为了安全，不允许你们实用会话共享

**Comment by wojiushixiaobai** [comment]
是否可以做成选项，只允许查看时可以不需要登录。
允许操作时必须要登录。

**Comment by ryswork1993** [comment]
对，分享时可以选择查看权限或者操作权限
