### ISSUE TITLE
请问如何允许sudo -i

### ISSUE THREAD

**Issue by veryrich** [jumpserver/jumpserver#694]
请问如何允许sudo -i 切换至root ？

**Comment by hellorocky** [comment]
在`/etc/sudoers`文件中添加如下:

```
用户名 ALL=(ALL) NOPASSWD: ALL
```

**Comment by veryrich** [comment]
我也是这么处理的。。我以为在jumpserver里面可以设置。。。。还是不够智能啊

**Comment by hellorocky** [comment]
![b5553066-1a32-4456-b5f7-dadf36729821](https://user-images.githubusercontent.com/7486508/30356705-11a2d852-986d-11e7-8504-c96163bfc0e1.png)

**Comment by jiaxiangkong** [comment]
/bin/bash

**Comment by veryrich** [comment]
添加sudoer文件只能手动处理
