### ISSUE TITLE
[Bug] 无法发送测试邮件

### ISSUE THREAD

**Issue by shaonx** [jumpserver/jumpserver#6949]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome
版本 94.0.4606.61（正式版本） （64 位）

**Bug 描述**
已经保存了邮件服务器信息，但是无法发送测试邮件。提示400错误

**Bug 重现步骤(有截图更好)**
1.  提示没有EMAIL_HOST参数，但是其实已经有了
![image](https://user-images.githubusercontent.com/52696672/134661557-975a165f-737b-48e6-b344-8e2ee784bc73.png)
![image](https://user-images.githubusercontent.com/52696672/134661780-ea3ad064-e022-4c3e-9757-1a216fe74ae4.png)

2. 
3.

**Comment by linl12138** [comment]
勾选使用ssl
