### ISSUE TITLE
v0.4.0    资产详情页  选择用户与资产组的bug

### ISSUE THREAD

**Issue by ZQiannnn** [jumpserver/jumpserver#695]
问题分析： 页面  updateAssetGroups和updateAssetSystem 共用了同一个jumpserver.groups_selected变量，导致变量内共同存在group的值与assert的值，造成页面以及js的混乱。

另外，Group和Assert id相同的时候，remove会同时删掉两个option

**Comment by ZQiannnn** [comment]
![wechatimg6124](https://user-images.githubusercontent.com/19886406/30357216-163fae64-9870-11e7-8773-49be29cd50e5.jpeg)

**Comment by ibuler** [comment]
fixed, 期待你的反馈
