### ISSUE TITLE
[Feature] 创建用户的API返回信息改进 

### ISSUE THREAD

**Issue by 775838893** [jumpserver/jumpserver#6958]
**请描述您的需求或者改进建议.**
当用户存在时，返回的信息如下：
{"email":["具有 邮件 的 用户 已存在。"],"username":["具有 用户名 的 用户 已存在。"]}

建议加上用户名或邮件信息

**Comment by jym503558564** [comment]
v2.20.0版本，JumpServer新增支持基于角色的权限访问控制（RBAC）。
