### ISSUE TITLE
[Question] web 终端连接vpc 网络很容易断开

### ISSUE THREAD

**Issue by gglnp** [jumpserver/jumpserver#6959]
**请描述您的问题.**
通过网域 连接vpc网络 会出现 连接不上，和连接一会后断开
![ssh-error](https://user-images.githubusercontent.com/61819511/134837614-d273b650-a8f1-488c-88ad-35d7dee40ff3.png)

查看koko 日志:
![koko-error](https://user-images.githubusercontent.com/61819511/134837798-5f3b7fe6-b183-468a-8eca-b265dee8ef84.png)

这个是我这边的情况还是jumpserver有问题?

**Comment by LeeEirc** [comment]
你的网络需要支持 websocket 的长连接。
