### ISSUE TITLE
[Feature] 关于快捷键呼出侧边栏

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#6972]
首先，很感谢开发团队能看到我的需求建议，并进行了对应的功能开发。
       今天终于成功更新到了v2.14.2版本，看到了快捷键呼出侧边栏的功能更新，但并不是很满意。对比历史版本的使用习惯，我希望的是快捷键呼出剪贴板工具，或者像1.5版本一样不通过辅助工具直接能够复制粘贴，而不是只呼出侧边栏，这样的改动其实没有太大意义。不知道是不是开发有难度，但还是希望能够继续优化。
       另外，说点题外话，从1.5版本到2.10版本版本其他功能在升级但复制黏贴功能在降级，从一开始使用1.5版本时可以像windows远程桌面一样复制粘贴，中间不知道更新到哪个版本就没法用了，只能靠快捷键呼出剪贴板工具实现，到了2.10版本连快捷键呼出剪贴板功能都没有了，这确实影响了便捷性。

**Comment by LeeEirc** [comment]
配置 https，是可以直接复制粘贴，浏览器也需要开启对剪切板的支持。如果使用社区版本，目前默认使用的 http，需要自行配置https。参考[文档](https://docs.jumpserver.org/zh/master/admin-guide/proxy/)

**Comment by vzrs** [comment]
非常感谢！

**Comment by BaiJiangJie** [comment]
v3 版本有优化，建议升级使用。
