### ISSUE TITLE
[Bug] Web终端字号大于13，最后一行显示不完整

### ISSUE THREAD

**Issue by BOBYou** [jumpserver/jumpserver#6974]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.14.2-101 GPLv2.

**浏览器版本**
Chrome 版本 94.0.4606.61

**Bug 描述**
字符终端字体大小，字号大于等于 14，最后一行显示不完整

**Bug 重现步骤(有截图更好)**
1.  打开web终端，设置字符终端字体大于为15
2. 连接Linux终端，回车到最后一行
3. 输入 LLLLlllllllggggggg，观察是否有问题

问题截图：
字号 12
![12](https://user-images.githubusercontent.com/4455220/135215957-639473c1-07b2-4b6a-bc83-7959e908b2d3.jpg)

字号 13
![13](https://user-images.githubusercontent.com/4455220/135215961-24a44600-a756-4735-bfd1-43312823d88c.jpg)

字号 14
![14](https://user-images.githubusercontent.com/4455220/135215964-581c1f45-d549-4d91-a635-a2f3f4a3ecba.jpg)

字号 15
![15](https://user-images.githubusercontent.com/4455220/135215968-e1014be8-ca16-42ff-9f52-112339b44f7a.jpg)

字号 16
![16](https://user-images.githubusercontent.com/4455220/135215969-1939b490-4b76-4ad8-aca5-7411d9f3ee09.jpg)

**Comment by smallodd** [comment]
我这边不管几号字体都显示不全
![image](https://user-images.githubusercontent.com/13759794/136877476-aab38c8f-c630-4817-9962-f703656580a5.png)

**Comment by paddy235** [comment]
确实如此，使用过程很痛苦

**Comment by jym503558564** [comment]
新版本已修复，请更新至新版测试。如有其他问题，可再次提Issues
