### ISSUE TITLE
[Feature] 增加类似子管理员功能

### ISSUE THREAD

**Issue by 580825** [jumpserver/jumpserver#6987]
**请描述您的需求或者改进建议.**
能否增加子管理员功能

比如授权一批机器为 张三 管理，张三可以修改这批机器的信息，也可以给其他人授权这批机器的信息

多谢

**Comment by ibuler** [comment]
企业版本支持 多组织，可以给某个用户建个组织，设置为组织管理员，就可以做你想要的事情了

**Comment by ibuler** [comment]
其实 JumpServer 中的组织，就是 namespace，就是 project，只不过叫法不一样。由于产品是 企业级 产品，所以没有开放用户自己创建组织的权限
