### ISSUE TITLE
[Question] web jumpserver全屏后，在使用vim时，vim的ESC键与退出jumpserver全屏冲突。

### ISSUE THREAD

**Issue by islengxw** [jumpserver/jumpserver#6988]
问题1：如题目。
问题2：请问如何消除水印？如下图所示中‘xwl‘的水印
![2021-10-08_201334](https://user-images.githubusercontent.com/43981882/136555295-8c69d120-6b61-4c8b-960b-50c0a4b295f5.jpg)

**Comment by JaySon-Huang** [comment]
I find that web browser like Safari can use the `ESC` to exit vim edit mode correctly

**Comment by wurenny** [comment]
现在的chrome已经改成需要长按Esc才能退出全屏了，已经不存在这个问题了
