### ISSUE TITLE
excel批量导入用户功能密码设置没有写入数据库[Bug] 

### ISSUE THREAD

**Issue by Garen2020** [jumpserver/jumpserver#6994]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.14.2

**Bug 描述**
excel批量导入用户功能密码设置没有写入数据库批量导入后还要手动设置一遍密码

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/60033632/136654282-7585dd69-0db3-4ea7-b3cf-72c0726e98c9.png)

<img width="649" alt="用户密码" src="https://user-images.githubusercontent.com/60033632/136654218-4600f2ff-1491-40ea-9bef-7ce3786869d7.png">
[user.xlsx](https://github.com/jumpserver/jumpserver/files/7315385/user.xlsx)

**Comment by wojiushixiaobai** [comment]
无法复现。
![image](https://user-images.githubusercontent.com/24326988/145903885-9cc9c864-a2e3-469c-b73b-228746c42034.png)
确认导入时的密码字段不为空。可以双击对应字段在线修改

csv 内容，密码需要指定 `密码策略` 为 `custom`
![image](https://user-images.githubusercontent.com/24326988/145903982-c5c2273c-7239-495a-9adf-ab23e8e2ee4a.png)
