### ISSUE TITLE
配置了域名后web端无法连接

### ISSUE THREAD

**Issue by yaohp** [jumpserver/jumpserver#700]
![image](https://user-images.githubusercontent.com/12130231/30414530-a2571cca-9956-11e7-83ba-a0f075c82f59.png)

使用ip+端口访问就可以zhengchang正常连接

**Comment by ibuler** [comment]
右击浏览器-检查-Network  然后刷新该页面查看，有没有红色报错


![image](https://user-images.githubusercontent.com/17382885/30889347-5f1d13f8-a2eb-11e7-8e7d-719f10f17450.png)
