### ISSUE TITLE
[Bug] 使用搜狗输入法中文输入，在web终端中回车，会出现重复字符

### ISSUE THREAD

**Issue by smallodd** [jumpserver/jumpserver#7000]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.14.2

**浏览器版本**
![image](https://user-images.githubusercontent.com/13759794/136874595-bba30464-68a8-4342-975a-b58001775585.png)

**搜狗输入法版本（Linux版）**
![image](https://user-images.githubusercontent.com/13759794/136875097-38057049-32ed-41a6-9af0-38981b0e2999.png)

**Bug 描述**
使用搜狗输入法中文输入，在web终端中回车，会出现重复字符

**Bug 重现步骤(有截图更好)**
1.  打开web终端
2. 切换到搜狗输入法中文
3. 输入cd，然后回车

**现象**
出现cdcd

**图片**
![录屏_选择区域_20211012091341](https://user-images.githubusercontent.com/13759794/136874888-6bd6e417-a46d-4d1e-b977-69245840ed2b.gif)

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by jym503558564** [comment]
重复问题。 已记录
