### ISSUE TITLE
[Bug] lion容器不停地产生core.xxx文件，导致存储空间耗尽

### ISSUE THREAD

**Issue by dowliu** [jumpserver/jumpserver#7001]
**JumpServer 版本**
从v2.12到v2.14
**Bug 描述**
在lion容器的/opt/lion下，不停地产生core.xxx文件，导致存储空间占用过大，每次都需要手去清理。8月份有在qq群反馈过，从2.12.1开始，至今未得到解决。

[root@ip-172-23-4-153 lion]# pwd
/opt/docker/overlay2/d37e8c8535e8ef0eaea0d157cfb543381db52500bc5025e82f2b698b3c88535a/merged/opt/lion

[root@ip-172-23-4-153 lion]# ls
config_example.yml  core.11726  core.1352   core.14854  core.15906  core.18427  core.21543  core.23648  core.26003  core.27933  core.305    core.4007  core.6736  core.8494
core.10023          core.11731  core.13632  core.14859  core.16114  core.18532  core.21622  core.23663  core.2609   core.28070  core.31124  core.406   core.6756  core.8634
core.10106          core.11770  core.1368   core.14883  core.16528  core.18604  core.21698  core.23821  core.26176  core.28083  core.31319  core.4498  core.6948  core.9146
core.10213          core.11824  core.13785  core.14941  core.16543  core.18827  core.21800  core.23903  core.26239  core.2825   core.31368  core.5016  core.7145  core.9162
core.10432          core.11917  core.1397   core.15072  core.16576  core.18938  core.22238  core.24126  core.26340  core.28391  core.31597  core.5663  core.7456  core.9208
core.10655          core.12013  core.13971  core.15087  core.16655  core.18998  core.22318  core.24333  core.2636   core.28400  core.31719  core.5734  core.7505  core.9262
core.10680          core.12124  core.1405   core.15124  core.16980  core.1909   core.2244   core.24391  core.26530  core.28639  core.31743  core.5741  core.7541  core.9322
core.10821          core.12473  core.1413   core.15258  core.17016  core.19612  core.22487  core.24530  core.26618  core.28693  core.31842  core.5768  core.8015  core.9333
core.10978          core.12576  core.14409  core.15321  core.17174  core.19727  core.22566  core.24666  core.27037  core.2875   core.32036  core.5783  core.8118  core.9500
core.11014          core.12582  core.1441   core.15379  core.17221  core.2008   core.2263   core.24967  core.2740   core.28813  core.32075  core.6095  core.8192  core.9644
core.11210          core.13018  core.14422  core.15471  core.17234  core.20088  core.22643  core.25000  core.27538  core.2944   core.32569  core.6097  core.8231  core.9934
core.11314          core.13193  core.14536  core.15553  core.1777   core.20339  core.2272   core.25332  core.27628  core.29739  core.3495   core.6230  core.8308  data
core.1144           core.1325   core.14639  core.15625  core.17841  core.20875  core.22835  core.25443  core.27793  core.29776  core.3654   core.6256  core.8336  lion
core.11574          core.13256  core.1477   core.15806  core.1795   core.20898  core.22881  core.25506  core.27843  core.30068  core.3737   core.6624  core.8376  ui
core.11705          core.13325  core.14842  core.15821  core.18341  core.20935  core.23231  core.25958  core.27860  core.30166  core.3942   core.6657  core.8402

**Comment by lucyxss** [comment]
@wojiushixiaobai 请问在什么版本中解决了，遇到了同样的问题

**Comment by lucyxss** [comment]
@LeeEirc

**Comment by dowliu** [comment]
请问该问题有眉目了吗？根据测试，我新建的jumpserver没遇到该问题，当前的jumpserver是从老版本升级上来的，该问题始终存在。

**Comment by dowliu** [comment]
最近一直在排查该问题，为什么会出现在升级过的jumpserver中，而新建的却没有。对比了两边的数据库表，老的jumpserver里面原来在1.5.x的时候是用企业版的all in one版本，之后迁移到2.x上来的。表里面有多张xpack_xxx的表，这几张表之前也闹过问题，之前只是清除过数据，但是并没有动过这些表。这次干脆就把表全部drop掉。经过这一周多的观察，发现core.xxx文件再也没有出现过了，不知道是不是这个原因造成的。

之前试用的企业版，用的试用license，体验了一下公有云自动同步资产的功能。在试用license到期之后，xpack的菜单功能也隐藏了看不到，之前建的那些job也没有清理。这就导致了后面在删除部分当时由该job自动创建的资产时会提示失败。这些资产的UUID被相关job的表引用为外键了的，所以无法删除。当时就把外键检查关闭了才得以删除，避免后面还有出现类似问题，就把几张xpack_xxx的表truncate了。没想，core.xxx的问题也与该问题有关。

@lucyxss 可以关注一下该问题哈，希望对你有帮助。

**Comment by wojiushixiaobai** [comment]
allinone 镜像在 run 时加入 ulimit 声明
```bash
docker run --ulimit core = 0
```
compose 运行的加入到 docker-compose.yml 里
```
ulimits:
      core: 0
```

- 可参考 https://github.com/jumpserver/installer/blob/master/compose/docker-compose-app.yml#L8
