### ISSUE TITLE
[Question] 跨大版本升级的方案咨询

### ISSUE THREAD

**Issue by LuckyDogg** [jumpserver/jumpserver#7005]
**请描述您的问题.**
请问 从 1.5.x 直接升级到 2.14.x 建议的升级方案是什么呢？
数据格式是不是大概率也不兼容了

**Comment by wojiushixiaobai** [comment]
按照文档迁移即可。https://docs.jumpserver.org/zh/master/install/migration/

**Comment by wojiushixiaobai** [comment]
暂时没复现，换个浏览器看看。比如 Edge

**Comment by LuckyDogg** [comment]
![image](https://user-images.githubusercontent.com/16526987/137245534-78ecbcf7-b027-4031-88a6-c4979eb04ca5.png)
请我这个是不是写错了，应该改Volume_dir
