### ISSUE TITLE
Linux web terminal 显示有问题

### ISSUE THREAD

**Issue by Allenzhang-92** [jumpserver/jumpserver#7016]
**JumpServer 版本(v1.5.9以下不再支持)**
在选择某一个linux资产连接的时候，偶尔会出现输入的信息强制换行的情况，在重新连接后问题消失

**浏览器版本**

**Bug 描述**
![image](https://user-images.githubusercontent.com/63391681/137423707-2df5e27d-99bf-4a63-9eb5-f574b478637e.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by Allenzhang-92** [comment]
使用的是谷歌浏览器，用火狐没发现过这样的情况

**Comment by jym503558564** [comment]
什么版本
