### ISSUE TITLE
0.3.2版本怎么安装coco

### ISSUE THREAD

**Issue by 727023460** [jumpserver/jumpserver#702]

**Comment by hellorocky** [comment]
coco是0.4版本的, 0.3.2不需要安装,也不能安装

**Comment by 727023460** [comment]
但是公司原来的0.3.2版本用到了coco

**Comment by 727023460** [comment]
connect.py里面有输出的代码，但是不知道在哪里用到了

**Comment by hellorocky** [comment]
0.3.2用的是connect.py脚本, 0.4使用的coco, 功能类似, 只不过coco是独立部署的
