### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Gerry-zhuxudong** [jumpserver/jumpserver#7021]
**JumpServer 版本(v1.5.9以下不再支持)**
版本 2.13.2

**浏览器版本**

**Bug 描述**
当数据库数据量比较大的时候，单库100G
数据库登录的时候会卡30-50秒
我们一般登录数据库的时候都会用到  -A

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/43259140/137456994-309e03b2-5832-4a12-a902-11c48601c387.png)

3.

**Comment by LeeEirc** [comment]
新版本连接web cli 方式连接 MySQL，已经增加选项
