### ISSUE TITLE
[Bug] 无法发送邮件

### ISSUE THREAD

**Issue by marklinglon** [jumpserver/jumpserver#7022]
![image](https://user-images.githubusercontent.com/18097531/138062061-4acd17d3-d63b-4bbf-a34f-bf45fb4b8c5b.png)

**Comment by marklinglon** [comment]
另外我设置的启用ssl，重新打开后怎么启用的复选框没选中

**Comment by wojiushixiaobai** [comment]
发件人确认下。

**Comment by marklinglon** [comment]
jumpserver/jms_all:v2.14.1
升级到
jumpserver/jms_all:v2.14.2
后解决
