### ISSUE TITLE
[Bug] v2.14.2 LDAP服务器密码强制设置

### ISSUE THREAD

**Issue by onecer** [jumpserver/jumpserver#7023]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.14.2

**浏览器版本**

chrome

**Bug 描述**

问题在于，LDAP的服务器端不是每个都一定要输入密码。这导致了我们以前用空密码连接的，压根无法保存。还要输入个密码，再到数据库中更新为空。
我们之前在v2.11.3这个版本是没问题的。

**Bug 重现步骤(有截图更好)**
1.  web端 -> 系统设置 -> LDAP设置
2. 
3.

**Comment by ibuler** [comment]
https://github.com/jumpserver/lina/pull/1095

**Comment by wojiushixiaobai** [comment]
生产环境中，应该使用带密码的账户进行鉴权。
