### ISSUE TITLE
对比teleport

### ISSUE THREAD

**Issue by jlijian3** [jumpserver/jumpserver#703]
https://github.com/eomsoft/teleport
同是开源堡垒机，jumpserver的web管理确实非常好，要是能跟teleport的核心结合就完美了。
跟teleport相比，核心功能差距还是比较大：
一、teleport支持windows、录像回放；
二、jumpserver用xshell、secureCRT等ssl client不能一键登录等等
三、性能方面没有测，teleport核心部分用C++开发，不知道会不会比python好点

**Comment by hellorocky** [comment]
你们公司在使用teleport吗?

**Comment by wuleiisme** [comment]
一、Jumpserver支持录像回放的
二、Xshell, SecureCRT需要转换一下证书格式

原先Teleport的缺点是没有MacOS客户端，现在也有了...
