### ISSUE TITLE
[Bug] jms bacup_db 定时备份有问题

### ISSUE THREAD

**Issue by omyhub** [jumpserver/jumpserver#7035]
** jumpserver 2.13.2

**Bug 描述**
kvm虚拟机做了ha高可用，主备上用crontab 调 jms backup_db备份，外置数据库(mariadb 10.6.4), 连续几天备份文件大小差异非常大,估计小的备份有问题，大的备份数据大小和我导出差不多。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35255549/138195642-23e67271-d448-465b-bfd4-7be73f5d952d.png)

**Comment by wojiushixiaobai** [comment]
下个版本优化不锁表导出
