### ISSUE TITLE
[Feature] v2.14.2不支持windows录像快进回放

### ISSUE THREAD

**Issue by shancuser** [jumpserver/jumpserver#7036]
**请描述您的需求或者改进建议.**
需求痛点：
出现运维事故，已经确认发生时间节点不能快进查看，导致要花较长时间定位问题

![image](https://user-images.githubusercontent.com/86365242/138199757-f12eafdf-738f-4011-96f3-bc72ade65836.png)

**Comment by BaiJiangJie** [comment]
新版本可以拖动，但是体验不是很好。

计划在 v3.3 版本中支持录像转码为 mp4 格式，这样体验会更好。
