### ISSUE TITLE
v.0.3.2推送用户提示 /var/tmp/scl0cXZos: line 8: -k: command not found\r\n

### ISSUE THREAD

**Issue by jiangping20160209** [jumpserver/jumpserver#705]
2017-09-15 14:07:22,840 - ansible_api.py - DEBUG - {'dark': {}, 'contacted': {u'Lserv-222': {'invocation': {'module_name': 'script',
 'module_complex_args': {}, 'module_args': u'/tmp/tmpQibAHw'}, 'stdout': '/var/tmp/scl0cXZos: line 8: -k: command not found\r\n', 'c
hanged': True, 'stderr': '', 'rc': 127}}}
客户端执行了这样一条命令： /usr/bin/scl enable devtoolset-1.1  '-k'

**Comment by jiangping20160209** [comment]
请jumpserver作者帮忙看下

**Comment by ibuler** [comment]
找打那个临时文件了？
