### ISSUE TITLE
[Question] 原先通过堡垒机免密登陆的机器，重装后再推送用户无法连接了，IP连接信息未变

### ISSUE THREAD

**Issue by wanghaibo-person** [jumpserver/jumpserver#7050]
**请描述您的问题.**
报错信息附件
![image](https://user-images.githubusercontent.com/46038902/138274399-35d26e9c-18d6-40be-8164-e1b4204536c6.png)

**Comment by wojiushixiaobai** [comment]
docker exec -it jms_core bash
