### ISSUE TITLE
[Bug]  jumpserver安装后启动失败

### ISSUE THREAD

**Issue by XzBuleSky** [jumpserver/jumpserver#7053]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver 2.14.2版本

**Bug 描述**
  按照文档进行部署操作,  安装完成启动报错.  按照文档报错在core容器中操作启动正常.   但是在容器重启 问题依旧.
  
```
$ docker exec -it jms_core python /opt/jumpserver/apps/manage.py makemigrations
Migrations for 'authentication':
  apps/authentication/migrations/0005_auto_20211022_1147.py
    - Change Meta options on loginconfirmsetting
```
**Bug 重现步骤(有截图更好)**
1.   启动报错
![image](https://user-images.githubusercontent.com/33563050/138390278-91de9b2d-03ed-4ddd-946d-32ccf6d7aa59.png)
2.  日志信息报错
![image](https://user-images.githubusercontent.com/33563050/138390322-98991c83-7ecb-419f-b805-5af9bdb1b909.png)
3. 根据报错操作启动成功信息  
![image](https://user-images.githubusercontent.com/33563050/138390538-ed48e3ad-ded6-46ef-9abf-2bb3a35f0aa4.png)
4. 重新启动报错
![image](https://user-images.githubusercontent.com/33563050/138390846-1fd983bb-e261-4c16-91db-c44eb01a1b02.png)

**Comment by wojiushixiaobai** [comment]
红色提示请勿处理，这是启动健康检查超时了。可以把时间改长
