### ISSUE TITLE
[Bug] 监控模式下，VIM乱码

### ISSUE THREAD

**Issue by Alceatraz** [jumpserver/jumpserver#7054]
**JumpServer 版本(v1.5.9以下不再支持)**

2.14.2

**浏览器版本**

Google Chrome 94.0.4606.81 (正式版本) （64 位） (cohort: Stable)
修订版本 5a03c5f1033171d5ee1671d219a59e29cf75e054-refs/branch-heads/4606@{#1320}

**Bug 描述**
监视会话中，监视者观看vim会变成乱码（原始字符序列），操作者不受影响。

**Bug 重现步骤(有截图更好)**
![QQ截图20211022134218](https://user-images.githubusercontent.com/8266702/138403945-c67d4165-ee26-4de9-a823-9e4ea1844695.png)

**Comment by LeeEirc** [comment]
vim 有特定的终端状态。中途监控的话，无法显示完整的视图。暂不处理这种情况了。
