### ISSUE TITLE
[Bug] vim编辑文本页面乱码问题

### ISSUE THREAD

**Issue by LalexH** [jumpserver/jumpserver#7058]
**JumpServer 版本(v1.5.9以下不再支持)**
1.5.9

**浏览器版本**
ssh 登录

**Bug 描述**
通过ssh登录shell后，一段时间后通过vim编辑文本会有如下截图的问题

**Bug 重现步骤(有截图更好)**
1.  通过ssh登录服务器
2.  使用一段时间后，vim编辑文本会出现如下问题
3. 
![image](https://user-images.githubusercontent.com/34831384/138420580-32949a34-1a90-434a-b326-596e6b0ff285.png)
4. 切换新窗口口问题消失，隔一段时间后又会复现

**Comment by wojiushixiaobai** [comment]
请在新版本验证问题是否解决。
