### ISSUE TITLE
[Question] Python 可以连接吗？

### ISSUE THREAD

**Issue by lhsaq2009** [jumpserver/jumpserver#7060]
**请描述您的问题.**
公司使用 jumpserver，目前日志分散在较多节点上，每次搜索日志，十分痛苦，需要每个节点去执行。

期望解决：

期望能有个 Python 连接方式，方便我直接获取所有 连接的节点，然后一键执行，进行查询

**Comment by wojiushixiaobai** [comment]
JumpServer 支持 syslog
