### ISSUE TITLE
[Bug] 命令过滤针对MySQL终端或者Hive终端不生效

### ISSUE THREAD

**Issue by wineejam** [jumpserver/jumpserver#7074]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.13.2

**浏览器版本**
chrome最新版本
SecureCRT8.5操作

**Bug 描述**
命令过滤针对MySQL终端或者Hive终端不生效

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/8789004/138797134-c72d8cc0-9e27-4e15-bb34-c1f75c069e7d.png)
 已设置 drop table 为禁用命令
2. 在CRT中登录MySQL终端中执行 drop table xxx，禁用不生效，命令正常执行
![image](https://user-images.githubusercontent.com/8789004/138797214-f519f872-9164-44b2-b132-937170d60687.png)
Hive终端类似情形也不生效
3. 在命令记录中能查询到drop table的命令
![image](https://user-images.githubusercontent.com/8789004/138797486-38d4195a-cf40-47ee-ba3c-73521bae85d2.png)

请问这个是BUG还是说针对MySQL终端或者Hive终端不能实现命令过滤？

**Comment by ibuler** [comment]
下面的正则有问题，上面的命令，之前没有开放带空格的命令，下个版本优化，命令可以带空格
