### ISSUE TITLE
[Bug] 全新环境录入邮件服务器配置未勾选TLS SSL报错

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#7088]
**JumpServer 版本(v1.5.9以下不再支持)**
2.14.2

**浏览器版本**
chrome

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  设置邮件服务器
2. 填写地址，去掉勾选SSL TLS提交报错
3. 勾选保存后，编辑去掉勾选 正常

![image](https://user-images.githubusercontent.com/44662176/139041596-bbe064b4-4bb6-475a-9dad-ae79e932862b.png)

**Comment by wojiushixiaobai** [comment]
新版本已修复
