### ISSUE TITLE
新增系统用户，选择私钥文件，总是报“ssh密钥不合法”的错误

### ISSUE THREAD

**Issue by DHLWDX** [jumpserver/jumpserver#709]
新增系统用户，选择私钥文件，总是报“ssh密钥不合法”的错误，我是把私钥，直接复制粘贴，保存为.txt文件

**Comment by hellorocky** [comment]
最好使用 sublime或者 notpad++编辑器, txt文件好像会在文本后面添加换行之类的隐藏字符, 注意检查密钥中是否有换行, 不能有换行符

**Comment by gxk001** [comment]
ssh-keygent -t rsa
之后，把私钥文件 id_rsa 复制出来，上传私钥时选择这个文件

**Comment by ericyee** [comment]
上传的秘钥在生成的时候不能设置密码，否则提示秘钥不正确。
