### ISSUE TITLE
[Bug] 开启 [AUTH_OPENID=true] 后，用户名密码登录界面报错

### ISSUE THREAD

**Issue by wangxiaochuang** [jumpserver/jumpserver#7090]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.14.2

**浏览器版本**
chrome Version 95.0.4638.54

**Bug 描述**
只开启AUTH_OPENID的配置，除了通过openid外，还想登录本地账号，但是输入账号密码后提交报错

**Bug 重现步骤(有截图更好)**

配置openid后，访问系统会显示如下界面，点击取消，使用本地账号登录
![图片](https://user-images.githubusercontent.com/12962576/139628102-52c55062-1da2-48c3-99e9-830effacb097.png)
![图片](https://user-images.githubusercontent.com/12962576/139628378-5697d41e-ae31-4467-bc36-79f11df17e56.png)

输入用户名密码点击登录后返回400
![20211027191234](https://user-images.githubusercontent.com/12962576/139055820-fa2fd8f7-d2b2-4244-adb5-abb3a7dc16fd.jpg)

**Comment by wangxiaochuang** [comment]
直接使用openid登录是没有问题的；现在我更新到v2.15.2版本了，取消openid登录后使用本地账号密码登录还是一样的问题。

**Comment by Gerrylinux** [comment]
这是日志内容，红框内是jms本地用户登录报错信息
![image](https://user-images.githubusercontent.com/31839722/140488292-4b29876f-2518-4da1-a286-a19be96c22a9.png)

**Comment by wojiushixiaobai** [comment]
请在新版本验证问题是否解决，有问题请重新打开此问题
