### ISSUE TITLE
有没有办法设置jumpserver终端的屏占比大小，左右的黑边太多

### ISSUE THREAD

**Issue by MagicStarTrace** [jumpserver/jumpserver#7092]
**请描述您的需求或者改进建议.**

我目前使用的jumpserver version是2.13.2 

在web终端看到左右两侧全是黑边，有没有办法设置调整大小？

![293E0A4B-621F-4368-91BB-CD45C0167BB3](https://user-images.githubusercontent.com/15685376/139176189-bd802770-a5d9-45fb-a9b5-1dbcc1f45272.png)

这屏占比太浪费了

另外右边的三个(剪贴板、文件上传、快捷键)选项卡有没有地方可以隐藏， 我记得历史版本是没有的

**Comment by jym503558564** [comment]
可设置一下分辨率，如还有其他问题，可再次打开Issues
![image](https://user-images.githubusercontent.com/40739051/152740285-74a36e92-e861-4e89-b42b-1ab7ffe37b9b.png)
