### ISSUE TITLE
怎么更改注册邮件中秘钥下载地址？

### ISSUE THREAD

**Issue by chudada** [jumpserver/jumpserver#710]
我找到user_api.py  文件，将“%S”更改为如图
![image](https://user-images.githubusercontent.com/32056144/30532047-9d8ef934-9c84-11e7-8fad-40e262f43d18.png)   并且重新生成了.pyc文件，但是还是不生效  求助

**Comment by nice-jj** [comment]
需要重启jumpserver

**Comment by meeking1** [comment]
没有加端口号吧
