### ISSUE TITLE
jumpserver 添加 win2016 资源，测试连接的时候报错

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#7109]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.12.1

**浏览器版本**

**Bug 描述**
在添加了win2016资源之后，测试资产连接性的时候报错：kombu.exceptions.EncodeError: Object of type Asset is not JSON serializable

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/29726716/139370273-f4db640a-7dc6-45f3-b298-599e3182f37b.png)

2. 
![image](https://user-images.githubusercontent.com/29726716/139370141-d6a32bf6-a21a-4bc9-91ee-dc12f089aeb3.png)

3. 
![image](https://user-images.githubusercontent.com/29726716/139370213-4061efba-49ab-44e1-b4b1-c3d2a9175a9f.png)

**Comment by wojiushixiaobai** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_rdp/
请勿使用 windows2016 系统平台
