### ISSUE TITLE
coco 在xshell 中使用sz 下载到一半出现乱码，然后停止下载。

### ISSUE THREAD

**Issue by hfq-haochenxiao** [jumpserver/jumpserver#711]

**Comment by lichenglongqi** [comment]
这应该不是coco的问题吧，你就算不用jumpserver，有时候sz，或者rz的时候，也会出现乱码，然后中断吧

**Comment by hfq-haochenxiao** [comment]
@lichenglongqi  嗯，请问下造成这个问题的原因是什么，有什么好的解决办法吗。

**Comment by lichenglongqi** [comment]
@hfq-haochenxiao 并不知道是什么原因，我以前也偶尔会遇到这样的问题

**Comment by hfq-haochenxiao** [comment]
@lichenglongqi  好的。谢谢。

**Comment by roarlion** [comment]
在CRT中测试也是这样，下载一会儿以后出现满屏乱码，有时会是可以下载成功的，用xshell下载的话没有成功过

**Comment by penglongsd** [comment]
你这个问题最后怎么解决的那？我也遇到同样的问题

**Comment by roarlion** [comment]
没有找到好的方法，新版本还没尝试，secureCRT出现这种情况较少；



cyzwroarlion@foxmail.com
 
发件人： penglongsd
发送时间： 2018-03-28 16:50
收件人： jumpserver/jumpserver
抄送： roarlion; Comment
主题： Re: [jumpserver/jumpserver] coco 在xshell 中使用sz 下载到一半出现乱码，然后停止下载。 (#711)
你这个问题最后怎么解决的那？我也遇到同样的问题

**Comment by Holmeyoung** [comment]
文件：
zip **YourFile**.zip **乱码的文件**

文件夹：
zip -r **YourFolder**.zip **乱码的文件夹**

然后传输压缩文件

**Comment by wanrui** [comment]
怀疑zmodem 协议处理标准应该有一定的关系
