### ISSUE TITLE
[Bug] ssh 2222 端口 rz sz 文件乱码

### ISSUE THREAD

**Issue by jhsswl** [jumpserver/jumpserver#7112]
**JumpServer 版本(v1.5.9以下不再支持)**
2.15.1

**浏览器版本**

**Bug 描述**
xshell ssh 2222端口登录跳板机，在资产主机上rz上传文件就乱码，传输出错

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
网络问题，请自行检查下
