### ISSUE TITLE
[Feature] JumpServer用户登录规则支持分时登录全局设置

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7117]
**请描述您的需求或者改进建议.**
     在JumpServer最新版2.15版本中支持用户登录规则支持分时登录，但是这个功能是针对单个用户来设置。希望能添加全局设置。否则用户过多的环境没办法管理。

**Comment by jym503558564** [comment]
已记录，并反馈给开发人员。请持续关注我们未来版本发布～
