### ISSUE TITLE
centos6 Jumpserver0.4.0 报错

### ISSUE THREAD

**Issue by Jonnter** [jumpserver/jumpserver#712]
执行bash make_migrations.sh 
报错如下
    from .group import *
  File "/opt/jumpserver/apps/users/models/group.py", line 11, in <module>
    from common.utils import signer, date_expired_default
  File "/opt/jumpserver/apps/common/utils.py", line 19, in <module>
    import paramiko
  File "/usr/local/python3/lib/python3.5/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/python3/lib/python3.5/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/usr/local/python3/lib/python3.5/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/usr/local/python3/lib/python3.5/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: module 'gssapi' has no attribute 'GSSException'

**Comment by guanqinglin** [comment]
同问，这是啥问题。。。。

**Comment by gxk001** [comment]
ssh_gss.py，53,54行改成：
53     import gssapi.error
54     GSS_EXCEPTIONS = (gssapi.error.GSSException,)

**Comment by Jonnter** [comment]
今天又试了一下， 安装完Python之后，直接进入Python3的虚拟环境中，在安装jumpserver就不会出现这个问题了

**Comment by chinarhcx** [comment]
都是在python3环境中试过很多次，都是这样的，再试试gxk001那种方法看看

**Comment by chinarhcx** [comment]
还是不行的，还是有错误的,神奇了，装了很多次，就第一次居然成功了，其他的全部失败，都是这个错误

**Comment by nc430** [comment]
一样的问题，不知道为何，gssapi好像不行，换成python-gssapi可以，但是其他的一样报错，不知道是不是这个版本的jumpserver有问题

**Comment by gxk001** [comment]
![image](https://user-images.githubusercontent.com/32119424/30633672-1d018df8-9e1f-11e7-9376-5c670da31a81.png)
http://pythonhosted.org/python-gssapi/api/gssapi.html#module-gssapi.error

上面是我的版本。估计和环境有关。

而且 py3.6.2 + ansible 2.4 会报Inventory 的 importError，
pip uninstall ansible
pip install "ansible>2.3,<2.4" 
之后才可以。

**Comment by armolee** [comment]
安装的时候把requirements的>=都改成==，基本没什么问题

**Comment by nc430** [comment]
对的，我两个gssapi都装了，然后ansible报模块错误，试试修改requirements试试

**Comment by Arnosir** [comment]
保证下面的两个包的版本为指定版本。 别 >= 默认的安装。
ansible                  2.2.2.0
paramiko                 2.1.2

**Comment by ibuler** [comment]
已更改requirements

**Comment by vslinux** [comment]
今天安装jumpserver1.4.1 也报同样的错误，把paramiko-2.4.1降为paramiko-2.3.1正常！
