### ISSUE TITLE
数据库应用批量改密失败[Bug] 

### ISSUE THREAD

**Issue by Garen2020** [jumpserver/jumpserver#7122]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.15.2

**Bug 描述**
mysql数据库版本5.6.51-2.el7，改密计划执行失败

**Bug 重现步骤(有截图更好)**
<img width="930" alt="bug" src="https://user-images.githubusercontent.com/60033632/139557860-5ddbe21d-e6f8-4fe6-808f-0479f81e13d7.png">

**Comment by feng626** [comment]
暂时不支持mysql5.7以下版本
