### ISSUE TITLE
云管中心同步资产任务云端和Jumpserver资产不同步[Bug] 

### ISSUE THREAD

**Issue by Garen2020** [jumpserver/jumpserver#7123]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.15.2

**Bug 重现步骤(有截图更好)**
1. 阿里云创建一台资产
2. JMS配置阿里云账号密码，并创建同步任务，手动执行一次，阿里云的资产自动同步过来
3. 阿里云释放这台资产，手动执行同步任务一次，JMS资产管理中的这台资产还在，没有做到与云上资产的同步
<img width="933" alt="bug1" src="https://user-images.githubusercontent.com/60033632/139566432-2d8e9efe-6034-4f44-a6b7-ebfb549cef0c.png">
<img width="919" alt="bug2" src="https://user-images.githubusercontent.com/60033632/139566441-abe31c99-f083-48af-8f1b-1c738919a01e.png">

**Comment by coxi-wik** [comment]
释放需要手动操作，在同步历史详情中，有删除已释放资产的按钮

**Comment by coxi-wik** [comment]
释放需要手动操作，在同步历史详情中，有删除已释放资产的按钮

**Comment by coxi-wik** [comment]
释放需要手动操作，在同步历史详情中，有删除已释放资产的按钮

**Comment by Garen2020** [comment]
好的，验证可以
