### ISSUE TITLE
[Bug] 特权用户与系统用户无法保存ssh密钥

### ISSUE THREAD

**Issue by wangrenqing** [jumpserver/jumpserver#7124]
**JumpServer 版本(v1.5.9以下不再支持)**

Version v2.15.2 GPLv
**浏览器版本**
版本 95.0.4638.54（正式版本） (x86_64)

**Bug 描述**

[Bug] 特权用户与系统用户无法保存ssh密钥
**Bug 重现步骤(有截图更好)**
1
![image](https://user-images.githubusercontent.com/30227537/139566529-5a554438-f623-45c9-8247-194e1f22097f.png)
![image](https://user-images.githubusercontent.com/30227537/139566547-236e92ad-0926-49d3-a11a-4b004dd796b5.png)

![image](https://user-images.githubusercontent.com/30227537/139566648-1bcfc656-abca-4095-87e7-4f9cc1d970a7.png)

系统 用户我也试过，一样子
安装方式，昨天通脚本快速安装的，先是安装 了Version v2.15.0，发现不行，再执行./jmsctl.sh check_update 升级 发现还是不可以。。

**Comment by wangrenqing** [comment]
提示保存成功的。

![image](https://user-images.githubusercontent.com/30227537/139566734-a2d09c93-86eb-420a-88c0-054f6a24a30e.png)

**Comment by ibuler** [comment]
收到，正在处理

**Comment by ibuler** [comment]
已修复 https://github.com/jumpserver/jumpserver/releases/tag/v2.15.3

非常抱歉出现这个 bug

**Comment by wangrenqing** [comment]
大佬 可以，
不错，牛批。。

**Comment by wangrenqing** [comment]
THs~
