### ISSUE TITLE
[Bug] JumpServer MFA无法重置

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7125]
版本：2.14
条件：同时开启了MFA验证和短信认证
问题：在同时开启了MFA和短信认证的时候点击重置MFA不会进入重新绑定过程

Bug 重现步骤
1.  开启MFA验证
2. 开启短信验证
3. 点击重置MFA按钮
4. 不会有重新绑定MFA的过程
5. 需要解绑短信认证才会有MFA的认证过程

**Comment by wojiushixiaobai** [comment]
最新版本已解决
