### ISSUE TITLE
[Bug] 公告提示不支持换行显示

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#7127]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.15.1
**浏览器版本**

**Bug 描述**
告示提示功能不支持换行显示

**Bug 重现步骤(有截图更好)**
1.  设置公告提示，“系统设置>基本设置>启用公告”；
2. 配置公告内容，内容中包含换行内容；
3. 返回仪表盘首页，公告内容未换行；

配置公告内容，包含换行内容：
![image](https://user-images.githubusercontent.com/34565342/139627628-e0e5d6ed-bfec-4d26-83df-b388f88f6918.png)
实际显示时，未换行：
![image](https://user-images.githubusercontent.com/34565342/139627664-4748d758-b05b-4a71-bbea-7637e8713a29.png)

**Comment by jym503558564** [comment]
已记录，并反馈给开发人员。
