### ISSUE TITLE
[Bug] JumpServer工单审批权限错乱

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7128]
版本：2.15
问题：JumpServer工单审批权限错乱
步骤：
1.  设置JumpServer中张三用户为管理员
2.  普通用户申请资产张三有审批权限
3.  设置张三为普通用户
4.  普通用户张三还有资产审批权限

**Comment by feng626** [comment]
审批人设置的是张三是么  要是已经自定张三为审批人的话 张三是可以审批的

**Comment by wojiushixiaobai** [comment]
使用模板？
