### ISSUE TITLE
[Bug] 资产授权详情 undefined

### ISSUE THREAD

**Issue by Eid-Chen** [jumpserver/jumpserver#7135]
**JumpServer 版本(v1.5.9以下不再支持)**
2.15.2  &  2.15.3

**浏览器版本**
版本 95.0.4638.69（正式版本） （64 位）

**Bug 描述**
1.根据官网：https://docs.jumpserver.org/zh/master/install/setup_by_lb/ ，目前搭建 了一台主节点
2.数据库使用阿里云RDS ，Redis 服务，Redis版本：5
3.使用 Google Chrome浏览器登陆新搭建的jumpserver查看授权详细信息 ，第一次点击 无详细信息，返回第二次点击查看就可查，或者刷新浏览器也可以
4.查看系统用户详情依然发生这个问题

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/44772350/140013105-3e7cc8b4-8fb3-4a00-89b6-0eeb096efb99.png)
![image](https://user-images.githubusercontent.com/44772350/140013132-8114b71f-4ba9-4264-9f5b-dedc39881d72.png)
![image](https://user-images.githubusercontent.com/44772350/140013147-216c82bc-0050-468b-95f7-b5f17217cece.png)

**Comment by Eid-Chen** [comment]
Microsoft Edge 版本 95.0.1020.40 (官方内部版本) (64 位)

补充： Edge浏览器也有这个问题

补充：2.15.2  存在，升级至  2.15.3 ，依然存在

**Comment by wojiushixiaobai** [comment]
日志发上来看看，可以尝试使用自带的 redis 看看问题是否复现

**Comment by Eid-Chen** [comment]
您好，很高兴收到您的回复，调取部分日志如下，如需更多烦请告知
![image](https://user-images.githubusercontent.com/44772350/140261001-f520dc13-a76f-4d9e-938d-e8bea5e49b90.png)
![image](https://user-images.githubusercontent.com/44772350/140261011-0b10cc3d-49ac-4093-8587-43808eacad48.png)
![image](https://user-images.githubusercontent.com/44772350/140261019-875158fd-5e8e-4063-8d6e-aac225547fcf.png)
![image](https://user-images.githubusercontent.com/44772350/140261025-9ce81f9b-72fe-46a6-b4bc-83d2c68aeb3d.png)

另外查看 drf_exception.log 可见如下，jumpserve应该是自动安装python3.6版本，但是不知为何有python3.8的调用，不知是否能够对您的分析提供帮助
![image](https://user-images.githubusercontent.com/44772350/140261137-ee8f4578-5a79-45a5-a2df-0d86e674319a.png)

综上，十分感谢

**Comment by Eid-Chen** [comment]
另补充： 在升级2.15.3之前的 2.15.2版本，曾尝试使用本地mysql和redis，仍存在该现象

**Comment by wojiushixiaobai** [comment]
访问下 Demo：https://demo.jumpserver.org/
看下是否能复现，我没法在我的环境复现这个，是否有其他的安全拦截如 WAF 作用

**Comment by Eid-Chen** [comment]
您好，在  Demo：https://demo.jumpserver.org/    并没有发现我遇到的问题 ， 是否给你提供详细的日志以便提供帮助？

**Comment by wojiushixiaobai** [comment]
无法复现此问题，我后续会继续关注，看是否有其他用户复现

**Comment by Anorpi** [comment]
我这边也遇到了相同的问题

**Comment by superHuang476** [comment]
经多次测试，内部跨网端访问会出现该问题，使用VPN访问则不会出现

**Comment by superHuang476** [comment]
经多次测试，内部跨网段访问会出现该问题，使用VPN访问则不会出现
