### ISSUE TITLE
[Feature] 增加连接限速(client <--> 跳板机 <---> server)

### ISSUE THREAD

**Issue by omyhub** [jumpserver/jumpserver#7140]
**问题.**
有开发人员或者运维使用跳板机传输数据，最常见用 rz,sz （lrzsz）传输数据，导致jumpserver服务器网卡跑满，
**建议**
能够设置全局限速，针对jumpserver console 或 web terminal 方式的连接 或者 其他方式解决服务器和本地比较大的文件传输问题 ， 10M-100M

**Comment by wojiushixiaobai** [comment]
网络问题，原则上应该在上层应用防火墙进行协议流量限制。
