### ISSUE TITLE
JumpServer v2.13.2版本使用需求

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#7141]
1.这个会话管理-历史会话处的目标类型，能不能指定成应用的类型，或者单独再有个类型指名对应的应用项。
目前这个截图中是一台远程应用的win服务器，但是后台对这个win-server发布了多个数据库，如果需要紧急排查某个远程应用数据库的录像，这样审计效率不太高效阿。
![image](https://user-images.githubusercontent.com/77430030/140291025-ffd025b1-c62c-4486-be0e-c5b331d11bdd.png)

使用建议：
2.在资产授权侧，如果涉及到单台资产多个系统用户的授权，能否在模糊搜索出来系统用户信息后，多选不进行页面刷新，在多选完成后，点击空白侧来进行页面的刷新。（如果存在多个同名的系统用户，在搜索出来后选一个刷新一次，再搜索选择，运维使用上不太效率）  

3. 与问题2类似，在堡垒机页面，比如资产列表，想要更新主机名包含test的资产信息，搜索结果有多个（test1、test2）。在更新完一台test1后，界面也是直接刷新了，需要重新搜索后，才可以找到test2的信息进行更新。运维操作会比较繁琐。

**Comment by coxi-wik** [comment]
补充一张建议2的图

![65ee9f5b2350a8795f9d375868bc7f3](https://user-images.githubusercontent.com/77430030/140293098-f0efb2c9-389d-401a-b12a-5d6546c84750.png)

**Comment by BaiJiangJie** [comment]
v3 版本中有一些优化，建议升级使用。
