### ISSUE TITLE
[Feature] 点击资产修改或者授权修改后返回到原来选中的树节点

### ISSUE THREAD

**Issue by liuchangfitcloud** [jumpserver/jumpserver#7146]
**请描述您的需求或者改进建议.**
希望在每次修改完资产信息或者授权信息后可以返回到原来选中的数节点位置
![image](https://user-images.githubusercontent.com/44662176/140670948-1be4cfef-11c3-4b45-9845-2eb76e011e65.png)

**Comment by jym503558564** [comment]
跟研发人员反馈了，将在未来版本进行优化。预计是v3后～
