### ISSUE TITLE
[Feature] windows资产web页面的快捷键栏添加“ESC”快捷键

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#7147]
**请描述您的需求或者改进建议.**
使用web方式全屏登录windows服务器的时候，有时候需要按ESC退出某个软件或者编辑模式，结果是退出了全屏。想在快捷键栏里面添加一个esc快捷键。

**Comment by wojiushixiaobai** [comment]
已在计划中。

**Comment by LeeEirc** [comment]
已经添加 ESC 和 F11 快捷键
