### ISSUE TITLE
[Bug] 无法保存资产详情

### ISSUE THREAD

**Issue by nlwng** [jumpserver/jumpserver#7149]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.15.2

**浏览器版本**
chrome 版本 95.0.4638.69（正式版本） （64 位）

**Bug 描述**
无法保存资产详情，只能保存固资号，无法保存

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/4245956/140679580-0093c019-be7d-468b-967d-79e302e2d650.png)
![image](https://user-images.githubusercontent.com/4245956/140679718-b2e86ba7-14e5-4dc1-9bd9-0431d8495153.png)

**Comment by jym503558564** [comment]
新版本未复现该问题，请更新至新版本进行测试。如还存在该问题，可再次打开Issues
