### ISSUE TITLE
[Feature] 尾纤命令操作发送通知

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#7155]
**请描述您的需求或者改进建议.**
执行有些命令的时候允许执行，发送邮件给管理员

**Comment by BaiJiangJie** [comment]
新版本支持`危险命令告警`，对于普通命令，暂时不考虑支持。

<img width="1827" alt="image" src="https://user-images.githubusercontent.com/32935519/232730580-68942e80-88bd-4363-8368-c772681bf201.png">
