### ISSUE TITLE
[Feature] 终端管理组件离线后对邮件或站内信的同步时效

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#7157]
**请描述您的需求或者改进建议.**
JumpServer v2.13.2
1.在测试堡垒机组件离线后是否会进行邮件同步告警中发现。
终端管理组件检测的状态为30s左右，但是组件离线后对邮件或站内信的同步时效均为1h，感觉有点太长了，这里时效是否应该进行下优化，将发送邮件时效缩短或者提供一个参数项让用户自定义发件时效。

<img width="515" alt="c61f6003b1b5c3f02250744f35725a0" src="https://user-images.githubusercontent.com/77430030/140877868-dcddea77-d3d5-426a-ba6b-df70c20876b3.png">

**Comment by jym503558564** [comment]
目前暂不支持自定义时效
