### ISSUE TITLE
使用动态用户，登录进去没有普通用户的home权限

### ISSUE THREAD

**Issue by xisafe** [jumpserver/jumpserver#7167]
用SSH连接（devops-@10.192.1.1）[连接数量: 1]
Last login: Thu Nov 11 11:45:46 2021 from 10.192.1.218
Could not chdir to home directory /home/13834: Permission denied
-bash: /home/13834/.bash_profile: Permission denied
-bash-4.2$

**Comment by wojiushixiaobai** [comment]
推送异常？
