### ISSUE TITLE
粘贴的时候中文乱码，再重新复制一次粘贴就正常了

### ISSUE THREAD

**Issue by MagicStarTrace** [jumpserver/jumpserver#7170]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver版本 2.13.2

**浏览器版本**
chrom是最新版本

**Bug 描述**
web终端经常出现粘贴出现中文乱码，是因为字符集转换出现bug了吗？

**Bug 重现步骤(有截图更好)**
1 本地拷贝一段大约200行左右的文本(含中英文)
2 在远端ubuntu中粘贴 出现乱码

**Comment by wojiushixiaobai** [comment]
尚未复现此问题，我会关注此问题。

**Comment by MagicStarTrace** [comment]
> 

应该是到文字上限了
