### ISSUE TITLE
[Bug] v2.15.3使用web终端出现Connection websocket closed

### ISSUE THREAD

**Issue by smallodd** [jumpserver/jumpserver#7171]
**JumpServer 版本(v1.5.9以下不再支持)**
![image](https://user-images.githubusercontent.com/13759794/141249155-128b8c5a-c9ac-46db-b02e-79a71674d9c2.png)

**浏览器版本**
![image](https://user-images.githubusercontent.com/13759794/141249103-4ac19a6b-efd2-4ac8-81fe-577b571252a3.png)

**Bug 描述**
v2.15.3使用web终端出现Connection websocket closed

**Bug 重现步骤(有截图更好)**
1.  启动web终端
2. 随便点击进入一个资产
3. 使用tail命令看log
4. 不一会儿出现

![image](https://user-images.githubusercontent.com/13759794/141249043-bebad30a-e9de-4597-9a26-32c975bad83e.png)

**Comment by wojiushixiaobai** [comment]
检测反向代理
https://docs.jumpserver.org/zh/master/admin-guide/proxy/

**Comment by smallodd** [comment]
> 检测后端代理 https://docs.jumpserver.org/zh/master/admin-guide/proxy/

没有使用Nginx  只是ip直接访问

**Comment by wojiushixiaobai** [comment]
如果使用了代理请关闭代理，如果使用了vpn，请在vpn里配置websocket支持
