### ISSUE TITLE
[BUG] 普通用户无法启动

### ISSUE THREAD

**Issue by purplegrape** [jumpserver/jumpserver#7173]
**JumpServer 版本(v1.5.9以下不再支持)**
版本：2.15.3

**浏览器版本**
无

**Bug 描述**
使用普通用户身份启动jumpserver失败，报权限不够

**Bug 重现步骤(有截图更好)**
1.  chown -R root.root /opt/jumpserver
2.  chown -R centos.centos /opt/jumpserver/{data,logs}
3. su - centos
4. source py3-venv/bin/activate
5. ./jms start all

**Comment by purplegrape** [comment]
修改配置文件config.yml ,  指定 LOG_DIR 路径但不生效

**Comment by wojiushixiaobai** [comment]
给与 docker 权限，自行测试

**Comment by purplegrape** [comment]
python start_celery_beat.py 
Get beat lock start to run it
celery beat v4.4.2 (cliffs) is starting.
Traceback (most recent call last):
  File "/usr/share/jumpserver-python3-venv/lib64/python3.6/site-packages/celery/platforms.py", line 149, in acquire
    self.write_pid()
  File "/usr/share/jumpserver-python3-venv/lib64/python3.6/site-packages/celery/platforms.py", line 216, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
PermissionError: [Errno 13] Permission denied: '/usr/share/jumpserver/apps/celerybeat.pid'

已查到问题根源是jumpserver/utils/start_celery_beat.py  脚本

改进办法如下
cmd = [
    'celery', 'beat',
    '-A', 'ops',
    '-l', 'INFO',
    '--scheduler', scheduler,
    '--pidfile','/tmp/beat.pid',
    '--max-interval', '60'
]

指定一个可写的目录     '--pidfile','/tmp/beat.pid',
