### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by zxy860320** [jumpserver/jumpserver#7178]
**请描述您的问题.**
windows安装vscode无法通过跳板机连接到指定服务器。报如下错误
![image](https://user-images.githubusercontent.com/45409926/141423719-f80f5e00-2e1b-46da-83f3-4f49659353a8.png)
请问是我的vscode配置有问题吗？我用的是这个命令ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222.
powersehll使用这个命令是没有问题的。我看官方更新文档也已经修复了这个bug的，而且我用的跳板机是v2.15.3版本的。
![image](https://user-images.githubusercontent.com/45409926/141423909-63cf13a8-5415-470c-a4fb-78f6caedb5b4.png)

**Comment by wojiushixiaobai** [comment]
- /opt/jumpserver/config/config.txt
```
ENABLE_LOCAL_PORT_FORWARD=true   # 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
ENABLE_VSCODE_SUPPORT=true       # 是否开启 针对 vscode 的 remote-ssh 远程开发支持 ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。( 注意: vscode 的连接操作，无审计功能 )
```

**Comment by zxy860320** [comment]
非常感谢你的解答，我按照你说的进行配置了，也重启了jumpserver，但是我在vscode客户端还是报同样的错误.

**Comment by wojiushixiaobai** [comment]
未复现，确定该资产的系统用户唯一且为自动登录。
可以手动 ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222 确定输入密码后可以直接连接到资产。
