### ISSUE TITLE
[Question] 安装问题

### ISSUE THREAD

**Issue by asskss** [jumpserver/jumpserver#7179]
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    8m17s                  default-scheduler  Successfully assigned jms/jumpserver-jms-celery-c4b8d9975-9vpw4 to master
  Warning  FailedMount  6m14s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[jms-core-data jms-core-logs], unattached volumes=[jms-core-config jms-core-data jms-core-logs kube-api-access-m6mk6]: timed out waiting for the condition
  Warning  FailedMount  3m56s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[jms-core-logs jms-core-data], unattached volumes=[jms-core-logs kube-api-access-m6mk6 jms-core-config jms-core-data]: timed out waiting for the condition
  Warning  FailedMount  2m3s (x11 over 8m16s)  kubelet            MountVolume.SetUp failed for volume "pvc-a42451f1-3be3-40b8-b8d6-2e8e7b376d30" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 192.168.159.10:/data/nfs-k8s/jms-jumpserver-jms-core-logs-pvc-a42451f1-3be3-40b8-b8d6-2e8e7b376d30 /var/lib/kubelet/pods/67c9c892-729c-407e-b0ba-693faaecca3b/volumes/kubernetes.io~nfs/pvc-a42451f1-3be3-40b8-b8d6-2e8e7b376d30
Output: mount.nfs: mounting 192.168.159.10:/data/nfs-k8s/jms-jumpserver-jms-core-logs-pvc-a42451f1-3be3-40b8-b8d6-2e8e7b376d30 failed, reason given by server: No such file or directory
  Warning  FailedMount  98s                  kubelet  Unable to attach or mount volumes: unmounted volumes=[jms-core-data jms-core-logs], unattached volumes=[jms-core-data jms-core-logs kube-api-access-m6mk6 jms-core-config]: timed out waiting for the condition
  Warning  FailedMount  1s (x12 over 8m17s)  kubelet  MountVolume.SetUp failed for volume "pvc-7f83fabe-fac6-4cfa-be8c-978227409711" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 192.168.159.10:/data/nfs-k8s/jms-jumpserver-jms-core-data-pvc-7f83fabe-fac6-4cfa-be8c-978227409711 /var/lib/kubelet/pods/67c9c892-729c-407e-b0ba-693faaecca3b/volumes/kubernetes.io~nfs/pvc-7f83fabe-fac6-4cfa-be8c-978227409711
Output: mount.nfs: mounting 192.168.159.10:/data/nfs-k8s/jms-jumpserver-jms-core-data-pvc-7f83fabe-fac6-4cfa-be8c-978227409711 failed, reason given by server: No such file or directory

**Comment by asskss** [comment]
MountVolume.SetUp failed for volume "pvc-077ef8dd-a979-4645-8c4f-1f6cf71c91b3" : mount failed: exit status 32

**Comment by wojiushixiaobai** [comment]
pvc need ReadWriteMany.
Re-detect storage mount.

**Comment by ibuler** [comment]
您超过 30 天未反馈信息，我们将关闭该 issue，如有需求您可以重新打开或者提交新的 issue
