### ISSUE TITLE
jumpserver的用户、管理用户、系统用户、分别指什么？有什么区别？

### ISSUE THREAD

**Issue by DHLWDX** [jumpserver/jumpserver#718]
由于jumpserver 的“用户”比较多，搞不清楚用户、管理用户、系统用户分别代表什么？请大神帮忙解惑一下

**Comment by qils** [comment]
用户： 这个用户指堡垒机账号， 就是你能用这个账号登录web页面， 登录跳板机服务器的用户， 登录方式是秘钥登录。

管理用户： 这个用户是你的目标资产主机上面拥有很高权限的用户比如root, 这个用户的目的是用来通过ansible接口推送下面将要说的系统用户。

系统用户： 指你需要登录的目标资产主机的普通用户， 这个用户是给你登录目标主机的用户， 批量执行命令的用户。

**Comment by qinshulei** [comment]
建议在系统里面加相关说明．直接用系统的时候，看到这个两个用户创建，觉得非常困惑．

**Comment by fanlc** [comment]
jumpserver 用户,系统用户和管理用户 普通用户和特权用户 区别：
https://www.cnblogs.com/fanfanfanlichun/p/15060625.html
