### ISSUE TITLE
[Feature] Web SSH中增加快捷命令功能

### ISSUE THREAD

**Issue by moestars** [jumpserver/jumpserver#7187]
**请描述您的需求或者改进建议.**
Web SSH中增加快捷命令功能
可极大方便客户使用时手打命令。提高工作效率

**Comment by wojiushixiaobai** [comment]
比如

**Comment by moestars** [comment]
> 请举例说明： 比如什么快捷键
感谢回复，类似于这样的。添加快捷命令列列如 yum update 只需在SSH附近选择这个系统就能自动输入之前添加好的命令
![GNZ~JK0AW(LGXZ}V@1G @MM](https://user-images.githubusercontent.com/46750719/141885506-249d1af6-b4a6-4d68-99a2-fad39c086126.png)
![image](https://user-images.githubusercontent.com/46750719/141885577-0142f19c-a410-41b2-a338-a6349c44c291.png)

**Comment by moestars** [comment]
对于要输入长命令来说可以节省很多时间，只需添加好预设点一下就能自动输入进SSH里面

**Comment by wojiushixiaobai** [comment]
我整理下你的需求：
- 允许用户自定义 ssh 快捷键

是这样吧，我看你输入的命令都是个性化的命令，并非通用

**Comment by moestars** [comment]
对的，自定义 SSH 个性化命令，选择某条命令后自动输入到 SSH 里。
然后有两个按钮 一个是输入后运行，另一个仅输入到 SSH 中但不运行，需要用户手动按回车运行。

**Comment by moestars** [comment]
可以参考一下隔壁 spug ，他们有个批量命令，里面可以添加自定义命令模板。但在 WEB SSH 中并没有模板。
Web SSH唯独就差了这个，目前我所知的在线 SSH 软件都没有这个功能

**Comment by wojiushixiaobai** [comment]
提上去了，感谢建议

**Comment by chaosky** [comment]
> 请举例说明： 比如什么快捷键

可以在 web 终端里面支持 [tmux](https://github.com/tmux/tmux) 或者 [byobu](https://help.ubuntu.com/community/Byobu) 的[快捷键](https://www.ruanyifeng.com/blog/2019/10/tmux.html)吗？
