### ISSUE TITLE
更新版本后发现资产页有地方显示有问题，可以帮忙看下吗

### ISSUE THREAD

**Issue by xiao12138-wtc** [jumpserver/jumpserver#7191]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/57217982/141737093-f8c9b128-3079-43f3-a744-3ec8f8c7260d.png)
![image](https://user-images.githubusercontent.com/57217982/141737331-5aa667af-db33-4a35-b61f-7198345a9929.png)
资产不能翻页了，节点也不能显示，是不是我导入之前的数据时这张表有误是有无误，帮忙看下，感谢

**Comment by ibuler** [comment]
数据自己导入更换过？删除一个资产刷新一下数量试试

**Comment by xiao12138-wtc** [comment]
和节点有关系，看起来只认到了Default节点的资产，其他自定义的资产下的节点显示有问题

**Comment by xiao12138-wtc** [comment]
我现在的节点大部分是自定开头的，不是Default开头，有什么解决办法呢，只能手动更改吗，请教

**Comment by xiao12138-wtc** [comment]
都是下面这种的
![image](https://user-images.githubusercontent.com/57217982/142172135-3fb555ff-de3b-4566-beee-ae2d56ce8dad.png)

**Comment by jym503558564** [comment]
联系我们微信群管理员，远程协助一下
