### ISSUE TITLE
[Bug] 用户登陆规则不能实时生效

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#7192]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.15.3
**浏览器版本**
chrome

**Bug 描述**
已登陆在线的用户，在限制时间段（拒绝/复核）中不会被强制下线

**Bug 重现步骤(有截图更好)**
1.  先登陆普通用户，保持在线状态
2. 通过管理员设置限制时间段登陆（拒绝/复核）规则；
3. 在限制时间段之前登陆的用户，且保持在线状态下，不会被强制登出

**Comment by ibuler** [comment]
只在登陆时控制，没有下线已登陆的
