### ISSUE TITLE
[Bug] 语言切换英文后，执行“重置密码”操作，站内信通知内容显示为中文非英文

### ISSUE THREAD

**Issue by chenxin2001** [jumpserver/jumpserver#7198]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
语言切换英文后，执行“重置密码”操作，站内信通知内容显示为中文非英文

**Bug 重现步骤(有截图更好)**
1.  切换英文
2. 重置密码
3. 点开站内信查看详情

![image](https://user-images.githubusercontent.com/34565342/141753347-6f229ea6-e5d4-4da9-8178-3972c5ec4dfb.png)

**Comment by ibuler** [comment]
这种异步发送的信息，目前只能根据系统的语言来发送

**Comment by jym503558564** [comment]
已记录
