### ISSUE TITLE
非管理员自由管理名下资产分组

### ISSUE THREAD

**Issue by tystal** [jumpserver/jumpserver#7200]
非管理员的对资产管理，可以实现**自由分组重命名**。
类似QQ好友分组，我怎么分组备注，对其他用户均不会造成任何影响。
![image](https://user-images.githubusercontent.com/41604851/141881440-972570e0-9bbe-4570-ba37-390992f66714.png)
对于我们而言，使用场景不一样。实际使用频率更高的实际是业务部门，而非运维。
管理员一般是运维，而我是业务负责人，对着这些资产，不能自由分组命名，一直要去excel表格核对信息，也是头大。
希望如果采纳有上线此功能的话，通知一下，谢谢。

**Comment by ibuler** [comment]
收到，这需要支持用户配置，这在我们计划中

**Comment by tystal** [comment]
> 收到，这需要支持用户配置，这在我们计划中

评估预计多久能上线呢

**Comment by jym503558564** [comment]
已记录，并反馈。请持续关注我们新版本发布～

**Comment by jym503558564** [comment]
问题重复 https://github.com/jumpserver/jumpserver/issues/7247
