### ISSUE TITLE
[Question] Only English language

### ISSUE THREAD

**Issue by beren41** [jumpserver/jumpserver#7206]
**请描述您的问题.**
Hello.  I deployed jumpserver 2.15.4 according to the instructions https://docs.jumpserver.org/zh/master/install/setup_by_fast/. Please tell me how only English is in the web interface? If possible, tell me how )

**Comment by barto95100** [comment]
THe same question

login page is in english but after logged the page is in chinese 

I add the on /opt/jumpserver/config/koko/config.yml : 

LANGUAGE_CODE: en

but nothing, don't work

**Comment by ibuler** [comment]
set default lang to en next version

https://github.com/jumpserver/lina/pull/1190

**Comment by ibuler** [comment]
@barto95100 

config.yml  location should be  /opt/jumpserver/config/config.yml , use env syntax

**Comment by beren41** [comment]
The login page is in Chinese. But if I log in, everything will be in English. Is it possible for the login page to be in English ? ;)

**Comment by xyziven** [comment]
@beren41 It appears EN to me when in the login page when I load the page from Chrome which with English as the default language in browser's setting, though there's couple of Chinese characters.
