### ISSUE TITLE
[Bug] 命令过滤

### ISSUE THREAD

**Issue by ATiRadeon** [jumpserver/jumpserver#7207]
**JumpServer 版本(v1.5.9以下不再支持)**
2.15.3

**浏览器版本**
Chrome95

**Bug 描述**
命令过滤显示拦截成功，但实际命令已生效

**Bug 重现步骤(有截图更好)**
1.  使用SSH登录交换机
![16371178210673864276141_46121847212_B9EB611B-6155-4479-8E79-F5A060E602EE](https://user-images.githubusercontent.com/26919184/142127487-84417e76-1bc6-44ad-b36e-45f0f9a15361.png)

**Comment by jym503558564** [comment]
最新版本未发现该问题，请更新至最新版本测试
