### ISSUE TITLE
0.4.0 py3.6.2 会话历史 播放 按钮 点击无反应

### ISSUE THREAD

**Issue by gxk001** [jumpserver/jumpserver#721]
![image](https://user-images.githubusercontent.com/32119424/30727905-bd2c23b6-9f86-11e7-95d1-1b0e89bebfd6.png)

![image](https://user-images.githubusercontent.com/32119424/30727887-a43ceef8-9f86-11e7-89a8-7ceb1ff2a9ee.png)

![image](https://user-images.githubusercontent.com/32119424/30727861-7f750826-9f86-11e7-973f-ac415a9307a5.png)

jumpserver.log 之前点击播放 后报 dataTables.min.js 404
目录里面是 datatables.min.js 
改完后，还是无法播放。

还需要设置那里吗？

**Comment by hellorocky** [comment]
假按钮, 功能未开发
