### ISSUE TITLE
[Question] 终端离线

### ISSUE THREAD

**Issue by garyj01** [jumpserver/jumpserver#7226]
**请描述您的问题.**
启动jumpserver后，过一会celery和core终端会显示离线，请问要如何处理

![图片](https://user-images.githubusercontent.com/86938259/142395390-e4a7e94a-56d9-41e6-97b6-70210bfd49b2.png)

**Comment by xinsir88** [comment]
有同样问题，求大神帮忙

**Comment by xinsir88** [comment]
我关闭本地防火期和selinux防火墙就在线了。
但是我点web终端 白屏 不知道为什么

**Comment by wojiushixiaobai** [comment]
请使用最新版本

**Comment by denity** [comment]
@wojiushixiaobai   您好，还得请教您一个问题，请指教。

![image](https://user-images.githubusercontent.com/2181344/154958650-dcad27fe-18cb-48e5-986c-6347d51cc3e8.png)

安装了  2.19.0 的版本，还是显示
[Celery]-xxxx
终端已离线: [Celery]-xxx
[Core]-d46017a3440c
终端已离线: [Core]-d46017a3440c

这个健康检查的原理是什么样的？ 需要配置哪里和哪里的联通策略或者检查什么服务状态？？？
谢谢。
