### ISSUE TITLE
web rdp连接服务器上传文件报错[Bug] 

### ISSUE THREAD

**Issue by sevenclockseven** [jumpserver/jumpserver#7240]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
升级到最新2.16，web rdp连接windows主机，上传文件直接报连接异常，文件大小40M，之前上传都是正常的

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/49014592/142559401-7bdff286-7353-4262-b545-49fa29f31faf.png)

2. 
![image](https://user-images.githubusercontent.com/49014592/142559667-704b8b30-d74f-4943-b02c-b31d6293c92e.png)

3.

**Comment by jym503558564** [comment]
该问题还存在吗

**Comment by sevenclockseven** [comment]
最近没有再出现

在 2022-02-08 16:42:03，"八千流" ***@***.***> 写道：


该问题还存在吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jym503558564** [comment]
好的，如还有问题，可再次向我们提issues。
