### ISSUE TITLE
[Question] 我们后期会考虑直接对接aws、阿里云、腾讯云等主流云平台嘛！

### ISSUE THREAD

**Issue by lizhen1412** [jumpserver/jumpserver#7242]
**请描述您的问题.**
后期直接通过配置的认证实时同步获取机器，这样减少挨个点击的可能

**Comment by sevenclockseven** [comment]
这是企业版功能吧

**Comment by wml3** [comment]
企业版中支持将云上资产定期同步到堡垒机，支持范围包括主流公有云、私有云平台，详情可到官网咨询，https://jinshuju.net/f/sQ91MK。

**Comment by lizhen1412** [comment]
> 这是企业版功能吧

哈哈，好像是，我好像想要的功能有点多了哈哈

**Comment by lizhen1412** [comment]
> 企业版中支持将云上资产定期同步到堡垒机，支持范围包括主流公有云、私有云平台，详情可到官网咨询，[https://jinshuju.net/f/sQ91MK。](https://jinshuju.net/f/sQ91MK%E3%80%82)

好的，谢谢，您的回答非常有用，谢谢
