### ISSUE TITLE
[Bug] 飞书认证失败，测试提示 app id not exists

### ISSUE THREAD

**Issue by lizhen1412** [jumpserver/jumpserver#7243]
**JumpServer 版本(v1.5.9以下不再支持)**
2.16.0

**浏览器版本**
Chrome 95.0.4638.69

**Bug 描述**
我按照文档，去做飞书认证，飞书开放平台appid 是存在的，JumpServer  提示不存在

![image](https://user-images.githubusercontent.com/29331541/142572388-dc5a84b6-39cd-4f4e-9b4a-ff4f0ff904c0.png)
![image](https://user-images.githubusercontent.com/29331541/142572408-f071528c-8670-427f-bf64-0d8730cf71b3.png)

**Comment by lizhen1412** [comment]
我看过代码，底层写死的url 是飞书的，我们是接的lark,能兼容一下lark 吗？

**Comment by ibuler** [comment]
lark 国际版飞书？

**Comment by ibuler** [comment]
你先修改一下地址，看看有没有完全兼容国际版的，如果可以的话，我们处理一下，内部没有这样的环境

**Comment by lizhen1412** [comment]
> lark 国际版飞书？

对的

**Comment by lizhen1412** [comment]
> 

好的我试下，如果可以的话我给你说下。我明天试下吧！

**Comment by lizhen1412** [comment]
我看了下，对比了下两边文档，好像确实很不太一样。
飞书更友好一点
https://open.feishu.cn/document/tools-and-resources/postman-collection-data-manual#6445d50a
https://open.larksuite.com/document/ukTMukTMukTM/uITNz4iM1MjLyUzM

**Comment by lizhen1412** [comment]
@ibuler  请问我们有排期这个的需求吗?我开始以为是bug 现在看来是需求了

**Comment by ibuler** [comment]
目前没有

**Comment by lizhen1412** [comment]
好的吧！那台遗憾了
