### ISSUE TITLE
[Bug] RDP客户端无法调整颜色，导致登陆24位linux资产时黑屏

### ISSUE THREAD

**Issue by sky84892070** [jumpserver/jumpserver#7245]
**浏览器版本**
chrome

**Bug 描述**
用户采用linux 24位颜色桌面（设计软件调整为24位），使用XRDP+VNC的方式登陆资产。由于企业版RDP客户端默认为32位颜色，在登陆资产后显示为黑屏无法正常使用。
建议可以像全屏和分辨率一样，配置客户端RDP颜色。（用户每次下载RDP文件后，编辑选择颜色，使用起来非常不方便）

**Comment by ibuler** [comment]
v2.16.3 可以设置了
