### ISSUE TITLE
[Bug] 登录时提示需要浏览器设置Cookie，但实际上浏览器已经勾选了「允许所有Cookie」

### ISSUE THREAD

**Issue by Andyguo5891** [jumpserver/jumpserver#7252]
**JumpServer 版本(v1.5.9以下不再支持)**
2.16

**浏览器版本**
chrome 96.0.4664.55

**Bug 描述**
登录时提示需要浏览器设置Cookie，但实际上浏览器已经勾选了「允许所有Cookie」

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/46042812/142980792-d4327991-db22-4965-a435-935a0e9c9112.png)

2.
![image](https://user-images.githubusercontent.com/46042812/142980849-ee2d2cb6-b397-48df-912e-0d8470d357b0.png)

**Comment by wojiushixiaobai** [comment]
直接访问域名，不要带路径 /core/auth/login/
