### ISSUE TITLE
配置用户公钥和系统用户密钥后，在页面上提示已配置密钥

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#7256]
在用户信息中设置了公钥，刷新后看不到该用户是否已经设置了公钥；
在系统用户中设置了密钥，刷新后看不到该系统用户是否已经设置了密钥。
对于密钥的管理有严重影响
![image](https://user-images.githubusercontent.com/89773363/142986731-7bf1e5f9-dfb5-47b0-b552-395504e2af90.png)

**Comment by ibuler** [comment]
收到，想想办法

**Comment by jym503558564** [comment]
系统用户详情页,可查看到ssh指纹。用户暂时没有，已记录，可改进。
