### ISSUE TITLE
[Feature] 关于新功能更新的一些建议

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#7257]
希望在有新功能更新的时候，随附一个简要的操作说明，不然每次更新后要花很长时间找这个功能。不然就是来Issues里面提问，但时效性很差，不能第一时间体验并反馈问题。这对于一个积极的社区用户是一个比较遗憾的事情，希望日后能有改进，感谢你们的努力！！

**Comment by ibuler** [comment]
现在新版本发布后，内部会有 直播，未来计划发布到 B 站
