### ISSUE TITLE
[Bug] 新建资产后会自动分配给所有已有的系统用户、特权用户

### ISSUE THREAD

**Issue by NS-Sp4ce** [jumpserver/jumpserver#7262]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.16.1

**浏览器版本**
Chrome 95.0.4638.69 

**Bug 描述**
新建资产后会自动分配所有已有的系统用户、特权用户

**Bug 重现步骤(有截图更好)**
1.  新建资产
![image](https://user-images.githubusercontent.com/33349032/143186439-6a195f8c-6071-43b9-8908-9fd7bde2f527.png)
2. 查看资产列表对应资产
![image](https://user-images.githubusercontent.com/33349032/143186505-480aed2a-e07c-432e-a402-3dea4426244c.png)

3. 系统用户中已被自动添加该资产
![image](https://user-images.githubusercontent.com/33349032/143186569-8c911114-64d1-49e7-8f45-38614fb80ea2.png)

![image](https://user-images.githubusercontent.com/33349032/143186619-b7f7627a-4d40-4dff-bd45-5920c6f30c3c.png)

**Comment by wojiushixiaobai** [comment]
去检查授权，去掉授权里面的节点

**Comment by NS-Sp4ce** [comment]
> 去检查授权，去掉授权里面的节点

感谢回复，按照要求，已将资产授权中的节点置空并且未添加进授权的资产中
![image](https://user-images.githubusercontent.com/33349032/143227629-5da97f9c-650d-4b18-975d-200d797c7739.png)
![image](https://user-images.githubusercontent.com/33349032/143227737-32906d82-9833-4d3d-bfb3-a9e2d46a9fd8.png)
但是依然新建后自动分配了所有的帐号
![image](https://user-images.githubusercontent.com/33349032/143227807-bbdd8f54-3f6a-462e-a6e0-6b81f31b33e3.png)
![image](https://user-images.githubusercontent.com/33349032/143227847-1a92a02d-4905-4ad0-9a86-d1ebf6d805f0.png)

**Comment by wml3** [comment]
用户和资产的对应关系是在授权规则里产生的，可以查查每一条规则
