### ISSUE TITLE
audits_commandlog表的output输出和audits_recordlog表的output输出有什么区别？

### ISSUE THREAD

**Issue by DHLWDX** [jumpserver/jumpserver#727]
audits_commandlog有一个字段 output，audits_recordlog也有一个字段output，同一个proxy_log_id，二者的输出结果有区别，这是怎么回事？

**Comment by ibuler** [comment]
recordlog 是为了记录录像，只不过还没有上传录像

**Comment by DHLWDX** [comment]
记录录像？是把视频文件上传到这张表中吗？
