### ISSUE TITLE
[Feature] Cookie 不安全设置：Cookie中未配置Secure和HttpOnly参数为True

### ISSUE THREAD

**Issue by coxi-wik** [jumpserver/jumpserver#7283]
**请描述您的需求或者改进建议.**
Cookie 不安全设置：Cookie中未配置Secure和HttpOnly参数为True

**Comment by coxi-wik** [comment]
![image](https://user-images.githubusercontent.com/77430030/143418901-34804dc3-e1d8-4131-9090-19a6f95a1688.png)

在nginx配置文件的location项添加下列参数即可暂时处理
proxy_cookie_path / "/; httponly; secure; SameSite=Lax";

**Comment by ibuler** [comment]
Got it

**Comment by wojiushixiaobai** [comment]
开启设置后，会导致用户无法登录。需要其他解决方案

**Comment by BaiJiangJie** [comment]
v3 新版本可以对 Secure 进行配置，

配置文件修改配置项，SESSION_COOKIE_SECURE=True（[默认为 False](https://github.com/jumpserver/jumpserver/blob/dev/apps/jumpserver/conf.py#L497)）

HttpOnly 参数，[SESSION_COOKIE_HTTPONLY=True](https://docs.djangoproject.com/zh-hans/4.2/ref/settings/#std-setting-SESSION_COOKIE_HTTPONLY)（默认为 True，不允许修改）

**Comment by BaiJiangJie** [comment]
如果开启 SESSION_COOKIE_SECURE=True 后，没有生效，请检查：

1. 当前请求不是通过 HTTPS 连接发起的。如果当前请求是通过 HTTP 连接发起的，Django 会自动将 session cookie 的 secure 属性设置为 False，这是为了避免在非安全连接上出现安全漏洞。

2. 中间代理服务器未正确传递 X-Forwarded-Proto 头。如果你的 Django 项目后面有一层反向代理服务器，你需要确保该代理服务器正确地传递了 X-Forwarded-Proto 头，以告知 Django 当前请求的协议类型。否则，Django 将会认为当前请求是非安全的 HTTP 连接，从而将 session cookie 的 secure 属性设置为 False。

你可以通过在 Nginx 服务器上配置以下代理头来解决该问题：
```
proxy_set_header X-Forwarded-Proto $scheme;
```
如果你使用的是其他反向代理服务器，需要查看该服务器的文档以了解如何正确地传递 X-Forwarded-Proto 头。

3. 浏览器缓存了 session cookie。如果你之前在浏览器中使用过非安全连接，可能会导致浏览器缓存了 session cookie。即使你在 Django 中将 SESSION_COOKIE_SECURE 设置为 True，浏览器也会继续使用之前的非安全连接上的 session cookie。这个问题可以通过清除浏览器缓存来解决。

如果你已经排除了以上问题，但仍然发现 SESSION_COOKIE_SECURE 设置不生效，

请重新打开 Issue。
