### ISSUE TITLE
关闭终端或者输入exit，sshd没有关闭，init.sh脚本没有退出

### ISSUE THREAD

**Issue by hswlxc** [jumpserver/jumpserver#729]
退出ssh，init.sh 仍在运行，内存不能释放

**Comment by gxk001** [comment]
init.sh 没退出，是在哪里看出来的？
我之前也碰到过退出终端或exit ， coco 和服务器之间的sshd socket （这些socket都是由run_server.py 的线程打开）没有关闭。

最后重启的coco，之后在连接，退出，就没有问题，目前还没有重现过。

**Comment by ibuler** [comment]
init.sh是0.3.2的版本。

理论上用户退出了，该init.sh和connect.py会断开
