### ISSUE TITLE
jms负载均衡部署，登录web会话会有卡顿，登录时间较长

### ISSUE THREAD

**Issue by fisholdman** [jumpserver/jumpserver#7291]
**JumpServer 版本(v1.5.9以下不再支持)**
2.15.3

**浏览器版本**
Chrome  96.0.4664.45

**Bug 描述**
web终端登录服务器会有卡顿，会有登录失败的提示。

**Bug 重现步骤(有截图更好)**
1.  进入web终端
2.  点击需要登录的资产
3.  卡顿+登录失败提示，可以成功登录，但是全程需要15秒左右时间。

**Comment by wojiushixiaobai** [comment]
检查架构及资产设置

**Comment by fisholdman** [comment]
> 检查架构及资产设置 比如 ssh 的 USEDNS 开启就会导致连接的时间变长

web会话登录会有失败的提示？貌似是尝试多次，前几次提示失败应该是密码错误导致的，我只有一个系统用户，为何会尝试多次？是哪里配置有问题？系统用户有删除、重复添加的操作。

**Comment by wojiushixiaobai** [comment]
系统用户如果开启了推送会有推送任务执行，检查下

**Comment by fisholdman** [comment]
> 系统用户如果开启了推送会有推送任务执行，检查下

没有开启推送，系统用户我只配置了特权用户，直接使用特权用户登录

**Comment by fisholdman** [comment]
`开始连接到 超级系统用户@192.168.21.2 1.8`
`Last failed login: Tue Dec 21 11:45:51 CST 2021 from 192.168.21.2 on ssh:notty`
`There were 2 failed login attempts since the last successful login.`
`Last login: Tue Dec 21 11:38:26 2021 from 192.168.22.220`
`[root@vm-jumpserver01 ~]$ `

几乎每次都会提示有失败的登录，服务器上也有认证失败的log

**Comment by wojiushixiaobai** [comment]
那应该是哪里配置有误，仔细检查下。

**Comment by fisholdman** [comment]
使用特权用户就有这种现象，普通用户就不会出现，这是为何？

**Comment by ibuler** [comment]
多次尝试应该是会用  密钥和密码去尝试的，先手动在 容器里 ssh 连接一下试试速度
