### ISSUE TITLE
[Question]添加mysql资产的时候，数据库名字必须指定

### ISSUE THREAD

**Issue by xiaohinata** [jumpserver/jumpserver#7293]
** 版本：社区版2.16.1 **

** 问题描述 **
添加mysql资产的时候，提示必须要指定具体的数据库名称，如果需要对整个数据库实例授权，应该避免指定数据库名称，官方文档也是说可以不填，但是我这里报错，社区版2.11的时候也是这样

<img width="504" alt="企业微信截图_08574032-d231-4155-bef8-9f0e3d393695" src="https://user-images.githubusercontent.com/11013971/143544117-4fc86df8-ac0e-40a2-94e2-5a07cf7f45ff.png">

官方文档：
<img width="664" alt="企业微信截图_14b72dd7-befd-4ff1-8619-b8ff4a2cd922" src="https://user-images.githubusercontent.com/11013971/143544527-76e1c751-85ff-44f9-9666-a99deda0b7da.png">

我指定一个默认的mysql数据库就行，然后赋权以后，就是根据指定的系统账号所拥有的数据库权限来展示

**Comment by wojiushixiaobai** [comment]
企业版本里面的一个组件会用到此功能，要求必须指定数据库。

**Comment by ibuler** [comment]
可以写 test 或 Mysql 数据库来
