### ISSUE TITLE
koko lion 数据持久化咨询

### ISSUE THREAD

**Issue by tanzhiliangit** [jumpserver/jumpserver#7297]
我想知道jumpserver 中组件koko 和lion 是否可以以无状态的容器方式运行，如果不可以那么这两个组件在容器中必须要做数据持久化的目录是哪些？

**Comment by wojiushixiaobai** [comment]
你看下需要持久化的目录，比较关键的：
一个是组件认证使用的 key
一个是用户连接资产过程的 录像（会话结束后录像会上传到 Core，上传完毕后会清理掉文件）

持久化目录：
/opt/koko/data
/opt/lion/data

**Comment by tanzhiliangit** [comment]
如果这两个目录(/opt/koko/data
/opt/lion/data)不做持久化，容器删除并重建后会有什么影响，我尝试过删除并重建koko 和lion这两个 k8s pod容器但是并未发现服务异常

**Comment by tanzhiliangit** [comment]
另外请问下你所指的 "组件认证使用的 key" 具体是哪个key文件(相对文件路径)

**Comment by wojiushixiaobai** [comment]
@tanzhiliangit key 就在 data 文件夹里面，不做持久化会导致上传失败的录像在 pod 重建后丢失。
