### ISSUE TITLE
[Question] 请问 API创建新用户的时候是否可以指定默认密码。

### ISSUE THREAD

**Issue by cd06b9** [jumpserver/jumpserver#7299]
**请描述您的问题.**
def create(self):
        print("创建用户 {}".format(self.username))
        url               = '/api/v1/users/users/'
        data              = {
            'name': self.name,
            'username': self.username,
            'email': self.email,
            'is_active': True
        }
        res               = HTTP.post(url, json=data)
        self.id           = res.json().get('id')

    def perform(self):
        self.exist()

# 此处的data 是否可以添加一个默认密码比如： ’pwd‘：’123‘，如何可以请问参数名是什么

**Comment by wojiushixiaobai** [comment]
```json
data = {
    "password_strategy": "custom",
    "name": "张三",
    "username": "zhangsan",
    "email": "zhangsan@local.host",
    "password":"你要设置的密码"
}
```

**Comment by jym503558564** [comment]
自定义密码，需要两个字断："password_strategy": "custom", "password":"你要设置的密码"
