### ISSUE TITLE
[Question] 日志偶发泰文记录

### ISSUE THREAD

**Issue by Laplacence** [jumpserver/jumpserver#7303]
v2.15.3
![Snipaste_2021-11-30_15-29-31](https://user-images.githubusercontent.com/22720300/144004346-39e37536-a767-4205-b75c-342e4773b597.png)
有些日志会出来泰文

**Comment by ibuler** [comment]
@xuxinwen

**Comment by xuxinwen** [comment]
可以留个联系方式吗，到你的环境看一下

**Comment by ibuler** [comment]
问题已找到翻译 Password 导致的
