### ISSUE TITLE
求大神帮忙，web终端白屏

### ISSUE THREAD

**Issue by xinsir88** [jumpserver/jumpserver#7305]
您好，我按照官方文档的源码编译过程，所有组件都成功安装，登录后点web终端白屏转圈，像下面的效果。
![image](https://user-images.githubusercontent.com/44859018/144017101-fd030f93-00d4-4009-87b7-422168d774c0.png)
我nginx的配置如下：
`server {
  listen 80;
  # server_name _;

  client_max_body_size 5000m;

  # Luna 配置
  location /luna/ {
    proxy_pass http://127.0.0.1:4200;
  }

  # Core data 静态资源
  location /media/replay/ {
    add_header Content-Encoding gzip;
    root /opt/jumpserver-2.16.3/data/;
  }

  location /media/ {
    root /opt/jumpserver-2.16.3/data/;
  }

  location /static/ {
    root /opt/jumpserver-2.16.3/data/;
  }

  # KoKo Lion 配置
  location /koko/ {
    proxy_pass       http://127.0.0.1:5000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  # lion 配置
  location /lion/ {
    proxy_pass http://127.0.0.1:8081;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }

  # Core 配置
  location /ws/ {
    proxy_pass http://127.0.0.1:8070;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location /api/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /core/ {
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # 前端 Lina
  location /ui/ {
    proxy_pass http://127.0.0.1:9528;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    rewrite ^/(.*)$ /ui/$1 last;
  }
}`

我本地的4200端口也是开启着的。
`(py3) [root@localhost conf.d]# netstat  -ntpl | grep 4200
tcp        0      0 127.0.0.1:4200          0.0.0.0:*               LISTEN      6244/ng serve       
(py3) [root@localhost conf.d]# `

求大神指导

**Comment by xinsir88** [comment]
所有的终端都是在线状态

**Comment by xinsir88** [comment]
celery和core终端会显示离线

**Comment by wojiushixiaobai** [comment]
编译后用编译好的静态文件，默认情况下需要处理跨域问题
