### ISSUE TITLE
[Bug] vscode连接jumpserver的资产不能审计

### ISSUE THREAD

**Issue by mfanoffice** [jumpserver/jumpserver#7306]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
vscode连接jumpserver的资产，在jumpserver中只能看到登录时间记录，不能产看操作命令，不能进行命令拦截

**Bug 重现步骤(有截图更好)**
1.  ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
2.  vscode中安装shellman，进行命令操作
3.  jump server中没有命令记录，录屏，高危命令拦截等审计

**Comment by JohnsonJo** [comment]
版本v2.12.1也是没法审计。
请问是vscode上来的就是没法审计还是需要升级版本？

**Comment by LeeEirc** [comment]
https://docs.jumpserver.org/zh/master/admin-guide/env/?h=vscode#koko 看文档配置说明，vscode 远程开发走的ssh转发，暂时无法审计。

**Comment by DachuanZhao** [comment]
目前这个问题，有feature支持了嘛？
