### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by mfanoffice** [jumpserver/jumpserver#7307]
**请描述您的问题.**
通过xftp等工具连接到jumpserver，然后往Linux资产中传文件的速度 比 直接往Linux资产传文件的速度慢很多，这是为什么？或者有没有优化这方面的计划？
![image](https://user-images.githubusercontent.com/48307752/144164327-16705689-c64a-42f5-b176-cd1db79fecf1.png)
![image](https://user-images.githubusercontent.com/48307752/144164392-c1270689-a0a4-4db6-8c1e-1b618071233a.png)

**Comment by ibuler** [comment]
@jumpserver/developers  

Eric

**Comment by ibuler** [comment]
因为这个需要server 中转一下，并且涉及到数据流拦截，所以要慢，这个速度是正常的
