### ISSUE TITLE
[Bug]  VScode 登录问题

### ISSUE THREAD

**Issue by npcomet** [jumpserver/jumpserver#7308]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.16.3

**浏览器版本**
Google Chrome
版本 96.0.4664.45（正式版本） （64 位）

**Bug 描述**
按照官方提供的命令
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p222
进行直连不成功，经过反复排查是用户名的问题，我司用户名是jumpserverUsername@jumpserver.org形式的
最后新建不含@字符的用户名测试测试通过

**Bug 重现步骤(有截图更好)**
1.  建立含有@字符的用户
2. ssh 直连 ssh jumpserverUsername@jumpserver.org@systemUsername@AssetIP@jumpserverHostIP -p222
3. 不能连接和匹配资产

**修复建议
1、@字符从右到左匹配
2、或者在建立用户的时候屏蔽@等特殊字符

**Comment by LeeEirc** [comment]
用 `ssh  jumpserverUsername@jumpserver.org#systemUsername#AssetIP@jumpserverHostIP -p2222` 的方式试试

**Comment by npcomet** [comment]
> 用 `ssh jumpserverUsername@jumpserver.org#systemUsername#AssetIP@jumpserverHostIP -p2222` 的方式试试
可以了～
非常感谢

**Comment by npcomet** [comment]
提交之前没有搜索相关问题，建议关闭
https://github.com/jumpserver/jumpserver/issues/6314
