### ISSUE TITLE
[Bug] 推送用户失败

### ISSUE THREAD

**Issue by denjones** [jumpserver/jumpserver#7309]
**JumpServer 版本(v1.5.9以下不再支持)**
2.16.3

**浏览器版本**
Chrome

**Bug 描述**
![image](https://user-images.githubusercontent.com/1130243/144372931-eaad07b2-ab1c-401e-9cc8-11df21cf0ad5.png)
推送用户报错

**Bug 重现步骤(有截图更好)**
1. 点击推送用户
2. 推送失败，如图所示

**Comment by wojiushixiaobai** [comment]
动态用户吗？需要更多的系统用户信息

**Comment by denjones** [comment]
就是普通用户common user，用户信息继承自1.5.X版本数据

**Comment by wojiushixiaobai** [comment]
看起来是参数有问题，方便的话可以发下系统用户的信息。
或者群里喊我远程看下环境

**Comment by denjones** [comment]
不知道要提供什么信息，如果重新创建的系统用户能够推送成功

**Comment by ibuler** [comment]
issue 长时间没有回复，先关闭了，有问题重新打开
