### ISSUE TITLE
jumpserver 如何去连接 aix系统？

### ISSUE THREAD

**Issue by jackieshew2003** [jumpserver/jumpserver#731]
想使用jumpserver连接几台AIX 小型机，每次推送都是失败，也找不到资料，谁能够给提供一下资料呢？

**Comment by ibuler** [comment]
推送用户，是使用ansible完成的，所以应该查看ansible支不支持aix，如果实在不支持，可以单独设置一个系统用户，把手动设置密码，然后模拟推送
