### ISSUE TITLE
连接异常  无法连接到远程桌面服务器（网络不可达 | 安全策略错误）

### ISSUE THREAD

**Issue by linxingchao** [jumpserver/jumpserver#7312]
使用windows-rdp，安全策略配置完好，使用multidesk可以远程，单jumpserver无法远程
![image](https://user-images.githubusercontent.com/18258911/144536587-871e537d-525f-4589-ae24-4d3eb7bb903d.png)

**Comment by wojiushixiaobai** [comment]
系统平台改 windows

**Comment by Jaasdsa** [comment]
这个情况我也遇到了，rdp客户端只能勾选Enable Credential Security Support Provider (CredSSP)才能远程，不勾选则远程不了，但是jumpserver远程不了，相同的报错界面。不是很明白jumpserver远程windows server2016需要哪些环境准备

**Comment by Jaasdsa** [comment]
> 系统平台改窗口



> 系统平台改窗口

这个情况我也遇到了，系统平台改为 windows、windwos2016、windows-RDP、windows-TLS都试过，自定义平台也试过一些。 rdp客户端只能勾选Enable Credential Security Support Provider (CredSSP)才能远程，不勾选则远程不了，该背景下jumpserver远程不了，相同的报错界面。不是很明白jumpserver远程windows server2016需要哪些环境准备
![image](https://user-images.githubusercontent.com/29112372/144561321-c92b4df4-9052-4e5c-83e5-5a4d1184c7a7.png)

**Comment by Jaasdsa** [comment]
我通过【 Disable-WSManCredSSP -Role Server】在windows服务器关闭CredSSP功能，RDP客户端已经能正常远程了，jumpserver还是提示【网络不可达|安全策略错误】
![image](https://user-images.githubusercontent.com/29112372/144569866-aa4bed99-bf00-40f2-ba4f-90c3dfd3159d.png)

**Comment by Jaasdsa** [comment]
jumpserver环境： CentOS Linux release 8.5.2111 / jumpserver 2.16.3
目标客户端：windows server datacenter 2016
需求：远程错误时报错信息需要具体，并能够反馈给前端

**Comment by Jaasdsa** [comment]
已经解决了，由于我在公司路由器上面开启禁止二级路由功能，导致jumpserver物理机能上网，但容器不能上网。从而引发的连环血案。解决掉网络故障后，进入容器保证网络通常即可
![image](https://user-images.githubusercontent.com/29112372/144995157-aa78a973-99ad-4ec8-96f2-a2c575509815.png)

**Comment by dongfo** [comment]
同等条件下Windows sever 2008可以，2016不可以。提示：连接异常 无法连接到远程桌面服务器（网络不可达 | 安全策略错误
