### ISSUE TITLE
[Bug] /assets/assets/{id} DELETE无法删除机器

### ISSUE THREAD

**Issue by caibaofei** [jumpserver/jumpserver#7316]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer2.16.3

**浏览器版本**

**Bug 描述**
使用jumpserverapi提供的接口删除机器，报错{"detail":"身份认证信息未提供。","code":"not_authenticated"}

**Bug 重现步骤(有截图更好)**
1. api接口提供的文档
![image](https://user-images.githubusercontent.com/38309951/144576335-dad55838-1fbc-4e0e-b374-4ed3f52d6f65.png)

2.使用后报错信息 
![image](https://user-images.githubusercontent.com/38309951/144575988-970091e5-db88-4181-a921-5e4e397226ef.png)

**Comment by wojiushixiaobai** [comment]
未提供有效的身份验证。
请参考 [API 认证](https://docs.jumpserver.org/zh/master/dev/rest_api/#api_2)
