### ISSUE TITLE
[Bug] Ger是不是 Get呀，改一改，koko log 里的

### ISSUE THREAD

**Issue by rayPan2333** [jumpserver/jumpserver#7317]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.16.3

**Bug 描述**
koko/pkg/handler/asset.go  line 20
logger.Errorf("Ger user perm assets failed: %s", err.Error())

Ger是不是 Get呀

**Comment by LeeEirc** [comment]
感谢你的反馈，已经修正错误 #https://github.com/jumpserver/koko/pull/754 
如遇类似的拼写错误，可直接提交 pr，帮助我们改进完善。
