### ISSUE TITLE
jumpserver3.0新建用户时，如果勾选了发送邮件会持续卡顿

### ISSUE THREAD

**Issue by chenhnty** [jumpserver/jumpserver#732]
如果不勾选发送邮件，则可以立刻跳转到用户列表。
且创建成功的用户，不会收到有用户密钥信息的邮件。

**Comment by ibuler** [comment]
是的，发送邮件会调用smtp服务器同步的发送，所以会卡顿一会儿

**Comment by chenhnty** [comment]
但是我现在遇到情况是，创建用户勾选了发送邮件，会一直卡顿，添加的收件箱也无法收到邮件。但是最初添加的smtp服务器发的测试邮件可以收到。

**Comment by imocat** [comment]
新建用户是，卡顿的时间很长
无奈之下只能重启jumpserver （ service.sh restart)
建议使用异步队列，或使用其他其他邮件服务
