### ISSUE TITLE
运行多个koko节点会导致sftp无法正常使用

### ISSUE THREAD

**Issue by tanzhiliangit** [jumpserver/jumpserver#7321]
**请描述您的问题.**

当我在jumpserver 部署多个koko节点时候会导致sftp无法正常使用，无法正常使用的原因大概就是因为轮询方式请求不同的koko服务，导致session变化导致的，想知道针对这个问题有没有好的建议。
![image](https://user-images.githubusercontent.com/43702137/144704583-7b0c05dd-eb9f-480c-978e-8d1b3dd23c45.png)

**Comment by wojiushixiaobai** [comment]
config.txt 配置文件添加下面参数
- 参考 https://docs.jumpserver.org/zh/master/install/setup_by_lb/

# KoKo Lion 配置
SHARE_ROOM_TYPE=redis                                            # KoKo Lion 使用 redis 共享
