### ISSUE TITLE
API /api/v1/assets/nodes/ 无法使用full_value创建资产节点

### ISSUE THREAD

**Issue by tanzhiliangit** [jumpserver/jumpserver#7322]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.16.1

**浏览器版本**

**Bug 描述**
调用 api /api/v1/assets/nodes/  post  {"value": "test100" }他会在顶层下创建一个资产节点（例如：/Default/test100），然后我想通过传{"full_value": "/Default/test100/test10000"}去创建一个我想要的资产节点(/Default/test100/test10000)，可是他并没有达到预期而是创建了一个 '/Default/没有名字' 的资产节点

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/43702137/144744266-32e536f4-de53-4a54-b25a-9e51fe87f19e.png)
![image](https://user-images.githubusercontent.com/43702137/144744292-a1808702-aba0-470f-a21b-02aa49606295.png)

**Comment by ibuler** [comment]
目前 api 还不能根据 full value 来创建，我们记录到内部了，到时支持一下，现在只能通过父节点去创建子节点，具体可以F12，查看 页面的 api 请求过程 

```
POST HOST/api/vi/assets/nodes/4cd47f4a-e1eb-447c-91db-ca21429a0abf/children/

{
   "value": “TestNode"
}
```

**Comment by ibuler** [comment]
已排期，暂时关闭了，等待版本发布
