### ISSUE TITLE
Windows 平台使用 VSCode 的 Remote SSH 功能在 Linux 上进行远程调试

### ISSUE THREAD

**Issue by qqqqqee** [jumpserver/jumpserver#7324]
**请描述您的问题.**
 想要在windows 平台远程debug服务器上的jumpserver ，应该怎么配置呢，可以通过debug启动服务，但是服务起来之后进不去断点，请指教

**Comment by ibuler** [comment]
不太理解，JumpServer 不支持部署在 Windows上，仅支持 macOS 和 Linux

**Comment by qqqqqee** [comment]
嗯，这个我知道，我的jumpserver 是部署到了centos7 上，我想在windows上远程debug 看一下代码 ，在vscode上调试cenos7上运行的代码，这样是否可行？

**Comment by ibuler** [comment]
这个可以的

**Comment by qqqqqee** [comment]
我配了Remote SSH 和 lanch.json 但是在浏览器里访问某些功能，在vscode里面进不去断点，
![image](https://user-images.githubusercontent.com/33541564/144780199-894b7699-104f-487e-a643-b6786bc0d4a0.png)
不知道有什么问题，请指教一下

**Comment by ibuler** [comment]
这就超出的的知识范围了，对 vscode 不是很熟悉，我是 idea 的拥护者

**Comment by qqqqqee** [comment]
我也用idea ，我看官网推荐使用vscode
![image](https://user-images.githubusercontent.com/33541564/144781711-af3c4378-6722-4764-902f-fa4db934e65a.png)

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
断点问题很多IDE都有，这个可能没法提供啥帮助

**Comment by LeeEirc** [comment]
![image](https://user-images.githubusercontent.com/32626707/145366800-235b3d2d-6607-4eae-be99-c392267b7cf2.png)

试试这个启动配置

**Comment by qqqqqee** [comment]
好的，谢谢，我试一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 下午5:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] Windows 平台使用 VSCode 的 Remote SSH 功能在 Linux 上进行远程调试 (Issue #7324)





 

 
试试这个启动配置
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ibuler** [comment]
长时间没有收到回复，暂时关闭 issue，有问题请重新打开
