### ISSUE TITLE
[Question] 请问通过 SSH 工具直连资产， 支持 JetBrains 公司的 intelliJ IDEA 等 IDE 吗？

### ISSUE THREAD

**Issue by xuyang2** [jumpserver/jumpserver#7325]
请问通过 SSH 工具直连资产， 支持 intelliJ IDEA 的 Deployment 的 SFTP 配置吗？

AssetIP 为唯一资产，
命令行 `ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p 2222` 直连 AssetIP 正常

在 IDEA 中用下图的配置，执行 Deployment 上传时，IDEA 报错：
`Upload to ****** failed. please select one of the assets`

![image](https://user-images.githubusercontent.com/6643001/144785827-dda79fe6-8d8d-4145-badb-98b453864eb0.png)

- https://blog.fit2cloud.com/?p=2267
- https://www.jetbrains.com/help/idea/creating-a-remote-server-configuration.html

**Comment by LeeEirc** [comment]
从日志上看，这个授权的并不是唯一的资产 ip

**Comment by ibuler** [comment]
长时间没有收到回复，有问题请重新打开

**Comment by notionev** [comment]
请问问题解决了吗？

**Comment by xuyang2** [comment]
> 请问问题解决了吗？

没解决。好在管理员暂时还没禁用 rz sz 😂
