### ISSUE TITLE
开源项目jumpserver django3.1.31启动，找不到静态文件

### ISSUE THREAD

**Issue by g37502** [jumpserver/jumpserver#7326]
启动命令:
3  /opt/py3/bin/python3 -u /opt/jumpserver-master/apps/manage.py runserver :8000
setting配置如下：
STATIC_URL = '{}/static/'.format(CONFIG.FORCE_SCRIPT_NAME)
STATIC_ROOT = os.path.join(PROJECT_DIR, "data", "static")
STATIC_DIR = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = ( os.path.join(BASE_DIR, "static"),)
templates配置如下
{% load static %} 
<link href="{% static "css/jumpserver.css" %}" rel="stylesheet"> 
<script src="{% static "js/jumpserver.js" %}"></script>
找不到静态文件：
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from 'http://**.**.**.**:8000/static/css/bootstrap.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by wojiushixiaobai** [comment]
开发请参考 [编译文档](https://docs.jumpserver.org/zh/master/dev/build/)
