### ISSUE TITLE
无法在互联网环境下远程使用服务器

### ISSUE THREAD

**Issue by cloudhy** [jumpserver/jumpserver#7327]
**请描述您的问题.**
jumpserver 部署在公司环境，web端已经映射到互联网。在公司环境下，可以正常访问web界面，登录并且远程服务器。在其他环境，可以正常登陆jumpserver，看到我的资产列表，但是无法在web端远程任何服务器，包含windows以及linux

**Comment by wojiushixiaobai** [comment]
请按照要求正确处理 websocket
https://docs.jumpserver.org/zh/master/admin-guide/proxy/
