### ISSUE TITLE
ssh key过期怎么处理

### ISSUE THREAD

**Issue by brucefanhaitao** [jumpserver/jumpserver#733]
安装完0.4.0版本之后，界面上提示SSH key已经过期，怎么处理

![default](https://user-images.githubusercontent.com/29652825/30905004-2c4fc432-a3a6-11e7-9e1c-48779d061d06.png)

**Comment by ibuler** [comment]
其实这个或许不是过期，而是你没有设置key，点击设置，上传自己的key公钥

**Comment by ibuler** [comment]
fixed  688a836bbed33c30793f55fe0b4a6221744f65c0

**Comment by brucefanhaitao** [comment]
是在jumpserver上生成秘钥，然后把公钥拷进去吗
![default](https://user-images.githubusercontent.com/29652825/30944022-cb4c06e6-a427-11e7-84f1-6e283b76312c.png)
