### ISSUE TITLE
[Feature] 能否把ssh登录界面的其他入口都去除？

### ISSUE THREAD

**Issue by asskss** [jumpserver/jumpserver#7333]
![da6001a33ce593b47f69ebef192aee8](https://user-images.githubusercontent.com/55012560/144961987-b90b0f85-2cd0-488f-9b1a-44e073480ddb.png)

**Comment by asskss** [comment]
去除其他入口，只留下k8s的入口

**Comment by ibuler** [comment]
并不能，需要自己开发
