### ISSUE TITLE
管理用户与系统用户究竟是什么鬼

### ISSUE THREAD

**Issue by brucefanhaitao** [jumpserver/jumpserver#734]
谁能介绍一下这俩用户究竟是什么鬼

![default](https://user-images.githubusercontent.com/29652825/30906595-eb9db016-a3aa-11e7-8b3f-0476b201c87a.png)

**Comment by chenhnty** [comment]
管理用户是你添加的服务里存在的用户，如root；系统用户是用管理用户在服务器上创建的用户

**Comment by ibuler** [comment]
conflict with #718

**Comment by brucefanhaitao** [comment]
您这说的服务是什么意思呢，服务是不是指资产服务器；（1）如果是的话，那么管理用户就是资产服务器上的用户，如：root，拥有all sudo权限；（2）系统用户就是资产服务器上的root用户在资产服务商创建的普通用户呢？

**Comment by hellorocky** [comment]
是

**Comment by fanlc** [comment]
jumpserver 用户,系统用户和管理用户 普通用户和特权用户 区别：
https://www.cnblogs.com/fanfanfanlichun/p/15060625.html
