### ISSUE TITLE
[Bug] 没有设置 mfa 情况下，koko 登陆会报错

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#7344]
**请描述您的需求或者改进建议.**

![image](https://user-images.githubusercontent.com/17382885/145348785-d8a1396e-963b-4710-8e98-e6ddca117ab7.png)

**Comment by youliyuan-fit2cloud** [comment]
test

**Comment by ibuler** [comment]
已修复

**Comment by youliyuan-fit2cloud** [comment]
test

**Comment by ibuler** [comment]
好的
