### ISSUE TITLE
[0.4.0] 系统用户新增级别属性，用户登录等默认用最高级别登录

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#735]
使用版本  0.4.0

现在当用户授权多个系统用户时，用户必须手动去选择使用哪个系统用户登陆，这显然在使用体验是有问题的，所以系统用户增加一个 级别的属性，如果授权了多个，则使用最高级别的登陆，当然，如果级别一样，则提示用户选一个

**Comment by huangzx** [comment]
good job

**Comment by ibuler** [comment]
解决
