### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by linyaohong** [jumpserver/jumpserver#7356]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
google

**Bug 描述**
为当前系统用户关联数量
![image](https://user-images.githubusercontent.com/48407246/145416900-ab37c52e-b9fa-4c61-9862-21b1de56250f.png)
当我添加了一个授权规则
![image](https://user-images.githubusercontent.com/48407246/145417105-4a64d316-ddf7-490c-b459-38d31c12360b.png)
这个系统用户如下，理论上是正确的
![image](https://user-images.githubusercontent.com/48407246/145417263-6343e9cf-cc73-4e1b-a68a-a9254d49a9bb.png)
当我把授权去掉以后
![image](https://user-images.githubusercontent.com/48407246/145418983-19d8d712-b410-4301-9cf1-525050f4ac48.png)

理论上蓝色方块内的数字应该变成 1 因为目前已经只有一个授权关联了此账号
![image](https://user-images.githubusercontent.com/48407246/145419158-b62df2f0-a717-418d-9024-662f1ed93076.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
单向的，授权会让系统用户和资产自动关联，取消授权不会取消关联
