### ISSUE TITLE
[Bug]  jumpserver 无法自动推送系统用户

### ISSUE THREAD

**Issue by shaojiechao** [jumpserver/jumpserver#7358]
**jumpserver版本：** 2.16.1

**问题描述：**

根据官方文档容器化部署jumpserver，在创建资产之后，jumpserver无法自动推送系统用户（通过以下截图可以看到改系统用户是可以识别到所创建的资产，以及已经开启了自动推送功能），手动推送是没有任何问题的
![image](https://user-images.githubusercontent.com/95906788/145540279-6c3e01b8-66c7-4772-b92d-676dc64bd906.png)
![image](https://user-images.githubusercontent.com/95906788/145540611-68f63b8a-db8b-47c5-8c4b-7e68916be0ce.png)

经过测试，在资产授权中，如果“资产”选择“节点”的话，就无法自动推送系统用户
![image](https://user-images.githubusercontent.com/95906788/145540536-889a470b-756e-47ce-b61c-a5cf7af475fd.png)

如果在“资产”中去选择所创建的资产，那么就可以自动推送系统用户，但是这样做的话，每次新创建节点，就要在资产授权中手动增加一次
![image](https://user-images.githubusercontent.com/95906788/145541147-7a947db7-9f59-4293-8d97-519910bd7e0e.png)

之前用的1.5.6-2版本，在资产授权中选择“节点”就可以自动推送用户
![image](https://user-images.githubusercontent.com/95906788/145541467-121fbfd9-9a22-474c-8db1-aebf1bea8cd8.png)

**Comment by shaojiechao** [comment]
hello，请问这个问题什么时候可以帮我看看类

**Comment by wojiushixiaobai** [comment]
已修复，等待版本更新。

**Comment by shaojiechao** [comment]
好的，该问题在哪个版本会修复，麻烦到时候告知一下哈

**Comment by wojiushixiaobai** [comment]
@shaojiechao 昨天发布的版本 v2.17.0 可以测试验证下
