### ISSUE TITLE
在jumpserver平台上创建用户的时候不发送邮件

### ISSUE THREAD

**Issue by brucefanhaitao** [jumpserver/jumpserver#736]
是不是下面的EMAIL_HOST得修改成自己的邮箱啊
![default](https://user-images.githubusercontent.com/29652825/30945801-d9f16de8-a432-11e7-812d-817e8370ffdf.png)

**Comment by ibuler** [comment]
是的

**Comment by brucefanhaitao** [comment]
我把这个位置改成自己的邮箱了，创建用户的时候也没有发邮件啊

**Comment by wocswang** [comment]
我都修改了然后也没有发送邮件，报错了

**Comment by brucefanhaitao** [comment]
4.0版本存在这个问题，我改用3.2版本了，3.2的更加稳定些，建议使用3.2
