### ISSUE TITLE
连接windows主机报 aborted see logs错误

### ISSUE THREAD

**Issue by szljh** [jumpserver/jumpserver#7366]
**请描述您的问题.**
![logs](https://user-images.githubusercontent.com/4980540/145743583-5fa6fbe9-86c8-457d-a7d4-7fe66d471c40.png)

**Comment by wojiushixiaobai** [comment]
查看 lion 日志
docker logs -f jms_lion --tail 200

**Comment by szljh** [comment]
![企业微信截图_16393657602780](https://user-images.githubusercontent.com/4980540/145747444-be906e43-bb76-4b0e-bbd4-53b355457ac9.png)
logs之前就查过，不知道问题点在那边，就是连接到服务器就中断了，关键堡垒机中其它主机连接是正常的。打扰！

**Comment by LeeEirc** [comment]
看以 guacd 开头的异常日志。

**Comment by h77626592** [comment]
遇到相同的报错了

windows服务器上传文件后，把文件从Guacamole RDP中复制到本地磁盘发生的问题，这个怎么解决?

**Comment by sevenclockseven** [comment]
我也是相同的报错

windows服务器上传文件后，把文件从Guacamole RDP中复制到本地磁盘时报错，猜测可能跟部署服务器带宽有关

**Comment by wojiushixiaobai** [comment]
说明版本号

**Comment by h77626592** [comment]
最新社区版  Version v2.17.0 GPLv2.

**Comment by h77626592** [comment]
> 我也是相同的报错
> 
> windows服务器上传文件后，把文件从Guacamole RDP中复制到本地磁盘时报错，猜测可能跟部署服务器带宽有关

一个10M左右的文件不至于吧  -_-!!

**Comment by sevenclockseven** [comment]
@h77626592 升级到v2.17.1有所改善，猜测跟带宽有关是因为我把服务器上占用带宽多的应用关了，报错情况有所好转

**Comment by tzm1921995** [comment]
不得不降回1.14版本，我怀疑是文件上传审计那块功能引起的

**Comment by shuboGe** [comment]
我也遇到这个问题 我是2.19 你们都解决了吗？

**Comment by Satan023** [comment]
v3.3.1，一样问题
`2023-06-13 09:50:56 tunnel conn.go [ERROR] Session[68019990-35b2-44a5-9b68-788890b5c97e] receive web client disconnect opcode
2023-06-13 09:50:56 tunnel conn.go [ERROR] Session[68019990-35b2-44a5-9b68-788890b5c97e] web client read err: websocket: close 1005 (no status)
2023-06-13 09:50:56 tunnel conn.go [ERROR] Session[68019990-35b2-44a5-9b68-788890b5c97e] send web client err: websocket: close sent
2023-06-13 09:50:56 session server.go [ERROR] 录像存储设置为 null，无存储
`

**Comment by taoshanghu** [comment]
我也遇到一样的问题，最终判断是windows系统 远程问题，我换成windows远程桌面还是链接不上，提示协议异常，重启windows系统后恢复正常
