### ISSUE TITLE
[Feature] 能否支持VNC传送文件？

### ISSUE THREAD

**Issue by Azreulo** [jumpserver/jumpserver#7368]
服务端使用的是RealVNC，原生VNCViewer是可以传送文件的，但是堡垒机的VNC不支持，这很不方便。
因为环境限制RDP协议不能使用，So~~~

麻烦能增加这个功能。Thanks~

**Comment by ibuler** [comment]
RealVNC 是商业的 VNC Server，上传下载文件是其私有协议，tigervnc 等均不支持
