### ISSUE TITLE
感觉终端展示有点问题

### ISSUE THREAD

**Issue by brucefanhaitao** [jumpserver/jumpserver#737]
我加了两台资产设备，在两台机器上分别创建了tom和openstack系统用户，也在jumpserver的web界面上增加了如下的一条授权规则（图2），但是终端处会显示两个用户呢（图1）；也试了一下分开创建两条规则，但结果还是图1那样
![default](https://user-images.githubusercontent.com/29652825/30948277-53fb567c-a441-11e7-86e1-58a597751553.png)

![default](https://user-images.githubusercontent.com/29652825/30948308-94eb23ba-a441-11e7-8df6-b27825537a61.png)

**Comment by brucefanhaitao** [comment]
是不是两台设备的系统用户名不一样的话，然后同时授权给同一个用户，在这个用户下就能看到有两个系统用户呢

**Comment by hellorocky** [comment]
第一个图片中的用户是第二个图片中的System users

**Comment by brucefanhaitao** [comment]
恩，了解了，谢谢
