### ISSUE TITLE
[Feature] 可否加入双因子认证白名单网段功能

### ISSUE THREAD

**Issue by HolyGu** [jumpserver/jumpserver#7374]
希望可以在后台增加一个自定义白名单网段功能，例如在白名单内设置10.10.0.0/16，那么这个IP段内的用户去使用堡垒机的时候，无需双因子认证，在非白名单内的网段如172.16.0.0/16或互联网访问到堡垒机的时候，登录需要双因子认证

**Comment by ibuler** [comment]
暂无计划
