### ISSUE TITLE
测试资产连通性一直失败[Bug] 

### ISSUE THREAD

**Issue by flapjackegg** [jumpserver/jumpserver#7379]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.16.3 GPLv2.

**浏览器版本**
Chrome 96.0.4664.55

**Bug 描述**
添加资产以后，只有测试资产连通性一直失败，其他更新资产信息、推送用户等其他任务都没有问题

**Bug 重现步骤(有截图更好)**
1. 我们不允许 root 用户直连，特权用户使用的是具有 sudo 权限 NOPASSWD: ALL 的用户
2. 添加资产以后，测试资产连通性一直失败，手动测试也失败，但是更新资产信息、推送用户等其他任务都没有问题

报错截图：

![image](https://user-images.githubusercontent.com/33110052/145961396-868ceea6-4076-4554-a726-6e3c7d91a0b6.png)

**Comment by flapjackegg** [comment]
我找了一台测试机，特权用户用 root 是没有问题的，但是换成有 sudo 权限的非 root 用户就不行

**Comment by ibuler** [comment]
不行，需要特权用户
