### ISSUE TITLE
[Bug] web终端连接时使用的特权用户不匹配

### ISSUE THREAD

**Issue by lrx0014** [jumpserver/jumpserver#7388]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.16.3

**浏览器版本**
Chromium Edge 

**Bug 描述**
创建了两个特权账号，分别对应两台机器
特权用户ssh-privileged-tx-sh-01对应一台公有云机器
特权用户ssh-root-ssh-jumper对应一台内网机器(localhost)

按理说，通过web终端连接内网机器的时候，应该使用的是特权用户ssh-root-ssh-jumper，但连接的时候用的却是ssh-privileged-tx-sh-01，导致连接失败，并且ssh-privileged-tx-sh-01与内网机器并没有关联

好像只有web终端有问题，硬件信息和连通性都是正常获取到了

**Bug 重现步骤(有截图更好)**
1、两个特权用户各自对应一台机器
![image](https://user-images.githubusercontent.com/13842428/145985606-f78db743-84a3-4ed5-bab8-ec151ccba8b7.png)

2、内网机器只分配了ssh-root-ssh-jumper
![image](https://user-images.githubusercontent.com/13842428/145985754-e505a4f9-703d-444b-b13d-a9208b9755d2.png)

3、但是连接内网机器的时候却是用的公有云的特权账号
![image](https://user-images.githubusercontent.com/13842428/145985857-9871c269-006a-4bfc-9f31-20a55767efa6.png)

**Comment by lrx0014** [comment]
补充一点，刚开始的时候不小心把两个特权用户都分配到了localhost资产下，然后后面从localhost下删除了公有云的用户绑定，web终端似乎还是能读取到公有云的用户

**Comment by wojiushixiaobai** [comment]
授权错误而非bug
