### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sageonedream** [jumpserver/jumpserver#7393]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.15.3

**浏览器版本**
googel 96.0.4664.93

**Bug 描述**
点击进入功能页面(比如创建用户页面)时，没有返回按钮，用户体验下不友好，建议优化

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/92150453/146129628-c625fc6c-14e2-4337-8ed6-bb8f2071ddd2.png)

**Comment by ibuler** [comment]
浏览器返回吧
