### ISSUE TITLE
Windows资产web终端频繁连接异常出现

### ISSUE THREAD

**Issue by watson6** [jumpserver/jumpserver#7405]
## 部署环境
install-2.16.3 版本在一台虚拟机拉起服务。MySQL和redis是使用外部集群。

## 下面是windows资产的配置方式，无论是切换windows 还是windows2016 情况都是一样
![image](https://user-images.githubusercontent.com/10827194/146292650-e0fe7a3e-da32-427b-a4a4-88ff5f409868.png)

## 出现异常的情况是如下
出现异常的情况非常高频，需要至少重复打开四次以上才能连接成功。连接到远程桌面之后，关闭窗口。重新再次连接，依旧提示 【连接异常】只能关闭整个web终端页面，重复打开几次提示连接异常才能正常打开远程桌面。
![image](https://user-images.githubusercontent.com/10827194/146293030-3d4db7f6-b5bc-45c2-a729-3d0d0c4c39e2.png)

##具体连接异常之后，日志的体现
```
2021-12-16 01:29:37 tunnel server.go [ERROR] No session found
[GIN] 2021/12/16 - 01:29:37 | 200 |   38.917257ms |   172.17.146.60 | GET      "/lion/ws/connect/?SESSION_ID=567457c3-9815-4daf-9f67-36598c7f605b&GUAC_WIDTH=1504&GUAC_HEIGHT=915&GUAC_DPI=96&GUAC_IMAGE=image%2Fjpeg&GUAC_IMAGE=image%2Fpng&GUAC_IMAGE=image%2Fwebp&GUAC_AUDIO=audio%2FL8&GUAC_AUDIO=audio%2FL16"
```

**Comment by wojiushixiaobai** [comment]
群里面已经解释过，除非提交更详细的内容，否则不受理

**Comment by watson6** [comment]
感谢响应，群里面的确回应过了，但是提供的信息【网络问题或者被WAF拦截】给到我们，没啥思路排查下去。因为WAF已经确认是没有这个环节，网络问题有什么具体方向课参考么？麻烦指导下。下面我重新提供一些信息来说明


我们jumpserver节点，通过installer-v2.16.3 docker-compose 拉起服务。
前面再通过F5代理来访问jumpsever，在F5层有增加的对应的websocket信息。简要说是F5 访问了后端虚拟机docker-proxy 映射出来的8081 端口直达lion应用里面。
    proxy_set_header Upgrade websocket;
    proxy_set_header Connection "upgrade";

下面这个是连接失败的请求header情况了。
![image](https://user-images.githubusercontent.com/10827194/146346269-1f7ac454-7f46-441f-897b-70344de78aad.png)
下面是重连多只之后，成功连接到远程桌面的请求hearder情况
![image](https://user-images.githubusercontent.com/10827194/146346795-15bdbac8-6ee0-4d47-b371-2556863d420b.png)

可见他们是差异不大的。
中间存在的丢失情况，也不清楚。麻烦说明下这个建立连接是怎样的过程？ 需要在header里面里面增加什么参数，或缺失去了什么

**Comment by wojiushixiaobai** [comment]
正常情况不需要单独对 lion 组件进行设置，应该设置 jumpserver 最终的出口地址即可。
默认是 80 443.
可以参考 nginx 反向代理的相关内容
