### ISSUE TITLE
[Bug] web终端 视图 全屏显示不可用

### ISSUE THREAD

**Issue by fisholdman** [jumpserver/jumpserver#7419]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.17.0

**浏览器版本**
Chrome 已是最新版本
版本 96.0.4664.110（正式版本） （64 位）

**Bug 描述**
web终端 视图 全屏显示不可用，点不动，点了没反应

**Bug 重现步骤(有截图更好)**
1.  web终端 视图 
2.  点击全屏显示
3.  无反应

**Comment by ibuler** [comment]
这个是指的连接的某个资产，然后全屏，首先要连接上资产
