### ISSUE TITLE
[Question] 同网段下资产无法访问

### ISSUE THREAD

**Issue by alhakb** [jumpserver/jumpserver#7421]
jumpserver部署的服务器与资产服务器处于同一网段下，jumpserver是arm64应用，资产是x86应用，在链接时一直提示以下内容：

开始连接到 ${资产名}-${用户名}@IP14.9
开始连接到 ${资产名}-${用户名}@IP error: 网络不通（连接超时）
Receive Connection closed

这个问题是由于架构导致的吗，我用x86部署jumpserver时，x86资产和arm资产都可以正常连接

**Comment by wojiushixiaobai** [comment]
与架构无关，检查网络。
或者重启 docker，再重启 jumpserver
```
jmsctl down
systemctl restart docker
jmsctl start
```
