### ISSUE TITLE
[Bug] 云管中心同步 BUG

### ISSUE THREAD

**Issue by wisonic-s** [jumpserver/jumpserver#7426]
**JumpServer 版本(v1.5.9以下不再支持)**
2.17.0

**浏览器版本**
Chrome 93.0.4577.82

**Bug 描述**
云管中心同时启动两个节点为根节点的同步任务，会出现死锁，无法取消任务，此时无法资产树那边无法在根节点下添加子节点。

**Bug 重现步骤(有截图更好)**
1.  云管中心创建两个节点为根节点的同步任务。
2. 同时执行同步任务。

**Comment by BaiJiangJie** [comment]
单个任务执行，也不可以取消任务；
根节点下创建子节点，需要等任务同步结束之后。
