### ISSUE TITLE
[Question] 使用allinone的方式升级到v2.17.0后Core和Celery两个终端离线

### ISSUE THREAD

**Issue by wanglong168** [jumpserver/jumpserver#7428]
**请描述您的问题.**
使用allinone的方式升级到v2.17.0后Core和Celery两个终端刚启动的时候是正常的 过会就离线了
我发现Core和Celery的远端地址和KoKo和Lion的远端地址不一样 正常的远端地址是127.0.0.1 不正常的是容器的IP

**Comment by wojiushixiaobai** [comment]
忽略
