### ISSUE TITLE
防火墙问题

### ISSUE THREAD

**Issue by xiaoxiao789** [jumpserver/jumpserver#743]
[简述你的问题]
默认安装完成后，防火墙是关闭的，如果开启防火墙，需要开启哪些端口，有没有人指点一下啊，谢谢
##### 使用版本
[使用的Jumpserver版本 0.3.2 ]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

**Comment by ibuler** [comment]
ssh端口 22  http端口 8080  如果使用nginx还有80
