### ISSUE TITLE
[Bug] 文件管理鼠标拖动可选到".."目录

### ISSUE THREAD

**Issue by Phyzait** [jumpserver/jumpserver#7434]
**JumpServer 版本(v1.5.9以下不再支持)**
2.17.0

**浏览器版本**
Chrome 96.0.4664.93（正式版本） (arm64)

**Bug 描述**
文件管理鼠标拖动全选时".."目录可被同时选择，非常容易误操作。
Command+A全选时不会选中".."目录。
鼠标操作全选删除会导致上级目录同时被删除。

**Bug 重现步骤(有截图更好)**
1.  进入任意子目录
2. 鼠标拖动全选所有文件及文件夹（从底拉到头，包括".."）
3. 删除

**Comment by ibuler** [comment]
没有遇到改问题， .. 目录是无法被鼠标框选中的，附一个图吧

**Comment by Phyzait** [comment]
> 没有遇到改问题， .. 目录是无法被鼠标框选中的，附一个图吧

![image](https://user-images.githubusercontent.com/7850266/148005604-2f64c558-9020-4ea4-97d1-4325ed5cb01a.png)
如图，列表中共11个文件/文件夹，鼠标拖动进行全选，同时选中了".."目录

**Comment by LeeEirc** [comment]
测试了下，鼠标选择是可以选择 .. 上一级目录，这种全选删除，就使用command + A 快捷键吧。

**Comment by ibuler** [comment]
收到，先记录一下，先搁置吧，可能不太好单独处理
