### ISSUE TITLE
[Question] redis如何选择其它db库

### ISSUE THREAD

**Issue by dongye2738** [jumpserver/jumpserver#7437]
* jumpserver的redis环境变量只看到redis的host与密码，没有看到如何选择用哪个库的变量，请问我如果不想用0库可以选择其它库吗？在docker的env下如何配置？

**Comment by wojiushixiaobai** [comment]
[参数列表](https://steamcommunity.com/app/1426490/discussions/)

**Comment by dongye2738** [comment]
@wojiushixiaobai 链接怎么是steam的？

**Comment by hellyhe** [comment]
配置缺少 db0 配置项
