### ISSUE TITLE
[Bug] 默认shell为Fish shell时无法通过vscode的remote-ssh插件连接

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#7438]
**JumpServer 版本(v1.5.9以下不再支持)**
2.17.0

**浏览器版本**
无关

**Bug 描述**
默认shell为Fish shell时无法通过vscode的remote-ssh插件登录
若更改默认shell为bash则可以正常登录

**Bug 重现步骤(有截图更好)**
1.  使用fish shell作为默认shell
![image](https://user-images.githubusercontent.com/22488813/147385047-0ac5aa4a-bd4c-41ed-b587-823bb8c81ade.png)
![image](https://user-images.githubusercontent.com/22488813/147385023-6bc5ad1d-531a-4842-86d6-3d9f9d495d61.png)
会一直卡在这个地方。

2. 使用bash作为默认shell
![image](https://user-images.githubusercontent.com/22488813/147385104-c61c8d60-d427-4683-a377-1051a616d4c9.png)
![image](https://user-images.githubusercontent.com/22488813/147385111-3e47d11e-4329-4fee-afdd-3e24576510bc.png)

3. 如果使用ssh直连，不管是bash还是fish，都可以正常登录：
![image](https://user-images.githubusercontent.com/22488813/147385163-fb7dd2bb-2ead-4f11-a99e-f47bd3c8eef1.png)

**Comment by ibuler** [comment]
@LeeEirc  处理一下

**Comment by LeeEirc** [comment]
vs code有自己的处理逻辑，需要深入做更多定制化的处理，因此暂时先不支持非bash的情况了。
Duplicate of #https://github.com/jumpserver/jumpserver/issues/6384

**Comment by rty813** [comment]
@LeeEirc 这个问题在v3上面是否得到修复？

**Comment by LeeEirc** [comment]
> @LeeEirc 这个问题在v3上面是否得到修复？
并不会直接支持。可以自行测试下，v3 对 Windows 版本 VS Code 的 remote-ssh 连接部分有调整。
