### ISSUE TITLE
django.db.utils.IntegrityError: (1364, "Field 'from_ticket' doesn't have a default value")

### ISSUE THREAD

**Issue by MagicStarTrace** [jumpserver/jumpserver#7439]
添加授权资产的时候我在croe的logs (log/jumpserver.log)看到这个
django.db.utils.IntegrityError: (1364, "Field 'from_ticket' doesn't have a default value")

![image](https://user-images.githubusercontent.com/15685376/147429768-49d125d6-9568-462c-84d5-447b6147235e.png)
![image](https://user-images.githubusercontent.com/15685376/147429812-90d486bf-d066-45bf-aaf6-a08aa180f3cf.png)

看起来是字段缺少默认值，什么问题导致的呢？还有这个怎么修复？
谢谢！

**Comment by wojiushixiaobai** [comment]
如果是升级后出现的，检查升级过程。或者还原数据库重新升级
