### ISSUE TITLE
[Bug] {'xx@126.com': (554, b'5.7.1 <xx@126.com>: Relay access denied')}

### ISSUE THREAD

**Issue by htmz** [jumpserver/jumpserver#7445]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Google Chrome
版本 96.0.4664.110（正式版本） (x86_64)

**Bug 描述**
jumpserver集群双机负载，同一个redis、mysql，邮件配置问题

**Bug 重现步骤(有截图更好)**
1.   jumpserver 111机器，测试发送邮件，显示Relay access denied
![111](https://user-images.githubusercontent.com/27039243/147532507-834362ba-2633-4e9d-acf0-51a8c0e6266e.png)
2.jumpserver 112机器，则是发送成功
![112](https://user-images.githubusercontent.com/27039243/147532564-0bf20bad-c6e1-43b9-b494-bec95606721c.png)
3. 当我在111机器上重新设置smtp账户密码时，测试邮件发送成功，但是112机器又会报Relay access denied错误
![1111](https://user-images.githubusercontent.com/27039243/147533064-659b30e5-e789-473c-99e9-a9b557aa8df0.png)
![1112](https://user-images.githubusercontent.com/27039243/147533089-128c8d15-8592-45b0-bad5-641bb793f61b.png)

**Comment by htmz** [comment]
补充：112机器 报Relay access denied错误
![1121](https://user-images.githubusercontent.com/27039243/147533314-c317aa06-ada9-458b-8500-a358a9f425a5.png)

**Comment by wojiushixiaobai** [comment]
此问题是两个节点的 SECRET_KEY 不一致导致，请检查配置文件
```bash
cat /opt/jumpserver/config/config.txt | grep SECRET_KEY
```

**Comment by htmz** [comment]
> 此问题是两个节点的 SECRET_KEY 不一致导致，请检查配置文件
> 
> ```shell
> cat /opt/jumpserver/config/config.txt | grep SECRET_KEY
> ```
```
SECRET_KEY=ODZjZjAyODctOGY4OS00MTZjLTg4ZTUtZmMxMDIwMTAwMTEx   111
SECRET_KEY=ODZjZjAyODctOGY4OS00MTZjLTg4ZTUtZmMxMDIwMTAwMTEy   112
```
确实不一样呢 应该以那个为准呢

**Comment by htmz** [comment]
> > 此问题是两个节点的 SECRET_KEY 不一致导致，请检查配置文件
> > ```shell
> > cat /opt/jumpserver/config/config.txt | grep SECRET_KEY
> > ```
> 
> ```
> SECRET_KEY=ODZjZjAyODctOGY4OS00MTZjLTg4ZTUtZmMxMDIwMTAwMTEx   111
> SECRET_KEY=ODZjZjAyODctOGY4OS00MTZjLTg4ZTUtZmMxMDIwMTAwMTEy   112
> ```
> 
> 确实不一样呢 应该以那个为准呢

解决问题 赞！！

**Comment by htmz** [comment]
解决
