### ISSUE TITLE
[Bug] 系统用户删除确认机制

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#7448]
v2.17.1
针对系统用户已经被资产关联调用了。
可以直接把该系统用户直接删除，并没有做判断吗？
比如该系统用户已经被资产使用，应该不能被删除，提示被使用。
当前情况可以直接删除掉。

**Comment by ibuler** [comment]
现在大部分都没有这个确认机制，用户也可以直接删掉，显然这个比 系统用户 删掉了更麻烦，等待更多反馈吧
