### ISSUE TITLE
luna-v2.17.1安装失败[Question] 

### ISSUE THREAD

**Issue by chinasjok** [jumpserver/jumpserver#7449]
手动安装luna组件
现象一，luna-v2.17.1 npm install 安装依赖后执行 build，有如下报错。淘宝和官方源多次尝试均是如此。
尝试通过[https://stackoverflow.com/questions/54162297/module-not-found-error-cant-resolve-crypto](url)修复并没有得到解决。
如果将crypto-js 更换成3.9版本Build就不会有问题，但仍然会出现现象二的问题。请问如何能解决，感谢~

(py3) [root@10-255-244-163 dist]# node --version
v10.24.1

(py3) [root@10-255-244-163 luna-v2.17.1]# node_modules/\@angular/cli/bin/ng build

chunk {main} main.js, main.js.map (main) 482 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 428 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 828 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1000 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.76 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 9.26 MB [initial] [rendered]
Date: 2021-12-29T09:28:39.513Z - Hash: 296041fe052beeccd119 - Time: 34491ms

WARNING in ./node_modules/crypto-js/core.js
Module not found: Error: Can't resolve 'crypto' in '/opt/luna-v2.17.1/node_modules/crypto-js'

现象二，如果使用 ng serve 启动 4200 端口后，点击 会话管理-->web终端页面 DevTools会报截图中的错误。Chrome 版本 93.0.4577.63
(py3) [root@10-255-244-163 luna-v2.17.1]# node_modules/\@angular/cli/bin/ng serve
10% building 4/4 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 486 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 428 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 828 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1000 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.76 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 10.9 MB [initial] [rendered]
Date: 2021-12-29T09:36:41.853Z - Hash: 2923edc88e966fdc30ee - Time: 37474ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Compiled successfully.

![image](https://user-images.githubusercontent.com/10579367/147649029-7c1c1d23-0769-41c7-ae3a-2a18b43effb0.png)

![image](https://user-images.githubusercontent.com/10579367/147648349-f772e6f2-c232-4216-a7d7-e7b78cd54c00.png)

**Comment by ibuler** [comment]
手动用 dockerfile 构建一下试试，所有过程都在 dockerfile 中表明了，nodejs 有时候一些依赖确实烦人

**Comment by tho1314** [comment]
在 https://stackoverflow.com/questions/52530289/module-not-found-error-cant-resolve-crypto-in-opt-lampp-htdocs-angular-te
找到解决方法：
But instead of using a pre-install, I just hand edited `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js' and changed the lines in that regex:
// old:
node: false,
// new:
node: { crypto: true, stream: true },

**Comment by ibuler** [comment]
dockerfile 中没有特殊处理过，不知道他们之间存在什么关系，是否和 Nodejs 版本有关
