### ISSUE TITLE
COCO没有资源组等信息

### ISSUE THREAD

**Issue by jiangshp** [jumpserver/jumpserver#745]
[简述你的问题]
使用coco或luna登录后，查看不到资源信息，无法连接到主机。
##### 使用版本
0.4.0版本

##### 问题复现步骤
1.使用ssh -p2222 admin@192.168.244.144登录，看不到资源信息。
![image](https://user-images.githubusercontent.com/32517381/31181071-f40c0c0e-a952-11e7-855b-5d0c34fb4fb3.png)

使用luna访问http://xx.xx.xx.xx:5000,看不到资源信息。
![image](https://user-images.githubusercontent.com/32517381/31181018-d0cf3c98-a952-11e7-8548-11914edab0e0.png)

2. jumpserver主机资源。

![image](https://user-images.githubusercontent.com/32517381/31181177-3d77cfae-a953-11e7-9b86-fa9ce46fa922.png)

**Comment by ibuler** [comment]
创建主机后授权给admin用户没有？
