### ISSUE TITLE
[Feature] 建议新增批量移除系统用户资产列表中的资产

### ISSUE THREAD

**Issue by renziyou** [jumpserver/jumpserver#7451]
**请描述您的需求或者改进建议.**

情景描述：因同事操作失误，在系统用户资产列表右侧【关联节点】添加了根节点，导致所有资产被关联至该用户下，当移除节点后资产清单中的资产任在该用户下，需手动一台一台点删除。因此希望新增批量移除，或移除节点后自动移除节点下的资产

**Comment by ibuler** [comment]
收到

**Comment by jym503558564** [comment]
已记录，并反馈。
