### ISSUE TITLE
web终端页面跳转问题

### ISSUE THREAD

**Issue by linl12138** [jumpserver/jumpserver#7456]
![image](https://user-images.githubusercontent.com/42909446/147801214-1b42e9e6-7d09-42f4-a424-ba0a765401fe.png)
希望这个跳转可以修改为跳转到新页面

**Comment by ibuler** [comment]
好

**Comment by ibuler** [comment]
我记得这个地址好像没有跳转地址，打算直接去掉跳转

**Comment by ibuler** [comment]
https://github.com/jumpserver/luna/pull/480
