### ISSUE TITLE
[Bug] JumpServer 工单显示问题

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7457]
JumpServer版本：JumpServer v2.17
Bug 描述：JumpServer v2.17版本普通用户通过工单申请资产不显示申请按钮
Bug截图：

![image](https://user-images.githubusercontent.com/29521063/147801809-062383ee-401c-420b-a3ca-309485eaef90.png)

**Comment by ibuler** [comment]
内部聊吧
