### ISSUE TITLE
希望增加常见的流行数据库的管理，目前只有mysql

### ISSUE THREAD

**Issue by charles-liming** [jumpserver/jumpserver#7459]
比如 postgre 的流行度因次于mysql，国内市场对mysql 的支持比较多，但是pg 确实很少（但是pg 的用户并不少），另外mysql 面临闭源 的风险，还请多支持下postgre 数据库

**Comment by ibuler** [comment]
目前还没有计划支持 pg，等待国内 pg 的强大吧
