### ISSUE TITLE
SUDO权限怎么配置

### ISSUE THREAD

**Issue by jiangshp** [jumpserver/jumpserver#746]
[简述你的问题]
如何配置SUDO权限，配置系统帐号具有所有命令权限。

##### 使用版本
0.4版本
![image](https://user-images.githubusercontent.com/32517381/31184708-be6c0270-a95c-11e7-8a3f-285d34fcb63a.png)

**Comment by hellorocky** [comment]
如图所示

**Comment by ibuler** [comment]
这里的sudo写法和我们平时配置用户sudo是一样的，/bin/whoami,!/bin/ifconfig 等等

**Comment by jiangshp** [comment]
如果是普通帐号，需要可以执行所有权限呢？  用ALL没有效果，还是普通帐号的权限，没有其它权限。

**Comment by hellorocky** [comment]
@jiangshp  可以先学习一下sudo和sudoers的使用吧
