### ISSUE TITLE
安装pip install -r requirements/requirements.txt

### ISSUE THREAD

**Issue by honghh2018** [jumpserver/jumpserver#7461]
找不到ERROR: Failed building wheel for xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects

dnf install xmlsec1-devel 报找不到包xmlsec1-devel

Last metadata expiration check: 2:07:39 ago on Fri 31 Dec 2021 04:53:03 AM EST.
No match for argument: xmlsec1-devel
Error: Unable to find a match: xmlsec1-devel

 xmlsec1存在我的系统中
 xmlsec1 --version
(py3) [root@localhost jumpserver-2.17.1]#  xmlsec1 --version
xmlsec1 1.2.25 (openssl)

版本：
CENTOS8
如何解决这个问题呢？

祝好

**Comment by wojiushixiaobai** [comment]
启用 centos-powertools
