### ISSUE TITLE
[Feature] 允许用户自助重置MFA验证码

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#7462]
**请描述您的需求或者改进建议.**
当用户体量很大时，每天都能收到一些用户的服务请求，要重置MFA验证码的，这给管理员增加了不少工作，用户也感觉不方便。是否可以给用户一个自助重置的地方？

**Comment by wojiushixiaobai** [comment]
自己写个页面，调 api 处理即可

**Comment by ibuler** [comment]
允许用户重置 MFA，那 MFA 存在的意义是什么？攻击的时候 攻击者也提出重置  MFA 的请求

**Comment by khy2021** [comment]
MFA重置之前需要LDAP认证

**Comment by ibuler** [comment]
MFA 是防突破的最后屏障，不允许用户自己重置，如果忘记只能让管理员重置
