### ISSUE TITLE
[Bug] 文件管理一次性选择大量文件时卡loading

### ISSUE THREAD

**Issue by Phyzait** [jumpserver/jumpserver#7465]
**JumpServer 版本(v1.5.9以下不再支持)**
2.17.0

**浏览器版本**
Chrome 96.0.4664.93（正式版本） (arm64)

**Bug 描述**
文件管理批量选择大量文件并操作删除，卡加载中，删不掉。只能分批删除，一次删二十多个非常快。
大概四十个文件以上会出现这种问题

**Bug 重现步骤(有截图更好)**
1.  文件管理选中大量文件（大概四十个以上）
2. 删除

**Comment by LeeEirc** [comment]
删除特别多的文件，猜测可能会触发 http 请求 URL 最大长度限制。可打开 浏览器开发者工具查看下。

**Comment by ibuler** [comment]
想办法 alert 一下？
