### ISSUE TITLE
[Question] Koko 打开ENABLE_LOCAL_PORT_FORWARD后依旧有问题

### ISSUE THREAD

**Issue by x2x4com** [jumpserver/jumpserver#7466]
需求是这样，我们有些内部服务是需要通过http来访问，之前要么是通过本地ssh动态端口转发，然后用代理进去方式访问，要么用本地端口直接ssh后绑定对端端口到本地

Host jumpserver-user1-1
    HostName some-public-ip
    Port 2222
    User user1
    DynamicForward 12083

Host jumpserver-user1-2
    HostName ip
    Port 2222
    User user1

Host internal-service-1
	HostName 10.205.194.220
	User host-user
	ForwardAgent yes
	ProxyJump   jumpserver-user1-2
	LocalForward 9099 127.0.0.1:8091

 无论是哪一种登录进去都是报下面的错误
open failed: administratively prohibited: port forwarding is disabled

koko的版本是2.17

koko打开了转发的参数
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true

确认容器在启动时候参数已经生效了

2022/01/04 11:08:59 &{Name:[KoKo]-dev-jumper-hype-c2e47ac46af2 CoreHost:http://core:8080 BootstrapToken:abcd BindHost:0.0.0.0 SSHPort:2222 HTTPPort:5000 SSHTimeout:15 LogLevel:ERROR Comment:KOKO LanguageCode:en UploadFailedReplay:true AssetLoadPolicy: ZipMaxSize:1024M ZipTmpPath:/tmp ClientAliveInterval:30 RetryAliveCountMax:3 ShowHiddenFile:false ReuseConnection:true ShareRoomType:local RedisHost:redis RedisPort:6379 RedisPassword:efg RedisDBIndex:0 RedisClusters:[] EnableLocalPortForward:true EnableVscodeSupport:true RootPath:/opt/koko DataFolderPath:/opt/koko/data LogDirPath:/opt/koko/data/logs KeyFolderPath:/opt/koko/data/keys AccessKeyFilePath:/opt/koko/data/keys/.access_key ReplayFolderPath:/opt/koko/data/replays}

**Comment by wojiushixiaobai** [comment]
不支持转发，也不支持隧道

**Comment by x2x4com** [comment]
那么有什么其他的解决方法来满足我访问堡垒机后的http的请求呢

**Comment by x2x4com** [comment]
算了，内网再开一台windows专门用户http的代理，再用jumpserver监管
