### ISSUE TITLE
新版本对做了登录限制的的ad账号,登录服务器会提示密码错误

### ISSUE THREAD

**Issue by ShawnZHFaa** [jumpserver/jumpserver#7468]
旧版本可以跳过这个界面直接进入到服务器在输入登录 新版本必须在这里输入
![image](https://user-images.githubusercontent.com/97140567/148151744-81549bf5-41ac-47ef-b338-6a6a4d0aec53.png)
但是对做了登录限制的AD账号登录会报账号密码错误
![image](https://user-images.githubusercontent.com/97140567/148151930-619a1c61-6a12-4d79-869b-7f3aebb481b7.png)
![image](https://user-images.githubusercontent.com/97140567/148152061-464ce409-2c15-495b-a773-dc1a8b40fe96.png)
![image](https://user-images.githubusercontent.com/97140567/148152090-4e33e351-bbe4-4269-b645-dff9e3cef471.png)
只要AD上解开登录限制 把这个账号改为可以登录到全部计算机  马上可以登录
老版本可以直接点跳过按钮进入到服务器在输入域账号密码，新版本无法跳过导致域账号一直无法登录 急！！！

**Comment by ShawnZHFaa** [comment]
登陆后查看日志提示用户不允许登录到这台电脑 但是AD上面是放开允许登录的
![image](https://user-images.githubusercontent.com/97140567/148159232-6aad1432-b745-47b0-ad99-56b0ce2652ad.png)

**Comment by ShawnZHFaa** [comment]
问题已解决，需要添加jms_lion这个容器的容器ID到AD账号上面，但是之前旧版本不需要这个操作。
![image](https://user-images.githubusercontent.com/97140567/148172173-8c0a6b24-3e6b-4860-947e-78fcaea31c49.png)
![image](https://user-images.githubusercontent.com/97140567/148172193-2dfde44c-2ef6-43c6-b3f9-4a33597e9f26.png)

**Comment by ibuler** [comment]
这个在这里输入，和点击跳过，在windows页面输入，结果应该是一样的

**Comment by WeiqiuLiu** [comment]
> 问题已解决，需要添加jms_lion这个容器的容器ID到AD账号上面，但是之前旧版本不需要这个操作。 ![image](https://user-images.githubusercontent.com/97140567/148172251-438c761e-bf64-431d-af98-3cc7c86043a6.png) ![image](https://user-images.githubusercontent.com/97140567/148172284-3f935bd4-5c15-49a7-9e3d-bd5f9ec11727.png)

我也遇到了同样的问题，在jumpserver系统账号配置内添加了AD域名，之前的版本可以用，更新到2.17.3后就无法登录了。
域控报错日志：
```
源工作站:	36f8395f2af2 # 这个就是docker container id
错误代码:	0xC0000070
```

**Comment by wojiushixiaobai** [comment]
@WeiqiuLiu 可能是系统平台有问题，资产详情里面检查下。
