### ISSUE TITLE
[Bug] allinone部署的环境批量执行命令一直显示等待

### ISSUE THREAD

**Issue by hejianlai** [jumpserver/jumpserver#7469]
**JumpServer 版本(v1.5.9以下不再支持)**

jumpserver版本2.1..0
allinone安装
redis版本6.0

**浏览器版本**

**Bug 描述**
批量执行命令一直显示等待
![647d813e3a58a7ed2ab8ca97e3d6132](https://user-images.githubusercontent.com/31337851/148171181-2ff78969-fc20-4351-96cb-5657a131151b.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
尝试重启或检查 celery 日志
如果配置了反向代理，注意配置 websocket

**Comment by ibuler** [comment]
感觉应该是 celery 出问题了，这个需要未来项目能明确提示

**Comment by hejianlai** [comment]
> 
重启也查看了celery的日志没事有异常信息，但是执行命令还是一直等待0.0
![Uploading image.png…]()

**Comment by wojiushixiaobai** [comment]
图片看不到，你看看有没有报错的内容。
没有的话，可以看下web页面的任务监控，看看组件是否都在线

**Comment by hejianlai** [comment]
> 图片看不到，你看看有没有报错的内容。 没有的话，可以看下web页面的任务监控，看看组件是否都在线
组件都是在线的0.0
![image](https://user-images.githubusercontent.com/31337851/148897279-14deb7bf-0c84-4ba6-9ba6-161cd5d6fd26.png)

**Comment by wojiushixiaobai** [comment]
已复现此问题，由 -d 后台运行导致的问题，临时修复访问
wojiushixiaobai/Dockerfile#19059e1898f008b8e15b8a78330a217d4bd978b8

等待版本更新修复
