### ISSUE TITLE
[Bug] 在telnet交换机时配置了命令过滤的高危命令无法被过滤

### ISSUE THREAD

**Issue by zhangkehz** [jumpserver/jumpserver#7472]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.17.2 GPLv2

**浏览器版本**
Microsoft Edge 版本 96.0.1054.62

**Bug 描述**
在telnet交换机时配置了命令过滤的高危命令无法被过滤

**Bug 重现步骤(有截图更好)**
1.  新建交换机资产并连接
2. bug截图（已经禁止了的情况下命令仍然运行了）
![41f316c6068f68a9fb62413ac696d8d](https://user-images.githubusercontent.com/55628285/148718902-c7e3f14b-8dec-443a-9184-30c224366d6f.png)
3. 交换机版本号
![image](https://user-images.githubusercontent.com/55628285/148718808-52689c43-4360-4a5b-8d10-0ebf177c120a.png)

**Comment by LeeEirc** [comment]
收到，待调研之后，修复。

**Comment by ibuler** [comment]
已记录到内部 bug 库，暂时关闭 issue，修复后会在该 issue 通知

**Comment by LeeEirc** [comment]
@zhangkehz 能否在交流群里找下我(Eric)，想在你的测试环境验证下。
