### ISSUE TITLE
[Bug] 在线数量不对 

### ISSUE THREAD

**Issue by laodengto** [jumpserver/jumpserver#7474]
**请描述您的需求或者改进建议.**
在JumpServer首页显示的在线用户数量 和实际在线用户数不对
![image](https://user-images.githubusercontent.com/49049414/148737286-51fea738-c7ef-4c6e-9cf1-97f483a1b365.png)

**Comment by oldboydeng** [comment]
实际在线四个人

**Comment by ibuler** [comment]
这个在线是指的连接资产，没有连接资产就不算，可能有歧义，打算更改

**Comment by jym503558564** [comment]
已记录反馈给开发人员，请持续关注我们版本发布情况。
