### ISSUE TITLE
2.17.3 数据库连接提示错误

### ISSUE THREAD

**Issue by Ericmar** [jumpserver/jumpserver#7480]
koko 2.17.3 数据库连接报以下错误，mysql-client 版本 mysql-8.0.27-linux-glibc2.17-x86_64-minimal
fork/exec /usr/local/bin/mysql: operation not permitted

**Comment by Ericmar** [comment]
![image](https://user-images.githubusercontent.com/1302654/148985898-195f2423-e1ea-4baa-bc9d-66da0b96364b.png)

**Comment by Ericmar** [comment]
![image](https://user-images.githubusercontent.com/1302654/148989192-ce01c12f-f721-4a04-a088-039ee971824e.png)
日志显示字符不匹配，连是连上的

**Comment by Ericmar** [comment]
以非root用户启动，启动用户jumpserver，已经给了免密的sudo权限

**Comment by wojiushixiaobai** [comment]
mysql 二进制权限不对

**Comment by Ericmar** [comment]
> mysql 二进制权限不对

但是本地直接运行是对的啊～你的意思是执行文件的权限问题吗

**Comment by Ericmar** [comment]
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
你自己构建的镜像的话，可以参考 https://github.com/jumpserver/Dockerfile/blob/master/koko/Dockerfile 此文件

**Comment by Ericmar** [comment]
我是按照这个https://docs.jumpserver.org/zh/master/dev/build/编译安装的
