### ISSUE TITLE
执行最新版本2.17.3安装报错./jmsctl.sh install

### ISSUE THREAD

**Issue by zhmg23** [jumpserver/jumpserver#7482]
**请描述您的问题.**
在安装最新版本2.17.3时，报错
# ./jmsctl.sh install
1. 检查配置文件
2. 备份配置文件
3.  配置持久化目录
4.  配置 MySQL
5. 配置 Redis
6. 配置对外端口
以上都正常通过
到第7步报错了
7. 初始化数据库
Creating network "jms_net" with driver "bridge"
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-dfaaacaa8b87 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
Creating network "jms_net" with driver "bridge"
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-3fec5a964112 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))
Error: No such container: jms_core
[ERROR] 表结构变更失败!

**Comment by wojiushixiaobai** [comment]
别在 docker 启动后修改任何 firewalld 或 iptables
使用以下命令解决
```bash
./jmsctl.sh down
systemctl restart docker
./jmsctl.sh init_db
```

**Comment by zhmg23** [comment]
感谢感谢！通过如下方式解决：
1、删除之前的镜像
2、重启docker

> 别在 docker 启动后修改任何 firewalld 或 iptables 使用以下命令解决
> 
> ```shell
> ./jmsctl.sh down
> systemctl restart docker
> ./jmsctl.sh init_db
> ```
