### ISSUE TITLE
[Question] ssh基本登录问题

### ISSUE THREAD

**Issue by zhoucz97** [jumpserver/jumpserver#7484]
**请描述您的问题.**
请问普通用户如何通过终端连接服务器呢，直接ssh 资产IP会报超时错误，看到其他issue中要用下面格式登录
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p222   这四个字段分别在哪里获得呢？？

**Comment by ibuler** [comment]
ssh laoguang@root@172.16.1.1@demo.jumpserver.org -p2222

laoguang: 是自己登录 jumpserver 系统的用户
root: 是登录资产的信息
172.16.1.1: 是资产的Ip

**Comment by zhoucz97** [comment]
感谢

**Comment by ibuler** [comment]
超过 7 天没有回复，暂时关闭 issue， 有疑问可以重新打开
