### ISSUE TITLE
[Bug] Windows server 2016连接性探测故障

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7499]
**JumpServer 版本(v1.5.9以下不再支持)**
JumpServer v2.16.3

**浏览器版本**

**Bug 描述**
windows server 2016在安装Openssh后进行连接性探测会hang住，windows server 2019则正常。但是实际连接是正常的。
![image](https://user-images.githubusercontent.com/29521063/149441270-ca6e23cb-6f6e-4275-9a84-e6126a0734b6.png)
![image](https://user-images.githubusercontent.com/29521063/149441283-1b54da0b-f3f4-4033-96df-e6891e39dec9.png)

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
没法复现，我多找几个环境验证下。稍后回复
