### ISSUE TITLE
[Bug] 手机登录终端输入字符重复

### ISSUE THREAD

**Issue by LASTGL** [jumpserver/jumpserver#7501]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver 2.12.2 通过jumpserver-installer-v2.17.3升级至

jumpserver 2.17.3

**浏览器版本**
ios15.2 Safari  百度输入法
HarmonyOS 2 华为游览器 华为输入法/百度输入法

**Bug 描述**
使用手机ssh登录交换机成功后输入字符会发生重复

**Bug 重现步骤(有截图更好)**
1. 手机通过域名登录jumpserver
2. 通过web终端ssh登录交换机
3. 输入sys，web终端显示ssyyss。

回退至2.12.2恢复正常

**Comment by LeeEirc** [comment]
切换成英文输入法试试？

**Comment by LASTGL** [comment]
> 切换成英文输入法试试？

切换到英文输入会重复，ios切换原生纯英文输入法倒是正常了

**Comment by LeeEirc** [comment]
> > 切换成英文输入法试试？
> 
> 切换到英文输入会重复，ios切换原生纯英文输入法倒是正常了

华为也使用原生输入法呢？

**Comment by wojiushixiaobai** [comment]
中文输入法确实会出现此问题，可以切换到英文输入法临时解决

**Comment by jym503558564** [comment]
https://github.com/jumpserver/jumpserver/issues/7000 重复问题

**Comment by jym503558564** [comment]
已记录
