### ISSUE TITLE
helm 部署，自定义resources：不生效 [Bug] 

### ISSUE THREAD

**Issue by haitang5445** [jumpserver/jumpserver#7504]
**JumpServer 版本(v1.5.9以下不再支持)**
 jumpserver/jumpserver   2.17.3          v2.17.3         A Helm chart for Deploying Jumpserver on Kubern...

**浏览器版本**

**Bug 描述**
使用helm部署jumpserver 后发现 对core koko lion的资源限制resources: 不生效 

**Bug 重现步骤(有截图更好)**
1.  helm pull jumpserver/jumpserver   
2.  tar -zxvf jumpserver-2.17.3.tgz
3.  cd jumpserver
4.  编辑values.yaml （只修改了core的）
......

    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi

......

5.  helm install test --dry-run --debug ./ > 1.txt
6.  查看 1.txt
......

  COMPUTED VALUES:
  core:
    affinity: {}
    command: []
    config:
      bootstrapToken: ""
      debug: false
      log:
        level: ERROR
      secretKey: ""
    enabled: true
    env: []
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: jumpserver/core
      tag: v2.17.3
    labels:
      app.jumpserver.org/name: jms-core
    livenessProbe:
      failureThreshold: 30
      httpGet:
        path: /api/health/
        port: web
    nodeSelector: {}
    persistence:
      accessModes:
      - ReadWriteMany
      finalizers:
      - kubernetes.io/pvc-protection
      size: 10Gi
      storageClassName: jumpserver-data
    podSecurityContext: {}
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /api/health/
        port: web
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
  
.........

      containers:
        - name: jms-celery
          securityContext:
            {}
          image: "docker.io/jumpserver/core:v2.17.3"
          imagePullPolicy: IfNotPresent
          args: ["start", "task"]
          env:
            - name: SECRET_KEY
              value: ""
            - name: BOOTSTRAP_TOKEN
              value: ""
            - name: DEBUG
              value: "false"
            - name: LOG_LEVEL
              value: "ERROR"
            - name: SESSION_EXPIRE_AT_BROWSER_CLOSE
              value: "true"
            - name: HTTP_LISTEN_PORT
              value: "8080"
            - name: WS_LISTEN_PORT
              value: "8070"
            - name: DB_ENGINE
              value: "mysql"
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: "jumpserver"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /opt/jumpserver/utils/check_celery.sh
          resources:
            null
          volumeMounts:

......

**Comment by ibuler** [comment]
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
已经处理，下个版本修复。

**Comment by wojiushixiaobai** [comment]
我来关就行。等发版了我关

**Comment by haitang5445** [comment]
我已经clone 源码自己package 了 ，  233333
