### ISSUE TITLE
[Bug] 在资产列表点击【测试资产可连接性】时报Connect websocket server error

### ISSUE THREAD

**Issue by jackey20200402** [jumpserver/jumpserver#7514]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.17.3

**浏览器版本**
Chrome 版本 97.0.4692.71（正式版本） （64 位）

**Bug 描述**
在资产列表点击【测试资产可连接性】时报Connect websocket server error
查看celery_ansible.log 看到有执行ansible命令

**Bug 重现步骤(有截图更好)**
1. 点击 【测试资产可连接性】
[截图1](https://github.com/jackey20200402/myrepo/blob/main/img/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220117192824.png)

**Comment by wojiushixiaobai** [comment]
正常部署的话，重启下jumpserver即可。
有单独的反向代理或者vpn请配置websocket支持

**Comment by jym503558564** [comment]
@jackey20200402 该问题还存在吗？

**Comment by jym503558564** [comment]
如果还存在的话，可再次打开Issues
