### ISSUE TITLE
[Bug] windows server连接问题

### ISSUE THREAD

**Issue by gold-fisher** [jumpserver/jumpserver#7516]
**JumpServer 版本(v1.5.9以下不再支持)**：2.14.2

**浏览器版本** chrome 96.0.4664.110

**Bug 描述**
有多台windows机器时，系统用户里的administrator密码设置成不同时，jumpserver连接报错，“用户名或密码认证错误”，但实际上密码是正确的，因为通过本地mstsc远程测试过。
当把这几个administrator的密码改成相同时，jumpserver就可以连接上这些windows机器了。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24870097/149802005-f2ba208f-ee1f-4c55-8fc1-08c05c9df66c.png)

1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
需要管理员权限

**Comment by gold-fisher** [comment]
> 需要管理员权限

![image](https://user-images.githubusercontent.com/24870097/149857791-85cd7ece-3a5a-4024-9808-5881083198a5.png)
就是用jumpserver的管理员添加的上述用户

**Comment by ibuler** [comment]
@wojiushixiaobai 这个我们能复现吗

**Comment by wojiushixiaobai** [comment]
如果是连接资产报错，检查授权是否正确选择系统用户。如果是测试资产连接报错，检查特权用户

**Comment by gold-fisher** [comment]
> 如果是连接资产报错，检查授权是否正确选择系统用户。如果是测试资产连接报错，检查特权用户

现在就是把系统用户temp和temp2里的administrator密码改成一样的，就可以连接资产了。

**Comment by ibuler** [comment]
temp temp2 两个密码都改成错的，测试，
temp1 改成正确的 连接测试，
temp1 改成错误的，temp2 改成错误的 连接测试
