### ISSUE TITLE
[Feature] 登录windows服务器添加/admin选项

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#7518]
**请描述您的需求或者改进建议.**
有的机器配置了rds，当rds过期或者授权数满了的时候，账号无法登录，此时mstsc需要使用/admin参数进行登录。是否可以给用户一个选项，让用户可以选择/admin登录。

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/150109729-cf4da19e-e0a6-48d4-a209-218238f6f67e.png)

如示，创建一个新的 平台，资产使用这个平台即可

**Comment by khy2021** [comment]
3Q

**Comment by dongfo** [comment]
测试发现该办法可以在window server 2008上奏效，但在window server2012,2016上无效。
