### ISSUE TITLE
[Question] 请问如何单独升级2.9.0版本以前的gua组件从1.3.0更新到1.4.0

### ISSUE THREAD

**Issue by enan820** [jumpserver/jumpserver#7520]
**请描述您的问题.**
大佬们，由于业务原因无法将jumpserver更新到最新版，所以想单独升级gua组件。我修改了docker-guacamole项目中的GUACD_VER=1.4.0和guacamole-1.4.0.war。guacamole-auth-jumpserver-1.3.0.jar保持不变，制作了jumpserver/guacamole镜像。成功启动后，gua组件始终显示离线。
docker logs -f jms_guacamole后显示的错误信息如下图
![图片1](https://user-images.githubusercontent.com/18327082/149881211-649d7b56-5ce9-492b-9ba1-20c13d2f0ed0.png)

**Comment by enan820** [comment]
使用1.4.0的server和guacamole-1.3.0.war能够注册，但server和client版本不同，总感觉会有问题。

**Comment by ibuler** [comment]
自己适配一下吧
