### ISSUE TITLE
[Question] jumpserver更新至2.17.3后，jms_web一直重启

### ISSUE THREAD

**Issue by zhmg23** [jumpserver/jumpserver#7528]
**请描述您的问题.**
请问一下，jumpserver更新至2.17.3后，jms_web一直重启

# docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                          PORTS                              NAMES
055b1ec24654        jumpserver/lion:v2.17.3   "/usr/bin/supervisord"   19 minutes ago      Up 19 minutes (healthy)         4822/tcp                           jms_lion
a7498d6eb609        jumpserver/core:v2.17.3   "./entrypoint.sh sta…"   19 minutes ago      Up 19 minutes (healthy)         8070/tcp, 8080/tcp                 jms_celery
97ddccfaa5cb        jumpserver/koko:v2.17.3   "./entrypoint.sh"        19 minutes ago      Up 19 minutes (healthy)         0.0.0.0:2222->2222/tcp, 5000/tcp   jms_koko
f8c71eabf045        jumpserver/web:v2.17.3    "/docker-entrypoint.…"   19 minutes ago      Restarting (1) 32 seconds ago                                      jms_web
198137237bc8        jumpserver/core:v2.17.3   "./entrypoint.sh sta…"   19 minutes ago      Up 19 minutes (healthy)         8070/tcp, 8080/tcp                 jms_core

查看容器日志
#docker logs f8c71eabf045 
nginx: [emerg] host not found in upstream "koko" in /etc/nginx/conf.d/default.conf:36
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] host not found in upstream "koko" in /etc/nginx/conf.d/default.conf:36
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] host not found in upstream "koko" in /etc/nginx/conf.d/default.conf:36

请问这是什么原因？

**Comment by zhmg23** [comment]
> koko 容器没有启动？

启动成功的，见下图
<img width="905" alt="koko" src="https://user-images.githubusercontent.com/5287893/150059848-f66491d0-75e4-4f9b-9878-18d70b1f9d0a.png">

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/150108841-5ae55bfd-eb46-4e92-8a3d-422318b93a56.png)

nginx 这个报错就是 因为没有发现 koko 容器，先删除 web 容器，在启动

```
$ docker rm jms_web
$ ./jmsctl start
```

**Comment by jym503558564** [comment]
@zhmg23 该问题是否已经解决，如还有问题，可再次打开Issues.
