### ISSUE TITLE
[Bug] H5端linux terminal字符键入重复键入

### ISSUE THREAD

**Issue by Fit2CloundGhh** [jumpserver/jumpserver#7531]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.17.3

**浏览器版本**
Chrome 97.0.4692.71

**Bug 描述**
使用H5端的堡垒机，连接linux资产时，使用手机键盘键入命令时，每个字符都会重复输入，例如输入`ll`，terminal界面会出现'llll'

**Bug 重现步骤(有截图更好)**
1.  登录H5堡垒机
2. 连接任意一台linux资产
3. 输入命令

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/150109471-74f4853a-5946-496d-90e5-621dc83421f7.png)

如示，创建一个新的 平台，资产使用这个平台即可

**Comment by ibuler** [comment]
小米手机表示没有问题

**Comment by ibuler** [comment]
输入法问题，不要在英文状态下输入
