### ISSUE TITLE
[对于数据库命令的过滤可以不区分大小写] 

### ISSUE THREAD

**Issue by luolei2939** [jumpserver/jumpserver#7536]
目前命令过滤器的命令过滤规则使用正则表达式，会区分大小写，Linux的命令是区分大小写的，但是数据库的命令是不区分大小写的。
比如命令过滤器里设置了DROP DATABASES; 可以被阻挡，但是drop databases就不行。
希望可以增加一个选项，如果是数据库命令过滤就不区分大小写，Linux服务器命令区分大小写。
![Uploading image.png…]()

**Comment by ibuler** [comment]
已记录，等待处理
