### ISSUE TITLE
Jumpserver的录像回放是怎么实现的啊？有录像文件吗？

### ISSUE THREAD

**Issue by congyingzhu** [jumpserver/jumpserver#754]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
问题不清楚

**Comment by congyingzhu** [comment]
就是我们有个项目，想要对jumpserver的录像回放功能进行二次开发，jumpserver的录像回放功能是怎么实现的？是jumpserver录像的时候打开了第三方工具录像，还是说用的是其他思路？

**Comment by MOOREZHANG64** [comment]
录像保存在replay文件下，但用第三方软件（如影音先锋）无法打开该.replay文件
![image](https://user-images.githubusercontent.com/10070015/65216711-71e8ed80-dae4-11e9-8ae1-3cc279169134.png)

**Comment by 528592869** [comment]
我也遇到这个问题，解决了没？

**Comment by congyingzhu** [comment]
解决了，就是前端渲染数据行程的录像



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] Jumpserver的录像回放是怎么实现的啊？有录像文件吗？ (#754)





 
我也遇到这个问题，解决了没？

**Comment by congyingzhu** [comment]
解决了，就是前端渲染数据形成的录像，没有具体文件，只有数据






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] Jumpserver的录像回放是怎么实现的啊？有录像文件吗？ (#754)





 
我也遇到这个问题，解决了没？
