### ISSUE TITLE
[Bug] 配置网域网关，资产可正常ssh，但测试资产连接失败

### ISSUE THREAD

**Issue by hujx111** [jumpserver/jumpserver#7543]
**JumpServer 版本(v2.17.3)**

**Bug 描述**
配置网域网关后，测试连接网关正常 ，端口22。配置资产，选择网域，配置完成后可以正常ssh。但测试资产可连接性，就报错了「fatal: [xxxxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange", "unreachable": true}」，更新硬件信息也是同样的报错信息

![image](https://user-images.githubusercontent.com/43087874/150474217-071e2f22-1abc-4c12-8a1a-d10a36ee913c.png)

**Comment by ibuler** [comment]
可连接性测试用的是管理用户，连接用的是某个别的系统用户

**Comment by hujx111** [comment]
目前测试都是同一个用户下，配置了root用户

**Comment by jym503558564** [comment]
创建资产所选择的特权用户的密码正确吗？

**Comment by ChenNengNeng** [comment]
有同样的问题，连接超时，怀疑在测试连接和更新硬件信息的时候没有正常走网域网关，jumpserver版本2.17.3。

**Comment by hujx111** [comment]
> 可以正常ssh，密码没问题。

**Comment by hujx111** [comment]
可以正常ssh，密码没错

**Comment by jym503558564** [comment]
升级到v2.18.2或者v2.19.1版本进行测试，最近修复了该问题。

**Comment by hujx111** [comment]
升级到v2.18.2或者v2.19.1版本，这两个版本都有同样的问题。跟https://github.com/jumpserver/jumpserver/issues/7600 这个一样

**Comment by wuchengjiang** [comment]
升级到v2.20.2 也不行，之前没问题的，现在重新推送也不行。
TASK [Set manager password] ****************************************************
fatal: [SHIDC-10-10-3-55]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\nConnection to UNKNOWN port 65535 timed out", "unreachable": true}

PLAY RECAP *********************************************************************
SHIDC-10-10-3-55 : ok=4    changed=1    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
推送系统用户到平台: [unixlike]
主机数量: 1

PLAY [Push system users to asset: 普通用户(None) => SHIDC-10-10-3-55(10.10.3.55)] ***

TASK [Add user dev] ************************************************************
fatal: [SHIDC-10-10-3-55]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\nConnection to UNKNOWN port 65535 timed out", "unreachable": true}

PLAY RECAP *********************************************************************
SHIDC-10-10-3-55: ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
Push system user task skip, auto push not enable: system_user=jump
Task assets.tasks.push_system_user.push_system_users_a_asset[f245a87d-fe81-4d28-8623-bae8216b3529] succeeded in 279.549102505669s: None

**Comment by zhongw** [comment]
一路升级到2.20.2，在添加网域网关后，也遇到楼上类似的问题。
```
fatal: [myhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host\r\nConnection closed by UNKNOWN port 65535", "unreachable": true}
```

**Comment by Nidhoggur1993** [comment]
@ibuler 版本 v2.20.3 也有这个问题，但情况稍微有点不同
复现方式：
1. 新建/导入资产server1
2. 创建特权用户user1
3. 在权限管理中，授权特权用户user1给server1
![image](https://user-images.githubusercontent.com/12947582/164651074-f4264d78-81c3-4665-abda-492216f067b9.png)

4. 资产列表中，进入server1详情页，此时：
    i. 详情页中不显示特权用户
    
![image](https://user-images.githubusercontent.com/12947582/164649078-c5c5f89c-ec80-45e0-a89e-ed40967861f2.png)

    ii. 点击连通性测试，celery报错，连通性测试的用户是root@server1而不是user1@server1
    
![image](https://user-images.githubusercontent.com/12947582/164648928-9da7e4ca-bdfe-40d0-ac4a-328c0fceec50.png)

**Comment by vincent1016** [comment]
@Nidhoggur1993 我碰到跟你一样的问题，你的主机是不是用密钥对登录的？

**Comment by Nidhoggur1993** [comment]
> @Nidhoggur1993 我碰到跟你一样的问题，你的主机是不是用密钥对登录的？

我的问题解决了，主要是因为没有配置特权用户
你看一下`点击资产-更新-特权用户`是不是没有配置任何东西，是空的
就我的问题来说，选择一个正确的特权用户就好了
我怀疑这是个导入资产和特权用户分配的bug
@ibuler

**Comment by hujx111** [comment]
我似乎找到的问题所在了，作为网关的服务器openssh版本要跟源的版本一致。原来网关的openssh版本号是「OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017」，源服务器版本：「OpenSSH_8.8p1, OpenSSL 1.0.2k-fips  26 Jan 2017」。把网关服务器的openssh升级之后，进行连接测试，可以成功，不会报「UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\nConnection to UNKNOWN port 65535 timed out",」"unreachable": true}

**Comment by woniuzhang** [comment]
> 我似乎找到的问题所在了，作为网关的服务器openssh版本要跟源的版本一致。原来网关的openssh版本号是「OpenSSH_7.4p1, OpenSSL 1.0.2k-fips 26 Jan 2017」，源服务器版本：「OpenSSH_8.8p1, OpenSSL 1.0.2k-fips 26 Jan 2017」。把网关服务器的openssh升级之后，进行连接测试，可以成功，不会报「UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\nConnection to UNKNOWN port 65535 timed out",」"unreachable": true}

遇到了同样的问题， 源服务器 和 网关的openssh版本号 都是openssh-7.4p1
