### ISSUE TITLE
[Bug] 配置网关时，不能配置带密码的密钥

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#7544]
**JumpServer 版本(v1.5.9以下不再支持)**
2.17.0

**浏览器版本**
谷歌97.0.4692.71

**Bug 描述**
配置网关时，不能配置带密码的密钥。
在配置系统用户时，可以填写密钥密码，在配置网关时应该也能支持填写密钥密码。

**Bug 重现步骤(有截图更好)**
1.  配置网关时选择带密码的密钥
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/89773363/150507017-0dab0ed4-69b5-4392-b2c2-75fbad2bfbf7.png">

2.  连接资产时，提示网关连接失败
![image](https://user-images.githubusercontent.com/89773363/150506682-f207ca84-751b-4492-805e-4ebd33764303.png)

3.

**Comment by ibuler** [comment]
暂无支持计划
