### ISSUE TITLE
添加资产以后，特权用户界面测试节点连接性是ok的，但是在资产界面测试可连接性部分连不上[Bug] 

### ISSUE THREAD

**Issue by hryGithub** [jumpserver/jumpserver#7548]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.18.1

**浏览器版本**
chrome 97

**Bug 描述**
添加资产以后，特权用户界面测试节点连接性是ok的，但是在资产界面测试可连接性部分连不上

**Bug 重现步骤(有截图更好)**
1.  特权用户界面测试连接性
![QQ图片20220125102118](https://user-images.githubusercontent.com/32188410/150899542-8f110d7f-8874-4cbc-89ea-c34e193db4b7.png)

2. 资产界面测试可连接性
![QQ图片20220125102234](https://user-images.githubusercontent.com/32188410/150899563-ff261d34-4eeb-41cd-a29a-c8382e9ccddc.png)

**Comment by hryGithub** [comment]
我重新添加了一遍资产，然后现在变成192.168.1.11可以连接，其他机器连不上了
![QQ图片20220125104829](https://user-images.githubusercontent.com/32188410/150901792-d0777c77-2f2e-4308-9877-44113d88dee8.png)

**Comment by wojiushixiaobai** [comment]
系统用户排序有关，已经反馈。

**Comment by hryGithub** [comment]
那我这边临时处理方法是降级版本吗

**Comment by ibuler** [comment]
如果备份了数据库就好办

**Comment by xuxinwen** [comment]
可以留个联系方式吗

**Comment by hryGithub** [comment]
我是新装的，目前安装的2.17.3版本没这个问题

**Comment by hryGithub** [comment]
企鹅：2917518534

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/155105275-b9552b15-2501-486f-8b18-6b7ccca474ac.png)
升级到v2.18.2或者最新版本v2.19.1版本进行测试，新版本已修复

**Comment by u1zz** [comment]
v2.19.1还有这个问题，系统用户和普通用户都只有一个
