### ISSUE TITLE
添加完用户，发用的邮件没有端口号

### ISSUE THREAD

**Issue by meeking1** [jumpserver/jumpserver#755]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2
##### 问题复现步骤
1. [步骤1]新建一个用户的时候发邮件
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/27937590/31529315-030f2d26-b00b-11e7-98b4-0cb3cf4cfcbf.png)
 Hi, wangmq
        您的用户名： wangmq
        您的权限： 普通用户
        您的web登录密码： ia15FQwxddWtbw1u
        您的ssh密钥文件密码： KF_OPzr2pBrCJ1pW
        密钥下载地址： http://192.168.0.101/juser/key/down/?uuid=58ed931a4df44126842e738550ee16c6
        说明： 请登陆跳板机后台下载密钥, 然后使用密钥登陆跳板机！
##### 其他
点击下载的时候是页面错误，要在192.168.0.101后面加上:8000，才可以下载，请问，在哪里可以修改这个配置文件

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/master/jumpserver.conf#L2
