### ISSUE TITLE
[Question]  ssh 登录 可以设置显示组名吗？

### ISSUE THREAD

**Issue by zgfh** [jumpserver/jumpserver#7553]
**请描述您的问题.**
目前ssh 主机类别只有主机名,ip,备注

主机很多的时候比较难搜索
是否可以增加一列 组名？

**Comment by LeeEirc** [comment]
资产没有所谓的` 组名`， 只有 `组织` 和 `节点`。不知道你具体的想显示什么？

**Comment by jym503558564** [comment]
可将资产归类好节点，通过节点搜索。

**Comment by zgfh** [comment]
> 组织

说错了，组织
