### ISSUE TITLE
[Question] Web终端进行输入操作，浏览器卡住，如何排查问题

### ISSUE THREAD

**Issue by LyleLaii** [jumpserver/jumpserver#7554]
进入web终端，敲击回车键即可触发。触发后整个浏览器卡住，包括鼠标点击在内的操作均无响应。切换其他应用程序后，再切回浏览器可以正常交互，但Web终端不可正常使用，输入操作任然会卡住整个浏览器。

观察浏览器console没用任何报错信息，从任务管理器看pc整体无性能问题。

请问是否有类似案例及解决方案或如何进行排查，谢谢。

版本信息
JumpServer Version v2.17.1
Chrome 97.0.4692.71
Edge 97.0.1072.62

**Comment by wojiushixiaobai** [comment]
没有复现，请换个浏览器测试下看看

**Comment by jym503558564** [comment]
无法复现，可微信群联系我们管理员查看一下。
