### ISSUE TITLE
批量支持点了多次后，进程无法结束

### ISSUE THREAD

**Issue by QinQiang666** [jumpserver/jumpserver#7555]
version：v2.13.2
再批量执行的时候（有很多机器），点了多次执行，然后关闭也面后，批量执行的操作不会结束，还是会再后台重复执行，服务重启了也不好使，通过查看 celery_ansible.log 日志，一直再重复执行

**Comment by wojiushixiaobai** [comment]
任务下发后会按照顺序执行，不是关闭页面就会取消

**Comment by QinQiang666** [comment]
> 任务下发后会顺序执行，不是关闭页面必须取消按照

那怎么能结束到这种重复的执行那？
