### ISSUE TITLE
jumpserver无法启动

### ISSUE THREAD

**Issue by kesongyuan** [jumpserver/jumpserver#7558]
版本：v2.18.1
使用一键脚本安装，离线安装
运行时报错
`[root@VM-16-5-centos ~]# cd /opt/jumpserver-installer-v2.18.1
[root@VM-16-5-centos jumpserver-installer-v2.18.1]# ./jmsctl.sh start
jms_redis is up-to-date
jms_mysql is up-to-date
Creating jms_core ... done

ERROR: for koko  Container "8450a49123b0" is unhealthy.

ERROR: for lion  Container "8450a49123b0" is unhealthy.

ERROR: for celery  Container "8450a49123b0" is unhealthy.

ERROR: for web  Container "8450a49123b0" is unhealthy.
ERROR: Encountered errors while bringing up the project.`

**Comment by wojiushixiaobai** [comment]
[查询日志方法](https://docs.jumpserver.org/zh/master/faq/other/#_2)

**Comment by jym503558564** [comment]
@kesongyuan 该问题还存在吗？可将报错的日志信息贴出来，或者微信群联系我们群管理员帮忙处理。
