### ISSUE TITLE
jumpserver2.18.1无法连接阿里云rds

### ISSUE THREAD

**Issue by Changego** [jumpserver/jumpserver#7564]
**JumpServer 版本(v1.5.9以下不再支持)**
2.18.1

**浏览器版本**
火狐

**Bug 描述**
jumpserver2.18.1无法连接阿里云rds

**Bug 重现步骤(有截图更好)**
 error: ERR wrong number of arguments for 'AUTH' command
Receive Connection closed
Connection websocket closed

**Comment by ibuler** [comment]
这是 redis ?

**Comment by Changego** [comment]
是的啊.
