### ISSUE TITLE
[Bug] 命令过滤规则无法选择应用

### ISSUE THREAD

**Issue by ningdaqing** [jumpserver/jumpserver#7569]
JumpServer版本：2.18.1

Bug描述：命令过滤不能选择应用

Bug截图：
![image](https://user-images.githubusercontent.com/29521063/152737744-2949a0f4-f72b-421d-911d-867c384a8aeb.png)

**Comment by jym503558564** [comment]
未复现。有创建系统用户或应用吗

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/152936045-5239a3d0-a922-456a-ba9e-63b50615d086.png)

**Comment by jym503558564** [comment]
该问题还存在吗？

**Comment by jym503558564** [comment]
如果还有问题，可以再次打开Issues。
