### ISSUE TITLE
[Bug] GUI RDP剪贴板 粘贴换行符失效

### ISSUE THREAD

**Issue by gaohonghai** [jumpserver/jumpserver#7570]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.18.1

**浏览器版本**
版本 97.0.4692.99

**Bug 描述**
GUI RDP剪贴板，粘贴换行符失效

**Bug 重现步骤(有截图更好)**
1.  在jms上使用GUI的方式发起RDP连接
2. 打开剪贴板，输入带有换行符的内容。例如下述内容：
123
456
3. 在剪贴板中复制上述内容，在windows中粘贴至记事本。发现粘贴内容展示为123456。如下图所示：
![image](https://user-images.githubusercontent.com/92966838/152739442-9d05208d-e547-4846-98e4-0226c07c6c8b.png)

**Comment by jym503558564** [comment]
从外部复制，剪切板是支持换行的。

**Comment by Fit2CloundGhh** [comment]
您那边剪贴板是可以的？我试了很多遍确实不行呢

**Comment by jym503558564** [comment]
支持外部复制（含换行）。不知道您从剪贴板写入，并复制，这个操作的意义是什么？

**Comment by Fit2CloundGhh** [comment]
是我理解有问题吗，rdp GUI的方式访问，从外部复制内容到远程资产，不是只能通过剪贴板、上传下载吗？现在可以不经过剪切板直接从外部复制进去？

**Comment by Fit2CloundGhh** [comment]
是我理解有问题吗，rdp GUI的方式访问，从外部复制内容到远程资产，不是只能通过剪贴板、上传下载吗？现在可以不经过剪切板直接从外部复制进去？

**Comment by jym503558564** [comment]
跟换行符可能有关系，目前我们没控制这个。
![image](https://user-images.githubusercontent.com/40739051/153113254-9f850182-3af2-4450-a4f0-d8fc1f418c16.png)
如VScode，CRLF复制过来，支持换行。 LF就无法换行。

**Comment by Fit2CloundGhh** [comment]
大佬好，客户的应用场景是这样的，GUI访问windows的时候，需要粘贴多个sql语句，在剪贴板使用换行符换行之后，粘贴到资产记事本或者navicat query界面，发现换行符丢了。

我自己也试了试，直接在咱们剪贴板上输入：

123
456

复制到资产记事本确实是丢了换行符。

按您描述，是可能跟不同平台编码有关系吗？但是已经有先粘贴到咱们剪贴板上，剪贴板上已经展示了有换行符的内容，复制到远程桌面就不行，您看这样能修吗。
