### ISSUE TITLE
jumpserver是否支持redis分片集群配置[Question] 

### ISSUE THREAD

**Issue by penngke** [jumpserver/jumpserver#7576]
**请描述您的问题.**
jumpserver使用redis，是否支持redis的分片+副本集的集群模式？

**Comment by wojiushixiaobai** [comment]
vip 形式的集群应该没问题
如阿里云的 redis 集群版本

注意：
因为 redis 6.0 版本新增了账号密码认证功能， JumpServer 目前只支持密码的认证，尚不支持带用户的密码身份认证。

**Comment by abelyang** [comment]
> vip 形式的集群应该没问题 如阿里云的 redis 集群版本
> 
> 注意： 因为 redis 6.0 版本新增了账号密码认证功能， JumpServer 目前只支持密码的认证，尚不支持带用户的密码身份认证。

预计什么时间能支持带用户名和密码的身份认证呢？

**Comment by wojiushixiaobai** [comment]
已在计划中，目前尚未有准确的时间，但是会尽快支持

**Comment by penngke** [comment]
谢谢回复，期待支持！
