### ISSUE TITLE
怎么配置非/的反向代理

### ISSUE THREAD

**Issue by csrlsm** [jumpserver/jumpserver#7585]
**请描述您的问题.**
我需要通过现有的nginx-proxy进行代理jumpserver，但目前location / {}已代理其他系统，需要使用location /jumpserver {}进行代理jms，但配置一直返回404，提示找不到/jumpserver/api/xxx

**Comment by jym503558564** [comment]
反向代理参考https://docs.jumpserver.org/zh/master/admin-guide/proxy/?h=%E5%8F%8D%E5%90%91

**Comment by wojiushixiaobai** [comment]
用其他二级域名，不要与其他现有域名冲突，或者使用当前域名的其他端口
