### ISSUE TITLE
[Bug] 在线文档中的部分截图是 v1.4.9 版本的，太老了。

### ISSUE THREAD

**Issue by maninhill** [jumpserver/jumpserver#7586]
主要集中在【用户文档】这个章节，比如 https://docs.jumpserver.org/zh/master/user-guide/assets/user-asset/

![image](https://user-images.githubusercontent.com/41712985/153119189-1b2eb853-37fa-42a8-82e7-e3455d24908a.png)

**Comment by jym503558564** [comment]
好的，感谢反馈。我们将进行更改～
