### ISSUE TITLE
镜像拉取慢

### ISSUE THREAD

**Issue by duanzhanling** [jumpserver/jumpserver#759]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本0.4.0]
jumpserver/jumpserver:v0.4.0-beta1
jumpserver/coco:v0.4.0-beta1
jumpserver/luna:v0.4.0-beta1

这三个镜像拉取很慢，建议在阿里云上搞下镜像，而且最新的安装文档看了，对于docker和docker-compose的安装这块没有，建议改进下

**Comment by ibuler** [comment]
Get it
