### ISSUE TITLE
项目路径移动服务就无法正常访问了

### ISSUE THREAD

**Issue by zhuima** [jumpserver/jumpserver#76]
主要影响的是/usr/lib/python2.6/site-packages/django/template/loader.py in find_template, line 131
查询不到templates，导致项目移动路径就出现无法正常加载静态文件的问题

**Comment by ibuler** [comment]
不会啊， templates是在项目里的，不会影响的
如果说影响则原来影响的是 /etc/profile.d/zzjumpserver.sh，现在已经改变思路了，此问题也不会出现
