### ISSUE TITLE
从docker-compose安装 服务起来后 请问如何配置邮件服务功能

### ISSUE THREAD

**Issue by zwx168238** [jumpserver/jumpserver#760]
[从docker-compose安装 服务起来后 请问如何配置邮件服务功能]

##### 使用版本
 0.4.0

##### 问题复现步骤
1. 下载项目代码
2. docker-compose up -d 
3.服务运行正常，新建用户后无邮件提示

**Comment by ibuler** [comment]
可以把配置文件copy出来，然后修改，修改完成后，运行docker时挂载上去

**Comment by zwx168238** [comment]
好的 我尝试下
