### ISSUE TITLE
[Bug] 使用网关链接内容，测试链接和获取硬件资源失败

### ISSUE THREAD

**Issue by lazychanger** [jumpserver/jumpserver#7600]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-installer-v2.18.1
**浏览器版本**
Google Chrome
版本 98.0.4758.80（正式版本） (x86_64)
**Bug 描述**
````
TASK [setup] *******************************************************************
fatal: [xxxxxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host\r\nConnection closed by UNKNOWN port 65535", "unreachable": true}
PLAY RECAP *********************************************************************
xxxxxx                   : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
获取资产信息失败：xxxxxx
Task assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_manual[9c1dd6e1-b144-4738-91be-ca15a0978384] succeeded in 0.15452511499461252s: None
````
**Bug 重现步骤(有截图更好)**
1.  创建SSH网关
2. 创建资源选择第一步网关
3. 测试链接、获取硬件资源失败。弹窗出现“ UNKNOWN port 65535”

**注：在WEB终端中，该节点可以链接上。仅仅只是测试链接和获取硬件资源失败。**

**Comment by wojiushixiaobai** [comment]
换个端口试试？

**Comment by lazychanger** [comment]
都有试过了。网关端口是10022，资源端口是22。web终端中可以连接，但是测试连通性和获取硬件资源不行

**Comment by wojiushixiaobai** [comment]
没法复现，我这边测试没问题

**Comment by lazychanger** [comment]
这就很尴尬，我这边一直复现。
虽然不影响使用。先挂着吧

**Comment by ibuler** [comment]
端口对的上吗？

**Comment by lazychanger** [comment]
报错显示`UNKNOWN Port 65535`，我自己的网关和资产都和这个无关呀。我在WEB终端连接是可以的，

**Comment by ibuler** [comment]
那肯定是哪里配置错了，这个端口应该是网关的端口

**Comment by lazychanger** [comment]
如果配置错啦。WEB终端那边页应该连接不上才对。不是嘛？

**Comment by ibuler** [comment]
截图一下网关的信息，看一下

**Comment by lazychanger** [comment]
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/20916944/154037139-816da271-b590-4ed4-8bea-b5e9d3e53cc5.png">

**Comment by ibuler** [comment]
这样测试一下，测试连接的时候，去 core 容器中 看看 ansible 的命令

```
# docker exec -it jms_core bash
# ps aux | grep sshpass

```

**Comment by lazychanger** [comment]
确定是这样执行的嘛？
显示结果里面没有这些

<img width="702" alt="image" src="https://user-images.githubusercontent.com/20916944/154178528-6f3ffe93-0fb6-4136-b33a-add10507e07c.png">

**Comment by ibuler** [comment]
执行任务的过程中

**Comment by lazychanger** [comment]
出现标题错误时候。您给的命令没有显示出任何内容。

**Comment by ibuler** [comment]
点击测试后，立刻去 执行那个命令

**Comment by lazychanger** [comment]
没有东西

<img width="657" alt="image" src="https://user-images.githubusercontent.com/20916944/154187321-30f64cc7-56db-4a4d-b60e-a8442abad2cc.png">

**Comment by ibuler** [comment]
必须在执行那个任务的时候，还没有结果前，这里才能看到

**Comment by lazychanger** [comment]
您可以看到我是一直在刷的呀。另外一边也是在跑。好几次尝试都没有刷出来呀

**Comment by ibuler** [comment]
好吧，要不以后遇到了再处理？

**Comment by killinitzero** [comment]
网域中配置的网关的系统版本太低会导致这个问题，把网关换成高系统版本则解决这个问题
