### ISSUE TITLE
[Question] 推送资产失败 提示Invalid/incorrect password: Permission denied

### ISSUE THREAD

**Issue by wanglong168** [jumpserver/jumpserver#7602]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.18.0

**浏览器版本**
chrome 97

**Bug 描述**
升级后推送资产出现账号密码错误 连不上资产 之前在2.17.0还可以，升级到2.18.0出现该问题

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/78788958/153541424-9bbe3d84-738c-4da6-ba2f-2280dfa81816.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
更新到 v2.18.2 即可

**Comment by XingTom** [comment]
遇到同样问题，请问怎么解决的呢，谢谢
