### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by assasinwang** [jumpserver/jumpserver#7603]
**请描述您的问题.**
你好，关于中文乱码的问题，有办法可以解决吗:
1.ssh 连接Windows中文乱码
![image](https://user-images.githubusercontent.com/48608067/153562434-01bc6fb1-c9aa-488f-8225-826f3ef74ddd.png)
![Windows ssh中文乱码](https://user-images.githubusercontent.com/48608067/153561544-fc5316ac-6603-4280-94b3-e6010f54c679.png)

2.vnc 连接Windows，从外部粘贴中文乱码，已测试chrome版本 98.0.4758.82(正式版本)(64 位)和firefox 97.0 (64 位)
![vnc剪贴板从外部粘贴](https://user-images.githubusercontent.com/48608067/153561987-a2c94b26-b151-44c8-ac0e-4dfb45f954b9.png)

3.vnc 连接Windows，从内部复制中文乱码，已测试chrome版本 98.0.4758.82(正式版本)(64 位)和firefox 97.0 (64 位)
![vnc剪贴板从内部复制](https://user-images.githubusercontent.com/48608067/153562117-4d28ea08-74da-4859-8a78-fe4a9f50ee25.png)

**Comment by wojiushixiaobai** [comment]
资产管理 - 系统平台可以修改编码。

**Comment by assasinwang** [comment]
一共两个编码可选，都试过。还是不行
![image](https://user-images.githubusercontent.com/48608067/153788715-0ea2488b-86d3-48a4-9b00-90baefeeae4e.png)
