### ISSUE TITLE
install 目录下没有install.py脚本

### ISSUE THREAD

**Issue by navyaijm2017** [jumpserver/jumpserver#761]
[简述你的问题]

##### 使用版本
最新版本

##### 问题复现步骤
cd /opt
git clone https://github.com/jumpserver/jumpserver.git
cd jumpserver/install/
./install.py #没有这个脚本
##### 其他

[注:] 完成后请关闭 issue

**Comment by hellorocky** [comment]
如果安装0.3.2请切换到master分支
