### ISSUE TITLE
鼠标放在窗口边缘想改变大小，但是鼠标样式不会改变

### ISSUE THREAD

**Issue by jeahoonchen** [jumpserver/jumpserver#7612]
将把鼠标放在窗口边缘的时候，想通过拖动改变窗口大小，可以实现，但是问题是，鼠标放到窗口边缘时，它的样式不会改变成双箭头的样式，导致很难判断鼠标是否到了可拖动的区域，请问这个有解决办法吗？

**Comment by wojiushixiaobai** [comment]
因为不是使用远程的鼠标，所以会有此问题，暂时没有更好的解决方法。

**Comment by jeahoonchen** [comment]
了解了，谢谢
