### ISSUE TITLE
[Question] 如何通过jumpserver管理Windows虚机

### ISSUE THREAD

**Issue by rait-winter** [jumpserver/jumpserver#7616]
**请描述您的问题.**
jumpserver管理Windows机器，需要看到桌面，现可利用下载openssh软件，连接到命令行

**Comment by ibuler** [comment]
能用远程桌面连接吗

**Comment by rait-winter** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Question] 如何通过jumpserver管理Windows虚机 (Issue #7616)




 
能用远程桌面连接吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ibuler** [comment]
那应该是支持的啊，填写 ip 端口，账号密码就行

**Comment by rait-winter** [comment]
web端可以桌面式访问，现在是命令行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月17日(周四) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Question] 如何通过jumpserver管理Windows虚机 (Issue #7616)




 
那应该是支持的啊，填写 ip 端口，账号密码就行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongfo** [comment]
目前已经通过openssh自动推送用户，完成登录window服务器的动作，但是推送的用户权限过低，无法管理IIS站点。导致该实际上失去意义。

**Comment by rait-winter** [comment]
你好，有没有web管理Windows相关配置说明或者演示。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Question] 如何通过jumpserver管理Windows虚机 (Issue #7616)




 
目前已经通过openssh自动推送用户，完成登录window服务器的动作，但是推送的用户权限过低，无法管理IIS站点。导致该实际上失去意义。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dongfo** [comment]
> 目前已经通过openssh自动推送用户，完成登录window服务器的动作，但是推送的用户权限过低，无法管理IIS站点。导致该实际上失去意义。

在另一个回答里找打解决方法了 #7518 
可以实现admin登录
