### ISSUE TITLE
1.4.4升级到新版本后系统管理员无法显示资产

### ISSUE THREAD

**Issue by opslx** [jumpserver/jumpserver#7617]
**请描述您的问题.**
1.4.4升级到2.16.3后普通用户使用正常，系统管理员不显示资产
管理员:
![image](https://user-images.githubusercontent.com/50452206/154021277-5557203d-4e77-4ed6-b0a0-09fed97deeee.png)
普通用户:
![image](https://user-images.githubusercontent.com/50452206/154021356-d4936578-afc0-4717-a6a3-3b2d67cf6093.png)

**Comment by ibuler** [comment]
重启一下，应该是缓存问题

**Comment by opslx** [comment]
不行，用户什么的都不显示，普通用户用起来一切正常
![image](https://user-images.githubusercontent.com/50452206/154032925-899745da-3059-4f9d-b7ca-b4b457b98435.png)

**Comment by ibuler** [comment]
qq群里联系一下我吧（老广），远程看下

**Comment by ibuler** [comment]
邮件也行  ibuler#fit2cloud.com

**Comment by wojiushixiaobai** [comment]
应该是之前修改过默认的根节点导致的。

**Comment by opslx** [comment]
降级到2.11后正常，2.12就不行，先用2.11了
![Uploading image.png…]()
