### ISSUE TITLE
搜索主机时出现很多重复的主机名

### ISSUE THREAD

**Issue by jiangping20160209** [jumpserver/jumpserver#762]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2]

##### 问题复现步骤
1. [步骤1] 添加了一个资产组 包含了所有机器
2. [步骤2]点击查看资产 搜索主机名时出现了很多重复的主机名

**Comment by ibuler** [comment]
0.3.2小bug不再修复
