### ISSUE TITLE
[Question] 如何多标签查询资产

### ISSUE THREAD

**Issue by xuchenCN** [jumpserver/jumpserver#7628]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/2757089/154395518-4d767335-dd85-42ec-ac09-1f5164660da2.png)

搜索框选择标签，输入内容只能查询一个标签，再次选择标签会被替换掉，如何多标签联合查询？

谢谢！

**Comment by ibuler** [comment]
暂时还不支持，我们研究一下，后端 api 貌似也不支持
