### ISSUE TITLE
4.0版本 ldap配置问题以及系统用户推送以及邮件的问题

### ISSUE THREAD

**Issue by yuxinmiaomiao** [jumpserver/jumpserver#763]
1 ： 4.0版本ldap功能
-------------------------------------------------------------------------------
 # LDAP Auth settings
    AUTH_LDAP = True
    AUTH_LDAP_SERVER_URI = 'ldap://XX.XX.XX.XX:389'
    AUTH_LDAP_BIND_DN = 'cn=admin,dc=XXXXXX,dc=cn'
    AUTH_LDAP_BIND_PASSWORD = 'XXXXXXX'
    AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,dc=jumpserver,dc=org"
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "cn",
        "name": "sn",
        "email": "mail"
    }
    AUTH_LDAP_START_TLS = False

    def __init__(self):
        pass

    def __getattr__(self, item):
        return None
-------------------------------------------------------------------------------
配置如上（不知道怎么上传图片）XXX替代的配置没有问题；重启服务之后，在ldap模块上更改面之后，其他使用ldap的平台 比如 owncloud密码都改成功了 但是jumpserver不行，请问是哪里的问题，是配置文件有问题 还是有其他地方也需要修改？

2： 4.0版本系统用户推送
4.0版本系统用户推送之后 在关联的资产里 可连接状态是红X的状态，服务器上也没有创建的系统用户（没有成功推送），有人问过这个问题 但是没有得到解决

3: 4.0版本不能邮件
邮件配置如下（不知道在哪上传图片）
----------------------------------------------
EMAIL_HOST = 'smtp.exmail.qq.com'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = 'jumpserver@XXXXX.cn'
    EMAIL_HOST_PASSWORD = '12345678'
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = False
    EMAIL_SUBJECT_PREFIX = '[Jumpserver] '
    SITE_URL = 'http://XXXXXXX:8080'
--------------------------------------------
我之前搭建的3,x版本的配置是这样的 可以发送邮件，但是4.0的不行  看报错是提示认证不对；但是配置文件里写的邮件和密码是正确的，费解ing...

**Comment by zwx168238** [comment]
我直接从docker-compose启动的 不知道怎么配置邮件 请问你邮件配置的部分是写在哪里啊

**Comment by yuxinmiaomiao** [comment]
@zwx168238 我这个邮件配置就是在jumpserver 的配置文件上的啊 /opt/jumpserver/config.py 就这个

**Comment by wocswang** [comment]
我也是配置成功后，创建新用户不发邮件是怎么回事啊

**Comment by wocswang** [comment]
@zwx168238 我也是邮件这不发邮件，从后台看邮件内容都产生了就是不发送，你解决了吗

**Comment by zwx168238** [comment]
没有

**Comment by gengkeye** [comment]
我的生产环境中系统用户也没有推送成功（显示是成功了），但是开发环境中是可以成功推送的。

**Comment by stillmanwang** [comment]
@yuxinmiaomiao 大哥你现在ldap是集成成功了吗？求指导下啊。

**Comment by ibuler** [comment]
ldap新版本支持 系统设置来完成
