### ISSUE TITLE
[云管中心资产同步建议] 

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#7632]
云管中心在做资产同步时候，1、是否可以按照资产的主机名进行规则匹配，目前好像只能通过IP进行过滤，无法从业务的维度对服务器进行组划分；2、或者同步资产的时候可以进行标签的选择，云上的服务器是有业务标签的，这样服务器就可以根据业务需求同步到不同的节点了。

**Comment by wojiushixiaobai** [comment]
收到，等待内部讨论后回复。

**Comment by w7374520** [comment]
只需要提供apikey， 就能够自动同步阿里云、腾讯云、aws就更好了，就能纳管很多资源。。。。简化了资产管理，扩大了用户的受用量
