### ISSUE TITLE
[Bug]  ssh终端不支持 CAS 方式认证

### ISSUE THREAD

**Issue by charles-liming** [jumpserver/jumpserver#7634]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
使用iterm2 或者SEcurecrt ssh 连接jump 2222 一直提示 认证的密码错误

**Bug 重现步骤(有截图更好)**
1.  
<img width="642" alt="image" src="https://user-images.githubusercontent.com/34326414/154449003-e533e57b-2d1d-4ac5-8181-0c4cc497481f.png">

2. 
3.

**Comment by wojiushixiaobai** [comment]
ssh 暂时不支持第三方认证，只有 web 支持

**Comment by ibuler** [comment]
打算支持一下，我们是这么考虑的，你看看行不行

用户ssh登录，发现用户是cas，会提示用户使用 token 登录，用户点击 url 地址，从页面上创建一个一次性token 来完成登录，这个 token 依附于登录的会话

**Comment by charles-liming** [comment]
目前看，我这边测试 ssh 走的ssh 密钥认证，可以直接完成认证，并出现一下界面




这个目前是可以使用的，看起来没有cas逻辑，不过这样也可以使用










在 2022-02-18 11:43:37，"parry" ***@***.***> 写道：

目前看起来可以，不用单独支持，我待会放截图


Get Outlook for Android

**Comment by ibuler** [comment]
用 Public key 也行

**Comment by ibuler** [comment]
那就暂时这样

**Comment by charles-liming** [comment]
反复思索后，还是建议支持下ssh 的cas 认证，要不然有10台电脑就需要更细10台电脑的密钥

**Comment by charles-liming** [comment]
> 打算支持一下，我们是这么考虑的，你看看行不行
> 
> 用户ssh登录，发现用户是cas，会提示用户使用 token 登录，用户点击 url 地址，从页面上创建一个一次性token 来完成登录，这个 token 依附于登录的会话

希望你们看下，这个是不是可以处理
