### ISSUE TITLE
搜索主机时出现重复的主机名

### ISSUE THREAD

**Issue by jiangping20160209** [jumpserver/jumpserver#764]
[简述你的问题]
使用版本

[请提供你使用的Jumpserver版本 0.3.2]
问题复现步骤

    [步骤1] 添加了一个资产组 包含了所有机器
    [步骤2]点击查看资产 搜索主机名时出现了很多重复的主机名

**Comment by choldrim** [comment]
重复 https://github.com/jumpserver/jumpserver/issues/762
