### ISSUE TITLE
[Feature] 用户列表数据显示不全

### ISSUE THREAD

**Issue by QHxiang** [jumpserver/jumpserver#7647]
**请描述您的需求或者改进建议.**
数据库里面表users_user表里面的用户可以登录，但是在web用户列表里面找不到相应的用户。建议修复下这部分功能。
![image](https://user-images.githubusercontent.com/21072348/154657030-d2427023-09e3-48ec-8e1c-c5568d073239.png)
这个页面用户信息有缺失

**Comment by ibuler** [comment]
也就是数据库有这个用户，列表上看不到

**Comment by wojiushixiaobai** [comment]
直接从数据库添加的用户，注意组织id需要填写

**Comment by QHxiang** [comment]
我们的用户是直接从ladp同步的

**Comment by QHxiang** [comment]
> 也就是数据库有这个用户，列表上看不到

是的

**Comment by ibuler** [comment]
之前版本有这个bug，ldap导入时用户没导入到默认组织，稍后附上办法

**Comment by QHxiang** [comment]
> 稍后附上办法

是用什么办法啊
