### ISSUE TITLE
新建用户发送的邮件中有错误

### ISSUE THREAD

**Issue by xwzjx521** [jumpserver/jumpserver#765]
[简述你的问题]
新安装的jumpserver 安装法法是 git + git checkout master + python install.py 
创建用户发送的邮件中 密码下载地址中，地址不带端口。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
Version 0.3.2 GPL.
##### 问题复现步骤
1. [步骤1]：新建用户。保存
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/30651807/31655405-641f2bc6-b2ee-11e7-9651-0ca86800c74d.png)
![image](https://user-images.githubusercontent.com/30651807/31655609-08c77a98-b2ef-11e7-8b3e-151af694a4ef.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by xwzjx521** [comment]
![image](https://user-images.githubusercontent.com/30651807/31655469-94b1f6ba-b2ee-11e7-9cb2-b572346b170c.png)

**Comment by wocswang** [comment]
你好，你的这个邮件怎么弄的，我配置完成后添加新用户不发送邮件，邮件内容都产生了可以从后台看就是不发送

**Comment by hellorocky** [comment]
@wocswang 看日志

**Comment by wocswang** [comment]
从后台日志内容都产生出来了但是就是发送不了，详细信息附件了帮我看看谢谢





在 2017-10-18 14:58:27，"中国娃" <notifications@github.com> 写道：


@wocswang 看日志

**Comment by wocswang** [comment]
这个是我那个jumpserver的config.py文件配置，看看配置的对吗，附件详情





在 2017-10-18 14:58:27，"中国娃" <notifications@github.com> 写道：


@wocswang 看日志

**Comment by ibuler** [comment]
请测试 0.5.0版本
