### ISSUE TITLE
4.0如何部署到生产环境

### ISSUE THREAD

**Issue by wocswang** [jumpserver/jumpserver#766]
4.0版本如何部署到生产环境啊，利用nginx+uwsgi，或者别的方案也行。还有就是部署完成后跳转页面有点慢，是不是没有用服务部署的原因啊

**Comment by ibuler** [comment]
刚开始可能是因为 js,css较大导致比较慢，浏览器缓存后就没问题了

**Comment by choldrim** [comment]
@wocswang 我用的是nginx。
两台机器部署jumpserver + coco，用腾讯云上的CLB做高可用

**Comment by wocswang** [comment]
你好，你部署的时候有没有遇到添加用户时发送邮件失败的现象




在 2017-10-20 16:14:10，"Caijun" <notifications@github.com> 写道：


@wocswang 我用的是nginx。
两台机器部署jumpserver + coco，用腾讯云上的CLB做高可用

**Comment by ibuler** [comment]
速度比较慢的原因是引用了 network.css的 js，需要翻墙，已处理
