### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by charles-liming** [jumpserver/jumpserver#7662]
**请描述您的需求或者改进建议.**
jumpserver 资产列表下的系统用户，分成普通用户跟特权用户，想法本来没有问题，但是分开后，特权用户仅支持ssh 协议，感觉是不是没有想明白，我理解上 作为系统用户，普通用户跟特权用户的类型，是相同的，特权用户也需要普通用户一样的多协议类型支持，而不仅仅是ssh，这是我的思考，还请官方的同学辛苦给予解答。

**Comment by wojiushixiaobai** [comment]
ssh协议才需要特权用户。
其他协议不需要特权用户。

**Comment by charles-liming** [comment]
你好，我觉着特权用户跟协议本身没有关系吧，所以能说下咱们的逻辑吗比如win 有admin 也可以有其他普通用户。 发件人: ***@***.*** ***@***.***> 代表 吴小白 ***@***.***>日期: 星期二, 2022年2月22日 下午2:14收件人: jumpserver/jumpserver ***@***.***>抄送: charles-liming ***@***.***>, Author ***@***.***>主题: Re: [jumpserver/jumpserver] [Feature] (Issue #7662)ssh协议才需要特权用户。其他协议不需要特权用户。—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
