### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by LHB6540** [jumpserver/jumpserver#7664]
**请描述您的问题.**
V2.3.0 版本是否支持升级至 V2.19.1版本？

原先生产环境中使用的是编译安装的V2.3.0版本，现在尝试拷贝数据至一台机器测试升级。

尝试一：参考此文档升级https://docs.jumpserver.org/zh/master/install/migration/
在此步骤出错
` [root@VM-1-12-centos jumpserver-installer-v2.19.1]# ./jmsctl.sh restore_db /data/setup/jumpserver-v2.3.0/jumpserver.sql
Start restoring database: /data/setup/jumpserver-v2.3.0/jumpserver.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 3780 (HY000) at line 94: Referencing column 'asset_id' and referenced column 'id' in foreign key constraint 'applications_remoteapp_asset_id_e04045e6_fk_assets_asset_id' are incompatible.
[ERROR] Database recovery failed. Please check whether the database file is complete or try to recover manually!`
即数据库ORM升级迁移时出错
疑问：V2.3.0 版本是否支持升级至 V2.19.1版本？数据库结构能否正常Migrate

尝试二：先在测试环境中使用installer方式重新部署一次，再参考此文档进行升级。https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/
但是无法找到V2.3.0的installer的包，尝试从
https://github.com/jumpserver/installer/releases/download/v2.3.0/jumpserver-installer-v2.3.0.tar.gz 获取installer，提示无该文件
疑问：能否提供V2.3.0的installer安装方式

**Comment by wojiushixiaobai** [comment]
检查下字符集是否有问题

**Comment by LHB6540** [comment]
> Referencing column 'asset_id' and referenced column 'id' in foreign key constraint 'applications_remoteapp_asset_id_e04045e6_fk_assets_asset_id' are incompatible.
这里提示的是外键变了，不是编码问题，编码都是UTF8
`Referencing column 'asset_id' and referenced column 'id' in foreign key constraint 'applications_remoteapp_asset_id_e04045e6_fk_assets_asset_id' are incompatible.`

**Comment by jym503558564** [comment]
群里联系我们管理员，远程协助看一下
