### ISSUE TITLE
[Question] docker版2.4.3升级2.19.1 无法使用web终端内的服务器无法正常登录显示502

### ISSUE THREAD

**Issue by leon8693** [jumpserver/jumpserver#7683]
jumpserver 版本 2.4.3 docker方式安装
准备升级至2.19.1
#参考的是如下的文档docker版
https://docs.jumpserver.org/zh/master/install/migration/
2.19.1的安装和SECRET_KEY,BOOTSTRAP_TOKEN,都没异常
正常也可以登录主页面
但是选择web终端,选择要登录的服务器后出现502

KoKo报错如下
2022/02/23 16:45:51 &{Name:[KoKo]test05-2e039570f040 CoreHost:http://core:8080 BootstrapToken:xxxxxxxxx BindHost:0.0.0.0 SSHPort:2222 HTTPPort:5000 SSHTimeout:15 LogLevel:ERROR Comment:KOKO LanguageCode:zh UploadFailedReplay:true AssetLoadPolicy: ZipMaxSize:1024M ZipTmpPath:/tmp ClientAliveInterval:30 RetryAliveCountMax:3 ShowHiddenFile:false ReuseConnection:true ShareRoomType:local RedisHost:redis RedisPort:6379 RedisPassword:xxxxxxxxxxx RedisDBIndex:0 RedisClusters:[] EnableLocalPortForward:false EnableVscodeSupport:false RootPath:/opt/koko DataFolderPath:/opt/koko/data LogDirPath:/opt/koko/data/logs KeyFolderPath:/opt/koko/data/keys AccessKeyFilePath:/opt/koko/data/keys/.access_key ReplayFolderPath:/opt/koko/data/replays}
2022-02-23 16:45:51 [ERRO] Access key unauthorized, try to register new access key
2022-02-23 16:45:51 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}

![image](https://user-images.githubusercontent.com/2100865/155287700-21c8ac94-730f-4034-b9a1-48be8e342fb2.png)

但是从/opt/jumpserver/config/config.txt 配置文件看
SECRET_KEY 和 BOOTSTRAP_TOKEN 确认已更替成老的2.4.3版本的key

![image](https://user-images.githubusercontent.com/2100865/155441100-c280a1a0-52dc-46c5-aba6-3e157a21478f.png)

**Comment by leon8693** [comment]
已解决,参考: https://github.com/jumpserver/jumpserver/issues/4347
![image](https://user-images.githubusercontent.com/2100865/155452284-a5bd2626-b668-43a6-8384-fd26ee1eda53.png)
建议官方将这个注意事项加入到文档中,毕竟迁移不是经常迁的。

**Comment by jym503558564** [comment]
好的，感谢反馈～
