### ISSUE TITLE
[Bug] 命令记录无法根据资产名称过滤

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#7685]
**JumpServer 版本(v1.5.9以下不再支持)**
2.19.1

**浏览器版本**

**Bug 描述**
命令记录无法根据资产名称过滤

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44529247/155329329-c4e7f030-6a11-4cff-9fc7-0ea5e35901ae.png)
![image](https://user-images.githubusercontent.com/44529247/155329414-d98608d1-7442-460d-a0d2-65973182744a.png)

3.

**Comment by wojiushixiaobai** [comment]
你搜索错了，你应该用模糊搜索。
精确搜索需要资产命令+资产ip
![image](https://user-images.githubusercontent.com/24326988/155468023-6234a0f5-f10b-4cce-b49f-9eea3f520180.png)
