### ISSUE TITLE
版本4.0中ssh密钥不合法

### ISSUE THREAD

**Issue by wangchongsheng** [jumpserver/jumpserver#769]
[简述你的问题]

##### 使用版本
Jumpserver版本 0.4.0

##### 问题复现步骤
1. 点击资产管理-->管理用户-->创建管理用户--->提交
2.报错：ssh密钥不合法

我应该使用什么格式的密钥或者有什么具体操作步骤,
我使用的私钥是PPK格式的

**Comment by wangchongsheng** [comment]
版本4.0中ssh密钥不合法

**Comment by choldrim** [comment]
rsa 的可以

**Comment by ibuler** [comment]
rsa或dsa格式

**Comment by skyrim61** [comment]
ssh-keygen -t rsa
