### ISSUE TITLE
[Question] 系统用户使用秘钥认证方式登入资产设备，会弹出输入密码，密码错误两次后，才会使用秘钥方式登入资产

### ISSUE THREAD

**Issue by anatsking** [jumpserver/jumpserver#7695]
**请描述您的问题.**
版本2.19.1
系统用户-认证
认证方式密码，密码为空，SSH秘钥导入正确秘钥，秘钥密码为空
![image](https://user-images.githubusercontent.com/77421006/155636897-1a10d470-9481-4e60-b071-4222cede1691.png)
配置好，登入资产时，会弹出“Password:”输错或者直接回车两次后，第三次登入（不需要输入密码或回车）到设备
![image](https://user-images.githubusercontent.com/77421006/155637050-db876820-1c7c-43e3-a138-eee742129ff5.png)

**Comment by jym503558564** [comment]
vi /etc/ssh/sshd_config
# 禁用 ChallengeResponseAuthentication 
ChallengeResponseAuthentication no

重启sshd
systemctl restart sshd

**Comment by anatsking** [comment]
完美解决，感谢
