### ISSUE TITLE
资产授权过期后WEB界面资产数量与资产不对应

### ISSUE THREAD

**Issue by ML-mulan** [jumpserver/jumpserver#7698]
JumpServer-V2.19.1

chromre&safari均显示有问题

描述：授权a、b、c三台机器给用户test,授权到期后，web终端查看的机器数量为3，但实际显示的资产只有两台。

截图：
1、授权2条，资产数量3，第1条已过期：
![11 pic](https://user-images.githubusercontent.com/85107494/155696539-da6e51a0-ecea-44c2-9bd3-1016468d5a25.jpg)

2、web端查询异常：

<img width="903" alt="image" src="https://user-images.githubusercontent.com/85107494/155696468-3514eba4-6066-4122-bc0a-e6ddb73d2917.png">

**Comment by ibuler** [comment]
@jym503558564 看看是不是缓存的bug

**Comment by ML-mulan** [comment]
应该不是，清除缓存强制刷新都没用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] 资产授权过期后WEB界面资产数量与资产不对应 (Issue #7698)





 
@jym503558564 看看是不是缓存的bug
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jym503558564** [comment]
无法复现
