### ISSUE TITLE
命令统计出现乱码现象

### ISSUE THREAD

**Issue by nice-jj** [jumpserver/jumpserver#770]
在使用rz上传文件时，命令统计出现乱码，并在上传文件之后，命令无法再记录

##### 使用版本
0.3.2

##### 问题复现步骤
1. 使用jumpserver登录一台服务器，执行命令之后，命令统计中正常显示
2. 使用rz 上传文件，命令统计中出现乱码，上传文件后再执行命令，命令统计中无法显示执行rz命令后所执行的命令

##### 具体表现
执行rz命令前的录像截图
![qq 20171020103543](https://user-images.githubusercontent.com/25783795/31802870-352f615e-b583-11e7-8649-4fe399556c1b.png)

执行rz命令后的录像截图
![qq 20171020103643](https://user-images.githubusercontent.com/25783795/31802877-3a678746-b583-11e7-9e61-603bbf65c02f.png)

执行rz命令前的命令统计截图
![qq 20171020103919](https://user-images.githubusercontent.com/25783795/31802881-3e9e01f0-b583-11e7-92dd-b34daa74965f.png)

执行rz命令后的命令统计截图
![qq 20171020104027](https://user-images.githubusercontent.com/25783795/31802886-42937696-b583-11e7-829f-7e2fd6d847ad.png)

**Comment by ibuler** [comment]
嗯，这个bug确实存在，用户使用rz,sz等命令也会记录分析

**Comment by nice-jj** [comment]
@ibuler 请问有解决办法吗？

**Comment by ibuler** [comment]
不好解决
