### ISSUE TITLE
[Question] OIDC认证问题，提示Server error occur

### ISSUE THREAD

**Issue by Gianthard-XYZ** [jumpserver/jumpserver#7701]
**请描述您的问题.**
大家好，想跟大家请教一下，我配置了OIDC方式认证，在跳转至OIDC服务器这边登录后，跳转回来时提示：
Server error occur, contact administrator

跳转回来的URL类似：https://设备域名/core/auth/openid/callback/?code=ce62b7e2d4c43a9fd704536468405b67&state=WJK9StmyZMad6HkWBj0Al5nzzBIGvp5o

请问这是什么情况？应该如何处理？

谢谢大家。

**Comment by wojiushixiaobai** [comment]
根据 core 日志排查下错误
