### ISSUE TITLE
[Feature] Luna 改进建议

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#7702]
**请描述您的需求或者改进建议.**
1. 支持在Luna右键菜单复制资产名称
![image](https://user-images.githubusercontent.com/11138015/155832171-ca117cb8-d399-4712-913b-331829667c15.png)
![image](https://user-images.githubusercontent.com/11138015/155832182-307940c5-4af9-40f2-ab60-5e90c94e560e.png)
2. 终端标签页能自适应长度。
举例：资产名称是AA_BB_CC_DD_EE_FF，但由于标签长度限制，只能展示AA_BB_CC，而这个前缀是公共前缀，无法通过该前缀分辨当前连接的是哪个资产。
![image](https://user-images.githubusercontent.com/11138015/155832215-f20194f4-9702-4bdb-900d-f0dc08df81ac.png)

**Comment by ibuler** [comment]
Luna 后续考虑使用 vscode 重构
