### ISSUE TITLE
[Bug] 任务输出弹出窗口输出看不到内容

### ISSUE THREAD

**Issue by sfs77** [jumpserver/jumpserver#7721]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.19.1， 两节点高可用部署，外部数据库和nfs

**浏览器版本**
Chrome 98.0.4758.109 , macos 12.1, Apple M1

**Bug 描述**
测试资产连接性，推送系统用户等celery的任务，任务输出弹出窗口输出看不到内容
不论是在实时执行任务的弹窗，还是“任务列表”里面查看任务的输出

**Bug 重现步骤(有截图更好)**
<img width="896" alt="image" src="https://user-images.githubusercontent.com/22687848/156293767-0391afe6-fe46-413f-aeca-ca9718b7399d.png">

**Comment by sfs77** [comment]
关闭一个节点，保留一个节点运行，触发task后仍然看不到输出
NFS正常工作和共享
从v2.18.1升级，v2.18.1没遇到过这个问题

**Comment by sfs77** [comment]
我再自己部署两个版本试一下，排除一下其他因素

**Comment by sfs77** [comment]
试了2.18.1也不行了，这个任务日志是websocket的，和云厂商的LB配置有关吗？  但是我这边站内信的ws又是正常的

**Comment by sfs77** [comment]
目前测试下来好像和redis版本有关，云厂商上用的是4.0 是和这个有关吗？task日志显示依赖redis 5.0？

**Comment by wojiushixiaobai** [comment]
redis 需要大于等于 5.0

**Comment by sfs77** [comment]
> 



> redis 需要大于等于 5.0

好的，感谢！
