### ISSUE TITLE
coco无法用序号连接搜索出来的主机

### ISSUE THREAD

**Issue by coolwind8214** [jumpserver/jumpserver#773]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
版本0.4.0
##### 问题复现步骤
1. [步骤1]
coco搜索出来的主机，无法用序号连接。
输入搜索出来的机器序号后会连接到默认列表是用该序号的主机。
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/32867316/31762625-56df29a0-b4ee-11e7-8472-00931b97b52e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
新版本fixed
