### ISSUE TITLE
[Question] 系统用户不知道什么原因关联了无关资产

### ISSUE THREAD

**Issue by zengcq** [jumpserver/jumpserver#7739]
**请描述您的问题.**
系统用户不知道什么原因关联了无关资产

**版本**
v2.19.1

**出现时的操作步骤**
1. 新增资产和系统用户
2. 更新用户的授权规则, 在权限管理->系统授权->已用的用户授权中更新添加该新的系统用户
3. 点击资产管理->系统用户, 该系统用户的资产栏中出现大量无关的节点和资产

**当前的处理方式**
在资产管理->系统用户, 将这些多出来的资产和节点一一删除

**注:**
不知是否我操作的方式不对, 麻烦给看下该问题, 非常感谢.

**Comment by wojiushixiaobai** [comment]
已知问题，后续会进行优化。

**Comment by zengcq** [comment]
好的, 谢谢.

**Comment by yanzhaoyl** [comment]
Version v2.20.0  版本 疑似 问题还存在， 感觉像是（未详细复现） 新增 系统用户时，自动绑定到 已有资产上的。

**Comment by yanzhaoyl** [comment]
@wojiushixiaobai  你好，请问 此问题 在新的版本中已经解决了吗？我看这个提问被关闭了。 我在 Version v2.20.0 版本上，可能也出现这个问题了。 添加新的系统用户时，被绑定到了无关的资产上。

**Comment by wojiushixiaobai** [comment]
这是因为错误的授权导致的，里面记录的是所有历史的授权，没有影响。

我们暂时没有时间处理这个问题，但是它在我们的优化计划里面。
