### ISSUE TITLE
[Bug] 升级至2.19.1后，资产详细账号列表操作更新功能失效

### ISSUE THREAD

**Issue by lenoray** [jumpserver/jumpserver#7744]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Edge、Chrome

**Bug 描述**
升级至2.19.1后，资产详细账号列表操作更新功能失效，之前点击可以设置密码，现版本点击无效

**Bug 重现步骤(有截图更好)**
1. 点击资产名称
2. 点击账号列表
3. 找到对应账号点击更新，应该弹出模态对话框更新密码，现在无效

**Comment by lenoray** [comment]
![无标题](https://user-images.githubusercontent.com/17763026/156877064-fc057a2f-214b-4a45-a146-af63a71f5c34.png)

**Comment by wojiushixiaobai** [comment]
收到反馈，请等待修复。
