### ISSUE TITLE
[Bug] 绑定飞书显示请求非法

### ISSUE THREAD

**Issue by xing0821** [jumpserver/jumpserver#7748]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.19.1

**浏览器版本**
Chrome 98.0.4758

**Bug 描述**
  按照官方文档绑定飞书机器人, 并录入 app_id 以及 secret, 测试返回结果正常. 用户点击设置飞书认证, 显示请求非法请联系管理员.  飞书后台可看到请求失败. 当前登陆账户名称为 xxx, 但报错中显示 id 为 test
```
POST /open-apis/im/v1/messages?receive_id_type=user_id
错误码 : 99992360
错误日志 : "these ids not existed: [test]"
```

**Comment by Hello-Hyman** [comment]
碰到了同样的问题，通过在jumpserver-基本设置中设置当前站点URL解决，可以试试
