### ISSUE TITLE
[Question] 请问"登录失败策略"在哪里配置？

### ISSUE THREAD

**Issue by wstxyswy** [jumpserver/jumpserver#7752]
**请描述您的问题.**
请问“登录失败策略”在哪里配置？
在"系统设置"--"安全设置" 页面没找到，版本是: "Version v2.14.1 GPLv2."
![image](https://user-images.githubusercontent.com/43592564/156988881-9dd482a1-c06d-4da4-9416-eb3b39fddf61.png)
![image](https://user-images.githubusercontent.com/43592564/156988904-e12d82c7-dba1-453e-a47f-46df7799dbc8.png)
看文档是在"安全设置"页面设置：
![image](https://user-images.githubusercontent.com/43592564/156989464-b5d64dae-1e58-4768-bda6-52198242c252.png)

**Comment by wojiushixiaobai** [comment]
请更新至新版本

**Comment by wstxyswy** [comment]
谢谢，升级到"v2.19"就可以了
