### ISSUE TITLE
jumpserver可以做高可用吗？

### ISSUE THREAD

**Issue by brucefanhaitao** [jumpserver/jumpserver#776]
搭建了两台3.2版本的jumpserver，并且部署了Keepalived，但是停掉其中一台server的服务，虚拟IP飘不到另一台server上，而且虚拟IP：8000访问不了jumpserver界面。请问是不是跟安装jumpserver时的IP有关呢？
![default](https://user-images.githubusercontent.com/29652825/31874990-97265f7a-b7fe-11e7-9e0c-e050f6f99aa7.png)
是不是图中的IP得改成虚拟IP呢？

**Comment by ibuler** [comment]
原来版本设计时没有考虑高可用，新版本考虑了
