### ISSUE TITLE
[Bug] 登录页面是否开启验证码（SECURITY_LOGIN_CAPTCHA_ENABLED）

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#7760]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.19.1

**浏览器版本**
99.0.4844.51

**Bug 描述**
在config.txt 添加了配置参数：
SECURITY_LOGIN_CAPTCHA_ENABLED=True

（True 和 true 都试了）

配置完参数后，执行 jmsctl.sh restart 重启JS，
进入JS登录页没有默认开启验证码，需要我输错一次用户名密码才会开启验证码，
第二天再进入JS登录页又没有验证码了

**Comment by wojiushixiaobai** [comment]
默认不需要验证码，减少用户的输入。
但是为了防止机器人，输入错误的密码后将需要输入验证码才能第二次提交。
