### ISSUE TITLE
[Bug] 使用动态用户执行批量任务时 使用root账户连接

### ISSUE THREAD

**Issue by htmz** [jumpserver/jumpserver#7762]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.19.1 GPLv2

**浏览器版本**
Google chrome 版本 97.0.4692.71（正式版本） (x86_64)

**Bug 描述**
使用动态用户执行批量任务时 使用root账户连接

**Bug 重现步骤(有截图更好)**
1.  用户登陆后使用批量命令时，选择动态用户后，执行命令却是root账户
<img width="823" alt="image" src="https://user-images.githubusercontent.com/27039243/157157285-d3074aeb-ba06-46a4-ae9b-abfbb9053b7d.png">

**Comment by wojiushixiaobai** [comment]
当前登录用户的用户名是啥？版本号说明下
