### ISSUE TITLE
[Question] jmp負載均衡架構core容器集體失效問題

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#7764]
JMP採用負載均衡方式部署後，3台JMP服務器同時掛載了NFS /data/jumpserver/core/data共享目錄，昨天其中一台服務器網絡出現問題後，導致另外2台的core容器也出現了問題，都處於unhealthy狀態，導致JUMPSERVER無法正常使用，按照原理來說一台服務器出現問題不會影響其它服務器上的容器運行，請問這個問題是出在哪裡？查看網絡有問題的那台JMP服務器日誌如下：
![image](https://user-images.githubusercontent.com/35226938/157162220-d4502b08-5962-42c9-baa4-e9a280ee984f.png)

**Comment by wojiushixiaobai** [comment]
你的前端 slb 没有正常对异常的后端进行剔除，需要调整 slb 的配置，另外你图片的报错是 redis 导致的。
以 [HAProxy](https://docs.jumpserver.org/zh/master/install/setup_by_lb/#haproxy) 为例，请参考该文档
