### ISSUE TITLE
文件上传不可用，请问文件上传如何使用或需要安装什么插件?

### ISSUE THREAD

**Issue by pengzhong2010** [jumpserver/jumpserver#777]
[简述你的问题]
使用《v0.4.0 基于 CenOS7 的系统》和github上面的docker启动方式分别测试，文件上传不可用，请问文件上传如何使用或需要安装什么插件?
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤
1. [步骤1]ssh -p2222 xx@xx.xx.xx.xx
2. [步骤2]u
返回No asset match, please input again
![image](https://user-images.githubusercontent.com/18000468/31885192-475b5700-b7b5-11e7-9139-5b334aa338dd.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
还未完成哈
