### ISSUE TITLE
[Feature] MFA 校验全局有效期

### ISSUE THREAD

**Issue by internelp** [jumpserver/jumpserver#7771]
建议允许设置全局 MFA 校验有效期

每天（或其他时长）同一设备仅验证一次即可。

**Comment by ibuler** [comment]
和登录时间一样

**Comment by internelp** [comment]
> 和登录时间一样

但是如果使用 ssh 客户端连接，就得每次登录了。

**Comment by ibuler** [comment]
ssh客户端无法存状态，如果记录了 ip，那别人在这个 ip 登陆就不需要 mfa 了，所以不可取

**Comment by internelp** [comment]
> ssh客户端无法存状态，如果记录了 ip，那别人在这个 ip 登陆就不需要 mfa 了，所以不可取

了解了。
