### ISSUE TITLE
jumpserver 上传文件卡死

### ISSUE THREAD

**Issue by ximenfeibing** [jumpserver/jumpserver#778]
[简述你的问题]
jumpserver 上传文件卡死
##### 使用版本
[请提供你使用的Jumpserver版本0.3]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
出现下图提示内容，出现后终端无法继续操作
![image](https://user-images.githubusercontent.com/15155388/31933153-e820f466-b86d-11e7-85d1-426e8629fe67.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jiabin1994** [comment]
你的问题解决了没有，我也遇到同样的问题

**Comment by ibuler** [comment]
需要ssh工具支持 xyz-modem
