### ISSUE TITLE
[Question] 关于管理cisco交换机

### ISSUE THREAD

**Issue by wpy1215** [jumpserver/jumpserver#7780]
**请描述您的问题.**
思科交换机是可以加入管理的，我试了几个命令，都是执行失败。
管理cisco IOS的时候能否执行批量命令？如果可以，需要通过什么命令执行？

**Comment by ibuler** [comment]
能连接上吗？ 
还是说批量命令？

**Comment by wpy1215** [comment]
> 能连接上吗？ 还是说批量命令？

实际是可以通过web终端连上的，但是显示不能连接，我不太清楚怎么对管理的思科交换机进行批量命令。
![image](https://user-images.githubusercontent.com/43837207/157581453-2c85d015-81ba-4fe7-ad2b-e032d4a8ef73.png)

**Comment by ibuler** [comment]
思科交换机执行用的 ansible 的 raw 模块，实际上 ssh 执行命令

**Comment by wpy1215** [comment]
> 思科交换机执行用的 ansible 的 raw 模块，实际上 ssh 执行命令

在选择cisco交换机批量执行命令的时候不管执行什么命令都会报错，我说我想了解一下这个ansible是安装在那个容器（我使用的docker安装）内的？感谢！
![image](https://user-images.githubusercontent.com/43837207/163560699-b4bbe7b7-3641-44b8-b21d-17ff0d1c9846.png)
@ibuler

**Comment by wojiushixiaobai** [comment]
core 里面

**Comment by wpy1215** [comment]
其实我主要是不太明白下图中的报错，因为看报错明显是执行的linux命令行，但是在cisco IOS中需要执行怎样的命令才能批量执行呢？
![image](https://user-images.githubusercontent.com/43837207/163775602-d932f9fe-a13d-4e78-a757-a0237136a5bd.png)

**Comment by wojiushixiaobai** [comment]
不能，交换机需要完整的支持 python 和 ssh 才行。
