### ISSUE TITLE
[Question] 对于特权用户、普通用户的较好的实践是怎样？

### ISSUE THREAD

**Issue by denity** [jumpserver/jumpserver#7781]
对于特权用户、普通用户的较好的实践是怎样？

比如一个组里有100台服务器，理论上每台服务器上的账号、密码都不一样的，这样势必需要设置100个特权账号或者普通账号进行系统运维。假如对这个组授权，还需要在系统用户中逐一添加这100个特权账号或者普通账号。
然后在Web终端运维的时候（第一次）还需要在这100个账号里面去选择哪一个账号进行运维。
并且，重新进入“资产列表”——“主机”——“系统用户”和“账号列表”中，又会将这100个账号都列出来？

问题1：能否考虑“账号”就和“资产”关联？

问题2：难道需要所有主机都使用同样的账号/密码/证书登录？

jumpserver 版本：v2.19.0

**Comment by ibuler** [comment]
特权用户现在来说只是用来推送其它普通用户的

**Comment by denity** [comment]
设备连通性是用特权账号么？

**Comment by wml3** [comment]
两个地方会有连通性测试，一个是针对资产的连通性测试，这个地方用的是特权账号；另一个是针对授权的系统用户做的连通性测试，这里用的是各个系统用户做测试
