### ISSUE TITLE
网页版本,连接服务器的输入法和本地输入法中英文切换冲突,需要按好几次才能完成切换[Bug] 

### ISSUE THREAD

**Issue by Rory602** [jumpserver/jumpserver#7785]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
没有太好的解决方案，系统的优先级会比较高，然后到浏览器，最后才到浏览器里面的资产
