### ISSUE TITLE
ssh tunneling报错

### ISSUE THREAD

**Issue by bangbang93** [jumpserver/jumpserver#779]
![image](https://user-images.githubusercontent.com/3430784/31995585-ae0505aa-b94a-11e7-9b57-2c2e5d2fd1c3.png)

##### 使用版本
0.4.0

##### 问题复现步骤
ssh -L 8000:someip:8001 remote

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不支持
