### ISSUE TITLE
Jumpserver4.0的邮件发送问题.

### ISSUE THREAD

**Issue by hrool** [jumpserver/jumpserver#780]
[简述你的问题]
通过docker安装的4.0不能推送用户的密码邮件
##### 使用版本
0.4.0

##### 仔细查看jumpserver的代码后, 发现4.0存在普遍问题.
邮件发送的处理逻辑全部是放入celery异步执行, 具体步骤在于:
common.task.send_mail_async:
![image](https://user-images.githubusercontent.com/18434071/32007286-c0046d58-b96e-11e7-8609-118d7177defe.png)

搜索整个项目后发现, 调用send_mail_async的只存在于
users.utils里面的send_reset_password_mail, user_add_success_next, send_reset_ssh_key_mail这三个方法.
而调用方式, 全部都是:
send_mail_async.delay(subject, message, recipient_list, html_message=message)
很明显, 参数个数大于3, 所以send_mail_async并不会自动把settings.EMAIL_HOST_USER加入进去.
由于缺少from mail参数, django的send_mail不可能发送成功.
所以,肯定会存在问题.

PS: 另外在
![image](https://user-images.githubusercontent.com/18434071/32006748-3366c5c2-b96d-11e7-9199-fbf1d312a320.png)
这里对编码的处理有问题,有中文的情况下, log失败, 直接导致后面的send_mail_async根本不会调用,
jumpserver开发者大部分是国人, 这里应该处理下?

建议:
前期修改: users.utils里面调用send_mail_async加上form mail参数, 默认可以是settings.EMAIL_HOST_USER
后期修改: 如果使用自建的邮箱服务器, 或者不是托管的企业邮箱,那么EMAIL_HOST_USER根本不行,因为没有@domain.com, 所以这时候可以考虑单独加一个setting, 不能和EMAIL_HOST_USER公用
终极修改: 这类配置, 应该放入web的后台设置中, 包括email通知, 站点路径.

PS: 
如果确认上诉问题存在, 我可以提交PR, 修改users.utils里面的send_mail_async调用方式(改动很小)
至于在setting里面增加配置, 这种需要各方讨论一下.
把邮件设置放入web后台的设置中, 则需要改变的地方太多, 我认为短期内不好实现.
[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. html_message=message是不计入args的而是计入kwargs中，所以不会超过3
https://github.com/jumpserver/jumpserver/blob/dev/apps/common/tasks.py#L21

2. 日志里不会打印中文日志

**Comment by hrool** [comment]
1. 我对args和Kwargs的理解有错,  send_mail_async这段代码的确没有问题.
2. 但是由于日志不能打印中文, 而发送邮件的内容的确含有中文, 这里就崩溃了, 导致后面的send_mail_async没有执行,  这个才是导致邮件没有正常发送的原因. 如果关闭debug,邮件就能正常发送了. 可是这样应该是不合理的. message的确含有中文, 这个又的确有debug参数存在.
https://github.com/jumpserver/jumpserver/blob/8ed40cafb0170582247f0b4e571d0d99e566856d/apps/users/utils.py#L120

**Comment by hrool** [comment]
@ibuler

**Comment by ibuler** [comment]
0.5.0已修复
