### ISSUE TITLE
[Feature] RDP支持Hyper-V宿主机的Preconnection PDU选项

### ISSUE THREAD

**Issue by wjluo** [jumpserver/jumpserver#7810]
在Hyper-V虚拟机出网络配置故障时，需要连接到Hyper-V宿主机进行紧急处理。因此，请支持Hyper-V宿主机的Preconnection PDU选项。参考文档：https://guacamole.apache.org/doc/gug/configuring-guacamole.html#rdp-preconnection-pdu

**Comment by ibuler** [comment]
记录到内部系统了，等待排期，暂时关闭
