### ISSUE TITLE
CSS的问题

### ISSUE THREAD

**Issue by pdgz** [jumpserver/jumpserver#782]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
最新版本。
##### 问题复现步骤
1. [步骤1]
国内网络，每次点击一个页面，都跳转很慢，
打开浏览器调试，
https://fonts.css.network/css?family=Roboto:400,300,500,700 不能访问了
2. [步骤2]

##### 其他
建议换成国内的或直接放一个静态的css代替

[注:] 完成后请关闭 issue

**Comment by YinJie2015** [comment]
替换成“fonts.cat.net”可以暂时解决
#grep "fonts.cat.net" * -r
apps/static/css/plugins/inputTags.css:@import url("https://fonts.cat.net/css?family=Open+Sans:300,400,600,700");
apps/static/css/plugins/inputTags.css:@import url("https://fonts.cat.net/css?family=Roboto:400,300,500,700");
apps/static/css/style.css:@import url("https://fonts.cat.net/css?family=Open+Sans:300,400,600,700");
apps/static/css/style.css:@import url("https://fonts.cat.net/css?family=Roboto:400,300,500,700");
apps/static/js/plugins/highcharts/themes/sand-signika.js:	href: 'https://fonts.cat.net/css?family=Signika:400,700',
apps/static/js/plugins/highcharts/themes/dark-unica.js:	href: 'https://fonts.cat.net/css?family=Unica+One',
apps/static/js/plugins/highcharts/themes/grid-light.js:	href: 'https://fonts.cat.net/css?family=Dosis:400,600',

**Comment by pdgz** [comment]
ok!
