### ISSUE TITLE
显示中文乱码

### ISSUE THREAD

**Issue by jiangshp** [jumpserver/jumpserver#785]
[简述你的问题]
使用xshell登录服务器，系统字符编码zh_CN.UTF-8,应用配置文件和日志可以正常显示中文。
但是使用jumpserver 0.3可以远程连接上服务器， 浏览器的字符编码也为UTF-8, 显示中文为乱码。

##### 使用版本
jumpserver 0.3

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/32517381/32160180-8be7bdec-bd8b-11e7-93fb-1634cf33af42.png)
![image](https://user-images.githubusercontent.com/32517381/32160197-9feb3e54-bd8b-11e7-9348-d4f9fd77887e.png)

**Comment by jiangshp** [comment]
jumpserver有地方修改编码吗？

**Comment by ibuler** [comment]
乱码和jumpserver没有关系，jumpserver是透明中转的，请尝试直接登录服务器测试一下，或者关注一下xshell的编码设置
