### ISSUE TITLE
[Question] 当windows server 勾选“Allow connections only from computers running Remote Desktop with Network Level Authentication.” jumpserver 无法进行RDP连接

### ISSUE THREAD

**Issue by gary18chen** [jumpserver/jumpserver#7856]
系统为windows server 2016
当windows server 勾选“Allow connections only from computers running Remote Desktop with Network Level Authentication.” 
![image](https://user-images.githubusercontent.com/101391382/158346274-11688846-f123-40a9-b135-648aae394a2e.png)
jumpserver 无法进行RDP连接，连接时提示网络不可达或者
![image](https://user-images.githubusercontent.com/101391382/158346471-cbd83c8c-fe33-413b-a97c-63e9c1ad7597.png)
即使修改模板后也会提示用户名不正确等问题
已检查网络联通正常，RDP服务正常，docker内也可以连接到RDP服务器及相关端口

**Comment by wojiushixiaobai** [comment]
系统平台选择 Windows 即可

**Comment by gary18chen** [comment]
![image](https://user-images.githubusercontent.com/101391382/158498258-e9d95124-4802-485f-b6f5-a233677f5651.png)
![image](https://user-images.githubusercontent.com/101391382/158498295-20f175cb-b0de-49f3-9bc1-38204d7dff53.png)
修改为windows后，报错依旧。

**Comment by gary18chen** [comment]
问题解决了，类型改为windows，输对密码就可以登陆进去。
但没有勾“Allow connections only from computers running Remote Desktop with Network Level Authentication.”
即使输错密码也可以到windows远程页面，有勾、没有勾的区别只在这里。

**Comment by wojiushixiaobai** [comment]
好的
