### ISSUE TITLE
系统管理员无法解锁普通用户

### ISSUE THREAD

**Issue by masayil** [jumpserver/jumpserver#7859]
普通用户被锁定，系统管理无法解锁，显示禁止标志，只有超级用户admin才可以解锁吗
![image](https://user-images.githubusercontent.com/65291464/158360123-2f5079cf-e35c-4faa-9353-03b037496f73.png)

**Comment by wojiushixiaobai** [comment]
刷新下页面，默认信息存储在 redis 里面，多组件的话确定 redis 共享
