### ISSUE TITLE
特权用户怎么没法添加RDP协议的用户

### ISSUE THREAD

**Issue by chanyipiaomiao** [jumpserver/jumpserver#7872]
特权用户怎么没法添加RDP协议的用户
![image](https://user-images.githubusercontent.com/1332794/158526935-6206fd4a-b44a-4d25-a9db-35db2c5e1a31.png)

**Comment by chanyipiaomiao** [comment]
版本是： v2.19.2

**Comment by wojiushixiaobai** [comment]
- jumpserver/jumpserver#7892
