### ISSUE TITLE
不能添加用户

### ISSUE THREAD

**Issue by aukeys** [jumpserver/jumpserver#788]
Request Method: | POST
-- | --
http://192.168.96.229:8091/users/user/create
1.11.6
TypeError
str() takes at most 1 argument (2 given)
/data/server/jump_zip/jumpserver-dev/apps/common/utils.py in sign_t, line 73
/usr/bin/python
2.7.5
['/data/server/jump_zip/jumpserver-dev/apps',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib/python2.7/site-packages',  '/data/server/jump_zip/jumpserver-dev',  '/data/server/jump_zip/jumpserver-dev/apps']

class Signer(object):
    """用来加密,解密,和基于时间戳的方式验证token"""
    def __init__(self, secret_key=SECRET_KEY):
        self.secret_key = secret_key

    def sign(self, value):
        if isinstance(value, bytes):
            value = value.decode("utf-8")
        s = JSONWebSignatureSerializer(self.secret_key)
        return s.dumps(value)

    def unsign(self, value):
        s = JSONWebSignatureSerializer(self.secret_key)
        try:
            return s.loads(value)
        except BadSignature:
            return {}

    def sign_t(self, value, expires_in=3600):
        s = TimedJSONWebSignatureSerializer(self.secret_key, expires_in=expires_in)
        #value = value.decode("utf-8")
        #return str(s.dumps(value), encoding="utf-8")
        return str(s.dumps(value), encoding="utf8")  《--------------问题行
        #return s.dumps(value)

    def unsign_t(self, value):
        s = TimedJSONWebSignatureSerializer(self.secret_key)
        try:
            return s.loads(value)
        except (BadSignature, SignatureExpired):
            return {}

**Comment by jiaxiangkong** [comment]
v0.4.0 是用 Python 3.6
