### ISSUE TITLE
[Bug] 无法连接windows主机，已添加系统用户和已关联资产

### ISSUE THREAD

**Issue by chanyipiaomiao** [jumpserver/jumpserver#7892]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.19.2
**浏览器版本**
Microsoft Edge 99.0.1150.39
**Bug 描述**
系统用户界面创建了一个windows系统用户(普通用户)，也关联了一台windows主机，但是在web终端点击连接这台window主机时有一个弹出框： 没有系统用户
另外特权用户为什么不能添加RDP协议的用户了
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/1332794/158723345-ba57327d-6d5d-45f5-8d9f-dce0e93e037c.png)
![image](https://user-images.githubusercontent.com/1332794/158723410-0739422d-19c2-41ce-8a1b-e8b4cdd805a5.png)

**Comment by wojiushixiaobai** [comment]
ssh 协议目前才需要特权用户

**Comment by chanyipiaomiao** [comment]
那第一个问题是怎么回事，明明是已经关联了，怎么提示没有系统用户

**Comment by harry91** [comment]
> ssh 协议目前才需要特权用户，提示没有系统用户是因为授权规则里面没有授权系统用户导致

这个设计太差劲了

**Comment by oldthreefeng** [comment]
> ssh 协议目前才需要特权用户，提示没有系统用户是因为授权规则里面没有授权系统用户导致

这个可以在创建windows的时候，给用户一个提示， 因为 windows 并没有 特权用户 这个概念。  

有点离谱
