### ISSUE TITLE
日志功能有bug

### ISSUE THREAD

**Issue by nhywieza** [jumpserver/jumpserver#792]
1. 仅当在client端输入内容时才会把上一条日志给记录下来。
2. 在输出信息过程中，不断的输入日志会乱码。

##### 使用版本
dev版本

##### 问题复现步骤
1. ps aux
2. 不断的按回车

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/8528287/32431641-e5709132-c299-11e7-8f20-bff821e6a1d7.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个问题在修复中，也再重构coco
