### ISSUE TITLE
[Question] how to download private key

### ISSUE THREAD

**Issue by chad-kumu** [jumpserver/jumpserver#7922]
**请描述您的问题.**

Can I download the private key that I used?

let say I lost my private key and I want to download the file inside the application(Jumpserver). is that possible?

**Comment by wojiushixiaobai** [comment]
Yes, you can.
:)

Assets - Asset detail - Account list - view
![image](https://user-images.githubusercontent.com/24326988/158958441-7907bf05-1184-498b-a44d-149ac666161c.png)

**Comment by chad-kumu** [comment]
Thank you.. I was able to get retrieve the private key..

Cheers.
