### ISSUE TITLE
[Bug]  安装完成之后，redis连接失败

### ISSUE THREAD

**Issue by fuzengjie** [jumpserver/jumpserver#7936]
**Bug 描述**

使用安装文档一步步进行安装，并且使用的是外部mysql和redis，工程起来之后，日志报错，连不上redis，从日志上看，没有拿到redis host地址，打印的为None
**Bug 重现步骤(有截图更好)**
1、安装截图，配置文件提前配置好了redis地址，安装的时候也识别到了
<img width="2463" alt="image" src="https://user-images.githubusercontent.com/9402808/158988096-967adbee-47f4-4ae8-9add-bf34901aaccb.png">

2、工程起来之后，前端页面打不开
<img width="781" alt="image" src="https://user-images.githubusercontent.com/9402808/158988366-1c1dbfee-03b1-4874-be88-d38ce64bc096.png">

3、查看日志报错
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/9402808/158987683-c5efad5f-6edf-4604-897f-c90004efb526.png">

4、上docker里，进入django shell 环境，手动测试 redis 联通性
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/9402808/158988330-006561a0-e03b-493d-8a7f-4868258d9143.png">

**Comment by fuzengjie** [comment]
使用内置redis 也是同样的情况
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/9402808/158993443-6594b152-9f97-46c1-8a88-405bb47aa6f6.png">

**Comment by wojiushixiaobai** [comment]
密码不要包含特殊字符串试试。注意 iptables

**Comment by fuzengjie** [comment]
换了简单密码之后解决了， 后续希望能修复一下这个小bug。 也感谢及时支持，赞

**Comment by Anymous526** [comment]
当外部redis的密码有特殊字符时,无法启动. core报连接不上redis
