### ISSUE TITLE
[Bug] 企业微信绑定用户时404

### ISSUE THREAD

**Issue by marklinglon** [jumpserver/jumpserver#7937]
JumpServer 版本v1.20.0

**Bug 描述**
用户绑定企业微信时，扫码后404

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/18097531/159162545-a6ada63c-5a67-466d-ba22-3d56716443c2.png)
企业微信绑定时的扫码地址是，
https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid=&agentid=1000029&state=rLjRUeGZfBsq1PcC&redirect_uri=http:/******.com/ui/#/settings/basic/core/auth/wecom/qr/bind/b8974e70-1c6f-4217-b9f5-a61031dc41c9/callback/?redirect_url=%2Fprofile%2Finfo
我另一个jumpserver绑定成功的地址是
https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid=&agentid=1000029&state=rLjRUeGZfBsq1PcC&redirect_uri=http:/******.com/core/auth/wecom/qr/bind/b8974e70-1c6f-4217-b9f5-a61031dc41c9/callback/?redirect_url=%2Fprofile%2Finfo

**Comment by marklinglon** [comment]
原因找到了，基本设置里站点url设置的不对，只能到域名结束

**Comment by wojiushixiaobai** [comment]
好的，能解决问题就行
