### ISSUE TITLE
ssh 中断不退出

### ISSUE THREAD

**Issue by jiangwu1206** [jumpserver/jumpserver#794]
[简述你的问题]
使用Xshell 登录跳板机后再连接到其他服务器后用户直接关闭Xshell用户不会自动退出
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
因为直接关闭xshell, 后端无法正常收到端口请求，不过 jumpserver会自动定时清理的
