### ISSUE TITLE
[Feature] 增加ftp和winscp功能

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#7945]
**请描述您的需求或者改进建议.**
目前jumpserver没有ftp和winscp功能，而sftp功能有如下缺陷：
1. 使用麻烦，需要在系统用户指定的目录下进行，如默认的tmp目录；用户要先上传到这里，然后ssh登录后再cp到自己的目录；
2. 受Guacamole或者tmp目录大小的限制，无法传输很大的文件。
建议：
linux资产增加ftp功能，让用户像使用filezilla一样做文件传输操作；
windows资产增加winscp功能

**Comment by wojiushixiaobai** [comment]
Please use the internal MySQL or check the MySQL configuration.
