### ISSUE TITLE
[Bug] v2.17.3升级之后版本，连接windows异常，连接linux正常。

### ISSUE THREAD

**Issue by xiefei0826** [jumpserver/jumpserver#7949]
**Bug 描述**
V2.17.3 后的dockerfile 升级了guacd,从版本1.3.0 升级到了1.4.0导致所有与guacd相关的应用不能正常使用。
但是新安装的V2.17.3之后的版本，使用正常。对比了数据库，只是新增了一个表，其他没有太多变化。
因为资产有点多，密码原文件丢失等各方面原因，目前只能升级，不能导入新的实例。
进入容器中，guacd服务运行正常。无异常日志。

**Comment by wojiushixiaobai** [comment]
根据新文档，调整下资产的系统平台和远程 NLA 设置即可
[Windows RDP 资产要求](https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_rdp/)

**Comment by xiefei0826** [comment]
感谢，这个方法之前尝试过。步骤可能不一样。我再次尝试下。





我心飞翔


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Bug] v2.17.3升级之后版本，连接windows异常，连接linux正常。 (Issue #7949)





 
根据新文档，调整下资产的系统平台和远程 NLA 设置即可
 Windows RDP 资产要求

**Comment by xiefei0826** [comment]
还是不正常。新安装的jumpserver ，选择window都能正常连接
，但是老的就不行了。感觉是那里配置问题


我心飞翔


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Bug] v2.17.3升级之后版本，连接windows异常，连接linux正常。 (Issue #7949)





 
根据新文档，调整下资产的系统平台和远程 NLA 设置即可
 Windows RDP 资产要求

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159397952-ad0b9f45-152d-4b3c-a464-cf57a6bdd294.png)
这些也是调整了的呢

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159398443-37af1390-ba85-4658-88be-4ecc018c60d3.png)

**Comment by wojiushixiaobai** [comment]
提示无法连接 guacamole 服务器可能是 lion 组件异常了，重启下 jms_lion
```bash
docker restart jms_lion
```

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159411842-9a01ed01-17fa-41e3-98c0-7931b3e02294.png)
重启过不行的。现在开了info 日志。会有这些,是否有影响呢？lion日志里看是启动成功了的。

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159412311-2f5754a0-7074-454d-b43b-7055dd96791e.png)

**Comment by xiefei0826** [comment]
感觉还是在guacd 上，查是guacd看起来运行正常

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159412557-79103bb0-a698-4122-b05e-39e00fce4949.png)

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159413134-c7bc34d4-9f71-4201-b39e-e5afaf7c0bf1.png)
这个端口死掉了，在开始的时候是正常的。但是没有异常日志。

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159414791-8b0f329c-9d06-4ff6-96c5-723d6f7cf366.png)
比较了两个配置，发现了，问题，一个监控的ipv4 一个监控的ipv6 ipv6的通过Ipv4肯定不通呀。

**Comment by wojiushixiaobai** [comment]
kill掉后手动启动 guacd 试试
```bash
/etc/init.d/guacd status
/etc/init.d/guacd restart
```

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/159416373-62f1e26b-f3bf-45ea-94cd-3699dd09dba7.png)
这个是老数据库升级上来异常的监听， 版本号V2.19.1
![image](https://user-images.githubusercontent.com/46474161/159416431-7a77b242-6f87-4e8e-a0bb-ff84f58857ea.png)
这个是V2.17.3下，或重新创建正常的监听。 版本号V2.17.3 与V2.19.1 一样重启一样的。如果

**Comment by wojiushixiaobai** [comment]
这个不要紧，你开了ipv6会自动监听到 ipv6 的地址，是使用人数很多吗？
正常这个服务不会挂才是

**Comment by xiefei0826** [comment]
这个服务不会挂，未开通ipv6地址。应该是局域网腾讯云给开通了，但是配置的是127.0.0.1:4822  这样的，如果监听的Ipv6地址，肯定不能连接呀

**Comment by xiefei0826** [comment]
这个服务一直正常运行着。

**Comment by wojiushixiaobai** [comment]
```bash
docker exec -it jms_lion bash
cat /etc/supervisor/conf.d/supervisord.conf
```
看起来默认是监听在 ipv4 的接口

**Comment by xiefei0826** [comment]
很怪的就是，升级才会到ipv4 老版本，还有 重新创建都不会过去。这个guacd 有没有地方配置监听呢？

**Comment by xiefei0826** [comment]
这个文件之前也查看了，理论上是在ipv4 。不知道为什么，升级的，一直跑ipv6上去了

**Comment by xiefei0826** [comment]
找到了，要默认修改下。-d  -l  建议你们也指定下。可能这个是什么情况下出的一个未知道BUG。

**Comment by xiefei0826** [comment]
现在我要做的就是重新打镜像。来修复这个问题。感谢你们。
