### ISSUE TITLE
[Bug] Web终端会话窗口显示问题

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#7963]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.20.0

**浏览器版本**
Edge 99.0.1150.46

**Bug 描述**
退出会话后，会话标题没有变化

**Bug 重现步骤(有截图更好)**
1.  连接Linux会话，执行exit退出后，窗口无变化。
![image](https://user-images.githubusercontent.com/58923704/159614717-aaea182a-604c-4a94-b7a7-389b706738c2.png)
当点击别的任意位置，窗口变化为灰色代表离开。（是否可以做到断开会话马上有差异的显示）
![image](https://user-images.githubusercontent.com/58923704/159614880-2591855b-dab4-477f-9ea5-dba4e9f02fed.png)

2.  对已断开窗口右键“重新连接”后，再次执行exit退出后，窗口无变化，点击别的位置，切换会话也是无变化。
![image](https://user-images.githubusercontent.com/58923704/159615064-475a2250-616b-4102-a41d-d96a6ef32255.png)

**Comment by jym503558564** [comment]
在最新版本v2.24.2中：
未复现
![image](https://user-images.githubusercontent.com/40739051/183549417-49c32a11-8b8f-42e2-be04-012300d1c299.png)

**Comment by jym503558564** [comment]
如还有问题，可群里联系我们管理员，进行远程协助看一下。我们目前无法复现您所遇到的问题。
