### ISSUE TITLE
[Bug]  命令过滤,按tab键罗列的多行信息，最后一行会被当作命令，显示命令禁止

### ISSUE THREAD

**Issue by yunyaomingzheng** [jumpserver/jumpserver#7967]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.19.2

**浏览器版本**
chrome 版本 99.0.4844.74（正式版本） (x86_64)

**Bug 描述**
开启命令过滤，输入命令时使用了tab键，罗列出了一些文件，罗列出的信息会被作当作命令，显示命令被禁止，导致命令输入失败。

**Bug 重现步骤(有截图更好)**
1.  直接输入ls，命令成功执行
<img width="963" alt="image" src="https://user-images.githubusercontent.com/35861629/159712385-bbd78c0d-328a-4d5c-ad38-10c9325004f5.png">

2. 输入ls后，按空格，然后按tab键，会罗列当前文件夹下文件
<img width="809" alt="image" src="https://user-images.githubusercontent.com/35861629/159712474-79d07b58-4ea7-4ae9-a7dc-cffad600bd0e.png">

3. 此时直接回车，或ls 后选择一个文件夹再回车，都会报错
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/35861629/159712582-41e1474c-8795-423a-b4e7-40fbfb9def43.png">
4.可以从图上看到，输入ls命令，按空格，再按tab罗列了jumptest文件夹下的文件夹，此时显示的是

`11dsdfdfg/    1ASD/         2BBBBB/       3JHKH/        5asadsd/      7czxcxc/      9asdasdsad/     
              
1AAAAA/       22uiuiouiou/  3CCCCCC/      4DDDDDD/      6eqweqwe/     8asdd/    `
两行，此时直接回车，罗列信息的第二行“1AAAAA/       22uiuiouiou/  3CCCCCC/      4DDDDDD/      6eqweqwe/     8asdd/ ”会被当作是命令显示“命令 1AAAA... 是被禁止的”

**Comment by ibuler** [comment]
命令处理这里有时的确不太精确，等待优化
