### ISSUE TITLE
[Bug] 升级V2.19.2升级V2.20.0 或V2.20.1 报core api错误 

### ISSUE THREAD

**Issue by xiefei0826** [jumpserver/jumpserver#7968]
<img width="972" alt="企业微信截图_16480816806468" src="https://user-images.githubusercontent.com/46474161/159820481-3659f405-a0eb-4fc1-868e-9bc44d485047.png">

查看服务运行正常，端口存活。无异常日志

**Comment by huwsun** [comment]
遇到了同样的问题

**Comment by wojiushixiaobai** [comment]
需要检查升级过程是否有错误

**Comment by xiefei0826** [comment]
k8s 部署的，未看到有错误日志呢？

**Comment by ibuler** [comment]
已修复

**Comment by xiefei0826** [comment]
好的，感谢

**Comment by xiefei0826** [comment]
刚验证还是有同样的问题，只不过运行一次静态文件清理，或删除之前的文件  最后重新启动。就完美解决。
