### ISSUE TITLE
[Bug] 添加cisco交换机远程的时候提示“没有系统用户”

### ISSUE THREAD

**Issue by Jack-Ywn** [jumpserver/jumpserver#7972]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.20.0

**浏览器版本**
 Google Chrome 99.0.4844.82（正式版本） （64 位）

**Bug 描述**
资产中添加思科交换机，并且已经关联了交换机系统用户，
系统用户我尝试添加了两种用户类型（telnet和ssh两种类型）
交换机telnet和ssh的两种登录方式我均已经开启
但是JumpServer两种方式无法远程，均提示无系统用户

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/72083949/160051830-d2bc8582-cf9a-449f-ae22-43e6d5975c54.png)
![image](https://user-images.githubusercontent.com/72083949/160051991-a3868a7c-af7f-4a14-a3b5-02d83b9f22f1.png)
![image](https://user-images.githubusercontent.com/72083949/160052066-1d9bbf64-785a-4339-be46-6892bf8034a4.png)

**Comment by wojiushixiaobai** [comment]
检查资产 授权
