### ISSUE TITLE
[Bug] K8S应用连接 Role+RoleBinding 无法快速连接 Pod

### ISSUE THREAD

**Issue by lyc7456** [jumpserver/jumpserver#7973]
ClusterRole+ClusterRoleBinding

**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.18.1-101

**浏览器版本**
Google Chrome 版本 99.0.4844.82（正式版本） （64 位）

**Bug 描述**
K8S RBAC 使用 Role+RoleBinding 的 SA 用户，再用 Jumpserver K8S应用连接无法展示 Pod。

![](https://res.lyc7456.com/20220329104300.png)

**Bug 重现步骤(有截图更好)**
初衷是为了限制 K8S 连接用户只能访问 default ns
1. develop 用户 K8S RBAC ClusterRole+ClusterRoleBinding 可以快速连接所有 ns 的 Pod
2. develop1 用户 K8S RBAC Role+RoleBinding 限制了ns为default，无法展示Pod的快速连接，但右击连接apiserver正常。

**Comment by feng626** [comment]
rbac 暂时不支持k8s上单独控制，现在只有应用层面上的控制

**Comment by lyc7456** [comment]
希望新版本能够支持，tks。

**Comment by feng626** [comment]
先记录一下，排个期

**Comment by BaiJiangJie** [comment]
@feng626 冯，把后端调用的获取 Pods 的 k8s API 发出来，试一下。

**Comment by feng626** [comment]
https://k8s-python.readthedocs.io/en/latest/README.html?highlight=list_pod_for_all_namespaces

**Comment by ibuler** [comment]
系统用户需要有这个权限才可以，所以 保证 kubectl get pods 是可以的
