### ISSUE TITLE
[Bug] 命令过滤在网络上设备不生效？

### ISSUE THREAD

**Issue by leoyip** [jumpserver/jumpserver#7974]
**请描述您的问题.**
JS Version v2.19.2 GPLv2. ，网络设备华三5130S-EI，测试 shutdown 命令拦截.

问题现象：命令禁止虽然提示，但是并没有达到过滤效果，命令还是输入生效了. 测试过服务器，在服务器资产上命令过滤是生效的。

<img width="602" alt="307418aa0e8d94b83d495b937573389" src="https://user-images.githubusercontent.com/16930670/160066538-ea1fa515-719f-471b-a5ea-18e3f0595b53.png">

过滤器配置：

<img width="693" alt="6e322f278930d487927d96d4c1075a8" src="https://user-images.githubusercontent.com/16930670/160066761-1bb9c804-a987-4c88-8bc9-d8ce3fcd7f7e.png">

<img width="1684" alt="2b49216361ef3baf757bda15eabb36f" src="https://user-images.githubusercontent.com/16930670/160066863-fcf3e0cb-c14e-481d-a47e-281bd44cc10a.png">

**Comment by LeeEirc** [comment]
新创建个名为  h3c 系统平台，这个资产的平台更改为新创建的 h3c 系统平台，再试试

**Comment by luweijun1992** [comment]
> 新创建个名为 h3c 系统平台，这个资产的平台更改为新创建的 h3c 系统平台，再试试

这是啥原理？这样就可以？

**Comment by LeeEirc** [comment]
koko做了一些兼容处理

**Comment by luweijun1992** [comment]
> koko做了一些兼容处理

那是否可以在软件默认情况下就把几种平台类型给创建好。不然都不知道jms支持哪些平台。
比如：windows、linux、network、等等之类

**Comment by LeeEirc** [comment]
> 

后面会逐渐增加到平台类型里

**Comment by luweijun1992** [comment]
> > 
> 
> 后面会逐渐增加到平台类型里

那当前都有哪些？平台名称是不是要严格一样。

**Comment by LeeEirc** [comment]
名称需要是 h3c 和 huawei，不区分大小写。

**Comment by leoyip** [comment]
> 

这个是不是Bug？有计划修复吗？

**Comment by LeeEirc** [comment]
> > 
> 
> 这个是不是Bug？有计划修复吗？

已经修复了呀，按以上步骤操作解决。后面优化页面选项。
