### ISSUE TITLE
RDP远程桌面输入法无法输入逗号，以及部分按键无法输入

### ISSUE THREAD

**Issue by yww0926** [jumpserver/jumpserver#7978]
**JumpServer 版本(v1.5.9以下不再支持)**
2.1.8
2.1.9

**浏览器版本**
chrome 90.0.4430.212（正式版本） （64 位）
搜狗浏览器 11.0.1.34700
OPERA浏览器 84.0.4316.31

**Bug 描述**
1、在进入RDP远程桌面使用过程中，使用输入法（搜狗输入法在网页中输入文字，经常无法输入逗号或句号，切换到英文即可输入（但输入的是英文逗号）。搜狗输入法版本（11.8.0.5496），手心输入法版本（2.7.0.1702），两种输入法均出现过此问题，但也不是每次都出现。
2、部分按键无法输入，切换到英文输入法，也无法输入字符，使用KeyboardTest软件检测键盘输入，发现是没有按键输入的。而且有时会触发系统的一些快捷键，例如单按D键，会最小化所有窗口显示桌面，好像是按了win+D键，此时点击一下右侧快捷键小箭头里的win+D键，即可恢复正常，但有时不会恢复正常。
**Bug 重现步骤(有截图更好)**
1.  暂时没发现如何再现以上问题，正常使用时输入文字不定时出现。两种jumper server版本以及三种浏览器均会出现此类问题

**Comment by wojiushixiaobai** [comment]
用远程的输入法而不是使用本地的输入法输入

**Comment by yww0926** [comment]
> 用远程的输入法而不是使用本地的输入法输入
明白了，刚试了试，把本地切到英文，可以使用远程的输入法，我再测试一下，谢谢。
