### ISSUE TITLE
[Question] 上传文件至WinServer失败

### ISSUE THREAD

**Issue by Gerogeqd** [jumpserver/jumpserver#7979]
jumpserver版本：v2.12.1
问题现象：在会话管理中登录Windows服务器，使用右边的文件传输传送小文件正常，传送大于十几兆的文件时，出现下图问题，请帮忙看下解决方法，谢谢
![20220326230627](https://user-images.githubusercontent.com/36184228/160245855-5b49ca69-c420-4b33-9be0-180750f8b2d1.png)

**Comment by LeeEirc** [comment]
看下是否有其他 nginx 负载，限制了上传大小

**Comment by Gerogeqd** [comment]
没有其它负载，只一套nginx，现在发现Windows 10M左右没有问题，再往大了就开始出上面的问题，Linux传个几百兆大的文件都OK

**Comment by Gerogeqd** [comment]
找到原因了，WAF上限制了上文件文件的大小，感谢 @LeeEirc
