### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by k4n5ha0** [jumpserver/jumpserver#7980]
**JumpServer 版本(v1.5.9以下不再支持)**
2.19.2

**浏览器版本**
所有

**Bug 描述**
ip地址可伪造

**Bug 重现步骤(有截图更好)**
1
![image](https://user-images.githubusercontent.com/22064977/160265041-5e3293d8-4e69-4563-bda1-1e7e200286f7.png)

![image](https://user-images.githubusercontent.com/22064977/160265030-85a23e8d-3681-43f3-83b6-f4204059de5f.png)

3.

**Comment by wojiushixiaobai** [comment]
既然你知道这个问题，那么你应该知道这个问题的解决方案才对。
我们没法判断用户部署的环境，你可以通过修改最上层的反向代理来解决此问题。
目前我们的默认配置是
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
```
此方式常用于前面还有反向代理，如果需要获取用户真实 ip 则需要通过 $proxy_add_x_forwarded_for
如果本身就是对外的最终出口反向代理，则需要使用 $remote_addr，通过 tcp 层获取用户真实 ip，防止伪造
```
proxy_set_header X-Forwarded-For $remote_addr;
```
