### ISSUE TITLE
[Question] ha配置https证书后，使用域名登录时，链接会跳转https://ui/#/，丢失域名字段

### ISSUE THREAD

**Issue by luchunxia123** [jumpserver/jumpserver#7986]
**请描述您的问题.**
使用自签的证书
![1648519980](https://user-images.githubusercontent.com/50660925/160518829-6d50028e-9a04-4e97-a6dc-3884e8ea990f.png)
ha配置文件截图
![1648519980(1)](https://user-images.githubusercontent.com/50660925/160518873-93e3919a-c477-4f98-a412-4a5ee1ddcbb7.png)
修改hosts文件，10.130.12.196 secjump.navinfo.com
使用域名登录
![1648519980(3)](https://user-images.githubusercontent.com/50660925/160519083-78c8fe7b-f28d-459b-82e7-9dcdf88d1444.png)
登录成功后，链接变为
![1648519980(4)](https://user-images.githubusercontent.com/50660925/160519017-43a7787e-8e79-49ef-9c56-d1a07eb65a60.png)

链接变为 https://ui/#/   ，缺少了域名

**Comment by wojiushixiaobai** [comment]
[nginx ssl 部署](https://docs.jumpserver.org/zh/master/admin-guide/proxy/)
