### ISSUE TITLE
[Bug] 推送系统用户为 sa 的用户报ansible语法异常

### ISSUE THREAD

**Issue by liwenson** [jumpserver/jumpserver#7987]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.17.3 GPLv2.

**浏览器版本**
Google Chrome 版本 99.0.4844.82

**Bug 描述**
推送系统用户为 sa 的用户报ansible语法异常, 报异常的都是最近购买的阿里云主机，不清楚是阿里云主机禁用了sa 关键字，还是jumpserver ansible脚本的问题

**Bug 重现步骤(有截图更好)**
推送系统用户到平台: [unixlike]
主机数量: 1
PLAY [推送系统用户到入资产: sa] ***************************************************************************************************************************
TASK [Add user sa] ******************************************************************************************************************************
ok: [ali02-prod-xxxx-cluster-wms-05]
TASK [Add group sa] *****************************************************************************************************************************
ok: [ali02-prod-xxxx-cluster-wms-05]
TASK [Set sa password] **************************************************************************************************************************
ok: [ali02-prod-xxxx-cluster-wms-05]
TASK [Set sa sudo setting] **********************************************************************************************************************
fatal: [ali02-prod-xxxx-cluster-wms-05]: FAILED! => {"changed": false, "msg": "failed to validate: rc:1 error:>>> /root/.ansible/tmp/ansible-tmp-1648522284.2223945-7873-97623960105974/tmpGFd14n: 语法错误 near line 122 <<<\n"}
PLAY RECAP **************************************************************************************************************************************
ali02-prod-xxxx-cluster-wms-05 : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
Task assets.tasks.push_system_user.push_system_user_to_assets[967fb17d-cbb2-4226-85c9-3331b7b24f92] succeeded in 8.325662525836378s: None

**Comment by wojiushixiaobai** [comment]
系统用户名称不要出现空格或者特殊字符

**Comment by liwenson** [comment]
没有使用空格和特殊的字符。从1.x 版本开始，一直都是使用sa作为用户名，之前的推送都没有问题，其他如ops的用户名推送也没有问题。

**Comment by ibuler** [comment]
应该是哪里有特殊字符了

**Comment by liwenson** [comment]
大佬们，有什么方式能排查下吗？虽然可以推送其他的用户名，但是需要更改很多的权限组，着实有点头疼

**Comment by wojiushixiaobai** [comment]
提示是语法错误，检查下系统用户的设置，比如 sudo 是否正确。
有时候 sudo 里面的路径不正确也会出现此问题，不同的操作系统，二进制执行文件的路径是不同的。

**Comment by liwenson** [comment]
感谢大佬，问题已经找到了，有同事在 sa 用户的sudo 里面添加了一个命令, 新的服务器是没有这个命令的。导致下发新的服务器就会报错
