### ISSUE TITLE
[Question] Mac下调试项目，编译guacamole不通过

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#7988]
mac环境，编辑guacamole不通过，更换了gcc版本到gcc-11无效，请教下如何解决呢？
![image](https://user-images.githubusercontent.com/39855929/160530496-3cb5f512-2891-4d57-981b-bc3c44c52a0a.png)

**Comment by wojiushixiaobai** [comment]
目前应该不支持在 macOS 编译，你可以用 Docker 进行编译

**Comment by lf-zhang** [comment]
> 

使用 docker 部署guacad成功
