### ISSUE TITLE
[Feature] 定时发送报告

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#7990]
**请描述您的需求或者改进建议.**
有两个需求，一个是可以选择几个用户，每次登录的时候可以发送邮件给指定的人告知登录情况；
第二个需求：希望可以定时发送用户访问资产的信息报表，可以包括用户的操作，比如数据库里的select、insert多少次等

**Comment by wojiushixiaobai** [comment]
企业版本可以满足第一个需求。
第二个报表需求推荐使用第三方软件自行实现，比如我司的另外一个产品 [DataEase](https://dataease.io/)
