### ISSUE TITLE
[Question] 如何使用paramiko模块连接到jumpserver

### ISSUE THREAD

**Issue by Jinbingchen** [jumpserver/jumpserver#7992]
需求：我已经在一台云服务器上部署好了jumpserver，并连接好了数据库。通过ssh可以进入，并在opt查看数据库。我希望能用python实现这一共能。
问题：代码如下所示（hostname最后两位以xxx替代）
import paramiko

client = paramiko.SSHClient()

client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

client.connect(hostname='35.78.xxx.xxx', port=2222, username='people', password='jbc1230jbc')

stdin, stdout, stderr = client.exec_command('df -h ')  # stdout 为正确输出，stderr为错误输出，同时是有1个变量有值

print(stdout.read().decode('utf-8'))

client.close()

运行结果为：

No PTY requested.

请问这个问题该如何解决？

**Comment by wojiushixiaobai** [comment]
```
client.connect(hostname='35.78.xxx.xxx', port=2222, username='people', password='jbc1230jbc')
channel = ssh.invoke_shell(term='xterm-256color')
channel.settimeout(10)
channel.send('p\r')  # 输入 p 回车
output = channel.recv(1024).decode('utf-8')
print(output)
ssh.close()
```
使用

**Comment by Jinbingchen** [comment]
嗯，完美的回答了我的问题，谢谢

**Comment by wojiushixiaobai** [comment]
#7549
