### ISSUE TITLE
[Feature] 消息订阅支持邮件

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#7994]
**请描述您的需求或者改进建议.**
目前消息订阅只支持站内信，希望支持邮件发送的方式
v2.20.1

**Comment by ibuler** [comment]
配置了SMTP 就支持了
<img width="802" alt="image" src="https://user-images.githubusercontent.com/17382885/161178507-2cc977dc-3b76-4cce-b379-291641d41574.png">
