### ISSUE TITLE
[v3.0 beta] ansible引起的推送，命令执行，获取资产信息卡顿bug

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#80]
bug现象：如题执行以上操作，有一台机器有故障，如资产不在线，会引起卡顿
bug分析：可能是由于没连接上，在等待timeout时间
bug测试：添加一台不存在的服务器，或写错端口

**Comment by ibuler** [comment]
@yumaojun03 看看设置timeout时间是否可以解决该问题

**Comment by yumaojun03** [comment]
ubuntu的install.py兼容做完后，会处理这个问题
