### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by samgang** [jumpserver/jumpserver#8008]
**请描述您的需求或者改进建议.**
希望同时支持用户名和邮箱登录

如果用户名是邮箱格式，在ssh直连主机时会因为用户名是邮箱格式多一个@造成连接不成功，如果都可以登录的话，直连用用户名，web登录用邮箱来进行登录

**Comment by wojiushixiaobai** [comment]
用户名包含@是吗？

**Comment by samgang** [comment]
是的

**Comment by samgang** [comment]
> 用户名包含@是吗？

是的

**Comment by ibuler** [comment]
不计划支持
