### ISSUE TITLE
[Bug] Connection websocket closed

### ISSUE THREAD

**Issue by 993639542** [jumpserver/jumpserver#8009]
**Bug 描述**
v2.15.4使用web终端出现Connection websocket closed

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/71875924/161004958-70ff6d97-5c04-462d-9094-67c54addff0c.png)
使用过程中出现Connection wesocket closed

**代理配置**
upstream jumpserver {
  server xxxxxx:80;
}
server {
 listen 80;
 server_name jumpserver.xxxxx.com;  # 自行修改成你的域名
 return 301 https://$server_name$request_uri;
}
server {
  listen 443 ssl;
  server_name          jumpserver.xxxxx.com;  # 自行修改成你的域名
  ssl_certificate      /opt/soft/nginx/conf/all.xxxxx.crt;  # 自行设置证书
  ssl_certificate_key  /opt/soft/nginx/conf/all.xxxxx.key;  # 自行设置证书
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets on;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4:!DH:!DHE:!DES:!ECDHE-RSA-DES-CBC3-SHA;
  add_header Strict-Transport-Security "max-age=31536000" always;
  ssl_prefer_server_ciphers off;

  client_max_body_size 5000m;

  location / {
    proxy_pass http://jumpserver;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}

**Comment by ibuler** [comment]
参考 https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf

**Comment by 993639542** [comment]
> 参考 https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf

我自己加的代理配置就是和这个一样的呀，难道自己加代理会有问题么

**Comment by 993639542** [comment]
> 参考 https://github.com/jumpserver/installer/blob/dev/config_init/nginx/lb_http_server.conf

我有注意到v2.15.4的jms_web容器即nginx，配置文件/etc/nginx/conf.d/default.conf只有lion那一部分的反向代理是加了websocket长连接的，请问和这个有关系么？如果我在主配置文件/etc/nginx/nginx.conf加上反向代理长连接配置，是否可以得到改善？
