### ISSUE TITLE
jumpserver上的用户如何设置密码登录，不需要密钥

### ISSUE THREAD

**Issue by chenhnty** [jumpserver/jumpserver#801]
[简述你的问题]
jumpserver上创建的用户，如何不用密钥登录，而只用密码就可以ssh登录jumpserver，并查看相关服务器信息
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by lvjzhong** [comment]
同问该问题，密钥登录的方式创建用户后登录不成功，想知道创建用户时如何修改为密码登录的方式，谢谢！

**Comment by 5262** [comment]
![default](https://user-images.githubusercontent.com/31202793/33158483-48904ad8-d045-11e7-8506-18afdd686b8e.png)
同问，配置了sshkey但实际使用时没有连接按钮。。。，可以用密码登录吗？

**Comment by ibuler** [comment]
0.3版本不支持，新版本是支持的
