### ISSUE TITLE
[Bug] web ui管理mysql 时，不能输入或正常显示中文

### ISSUE THREAD

**Issue by xiefei0826** [jumpserver/jumpserver#8010]

**Comment by xiefei0826** [comment]
![image](https://user-images.githubusercontent.com/46474161/161087958-0fab5747-e43d-40b3-8dae-f88eae9439fd.png)
标记的地方为中文

**Comment by ibuler** [comment]
我记得之前处理过，和环境变量 LANG 有关

**Comment by ibuler** [comment]
@LeeEirc 处理一下

**Comment by LeeEirc** [comment]
@xiefei0826 用的什么版本？怎么部署的？使用最新版本试试？
![image](https://user-images.githubusercontent.com/32626707/161181817-42e8e151-5d4d-4dd1-97c8-b51958145c22.png)
![image](https://user-images.githubusercontent.com/32626707/161182007-cbf65e91-6336-4998-9acd-2114bf30a71c.png)

**Comment by xiefei0826** [comment]
是最新版本呢，
![image](https://user-images.githubusercontent.com/46474161/161432791-6e0880b9-ae73-4a54-bb77-8d23f0da18d5.png)
![image](https://user-images.githubusercontent.com/46474161/161432822-5e16dd44-c1da-4659-962c-9554d28611d2.png)
后边图片是jumpserver 
![image](https://user-images.githubusercontent.com/46474161/161432845-57225e24-4e56-4086-92df-2fcc34b88a68.png)
刚升级了最新版本也是这样

**Comment by xiefei0826** [comment]
调整成了 
![image](https://user-images.githubusercontent.com/46474161/161433323-10639a86-f742-4789-9568-caf7e0b5ee5b.png)
或删除lang指定，也不行呢

**Comment by xiefei0826** [comment]
再次发现个问题，k8s容器里也不能输入中文，但是linux 服务器可以。 走linux 进入容器也可以，直接通过管理器，进入不行

**Comment by wojiushixiaobai** [comment]
测试无问题，以下是测试使用的命令
```bash
docker network create jms_net --subnet=192.168.250.0/24

docker run --name jms_mysql --network jms_net -d \
  -e MARIADB_ROOT_PASSWORD=weakPassword \
  -e MARIADB_DATABASE=jumpserver \
  mariadb:10

docker run --name jms_all --network jms_net --rm \
  -e DB_HOST=jms_mysql \
  -e DB_USER=root \
  -e DB_PASSWORD=weakPassword \
  --privileged=true \
  jumpserver/jms_all:v2.20.2 init_db

docker run --name jms_all --network jms_net -d \
  -p 80:80 \
  -p 2222:2222 \
  -e LOG_LEVEL=ERROR \
  -e DB_HOST=jms_mysql \
  -e DB_USER=root \
  -e DB_PASSWORD=weakPassword \
  -e DB_NAME=jumpserver \
  --privileged=true \
  jumpserver/jms_all:v2.20.2
```

**Comment by xiefei0826** [comment]
docker 启动是正常的。但是jms_all 不正常

**Comment by wojiushixiaobai** [comment]
@xiefei0826 我通过上方的命令启动测试无此问题，请提供复现的过程

**Comment by xiefei0826** [comment]
env LANG=C.UTF-8 /bin/bas  安装语言包，及配置这个。all默认的是安装的language-pack-en
