### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#8012]
**JumpServer 版本(v1.5.9以下不再支持)**

Version v2.20.1 GPLv2.

**浏览器版本**

Google Chrome
版本 99.0.4844.84

**Bug 描述**
消息订阅，监控告警邮件勾选无法取消，每隔一小时都有状态邮件通知， 危险命令，勾选无法添加，勾选后，切换页面就恢复默认了。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24754263/161187666-2a889c45-de75-4a40-9940-fe199764ed06.png)

**Comment by wojiushixiaobai** [comment]
测试通知取消添加无问题，有其他异常提示吗？

**Comment by jiangxianliang007** [comment]
有一个报错，不知道有没有关系 
![image](https://user-images.githubusercontent.com/24754263/161886688-79c35311-64e8-4217-8aa3-8e0d593a7798.png)

**Comment by jiangxianliang007** [comment]
升级 Version v2.20.3 后解决
