### ISSUE TITLE
[Question] 终端健康状况检查警告

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#8013]
UI站内信不定期有提醒“终端已离线: [Core] 5ba239f3650f”。
1.请问这个信息是什么意思？譬如什么服务当时会不可用吗？
2.Healthcheck频率参数已经修改如下，是否仍不足够
......
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -fsL http://localhost:8080/api/health/ > /dev/null"
                ],
                "Interval": 20000000000,
                "Timeout": 10000000000,
                "StartPeriod": 90000000000,
                "Retries": 3
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -fsL http://localhost:8080/api/health/ > /dev/null"
                ],
                "Interval": 20000000000,
                "Timeout": 10000000000,
                "StartPeriod": 90000000000,
                "Retries": 3
........
3.这个core服务是否有优化配置方法？譬如增加内存、cpu等资源。/opt/jumpserver/config.yml 这个文件都可以配置些什么？

版本：v2.20.1
            "Image": "jumpserver/core:v2.20.1",
            "Volumes": {
                "/opt/jumpserver/config.yml": {},
                "/opt/jumpserver/data": {},
                "/opt/jumpserver/logs": {}

终端健康状况检查警告
35 分钟前
[Core] 5ba239f3650f

    终端已离线: [Core] 5ba239f3650f

[Core] 4300ce1391c1

    终端已离线: [Core] 4300ce1391c1

[Core] 074489f78d41

    终端已离线: [Core] 074489f78d41

[Core] 7d2f0ae2bc79

    终端已离线: [Core] 7d2f0ae2bc79

......

**Comment by wojiushixiaobai** [comment]
忽略，等待我们优化此处检查

**Comment by 521chy** [comment]
[Celery]-VM-4-10-debian | 0 | 离线 
[Core]-VM-4-10-debian | 0 | 离线

手动官方安装，这两个组件经常离线。重启主要jms服务可以恢复，预计半小时后会离线。

**Comment by wojiushixiaobai** [comment]
不影响使用忽略即可
