### ISSUE TITLE
[连接机器提示:认证失败（用户名或密码错误）] 

### ISSUE THREAD

**Issue by yangruizeng** [jumpserver/jumpserver#8014]
jumpserver版本：v2.5.3
问题描述： 
1. jumpserver上推送用成功，连接测试也显示成功。 但是登陆报错： 提示：认证失败（用户名或密码错误）。
2. 在其它服务器通过私钥连接没有问题。 只有jumpserver登陆失败。
koko报错信息：
jms_koko     | 2022-04-01 14:54:56 [ERRO] Conn[49c3682c-e9ed-4c6a-9e1f-bf593ff69792] create ssh client (admin@dev02) err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
jms_koko     | 2022-04-01 14:54:56 [ERRO] Conn[49c3682c-e9ed-4c6a-9e1f-bf593ff69792] getting srv conn failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

要连接的目标服务器版本： 腾讯OS（CentOS Linux release 8.2.2.2004 (Core)）

**Comment by wojiushixiaobai** [comment]
资产的 openssh-server 版本多少？

**Comment by yangruizeng** [comment]
> 资产的 openssh-server 版本多少？
OpenSSH_8.8p1, OpenSSL 1.1.1g FIPS  21 Apr 2020

PasswordAuthentication yes 打开这个配置后可以连接了

**Comment by BigbigY** [comment]
我的版本是OpenSSH_8.9p1，但是我打开这个配置还是不行

**Comment by laster-bin** [comment]
> 
我同样是ubuntu 2204同样遇到这样的问题，是否有办法解决

**Comment by Linuxstyle** [comment]
我同样是ubuntu 2204同样遇到这样的问题，是否有办法解决

**Comment by wojiushixiaobai** [comment]
@Linuxstyle 修改 ssh 配置文件后重启下 ssh 服务即可

**Comment by KydPi** [comment]
@wojiushixiaobai 
我也遇到了同样的问题；在sshd_config开启了PasswordAuthentication yes，也无法jumps上连接，可以保证的是我和直连使用的是一样的用户和密钥；
报错信息：error: 认证失败（用户名或密码错误） Receive Connection closed
系统版本：Ubuntu 22.04.4 LTS
ssh版本：OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
