### ISSUE TITLE
[Feature] 希望会话连接能够左右拖动来自定义打开顺序。

### ISSUE THREAD

**Issue by lyc7456** [jumpserver/jumpserver#8017]
**请描述您的需求或者改进建议.**

## 截图演示需求

![](https://res.lyc7456.com/20220402100555.png)

## Feature1.希望会话连接能够左右拖动来自定义打开顺序。

因为有时候需要开好几个连接来执行一系列的操作，这些操作有些关联性很强，所以打开连接的顺序至关重要。

有时有临时打开的连接需要放到到前面某个连接前后，不得不把所有连接关闭重新打开一遍来重置我想要的连接顺序。

## Feature2.希望能够支持拖动来对单个会话窗口的宽度进行自定义调整。

有一些资产名称比较长，我知道鼠标移动上去能够动态的显示其全名，但是当打开连接数量较多时，为了能够分辨资产全名不得不频繁移动鼠标去显示其全名。

**希望以上两个Feature能够被支持，Thinks**。

**Comment by ibuler** [comment]
移动顺序这个需求，我们看看，打算使用 vscode 重构这个呢

**Comment by ibuler** [comment]
第二个需求应该是不行的，因为 chrome 的 tab, vscode 的tab 也都不支持 拖动长度
