### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xuhualin** [jumpserver/jumpserver#8024]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.20.0

**浏览器版本**

**Bug 描述**
特权用户认证方式只能是密码,密钥认证不生效

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
测试新版本是否任然存在此问题，如果 ssh 版本大于等于 8.8 需要等我们功能迭代

**Comment by xuhualin** [comment]
jumpserver版本:Version v2.20.2 GPLv2.
ssh版本:OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
还是不行

**Comment by xuhualin** [comment]
有预计修复时间不？

**Comment by wojiushixiaobai** [comment]
测试并无此问题，请仔细检查操作过程。

**Comment by xuhualin** [comment]
非bug，已解决，感谢支持
