### ISSUE TITLE
[Question] 开启 MFA 后，无法使用终端登录 Koko

### ISSUE THREAD

**Issue by CandySunPlus** [jumpserver/jumpserver#8025]
开启 MFA 后，用终端直接登录时提示选择 MFA Option，但是又没有 Option 给出。
<img width="403" alt="image" src="https://user-images.githubusercontent.com/502700/161382213-a7f7b351-7d8a-4ca4-b46a-3ea5c31aa793.png">

使用版本：
<img width="196" alt="image" src="https://user-images.githubusercontent.com/502700/161382268-d9cff0f3-4508-4849-a1db-c2b0a38bda5d.png">

**Comment by wojiushixiaobai** [comment]
shell 不是 bash？

**Comment by wojiushixiaobai** [comment]
请使用 bash 试试

**Comment by CandySunPlus** [comment]
Bash 下问题依旧
<img width="406" alt="image" src="https://user-images.githubusercontent.com/502700/162115901-ab9c959b-e275-4a11-8845-885e538beb6c.png">

**Comment by wojiushixiaobai** [comment]
无法复现，检查是否配置了 ~/.ssh/config 登录脚本

**Comment by CandySunPlus** [comment]
没问题了，是我的用户忘了绑定 MFA
