### ISSUE TITLE
[Bug] Remote app 添加 chrome 报错

### ISSUE THREAD

**Issue by dongyangguo2021** [jumpserver/jumpserver#8026]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.20.1版本

**浏览器版本**
360极速浏览器

**Bug 描述**
增加系统用户--添加Chrome协议用户--报错（chrome不是合法选项）

**Bug 重现步骤(有截图更好)**
1. 
![image](https://user-images.githubusercontent.com/102224178/161417276-72c8f70a-eb78-4fe9-b5db-b0a30db35707.png)
2. 
3.

**Comment by ibuler** [comment]
已解决 https://github.com/jumpserver/lina/pull/1633/files
