### ISSUE TITLE
升级时提示Table 'jumpserver.jms_oidc_rp_oidcuser' doesn't exist 

### ISSUE THREAD

**Issue by hugeng1979** [jumpserver/jumpserver#8027]
在从2.18.2升级到2.20.2时，在升级到数据库的时候提示这个，选择继续，升级实际上是成功的。
这个应该在之前升级到2.18.2时也有类似的错误，当时也是忽略且继续的。

提这个问题的原因，是因为在删除来源于LDAP的用户时报错，
<img width="681" alt="image" src="https://user-images.githubusercontent.com/35301810/161549020-e55a402f-902e-4a71-9365-e866fcedb11b.png">

升级时的提示：

4. 备份数据库
正在备份...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Error: Couldn't read status information for table jms_oidc_rp_oidcuser ()
mysqldump: Couldn't execute 'show create table `jms_oidc_rp_oidcuser`': Table 'jumpserver.jms_oidc_rp_oidcuser' doesn't exist (1146)
[ERROR] 备份失败!
备份数据库失败, 继续升级吗? (y/n)  (默认为 n): y

**Comment by wojiushixiaobai** [comment]
尝试修复一下表看看？

**Comment by hugeng1979** [comment]
不好意思，请问一下，如何修复表？

**Comment by ibuler** [comment]
正常的话，应该是有这张表的

**Comment by wojiushixiaobai** [comment]
```mysql
mysqlcheck -c --all-databases -uroot -p
```
