### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by liulian1978** [jumpserver/jumpserver#8028]
### k8s helm部署 后 gunicorn.log 日志报错
**JumpServer 版本(v1.5.9以下不再支持)**
2.20.2

**浏览器版本**

**Bug 描述**
k8s helm部署 后 gunicorn.log 日志报错
[2022-04-05 14:39:05 +0800] [21] [INFO] Starting gunicorn 19.9.0
[2022-04-05 14:39:05 +0800] [21] [INFO] Listening at: http://0.0.0.0:8080 (21)
[2022-04-05 14:39:05 +0800] [21] [INFO] Using worker: gthread
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-04-05 14:39:05 +0800] [26] [INFO] Booting worker with pid: 26
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-04-05 14:39:05 +0800] [27] [INFO] Booting worker with pid: 27
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-04-05 14:39:05 +0800] [28] [INFO] Booting worker with pid: 28
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-04-05 14:39:06 +0800] [29] [INFO] Booting worker with pid: 29
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)

**Bug 重现步骤(有截图更好)**
1. 
2. 
3.

**Comment by liulian1978** [comment]
![福昕截屏20220405144628372](https://user-images.githubusercontent.com/3723187/161695206-39d45a7c-5dde-4c3a-83a8-5cf82d7d5699.PNG)

**Comment by ibuler** [comment]
k8s的不太清楚

**Comment by liulian1978** [comment]
[2022-04-05.zip](https://github.com/jumpserver/jumpserver/files/8424658/2022-04-05.zip)
日志文件
![福昕截屏20220406154306304](https://user-images.githubusercontent.com/3723187/161922262-80fbf8f7-05c0-48a4-b773-45a231bbaba.PNG)
![福昕截屏20220406154531319](https://user-images.githubusercontent.com/3723187/161922698-0352958b-15ab-4594-aeda-1f2e7b7f4c18.PNG)

**Comment by wojiushixiaobai** [comment]
看起来是服务没有正常启动，确定服务器的资源是否足够运行此 pod
可以把 check 时间拉长，等待运行看看
