### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by micrsun** [jumpserver/jumpserver#8030]
**JumpServer 版本(v1.5.9以下不再支持)**
2.9.2

**浏览器版本**
Chrome 100

**Bug 描述**

Nessus扫描2222端口，报一个低危漏洞，“SSH弱MAC算法已启用" ，
	漏洞描述：
远程SSH服务器配置为允许MD5或96位MAC算法，这两种算法都被认为是较弱的。注意，这个插件只检查SSH服务器的选项，不检查易受攻击的软件版本。
	加固建议：
请与供应商联系或查阅产品文档以禁用MD5和96位MAC算法。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/41136860/161956482-31c65875-6a9b-4b9e-95c0-b659d5c03674.png)

2. 
3.

**Comment by ibuler** [comment]
低级别的，可以忽略吧

**Comment by ibuler** [comment]
@LeeEirc 看一下，看看好不好处理
