### ISSUE TITLE
[Bug] MFA关闭后查看系统用户密码还是需要输入动态密码

### ISSUE THREAD

**Issue by leoyip** [jumpserver/jumpserver#8032]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本** 
Firefox 98.0.2 (20220322144853)

**Bug 描述**
MFA关闭后，查看系统用户密码还是需要输入动态密码。

**Bug 重现步骤(有截图更好)**
1.  点击个人信息，进入设置多因子认证。
2. 点击“启用MFA”右侧按钮，切换为“off”
<img width="752" alt="1bb311387a78c4dd0009b2a44fbc628" src="https://user-images.githubusercontent.com/16930670/162137357-4c43f4f1-dd38-48cc-8b14-358fd67f7101.png">

3. 更新成功后转到控制台，点击资产管理——系统用户。
4. 点击一个系统用户， 切换到账号列表，点击查看，提示需要MFA码。
<img width="688" alt="42328e637b83993ae295473195ed2d9" src="https://user-images.githubusercontent.com/16930670/162137679-18a7dbfc-1200-402e-82d4-9b2c6762389a.png">

**期望结果**
1. 关闭MFA多因子认证后，应该不用再输入MFA码。如果需要MFA码，那应该提示去启用MFA码。

**Comment by wojiushixiaobai** [comment]
[JumpServer 参数说明文档](https://docs.jumpserver.org/zh/master/admin-guide/env/)
```
SECURITY_VIEW_AUTH_NEED_MFA=True         # 查看或导出密码，需要 MFA
```

**Comment by leoyip** [comment]
交互上不是那么符合逻辑

**Comment by ibuler** [comment]
查看一次后，有个有效期
