### ISSUE TITLE
jumpserver2.19社区版本能创建用户，不能更新和删除用户

### ISSUE THREAD

**Issue by yehesite** [jumpserver/jumpserver#8036]
**请描述您的问题.**
jumpserver2.19社区版本能创建用户，不能更新和删除用户，提交一直的转圈圈，然后报错，提示：删除失败 Error: timeout of 60000ms exceeded。服务重启过了，还是不行呢！

**Comment by wojiushixiaobai** [comment]
看看 core 的 jumpserver.log
```bash
docker exec -it jms_core bash
tail -f /opt/jumpserver/logs/jumpserver.log -n 200
```
