### ISSUE TITLE
[Bug] 全新安装2.20.2 ssh的主机无法连接

### ISSUE THREAD

**Issue by sfgiuggese** [jumpserver/jumpserver#8039]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
firefox　99.0 　64位

**Bug 描述**
docker部署的jumpserver　ssh的主机无法连接

**Bug 重现步骤(有截图更好)**
![图片](https://user-images.githubusercontent.com/45352156/162654393-a5781b24-dd72-410e-823e-9340b028a109.png)

logs显示这个
![图片](https://user-images.githubusercontent.com/45352156/162654441-36b96304-58be-4c21-81c2-f3ae885f805d.png)

**Comment by wojiushixiaobai** [comment]
allinone 部署的话，看看 koko 的日志
```bash
docker exec -it jms_all bash
tail -f /opt/koko/data/logs/koko.log -n 200
```

**Comment by sfgiuggese** [comment]
[koko.log](https://github.com/jumpserver/jumpserver/files/8463422/koko.log)

**Comment by sfgiuggese** [comment]
![图片](https://user-images.githubusercontent.com/45352156/162726979-85cfed00-22a0-4975-ac78-798588a49467.png)

**Comment by sfgiuggese** [comment]
![图片](https://user-images.githubusercontent.com/45352156/162727398-4e881d06-ae63-48c8-95b1-a28d1f2aa99d.png)

**Comment by wojiushixiaobai** [comment]
你的组件注册有误，从web终端管理删掉离线的组件，在容器里面删掉对应的key文件后重启容器
```bash
docker exec -it jms_all bash
rm -f /opt/koko/data/keys/*
exit
docker restart jms_all
```
