### ISSUE TITLE
审计session历史中不能播放操作录屏

### ISSUE THREAD

**Issue by cycwll** [jumpserver/jumpserver#804]
git
git clone https://github.com/jumpserver/jumpserver.git

docker-compose up 运行的，运行正常。
配置了资产，管理用户，系统用户，授权，终端连接操作正常

1、审计session历史中不能播放操作录屏
![image](https://user-images.githubusercontent.com/6410130/32780365-ed4667ae-c97b-11e7-8293-4f64def74e99.png)

2、命令记录不全（我执行了touch，echo， rm 等命令，只记录了echo命令）
![image](https://user-images.githubusercontent.com/6410130/32780400-06a7ca4e-c97c-11e7-9a33-bbdfe79b8ab6.png)

[注:] 完成后请关闭 issue

**Comment by cycwll** [comment]
看了一下说明，应该是0.4版本还不支持回放功能。
折腾了一下0.3.2  一直显示Connection Reset By Peer。按照这里的解决说明，都试了一遍还是不行。放弃了。
![image](https://user-images.githubusercontent.com/6410130/32819308-8b16ccbc-ca03-11e7-9120-aecf0829f740.png)
坐等0.4版本的回放功能了。

**Comment by gengkeye** [comment]
0.4版本的回放功能大概什么时候完成，有知道的吗？我也在等这个功能，实在不行只能自己写了。

**Comment by ibuler** [comment]
新版本已经支持了
