### ISSUE TITLE
[Bug] Docker Hub 里的 jumpserver/nginx 镜像更新问题

### ISSUE THREAD

**Issue by NHZEX** [jumpserver/jumpserver#8042]
1. `jumpserver/jms_nginx` 写着废弃，但`jumpserver/nginx`并没有新的镜像推送
2. `jumpserver/jms_nginx` 缺失部分版本标签，比如：`2.17.5`，`2.18.3`

**Comment by wojiushixiaobai** [comment]
请认真的看文档，你的疑问自然解决。
新版本中已经去掉 
```
jumpserver/nginx 
jumpserver/lina
jumpserver/luna
```
这三个镜像，整合为
```
jumpserver/web
```
如果你遇到此问题，表示你未按照文档的方式正确的升级或者安装。

**Comment by NHZEX** [comment]
感谢，我把`jumpserver/jms_nginx`替换为`jumpserver/web`后可以了
