### ISSUE TITLE
堡垒机对接ldap相关问题

### ISSUE THREAD

**Issue by okada8** [jumpserver/jumpserver#8049]
**请描述您的需求或者改进建议.**
堡垒机对接ldap后，只支持ldap用户登录堡垒机，但是怎样支持登录服务器时使用ldap用户

**Comment by zhongw** [comment]
使用动态用户名即可：
![image](https://user-images.githubusercontent.com/3071894/163307163-d81666b9-7236-406c-8ace-5e8cf09ed7cb.png)

**Comment by okada8** [comment]
我试试

**Comment by okada8** [comment]
可以了，谢谢大佬
