### ISSUE TITLE
[Feature] 希望支持红旗2、红旗3操作系统的批量改密

### ISSUE THREAD

**Issue by Fit2Cloud-Onedream** [jumpserver/jumpserver#8050]
**请描述您的需求或者改进建议.**
红旗2、3的openssh版本较老，希望JMS的批量改密能向下兼容老版本的openssh
报错截图
![76030fe2adf5b9e6c4ffe07885b3f8a](https://user-images.githubusercontent.com/80380041/163079956-3c86d0c3-27a8-4ce0-940b-41e2d6ec1644.png)

[root@localhost ~]# more /etc/asianux-release 
Asianux release 2.0 (Trinity SP3)
[root@localhost ~]# ssh -V
OpenSSH_4.0p1, OpenSSL 0.9.7a Feb 19 2003
[root@localhost ~]# more /etc/asianux-release 
Asianux Server 3 (Quartet SP3)
[root@localhost ~]# ssh -V
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

**Comment by wojiushixiaobai** [comment]
自行升级 ssh 版本

**Comment by ibuler** [comment]
等待重构完成 平台
