### ISSUE TITLE
[Question] LDAP还未导入用户，LDAP用户就可以登陆堡垒机，但无法在用户列表中找到，无法授权资产。

### ISSUE THREAD

**Issue by Coylexiao** [jumpserver/jumpserver#8063]
**请描述您的问题.**
版本：v2.11.1
有个新用户，管理员没有从ldap中导入，但他可以登陆堡垒机，现在管理员需对对这个新用户授权资产，但在用户列表中无法找到这个用户，在ldap导入界面看到状态，用户是已导入的，现在需要怎么处理，才能在用户列表中显示这个新用户？
这也算是一个BUG吧，未导入的用户可以登陆堡垒机，不知道在以后的版本是否已修复这个问题。

**Comment by wojiushixiaobai** [comment]
新版本已修复此问题
