### ISSUE TITLE
[Question] 文件管理，向网盘里复制文件速度非常慢，服务器外网带宽没问题

### ISSUE THREAD

**Issue by nobita215** [jumpserver/jumpserver#8072]
**请描述您的问题.**
一直就是几百kb的速度。
![screenshot-20220416-080735](https://user-images.githubusercontent.com/12522734/163653964-7e178546-a005-499f-b57d-7a79d58fcb88.png)

**Comment by wojiushixiaobai** [comment]
看起来是 资产到 堡垒机的速度有问题
