### ISSUE TITLE
[Feature] 希望在Pod文件管理中增加对无ssh服务的Pod的支持

### ISSUE THREAD

**Issue by zhangzhangzf** [jumpserver/jumpserver#8073]
当前对于Pod中文件管理时，需要在Pod中有ssh服务，通过sftp进行文件传输？
对于无ssh服务的Pod，无法在Jumpserver进行Pod文件的相关操作。
通过k8s接口完成Pod文件管理在技术上是可行的吧，我们讨论讨论。

**Comment by ibuler** [comment]
现在支持了

**Comment by zhangzhangzf** [comment]
> 现在支持了


> 现在支持了

请问从哪个版本开始支持的？

**Comment by jym503558564** [comment]
可更新至最新版本
