### ISSUE TITLE
jumpserver 4.0  添加资产后为什么在终端上没有显示

### ISSUE THREAD

**Issue by linfeng1127** [jumpserver/jumpserver#810]
如题，我是用docker  进行安装部署的，安装过程没有提示设置邮件地址等信息，部署完成后，系统可以正正访问，但后台总是报COCO问题，另外，添加资产后，在终端界面也没有显示 。这系统怎么使用啊？请高人指教 ，谢谢！

![Uploading 1.png…]()

**Comment by justhonor** [comment]
终端界面没有显示？是指的是点击资产后，没有出现之前添加成功的资产吗？

**Comment by fanghao1028** [comment]
我的也是，前一天配置完还能在终端界面看到，第二天再看就没有了

**Comment by ibuler** [comment]
新版本查看是否还存在该bug
