### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by nondevops** [jumpserver/jumpserver#8103]
**请描述您的问题.**
我们有分布在全国各地的门店，每个门店有windows系统的电脑和Ubuntu系统的电脑，如何通过jumpserver管理分布在全国各地门店里面的电脑呢？可以提供下思路和配置案例吗？

**Comment by ibuler** [comment]
比较复杂，因为没有agent，所以代理方式不行

**Comment by wojiushixiaobai** [comment]
组网后使用 jumpserver 管理
