### ISSUE TITLE
[Bug] 从1.5.4-2升级至2.20.3 左侧会话管理等侧边栏消失不见

### ISSUE THREAD

**Issue by feeops** [jumpserver/jumpserver#8109]
**JumpServer 版本(v1.5.9以下不再支持)**
2.20.3

**浏览器版本**

chrome 100

**Bug 描述**

采用docker组件升级

![会话管理](https://user-images.githubusercontent.com/92842117/164146803-b6abb3e5-22f9-4328-82a5-85b356b4d667.png)

**Comment by ibuler** [comment]
切换视图

**Comment by feeops** [comment]
> 切换视图

这些也太难找了，搞了两天时间，一直以为是我操作有问题～

**Comment by feeops** [comment]
官网和视频中，会话管理都是在左侧的，一直以为打开方式有问题

**Comment by ibuler** [comment]
官网视频没有及时更新

**Comment by ibuler** [comment]
优化一波，添加向导

**Comment by Totobo** [comment]
> > 切换视图
> 
> 这些也太难找了，搞了两天时间，一直以为是我操作有问题～

确实，我自己折腾了俩小时，实在没辙挨个看issue看到这个才知道要切换视图。。
