### ISSUE TITLE
0.4.0版本，运行需要输入字符的脚本彻底卡死

### ISSUE THREAD

**Issue by goldMonkey** [jumpserver/jumpserver#811]
[简述你的问题]

##### 使用版本
0.4.0

##### 问题复现步骤
1. 用web或终端连进服务器
2. 运行shell脚本，脚本需要输入字符，然后就彻底卡死，键盘输入什么都没反应了

##### 具体表现
![266518c1-e99e-4ed0-a56d-73829e00b8da](https://user-images.githubusercontent.com/9836254/32877510-d931884a-cadc-11e7-89ec-31025bf756cf.png)
运行脚本，在这个界面需要键盘输入，彻底卡死，ctrl+c也无法退出

##### 其他
![40f4e016-3971-4399-a568-153f56b50d30](https://user-images.githubusercontent.com/9836254/32877580-24b02c9a-cadd-11e7-9865-4961e6957aa7.png)
与此同时，在管理后台点击完成按钮，提示成功，但是界面刷新后session还在，多次点击完成按钮也无法结束。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
查看一下后台有没有报错

**Comment by awangcn** [comment]
我也碰到这个情况了，怎么解决呢 
![jumpserver 4](https://user-images.githubusercontent.com/25479435/33591515-e0e82d6c-d9c0-11e7-9721-8c275f23d736.jpg)

**Comment by ibuler** [comment]
fixed
