### ISSUE TITLE
希望增加一个账号认证直连功能解决传文件问题

### ISSUE THREAD

**Issue by micahfy** [jumpserver/jumpserver#812]
比如用户登陆账号 zhangsan ，名下有192.168.0.10；192.168.0.15的服务器
在ssh验证的时候 输入账号zhangsan@192.168.0.10  （或者用~等符号连接） 和zhangsan账号的密码，能够跳过登陆页面直连进192.168.0.10服务器，方便有些应用或者互传文件等功能。

##### 使用版本
 Jumpserver  0.4.0

**Comment by ibuler** [comment]
你可以使用 xshell等提供的expect功能直接登陆到服务器

**Comment by wojiushixiaobai** [comment]
@ibuler 老哥，expect貌似不能解决传文件的问题。。。我看0.4上面已经有这个选项了，加油。
