### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ipinco** [jumpserver/jumpserver#8122]
创建数据库登录用户时失败

2022-04-20 22:53:44 [log WARNING] Bad Request: /api/v1/users/users/
2022-04-20 22:53:45 [log WARNING] Bad Request: /api/v1/users/users/

![image](https://user-images.githubusercontent.com/3378774/164260650-6ca86965-18a4-4660-b250-51d353b680df.png)

**Comment by ibuler** [comment]
怎么没有显示系统角色呢

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/164365674-a633f8ed-9ddb-4e79-b735-7cac1ec3bb04.png)

**Comment by wojiushixiaobai** [comment]
自编译的组件，请重新检查组件版本

**Comment by ipinco** [comment]
原因找到了， 2.20.1 版本组件正确但确实是没显示角色，换成最新版本的 2.20.3 同时替换了 luna lina 到2.20.3 后已经可以了
