### ISSUE TITLE
[Bug] 数据量过大，jms_core容器会反复重启

### ISSUE THREAD

**Issue by feeops** [jumpserver/jumpserver#8123]
**JumpServer 版本(v1.5.9以下不再支持)**
2.20.3

**浏览器版本**

**Bug 描述**

我是从1.5.4迁移到2.20.3
数据量非常大，备份的sql文件都有2.1G

compose目录中的docker-compose-app.yml
在进行启动时，会进行数据库表结构的修改，修改时间过长
会导致容器健康检查不通过反复重启，重启会导致数据库修改不完整
最后即使启动成功了，数据库中也会有各种小问题

**Comment by ibuler** [comment]
2.1G 数据量应该还行，可以执行一下 ./jmsctl.sh upgrade

**Comment by feeops** [comment]
要先执行./jmsctl.sh upgrade，但文档中没有说明，可以补充一下
