### ISSUE TITLE
[Question] 版本升级从2.19.1到2.20.3报无法变更数据表结构

### ISSUE THREAD

**Issue by china-bigcloud** [jumpserver/jumpserver#8124]
![image](https://user-images.githubusercontent.com/25924469/164388223-9ce1aa2a-d638-43d8-9663-43de05b00caa.png)

![image](https://user-images.githubusercontent.com/25924469/164388156-d9e01700-6af8-45bc-982e-c7fc4bb8bf26.png)

**Comment by wojiushixiaobai** [comment]
字符集有问题，检查下

**Comment by china-bigcloud** [comment]
![image](https://user-images.githubusercontent.com/25924469/164390395-62c50dea-b51e-4f6f-bb56-fe670ea31226.png)

**Comment by china-bigcloud** [comment]
我使用文档中的创建语句
create database jumpserver default charset 'utf8';
并且我查看了备份SQL文件，也没有指定字符集？

**Comment by wojiushixiaobai** [comment]
看下 sql 里面是否有 COLLATE= xxx 的内容

**Comment by china-bigcloud** [comment]
> 看下 sql 里面是否有 COLLATE= xxx 的内容

没有 COLLATE= xxx 的内容

**Comment by wojiushixiaobai** [comment]
```bash
COLLATE= 
```
比如 COLLATE=utf8_bin

**Comment by china-bigcloud** [comment]
已解决，参考如下
https://github.com/jumpserver/jumpserver/issues/6918
