### ISSUE TITLE
[Bug] 我的资产和批量命令里面数量不一致

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#8125]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome 已是最新版本
版本 100.0.4896.12

jumpserver  Version v2.20.3 GPLv2.

**Bug 描述**

我的资产 有97台服务器，但在批量命令里面却只显示87台， 原因是我有2个特权用户，另外10台不显示的服务器和显示的87台服务器使用的是不同的特权用户。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24754263/164394646-809aaf87-f6ad-4eb8-bcc7-55930c187bbd.png)

**Comment by wojiushixiaobai** [comment]
右下角切换系统用户
