### ISSUE TITLE
[Bug] 终端资产排序错乱

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#8126]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

jumpserver  Version v2.20.3 GPLv2.

**Bug 描述**
一共97台服务器，用xshell 连接堡垒机后，分2页显示，但排序错乱了，比如我 a 开头的机器有9台，第一页显示5台，还有4台显示到第二页了。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24754263/164397128-d2490dc8-e58d-46d6-b7e0-2287f70df765.png)
![image](https://user-images.githubusercontent.com/24754263/164397227-7dde8288-8d98-4df6-ae25-2ce71dc251fe.png)

**Comment by LeeEirc** [comment]
xshell连接堡垒机的资产排序，是按照当前页的结果做出的排序，并不是所有授权资产的排序。

**Comment by jiangxianliang007** [comment]
> xshell连接堡垒机的资产排序，是按照当前页的结果做出的排序，并不是所有授权资产的排序。

问题是，开头名称相同的主机，为什么分开在2个页面显示。

**Comment by LeeEirc** [comment]
分页的数据结果，**并不是按照主机名排序**， 因此暂时只能以当前页结果排序。

**Comment by jiangxianliang007** [comment]
现在是按照什么排序的？有没有计划按主机名排序。要不然感觉会比较混乱。

**Comment by LeeEirc** [comment]
koko 默认是异步获取用户的授权资产，展示的时候，只排序当前获取的授权资产数据。如果资产少，可以调整 koko的加载逻辑，这样排序结果可能符合你的预期。
```
# ASSET_LOAD_POLICY=all          # all 则用户资产缓存本地搜索分页；默认异步加载资产, 异步搜索分页; 
```
