### ISSUE TITLE
修改管理员密码之后，页面终端看不见了

### ISSUE THREAD

**Issue by pineforever** [jumpserver/jumpserver#813]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue
![image](https://user-images.githubusercontent.com/8857671/32882428-48865d62-caef-11e7-9e70-48aee2caac03.png)

**Comment by ibuler** [comment]
重新登陆试试

**Comment by pineforever** [comment]
实在是不好意思，我们这个已经解决了，看到是同事将coco和账户删除了，但是添加上也是没用的，最后只能重新初始化了
