### ISSUE TITLE
Version v2.20.3，"特权用户" - "创建"，不能像普通用户一样有下拉菜单，故不能创建非ssh类用户

### ISSUE THREAD

**Issue by arkue** [jumpserver/jumpserver#8137]
如题
![新建位图图像](https://user-images.githubusercontent.com/26920402/164740160-3b7b2814-15f6-4e55-aa30-4f99e531f0b3.png)

**Comment by CharisLuo** [comment]
你好，    谢谢你的来信，我已收到，会尽快与你联系。罗诗梦

**Comment by arkue** [comment]
升级到Version v2.21.0，问题依旧。部署方式，allinone

**Comment by arkue** [comment]
![新建位图图像](https://user-images.githubusercontent.com/26920402/164751690-55c85300-fc3b-4638-a654-5101d46980de.png)

问题2，如图：
资产列表处显示正常，在资产授权处建立相同的对应关系。添加资产后，一些资产为何显示在资产树外侧？在web终端也就如此显示了，不知是bug还是操作有误

**Comment by arkue** [comment]
问题3，在客户端使用ssh -p 2222  jms用户@资产用户@资产ip@jms-ip，收到错误Remote side unexpectedly closed network connection，若ssh -vvvvv，收到错误Authentication failed，资产用户选择特权root还是系统其它用户均如此，与此同时在web-cli正常；在jms端LOG_LEVEL=DEBUG，只有“ [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True”，无它

问题4，既然为跳板机，【ssh -p 2222  jms用户@资产用户@资产ip@jms-ip】，有没有第一步ssh登录jms、第二部选择资产的方式，而不是【ssh -p 2222  jms用户@资产用户@资产ip@jms-ip】必须指定资产用户和ip？否则使用者还是需要针对每一个资产做ssh session配置。

**Comment by arkue** [comment]
问题234都已解决为用户配置错误。
问题1，变为无法连接 guacamole 服务器，docker jms_all:v2.21.1没有这个组件、需配置https://github.com/jumpserver/docker-guacamole-v1 还是https://github.com/jumpserver/docker-guacamole？
docker按jms_all:80->8080、guacamole:8080 ->8081配置，guacamole loglevel=debug，抓不到错误，jms web-cli仍然报同样错误

**Comment by wojiushixiaobai** [comment]
```bash
docker exec -it jms_all bash
/etc/init.d/guacd restart
```

**Comment by ibuler** [comment]
其实现在特权用户是原来的管理用户，主要是用来支持 devops 的，所以出现了这个问题
