### ISSUE TITLE
[Bug] 使用oidc方式认证登陆Jumpserver后，无法使用ssh方式连接到jumpserver

### ISSUE THREAD

**Issue by liuyongqing1** [jumpserver/jumpserver#8138]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.0 

**浏览器版本**
chrome 100.0.4896.127

**Bug 描述**
当我使用oidc 对接dex 认证登陆成功后，可以正常使用web终端，但 ssh CiQyMDY2OTkyMC01ZjliLTQxNDUtYjlkYy0yN2M0MjAyNTcw@192.168.xxx.xxx -p 30353
 
30353为koko 2222 端口（kubernetes nodeport）会提示输入密码 但是页面不能重置密码，使用公钥也不行。请问有什么办法oidc用户能通过ssh登陆吗

**Bug 重现步骤(有截图更好)**
1.  使用oidc验证
2. 使用ssh客户端登陆
3. 
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/13477384/164890953-cde8b901-435a-4711-8ee8-1107131c52ff.png">

**Comment by liuyongqing1** [comment]
更新状态：
       使用公钥方式可以登陆了。自己配置的问题。 
       有一个问题是不是密码方式不支持

**Comment by Halo1236** [comment]
使用临时密码功能

**Comment by liuyongqing1** [comment]
![image](https://user-images.githubusercontent.com/13477384/165008229-4eac6457-98b1-4064-933c-b49cfcbed554.png)
我这里的更新密码是灰色的

**Comment by ibuler** [comment]
config.txt 开启

AUTH_TEMP_TOKEN=true，然后看看 个人信息，新版本 v2.21
