### ISSUE TITLE
[Bug] 从web管理下载之后的文件名和下载之前的文件名不一样

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#8139]
**JumpServer 版本(v1.5.9以下不再支持)**
2.21.0

**浏览器版本**
Microsoft Edge  版本 100.0.1185.44

**Bug 描述**

从web管理下载之后的文件名和下载之前的文件名不一样
**Bug 重现步骤(有截图更好)**
1.  下载之前
<img width="793" alt="image" src="https://user-images.githubusercontent.com/44529247/164913196-b840a936-d6ed-4d08-bef8-37545d5817d9.png">

2. 下载之后
<img width="652" alt="image" src="https://user-images.githubusercontent.com/44529247/164913210-738864b2-99da-4ad5-9ba0-6b21a799ea39.png">

3.

**Comment by wojiushixiaobai** [comment]
无法复现，请检查是否是浏览器的行为或者安全软件的行为
