### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by netyjq** [jumpserver/jumpserver#8140]
**请描述您的问题.**
系统用户下面 普通用户特权用户，测试资产可连接性 或者 推送系统用户

一直打印 ...............................................................................................................................................................

我使用特权账号root 和 新建的 普通账户都是这个结果，但是我直接用特权账号，能登录跳板机，能正常使用，不知道是什么原因，麻烦帮忙看下

Version v2.16.1 GPLv2. Copyright FIT2CLOUD 飞致云 © 2014-2021

**Comment by wojiushixiaobai** [comment]
celery 不工作，尝试重启或者检查日志
