### ISSUE TITLE
[Question] 我的资产有”未分组“

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#8143]
**请描述您的问题.**
在web终端看到一些未分组资产。
但是这些资产在我对应的组里已经有了。
是我那里没配置好吗？
![图片](https://user-images.githubusercontent.com/38068938/164968779-dd425a9d-65ef-459d-8216-8e63b0a9dd35.png)

另外，本机不能连接本机。譬如：我的jumpserver 部署的ip是192.168.1.1 ，那么新增一个对应资产(192.168.1.1)：
提示：
开始连接到 普通用户@192.168.1.1 error: dial tcp 192.168.1.1 :22: connect: no route to host
Receive Connection closed
Connection websocket closed
我在本地控制台登录本机直接ssh本机是没问题的。

版本：Version v2.21.0
部署方式：docker

**Comment by wojiushixiaobai** [comment]
设置里面设置一下，把未分组关闭
