### ISSUE TITLE
配置完成之后SSH提示用户名密码错误

### ISSUE THREAD

**Issue by topsekadmin** [jumpserver/jumpserver#8146]
报错如下图：
![image](https://user-images.githubusercontent.com/59950798/164970385-3102bfa1-5a4e-47e1-9afc-4cb2fafdb37d.png)

资产配置里显示服务器都可以连接，如下图：
![image](https://user-images.githubusercontent.com/59950798/164970486-d523ad45-e885-4a72-8503-be17d6b6c7a4.png)

系统用户配置里也对应的服务器账号和登入密码
![image](https://user-images.githubusercontent.com/59950798/164970534-cdb9e85c-f642-4a7e-a7af-4e6836447140.png)

然后配置授权
![image](https://user-images.githubusercontent.com/59950798/164970577-50812015-85f4-4dca-a901-68cc57120dac.png)

请问是哪里出了问题？

**Comment by wojiushixiaobai** [comment]
检查系统用户

**Comment by ideamean** [comment]
同问, 一样的问题

**Comment by aiden0z** [comment]
看下授权规则里有没有配置正确的用户

**Comment by ideamean** [comment]
> 看下授权规则里有没有配置正确的用户

感谢指导，已解决。 
原因是： 机器里有一部分使用私钥登录，一部分使用用户名密码登录。 资产授权里没有给用户密码的机器增加授权规则。
不知道一楼兄弟是不是也是这情况
