### ISSUE TITLE
[Bug] 修改配置不生效

### ISSUE THREAD

**Issue by liuyongqing1** [jumpserver/jumpserver#8147]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.0版本

**浏览器版本**
100.0.4896.127

**Bug 描述**
在设置 中修改配置后不会生效

**Bug 重现步骤(有截图更好)**
1.  进入设置 安全设置 关闭开启水印后  再返回其他页面 再进入页面还是原来的值
2.本来以为nginx缓存 问题，但是发现nginx并没有配置，直接调用core接口返回的还是未修改的值

**Comment by liuyongqing1** [comment]
更正不是立即生效，应该得过一段时间。请问一下是有定期更新机制吗还是怎么

**Comment by wojiushixiaobai** [comment]
组件同步需要时间，大概1分钟左右

**Comment by liuyongqing1** [comment]
好的收到
