### ISSUE TITLE
[Question] SSO 申请出来的链接可以禁止多次登录吗？可以设置有效期吗？

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#8148]
**请描述您的问题.**
SSO 利用管理员 token 生成了登录 url，但是每个人拿到这个链接都可以登录，是否允许**只登录一次**呢
![image](https://user-images.githubusercontent.com/39855929/164976461-1e0841c9-bc80-421b-bfa5-c2a349fc5290.png)

设置了 token **有效期**没有效果，超过这个时间还是可以登录，这个有效期指的是什么的有效期呢？

**Comment by ibuler** [comment]
Get， 验证完后就失效
