### ISSUE TITLE
[mycat 分库分表中间件软件支持] 

### ISSUE THREAD

**Issue by chuqiao8250** [jumpserver/jumpserver#8154]
**请描述您的需求或者改进建议.**
希望db client 支持navicat 管理mycat 分库分表中间件软件

**Comment by ibuler** [comment]
原生mysql的协议，不打算扩展

**Comment by chuqiao8250** [comment]
现在很多用户多使用类似 mycat 的分库分表的中间件，除管理员外，用户直接操作mysql不多了
