### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by jarson2014** [jumpserver/jumpserver#8155]
**请描述您的问题.**
我们现在用的版本是 Version 1.4.6-2 GPLv2 ，想升级到最新版本，请教该如何操作？我看文档上的最低版本都是 V2.12.0 版本的文档，更低版本的都没有文档了。

**Comment by wojiushixiaobai** [comment]
- [未使用 installer 部署的用户请参考迁移说明迁移到最新版本](https://docs.jumpserver.org/zh/master/install/migration/)
