### ISSUE TITLE
[Feature] 关于Linux管理和文件上传便利性问题

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#8156]
目前已经使用Jumpserver很久了，大多数时间用于管理Windows资产，近期Linux资产开始增多并凸显出一些便利性问题，目前最为突出的就是默认文件上传路径为/tmp，可能对于运维人员来说无所谓，但对于开发和实施人员来说，大量Linux主机的操作，会影响工作效率。
希望后期能够考虑一下两个需求点：
1、Linux上传文件时可自主选择上传目录或使用默认目录；
2、通过链接方式调用第三方SSH客户端访问Linux资源。（如果该项能实现，可以忽略第一项）

望采纳，感谢。

**Comment by fengmikaelson** [comment]
你可以把默认文件上传路径改为/
这样就可以看到所有目录啊。剩下的就是权限控制的问题了。
他们也只能进去自己能看的目录。

**Comment by vzrs** [comment]
> 你可以把默认文件上传路径改为/ 这样就可以看到所有目录啊。剩下的就是权限控制的问题了。 他们也只能进去自己能看的目录。

我找到了路径配置，但是修改后没有效果，能否麻烦您简单描述一下更改方法，感谢！

**Comment by wojiushixiaobai** [comment]
系统用户里面自己定义
