### ISSUE TITLE
[Question] 是否支持限制文件上传和下载

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#8158]
**请描述您的问题.**
很多时候，我们虽然允许操作员远程操作终端，但是我们不允许某些角色/人员上传或下载远程设备文件。请问堡垒机是否有相关权限可以供配置？

环境：
docker
Version v2.21.0

**Comment by wojiushixiaobai** [comment]
授权管理里面有相应的权限设置
