### ISSUE TITLE
添加用户出现：[Errno 111] Connection refused

### ISSUE THREAD

**Issue by wangpengtai** [jumpserver/jumpserver#816]
[简述你的问题]
创建用户后无法推送邮件，手动勾选发送邮件后，确认保存后，会跳到错误页面error at /juser/user/edit/
[Errno 111] Connection refused
##### 使用版本
[使用的Jumpserver版本 0.3.2]

##### 问题复现步骤
1. 见截图
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/26785271/32929937-73c408b0-cb96-11e7-90db-905bb6354bc1.png)
![image](https://user-images.githubusercontent.com/26785271/32930019-e79d79f6-cb96-11e7-9d9a-f6517e8ab092.png)
![image](https://user-images.githubusercontent.com/26785271/32929956-95f7a54a-cb96-11e7-8bfe-3fd300e18fa5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
发送邮件失败了

**Comment by qinhaxx** [comment]
个人建议，您把python version 换成 2.7 试试
