### ISSUE TITLE
[Feature]  web终端不可以进行拖拽整合窗口

### ISSUE THREAD

**Issue by gglnp** [jumpserver/jumpserver#8163]
在web终端打开多个窗口后，想要将当前的窗口拖拽到指定窗口的后面，就像 SecureCRT 里建立的连接窗口一样，可以将当前的连接窗口进行拖拽到任意连接窗口的前后。
 
![2022-04-28_10-26](https://user-images.githubusercontent.com/61819511/165664188-a9919841-eb4a-4be8-ba99-a279e2410a2f.png)

**Comment by ibuler** [comment]
正在处理
