### ISSUE TITLE
koko/data/replay/xxx.cast 持续写入将磁盘打满

### ISSUE THREAD

**Issue by ronaldo-bo** [jumpserver/jumpserver#8164]
**故障情况**：从4月16号 -> 4月28日  连续13天 **koko/data/replay/2022-04-16/xxxsss.cast 文件一直写入数据并未自动清理**

**其他说明**：**4.16号的.cast文件抱歉当时未截图，没记错显示了很多diff 信息**，0416-0428期间正常使用 应该无特殊操作

**jumpserver版本**：v2.19.1

**提出问题**：
1.koko/data/replay 是存放什么信息的（官网有看到koko是负责ssh连接的）
2.什么情况下才会让 xxx.cast一直写入数据、怎样才能再次避免这种事件的发生呢？ 

如有答复，十分感谢

<img width="725" alt="image" src="https://user-images.githubusercontent.com/71818803/165669771-0d4267a0-c887-499c-adac-596c0db40bce.png">

**Comment by wojiushixiaobai** [comment]
这是录像文件，看看是不是有异常的会话导致，看看他最后执行的命令是什么，在命令记录里面

**Comment by ibuler** [comment]
是不是有持续上传下载什么的

**Comment by ronaldo-bo** [comment]
<img width="1455" alt="企业微信截图_b31dae09-ce6d-419f-98da-ff1ef91f690c" src="https://user-images.githubusercontent.com/71818803/165719922-ad6dbbfa-094b-4aaa-af02-00fc54345777.png">

上午echo空之后，下午发现还在写入，原来输出的不是diff命令。

----

查了下命令日志，到没看见特别的操作 异常会话的几率应该比较小些。

虽然上传下载的可能性比较大，不过并没有看到连续的上传下载记录，

tar cfz 20220415.tar.gz 2022041du -sh *  只看到这么1条错误命令
<img width="409" alt="image" src="https://user-images.githubusercontent.com/71818803/165743345-1e5f1db3-820d-4e92-8d5c-0759124bd665.png">


暂时的解决办法是：**直接 echo空后将log文件删除了**，目前观察没有新文件产生，如果再有类似的可能就找时间将koko容器重启来解决了。

**Comment by Aaron199** [comment]
我也遇到一样的问题
![image](https://user-images.githubusercontent.com/35388612/172519687-4ebb18fc-c8ee-42fa-95bc-78e3749873ab.png)

**Comment by ronaldo-bo** [comment]
> 我也遇到一样的问题 ![image](https://user-images.githubusercontent.com/35388612/172519687-4ebb18fc-c8ee-42fa-95bc-78e3749873ab.png)

没记错后边又出现了，最后重启了整个jumpserver就没碰见过了。保险起见还针对这个目录做了定时的清理脚本

**Comment by zcymantou** [comment]
这个是什么问题，要如何解决，只能此前koko的容器吗，重启后，好像还是会增长
