### ISSUE TITLE
[Bug] 2.21.0执行windows资产改密计划失败

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#8166]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome 100.0.4896.127

**Bug 描述**
2.21.0版本，执行windows资产改密计划时失败

**Bug 重现步骤(有截图更好)**
1.  windows资产安装openssh服务
2. 创建特权用户，并给windows资产关联特权用户
3. 测试特权用户可连接性（资产列表点击资产名称-系统用户-测试），显示成功
![image](https://user-images.githubusercontent.com/89773363/165671365-277c93e7-8bbc-4118-b370-faefdb68db5e.png)

![image](https://user-images.githubusercontent.com/89773363/165671266-6f2f575c-2c81-42ab-93b4-9111b6d524e7.png)

5.创建并执行改密计划，报错如图
<img width="905" alt="image" src="https://user-images.githubusercontent.com/89773363/165671194-b7bfbd88-cfd4-4c7d-b915-9a156faadf51.png">

**Comment by wojiushixiaobai** [comment]
bug，等待修复
