### ISSUE TITLE
linux rz命令上传文件大于500M无法上传

### ISSUE THREAD

**Issue by marginqm** [jumpserver/jumpserver#8167]
针对linux系统在web终端通过rz命令上传文件时，无法上传大于500M的文件，请问该如何解决这个问题呢？
本地jumpserver版本是：Version v2.13.2-101
<img width="777" alt="image" src="https://user-images.githubusercontent.com/10354473/165683642-b900c003-c06e-4a70-8377-05e834492978.png">

**Comment by ibuler** [comment]
rzsz 对大文件来说，上传下载效率不行，大文件请使用上传下载完成

**Comment by marginqm** [comment]
那如何解决500M的限制呢？针对“Version v2.13.2-101”的操作方法！
