### ISSUE TITLE
[Question] 小白问题：登录成功后能不能直接打开某一台服务器呢？需要改哪个地方？

### ISSUE THREAD

**Issue by 157677678** [jumpserver/jumpserver#8168]
现在登录成功后，进入的是 我的资产 这个页面，可以从这里选择 进入服务器 页面跳转为/luna/?login_to=5e88ee7e-d63f-449a-8a6f-2747b38c62c9，如果想登录后，直接进入这台服务器，应该改哪个地方？
（就是把登录成功页改为/luna/?login_to=5e88ee7e-d63f-449a-8a6f-2747b38c62c9）

**Comment by wojiushixiaobai** [comment]
/core/auth/login/?next=/luna/?login_to=5e88ee7e-d63f-449a-8a6f-2747b38c62c9

eg:
https://demo.jumpserver.org/core/auth/login/?next=/luna/
