### ISSUE TITLE
通过跳板机跳转到资产时，报错提示kinit

### ISSUE THREAD

**Issue by chenhnty** [jumpserver/jumpserver#817]
[简述你的问题]
通过跳板机跳转到资产时，报错提示“kinit: Clients credentials have been revoked while getting initial credentials”
只有通过“Ctrl+c”中断，才可以停止报错提示继续使用
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个错或许是你服务器端的ssh报的，手动ssh登陆一下
