### ISSUE TITLE
[Bug] mysql客户端连接报错

### ISSUE THREAD

**Issue by huwsun** [jumpserver/jumpserver#8170]
**JumpServer 版本(v1.5.9以下不再支持)**
2.21.1

**浏览器版本**

**Bug 描述**
mysql客户端连接
`mysql -u xxxx -pxxxxx -h xxx.com -P 33060 mysql`
提示错误
`rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused"`

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
关闭你的代理

**Comment by huwsun** [comment]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/4082111/167282874-f057d06b-8ae0-4ec0-bb09-c18748c7d5d7.png">
没有开代理，还是一样的报错

**Comment by wojiushixiaobai** [comment]
更新到 v2.21.4 试试，已经修复此问题

**Comment by huwsun** [comment]
升级测试可以了，非常感谢！
