### ISSUE TITLE
[Feature] ldap可以同步用户组，并支持同步多个ldap

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#8172]
**请描述您的需求或者改进建议.**
1、jumpserver可以对接ldap，且支持多个ou，拉取里面的用户，但是不能拉取组，目前公司有百十个组，同步过来用户在手动放到组里太麻烦了；
2. 公司有多个子公司，有各自的ad服务器，希望jumpserver可以同时对接多个ad，但是目前看来只能对接一个ldap服务器地址，可否考虑支持一下

**Comment by wojiushixiaobai** [comment]
应该做域信任，然后域信任登录。
支持多个域可能不太好判断登录用户名
