### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by abelyang** [jumpserver/jumpserver#8173]
**请描述您的问题.**
2.21.1 magnus 组件起不来 日志 报错 
![Dingtalk_20220428234934](https://user-images.githubusercontent.com/8252560/165793246-daea113c-8b77-4372-b31e-d2ee78b2b138.jpg)
![Dingtalk_20220428234934](https://user-images.githubusercontent.com/8252560/165793187-870571b0-dccd-49fa-98d0-41f1e6caa3df.jpg)

**Comment by wojiushixiaobai** [comment]
core异常，请检查core
