### ISSUE TITLE
[Feature] 希望支持用户设置登录后默认页面

### ISSUE THREAD

**Issue by yuchunyun** [jumpserver/jumpserver#8174]
**请描述您的需求或者改进建议.**
目前用户登录系统后默认页面是“概览页”，但在实际使用中用户都是希望直接去到资产页，能快速连接资产。所以希望有功能能让用户设置登录后的默认页面为“我的资产”页面。

**Comment by wojiushixiaobai** [comment]
后续看看如何优化下，我们的想法是希望用户能在登录时给与一些提示信息帮助企业解决一些安全问题。
我们在概览页面显示了用户上一次连接进行的一些操作，这些操作如果有异议的话可以帮助用户和管理员快速定位安全问题。
