### ISSUE TITLE
[Question] 任务执行界面黑屏

### ISSUE THREAD

**Issue by menglee37** [jumpserver/jumpserver#8179]
**请描述您的问题.**
是用镜像 jumpserver/jms_all:v2.20.2 部署的jumpserver。
部署成功后，资产管理界面，不论是推送普通用户还是测试连接性，不论任务是否执行成功，弹出的任务执行界面都黑屏，没有输出任何信息。
![image](https://user-images.githubusercontent.com/104623946/165921650-777a1077-228c-458e-9269-bf8f08b2e4c7.png)
![image](https://user-images.githubusercontent.com/104623946/165921757-d9abe58d-6957-4bd8-9e82-2369518d8ff8.png)

**Comment by wojiushixiaobai** [comment]
celery 组件未启动，或者检查日志是否有其他错误

**Comment by menglee37** [comment]
celery正常启动， jumpserver.log没有错误，celery.log没有内容，执行任务时候，celery_ansible.log 和 celery_default.log有对应日志产生

**Comment by menglee37** [comment]
并且无法执行批量命令，界面一直显示等待
![image](https://user-images.githubusercontent.com/104623946/166892921-51a82987-f480-4449-a3f9-9bc84bbb8e8e.png)

**Comment by menglee37** [comment]
并且无法执行批量命令，界面一直显示等待
![image](https://user-images.githubusercontent.com/104623946/166892921-51a82987-f480-4449-a3f9-9bc84bbb8e8e.png)

**Comment by wojiushixiaobai** [comment]
如果组件无异常，那应该是反向代理配置有误导致（或者出口 slb 的 websocket 未正确配置）
以 nginx 反向代理为例：
```vim
server {

    listen 80;
    server_name demo.jumpserver.org;  # 自行修改成你的域名

    client_max_body_size 4096m;  # 上传文件大小限制

    location / {
            # 这里的 ip 是后端 JumpServer nginx 的 ip
            proxy_pass http://192.168.244.144;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```
- proxy_http_version 1.1;
- proxy_set_header Upgrade $http_upgrade;
- proxy_set_header Connection "upgrade";
