### ISSUE TITLE
SSH连接H3C网络设备无法使用backspace键

### ISSUE THREAD

**Issue by biliivan** [jumpserver/jumpserver#8181]
JumpServer 版本2.20.0以上

**浏览器版本**
各浏览器

**Bug 描述**
SSH连接H3C网络设备命令输入无法使用backspace键，

**Comment by ibuler** [comment]
按住 ctrl，这应该和 term 类型有关，你可以尝试使用 xshell 等工具连接上去看看是不是可以，如果可以查看一下当前 term 类型

**Comment by LeeEirc** [comment]
![image](https://user-images.githubusercontent.com/32626707/172768339-f3b26c82-8a5a-414a-9e03-12585d2908ad.png)
 新版本中试试修改这个选项为 是。
