### ISSUE TITLE
[Question] 导出历史会话记录提示504 gateway timeout

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#8184]
使用jumpserver2.15.3版本，通过UI界面导出历史会话记录，页面提示访问超时，后端web已设置以下参数还是提示超时，数据量16K左右。
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 6000;

**Comment by ibuler** [comment]
你这个就是因为输出处理导致的超过30s了

**Comment by liujunfei980** [comment]
> 你这个就是因为输出处理导致的超过30s了

已经搞定，在jms_web中的nginx加上以下参数可以正常导出数据了
proxy_connect_timeout 600;
proxy_send_timeout 600;
proxy_read_timeout 600;
send_timeout 6000;

**Comment by ibuler** [comment]
Ok
