### ISSUE TITLE
[Bug] MySQL禁止命令运行，会出现有时能禁止，有时不能禁止的情况

### ISSUE THREAD

**Issue by shendingjun** [jumpserver/jumpserver#8186]
**JumpServer 版本(v1.5.9以下不再支持)**
版本: v2.21.2

**浏览器版本**
Google Chrome 100.0.4896.127

**Bug 描述**
MySQL 5.7.28禁止命令运行，会出现有时能禁止，有时不能禁止的情况

**Bug 重现步骤(有截图更好)**
1. 执行show databases;命令
2. 出现如下图结果，同样的命令，会出现有时能禁止，有时不能禁止的情况
3. 
![123](https://user-images.githubusercontent.com/52272899/166205359-40265d05-c9da-4522-85d7-b9ed5801623b.jpg)

**Comment by ibuler** [comment]
命令解析没做好

**Comment by shendingjun** [comment]
> 解析没做好

^.*show.*database.*$
我是这样写的，那请问应该怎么写呢？

**Comment by ibuler** [comment]
方向键返回的吧，应该是后台没处理好方向选择

**Comment by LeeEirc** [comment]
这个等后续优化吧。一些操作记录还不太准确。
