### ISSUE TITLE
mysql客户端连接失败

### ISSUE THREAD

**Issue by Unic0rnLien** [jumpserver/jumpserver#8193]
使用的是docker镜像jumpserver/jms_all:v2.21.2

web终端里打开mysql，调起dbclient，发生错误：

1045 - rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9090: connect: connection refused"

33060端口没有经过代理。

翻遍github仓库，发现是wisp监听9090端口，进入jms_all容器中查看，没有进程在监听9090端口，在目录下没有看到关于wisp的文件和配置，wisp是否需要自己部署？

**Comment by wojiushixiaobai** [comment]
magnus 组件异常或者你的网络有问题，比如使用了代理之类的

**Comment by huwsun** [comment]
升级测试可用了，非常感谢！

**Comment by wojiushixiaobai** [comment]
更新到 v2.21.4 试试，已经修复此问题
