### ISSUE TITLE
[Feature] magnus 能否设置数据库连接帐号密码保持不变？

### ISSUE THREAD

**Issue by changeflyhigh** [jumpserver/jumpserver#8195]
**请描述您的需求或者改进建议.**
![图片](https://user-images.githubusercontent.com/30860085/167134778-249c2b29-4230-46a8-8d96-c60b9919328c.png)

**Comment by xiaohui1997** [comment]
确实需要这个需求，有些场景需要长时间使用数据库而并非为临时使用300s。希望可以控制过期时间。
