### ISSUE TITLE
command_store.save()方法报错

### ISSUE THREAD

**Issue by B9527** [jumpserver/jumpserver#820]
[简述你的问题]
.命令记录存数据时程序会报错！
##### 使用版本0.4.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]

##### 问题复现步骤
1. [步骤1] conmand_log .命令记录存数据时程序会报错！

解决方法：可自己重写command_store.save()方法。

[注:] 完成后请关闭 issue

**Comment by B9527** [comment]
> \jumpserver\apps\audits\backends\command\serializers.py

` class CommandLogSerializer(serializers.ModelSerializer):
    """使用这个类作为基础Command Log Serializer类, 用来序列化"""

    class Meta:
        model = CommandLog
        fields = '__all__'

    def create(self, validated_data):

        try:
            output = validated_data['output']
            validated_data['output'] = base64.b64decode(output)
        except IndexError:
            pass
        return command_store.save(validated_data)`


> \jumpserver\apps\audits\backends\command\db.py
`    def save(self,validated_data):

            command_log = self.model.objects.create(**validated_data)
            return command_log`

**Comment by ibuler** [comment]
已修复
