### ISSUE TITLE
[Feature] 禁用的资产是否可以对用户不显示

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#8204]
**请描述您的需求或者改进建议.**
把资产禁用后，目前是还能看到该资产。是否可以将禁用的资产隐藏起来不给用户看到呢？

**Comment by heatdrive** [comment]
![image](https://user-images.githubusercontent.com/100142472/181025867-8da15dd1-4620-4bc5-b6a8-3416192f3800.png)
该提示已经满足需求了吧
