### ISSUE TITLE
[Question] 怎么部署自已生成的ssl证书,来使用rdp的复制粘贴功能?

### ISSUE THREAD

**Issue by alvinsunalvin** [jumpserver/jumpserver#8205]
**请描述您的问题.**
使用了
openssl生成了自己域名的证书的crt和key文件,放在:
/opt/jumpserver/config/nginx/cert
并且修改了
/opt/jumpserver/config/config.txt中的ssl相关选项如下:

USE_LB=1
HTTPS_PORT=443
SERVER_NAME=jump.mybaidu.com
SSL_CERTIFICATE=cert/server.crt
SSL_CERTIFICATE_KEY=cert/server.key

然后运行了:
/opt/jumpserver-installer-v2.21.3/jmsctl.sh restart
重启了服务,jms_lb就一直处于restart状态，网页也无法通过https://访问堡垒机

**Comment by wojiushixiaobai** [comment]
```bash
docker logs -f jms_lb --tail 200  # 查看日志
```

**Comment by alvinsunalvin** [comment]
已经解决了  
日志里面显示:

nginx: [emerg] SSL_CTX_use_certificate("/etc/nginx/cert/server.crt") failed (SSL: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small)


网上查了一下 是openssl在生成证书的时候 密钥太弱了的原因 :
openssl genrsa -des3 -out nginx.key 1024
把这个改成openssl genrsa -des3 -out nginx.key 2048
就可以了

完整的生成证书过程:
cd /opt/jumpserver/config/nginx/cert
rm -f *.*
openssl genrsa -des3 -out server1.key 2048
openssl req -new -key server1.key -out server.csr
openssl rsa -in server1.key -out server.key
openssl x509 -req -days 3650 -in server.csr  -signkey server1.key -out server.crt
