### ISSUE TITLE
0.4.0在ubuntu上如何部署？

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#821]
我想在ubuntu上部署Jumpserver 0.4.0，但默认好像只支持centos哦？

##### 使用版本
 0.4.0

**Comment by hellorocky** [comment]
跟操作系统没有关系, 有Python3就可以了, Ubuntu也可以的

**Comment by ibuler** [comment]
查看centos的部署过程，然后尝试安装
