### ISSUE TITLE
[Bug] web终端快速点多个资产连接的异常现象

### ISSUE THREAD

**Issue by jjk334** [jumpserver/jumpserver#8210]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.20.3

**浏览器版本**
google chrome 100.0.4896.127

**Bug 描述**
1.web终端快速点多个资产连接的时候，大概率会出现连接不上资产的情况
2.还可能出现窗口分辨率不对的问题

**Bug 重现步骤(有截图更好)**
一、
![image](https://user-images.githubusercontent.com/77146761/167532350-8c16d7e5-39a7-4924-a705-c76a0d5c66b9.png)
二、
![image](https://user-images.githubusercontent.com/77146761/167532848-61fa5ad2-0e9d-4e3d-ba37-5bed53941384.png)

**Comment by wojiushixiaobai** [comment]
更新到最新版本看看
问题1 已经有优化，快速点击这个属于异常操作。
问题2 可能是你的系统配置终端大小

**Comment by jjk334** [comment]
你好，我更新到v2.21.4 现象还是一样的。
还有就是v2.21.4这个版本luna登录一个新资产都会有这个确认框。系统设置好像不能关闭。
![image](https://user-images.githubusercontent.com/77146761/167999368-f7e99fd2-65b5-49dd-b4df-f1f7ef65f1d5.png)

**Comment by jjk334** [comment]
你好，更新了v2.22.0。
1.web终端快速点多个资产连接的时候，大概率会出现连接不上资产的情况（已解决）
2.还可能出现窗口分辨率不对的问题（这个现象还是会出现，但是具体的复现流程不好复现，就是在打开窗口的时候会出现和分辨率不一致的情况）

**Comment by wojiushixiaobai** [comment]
分辨率问题暂时没法复现，请说明下环境，我这边测试下看看

**Comment by jjk334** [comment]
你好，复现的步骤也是批量打开终端比较会出现。您可以试试
