### ISSUE TITLE
[Feature]支持对spice协议虚拟桌面的直接纳管

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#8211]
**请描述您的需求或者改进建议.**
公司属于芯片设计类，目前对spice虚拟桌面的管理是刚需，了解了深信服的堡垒机是可以直接纳管的，JumpServer目前没看到，了解了可以通过远程应用发布客户端，但是肯定不如原生支持的体验好，看看JumpServer是否可以考虑一下

**Comment by LeeEirc** [comment]
guacamole-server 尚未支持此协议，目前就不考虑了。guacamole-server 对此协议的相关进展 详见[GUACAMOLE-261](https://issues.apache.org/jira/browse/GUACAMOLE-261?attachmentOrder=asc)

**Comment by ibuler** [comment]
那等待时机成熟再来看看
