### ISSUE TITLE
[Bug] 命令过滤掉了rm等命令，但是通过编辑脚本还可以实现rm操作。

### ISSUE THREAD

**Issue by l0w0z0** [jumpserver/jumpserver#8215]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-offline-installer-v2.21.2-amd64-192.tar.gz

**浏览器版本**
版本 101.0.4951.54（正式版本） （64 位）
**Bug 描述**
命令过滤中禁用掉rm命令，但是通过vi编辑脚本后还可以实现rm操作，并且vi操作不能被禁止。或者通过上传脚本，也可以执行rm操作

**Bug 重现步骤(有截图更好)**
1.  禁用rm，命令过滤掉。
2. shell窗口输入rm就可以禁止操作。
3. vi  111.sh
4. 输入 rm $1
5. 保存退出脚本。
6. 给脚本赋予执行权限。赋予执行权限这个也是要有的操作。或者上传带有执行权限的脚本也可以。或者上传压缩文件，文件里带执行权限。
7. ./111.sh file  还是能够删除文件。

**Comment by wojiushixiaobai** [comment]
你需要的是系统级别的命令拦截，需要自行定制化 bash，JumpServer 只是基于当前输入的字符串进行拦截
