### ISSUE TITLE
[Bug] 钉钉免密登录后打开Web终端，出现未登录状态。

### ISSUE THREAD

**Issue by rex5652** [jumpserver/jumpserver#8216]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
在钉钉工作台内免密登录后，在工作台点击“web终端”，此时会跳出钉钉用外部浏览器打开导致登录状态失效，需要输入用户名密码重新登录。
是否应该是点击“web终端“后继续在工作台的标签页内打开以保留登录状态？
还是用外部浏览器打开的时候携带token之类的就不用再登陆一次？

**Bug 重现步骤(有截图更好)**
1.  钉钉工作台内用免密登录Jumpserver
2.  点击右上角Web终端按钮
3.  此时会跳出钉钉用外部浏览器打开，出现未登录状态

**Comment by rex5652** [comment]
Version v2.21.3

**Comment by wojiushixiaobai** [comment]
钉钉是否可以像微信一样，使用默认浏览器打开

**Comment by jym503558564** [comment]
已知问题

**Comment by rex5652** [comment]
> 钉钉是否可以像微信一样，使用默认浏览器打开

默认浏览器就是外部的第三方浏览器。我不知道能不能在钉钉工作台内的新标签页打开。我个人希望是能通过外部浏览器打开，这样用起来效率和便利性会更好

**Comment by rex5652** [comment]
V2.22.2依然存在此问题

**Comment by rex5652** [comment]
> 这个应该是机制问题，必须要在 钉钉的里面打开网站才行

是的，要么web终端在钉钉的工作台标签页上打开。要么可以参考一下语雀，他们是通过标签页传递token，然后从外部浏览器打开网页实现自动登录

**Comment by rex5652** [comment]
v2.23.4 依然存在这个问题
