### ISSUE TITLE
生产环境，JMS已经接受COCO和LUNA的注册，但仍然授权失败

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#822]
[简述你的问题]
JMS已经接受COCO和LUNA的注册，但仍然报错：App auth failed, Access key error or need admin active it
##### 使用版本
JMS: V0.4
OS: CentOS7.4
env: Production
##### 问题复现步骤
1. git clone https://github.com/jumpserver/luna.git
2. 执行yum install 和 pip install
3. 修改配置文件config.py
4. JMS应用程序-终端中接受注册，填写相关信息

##### 具体表现[截图可能会更好些,最好能截全]
`(py3) [seven@node2-jmp40-release luna]$ python run_server.py `
`ERROR:root:Load access key failed`
`Using access key 2fe39726-3867-4e48-a022-13344a7369b3:***`
`WARNING:luna.service:App auth failed, Access key error or need admin active it`
`WARNING:luna.service:App auth failed, Access key error or need admin active it`

##### 其他
config.py中的配置如下：
---------------------------------------------------------------------
DEBUG = False
NAME = 'luna'
BIND_HOST = '0.0.0.0'
LISTEN_PORT = 5000
JUMPSERVER_ENDPOINT = 'http://0.0.0.0/'
----------------------------------------------------------------------

**Comment by hellorocky** [comment]
试试把keys目录下的.access_key隐藏文件删除, 然后再注册试试

**Comment by gengkeye** [comment]
这个试过了，没用

**Comment by gengkeye** [comment]
JSM日志报错：
172.16.7.254 - - [22/Nov/2017:22:26:36 -0500] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 403 43 "-" "jms-sdk-py/luna"

**Comment by gengkeye** [comment]
运行开发环境是可以的，但是生产环境就不行了。。我是用Apache+mod_wsgi部署的

**Comment by ibuler** [comment]
JUMPSERVER_ENDPOINT = 'http://0.0.0.0/'   ？这个地址？

**Comment by gengkeye** [comment]
> JUMPSERVER_ENDPOINT = 'http://0.0.0.0/' ？这个地址？

是的

**Comment by gengkeye** [comment]
服务器换成nginx+gunicorn之后，LUNA和COCO可以正常使用了。不知道是不是APACHE的配置出现了什么问题。

**Comment by ibuler** [comment]
0.5.0打算release了，之前的 0.4.0一直没有release，请关注
