### ISSUE TITLE
[Question] 请问开启OIDC认证后，本地用户还能登录吗

### ISSUE THREAD

**Issue by diannei** [jumpserver/jumpserver#8220]
**请描述您的问题.**
启用OIDC认证后，web访问自动跳转到授权地址，没有本地登录框，怎么解决呢？

**Comment by diannei** [comment]
我是按这个方式配得，对接Azure。https://baijiahao.baidu.com/s?id=1721116864346185647&wfr=spider&for=pc

**Comment by wojiushixiaobai** [comment]
?admin=1
比如：https://demo.jumpserver.org/core/auth/login/?admin=1

**Comment by diannei** [comment]
> ?admin=1 比如：https://demo.jumpserver.org/core/auth/login/?admin=1

可以登录了，谢谢
