### ISSUE TITLE
[Bug] 用jumpserver文件管理从交换机下载文件为空

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#8221]
**JumpServer 版本(v1.5.9以下不再支持)**
2.21.4

**浏览器版本**

**Bug 描述**
用jumpserver文件管理从交换机下载文件为空，跳过jumpserver用sftp直接登录交换机下载正常。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
目前 只支持 ssh 协议的资产

**Comment by ryswork1993** [comment]
ssh登录
<img width="458" alt="image" src="https://user-images.githubusercontent.com/44529247/167989796-b1590f3f-bd88-44b4-b664-d47f7b86a814.png">
sftp登录
<img width="472" alt="image" src="https://user-images.githubusercontent.com/44529247/167989877-ff57a586-5aef-4dde-89b0-53cb081479a7.png">
跳过jumpserver用sftp下载文件
<img width="632" alt="image" src="https://user-images.githubusercontent.com/44529247/167990047-44e1c485-57d7-45ba-badf-ccb3e50ece19.png">
登录jumpserver用sftp下载交换机文件
![image](https://user-images.githubusercontent.com/44529247/167990703-07d5fe6e-d5e4-4c54-9edf-cb339acdcebc.png)
![image](https://user-images.githubusercontent.com/44529247/167990715-cfa28b5e-7437-40db-94c9-7671eee2fa25.png)
用xftp工具登录jumpserver下载交换机文件
<img width="613" alt="image" src="https://user-images.githubusercontent.com/44529247/167990887-e03cb5b9-c3cf-4c21-8b54-3da6eda69514.png">

**Comment by LeeEirc** [comment]
看下 koko 是否有报错日志？

**Comment by ryswork1993** [comment]
> 看下 koko 是否有报错日志？

<img width="605" alt="image" src="https://user-images.githubusercontent.com/44529247/168214442-8419976b-dc91-4880-b96f-c908dec8b4bf.png">

**Comment by LeeEirc** [comment]
交换机型号？其他机器有这样的问题吗？是否被防火墙拦截？
