### ISSUE TITLE
[Feature] 移动文件之前弹出确认

### ISSUE THREAD

**Issue by fanthos** [jumpserver/jumpserver#8226]
**请描述您的需求或者改进建议.**
移动文件前最好弹出提示，避免错误操作。

[moveConfirm : false // Display confirmation dialog when moving items](https://github.com/Studio-42/elFinder/blob/84f07fd18a4fc91d769aef35bb26da9addf851c3/js/elFinder.options.js#L698)

**Comment by wojiushixiaobai** [comment]
web 文件管理？

**Comment by fanthos** [comment]
对。
我之前有一次手抖，把一个文件夹拖到了另一个文件夹里面，没提示直接移动了。

**Comment by wojiushixiaobai** [comment]
@LeeEirc 老哥能做吗

**Comment by LeeEirc** [comment]
这就加上

**Comment by LeeEirc** [comment]
新版本已经发布支持。
