### ISSUE TITLE
[Feature] windows资产使用WMI进行管理

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#8228]
**请描述您的需求或者改进建议.**
目前windows资产都是通过openssh进行管理的，但是openssh工具基本都不符合windwos系统标准基线，在安全合规要求高的公司
很难实施。是否可以使用windows原生的WMI管理工具，进行改密、账号管理等操作呢？

**Comment by ibuler** [comment]
WMI 无法配置网关吧
