### ISSUE TITLE
[Bug] 部分主机访问web终端无法进入

### ISSUE THREAD

**Issue by yanghuabin1202** [jumpserver/jumpserver#8230]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.21.3

**浏览器版本**
Microsoft Edge
版本 101.0.1210.39 (正式版本) (64 位)

**Bug 描述**
部分主机访问web终端页面一直等待加载中，调试发现 http://10.1.20.63/luna/main.321698d57f5ed35279e0.js 该请求返回状态码206，无相关资源返回
终端报错 GET http://10.1.20.63/luna/main.321698d57f5ed35279e0.js net::ERR_CONNECTION_RESET 206 (OK)

**Bug 重现步骤(有截图更好)**
1.  页面等待加载
![image](https://user-images.githubusercontent.com/30710267/168035674-bbe5e01e-4aae-4a7a-84bd-a2eeb60009c4.png)

2. 页面调试信息
![Snipaste_2022-05-12_17-02-23](https://user-images.githubusercontent.com/30710267/168035323-86359d14-2bc5-4080-9bb1-f128fbb7a9de.png)

**Comment by wojiushixiaobai** [comment]
无法复现，请说明下浏览器信息我们测试下。
也可以让用户检查是否配置了代理或者尝试更换浏览器测试

**Comment by yanghuabin1202** [comment]
### **针对不同浏览器**
我也尝试过Chrome和Firefox浏览器
**Chrome** 
![image](https://user-images.githubusercontent.com/30710267/168235331-a64bec0a-27e5-4329-8fc1-a4c87d2e179b.png)
![image](https://user-images.githubusercontent.com/30710267/168235632-4a5fb57d-06f5-448d-983e-36cac6e91755.png)

**Firefox**
![image](https://user-images.githubusercontent.com/30710267/168235712-8087f9b6-6d62-4b93-9334-4edc5545e96f.png)
![image](https://user-images.githubusercontent.com/30710267/168235819-46ce0365-2fec-474a-8201-0ca4f91ca188.png)
都是同样的情况，luna的 main.321698d57f5ed35279e0.js  文件无法下载成功

![image](https://user-images.githubusercontent.com/30710267/168236445-0972ed7e-be06-4530-a1eb-2a9fe7208540.png)
单独请求获取该文件资源，下载下来的是不完整的

### 关于代理问题
尝试过内网主机，也是会出现部分主机或笔记本无法访问，一步分访问正常，即所有的主机访问/ui 路径下的页面都正常访问，但是访问/luna下的就出现部分主机无法正常加载相关js资源

我也尝试过修改nginx的配置，增大其缓冲区，但是也没有改变。目前该版本的main.321698d57f5ed35279e0.js的体积约为1.4M左右，建议是否可以在下一个版本中将luna项目打包后的单个文件体积减小。

**Comment by wojiushixiaobai** [comment]
说明下部署过程，我这边无法复现此问题。可能需要检查部署的环境

**Comment by yanghuabin1202** [comment]
使用的是JumpServer installer中的 ./jmsctl.sh 进行安装和升级的

**Comment by wojiushixiaobai** [comment]
是否有安全设备或者waf等拦截了请求？

**Comment by archyese** [comment]
怎么样，解决了吗。我是内网部署，让后通过cloudfalre zero trust穿透出去。内网访问没有问题，但是通过cloudfalre代理的无法访问。
