### ISSUE TITLE
[Bug] db-client连接命令行执行报错：ERROR 1043 (08S01): Bad handshake

### ISSUE THREAD

**Issue by metaroad** [jumpserver/jumpserver#8233]
jumpsserver 2.21.4
配置时使用外置的数据库

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
使用db-client生成的连接命令行去执行，报错ERROR 1043 (08S01): Bad handshake

**Bug 重现步骤(有截图更好)**
1.  测试了3台主机的每台主机都有运行mysql数据库应用，其中1台应用数据库连接成功，2台应用数据库报错ERROR 1043 (08S01): Bad handshake
2. navicat连接正常
3. web-cli连接正常
请问这个bug如何解决？
![image](https://user-images.githubusercontent.com/76619644/168054876-e1ea60d0-39ba-4467-99d6-b519856a8bb2.png)
![image](https://user-images.githubusercontent.com/76619644/168054919-6862ff85-aeeb-4d6a-877a-59b073165bce.png)

**Comment by ibuler** [comment]
v22 版本修复了一波，用新版本看看
