### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by micrsun** [jumpserver/jumpserver#8234]
**JumpServer 版本(v1.5.9以下不再支持)**
2.21.4

**浏览器版本**
Chrome 100

**Bug 描述**
链接华为交换机，部分交换机升级固件后，SSH的 key exchange 秘钥交换算法进行了升级，目前仅支持
dh_group14_sha256  dh_group15_sha512  dh_group16_sha512  dh_group_exchange_sha256

貌似jumpserver 连不上，提示

开始连接到 BJ_NETDEVICE_通用@11.11.1.4 42.9
开始连接到 BJ_NETDEVICE_通用@11.11.1.4 error: EOF
Receive Connection closed
Connection websocket closed
![image](https://user-images.githubusercontent.com/41136860/168061617-6a55bd1b-f96e-4036-9e2b-bf35c4368985.png)

**Bug 重现步骤(有截图更好)**
1

2. 
3.

**Comment by LeeEirc** [comment]
目前仅支持以下 keyexchange 秘钥交换算法。
 ```
curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 
diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 diffie-hellman-group1-sha1 
diffie-hellman-group-exchange-sha1 diffie-hellman-group-exchange-sha256
```

看能否修改相关机器配置试试吧。
