### ISSUE TITLE
[Bug]  JumpServer 版本 v2.21.4    jumpserver/magnus:v2.21.4 unhealthy  always restart

### ISSUE THREAD

**Issue by xmskf** [jumpserver/jumpserver#8239]
umpServer 版本(v1.5.9以下不再支持)
JumpServer 版本 v2.21.3

浏览器版本
Microsoft Edge v100

Bug 描述

jms_magnus. 出现错误，容器状态一直为starting 或 unhealthy

jms_magnus ./entrypoint.sh  Up (health: starting)   0.0.0.0:33060->33060/tcp, 0.0.0.0:33061->33061/tcp,        
                                                                      54320/tcp 
2022-05-10 11:28:03 [FATA] 注册终端失败退出
Load config from env
{ComponentName:magnus Name:[Magnus]-localhost.localdomain-14df7b1c4692 CoreHost:http://core:8080 BootstrapToken:MDYzYTZhNGYtYzM4Zi0yMTQz BindHost:0.0.0.0 BindPort:9090 LogLevel:ERROR RootPath:/opt/magnus ExecuteProgram:/opt/magnus/magnus DataFolderPath:/opt/magnus/data LogFolderPath:/opt/magnus/data/logs KeyFolderPath:/opt/magnus/data/keys AccessKeyFilePath:/opt/magnus/data/keys/.access_key}
2022-05-10 11:22:05 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}
2022-05-10 11:22:10 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}
2022-05-10 11:22:15 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}
经过查找 根本没有/opt/magnus/data/keys/.access_key 这个文件

cannot access /opt/magnus/data/keys/.access_key: No such file or directory
Bug 重现步骤(有截图更好)
1、从v2.17.3升级上来，现有遇上这个问题

升级方法：
下载离线安装包

cd /opt
tar -xf jumpserver-offline-installer-v2.21.3-amd64-193.tar.gz
cd jumpserver-offline-installer-v2.21.3-amd64-193

./jmsctl.sh upgrade
./jmsctl.sh start

链接上一个issus
[[Bug] jms_magnus. 出现错误，容器状态一直为starting 或 unhealthy](https://github.com/jumpserver/jumpserver/issues/8212)
![2022-05-16-15:58:12](https://user-images.githubusercontent.com/6941905/168547165-e14b5c88-43e4-4a00-82af-25d3dbf51b17.png)

相关人员跟我说v2.21.4 已解决相关问题，实际问题并未解决。

**Comment by wojiushixiaobai** [comment]
根据提示，检查 core 组件是否异常

**Comment by wuweilin99** [comment]
我也遇到了一样的问题，版本为v2.21.4 ， 请求的话按照对应命令的返回都是正常的
![image](https://user-images.githubusercontent.com/33522254/168759680-dd640c7c-dc28-4f24-9cb7-0274686b5607.png)
![image](https://user-images.githubusercontent.com/33522254/168759836-5dfd14bb-f8ad-4196-9f27-2b9c42484a28.png)

**Comment by wojiushixiaobai** [comment]
@wuweilin99 你的问题是
```
service account registration disabled
```
注册服务已关闭
请到 web页面，安全设置里面把 `终端注册` 选择打开
![image](https://user-images.githubusercontent.com/24326988/168943910-1c9f9879-f283-475f-969f-861158a294d4.png)

**Comment by wuweilin99** [comment]
@wojiushixiaobai 还真是。。。。谢谢

**Comment by xmskf** [comment]
@wojiushixiaobai   您好，通过你提供的命令进行测试，结果如下，好像和你的返回结果是一致的

```bash
[root@localhost jumpserver-installer-v2.21.4]# docker exec -it jms_magnus bash
root@d6ad9a20ff45:/opt/magnus# curl http://core:8080/api/health/
{"status":true,"db_status":true,"db_time":0.004669189453125,"redis_status":true,"redis_time":0.0015075206756591797,"time":1652858571}
root@d6ad9a20ff45:/opt/magnus# curl http://core:8080/api/v1/terminal/terminal-registrations/
{"detail":"身份认证信息未提供。","code":"not_authenticated"}
```

**Comment by wojiushixiaobai** [comment]
@xmskf 加到开源群联系群主远程看看环境

**Comment by wojiushixiaobai** [comment]
环境问题导致的表字段丢失，需要修复表结构，非代码问题。
