### ISSUE TITLE
替换资产管理用户的bug

### ISSUE THREAD

**Issue by BackFire** [jumpserver/jumpserver#824]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0

##### 问题复现步骤
1. 任意选择一个管理用户
2. 用选择的管理用户替换任意资产的管理用户，就报错

##### 具体表现[截图可能会更好些,最好能截全]
![_2017-11-22_17-09-31](https://user-images.githubusercontent.com/5419211/33118810-ece91efa-cfa7-11e7-861d-ee7b11b30815.png)
![_2017-11-22_17-04-33](https://user-images.githubusercontent.com/5419211/33118814-f0671bc2-cfa7-11e7-9726-a1f3f9300747.png)

##### 其他
pip3 list结果
amqp (2.2.2)
ansible (2.2.2.0)
asn1crypto (0.23.0)
bcrypt (3.1.4)
billiard (3.5.0.3)
cachetools (2.0.1)
celery (4.1.0)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
coreapi (2.3.3)
coreschema (0.0.4)
cryptography (2.1.3)
decorator (4.1.2)
Django (1.11.7)
django-auth-ldap (1.2.16)
django-bootstrap3 (9.1.0)
django-filter (1.1.0)
django-formtools (2.1)
django-redis-cache (1.7.1)
django-rest-swagger (2.1.2)
django-simple-captcha (0.5.5)
djangorestframework (3.6.2)
djangorestframework-bulk (0.2.1)
dotmap (1.2.20)
ecdsa (0.13)
enum-compat (0.0.2)
eventlet (0.21.0)
Flask (0.12.2)
ForgeryPy (0.1)
greenlet (0.4.12)
gssapi (1.2.0)
idna (2.6)
itsdangerous (0.24)
itypes (1.1.0)
Jinja2 (2.10)
jumpserver-python-sdk (0.0.16)
kombu (4.1.0)
ldap3 (2.4)
MarkupSafe (1.0)
mysqlclient (1.3.12)
olefile (0.44)
openapi-codec (1.3.2)
paramiko (2.2.0)
passlib (1.7.1)
Pillow (4.3.0)
pip (9.0.1)
pyasn1 (0.3.7)
pycparser (2.18)
pycrypto (2.6.1)
pyldap (2.4.37)
PyNaCl (1.2.0)
pyte (0.7.0)
python-gssapi (0.6.4)
pytz (2017.3)
PyYAML (3.12)
redis (2.10.6)
requests (2.18.4)
setuptools (19.2)
simplejson (3.12.0)
six (1.11.0)
sshpubkeys (2.2.0)
uritemplate (3.0.0)
urllib3 (1.22)
vine (1.1.4)
wcwidth (0.1.7)
Werkzeug (0.12.2)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed
