### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by cywang4** [jumpserver/jumpserver#8249]
**请描述您的问题.**
新版jumpserver的录像存储，如何在jumpserver上打开查看呢？只能在终端设置里看到有录像存储，还需要去机器中的目录自己去找录像文件，平台上不提供下载和回放录像的功能了吗？

**Comment by wojiushixiaobai** [comment]
默认在web 页面的审计菜单里面进行审计。
![image](https://user-images.githubusercontent.com/24326988/168944034-33a45020-b4ff-46c8-90fe-a1ffd0aa59ff.png)

**Comment by cywang4** [comment]
多谢，我已经找到了，非常感谢你的邮件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Question]  (Issue #8249)





 
默认在web 页面的审计菜单里面进行审计。
