### ISSUE TITLE
[Question] 公司再用的一套jumper，打开/刷新登录页面都要2秒中，新搭建环境只要0.5秒

### ISSUE THREAD

**Issue by zhangdewan01** [jumpserver/jumpserver#8251]
**请描述您的问题.**
登陆/刷新登录页面的逻辑是怎么样的？

怎么解决这么高的延迟，已经排除资源、网络方面的问题。

**Comment by zhangdewan01** [comment]
或者换个问题，怎么能看到代码的执行过程

**Comment by zhangdewan01** [comment]
![image](https://user-images.githubusercontent.com/105709710/168777603-1723edc4-581b-4f74-90e0-d899808842c5.png)

**Comment by wojiushixiaobai** [comment]
如果开启了 https 的话，可以尝试把 http2 打开

**Comment by zhangdewan01** [comment]
没有打开https呢

**Comment by wojiushixiaobai** [comment]
那得自行排查下，如果直连也有此问题，可以尝试检查各个容器的 io 是否异常

**Comment by zhangdewan01** [comment]
主机io 测试是没有问题的，，怎么检查各个容器的io呢

**Comment by zhangdewan01** [comment]
![image](https://user-images.githubusercontent.com/105709710/169818281-9e6c9122-f181-4b4e-8321-620eae5c4d55.png)
重启服务器登录快了很多，web ssh 还是慢

**Comment by zhangdewan01** [comment]
这里是在做什么？

**Comment by zhangdewan01** [comment]
可以加个微信不 18969058870

**Comment by zhangdewan01** [comment]
web ssh 慢，这个一般是什么原因呢

**Comment by zhangdewan01** [comment]
我将数据库的数据导出后，迁移到另外一套相同版本的jumpServer上，发现是不卡的。

**Comment by wojiushixiaobai** [comment]
那可能是 jumpserver 所在的服务器可能存在性能问题或者一些内核参数需要调整
