### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rlivacdg/MySQL-python/

### ISSUE THREAD

**Issue by janshyxt** [jumpserver/jumpserver#826]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
使用的python是 3.5.2版本。安装报错，信息如下：    ImportError: No module named 'ConfigParser'
[root@haproxy24 install]# cd jumpserver/install && pip install -r requirements.txt
-bash: cd: jumpserver/install: No such file or directory
[root@haproxy24 install]# cd /opt
[root@haproxy24 opt]# cd jumpserver/install && pip install -r requirements.txt
Collecting django==1.6 (from -r requirements.txt (line 2))
  Using cached Django-1.6-py2.py3-none-any.whl
Collecting pycrypto==2.6.1 (from -r requirements.txt (line 3))
  Using cached pycrypto-2.6.1.tar.gz
Collecting paramiko==1.16.0 (from -r requirements.txt (line 4))
  Using cached paramiko-1.16.0-py2.py3-none-any.whl
Collecting ecdsa==0.13 (from -r requirements.txt (line 5))
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting MySQL-python==1.2.5 (from -r requirements.txt (line 6))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rlivacdg/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/tmp/pip-build-rlivacdg/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ImportError: No module named 'ConfigParser'
    

    ****
    

##### 其他

[注:] 完成后请关闭 issue

**Comment by eli261** [comment]
python3.5不支持安装 MySQL-python这个包，所以你需要修改
 jumpserver/install/requirements.txt这个文件，把其中MySQL-python==1.2.5这行删除掉，然后添加这行：
mysqlclient

**Comment by ibuler** [comment]
0.3.2版本仅支持Python
