### ISSUE TITLE
远程办公双屏幕显示问题

### ISSUE THREAD

**Issue by stayupupup2** [jumpserver/jumpserver#8266]
**请描述您使用場景：
因居家办公，为了控管办公室值班人员连接回办公室PC。
因此使用Jumpserver来进一步记录人员的使用情況。所以采用VNC方式远程。
远程过去不能够单屏幕切换，只能两个屏幕显示在同一界面中，所以不论是图标还是字体都很小，很不方便。

**Comment by stayupupup2** [comment]
求关注求关注~

**Comment by wojiushixiaobai** [comment]
双屏的问题暂时没法解决，可以临时屏蔽一个显示器或者本地也使用双屏然后全屏使用即可
