### ISSUE TITLE
【需求】登录界面能不能调整各列顺序？

### ISSUE THREAD

**Issue by DanielYWoo** [jumpserver/jumpserver#827]
比如我需要把hostname放到第二列，放到IP前面。可以配置么？

**Comment by gengkeye** [comment]
哪个登录界面？描述不清楚啊

**Comment by eli261** [comment]
![image](https://user-images.githubusercontent.com/1914870/33161645-c54d10be-d05f-11e7-89a3-5a496d062b06.png)
你说的是coco界面吧。那个要修改python源代码。很好改的。

**Comment by ibuler** [comment]
这个。。。

**Comment by hellorocky** [comment]
https://github.com/jumpserver/coco/blob/f5370346327e2c605e972b8d84ca4330e4b3c615/coco/interactive.py#L205  改改这个函数
