### ISSUE TITLE
[Question] 普通用户登录后，在资产列表中没有《可连接》字段的显示

### ISSUE THREAD

**Issue by beanmilk666** [jumpserver/jumpserver#8277]
普通用户登录后，资产列表没有《可连接》字段，无法知道哪些资产是可用的，在自定义列表字段配置中也没有该选项。
系统管理员用户可以看到《可连接》字段

**Comment by beanmilk666** [comment]
我的版本是v1.13.2

**Comment by ibuler** [comment]
因为现在的可连接存在问题，网络设备、或者不支持 ansible 的windows 无法探测，等待优化可连接方法后再做处理

**Comment by beanmilk666** [comment]
> 因为现在的可连接存在问题，网络设备、或者不支持 ansible 的windows 无法探测，等待优化可连接方法后再做处理

谢谢解释！不过我觉得“可连接”这个状态，我们最主要的是关注这个资产是否可以抵达（网络条件是否贯通），真正是否能够连接、认证等其他的问题我们并不关注，只需要知道这台资产还是不是在线就行了。所以我觉得探测到端口的连通性层面就可以了，网络通畅，啥都好说。至于其他问题，用户自行解决就好了。

**Comment by ibuler** [comment]
嗯，这个后续的确得优化一波，可以让用户自己确认这个连接性
