### ISSUE TITLE
[Bug] Version v2.22.0 本地Mysql客户端（Navicat Premium）连接超时后依然能够访问

### ISSUE THREAD

**Issue by zhangjiaxin281** [jumpserver/jumpserver#8279]
**浏览器版本**
Chrome 版本 101.0.4951.67（正式版本） （64 位）

**Bug 描述**
虚拟机中采用一键安装 Version v2.22.0  开源版本，当连接时间超过5分钟以后，本地Mysql客户端（Navicat Premium）依然能操作数据，不合理。
**Bug 重现步骤(有截图更好)**
1.  Web终端打开Mysql时采用本地Mysql客户端（Navicat Premium）测试连接成功并进入数据库维护界面；
2. 关闭浏览器右上角关闭按钮；
3. 连接超过5分钟以后刷新客户端依然能查到数据；
4. 再次浏览器打开后，在仪表盘中终止连接用户和在线会话时，再次刷新Navicat Premium刷新标数据依然可用，这时连接用户和在线会话数回复到未终止数
5. 再次在本地Mysql客户端Navicat Premium测试连接后，连接依然测试成功。

**Comment by wojiushixiaobai** [comment]
连接断开 5 分钟后再试
