### ISSUE TITLE
[Question] 本地客户端直连 Redis 连接不成功

### ISSUE THREAD

**Issue by zhangjiaxin281** [jumpserver/jumpserver#8280]
**请描述您的问题.**
堡垒机中Redis配置完成，在Web CLI 中能登录成功，但是在RDM客户端输入DB Client信息，点检测试测试失败。
版本：我用的Redis版本5.0.8、jumpserver版本2.22.0
疑问：我没有设置用户名，但是DB Client给出信息，不管输入不输入用户名都验证失败

**Comment by wojiushixiaobai** [comment]
当前不支持 RDM客户端

**Comment by zhangjiaxin281** [comment]
> 目前不支持RDM客户端

下个版本是否考虑支持RDM客户端，对于连接5分钟有效时间是否考虑用户自己定义配置。

**Comment by wojiushixiaobai** [comment]
适配 RDM 客户端需要时间，是否支持自定义时间我们还在考虑。
