### ISSUE TITLE
[Feature] 建议增加快速命令或命令片段功能

### ISSUE THREAD

**Issue by Subp66** [jumpserver/jumpserver#8282]
**请描述您的需求或者改进建议.**
可以在web控制台上增加快速命令功能，方便通过点击，自动输入大段命令。
可以有管理员设置全局快速命令，所有用户都可以使用，也可以由管理员限制用户私自创建。
也可以支持用户自己创建只有他本人的账号可以看到的快速命令。

这样会大大提高web控制台的工作效率，望采纳，谢谢！

**Comment by ibuler** [comment]
等待规划
