### ISSUE TITLE
[Feature] 建议增加web控制台批量连接服务器功能

### ISSUE THREAD

**Issue by Subp66** [jumpserver/jumpserver#8283]
**请描述您的需求或者改进建议.**
在web控制台同时打开100个窗口，右键点击其中一个标签，会有关闭所有、关闭右侧，关闭其它等。
希望也能增加批量连接的功能，比如可以允许在左边栏通过鼠标点击拉选一片区域，然后右键连接选中
或者可以在分类上右键，连接此分类下所有服务器。
还有一种情况，比如打开了100个窗口，批量做完一些操作后，执行了重启，过一会机器起来了，右键其中一个标签，可以有连接所有、或重连所有等！

**Comment by ibuler** [comment]
感觉有点复杂，欢迎 PR
