### ISSUE TITLE
[Bug] v2.22.0 mysql无法连接

### ISSUE THREAD

**Issue by gnfy** [jumpserver/jumpserver#8286]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
v2.22.0 启用DB Client无法连接数据库。

**Bug 重现步骤(有截图更好)**
ERROR 2003 (HY000): Can't connect to MySQL server on 'xxx' (111)

**Comment by gnfy** [comment]
[demo
](https://demo.jumpserver.org/)，这个刚试了一下，也无法连接。

**Comment by wojiushixiaobai** [comment]
自行检查网络和账号密码

**Comment by gnfy** [comment]
> 自行检查网络和账号密码

目前我们测试的情况是这样子的：
1. redis：db client 正常，web cli 正常。
2. mysql：db client 连接不上。web cli 正常。

就mysql的话，我们试了rds与自建的测试库，目前都是无法连接的。
然后，昨天还试了下你们提供的demo链接中的mysql db client方式，也是无法连接的。
因此，还期待项目方再核实一下该bug。

**Comment by wojiushixiaobai** [comment]
demo 的链接之前是无效的，昨天已经修改

**Comment by gnfy** [comment]
刚才试了一下，还是无法登录你demo链接给的地址。提示：ERROR 1043 (08S01): Bad handshake

**Comment by Aaron3S** [comment]
提示 **ERROR 1043 (08S01): Bad handshake** 的错误将在下个小版本修复

**Comment by wojiushixiaobai** [comment]
最新版本已经修复，请验证
@gnfy

**Comment by gnfy** [comment]
> 最新版本已经修复，请验证 @gnfy

我们的版本还没来得急升级。用你们的demo店铺看，目前还是无法正常使用的。 @wojiushixiaobai @Aaron3S

**Comment by wojiushixiaobai** [comment]
无法复现，此问题关闭
