### ISSUE TITLE
添加用户选择邮件发送方式，提交后服务卡死，日志无报错

### ISSUE THREAD

**Issue by qinhaxx** [jumpserver/jumpserver#829]
[简述你的问题]

##### 使用版本
Jumpserver版本 0.3.2

##### 问题复现步骤
1. 在用户组标签下，选择用户添加按钮
2. 填写用户信息，最后有一个选项，选择发送邮件，
3.只要选择发送邮件的方式，点击确认保存，服务就会卡死

4.去查看日志 tail -f /opt/jumpserver/log/jumpserver.log
日志显示如下：
2017-11-24 10:56:04,228 - user_api.py - DEBUG - 生成ssh key， 并设置authorized_keys

5.然后我去执行 ./service.sh status，显示如下：
jumpserver is running...                                   [  OK  ]

6.我执行 ./service.sh restart 重新登陆jumpserver 服务
新增加的用户也是成功的
![image](https://user-images.githubusercontent.com/11629750/33194087-549926c4-d108-11e7-8b0d-85f47adbad76.png)

这个问题，我该怎么排查和解决，或者是不是bug，求方案，谢谢🙏

我现在解决的方案，就是./service.sh restart

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/11629750/33193633-09debfd4-d105-11e7-8b87-9f8990b6c98e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可是发送邮件失败了，建议检查一下邮件配置，或者对方邮箱对不对

**Comment by a001189** [comment]
邮件配置为题，jumserver.conf 中 默认email_use_ssl = False ，改为True ；同时邮箱服务器端口改为ssl模式的端口，如163.com则为465

**Comment by qinhaxx** [comment]
非常感谢，问题已经解决。
解决办法：jumserver.conf 中 默认email_use_ssl = False ，改为True。
