### ISSUE TITLE
[Bug] Web终端登录失效时候的跳转问题

### ISSUE THREAD

**Issue by SC-zj** [jumpserver/jumpserver#8293]
**JumpServer 版本(v1.5.9以下不再支持)**
2.22.0

**浏览器版本**
Google Chrome 101.0.4951.67

**Bug 描述**
登陆失效（一段时间未登录）的时候通过api直接登录服务器无法自动重定向到登录界面，一直在反复加载。
登陆方式：/luna/?login_to=9898fe9a-2a9f-427d-b525-286d096cd920
账号状态：开启了MFA
游览器报错：[Intervention] Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. 

**Bug 重现步骤(有截图更好)**
1.第一次登录或者距离上次登录有一段时间
2./luna/?login_to=9898fe9a-2a9f-427d-b525-286d096cd920 跳转到堡垒机web终端界面
3.web终端界面一直在反复加载，无法正常连接服务器或者跳转到登录界面
4.报错图片：
![image](https://user-images.githubusercontent.com/70679694/169942841-62f1f395-cfd4-45e7-987b-89309d6f0dda.png)
5.手动打开堡垒机主页（登录界面）后，再打开 /luna/?login_to=9898fe9a-2a9f-427d-b525-286d096cd920 能跳转到登录界面，恢复正常

**Comment by SC-zj** [comment]
https://user-images.githubusercontent.com/70679694/170804961-fdc80017-c9c6-410d-9a01-1cbf29531fc4.mp4

1.这是早上同事发我的，这个问题的确是偶有发生，先登录JumpServer没问题。
2.其次我还发现了个bug，开启MFA认证后/auth/login/?next=/luna/?login_to=d7d2824a-336d-4f05-af4f-53aea8147cfd
会重定向到/core/auth/login/mfa/ 丢失了?next=/luna/?login_to=d7d2824a-336d-4f05-af4f-53aea8147cfd标志

**Comment by ibuler** [comment]
@wojiushixiaobai 想办法复现一下刷新的问题

**Comment by paddy235** [comment]
我也是这个现象

**Comment by paddy235** [comment]
我用火狐没问题，升级前还可以用谷歌浏览器，升级到这个版本就无法用了

**Comment by paddy235** [comment]
尝试过各种操作，包括清除缓存，使用无痕模式等，问题依然存在。

**Comment by paddy235** [comment]
版本 99.0.4844.84（正式版本）Fedora Project （64 位）
