### ISSUE TITLE
[Bug] terminal_command无法监控到处于screen或者tmux里面的命令

### ISSUE THREAD

**Issue by llseann** [jumpserver/jumpserver#8296]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.19.2
**浏览器版本**
Microsoft Edge
版本 89.0.774.45 (官方内部版本) (64 位)
**Bug 描述**
命令审计里面无法记录到screen或者tmux里面运行过的命令
**Bug 重现步骤(有截图更好)**
1.  以screen为例,screen -S test
2. echo "test"
3. 命令记录页面只能看到screen -S test   而无法看到echo "test"

**Comment by LeeEirc** [comment]
待调研，需要正确识别 screen 的状态。
