### ISSUE TITLE
请问一套环境下如何部署两套jumpserver

### ISSUE THREAD

**Issue by Sumiter0312** [jumpserver/jumpserver#8297]
**请描述您的问题.**
目前服务器上已经部署了一套jumpserver服务，现在需要再部署一套(还在当前服务器上) , 请问这个支持吗?

**Comment by wojiushixiaobai** [comment]
不支持，建议使用不同的资产进行部署

**Comment by moqi2011** [comment]
用docker不行？

**Comment by wojiushixiaobai** [comment]
@moqi2011 容器名称写死了，docker 不行
