### ISSUE TITLE
[Bug] 使用xshell连接终端，使用xshell快捷键，无法正确判断命令

### ISSUE THREAD

**Issue by shiweifei** [jumpserver/jumpserver#8299]
**JumpServer 版本(v1.5.9以下不再支持)**
版本: v2.21.2

**浏览器版本**
Google Chrome 100.0.4896.127

**Bug 描述**
使用xshell快捷键，无法正确判断命令；
偶现问题，影响体验。

**Bug 重现步骤(有截图更好)**
1. 使用xshell连接目标设备
2. 使用xshell 快捷按钮执行ps -ef命令
3. 再次执行任意命令 如cd /tmp，此时查看后台命令识别结果；

**Comment by LeeEirc** [comment]
技术实现问题，等后续优化。
