### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#8300]
**JumpServer 版本(v1.5.9以下不再支持)**
 v2.22.1 GPLv2

**浏览器版本**
火狐 100.0.1

**Bug 描述**
nginx错误日志：
2022/05/26 15:03:58 [error] 34#34: *2288 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/assets/cmd-filters/?search=&offset=0&limit=10 HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/assets/cmd-filters/?search=&offset=0&limit=10", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:03:58 [warn] 34#34: *2288 upstream server temporarily disabled while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/assets/cmd-filters/?search=&offset=0&limit=10 HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/assets/cmd-filters/?search=&offset=0&limit=10", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:04:19 [error] 34#34: *2288 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/assets/assets/?offset=0&limit=15&display=1&draw=1 HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/assets/assets/?offset=0&limit=15&display=1&draw=1", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:04:19 [warn] 34#34: *2288 upstream server temporarily disabled while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/assets/assets/?offset=0&limit=15&display=1&draw=1 HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/assets/assets/?offset=0&limit=15&display=1&draw=1", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:04:49 [error] 34#34: *2288 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/users/profile/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/users/profile/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:04:49 [warn] 34#34: *2288 upstream server temporarily disabled while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/users/profile/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/users/profile/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:09:22 [error] 34#34: *2411 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.20.44, server: , request: "GET /core/auth/login/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/core/auth/login/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:09:22 [warn] 34#34: *2411 upstream server temporarily disabled while connecting to upstream, client: 192.168.20.44, server: , request: "GET /core/auth/login/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/core/auth/login/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:09:35 [error] 34#34: *2425 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/settings/public/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/settings/public/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"
2022/05/26 15:09:35 [warn] 34#34: *2425 upstream server temporarily disabled while connecting to upstream, client: 192.168.20.44, server: , request: "GET /api/v1/settings/public/ HTTP/1.1", upstream: "http://[fc00:1010:1111:200::4]:8080/api/v1/settings/public/", host: "192.168.22.55", referrer: "http://192.168.22.55/ui/"

**Bug 重现步骤(有截图更好)**
1.  登录偶尔提示“连接websocket失败”
2. JS是刚装好的，按curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.22.1/quick_start.sh | bash 几乎是默认的安装方式
3.我加了台WIN2008,不能连接到，一直在转圈圈，客户端远程桌面测试正常。修改过系统平台，如Windows、Windows2016、Windows-RDP
![图片](https://user-images.githubusercontent.com/38068938/170438008-0e2a2cab-8e75-4b1b-8c2d-28e42d39f4fc.png)
![图片](https://user-images.githubusercontent.com/38068938/170438347-54c03d3d-3d55-4ffa-87f9-116fa370be17.png)

**Comment by wojiushixiaobai** [comment]
检查 jms_core 日志
