### ISSUE TITLE
[Bug] 安装失败

### ISSUE THREAD

**Issue by zy84338719** [jumpserver/jumpserver#8301]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
安装失败
6. Init JumpServer Database
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './compose/docker-compose-init-db.yml'
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './compose/docker-compose-init-db.yml'
Error: No such container: jms_core

**Bug 重现步骤(有截图更好)**
6. Init JumpServer Database
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './compose/docker-compose-init-db.yml'
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './compose/docker-compose-init-db.yml'
Error: No such container: jms_core

**Comment by wojiushixiaobai** [comment]
无法复现，检查安装过程是否有其他错误提示
