### ISSUE TITLE
[Bug] 账号列表中能看到密码明文

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#8302]
**JumpServer 版本(v1.5.9以下不再支持)**
2.19.2

**浏览器版本**

谷歌78
**Bug 描述**
资产账号那里点击查看密码，可以看到所有浏览器记录的账号明文密码；存在严重的安全风险

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![image](https://user-images.githubusercontent.com/93170709/170615960-634e450e-d172-4c0b-8d93-90a8fc1da6df.png)

**Comment by wojiushixiaobai** [comment]
就是这样设计的

**Comment by khy2021** [comment]
> 

但是这些账号，有的是其它web平台的登录账号密码。

**Comment by ibuler** [comment]
这个是浏览器存的，和 JumpServer 没关系
