### ISSUE TITLE
[Question] 请问docker方式安装完成后，首次登录的账号密码是什么

### ISSUE THREAD

**Issue by FX-Max** [jumpserver/jumpserver#8310]
**请描述您的问题.**
作者你好，使用docker-compose方式安装完成了jumpserver，打开直接是登录界面。
请问首次登录的账号密码是什么？
使用的配置文件.env文件和官方项目里面类似[https://github.com/jumpserver/Dockerfile/blob/master/config_example.conf](https://github.com/jumpserver/Dockerfile/blob/master/config_example.conf)，试了下其中的一些字符串，也都未登录成功。

**Comment by wojiushixiaobai** [comment]
默认用户：admin
默认密码：admin

**Comment by chendelin1982** [comment]
> **请描述您的问题.** 作者你好，使用docker-compose方式安装完成了jumpserver，打开直接是登录界面。 请问首次登录的账号密码是什么？ 使用的配置文件.env文件和官方项目里面类似https://github.com/jumpserver/Dockerfile/blob/master/config_example.conf，试了下其中的一些字符串，也都未登录成功。

Hi，docker-compose.yml 在哪里呢？

**Comment by wojiushixiaobai** [comment]
@chendelin1982
- https://github.com/jumpserver/Dockerfile
