### ISSUE TITLE
资产管理——系统用户页显示“资产数量”问题[Question] 

### ISSUE THREAD

**Issue by diaoz** [jumpserver/jumpserver#8312]
**咨询关于资产管理——系统用户页显示“资产数量”问题**

版本：2.22.1

请问下其显示的值是否是不正确的，我这边的配置方式是为每个资产创建一个对应系统用户。
总共资产有16台。

相关截图如下：
![捕获](https://user-images.githubusercontent.com/19204293/170900391-aca1db67-a3d6-4e74-8ba0-e9e0e5d0735a.PNG)

**Comment by wojiushixiaobai** [comment]
已知问题，授权错误导致。
