### ISSUE TITLE
[Question] 资产授权那里显示得特别慢

### ISSUE THREAD

**Issue by khy2021** [jumpserver/jumpserver#8313]
**请描述您的问题.**
点击“资产授权”，要转1分钟才能显示出来。
版本：2.19.2；资产规模在2W左右，资产授权有5k+.

**Comment by wojiushixiaobai** [comment]
检查下是哪个环节慢，先排除 io 和 网络 方面的问题

**Comment by khy2021** [comment]
> 检查下是哪个环节慢，先排除 io 和 网络 方面的问题

数据量大，跟IO和网络应该无关。就是业务逻辑或者sql性能问题

**Comment by wojiushixiaobai** [comment]
继续排查下，先确定是哪个环节出现的问题
