### ISSUE TITLE
./ Jms startup issue

### ISSUE THREAD

**Issue by misterocc** [jumpserver/jumpserver#8315]
Good Day,

I'm having an issue when I tried to start up the jumpserver, when I list the directory it's show jms folder was there but when I start up It's show: No such file or directory. 

Even I tried to run the "./jms -h" help function and it's having the issue like 

File "./jms", line 10, in <module>
  import django
ModuleNotFoundError: No module named 'django'

Can you please explain to me is there any step were wrong? I follow the guideline by below link

Thanks
<https://sourceexample.com/article/en/ebbcca5df55067588b4382a8a5933019/>

![Screenshot 2022-05-30 135334](https://user-images.githubusercontent.com/100667696/170925929-2089461f-416d-4f2e-8ba5-cc2903c736b4.jpg)

**Comment by wojiushixiaobai** [comment]
```bash
pip install -r requirements/requirements.txt
```
Installer see https://github.com/jumpserver/Dockerfile
