### ISSUE TITLE
[Bug] 14.2升级21.4，web ssh 连接报错

### ISSUE THREAD

**Issue by zhangdewan01** [jumpserver/jumpserver#8317]
**JumpServer 版本(v1.5.9以下不再支持)**
14.2升级21.4

**Bug 描述**
升级版本后，web ssh 报错，koko错误信息：
![image](https://user-images.githubusercontent.com/105709710/170930575-60fa149e-e84e-40c5-bd5d-d35760eb90dc.png)

**Bug 重现步骤(有截图更好)**
1.  新节点部署14.2版本，导入数据，使用正常
2.  升级到21.4，web ssh 报错
3.  查看日志
- 目标节点日志：
![image](https://user-images.githubusercontent.com/105709710/170930759-0dc438ac-59ef-45d2-9bec-504dc19a5079.png)
- koko日志：
![image](https://user-images.githubusercontent.com/105709710/170930575-60fa149e-e84e-40c5-bd5d-d35760eb90dc.png)

**Comment by zhangdewan01** [comment]
经过进一步的测试，发现只有老版本的suse，才无法连接。根据日志来看，应该是新版本的koko容器使用了gcm算法，在老的susu版本中不支持。

**Comment by zhangdewan01** [comment]
老版本不只一台suse，而且是生产环境的机器。这个不好改。

koko是在哪里有指定加密算法的，这个可以改吗？

不能改就只能回退版本了。。

**Comment by LeeEirc** [comment]
说一下 suse的版本 和 ssh server的版本，我验证下。理论上应该都是支持的。
 koko 使用的加密算法如下:
 ``` 
aes128-gcm@openssh.com chacha20-poly1305@openssh.com aes128-ctr aes192-ctr aes256-ctr 
arcfour256 arcfour128 arcfour aes128-cbc 3des-cbc
```

**Comment by zhangdewan01** [comment]
![image](https://user-images.githubusercontent.com/105709710/171149925-8e2294b1-c71f-4a2e-ac69-0261230a4ca8.png)
![image](https://user-images.githubusercontent.com/105709710/171149995-2dd1fbfa-0809-4f39-ba57-d6df02f4f48e.png)

**Comment by LeeEirc** [comment]
suse 的版本太旧了，无法复现你的环境。找了一个 sshd 6.2 的镜像测试了下，正常是可以连接的

![image](https://user-images.githubusercontent.com/32626707/171351472-97a05760-243d-469f-86ef-d3ecb90beee7.png)

![image](https://user-images.githubusercontent.com/32626707/171351847-5924f67c-4ef6-488a-b070-c277557f4fc9.png)

**Comment by zhangdewan01** [comment]
我测试的centos 系统也有ssh版本较低的，都可以连；
测试到只是suse 不行，也不排除是我们环境的suse 做过裁剪导致。
那这个issue我关了。

感谢！

网络不好，上周回复的没上传上。

**Comment by zhangdewan01** [comment]
最后还有个问题，koko 使用的加密算法，从14.2到21.4，有过什么变化吗？

**Comment by LeeEirc** [comment]
v2.14.2 和 v2.21.4 两个版本应该是没有变化的。

> 最后还有个问题，koko 使用的加密算法，从14.2到21.4，有过什么变化吗？

**Comment by zhangdewan01** [comment]
thanks ~
