### ISSUE TITLE
docker搭建0.3遇到的问题

### ISSUE THREAD

**Issue by lilithGao** [jumpserver/jumpserver#833]
1.添加用户，用户不能在终端登录跳板机
2.文档里写在容器启动之后进到容器里改jumpserver.conf里的url，但是并不能生效

jumpserver 0.3.2

1.用提供的dockerfile封装的文档搭建，搭建完成后，新增用户不能在终端登录jumpserver，报错如下
![image](https://user-images.githubusercontent.com/31029606/33355323-f4c0b6c0-d4f1-11e7-84e9-c9ce6a13ea3b.png)

我在容器里修改了/etc/shadow，把图中！去掉后，可以正常登录
![image](https://user-images.githubusercontent.com/31029606/33355366-2e0aed88-d4f2-11e7-92f6-9e941b161fac.png)
![image](https://user-images.githubusercontent.com/31029606/33355393-4914d0b2-d4f2-11e7-9fe1-62f1055d2322.png)

2.文档中说，启动容器后，修改容器内jumpserver.conf里的url，但是并不能生效？是否有别的办法设置url让他生效

**Comment by ibuler** [comment]
0.3 docker需要自己研究，并不推荐docker安装
