### ISSUE TITLE
[Question] How to configure SMTP serveur without username and password 

### ISSUE THREAD

**Issue by barto95100** [jumpserver/jumpserver#8330]
I test to configure smtp server email but is necessary to configure de username but my smtp server not accept the username because is configured of ip source to allowed or not the email send

Thank's

**Comment by wojiushixiaobai** [comment]
Unauthenticated SMTP servers are not currently supported

**Comment by barto95100** [comment]
maybe in future release ?

**Comment by wojiushixiaobai** [comment]
There are safety risks, so it is not recommended.

**Comment by wojiushixiaobai** [comment]
If you are using the mail proxy mode, you can configure the proxy for authentication.
There is no need for any authentication. We need to discuss it in an internal meeting.
