### ISSUE TITLE
[Question] Reset password URL (Localhost)

### ISSUE THREAD

**Issue by misterocc** [jumpserver/jumpserver#8332]
Hi Team,

When I created an user account and received an email with password reset link as below URL. 

I'm unable access if I'm not connected the internal network.

where can I change the URL from localhost to external link?

http://localhost:8080/core/auth/password/reset/?token=ObOwWZidu2naZXXpmkyT6Srd6vb9H

Thanks
![Jump Server reset password](https://user-images.githubusercontent.com/100667696/171540108-60bcc353-23c6-4af9-931f-566610859d4c.jpg)

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/171784475-f01579e1-53b6-49d0-930a-80bc7479ad65.png)
Reset.
