### ISSUE TITLE
在控制台选择了资产列表，选择自定义列表显示问题

### ISSUE THREAD

**Issue by 3721518** [jumpserver/jumpserver#8333]
资产列表--（右侧按钮）自定义列表字段，勾选了"备注"会显示备注信息，但在过了一段时间又自动变为不勾选状态了，请问是啥问题呢？ 
jumper（版本号v2.21.2）

**Comment by wojiushixiaobai** [comment]
cookie ？会话变更了吧

**Comment by 3721518** [comment]
> cookie ？会话变更了吧
您是说我勾选了备注，跟cookie有关系，会话变更会初始化，这太扯了吧，我设置了备注并勾选了它就是我想要它长期显示的，为什么会这样操作呢？
![image](https://user-images.githubusercontent.com/68690637/172997693-639c39a7-4182-4a95-a7f1-2e0ffeb106cc.png)

**Comment by wojiushixiaobai** [comment]
此行为不会写入数据库，只会保留在本地

**Comment by 3721518** [comment]
> 此行为不会写入数据库，只会保留在本地

需写入数据库，请问如何解决？

**Comment by wojiushixiaobai** [comment]
需要修改代码

**Comment by 3721518** [comment]
您好，这是个需求，能加入到您们的日常计划中吗？
或更高版本中有没有解决此问题呢，或待解决！

**Comment by jym503558564** [comment]
自定义列表的信息只存储在浏览器的本地存储空间，只对当前的浏览器（不是无痕浏览器）。当您换了浏览器或者无痕浏览器，这个设置就会失效
