### ISSUE TITLE
点击资产列表并创建节点后回车，列表自动刷新显示问题

### ISSUE THREAD

**Issue by 3721518** [jumpserver/jumpserver#8334]
选择资产列表--创建节点后回车，列表就自动刷新并显示了所有节点。
建议是能否在创建节点后回车并定位到刚创建的节点上呢。如果不这样做，节点太多每次都显示所有找起来刚创建的节点好麻烦的要找好久。
jumper（版本号v2.21.2）

**Comment by ibuler** [comment]
收到，不如手动刷新呢，不用维护树的正确数量

**Comment by 3721518** [comment]
> 收到，不如手动刷新呢，不用维护树的正确数量

手动刷新是怎样刷新？是否可以设置成这样，创建了节点回车后即停留在刚创建的节点上即可，不需要自动刷新！

**Comment by ibuler** [comment]
修复了，添加后不刷新了
