### ISSUE TITLE
jumpserver中ubuntu 22.04不支持密钥登录

### ISSUE THREAD

**Issue by theonlyu** [jumpserver/jumpserver#8337]
jumpserver中ubuntu 22.04不支持密钥登录，必须使用密码登录。ubuntu其他版本都可以密钥登录。

测试，不用jumpserver用密钥是可以登录的，唯独添加到jumpserver不行。

连接测试时可以的通的
![屏幕截图 2022-06-03 103149](https://user-images.githubusercontent.com/75383020/171781264-762fb8d3-8455-48c8-ad77-5ac64490af51.png)

唯独在终端时，提示：error: 认证失败（用户名或密码错误），经过很多工具连接测试确定，用户名或密钥正确。

**Comment by wojiushixiaobai** [comment]
当前最新版本无法复现此问题，请自行排查下问题。
已验证 Ubuntu Desktop 22.04 LTS
```bash
# 生成密钥的命令
root@ubuntu:~# ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:AKqJ6oNFukLbe0FxDtkOscvm3QBN6fzfkOWNH/aPbRd root@ubuntu22.04
The key's randomart image is:
+---[RSA 3072]----+
|    .   .        |
|     + o         |
|    . @          |
| o.o B O .       |
|oo= o X S o .    |
|+.o. = * + +   E |
|o+  + o * . o   .|
|o. . o o o . .o..|
| .. .        .oo.|
+----[SHA256]-----+
```

**Comment by sdl9i2** [comment]
我这边遇到的问题一样，堡垒机是18.04，需要登录的机器是22.04
需要手动修改 22.04 的/etc/ssh/ssh_config 增加 PubkeyAcceptedKeyTypes +ssh-rsa 才可以正常登录
根据：https://askubuntu.com/questions/1404049/ssh-without-password-does-not-work-after-upgrading-from-18-04-to-22-04

The RSA SHA-1 hash algorithm is being quickly deprecated

不知我升级堡垒机是否可以解决，现在用的堡垒机版本应该还是1年前的

**Comment by wojiushixiaobai** [comment]
jumpserver 新版本已经不需要修改配置文件

**Comment by sdl9i2** [comment]
> jumpserver 新版本已经不需要修改配置文件

好的，我后面升级试一下
