### ISSUE TITLE
[Feature] Mac输入法切换问题

### ISSUE THREAD

**Issue by 55764418** [jumpserver/jumpserver#8338]
**请描述您的需求或者改进建议.**
使用Mac连接Web 终端后输入法切换是个大问题，Mac默认是大小写键切换的，造成Web终端内的Windows设备无法正常输入字符，还切换不好，使用体验不流畅。

**Comment by ibuler** [comment]
所有远程连接应该都会有这样的问题，因为输入会同时发本机和远端

**Comment by 55764418** [comment]
> 所有远程连接应该都会有这样的问题，因为输入会同时发本机和远端

那有什么好的解决方案，解决这个问题吗？特别是在Win系统内输入密码是个折磨人的事情！

**Comment by 55764418** [comment]
> 所有远程连接应该都会有这样的问题，因为输入会同时发本机和远端

那有什么好的解决方案，解决这个问题吗？特别是在Win系统内输入密码是个折磨人的事情！

**Comment by 55764418** [comment]
> 所有远程连接应该都会有这样的问题，因为输入会同时发本机和远端

那有什么好的解决方案，解决这个问题吗？特别是在Win系统内输入密码是个折磨人的事情！
