### ISSUE TITLE
请问是否支持ctrl+D退出

### ISSUE THREAD

**Issue by antimoth** [jumpserver/jumpserver#834]
请问支持ctrl+D退出吗？现在每次退出都要单独去输入一个q。

**Comment by liuzheng** [comment]
Mac是支持的，Windows是有点蛋疼了，因为Windows 的ctrl+d是浏览器默认的保存书签，存在按键冲突，你改掉浏览器的这个按键冲突即可

**Comment by antimoth** [comment]
登录到服务器后的ctrl+d是可以生效的，这个又是什么回事呢？

**Comment by liuzheng** [comment]
@antimoth 你是指ssh登录还是webterminal登录？

**Comment by antimoth** [comment]
ssh登录。win7中使用xshell连接jumpserver，并选择一个服务器登录进去，在那个服务器里ctrl+d是可以生效的。但是在jumpserver的操作界面(选择服务器的终端界面)，ctrl+d只会触发重新打印一串：
###    欢迎使用Jumpserver开源跳板机系统   ### 

        1) 输入 ID 直接登录 或 输入部分 IP,主机名,备注 进行搜索登录(如果唯一).
        2) 输入 / + IP, 主机名 or 备注 搜索. 如: /ip
        3) 输入 P/p 显示您有权限的主机.
        4) 输入 G/g 显示您有权限的主机组.
        5) 输入 G/g + 组ID 显示该组下主机. 如: g1
        6) 输入 E/e 批量执行命令.
        7) 输入 U/u 批量上传文件.
        8) 输入 D/d 批量下载文件.
        9) 输入 H/h 帮助.
        0) 输入 Q/q 退出.

Opt or ID>: 

这样的选择提示。必须要输入q才能退出。

**Comment by liuzheng** [comment]
这个控制台界面，这个下一版本会加入部分常规快捷键

**Comment by antimoth** [comment]
好的.
thks！

**Comment by lovejoy** [comment]
请问这个支持了吗
