### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#8343]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.22.1

**浏览器版本**
Microsoft Edge
版本 102.0.1245.33 (正式版本) (64 位)

**Bug 描述**

[Core]
[Celery]
终端 离线 但是不影响正常使用 
koko终端是正常的
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/70053869/172254482-58bde3b1-ce6a-4fd2-911d-2fd8eb5a6d61.png)

**Comment by ibuler** [comment]
应该是某个线程退出了，无法记录 健康信息了

**Comment by JeongHyeokLee** [comment]
![image](https://user-images.githubusercontent.com/70053869/174260980-e02cecdf-d01b-49cc-950e-bd96aa531605.png)
2.23.0同样有这个问题

**Comment by ibuler** [comment]
刚启动时状态正常吗

**Comment by JeongHyeokLee** [comment]
刚刚启动是正常的 过几分钟就显示断开 但是不影响使用

**Comment by JeongHyeokLee** [comment]
我不是通过docker部署的

**Comment by JeongHyeokLee** [comment]
![image](https://user-images.githubusercontent.com/70053869/175021185-90f44a18-969a-4495-86f9-6999762a7046.png)
2.23.1还是同样的问题

**Comment by wojiushixiaobai** [comment]
不影响使用的话先忽略，我们后续会优化此问题。
