### ISSUE TITLE
[Bug] RDP连接异常，互PING正常

### ISSUE THREAD

**Issue by misterocc** [jumpserver/jumpserver#8345]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome 101.0.4951.41

**Bug 描述**
Linux SSH链接没问题，唯独RDP连接出现了异常。WINDOWS 10已打开RDP权限

<img width="240" alt="image" src="https://user-images.githubusercontent.com/100667696/172294354-56d8fe8e-6279-4b63-b1a0-dea0adeaf1bb.png">

**Bug 重现步骤(有截图更好)**
1.  WEB终端选择Windows显示以下报错，从Jumpserver ping到此设置好的Windows是没问题的
<img width="331" alt="image" src="https://user-images.githubusercontent.com/100667696/172294453-08046435-e601-4ac0-8b98-1dcbe6b5149e.png">

2. 测试PING时显示成功
<img width="835" alt="image" src="https://user-images.githubusercontent.com/100667696/172294609-477d9b2c-a001-424d-b9c0-93fba04d363e.png">

**Comment by wojiushixiaobai** [comment]
[Windows RDP 资产要求](https://docs.jumpserver.org/zh/master/admin-guide/assets/windows_rdp/)
- [ ] 打开 Windows 远程设置
- [ ] 防火墙放行 rdp 端口
- [ ] 创建资产时 系统平台 选择 Windows
- [ ] 正常创建 RDP 系统用户
- [ ] 授权后即可
