### ISSUE TITLE
[Question] 通过 SSH ⼯具直连资产 如果目的服务器不是跑在22端口要怎么办？

### ISSUE THREAD

**Issue by qiulang** [jumpserver/jumpserver#8350]
看到  [2.11](https://docs.jumpserver.org/zh/master/about/change_log/#v2110) 这个功能
feat: ⽀持通过 SSH ⼯具直连资产。如：ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP

但是我们目的服务器不是跑在标准22端口，实际上我们的所有目的服务器都用一个IP地址，通过端口来区分转发，比如我的目的ip 60.205.207.101 ，我执行  `ssh qiulang@root@60.205.207.101@192.168.1.16 -p 2222` 

这样就会提示让我 ”选择其中一个资产登录“，但实际上我想直连 22227端口的机器，我用 `ssh qiulang@root@60.205.207.101:22227@192.168.1.16 -p 2222` 报错 未发现匹配的资产 60.205.207.101:22227

请问我这个需求能支持吗？

**Comment by wojiushixiaobai** [comment]
不需要知道端口，60.205.207.101 是你在 jumpserver 列表的主机名或者ip，具有唯一性的东西。

**Comment by qiulang** [comment]
但我的问题是 `ssh qiulang@root@60.205.207.101@192.168.1.16 -p 2222` 就需要再选择其中一个资产登录，而我是想能直接登录资产中某台目标服务器

**Comment by wojiushixiaobai** [comment]
如果你想登录的机器不在资产列表里面，那请将资产加入 jumpserver 后继续。如果资产无法直连，请使用网域网关功能

**Comment by qiulang** [comment]
你一直没明白我的问题
`ssh qiulang@root@60.205.207.101@192.168.1.16 -p 2222` 就会让我选择资产列表，选择后再登录。我的问题是有没有可能直接就登录到资产中的某一台机器，不要选择这一步。

**Comment by LeeEirc** [comment]
使用 `ssh qiulang@system_user_id@asset_id@192.168.1.16 -p 2222 ` 试试，你有多个资产的ip 都是 60.205.207.101，所以需要选择

**Comment by qiulang** [comment]
@LeeEirc   我现在就是这么用的! 所以你的答复就是确认了如果有多个资产的ip都是一样，就没法直连，对吧

**Comment by LeeEirc** [comment]
asset_id 是资产的 id 字段， 不是 ip字段。可以直接连接。

**Comment by ibuler** [comment]
> @LeeEirc 我现在就是这么用的! 所以你的答复就是确认了如果有多个资产的ip都是一样，就没法直连，对吧

你的理解是对的，只有 id 才能唯一，别的如果有多个的话，就需要手动选择了
