### ISSUE TITLE
[Question] 如何从目的服务器拷贝文件？

### ISSUE THREAD

**Issue by qiulang** [jumpserver/jumpserver#8351]
看到这个问题单 https://github.com/jumpserver/jumpserver/issues/130 说不支持 `ssh -J` 我试了 `scp -J` 确实也报错
所以我到底要怎么把目的服务器的文件拷贝到本地，或者从本地上传文件到目的服务器？实际开发中，这样的需求还是很多。

**Comment by wojiushixiaobai** [comment]
不支持 scp，请用 sftp 或 web 文件管理上传下载。
rzsz 也可以

**Comment by qiulang** [comment]
sftp 要怎么配置，有没有文档说明

**Comment by wojiushixiaobai** [comment]
默认就支持，不需要配置。
访问 jumpserver 2222 端口

**Comment by qiulang** [comment]
但是我是要从目的服务器拷贝文件

如果 `sftp -P  2222 jumpserver` 只是登录到  jumpserver

**Comment by LeeEirc** [comment]
sftp 可以通过一层层目录 cd 进去（目录是组织节点的树形结构）。目前仅 ssh 支持直连格式，sftp 尚未支持直连格式登陆到目标机器，待后续优化。

**Comment by qiulang** [comment]
@LeeEirc 我的问题就是要怎么**从目标机器拷贝文件**？ 因为我试了scp不行 @wojiushixiaobai 跟我说sftp 那看来也不行，那还有什么办法？

**Comment by LeeEirc** [comment]
可以用 sftp的工具 复制文件啊，你操作下就知道了。

**Comment by ibuler** [comment]
服务器相互 copy 目前不支持

**Comment by qiulang** [comment]
@LeeEirc  sftp 只能连到跳板机，但是我是要在目的机器和本机机器之间互传

**Comment by qiulang** [comment]
@ibuler 不是 服务器相互copy 是要把目的机器的文件下载到我本机机器

**Comment by xyzkk3** [comment]
> 

问题解决了吗

**Comment by xyzkk3** [comment]
服务器之间传输文件确实是很常见的需求，把文件拖到jumpserver那个web端太慢了，数据量少还好，数据量大，简直折磨。本来就一句scp命令解决的事情。不考虑支持下支持scp？

**Comment by wojiushixiaobai** [comment]
@xyzkk3 关闭问题表示问题已经解决，目前已经实现该功能，请在 v2.24 版本（下个版本）体验
