### ISSUE TITLE
[Feature] 资源主机的复制粘贴内容审计

### ISSUE THREAD

**Issue by zhituanchen** [jumpserver/jumpserver#8352]
**请描述您的需求或者改进建议.**
您好，有个情况，就是需要知道人员复制粘贴内容记录，看能否有复制粘贴的审计记录；
![image](https://user-images.githubusercontent.com/71009460/172807757-9290b102-f7ff-4818-80a4-b3d150b3f5ea.png)

**Comment by wojiushixiaobai** [comment]
无

**Comment by zhituanchen** [comment]
您好
      这个功能能否后续开发，因为存在其他用户拷贝敏感信息的可能，需要记录信息。

**Comment by zhituanchen** [comment]
您好
     Linux大概可从操作审计查看，当前主要是这个Windows的复制粘贴审计看能否有或者后续开发

**Comment by wojiushixiaobai** [comment]
暂时没太好的办法处理。

**Comment by ibuler** [comment]
有计划支持
