### ISSUE TITLE
提问网域网关

### ISSUE THREAD

**Issue by 870561859** [jumpserver/jumpserver#8355]
混合生成环境网域网是啥

**Comment by wojiushixiaobai** [comment]
比如公司有内网和外网，网关就是 DMZ 区域的资产，可以用这个 DMZ 的资产作为跳板同时连接内网和外网。
原理是通过 ssh 转发。

比如阿里云内网，你可以用一个有公网的机器作为网关，这样用户可以通过这个网关去连接内网没公网的资产


```
{ user }  ---> { 网关 } ---> { 内网资产 }
```

**Comment by 870561859** [comment]
> 比如公司有内网和外网，网关就是 DMZ 区域的资产，可以用这个 DMZ 的资产作为跳板同时连接内网和外网。 原理是通过 ssh 转发。
> 
> 比如阿里云内网，你可以用一个有公网的机器作为网关，这样用户可以通过这个网关去连接内网没公网的资产
> 
> ```
> { user }  ---> { 网关 } ---> { 内网资产 }
> ```

了解了  感谢
