### ISSUE TITLE
关于单独部署lion组件的问题

### ISSUE THREAD

**Issue by q99710lqq** [jumpserver/jumpserver#8356]
jumpserver-V2.22.2版本使用./jmsctl.sh install部署了,然后在另一台服务器重新使用docker再部署了lion组件，终端管理器上能注册成功新的lion组件,
![image](https://user-images.githubusercontent.com/107239001/173003612-6ac7dd2d-cffe-4aec-955f-15e2040a9d1e.png)
将老的组件删除后,在jumpserver中访问windows服务器，无法连接，报api错误，排查后发现jumpserver请求继续往老的地址上请求导致,
![image](https://user-images.githubusercontent.com/107239001/173003937-c5b5f5c6-e04c-43dd-b938-1b91c14d267f.png)
,这种情况下将如何解决

**Comment by wojiushixiaobai** [comment]
重启 docker 后重启 jumpserver

**Comment by q99710lqq** [comment]
> 重启 docker 后重启 jumpserver

这两个都有重启,restart,然后先stop,再start都试过.

**Comment by wojiushixiaobai** [comment]
nginx 配置地址改过来。
```bash
docker exec -it jms_web bash
```
```bash
cat /etc/nginx/conf.d/default.conf
```
```vim
    location /lion/ {
        proxy_pass http://lion:8081;    # <--  修正
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ignore_client_abort on;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;
        proxy_read_timeout 600;
        send_timeout 6000;
    }
```

**Comment by q99710lqq** [comment]
> nginx 配置地址改过来。
> 
> ```shell
> docker exec -it jms_web bash
> ```
> 
> ```shell
> cat /etc/nginx/conf.d/default.conf
> ```
> 
> ```viml
>     location /lion/ {
>         proxy_pass http://lion:8081;    # <--  修正
>         proxy_buffering off;
>         proxy_request_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
> ```

![image](https://user-images.githubusercontent.com/107239001/173268234-3f806681-e39e-4a60-8704-87cc2a2fcd33.png)
感谢大神,可以了,那我这样也可以做多台负载了.
