### ISSUE TITLE
系统用户配置为动态用户，开启自动推送后，推送所有用户到服务器上

### ISSUE THREAD

**Issue by xuzevin** [jumpserver/jumpserver#8358]
系统用户配置为动态用户，开启自动推送后，会在服务器上创建jumpserver里所有的用户，是否可以指定推送某个用户，或者在登录的时候验证用户是否存在，不存在在创建后登录，而不是推送所有用户到服务器上

**Comment by ibuler** [comment]
这个目前没有很好的办法，用户 - 资产 - 系统用户 的关联关系是通过授权完成的，系统用户会在资产上推送，关联的所有系统用户，所以是个笛卡尔集合

**Comment by Hamerle** [comment]
> 这个目前没有很好的办法，用户 - 资产 - 系统用户 的关联关系是通过授权完成的，系统用户会在资产上推送，关联的所有系统用户，所以是个笛卡尔集合

那不能以授权为枢纽么？，推送用户以授权中的jumpserver用户为准，授权哪个用户就推送哪个用户。现在一次性推送说有就挺不合理的，如果公司两三百人，每个机器都有几百个账号。。。

**Comment by heatdrive** [comment]
> > 这个目前没有很好的办法，用户 - 资产 - 系统用户 的关联关系是通过授权完成的，系统用户会在资产上推送，关联的所有系统用户，所以是个笛卡尔集合
> 
> 动态用户推送不能以授权为参照么？以授权中的jumpserver用户为准，授权哪个用户就推送哪个用户。现在一次性推送所有就挺不合理的，如果公司两三百人，每个机器都有几百个账号。。。

我自己的环境不授权就不会推这个动态用户的，是不是授权的时候加了一个大的用户组，不需要的账号都包括了.

**Comment by ibuler** [comment]
打算优化了，让用户自己处理推送

**Comment by seaurching** [comment]
我添加了一个系统用户后，点击推送。也显示成功了，主机上没有这个账号

**Comment by wojiushixiaobai** [comment]
等待优化
