### ISSUE TITLE
[Question] vscode 能通过remote container连接到资产上的容器吗

### ISSUE THREAD

**Issue by Kurt-Shiwz** [jumpserver/jumpserver#8363]
**请描述您的问题.**
我现在可以通过vscode 的remote ssh连接到资产，也能通过vscode的docker 插件看到正在运行的容器，也能通过`attach shell`在vscode的内置终端进到容器里。但是`attach vscode`却不行，一直卡死在`Start: Run in host: id -un`。
这个是怎么个情况，是说jumpserver还不支持remote container这种方式吗？还是需要再调整别的配置？

**Comment by LeeEirc** [comment]
仅对 remote-ssh 做优化，remote-container并不支持。

**Comment by Kurt-Shiwz** [comment]
> 仅对 remote-ssh 做优化，remote-container并不支持。

现在部分项目对于开发环境需要安装很多依赖和配置，使用docker包一个完善的环境用于开发也是挺常见的，非常期望后面有机会能支持这个功能~
