### ISSUE TITLE
Errno 1] _ssl.c：492：错误：140770FC：SSL例程：SSL23_GET_SERVER_HELLO：未知的协议

### ISSUE THREAD

**Issue by jiabin1994** [jumpserver/jumpserver#837]
请求方法： | POST
-- | --
http://192.168.30.219:8000/juser/user/edit/?id=4
1.6
SSLError
[Errno 1] _ssl.c：492：错误：140770FC：SSL例程：SSL23_GET_SERVER_HELLO：未知的协议
/usr/lib64/python2.6/ssl.py在do_handshake第279行
在/ usr / bin中/蟒蛇
2.6.6
[ '的/ usr /本地/ jumpserver主'，  '/usr/lib64/python26.zip'，  '/usr/lib64/python2.6'，  '/usr/lib64/python2.6/plat-linux2'，  '/usr/lib64/python2.6/lib-tk'，  '/usr/lib64/python2.6/lib-old'，  '/usr/lib64/python2.6/lib-dynload'，  '/usr/lib64/python2.6/site-packages'，  '/usr/lib64/python2.6/site-packages/gtk-2.0'，  '/usr/lib/python2.6/site-packages'，  '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info']
星期一，2017年12月4日星期一09:36:25 +0800

Environment:

Request Method: POST
Request URL: http://192.168.30.219:8000/juser/user/edit/?id=4

Django Version: 1.6
Python Version: 2.6.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'django_crontab',
 'bootstrapform',
 'jumpserver',
 'juser',
 'jasset',
 'jperm',
 'jlog')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py" in get_response
  114.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/jumpserver-master/jumpserver/api.py" in __deco
  281.             return func(request, *args, **kwargs)
File "/usr/local/jumpserver-master/juser/views.py" in user_edit
  399.             send_mail('您的信息已修改', msg, MAIL_FROM, [email], fail_silently=False)
File "/usr/lib/python2.6/site-packages/django/core/mail/__init__.py" in send_mail
  50.                         connection=connection).send()
File "/usr/lib/python2.6/site-packages/django/core/mail/message.py" in send
  255.         return self.get_connection(fail_silently).send_messages([self])
File "/usr/lib/python2.6/site-packages/django/core/mail/backends/smtp.py" in send_messages
  88.             new_conn_created = self.open()
File "/usr/lib/python2.6/site-packages/django_smtp_ssl.py" in open
  12.                                            local_hostname=DNS_NAME.get_fqdn())
File "/usr/lib64/python2.6/smtplib.py" in __init__
  761.             SMTP.__init__(self, host, port, local_hostname, timeout)
File "/usr/lib64/python2.6/smtplib.py" in __init__
  244.             (code, msg) = self.connect(host, port)
File "/usr/lib64/python2.6/smtplib.py" in connect
  300.         self.sock = self._get_socket(host, port, self.timeout)
File "/usr/lib64/python2.6/smtplib.py" in _get_socket
  767.             new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
File "/usr/lib64/python2.6/ssl.py" in wrap_socket
  342.                      suppress_ragged_eofs=suppress_ragged_eofs)
File "/usr/lib64/python2.6/ssl.py" in __init__
  120.                 self.do_handshake()
File "/usr/lib64/python2.6/ssl.py" in do_handshake
  279.         self._sslobj.do_handshake()

Exception Type: SSLError at /juser/user/edit/
Exception Value: [Errno 1] _ssl.c:492: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

修改用户点击启动和发送短信的同事报这个错误

**Comment by ibuler** [comment]
调试一下配置文件中smtp ssl tls的配置
