### ISSUE TITLE
组件xrdp 和 omnidb 报如下问题

### ISSUE THREAD

**Issue by liuwenzhi0318** [jumpserver/jumpserver#8382]
**JumpServer 版本 2.13.2**

**Bug 描述**
两个组件容器反复重启。
其中xrdp的日志如下
xrdp_1    | 
xrdp_1    | Mon Jun 13 18:34:03 CST 2022
xrdp_1    | XRDP Version v2.13.2, more see https://www.jumpserver.org
xrdp_1    | Quit the server with CONTROL-C.
xrdp_1    | 
xrdp_1    | Start forward-server ...
xrdp_1    | Start forward-server ok
xrdp_1    | logging configuration:
xrdp_1    |     LogFile:       /opt/xrdp/data/logs/xrdp.log
xrdp_1    |     LogLevel:      1
xrdp_1    |     EnableSyslog:  1
xrdp_1    |     SyslogLevel:   4
xrdp_1    | [20220613-18:34:03] [ERROR] verify_partner.jms_http_get failed http_code 401, body {"detail":"Invalid signature.","code":"authentication_failed"}
xrdp_1    | 
xrdp_1    | [20220613-18:34:03] [ERROR] refresh_terminal_config.jms_http_get failed http_code 401, body {"detail":"Invalid signature.","code":"authentication_failed"}
xrdp_1    | 
xrdp_1    | [20220613-18:34:03] [ERROR] xrdp_partner:init_partner failed[-1]
xrdp_1    | 

omnidb 容器报这样的
omnidb_1  | Starting OmniDB websocket...
omnidb_1  | Checking port availability...
omnidb_1  | Starting websocket server at port 8071.
omnidb_1  | Starting OmniDB server...
omnidb_1  | Checking port availability...
omnidb_1  | Starting server OmniDB 2.17.0 at 0.0.0.0:8082/omnidb.
omnidb_1  | User database version 2.17.0 is already matching server version.
omnidb_1  | [06/13/2022 18:34:35] ERROR [JumpServer_app.service.client:238] 校验终端有效性不符合预期, 响应状态码: (401), text: ({"detail":"Invalid signature.","code":"authentication_failed"})
omnidb_1  | [06/13/2022 18:34:35] ERROR [JumpServer_app.startup:19] 终端无效, 尝试删除AccessKey文件并重新启动服务 (文件路径: /opt/omnidb/data/key/omnidb.key)

**Comment by liuwenzhi0318** [comment]
问题得到解决了
只需要删掉原来的key就行了， docker 的位置一般在/opt/jumpserver/xrdp目录 和omnidb目录下找key目录。删掉就行。

**Comment by ibuler** [comment]
好的
