### ISSUE TITLE
[Feature] SSO认证建议在登录页面提供按钮跳转到第三方认证中心的指定URL

### ISSUE THREAD

**Issue by kihoor** [jumpserver/jumpserver#8384]
SSO单点认证   建议在登录页面提供一个按钮  跳转到第三方认证中心的指定URL，用户无需知道或者输入认证中心的地址。
众多单点登录也都是这么做的，用户只需要知道自己要操作的业务系统，而非认证中心

**Comment by ibuler** [comment]
能截个图吗，或者举个产品的例子，看一下
