### ISSUE TITLE
[Bug] Jumpserver Terminal Replay Storage Minio

### ISSUE THREAD

**Issue by artemus717** [jumpserver/jumpserver#8385]
**JumpServer 版本(v1.5.9以下不再支持)**
2.22.0 / 2.22.2

**Bug 描述**
Unable to store terminal replay storage to minio via s3 protacol.
Do test on console response account invaild

**Bug 重现步骤(有截图更好)**
![9d39c7bd1d915cb11b4fb47d91d8308](https://user-images.githubusercontent.com/16465173/173512770-ec887edc-0901-4b99-b3c2-1adf97a8fe38.png)

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/173543598-2e5a3262-6d66-42ec-9312-078108589cab.png)

**Comment by artemus717** [comment]
![image](https://user-images.githubusercontent.com/16465173/173972166-3dd3b30c-186d-420d-86e0-ca7bf7fe5131.png)
Did your ceph use S3 protocol?

**Comment by wojiushixiaobai** [comment]
s3 --> Amazon Simple Storage Service (Amazon S3)
```
S3 format: http://s3.{REGION_NAME}.amazonaws.com
S3(China) format: http://s3.{REGION_NAME}.amazonaws.com.cn
Such as: http://s3.cn-north-1.amazonaws.com.cn
```
Cannot be compatible with Minio
