### ISSUE TITLE
更新不出来内存 系统等信息。

### ISSUE THREAD

**Issue by jiabin1994** [jumpserver/jumpserver#839]
![l87aq6reyokjk78dxj3 f j](https://user-images.githubusercontent.com/33475984/33539443-62eaa080-d901-11e7-8acb-cc74885faf9d.png)

**Comment by ibuler** [comment]
定期的，去详情里面手动更新一下

**Comment by jiabin1994** [comment]
已解决了，谢谢

**Comment by qianghong000** [comment]
怎么解决的
