### ISSUE TITLE
web后台用户管理那儿做一个禁用按钮，实现点一下禁用WEB登陆，同时系统对应的用户被注释

### ISSUE THREAD

**Issue by guoshuaifeng** [jumpserver/jumpserver#84]
我把某个用户禁用了，他登陆jumpserver网页提示“用户未激活”，但能SSH登上

web后台用户管理那儿做一个禁用按钮，实现点一下禁用WEB登陆，同时系统对应的用户被注释

**Comment by ibuler** [comment]
#83 已修复，merge到dev，请等待合并

外观ui修改排期比较低
