### ISSUE TITLE
资产组其他信息更新，资产未动的情况下，提交成功后，原有资产被清空

### ISSUE THREAD

**Issue by getway** [jumpserver/jumpserver#840]
[简述你的问题]

##### 使用版本
[0.4.0]

##### 问题复现步骤
1. [步骤1]
当前资产组情况：有两个主机资产，选择更新按钮
![image](https://user-images.githubusercontent.com/5615804/33544351-6de9b098-d915-11e7-84fc-1bf712936324.png)

2. [步骤2]
进入更新资产组页面，不做任何修改，直接提交：
![image](https://user-images.githubusercontent.com/5615804/33544461-d08b876c-d915-11e7-9fa1-ee447d02f407.png)

3. [步骤3]
原有资产jing'ran竟然么有了：
![image](https://user-images.githubusercontent.com/5615804/33544504-fa94d608-d915-11e7-97fd-f8a39eb07464.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已修复
