### ISSUE TITLE
[Question] 连接 mysql 时，unshare 开启命名空间失败

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#8402]
**请描述您的问题.**
version: 2.20.1
![image](https://user-images.githubusercontent.com/39855929/173734182-9cce681d-eca3-42ba-9101-3ac971ec071c.png)

**Comment by wojiushixiaobai** [comment]
koko 容器需要使用特权创建

**Comment by lf-zhang** [comment]
请教下，通过 nobody 用户和通过 unshare 命令创建 mysql 命令行有什么区别吗？nobody 用户是否可以支持正常使用 mysql 登录功能呢？

**Comment by wojiushixiaobai** [comment]
namespace 必须要特权创建吧
