### ISSUE TITLE
[Bug] 文件管理拖动文件夹，点击取消，不能真正取消传输

### ISSUE THREAD

**Issue by JonnnLOL** [jumpserver/jumpserver#8412]
**JumpServer 版本(v1.5.9以下不再支持)**
2.22.2

**浏览器版本**
Microsoft Edge
版本 102.0.1245.39 (正式版本) (64 位)

**Bug 描述**
文件管理拖动文件夹从一个资产到另一个资产，点击取消，并不能真正取消传输，服务仍在传输，关闭文件管理页面才可真正中断

**Bug 重现步骤(有截图更好)**
1. 拖动 126 资产的 data 文件夹到 222 资产下 
![image](https://user-images.githubusercontent.com/95204418/173821185-85a23012-946a-4131-99ae-7679e70a0cea.png)

2. 点击取消，后台仍在传输，若不关闭页面，文件将会移动完成
![image](https://user-images.githubusercontent.com/95204418/173821366-5d570a5a-815e-4543-a32b-5e74513993df.png)

**Comment by ibuler** [comment]
@LeeEirc
