### ISSUE TITLE
[BUG]系统用户推送失败

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#843]
[简述你的问题]
系统用户推送，页面上显示成功，但是远程主机上并没有创建系统用户。

##### 使用版本
服务器：nginx+gunicorn
Jumpserver: 0.4

##### 具体表现

![image](https://user-images.githubusercontent.com/8511007/33597086-39bd4810-d9d9-11e7-89c6-0ca467d41e77.png)

经调查发现，推送没有成功但显示成功是因为下面这行:
文件名：ops/utils.py:72
```
        if len(summary['failed']) == 0:
```
应改为：
```
        if len(summary['failed']) == 0 and len(summary['success']) > 0:
```
但是还没解决为什么没有推送成功的问题。

**Comment by b2scrip** [comment]
一样的问题，
我在开发环境下测试 没有任何问题，但是用NGINX+UWSGI下面部署系统用户无法推送。
还有其他人遇到一样问题吗

**Comment by b2scrip** [comment]
艰难的问题排查，终于找到了答案。。。
简而言之，你在线上部署时候需要考虑环境变量

`   os.chdir(apps_dir)
    os.environ.setdefault('C_FORCE_ROOT', '1')
    os.environ.setdefault('PYTHONOPTIMIZE', '1')
`
记得在你CELERY deamon进程里面，引入

**Comment by gengkeye** [comment]
@b2scrip 非常感谢，正解！

**Comment by wangyunlongg** [comment]
@gengkeye @b2scrip 考虑环境变量是什么意思啊，最终怎么解决的啊？
“简而言之，你在线上部署时候需要考虑环境变量
   os.chdir(apps_dir)
    os.environ.setdefault('C_FORCE_ROOT', '1')
    os.environ.setdefault('PYTHONOPTIMIZE', '1')”

**Comment by ibuler** [comment]
感谢，新版本已使用
