### ISSUE TITLE
使用文件管理上传下载文件后，再次连接资源无反应[Bug] 

### ISSUE THREAD

**Issue by vyunwei** [jumpserver/jumpserver#8431]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.20.0 GPLv2
Version v2.23.0 GPLv2

**浏览器版本**

Chrom 版本 102.0.5005.115
**Bug 描述**

使用FTP上传下载文件后，再次连接资源无反应
**Bug 重现步骤(有截图更好)**
1.  打开资源控制台，打开资源文件管理进行文件下载
2. 关闭文件管理，关闭资源ssh
3. 再次打开资源ssh无反应

**Comment by vyunwei** [comment]
![image](https://user-images.githubusercontent.com/18206104/174256136-efcf0417-361f-4cba-97dc-399f4b1d6ac4.png)

**Comment by vyunwei** [comment]
可以连接其他资源ssh，之前用过文件管理的资源不行，
Version v2.20.0 GPLv2
Version v2.23.0 GPLv2
以上两个版本都存在这个问题。

**Comment by LeeEirc** [comment]
不知道你的ssh 资源，具体指的那种机器。
在 config.txt 增加个参数，去掉 ssh 的连接服用，试试
```
 REUSE_CONNECTION=False            # 是否复用同一用户的 SSH 连接
```
https://docs.jumpserver.org/zh/master/admin-guide/env/

**Comment by vyunwei** [comment]
> 不知道你的ssh 资源，具体指的那种机器。 在 config.txt 增加个参数，去掉 ssh 的连接服用，试试
> 
> ```
>  REUSE_CONNECTION=False            # 是否复用同一用户的 SSH 连接
> ```
> 
> https://docs.jumpserver.org/zh/master/admin-guide/env/

ssh连接的centos主机

**Comment by vyunwei** [comment]
> > 不知道你的ssh 资源，具体指的那种机器。 在 config.txt 增加个参数，去掉 ssh 的连接服用，试试
> > ```
> >  REUSE_CONNECTION=False            # 是否复用同一用户的 SSH 连接
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://docs.jumpserver.org/zh/master/admin-guide/env/
> 
> ssh连接的centos主机

我等个20分钟到半个小时左右就可以连接了，我感觉是关闭浏览器以后ssh通道还被占用着，等过了超时时间才可以连。

**Comment by LeeEirc** [comment]
> 

先修改完配置，重启服务试试吧。

**Comment by vyunwei** [comment]
> > 
> 
> 先修改完配置，重启服务试试吧。

修改完重启验证了一下，没有出现之前的问题，我再观察一段时间，有问题再反馈。
谢谢~
