### ISSUE TITLE
使用kubernetes应用，kubectl -n 命名空间不会自动补全

### ISSUE THREAD

**Issue by MrLichangming** [jumpserver/jumpserver#8432]
**请描述您的问题.**
jumpserver version: v2.22.2

在登录上kubernetes应用终端后，使用kubectl  -n 指定命名空间时，失去了自动补全功能，想咨询下为何这样？

**Comment by MrLichangming** [comment]
有没有运维同学 也遇到了一样的问题，请追加

**Comment by LeeEirc** [comment]
https://kubernetes.io/zh-cn/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/
如果没记错的话，只是自动补全 kubectl 的参数，并不会补全 k8s 拥有的资源

**Comment by ibuler** [comment]
https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/

**Comment by ibuler** [comment]
@MrLichangming 要不你手动配置一下，反馈过来，我们更改一下

**Comment by MrLichangming** [comment]
@ibuler  @LeeEirc  感谢回答， 提问题前我验证过了这个，在centos7.9的主机上，是可以没问题，在我们jumpserver上，我通过详细的图形解释描述下遇到的问题

jumpserver:
1. 登录k8s资产后的界面
![image](https://user-images.githubusercontent.com/29295178/174725945-262accf6-c144-4e51-90c4-656c5e5f8dd3.png)
![image](https://user-images.githubusercontent.com/29295178/174726038-6e873375-879f-4549-9989-7e13aee32cc3.png)

2. 问题点
![image](https://user-images.githubusercontent.com/29295178/174726305-cfbdc645-0a91-4d74-b08c-37d0bf3cb67f.png)
以上是正常的，当我 输入 -n 指定命名空间时， tab键就失效了
![image](https://user-images.githubusercontent.com/29295178/174726562-752c7179-4257-4dac-8e8c-70ba59fd4dd9.png)

正常的centos7.9主机，尝试2步骤，可明显观察到于jumpserver资产使用的不同点
![image](https://user-images.githubusercontent.com/29295178/174726924-61fe9f69-b7f1-4133-9323-f4267d662d6b.png)

这个问题  不太清楚是否是kubectl bash_completion对jumpserver 底层系统不兼容的问题导致的，需要寻求帮助下

**Comment by MrLichangming** [comment]
我记得之前版本是正常的，我不确认 我这次使用最新的版本 2.22.2 是否遇到了bug

**Comment by LeeEirc** [comment]
> 我记得之前版本是正常的，我不确认 我这次使用最新的版本 2.22.2 是否遇到了bug

并没有做太多改动，你尝试手动配置看看吧。

**Comment by MrLichangming** [comment]
我很明确的 这个连接的东西
https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/

在进入到kubectl的界面时，已经完全安装了，就这样吧   来来回回 太费劲

**Comment by liyangFileRepository** [comment]
我在 2.4.0 版本也遇到这个问题

**Comment by MrLichangming** [comment]
看下官方是否修复此问题吧

**Comment by liyangFileRepository** [comment]
这个问题，为了满足开发的需求，曲线救国，在koko中安装kubens命令，使用该命令来切换命名空间。


安装该命令后，运行会报错，报错的原因受限于这个web终端，下面是解决方式：
54： ns="$($KUBECTL config view ***@***.***==\"${cur_ctx}\")].context.namespace}")" \
69： $KUBECTL get namespaces -o=jsonpath='{range .items[*].metadata.name}{@}{"\n"}{end}'


更改为
54： ns="$($KUBECTL config view | grep -v NAME | awk '{print $1}')"
69： $KUBECTL get namespaces | grep -v NAME | awk '{print $1}'




| |
李杨
|
|
***@***.***
|



在 2022-09-27 21:49:51，"MrLichangming" ***@***.***> 写道：

看下官方是否修复此问题吧

**Comment by nangongchengfeng** [comment]
> 有没有运维同学 也遇到了一样的问题，请追加

目前我遇到这个问题。
版本：jumpserver-offline-installer-v3.6.2-amd64
![image](https://github.com/jumpserver/jumpserver/assets/46562911/111543ea-4eb3-481c-a200-cc250a2cc450)
