### ISSUE TITLE
[Bug] 这是个半成品？貌似就录像正常

### ISSUE THREAD

**Issue by zhangbest5** [jumpserver/jumpserver#8433]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-installer-v2.22.3

**浏览器版本**
 Chrome 版本 102.0.5005.63（正式版本） （64 位）

**Bug 描述**
linux centOS 7 服务器
1、duf 中有乱码
2、命令不记录
3、文件管理无法正常使用，这目录怎么对应的，根本对不上啊？建立文件夹传输文件都哪去了？
4、客户端无法连接非22端口？

**Bug 重现步骤(有截图更好)**
1.  duf 中有乱码
![image](https://user-images.githubusercontent.com/55474238/174422319-16ff7a7f-47ca-4da3-97b4-fd682e6d92eb.png)

2. 命令不记录：duf命令记录为 | ，ls命令不记录
[download_2022-06-18_11-40-28.csv](https://github.com/jumpserver/jumpserver/files/8932904/download_2022-06-18_11-40-28.csv)

3. 文件管理无法正常使用，这目录怎么对应的，根本对不上啊？建立文件夹传输文件都哪去了？
![image](https://user-images.githubusercontent.com/55474238/174422257-936a556e-be52-47bc-9ffd-de89382bfce9.png)

4.windows客户端下载后连不了，显示超时，这是非22端口压根就连不了吧？
jumpserver-client-windows-x86_64.msi

**Comment by ibuler** [comment]
不懂尊重，拒绝回答

**Comment by zhangbest5** [comment]
真是好理由
如果我不尊重您，
为何123的费工夫列这么多问题？
如果我为了不尊重这么好的一个开源项目？？
那我直接列个标题不就得了，写什么内容？
还是
解决不了问题，就解决掉提出问题的人

也许不是，那我就再重新反馈下问题，充分尊重
