### ISSUE TITLE
[Bug] 社区版 Version v2.23.0 网页版terminal 选中文本不能自动复制了

### ISSUE THREAD

**Issue by abelyang** [jumpserver/jumpserver#8434]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.23.0 GPLv2.

**浏览器版本**
谷歌浏览器

**Bug 描述**
网页版terminal 选中文本不能自动复制了

**Bug 重现步骤(有截图更好)**
1.  

2. 
3.

**Comment by LeeEirc** [comment]
已修复https://github.com/jumpserver/koko/pull/906 ，等小版本发布。
