### ISSUE TITLE
[Question] helm安装后无法访问

### ISSUE THREAD

**Issue by hero-lzh** [jumpserver/jumpserver#8435]
**请描述您的问题.**
使用helm升级2.14.x版本到2.23.0无法访问，使用helm重新安装后也无法访问，提示404。也没错误日志。

**Comment by wojiushixiaobai** [comment]
404 是 ingress 返回的还是 jms_web pod 返回的。
ingress 返回的需要重新载入 ingress，或者 jms_web pod
如果是 jms_web pod 返回的，重新 recreate jms_web pod 或者查看其日志

**Comment by wojiushixiaobai** [comment]
你的反向代理可能有问题

**Comment by hero-lzh** [comment]
core日志提示这个，请问是什么问题呢

**Comment by wojiushixiaobai** [comment]
需要更完整的错误日志

**Comment by wojiushixiaobai** [comment]
请去掉 LB 后验证

**Comment by hero-lzh** [comment]
已处理，ingress的转发有问题，感谢解答
