### ISSUE TITLE
[Bug]  v2.20.3 升级到 v2.22.0 v.2.22.2 v2.22.3 通过UI页面登录失败

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#8441]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
chrome 版本 102.0.5005.115（正式版本） （64 位）

**Bug 描述**
v2.20.3 升级到 v2.22.0 v.2.22.2 v2.22.3  通过UI 页面登录失败，会提示  * 该字段是必填项。 明明是填了密码。正常情况下输入错误的密码会提示，密码错误。  升级到 v2.21.4 版本没问题。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3. 
![image](https://user-images.githubusercontent.com/24754263/174534215-c96e60f9-ff75-41cc-ac08-2603db19d711.png)

**Comment by wojiushixiaobai** [comment]
清理下浏览器缓存

**Comment by theonlyu** [comment]
我也遇到同样的问题，v2.19.3升级到v2.23.0.

不是浏览器缓存问题，换台电脑同样的提示。
![屏幕截图 2022-06-21 090726](https://user-images.githubusercontent.com/75383020/174701852-4269c4ff-bf42-4498-8ba5-7d773191f0a0.png)

只有第三方ssh工具可以登录，但是页面版，死活登录不了，希望速度解决这个bug

**Comment by ibuler** [comment]
群里联系一下 @wojiushixiaobai 我们具体看看这个问题，按道理来说不应该出现才对

**Comment by Ro0tk1t** [comment]
jmctl 重启下就行

**Comment by theonlyu** [comment]
> jmctl 重启下就行

不行，重启在多遍也没用，服务器重启都没用。跟重启没啥关系

**Comment by theonlyu** [comment]
最新反馈，我试着直接安装最新版本v2.23.0，然后将v2.19的数据库导过去。

最后测试，发现可以用直接用IP登录账号密码。但是不能用域名登录，用域名登录只提示*该字段为必填项。

**Comment by zhegeshijiehuiyouai** [comment]
我也遇到了，v2.21.4升级到v2.22.4
