### ISSUE TITLE
web端 rz 上传文件乱码报错

### ISSUE THREAD

**Issue by yanyanyong** [jumpserver/jumpserver#8445]
**请描述您的问题.**
web端 下载lrzsz 用rz上传jar包会出乱码并报错卡死，是编码问题还是什么原因，传其他文本没有问题，有遇见过吗？

**Comment by yanyanyong** [comment]
![企业微信截图_16557028161207](https://user-images.githubusercontent.com/76428790/174542599-e8a89380-205c-466e-8270-d06aebf84507.png)

**Comment by ibuler** [comment]
这个问题比较难说，因为 rzsz 有时在 xshell 上也不稳，最好压缩一下在 rzsz

**Comment by yanyanyong** [comment]
> 这个问题比较难说，因为 rzsz 有时在 xshell 上也不稳，最好压缩一下在 rzsz

压缩过还是会乱码，gzip和tar.gz都试过，单上传一个程序exe文件都会乱码报错，联系技术咨询说是大文件用rz会有乱码是已知bug（文件只有几十M），是不太方便，只出现用web连接资产的情况下，其他终端试过用没问题。如果真的是bug还请以后可以多重视这个问题，谢谢

**Comment by LeeEirc** [comment]
> > 这个问题比较难说，因为 rzsz 有时在 xshell 上也不稳，最好压缩一下在 rzsz
> 
> 压缩过还是会乱码，gzip和tar.gz都试过，单上传一个程序exe文件都会乱码报错，联系技术咨询说是大文件用rz会有乱码是已知bug（文件只有几十M），是不太方便，只出现用web连接资产的情况下，其他终端试过用没问题。如果真的是bug还请以后可以多重视这个问题，谢谢

如果只有 web 使用 rz 会出现此问题，可能还需要调研 js 的库。

**Comment by iseki0** [comment]
这不是个提问，这应该是个 Bug @wojiushixiaobai 关掉是已修复了吗
