### ISSUE TITLE
[Bug] 【充分尊重】反馈部分乱码，命令不记录，文件管理无法正常使用，客户端无法连接非22端口

### ISSUE THREAD

**Issue by zhangbest5** [jumpserver/jumpserver#8446]
**充分尊重**
首先先表达充分尊重，我对作者大神的敬仰犹如滔滔江水连绵不绝
再者，我也是个Dota2的游戏爱好者，
这么好的项目怎么能不尊重？
（上次直接关闭我问题，说我不尊重，冤啊！）

**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-installer-v2.22.3

**浏览器版本**
Chrome 版本 102.0.5005.63（正式版本） （64 位）

**Bug 描述**
linux centOS 7 服务器
1、duf 中有乱码
2、命令不记录
3、文件管理感觉无法正常使用，这目录是怎么对应的？建立文件夹传输文件都哪去了？建议完善官方文档
4、客户端无法连接非22端口？

**Bug 重现步骤(有截图更好)**
1.duf 中有乱码
![image](https://user-images.githubusercontent.com/55474238/174541108-42eac7df-cdff-489e-9395-715a82e1d12d.png)

2.命令不记录：duf命令记录为 | ，ls命令不记录
[download_2022-06-18_11-40-28.csv](https://github.com/jumpserver/jumpserver/files/8932904/download_2022-06-18_11-40-28.csv)

3.文件管理是连接上了，但从我小白的角度感觉无法正常使用，这目录打开的目录是哪里？
建立文件夹、传输文件都去了哪里？我看了官方文档，也是这样，没有解决我的疑惑
建议文档能更细致些，增加后续说明，能解答下建立文件夹、传输文件都去了哪里？
![image](https://user-images.githubusercontent.com/55474238/174541169-7e910c7f-9cef-4b08-a39e-9a03bd8e2e89.png)

4.windows客户端下载后连不了，显示超时，请问：这是非22端口现在不支持吗？

**最后**
再次表达尊重，非常尊重作者大神 写得了代码，玩得了dota2，又会python，又会golang
我也是个搞运维的，也学了golang，也玩dota2（虽然您选的那几个英雄我不爱玩，因为不6）

**Comment by ibuler** [comment]
端口需要在后台设置好， 系统设置 / 终端设置 / 服务端点
