### ISSUE TITLE
[Question] 创建系统用户时，选择密钥文件时，有些pem显示可用，有些是灰色不可能，有什么限制？

### ISSUE THREAD

**Issue by hanjun806** [jumpserver/jumpserver#8458]
创建系统用户时，选择密钥文件时，有些pem显示可用，有些是灰色不可能，有什么限制？

![20220622101136](https://user-images.githubusercontent.com/14847373/174928937-5205f4ac-f5c5-4e09-9a11-010c54e3ac22.jpg)
![20220622101305](https://user-images.githubusercontent.com/14847373/174928944-7616be37-1871-4733-a7de-bee49b19b08e.jpg)

**Comment by wojiushixiaobai** [comment]
检查下格式看看，或者检查文件的权限
