### ISSUE TITLE
网域网关，多层网关下该如何实现呢？

### ISSUE THREAD

**Issue by HandSomeRoger** [jumpserver/jumpserver#8459]
现在的网域网关，实现“JMS => 网域网关 => 目标资产”访问是没问题的。
但是实际需求中会有“JMS => 网域网关 => 另一个网域网关 => 目标资产”的需求。这种应该怎么做呢。现有版本是 v2.20.2

**Comment by wojiushixiaobai** [comment]
如果有这样的情况建议先组网。
暂时不支持这种场景，可靠性无法保证
