### ISSUE TITLE
docker-compose安装config的问题

### ISSUE THREAD

**Issue by x82423990** [jumpserver/jumpserver#846]
[简述你的问题]
使用docker-compose安装成功后， 怎么修改mail的配置文件啊， 如果不配置邮件， 新建用户的key和passwd 保存在什么地方的啊？
##### 使用版本
 0.4.0

**Comment by wojiushixiaobai** [comment]
貌似需要修改容器并重新初始化，这里涉及到docker的操作，题主百度 docker容器修改。

**Comment by x82423990** [comment]
mail的配置文件在邮件账户配置的里面，用户表为CmsUser.
