### ISSUE TITLE
[Feature] 在线更新功能？

### ISSUE THREAD

**Issue by 55764418** [jumpserver/jumpserver#8463]
**请描述您的需求或者改进建议.**
是否考虑在线自动更新的功能，否则每次更新都太麻烦了，一不小心就落后好多个版本！

**Comment by wojiushixiaobai** [comment]
容器化的代码自动更新不太好处理，当前的 installer 更新已经很方便了

**Comment by jym503558564** [comment]
我们每个月都会迭代一个大版本，多个小版本，可持续关注我们版本发布情况。
