### ISSUE TITLE
[Bug] 终端登录时看到已经手工从资产中删除关联的系统用户

### ISSUE THREAD

**Issue by jozzlee** [jumpserver/jumpserver#8464]
**JumpServer 版本(v1.5.9以下不再支持)**
2.23.1

**浏览器版本**
Chrome 102.0.5005.115

**Bug 描述**
使用Web终端登录时，看到已经手工从资产中删除关联的系统用户（该系统用户被授权给用户的其他资产）。
1. 希望添加系统用户后不要自动关联到所有资产、以免除步骤6和7；
2. 希望只能看到与资产明确关联的系统用户，而不是用户所拥有的所有系统用户。

**Bug 重现步骤(有截图更好)**
1. 添加资产：资产1、资产2；
2. 添加系统用户：系统用户A、系统用户B；
3. 添加用户：张三、李四；
4. 新建授权”给用户张三的授权“:资产1+资产2+系统用户A+系统用户B；
5. 新建授权”给用户李四的授权“:资产1+系统用户A；
6. 查看资产1，可看到系统用户A和B，从中移除不需要的系统用户B；
7. 查看资产2，可看到系统用户A和B，从中移除不需要的系统用户A；
8. 使用用户张三登录web终端，选择资产1，仍然出现系统用户选择用户A和用户B。

**Comment by jozzlee** [comment]
这似乎是一个存在很久的Bug，可以搜索到的有这些：[关联 系统用户](https://github.com/jumpserver/jumpserver/issues?q=is%3Aissue+%E5%85%B3%E8%81%94+%E7%B3%BB%E7%BB%9F%E7%94%A8%E6%88%B7+)

**Comment by jozzlee** [comment]
在系统用户A的详情-资产列表中不存在资产2，在资产2的详情-系统用户中也不存在系统用户A，因为张三的授权里有涉及资产2和系统用户A就在资产2的登陆界面展示系统用户A？

**Comment by wojiushixiaobai** [comment]
授权错误导致

**Comment by jozzlee** [comment]
> 授权错误导致

你好，可否详细指出是步骤1-4哪里错误了？

**Comment by wojiushixiaobai** [comment]
步骤 1-4 均为错误的操作。
请从授权管理里面移除错误的授权规则

**Comment by jozzlee** [comment]
> 步骤 1-4 均为错误的操作。 请从授权管理里面移除错误的授权规则

我还是无法理解这其中的逻辑，应该如何改正？我重新组织了下语言，烦请再看看
1. 添加资产：资产1、资产2；
2. 添加系统用户：系统用户A、系统用户B；
3. 添加用户：张三、李四；
4. 新建授权”给用户张三的授权“:资产1+资产2+系统用户A+系统用户B；
5. 新建授权”给用户李四的授权“:资产1+系统用户A；
6. 查看资产1，可看到系统用户A和B，从中移除不需要的系统用户B；
7. 查看资产2，可看到系统用户A和B，从中移除不需要的系统用户A；
8. 使用用户张三登录web终端，选择资产1，仍然出现系统用户选择用户A和用户B。

**Comment by wojiushixiaobai** [comment]
请创建两个授权
新建授权”给用户张三的授权“:资产2+系统用户B；
新建授权”给用户李四的授权“:资产1+系统用户A；

**Comment by jozzlee** [comment]
您的回答将导致张三无法访问资产1+系统用户A，这不是我遇到的问题的解决方案。

**Comment by jozzlee** [comment]
> 请创建两个授权 新建授权”给用户张三的授权“:资产2+系统用户B； 新建授权”给用户李四的授权“:资产1+系统用户A；
> 
> ```
> | 表单     | 资产1授权                | 资产2授权            |
> | -------- | ----------------------- | ------------------- |
> | 名称     | 资产1测试授权            | 资产2测试授权         |
> | 用户     | 张三(zhangsan)          | 李四(lisi)            |
> | 用户组   |                          |                     |
> | 资产     | 资产1(172.16.80.11)     |  资产2(172.16.80.21) |
> | 节点     |                         |                      |
> | 系统用户 | 系统用户A(test01)        | 系统用户B(test02)     |
> | 权限     | √ 全部                  | √ 全部                |
> ```

您的回答将导致张三无法访问资产1+系统用户A，这不是我遇到的问题的解决方案。

**Comment by wojiushixiaobai** [comment]
@jozzlee 张三无法访问资产1+系统用户A
这句话已经对授权理解错误

授权是 `用户和用户组` 使用授权的 `系统用户` 连接到 `资产或者节点` 下的所有资产。

**Comment by jozzlee** [comment]
> @jozzlee 张三无法访问资产1+系统用户A 这句话已经对授权理解错误
> 
> 授权是 `用户和用户组` 使用授权的 `系统用户` 连接到 `资产或者节点` 下的所有资产。
> 
> 你要授权 某人 使用 某账号 访问 某个资产
> 
> 正确理解这句话，然后看懂这个授权
> 
> ```
> | 表单     | 资产1授权                | 资产2授权            |
> | -------- | ----------------------- | ------------------- |
> | 名称     | 资产1测试授权            | 资产2测试授权         |
> | 用户     | 张三(zhangsan)          | 李四(lisi)            |
> | 用户组   |                          |                     |
> | 资产     | 资产1(172.16.80.11)     |  资产2(172.16.80.21) |
> | 节点     |                         |                      |
> | 系统用户 | 系统用户A(test01)        | 系统用户B(test02)     |
> | 权限     | √ 全部                  | √ 全部                |
> ```
> 
> 授权 `张三(zhangsan)` 使用 `系统用户A(test01)` 连接 `资产1(172.16.80.11)` 授权 `李四(lisi)` 使用 `系统用户B(test02 )` 连接 `资产2(172.16.80.21)`
> 
> 你也可以 授权 `张三(zhangsan)` 和 `李四(lisi)` 使用 `系统用户A(test01)` 连接 `资产1(172.16.80.11)` 授权 `张三(zhangsan)` 和 `李四(lisi)` 使用 `系统用户B(test02 )` 连接 `资产2(172.16.80.21)`
> 
> 不管你怎么授权，连接资产的 `系统用户都保证唯一`
> 
> 如果还是无法理解，请按照上文操作。 如果仍旧无法理解，那么我们无更多建议，抱歉。

我想你的意思是我必须新建第三条授权:张三的授权二，授权张三访问资产1+系统用户A。

**Comment by jozzlee** [comment]
> 问题解决了吗？这个的确貌似是一直存在的，期待官方处理。

官方答复这不是个问题，按我的理解就是“资产授权”是以“资产”为本而非以人为本，所以不存在一条授权为某用户授权所需资产的功能，而是应该分门别类地为不同资产创建授权、关联系统用户和用户。
