### ISSUE TITLE
[Bug] navicat通过jumpserver连接MySQL-5时，提示 1146-Table'mysql.role_edges' doesn't exist

### ISSUE THREAD

**Issue by changeflyhigh** [jumpserver/jumpserver#8467]
**JumpServer 版本(v1.5.9以下不再支持)**

**navicat 版本**
navicat 15.0.12

**Bug 描述**
navicat通过jumpserver连接MySQL-5时，提示 1146-Table'mysql.role_edges' doesn't exist

**Bug 重现步骤(有截图更好)**
1.  打开 navicat-jumpserver-MySQL5 的连接
2. 点击用户
![navicat-jump](https://user-images.githubusercontent.com/30860085/175242693-8d988c12-399a-419f-b849-32e43ba37921.png)

分析-供参考：
MYSQL-5 本来就没有 mysql.role_edges 表，这个表是在 MYSQL-8 后才引入的。

**Comment by jym503558564** [comment]
已反馈开发人员，如有优化，我们将在后续版本发布。请持续关注我们版本发布情况～

**Comment by changeflyhigh** [comment]
问题还没解决呀

**Comment by ibuler** [comment]
小问题，等待以后处理了，可能需要每个版本数据库开一个端口了，存在不兼容的问题

**Comment by changeflyhigh** [comment]
OK, 期待后续的新版本！
