### ISSUE TITLE
[Question] 系统用户自动推送的问题

### ISSUE THREAD

**Issue by Nidhoggur1993** [jumpserver/jumpserver#8469]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.1

**问题描述**
在`用户管理-系统用户`中，如果某个系统用户不启用自动推送，那么在`系统用户详情`中，右侧的`快速更新`栏中的`立即推送用户`按键会被置灰，资产右侧的`操作`栏中，推送按钮也会被置灰，见下图
![image](https://user-images.githubusercontent.com/12947582/175252990-1893bf0b-dc45-44fa-bf91-20606f832717.png)

我的理解是，如果我把自动推送取消，这两个按键应该是给我手动推送系统用户的，如果这两个按键不可用的话，要怎么才能手动推送系统用户到资产呢？
PS：这批资产的管理用户都是正常可连接的

**Comment by jym503558564** [comment]
需要开启推送按钮

**Comment by Nidhoggur1993** [comment]
> 需要开启推送按钮

具体在哪里开启呢？
我理解这个是自动推送吧？就是定期会推送一次的那种
![image](https://user-images.githubusercontent.com/12947582/175266484-0e068887-a95e-4d7a-9e4b-dc3f9706ff0e.png)

如果这个选项是推送控制开关的话，是不是修改一下描述更合适呢？

**Comment by wojiushixiaobai** [comment]
参考快速入门文档，需要开启自动推送选项才能在资产上面创建不存在的用户或者更新用户
