### ISSUE TITLE
TemplateDoesNotExist at /login/

### ISSUE THREAD

**Issue by hmtiannan** [jumpserver/jumpserver#847]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2
##### 问题复现步骤
[root@centos701 jumpserver-0.3.2-rc2]# python manage.py runserver 0.0.0.0:8000
Validating models...

0 errors found
December 06, 2017 - 22:33:13
Django version 1.6, using settings 'jumpserver.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[06/Dec/2017 22:33:31] "GET / HTTP/1.1" 302 0
[06/Dec/2017 22:33:31] "GET /login/ HTTP/1.1" 500 85400

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/20086500/33666680-bdd05ec4-dad5-11e7-9efd-ae72986845ca.png)

##### 其他
TemplateDoesNotExist at /login/

Request Method: | GET
-- | --
http://192.168.163.130:8000/login/
1.6
TemplateDoesNotExist
login.html
/usr/lib64/python2.7/site-packages/django/template/loader.py in find_template, line 131
/usr/bin/python
2.7.5
['/root/jumpserver-0.3.2-rc2',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib/python2.7/site-packages']
Wed, 6 Dec 2017 22:33:31 +0800
Template-loader postmortem

Django tried loading these templates, in this order:
Using loader django.template.loaders.filesystem.Loader:
/root/jumpserver-0.3.2-rc2/templates/login.html (File does not exist)
Using loader django.template.loaders.app_directories.Loader:
/usr/lib64/python2.7/site-packages/django/contrib/admin/templates/login.html (File does not exist)
/usr/lib64/python2.7/site-packages/django/contrib/auth/templates/login.html (File does not exist)
/usr/lib/python2.7/site-packages/bootstrapform/templates/login.html (File does not exist)

**Comment by ibuler** [comment]
查看 /root/jumpserver-0.3.2-rc2/templates/ 中是否有 login.html
