### ISSUE TITLE
[Feature] 请问是否能支持在 K8S 连接中使用 helm

### ISSUE THREAD

**Issue by get-set** [jumpserver/jumpserver#8476]
**需求或建议**：
在 K8S 连接中使用 helm 命令（或者其他类似工具，比如 kustomize 等）

**目前的情况**：
我尝试将 `helm` 执行文件 cp 到 jms_koko 的 `/usr/local/bin` 下，然后在 JumpServer Terminal 中使用 `helm` 命令，发现会报

```
# helm list
Error: list: failed to list: secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "default"
```

而 `kubectl` 命令是有相应的权限的。

**请问**：
- 这个 `system:anonymous` 用户是哪里来的，即使明确用 `export KUBECONFIG=.kube/config` 指定 kubeconfig 也不行。
- 看了一下 koko 里边，对于每次连接会用 `unshare --fork --pid --mount-proc /opt/koko/init-kubectl.sh` 起一个，请问 `rawkubectl` 和 `kubectl` 的区别是什么呀？是自行构建的加入某些机制的版本吗？有没有相应的代码可以学习一下哒？
- 请问是否有关于 JumpServer 连接 K8S 的实现机制的文档啊？

借 Issue 感谢一下，谢谢技术团队做了这么好的软件，好用！

**Comment by cywang4** [comment]
我发现.kube/config缺少集群证书和user的token，所以helm会报错如下：
Error: list: failed to list: secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "default"

**Comment by get-set** [comment]
> 

koko 对 kubectl 加了一层壳来处理 token 认证问题，helm 也需要这样做，我提了个 pr 增加 helm 工具命令，https://github.com/jumpserver/koko/pull/910。
