### ISSUE TITLE
[Feature] 支持无用户名/密码方式连接mongodb数据库

### ISSUE THREAD

**Issue by gebing** [jumpserver/jumpserver#8479]
**请描述您的需求或者改进建议.**
现在jump-server连接mongodb数据库时，必须创建mongodb的带用户名/密码的普通用户，能否支持无用户名/密码方式连接mongodb数据库？

**Comment by wojiushixiaobai** [comment]
收到，我们评估下。

**Comment by ibuler** [comment]
为了安全，还是设置一个密码吧

**Comment by phantomlsh** [comment]
同样有这个需求。是否可以向MongoDB Compass那样提供基于ssh隧道的mongodb管理方案？我们的数据库都是仅允许本地访问的。
