### ISSUE TITLE
[Feature] Web终端资产列表自动展开

### ISSUE THREAD

**Issue by sicode** [jumpserver/jumpserver#8498]
**请描述您的需求或者改进建议.**
目前的设计每次进入终端 都得手工点开左侧的资产列表再连接，多层级的时候有点麻烦

其实要么把搜索框直接放出来，我可以直接搜索，不需要现在手工点  放大镜 再输入关键字 搜索

要么增加设定 是否自动展开资产列表

**Comment by ibuler** [comment]
你右击一下图标试试

**Comment by sicode** [comment]
噢噢，右键 展开 所有资产
