### ISSUE TITLE
[Bug] v2.18.1 k8s 环境登陆异常

### ISSUE THREAD

**Issue by Changego** [jumpserver/jumpserver#8499]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.18.1
**环境描述**
域名--https（nginx）--traefik ---K8s

**Bug 描述**
域名打开非常慢，请帮忙看下什么情况。多谢。
/api/v1/settings/public/open/ 应该这个接口
**Bug 重现步骤(有截图更好)**

![1656390422210](https://user-images.githubusercontent.com/4628191/176093056-f50cd10b-76d6-480e-b696-22d7d8a1f74a.png)
正常点击无响应，直接访问秒开。

![16563906709964](https://user-images.githubusercontent.com/4628191/176093069-bc6b9fdc-234c-4617-aa28-294baa0d3890.png)

**Comment by wojiushixiaobai** [comment]
无法复现，测试下不通过代理是否有问题
