### ISSUE TITLE
通过 Xshell 批量推送后 断开的问题

### ISSUE THREAD

**Issue by AnndaGH** [jumpserver/jumpserver#850]
根据观察响应时间较长的命令例如 通过yum安装一些依赖关系可能30秒左右，通过xshell执行，有时候没有返回就断开了，有时候是刚返回一部分内容就断开了。但是通过网页来批量推送却没有问题，xshell推送一些简单的命令比如date也可以正常执行并返回，是xshell哪里有问题，哪里需要配置吗？

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.3.2

**Comment by ibuler** [comment]
没有30s就断开限制，请查找其他原因和报错
