### ISSUE TITLE
[Feature] 关于Web终端搜索功能

### ISSUE THREAD

**Issue by vzrs** [jumpserver/jumpserver#8509]
从2.20.1更新到2.23.2，发现Web终端搜索功能发生了变化，新版的搜索方式不是特别理想，菜单栏收缩到比较窄的时候搜索栏就看不到了。如果是为了分别搜索“我的资产”和“我的应用”，建议还是沿用之前的UI，在名称下面设置搜索栏。

**Comment by wojiushixiaobai** [comment]
收到，我们看看如何优化下。

**Comment by ibuler** [comment]
做了优化了，就不能退步了，只能基于现有的进行优化了
