### ISSUE TITLE
无法ssh公钥登录

### ISSUE THREAD

**Issue by jabbber** [jumpserver/jumpserver#851]
无法ssh公钥登录

##### 使用版本
b0297e5fecacc2d2b35d94d58f3c29e30f523694
之后的所有版本，无法ssh公钥登录

##### 问题复现步骤
1. /users/profile/
2. 点击重置SSH密钥，输入后保存
3. ssh公钥显示为空
4. 通过ssh客户端登录时公钥验证失败，只能输入密码登录

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
如果没有显示指纹，可能就没有更新成功

**Comment by ibuler** [comment]
删掉数据里的记录，重新更新一下试试

**Comment by jabbber** [comment]
我删掉用户新建就是如此，回退到我说的版本就正常了，看了代码的差异，应该是改出问题了

**Comment by ibuler** [comment]
回退到哪儿版本没问题了，我对比一下

**Comment by JarboU** [comment]
我升级到 V2.28.1，保存ssh公钥的时候显示成功，但是查看用户是无 ssh指纹，也无法用此用户登录系统。ps: 克隆一个已有密钥的用户，在未保存的时候都能看到 ssh 指纹，保存后再查看详情或编辑此用户均未查看到 ssh 指纹。
