### ISSUE TITLE
[Bug] Mysql命令过滤器偶发无法命中

### ISSUE THREAD

**Issue by zhongjun96** [jumpserver/jumpserver#8510]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.22.2 GPLv2.

**浏览器版本**
Chrome 101.0.4951.41
iTerm2 Build 3.4.15

**Bug 描述**
Mysql 命令过滤器会被跳过

**Bug 重现步骤(有截图更好)**
1.  添加两条命令过滤。`update .*`禁止。`update .* where .*`允许。![](https://user-images.githubusercontent.com/18225577/176575678-845ce94d-0b4f-4c2e-aea0-4ad6492258f2.png)
2. cli连接数据库，操作 `update xxx set aa='bb';` 命中拦截。操作` update xxx set aa='bb' where id = 1; ` 允许操作。<br/>
3.  再次操作 ```update xxx set aa='bb';``` 未命中拦截。
4. ![](https://user-images.githubusercontent.com/18225577/176576289-d88b71ba-43c4-4040-ab88-d85af62ebab8.png)

**Comment by zhongjun96** [comment]
会话详情的命令记录也出现不一致的情况：
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/18225577/176579814-abbf1df9-b559-4adf-8ef9-9c288c156e59.png">

**Comment by LeeEirc** [comment]
命令拦截和命令记录，都是与命令解析直接相关，基于目前的技术实现，只能等后续的优化，增强准确度。

**Comment by jym503558564** [comment]
已知问题，后续若有优化，我们将会在将来版本发布。
