### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NickWang2** [jumpserver/jumpserver#8516]
**JumpServer 版本(v1.5.9以下不再支持)**
luna v2.22.1

**浏览器版本**
firefox 2020.8

**Bug 描述**
用WEB CLI 连接Mysql，未选择 ”禁用自动补全“。选中 ”禁用自动补全“ 时正常。
1。当mysql表数量很多时（我测试的表有几千个），mysql --auto-rehash --user=xxx  进程CPU使用率很高，webcli没反应。
即使用户关闭webcli连接，对应的进程仍然一直存在长达几个小时。

2。如何改成默认选中 ”禁用自动补全“？
修改/opt/luna/main.a6769b870feddb6ed98b.js
label:"Disable auto completion",value:!1}]}  ==》 value:!0
this.isShowAdvancedOption=!1 ==》 this.isShowAdvancedOption=!0
页面显示已选中 ”禁用自动补全“ ,但提交时未生效 disableautohash仍然是空

最后只能
e=this.getFilteredField("disableautohash"),n=e&&e.value?1:"" ==》 e=this.getFilteredField("disableautohash"),n=e&&e.value?1:1
强制设置为1使”禁用自动补全“选项失效。

**Comment by ibuler** [comment]
新版本支持了
