### ISSUE TITLE
[Bug] 2.19版本导出用户有效性字段为空；2.23版本导入用户模板excel报错，提示系统用户组织用户字段必须为string

### ISSUE THREAD

**Issue by shenzhihao1** [jumpserver/jumpserver#8519]
JumpServer 版本：v2.19及后续版本

浏览器版本：chrome浏览器

**Bug 描述**
导出用户列表，查看excel的用户是否有效字段为空值。2.23版本，导入用户模板excel报错，提示系统用户组织用户字段必须为string

**Bug 重现步骤(有截图更好)**
问题1：
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/101631442/176654671-6df7792a-871b-4d63-a7a0-60b00127c94b.png">

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/101631442/176654759-5f80adb1-8191-4bec-9621-69a03c928d72.png">

问题2：
这是2.23版本导出的用户列表
<img width="339" alt="20d2c248f8452de19c1bff332d5b52d" src="https://user-images.githubusercontent.com/101631442/176654878-319a29e6-b8dd-4de4-9093-f7e043b32696.png">

不做任何改动导入进去
<img width="298" alt="6e2c44aea195f61839a0518a06ff4d6" src="https://user-images.githubusercontent.com/101631442/176655041-19ce916a-0821-4d83-8b71-c02ac61403a0.png">

必须改成字符串才能导入
<img width="833" alt="09207d95142e20aff68ab39b475b1a6" src="https://user-images.githubusercontent.com/101631442/176655111-bcd6db24-f2a1-414c-9045-077db2bcae5f.png">

这对于用户来说体验差。

**Comment by BaiJiangJie** [comment]
将会在 v2.24 中进行修复，目前已修复到 dev。

https://github.com/jumpserver/lina/pull/1854

https://github.com/jumpserver/jumpserver/pull/8518
