### ISSUE TITLE
我想问一问现在的jumpserver是否支持和openldap结合？

### ISSUE THREAD

**Issue by buzhiren** [jumpserver/jumpserver#852]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by peablog** [comment]
支持的

**Comment by buzhiren** [comment]
@peablog 大哥，你不用回答的这么高冷吧，就三个字，既然支持，你至少给个大体的操作步骤吧，或者大体的实现方法也行呀，新公司最近要用jumpserver结合ldap，我很迷茫的。

**Comment by peablog** [comment]
@buzhiren 打开配置文件修改LDAP相关配置就完了？要怎么说？

**Comment by buzhiren** [comment]
你说的是0.3版本吗，

**Comment by jiaxiangkong** [comment]
v0.3.2不支持  v0.4.0支持

**Comment by leochan007** [comment]
@jiaxiangkong docker版本也可以吧？怎么配置呢、

**Comment by topicgit** [comment]
版本 0.4.0 ，我配置了ldap之后不能使用ldap中的用户连接coco和登陆jms，而且我也没看到系统上有同步用户的按钮，请问这个有文档说明吗？
下面是我的ldap配置，我直接修改的jumpserver容器里面的config.py
`    # LDAP Auth settings
    AUTH_LDAP = True
    AUTH_LDAP_SERVER_URI = 'ldap://10.18.7.144:389'
    AUTH_LDAP_BIND_DN = 'dc=ipa,dc=jie,dc=com'
    AUTH_LDAP_BIND_PASSWORD = 'axxx123'
    AUTH_LDAP_USER_DN_TEMPLATE = 'uid=%(user)s,cn=users,cn=accounts,dc=ipa,dc=jie,dc=com'
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "uid",
        "name": "uid",
        "email": "mail"
    }
    AUTH_LDAP_START_TLS = False`

**Comment by ibuler** [comment]
不需要同步，登陆是会自动调用

**Comment by topicgit** [comment]
用最新代码测试可以了，谢谢。
