### ISSUE TITLE
登录交换机提示密钥交换失败

### ISSUE THREAD

**Issue by Darren-qu** [jumpserver/jumpserver#8523]
![image](https://user-images.githubusercontent.com/86956804/176881215-efb95810-78c9-43d4-85cf-d1497258b7d8.png)

ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [diffie-hellman-group1-sha1 diffie-hellman-group14-sha1 ecdh-sha2-nistp256 ecdh-sha2-nistp521 ecdh-sha2-nistp384 curve25519-sha256@libssh.org], server offered: [diffie-hellman-group16-sha512 diffie-hellman-group15-sha512 diffie-hellman-group14-sha256 diffie-hellman-group-exchange-sha256]

**Comment by LeeEirc** [comment]
使用的那个版本？ 什么型号的交换机？

**Comment by LeeEirc** [comment]
使用最新的版本试试

**Comment by leon-fans** [comment]
> 最新版的修复了这个问题, Eric 谢谢您。

您好，能问一下您是用哪个版本修复了这个问题？

**Comment by Darren-qu** [comment]
Version v2.23.2 GPLv2.
