### ISSUE TITLE
[Bug] quick_start.sh 连接外部数据库报错

### ISSUE THREAD

**Issue by Nidhoggur1993** [jumpserver/jumpserver#8538]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.1

**Bug 描述**
按正常步骤执行 bash quick_start.sh，在数据库阶段选择连接外部数据库，脚本报错，但是命令行可以正常连接数据库

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/12947582/177278779-1169b91b-4b85-456b-85e8-5f554bc5c8e5.png)

库的字符都是utf8
![image](https://user-images.githubusercontent.com/12947582/177279438-2615adcf-40b3-4bbe-9ee7-5ce418bfa43c.png)

**Comment by wojiushixiaobai** [comment]
这并不是 bug，容器默认的网段是 172.17.0.0/16
你实际的服务器网段 和  容器的 网段已经冲突。
自然没法访问
