### ISSUE TITLE
请问系统用户和管理用户是怎么定义的？

### ISSUE THREAD

**Issue by gtfcugb** [jumpserver/jumpserver#854]
麻烦好心人解释下。

**Comment by jiaxiangkong** [comment]
哪个版本

**Comment by sz233** [comment]
0.4.0的版本
管理用户需要有目标服务器的ALL sudo 权限，可以是root，用于推送系统用户。
系统用户可以通过跳板机登录目标机，是由管理用户创建的。

**Comment by wojiushixiaobai** [comment]
楼上回答得很清楚了，系统用户在你创建后，会被管理用户推送到服务器上，不需要你人为去添加，用
户可以关联系统用户，通过系统用户来限制用户的权限。
