### ISSUE TITLE
[Bug] 命令过滤里面把rm设置为拒绝，有个用户给自己赋权之后就rm成功了，希望一直阻止用户rm

### ISSUE THREAD

**Issue by e68zts** [jumpserver/jumpserver#8542]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.22.1 GPLv2.

**浏览器版本**
版本 96.0.4664.93（正式版本） （64 位）

**Bug 描述**
命令过滤里面把rm设置为拒绝，有个用户给自己赋权之后就rm成功了
![image](https://user-images.githubusercontent.com/22285555/177459492-1f075a96-c43d-4ba2-b14e-5b3c747f05ae.png)

**Bug 重现步骤(有截图更好)**
1.  登录admin用户，在 资产管理--命令过滤 先创建一个命令过滤，在添加一个防止rm规则
我添加的如下
![image](https://user-images.githubusercontent.com/22285555/177460129-4f411531-952b-438c-9a3a-6d049fe7d495.png)

2.  用户rm删除第一次没有成功，给自己赋权之后就rm成功了，希望一直阻止用户rm动作

**Comment by wojiushixiaobai** [comment]
只能防呆，绕过的方法很多，建议资产管理员将 rm 二进制权限修改

**Comment by e68zts** [comment]
提个建议，，，，用户在通过web输入的命令是通过webscoket方式传给虚拟机去执行的对吧，这样的话，我们在webscoket接收用户输入命令的时候，判断一下，如果是rm并且规则是拒绝，不交给虚拟机执行，这样处理是否可行呢
