### ISSUE TITLE
[Question] 用mobaxterm软件 sftp连接堡垒机，不能上传文件。xshell 软件、web终端能正常上传

### ISSUE THREAD

**Issue by mogecheche** [jumpserver/jumpserver#8545]
**请描述您的问题.**
版本2.22.4 ，通过mobaxterm软件，直接sftp 用户名@jms 2222，上传文件至模板资产，传输进度一直0%
![image](https://user-images.githubusercontent.com/32326629/177482331-6b1684e3-5aef-4b6d-959c-a4bba24bbd2c.png)

**Comment by LeeEirc** [comment]
刚下载了一个mobaxterm，无法复现你的问题
![image](https://user-images.githubusercontent.com/32626707/177724682-d5666f02-1dfc-4f19-9f68-f353c5941be9.png)
![image](https://user-images.githubusercontent.com/32626707/177724750-73217e09-1f3b-4a57-948b-a50a25b34b1b.png)
![image](https://user-images.githubusercontent.com/32626707/177725122-bd60d052-3b14-4edf-908f-497a1492d6b1.png)
