### ISSUE TITLE
[Bug] 2.20 升级到2.23.2 报Access key 已失效, 重新注册，但是2.20的版本没有magnus 这个服务

### ISSUE THREAD

**Issue by yangjie-mr** [jumpserver/jumpserver#8548]
**JumpServer 版本(v1.5.9以下不再支持)**
2.20  2.23.2

**浏览器版本**
103.0.5060.114

**Bug 描述**
2.20 升级到2.23.2 报Access key 已失效, 重新注册，但是2.20的版本没有magnus 这个服务,所以找不到那个key

**Bug 重现步骤(有截图更好)**
1.  
![3e081a917fb99af6058e8f9ae47662f](https://user-images.githubusercontent.com/46342047/177702249-fb0406af-d1aa-4dea-a9b3-2f3051b0c433.png)

**Comment by wojiushixiaobai** [comment]
去 web 页面的安全设置把 允许组件注册 功能打开

**Comment by yangjie-mr** [comment]
好的，解决了，谢谢
