### ISSUE TITLE
创建资产失败

### ISSUE THREAD

**Issue by sunhackboy** [jumpserver/jumpserver#855]
![2](https://user-images.githubusercontent.com/33950419/33831291-6c1f5dec-deb2-11e7-9841-19f99e449509.png)

[简述你的问题]

##### 使用版本
jumpserver 0.4.0

##### 问题复现步骤
1.按照如下连接安装
https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F
2. 创建资产
![1](https://user-images.githubusercontent.com/33950419/33831087-98013292-deb1-11e7-82d8-2d23bd498ed7.png)
![3](https://user-images.githubusercontent.com/33950419/33831301-744895f6-deb2-11e7-8fc1-63d34fd0757d.png)

![2](https://user-images.githubusercontent.com/33950419/33831304-78a0fa9e-deb2-11e7-98ef-5374f785abfa.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by sunhackboy** [comment]
设置管理用户时，选择密钥方式，在创建资产，设置管理用户时报错，使用密码方式，没有问题

**Comment by liuzongqing** [comment]
遇到相同问题

Request Method: | POST
-- | --
http://10.0.74.106:8081/assets/asset/create/
1.11
TypeError
initial_value must be str or None, not dict
/opt/jumpserver/apps/common/utils.py in ssh_key_string_to_obj, line 185
/opt/jumpserver_env/bin/python
3.6.1
['/opt/jumpserver/apps',  '/usr/local/python3/lib/python36.zip',  '/usr/local/python3/lib/python3.6',  '/usr/local/python3/lib/python3.6/lib-dynload',  '/opt/jumpserver_env/lib/python3.6/site-packages',  '/opt/jumpserver',  '/opt/jumpserver/apps']
星期二, 26 十二月 2017 18:46:09 +0800

**Comment by gefangshuai** [comment]
同样的问题：
![image](https://user-images.githubusercontent.com/3143306/34467429-75adb6ee-ef2c-11e7-9ed2-ee27b9a954a4.png)

**Comment by ibuler** [comment]
新版本修复了
