### ISSUE TITLE
[Bug] v2.23.2单机全docker模式magnus使用内存会一直上涨直到内存爆满导致进程全部离线

### ISSUE THREAD

**Issue by Changego** [jumpserver/jumpserver#8550]
**JumpServer 版本(v1.5.9以下不再支持)**
 v2.23.2

**Bug 描述**
v2.23.2单机全docker模式magnus使用内存会一直上涨直到内存爆满导致进程全部离线。 

**Bug 重现步骤(有截图更好)**
![20220707153108](https://user-images.githubusercontent.com/4628191/177717235-085aab7a-ca38-4e8c-b495-14525d9039ab.png)

![20220707153209](https://user-images.githubusercontent.com/4628191/177717384-7cf0dc1e-54ed-42ad-a361-c590b9ee167d.png)

![image](https://user-images.githubusercontent.com/4628191/177717526-5a833713-9d42-4461-a71e-5dcc87189a04.png)

**Comment by wojiushixiaobai** [comment]
如何复现过程？或者使用什么客户端出现的此问题？

**Comment by Changego** [comment]
服务启动 后 magnus占用内存就会一直增加。

**Comment by Changego** [comment]
oad config from env
{ComponentName:magnus Name:[Magnus]-itsa-0d49daa6fd09 CoreHost:http://core:8080 BootstrapToken:YzVlMzUyZGQtOWVl BindHost:0.0.0.0 BindPort:9090 LogLevel:ERROR RootPath:/opt/magnus ExecuteProgram:/opt/magnus/magnus DataFolderPath:/opt/magnus/data LogFolderPath:/opt/magnus/data/logs KeyFolderPath:/opt/magnus/data/keys AccessKeyFilePath:/opt/magnus/data/keys/.access_key}

**Comment by Aaron3S** [comment]
您在微信群里吗， @沈晨阳，帮您处理这个问题。

**Comment by Changego** [comment]
不在群里，需如何处理呢？

**Comment by Aaron3S** [comment]
您加我微信吧。 我帮你看看环境，存在什么问题，一起定位一下问题 vx: 17610225326

**Comment by ambition0222** [comment]
全都放在k8s上，也是 magnus占用内存一直增加，一周的时间就涨到3G以上

**Comment by ambition0222** [comment]
v2.23.2的版本镜像

**Comment by dxygit1** [comment]
我也有同样的问题  可以方便告知下 是什么原因么？

**Comment by wojiushixiaobai** [comment]
@dxygit1 WAF 扫描端口导致的，可以将 magnus 端口加入白名单试试。

**Comment by dxygit1** [comment]
> @dxygit1 WAF 扫描端口导致的，可以将 magnus 端口加入白名单试试。

好的  多谢。
