### ISSUE TITLE
[Bug] 使用DB Client方式连接mysql，5分钟之后token就过期了，数据库断开连接

### ISSUE THREAD

**Issue by jerryyim** [jumpserver/jumpserver#8555]
**JumpServer 版本(v1.5.9以下不再支持)**
2.23.2

**浏览器版本**
chrome 97.0.4692.71（正式版本） （64 位）

**Bug 描述**
使用DB Client方式连接mysql，5分钟之后token就过期了，数据库断开连接

**Bug 重现步骤(有截图更好)**
1.  连接mysql应用资产，选择 ”使用客户端执行“；
2. 5分钟之后，客户端提示与mysql断开连接，且无法重新连接，需要到jumpserver重新连接该资产；
3. jumpserver配置文件已有配置CONNECTION_TOKEN_EXPIRATION=3600，且重启过；
4.jumpserver web的连接最大空闲时间也设置的是30分钟
![9fe84360b0853a8c19a7c6e72eed436](https://user-images.githubusercontent.com/63450852/177746763-d835b882-713f-4f93-a496-47a3b01c6c29.png)

**Comment by BaiJiangJie** [comment]
看截图数据库本身是不是有什么限制啊？

显示 Lost connection to MySQL server during query ...

**Comment by BaiJiangJie** [comment]
或者换一个数据库试试呢？比如说redis

**Comment by jym503558564** [comment]
无法复现。
@jerryyim 目前该问题还存在吗？

**Comment by xiaohui1997** [comment]
该问题一直存在，默认是300s有效期并且没有办法在页面上做更改，有时候需要使用navicat长时间使用根本没办法 过五分钟就得重新输入最新的账号密码才行，建议官方可以把这块弄成可配置项，长时间使用真的很有必要呀。

**Comment by jym503558564** [comment]
token过期时间可配置，用户一直使用该token是会续期。
# 设置connection token过期时间, vim /opt/jumpserver/config/config.txt
CONNECTION_TOKEN_EXPIRATION=300

**Comment by BruceLinda** [comment]
> 该问题一直存在，默认是300s有效期并且没有办法在页面上做更改，有时候需要使用navicat长时间使用根本没办法 过五分钟就得重新输入最新的账号密码才行，建议官方可以把这块弄成可配置项，长时间使用真的很有必要呀。

请问你解决了吗？我也出现了类似的情况

**Comment by BruceLinda** [comment]
> **JumpServer 版本(v1.5.9以下不再支持)** 2.23.2
> 
> **浏览器版本** chrome 97.0.4692.71（正式版本） （64 位）
> 
> **Bug 描述** 使用DB Client方式连接mysql，5分钟之后token就过期了，数据库断开连接
> 
> **Bug 重现步骤(有截图更好)**
> 
> 1. 连接mysql应用资产，选择 ”使用客户端执行“；
> 2. 5分钟之后，客户端提示与mysql断开连接，且无法重新连接，需要到jumpserver重新连接该资产；
> 3. jumpserver配置文件已有配置CONNECTION_TOKEN_EXPIRATION=3600，且重启过；
>    4.jumpserver web的连接最大空闲时间也设置的是30分钟
>    ![9fe84360b0853a8c19a7c6e72eed436](https://user-images.githubusercontent.com/63450852/177746763-d835b882-713f-4f93-a496-47a3b01c6c29.png)

我也出现了类似的情况，我设置CONNECTION_TOKEN_EXPIRATION=2592000，过会断开连接再重新连就连接不上了
