### ISSUE TITLE
SMTPServerDisconnected

### ISSUE THREAD

**Issue by zhaosi2017** [jumpserver/jumpserver#856]
[简述你的问题]

Request Method: | POST
-- | --
http://XXXXXX:8000/juser/user/edit/?id=2
1.6
SMTPServerDisconnected
Connection unexpectedly closed
/usr/lib64/python2.7/smtplib.py in getreply, line 367
/bin/python2.7
2.7.5
['/opt/jumpserver',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib/python2.7/site-packages']
Tue, 12 Dec 2017 11:28:15 +0800

[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
     版本:0.3.2
##### 问题复现步骤
1. [步骤1]   新建用户, 填的google邮箱.
2. [步骤2]  给新建的用户发邮件.

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/27183509/33866691-b7deac92-df2a-11e7-95a5-4917f01dcc1a.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by jiaxiangkong** [comment]
用465端口  配置文件 jumpserver.conf  SSL改为true

**Comment by zhaosi2017** [comment]
已解决
