### ISSUE TITLE
[产品设计] 系统用户和资产账号的分离

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#8560]
<p>JumpServer 中系统用户是登录资产的实体，也是授权的实体。登录资产意味这要有账号密码，如果公司资产比较多，因为等保要求通常账号密码还不一样，解决方案有两个：</p><ol><li>创建 <strong>多个系统 </strong>用户，每个系统用户的账号密码不一样</li><li>创建 <strong>一个系统 </strong>用户，为每个资产设置不同的账号密码</li></ol><p><br /></p><p>这两种方式都存在一些问题，</p><ol><li>创建多个系统用户会为授权带来不便，不能在使用节点授权，或者批量授权，只能一个资产一个资产的授权，批量授权会导致登录的时候去选择那个对的系统用户，否则无法登录</li><li>创建一个系统用户，为不同资产设置不用的账号密码，目前这种方式，引导不够明显，一些用户并不知道，也是后续才支持的功能。另外对于系统用户在不同资产上设置账号密码，感觉也不好理解，也会导致资产上有相同用户名的账号，但是密码不一样，因为都可以为系统用户在资产上设置不同的密码（当然这个在上述中也存在），所以资产账号清晰度还是不够，不够唯一</li></ol><p><br /></p><p>所以我们想能不能将系统用户和资产账号分离开来，系统用户拥有用户名，但不再拥有密码信息，只是用来做授权。用户登录的时候，根据系统用户的名称去选择资产上的账号凭证去登录，资产上的账号名不能重复，所以必然只能选到一个，如果登录不上，很方便定位密码问题。</p><p><br /></p><p>这就要求 创建的资产的时候，需要为资产上设置登录账号，登录时选择系统用户才不会有问题。原来本身我们其实是有账号这层的，但是原来的 <strong>资产账号</strong> 是 <strong>资产</strong> 和 <strong>系统用户，</strong>他们三者之间是强关联关系<strong>，</strong>表如下</p><p><br /></p>

ID | 用户名 | 密码 | 系统用户 | 资产
-------- | -------- | -------- | -------- | --------
1 |   |   | S1 | A1
2 |   | xxx | S1 | A1
3 | web | xxx |   | A1

<p class="auto-cursor-target"><br /></p><p class="auto-cursor-target">注: 系统用户 S1 用户名都是 web，S1，A1 在表中以 ID 形式存在</p>

<ul style="list-style-type: square;"><li class="auto-cursor-target">id1 是 系统用户资产关联，没有单设置密码是只是关联关系，没有账号表中没有密码，账号密码在系统用户上</li><li class="auto-cursor-target">id2 是 系统用户在资产上单独设置了密码</li><li class="auto-cursor-target">id3 是 改密生成的账号</li></ul><p>所以登录时，优先选择 id3 作为登录，因为是改密生成的，优先级高，其次是 id2 单独设置的，最后才是 id1，是不是有点麻烦</p><p><br /></p><p>如果我们将账号设置为和资产强关联，和系统用户弱关联就是</p><p><br /></p>

ID | 用户名 | 密码 | 资产
-------- | -------- | -------- | --------
1 | web | xxx | A1
2 | web | xxx | A2
3 | root | xxx | A1

<p class="auto-cursor-target"><br /></p><p class="auto-cursor-target">当 使用系统用户 S1 登录 资产A1，S1 用户名是 web， 就来账号表中寻找&nbsp; 用户名是 web 资产时 A1 的记录，最多只能找到一个，关系明朗了很多</p>

有些人可能有疑问，为何不把系统用户去掉呢，直接使用账号，授权里也写账号？

这样也有问题，就是授权的时候不得不一个个授权(一个资产、一个账号添加一个授权) = 麻烦，
或者根据用户名授权，但是用户名相同的他们之间没有关系吗？比如 root 账号，他们只是在不同资产上的密码不一样，其他特性很相似，比如权限，比如应该禁止的命令。 

所以系统用户是登录资产的实体，登录时会选择 系统用的一些规则做约束，会选择系统用户名称一样的资产账号进行登录

**Comment by ibuler** [comment]
大家使用表情说明一下是否支持

**Comment by internelp** [comment]
支持，解决批量授权时登录要选择一大堆账号。
账号应当和资产强关联。

**Comment by 2022liuws** [comment]
非常有必要

**Comment by bitqiu** [comment]
有必要

**Comment by putianhui** [comment]
感觉有必要的

**Comment by dzhyw** [comment]
登陆选账户，确实很麻烦

**Comment by plateauandsp** [comment]
有必要，尤其在大规模资产、用户资产密码还都不太一样的时候，初始化录入和授权是个噩梦。

**Comment by evilgaoshu** [comment]
支持强关联；另外资产授权配置希望能更加灵活，比如支持嵌套（套娃）等，减小精细授权下的配置工作量

**Comment by jozzlee** [comment]
是否可以考虑转向以人为本的授权模式呢？“等保要求通常账号密码还不一样”这其实就已经是因人授权的模式了，在现有的以资产为核心的授权模式里怎么改都别扭。我的想是不是可以不要坚持做资产-系统用户-人三方关联，改成 资产-系统用户，资产-人，系统用户-人。一个人有权使用某资产而无权使用该资产中的高级系统用户是一个常见的需求，在目前的设计里只能为该资产建两条不同的授权，如果有多个资产存在此情况就要多建很多授权。而如果将现有的资产授权分拆为资产-系统用户管理、用户授权（用户-资产、用户-系统用户）可能会好很多，因为管理中不太可能让某用户在不同资产里的权限不同。

**Comment by khy2021** [comment]
用户在登录资产的时候，是否可以优化下，不显示没有托管密码的系统用户？

**Comment by heatdrive** [comment]
【使用系统用户 S1 登录 资产A1，S1 用户名是 web， 就来账号表中寻找  用户名是 web 资产时 A1 的记录，最多只能找到一个】
->这种是不是就推翻了现在的资产授权逻辑了，也就是说在系统用户S1想要连接资产A1的时候，首先选择资产用户名web，JMS对应查找到唯一资产A1？（因为弱关联所以不一定是有效项，假设输入了一个不存在的web1，再手动选择资产？）
不知道理解对不对。

**Comment by leim** [comment]
这真的是大家诟病的一个事情，资产的账号应该是与资产强关联的，结果在jumpserver里面资产却一直与资产的登录账号无关联，都是通过授权给用户，再由用户自行选择，这样的话，假如用户名下授权了100个资产，每个资产的登录账号都不同，将会是一件噩梦。

**Comment by 15326047083** [comment]
支持支持！同时希望考虑#8696中用户名后缀问题，谢谢~~

**Comment by xyziven** [comment]
支持。这样重构后，系统用户相当于资产账号组的概念？

**Comment by sende** [comment]
1、系统用户和资产强关联关系，创建资产或系统用户时完成关联设置
2、授权时可以沿用现在的交互，可以同时授权资产和用户，但是不需要做系统用户关联资产的动作。
3、最终登陆时判断资产是否有授权，资产对应的系统用户是否授权。如果多个已关联资产系统用户有被授权，这时候可以给用户选择登陆用户。

**Comment by ibuler** [comment]
@xyziven 打算去掉系统用户概念了

**Comment by Weiney** [comment]
十分十分有必要, 这个问题好多人都反馈了, 本身也是易混淆的点
