### ISSUE TITLE
[Question] PostgreSQL是需要收费版本才支持吗

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#8563]
**请描述您的问题.**
![8AFFFAFCA43D3EDBB1CDDB1EC9A42126](https://user-images.githubusercontent.com/16998173/178208902-1ad430b9-8422-4f10-b62f-591be3f51151.jpg)

当前版本Version v2.21.4

**Comment by jym503558564** [comment]
企业版支持PostgreSQL。
