### ISSUE TITLE
mysql 参数不生效

### ISSUE THREAD

**Issue by dzhyw** [jumpserver/jumpserver#8567]
**请描述您的问题.**
修改了mysql超时设置，但是mysql容器里面默认还是显示28800
配置文件里面指定的是
interactive_timeout  =  1800
wait_timeout  = 1800

![image](https://user-images.githubusercontent.com/7122097/178402380-2935d256-d66b-489d-a5ea-3967d9843822.png)

**Comment by wojiushixiaobai** [comment]
推荐使用自建数据库，这个问题我们调查下。
