### ISSUE TITLE
0.4版本中coco和Luna 是什么

### ISSUE THREAD

**Issue by buzhiren** [jumpserver/jumpserver#857]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤

不是很了解coco和luna在jumpserver 0.4版本中是什么服务，插件吗？

##### 其他

[注:] 完成后请关闭 issue

**Comment by zak2458** [comment]
同问，是为了方便CRT用户来连接吗

**Comment by liuzheng** [comment]
luna 是作为未来jms的前端而起的项目，未来将逐步替代jms的前端渲染工作
coco是提供websocket和ssh协议的程序，未来将由其提供webterminal和webRDP以及ssh连接的功能
为什么要拆分？
功能拆分，细化，使用更优秀的编程语言和工具进行开发对应的项目。
用户体验上来说，部署的难度会降低，系统耦合度会降低，开放第三方的系统接入，做开源，就是要开放给大家玩（我们深知我们的开发能力有限，很多功能实现起来可能不如专业人士的完美，需要大家一起努力）。

**Comment by buzhiren** [comment]
感觉coco就是把3.0 ssh到系统的用户，封装到程序里面，用户登录逻辑是：ssh -> coco  ->  系统，省去了用户之间登录跳板机系统。
而luna就是 3.0 web登录连接的加强版本。
是这样理解吗 @liuzheng

**Comment by liuzheng** [comment]
是，但是后期会更加牛逼，解耦后很多东西就可以做的很精细了。

**Comment by buzhiren** [comment]
这样模块化设计很厉害，但是系统用户去掉后，连接其他服务器也是基于ssh吧，那系统用户不分开，不会不安全吗？
@liuzheng

**Comment by liuzheng** [comment]
考虑了，ssh的用户是你登陆jms的用户，你会吧自己的公钥上传上去，ssh的时候是验证私钥和用户名的，通过的话就会拿到和jms一样的数据，全程基于ssh加密。登陆coco后再由coco转发对应的已授权的资产进行连接。

**Comment by buzhiren** [comment]
那coco和授权服务器连接是基于ssh的，那coco这个程序最终是以哪个用户和授权服务器用户ssh的呢？这个我挺好奇，大神有时间的话，告诉一下 @liuzheng

**Comment by liuzheng** [comment]
谁ssh 登coco就是谁啊，按常规思维来想，没啥特别的，谁操作，谁负责

**Comment by buzhiren** [comment]
是我没说清楚，比如我以jms这个用户登录了coco，但是jms用户是没有在跳板机这个服务器系统上生成的，也就是此时jms这个用户只是在coco这个程序里面的，或者说ssh的最后就是root用户吗？

**Comment by liuzheng** [comment]
比如，你在jms的用户名是A，密码是B
现在你可以使用用户名A密码B来登录jms，没毛病
然后你ssh A@coco 使用jms上你上传的公钥锁对应的私钥去登录。
你所做的所有操作和使用jms一模一样。
你所理解的是openssh-server安装后使用系统用户（比如你系统里只有Ubuntu和root）登录
# 但是
coco上去是使用了jms的用户，和这个coco所运行的宿主机是隔离的

从安全角度来讲，coco提供了一个ssh的沙盒，和coco所在的宿主机是隔离的，你根本拿不到coco宿主机的权限。
