### ISSUE TITLE
[Bug] 网关测试连接报错: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#8573]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.2

**浏览器版本**
chrome最新版本

**Bug 描述**
配置网域网关节点后测试了连接报错: Error reading SSH protocol banner
该节点相同的配置在资产里面可以正常连接

**Comment by ibuler** [comment]
确认一下是否开启 ssh forward

**Comment by mrsdpz** [comment]
> 确认一下是否开启 ssh forward



> 确认一下是否开启 ssh forward

我现在只是配置一个网域添加网关,  在网关页面测试连接报错, 还没有通过这个网关去连接别的机器, 和 ssh forward 没关系吧

**Comment by mrsdpz** [comment]
这边看了下源码，在测试网关的连接时先 ssh 到网关，在网关机器上 ssh 127.0.0.1，而我这边ssh没有开放127.0.0.1访问，希望能在文档中注明这一点

**Comment by wojiushixiaobai** [comment]
回环地址没有开放这个说法才对。
