### ISSUE TITLE
[Bug] 网域网关测试连接报错

### ISSUE THREAD

**Issue by haitang5445** [jumpserver/jumpserver#8575]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.2~v2.23.3

**浏览器版本**
chrome最新版本

**Bug 描述**

配置网域网关节点后测试了连接报错:Authentication failed.（网关节点为windows 安装的openssh-win64,使用2.17版本则为正常）
在core 和koko 能正常登录连接到网关节点

**Bug 重现步骤(有截图更好)**

**Comment by ibuler** [comment]
windows ssh 不支持网关功能
