### ISSUE TITLE
用户授权后，登录失败

### ISSUE THREAD

**Issue by csuzhangh** [jumpserver/jumpserver#858]
[简述你的问题]

##### 使用版本
0.4.0

##### 问题复现步骤
1. 添加系统账号
2.进行授权
3. 通过coco登录，提示Auth failed

尝试过密码、public key，尝试过推送用户、自己创建用户，都失败

##### 具体表现[截图可能会更好些,最好能截全]
操作截图
![image](https://user-images.githubusercontent.com/34495019/33918682-be2d8580-dfef-11e7-9d0a-2c9937f1541d.png)

coco中的Systemout日志
![image](https://user-images.githubusercontent.com/34495019/33918780-4b6f6562-dff0-11e7-8de0-dc0b0577f65d.png)

coco输出的日志
<img width="914" alt="_20171213091345" src="https://user-images.githubusercontent.com/34495019/33918754-2ca5877e-dff0-11e7-93b5-dcac040f2548.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by buzhiren** [comment]
同问，资产授权后应该是把系统用户推送过去了，在要连接的服务器是生产了系统用户，但是系统用户下没有生成authorized_keys认证文件，无法连接到服务器

**Comment by csuzhangh** [comment]
我跟踪了一下，似乎是在建立ssh连接时没有获取到正确的密码或密钥，不知是不是个bug

**Comment by buzhiren** [comment]
0.4版本是取消了直接注册系统用户，是coco这个组件来沟通连接的好像，也不知道底层是哪个用户和其他服务器连接

**Comment by buzhiren** [comment]
@csuzhangh  那这个问题你是如何解决的呢，我就卡在这里了

**Comment by csuzhangh** [comment]
使用public key的不知道怎么解决。

使用密码的可能是个bug。
jumpserver使用JSONWebSignatureSerializer将密码加密后存储，例如加密后为b'eyJhbGciOiJIUzI1NiJ9.IjFxYXoyd3N4Ig.GLR3t8nyHPS4qUdtZ3oQWyHrRLOs6rd409gYKENzgI4'，如果直接使用这个密文去解密，就会报错，如果将开头的b'和结尾的'去掉，解密就没问题，相应的使用密码也可以正常登陆。
修改内容：
jumpserver/apps/common/utils.py的第65行，改为
return s.loads(value[2:-1])

**Comment by buzhiren** [comment]
@csuzhangh 那jumpserver上coco是以哪个用户和授权服务器ssh的呢，你说的这个加密是加密的哪个用户的密码？

**Comment by csuzhangh** [comment]
这个加密的是系统用户的密码，也就是推送到客户端的那个用户

**Comment by buzhiren** [comment]
不是，我不了解的是，跳板机要和授权的服务器ssh，但是跳板机服务器上又不生成任何系统用户，coco这个程序最后都是要依托一个系统用户和授权服务器的系统用户ssh的吧，那这个coco依托的系统用户又是什么

**Comment by sz233** [comment]
我昨天也遇到了这个问题，是因为我没有弄清管理用户与系统用户的关系。你确定你在做推送时返回是成功的么？日志里有打印successed的服务器么？

**Comment by buzhiren** [comment]
在授权服务器上推送的系统用户是成功生成了的。

**Comment by wangyunlongg** [comment]
各位大神，登录失败的问题解决了吗

**Comment by wojiushixiaobai** [comment]
已经解决，资产管理-系统用户  更新系统用户，认证方式换成 Password 即可解决。有哪位老哥有luna 的教程吗？？？我这里新版本直接炸了。。。各种报错。。
