### ISSUE TITLE
创建授权成功后，ssh连接跳板机无法连接其他服务器

### ISSUE THREAD

**Issue by buzhiren** [jumpserver/jumpserver#859]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤

1.  问题描述
ssh连接跳板机后，可以显示服务器和用户，但是选择用户后认证失败，
在要登录的服务器查看后，该服务器上创建了推送的系统用户，但是系统用户下没有生成authorized_keys文件。
报错如下：

More than one system user granted, select one
[0] rd
[1] sudo
[2] dev01

System user> 2

Connecting dev01@10.171.98.145:56868 ... 
Connect backend server 10.171.98.145 failed: Auth failed

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
使用密码认证。

**Comment by leon-fans** [comment]
貌似使用密码认证还是报这个错误。

**Comment by wojiushixiaobai** [comment]
@leon-fans  参考https://github.com/jumpserver/jumpserver/issues/858 的回答

修改内容：jumpserver/apps/common/utils.py的第65行，改为return s.loads(value[2:-1])
--

**Comment by ibuler** [comment]
新版本已修复
