### ISSUE TITLE
[Bug] 多个特权用户会重复关联到同一个资产

### ISSUE THREAD

**Issue by daolinzi** [jumpserver/jumpserver#8593]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.2

**浏览器版本**
Google Chrome 版本 103.0.5060.114（正式版本） （32 位）

**Bug 描述**
特权用户1    (A项目_root，root，password1)
特权用户2    (B项目_root，root，password2)

创建资产1时，选择特权用户时，选择特权用户1

实际情况是：多个特权用户都会关联资产 1   

**Bug 重现步骤(有截图更好)**
1. 创建特权用户1和特权用户2 
![image](https://user-images.githubusercontent.com/59077892/178916685-e091727f-0809-49e7-8adf-04e2b7c7a293.png)
![image](https://user-images.githubusercontent.com/59077892/178916746-58a6325c-f967-4c4e-80fa-d72d41aa2a1e.png)

2. 创建资产1
 
![image](https://user-images.githubusercontent.com/59077892/178917039-679c812c-cfba-4fc3-a701-ac08cabb7419.png)

4. 
![image](https://user-images.githubusercontent.com/59077892/178917749-a0278d5d-bc19-445d-bf8f-bf8c7c577578.png)

我创建资产时，只关联了一个特权用户，但查看时，资产的下面居然有3个特权用户。

**Comment by wojiushixiaobai** [comment]
错误的授权导致，检查你的授权
