### ISSUE TITLE
管理员与用户资产列表排序不统一

### ISSUE THREAD

**Issue by Nnaking** [jumpserver/jumpserver#8598]
版本v2.23.3，社区版
管理员的资产列表：
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/33016473/179144197-25109d30-1c81-4615-ab8c-d5f194acd7d4.png">
用户的资产列表：
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/33016473/179144432-248f0689-6359-4e17-b4e0-3a74c5233a94.png">

**Comment by ibuler** [comment]
收到
