### ISSUE TITLE
无法回放历史命令

### ISSUE THREAD

**Issue by csuzhangh** [jumpserver/jumpserver#860]
<img width="914" alt="_20171214131147" src="https://user-images.githubusercontent.com/34495019/33976534-7596a7f2-e0d0-11e7-88f1-49b2ae53aba2.png">
[简述你的问题]

##### 使用版本
0.4.0

##### 问题复现步骤
1. 使用coco连接并执行一些操作，然后断开连接；
2. 在JumpServer界面上，查看审计-Session历史，并点击播放；
3. 没有任何反应

##### 具体表现[截图可能会更好些,最好能截全]
在JumpServer日志中有如下错误，不知有没有什么关系
<img width="914" alt="_20171214131147" src="https://user-images.githubusercontent.com/34495019/33976537-8368683e-e0d0-11e7-9e29-0daf5adf301e.png">

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
0.4.0版本未完成该功能

**Comment by ibuler** [comment]
测试 0.5.0版本
