### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-N_ueht/Django/

### ISSUE THREAD

**Issue by Leon0921** [jumpserver/jumpserver#861]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
Jumpserver版本 0.4.0
##### 问题复现步骤
1. [步骤1]
pip install -r requirements.txt
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34546744/33999091-7263f324-e124-11e7-9947-3e3b232d24b8.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by bigV4** [comment]
![image](https://user-images.githubusercontent.com/8856059/34146904-b69ae902-e4d6-11e7-9ef1-72cf29edd762.png)

**Comment by bigV4** [comment]
![image](https://user-images.githubusercontent.com/8856059/34146969-034f1af2-e4d7-11e7-92ce-189fad9badfb.png)

**Comment by ibuler** [comment]
难道不是  Django==1.11
