### ISSUE TITLE
[Bug] 1.12.1升级至1.23.4升级失败，表结构更新错误。

### ISSUE THREAD

**Issue by LalexH** [jumpserver/jumpserver#8617]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.1

**浏览器版本**
没有用到浏览器

**Bug 描述**
2.12.1升级至2.23.4过程失败

**Bug 重现步骤(有截图更好)**
1.  执行./jmsctl.sh upgrade进行版本升级。
2. 
![Uploading 21658199799_.pic.jpg…]()
![Uploading 31658199820_.pic.jpg…]()

**Comment by wojiushixiaobai** [comment]
图片无法显示

**Comment by jym503558564** [comment]
请重新截图报错日志信息
