### ISSUE TITLE
[Question] 配置CAS后，启动创建用户(如果不存在)

### ISSUE THREAD

**Issue by Pa55w0rd** [jumpserver/jumpserver#8639]
登录过程中，jump没有的账号会报403，这个需要怎么排查

**Comment by wojiushixiaobai** [comment]
确定安全设置 未勾选 仅已存在用户登录
![image](https://user-images.githubusercontent.com/24326988/179954786-04ea65c9-bc8f-49eb-be58-29d77f6d52a3.png)

**Comment by wojiushixiaobai** [comment]
没理解你说的什么意思，你使用 CAS 账号密码登录不就行了？

**Comment by Pa55w0rd** [comment]
> 没理解你说的什么意思，你使用 CAS 账号密码登录不就行了？

配置CAS后，登录入口在cas侧，堡垒机自己的登录入口怎么关闭掉

**Comment by wojiushixiaobai** [comment]
无法关掉

**Comment by Pa55w0rd** [comment]
> 无法关掉

如果不想用户通过这个入口登录，怎么办

**Comment by wojiushixiaobai** [comment]
得修改源码

**Comment by jym503558564** [comment]
感谢反馈，我们后续版本会优化提示信息，请持续关注我们版本发布情况
