### ISSUE TITLE
AttributeError: module 'ldap' has no attribute 'SCOPE_SUBTREE'

### ISSUE THREAD

**Issue by luchuangao** [jumpserver/jumpserver#864]
[简述你的问题]

##### 使用版本
[0.4.0]

##### 问题复现步骤
您好，我执行bash make_migrations.sh 后报AttributeError: module 'ldap' has no attribute 'SCOPE_SUBTREE'错误，请问怎么解决

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/21233112/34199626-58b32dc6-e5a9-11e7-87f6-35b1b4ae10f0.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
请使用0.5测试

**Comment by sogog** [comment]
0.5.0同样的错误

**Comment by deny20080** [comment]
我也遇到同样错误

**Comment by dishuihengxin** [comment]
最新版本也是出现这个错误，请问什么解决？

**Comment by mac-zhou** [comment]
首先查看一下pip安装了哪些ldap包
```pip3 list  |grep ldap```
正确的应该是
```pip3 install pyldap
pip install ldap3```
