### ISSUE TITLE
[Bug] 常登录城市登录后 提示异地登录

### ISSUE THREAD

**Issue by gaohonghai** [jumpserver/jumpserver#8650]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.2

**浏览器版本**
 103.0.5060.114

**Bug 描述**
常登录城市登录后 提示异地登录

**Bug 重现步骤(有截图更好)**
1. 登录后 站内信 该账号异地登录
![image](https://user-images.githubusercontent.com/92966838/180388361-b0a75ab7-4789-45dd-96d5-b1c9a25d9c6d.png)

2.查看账号历史登录记录
![image](https://user-images.githubusercontent.com/92966838/180388438-d7e97e8a-8e8c-4222-b0f0-3ae5313f3d69.png)

**Comment by wojiushixiaobai** [comment]
我们看看，感谢反馈。应该是 ip 库不准

**Comment by jym503558564** [comment]
新版本已修复，请升级到新版本进行测试，如有问题可再次向我们提Issues.
