### ISSUE TITLE
[Question] Jumpserver使用本地用戶登錄沒有登錄日誌

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#8652]
jumpserver版本：2.13.2
問題描述：
在jumpserver建立本地用戶賬戶，登錄時後台jumpserver日誌顯示Authenticate user: None，不顯示具體賬號信息，如圖：
![image](https://user-images.githubusercontent.com/35226938/180679438-3c15ad9b-0cf8-41b9-8818-df52eb26f4d7.png)
![image](https://user-images.githubusercontent.com/35226938/180679462-bd39bbcf-e483-472d-a0ff-7350aba0a5b8.png)

**Comment by jym503558564** [comment]
升级到最新版本测试
