### ISSUE TITLE
[Question] ldap认证无法导入用户组信息

### ISSUE THREAD

**Issue by liangxm-0323** [jumpserver/jumpserver#8653]
**请描述您的问题.**
用户属性映射信息
`{
  "username": "sAMAccountName",
  "name": "displayName",
  "email": "mail",
  "groups": "department"
}`
ldap认证配置后，再用户信息可以看到用户组，导入用户后，无用户组信息

**Comment by jym503558564** [comment]
目前同步用户组，仅支持Windows AD。

**Comment by liangxm-0323** [comment]
我使用的就是windows AD,在用户导入界面可以看到用户组，导入后，在用户列表中无用户组信息

**Comment by liangxm-0323** [comment]
导入前：
![12d8cd65bfa3eee04d335d229ca6720](https://user-images.githubusercontent.com/66943251/180725944-ea4f4927-ed2b-412b-8e72-de22748d1a67.jpg)
导入后
![Uploading db107abbc368a3b48c59ad864d342e6.jpg…]()

**Comment by liangxm-0323** [comment]
导入后
![db107abbc368a3b48c59ad864d342e6](https://user-images.githubusercontent.com/66943251/180726303-8a98c51c-6342-43af-b9df-df83a560c693.jpg)

**Comment by wojiushixiaobai** [comment]
"groups": "department"
填写错误，请更正为默认值

**Comment by jym503558564** [comment]
测试一下属性改为：memberOf
{
  "groups": "memberOf"
}

**Comment by liangxm-0323** [comment]
测试了memberOf会抓取到ou信息。用户组里会显示各个层级的OU，所以选择了抓取department数据

**Comment by rootisnew** [comment]
目前jumpserver导入用户只能支持中文么？我想实现导入为用户的英文名
