### ISSUE TITLE
[Bug] v2.17.0版本升级到v2.24.0版本数据库ip获取错误

### ISSUE THREAD

**Issue by Gerrylinux** [jumpserver/jumpserver#8655]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.0

**浏览器版本**
无

**Bug 描述**
操作升级命令，在更新数据库时，获取的ip为本地ip，数据库是外置ip。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/31839722/180909245-26f054c4-e91e-4fcd-bfd5-271551ca375e.png)
![image](https://user-images.githubusercontent.com/31839722/180909291-10953331-f6f4-4bab-863f-1d70527a0227.png)

1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
检查 jumpserver 用户的授权，授权里面请确认包含 index
如果不确认，请授权 all
```mysql
grant all on jumpserver.* to 'jumpserver'@'%';
flush privileges;
```
