### ISSUE TITLE
[Question] 刪除用戶提示被其它對象關聯，不能刪除

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/jumpserver#8656]
**请描述您的问题.**
Jump版本：2.9.2
刪除用戶時報以下錯誤：
![image](https://user-images.githubusercontent.com/35226938/180918230-06556343-95fe-4c04-8d64-354bda8f2d39.png)

**Comment by wojiushixiaobai** [comment]
禁用 SO Token 认证 后继续操作
