### ISSUE TITLE
[Bug] 安装报错cannot import name 'get_version' from 'django.utils.version'

### ISSUE THREAD

**Issue by michaelsara** [jumpserver/jumpserver#8660]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.0
**Bug 描述**
安装报错cannot import name 'get_version' from 'django.utils.version'

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/25817965/181034813-62d63bfe-dac5-435f-a81d-047a5a8ad194.png)

**Comment by wojiushixiaobai** [comment]
镜像可能有问题，请重新拉取镜像

**Comment by michaelsara** [comment]
> 镜像可能有问题，请重新拉取镜像

重新安装后正常，问题已解决，多谢大佬
