### ISSUE TITLE
edge浏览器登录，标签休眠就会登出[Bug] 

### ISSUE THREAD

**Issue by sevenclockseven** [jumpserver/jumpserver#8661]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.0 GPLv3

**浏览器版本**
Microsoft Edge
版本 103.0.1264.71 (正式版本) (64 位)

**Bug 描述**
使用浏览器登录，edge浏览器标签页会自动休眠，休眠后jumpserver就会登出，jumpserver配置的浏览器重启需要重新登录，之前版本都没有这个问题

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
关闭浏览器休眠

**Comment by sevenclockseven** [comment]
@wojiushixiaobai 之前版本并没有这个问题，我现在用的版本就是这么设计的吗？

**Comment by sevenclockseven** [comment]
@wojiushixiaobai 把浏览器标签休眠关了，jumpserver浏览器登录，半个小时无操作还是会登出

**Comment by smallodd** [comment]
我这边使用也出现类似的问题。且登陆的时候不能设置一天内自动登录

**Comment by sevenclockseven** [comment]
> 关闭浏览器休眠

把浏览器标签休眠关了，jumpserver浏览器登录，半个小时无操作还是会登出，另外空闲连接时间配置的30分钟，实际上10分钟左右就会自动关闭

**Comment by wojiushixiaobai** [comment]
@sevenclockseven 
检查配置文件
- /opt/jumpserver/config/config.txt
```
... 省略
#  请禁用 SESSION_COOKIE_AGE 的设置，并开启 SESSION_EXPIRE_AT_BROWSER_CLOSE

# SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间
SESSION_EXPIRE_AT_BROWSER_CLOSE=True  # 关闭浏览器失效登录的 session
```

@smallodd 
检查配置文件
- /opt/jumpserver/config/config.txt
```
... 省略
#  请禁用 SESSION_EXPIRE_AT_BROWSER_CLOSE 的设置，并开启 SESSION_COOKIE_AGE

SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间，单位（秒）
# SESSION_EXPIRE_AT_BROWSER_CLOSE=False  # 关闭浏览器失效登录的 session
```

**Comment by smallodd** [comment]
![image](https://user-images.githubusercontent.com/13759794/181466623-e9988c1c-5c6f-493d-94e6-0f941d3e7222.png)
看了下是这样的 ，需要我改成如下配置嘛？如果是 是不是每次升级以后都需要改一下这里呢
SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间，单位（秒）
# SESSION_EXPIRE_AT_BROWSER_CLOSE=False  # 关闭浏览器失效登录的 session

**Comment by wojiushixiaobai** [comment]
@smallodd 不需要。这是你以前修改了配置，升级不会变更此内容

**Comment by sevenclockseven** [comment]
> @smallodd 不需要。这是你以前修改了配置，升级不会变更此内容



> @sevenclockseven 检查配置文件
> 
> * /opt/jumpserver/config/config.txt
> 
> ```
> ... 省略
> #  请禁用 SESSION_COOKIE_AGE 的设置，并开启 SESSION_EXPIRE_AT_BROWSER_CLOSE
> 
> # SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间
> SESSION_EXPIRE_AT_BROWSER_CLOSE=True  # 关闭浏览器失效登录的 session
> ```
> 
> @smallodd 检查配置文件
> 
> * /opt/jumpserver/config/config.txt
> 
> ```
> ... 省略
> #  请禁用 SESSION_EXPIRE_AT_BROWSER_CLOSE 的设置，并开启 SESSION_COOKIE_AGE
> 
> SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间，单位（秒）
> # SESSION_EXPIRE_AT_BROWSER_CLOSE=False  # 关闭浏览器失效登录的 session
> ```

@wojiushixiaobai 之前就是设置的有效期，后来我就想不要有效期，就想要浏览器关闭session失效，才启用关闭浏览器失效的配置，之前的版本都没有问题，还是说以后版本都跟v2.24.0一样了

**Comment by sevenclockseven** [comment]
> @sevenclockseven 检查配置文件
> 
> * /opt/jumpserver/config/config.txt
> 
> ```
> ... 省略
> #  请禁用 SESSION_COOKIE_AGE 的设置，并开启 SESSION_EXPIRE_AT_BROWSER_CLOSE
> 
> # SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间
> SESSION_EXPIRE_AT_BROWSER_CLOSE=True  # 关闭浏览器失效登录的 session
> ```
> 
> @smallodd 检查配置文件
> 
> * /opt/jumpserver/config/config.txt
> 
> ```
> ... 省略
> #  请禁用 SESSION_EXPIRE_AT_BROWSER_CLOSE 的设置，并开启 SESSION_COOKIE_AGE
> 
> SESSION_COOKIE_AGE=86400     # session 有效期  默认界面用户不需要密码自动化登录时间，单位（秒）
> # SESSION_EXPIRE_AT_BROWSER_CLOSE=False  # 关闭浏览器失效登录的 session
> ```

@wojiushixiaobai 之前就是设置的有效期，后来我就想不要有效期，就想要浏览器关闭session失效，才启用关闭浏览器失效的配置，之前的版本都没有问题，还是说以后版本都跟v2.24.0一样了

**Comment by wojiushixiaobai** [comment]
@sevenclockseven 配置 `SESSION_EXPIRE_AT_BROWSER_CLOSE=True` 后，页面可以勾选，但是实际是无效的设置。
算是以前的 bug，新版本我们修复了。

后期我们可能会对开启了 `SESSION_EXPIRE_AT_BROWSER_CLOSE` 参数的用户不显示此按钮。

**Comment by smallodd** [comment]
> @smallodd 不需要。这是你以前修改了配置，升级不会变更此内容

讲真 我之前一直默认来着，根本不知道有这个设置
