### ISSUE TITLE
[Feature] 公告内容追加显示

### ISSUE THREAD

**Issue by heatdrive** [jumpserver/jumpserver#8673]
**请描述您的需求或者改进建议.**
1、通过ssh工具类登录JumpServer时，在选择界面上显示公告内容。
2、Web页面公告内容支持修改字体大小。

**Comment by ibuler** [comment]
1. ssh 界面显示，不好设计，感觉也影响美观
2. 不支持太多自定义，只支持一种标准设计，你可以修改一下字体大小，发过来我们看看是不是更美观了
