### ISSUE TITLE
[Bug] 连接Windows资产卡顿

### ISSUE THREAD

**Issue by fattan9577** [jumpserver/jumpserver#8674]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.0

**浏览器版本**
chrome  103.0.5060.134

**Bug 描述**
通过Web 访问Windows资产时，一旦资产播放视频，就会非常卡顿，甚至断连。
若用户资产有使用动态桌面，同理，非常卡顿

**Bug 重现步骤(有截图更好)**
卡顿无法截图，如描述所述。v2.23.2同样有这个问题
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
当前 lion 组件使用了 apache guacamole-server 代理，目前存在此问题，需要等待 apache 官方优化
