### ISSUE TITLE
请问如何配置超时断开jumpserver的用户的ssh登录，而非资产ssh超时断开

### ISSUE THREAD

**Issue by outsrkem** [jumpserver/jumpserver#8675]
**请问如何配置超时断开jumpserver的用户的ssh登录，而非资产ssh超时断开.**
![7f19652d89d158258496a25e33a6743](https://user-images.githubusercontent.com/56825316/181925311-07de7b8c-e0d8-4897-a1af-e767aab63bb2.png)

**Comment by wojiushixiaobai** [comment]
最新版本的话，试试设置里面的 最大空闲 时间

**Comment by dowliu** [comment]
在2.14.0引入最大空闲参数后，无论如何设置，都会在超过60min后断开用户会话，设置了其他值（比如240min）也不行，请确认一下这个是否是个bug呢，升级到2.14.1之后问题仍然存在。在数据库里面，能够看到该值已经进行了修改。

**Comment by dowliu** [comment]
> 最新版本的话，试试设置里面的 `最大空闲` 时间

在2.14.0引入最大空闲参数后，无论如何设置，都会在超过60min后断开用户会话，设置了其他值（比如240min）也不行，请确认一下这个是否是个bug呢，升级到2.14.1之后问题仍然存在。在数据库里面，能够看到该值已经进行了修改。

**Comment by LeeEirc** [comment]
> 在2.24.0引入最大空闲参数后，无论如何设置，都会在超过60min后断开用户会话，设置了其他值（比如240min）也不行，请确认一下这个是否是个bug呢，升级到2.24.1之后问题仍然存在。在数据库里面，能够看到该值已经进行了修改。

截图看看你的设置。设置之后，koko同步配置大概需要一分钟左右。仅对新的登陆连接生效。

**Comment by dowliu** [comment]
> > 在2.24.0引入最大空闲参数后，无论如何设置，都会在超过60min后断开用户会话，设置了其他值（比如240min）也不行，请确认一下这个是否是个bug呢，升级到2.24.1之后问题仍然存在。在数据库里面，能够看到该值已经进行了修改。
> 
> 截图看看你的设置。设置之后，koko同步配置大概需要一分钟左右。仅对新的登陆连接生效。

详情请移步issue:[[#8731](https://github.com/jumpserver/jumpserver/issues/8731)]
