### ISSUE TITLE
能否新增个人信息中ssh公钥设置中的公钥由管理员开启生成的密钥有密码 

### ISSUE THREAD

**Issue by outsrkem** [jumpserver/jumpserver#8677]
**能否新增个人信息中ssh公钥设置中的公钥由管理员开启生成的密钥有密码 .**
**用户重置密钥时，生成密钥密码，用户可获取 .**
**管理员可配置是否强制启用，或者选择新启用.**
![image](https://user-images.githubusercontent.com/56825316/181930262-8cd65958-b2f2-4642-a3c2-3b95ba3267e8.png)

**Comment by ibuler** [comment]
暂时没有计划，等需求多了再考虑
