### ISSUE TITLE
能否新增ssh客户端登陆时的认证类型可选择开启

### ISSUE THREAD

**Issue by outsrkem** [jumpserver/jumpserver#8678]
**能否新增ssh客户端登陆时的认证类型可选择开启.**
**1、管理员配置密码或者ssh公钥均可登陆ssh**
**1、管理员配置只能密钥登陆或者密码登陆ssh**
![image](https://user-images.githubusercontent.com/56825316/181933378-d5076a4c-c655-4b52-a265-345db2304e6f.png)

**Comment by LeeEirc** [comment]
理论上可行，已记录需求，等后续排期。

**Comment by LeeEirc** [comment]
目前如果仅仅想禁止 password 等认证，可以在终端设置里限制。

![image](https://user-images.githubusercontent.com/32626707/182092562-7fdd700f-6780-45e0-95d0-ff26e8ca35cd.png)

但要达到对认证类型的颗粒度控制，就需要重启 Koko，这就不够灵活，且与上述的设置会产生理解冲突。不适合在产品上做这样的控制。
