### ISSUE TITLE
[Question]Windows 输入法近端，远端不同步导致的选字框无法显示问题

### ISSUE THREAD

**Issue by phphy** [jumpserver/jumpserver#8679]
连接到远端，ctrl + shift 切换输入法，不能传递到远端，只在近端生效，本地中文输入法，远端还是英文，或者本地中文，远端中文，就看不到选字框，有没有解决方案？键盘的切换是否可以根据焦点进行判断，盼复。

**Comment by ibuler** [comment]
这个应该是所有远程工具都会遇到的问题，teamview 向日葵 我也经常遇到，目前没有好的办法

**Comment by phphy** [comment]
谢谢您的回复，我是非开发人员，我在想，如果我的鼠标焦点停留在rdp远程桌面上，那系统可不可以认为我此时按的ctrl + shift 按键是要作用于远端的，同时本地端输入法置为默认英文小写输入法，这样描述是不是清晰。

**Comment by wojiushixiaobai** [comment]
不可以，系统会优先响应

**Comment by phphy** [comment]
OK，谢谢
