### ISSUE TITLE
 【docker建议】docker-compose文件最好将数据库的数据文件外挂出来，不然重新创建数据会丢的

### ISSUE THREAD

**Issue by topicgit** [jumpserver/jumpserver#868]
[简述你的问题]

##### 使用版本
 0.4.0

##### 问题复现步骤
docker-compose down

##### 具体表现[截图可能会更好些,最好能截全]
所有数据会丢失

##### 其他
 例如这样配置：
![image](https://user-images.githubusercontent.com/11975460/34254890-1c746678-e689-11e7-976e-fce7441f5a34.png)

[注:] 完成后请关闭 issue

**Comment by znavy** [comment]
默认已经数据持久化了。
也可以这样定义：
volumes:
      - /app/data/jumpserver/data:/opt/jumpserver/data
      - /app/data/jumpserver/logs:/opt/jumpserver/logs

**Comment by topicgit** [comment]
你这个可能是Dockerfile，我说的那个是docker-compose文件。

**Comment by znavy** [comment]
就把这段加入到你的compose文件

**Comment by topicgit** [comment]
多谢

**Comment by topicgit** [comment]
--
