### ISSUE TITLE
[Question] 使用 jumpserver clients 服务端

### ISSUE THREAD

**Issue by JarboU** [jumpserver/jumpserver#8680]
**请描述您的问题.**
jumpserver clients 正常安装，也能正常吊起 jumpserver clients 应用。但是连接报错 Connection refused。
使用 docker 部署 jumpserver v2.24.0 。放通端口 80,22,33060,33061；
请问还需要放通什么端口？
![image](https://user-images.githubusercontent.com/30835219/182063356-1159da49-c50a-42be-8818-ebe18d820d8c.png)

**Comment by wojiushixiaobai** [comment]
这个看起来是网络问题，看看是不是本地到堡垒机的端口未开放

**Comment by JarboU** [comment]
我就是想知道这个端口是多少，因为是用  docker 部署得~

**Comment by wojiushixiaobai** [comment]
默认是 2222

**Comment by JarboU** [comment]
2222 端口我放通了的，貌似还不行。感谢答复~

**Comment by JarboU** [comment]
知道问题了，确实是 2222 端口。我映射出来的不是 2222 端口，所以才报了这个错。感谢
