### ISSUE TITLE
[Feature] Web终端增加节点上右击连接该节点下所有资产功能

### ISSUE THREAD

**Issue by samgang** [jumpserver/jumpserver#8681]
**请描述您的需求或者改进建议.**
在 `Version v2.24.0` 的 Web 终端里无法对节点进行操作，希望在未来的版本中增加右击节点可以连接该节点下所有资产功能。如图所示
![功能图](https://s1.328888.xyz/2022/08/02/OLZqp.png)

**Comment by jym503558564** [comment]
点击节点连接所有资产，这个功能似乎只方便，该节点下所有资产都只授权单一的系统用户。
对于用户其他使用场景，如资产分别有多系统用户呢？此时点击节点，需要不同系统用户连接该节点下的资产。
对于其他场景似乎不是很方便。

**Comment by samgang** [comment]
很感谢你的回复。我认为这是一个很微小但对部分用户会有好处的功能。
1. 资产需要进行分类（分节点）管理。如果资产没有进行分类，直接在总节点上进行连接，造成连接所有，应该是有问题的。
2. 资产有多用户，如果使用此功能是否应该弹窗进行二次确认呢？
3. 如果觉得有风险，那么是否可以增加设置选项，就像批量命令执行，由各使用者的管理员来确定是否开启。

**Comment by jym503558564** [comment]
目前我们团队研发人员计划将系统用户和资产账号进行分离：https://github.com/jumpserver/jumpserver/issues/8560。
届时我们再反馈一下开发人员，进行评估您这个需求的可行性。后续如有计划，将会在未来版本进行发布。感谢～
