### ISSUE TITLE
[Bug] 无法开启jumpserver页面不需要重新登录的功能

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#8690]
**JumpServer 版本(v1.5.9以下不再支持)**
2.24.0

**浏览器版本**

**Bug 描述**
无法开启jumpserver页面不需要重新登录的功能
将SESSION_EXPIRE_AT_BROWSER_CLOSE=true参数删除只保留SESSION_COOKIE_AGE=3600，重启jms还是无法实现关闭页面不需要重新登陆的功能

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/44529247/182336438-e8c29e0e-559d-487e-9457-7cf7ae4d8ebf.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
需要浏览器的支持，比如关闭浏览器后允许后台运行的选项

**Comment by NagaResst** [comment]
我也遇到这个问题了。ldap登录，无法启用1天自动登录的功能。而且经常用着用着，会话就断了，一直在用的web终端却无法打开新的设备，需要重新登录。

**Comment by jym503558564** [comment]
v2.24.2已经修复，可升级至最新版本进行测试
