### ISSUE TITLE
Unable to access the assets using SSH 

### ISSUE THREAD

**Issue by argadepp** [jumpserver/jumpserver#8692]
Hi , 

Have implemented the Jumpserver using the One Click installer and all services are running , have configured user , asset , permissions but unable to access the server getting error as 

Please help on same and share the solution 

![image](https://user-images.githubusercontent.com/90461882/182366349-dd4dca57-b175-4d0f-8926-0a7e5b466f0f.png)
![error](https://user-images.githubusercontent.com/90461882/182372004-1ada6931-7e57-4660-9f6a-49c0a666a9a9.PNG)
![koko error](https://user-images.githubusercontent.com/90461882/182372010-0efd2e65-94e5-4edb-9d44-2f011ac825f3.PNG)

**Comment by wojiushixiaobai** [comment]
Reverse proxy needs to configure websocket to work properly.
```text
websocker upgrade err: websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade' header
```
```bash
vi /etc/nginx/conf.d/jumpserver.conf
```
```vim
server {

    listen 80;
    server_name demo.jumpserver.org;  # your domain name

    client_max_body_size 4096m;  # upload file max size

    location / {
            # your jumpserver host
            proxy_pass http://192.168.244.144;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```
