### ISSUE TITLE
在安卓设备上通过堡垒机播放视频，明显卡顿掉帧

### ISSUE THREAD

**Issue by henry59687** [jumpserver/jumpserver#8693]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
Chrome

**Bug 描述**
在安卓设备上通过堡垒机播放视频，明显卡顿掉帧

**Bug 重现步骤(有截图更好)**
1.  打开安卓的chrome
2.  链接登录堡垒机地址
3.  进入我的资产
4.  打开堡垒机的chrome
5.  输入地址如bilibili.com 并访问
6.  点击任意视频
7.  卡顿

**Comment by wojiushixiaobai** [comment]
目前的性能只能这样，如果需要流畅的使用各种功能推荐使用支持 vgpu 加速的云桌面或者我们的企业组件 razor，可以享受原生的速度体验
