### ISSUE TITLE
[ERROR] Failed to change the table structure!

### ISSUE THREAD

**Issue by gzwxh** [jumpserver/jumpserver#8694]
**JumpServer 版本(v1.5.9以下不再支持)**
从JumpServer 2.23.4 版本无法进行更到2.24.0

**浏览器版本**
无

**Bug 描述**
在根据以往的更新方式，
[root@gzwxhcn jumpserver-installer-v2.23.4]# ./jmsctl.sh upgrade
执行之后，报错以下信息
django.db.utils.OperationalError: (1050, "Table 'assets_commandfilter_applications' already exists")
[ERROR] Failed to change the table structure!

**Bug 重现步骤(有截图更好)**

说明：
数据库使用外置数据库，MySQL5.7
Redis也是外置的。
通过之后安装2.24.0版本的JumpServer ，查看数据库是有132表，之前的2.23.4 数据库是106。其中对比users_user 这个表中多了一个字段，且该字段不能为空    is_service_account
老数据中是否在更新的时候有相关的操作

**Comment by jym503558564** [comment]
是社区版本吗？安装升级请先参考文档：https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

**Comment by 1-step** [comment]
mark it, 我也遇到了同样的问题，V3.1.2升级到V3.2.0出现了上面的问题，有解决方案吗？
