### ISSUE TITLE
[Bug] 执行批量命令或者测试连接，一直是    ......    状态。

### ISSUE THREAD

**Issue by liang2025** [jumpserver/jumpserver#8695]
**JumpServer 版本(v1.5.9以下不再支持)**   2.22.0

**浏览器版本**    版本 103.0.5060.134（正式版本） （64 位）

**Bug 描述**   执行批量命令或者测试连接，一直是    ......    状态。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/58716359/182559435-867f269b-7b2a-4bd0-af19-7b51a86b4ba5.png)

2. 
3.

**Comment by liang2025** [comment]
![image](https://user-images.githubusercontent.com/58716359/182559799-445f3b10-6037-46a1-a0ef-6b1b1515391e.png)
web终端没问题，上午都用了没问题，下午有一个批量命令执行没通过，一真是   ... ... 的状态，后面就这样了，不管怎么操作都是这种等待的状态

**Comment by wojiushixiaobai** [comment]
重启下 jumpserver 就行
```
jmsctl restart
```
