### ISSUE TITLE
Azure PaaS数据库用户统一管理[Feature] 

### ISSUE THREAD

**Issue by 15326047083** [jumpserver/jumpserver#8696]
**请描述您的需求或者改进建议.**
由于Azure PaaS MYSQL数据库特殊性，其账号包含后缀，如：bastion_all@acc-v2-database，bastion_rw@prd-database
所以无法在系统用户中使用同一用户进行管理，导致如果我有n个mysql paas，就需要创建n*m个系统用户，且应用授权面临同样的问题。
所以希望可以出一个解决方案用于解决系统用户的后缀问题。
非常感谢。
![微信截图_20220803183551](https://user-images.githubusercontent.com/31504898/182588113-34b8d823-8349-46eb-82a8-45257c342d34.png)

**Comment by wojiushixiaobai** [comment]
- #8560
