### ISSUE TITLE
请问SFTP连接后能显示隐藏文件吗？

### ISSUE THREAD

**Issue by strongDong** [jumpserver/jumpserver#8697]
使用winscp连接jumpserver sftp后不显示隐藏文件，如图
![image](https://user-images.githubusercontent.com/16399186/182590744-6d77ab96-b488-4960-a42b-d19ec0b1afc0.png)

直连服务器时是显示的，如下图中的 .env 文件：
![image](https://user-images.githubusercontent.com/16399186/182591013-2ffb1358-8e5e-410e-8488-49567a201025.png)

设置中已经打开了显示隐藏文件选项
![image](https://user-images.githubusercontent.com/16399186/182591118-47e23539-a4d2-4e78-8e72-5701f8e7ce7e.png)

是还需要配置哪里吗？还是目录暂时不支持显示隐藏文件呢？

**Comment by jym503558564** [comment]
修改配置文件：
```
vim /opt/jumpserver/config/config.txt
SFTP_SHOW_HIDDEN_FILE=true
```
然后重启服务，在进行测试

**Comment by strongDong** [comment]
> 修改配置文件：
> 
> ```
> vim /opt/jumpserver/config/config.txt
> SFTP_SHOW_HIDDEN_FILE=true
> ```
> 
> 然后重新启动服务，在进行测试

按您说的配置了，依然没有生效
我是docker启动的，默认没有/opt/jumpserver/config/目录和config.txt文件，然后我再core和celery服务分别挂载了/opt/jumpserver/config目录，并在宿主机持久化的config目录中创建了config.txt文件。
![image](https://user-images.githubusercontent.com/16399186/182989075-a15d124f-783b-43b0-9253-1982780f52fb.png)


core容器内的文件如下：
![image](https://user-images.githubusercontent.com/16399186/182988393-cd25ae10-bf1d-4713-9841-c287bf835fb8.png)

配置完后全部docker-compose down重新up -d启动的，是我哪里配置错了？
docker启动是不是有更优雅、方便的配置方法？

**Comment by strongDong** [comment]
问题已解决。
由于我是使用的 https://github.com/jumpserver/Dockerfile/ 项目中的docker-compose启动的没有config.txt文件，只需要在koko上添加环境变量 SFTP_SHOW_HIDDEN_FILE=true 并重建koko镜像即可。

![image](https://user-images.githubusercontent.com/16399186/183056791-2b92342f-475a-451b-b9b6-9d5b48c79988.png)

再次感谢！
