### ISSUE TITLE
[Feature] clients 拉起客户端支持

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#8700]
**请描述您的需求或者改进建议.**
当前clients拉起ssh协议只支持putty客户端，能否添加更多选择，比如Xshell、CRT等ssh客户端。

**Comment by leim** [comment]
可以这样做：

1、组装一个json：

```
{"protocol": "mysql", "username": "admin", "command": "cmd"}
```

protocol固定是mysql，username随便，command里面就是你要执行的命令，任意命令都可以。

2、将上面的json转为base64：

```
eyJwcm90b2NvbCI6ICJteXNxbCIsICJ1c2VybmFtZSI6ICJhZG1pbiIsICJjb21tYW5kIjogImNtZCJ9
```

3、将base64的值前面加上协议：

```
jms://eyJwcm90b2NvbCI6ICJteXNxbCIsICJ1c2VybmFtZSI6ICJhZG1pbiIsICJjb21tYW5kIjogImNtZCJ9
```

4、浏览器跳转上面得到的地址即可：

```
location.href = "jms://eyJwcm90b2NvbCI6ICJteXNxbCIsICJ1c2VybmFtZSI6ICJhZG1pbiIsICJjb21tYW5kIjogImNtZCJ9"
```

按照上面的方法，可以执行任意命令，也可以在自己的网页里面，利用jumpclient，执行任何自己想要执行的命令。

**Comment by ibuler** [comment]
Xshell、CRT 不支持 使用命令直接连接，可能需要新建连接，才能使用，比较麻烦
