### ISSUE TITLE
[Feature] 当使用用户映射对接openid后，用户名不能与多用户对应。

### ISSUE THREAD

**Issue by liuyongqing1** [jumpserver/jumpserver#8702]
**请描述您的需求或者改进建议.**
当jumpserver使用用户映射适配openid后，想使用动态用户登陆的时，发现openid返回的用户结构不满足linux用户要求:
例如返回的name字段为  si Li
                  email字段为   sili@jumpserver.com
 这两种格式无法对应linux用户名。name带有空格。email带有@等特殊字符。能不能实现使用email @前缀部分作为用户名 sili 这样的用户名。

可以提供这样的功能不。

**Comment by ibuler** [comment]
新版本支持了映射关系更改，可以指定映射了

![image](https://user-images.githubusercontent.com/17382885/183323671-4a2a54cb-8b3f-466f-9447-c74327c43ab9.png)

**Comment by liuyongqing1** [comment]
我使用的就是新版本，也使用了这个功能，我的意思是当使用了这个功能后，再使用动态用户去登陆资产的功能时，有个问题存在。
就是name preferred_username和email 三个字段的信息都不在在linux上创建用户。
name和preferred_username 名称带有空格。email带有@特殊字符，linux不支持这样的用户名。

所以想问问能不能提供比如切割email字段，前缀为用户名的方法或是功能。比如email 为sili@abc.com   那sili为用户名。


如果不能实现 能否提供个手动改代码的方案

**Comment by jym503558564** [comment]
preferred_username 都带空格？

**Comment by liuyongqing1** [comment]
{
  "iss": "https://xxxx.xxxx.cn/dex",
  "sub": "CiQy6565656565656565TcwZDYSCW1pY3Jvc29mdA",
  "aud": "auth",
  "exp": 1660103113,
  "iat": 1660016713,
  "nonce": "console",
  "at_hash": "56565650bQb9Zo1URfqw",
  "email": "lisi@test.io",
  "email_verified": true,
  "groups": [
    "All employees"
  ],
  "name": "si Li",
  "ext": {
    "is_admin": false,
    "conn_id": "microsoft"
  }
}


实际返回结果 是这样的

**Comment by wojiushixiaobai** [comment]
建议在 openid 新增 user 字段，添加对应的 username。
如果条件不允许，直接修改 core 的代码
```bash
https://github.com/jumpserver/jumpserver/blob/master/apps/authentication/backends/oidc/backends.py#L290
```
