### ISSUE TITLE
Console view for group

### ISSUE THREAD

**Issue by adis3421** [jumpserver/jumpserver#8703]
Hi,

I would like do Console View for group, actualy when I add role to consol view user are seeing all asset. I would like that seeing only group a, b or c and administer only your group not all. In my enviroment this option is unacceptable. Mayby you have resolv this problem? 
My version is 2.23.2.

Regards,
AN

**Comment by LeeEirc** [comment]
No, you could't. I think you may want use Enterprise edition, which could create different organizations.
