### ISSUE TITLE
[建议] v3.0 重构计划 

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#8711]
JumpServer v3 计划启动，自 2020年6月 发布 v2 以来，每个月发布一个版本，共迭代了 24 个版本。期间收到了不少反馈，我们也反省了一些设计，的确存在一些难以理解的问题，所以我们计划做 v3.0 了。

## v3 计划的一些原则
1. 设计比较复杂的，重构了
2. 设计比较难以理解的，重构了
3. 之前考虑做但是因为兼容问题没做的，做了
4. 其它的不做

## 优化项
我们对一些功能做了优化设想，目前总结有以下:

- 系统用户重构为账号，放弃系统用户中间层
- 资产和应用合并，复杂的项放到平台上
- 资产平台重构，承载更多功能
- RemoteApp 重构
- Installer 中使用 MariaDB 替代 MySQL

## 一、系统用户重构为账号，放弃系统用户中间层
从 **JumpServer** 初始，我们就确立了 **用户**、**资产**、**系统用户** 的三种核心实体，前两种是必须的，而 **系统用户** 是我们设计一个类似账号的 **中间层**，目的是不用在资产上 **繁琐的** 一个个添加账号， 并且赋予了授权**自动创建**账号并且**自动推送**的功能。这个在资产规模比较小，账号密码相同比较多的时候，非常简便，但是在资产众多，并且等保要求资产密码都不一样时，却有了非常大的困扰，正如 [#8550 系统用户和账号分离](https://github.com/jumpserver/jumpserver/issues/8560) 中描述，问题变的比较复杂。

所以我们打算放弃系统用户设计，回归到原始的账号上来，添加资产时添加上资产上有的账号(也可以建好账号模版，自动创建一些账号)。这种设计的好处是，自动化的内容放到外层，不因自动化设计(或者其它设计)让架构变的复杂，我们在写代码是就采用的这种策略，聚焦主流程，其它的放到扩展中。

系统用户除了账号功能外，还有 命令过滤、SFTP 目录，命令过滤放到 ACL 中， SFTP 目录放到资产的平台上。

系统用户对账号也有一些延伸，如 **同名账号**（和当前登录用户名称相同）、**手动账号**，也得妥善处理，
同名账号可能是手动的，可能是托管密码的，手动的就是帮助填写用户名(或者锁定用户名)，托管的就是选择同名账号登录

我们的授权系统也得跟着做更改，把原来的 系统用户，改为 账号的名称。我们为此也需要创建一些虚拟账号，来处理上述的 同名账号 和 手动账号

### 虚拟账号

- 手动账号 @input
- 同名账号 @user
- 所有账号 @all

### 账号模版
重构系统用户为账号后，我们之前做的 自动创建账号，自动推送账号到资产上就需要使用账号模版来完成。初步的想法是，创建资产的时可以选择账号模版，然后根据账号模版创建完资产，自动根据模版上的用户名密码创建账号。

当然我们也可以设计根据信号类自动应用模版，比如 创建 windows 类型时自动应用模版，授权资产时自动应用模版到资产。

模版上根据协议定义了需要的属性，用户名、密码 等。

## 二、资产和应用合并，复杂的项放到平台上

起初 JumpServer 中只有资产，后来为了支持 数据库，我们新增了应用，因为每种应用可能都有单独的一些字段，所以我们不得不新增了 Application 表，这导致现在很多关系会和资产一样存在两份，如 授权表、系统用户关系表、命令过滤表，提供的 api 也都是双份的。另外也有一些用户反馈，也希望应用支持放到资产树上。

所以我们打算合并 **资产和应用**，强化 **资产平台** 方面的职责，抽象出通用资产字段放入 assets_asset 表中，按照类别分为 **主机、网络设备、数据库、云、Web** 等。分类别的依据是 字段属性 是否大致相同，如果和以往不同则需要考虑区分。

需要说明的是原来 RemoteApp 是个特殊的存在，它本身其实只是连接方式不同，并不是一种真实的类别，所以我们删掉了 远程应用，而是 融入到其他类别中，如 数据库、web，不再有单独分类。

每种类别下也可以对应不同的资产类型，当然我们也没有必要穷举每个类别下的所有类型。

#### 内置的类型：

| 主机  | 网络设备 | 数据库 | 容器 | Web | 其它 
| --- | --- | --- | --- | --- | --- |  
| Linux | 交换机 | MySQL | Kubernetes | 网站 |  
| Windows | 路由器 | PostgreSQL |  | 邮箱  | 
| Unix | 存储设备 | Oracle |  |  |  |
| MacOS |  | SQLServer |  |  |  |
| BSD |  | MongoDB |  |  |  |
| 大型机 |  | Redis |  |  |  |

**注**: Web 下的分类没有想好，因为之前 Remote App 下是支持 chrome 打开的网站的。容器之前叫 云，也没有想好类别名称，来承纳更多类型

## 三、资产平台重构

平台的作用是基于以上类型划分后，更细致灵活的区分，可以用作针对 操作系统的区分
、版本的区分、编码的区分 等。平台中有 类别、类型 属性，属于小分类。

- Linux 中可以分 CentOS，Ubuntu 平台做标记
- MySQL 中区分 MySQL5 和 MySQL8，他们的认证方式可能有区别
- Unix 中的 AIX, Solaris 

区分类型后，我们也可以做以下事情：

- 灵活定义探活方式
- 灵活定义改密方式
- 灵活定义账号推送
- 灵活定义su切换方式(enable、还是 su)
- 为资产创建设置初始值 (作为资产模版功能)

**思考：** MySQL 的版本号 5, 8 需要放到资产数据库表的字段中吗? 还是放到平台中？不同类型数据库的版本可能还不一样呢？

**回答：** 数据库要预留版本这个字段，因为这个字段对于连接数据库来说，尤其是直连方式有着强依赖关系，所以对于数据库来说，这个字段是必须的了，可以新建 两个平台，MySQL5 和 MySQL8 将版本进行默认。

#### 资产多协议还是单协议
起始 JumpServer 中的资产是单个协议的，后来因为账号改密(自动推送账号)，Windows 需要支持 ssh，才能使用 ansible，所以我们支持了 多协议。但用起来的确不太方面，并且除了主机资产，通常别的可能只有一个协议，比如 DB，或者不用协议 比如 Web (虽然是 http 协议，通常地址中就携带了，没有必要再分开写吧，端口也大多是默认的)。

- Windows 安装 openssh 支持 ssh；安装 vnc 支持 vnc
- Linux 安装 xrdp 支持 rdp，安装 vnc 支持 vnc，还有 telnet

现实中可能概率比较小，再添加一个资产通常能解决。但是两个问题不太好处理：

1. 改密需要额外的支持，比如 windows 需要 ssh
2. 新建成为两个资产后，改密后账号密码如何同步

问题1，可以在 **平台** 上下功夫，因为对于公司来说大部分端口应该是一致的，允许平台来设置 ssh 端口，但是略显生硬，为赋新词强说愁

问题2，一个资产改为两个资产后，如果想账号同步的话，需要设计一个绑定机制，说明他们是同一个资产，账号可能是一样的，改了一个后需要同步更新另一个。

问题变的又比较复杂了，或许支持多协议可能更容易描述真实的资产。

#### 设置项的位置
用户连接到资产，可能某种资产或者某个协议有一些特殊的表现，具体应该在哪去配置呢

1. 平台上配置 大多数类型的资产都可能遇到的，配置到平台上
2. 资产上配置 各资产大概率不相同的放到资产上
3. 账号上配置 和认证有关的在账号上
4. 连接时配置 两次连接同一资产，同一账号可能不同时在连接时

#### 资产账号多协议，单协议、还是没协议
当资产支持了多个协议，新建账号时自然也要对应协议，因为有协议才能确定字段，比如 ssh 支持 private key，rdp 需要 domain。

单协议
--- 

| ID | 用户名 | 协议 | 密码 | 资产 |
| --- | --- | --- | --- | --- | 
| 1 | root | ssh | xxx | A |
| 2 | administrator | rdp | xxx | B |
| 3 | administrator | ssh | xxx | B |

单协议对于账号是最直白的，最清楚的，允许 同名账号 密码不同，这也为改密带来了问题，2、3 本质上是同一个账号，改密后需要同步更改，也得做账号捆绑，为了弥补我们试试多协议

多协议
---
| ID | 用户名 | 协议 | 密码 | 资产 |
| --- | --- | --- | --- | --- | 
| 1 | root | ssh | xxx | A |
| 2 | administrator | ssh+rdp | xxx | B |
| 3 | administrator | vnc | xxx | B |
| ~~4~~ | ~~administrator~~ | ~~ssh~~ | ~~xxx~~ | ~~B~~ |

多协议应该能解决上面的问题，也能很好的描述账号本身，也能一个资产，同账号名，不同协议不同密码。

但是 用户名、协议、资产 构成的唯一约束就比较麻烦了，添加 4 的时候，得去判断 2，无法在数据库层面完成约束，需要业务支持。

无协议
---
| ID | 用户名 | 协议 | 密码 | 资产 |
| --- | --- | --- | --- | --- | 
| 2 | administrator |  | xxx | B |
| 3 | administrator | ssh+rdp+vnc+telnet | xxx | B |

其实相当于多协议-资产上支持的所有协议。这种在于新建账号时，要把资产支持的所有协议需要的字段都列出来

综上所述，无协议可能比较适中一些

## 四、Remote App 重构
原来的 Remote App 是作为一种应用类别存在的，每个远程应用需要配置一个依赖的 RDP 资产，在这个资产上安装对应用，然后有托管程序拉起。这种使用方式比较基础，不易与扩展，并且部署交付都消耗人力，所以我们要对它进行重构。

- Remote App 作为一种连接方式，而不是一种类型
- Remote App 主机池由 JumpServer 维护，能定时上报状态
- Remote App 主机可以自动部署，自动维护
- 密码代填 使用 Python 框架完成，不再使用 AutoHotKey
- 添加 RemoteApp 类型后，需要声明支持的资产类型
- 其它 

## 五、关于资产连接方式的统一
区分三种方式

#### 本地客户端方式 (native) - 原始协议级实现
  - native_magnus(DB 客户端) (出现 tab，二级处理)
      - native_magnus_navicat (直接拉起，目前还无法实现)
      - native_mangus_mysqlcli (直接拉起，目前还无法实现)
  - native_koko(SSH 客户端) (拉起 putty 连接资产)
  - native_razor(RDP 客户端) (拉起 rdp 连接资产，可选下载 rdp 文件)
    
#### Web(web) - 基于 Web 实现
  - web_omnidb(DB GUI) (DB web 实现)
  - web_koko(WEB CLI) (SSH/Telnet web 实现)
  - web_lion(WEB RDP) （RDP web 实现)
    
#### 远程应用(remote_app) - 基于 Remote App 实现代理，只能录像
  - remoteapp_navicat (远程应用 Navicat)
  - remoteapp_chrome (远程应用 Chrome)

**说明**: remote app 方式可以 web 连接，拉起 rdp 客户端，也可以下载文件，提供额外三种选项

#### Installer 中使用 MariaDB 取代 MySQL
MySQL 5.x 系列没有 arm 版本，这就导致我们在不同平台上，用了不同的数据库，这个版本统一了

**Comment by ibuler** [comment]
有一个值得商榷的事，到底一个资产要不要支持多个协议

**Comment by heatdrive** [comment]
真的推到重来了 这将是一个伟大的版本

**Comment by dowliu** [comment]
建议社区版本也能支持pg和oracle数据库的管理，只支持cli操作也行。然后给xpack开放web管理的方式。

**Comment by ibuler** [comment]
> 

我们考虑一下

**Comment by evilgaoshu** [comment]
既然以资产众多为背景，希望能考虑增加对 ansible 支持

**Comment by ibuler** [comment]
> 既然以资产众多为背景，希望能考虑增加对 ansible 支持

那就支持一下呗，不过不放在 3.0 了，以后可以完善

**Comment by py0426** [comment]
感觉底层已经明显具备cmdbt特性了，主机、数据库、账号密码、容器都可以看作是底层资产，堡垒机只是一种基于底层数据的运用。如果是这样的话，是否可以考虑进一步丰富底层，以应用为中心(类似bk-cmdb)的思想来重构底层，后续jumpserver也就不再局限于jumpserver了。

**Comment by ibuler** [comment]
@py0426 对于 bk 还没有太多研究，这里只是做了抽象，通用字段抽象出来放到 asset_asset 表中，每种类型资产属性放入到单独的表中。

**Comment by ibuler** [comment]
账号差异
![v2-v3账号差异](https://user-images.githubusercontent.com/17382885/185865302-ccdd0e28-6b63-463e-b9d8-868621a4bfd9.jpg)

资产差异
![v2 - v3 资产差异](https://user-images.githubusercontent.com/17382885/185865336-bfbae17b-7f61-486d-a3aa-e5b26ea5e532.png)

**Comment by ibuler** [comment]
### 资产差异
![v2 - v3 资产差异](https://user-images.githubusercontent.com/17382885/185865336-bfbae17b-7f61-486d-a3aa-e5b26ea5e532.png)

**Comment by xufeng0832** [comment]
对k8s类型资产是以cluster为单位的资产还是以container为单位呢？代建议可以针对container或pod授权。

**Comment by xyziven** [comment]
感觉也是无协议比较适中，绝大部分情况下其实都是单协议连接，下面这种多协议可能相对少数
linux： ssh+rdp+telnet
windows： rdp+ssh

其实是否多协议也主要依赖资产所能提供的连接方式，另外VNC又是相对特殊的连接方式，它主要涉及vnc密码，没有具体的用户名。

**Comment by xyziven** [comment]
**“灵活定义su切换方式(enable、还是 su”**

能灵活定义切换方式挺好的，同时还应该考虑一下sudo切换的方式：管理员应该可以设定是通过su还是sudo来切换。sudo的好处是“只需知道当前登录用户的密码”，而无需知道2个密码（目标用户的密码）

**Comment by ChenpiDog** [comment]
希望社区版对数据库的支持能更强大更完善些：
1）除MySQL外，支持其它的一些开源数据库如PostgreSQL和GreenPlum；
2）提供一个页面更美观、功能更完善的网页版SQL Studio。

**Comment by ibuler** [comment]
> 

有时候也没办法，做着做着，就不好使用了

**Comment by levie-vans** [comment]
建议数据库资产增加一些新的数据库的支持，比如TiDB和OceanBase，我们现在就已经在大规模使用TiDB了

**Comment by ttkanni** [comment]
Jumpserver是一个很不错的开源产品，一步一步迭代也经历过大几十次更新了，开源精神非常值得点赞！

作为一个用过不少堡垒机的新手，反馈一点使用感受和优化建议。

首先，系统用户，这个设计不太符合实际使用场景，尤其在大小金融权限隔离、等保要求严格的单位，几乎无法使用，不可能存在一套账号密码能够连通大部分资源。
其次，在逻辑和场景上，账号不建议这么严格的区分，不管是管理员账号（如root）还是普通用户（如appuser），它们都是账号，系统权限高低只是账号的一个属性，只要愿意设置，普通用户appuser也可以是系统级用户，账号的权限属性是可以相互转换的。账号的严格管控，建议通过授权策略去实现。
再次，管理员账号（如root）还是普通用户（如appuser），在企业内部都是独立的使用的，而且管理员账号主要是系统管理维护并使用，普通用户（如appuser1、appuser2……）主要是应用运维来使用。用户做了独立拆分，在原来的Jumpserver逻辑里用户授权相对的就很麻烦，同时如果一台资源存在多方合作（互相不能看见对方），需要很多普通用户的场景，资产授权就会很繁琐。
最后，jumpserver的授权逻辑，感觉用起来怪怪的，当前2.28.1系统用户、普通用户会附加在所有的资源上，登录的时候需要下拉选择。这一点逻辑和堡垒机“独立管控、逻辑隔离、透明使用”的初衷有点小冲突，作为普通用户A，登录一台资源，就应该只看到A能看到的用户配置，其他普通用户B哪怕连名字也不应该是A看到的。

作为堡垒机来说，物理机、虚拟机、应用等都是resource，账号都是resource的附加属性，使用方作为独立的user或者group里的user，针对user的访问权限，应该是针对单个resource做独立权限定义，这些都是通过一条一条rules或者policy控制，一条rules或者policy要明确定义user xx使用account yy通过zz登录方式访问resource kk 。rules或者policy可以考虑以group的形式应对相同的权限场景，比如XX管理员肯定会拥有XX系统下所有ECS的root权限（所有的ECS的root密码都不一样）。正如账号是resource的附加属性，rules或者policy也可以附加到user或者user group上。这样既可以实现精准控制，也能以组的形式去实现resource和user的关联。在管控分离严格的实际场景里，小明通过Jumpserver登录ecs1，那么在ecs1的连接界面，他能而且只能选择授权给他appuser1 ssh/sftp登录，并不能看见其他任何非相关的登录用户。

希望这些使用反馈和优化建议能够帮助重构Jumpserver，感谢带给我们这么好的一款开源产品。

**Comment by ibuler** [comment]
非常开心收到反馈，我们也是基于以上的一些问题，开启了 v3 之旅

1. 抛弃系统用户
Js 刚开始主要考虑的是易用，一个系统用户，自动推送，密码（密钥）是隐藏的，普通用户不会接触。但随着发展，或者等保要求，对账号提出了要求，复杂度、定时改密 等。随着用户越来越多，也收到了他们真实环境的反馈，所以我们在做这方面的调整，放弃系统用户，回归账号本身

2. 账号特权
其实账号特不特权，更多是在维护者的定义，js 中目前也只是个标记，或者筛选的条件，或者用来提权的范围

3. 授权体系
这里你可能没有去做好细化授权规则。JS 是可以指授权某个资产上的某个系统用户的，但是如果你的资产上或者资产所在节点被重复授权了，才会出现多个系统用户

**Comment by ttkanni** [comment]
感谢回复！今天检查了一遍配置，确实是在授权规则里配置了“节点”才导致用户附加到所有节点的ECS上了，感谢指导。

针对jumpserver的v3.0计划，分享一些个人看法，共参考。

> Windows 安装 openssh 支持 ssh；安装 vnc 支持 vnc
> Linux 安装 xrdp 支持 rdp，安装 vnc 支持 vnc，还有 telnet
> 问题1，可以在 平台 上下功夫，因为对于公司来说大部分端口应该是一致的，允许平台来设置 ssh 端口，但是略显生硬，为赋新词强说愁

**针对这个问题，一般企业尤其是金融这种要求严格的企业，对于第三方安装件都是很谨慎的，基本态度是“谁安装谁维护谁兜底”。如果JMS在这块确实需要，建议将Windows、Linux安装插件打包成一个功能插件，这个功能建议可以通过资源上的高权限账号自动安装或用户手动安装，平台上的功能（如定期改密）依赖这个插件功能的开启。
此外还要考虑安全问题，一般针对ssh、vnc这类敏感端口都要单独设置，不能默认，建议涉及的时候考虑一下加入可选配置。其次ssh这类是高危漏洞频繁的插件，漏洞修复的功能也要考虑到。金融单位定期会有漏扫，扫到就要整改或者限制使用。
用JMS当前的方式实现定期改密这类功能显得太重，之前使用卓豪的软件看到过它的一种实现方式，每个资源，比如ECS或者RDS，会要求你写入一个最高权限账号（如root或者dbadmin），它的改密动作就是通过这种高权限账号去实现，一个动作模块内包含去资源上改密、更新自己的元数据库记录。每个操作都是类似事务的机制，有判断、有容错、有重试、有历史版本记录。类似这种思路可以考虑下，轻量级还不需要引入额外的软件，只是针对不同资源类型需要做好不同的接口，当然堡垒机里的资源都是可以规范化的，整体可控。**


> 问题2，一个资产改为两个资产后，如果想账号同步的话，需要设计一个绑定机制，说明他们是同一个资产，账号可能是一样的，改了一个后需要同步更新另一个。
> 问题变的又比较复杂了，或许支持多协议可能更容易描述真实的资产。

**多协议和无协议都可以比较好的描述并解决这个问题，多协议的话更符合日常场景的实际表现，针对提到的账号插入的问题，这个问题可以考虑引入数据库的存储过程实现，所有的数据库里账号的增删改查都可以考虑这种思路，这样在数据一致性、可靠性以及稳定性都可以保证，而且不用在JMS应用端增加负载。唯一麻烦的是，存储过程不方便迁移，对于升级、跨平台这类操作中要密切注意。
同时有一点建议，在多协议方式里，例如windows原生支持的协议如rdp，A资产中administrator使用rdp方式作为一条记录存储，JMS带来的附加协议登录方式（如ssh、vnc）作为另外一条记录存储方便后续增删查改，而且不建议设计成可以同账号、不同密码的逻辑，同名迷惑性且不方便维护。**



> 用户连接到资产，可能某种资产或者某个协议有一些特殊的表现，具体应该在哪去配置呢
> 
> 平台上配置 大多数类型的资产都可能遇到的，配置到平台上
> 资产上配置 各资产大概率不相同的放到资产上
> 账号上配置 和认证有关的在账号上
> 连接时配置 两次连接同一资产，同一账号可能不同时在连接时

推荐在授权策略Rules或Policy里配置，授权策略作为资产和实际用户之间的桥梁，本身应该要承担这种特殊差异性的屏蔽工作，不能去影响资产和用户两个主体的原子性、增加管理成本与维护难度。
授权策略Rules或Policy的布局建议进行优化，当前JMS的授权策略格式无法实现这样的逻辑，推荐一种设计格式，一条授权策略主要分为：自身属性描述、资产与用户配对关系，首先是策略自身属性描述，如名字、备注等，其次是资产与用户配对策略，资产上需要存储资产与账号、协议的组记录，用户和用户组这一端实现建立与授权规则的匹配关系。一条子授权策略建立时先选择一个资产，带出资产上面的账号、匹配的登录协议（每种账号-协议的匹配单独成立），勾选后考虑增设附加操作，然后再匹配用户或用户组。可以使用多条子策略组合成一个授权策略，解决对一个用户或用户组的权限定义。
在授权策略的功能菜单内，建议增设查询功能，可按照资产、账号、协议、用户/用户组多层次组合查询，方便授权策略太多、难以查询的问题。
这种逻辑有一个好处，配置快捷，不用单独精细化一条一条授权策略去配置，子策略聚合成一条授权策略更加灵活，不会产生很多的授权策略数量。唯一一个麻烦的点在于查询和管理上，子策略的查询与展示会比较繁琐，可以考虑组合查询，展示得好好考虑下方式了。

@ibuler 说的比较多，也比较乱，希望有帮助。

**Comment by levie-vans** [comment]
建议登录JmupServer的Web端增加mTLS双向证书认证，为每个用户单独生成客户端证书，进一步增强安全性。

**Comment by wizpresso-steve-cy-fan** [comment]
希望mssql功能可以開源

**Comment by shuboGe** [comment]
现在用的企业版，但是文件管理这一块，希望再优化一下，可以把操作上传下载的文件能够保存下来，方便我们运维审计。目前对安全的要求越来越高。我想这也是大部分使用堡垒机公司的需求。谢谢。

**Comment by ibuler** [comment]
@shuboGe 这个未来会做

**Comment by ggfvictor** [comment]
希望可以增加代理功能，部分海外服务器有时候需要socks5代理连接会更加稳定，希望能够增加前置代理的选择

**Comment by maninhill** [comment]
V3 设计的解读文章（来自老广）：https://mp.weixin.qq.com/s/ofN6KUyjabaWw4HVdvLQ8Q
