### ISSUE TITLE
升级2.23.4的时候报redis错误，实际redis没有问题如何解决？

### ISSUE THREAD

**Issue by jxwuqingyan** [jumpserver/jumpserver#8712]
如图：
<img width="698" alt="image" src="https://user-images.githubusercontent.com/18183044/183569650-0c26e341-dcf4-411a-b60e-c57d574b8ce0.png">
使用的是外置redis，版本6.0.16

**Comment by wojiushixiaobai** [comment]
网络问题，自己到容器里面进行验证
docker exec -it jms_all bash
redis-cli -h 172.16.102.21 -a ${REDIS_PASSWORD}

**Comment by jxwuqingyan** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/18183044/183589002-284961cd-0e31-461c-8d54-e6f89511bb4b.png">

确定不是网络问题

**Comment by wojiushixiaobai** [comment]
```bash
cd /opt/jumpserver/logs
cat jumpserver.log
```
确定下这个错误日志的时间

**Comment by jxwuqingyan** [comment]
就我截图的时候，现在没法登录

**Comment by wojiushixiaobai** [comment]
redis 的密码是不是简单密码或者包含了特殊字符串？

**Comment by jxwuqingyan** [comment]
没有特殊符号呢，就简单的8个字母，大小写都没有，整不会了   最新的redis版本要什么要求？ 还有如果需要用镜像jms_all自带的redis需要怎么开启？

**Comment by jxwuqingyan** [comment]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/18183044/183619572-20f9bd19-1f82-4e98-8a4d-146712224801.png">
现在换了自带的redis，有新的报错^^

**Comment by wojiushixiaobai** [comment]
检查你的配置文件

**Comment by jxwuqingyan** [comment]
配置文件我检查了没有问题，从2.5.2--》2.6.2--》2.16.2都没有问题，在升级到2.18.2的时候，报了这个错：
![image](https://user-images.githubusercontent.com/18183044/184289387-ad2dffe8-0a5c-49d3-97b5-2303c3d554d4.png)
在整个升级过程中只改了镜像的tag，其他都没动，有没有好的解决方案？

**Comment by jym503558564** [comment]
升级问题，可以企业微信群里联系我们工作人员帮忙查看一下。
