### ISSUE TITLE
录像加密存储 

### ISSUE THREAD

**Issue by guxiaoming7087** [jumpserver/jumpserver#8718]
**请描述您的问题.**
目前将录像存储至阿里云OSS，可以实现录像下载后需要认证才能播放吗？

**Comment by wojiushixiaobai** [comment]
OSS本身就需要认证，不做额外的加密解密

**Comment by guxiaoming7087** [comment]
有提交过阿里工单，从WEB界面下载OSS里面的文件是不需要认证就能打开的，jumperser端可以实现吗？

**Comment by wojiushixiaobai** [comment]
暂不做考虑
