### ISSUE TITLE
[Question]  是否支持关闭 zlib@openssh 压缩

### ISSUE THREAD

**Issue by Songxwn** [jumpserver/jumpserver#8719]
**请描述您的问题.**

请问Jumpserver连接SSH 资产的时候，是否能完全关闭 zlib@openssh。
因为我们部分SSH设备有问题，导致zlib@openssh算法出现了bug.

**Comment by Songxwn** [comment]
此问题发现ansible 任务（测试资产可连接性）中，会自动使用此算法。

**Comment by jym503558564** [comment]
报错日志可截图，我们开发人员好排查问题和解决问题。
