### ISSUE TITLE
Bad authentication type

### ISSUE THREAD

**Issue by tomxiaxia** [jumpserver/jumpserver#872]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
jumpserver0.3.2
##### 问题复现步骤
1. [步骤1] 推送系统用户 到主机报错
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
我的主机的key 可以远程登录到所有主机
FAILED: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])FAILED: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])FAILED: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])

##### 其他

[注:] 完成后请关闭 issue

**Comment by jumping** [comment]
刚刚也遇到这样的问题。最后解决了。
原因是：jumpserver 添加 用户后，不知什么原因，没有修改home目录下的文件权限，导致无法使用公钥。
