### ISSUE TITLE
[Question] vscode remote ssh 端口转发失败

### ISSUE THREAD

**Issue by BoringCat** [jumpserver/jumpserver#8726]
**请描述您的问题.**
通过 Jumpserver 连接主机时，VsCode会卡在 `Setting up SSH Host fooHost-jumpserver: ([details] command:opensshremotes.showDetails)) Setting up SSH tunnel`
![image](https://user-images.githubusercontent.com/25497484/184054134-0ef12c0c-d6ec-48fa-ab43-f8095cee86be.png)

但直连主机时，VsCode 可以成功连接
![image](https://user-images.githubusercontent.com/25497484/184054358-78023abc-8f9e-4971-abb7-e1a038ac05ab.png)

<details>
<summary>使用的 ssh_config</summary>
<pre>Host fooHost-jumpserver
    HostName jumpserver.****
    User boringcat@root@xx.xx.xx.xx
    Port 2222
Host fooHost-direct
    HostName xx.xx.xx.xx
    User root
    Port 22
</pre>
</details>

<details>
<summary>koko的配置</summary>
<pre># 项目名称, 会用来向Jumpserver注册, 识别而已, 不能重复
# NAME: 'jumpserver'
# Jumpserver项目的url, api请求注册会使用
CORE_HOST: http://127.0.0.1:8080
# Bootstrap Token, 预共享秘钥, 用来注册coco使用的service account和terminal
# 请和jumpserver 配置文件中保持一致，注册完成后可以删除
BOOTSTRAP_TOKEN: ***********************
# 启动时绑定的ip, 默认 0.0.0.0
# BIND_HOST: 0.0.0.0
# 监听的SSH端口号, 默认2222
# SSHD_PORT: 2222
# 监听的HTTP/WS端口号，默认5000
# HTTPD_PORT: 5000
# 项目使用的ACCESS KEY, 默认会注册,并保存到 ACCESS_KEY_STORE中,
# 如果有需求, 可以写到配置文件中, 格式 access_key_id:access_key_secret
# ACCESS_KEY: null
# ACCESS KEY 保存的地址, 默认注册后会保存到该文件中
# ACCESS_KEY_FILE: data/keys/.access_key
# 设置日志级别 [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
LOG_LEVEL: WARN
# SSH连接超时时间 (default 15 seconds)
# SSH_TIMEOUT: 15
# 语言 [en,zh]
# LANG: zh
# SFTP的根目录, 可选 /tmp, Home其他自定义目录
SFTP_ROOT: /
# SFTP是否显示隐藏文件
# SFTP_SHOW_HIDDEN_FILE: false
# 是否复用和用户后端资产已建立的连接(用户不会复用其他用户的连接)
# REUSE_CONNECTION: true
# 资产加载策略, 可根据资产规模自行调整. 默认异步加载资产, 异步搜索分页; 如果为all, 则资产全部加载, 本地搜索分页.
# ASSET_LOAD_POLICY:
# zip压缩的最大额度 (单位: M)
# ZIP_MAX_SIZE: 1024M
# zip压缩存放的临时目录 /tmp
# ZIP_TMP_PATH: /tmp
# 向 SSH Client 连接发送心跳的时间间隔 (单位: 秒)，默认为30, 0则表示不发送
# CLIENT_ALIVE_INTERVAL: 30
# 向资产发送心跳包的重试次数，默认为3
# RETRY_ALIVE_COUNT_MAX: 3
# 会话共享使用的类型 [local, redis], 默认local
# SHARE_ROOM_TYPE: local
# Redis配置
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6380
# REDIS_PASSWORD:
# REDIS_CLUSTERS:
# REDIS_DB_ROOM:
# 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
ENABLE_LOCAL_PORT_FORWARD: true
# 是否开启 针对 vscode 的 remote-ssh 远程开发支持 ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。( 注意: vscode 的连接操作，无审计功能 )
ENABLE_VSCODE_SUPPORT: true
</pre>
</details>
<details>
<summary>使用Python3解析koko的配置</summary>
<pre>Python 3.8.13 (default, Aug  9 2022, 16:17:11) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> with open('config.yml') as f:
...  c = yaml.safe_load(f)
... 
>>> c
{'CORE_HOST': 'http://127.0.0.1:8080', 'BOOTSTRAP_TOKEN': '***********************', 'LOG_LEVEL': 'WARN', 'SFTP_ROOT': '/', 'REDIS_HOST': '127.0.0.1', 'REDIS_PORT': 6380, 'ENABLE_LOCAL_PORT_FORWARD': True, 'ENABLE_VSCODE_SUPPORT': True}
>>> 
</pre>
</details>

**Comment by jym503558564** [comment]
koko的报错日志截图一下

**Comment by BoringCat** [comment]
> koko的报错日志截图一下

koko没有输出报错日志😥

**Comment by LeeEirc** [comment]
vscode的版本，你本地电脑的系统版本，主机的系统版本和openssh的版本，分别是什么？

**Comment by BoringCat** [comment]
VsCode：`1.70.0 (system setup)`
系统：`Win10 21H2 19044.1415`
主机的系统：`PVE 6.4 (Debian 10) 5.4.189-1-pve #1 SMP PVE 5.4.189-1 (Wed, 11 May 2022 07:10:20 +0200) x86_64 GNU/Linux`
本地的openssh版本：`OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2`
主机的openssh版本：`OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1n  15 Mar 2022`

**Comment by LeeEirc** [comment]
未能复现 我使用的环境如下：

VSCode Version: 1.70.1 (user setup) 
本地 Windows 10 企业版 LTSC
本地Windows openssh V8.9.1.0p1-Beta
主机 openssh OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
