### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yanyanyong** [jumpserver/jumpserver#8729]
**浏览器版本**
chrome 103.0.5060.134

**Bug 描述**
linux 资产通过 rz 命令上传大文件(100M)后报乱码错误并且终端界面卡住无法操作，也无法敲命令去正常退出，
只能关闭页面或者重新连接，只要是终端界面卡住没有正常退出都会这样，我理解为会话僵死
这样子在堡垒机连接会话并不会断开，只能在控制台终止会话，稍不注意这个僵死的会话就会生成一个巨大的临时录像文件把磁盘压爆。有没有功能能让堡垒机自动识别僵死的会话并且关掉？

**Bug 重现步骤(有截图更好)**
1.  
![1660196380829](https://user-images.githubusercontent.com/76428790/184070651-f49a50a2-bdd5-4aca-85a1-85856dfe8c70.png)

2. rz test.txt   #上传文件乱码界面僵死，无法输入命令退出
3. 堡垒机终端右上角关闭当前会话或者重新连接
4. 控制台显示在线会话有多个，之前僵死的会话会一直在

**Comment by LeeEirc** [comment]
待复现，会完善下在线会话的退出机制。
