### ISSUE TITLE
python3.6.4 环境安装报错

### ISSUE THREAD

**Issue by xiaodingding** [jumpserver/jumpserver#873]
[简述你的问题]
1.在ubuntu 16.04 LTS ,python 3.6.4环境下安装报错，安装测试一晚上无法解决。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
Jumpserver 0.4.0
##### 问题复现步骤
1. [步骤1]
安装最新python环境，python3.6.4版本
2. [步骤2]
执行 pip install -r requirements.txt -i https://pypi.doubanio.com/simple
##### 具体表现[截图可能会更好些,最好能截全]
![default](https://user-images.githubusercontent.com/5170656/34386150-385603dc-eb62-11e7-94a6-d43531c5a0f5.png)

##### 其他
1.gssapi 安装一直报错。
Complete output from command python setup.py egg_info:
    /bin/sh: 1: krb5-config: not found
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uy1yyr5e/gssapi/setup.py", line 56, in <module>
        link_args = get_output('krb5-config --libs gssapi')
      File "/tmp/pip-build-uy1yyr5e/gssapi/setup.py", line 38, in _get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/python36/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/python36/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
    
2.安装python-ldap 报错
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-30de2asj/python-ldap/setup.py", line 9, in <module>
        from ConfigParser import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    
![default](https://user-images.githubusercontent.com/5170656/34386728-0d67584e-eb65-11e7-82b6-9a04c28335e1.png)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-30de2asj/python-ldap/
ConfigParser 查找网上相关资料，改文件名称，不能解决，安装mycqlclient也不能解决。
因为Python3之后，ConfigParser变成了configparser，即使改了文件名，也不能使用。
![default](https://user-images.githubusercontent.com/5170656/34386691-e82956f4-eb64-11e7-9a8f-e255138b6bae.png)

3.在实际环境中，运行的时候报如下错：
ImportError: No module named 'mysite'，
![default](https://user-images.githubusercontent.com/5170656/34386670-d064fa6e-eb64-11e7-8a0f-790e2cc7b4f6.png)

4.还有请问一下，这个平台如何可以在Windows中正常运行呢？

谢谢。
[注:] 完成后请关闭 issue

**Comment by Aeternam** [comment]
1. gssapi
apt install -y libkrb5-dev

**Comment by ibuler** [comment]
0.5.0版本已经严格控制了各模块版本，请测试
