### ISSUE TITLE
[Bug] 升级2.24.0后会话经常被关闭

### ISSUE THREAD

**Issue by dowliu** [jumpserver/jumpserver#8731]
**JumpServer 版本(v1.5.9以下不再支持)**
2.24.0

**浏览器版本**
Edge 版本 104.0.1293.47 (正式版本) (64 位)

**Bug 描述**
在2.24.0引入最大空闲参数后，无论如何设置，都会在超过60min后断开用户会话，设置了其他值（比如300）也不行，请确认一下这个是否是个bug呢，升级到2.24.1之后问题仍然存在。在数据库里面，能够看到`SECURITY_MAX_IDLE_TIME`已经进行了修改。

**Comment by dowliu** [comment]
![Snipaste_2022-08-11_16-38-21](https://user-images.githubusercontent.com/59379000/184096482-8fa74954-2795-409a-be73-90644de389ca.png)
![Snipaste_2022-08-11_16-41-09](https://user-images.githubusercontent.com/59379000/184096486-f29528fd-0a92-45d1-a806-4d0d4ab5f46a.png)

**Comment by LeeEirc** [comment]
贴下koko的日志？

**Comment by dowliu** [comment]
[koko.log](https://github.com/jumpserver/jumpserver/files/9336113/koko.log)
附件里面一些敏感信息作了脱敏处理，应该不影响阅读。

**Comment by LeeEirc** [comment]
未发现问题，可以看到 8d648b41-5c0d-408d-a12d-37a640f08fdd 确实因为超时 300 分钟断开。

**Comment by dowliu** [comment]
我再补充一下场景，我们的jumpserver是部署在aws alb后面的，我看了一下，aws的alb有个空闲会话保持设置的参数，最大可以设置3600s，是否和该配置有关。但是在升级到2.24.0之前并未出现过该问题。在之前版本未引入`SECURITY_MAX_IDLE_TIME`参数的时候，jumpserver的web端是否会定期和后端进行通讯，所以未达到alb的空闲会话超时值？

**Comment by dowliu** [comment]
![Snipaste_2022-08-15_17-01-38](https://user-images.githubusercontent.com/59379000/184607258-2bf34ad2-b078-4add-b616-96b879e011b0.png)
如图，刚刚我对比了一下，log里面300min超时的那个session是连资产的会话，并非用户登录的会话。所以，`SECURITY_MAX_IDLE_TIME`参数真的针对的是用户登录会话，而不是原来版本里面的资产会话吗？

**Comment by LeeEirc** [comment]
SECURITY_MAX_IDLE_TIME 是登陆资产的操作会话超时时间，你需要的可能是 core 的参数配置[SESSION_COOKIE_AGE](https://github.com/jumpserver/jumpserver/blob/dev/config_example.yml#L21)

**Comment by dowliu** [comment]
> SECURITY_MAX_IDLE_TIME 是登陆资产的操作会话超时时间，你需要的可能是 core 的参数配置[SESSION_COOKIE_AGE](https://github.com/jumpserver/jumpserver/blob/dev/config_example.yml#L21)

嗯，是的。这个参数除了在config里面设置，有其他地方可以设置吗？

**Comment by BaiJiangJie** [comment]
v2.24.2 版本修复了，用户每隔一小时会自动退出的问题。

另外，如果不升级也可以通过修改配置文件参数进行解决，SESSION_COOKIE_AGE，单位 s

@dowliu

**Comment by dowliu** [comment]
已经升级到了2.24.2，同时也修改了config.txt里面的参数，今天上午测试似乎正常了。感谢工作人员的解答。
