### ISSUE TITLE
[Question] 请问连接 TigerVNC 如何支持剪贴板

### ISSUE THREAD

**Issue by get-set** [jumpserver/jumpserver#8734]
情况: 用 Web 页面方式访问 VNC 时, 剪贴板无法使用, 请问是否支持? 或者是否需要安装某些工具?

系统版本: Ubuntu 20.04 LTS
桌面环境: ubuntu-desktop/focal-updates,now 1.450.2 amd64
JumpServer: 1.23.2
VNC版本: TightVNC Server version 1.3.10

谢谢!

**Comment by wojiushixiaobai** [comment]
标准 vnc 协议本身就不支持复制粘贴和文件上传下载

**Comment by get-set** [comment]
理解了，谢谢！
