### ISSUE TITLE
如果页面的终端持续输出几百万行的log会不会导致浏览器卡死[Question] 

### ISSUE THREAD

**Issue by Juken8104** [jumpserver/jumpserver#8736]
**如果页面的终端持续输出几百万行的log会不会导致浏览器卡死，前端页面会不会由于显示的元素内容过大儿导致页面out of memory?**

**Comment by wojiushixiaobai** [comment]
只会显示 5000 行

**Comment by Juken8104** [comment]
> 只会显示 5000 行

是终端页面始终保持再5000行嘛？还是websocket一次性限制输出5000行，终端页面会持续append？

**Comment by ibuler** [comment]
web 终端那个窗口，最多显示 5000行历史，超过了就 free 了
