### ISSUE TITLE
[Bug] xshell使用rz传输文件之后，后续当前session使用的命令 录像缺失，命令历史缺失

### ISSUE THREAD

**Issue by DeyunLuo** [jumpserver/jumpserver#8738]
[类似issue 770提到的问题](https://github.com/jumpserver/jumpserver/issues/770)
**Bug 描述**
1. xshell 5.0版本使用rz命令之后，后续命令录像缺失，命令历史缺失。
    如下图所示
     
<img width="555" alt="WeChatWorkScreenshot_798755ee-4124-4981-b028-5342175081b8" src="https://user-images.githubusercontent.com/32233191/184314415-4eaed20d-ad47-4021-9ef7-12a9e40dd159.png">
<img width="653" alt="WeChatWorkScreenshot_979afa5f-8fe9-448c-8696-f48eab5bb016" src="https://user-images.githubusercontent.com/32233191/184314442-bdac870e-6b6d-4727-8764-0ddb8907a128.png">

**Comment by LeeEirc** [comment]
已经修复，等待版本更新。

**Comment by LeeEirc** [comment]
新版本v2.25已经发布。
