### ISSUE TITLE
[Bug]  lb服务启动失败，sed: cannot rename /etc/nginx/conf.d/sednEaKnD: Device or resource busy

### ISSUE THREAD

**Issue by Fmetat** [jumpserver/jumpserver#8742]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.2

**浏览器版本**

**Bug 描述**
从v2.11.0 升级后启动，lb服务启动失败，sed: cannot rename /etc/nginx/conf.d/sednEaKnD: Device or resource busy

**Bug 重现步骤(有截图更好)**
1.  从v2.11.0 升级后启动
![image](https://user-images.githubusercontent.com/50227571/184471854-1dfc7719-37b9-4653-923c-dcbec149155d.png)

![image](https://user-images.githubusercontent.com/50227571/184471882-f424d1bf-0460-4afd-86ae-2dee5a5149eb.png)

**Comment by wojiushixiaobai** [comment]
将你修改的代码还原。

**Comment by Fmetat** [comment]
> 将你修改的代码还原。

什么都不改的报错为：
![image](https://user-images.githubusercontent.com/50227571/184474130-fc9a12e8-66b9-4ad2-9ffa-196e1863f4af.png)

**Comment by wojiushixiaobai** [comment]
请正确升级，参考升级文档的步骤。
