### ISSUE TITLE
[Bug] redis 托管是否不支持集群模式

### ISSUE THREAD

**Issue by kerecsen** [jumpserver/jumpserver#8748]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.2

**浏览器版本**
chrome Version 103.0.5060.134

**Bug 描述**
 使用 应用管理-数据库-redis 托管功能发现连 redis 集群模式查询 redis 数据会出现『(error) MOVED xxx 』错误，即时模仿 redis-cli 加上 -c 参数也不行

**Bug 重现步骤(有截图更好)**
1.  redis 信息配置如下：
![image](https://user-images.githubusercontent.com/22140485/184619607-a08af421-5603-4cc2-910e-275975655492.png)

2. 连接 redis：
![image](https://user-images.githubusercontent.com/22140485/184619734-285bf48c-3033-4979-a94b-cbb9ab11cc9a.png)

**Comment by LeeEirc** [comment]
尚未支持命令行参数 -c 的集群模式，待后续完善。

**Comment by kerecsen** [comment]
> 

好的，顺便也问下 mongodb 的纳管支持集群模式么？

**Comment by LeeEirc** [comment]
目前不支持。可以贴一下你使用的集群连接命令，后续版本完善。
