### ISSUE TITLE
[Bug]由2.19升级至2.24后，终端设置里的录像存储、命令存储的历史配置无法删除，并怀疑实际没有切换至其他配置

### ISSUE THREAD

**Issue by LHB6540** [jumpserver/jumpserver#8757]
**JumpServer 版本(v1.5.9以下不再支持)**
当前jumpserver版本2.24.2

**Bug 描述**
在升级至2.24.2的过程中，做了两步：
1、拷贝数据至另一台机器
2、升级至2.24.2
由于迁移到了新机器，旧机器所使用的es、minio存储准备换成本地存储，切换为本地后，打算删除原有的es、minio存储配置，但是提示配置正在使用中。请问这只是个删除的bug，还是实际上我并没有切换到本地存储成功
![image](https://user-images.githubusercontent.com/41095303/185020549-41cd4796-bbde-4c9a-b738-6fe0a433f57d.png)
![image](https://user-images.githubusercontent.com/41095303/185020715-f3ca711d-b054-4adf-80b4-c1f26c2613f2.png)

**Bug 重现步骤(有截图更好)**
1.在2.19.3版本中的终端配置中使用外部minio、es  
2. 备份数据库至另一台机器，安装并升级至2.24.2版本
3. 尝试删除minio、es配置

**Comment by wojiushixiaobai** [comment]
同步需要时间，切换后大概 1 分钟左右即可清理掉。或者讲所有会话结束后，重启 jumpserver 服务，然后删除即可。

**Comment by LHB6540** [comment]
新迁移的那台机器是连不上旧的es、minio的，不在同一个网络内，不存在同步的情况

**Comment by wojiushixiaobai** [comment]
停机后迁移，使用过程中迁移可能会导致此问题，将所有在线会话清理掉

**Comment by LHB6540** [comment]
好的，我试一下

**Comment by jym503558564** [comment]
先把终端批量更新命令存储和录像存储，不再使用原有的es、minio存储配置。更新后，就可以删除原有的es、minio存储配置
![image](https://user-images.githubusercontent.com/40739051/185313840-f73c780b-a842-4788-abe6-173f10e2d4fd.png)

**Comment by LHB6540** [comment]
> 先把终端批量更新命令存储和录像存储，不再使用原有的es、minio存储配置。更新后，就可以删除原有的es、minio存储配置 ![image](https://user-images.githubusercontent.com/40739051/185313840-f73c780b-a842-4788-abe6-173f10e2d4fd.png)

可以啦，谢谢
