### ISSUE TITLE
[Bug] 针对断连问题要怎么排查定位

### ISSUE THREAD

**Issue by fattan9577** [jumpserver/jumpserver#8759]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.24.0

**浏览器版本**

**Bug 描述**
找了大概30-40个人，同时测试。发现断连现象的发生，频率和次数都比较高。
查看了Lion的日志，发现有错误信息，但是不知道如何解决和定位？

**Bug 重现步骤(有截图更好)**
![f9211f79-bd3f-4ef4-87f4-4c5a63bc2af9](https://user-images.githubusercontent.com/17006372/185056069-2a86e652-9754-401f-9f5c-4ba899e47f47.png)

**Comment by wojiushixiaobai** [comment]
先通过直连的方式排除网络问题，如果问题依旧，可以调整日志等级检查下是否有其他的异常日志
