### ISSUE TITLE
[Question] 添加redis应用时必须指定系统用户

### ISSUE THREAD

**Issue by AlliotTech** [jumpserver/jumpserver#8764]
**请描述您的问题.**
部分redis实例是没有鉴权的，而添加到jumpserver中后必须指定一个系统用户。
web直接登录的时候，提示需要输入密码： 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/24980252/185079899-d22214d5-b7ac-4496-b4fb-7f67edf482e3.png">

直接回车后，可以登录。 但是选择 DB Client 方式登录时，出现如下错误： 
``` shell
redis-cli -h jumpserver.xxx.com -p 63790 -a a0d9d2dxxxx4d33-ac9d-15cac545a450@xxxx
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

I/O error

jumpserver.xxxxx.com:63790>
```

**Comment by Aaron3S** [comment]
已优化，请关注近期 release note，感谢贡献。

**Comment by seaurching** [comment]
@Aaron3S 我添加了没有密码的redis，连接的时候提示没有系统用户，无法连接
