### ISSUE TITLE
[Question] 扩容节点之后，ssh连接到新扩容的节点，公私钥验证失败，提示输入密码

### ISSUE THREAD

**Issue by DeyunLuo** [jumpserver/jumpserver#8766]
之前有两台koko/core的节点，共用同一个数据库和redis，上层用keepalived做了高可用
现在另一个集群继续扩容两台koko/core节点，使用ssh 用户名@新节点IP，提示输入密码
如下图所示
<img width="496" alt="Screen Shot 2022-08-17 at 17 47 15" src="https://user-images.githubusercontent.com/32233191/185088797-3704f363-2d47-4f71-88b0-98b51983a1e5.png">
原来koko节点可以正常登录
<img width="553" alt="Screen Shot 2022-08-17 at 17 47 49" src="https://user-images.githubusercontent.com/32233191/185088967-f4afdd7f-8dbf-4878-a6f2-9ba9f65e20a0.png">
查看core的日志发现，koko请求token的时候接口返回了400
jms_core日志如下所示
<img width="662" alt="Screen Shot 2022-08-17 at 17 50 13" src="https://user-images.githubusercontent.com/32233191/185089495-349eee7f-c6be-4018-91dc-0d229393edff.png">
jms_koko请求认证日志如下所示
<img width="1654" alt="Screen Shot 2022-08-17 at 17 48 38" src="https://user-images.githubusercontent.com/32233191/185089198-de10a30f-93c5-4c0b-965a-4a255cdcc636.png">
看看jms_web的python源码大概定位到问题所在，如下图所示
<img width="1223" alt="Screen Shot 2022-08-17 at 17 49 15" src="https://user-images.githubusercontent.com/32233191/185089301-a11177f2-abe3-4ca4-8521-c7d9850a23ec.png">
下一步除了改源码debug之外，有解决建议吗

**Comment by wojiushixiaobai** [comment]
检查 secret_key 是否一致

**Comment by DeyunLuo** [comment]
> 检查 secret_key 是否一致

感谢大佬，确实是secret_key问题
