### ISSUE TITLE
提示：你的SSH Key没有设置或已经过期,点击 链接 更新，怎么解决？

### ISSUE THREAD

**Issue by sipwhy** [jumpserver/jumpserver#877]
安装环境
CentOS 7

安装的版本
[Jumpserver 0.4.0]

问题描述
在浏览器上登录后，所有的页面都有提示：你的SSH Key没有设置或已经过期,点击 链接 更新
怎么解决？

**Comment by hellorocky** [comment]
admin账号默认是没有设置蜜月的, 按照提示设置就行了
