### ISSUE TITLE
[Feature] 希望可以增加跳板WEB访问功能

### ISSUE THREAD

**Issue by ZJyche** [jumpserver/jumpserver#8770]
**请描述您的需求或者改进建议.**
一些资产不是通过SSH、RDP、Telnet或VNC进行访问的
希望可以有通过该堡垒机访问一些WEB管理页面的功能（不需要密码自动填充等）

我当前是先RDP后通过Windows主机来访问Web管理页面，步骤有些繁琐

希望可以在堡垒机中直接访问对应资产的Web页面，谢谢！

**Comment by ZJyche** [comment]
例如访问配置内网设备页面，如安全设备或虚拟化设备、服务器等。。。
可能涉及到例如POST文件上传和代码解析安全性等。。不过确实是这样的场景不少希望能得到评估，谢谢！

**Comment by wojiushixiaobai** [comment]
企业版本功能，开源版本尚不支持
