### ISSUE TITLE
[紧急，谢谢] 系统没有发出密码到期提醒，也没有自动更新托管密码

### ISSUE THREAD

**Issue by get-set** [jumpserver/jumpserver#8773]
**JumpServer 版本(v1.5.9以下不再支持)**：2.23.2

**浏览器版本**：Chrome 104 arm

**Bug 描述**

系统没有发出密码到期提醒，也没有自动更新托管密码。

**Bug 重现步骤(有截图更好)**

1. 终端中会提示密码过期，这里的密码应该是 Linux 主机的密码，但是密码是动态用户托管的，用户并不知道：

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/7991571/185350961-82974110-ec92-4c5f-a7ff-7e615bcd60f8.png">

2. 说明：近 5 天也没有收到需要重置密码的邮件，发件的配置测试没问题。
3. 重置JumpServer的密码，能够收到重置密码成功的邮件。
4. 再次进终端，依然提示密码过期。
5. 执行用户推送到 Linux 主机的操作，ansible 结果是 `OK`，没有 `changed`。然后再次尝试，依然是密码过期。

**补充说明：**
- 该用户是用动态用户推送的：
<img width="579" alt="image" src="https://user-images.githubusercontent.com/7991571/185292544-803e657d-f434-4bad-ac88-66d55f027a23.png">

- 系统设置密码过期时间为 90 天：
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/7991571/185341750-7ff8a6a7-9b32-4477-a3df-7f71a37c395e.png">

- 我们的主机本身也设置了过期时间为 90 天。现在是在主机那边已经过期了，但是 JumpServer 的“托管密码”功能没有更新密码。

**请问：** 
- 现在是否有临时的方式可以先处理的？
- 管理员不介入的情况下，用户应该如何正确处理这种情况？
- 设置里的“用户密码过期时间”是指 JumpServer 这边的用户的过期时间吗？如果是，没有提前5天开始发送邮件的原因可能是什么啊（邮件服务器的发件配置没问题，已测试）？
- 动态用户的“托管密码”功能是否会定期自动更新主机那边的系统用户的密码？

多谢！

**Comment by wojiushixiaobai** [comment]
资产密码到期不会自动提醒，jumpserver 不会知道资产的密码到期时间。
用户密码到期和资产的系统用户到期时间不是一回事。

企业版本有对应的解决方法，对于开源版本，请修改密码后重新推送，并且在每次密码到期后都需要手动修改系统用户密码然后进行推送（或者可以用 api 实现自动化）

**Comment by get-set** [comment]
@wojiushixiaobai 谢谢你的解答。

“资产密码到期不会自动提醒，jumpserver 不会知道资产的密码到期时间” 这个是可以理解的哈。不过 JumpServer 的用户也到设置的密码到期时间了，看是会提前 5 天发邮件提醒的，但是没有收到。

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/7991571/185341750-7ff8a6a7-9b32-4477-a3df-7f71a37c395e.png">

比如这个用户：

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7991571/185519964-21182405-f910-4441-b28a-6f7183722b24.png">

正常情况下应该有提醒的对吧？

**Comment by get-set** [comment]
第二个问题，请问如果是开源版本的话，动态用户托管密码是不会自动定期更新和推送到主机的是吗？谢谢！

**Comment by wojiushixiaobai** [comment]
没有收到邮件可能邮件进了垃圾箱、邮箱相关配置错误或者 JumpServer 服务异常导致。

开源版本动态用户托管密码是触发型任务，比如对授权的资产增改，系统用户增改才会进行推送作业。
正常情况下没有变动不会进行推送。

**Comment by get-set** [comment]
确认没有仅垃圾箱，邮箱相关配置是对的，而且主动修改密码后会收到邮件通知。

**Comment by jym503558564** [comment]
用户密码过期邮件提醒没有收到，JumpServer是什么版本？

**Comment by get-set** [comment]
JumpServer 是 2.23.2 版本的。

请问对于这个用户来说（系统设置是密码过期时间 90 天）：

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7991571/185519964-21182405-f910-4441-b28a-6f7183722b24.png">

发邮件的时机是以 “失效日期” 为准，还是以 “密码更新日期”+90 为准？

**Comment by jym503558564** [comment]
“密码更新日期”+90

**Comment by get-set** [comment]
@jym503558564 确实是没收到，所有用户都没有收到。

**Comment by jym503558564** [comment]
好的，我们排查一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 刘康 ***@***.***&gt;
发送时间: 2022年8月22日 21:40
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] [紧急，谢谢] 系统没有发出密码到期提醒，也没有自动更新托管密码 (Issue #8773)





 
@jym503558564 确实是没收到，所有用户都没有收到。

**Comment by get-set** [comment]
> 资产密码到期不会自动提醒，jumpserver 不会知道资产的密码到期时间。
用户密码到期和资产的系统用户到期时间不是一回事。

> 企业版本有对应的解决方法，对于开源版本，请修改密码后重新推送，并且在每次密码到期后都需要手动修改系统用户密码然后进行推送（或者可以用 api 实现自动化）

@wojiushixiaobai  我尝试用 API 去更新托管密码，但是发现 `password` 是加密了的，请问这个加密算法是什么？或者是否有更加合适的 API？非常感谢！

<img width="581" alt="image" src="https://user-images.githubusercontent.com/7991571/185935798-2d787d81-383b-4ec3-911b-3a95dbcc54a4.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/7991571/185935181-8fb7c942-7d6f-42aa-85e4-eee989ff24ac.png">

**Comment by jym503558564** [comment]
@get-set 关于密码快过期的邮件提醒，无法复现该问题。发送密码过期提醒，每天会有触发的时间。而不是马上修改配置（系统设置-安全设置-密码过期时间），就立刻发送邮件提醒。

**Comment by get-set** [comment]
@jym503558564  嗯，谢谢！挺奇怪的，密码过期时间我刚部署的时候就设置了，没有改动过，这个问题先放一放吧，你们在另外的环境里也不好验证。

上面的那个问题，你看能帮忙回答一下吗？如果要定期通过 API 刷新托管密码的话，`password`字段如何在构造数据的时候做加密？是什么算法呢？

**Comment by wojiushixiaobai** [comment]
前端加密
api 传递时不需要加密，明文传递即可。

**Comment by get-set** [comment]
好的，谢谢！
