### ISSUE TITLE
[Question] 文档是不是没更新，很多配置和菜单都没找到

### ISSUE THREAD

**Issue by lyy289065406** [jumpserver/jumpserver#8775]
1. 开启 SSO `vi /opt/jumpserver/config/config.txt` ， 这个文件是挂载到哪个 docker 下？ 文档没有说明， 我去 core 的容器下 `/opt/jumpserver/` 只有 config.yml， 直接创建一个目录？ 是挂载在 jms_celery 还是 jms_core 也没说。
2. 开启 SAML2 的 【系统设置】菜单完全没有吧？ 【日志审计】菜单 也没有，怎么配？

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/185464608-a5a7b145-748d-452c-93fe-ca24380ae26d.png)
