### ISSUE TITLE
[Question] 2.21.4升级到2.25.0之后，ssh无法登录

### ISSUE THREAD

**Issue by DeyunLuo** [jumpserver/jumpserver#8785]
两台机器一台是2.21.4版本，一台升级到2.25.0之后，ssh无法登录，
koko报错如下所示
<img width="1676" alt="Screen Shot 2022-08-19 at 17 05 37" src="https://user-images.githubusercontent.com/32233191/185585160-245a518b-52c0-4950-b484-642ea9b61e74.png">

进入jms_core容器内部，旧的2.21.4版本可以拿到public_key，如下图所示
![36171660892584_ pic](https://user-images.githubusercontent.com/32233191/185583891-07763979-520e-4966-9a60-bb7e08be9891.jpg)
新版本2.25.0拿不到public_key,
![36191660892604_ pic](https://user-images.githubusercontent.com/32233191/185583937-cdf1f9b0-947d-4677-a6ba-dc06850d4f6d.jpg)
两边的SECRET_KEY和BOOTSTRAP_TOKEN是一致的，
![36241660892778_ pic](https://user-images.githubusercontent.com/32233191/185584010-029ad412-94ad-4eb0-ab82-b34d0881c3b9.jpg)
![36251660892778_ pic](https://user-images.githubusercontent.com/32233191/185584015-d1c10347-7995-4d31-9cae-769dfa040800.jpg)
<img width="1356" alt="Screen Shot 2022-08-19 at 17 04 23" src="https://user-images.githubusercontent.com/32233191/185584914-b1510a32-e7a5-40f5-aadb-43609d26ae0a.png">
<img width="1390" alt="Screen Shot 2022-08-19 at 17 04 32" src="https://user-images.githubusercontent.com/32233191/185584947-4a46943a-0af2-488c-acf1-78ec7d0c8759.png">

2.25.0版本的jms_core容器日志
<img width="1683" alt="Screen Shot 2022-08-19 at 17 00 39" src="https://user-images.githubusercontent.com/32233191/185584212-c9bf1789-99c4-4158-9843-555b89d5025d.png">
查看数据库django_migrations如下所示
<img width="1076" alt="WeChatWorkScreenshot_b269a149-df63-4a36-8c50-86cd519fe1e2" src="https://user-images.githubusercontent.com/32233191/185584724-521e85b5-6c2e-4899-866f-8faa9be1ea75.png">
升级正常的django_migrations如下所示
<img width="838" alt="WeChatWorkScreenshot_4d88f04a-a3ac-4629-842a-276c5c06359b" src="https://user-images.githubusercontent.com/32233191/185584759-68b4f8f1-8bb1-4ed4-b0c9-87150cf0aad4.png">

把2.25.0使用2.21.4目录的./jmsctl.sh restart之后，可以正常ssh登录
求一个解决思路

**Comment by wojiushixiaobai** [comment]
同一个数据库，多组件负载均衡要求所有组件的版本必须一致

**Comment by DeyunLuo** [comment]
我升级一下主的版本试试

**Comment by DeyunLuo** [comment]
尝试使用同一个版本，并且只保留一台koko，也不行，要输入密码

**Comment by DeyunLuo** [comment]
> 同一个数据库，多组件负载均衡要求所有组件的版本必须一致

找到问题了，升级之后jumpserver-2.25.0/apps/common/utils/crypto.py的加密方式变了，导致2.21.4和2.25.1使用相同的SECRET_KEY加密的public_key不一致，升级的时候migrate数据库会变更这个public_key吗？有解决建议吗，大佬

**Comment by wojiushixiaobai** [comment]
多个节点升级参考官方负载均衡文档说明部署升级，升级前所有节点都需要关闭。
任意节点升级后，其他节点再直接升级即可

**Comment by DeyunLuo** [comment]
> 多个节点升级参考官方负载均衡文档说明部署升级，升级前所有节点都需要关闭。 任意节点升级后，其他节点再直接升级即可

关闭所有节点重新升级还是不行，可以手动触发user的public_key和system_user的private_key migrate吗?

**Comment by ibuler** [comment]
jumpserver-2.25.0/apps/common/utils/crypto.py 这个的确改过，但是没有道理会不一致啊，兼容之前的方式，方便私聊发一下 密钥和一个加密的密文吗

**Comment by ibuler** [comment]
能说明一下你的 SECRET_KEY 的长度吗

**Comment by DeyunLuo** [comment]
> jumpserver-2.25.0/apps/common/utils/crypto.py 这个的确改过，但是没有道理会不一致啊，兼容之前的方式，方便私聊发一下 密钥和一个加密的密文吗 [ibuler@qq.com](mailto:ibuler@qq.com)

secret_key: nyvvz4ZE8IMbknaQH59HrA
密文: 2Sn4VcZV6pSCrge2BXIGZw==mE5eyxOErBZAojCY7HAzAA==jtdXoXjHICQWaHOjW5ibdw==WbQ8aFtdL6c6yLNIDjw2p0ill9PFuf4/WsR0MEvAFbmu1Eo1z87/U4i03LRjN+JR1uXBQ7arVbY/m/MlmAguZzfDFX5vKEXXIJGMmNNXV+bxnEH7aiv7Fkn6z6BE0eovTWbzlfuY2ZWg7ZK6oPSrHXSqOhMgJbeZUSZ0So1G/PcWuSxioGN+MrzqynBOIs11IyTIXEOQrvG2mP6QYW6wRFUI+EtCjxUq03m+SGawIf7M+fpTCKoXJEQTtix+hc8ThsCabrqguGU50y1x1Osv+LzwswG0gOCyhv431MMaf2Hn5pDlPP/h2UctHcohlfhxxuK30s6T6yZSYS5S5L537KFnNtNQqoXJKSNxihrRz6zujXuXI79UpoQ/XIq4RO3RP3T33LMVkCvGgvInNWovj4RiwS+Y5cxBj5QNDgGxfeE1HImcWV5YgbnytVrm/fd6flePucdC95fQGr0+gyK6uc9kC1BX3gfjoMam38P9AAE0eHAtW93dyqn6qpOXGFlcmo0Rnl+Y0isuh5l7eybTfXjKZjkfCqZoWwz/FV9P3VdxtWcbmz2Sww+F/TSo9J/29aU6Fi6V1DQSuaewSoC7w+D+4DyH0qntqJRkPFc0Q1BpVkkBjL1ftWvVHWXpnV2wy5MAxn2KeDdBKAiKIH9ZcpMQtgmwSzRiIKr8iHes1/PYRoz8Z3yPaSuuY0KXda/evV4x6LM5L9+/S7bOwRlCKUjE9PF6/hYU

**Comment by DeyunLuo** [comment]
> jumpserver-2.25.0/apps/common/utils/crypto.py 这个的确改过，但是没有道理会不一致啊，兼容之前的方式，方便私聊发一下 密钥和一个加密的密文吗 [ibuler@qq.com](mailto:ibuler@qq.com)

secret_key保持一致
上面是2.21.4生成的密文
下面是2.25.1版本的密文
AVpy1SQTB5SpqV6vQaaMWw==Pmw/sZ3JqPoQMyjS0G8law==1aiyotvL51cHVMZ4CnL2zQ==CHssh9TPL2VWoHQgVIZan1Hfl+qw6zjC5Po3l7VWewNyjUtuxI27/khvmGyLNTCt65WzTy9Jm9C31tTQmoMqTOTNqbK8nKdZmuHhTj63PWkAdHPlsw/ksGNqEeFvTZOn1zgaG07r9+ADGDOcShkdgyppDUNmYCtg8USsw/F9OVfEec5xupuHODDdZhINoFubDFI+LukxjelXYg5HLRTUgibcXk4RLvbJALSwci412Q+JAMloaaDPlUiqlLvEDFfIhhie972dbu2hwMdq+4Wb1aDpE7UE9eMAfmMfNDzZ6LAVv8iBQzLUiDU5y5mcHwmRTqCiqhW9ayNmiquS5mHBvm19Xzo8p7EhCHi/MdLBzbBuKVkygqF0AUJ6ze606FwzQMIOGQx5HUTa1krGgfwbDWykP+TVbHLpo01P68SagA+yGJWqGehlUsEc8IVCT2iQWYd7maaTdY0Pm8LSpwwIpvo8ZGtdm0uPEl1iNmeLqVjmuD98Xp3ku1Iut8HgfX8pkEJ5iKIA5YDtg8m1IaC/Y6C3sLwv00ZKLO/u4NGpr2+sC/RL0eNhKB1x/XaDjBAnpsOCVGFh33vMuQQbubFnV0wkbPVrEps8Xm18Xi2LGf7TYf4w+MBbUYyoDMCMA8fHxPunZxs8O/7ZHZCsdG3/Pmv+YS9S34RK1LfRvO4YfT0X8Spr02AXkoqKxoOE2bAtIQ37nl0TclXmBWwiTYLEBBQ8JP1C7kq6

**Comment by DeyunLuo** [comment]
把crypoto.py单独拿出来运行，2.25.1版本无法解密2.21.4版本生成的密文

**Comment by ibuler** [comment]
找到问题了，在 key 长度低于 36 时，出现了不兼容情况，我们紧急修复一下

**Comment by DeyunLuo** [comment]
经过更改jumpserver-2.25.0/apps/common/utils/crypto.py的padding_key方法
将`def padding_key(key, max_length=32):
    """
    返回32 bytes 的key
    """
    if not isinstance(key, bytes):
        key = bytes(key, encoding='utf-8')

    if len(key) >= max_length:
        return key[:max_length]

    while len(key) % 16 != 0:
        key += b'\0'
    return key`
更改为
`def padding_key(key, max_length=32):
    """
    返回32 bytes 的key
    """
    if not isinstance(key, bytes):
        key = bytes(key, encoding='utf-8')

    if len(key) >= 32:
        return key[:32]

    return pad(key, 32)`之后，
经过上述处理之后AESCryptoGCM对象的self.key和2.21.4会保持一致，2.25版本可以解密2.21.4的密文，

**Comment by DeyunLuo** [comment]
> 找到问题了，在 key 长度低于 36 时，出现了不兼容情况，我们紧急修复一下

好的

**Comment by ibuler** [comment]
已修复  https://github.com/jumpserver/jumpserver/pull/8795，今天发版
