### ISSUE TITLE
[Question] Ldap使用邮箱登陆如何使用SSH直连资产？

### ISSUE THREAD

**Issue by 111234567890** [jumpserver/jumpserver#8787]
**请描述您的问题.**
正常来说SSH直连资产需要 ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p 2222
但是LDAP的username是邮箱，举个例子
username:  abc@example.com
资产ip 192.168.3.100
堡垒机ip 192.168.3.1
ssh abc@example.com@root@192.168.3.100@192.168.3.1  -p 2222  会提示密码不对
这种情况需要怎么处理？还是我的操作有问题？

**Comment by wojiushixiaobai** [comment]
可以用 # 分割
