### ISSUE TITLE
[Question]一键部署之后，用系统账号测试登录服务器报错

### ISSUE THREAD

**Issue by tcjc5214** [jumpserver/jumpserver#8788]
**请描述您的问题.**
我的服务是centos7.6, 使用一键部署jumpserver v2.25.0版本之后，无法用系统账号 测试登录新的资源服务，报错截图如下
![image](https://user-images.githubusercontent.com/21101930/185738940-871e56d1-11f2-431f-984d-137eff8f02ff.png)
ansible 报权限问题，能否给到指导，避开这个问题

**Comment by jym503558564** [comment]
v2.25.1已修复，可升级至最新版本进行测试。
