### ISSUE TITLE
资产硬件更新时报错 报错代码块jumpserver/apps/assets/tasks.py

### ISSUE THREAD

**Issue by whoistr** [jumpserver/jumpserver#879]
[简述你的问题]
在资产详情界面，点击更新硬件信息报error
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤
1. [步骤1]
点击资产管理--点击资产具体信息
2. [步骤2]
点击硬件刷新 
##### 具体表现[截图可能会更好些,最好能截全]
![1](https://user-images.githubusercontent.com/17622106/34433415-1b876e18-ecba-11e7-851a-6a54c30d0a71.png)
![2](https://user-images.githubusercontent.com/17622106/34433417-1f654a82-ecba-11e7-8573-f8d4e719f3ee.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
解决了？

**Comment by whoistr** [comment]
不是，是更新了一版代码就没有遇到这个问题了。 所以关了
