### ISSUE TITLE
[Bug] 命令存储 ES远程存储

### ISSUE THREAD

**Issue by PGDream** [jumpserver/jumpserver#8791]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
命令存储我们配置到ES中，但是配置页面无法配置ES认证的用户名和密码，后来使用URL方式配置用户名密码就出现前端split问题

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/6630520/185836703-a967574d-7823-49c3-b263-888379064984.png)

2. 
![image](https://user-images.githubusercontent.com/6630520/185836718-bbf5feec-99fc-49dd-ad52-b599948c7a0d.png)

3.

**Comment by wojiushixiaobai** [comment]
无法复现
![image](https://user-images.githubusercontent.com/24326988/186118496-d5edce4c-1ab7-448b-a017-91a584c8c258.png)
![image](https://user-images.githubusercontent.com/24326988/186118573-c6db3398-3e5d-4815-989d-c8575045908b.png)
