### ISSUE TITLE
[Bug] 升级jumpserver v2.25.2版本 xshell间隔30s左右，使用rz传输文件之后，后续当前session使用的命令 录像缺失，命令历史缺失

### ISSUE THREAD

**Issue by DeyunLuo** [jumpserver/jumpserver#8798]
[issue 8738](https://github.com/jumpserver/jumpserver/issues/8738)
v2.25.0版本修复了rz传文件，如下所示
<img width="254" alt="WeChatWorkScreenshot_0437db96-ccd7-4445-bfef-d50016f8ee2f" src="https://user-images.githubusercontent.com/32233191/185907143-e4570f45-29e0-441f-b058-6f8c94f83524.png">

但是输入rz命令之后，rz弹出窗口停留30s之后再选择文件传输，后续的命令依然无法录像，如下图所示
<img width="1407" alt="WeChatWorkScreenshot_e1cdeece-1056-4e01-9629-780ed1f6abd5" src="https://user-images.githubusercontent.com/32233191/185907461-e9f50557-6051-41b8-bd0c-e8a52b09aa89.png">

<img width="256" alt="WeChatWorkScreenshot_4439a4a8-cbe3-418b-a0b5-c433d96e5e2a" src="https://user-images.githubusercontent.com/32233191/185907302-5a1cbe54-26c5-401d-9159-81d7eef89123.png">
<img width="441" alt="WeChatWorkScreenshot_5c68f4f5-1636-4211-96dd-fc60f497e09b" src="https://user-images.githubusercontent.com/32233191/185907715-8bd8a627-f436-4fe5-ae72-2c79aca1aeea.png">

**Comment by LeeEirc** [comment]
感谢如此细致测试，待复现，调研后修复。
