### ISSUE TITLE
Document About SSL Usage.

### ISSUE THREAD

**Issue by wptad** [jumpserver/jumpserver#88]
I am planning to make a full document about SSL usage in this week.

**Comment by wptad** [comment]
@ibuler 大概写了一个nginx配置文档，测试通过。你看一下，可以考虑加到帮助文档目录里。https://github.com/jumpserver/jumpserver/blob/master/docs/nginx-with-ssl-configuration.md

**Comment by ibuler** [comment]
ok, django和websocket入口文件统一了，其中的参数可能需要修改， @jiaxiangkong 最后会校对一遍
