### ISSUE TITLE
V0.32 Docker部署 ssh 工具无法登录。

### ISSUE THREAD

**Issue by CaoMengLong** [jumpserver/jumpserver#880]
docker部署的，然后端口映射到22的.现在web好用。

ssh客户端连接不上去。

看了常见问题文档都不能解决。

请问有办法解决吗？

谢谢~

使用的Jumpserver版本 0.3.2

![image](https://user-images.githubusercontent.com/10876024/34459574-cf7c466c-ee2e-11e7-95dc-4d48c51f6542.png)

**Comment by wojiushixiaobai** [comment]
不推荐使用 ssh
已经运行的容器可以使用docker exec it 容器名 /bin/bash 
未运行的可以使用 docker run it 容器名 /bin/bash 

使用前可以使用--help 查看说明

**Comment by CaoMengLong** [comment]
不是要进docker容器。是要进 jumpserver的ssh 跳板机界面。  端口映射过去后，发现没法进入呢。

**Comment by ibuler** [comment]
0.3版本对 docker不友好
