### ISSUE TITLE
[Feature] 升级到2.25.2后，视图菜单下的“显示左边栏”能不能保留？

### ISSUE THREAD

**Issue by QingYu2017** [jumpserver/jumpserver#8801]
升级后该选项取消，左下角有折叠按钮，折叠后左边栏折叠后显示抽屉和九宫格按钮但还是占用空间，体验不如通过“显示左边栏”关闭边栏，建议保留，谢谢

**Comment by jym503558564** [comment]
感谢您的提议。目前大部分用户使用体验良好，如后续有需要重新设计，我们会在未来版本进行优化～
