### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by changeflyhigh** [jumpserver/jumpserver#8802]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.23.0   --> V2.24.0   -->V2.25.0

**浏览器版本**
Firefox 103.0.2 (64 位)

**Bug 描述**
![图片](https://user-images.githubusercontent.com/30860085/186300653-e8dfb4ea-1340-4730-95da-67f9d121062e.png)
升级jumpserver版本后，此处的数据库帐号密码会发生变化，但我已经设置了很长很长的密码超时时间

**Bug 重现步骤(有截图更好)**
1.  https://github.com/jumpserver/jumpserver/releases 下载 升级包，使用 ./jmsctl.sh upgrade
2. 初始版本 V2.23.0
3. 只升级大版本，不升级小版本  V2.23.0 -> V2.24.0 -> V2.25.0
4. 升级结束后，navicat连接 jumpserver的 数据库帐号密码 都变了，但我已经设置了很长很长的密码超时时间

**Comment by wojiushixiaobai** [comment]
每次都会变更

**Comment by changeflyhigh** [comment]
> 每次都会变更

但是已经设置了 过期时间了呀，不生效啦？

**Comment by changeflyhigh** [comment]
> 每次都会变更

如果企业级用户大规模推广这个功能，每次升级都换一次密码，估计 运维团队 要被扣绩效了。

**Comment by wojiushixiaobai** [comment]
从 web页面右上角 - 连接令牌里面确认下。

**Comment by changeflyhigh** [comment]
![图片](https://user-images.githubusercontent.com/30860085/186798352-6fb85c7a-1b1d-4227-ba41-790051572824.png)

**Comment by jym503558564** [comment]
关于Magnus数据库连接信息，每次点击，都会心新创建一个token。这个token的有效期是您所设置的有效期，在这个有效期时间内，您可以一直拿着这个token进行连接。

**Comment by jym503558564** [comment]
您连接失败时，截图一下后台报错的日志信息，方便我们研发人员进行分析排查。

**Comment by changeflyhigh** [comment]
2022-09-01 14:12:41 [ERRO] Get Connect token auth failed: POST http://core:8080/api/v1/authentication/connection-token/secret-info/detail/ failed, get code: 500, {"error": "Server internal error"}

**Comment by jym503558564** [comment]
连接数据库失败时，Magnus的日志也截图一下

**Comment by changeflyhigh** [comment]
> 连接数据库失败时，Magnus的日志也截图一下

1、我发的就是 Magnus 的日志，只是文本，不是截图
2、问题并不在于 Magnus 日志，而是旧的 token 在升级的时候过期了，不见了，这个才是问题所在。对于 Magnus 而言就是 用一个不存在的 token 过来访问而已。

**Comment by jym503558564** [comment]
> ![图片](https://user-images.githubusercontent.com/30860085/186798352-6fb85c7a-1b1d-4227-ba41-790051572824.png) 补充说明： 令牌失效日期是 2027/8/24，我设置了5年过期时间，倒退生成时间是 2022/8/24，也就是前两天升级到时候，即是升级 V2.25.0 的时候创建的，并不是 V2.23.0 的时候创建的，因为 V2.23.0使用了应该有一个月了。

从这张图显示，token还在有效期

**Comment by jym503558564** [comment]
> ![图片](https://user-images.githubusercontent.com/30860085/186798352-6fb85c7a-1b1d-4227-ba41-790051572824.png) 补充说明： 令牌失效日期是 2027/8/24，我设置了5年过期时间，倒退生成时间是 2022/8/24，也就是前两天升级到时候，即是升级 V2.25.0 的时候创建的，并不是 V2.23.0 的时候创建的，因为 V2.23.0使用了应该有一个月了。

从这张图显示，token还在有效期
