### ISSUE TITLE
[Bug]  开启OIDC的身份认证后，再开启MFA后，认证就会失败

### ISSUE THREAD

**Issue by cnn911** [jumpserver/jumpserver#8804]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.4

**浏览器版本**
google chrome 版本 104.0.5112.81

**Bug 描述**
先开启OIDC的身份认证，整体认证流程正常。再开启MFA后，认证流程走不通。

**Bug 重现步骤(有截图更好)**
1.  开启OIDC的身份认证并关闭其他认证方式 
![image](https://user-images.githubusercontent.com/18166072/186350412-df8f5533-1669-4b65-a3b3-c3163140fec8.png)
![image](https://user-images.githubusercontent.com/18166072/186350526-041bfa9d-668a-4028-a062-3d93a52c4e04.png)
2. 再开启MFA设置 
![image](https://user-images.githubusercontent.com/18166072/186350608-b06b291f-dfae-4060-8fd2-e9095b21fb36.png)
3. 然后普通用户进行认证，在点击“下一步”后，出现异常：
![image](https://user-images.githubusercontent.com/18166072/186350983-7c3b16a1-df7a-49e7-ba35-57e69993d7ca.png)
![image](https://user-images.githubusercontent.com/18166072/186351032-25f5be8d-6296-4d31-b57e-52ea09b51b79.png)

**Comment by cnn911** [comment]
@BaiJiangJie , 麻烦确认下是否是配置问题，还是已知bug？希望尽早回复下。

**Comment by jym503558564** [comment]
无法复现该问题，OIDC配置请参考文档：https://docs.jumpserver.org/zh/master/admin-guide/authentication/openid/?h=oidc

**Comment by cnn911** [comment]
@jym503558564 ,OIDC按照文档配置后是没有问题的。现在是在oidc配置成功后，再开启MFA，登录就会有问题，这个是不是MFA的配置或者bug导致的？具体配置可以看下我的bug重现步骤。

**Comment by cnn911** [comment]
@jym503558564  升级到v2.25.4版本后，MFA功能就没有问题了。

**Comment by jym503558564** [comment]
@cnn911  哪一个版本出现该问题的？

**Comment by cnn911** [comment]
> @cnn911 哪一个版本出现该问题的？

v2.21.4. 你们issuer模板第一行不就是要求要填版本号吗？

**Comment by cnn911** [comment]
> @cnn911 哪一个版本出现该问题的？

v2.21.4. 你们issuer模板第一行不就是要求要填版本号吗？

**Comment by cnn911** [comment]
> @cnn911 哪一个版本出现该问题的？

v2.21.4. 你们issuer模板第一行不就是要求要填版本号吗？

**Comment by jym503558564** [comment]
好的，我们测试一下该版本。

**Comment by jym503558564** [comment]
> > @cnn911 哪一个版本出现该问题的？
> 
> v2.21.4. 你们issuer模板第一行不就是要求要填版本号吗？

因为有一些用户填的版本和真实环境的版本不一致，我们需要确认一下。感谢理解～关于这个版本MFA的问题，我们会测试一下。
