### ISSUE TITLE
[Bug]  CSRF验证失败. 请求被中断.

### ISSUE THREAD

**Issue by AlliotTech** [jumpserver/jumpserver#8805]
2.24.2 -> 2.25.2 后出现csrf验证失败的错误

### 请求路径：
client -> 外部nginx(https )-> jumpserver (http 80)

### 部署方式
虚机环境 一键脚本

![image](https://user-images.githubusercontent.com/24980252/186391157-8aaf72d8-1ac6-4f46-8a85-a910753e3646.png)

2.24.2 是正常的

**Comment by wojiushixiaobai** [comment]
清理下浏览器缓存应该就解决了。暂时没法复现这个问题，如果问题依旧请提供 jumpserver core 组件日志

**Comment by AlliotTech** [comment]
```
server {
    listen 123 ssl http2;
    listen [::]:123 ssl http2;

    server_name a.com;

    ssl_certificate /1.pem;

    ssl_certificate_key privkey.pem;

    location / {

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        Upgrade            $http_upgrade;

        proxy_set_header        Connection            $connection_upgrade;

        proxy_set_header        Host            $http_host;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_pass http://192.168.2.200:80;

    }

```

root@debian:/opt/jumpserver/core/logs#  tail -f jumpserver.log  没有错误日志

root@debian:/opt/jumpserver/core/logs# tail -f gunicorn.log：
```
192.168.250.7 [01/Sep/2022:07:41:37 +0800] 0.021203s "POST /core/auth/login/ HTTP/1.0" 403 1016
```

**Comment by jym503558564** [comment]
清除下浏览器缓存，再试试看。未复现该问题

**Comment by AlliotTech** [comment]
> 清除下浏览器缓存，再试试看。未复现该问题

emmm , 前面提到过，无痕模式打开的，同时尝试更换过浏览器。  
2.24.2 正常，目前已回退。（2.25.3问题依旧）

**Comment by jym503558564** [comment]
@AlliotTech 微信企业社区群或者QQ群联系我们的人员，远程协助查看一下，目前我们无法复现该问题。

**Comment by AlliotTech** [comment]
解决了。。。
参考文档： 
https://docs.djangoproject.com/en/4.1/ref/settings/#secure-proxy-ssl-header
``` 
/opt/jumpserver/apps/jumpserver/settings/base.py
```
nginx需要新增一条配置： `proxy_set_header  X-Forwarded-Proto  $http_X_Forwarded_Proto; `

**Comment by wojiushixiaobai** [comment]
正常情况下不需要此配置才是，请参考官方文档正确配置

> 解决了。。。 参考文档： https://docs.djangoproject.com/en/4.1/ref/settings/#secure-proxy-ssl-header
> 
> ```
> /opt/jumpserver/apps/jumpserver/settings/base.py
> ```
> 
> nginx需要新增一条配置： `proxy_set_header X-Forwarded-Proto $http_X_Forwarded_Proto; `
