### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by jarvis-chenjw** [jumpserver/jumpserver#8807]
**请描述您的问题.**
安全扫描出现“检测到目标站点存在javascript框架库漏洞“的问题，请问这个有办法解决吗？
![image](https://user-images.githubusercontent.com/32596476/186556997-ae6b6721-511e-4b0c-8dbb-90df0f460b1a.png)

**Comment by jym503558564** [comment]
感谢反馈，我们开发人员跟进一下该问题。

**Comment by jym503558564** [comment]
该问题已修复，将在后续版本发布，请持续关注我们的版本发布情况，进行更新验证。
