### ISSUE TITLE
[Feature] Windows资产增加链接分享功能

### ISSUE THREAD

**Issue by leoyip** [jumpserver/jumpserver#8809]
**请描述您的需求或者改进建议.**
Linux有通过链接分享当前资产操作，Windows也有这块需求。
使用场景，比如有个问题乙方当前的技术支持人员搞不定，需要开发介入，但他们又不是在同一个城市，而我又不想开那么多堡垒机的用户，这时侯这功能就用得上了。类似Teamviewer多人同时控制一台终端。

**Comment by heatdrive** [comment]
即便是linux会话的分享也是需要通过认证的用户才能使用。堡垒机的原则是4A审计，所以“不想开那么多堡垒机的用户”需求是不成立的。windows的分享目前应该还有技术限制，未来是有希望实现的。
