### ISSUE TITLE
[Bug] OIDC用户通过sftp客户端连接堡垒机，提示connection lost

### ISSUE THREAD

**Issue by ba1dh3ad** [jumpserver/jumpserver#8812]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.25.0

**浏览器版本**
Chrome 104.0.5112.102

**Bug 描述**
OIDC用户通过sftp客户端连接堡垒机，会提示connection lost

**Bug 重现步骤(有截图更好)**
1.  使用密钥，通过sftp客户端连接堡垒机，cd到服务器目录时，提示connection lost
![图片](https://user-images.githubusercontent.com/84117046/186802931-4cbea987-dc07-4502-a804-1b475d658bcc.png)

2. 使用用户名密码登录堡垒机的用户不会出现这个问题。

**Comment by LeeEirc** [comment]
贴下 koko 的对应的报错日志  `docker logs -f jms_koko --tail=100`
