### ISSUE TITLE
[Question] 云端唤醒& windows鼠标/键盘 失效

### ISSUE THREAD

**Issue by aqqwiyth** [jumpserver/jumpserver#8813]
请问 #6549 云端唤醒是解决什么场景下的问题?  

另外我们当前使用 jumpserver 过程中遇到一个问题. 
场景1.  使用jumpserver安装了向日葵软件之后, 只要jumpserver退出,向日葵就无法被连接
场景2.  使用3389远程安装向日葵正常, 登录过jumpserver之后退出, 向日葵无法打开.

**Comment by ibuler** [comment]
向日葵需要有在线会话支持，我之前遇到过，关闭屏幕就不行了

**Comment by aqqwiyth** [comment]
@ibuler 这种情况下就会出现   在jumpserver退出之后 鼠标/键盘 模拟操作就失效.   比如常见的按键精灵, 连点模拟器之类的. 

必须用tscon.exe退出会话 
 参考 : https://blog.csdn.net/cz1098564315/article/details/86712128

**Comment by jym503558564** [comment]
感谢反馈～
我们会关注是否很多用户遇到该问题。
