### ISSUE TITLE
[Question] 新版本容器系统时区问题

### ISSUE THREAD

**Issue by heatdrive** [jumpserver/jumpserver#8814]
**请描述您的问题.**
当前新版本各容器的系统时区设置，除了mysql（mariadb）应该都是保持和主机一致，只有mysql选择了UTC时区。
请问这么规划的设计思路，mysql选择UTC是有什么特殊的意图或是限制？

当前版本2.23.4

**Comment by wojiushixiaobai** [comment]
mysql 是使用的官方镜像，未作改动。
