### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by superwilliamlove** [jumpserver/jumpserver#8815]
**浏览器版本**
Google Chrome 版本 103.0.5060.134（正式版本） （64 位）

**Bug 描述**
点击主页图标返回仪表盘页面的时候，经常响应速度会很慢，然后刷新又恢复可以正常回到仪表盘

**Bug 重现步骤(有截图更好)**
1.  在其他页面点击图标回到仪表盘页面
![EGYSiGwNKK](https://user-images.githubusercontent.com/77044309/186870472-e8513b60-9179-403b-9ed7-c803f759c70b.jpg)
2.点击其他页面是正常的

**Comment by ibuler** [comment]
是有这么个问题
