### ISSUE TITLE
[Question] MySQL应用数据库管理

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#8818]
MySQL 数据库应用管理是不是只支持一个database？
是否支持整个实例级别的数据库管理？
比如，mysql有a,b,c三个库，但是通过我们的数据库应用只能写a或b或c，使用*或a,b的方式指定数据库是不行的。
请问这个功能当前是不支持么？
Jumpserver version：2.25.1

**Comment by songchaoqiang** [comment]
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/109948570/187177012-23f6fb48-ae84-4447-9fcd-e92d82708f23.png">
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/109948570/187177178-aebb790c-909f-4bd2-b682-eb846e07854e.png">

mysql、redis创建操作都是这样的要求

**Comment by ibuler** [comment]
默认数据库，进去可以切换

**Comment by songchaoqiang** [comment]
ok，我试试

**Comment by songchaoqiang** [comment]
Jumpserver version：2.25.1，社区版
部署方式：k8s helm
redis 的访问端口63790看起来没有在任何服务暴露，如果需要暴露端口的话是在koko的service服务上加一个port吗？

**Comment by songchaoqiang** [comment]
截图如下
<img width="770" alt="image" src="https://user-images.githubusercontent.com/109948570/187421822-e3f779b7-19c2-499a-bcdb-742c62d2d997.png">
目前这个版本看起来SSH和mysql是暴露了的，但是没有redis的端口

**Comment by wojiushixiaobai** [comment]
等待 jumpserver/helm-charts#101 的合并，预计下个版本修复
