### ISSUE TITLE
[Bug] window打开内网特定的网页时整个windows远程桌面就卡了

### ISSUE THREAD

**Issue by simplove** [jumpserver/jumpserver#8819]
**JumpServer 版本(v2.5.2)**
**浏览器版本**
版本 104.0.5112.102（正式版本） （64 位）

**Bug 描述**
通过jumpserver网页远程windows,在访问内网的某一个网页的时候，整个windows界面就变得特别卡，什么也操作不了。
但是通过微软自带的远程桌面工具远程那台windows,访问同一个网页，不会出现卡顿。
初步怀疑是那个网页调用了一些插件和jumpserver自带的录屏功能相冲突导致的。
![This is an image](https://s3.bmp.ovh/imgs/2022/08/30/966f0d23b6c9d1d9.png)

请问这种情况要如何处理？
还需要我提供一些什么东西，网页是内网部署的，无法在公网上展示。

**Comment by wojiushixiaobai** [comment]
版本是 v2.5.2？试试我们的新版看看

**Comment by simplove** [comment]
> 版本是v2.5.2吗？试试我们的新版看看
打错了。。。是最新版本
Version v2.25.2

**Comment by jym503558564** [comment]
@simplove 该问题每次必现吗？每次卡顿多久？

**Comment by simplove** [comment]
> @simplove 该问题每次必现吗？每次卡顿多久？

是的，每次必卡，只要一打开那个网页就必卡。无论是用chrome，还是用IE都卡。
本来那个网页要是用IE的，因为它要安装一些组件，里面的内容才可以正常显示

**Comment by jym503558564** [comment]
@simplove  除了打开这个网页会卡，还有其他网页会发生卡顿吗？可否远程协助查看？我们开发人员安排合适的时间远程协助查看，排查一下情况？

**Comment by simplove** [comment]
> @simplove 打开这个网页会卡，还有其他网页会发生卡吗？可否远程协助查看？

打开其它任何网页都不会，可以远程查看。怎么联系你们

**Comment by jym503558564** [comment]
@simplove 您在企业微信群里联系一下我们开发人员：李智

**Comment by simplove** [comment]
已联系到相关的支持人员。
问题找到了，由于那个网页的首页有大图片和一些动画很吃带宽资源，而本身的远程方式是通过frp内网穿透的方式实现的，所用的腾讯云服务器带宽只有5M，所以会卡。
在测试纯内网的环境中情况要好很多。
这个issue可以关闭了，谢谢。
