### ISSUE TITLE
用最新的jumpserver安装，是否没法用docker安装了

### ISSUE THREAD

**Issue by zhouyanpei** [jumpserver/jumpserver#882]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
Jumpserver 0.4.0

##### 问题复现步骤
1. 下载了最新的Jumpserver后，没有docker-compose文件了，是否没法再用docker安装了？

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
手动创建一个，版本改成最新的试试。
可以参考https://zqiannnn.github.io/jumpserver-ansible/
