### ISSUE TITLE
[Question]  通过nginx代理服务后访问资产控制台 提示 Connection websocket error

### ISSUE THREAD

**Issue by rainsunset** [jumpserver/jumpserver#8820]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/26954709/187508170-200c26a5-f2c1-4f35-aba8-50b427006892.png)

网络结构：
堡垒机部署在：77.15 和 77.16 上，用77.12做Haproxy负载均衡 , 然后用77.11(eth0)上的nginx做反向代理(port:80 server_name: jump.domain  -> 77.12)
77.11(eth0)这个设备的另一张网卡ip为31.1.11(eth1)   

场景：
在ip为31.1.100的设备上用jump.domain可以访问到堡垒机机页面，但是进入资产控制台时提示  Connection websocket error
在ip为77.10的设备上用 77.12是可以正常访问到堡垒机页面，并且进入到资产控制台的

请问我还需要增加什么配置？盼复

**Comment by wojiushixiaobai** [comment]
- [多层 nginx 反向代理](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)

**Comment by rainsunset** [comment]
谢谢  已解决
