### ISSUE TITLE
[Bug] 审计系统无法记录，使用终端上传文件后的操作命令

### ISSUE THREAD

**Issue by cw731** [jumpserver/jumpserver#8821]
通过终端和和网页终端测试 都存在这种现象。怕有人恶意通过上传文件来逃避监管。

1.
![image](https://user-images.githubusercontent.com/49554722/187578927-f4172f7f-3206-4daf-a803-958d50414b85.png)
![image](https://user-images.githubusercontent.com/49554722/187579035-65dc8464-fbee-4962-945a-9c57a1d90d71.png)

2. 
3.

**Comment by cw731** [comment]
jumpserver 版本 ：Version v2.24.2 GPLv3.

**Comment by wojiushixiaobai** [comment]
录像里面不会漏，命令记录我们研究下看能不能优化

**Comment by LeeEirc** [comment]
能否使用 v2.25 版本测试下，有对 rz 上传之后的录像遗失问题优化。
