### ISSUE TITLE
[Question] 无法通过隐性url 来访问服务

### ISSUE THREAD

**Issue by rainsunset** [jumpserver/jumpserver#8826]
**请描述您的问题.**
域名配置：
jump.doman.cn  策略A 指向jumpserver所在服务器ip
jumps.doman.cn   策略：隐性url 指向http://jump.doman.cn:8011   
![image](https://user-images.githubusercontent.com/26954709/187754049-889a4944-32ce-4860-a5f5-9a9cd1142d39.png)

问题：
无法通过 http://jumps.doman.cn  来访问服务
![Snipaste_2022-09-01_02-25-43](https://user-images.githubusercontent.com/26954709/187754203-5b4019b7-8c31-48a5-8b46-48d111c13639.png)

但是可以通过 http://jump.doman.cn:8011 来访问服务
![Snipaste_2022-09-01_02-28-44](https://user-images.githubusercontent.com/26954709/187754315-9d774672-d821-40c4-84b7-d131b6470dd8.png)

nginx配置如下
```
server {
  listen  80;
  server_name  jump.doman.cn;
  add_header Strict-Transport-Security "max-age=63072000" always;
  client_max_body_size 4096m;  # 录像及文件上传大小限制

  location / {
      proxy_pass http://192.168.77.12; #代理地址
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Port $server_port;

      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_request_buffering off;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
  }
}
```

请问我需要增加什么配置才可以使用隐性url访问服务？🤔

**Comment by wojiushixiaobai** [comment]
CNAME 用法错误。
CNAME 无法完成重定向，请通过反向代理配置
