### ISSUE TITLE
关于资产管理权限的疑问

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#8828]
场景是这样的：我希望某个用户组（或某些用户），只能看到指定节点下的资产，并发起类似新增修改一类的维护。而现在的角色不管我怎么配置，要么就所有节点下的资产都能操作，要么就全部都无法查看/维护。是我不会配置还是不支持？是否能改进？

**Comment by jym503558564** [comment]
没明白什么意思？可否截图描述再一下？

**Comment by jym503558564** [comment]
我目前我们还不支持权限位精确到指定到某个节点的权限
