### ISSUE TITLE
Jumpserver 0.5.0 资产授权用户及用户组是否二选一

### ISSUE THREAD

**Issue by qiushaohu** [jumpserver/jumpserver#883]
[简述你的问题]
资产授权用户及用户组是否二选一

##### 使用版本
Jumpserver 0.5.0

##### 问题复现步骤
1. [步骤1]
权限管理 -- 资产授权 -- 创建授权规则
2. [步骤2]
**选用用户组，没有选用户，提交的时候提示需要选用户**

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/34025457/34515373-c7eb5e76-f0ac-11e7-92bd-bff5f87bce86.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已经修复了

**Comment by qiushaohu** [comment]
@ibuler  哥，我如何更新

**Comment by ibuler** [comment]
git pull

**Comment by qiushaohu** [comment]
@ibuler  thanks
