### ISSUE TITLE
用户列表里面不能展示部分ldap同步的用户[Bug] 

### ISSUE THREAD

**Issue by QHxiang** [jumpserver/jumpserver#8830]
**JumpServer 版本(v1.5.9以下不再支持)**

jumpserver版本2.11
**浏览器版本**

**Bug 描述**
web页面，用户列表中部分ldap同步用户数据丢失，资产授权不能够授权给那部分丢失的用户，已经查看过数据库，数据库用户表是能够查到丢失的用户的

**Bug 重现步骤(有截图更好)**
1.  这个页面找不到用户
![image](https://user-images.githubusercontent.com/21072348/187856178-2f323f54-a214-4d1b-8e48-4929fc4800e9.png)

2. 资产授权不能够选择未展示的用户
![image](https://user-images.githubusercontent.com/21072348/187856330-d38fa37e-3a85-4faa-a6d3-ccfb25a03169.png)

3. 数据库里面查看用户是正常的
![image](https://user-images.githubusercontent.com/21072348/187856768-ac885612-3eca-460b-ba6c-65260233614d.png)

**Comment by jym503558564** [comment]
同步后，在用户列表看不见LDAP用户？刷新一下浏览器呢？

**Comment by QHxiang** [comment]
尝试过了，没有用

**Comment by jym503558564** [comment]
导入过程中，没有报错信息？都是成功的？

**Comment by QHxiang** [comment]
我手机号15206115285，方便加个微信看下吗

**Comment by jym503558564** [comment]
经我们研发人员初步诊断，在旧版本看你存在该问题，建议先升级至最新版本，再进行同步设置一下。

**Comment by QHxiang** [comment]
同步时这个地方一键导入吗
![image](https://user-images.githubusercontent.com/21072348/187871893-f8ed9235-b0d7-41ae-ba06-73c72f076579.png)

**Comment by QHxiang** [comment]
我们曾经升级过到新版本2.24.但是由于用户使用习惯问题，作了回退处理，在2.24版本里面我们有测试过我们不存在的用户，和现有情况一样，依旧存在用户不显示问题，且不能对这部分用户进行授权

**Comment by jym503558564** [comment]
升级至2.24后，有重新进行同步吗？

**Comment by QHxiang** [comment]
同步是我刚刚说的那个地方一键导入吗

**Comment by jym503558564** [comment]
> 同步是我刚刚说的那个地方一键导入吗
是的

**Comment by QHxiang** [comment]
升级到新版本后未作同步，能麻烦说下现在这个版本是什么原因会导致部分用户不能展示情况吗

**Comment by jym503558564** [comment]
同步时未设置上组织，可能存在游离组织，导致用户列表看不见。目前猜测旧版本可能是这个问题

**Comment by jym503558564** [comment]
查看 orgs_organization_members 表里的 Default 组织关联的用户 id 是否存在

**Comment by QHxiang** [comment]
你活的这个是新版的数据库表把，我们现在2.11版本里面是没有这个表的

**Comment by QHxiang** [comment]
这个是我在2。14版本里面看到的你们修复的问题，是我所说的问题吗
![image](https://user-images.githubusercontent.com/21072348/187877049-2d420e1a-0269-45e6-a279-60b175b9603c.png)

**Comment by jym503558564** [comment]
v2.12我们修复过一个LDAP的问题。但是您这边如果不方便升级至最新版本，也可以升级至v2.13.2进行测试。

**Comment by QHxiang** [comment]
orgs_organization_members这个表里面确实没有未展示的用户id，如果我们想要补数据的话，是只更新这个表就可以吗？这个表里面的第一个字段id是有什么关联关系吗

**Comment by QHxiang** [comment]
我通过数据库的表关系里面没有关于orgs_organization_members这个表里面的id字段的关联关系，我们只需要保证这个id是唯一字符串就可以吗

**Comment by jym503558564** [comment]
是 Default 组织关联的“用户 id ”是否存在

**Comment by QHxiang** [comment]
users_user表是有用户数据，orgs_organization_members表里面没有未展示用户的用户的关联信息

**Comment by QHxiang** [comment]
我们这边先去尝试下插入数据试试，今天给您添麻烦了，谢谢

**Comment by jym503558564** [comment]
建议备份数据库，先进行升级至临近版本进行测试。

**Comment by QHxiang** [comment]
使用一键导入功能后，我们数据库里面users_user表里面丢失了部分用户，但是丢失的这部分用户仍然可以登录jumpserver登录，能麻烦问下是什么原因导致的吗

**Comment by jym503558564** [comment]
> 使用一键导入功能后，我们数据库里面users_user表里面丢失了部分用户，但是丢失的这部分用户仍然可以登录jumpserver登录，能麻烦问下是什么原因导致的吗

这个问题上面回复过了，您当前版本确实存在这个问题。建议升级至新版本，我们在v2.12修复过该LDAP导入的问题。

**Comment by jym503558564** [comment]
@QHxiang 该问题能解决不？

**Comment by QHxiang** [comment]
暂时还未进行升级，排期是安排这俩周进行升级

**Comment by jym503558564** [comment]
> 暂时还未进行升级，排期是安排这俩周进行升级

好的，如有问题，可再次联系我们。

**Comment by QHxiang** [comment]
![image](https://user-images.githubusercontent.com/21072348/188774160-847dbc24-f173-45d3-99b5-9abbb71a44d2.png)
这个我在源码里面找到的，麻烦问下orgs_organization_members这个表里面id这个字段的数值，是基于uuid4生成的32位唯一id吗

**Comment by jym503558564** [comment]
好的，如有问题，可再次联系我们。

**Comment by QHxiang** [comment]
非常感谢，我们版本升级后确实解决了用户列表看不到和资产无法授权问题，另外想请教下，账号异地登录邮件提醒功能，可以自己配置模板吗？还是只有创建账号可以自己设置邮件模板？

**Comment by jym503558564** [comment]
异地登录邮件提醒，目前无法自定义配置模版。

**Comment by jym503558564** [comment]
如还有其他问题，可再次提Issues。感谢持续关注JumpServer。
