### ISSUE TITLE
[Question] Redis Cli连接报错

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#8832]
使用web终端可以正常连接，但是使用cli会报出如下错误。
redis-cli -h xxxxx -p 63790 -a xxxxxx@xxxxxxxxx
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.

I/O error
xxxxxx:63790>

**Comment by jym503558564** [comment]
端口是否有正常暴露？
附上Magnus连接失败的报错日志信息

**Comment by songchaoqiang** [comment]
正常暴露，telnet没有问题

**Comment by songchaoqiang** [comment]
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/109948570/187883255-480b163e-cbc0-4a94-b6c4-2d3dbfd9d77d.png">

**Comment by songchaoqiang** [comment]
使用cli在本地连接mysql也是可以的

**Comment by jym503558564** [comment]
该redis是否没有配置用户名或密码

**Comment by songchaoqiang** [comment]
redis没有用户和密码，从web cli连接的时候，出现password是直接回车就可以连接成功的

**Comment by songchaoqiang** [comment]
我看到之前好像也有小伙伴提过类似问题，是不是当前版本暂未修复？
https://github.com/jumpserver/jumpserver/issues/8764

**Comment by jym503558564** [comment]
目前最新版本存在该问题，我们后续会修复

**Comment by jym503558564** [comment]
@songchaoqiang 最新版本已修复该问题，可升级至最新版本进行测试

**Comment by songchaoqiang** [comment]
最新版本是指哪一个版本呢，麻烦您列一下helm chart和镜像版本。

**Comment by jym503558564** [comment]
v2.26版本已修复。

**Comment by songchaoqiang** [comment]
已验证
