### ISSUE TITLE
magnus连接超时问题

### ISSUE THREAD

**Issue by laodengto** [jumpserver/jumpserver#8834]
JumpServer 版本：2.24.2
会话连接过期时间设置14400 秒、
<img width="375" alt="80d82fd58337bbdf4eb907f31b20f30" src="https://user-images.githubusercontent.com/49049414/188077252-941047af-2d39-452c-91c2-2e7f62872a65.png">
MySQL 的系统用户是手动输入密码，

在使用 Navicat 正常连接到 MySQL  之后操作过程会中断如下图：
在连接成功之后使用一段时间，后点击查询
![18884d8d2ce31e5b4fa615b882578dd](https://user-images.githubusercontent.com/49049414/188113166-9d2e565f-1faa-4c71-b722-03b4efb69e31.jpg)

<img width="342" alt="4fead914a1696cedb2aae3f415a84c7" src="https://user-images.githubusercontent.com/49049414/188083604-3160cb1c-f5bc-40d8-9c9a-0c1923c2d12b.png">
MySQL 的系统用户使用托管密码是正常连接 

托管密码，和手动输入密码，使用db client走的代码逻辑是不是不一样的？

**Comment by BaiJiangJie** [comment]
v3 版本应该解决了这个问题，建议升级使用。
