### ISSUE TITLE
Nginx反向代理堡垒机后登录Windows资产经常有WebSocket问题

### ISSUE THREAD

**Issue by 993639542** [jumpserver/jumpserver#8835]
**JumpServer 版本(v2.21.4)**

**浏览器版本**
Google  104.0.5112.102

**Bug 描述**
各位大佬好， 我们刚开始部署的时候没有将证书存放在堡垒机上，前面走了一层Nginx反向代理。但是登录Windows服务器WebSocket问题一直存在，Nginx反代时已经配置了WebSocket配置的，此问题已困扰小弟良久，烦请大佬们指点迷津，感恩！

**Bug 重现步骤(有截图更好)**
1.  出现WebSocket截图
![image](https://user-images.githubusercontent.com/71875924/188349762-9a8b1cd1-2cd8-44c8-99e8-5fdd82c608ae.png)
2. 正常请求WebSocket截图
![image](https://user-images.githubusercontent.com/71875924/188349847-f8cf854b-13cb-45d5-8b2b-f529fb92f343.png)
3.Nginx反代配置截图
![image](https://user-images.githubusercontent.com/71875924/188349884-83c43f0a-f272-4876-807e-0d5200a8db39.png)

**Comment by wojiushixiaobai** [comment]
参考下面文档
- [多层 nginx 反向代理⚓︎](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)

```nginx
server {
    listen 80;
    server_name demo.jumpserver.org;  # 自行修改成你的域名
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name          demo.jumpserver.org;  # 自行修改成你的域名
    ssl_certificate      sslkey/1_jumpserver.org_bundle.crt;  # 自行设置证书
    ssl_certificate_key  sslkey/2_jumpserver.org_bundle.key;  # 自行设置证书
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_protocols TLSv1.1 TLSv1.2;
    add_header Strict-Transport-Security "max-age=63072000" always;

    client_max_body_size 4096m;  # 录像及文件上传大小限制
    location / {
        # 这里的 ip 是后端 JumpServer nginx 的 ip
        proxy_pass http://192.168.244.144;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

**Comment by 993639542** [comment]
大佬好，我找了几个疑似的会话，因为是开发同事反馈的，我这边没查到它对应的会话ID，并且我这边复现失败了。
![image](https://user-images.githubusercontent.com/71875924/188408272-b14ced74-cb01-4d2c-8c09-3b367b407f9d.png)

**Comment by 993639542** [comment]
如果这看不出什么，烦请大佬列一下此前别的小伙伴们出现类似的问题又可能是因为什么原因呢

**Comment by wojiushixiaobai** [comment]
直连应该不会，看看是不是过了 vpn 或者使用了代理之类的。
