### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by levywang** [jumpserver/jumpserver#8836]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.23.0

**浏览器版本**
chrome 89.0.4389.90

**Bug 描述**
更新版本后，web终端资产搜索框icon太小，容易误触，且旁边的资产框也容易折叠起来，没有老版本好用，建议优化一下。

**Bug 重现步骤(有截图更好)**
1.  点击搜索图标
2. 输入ip搜索机器，很容易误触

![image](https://user-images.githubusercontent.com/16538263/188424726-0f1f9b72-b4ec-44b1-b069-01732276a8e1.png)

**Comment by jym503558564** [comment]
目前大部分用户使用暂无反馈该问题，我们研发人员会继续关注用户使用体验问题，如有更多用户提出反馈意见，我们会进行优化。感谢反馈～
