### ISSUE TITLE
[Question] mysql命令行展示不完整

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#8838]
**请描述您的问题.**
版本：2.20.1
docker部署
mysql：5.7
登录 mysql 之后，输入的命令如果比较长，使用上键展示历史命令的时候显示不完整
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/39855929/188638818-acb48ad7-70d9-44c9-8e23-15863a4200b2.png">
这个是否是展示时候的bug呢？是否可以配置展示的模式？

**Comment by LeeEirc** [comment]
jms版本？如何部署的？mysql 资产的版本？

**Comment by lf-zhang** [comment]
> jms版本？如何部署的？mysql 资产的版本？

版本：2.20.1
docker部署
mysql：5.7

**Comment by jym503558564** [comment]
建议升级至最新版进行测试，最近版本目前没有这个问题。
