### ISSUE TITLE
ssh方式登录无法播放回放

### ISSUE THREAD

**Issue by aaronchou0** [jumpserver/jumpserver#884]
[简述你的问题]

##### 使用版本
[Jumpserver版本 0.3.2 ]

##### 问题复现步骤
1. 使用ssh登录，操作
2. 断开后无法查看回放

##### 具体表现[截图可能会更好些,最好能截全]
点击回放后弹出播放界面，但节目上只有光标闪烁，无其他任何信息，而且显示的总时间为0
![image](https://user-images.githubusercontent.com/15139155/34547171-40466ef6-f134-11e7-82a0-41f5dac4d2e6.png)

##### 其他
web登录监控和回放都可以查看
ssh登录仅可查看监控，无法查看回放

**Comment by liuzheng** [comment]
应该是你的操作数据过大导致的，请问该回放是否包含cat大文件和tail监控文件变化

**Comment by aaronchou0** [comment]
没有操作过任何大数据，只要是ssh方式登录的都无法查看回放。

**Comment by aaronchou0** [comment]
@liuzheng 没有操作过任何大数据，只要是ssh方式登录的都无法查看回放。

**Comment by liuzheng** [comment]
能否将浏览器console的报错截图给我？
@aaronchou0

**Comment by aaronchou0** [comment]
console没有报错，没任何输出，后台日志级别开到debug也没有打任何日志。。。@liuzheng

**Comment by aaronchou0** [comment]
console开到verbose有了 
图传不上来，给你发文字吧
layer.js:2 [Violation] Avoid using document.write().
f.close @ layer.js:2
a @ layer.js:2
dispatch @ jquery-2.1.1.js:3
r.handle @ jquery-2.1.1.js:3
term.js:6092 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ term.js:6092
Terminal.bindMouse @ term.js:1416
Terminal.open @ term.js:1024
(anonymous) @ record.js:124
(anonymous) @ angular.min.js:80
(anonymous) @ angular.min.js:112
$eval @ angular.min.js:126
$digest @ angular.min.js:123
$apply @ angular.min.js:126
l @ angular.min.js:81
M @ angular.min.js:85
F.onload @ angular.min.js:86
term.js:6092 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by aaronchou0** [comment]
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952    term.js:6092  
@liuzheng

**Comment by liuzheng** [comment]
唉，又是layer.js 问题。。。麻烦尝试使用最新版的吧

**Comment by aaronchou0** [comment]
这个不升级能解决不，新版本感觉问题上好像更多吧

**Comment by liuzheng** [comment]
试一下新版本的coco和Luna，可能可以解决
