### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by shenwxopen** [jumpserver/jumpserver#8841]
**获取主机硬件信息报错**
PLAY [Update assets hardware info: ['Dac-jumpserver']] ******************************************************************************************************************************************************

TASK [setup] ************************************************************************************************************************************************************************************************
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ops.ansible.callback.AdHocResultCallback object at 0x7f3554d360d0>):
'show_task_path_on_failure'

PLAY RECAP **************************************************************************************************************************************************************************************************
Dac-jumpserver             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2022-09-07 16:13:53 [gather_asset_hardware_info ERROR] Get asset info failed: Dac-jumpserver
Get asset info failed: Dac-jumpserver
Task assets.tasks.gather_asset_hardware_info.update_assets_hardware_info_manual[895a1678-73b9-4c02-be29-58fa8b107541] succeeded in 0.19517175003420562s: None

**Comment by jym503558564** [comment]
哪个版本？
