### ISSUE TITLE
COCO相关一些小问题

### ISSUE THREAD

**Issue by Nidhoggur1993** [jumpserver/jumpserver#885]
[简述你的问题]

##### 使用版本
0.5.0

##### 问题复现步骤
1.git clone coco之后修改conf.py的内容并不能传到jms的web内，而是继续使用默认的APP_NAME和SSHD_PORT

2.在jms的web内删除coco后再python run_server.py会提示Access key is not valid

3.希望coco的日志级别可调，目前日志里会一直刷新DEBUG信息 

> [connectionpool DEBUG] http://127.0.0.1:8080 "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2

##### 具体表现[截图可能会更好些,最好能截全]
1.![image](https://user-images.githubusercontent.com/12947582/34553849-adf8074a-f164-11e7-9ed2-848e4cdfda75.png)

2.![image](https://user-images.githubusercontent.com/12947582/34553649-a8af10fe-f163-11e7-9893-79bfa7ce50b4.png)

3.![image](https://user-images.githubusercontent.com/12947582/34553906-ffab16ea-f164-11e7-9715-d2341667aa5b.png)

##### 其他
附件是coco日志和jms日志
[coco.log](https://github.com/jumpserver/jumpserver/files/1602703/coco.log)
[jumpserver.log](https://github.com/jumpserver/jumpserver/files/1602704/jumpserver.log)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1.git clone coco之后修改conf.py的内容并不能传到jms的web内，而是继续使用默认的APP_NAME和SSHD_PORT

第一次注册时才会使用 APP_NAME，也只是一个标示，SSHD_PORT是coco启动监听的端口，每次更改必然会变，但是不会更新注册时的

2.在jms的web内删除coco后再python run_server.py会提示Access key is not valid

删除对应的 acces_key文件，rm -f kes/.access_key

3.希望coco的日志级别可调，目前日志里会一直刷新DEBUG信息

[connectionpool DEBUG] http://127.0.0.1:8080 "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2

    # 设置日志级别 ['DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', 'CRITICAL']
    # LOG_LEVEL = 'INFO'
