### ISSUE TITLE
luan页面异步加载资产树设置为否，资产树刷新无效，不会收缩资产树列表[Bug] 

### ISSUE THREAD

**Issue by Primeyang** [jumpserver/jumpserver#8850]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.25.1

**浏览器版本**
Microsoft Edge
版本 105.0.1343.27 (正式版本) (64 位)

**Bug 描述**
luan页面异步加载资产树设置为否，资产树刷新无效，不会收缩资产树列表

**Bug 重现步骤(有截图更好)**
1.  web终端页面
2. 设置异步加载资产树
3. 展开多个资产树
4. 刷新资产树，不会收缩资产树列表

**Comment by jym503558564** [comment]
需要刷新浏览器

**Comment by Primeyang** [comment]
刷新浏览器也不会收缩资产树，需要切换异步加载资产树是和否，然后在刷新浏览器才可以收缩

**Comment by Primeyang** [comment]
之前的版本是可以在luan页面 《《我的资产》》位置刷新就可以

**Comment by huailei000** [comment]
https://github.com/jumpserver/luna/pull/696

**Comment by jym503558564** [comment]
已修复，请及时关注我们的版本发布，进行更新。
