### ISSUE TITLE
[Bug] LDAP无法设置成功

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#8854]
**JumpServer 版本(v1.5.9以下不再支持)**
2.25.2

**浏览器版本**
edge 105.0.1343.33

**Bug 描述**
无法设置成功LDAP认证。我在老版本2.5.3里面，用相同的配置项，是可以配置成功的。

**Bug 重现步骤(有截图更好)**
1.  ![image](https://user-images.githubusercontent.com/22488813/189796060-e5273b5a-1ccb-4e0a-96b5-38cb7fde61bd.png)
2. 点击提交，报错：Internal server error
3. ![image](https://user-images.githubusercontent.com/22488813/189796839-1109e8a1-39ae-4266-86a9-24d04b960cef.png)

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/190313789-e63efe8e-5101-4840-8316-b27b8f0c9a73.png)
同步设置关闭或者修正 `* * * * *`

**Comment by rty813** [comment]
无法关闭定时执行，关闭的时候还是报相同的错误：
![image](https://user-images.githubusercontent.com/22488813/190402211-d6f834f5-a27a-4284-bd15-a1f02024de56.png)

**Comment by wojiushixiaobai** [comment]
从配置文件 /opt/jumpserver/config/config.txt 移除相应的配置，如果配置文件不存在该设置
请从数据库 settings_setting 表里面移除

**Comment by rty813** [comment]
> 

从数据库中删除对应项目，然后jmsctl --restart重启后现在好了，感谢。
