### ISSUE TITLE
日志实时监控存在安全问题

### ISSUE THREAD

**Issue by jsp777** [jumpserver/jumpserver#886]
日志实时监控通过websocket接口去监控文件变化，URL是这样的形式：
`ws://ip/ws/monitor?file_path=/opt/jumpserver/logs/tty/20180104/{username}_{system}_161554`
问题来了，这里file_path参数是绝对路劲，那么用户可以自己篡改file_path路劲监听其它以.log结尾的文件，比如监听/opt/jumpserver/logs/jumpserver.log：
![image](https://user-images.githubusercontent.com/35052331/34555400-92709142-f16c-11e7-8a64-bdb8cce6ea34.png)
要知道jumpserver是以root权限运行的，那么可能导致某些敏感log文件被堡垒机管理员看到，不是啥好事（堡垒机管理员和堡垒机系统运维很有可能不是一个人）
请至少判断file_path的路劲是否符合常规，最好就是把file_path弄到数据库里，从数据库里读，这样用户无法控制file_path

##### 使用版本
Jumpserver版本0.3.2

##### 问题复现步骤
直接修改html代码中的file_path，再打开监控

##### 其他

[注:] 完成后请关闭 issue

**Comment by jsp777** [comment]
define file_monitor那里我加了判断先临时规避这个问题：
`def file_monitor(path='.', client=None):
    wm = WatchManager()
    mask = IN_DELETE | IN_CREATE | IN_MODIFY
    notifier = AsyncNotifier(wm, EventHandler(client))
    wm.add_watch(path, mask, auto_add=True, rec=True)
    if not os.path.isfile(path):
        logger.debug("File %s does not exist." % path)
        sys.exit(3)
    elif not os.path.realpath(path).startswith(os.getcwd() + '/logs/tty'):
        logger.debug("Illegal File %s" % path)
        sys.exit(3)
    else:
        logger.debug("Now starting monitor file %s." % path)
        global f
        f = open(path, 'r')
        st_size = os.stat(path)[6]
        f.seek(st_size)`

**Comment by liuzheng** [comment]
我们正在解决这个问题，我们的方案是每次监控生成临时的token，然后由后端校验后再给出数据

很感谢给出security的建议，这个issue我先关了
