### ISSUE TITLE
[Bug] web远程windows的时候，托管密码不会自动填充

### ISSUE THREAD

**Issue by qxtalk** [jumpserver/jumpserver#8861]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.14 以上版本

**浏览器版本**
谷歌
Edge

**Bug 描述**
V2.14 以上版本windows资产，web远程的时候，托管密码不会自动填充，只显示其他用户，填入了用户名，没有密码。
同样的windows服务器或终端，使用以下版本，V2.13.2  都是正常的，可以直接远程进入

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/37611306/190074956-370fdbcc-9eff-4f70-8258-7c8441aa21c9.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
资产系统平台选择 windows，勿选择 windows 2016。
资产远程设置勾选 （要求设备使用网络级别身份验证连接）NLA

**Comment by qxtalk** [comment]
> 资产系统平台选择 windows，勿选择 windows 2016。 资产远程设置勾选 （要求设备使用网络级别身份验证连接）NLA
> 
> 可以自行登录 [演示](https://demo.jumpserver.org) 网站验证

在测试版本中，V2.13和V2.14版本以上资产选择的都是windows

**Comment by qxtalk** [comment]
测试为V2.14版本后rdp方式连接改变。服务器安装有ESET Server Security无法通过，卸载后可以，测试把ESET Server Security所有功能禁用或者添加排除、白名单仍无效，只能忍痛使用老版本v2.13.2来连接windows资产。希望博主后期增加旧平台连接方式，增加2.13 RDP方式到新版本中来供选择。

**Comment by wojiushixiaobai** [comment]
[apache/guacamole-server](https://github.com/apache/guacamole-server) 行为的变更，jumpserver 不处理
