### ISSUE TITLE
[Question] core服务启动失败

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#8863]
使用k8s helm部署jumpserver
jumpserver版本: v2.25.4
k8s版本: 1.22
mysql: 5.7.34
redis: 6.2

core服务启动后日志卡住不输出，然后容器直接重启，从pod中查看日志也没有信息
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/109948570/190129673-ce9c6c67-3e80-40c3-b9e6-bec2fcb06b07.png">

**Comment by songchaoqiang** [comment]
开启debug模式也看不到任何新的日志输出，进入pod后模拟执行./entrypount.sh start web也是卡死，但如果手动ctrl+c，就会往下正常执行，这会是什么问题？
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/109948570/190138386-3c55f3bb-a012-469f-a937-d98bf5a183f4.png">

**Comment by wojiushixiaobai** [comment]
静态文件拷贝，你的存储写入慢导致卡住了。

**Comment by songchaoqiang** [comment]
有没有可能是因为我使用aws elaticcache启用了1分区3节点的原因导致？
昨天我尝试改为1分区1节点就很快。

**Comment by songchaoqiang** [comment]
如果是因为启用了多可用的问题的话，有没有什么解决办法？
毕竟生产环境还是希望能够使用多个节点保障可用性

**Comment by wojiushixiaobai** [comment]
我不清楚 aws elaticcache 的用途，高可用直接启动多个副本即可

**Comment by songchaoqiang** [comment]
我是指底层数据服务的高可用，aws elaticcache其实就是redis

**Comment by wojiushixiaobai** [comment]
redis 集群的话提供的应该是 vip 地址，jumpserver 使用此 vip 地址即可。
由云服务商提供的服务都有可靠性保证，单节点或者多节点应该影响不大
