### ISSUE TITLE
[Question] 如何关闭ssh keepalive终端消息

### ISSUE THREAD

**Issue by j0ck1e** [jumpserver/jumpserver#8865]
**请描述您的问题.**
每隔30s会stdout ssh keeplive非常影响操作,如何把消息关掉?
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1

**Comment by wojiushixiaobai** [comment]
你可以关闭 debug，或者自行找到 client_input_channel_req 函数去掉日志输出

**Comment by j0ck1e** [comment]
当前已经是`LOG_LEVEL=ERROR`
`client_input_channel_req`这个函数是在koko ssh里面吗

**Comment by wojiushixiaobai** [comment]
ssh debug

**Comment by j0ck1e** [comment]
没明白,是指koko仓库ssh功能的debug吗?

**Comment by wojiushixiaobai** [comment]
说明版本号和复现过程，这个错误是 ssh 打印的，不是 jumpserver 的代码里面打印的

**Comment by j0ck1e** [comment]
[已解决] 执行以下命令关闭显示
``` shell
echo 'CLIENT_ALIVE_INTERVAL: 0' >> /opt/jumpserver/config/koko/config.yml
./jmsctl.sh restart
```
