### ISSUE TITLE
[Question] 请问为什么日志审计中登录日志为空？

### ISSUE THREAD

**Issue by lifubang** [jumpserver/jumpserver#8869]
**请描述您的问题.**
我们使用咱们的开源堡垒机，很厉害！
在等保过程中发现，咱们的日志审计中，操作日志记录很全面，但是登录日志为空，查看了数据库也是为空。麻烦问问问什么，如何修复？

**Comment by wojiushixiaobai** [comment]
没复现，通过什么方法登录的日志没有。

可以到 [Demo](https://demo.jumpserver.org/) 环境验证下

**Comment by lifubang** [comment]
Web页面登录的，19年搭建的，新装了个2.25.5就有了。多谢！

**Comment by lifubang** [comment]
> Web页面登录的，19年搭建的，新装了个2.25.5就有了。多谢！

另外，新版对mysql8的安装第一步初始化数据库会报错。创建数据库用户的语句要改下。
