### ISSUE TITLE
[Question] 使用 kubernetes 功能，连接web终端，输入中文乱码

### ISSUE THREAD

**Issue by liyangFileRepository** [jumpserver/jumpserver#8872]
**请描述您的问题.**
连接k8s，web终端输入中文乱码

**Comment by liyangFileRepository** [comment]
![截图 2022-09-16 17-02-44](https://user-images.githubusercontent.com/90376605/190600424-131e4cf4-255b-4788-aec4-1c37a7fcc2ed.png)

**Comment by wojiushixiaobai** [comment]
试试
```sh
export LANG=en_US.utf8
```

**Comment by liyangFileRepository** [comment]
谢谢，可以使用了



| |
李杨
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月16日 18:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jumpserver/jumpserver] [Question] 使用 kubernetes 功能，连接web终端，输入中文乱码 (Issue #8872) |

试试

export LANG=en_US.utf8

**Comment by jym503558564** [comment]
好的，后续有什么问题可以再次提Issues.
