### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by baixing99** [jumpserver/jumpserver#8883]
**JumpServer 版本 v2.14.1**

**浏览器版本**
Chrome 已是最新版本
版本 105.0.5195.127（正式版本） （64 位）

**Bug 描述**
链接windows客户端时候 点击剪切板有很大概率不弹框 无法复制剪切板内容

**Bug 重现步骤(有截图更好)**
1.  正常点击“剪切板”弹框情况下
2. 点击windows桌面
3. 再次点击“剪切板” 大概率 剪切板不会弹出来

**Comment by jym503558564** [comment]
建议升级至新版本，新版本无该问题。
