### ISSUE TITLE
[Question] jumpserver连接mysql字符集

### ISSUE THREAD

**Issue by songchaoqiang** [jumpserver/jumpserver#8885]
jumpserver version:v2.25.4
jumpserver mysql: 5.7.38
application mysql:8.0.30

在application mysql设置参数character_set_results为utf8mb4，但是通过jumpserver client查看却是utf8mb3，如果加一个global参数则可以查询到为utf8mb4，想了解下jumpserver去连接application mysql时是否会通过session覆盖原有global参数?

截图：直接查看mysql字符集
<img width="810" alt="image" src="https://user-images.githubusercontent.com/109948570/191654449-7aacde61-482d-4cdc-954e-93bd3996475d.png">

截图：添加global参数查看mysql字符集
<img width="825" alt="image" src="https://user-images.githubusercontent.com/109948570/191654507-280091af-b557-4767-92ce-3e05387dc2f6.png">

**Comment by LeeEirc** [comment]
通过 本地客户端连接，还是通过 web cli的方式？通过 jumpserver 连接 mysql 数据库，都是默认的 utf8字符。web cli 用的 mysql 客户端是 mariadb，因此 utf8 就是 utf8mb3 [mariadb参考](https://mariadb.com/kb/en/unicode/)，可能受此影响。

**Comment by songchaoqiang** [comment]
两种方式都有，web cli和DB Client通过token连接都是有的

**Comment by LeeEirc** [comment]
每一个会话，字符设置都会修改成utf8。

**Comment by songchaoqiang** [comment]
字符设置都会修改为utf8，也就是会修改为utf8mb3对吧？这个"web cli 用的 mysql 客户端是 mariadb"是否可以由用户选择配置？

**Comment by LeeEirc** [comment]
暂不支持修改。
