### ISSUE TITLE
[Question] 通过api无法批量添加数据库的详细信息

### ISSUE THREAD

**Issue by goudan0528** [jumpserver/jumpserver#8888]
问题描述：
 1. 在使用/api/v1/applications/applications/接口，批量添加数据库时，参照官方api文档，只能指定数据库的名称、类别和类型，但是具体的数据库ip、端口这些无法指定，请问一下，这个是现在还没有实现吗，还是说可以有办法做到批量添加，如果只能手动添加的话，在遇到数据库特别多的情况下，会非常难管理，因为jumpserver的管理是具体到指定的库。
 2. 另外，body中的attrs能说明一下作用和如何使用么，它要提示是必须的，实际上可以不填，在示例中也没有指出它具体的使用方法
 3. 目前在用jumpserver的版本号是：v2.23.4

![图片](https://user-images.githubusercontent.com/62042619/191711992-f463c69f-12e1-4f8b-9c88-af97e608ddf4.png)

![图片](https://user-images.githubusercontent.com/62042619/191712132-9ec55938-c48d-44bf-821a-58b48fd2ae18.png)

**Comment by jym503558564** [comment]
host、port、database 信息写在attrs里，如图所示：
![image](https://user-images.githubusercontent.com/40739051/191717670-05396c2b-a511-4b4a-afa2-9d9635639628.png)

**Comment by jym503558564** [comment]
host、port 、database信息需要写在arrts里，如图所示：
![image](https://user-images.githubusercontent.com/40739051/191718940-c3893e6c-e2cf-4ac4-8133-37ef728627f1.png)

**Comment by jym503558564** [comment]
g
