### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by yanyanyong** [jumpserver/jumpserver#8889]
**JumpServer 版本 
v2.23.0 

**浏览器版本**
chrome 105.0.5195.127

**Bug 描述**
打开文件管理选中多个日志文件删除，右上角进度条卡住且不会退出

**Bug 重现步骤(有截图更好)**
1.  打开文件管理,选中多个文件点击删除，右上角显示正在删除，测试中大概超过40个文件(大约10多G)，删除进度条会一直显示卡住
2. 选中的多文件删除进度条卡住偶尔有没有删除掉的现象。一次选中稍微删除少一点的话就没有这种问题
3.

**Comment by wojiushixiaobai** [comment]
推荐使用 shell 操作，问题我们需要检测下是否可以复现

**Comment by LeeEirc** [comment]
文件数量太多，会触发 url 长度限制。建议少量，多次吧。
