### ISSUE TITLE
怎么设置通过root用户登录主机等相关root的问题

### ISSUE THREAD

**Issue by meitf** [jumpserver/jumpserver#889]
[简述你的问题]

##### 使用版本
Jumpserver版本 0.3.2
##### 问题复现步骤

1. 怎么设置通过root用户登录主机
因为好像推送的都不是root用户，也没法授权root用户给主机或Jms用户，要怎么设置才能使用root用户登录机器呢？是通过给一个nopasswd all的sudo权限系统用户解决的么？

2、管理用户问题
管理用户只能有一个吗？设置的地方只有一个啊，假如我设置管理用户为root，可能目标主机的root用户的密码都不一样，那岂不是一个管理用户一个不够？
(这个问题知道了，好像在添加资产的时候可以不选择默认的管理账户，手动单独设置一个，恩这个可以)

3、sudo权限问题
默认添加的sudo命令，推送用户之后前面都会有一个NOPASWD，意思是sudo 切换root权限的时候不需要提供系统用户密码，怎么在平台设置能去掉这个NOPASWD？

感谢！

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. 不支持 root作为系统用户
2. 是的，老版本这能设置一个
3. 普通用户是不知道后面系统用户真正密码的，所以必须NOPASSWD
