### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by sumeng001** [jumpserver/jumpserver#8890]
**请描述您的问题.**
使用jumpserver的swagger中audits_command-execution-logs接口的date_from和date_to参数，使用时间戳或者时间 接口返回的值都是默认的。
麻烦帮忙这里应该填什么格式呢？谢谢
![image](https://user-images.githubusercontent.com/28882514/191922241-5b07e3a9-5d2d-4a7b-85bc-246971bf12e7.png)
![image](https://user-images.githubusercontent.com/28882514/191925698-350682fe-c538-4d2e-9fe7-214f2826aafb.png)

**Comment by wojiushixiaobai** [comment]
2022-09-24T04:15:29.129Z
T 表示 [分隔符]，Z 表示的是 UTC 时间。
他指的时间为 2022-09-24 12:15:29 

或者你可以尝试直接使用
2022-09-24 12:15:29 +0800

**Comment by sumeng001** [comment]
> 2022-09-24T04:15:29.129Z T 表示[显示字符]，Z是UTC时间。 他指的时间为2022-09-24 12:15:29
> 
> 或者你可以尝试直接使用 2022-09-24 12:15:29 +0800

使用2022-09-24 12:15:29 +0800类型后返回为空
![image](https://user-images.githubusercontent.com/28882514/192180539-21bcfa95-766d-4697-881d-141d420d89a9.png)

**Comment by BaiJiangJie** [comment]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/32935519/229016351-ca964d96-1e94-412a-87aa-84a8442ffcb5.png">

**Comment by BaiJiangJie** [comment]
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/32935519/229016435-8962fe59-b402-4a99-a1bd-7b248c9544f4.png">
