### ISSUE TITLE
[Bug] 作业中心 - 任务列表 任务详情无法输出任务详情

### ISSUE THREAD

**Issue by wojiushixiaobai** [jumpserver/jumpserver#8896]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.26.0

**浏览器版本**

**Bug 描述**
作业中心 - 任务列表 
任务详情无法输出日志
执行历史详情无法输出日志

**Bug 重现步骤(有截图更好)**
1. 访问 作业中心 - 任务列表
2. 选择任意任务查看详情
3. 查看输出

**Comment by jym503558564** [comment]
v2.27.0解决
