### ISSUE TITLE
[Bug] 修复命令输入解析错误的问题

### ISSUE THREAD

**Issue by fengbenming** [jumpserver/jumpserver#8897]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.22.2

**浏览器版本**
firefox 104.0.2 (64 位)
chrome 105.0.5195.127（正式版本） （64 位）

**Bug 描述**
当输入命令行超过一行或者批量粘贴命令的时候，proxy/parser.go: 319 parseCmdInput方法解析命令的输入的时候，采用'\r’分割命令行，这样就会错误的解析到最后那行为用户的输入命令，而不能把多行整体的当成用户最后的一次输入。这样可能会导致依赖这个结果的业务异常，比如说高危命令过滤就会变的失效。

**Bug 重现步骤(有截图更好)**
1.  设置高危命令
2.  打开web terminal 输入不超过一行包含高危命令的命令
3.   打开web terminal 输入超过一行包含高危命令的命令

**Comment by jym503558564** [comment]
已修复
