### ISSUE TITLE
[Question] helm部署jumpserver失败

### ISSUE THREAD

**Issue by dinghui40** [jumpserver/jumpserver#8899]
**请描述您的问题.**
我使用helm加values.yaml的方式部署jumpserver但是pod却有几个运行不起来和正在等待
k8s版本：1.25
容器运行时：containerd
以下是图片
<img width="805" alt="image" src="https://user-images.githubusercontent.com/102201557/192188335-b2e46bad-91ad-45a7-b42b-8dbdc63e4b5d.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/102201557/192188361-4f07b0af-a305-4477-bc71-5bf65e838074.png">
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/102201557/192188380-e916d2a3-800b-42b2-869f-8a695850fd79.png">
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/102201557/192188415-fc43443c-564c-4015-a402-b518a5859ea3.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/102201557/192188443-5de12064-4d3a-472e-9682-45403c0af25b.png">

**Comment by wojiushixiaobai** [comment]
看看 core 组件的日志
其他组件的日志提示无法连接到 core:8080

**Comment by dinghui40** [comment]
这个组件似乎一直处于一个这样的状态
############################
2022-09-26 11:14:45 Check database connection: 0
System check identified no issues (0 silenced).
2022-09-26 11:14:46 Database connect success
2022-09-26 11:14:46 Collect static files
2022-09-26 11:14:47 Collect static files done
2022-09-26 11:14:47 Check database structure change ...
2022-09-26 11:14:47 Migrate model change to database ...
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
After migration, update builtin role permissions
2022-09-26 11:14:51 Mon Sep 26 11:14:51 2022
2022-09-26 11:14:51 JumpServer version v2.26.0, more see https://www.jumpserver.org

- Start Flower as Task Monitor

- Start Gunicorn WSGI HTTP Server
- Start heartbeat thread => ([Core]-jms-k8s-jumpserver-jms-core-f75cf7654-qztvb)

- Start Daphne ASGI WS Server
2022-09-26 11:14:54 Check service status: flower -> running at 18
2022-09-26 11:14:55 Check service status: gunicorn -> running at 20
2022-09-26 11:14:56 Check service status: daphne -> running at 28
2022-09-26 11:15:27 Check service status: flower -> running at 18
2022-09-26 11:15:28 Check service status: gunicorn -> running at 20
2022-09-26 11:15:29 Check service status: daphne -> running at 28
2022-09-26 11:16:00 Check service status: flower -> running at 18
2022-09-26 11:16:01 Check service status: gunicorn -> running at 20
2022-09-26 11:16:02 Check service status: daphne -> running at 28
2022-09-26 11:16:33 Check service status: flower -> running at 18
2022-09-26 11:16:34 Check service status: gunicorn -> running at 20
2022-09-26 11:16:35 Check service status: daphne -> running at 28
2022-09-26 11:17:06 Check service status: flower -> running at 18
2022-09-26 11:17:07 Check service status: gunicorn -> running at 20
2022-09-26 11:17:08 Check service status: daphne -> running at 28
2022-09-26 11:17:39 Check service status: flower -> running at 18
2022-09-26 11:17:40 Check service status: gunicorn -> running at 20
2022-09-26 11:17:41 Check service status: daphne -> running at 28
2022-09-26 11:18:12 Check service status: flower -> running at 18
2022-09-26 11:18:13 Check service status: gunicorn -> running at 20
2022-09-26 11:18:14 Check service status: daphne -> running at 28
2022-09-26 11:18:45 Check service status: flower -> running at 18
2022-09-26 11:18:46 Check service status: gunicorn -> running at 20
2022-09-26 11:18:47 Check service status: daphne -> running at 28
2022-09-26 11:19:18 Check service status: flower -> running at 18
2022-09-26 11:19:19 Check service status: gunicorn -> running at 20
2022-09-26 11:19:20 Check service status: daphne -> running at 28
2022-09-26 11:19:51 Check service status: flower -> running at 18
2022-09-26 11:19:52 Check service status: gunicorn -> running at 20
2022-09-26 11:19:53 Check service status: daphne -> running at 28
2022-09-26 11:20:24 Check service status: flower -> running at 18
2022-09-26 11:20:25 Check service status: gunicorn -> running at 20
2022-09-26 11:20:26 Check service status: daphne -> running at 28
2022-09-26 11:20:57 Check service status: flower -> running at 18
2022-09-26 11:20:58 Check service status: gunicorn -> running at 20
2022-09-26 11:20:59 Check service status: daphne -> running at 28
2022-09-26 11:21:30 Check service status: flower -> running at 18
2022-09-26 11:21:31 Check service status: gunicorn -> running at 20
2022-09-26 11:21:32 Check service status: daphne -> running at 28
2022-09-26 11:22:03 Check service status: flower -> running at 18
2022-09-26 11:22:04 Check service status: gunicorn -> running at 20
2022-09-26 11:22:05 Check service status: daphne -> running at 28
2022-09-26 11:22:36 Check service status: flower -> running at 18
2022-09-26 11:22:37 Check service status: gunicorn -> running at 20
2022-09-26 11:22:38 Check service status: daphne -> running at 28
2022-09-26 11:23:09 Check service status: flower -> running at 18
2022-09-26 11:23:10 Check service status: gunicorn -> running at 20
2022-09-26 11:23:11 Check service status: daphne -> running at 28
2022-09-26 11:23:42 Check service status: flower -> running at 18
2022-09-26 11:23:43 Check service status: gunicorn -> running at 20
2022-09-26 11:23:44 Check service status: daphne -> running at 28
2022-09-26 11:24:15 Check service status: flower -> running at 18
2022-09-26 11:24:16 Check service status: gunicorn -> running at 20

**Comment by dinghui40** [comment]
好想没有启动起来，并没有输出日志
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/102201557/192220607-3da21f73-8b67-47dc-9f91-82a8028940a1.png">

**Comment by dinghui40** [comment]
我用centos和ubuntu都是这种问题，有么有可能是我 values.yaml 文件写错了呢，需要我发出来看看吗

**Comment by wojiushixiaobai** [comment]
可以，如果 core 正常启动了，你试试从其他异常的 pod 请求 core:8080 看看能不能访问

**Comment by dinghui40** [comment]
# Default values for jumpserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
## @param global.redis.password Global Redis&trade; password (overrides `auth.password`)
##
global:
  imageRegistry: "swr.cn-south-1.myhuaweicloud.com"
  imageTag: v2.26.0
  ## E.g.
  #  imagePullSecrets:
  #  - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "nfs-client"

## Please configure your MySQL server first
## Jumpserver will not start the external MySQL server.
##
externalDatabase:
  engine: mysql
  host: 
  port: 3306
  user: root
  password: ""
  database: jumpserver

## Please configure your Redis server first
## Jumpserver will not start the external Redis server.
##
externalRedis:
  host: 
  port: 6379
  password: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

ingress:
  enabled: false
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "4096m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  hosts:
    - "test.jumpserver.org"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

core:
  enabled: true

  labels:
    app.jumpserver.org/name: jms-core

  config:
    # Generate a new random secret key by execute `cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`
    secretKey: "i6pMvNDpwqxCmbEq5TTiZGYQrRTr19yxeiujJ7DAXl6AxRyp9e"
    # Generate a new random bootstrap token by execute `cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 24`
    bootstrapToken: "SAVHr7WIdlfLMj3B2OopVAGZ"
    # Enabled it for debug
    debug: false
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: docker.io
    repository: jumpserver/core
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env:
    # See: https://docs.jumpserver.org/zh/master/admin-guide/env/#core
    SESSION_EXPIRE_AT_BROWSER_CLOSE: true
    # SESSION_COOKIE_AGE: 86400
    # SECURITY_VIEW_AUTH_NEED_MFA: true

  livenessProbe:
    failureThreshold: 30
    httpGet:
      path: /api/health/
      port: web

  readinessProbe:
    failureThreshold: 30
    httpGet:
      path: /api/health/
      port: web

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    web:
      port: 8080
    ws:
      port: 8070

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 1000m
    #   memory: 2048Mi
    # requests:
    #   cpu: 500m
    #   memory: 1024Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 100Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

koko:
  enabled: true

  labels:
    app.jumpserver.org/name: jms-koko

  config:
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: docker.io
    repository: jumpserver/koko
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env: []
    # See: https://docs.jumpserver.org/zh/master/admin-guide/env/#koko
    # LANGUAGE_CODE: zh
    # REUSE_CONNECTION: true
    # ENABLE_LOCAL_PORT_FORWARD: true
    # ENABLE_VSCODE_SUPPORT: true

  livenessProbe:
    failureThreshold: 30
    httpGet:
      path: /koko/health/
      port: web

  readinessProbe:
    failureThreshold: 30
    httpGet:
      path: /koko/health/
      port: web

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    privileged: true
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    web:
      port: 5000
    ssh:
      port: 2222

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

lion:
  enabled: true

  labels:
    app.jumpserver.org/name: jms-lion

  config:
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: docker.io
    repository: jumpserver/lion
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env:
    # See: https://docs.jumpserver.org/zh/master/admin-guide/env/#lion
    JUMPSERVER_ENABLE_FONT_SMOOTHING: true
    # JUMPSERVER_COLOR_DEPTH: 32
    # JUMPSERVER_ENABLE_WALLPAPER: true
    # JUMPSERVER_ENABLE_THEMING: true
    # JUMPSERVER_ENABLE_FULL_WINDOW_DRAG: true
    # JUMPSERVER_ENABLE_DESKTOP_COMPOSITION: true
    # JUMPSERVER_ENABLE_MENU_ANIMATIONS: true

  livenessProbe:
    failureThreshold: 30
    httpGet:
      path: /lion/health/
      port: web

  readinessProbe:
    failureThreshold: 30
    httpGet:
      path: /lion/health/
      port: web

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    web:
      port: 8081

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 50Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

magnus:
  enabled: true

  labels:
    app.jumpserver.org/name: jms-magnus

  config:
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: docker.io
    repository: jumpserver/magnus
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env: []

  livenessProbe:
    failureThreshold: 30
    tcpSocket:
      port: mysql

  readinessProbe:
    failureThreshold: 30
    tcpSocket:
      port: mysql

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    mysql:
      port: 33060
    mariadb:
      port: 33061
    redis:
      port: 63790
    postgre:
      port: 54320
    oracle11g:
      port: 15211
    oracle12c:
      port: 15212

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 512Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

xpack:
  enabled: false

omnidb:
  labels:
    app.jumpserver.org/name: jms-omnidb

  config:
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: registry.fit2cloud.com
    repository: jumpserver/omnidb
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env: []

  livenessProbe:
    failureThreshold: 30
    tcpSocket:
      port: web

  readinessProbe:
    failureThreshold: 30
    tcpSocket:
      port: web

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    web:
      port: 8082

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

razor:
  labels:
    app.jumpserver.org/name: jms-razor

  config:
    log:
      level: ERROR

  replicaCount: 1

  image:
    registry: registry.fit2cloud.com
    repository: jumpserver/razor
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env: []

  livenessProbe:
    failureThreshold: 30
    tcpSocket:
      port: rdp

  readinessProbe:
    failureThreshold: 30
    tcpSocket:
      port: rdp

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    rdp:
      port: 3389

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 50Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

web:
  enabled: true

  labels:
    app.jumpserver.org/name: jms-web

  replicaCount: 1

  image:
    registry: docker.io
    repository: jumpserver/web
    tag: v2.26.0
    pullPolicy: IfNotPresent

  command: []

  env: []
    # nginx client_max_body_size, default 4G
    # CLIENT_MAX_BODY_SIZE: 4096m

  livenessProbe:
    failureThreshold: 30
    httpGet:
      path: /api/health/
      port: web

  readinessProbe:
    failureThreshold: 30
    httpGet:
      path: /api/health/
      port: web

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    web:
      port: 80

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  persistence:
    storageClassName: jumpserver-data
    accessModes:
      - ReadWriteMany
    size: 1Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # subPath: ""
    # existingClaim: ""

  volumeMounts: []

  volumes: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

**Comment by dinghui40** [comment]
其他容器也访问不到这个地址

**Comment by dinghui40** [comment]
真的是找不到其他办法，真的奇怪嘞

**Comment by dinghui40** [comment]
我找到问题所在了，问题就是容器内没有自动生成内部可解析的域名，导致pod之间相互访问不通。
我是这么解决的：
hostAliases:
      - ip: $IP
        hostnames:
        - "jms-k8s-jumpserver-$name"
