### ISSUE TITLE
Jumpserver0.5.0   资产授权中 用户（组） / 资产（组）/系统用户几者的关系？

### ISSUE THREAD

**Issue by qiushaohu** [jumpserver/jumpserver#890]
[问题]
1. 资产授权中 用户（组） / 资产（组）/系统用户几者的关系？
2. 请教下 0.5.0 中， 集群这个概念起什么作用？ 可以理解为是CMDB中的机房吗？ 另外，这个集群是否会对授权产生影响？

##### 使用版本
[Jumpserver 0.5.0]

##### 问题复现步骤
1. 资产授权  资产和资产组全不勾选，可以新建成功
![image](https://user-images.githubusercontent.com/34025457/34597485-e013b8a6-f221-11e7-9ce4-44ee06bee4da.png)

2. 资产授权 无论我怎么选资产或资产组，都会提示 “Asset xxx not have [liuzhe] system users, please check
* required”
请问是有其他地方来绑定资产和系统用户吗？
![image](https://user-images.githubusercontent.com/34025457/34597521-14ba6ae6-f222-11e7-9f6e-ab794cda7aeb.png)

######其他
建议： 如果有时间，麻烦整理一份 新版jumpserver中的 概念及关系图，这样用户就不需要从前面的版本去学习啦，谢谢！

**Comment by ibuler** [comment]
Hi:

资产中的集群可以理解成IDC也可以理解成环境，现在的集群是用来做某些管理和规划的，体现在一下：

1. 管理用户    集群可以设计管理用户，这样资产可以继承该集群的管理用户，不用单独设置了
2. 系统用户    添加系统用户时可以选择存在于哪些集群，这样系统用户会自动推送到该集群的所有资产中
3. 其他          未来会基于集群做自动发现资产的功能

**Comment by ibuler** [comment]
关于那个提示， 是由于你授权的系统用户在那台资产中不存在，或者说在那个资产所在的集群中不存在。

之前的策略是授权时自动推送，自动把系统用户推送到授权的资产中，这样显然比较无脑。现在的策略是利用集群，做提前规划，哪些集群里存在哪些系统用户，规划好后再做授权

**Comment by qiushaohu** [comment]
@ibuler  收到，谢谢，我先整理下。
