### ISSUE TITLE
系统用户推送和授权的关系

### ISSUE THREAD

**Issue by meitf** [jumpserver/jumpserver#891]
[简述你的问题]

##### 使用版本
0.3.2 

##### 问题复现步骤
请问是不是只有推送过给目标主机的系统用户，才能在授权策略中将 该目标主机和该系统用户关联起来？能不能关联系统原有已设置好的系统用户呢，没有经过推送的那种？
![image](https://user-images.githubusercontent.com/32865196/34599959-222648f4-f230-11e7-9585-35ba998f4833.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是的，必须推送过，否则建立了授权规则，用户也访问不了

**Comment by meitf** [comment]
能否添加系统原有已设置好的系统用户呢，没有经过推送的那种？
如果不能实现的话，在jms平台重新设置一样的系统用户，并且一样的sudo权限的用户时候，会不会影响之前的设置，比如之前的家目录下有文件，重新推送一下会不会把之前的文件冲掉？

**Comment by ibuler** [comment]
可以添加已有的系统用户，在推送里面 不选择 密码或秘钥，这是模拟一下推送
