### ISSUE TITLE
[Bug] navicat连接mysql数据库，不能点停止。

### ISSUE THREAD

**Issue by ccyuvin** [jumpserver/jumpserver#8916]
**Bug 描述**
从 v2.23.4 升级到 v2.26.0  后，Magnus连接mysql数据库，使用navicat客户端，执行长时间sql，不能中途点停止执行。点击停止没有响应，sql还是会继续执行。
直连数据库是可以正常点击停止的。

尝试多个版本的navicat均不能正常点击停止。
尝试更换dbeaver，dbeaver的取消功能，直接报错，然后看到数据库会话里面，还是存在那条sql一直在跑。无法取消执行。
![image](https://user-images.githubusercontent.com/85599321/192485465-a5735823-060c-45b0-8d0a-1a66b6b5fa48.png)
![image](https://user-images.githubusercontent.com/85599321/192488785-d188a5f5-a521-4729-8242-a081add188d0.png)
![image](https://user-images.githubusercontent.com/85599321/192488991-2a6894d9-d243-47b8-b599-0f948d72a6cb.png)

**Comment by jmxh1** [comment]
遇到同样的问题，发现是不能正常执行kill命令
版本：v2.26.1

**Comment by Aaron3S** [comment]
检查一下命令是否匹配到了命令过滤器。 看报错是这样的。

**Comment by jym503558564** [comment]
我们新版本将重构Magnus，将会测试一下该问题是否存在。谢谢反馈～
