### ISSUE TITLE
jumpserver能不能结合tcp端口转发做多IDC的整合

### ISSUE THREAD

**Issue by meitf** [jumpserver/jumpserver#892]
[简述你的问题]

##### 使用版本
0.3.2
##### 问题复现步骤
所有主机推送的过程貌似都是直连的，假如我有多个idc，一个idc只有一台机器能脸上jumpserver，然后我通过这台机器做tcp跳转，比如idc有A B C D，能连接jms   A:22，通过设置tcp端口转发（如iptables设置）访问A:22001 可以跳转到B:22，访问A:22002可以跳转C:22，访问A:22003可以跳转D:22，将A:22001，A:22002，A:22003填入主机资产，能否访问到B:22，C:22，D:22，这样可以将不是直连的机器全部统一管理起来，咱们有做过类似的调试不，可行吗？

##### 其他

[注:] 完成后请关闭 issue

**Comment by hellorocky** [comment]
我之前这样用过,  没啥问题, 就是感觉不如直连的爽..

**Comment by ibuler** [comment]
现在也允许啊，不过不建议

**Comment by wangkai1994** [comment]
> 现在也允许啊，不过不建议

新版本是否不允许端口转发？
