### ISSUE TITLE
[Question] SFTP 直连资产格式是啥

### ISSUE THREAD

**Issue by DiligentNezha** [jumpserver/jumpserver#8924]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/20829924/193208394-dddd4311-d22c-4fc9-9c2d-234ad5e12f7c.png)
我按照ssh 直连资产的格式，不起作用

**Comment by jym503558564** [comment]
支持#格式：sftp jumpserverUsername#systemUsername#AssetIP#jumpserverHostIP -p2222
支持@格式：sftp jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222 
![image](https://user-images.githubusercontent.com/40739051/193209328-504378db-58c6-4e3d-909d-36133d7063ef.png)

**Comment by jym503558564** [comment]
如有其他问题，可再次提Issues。

**Comment by DiligentNezha** [comment]
> 
提示输入密码，这个密码是什么密码？jms 账号的密码还是 系统用户的密码

**Comment by DiligentNezha** [comment]
> 如有其他问题，可再次提Issues。

试了几个密码都不对，JMS 我使用 密钥认证的
