### ISSUE TITLE
[Bug] Linux关闭终端回显后无法记录操作

### ISSUE THREAD

**Issue by kuresaru** [jumpserver/jumpserver#8927]
**JumpServer 版本(v1.5.9以下不再支持)**

Version v2.26.0 GPLv3

**浏览器版本**

360极速浏览器 | 13.5.2022.0 (正式版本) （32 位）
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 QIHU 360EE

**Bug 描述**

Linux关闭终端回显后无法记录操作

**Bug 重现步骤(有截图更好)**
1. 登录 https://demo.jumpserver.org/core/auth/login/
2. 打开web终端登录test_ssh
3. 输入命令 stty -echo 关闭终端回显
4. 盲打命令 echo Hello World  屏幕显示Hello World
5. 会话审计会话记录回放和命令记录中只有一条stty -echo记录, 没有之后命令的记录

**Comment by LeeEirc** [comment]
命令记录是基于服务端回显的结果进行解析，关闭回显无法记录命令。如果无法回放录像，这个有待调研。

**Comment by kuresaru** [comment]
确实回放里没有关闭后的所有内容 包括输出

**Comment by LeeEirc** [comment]
未能复现你的情况，我执行了 `stty -echo` 之后，录像文件可以看到后续的输出内容。
