### ISSUE TITLE
资产硬件信息更新时ansible的dark报File "/usr/local/lib/python3.6/ast.py" SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by whoistr** [jumpserver/jumpserver#893]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
jumpserver 0.5.0
ansible  2.4.2.0
虚拟python 3.6.4
##### 问题复现步骤
 点击资产详细信息--更新资产硬件

##### 具体表现[截图可能会更好些,最好能截全]
![_20180105162334](https://user-images.githubusercontent.com/17622106/34600936-d15daa34-f234-11e7-84b0-5e129d647e4e.png)

##### 其他
是版本不支持或者说没对应嘛~

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
再添加一台其它机器测试一下
