### ISSUE TITLE
上传ed25519密钥失败

### ISSUE THREAD

**Issue by 37491** [jumpserver/jumpserver#8930]
版本：docker jumpserver/jms_all:v2.26.1
上传rsa格式密钥可以成功保存，ed25519则提示错误：`密钥不合法或密钥密码错误`
生成密钥的命令为`ssh-keygen -t ed25519 -f ./dev_ed25519`，无密码加密。

![image](https://user-images.githubusercontent.com/113976090/194701476-e1ab562a-1f10-4003-8b8b-198064686360.png)

**Comment by jym503558564** [comment]
目前暂不支持ed25519密钥

**Comment by jym503558564** [comment]
是的，目前不支持。

> 看到这个PR说支持了 #5604 , #5621 也说支持了。回退了吗

**Comment by jym503558564** [comment]
后续如果支持的话，我们将在未来的版本发布。请及时关注我们每个月版本发布情况～
