### ISSUE TITLE
[Question] Change language in report logs audit

### ISSUE THREAD

**Issue by fsatrion** [jumpserver/jumpserver#8939]
Hi,
how to change chinese characters in report logs audit to english? 
thank you

![image](https://user-images.githubusercontent.com/62125821/194917487-b209fb1e-660a-49c8-9991-51dec59ed896.png)

**Comment by wojiushixiaobai** [comment]
Feedback has been received, let's see if we can optimize this issue.

**Comment by fsatrion** [comment]
> Feedback has been received, let's see if we can optimize this issue.

Halo @wojiushixiaobai @BaiJiangJie 
related to this issue, has it solved in the latest version of jumpserver?

**Comment by wojiushixiaobai** [comment]
The problem is temporarily unresolved

**Comment by fsatrion** [comment]
ok thank you for your response, i will wait for the good news

**Comment by BaiJiangJie** [comment]
Hi, @fsatrion the v3 version has made some optimizations for translation information, you can upgrade to the latest version to see if your problem is solved.

**Comment by BaiJiangJie** [comment]
Confirmed, the translation of the login city in the audit log cannot be resolved for the time being.

**Comment by ammarun11** [comment]
Hi, @BaiJiangJie you mean for translation information login city is still under development and not yet implemented on the v3 version?
