### ISSUE TITLE
[Feature] jquery版本过低的安全问题

### ISSUE THREAD

**Issue by ldzbook** [jumpserver/jumpserver#8944]
奇安信安全扫描报告堡垒机jquery版本过低，可能遭受漏洞攻击的安全漏洞，建议升级到3.5.0以上

请问是否可以升级，以及升级时间表？

**Comment by jym503558564** [comment]
v2.26.2和v2.27.0版本，将会解决该问题。届时请关注我们版本发布情况，进行升级。
