### ISSUE TITLE
[Bug] 无法使用MySQL客户端工具连接TiDB

### ISSUE THREAD

**Issue by darkelf21cn** [jumpserver/jumpserver#8952]
**JumpServer 版本(v1.5.9以下不再支持)**
2.26.1

**浏览器版本**

**Bug 描述**
通过MySQL客户端工具连接TiDB后，执行任何命令均报错。尝试过将TiDB设置为MySQL和MariaDB类型，使用MySQL Workbench, MySQL CLI, DBeaver连接，均报同样的错误。

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.5.5-10.1.48-MariaDB

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables;
ERROR 8052 (HY000): invalid sequence 0 != 3
No connection. Trying to reconnect...
Connection id:    1
Current database: _share

ERROR 8052 (HY000): invalid sequence 0 != 3
No connection. Trying to reconnect...
Connection id:    1
Current database: _share

ERROR 8052 (HY000): invalid sequence 0 != 3
mysql>

**Bug 重现步骤(有截图更好)**
1.  选择以“DB Client”的方式连接数据库
2.  使用MySQL客户端连接数据库

**Comment by jym503558564** [comment]
暂不支持TiDB

**Comment by levie-vans** [comment]
TiDB应该是兼容MySQL协议的，不知道为什么不支持
