### ISSUE TITLE
[Bug] 网络交换机密码代填无法工作

### ISSUE THREAD

**Issue by Lucillechu** [jumpserver/jumpserver#8954]
**JumpServer 版本(v1.5.9以下不再支持)**
2.14及以后版本

**浏览器版本**
无区别

**Bug 描述**
网络设备型号：SG300-52P 52-Port Gigabit PoE Managed Switch
![图片](https://user-images.githubusercontent.com/102274757/195571058-94791b34-0253-4810-939b-74e338cbfc53.png)

**Bug 重现步骤(有截图更好)**
1.  使用ssh协议登录之后，相比于默认的服务器多一层login as ；
2. 默认的密码代填无法工作
3.

**Comment by Lucillechu** [comment]
> **JumpServer 版本(v1.5.9以下不再支持)** 2.14及以后版本
> 
> **浏览器版本** 无区别
> 
> **Bug 描述** 网络设备型号：SG300-52P 52-Port Gigabit PoE Managed Switch
> 
![图片](https://user-images.githubusercontent.com/102274757/195570808-3343b339-0be6-49cf-a705-b76f8fc1b4cd.png)

> **Bug 重现步骤(有截图更好)**
> 
>     1. 使用ssh协议登录之后，相比于默认的服务器多一层login as ；
> 
>     2. 默认的密码代填无法工作

**Comment by wojiushixiaobai** [comment]
具体现象请描述下，或者上传相关图片，我们尝试复现下

**Comment by Lucillechu** [comment]
网络设备通过putty登录，如下图所示。出现login as后，需要回车，然后继续输入用户名密码（该页面为错误示范）；
![图片](https://user-images.githubusercontent.com/102274757/195806943-41e9bdee-984d-4f65-a6a9-447aff2688f6.png)
![图片](https://user-images.githubusercontent.com/102274757/195807024-208af4a0-24d5-4baf-97f2-6aebfd6ddbf1.png)
putty日常登录正常SSH协议资产:
![图片](https://user-images.githubusercontent.com/102274757/195808887-2fbde31c-c3e0-482d-8e63-8a0b237943ee.png)
JumpServer登录如下所示：
![图片](https://user-images.githubusercontent.com/102274757/195807217-b0f56c23-11d7-44c3-9370-3de405cb65ac.png)
![图片](https://user-images.githubusercontent.com/102274757/195808609-1fbfcec6-76ea-47e3-8fac-d9c529bea89a.png)

**Comment by LeeEirc** [comment]
堡垒机的 ssh 连接，使用的是 SSH 协议的认证。如果网络设备在ssh协议认证完成之后，还需单独做认证处理，则暂时无法处理这种代填。
