### ISSUE TITLE
推送用户的密码是多少

### ISSUE THREAD

**Issue by meitf** [jumpserver/jumpserver#896]
[简述你的问题]

##### 使用版本
版本 0.3.2 

##### 问题复现步骤
推送系统用户之后，给系统用户生成的密码是多少？有默认的密码吗？

##### 具体表现[截图可能会更好些,最好能截全]

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
随机

**Comment by meitf** [comment]
那就是说我也不知道密码是多少咯？  如果想知道密码的话只能用root登进去再改？
