### ISSUE TITLE
[Bug] v.2.26.1 JumpServer纳管RedisCluster的时候无法使用集群模式连接Cluster

### ISSUE THREAD

**Issue by yexingok** [jumpserver/jumpserver#8966]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.26.1

**浏览器版本**
Edge

**Bug 描述**
在控制台-应用管理-数据库-创建数据库应用纳管RedisCluster的时候,
发现无法选择使用集群模式连接Redis集群,命令行上是redis-cli -c -h host
使用非集群模式连接, 会很不方便.
是否可以增加选项,让用户选择可以使用集群模式连接?

**Bug 重现步骤(有截图更好)**
1. 用管理员身份登录
2. 在控制台-应用管理-数据库-创建Redis数据库应用来纳管RedisCluster的时候
3. 您会发现无法选择使用集群模式连接 (即Redis-cli -c 的方式连接)

![Redis-cluster-connect-support](https://user-images.githubusercontent.com/368081/196329050-feed93cb-6746-4815-b48c-ba8766f886ed.png)

**Comment by jym503558564** [comment]
感谢反馈和建议，我们研发人员评估下该需求～

**Comment by yexingok** [comment]
好的,谢谢
