### ISSUE TITLE
[Feature] 用户使用DB Client连接数据库生成的用户名不可读

### ISSUE THREAD

**Issue by NickWang2** [jumpserver/jumpserver#8969]
当用户使用DB Client连接数据库，生成的用户名是随机字符，当用户有多个数据库应用时，从用户名上分不清楚对应哪个数据库。

需求1：是否考虑生成的用户名添加system_user.name标志。

我目前使用的v2.22.1 版本，对应authentication/api/connection_token.py 420行修改。
    418     def create_token(self, user, asset, application, system_user, ttl=5 * 60):
    419         self.check_resource_permission(user, asset, application, system_user)
    420         token = str(system_user.name)+'-'+random_string(36)
    421         secret = random_string(16)

需求2：使用DB Client连接数据库，产生的用户名等认证信息，默认有效期好像只有5分钟。
是否考虑在系统配置中添加配置项，让管理员配置有效期。
我认为多数用户习惯使用数据库管理工具，太短的有效期会导致使用上极不方便。

当然有效期更短也加更安全。
如果数据库连接认证直接和用户登录jumpserver的认证信息一致那更完美了。

**Comment by jym503558564** [comment]
关于需求2，可以定义配置有效期。vim /opt/jumpserver/config/config.txt，添加参数TOKEN_EXPIRATION=300，单位是秒。
