### ISSUE TITLE
[Feature] 针对sftp server的连接

### ISSUE THREAD

**Issue by zhabi** [jumpserver/jumpserver#8975]
**请描述您的需求或者改进建议.**
针对只支持sftp 的设备，或者支持ssh的设备，希望可以支持单独的 sftp/文件传输 授权

**Comment by jym503558564** [comment]
能否描述得再详细一点，不明白您这要表达什么？

**Comment by zhabi** [comment]
有两种场景：
1. 针对部分开放了ssh协议的设备，希望能单独支持只授权文件传输，而不允许进行命令行连接；
2. 针对只开放sftp 的设备，希望能支持只对sftp 进行授权

**Comment by jym503558564** [comment]
> 有两种场景：
> 
> 1. 针对部分开放了ssh协议的设备，希望能单独支持只授权文件传输，而不允许进行命令行连接；
> 2. 针对只开放sftp 的设备，希望能支持只对sftp 进行授权

目前暂不支持单独授权
