### ISSUE TITLE
[Question] jumpserver 安装 core容器报错

### ISSUE THREAD

**Issue by Sumiter0312** [jumpserver/jumpserver#8976]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/28424038/196865117-6b947b23-0d41-4dcc-9483-85c6ae1aca2a.png)

按照官网的方式 但是 core容器都没有创建，如何解决呢

**Comment by wojiushixiaobai** [comment]
docker ps，检查 mysql 和 redis 为什么异常
```
docker logs -f jms_redis
docker logs -f jms_mysql
```
或者卸载后重新安装
