### ISSUE TITLE
[Bug] ed25519 ssh 密钥不被支持？

### ISSUE THREAD

**Issue by nAnderYang** [jumpserver/jumpserver#8978]
**JumpServer 版本(v1.5.9以下不再支持)**
`2.26.1`

**浏览器版本**
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
x1.00`

**Bug 描述**
![image](https://user-images.githubusercontent.com/28423384/196911798-0d12e0ed-3d88-4018-a462-c8c786c2ed91.png)
![image](https://user-images.githubusercontent.com/28423384/196912042-5772e04d-430e-476e-ad26-31e0fd890168.png)

**Bug 重现步骤(有截图更好)**
1.  生成无密码的ed25519密钥
2. junpserver中添加 失败

**Comment by jym503558564** [comment]
目前暂不支持ed25519密钥

**Comment by nAnderYang** [comment]
> 目前暂不支持ed25519密钥

请问是否有支持计划?

**Comment by jym503558564** [comment]
目前暂无计划，Python里的库不支持。如后续能支持，我们会在将来版本发布。谢谢反馈～

**Comment by LiYangkai** [comment]
是哪个库不支持呢？我这边过去ssh使用的 python 库主要是paramiko ，这个库看了下[changelog](https://www.paramiko.org/changelog.html?highlight=paramiko%20ed25519)应该是支持的；
ansible我记得也是用python写的，前几天测了下也支持ed25519。
目前新的操作系统开始默认弃用ssh-rsa交互，由于安全审计，继续使用可能会遇到一些潜在问题，希望能够加入后续更新计划中

**Comment by nAnderYang** [comment]
[`pynacl`](https://github.com/pyca/pynacl) 也是支持的.希望JPS能尽早的支持吧~
