### ISSUE TITLE
使用production,css样式丢失

### ISSUE THREAD

**Issue by jiang800702** [jumpserver/jumpserver#898]
[简述你的问题]

##### 使用版本
 0.4.0

##### 问题复现步骤
1.在config.py中把最后一行改成production

##### 具体表现[截图可能会更好些,最好能截全]

![1](https://user-images.githubusercontent.com/22389335/34660523-f11349b2-f43a-11e7-819d-da1561b1c31d.jpg)
![2](https://user-images.githubusercontent.com/22389335/34660524-f14461c8-f43a-11e7-95b0-e0c2445462be.jpg)
![3](https://user-images.githubusercontent.com/22389335/34660525-f1747886-f43a-11e7-8c6f-4ea63f40109e.jpg)

**Comment by ibuler** [comment]
0.5.0部署不会了，静态文件使用nginx来处理了
