### ISSUE TITLE
[Question] 使用不同的请求方式，api 的返回结果不同？

### ISSUE THREAD

**Issue by NWYLZW** [jumpserver/jumpserver#8981]
尝试用 cookie 和 api key 的方式请求 log 的相关 api
发现 api key 的方式会丢失掉一部分内容
* curl + cookie
    <img width="279" alt="6994e4e94eb45043598cc4d31d4f2a10" src="https://user-images.githubusercontent.com/51358815/197096839-53061a60-ad82-4bc8-8f5a-dafdb93e28f9.png">
* nodejs + api key（而且这个返回结果大小不一定，有时长有时短）
    <img width="291" alt="9b2438ec2d85e777c81ccc817be1c683" src="https://user-images.githubusercontent.com/51358815/197097084-9d82e758-f88d-4e6a-a68e-9b9270443e42.png">
* browser + cookie
    <img width="273" alt="85f58a437c5605b942c11fc7d5920330" src="https://user-images.githubusercontent.com/51358815/197097055-f35ca7c6-f1f7-45b9-aebd-b35eb517391d.png">

**Comment by NWYLZW** [comment]
这是否是特殊的设计，还是一个 bug ？

**Comment by NWYLZW** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/apps/common/api.py#L50-L56

？？？？
感觉是这段内容导致的，~~是在付费版有在不同的验证方式下过滤数据吗~~

**Comment by NWYLZW** [comment]
> 返回的 data 数据有丢失？还是只是头有不一样的地方？

不止 content type 长度不一样，内容也不一样了

对应的是 `/ops/command-executions/` 接口
返回的 log_url `/api/v1/ops/celery/task/$id/log/` 的返回内容

**Comment by ibuler** [comment]
请求和哪种认证方式没有关系，celery log 这个 api 是多段的 api

```

curl https://$HOST/api/v1/ops/celery/task/b1bd9c8d-d222-451f-a04a-8e0833a83bb5/log/


{
  "data": "---------- 任务开始 ----------\r\n$ whoami (2022-10-21 14:42:34) *********************************************************************************************************\r\n\u001b[0;31mci2 | FAILED! => \u001b[0m\r\n\u001b[0;31mInvalid/incorrect password: Warning: Permanently added '118.190.42.97' (ECDSA) to the list of known hosts.\r\n\u001b[0m\r\n\u001b[0;31mPermission denied, please try again.\u001b[0m\r\n---------- 任务结束 ----------\r\n\r\n",
  "end": false,
  "mark": "cdf6985d-9ddd-4b50-b019-504353edcf50"
}
```

- /api/v1/ops/command-executions/   这个是执行命令的接口，不包含日志
- 执行命令过程是 celery 调用 ansible 去执行的

**Comment by NWYLZW** [comment]
可是我这里现在就是用不同的认证方式，最后 data 字段的内容就是完全不一样的
使用 api key 的方式会导致内容缺少一大截

* 我是调用 `/api/v1/ops/command-executions/` 获取到了返回了 log url 字段，然后去请求这个 log url

**Comment by NWYLZW** [comment]
```json
{
    "data": "---------- 任务开始 ----------\r\n$ ls -l (2022-10-21 14:01:00) **************************************************\r\n\u001b[0;33m【some content\u001b[0m\r\n\u001b[0;33m\u001b[0m\r\n---------- 任务结束 ----------\r\n\r\n】",
    "end": false,
    "mark": "65170749-712a-42b4-8c1f-b576ff2198a2"
}
```

被 【】包裹的内容用 api key 的方式进行请求会丢失

https://gist.github.com/NWYLZW/95aaae0f65fae3ee5e89aa86b06a99c9

可以使用 node 16 + ts-node + `npm install http-signature` 执行这段 index.ts 代码

**Comment by ibuler** [comment]
Node js 我不太会我用 py 写的没有问题

```
#!/usr/bin/python
#

import os
import datetime
import requests
from httpsig.requests_auth import HTTPSignatureAuth


url = "$HOST/api/v1/ops/celery/task/14b7898d-8c8f-4d44-b342-d64c2c23f281/log/"
token = 'cxxxxxxxxxxxxxxxxxxxxxxxxx'
ak = ('93xxxxxxxxxxxxxx7f9a', 'xxxxxxxxxxxx880b43fd-6305-59e4')


def request_with_token():
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer {}'.format(token)
    }
    resp = requests.get(url, headers=headers)
    print("Token response: ")
    print(resp.json())


def request_with_ak():
    signature_headers = ['(request-target)', 'accept', 'date']
    auth = HTTPSignatureAuth(key_id=ak[0], secret=ak[1], algorithm='hmac-sha256', headers=signature_headers)
    gmt_form = '%a, %d %b %Y %H:%M:%S GMT'
    headers = {
        'Accept': 'application/json',
        'Date': datetime.datetime.utcnow().strftime(gmt_form)
    }
    resp = requests.get(url, headers=headers, auth=auth)
    print("Ak response: ")
    print(resp.json())


if __name__ == '__main__':
    request_with_token()
    request_with_ak()

```

![image](https://user-images.githubusercontent.com/17382885/197148932-1fa0296b-9bf7-4764-937d-524eb49e0207.png)

**Comment by NWYLZW** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/51358815/197149620-ab17c1c6-507e-474f-bf46-010ea2ef1585.png">

是不是因为写了这行，我试试去掉这一行看看

**Comment by NWYLZW** [comment]
我本确认并运行了一下，python 确实能拿到正确的头以及数据
大概是 node.js 平台的问题
不过我还不确定是什么原因导致的这个问题

按道理都是使用的 http 方式，http header 也应该是一样的
唯一的区别是用 python 的带了一个 `'user-agent': 'python-requests/2.26.0', `

我再研究一下区别

**Comment by NWYLZW** [comment]
结论，运行的太快了
服务端还没有将内容写入
读取到的内容是旧的

**Comment by ibuler** [comment]
@NWYLZW 这个接口是个异步借口，后面有 end 标记，没有 end 需要一直请求

**Comment by NWYLZW** [comment]
> @NWYLZW 这个接口是个异步借口，后面有 end 标记，没有 end 需要一直请求

了解，不过我觉得可以从 http 状态上面去处理这个问题吧

如果指令没执行 1xx
指令执行失败了 4xx、5xx
指令执行成功了 200

这样子就不需要客户去手动处理这部分逻辑，对于 api 调用方来说可能更方便，也更少的问题（~~比如我~~）

**Comment by semiconlon** [comment]
end 为 flase 同个 log_url 请求返回的数据都是一样的 不可能等到 end 为 false 是不是有 bug
