### ISSUE TITLE
[Bug] electerm 直连资产，ssh 正常，sftp 报错

### ISSUE THREAD

**Issue by DiligentNezha** [jumpserver/jumpserver#8982]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.26.1 GPLv3

**浏览器版本**

**Bug 描述**
mac electerm 直连资产，ssh 正常，sftp 报错

**Bug 重现步骤(有截图更好)**
1.  用户名格式为 jmsUsername@assetUsername@assetIp
<img width="758" alt="image" src="https://user-images.githubusercontent.com/20829924/197170071-6bd57f6a-fb1d-4f2b-9c07-4f86dc3a4c8d.png">
2. 
<img width="2536" alt="image" src="https://user-images.githubusercontent.com/20829924/197170430-9149dad0-99df-416f-89f9-ad61d1565c1d.png">
3.

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/197433130-ef6a8194-609d-413c-ac24-494731d27db8.png)
