### ISSUE TITLE
[Bug] 自定义权限给了更新和删除用户，用户连admin账户都能改密和删除

### ISSUE THREAD

**Issue by pengcheng820** [jumpserver/jumpserver#8983]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.26.1 GPLv3.

**浏览器版本**
Microsoft Edge 版本 106.0.1370.47 (正式版本) (64 位)

**Bug 描述**
自定义权限给了更新和删除用户，用户连admin账户都能改密和删除
个人感觉这个权限划分不太合理，按理admin其他人都动不了
如果给了更新和删除权限，用户都能改动初始的admin账号，那就没有所谓的管理员了
如果除了admin，没有一个用户有控制器，又因为这个问题把admin删除了，那此时系统是不是就没admin了

[https://pic.jitudisk.com/public/2022/10/21/8f350bbb65c63.jpg](自定义权限)

[https://pic.jitudisk.com/public/2022/10/21/9bcb4eac27abb.jpg](删除admin)

**Comment by jym503558564** [comment]
实际情况admin不会被删除，后端做了限制。
