### ISSUE TITLE
[Feature] Koko 子项目有计划支持主项目的 api key 等验证方式调用 api 吗

### ISSUE THREAD

**Issue by NWYLZW** [jumpserver/jumpserver#8985]
想要集成部署测试环境，通过调用 jms 的 api 的方式去做到
在这个过程中需要 jms 的 koko 的 upload 功能，但是看了一下
koko 目前只支持 cookie 的方式且必须客户端连接上 ws 才能进行文件上传

目前好像只支持使用 cookie 的方式调用 api
https://github.com/jumpserver/koko/blob/dev/pkg/auth/http.go#L21-L32

以及限制了必需进行 ws 登陆的部分
https://github.com/jumpserver/koko/blob/dev/pkg/httpd/webserver.go#L75-L93

**Comment by ibuler** [comment]
之所以有用到 ws 是因为分布式部署，后面可能多个 koko，上传没有办法段时间内完成，所以做了分片上传，使用 ws 保持心跳

**Comment by NWYLZW** [comment]
> 之所以有用到 ws 是因为分布式部署，后面可能多个 koko，上传没有办法段时间内完成，所以做了分片上传，使用 ws 保持心跳

哦哦，那么 ws 鉴权可以支持一下 Bear Token 或者现在 Signature 的方式进行鉴权登陆吗

**Comment by ibuler** [comment]
目前还不支持，应该是可以做的

**Comment by NWYLZW** [comment]
> 目前还不支持，应该是可以做的

非常期待，谢谢

**Comment by jym503558564** [comment]
未来如果支持，我们将在后续版本进行发布，感谢反馈与支持～
