### ISSUE TITLE
[Question] 从2.26.1版本升级到2.27.0版本后web终端中的mysql输出中文乱码

### ISSUE THREAD

**Issue by liubo637** [jumpserver/jumpserver#8986]
**请描述您的问题.**
从2.26.1版本升级到2.27.0版本后web终端中的mysql输出中文乱码，并且也不能输入中文

**Comment by jym503558564** [comment]
感谢反馈，我们将尽快修复。

**Comment by jym503558564** [comment]
v2.28.0修复

**Comment by MCwrc** [comment]
@jym503558564 
V2.23.2 web终端mysql无法输入中文，v2.28.0会修复此问题吗？

**Comment by liubo637** [comment]
升级到v2.28.0版本后查询web终端中显示中文正常了，但仍然不能输入中文

**Comment by BaiJiangJie** [comment]
升级到 v3 版本可以了。 

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/32935519/229048455-bafdbdfe-e557-4463-90b5-175e29659696.png">

**Comment by xzc-1** [comment]
> 升级到 v3 版本可以了。
> 
> <img alt="image" width="1509" src="https://user-images.githubusercontent.com/32935519/229048455-bafdbdfe-e557-4463-90b5-175e29659696.png">

用的是什么版本 我用的v3.4.1，docker镜像部署，koko容器内mysql连接可以输入中文（加了环境变量LANG=zh_CN.UTF-8），但是web依旧不行
