### ISSUE TITLE
从2.26.1版本升级到2.27.0版本后 DB Client连接数据库 连接不上 

### ISSUE THREAD

**Issue by ssk8788** [jumpserver/jumpserver#8989]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![lQLPJxbQNpvyk_HNAYjNB1Kwj6b1k1sJou8DVjP4LMBwAA_1874_392](https://user-images.githubusercontent.com/48977305/197927922-237404d6-8e43-4727-8bad-ec223a4d2583.png)
![lQLPJxbQNrknXnnMl80BzLAr4iwayMGYEQNWNCerAPQA_460_151](https://user-images.githubusercontent.com/48977305/197928016-82a30b62-5270-4f96-acf1-f6f6b330b911.png)

**Comment by ayers-ltd** [comment]
怎么升级的？./jmsctl.sh check_update 2.27.0 ?

**Comment by jym503558564** [comment]
连接什么数据库的时候报的？报什么错？

**Comment by ssk8788** [comment]
已解决，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 八千流 ***@***.***&gt;
发送时间: 2022年10月27日 09:53
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: ssk8788 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jumpserver/jumpserver] 从2.26.1版本升级到2.27.0版本后 DB Client连接数据库 连接不上  (Issue #8989)





 
连接什么数据库的时候报的？报什么错？

**Comment by jym503558564** [comment]
好的，感谢反馈～
