### ISSUE TITLE
jumpserver v0.4.0版本的数据怎么导入到v0.5.0

### ISSUE THREAD

**Issue by yuanguoping** [jumpserver/jumpserver#899]
[简述你的问题]

##### 使用版本
[Jumpserver v0.5.0]

##### 问题复现步骤
v0.5.0和v0.4.0数据库表结构不一样，怎么把v0.4.0的数据导入到v0.5.0中？

**Comment by wojiushixiaobai** [comment]
关注一下。

**Comment by ibuler** [comment]
表结构差别不是很大，请想办法写sql解决
