### ISSUE TITLE
[Bug] v2.26.1 magnus DB client 登录 ERROR  backend auth error invalid ok packet 

### ISSUE THREAD

**Issue by yamin-zou** [jumpserver/jumpserver#8990]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.26.1

**浏览器版本**
DB client 登录 ERROR  backend auth error invalid ok packet 

**Bug 描述**
DB client 登录 ERROR  backend auth error invalid ok packet 
Web CLI 可以正常登录。

**Bug 重现步骤(有截图更好)**
1.  DB client 登录 
2. ERROR  backend auth error invalid ok packet 
3.

**Comment by yamin-zou** [comment]
找到原因，数据库默认的需要填写一个database，升级前版本可以不填，升级后必须填，是用来进行 判断登录成功的？
这个值 为什么是必须的？每个用户能看到的database都不一样，在数据库实例上填写一个默认database 简直画蛇添足。

**Comment by jym503558564** [comment]
谢谢反馈，后续版本机制变了，必须要指定数据库。

**Comment by yamin-zou** [comment]
> 

是因为什么原因 需要制定数据库呢？不是很理解这个机制。

**Comment by jym503558564** [comment]
不指定数据库，我们一些组件没法代理连接上数据库。例如omniDB
