### ISSUE TITLE
[Bug] 命令存储中的Elasticsearch只支持7.X的版本

### ISSUE THREAD

**Issue by chenshangwei** [jumpserver/jumpserver#8998]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-offline-installer-v2.27.0-amd64-113 

**浏览器版本**
无

**Bug 描述**
经过测试与日志分析，发现jumpserver中命令存储-ES的存储，只支持7.X的版本，
望支持更多的版本，或者支持7.X也行，但是要文档里说明下。

**Bug 重现步骤(有截图更好)**
 jumpserver使用的python的ES模块版本是7.8.0
 使用ES5.x 6.x时，jumpserver.log日志出现
[ERRO] ES failure to save: [400]: invalid_type_name_exception: Document mapping type name can't start with '_', found: [_doc]: :

**Comment by jym503558564** [comment]
ES6.x是支持的

**Comment by Songxwn** [comment]
同问题，希望能尽快支持ES 8.X版本
