### ISSUE TITLE
[Question] `[WARNING]: Consider using the file module with state=touch rather than running 'touch'.`

### ISSUE THREAD

**Issue by gMan1990** [jumpserver/jumpserver#8999]
`批量命令` 里执行了下`touch`

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/198911649-faea6aeb-b9f7-4a8d-ab3f-c070aa24a596.png)

这是 ansible 的建议提示，你如果需要生成空文件，请按照说明使用对应的模块，对应 shell，请参考上图。
