### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#900]
[简述你的问题]

##### 使用版本
0.3.2 

##### 具体表现
我在国外，和中国时差是一小时，已经设置了系统的时区。
但在登录历史查看登录时间是中国的时间。

##### 问题
1、代码是使用系统的时区，还是指定了中国时区？
2、如果是，建议加一个指定时区的配置项。

谢谢！

**Comment by huangzx** [comment]
我改了 jumpserver/settings.py 中的 TIME_ZONE 配置，批量命令和上传文件的临时目录时间是对的，但登录历史就没有新记录了，数据库中是有记录的。前端bug？

**Comment by huangzx** [comment]
jumpserver/settings.py 修改这个文件解决了。

**Comment by liujunfei980** [comment]
具体是修改settings.py哪里？
