### ISSUE TITLE
[Feature] Mangus 数据库连接组件 端口与数据库不固定 不太友好

### ISSUE THREAD

**Issue by chenshangwei** [jumpserver/jumpserver#9007]
**请描述您的需求或者改进建议.**
版本是 jumpserver-offline-installer-v2.27.0-amd64-113
Mangus 数据库连接组件  端口与数据库不固定 不太友好

端口从30000 ++ 是按照字符排列顺序++的  添加数据库可能会挤到顺序里面 端口就变化了 

现在想的办法 就是 数据库的名字前面加个 0 1 2 3 4这样的前缀 
这样数据库资产排列的顺序就不会变 端口也就固定了

另外，希望api中的applications/applications/ 也能返回这个管理端口号

**Comment by ibuler** [comment]
由于 oracle 的技术问题，所以采用了一个数据库一个端口的方案，这样比较方便处理 oracle 协议，未来考虑 开源数据库固定端口，oracle 动态端口。

api applications 返回可能不合适，目前只有 db 这样，所以应该 /applications/databases/ 返回

**Comment by Comver** [comment]
我们有做Mysql端口转发，目前使用了新版本后，因为端口号不固定，完全没法正常工作了。

**Comment by chenshangwei** [comment]
> 我们有做Mysql端口转发，目前使用了新版本后，因为端口号不固定，完全没法正常工作了。

我现在从A0 A1..A9 B0..B9这样的规则排，端口号就能固定了

**Comment by ibuler** [comment]
最好不要在程序上使用 mysql 转发

**Comment by sevenclockseven** [comment]
@ibuler mysql转发会有什么问题吗，我现在也是做的转发

**Comment by sevenclockseven** [comment]
> 我们有做Mysql端口转发，目前使用了新版本后，因为端口号不固定，完全没法正常工作了。

我把mysql访问端口固定成1个，转发到一堆配置范围内的端口，这样凑合也能用

**Comment by chenshangwei** [comment]
> @ibuler mysql转发会有什么问题吗，我现在也是做的转发

程序连的话会产生大量的审计日志吧，堡垒机本身不是设计为程序连接的。

**Comment by ibuler** [comment]
@sevenclockseven  堡垒机会记录每个命令，还会分析命令，也会命令正则匹配拦截，或者提交工单什么的，速度会慢几个数量级

**Comment by Comver** [comment]
我们的场景是 大量机器在海外，跳板机在海外，需要在国内搭一个端口转发，加速访问。 
过去端口号都是固定的，所以很方便来设置。 现在端口随机后，很难做。 而且系统有最低要求的端口数量，只设置几个是行不通的。

> 转发到一堆配置范围内的端
