### ISSUE TITLE
LDAP认证用法？

### ISSUE THREAD

**Issue by kingsxw** [jumpserver/jumpserver#901]
##### 使用版本
0.5.0

##### 问题
在config.py配置好ldap认证信息以后
第一次登陆ldap账号，会有向导导入ldap信息创建一个本地账号，相当于还是使用本地账号和本地认证。
是设计本来就如此，还是我使用方法不对？不能使用ldap认证的话意义不大啊。

**Comment by ibuler** [comment]
会把基本信息导入到db中，认证还是走的ldap，如果基本信息都没有页面会无法展示的

**Comment by kingsxw** [comment]
应该是找到问题了，因为用的Windows ad，配置如下
        "username": "sAMAccountName",
        "name": "displayName",

然后第一次登陆还是得用cn，username": "sAMAccountName这个对初次登陆不生效，按向导提示走完以后
再用cn登陆提示1062, "Duplicate entry 'xxx(此处是sAMAccountName)' for key 'username'"
用sAMAccountName登陆可以，但实际上是本地账户

但是不想用cn做用户名，因为是中文姓名不方便

**Comment by kaka1992** [comment]
AUTH_LDAP = True
    AUTH_LDAP_SERVER_URI = 'ldap://ldap1.****.com:389'
    AUTH_LDAP_BIND_DN = 'uid=jumpserver,ou=Machine,dc=****,dc=com'
    AUTH_LDAP_BIND_PASSWORD = '****'
    AUTH_LDAP_SEARCH_OU = 'ou=People,dc=****,dc=com'
    AUTH_LDAP_SEARCH_FILTER = '(employeeType=devops)'
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "uid",
        "name": "uid",
        "email": "mail"
    }
    AUTH_LDAP_START_TLS = False


我配置了这些，还是用ldap账号登录不了。现实账号密码不正确，其他的ldap接入系统都能用

**Comment by ibuler** [comment]
AUTH_LDAP_SEARCH_FILTER 应该有问题，%(user)s 不能去掉，另外请 git pull，已支持web页面设置

**Comment by kaka1992** [comment]
我更新代码，配置了%(user)s。还是登录不上，test显示有6位用户存在。

**Comment by Err0rZero** [comment]
同上，我也遇到了现实有用户存在，但是就没无法做到ldap认证登录，看了日志也没报错

**Comment by colinlabs** [comment]
+1 有用户显示，无法使用ldap认证登陆 用户过滤器:(uid=%(user)s), @ibuler

**Comment by renchili** [comment]
同上 一样的问题  匹配出来一大堆用户然后 并不能登陆

**Comment by BigbigY** [comment]
+1 AD测试正常，登陆失败，日志中没有报错
