### ISSUE TITLE
Delete Session Record in Audit 

### ISSUE THREAD

**Issue by Garrybac** [jumpserver/jumpserver#9010]
How could we delete Session list in Sessions Audit?
![Session List](https://user-images.githubusercontent.com/117132103/199632800-5284c843-cb79-44fc-8dda-aef0e65cfda9.PNG)

**Comment by Garrybac** [comment]
Is there a way to delete these sessions replays?
Thanks

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/200984435-28297ec3-c2bf-4d5b-b79b-dd54ab593174.png)

**Comment by Garrybac** [comment]
Thank you.
