### ISSUE TITLE
jumpserver init failed

### ISSUE THREAD

**Issue by shibosen** [jumpserver/jumpserver#9015]
[root@node01 ~]# kubectl get pod  -n jms -o wide
NAME                           READY   STATUS    RESTARTS   AGE     IP            NODE      NOMINATED NODE   READINESS GATES
jms-mysql-0                    1/1     Running   0          18h     10.42.1.14    master2   <none>           <none>
jms-redis-master-0             1/1     Running   0          18h     10.42.1.15    master2   <none>           <none>
jms-redis-replicas-0           1/1     Running   0          18h     10.42.2.11    master3   <none>           <none>
jms-redis-replicas-1           1/1     Running   0          5h48m   10.42.1.16    master2   <none>           <none>
jms-redis-replicas-2           1/1     Running   0          5h47m   10.42.0.105   master    <none>           <none>
jumpserver-jms-init-db-2n5nl   0/1     Pending   0          17s     <none>        master    <none>           <none>
[root@node01 ~]# kubectl  logs -f -n jms jumpserver-jms-init-db-2n5nl
Error from server (NotFound): the server could not find the requested resource ( pods/log jumpserver-jms-init-db-2n5nl)

**Comment by wojiushixiaobai** [comment]
`jumpserver-jms-init-db` is `jobs`
kubectl get jobs/jumpserver-jms-init-db-2n5nl

**Comment by shibosen** [comment]
> ```shell
> kubectl get jobs/jumpserver-jms-init-db-2n5nl
> ```

重新删除jumpserver helm instance再次install以后init恢复正常了

**Comment by shibosen** [comment]
业务容器无法正常运行

[root@node01 jumpserver]# kubectl get pod -n jms
NAME                                     READY   STATUS              RESTARTS   AGE
jms-mysql-0                              1/1     Running             0          19h
jms-redis-master-0                       1/1     Running             0          19h
jms-redis-replicas-0                     1/1     Running             0          19h
jms-redis-replicas-1                     1/1     Running             0          6h5m
jms-redis-replicas-2                     1/1     Running             0          6h4m
jumpserver-jms-celery-74c5559b99-xfj82   0/1     ContainerCreating   0          99s
jumpserver-jms-core-67454dfbc-gsqx2      0/1     ContainerCreating   0          98s
jumpserver-jms-koko-545476dc56-mcx9s     0/1     ContainerCreating   0          99s
jumpserver-jms-lion-7bc7dd84b8-mxh7s     0/1     ContainerCreating   0          99s
jumpserver-jms-magnus-b44b7645f-srtlm    0/1     ContainerCreating   0          99s
jumpserver-jms-web-58cf8c67bb-nqrjg      0/1     ContainerCreating   0          99s


events：

Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Warning  FailedScheduling    3m5s               default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    3m3s               default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           3m                 default-scheduler        Successfully assigned jms/jumpserver-jms-celery-74c5559b99-xfj82 to master3
  Warning  FailedAttachVolume  67s (x6 over 85s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7459554c-db71-4696-aec1-af59cc49479b" : rpc error: code = DeadlineExceeded desc = volume pvc-7459554c-db71-4696-aec1-af59cc49479b failed to attach to node master3
  Warning  FailedAttachVolume  67s (x6 over 85s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1c1f07b7-cef1-48d3-bdd0-4b0e12f2bd51" : rpc error: code = DeadlineExceeded desc = volume pvc-1c1f07b7-cef1-48d3-bdd0-4b0e12f2bd51 failed to attach to node master3

但是pvc都是可以正常绑定的：
[root@node01 jumpserver]# kubectl get pvc -n jms
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-jms-mysql-0                  Bound    pvc-92416cfa-eefc-4384-a6bd-ead21ccb6658   8Gi        RWO            longhorn       19h
jumpserver-jms-core-data          Bound    pvc-7459554c-db71-4696-aec1-af59cc49479b   100Gi      RWX            longhorn       3m3s
jumpserver-jms-core-logs          Bound    pvc-1c1f07b7-cef1-48d3-bdd0-4b0e12f2bd51   100Gi      RWX            longhorn       3m3s
jumpserver-jms-koko-data          Bound    pvc-0e9ee5e0-e68b-4937-92af-9346445100a8   10Gi       RWX            longhorn       3m3s
jumpserver-jms-lion-data          Bound    pvc-b6d0f60d-ebbe-4de0-a796-b9936785eb81   50Gi       RWX            longhorn       3m3s
jumpserver-jms-magnus-data        Bound    pvc-e65fc213-d3ba-43af-9db7-eb4e8c7c923e   10Gi       RWX            longhorn       3m3s
jumpserver-jms-web-logs           Bound    pvc-809b8dce-b429-4baf-a4fa-04118e30da6e   1Gi        RWX            longhorn       3m3s
redis-data-jms-redis-master-0     Bound    pvc-22441e15-8eec-4b61-9f22-058a92f568e8   8Gi        RWO            longhorn       19h
redis-data-jms-redis-replicas-0   Bound    pvc-e1953cf3-c6a4-43d8-af8a-5f09d67657c7   8Gi        RWO            longhorn       19h
redis-data-jms-redis-replicas-1   Bound    pvc-6c30fa71-8cc5-4819-bebb-9b20e1ae6cfc   8Gi        RWO            longhorn       6h6m
redis-data-jms-redis-replicas-2   Bound    pvc-9102dc00-2b4a-4b89-9ff2-19dc5856708f   8Gi        RWO            longhorn       6h6m

**Comment by wojiushixiaobai** [comment]
查看 core 的日志，根据提示解决

**Comment by shibosen** [comment]
> 查看 core 的日志，根据提示解决

Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Warning  FailedScheduling    8m47s                  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling    8m46s                  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled           8m43s                  default-scheduler        Successfully assigned jms/jumpserver-jms-core-67454dfbc-gsqx2 to master3
  Warning  FailedMount         6m40s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[jms-core-data jms-core-logs], unattached volumes=[jms-core-config jms-core-data jms-core-logs kube-api-access-gd7ht]: timed out waiting for the condition
  Warning  FailedMount         4m22s                  kubelet                  Unable to attach or mount volumes: unmounted volumes=[jms-core-data jms-core-logs], unattached volumes=[kube-api-access-gd7ht jms-core-config jms-core-data jms-core-logs]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m53s (x10 over 7m8s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-7459554c-db71-4696-aec1-af59cc49479b" : rpc error: code = DeadlineExceeded desc = volume pvc-7459554c-db71-4696-aec1-af59cc49479b failed to attach to node master3
  Warning  FailedAttachVolume  2m53s (x10 over 7m8s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1c1f07b7-cef1-48d3-bdd0-4b0e12f2bd51" : rpc error: code = DeadlineExceeded desc = volume pvc-1c1f07b7-cef1-48d3-bdd0-4b0e12f2bd51 failed to attach to node master3
  Warning  FailedMount         2m6s                   kubelet                  Unable to attach or mount volumes: unmounted volumes=[jms-core-data jms-core-logs], unattached volumes=[jms-core-data jms-core-logs kube-api-access-gd7ht jms-core-config]: timed out waiting for the condition

[root@node01 jumpserver]# kubectl logs -n jms jumpserver-jms-core-67454dfbc-gsqx2
Error from server (BadRequest): container "jms-core" in pod "jumpserver-jms-core-67454dfbc-gsqx2" is waiting to start: ContainerCreating

**Comment by wojiushixiaobai** [comment]
pvc 创建有问题
