### ISSUE TITLE
数据库同步失败

### ISSUE THREAD

**Issue by ahaii** [jumpserver/jumpserver#902]
[简述你的问题]
执行sh init_db.sh的时候，失败。
提示信息:
django.db.utils.IntegrityError: Problem installing fixture '/data/local/jumpserver-dev0.4/apps/fixtures/init.json': Could not load assets.AssetGroup(pk=d742a7be-faf1-4c29-ae0a-e6aa640ab395): column name is not unique

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
Jumpserver0.4
Python3.6

##### 问题复现步骤
1. [步骤1]
sh make_migrations.sh
2. [步骤2]
sh init_db.sh
##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/11328004/34707234-53267c84-f547-11e7-8eb3-378c5c4056a5.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
现在dev分支是 0.5.0了，不需要初始化数据库了

**Comment by ahaii** [comment]
ok.谢谢。
