### ISSUE TITLE
[fix] 系统用户手动填写密码

### ISSUE THREAD

**Issue by haohao0328** [jumpserver/jumpserver#9024]
**请描述您的需求或者改进建议.**
在资产登录界面选择浏览器记住密码，当点击小眼睛组件时可以直接看到密码，建议这个地方做个二次认证。

**Comment by BaiJiangJie** [comment]
这个感觉没有必要，因为在浏览器控制台也是可以查看的。

如果想要不能查看，还是建议将密码托管在平台里。
