### ISSUE TITLE
资产批量导入报错

### ISSUE THREAD

**Issue by jackkeyang** [jumpserver/jumpserver#903]
[简述你的问题]

##### 使用版本
0.4.0

##### 问题复现步骤
资产批量导入csv，无反应，日志报错如下
![tim 20180109143926](https://user-images.githubusercontent.com/13012416/34707878-ecaef400-f54a-11e7-901b-1624650e84dd.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
0.5.0的呢？
