### ISSUE TITLE
[Bug] 邮件测试连接发件人不能为 null

### ISSUE THREAD

**Issue by JonnnLOL** [jumpserver/jumpserver#9030]
**JumpServer 版本(v1.5.9以下不再支持)**
2.27.0

**浏览器版本**

Microsoft Edge
版本 107.0.1418.26 (正式版本) (64 位)

**Bug 描述**
邮件测试连接发件人未默认使用 smtp 账号，导致测试连接时返回发件人不能为 null

**Bug 重现步骤(有截图更好)**
1.  全新部署的 JumpServer
2.  配置邮件服务器，发件人置空，点击测试连接按钮无反应且未发送邮件，通过开发者工具查看请求发现测试连接请求返回 400，提示发件人不能为 null，说明并未默认使用 smtp 账号作为发件人
![image](https://user-images.githubusercontent.com/95204418/200713290-b207fe35-b801-404e-a6ad-34c05ef20f85.png)

**Comment by jym503558564** [comment]
感谢反馈，我们将在v2.27.1小版本修复
