### ISSUE TITLE
[Question] 基于 JumpServer 如何做 CI/CD

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#9036]
**请描述您的问题.**

之前持续部署的执行需要依赖 SSH 隧道进行线上环境部署，但是 JumpServer 的 SSH 网关不支持隧道，那企业引入 JumpServer 之后如何做 CD ？官方没有类似的案例说明，所以在社区寻求一下帮助。

**Comment by wojiushixiaobai** [comment]
CI/CD 的流程和堡垒机没啥关系吧，CI/CD 本身就有任务日志记录。
而且经过堡垒机后可靠性也无法保障，在 CI/CD 的流程里面不应该出现堡垒机。
