### ISSUE TITLE
[Question]负载均衡模式各节点若未设置NFS共享的持久化目录会造成什么问题

### ISSUE THREAD

**Issue by Anorpi** [jumpserver/jumpserver#9039]
**负载均衡模式各节点未将 `VOLUME_DIR` 设置为NFS共享会造成什么问题**
官方部署文档介绍了  负载均衡 的安装与部署。
其中文档提到各个节点的 `VOLUME_DIR=/opt/jumpserver` 指定的目录是通过NFS挂载共享的。
我部署了两个节点共用了 Redis 和 MySQL 但 `VOLUME_DIR=/opt/jumpserver` 此目录两节点未设置NFS共享，功能似乎都正常。
想了解下 这个 `VOLUME_DIR=/opt/jumpserver` 的目录，各节点共享与不共享的区别是什么，线上不共享的话，会存在什么问题。

**Comment by wojiushixiaobai** [comment]
任务日志可能无法正常查看

**Comment by Anorpi** [comment]
> 任务日志可能无法正常查看

任务日志是指 jumpserver 自身任务的日志吗
URL：https://x.x.x.x/ui/#/console/ops/tasks

录像日志是否也是存储在这里的，使用单节点的IP登入执行的操作，录像会不会在其他节点上看不到呢。

感谢

**Comment by wojiushixiaobai** [comment]
使用第三方对象存储，如 OSS、AWS 等存储录像即可避免此问题

**Comment by Anorpi** [comment]
> 任务日志可能无法正常查看

这个可以具体些吗 
是什么日志 不清楚这个日志无法查看会造成什么问题。

以及各节点间，没有共享此目录的话，是否还会有其他问题？

感谢大佬们。

**Comment by wojiushixiaobai** [comment]
不影响资产连接功能，你可以查看具体需要共享的目录。
里面都是日志、静态文件、录像文件等。

如果在 A 节点查看 B 节点的文件 就会无法查看该文件，除此之外无其他问题
