### ISSUE TITLE
jumpserver 0.3.0-beta 版本删除后 无法ssh登陆服务器的问题

### ISSUE THREAD

**Issue by JinLongA** [jumpserver/jumpserver#904]
删除jumpserver后 用普通用户ssh服务器的时候 会调用connect.py的文件 无法远程
![note_attach](https://user-images.githubusercontent.com/34049664/34712809-2455fc28-f55f-11e7-8c3f-c1a0d4f7f90c.png)
![2](https://user-images.githubusercontent.com/34049664/34712811-24843908-f55f-11e7-9f85-c0d56768ea9d.png)
![3](https://user-images.githubusercontent.com/34049664/34712812-24b27c64-f55f-11e7-812f-2d8c9d30585a.png)

**Comment by JinLongA** [comment]
已经删除了jumpserver 为什么还会去调用这个文件呢 是jumpserver在安装的时候修改了系统的什么配置吗 求大神帮忙

**Comment by ibuler** [comment]
修改 /etc/passwd 把后面的 init.sh 换为 /bin/bash

**Comment by JinLongA** [comment]
![image](https://user-images.githubusercontent.com/34049664/34713058-fe51b41c-f55f-11e7-9a9f-1674dde02184.png)
已经都是bin/bash了

**Comment by ibuler** [comment]
beta版？好吧，去 /etc/profile.d/下移除  zzjumpserver.sh

**Comment by JinLongA** [comment]
哇塞 成功了 谢谢 大神 给您作揖了 我头大了一周了都没感解决 万分感谢！！！
