### ISSUE TITLE
[Question] rdp文件上传限制

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#9041]
**请描述您的问题.**

请问rdp文件上传限制是怎么做的。
我这边上传大文件：8G失败，页面没有具体报错信息。

nginx里的参数已经调整过 client_max_body_size 9096m;

 JMSERVER: Version v2.27.0 
浏览器 chrom 版本: 107.0.5304.88（正式版本）

**Comment by wojiushixiaobai** [comment]
检查下 nginx 日志和 lion 组件的日志
大文件尽量通过其他的方式管理
