### ISSUE TITLE
远程资产提示 502 Bad Gateway

### ISSUE THREAD

**Issue by 37491** [jumpserver/jumpserver#9047]
windows rdp, 提示 502 Bad Gateway. 重启jms docker后恢复。查看日志有这条：
```
[1411289.979349] guacd[285897]: segfault at 10 ip 00007fbd6a6f2f06 sp 00007fbd6253dc80 error 4 in libguac-client-rdp.so.0.0.0[7fbd6a6de000+1d000]
```
超过1天大概率会挂掉，现在是做了个job定时重启。昨天这个是启动16小时后发现远程不了。目前资产和用户数量<10 。
docker 版本：jumpserver/jms_all:v2.27.0
Docker version 20.10.20, build 9fdeb9c
Host: Debian 11

**Comment by wojiushixiaobai** [comment]
guacd 异常了，你可能得检查下 guacd 的日志

**Comment by wojiushixiaobai** [comment]
根据下面的日志定义：
- https://github.com/wojiushixiaobai/Dockerfile/blob/master/allinone/supervisord.conf#L25
错误日志会重定向到 /dev/stderr
使用 docker logs jms_all 应该能看到导致异常的错误日志才对
