### ISSUE TITLE
[Question] oidc用户ssh 登陆

### ISSUE THREAD

**Issue by aiopser** [jumpserver/jumpserver#9055]
**请描述您的问题.**
oidc用户能通过ssh 2222 端口登录吗

**Comment by aiopser** [comment]
试了下是可以的，只不过用OIDC登录的用户默认的用户名变成了是34ab184b-8b92-45d5-bd91-15070617fee6 这种，名称是他的登录名。

那么怎么设置才能让OIDC登录的用户名变成jumpsever的用户名呢，而不是自动生成的
当前使用的版本是v2.12.0

**Comment by jym503558564** [comment]
我们在v2.23.0版本中：支持OpenID认证设置用户属性映射字段
![image](https://user-images.githubusercontent.com/40739051/202672262-26057206-ed6a-4058-b64b-a98060f9ac00.png)
