### ISSUE TITLE
jumpserver登陆问题

### ISSUE THREAD

**Issue by weijiaqi123** [jumpserver/jumpserver#906]
[简述你的问题]

##### 使用版本
[使用的Jumpserver版本 0.3.2 ]

##### 问题复现步骤
1. [步骤1]
跳板机无法登录

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![qq20180111093955](https://user-images.githubusercontent.com/35318288/34804401-6edf95ba-f6b3-11e7-8767-b19f94a5f34e.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不要登录jumpserver本机
