### ISSUE TITLE
[Question] 2.20.1版本WebTerminal 界面如何取消右边的侧边栏？是否支持设置侧边栏宽度？

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#9061]
**请描述您的问题.**
版本：2.20.1，设置里暂未找到设置右边侧边栏的地方。
WebTerminal 界面如何取消右边的侧边栏？是否支持设置侧边栏宽度？

<img width="92" alt="image" src="https://user-images.githubusercontent.com/39855929/201813281-3b8e9ec2-59c6-4505-9b14-27d43a5514fd.png">

**Comment by lf-zhang** [comment]
侧边栏会遮挡到内容，导致展示不完整，所以需要去掉

**Comment by lf-zhang** [comment]
还有个问题想请教下：使用SSO登录时直接登录到机器了，是否能配置或者支持打开WebTerminal的功能栏？
<img width="452" alt="image" src="https://user-images.githubusercontent.com/39855929/201818334-cf975cee-2ef7-4ab7-b5a8-3e4aed7f0b93.png">

**Comment by jym503558564** [comment]
侧边栏会遮挡到的内容，截图看一下？我们在新版本中，已经优化过侧边栏。
![image](https://user-images.githubusercontent.com/40739051/202673698-a5c8c3fc-e38e-4338-a52b-bcf0734faad4.png)
