### ISSUE TITLE
[Question] SSH 如何直连资产时非交互式执行命令

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#9064]
**请描述您的问题.**

想要直连资产触发执行某个命令，但我试了好几种方式都报错 `No PTY requested.`

```bash
$ echo 'pwd' | ssh -p 2222 jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP
Pseudo-terminal will not be allocated because stdin is not a terminal.
Authenticated with partial success.
itj180012
Please Enter MFA Code.
[OTP Code]: ******
No PTY requested.

$ ssh -p 2222 jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP <<EOF
heredoc> pwd
heredoc> EOF
Pseudo-terminal will not be allocated because stdin is not a terminal.
Authenticated with partial success.
itj180012
Please Enter MFA Code.
[OTP Code]: ******
No PTY requested.

$ ssh -p 2222 jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP pwd
Authenticated with partial success.
itj180012
Please Enter MFA Code.
[OTP Code]: ******
No PTY requested.
```

**Comment by cobolbaby** [comment]
@LeeEirc 如果想要支持，是只需要修改 koko，还是连 core 也得一起动？

**Comment by LeeEirc** [comment]
修改koko即可

**Comment by cobolbaby** [comment]
@LeeEirc 

看了 koko 的源码，不知道下面俩个方法是否可以解决该问题:

1. 启用 ENABLE_VSCODE_SUPPORT
2. 注释掉以下 code

https://github.com/jumpserver/koko/blob/1ea6cbfadf438b93be0088662a177e269e486447/pkg/handler/direct_handler.go#L161-L164

**Comment by LeeEirc** [comment]
koko 暂时没有对 非Pty 的请求做处理，后续再考虑对直连资产执行非交互式命令的支持，也欢迎 pr。

**Comment by cobolbaby** [comment]
> koko 暂时没有对非 Pty 的请求做处理

我看 vscode remote ssh 走的就是非 Pty 吧

> 再考虑对直连资产执行非交互式命令的支持

有没有开发环境搭建的方法，感觉组件涉及的比较多，我怎么构建一个 koko 的开发环境？

**Comment by LeeEirc** [comment]
vscode 是 ssh tunnel。koko 开发环境可以参考仓库的说明。需要先启动 jumpserver 项目，再启动 koko。

**Comment by cobolbaby** [comment]
> vscode 是 ssh tunnel

那 ansible 方式理论上应该和 vscode 是一种方式吧。

**Comment by LeeEirc** [comment]
计划在 v3 中做支持。

![image](https://user-images.githubusercontent.com/32626707/209271315-f019f0e5-cc59-4e21-965b-215dbd24de4d.png)

**Comment by cobolbaby** [comment]
> 计划在 v3 中做支持。

好消息，不过 v3 预计什么时候发布？该功能是否可以合并到 v2，毕竟 v2 较为稳定，v3 少说也得经过半年一年的迭代才能上生产。

**Comment by LeeEirc** [comment]
不会在 v2 增加新功能了。

**Comment by cobolbaby** [comment]
@LeeEirc V3 支持该功能了吗？

**Comment by cai-zhencheng** [comment]
同问：V3 支持该功能了吗？能否重开此 Issue?
