### ISSUE TITLE
[Question] 配置了nginx反向代理，其他都好的就是文件管理有问题

### ISSUE THREAD

**Issue by Zhengyueewee2e** [jumpserver/jumpserver#9068]
反向代理命令：
![image](https://user-images.githubusercontent.com/40627010/201893733-d55e0f65-0fbf-4a0a-9f99-7724f3a36c4c.png)
文件管理报错：
![image](https://user-images.githubusercontent.com/40627010/201894109-826cde05-776e-4d97-aec9-3c0167ee89c2.png)
不加nginx反向代理是好的

**Comment by wojiushixiaobai** [comment]
看看nginx 的日志，是报啥错误

**Comment by Zhengyueewee2e** [comment]
![image](https://user-images.githubusercontent.com/40627010/202068943-c75bd3bc-93d5-4782-a46e-a4f00e2c253e.png)
报这个错误

**Comment by Zhengyueewee2e** [comment]
![image](https://user-images.githubusercontent.com/40627010/202069330-7f0c5012-61da-4271-9dce-6afd237f5343.png)

**Comment by Zhengyueewee2e** [comment]
![image](https://user-images.githubusercontent.com/40627010/202071119-01cfa274-c247-4c34-af9c-a4334718b998.png)

我 发现当我upstream中注释掉一个站点，就好了，但是配两个站点就会出这个问题

**Comment by wojiushixiaobai** [comment]
持久化 cookie，配置 ip_hash;

**Comment by Zhengyueewee2e** [comment]
解决了，谢谢
