### ISSUE TITLE
点击连接出现的问题

### ISSUE THREAD

**Issue by weijiaqi123** [jumpserver/jumpserver#907]
##### 使用版本
[使用的Jumpserver版本 0.3.2 ]

##### 问题复现步骤
1. [步骤1]
点击连接,chu'xi出现下面界面
2. [步骤2]
![q1](https://user-images.githubusercontent.com/35318288/34804735-2c41a21e-f6b5-11e7-90b4-965bf8f24367.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by huangzx** [comment]
如果是经过反向代理的，试试这个：https://github.com/jumpserver/jumpserver/wiki/v0.3.2-Nginx-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

websocket 部分

**Comment by ibuler** [comment]
#568
