### ISSUE TITLE
[Question] 无法使用VScode连接 jumpserver

### ISSUE THREAD

**Issue by qiuyuyin** [jumpserver/jumpserver#9072]
使用 ssh -i 'xxx\ssh.pem' -p 37000 xxx@xxxx@hostIP@jumpServerIP连接jumpserver命令连接时
在使用VScode进行连接时，不会出现连接成功的状态，并且会一直出现连接中的状态，请问如何解决这个问题

**Comment by wojiushixiaobai** [comment]
参考 #8341

**Comment by qiuyuyin** [comment]
已近解决

**Comment by qiuyuyin** [comment]
OK
