### ISSUE TITLE
[Question] web sftp 文件下载时怎么知道有没有通过 zip 进行压缩

### ISSUE THREAD

**Issue by wangchaoforever** [jumpserver/jumpserver#9073]
**请描述您的问题.**
JumpServer 文档的 [KoKo 参数说明](https://docs.jumpserver.org/zh/master/admin-guide/env/?h=sftp#koko) 中有 `ZIP_MAX_SIZE=1024M ` 参数，请问这个参数为 1024M 是默认值吗？意思是小于 1024M 的话，通过 web sftp 下载会通过 zip 对文件进行压缩再传输过来吗？

**Comment by LeeEirc** [comment]
是的，文件夹下载会走 zip 压缩。

**Comment by wangchaoforever** [comment]
@LeeEirc 我尝试了下，确实文件夹下载可以压缩，将 118M 压缩成了 31M 再进行传输。
我们遇到的场景是单个文件夹中有很多的文件，但是我要下载的文件可能只有其中1个或几个，而且单个文件可能比较大。请问支持单个文件下载走 zip 压缩吗？

**Comment by LeeEirc** [comment]
单个文件不需要压缩啊，你可以直接点击下载。

**Comment by wangchaoforever** [comment]
可以直接点击下载，但是文件比较大，且带宽有限，希望能点击下载的时候自动压缩。

**Comment by LeeEirc** [comment]
那暂时不支持。
