### ISSUE TITLE
定时任务会将主机数据的 其他IP 清空

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#908]
[简述你的问题]

##### 使用版本
0.3.2

##### 具体表现[截图可能会更好些,最好能截全]
1、手动修改了 其他IP
2、执行下面的定时任务，其他IP 被清空

![image](https://user-images.githubusercontent.com/3265516/34807610-579d0a8c-f6bc-11e7-9246-77be12e25511.png)

##### 其他
0 1 * * * /usr/bin/python /data/jumpserver/jumpserver/manage.py crontab run 3718e5baf203ed0f54703b2f0b7e9e16 # django-cronjobs for jumpserver

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/0.3.3/jasset/asset_api.py#L381   会自动收集机器上的其他ip的，如果你有多块网卡的话

**Comment by huangzx** [comment]
all_ip = setup_info.get("ansible_all_ipv4_addresses")
print(asset_ip)
print(all_ip)
other_ip_list = all_ip.remove(asset_ip) if asset_ip in all_ip else []
print(other_ip_list)

---
192.168.1.2
[u'192.168.1.2', u'61.14.253.146']
None

问题出在这段代码，我看不懂 :(

**Comment by huangzx** [comment]
我知道了。
remove 方法没有返回值

**Comment by huangzx** [comment]
```
# git diff jasset/asset_api.py
diff --git a/jasset/asset_api.py b/jasset/asset_api.py
index 2d86b67..fc7143c 100644
--- a/jasset/asset_api.py
+++ b/jasset/asset_api.py
@@ -330,6 +330,8 @@ def get_ansible_asset_info(asset_ip, setup_info):
                 disk_need[disk_name] = disk_format
     all_ip = setup_info.get("ansible_all_ipv4_addresses")
     other_ip_list = all_ip.remove(asset_ip) if asset_ip in all_ip else []
+    if all_ip:
+        other_ip_list = all_ip
     other_ip = ','.join(other_ip_list) if other_ip_list else ''
     # hostname = setup_info.get("ansible_hostname")
     # ip = setup_info.get("ansible_default_ipv4").get("address")
```

加上这句，解决了
