### ISSUE TITLE
jumpserver-0.3.3外网访问问题

### ISSUE THREAD

**Issue by JinLongA** [jumpserver/jumpserver#909]
我在内网安装得jumpserver 公网路由得80端口映射到内网得一个nginx上 然后用域名转发到这一台jumpserver上 添加的资产也都是内网网段得 请问如果配置nginx转发
![image](https://user-images.githubusercontent.com/34049664/34858114-63a7c8e4-f789-11e7-86a9-1ad32698d095.png)
![image](https://user-images.githubusercontent.com/34049664/34858126-6de6e178-f789-11e7-8f56-b9113c3f3d54.png)

**Comment by JinLongA** [comment]
在内网访问jumpserver得时候 就可以连接上资产 外网连接不上

**Comment by ibuler** [comment]
保证jumpserver与资产之间网络是可达的

**Comment by wojiushixiaobai** [comment]
proxy_pass 错误，把8000去掉。
server name 与proxy_pass 的 doman name 应该一致才对，要想外网加端口访问的话，应该是在 proxy_set_header Host 里面设置才对。

**Comment by Crushlinuxstart** [comment]
你好你的问题解决了吗 我也遇到了
