### ISSUE TITLE
搜索下拉框可以增加外网IP吗？还有ssh登陆的时候也加上外网IP的选项

### ISSUE THREAD

**Issue by vb3328998** [jumpserver/jumpserver#9092]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/40584745/202391266-f0ebb9ae-761f-48f6-b289-551d8d784ee0.png)
搜索下拉框可以增加外网IP吗？还有ssh登陆的时候也加上外网IP的选项

**Comment by BaiJiangJie** [comment]
在 v3 版本中，对于资产只保留了一个地址字段（address），没有再区分内网 IP 和 公网 IP 了。
