### ISSUE TITLE
[Feature] 文件上传或下载审计能提供保存的文件

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#9097]
**请描述您的需求或者改进建议.**
调研过多家堡垒机，齐治、阿里云堡垒机等都可以将上传或下载的文件保存供日后审计，但JumpServer这边一直没有，建议考虑一下。如果是考虑文件大小，可以像当前上传下载文件nginx那里设置限制一样进行限制。

**Comment by levie-vans** [comment]
强烈支持
