### ISSUE TITLE
[Question] OpenID登录用户退出登录报错502

### ISSUE THREAD

**Issue by aiopser** [jumpserver/jumpserver#9104]
**请描述您的问题.**
OpenID登录用户，点击退出登录报错502
![image](https://user-images.githubusercontent.com/56713171/202657336-e4e9a118-9cee-4a58-a431-1f5efd50ef8d.png)

**Comment by jym503558564** [comment]
无法复现，什么版本。

**Comment by aiopser** [comment]
v2.26.0

**Comment by aiopser** [comment]
在jumpserver 管理页面认证设置里配置OIDC  和在 jumpserver服务器上的config.txt 里配置OIDC 这两者有什么区别
jumpserver是读哪里的配置呢，优先级？

**Comment by wojiushixiaobai** [comment]
页面优先
