### ISSUE TITLE
[Bug] 资产更新不生效

### ISSUE THREAD

**Issue by crazysarah** [jumpserver/jumpserver#9109]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.22.1 及更新后 V2.28.1

**浏览器版本**
CHROMIUM 107.0.1418.52

**Bug 描述**
从HTTPS退回到HTTP之后，删除了LB，发现资产更新不了。按更新按钮只是转了几秒。没有提示修改成功。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/46314944/203214728-5659d99b-d61b-4ad6-8a58-9f8fb56f7c83.png)

2. 
3.

**Comment by wojiushixiaobai** [comment]
看看 nginx 的日志，应该是 反向代理 有问题或者 celery 掉线了

**Comment by crazysarah** [comment]
> 看看 nginx 的日志，应该是 反向代理 有问题或者 celery 掉线了

nginx日志没有问题，容器看过正常ONLINE，但容器内部访问不了celery 8070 8080端口。。。

**Comment by wojiushixiaobai** [comment]
前端显示 connect error 的话，nginx 应该会有一条对应的错误信息才是。

**Comment by crazysarah** [comment]
没有显示连接错误，没有任何提示，发现用内网ip访问能正常修改，用域名就不行。

**Comment by wojiushixiaobai** [comment]
[反向代理配置需要添加 websocket 相关支持。](https://docs.jumpserver.org/zh/master/admin-guide/proxy/#2-nginx)

```
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
```

**Comment by wojiushixiaobai** [comment]
那就是你的 waf 拦截了请求

**Comment by crazysarah** [comment]
嗯，慢慢检查一下先，应该不是堡垒机的问题了。
