### ISSUE TITLE
[Feature] ftp默认路径支持动态名称

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#9111]
**请描述您的需求或者改进建议.**
当前v2.28及之前版本ftp路径只能写死。希望能将路径指定为当前用户的家目录，如/home/admin，或者是能指定路径+当前用户名，如/fs01/home/admin【这个“admin”动态传参当前用户名，${username}】

**Comment by wojiushixiaobai** [comment]
写 home 即可，页面有 tip 提示
