### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jiangqinghuang** [jumpserver/jumpserver#9112]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.1 

**浏览器版本**
Firefox
chrome

**Bug 描述**
MySQL控制台，命令行中无法输入中文。

**Bug 重现步骤(有截图更好)**
1.  进入MySQL命令控制台。
2. 输入带中文的SQL。

**Comment by wojiushixiaobai** [comment]
如何部署的，installer 部署的大多数情况下已经解决了才对，检查 mysql server 是否定义了相关配置导致无法输入中文
