### ISSUE TITLE
[Question] 远程桌面连接当前已关闭你的背景

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#9113]
**请描述您的问题.**
通过web gui  连接windows2016，远程桌面黑色背景。系统背景功能提示：远程桌面连接当前已关闭你的背景。
是否有办法修改使支持。

 JUMPSERVER: Version v2.27.0
![图片](https://user-images.githubusercontent.com/38068938/203494512-7104b762-1e4c-45f5-bb6b-a6838e2c212e.png)

**Comment by wojiushixiaobai** [comment]
[Lion 参数说明](https://docs.jumpserver.org/zh/master/admin-guide/env/#lion)
```
JUMPSERVER_COLOR_DEPTH=32                    # 颜色深度 低色 16位, 真彩 24位, 真彩 32位
JUMPSERVER_DPI=120                           # 图像每英寸长度内的像素点数 120, 160, 240 等
JUMPSERVER_DISABLE_AUDIO=False               # 禁止声音 true, false  无(允许声音)
JUMPSERVER_ENABLE_WALLPAPER=False            # 启用墙纸 true, false  无（禁用）
JUMPSERVER_ENABLE_THEMING=False              # 启用主题 true, false  无（禁用）
JUMPSERVER_ENABLE_FONT_SMOOTHING=False       # 启用平滑字体 true, false  无（禁用）
JUMPSERVER_ENABLE_FULL_WINDOW_DRAG=False     # 启用拖拽窗口时渲染全部内容 true, false  无（禁用）
JUMPSERVER_ENABLE_DESKTOP_COMPOSITION=False  # 启用透明窗口和阴影等图形效果 true, false  无（禁用）
JUMPSERVER_ENABLE_MENU_ANIMATIONS=False      # 启用菜单开关动画 true, false  无（禁用）
```
将 `JUMPSERVER_ENABLE_WALLPAPER=True` 写入 `/opt/jumpserver/config/config.txt` 然后重启 JumpServer 即可
```bash
# /opt/jumpserver/config/config.txt
...
JUMPSERVER_ENABLE_WALLPAPER=True
```

**Comment by sanpichen** [comment]
已按指引修改，容器中也已经生效，但是没有效果。
![图片](https://user-images.githubusercontent.com/38068938/203886085-a99456f3-2c8b-4a88-baa0-3aacc4daf8a2.png)

**Comment by wojiushixiaobai** [comment]
检查是否有其他规则限制，比如组策略

**Comment by sanpichen** [comment]
已解决：
JUMPSERVER_ENABLE_WALLPAPER=True 有点瑕疵，修改为：JUMPSERVER_ENABLE_WALLPAPER=true

也就是true的首字母小写生效。
