### ISSUE TITLE
[Feature] 连接k8s集群后，希望jsonpath中可以不加转义符直接执行。

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#9126]
**请描述您的需求或者改进建议.**
连接k8s容器集群后，命令中的jsonpath不添加转义符，执行会报错，符号较多时容易出错，希望可以进行优化。
报错：
![报错](https://user-images.githubusercontent.com/89773363/204203915-28bb52dc-8074-4c08-b0bc-c89a32d62d53.png)
添加转义符后可以正常执行：
<img width="1137" alt="添加转义后可以正常执行" src="https://user-images.githubusercontent.com/89773363/204203936-c7dc8ada-2e73-448c-b9ff-bfa396f3847b.png">

**Comment by BaiJiangJie** [comment]
研究了一下，后端不太好处理。
