### ISSUE TITLE
v0.5.0-Nginx-luna跳转jumpserver首页

### ISSUE THREAD

**Issue by henry-zhang** [jumpserver/jumpserver#913]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.5.0
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

server {
    listen 80;

  location /luna/ {
    try_files $uri / /index.html;
    alias /opt/luna/dist;
  }
  
  location /socket.io/ {
        proxy_pass http://localhost:5000/socket.io/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # WebSocket support (nginx 1.4)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
  }

  location / {
        proxy_pass http://localhost:8080;
  }

}

##### 具体表现[截图可能会更好些,最好能截全]
点击回放， 自动跳转到jumpserver首页

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
你怎么搞这个地址   /opt/luna/dist 如果非开发者，请使用release版本

**Comment by henry-zhang** [comment]
我是自己buil的，后来也尝试下载release的版本，也遇到了这个错误跳转的问题
cd /opt
$ git clone https://github.com/jumpserver/luna.git
$ cd luna && npm install && npm run-script build

**Comment by henry-zhang** [comment]
nginx 片段：  
 location /luna/ {
          try_files $uri  / /index.html;
          alias /opt/luna/tmp/luna/;
}



luna release 最新的版本
[root@localhost luna]# md5sum ../luna.tar.gz
0e5e2a5a927a67cd7c678e68cd1035d2  ../luna.tar.gz
[root@localhost luna]# pwd
/opt/luna/tmp/luna
[root@localhost luna]# ls
3rdpartylicenses.txt                                 OpenSans-Italic.9b30f13428e1b4a659ae.ttf
favicon.ico                                          OpenSans-Italic.d6671d41dde41d355619.svg
fontawesome-webfont.674f50d287a8c48dc19b.eot         OpenSans-Italic.e487b7cb072550896dde.eot
fontawesome-webfont.912ec66d7572ff821749.svg

**Comment by henry-zhang** [comment]
After changed as the following , works.
      location /luna/ {
          index index.html;
          try_files $uri  $uri/ /luna/index.html;
          root /opt/luna/tmp/;
}

**Comment by liuzheng** [comment]
@henry-zhang 为什么root你填成tmp？root填的path应该是ls 该path直接出各种Luna的文件
