### ISSUE TITLE
[Bug] 调整web-cli窗口大小后字符显示混乱

### ISSUE THREAD

**Issue by a2659802** [jumpserver/jumpserver#9132]
**JumpServer 版本(v1.5.9以下不再支持)**
2.27.0

**浏览器版本**
Chrome 107.0.5304.121（正式版本） （64 位）

**Bug 描述**
调整web-cli窗口大小后字符显示混乱（见下方gif)

**Bug 重现步骤(有截图更好)**
1. 输入几行回车，将光标移动到大概中间的位置
2. 输入一长串的字符，超出当前窗口折行到下一行
3. 缩小窗口
4. 放大窗口
![resize](https://user-images.githubusercontent.com/38930113/204731258-107b2a44-ed08-49e9-a8d7-419cdaa57d26.gif)

可以看到有一些字符在放大后显示出现异常

**Comment by LeeEirc** [comment]
可能是正常现象吧，放大和缩小窗口之后，会改变当前的行宽设置。待后续看看 xterm.js 是不是有设置的地方。
