### ISSUE TITLE
[Feature] 是否可以禁止”记住密码到浏览器“和显示密码明文

### ISSUE THREAD

**Issue by 37491** [jumpserver/jumpserver#9142]
**请描述您的需求或者改进建议.**
是否可以在管理后台禁掉这个选项和显示密码明文(使用动态用户名/密码时的出现)？
![image](https://user-images.githubusercontent.com/113976090/205026603-85811249-0fbe-4433-8ba5-2d346323f6e9.png)

**Comment by ibuler** [comment]
产品上目前这么设计的，记住密码到浏览器也会加密的
