### ISSUE TITLE
[Bug] 对接keycloak的OIDC认证无法登录，页面提示Bad Request

### ISSUE THREAD

**Issue by LyleLaii** [jumpserver/jumpserver#9146]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.26.1

**浏览器版本**
chrome 105.0.5195.127

**Bug 描述**
配置完成且正常使用一段时间突然出现无法登录，页面提示400。在jms_core容器内没有找到相关报错日志。
![image](https://user-images.githubusercontent.com/23184705/205209138-b468ae71-1394-4554-abcf-56132bd7d4df.png)

认证模块相关日志是在哪里呢？

**Comment by wojiushixiaobai** [comment]
检查你的认证服务器是否正确请求并返回 jumpserver 所需信息。

如果正确返回报 400，请将认证服务器升级为 https 访问，jumpserver 也不需要 https

**Comment by LyleLaii** [comment]
我的认证服务器没有问题，其他业务正常运行。jumpserver的配置也没有调整。能否提供相关日志的路径，我先检查下日志看。

**Comment by wojiushixiaobai** [comment]
日志查看方式参考 [查询日志方法](https://docs.jumpserver.org/zh/master/faq/other/#_2)

**Comment by LyleLaii** [comment]
该部分日志是在哪个模块？我已经查看过core服务的相关日志了，没有看到相关的输出

**Comment by wojiushixiaobai** [comment]
正常输出到 jumpserver.log
