### ISSUE TITLE
在没有做过变更的情况下突然无法登录

### ISSUE THREAD

**Issue by PayneRose** [jumpserver/jumpserver#9148]
**我在k8s1.22版本中部署了jms v2.28.1版本，在部署后使用了大约几天的时间，突然无法登录了，输入密码后无法自动跳转到登录界面，发现jumpserver-jms-celery容器有crash现象，但是重启后没有复现**
![image](https://user-images.githubusercontent.com/28387352/205248506-1e73dd90-56e8-4660-9c6c-6b344be23b60.png)

**Comment by wojiushixiaobai** [comment]
看看日志，应该 redis 有问题或者存储出问题。

**Comment by PayneRose** [comment]
我重新部署了服务，又可以了，但是我找不到原因，先关闭了
