### ISSUE TITLE
[Question] 从2.23.2升级到2.28.1后服务无法启动

### ISSUE THREAD

**Issue by hugeng1979** [jumpserver/jumpserver#9153]
**请描述您的问题.**
原版本2.23.2，使用一直正常。
用通用的升级方式进行升级（以前这样升级过多次）。先wget文件，再解压缩执行./jmsctl.sh upgrade 
这次启动命令时，发现多出现了一个lb，造成服务无法启动，请问怎么解决？还需要我补充什么信息吗？
9443端口是https，存在文件config/nginx/lb_http_server.conf  在这个文件里写了nginx关于ssl站点的参数。

[root@jump jumpserver-installer-v2.28.1]# ./jmsctl.sh stop
Stopping jms_core ... done
Stopping jms_koko ... done
Stopping jms_lion ... done
Stopping jms_magnus ... done
Stopping jms_celery ... done
ERROR: No such service: lb
Removing jms_core ... done
Removing jms_koko ... done
Removing jms_lion ... done
Removing jms_magnus ... done
Removing jms_web ... done
Removing jms_celery ... done
ERROR: No such service: lb
[root@jump jumpserver-installer-v2.28.1]# ./jmsctl.sh start
WARNING: Found orphan containers (jms_lb) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
jms_mysql is up-to-date
jms_redis is up-to-date
Creating jms_core ... done
Creating jms_koko ...
Creating jms_celery ...
Creating jms_lion   ...
Creating jms_magnus ...
Creating jms_koko   ... done
Creating jms_celery ... done
Creating jms_lion   ... done
Creating jms_magnus ... done
32cfd484d): Bind for 0.0.0.0:9443 failed: port is already allocated

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint jms_web (5f068a48c9717dc0378e387a46e03ef088e8afd49edce589c0f70e732cfd484d): Bind for 0.0.0.0:9443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
[root@jump jumpserver-installer-v2.28.1]#

**Comment by hugeng1979** [comment]
在升级时，没有下载jms-lb类似的镜像。
2. 加载 Docker 镜像
[jumpserver/redis:6.2]
6.2: Pulling from jumpserver/redis
6.2: Pulling from jumpserver/redis
Digest: sha256:8463f73cb16d85c7b671ec6a198839529cdcd275ef4e7201ad99978845ebd4f1
Status: Image is up to date for jumpserver/redis:6.2

[jumpserver/mysql:5.7]
5.7: Pulling from jumpserver/mysql
Digest: sha256:24fe4f4aaf4dd86920612aa925693da731dd35e6ab2146b860c8a2b3b750bd58
Status: Image is up to date for jumpserver/mysql:5.7

[jumpserver/core:v2.28.1]
v2.28.1: Pulling from jumpserver/core
Digest: sha256:7ac1a6abb1dc5ed0f9c9c7da6f5a37d8cf17c979392138e9bc23e1f1d0141c97
Status: Image is up to date for jumpserver/core:v2.28.1

[jumpserver/koko:v2.28.1]
v2.28.1: Pulling from jumpserver/koko
Digest: sha256:209de44819512cfb9deba431a00c78048796608506028932f01d99143b32b88c
Status: Image is up to date for jumpserver/koko:v2.28.1

[jumpserver/lion:v2.28.1]
v2.28.1: Pulling from jumpserver/lion
Digest: sha256:e526890a72b464d35dbfc2f35d391f62e756fa3c3338a78ab48be1c0799e1700
Status: Image is up to date for jumpserver/lion:v2.28.1

[jumpserver/magnus:v2.28.1]
v2.28.1: Pulling from jumpserver/magnus
Digest: sha256:72ccdc36951e3ba63c17b68ea8ea5e1c0fbb237f19184a76b4006d2da2d75452
Status: Image is up to date for jumpserver/magnus:v2.28.1

[jumpserver/web:v2.28.1]
v2.28.1: Pulling from jumpserver/web
Digest: sha256:a7065804f135f3d1fef15412adec99d62475e42e48c0ec6934d7fc4b44aae1ad
Status: Image is up to date for jumpserver/web:v2.28.1

完成

3. 备份数据库
正在备份...

**Comment by hugeng1979** [comment]
不好意思，我查了之前的版本2.23.2是有jms_lb的，但是在两个版本的目录中查看docker-compose-lb.yml 。两个版本的此文件差异很大。

root@jump jumpserver-installer-v2.28.1]# cat ../jumpserver-installer-v2.23.2/compose/docker-compose-lb.yml
version: '2.4'

services:
  lb:
    image: jumpserver/web:${VERSION}
    container_name: jms_lb
    ulimits:
      core: 0
    restart: always
    tty: true
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      USE_IPV6: ${USE_IPV6}
      SERVER_NAME: ${SERVER_NAME:-}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE:-}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY:-}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    volumes:
      - ${VOLUME_DIR}/lb/log:/var/log/nginx
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${CONFIG_DIR}/nginx/lb_http_server.conf:/etc/nginx/sites-enabled/jumpserver.conf
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: "curl -fs http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - net
[root@jump jumpserver-installer-v2.28.1]# cat compose/docker-compose-lb.yml
version: '2.4'

services:
  web:
    ports:
      - ${HTTPS_PORT:-443}:${HTTPS_PORT:-443}
    environment:
      HTTPS_PORT: ${HTTPS_PORT:-443}
      SERVER_NAME: ${SERVER_NAME:-}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE:-}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY:-}
    volumes:
      - ${CONFIG_DIR}/nginx/cert:/etc/nginx/cert
      - ${CONFIG_DIR}/nginx/lb_http_server.conf:/etc/nginx/sites-enabled/jumpserver.conf

**Comment by hugeng1979** [comment]
我对比了现有的config.txt与 git里的config.txt，发现有很多不一样的地方。我以git里的config.txt为蓝本进行修改，现在网站已经恢复。只是还有小问题。
1. stop停止服务时，会提示
[root@jump tmp]# /opt/jumpserver-installer-v2.28.1/jmsctl.sh stop
Stopping jms_core ... done
Stopping jms_koko ... done
Stopping jms_lion ... done
Stopping jms_magnus ... done
Stopping jms_web ... done
Stopping jms_celery ... done
ERROR: No such service: lb
Removing jms_core ... done
Removing jms_koko ... done
Removing jms_lion ... done
Removing jms_magnus ... done
Removing jms_web ... done
Removing jms_celery ... done
ERROR: No such service: lb

2.jmsctl.sh status 会发现jms_magnus占用了从0到9999端口，见截图
<img width="766" alt="iShot_2022-12-03_22 00 37" src="https://user-images.githubusercontent.com/35301810/205444756-58f6966b-1af8-42dc-a662-7bdb2e841f88.png">

另外我现在的config.txt如下
`# JumpServer configuration file example.
#
# 如果不了解用途可以跳过修改此配置文件, 系统会自动填入
# 完整参数文档 https://docs.jumpserver.org/zh/master/admin-guide/env/

################################## 镜像配置 ###################################
#
# 国内连接 docker.io 会超时或下载速度较慢, 开启此选项使用华为云镜像加速
# 取代旧版本 DOCKER_IMAGE_PREFIX
#
# DOCKER_IMAGE_MIRROR=1

################################## 安装配置 ###################################
#
# JumpServer 数据库持久化目录, 默认情况下录像、任务日志都在此目录
# 请根据实际情况修改, 升级时备份的数据库文件(.sql)和配置文件也会保存到该目录
#2
VOLUME_DIR=/opt/jumpserver

# 加密密钥, 迁移请保证 SECRET_KEY 与旧环境一致, 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 SECRET_KEY
#
SECRET_KEY=

# 组件向 core 注册使用的 token, 迁移请保持 BOOTSTRAP_TOKEN 与旧环境一致,
# 请勿使用特殊字符串
# (*) Warning: Keep this value secret.
# (*) 勿向任何人泄露 BOOTSTRAP_TOKEN
#
BOOTSTRAP_TOKEN=

# 日志等级 INFO, WARN, ERROR
#
LOG_LEVEL=ERROR

# JumpServer 容器使用的网段, 请勿与现有的网络冲突, 根据实际情况自行修改
#
DOCKER_SUBNET=192.168.250.0/24

# ipv6 nat, 正常情况下无需开启
# 如果宿主不支持 ipv6 开启此选项将会导致无法获取真实的客户端 ip 地址
#
USE_IPV6=0
DOCKER_SUBNET_IPV6=fc00:1010:1111:200::/64

################################# MySQL 配置 ##################################
# 外置 MySQL 需要输入正确的 MySQL 信息, 内置 MySQL 系统会自动处理
#
DB_ENGINE=mysql
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=jumpserver

################################# Redis 配置 ##################################
# 外置 Redis 需要请输入正确的 Redis 信息, 内置 Redis 系统会自动处理
#
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# 如果使用外置 Redis Sentinel, 请手动填写下面内容
#
# REDIS_SENTINEL_HOSTS=mymaster/192.168.100.1:26379,192.168.100.1:26380,192.168.100.1:26381
# REDIS_SENTINEL_PASSWORD=your_sentinel_password
# REDIS_PASSWORD=your_redis_password

################################## 访问配置 ###################################
# 对外提供服务端口, 如果与现有服务冲突请自行修改
# 如果不想对外提供访问可以使用 127.0.0.1:<port>, eg: 127.0.0.1:33060
#
HTTP_PORT=80
SSH_PORT=2222
MAGNUS_PORTS=30000-30100

################################# HTTPS 配置 #################################
# 参考 https://docs.jumpserver.org/zh/master/admin-guide/proxy/ 配置
#
HTTPS_PORT=9443

#
CLIENT_MAX_BODY_SIZE=4096m

################################## 组件配置 ###################################
# 组件注册使用, 默认情况下向 core 容器注册, 集群环境需要修改为集群 vip 地址
#
CORE_HOST=http://core:8080
PERIOD_TASK_ENABLED=True

# Core Session 定义,
# SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期,
# SESSION_EXPIRE_AT_BROWSER_CLOSE=true 表示关闭浏览器即 session 过期
#
# SESSION_COOKIE_AGE=86400
SESSION_EXPIRE_AT_BROWSER_CLOSE=True

# Lion 开启字体平滑, 优化体验
#
JUMPSERVER_ENABLE_FONT_SMOOTHING=True

################################# XPack 配置 #################################
# XPack 包, 开源版本设置无效
#
RDP_PORT=3389

################################## 其他配置 ##################################
# 终端使用宿主 HOSTNAME 标识, 首次安装自动生成
#
SERVER_HOSTNAME=${HOSTNAME}

# 当前运行的 JumpServer 版本号, 安装和升级完成后自动生成
#
CURRENT_VERSION=v2.28.1
`

**Comment by wojiushixiaobai** [comment]
```
Bind for 0.0.0.0:9443 failed: port is already allocated
```
端口冲突

`jms_magnus占用了从0到9999端口`  端口只是标识， Dockerfile 不当导致，只是申明了该端口，并未使用，也不对外提供服务

- link: https://github.com/jumpserver/jumpserver/issues/9007

**Comment by hugeng1979** [comment]
那不再需要jms_lb组件，怎么清理可以避免stop时出现
ERROR: No such service: lb     这个提示。

**Comment by wojiushixiaobai** [comment]
请按照官方文档升级，在新的 installer 目录执行下面命令即可
```bash
docker stop jms_lb
docker rm jms_lb
```
```bash
./jmsctl.sh start
```

**Comment by hugeng1979** [comment]
还是不行。我先执行docker stop jms_lb ，提示Error response from daemon: No such container: jms_lb
然后再次执行upgrade升级，升级完全正常。 升级后start没有问题，再stop，还是ERROR: No such service: lb

8. 升级成功, 可以重新启动程序了
cd /opt/jumpserver-installer-v2.28.1
./jmsctl.sh start


[root@jump jumpserver-installer-v2.28.1]# ./jmsctl.sh start
jms_redis is up-to-date
jms_mysql is up-to-date
Creating jms_core ... done
Creating jms_lion   ... done
Creating jms_web    ... done
Creating jms_celery ... done
Creating jms_magnus ... done
Creating jms_koko   ... done
[root@jump jumpserver-installer-v2.28.1]# docker stop jms_lb
Error response from daemon: No such container: jms_lb
[root@jump jumpserver-installer-v2.28.1]# ./jmsctl.sh stop
Stopping jms_core ... done
Stopping jms_koko ... done
Stopping jms_lion ... done
Stopping jms_magnus ... done
Stopping jms_web ... done
Stopping jms_celery ... done
ERROR: No such service: lb
Removing jms_core ... done
Removing jms_koko ... done
Removing jms_lion ... done
Removing jms_magnus ... done
Removing jms_web ... done
Removing jms_celery ... done
ERROR: No such service: lb

**Comment by china-live** [comment]
有后续吗？我现在也是2.23.2  准备升级呢

**Comment by wojiushixiaobai** [comment]
@hugeng1979 操作不当导致，请在新的 installer 里面执行命令而不是在旧版本的 installer 中执行
@china-live 参考文档升级即可，当前升级无问题
