### ISSUE TITLE
[Bug] Celery任务日志窗口不显示内容

### ISSUE THREAD

**Issue by Anorpi** [jumpserver/jumpserver#9156]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.1

**浏览器版本**
Chrome 版本 108.0.5359.95（正式版本） （64 位）

**Bug 描述**
1. 浏览器窗口不显示 Celery任务日志
2. 在 作业中心-任务列表-可以看到执行列表，但点击“输出”，跳出的  Celery任务日志 窗口，不显示任何内容。

**Bug 重现步骤(有截图更好)**
点击测试：
![jmp-iss1](https://user-images.githubusercontent.com/7035867/205589930-f0c8f79b-2168-4f46-8264-ef5cedf4e53b.png)

点击输出：

![Snipaste_2022-12-05_16-31-38](https://user-images.githubusercontent.com/7035867/205590275-05c43f74-89bc-4712-bb95-fbf006b3871e.png)

**Comment by wojiushixiaobai** [comment]
单节点出现此问题表示你反向代理有问题或者未配置 websocket 支持（waf 拦截）等。

多节点请配置共享存储，确定所有节点均可访问共享存储的文件信息

**Comment by Anorpi** [comment]
是按照官网的部署文档 “安装配置-负载均衡”，部署了第一台实例，其他节点打算后续部署。
没有使用共享存储，用的本地存储。

然后直接解析到主机IP进行访问的，这个实际上应该就算是单节点部署吧。前面没有配置nginx，也没有waf设置。

**Comment by Anorpi** [comment]
这边使用尝试使用 家庭网络 进行了登录连接，同样是不显示日志。

**Comment by Anorpi** [comment]
Redis 版本问题，Redis 4.0 更换至 5.0 后，问题解决了。
