### ISSUE TITLE
python run_server.py无法直接启动

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#916]
##### 使用版本
[版本  0.5.0-2 GPLv2.]

启动命令python run_server.py 无法启动报错：
usage: run_server.py [-h]
                     {all,gunicorn,celery,beat}
                     [{all,gunicorn,celery,beat} ...]
run_server.py: error: the following arguments are required: services

使用：nohup python run_server.py all &才能启动，这样正常吗？

**Comment by qianghong000** [comment]
123

**Comment by yamin-zou** [comment]
小白 前来同问，还不能直接停。

**Comment by ibuler** [comment]
python run_server.py all

**Comment by ibuler** [comment]
可以放到 screen中执行

**Comment by qianghong000** [comment]
nohup python run_server.py all &  这样启动也可以吧

**Comment by ibuler** [comment]
可以

**Comment by qianghong000** [comment]
ok，多谢~

**Comment by testueu** [comment]
请问在哪里可以下再0.3版本的jumpserver

**Comment by qianghong000** [comment]
https://github.com/jumpserver/jumpserver/archive/0.3.3.zip

**Comment by testueu** [comment]
@qianghong000  请问有0.4版本的jumpserver么

**Comment by qianghong000** [comment]
@ibuler 有命令可以关闭服务吗？现在用kill杀掉的
