### ISSUE TITLE
启动时运行python run_server.py all报错 beat: Waking up in 1.00 minute.

### ISSUE THREAD

**Issue by xyw324** [jumpserver/jumpserver#917]
[简述你的问题]

##### 使用版本
 [0.5.0]

##### 问题复现步骤
启动时运行python run_server.py all报错

##### 具体表现[截图可能会更好些,最好能截全]

Task create new adhoc: 定期更新资产硬件信息
Task assets.tasks.update_assets_hardware_info_period[e35c4ee3-9bd4-4118-bc9c-78f902b4dfab] succeeded in 0.02658176000113599s: None
beat: Synchronizing schedule...
Writing entries...
DatabaseScheduler: Schedule changed.
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: assets.tasks.update_assets_hardware_info_period assets.tasks.update_assets_hardware_info_period(*[], **{}) <freq: 1.00 hour>>
<ModelEntry: assets.tasks.test_admin_user_connectability_period assets.tasks.test_admin_user_connectability_period(*[], **{}) <freq: 1.00 hour>>
<ModelEntry: assets.tasks.test_system_user_connectability_period assets.tasks.test_system_user_connectability_period(*[], **{}) <freq: 1.00 hour>>
<ModelEntry: assets.tasks.push_system_user_period assets.tasks.push_system_user_period(*[], **{}) <freq: 1.00 hour>>
<ModelEntry: terminal.signals_handler.set_session_info_cache terminal.signals_handler.set_session_info_cache(*[], **{}) <freq: 1.00 hour>>
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4 * * * (m/h/d/dM/MY)>>
<ModelEntry: 定期更新资产硬件信息 ops.tasks.run_ansible_task(*['228c8d63-15fb-4cf2-8907-5f55e4b404c5'], **{'callback': 'assets.tasks.set_assets_hardware_info'}) <freq: 1.00 day>>
beat: Waking up in 1.00 minute.
此处一直卡
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这不是报错，就应该卡到这里

**Comment by sinerxx** [comment]
定时任务多了之后，页面加载太卡了

**Comment by ppbibo** [comment]
问一下，这种情况怎么解决呢？？

**Comment by ppbibo** [comment]
我也遇到了相似的问题
启动卡在这
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.

**Comment by ibuler** [comment]
不用解决，前台运行的，就是这样
