### ISSUE TITLE
[Question]一键新装，启动过程 failed to register layer

### ISSUE THREAD

**Issue by thtznet** [jumpserver/jumpserver#9172]
**请描述您的问题.**
使用的 curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.28.1/quick_start.sh | bash 安装。
启动过程出现如下错误：
![image](https://user-images.githubusercontent.com/11564763/206107451-38c0e424-0a40-44d5-a729-00b96565445e.png)

**Comment by wojiushixiaobai** [comment]
安全软件拦截

**Comment by thtznet** [comment]
> 安全软件拦截

全新的debian，没有安装软件，网络上也没有防火墙。

**Comment by wojiushixiaobai** [comment]
请仔细检查，此问题基本都是安全软件拦截导致。
可以自行部署测试环境对比。
