### ISSUE TITLE
[Bug] koko客户端

### ISSUE THREAD

**Issue by xq-zoro** [jumpserver/jumpserver#9176]
**JumpServer 版本(v1.5.9以下不再支持)**
 2.28.1版本

**浏览器版本**

**Bug 描述**
KOKO 客户端，进入mysql数据库后，CTRL C 期望断开正在执行的SQL，
目前却会直接退出客户端，

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/49966849/206389812-d3b48787-88f0-492f-bb7a-1187f17bd147.png)

2. 
3.

**Comment by LeeEirc** [comment]
linux 系统下 mysql 命令行客户端连接，使用 CTRL C 就是直接退出客户端，属于默认行为。

**Comment by xq-zoro** [comment]
会有这种情况，当我运行的Sql 执行时间过长或者我想中断正在执行的Sql，这时候 CTRL C 就会直接退出，这样是不是风险项呢，因为我并不清楚 CTRL C 后的Sql运行状态
