### ISSUE TITLE
[Bug] Web GUI 登录 Windows 手动输入密码包含单引号未在页面提示

### ISSUE THREAD

**Issue by JonnnLOL** [jumpserver/jumpserver#9177]
**JumpServer 版本(v1.5.9以下不再支持)**
2.28.1

**浏览器版本**
Microsoft Edge
版本 107.0.1418.62 (正式版本) (64 位)

**Bug 描述**
系统用户密码配置为手动输入，Web GUI 登录 Windows 黑屏，按 F12 才发现返回结果密码不能包含 `'` 字符，这项提醒未在页面提示

**Bug 重现步骤(有截图更好)**
1.  系统用户密码配置为手动输入
2. Web GUI 登录 Windows 黑屏
3. F12 可以看到返回结果密码不能包含 `'` 字符
![image](https://user-images.githubusercontent.com/95204418/206392807-9e0d6c0c-c7c6-4d55-983e-98b07333d6e2.png)

**Comment by BaiJiangJie** [comment]
v3 版本对这一块有优化，可以在新版本中试一下问题是否还存在。

如果存在，可以再打开当前 Issue。
