### ISSUE TITLE
[Question]命令存储出现问题，日志提示ES版本不行

### ISSUE THREAD

**Issue by fight-club-2021** [jumpserver/jumpserver#9180]
发现在jumpserver v2.27.0版本下，用magnus数据库代理的方式连接数据库执行sql命令后，sql命令不会存储到已设置的es中，而是存到默认存储里。看日志提示信息如下：
![image](https://user-images.githubusercontent.com/93704543/206410925-b0857464-dd57-4c92-86db-17eed83a610d.png)

**想问下jumpserver v.2.27.0版本的命令存储功能，支持哪个版本的elasticsearch ？**

**Comment by fight-club-2021** [comment]
用的es事 aws上的es 7.4

**Comment by LeeEirc** [comment]
看着像是 go 的 es-sdk 不兼容。 magnus 容器内上传命令使用的 es-sdk 是 v7.16.0。你升级下，能解决吗？

**Comment by fight-club-2021** [comment]
> 看着像是 go 的 es-sdk 不兼容。 magnus 容器内上传命令使用的 es-sdk 是 v7.16.0。你升级下，能解决吗？

求教，这该如何升级，我的jumpserver是部署在k8s里的，我查了magnus的dockerfile没看到有安装es-sdk的。

**Comment by LeeEirc** [comment]
容器内使用的 es-sdk 集成在 [wisp](https://github.com/jumpserver/wisp) 内，我意思是升级下你 es 服务的版本，是否能解决。如果不行的话，可能需要降级 wisp 的 es-sdk 的版本。

**Comment by fight-club-2021** [comment]
> 容器内使用的 es-sdk 集成在 [wisp](https://github.com/jumpserver/wisp) 内，我意思是升级下你 es 服务的版本，是否能解决。如果不行的话，可能需要降级 wisp 的 es-sdk 的版本。

那我试试降级wisp的es-sdk版本，在用的es难升级，因为很多人在用。

**Comment by LeeEirc** [comment]
> 那我试试降级wisp的es-sdk版本，在用的es难升级，因为很多人在用。

降级之后，可以上传命令了吗？ @fight-club-2021
