### ISSUE TITLE
[Question] Connect JumpServer to VPN 🚀

### ISSUE THREAD

**Issue by nmella** [jumpserver/jumpserver#9181]
Hi guys 👋, new here. 

I was testing jumpserver and it works awesome ! Thanks for the great piece of work ! 👍

How can I add assets which are behind a VPN network ? We typically connect to the VPN network with OpenVPN or FortiVPN client. I check the "**Domains >> Gateway**" section, but it seems the only option is SSH protocol. 

So, I am lost on how to connect to the VPN.

Thanks for any tip or advice !

**Comment by wojiushixiaobai** [comment]
Connect to your VPN on "**any server**".
Use this "**any server**" for the JumpServer "Domains >> Gateway"

**Comment by nmella** [comment]
Thank you @wojiushixiaobai ! Will try that. !
