### ISSUE TITLE
[Question] 启用OIDC连接至provide时返回错误，并重复循环登录，疑似jumpserver缺少 PKCE 功能

### ISSUE THREAD

**Issue by doveyoung1126** [jumpserver/jumpserver#9197]
**请描述您的问题.**
1. 启用 OIDC 功能并填入各值
2. 尝试使用 OIDC 登录 jumpserver
3. 循环重定向至登录界面
4. provide返回错误信息 Authorization Server policy requires PKCE to be used for this request

在 jumpserver 的设置界面没有看到相关的设置，provide 是 [logto](https://github.com/logto-io/logto) ，已明确表示必须开启 PKCE 
请问是不支持 PKCE，还是我没找到设置的地方？
![image](https://user-images.githubusercontent.com/44560122/207018254-6a486d73-f07f-4af6-8d64-0e5af3f6f17c.png)

**Comment by Hi-JWD** [comment]
我们本地搞个环境测试一下，再回复哈

**Comment by doveyoung1126** [comment]
好的，期待您的回复
好像是缺少 
code_challenge_method: 
    - S256
    - plain

**Comment by Hi-JWD** [comment]
> 好的，期待您的回复 好像是缺少 code_challenge_method: - S256 - plain

最新版本已经支持
可安装测试
