### ISSUE TITLE
[Bug] 存在巨大安全隐患

### ISSUE THREAD

**Issue by klzdy123** [jumpserver/jumpserver#9209]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.4

**浏览器版本**
chrome 版本 108.0.5359.98（正式版本） (x86_64)

**Bug 描述**
应用授权 授权了MySQL 之后，使用 web终端以 DB Client 方式连接，复制相关登录信息在自己电脑上使用数据库客户端工具进行连接，当设置该授权用户为失效后，原有 数据库客户端工具 还能继续访问和操作数据库

**Bug 重现步骤(有截图更好)**
1.  应用管理-添加 MySQL 数据库
2. 应用授权给某一个用户
3. 使用 Web终端，以 DB Client 方式连接
4. 获取相关数据库信息后，使用 数据库客户端工具 进行配置和连接
5. 后台将该应用授权删除或者设置为失效
6. 数据库客户端工具 任然可以继续使用（😨）

**Comment by wojiushixiaobai** [comment]
当前不会限制已经建立连接的会话。
从安全角度考虑这是一个问题；
但是从使用人员和管理人员角度考虑，这是一个折衷的方案，不允许建立新的连接，单号会防止正在操作的会话突然断开。

后续我们看看是否需要添加授权到期立即断开的功能

**Comment by klzdy123** [comment]
好的，可以考虑 给管理员就还是保持当前方案；
对于其他子用户或组，则直接断开会话。
