### ISSUE TITLE
小白邮件发不出去啊 [Errno 111] 

### ISSUE THREAD

**Issue by yamin-zou** [jumpserver/jumpserver#921]
[简述你的问题]
发送邮件不出去
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.5.0-2 GPLv2.
##### 问题复现步骤
1. [步骤1]

点击发送重置密码邮件

##### 具体表现[截图可能会更好些,最好能截全]
报错如下：
2018-01-16 11:30:49 [tasks ERROR] Sending mail error: [Errno 111] Connection refused
Sending mail error: [Errno 111] Connection refused
Task common.tasks.send_mail_async[df38918b-bffc-4724-b3d0-6d4e9db1381b] succeeded in 0.006953117001103237s: None

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
系统设置页面设置email，测试一下连接

**Comment by xyw324** [comment]
邮件协议端口一般不用25 ，用ssl加密端口

**Comment by yamin-zou** [comment]
系统设置页面？ 是指正广和文件 config.py 吗？ 是这样设置的吗？
class DevelopmentConfig(Config):
    EMAIL_HOST = 'mail.xxx.com'
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = True
    EMAIL_HOST_USER = 'op@xxx.com'
    EMAIL_HOST_PASSWORD = 'xxxxx'
    EMAIL_SUBJECT_PREFIX = '[Jumpserver] '
    SITE_URL = 'http://172.25.10.83:8080' 


class TestConfig(Config):
    pass

**Comment by wojiushixiaobai** [comment]
@yamin-zou 
TLS 和 SSL 都 false 试试，确定当前服务器环境可以正常访问邮箱服务器。

**Comment by testueu** [comment]
我使用的0.5 没有系统设置那一选项呀

**Comment by wojiushixiaobai** [comment]
@testueu 可以更新到最新，
cd jumpserver && git checkout dev

**Comment by yamin-zou** [comment]
搞定了 ，谢谢大家，另外问下，加了ladp然后怎么测试可以用啊？我直接用ldap用户登录好像不行

**Comment by wojiushixiaobai** [comment]
@yamin-zou 邮件设置的旁边有LDAP设置，里面可以测试

**Comment by yamin-zou** [comment]
@wojiushixiaobai 我设置了，也成功了，那么用户还是要自己建吗？只是密码不用设置？

**Comment by yamin-zou** [comment]
@wojiushixiaobai 搞定了,中文界面 启用ldap 翻译成二次验证, 一下子没反应过来,没勾上。

**Comment by vlingfu** [comment]
@yamin-zou 启用ldap在哪勾选。？ 请问
