### ISSUE TITLE
[Bug] 无法处理反向代理的header导致在登陆的时候触发CSRF防护，无法登录

### ISSUE THREAD

**Issue by 0pera** [jumpserver/jumpserver#9210]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.4

**浏览器版本**
firefox 最新

**Bug 描述**
我使用了一个OPNsense，装上Nginx插件作为前端的反向代理，但是配置了之后出现无法登录，一到登录页面就提示CSRF 403.
我仔细对比了一下文档里面的反向代理配置和OPNsense生成的Nginx配置文件，并且抓包进行对比，发现是多了几个header，我手动注释掉这几个配置之后就正常了。
包括这么几个：
```
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Host $host;
```

我见到超管登录之后，基本设置中有一个“当前站点URL”
能否在“当前站点URL”和这几个header参数都匹配的情况下，允许通过CSRF检查？

**Bug 重现步骤(有截图更好)**
1.  使用Nginx作为前端反向代理，配置里面配置上述的3个header
2. 登录

**Comment by wojiushixiaobai** [comment]
- Link: https://github.com/jumpserver/jumpserver/pull/9138

**Comment by BaiJiangJie** [comment]
新版本已经有了，试一下解决了吗？
如果有问题的话，再打开当前 Issue。

**Comment by 0pera** [comment]
刚把系统升级到最新版的3.4.0，直接翻源文件的话，可以看到补丁包已经整合进去了。但是我刚才测试还是不行。
只要前端的NGINX包含3个里面的任意一个header都会触发CSRF拦截。
我也不知道哪里能够设置`CSRF_TRUSTED_ORIGINS`，从网页上修改了站点URL也不行。直接修改`/opt/jumpserver/config/config.txt`也不行。不确定是没法将参数传进去还是什么。
另外，Django的版本是4还是3？两个版本的`CSRF_TRUSTED_ORIGINS`参数的格式略有不同。

**Comment by dddddddddd000nnnnnnnnnn** [comment]
我也遇到同样的问题，还请大神们帮忙解决，当前JMS升级到3.4.1，跟上楼一样在/opt/jumpserver/config/config.txt增加CSRF_TRUSTED_ORIGINS，依然不行

**Comment by 0pera** [comment]
经过了一番研究……我找到一个规避的方法。
jms_web是一个用NGINX提供的反向代理，其NGINX配置文件存放在/opt/jumpserver/config/nginx。
可以修改配置文件，在server一节里面，插入
```
    proxy_set_header X-Forwarded-Proto "";
    proxy_set_header X-Forwarded-Port "";
    proxy_set_header X-Forwarded-Host"";
```
这样可以移除前端反向代理添加的这几个header。实测不再出现CSRF告警。
