### ISSUE TITLE
[Bug] oauth2 配置客户端密钥保存后丢失

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9216]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.25.4
**浏览器版本**
最新 chrome

**Bug 描述**
配置 oauth2 正常工作一段时间后发现 oauth2 登录方式失效,排查发现oauth2 配置中客户端密钥一项内容为空,再次配置后保存刷新页面仍未空,jumpserver.log 显示
2022-12-16 18:03:51 [connection ERROR] Consume msg error: Connection closed by server.
redis内执行 keys *
127.0.0.1:6379> keys *
1) "lock:beat-distribute-start-lock"

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by O-Jiangweidong** [comment]
秘钥等敏感信息在页面配置项配置后，是不显示的，默认的会话缓存信息在redis的4号库中，在配置文件config.txt中将LOG_LEVEL改成DEBUG模式，看看详细日志中的报错是什么

**Comment by O-Jiangweidong** [comment]
OAuth2的秘钥信息保存在数据库的settings_setting表中键为AUTH_OAUTH2_CLIENT_SECRET

**Comment by BaiJiangJie** [comment]
理论上不会存在数据丢失的问题。
