### ISSUE TITLE
[Feature] 无用户名密码的MongoDB连接

### ISSUE THREAD

**Issue by phantomlsh** [jumpserver/jumpserver#9217]
**请描述您的需求或者改进建议.**

是否可以支持没有用户名和密码的MongoDB数据库管理？

是否可以支持基于ssh隧道的数据库管理？

我们的数据库场景是：数据库只允许本地访问，数据库连接无法穿透目标主机的防火墙。以往我们是通过MongoDB Compass工具中的ssh隧道连接到目标主机然后访问其本地数据库，请问jumpserver有没有计划支持类似的功能呢？

谢谢！

**Comment by BaiJiangJie** [comment]
`是否可以支持没有用户名和密码的MongoDB数据库管理？`

为了安全，暂时不考虑支持。

`是否可以支持基于ssh隧道的数据库管理？`

在 v2、v3 版本中都可以配置使用网关去代理连接数据库。

**Comment by phantomlsh** [comment]
通过限制数据库仅允许本地访问，通过防火墙等方式而不是通过数据库密码，是一种安全可行的单机数据库实现方案。因此，在ssh隧道进入一个主机后管理上面没有密码的数据库，应该支持在连接数据库时不使用密码。望考虑，谢谢！
