### ISSUE TITLE
[Question]Storage Class使用gp3无法ReadWriteMany

### ISSUE THREAD

**Issue by jesse-zhangh** [jumpserver/jumpserver#9231]
helm部署v2.28.5
在AWS云环境，storge class使用的gp3，gp3不支持ReadWriteMany

能否修改为ReadWriteOnce模式呢？多挂载几个pvc

**Comment by wojiushixiaobai** [comment]
主要是 core 和 celery 需要共享读写，没法共享读写的话，你看看如何合并到 web pod，让前端用户能正常读取到文件。

**Comment by jesse-zhangh** [comment]
@wojiushixiaobai 感谢解答，已经手动弄了nfs pv。
