### ISSUE TITLE
升级到v2.28.5后 测试资产可连接性全部失败,之前加入的节点可以ssh 新加入的不能ssh

### ISSUE THREAD

**Issue by BruceChinese** [jumpserver/jumpserver#9238]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.5

**浏览器版本**

版本 108.0.5359.124（正式版本） (arm64)
**Bug 描述**

升级到v2.28.5后 测试资产可连接性全部失败,之前加入的节点可以ssh 新加入的不能ssh
**Bug 重现步骤(有截图更好)**

**Comment by wojiushixiaobai** [comment]
看起来是账户密码错误导致

**Comment by wojiushixiaobai** [comment]
看起来是账户密码错误导致

**Comment by wojiushixiaobai** [comment]
看起来是账户密码错误导致

**Comment by BruceChinese** [comment]
用的key认证 这个没有动过

**Comment by wojiushixiaobai** [comment]
在 web 页面，系统用户详情里面看下你上传的 key 是否正确，可以明文查看，对比下。

**Comment by BruceChinese** [comment]
并不是所有的节点都不能连接,只有一部分不能 用的全部都是一个key

**Comment by wojiushixiaobai** [comment]
这些无法连接的资产，你将 key 手动复制到本地 key 文件，手动使用 `ssh -i <file.key> <user>@<host> -p <port>` 试试

**Comment by BruceChinese** [comment]
手动连接可以

**Comment by wojiushixiaobai** [comment]
系统用户详情里面里面你查到 key 复制到本地可以？

**Comment by BruceChinese** [comment]
不知道为什么 特权用户的key没了, 重新加上就好了

**Comment by LeeEirc** [comment]
如果升级过程没有报错，不应该会丢失key，你从那个版本升级的？

**Comment by BruceChinese** [comment]
v2.28.1

**Comment by LeeEirc** [comment]
那估计是别的问题，同一个大版本 v2.28，没有数据库迁移文件的变更，不会修改数据库。

**Comment by BruceChinese** [comment]
系统用户能ssh连接,但是点击测试的时候是不能连接这个一般是怎么回事

**Comment by BruceChinese** [comment]
![image](https://user-images.githubusercontent.com/12492229/209909948-1451aac1-8f9e-4324-8832-01e3b2504ced.png)
![image](https://user-images.githubusercontent.com/12492229/209910018-d510a233-a378-4cd3-83c5-b6d5f5ee684e.png)

**Comment by LeeEirc** [comment]
如果还有其他问题，可以新开 issue。
