### ISSUE TITLE
jumpserver 加载静态资源有问题

### ISSUE THREAD

**Issue by Jiangofstudy** [jumpserver/jumpserver#924]
[简述你的问题]

##### 使用版本
jumpserver v0.50

##### 问题复现步骤
jumpserver 加载不到静态资源，一开始是好的

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/28861075/34982246-daca1ee6-fae4-11e7-94c6-8b54ccdda5e2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
可以检查下文件的权限是不是正确的。检查日志

**Comment by Jiangofstudy** [comment]
我是用root用户启动的，权限应该不会有问题的吧？

**Comment by wojiushixiaobai** [comment]
@Jiangofstudy 发图

**Comment by Jiangofstudy** [comment]
![image](https://user-images.githubusercontent.com/28861075/35021462-f32e1c08-fb6b-11e7-9d0f-6e8ac3c4ae8e.png)
![image](https://user-images.githubusercontent.com/28861075/35021476-0588de92-fb6c-11e7-941f-54b461e7eb8c.png)

**Comment by wojiushixiaobai** [comment]
@Jiangofstudy  确定你 apps 目录下的资源文件是正常的，报404的连接，到相应的目录看里面是否有相应的资源。

**Comment by Jiangofstudy** [comment]
确定是相应的目录存在该资源；我刚才从github上又重新拉取了一份 还是报404

**Comment by wojiushixiaobai** [comment]
@Jiangofstudy 方便的话发个远程看下，不方便的话建议你检查下环境。

**Comment by Jiangofstudy** [comment]
我再检查检查

**Comment by michaelzhang02010479** [comment]
I have an same issue,when I visit the website via 8080 is OK,but not work via nginx with the port of 80.

**Comment by XIANGCHAO1990** [comment]
是不是跟网速有关系，有的时候能加载出来，有的时候不能
