### ISSUE TITLE
[Bug] 阿里云MongoDB集群无法网关跳转连接

### ISSUE THREAD

**Issue by tqtcloud** [jumpserver/jumpserver#9241]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.6

**浏览器版本**
chrome 108.0.5359.125

**Bug 描述**
阿里云 MongoDB 集群无法通过网域网关连接

**Bug 重现步骤(有截图更好)**
1.  设置阿里云内网ecs服务器网域网关（ecs通过秘钥对连接）
2. 添加MongoDB数据库，并设置网域
3. 连接直接报错

出现问题后查阅koko日志如下：

![image](https://user-images.githubusercontent.com/86145643/209429942-7327584d-a0d4-40f1-ae30-7fe4de7104d3.png)
redis是可以通过网域网关连接的，就MongoDB不可以。
看日志是直接网关都没连接上，我看是已经有过一版MongoDB的连接优化，但目前升级后仍然连接有问题，尝试过很多次
![image](https://user-images.githubusercontent.com/86145643/209430061-14c03839-6525-4744-9c88-c9d1dba1ef04.png)

**Comment by LeeEirc** [comment]
看着很像是 网关 服务器 sshd 没有开启 ssh 转发。
