### ISSUE TITLE
[Question] Add Windows RDP Admin User

### ISSUE THREAD

**Issue by wonhee0410** [jumpserver/jumpserver#9242]
Hi Team,

When I add Admin Users in Assets, it just shows SSH Protocol.

How could I add RDP and another Protocol to create user ? Thank you.

![image](https://user-images.githubusercontent.com/60768442/209530690-3d47b9fd-c8b6-4e27-be29-e395bb5b875e.png)

**Comment by wojiushixiaobai** [comment]
RDP protocol does not require privileged users.

**Comment by wonhee0410** [comment]
> RDP protocol does not require Admin User.

Excuse me, but how can I add RDP user to auth when connect to Asset ?

I don't fill Auth with Admin user, but when I click connect it shows like this.

![image](https://user-images.githubusercontent.com/60768442/209533831-2482de55-667c-4c33-b74f-4a12a7edcf6c.png)

**Comment by wojiushixiaobai** [comment]
Create a Common user.
![image](https://user-images.githubusercontent.com/24326988/209535361-205bb439-147f-4ccf-844c-5e0d989a489b.png)

Associate this system user in Asset Permissions.
![image](https://user-images.githubusercontent.com/24326988/209535658-404b13b1-8948-4df3-b17a-d27dedaa4809.png)

**Comment by wonhee0410** [comment]
> Create a Common user. ![image](https://user-images.githubusercontent.com/24326988/209535361-205bb439-147f-4ccf-844c-5e0d989a489b.png)
> 
> Associate this system user in Asset Permissions. ![image](https://user-images.githubusercontent.com/24326988/209535658-404b13b1-8948-4df3-b17a-d27dedaa4809.png)

Thank you for your help !

I have another question. Can JumpServer use RDP to Windows Server with Smart Card ?

Thanks.

**Comment by wojiushixiaobai** [comment]
Smart Card not supported.

**Comment by wonhee0410** [comment]
So the normal users cannot add Asset and add System User by themselves. We need to add them by Admin role and provide permissions to the normal user ?

Are there any ways for normal user do it by themselves ? Thanks.

**Comment by wojiushixiaobai** [comment]
Normal users have access only.
Administrators need to assign assets to normal users.
