### ISSUE TITLE
jumpserver0.3.2  二次开发 兼容django1.11问题

### ISSUE THREAD

**Issue by linxianjie** [jumpserver/jumpserver#925]
[简述你的问题]
jumpserver0.3.2 把django升级到1.11 导致堵塞问题

如果一个视图函数执行时间长点，会堵塞整个jumpserver的访问

请问有什么方法解决这个问题

[请提供你使用的Jumpserver版本 0.3.2 ]

、

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
django本来就是阻塞式的，你可用用uwsgi开启多个进程处理，执行时间比较长的任务放到后台celery task中

**Comment by linxianjie** [comment]
@ibuler  我测试了最初的版本是不堵塞的，请问你们是做的uwsgi开启多个进程处理吗

**Comment by linxianjie** [comment]
@ibuler 这个是我启动jumpserver的脚本
![image](https://user-images.githubusercontent.com/35400966/35028229-e8c97b44-fb8f-11e7-9585-61c8a1bf6ed1.png)

**Comment by linxianjie** [comment]
测试错了，最初版本也是一样会堵塞
