### ISSUE TITLE
[Question] 多云环境下用户管理问题

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#9257]
**请描述您的问题.**

如果有很多部署环境，每一个环境都需要部署一套堡垒机，如何简化用户权限的申请？还有说有什么推荐的方案？是 "单点登录 + 各环境单独分配权限" 吗？

**Comment by wojiushixiaobai** [comment]
简化用户权限的申请可以直接对接到 OA 审批。

其他的看实际需求
