### ISSUE TITLE
[Question] 是否支持对接多个 LDAP Server

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#9258]
**请描述您的问题.**

公司集团会按照大区进行 LDAP 的垂直切分，没有一个集中式的 LDAP Server，此时 JumpServer 就需要对接多个 LDAP 服务地址。

不知道目前 JumpServer 是否支持该功能？

**Comment by wojiushixiaobai** [comment]
你应该配置信任域

**Comment by cobolbaby** [comment]
> 你应该配置信任域

没理解您的意思，能否简单再说一下？

**Comment by wojiushixiaobai** [comment]
搜索引擎搜索 域信任 参考其中相关文档即可。

**Comment by cobolbaby** [comment]
@wojiushixiaobai 

我请我们的域控管理员验证了一下，但得到的反馈是"无法通过域信任解决跨域认证问题"，您可否给点建议．

**Comment by cobolbaby** [comment]
> 我请我们的域控管理员验证了一下，但得到的反馈是"无法通过域信任解决跨域认证问题"

具体问题参见: https://github.com/jumpserver/jumpserver/issues/10383
