### ISSUE TITLE
缺失Dockerfile文件

### ISSUE THREAD

**Issue by heheniuniu219** [jumpserver/jumpserver#926]
[简述你的问题]
在utils下面看到了`build_docker.sh`和`run_docker.sh`文件，但是没有在上层目录找到Dockerfile文件。
##### 使用版本
Jumpserver版本0.4.0

**Comment by ibuler** [comment]
Dockerfile不再提供

**Comment by fhwo13** [comment]
那么Dockerfile在哪里获取呢？
