### ISSUE TITLE
[Feature] 帮助文档【更新说明】链接的建议

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#9262]
**请描述您的需求或者改进建议.**

帮助文档网站：https://docs.jumpserver.org/zh/master/ ，上面的更新说明，2.26.3版本及以前，都是直接链接本地页面，自2.27.0开始，就直接跳转到github的release地址了，目前有两个问题。

1、由于众所周知的原因，在国内的网络打开github非常困难，想要了解一下更新内容，需要使用各种手段。

2、以前，想要查询某个特定版本的更新日志，直接docs网站在左上角选择版本，再选择【更新说明】，即可一目了然，现在跳转到github release页面之后，还要向后翻不知道几页才能找到。

不知道将【更新说明】跳转到github release的原因是什么，但是总感觉还是之前的方式更好一些。

![jms_upd_01](https://user-images.githubusercontent.com/1665397/210289983-742e9b0f-fa67-4d1b-a830-1b038d6b614d.png)

![jms_upd_02](https://user-images.githubusercontent.com/1665397/210289992-24d20499-88fc-4fd8-8ecc-d74c64deba48.png)

**Comment by wojiushixiaobai** [comment]
重复的工作，这部分的内容暂时没法通过脚本自动化完成。
之后我们有解决方案后可以尝试优化
