### ISSUE TITLE
[Feature] 关于登录的时候，没有某台服务器的权限显示为没有资产的建议

### ISSUE THREAD

**Issue by DeyunLuo** [jumpserver/jumpserver#9263]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/32233191/210292870-8ecb9c42-823b-4ea0-a039-9faf443aa568.png">

没有资产这个提示很容易误导用户，收到过很多反馈是用户并不清楚是并没有这台资产的权限，还是堡垒机确实没有这台资产。
更多的时候用户是以为堡垒机上没有这台资产，建议优化为没有权限

**Comment by LeeEirc** [comment]
此处是通过 api 搜索用户的有权限的资产，如果搜索不到，就默认无权限。对于用户来说，无权限和无资产，是一样的结果。

**Comment by DeyunLuo** [comment]
> 此处是通过 api 搜索用户的有权限的资产，如果搜索不到，就默认无权限。对于用户来说，无权限和无资产，是一样的结果。

请求api的结果是一样，就是对用户的提示不太友好

**Comment by LeeEirc** [comment]
请求的 api 数据，koko 也无法区分，暂时不处理此问题。
