### ISSUE TITLE
[Bug] OIDC认证生成的账号，绑定企业微信会提示验证账号密码

### ISSUE THREAD

**Issue by jinqinghui** [jumpserver/jumpserver#9265]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.6

**浏览器版本**

**Bug 描述**
OIDC认证生成的账号，绑定企业微信会提示验证账号密码。但是如果用管理员账号，把新账号认证源改成OAuth2。绑定企业微信则不会提示需要验证密码。

**Bug 重现步骤(有截图更好)**
1.  OIDC认证。
2. 绑定企业微信。
3. 提示验证密码
![image](https://user-images.githubusercontent.com/29370163/210294377-aff82909-7f1c-460f-bfe9-ccefca1e8c3b.png)
![image](https://user-images.githubusercontent.com/29370163/210294403-2d44f3ff-5e38-497e-8cce-21f75b65bd68.png)

**Comment by jinqinghui** [comment]
应该是直接让绑定企业微信，不用验证密码。OIDC生成的账号也没密码。

**Comment by O-Jiangweidong** [comment]
这个和用户的来源没有关系，这个是安全措施，只要是登录超过5分钟的用户，绑定企业微信均需要验证密码，如果需要绑定微信，请重新登录在5分钟内绑定即可
