### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ttweip** [jumpserver/jumpserver#9271]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.5   v2.28.6

**浏览器版本**
Microsoft Edge
版本 108.0.1462.54 (正式版本) (64 位)

**Bug 描述**
使用JumpServer连接交换机设备后，CLI中无法对输入的字符进行删除，交换机为H3C，固件版本V5.20

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
luna 页面设置里有配置 ^H ^?
各厂商不一致，无法统一

**Comment by jym503558564** [comment]
Luna页面就是Web 终端

**Comment by BaiJiangJie** [comment]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/32935519/232741790-bc1f1184-4c5a-4f51-bf92-58efaff5eb5e.png">
