### ISSUE TITLE
[Bug] 命令过滤设置正则匹配终端提示不正确

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#9272]
**JumpServer 版本**

v2.27.0

**Bug 描述**
正则过滤设置规则为下面的内容，在终端执行的时候依旧可以执行
```
^((service)\s\w+\s)((?!start|status).*)
```
或
```
^((service).*((?=stop|restart).*)$|(systemctl.*)((?=stop|restart).*)$)
```
以上正则是可以正常输出内容

![image](https://user-images.githubusercontent.com/7349963/210478087-ae92a5c1-da87-4eb5-8486-cc90df8d086b.png)
![image](https://user-images.githubusercontent.com/7349963/210478179-cf15d867-a579-4deb-b07c-1889761d06c4.png)

**Comment by LeeEirc** [comment]
命令规则，最好去掉 ^ 和 $ 开头结尾的正则，因为后台会把多个命令和正则进行合并计算。
如果发现没有匹配成功，可以先查看下会话的命令记录，是否正确解析，再对比下相应的正则表达式。

**Comment by seaurching** [comment]
> 

历史命令里面有service sshd restart、service sshd stop、systemctl restart sshd这样的命令，就是无法匹配

**Comment by seaurching** [comment]
> 命令规则，最好去掉 ^ 和 $ 开头结尾的正则，因为后台会把多个命令和正则进行合并计算。 如果发现没有匹配成功，可以先查看下会话的命令记录，是否正确解析，再对比下相应的正则表达式。

我修改了匹配规则也不生效，新的匹配规则是
`
(service).*((?=stop|restart).*)|(systemctl.*)((?=stop|restart).*)
`

**Comment by wojiushixiaobai** [comment]
直接 `service .*` 不就行了吗？

**Comment by seaurching** [comment]
> 直接 `service .*` 不就行了吗？

这个貌似范围太大了。连status和start都用不了。后端匹配的时候用的re.match吗？

**Comment by seaurching** [comment]
> 命令规则，最好去掉 ^ 和 $ 开头结尾的正则，因为后台会把多个命令和正则进行合并计算。 如果发现没有匹配成功，可以先查看下会话的命令记录，是否正确解析，再对比下相应的正则表达式。

我看了后台的源码，在忽略大小写的时候后台用的函数compile_regex，它可以返回pattern.
我看了koko的相关源码，forbiddenCommand这个函数里面传入的cmd不知道匹配出来什么

**Comment by seaurching** [comment]
@wojiushixiaobai @LeeEirc 我查了一些资料，koko用go编写，在regexp里面不支持正负预查，可以看一下regexp2这个库，里面支持```(?>re)```、```(?=re)```、```(?!re)```、```(?<=re)```、```(?<!re)```这些复杂的正则，要是不改koko源码，请在jumpserver的web页面上注明不支持`正负预查等复杂正则`

**Comment by wojiushixiaobai** [comment]
> > 直接 `service .*` 不就行了吗？
> 
> 这个貌似范围太大了。连status和start都用不了。后端匹配的时候用的re.match吗？

`service stop .*`
`service restart .*`
`systemctl stop .*`
`systemctl restart .*`
拆分成四条，修改代码这块我们再看看

**Comment by seaurching** [comment]
> 

写成4条正则是可以实现的，可所谓的正则就是一条规则匹配字符串，拆成4个不太合理……我debug了代码在web端执行批量命令可以正常匹配到，禁止运行相关的服务，正负向预查可以使用。在koko这里无法进行正负预查
![image](https://user-images.githubusercontent.com/7349963/210711487-eeb587bb-defa-47c8-b632-384ac02d6f12.png)

**Comment by LeeEirc** [comment]
测试了下 go 的 `regexp` 内置正则模块，执行 `regexp.Compile(`((service)\s\w+\s)((?!start|status).*)`) 会出现报错：
```
invalid or unsupported Perl syntax: `(?!
```
各个编程语言的正则模块确实会有差异，后续会优化考虑使用 regexp2 第三方模块，感谢指正 koko 的正则相关的问题。

**Comment by wojiushixiaobai** [comment]
优先解决问题，一条和四条没区别，不是四十条，可以接受的范围

**Comment by seaurching** [comment]
> 优先解决问题，一条和四条没区别，不是四十条，可以接受的范围

另外再正则里面包含`$`结尾的正则也不支持

**Comment by seaurching** [comment]
> 优先解决问题，一条和四条没区别，不是四十条，可以接受的范围
这里的正则匹配如果在终端执行命令，不会被拦截，koko里面没有添加replace('\r\n','\n')这样的parse导致命令不能正常拦截，只能写成一行
![image](https://user-images.githubusercontent.com/7349963/211497688-4ebdf8b2-ece5-425e-80f7-e8dd8faac2f2.png)

**Comment by BaiJiangJie** [comment]
后续 koko 优化一下正则匹配机制，尽量支持一些复杂的正则。

**Comment by LeeEirc** [comment]
评估了下 regexp2 库，并不能无缝替换标准库的 regexp，暂不做改动变更了。使用多条正则解决吧
