### ISSUE TITLE
[Question] SAML配置提示疑似错误

### ISSUE THREAD

**Issue by VinoXuanyu** [jumpserver/jumpserver#9273]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/68767004/210483019-334f18ee-bd5e-478d-90d1-84c303aa46cf.png">

这里提示key是jumpserver属性，value是idp属性，是否弄反了？

**Comment by VinoXuanyu** [comment]
这里感觉username才是jumpserver的属性呀

**Comment by jym503558564** [comment]
什么版本

**Comment by VinoXuanyu** [comment]
> 什么版本

应该是最新版吧？

**Comment by jym503558564** [comment]
好的，我们修复一下。
