### ISSUE TITLE
[Bug] Oracle数据库相关问题

### ISSUE THREAD

**Issue by seaurching** [jumpserver/jumpserver#9280]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.27.0

**Bug 描述**
第一个bug：
下面图中的这个红框地方应该改成tsn信息之类的，并添加两个选项是服务名称还是SID
![image](https://user-images.githubusercontent.com/7349963/210753498-952d4f74-77e2-4f59-abf7-12317f34ef51.png)

第二个bug：
navicate直连代理提示用户名密码错误

**Bug 重现步骤(有截图更好)**
1.  页面上添加数据库信息
![image](https://user-images.githubusercontent.com/7349963/210754243-5fb09baa-be81-4643-b4fc-0c71bc5f75e4.png)

2. 用web客户端测试连接
 
![image](https://user-images.githubusercontent.com/7349963/210754339-01c9a280-14fe-4c43-b0a4-5022a6a8c6b0.png)

3.用dbclient测试连接（更改sid、服务名都连接失败，数据库版本是11.2.0）
![image](https://user-images.githubusercontent.com/7349963/210754522-282424b6-17ed-4e35-9c46-b3af3a95abd9.png)
![image](https://user-images.githubusercontent.com/7349963/210754699-b7e574e6-f8af-43cc-8881-e8b4ea5cc204.png)
![image](https://user-images.githubusercontent.com/7349963/210754794-9e24f166-a3f2-4afe-a442-f373cb0cb25a.png)

4.用正常的连接方式测试（sid改成sypayrac1，服务名改成sypayrac均可正常连接）
![image](https://user-images.githubusercontent.com/7349963/210755388-fd63b264-5199-4669-96d8-2ad830ecfb06.png)
![image](https://user-images.githubusercontent.com/7349963/210755571-7d5ce26d-78a5-426b-89af-73d8912fc776.png)

**Comment by wojiushixiaobai** [comment]
SID
无法连接的 oracle 版本是多少

**Comment by seaurching** [comment]
> SID 无法连接的 oracle 版本是多少
```
SQL> select * from v$version;
--------------------------------------------------------------------------------
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL/SQL Release 11.2.0.4.0 - Production
CORE	11.2.0.4.0	Production
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production
```

**Comment by Aaron3S** [comment]
由于 Oracle 通信协议是私有协议， 我们在代理 Oracle 协议过程中遇到了一些难题，这些问题导致了没法完全适配所有的数据库连接，这里我们仍然在继续探索中。

**Comment by seaurching** [comment]
> 

####  好的，了解了。

**Comment by BaiJiangJie** [comment]
多关注一下在后续的 Release Note 更新，Oracle 的问题会随着版本进行不断优化。
目前也解决了一些相关 Oracle 12c 的问题，可以使用最新版本验证一下。

**Comment by seaurching** [comment]
@BaiJiangJie 我设置了oracle登录账号是sys，也设置这个账号是特权账号，登录数据库的时候提示“以sysdba身份登录”，这里可否优化一下？
<img width="412" alt="以sysdba身份登录" src="https://github.com/jumpserver/jumpserver/assets/7349963/67186882-4b99-4f50-b2ab-82bae2bc6738">
<img width="535" alt="sys_account_info" src="https://github.com/jumpserver/jumpserver/assets/7349963/d0fa7b1f-7399-4460-9dfc-b5dfa81782e4">
