### ISSUE TITLE
SMTP设置发件人地址问题

### ISSUE THREAD

**Issue by hchery** [jumpserver/jumpserver#9283]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.6

**浏览器版本**
Chrome 108.0.5359.124

**Bug 描述**
SMTP设置发件人地址无法使用 xx&lt;xx@xx.com&gt; 格式地址

**Comment by wojiushixiaobai** [comment]
仅支持 `user@domain.com`

**Comment by hchery** [comment]
那应该如何设置发件人昵称呢？

**Comment by BaiJiangJie** [comment]
昵称应该在 SMTP 服务器上设置吧
