### ISSUE TITLE
[Bug] 录像文件分辨率问题

### ISSUE THREAD

**Issue by zhenzhendong** [jumpserver/jumpserver#9284]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.  通过rdp方式链接乌班图22.04资产
2. 查看录像文件显示分辨率异常，显示不全

![image](https://user-images.githubusercontent.com/122069934/210921986-b3385f1d-fd1c-423e-85b0-b3c8cdc0ea41.png)

**Comment by wojiushixiaobai** [comment]
远端分辨率太大？无法自适应吗

**Comment by zhenzhendong** [comment]
web终端链接是正常的，就是查看审计的录像文件会出现异常

**Comment by zhenzhendong** [comment]
2.28，最新的版本

**Comment by BaiJiangJie** [comment]
是的，目前是存在这样的问题。只有对图形化方式（rdp、vnc）连接 Ubuntu 资产时会出现。

技术上有点难度，等合适的时候会处理一下。

**Comment by LeeEirc** [comment]
@BaiJiangJie  待技术深入研究下。

**Comment by BaiJiangJie** [comment]
目前遇到的用户较少，短期暂不支持。
