### ISSUE TITLE
[Bug] Ceph存储无法配置成功

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#9288]
**JumpServer 版本(v1.5.9以下不再支持)**
2.28.6

**浏览器版本**
Edge

**Bug 描述**
对象存储后端为Seaweedfs（s3），配置录像存储为Ceph。点击测试的时候，提示账号无效。但是账号密码肯定没有问题。
如果用jumpserver 2.5.3版本，用相同的配置，点击测试，是提示测试成功的。

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/22488813/211128092-4f2ff52a-aecf-467c-8372-9cf98f5b1db0.png)
2. 
![bf0d8b5d55304a8743efb1d34afc7fb](https://user-images.githubusercontent.com/22488813/211128105-f8adcf13-bb0a-465d-9c15-0c2c5395c8f2.png)
3. 2.5.3版本提示测试成功：
![image](https://user-images.githubusercontent.com/22488813/211128122-409eec6f-18d3-491b-8679-986ab75f66a3.png)

**Comment by rty813** [comment]
![image](https://user-images.githubusercontent.com/22488813/211128195-bf0df969-ed98-431d-bf91-a82a1b988661.png)
从这里可以看出，利用minio的mc命令，是可以成功连接到对象存储端点的。

**Comment by wojiushixiaobai** [comment]
不确定是不是证书的问题，你看看 core 组件的日志有没有错误提示。

**Comment by rty813** [comment]
从点击测试，到提示失败，core下的jumpserver.log没有任何日志

**Comment by wojiushixiaobai** [comment]
用 http 测试下看看，要验证的话从 core 容器里面进行测试

**Comment by rty813** [comment]
测试了一下，应该是dns、以及hosts设置的问题。我设置的端点用的是域名，但是这个域名指向的正好也是jms所在的服务器。导致在jms_core里面，解析域名的时候，得到的是127.0.0.1。我手动修改/etc/hosts后，让域名指向该服务器在局域网中的IP地址，就可以了。

由此又带来一个问题，我如何配置jms_core，使其能够在容器创建后，不需要我手动上去修改hosts，能自动配置好呢？

**Comment by wojiushixiaobai** [comment]
域名解析问题这个只能自行处理了。
