### ISSUE TITLE
[Question] 文件管理 中连接服务器出现："无法上传 connection lost"

### ISSUE THREAD

**Issue by wenbc** [jumpserver/jumpserver#9290]
版本：V2.28.1 
连接部分服务器出现 "无法上传 connection lost"。

![image](https://user-images.githubusercontent.com/8147297/211237293-7a233fd0-4129-4adc-8ace-33bf22d41216.png)

**Comment by wojiushixiaobai** [comment]
需要更详细信息，如：
- 部署方式
- 是否经过反向或正向代理
- 是否排除网络问题
- 更详细的组件错误日志

**Comment by wenbc** [comment]
> 需要更详细信息，如：
> 
> * 部署方式
> * 是否经过反向或正向代理
> * 是否排除网络问题
> * 更详细的组件错误日志

docker的部署方式：
![image](https://user-images.githubusercontent.com/8147297/211238209-8c08403e-b64c-4295-a7b7-24b3ae508ab4.png)

前面有一个反向代理：nginx(80 443 2222) --> jms_web(80 2222)，排查过直接访问后端jms_web这个也还是会有这个报错。

网络检查过，没有问题。

koko 的日志错误信息：
![image](https://user-images.githubusercontent.com/8147297/211238993-422da1b2-75e2-40c7-8b40-410dbf79d9e9.png)

**Comment by wojiushixiaobai** [comment]
那 ssh 连接应该也能复现此问题，在 web 终端页面连接资产后，在左侧的资产名称右键选择文件管理看看。
必须是连接成功资产后进行文件管理操作，然后看看。

1. 确定 ssh 连接是否有此问题
2. 确定 ssh 连接成功后文件管理是否有此问题

**Comment by wenbc** [comment]
已解决，是用户key的问题，重新推送用户就可以了。
