### ISSUE TITLE
centos7 V0.5.0安装luna失败

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#930]
[简述你的问题]

##### 使用版本
v0.5.0

##### 问题复现步骤
1. [步骤1]
按照教程在centos7上安装v0.5.0https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%9F%BA%E4%BA%8E-CentOS7   但是在第四步安装luna的时候出现了问题 
报错如下:

cd /opt
$ git clone https://github.com/jumpserver/luna.git
$ cd luna && npm install && npm run-script build
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![error4](https://user-images.githubusercontent.com/17851645/35031308-504e3842-fb9d-11e7-8888-121194c4ebb2.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
请使用release，如果你不是开发的话, https://github.com/jumpserver/luna/releases
