### ISSUE TITLE
[Question] 系统用户托管密码自动生成问题

### ISSUE THREAD

**Issue by hayderx** [jumpserver/jumpserver#9300]
在创建系统用户时选择托管密码和自动生成，请问下如果服务器上配置了登录密码有效期，再过期后会自动重新生成密码吗？

**Comment by wojiushixiaobai** [comment]
开源版本可能需要管理员定时的手动推送密码，企业版本有密码管理套件自动化处理密码问题。

**Comment by hayderx** [comment]
请问如果该用户自动生成的密码在服务器端已经过期了，手动推送密码提示{"changed": false, "msg": "Failed to connect to the host via ssh: vdollar_percent_expand: unknown key %m\r\npercent_expand failed", "unreachable": true}，需要怎么处理呢？是要把这个用户删除掉重建，然后再推送这个用户自动生成的密码吗？谢谢。

**Comment by wojiushixiaobai** [comment]
开源版本可以通过修改系统用户的密码然后重新推送即可，可以通过 api 定时触发
