### ISSUE TITLE
SFTP传输大文件卡住

### ISSUE THREAD

**Issue by 13368932502** [jumpserver/jumpserver#9306]
**SFTP传输大文件卡住**
SFTP传输大文件卡住，也没有显示错误信息，请问如何排查具体是啥原因照成的
![微信截图_20230112111811](https://user-images.githubusercontent.com/62083375/211968225-aaefacf5-b030-4160-b610-23f8d34c46ef.png)

**Comment by wojiushixiaobai** [comment]
检查下是不是 JumpServer 服务器的存储是不是满了
如果不是的话需要更具体的环境信息，比如是不是前端有 slb 之类的，请先排除网络问题。

**Comment by 13368932502** [comment]
已解决，是内部网络网络问题导致的

**Comment by jym503558564** [comment]
问题解决了，我们就关闭Issues。如有其他问题，可再次给我们提Isues.
