### ISSUE TITLE
AttributeError at /assets/system-user/create/

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#931]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2.]

##### 问题复现步骤
第一次创建的系统用户 可以正常使用，但是我删除以后，重新创建就直接报错了

AttributeError at /assets/system-user/create/
module 'cryptography.hazmat.primitives.serialization' has no attribute 'BestEncryption'
Request Method:	POST
Request URL:	http://xx.x.xx.xx:8080/assets/system-user/create/
Django Version:	1.11
Exception Type:	AttributeError
Exception Value:	
module 'cryptography.hazmat.primitives.serialization' has no attribute 'BestEncryption'
Exception Location:	/opt/py3/lib/python3.6/site-packages/paramiko/pkey.py in _write_private_key, line 344
Python Executable:	/opt/py3/bin/python3
Python Version:	3.6.4
Python Path:	
['/opt/jumpserver/apps',
 '/opt/py3/bin',
 '/usr/local/python3.6/lib/python36.zip',
 '/usr/local/python3.6/lib/python3.6',
 '/usr/local/python3.6/lib/python3.6/lib-dynload',
 '/opt/py3/lib/python3.6/site-packages',
 '/opt/jumpserver',
 '/opt/jumpserver/apps']

**Comment by qianghong000** [comment]
我把已经推送过去的系统用户 手动删除 就好了~~

**Comment by Hello-Linux** [comment]
你的v0.5怎么安装成功的为什么我的安装luna就报错了
![error4](https://user-images.githubusercontent.com/17851645/35031363-8a0678ce-fb9d-11e7-93a1-ad3a6e5eac00.png)

**Comment by qianghong000** [comment]
我不知道怎么装安装luna  我只装了coco

**Comment by qianghong000** [comment]
你知道怎么装吗？有文档吗

**Comment by Nidhoggur1993** [comment]
luna的安装可以参考wiki最下面的[部分](https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%9F%BA%E4%BA%8E-CentOS7#%E5%9B%9B-%E5%AE%89%E8%A3%85-web-terminal-%E5%89%8D%E7%AB%AF-luna)，但是新版本的luna只能用来回放不能作为web console了

**Comment by Hello-Linux** [comment]
我现在安装进来了，但是为什么我添加用户后收不到邮件呢？

**Comment by Hello-Linux** [comment]
@qianghong000  为什么提示我这个key无效呢？ 还有就是你能把你的操作流程文档发一下么 v0.5的
![default](https://user-images.githubusercontent.com/17851645/35033585-336fb9d6-fba6-11e7-836b-c752efe22650.png)

**Comment by liuzheng** [comment]
@Nidhoggur1993 当然可以拥有webterminal的功能啊，你直接进 jumpserver.xx.com/luna看就行了

**Comment by ibuler** [comment]
paramiko版本问题？
