### ISSUE TITLE
[Feature] api接口返回内容优化

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9311]
**请描述您的需求或者改进建议.**
api 接口返回内容过于粗暴
比如创建资产,返回内容
{
    "hostname": [
        "字段必须唯一"
    ]
}
这种情况应该认为是一种错误,
希望的返回结果应该是
{
    "message": "hostname:字段必须唯一",
    "code": 1,
    "result": false,
}
或者
{
    "message": "请求失败",
    "code": 0,
    "data": {
    "hostname": [
        "字段必须唯一"
    ]
    }
    "result": false,
}
能够通过一些公共的字段判断此次请求是否出了异常,而不是需要我整个解析返回内容
望能统一 api 返回内容格式

**Comment by BaiJiangJie** [comment]
可以通过响应码进行判断，会更加准确。

<img width="406" alt="image" src="https://user-images.githubusercontent.com/32935519/229768691-fcb583ca-8565-4477-8857-9b5e274f05dc.png">
