### ISSUE TITLE
[Question] ssh自动推送问题

### ISSUE THREAD

**Issue by rty813** [jumpserver/jumpserver#9318]
**请描述您的问题.**
自动推送的用户，是否可以指定group、home路径？

**Comment by wojiushixiaobai** [comment]
系统用户新建时可以指定

**Comment by rty813** [comment]
![image](https://user-images.githubusercontent.com/22488813/212833617-d77f5e59-ba86-4c30-9711-b7cea3de073b.png)
![image](https://user-images.githubusercontent.com/22488813/212833622-2a285944-7a6c-4da6-ae72-ed8376e5a243.png)

没有看到在哪里指定groups和home path

**Comment by wojiushixiaobai** [comment]
更新到新版本
![image](https://user-images.githubusercontent.com/24326988/213075184-8d7c0dab-b5ca-4c64-b05a-da677a8fdfe4.png)

**Comment by rty813** [comment]
thanks
