### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bigbang009** [jumpserver/jumpserver#9331]
**JumpServer 版本(v1.5.9以下不再支持)**
V2.4.2

**浏览器版本**
chrom 109.0.5414.74（正式版本） （64 位）

**Bug 描述**
web页面连接主机一段时间就会出现自动断开，提示Connection websocket closed，这个还没有到连接最大空闲时间（设置的是120分钟）
![image](https://user-images.githubusercontent.com/36918717/212913370-0600307e-183e-4a7f-b2f0-c07439e9b904.png)

![image](https://user-images.githubusercontent.com/36918717/212914116-3a2567ed-e03d-4dea-a7f3-eb01654ed72d.png)

不知道是不是哪里有BUG导致的，从抓包来看是前端给koko发送的FIN包

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by bigbang009** [comment]
koko日志
![image](https://user-images.githubusercontent.com/36918717/212915511-0d879bd9-3bae-4f25-bf96-0aac70795443.png)

**Comment by LeeEirc** [comment]
有点像是 websocket 没有配置正确，连接断开了。

**Comment by bigbang009** [comment]
> 有点像是 websocket 没有配置正确，连接断开了。

websocket需要怎么配置呢？有配置文件吗？

**Comment by LeeEirc** [comment]
怎么部署的？如果在 jumpserver 前面还存在负载相关，需要全部放开支持对 websocket 的限制。nginx 的配置可以参考官网文档。

**Comment by LeeEirc** [comment]
看这个 [参考文档](https://docs.jumpserver.org/zh/master/dev/build/#jumpserver)，koko 可参考如下配置：
```
 location /koko/ {
    # 注意将模板中的组件名称替换为服务实际 ip 地址， 如都在本机部署
    # proxy_pass       http://127.0.0.1:5000;
    proxy_pass       http://koko:5000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

**Comment by bigbang009** [comment]
> 看这个 [参考文档](https://docs.jumpserver.org/zh/master/dev/build/#jumpserver)，koko 可参考如下配置：
> 
> ```
>  location /koko/ {
>     # 注意将模板中的组件名称替换为服务实际 ip 地址， 如都在本机部署
>     # proxy_pass       http://127.0.0.1:5000;
>     proxy_pass       http://koko:5000;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_http_version 1.1;
>     proxy_buffering off;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>   }
> ```

就是参考官网配置的，但websocket不定时的会断开连接

**Comment by LeeEirc** [comment]
怎么部署的？有没有防火墙？浏览器到 JMS 服务之间需要经过哪些负载软件，能不能保持长连接？

**Comment by bigbang009** [comment]
> 怎么部署的？有没有防火墙？浏览器到 JMS 服务之间需要经过哪些负载软件，能不能保持长连接？

这边抓包分析发现，koko前端里发送websocket心跳包（ping）出现发了一段时间之后不发送了，这个可能是KOKO的bug吗？

**Comment by LeeEirc** [comment]
升级到最新版本测试下看看？

**Comment by bigbang009** [comment]
> 升级到最新版本测试下看看？

没有升级新版本，主要和前端js里的setInterval这个定时器有关系，这个倒数定时不准，所以才出现一段时间（超过断连的最大值）没有发送ping包

**Comment by LeeEirc** [comment]
v2.4 的版本已经不维护了，建议升级到v2.28 验证。尚未复现此问题。
