### ISSUE TITLE
Coco无法解析expect发来的\r回车符

### ISSUE THREAD

**Issue by topicgit** [jumpserver/jumpserver#934]
[简述你的问题]
 想要实现自动连接跳板机，跳到匹配的机器上，使用expect脚本发送回车符，coco无法识别
##### 使用版本
[ 0.5.0]

##### 问题复现步骤
1. 如下是自动连接跳板机的代码

#!/usr/bin/expect
set timeout 3
spawn ssh xxx@192.168.1.100
expect "*Opt*"
send "salt\r"
interact

2. 
执行以上的脚本,执行完成后会卡住，直到输入回车则进入匹配的服务器

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/11975460/35033131-707ba44a-fba4-11e7-8f51-6726006c0f10.png)

##### 其他

[注:] 完成后请关闭 issue

@ibuler

**Comment by liuzheng** [comment]
没这样玩过，你"\r\n"看看呢

**Comment by topicgit** [comment]
@liuzheng  
试过了依然不可以，就是卡在那里，回车一下就可以登陆；做这个的目的就是直接连接上目标主机。

**Comment by liuzheng** [comment]
直接连推荐ssh forward，应该支持，这个python版本我没测过，表示做了一半golang版本的，可以支持ssh forward

**Comment by kayaklee** [comment]
这应该是个jumpserver的bug，要sleep一下

send “salt”
sleep 0.1
send "\r"

这样就可以了
