### ISSUE TITLE
SAML2 登陆成功跳转到callback页面之后自动logout导致页面循环在login和idP之间

### ISSUE THREAD

**Issue by bofortitude** [jumpserver/jumpserver#9344]
我这边集成了公司自己的SAML2的idP服务器。从抓包结果看，登陆成功后idP服务器会正确回应了callback的链接。之后自动跳转到了首页，再之后等加载完css和js之后，就自动访问了logout导致跳出。此后一直循环。我尝试在用户管理的地方添加了用户，并且指定源为SAML，但反复试验后结果一致。请问这个可能是什么原因导致的？

**Comment by wojiushixiaobai** [comment]
同步注销 关闭后，对比下服务器的时间。

**Comment by bofortitude** [comment]
> 同步注销 关闭后，对比下服务器的时间。

你好，非常感谢你的回复。但是我检查过系统时间，是一致的，还是依然出现这个状况。不知道还有什么别的可排查的点没有。

**Comment by bofortitude** [comment]
> 同步注销 关闭后，对比下服务器的时间。

你好，感谢你的回复。因为我的服务器在国外，所以时区和默认的docker image的时区不一致，我尝试改过了。也查看了运行时的timezone，应该是改成本地了。但是问题依旧，请问是不是还有其他的地方需要重新设置时区？比如MySQL？

**Comment by bofortitude** [comment]
我尝试了把那几个docker-compose的文件都加上了映射系统timezone然后重新安装，但是结果还是自动跳出。请问是不是有个统一的位置能设置时区？

**Comment by wojiushixiaobai** [comment]
跨区的话，可以尝试用自编译的组件在本地运行看看。
https://docs.jumpserver.org/zh/master/dev/build/
