### ISSUE TITLE
为什么管理用户密码为空，都可以推送用户

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#935]
[简述你的问题]

##### 使用版本
[0.5.0-2 GPLv2]

我安装完jumpserver以后，管理用户没有填写密码，居然都可以推送用户，是怎么做到的？

**Comment by yamin-zou** [comment]
你设置key了？

**Comment by qianghong000** [comment]
没有啊，很神奇！没设置密码 也没设置key  居然可以连接过去。

**Comment by qianghong000** [comment]
难道说管理密码设置过一次 key加载过一次。但是后面删除了，还存在数据库里？

**Comment by ibuler** [comment]
设置过一次密码或秘钥会存储到数据库中
