### ISSUE TITLE
0.5.0 安装 Web Terminal 前端: Luna 无法访问

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#936]
[简述你的问题]

##### 使用版本
v0.5.0 我按照centos V0.5.0的安装教程安装完jumpserver后添加了用户,资产,系统用户,管理用户 COCO终端我可以登录进去并且可以操作终端但是新版本的luna怎么进去呢 我怎么在web UI接界面没有看到呢？
我用的是你们提供的luna版本https://github.com/jumpserver/jumpserver/wiki/v0.5.0-Nginx-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

##### 问题复现步骤
安装完成后找不到教程里面的那个luna终端界面

##### 具体表现[截图可能会更好些,最好能截全]

![error7](https://user-images.githubusercontent.com/17851645/35042884-4542ce7c-fbc5-11e7-8822-78c3aecf87f3.png)
![error8](https://user-images.githubusercontent.com/17851645/35043228-c7b19464-fbc6-11e7-99fb-808687490e2c.png)

没有luna
![default](https://user-images.githubusercontent.com/17851645/35043502-d8d4d64c-fbc7-11e7-839f-f84962fe5500.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
地址是你的jms的地址后面加上/luna/， 入口可能没做

**Comment by Hello-Linux** [comment]
@liuzheng  我是按照官方教程走的,luna的nginx配置文件也配置了你说的入口是什么意思？

**Comment by liuzheng** [comment]
就是没有按钮可以跳到Luna页面,链接参考http://demo.jumpserver.org/luna/

**Comment by Hello-Linux** [comment]
@liuzheng  没有按钮？我的nginx配置已经添加了跳转到luna目录的地址了为什么会访问不到呢？

**Comment by Hello-Linux** [comment]
@liuzheng  官方的连接是可以访问的我现在不知道为什么我的访问不了？我的配置都是copy官方的

**Comment by Hello-Linux** [comment]
@liuzheng  你的node版本是多少

**Comment by Hello-Linux** [comment]
@liuzheng  这个是我现在的配置文件
server {
    listen 80;
    server_name jumpserver.docker.com;

    location /luna/ {
        root /opt/luna/dist;
    }

    location /media/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
    }

    location /static/ {
        root /opt/jumpserver/data/;
    }

    location /socket.io/ {
        proxy_pass       http://localhost:5000/socket.io/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass http://localhost:8080;
    }
}

**Comment by Hello-Linux** [comment]
@liuzheng  我现在不明白的是你所说的跳转按钮是指什么

**Comment by Hello-Linux** [comment]
@liuzheng  还有就是我感觉你们的配置文件表达的不清晰 luna的这个目录在你们的项目里面是不存在的/path/luna/dist 这个disk不存在  第二个问题:配置文件是用这个---》 location /luna/ {
    try_files $uri / /index.html;
    alias /path/of/your/luna/;
  }    还是这个-----》https://github.com/jumpserver/jumpserver/wiki/v0.5.0-Nginx-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6  还是----》location /luna/ {
    root /opt/luna/dist;
}

**Comment by hittang** [comment]
请参考这个
https://github.com/jumpserver/jumpserver/wiki/v0.5.0-Nginx-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
注意目录






在 2018-01-18 00:16:37，"Hello-Linux" <notifications@github.com> 写道：


@liuzheng 还有就是我感觉你们的配置文件表达的不清晰 luna的这个目录在你们的项目里面是不存在的/path/luna/dist 这个disk不存在 第二个问题:配置文件是用这个---》 location /luna/ {
try_files $uri / /index.html;
alias /path/of/your/luna/;
} 还是这个-----》https://github.com/jumpserver/jumpserver/wiki/v0.5.0-Nginx-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 还是----》location /luna/ {
root /opt/luna/dist;
}

**Comment by Hello-Linux** [comment]
@liuzheng  我按照你给我的参考重新配置了一下但是还是不行直接报403
截图如下:
![error1](https://user-images.githubusercontent.com/17851645/35075380-b915948e-fc2d-11e7-84f9-d0ded232a050.png)
![error2](https://user-images.githubusercontent.com/17851645/35075385-bf00a5a0-fc2d-11e7-8ec7-e64e16888481.png)
![error3](https://user-images.githubusercontent.com/17851645/35075390-c51002d8-fc2d-11e7-8326-b59e43f69dbf.png)
这个403错误是指我的luna路径下没有index.html文件但是实际上我的dist目录是存在index文件的
![Uploading 图片.png…]

**Comment by wojiushixiaobai** [comment]
@hittang disk目录是 ng build 出来的。

我现在可以通过 ng serve 来访问 luna ，但是怎么与 jumpserver 通信还没搞懂。

**Comment by liuzheng** [comment]
@wojiushixiaobai 你现在搞明白了么？https://github.com/jumpserver/jumpserver/issues/937#issuecomment-358526590
