### ISSUE TITLE
web终端，上传文件，耗时很慢。 发现传输的时候，等待服务器响应耗时较长。 这个是什么导致的。

### ISSUE THREAD

**Issue by mogecheche** [jumpserver/jumpserver#9363]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/32326629/215422633-32684760-e21c-45b5-ac1e-f0f7655759b6.png)
![image](https://user-images.githubusercontent.com/32326629/215422712-238e8d96-5e55-4498-8da0-663c446c445b.png)
![image](https://user-images.githubusercontent.com/32326629/215422764-dbc63b4f-cd31-482a-804f-6923f8474042.png)

**Comment by LeeEirc** [comment]
如果文件很大的情况下，是分片上传，每一次都是通过 SFTP 直接 proxy 到 资产上。可以检查下 jms 到 资产的贷款传输是否足够快。

**Comment by mogecheche** [comment]
（前期已排除网络带宽，目前通过sdwan打通，带宽充足）传输文件不是很大，大概200M左右。实验测试，直接通过sftp 传输到 目标资产， 传输速度、带宽均在理想范围内；

通过堡垒机 传输，则等待时间很长。 主要是分片传输时， 等待服务器响应 时间过长， 每个分片需要等待10s。这个 【等待服务器响应】有没有优化空间，是否受链路延迟影响？

我司全国有好几个研发中心，总部到分公司延迟 35ms 左右，不知这个有没有影响，是否有优化空间。

**Comment by LeeEirc** [comment]
web 端肯定受链路影响的。你可以针对你的环境，从传输的链路对比下耗时。这肯定是一个综合的结果。

**Comment by mogecheche** [comment]
公网链路延迟固定，这个也不是公司网络运维可以调整的。 不通过堡垒机sftp可以理想传输，问题应该还是在堡垒机服务器上。同时目前从使用上来讲，除文件传输这个问题外，其它功能都是正常的， 不存在卡顿、延迟等问题

**Comment by LeeEirc** [comment]
通过堡垒机走 sftp 肯定要比直接连接要慢的，理论上是要降一半速度的。 或者你通过 sftp 工具连接 koko 的 2222 试试，看下是不是速度快一些？

**Comment by mogecheche** [comment]
通过xshell 和 Mobaxterm ，直接sftp 连接堡垒机2222  ，传输速率大概1MB/s ， 
![企业微信截图_16756706968223](https://user-images.githubusercontent.com/32326629/216919291-a27f8a47-8ea0-49a5-967d-96489b4c9d0c.png)
![企业微信截图_1675671004343](https://user-images.githubusercontent.com/32326629/216919301-e5079e6d-7abf-45ea-ba0c-7327a3f9959c.png)

**Comment by mogecheche** [comment]
这个时从南京本地， 直接通过stfp 传输文件至 堡垒机上(堡垒机在总部)，  传输速度10MB/s。 传输速率达到预期；同样，从堡垒机，sftp 传输文件至目标机器，也达到预期。 不认为是链路延迟导致的问题。

![企业微信截图_16756715601372](https://user-images.githubusercontent.com/32326629/216920391-1bceba42-bf98-40d7-9225-8c471716ac31.png)
![企业微信截图_16756715802804](https://user-images.githubusercontent.com/32326629/216920416-50acfb6c-64ef-4465-804b-497e16c07c9f.png)

**Comment by LeeEirc** [comment]
嗯，这个待调研看看。

**Comment by PlaneV** [comment]
有可能是这个问题，我们一起关注一下！
[https://github.com/jumpserver/jumpserver/issues/12620](https://github.com/jumpserver/jumpserver/issues/12620#issue-2107295512)
