### ISSUE TITLE
关于v0.5.0配置文件的问题

### ISSUE THREAD

**Issue by Hello-Linux** [jumpserver/jumpserver#937]
[简述你的问题]
官方的nginx配置文件存在的问题：
  location /luna/ {
    try_files $uri / /index.html;
    alias /path/of/your/luna/;
  }
问题描述: 
第一:alias 表述不清楚根目录应该是/path/of/your/luna/dist/ 而不是/path/of/your/luna/  容易造误导读者 :  

第二: try_file使用错误 ：首先try_files的意思是依次查找文件是否存在 最后一个index.html是内部的一个重定向必须保证存在假如我现在配置是location /luna/ {
       try_files $uri / /index.html;
       alias /opt/luna/dist/;
     }
由于jumpserver的作者在location匹配的path目录后面加上"/" 所以我们访问的url中也必须加上/也就是curl 127.0.0.1/luna/  而不是127.0.0.1/luna 否则会出现502错误
![me1](https://user-images.githubusercontent.com/17851645/35078617-0534cfbe-fc3e-11e7-802e-c601cc58e979.png) 这个是由于alias 关键字功能导致的 希望作者后面去掉location /luna/ 中的'/"改成location /luna即可

下面继续第二个问题try_files的使用问题,作者写的也是有问题的/opt/luna/dist中有一个入口文件也就是默认首页index.html try_files $uri / /index.html  此时访问会提示301 重定向次数过多
![me2](https://user-images.githubusercontent.com/17851645/35078996-f8047270-fc3f-11e7-8145-2e48e2c40825.png)

出现问题的原来在于alias跟try files的搭配错误造成路径出现歧义

最后附上修正的配置文件:
     location /luna {
        index index.html;
        alias /opt/luna/dist/;
  }

**Comment by liuzheng** [comment]
> 第一:alias 表述不清楚根目录应该是/path/of/your/luna/dist/ 而不是/path/of/your/luna/ 容易造误导读者 :

这边一定是我的路径，因为强烈要求大家去https://github.com/jumpserver/luna/releases，而不是编译，Luna这边默认两种类型的使用者，1.开发者：知道自己在做什么，知道如果编译编写代码，熟悉npm。2.使用者，仅仅使用即可，完全不懂npm是什么。

针对这两种用户，开发者知道整体架构，代码开发，以及dist这种基本问题，不需要过多说明。

使用者，连npm install都可能装不好，要求那么多干嘛，直接到release分支里下载代码解压，放到自己喜欢的路径下面，所以，针对教程中'/path/of/your/luna/'是对使用者说的话，而不是开发。

> 第二，省略

你这个问题会带来一连串的使用问题，请麻烦自己到隐身模式下测试上述修改将带来的问题。

**Comment by wojiushixiaobai** [comment]
。。原来是我的配置出了问题。。233333..完美解决

**Comment by yamin-zou** [comment]
小白求问，点击web终端，跳转 http://172.25.10.83/luna/?   
总是404 ？

**Comment by liuzheng** [comment]
请按照教程进行配置，https://github.com/jumpserver/jumpserver/wiki/v0.5.0-基于-CentOS7

**Comment by liuzheng** [comment]
@Hello-Linux 针对你强烈要求访问xxx.com/luna 可以访问到 xxx.com/luna/，请修改Luna跳转部分nginx config如下配置

```
  location /luna/ {
    try_files $uri / /index.html;
    alias /Users/liuzheng/gitproject/Jumpserver/luna/dist/;
  }

  location /luna {
# 必须在 /luna/ 之下
    rewrite ^(.*)$ $1/ break;
  }
```
