### ISSUE TITLE
luna通过点击列表不能连进去

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#938]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2.]

##### 问题复现步骤
![jump1](https://user-images.githubusercontent.com/9443696/35079172-d330544a-fc40-11e7-894f-9af04c985bdd.png)

luna装好以后，怎么jumpserver界面上没有连接按钮，打开终端后，左边的列表不能点

**Comment by liuzheng** [comment]
下载最新coco代码，然后更新环境依赖`pip install`，Luna也需要在release里下载最新的

**Comment by qianghong000** [comment]
我已经更新到dev分支最新代码了 luna下载了好几个版本都还是不行

**Comment by liuzheng** [comment]
@qianghong000 请下载Luna release版本，认真阅读部署文档
