### ISSUE TITLE
[Bug] 资产上可以连通测试通过，并且可以更新硬件配置信息，但是无法通过web终端登录

### ISSUE THREAD

**Issue by kevynull** [jumpserver/jumpserver#9381]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.17.2 GPLv2

**浏览器版本**
chrome Version 109.0.5414.87

**Bug 描述**
系统部署方式，docker-compose
新建资产和系统用户，并将系统用户推送到资产中后。
资产上可以连通测试通过，并且可以更新硬件配置信息。但是无法通过web终端登录。web终端页面显示的是之前其他的系统用户

**Bug 重现步骤(有截图更好)**

资产-系统用户界面
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/4230892/215726327-27d33fdc-c140-4ab4-ae8b-477629d1b2e1.png">

系统用户界面
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/4230892/215726191-44e98f94-e581-40b7-b2f3-a00f8f593a84.png">

连通性测试页面
<img width="900" alt="image" src="https://user-images.githubusercontent.com/4230892/215726509-3b3e7200-54b3-4250-b23d-a889b5730709.png">

资产列表界面
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/4230892/215726830-a73da3af-a962-418f-af56-0911dcba3700.png">

资产中系统用户界面
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/4230892/215727042-3180e804-752f-46ad-a5be-44792354db71.png">

Web终端无法登录
<img width="997" alt="image" src="https://user-images.githubusercontent.com/4230892/215727297-bd22f6dd-1c2e-4280-91b8-470212605445.png">

**Comment by wml3** [comment]
在V2版本，特权用户不会自动作为资产登陆用户，资产登陆的系统用户依据授权规则配置，查看授权规则配置是否正确

**Comment by kevynull** [comment]
> 

谢谢，问题解决了。看了下配置，的确在「授权规则」中配置只有「根用户」。这点设计上，有点违反直觉。一直认为是系统用户是在资产中配置的，而实际上则是在资产授权中配置的。
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/4230892/216301092-446d6885-10c4-4ab9-aa13-d2f76c97dfb6.png">

**Comment by BaiJiangJie** [comment]
好的，v3 版本相对于 v2 版本在系统用户方面有比较大的更新，如果可以的话，建议升级到 v2.28 的最新版本，或者 v3 版本进行使用。@kevynull
