### ISSUE TITLE
[Bug] 172.17网段的设备无法管理

### ISSUE THREAD

**Issue by jacquen** [jumpserver/jumpserver#9405]
Hi

我有一些设备在172.17网段内, 安装了jumpserver以后, 无法jumpserver访问这些设备.

显示错误:error: 网络不通（连接超时）

我在管理界面测试的时候没问题．别的网段的设备也没问题．如何修复这个问题？谢谢．

**Comment by luweijun1992** [comment]
> Hi
> 
> 我有一些设备在172.17网段内, 安装了jumpserver以后, 无法jumpserver访问这些设备.
> 
> 显示错误:error: 网络不通（连接超时）
> 
> 我在管理界面测试的时候没问题．别的网段的设备也没问题．如何修复这个问题？谢谢．

是不是docker容器网段冲突了，排查下。
`
docker inspect jms_core | grep IPAddress
`

**Comment by wml3** [comment]
修改 docker 网络即可

**Comment by jacquen** [comment]
> > Hi
> > 我有一些设备在172.17网段内, 安装了jumpserver以后, 无法jumpserver访问这些设备.
> > 显示错误:error: 网络不通（连接超时）
> > 我在管理界面测试的时候没问题．别的网段的设备也没问题．如何修复这个问题？谢谢．
> 
> 是不是docker容器网段冲突了，排查下。 `docker inspect jms_core | grep IPAddress`

docker inspect jms_core | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "192.168.250.3",

**Comment by jacquen** [comment]
> 修改 docker 网络即可

能否具体说说修改那个网络?谢谢

**Comment by wojiushixiaobai** [comment]
[Configure the default bridge network](https://docs.docker.com/network/bridge/#configure-the-default-bridge-network)
```json
# cat /etc/docker/daemon.json

{
  "bip": "192.168.1.1/24"
}
```
