### ISSUE TITLE
user中使用get_group_permissions有问题

### ISSUE THREAD

**Issue by xiao-fengzi** [jumpserver/jumpserver#941]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0
##### 问题复现步骤
1. [步骤1]
使用user.object.get(id=2).get_group_permissions()
提示ValueError: Cannot query "test1": Must be "Group" instance
这个让我好生费解

2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]

....
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/35184745-7c9b2498-fe34-11e7-9183-865b8a1f9b20.png)

**Comment by xiao-fengzi** [comment]
你这是取的id为1  也就是admin,如果角色为管理员角色，这里是没有问题的，
但是如果是非管理员角色 ，这里就会像我上图那样异常

**Comment by ibuler** [comment]
知道原因了，jumpserver 的UserGroup没有继承 django的组，所以不能执行该方法，但是如果继承的话也会有问题，因为group并不是一个abstract类，使用起来有些问题
