### ISSUE TITLE
[Feature] 增加飞书登录同时创建用户账户的功能

### ISSUE THREAD

**Issue by bud-zhenlanbing** [jumpserver/jumpserver#9417]
目前 Jumpserver 提供的飞书登录功能必须先让用户密码登录然后再绑定飞书，这样当有新用户，还是需要管理员手动添加账号，非常麻烦。希望增加飞书登录同时创建用户账户的功能，以减少管理员的负担。

提出此 issue 的原因是希望 Jumpserver 的飞书登录功能可以更加方便，让用户可以更方便地登录，同时减少管理员的工作量。希望您能考虑此建议并作出相应的改进。

**Comment by BaiJiangJie** [comment]
好的，目前考虑到用户安全问题，所以强制用户已存在并且需要绑定成功后才可以使用扫码登录。

计划在 v3.3 或者 v3.4 版本中，支持不存在的用户扫码直接登录。

**Comment by BaiJiangJie** [comment]
v3.3.0 版本中已支持。
