### ISSUE TITLE
创建用户报错

### ISSUE THREAD

**Issue by plakhp** [jumpserver/jumpserver#943]
[简述你的问题]

我创建建户后，提交时，报以下错误：

Request Method: | POST
-- | --
http://192.168.X.X:8080/users/user/create
1.11
OSError
[Errno 5] Input/output error
/opt/jumpserver/apps/users/utils.py in send_user_created_mail, line 62
/usr/bin/python
3.5.1
['/opt/jumpserver/apps',  '/usr/local/python35/bin',  '/usr/local/python35/lib/python35.zip',  '/usr/local/python35/lib/python3.5',  '/usr/local/python35/lib/python3.5/plat-linux',  '/usr/local/python35/lib/python3.5/lib-dynload',  '/usr/local/python35/lib/python3.5/site-packages',  '/usr/local/python35/lib/python3.5/site-packages/setuptools-38.4.0-py3.5.egg',  '/opt/jumpserver',  '/opt/jumpserver/apps']

**Comment by ibuler** [comment]
input/output error或许是语言设置？尝试操作系统改为 utf8字符集

**Comment by ahaii** [comment]
同样的错误

**Comment by ibuler** [comment]
你们是在什么操作系统运行的？

**Comment by ahaii** [comment]
CentOS7.2

**Comment by ahaii** [comment]
debug 信息显示 好像是调用发送邮件函数时失败，

**Comment by ahaii** [comment]
File "/data/local/jumpserver/apps/users/signals.py", line 16, in send_user_add_mail_to_user
    send_user_created_mail(user)
  File "/data/local/jumpserver/apps/users/utils.py", line 62, in send_user_created_mail
    print(message)
OSError: [Errno 5] Input/output error


日志显示发邮件这块有问题，有解么？ @ibuler

**Comment by ibuler** [comment]
注释掉那行
