### ISSUE TITLE
windows连接 DBClient 数据库

### ISSUE THREAD

**Issue by get-A-sys** [jumpserver/jumpserver#9437]
在 windows的命令行中，输入 DB Client 生成的命令行，总报错，密码时效性也都在时间内，密码也输入了很多次，总是报错

ERROR 1045 (HY000): Access denied for user 'root'@'192.168.10.102' (using password: YES)

**Comment by wojiushixiaobai** [comment]
检查你 windows 安装的 mysql client 是否兼容这种语法
