### ISSUE TITLE
coco 应用jumpserver-python-sdk 安装失败

### ISSUE THREAD

**Issue by xiaodingding** [jumpserver/jumpserver#945]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
最新版coco
##### 问题复现步骤
1. [步骤1]
安装环境：Python-3.6.1
2. [步骤2]
pip install -r requirements.txt
##### 具体表现[截图可能会更好些,最好能截全]
jumpserver-python-sdk==0.0.23 安装失败

![image](https://user-images.githubusercontent.com/5170656/35184371-9d931b1a-fe2f-11e7-8e5c-cf763eeb4432.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
不要使用国内镜像，也就是安装的时候不要指定 -i

**Comment by xiaodingding** [comment]
也还是找不到。。

**Comment by ibuler** [comment]
https://pypi.org/project/jumpserver-python-sdk/

**Comment by xiaodingding** [comment]
谢谢哈，各种试了一下啊，用easy_install 可以安装
