### ISSUE TITLE
[Feature] 建议web终端页面的资产列表展示资产备注信息

### ISSUE THREAD

**Issue by huguangya** [jumpserver/jumpserver#9458]
**请描述您的需求或者改进建议.**
需求描述：建议web终端页面的资产列表展示资产备注信息
需求背景：
1、堡垒机资产命名一般是ip或机器名，因此用户习惯在资产列表添加备注信息标识业务系统及其他属性，但是在连接资产的web终端web终端页面（黑框控制台页面，见下图2）没有展示备注信息，用户还需要回到资产列表页面才能看到，建议优化。
![1675822016774](https://user-images.githubusercontent.com/54281046/217410432-10648f2e-2e08-45b5-946e-f444a3af55fc.png)
![image](https://user-images.githubusercontent.com/54281046/217410399-f02a536e-5d92-43d9-b1ec-8e236d1a7a72.png)
2、另外会有第三方对接的场景，用户通过其他平台直接单点登录打开web控制台页面，此种场景下用户一般都不会再单独打开堡垒机资产列表页面，因此web终端页面展示备注信息会更有必要。（关联场景，后续计划由云管平台直接推送云管侧的虚拟机备注信息给jumpserver，此种场景下备注信息会更有价值）
帮忙优先排期哈，感谢！

**Comment by BaiJiangJie** [comment]
计划在 v3.2 版本中将资产的备注信息在 hover 资产时显示。

目前只显示了 IP 信息。

<img width="507" alt="image" src="https://user-images.githubusercontent.com/32935519/229100289-eddc6508-115c-4e63-97d4-2bdacb8685d6.png">
