### ISSUE TITLE
创建的应用程序用户无法在用户列表中看到

### ISSUE THREAD

**Issue by justlooks** [jumpserver/jumpserver#947]
创建的应用程序用户无法在用户列表中看到，但是如果你创建同样email的用户，会提示该用户存在

##### 使用版本
0.4.0

##### 问题复现步骤
1. 先创建一个应用程序用户
2. 再用户列表里看，无法看到该用户，但是要创建同样email名字的用户却提示该邮箱用户已存在

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
故意隐藏了，有必要显示吗?

**Comment by justlooks** [comment]
但是有一个问题，随着应用的上线下线，我废弃的应用程序用户怎么清理？

**Comment by ibuler** [comment]
此服务账户非服务器上的用户，是jumpserver本身的应用程序账户

**Comment by justlooks** [comment]
也就是如果对使用堡垒机的人来说，是不会有场景会创建这个用户的是吧？

**Comment by ibuler** [comment]
是的，这里会改掉，新建用户没有那个选项
