### ISSUE TITLE
git clone安装的jumpserver版本仍然是v0.3.3，希望提示v0.5.0在哪里

### ISSUE THREAD

**Issue by 854000648** [jumpserver/jumpserver#948]
[简述你的问题]
github 上面最高只能下载v0.3.3 的版本，与官方描述的v0.5.0不符

##### 使用版本
0.3.3  

##### 问题复现步骤
1. 官方demo发现v0.5.0

2. 但是实际下载dev分支，只能clone到 v0.3.3
###### 安装后的
![image](https://user-images.githubusercontent.com/12493547/35213545-f69e66a0-ff98-11e7-9d9d-1711971eee3b.png)

###### 官方demo的v0.5.0
![image](https://user-images.githubusercontent.com/12493547/35213575-0fa2f440-ff99-11e7-9964-ec5e03e65fd6.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by increase0102** [comment]
dev项目就是0.5.0的 我刚搭建的正常

**Comment by 854000648** [comment]
请问有基于docker的安装方式吗？ 或者说与v0.3.3的docker安装方式有区别吗
