### ISSUE TITLE
[Question] Session online list does not disapear 

### ISSUE THREAD

**Issue by shlee4** [jumpserver/jumpserver#9483]
In "Sessions online"  screen
1. When I click the "Monitor" button, a pop-up window appears prompting "Conncect Error Not Found Session".
2. "Terminate" button works well
3. Screen is refreshed,  **but the list does not disappear.**

![Jumpserver Moniter button Click](https://user-images.githubusercontent.com/124868879/217758940-35d3a958-c44c-4a0d-8d77-52b777a32e35.jpg)

![Jumpserver Terminate button Click](https://user-images.githubusercontent.com/124868879/217758976-6fe98faa-b6b3-4af2-bb26-727fc96645c8.jpg)

**Comment by wojiushixiaobai** [comment]
Wrong session, service may need to be restarted to resolve the problem.

**Comment by shlee4** [comment]
> 

Thank you. I'll try it.

**Comment by shlee4** [comment]
> Wrong session, service may need to be restarted to resolve the problem.

Thank you. I'll try it.

**Comment by BaiJiangJie** [comment]
Hi, @shlee4 does the same problem still occur now?

Or I suggest you upgrade to the latest version of **v3** and try it out, will it still appear?

**Comment by shlee4** [comment]
Hi.
We did restart the service, and the problem is resolved.
Thanks.

**Comment by BaiJiangJie** [comment]
Ok, you're welcome.
