### ISSUE TITLE
用户ssh到主机失败

### ISSUE THREAD

**Issue by xunmeng-666** [jumpserver/jumpserver#949]
[简述你的问题]

##### 使用版本
版本：0.3.2

##### 问题复现步骤
1. 新建用户成功
2. 授权主机成功
3. 下载用户key，使用ssh登录，可登录到跳板机，输入编号连接主机时报错
4. WEB可正常登录
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/14903429/35261364-c4a232b4-004a-11e8-95bc-6fe87524b1ce.png)

![image](https://user-images.githubusercontent.com/14903429/35261441-0cf2ac7e-004b-11e8-910c-34e9563f02da.png)

##### 其他
检查服务器并没有生成“用户_角色的key”

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
这个问题貌似之前没有遇到过
