### ISSUE TITLE
在进行用户导入的时候，下载了提供的模板，并编辑，无法执行导入

### ISSUE THREAD

**Issue by justlooks** [jumpserver/jumpserver#950]
在进行用户导入的时候，下载了提供的模板，并编辑，无法执行导入，也无任何提示，按导入按钮没有任何反应

##### 使用版本
0.4.0

##### 问题复现步骤
1. 选择用户管理－》用户－》选择导入，导入模板，然后写入一行用户，保存
2.重新打开用户管理－》用户－》选择导入－》选择编辑好的模板－》点导入

##### 具体表现[截图可能会更好些,最好能截全]
<img width="761" alt="2018-01-23 2 54 37" src="https://user-images.githubusercontent.com/295168/35262001-99f91318-004d-11e8-99c9-77ed714eacf9.png">
<img width="988" alt="2018-01-23 2 57 12" src="https://user-images.githubusercontent.com/295168/35262054-da4940be-004d-11e8-963d-a353756fa0b3.png">

**Comment by ibuler** [comment]
0.4版本已经废弃

**Comment by justlooks** [comment]
那上生产我该选择哪个版本？

**Comment by lovefirewall** [comment]
官方建议直接换用0.5.0

**Comment by ericyee** [comment]
模板默认要utf-8格式，你编辑后应该是编码格式变了，重新编辑保存为utf-8就可以
