### ISSUE TITLE
访问静态文件403

### ISSUE THREAD

**Issue by xuzheng0017** [jumpserver/jumpserver#9502]
1. 使用官方提供的 https://jumpserver.github.io/helm-charts 部署
2. 打开首页访问CSS等样式加载不出来，状态码 403
3. 进入容器测试
```curl http://127.0.0.1/static/css/style.css```
一样返回403

版本：2.28.6

**Comment by wojiushixiaobai** [comment]
403 应该是你的 nfs 权限有问题导致，检查下

**Comment by xuzheng0017** [comment]
挂载权限应该没问题，单独给文件777权限还是403
![image](https://user-images.githubusercontent.com/35769132/218062762-7cd86db0-81a4-4d3c-b9f0-ac0efb2480ff.png)

**Comment by xuzheng0017** [comment]
对比了之前在别的集群装过一次2.23.2的版本，生成的static目录权限是755，而这次是750，我找下原因

**Comment by wojiushixiaobai** [comment]
嗯，临时解决手动修复下权限就行，具体要找下原因

**Comment by xuzheng0017** [comment]
新购的某云的容器集群，运行时containerd做了安全加固会自动修改umask值为0027，导致创建的目录权限不对
