### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 2100663502** [jumpserver/jumpserver#9506]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.6
**浏览器版本**
版本 109.0.5414.120 chrom
**Bug 描述**
登陆失效（一段时间未登录）的时候通过api直接登录服务器无法自动重定向到登录界面，一直在反复加载。
请求地址：/luna/?_=1675414651963
**Bug 重现步骤(有截图更好)**
1.第一次登录或者距离上次登录有一段时间,超过一天
2.随意请求内部的一个界面
3.web终端界面一直在反复加载，无法正常连接服务器或者跳转到登录界面
4.手动打开堡垒机主页（登录界面）后，再打开 /luna/?_=1675414651963 能跳转到登录界面，恢复正常

**Comment by actck** [comment]
相同的问题，浏览器是Safari
