### ISSUE TITLE
windows chrome web terminal无法粘贴外部命令无法粘贴

### ISSUE THREAD

**Issue by roarlion** [jumpserver/jumpserver#951]
[简述你的问题]

##### 使用版本
[0.5.0]

##### 问题复现步骤
1. [步骤1]复制电脑文本中的命令或者链接的另一台终端的命令
2. [步骤2]在web terminal中右键无法进行粘贴

##### 具体表现[截图可能会更好些,最好能截全]

![qq 20180123193251](https://user-images.githubusercontent.com/31337464/35273887-1f77e646-0075-11e8-9ac8-53edc265fd51.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@liuzheng

**Comment by liuzheng** [comment]
问题已经fix，等会儿push代码，然后选中复制有些小问题，再看
