### ISSUE TITLE
vim编辑文件后的录像不能继续回放

### ISSUE THREAD

**Issue by xyaxlz** [jumpserver/jumpserver#952]
[vim 一个文件后录像不能继续回放]

##### 使用版本
[0.3.2 ]

##### 问题复现步骤
1. [vim 编辑一个文件后，再执行一些其他命令]
2. [观察回放录像，vim 以后，其它命令不能回放，vim 编辑过程也不能记录]

##### 具体表现[截图可能会更好些,最好能截全]

<img width="591" alt="default" src="https://user-images.githubusercontent.com/5790900/35280103-15505d0a-008a-11e8-8b76-8c7ca3dea0c4.png">

数据卡在22秒 不能向下回放
<img width="388" alt="default" src="https://user-images.githubusercontent.com/5790900/35280135-365d2f3c-008a-11e8-8a3d-730a1f49b6b5.png">
在vim 编辑文件后还有其它操作

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
0.3.2 bug不再修复

**Comment by foreveryan** [comment]
@xyaxlz 
给你提供一个方法，希望对你有用。
在服务器上找到对应的记录操作的log文件，如`aaa.log`
使用linux自带的`split`（version≥v8.21）命令对其进行按行分割，每行分割为一个文件,文件前缀为`per_`：
`split -l 1 aaa.log per_`

使用for循环逐帧输出结果文件。
`for I in per_* ; do cat $I ; sleep 0.2 ; done`

即可在你的终端屏幕上输出整个录像全过程。

借助上面这个思路，你也可以同时读取log文件对应的time文件，如`aaa.time`，从中获取对应的增量时间差和字节数，写个脚本逐帧按字节读取对应log的内容，也就和Jumpserver录像回放的逻辑一样了。
