### ISSUE TITLE
安装jumpserver 3 以后 su - 普通账号问题

### ISSUE THREAD

**Issue by linxianjie** [jumpserver/jumpserver#953]
[简述你的问题]
安装了jumpserver3 切换普通账号提示 
![image](https://user-images.githubusercontent.com/35400966/35318032-905343c0-0114-11e8-8897-aec94e2b7ffc.png)

注释掉
![image](https://user-images.githubusercontent.com/35400966/35318067-b61b750a-0114-11e8-986f-01123d7848b8.png)
切换显示
![image](https://user-images.githubusercontent.com/35400966/35318079-c20702a8-0114-11e8-886d-b78ee28901c0.png)

这台服务器是公共用的 我想还原成原来那样可以su - 普通账号

请问怎么操作

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
cat /etc/passwd  修改最后的 init.sh为bash

**Comment by linxianjie** [comment]
@ibuler 
还是不行
![image](https://user-images.githubusercontent.com/35400966/35373363-0cd2d248-01d9-11e8-9e36-ef5f9eb936c3.png)
还是会调
![image](https://user-images.githubusercontent.com/35400966/35373394-263878be-01d9-11e8-8cef-128e806f4432.png)
![image](https://user-images.githubusercontent.com/35400966/35373417-404e57e6-01d9-11e8-9082-cf12f8adf872.png)

**Comment by linxianjie** [comment]
![image](https://user-images.githubusercontent.com/35400966/35378625-75c16cc8-01ee-11e8-9c8a-a7b54f33f03e.png)
