### ISSUE TITLE
使用Mac自带终端连接coco卡死

### ISSUE THREAD

**Issue by sz233** [jumpserver/jumpserver#955]
[简述你的问题]
使用Mac自带终端连接coco服务时卡死。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
v0.5.0

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/30258956/35323086-57695956-0127-11e8-9d66-6af200d88862.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
附上 coco的debug log

**Comment by sz233** [comment]
mac现在无法复现，使用secureCRT也有类似问题，日志如下：
![image](https://user-images.githubusercontent.com/30258956/35497173-028d046a-0504-11e8-9ee2-b1b3245d3634.png)

**Comment by ibuler** [comment]
fixed
