### ISSUE TITLE
0.5.0  创建系统用户不能上传私钥

### ISSUE THREAD

**Issue by leecynew** [jumpserver/jumpserver#959]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1] 取消自动生成秘钥，上传ssh私钥
2. [步骤2] 点击提交，上传的私钥不见了，并提示密钥和密码必须填写一个

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28134330/35376936-2ed142d0-01e8-11e8-8c9e-97c390e15004.png)
![image](https://user-images.githubusercontent.com/28134330/35376991-68b6d8b6-01e8-11e8-907d-2ab9949b4223.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ericyee** [comment]
上传的秘钥在生成的时候不能设置密码，否则提示秘钥不正确。

**Comment by ibuler** [comment]
这个问题已找到原因，可能是你的秘钥加密了, 尝试更新一下 Jumpserver

**Comment by ibuler** [comment]
测试没问题关闭 issue
