### ISSUE TITLE
[Bug] 命令过滤规则没有绑定任何资源依然生效的问题

### ISSUE THREAD

**Issue by Lihy6472** [jumpserver/jumpserver#9590]
**JumpServer 版本(v1.5.9以下不再支持)**

> v2.28.7

**浏览器版本**

> chrome 110.0.5481.96

**Bug 描述**

> 在命令过滤里设置过滤规则为rm命令，绑定用户gientech，但是使用其他用户(root用户)在web端登陆后执行rm命令也会提示命令禁止。

**Bug 重现步骤(有截图更好)**
1. 创建命令过滤
![image](https://user-images.githubusercontent.com/116717391/219315513-456e0842-db63-403f-8029-5a8b1b2729a8.png)
2. 创建命令过滤器{类型：命令、内容：reboot poweroff halt shutdown rm、动作：拒绝、忽略大小写：忽略} 
![image](https://user-images.githubusercontent.com/116717391/219315608-78cc06b6-4ea6-4dc6-9ccb-ef6f1903f2d4.png)
3. 绑定用户组：普通用户、绑定系统用户：低权限用户(gientech)
![image](https://user-images.githubusercontent.com/116717391/219315948-fcda8406-01fb-4627-8b7a-b2e73bcdaca0.png)
4. 使用root用户登陆资产测试执行rm命令提示"rm命令是被禁止的"
![image](https://user-images.githubusercontent.com/116717391/219316271-5b17b238-c307-4faa-8a16-a71e5604fa64.png)

* 附件为视频回放
[d6eed3a9-32ec-4eaf-8627-5d6d620ee4fc_2.zip](https://github.com/jumpserver/jumpserver/files/10754010/d6eed3a9-32ec-4eaf-8627-5d6d620ee4fc_2.zip)

**Comment by wojiushixiaobai** [comment]
删除 `普通用户` 组，看问题是否复现

**Comment by Lihy6472** [comment]
* 删除"普通用户组"后问题依然存在。
![image](https://user-images.githubusercontent.com/116717391/219323160-251ef94d-3de6-46b7-805e-7d6a9f081726.png)
![image](https://user-images.githubusercontent.com/116717391/219323211-f201cece-f8a6-46c6-be4a-f3dabf5b36d7.png)
![image](https://user-images.githubusercontent.com/116717391/219323338-7a2704d7-f655-4d42-982f-9536a1c96cd4.png)

**Comment by wojiushixiaobai** [comment]
我的意思是，`命令过滤器` 只绑定 `gientech` 的情况下，其他系统用户是否受到影响

**Comment by Lihy6472** [comment]
* 现在命令过滤器没有绑定用户、用户组、应用，但是使用root用户在webcli链接服务器后依旧会有影响。

![命令过滤器](https://user-images.githubusercontent.com/116717391/219361762-5784c171-dda5-493b-aa43-44e6fda9a404.png)
![测试命令](https://user-images.githubusercontent.com/116717391/219361959-2d3ee035-2881-4088-aaf4-7e240bd41336.png)
![用户详情](https://user-images.githubusercontent.com/116717391/219362013-077d440c-56c2-462c-8959-668b8b081aa6.png)

**Comment by BaiJiangJie** [comment]
`命令过滤规则` 绑定的用户、用户组、应用、系统用户，它们之间是 或 的关系。

比如：绑定了用户A，那么用户A 登录所有资产/应用时，当前`命令过滤规则`都会生效。其他字段都是一样的逻辑。

按照最后的截图来看，没有绑定任何资源（包括，用户、用户组、应用、系统用户），但是命令依然被禁止了。

这是不应该出现的，如果按照这样的逻辑，删掉所有的命令过滤规则也会禁止命令。

要看一下你的`命令过滤规则`有多少条？是否是其他规则生效了呢？

**Comment by Lihy6472** [comment]
一共只对这几个命令生效"reboot poweroff halt shutdown rm"，并且只设置了这一个过滤规则。

**Comment by BaiJiangJie** [comment]
好的，新版本中对这一块做了重构。
