### ISSUE TITLE
[Bug] JumpServer录像无法删除，导致服务器磁盘被占满

### ISSUE THREAD

**Issue by blooze123** [jumpserver/jumpserver#9605]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.1

**浏览器版本**

**Bug 描述**
用户在本地服务器部署JumpServer，正常使用一段时间后，发现.cast后缀文件达到了1.5T，磁盘空间被占满了，并且该录像文件一直存储在同一天（2023-02-01）。

**Bug 重现步骤(有截图更好)**
1.  用户出现录像文件空间被占满
![9f11bb5d98ece06a83e7f733befce7d](https://user-images.githubusercontent.com/47737772/219575145-f8e260ba-67ba-4e8f-be94-e0cedfebdabe.png)
2.排查用户录像存储文件夹，发现录像全部存储在了 2023-02-01 这个文件夹下面，并且文件空间占用1.5T空间
![0986724f02fd803cebf02d567810115](https://user-images.githubusercontent.com/47737772/219575608-fa80470e-5148-42a5-8528-34b0d85b41aa.png)

**Comment by china-live** [comment]
我记得管理员帐户好像可以设置录像保存期的样（不确定）

**Comment by blooze123** [comment]
可以设置，我这边也有跟用户建议设置定期清理超时录像的方案。但是这个录像全部存储在了同一天的文件夹下的bug应该还是在的，需要排查一下原因

**Comment by wojiushixiaobai** [comment]
录像 bug，会话异常中断但是无法正常结束导致的。
手动删除该录像后重启服务即可解决

**Comment by BaiJiangJie** [comment]
有几种解决方案，考虑一下：

1. 使用 NFS 挂在录像存储目录
2. 配置 OSS 录像存储存放录像
3. 根据使用频率，配置定期清理（v3版本已解决）

**Comment by meitounao-hub** [comment]
我也遇到了同样的问题。在web终端的在线会话里，找到该异常的会话后将其终断后解决了。

**Comment by meitounao-hub** [comment]
但是后续还会出现异常会话导致问题出现。该怎样彻底解决下呢？
