### ISSUE TITLE
0.5版本web_terminal 404 问题

### ISSUE THREAD

**Issue by 303563041** [jumpserver/jumpserver#961]
[简述你的问题]
0.5 jms web_terminal 404 报错
##### 使用版本
0.5.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. admin 用户登录复现问题
1）右上角选user page，
![image](https://user-images.githubusercontent.com/18571915/35397663-fd126646-022a-11e8-8e07-734ea87f3e28.png)

2）然后左侧选择web_terminal，
![image](https://user-images.githubusercontent.com/18571915/35397723-279e945c-022b-11e8-9b77-983c3d8efde0.png)

3）直接跳转到404错误页面。
![image](https://user-images.githubusercontent.com/18571915/35398046-fd76ef3e-022b-11e8-81a8-1bfbdf2c88b9.png)

2. 使用普通用户登录复现问题
参考上面第2）、3）操作截图。

##### 其他

[注:] 完成后请关闭 issue

**Comment by Sandra299** [comment]
你好，我也遇到这样的问题，请问你是怎么解决的呢？
