### ISSUE TITLE
[Question] 无法登录，提示为设置你的浏览器支持cookie

### ISSUE THREAD

**Issue by cataglyphis** [jumpserver/jumpserver#9618]
登录系统后，提示`设置你的浏览器支持cookie`，重启各个服务后尝试登录仍然报该错误，导致无法正常登录

**Comment by cataglyphis** [comment]
有遇到这个问题么？现在网页进不去

**Comment by wojiushixiaobai** [comment]
请通过根路径进入，比如 jumpserver.domani.com
如果现象还是一样，请清理 cookie 后继续测试
如果问题依旧，请检测 waf 是否拦截了

**Comment by cataglyphis** [comment]
> 请通过根路径进入，比如 jumpserver.domani.com 如果现象还是一样，请清理 cookie 后继续测试 如果问题依旧，请检测 waf 是否拦截了

重新用 docker 部署了，现在没问题了~感谢
