### ISSUE TITLE
V0.3.2配置及屏幕录像

### ISSUE THREAD

**Issue by ehui168** [jumpserver/jumpserver#962]
[简述你的问题]
1、请问0.3.2的屏幕录像文件保存路径在哪？能否导出备份
2、Jumpserver系统部署到生产环境后，日常配置文件该如何备份？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.3.2
##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
/opt/jumpserver/logs/tty中，备份内容较多  /home /etc/passwd /etc/group /opt/jumpserver等等，请尝试新版本
