### ISSUE TITLE
 添加资产无法连接.

### ISSUE THREAD

**Issue by airforce-captain** [jumpserver/jumpserver#963]
[简述你的问题]

添加资产始终无法连接...

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

0.5.0

##### 问题复现步骤
1. [步骤1]
先添加一个主机的管理用户如root
2. [步骤2]
然后添加这个主机资产，选择使用第一步添加的管理用户。
3. [步骤3]
然后点击测试连接，或者获取资产信息，都提示无法到达.， 我确定添加的管理用户和密码是正确的，添加的资产主机手工ssh也是可以连接的。

##### 具体表现[截图可能会更好些,最好能截全]

{"unreachable":true,"msg":"Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1516939829.2810884-243789368722810 `\" && echo ansible-tmp-1516939829.2810884-243789368722810=\"` echo ~/.ansible/tmp/ansible-tmp-1516939829.2810884-243789368722810 `\" ), exited with result 3","changed":false}}}}

##### 其他

官方文档不齐全或过时未更新，也有可能是我没找到。

**Comment by airforce-captain** [comment]
已经解决， 环境是docker , 需要安装openssh客户端.否则就出现ansible 无法连接的情况.

**Comment by he-aook** [comment]
我也是用docker安装的 opens-clients客户端我已经安装了但是还是ping不通呢
