### ISSUE TITLE
[Question] windows禁用了LM响应后无法远程

### ISSUE THREAD

**Issue by china-live** [jumpserver/jumpserver#9630]
**请描述您的问题.**
Windows 2008R2 服务器上发现大量ntlmssp登录审核失败日志，于是在组策略里禁用了LM响应。
发现堡垒机无法远程了，该怎么办？
![Uploading QQ图片20230220132103.png…]()

**Comment by wojiushixiaobai** [comment]
图片无法查看

**Comment by china-live** [comment]
这个图片没什么，就是如何禁用LM响应的，参考这个
http://mt.sohu.com/20170316/n483614214.shtml

**Comment by china-live** [comment]
现在的问题是，不禁用的话，服务器上有很多审核失败记录。

**Comment by wojiushixiaobai** [comment]
建议使用防火墙 + 白名单的方式处理，参考 `http://mt.sohu.com/20170316/n483614214.shtml` 文档操作后，所有用户均无法远程，此问题与 JumpServer 无关，你可能需要微软的专家技术支持
