### ISSUE TITLE
0.5.0 还有批量执行命令的功能吗

### ISSUE THREAD

**Issue by leecynew** [jumpserver/jumpserver#964]
[简述你的问题]

##### 使用版本 0.5.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]连接ssh server 没有看见批量执行执行命令
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/28134330/35426529-ade98b66-029e-11e8-86c2-711f666cd086.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by Nidhoggur1993** [comment]
可以看这个 #940  ，以后应该会有

**Comment by ibuler** [comment]
已在下个feature中
