### ISSUE TITLE
命令返回很多结果时，页面卡死

### ISSUE THREAD

**Issue by thorzhang** [jumpserver/jumpserver#966]
[简述你的问题]

##### 使用版本
0.5.0

##### 问题复现步骤
1. 比如输入history，会返回很多结果
2.  页面卡死，无法再做任何操作。
![qq 20180126154018](https://user-images.githubusercontent.com/32703327/35429488-43e6ccea-02af-11e8-80fa-38a59728c503.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
@liuzheng

**Comment by liuzheng** [comment]
请尝试使用最新的luna release版本，Luna的0.5-beta需要同步升级coco，从页面上看你这个不是最新版本，未来截图或提issue请添加左下角的版本，如还有bug，请reopen该issue
