### ISSUE TITLE
ssh登陆不成功

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#967]
[简述你的问题]
在终端和web终端都不能ssh进去
##### 使用版本
0.5.0-2

##### 问题复现步骤
source /opt/py3/bin/activate
python /opt/coco/run_server.py &
exit
##### 具体表现[截图可能会更好些,最好能截全]
当coco运行在前台时没有问题。
通过&将其放在后台，也没有问题。
退出shell，coco仍然在运行，但是客户端就不能登陆了，ssh -v显示停在了env LANG，而且不能ctrl+c终止
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending environment.
debug1: Sending env XMODIFIERS = @im=ibus
debug1: Sending env LANG = zh_CN.UTF-8
光标在此闪烁

##### 其他

[注:] 完成后请关闭 issue

**Comment by yyhutao** [comment]
我也遇到同样的问题

**Comment by ibuler** [comment]
使用新版本试试
