### ISSUE TITLE
v0.5版本，users_users表中password如何加密的

### ISSUE THREAD

**Issue by devon6686** [jumpserver/jumpserver#970]
[简述你的问题]

##### 使用版本
 使用的是0.5.0

##### 问题复现步骤
1. 想直接修改mariadb中users_users表中用户的password，password密码是如何加密的？

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
自己看代码，你这属于第三方入侵修改。。。这个在我们这边不被允许的

我们应该说是强烈反对你这样做，你这个问题很有黑客入侵的倾向，找到系统的注入点了？然后直接dump表？

**Comment by devon6686** [comment]
好的，了解了
