### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by G-lin** [jumpserver/jumpserver#9709]
**问题：**
_连接数据库时，用Web CLI可以正常访问数据库，但是选DB Client，使用生成的数据库连接信息却无法访问。_
**命令：**
mysql -u 309f2704-0f02-476c-9795-xaa44x9225ac -pmUipxpsdGIa5Sm47 -h xxxx.xxxx.xxx -P 30000 db_name。
**数据库版本：**
v5.7.29。
**报错信息：**
ERROR 2003 (HY000): Can't connect to MySQL server on 'xxxx.xxxx.xxx' (60)。

**自己的思考：**
是因为我配置的HTTP_PORT不是80（我用的8080） ，然后我在统一的入口#服务器A#使用nginx80和443端口代理到安装了jumpServer#服务机器B#的8080端口导致的吗？我的#服务器A#和#服务器A#都放通了30000/30100端口，还是不行，但使用IP加端口访问就没问题，如果我还是想用域名访问的话，我需要做什么呢？

**Comment by wojiushixiaobai** [comment]
TCP 端口转发规则检测下，看起来这不是 JumpServer 的问题，而是入口服务器到堡垒机的端口转发出现了问题。

**Comment by G-lin** [comment]
> 而是入口服务器到堡垒机的端口

这个多个端口的转发应该怎么做呢？而且我还想用域名。 <域名+端口号> 这样的方式访问不了吧

**Comment by G-lin** [comment]
> TCP 端口转发规则检测下，看起来这不是 JumpServer 的问题，而是入口服务器到堡垒机的端口转发出现了问题。

谢谢，我自己研究一下，先吧这个关了
