### ISSUE TITLE
coco升级后错误

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#971]
[简述你的问题]

##### 使用版本
[0.5.0-2 GPLv2]

##### 问题复现步骤

coco升级后发现授权的主机都看不到了，杀掉进程重启后报错
# python run_server.py 
2018-01-29 11:37:35 [service DEBUG] Initial app service
2018-01-29 11:37:35 [service DEBUG] Load access key
2018-01-29 11:37:35 [service INFO] No access key found, register it
2018-01-29 11:37:35 [service INFO] "Terminal was not accepted yet"
2018-01-29 11:37:38 [service INFO] "Terminal was not accepted yet"
2018-01-29 11:37:41 [service DEBUG] Set app service auth: 72a57b15-a9e2-4d1c-af80-531a50012b64:20ca8961-c8b6-4ac7-9799-ea3bac6b229d
2018-01-29 11:37:41 [service ERROR] Connect server error or access key is invalid, remove `./keys/.access_key` run again
2018-01-29 11:37:44 [service ERROR] Connect server error or access key is invalid, remove `./keys/.access_key` run again
2018-01-29 11:37:47 [service ERROR] Connect server error or access key is invalid, remove `./keys/.access_key` run again

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
这报错已经解释了该怎么做啊。。。。郁闷了。。。要用中文打一遍？

"Terminal was not accepted yet"

=== 终端不被授权

Connect server error or access key is invalid, remove ./keys/.access_key run again

链接服务错误或者请求密钥不合法， 删除./keys/.access_key 并重启


我也是醉了

**Comment by qianghong000** [comment]
删除重启了还是起不来
2018-01-29 11:41:15 [service DEBUG] Initial app service
2018-01-29 11:41:15 [service DEBUG] Load access key
2018-01-29 11:41:15 [service INFO] No access key found, register it
2018-01-29 11:41:15 [service ERROR] Failed register terminal OP_Manage exist already

**Comment by qianghong000** [comment]
jumpserver也需要重启吗

**Comment by qianghong000** [comment]
删除./keys/.access_key，然后删除页面里以前授权过的终端，运行python run_server.py 以后，重新授权终端，依旧报错：[service ERROR] Connect server error or access key is invalid, remove `./keys/.access_key` run again

**Comment by qianghong000** [comment]
Requirement already satisfied: asn1crypto==0.23.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: bcrypt==3.1.4 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: boto3==1.5.18 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: botocore==1.8.32 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: certifi==2017.11.5 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: cffi==1.11.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: chardet==3.0.4 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: click==6.7 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: cryptography==2.1.4 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: Flask==0.12.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: Flask-SocketIO==2.9.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: idna==2.6 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: itsdangerous==0.24 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: Jinja2==2.10 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: MarkupSafe==1.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: paramiko==2.4.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: psutil==5.4.1 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: pyasn1==0.4.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: pycparser==2.18 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied: PyNaCl==1.2.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied: pyte==0.7.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied: python-engineio==2.0.1 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied: python-gssapi==0.6.4 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied: python-socketio==1.8.3 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied: pytz==2017.3 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: requests==2.18.4 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied: simplejson==3.13.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied: six==1.11.0 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: tornado==4.5.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied: urllib3==1.22 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied: wcwidth==0.1.7 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: werkzeug==0.12.2 in /opt/py3/lib/python3.6/site-packages (from -r requirements.txt (line 32))
Collecting jumpserver-python-sdk==0.0.27 (from -r requirements.txt (line 33))
  Could not find a version that satisfies the requirement jumpserver-python-sdk==0.0.27 (from -r requirements.txt (line 33)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26)
No matching distribution found for jumpserver-python-sdk==0.0.27 (from -r requirements.txt (line 33))

重新pull最新的coco，pip install -r requirements.txt 安装依赖报错

**Comment by ibuler** [comment]
https://pypi.org/project/jumpserver-python-sdk/  那可能是你的pypi有镜像

**Comment by liuzheng** [comment]
cat ~/.pip/pip.conf
你一定使用了国内源加速了

**Comment by qianghong000** [comment]
怎么解决呢？手动改成0.0.26行吗

**Comment by liuzheng** [comment]
wiki 上写的很明确了。。。。
https://github.com/jumpserver/jumpserver/wiki/v0.5.0-%E5%9F%BA%E4%BA%8E-CentOS7
![image](https://user-images.githubusercontent.com/1198380/35494477-dc51bd12-04f5-11e8-8753-91c507a65ce3.png)

**Comment by qianghong000** [comment]
已经解决，谢谢

**Comment by buguoqiang** [comment]
@qianghong000 请告知我如何解决的，我重新安装（重装了centos系统）了jumpserver和coco，确认没有使用国内的源，可问题依旧，谢谢。

**Comment by qianghong000** [comment]
jumpserver安装依赖库的时候不要指定-i参数

**Comment by qianghong000** [comment]
cat ~/.pip/pip.conf
[global]
index-url=http://mirrors.aliyun.com/pypi/simple

[install]
trusted-host=mirrors.aliyun.com
改成这个。然后删除./keys/.access_key

**Comment by buguoqiang** [comment]
在我接受这个coco之后，看到系统发送邮件到某个地址，提示如下：

\'创建账户成功\', \'\n    你好 coco-b3f59b:\n    </br>\n    恭喜您，您的账号已经创建成功    </br>\n     <a href="http://192.168.98.131:8080/users/password/reset?token=eyJhbGciOiJIUzI1NiIsImlhdCI6MTUxNzIxMTg2OSwiZXhwIjoxNTE3MjE1NDY5fQ.eyJyZXNldCI6IjNlNzMwMDQ2LThiNTgtNDcyNi1hMTIxLTI0YTg1ZTEwMmJhNyIsImVtYWlsIjoiY29jby1iM2Y1OWJAbG9jYWwuZG9tYWluIn0.VKxFmjMPBbovFGTCoyXUjj-nuRk9qi1cvAdoDiIjmmo">请点击这里设置密码</a>    </br>\n    这个链接有效期1小时, 超过时间您可以 <a href="http://192.168.98.131:8080/users/password/forgot?email=coco-b3f59b@local.domain">重新申请</a>\n\n    </br>\n    ---\n\n    </br>\n    <a href="http://192.168.98.131:8080/users/login">Login direct</a>\n\n    </br>\n    \', [\'coco-b3f59b@local.domain\'])',... kwargs:{}


实际上这个邮件地址并不存在，一定要发送到正确的邮件地址然后通过增加用户的方式来吗？

**Comment by buguoqiang** [comment]
我没有指定源。难道还是必须指定源么？
 
 
------------------ Original ------------------
From: "shihong.qiang"; 
Date: 2018年1月29日(星期一) 下午3:49
To: "jumpserver/jumpserver"; 
Cc: "buguoqiang"; "Comment"; 
Subject: Re: [jumpserver/jumpserver] coco升级后错误 (#971)

 

cat ~/.pip/pip.conf
 [global]
 index-url=http://mirrors.aliyun.com/pypi/simple
 
[install]
 trusted-host=mirrors.aliyun.com
 改成这个。然后删除./keys/.access_key

**Comment by buguoqiang** [comment]
按照您说的，我重试了，问题依旧。我的管理员邮箱收到一个邮件：


很抱歉您发送的邮件被退回，以下是该邮件的相关信息：


被退回邮件	主 题：[Jumpserver]创建账户成功 
时 间：2018-01-29 15:51:50
无法发送到 coco-a6d51d@local.domain
退信原因	收件人（coco-a6d51d@local.domain）所属域名不存在，邮件无法送达。 
Name service error for name=local.domain type=MX: Host not found
解决方案	请联系您的收件人，重新核实邮箱地址，或发送到其他收信邮箱。 您也可以向腾讯企业邮团队报告此退信。
此外，您还可以 点击这里 获取更多关于退信的帮助信息。



这个是在接受coco的时候收到的邮件，是否跟这个相关？coco的name必须是某个真实的邮件地址？
 
 
------------------ Original ------------------
From: "shihong.qiang"; 
Date: 2018年1月29日(星期一) 下午3:49
To: "jumpserver/jumpserver"; 
Cc: "buguoqiang"; "Comment"; 
Subject: Re: [jumpserver/jumpserver] coco升级后错误 (#971)

 

cat ~/.pip/pip.conf
 [global]
 index-url=http://mirrors.aliyun.com/pypi/simple
 
[install]
 trusted-host=mirrors.aliyun.com
 改成这个。然后删除./keys/.access_key

**Comment by qianghong000** [comment]
不晓得了 我就是改了那个文件解决的

**Comment by buguoqiang** [comment]
@qianghong000 好的，谢谢。能不能把你的coco的配置文件给我看看（隐去关键信息）

**Comment by buguoqiang** [comment]
@liuzheng 我按照所说的方法没有使用国内源，没有“-i”选项和pip.conf，可是问题依旧。请问如何处理，谢谢。

**Comment by qianghong000** [comment]
cp  /opt/coco/conf_example.py   /opt/coco/conf.py   配置文件我什么都没改

**Comment by buguoqiang** [comment]
哎，这个问题，我始终解决不了。上述方法都都按照你们的来做了，重装了系统也不行啊

**Comment by liuzheng** [comment]
@buguoqiang 报错呢，自己读一下，你pip重新安装一下，使用最新的代码
