### ISSUE TITLE
[Question] DB Client 数据库信息 续期token策略

### ISSUE THREAD

**Issue by jones-0701** [jumpserver/jumpserver#9726]
**请描述您的问题.**
使用DB Client链接数据库的方式，通过Navicate链接，并一直处于链接状态下，jumpserver数据库中的过期时间一直在循环刷新，请教一下这里如果一直保持链接的状态下，是无线续期的吗？ 有什么续期策略可以配置吗？

**Comment by ibuler** [comment]
老版本会每过一段时间续一下，v3 新版本不在续期

**Comment by BaiJiangJie** [comment]
v3.3.1 版本支持配置复用，以及过期时间。
