### ISSUE TITLE
[Question] koko 提示当前资产

### ISSUE THREAD

**Issue by weiya1990** [jumpserver/jumpserver#9740]
使用xshell客户端登录时如何在选中资产时的提示信息显示当前资产的主机名和ip？默认安装没有这方面的提示，请问如何配置
![image](https://user-images.githubusercontent.com/38902618/221078063-2a07e63c-ea81-402c-bd03-cdedd56db4ba.png)
![image](https://user-images.githubusercontent.com/38902618/221078372-15280e34-0fd6-4d01-bd49-f388dd8b0f7e.png)

**Comment by ibuler** [comment]
意思是选择了资产，选择账号的时候，提示一下当前资产？

@LeeEirc

**Comment by weiya1990** [comment]
是的，请问可以吗？我现在的版本是v2.27.0




1830624909
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] [Question]  (Issue #9740)





 
意思是选择了资产，选择账号的时候，提示一下当前资产？
 
@LeeEirc

**Comment by LeeEirc** [comment]
不会再 v2 上做改动了，考虑在v3上支持

**Comment by LeeEirc** [comment]
![image](https://user-images.githubusercontent.com/32626707/229774659-b9cad60d-fd09-47e4-b475-67c46a9f369f.png)

将在 v3.2 实现，待发版本。
