### ISSUE TITLE
[Bug] LXC容器下启动失败

### ISSUE THREAD

**Issue by rayfalling** [jumpserver/jumpserver#9743]
**JumpServer 版本(v1.5.9以下不再支持)**
2.87.0- 3.0.0
目前测试了这两个

**Bug 描述**
LXC容器下无法启动docker，/usr/local/bin/clickhouse-client使用了超出65535的UID和GID
参考：https://gitlab.com/Shinobi-Systems/Shinobi/-/issues/452

**Bug 重现步骤(有截图更好)**
1.  PVE创建LXC容器
2. 一键安装脚本
3. 
![image](https://user-images.githubusercontent.com/13343271/221085017-196719dc-93dc-4f50-a988-88ad84a26249.png)

**Comment by ibuler** [comment]
@wojiushixiaobai 可以测测

我们目前没有试过 lxc

**Comment by wojiushixiaobai** [comment]
收到，下个版本解决。
```
# 确实超了，我手动更新下这个包。
-rwxr-xr-x 1 197610 197610 419824648 10月 31 00:48 clickhouse-client
```

**Comment by rayfalling** [comment]
是否有临时解决方案先行安装一下？

**Comment by wojiushixiaobai** [comment]
@rayfalling 手动重新构建下镜像
```bash
git clone -b v3.0.0 https://github.com/jumpserver/koko --depth=1
docker buildx build -t jumpserver/koko:v3.0.0 . --load
```
