### ISSUE TITLE
[Bug] v3 版本无法创建账号

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9750]
**JumpServer 版本(v1.5.9以下不再支持)**

 v3
**浏览器版本**

**Bug 描述**
 在账号列表创建账号时，必须填写资产，而前端页面上没有标识，请问这是bug 还是设计如此？

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by ibuler** [comment]
账号是必须要有资产的，否则就是个凭证或者是个账号模版。

可以在资产中添加账号，或者添加账号时选择某个资产

**Comment by mrsdpz** [comment]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/31802195/221118790-b64d0f29-9945-4b8e-b67f-441aa3082e6b.png">
前端应该添加必填标识
