### ISSUE TITLE
[Feature] v3 版本，无法添加多个协议

### ISSUE THREAD

**Issue by fengziyun** [jumpserver/jumpserver#9751]
![image](https://user-images.githubusercontent.com/28677290/221110634-93b63cf8-7859-4269-b054-e94def2c3c7f.png)
一台机可以有多个VNC，但Jumpserver只支持一个vnc协议，不能写多个端口。

-----
![image](https://user-images.githubusercontent.com/28677290/221111505-618b6f22-7101-4ed2-96b8-9c04dae07c72.png)
密码或者密钥没有自动生成，要靠手动输入

**Comment by ibuler** [comment]
1. 多个 vnc 可以添加多个资产来解决，毕竟这里可能只有 vnc 遇到
2. 自动推送功能还在研发中，未来版本会回归

**Comment by fengziyun** [comment]
这样不方便管理，加上购买了企业版后，一个机器多个资产，一个资产只对应一个人，那么假设一个机器八个用户，有三台服务器，资产就要添加多达24个，这不太合理。

**Comment by fengziyun** [comment]
xrdp可以使用Xvnc，但是显示不正常。
Centos系统下VMware可以打开虚拟机，但是画面不显示，只有直连vnc才正常。Xorgxrdp兼容性没有Xvnc好，但直连vnc不太会出现其他错误。

**Comment by KeitaroDPVF** [comment]
@fengziyun 我这边的情况是这样
需要仅提供VNC连接的主机，但创建主机时必带SSH；想新建平台类型时会发现也是必带SSH。
所以使用**导入**的方式创建了一个平台列表中的主机模版，再以这个模版创建主机资产。
推测可以使用这种方式创建多个相同服务的自定义平台，再以此自定义平台发放虚拟机？
但这不是官方页面提供的功能，可能存在潜在问题。

**Comment by BaiJiangJie** [comment]
资产上暂不考虑支持添加多个相同的协议。
