### ISSUE TITLE
[Feature] v3 认证设置功能单一

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9755]
**请描述您的需求或者改进建议.**
v2 版本有多种认证方式，我们接入了 oauth2，v3 版本目前仅有LDAP CAS 两种，请问未来是否对齐 v2 版本？以及具体的改动时间

**Comment by ibuler** [comment]
v3 版本，收紧了 auth 集成，开放了 remote app 功能。

我们也参考了很多开源软件，这方面也基本是 EE 版本才有的。

**Comment by mrsdpz** [comment]
那未来不会像 v2 一样支持其他的协议了吗?

**Comment by ibuler** [comment]
不会了，希望有能力的公司购买企业版来支持我们继续开发

**Comment by wangdjunfeng** [comment]
> **请描述您的需求或者改进建议.** v2 版本有多种认证方式，我们接入了 oauth2，v3 版本目前仅有LDAP CAS 两种，请问未来是否对齐 v2 版本？以及具体的改动时间

想了解v2版本你用的哪个版本能正常接入oauth2，我遇到无限重定向登陆的问题
