### ISSUE TITLE
[Question] v2 升级 v3 的一些问题

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9758]
我目前的 jumpserver 版本:2.54
1. 是否支持v2任意版本直接升级 v3?
我是否需要升级到 v2最新版本,再升级 v3

2. v2 系统用户与 v3 账号是何种对应关系?
目前系统中同步了大量的密码,但并非每个系统用户都绑定了资产,那么迁移后的密码是录成普通账号还是账号模块?

3.v2 系统用户与资产的关联关系 与  v3 机器密码的关联关系如何对应?
由于某些缘故, 现在系统中的资产莫名其妙的绑定了大量系统用户,有的资产绑定了五六千系统用户,这种情况下迁移至 v3,是否每个机器下面会有大量的账号?

**Comment by ibuler** [comment]
1. v2 可以直接升级到 v3 ，不需要到 v2 最后版本
2. v2 系统用户 和 关联资产 会迁移成 账号，取 系统用户的用户名，密码，密钥 和 资产 组合成一个账号，同名的只会保留一个

对于第二点，我们在研究是否把同名的其他的转换为 账号的历史

**Comment by BaiJiangJie** [comment]
具体的场景，建议 v2 环境先保留下来，在新环境中导入数据库数据升级到 v3 使用一段时间，确认没问题再切换到 v3 环境。

@mrsdpz

**Comment by jhsnbj** [comment]
v2任意版本直接升级 v3，提示 (1146, "Table 'jumpserver.assets_database' doesn't exist")   可以手工把表结构创建吗？
