### ISSUE TITLE
V0.5.0添加资产报错

### ISSUE THREAD

**Issue by devon6686** [jumpserver/jumpserver#976]
[简述你的问题]

##### 使用版本
[ V0.5.0]

##### 问题复现步骤
1. [步骤1]
添加资产的时候报下面的错误：

Exception Type: OSError at /assets/asset/create/
Exception Value: [Errno 5] Input/output error
2. [步骤2]

Environment:

Request Method: POST
Request URL: http://XXX/assets/asset/create/

Django Version: 1.11
Python Version: 3.6.4
Installed Applications:
['users.apps.UsersConfig',
 'assets.apps.AssetsConfig',
 'perms.apps.PermsConfig',
 'ops.apps.OpsConfig',
 'common.apps.CommonConfig',
 'terminal.apps.TerminalConfig',
 'rest_framework',
 'rest_framework_swagger',
 'django_filters',
 'bootstrap3',
 'captcha',
 'django_celery_beat',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'jumpserver.middleware.TimezoneMiddleware',
 'jumpserver.middleware.DemoMiddleware']

Traceback:

File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/root/.pyenv/versions/3.6.4/lib/python3.6/contextlib.py" in inner
  52.                 return func(*args, **kwds)

File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/opt/py3/lib/python3.6/site-packages/django/contrib/auth/mixins.py" in dispatch
  116.         return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)

File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/opt/py3/lib/python3.6/site-packages/django/views/generic/edit.py" in post
  217.         return super(BaseCreateView, self).post(request, *args, **kwargs)

File "/opt/py3/lib/python3.6/site-packages/django/views/generic/edit.py" in post
  182.         if form.is_valid():

File "/opt/jumpserver/apps/assets/forms.py" in is_valid
  51.         print(self.data)

Exception Type: OSError at /assets/asset/create/
Exception Value: [Errno 5] Input/output error

**Comment by deeper-yang** [comment]
我也遇到了一样的问题，同求解决方法

**Comment by ibuler** [comment]
不知道为何你们的系统都允许print中文

**Comment by ibuler** [comment]
使用docker了吗？

**Comment by ibuler** [comment]
https://github.com/omab/python-social-auth/issues/716 
https://stackoverflow.com/questions/34643170/amazon-django-each-12-hours-appears-that-errno-5-input-output-error

Since the error is in a print statement, I would assume that the server stdout is closed, thus producing an IO error when trying to write to it.
应该是你的server stdout关闭了，如果是docker则很有可能

**Comment by ibuler** [comment]
https://groups.google.com/forum/#!topic/django-users/D7nqbmjhNOM

**Comment by ibuler** [comment]
如果方便，teamview解决一下，请联系我

**Comment by devon6686** [comment]
没用docker

**Comment by ibuler** [comment]
解决了？

**Comment by deeper-yang** [comment]
修改  /etc/sysconfig/i18n  
字符集改成英文
LANG="en_US.UTF-8"
然后重启jumpserver服务，这个报错就没有了

**Comment by devon6686** [comment]
好的，我试下
