### ISSUE TITLE
[不确定是不是Bug] Windows资产无法连接

### ISSUE THREAD

**Issue by clannon** [jumpserver/jumpserver#9770]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.0

**浏览器版本**
firefox 102.8.0esr 

**Bug 描述**
添加windows资产，测试连接不通，显示去连目标的22端口，而不是3389，哪个地方有问题？

**Bug 重现步骤(有截图更好)**
1.加资产
<img width="563" alt="1" src="https://user-images.githubusercontent.com/34529891/221341115-f1ec83aa-0e75-4095-9a97-1c082ad195d1.png">

2.测试
<img width="878" alt="2" src="https://user-images.githubusercontent.com/34529891/221341124-9b0bd86d-4caa-49f4-9c64-b535b2f34c22.png">
<img width="651" alt="3" src="https://user-images.githubusercontent.com/34529891/221341128-dac9dc3e-4332-4ff4-8c55-9dd518838204.png">

**Comment by ibuler** [comment]
可连接性是需要 ansible 测试的，ansible 目前需要 ssh

**Comment by clannon** [comment]
> 

这一说我想起来了，之前用的1.4、1.5，印象中windows是有些特殊，好像还有个提示让随便填个系统用户，并且不会显示可连接，原来现在还是这样……后面试了下确实和这里可不可以连接的显示无关，但既然有“测试”的选项，加完资产后八成都会去试试对吧，返回个失败着实有些头疼，像我后面就没再去是不是到底能不能连，毕竟已经提示不能连了嘛~
