### ISSUE TITLE
[Bug Web CLI 连接方式下 文件管理不能上传文件] 

### ISSUE THREAD

**Issue by gaochangshui** [jumpserver/jumpserver#9771]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**

1. 通过 Web CLI 连接资产之后，里面的【文件管理】功能 打开之后不能上传文件。提示 “无法上传 "please select one of the systemUsers".”
2. 通过 Web SFTP 连接资产之后，可以上传和下载文件。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/77267700/221341462-8ae64176-fed0-4044-ae1c-e43bebc6d13b.png)

![image](https://user-images.githubusercontent.com/77267700/221341394-3514c5b4-e4a5-42ce-8a45-5864395fccec.png)

![image](https://user-images.githubusercontent.com/77267700/221341623-d3713150-a671-4d7e-bfc1-4e30bdbd37fc.png)

**Comment by LeeEirc** [comment]
文件管理里，必须是资产上已有的授权账号，如果仅授权手动账号，可以通过 Web SFTP 连接方式管理。
