### ISSUE TITLE
[Question] Integrate jumpserver and keycloak use OIDC

### ISSUE THREAD

**Issue by fsatrion** [jumpserver/jumpserver#9772]
Hi, i've 2 question 

1. i will integrate jumpserver with OIDC and keycloak. 
The authentication process running smootly but i've problem in logout process. I found  `Invalid redirect uri` and session in keycloak still active after click logout button. any solution for this problem? i was following instruction from this [documentation](https://docs.jumpserver.org/zh/master/admin-guide/authentication/openid/#3) 

![image](https://user-images.githubusercontent.com/62125821/221340228-697d8450-0df7-4b34-9bb7-3bbb9efe8333.png)

 **Log from keycloak**
`2023-02-25 05:14:42,916 WARN  [org.keycloak.events] (executor-thread-2309) type=LOGOUT_ERROR, realmId=<myrealm>, clientId=null, userId=null, ipAddress=<my-ip>, error=invalid_redirect_uri, redirect_uri=http://<jumpserver-endpoint>/`

2. After success login user from keycloak, the new user don't have user group and system role. we must assign user group and system role manual after login success, bcause user in keycloak will be stored in jumpserver after login success.
Is this possible to assign role and group before login? maybe use user attr map? if this possible, how about an example of user attr map?

i used default user attr map like this.
```
{
  "name": "name",
  "username": "preferred_username",
  "email": "email"
}
```

**Comment by O-Jiangweidong** [comment]
Problem 1: The keycloak log displays that some endpoint addresses are not valid. F12 console check the specific endpoint address. According to the specific endpoint address analysis problem, it should be caused by the improper configuration in the keycload cloak. The document address of Keycload can be viewed as follows：https://www.keycloak.org/docs/latest/server_admin/index.html#assembly-managing-clients_server_administration_guide

**Comment by O-Jiangweidong** [comment]
Question 2: Currently, JumpServer only supports the synchronization of certain user attributes, such as username, email... (more fields reference: https://github.com/jumpserver/jumpserver/blob/dev/apps/users/models/user.py#L671)

**Comment by O-Jiangweidong** [comment]
You can check it out by clicking the link below：

https://mp.weixin.qq.com/s?__biz=Mzg4MzkwMjM5MQ==&mid=2247485088&idx=1&sn=c2644f5afbb309b8ff6cdb5edfb0595b&chksm=cf411478f8369d6e80be20348cc995af69c293e96b6d1dc34df3a50ebd856dfa3b310249342c&sessionid=0&scene=126&subscene=0&clicktime=1678678152&enterid=1678678152&ascene=3&fasttmpl_type=0&fasttmpl_fullversion=6584559-zh_CN-zip&fasttmpl_flag=0&realreporttime=1678678152496&devicetype=android-33&version=2800213d&nettype=WIFI&abtest_cookie=AAACAA%3D%3D&lang=zh_CN&session_us=gh_3b85d07f7548&countrycode=CN&exportkey=n_ChQIAhIQjdPjXRFepSQK%2FSmBmLVQjxLnAQIE97dBBAEAAAAAAJovC5D9sbIAAAAOpnltbLcz9gKNyK89dVj0CTT%2BSO72h1tOj1ztdBFLuXHARdOpiqpeEpYTnuSNcZTdH%2FY8tQRlm1UbgzP2At4BGSetP0U94K27s3md%2FZmaxD%2FyWFaAlBodj2iGsfExOiHnIa0MjnOS6DU7dMBX4UfpnBwharVGnx3g8r3DDBLXf8UsPE6kiZlVqdueN1riIqio589vHmrfq9SNW372OSMhZesJ19bkyREg%2BZGYOIWHdsXI2mD8QU8tCwDE3bKSCsIQGewzZYUiX6hfmwAoZ%2FUikg%3D%3D&pass_ticket=6hVdYFsUZP5YLV%2FB1c18hXnSeeCgdAM4BPfiJiK5vjKesM3bIimmFVFpvPm8imvgVfVmxOmtLm93VpKW4Og2XQ%3D%3D&wx_header=3

**Comment by fsatrion** [comment]
Thank you for the reference, i was read this link but i can't found detail about mapping attribute.

i have tried with user attribute like this and i found error.

### User attr
```
{
  "name": "name",
  "username": "preferred_username",
  "email": "email",
  "groups": "groups",
  "role": "role"
}
```

## Error in attribute groups
```
2023-03-21 01:34:04 [log ERROR] Internal Server Error: /core/auth/openid/callback/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
users.models.user.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
    user = auth.authenticate(nonce=nonce, request=request)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
    user, created = self.get_or_create_user_from_claims(request, claims)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
    user, created = get_user_model().objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 451, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 498, in __init__
    _setattr(self, prop, kwargs[prop])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__
    raise TypeError(
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
```

## Error in atribute role
```
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'role' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
    user = auth.authenticate(nonce=nonce, request=request)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
    user, created = self.get_or_create_user_from_claims(request, claims)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
    user, created = get_user_model().objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/jumpserver/apps/users/models/user.py", line 824, in save
    return super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'role' at row 1")
```

## keycloak group mapping
![image](https://user-images.githubusercontent.com/62125821/226444089-59faab05-1a34-4981-8e2c-310099713b49.png)

## keycloak role mapping
![image](https://user-images.githubusercontent.com/62125821/226444019-de62f536-c527-48fb-a47a-aa3833a37ca3.png)

Do you have suggest for this problem?

**Comment by fsatrion** [comment]
> Thank you for the reference, i was read this link but i can't found detail about mapping attribute.
> 
> i have tried with user attribute like this and i found error.
> 
> ### User attr
> ```
> {
>   "name": "name",
>   "username": "preferred_username",
>   "email": "email",
>   "groups": "groups",
>   "role": "role"
> }
> ```
> 
> ## Error in attribute groups
> ```
> 2023-03-21 01:34:04 [log ERROR] Internal Server Error: /core/auth/openid/callback/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
>     return self.get(**kwargs), False
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
>     raise self.model.DoesNotExist(
> users.models.user.User.DoesNotExist: User matching query does not exist.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
>     user = auth.authenticate(nonce=nonce, request=request)
>   File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
>     user = backend.authenticate(request, **credentials)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
>     user, created = self.get_or_create_user_from_claims(request, claims)
>   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
>     user, created = get_user_model().objects.get_or_create(
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
>     return self.create(**params), True
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 451, in create
>     obj = self.model(**kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 498, in __init__
>     _setattr(self, prop, kwargs[prop])
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__
>     raise TypeError(
> TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
> ```
> 
> ## Error in atribute role
> ```
> MySQLdb._exceptions.DataError: (1406, "Data too long for column 'role' at row 1")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
>     user = auth.authenticate(nonce=nonce, request=request)
>   File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
>     user = backend.authenticate(request, **credentials)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
>     user, created = self.get_or_create_user_from_claims(request, claims)
>   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
>     user, created = get_user_model().objects.get_or_create(
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
>     return self.create(**params), True
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/opt/jumpserver/apps/users/models/user.py", line 824, in save
>     return super().save(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
>     super().save(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
>     self.save_base(using=using, force_insert=force_insert,
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
>     updated = self._save_table(
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
>     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
>     return manager._insert(
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
>     return query.get_compiler(using=using).execute_sql(returning_fields)
>   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
>     return self.cursor.execute(query, args)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
>     res = self._query(query)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
>     db.query(q)
>   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
>     _mysql.connection.query(self, query)
> django.db.utils.DataError: (1406, "Data too long for column 'role' at row 1")
> ```
> 
> ## keycloak group mapping
> ![image](https://user-images.githubusercontent.com/62125821/226444089-59faab05-1a34-4981-8e2c-310099713b49.png)
> 
> ## keycloak role mapping
> ![image](https://user-images.githubusercontent.com/62125821/226444019-de62f536-c527-48fb-a47a-aa3833a37ca3.png)
> 
> Do you have any suggest for this problem?

@O-Jiangweidong

**Comment by O-Jiangweidong** [comment]
Our keycloak version is 19.0.2, can you try to align the keycloak version here

**Comment by O-Jiangweidong** [comment]
> > Thank you for the reference, i was read this link but i can't found detail about mapping attribute.
> > i have tried with user attribute like this and i found error.
> > ### User attr
> > ```
> > {
> >   "name": "name",
> >   "username": "preferred_username",
> >   "email": "email",
> >   "groups": "groups",
> >   "role": "role"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Error in attribute groups
> > ```
> > 2023-03-21 01:34:04 [log ERROR] Internal Server Error: /core/auth/openid/callback/
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
> >     return self.get(**kwargs), False
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
> >     raise self.model.DoesNotExist(
> > users.models.user.User.DoesNotExist: User matching query does not exist.
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
> >     response = get_response(request)
> >   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
> >     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> >   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
> >     return func(*args, **kwds)
> >   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
> >     return self.dispatch(request, *args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
> >     return handler(request, *args, **kwargs)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
> >     user = auth.authenticate(nonce=nonce, request=request)
> >   File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
> >     user = backend.authenticate(request, **credentials)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
> >     return func(*args, **kwargs)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
> >     user, created = self.get_or_create_user_from_claims(request, claims)
> >   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
> >     return func(*args, **kwds)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
> >     user, created = get_user_model().objects.get_or_create(
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
> >     return getattr(self.get_queryset(), name)(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
> >     return self.create(**params), True
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 451, in create
> >     obj = self.model(**kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 498, in __init__
> >     _setattr(self, prop, kwargs[prop])
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__
> >     raise TypeError(
> > TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use groups.set() instead.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Error in atribute role
> > ```
> > MySQLdb._exceptions.DataError: (1406, "Data too long for column 'role' at row 1")
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
> >     response = get_response(request)
> >   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
> >     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> >   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
> >     return func(*args, **kwds)
> >   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
> >     return self.dispatch(request, *args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
> >     return handler(request, *args, **kwargs)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 142, in get
> >     user = auth.authenticate(nonce=nonce, request=request)
> >   File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
> >     user = backend.authenticate(request, **credentials)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
> >     return func(*args, **kwargs)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 210, in authenticate
> >     user, created = self.get_or_create_user_from_claims(request, claims)
> >   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
> >     return func(*args, **kwds)
> >   File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 60, in get_or_create_user_from_claims
> >     user, created = get_user_model().objects.get_or_create(
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
> >     return getattr(self.get_queryset(), name)(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
> >     return self.create(**params), True
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
> >     obj.save(force_insert=True, using=self.db)
> >   File "/opt/jumpserver/apps/users/models/user.py", line 824, in save
> >     return super().save(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
> >     super().save(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
> >     self.save_base(using=using, force_insert=force_insert,
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
> >     updated = self._save_table(
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
> >     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
> >     return manager._insert(
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
> >     return getattr(self.get_queryset(), name)(*args, **kwargs)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
> >     return query.get_compiler(using=using).execute_sql(returning_fields)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
> >     cursor.execute(sql, params)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
> >     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
> >     return executor(sql, params, many, context)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
> >     return self.cursor.execute(sql, params)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
> >     raise dj_exc_value.with_traceback(traceback) from exc_value
> >   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
> >     return self.cursor.execute(sql, params)
> >   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
> >     return self.cursor.execute(query, args)
> >   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
> >     res = self._query(query)
> >   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
> >     db.query(q)
> >   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
> >     _mysql.connection.query(self, query)
> > django.db.utils.DataError: (1406, "Data too long for column 'role' at row 1")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## keycloak group mapping
> > ![image](https://user-images.githubusercontent.com/62125821/226444089-59faab05-1a34-4981-8e2c-310099713b49.png)
> > ## keycloak role mapping
> > ![image](https://user-images.githubusercontent.com/62125821/226444019-de62f536-c527-48fb-a47a-aa3833a37ca3.png)
> > Do you have any suggest for this problem?
> 
> @O-Jiangweidong

This error was caused by synchronizing unsupported parameters: group and role, which have their own meanings within JumpServer

**Comment by fsatrion** [comment]
> Try using only these few attribute mappings first: {"name": "name", "username": "preferred_username", "email": "email",}

Thank you for your response
if try this attribute working smootly but role and group not assign to user when successfuly authentication in jumpserver via OID.  The reason why add this attribute (  "groups": "groups", "role": "role") to assign role and group automaticaly when user in first time login. user stored in identity provider, no user in jumpserver before.

in this code https://github.com/jumpserver/jumpserver/blob/dev/apps/users/models/user.py#L671 , i found parameter groups and role in line 712-727 (CMIIW) and then i used "groups" and "role" for mapping with keycloak.

**Comment by BaiJiangJie** [comment]
Hi, @fsatrion Thank you very much for your recognition of JumpServer.

Synchronization of **roles** and **user groups** is currently not supported for **OpenID (Keycloak)**.

For **LDAP** authentication **only** synchronization of **user groups** is supported.

We will investigate and consider it later, but the cycle may be longer.

**Comment by Wapol4** [comment]
Thank you for your response @BaiJiangJie, 

I've created a group in openldap, I want to make sure if the group role is mapping between the user and the open ldap group, not mapping between openldap group and jumpserver group?

Here is a picture of what I have done so far:

Side OpenLDAP:

1. User and Group OpenLDAP
user: joko, group: L2

![image](https://user-images.githubusercontent.com/88999708/231678302-a69ef3f8-f1e7-4aaa-96b8-cc75a14f6364.png)

Side Jumpserver

1. Configuration Autth

![image](https://user-images.githubusercontent.com/88999708/231678526-a7dfc4bf-b9fb-4f7c-9e84-cdd94ba9b9c7.png)

2. Group Jumpserber : L2

![image](https://user-images.githubusercontent.com/88999708/231678865-69bcc531-4882-44e1-83b9-4ca5c515e38d.png)

3. Successful login, but the group did not follow

![image](https://user-images.githubusercontent.com/88999708/231679298-b79ed181-b611-413e-b656-6036f30f8ed3.png)

do you have documentation for this case? Thankyou

**Comment by BaiJiangJie** [comment]
You should view the synchronized `user group` information under the `Console` -  `Users` - `User group` .
