### ISSUE TITLE
[Feature] RDP客户端连接成功后，切换显示器，希望可以自适应分辨率

### ISSUE THREAD

**Issue by lyons-hz** [jumpserver/jumpserver#9778]
**请描述您的需求或者改进建议.**
RDP连接后，将窗口从小显示器挪到大显示器后分辨率不能自适应，直接使用mstsc连接是可以自适应显示器分辨率的。
![image](https://user-images.githubusercontent.com/89773363/221394376-5b1f476b-dd0b-4e82-88a5-6b8e2b0f0c43.png)

**Comment by ibuler** [comment]
如果锁定了分辨率那就是固定，如果是自动的，换屏幕应该会自适应分辨率

**Comment by ibuler** [comment]
还有问题。请重新打开
