### ISSUE TITLE
[Feature] 3.0之后没有之前的saml等单点登录功能。

### ISSUE THREAD

**Issue by HibikiLinux** [jumpserver/jumpserver#9779]
**请描述您的需求或者改进建议.**
之前2版本是有saml登录接入功能的。安装3.0之后没有了
![20230226195041](https://user-images.githubusercontent.com/28665234/221408762-73dd3a64-b549-4d10-82bb-ed88dda419fb.png)

**Comment by jym503558564** [comment]
内置到Xpack中了。

**Comment by KongNan** [comment]
开发方可能出于各种考虑对功能进行调整，但如果造成特定级别版本的功能缩减，还是该在更新中进行明确说明和提醒，避免影响用户使用、习惯或热情。

**Comment by everiori** [comment]
oidc也被放到Xpack里了？相当于功能减少？开源这么玩儿不太好吧。

**Comment by ibuler** [comment]
我们参考了常见开源产品企业版策略做的变更，为了弥补，我们向社区开放了 remote apps，支持了 web 资产

**Comment by ibuler** [comment]
> 开发方可能出于各种考虑对功能进行调整，但如果造成特定级别版本的功能缩减，还是该在更新中进行明确说明和提醒，避免影响用户使用、习惯或热情。

已经在整理了

**Comment by ibuler** [comment]
> oidc也被放到Xpack里了？相当于升级把原有功能给升没了？开源这么玩儿不太好吧。

见回复

**Comment by maninhill** [comment]
1. 我们遵循惯例，比如 Teleport 等产品也是采取类似的策略。
2. 我们也同样把一些原来 X-Pack 功能开放给社区，比如 Remote Apps。
3. v2.28 我们仍然会长期维护，如果这个功能特别重要，不建议升级。

感谢大家一直以来的支持。

**Comment by ibuler** [comment]
> 再出

升级上来的可以使用，新用户不再支持

**Comment by HuanMeng0** [comment]
> > 再出
> 
> 升级上来的可以使用，新用户不再支持

是否可以理解为“升级上来的可以在SAML证书有效期内继续使用”？
