### ISSUE TITLE
命令记录回放内容异常

### ISSUE THREAD

**Issue by mynicolas** [jumpserver/jumpserver#978]
[简述你的问题]

##### 使用版本
0.5.0-2

##### 问题复现步骤
命令记录回放，vim命令修改文件内容的记录是混乱的。

##### 具体表现[截图可能会更好些,最好能截全]

![image](https://user-images.githubusercontent.com/5128647/35547379-b140b420-05b3-11e8-90fa-0cced79ccba6.png)

**Comment by qiushaohu** [comment]
试试将浏览器窗口最大化播放

**Comment by hacker0001** [comment]
Request Method: | GET
-- | --
http://192.168.30.xx:8080/luna/replay/606ac62d-a448-4a95-8e1a-ae8a3c6a2cfd

报错是什么问题
