### ISSUE TITLE
[Bug] v3.0.0登录失败

### ISSUE THREAD

**Issue by Tiaonmmn** [jumpserver/jumpserver#9780]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer v3.0.0

**浏览器版本**
Microsoft Edge v107.0.1418.42

**Bug 描述**
用户登录资产失败，显示“登录提醒”提示框，无法取消。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/17075857/221455731-da000aeb-b098-48ab-96c4-34d5f3073459.png)

**Comment by BaiJiangJie** [comment]
打开浏览器-右击-检查，看一下控制台有没有报错信息

**Comment by Tiaonmmn** [comment]
无报错

**Comment by BaiJiangJie** [comment]
应该会有报错，先打开控制台，再刷新页面连接资产。

现在问题还会出现吗？

**Comment by omixwxm** [comment]
我遇到了相似的错误，重启服务、重新登录、刷新页面都无效，F12 查看到调用 `/api/v1/authentication/connection-token/` 接口时出现 500 异常。

**Comment by omixwxm** [comment]
我的问题解决了，是由于在 `控制台 -> 权限管理 -> 资产登录` 功能中录入的资产地址（IP/主机）中使用了带有 `-` 字符的域名（比如：`a-b-c.example.com`），删除掉就正常了
