### ISSUE TITLE
[Feature] v3.0缺少动态用户名登录功能

### ISSUE THREAD

**Issue by Tiaonmmn** [jumpserver/jumpserver#9781]
**请描述您的需求或者改进建议.**
v2版本中有根据JumpServer当前登录用户名登录资产的功能，v3.0版本取消了该功能。
可否考虑恢复该功能？该功能在多用户登录Windows资产时十分有用。

**Comment by ibuler** [comment]
授权时授权同名账号就可以了，只不过同名账号的自动推送还没完成

**Comment by Tiaonmmn** [comment]
这需要新建资产账号吧？v2版本中可以通过使用“动态用户名”功能，不需要新建资产账号即可登录。

**Comment by ibuler** [comment]
因为原来的动态系统用户，有自动推送的功能，v3 没来得及做，有点复杂，后面会补上的

**Comment by ylwind** [comment]
注意到目前同名账号貌似没有自动推送功能，目前使用同名账号登录依旧需要输入密码，是我的操作流程有问题吗？
![image](https://github.com/jumpserver/jumpserver/assets/56013580/42beb254-ece3-44e7-bc7e-53f0ae962bd9)

**Comment by wolfgang1219** [comment]
解决了吗
