### ISSUE TITLE
[Bug] Blank popup when connect to Web Platform v3.0.0

### ISSUE THREAD

**Issue by wonhee0410** [jumpserver/jumpserver#9782]
**JumpServer**
Version 3.0.0

**Browser version**
Chrome version 100.0.4896.127

**Bug**
Cannot connect to Web Platform, there is a blank popup.

**Bug**
1. On Console -> Asset -> Click on Asset Name
2. Add Account on Account List
3. Switch to Workbench -> My Assets -> Click Connect next to Web platform name
4. The error shows as below
![image](https://user-images.githubusercontent.com/60768442/221474418-6ed4a45e-174b-4cc2-9e29-4be844b803b8.png)

**Comment by ibuler** [comment]
We will fix this error next small version, today

**Comment by ibuler** [comment]
v3.0.1 released，try again

**Comment by wonhee0410** [comment]
> v3.0.1 released，try again

Hello, now it shows with this option, how can I connect ? It's grey out. Thank you.
![image](https://user-images.githubusercontent.com/60768442/221776317-3a5437dd-1a6a-45ba-9df4-8bd2d29e6265.png)

**Comment by ibuler** [comment]
Web connect depends on Windows Remote Apps，So you need setting up this follow the doc  https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/

**Comment by Yansre** [comment]
3.0.2版本依旧不行

**Comment by wonhee0410** [comment]
> Web connect depends on Windows Remote Apps，So you need setting up this follow the doc https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/

Thanks. I have downloaded the "JumpServer Client" but the button still grey out.

Did I do anything wrong ?

**Comment by wonhee0410** [comment]
> > Web connect depends on Windows Remote Apps，So you need setting up this follow the doc https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/
> 
> Thanks. I have downloaded the "JumpServer Client" on the laptop, but the button still grey out.
> 
> Did I do anything wrong ?

**Comment by LeeEirc** [comment]
> > Web connect depends on Windows Remote Apps，So you need setting up this follow the doc https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/
> 
> 
> 
> Thanks. I have downloaded the "JumpServer Client" on my laptop but the button still grey out.
> 
> 
> 
> Did I do anything wrong ?

You should add an applet-host which is a windows server on Settings-Remoteapp page, then click initial deploy button. It will deploy all applets on the applet-host.

**Comment by wonhee0410** [comment]
> > > Web connect depends on Windows Remote Apps，So you need setting up this follow the doc https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/
> > 
> > 
> > Thanks. I have downloaded the "JumpServer Client" on my laptop but the button still grey out.
> > Did I do anything wrong ?
> 
> You should add an applet-host which is a windows server on Settings-Remoteapp page, then click initial deploy button. It will deploy all applets on the applet-host.
I have installed a Windows Server, but when add Remote Host to Applets, it needs port 22, is it right ?
![image](https://user-images.githubusercontent.com/60768442/223642694-7fc328ba-c09c-4026-a481-b480e75d3364.png)

**Comment by LeeEirc** [comment]
Yes, you should install OpenSSH-Server on the Windows Server.  We use OpenSSH to connect the Window server and execute the deployment tasks.

**Comment by wonhee0410** [comment]
Hello all,
Where is this file ? I need to change the name of account.
Thank you.

![image](https://user-images.githubusercontent.com/60768442/226267854-0c5d7595-373b-4701-b405-125f6bbc61ac.png)

**Comment by LeeEirc** [comment]
The fields of the JSON data do not need to be adjusted, JumpServer will automatically replace this data for Web.  If you need to develop your own applet application, you can directly use the data in the account field.

**Comment by wonhee0410** [comment]
> The fields of the JSON data do not need to be adjusted, JumpServer will automatically replace this data for Web. If you need to develop your own applet application, you can directly use the data in the account field.

The problem is when I click Deploy to a Windows Server, it shows that **"No Account Available"**.
It's just received account **"Administrator"** for deployment.
How can I change this ? Thank you.

![image](https://user-images.githubusercontent.com/60768442/226501267-08944038-6a6e-4bcb-8ee7-524cdf194854.png)

**Comment by LeeEirc** [comment]
JumpServer use the privileged account to deploy. You should update the account to be a privileged account, as the `administrator` account below:

![image](https://user-images.githubusercontent.com/32626707/226519155-2cae293d-6655-4f16-811c-60f117c79829.png)
