### ISSUE TITLE
[Bug] 通过接口创建服务树节点，可能会重复

### ISSUE THREAD

**Issue by mosesyu95** [jumpserver/jumpserver#9789]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3

**浏览器版本**

**Bug 描述**
通过接口创建节点，可以创建重复节点。
/api/v1/assets/nodes/%s/children/

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/22955185/221487060-23d56478-dcd9-447c-8c11-02ae6a4abde5.png)

**Comment by mrsdpz** [comment]
update 似乎会检测同名,可以先创建一个随机的或者固定的临时名称,再 update

**Comment by BaiJiangJie** [comment]
嗯，v3.4 版本会校验一下，同级下不允许创建同名节点；更新默认会校验。
@mosesyu95 @mrsdpz
