### ISSUE TITLE
[Question] v2.28.7双机jumpserver使用同一个rds数据库这样可以吗？

### ISSUE THREAD

**Issue by opcache** [jumpserver/jumpserver#9792]
**请描述您的问题.**
[Question] v2.28.7双机jumpserver使用同一个rds数据库这样可以吗？
还需要同步这两文件夹那些文件？？
 /opt/jumpserver
 /data/jumpserver

**Comment by ibuler** [comment]
可以的，需要使用同一个 redis，这两个目录 nfs

**Comment by opcache** [comment]
> 可以的，需要使用同一个 redis，这两个目录 nfs

可以用同步的方式吗？应该也可以吧？

**Comment by ibuler** [comment]
可以

**Comment by opcache** [comment]
谢谢
