### ISSUE TITLE
[Bug] 历史会话无法基于HTTP协议过滤，远程应用协议类型都变成了RDP

### ISSUE THREAD

**Issue by weishuo6** [jumpserver/jumpserver#9793]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.0

**浏览器版本**
谷歌浏览器108.0.5359.99

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.录像审计选择http协议过滤发现无法识别远程应用
![image](https://user-images.githubusercontent.com/35896106/221508985-9c30726a-db47-4e16-a5de-bc1aaf4a263f.png)
2.远程应用协议类型都变成了RDP
![image](https://user-images.githubusercontent.com/35896106/221509191-414c3f9a-8984-4d77-9294-c78bd452fd1a.png)

**Comment by ibuler** [comment]
貌似确实有这个问题，应该填写 资产的协议，而不是连接的协议，已记录

**Comment by BaiJiangJie** [comment]
新版本已修复。
