### ISSUE TITLE
[Question] 3.0远程应用问题

### ISSUE THREAD

**Issue by zs19940216** [jumpserver/jumpserver#9800]
部署之后，无法登录website，提示下载rdp文件，这个应该怎么处理呢
![image](https://user-images.githubusercontent.com/45357822/221729760-5cfdacb2-9051-4d5a-af4c-a37adf64791c.png)

**Comment by LeeEirc** [comment]
查看下发布机是否正确部署成功，状态是否正常，并刷新下 luna 页面。
