### ISSUE TITLE
窗口的复制和重新连接没有了

### ISSUE THREAD

**Issue by harbour015** [jumpserver/jumpserver#9801]
![image](https://user-images.githubusercontent.com/48000268/221730383-eb95c7a5-bd15-4c7d-97c1-e6bcc46690d3.png)
只有关闭当前和关闭所有，能不能恢复之前的复制和重新连接

**Comment by ibuler** [comment]
下个版本恢复

**Comment by harbour015** [comment]
![image](https://user-images.githubusercontent.com/48000268/223938659-4600cea7-0523-4854-9898-af8ba0124034.png)
说好的下个版本恢复呢，跟着更新三个版本了，还没恢复。

**Comment by ibuler** [comment]
大版本，不是小版本，3.1 已经提测了

**Comment by BaiJiangJie** [comment]
试试最新版本。@harbour015 

<img width="481" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/c3f59651-0c04-44df-82be-2e1fcfe8fe99">
