### ISSUE TITLE
[Question] 3.0版本无法设置用户sftp根目录

### ISSUE THREAD

**Issue by PlaneV** [jumpserver/jumpserver#9802]
**各位好！我安装JumpServer 3.0之后，发现没有地方设置用户文件管理里面的根目录，所有用户都只能访问/tmp目录，如果我希望用户打开文件管理就是/home这个目录，请问我应该在怎么做？谢谢！**
版本：3.0 社区版
部署方式：官方文档快速部署脚本：`curl -sSL https://resource.fit2cloud.com/jumpserver/jumpserver/releases/latest/download/quick_start.sh | bash`
OS：CentOS 7.9

**Comment by wojiushixiaobai** [comment]
平台列表 详情 里面

**Comment by PlaneV** [comment]
根据您的回复已经成功解决问题，太感谢了！
