### ISSUE TITLE
无法使用api[Question] 

### ISSUE THREAD

**Issue by qicaihuoyan** [jumpserver/jumpserver#9803]
**请描述您的问题.**
最新版本,认证token后,在后台使用api老是失败,报错
TypeError: Failed to fetch
请问是什么原因

**Comment by wojiushixiaobai** [comment]
接口有变更，具体根据返回的 response 提示

**Comment by qicaihuoyan** [comment]
提示就是这个


Code | Details
-- | --
Undocumented | TypeError: Failed to fetch

再无其他提示...

**Comment by qicaihuoyan** [comment]
网上查让看nginx配置,但是我看nginx也不是别的端口就是默认的80

**Comment by qicaihuoyan** [comment]
日志显示
127.0.0.1 - - [28/Feb/2023:17:13:29 +0800] "GET / HTTP/1.1" 301 162 "-" "curl/7.74.0" "-"

**Comment by wojiushixiaobai** [comment]
具体哪个 api

**Comment by qicaihuoyan** [comment]
我实验了10多个都不行,anthorze我就是在web后台生成一个apikey后,在这里输入Token api密钥进行授权的

**Comment by qicaihuoyan** [comment]
考虑到2升级到3,我全新安装了一个3,用以下api也是无法使用
curl -X GET "http://172.16.194.248/api/v1/assets/assets/?name=10.77.1.102&address=10.77.1.102&platform=Linux" -H  "accept: application/json" -H 'Authorization: Token 38e6634d-865b-46bc-a4a9-0af4abdc3f60'

说认证令牌失效,,,可token是我在后台生成的
