### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Primeyang** [jumpserver/jumpserver#9806]
**JumpServer 版本( v3.0.1 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
异步加载资产树，资产列表不收缩，在之前老版本也出现过，后来修复，本次再次出现

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wojiushixiaobai** [comment]
默认不要展开是吗？

**Comment by Primeyang** [comment]
现在是默认直接展开了，刷新就展开，现在只能改成同步载资产树，这个资产树不会直接展开

**Comment by Primeyang** [comment]
![image](https://user-images.githubusercontent.com/17820033/223043787-a13c7502-2f0d-4a4c-a96f-65cc5964a18a.png)
设置成这个，整个资产树就全部展开了，收起来，刷新还是全部展开，只能设置成是，才能会收缩，这样的话，我在web终端页面输入搜索ip，就不知道是哪个节点下了

**Comment by BaiJiangJie** [comment]
好的，这个问题会在 v3.2 版本中进行修复。
