### ISSUE TITLE
[Bug] 3.0.1外部受限用户连接资产提示没有权限，用户管理中的角色列表不见了

### ISSUE THREAD

**Issue by reginofchaos** [jumpserver/jumpserver#9807]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.1

**浏览器版本**
Microsoft Edge
版本 110.0.1587.57 (正式版本) (64 位)

**Bug 描述**
升级3.0.1之后，角色为外部受限用连接资产提示没有权限，进入用户管理中发现角色列表不见了

**Bug 重现步骤(有截图更好)**
1.角色为外部受限用连接资产提示没有权限，之前版本外部受限用户连接已授权的资产正常
![image](https://user-images.githubusercontent.com/730904/221781726-b1ddf719-7c49-443f-b63f-22be5d32b273.png)

2.进入用户管理中发现角色列表不见了。
![image](https://user-images.githubusercontent.com/730904/221781410-c0f184c1-17e7-43db-bd6c-2b47beb7f1c2.png)

**Comment by wojiushixiaobai** [comment]
旧版本使用了自定义角色导致，需要将该用户角色改为默认的用户角色即可。

**Comment by reginofchaos** [comment]
新版本已经不提供角色管理功能了吗？

**Comment by wojiushixiaobai** [comment]
社区版本不提供，由企业版本提供。

**Comment by shawn996** [comment]
社区版不提供角色了也无所谓，但至少给个解决办法吧。
