### ISSUE TITLE
[Bug] V3.0*通过表格批量导入用户（含初始密码）后密码不匹配

### ISSUE THREAD

**Issue by pika-FENG** [jumpserver/jumpserver#9808]
![image](https://user-images.githubusercontent.com/91412927/221784726-fa3ae41c-e0c6-4a17-80cf-fb72c831a338.png)

使用该模式导入用户，导入的用户使用Admin@123初始密码无法登陆。

**Comment by wojiushixiaobai** [comment]
密码是否有效由 字段 *密码策略* 决定

**Comment by pika-FENG** [comment]
so~通过表格批量创建时，这个字段应该传什么？

**Comment by pika-FENG** [comment]
在api中找到了，感觉不是很友好。
{ "value": "custom", "label": "设置密码" }

**Comment by skinnyshy** [comment]
通过模板新建用户也是这个问题，请问是怎么解决的呢？
