### ISSUE TITLE
[Feature] v3.x 命令过滤建议

### ISSUE THREAD

**Issue by luweijun1992** [jumpserver/jumpserver#9809]
**请描述您的需求或者改进建议.**
建议：将命令过滤放在一条里面。
命令组那边做成列表形式
可以手动输入命令组内容或者选择已创建的命令组。
![f6d36e713317ed5ec0615260cbf6071](https://user-images.githubusercontent.com/58923704/221796416-ba6ac250-5351-4fef-9a9e-6b08a65da645.png)

当前需要创建至少2条来实现限制，比如需要一条规则是允许的，一条是拒绝来配合使用。

**Comment by luweijun1992** [comment]
补充：
针对列表中的行可以随意更换顺序，比如rule-id 2 换到rule-id 1，可以做成拖拉；
或者rule-id选择，比如将rule-id 2选择为1，原rule-id 2变为1，原rule-id 1往后排。

**Comment by wojiushixiaobai** [comment]
命令组输入框可以添加多个命令组

**Comment by luweijun1992** [comment]
> 命令组输入框可以添加多个命令组

可以选择多个是没错。
我的意思可以在一条命令过滤规则中将拒绝和允许搞定，无需创建两条规则。（比如我当前需要设置一个允许执行查看和ping命令，还得创建一条拒绝剩下所有命令.*）
且我描述的rule-id 对应当前优先级，也就是约往前的id优先级越高。

**Comment by ibuler** [comment]
这不就是原来的命令过滤器吗，一些用户反馈和常见 ACL 不像，就做了更改

**Comment by luweijun1992** [comment]
> 这不就是原来的命令过滤器吗，一些用户反馈和常见 ACL 不像，就做了更改

比如当前我的做法。针对网络设备，要设置一个只读用户，只能允许执行几条查看命令，其他都不允许。
我需要创建2条“命令过滤”规则配合才能满足需求。
规则1：优先级50；命令组（dis.*|ping.*|quit|q.*）；动作 接受；
规则2：优先级100；命令组（.*）；动作 拒绝；
（且还需要编辑规则才能看到具体动作是什么）
![image](https://user-images.githubusercontent.com/58923704/222023844-42969648-6ea3-405d-91b0-ecdb1898d9e8.png)
![image](https://user-images.githubusercontent.com/58923704/222023957-1d2ac122-74cd-4c53-be23-411efa65e475.png)

**Comment by BaiJiangJie** [comment]
### 对于 **动作** 是放在 **命令组** 中 还是 **命令过滤规则**中，是两个角度的问题，每一种方案都有一些场景不能满足。

比如，

1. 第一种放到**命令过滤规则**（也是 <= v2.28 版本中的方式），你的场景用一条规则就满足不了。

2. 第二种放到**命令组**中，那么用户想配置多个命令组的拒绝，就需要每一个命令组中选择“拒绝”，那如果动作是复核的情况（企业版功能），那用户就需要在每一个**命令组**中来配置复核人，显然这样也是很繁琐的。

_所以，在 v3 版本中，我们将**命令过滤**功能和**资产登录**（企业版功能）功能的配置方式进行了统一，都采用现在的策略。_

对于优先级的问题，当然也是在**命令过滤规则**中指定会更好。



### 对于**命令过滤规则**详情页面信息缺少的问题，我们会在 v3.2 版本中展示出来。
