### ISSUE TITLE
linux命令行下,命令是可以记录和实时监控的.

### ISSUE THREAD

**Issue by skyrim61** [jumpserver/jumpserver#981]
[简述你的问题]
我使用的jumpserver版本是0.3.2

问题:
linux命令行下,是可以记录和实时监控用户使用的命令的
在mysql > 命令行下无法记录mysql命令

这是没有设计监控mysql命令行,还是bug?
后续可以监控吗?

**Comment by liuzheng** [comment]
没设计，后期会完善
