### ISSUE TITLE
[Bug] 秘钥升级失效

### ISSUE THREAD

**Issue by JeongHyeokLee** [jumpserver/jumpserver#9815]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V2.28.7 升级 V3.0.2
**浏览器版本**
版本 110.0.1587.57 (正式版本) (64 位)
**Bug 描述**
V2.28.7 升级 V3.0.2之后原来V2.28.7配置的密钥（密钥加密了）验证模式到V3.0.2之后全部变成密码验证了，密码是密钥的教秘密码，从而导致ssh链接从密钥验证变成密码验证，导致ssh链接失败！

**Bug 重现步骤(有截图更好)**
 V3.0.2升级之后导出的数据截图如下
升级到导致所有的验证类型变成密码验证
![image](https://user-images.githubusercontent.com/70053869/221898515-658c14ac-7be2-4262-9e5a-af52db0031f0.png)
这个是我测试时候新添加的
![image](https://user-images.githubusercontent.com/70053869/221898809-7c43f1ff-15f5-4789-b43d-528e9c9e19ec.png)

**Comment by ibuler** [comment]
我们验证一下，如果核实，今天修复

**Comment by ibuler** [comment]
刚才测试了一下迁移后是没问题的

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/apps/assets/migrations/0100_auto_20220711_1413.py#L60

如果原来是 ssh key，迁移后名称后缀有 (ssh key)

**Comment by JeongHyeokLee** [comment]
V3.0.3升级还是这个样子 只能停留在V2的最后一个版本

**Comment by ibuler** [comment]
可以导出一些数据给我们测试吗

**Comment by ibuler** [comment]
可以脱敏给我们一些测试数据吗，比如 ip 写乱 key 新生成

**Comment by BaiJiangJie** [comment]
v3.1.0+ 已经修复了，升级到最新版本使用，如果还有问题再打开 Issue。
