### ISSUE TITLE
[Bug] v2升级v3后windows 2012普通用户无法登录且只能创建2个远程会话

### ISSUE THREAD

**Issue by dowliu** [jumpserver/jumpserver#9817]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.0（从v2.28.7升级）

**浏览器版本**
Microsoft Edge Version 110.0.1587.57 (Official build) (64-bit)

**Bug 描述**
1. Windows 2012系统中的普通用户（加入Users和Remote Desktop Users组）无法登录，提示“拒绝请求的会话访问”，如果加入Administrators组可以正常登录，但是存在下面的第2点问题；
2. 拥有RDS功能的Windows 2012系统，只允许2个远程会话，组策略里面设置的远程会话限制是10个。

上述两个问题在原来v2版本使用正常，是升级到v3之后出现的。根据文档，将平台列表 - rdp协议里面的安全设置为“NLA”仍然无法解决。

现在同时存在v2.28.7和v3.0.0的两套堡垒机，配置了同一台Windows 2012服务器、同样的账号和授权。v2版本的堡垒机所有账号可以正常连上该服务器，且支持2个以上的远程会话。而v3版本的堡垒机只有加入了administrators的账号可以还登录，但只能同时创建2个会话。

![QQ图片20230301100830](https://user-images.githubusercontent.com/59379000/222026734-5a7f96b2-637d-49b9-a5bc-e38313944052.png)
![Snipaste_2023-03-01_10-09-10](https://user-images.githubusercontent.com/59379000/222026739-4901d52c-1e72-479b-a090-aeffbec9ab39.png)
![Snipaste_2023-03-01_10-10-40](https://user-images.githubusercontent.com/59379000/222026741-5cc45845-17f6-45fa-89df-1764fc5bb127.png)

**Comment by ibuler** [comment]
Windows 限制，去微软家购买 License

**Comment by dowliu** [comment]
> Windows 限制，去微软家购买 License

本次反馈的问题是两个，1. 普通用户无法登录的问题和微软的License无关吧？
2. 关于多会话的问题。操作系统已经配置了rds授权，在v2上面可以正常使用多会话，v3不行。这个应该和微软的rds授权没关系吧？现在我两个版本的jumpserver同时连同一台资产，出现了上述不一样的结果，问题应该不在资产本身。

**Comment by dowliu** [comment]
为了确认一下是否是因为从v2升级上来导致的不兼容，刚刚又全新部署了一套v3，问题仍然存在。

**Comment by ibuler** [comment]
1. 检查一下登录时的账号密码是否正确，管理员和普通用户登录没有什么区别
2. 连接方式 v2, v3 没做变更


@wojiushixiaobai 帮看看呗

**Comment by dowliu** [comment]
账号密码没问题，加入administrators组就能连上。
v2能连，v3连不了。昨天小白老师也一起排查了，未曾找到原因。

**Comment by dowliu** [comment]
![1](https://user-images.githubusercontent.com/59379000/222041957-a5d9fa06-b5c1-4479-87c0-3dacbca1e15d.png)
RDS授权检测也是正常的。v3应该是在v2的基础上改了什么代码。

**Comment by Pu-pupu** [comment]
相同的问题，Windows 2012，提示拒绝请求的会话访问。

**Comment by sanpichen** [comment]
windows server 2016 std  相同的问题。
V2没有使用没有问题。
V3administrator 最多可以开两个窗 普通用户“拒绝请求的会话访问”
以下是系统日志错误：
日志名称:          System
来源:            Microsoft-Windows-DistributedCOM
日期:            2023/3/2 15:41:36
事件 ID:         10016
任务类别:          无
级别:            错误
关键字:           经典
用户:            SYSTEM
计算机:           TBSERA-xxxxx
描述:
应用程序-特定 权限设置并未向在应用程序容器 不可用 SID (不可用)中运行的地址 LocalHost (使用 LRPC) 中的用户 NT AUTHORITY\SYSTEM SID (S-1-5-18)授予针对 CLSID 为 
{8D8F4F83-3594-4F07-8369-FC3C3CAE4919}
、APPID 为 
{F72671A9-012C-4725-9D2F-2A4D32D65169}
 的 COM 服务器应用程序的 本地 激活 权限。此安全权限可以使用组件服务管理工具进行修改。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-02T07:41:36.703848000Z" />
    <EventRecordID>63540</EventRecordID>
    <Correlation />
    <Execution ProcessID="548" ThreadID="16000" />
    <Channel>System</Channel>
    <Computer>TBSERA-613200</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="param1">应用程序-特定</Data>
    <Data Name="param2">本地</Data>
    <Data Name="param3">激活</Data>
    <Data Name="param4">{8D8F4F83-3594-4F07-8369-FC3C3CAE4919}</Data>
    <Data Name="param5">{F72671A9-012C-4725-9D2F-2A4D32D65169}</Data>
    <Data Name="param6">NT AUTHORITY</Data>
    <Data Name="param7">SYSTEM</Data>
    <Data Name="param8">S-1-5-18</Data>
    <Data Name="param9">LocalHost (使用 LRPC)</Data>
    <Data Name="param10">不可用</Data>
    <Data Name="param11">不可用</Data>
  </EventData>
</Event>

**Comment by wojiushixiaobai** [comment]
平台列表新建一个windows 平台，保存后点击刚才创建的 windows 平台进入详情页面，然后在右下角点击 3389 右侧的齿轮按钮，把 console 关闭。
![image](https://user-images.githubusercontent.com/24326988/222368217-bc9847d9-7b58-4048-8803-87764aba8271.png)
![image](https://user-images.githubusercontent.com/24326988/222368269-81ab4f9d-dd8c-4fb8-a7d7-296edce6faf6.png)

**Comment by dowliu** [comment]
> 平台列表新建一个windows 平台，保存后点击刚才创建的 windows 平台进入详情页面，然后在右下角点击 3389 右侧的齿轮按钮，把 console 关闭。 ![image](https://user-images.githubusercontent.com/24326988/222368217-bc9847d9-7b58-4048-8803-87764aba8271.png) ![image](https://user-images.githubusercontent.com/24326988/222368269-81ab4f9d-dd8c-4fb8-a7d7-296edce6faf6.png)

这个配置修改，对以上两个问题都没帮助。在Windows Server 2012上，普通用户还是无法登录，会话也只能同时登录两个。

**Comment by ibuler** [comment]
目前我们还没能复现，等待更多用户遇到此问题，我们再想想办法

**Comment by sanpichen** [comment]
> 平台列表新建一个windows 平台，保存后点击刚才创建的 windows 平台进入详情页面，然后在右下角点击 3389 右侧的齿轮按钮，把 console 关闭。 ![image](https://user-images.githubusercontent.com/24326988/222368217-bc9847d9-7b58-4048-8803-87764aba8271.png) ![image](https://user-images.githubusercontent.com/24326988/222368269-81ab4f9d-dd8c-4fb8-a7d7-296edce6faf6.png)



> > 平台列表新建一个windows 平台，保存后点击刚才创建的 windows 平台进入详情页面，然后在右下角点击 3389 右侧的齿轮按钮，把 console 关闭。 ![image](https://user-images.githubusercontent.com/24326988/222368217-bc9847d9-7b58-4048-8803-87764aba8271.png) ![image](https://user-images.githubusercontent.com/24326988/222368269-81ab4f9d-dd8c-4fb8-a7d7-296edce6faf6.png)
> 
> 这个配置修改，对以上两个问题都没帮助。在Windows Server 2012上，普通用户还是无法登录，会话也只能同时登录两个。


修改取消console是可行的。但是如何批量修改？系统默认的windows平台是不能修改的，新增再重新配置平台似乎数量太多了.

**Comment by ibuler** [comment]
@dowliu 3.1 版本 默认不开启 console

**Comment by dowliu** [comment]
升级到3.10之后，去掉console选项，可以正常连接windows资产了。
