### ISSUE TITLE
用户权限归属错误

### ISSUE THREAD

**Issue by sz233** [jumpserver/jumpserver#982]
[简述你的问题]

授权后的用户，家目录所属用户和所属组显示为uid和gid

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

0.5.0

##### 问题复现步骤
1、web为用户授权服务器，用户为系统用户，已加入服务器集群，并写了资产授权规则
2、使用coco连接服务器，报权限不足的错误，登录服务器看到此用户的家目录所属用户和所属组都是id。
##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/30258956/35611894-961ad7c2-06a1-11e8-922b-07d8680064bd.png)
![image](https://user-images.githubusercontent.com/30258956/35611828-5230c940-06a1-11e8-99c4-13816b2a49cc.png)

##### 其他
用户推送没有报错。

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
可能是之前拥有这个家目录，删除用户的时候名义清理家目录导致的
