### ISSUE TITLE
[Bug] 应用授权上传下载无法控制

### ISSUE THREAD

**Issue by limin-fit2** [jumpserver/jumpserver#9820]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
       Version v2.28.5

**浏览器版本**
版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
发布应用授权规则，去掉文件上传下载、粘贴复制权限，实际上文件管理功能权限未受到控制

**Bug 重现步骤(有截图更好)**
1.创建应用授权规则，去掉文件上传下载权限
2.打开plsql应用，右侧设置“文件管理”未被屏蔽，仍然能上传文件
3.查询数据集，将查询结果导出，能直接下载到本地
![image](https://user-images.githubusercontent.com/61964761/222030646-5b5427cf-8f94-4968-8dfb-875d1c079956.png)
![image](https://user-images.githubusercontent.com/61964761/222032998-169460a1-494e-4534-8924-6bc6d8e8d9d6.png)
![image](https://user-images.githubusercontent.com/61964761/222032437-39c9e26c-4b95-4d15-8c37-89ccc6f73a78.png)

**Comment by LeeEirc** [comment]
是不是有多个授权。另外是否配置了 remoteapp 的全局上传下载？

**Comment by LeeEirc** [comment]
开启全局就不走授权。另外授权的上传下载和全局的上传下载是一样的逻辑。没理解下载文件无法保存到下载至本地。

**Comment by limin-fit2** [comment]
下载至本地指的是我需要导出的文件没办法从远程服务器拷贝至我的本地电脑上；
如果不开启全局，操作软件的导出数据功能，无法将导出文件保存在gua中，导出的数据依旧存在应用发布机这台服务器上，无法下载至我本地电脑上

**Comment by LeeEirc** [comment]
> 下载至本地指的是我需要导出的文件没办法从远程服务器拷贝至我的本地电脑上； 如果不开启全局，操作软件的导出数据功能，无法将导出文件保存在gua中，导出的数据依旧存在应用发布机这台服务器上，无法下载至我本地电脑上

我的意思是，开启全局的上传下载权限，和授权应用的上传下载，理论上代码是一样的。不应该存在这个问题。
