### ISSUE TITLE
[Bug] luna自动死循环刷新

### ISSUE THREAD

**Issue by Art-Man** [jumpserver/jumpserver#9823]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.7

**浏览器版本**
chrome

**Bug 描述**
luna页面自动死循环刷新；

**Bug 重现步骤(有截图更好)**

偶发性的，但频率又点高，已经出现过几次了；
目前不清楚是什么原因产生的；
界面刷新页不行；

**Comment by Leif160519** [comment]
这个我也遇到过，可能是登录会话过期了，需要重新登录，重新开一个jumpserver网页看是不是要登录

**Comment by updogliu** [comment]
我也遇到过一次，是会话过期。希望能改善这里，会话过期时提示过期，而不是页面闪啊闪的一致刷。

**Comment by BaiJiangJie** [comment]
好的，我们复现一下。

**Comment by BaiJiangJie** [comment]
v3 版本已经解决。
