### ISSUE TITLE
RetomeApp  FAILED! => {"changed": true, "cmd": "tinkerd install --name chrome"

### ISSUE THREAD

**Issue by haitang5445** [jumpserver/jumpserver#9826]
**请描述您的问题.**
version v3.0.1~3.0.2

添加远程应用发布机后，部署Chrome Browser，出现err (RDS Open-SSH 已经装了，用户也是特权用户)
![image](https://user-images.githubusercontent.com/59681546/222081219-73483622-3136-4109-a314-78a83fd00d3b.png)

![image](https://user-images.githubusercontent.com/59681546/222080895-b4ec8f47-abb4-4f1a-ba10-528b0e8c4375.png)

**Comment by LeeEirc** [comment]
需要先初始化部署

**Comment by haitang5445** [comment]
已解决上面的问题。

**Comment by eXerc1st** [comment]
How do you initialize a deployment?
