### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thor8848** [jumpserver/jumpserver#9828]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**
Safari浏览器
版本15.4 (17613.1.17.1.6)

**Bug 描述**
Mac下safari兼容问题。
新建的jumpserver, 资产管理直接一片空白，换chrome就好使，找半天按钮。。。

**Bug 重现步骤(有截图更好)**
1.
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/67045073/222091323-65587a87-fe77-4a1b-804f-048cc9e18290.png">

2.
3.

**Comment by wojiushixiaobai** [comment]
清理下浏览器缓存应该就行。

**Comment by thor8848** [comment]
我草  我傻逼了
