### ISSUE TITLE
[Bug] v2 升级 v3 后 web 端登录资产耗时长

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9832]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

 v3.0.0
**浏览器版本**

**Bug 描述**
web 端选择资产及账号后,观察接口已返回,耗时短, 但web 端 loading转圈圈未进行连接,往往等待六七秒,页面开始显示 ssh 连接详情,耗时零点几秒连接成功, ssh 登录未出现该情况,是否是 luna 的 bug?

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wojiushixiaobai** [comment]
资产很多吗？

**Comment by mrsdpz** [comment]
六千台左右

**Comment by wojiushixiaobai** [comment]
授权数量超过 1w 条了吗？如果方便的话还请告知下大致的资产数量，用户数量，授权数量，我们本地复现下。

按照我们之前的测试结果，授权数量超过 1w 后，响应会变慢属于正常现象。但是我不确定 6-7s 是否属于正常范围，因为这个还跟硬件有关。

**Comment by mrsdpz** [comment]
资产:6761
账号数量:17756
资产授权:798
选中账号点击登录  /api/v1/terminal/endpoints/smart/?protocol=ssh&token= 这个接口很快返回了
页面上的圈圈会转一会,今天看大概会转个三四秒,没有上周那么夸张

**Comment by mrsdpz** [comment]
部署jumpserver 的机器和 mysql 性能负载很低

**Comment by ibuler** [comment]
可以打开浏览器的开发者模式，去看看哪些 api 速度慢了

**Comment by mrsdpz** [comment]
> 可以打开浏览器的开发者模式，去看看哪些 api 速度慢了

![image](https://user-images.githubusercontent.com/31802195/223661349-f63e9457-7b4e-4434-948a-ddec81915323.png)
这些静态文件每次都要去请求, 这些应该一开始请求一次就行了吧?每次都请求就会在这里停顿

**Comment by LeeEirc** [comment]
已经完善 koko 静态资源的缓存，等下个 v3.1 版本更新。
