### ISSUE TITLE
[Question] 双机部署v2.28.7第二台jms_core 无法启动

### ISSUE THREAD

**Issue by opcache** [jumpserver/jumpserver#9837]
**请描述您的问题.**
双机部署v2.28.7，两台连接同一个MYSQL和redis, 第二台jms_core 无法启动，要怎么处理??
[
![aa20230301220127](https://user-images.githubusercontent.com/39149378/222162543-bfd20d3f-10dc-4190-96ec-794067da334c.jpg)
](url)

**Comment by opcache** [comment]
看了下文档，是要加这个配置吗？
···
# KoKo Lion 配置
SHARE_ROOM_TYPE=redis                                            # KoKo Lion 使用 redis 共享
REUSE_CONNECTION=False                                           # Koko 禁用连接复用
···

**Comment by opcache** [comment]
两台jumpserver连接同一个MYSQL和redis,似乎不行，改用其他方式可以正常启动

**Comment by wojiushixiaobai** [comment]
不能启动的 jumpserver core 日志报什么错

**Comment by BaiJiangJie** [comment]
docker logs -f jms_core --tail 10

理论上是可以的，看看 core 的启动日志报什么错？

**Comment by BaiJiangJie** [comment]
如果还有问题，再打开 issue。
