### ISSUE TITLE
[Question] jumpserver web登入的ip显示192.168.250.1 

### ISSUE THREAD

**Issue by redgeek01** [jumpserver/jumpserver#9838]
jumpserver web登入的ip显示192.168.250.1 
登入城市     局域网(192.168.250.1)
页面提示     连接 websocket 失败

**Comment by redgeek01** [comment]
登入城市  局域网(192.168.250.1)

**Comment by ibuler** [comment]
1. 有可能是防火墙问题
2. 如果有多层Nginx，有的 配置没有 Upgrade

**Comment by ibuler** [comment]
有问题重新打开
