### ISSUE TITLE
[Bug] ldap登录异常

### ISSUE THREAD

**Issue by qianyu-0712** [jumpserver/jumpserver#9839]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.2

**浏览器版本**
版本 110.0.1587.57 (正式版本) (64 位)

**Bug 描述**
使用ldap进行登录时，用户登录提示：Server error occur, contact administrator
日志提示：django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxx' for key 'email'")
但是并没有重复的邮箱输入，因为jumpserver是全新重建，不是升级过来的。ldap也只进行了一次的导入

**Bug 重现步骤(有截图更好)**
1.配置ldap登录
2.进行web登录ldap账号
3.跳转至错误页面
![2f71d32f8ac0aea014e423a5a9b5d41](https://user-images.githubusercontent.com/63082453/222307146-aa9a6649-f6e8-402c-b6d4-cfd81b6c3db7.png)
![efef071c0ad78552f3fa6bd30498813](https://user-images.githubusercontent.com/63082453/222307174-4542daed-a41b-4f62-9539-eaf27c97b58b.png)
![b4edd1757a8c0622c58f96150cf700c](https://user-images.githubusercontent.com/63082453/222307199-0ffbed4f-b65c-4ad4-aba9-8c9d5747680f.png)

**Comment by ibuler** [comment]
目前用户列表中没有这个邮箱的吗

**Comment by qianyu-0712** [comment]
确认是没有重复邮箱的
![image](https://user-images.githubusercontent.com/63082453/222311179-94db4785-4cff-4574-a60a-b544f51285d8.png)

**Comment by BaiJiangJie** [comment]
可能是因为导入到了全局组织下，查询数据库 users_user 表数据应该是存在的。

**Comment by qianyu-0712** [comment]
请问该如何处理

**Comment by BaiJiangJie** [comment]
方便远程看一下吗？@qianyu-0712

**Comment by qianyu-0712** [comment]
2435550795我们加一下qq进行链路

**Comment by ibuler** [comment]
做了一些优化，如果 email 存在登录会有提示

**Comment by ibuler** [comment]
如果还有问题再打开
