### ISSUE TITLE
[Bug] 邮件配置异常

### ISSUE THREAD

**Issue by hzhfit2cloud** [jumpserver/jumpserver#9840]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.2

**浏览器版本**
chrome

**Bug 描述**
沿用相同的邮箱配置 V2 连接正常，V3.0.2 报错：
unsupported operand type(s) for +: 'NoneType' and 'str'

**Bug 重现步骤(有截图更好)**
1.系统管理邮件配置
2.填写在 V2 正常连接的邮箱服务配置
3.在 V3.0.2 中报错

<img width="575" alt="image" src="https://user-images.githubusercontent.com/89765365/222325212-1bbd0548-3d2a-44ad-8ad8-bc6c443b53b0.png">

**Comment by wojiushixiaobai** [comment]
自定义过邮件模板还是 smtp 配置不对，截图看看

**Comment by hzhfit2cloud** [comment]
没有自定义邮件模板
页面报错如下：
![image](https://user-images.githubusercontent.com/89765365/222998215-2b4685ec-a77f-4477-aa41-b01139c97b4d.png)

**Comment by wojiushixiaobai** [comment]
点击 邮件服务器 后面的 设置 按钮截图
点击 创建用户内容 后面的 设置 按钮截图

**Comment by hzhfit2cloud** [comment]
![image](https://user-images.githubusercontent.com/89765365/223933694-0048c3ce-d301-4ad7-b292-366715f742b1.png)
![image](https://user-images.githubusercontent.com/89765365/223933678-c93cbb7e-2c23-4d2b-a531-38f4d45c1d13.png)

**Comment by O-Jiangweidong** [comment]
新版本解决了此问题，如果未升级的话，可以将邮件配置中的必填项都添加之后点击提交后再测试即可

**Comment by BaiJiangJie** [comment]
建议升级解决。
