### ISSUE TITLE
web终端连接mysql资产

### ISSUE THREAD

**Issue by gxy-13** [jumpserver/jumpserver#9841]
使用web终端连接mysql资产，显示
Receive Connection closed 
Connection websocket closed 

mysql资产在资产管理测试连接是可连接
![a2ce41586c816ed0193c18c1fea55f82](https://user-images.githubusercontent.com/83151481/222326712-bccfd722-00a1-4437-8c3a-8fb1135ba60f.jpg)

**Comment by LeeEirc** [comment]
看下 koko 的日志 docker logs -f jms_koko

**Comment by gxy-13** [comment]
![f54a74335e5493fb10cfd8e811c1a842](https://user-images.githubusercontent.com/83151481/222363429-d4c08e39-c1b6-47c6-9e08-4fb34a73fd3d.jpg)

**Comment by gxy-13** [comment]
已解决，mysql路由的问题

**Comment by hkhking** [comment]
你好我也遇见同样问题了 请问怎么解决的?thx
