### ISSUE TITLE
[Question] token生成问题

### ISSUE THREAD

**Issue by qicaihuoyan** [jumpserver/jumpserver#9849]
我用api生成token报错
curl -X POST http:/***/api/v1/authentication/auth/  -H 'Content-Type: application/json' -d '{"username": "admin", "password": "ZrF0TPQJy1<-,(>_o&[T"}'
报错
<html>
<head><title>307 Temporary Redirect</title></head>
<body>
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
请问是什么问题?还有api/docs页面的authorize里面的token是用上面的api生成吗?
昨天我关闭了一个api的问题,,因为昨天我调试成功了,但是今天在用api又失败了

**Comment by wojiushixiaobai** [comment]
你可以测试下 demo.jumpserver.org 对比下

**Comment by BaiJiangJie** [comment]
调用这个 `/api/v1/authentication/tokens/` 生成认证 token。
