### ISSUE TITLE
创建系统用户 自动推送报错

### ISSUE THREAD

**Issue by vlingfu** [jumpserver/jumpserver#985]
[简述你的问题]
创建系统用户，自动推送报错

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/35830275/35613957-6d17eb38-06a8-11e8-8169-a953c0f33547.png)

2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
系统用户只有密码是吗？

**Comment by vlingfu** [comment]
刚才看了下，我推送之后 感觉没有反应，看见了日志中的报错。刚才查看的时候发现，账号创建了，但是仅仅创建了账号，没有密码。没有ssh目录，没有key

**Comment by vlingfu** [comment]
推送之后，看到了报错，当时id了一下账号，发现是没有的。账号生成也存在延迟

**Comment by ibuler** [comment]
fixed
