### ISSUE TITLE
[Bug] 升级之后切换用户登录失败。

### ISSUE THREAD

**Issue by yunyouu** [jumpserver/jumpserver#9850]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.0

**浏览器版本**
mac m1 chrome111.0.5563.50

**Bug 描述**
资产添加了两个账号：
1. admin 普通用户，密钥登录。测试连接成功。
2. root 用户，使用密码，禁止 ssh 登录。设置切换自 admin 用户，测试连接失败。
两个账号在服务器上测试都是正常的，密码以及密钥都没问题

root 账号连接提示以下问题
<img width="601" alt="image" src="https://user-images.githubusercontent.com/32095100/222402806-4c46071e-e523-4f28-8c0e-da9931b98214.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/32095100/222403054-616026ad-c794-41ea-a47f-4465fbb3e01e.png">

**Comment by yunyouu** [comment]
> 对于 root 用户，日志显示只允许 publickey, gssapi-keyex, gssapi-with-mic 几种方式的认证，你配置的是密码，所以测试失败了。

root 用户配置的密钥登录，切换的账号是密码登录。另外这个问题在升级 v3.1.0 之后解决了可以登录，但是还是不可以测试连接。

**Comment by BaiJiangJie** [comment]
在 JumpServer 中单独测试 root用户（密钥认证）和 admin 用户（密码认证）的可连接性都会成功吗？

**Comment by davie89** [comment]
这个问题在， v3.1.1的版本还没解决。也不知道什么时候能解决

**Comment by davie89** [comment]
目前设备通过加固root无法登录，如果不能切换账号很影响使用，希望官方能尽快解决

**Comment by davie89** [comment]
开始连接到 root@172.24.21.21  3.1
开始连接到 root@172.24.21.21 error: EOF
Receive Connection closed
Connection websocket closed

**Comment by LeeEirc** [comment]
看下 koko 的日志，linux 服务是不是切换失败了？ 截图看下 `su - root` ，是否代填和匹配出现错误

**Comment by yunyouu** [comment]
> 看下 koko 的日志，linux 服务是不是切换失败了？ 截图看下 `su - root` ，是否代填和匹配出现错误

<img width="833" alt="image" src="https://user-images.githubusercontent.com/32095100/229403293-5a26cf06-cacd-4983-b228-2435ec92cc0e.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/32095100/229403390-e98ccfc6-34a2-49a2-9d37-d72b6cb56bbe.png">
账号配置了切换，但是看日志好像是直接登录了，没有切换。

**Comment by LeeEirc** [comment]
资产是什么系统？使用 admin 直接登录资产，手动 su - root 看看？

**Comment by yunyouu** [comment]
升级到 v3.1.2 解决当前问题，关闭了。感谢各位 🙏
