### ISSUE TITLE
[Bug] 密钥登陆资产失败

### ISSUE THREAD

**Issue by zeng202211** [jumpserver/jumpserver#9852]
**JumpServer 版本 v3.0.3 ** 

**浏览器版本**
Chromium 110

**Bug 描述**
密钥登陆Linux资产失败，测试资产链接出现下图错误，链接资产失败
![image](https://user-images.githubusercontent.com/126559759/222460703-59b86953-0001-4b33-9491-31c5aa8ab75f.png)

**Linux密钥**
![image](https://user-images.githubusercontent.com/126559759/222461848-5819bbbe-853e-4703-b401-78979b864f41.png)

**Comment by LeeEirc** [comment]
建议使用 `ssh-keygen -t rsa -f ./id_rsa `  命令创建私钥

**Comment by zeng202211** [comment]
好的，谢谢
