### ISSUE TITLE
Nginx如何通过二级目录代理Jumpserver

### ISSUE THREAD

**Issue by Conficker-zy** [jumpserver/jumpserver#9854]
根据官方文档建议：https://github.com/jumpserver/docs/pull/213/files，配置了nginx反代至v3.0.2版本。对此配置做了如下修改：
```
        location /jms {
            # 将 proxy_pass 替换成对应服务地址即可
            proxy_pass http://192.168.15.20;
            proxy_set_header Accept-Encoding "";
            rewrite "/jms/(.*)$" /$1 break;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect ~^/(.*) http://$http_host/jms/$1;
            sub_filter_types *;
            sub_filter_once off;
            sub_filter '/static/' '/jms/static/';
            sub_filter '/ui/' '/jms/';
            sub_filter '/api/' '/jms/api/';
            sub_filter '/core/' '/jms/core/';
            sub_filter '/ws/notifications/' '/jms/ws/notifications/';
            sub_filter '/luna/' '/jms/luna/';
            sub_filter '/koko/' '/jms/koko/';
            sub_filter '/lion' '/jms/lion/';
            sub_filter '/media/' '/jms/media/';
            sub_filter '/omnidb/' '/jms/omnidb/';
            sub_filter '/player/' '/jms/player';
            sub_filter '/theme/' '/jms/theme/';
            sub_filter '/ui/assets/' '/jms/ui/assets/';
        }
```
测试过程中又遇到如下问题：
1、第一次登陆时出现404：
![404](https://user-images.githubusercontent.com/74549798/222648691-822727f7-7111-43b5-b14b-d6c0b2e89d16.png)
点击去往首页后，回到主页面
2、通过web cli远程服务器时，远程界面出现404，具体返回如下：
![image](https://user-images.githubusercontent.com/74549798/222649354-2e3e54d1-a253-4706-90fb-1c18bf3f0c39.png)
此时浏览器URL是http://192.168.15.21/jms/luna/?_=1677825356663
404的消息头内容如下：
![image](https://user-images.githubusercontent.com/74549798/222649520-364cc27e-c36a-47d1-924e-df1bf3300ec1.png)

有没有大佬能够指导一下如何通过nginx配置二级目录访问Jumpserver

**Comment by ibuler** [comment]
目前官方不支持二级目录

**Comment by Venurs** [comment]
`      location /jms {
          proxy_pass http://10.64.34.5:4325;
          proxy_set_header Accept-Encoding "default";
          rewrite "/jms/(.*)$" /$1 break;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_request_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_redirect ~^/(.*) http://$http_host/jms/$1;
          sub_filter_types *;
          sub_filter_once off;
          sub_filter '/static/' '/jms/static/';
          sub_filter '/ui/' '/jms/ui/';
          sub_filter '/api/' '/jms/api/';
          sub_filter '/core/' '/jms/core/';
          sub_filter '/ws/notifications/' '/jms/ws/notifications/';
          sub_filter '/luna/' '/jms/luna/';
          sub_filter '/koko/' '/jms/koko/';
          sub_filter '/lion' '/jms/lion/';
          sub_filter '/media/' '/jms/media/';
          sub_filter '/omnidb/' '/jms/omnidb/';
          sub_filter '/player/' '/jms/player';
          sub_filter '/theme/' '/jms/theme/';
          sub_filter '/ui/assets/' '/jms/ui/assets/';
      }
      location /koko {
          proxy_pass http://10.64.34.5:4325;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_request_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_ignore_client_abort on;
          proxy_connect_timeout 600;
          proxy_send_timeout 600;
          proxy_read_timeout 600;
          send_timeout 6000;
      }
`

解决/koko/connect请求404问题

**Comment by Venurs** [comment]
`
location /koko {
    proxy_pass http://127.0.0.1:4325;
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
}`
nginx增加以上配置解决/koko/connect请求404问题
