### ISSUE TITLE
[Bug] 账号模板里，未开启mfa，在日志中也可以看到明文密码

### ISSUE THREAD

**Issue by yourenyouyu** [jumpserver/jumpserver#9855]
<img width="851" alt="image" src="https://user-images.githubusercontent.com/13463500/222891278-39694636-5e80-430e-ba44-c97276c4b035.png">

**Comment by ibuler** [comment]
收到尽快处理

**Comment by O-Jiangweidong** [comment]
@yourenyouyu 麻烦说下复现步骤，我们本地密码是脱敏了的
<img width="1059" alt="图片" src="https://user-images.githubusercontent.com/80373698/223654207-ebe7ef8c-ab07-4fe0-b8cb-2a07ab64f7a7.png">

**Comment by O-Jiangweidong** [comment]
已解决

**Comment by yourenyouyu** [comment]
好的，到时候我看下
