### ISSUE TITLE
[Bug] web远程应用报错

### ISSUE THREAD

**Issue by cross10** [jumpserver/jumpserver#9857]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.3-amd64

**浏览器版本**
Microsoft Edge
版本 110.0.1587.57 (正式版本) (64 位)

**Bug 描述**
web远程应用配置完成后无法使用，提示：Core API 发生错误

**Bug 重现步骤(有截图更好)**
1. 创建应用发布机并部署（API 服务填的是jms的web地址，服务器上并没有8080端口开放）
![image](https://user-images.githubusercontent.com/35590219/222940699-f3e191a1-4e9c-47de-bedb-000aa1c89c65.png)

![image](https://user-images.githubusercontent.com/35590219/222940149-b1ddb6e6-eada-4ba7-a484-b9540236ca37.png)
2. 发布远程应用
![image](https://user-images.githubusercontent.com/35590219/222940259-164ee30d-9d5c-4679-8914-c13df4ea2367.png)
3. 创建website资产(web是个python3的http模块起的下载列表页面，填的账号是应用发布机的登陆账号，不知道是不是应该填其他的账号？)
![image](https://user-images.githubusercontent.com/35590219/222940338-05fa086b-b347-4679-b811-d5343cd2bf12.png)
4.  添加资产权限
5. 从web终端选中创建的website资产，提示：Core API 发生错误
![image](https://user-images.githubusercontent.com/35590219/222940170-67b11c82-7037-4f8c-b778-b419c2da4014.png)

![image](https://user-images.githubusercontent.com/35590219/222940531-99916970-5c01-4248-a872-2909c6f4f57e.png)

**Comment by wojiushixiaobai** [comment]
看 lion 组件的日志
```sh
docker logs -f jms_lion --tail 200
```

**Comment by cross10** [comment]
日志如下

`[GIN] 2023/03/06 - 08:55:30 | 200 |      35.107µs |       127.0.0.1 | GET      "/lion/health/"
[GIN] 2023/03/06 - 08:55:32 | 200 |   28.935361ms |     192.168.3.8 | GET      "/lion/connect/?token=798892e9-c130-4df0-b358-58ee52205be4"
2023-03-06 08:55:32 tunnel server.go [ERROR] Create token session err: connect API core err: POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}
[GIN] 2023/03/06 - 08:55:32 | 400 |  202.120734ms |     192.168.3.8 | POST     "/lion/api/session"
[GIN] 2023/03/06 - 08:55:40 | 200 |      34.095µs |       127.0.0.1 | GET      "/lion/health/"
[GIN] 2023/03/06 - 08:55:43 | 200 |   35.572026ms |     192.168.3.8 | GET      "/lion/connect/?token=e52cd86d-798f-4858-aa7d-8bf168f386c9"
2023-03-06 08:55:44 tunnel server.go [ERROR] Create token session err: connect API core err: POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}
[GIN] 2023/03/06 - 08:55:44 | 400 |  457.955507ms |     192.168.3.8 | POST     "/lion/api/session"
[GIN] 2023/03/06 - 08:55:50 | 200 |      36.872µs |       127.0.0.1 | GET      "/lion/health/"`

![image](https://user-images.githubusercontent.com/35590219/222996987-ba28f83b-245d-4abe-aa6d-544d72cca126.png)

**Comment by wojiushixiaobai** [comment]
根据提示，你没正确授权账号，检查下你的授权规则，账号那栏填的什么，可以勾选 - [ ] 所有账号试试

**Comment by sparkry** [comment]
我也是同样的问题，提示：Core API 发生错误，账号授权admin账号，还是提示  POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}

**Comment by cross10** [comment]
我好像发现问题所在了，我的这台win远程应用发布机加域了，用没有加域的机器就可以正常授权

**Comment by cross10** [comment]
> 我也是同样的问题，提示：Core API 发生错误，账号授权admin账号，还是提示 POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}

你的发布机加域了吗？   试试把域去掉

**Comment by sparkry** [comment]
> 

我的服务器没有加域

> > 我也是同样的问题，提示：Core API 发生错误，账号授权admin账号，还是提示 POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}
> 
> 你的发布机加域了吗？ 试试把域去掉

**Comment by sparkry** [comment]
> 

我的服务器没有加域

> > 我也是同样的问题，提示：Core API 发生错误，账号授权admin账号，还是提示 POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}
> 
> 你的发布机加域了吗？ 试试把域去掉

**Comment by cross10** [comment]
我是用iso镜像重装了一台win服务器，然后就没问题了

> > 
> 
> 我的服务器没有加域
> 
> > > 我也是同样的问题，提示：Core API 发生错误，账号授权admin账号，还是提示 POST http://core:8080/api/v1/authentication/super-connection-token/applet-option/ failed, get code: 400, {"error":"No host account available"}
> > 
> > 
> > 你的发布机加域了吗？ 试试把域去掉
