### ISSUE TITLE
[Question] 双机部署v2.28.7测试资产可连接性会显示 ... 字符

### ISSUE THREAD

**Issue by opcache** [jumpserver/jumpserver#9858]
**请描述您的问题.**
双机部署v2.28.7测试资产可连接性会卡住，这个是什么地方问题？怎么解决
[
![cc20230306101631](https://user-images.githubusercontent.com/39149378/223004441-b0ae73bf-1b24-45a8-b4c8-64b85eae3e1f.png)
](url)

**Comment by wojiushixiaobai** [comment]
需要使用 nfs 或者其他文件共享工具把 core/data 目录共享

**Comment by opcache** [comment]
> 需要使用 nfs 或者其他文件共享工具把 core/data 目录共享

这个目录那没办法高可用？可以放OSS之类的吗？主要节点不在同一个区域

**Comment by BaiJiangJie** [comment]
这是由于 Celery 执行在 A 节点，查看日志的时候访问到了 B 节点，Celery 日志存放在了主机的目录下，

比如 B 节点的目录中没有这个日志文件，页面就会显示`...`，遇到这样的情况，用户一般是使用 NFS 共享 core/data 目录。

目前不支持 OSS 存储。

将来会考虑新增一个 `文件管理服务` 来解决类似这样的问题，但是目前还没有提上开发日程。
