### ISSUE TITLE
jumpserver部署在内网，无法访问公网，是否可以设置代理？

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#986]
[简述你的问题]

##### 使用版本
0.3.2

##### 具体表现
生产环境使用，应用部署在内网，无法直接访问公网，目前发现发送邮件有问题。
请问是否可以设置 proxy ？

[注:] 完成后请关闭 issue

**Comment by liuzheng** [comment]
还未做该功能，将来会做的
