### ISSUE TITLE
[Feature] v3.* 版本建议恢复原右击选项卡的 “文件管理” 按钮

### ISSUE THREAD

**Issue by sigboom** [jumpserver/jumpserver#9860]
v3.* 版本 web 终端页面建议恢复原右击选项卡的 “文件管理” 按钮，可以快速进行 sftp 连接
![image](https://user-images.githubusercontent.com/34954447/223015589-0107f5ec-a8e5-4fff-ad44-1158df961e98.png)
对应生成页签希望和原有 ssh 标题有区分度，加上文字描述或者其他

**Comment by sanpichen** [comment]
附议。
按照新版本的这个用法，好麻烦，特别是当我们使用了：记住密码，下次自动登录 后，会导致使用sftp后再次进入的时候又要再勾选回来。
