### ISSUE TITLE
[Feature] vnc连接错误提示优化建议

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [jumpserver/jumpserver#9862]
**请描述您的需求或者改进建议.**
在使用vnc访问windows的时候，密码错误的情况下，连接的错误提示是“网络不可达｜安全策略错误”，不便于排查，希望优化下错误提示。（注：v2、v3版本都存在同样问题）

**Comment by ibuler** [comment]
这个尝试过了，guacamole server 没有太明确的错误返回信息

**Comment by BaiJiangJie** [comment]
Lion 组件再调研一下，看看能不能通过返回的字符串信息把已知的错误匹配出来。 @LeeEirc

**Comment by BaiJiangJie** [comment]
rdp 会话返回的错误信息还多一些，vnc 会话没有返回详细的错误信息。

所以我们的连接页面页显示不出来。
