### ISSUE TITLE
[Bug] 通过web登录Linux资产显示无权限，但是通过ssh可以正常登录

### ISSUE THREAD

**Issue by qianshijinshen** [jumpserver/jumpserver#9864]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.3

**浏览器版本**
Chrome 
版本 110.0.5481.178（正式版本） （64 位）

**Bug 描述**
通过web登录Linux资产显示无权限，但是通过ssh可以正常登录

**Bug 重现步骤(有截图更好)**
1.从2.25.2版本升级到3.0.3，测试登录Linux资产时提示没有权限。通过ssh测试登录可以正常登录
2.删除资产下的账户重新添加、删除Linux资产重新添加、删除授权重新授权均无效。
3.

**Comment by Yansre** [comment]
是不是自定义角色，3.0好像移除了角色，使用默认角色就可以了

**Comment by qianshijinshen** [comment]
没有用自定义角色，角色是组织用户/西戎管理员，船舰用户的时候都是默认的&nbsp;


堕落金刚
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 晚上10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jumpserver/jumpserver] [Bug] 通过web登录Linux资产显示无权限，但是通过ssh可以正常登录 (Issue #9864)





 
是不是自定义角色，3.0好像移除了角色，使用默认角色就可以了

**Comment by qianshijinshen** [comment]
![K2_)X(`01F7`T7$}PF5OE~N](https://user-images.githubusercontent.com/48887652/223317905-56392e05-4456-4e39-82da-0d8ae2a737ff.png)

**Comment by qianshijinshen** [comment]
![K2_)X(`01F7`T7$}PF5OE~N](https://user-images.githubusercontent.com/48887652/223317964-44e2c1d9-cf53-4ea8-b05a-47364c8b253a.png)
请求这个地址报错了
