### ISSUE TITLE
[Bug] v3 网页访问luna 登录机器慢,资源请求耗时长

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9866]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/31802195/223366704-723a8b12-83e1-4e04-b154-92a2dc1d7c30.png">
<img width="993" alt="image" src="https://user-images.githubusercontent.com/31802195/223367374-693b3d18-443b-47fe-a3c2-a2671c8431c0.png">

详细信息见https://github.com/jumpserver/jumpserver/issues/9832

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ibuler** [comment]
静态 js 速度主要由网络决定吧

**Comment by mrsdpz** [comment]
问题是为什么每次登录一个机器都要请求一次这些资源
