### ISSUE TITLE
jumpserver 3.0获取账号模板接口需要mfa认证可以取消吗？

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [jumpserver/jumpserver#9868]
我在调用接口更新资产的账号，我的思路是，创建账号模板（ssh key），我通过接口读取私钥，然后给assets_assets的accounts字段中传递对应的私钥，以此来更新资产的账号。
我调用 /api/v1/accounts/account-template-secrets/{id}/时，需要mfa的那个码，感觉代码难以实现，可以把接口获取secrets的mfa限制去掉吗？

**Comment by wojiushixiaobai** [comment]
- https://docs.jumpserver.org/zh/v3/guide/env/

```
SECURITY_VIEW_AUTH_NEED_MFA=True         # 查看或导出密码，需要 MFA
```
