### ISSUE TITLE
[Bug] 3.03版本windows不能登录

### ISSUE THREAD

**Issue by harbour015** [jumpserver/jumpserver#9869]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.03

**浏览器版本**
edge

**Bug 描述**
添加windows7的资产，然后再添加账号，登录时，看不到添加的账号。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/48000268/223600215-a56b0531-47ef-4df5-beb9-e3e9090fc4a3.png)

2.
![image](https://user-images.githubusercontent.com/48000268/223600306-a882675f-3802-451e-ba1d-58debb13597e.png)

**Comment by wojiushixiaobai** [comment]
授权里面正确授权账号

**Comment by harbour015** [comment]
尴尬了，是我的问题，不是bug
