### ISSUE TITLE
0.5.0 ldap未生效

### ISSUE THREAD

**Issue by vlingfu** [jumpserver/jumpserver#987]
[简述你的问题]
5.0 web界面配置ldap，测试已经通过如图，已经提交并重启了服务。但是使用ldap账号无法登录, ldap账号确认没有问题。日志没有报错。 请问如何解决？
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. [步骤1]
![image](https://user-images.githubusercontent.com/35830275/35619449-0fb6333a-06b9-11e8-9832-4138787f8766.png)

[注:] 完成后请关闭 issue

**Comment by simplezhang615** [comment]
0.5.0版本，同样通过测试无法使用，但不同的是第一次登录成功后，修改映射属性就无法登录

**Comment by simplezhang615** [comment]
过滤规则有问题，更新到最新版本试试

**Comment by colinlabs** [comment]
+1 测试通过，也能获取到用户，但是使用用户无法登陆，用户OU: (uid=%(user)s)

**Comment by ibuler** [comment]
fixed，请更新，忘记这个页面的启用ldap选项
