### ISSUE TITLE
[Feature] 远程应用website URL状态栏隐藏

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#9873]
**请描述您的需求或者改进建议.**
v2支持配置将远程应用chrome的url栏隐藏，这样避免用户去修改；
v3没有地方修改，将url栏隐藏，最好是默认，或者通过配置手动选择隐藏。
![image](https://user-images.githubusercontent.com/66759501/223610861-aea5e3cb-0e1b-4a2d-89cf-3c89275ec286.png)

**Comment by ibuler** [comment]
这样可能会造成安全问题，比如 有人伪造了一个网站和银行页面很像，你输入后就被钓鱼了

**Comment by jstbw** [comment]
，，，内部使用，而且是管理员配置的website。如果不能支持url栏隐藏，那用户不就能通过website随意访问了嘛，之前通过chrome加参数隐藏地址栏。那按照上面你的说法，可不可以锁定地址栏，用户可以看到url，但是不能修改，但这样实现起来比单纯的隐藏url地址栏工作量大多了应该

**Comment by wojiushixiaobai** [comment]
审计就是为了便于事后溯源，安全需要多方面工作的结合，我们理解你的担心，但是目前我们认为让用户知道自己在什么地方做什么操作这个比较重要。

后续如果确实需要，我们可以通过增加参数来进行控制，由管理员决定是否开放。

**Comment by ibuler** [comment]
后面增加一个选项，是否显示地址栏，想想是全局的还是单个资产的

**Comment by BaiJiangJie** [comment]
v3.4 版本会支持隐藏地址栏。 @jstbw
