### ISSUE TITLE
[Feature] 修改ftp路径

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#9878]
**请描述您的需求或者改进建议.**
之前不能灵活的修改ftp路径也就忍了，现在ftp路径绑定在平台中？自带的不能修改，还必须得克隆创建再修改，在v2版本之上反向升级？

**Comment by wojiushixiaobai** [comment]
改了逻辑，账号不再跟之前的版本一样有其他属性。
使用的习惯变了

**Comment by jstbw** [comment]
那看看能不能调研优化一下ftp路径修改方式，现在的太隐藏了，而且灵活度太低，不光是使用习惯的问题了

**Comment by ibuler** [comment]
不能
