### ISSUE TITLE
[Bug] 使用标签endpoint选择端点，连接时提示undefined

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9879]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.3

**浏览器版本**

**Bug 描述**
使用标签endpoint选择端点，连接时提示undefined

**Bug 重现步骤(有截图更好)**
配置资产标签
![image](https://user-images.githubusercontent.com/14314203/223618488-4f8be10d-fd49-4ffe-8642-a985bf15e19b.png)
终端设置
![image](https://user-images.githubusercontent.com/14314203/223618551-d0df4c0d-22a3-4db6-84aa-d655ea5f3a95.png)
连接提示
![image](https://user-images.githubusercontent.com/14314203/223618590-323ea6a5-48ab-4f58-8c07-e53f25163393.png)

**Comment by mjwtc0722** [comment]
这个问题v3.1.0没有修复

**Comment by BaiJiangJie** [comment]
好的，我们来复现一下。

**Comment by BaiJiangJie** [comment]
服务端点**Database**是这个IP，当前访问站点使用的是什么地址呢？（浏览器地址栏的地址）
 
<img width="1860" alt="image" src="https://user-images.githubusercontent.com/32935519/228819409-51468531-1c51-4a54-86de-acb667a59a44.png">

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/releases/tag/v3.3.1

v3.3.1 版本修复了。

<img width="953" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/abe5c45a-af32-42ca-9422-3adba2b7785f">
