### ISSUE TITLE
AES key must be either 16, 24, or 32 bytes long

### ISSUE THREAD

**Issue by liyehaha** [jumpserver/jumpserver#988]
[简述你的问题]

##### 使用版本
0.3.2

##### 问题复现步骤
1. 添加资产

##### 具体表现

Request Method: | POST
-- | --
http://127.0.0.1/jasset/asset/add/
1.6
ValueError
AES key must be either 16, 24, or 32 bytes long
/opt/jumpserver/jumpserver/api.py in encrypt, line 213
/bin/python
2.7.5
['/opt/jumpserver',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib64/python2.7/site-packages/gtk-2.0',  '/usr/lib/python2.7/site-packages']
Thu, 1 Feb 2018 13:18:45 +0800

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed
