### ISSUE TITLE
jumpserver 3.03通过接口更新资产，传递了account的version，但是不生效，导致账号无法更新

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [jumpserver/jumpserver#9885]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.03

**浏览器版本**
chrome 版本 110.0.5481.104（正式版本） （64 位）

**Bug 描述**
接口：/assets/assets/ （PUT）
通过该接口更新资产并添加一个account，摘取部分代码，accounts字段的值如下：
`'accounts': [{'name': templ['name'], 'username': templ['username'], 'version': 12, 'secret_type': {'value': 'ssh_key', 'label': 'SSH 密钥'}, 'secret': templ_secret, 'privileged': True}],`

**Bug 重现步骤(有截图更好)**
1. 将jumpserver上所有账号全部删完，第一次调用接口，能跑通，且添加了账号，但是查看数据库accounts_account表，version的值为0
2.将上述代码中accounts字段中的version改为13，第二次调用接口，报“{"error": "Server internal error"}”，查看数据库accounts_account表，账号的version值依然为0

另外，我不传递version，数据库中的version字段也为0

我猜测是不是因为version没有修改到，导致我更新assets报错？

**Comment by ibuler** [comment]
Version字段暂时不起作用

**Comment by zhegeshijiehuiyouai** [comment]
那么第二次调用接口，报“{"error": "Server internal error"}”，是为什么呢？

**Comment by BaiJiangJie** [comment]
应该是 API 调用的不对，如果要更新账号的信息，使用下面的 API：

/api/v1/accounts/accounts/账号ID/

比如：

PATCH /api/v1/accounts/accounts/19be5e27-beb8-40e7-bbf3-92546995c463/

{
   "secret": ""
}

**Comment by BaiJiangJie** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/32935519/228818495-dfea7ca6-3dfb-4636-844e-18b86c268921.png">

**Comment by BaiJiangJie** [comment]
资产 API 中添加账号的信息，只在创建资产时生效。

如果更新账号的信息，调用账号的 API 进行操作，就不能再调用资产的 API 了。
