### ISSUE TITLE
[Bug] luna 静态文件文件重复请求导致页面响应慢

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9888]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

 v3.0.0
**浏览器版本**

**Bug 描述**
<img width="687" alt="image" src="https://user-images.githubusercontent.com/31802195/223640524-88506e82-e8ab-47c2-8857-ec3ca02ac9ad.png">
网页端登录机器为什么每次登录机器都要请求这一批静态文件?难道不应该第一次请求就行了吗?

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ibuler** [comment]
现在访问 koko 是用的 iframe，看看浏览器有没有开启 cache，就不用每次都加载 css 了

**Comment by mrsdpz** [comment]
没有禁用缓存, 你们可以测试一下

**Comment by ibuler** [comment]
每次 url 都不一样，好像不会使用缓存

**Comment by maninhill** [comment]
构建时，是不是可以把这些 css js 合并起来，压缩成一个？

**Comment by mrsdpz** [comment]
> 

挺影响用户体验的,希望能优化一下

**Comment by ibuler** [comment]
下个版本优化完成，增加缓存

**Comment by LeeEirc** [comment]
#9832

**Comment by LeeEirc** [comment]
v3.1 已经更新，有问题再反馈。
