### ISSUE TITLE
[Question] 资产连接测试失败

### ISSUE THREAD

**Issue by isyekong** [jumpserver/jumpserver#9890]
![image](https://user-images.githubusercontent.com/20068143/223664202-a4bf653d-742b-4d78-a844-45290d528013.png)

您好，快速安装后添加资产出现如图错误

**Comment by isyekong** [comment]
更新一次之后，使用的是 IP 连接
![image](https://user-images.githubusercontent.com/20068143/223664690-f63b6d71-61ba-4d4b-89b6-464423de9a17.png)

**Comment by wojiushixiaobai** [comment]
> 更新一次之后，使用的是 IP 连接 ![image](https://user-images.githubusercontent.com/20068143/223664690-f63b6d71-61ba-4d4b-89b6-464423de9a17.png)

网络有问题，无法正确解析你资产的主机名或者 IP 地址

**Comment by isyekong** [comment]
您好，感谢回复
网络是正常的，经过测试写IP也会相同报错，使用系统自带的检测工具可以ping
![image](https://user-images.githubusercontent.com/20068143/223941376-5a7df6e3-9fbc-4b4e-ad1f-0ed51c4a77d6.png)

有什么排查思路吗

**Comment by BaiJiangJie** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/32935519/228816933-a31b0dd8-b3ef-4fc9-81e0-154f27321af9.png">

config.txt 中开启 Debug 模式（ DEBUG=true）后重启服务。

在页面上执行一次测试可连接性，然后查看图片中的 hosts.json 文件内容。

看日志是文件内容格式有问题，没有正常解析出目标资产。

**Comment by BaiJiangJie** [comment]
升级到最新版本试一下。
