### ISSUE TITLE
[Question] 3.0.3 远程应用调用 Core API 发生错误

### ISSUE THREAD

**Issue by jangrui** [jumpserver/jumpserver#9891]
运行环境：Kubernetes v1.24.2
部署方式：helm

![image](https://user-images.githubusercontent.com/5895682/223669038-87ac68ed-26e9-476b-81d3-12c4a4c2ff38.png)
![image](https://user-images.githubusercontent.com/5895682/223670003-625e4dcd-e202-41e8-bbfa-9ea9bb61b872.png)

**Comment by LeeEirc** [comment]
看下发布机上的账号列表，以 `jms_ ` 开头的账号是否都正常激活？

**Comment by jangrui** [comment]
> 看下发布机上的账号列表，以 `jms_ ` 开头的账号是否都正常激活？

![image](https://user-images.githubusercontent.com/5895682/223671290-77e19bb1-a561-470d-80a7-17e51cac9a30.png)

**Comment by jangrui** [comment]
> > 看下发布机上的账号列表，以 `jms_ ` 开头的账号是否都正常激活？
> 
> ![image](https://user-images.githubusercontent.com/5895682/223671290-77e19bb1-a561-470d-80a7-17e51cac9a30.png)

@LeeEirc 删除发布机重新添加一遍，ok 了。
