### ISSUE TITLE
[Feature] 不能指定系统用户

### ISSUE THREAD

**Issue by huabuxiang** [jumpserver/jumpserver#9894]
**请描述您的需求或者改进建议.**目前用的版本是V3.0.3 同一个资源不同不通用户，不能指定某个账户，适用那个系统用户登入

**Comment by ibuler** [comment]
产品上做了更改，已不存在系统用户概念，现在一个资产上添加的账号，用户名和类型是不可以重复的，所以是按照账号的用户名进行授权的

**Comment by huabuxiang** [comment]
比方说我这个资产上有二个账户，系统管理员，运维人员，我怎么授权登入这台资源的是运维人员账户？

**Comment by ibuler** [comment]
选择运维用户和用户组，账号那选择运维账号的用户名

**Comment by huabuxiang** [comment]
目前这个功能很不好用，比如说我运维组里有几台资源，每台资源的账户不同的，授权应该每台资源指定不同的账户登入，现在这个版本不行

**Comment by ibuler** [comment]
可以换个思路，重新体会一下新版本的设计，系统用户不会再回来了

**Comment by huabuxiang** [comment]
> 可以换个思路，重新体会一下新版本的设计，系统用户不会再回来了

从用户体验角度来说，这个新的设计，不符合人们常规操作
