### ISSUE TITLE
[Bug] 通过jumpserver往windows资产上传输文件不显示进度

### ISSUE THREAD

**Issue by ryswork1993** [jumpserver/jumpserver#9895]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
通过jumpserver往windows资产上传输文件不显示进度

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/44529247/223901826-c1b61bfd-d219-42e7-9d80-59eae8583381.png)

2.
3.

**Comment by LeeEirc** [comment]
如果文件名携带了路径字符斜杠 ` / `，可能会上传失败。

**Comment by BaiJiangJie** [comment]
带 / 和 \ 的文件名，上传时都会转为 _ 字符。

<img width="613" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/24a887a7-3700-4f3b-85c6-f9fd56c0b35f">
<img width="276" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/5b06c7d4-54d7-4ceb-aaa3-73c902c6585f">
