### ISSUE TITLE
[Bug] 账号模版使用带密码的SSH密钥时，主机资产无法添加此账户模版

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9899]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.3

**浏览器版本**

**Bug 描述**
账号模版使用带密码的SSH密钥时，主机资产无法添加此账户模版。无密码的SSH密钥的账号模板没有此问题。
两个请求中，带密码的SSH密钥使用POST  /api/v1/accounts/accounts/ 请求中ssh_key_fingerprint的值为空（可能是这个问题）
"secret_type":{"value":"ssh_key","label":"SSH 密钥"},"spec_info":{"ssh_key_fingerprint":""}

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by feng626** [comment]
下一个小版本解决

**Comment by mjwtc0722** [comment]
此问题已在v3.1.0修复
