### ISSUE TITLE
[Question] 数据库MySQL8客户端连接是否支持

### ISSUE THREAD

**Issue by karlleecn** [jumpserver/jumpserver#9906]
**请描述您的问题.**
数据库是MySQL8.0.26，使用web cli连接可以正常连接和使用，使用客户端方式连接会报错，根据客户端连接提供的连接信息使用Navicat连接时报错“2013 - Lost connection to MySQL server during query”,使用DBeaver连接时无论使用哪个版本的驱动都报错“Got packets out of order”，使用客户端方式提供的命令行连接时，可以连接，但执行任何命令都会报错“ERROR 1156 (08S01): Got packets out of order
No connection. Trying to reconnect...”，请问是当前版本不支持客户端方式连接MySQL8吗？

**Comment by Aaron3S** [comment]
您好 提供下当前使用的 jumpserver 版本？

**Comment by karlleecn** [comment]
版本是3.0.4

> 您好 提供下当前使用的 jumpserver 版本？

**Comment by Aaron3S** [comment]
我们本地复现一下试试

**Comment by Aaron3S** [comment]
我这边没有复现 8.0.26可以正常连接，您加我微信，我帮您看下 tel: 17610225326

**Comment by Aaron3S** [comment]
问题已经确认，当录入资产时没有提供 数据库 字段时，且当前数据库中不存在 mysql 数据库，会导致无法连接， 主动指定 数据库 可以解决当前问题。
