### ISSUE TITLE
[Bug] jumpserver 3.03  移除组织用户后再邀请并修改角色为组织管理员，邀请成功后角色身份依然是组织用户

### ISSUE THREAD

**Issue by liufei20151013** [jumpserver/jumpserver#9909]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.3

**浏览器版本**
chrome

**Bug 描述**
移除组织中的一个用户，该用户为组织用户角色；
重新邀请该用户，并修改角色为组织管理员；
邀请成功后，角色身份依然是组织用户。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/15103510/223987722-1e5a796b-200c-4fa6-9be8-67da775ee932.png)

2.
![image](https://user-images.githubusercontent.com/15103510/223987932-b9a29397-7a08-46a9-8415-e740252ca01f.png)

3.
![image](https://user-images.githubusercontent.com/15103510/223987722-1e5a796b-200c-4fa6-9be8-67da775ee932.png)

**Comment by feng626** [comment]
我这环境没有复现，进交流群问问其他人
