### ISSUE TITLE
0.5.0-2 硬件信息识别中的model字段

### ISSUE THREAD

**Issue by qiushaohu** [jumpserver/jumpserver#991]
[简述你的问题]
在硬件信息获取过程中，model字段获取的是ansible_product_version参数值，经与资产管理员讨论，觉得该字段取ansible_product_name可能会更有意义。 特此，建议将此字段修改为取值ansible_product_name

##### 使用版本
0.5.0-2

##### 具体表现
![image](https://user-images.githubusercontent.com/34025457/35721705-34a8cf7e-082e-11e8-99c6-55ddb3ab6d69.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
已改
