### ISSUE TITLE
[Bug] 使用带密码的SSH密钥的账号，无法登录

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9912]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.3

**浏览器版本**

**Bug 描述**
使用带密码的SSH密钥的账号，无法登录

**Bug 重现步骤(有截图更好)**
1. 
2.
3.

**Comment by LeeEirc** [comment]
有具体的报错信息吗？

**Comment by mjwtc0722** [comment]
![image](https://user-images.githubusercontent.com/14314203/224558819-332a3ecf-5028-412a-8def-0ae5c9f6b447.png)
报错就是用户密码不对，但是我确认过，这个密钥key和密码是正确的

**Comment by LeeEirc** [comment]
如果是升级上来的私钥，可以再手动更新下私钥试一试？使用非带密码的SSH密钥，可正常连接吗？

**Comment by mjwtc0722** [comment]
> 

手动更新过了，没有用。不带密码的密钥是可以用的

**Comment by LeeEirc** [comment]
已修复，等下个版本更新。

**Comment by LeeEirc** [comment]
#9958

**Comment by LeeEirc** [comment]
v3.1.0 已发版，有问题可提新 issue。
