### ISSUE TITLE
0.5.0版本是否取消了对交换机的支持

### ISSUE THREAD

**Issue by simplezhang615** [jumpserver/jumpserver#992]
[简述你的问题]
0.5.0版本是否取消了对交换机的支持？tasks任务无法对交换机正确检测，资产中也取消了硬件类型字段
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0

![image](https://user-images.githubusercontent.com/36071491/35767688-ef464b24-092b-11e8-8a92-1ddbc8ad0067.png)
![image](https://user-images.githubusercontent.com/36071491/35767694-16515a24-092c-11e8-8302-f563cbe12215.png)

![image](https://user-images.githubusercontent.com/36071491/35767698-3ed6fe4a-092c-11e8-8ea0-15c019bc1014.png)

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
支持交换机，交换机上没有python环境，所以请添加一个已知账号密码的系统用户
