### ISSUE TITLE
[Bug] windows 测试可连接线需要 ssh

### ISSUE THREAD

**Issue by 0xorOne** [jumpserver/jumpserver#9920]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.04

**浏览器版本**

chrome 110.0.5481.178
**Bug 描述**

设置资产是windows-RDP，协议和端口也是rdp和3389，但是测试的时候访问的却是22
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/125463022/224354857-42a54727-0da1-4943-9c89-757e15dddea8.png)
![image](https://user-images.githubusercontent.com/125463022/224354991-32f6d084-a119-4328-9bbd-1568caf7457d.png)

**Comment by ibuler** [comment]
现在测试 windows 连接性，依赖 windows ansible ssh

**Comment by 0xorOne** [comment]
请问这个在哪个版本是能用的

**Comment by 0xorOne** [comment]
或者说有什么方法正常使用吗

**Comment by ibuler** [comment]
现在测试可连接线，需要添加 ssh，windows 上安装上 ssh，或者等待未来更新

**Comment by ibuler** [comment]
我们研究一下命令行的可行方法

```

#!/bin/bash

# 定义变量
host="<Windows 主机 IP 地址>"
username="<Windows 用户名>"
password="<Windows 密码>"

# 测试连接
if xfreerdp /u:"$username" /p:"$password" /v:"$host" +clipboard +fonts +aero +window-drag; then
  echo "连接成功！"
else
  echo "连接失败！"
fi
```

**Comment by BaiJiangJie** [comment]
测试可连接性 v3.4 会支持不需要安装 OpenSSH 服务。https://github.com/jumpserver/jumpserver/pull/10602

但是对于一些推送、改密任务，还是需要的。

**Comment by yuwenchiu** [comment]
> 测试可连接性 v3.4 会支持不需要安装 OpenSSH 服务。#10602
> 
> 但是对于一些推送、改密任务，还是需要的。

請問這個改動是否還沒發佈，什麼時候會發佈呢？

**Comment by BaiJiangJie** [comment]
已发布，更新一下最新版本。

**Comment by BaiJiangJie** [comment]
已发布，更新一下最新版本。
