### ISSUE TITLE
[Bug] RDP资产入口输入错误的用户名密码且选中自动登录后，重复提示错误无法正常登录。

### ISSUE THREAD

**Issue by haitao127** [jumpserver/jumpserver#9922]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.4

**浏览器版本**
Edge 110

**Bug 描述**
密码策略为手动输入时，用户登录RDP选中“自动登录”，但是输错密码后，每次打开该界面直接提示错误，无法重新输入密码。

**Bug 重现步骤(有截图更好)**
1.用户登录Jumpserver工作台；
2.从资产列表中进入RDP资产的终端入口；
3.输入错误的用户名和密码；
4.选中“自动登录”；
5.点击确认。

**Comment by ibuler** [comment]
右击重新连接，自动时有那个提示

**Comment by haitao127** [comment]
这样啊，谢谢啦，找到喽，麻烦了。。。
