### ISSUE TITLE
[Question] 集群部署异地灾备 mysql 哪些表不同步？

### ISSUE THREAD

**Issue by mrsdpz** [jumpserver/jumpserver#9923]
**请描述您的问题.**
我在阿里云 A 区集群部署了一套 jumpserver ，使用的mysql es oss 都在阿里云 A 区，我们想在阿里云 B 部署一个 jumpserver做冷备，起了一个新的 mysql 同步 A 区 mysql 的数据，同时在 B 起新的 es oss 供jumpserver 使用，我们目前 mysql 的同步排除了 terminal 开头的表，发现 koko 起不来。
我在本地模拟了这一过程，清空了terminal开头的表，报错如下：
2023/03/13 11:30:48 &{Name:[KoKo]-Arthron.local CoreHost:http://127.0.0.1:8060 BootstrapToken:dsafdsf BindHost:0.0.0.0 SSHPort:2222 HTTPPort:5001 SSHTimeout:15 LogLevel:INFO Comment:KOKO LanguageCode:zh UploadFailedReplay:true AssetLoadPolicy: ZipMaxSize:1024M ZipTmpPath:/tmp ClientAliveInterval:30 RetryAliveCountMax:3 ShowHiddenFile:false ReuseConnection:true ShareRoomType:local RedisHost:127.0.0.1 RedisPort:6379 RedisPassword: RedisDBIndex:0 RedisClusters:[] RedisSentinelPassword: RedisSentinelHosts: RedisUseSSL:false EnableLocalPortForward:false EnableVscodeSupport:false RootPath:/Users/arthron/code/koko DataFolderPath:/Users/arthron/code/koko/data LogDirPath:/Users/arthron/code/koko/data/logs KeyFolderPath:/Users/arthron/code/koko/data/keys AccessKeyFilePath:/Users/arthron/code/koko/data/keys/.access_key ReplayFolderPath:/Users/arthron/code/koko/data/replays CertsFolderPath:/Users/arthron/code/koko/data/certs}
2023-03-13 11:30:48 [INFO] Exchange share room type: local
FATA[0002] GET http://127.0.0.1:8060/api/v1/terminal/terminals/config/ failed, get code: 404, {"detail":"用户对象不存在","code":"object_does_not_exist"} 
Exiting.

https://github.com/jumpserver/koko/blob/28e4f3f0690dd7daac0d2c2ba4a19aee21638e47/pkg/jms-sdk-go/service/register.go#L43  此处报错
请问做异地灾备的话，mysql 哪些表不需要同步

**Comment by mrsdpz** [comment]
v3.0.0版本

**Comment by ibuler** [comment]
所有表都需要同步

**Comment by mrsdpz** [comment]
> 

像配置录像配置的 oss 信息、命令存储的 es 配置，这些东西两个区域用的不是同一个，明显不用同步需要重新配置，terminal 信息两个区域也不一样，这个也不用吧

**Comment by ibuler** [comment]
同步配置，不同 terminal 使用不同配置

**Comment by mrsdpz** [comment]
> 

terminal_replaystorage 这张表中的 default 存储配置中的 meta 是如何生成的?
跨机房部署的冷备jumpserver 节点同步了主 jumpserver 集群的配置后, koko 出现以下报错:
2023-03-14 11:25:52 [ERRO] Session[bdb07c67-64d2-428d-b717-e92c3f00c68a] user read err: io: read/write on closed pipe
2023-03-14 11:27:05 [ERRO] Session[771b7b91-9228-421a-9f75-008f5e83d770] srv read err: EOF
2023-03-14 11:27:05 [ERRO] Session[771b7b91-9228-421a-9f75-008f5e83d770] user read err: io: read/write on closed pipe
同时登录退出机器会卡顿
本地开发环境篡改default 的 meta 项亦能复现以上报错,我该如何解决?或者如何生成对应机器上的/opt/jumpserver 下的默认replaystorage的配置?

**Comment by BaiJiangJie** [comment]
你的使用方式有问题，按照下面的操作配置一下：

1. 保证两个集群的数据库表数据一致（必须）
2. 在系统设置-终端设置-录像存储/命令存储，分别创建 A、B群集中的 oss 和 es 。
3. 在系统设置-终端设置-终端管理，分别更新 A、B 集群的 KoKo 终端，分别设置对应的 oss 和 es 存储。
