### ISSUE TITLE
[Question] SSH终端连接后，资产信息过长，无法展示完整字段信息

### ISSUE THREAD

**Issue by KaguraRui** [jumpserver/jumpserver#9929]
**请描述您的问题.**
SSH终端连接后，资产信息过长，无法展示完整字段，如下：
![image](https://user-images.githubusercontent.com/127723557/224645613-f5593769-76bc-4cf3-8971-115523876831.png)
如何解决类似显示问题？

**Comment by LeeEirc** [comment]
这个是自动截断，以适应终端大小，可以手动调整终端大小，显示更多。

**Comment by testfredsu** [comment]
可以不要一些欄位嗎? 如果可以該怎麼設置呢?

**Comment by KaguraRui** [comment]
> 这个是自动截断，以适应终端大小，可以手动调整终端大小，显示更多。

可能是内容太多了，终端调整后还是会被截断，能否指定义显示的列呢？比如说指定名称&ip

**Comment by testfredsu** [comment]
> > 这个是自动截断，以适应终端大小，可以手动调整终端大小，显示更多。
> 
> 可能是内容太多了，终端调整后还是会被截断，能否指定义显示的列呢？比如说指定名称&ip

我也想知道

**Comment by LeeEirc** [comment]
暂不支持自定义配置。
