### ISSUE TITLE
登录到服务器时vim中文显示乱码

### ISSUE THREAD

**Issue by jiangping20160209** [jumpserver/jumpserver#993]
[简述你的问题]

##### 使用版本
Jumpserver版本 0.3.2

##### 问题复现步骤
1. [ssh直接登录服务器]
![image](https://github.com/jiangping20160209/daemon/blob/master/ssh%E7%9B%B4%E6%8E%A5%E7%99%BB%E5%BD%95.bmp)
2. [jumpserver登录]
![image](https://github.com/jiangping20160209/daemon/blob/master/jumpserver%E7%99%BB%E5%BD%95.bmp)
##### 具体表现[截图可能会更好些,最好能截全]
jumpserverl登录服务器，vim查看文件是显示中文乱码 
如果通过ssh直接连接服务器可以正常显示中文

**Comment by liuzheng** [comment]
请使用新版本
