### ISSUE TITLE
[Question] 可以導出 不能導入

### ISSUE THREAD

**Issue by testfredsu** [jumpserver/jumpserver#9934]
V3.0.4我看文章都有導出和導入按鈕 但是我只能導出沒有導入 請問是哪問題呢

![image](https://user-images.githubusercontent.com/79911609/224694266-870b48bb-7b87-43e5-a808-3eb9cb5234f4.png)

**Comment by KeitaroDPVF** [comment]
选择右边的【主机】【网络设备】才有导入。【所有】页面是没有导入功能的。

**Comment by ibuler** [comment]
所有页面，包含了很多类型的资产，数据结构也不相同，所以禁用了

**Comment by testfredsu** [comment]
好的 謝謝大家
