### ISSUE TITLE
[Bug] 升级至V3.0.4之后，仪表盘存在断图

### ISSUE THREAD

**Issue by liuhryme** [jumpserver/jumpserver#9935]
**Bug 描述**
升级至V3.0.4之后，仪表盘-用户/资产活跃情况，存在断图，截图如下：

![image](https://user-images.githubusercontent.com/12726017/224873138-b91f05f1-5cfa-4e37-9733-3296917861ff.png)

**Comment by ibuler** [comment]
小问题，暂时忽略吧
