### ISSUE TITLE
[Feature] 使用CAS接入后，使用ssh 无法用密码的方式登陆

### ISSUE THREAD

**Issue by liuhryme** [jumpserver/jumpserver#9936]
**请描述您的需求或者改进建议.**
使用CAS接入后，使用ssh 无法用密码或者密码+token的方式登陆

**Comment by liuhryme** [comment]
终端ssh登录是不是不支持cas登录。 这个选项开启和关闭都一样 密码登录失败/

**Comment by O-Jiangweidong** [comment]
CAS登录不支持终端ssh登录的，本地用户支持，如果想要cas用户登录ssh终端，可以使用临时密码功能进行登录使用

config.txt 中添加 AUTH_TEMP_TOKEN=true ，重启服务开启功能
在个人界面复制即可使用
<img width="826" alt="图片" src="https://user-images.githubusercontent.com/80373698/225244886-8fbe35f3-67c2-4445-bc95-d45e80f23aba.png">

**Comment by BaiJiangJie** [comment]
对的，CAS 属于页面跳转认证方式。

如果使用 SSH 终端登录，需要使用临时密码功能。
