### ISSUE TITLE
[Bug] 资产删除后，资产树的数量与实际资产数量不一致

### ISSUE THREAD

**Issue by KaguraRui** [jumpserver/jumpserver#9938]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
资产删除后，资产树的数量与实际资产数量不一致。

**Bug 重现步骤(有截图更好)**
1.实际资产已经删除了，资产信息也看不到了，但是资产树刷新后，还存在已删除的资产数量
2.
![image](https://user-images.githubusercontent.com/127723557/224884911-bc8908d7-edf3-440b-a295-bb7c1f67660c.png)

**Comment by BaiJiangJie** [comment]
<img width="325" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/37d6d17f-7f2c-4c2f-acb3-6a3fbf88ace3">

右击校对资产数量。
