### ISSUE TITLE
能不能出一个使用文档，描述后台功能如何使用

### ISSUE THREAD

**Issue by TesKO666** [jumpserver/jumpserver#994]
[简述你的问题]
能不能出一个使用文档，描述后台功能如何使用
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
能不能出一个使用文档，搭建按照文档描述都可以完成，但是里面的内置功能最好有一个使用手册，不是每一个使用者都是运维或者研发，更多的可能是运营等其他角色。

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@TesKO666 https://github.com/jumpserver/jumpserver/wiki/v0.5.0-应用图解

**Comment by ifreesec** [comment]
我表示那个 GIF 图看的很懵逼，建议改成视频，不然像想清楚的看某一步这种操作很浪费时间，一秒就闪过了，又得从头看，表示很伤心

**Comment by TesKO666** [comment]
over
