### ISSUE TITLE
[Bug] 通过vnc登录CentOS后，无法选中文件编辑器中的文本内容。

### ISSUE THREAD

**Issue by haitao127** [jumpserver/jumpserver#9941]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.4

**浏览器版本**
Edge/Safari/Firefox

**Bug 描述**
通过vnc登录CentOS后，无法选中文件编辑器中的文本内容，但是登录Ubuntu系统后，可以选中。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/12413287/224897781-96297a19-bdeb-4bb2-9ea4-57a678c6dc6b.png)

**Comment by ibuler** [comment]
这应该和本身软件有关系，和堡垒关系不大

**Comment by haitao127** [comment]
> 这应该和本身软件有关系，和堡垒关系不大

但是在CentOS 7.9(2009)本机或者通过VNC Viewer/Remmina客户端连接使用的时候，没有这个现象，通过JumpServer就出现了。
然后又把TigerVNC替换成了RealVNC Server，也是一样的现象。
gedit和terminal中都是这个情况。

**Comment by haitao127** [comment]
各种办法尝试失败，重装了CentOS系统后，居然正常了，但是还是不明确问题所在。。。
