### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9944]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.4

**浏览器版本**
MacOS 13.0.1 （M1）+ Chrome 111.0.5563.64

**Bug 描述**
web资产无法连接

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/14314203/224921899-727a192e-5be5-4b29-9076-a8753e9ecc45.png)

**Comment by LeeEirc** [comment]
需要 设置-远程应用-应用发布机 添加发布机，并部署之后，才可以使用。
