### ISSUE TITLE
[v3.0 同一账号用户名不能通过不同账号名称来区分] 

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#9945]
**请描述您的需求或者改进建议.**
描述：
v3.0 账号的用户名是唯一的，如果系统中已经添加了root账号，如果在使用账号切换功能（sudo  su - ）会报错，用户名冲突
![image](https://user-images.githubusercontent.com/43403764/224926310-47763223-893d-474f-a256-b0413604cfdb.png)

建议：可以通过账号名称来区分同一用户名（v2.0是可以的）

**Comment by wojiushixiaobai** [comment]
v3 同名账号只允许有一个
