### ISSUE TITLE
jumpserver没有ansible和上传下载文件选项

### ISSUE THREAD

**Issue by wspd2004** [jumpserver/jumpserver#995]
jumpserver没有ansible和上传下载文件选项

##### 使用版本
jumpserver 0.5.0

##### 问题复现步骤
部署完成后没有ansible和上传下载文件选项
是否没完成，还是我安装有问题，如果是 没完成，是否低版本的已完成，
我能去哪里下载低版本的jumpserver

**Comment by Debris2017** [comment]
将来会有，因为这个功能带来一些安全问题,目前没开放出来。需呀上传和下载的功能可以去用0.3.

**Comment by Kisen-Chin** [comment]
@Debris2017 hi， 想问下：
需呀上传和下载的功能可以去用0.3.
这个版本是哪个版本？ 在release里没看到有0.3这个版本啊
