### ISSUE TITLE
[Question] 不健康原因

### ISSUE THREAD

**Issue by testfredsu** [jumpserver/jumpserver#9950]
![image](https://user-images.githubusercontent.com/79911609/225027845-57d7db94-a723-4158-a453-a10f2b94fffb.png)

跟著找到相關檔案 docker-compose-task.yml:    container_name: jms_celery

檔案內容如下 其中找不著這隻sh  /opt/jumpserver/utils/check_celery.sh

請問是我的安裝哪邊有問題嗎

version: '2.4'

services:
  celery:
    image: jumpserver/core:${VERSION}
    container_name: jms_celery
    ulimits:
      core: 0
    restart: always
    tty: true
    command: start task
    depends_on:
      core:
        condition: service_healthy
    env_file:
      - ${CONFIG_FILE}
    healthcheck:
      test: "bash /opt/jumpserver/utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ${VOLUME_DIR}/core/data:/opt/jumpserver/data
      - ${VOLUME_DIR}/core/logs:/opt/jumpserver/logs
    networks:
      - net
~

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/jumpserver/blob/dev/utils/check_celery.sh

该文件存放在容器里面
不健康的原因请查看日志
```bash
docker exec -it jms_celery bash
cd logs
# 查看 celery 开头的相关日志
```

**Comment by BaiJiangJie** [comment]
升级到最新 v3 版本再看看服务，如果还有问题，请重新打开 Issue。
