### ISSUE TITLE
[Question] 关于新版本V3安装之后，使用网域进行连接资产会卡住的问题

### ISSUE THREAD

**Issue by wlzscn** [jumpserver/jumpserver#9952]
**请描述您的问题.**

您好：
在更新到V3版本之后，远程连接资产会遇到卡住的问题，需要重新登录才可以，旧版本使用过程中没有遇到过。
资产是使用网域的模式进行连接，每个网域设置了两个网关，而且使用过程中也会产生卡顿的情况，不知道是不是网络原因造成的呢？

**Comment by wojiushixiaobai** [comment]
卡顿是指什么卡顿？连接慢可以尝试检查 SSH USEDNS 的设置

**Comment by wlzscn** [comment]
您好：

   卡住的情况类似于下图，在进行到这个位置无法进行，直接卡住，需要重新连接才可以。windows桌面也是直接卡在了操作页面，没有任何反应，需要重新连接。



***@***.***
 
发件人： 吴小白
发送时间： 2023-03-15 17:30
收件人： jumpserver/jumpserver
抄送： wlzscn; Author
主题： Re: [jumpserver/jumpserver] [Question] 关于新版本V3安装之后，使用网域进行连接资产会卡住的问题 (Issue #9952)
卡顿是指什么卡顿？连接慢可以尝试检查 SSH USEDNS 的设置

**Comment by LeeEirc** [comment]
这种应该是网络问题。可以直连某一个资产测试卡不卡？

**Comment by BaiJiangJie** [comment]
升级到最新版本试一下，如果还有问题，再打开 issue。
