### ISSUE TITLE
[Question] 3.0.4 文件管理功能无法使用了

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#9953]
**请描述您的问题.**
版本：3.0.4

通过文件管理无法连接到目标服务器（LINUX系统）
有为该服务器配置:手工输入、用户模板中名称为"USER“的空密码用户

![图片](https://user-images.githubusercontent.com/38068938/225187046-fe3cfdc8-bec3-4b52-b91d-1f1e80828d5d.png)

直接通过资产树连接功能则能连接到
![图片](https://user-images.githubusercontent.com/38068938/225186803-ca398ae5-ccb7-4fd2-b295-d52d84d1401c.png)
![图片](https://user-images.githubusercontent.com/38068938/225187616-b8f81bf3-c548-49f0-a558-f7fee7abcfd8.png)

请问文件管理功能要怎么用？难道还要配置设置好密码的用户？是不是应该也能弹出用户/密码窗口而我不会？

**Comment by wojiushixiaobai** [comment]
勾选不生效问题请尝试更新至 v3.1.0 后看看问题是否解决

**Comment by BaiJiangJie** [comment]
v3.4 版本已经修复。
