### ISSUE TITLE
[Question] 客户端拉不起来

### ISSUE THREAD

**Issue by sanpichen** [jumpserver/jumpserver#9955]
**请描述您的问题.**
一直拉不起客户端
使用的是docker部署的V3.0.4 

win10操作系统。
chrom、firefox、edge都是过，
有提示我是否允许，通过后无反应。
是被系统什么东西拦了吗，还要开什么权限？

![图片](https://user-images.githubusercontent.com/38068938/225191079-7f642a3f-c779-4f75-af9c-833301a3b784.png)

![图片](https://user-images.githubusercontent.com/38068938/225190560-1c928762-3f4b-4c95-b08f-ea6e90d397b7.png)

**Comment by jym503558564** [comment]
拉起的包是最新的吗？jumpserver-client-windows-x86_64.msi

**Comment by wojiushixiaobai** [comment]
重启下浏览器或者重启下电脑

**Comment by sanpichen** [comment]
chrom 版本 111.0.5563.65
实际已经安装过客户端了


会弹出这个
![图片](https://user-images.githubusercontent.com/38068938/225862979-bbe1b198-8350-488f-9ff3-8e5deba089cf.png)

**Comment by feng626** [comment]
只有ssh拉起不好使么？进入client的安装目录看看有没有putty

**Comment by BaiJiangJie** [comment]
暂时看不出是什么原因导致的，需要远程你的电脑看一下路径的配置。

如果你在社区交流群里可以直接 @wojiushixiaobai 来帮你看一下。

**Comment by BaiJiangJie** [comment]
升级最新版本试试。
