### ISSUE TITLE
创建用户组后不显示

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#996]
[简述你的问题]

##### 使用版本
[0.5.0-2 GPLv2]

##### 问题复现步骤
![jms](https://user-images.githubusercontent.com/9443696/35795660-ccd215c2-0a94-11e8-9a85-46ddcdbbf7cc.png)

**Comment by wojiushixiaobai** [comment]
信息填写要完整。

**Comment by ibuler** [comment]
未能复现

**Comment by qianghong000** [comment]
记不清楚了  升级以后还不行吗
