### ISSUE TITLE
[Question] koko打包问题咨询

### ISSUE THREAD

**Issue by wangheng0206** [jumpserver/jumpserver#9961]
rawkubectl是怎么打包生成的
![image](https://user-images.githubusercontent.com/106153788/225221556-3526ef58-5cb8-444b-95fb-68b483b0c519.png)
![image](https://user-images.githubusercontent.com/106153788/225221632-2b000147-92be-4b30-95ca-824bdba67a8a.png)

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/koko/blob/dev/Dockerfile#L28

参考 Dockerfile，这是下载的二进制文件
