### ISSUE TITLE
[Question] Web应用登录，HTTP Basic如何自动认证

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9962]
Web应用开启了Basic的认证方式，如何配置Web远程应用不需要输入用户名密码即可登录

**Comment by wojiushixiaobai** [comment]
https://username:password@www.example.com/

**Comment by mjwtc0722** [comment]
不能这样，提示格式错误，校验要改一下。另外这个方式密码是明文的，不太合适
![image](https://user-images.githubusercontent.com/14314203/225282077-ad0a3136-1d20-4a0b-87fb-d358ebc7a084.png)

**Comment by mjwtc0722** [comment]
v3.1.0修复了URL中不能使用https://username:password@www.example.com/的问题，但是这样的话用户可以看到明文的用户名密码，希望还是通过账号资产的方式配置

**Comment by ibuler** [comment]
目前不支持，会泄露账号密码
