### ISSUE TITLE
[Question] 远程应用DBeaver如何不检查版本更新

### ISSUE THREAD

**Issue by mjwtc0722** [jumpserver/jumpserver#9964]
![image](https://user-images.githubusercontent.com/14314203/225228620-171561f2-6fbc-4759-9253-b8abc0fc492f.png)

**Comment by O-Jiangweidong** [comment]
点击窗体(Window) -> 首选项(Preferences) -> 用户界面(User Interface) -> 自动检查更新(Automatic updates check)
![图片](https://user-images.githubusercontent.com/80373698/225241358-8d271763-1005-4c87-b932-5b8e98469162.png)
![图片](https://user-images.githubusercontent.com/80373698/225241366-c7210934-9498-4a85-abd4-d619d26724ea.png)

**Comment by ibuler** [comment]
这个能默认不检查吗

**Comment by mjwtc0722** [comment]
这个好像是没有用的，因为这个配置是针对用户的，如果用另外一个用户登录依然会先检查版本更新。另外离线驱动也是一样的问题

**Comment by O-Jiangweidong** [comment]
我们调研看看

**Comment by mjwtc0722** [comment]
这个问题能改进吗？

**Comment by O-Jiangweidong** [comment]
> 这个问题能改进吗？

可以的，会在近期的版本中进行优化
