### ISSUE TITLE
[Bug] - English Translation issue

### ISSUE THREAD

**Issue by controlom** [jumpserver/jumpserver#9965]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
Version 3.0.0

**浏览器版本**
Chrome and all browser

**Bug 描述**
English Translation issue

**Bug 重现步骤(有截图更好)**
1. Sometimes we have English translation issues and the wording is not in English but in Chinese 
2. We can see this issue in many areas, connection panels or in some error messages. 

how can we move this to English?

![image](https://user-images.githubusercontent.com/22157928/225228853-4b8f9ca8-4dbe-401b-8340-aa73bce3549a.png)

**Comment by jym503558564** [comment]
Thanks for the feedback, we will fix this issue。
