### ISSUE TITLE
[Bug] 录像回放无法准确拉动进度条，JumpServer播放器也是

### ISSUE THREAD

**Issue by jstbw** [jumpserver/jumpserver#9972]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
录像审计，在线播放录像进度条无法拖动，或拖动不准确。下载录像文件到JumpServer播放器（最新）上也是一样。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/66759501/225273625-c78ee059-be63-410c-9efb-cf3909ba56ed.png)
进度条无法z准确定位
![image](https://user-images.githubusercontent.com/66759501/225273380-eefb07e1-e9a0-48af-aed9-bab75fc17805.png)
无快进

**Comment by wojiushixiaobai** [comment]
收到，我们会持续优化。

**Comment by BaiJiangJie** [comment]
最新版本支持 mp4 格式的录像，拖动播放不是问题了。
