### ISSUE TITLE
如何关闭或则配置定时测试任务

### ISSUE THREAD

**Issue by 291723286** [jumpserver/jumpserver#998]
[简述你的问题]

##### 使用版本
0.5.0

##### 其他
如何关闭或配置定时测试管理用户，系统用户的可连接性。机器多的情况下很占用带宽，很卡。

**Comment by sinerxx** [comment]
ecs主机 2核4G卡到不行

**Comment by wojiushixiaobai** [comment]
23333....局域网都这么惨吗老哥。

**Comment by ibuler** [comment]
暂时没有办法，只能修改代码
