### ISSUE TITLE
[Bug] 升级v3后，无法将批量资产指定管理员，只能每个资产点开再选择管理员

### ISSUE THREAD

**Issue by blpzeng** [jumpserver/jumpserver#9980]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.0.4

**浏览器版本**

Microsoft Edge
版本 111.0.1661.41 (正式版本) (64 位)

Chrome
版本 110.0.5481.177（正式版本） （64 位）
 
**Bug 描述**
1、升级v3后，无法将批量资产指定管理员，只能每个资产点开再选择管理员，希望能恢复此功能。
2、在V2时是支持的；

**Bug 重现步骤(有截图更好)**

![QQ截图20230315195338](https://user-images.githubusercontent.com/127950235/225302300-e656d4a6-355d-40d7-818b-f9d4793b5efb.jpg)
![QQ截图20230315195527](https://user-images.githubusercontent.com/127950235/225302307-c2745f1e-7bc6-462f-8fd5-e616c18c5408.jpg)

**Comment by wojiushixiaobai** [comment]
收到，我们看看是否能够进行优化。

**Comment by blpzeng** [comment]
谢谢，期待下一个版本有更新，这个还是非常实用的功能。

**Comment by blpzeng** [comment]
我目前用的3.0.4，账号及账号模板里无法关联资产。

本周末升级后试试。

Thanks&Best Regards.
==============================
Zeng LingPing
