### ISSUE TITLE
[Question] 账号改密有sudo权限的账号改密失败

### ISSUE THREAD

**Issue by LinuxLeader** [jumpserver/jumpserver#9985]
**请描述您的问题.**
V3版本账号改密功能只能是root么？测试有sudo权限特权账号改密会失败，如果sudo特权用户排序在root上面，也会失败
![image](https://user-images.githubusercontent.com/43403764/225513363-b18a46e3-f846-44a6-9418-dc0e3e6d2327.png)
这种情况会报权限不够

**Comment by BaiJiangJie** [comment]
最新版本修复了，更新升级一下试试。
