### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by gaochangshui** [jumpserver/jumpserver#9986]
对于 有的 windows server 2008 文件上传后，在windows 系统上 找不到 download 文件夹
这个情况 是需要什么设定吗

![image](https://user-images.githubusercontent.com/77267700/225520636-fbc14649-5f7b-4d26-95cc-97804cd3a592.png)

**Comment by wojiushixiaobai** [comment]
正常通过 `mstsc` 命令挂载共享盘可以在远端显示吗？检查下

**Comment by BaiJiangJie** [comment]
正常部署完应该是没问题可以显示的，升级到最新版本再试试。

如果有问题再重新打开 issue。
