### ISSUE TITLE
[Feature] 客户端连接支持使用mysql_safe方式启动的mysql

### ISSUE THREAD

**Issue by karlleecn** [jumpserver/jumpserver#9989]
**请描述您的需求或者改进建议.**
我们当前MySQL启动方式都是mysql_safe，mysql版本8.0.26，使用jumpserver连接时，其中web cli方式连接没有问题，但使用客户端方式连接时就会报错，测试过当使用非mysql_safe方式启动的MySQL服务，jumpserver可以正常连接。对于mysql_safe方式启动的MySQL，咱们下个版本的数据库客户端连接方式是否可以支持连接。

**Comment by ibuler** [comment]
3.1修复，已发版

**Comment by BaiJiangJie** [comment]
升级到最新版本试一下。
