### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AlenxHai** [jumpserver/jumpserver#9992]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.1.0

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/29483702/225787068-41c1dcad-7bb2-4259-aea1-0c238dc83b81.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wojiushixiaobai** [comment]
警告非错误，请忽略
