### ISSUE TITLE
web终端哪里，linux窗口发送文本到所有终端是否可以把窗口设置为上下拉大] 

### ISSUE THREAD

**Issue by cxs5168** [jumpserver/jumpserver#9994]
建议web终端linux访问时，最下方的“发送文本到所有终端”可以设置大一点。能让用户自己更改更好。谢谢。

**Comment by cxs5168** [comment]
![image](https://user-images.githubusercontent.com/116624038/225812846-94c7cb87-498e-4fce-afee-b54006c2fc7b.png)

**Comment by cxs5168** [comment]
如上图红线标识的那个地方，很小，不方便复制粘贴。

**Comment by ibuler** [comment]
和左侧高度对齐的，目前没有计划更改

**Comment by cxs5168** [comment]
好吧，谢谢。
