### ISSUE TITLE
connect websocket server error[Bug] 

### ISSUE THREAD

**Issue by qweuorncjd** [jumpserver/jumpserver#9995]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v2.28.1

http://10.5.0.13:30080/ui/#/ops/celery/task/f7497fe5-d0cd-4dc2-b003-497ec531764a/log?type=celery

**Comment by wojiushixiaobai** [comment]
Check that the celery component is working properly.

**Comment by BaiJiangJie** [comment]
全部重启一下服务。
