### ISSUE TITLE
[Feature] 建议平台不要强制绑定ssh协议

### ISSUE THREAD

**Issue by mrbaiwei** [jumpserver/jumpserver#9997]
![image](https://user-images.githubusercontent.com/16459219/225848240-2691ad85-c84c-4aa5-b272-dac73031135d.png)
导入资产时收到错误，平台设置那里也无法调整，由于部分设备仅提供了telnet协议登录，建议只要是允许的协议之一即可

**Comment by wojiushixiaobai** [comment]
请新建平台

**Comment by ibuler** [comment]
打算做了，锁定那个协议，平台上可以配置

**Comment by ibuler** [comment]
![image](https://user-images.githubusercontent.com/17382885/226556630-6a6dacbf-a2b5-4a49-b6dc-add66adf6387.png)

**Comment by ibuler** [comment]
3.2发布，先关闭了
