### ISSUE TITLE
[Bug] 客户端 AnotherRedisDesktopManager无法通过jumpserver连接Redis

### ISSUE THREAD

**Issue by alexchenx** [jumpserver/jumpserver#9998]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
Jumpserver v3.0.4

**浏览器版本**
Chrome 版本 110.0.5481.78（正式版本） （64 位）

**Bug 描述**
我现在用 Jumpserver v3.0.4，配置了2个redis，redis版本都是5.0.4.
 - A redis 没有设置密码
 - B redis 设置了密码

现在情况是：
如果使用Jumpserver Web CLI, 两个redis都可以正常连接；
如果使用客户端（AnotherRedisDesktopManager 1.5.9），A可以连接，B无法连接

**Bug 重现步骤(有截图更好)**
1. 搭建Redis A，版本为Redis 5.0.4, 不设置密码；
2. 搭建Redis B，版本为Redis 5.0.4, 设置密码123456；
3. 在Jumpserver添加这两个Redis；
4. 在Web终端测试通过Web CLI连接两个Redis，两个都可以连通；
5. 测试使用客户端AnotherRedisDesktopManager通过Jumpserver提供的连接信息连接Redis A，连接成功。
    连接信息处密码内容写入格式为：jump提供用户名@jump提供密码
    
![{06T(~Q_I(4B8OG_6ZB@6RG](https://user-images.githubusercontent.com/20258367/225852182-db6cb756-3cc5-4418-be12-600722e8fbe5.jpg)

6. 测试使用客户端AnotherRedisDesktopManager通过Jumpserver提供的连接信息连接Redis B，连接不成功。
   连接信息处密码内容写入格式为：jump提供用户名@jump提供密码  ，如第5步格式，保存后连接显示如下错误：
   
![9HSBFW`I T$2PBGOAC5V)2O](https://user-images.githubusercontent.com/20258367/225852625-8ffc8f59-79bd-4e31-a967-767847fcd206.jpg)

**Comment by Aaron3S** [comment]
我们复现处理一下。

**Comment by BaiJiangJie** [comment]
更新最最新版本试一下，对 redis 的用户名填写有优化。

redis 5 以下是没有用户名的，升级到最新版本，username 字段写为 null。

密码正常填写。

如果还有问题再重新打开 issue。
